### ISSUE TITLE
Invoke lambda locally fails

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#10]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Calling invoke fails:
```
$ amplify function invoke TestFunction Get /items
Using service: Lambda, provided by: awscloudformation
? Provide the name of the script file that contains your handler function: index.js
? Provide the name of the handler function to invoke: handler
>> Local Npm module "grunt-aws-lambda" not found. Is it installed?
Warning: Task "lambda_invoke" not found. Use --force to continue.

Aborted due to warnings.
```

I've tried to install the missing package in both the function and the angular application itelf. Still does not work.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I've been following the Angular guide to setup a basic application.

What is the expected behavior?
Execute the lambda function locally.

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
0.1.13

**Comment by kaustavghosh06** [comment]
Hey @jarrettj  , I was able to reproduce the issue and submitted a PR for the same -> https://github.com/aws-amplify/amplify-cli/pull/15/files 
I'll close the issue once we this change pushed to npm.

**Comment by jarrettj** [comment]
Awesome! Thanks man.

**Comment by kaustavghosh06** [comment]
The fix for this has been pushed tp NPM. You can update the CLI and feel free to re-open this issue if you find the fix stil not working.

**Comment by jarrettj** [comment]
Hi,

Good day.

Thanks for the push. Fixed this issue, will open a new issue on what happens now.

Regards.
