### ISSUE TITLE
@auth transforms wrong ownerField and identityField

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#100]
**Do you want to request a feature or report a bug?**

Bug

**Steps to reproduce the issue:**

Using the following schema:

```
type Note @model @auth(rules: [{allow: owner }]) @searchable{
   id: ID!
   note: String!
}
```

According to doc [https://github.com/aws-amplify/amplify-cli/blob/master/graphql-transform-tutorial.md](https://github.com/aws-amplify/amplify-cli/blob/master/graphql-transform-tutorial.md), this is equivalent to:

```
type Note @model @auth(rules: [{allow: owner, ownerField: "owner", identityField: "username" }]) @searchable{
   id: ID!
   note: String!
}
```

The generated file amplify/backend/api/amplifynotes/build/resolvers/Mutation.createNote.request contains the codes:

```
## START: Inject Ownership Information. **
#if( $util.isNullOrBlank($ctx.identity.username) )
$util.unauthorized()
#end
$util.qr($ctx.args.input.put("owner", $ctx.identity.username))
## END: Inject Ownership Information. **
```

When I changed the schema to:

```
type Note @model @auth(rules: [{allow: owner, ownerField: "userId", identityField: "sub" }]) @searchable{
   id: ID!
   note: String!
}
```
The generated build/resolvers/Mutation.createNote.request: 

```
## START: Inject Ownership Information. **
#if( $util.isNullOrBlank($ctx.identity.userId) )
$util.unauthorized()
#end
$util.qr($ctx.args.input.put("userId", $ctx.identity.userId))
## END: Inject Ownership Information. **
```

**What is the expected behavior?**

The generated build/resolvers/Mutation.createNote.request should be: 

```
## START: Inject Ownership Information. **
#if( $util.isNullOrBlank($ctx.identity.sub) )
$util.unauthorized()
#end
$util.qr($ctx.args.input.put("userId", $ctx.identity.sub))
## END: Inject Ownership Information. **
```

I'm using Mutation.createNote.request to illustrate the error. The error occurs to other resolvers as well.

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**

macOS
* **Output of ``amplify --version``**:

0.1.16

**Comment by mikeparisstuff** [comment]
This looks like a bug. I'll take a look and should have a fix soon.

**Comment by mikeparisstuff** [comment]
This was fixed by https://github.com/aws-amplify/amplify-cli/pull/115

**Comment by mikeparisstuff** [comment]
Sorry wrong link. It was fixed by this https://github.com/aws-amplify/amplify-cli/pull/63

**Comment by jaxondu** [comment]
Has the update been pushed? I just updated to amplify-cli 0.1.18 and repeat "amplify add api" and the result is worst. I am following the tutorial at https://medium.com/open-graphql/create-a-multiuser-graphql-crud-l-app-in-10-minutes-with-the-new-aws-amplify-cli-and-in-a-few-73aef3d49545.

`
$ amplify api add
? Please select from one of the below mentioned services GraphQL
? Provide API name: amnotes
? Choose an authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? true
? What best describes your project: 
? What best describes your project: Objects with fine-grained access control (e.g., a proj
ect management app with owner-based authorization)
? Do you want to edit the schema now? Yes
Please edit the file in your editor: /Users/Me/amplify/amnotes/amplify/backend/api/amnotes/schema.graphql
? Press enter to continue 
`

The schema used:

`
type Note 
    @model 
    @auth(rules: [
        {allow: owner, ownerField: "userId", identityField: "sub" }
    ]) 
{
   id: ID!
   note: String!
}
`

This is the resulted build/resolvers/Mutation.createNote.request

`## START: Prepare DynamoDB PutItem Request. **
$util.qr($context.args.input.put("createdAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("updatedAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("__typename", "Note"))
{
  "version": "2017-02-28",
  "operation": "PutItem",
  "key": {
      "id": {
          "S": "$util.autoId()"
    }
  },
  "attributeValues": $util.dynamodb.toMapValuesJson($context.args.input),
  "condition": {
      "expression": "attribute_not_exists(#id)",
      "expressionNames": {
          "#id": "id"
    }
  }
}
## END: Prepare DynamoDB PutItem Request. **
`

All the authentication inject ownership resolver codes are gone!!

**Comment by mikeparisstuff** [comment]
The issue was a undefined being interpreted as meaning the same null. You can get around this in the existing build by explicitly passing `mutations:[create,update,delete]` and `queries:[get,list]` to the `@auth` directive.

**Comment by kaustavghosh06** [comment]
We just published to npm with a fix for this. Please use the version -> 0.1.19.
Closing the issue, feel free to re-open if the issue persists.
