### ISSUE TITLE
Some override configuration for Storage/S3 not working on Amplify Console CI/CD builds

### ISSUE THREAD

**Issue by javiermartingonzalez** [aws-amplify/amplify-cli#10001]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.6.24

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

storage

### Amplify Commands

override

### Describe the bug

I have an override.ts file for storage on my Amplify to add `s3:putObjectAcl` permission to `s3AuthPublicPolicy`. It was working fine from 4 months but then with recently released Amplify update, it is not working anymore.

```
resources.s3AuthPublicPolicy.policyDocument.Statement = Object.assign(
        resources.s3AuthPublicPolicy.policyDocument.Statement, 
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
        }
    )
```

If I made the push with old Amplify version (v7.6.22), the permissions are correctly added to the IAM profile. Some days ago, with CI/CD builds it was working, too. But with new version of Amplify isn't working event with `--force` flag.

Also, the values correctly pushed with v7.6.22 are removed when CI/CD run. So now, my project is not able to upload any file to S3 due "Permission Denied" error because s3:putObjectAcl permission is not added for authRole.

### Expected behavior

 Take care of override.ts modifications for s3AuthPublicPolicy

### Reproduction steps

1. Create override storage
2. Add s3AuthPublicPolicy CDK changes adding new policy
3. Upload something with latest version but no taking care of that field

**Comment by ykethan** [comment]
Thank you for reaching out, on replication I was able to find that the statement is expecting an array while we are passing in an object. Could you please try the following.
```
resources.s3AuthPublicPolicy.policyDocument.Statement =  [
        ...resources.s3AuthPublicPolicy.policyDocument.Statement,
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
        }
    ]
```

**Comment by ykethan** [comment]
I understand that the type for `Statement` does shows "any" as the expected property but the cloudformation expects an array.
for type safety marking this as a bug.

**Comment by javiermartingonzalez** [comment]
> Thank you for reaching out, on replication I was able to find that the statement is expecting an array while we are passing in an object. Could you please try the following.
> 
> ```
> resources.s3AuthPublicPolicy.policyDocument.Statement =  [
>         ...resources.s3AuthPublicPolicy.policyDocument.Statement,
>         {
>             Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
>         }
>     ]
> ```

My code is the same as someone suggest me on #8894 . It was working but it starts to fail in the last Amplify version.

Also tested your code with no result: 

```
2022-03-17T01:03:53.362Z [INFO]: UPDATE_IN_PROGRESS          S3AuthPublicPolicy                                                       AWS::IAM::Policy           Thu Mar 17 2022 01:03:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_FAILED               S3AuthPublicPolicy                                                       AWS::IAM::Policy           Thu Mar 17 2022 01:03:50 GMT+0000 (Coordinated Universal Time) Syntax errors in policy. 
```

**Comment by ykethan** [comment]
Hello @javiermartingonzalez, on deeper investiagtion and replciation in my local amplify application I was able to use the following options in my override.

option 1: 

Using the override file to add permission to the existing policy.

```
resources.s3AuthPublicPolicy.policyDocument.Statement[0] = Object.assign(
        resources.s3AuthPublicPolicy.policyDocument.Statement[0], 
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
        }
    )
```

output in cloudformation under S3AuthPublicPolicy:

```
"PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:s3:::",
                      {
                        "Ref": "S3Bucket"
                      },
                      "/public/*"
                    ]
                  ]
                }
              ]
            }
          ]
        }
```

output in IAM:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::****/public/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```


option 2:

Using the override file to add permission by creating a new policy statement.

```
resources.s3AuthPublicPolicy.policyDocument.Statement =  [
        ...resources.s3AuthPublicPolicy.policyDocument.Statement,
        {
            "Effect": "Allow",
            "Action": [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"],
            "Resource": "*"
        }
    ]
```

output in cloudformation under S3AuthPublicPolicy:

```
"PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
              ],
              "Resource": "*"
            }
          ]
        }
```

output in IAM:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
additionally we can `...resources.s3AuthPublicPolicy.policyDocument.Statement,` to keep the existing policy and append with the above options.

Please do let me know if this helps. If in case the above options may not be for your use case, Could you please provide me some additional information on your use case.

**Comment by javiermartingonzalez** [comment]
Solved with option 1, thank you.

Same as I have before but adding the [0].

Something have changed in the newest version of Amplify.

Thanks!

**Comment by ykethan** [comment]
glad to hear we were able to mitigate the issue.
closing this for now. please do reach out to us again.

**Comment by benjamindoe** [comment]
I'm currently running into a similar issue. My override looks something like this
```ts

export function override(resources: AmplifyS3ResourceTemplate) {
  resources.s3AuthPublicPolicy.policyDocument.Statement[0] = {
    ...resources.s3AuthPublicPolicy.policyDocument.Statement[0],
    Action: [
      "s3:PutObjectAcl",
      "s3:PutObject",
      "s3:GetObject",
      "s3:DeleteObject",
    ],
  };
}
```

This gives a resulting IAM Policy within the authRole IAM role for Public_policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::<BUCKET_NAME_HERE>/public/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```


Uploading using the Storage Amplify API returns a 403 error while logged into the Amplify app
```js
await Storage.put(fileName, file, {
  contentType: file.type,
  level: "public",
  acl: "public-read",
});
```

Removing the line `acl: "public-read"` results in a successful upload but it means the files are not publicly accessible via a permanent URL.
