### ISSUE TITLE
Pluralization of models is not working as expected

### ISSUE THREAD

**Issue by christianguevara** [aws-amplify/amplify-cli#10009]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

7.6.24

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Pluralization is not working as expected, even when the flag `improvePluralization` is set to true.

This happened in some update between versions `7.6.13` and `7.6.24`:

**MemberGroupAccess**
Query:
'e' is removed incorrectly
<img width="375" alt="Screen Shot 2022-03-16 at 17 54 36" src="https://user-images.githubusercontent.com/10765364/158704504-447b31a1-98d9-4314-b5b7-88edee20ff5b.png">
Type:
```graphql
type MemberGroupAccess
  @model
  {
  id: ID!
  .....
}
```

**DealCategory**
Query:
'y' is replaced incorrectly
<img width="342" alt="Screen Shot 2022-03-16 at 17 53 44" src="https://user-images.githubusercontent.com/10765364/158704396-2da8f33d-a973-4e3e-ba5f-15c376767b21.png">
Type:
```graphql
type DealCategory
  @model
{
  id: ID!
  ....
}
```

**LeadOffers**
Query:
's' is added when it shouldn't
<img width="312" alt="Screen Shot 2022-03-16 at 17 53 59" src="https://user-images.githubusercontent.com/10765364/158704421-cbf9f40a-f0be-4923-8ef2-8fcbb7a8dda1.png">
Type:
```graphql
type LeadOffers
@model(subscriptions: null)
{
  id: ID!
  ....
}
```

### Expected behavior

Pluralization should work like before the update

### Reproduction steps

1. Create the types in 7.6.13
2. Make sure `improvePluralization` flag is set to true in `cli.json`
3. Push
4. Check pluralization is correct
5. Update amplify cli to latest (7.6.24)
6. Push
7. Check pluralization again

**Comment by christianguevara** [comment]
This is not graphql transformer v2, is "GraphQL transformer version: 1", sorry for the confusion

**Comment by ykethan** [comment]
Hello @christianguevara , Thank you for reaching out. I tried replicating using the instructions provided but was unable to reproduce the pluralization change with feature set as `true`, but observed this behavior with the flag set to `false` in the V1 transformer version.

Could you please set the `"improvepluralization": true` delete the `build` folder present in your `amplify/backend/api/<api name>` folder and run the following commands:

1. amplify api gql-compile
2. amplify codegen

Please do check the queries in the generated files and let us know if this helped. If in case the queries still show the incorrect plurals, could you please let us know if there are any additional steps that were taken in building the API.

**Comment by christianguevara** [comment]
Hi @ykethan it didn't worked, but you using "improvepluralization" all lowercase made me test more things and I found something.

In old versions of amplify inside the `cli.json` we had something like:

```json
{
  "features": {
    "graphQLTransformer": {
      "improvePluralization": true,
      "enableIterativeGsiUpdates": true
    },
    "auth": {
      "enableCaseInsensitivity": true,
      "breakCircularDependency": true
    },
    "project": {
      "overrides": true
    }
  }
}
```

After latest versions `cli.json` was updated to:

```json
{
  "features": {
    "graphQLTransformer": {
      "improvePluralization": true,
      "enableIterativeGsiUpdates": true
    },
    "auth": {
      "enableCaseInsensitivity": true,
      "breakCircularDependency": true
    },
    "project": {
      "overrides": true
    },
    "graphqltransformer": {
      "improvepluralization": true,
      "securityEnhancementNotification": false,
      "showfieldauthnotification": false
    }
  }
}

```

You can see CLI added a `graphqltransformer` prop in all lowercase different than the camelCase we were using before.
`improvePluralization` was not "migrated" and [DOCS](https://docs.amplify.aws/cli/reference/feature-flags/#improvePluralization) are not showing this change.

The solution was to include `"improvepluralization": "true"` all lowercase inside the new `graphqltransformer` prop.

Thanks for the help, we might have found a migration issue :)

**Comment by ykethan** [comment]
hi @christianguevara glad to hear that you were able to mitigate the issue, if I may ask what was the previous Amplify CLI version the application was utilizing. I understand that 7.6.13 was the version upgraded from but was there a different version being used before this.
