### ISSUE TITLE
amplify env add throws error

### ISSUE THREAD

**Issue by kyangy** [aws-amplify/amplify-cli#1001]
**Describe the bug**
Running `amplify env add` throws `TypeError: Cannot read property 'config' of undefined`

**To Reproduce**
1. amplify env add

**Expected behavior**
Should be able to create a new env

**Screenshots**
<img width="1440" alt="screen shot 2019-03-08 at 10 46 14 am" src="https://user-images.githubusercontent.com/9537888/54048745-7cb6e300-418f-11e9-8ec2-c2689fca8157.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.14.1

**Comment by kaustavghosh06** [comment]
@kyangy Do you have a `archive` key in your amplify/team-provider-info.json file?

**Comment by kyangy** [comment]
@kaustavghosh06 i do not

**Comment by kaustavghosh06** [comment]
How does your `amplify/.config/local-aws-info.json` file look like?

**Comment by kyangy** [comment]
ahh yes i do see the archive key in there

**Comment by kaustavghosh06** [comment]
You might want to remove that and give it a try again. Not sure how that got in.

**Comment by kyangy** [comment]
ok cool that worked! i did have the same archive env pushed previously but i terminated it. thanks! @kaustavghosh06
