### ISSUE TITLE
Lambda trigger for Dynamodb Stream, no option to select View type

### ISSUE THREAD

**Issue by mfirosPFT** [aws-amplify/amplify-cli#10010]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?** 
Adding trigger to DynamoDB 
**Amplify CLI Version**
7.6.23
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
DynamoDB, Lambda
**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Is there any way to select the View Type while adding a Lambda trigger to DynamoDB using CLI, it defaults to **New Image**, but my usecase is to have both **New Image and Old Image** selected. 
We can do this manually, but that breaks the whole point of using the same code for multiple env. 

Please suggest. Thank you. Attached a screenshot of what I am referring to in console

![screenshot-ap-south-1 console aws amazon com-2022 03 17-13_07_32](https://user-images.githubusercontent.com/95845849/158760047-8c175b4c-3197-4f61-84d8-bd3b2bab4b75.png)

Can we do something like this from CLI

![screenshot-ap-south-1 console aws amazon com-2022 03 17-13_12_18](https://user-images.githubusercontent.com/95845849/158760630-5af6ed7f-38af-4def-bfe7-8c81fae79a94.png)

**Comment by ykethan** [comment]
Hello @mfirosPFT, apologies for the delay in a response. When adding a storage using `amplify add storage` on latest version of the CLI, we can utilize the `amplify override storage` to override this attribute.

For example we can utilize the following code example.

```ts
export function override(resources: AmplifyDDBResourceTemplate) {
    resources.dynamoDBTable.streamSpecification["streamViewType"] = "New Image and Old Image";
}

```

**Comment by mfirosPFT** [comment]
awesome, thanks for the response.
