### ISSUE TITLE
feature flag doc for pluralization needs to be updated

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#10033]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.25

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

api

### Amplify Commands

init

### Describe the bug

Currently, the Amplify feature flag doc provides the `improvepluralization` with a camel case `improvePluralization`. needs to be updated with the correct syntax.
https://docs.amplify.aws/cli/reference/feature-flags/#improvePluralization

- reference: #10009 

### Expected behavior

set `improvePluralization` to `improvepluralization`

### Reproduction steps

none

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
@ykethan the flags are converted to lowercase when the file is [loaded](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli-core/src/feature-flags/featureFlagFileProvider.ts#L60), so this isn't a documentation issue.

**Comment by josefaidt** [comment]
Notes for docs update: should we perhaps list feature flags by name and show the value we'll see in `cli.json` as it appears?

- Improve Pluralization `improvepluralization`

**Comment by josefaidt** [comment]
NOTE: add callout to docs that feature flags are case-insensitive https://docs.amplify.aws/cli/reference/feature-flags/#feature-flags

**Comment by ykethan** [comment]
Closing as PR has been merged.
