### ISSUE TITLE
API put "AccessDeniedException" does not end catch

### ISSUE THREAD

**Issue by rozhali** [aws-amplify/amplify-cli#1003]
**Describe the bug**
API.put, getting "AccessDeniedException" error back but it is not ending up in the catch block

**To Reproduce**

`API.put(apiName, "/orders", myInit).then(response => {
                // Add your code here
                console.log("response: ", response);
                navigation.navigate("ConfirmReceipt");
            }).catch(error => {
                console.log("error.response from put: ", error.response)
                console.log("Navigate to error page");
            });`

**Expected behavior**
This should end up in the catch block and not the response.

**Screenshots**
![screen shot 2019-03-02 at 5 01 34 pm](https://user-images.githubusercontent.com/16752065/53689524-fde42500-3d0c-11e9-92d0-0162d3dc438d.png)

**Additional context**
This is a react native project, and the backend has been generated via the amplify CLI

**Comment by manueliglesias** [comment]
Transferred to cli. The lambda code needs to send an appropriate statusCode in the response.
