### ISSUE TITLE
Stuck - Fetching updates to backend environment: dev from the cloud.

### ISSUE THREAD

**Issue by stablefi** [aws-amplify/amplify-cli#10049]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

I want to deploy a react.js application with Amplify (eu-west-1). 

I could deploy it through a CICD with a GitHub (manual process). 

However, when I use the Amplify CLI to deploy the app, the process is not working (stuck on `amplify push`).

I am following literally the steps I mention.

### Expected behavior

I should deploy the application when I run: `amplify push`

### Reproduction steps

1. `npm install -g @aws-amplify/cli`
2. `npm aws-amplify`
3. `amplify configure` (It create programatic keys with AmplifyFullAdmin policy)
4. I create programatic keys with FullAdmin policy to the next step.
5. `amplify init`
6. `amplify push`

**Comment by ykethan** [comment]
Hello @stablefi, Thank you for reaching out. Apologies for the delay in a response. I tried to replicate the issue with the following steps.

1. created a react App.
2. `amplify configure`
3. Login and then create a user with Admin permissions.
4. Copied the Secret Access key and Access key ID.
5. pasted it in the Amplify CLI prompt.
6. Added a example resource and performed `amplify push`

on pushing my changes I was unable to see any errors or process being stuck on the push phase. Could you please let me if you are still experiencing issues with the push command.

**Comment by ykethan** [comment]
Hello @stablefi, following up on this issue. Please do let us know if you are facing any continued issues.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please do reach out to us again.
