### ISSUE TITLE
Delete application from aws 

### ISSUE THREAD

**Issue by damienfmx74** [aws-amplify/amplify-cli#10040]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

v7.6.25

### What operating system are you using?

Mac V11.6.5 Big sur

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

i have delete all AWS S3 compartiments on the console AWS, i have delete amplify of my project with amplify cli. 

### Amplify Categories

storage, hosting, Not applicable

### Amplify Commands

publish, pull

### Describe the bug

I want to delete the application from amplify, but an error appears : 
- ### Invoking remove all backends execution failed
I went back to the S3 compartment, and created an empty compartment with the same name as when I created the project. I made a copy of the amplify folder before deleting amplify from the project. 
after that i went back to the VScode project. and i reinstalled aws cli, and i tried to pull the application registered on aws. i choose -aws profile -> default key but i have this error: 
### Error downloading #current-cloud-backend.zip from deployment bucket: amplify-travelwebsite-dev-104849-deployment, the error is: The specified key does not exist.
it's impossible. I try to init amplify, same another error 
### Initializing your environment: devCould not initialize 'dev': The specified key does not exist.

i need help please ,I don't know what to do anymore

### Expected behavior

I hope to be able to pull the project so that I can properly remove the amplify application. i can't currently delete a project

### Reproduction steps

amplify pull --appId d2uuzr317tcvrq --envName dev
amplify init

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @damienfmx74 :wave: thanks for raising this! To clarify, were all s3 resources deleted via the console and we're wanting to use `amplify delete` to remove other resources (such as auth, functions) associated with the project?

**Comment by damienfmx74** [comment]
hi , <img width="1001" alt="Capture d’écran 2022-03-22 à 17 51 36" src="https://user-images.githubusercontent.com/45952066/159532971-f02c1abd-29b3-4cb2-8a84-be4f045c09a4.png">
i haven't s3 ressources, all are delete. and i can't delete application because of this I think.

**Comment by damienfmx74** [comment]
yes, I just made this request "aws amplify delete-app --app-id (id)", it works perfectly thanks
