### ISSUE TITLE
GraphQL override not working

### ISSUE THREAD

**Issue by maxludovicohofer** [aws-amplify/amplify-cli#10054]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Amplify Categories

storage, api

### Amplify Commands

override, push

### Describe the bug

The override file is not read as console logs are not printed to the screen during amplify push.

### Expected behavior

Should read the override file and apply the overrides.

### Reproduction steps

1. Create a graphQL API
2. Override the api
3. The override code: 
```typescript
import { AmplifyApiGraphQlResourceStackTemplate } from "@aws-amplify/cli-extensibility-helper";
import { ModelDirectiveStack } from "@aws-amplify/cli-extensibility-helper/lib/types/api/amplify-api-resource-stack-types";
import environment from "./overrideContext"; //? Generated from a pre-push hook

type Models =
  | "Task"
  | "Identity"
  | "User"
  | "Activity"
  | "Payment"
  | "Audit"
  | "Notification"
  | "Configuration";

export function override({ models }: AmplifyApiGraphQlResourceStackTemplate) {
  const { Task, Identity, User, Activity, Payment, Audit } = models as Partial<
    Record<Models, ModelDirectiveStack>
  >;

  if (environment === "usability") {
    prepareForExport(Task);
    prepareForExport(Identity);
    prepareForExport(User);
    prepareForExport(Activity);
    prepareForExport(Payment);
    prepareForExport(Audit);
  }
}

function prepareForExport(model?: ModelDirectiveStack) {
  if (model) {
    model.modelDDBTable.pointInTimeRecoverySpecification = {
      pointInTimeRecoveryEnabled: true,
    };
  }
}

```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @maxludovicohofer :wave: thanks for raising this! Unfortunately I was not able to reproduce by using a modified overrides file:

```ts
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper'
import { ModelDirectiveStack } from '@aws-amplify/cli-extensibility-helper/lib/types/api/amplify-api-resource-stack-types'
// import environment from './overrideContext' //? Generated from a pre-push hook

type Models = 'Todo'

export function override({ models }: AmplifyApiGraphQlResourceStackTemplate) {
  const { Todo } = models as Partial<Record<Models, ModelDirectiveStack>>

  // if (environment === 'usability') {
  prepareForExport(Todo)
  // }
}

function prepareForExport(model?: ModelDirectiveStack) {
  if (model) {
    model.modelDDBTable.pointInTimeRecoverySpecification = {
      pointInTimeRecoveryEnabled: true,
    }
  }
}
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/5033303/159779690-b035a06b-d11c-4907-a3ea-58e4d1f681ba.png">

Can you confirm whether the environment check is working as expected?
