### ISSUE TITLE
amplify pull command not working in latest Amplify CLI version - 7.6.26 

### ISSUE THREAD

**Issue by nileshordex** [aws-amplify/amplify-cli#10050]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

pull

### Describe the bug

Failed to pull the backend.
Invalid feature flag configuration

These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:
  - graphqltransformer.showfieldauthnotification

This issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.

Learn more about feature flags: https://docs.amplify.aws/cli/reference/feature-flags

### Expected behavior

Pick a backed environment in local.

### Reproduction steps

Follow the below setups...

1. amplify pull
2. Select the authentication method you want to use
3. accessKeyId
4. secretAccessKey
5. region
6. Which app are you working on?
7. Pick a backend environment

Above setups follow then got the error.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @nileshordex :wave: thanks for raising this! Unfortunately I was not able to reproduce using the provided steps, using both AWS Profile and AWS Access Keys and projects with and without the feature flag. Can you confirm you are running the latest version of the CLI with `amplify -v` and do you remember the last version of the CLI used on this project?

**Comment by JamieSlome** [comment]
@josefaidt - getting a similar issue here as well.

```
                                 # Starting phase: preBuild
                                 # Executing command: nvm use 16
2022-03-25T10:34:36.592Z [INFO]: Now using node v16.13.2 (npm v8.1.2)
2022-03-25T10:34:36.594Z [INFO]: # Executing command: envCache --set stackInfo ""
2022-03-25T10:34:36.601Z [INFO]: # Executing command: amplify -v
2022-03-25T10:34:57.559Z [INFO]: [31mInvalid feature flag configuration[39m
2022-03-25T10:34:57.561Z [INFO]: [31mThese feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:[39m
                                 [31m  - graphqltransformer.showfieldauthnotification[39m
                                 [31mThis issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.[39m
                                 [31mEnsure that the CI/CD pipeline is not using an older or pinned down version of Amplify CLI.[39m
                                 [31mLearn more about feature flags: https://docs.amplify.aws/cli/reference/feature-flags[39m
2022-03-25T10:34:57.579Z [ERROR]: !!! Build failed
2022-03-25T10:34:57.579Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-25T10:34:57.579Z [INFO]: # Starting environment caching...
2022-03-25T10:34:57.580Z [INFO]: # Environment caching completed
Terminating logging...
```

Even just running `amplify -v` resulted in this error?

**Comment by josefaidt** [comment]
Hey @JamieSlome do you have a version set for Amplify CLI in your app's build settings? By default it should use the latest version available

**Comment by JamieSlome** [comment]
@josefaidt - I have `latest` pinned for the Amplify CLI version.

**Comment by prestonhom** [comment]
Been having similar issue trying to deploy backend with `graphqltransformer.showfieldauthnotification`. Any updates on this @josefaidt? 

Node - v16.14
Amplify Build CLI version - @latest / v7.6.26 (tried both)
Local @aws-amplify/cli - v7.6.26

**Comment by josefaidt** [comment]
Hey @nileshordex @prestonhom and @JamieSlome are y'all still experiencing this issue? If so, can you try to push locally with `amplify push` to mitigate the issue?

**Comment by JamieSlome** [comment]
@josefaidt - no longer experiencing this 👍
