### ISSUE TITLE
Set DynamoDB trigger from amplify update storage

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-cli#10064]
### Is this feature request related to a new or existing Amplify category?

storage, function

### Is this related to another service?

DynamoDB

### Describe the feature you'd like to request

Would be useful to be able to attach a lambda function as a trigger on a DynamoDB stream via `amplify update storage` for a table created behind the scenes with graphql API. This flow should be able to attach an existing function or ask to create a new one for this purpose. 

### Describe the solution you'd like

1. Run `amplify storage update`
2. Select a NoSQL table created from the GraphQL API provisioning also done with the CLI
3. Select `Attach streams trigger` from the options
4. List the existing functions with an additional row for `Create new function`
5. If selecting an existing function, attach it, otherwise begin the create new function flow

### Describe alternatives you've considered

Currently have to do it via `amplify function add` and select the trigger template (which is a bit confusing as this implies it is just a template for the function code itself and not actually doing anything else. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @iyz91 :wave: thanks for taking the time to file this feature request separate from the bug report in #10061 🙂 Marking as a feature request for storage

**Comment by josefaidt** [comment]
Hey @iyz91 :wave: upon further investigation this flow is intended to be supported and the bug report you filed has effectively documented the broken workflow. Closing in favor of tracking the bug, #10061 

documentation reference: https://docs.amplify.aws/cli/usage/lambda-triggers/#dynamodb-lambda-triggers
