### ISSUE TITLE
Facebook signin not working on deployed environment

### ISSUE THREAD

**Issue by kgoyal98** [aws-amplify/amplify-cli#10078]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

Facebook signin is working on localhost but not on hosted environment.

These are the network traces for localhost signin
![image](https://user-images.githubusercontent.com/32641543/160270666-54c168d4-dccc-4499-bcf3-ad4a316ff6ba.png)

These are the network traces for hosted env signin
![image](https://user-images.githubusercontent.com/32641543/160270650-bb86d9bd-e9e6-453f-bab2-4d65196e1059.png)

### Expected behavior

-

### Reproduction steps

followed steps for amplify FB signin

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by swaminator** [comment]
Are you using Amplify Hosting to host the app?

**Comment by kgoyal98** [comment]
@swaminator yes

**Comment by kgoyal98** [comment]
Can somebody please help here.

**Comment by kgoyal98** [comment]
I found the issue here.
In the rewrites and redirects rules, I had
    ```
{
        "source": "https://<domain>.in",
        "target": "https://www.<domain>.in",
        "status": "302",
        "condition": null
    }, 
```
I changed the status to 200 and it works now.
