### ISSUE TITLE
Unauthorized issue with updateMutation for certain types

### ISSUE THREAD

**Issue by tanayvk** [aws-amplify/amplify-cli#10087]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.18.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

Ubuntu (WSL)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

As per the given graphql, we have a type ProjectUser.
When I run updateProjectUser mutation with something like:
```
mutation UpdateProjectUser(
  $input: UpdateProjectUserInput!
  $condition: ModelProjectUserConditionInput
) {
  updateProjectUser(input: $input, condition: $condition) {
    id
  }
}
```
where input is like
```
{
  id: "91c0a1a3-9ebb-4bb7-8c95-243d2f01fe01",
  accessType: "Editor"
}
```

I'm getting the error:
`{ errorType: "Unauthorized", message: "Unauthorized on [id, accessType]" }`

But I could check DynamoDB to verify that the User does indeed have the required groups for running update mutations. Since the read operation is working fine. Also, there is no special authorization for the id and access type fields.

I need some help figuring out the error here.
I looked into Amplify issues and found a related fix at [https://github.com/aws-amplify/amplify-cli/issues/9883 ](https://github.com/aws-amplify/amplify-cli/issues/9883)
But that's already merged into the CLI version I'm using as noted above. And I'm still facing this issue.

### Expected behavior

Expected the updateUser mutation to run without any authentication issues.

### Reproduction steps

1. Push the schema.graphql
2. Add a Cognito user to a user group and put the user group in the U field in the type.
3. Try updating the type ProjectUser through AppSync console by running updateProjectUser mutation.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type ProjectUser
  @model(queries: null)
  @auth(
    rules: [
      { allow: private, operations: [create] }
      { allow: groups, groupsField: "R", operations: [read] }
      { allow: groups, groupsField: "U", operations: [update] }
      { allow: groups, groupsField: "D", operations: [delete] }
    ]
  ) {
  id: ID!
  projectID: ID!
  project: Project! @belongsTo(fields: ["projectID"])
  accessType: Access!
  R: [String]
  U: [String]
  D: [String]
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Posting this as recommended by the AWS Support team.

**Comment by ykethan** [comment]
Hello @tanayvk, Thank you for reaching out. On replicating the schema in my Amplify application I was unable to replicate the error. I utilized the following replication steps in my Amplify application.

1. added graphql to my application with the following schema.

```GraphQL
type ProjectUser
  @model(queries: null)
  @auth(
    rules: [
      { allow: private, operations: [create] }
      { allow: groups, groupsField: "R", operations: [read] }
      { allow: groups, groupsField: "U", operations: [update] }
      { allow: groups, groupsField: "D", operations: [delete] }
    ]
  ) {
  id: ID!
  projectID: ID!
  project: Project! @belongsTo(fields: ["projectID"])
  accessType: Access!
  R: [String]
  U: [String] 
  D: [String]
  }

type Project @model {
  id: ID!
  name: String
  projectuser: ProjectUser @hasOne
}

enum Access {
  All,
  semi,
  private
}

```

2. Create a user in Cognito and add user to group "U".
3. In my AppSync console logged in as the user using Cognito authorization.
4. Ran createProjectUser with the following query.

```GraphQL
 createProjectUser(input: {U: ["U"], projectID: "1234", accessType: private}) {
    U
    projectID
    D
    R
    id
  }
```

Output:

```JSON
{
  "data": {
    "createProjectUser": {
      "U": [
        "U"
      ],
      "projectID": "1234",
      "D": null,
      "R": null,
      "id": "45792d5c-cd23-438b-bfe4-3120862f8422"
    }
  }
}
```

5. Ran updateProjectUser with the following query.

```GraphQL
updateProjectUser(input: {id: "45792d5c-cd23-438b-bfe4-3120862f8422", projectID: "10887"}) {
    id
    projectID
    updatedAt
    accessType
  }
```
output:

```JSON
{
  "data": {
    "updateProjectUser": {
      "id": "45792d5c-cd23-438b-bfe4-3120862f8422",
      "projectID": "10887",
      "updatedAt": "2022-04-01T16:58:14.499Z",
      "accessType": "private"
    }
  }
}
```
6. additionally, updated access type as well.
output:

```JSON
{
  "data": {
    "updateProjectUser": {
      "id": "45792d5c-cd23-438b-bfe4-3120862f8422",
      "projectID": "10887",
      "updatedAt": "2022-04-01T17:23:12.471Z",
      "accessType": "semi"
    }
  }
}
```

Could you please let me know if value `U` is an array of Cognito User Pool groups in which the authenticated user is a member of. Could you also please provide me a sample of the `Project` and `Access` types.

**Comment by ykethan** [comment]
Hello @tanayvk, wanted to followup on this and see if you are experiencing any issues.

**Comment by ykethan** [comment]
closing the issue due to inactivity for an extended period. Please feel free in reaching out to us again.
