### ISSUE TITLE
AdminQueries AWS::ApiGateway::RestApi Unable to put integration on 'ANY' for resource at path '/{proxy+}'

### ISSUE THREAD

**Issue by MichaelPlan** [aws-amplify/amplify-cli#10084]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.2

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth, api

### Amplify Commands

push, update

### Describe the bug

Added AdminQueries via 'amplify update auth' and after 'amplify push' I got:

CREATE_FAILED      AdminQueries AWS::ApiGateway::RestApi Mon Mar 28 2022 13:48:53 GMT+0200 (Central European Summer Time) Errors found during import:  Unable to put integration on 'ANY' for resource at path '/{proxy+}': Invalid lambda function (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: cb4fdec6-fb09-4298-b072-98f59963c44f; Proxy: null)

I can't push anything now.

### Expected behavior

Push should run without problems.

### Reproduction steps

1. amplify update auth
2. Choose AdminQueries
3. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

CREATE_FAILED      AdminQueries AWS::ApiGateway::RestApi Mon Mar 28 2022 13:48:53 GMT+0200 (Central European Summer Time) Errors found during import:  Unable to put integration on 'ANY' for resource at path '/{proxy+}': Invalid lambda function (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: cb4fdec6-fb09-4298-b072-98f59963c44f; Proxy: null)

**Comment by MichaelPlan** [comment]
@jhockett sure:

{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "****664a87b2_identitypool_664a87b2",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "****664a87b2",
    "userPoolName": "****664a87b2_userpool_664a87b2",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email",
      "nickname",
      "preferred_username"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "****664a87b2_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "sharedId": "664a87b2",
    "resourceName": "****664a87b2",
    "authSelections": "identityPoolAndUserPool",
    "useDefault": "manual",
    "triggers": {
      "PostConfirmation": [
        "add-to-group"
      ],
      "PreSignup": [
        "custom"
      ]
    },
    "userPoolGroupList": [
      "Member",
      "Admin"
    ],
    "serviceName": "Cognito",
    "usernameCaseSensitive": false,
    "useEnabledMfas": true,
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": true,
    "dependsOn": [
      {
        "category": "function",
        "resourceName": "****664a87b2PostConfirmation",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      },
      {
        "category": "function",
        "resourceName": "****664a87b2PreSignup",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      }
    ],
    "permissions": [
      "{\n  \"policyName\": \"AddToGroupCognito\",\n  \"trigger\": \"PostConfirmation\",\n  \"effect\": \"Allow\",\n  \"actions\": [\n    \"cognito-idp:AdminAddUserToGroup\",\n    \"cognito-idp:GetGroup\",\n    \"cognito-idp:CreateGroup\"\n  ],\n  \"resource\": {\n    \"paramType\": \"!GetAtt\",\n    \"keys\": [\n      \"UserPool\",\n      \"Arn\"\n    ]\n  }\n}"
    ],
    "authTriggerConnections": "[\n  {\n    \"triggerType\": \"PostConfirmation\",\n    \"lambdaFunctionName\": \"frinju664a87b2PostConfirmation\"\n  },\n  {\n    \"triggerType\": \"PreSignUp\",\n    \"lambdaFunctionName\": \"frinju664a87b2PreSignup\"\n  }\n]",
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "adminQueryGroup": "Admin",
    "thirdPartyAuth": false,
    "userPoolGroups": true,
    "adminQueries": true,
    "hostedUI": false,
    "authProviders": []
  }
}

**Comment by josefaidt** [comment]
Hey @MichaelPlan are you still experiencing this issue?
