### ISSUE TITLE
Amplify Cannot Authenticate Role Credentials Through Access Tokens

### ISSUE THREAD

**Issue by kurtpatrick-yu** [aws-amplify/amplify-cli#10081]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac, Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

init, pull

### Describe the bug

When running amplify init/pull via headless mode using AWS Tokens, the CLI returns _"Invalid configuration settings!"_. I manually ran amplify pull and input my access tokens, and it returned the same. It cannot read my AWS access tokens.

_Note: The tokens are from role sessions._

### Expected behavior

It should be able to pull/initialize project upon run similar to when I use profile.

### Reproduction steps

Code used:
```
#!/bin/bash
set -x
IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"yarn build-apac-dev\",\
\"StartCommand\":\"yarn start-apac-dev\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$1\",\
\"secretAccessKey\":\"$2\",\
\"region\":\"$3\"\
}"
AMPLIFY="{\
\"projectName\":\"apacaitbx\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```

Output:
```
KurtPatrick.Yu@PHPMACFJ124Q05P apac-ai-powered-vhc % sh amplify-steps/amplify-init.sh ********************* ******************************** ap-northeast-1
+ IFS='|'
+ REACTCONFIG='{"SourceDir":"src","DistributionDir":"build","BuildCommand":"yarn build-apac-dev","StartCommand":"yarn start-apac-dev"}'
+ AWSCLOUDFORMATIONCONFIG='{"configLevel":"project","useProfile":false,"profileName":"default","accessKeyId":"******************","secretAccessKey":"********************************,"region":"ap-northeast-1"}'
+ AMPLIFY='{"projectName":"apacaitbx","envName":"dev","defaultEditor":"code"}'
+ FRONTEND='{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"yarn build-apac-dev","StartCommand":"yarn start-apac-dev"}}'
+ PROVIDERS='{"awscloudformation":{"configLevel":"project","useProfile":false,"profileName":"default","accessKeyId":"************","secretAccessKey":"*********************************","region":"ap-northeast-1"}}'
+ amplify init --amplify '{"projectName":"apacaitbx","envName":"dev","defaultEditor":"code"}' --frontend '{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"yarn build-apac-dev","StartCommand":"yarn start-apac-dev"}}' --providers '{"awscloudformation":{"configLevel":"project","useProfile":false,"profileName":"default","accessKeyId":"*******","secretAccessKey":"****************","region":"ap-northeast-1"}}' --yes
Note: It is recommended to run this command from the root of your app directory
The following configuration will be applied:

Project information
| Name: apacaitbx
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: yarn build-apac-dev
| Start Command: yarn start-apac-dev

(node:10047) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
Invalid configuration settings!
? Do you want to retry configuration? (y/N) 
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
2022-03-27T22:14:26.981Z|info : amplify init core  [***]{"amplify":"{\"projectName\":\"[***]itbx\",\"envName\":\"[***]ev\",\"[***]ultEditor\":\"code\"}","frontend":"{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"yarn build-apac-dev\",\"StartCommand\":\"yarn start-apac-dev\"}}","providers":"{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":false,\"profileName\":\"default\",\"accessKeyId\":\"[***]CCZKUWH3\",\"secretAccessKey\":\"[***]cyDwr5zsLxxqu5K4\",\"region\":\"ap-northeast-1\"}}","yes":true}
2022-03-27T22:14:27.028Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2022-03-27T22:14:38.709Z|info : amplify init core  [***]{"amplify":"{\"projectName\":\"[***]itbx\",\"envName\":\"[***]ev\",\"[***]ultEditor\":\"code\"}","frontend":"{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"yarn build-apac-dev\",\"StartCommand\":\"yarn start-apac-dev\"}}","providers":"{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":false,\"profileName\":\"default\",\"accessKeyId\":\"[***]CCZKUWH3\",\"secretAccessKey\":\"[***]cyDwr5zsLxxqu5K4\",\"region\":\"ap-northeast-1\"}}","yes":true}
2022-03-27T22:14:38.748Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

```

</details>

### Additional information

Locally, this works when we use profile, but we need this to run on a pipeline where we generate tokens via assume role.

**Comment by josefaidt** [comment]
Hey @kurtpatrick-yu :wave: thanks for raising this! To clarify, are you aiming to initialize an existing project or create a new project?

**Comment by kurtpatrick-yu** [comment]
Hi @josefaidt, this is to initialize an existing project, but it doesn't work on new projects as well. I was able to isolate the issue where amplify does not ask for _aws_session_token_ and _aws_security_token_ when not using profile. I tried adding them as keys on headless mode as well but they don't seem to be valid keys and just get ignored and I get the same error.

```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$1\",\
\"secretAccessKey\":\"$2\",\
\"sessionToken\": \"$3\",
\"securityToken\": \"$4\",
\"region\":\"$5\"\
}"
```

May I know if there is a way to pass _aws_session_token_ and _aws_security_token_ when not using profile?

**Comment by josefaidt** [comment]
Hey @kurtpatrick-yu :wave: thank you for the clarification! While headless init does not support `sessionToken` and `securityToken` we can provide these as environment variables that AWS CLI uses, `AWS_SESSION_TOKEN`. Can you try setting those as environment variables as defined here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials?

**Comment by josefaidt** [comment]
Hey @kurtpatrick-yu :wave: are you still experiencing this issue?

**Comment by kurtpatrick-yu** [comment]
Hi @josefaidt, I was able to workaround this by using profile instead of tokens and then adding a config and credentials file for it to process. This fully emulates what I do locally.

**Comment by mjmostachetti** [comment]
This still doesn't work.
