### ISSUE TITLE
Cloudfront hosting: inconsistencies in cloudformation distribution

### ISSUE THREAD

**Issue by olivierpichon** [aws-amplify/amplify-cli#10082]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

`7.6.5`

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No change

### Amplify Categories

hosting

### Amplify Commands

add, configure, Not applicable

### Describe the bug

Using `amplify hosting configure` or `amplify hosting add` to configure / add a Amazon CloudFront and S3 configuration creates a cloudformation. In this cloudformation, the S3 bucket is configured to use static web hosting:

```
"WebsiteConfiguration": {
    "IndexDocument": "index.html",
    "ErrorDocument": "index.html"
},
```

However, in the cloudformation's cloudfront details, we never use the static web hosting from S3 as the origin of the cloudfront distribution. We instead use the bucket itself:
```
"Origins": [
    {
        "DomainName": {
            "Fn::GetAtt": [
                "S3Bucket",
                "DomainName"
            ]
        },
```

(The origin URL is not xxx.s3-website-us-east-1.amazonaws.com)

### Expected behavior

Either disable S3 hosting on the bucket or, use the hosting feature of the bucket as the origin of the cloudfront distribution.

It looks like what was decided in the end is to leave the bucket's content private and to give the cloudfront distribution an Origin Access Policy to access the bucket. If that's the case, then disabling S3 hosting seems like the way to go as having a web server on top of inaccessible objects is not useful.

### Reproduction steps

1. Add a `Amazon CloudFront and S3` hosting solution.
2. See that it includes web hosting at the S3 level.

**Comment by ykethan** [comment]
Hello @olivierpichon, checking in to see if you are facing any issues with the latest CLI.

**Comment by olivierpichon** [comment]
@ykethan yes still the same with latest CLI version
