### ISSUE TITLE
disable autoId | Schema Error: Unknown directive "pk"

### ISSUE THREAD

**Issue by rfdc** [aws-amplify/amplify-cli#1008]
**Describe the bug**
I am using the info from post #56 and getting the following Schema Errors:
```
Schema Errors:
Unknown directive "pk".
GraphQL request (35:13)
34: {
35:     id: ID! @pk
```
graphQL  Schema:
```
type Campaign
@model
{
    id: ID! @pk
    ....
}
```
**Additional context**
This is a schema that was previously created with just ID!
Thanks

**Comment by mikeparisstuff** [comment]
@rfdc The @pk directive is not implemented. There will soon be a new RFC that comments on how to build custom index structures for @model types.

**Comment by rfdc** [comment]
That would be great cos every time I update my schema I need to update the resolvers manually and also document it for future developers

Any idea when it will be implemented? How do I get updates towards it? 

thanks @mikeparisstuff

**Comment by mikeparisstuff** [comment]
Here is the RFC for custom indexes https://github.com/aws-amplify/amplify-cli/issues/1062. It would be great if you could respond with feedback so we can make sure to address any concerns. You also have the option of overwriting any auto-generated resolver templates with custom templates that will not be overwritten each time you run build. You can read more details on this here https://aws-amplify.github.io/docs/cli/graphql#overwrite-a-resolver-generated-by-the-graphql-transform.

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.
