### ISSUE TITLE
AdminQuery: API AdminQueries does not exist

### ISSUE THREAD

**Issue by stayingcool** [aws-amplify/amplify-cli#10092]
### Before opening, please confirm:

- [ ] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v10.15.1

### Amplify CLI Version

4.25.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Amplify Categories

auth, storage, function, hosting

### Amplify Commands

Not applicable

### Describe the bug

**AdminQuery** is returning an exception **"API AdminQueries does not exist"**
- `amplify status` shows the AdminQuery
- API Gateway shows the Lambda function linked to it
- The lambda execution policy has the required Action "_cognito-idp:AdminListGroupsForUser_",
- CloudWatch has no records on the lambda invocation 
- I deleted and added the AdminQuery once again

The function that I have to list the groups of a user (_listGroupsForUser_):

```
async isQCAuditor(cognitoUsername) {
    if (!cognitoUsername) return false;

    let isQcAuditor = false;
    let nextToken;
    let apiName = "AdminQueries";
    let path = "/listGroupsForUser";
    let myInit = {
      queryStringParameters: {
        username: cognitoUsername,
        token: nextToken
      },
      headers: {
        "Content-Type": "application/json",
        Authorization: `${(await Auth.currentSession())
          .getAccessToken()
          .getJwtToken()}`
      }
    };

    try {
      const { NextToken, ...cognitoGroups } = await API.get(
        apiName,
        path,
        myInit
      );
      nextToken = NextToken;

      for (let group of cognitoGroups.Groups) {
        if (group.GroupName === "qcauditor") {
          isQcAuditor = true;
          break;
        }
      }
    } catch (e) {
      console.log(e);
    }

    return isQcAuditor;
  }
};
```

The REST endpoint is still returning the same error. 
Can you provide some hints to resolve this issue?

### Expected behavior

The AdminQueries API should return the list of groups for a user.

### Reproduction steps

1. Add the admin query as [documented](https://docs.amplify.aws/cli/auth/admin/#admin-queries-api)
2. Invoke the above-mentioned function (code provided above)
3. The API fails and the exception gets caught in the catch block and the error shows _"API AdminQueries does not exist"_

> I cannot upgrade the version of amplify cli as of now. This is a working setup and is a part of my production setup that suddenly stopped working. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by stayingcool** [comment]
I have asked for help in Discord community as well:
https://discord.com/channels/705853757799399426/957602716312543262

**Comment by jhockett** [comment]
Hi @stayingcool,

> I deleted and added the AdminQuery once again

How did you delete the Admin Queries API the first time?

**Comment by josefaidt** [comment]
Hey @stayingcool :wave: unfortunately I have not been able to reproduce this issue after adding, testing, removing & re-adding AdminQueries, etc. The error you are experiencing: `API AdminQueries does not exist` is likely returned from the `aws-amplify` API module. Can you confirm whether the AdminQueries API was successfully added and restricted to a group?

**Comment by stayingcool** [comment]
@josefaidt - This issue can be closed.

Please refer:
https://github.com/aws-amplify/amplify-js/issues/9746
