### ISSUE TITLE
Unauthorized using APIKey AppSync Auth0Function

### ISSUE THREAD

**Issue by jacobcravinho** [aws-amplify/amplify-cli#10096]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.14.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

M1 Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

I am following a simple todoList example.  From my app I wanted to list items and was returned a status:200 but the response message was "Not authorized to access listTodos on type ModelListTodosConnections".  Because I was returned a 200 and not 400 I figured it is an issue with the AppSync function.

I found in AppSync -> Functions -> QuerylistTodospostAuth0Function that this is being invoked with an APIKey.  The bellow code (request template) is hitting the if statement and returning unauthorized. 

`## [Start] Sandbox Mode Disabled. **
#if( !$ctx.stash.get("hasAuth") )
  $util.unauthorized()
#end
$util.toJson({})
## [End] Sandbox Mode Disabled. **`

Removing the if statement gives desired results and returns items from DDB.

### Expected behavior

When using APIKey do not return unauthorized in request mapping template

### Reproduction steps

Follow Todo Amplify Tutorial

**Comment by ykethan** [comment]
Hello @jacobcravinho, I tried replicating the steps from the following document outlining a Todo AppSync Schema.
https://docs.amplify.aws/start/q/integration/react/

But did not experience the error mentioned. It would be great, if you please let us know if there were any additional steps utilized or document referenced while creating the application. Could you please provide me you Graphql schema.

**Comment by ykethan** [comment]
hey @jacobcravinho wanted to follow up on this and see if you are experiencing any issues.

**Comment by ykethan** [comment]
closing the issue due to inactivity for an extended period
