### ISSUE TITLE
Annotation-created mutations should return a Payload type

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-cli#101]
**Do you want to request a feature or report a bug?**
Feature request

**What is the current behavior?**
Annotation-created mutations return the base type. However, several people (e.g. [Caleb Meredith](https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97)) have recommended that mutations nest the returned instance in a payload object.

**What is the expected behavior?**
Desire at least an option for annotation (or maybe another transform!) to wrap mutation return types in a unique-per-mutation payload type.

**Comment by mikeparisstuff** [comment]
I agree that the `Payload` concept is useful and this would not be difficult to add in the future as another transformer. We decided against adding the additional payload wrapper for the simple case as it can add layers to code gen and confuse new comers, but if there sufficient demand we can discuss changing the default.
