### ISSUE TITLE
Can't pull backend during deployment due to feature flag: graphqltransformer.showfieldauthnotification Amplify 7.6.26

### ISSUE THREAD

**Issue by prestonhom** [aws-amplify/amplify-cli#10106]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, but I tried to on the generated cli.json file. When I try to push to remove the unrecognized field -`graphqltransformer.showfieldauthnotification` , my local machine performs a pull and no changes are persisted.

### Amplify Categories

auth, function, api

### Amplify Commands

pull, push, status

### Describe the bug

I am trying to deploy my app which I have done fine in since v4. Recently I've updated to 7 and can't resolve this featureflag conflict 
`These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:[39m
                                 [31m  - graphqltransformer.showfieldauthnotification[39m
                                 [31mThis issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.[39m
`
I've tried adding @latest/7.6.26 in the build image settings to no avail as well.

### Expected behavior

I expect the backend to be built and deployed.

### Reproduction steps

In my local machine. I:

1. `amplify pull`
2. delete this key value pair in root/amplify/cli.json: features.graphqltransformer.showfieldauthnotification 
3. `amplify push`
4. go to AWS console to deploy

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by vishalt-verneek** [comment]
following.. I am getting the same error as well

**Comment by ykethan** [comment]
Hello @prestonhom, wanted to followup on this and see if you are still experiencing this issue.

**Comment by prestonhom** [comment]
@ykethan @vishalt-verneek  Sorry for the late rseponse.

This worked for me https://github.com/aws-amplify/amplify-js/discussions/9427#discussioncomment-2481027
not exactly the same script but very similar. The 2 bolded lines are what made the deployment work. 
While also adding
`version: 1
env:
  variables:
    VERSION_AMPLIFY: 7.6.26
backend:
  phases:
    preBuild:
      commands:
        - **npm i -g @aws-amplify/cli@${VERSION_AMPLIFY}** 
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - **nvm use $VERSION_NODE_16**
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*`

**Comment by ykethan** [comment]
hey @prestonhom, glad to hear that you are back up and running. could you please confirm if the logs for your failed builds contained the following error.
``
Error patching NPM package '@aws-amplify/cli' to version latest
``

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please do reach out to us again.
