### ISSUE TITLE
Cannot get data in real time with Update Subscription

### ISSUE THREAD

**Issue by shichi18** [aws-amplify/amplify-cli#10107]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

codegen

### Describe the bug

Cannot get when Update Subscription is set in the sign-in state (Cognito UserPool).
User belongs to one or more groups.
It worked fine with IAM guest login.
It is possible that the code here is incorrect, but I would be happy to have you guys confirm this.

### Expected behavior

Cannot get when Update Subscription is set in the sign-in state (Cognito UserPool).
I did not catch the error.

### Reproduction steps

1. User belongs to one or more groups.
2. cognito login 
3. use amplify-js (ionic)
```
this.apiService.OnUpdateRoomsListener(id).subscribe(
 (data) => {
console.log('get Data');
},
```

4. update Rooms

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Rooms @model
@auth(rules: [
  { allow: owner, ownerField: "id", operations: [create, update, read] }
  { allow: groups, groups: ["employee"] }
  { allow: public, provider: iam, operations: [create, update, read] }
]) {
  id: ID!
  data1: string
  data2: string
  data3: string
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by shichi18** [comment]
thank you.

I re-created the account and it now works fine.

However, it was a little strange since it seemed to work before.
If you have no idea what is going on on your end, you can close it.

Sorry I could not reproduce it.

**Comment by ykethan** [comment]
Hello @shichi18, Thank you for reaching out. Looking at the schema and on replicating in my Amplify application. I can see the `ownerField: "id"` which will cause record creation errors. As the ID field is unique, AppSync will fill in the id as owner but will cause a creation error on the next record with the same id. could you please remove the `ownerField` and deploy the API.

**Comment by shichi18** [comment]
@ykethan 
ID field was unique.
Guest login (random string) and user login (UserPool ID) used different IDs.

Get was working, so I felt that IDs were not a problem.
After updating data, I was able to get the updated information with `GetRoom`.
`OnUpdateRoomListener` could not get the data in real time (this is the topic of this issue).
Nothing was returned.

When I switched the login to another account or guest, it worked, so it is possible that something is wrong with the DB.
However, the ID did match the account.

Creating and recreating the account solved the problem and I am able to use it again, but I will also try it the way you have taught me.
Thank you!

**Comment by ykethan** [comment]
Hey @shichi18, I replicated the `onUpdateRooms` in my local application utilizing the following code.

```js
const subs = API.graphql({
      query: subscriptions.onUpdateRooms,
      variables: { id: "<id of owner>" },
    }).subscribe({
      next: ({ provider, value }) => console.log({ provider, value }),
      error: (error) => console.warn(error),
    });
```
on running a `npm start` I was able to see the room update actions in my browser console on each update room query. I was unable to see an error when creating a subscription. But I experienced an `DynamoDB:ConditionalCheckFailedException` error when creating a new room as the owner field is unique.

I understand the issue had been resolved after recreating the account, please do reach out if you are experiencing any issues.

**Comment by ykethan** [comment]
closing the issue. Please do reach out to us again.
