### ISSUE TITLE
Dynamic Group Authorization Exceeding Cognito Limits

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-cli#10110]
**Which Category is your question related to?**

Setting up a GraphQL API

**Amplify CLI Version**
7.6.26

**What AWS Services are you utilizing?**
Cognito, DynamoDB, AppSync, DataStore

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

**Background :** 

We are building an app (in iOS and eventually Android) that manages competitions. Users of the app can create their competition and then invite people to join it. The app provides real time result data and notifications which DataStore and AppSync is really attractive for us to handle. People who join would fall into a few "groups". Administrators who can edit and manage the settings of the Competition. Competitors who can read the information about the competition. And then various other groups with different permissions levels for different aspects with the Competitions (for instance, administrators, timers, book keepers for individual events within the competition.) 

Individuals can belong to any of these groups and also be part of any number of Competitions. Therefore there is hierarchy where "Competitions" are at the top and under that are "Permission Groups" and under that are the "Users". Therefore having a Cognito "Admin" or "Editor" group doesn't work since we would need to create multiple versions of these groups for each Competition. 

**Issue :**

This is where the real issue becomes apparent. If we were to use groups in Cognito we would only be able to support 100 or so Competitions and then our App would fail. Because Cognito only support 500 groups (everyone would be in the same User Pool). 

A suggestion was made by @josefaidt to use dynamic groups which I had investigated. But that runs into the 500 group limit I believe. However, to be clear in this snippet below does a dynamic group actually reference a Cognito group? I assume it did...

```
@auth(rules: [
    { allow: owner, operations: [create, read, update] }
    { allow: groups, groupsField: "viewers", operations: [read] }
])
```

We are converting our app from using a REST interface through API Gateway with Lambdas responding to the endpoints to AppSync and GraphQL. In our existing RDS schema we have the concept of `"Competition" > "Competition_Admin" > "Role", "Account". ` Competition_Admin would be analogous to a Cognito Group. 

**Use Case Example :**

So for example, User A creates Competition A. The backend also creates an entry in the "Competition_Admin" table where it has a relationship to User and Competition and Role. That entry would have User A, Competition A, and Role Owner (which has full read/write access booleans turned on). The lambdas then check these tables to ensure that if someone is editing/deleting anything in the Competition that they have the appropriate permissions. 

Same scenario for User B. They create Competition B and an entry in "Competition_Admin" is created for User B, Competition B, Role Owner. 

Continuing on, User A decides to invite User C to be an admin in their Competition A. User C is then added to the "Competition_Admin" with entry of User C, Competition A, Role Admin. This Role, for example, is setup to allow User C to edit settings in Competition A but not delete Competition A. 

Finally, User B decides to invite User D to be an admin in their Competition B. "Competition_Admin" entry of User D, Competition B, Role Admin. 

So what we have essentially have here is 4 groups. Perhaps only 3 groups since the Role Owner should probably be considered a single group that manages who owns which Competition. But each Competition has its own "Admin" group. 

**Questions :**

1. Are dynamic groups referencing Cognito Groups or is it more referencing a table within a schema like "Competition_Admin" in the example above? (If it's the latter then we're golden).
2. **Lambda Resolvers** : _Assuming Question 1 is referencing Cognito Groups then we need to look at custom authentication options._ Lambda Resolvers were investigated but they apparently don't work with **DataStore** which is a requirement for offline storage in our app. Is there a way around this? 
3. **Lambda Resolvers pt.2** We are familiar with creating Lambda code. But are also cautious as it seems they then are responsible for loading the data from DynamoDB and then sending it back? We'd be losing all that time saved that Amplify was providing to us through auto generated code.
4. **Extend Amplify-Generated Resolvers** - This appears to require us to use VTL code but it does seem that this approach would leave all the rest of the heavy lifting to the Amplify generated code. However we are not familiar at all with VTL code or what "slot" we should insert our code in? (pre-Auth?). Some sample code that would address the example above would be very helpful. Essentially using a "model" in the GraphQL Schema as the authentication criteria. Link to docs below.
    https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers
5. Other options?

**Comment by Etep15** [comment]
So looks like a partial solution is to use the `ownerField` tag in the @auth rules. For instance here is my model in graphql.schema. Also understanding that dynamic groups do NOT use Cognito groups (thanks @josefaidt ). So the answer to question #1 was positive. 

However using `groupsField` wasn't working and I still think it may point to a Coginto group. Even though I set admins to the username of the second user they had no access. I think this is because its still pointing to some concept of a group which I assume is a Coginto group. If it isn't I'm not sure what it is pointing to???

But then I found `ownerField` and came up with the below model.

```
type Blog @model @auth(rules: [
  {allow:owner, operations:[create, read, update, delete]}
  {allow:owner, ownerField: "admins", operations: [update, read] }
])
{
  id: ID!
  name: String
  posts: [Post] @hasMany
  owner: String
  admins: [ID] @auth(rules:[{allow:owner, operations:[create, read, update, delete]}])
}
```

This works great using the AppSync Query console. I can assign an admin by username and they can read and update the blog entry but they can't delete it. Where as the original owner can delete the blog. Perfect. This is what we want. Also different Blogs with different admins are isolated as well. 

However I've now run into the issue that on the iOS side this Use Case is not supported... 

I'm seeing the following log output from my test app where I subscribe to changes...

```
[RemoteSyncEngine] initializeSubscriptions(api:storageAdapter:)
[AuthRuleDecorator] Detected multiple owner type auth rules with a READ operation. We currently do not support this use case. Please limit your type to just one owner auth rule with a READ operation restriction.
```

The logging continues to spin around and attempt multiple times to get the subscriptions to take. 

I'm not sure if this is the AppSync or DataStore implementation causing this error. But I'm not sure how to proceed here. Having subscriptions was one of the key features that attracted us to pursue AppSync with our Amplify project.

**Comment by josefaidt** [comment]
Hey @Etep15 :wave: thanks for taking the time to file this and apologies for the confusion! Yes Dynamic Groups auth will use Cognito groups, I misspoke. The owner field as you pointed out is a suitable solution to store user ID's to a field for access rights. From the [docs](https://docs.amplify.aws/cli/graphql/authorization-rules/#user-group-based-data-access):

> With dynamic group authorization, each record contains an attribute specifying what groups should be able to access it. Use the groupsField argument to specify which attribute in the underlying data store holds this group information

Does this also answer questions 2 & 3?

> Lambda Resolvers : Assuming Question 1 is referencing Cognito Groups then we need to look at custom authentication options. Lambda Resolvers were investigated but they apparently don't work with DataStore which is a requirement for offline storage in our app. Is there a way around this?
Lambda Resolvers pt.2 We are familiar with creating Lambda code. But are also cautious as it seems they then are responsible for loading the data from DynamoDB and then sending it back? We'd be losing all that time saved that Amplify was providing to us through auto generated code.

**Comment by Etep15** [comment]
It does thank you. I think I still need to dive into Lambda Resolvers in order to kick off things such as a push notification through SNS or Pinpoint on a create or update coming in through AppSync. But that's another topic.

The one remaining issue is the subscriptions piece. While they are a valid configuration they aren't supported with two owner rules with DataStore according to the issue I noted above. #1590. That's the next challenge. Hoping that makes it to a release soon. 

One thing I will note, is that the documentation could be updated. There's some ambiguity which I struggled with in that what does the term "group" mean. For example : 

> With dynamic group authorization, each record contains an attribute specifying what `Cognito` groups should be able to access it.

That simple change would've helped a ton. Just a suggestion.

Thanks once again for all your help! I think we are good here. Hope this helps others.

**Comment by josefaidt** [comment]
Hey @Etep15 that's a great callout on the docs piece. I'll mark this as a documentation issue 🙂
