### ISSUE TITLE
Cannot add new @index on an existing table

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#10117]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.2.0

### Amplify CLI Version

7.6.26

### What operating system are you using?

macOS 

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Amplify Categories

storage, api

### Amplify Commands

push

### Describe the bug

I have an existing `@model`-backed type that I would like to add a new `@index` to. The new `@index` is added on the field which serves as the type's `@primaryKey`.
The purpose of the new index is its dedicated sort key field.

My `secondaryKeyAsGSI` flag is set to `false` as I essentially cannot update it (see https://github.com/aws-amplify/amplify-cli/issues/10111).

When I try to add a new index, upon push I get the following error:
`🛑 An error occurred during the push operation: Attempting to add a local secondary index to the PostCollectionMembershipTable table in the PostCollectionMembership stack. Local secondary indexes must be created when the table is created.`

### Expected behavior

 Be able to add a new index, by leveraging DynamoDB's GSI.

### Reproduction steps

1. Create `@model` backed type with a custom field serving as `@primaryKey`
2. amplify push (so that DynamoDB tables are created)
3. Add a new `@index` on the field with the `@primaryKey` defined on it
4. Attempt to `amplify push` once again

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type PostCollectionMembership
  @model
  @searchable
  @auth(rules: [
    {allow: owner, ownerField: "ownerSub", identityClaim: "sub", operations: [read, delete]},
    {allow: public, operations: [read]},
    {allow: private, operations: [read]},
    {allow: private, provider: iam, operations: [create, read, update, delete]}
]) {
  ownerSub: String!
  author: User!
    @hasOne(fields: ["ownerSub"])

  postCollection_id: ID!
    @primaryKey(sortKeyFields: ["post_id"])
    @index(name: "byPostCollection", sortKeyFields: ["createdAt"])
    @index(name: "byPostCollectionAndRank", sortKeyFields: ["rank"])
    
  postCollection: PostCollection!
    @belongsTo(fields: ["postCollection_id"])

  post_id: ID!
    @index(name: "byPost", sortKeyFields: ["createdAt"])

  post: Post
    @hasOne(fields: ["post_id"])

  createdAt: AWSDateTime!
  rank: Float!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
@ataibarkai Can you explain more about why you can't migrate your LSIs to GSIs? Enabling that feature flag and pushing should switch existing LSIs to GSIs and allow you to create new GSIs.

Barring updating that feature flag, there is currently no way to add a GSI that uses the primary key field

**Comment by edwardfoyle** [comment]
@ataibarkai thanks for the details! That makes sense. I'm going to close this in favor of the feature request you opened in https://github.com/aws-amplify/amplify-cli/issues/10111

**Comment by ataibarkai** [comment]
Sounds good @edwardfoyle , will keep discussion on the other thread then
