### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by RFason** [aws-amplify/amplify-cli#10127]
**Describe the bug**

bash: amplify: command not found
**To Reproduce**
1. npm install -g @aws-amplify/cl
2. amplify configure
3.  See error - bash: amplify: command not found

**Expected behavior**
Expected to configure

**Screenshots**

**Desktop (please complete the following information):**

Mac - Monterey 
**Smartphone (please complete the following information):**

**Additional context**
command input: 
amplify configure

command output: 
bash: amplify: command not found

node version v16.14.2
Installed using npm

**Comment by RFason** [comment]
it printed /usr/local/bin when using npm bin -g

**Comment by josefaidt** [comment]
Thanks for the clarification @RFason how was Node & NPM installed? Can you confirm whether `echo $PATH | grep $(npm bin -g)` returns anything?

**Comment by RFason** [comment]
1. It was install via Node website -nodejs.org/en/download and NPM - npm install -g npm

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin

**Comment by josefaidt** [comment]
Hey @RFason thanks for clarifying. Moving forward I would make sure:

- Node and NPM are installed
- `npm bin -g` is a part of our `PATH` environment variable
- after `@aws-amplify/amplify-cli` is installed with `npm i -g @aws-amplify/amplify-cli`, we can confirm the binary is available with `which amplify`

For reference, we can alternatively use a Node version manager like [nvm](https://github.com/nvm-sh/nvm), more info can be found on the [npm docs](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-nodejs-and-npm)

We can also set a custom [npm prefix](https://docs.npmjs.com/cli/v8/commands/npm-prefix)

With that I will close this issue for now, however if needed we can re-open to investigate further. Please use the NPM docs as a point of reference for troubleshooting globally installed packages and binaries not available

**Comment by RFason** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-amplify%2famplify-cli - Not found
npm ERR! 404 
npm ERR! 404  '@aws-amplify/amplify-cli@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

I'm now getting this error when installing.

**Comment by RFason** [comment]
Thanks for all your help Josef! I am closing this due to an internal  issue that needs to be reviewed. I really appreciate your help getting to the root cause of this issue.
