### ISSUE TITLE
Cannot delete environment

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#10129]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Tried deleting the environment via the UI in the console, that fails too.

### Amplify Categories

api

### Amplify Commands

delete

### Describe the bug

I've tried to delete an environment manually via the UI and via the CLI but it seems impossible to do.

The UI fails with an error that it simply can't complete the action.

To delete in the CLI I tried to pull it down locally first via the "Local setup" command line. This opens a browser to Amplify Admin but claims my environment is invalid yet it is listed.

This has been happening for months and I've just pushed it off as a thing I'll sort in the future but then I saw the bill for leaving this dead environment around and unable to kill it off! So time to act! 

### Expected behavior

Deleting either via the UI or the CLI should kill off the environment.

Even better if a delete fails due to nothing I've done then stop billing me until its sorted :D

### Reproduction steps

Use the local setup command line from the console:

`amplify pull --appId 1234567890 --envName staging`

Browser opens, tells me my environment is invalid and I should select another. My enviroment is listed in the drop down, selecting it fails with the same error.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1674590/161735092-e9e1727d-6be5-48ca-b9bd-4eed6f814dee.png">

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

This was raise before Christmas originally but I had to park it due to deadlines https://github.com/aws-amplify/amplify-cli/issues/9317

Now really need to get these cleaned up and stop losing money on them.

**Comment by PeteDuncanson** [comment]
Now I can't delete another environment either, different error this time. Pulled it down via the "local setup" cli command. Ran `amplify env remove live` and it then asks me to pick an authorisation type (while telling me it is actually doing the delete in the cloud) and then fails no matter what type I pick.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1674590/161747777-c19af240-0333-497b-911b-c7630fa95490.png">

**Comment by parvusville** [comment]
I faced similar issue, maybe this helps? https://github.com/aws-amplify/amplify-cli/issues/9880#issuecomment-1057329757
