### ISSUE TITLE
Is it possible to connect amplify React frontend to a lambda created from the aws console (Not from amplify cli) within the same vpc?

### ISSUE THREAD

**Issue by ahlag** [aws-amplify/amplify-cli#10120]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
New category

**Amplify CLI Version**

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Amplify, Application Load Balancer, Lambda, API Gateway

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
We are considering connecting our React app deployed in frontend to a Lambda we have created in the aws console. Is it possible to connect them within the same VPC?

**Comment by josefaidt** [comment]
Hey @ahlag :wave: thanks for raising this and apologies for the delay here! Are you still experiencing this issue? This workflow (connecting to resources behind a VPC) is currently not supported, however this does appear similar to the following feature requests where folks have posted suitable workarounds https://github.com/aws-amplify/amplify-cli/issues/32#issuecomment-506720192

**Comment by ahlag** [comment]
@josefaidt 
Thank you so much for getting back. We have found a workaround.
