### ISSUE TITLE
Setting an existent lambda trigger to many @models

### ISSUE THREAD

**Issue by alphonse92** [aws-amplify/amplify-cli#10121]
Hi. Is there a way to set the same lambda trigger to many @models using the amplify cli? How? `amplify update function` not supports that feature.

**Comment by edwardfoyle** [comment]
@alphonse92 what do you mean by a lambda trigger on a model? are you using the @function directive? If so, multiple @function directives can point to the same lambda. Check out the docs on that here: https://docs.amplify.aws/cli-legacy/graphql-transformer/function/
