### ISSUE TITLE
Command Issue Still unable to resolve

### ISSUE THREAD

**Issue by RFason** [aws-amplify/amplify-cli#10135]
Hey @RFason thanks for clarifying. Moving forward I would make sure:

- Node and NPM are installed
- `npm bin -g` is a part of our `PATH` environment variable
- after `@aws-amplify/amplify-cli` is installed with `npm i -g @aws-amplify/amplify-cli`, we can confirm the binary is available with `which amplify`

For reference, we can alternatively use a Node version manager like [nvm](https://github.com/nvm-sh/nvm), more info can be found on the [npm docs](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-nodejs-and-npm)

We can also set a custom [npm prefix](https://docs.npmjs.com/cli/v8/commands/npm-prefix)

With that I will close this issue for now, however if needed we can re-open to investigate further. Please use the NPM docs as a point of reference for troubleshooting globally installed packages and binaries not available

_Originally posted by @josefaidt in https://github.com/aws-amplify/amplify-cli/issues/10127#issuecomment-1089142416_

- Node is installed  -v16.14.2
-NPM is installed. -8.5.0
-NVM is installed

Still unable to install Amplify CLI

**Comment by RFason** [comment]
Tried using -  npm i -g @aws-amplify/amplify-cli

Received this error

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-amplify%2famplify-cli - Not found
npm ERR! 404 
npm ERR! 404  '@aws-amplify/amplify-cli@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by josefaidt** [comment]
Hey @RFason my apologies the npm package name is `@aws-amplify/cli`

**Comment by josefaidt** [comment]
I've also re-opened the other issue and will be closing this in favor of tracking existing issue. In the future, please consider filing an issue using our structured [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml), which can help us gather additional context around your environment and the issue you're experiencing.
