### ISSUE TITLE
@hasOne and @belongsto is NOT bidirectional

### ISSUE THREAD

**Issue by bergmorten** [aws-amplify/amplify-cli#10133]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

node 16

### Amplify CLI Version

7.6.25

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Models and VTL created for @hasOne and @belongsTo is not connected.

### Expected behavior

Should work as described by [cli docs](https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship). Models of hasOne and belongsTo should reference each other. 

### Reproduction steps

I've responded to the other ticket #9958 , but It seems that no one is follow up old tickets?

For a demo I've recreated the example in [cli docs](https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship)

The expected behavior is that hasOne and belongsTo should behave similar to hasMany and belongsTo. The cli docs describes has one like this:

_Has One: Create a one-directional one-to-one relationship between two models. For example, a Project "has one" Team. This allows you to query the team from the project record._

_Belongs To relationship: Make a "has one" or "has many" relationship bi-directional with the @belongsTo directive._

<details><summary>Model:</summary>

```graphql
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
}

type Project @model {
  id: ID!
  name: String
  team: Team @hasOne
}

type Team @model {
  id: ID!
  name: String!
  project: Project @belongsTo
}
```

</details>

Then I set up a team and try to connect the project to the team.

<details><summary>Mutations:</summary>

```graphql
mutation MyMutation {
  createTeam(input: {name: "test team1"}) {
    id
  }
}
### Response 
{
  "data": {
    "createTeam": {
      "id": "d83d577a-cf84-4a59-a2c7-0dffdab03218"
    }
  }
}
### end response

mutation CreateProject {
  createProject(input: {name: "New Project", projectTeamId: "d83d577a-cf84-4a59-a2c7-0dffdab03218"}) {
    id
    name
    team {
      id
      name
      project {
        id
        name
      }
    }
  }
}

### Response 
{
  "data": {
    "createProject": {
      "id": "c3f685f2-ef36-4914-b456-95dbe5be3b41",
      "name": "New Project",
      "team": {
        "id": "d83d577a-cf84-4a59-a2c7-0dffdab03218",
        "name": "test team1",
        "project": null
      }
    }
  }
}
### end response
```

</details>

You can see that the last response that team d83d577a-cf84-4a59-a2c7-0dffdab03218 is not connected to project. This is verified with a full query.

<details><summary>Query:</summary>

```graphql

query MyQuery {
  listTeams {
    items {
      id
      teamProjectId
      project {
        name
        id
      }
      name
    }
  }
  listProjects {
    items {
      id
      name
      projectTeamId
      team {
        name
        id
      }
    }
  }
}

{
  "data": {
    "listTeams": {
      "items": [
        {
          "id": "d83d577a-cf84-4a59-a2c7-0dffdab03218",
          "teamProjectId": null,
          "project": null,
          "name": "test team1"
        }
      ]
    },
    "listProjects": {
      "items": [
        {
          "id": "c3f685f2-ef36-4914-b456-95dbe5be3b41",
          "name": "New Project",
          "projectTeamId": "d83d577a-cf84-4a59-a2c7-0dffdab03218",
          "team": {
            "name": "test team1",
            "id": "d83d577a-cf84-4a59-a2c7-0dffdab03218"
          }
        }
      ]
    }
  }
}
```

</details>

When I look at the internal schema generated by amplify cli (amplify\backend\api\awstest\build\schema.graphql) , the models do not have any connections....

<details><summary>Internal schema:</summary>

```graphql

type Project {
  id: ID!
  name: String
  team: Team
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  projectTeamId: ID
}

type Team {
  id: ID!
  name: String!
  project: Project
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  teamProjectId: ID
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelProjectConnection {
  items: [Project]!
  nextToken: String
}

input ModelProjectFilterInput {
  id: ModelIDInput
  name: ModelStringInput
  and: [ModelProjectFilterInput]
  or: [ModelProjectFilterInput]
  not: ModelProjectFilterInput
  projectTeamId: ModelIDInput
}

type Query {
  getProject(id: ID!): Project
  listProjects(filter: ModelProjectFilterInput, limit: Int, nextToken: String): ModelProjectConnection
  getTeam(id: ID!): Team
  listTeams(filter: ModelTeamFilterInput, limit: Int, nextToken: String): ModelTeamConnection
}

input ModelProjectConditionInput {
  name: ModelStringInput
  and: [ModelProjectConditionInput]
  or: [ModelProjectConditionInput]
  not: ModelProjectConditionInput
  projectTeamId: ModelIDInput
}

input CreateProjectInput {
  id: ID
  name: String
  projectTeamId: ID
}

input UpdateProjectInput {
  id: ID!
  name: String
  projectTeamId: ID
}

input DeleteProjectInput {
  id: ID!
}

type Mutation {
  createProject(input: CreateProjectInput!, condition: ModelProjectConditionInput): Project
  updateProject(input: UpdateProjectInput!, condition: ModelProjectConditionInput): Project
  deleteProject(input: DeleteProjectInput!, condition: ModelProjectConditionInput): Project
  createTeam(input: CreateTeamInput!, condition: ModelTeamConditionInput): Team
  updateTeam(input: UpdateTeamInput!, condition: ModelTeamConditionInput): Team
  deleteTeam(input: DeleteTeamInput!, condition: ModelTeamConditionInput): Team
}

type Subscription {
  onCreateProject: Project @aws_subscribe(mutations: ["createProject"])
  onUpdateProject: Project @aws_subscribe(mutations: ["updateProject"])
  onDeleteProject: Project @aws_subscribe(mutations: ["deleteProject"])
  onCreateTeam: Team @aws_subscribe(mutations: ["createTeam"])
  onUpdateTeam: Team @aws_subscribe(mutations: ["updateTeam"])
  onDeleteTeam: Team @aws_subscribe(mutations: ["deleteTeam"])
}

type ModelTeamConnection {
  items: [Team]!
  nextToken: String
}

input ModelTeamFilterInput {
  id: ModelIDInput
  name: ModelStringInput
  and: [ModelTeamFilterInput]
  or: [ModelTeamFilterInput]
  not: ModelTeamFilterInput
  teamProjectId: ModelIDInput
}

input ModelTeamConditionInput {
  name: ModelStringInput
  and: [ModelTeamConditionInput]
  or: [ModelTeamConditionInput]
  not: ModelTeamConditionInput
  teamProjectId: ModelIDInput
}

input CreateTeamInput {
  id: ID
  name: String!
  teamProjectId: ID
}

input UpdateTeamInput {
  id: ID!
  name: String
  teamProjectId: ID
}

input DeleteTeamInput {
  id: ID!
}
```
</details>

### GraphQL schema(s)

<details>

```graphql
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
}

type Project @model {
  id: ID!
  name: String
  team: Team @hasOne
}

type Team @model {
  id: ID!
  name: String!
  project: Project @belongsTo
}
```

</details>

**Comment by edwardfoyle** [comment]
Hi @bergmorten the hasOne <=> belongsTo relationship is slightly different than hasMany <=> belongsTo.

Using your schema as an example, here's what happens with `@hasMany`:
```graphql
type Project @model {
  id: ID!
  name: String
  teams: [Team] @hasMany
}

type Team @model {
  id: ID!
  name: String!
  project: Project @belongsTo
}
```
In this case, Amplify will configure the Team records to have a `projectTeamId` field which stores the foreign key to the Project. A request for Project.teams will perform a query operation on the Team table looking for that project id. A request for Team.project will use the `projectTeamId` stored in the record to get the corresponding project record. Note that the Project records do not have any foreign key to Team records in this case. The Project record uses its own id when looking up Team records

Now let's look at your actual schema:
```graphql
type Project @model {
  id: ID!
  name: String
  team: Team @hasOne
}

type Team @model {
  id: ID!
  name: String!
  project: Project @belongsTo
}
```
In this case, both the Project and Team records have a `projectTeamId` field that stores the foreign key to the other model. So for the bidirectional relationship to work, both records must have the id of the other set. This can be accomplished with the following mutation:
```graphql
mutation MyMutation {
  createTeam(input: {id: "team-id-1", name: "my team", teamProjectId: "proj-id-1"}) {
    id
  }
  createProject(input: {id: "proj-id-1", name: "my proj", projectTeamId: "team-id-1"}) {
    id
  }
}
```
and tested with this query:
```graphql
query MyQuery {
  getTeam(id: "team-id-1") {
    project {
      id
      name
      team {
        id
        name
      }
    }
  }
}
```
which returns:
```json
{
  "data": {
    "getTeam": {
      "project": {
        "id": "proj-id-1",
        "name": "my proj",
        "team": {
          "id": "team-id-1",
          "name": "my team"
        }
      }
    }
  }
}
```

The underlying reason for this difference is `@hasMany` is using DynamoDB query operations under the hood whereas `@hasOne` is using DynamoDB getItem operations. The query operation is against a GSI that uses the Project id as an index. The getItem operation request the id of the record being queried.

**Comment by bergmorten** [comment]
@edwardfoyle  Then the both the documentation and example in the cli doc is wrong? https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship

_Make a "has one" or "has many" relationship bi-directional with the @belongsTo directive._ 

**From example in cli doc, it states that create project with a team, will return a team referring back to project.**
```graphql

mutation CreateProject {
  createProject(input: { name: "New Project", teamID: "a-team-id"}) {
    id
    name
    team { # query team from project
      id
      name
      project { # bi-directional query: team to project
        id
        name
      }
    }
  }
}

```

**Comment by walkingtospace** [comment]
I am stuck in the same issue. seems the documentation is wrong or misleading?

**Comment by SaileshKumar** [comment]
@edwardfoyle  wanted to follow up here in case it got buried, is the documentation misleading or is there a way to set up a bidirectional 1:1 relationship where you can create model B and be able to query from model A without having to update A?

**Comment by MaximilianoCidron** [comment]
I'm having the same problem currently with the hasMany/belongsTo and hasOne/belongsTo, I can't query ítems from model B without having to update or query item A again.

**Comment by majirosstefan** [comment]
Since this has been mentioned in multiple issues -
([here](https://github.com/aws-amplify/amplify-category-api/issues/1184), [here](https://github.com/aws-amplify/amplify-cli/issues/556), [here](https://github.com/aws/aws-appsync-community/issues/159)) - I am writing my workaround which is explained below: 


### **_Use Case_**
_1. I want 1 **_Call_** to have exactly 1 **_Review_** (**1:1 relationship**). 
2. E.g. when creating **Review** object, I do not want to also update **_Call_** object.
3. When querying **Call** objects, I want AppSync to auto populate **Review** object inside **Call** object.
4. When **Review** is deleted, **Call** object remains unchanged._

### **_Workaround_**
**The workaround** is that the **application layer is responsible for linking Call and Review objects by ID** (Call ID needs to be the same as Review ID) // you would need to handle it on your own in your app logic.

Then - by using similar schema like this one - each AppSync operation should  give you the data you probably needed :  

```
type Call @model  {
  id: ID!
  review: Review @hasOne(fields: ["id"])
}

type Review @model  {
  id: ID!  
  rating: Int!
  call: Call @hasOne(fields: ["id"])
}
```

### **AppSync Results**

<img width="1759" alt="Screenshot 2024-03-13 at 3 25 22 PM" src="https://github.com/aws-amplify/amplify-cli/assets/44647381/b7cd8bc3-044f-4bbe-b8a4-0c7484430c9b">

### **Weak points**

The only "maybe-problem" that I see when writing this comment could be during data deletion (e.g. if **Call** is deleted, the **Review** should be deleted too) - but this can be handled easily in your code, using DynamoDB streams, etc.

**Comment by yupm** [comment]
Why is this closed? I am also encountering this bug.
