### ISSUE TITLE
Custom Cognito Invitation Message without {username}

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#10148]
### Is this feature request related to a new or existing Amplify category?

auth

### Describe the feature you'd like to request

In the Custom Message Cognito Lambda trigger, you are required to include {username} and {####} in your custom message for CustomMessage_AdminCreateUser. My app uses email and preferred_username aliases and the username is not something the user should see or know. 

### Describe the solution you'd like

There are a few options: I'd like to either be able to ignore {username} all together or specify {email} instead

### Describe alternatives you've considered

For now I'm going to include {username} but using html set the color to white and size to 0px. Unfortunately this will still prevent me from sending an SMS invitation. Especially considering the character limit for SMS is 140 characters and the usernames are very long

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by julien-tamade** [comment]
Actually as I dug deeper, I realize that you can't actually login with any of the aliases when status is FORCE_CHANGE_PASSWORD, so this is now a feature request that that functionality is enabled as well

**Comment by ykethan** [comment]
Hello @julien-tamade, wanted to follow up on this. Please do let us know if you are facing any issues.

**Comment by ykethan** [comment]
closing the issue due to inactivity. Please do reach out to us again.
