### ISSUE TITLE
Unable to list the connected table's fields in has many relationship

### ISSUE THREAD

**Issue by Priyangacdi** [aws-amplify/amplify-cli#10140]
I'm trying to connect two tables with `@connection(name: "ConnectionName")`. But I can't able to list the connected table's data in a single list query. In get query I can get all the fields.

Example:

Two tables - Authors and Books

One Author has many Books

I have the below code in my schema.graphql file

```
type Author
@model(subscriptions: null)
@auth(rules: [{
    allow: owner, 
    operations: [read, create, update, delete]}]) {
  id: ID!
  authorName: String!
  books: [Book] @connection(name: "Books")
}

type Book
@model(subscriptions: null) {
  id: ID!
  title: string!
  authorId: Author @connection(name: "Books")
}

```
From the above schema the queries and mutations will be generated automatically as below.

**getAuthor Query**
```
export const getAuthor = /* GraphQL */ `
  query GetAuthor($id: ID!) {
    getAuthor(id: $id) {
      id
      authorName
      books {
        items {
          id
          title
          createdAt
          updatedAt
        }
        nextToken
      }
      createdAt
      updatedAt
    }
  }
`;
```
**listAuthor Query**
```
export const listAuthors = /* GraphQL */ `
  query LisAuthors(
    $filter: ModelAuthorFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listAuthors(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        authorName
        books {
          nextToken
        }
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
```
Here my expectation is to get the list of authors along with their books in a single query which is `listAuthors`. But I can get only nextToken from the books table in that listAuthors query.

**Comment by edwardfoyle** [comment]
Hi @Priyangacdi if this is a new project, I would highly recommend you use the new transformer which uses `@hasMany` and `@belongsTo` to accomplish the connection you are trying to set up: https://docs.amplify.aws/cli/graphql/data-modeling/#setup-relationships-between-models

If you need to use the transformer v1, see the docs here on how to set up a has-many <=> belongs-to relationship: https://docs.amplify.aws/cli-legacy/graphql-transformer/connection/#belongs-to
