### ISSUE TITLE
Amplify CLI executable crashes on Debian 11 after upgrading to CLI version 8.0.0

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#10156]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

` $ sudo npm -g install @aws-amplify/cli@8.0.0`

### If applicable, what version of Node.js are you using?

v14.19.1       (and npm version is 8.6.0)

### Amplify CLI Version

8.0.0

### What operating system are you using?

Debian 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Everything worked up to and including CLI version 7.6.26. 

But when I upgraded just now to version 8.0.0, nothing worked.  

```
> sudo npm -g install @aws-amplify/cli@8.0.0

added 15 packages, and audited 16 packages in 2m

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
> amplify --version
Pkg: Error reading from file.
```

NOTE: repeating this a dozen times today I noticed there was always a delay at the very end of the npm install command - it loads everything from the network quickly but then the installation does not end for several full minutes, before terminating with no complaints, this final delay seems unusual.

### Expected behavior

I expected the npm install command to result in a working amplify executable.

### Reproduction steps

1. Run `sudo npm -g install @aws-amplify/cli@8.0.0`
2. Run `amplify --version`

If reproduced, you should see the error message: "Pkg: Error reading from file."

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @dorontal :wave: thanks for raising this! Can you try installing the CLI without using `sudo`? If you are receiving `EACCES` issues when installing packages globally, please refer to [this npm doc](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more information on how to resolve global installation issues.

**Comment by dorontal** [comment]
@josefaidt just tried installing with no sudo. Then I ran the amplify binary that was deposited in `./node_modules/.bin/amplify` and it works, at least it gives an answer when you do `amplify --version`. Thanks!
