### ISSUE TITLE
Do make "amplify push" works after "amplify remove auth && amplify add auth"

### ISSUE THREAD

**Issue by alphonse92** [aws-amplify/amplify-cli#10153]
### Is this feature request related to a new or existing Amplify category?

auth, api

### Is this related to another service?

cognito, appsync

### Describe the feature you'd like to request

Today there is not a straightforward way to reset your Cognito user pool. Because after you run: `amplify remove auth` and the `amplify push`  you will get an exception caused by this: https://github.com/aws-amplify/amplify-cli/issues/172 The workaround purposed there is super dirty. The real solution to creating a new auth service after removing it is:

1. `amplify update api`
2. Select Rest or Graphql (what you already selected)
3. Select `Authorization modes`
4. Then select ` Amazon Cognito User Pool` Obviously it does not exist because you removed it. It will know and the amplify let you create a new on
5. After that you can run `amplify push` without throwing any exception.

### Describe the solution you'd like

Just run:

1. `amplify remove auth`
2. `amplify add auth`
3. `amplify push`
4. Pushed without any exception, API should be updated with the new auth config. Too much? You already do!

### Describe alternatives you've considered

Quit amplify! Come on!

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @alphonse92 :wave: thanks for raising this! This issue will be fixed on the release of https://github.com/aws-amplify/amplify-cli/pull/10072. I will link this issue and mark as a duplicate bug 🙂

**Comment by josefaidt** [comment]
Closing due to [release of Amplify CLI 8.0.1](https://github.com/aws-amplify/amplify-cli/releases/tag/v8.0.1)
