### ISSUE TITLE
could you include the environment into aws-exports

### ISSUE THREAD

**Issue by h0ru5** [aws-amplify/amplify-cli#1015]
**Is your feature request related to a problem? Please describe.**
We are using a different cognito user pool when using dev and prod, so I need to change the domain for cognito based on the environment.

**Describe the solution you'd like**
to have stateless code, I want to choose the domain based on the environment (basically is it prod or not)

**Describe alternatives you've considered**
using same userpool for prod&dev - don't want my customers to log into beta

**Additional context**
amonge the generated variables in aws-exports, please include the amplify environment (and while at it best also `git describe` - makes test results so much easier to handle)

**Comment by kaustavghosh06** [comment]
@h0ru5 We are currently working on the hosted UI support as a part of the CLI which would enable you to specify the domain-name per env.

**Comment by h0ru5** [comment]
I like. would be great to have hosted UI in the CLI.

**Comment by kaustavghosh06** [comment]
With our new version of the CLI (>1.4.0), we've introduced Hosted-UI/Outh flow as a part of the CLI flow. Please feel free to check it out and re-open/comment on this issue if you see a problem with it.
