### ISSUE TITLE
Amplify 8.0.0 not install a compiled binary object

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-cli#10160]
Is there any documentation on what has happened with the 8.0 release?

It appears that all the amplify packages have now been compiled down into a binary which is installed via download then the cli is installed

I assume this is for speed purposes?

My concern is I can no longer monkey patch (I was doing this using diff against node_modules) to incorporate PRs that have been provided to the project and not merged for months.

**Comment by sachscode** [comment]
Hi @johnf 
Could you please share the PRs which you rely upon - in addition to the below mentioned.
[10091](https://github.com/aws-amplify/amplify-cli/pull/10091) ,
[9095](https://github.com/aws-amplify/amplify-cli/pull/9095)

**Comment by johnpc** [comment]
We are now vending platform specific binaries, primarily for security reasons. See https://github.com/aws-amplify/amplify-cli/pull/10042 for more information. The packaged binaries allow us to guarantee that our dependencies are tested, preventing [supply chain attacks](https://blog.sonatype.com/npm-libraries-colors-and-faker-sabotaged-in-protest-by-their-maintainer-what-to-do-now) a la `ua-parser-js` and `colors`.

If you want to do some monkey patching, I'd recommend cloning this repo and using our `amplify-dev` symlink. If you must use an npm installation, we still vend `@aws-amplify/cli-internal` which works as `@aws-amplify/cli` worked in 7.x, but we do not recommend this as it is vulnerable to npm supply chain attacks.

**Comment by johnf** [comment]
@johnpc That makes sense, it's a pretty major change however and could do with a blog post or extra documentation somewhere

@sachscode #9095, multi env across different accounts is extremely painful without it

Thanks both
