### ISSUE TITLE
"GraphQL error: Unauthorized" when calling api from a lambda function

### ISSUE THREAD

**Issue by nxia416** [aws-amplify/amplify-cli#10178]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Function, GraphQL API

**Amplify CLI Version**
7.6.26

**What AWS Services are you utilizing?**
Amplify, lambda functions, AppSync APIs 

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

[logic]
The basic logic is: I have a user model and the user can update the model by updating the address. However, there is always a unauthorized problem from the local mock.

[error]
From http://localhost:20002/, `bindProfile` is not working. But if I select "Auth - User Pool" with a configured user. I can successfully call the `getUser` and `listUsers` functions. 

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1368781/162559925-95e01f77-d68c-4f14-84ad-473696debd7d.png">

[code]
here is the graphql API:

    type User
      @model
      @auth(
        rules: [
          { allow: groups, groups: ["admin"], operations: [read, update] }
          { allow: owner }
          {
            allow: private
            provider: iam
            operations: [read, update, create, delete]
          } # add for function calls
          {
            allow: private
            provider: userPools
            operations: [read, update, create, delete]
          } # add for function calls
        ]
      ) {
      id: ID!
      email: String!
    }
    
    type Mutation {
      bindProfile(address: String!, scholar_url: String!): User
        @function(name: "bindProfile-${env}")
        @auth(rules: [{ allow: private, provider: userPools }])
    }

here is the function js:

    /* Amplify Params - DO NOT EDIT
      API_PROJECTSCHOLAR1_GRAPHQLAPIENDPOINTOUTPUT
      API_PROJECTSCHOLAR1_GRAPHQLAPIIDOUTPUT
      ENV
      REGION
    Amplify Params - DO NOT EDIT */

    const AWSAppSyncClient = require("aws-appsync").default;
    const gql = require("graphql-tag");
    global.fetch = require("node-fetch");
    const AWS = require("aws-sdk");

    let graphqlClient;

    const getUser = /* GraphQL */ `
      query GetUser($id: ID!) {
        getUser(id: $id) {
          id
          email
        }
      }
    `;

    /**
     * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
     */
    exports.handler = async (event, context, callback) => {
      console.log(`EVENT: ${JSON.stringify(event)}`);

      env = process.env;
      console.log(env);

      AWS.config.update({
        region: env.REGION,
        credentials: new AWS.Credentials(
          env.AWS_ACCESS_KEY_ID,
          env.AWS_SECRET_ACCESS_KEY,
          env.AWS_SESSION_TOKEN
        ),
      });
      const credentials = AWS.config.credentials;
      console.log(credentials);

      if (!graphqlClient) {
        graphqlClient = new AWSAppSyncClient({
          url: env.API_PROJECTSCHOLAR1_GRAPHQLAPIENDPOINTOUTPUT,
          region: env.REGION,
          auth: {
            type: "AWS_IAM",
            credentials,
          },
          disableOffline: true,
        });
      }

      const res = await graphqlClient.query({
        query: gql(getUser),
        variables: { id: "ea3256d2-9ead-4bde-bdcf-96ede4b66571" },
      });

      return {
        statusCode: 200,
        //  Uncomment below to enable CORS requests
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Headers": "*",
        },
        body: {
          "todo.."
        },
      };
    };

[env] here is the env and credentials

    {
      ENV: 'dev',
      REGION: 'ap-southeast-1',
      API_PROJECTSCHOLAR1_GRAPHQLAPIIDOUTPUT: 'g3z3yhuztreg5cyn5tixxxxxxxx',
      API_PROJECTSCHOLAR1_GRAPHQLAPIENDPOINTOUTPUT: 'http://localhost:20002/graphql',
      API_PROJECTSCHOLAR1_GRAPHQLAPIKEYOUTPUT: 'apiprojectscholar1GraphQLAPIKeyOutput',
      AWS_ACCESS_KEY_ID: 'AKIAXB4REQEBxxxxxxxx',
      AWS_SECRET_ACCESS_KEY: '1ctIQOsAdMXb/cMYjj0YlITvEYXeayVvxxxxxxxx',
      _X_AMZN_TRACE_ID: 'amplify-mock-x-amzn-trace-id',
      AWS_EXECUTION_ENV: 'AWS_Lambda_amplify-mock',
      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: '128',
      AWS_LAMBDA_FUNCTION_VERSION: '1',
      AWS_LAMBDA_INITIALIZATION_TYPE: 'on-demand',
      AWS_LAMBDA_LOG_GROUP_NAME: 'amplify-mock-aws-lambda-log-group-name',
      AWS_LAMBDA_LOG_STREAM_NAME: 'amplify-mock-aws-lambda-log-stream-name',
      TZ: 'UTC',
      _HANDLER: 'index.handler',
      AWS_REGION: 'ap-southeast-1',
      AWS_LAMBDA_FUNCTION_NAME: 'bindProfile',
      LAMBDA_TASK_ROOT: '/Users/test/project-scholar1/amplify/backend/function/bindProfile',
      LAMBDA_RUNTIME_DIR: '/Users/test/project-scholar1/amplify/backend/function/bindProfile',
      __CF_USER_TEXT_ENCODING: '0x1F6:0x0:0x0'
    }
    Credentials {
      expired: false,
      expireTime: null,
      refreshCallbacks: [],
      accessKeyId: 'AKIAXB4REQEBCxxxxxxx',
      sessionToken: undefined
    }

[question] I notice that `sessionToken` is `undefined`. Is this the problem? I tried to call `getUser` with `IAM (UnAuth Role)` and can get a similar `Unauthorized` error.
![image](https://user-images.githubusercontent.com/1368781/162560338-71e5ea86-dd39-4e2a-ae8d-f5f0bac529ff.png)

**Comment by LaurensBrinker** [comment]
When you use a local mock, to test IAM authorization with your lambda function, you must use the mock credentials.

```
"accessKeyId": "ASIAVJKIAM-AuthRole", 
"secretAccessKey": "fake"
```

This issue is discussing the same problem as yours - and will provide more info: https://github.com/aws-amplify/amplify-cli/issues/9100#issuecomment-1087844171

It should be an easy fix, consider changing your code where you create your AppSync client to something similar to mine:
```
const AWS = require('aws-sdk')
const AWSAppSyncClient = require('aws-appsync').default;
require('cross-fetch/polyfill');

const mockCredentials = { 
	"accessKeyId": "ASIAVJKIAM-AuthRole", 
	"secretAccessKey": "fake"
}

const credentials = AWS.config.credentials || mockCredentials

exports.appsync = new AWSAppSyncClient({
	url: process.env.API_<APINAME>_GRAPHQLAPIENDPOINTOUTPUT,
	region: process.env.REGION,
	auth: {
		type: 'AWS_IAM',
		credentials: credentials,
	},
	disableOffline: true,
});
```

**Comment by julien-tamade** [comment]
Another thing to note is that your model isn't setup for iam permission. So when you're trying to evoke the api from the lambda, it's unable to access the model.

adding:
@auth(rules: [{ allow: public/private, provider: iam }]) 

I believe would solve it

**Comment by nxia416** [comment]
> Another thing to note is that your model isn't setup for iam permission. So when you're trying to evoke the api from the lambda, it's unable to access the model.
> 
> adding: @auth(rules: [{ allow: public/private, provider: iam }])
> 
> I believe would solve it

You mean the User model, right? I added that as one of the 4 rules:

`
    @auth(
      rules: [
        { allow: groups, groups: ["admin"], operations: [read, update] }
        { allow: owner }
        {
          allow: private
          provider: iam
          operations: [read, update, create, delete]
        } # add for function calls
        {
          allow: private
          provider: userPools
          operations: [read, update, create, delete]
        } # add for function calls
      ]
    ) 
`

**Comment by nxia416** [comment]
@LaurensBrinker you are awesome! I fixed it. How ever I do have local values for my `AWS.config.credentials`, so I updated the line:

`
    const credentials = process.env.AWS_EXECUTION_ENV.endsWith("mock")
      ? mockCredentials
      : AWS.config.credentials;
`

**Comment by josefaidt** [comment]
Hey @nxia416 apologies for the delay here! It seems like you are back up and running though 🙂 ! I'll close this issue for now however if you are still experiencing this please feel free to reply back and we can re-open to investigate further
