### ISSUE TITLE
How to trigger onCreate, onUpdate, onDelete using amplify function and send notification using firebase messaging

### ISSUE THREAD

**Issue by simaspoldantb** [aws-amplify/amplify-cli#10185]
Hi, I'm new user of aws amplify. I wanna ask, how to use aws amplify function (https://docs.amplify.aws/cli/function/), and there any way to trigger datastore when data onCreate, onUpdate, and on Delete like firebase function (https://firebase.google.com/docs/functions/firestore-events#trigger_a_function_when_a_new_document_is_created)

I need function like that to make counting data, and send notification using firebase messaging

**Comment by caesarisme** [comment]
The easiest way is to create rest api endpoints for this particular table and replace all Graphql mutations on client side related to this table by rest api endpoints. You may face some difficulties with rest api query authorizations

**Comment by simaspoldantb** [comment]
thank you, actually this is not what I expected. but your comment maybe the best choice for now. 
I hope, I'm not facing project using aws again. project using aws took twice time as long as usual.
