### ISSUE TITLE
Update to API on an existing repo when there are no changes

### ISSUE THREAD

**Issue by roychoo** [aws-amplify/amplify-cli#1018]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
Wanted to share the repo with team. But cloning the repo with no change results a change to API on ```amplify push```. there is also changes to ```schema.json```.

**To Reproduce**
1. git clone https://gitlab.com/roychoo/test
2.```amplify init```
3. use existing environment; master
4. ```amplify push```
5. recorded changes to API 
6. ```schema.json``` is changed for some reasons

**Expected behavior**
Would expect no change needed for push, no change to schema.json

**Screenshots**
![image](https://user-images.githubusercontent.com/1853311/54136732-48754800-4457-11e9-984d-edfe8d0ee106.png)
![image](https://user-images.githubusercontent.com/1853311/54137128-04cf0e00-4458-11e9-80fb-759c9ca57e4d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
```amplify-cli 1.1.7```

**Comment by kaustavghosh06** [comment]
@roychoo You could probably put the schema.json file in .gitignore given that it is a runtime file for code-gen

**Comment by roychoo** [comment]
@kaustavghosh06 thanks, what about the update to API? is that normal? given that it was a fresh repo?

**Comment by roychoo** [comment]
sorry can reopen? accidentally click on it

**Comment by roychoo** [comment]
sorry click accidentally.

**Comment by kaustavghosh06** [comment]
@roychoo Yes it is normal to put it in gitignore since codegen would fetch a version of the schema.json each time there an update to the schema.

**Comment by roychoo** [comment]
@kaustavghosh06 Sorry i mean there was no change to schema, i just checked it out from the repo and run amplify push and see that there is an update to the API category which baffles me. I am using the multienv feature.

**Comment by kaustavghosh06** [comment]
@roychoo We fetch the schema.json directly from the AWS AppSync service so there might've been a recent service side change which changed the Int types to Float types for your schema. What does your GraphQL schema look like?

**Comment by roychoo** [comment]
like this..

```
type QuestionAnswer @model @searchable {
  id: ID!
  questions: [String]
  answer: String
}
```

**Comment by roychoo** [comment]
@kaustavghosh06 any updates on this?
To add on, when i do ```amplify init``` it always update the stack even though there is no changes to the stack. Is this expected?

**Comment by roychoo** [comment]
closing this issue, it seems that when i first using multienv, it did a migration on the templates and seems something went wrong. After when i delete and re-add again, it does not happen again.

**Comment by Monder87** [comment]
same problem here, after clone the repo i got :
```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | dnai          | Update    | awscloudformation |
| Auth     | dnaia8c6ea84  | No Change | awscloudformation |
```
but the api should be the same
