### ISSUE TITLE
Where do I add permissions when using amplify-cli?

### ISSUE THREAD

**Issue by bwobbones** [aws-amplify/amplify-cli#1019]
** Which Category is your question related to? **
API/Function

** What AWS Services are you utilizing? **
Lambda/DynamoDB

** Provide additional details e.g. code snippets **
I have a lambda that gathers data from DynamoDB that i created using the cli.

When I execute it, I get a permission error:

`User: blah is not authorized to perform: dynamodb:DescribeTable`

This is easy enough to fix, I added the DynamoDB permissions required through the console but this feels bad.  I could edit the cloudformation template, adding the permissions there before `push`ing the changes up.  But the template is generated, that also feels bad.

Any idea where I should be doing this?  I can't find any documentation around it.

**Comment by kaustavghosh06** [comment]
@bwobbones You could probably modify the Cloudformation file in `amplify/backend/function<funcition-name>/cloudformation-file.json` file to add the perminssions.

**Comment by gregevari** [comment]
Thanks @kaustavghosh06, do you know if that file will be overwritten if I push changes?

**Comment by kaustavghosh06** [comment]
@gregevari What do you mean by if push changes? I don't beleive this file is changed dynamically by the CLI after it's created.

**Comment by gregevari** [comment]
@kaustavghosh06 pushing with `amplify push`.  I think you cover my question though, thanks!
