### ISSUE TITLE
Email option not available for "How do you want your end users to sign in?" using amplify add auth.

### ISSUE THREAD

**Issue by zhzhang** [aws-amplify/amplify-cli#102]
When configuring auth using this cli, the option for end users to sign in via email is not available as a configuration choice in the setup flow. Why is this the case, and what's the proper way to make email the sign-in method? Should I just use the username sign-in method but enforce that usernames and emails are the same?

**Comment by gustavo-rios** [comment]
I am also interested in this option, is an option in awsmobile CLI but not in Amplify CLI

**Comment by haverchuck** [comment]
When implmented, this should include email or phone_number options.

**Comment by aiwilliams** [comment]
Will this end up using the [UsernameAttributes](https://github.com/awsdocs/aws-cloudformation-user-guide/commit/33bfa503a91579857cf5bec0baace9d5d79e95f5)?

**Comment by tamsynjennifer** [comment]
I also need this. At the moment I can manually set up the "Users can use email as their "username" to sign up and sign in" option from the AWS console with MobileHub but I would really like to have the option to select it from the Amplify Cli especially since there are already the options to add other user attributes like given_name and family_name. Sign Up with email instead of a username is quite a standard case I think.

**Comment by tamsynjennifer** [comment]
Is there any update on this request? Being able to use the Amplify Cli to set up sign in with an email address instead of username? 
<img width="1083" alt="screen shot 2018-10-14 at 18 09 17" src="https://user-images.githubusercontent.com/31040727/46919798-938c4b80-cfdc-11e8-83c8-2f7e3a042df5.png">

**Comment by angineering** [comment]
I also find this a very strange and frustrating limitation. I even tried to create a new cognito and replace the one in the setup doc, but it just ended up making a NEW cognito with that given name instead (overwriting the ids etc).

**Comment by angineering** [comment]
Finally figured this out looking at the template language.
Under `Type: AWS::Cognito::UserPool` set
      ```
UsernameAttributes:
        - 'email'
```

This will create it with email instead of username setup.

**Comment by tamsynjennifer** [comment]
@angineering I am not sure I understand how you solved the problem? If you set up Cognito with the Amplify Cli (using the terminal and going through the custom set up options) it doesn't allow you to select Email as username. It gives you other options such as adding any attributes you want but not "Email as Username". Once Cognito is set up I don't seee how you can change the username setting... If you could explain in more detail how you did this I would be very grateful! Thanks

**Comment by tamsynjennifer** [comment]
@angineering Thanks! I understand now. It worked for me too! :)

**Comment by tamsynjennifer** [comment]
@rcanessa89 Did you edit the file before doing `amplify push`?

**Comment by Eduardo-Vargas** [comment]
Any updates on this?

**Comment by amirmishani** [comment]
@rcanessa89  Only one of the aliasAttributes or usernameAttributes can be set in a User pool.

**Comment by andrewjdavison** [comment]
I haven't been able to get either to work. the Amplify push command returns:

Property validation failure: [Encountered unsupported properties in {/}: [UsernameAttributes]]

This was in my config template:

`    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Ref userPoolName
      UsernameAttribues:
        - 'email'
      Schema: `

**Comment by fcwheeler** [comment]
Hee is what I did to make this work (after trying many variations:

In the YML file, add the following to the list of variables at the top of the page
` UsernameAttributes:
    Type: CommaDelimitedList`

Then, in the UserPool: section below, add the following:

` UsernameAttributes: !Ref UsernameAttributes`

Then, in the parameters.json file, add:

`"UsernameAttributes": ["email"],`


This worked for me

**Comment by comfytoday** [comment]
Adding the following to the CF template works:
```
UsernameAttributes:
        - 'email'
```
However the builtin Amplify signup forms are not compatible... at least not the aws-amplify-vue component I've tried it with. 

Even passing in a signUpFields array to try and force it to stop displaying the username field, it just sticks one in there anyway, along with a phone number saying they are both required (The Cognito console does not list them as required)

**Comment by h0raz** [comment]
@comfytoday 
not 100% sure if vue behaves the same as angular but there you need to set `hideAllDefaults` 
like
```
signUpConfig = {
    hideAllDefaults: true,
    signUpFields: [
    {
      label: 'Name',
      key: 'name',
      required: true,
      displayOrder: 1,
      type: 'text',
    },
    {
      label: 'Email',
      key: 'username',
      required: true,
      displayOrder: 2,
      type: 'email',
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 3,
      type: 'password',
    }
    ]
  };
```

**Comment by comfytoday** [comment]
@h0raz Thank you! 

Saved me some explaining....

This is the config I used in Vue. Found reference in another Github issue. It doesn't appear to be documented on the Vue side.

```
signUpConfig: {
          header: 'Sign Up',
          hideDefaults: true,
          signUpFields: [
            { ...
```

**Comment by janhesters** [comment]
```js
const signUpConfig = {
  hiddenDefaults: ['username'],
  signUpFields: [
    {
      label: 'Email',
      key: 'email',
      required: true,
      displayOrder: 1,
      type: 'string',
      custom: false
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 2,
      type: 'password',
      custom: false
    },
    {
      label: 'Phone Number',
      key: 'phone_number',
      required: true,
      displayOrder: 3,
      type: 'tel',
      custom: false
    }
  ]
};

export default withAuthenticator(App, { signUpConfig });
```
And adding:

![yamlconfig](https://user-images.githubusercontent.com/31096420/54390517-f3c60d00-46a2-11e9-8aa4-b5f723729f44.png)
 
[worked for me](https://medium.com/@jan.hesters/email-only-sign-up-with-aws-amplify-81a3d718a7f9).

**Comment by undsoft** [comment]
If anyone is wondering how they can replace Username label on the Login screen, you can "translate it":

```js

I18n.setLanguage('en');
I18n.putVocabularies({
  en: {
    'Username': 'Email'
  }
});

```

**Comment by kaustavghosh06** [comment]
With our new version of the CLI we've introduced the ability for users to select how they want users to sing in upfront as a part of the default flow instead of setting the username attribute as a default in the default flow (which is immutable unfortunately after the creation of the userpool since that is a restriction from the Cognito service). Please feel free to check it out and re-open/comment on this issue if you see a problem with it.

**Comment by vjindalaurea** [comment]
Hi @kaustavghosh06 , so now we can use specify email as login option using amplify CLI ? Can you please share more details on it ?

**Comment by kaustavghosh06** [comment]
<img width="679" alt="Screen Shot 2019-04-02 at 11 10 24 PM" src="https://user-images.githubusercontent.com/7247658/55456698-98e64e00-559c-11e9-9842-e85dfd240810.png">

In the above screenshot, I'm using the latest version of the CLI to add an auth resource. We now explicitly ask the user during this setup as to how they want their users to sign in. (This attribute is unfortunately not editable after your initial push due to Cognito service limitation)

**Comment by janhesters** [comment]
@kaustavghosh06 Great, thank you for adding this feature!

**Comment by ajhool** [comment]
I'm glad to see that this is a new feature. However, I created my project before this feature was available, so my Auth stack currently expects a: "username + email + phone number", which is way too much. I'd like to switch to Email.

I know that you can't change this setting on Cognito after you've created the Userpool, however, I'm worried that there is no way within Amplify to create a new Cognito Userpool and go through the initialization process. I don't believe that creating a new Env provides an opportunity to reconfigure Auth so that it uses Email instead of Username.

I'm still in development so I can throw users and data away.

Am I stuck? If I need to create a new project to redo the Auth initialization, is there a guide for porting configuration to a new project?

**Comment by nihp** [comment]
In my login it have both email and phone number. But I only receives code for my phone number.

I not received anything in my mail. Can anyone elaborate. How can I send the confirmation for both (Mobile and email)

**Comment by edlefebvre** [comment]
> I know that you can't change this setting on Cognito after you've created the Userpool, however, I'm worried that there is no way within Amplify to create a new Cognito Userpool and go through the initialization process. I don't believe that creating a new Env provides an opportunity to reconfigure Auth so that it uses Email instead of Username.
> 
> I'm still in development so I can throw users and data away.
> 
> Am I stuck? If I need to create a new project to redo the Auth initialization, is there a guide for porting configuration to a new project?

@ajhool did you find a solution to this?

**Comment by ianmartorell** [comment]
> <img alt="Screen Shot 2019-04-02 at 11 10 24 PM" width="679" src="https://user-images.githubusercontent.com/7247658/55456698-98e64e00-559c-11e9-9842-e85dfd240810.png">
> 
> In the above screenshot, I'm using the latest version of the CLI to add an auth resource. We now explicitly ask the user during this setup as to how they want their users to sign in. (This attribute is unfortunately not editable after your initial push due to Cognito service limitation)

How does one go about using the `Auth` module with this configuration? [The docs](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js) don't mention anything about email-only signup or signin, and the Typescript typings say `username` is required for both `Auth.signUp` and `Auth.signIn`.

**Comment by douglas-mason** [comment]
@ianmartorell if you choose email only login, the `username` property is the email address.

**Comment by ianmartorell** [comment]
@douglas-mason Oh I see! I guess that could be made more clear in the documentation but thanks!

**Comment by douglas-mason** [comment]
@ianmartorell yeah, it took me some trial and error before realizing that as well.

**Comment by Glen-Moonpig** [comment]
I chose email only login in the CLI, but the authenticator registration page still asks for a username and email address...
