### ISSUE TITLE
`git push --yes` resulting in many CloudFormation stacks being created 

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1020]
**Describe the bug**
My colleague and I discovered this bug when her API was reporting as not existing in the AppSync console.

Not really sure what to say, a screenshot is worth a thousand words:

**To Reproduce**
No idea.

**Expected behavior**
A single stack is created (or updated/modified), and that stack has valid output.

**Screenshots**
![cli-many-stacks](https://user-images.githubusercontent.com/22964702/54155281-6ae07480-4409-11e9-9b1a-1a38f2d51722.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu (WSL)

**Additional context**
This broke a development environment, hoping we can repair this so we don't have to re-create resources.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu Could you paste your colleagues `amplify/backend/amplify-meta.json` file? Maybe she's checking a different region on the console (different from where the API was actually deployed).

**Comment by jkeys-ecg-nmsu** [comment]
API seems to have reappeared (in the console), although my colleague's environment occasionally shows two API categories (one of which has no template provider...). Running `amplify init` and selecting her environment gets us back to a working project state, although API is always in Update status on "re-init".

Since there are a number of issues tracking API issues similar to this one, I'm closing this. Thanks @kaustavghosh06 for the advice!
