### ISSUE TITLE
How to choose a graphql client： Amplify Graph client, or AppSyncClient，or Axios?

### ISSUE THREAD

**Issue by nxia416** [aws-amplify/amplify-cli#10212]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

graphql, appsync

**Amplify CLI Version**

7.6.26

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

I can see there are 3 ways we can use graphql client. Is there a document for how to use which client in which case?

**method1: Amplify Graph client**

I can see the example from the document here:  https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#using-amplify-graphql-client

    // Creating a post is restricted to IAM 
    const createdTodo = await API.graphql({
      query: queries.createTodo,
      variables: {input: todoDetails},
      authMode: 'AWS_IAM'
    });

I think this is the easiest way to call graphql apis, and I am using this method from my nextjs SSR. But I do have a few question:

- Can I also use this amplify graph client in a Amplify Lambda Function? 
- How can I get and set the API_KEY from AppSync? The document doesn't mention that. Now I am having a `Server Error
Error: No api-key configured` error, when creating a public api (auth with API_KEY and `@auth(rules: [{ allow: public }])`).  

**method2: AppSyncClient**

I can see the example from: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#api-key

    import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync';
    import awsconfig from './aws-exports';

    const client = new AWSAppSyncClient({
      url: awsconfig.aws_appsync_graphqlEndpoint,
      region: awsconfig.aws_appsync_region,
      auth: {
        type: AUTH_TYPE.API_KEY,
        apiKey: awsconfig.aws_appsync_apiKey,
      },
    });

Questions:
- I can't get a `aws_appsync_apiKey` field from `<MYPROJECT>/src/aws-exports.js`. I don't have that in my local file, which has a  "WARNING: DO NOT EDIT" mark. In the file I do have a `aws_appsync_authenticationType` key as `API_KEY`.
- Is it more recommended to use AWSAppSyncClient in an amplify function rather than `await API.graphql...`? 

**method3: Axios**

I see the example here: https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#query

    const graphqlData = await axios({
      url: process.env.API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT,
      method: 'post',
      headers: {
        'x-api-key': process.env.API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT
      },
      data: {
        query: print(listTodos),
      }
    });

I know this must be a lower level implementation for a query and I guess this is not recommended...

**Comment by nxia416** [comment]
figured out the missing aws_appsync_apiKey problem: i changed the default authorization type, but didn't run `amplify push`

**Comment by nxia416** [comment]
Amplify Graph client vs. AppSyncClient vs. Axios, any suggestions?

**Comment by josefaidt** [comment]
Hey @nxia416 :wave: apologies for the delay here!! Are you still experiencing this issue? We've recently updated our documentation for [calling a GraphQL API from Lambda](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/)
