### ISSUE TITLE
How I can use the mocked Dynamo database when running mock function?

### ISSUE THREAD

**Issue by duranmla** [aws-amplify/amplify-cli#10221]
When I am creating a new lambda function that needs to do operations with my database I would like to being able to iterate locally  instead need to deploy to my development environment constantly to test. The current flow I am using to achieve this is to:

- amplify mock
- amplify mock function foo
- _choose my event file that I take from copy the event from CloudWatch_

_This works but as I am hitting Dynamo within my function I got error of permissions which somehow makes sense because I am doing this "mock run"_

**How I can allow my mock function run to hit the instance of Dynamo that AppSync uses when `amplify mock` runs?**

I found on the web this https://www.gravitywell.co.uk/insights/how-to-use-your-mocked-dynamodb-with-appsync-and-lambda/ but maybe it is outdates cause I can't make it work, I can't even pass environment variables to my lambda function to try to change the behaviour.

**Which Category is your question related to?**
storage

**Amplify CLI Version**
8.0.1

**What AWS Services are you utilizing?**
DynamoDB
AppSync

🙏 Thanks in advance!

**Comment by tmadge** [comment]
Does this help?
https://docs.amplify.aws/cli/usage/mock/#connecting-to-a-mock-model-table

**Comment by duranmla** [comment]
> Does this help?
> https://docs.amplify.aws/cli/usage/mock/#connecting-to-a-mock-model-table

I think this looks exactly as what I need, I must solve another issue I have before coming back to this need but it seems like this is the answer. Sorry for making a question that was on the docs :(
