### ISSUE TITLE
Searchable lambda function using deprecated Python version 3.6

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-cli#10236]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

6.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

add, push, update

### [Action Required] AWS Lambda end of support for Python 3.6
AWS is deprecating Python 3.6, yet that is the version used by the amplify CLI to create the function `DdbToEsFn` when making a GraphQL table `@searchable`

### Expected behavior

The CLI should not create infrastructure that reached their End-Of-Life (EOL)

### Reproduction steps

Make a table `@searchable` and check the python version in the Lambda console for the function `DdbToEsFn-[...]`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by wvidana** [comment]
Here the runtime definition https://github.com/aws-amplify/amplify-cli/blob/17b5df0f91ac17593578b6ff16f0a9b6b8ac1602/packages/amplify-graphql-searchable-transformer/src/cdk/create-cfnParameters.ts#L36-L43

**Comment by josefaidt** [comment]
Hey @wvidana :wave: thanks for raising this and great callout! Marking as a bug to increase the Python version 🙂

**Comment by rosmu** [comment]
@josefaidt @sundersc 

How should we upgrade existing DdbToES-* function on an existing project which is running on Python3.6? Will it get auto upgraded to `Python 3.8` when Amplify CLI is upgraded to `v8.2` and did a `amplify push`?

**Comment by DeniferSantiago** [comment]
In my case `amplify push` removed my `DdbToES ` function

(versión: 8.4.0)

**Comment by georgevicbell** [comment]
@DeniferSantiago how did you get it back? I have also lost it...

**Comment by DeniferSantiago** [comment]
@georgevicbell Actually now it has a new name: OpenSearchStreaming

**Comment by georgevicbell** [comment]
Thanks! Indeed it does!
