### ISSUE TITLE
amplify codegen add gives error: 'The "path" argument must be of type string'

### ISSUE THREAD

**Issue by MiMo42** [aws-amplify/amplify-cli#1023]
**Describe the bug**
Error when adding an existing API to codegen.

`amplify codegen add --apiId XXXMyApiIdXXXX `

adds "api" section to amplify-meta.json files
but then terminates with error:

```
$ amplify codegen add --apiId XXXXXXX
✔ Getting API details
✖ Getting API details
The "path" argument must be of type string. Received type undefined
```

Trying to get it up and running using statements command i got a callstack:

```
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at projects.forEach (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/statements.js:19:31)
    at Array.forEach (<anonymous>)
    at Object.generateStatements (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/statements.js:18:12)
    at Command.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/statements.js:11:21)
    at Runtime.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:13:53)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:7:71 
```

**To Reproduce**
1. A project with *no* API managed by CFN 
2. type $ amplify codegen add --apiId XXXXXX 
to add an API that has been created with AppSync console before.

**Expected behavior**
The command should successfully add the external API.

**Desktop (please complete the following information):**
 - OS: macOS
 - Amplify CLI 1.1.7

**Comment by kochetkovIT** [comment]
Just had similar problem. Solved it by adding `projectPath` attribute in `<project_root>/amplify/.config/local-env-info.json` with a valid path, worked both absolute and relative paths for me.

**Comment by MiMo42** [comment]
I am not using environments yet.
Automatic migration did not create the local-env-info.json.
I added the file manually and set projectPath like @kochetkovIT suggested.
Now codegen works for me again.

The automatic migration should have created the file though...

**Comment by kaustavghosh06** [comment]
@MiMo42 Automatic migration should've ideally created the local-env-info.json file. Did you mirate from @multinev version of the CLI or master version of the CLI?

**Comment by MiMo42** [comment]
@kaustavghosh06 
I migrated from a pre multienv era project using one of the first releases supporting multienv (I am not sure which version it actually was). I did choose the migration not to create environments during the migration process when being asked for it.
No betas involved. CLIs have been installed by npm install -g @aws-amplify/cli

**Comment by kaustavghosh06** [comment]
@MiMo42 The CLI should've created the local-env-info file with the projecPath and I tried reproducing this but couldn't. Were there any speific errors during the migration or was rhe migration successful?

@kochetkovIT Would like to know about your experience as well so that I can reproduce this.

**Comment by MiMo42** [comment]
No errors during migration. It was successful.
Migration has been performed with CLI v1.1.4

**Comment by kaustavghosh06** [comment]
@MiMo42 We weren't able to reproduce this with the latest version of the CLI. Please feel free to re-open if you see similar behavior with any of your other projects. Would like to see your pre-migration project structure if possible in case of this behavior.

**Comment by gvb26** [comment]
I am also facing this issue. I am unable to find a directory known as .config in my project folder either. Any solutions?

**Comment by yuth** [comment]
@gvb26 did you see any errors when you ran `amplify` commands? What was the version of last CLI you had run `amplify` successfully? What version do you have installed currently?
