### ISSUE TITLE
Subscriptions fail when owner claim uses custom attributes

### ISSUE THREAD

**Issue by MatthiasF999** [aws-amplify/amplify-cli#10254]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.0.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Added a custom attribute to cognito group.

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

#10199 introduces `const roleClaims = role.claim!.split(':');` in packages/amplify-graphql-auth-transformer/src/resolvers/subscriptions.ts
This breaks using custom attributes for owners, as custom attributes are prefixed with `custom:`

Possible solutions would be:

1. Revert #10199 
2. Do not split the role claim, if it starts with `custom:`

### Expected behavior

The generated auth template should look like
```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $ownerEntity0 = $util.defaultIfNull($ctx.args.owner, null) )
    #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("custom:tenant"), "___xamznone____") )
    #if( $ownerEntity0 == $ownerClaim0 )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

but it currently looks like

```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#if( $util.authType() == "User Pool Authorization" )
  #set( $ownerEntity0 = $util.defaultIfNull($ctx.args.owner.split(":")[0], null) )
  #if( !$isAuthorized )
    #set( $ownerClaim0_0 = $util.defaultIfNull($ctx.identity.claims.get("custom"), "___xamznone____") )
    #if( $ownerEntity0 == $ownerClaim0_0 )
      #set( $isAuthorized = true )
    #end
  #end
  #if( !$isAuthorized )
    #set( $ownerClaim0_1 = $util.defaultIfNull($ctx.identity.claims.get("tenant"), "___xamznone____") )
    #if( $ownerEntity0 == $ownerClaim0_1 )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

### Reproduction steps

1. Create an amplify project
2. Add auth to amplify
3. Add a custom attribute to cognito group
4. Add a graphql API
5. Add owner auth with an identity claim using the custom attribute

### GraphQL schema(s)

<details>

```graphql
type Productl
  @model
  @auth(
    rules: [
      {
        allow: owner
        identityClaim: "custom:tenant"
        operations: [create, update, read, delete]
      }
    ]
  ) {
  owner: ID @index(name: "byOwner", sortKeyFields: ["id"])
  id: ID!
  name: String!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @MatthiasF999, Thank you for informing us on this. marking this as bug.
