### ISSUE TITLE
Geo - New HERE map styles

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-cli#10290]
### Is this related to another service?

Amazon Location Service

### Describe the feature you'd like to request

About a month ago Amazon Location Service (covered by the Geo category) has added  two new map styles for the HERE provider (here the [What's New post](https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-location-service-two-here-map-styles/)).

Just tried to create a new map resource in a blank project using v8.0.2 and the aforementioned map styles are missing:
```sh
? Specify the map style. Refer https://docs.aws.amazon.com/location-maps/latest/APIReference/API_MapConfiguration.html …  (Use arrow keys or type to filter)
  Streets (data provided by Esri)
❯ Berlin (data provided by HERE)
  Topographic (data provided by Esri)
  Navigation (data provided by Esri)
  LightGrayCanvas (data provided by Esri)
  DarkGrayCanvas (data provided by Esri)
```

### Describe the solution you'd like

Be able to select the new map styles when adding a new map resource in my Amplify project:

### Describe alternatives you've considered

Creating them manually, which would defeat the purpose of the CLI.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by dreamorosi** [comment]
Just realised that the [CloudFormation page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-location-map-mapconfiguration.html) for `AWS::Location::Map MapConfiguration` does not show (yet) the new Map Styles that are instead available on the Console:
![image](https://user-images.githubusercontent.com/7353869/165147974-cac530da-513b-4026-ae98-3c7380c7fbac.png)

**Comment by dreamorosi** [comment]
Did some further research and tried to deploy a map resource using one of the two new styles using CDK (which I see is what you use under the hood):
```ts
new CfnMap(this, 'Map', {
      mapName: 'test-map',
      pricingPlan: 'RequestBasedUsage',
      configuration: {
        style: 'VectorHereExplore',
      }
});
```
And was able to deploy successfully:
![image](https://user-images.githubusercontent.com/7353869/165149311-21e171d1-e6d3-4836-8db6-6ff035ffffa3.png)

It must be a documentation issue, will leave a feedback on the page to try to fix it.

If welcome, I'd be happy to open a PR for this change. From what I see most of the action needs to happen [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-geo/src/service-utils/mapParams.ts#L26-L28) and [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-geo/src/service-walkthroughs/mapWalkthrough.ts#L85-L90).

**Comment by dreamorosi** [comment]
As linked above there's already a PR open.

That PR, instead of just introducing the new styles also changes the default map style (and has some issues around linting and usage of the provider's name). For what it's worth I don't think the default provider should change and definitely this should not come from a first time contribution.

Happy to work with the person opening the original PR (they're an AWS Community Builder active with Amazon Location Services) or open a new one limited with the scope of adding the styles.

**Comment by dayjournal** [comment]
Thank you for creating the issue. My pull request includes changing the default map style and adding a style. Should I change my pull request only to add a style this time?

**Comment by AaronZyLee** [comment]
Thanks for bringing this out. From CLI side the change LGTM but we need additional context from library team since they consume the CLI's output. Will come back once the feedback is received from them.

**Comment by dayjournal** [comment]
@AaronZyLee 
Thank you. We are waiting for you. 🙇

**Comment by thaddmt** [comment]
@AaronZyLee think it looks good on the Amplify JS end, we don't keep any list of the styles on our end so should be good to go

**Comment by josefaidt** [comment]
Closing as PR was merged
