### ISSUE TITLE
Amplify pull updates cli.json with non-existing flags: project

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/amplify-cli#10298]
**Describe the bug**
I recently tried to push changes via cloudformation and failed.
Then I tried "amplify pull" to rever the local changes.
The command generated a line

` 
"project": {
            "overrides": true
}`

which throws error when simply running amplify status

Invalid feature flag configuration

**To Reproduce**

**Expected behavior**
Do not add invalid flags

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[] iOS

**Comment by josefaidt** [comment]
Hey @GMerakis :wave: are you still experiencing this issue?
