### ISSUE TITLE
Subscription filter on owner not respecting other rules

### ISSUE THREAD

**Issue by kddejong** [aws-amplify/amplify-cli#10292]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

8.0.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

The following auth rules
```
type Message @model 
  @auth(rules: [
    { allow: private, operations: [read] },
    { allow: owner, operations: [create, read, update, delete]}
  ])
{
```

will result in the following subscriptions
```
onCreateMessage(owner: String): Message @aws_subscribe(mutations: ["createMessage"])
onUpdateMessage(owner: String): Message @aws_subscribe(mutations: ["updateMessage"])
onDeleteMessage(owner: String): Message @aws_subscribe(mutations: ["deleteMessage"])
```

While the read is extra in the owner field and is covered by private removing read 
```
type Message @model 
  @auth(rules: [
    { allow: private, operations: [read] },
    { allow: owner, operations: [create, update, delete]}
  ])
{
```

will result in
```
onCreateMessage: Message @aws_subscribe(mutations: ["createMessage"])
onUpdateMessage: Message @aws_subscribe(mutations: ["updateMessage"])
onDeleteMessage: Message @aws_subscribe(mutations: ["deleteMessage"])
```

It seems the read on the owner auth rule voids all other rules

### Expected behavior

```
type Message @model 
  @auth(rules: [
    { allow: private, operations: [read] },
    { allow: owner, operations: [create, read, update, delete]}
  ])
{
```
this should result in 
```
onCreateMessage: Message @aws_subscribe(mutations: ["createMessage"])
onUpdateMessage: Message @aws_subscribe(mutations: ["updateMessage"])
onDeleteMessage: Message @aws_subscribe(mutations: ["deleteMessage"])
```

### Reproduction steps

See above

### GraphQL schema(s)

<details>

```graphql
type Message @model 
  @auth(rules: [
    { allow: private, operations: [read] },
    { allow: owner, operations: [create, update, delete]}
  ])
{
  content: String!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

None

**Comment by kddejong** [comment]
Same issue applies when the owner field is specified with no operations

```
type Test @model 
  @auth(rules: [
    { allow: private, operations: [read] },
    { allow: owner }
  ])
{
  content: String
}
```

**Comment by naingaungphyo** [comment]
Well, I don't think this is a bug though, it is _nice to have feature_.
But for me, it will introduce me to a lot of complexity and energy to read that schema if one rule respects the other.
I will just write separate rules as what I want even if they are overlapping and respecting other rules.

**Comment by ykethan** [comment]
hello @kddejong 👋 , Thank you for reaching out. The adding the read permission to the `@auth` will add the `owner: String` to the generated schema. This is currently expected as this will allow customers to apply filter based on the owner when creating a subscription but this field will be created as optional. 
I was able to test this in my local application and on Appsync console as well. If we don't provide the owner the subscription will listen to all events (example: onCreate). Adding the owner field only provided onCreate events performed by the owner.

**Comment by kddejong** [comment]
That is correct but that means for this scenario
```
type Test @model 
  @auth(rules: [
    { allow: public, operations: [read] },
    { allow: owner }
  ])
```

In this scenario public users can do `listTests` and `getTest` but they cannot subscribe to mutations like `createTest`, `deleteTest`, or `updateTest`.  They would have to re-poll using `listTests` and `getTest` to get the most recent information.  My point is if I decide members of the public can read the items in `Test` they should be able to sit on the mutations with subscriptions to keep that data up to date.

**Comment by ykethan** [comment]
hey @kddejong, to test this I was able to replicate the following my application and observed that I was able to use a API key and subscribe to a `onCreate` operation when a logged in user(ex: Cognito) creates a post.

![image](https://user-images.githubusercontent.com/87995712/165776364-142a08e3-6642-490f-8c70-8f49564815d9.png)
![image](https://user-images.githubusercontent.com/87995712/165776410-198af041-6a12-4aa7-9be1-3ca6b135a03e.png)
![image](https://user-images.githubusercontent.com/87995712/165776487-7831cbf8-9eae-4efc-b710-6f9044750675.png)

Please do let us know know if this is what you are looking for. If I may have misunderstood anything, It would be great if you could provide us some additional information into your use case and if possible provide us some sample screenshots of the behaviour you are experiencing.

**Comment by kddejong** [comment]
I'm able to replicate this with a new amplify app.  I found oddities so I'm spinning up a few more apps to try track whats going on.
