### ISSUE TITLE
amplify add analytics -TypeError: "Cannot read property 'run' of undefined" 

### ISSUE THREAD

**Issue by rayteale** [aws-amplify/amplify-cli#1031]
While following vanilla install of amplify for test dev purposes came to a stop at"amplify add analytics":
__________
_raycode$_ amplify add analytics
Using service: Pinpoint, provided by: awscloudformation
? Provide your pinpoint resource name: comapp
Adding analytics would add the Auth category to the project if not already added.
TypeError: Cannot read property 'run' of undefined
    at inquirer.prompt.then (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-analytics/provider-utils/awscloudformation/service-walkthroughs/pinpoint-walkthrough.js:98:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the analytics resource_
______________
Note: also fails on "amplify add api" but not "amplify add auth" which works fine.

**To Reproduce**
   17  sudo npm install -g @aws-amplify/cli@0.1.34
   18  amplify configure
   19  sudo gem install cocoapods
   20  mkdir comapp
   21  cd comapp
   22  npx create-react-app comapp
   23  cd comapp
   24  npm start
   25  amplify init
   26  npm install --save aws-amplify
   27  npm install --save aws-amplify-react
   28  npm start
   29  amplify add analytics

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6

**Comment by kaustavghosh06** [comment]
@rayjanwilson I see that you're using an older version of the CLI. Could you please upgrade your CLI to the latest version? (1.1.7). I wasn't able to reproduce the issue with this latest version.

**Comment by rayteale** [comment]
The CLI upgrade has fixed the issue.  Thanks
