### ISSUE TITLE
Unable to complete the Getting Started tutorial

### ISSUE THREAD

**Issue by Coronus117** [aws-amplify/amplify-cli#10325]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.1.0

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Your tutorial at https://docs.amplify.aws/start/getting-started/installation/q/integration/react/#option-1-watch-the-video-guide is broken. At the bottom of page 2 (https://docs.amplify.aws/start/getting-started/setup/q/integration/react/) it says to add two imports to the src/index.js file, one of them says "import awsExports from './aws-exports';" but nothing named aws-exports was created in the src folder... or anywhere in my project. This gives me the Module not found: Error: Can't resolve './aws-exports' error.

### Expected behavior

I expected something to be created called aws-exports in my src folder.

### Reproduction steps

I'm just going to copy the exact steps from your own tutorial because that's what I did.
1. npm install -g @aws-amplify/cli
2. amplify configure (accept all defaults)
    a. Finish creating the new IAM user in the AWS 
    b. Copy and paste the keys into the terminal running amplify configure
3. npx create-react-app react-amplified
4. cd react-amplified
5. npm start
6. ctrl+c to stop that process
7. amplify init (accept all defaults)
8. npm install aws-amplify @aws-amplify/ui-react
9. open src/index.js
    a. put these lines below the last import
        i. import { Amplify } from 'aws-amplify';
        ii. import awsExports from './aws-exports';
        iii. Amplify.configure(awsExports);
10. npm start (BUG, it won't continue)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @Coronus117, Thank you for reaching out. normally the amplify aws-exports will be created as the following.

![image](https://user-images.githubusercontent.com/87995712/166311550-ce8eae99-7d7b-481f-b491-1206022c23b6.png)
![image](https://user-images.githubusercontent.com/87995712/166312250-441bd9c4-785d-4c78-ae88-2d38f6bb0c63.png)


if in case you have not added any other resource to a project can you please try `amplify delete` and doing a `amplify init` again.
or create a new react app and try running the `amplify init` to isolate and see if this occurred in this specific application. 

I tried replicating this in my windows PC on amplify version 8.1.0 but did not run into the issue.

**Comment by ykethan** [comment]
Hey @Coronus117, following up to see if you are experiencing any issues.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please do reach out to us again, we would be happy in reopening the issue.
