### ISSUE TITLE
What Amplify files should be .gitignored for projects that are shared across developer machines?

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1032]
It seems like, at the very least, local-env-info.json should be .gitignored, because whoever last pushed to the master branch will break the local environment of whoever next pulls from master. 

What other files should be .gitignored to minimize Amplify conflicts when developers are sharing the same backend?

** Provide additional details e.g. code snippets **
We've been stepping on each other's toes a lot, breaking environments, manually editing local-env-info.json (**this breaks on Windows btw, it does not correctly generate paths that go into the /mnt/c/\* directory **), getting merge conflicts because of last push timestamps, etc.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu When you initialize a project using the latest version of the CLI, we create or append to your existing .gitignore file. We recommend ignoring the following files/folders.
```
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json

```

**Comment by jkeys-ecg-nmsu** [comment]
Ah, and indeed these are a part of our .gitignore. So many pointless merges :P So it's a git cache issue then. Problem solved!

To anyone who finds themselves in a similar situation, [this is the remedy](https://stackoverflow.com/a/25436481/91713):

```
git rm -rf --cached .
git add .
```

Thanks!

**Comment by arelaxend** [comment]
Hi,

I am not sure it is secured to allow team-provider-info.json in git repository while it may contains provider credentials.

What do you think

**Comment by dopry** [comment]
@arelaxend  team-provider-info.json does **not** contain credentials.

**Comment by arelaxend** [comment]
Yes they change it recently, didn't they

**Comment by GMerakis** [comment]
why are amplify/backend/awscloudformation ignored?
I mean I understand why it's ignored for public repo
for private repo in small teams, we want reuse the same stack (or is this a bad practice?)

**Comment by dgills** [comment]
@GMerakis absolutely valid use case.  For team sharing, you'd expose the project's `amplify/team-provider-info.json` and basically .gitignore the rest.

Provided everyone has access to the relevant project CloudFormation stacks and that each person's local AWS/Amplify profile (access + secret keys included) has project access, they would then use amplify-cli to pull down the rest of the project files.


Check out their docs on [Team environments > Sandbox](https://docs.amplify.aws/cli/teams/sandbox) for more
