### ISSUE TITLE
Can not set/change Elasticsearch domain name

### ISSUE THREAD

**Issue by kstro21** [aws-amplify/amplify-cli#1033]
**Describe the bug**
I'm trying to change set the Elasticseach domain name, though that using what is described here https://aws-amplify.github.io/docs/cli/graphql#aws-cloudformation-template-parameters was the solution. But it doesn't, actually, after looking into the template *amplify\backend\api\amplifytest\build\stacks\SearchableStack.json* I realize that the parameter `"ElasticSearchDomainName"` is not used at all.

**To Reproduce**
1. Add the *@searchable* directive to one of the models in the **schema.graphql**
2. Edit the file _amplify\backend\api\amplifytest\parameters.json_ and add `"ElasticSearchDomainName": "my-custom-domain-name"`
3. Run `amplify push`
4. The domain name is not changed 

**Expected behavior**
Expected to be able to choose the Elasticseach domain name. So, if we set the parameter in _amplify\backend\api\amplifytest\parameters.json_ it is passed to the template and used to set the `"DomainName"` property of the `"AWS::Elasticsearch::Domain"`. Don't forget to also use the `env` parameter, it will be nice to appear in the final URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/5972646/54309746-27237180-45a7-11e9-9a83-59b3c87df6a6.png)

**Desktop (please complete the following information):**
 - amplify 1.1.7

**Additional context**
The parameter value is passed to the template, it can be confirmed by inspecting the **Parameters** tab of the stack in the CloudFormation Console. The parameter is defined in the template located at *amplify\backend\api\amplifytest\build\stacks\SearchableStack.json*
```
"ElasticSearchDomainName": {
    "Type": "String",
    "Description": "The name of the Elasticsearch domain.",
    "Default": "appsync-elasticsearch-domain",
    "AllowedPattern": "^[a-z][a-z0-9-]*$",
    "MinLength": 1,
    "MaxLength": 28
},
```
but the parameter is not used in the resource, here is the complete definition of the  `"AWS::Elasticsearch::Domain"`
```
"ElasticSearchDomain": {
    "Type": "AWS::Elasticsearch::Domain",
    "Properties": {
        "DomainName": {
            "Fn::If": [
                "HasEnvironmentParameter",
                {
                    "Ref": "AWS::NoValue"
                },
                {
                    "Fn::Join": [
                        "-",
                        [
                            "d",
                            {
                                "Ref": "GetAttGraphQLAPIApiId"
                            }
                        ]
                    ]
                }
            ]
        },
        "ElasticsearchVersion": "6.2",
        "ElasticsearchClusterConfig": {
            "ZoneAwarenessEnabled": false,
            "InstanceCount": {
                "Ref": "ElasticSearchInstanceCount"
            },
            "InstanceType": {
                "Ref": "ElasticSearchInstanceType"
            }
        },
        "EBSOptions": {
            "EBSEnabled": true,
            "VolumeType": "gp2",
            "VolumeSize": {
                "Ref": "ElasticSearchEBSVolumeGB"
            }
        }
    }
},
```
Note that ` "DomainName"` do not use the parameter `"ElasticSearchDomainName"`

**Comment by mikeparisstuff** [comment]
@kstro21 Thanks for the comment. This looks like something that slipped through and was meant to be removed from the parameter options. Can I ask for more details on why you want to rename the domain? Is it just the domain name that you want to customize? Do you have any requirement to use a ES domain that is managed outside of Amplify?

**Comment by kstro21** [comment]
Hi, @mikeparisstuff, for example, right now I have 3 environments created using **amplify**, and it is hard to identify to which environment belongs each of the Elasticsearch instances just by looking to the names. 
![image](https://user-images.githubusercontent.com/5972646/54647774-3e1c0500-4a7a-11e9-8923-5965ba893a14.png)

See my point? What about if we can set the `"ElasticSearchDomainName"` parameter value and the result is something like **[projectname]-[env]-ramdonAWSid**? It will look like **myproject-qa-reaw6wkydg9h** and anyone in my team will know it belongs to the QA environments. It will be great!.

I would like to take a look at this and make a PR if you allow me.

**Comment by mikeparisstuff** [comment]
@kstro21 Thanks for the comment. This looks like something that slipped through and was meant to be removed from the parameter options. Can I ask for more details on why you want to rename the domain? Is it just the domain name that you want to customize? Do you have any requirement to use a ES domain that is managed outside of Amplify?

**Comment by mikeparisstuff** [comment]
@kstro21 Gotcha. I remember looking into this in the past and believe I backed away from putting the env name in the domain name because the domain name has a limit of 28 characters. If you are willing to look at this and find a good way to support your use case that does not break existing APIs, I am happy to review a PR.

**Comment by mdw2000** [comment]
@kstro21 @mikeparisstuff Is there scope to look at this enhancement again?

Sharing / reusing domains between projects are valid use cases in addition to adding the environment to the domain name:

- Reuse between environments for smaller projects (no need to have a cluster per environment, dev, test, even prod can share the same cluster to save cost)
- Sharing between projects - where separate Appsync projects/APIs form part of a larger system with an existing cluster

**Comment by RossWilliams** [comment]
- ES is also the slowest component to create, more than all others we have combined.
- With the console now offering environment per branch, costs can get out of control when a dev creates 2-3 branches a day. Sharing ES would help n speed and cost.

**Comment by MontoyaAndres** [comment]
any news about it?

**Comment by renebrandel** [comment]
Hi folks - with the ability to modify Amplify-generated resources, you should be able to address this now. https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive 

@-mention me if you have any further questions on this.
