### ISSUE TITLE
Cannot Attach to Backend

### ISSUE THREAD

**Issue by BrianSHenderson** [aws-amplify/amplify-cli#1034]
When I pull from GitHub to a new machine I get errors when doing commands such as:
awsmobile pull
awsmobile console
Where I receive:
backend awsmobile project unknown

Attempting to do:
awsmobile init <project id> 
Gives an Invalid Signature error

Any ideas?

**Comment by kaustavghosh06** [comment]
@BrianSHenderson We've deprecated the awsmobile-cli. Please use the amplify-cli to build your app moving forward or use the https://github.com/awslabs/amplify-mobilehub-migrator to migrate your MobileHub project and then use the amplify-cli.
