### ISSUE TITLE
Upgrading to v2, getting "Your instance type for OpenSearch is t2.small.elasticsearch, you may experience..." even though it is set to medium

### ISSUE THREAD

**Issue by VicFrolov** [aws-amplify/amplify-cli#10362]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.2

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I am upgrading from v1 to v2, and in my `team-provider-info.json`, I already had medium instances, but updated to use OpenSearchInstanceType:
```
{
  "prod": {
    "categories": {
      "api": {
        "my-api": {
          "OpenSearchInstanceType": "t2.medium.elasticsearch"
        }
      }
    }
  }
}
```

I have all my environments using t2.medium, but I am getting the warning during the `amplify push` step that it is being set to t2.small.elasticsearch). This was not an issue on v1.

### Expected behavior

Do not show warning and correctly set t2.medium.elasticsearch

### Reproduction steps

Cannot really describe given I have a large v1 api. But I have followed migration steps defined [here](https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @VicFrolov, Thank you for reaching out. On replicating the `@searchable` in my v2 transformer schema and modifying the `teams-provider-info.json` according to https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments. I observed the schema compilation will display the same message. 

marking this as bug for improvements.
