### ISSUE TITLE
auth - user group role not found in stack

### ISSUE THREAD

**Issue by adilosa** [aws-amplify/amplify-cli#10365]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

override, publish

### Describe the bug

We used to use `amplify update auth` to add new user pool groups, which get added to `template.json` and `user-pool-group-precedence.json`. 

With the new auth migration, amplify wants to delete all the groups on every publish. If I manually edit the template, amplify still wants to delete groups from `amplify/backend/types/amplify-dependent-resources-ref.d.ts`. Then the CloudFormation deployment fails with `"Output 'customerNameGroupRole' not found in stack"`.

### Expected behavior

amplify publish should not be trying to delete my user groups. 

the [auth migration guide](https://docs.amplify.aws/cli/migration/override/) is not at all clear how this is intended to work with existing user pool groups done in the (I guess old?) fashion. 

### Reproduction steps

1. existing repo with custom user groups
2. try and add a user group, migrate auth, or publish --> fail to deploy and/or it tries to remove user groups from stack

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

**Comment by adilosa** [comment]
Thanks for your response.

When I run `amplify update auth` and select 'Create or update Cognito user pool groups', it does list all of the existing groups correctly. `amplify status` shows Auth userPoolGroups needs to be updated, but it doesn't show details on each group.  `git diff` shows that it's no longer removing all the groups (somehow), but it is removing the "customPolicy" fields from each in user-group-precedence.json.

Do I need to override the IAM policies in a different way after the migration? I couldn't find much documentation on the new way of doing it.

**Comment by ykethan** [comment]
Hello @adilosa, Thank you for the information. I was able to find the following issues similar to the behaviour you are experiencing.
https://github.com/aws-amplify/amplify-cli/issues/9738
https://github.com/aws-amplify/amplify-cli/issues/10417

The issues have been marked as a bug, please do subscribe to the issue and add comments on behaviors observed in your application.

**Comment by josefaidt** [comment]
Hey @adilosa from this note:

> git diff shows that it's no longer removing all the groups (somehow)

Was the behavior seen in the original report no longer occurring? We've linked the existing issue regarding customPolicy blocks getting removed from the user-pool-precedence.json file, however have been unable to reproduce the original issue where you're seeing groups are removed on push

**Comment by adilosa** [comment]
Hi, yes, I haven't been able to repro the original behavior now. The remaining issue seems to match #9738 so I'll close this in favor of that. Thanks!
