### ISSUE TITLE
main property no longer populated in @aws-amplify/cli package.json

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#10378]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac OS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Previous package.json files of amplify cli had a [main](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) property set. This allowed us to import ```@aws-amplify/cli``` in our custom js scripts and execute the amplify cli via javascript. Our custom js script used the amplify cli codegen command to generate graphql types for our backend (until https://github.com/aws-amplify/amplify-codegen/issues/49 is resolved by cli team). 

It seems recently this main property was removed, and only a bin property exists. See screenshot below. I think this was introduced in this PR: https://github.com/aws-amplify/amplify-cli/pull/10042

<img width="333" alt="cli — vi package json — 178×90 2022-05-06 18-23-33" src="https://user-images.githubusercontent.com/81853/167230945-ce582962-b436-4ad2-9542-79b727418e4a.png">

This causes our script to fail with error: 

```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/hisham/.nvm/versions/node/v14.17.6/lib/node_modules/@aws-amplify/cli'
Require stack:
- /Users/hisham/src/ess-app/packages/cli/node_modules/import-global/index.js
- /Users/hisham/src/ess-app/packages/cli/amplify-codegen.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at module.exports (/Users/hisham/src/ess-app/packages/cli/node_modules/import-global/index.js:9:10)
    at Object.<anonymous> (/Users/hisham/src/ess-app/packages/cli/amplify-codegen.js:19:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/hisham/src/ess-app/packages/cli/node_modules/import-global/index.js',
    '/Users/hisham/src/ess-app/packages/cli/amplify-codegen.js'
  ]
}
```

Manually adding "main: "lib/index.js" to the package.json resolves this issue

### Expected behavior

I should be able to import the ```@aws-amplify/cli``` in my js files and run it through js rather than pure command line. 

### Reproduction steps

Use [import-global](https://github.com/sindresorhus/import-global) to import the amplify cli like so in any js file: 

```
const { run: runAmplifyCli } = importGlobal('@aws-amplify/cli');
```

### GraphQL schema(s)

N/A

### Log output

N/A

**Comment by hisham** [comment]
Hi @josefaidt - yes I ended up using child_process.exec and it worked fine with no issues. 

The initial advantage of running the js directly is it made debugging easier since it allowed us to step the debugger into amplify cli code to troubleshoot things. Now that our script is working this is less of a need, so I switched to using execSync. 

Another issue I found is it seems the amplify cli code now calls process.exit(0) when a command succesfully completes, which causes our entire script to exit. execSync resolved this issue as well for us. 

You can go ahead and close this if you want, thank you! :)

**Comment by hisham** [comment]
Thank you for letting me know of zx, that is very handy, I wasn't aware of it. Might use it for future scripts.

**Comment by josefaidt** [comment]
Hey @hisham glad to hear that worked out for you! And zx has been really handy for my own scripts as well as it makes working with JSON inputs trivial! 

I'll close this issue as a duplicate feature request of #7025 🙂
