### ISSUE TITLE
ENOENT error on pycache when running push or pull after deleting lambda layer from cloud

### ISSUE THREAD

**Issue by jpollmann102** [aws-amplify/amplify-cli#10387]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.2

### Amplify CLI Version

8.1.0

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleted Lambda Layer via AWS Console

### Amplify Categories

function

### Amplify Commands

pull, push

### Describe the bug

When running `amplify push` or `amplify pull` even with `--force` command, I get the following error:

```
Could not initialize 'staging': ENOENT: no such file or directory, realpath 'C:\Users\<UserName>\Documents\...\...\...\amplify\.temp\#current-cloud-backend\function\<layer name>\lib\python\lib\python3.10\site-packages\pipenv\patched\notpip\_internal\distributions\__pycache__'
```

### Expected behavior

Expected changes from cloud to be pulled without error

### Reproduction steps

Not entirely sure if this will replicate the issue, but here is what I personally am stuck at.

1. Create a lambda layer via CLI using `amplify add function`
2. Delete layer in cloud
3. Run `amplify pull` to pull changes from cloud

### Additional information

I have tried removing the .temp folder,  and I have verified that the directory that the error is presenting is in fact existing. I can provide any additional information as needed

**Comment by jpollmann102** [comment]
Ah, good to know. Unfortunately that does not work with the error:

```
An error occurred fetching the latest layer version metadata for "<lambda layer name>": Cannot read property 'LogicalName' of undefined
```

**Comment by josefaidt** [comment]
Hey @jpollmann102 I believe this error is due to the Layer no longer existing, so the CLI cannot get the related layer metadata. 

> An error occurred fetching the latest layer version metadata for "<lambda layer name>"

```
> amplify remove function
? Choose the resource you would want to remove 10263layer58c94806 (layer)
When you delete a layer version, you can no longer configure functions to use it.
However, any function that already uses the layer version continues to have access to it.
✖ Loading layer data from the cloud...
An error occurred fetching the latest layer version metadata for "10263layer58c94806": Cannot read property 'LogicalName' of undefined
```

But no worries! We can do a few manual edits to remove this layer from our local project:

1. remove the layer directory from `amplify/backend/function`
2. remove the layer references in `amplify/team-provider-info.json`
3. remove the layer references in `amplify/backend/backend-config.json`
4. run `amplify env checkout <current-env-name>`
5. this should now show your layer in the `DELETE` state
6. push with `amplify push -y`
7. observe successful removal from project 🙌

**Comment by jpollmann102** [comment]
Awesome, thanks for the help, I appreciate it
