### ISSUE TITLE
Region add api issue for ap-northeast-2

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [aws-amplify/amplify-cli#1038]
(Describe)
Unable to setup for ap-northeast-2 with Amplify cli tool when:
(Reproduce)
1. change the ~/.aws/config to ap-northeast-2 from ap-northeast-1 or wherever.
2. get start tutorial step ...
3. amplify add api
4. amplify push
5. .. after a while, return on the console with this error. 
Following resources failed

Resource Name: GraphQLSchema (AWS::AppSync::GraphQLSchema)
Event Type: create
Reason: The provided token is malformed or otherwise invalid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidToken; Request ID: E44178C6C2BD2BA3; S3 Extended Request ID: NCCMQwu8towi2pJBHeOFBXK4FF2Hrvzc1NPvA+gIA6beGFoz53ZSIRWaYVi/Z8Kfr4f2P8gMQfA=)

(Expected behavior)
It should allow the account setup in this region. If changing the region back to ap-northeast-1 again, it works fine. 

(System)
 - xCode 10.1
- MacOs 10.13

**Comment by kaustavghosh06** [comment]
@InfiniteRandomVariable I was able to reproduce this bug. I believe it's an issue with the AppSync Service. I will engage with them and update this thread after I hear back from them.

**Comment by kaustavghosh06** [comment]
@InfiniteRandomVariable The issue should be fixed now in ap-northeast-2.
