### ISSUE TITLE
Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.}

### ISSUE THREAD

**Issue by jiaxiuli** [aws-amplify/amplify-cli#10405]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install @aws-amplify/cli -g

### If applicable, what version of Node.js are you using?

v16.14.2

### Amplify CLI Version

Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.}

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

run command start with "amplify" will get the error "Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.}" after installed it.

### Expected behavior

should not get the error

### Reproduction steps

1. npm install @aws-amplify/cli -g
2. amplify
Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.}
3. amplify version
Platform with type "Windows_NT" and architecture "ia32" is not supported by @aws-amplify/cli.}

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @jiaxiuli :wave: thanks for raising this! I've gone ahead and marked this as a bug 🙂

**Comment by josefaidt** [comment]
Hey @jiaxiuli unfortunately this architecture is not supported, and we will add documentation around the scope of support per this issue https://github.com/aws-amplify/amplify-cli/issues/10295.

Marking as a duplicate wontfix of #10295
