### ISSUE TITLE
AuthError - Error: Amplify has not been configured correctly after adding notifications and analytics categories

### ISSUE THREAD

**Issue by Samaritan1011001** [aws-amplify/amplify-cli#10410]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### Amplify CLI Version

8.2.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, analytics, notifications

### Amplify Commands

add, push

### Describe the bug

In a React Native project, adding the categories `notifications` and `analytics` in addition to using `withAuthenticator` from `aws-amplify-react-native` in the app code causes an `AuthError`

Steps shown in the Error to resolve does not work. The error is shown below, 

```cli
ERROR  [ERROR] 43:50.739 AuthError - 
Error: Amplify has not been configured correctly. 
The configuration object is missing required auth properties.
This error is typically caused by one of the following scenarios:

1. Did you run `amplify push` after adding auth via `amplify add auth`?
    See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
```

### Expected behavior

I expect to not see the AuthError as adding `notifications` and `analytics` also internally by default adds `auth` to the project which is seen when I run `amplify push`

### Reproduction steps

1. npx react-native init auth_error_app
2. amplify init
3. amplify add notifications
4. amplify add analytics
5. use withAuthenticator in the app code as shown in the [documentation](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react-native/#using-withauthenticator-hoc)
6. amplify push
7. npx react-native run-android
3. Notice that you get the `AuthError` in the terminal once the app is running on your emulator

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
 ERROR  [ERROR] 43:50.739 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.

```

</details>

### Additional information

A quick fix that seems to work is adding categories in the following order: 
auth → notifications → analytics

**Comment by ykethan** [comment]
Hello @Samaritan1011001,Thank you for reporting this. I was able replicate this in my Amplify application.  Marking as bug.

**Comment by ykethan** [comment]
Note: The `amplify add notification` adds the Cognito resource directly without the Auth flow. 
Additionally observed the team-provider-info.json with the following attribute.

```JSON
 "categories": {
      "auth": {
        "undefined": {}
      },
```

**Comment by lazpavel** [comment]
Hi @Samaritan1011001, this issue is fixed in the latest CLI, also adding notifications will automatically add auth and analytics.
