### ISSUE TITLE
Amplify API returning CORS error

### ISSUE THREAD

**Issue by sayu-agiliad** [aws-amplify/amplify-cli#10425]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.0.2

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes done.

### Amplify Categories

auth, function, api

### Amplify Commands

add

### Describe the bug

I added an API with below configuration:
![image](https://user-images.githubusercontent.com/20765370/168584496-a0d861f4-2647-4e4a-a849-9d8398bba6c5.png)

I invoke the API like this
![image](https://user-images.githubusercontent.com/20765370/168584811-8c47b5e4-470b-491a-b187-6582344fc778.png)

I get error 403 when I invoke the API in the context of an authenticated user. 
![image](https://user-images.githubusercontent.com/20765370/168589864-7f245561-bd4d-4b39-8808-fe38371a2d83.png)

### Expected behavior

Error should not occur.

### Reproduction steps

1. Create a next js project
2. Add Auth with user groups. 
3. Add API with above settings.
4. Invoke API 

### GraphQL schema(s)

Not applicable

**Comment by josefaidt** [comment]
Hey @sayu-agiliad :wave: thanks for raising this! The example you provided will work when using a custom authorizer leveraging Cognito User Pools, however when restricting routes to auth users, guests, and groups from the CLI we will be authenticating with IAM. Can you try calling your API without providing a custom auth header?

**Comment by josefaidt** [comment]
Hey @sayu-agiliad here is the documentation page for fetching data from our REST API https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/

I have a few follow-up questions:

- are you using any [overrides](https://docs.amplify.aws/cli/restapi/override/)?
- are you using a custom authorizer?

**Comment by sayu-agiliad** [comment]
> Hey @sayu-agiliad here is the documentation page for fetching data from our REST API https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/
Thank you. I have been following this guide, but 
 
> I have a few follow-up questions:
> 
> * are you using any [overrides](https://docs.amplify.aws/cli/restapi/override/)?
No I am not using any overrides.

> * are you using a custom authorizer?
No I am not using a custom authorizer.

I am trying to develop a NextJS application, and I would like the API to be restricted to only users belonging to a particular group.  

I have confirmed that If I do not restrict API access, I am able to invoke the API successfully.

**Comment by josefaidt** [comment]
Hey @sayu-agiliad can you share a snippet of how you're calling the API from the frontend? Also, do you have CORS headers applied to your Lamdba function's response? In the following example authenticated users are allowed to `read` the endpoint, where members of the `admins` group are able to `create` _and_ `read`

**lambda**

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
  console.log(`EVENT: ${JSON.stringify(event)}`)
  return {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': '*',
    },
    body: JSON.stringify('Hello from Lambda!'),
  }
}
```

Sample frontend code (using Next.js)

```js
// src/pages/hello.jsx
import { useState, useEffect } from 'react'
import { API } from 'aws-amplify'
import awsExports from '../aws-exports'

const [{ name: API_NAME }] = awsExports.aws_cloud_logic_custom

export default function HelloPage(props) {
  const [data, setData] = useState()

  async function read() {
    setData(await API.get(API_NAME, '/hello', { response: true }))
  }
  async function create() {
    setData(await API.post(API_NAME, '/hello', { response: true }))
  }

  useEffect(() => {
    read()
  }, [])

  return (
    <div>
      <button onClick={read}>read</button>
      <button onClick={create}>create</button>
      <pre>
        <code>{JSON.stringify(data, null, 2)}</code>
      </pre>
    </div>
  )
}
```

In the end, we should receive a 403 error when attempting to make a POST call while signed in as `user`
<img width="693" alt="image" src="https://user-images.githubusercontent.com/5033303/168670966-9805359a-7c12-4059-a278-9fa732c8f984.png">

**Comment by sayu-agiliad** [comment]
1. Yes, I do have CORS header applied to my Lambda functions response.
2.  My front end code looks like below 


```
  async function checkLogin(){
  console.log('Access token', (await Auth.currentSession()).getAccessToken().getJwtToken())
  console.log('ID Token', (await Auth.currentSession()).getIdToken().getJwtToken())
  let apiName = 'NotificationAPI';
  let path = '/items';
  let myInit = {
      headers: {
            Authorization: `${(await Auth.currentSession()).getAccessToken().getJwtToken()}`
      }
  }
  const result = await API.get(apiName, path,myInit)
}

```


If I invoke the API like below:
```const result = await API.get(apiName, path,{result:true})```

I get 
![image](https://user-images.githubusercontent.com/20765370/168727789-da6fc9e0-3e43-4c2c-acb2-2d96689d1795.png)



Please note that the API was created with below settings:

```
? Select from one of the below mentioned services: REST
√ Select the REST API you want to update: · NotificationAPI
√ What would you like to do? · Update path
? Select the path to edit /
√ Provide a path (e.g., /book/{isbn}): · /
√ Choose a Lambda source · Use a Lambda function already added in the current Amplify project
√ Choose the Lambda function to invoke by this path · NotificationLambda
√ Restrict API access? (y/N) · yes
√ Restrict access by: · Auth/Guest Users
√ Who should have access? · Authenticated users only
√ What permissions do you want to grant to Authenticated users? · create, read, update, delete
```

I want the API to be accessible to all Authenticated users.

**Comment by josefaidt** [comment]
Hey @sayu-agiliad do you receive any errors when attempting to call the API without the `init` with the Authorization header? 

```js
 async function checkLogin() {
  let apiName = 'NotificationAPI';
  let path = '/items';
  let myInit = {
  const result = await API.get(apiName, path)
}
```

**Comment by sayu-agiliad** [comment]
@josefaidt  I get the below error if I do not use the init.
![image](https://user-images.githubusercontent.com/20765370/168819927-0dd2bdb5-331e-4ae9-b75f-2e45f31e7e79.png)

In developer tools, I see the error details as below:
![image](https://user-images.githubusercontent.com/20765370/168820040-88a46cae-0e3e-4c12-bc45-8162738920ae.png)

**Comment by josefaidt** [comment]
Hey @sayu-agiliad do you see an authorization header attached to the request? 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/5033303/168821215-7023365e-ab89-4a6d-abd8-c46a41767b64.png">

And we should see IAM as the authorization set on our API Gateway route 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/5033303/168821420-cb1ac3a6-12c1-46ed-b31f-2a02af76d1d7.png">

**Comment by sayu-agiliad** [comment]
@josefaidt  The API Gateway has the Authorization set to AWS IAM as in your screenshot.
However, my request headers does not contain the authorization header as can be seen below.
![image](https://user-images.githubusercontent.com/20765370/168823232-f2d61994-1a52-43e0-aebe-dfc937e36fb1.png)

**Comment by sayu-agiliad** [comment]
@josefaidt 
package.json dependencies.

```  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mui/material": "^5.6.2",
    "aws-amplify": "^4.3.20",
    "cross-env": "^7.0.3",
    "jest-environment-jsdom": "^28.0.0",
    "next": "12.1.5",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-redux": "^8.0.1"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "cypress": "^9.5.4",
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.5",
    "jest": "^28.0.0"
  }```

my aws-exports.js
```

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1re9cJyj1",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {
        "domain": "dev-cat-csm-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/signin/,http://localhost:3000/signin/",
        "redirectSignOut": "http://localhost:3000/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "NotificationAPI",
            "endpoint": "https://yyyyyyyyyyy.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
```


I configure 
`Amplify.configure({ ...awsmobile, ssr: true });`


One thing I noticed, is that I am using 
`const { Auth } = withSSRContext();`

should i just import the Auth rather than getting it from SSRContext ?
