### ISSUE TITLE
Using @searchable directive with nested data

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#1044]
** Which Category is your question related to? **
Amplify, GraphQL API, Elasticsearch, DynamoDB

The Appointment table has a connection to an Account table which has a connection to a Marketer table. I want to search the Appointment table by Marketer ID field. 

Like so: 

```
query SearchAppointments{
  searchAppointments(
    filter: { account: { marketer: {id: {eq: "acme"}}}}) {
    items {      
      id      
      account {        
        id        
        marketer {          
          id          
          name        
        }      
      }        
      appointmentDate      
      appointmentStatus      
    }  
  }
}
```

Is this possible with the current version of Amplify? If not, would I have to create the fields on the Appointment object? 

I also need to search on date ranges. appointmentDate is a AWSDateTime. Will `gt` and `lt` work on date fields?

**Comment by mikeparisstuff** [comment]
Hey @aireater, the search field does not currently allow you query through nested fields automatically like this. With this being said, you have a few options. 

1. Store the marketerId on the appointment.

If you cut the Account out of the equation and make the appointment connect directly to the marketer:

```graphql
type Appointment {
  id: ID!
  time: String
  marketer: Marketer! @connection(name: "MarketerAppointments")
}
type Marketer {
  id: ID!
  name: String
  appointments: [Appointment] @connection(name: "MarketerAppointments")
}
```

Then the @connection fields will subtly add a "appointmentMarketerId" to the "Appointment" type. If you want to expose this ID to the API then all you need to do is add a field definition for it:

```graphql
type Appointment {
  id: ID!
  time: String
  marketer: Marketer @connection(name: "MarketerAppointments")
  appointmentMarketerId: ID
}
```

Once you have added the field, you may use it to search in the @searchable query:

```graphql
query SearchAppointments{
  searchAppointments(
    filter: { apointmentMarketerId: {eq: "acme"}}) {
    items {      
      id      
      account {        
        id        
        marketer {          
          id          
          name        
        }      
      }        
      appointmentDate      
      appointmentStatus      
    }  
  }
}
```

If you go down this route, you can actually avoid the search field completely and get all the appointments for a given marketer directly from DynamoDB.

```graphql
query GetAppointmentsForMarketer {
  getMarketer(
    id: "marketer-id"
  ) {
    items {      
      id      
      appointments {
        appointmentDate
        appointmentStatus
      }      
    }  
  }
}
```

2. Write a custom resolver with a custom Elasticsearch query:

See https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable for an example.

**Comment by aireater** [comment]
Thanks @mikeparisstuff , that makes sense. 

But then how do you I do range searches on dates using Amplify? lte and gte do not work on string fields. 

From my original question: 

> I also need to search on date ranges. appointmentDate is a AWSDateTime. Will gt and lt work on date fields?

**Comment by mikeparisstuff** [comment]
Hey @aireater. As of writing there are two ways to go about this:

1. Store the timestamps as integers and use the auto-generated gt/lt on the integer search inputs.
2. Use the PutMapping Elasticsearch API to specify that the datetime fields should be stored as a `date` type (see https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html). There are a few gotchas with this approach because you need to set the mapping before any data (that contains the mapped field) is inserted into the index. If you want to change the mapping on an existing field then you need to add the mapping and re-index the data into the newly mapped index. You can add mappings for fields that do not exist yet whenever you want. If you are still in dev mode, the easiest way to get the desired effect is to create a new env which will create a new cluster and then use kibana to call the PutMapping api. We are looking into ways to provide support for custom Elasticsearch mappings that will be applied at startup in the future but there is no set date for this feature.

**Comment by kaustavghosh06** [comment]
Closing this issue for now. Please feel free to re-open if you're still facing this problem.

**Comment by sasankmukkamala** [comment]
@aireater  - I was able to achieve range search on date by simply overriding SearchableStringFilterInput in my schema.graphql like this

`input SearchableStringFilterInput {
	ne: String
	eq: String
	match: String
	matchPhrase: String
	matchPhrasePrefix: String
	multiMatch: String
	exists: Boolean
	wildcard: String
	regexp: String
	range: [String]
}` 

and then i was able to use the range filter directly. 

@mikeparisstuff  - Didn't have to do any of the three suggestions you gave. Is this ok?

**Comment by izmalych** [comment]
```graphql
type UserData @model @searchable{
    id: ID!
    name: String!
    onboardingDate: String!
}

input SearchableStringFilterInput {
    ne: String
    eq: String
    range:[String]
}

query data{
  searchUserDatas(
    filter: {
      onboardingDate:{
        range:["2019-01-01","2019-09-01"]
      }
    }
  ) {
    items {
      id
      onboardingDate
    }
  }
}
```

works fine for me
