### ISSUE TITLE
Is aws amplify stable enough for production in 2022?

### ISSUE THREAD

**Issue by crzyjcky** [aws-amplify/amplify-cli#10453]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
amplify cli

**Amplify CLI Version**
8.2.0

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
ec2, appsync

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Amplify cli is a very good idea, it helps to speed up the development a lot. 
My when is, what happen when things break? How to troubleshoot the errors? How to maintain it? How to support schema evolution?

Any real production usage here?

**Comment by pjsandwich** [comment]
I use amplify in prod, works well for my use cases. Nice DX as well, discord community is responsive and helpful. You also benefit from being able to add services from AWS that aren't available through Amplify by doing manual configurations.

**Comment by josefaidt** [comment]
Hey @crzyjcky :wave: thanks for your feedback! Amplify CLI is a toolchain to create and manage backend AWS services for your application, and is used by customers for development and production deployments. In case you have any specific errors or issues that block you, please raise a GitHub issue. If you have general questions that you would like our community's assistance, please post them on our [community Discord server](https://discord.gg/invite/amplify)

**Comment by renebrandel** [comment]
Hi - just to add a bit more color here. We've got quite a big line-up of customers using Amplify in production including companies like Rivian, OrangeTheory, and Amazon Music. See the customer stories here: https://aws.amazon.com/amplify/customers/?nc=sn&loc=7

In addition, we're also trying to make troubleshooting a bit easier. Here's our first troubleshooting guide - let us know if you see something missing: https://docs.amplify.aws/cli/project/troubleshooting/ 

Last but not least, I encourage you to join our Discord Office Hours, where you get to connect with the team directly as well.
