### ISSUE TITLE
ModelSortDirection type missing from generated API.swift

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/amplify-cli#1045]
I have added a 'sortKey' in schema.graphql file and CLI successfully created DynamoDB with proper 'sortKey' but the API.swift file that was generated is missing 'ModelSortDirection' and hence, I am unable to define sort order for my objects. Not sure is this is an issue or a usage question.

** Which Category is your question related to? **
AWS Amplify CLI
** What AWS Services are you utilizing? **
AppSync
** Provide additional details e.g. code snippets **

**Comment by yuth** [comment]
@rohit3d2003 graphql transformer support sort key only for connections and the autogenerated statements don't pass any arguments to fields as the generated statements are only the starting point. Codegen generates only the types that are used in the project. You could update your query to accept sortKey as argument and you should get API.swift with ModelSortDirection

For instance if you follow the example of blog post in the [doc](https://aws-amplify.github.io/docs/cli/graphql#connection) you get the following query generated for you
```graphql
query ListBlogs(
  $filter: ModelBlogFilterInput
  $limit: Int
  $nextToken: String
) {
  listBlogs(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      name
      posts {
        items {
         id
        title
       }
        nextToken
      }
    }
    nextToken
  }
}
```
You could update the query to accept `blogPostSortDirection` and codegen would generate SortDIrection in your swift code
```graphql
query ListBlogs(
  $filter: ModelBlogFilterInput
  $limit: Int
  $nextToken: String,
  $blogPostSortDirection: ModelSortDirection
) {
  listBlogs(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      name
      posts(sortDirection: $blogPostSortDirection) {
        items {
         id
        title
       }
        nextToken
      }
    }
    nextToken
  }
}```

**Comment by rohit3d2003** [comment]
Thanks! Worked for me
