### ISSUE TITLE
Cognito App clients does not have App client secret for both

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#10468]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

8.3.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

Observed that both the CLI created Cognito resource have 2 App clients created. Both App Clients do not contain App client secret.

![image](https://user-images.githubusercontent.com/87995712/170140139-5cede943-ae6d-4270-85dd-611dfd2da6e3.png)
![image](https://user-images.githubusercontent.com/87995712/170140207-b015907f-e4fd-4f83-8e6c-046848131f56.png)

According to the documentation 1 Client will have App client secret while other does not.
https://docs.amplify.aws/console/auth/import/#import-an-existing-cognito-user-pool
https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/

### Expected behavior

update the documentation if the behaviour has changed

### Reproduction steps

1. amplify add auth
2. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
AFAIK We don't add app client secrets with userPool clients and also we don't provide any flow for that.

For the above link: We need app client secret added if there is any userpool with appclients(not generated with amplify) we are importing contains secrets.
