### ISSUE TITLE
Amplify push --minify stop working after GraphQL API migration

### ISSUE THREAD

**Issue by simoneagostinelli** [aws-amplify/amplify-cli#10479]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

8.3.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

After api graphql migration, when pushing resources with the command `amplify push --minify` on cloud, the stacks generated for the api graphql are not minified, and for this reason i can't push changes, because i have some stack greater than 1000000 bytes, and i get back the error

Template may not exceed 1000000 bytes in size.

before migration all json in stacks build folder are minified. but not now this is the reason of the previous error

### Expected behavior

during `amplify push --minify` commnad all stack generated must be minified

### Reproduction steps

deployed amplify graphql api with old version
run amplify update api and migrate graphql api to new version of graphql transformer
amplify push --minify (and now amplify stops to minify stacks)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by thejasonfisher** [comment]
Are there any potential workarounds here?  I need to migrate to GraphQL API v2 for OpenSearch aggregation features but this is keeping us back.

**Comment by simoneagostinelli** [comment]
@thejasonfisher the only workaround that i have found is to launch amplify push command and when it asks if you want to continue you can select yes, and after when amplify prompts if you want to generate graphql, before send yes, you can go in yours stack files in build folder and minify manually each json stacks that is too big. but if you have a lot of files that is too big this is very annoying, and you have to do this on every subsequent push

**Comment by simoneagostinelli** [comment]
Hi, any news about this bug? when you can release this fix?

**Comment by kzhang-dsg** [comment]
And update on this bug? We have around 300 models. the generated cloudformation-template.json exceeds 1000000 bytes, which caused the error.

**Comment by kzhang-dsg** [comment]
Also, the workaround does not work for me. After manually minifying the cloudformation-template.json, the size is still 1.2MB. Ideally, the Amplify CLI should [Break cloudformation file into smaller scripts](https://stackoverflow.com/questions/42837692/break-cloudformation-file-into-smaller-scripts).

**Comment by AlessandroAnnini** [comment]
Any news about this?

**Comment by simoneagostinelli** [comment]
@jhockett when will be released? i cant push anymore on amplify without migrate to V2 because of this https://github.com/aws-amplify/amplify-category-api/issues/715#issuecomment-1208404625
