### ISSUE TITLE
AWS Opensearch as custom AWS resources using CloudFormation template

### ISSUE THREAD

**Issue by rizvanhaider** [aws-amplify/amplify-cli#10498]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

8.1.2

### Amplify CLI Version

8.3.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I added a custom resource using amplify cli by selecting cloudformation as template for new resource and following is the template I added.

`{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "env": {
      "Type": "String"
    }
  },
  "Resources": {
    "OpenSearchService": {
      "Type": "AWS::OpenSearchService::Domain",
      "Properties": {
        "AccessPolicies": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Action": "es:*",
              "Condition": {
                "IpAddress": {
                  "aws:SourceIp": "<my-ip-was there>/32"
                }
              }
            }
          ]
        },
        "ClusterConfig": {
          "InstanceCount": 1,
          "InstanceType": "t2.small.search",
          "ZoneAwarenessEnabled": false
        },
        "EBSOptions": {
          "EBSEnabled": true,
          "VolumeType": "standard",
          "VolumeSize": 10
        }
      }
    }
  },
  "Outputs": {},
  "Description": "{\"createdOn\":\"Windows\",\"createdBy\":\"Amplify\",\"createdWith\":\"8.3.1\",\"stackType\":\"custom-customCloudformation\",\"metadata\":{}}"
}`

### Amplify Categories

custom

### Amplify Commands

push

### Describe the bug

I am unable to create opensearch domain via amplify cli using cloudformation template. it throws following error

**`Resource handler returned message: "Internal error occurred."`**

### Expected behavior

I expect either complete error detail or the success message that opensearch resource is created.

### Reproduction steps

1. create a new amplify app.
2. amplify add custom resource using `amplify add custom`.
3. use cloudFormation as template.
4. use the following template to add opensearch

`{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "env": {
      "Type": "String"
    }
  },
  "Resources": {
    "OpenSearchService": {
      "Type": "AWS::OpenSearchService::Domain",
      "Properties": {
        "AccessPolicies": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Action": "es:*",
              "Condition": {
                "IpAddress": {
                  "aws:SourceIp": "<your-ip-here>/32"
                }
              }
            }
          ]
        },
        "ClusterConfig": {
          "InstanceCount": 1,
          "InstanceType": "t2.small.search",
          "ZoneAwarenessEnabled": false
        },
        "EBSOptions": {
          "EBSEnabled": true,
          "VolumeType": "standard",
          "VolumeSize": 10
        }
      }
    }
  },
  "Outputs": {},
  "Description": "{\"createdOn\":\"Windows\",\"createdBy\":\"Amplify\",\"createdWith\":\"8.3.1\",\"stackType\":\"custom-customCloudformation\",\"metadata\":{}}"
}`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
`√ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev

┌──────────┬───────────────┬───────────┬───────────────────┐
│ Category │ Resource name │ Operation │ Provider plugin   │
├──────────┼───────────────┼───────────┼───────────────────┤
│ Custom   │ osfordd       │ Create    │ awscloudformation │
└──────────┴───────────────┴───────────┴───────────────────┘
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-ddrndos-dev-131724 AWS::CloudFormation::Stack Mon May 30 2022 15:49:07 GMT+0500 (Pakistan Standard Time) User Initiated
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS customosfordd AWS::CloudFormation::Stack Mon May 30 2022 15:49:13 GMT+0500 (Pakistan Standard Time) 
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS customosfordd AWS::CloudFormation::Stack Mon May 30 2022 15:49:14 GMT+0500 (Pakistan Standard Time) Resource creation Initiated
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-ddrndos-dev-131724-customosfordd-B3JMFSVRKW35 AWS::CloudFormation::Stack     Mon May 30 2022 15:49:14 GMT+0500 (Pakistan Standard Time) User Initiated 
CREATE_IN_PROGRESS OpenSearchService                                     AWS::OpenSearchService::Domain Mon May 30 2022 15:49:19 GMT+0500 (Pakistan Standard Time)
/ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OpenSearchService AWS::OpenSearchService::Domain Mon May 30 2022 15:49:22 GMT+0500 (Pakistan Standard Time) Resource creation Initiated
\ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED OpenSearchService                                     AWS::OpenSearchService::Domain Mon May 30 2022 16:06:43 GMT+0500 (Pakistan Standard Time) Resource handler returned message: "Internal error occurred." (RequestToken: e3c774e8-a7da-e94f-5eb4-1c542de12165, HandlerErrorCode: InternalFailure)
CREATE_FAILED amplify-ddrndos-dev-131724-customosfordd-B3JMFSVRKW35 AWS::CloudFormation::Stack     Mon May 30 2022 16:06:44 GMT+0500 (Pakistan Standard Time) The following resource(s) failed to create: [OpenSearchService]. 
- Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               customosfordd              AWS::CloudFormation::Stack Mon May 30 2022 16:07:22 GMT+0500 (Pakistan Standard Time) Embedded stack arn:aws:cloudformation:us-east-1:118012458843:stack/amplify-ddrndos-dev-131724-customosfordd-B3JMFSVRKW35/257a7250-e006-11ec-b1aa-128d7b0ae95d was not successfully created: The following resource(s) failed to create: [OpenSearchService].
UPDATE_ROLLBACK_IN_PROGRESS amplify-ddrndos-dev-131724 AWS::CloudFormation::Stack Mon May 30 2022 16:07:23 GMT+0500 (Pakistan Standard Time) The following resource(s) failed to create: [customosfordd].

| Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-ddrndos-dev-131724 AWS::CloudFormation::Stack Mon May 30 2022 16:07:55 GMT+0500 (Pakistan Standard Time) 
/ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS customosfordd AWS::CloudFormation::Stack Mon May 30 2022 16:07:57 GMT+0500 (Pakistan Standard Time) 
- Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS amplify-ddrndos-dev-131724-customosfordd-B3JMFSVRKW35 AWS::CloudFormation::Stack     Mon May 30 2022 16:07:58 GMT+0500 (Pakistan Standard Time) User Initiated
DELETE_IN_PROGRESS OpenSearchService                                     AWS::OpenSearchService::Domain Mon May 30 2022 16:08:00 GMT+0500 (Pakistan Standard Time)

DELETE_COMPLETE OpenSearchService AWS::OpenSearchService::Domain Mon May 30 2022 16:16:10 GMT+0500 (Pakistan Standard Time)
/ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-ddrndos-dev-131724-customosfordd-B3JMFSVRKW35 AWS::CloudFormation::Stack Mon May 30 2022 16:16:11 GMT+0500 (Pakistan Standard Time)
| Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE          customosfordd              AWS::CloudFormation::Stack Mon May 30 2022 16:16:25 GMT+0500 (Pakistan Standard Time)

Resource Name: opensearchservi-nkobofnaymxp (AWS::OpenSearchService::Domain)
Event Type: create
Reason: Resource handler returned message: "Internal error occurred." (RequestToken: e3c774e8-a7da-e94f-5eb4-1c542de12165, HandlerErrorCode: InternalFailure)


× An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
Resource is not in the state stackUpdateComplete`

```

</details>

**Comment by josefaidt** [comment]
Hey @rizvanhaider :wave: thanks for raising this! Out of curiosity, what is the motivation to deploy OpenSearch through a custom resource? I also have a few follow-up questions:

- are there any more descriptive errors in the CloudFormation console?
- are you able to deploy this CloudFormation template outside the context of Amplify?

**Comment by josefaidt** [comment]
Hey @rizvanhaider :wave: just wanted to follow-up on this one

**Comment by hoIIer** [comment]
Was there any resolution on this? Getting same error building similar stack outside amplify with regular cloudformation template:
```
  OpenSearchDomain:
    Type: 'AWS::OpenSearchService::Domain'
    Properties:
      ClusterConfig:
        InstanceCount: 2
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 20
        VolumeType: 'gp2'
    UpdatePolicy:
      EnableVersionUpgrade: true
```

**Comment by 0rdep** [comment]
Hi, i'm getting the same issue.
Theres any place that we can see the cloudformation logs? Or a detailed error message?

**Comment by hoIIer** [comment]
I was able to solve it by giving Cloudformation `es:*` permissions used in my build pipeline. Would have been helpful is they surfaced an error other than `Internal error`
