### ISSUE TITLE
Array Buffer Allocation Error when initializing Amplify for version 8.0.2 and above

### ISSUE THREAD

**Issue by kushagra1504** [aws-amplify/amplify-cli#10497]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.3.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Hi Team,

Facing this issue for Amplify above 8.0.2 and above whereas the setup works fine for 7.6.8. I have ensured that node version is 16.

The same error comes when running the immersion day with new version : 
https://webapp.serverlessworkshops.io/usermanagement/amplifycli/

ec2-user:~/environment/wild-rydes (master) $ amplify init
Downloading release from https://d2bkhsss993doa.cloudfront.net/8.3.1/amplify-pkg-linux-x64.tgz
node:internal/buffer:959
super(bufferOrLength, byteOffset, length);
^

RangeError: Array buffer allocation failed
at new ArrayBuffer ()
at new Uint8Array ()
at new FastBuffer (node:internal/buffer:959:5)
at createUnsafeBuffer (node:internal/buffer:1062:12)
at allocate (node:buffer:410:10)
at Function.allocUnsafe (node:buffer:375:10)
at Function.concat (node:buffer:553:25)
at Extract. (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/@aws-amplify/cli/lib/binary.js:124:37)
at Extract.emit (node:events:538:35)
at finishMaybe (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/@aws-amplify/cli/node_modules/readable-stream/lib/_stream_writable.js:624:14)

### Amplify Categories

custom

### Amplify Commands

init

### Describe the bug

Hi Team,

Facing this issue for Amplify above 8.0.2 and above whereas the setup works fine for 7.6.8. I have ensured that node version is 16.

The same error comes when running the immersion day with new version : 
https://webapp.serverlessworkshops.io/usermanagement/amplifycli/

ec2-user:~/environment/wild-rydes (master) $ amplify init
Downloading release from https://d2bkhsss993doa.cloudfront.net/8.3.1/amplify-pkg-linux-x64.tgz
node:internal/buffer:959
super(bufferOrLength, byteOffset, length);
^

RangeError: Array buffer allocation failed
at new ArrayBuffer ()
at new Uint8Array ()
at new FastBuffer (node:internal/buffer:959:5)
at createUnsafeBuffer (node:internal/buffer:1062:12)
at allocate (node:buffer:410:10)
at Function.allocUnsafe (node:buffer:375:10)
at Function.concat (node:buffer:553:25)
at Extract. (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/@aws-amplify/cli/lib/binary.js:124:37)
at Extract.emit (node:events:538:35)
at finishMaybe (/home/ec2-user/.nvm/versions/node/v16.14.2/lib/node_modules/@aws-amplify/cli/node_modules/readable-stream/lib/_stream_writable.js:624:14)

### Expected behavior

Amplify should initialize successfully and ask user for environment details, profile etc.

### Reproduction steps

1. npm install -g @aws-amplify/cli
2. echo '[profile default]' > ~/.aws/config
3. amplify init

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by stephenkruse** [comment]
We have the same exact issue :/

**Comment by stephenkruse** [comment]
Looks like the original instructions in the Workshop need to be updated. The Cloud9 instance needs to be t3.small, not t2.micro. 
Updating our instance to t3.small fixed the issue for us. 
Here are instructions on how to change your instance: 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-resize.html

**Comment by josefaidt** [comment]
Hey @kushagra1504 :wave: thanks for raising this! As @stephenkruse mentioned you will need to upgrade the instance type to a type that has more memory. Please let me know if that mitigates the issue!

**Comment by kushagra1504** [comment]
Thanks, I can verify that using t3.small fixes the issue. I will try and get the workshop steps modified accordingly. Thanks @josefaidt  and @stephenkruse !

**Comment by mgroff2** [comment]
Replicated the issue and fix this evening Can confirm WildRydes docs need to be updated. 
changed from t2.micro to t3.micro first and still wouldn't go. Then went to t3.small and it `amplify init` was able to complete.

**Comment by Nandhabhavan** [comment]
it looks like I am the only one who is getting this issue again and again even after changing the instance type to t3.small. Can anyone help me out

**Comment by rahulspoudel** [comment]
Looks like changing to t3.micro is the only way. Also, anyone has issues with instance running might be due to termination protection setting or cloud9 session opened in browser of the project environment running (it was the case with me). Thanks all.

**Comment by rahulspoudel** [comment]
Looks like changing to t3.small is the only way. Also, anyone has issues with instance always running while trying to stop (stopping -> pending -> running) might be due to termination protection setting or cloud9 session opened in browser of the project environment running (it was the case with me). Thanks all.
