### ISSUE TITLE
[GraphQL API] 'amplify status api -acm' CLI command not supported for flutter?

### ISSUE THREAD

**Issue by lfraker** [aws-amplify/amplify-cli#10507]
### Description

While debugging a separate issue, I attempted to use the Amplify CLI control matrix report as documented here: https://docs.amplify.aws/cli/graphql/authorization-rules/#advanced

The report does not print out anything about the model control matrix; output is just as follows:
<img width="549" alt="Screen Shot 2022-06-01 at 1 24 21 PM" src="https://user-images.githubusercontent.com/5459537/171465536-b8e669a3-9370-4269-81c5-aeb292901989.png">

I attempted to run this from the repo root and from the amplify API directory. Am I running this command wrong, or is this feature not supported for Flutter?

Also, is there a list of features supported by Amplify CLI that aren't supported in Amplify Flutter? I've been logging issues, but wondering if there's a quicker way for me to check and make sure the features are supposed to be supported before logging an issue?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Go to a project repository with API enabled
2. Run 'amplify status api -acm <model name>'
3. See that the output is not as expected.

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
N/A
```

### Device

N/A

### OS

N/A

### CLI Version

5.3.1

### Additional Context

Excluding dependencies, because it's a long list and unnecessary/unrelated to the problem since the problem is an Amplify CLI issue.

**Comment by josefaidt** [comment]
Hey @lfraker :wave: thanks for raising this! As @HuiSF pointed out this may be due to an older version of the CLI where this was either not working as expected or not supported at the time. What version of the CLI are you using?

**Comment by lfraker** [comment]
@HuiSF thanks for pointing that out!

@josefaidt definitely looks like I was using an older version of the CLI. I had run 'amplify upgrade' but hadn't upgraded via npm. Upgrading now and seeing if that resolves it! Will update shortly.

**Comment by lfraker** [comment]
@josefaidt that was the issue; closing this issue. Sorry for the confusion!
