### ISSUE TITLE
amplify auth remove does delete item in AWS 

### ISSUE THREAD

**Issue by batical** [aws-amplify/amplify-cli#10518]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.11.1

### Amplify CLI Version

8.3.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

amplify remove auth

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

A little story here

We were using a Cognito auth created with amplify with email login
We wanted to switch to SMS (and chose other configuration)

As it is not possible through amplify, here are the step
- create the new cognito
- add it in the federated identity pool as a second cognito
- add it in app sync
- remove all auth dependency in amplify and add it manually with both cognito
- create a migration process between both cognito

This was working fine since more than 3/4 month but had a more and more issue with access on app sync  (see #9702) and not only on key but even on mutation created with @model (the situation is worse than before)

all of are users did migrate to the new version of the mobile app so the old cognito is required only for migration now.
To avoid issue the issue of access app sync , I decided to replace the auth in the amplify cli stack, use the new cognito as default in app sync.(with fix lot of app sync access error)

- I check I did no have dependency to auth in amplify
- I did amplify remove auth
- amplify import auth (this was correctly import with authRole, unauthRole) etc.
-
```
"auth": {
        "XXXXXX": {
          "userPoolId": "eu-west-1_XXXXX",
          "userPoolName": "XXXXX",
          "webClientId": "XXXX",
          "nativeClientId": "XXXX8",
          "identityPoolId": "eu-west-1:XXXXXX",
          "identityPoolName": XXXXXX,
          "allowUnauthenticatedIdentities": false,
          "authRoleArn": "arn:aws:iam::xxxxx:role/xxxxxx-authRole",
          "authRoleName": "xxxxx7-authRole",
          "unauthRoleArn": "arn:aws:iam::xxxx:role/xxxxx-unauthRole",
          "unauthRoleName": "xxxxx7-unauthRole"
        }
      }
```

BUT from your doc
https://docs.amplify.aws/cli/auth/import/#unlink-an-existing-cognito-user-pool-or-identity-pool

`"In order to unlink your existing Cognito resource run amplify remove auth. This will only unlink the Cognito resource referenced from the Amplify project. It will not delete the Cognito resource itself."`

It actually did a lot of mess.

-  userPool : App integration -> App clients and analytics were all deleted
- Federated Identity -> identity Pool was deleted (the one which was imported by auth import command)
- it tried to delete the userPool but failed (amplify push was successful) (I was not able to find the log)
- still looking for other breaking thing 

I try to force push hoping for restauration of identityPoolId without success.
I had to recreate all  manually.

this was on a DEV env so we don't really care but we are afraid of migrating to prod env

### Expected behavior

do not delete the user pool id and all configuration

### Reproduction steps

See description of bug

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hello @batical, how was the initial `auth` resource created? If the `auth` resource was created by amplify executing `amplify auth remove` will remove the auth resources in cognito. If `auth` resource was imported then `amplify auth remove` should not remove the cognito resource. Can you please add more details on how exactly the `auth` resource was initially created? are you able to share a set of reproduction steps?

**Comment by batical** [comment]
Hello

Indeed, the auth was created using amplify add auth (something like that) when we bootstrap the project.
I maybe misunderstood the documentation.

It seems that it is working as intended. Is there a way to remove the auth in CloudFormation stack without removing  all cognito resources ? (by editing the auth folder, team provider file, backend file ? )

**Comment by batical** [comment]
this one the only way i found to make avoid access issue with appsync and 2 cognito because auth rôle seems not configured correctly ( a guess )
