### ISSUE TITLE
amplify pull (failure) - Failed to pull the backend. 🛑 Unexpected end of JSON input SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at getOAuthProviderKeys ....

### ISSUE THREAD

**Issue by renatovanquish** [aws-amplify/amplify-cli#10522]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

8.3.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

After this issue ##10466 - I can't pull from the environment

amplify pull --appId XXXXXXXX --envName dev
Opening link: https://us-east-1.admin.amplifyapp.com/admin/XXXXXXXX/dev/verify/
✔ Successfully received Amplify Studio tokens.
Amplify AppID found: XXXXXXXX. Amplify App name is: app-sls-lav
Backend environment dev found in Amplify Console app: app-sls-lav
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: .next
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? Yes
⠦ Building resource api/ApiGraphQL✅ GraphQL schema compiled successfully.

Edit your schema at /Users/rtc/Dev/app-sls-lav/amplify/backend/api/ApiGraphQL/schema.graphql or place .graphql files in a directory at /Users/rtc/Dev/app-sls-lav/amplify/backend/api/ApiGraphQL/schema
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
🛑 Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getOAuthProviderKeys (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:157:38)
    at updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:103:36)
    at /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:272:34
    at /snapshot/repo/build/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

### Expected behavior

I expected the pull to complete successfully!
But it's not finished!

### Reproduction steps

amplify pull --appId XXXXXXX --envName dev

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @renatovanquish, thank you for reaching out. On replicating this in my application I was unable to reproduce the error. I utilized the following steps in application.

1. Install amplify CLI version `8.3.0`.
2. added Outh flow to reproduce the [oAuthSecathAmplifyAppId] must have values error
3. upgraded the CLI version to `8.3.1` and did a push.
4. enabled studio and did a amplify pull.

I did not observe an error. In order to dive deeper into the issue, could you please provide us the following information.

1. Reproduction steps that can help us in replicating the error. 
2. cli-inputs.json file present under auth -> <auth name> folders.

**Comment by ykethan** [comment]
hey @renatovanquish, following up to see if you are experiencing any issues.

**Comment by ykethan** [comment]
closing the issue due to inactivity
