### ISSUE TITLE
Support lambda runtime for dotnet6

### ISSUE THREAD

**Issue by jonschoning** [aws-amplify/amplify-cli#10527]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

https://github.com/aws/aws-extensions-for-dotnet-cli supports .net 6 as described here. https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

the amplify cli hardcodes `dotnetcoreapp3.1` when invoking `dotnet lambda package` https://github.com/aws-amplify/amplify-cli/blob/da69dc8f71469b80830dd459b4be3b3c5e2accc4/packages/amplify-dotnet-function-runtime-provider/src/utils/package.ts

### Describe the solution you'd like

Since `dotnet lambda package` supports dotnet6 runtime, amplify cli should not hardcode `dotnetcoreapp3.1` when it attempts to package

### Describe alternatives you've considered

n/a

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @jonschoning :wave: thanks for raising this! I've marked this as a feature request for the team to evaluate further 🙂

**Comment by lomaky** [comment]
+1

**Comment by MauricioPaez** [comment]
+1
