### ISSUE TITLE
Amplify pull being blocked by Zscaler. 

### ISSUE THREAD

**Issue by tahgio** [aws-amplify/amplify-cli#10549]
I'm trying to fecth data through `amplify pull` but I'm being blocked by the Zscaler proxy. I keep getting the `unable to get local issuer certificate` error. Is there any command that I can run in my CLI to get amplify to know my certificate? 

I've already talked to my company support but they are having a big trouble to help me. Would anyone help me with this?

Thank you.

**Comment by ykethan** [comment]
hello @tahgio, The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/8361. Environment variables will need to be set for the HTTP_PROXY and HTTPS_PROXY environment variables with either the DNS domain names or IP addresses. Please refer to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html

**Comment by tahgio** [comment]
Yes. It seems that it is very similar to #8361. Thank you for your answer, my company support was able to help me with this at the end!
