### ISSUE TITLE
Changing DynamoDBBillingMode after failed updated not possible 

### ISSUE THREAD

**Issue by wbroek** [aws-amplify/amplify-cli#1054]
When I changed the DynamoDBBillingMode in the parameters.json and the update fails for another reason (like schema error etc) we push the new changes again I get the error message below: 

`
Subscriber limit exceeded: Update to PayPerRequest mode are limited to once in 1 day(s).
`

I understand the error but because my first push got the errors it looked like the change for DynamoDBBillingMode was not preserved? Or it should allow me to do the change because the error occurred 

Also do these changes apply to old tables as wel?

**To Reproduce**
- Set DynamoDBBillingMode to PAY_PER_REQUEST (or to PROVISIONED if it was PAY_PER_REQUEST) in the parameters.json
- Make an mistake in the schema.graphq (or other thing that the cli will error about)
- Push
- Correct the mistake
- Push again

**Comment by mikeparisstuff** [comment]
@wbroek Unfortunately this is a limit DynamoDB implements and there is very little we can do to prevent it. I suggest keeping your DynamoDB billing setting for one more day and then push you API with no other changes as soon as the limit exception is lifted.
