### ISSUE TITLE
Two back-ends use

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#10551]
**Which Category is your question related to?**
Amplify GraphQL API

**Amplify CLI Version**
8.4.0

**What AWS Services are you utilizing?**
Amplify GraphQL API

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Hi. I have about twenty tables without need of conflict resolution. And I just need one more for conflict resolution. Is it possible to use two Amplify back-ends in one application ? If not, how to work around this problem ?

**Comment by lazpavel** [comment]
Hi, it is possible to use multiple back-end for a single front-end application, however amplify doesn't provide any coordination logic between those backends and this will need to be handled manually. As for the GQL apis, currently we only support one API per application
