### ISSUE TITLE
GOlang functions build has stopped working

### ISSUE THREAD

**Issue by sky4git** [aws-amplify/amplify-cli#10564]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn global add @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

8.4.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I have a few `GOlang` functions. After updating the new amplify CLI version. It throws the following error. 

```
🛑 An error occurred during the push operation: /
Command failed with exit code 1: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

The same error has also been thrown by `amplify build function GolangFunction -y`

### Expected behavior

`amplify push --yes` should work without any errors.

### Reproduction steps

1. Install latest amplify cli `yarn global add @aws-amplify/cli`
2. install Golang version `1.18.2`
3. create Golang function
4. try to build function using `amplify build function GolangFunction -y` OR
5. use `amplify push --yes` command

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @sky4git, Thank you for reporting. I was able to reproduce the issue. marking this as bug.

Note: This occurs on a windows machine.
When cd'ing into the lambda function folder, I am able to run `go mod tidy`.  
But the amplify build function still throws the error.
```
Error: Command failed with exit code 1: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
go: module github.com/aws/aws-lambda-go/cmd/build-lambda-zip: Get "https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/build-lambda-zip/@v/list": dial tcp: lookup proxy.golang.org: no such host
```
