### ISSUE TITLE
Unfortunatly deleted my amplify project

### ISSUE THREAD

**Issue by BastienFerrier** [aws-amplify/amplify-cli#10560]
Hello,

I'd like to know if there is any way to recover from a deleted app in amplify. I have had a look but the only way is to create again and push back all config into the project.
All resources are still here (API, Auth, Cloud Formation,...) but the project is not.

Any solution would be much appreciated.

If it can help here is the id of the app: "d2cpl188hyw53h".

Thank you

**Comment by biller-aivy** [comment]
If you mean the amplify console, you can just add it again as new app from the repo. Amplify will find the amplify folder inside

**Comment by BastienFerrier** [comment]
Hi @biller-aivy 

Thanks' for the feedback.

This is what I did, adding a new project with "amplify init" but the thing is that everything from the previous amplify app is not linked and I don't know how to do that.

I have auth, API, functions, custom headers, Redirect, domain ... 
Everything is still in a cloudformation stack but I don't know how can I deploy this stack in my new amplify app.

Bastien

**Comment by biller-aivy** [comment]
So when you add the app, you can choose the backend right? so you have to choose the old backend. For this, there should be a amplify folder in the git repo I guess. 
Are you premium support customer? Sometimes they can restore some things for you a few hours.

**Comment by josefaidt** [comment]
Hey @BastienFerrier :wave: thanks for raising this and apologies for the delay here! As @biller-aivy mentioned if we have the Amplify backend folder and an existing stack, we should be able to recreate the Amplify app (with a valid App ID) with `amplify init`. Using the existing configuration, this should allow you to initialize the existing backend environment with your resources.

We can check the Amplify App ID by looking for `AmplifyAppId` in `amplify/backend/amplify-meta.json`
