### ISSUE TITLE
Amplify mock not working in 8.0.3 with Cognito User Pools

### ISSUE THREAD

**Issue by jw4949** [aws-amplify/amplify-cli#10578]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.9.0

### Amplify CLI Version

8.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

`amplify mock` opens, but the Explorer is empty.

### Expected behavior

Queries, Mutations and Subscriptions are shown on the left in Explorer

### Reproduction steps

1. Start `amplify mock`
2. Open `AppSync Mock endpoint is running at http://...`

### Additional information

Downgrade to CLI resolved this issue
`npm install -g @aws-amplify/cli@8.0.2`

**Comment by dwamianm** [comment]
@akinwol @kolodi @lazpavel ... 8.5.1 has fixed this issue for me!

**Comment by naingaungphyo** [comment]
I can confirm that it is also working in 9.0.0.

**Comment by AlirezaNikkhah1375** [comment]
I can confirm that my schema is available in version 9.1.0

**Comment by giovani-milanez** [comment]
It seems that this problem is back on versions 10.7.x
Downgrading to version 10.6.2 works:
npm install -g @aws-amplify/cli@10.6.2

**Comment by jonathanRos** [comment]
Back again on Version 11.0.3
Downgrading to version 10.6.2 works:
npm install -g @aws-amplify/cli@10.6.2

**Comment by michaelrios** [comment]
I have this issue in 11.1.0

**Comment by Bandisa** [comment]
I experienced the same issue.
## Hardware And Software Info
### Hardware
M2 MacBook Air
### Amplify CLI
[12.0.0](https://github.com/aws-amplify/amplify-cli/releases/tag/v12.0.0)
### Node
v18.16.0
### Java
```sh
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
## Solution
I firstly downgraded my java as per doc, which did not resolve the issue, then downgraded to @aws-amplify/cli@10.6.2 as [@michaelrios](https://github.com/michaelrios) mentioned above. and it worked.

**Comment by spoturno** [comment]
Hi, I have the same issue in 12.1.1

java: 
```
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9-78)
OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

Do I need to downgrade to 10.6.2 and my java version as @Bandisa mentioned above?

**Comment by Phok7** [comment]
Hello, the bug still happens in aws-amplify/cli@12.8.2

java version:

```
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment (build 18+36-2087)
OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

Node v18.13.0.

If I downgrade to aws-amplify/cli@10.6.2 it's works.
