### ISSUE TITLE
Function with IAM authorization gets "Not Authorized to access" error in GraphQL request

### ISSUE THREAD

**Issue by OskarD** [aws-amplify/amplify-cli#10586]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.0

### Amplify CLI Version

8.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, function

### Amplify Commands

Not applicable

### Describe the bug

There is something wrong with IAM authorization in functions

Result:
```
{
  "statusCode": 400,
  "body": "{\"data\":{\"listBlogs\":null},\"errors\":[{\"path\":[\"listBlogs\"],\"data\":null,\"errorType\":\"Unauthorized\",\"errorInfo\":null,\"locations\":[{\"line\":3,\"column\":5,\"sourceName\":null}],\"message\":\"Not Authorized to access listBlogs on type ModelBlogConnection\"}]}"
}
```

I created a sample project with the bug: https://github.com/OskarD/amplify-iam-function

### Expected behavior

The function should return a GraphQL result :)

### Reproduction steps

1. `amplify init`
2. `amplify add auth`
```
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM cont
rols (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
```

3. `amplify add api` with the relational boilerplate (Blogs, posts, comments)
```
Authorization modes
- Default: Amazon Cognito User Pool
- IAM

Conflict detection (required for DataStore)
- Conflict resolution strategy: Auto Merge
```

4. `amplify add function`
```
? Select the categories you want this function to have access to. api
? Select the operations you want to permit on amplifyiamfunction Query
```

5.  `amplify push`
6. Put [GraphQL from NodeJS IAM Authorization](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#iam-authorization) example code into the function 
7. Put `@auth(rules: [{allow: private, provider: iam}])` on the GraphQL type declarations in `amplify/backend/api/apiname/schema.graphql`
8. `amplify push`
9. `amplify mock function`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Blog @model @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  post: Post @belongsTo
  content: String!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
Ensuring latest function changes are built...
Starting execution...
EVENT: {"key1":"value1","key2":"value2","key3":"value3"}
Result:
{
  "statusCode": 400,
  "body": "{\"data\":{\"listBlogs\":null},\"errors\":[{\"path\":[\"listBlogs\"],\"data\":null,\"errorType\":\"Unauthorized\",\"errorInfo\":null,\"locations\":[{\"line\":3,\"column\":5,\"sourceName\":null}],\"message\":\"Not Authorized to access listBlogs on type ModelBlogConnection\"}]}"
}
Finished execution.

```

</details>

**Comment by MaximeIJ** [comment]
Hi @josefaidt, I'm also facing this (saw the thread on Discord and https://github.com/aws-amplify/amplify-cli/issues/10535) 

I looked into the auth VTL of one of the impacted queries and saw three 'adminRoles', two of which were Cognito-related and the last one was the name of my custom function along with its env ('darnwin-dev').

I double checked and there's no such role. The function 'darwin-dev' itself uses a differently named execution role. 

Could that be the issue: it adds the function's name as adminRole instead of its iam execution role arn?

**Comment by josefaidt** [comment]
Hey @MaximeIJ :wave: apologies for the delay here! I also have the function names in the admin roles `listusers-dev`. Would you mind filing a [separate issue](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) to capture the up-to-date, relevant details to better understand the context of your issue?
