### ISSUE TITLE
Query graphql api from Lambda Function

### ISSUE THREAD

**Issue by andy-HM** [aws-amplify/amplify-cli#10593]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify Lambda Function

**Amplify CLI Version**
8.1.0

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
auth, graphql api, storage, functions

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I am attempting to follow the [GraphQL From NodeJS ](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/) without success.  I have copied and pasted the code from the query section of the document.  However, I am receiving an error stating that "only absolute URLs are supported".  I have granted update and read permissions to my function during setup.  

My usage question is - is this documentation still up to date and is there a different way I should be doing this from a lambda function? 

Here is my code - modified to fit my API:

```js
`/* Amplify Params - DO NOT EDIT
	API_HFCAPI_GRAPHQLAPIENDPOINTOUTPUT
	API_HFCAPI_GRAPHQLAPIIDOUTPUT
	API_HFCAPI_GRAPHQLAPIKEYOUTPUT
	ENV
	REGION
Amplify Params - DO NOT EDIT */

const fetch = require('node-fetch')
const Request = require('node-fetch')    

const GRAPHQL_ENDPOINT = process.env.API_HFCAPI_GRAPHQLAPIENDPOINTOUTPUT;
const GRAPHQL_API_KEY = process.env.API_HFCAPI_GRAPHQLAPIKEYOUTPUT;

const query = /* GraphQL */ `
query ListProfiles {
  listUserProfiles {
    items {
      id
      firstName
    }
  }
}
`;

const variables = {}

/**
//  * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
 exports.handler = async (event) => {

    console.log(`EVENT: ${JSON.stringify(event)}`);
    console.log(GRAPHQL_ENDPOINT)
    console.log(GRAPHQL_API_KEY)

    // /** @type {import('node-fetch').RequestInit} */
    const options = {
        method: 'POST',
        headers: {
        'x-api-key': GRAPHQL_API_KEY
        },
        body: JSON.stringify({ query, variables })
    };

    const request = await new Request(GRAPHQL_ENDPOINT, options);

    let statusCode = 200;
    let body;
    let response;

    try {
        response = await fetch(request);
        body = await response.json();
        if (body.errors) statusCode = 400;
    } catch (error) {
        statusCode = 400;
        body = {
        errors: [
            {
            status: 400,
            message: error.message,
            stack: error.stack
            }
        ]
        };
    }

    return {
        statusCode,
        body: JSON.stringify(body)
    };

};
```

**Comment by josefaidt** [comment]
Hey @andy-HM :wave: thanks for raising this! Reading the error it almost sounds as if the environment variables are not populated and the endpoint URL is not valid, however I also noticed these imports

```js
const fetch = require('node-fetch')
const Request = require('node-fetch')  
```

where you'll want to import the named export `Request`

```js
const fetch = require('node-fetch')
const { Request } = require('node-fetch')  
```

**Comment by andy-HM** [comment]
Hello @josefaidt.  I am now receiving the following unauthorized error.  In my function configuration I have set full permissions on my API as well as the storage on my table I am querying.  In either case, I am still getting this error.  Any suggestions where I should turn next?

`
{
  "statusCode": 400,
  "body": "{\"data\":{\"listUserProfiles\":null},\"errors\":[{\"path\":[\"listUserProfiles\"],\"data\":null,\"errorType\":\"Unauthorized\",\"errorInfo\":null,\"locations\":[{\"line\":3,\"column\":3,\"sourceName\":null}],\"message\":\"Not Authorized to access listUserProfiles on type Query\"}]}"
}
`

**Comment by dwamianm** [comment]
@josefaidt +1 for this issue where querying my graphql from a lambda function is giving me an Unauthorized response. In fact, even selecting IAM from the appsync console is giving me an Unauthorized response. My schema has the correct auth rules setup and IAM is shown as an additional authorizer in the console as expected... but I am unable to execute any mutations using an IAM role.

**Comment by andy-HM** [comment]
@dwamianm I was able to get this figured out on my end by changing my auth rules on my model.  [Checkout the Amplify docs for more details](https://docs.amplify.aws/cli/graphql/authorization-rules/#global-authorization-rule-only-for-getting-started).  

Originally, I just had "private" on my model but I added "public".  Based on the docs, this would allow authentication by API key which is how this works from a Lambda function.  

Went from:
`@auth(rules: [{allow: private}])`

To:
`@auth(rules: [{allow: private}, {allow: public}])`

**Comment by josefaidt** [comment]
Hey @andy-HM :wave: apologies for the missed response here, but it appears you're experiencing the bug described here https://github.com/aws-amplify/amplify-cli/issues/10445#issuecomment-1134819106
