### ISSUE TITLE
How would you handle dev/prod enviroments with the CLI?

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#106]
**Do you want to request a feature or report a bug?**
Feature
**What is the current behavior?**
There's no dev and prod.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
How would you go about creating a development and production environment? 

**Steps to reproduce the issue:**

1. amplify publish 
2. updates aws environment
3. only one environment available

**What is the expected behavior?**
Some way to push to a test environment first.

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
MacOS
* **Output of ``amplify --version``**:
0.1.14
* **Did this work in previous versions?**: Y/N
N

**Comment by kaustavghosh06** [comment]
Yes, you're right @chrisco255 . We're working currently to make the staging experience better and will soon have a solution for it.

**Comment by jarrettj** [comment]
Awesome stuff. Will keep an eye out. Regards.

**Comment by swaminator** [comment]
@jarrettj @chrisco255 I'm a PM on the team and would love to chat with you to understand your expectations for managing multiple environments. If you could share your email I'll get in touch.

**Comment by chrisco255** [comment]
Hi @swaminator ufcordle@hotmail.com works for me. Thanks!

**Comment by andrewtpoe** [comment]
I'm looking to learn the amplify CLI as it appears to be a superb resource. I would love to see support for testing/staging/production environments.

**Comment by kaustavghosh06** [comment]
@jarrettj  @chrisco255 @andrewtpoe 
We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backwards from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by kaustavghosh06** [comment]
Based on all of your feedback, we’ve released a beta version of the CLI (npm install -g @aws-amplify/cli@multienv)  to support multiple environments, team workflows and integrate with your CI/CD flows.
Please check out this documentation for more details - https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Also, as a part of our feedback mechanism, we’ve opened up another [GitHub issue](https://github.com/aws-amplify/amplify-cli/issues/508),  to track feedback from everyone, iterate on this beta version and then merge it to master.  We'll close this issue and track feedback in #508. Looking forward to your feedback on this release.

**Comment by kaustavghosh06** [comment]
Closing this issue since this problem is solved with the release of the multienv feature-set mentioned above. Please feel free to re-open the issue if you've further questions about this.

**Comment by jarrettj** [comment]
Awesome! Started looking at amplify again and setting it up for multiple devs is all good. Thanks.
