### ISSUE TITLE
Cognito auth groups do not get added

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#10613]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.5.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

add, update

### Describe the bug

On creating a Cognito Auth and adding multiple auth groups. The first groups gets added to the resource and the remaining are removed.

adding multiple groups:
![image](https://user-images.githubusercontent.com/87995712/173906787-b81c8500-ea34-4a46-aa6f-460011345f88.png)

running update auth again:
![image](https://user-images.githubusercontent.com/87995712/173906895-412c3cd1-77a9-4f89-80f2-ba10edd16f91.png)

on checking user-pool-group-precedence file
![image](https://user-images.githubusercontent.com/87995712/173907069-4ff1f99c-26bf-4089-94d1-051bc2a5a51a.png)

### Expected behavior

ability to add multiple groups

### Reproduction steps

1. amplify add auth
2. amplify update auth 
3. select `Create or update Cognito user pool groups`
4. check the cloudformation and user-pool-group-precedence

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
closing in favour of https://github.com/aws-amplify/amplify-cli/pull/10641
