### ISSUE TITLE
Custom property type on model type

### ISSUE THREAD

**Issue by patrickeddy** [aws-amplify/amplify-cli#1064]
**Which Category is your question related to?**
API/GraphQL

**What AWS Services are you utilizing?**
AppSync, GraphQL Transform

**Provide additional details e.g. code snippets**
I'm trying to add a custom field type to a @model annotated GraphQL type like so:
```
enum NotificationMethod {
  ALL
  SMS
  EMAIL 
}
type Settings {
  notifications: NotificationMethod
}
type User @model {
 settings: Settings
}
```
However, whenever I try and `amplify push`, I receive this error about the generated subscriptions:
```
.../src/graphql/subscriptions.ts: Field "settings" of type "Settings" must have a selection of subfields. Did you mean "settings { ... }"?
✔ Generated GraphQL operations successfully and saved at src/graphql
```

Oddly enough, the push succeeds and everything works as normal. Queries/mutations in the GraphQL console all work as expected. The generated `src/graphql/subscriptions.ts` file however is not selecting the appropriate Settings.notifications subfield for a response though, and therefore we're getting this error.

I'm assuming this type of nesting of types is probably solved by normalizing the data and separating the settings out into a `Settings @model` and then adding a `@connection`, however we'd like to keep these settings on the User.

What's the recommended way forward here?

**Comment by yuth** [comment]
@patrickeddy this is a bug in codegen. I will work on fixing this, but in the meantime you could fix this by increasing the maximum statement depth to 3. You can do this by running `$ amplify codegen configure` and setting `Enter maximum statement depth [increase from default if your schema is deeply nested]` to 3

**Comment by patrickeddy** [comment]
@yuth thank you so much for the fast follow-up on this! Unfortunately even after setting the maximum statement depth to 3 or 4, I get the same error.
