### ISSUE TITLE
Cannot delete amplify project

### ISSUE THREAD

**Issue by mikefrancis** [aws-amplify/amplify-cli#10646]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

8.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, I removed the CloudFormation stacks

### Amplify Categories

Not applicable

### Amplify Commands

delete

### Describe the bug

I cannot delete the remnants of my Amplify project, I get the same error message as this:

https://github.com/aws-amplify/amplify-cli/issues/3204

And recreating the bucket and ZIP file, then deleting doesn't work.

I've tried using the CLI to do this and the Console, no dice.

### Expected behavior

I am able to delete my Amplify project

### Reproduction steps

1. Create a new Amplify project
2. Delete any related CLoudFormation stacks
3. Try to delete Amplify project

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

d2qg0knx7d1qfz

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @mikefrancis :wave: thanks for raising this! Does the Amplify project still exist in the AWS Console? Are you able to reinitialize the stacks with `amplify init` and choosing to initialize one of the existing backends? If not, the appropriate route would be to manually delete the previously-associated resources and use the AWS CLI to remove the Amplify app

**Comment by mikefrancis** [comment]
I should also add that this is making us hit our limit of AWS Amplify apps in a particular region, so we literally cannot deploy one project until this is fixed.

**Comment by josefaidt** [comment]
Hey @mikefrancis thanks for clarifying! While this is not a supported workflow, we can manually remove the Amplify app and associated backends with the AWS CLI. Please see https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html for more information. For the remaining, orphaned resources these can be manually deleted either with the AWS CLI or through the AWS Console

**Comment by mikefrancis** [comment]
@josefaidt Thank you so much, that's fixed it right up.
