### ISSUE TITLE
Amplify geo populate command not found

### ISSUE THREAD

**Issue by venuvasu** [aws-amplify/amplify-cli#10649]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

9.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, api

### Amplify Commands

add, Not applicable

### Describe the bug

I have created a geo fence collection using amplify add geo category. After that , I am trying to populate my geo fence collection using command amplify geo populate [according to https://docs.amplify.aws/cli/geo/geofencing/#upload-your-own-geojson-file-to-geofence-collection]. It says command not found.

$ amplify geo populate
⚠️ The Amplify CLI can NOT find command: geo populate
amplify geo <subcommand>

  add       Takes you through a CLI flow to add a geo resource to your local backend                                       
  update    Takes you through steps in the CLI to update a geo resource                                                    
  push      Provisions only geo cloud resources with the latest local developments                                         
  remove    Removes geo resource from your local backend. The resource is removed from the cloud on the next push command. 
  console   Opens the web console for the geo category            

### Expected behavior

? Provide the path to GeoJSON file containing the Geofences for ${your_geofence_collection} collection:
> ${your_input_geojson_file_path}

### Reproduction steps

1. amplify add geo [geo fences]
2. amplify push
3. amplify geo populate

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
The document has been updated with the latest command change https://docs.amplify.aws/cli/geo/geofencing/#upload-your-own-geojson-file-to-geofence-collection
