### ISSUE TITLE
Adding secret key doesn't update lambda role permissions

### ISSUE THREAD

**Issue by SaileshKumar** [aws-amplify/amplify-cli#10653]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

8.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

I added a secret variable to my function via amplify update function, but when trying to access it I get denied saying that my lambda role can't call GetParameters "because no identity-based policy allows the ssm:GetParameters action".

### Expected behavior

Would expect that the CLI would add the correct permissions when adding secret variables.

### Reproduction steps

1. amplify update function
2. add secret variable
3. attempt to access with the autogenerated code
4. see error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @SaileshKumar :wave: thanks for raising this! I was not able to reproduce this behavior using the latest version of the CLI and using two different functions, one where I've added the secret prior to pushing on `amplify add function`, and one where I've added secrets after initially pushing with `amplify update function`. Can you confirm your function's CloudFormation template received the `AmplifyFunctionSecretsPolicy` policy?

```json
"AmplifyFunctionSecretsPolicy": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-function-secrets-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ssm:GetParameter",
                "ssm:GetParameters"
              ],
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:aws:ssm:",
                    {
                      "Ref": "AWS::Region"
                    },
                    ":",
                    {
                      "Ref": "AWS::AccountId"
                    },
                    ":parameter",
                    {
                      "Fn::Sub": [
                        "/amplify/${appId}/${env}/AMPLIFY_${functionName}_",
                        {
                          "appId": {
                            "Ref": "secretsPathAmplifyAppId"
                          },
                          "env": {
                            "Ref": "env"
                          },
                          "functionName": "10653ead92285"
                        }
                      ]
                    },
                    "*"
                  ]
                ]
              }
            }
          ]
        }
      },
      "DependsOn": [
        "LambdaExecutionRole"
      ]
    }
```
