### ISSUE TITLE
New groups are not created when updating user pool groups

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#10662]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.5

### Amplify CLI Version

9.0.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

When running `amplify update auth` and adding new user pool groups,  the new user pool groups are not added after running `amplify push -y`.

I can see that the `user-pool-group-precedence.json` is updated to reflect the precedence of the groups (with the new additions):

```
[
  {
    "groupName": "basic",
    "precedence": 1
  },
  {
    "groupName": "editor",
    "precedence": 2
  },
  {
    "groupName": "admin",
    "precedence": 5
  }
]
```
Any ideas on what could be causing this? This used to work...

### Expected behavior

New user pool groups should be added.

### Reproduction steps

1. Create a user pool with the CLI with a few groups.
2. Run `amplify update auth` and add new user pool groups.
3. Run `amplify push` and see that the new groups were not created.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kylekirkby** [comment]
Update:

I updated the `user-pool-group-precedence.json` manually, adding the missing Cognito groups. I then executed `amplify push` to then be greeted with this lovely error:

```
CREATE_FAILED companyContributorGroupRole AWS::IAM::Role Wed Jun 29 2022 09:33:27 GMT+0100 (British Summer Time) us-east-1_GHxxxxx-companyContributorGroupRole already exists
CREATE_FAILED companyAdminGroupRole       AWS::IAM::Role Wed Jun 29 2022 09:33:27 GMT+0100 (British Summer Time) us-east-1_GHxxxxxx-companyAdminGroupRole already exists
```
My guess is that these roles were left dangling after running `amplify update auth`. I may try to delete these manually in the console and run `amplify push` again..

**Comment by kylekirkby** [comment]
OK, so deleting the dangling roles manually in the IAM console has fixed the above issue. So, updating `user-pool-group-precedence.json` manually is the temporary solution for Amplify CLI not adding the new Cognito groups...

**Comment by ykethan** [comment]
Hello @kylekirkby, Thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/10613. A PR has been created addressing this: https://github.com/aws-amplify/amplify-cli/pull/10641.

I will be closing this Github issue to keep the whole information related to this behaviour on a single stream to avoid any miscommunication. Please feel free to add your comments to the linked issue.
