### ISSUE TITLE
Amplify issue with pushing things on AWS

### ISSUE THREAD

**Issue by hammadxoho** [aws-amplify/amplify-cli#1066]
**Describe the bug**
I have created a lot of functions, APIs, storages and an auth with amplify. It was working all fine, but since last night i have not been able to push any changes on AWS. I wanted to edit one function and after editing, it reported the following

`⠋ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete` 

![PatientApp — -bash — 211×51 2019-03-19 13-28-30](https://user-images.githubusercontent.com/27281661/54591527-3ba2b680-4a4c-11e9-89f6-966260ade455.png)

Since then upon googling the issue,  i ran the following which updated my amplify cli
`npm install -g @aws-amplify/cli@latest`

And now when i push, amplify detects that the project was initialized using an older version of the CLI, and want me to migrate the project so that it is compatible with the latest version of the CLI.

If i enter yes i get the following
![PatientApp — -bash — 211×49 2019-03-19 13-34-07](https://user-images.githubusercontent.com/27281661/54591549-48270f00-4a4c-11e9-9257-df8b62829f10.png)

If i enter no i get the following
![PatientApp — -bash — 211×49 2019-03-19 13-34-33](https://user-images.githubusercontent.com/27281661/54591591-5ffe9300-4a4c-11e9-891a-ee1d19ca36e5.png)

Can you please let me know what should i do. I am in the middle of the project and i need to create more functions and storages, without losing any of the previous!

Thanks

**Comment by yuth** [comment]
@hammadxoho What was the version of Amplify CLI you had installed before the upgrade?

**Comment by hammadxoho** [comment]
@yuth, sorry, i am not sure.. i set it up on last October.  Currently its 1.1.7 
![PatientApp — -bash — 211×51 2019-03-21 12-25-22](https://user-images.githubusercontent.com/27281661/54738056-7172a700-4bd4-11e9-9afe-e4bc2978763c.png)

**Comment by hammadxoho** [comment]
@yuth can you please let me know what should i do regarding this.

**Comment by hammadxoho** [comment]
@haverchuck i am still stuck with this issue, can you guys please help me out. For a temp. time i think i would be editing the functions manually!

**Comment by struct78** [comment]
@hammadxoho I am getting this error too. It seems to be caused by the fact that I have multiple environments. If I update my sandbox environment at say 2:46pm, if my colleague tries to push their own environment changes at 2:48pm, they will get this message.

Even though my changes have no impact on my colleague's environment, if my colleague performs `amplify env pull` followed by `amplify push`, that seems to resolve it. 

Unfortunately this means we are all constantly playing a game of push pull ping pong.

Our CI pipeline now constantly fails because of this error, so we have to pull/push manually and re-trigger builds. Very frustrating.

**Comment by hammadxoho** [comment]
@struct78 sorry i don't get any notification on the update on the ticket, so did not know if you responded,
The difference is that i work alone on this.. 
i have still tried `amplify env pull` but i still get the same error

**Comment by yuth** [comment]
@hammadxoho we have made [some change](https://github.com/aws-amplify/amplify-cli/pull/1260) which should fix the reported issue. Could you try to update Amplify CLI `1.6.5` and see if this issue still persists?

**Comment by hammadxoho** [comment]
@yuth let me try that.
Yesterday i tried the manual migrations https://aws-amplify.github.io/docs/cli/migrate
and although it does give me issues still and does not update anything, but at least it has stopped detecting an older version of amplify cli! Let me try Ampliy CLI 1.6.5

**Comment by hammadxoho** [comment]
@yuth i have been able to update the functions now, after making manual migrations and then making some adjustments, and now it updates properly,
The issue i have right now is creating a new API endpoint, 
so to test it, i tried the following 
![PatientApp — -bash — 211×51 2019-05-02 17-54-31](https://user-images.githubusercontent.com/27281661/57076589-6f3b5680-6d03-11e9-8c85-86e5eba4f134.png)

it broke the JSON while creating and when i try to push, it only displays the Storage for creation, no Function or any update on the API.

After push, only the storage was created, After that i tried removing it and it again gave me an issue
![PatientApp — -bash — 211×51 2019-05-02 17-57-17](https://user-images.githubusercontent.com/27281661/57076734-c17c7780-6d03-11e9-8e7f-a434101fc9fb.png)

please let me know how can i resolve these?

**Comment by hammadxoho** [comment]
@yuth i figured the above out,, there was an issue with `amplify/backend-config.json` file, fixed it and now its all done,, Thank you for the help

**Comment by yuth** [comment]
@hammadxoho what was the issue with `amplify/backend-config.json`. Could you show the diff so we can have this documented

**Comment by hammadxoho** [comment]
@yuth, during migration, i accidentally removed the file, thus got a JSON error,
