### ISSUE TITLE
Hung up at / Uploading files... when performing Amplify push

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-cli#10685]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When pushing the schema using the command `amplify push`, the cli is hung at `- Uploading files...`

### Expected behavior

The cli should deploy the changes.

### Reproduction steps

Unfortunately I can not provide a reproducible example since I believe the issue might be specific to certain users only and not much debug info is provided by the cli.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by rezab777** [comment]
@ykethan 
Sure the environments I have tried so far are CMD, PowerShell and Git bash. 
Hitting return does not continue the process.

**Comment by rezab777** [comment]
I gave it a try in WSL and the issue isn't there. Seems to be specific to CMD, PowerShell and Git bash.

**Comment by ykethan** [comment]
Hey @rezab777 , glad to hear that you are up and running. Could please let us know if you are using Amplify CLI hooks in your application. https://docs.amplify.aws/cli/project/command-hooks/

**Comment by rezab777** [comment]
Hi @ykethan 
Not using any CLI hooks.

**Comment by ykethan** [comment]
Thank you for the information. When using the terminal inside Vscode such as CMD and powershell in my windows PC I was unable to replicate the issue. As a workaround using WSL seems to mitigate the issue. With that being said I will be closing the issue. Please feel free in reaching out to us, we would be happy in assisting you.
