### ISSUE TITLE
Cannot find module awscloudformation

### ISSUE THREAD

**Issue by EwanValentine** [aws-amplify/amplify-cli#1069]
**Describe the bug**
When I run:
```bash
 $ amplify push && amplify codegen
```

I get:
```bash
| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | wwmtg           | Update    | awscloudformation |
| Auth     | cognito08d97016 | No Change | awscloudformation |
? Are you sure you want to continue? true

Cannot find module 'awscloudformation'
✖ Downloading schema failed
missing path
```

I'm a little confused because this was working fine yesterday and I haven't really changed anything. So I'm not sure what change could have suddenly caused this.

**To Reproduce**
1. Run `$ amplify push && amplify codegen`

**Expected behavior**
I'd expect my changes to be reflected and pushed to AWS. Rather than an error.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Browser: Chrome
 - Version: `0.1.28` 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@EwanValentine You seem to be suing a very old version of the CLI (0.1.28), and we currently are on 1.5.0). Could you please use the latest version of the CLI and see if you're still seeing this behavior?
