### ISSUE TITLE
⚠️ The Amplify CLI can NOT find command:  video add

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#10734]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

9.1.0

### What operating system are you using?

11.6.6

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Running ```amplify video add``` results in ```⚠️ The Amplify CLI can NOT find command:  video add```

Running ```amplify``` only lists: ```where <category> is one of: notifications, api, auth, custom, storage, analytics, function, geo, hosting, interactions, predictions, xr```

### Expected behavior

A video resource should be added to the Amplify project
```video``` category should be present in category list

### Reproduction steps

1. Install amplify cli: ```npm install -g @aws-amplify/cli```
2. Install amplify-video plugin ```npm i amplify-category-video -g```
3. In an amplify project folder try: ```amplify video add```
4. run ```amplify``` in terminal -> video category is not listed

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I first tried to install the amplify-video plugin under node 16.x. It has issues on  install (security). I also tried 12.x (which later found out is to old for video plugin) - none of that worked either.

**Comment by josefaidt** [comment]
Hey @kjetilge :wave: can you verify the plugin was added to the CLI with `amplify plugin list`? If it is not in the list can you try manually adding it with `amplify plugin add` and re-try the command?

**Comment by kjetilge** [comment]
When running ```amplify plugin list``` I see all the expected plugin except ```video```.  If I try ```amplify plugin add amplify-category-video```, I get ```Can not locate the plugin package.
? Enter the absolute path for the root of the plugin directory:``` - I have no idea of where this root directory is located. Could you provide more details ?

**Comment by kjetilge** [comment]
I see now that others are having similar problems: [Can't add third-party NPM plugins since Amplify CLI v8.0.0](https://github.com/aws-amplify/amplify-cli/issues/10180)

**Comment by ykethan** [comment]
Hello @kjetilge, Thank you for reaching out. We can check the path for the plugin by running the following command.
`$(npm root -g)/amplify-category-video`
The plugin would be generally present under the npm node modules folder. 

Could you please copy the path from the output and add it to the plugin prompt. Please do let us know if this mitigates the issue.

**Comment by kjetilge** [comment]
Hm, still problems...
```
kjetilge@Kjetils-iPro UnicornFlix % $(npm root -g)
zsh: permission denied: /Users/kjetilge/.nvm/versions/node/v14.18.1/lib/node_modules
kjetilge@Kjetils-iPro UnicornFlix % amplify plugin add amplify-category-video
Can not locate the plugin package.
? Enter the absolute path for the root of the plugin directory: 
 /Users/kjetilge/.nvm/versions/node/v14.18.1/lib/node_modules
Failed to add the plugin package.
Error code: FailedVerification
Plugin verification error code: InvalidNodePackage
```

**Comment by ykethan** [comment]
Hello @kjetilge, glad to hear that you were able to mitigate the issue. The permission denied error on the command should not cause any issues with the plugin being added to amplify. I will be closing the issue, please do reach out to us again if are facing any issues with Amplify.
