### ISSUE TITLE
Unable to search AWSDateTime with @searchable

### ISSUE THREAD

**Issue by sadnub** [aws-amplify/amplify-cli#1075]
**Describe the bug**
I am using the @searchable on a model and have a AWSDateTime field. When I send a wildcard search with this field I get a UserIllegalArgumentException.

**To Reproduce**
Schema File
```
type SecurityEvent
  @model
  @searchable
{
  id: ID!
  securityEventCustomerId: ID!
  event_id: Int!
  entry_type: Int!
  source: String!
  time_written: AWSDateTime!
  computer: String!
  message: String
  login_type: Int
  new_security_id: String
  new_account_name: String
  new_account_domain: String
  new_login_id: String
  new_logon_guid: String
  workstation_name: String
  network_address: String
  source_port: Int 
  process_name: String
  additional_info: String
}
```
Relevant Generated Schema
```
input SearchableStringFilterInput {
  ne: String
  eq: String
  match: String
  matchPhrase: String
  matchPhrasePrefix: String
  multiMatch: String
  exists: Boolean
  wildcard: String
  regexp: String
}

input SearchableIDFilterInput {
  ne: ID
  eq: ID
  match: ID
  matchPhrase: ID
  matchPhrasePrefix: ID
  multiMatch: ID
  exists: Boolean
  wildcard: ID
  regexp: ID
}

input SearchableIntFilterInput {
  ne: Int
  gt: Int
  lt: Int
  gte: Int
  lte: Int
  eq: Int
  range: [Int]
}

input SearchableFloatFilterInput {
  ne: Float
  gt: Float
  lt: Float
  gte: Float
  lte: Float
  eq: Float
  range: [Float]
}

input SearchableBooleanFilterInput {
  eq: Boolean
  ne: Boolean
}

input SearchableSecurityEventFilterInput {
  id: SearchableIDFilterInput
  securityEventCustomerId: SearchableIDFilterInput
  event_id: SearchableIntFilterInput
  entry_type: SearchableIntFilterInput
  source: SearchableStringFilterInput
  time_written: SearchableStringFilterInput
  computer: SearchableStringFilterInput
  message: SearchableStringFilterInput
  login_type: SearchableIntFilterInput
  new_security_id: SearchableStringFilterInput
  new_account_name: SearchableStringFilterInput
  new_account_domain: SearchableStringFilterInput
  new_login_id: SearchableStringFilterInput
  new_logon_guid: SearchableStringFilterInput
  workstation_name: SearchableStringFilterInput
  network_address: SearchableStringFilterInput
  source_port: SearchableIntFilterInput
  process_name: SearchableStringFilterInput
  additional_info: SearchableStringFilterInput
  and: [SearchableSecurityEventFilterInput]
  or: [SearchableSecurityEventFilterInput]
  not: SearchableSecurityEventFilterInput
}

enum SearchableSortDirection {
  asc
  desc
}

enum SearchableSecurityEventSortableFields {
  id
  securityEventCustomerId
  event_id
  entry_type
  source
  time_written
  computer
  message
  login_type
  new_security_id
  new_account_name
  new_account_domain
  new_login_id
  new_logon_guid
  workstation_name
  network_address
  source_port
  process_name
  additional_info
}

input SearchableSecurityEventSortInput {
  field: SearchableSecurityEventSortableFields
  direction: SearchableSortDirection
}

type SearchableSecurityEventConnection {
  items: [SecurityEvent]
  nextToken: String
}
```

Searchable Query
```
//This is what my object looks like in JS and I am sending this in the filter argument
filter: {
  time_written: {wildcard: search+"*"}
  securityEventCustomerId: {eq: this.customer}
}

```
**Expected behavior**
It looks like it should treat the AWSDateTime property as a string based on the generated Schema. I can remove the time_written filter and it works. I can also OR other properties and it works.

**Screenshots**
Working
![image](https://user-images.githubusercontent.com/20450757/54689116-49604680-4af5-11e9-8c22-2bb27e650101.png)

Not Working
![image](https://user-images.githubusercontent.com/20450757/54688931-fab2ac80-4af4-11e9-9802-82f8e0361c51.png)

**Desktop (please complete the following information):**
 - Browser - Chrome

**Comment by mikeparisstuff** [comment]
The best way to work with dates in Elasticsearch is to use the Elasticsearch date type. This will require a few steps be taken on your behalf to update the mapping such that the fields are stored as dates. I comment on how to do this here https://github.com/aws-amplify/amplify-cli/issues/894. The API category does not yet have built in support for Elasticsearch date types but you can use custom resolvers to implement your own, tuned date queries in Elasticsearch. Read more on the date type here: https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html.

Another option is to start storing dates as integer epoch timestamps. This will allow you to use the gt/lt operators out of the box.

**Comment by sadnub** [comment]
Thanks @mikeparisstuff! That makes sense. If I wanted to store the date as epoch timestamps, would I need to store it as a TimeStamp Scalar? Or just use the Long type? I am referencing the Scalars listed [here](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html).

I currently just need to sort by the date of the record. Not the entire date and time.

**Comment by sadnub** [comment]
Just a heads up on this, I was able to to the match operation on the date and it works as expected.

```
//This is what my object looks like in JS and I am sending this in the filter argument
filter: {
  time_written: {match: this.date},
  securityEventCustomerId: {eq: this.customer}
}
```
Not sure why that is but it fulfills my use case.

**Comment by kaustavghosh06** [comment]
Feel free to re-open if you're still stuck on this.
