### ISSUE TITLE
BucketName construction does not work as intended if appname has a hyphen. Breaks BucketName uniqueness. 

### ISSUE THREAD

**Issue by PhilipWhiteside** [aws-amplify/amplify-cli#10756]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.5.0

### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

storage

### Amplify Commands

push

### Describe the bug

**Summary**

The S3 bucket name construction is not deterministic and can result in non-unique names, resulting in failed deployments. 

**Detail** 

The S3 bucket name is constructed from various elements within the CloudFormation template, snippet below. This aims to create a name with this pattern `<userSpecifiedName><stackName>-<envName>`.

However, if the project name contains a hyphen/dash `-` (E.g "demo-app") then this construction produces a different result and has this pattern `<userSpecifiedName><envName>-<envName>. With this pattern uniqueness is lost in the bucket name, so code is not sharable to other accounts (E.g. I had `demo-app-dev-dev` and my colleague deployed into their own account as `dev` resulting in the same name so the deployment failed. 

This happens because of the `Fn::Split` on `AWS::StackName` with `"-"` separator. 

**S3 bucket name construction template snippet**

```json
...
"Resources": {
    "S3Bucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            {
              "Ref": "bucketName"
            },
            {
              "Fn::Join": [
                "",
                [
                  {
                    "Ref": "bucketName"
                  },
                  {
                    "Fn::Select": [
                      3,
                      {
                        "Fn::Split": [
                          "-",
                          {
                            "Ref": "AWS::StackName"
                          }
                        ]
                      }
                    ]
                  },
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
...
```

### Expected behavior

The S3 bucket name to be created with uniqueness using deterministic parameters. 

### Reproduction steps

1. Create an app with a name that has a hyphen/dash (E.g. `my-app`).
2. Use `dev` as the env name
3. Add storage
4. Push app into account
5. Re-init the project as a new app (as if you had downloaded it from a GitHub project)
6. Use `dev` as the env name
7. Push app into account

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

d77ae78f60596ad3b37cd07c2d95d538

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

**Workaround**

- Rename the app to have no hyphen/dash `-`, specifically in the hidden file `amplify/.config/project-config.json
- Use a random env name such as `devsksksk`
- Rename the bucket `amplify/backend/storage/content/cli-inputs.json`

**Comment by josefaidt** [comment]
Hey @PhilipWhiteside :wave: thanks for raising this! I was not able to reproduce using a hyphen in the app name. Were you able to create this with the CLI?

```bash
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project my-app
>> Project name should be between 3 and 20 characters and alphanumeric
```

**Comment by PhilipWhiteside** [comment]
Hey @josefaidt you're correct I can't create a new project with the Amplify CLI with a hyphen. I don't know the exact path that got me there, perhaps as I started with a CDK backend and added the front end afterwards, merging the two. 

The construction is unpredictable, though not a high priority, it would make sense to define it once at the top stack and share down as a single value.
