### ISSUE TITLE
Publishing frontend code only very slow

### ISSUE THREAD

**Issue by lookitsatravis** [aws-amplify/amplify-cli#1076]
I've got a project I recently added hosting and a small React app to. When I run `amplify publish`, I see the table of resources and they all have an operation of "No Change" as expected. I am then prompted to continue, and I indicate "Yes", and then I see `⠼ Updating resources in the cloud. This may take a few minutes...` as normal. However, it can be 10 minutes or more before the local build command is run and the new React app is deployed. During that time, nothing seems to be happening. I looked briefly through the source and it seems to get into the CloudFormation resource pusher and just stays there for a while even though no resource changes are happening.

What I expect to happen:

I expect that since all resources have an operation of "No Change" that the CloudFormation provider would essentially complete immediately and the CLI would immediately build and deploy the React app.

**Comment by kaustavghosh06** [comment]
@lookitsatravis Which version of the CLI are you using?

**Comment by lookitsatravis** [comment]
Fair question. I thought I was on the latest version in this environment (1.1.7 as of now), but I was on 1.1.0. I updated and the problem is gone. Closing this. Thanks!
