### ISSUE TITLE
Python Lambda function no module found error

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#10786]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

When creating a lambda function and pushing it for the first time works perfectly. But on updating the pip file with a new package and pushing it cause a no module found error when executing the function.

Lambda layer does not work as well.

### Expected behavior

updating packages in Pip file should work

### Reproduction steps

Failing scenario

1. create a python function
2. push it using `amplify push` and test on console.
3. update pip file with following example
```
[dev-packages]
requests = "*"
```
add `import requests` to index.py
4. push the function and test it.
observe no module found error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Closing as discussed  @ykethan
