### ISSUE TITLE
Change the amplify push zip target.

### ISSUE THREAD

**Issue by longtt2705** [aws-amplify/amplify-cli#10783]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Amplify CLI Version**
9.1.0

**What AWS Services are you utilizing?**
AWS Lambda

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
My lambda is written in Typescript and need to be compiled and built before deploy. I have compiled and built the lambda using esbuild and compressed them into the `index.zip`. If I manually upload this file to lambda, it works well. But when I use `amplify push`, it will automatically zip all the .ts file in the /src into `latest-build.zip`, then deploy this file to the cloud.

My question is, how can I change the compress all the folder behavior of amplify push?

**Comment by josefaidt** [comment]
Hey @longtt2705 :wave: thanks for raising this! Unfortunately this workflow is not currently supported and every file under the function's `src/` directory will be included in the distribution zip archive. As a workaround, you can write your TypeScript files outside of this directory and change the esbuild output target to point to this `src/` directory

**Comment by josefaidt** [comment]
As an additional note, please refer to the following documentation page that describes this workflow in more detail https://docs.amplify.aws/cli/function/build-options/
