### ISSUE TITLE
S3 trigger event(suffix rule) does not work in the mock mode

### ISSUE THREAD

**Issue by laboone** [aws-amplify/amplify-cli#10798]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.6.19

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes.

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

When I uploaded a photo using `Storage.put()` in amplify mock mode, the amplify mock crashed with the following error.

```
2022-07-24T12:46:57.899Z - error: uncaughtException: The "path" argument must be of type string.
Received undefined date=Sun Jul 24 2022 21:46:57 GMT+0900, pid=69019, uid=501, gid=20,
cwd=/Users/laboone/personal/ts/albumie, execPath=/Users/laboone/.nvm/versions/node/v14.18.1/bin/node, version=v14.18.1,
argv=[/Users/laboone/.nvm/versions/node/v14.18.1/bin/node, /Users/laboone/.nvm/versions/node/v14.18.1/bin/amplify, mock],
rss=344952832, heapTotal=588693504, heapUsed=571384992, external=4658443, arrayBuffers=2309509, loadavg=[2.8115234375, 2.74169921875, 2.876953125],
uptime=1900344, trace=[column=7, file=internal/errors.js, function=new NodeError, line=322, method=null, native=false, column=11, file=internal/validators.js,
function=validateString, line=124, method=null, native=false, column=7, file=path.js, function=Object.join, line=1148, method=join, native=false, column=29,
file=/Users/laboone/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/utils/lambda/load-lambda-config.ts,
function=loadLambdaConfig, line=27, method=null, native=false, column=null, file=null, function=runMicrotasks, line=null, method=null, native=false, column=5,
file=internal/process/task_queues.js, function=processTicksAndRejections, line=95, method=null, native=false, column=22,
file=/Users/laboone/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/storage/storage.ts,
function=null, line=133, method=null, native=false],
stack=[TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined,
     at new NodeError (internal/errors.js:322:7),     at validateString (internal/validators.js:124:11),
     at Object.join (path.js:1148:7),
     at loadLambdaConfig (/Users/laboone/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/utils/lambda/load-lambda-config.ts:27:29),
     at runMicrotasks (<anonymous>),
     at processTicksAndRejections (internal/process/task_queues.js:95:5),
     at StorageServer.<anonymous> (/Users/laboone/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/storage/storage.ts:133:22)
]
```

As far as I investigate, the amplify mock mode does not support [AWS::S3::Bucket FilterRule](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration-config-filter-s3key-rules.html) properly.

I have the following cloudformation template.(amplify/backend/storage/hoge/build/cloudformation-template.json)

```json
:
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "suffix",
                      "Value": "albumie"
                    }
                  ]
                }
              },
              "Function": {
                "Ref": "functionS3Trigger51e7dea0Arn"
              }
            }
          ]
        }
:        
```

Name of FilterRule can be set to `prefix` or `suffix`.
But [the code](https://github.com/aws-amplify/amplify-cli/blob/87d15cb3e1c75fbd978c6fc7966e42b42e5d856a/packages/amplify-util-mock/src/storage/storage.ts#L122) checks only the prefix.
As a result, the value of `triggerName` becomes `undefined`, and the amplify mock mode crashes [in this method](https://github.com/aws-amplify/amplify-cli/blob/87d15cb3e1c75fbd978c6fc7966e42b42e5d856a/packages/amplify-util-mock/src/storage/storage.ts#L133).

To fix this problem, I made the following modification in my local environment.

```diff
diff --git a/packages/amplify-util-mock/src/storage/storage.ts b/packages/amplify-util-mock/src/storage/storage.ts
--- a/packages/amplify-util-mock/src/storage/storage.ts	(revision 87d15cb3e1c75fbd978c6fc7966e42b42e5d856a)
+++ b/packages/amplify-util-mock/src/storage/storage.ts	(revision 2d34beae82d3cc5ad3a737c18dcacd8db8cb0162)
@@ -118,8 +118,12 @@
             if (typeof rules.Value === 'string') {
               node = String(rules.Value);
             }
-            // check prefix given  is the prefix of keyname in the event object
-            if (keyName.indexOf(node) === 0) {
+
+            if (rules.Name === 'prefix' && keyName.startsWith(node)) {
+              triggerName = String(obj.Function.Ref).split('function')[1].split('Arn')[0];
+              break;
+            }
+            if (rules.Name === 'suffix' && keyName.endsWith(node)) {
               triggerName = String(obj.Function.Ref).split('function')[1].split('Arn')[0];
               break;
             }
@@ -130,6 +134,10 @@
         }
       }
 
+      if (triggerName === undefined) {
+        return;
+      }
+
       const config = await loadLambdaConfig(context, triggerName);
       const invoker = await getInvoker(context, { handler: config.handler, resourceName: triggerName, envVars: config.environment });
       try {

```

### Expected behavior

Lambda function is executed by S3 trigger event.

### Reproduction steps

Please see Describe the bug section.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by laboone** [comment]
I have made a PR.  https://github.com/aws-amplify/amplify-cli/pull/10799
I would appreciate it if you could review it:pray:

**Comment by josefaidt** [comment]
Closing due to PR merge 🎉
