### ISSUE TITLE
I want to use my own domain for cognito user hosted UI

### ISSUE THREAD

**Issue by AsitDixit** [aws-amplify/amplify-cli#10800]
During amplify add auth it is asking about about oAuth flow and client ID & secret and creating a domain like this "https://xxxxxxxx-dev.auth.us-east-1.amazoncognito.com/".
I deleted the above domain in my user pool and used my own domain name "auth.mydomain.com" with my issued certificate.

It is showing a massage that:
Before you can use this domain, you must add the alias target to your domain’s DNS record. If you’reusing Amazon Route 53 to manage your domain, you can do that from the Route 53 console.
Alias target  xxxxxxxxxxx.cloudfront.net

So  added the above to my DNS record as type: CNAME , name: alias, value:xxxxxxxxxxx.cloudfront.net
But it is not working:

When I am clicking on signup button(in my app) it is loading a custom tab with url:"https://xxxxxxxx-dev.auth.us-east-1.amazoncognito.com"
with error: "DNS_PROBE_FINISHED_NXDOMAIN"
When I am clicking on LunchHostedUI(in user pool app client section) it loading a site with my domain url but error:"auth.mydomain.com’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE"
I know I am missing something but I am unable to detect that.

**Comment by josefaidt** [comment]
Hey @AsitDixit :wave: thanks for raising this! Unfortunately we do not currently support custom domains for Cognito Hosted UI. Please subscribe to the following feature request for further updates and potential workarounds https://github.com/aws-amplify/amplify-cli/issues/1880

**Comment by AsitDixit** [comment]
@josefaidt How you said that but I am able to use that in my userpool
