### ISSUE TITLE
Adding lambda as event source to SQS queue fails due to lack of permissions while these permissions added with custom resource

### ISSUE THREAD

**Issue by alonsnir** [aws-amplify/amplify-cli#10805]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.16.0

### Amplify CLI Version

9.1.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth, custom, function, api

### Amplify Commands

push

### Describe the bug

Dependencies.

Here is the failing flow:

1. lambda add with the amplify add function
2. custom cdk script creating SQS
3. custom cdk script adding to the lambda's execution role an inline policy allowing to receive SQS messages
4. adding that lambda as an event source to the SQS
failure:
CREATE_FAILED      MyLambdaFuncSqsEventSourceFromPollybotsqsqueueCFD0C362 AWS::Lambda::EventSourceMapping  Resource handler returned message: "Invalid request provided: The provided execution role does not have permissions to call ReceiveMessage on SQS (Service: Lambda, Status Code: 400, Request ID: c92db418-2a1b-43ed-8c42-5d756c1a9bdb, Extended Request ID: null)" (RequestToken: cbe5a187-ee25-6b45-f138-34ac4fa27b91, HandlerErrorCode: InvalidRequest)

code:
```
pullRobotDataExecutionRole.attachInlinePolicy(
      new iam.Policy(this, 'pullRobotData_sqs_policies', {
        statements: [
          new iam.PolicyStatement(
            {
              actions: [
                'sqs:GetQueueUrl',
                'sqs:ListDeadLetterSourceQueues',
                'sqs:ReceiveMessage',
                'sqs:GetQueueAttributes',
                'sqs:ListQueueTags',
                'sqs:DeleteMessage'
              ],
              resources: [
                fromPollybotQueue.queueArn
              ],
            },
          )
        ]
      })
    );
const fromPollybotQueueEventSource = new SqsEventSource(fromPollybotQueue);
pullRobotDataFunc.addEventSource(fromPollybotQueueEventSource);
```
While debugging I have removed item 4 from the above "adding that lambda as an event source to the SQS" and ended up with lambda's execution role having all the required permissions, and now when rerun the entire script including add as event source all works fine. 

For me it indicates that the adding SQS as an event source to a function should be somehow dependent on inline policies attachment to be completed.

### Expected behavior

it should be a clear way to specify the order in which resources being created and thus resolve dependencies

### Reproduction steps

1. init amplify project
2. add function
3. add custom resource, use typescript
4. in that custom resource create SQS, give lambda permissions to receive sqs messages, add sqs as an event source to the lambda
5. amplify push will fail with ""Invalid request provided: The provided execution role does not have permissions to call ReceiveMessage on SQS"

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @alonsnir, Thank you for reaching out. A similar issue has been filed here https://github.com/aws-amplify/amplify-cli/issues/10332. Please feel free in subscribing to the issue and adding any information. 

In order to prevent any miscommunications between issues, I will be closing this issue.
