### ISSUE TITLE
How to allow guest access to a ExpressJS Lambda function on my custom domain?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#10814]
I've a SPA which runs on my custom domain. I have a rewrite rule setup to point everything to /index.html like so:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/1674590/181338720-b60597a5-bfc0-4df8-b81e-0414ac1f5d22.png">

Notice the webhooks negative check, this shouldn't match so should let it through.

I want to allow a 3rd party service to call a webhook on our site on my custom domain. My understanding is that added a new ExpressJS function and a REST API to my setup would allow this however I simply can't get it working.

I created my function and setup a route for it to reply to:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1674590/181340594-a3e7049a-55c5-4a6d-88c5-3475e8953dd5.png">

Then I added a REST API and pointed it to my function and allowed guest access. This seems to have worked as within the API in console I see that there is no auth required:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1674590/181340747-b7ff170b-8c82-4790-a9d6-514707873ea6.png">

I've disabled the default endpoint to try to force it to use my custom domain and redeployed but now when trying to hit the url via a POST in Postman I'm getting the following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>MethodNotAllowed</Code>
    <Message>The specified method is not allowed against this resource.</Message>
    <Method>POST</Method>
    <ResourceType>OBJECT</ResourceType>
    <RequestId>horridStringHere</RequestId>
    <HostId>somethingOrOtherHere</HostId>
</Error>
```

I can run the function locally using nodemon and have the 3rd party call it via a ngrok tunnel but once deployed I'm seemingly just left in the dark with error messages that don't help.

I've googled everything and now am just stuck.

**Which Category is your question related to?**

API.

**Amplify CLI Version**

9.10

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: thanks for raising this! Can you clarify this point?

> I've disabled the default endpoint to try to force it to use my custom domain and redeployed but now when trying to hit the url via a POST in Postman I'm getting the following error:

Have you setup a rewrite rule to route all requests to `/api/*` (for example) to your API Gateway?

**Comment by PeteDuncanson** [comment]
Hey Josef!

There was an option to "disable default endpoint" on the Api itself which I tried (read about it in a blog post somewhere and thought it worth a go). Apparently it can be unhappy if you hit it via the horrid auto generated url. 

I don't have a rewrite rule for the api (what would be /webhooks/ I assume?) should I?

**Comment by josefaidt** [comment]
Hey @PeteDuncanson thanks for clarifying! Is it this setting? 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5033303/181517388-6937c5ac-86d6-4e87-aa3f-fa3ad434d47a.png">

after disabling this did you redeploy the API Gateway instance?

<img width="543" alt="image" src="https://user-images.githubusercontent.com/5033303/181517558-ba150298-e8a2-4c33-9045-a930eda159de.png">

> I don't have a rewrite rule for the api (what would be /webhooks/ I assume?) should I?

Not necessarily! I was just curious if this was the approach you were taking 🙂 I've set this up before to where all requests to `/api` on my SPA hosted with Amplify Hosting point to the API Gateway default URL. 

> Apparently it can be unhappy if you hit it via the horrid auto generated url.

What issue were you having calling the API? it appears to not have any restrictions set and should be public

**Comment by PeteDuncanson** [comment]
Ok so we made some more progress on this today.

Following this doc (point 4. was the "helpful" one) https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-api-migration.html we switched the "endpoint configuration" from edge to regional and that seem to reset something and now POSTs are going through just fine on the default domain name (I re-enabled that this morning too) you know the horrid long one.

Still would like it to be accessible from my custom domain but my SPA and rewrite rules seem to be getting in the way. I'll try a new rule with your pattern but mashed to my naming, something like: `/webhooks/*` to redirect to the horrid generated url, sound about right?

**Comment by josefaidt** [comment]
Hey @PeteDuncanson glad to hear it!

>  I'll try a new rule with your pattern but mashed to my naming, something like: /webhooks/* to redirect to the horrid generated url, sound about right?

Yes, that is correct. Here is the rule I used as shown in Amplify Hosting's "rewrites and redirects" page

| Source address | Target address | Type | Country code |
|--|--|--|--|
| `/api/<PATH>` | `https://xxxxxx.execute-api.us-east-1.amazonaws.com/main/<PATH>` | 200 (Rewrite) | - |

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: just wanted to follow-up on this issue and see if the proposed rewrite rule worked for you?
