### ISSUE TITLE
Recover existing website after running `amplify init`

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-cli#10827]
**Which Specific Feature is your question related to?**
Amplify CLI?

**Provide additional details e.g. code snippets**
I was trying to perform an `amplify push` and seeing `File at path: '/workspace/joshmk/amplify/cli.json' does not exist` on an existing project. I tried `amplify configure` and `amplify pull` to solve the issue but with no luck. I then ran `amplify init` and now nothing is showing up when I visit the URL. Also, when I check dynamoDB, AppSync and S3, I'm no longer seeing the data for the website. The one thing I do see is past deployments in Amplify Studio.

The CLI didn't warn me about this being a destructive action if run on an existing website so I'm guessing the data can be retrieved? The site contained 2.5 years of my wife's blogging data and it's also where she sells her art, so I'm really hoping that all didn't get erased by me accidentally running the wrong CLI command.

I would love some help to recover her data. Thank you!

**Comment by jknapp25** [comment]
@cwoolum thank you!

**Comment by josefaidt** [comment]
Hey @jknapp25 :wave: thanks for raising this! The root cause is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/10686, however I'm curious about the current situation. Did the CLI create a second application with the same name (but different app ID's)?

**Comment by jknapp25** [comment]
@josefaidt I did see an additional app appear yes. I have deleted it since then though.

**Comment by jknapp25** [comment]
I had the sites set up in a wonky way, here's a bit of background...

I originally created the site for myself as a portfolio/blog kind of thing, but then my wife wanted one. A couple years ago I was unfamiliar with AWS so I mistakenly set up her site as the production of my site which was the staging one.

Essentially the same app in the console.

My site (staging) remains, but all of the services and data for hers are now gone. But I still see it listed in "Hosting environments" and "Backend Environments".

**Comment by jknapp25** [comment]
Ideally, I could restore her website but as a separate app

**Comment by josefaidt** [comment]
Hey @jknapp25 thanks for the clarification! 

> all of the services and data for hers are now gone. But I still see it listed in "Hosting environments" and "Backend Environments".

do you see the resources tied to the backend in the Console? If you visit the CloudFormation console do you also see the associated stack (appended with the environment name)?

**Comment by josefaidt** [comment]
@jknapp25 do the DynamoDB tables still exist? Something along the lines of `Page-ihkgrzbjvnd7vkt2eembqlvpje-main`?

**Comment by josefaidt** [comment]
> Clicking, "View in Cloudformation", does take me to a stack for her environment, but under "Resources" it is missing the API, Auth and Storage that my site is.

Is there an older copy of the site (+ `amplify` directory) in the parent directory?

**Comment by jknapp25** [comment]
> @jknapp25 do the DynamoDB tables still exist? Something along the lines of `Page-ihkgrzbjvnd7vkt2eembqlvpje-main`?

no

**Comment by josefaidt** [comment]
Hey @jknapp25 would you mind sending me the project identifier output of `amplify diagnose --send-report`?

**Comment by jknapp25** [comment]
@josefaidt here you go: b10711e9aad73c1ba5e1932bbe32cd93

**Comment by jknapp25** [comment]
The is the identifier after running the command on the branch that my website is based on. Now that I think about it, you're probably looking for the identifier if I run that on the branch her site was based on. Is that correct?

**Comment by josefaidt** [comment]
Hey @jknapp25 yes, that would be helpful, and thank you for sending that over! Are you currently deploying updates with Amplify Hosting's Git-connected CI/CD workflow, or also with the CLI (with `amplify push`)? From the original push error, is your project in a directory other than `/workspace/joshmk`? What was the push error received prior to being prompted for sending the diagnose report?

Overall so far nothing stands out to me as being destructive, and the CLI won't let you create an env with the same name (in the event it was overridden or deleted & recreated).

**Comment by jknapp25** [comment]
Here is the identifier on her branch: `b10711e9aad73c1ba5e1932bbe32cd93`

I was deploying using both. I thought it was required to deploy backend changes via the CLI and frontend changes via git. I didn't know that both will be picked up if just deployed with git. Is that how it works now?

**Comment by jknapp25** [comment]
The project is in `/workspace/joshmk`.

Yeah I think you are correct about the site beind overwritten or deleted.

**Comment by josefaidt** [comment]
Hey @jknapp25 

> I was deploying using git and the CLI.

Ah, is it possible the `backend` folder was removed during the series of `pull` and `init` executions? When we run `pull` the CLI will pull down a copy to a `.temp` directory. Is there a point in time where this directory was not cleaned up or accidentally pushed to git without `amplify/backend`? This would make sense as to how the resources were removed, and once those resources are recreated you should be able to restore from the backups

**Comment by josefaidt** [comment]
or sorry, an `amplify-backup` directory 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/5033303/182941228-70e2b2e2-29d0-4266-a35f-0405cbeed562.png">

**Comment by jknapp25** [comment]
Ah @josefaidt  I did delete the `amplify-backup` folder. I believe that was because I saw that suggestion in a forum.

**Comment by jknapp25** [comment]
@josefaidt is there anything that I can do to retrieve the backup if I had deleted the `amplify-backup` folder?

**Comment by josefaidt** [comment]
Hey @jknapp25 you will be able to reinstantiate the backend resources from the previous state of the backend in git, however these files capture the infrastructure-as-code and not the data that was stored in those resources. However, given you have a few table backups once these resources are restored you should be able to restore the backups.

**Comment by jknapp25** [comment]
@josefaidt good news! I was able to restore her primary table of blog posts. I'm so glad the backup worked! Thank you for your help mate. I will close this thread.
