### ISSUE TITLE
Lambda layers not working/linking as expected

### ISSUE THREAD

**Issue by masterprompt** [aws-amplify/amplify-cli#10842]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.1

### Amplify CLI Version

9.2.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Amplify Categories

function

### Amplify Commands

add, update

### Describe the bug

When attempting to add/update a lambda function using the cli to use lambda layers (selecting an existing layer created using the cli), the lambda's do not include any layers when deployed/pushed

This is the `function-parameters.json`:

```
{
  "lambdaLayers": []
}
```

Upon inspecting the lambda function in the lambda console it is observed there are no layers in the layers section.  When testing the function the function will error not finding the shared layer libraries.

### Expected behavior

Since I'm new to this, I Assume there should be some lambda layers defined in the `function-parameters.json` file.    I followed [this document](https://aws.amazon.com/blogs/mobile/how-to-use-lambda-layers-with-the-amplify-cli/) to the letter

### Reproduction steps

Follow document [here](https://aws.amazon.com/blogs/mobile/how-to-use-lambda-layers-with-the-amplify-cli/)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

[report-1659589251643.zip](https://github.com/aws-amplify/amplify-cli/files/9256745/report-1659589251643.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

none

**Comment by ykethan** [comment]
Hey @masterprompt, thank you for reaching out. I observed the blog post provided follows a deprecated work flow. Please refer to the following Amplify documentation that provided the updated information.
https://docs.amplify.aws/cli/function/layers/
https://docs.amplify.aws/cli/function/

To confirm, are you running the `amplify update function` command then selecting `Lambda layers configuration` ?
(Note: Just to be sure, we need to use the spacebar when selecting layers during the `Provide existing layers or select layers in this project to access from this function` step)

**Comment by masterprompt** [comment]
@ykethan 
The space key was the trick (and finding the most recent documentation)!  Thank you so much!  I feel like an idiot that I didn't see the space key (enter to skip).  Me thinks that using enter (call to action) to skip such an important step might be against the existing user experience patterns.  Thank you again!
