### ISSUE TITLE
amplify add geo & amplify push results in Parameters: [unauthRoleName] must have values

### ISSUE THREAD

**Issue by evan1715** [aws-amplify/amplify-cli#10866]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

This printed and reported as the issue when amplify push is executed.

CREATE_FAILED geomcMap0 AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:05 GMT-0400 (Eastern Daylight Time) Parameters: [unauthRoleName] must have values

### Expected behavior

For it to successfully push the map it created.

### Reproduction steps

1. amplify add geo
2. go through the steps it gives to create it
3. amplify push

### Project Identifier

Project Identifier: f91a401d15bfd02bf8f2e07537b8790d

### Log output

<details>

```
# Put your logs below this line
? Are you sure you want to continue? Yes
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-amplify38d0cfd81f5b4-staging-192631 AWS::CloudFormation::Stack Tue Aug 09 2022 18:21:57 GMT-0400 (Eastern Daylight Time) User Initiated
\ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS UnauthRole AWS::IAM::Role Tue Aug 09 2022 18:22:03 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS AuthRole   AWS::IAM::Role Tue Aug 09 2022 18:22:03 GMT-0400 (Eastern Daylight Time)
\ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          DeploymentBucket                            AWS::S3::Bucket            Tue Aug 09 2022 18:22:03 GMT-0400 (Eastern Daylight Time)
CREATE_IN_PROGRESS          geomcMap0                                   AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:03 GMT-0400 (Eastern Daylight Time)
CREATE_FAILED               geomcMap0                                   AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:05 GMT-0400 (Eastern Daylight Time) Parameters: [unauthRoleName] must have values
UPDATE_FAILED               AuthRole                                    AWS::IAM::Role             Tue Aug 09 2022 18:22:05 GMT-0400 (Eastern Daylight Time) Resource update cancelled
UPDATE_FAILED               DeploymentBucket                            AWS::S3::Bucket            Tue Aug 09 2022 18:22:05 GMT-0400 (Eastern Daylight Time) Resource update cancelled
UPDATE_FAILED               UnauthRole                                  AWS::IAM::Role             Tue Aug 09 2022 18:22:05 GMT-0400 (Eastern Daylight Time) Resource update cancelled
UPDATE_ROLLBACK_IN_PROGRESS amplify-amplify38d0cfd81f5b4-staging-192631 AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:06 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [geomcMap0]. The following resource(s) failed to update: [AuthRole, DeploymentBucket, UnauthRole].
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Tue Aug 09 2022 18:22:10 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Tue Aug 09 2022 18:22:10 GMT-0400 (Eastern Daylight Time)
UPDATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Tue Aug 09 2022 18:22:10 GMT-0400 (Eastern Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE UnauthRole AWS::IAM::Role Tue Aug 09 2022 18:22:27 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE AuthRole   AWS::IAM::Role Tue Aug 09 2022 18:22:27 GMT-0400 (Eastern Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                              DeploymentBucket                            AWS::S3::Bucket            Tue Aug 09 2022 18:22:31 GMT-0400 (Eastern Daylight Time) 
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-amplify38d0cfd81f5b4-staging-192631 AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:31 GMT-0400 (Eastern Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE geomcMap0 AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:33 GMT-0400 (Eastern Daylight Time) 
/ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-amplify38d0cfd81f5b4-staging-192631 AWS::CloudFormation::Stack Tue Aug 09 2022 18:22:33 GMT-0400 (Eastern Daylight Time) 
| Updating resources in the cloud. This may take a few minutes...

```

</details>

**Comment by josefaidt** [comment]
Hey @evan1715 :wave: thanks for raising this! I was not able to reproduce using the provided steps. When prompted, what were the settings chosen for the auth resource?

```console
aws-amplify/reproductions/10866 
➜  amplify add geo
? Select which capability you want to add: Map (visualize the geospatial data)
✔ geo category resources require auth (Amazon Cognito). Do you want to add auth now? (Y/n) · yes
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
✅ Successfully added auth resource 108664fb948fb locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

✔ Provide a name for the Map: · map4431ad1c
✔ Who can access this Map? · Authorized users only
Available advanced settings:
- Map style & Map data provider (default: Streets provided by Esri)

✔ Do you want to configure advanced settings? (y/N) · no
✅ Successfully added resource map4431ad1c locally.

✅ Next steps:
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud

aws-amplify/reproductions/10866 
➜  amplify push -y

# ... cloudformation output

✔ All resources are updated in the cloud
```

**Comment by josefaidt** [comment]
Hey @evan1715 thanks for clarifying. What settings were chosen when originally setting up auth?

**Comment by evan1715** [comment]
@josefaidt 
i don't recall the exact settings for auth setup. i may have done it through the website, separately making the cognito user pool and linking it through amplify in the website console.
is there a specific setting that would prevent this?

**Comment by ykethan** [comment]
Hey @evan1715, If the Cognito was created on the AWS console and was added to amplify CLI via the `import auth` command, this appears to be similar to https://github.com/aws-amplify/amplify-category-api/issues/677. I see a fix is currently in the works here: https://github.com/aws-amplify/amplify-cli/pull/10848

As a workaround I would suggest removing the Cognito Auth resource by running `amplify remove auth`. Then adding the resource using `amplify add auth` which enables amplify cli to create a Cognito resource with the default reference to the unauth role. We can then add the geo resource using the `amplify add geo` which should not throw any errors. Please refer to [documentation](https://docs.amplify.aws/cli/auth/overview/) for adding information on add auth. 

Hope this helps.

**Comment by evan1715** [comment]
that fix did not work for me. i ended up trying a lot of different things and the last thing i tried was
- amplify uninstall
- npm uninstall @aws/amplify-cli -g
- npm install @aws/amplify-cli -g
- amplify pull
- amplify add geo
- amplify push
and i believe that finally worked. used pre-made auth still.

**Comment by ykethan** [comment]
Hey @evan1715, Thank you for information. Glad to hear that you back up and running. For additional context and documentation purposes, I am curious in knowing if there have been any other changes prior to adding a the geo resource.

**Comment by evan1715** [comment]
@ykethan I wish I had written down everything I did, but I do not remember. I was trying to get it working probably for a total of 10 hours, so I tried a lot of varying things. I made a new repo, new amplify, etc and tried it through that means. Other than that, the last thing I tried to get it to work is the thing I said above.
It's still not working because I am getting a flood of bad requests in an infinite loop when I open the page that is supposed to have the map on it. This is even after I've added a lot of IAM permissions. Using the @.../react-ui package.
![image](https://user-images.githubusercontent.com/59775655/184549079-e552feab-5748-4faa-acf8-5f47f5977504.png)

**Comment by chrisbonifacio** [comment]
@evan1715 can you share the contents of your package.json and aws-exports files (redacted)? Also, curious to see how you're configuring Amplify in what seems to be a Next.js project. 

Lastly, please share any code snippets where you are calling `Amplify.configure` and how you might be using the `@aws-amplify/ui-react` library to set up authentication in your app (ex. Authenticator, useAuthenticator, etc).

**Comment by evan1715** [comment]
i see you've marked this as not-reproducible, however, i am not the only person with this. if you setup cognito and amplify all through the website/console, then apply it through an app, it does reproduce the same effect for me. trying to use the cli together with the console, it has almost zero compatibility with each other. try it again through those means.

package.json
<details>
{
    "name": "prototype",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
        "clearCache": "rm -rf node_modules && yarn cache clean && yarn install"
    },
    "dependencies": {
        "@aws-amplify/ui-react": "^3.3.0",
        "@aws-sdk/client-cognito-identity-provider": "^3.145.0",
        "@aws-sdk/client-dynamodb": "^3.145.0",
        "@aws-sdk/client-iot": "^3.145.0",
        "@aws-sdk/client-iot-data-plane": "^3.145.0",
        "@aws-sdk/client-iotanalytics": "^3.145.0",
        "@aws-sdk/client-s3": "^3.145.0",
        "amazon-cognito-identity-js": "^5.2.10",
        "aws-amplify": "^4.3.30",
        "bootstrap": "^5.2.0",
        "lodash": "^4.17.21",
        "moment": "^2.29.3",
        "moment-timezone": "^0.5.34",
        "next": "^12.2.4",
        "nodemailer": "^6.7.7",
        "react": "^18.2.0",
        "react-bootstrap": "^2.5.0",
        "react-dom": "^18.2.0",
        "react-redux": "^8.0.2",
        "recharts": "^2.1.10",
        "redux": "^4.2.0",
        "redux-thunk": "^2.4.1",
        "sass": "^1.54.3"
    },
    "devDependencies": {
        "chalk": "^4.1.2",
        "eslint": "^8.21.0",
        "eslint-config-next": "^12.2.4",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-promise": "^6.0.0",
        "eslint-plugin-react": "^7.30.1",
        "eslint-plugin-react-hooks": "^4.6.0",
        "prettier": "^2.7.1",
        "redux-logger": "^3.0.6"
    }
}
</details>

auto-generated aws-exports.js
<details>
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:50[.......]",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X[.......]",
    "aws_user_pools_web_client_id": "4[.......]",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "mcMap0-main": {
                        "style": "VectorEsriDarkGrayCanvas"
                    }
                },
                "default": "mcMap0-main"
            }
        }
    }
};

export default awsmobile;
</details>

Amplify.configure(the aws exports file) is how that's being called. it's in the app's root file, properly placed.

the map is being called how it's said in the documents of the /react-ui package:
const MapPage = () => <MapView />;
https://ui.docs.amplify.aws/react/connected-components/geo#mapview 

i have also tried to do it how the amplify docs say:
![image](https://user-images.githubusercontent.com/59775655/184672187-051fedab-2e71-45fa-89ac-15eab9aec31d.png)
https://docs.amplify.aws/lib/geo/maps/q/platform/js/#display-a-map 

both return the same issue/problem.

**Comment by ykethan** [comment]
Hey @evan1715, thank you for the information. To confirm are you utilizing the Authentication or the withAuthenticator component provided by amplify? if not could you please add the authentication component and let us know if the errors reappear. Please refer to https://ui.docs.amplify.aws/react/connected-components/authenticator#3-add-the-authenticator for additional information.

**Comment by evan1715** [comment]
yes, of course i am already using it.
![image](https://user-images.githubusercontent.com/59775655/184910157-9400ec83-53c6-4d5e-95d4-93e1ee5fcdb6.png)

**Comment by chrisbonifacio** [comment]
>if you setup cognito and amplify all through the website/console, then apply it through an app, it does reproduce the same effect
@evan1715 I'm sorry. I think we're getting a little confused with the reproduction steps here. Can you walk us through what you mean here? There are several ways to create a user pool resource in the browser such as via the Cognito console or Amplify Studio, etc. Did you use either of these?

How did you apply it to your app? via `amplify import auth`? If you used Studio, did you run `amplify pull --appId <your-app-id>`?

The error being about the unauthRoleName makes me think you might not have enabled unauthenticated users in your amplify app. Can you share the contents of your `team-provider-info.json` file?

**Comment by evan1715** [comment]
hey @chrisbonifacio , i can redo what i did and then give more thorough instructions. i'll write them all down step by step this time. however, due to a work timeline, i'll do that after i can get the geo online and functioning after the flood of bad requests is solved.

**Comment by ykethan** [comment]
hey, following up on this issue. Please do let us know if you require any assistance.

**Comment by evan1715** [comment]
i still have the same issue from this comment - https://github.com/aws-amplify/amplify-cli/issues/10866#issuecomment-1214423456

**Comment by evan1715** [comment]
i still have the same issue from this comment - https://github.com/aws-amplify/amplify-cli/issues/10866#issuecomment-1214423456
can't get it to work

**Comment by ykethan** [comment]
Hey @evan1715, For better tracking purposes and assistance would be open to creating the issue in the amplify JS repository as the issue is different from issue originally opened for.
Please refer to the following link: https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
