### ISSUE TITLE
Are git branch building and amplify push mutually exclusive?

### ISSUE THREAD

**Issue by isaiahtaylor** [aws-amplify/amplify-cli#10886]
**Which Category is your question related to?** Amplify

**Amplify CLI Version** 7.6.22

I've connected Amplify with my git repo and am having it build on new commits. Is this path mutually exclusive with using `amplify push`? I've had some bugs switching back and forth between these methods.

**Comment by isaiahtaylor** [comment]
Another aspect to this question: in the non-git build flow, when I run `amplify push`, it creates artifacts which I then commit. In the new flow, those artifacts do not get created because I'm just modifying the schema and pushing.

**Comment by josefaidt** [comment]
> I've connected Amplify with my git repo and am having it build on new commits. Is this path mutually exclusive with using amplify push? I've had some bugs switching back and forth between these methods.

:wave: this is relatively similar, where you must `amplify pull` to pull the latest backend state from your app's deployment bucket.

Closing due to age
