### ISSUE TITLE
Support for "access logging" enabled for s3 buckets

### ISSUE THREAD

**Issue by ncknuna** [aws-amplify/amplify-cli#1089]
**Is your feature request related to a problem? Please describe.**
While s3 bucket logging is not guaranteed to give us comprehensive audit logs, and we would be better served by the analytics module for analytics, if a security incident occurred, it would give us some additional traceability options.

**Describe the solution you'd like**
A CLI option to enable s3 bucket logging

**Describe alternatives you've considered**
Using the AWS CLI to call https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-logging.html . This is fine for now; I just wanted to put in the feature request since having it supported by Amplify by default would be slightly simpler

**Comment by svjacob** [comment]
+1 this would be nice.

**Comment by richAtreides** [comment]
Did this ever get implemented? I don't like having my config living in separate areas.

**Comment by wvidana** [comment]
anything?

**Comment by ykethan** [comment]
This has been address with the override functionality for storage category. Please refer https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-s3-resources.
