### ISSUE TITLE
ResourceNotReady: Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by Dhanesha-Dishit** [aws-amplify/amplify-cli#10901]
**Issue with 'amplify push', It crashes with the error 'ResourceNotReady: Resource is not in the state stackUpdateComplete'**

I am using multiple Amplify services in amplify backend like API, Auth, Function.I have 2 functions already in place in Amplify function, my amplify status is synced with the remote amplify then also if I am trying to update or create a function and pushing the same it crashes.

**Comment by ykethan** [comment]
Hey, thank you for reaching out. Would you be open to creating a issue on https://github.com/aws-amplify/amplify-cli/issues/new/choose and selecting `bug report`. Could you please provide us information on the cloudformation errors/ point of failures you are experiencing.
