### ISSUE TITLE
Support for more commands in headless mode?

### ISSUE THREAD

**Issue by ncknuna** [aws-amplify/amplify-cli#1090]
**Is your feature request related to a problem? Please describe.**
We have standardized settings that we use across all of our web application deployments, and we'd like to avoid an engineer accidentally mistyping one of those settings as they set up a new project.

**Describe the solution you'd like**
Allow all commands to be run headless, so they can be called from automated scripts

**Describe alternatives you've considered**
I've written a janky module which uses child_process.spawn to feed responses into the CLI. It works okay?

I think this is a more general version of #852

**Comment by kaustavghosh06** [comment]
@ncknuna We already support headless mode for majority of our deployment commands.
Please take a look at this for reference - https://aws-amplify.github.io/docs/cli/init#headless-usage-of-the-cli

**Comment by ncknuna** [comment]
@kaustavghosh06 I understand that most of the deployment-related commands (the ones that would be useful in a CI/CD scenario) are supported (thanks! I'm using them and they work great!). I'm talking about commands like `amplify add hosting`, which I would still like to automate, since, for example, we have a specific format for the buckets that we want all of our applications to follow

**Comment by et304383** [comment]
I second the desire that ALL commands be headless.  Consistency is key here.

**Comment by shqear-mawdoo3** [comment]
+1 to support all deployments commands
I can't create a CI/CD yet because of this command `amplify hosting add`

**Comment by sw-yx** [comment]
(not a fix) for reference the link that Kaustav linked to above has now moved to https://docs.amplify.aws/cli/usage/headless

**Comment by tfmorris** [comment]
@ncknuna Any chance you could share your script that uses `child_process.spawn`?
