### ISSUE TITLE
Amplify appending to bucket name

### ISSUE THREAD

**Issue by gmarshall56** [aws-amplify/amplify-cli#10927]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install aws-amplify

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth, storage

### Amplify Commands

add

### Describe the bug

Bucket name is changed vs what was entered via the "amplify add storage" prompts.

Ex: I entered bucket name "sar-import-bucket";  what was created was "sar-import-bucket14558-dev.", and this is the bucket that Amplify Store uses when Storage.put executes.

I see this in the src/aws-exports.js file in my VSCode project:
![image](https://user-images.githubusercontent.com/5943189/186229118-2604f0b2-fca2-4fab-96e0-a3c69d2808a3.png)

### Expected behavior

Expected the bucket name entered in the prompts to be used by Amplify Store.

### Reproduction steps

1.  When prompted by "amplify add storage", add your bucket name ( the name of an already existing bucket)
2. Finish the rest of the "amplify add storage" prompts

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

50ecbf0bc4838bab03027cff769f4468

### Log output

<details>

```
# Put your logs below this line

```

</details>

### Additional information

  Referring back to     [this issue](https://github.com/aws-amplify/amplify-cli/issues/4746), it appears that there is no way to change the name of a bucket stated in Amplify. But also, why did Amplify append the numbers and "-dev" to my bucket name?  Doing so requires that I then go back to my other progam code that reads these buckets, which require the bucket names to be exact.

Thank you

**Comment by ykethan** [comment]
Hello @gmarshall56, thank you for reaching out. This is currently the expected behaviour. Adding the UUID and env names allows the users to create a environment that is unique mitigating `bucket already exists` failures. adding the environment names allows users creating multiple environments to differentiate the buckets based on the environment name of the bucket. 

>( the name of an already existing bucket)
I noticed the comment here, are you looking to use an existing bucket? 
If yes, Amplify allows users to import an existing bucket as a storage resource. Please refer to https://docs.amplify.aws/cli/storage/import/#import-an-existing-s3-bucket for additional information.

**Comment by gmarshall56** [comment]
@ykethan 

> I noticed the comment here, are you looking to use an existing bucket?
If yes, Amplify allows users to import an existing bucket as a storage resource. Please refer to....

Thank you for your response.  It appears that you can specify your own already existing bucket when first running "amplify import storage", which is what I had done.  However, once this is command has completed, you can't run it again in order to change the bucket amplify storage is targeting.  Attempting to run "amplify import storage" again returns:

![image](https://user-images.githubusercontent.com/5943189/186670445-f9cc7288-8135-414c-953d-d512915b5533.png)

...and you are returned back to the system prompt.

So, referring to [this issue](https://github.com/aws-amplify/amplify-cli/issues/4746), you cannot change a Amplify storage bucket once it has been set using the "amplify import storage" cli?

**Comment by ykethan** [comment]
hello @gmarshall56, currently Amplify projects are limited to exactly one S3 bucket. if you would like to change the imported S3 bucket used we can use `amplify remove storage` this will unlink the imported resource without deleting it. we can then use `amplify add storage` to select a different bucket. 
As you may be aware there is currently a RFC open for this, please refer to https://github.com/aws-amplify/amplify-cli/issues/3977

**Comment by ykethan** [comment]
hey @gmarshall56, just following up on this.

**Comment by gmarshall56** [comment]
@ykethan Hi.  Haven't tried to remove / add storage yet.  Been walking through several you tubers posting great videos on Amplify.  I like it.  So far it works better than Vercel.  You can close this issue if you want.  Of course if I run into something I will open another issue. 

Thank you.

**Comment by ykethan** [comment]
hey @gmarshall56, glad to hear your interest in Amplify. please do reach out if you are experiencing any issues. 
closing the issue.
