### ISSUE TITLE
Amplify Cognito Redirect URL without Trailing Slash

### ISSUE THREAD

**Issue by rschre** [aws-amplify/amplify-cli#10937]
### Is this feature request related to a new or existing Amplify category?

auth

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

I'm trying to integrate Grafana with my amplify project and cognito auth.
When adding OAuth to my amplify auth the cli says "The value must be a valid URI with a trailing forward slash. HTTPS must be used instead of HTTP unless you are using localhost." 
When I add the URL as https://grafana-url/login/generic_oauth/ as required, the integration with grafana doesn't work. When I manually edit the URL in the console to https://grafana-url/login/generic_oauth the authentication works. 
I would like to be able to add the URL through the CLI instead of having to update it manually after every push.

### Describe the solution you'd like

Maybe a warning which says I'm adding a URL without trailing slash or something, but some way to add a URL without a trailing slash.

### Describe alternatives you've considered

Tried to find the possibility to change it in grafana.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @rschre, Thank you for reaching out. This appears to be similar to a feature request currently open, please refer to https://github.com/aws-amplify/amplify-cli/issues/7359. Please feel free in adding your concerns to the issue. To prevent any miscommunication between issues I will be closing the issue.
