### ISSUE TITLE
VSCode is not picking up the link for configuring PRODUCTION-READY authorization rules

### ISSUE THREAD

**Issue by M-Cooke99** [aws-amplify/amplify-cli#10938]
**Page**: [`https://docs.amplify.aws/cli/graphql/authorization/`](https://docs.amplify.aws/cli/graphql/authorization/)

**Feedback**: I was given this warning when setting up a new datastore API

WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an AP
I Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization
-rules

The link needs to be changed as VScode is not picking up the -rules on the end of the link (probably due to the carriage return)

**Comment by josefaidt** [comment]
Hey @M-Cooke99 :wave: thanks for raising this! To better understand the context of the issue what version of the CLI are you currently using? 

```console
aws-amplify/reproductions/10938 
➜  ay api gql-compile

⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules
```

**Comment by josefaidt** [comment]
Are you referring to the VSCode integrated terminal not picking up the `-rules` due to the link wrapping lines (when we `cmd+click` the link)?
