### ISSUE TITLE
Problems with resource access within lambda

### ISSUE THREAD

**Issue by AriDeve** [aws-amplify/amplify-cli#10949]
**Which Category is your question related to?**
Functions and auth

**Amplify CLI Version**
9.2.1

**What AWS Services are you utilizing?**
In this instance it would be lambda functions and cognito

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Getting the following error when trying to add a user from a lambda function, yet the lambda function has the permissions for cognito: function is not authorized to perform: cognito-idp:AdminCreateUser on resource: user-pool-ID because no identity-based policy allows the cognito-idp:AdminCreateUser action

The resource access permissions were given within cli, but I still cannot seem to access cognito from said function. Am I doing something wrong, missing something, etc?

It had worked this way before, before I recreated my cognito user pool and re-did the cli steps.

**Comment by ykethan** [comment]
Hello @AriDeve, thank you for reaching out. I was able to reproduce the error message when did not add any resource polices to the Lambda function. 

I utilized the following steps to mitigate the issue.
1. Created the python lambda function  and utilized the `client.admin_create_user` API call. 
2. Then in the functions `custom-policies.json` I added the following

```
[
  {
    "Action": ["cognito-idp:AdminCreateUser"],
    "Resource": ["*"] //modify this to your user pool
  }
]
```
3. `amplify push`

I was able to invoke the function on the aws console and received the following output.

```
{
    "ResponseMetadata": {
        "HTTPHeaders": {
            "connection": "keep-alive",
            "content-length": "277",
            "content-type": "application/x-amz-json-1.1",
            "date": "Wed, 31 Aug 2022 16:06:17 GMT",
            "x-amzn-requestid": "abcksadasd"
        },
        "HTTPStatusCode": 200,
        "RequestId": "dadasdad",
        "RetryAttempts": 0
    },
    "User": {
        "Attributes": [
            {
                "Name": "sub",
                "Value": "abcjdkdkld"
            },
            {
                "Name": "email",
                "Value": "accdd"
            }
        ],
        "Enabled": true,
        "UserCreateDate": "2022-08-31 16:06:17.193000+00:00",
        "UserLastModifiedDate": "2022-08-31 16:06:17.193000+00:00",
        "UserStatus": "FORCE_CHANGE_PASSWORD",
        "Username": "sai1"
    }
}
```

**Comment by ykethan** [comment]
hey @AriDeve, following up on this. Please do let us know if you require any assistance.

**Comment by AriDeve** [comment]
@ykethan My sincere apologies, I thought I had responded already, but apparently had forgotten to.. Unfortunately due to this issue, I had to put the project away for a short time, and work on a different one for the time being, and I haven't had the chance to switch back, and test the workaround yet.

**Comment by ykethan** [comment]
hey @AriDeve, I understand. To prevent the issue from going stale, I will be closing the issue for now. If you are facing any issues with the workaround do reach out to us we would be glad in assisting you.
