### ISSUE TITLE
update two model with single mutation function

### ISSUE THREAD

**Issue by uchar** [aws-amplify/amplify-cli#1096]
**Which Category is your question related to?**
Amplify api resolvers 

**What AWS Services are you utilizing?**
Amplify, GraphQL,DynamoDb

**Provide additional details e.g. code snippets**
I have following models:

```
 type Service @model {
     id: ID!
     reviewsCount: Int!
     reviews : [ServiceReview] @connection(name: "ServiceReviewsCon")
 }
   
 type ServiceReview @model{
     id: ID!
     comment:String!
     service:Service  @connection(name: "ServiceReviewsCon")
 }
```

How can I increase `reviewsCount` whenever I create a new `ServiceReview`? 

I think writing resolver in this case is not going to work because what I need is changing two tables at once.. am I right ?! If not can you point me in the right direction for solving it?

**Comment by mikeparisstuff** [comment]
This is not supported out of the box but you can write a pipeline resolver to implement this. You may also call a lambda function from an AppSync mutation and have that lambda function implement the logic.

**Comment by uchar** [comment]
@mikeparisstuff  I think amplify does not support pipeline resolver yet . Am I right ?
 With lambda solution, should I do both insert and  update in the lambda ? Is it possible to insert data using default query and just update other table with lambda? ( Currently, I have lambda with my logic and I'm trying to edit the `Stack `part of amplify's GraphQL. but I can't find out how to do it  )
Unfortunately, I'm very lost here, shouldn't this kind of tasks be much more easier ?

**Comment by mikeparisstuff** [comment]
@uchar You can use custom stacks to implement pipeline resolvers within Amplify. These docs discuss adding a custom resolver (https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model) and you can follow a similar pattern but replace it with a pipeline resolver.
