### ISSUE TITLE
The lambda triggers for dynamodb stream, cannot access (get or update) the dynamodb tables?

### ISSUE THREAD

**Issue by nxia416** [aws-amplify/amplify-cli#10967]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Functions

**Amplify CLI Version**

9.1.0

**What AWS Services are you utilizing?**

dynamodb and lambda

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Used `amplify add function` to add a lambda trigger for dynamodb. However, when I use this lambda function to access the dynamoDB tables, it feels like the thread is killed silently without any errors or logs.

here is my code
![image](https://user-images.githubusercontent.com/1368781/188305459-60df89a9-64f9-456c-b94b-85e82c712f6d.png)

here is my logs
![image](https://user-images.githubusercontent.com/1368781/188305787-e8c73873-3c77-4cc8-81af-786ffb4bb1f7.png)

The original logic here is: when someone added a record (an outside user) to the table, I used the dynamodb stream to trigger a lambda function. The triggered lambda function will crawl some new attributes, and then try to update the same record. I get stuck at the updating. 

Any help? My guess is, that maybe the lambda triggered by dynamodb cannot update the tables again? So I need to lambda trigger to add events to a SQS, and use another lambda to update the dynamo tables.

**Comment by nxia416** [comment]
I think there is something wrong with the lambda trigger. I tried to call another lambda from the trigger, I got the same result (nothing printed after call `await lambda.invoke(params).promise()`). To verify, I create a new lambda to call the same callee,   it works fine. 

So the dynamodb stream lambda trigger cannot access other tables or other functions? Why is that? I do add the access permissions from the CLI.

**Comment by ykethan** [comment]
hey @nxia416, thank you for reaching. I noticed that this issue is similar to https://github.com/aws-amplify/amplify-cli/issues/10969. could you please try the suggestion provided on the comment https://github.com/aws-amplify/amplify-cli/issues/10969#issuecomment-1238134070. 

Closing this to prevent any miscommunication.
