### ISSUE TITLE
Resolver to batch update multiple tables with a connection

### ISSUE THREAD

**Issue by laurachevalier4** [aws-amplify/amplify-cli#1097]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
API (custom resolvers)

** What AWS Services are you utilizing? **
AppSync, DynamoDB

** Provide additional details e.g. code snippets **
I am trying to write a resolver that will allow me to create a Resource with multiple Detail objects in one update. Relevant schema:
```
type Resource @model {
  id: ID!
  name: String!
  details: [Detail] @connection(name: "ResourceDetails")
}

type Detail @model {
  id: ID!
  name: String!
  resource: Resource @connection(name: "ResourceDetails")
  displayName: String!
  value: String!
}
```

Related autogenerated schema in AppSync:
```
input CreateDetailInput {
	id: ID
	name: String!
	displayName: String!
	value: String!
	detailResourceId: ID
}
input CreateResourceInput {
	id: ID
	name: String!
	details: [CreateDetailInput]
}
type Detail {
	id: ID!
	name: String!
	resource: Resource
	displayName: String!
	value: String!
}
type ModelDetailConnection {
	items: [Detail]
	nextToken: String
}
type Mutation {
	createResource(input: CreateResourceInput!): Resource
}
type Resource {
	id: ID!
	name: String!
	details(
		filter: ModelDetailFilterInput,
		sortDirection: ModelSortDirection,
		limit: Int,
		nextToken: String
	): ModelDetailConnection
}
```

My custom resolver is:
```
$util.qr($context.args.input.put("createdAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("updatedAt", $util.time.nowISO8601()))
#set($resourceData = [])
#set($resource = {})
$util.qr($resource.put("id", $util.defaultIfNullOrBlank($ctx.args.input.id, $util.autoId())))
$util.qr($resource.put("name", $ctx.args.input.name))
$util.qr($resource.put("details.items", $ctx.args.input.details))
$util.qr($resourceData.add($util.dynamodb.toMapValues($resource)))

#set($detailsdata = [])
#foreach($item in ${ctx.args.input.details})
    $util.qr($detailsdata.add($util.dynamodb.toMapValues($item)))
#end

{
    "version" : "2018-05-29",
    "operation" : "BatchPutItem",
    "tables" : {
    	"Resource": $utils.toJson($resourcedata),
        "Detail": $utils.toJson($detailsdata)
    }
}
```
(I have also tried replacing the table names with their full name from the DynamoDB console, and only adding `id` and `name` to my `resource` object, or adding `details` to `resource` without nesting it within `items`) . 

In the AppSync console for my app, I run:
```
mutation CreateResource {
  createResource(input: {id: "1234", name: "Newest Resource 1", , details: [{id: "4321", name: "somename", displayName: "displayname", value: "somevalue"}]}) {
    id
    name
    details {
      items {
        id
        name
        displayName
        value
      }
      nextToken
    }
  }
}
```

and get the response:
```
{
  "data": {
    "createResource": null
  },
  "errors": [
    {
      "path": [
        "createResource"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 4,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Items list for table Resource can't be null for path $[tables]"
    }
  ]
}
```
The following JS snippet gives the same error response:
```
let resourceObject = {
        id: resourceId,
        name: resource.name,
        details: resource.details.map((detail, index) => {
          return {
            id: uuid(),
            name: detail.detailName.split(" ").join("-").toLowerCase(),
            displayName: detail.detailName,
            value: detail.detailValue,
            detailResourceId: resourceId,
          }
        })
      }
      await API.graphql(graphqlOperation(mutations.createResource, { input: resourceObject }));
```

Given that I get the same error response no with the full or abbreviated table name, I wonder whether it even has to do with my resource object. What would be the correct way to write a resolver to make this sort of update? Documentation for resolvers that deal with batch put operations and connections between tables is sparse. Any help is appreciated!

**Comment by mikeparisstuff** [comment]
1. The table names in a BatchPutItem resolver do need to be the full names as seen in the DynamoDB console.
2. The BatchPutItem resolver returns a different shape than the PutItem resolver. The error you are getting is because the value returned by the response mapping template does not match the shape of your schema. You will need to write a response mapping template that pulls the value you are trying to return (in this case it looks like you want to return a Resource object). If you are only updating a single resource then you can probably return the first element in the results list for that table. E.G. use a response mapping template of `$util.toJson($ctx.result.data.Resource.get(0))`

**Comment by laurachevalier4** [comment]
Thanks Mike! Those are useful points, but I don't think they cover everything. I tried your suggestion and still saw the same error. However, you alluded to an important difference between BatchPutItem and PutItem: in addition to different expected return types, they seem to require different input types (BatchPutItem expects a list). Some progress after I changed the mutation definition to from `createResource(input: CreateResourceInput!): Resource` to `createResource(input: [CreateResourceInput]!): Resource`. Instead of error 
```
"Items list for table 'Resource-...-dev' can't be empty at path $[tables]"
```
I get error
```
"Items list for table 'Detail-...-dev' can't be empty at path $[tables]"
```

Removing the `Detail` table from the tables list removes the error entirely but then I'm not actually putting new Details objects. I tried following the example [here](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html) by creating a mutation that would update both tables and then return a custom object with `resources` and `details` lists, and then simply having `$utils.toJson($ctx.result.data)` in the response mapping template, but this gave a similar error to the above. 

Any thoughts on how I can get around these errors to create Details objects with every Resource I create, in one BatchPutItem mutation?

**Comment by laurachevalier4** [comment]
To work around this, I deleted the API and re-created with Detail as a nested type instead of its own model. Would still be great to know how to accomplish the above, but removing the connection and making `Detail` a regular type instead of a model did the trick for now!

**Comment by mikeparisstuff** [comment]
@laurachevalier4 Glad you got this working. The `BatchPut` resolver is a bit tricky to get right since it requires 1) using table names in resolvers, 2) configure the IAM policy attached to the data source to access multiple tables and 3) working with lists in mutations instead of single objects. We have a backlog item to support batch resolvers in the future. See #704 and #1060.

**Comment by nathanqueija** [comment]
Hello! What is the process if I want to have custom resolvers for `PutItem`, but I have different environments on Amplify? I'd like the custom resolver to work in every environment, but since the table name is hardcoded in the resolvers it only works in one environment.
