### ISSUE TITLE
` amplify diagnose --send-report` fails to send zip on windows

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#10980]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

v10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Tried the new way to send debug data to you but it seems to report that it failed to send the Zip so I don't get a Project Identifier to add to issues.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/1674590/188878069-3d6f5ad2-4f49-4884-b410-f78b8d46eca8.png">

### Expected behavior

Zip sends and it displays my Project Identifier or it reports why it can't so I can fix it.

### Reproduction steps

Simply ran ` amplify diagnose --send-report`  in the root of my application within a Windows Terminal run as admin.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
hey @PeteDuncanson, thank you for reaching out. I tested the flow in my windows PC by created a new folder named `Franchise-Manager` and then initialized a new amplify app. I tried using the CMD and powershell with both admin and without admin privileges but was unable to replicate the issue by running the `amplify diagnose --send-report` command.

could you provide us the logs after running the `amplify diagnose --send-report` command on your terminal? the logs for amplify can found at `C:\Users\<username>\.amplify\logs`. 
could you also confirm the windows version and terminal being used(example: CMD, powershell)

**Comment by PeteDuncanson** [comment]
Hey @ykethan,

I'm using Windows Terminal (https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=gb) run under admin rights.

Log today is pretty sparse though after re-running it just now:

```
2022-09-08T09:14:37.883Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2022-09-08T09:14:37.953Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
```

Let me know if there is anything else I can do/share with you to help work this one out. Up for a screenshare if needed.

**Comment by ykethan** [comment]
Hey @PeteDuncanson, thank you for the information. I tested this in a windows terminal(environment: windows 11) but was unable to replicate the issue. 

![image](https://user-images.githubusercontent.com/87995712/189144126-77759594-6763-47a8-bccb-c24451c5da7f.png)
![image](https://user-images.githubusercontent.com/87995712/189144192-1c904581-718c-404f-86d2-21bedcac3e1f.png)

Additionally, windows now allows users to add different terminals in one window.
![image](https://user-images.githubusercontent.com/87995712/189144021-c2482a9c-c73b-4836-b2da-39445fc01d7a.png)

Could you test the command in a different terminal such as powershell or command prompt? 
Additionally, I wanted to confirm if this occurs in a specific project. For a quick test could you create a sample amplify application in a new directory and run `amplify diagnose --send-report`

**Comment by PeteDuncanson** [comment]
@ykethan ive not created a new amplify project in over a year. Is there a cheat sheet somewhere or a quick how to for spinning one up for testing like this?

**Comment by ykethan** [comment]
Hey @PeteDuncanson, I would glad in assisting you. 

1. change the directory to a new folder different from your present Amplify project folder.  
2. run `amplify init`
3. run `amplify diagnose --send-report`

**Comment by PeteDuncanson** [comment]
@ykethan thanks for that :)

As suspected, it worked as it should!

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1674590/189159071-97f95edd-f0a6-47eb-88eb-d9b786c83897.png">

So what to try next? Personally I'm not all that bothered about it being broken but the developer in me doesn't like that its broken and not reporting why.

**Comment by ykethan** [comment]
Hey @PeteDuncanson, thank you for your patience. On testing multiple scenarios in my Amplify application, I was able to replicate the diagnose failure by removing the `backend-config.json`  and then run the diagnose command. But the diagnose command does throw an error providing information on the missing file.

![image](https://user-images.githubusercontent.com/87995712/189725209-764cd5c0-454b-4e77-bd24-870f055cf4db.png)

For a quick test, could you copy the amplify folder to a different directory.  Then delete the amplify folder and pull the backend using the `amplify pull` command. Could you then run the diagnose command to test if there may be any failures. 
If the command does not fail, we could check the difference between the amplify folders and check for missing files or attributes.

**Comment by ykethan** [comment]
hey @PeteDuncanson, following up on this. Please do let us know if you require any assistance.

**Comment by ykethan** [comment]
closing the issue due to inactivity
