### ISSUE TITLE
amplify publish stopped working after updating access and secret keys

### ISSUE THREAD

**Issue by silveriordza** [aws-amplify/amplify-cli#10998]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

My amplify had configured an access and secret key which is an admin user, in order to make changes to my AWS environments. I needed to recycle that access id and secret key in IAM since the secret key was exposed on a meeting somebody see them, hence I went to IAM using the AWS Console, created new access and secret keys then removed the old access and secret key.  

### Amplify Categories

function, api, hosting

### Amplify Commands

add, configure, env, status

### Describe the bug

Amplify CLI stops working as expected when the ACCESS ID and SECRET KEY of the user setup using the amplify configure, is changed manually in AWS IAM using the AWS Console.  After changing the access and secret keys, I ran "amplify configure" to update the new keys, followed the steps and provided the new access and secret keys and the command seemed to be successful, but then "amplify status" stopped showing the environments list,  amplify publish stopped working, couldn't do an "amplify pull" finished with errors.  Amplify status show this error: The security token included in the request is invalid.

### Expected behavior

Amplify CLI should correctly update the access and secret keys when changing existent keys using "amplify configure"

### Reproduction steps

1. Do amplify init, then amplify configure using some existent IAM admin user access and secret keys.
2. The project is code made in REACT and NodeJS in backend server. 
3. The NodeJS backend functions are contained in Lambda Functions created with amplify function.
4. The Lambda Functions are mapped to API paths.
5. In my project I have already multiple functions and paths that were fully tested and functional, deployed with AMPLIFY ENV ADD, AND AMPLIFY PUBLISH.
6. Add several environments, I do have 2 for DEV and 2 for PROD, same code for all with minor variations in DEV 2 compared to PROD.  Each DEV and PROD env is mapped to its own GIT BRANCH. I'm using GIT, but is not linked to automatically deploy code at check-in, I'm only using amplify to deploy code manually using amplify cli, not GIT. Git only to manage the code checkins, merging locally and remote branches repos. 
7. Go to IAM Console and for the user configured with "amplify configure", add new access and secret keys and remove the original ones. 
8. Run amplify configure to update the new access and secret keys. 
9. Run amplify status:  shows an error "The security token included in the request is invalid."
10. I tried to do amplify publish, it didn't work. Try to destroy the environment, doesn't work either. 
11. Got to the C:\Users\<user>\.aws\credentials  file like I had 2 profiles, 1 DEFAULT and one named Kuarsis-Web-App-Profile:
[default]
aws_access_key_id=[NEW ACCESS ID]
aws_secret_access_key=[NEW SECRET KEY]

[kuarsis-web-app-profile]
aws_access_key_id=[OLD ACCESS ID]
aws_secret_access_key=[OLD SECRET KEY]

**12. I noted only the Default profile keys were updated to the new keys by "amplify configure" but not the kuarsis-web-app-profile, and somehow when I use the amplify status or any other amplify command, it was using the kuarsis-web-app-profile keys and not the default, reason why it was showing the Invalid Token error.** I manually updated the credentials for kuarsis-web-app-profile in the credentials file to the new keys and that seemed to solve the amplify status issue. 
13. This can be considered a new functionality or perhaps as a bug, and it took me a while to figure this one out: when we use the "amplify configure" to reset the access id and secret key, it should update the profile that all the amplify commands are using by default, in this case it was the kuarsis-web-app-profile and not the default profile, but amplify configure updates by default the default profile and not the kuarsis-web-app-profile, which causes confusion and make the amplify to stop working. Perhaps is also my inexperience since I'm new to amplify, but it will be easier for everybody if amplify configure had updated kuarsis-web-app-profile since the beginning since that is the profile used by default by all the amplify cli commands in my project.

Note:  Unfortunately I didn't find the solution of updating the credentials file manually on time, and I tried several things while troubleshooting like: upgraded amplify and nodejs to the latest version which didn't fix the issue, I uninstalled amplify and reinstalled it again, which created an even bigger issue, now most of my environments started having issues with all amplify commands, when I run amplify status it shows the error "Name: Error : Message: Corrupt file contents in S:\Kuarsis\webapps\kuarsis-web-app\amplify\.config\local-aws-info.json" attached in the screenshot, then it cycles (frozen) there forever in the "FETCHING AWS AMPLIFY CONSOLE" step.  

**Is the uninstaller from amplify NPM removing the files in here "C:\Users\<user>\.amplify\awscloudformation"?** If yes, it shouldn't do that, uninstalling and reinstalling should be seamless to the user without affecting project code or losing important environment configurations. 

**To recover from this,** I added again the files into the awscloudformation subfolder, matching the filenames mentioned in local-aws-info.json for each environment, and then added the correct Access Id and Secret Key for each, after that, all my amplify commands started working normally for all my environments.  Uninstalling amplify must not remove files in the .amplify/awscloudformation folder, perhaps those files should be moved to be part of the project configurations instead and not be part of the unistall of amplify that way if we reinstall, it should work again normally taking all the project configs as they were.

Let me know if you have any questions.

![amplify invalid token 1](https://user-images.githubusercontent.com/63380676/189500091-c009dc1a-01ed-4497-80f5-151ed1b7c5af.png)

### GraphQL schema(s)
![error2](https://user-images.githubusercontent.com/63380676/189501201-4ed7a105-bf62-42f3-84ff-90b14d23ed0a.png)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @silveriordza, Thank you for reaching out. wanted to confirm the following.

> Run amplify configure to update the new access and secret keys.

was the credentials updated for the project using `amplify project configure`. Additionally, to confirm if the project environment is using the correct aws profile, could you please check the `local-aws-info.json` file present in the config folder under the amplify folder. If the folder is not visible could you open the `.vscode` then the `settings.json` file and set `"amplify/.config": true,` to false. 

![image](https://user-images.githubusercontent.com/87995712/191039388-c3662c6e-0e55-45fa-85e3-29dab76a3931.png)
![image](https://user-images.githubusercontent.com/87995712/191039647-2e3f855b-33f6-4fba-9462-6af232bbd2a2.png)

**Comment by ykethan** [comment]
hey @silveriordza, following up on this. Please do let us know if you require any assistance.

**Comment by silveriordza** [comment]
Hi ykethan,  the answer to all your questions are in the description of this issue.  I know it is a large description but all you need is there.   As I mentioned in the description, I used "amplify configure" to update the access key settings but I made a mistake and used the wrong AWS Key and didn't realize it,  I tried to do an amplify push and it failed,  and after that it was all chaos. I realized later I used the wrong AWS Key, and tried updating with the correct key using "amplify configure" but it didn't work, the project was messed up.  On my attempts to fix it, I uninstalled amplify and then installed it again with "npm" commands,  that just made the problem worst, it seems the uninstall process deleted the files here: "C:\Users\<user>\.amplify\awscloudformation" which seems to contain important settings for AWS Access keys and other specific settings of my project, all were deleted,  I fixed it by creating the files "C:\Users<user>.amplify\awscloudformation" again manually, making the filenames (ids) to match what the "local-aws-info.json" was expecting. I also fixed manually the settings in the profile here "C:\Users\<user>\.aws\credentials"  to match the correct AWS Access key, and after that everything worked fine. 

I can't tell what is wrong here since I don't know the insights of the amplify code,  but it should not break if the user (in this case me) makes a mistake and uses the wrong AWS ACCESS key on the "amplify configure", then do an "amplify push" it shuld not break the whole project, and if I run again "amplify configure" with the correct ACCESS KEY (after realizing the original mistake) it should not break. I also if we uninstall amplify with "npm" commands,  maybe it should not delete the user settings in "C:\Users\<user>\.amplify\awscloudformation" otherwise when the user reinstalls amplify with "npm" his settings are gone and there is no way to make the project work again unless you have a clever idea to re-create the auto generated files in "C:\Users\<user>\.amplify\awscloudformation".

I hope this helps explaining the problem better.   I may try to give you more specific steps to reproduce, but it takes time to break my own project and recover it just to show you how the error happened, but I will try once I have a chance.

BY THE WAY: This is no longer an error for me, I fixed it following the steps I described in this issue, I no longer need suggestions to fix it, since I fixed it, I'm just logging this issue to amplify team so you are aware of the issue and perhaps you can reproduce it on your side and possible prevent this to happen to others in the future. 

Thanks,
Silver

**Comment by ykethan** [comment]
Hey @silveriordza, glad to hear that you are back up and running. From the information provided I was unable to reproduce the issue.

1. Created a application using amplify cli
2. added new resources (Ex: lambda function) and pushed.
3. uninstalled amplify using npm.
4. reinstalled amplify using npm.
5. ran amplify configure and changed the profile information to a different user.
6. added a new resource in the project and pushed.

Does the steps provided align to your use case?

**Comment by silveriordza** [comment]
Those were not the exactly the steps to reproduce. Instead of pushing is publish. And I not only has lambda, I also have API Gateway, a React client and around 4 different environments in AWS based on this setup. 
I will close issue for now to not affect any metrics on your side, but I will submit a new issue with more clear steps to reproduce once I have a chance.

Thanks!
Silver.

**Comment by silveriordza** [comment]
Those were not the exactly the steps to reproduce. Instead of pushing is publish. And I not only has lambda, I also have API Gateway, a React client and around 4 different environments in AWS based on this setup.
I will close issue for now to not affect any metrics on your side, but I will submit a new issue with more clear steps to reproduce once I have a chance.

Thanks!
Silver.

**Comment by manifiserv** [comment]
I changed the access and secret key in "local-aws-info.json" mentioned the stored token json path.
```
{
  "dev": {
    "configLevel": "project",
    "useProfile": false,
    "awsConfigFilePath": MyPath\\.amplify\\awscloudformation\\KEJa3TAipe"
  }
}
```

I changed the values in this path "awsConfigFilePath"

It's working..
Thanks,
