### ISSUE TITLE
Amplify generated graphql API , not propagating X-ray to DynamoDB

### ISSUE THREAD

**Issue by geoaxis** [aws-amplify/amplify-cli#10996]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.16.0

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have not done any changes other than to enable x-ray in overrides.ts file

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

I am unable to see X-ray traces that propagate to DynamoDB when Amplify creates AppSync and other resoueaces.

### Expected behavior

When I create a simple AppSync todo API I can see DynamoDB table in the X-ray and service map. I expect Amplify generated AppSync  to do the same.

### Reproduction steps

1- I can create a graphql API using AWS amplify. 
2- I have enabled cognito authentication and "owner" baed authorization.
3- Amplify creates underlying resources including DynamoDB table. 
4- I can poke the API through graphql (from webapp and from AppSync graphql client)
5- X-ray traces are enabled (using overrides.ts) and I can X-ray  being put. 
6- But I don't see any x-ray trace going to DynamoDB table. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

N/A

**Comment by ykethan** [comment]
Hey @geoaxis, following up on this. Please do let us know if you require any additional information or assistance.

**Comment by ykethan** [comment]
closing the issue due to inactivity. Please do reach out to us again we would be happy in assisting you.
