### ISSUE TITLE
Why does my AWS Amplify project creates ACLs on all the regions

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-cli#10993]
**Which Category is your question related to?**

Resources generated on my AWS Console

**Amplify CLI Version**

10.0.0

**What AWS Services are you utilizing?**

Cognito, AppSync, DynamoDB, S3, Lambda

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

Hello, I was looking at the different resources that gets created whenever using the AWS Amplify CLI and I saw that it creates a [VPC](https://aws.amazon.com/vpc/) practically on every region of my AWS account. I tried looking at different ones and it looks like almost all of them actually aren't synced/added to any resource, the only one that I could find was on my main region and it looks like it's being used by CloudWatch for a specific function.

Is there any specific reason why these VPCs / ACLs are created? I also checked on 2 different AWS Amplify project and found these on both.

Thanks in advance!

**Comment by josefaidt** [comment]
Hey @jerocosio :wave: thanks for raising this! Could this be the [default VPC](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html) for your AWS account?

**Comment by jerocosio** [comment]
Hey @josefaidt you're correct! Thank you so much for looking into this!
