### ISSUE TITLE
CLI should use the same .ini / config parser as the rest of AWS

### ISSUE THREAD

**Issue by awsluja** [aws-amplify/amplify-cli#11023]
### Is this feature request related to a new or existing Amplify category?

auth, storage, api, hosting

### Describe the feature you'd like to request

The Amplify CLI currently uses this parser for config & credential files: https://github.com/npm/ini
It should be using the shared ini parser provided by the AWS SDK: https://github.com/aws/aws-sdk-js/blob/master/lib/shared-ini/index.js

There are several open issues related to the differences between the Amplify CLI and other AWS tools using the shared config/credentials files.
#10525 
#2441
#1245

### Describe the solution you'd like

Migrate to using the ini parser that is used by the rest of the AWS JS ecosystem.

### Describe alternatives you've considered

There are other publicly available ini parsers but we should stick to the AWS ini parser.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by evcodes** [comment]
I have a fix in the works for this

**Comment by evcodes** [comment]
After further investigation, I have found that the ini parser on aws-sdk-js is not meant to be consumed. Furthermore, it does not have the same methods as the npm ini parser that we are currently using. So we cannot use this aws-sdk ini parser. Closing this issue for now.
