### ISSUE TITLE
'@aws-amplify/cli' 10.1.0 Breaks build

### ISSUE THREAD

**Issue by AustinAmoruso** [aws-amplify/amplify-cli#11030]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.1.0

### What operating system are you using?

Amplify build

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

Trying to make a build in the Amplify console fails with amplify cli 10.1.0

There was an error initializing your environment.
[31mFailed to pull the backend.[39m
🛑 Unable to parse aws-exports.js. Has this file been modified?
Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
!!! Build failed
!!! Non-Zero Exit Code detected

### Expected behavior

Build works

### Reproduction steps

Create a new build via a pull request and have the Amplify build system `amplifyPush --simple`

### Log output

There was an error initializing your environment.
[31mFailed to pull the backend.[39m
🛑 Unable to parse aws-exports.js. Has this file been modified?
Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
!!! Build failed
!!! Non-Zero Exit Code detected

**Comment by sobolk** [comment]
We're sorry about this inconvenience. We have pointed `latest` back to 10.0.0.

**Comment by ykethan** [comment]
hey @AustinAmoruso, in addition to @sobolk update. please do let us know if building the application in 10.0.0 mitigates the issue.

**Comment by AustinAmoruso** [comment]
I was able to deploy with 10.0.0

**Comment by ykethan** [comment]
hey @AustinAmoruso, thank you for the update. apologies for the inconvenience. I will be closing the issue, please do reach out to us if you are experiencing any issues.

**Comment by josefaidt** [comment]
Hey @AustinAmoruso and @mate2 :wave: to add on to @sobolk 's note above, would you mind sending us the App ID and region of your Amplify app?

**Comment by josefaidt** [comment]
Closing as issue has been fixed 🙂
