### ISSUE TITLE
How to programmatically pass profile to use for Amplify CLI

### ISSUE THREAD

**Issue by hikarunoryoma** [aws-amplify/amplify-cli#11036]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify Init

**Amplify CLI Version**
7.6.23

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
React App

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
using the amplify CLI I want to provide a similar experience for headless CI/CD as dev users.  Right now I have a dev environment that I would like to publish a react app to. When running the commands below:

```
export AWSCLOUDFORMATIONCONFIG="{\
    \"configLevel\":\"project\",\
    \"useProfile\":true,\
    \"profileName\":\"dev\",\
    \"region\":\"us-east-1\"\
    }"

amplify init --amplify "{\"envName\": \"dev"}" --providers="{\"awscloudformation\":${AWSCLOUDFORMATIONCONFIG}}"
```
I get the following error: 
```
Using default provider  awscloudformation
⠋ Initializing your environment: devFailed to get profile: Profile configuration is missing for: default
```

This is because locally on my machine I have already specified in the `local-aws-info.json` 

```
"dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  },
```

I would like to override this or at least pragmatically be able to set this in case I am running amplify init on a new machine and not have to manually accept the default values.  I assumed that the `awscloudformation` provider would reset this, but it appears that that is not the case.  What is the point of specifying this provider then if at all?  Is there a way that I can specify on init what dev environment config should be?  

Thanks in advance!

**Comment by ykethan** [comment]
Hello @hikarunoryoma, Thank you for reaching out. could you let us know how the amplify application was copied over to the new environment. was this by coping the front end project with amplify folder or via git clone?
the `local-aws-info.json` is currently git ignored. if the `local-aws-info.json` file was copied over as well when copying the front end project, I would suggest removing the `local-aws-info.json` file and the local-env-info.json. then retry the init command ensuring a aws profile exists in the new environment/machine.

**Comment by ykethan** [comment]
Hey @hikarunoryoma , following up on this issue. Do let us know if you require any assistance.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please feel free in reaching out to us again, we would be happy in assisting you.
