### ISSUE TITLE
After upgrade, Amplify version remains the same (10.0.0) even though upgrade seems successful

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#11048]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

sudo npm -g

### If applicable, what version of Node.js are you using?

v14.20.0

### Amplify CLI Version

10.2.0

### What operating system are you using?

Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

update

### Describe the bug

When I upgraded, yesterday from version 10.0.0 to version 10.1.0 the output of `amplify --version` remained 10.0.0 even though npm did not think another upgrade was necessary and it considered the Amplify CLI package fully upgraded after that first upgrade.

The same thing happened today - with the existing version of Amplify CLI (10.1.0) I upgraded via `sudo npm i -g amplify`

### Expected behavior

I expected `amplify --version` to output the correct version after upgrade. I expected it to be 10.1.0 after the upgrade from 10.0.0 yesterday. I expected it to be 10.2.0 after the upgrade today, but it remains 10.0.0.

### Reproduction steps

Just type `amplify --version` after fully upgrading your amplify packages to 10.2.0 and you'll see that it still says 10.0.0

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dorontal** [comment]
Okay, here's how I solve this issue, but something is still wrong:

1) I removed amplify via `npm remove -g @aws-amplify/cli`
2) Reinstalled Amplify via `npm install -g @aws-amplify/cli` -- it still said it was on version 10.0.0
3) Did `amplify --upgrade`

All is fine now...

**Comment by joekiller** [comment]
10.1.0 and 10.2.0 are dead ducks. so long live 10.0.0

![image](https://user-images.githubusercontent.com/1022919/191623887-1bea25bd-0903-416e-81b3-49c95c62e9ab.png)
![image](https://user-images.githubusercontent.com/1022919/191623920-304f54fb-d3c5-47ca-9afd-543139ccc132.png)
