### ISSUE TITLE
amplify pull deletes hooks folder locally

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#11050]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

created backend on console

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

amplify hooks folder gets deleted when running a headless amplify pull. With amplify CLI v10.0.0 the hooks will not be maintained by amplify CLI and needs to be maintained on the version control system such as git.

The situation occurs when we create a application locally then push to the cloud backend. Then allow create a new hosting branch that creates a new backend. performing a pull on the new backend will remove the existing hooks folder locally.

possible cause amplify-backup folder being created on a pull 

### Expected behavior

Expected to not delete exisiting hooks folder 

### Reproduction steps

1. amplify init
2. amplify push
3. git commit and push
4. connect git repository to hosting (instead of attaching to existing backend, allow hosting to create a new backend env)
5. when backend build run, copy the pull command and run it in your present amplify application.
6. observe the existing hooks folder disappears/ gets deleted

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by evcodes** [comment]
Closing this issue as the last PR fixes this bug
