### ISSUE TITLE
Lambda stops to support node.js 6.10 rumtime

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#1105]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, Lambda

** Provide additional details e.g. code snippets **
I received the notification in my AWS dashboard:

> Your AWS Account currently has one or more Lambda functions using the node.js 6.10 runtime. The Node Foundation has previously published that node.js 6.x "Boron" will be declared End-of-Life (EOL) on April 2019 [1], and will stop receiving bug fixes, security updates, or performance improvements. Per the AWS Lambda runtime support policy [2], language runtimes that have reached their EOL are deprecated in AWS Lambda.

> Invokes for functions configured to run on node.js 6.10 will continue to work normally, however the ability to create new Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30 2019

> We encourage you to update your node.js 6.10 functions to a newer version of the Node runtime (node.js 8.10) so that you continue to benefit from important security, performance, and functionality enhancements offered by more recent releases. The newer node.js 8.10 version has improved ECMAScript support, along with other language and API improvements. The AWS Lambda programming model [3] for node.js 8.10 maintains backwards compatibility with previous versions to simplify portability. We recommend that you test your Lambda function to validate its behavior on the newer version of Node.js.

In my Lambda dashboard there is a function that I care built by amplify-cli is using node.js runtime 6.10. Is the team aware of the node.js 6.10 "deprecation"?

**Comment by kaustavghosh06** [comment]
@YikSanChan We're aware of this situation and mitigating the issue my moving our custom resource node version to 8.10. I'll update this thread once we push the changes.

**Comment by sirshannon** [comment]
So... less than 2 working days left and still no fix for this? Seriously?
This should have been done a year ago. I feel like I’ve been had.

**Comment by sportyrider** [comment]
@sirshannon it is resolved. Update amp cli to the latest version and change lambda runtime to 8.10 in existing CF, if you have existing lambdas. I just did that couple days back and all worked fine.

**Comment by sirshannon** [comment]
Thanks. I wonder why this issue is still open and the promised update from @kaustavghosh06 hasn’t happened...

**Comment by sportyrider** [comment]
True. I was watching PR and it was merged 2 days ago. In any case, you should be good to go.

**Comment by kaustavghosh06** [comment]
We upgraded our default Cloudformation tempaltes to NodeJS 8.10 with the latest version of the CLI. Here's a quick migration guide out here if you're using an older version/template in your project - https://aws-amplify.github.io/docs/cli/lambda-node-version-update

**Comment by sankranti2018** [comment]
Is Amplify console using an older version of the cli by any chance? I am running into this issue when I build using amplify console. Manual deployment work fine. Here is the message in build log. 2019-06-09T14:19:54.301Z [WARNING]: Error updating cloudformation stack
2019-06-09T14:19:59.308Z [INFO]: Following resources failed
2019-06-09T14:19:59.310Z [INFO]: Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
                                 Event Type: create
                                 Reason: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 80901c73-8ac1-11e9-ae20-4d856eb2d917)
                                 init failed
