### ISSUE TITLE
How to add custom domain name for EU Frankfurt?

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1106]
** Which Category is your question related to? **
Hosting
** What AWS Services are you utilizing? **
S3, CloudFront
** Provide additional details e.g. code snippets **
I ran the commands: `amplify add hosting` and `amplify publish`. I'm now wondering, how can I add a custom domain? I can't use the AWS Amplify console, because the console is somehow not available for EU Frankfurt.

**Comment by yuth** [comment]
@janhesters You could use cname as described in the [cloudfront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html) configure your custom domain for hosting.

**Comment by janhesters** [comment]
@yuth Thank you! I will try that 🙏

**Comment by kaustavghosh06** [comment]
@janhesters Did this work for you?

**Comment by kaustavghosh06** [comment]
Pleas re-open or respond to this issue if you're still blocked.

**Comment by et304383** [comment]
Sorry to hijack this, but @yuth and @kaustavghosh06  are you saying the only way to add a custom domain is to manually edit the CloudFront distribution after amplify creates it?

**Comment by yuth** [comment]
@et304383 no. Way to add custom domain is to use [CNames](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html)

**Comment by et304383** [comment]
Uhh, which means manually editing after the fact.  Or edit the generated CFN template.

Amplify should have this built in.

**Comment by janhesters** [comment]
@et304383 Nader Dabit just published a great tutorial about this: https://twitter.com/dabit3/status/1117763069558444032

**Comment by et304383** [comment]
Yeah that's not the CLI nor is that easy.  And it requires having added your app to the amplify console.  If you're using just the CLI, this isn't really feasible.

**Comment by wmlutz** [comment]
I'd recommend at least putting a cleaned up instructions of what's in the cloudfront docs in the amplify framework docs. https://aws-amplify.github.io/docs/js/start

I also went hunting for how to take my amplify-hosted-webapp and put it on a custom domain. All I found was this issue tracker.

**Comment by wmlutz** [comment]
@janhesters - that is for Amplify Console, not Amplify Framework.
