### ISSUE TITLE
Can't add a new cognito custom attribute through auth override

### ISSUE THREAD

**Issue by devChedar** [aws-amplify/amplify-cli#11065]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.0

### What operating system are you using?

Ubuntu on WSL

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

override

### Describe the bug

I added an auth override which missed the carrying over existing attributes from `resources.userPool.schema`. I am trying to add them back later but it is giving me the following issue

🛑 The following resources failed to deploy:
Resource Name: UserPool (AWS::Cognito::UserPool)
Event Type: update
Reason: Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 3aa23190-c93f-4dcc-8c01-e40661b1190c; Proxy: null)

### Expected behavior

Auth should be updated with the existing attributes

### Reproduction steps

1. Use old version of amplify auth v1
2. Add a custom attribute `tenantid` through cloudformation template
3. Upgrade the auth to v2 
4. Use amplify auth override and add the following code
```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const customAttribute = {
    attributeDataType: 'String',
    developerOnlyAttribute: false,
    mutable: true,
    name: 'tenantid',
    required: false,
  }
// Mising the ...(resources.userPool.schema as any[]) part
  resources.userPool.schema = [
    customAttribute,
  ]
}
```
5. Amplify push
6. Update the override to include ` ...(resources.userPool.schema as any[])` 
7. Code 
```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const customAttribute = {
    attributeDataType: 'String',
    developerOnlyAttribute: false,
    mutable: true,
    name: 'tenantid',
    required: false,
  }
  resources.userPool.schema = [
    ...(resources.userPool.schema as any[]), // Carry over existing attributes (example: email)
    customAttribute,
  ]
}
```
8. amplify push 

You should see the error now

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
hey @devChedar, Thank you for reaching out. I was able to replicate the error from the steps provided. Could you let us know if the Cognito login experience without the carryover attributes works as expected?

**Comment by devChedar** [comment]
I can login but the `tenantid` that I added through override doesn't have the read or write property. 

![image](https://user-images.githubusercontent.com/72195741/192449138-4dc00107-27eb-47de-9c82-b032f61a05b8.png)

**Comment by ykethan** [comment]
hey @devChedar, Thank you for the information. Newly added custom attributes are not set as readable or writable attributes by default on the App Clients. We can set the App client attributes by using the following in the override.

```
import { AmplifyAuthCognitoStackTemplate } from "@aws-amplify/cli-extensibility-helper";

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const customAttribute = {
    attributeDataType: "String",
    developerOnlyAttribute: false,
    mutable: true,
    name: "tenantid",
    required: false,
  };

  resources.userPool.schema = [
    ...(resources.userPool.schema as any[]),
    customAttribute,
  ];

   resources.userPoolClient.readAttributes = [ //set readable attributes
      "email",
      "custom:tenantid",
    ];
}

```
 
output: 

before override on readable attributes

![image](https://user-images.githubusercontent.com/87995712/192576202-6dede873-32b9-40ae-8441-0918aa461fe2.png)

after override:

![image](https://user-images.githubusercontent.com/87995712/192576320-4175c10e-8ee6-4635-accc-cf82dbb552b8.png)

furthermore, I was able to get some additional information on the error `Invalid AttributeDataType input, consider using the provided AttributeDataType enum.`, when we add `...(resources.userPool.schema as any[]),` to carry over the attributes cloudformation detects these changes as schema change with adding a new attribute email(example) resulting in the error. 
we will be reporting this to the cloudformation team and investigating this. Thank you for reporting. 

as a mitigation step i would suggest not removing and readding the carry over. removing the carryover will not remove the required attribute(in this example email) in the console.

**Comment by ykethan** [comment]
Hey @devChedar, following up on this issues. We have updated the Cognito override documentation to align with observed behaviour. Thank you for reporting. Please feel free in reaching out to us again.
