### ISSUE TITLE
There are no files in amplify hosting bucket

### ISSUE THREAD

**Issue by stallev** [aws-amplify/amplify-cli#11078]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

260402007550

### Region

us-east-1

### Step

Domain activation

### Status

Failed (no any files in the hosting bucket)

### Issue or question

Hello!
I did 'amplify add hosting' and I have 'amplifytest-20220925204839-hostingbucket-dev' created to host my app. After that I did 'amplify publish' and the app built successfully. But there are no files in the hosting bucket of the application. I need to add and remove some files from this busket daily.
Could you explain why, I don't see these files and how to add this bucket to enviromen variables list?

I duplicated this email to aws-amplify-customer@amazon.com

Thank you in advance.

**Comment by josefaidt** [comment]
Hey @stallev :wave: unfortunately I was not able to reproduce this using the following Hosting settings:

```
✔ Select the plugin module to execute · Amazon CloudFront and S3
? Select the environment setup: DEV (S3 only with HTTP)
? hosting bucket name hostingtest-20220928105129-hostingbucket
? index doc for the website index.html
? error doc for the website index.html
```

> But there are no files in the hosting bucket of the application. I need to add and remove some files from this busket daily.

Can you confirm the distribution directory set in `amplify/.config/project-config.json` is populated with the appropriate files such as `index.html`?
