### ISSUE TITLE
Amplify does not generate .config and  #current-cloud-backend - Missing required key 'apiId' in params

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-cli#11075]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

I recently deleted an amplify project with "amplify delete". But when creating a new one, it doesn't generate ".config" and "#current-cloud-backend" directories. This results in a failure when I run "amplify codegen":

✖ Downloading schema failed
Missing required key 'apiId' in params

The reason I deleted the last project was because of a seemingly fatal error when attempting to run "amplify pull" and "amplify push". It would tell me that an error occurred and that I need to unlink amplify-meta. I couldn't find a solution for this, so I decided to delete my project. The reason for this error seems to be because my local and cloud schemas were out of sync.

### Expected behavior

amplify init generates .config and  #current-cloud-backend directories

### Reproduction steps

amplify init
amplify add api
amplify codegen (this is how you see the error)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

[report-1664340518526.zip](https://github.com/aws-amplify/amplify-cli/files/9661528/report-1664340518526.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information
I wonder if I've hit some limit? [This post](https://github.com/aws-amplify/amplify-cli/issues/4918) showcases the same error, except I was not able to solve by doing what they did. My problem also seems bigger because <project-root>/amplify/backend/amplify-meta.json does not even exist

_No response_

**Comment by josefaidt** [comment]
Hey @justinjaeger :wave: thanks for raising this! Can you confirm whether the editor-specific files (e.g. `.vscode/settings.json`) are hiding these directories? Also, we should receive a message when attempting to run `amplify codegen` before codegen is added, which is added on `amplify push` or manually with `amplify add codegen`

Was the project re-initialized in the same directory as the old project where some of these hidden, untracked files would have been present?

**Comment by justinjaeger** [comment]
Hi @josefaidt , thanks for the reply. I did find a settings.json file hidden in the .vscode folder. Deleting that helped generate the #current-cloud-backend directory, so that's good.

However, I'm still getting an error on "amplify codegen":
- Downloading schema failed: Missing required key 'apiId' in params

I also tried this command, but still got the same message:
amplify codegen --appId [MY_APP_ID] --envName dev

**Comment by josefaidt** [comment]
Hey @justinjaeger to clarify, the `.vscode/settings.json` file was hiding those directories. However, I am not able to reproduce this issue.

Can you confirm you have a `.graphqlconfig.yml` file created by `amplify add codegen`?

```yml
projects:
  '9071':
    schemaPath: amplify/backend/api/11075/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

Following the provided steps upon running `amplify codegen` we are prompted to first add codegen:

```
> amplify codegen
code generation is not configured. Configure it by running 
$amplify codegen add
```

**Comment by justinjaeger** [comment]
I removed my .graphqlconfig.yml file this time after resetting. This solved the problem. Thank you! So in the future if I ever do "amplify delete" again, I'll also manually delete the .graphqlconfig.yml and .vscode/settings.json files.

What also complicated it was that there was an error in my schema.graphql, which I discovered when running "amplify rebuild api" (not recommended unless you can afford to lose all your data)
