### ISSUE TITLE
amplify cli unable to delete cognito user pools if they have a custom domain

### ISSUE THREAD

**Issue by mfreeman451** [aws-amplify/amplify-cli#1107]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
Cannot use amplify delete to remove auth or project if the cognito user pool is associated with a custom domain

**To Reproduce**
1. Create a project with amplify that includes auth. 
2. Manually configure that cognito user pool to have a custom domain associated with it. 
3. If you do an amplify delete on that service or project, it will fail to delete the cognito user pool. 
4. Users must manually delete custom domain before using amplify delete

**Expected behavior**
Cognito user pool is able to be deleted from aws amplify regardless of custom domain association

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX latest
 - Browser Chrome
 - Version latest

**Comment by kaustavghosh06** [comment]
@mfreeman451 How did you add the custom domain?

**Comment by mfreeman451** [comment]
@kaustavghosh06 Using the AWS Amplify Console (web), is that enough information?

**Comment by mfreeman451** [comment]
@kaustavghosh06 AWS Console->Cognito-> select my user pool -> App Integration -> Domain Name -> Use your domain name -> select my route 53 managed domain name

**Comment by kaustavghosh06** [comment]
@mfreeman451 If you've added Domain using the Cognito console, you would first have to remove it from the console and then you would be able to successfully delete it from your Ampify project.

**Comment by kaustavghosh06** [comment]
@mfreeman451 With the latest version of our CLI we added Hosted UI support (with support for provisioning of your domain), which takes care of removing the domain before deleting the user-pool. Please feel free to check it out and re-open/comment on this issue if you're still seeing this issue.

**Comment by Scottyaim** [comment]
Hi @kaustavghosh06 can i specify my custom domain in the amplify cli setup for authentication or do i have to do it manually via the AWS Cognito Console?

I'm currently doing it manually would be great to know if you can do it via the cli to keep all the configuration in one place. Thanks in advance, Amplify rocks!
