### ISSUE TITLE
Migrate analytics and notifications projects created before v10.3.0

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-cli#11087]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.2.0

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

analytics, notifications

### Amplify Commands

add, push

### Describe the bug

Projects that have analytics/notifications resources created with Amplify CLI v10.2.0 do not allow adding new notifications channels due to difference in implementation after 10.3.0. This ticket is to allow the migration of existing projects in order to support adding/updating new notification channels

### Expected behavior

Existing projects that have analytics/notifications enabled should allow adding more notification channels after Amplify CLI upgrade

### Reproduction steps

1. create a project and add notifications (SMS - channel) with an amplify before 10.3.0
2. execute `amplify push` and then upgrade the Amplify CLI to version > 10.3.0
3. adding new channels, updating existing, pushing changes should run without errors

**Comment by Straubulous** [comment]
This functionality is released in Amplify CLI 10.4.0.
