### ISSUE TITLE
How to resolve GetAttGraphQLAPIApiId in CustomResources.json

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#1109]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **

** What AWS Services are you utilizing? **

Dynamo / Elastic search searvice / lambda / amplify

** Provide additional details e.g. code snippets **

I can not find a way to resolve` GetAttGraphQLAPIApiId` in `CustomResources.json`.
So I tried to copy `build/stacks/SearchableStack.json` and edit it to customize dynamo stream lambda. (related https://github.com/aws-amplify/amplify-cli/issues/1022) . However it is failed, because  It can not resolve `GetAttGraphQLAPIApiId`. What should I do resolve it ?

**Comment by kstro21** [comment]
How are you trying to resolve it? Can you show that specific piece of the template?

Note that if you are in the `CustomResources.json` template or any other template that you created in the `amplify\backend\api\myapiname\stacks\`, you can use

```
{
    "Ref": "AppSyncApiId"
},
```

Hope it helps

**Comment by bokuweb** [comment]
@kstro21 Thanks for your great support !!! 😄 It solved!!
