### ISSUE TITLE
generate-access-logs get more accurate time range

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-cli#11092]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Hosting feature

Logging

### Describe the bug

When I use cli to get access logs using the following command

```sh
aws amplify generate-access-logs --domain-name <name> --app-id <id> --start-time 2022-09-29T14:00:00Z --end-time 2022-09-29T14:30:00Z
```

It always returns me the log of the entire hour, instead of the 30 minutes. 

### Expected behavior

I'd like to have a more accurate logs so that I can find the issue easier.

### Reproduction steps

1. use cli to get the access logs

```sh
aws amplify generate-access-logs --domain-name <name> --app-id <id> --start-time 2022-09-29T14:00:00Z --end-time 2022-09-29T14:30:00Z
```

2. see the time range of the logs, it's the entire hour

**Comment by ykethan** [comment]
Hey @0618, Thank you for reaching. I would suggest opening a issue on the https://github.com/aws/aws-cli repository for better assistance as Amplify cli does not maintain the commands provides by aws-cli.
