### ISSUE TITLE
@auth Per Field

### ISSUE THREAD

**Issue by chrisco255** [aws-amplify/amplify-cli#111]
**Is your feature request related to a problem? Please describe.**
Right now the `@auth` transformer can be applied to the model, but some use cases come up where you want only certain users to be able to access specific fields on a Type.

**Describe the solution you'd like**
Would like to be able to use the `@auth` transform on a per field basis

**Describe alternatives you've considered**
None, other than be implementing custom resolvers.

**Additional context**
None.

**Comment by mikeparisstuff** [comment]
I think this is a good idea. Have you thought more about how you would like to see it implemented?

I see two main options:

1. Add arguments to `@auth`. Usage would look something like:

```graphql
type Post @model @auth(allow: owner, fields: ["a", "b", "c"]) { ... }
```

2. Allow @auth to be specified on fields. Something like:

```graphql
type User @model {
  ssn: String @auth(allow: owner)
}
```

Downsides of this approach are that you would have to define @auth per field that you want to protect. That being said you could always put @auth on the type with the most basic auth for all fields then fine tune using @auth on the field level.

Let me know what you think.

**Comment by chrisco255** [comment]
Hi @mikeparisstuff, thanks for your reply. I think I like #2 better. It is more declarative and explicit when looking at the schema from a top level. Agreed, you'd generally want the most basic auth at top level for the model and then fine-grained definitions on a per-field basis.

**Comment by timrchavez** [comment]
This would be absolutely amazing to have.

**Comment by itrestian** [comment]
We (the AWS AppSync team) are currently looking for feedback on a server side solution for supporting field level auth and would love community feedback on the following RFC:

https://github.com/aws/aws-appsync-community/issues/1

**Comment by tobiasfeil** [comment]
For anyone looking (On Google, I found this first instead of the actual docs and only found them two days later):

This is supported now: https://docs.amplify.aws/cli/graphql-transformer/directives#field-level-authorization
