### ISSUE TITLE
Amplify commands returning nothing in mac terminal

### ISSUE THREAD

**Issue by indiebloom** [aws-amplify/amplify-cli#11106]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.1

### Amplify CLI Version

just installed, but amplify commands aren't working so can't tell

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

configure, status

### Describe the bug

amplify commands are not returning anything at all in the Terminal. They don't throw an error or show any output. They just do nothing.

### Expected behavior

Configure and status should show a result.

### Reproduction steps

run amplify version, or amplify configure, or amplify status

Result: nothing happens

<img width="448" alt="Screen Shot 2022-10-04 at 11 31 35 AM" src="https://user-images.githubusercontent.com/113216355/193897968-c6d9750e-d040-4a69-b145-cbea42d46376.png">

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
Hi @indiebloom, did you install Amplify CLI globally? I'm not able to reproduce on mac.

I installed with: `npm i -g @aws-amplify/cli`

**Comment by indiebloom** [comment]
This is resolved by running with sudo. Why is that?

**Comment by jhockett** [comment]
I wouldn't recommend installing with `sudo` because the Amplify CLI does not require it. You may have a permissions issue on your system, possibly with how node and npm were installed, that is bypassed when running with elevated permissions.

**Comment by indiebloom** [comment]
@jhockett I did install globally, yes. I have tried using nvm to fix node and npm with `nvm install node`, but amplify still doesn't do anything without sudo
