### ISSUE TITLE
amplify video add outputs ERROR: "Cannot read property 'dev' of undefined while "Building video resources..."

### ISSUE THREAD

**Issue by CKalt** [aws-amplify/amplify-cli#11105]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.1

### Amplify CLI Version

10.2.1

### What operating system are you using?

Fedora

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No. Simply running tutorial from here.

https://aws.amazon.com/blogs/media/introducing-aws-amplify-video-on-demand/

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

Trying to run the steps described here: [Introducing Video On Demand](https://aws.amazon.com/blogs/media/introducing-aws-amplify-video-on-demand/)

This step:

$ amplify video add

Never completes, and an error message displays: 
Cannot read property 'dev' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'

### Expected behavior

amplify 
[report-1664904401330.zip](https://github.com/aws-amplify/amplify-cli/files/9709378/report-1664904401330.zip)
video add step Should complete with out errors.

### Reproduction steps
Following steps from the post listed above.

1. mkdir AmplifyProject
2. cd AmplifyProject
3. amplify init
4. amplify video add

Then, when prompted, respond as follows:
? Select from one of the below mentioned services: Video-On-Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: 
myvodservice
? Select a system-provided encoding template, specify an already-created template name:  Default HLS 
Adaptive Bitrate
? Do you want to get notifications on the video processing job? No
? Is this a production enviroment? No
? Do you want Amplify to create a new GraphQL API to manage your videos? (Beta) No

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

f21ed827e58baae3b9361b745d68c94a
[report-1664904401330.zip](https://github.com/aws-amplify/amplify-cli/files/9709374/report-1664904401330.zip)
[report-1664904401330.zip](https://github.com/aws-amplify/amplify-cli/files/9709376/report-1664904401330.zip)
[report-1664904401330.zip](https://github.com/aws-amplify/amplify-cli/files/9709385/report-1664904401330.zip)

### Log output

n/a

**Comment by josefaidt** [comment]
Hey @CKalt :wave: thanks for raising this! To better understand the context of the issue as we begin to reproduce this, what is the error you are receiving?

**Comment by CKalt** [comment]
Hi @josefaidt

Thank you for the request for more information.

I reproduced the error and created a better report that contains the information you're requeting.
Can you please close this report and you this one instead?

[Better Report Same Issue](https://github.com/aws-amplify/amplify-cli/issues/11112)

**Comment by CKalt** [comment]
I have improved the steps to reproduce section.
And the "describe the bug" section contains the error I get. Specifically, during the `amplify video add` the following error happens:

Cannot read property 'dev' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
