### ISSUE TITLE
How to integrate external AppSync with Amplify

### ISSUE THREAD

**Issue by saahithyan** [aws-amplify/amplify-cli#11129]
I have my AppSync back-end created externally and amplify hosting front-end project. 

My local `aws-exports.js` file gets updated with appsync details when I run following command
`amplify add codegen --apiId appsync-api-id`

When I deploy my front-end application through amplify, it [automatically generate Amplify config at  build-time](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html). 

But it seems like only `amplify init` command ran, `amplify add codegen` command did not run.

So, how do I properly integrate external AppSync and Amplify ?

**Comment by ykethan** [comment]
Hello @saahithyan, you would need to include the codegen command in the build specification file. Please refer to https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html.

Additionally, we can utilize an existing GraphQL API in your application by confguring amplify. Please refer:
https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js/#re-use-existing-appsync-graphql-api

**Comment by ykethan** [comment]
Hey @saahithyan, following up on this issue. Do let us know if you require any assistance.

**Comment by ykethan** [comment]
closing the issue due to inactivity
