### ISSUE TITLE
No longer able to perform pull/push 

### ISSUE THREAD

**Issue by adcanis** [aws-amplify/amplify-cli#11125]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.7.1

### Amplify CLI Version

10.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

pull, push

### Describe the bug

When performing commands I am met with this error

> An error occurred while fetching the app backend: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

Can't launch studio from console either. 
This is not a new project (8 months) and has been worked on daily up until yesterday when this error popped up. 

**.aws/config**

```
[profile projectname]
output=json
region=ca-central-1

[profile projectname-dev]
region=ca-central-1
source_profile=projectname
role_arn=arn:aws:iam::*******:role/projectname-dev-admin

[profile projectname-qa]
region=ca-central-1
source_profile=projectname
role_arn=arn:aws:iam::******:role/projectname-qa-admin

[profile projectname-prod]
region=ca-central-1
source_profile=projectname
role_arn=arn:aws:iam::*******:role/projectname-prod-admin
```
**.aws/credentials**

```
[projectname]
aws_access_key_id=********
aws_secret_access_key=*******
```
Have tried the work around (disable and re-enable studio from console), delete `Amplify folder` and `aws-exports` and now can not run `amplify pull `.

### Expected behavior

validate credentials for CLI commands / login to studio

### Reproduction steps

N/A

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by adcanis** [comment]
hey @josefaidt. Yea, i've been using **aws-vault** to swap between roles (95% of time in dev) Its worked for the last 8 months with only one previous issue. I can't share my `local-aws-info.json` as my last attempt at resolve was deleting the `Amplify` folder and ` aws-exports.js` before trying to pull back in. I can't launch studio either from Console. I've also tried the workaround (disable/re-enable studio) and nothing.

**Comment by DeviousLab** [comment]
I'm encountering a similar issue, I added auth to my project via the CLI and tried to push my code after making my changes. Afterwards, trying to open the Amplify Studio for my project results in an error message: 'An error occurred while fetching the app backend: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1'
![image](https://user-images.githubusercontent.com/53790060/194783498-6b9d89fd-ab49-4e0b-8800-e42a2a36c73f.png)

The Authentication tab on my project from the AWS Amplify console is stuck in a constant loading state, I tried disabling and enabling the Amplify Studio, but the issue still persists.

My appId is `d3nhbfpi4tfnhf` and region is `eu-central-1` if it helps.

**Comment by josefaidt** [comment]
Hey @DeviousLab would you mind filing a separate issue for this occurrence? And @adcanis apologies for the delay here, but glad to hear you're back up and running despite needing to disable Studio. Would you mind posting the project ID output of `amplify diagnose --send-report`?
