### ISSUE TITLE
Deploying and publishing to existing app on AWS Amplify no longer works

### ISSUE THREAD

**Issue by Nadine-Schneider** [aws-amplify/amplify-cli#11130]
Hi! I need some help. 

In our company we use Github Actions to deploy and publish our front on Amplify. It always worked perfectly. Deployment and publishing is done in a single Amplify application. 

However, **since yesterday we were unable to deploy and publish, an error occurs indicating that the user is not authorized to create a new app**. However, **a new app should not be created in Amplify, an existing app should be used, as it always has been**. 

Our yml is:

In our YML file we have the following command to publish to Amplify:
`amplify init --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --yes`

The error:
![image](https://user-images.githubusercontent.com/38010089/194373780-a583a98b-5870-4c7e-a621-efef8c9cd155.png)

Can you help us please?

**Comment by josefaidt** [comment]
Hey @Nadine-Schneider :wave: thanks for raising this! This appears to be a duplicate of https://github.com/aws-amplify/amplify-cli/issues/11120, and as such I will close this as a duplicate bug

Please see [this comment](https://github.com/aws-amplify/amplify-cli/issues/11120#issuecomment-1270038231) for workaround steps. In short, replace `init` with `pull` in your script

**Comment by Nadine-Schneider** [comment]
Hey @josefaidt! 👋 
Yes, I just discovered that.
And I managed to solve my problem by going back to version 10.0.0 of @aws-amplify/cli.
Thanks for listening!
