### ISSUE TITLE
Unable to override RootUrl of API in override.ts

### ISSUE THREAD

**Issue by ramyohan90** [aws-amplify/amplify-cli#11139]
**Which Category is your question related to?** Amplify CLI Override in API

**Amplify CLI Version**: 9.2.1

**What AWS Services are you utilizing?** Lambda, Layer and APIGateway using Amplify cli

Created a Lambda Layer, Lambda function using Amplify and pushed it to cloud.

Then created a API gateway using "amplify add api" and executed "amplify override api" to add custom parameters.

By default, amplify RootURL ends with environment name (Eg: https://${api-id}.execute-api.us-east-1.amazonaws.com/${env})

I am unable to override the RootUrl in override.ts and if I tried to add RootURL through override function, it is throwing error "Error: logical id "RootUrl" already exists"

I want RootURL to end with api instead of env due to project requirement (Eg: https://${api-id}.execute-api.us-east-1.amazonaws.com/api)

**There is no override function to update RootURL.**

**Please help.**

**Comment by ykethan** [comment]
Hello @ramyohan90, thank you for reaching out. Currently, the amplify override does not support this workflow. A workaround would be to utilize the hosting "rewrite and redirect" rule to redirect the url. Please refer to comment on https://github.com/aws-amplify/amplify-cli/issues/10814#issuecomment-1199897963 and documentation https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html for additional information.

**Comment by ramyohan90** [comment]
@ykethan I have also found one more workaround solution which updates the api end point as below in the API Gateway

Although, I am not able to update the root url, I am able to update the deployment stage name as below in override.ts

**Code:** resources.deploymentResource.stageName = 'api';

This updates or adds a new end point ending with api and I am able to achieve what I need.

So after updating the stage name I get a new stage url as "https://${api-id}.execute-api.us-east-1.amazonaws.com/api"

Can you let know if this can be another work around ?

**Comment by ykethan** [comment]
Hey @ramyohan90, yes this should work, appreciate bringing up this workaround as well.

**Comment by ramyohan90** [comment]
Thank you for confirming. Task can be closed @ykethan
