### ISSUE TITLE
Auth migration fails

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#11149]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Auth

**Amplify CLI Version**
10.2.1

**What AWS Services are you utilizing?**
Amplify auth, cognito

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

I want to update my current Auth, and when I do `amplify update auth` I get:

![image](https://user-images.githubusercontent.com/34192856/194957294-375d0135-dc12-48b9-9b48-f68766fbb146.png)

After I hit `y` to migrate, it modifies some files. Once I do `amplify push` I get the following errors:

![image](https://user-images.githubusercontent.com/34192856/194958001-573e4f9c-761c-4695-ae50-080a1ed95fbf.png)

On the cloudformation logs I can see the following:

![image](https://user-images.githubusercontent.com/34192856/194959470-03b97296-b760-4d0b-aaf7-d84eb9fe2a5f.png)

I also I noticed a drift:

![image](https://user-images.githubusercontent.com/34192856/194959590-26357e5a-4aca-46f9-b050-650442eaf8e4.png)

How can I migrate?

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! Despite the role drift, can you post the git diff of the changes? Does the postconfirmation trigger have access to the GraphQL API?

**Comment by afern247** [comment]
It seems to delete some file:

![image](https://user-images.githubusercontent.com/34192856/196004731-6afcabb3-4d77-406e-8356-9e5bddc39186.png)

![image](https://user-images.githubusercontent.com/34192856/196004717-54315d64-3cbf-4209-81d0-efc523fa14e2.png)

Here's the json created:

```
{
  "version": "1",
  "cognitoConfig": {
    "authSelections": "identityPoolAndUserPool",
    "requiredAttributes": [
      "email"
    ],
    "resourceName": "Road2Crypto",
    "serviceName": "Cognito",
    "useDefault": "manual",
    "userpoolClientReadAttributes": [],
    "userpoolClientWriteAttributes": [],
    "aliasAttributes": [],
    "resourceNameTruncated": "road2abc",
    "sharedId": "abc",
    "userPoolGroupList": [
      "Admin"
    ],
    "userPoolGroups": true,
    "userPoolName": "Road2Crypto",
    "usernameAttributes": [
      "email"
    ],
    "usernameCaseSensitive": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientSetAttributes": false,
    "userpoolClientGenerateSecret": false,
    "userpoolClientLambdaRole": "Road2C84eb8bb1_userpoolclient_lambda_role",
    "passwordPolicyCharacters": [],
    "passwordPolicyMinLength": 6,
    "adminQueries": false,
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "emailVerificationMessage": "Forgot password code: {####}",
    "emailVerificationSubject": "Forgot password code: {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "autoVerifiedAttributes": [
      "email"
    ],
    "hostedUI": false,
    "thirdPartyAuth": false,
    "identityPoolName": "testAuthIdentityPool",
    "allowUnauthenticatedIdentities": true,
    "authProviders": [],
    "triggers": {
      "PostConfirmation": [
        "custom"
      ]
    }
  }
}
```
@josefaidt I think this might be an issue similar to the one [you helped me](https://github.com/aws-amplify/amplify-category-api/issues/786#issuecomment-1269186440) with the 

As far as the postconfirmation trigger, it does have access to the API via `Environment variables configuration`

**Comment by afern247** [comment]
Hi @josefaidt , any update on this?

**Comment by afern247** [comment]
Can someone take a look please

**Comment by josefaidt** [comment]
Hey @afern247 apologies for the delay here! While the auth and unauth role drift is under a separate investigation, yes, migrating the auth resource will remove `parameters.json` in favor of `cli-inputs.json`. After migrating can you confirm the `CustomMessage` trigger is still attached to the resource? From the original screenshots it almost appears the auth resource still has a placeholder reference to the function

**Comment by projectforeveryoung** [comment]
I'm having an issue with an auth change breaking the build. I'm stuck unable to build now despite a successful local build and run. 

Steps:
1. Updated CLI version to latest
2. "amplify auth remove" - Deleted my previous basic username/pw auth
3. Added new auth with federated SSO
4. amplify push
5. git commit and push
6. CI/CD build no longer builds on Amplify with error:
`2022-11-14T22:44:24.394Z [INFO]: 🛑 Failed to pull the backend.
2022-11-14T22:44:24.394Z [INFO]: File at path: '/codebuild/output/src156457618/src/project-name/amplify/backend/auth/projectnamecf7697d7/parameters.json' does not exist`

I have tried multiple mitigations unsuccessfully.  Can you advise on next steps?

**Comment by josefaidt** [comment]
Hey @projectforeveryoung thanks for chiming in here. Would you mind filing a separate issue for this occurrence? While the errors are similar the workflow appears to be a bit different and I want to be sure we're capturing this as we work through these issues. As a follow-up question, what version of the CLI is being used in Amplify Hosting?

**Comment by afern247** [comment]
> Hey @afern247 apologies for the delay here! While the auth and unauth role drift is under a separate investigation, yes, migrating the auth resource will remove `parameters.json` in favor of `cli-inputs.json`. After migrating can you confirm the `CustomMessage` trigger is still attached to the resource? From the original screenshots it almost appears the auth resource still has a placeholder reference to the function

What do you mean by if the `CustomMessage` trigger is still attached to the resource? Where would I see that? I see in `function-parameters.json` the following line:

`"triggerDir": "/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage",`

I just created another replica of the environment, this time I did: `amplify update auth` and walked through the configurations and added verification link with redirection. I also removed a lambda post confirmation trigger that eventually needs to be removed because was added with the UI. This is all the modified files:

![image](https://user-images.githubusercontent.com/34192856/203842616-5e1bcee4-cee2-4bc5-8dbb-c1b16789e59a.png)

Running `Amplify status` gives me this:

![image](https://user-images.githubusercontent.com/34192856/203842737-ababa7a8-9bba-4676-b9c8-e0782cb940f8.png)

so lots of changes... after I do `amplify push` I get the first error at:

![image](https://user-images.githubusercontent.com/34192856/203843607-d9a3f68d-1eb9-45f0-af76-65aea4fa888e.png)

Something to keep in mind is that the I modified manually the Auth on the UI in Cognito User Pools, I added there:
- Custom message for email verification
- Selected the lambda function for post confirmation
etc

This is part of the process I'm trying to get rid of in favor of doing it all on code. I mention this because I don't know if this is what's failing or one of the reasons why.

After I ran: `amplify push` this is what I got:

![image](https://user-images.githubusercontent.com/34192856/203846431-aa850a93-c7b8-469b-a5b6-f04afb9398e7.png)

I went to check my user's permission and it has the recommended settings:

![image](https://user-images.githubusercontent.com/34192856/203846541-205178f9-8d31-42ad-8cb5-fe11955134cb.png)

So I tried doing the push again, this time with root credentials and now the environment is in a limbo state again (can't update the project because it says there is a process pending) ... with a different error:

![image](https://user-images.githubusercontent.com/34192856/203847043-f14faa2d-279e-46ea-ab49-d8ff159db190.png)

This is so frustrating... what do you recommend to do next? I can create yet another environment or we can continue troubleshooting this one @josefaidt

**Comment by afern247** [comment]
Hi @josefaidt, first Happy Holidays!

I've been playing around with extra environments to resolve the issue and I was able to successfully migrate the Auth, however I'm missing one last part of the puzzle. You are helping me with https://github.com/aws-amplify/amplify-cli/issues/11142, and I was also able to override and push it without error but it's not sending the email. Do you mind taking a look at my response on that ticket so I can close that one and then try this ticket on production? Please do not close this one yet, I need to migrate on prod first, this was successful only on a dev env.

**Comment by afern247** [comment]
Anyone...?

**Comment by josefaidt** [comment]
Hey @afern247 apologies for the delay here!! Are you still experiencing this? Were you able to successfully migrate your production instance?

**Comment by afern247** [comment]
Not yet. I'm actually doing a bunch of code migration, I successfully migrated the iOS app to use the SDK version 2.0 and I'm also using sign up with code instead of link so I can remove all GUI changes. I expect to be able to try again next week and I'll let you know of the results.

**Comment by josefaidt** [comment]
Hey @afern247 that sounds great! I'll keep this open for now and circle back

**Comment by josefaidt** [comment]
Hey @afern247 I wanted to follow-up on this one and see how things were going. Are you still experiencing this issue?

**Comment by afern247** [comment]
I solved it already. Prod has been migrated. Thanks for the help and follow up @josefaidt

**Comment by josefaidt** [comment]
Hey @afern247 glad to hear you're up and running and were able to migrate successfully! Closing issue
