### ISSUE TITLE
AdministratorAccess-Amplify has no permission to perform appsync:UntagResource

### ISSUE THREAD

**Issue by csilvacaio** [aws-amplify/amplify-cli#11141]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v18.9.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

ArchLinux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, custom, api

### Amplify Commands

push

### Describe the bug

When trying to execute `amplify push`, I started facing the following issue:

```
🛑 The following resources failed to deploy:
Resource Name: GraphQLAPI (AWS::AppSync::GraphQLApi)
Event Type: update
Reason: User: ..._Full-access/amplifyadmin is not authorized to perform: appsync:UntagResource on resource: arn:aws:appsync:us-east-1...
 (Service: AWSAppSync; Status Code: 403; Error Code: AccessDeniedException; ...)

🛑 An error occurred during the push operation: /
Resource is not in the state stackUpdateComplete
```
I already tried with _--force_ and also after running a `amplify pull`.

My user profile contains the **AdministratorAccess-Amplify** role. Also, I was working normally on the same project and using the same profile and environment in the previous weeks.

### Expected behavior

A success push operation when executing an usual `amplify push`

### Reproduction steps

Unfortunately, I'm not able to provide the steps to reproduce the issue. It started happening after a normal/simple change on my lambda code.

**Comment by ykethan** [comment]
Hey @csilvacaio, thank you for reaching out. Wanted to confirm some information. Is the Lambda function dependent on the GrahpQL API resource?
Additionally, if you run `amplify push function` does the push fail as well?

**Comment by csilvacaio** [comment]
Hey @ykethan 

Yes, my lambda depends on GraphQL API resource. Also, I have the same issue when running `amplify push function <fnName>`. I tried to change another function that doesn't depend on GraphQL API, but I faced the same issue.

**Comment by ykethan** [comment]
Hey @csilvacaio, Thank you for the information. I observed the amplify application utilizes custom resource, does the application add any tags using the api override or amplify add custom to the AppSync API?
If no, were any tags manually added on the AppSync console?

Additionally, does manually adding the `appsync:UntagResource` inline policy to the `..._Full-access/amplifyadmin` role resolve the issue as a mitigation step?

**Comment by csilvacaio** [comment]
Manually adding the inline policy to the role solved my issue.
Thanks for your help @ykethan

**Comment by ykethan** [comment]
Glad to hear that you were able to mitigate the issue. I will be closing the issue, please feel free in reaching out to us again.
