### ISSUE TITLE
Could not initialize 'staging': EINVAL: invalid argument, realpath

### ISSUE THREAD

**Issue by DIBO237** [aws-amplify/amplify-cli#11146]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

10.2.2

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I was building a contact api which will store the user input data into dynamo db, everything works fine in local, but when i tried  'amplify pull' command it throws the bug.

```js script 
const AWS = require('aws-sdk')
const docClient = new AWS.DynamoDB.DocumentClient();


/**********************
 * Example get method *
 **********************/

app.get('/contact', function(req, res) {
  // Add your code here
  res.json({success: 'get call succeed!', url: req.url});
});

app.get('/contact/*', function(req, res) {
  // Add your code here
  res.json({success: 'get call succeed!', url: req.url});
});

/****************************
* Example post method *
****************************/
console.log(process.env.STORAGE_DYNAMOB9573AAC_NAME)
app.post('/contact', function(req, res) {
  var params = {
    TableName: process.env.STORAGE_DYNAMOB9573AAC_NAME,
    Item:{
      id:uniqid(),
      email:req.body.email,
      password:req.body.pass
    }
  }

  docClient.put(params,(err,data)=>{
       if(err) res.json({err})
       else res.json({ success:"success", datas:data})
  })
  // Add your code here
});
```

### Amplify Categories

auth, storage, function, api

### Amplify Commands

add, pull, push, status, update

### Describe the bug

```
C:\Users\dibya\Desktop\SKYGOAL\aws2>amplify pull

Pre-pull status:

    Current Environment: staging

┌──────────┬────────────────┬───────────┬───────────────────┐
│ Category │ Resource name  │ Operation │ Provider plugin   │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Function │ contact        │ Delete    │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Api      │ con            │ Delete    │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Auth     │ skygoal        │ No Change │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Storage  │ dynamob9573aac │ No Change │ awscloudformation │
└──────────┴────────────────┴───────────┴───────────────────┘

Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
\ Fetching updates to backend environment: staging from the cloud.🛑 Could not initialize 'staging': EINVAL: invalid argument, realpath 'C:\Users\dibya\Desktop\SKYGOAL\aws2\amplify\.temp\#current-cloud-backend\api\con'

C:\Users\dibya\Desktop\SKYGOAL\aws2>node -v
v16.14.0

C:\Users\dibya\Desktop\SKYGOAL\aws2>amplify version
10.2.2
```

### Expected behavior

i am trying to push the changes to aws console

### Reproduction steps

amplify pull or amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by DIBO237** [comment]
review

**Comment by josefaidt** [comment]
Hey @DIBO237 :wave: thanks for raising this! To better understand the context of the issue would you mind posting the project ID from `amplify diagnose --send-report`? I also have a few follow-up questions:

- is this `.temp` directory an artifact from another `pull` attempt?
- what were the changes applied prior to running `amplify pull` and receiving this error?
- can you provide minimal reproduction steps to reproduce this issue?

Here are the steps I followed to attempt reproducing on my end:

1. `amplify init -y`
2. `amplify add api` > REST API > add a function
3. `amplify push -y`
4. `amplify remove api` (to show the API resource in `delete` status)
5. `amplify pull` > follow prompts
6. observe successful pull

**Comment by josefaidt** [comment]
Hey @DIBO237 :wave: thanks for sending that over. How was the API originally added to the project? I see here it's shown in the `DELETE` status and the metadata for the API is empty (along with the function). Can you try running `amplify pull --restore`?

**Comment by DIBO237** [comment]
> Hey @DIBO237 👋 thanks for sending that over. How was the API originally added to the project? I see here it's shown in the `DELETE` status and the metadata for the API is empty (along with the function). Can you try running `amplify pull --restore`?

Hi @josefaidt actully i thought the api are causing this so i tried to delete it , i used ```amplify add api```

**Comment by josefaidt** [comment]
Hey @DIBO237 no worries, thanks for clarifying! Are you seeing a stale `amplify/.temp/` directory leftover from a previous failed pull?

**Comment by DIBO237** [comment]
hi @josefaidt , yes there is , it contains two filles ```#current-cloud-backend``` and ```#current-cloud-backend.zip```

**Comment by josefaidt** [comment]
Hey @DIBO237 :wave: apologies for the delay here!!! Please try removing the `.temp` directory and re-attempt the operations. Please note the resources that you intend to keep, as after a failed push it is possible the API will be deleted as the backend definition is no longer available in `amplify/backend`

**Comment by DIBO237** [comment]
Hi thanks for the help, i solved it by copying all the files inside ### .temp folder and pasting it inside backend folder.
