### ISSUE TITLE
While Pulling the amplify app with pull command I am getting error.

### ISSUE THREAD

**Issue by ShubhamVerma5588** [aws-amplify/amplify-cli#11143]
> While Pulling the amplify app I am getting error.
command : amplify pull --appId <appId> --envName <envName>
`
🛑 Cannot prompt for [An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm ] in a non-interactive shell

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
`
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?** amplify

**Amplify CLI Version**
10.2.1 version

**What AWS Services are you utilizing?**
API and DynamoDB 

**Error on amplify CLI**

🛑 Cannot prompt for [An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm ] in a non-interactive shell

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

**Comment by josefaidt** [comment]
Hey @ShubhamVerma5588 :wave: thanks for raising this! Would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help gather additional context around the issue you are experiencing.

Additionally, it was noticed that Amplify CLI 10.2.1 contained an issue and was reverted to [10.0.0](https://www.npmjs.com/package/@aws-amplify/cli)
