### ISSUE TITLE
How can I change from code to verification link at user sign up

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#11142]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify cli and its commands 

**Amplify CLI Version**
10.2.1

**What AWS Services are you utilizing?**
Amplify with api, cognito pools, datastore, analytics

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

I updated on the Cognito Pools GUI the verification method to be Link, however every time I change on the console the api using `amplify update auth` the gui changes disappear. 

How using that command I can update the auth method to send a link?

> I do not want redirection when the link is clicked

Here's how it looks on the GUI

![image](https://user-images.githubusercontent.com/34192856/194731592-01b557c0-f3a5-44c1-9fa1-c0485c87e652.png)

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! We can use [overrides](https://docs.amplify.aws/cli/auth/override/) to modify this property and persist across updates. To get started, run `amplify override auth`. Then paste the following into the newly created override file

```ts
// amplify/backend/auth/<resource-name>/override.ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPool.emailVerificationMessage = undefined
  resources.userPool.emailVerificationSubject = undefined
  resources.userPool.addPropertyOverride('VerificationMessageTemplate', {
    DefaultEmailOption: 'CONFIRM_WITH_LINK',
    EmailMessageByLink:
      'Please click the link below to verify your email address. {##Verify Email##}',
    EmailSubjectByLink: 'Your verification link',
  })
}
```

> **Note**
> For reference, here is the [schema for `VerificationMessageTemplate`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_VerificationMessageTemplateType.html).

After pushing the changes we will see the verification type has been changed to `link`

<img width="845" alt="image" src="https://user-images.githubusercontent.com/5033303/194888328-8d111279-5646-47fa-931a-b17d2175e177.png">

**Comment by afern247** [comment]
This is blocked by https://github.com/aws-amplify/amplify-cli/issues/11149 once I can upgrade I can test this

**Comment by afern247** [comment]
Hi @josefaidt , I'm getting a user sign up but the email to confirm the email is not being sent. I believe this is because I have to setup my domain, this is how I have it setup on the UI:

![image](https://user-images.githubusercontent.com/34192856/209683159-8908e336-bcdf-4295-997b-3a8a2fcf319d.png)

How can I extend your code to also send the link using my domain? I believe this is the issue.

Thanks and happy holidays!

**Comment by afern247** [comment]
Hi @josefaidt , any update on this?

**Comment by afern247** [comment]
Can someone help on this please
cc: @josefaidt

**Comment by josefaidt** [comment]
Hey @afern247 apologies for the delay!! Were you able to override the auth resource to set the VerificationTemplate?

**Comment by josefaidt** [comment]
Hey @afern247 in addition to the override in my previous reply we will also need to have a valid domain attached to the user pool, which we can configure by running `amplify update auth` and applying the default configuration with Social Provider. This will enable the Hosted UI and create a Cognito domain that will then be configured with the User Pool.
![image](https://user-images.githubusercontent.com/5033303/226761363-6056acf8-63a9-471e-9677-d2b5e267615c.png)
![image](https://user-images.githubusercontent.com/5033303/226761391-d908cad3-aafe-455b-85f3-75211897cb49.png)

The caveat being the [UI component's authenticator](https://ui.docs.amplify.aws/react/connected-components/authenticator) will default to asking for the confirmation code, therefore you will need to modify/override this behavior or use the [`Auth`](https://docs.amplify.aws/lib/auth/auth-events/q/platform/js/) module from `aws-amplify` to create an auth flow

**Comment by afern247** [comment]
Closing this as I will not be implementing it. There is not a native way to fully customize the backend for this feature using the command line and making UI changes is not good as it would be override by the CLI later on...

Thanks for the help jose
