### ISSUE TITLE
Amplify push creating multiple stale layers in lambda layer during amplify version upgrade

### ISSUE THREAD

**Issue by ramyohan90** [aws-amplify/amplify-cli#11144]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @amplify/cli@10.0.0

### If applicable, what version of Node.js are you using?

v16.17.1

### Amplify CLI Version

10.0.0

### What operating system are you using?

Centos 8 WSL

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Did not make any manual changes

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

We are currently using amplify 4.29.2. Although this version works fine, but as we are migrating the Node Version to 16.x, we have planned to migrate amplify to 10.x as well. Below were the steps we followed during amplify upgrade

1. We cloned our Repo which had Amplify 4.29.2 version of project
2. Our project contains, A Lambda Layer, A Lambda Function and a API module.
3. Added override function for API module to add some custom parameters  - No issues in this, it was successful
4. Then pushed the code changes. There were many stale layers got added to layer's cloud formation template (Eg: LambdaLayerPermissionPrivateLegacy57)
5. Then as per similar existing issue reported, removed stale layers using amplify remove function
6. When we pushed the code again, the stale layers were created in templates again. (Attached zip file which shows multiple layers created. sensitive data marked as X)

Please note that, when we create a fresh project with latest amplify version, we do not face this stale layers getting added issue. Only when we try to upgrade the project, we are getting this.

### Expected behavior

During this migration, we have problems only with the stale layers getting created again and again. We need to stop these from getting created.

### Reproduction steps

1. Create a small project with lambda layer, a function and api using amplify 4.29.2
2. Then upgrade amplify to latest version or 9+ version
3. Make changes accordingly to the latest version (like override function)
4. Push change.
5. Check Layer CF template. If no stale layers are present, make some change in API layer and push again
6. This time, stale layers will get created
8. Remove the stale layers using "amplify remove function" and push
9. But still, you can able to see stale layers getting created

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

[api-layer-cloud-formation-template.zip](https://github.com/aws-amplify/amplify-cli/files/9741861/api-layer-cloud-formation-template.zip)

**Comment by ramyohan90** [comment]
Kindly help us to resolve the issue without having to create a new project from scratch and adding the functions to it.

**Comment by josefaidt** [comment]
Hey @ramyohan90 :wave: thanks for raising this! While we begin to investigate this I have a few follow-up questions to better understand the context of the issue:

- are you referring to upgrading the Amplify CLI to version 9 and above?
- to clarify, were the changes made to the layer changes such as adding additional files?
- do you have Lambda functions dependent on specific versions of the layer?

> When we pushed the code again, the stale layers were created in templates again. (Attached zip file which shows multiple layers created. sensitive data marked as X)

After removing the layer versions using the CLI are you seeing them reappear upon running `amplify push`? Or are these new layers?

**Comment by josefaidt** [comment]
Hey @ramyohan90 

> So to answer your question I did not make any changes. I hope changing npm versions in package.json under lib/nodejs does not matter.

Upgrading package versions in the `package.json` file will trigger an update to the layer as it will install the dependencies, update the lockfile, and push.

> do you have Lambda functions dependent on specific versions of the layer?
> Yes we do have lambda function to which the layer is attached.

My apologies, to clarify when we add a function to a layer we have the option of choosing the LATEST version of the layer, or a specific version.

> After removing the layer versions using the CLI are you seeing them reappear upon running amplify push? Or are these new layers?
Yes after removing the layers using "amplify remove function", stale layers (Eg: LambdaLayerPermissionPrivateLegacy53) are getting added again during the push. Attached the zip file in this bug. You can refer that.
Please note that, the stale layers are not getting added when we create project from scratch but only during project upgrade, it is added.

How many layers are created on each push? Is it just one or a handful (e.g. 4-5)?

**Comment by ramyohan90** [comment]
>Upgrading package versions in the `package.json` file will trigger an update to the layer as it will install the dependencies, update the lockfile, and push.

 Yes, but I hope this is not the cause for stale layers being created.

> My apologies, to clarify when we add a function to a layer we have the option of choosing the LATEST version of the layer, or a specific version.

Yes I dont have problem with this

> How many layers are created on each push? Is it just one or a handful (e.g. 4-5)?

Around 50 to 60 layers are created - Please find the zip file I attached ([api-layer-cloud-formation-template.zip](https://github.com/aws-amplify/amplify-cli/files/9741861/api-layer-cloud-formation-template.zip)). The layers ending with Legacy are being created by itself. Also, I executed "amplify remove function" to remove stale layers, but still getting created during every push.

**Comment by josefaidt** [comment]
Hey @ramyohan90 thank you for clarifying. The CloudFormation template seems interesting, but would you be open to sharing the project ID output from `amplify diagnose --send-report`?

**Comment by ramyohan90** [comment]
> Hey @ramyohan90 thank you for clarifying. The CloudFormation template seems interesting, but would you be open to sharing the project ID output from `amplify diagnose --send-report`? This would help gather additional context around your project's setup

@josefaidt  I will provide it in a day or two. Thanks.

**Comment by ramyohan90** [comment]
> Hey @ramyohan90 thank you for clarifying. The CloudFormation template seems interesting, but would you be open to sharing the project ID output from `amplify diagnose --send-report`? This would help gather additional context around your project's setup

As you asked, attached the output here. Please help.
[report-1665944992050.zip](https://github.com/aws-amplify/amplify-cli/files/9832863/report-1665944992050.zip)

**Comment by ramyohan90** [comment]
> Hey @ramyohan90 apologies for the delay here! Are you still experiencing this issue? I'm able to see the additional layer versions in your CloudFormation stack, and am curious if you are able to manually remove those references from the CloudFormation stack and push with `--force`?

@josefaidt Unfortunately this issue is not fixed yet. Even if we remove those references manually, it is getting recreated again during push. (Haven't tried with --force argument though). As of now, we stick to amplify 4.29.2 / 4.50.0 with Node v16.17.1.

Our application is an enterprise one and we are running15 lambdas with large source code. So, it is impossible to create lambdas from scratch with new amplify version (10.x). Only migration from 4.X to 10.x will help us save time and cost. But migration causes above issues.

**Comment by josefaidt** [comment]
Hey @ramyohan90 in addition to my previous comment, can you see if these layers are still available in the AWS Console? If so, can you try deleting them from there?

**Comment by ramyohan90** [comment]
> Hey @ramyohan90 in addition to my previous comment, can you see if these layers are still available in the AWS Console? If so, can you try deleting them from there?

Hello @josefaidt - sorry for the late reply. Mid next week I will try to document / record the steps I followed and I will come back again in few days. Just give me few days as I am stuck in few deliverables. As per your latest statement, I will also check the layers in console and will try to delete if it is available in console. Thanks. Will come back soon with some more details, after that we can connect if required.

**Comment by josefaidt** [comment]
Hey @ramyohan90 no worries! I'll circle back in a few days!

**Comment by josefaidt** [comment]
Hey @ramyohan90 just wanted to circle back on this and see how things are going 🙂

**Comment by ramyohan90** [comment]
@josefaidt Thanks for the follow up. Unfortunately our tech team has decided to proceed with amplify 4.5.0 due to time constraints. So they have postponed the migration of amplify. In upcoming quarters, we would be migrating to new Node versions, so at that time they decided to upgrade to newer amplify versions. Can we close the issue now and re-open when we work on it again ?
