### ISSUE TITLE
Add AttributesRequireVerificationBeforeUpdate to CLI

### ISSUE THREAD

**Issue by jasondavis87** [aws-amplify/amplify-cli#11145]
### Is this related to another service?

Auth

### Describe the feature you'd like to request

I'd like to be able to add the option for users to verify their email before Cognito changes it, i.e. this: ```AttributesRequireVerificationBeforeUpdate```

### Describe the solution you'd like

I'd like an option in the CLI whilst setting up AUTH or updating AUTH that asks the user something like: "Would you like updates to emails/phone numbers to reflect immediately or upon email/phone verification? 

### Describe alternatives you've considered

N/A

### Additional context

This is an option already in Cognito docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminUpdateUserAttributes-property

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by akshbhu** [comment]
This feature will be automatically enabled for existing / new projects with next release.
here is the merged PR : https://github.com/aws-amplify/amplify-cli/pull/10773

**Comment by jasondavis87** [comment]
Thank You!
