### ISSUE TITLE
Preferred way to change env in the secondary frontend project?

### ISSUE THREAD

**Issue by taneba** [aws-amplify/amplify-cli#11147]
**Which Category is your question related to?**
env

**Amplify CLI Version**

10.0.0

According to the [docs](https://docs.amplify.aws/cli/teams/multi-frontend/#workflow), we should avoid modifying backend in the secondary project. So recommended way to start using the existing backend in the secondary project is to use `amplify pull`.

But how can we change env in the secondary project? If my understanding is right, the only way to do this is to `rm -rf amplify/` `rm src/aws-exports.js` and `amplify pull` again, which I think it's kinda cumbersome operation.

Is there any easier way to do this? or any plan to make it easier?

**Comment by taneba** [comment]
Maybe #9457 could make it easier

**Comment by josefaidt** [comment]
Hey @taneba :wave: thanks for raising this! For these types of projects we will need to pull the additional environments with `amplify pull --appId <app-id> --envName <env-name`. And while we work to improve the multi-env workflow, we can change environments by rerunning the pull command with the specified app ID and environment name

**Comment by taneba** [comment]
@josefaidt 
Thank you for your super rapid reply as always!
That command should help! 
And it'd be great if it is on the document (can I help with improving documentation?)
I'm ok with closing this, but leave it you ;)
