### ISSUE TITLE
Inacessible Host on Amplify Init

### ISSUE THREAD

**Issue by gdutramartins** [aws-amplify/amplify-cli#11157]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16,16,0

### Amplify CLI Version

10.2.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

init

### Describe the bug

amplify init causes de following error after choose profile:

- Inaccessible host: `amplify.us-west-2.amazonaws.com' at port `443'. This service may not be available in the `us-west-2' region.

I tried to  create another user 
I tested ping and Windows Test-NetConnection, both have sucess.
I read tutorial in aws and blogs, 

### Expected behavior

Configure amplify access with profile configuration.

### Reproduction steps

1. rum amplify init
2. accept all default configurations
3. Select AWS Proflie authentication method (tried with access key as well)
4. use default profile (created with amplify configure)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

amplify init was not executed so there is no information on dignose:

`amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
- Creating Zip

      No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.

× Creating Zip`

### Log output

<details>

```
# Put your logs below this line
Inaccessible host: `amplify.us-west-2.amazonaws.com' at port `443'. This service may not be available in the `us-west-2' region.

```

</details>

**Comment by josefaidt** [comment]
Hey @gdutramartins :wave: thanks for raising this! By chance are you behind a corporate VPN? Typically these connection issues signify an issue at the network level

**Comment by gdutramartins** [comment]
Thanks for response @josefaidt ,
With your comment i tried to suspend Bitdefender anti-virus and resolve my issue!!
Thanks a lot, helped with the solution.
