### ISSUE TITLE
does the new cli 10.2.3 update include fix to work with amplify-video-add plugin?

### ISSUE THREAD

**Issue by sirmaestro512** [aws-amplify/amplify-cli#11153]
does the new cli 10.2.3 update include fix to work with amplify-video-add plugin?

**Comment by josefaidt** [comment]
Hey @sirmaestro512 :wave: please refer to the explanation from one of our team members on the closed thread https://github.com/aws-amplify/amplify-cli/issues/11112#issuecomment-1268804613. In short, the plugin will need to be updated to support the latest CLI versions.
