### ISSUE TITLE
Multienv - resource changes to one env are reflected in another

### ISSUE THREAD

**Issue by sambomcd** [aws-amplify/amplify-cli#1115]
**Describe the bug**
Project using Amplify was set up using an older version of CLI (by a different person, so I do not have version number of that CLI). Wanting to implement different Amplify envs so I updated the CLI, completed migration, created a new amplify ENV and made changes to resources for that ENV. When I switch back to the 'old' env, the changes I have just made are showing as also being made to the old ENV, ready to be pushed.

**To Reproduce**

1. Installed CLI v1.1.8
2. Ran migration. Had an issue when it go to 'amplify push' stage, complained about corrupt data in local-aws-info.json. Removed a line referencing a file location (that was not mentioned int he manual instructions for migrating CLI).
3. amplify push failed complaining that cloudformation entries that were needed were missing
4. ran 'amplify configure project' and stepped through settings. 'amplify push' now successful.
5. create new amplify env
6. removed storage resource. amplify push
7. updated auth resource to new cognito pool. amplify push
8. added new storage resource. amplify push.
9. everything seems ok
10. check out the 'old' amplify env (NONE) and run 'amplify status'
11. it shows the above changes applied to this env also

**Expected behavior**
I expect that I am able to add and remove resources in the different environments and not have them affect other environments.

**Screenshots**
<img width="833" alt="Screen Shot 2019-03-25 at 1 39 40 PM" src="https://user-images.githubusercontent.com/1875763/54925349-0c85bc80-4f06-11e9-9d69-f32a090f17b9.png">
<img width="398" alt="Screen Shot 2019-03-25 at 1 40 31 PM" src="https://user-images.githubusercontent.com/1875763/54925356-0f80ad00-4f06-11e9-90dc-ca5b1d5d2893.png">
<img width="737" alt="Screen Shot 2019-03-25 at 1 41 14 PM" src="https://user-images.githubusercontent.com/1875763/54925357-10194380-4f06-11e9-873c-8da091b114d2.png">
<img width="426" alt="Screen Shot 2019-03-25 at 1 41 23 PM" src="https://user-images.githubusercontent.com/1875763/54925358-10194380-4f06-11e9-8c34-057607bf2294.png">
<img width="431" alt="Screen Shot 2019-03-25 at 1 41 36 PM" src="https://user-images.githubusercontent.com/1875763/54925366-13acca80-4f06-11e9-8895-40466f8aa82a.png">

**Desktop (please complete the following information):**
 - OS: macos 10.13.4
 - Browser safari
 - Version 11.1

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by kaustavghosh06** [comment]
@sambomcd That's the desired behavior to move in changes from one env to another. If you do not want to move changes from env to another, you might want to use `amplify env checkout <env-name> --restore` command.

**Comment by sambomcd** [comment]
Hi @kaustavghosh06 and many thanks for the quick response. Then I must be misunderstanding this - is the idea that I should have just created a new env, then simply run 'amplify push' and it would have duplicated all resources from the NONE env, but with a '-test' appended to the resource names created on AWS??  I had understood that once a new env had been created, you could add/remove resources from it without it affecting other env's?

**Comment by kaustavghosh06** [comment]
Yes, you're right. You would be creating a clone of the "NONE" env if you're adding a new env **from** the "NONE" enviornment. In your new env you can then add/modify/update resources and push which would create a new set of resources with "-test" postifx, this creating/modifing resources tied to the new env and not affect the "NONE" env.

 Now, if you want the same configuration changes to be reflected in the "NONE" env as well, you would run `amplify env checkout NONE` from the new env and run `amplify push` for the "NONE" env to reflect whatever congfigurations you added/updated/removed in your other new environment. If you don't want to copy the configurations from the new env to "NONE", you could always use `amplify env checkout --restore` command and this way your changes from the new env won't reflect in the "NONE" environment. 

You could refer to https://aws-amplify.github.io/docs/cli/multienv?sdk=js for docs around this.

**Comment by sambomcd** [comment]
Thanks @kaustavghosh06. I had been intending to come back to this issue and provide some feedback, but yes it is better closed. I have found some of the aspects of multienv to be not so intuitive such as:

- removing services in one env marks them to be removed in another
- needing to use the --restore command when checking out an env to ignore changes in another env (shoudln't this be the default behaviour when switching between envs?)

I am certain that there are FAR more considerations to this than I can fathom, but just wanted to put in my 2 cents worth. 

I had quite a few issues trying to:
- migrate to new version of CLI
- create a new env (with exactly the same resources as original, just different 'pools')
- make this work in a CI/CD process using CircleCI (couldnt get checkout to work as part of build, so in the end am just copying over aws-exports in build, which is obviously going to need to be manually updated if/when amplify resources are added/changed)

Still a fan of what you guys are doing - just thought I'd loop back on this.
