### ISSUE TITLE
Cannot read property 'sampledev' of undefined

### ISSUE THREAD

**Issue by cbraga01** [aws-amplify/amplify-cli#11164]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.17.1

### Amplify CLI Version

10.2.3

### What operating system are you using?

Ubuntu 22.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nothing

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

charly@charly-Latitude-5521:~/XXXXX/cloudfront-secure-media$ amplify add video
? Select from one of the below mentioned services: Video-On-Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: telecom
? Select a system-provided encoding template, specify an already-created template name:  Default HLS Adaptive Bitrate
? Do you want to get notifications on the video processing job? No
? Is this a production enviroment? Yes
? Do you want to protect your content with signed urls? No
? Do you want Amplify to create a new GraphQL API to manage your videos? (Beta) No
⠋ Building video resources...🛑 Cannot read property 'sampledev' of undefined

### Expected behavior

Following this procedure in :

https://aws.amazon.com/es/blogs/media/awse-protecting-your-media-assets-with-token-authentication/

All resources built should be the result expected.

### Reproduction steps

charly@charly-Latitude-5521:~/XXXXX/cloudfront-secure-media$ amplify add video
? Select from one of the below mentioned services: Video-On-Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: telecom
? Select a system-provided encoding template, specify an already-created template name:  Default HLS Adaptive Bitrate
? Do you want to get notifications on the video processing job? No
? Is this a production enviroment? Yes
? Do you want to protect your content with signed urls? No
? Do you want Amplify to create a new GraphQL API to manage your videos? (Beta) No
⠋ Building video resources...🛑 Cannot read property 'sampledev' of undefined

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

Project Identifier: fbcd806340f12f93b91dabbf7eeb1094

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Project Identifier: fbcd806340f12f93b91dabbf7eeb1094

**Comment by josefaidt** [comment]
Hey @cbraga01 👋 thanks for raising this! Please refer to the explanation from one of our team members on this closed thread regarding the third party video plugin https://github.com/aws-amplify/amplify-cli/issues/11112#issuecomment-1268804613. In short, the plugin will need to be updated to support the latest CLI versions, and another developer has recently filed [an issue](https://github.com/awslabs/amplify-video/issues/357) on their repository
