### ISSUE TITLE
DynamoDB Stream Lambda template not automatically granted necessary permissions

### ISSUE THREAD

**Issue by pjsandwich** [aws-amplify/amplify-cli#11166]
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

DynamoDB, AppSync GraphQL API

### Describe the feature you'd like to request

When going through the CLI setup sequence for a DynamoDB Lambda Trigger via `amplify add function`, the Lambda function should be granted access to the appropriate resources.

Currently, the following process:
```
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: nameOfFunction
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Lambda trigger
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream  
? Choose a DynamoDB event source option Use API category graphql @model backed DynamoDB table(s) in the current Amplify project dynamodbTable
```

leads to this error:
CLI:
```
🛑 The following resources failed to deploy:
🛑 An error occurred during the push operation: 
Resource is not in the state stackUpdateComplete
```
CloudFormation logs:
```
was not successfully created: No export named apiNameGraphQLAPIIdOutput:GetAtt:UserDataTable:StreamArn found
```

### Describe the solution you'd like

1. Configure resource
```
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: nameOfFunction
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Lambda trigger
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream  
? Choose a DynamoDB event source option Use API category graphql @model backed DynamoDB table(s) in the current Amplify project dynamodbTable
```

2.
```
amplify push
```

This should create the appropriate permissions for the lambda function to access the GraphQL API Endpoint Output from the API category and deploy the function.

### Describe alternatives you've considered

```
amplify update function

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. auth, api
? Select the operations you want to permit on project read
? Select the operations you want to permit on apiResource Query
```

This allows the function to deploy

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hello @pjsandwich, thank you for reaching. On replicating the Lambda trigger template in my Amplify application, I was unable to reproduce the error message. The Amplify CLI created a IAM role with with the necessary permissions.
![image](https://user-images.githubusercontent.com/87995712/195610831-05579707-bc9a-451d-99fc-6e0639018fa5.png)
![image](https://user-images.githubusercontent.com/87995712/195610808-e9f1e444-544a-4026-90f6-f90ec9c9c85d.png)

To dive deeper into the issue, could you provide us the following information.
What is the Amplify CLI version installed( using amplify -v)?
Does the the IAM user utilize Amplify administrator access or a custom access?
Could you run a diff on the the cli.json file present under the Amplify folder to ensure all the flag are latest?
```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false,
      "respectprimarykeyattributesonconnectionfield": false,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": true
  }
}
```

**Comment by pjsandwich** [comment]
Hey @ykethan, I'm using version 10.2.3. The user has Amplify admin access role configured. here's the output for `fc git.txt mine.txt` where `git.txt` is the `cli.json` you posted and `mine.txt` in my cli from the project.

```
Comparing files git.txt and MINE.TXT
***** git.txt
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false,
      "respectprimarykeyattributesonconnectionfield": false,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": false
    },
***** MINE.TXT
      "suppressschemamigrationprompt": true,
      "showfieldauthnotification": false,
      "securityEnhancementNotification": false
    },
*****
```

looks like I'm both missing some values and some of my values are different.

I should add that this project was initialized at Amplify v8.0 or maybe earlier

**Comment by ykethan** [comment]
Hey @pjsandwich, could you provide us the full cli.json? as this would enable us to create a similar environment.

**Comment by pjsandwich** [comment]
@ykethan 

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "showfieldauthnotification": false,
      "securityEnhancementNotification": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": true
  }
}
```

**Comment by ykethan** [comment]
hey @pjsandwich, Thank you for the information and working with me on this issue. Using the cli.json provided I tried replicating the issue by adding an GraphQL API and the Lambda trigger but did not experience the error `No export named apiNameGraphQLAPIIdOutput:GetAtt:UserDataTable:StreamArn found`. 

Could you try adding in the missing feature flags and a new Lambda trigger in a test environment to observe if the issue occurs in a different environment as well.
To document the issue could you provide us the project identifier by running `amplify diagnose --send-report`.

**Comment by ykethan** [comment]
Hey @pjsandwich  , following up on this behaviour. Please do let us know if you require any assistance.

**Comment by pjsandwich** [comment]
> Hey @pjsandwich , following up on this behaviour. Please do let us know if you require any assistance.

Hey, sorry about the absence, I haven't tried replicating this yet but will try it out eventually and let you know what the result is.

**Comment by ykethan** [comment]
Hey @pjsandwich, I will be closing the issue for now to prevent the issue from going stale. Please feel free in reopening the issue and tagging me or create a new issue linking the issue. We would be happy in diving deeper into the issue.
