### ISSUE TITLE
Amplify pull stuck on fetching updates (CLI version 10.2.3)

### ISSUE THREAD

**Issue by FarmerBZH** [aws-amplify/amplify-cli#11185]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.16.0

### Amplify CLI Version

10.2.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, custom, storage, function, api

### Amplify Commands

env, pull, push

### Describe the bug

If I run one of these command lines : 
`amplify pull`, `amplify push`, `amplify checkout env xxx`

It freezes every time during fetching:
`Fetching updates to backend environment: testing from the cloud.`

Yesterday, everything was working well as always but since this morning, I can make a simple `amplify pull`.

### Expected behavior

Pull, push or change amplify env.

### Reproduction steps

1. Go to your folder `amplify`
2. Make `amplify pull`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Also, I have tried everything on this issue: https://github.com/aws-amplify/amplify-cli/issues/4795

**Comment by josefaidt** [comment]
Hey @FarmerBZH :wave: thanks for raising this! As we begin to investigate, would you mind posting the proejct ID from `amplify diagnose --send-report`? Did this start occurring after upgrading the CLI? Were any other changes made?

**Comment by FarmerBZH** [comment]
@josefaidt the project ID is 9a18cb348ebcb3ddb2b3c1eecacf5233.

It just starts today and I do not know which kind of changes I have made between yesterday and today... This is the first that I face it.

Maybe coming from a npm install...

**Comment by josefaidt** [comment]
Hey @FarmerBZH no worries! I see you have quite a few resources and dependencies, but nothing that stands out. 

- do you see any logs that may indicate as to why the CLI is hanging in `~/.amplify/logs/`? 
- are you able to pull this project into a new sibling directory?

**Comment by FarmerBZH** [comment]
1)
> 2022-10-15T17:17:30.001Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ix-[***]ev-[***]48-[***]ment"}])

After reading the logs, I have found that it crashes everything at the same time (line above), so during an import from S3 (amplify-meta.json)

2) Already tried, same problem...

**Comment by FarmerBZH** [comment]
This morning, I made other tests in order to make it works without success.

- get other credentials (not working)
- use other machines with my credentials (working)
- remove everything about aws, amplify and make a fresh install (not working)
- pull another project (working)

Despite the freeze, I can see that the files are donwloaded. If I make a checkout dev, it freezes but it works. 
If I try to push, it is not working...

**Comment by FarmerBZH** [comment]
We finally found the problem and fixed it.

Each command line of amplify (`amplify push`, `amplify pull`... ) was launching a yarn process in the background which I did not have. 

Install yarn fixed it and now I can use the amplify cli as before.

Still do not know why it was working a week ago. 

Anyway, now it is good.
