### ISSUE TITLE
Grant access to DynamoDB to a lambda function

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#11189]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Functions

**Amplify CLI Version**
10.2.1

**What AWS Services are you utilizing?**
Functions, GraphQL API, DataStore, Cognito, etc...

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

How can I setup a lambda function, for example my `postconfirmation` function to communicate with a specific Table on DynamoDB?

On my environment I was doing this on the GUI which causes problems when I upgrade something because it overrides it, this is how I did it on the web:

I created an inline policy for the function to give it permission to the DynamoDB table. Here are some pictures to make it more clear of what I did:

1. I tapped on the Execution role of the function
![image](https://user-images.githubusercontent.com/34192856/196009293-a8790b9f-0e97-402b-96a4-58fbeefdc655.png)

2. Once I tapped the above, it takes me to IAM and I tap on "Create Inline Policy"
![image](https://user-images.githubusercontent.com/34192856/196009219-ec058fdd-e276-4d5d-949e-b8b3bd7b7881.png)

3. Next I manually copy the following JSON replacing the Resource line with my DynamoDB table ARN:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem"
            ],
            "Resource": "DYANMODB_USER_ARN_GOES_HERE"
        }
    ]
}
```

4. I also on the CLI create an environment variable with the table name:
![image](https://user-images.githubusercontent.com/34192856/196010097-cbc65b38-bac2-4c90-a594-d17dbc72b400.png)

All this is done on the web, but should be done using the CLI so it doesn't gets overriden by the CLI when I do an update, how can I make such change? I mean giving the same access using the CLI?

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! There's a setting in the "advanced..." section of the `amplify update function` flow called "Resource access permissions" that can be used grant permissions to `storage`, which will then allow you to select the underlying DynamoDB table you want to access

**Comment by afern247** [comment]
Thank you
