### ISSUE TITLE
Missing pinpoint permission on category notifications

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#11194]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.2.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

notifications

### Amplify Commands

Not applicable

### Describe the bug

Adding SMS notifications that creates a pinpoint resources fails with the following error when removing the resource.

```
User: arn:aws:iam::*****:user/amplifyuser is not authorized to perform: iam:DeletePolicy on resource: policy arn:aws:iam::****:policy/pinpoint_amplify-Pl0M6imC because no identity-based policy allows the iam:DeletePolicy action
```

### Expected behavior

add delete permission on Amplify administrator policy

### Reproduction steps

1. amplify init
2. amplify add notifications
`Choose the push notification channel to enable. SMS`
3. amplify push
4. amplify remove notifications
remove SMS
then remove pinpoint resource
observe error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

e688acd3eddd4a646cc43bdea0ed1a89

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
I was able to reproduce this using an IAM user with `AdministratorAccess-Amplify` attached. I also noticed we have to run `amplify remove notification` twice, once to remove SMS and once to remove the Pinpoint resources, which felt odd given we only need to execute the `add` flow once

**Comment by ykethan** [comment]
this has been fixed.
