### ISSUE TITLE
Can't remove PostConfirmation trigger function

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#11199]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Functions

**Amplify CLI Version**
10.2.1

I'm trying to delete my lambda function and I'm getting the following:

![image](https://user-images.githubusercontent.com/34192856/196326136-feed5338-ba44-4cf3-8e5d-02ef93ce46cf.png)

I tried deleting the permissions, switching in Cognito User Pools to none the lambda PostConfirmation trigger and nothing works, I keep getting the same message. Need some help to get rid of this sticky function please

![image](https://user-images.githubusercontent.com/34192856/196326283-dc3ca309-d04c-4dc3-88b4-397325781484.png)

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! Given the Amplify CLI will generate infrastructure-as-code (IaC) we are unable to make changes to resources in the AWS Console that the Amplify project manages, and sync these changes. To proceed with removing the function, please run `amplify update auth` and de-select the "Post Confirmation trigger" option in the prompts.

This is somewhat similar to https://github.com/aws-amplify/amplify-cli/issues/10934, where we're wanting to remove resource associations when attempting to remove the linked resource.

**Comment by josefaidt** [comment]
Hey @afern247 :wave: are you still experiencing this?

**Comment by afern247** [comment]
@danielleadams I'm still experiencing this, haven't had time to take  a look since there is another question blocking this one. Please re-open

**Comment by matt-prinold-grazinga** [comment]
`amplify auth update` has no option to remove the postConfirmation lambda association, the only way that worked was to completely change my auth to a default setup and then run `amplify remove function` and then reconfigure my auth back to how it was. This is extremely bad design, and is concerning if i were to use amplify in a production environment. 

`amplify auth update` (and all update operations) should really have a cli option to remove associations without having to reconfigure your entire auth again.
