### ISSUE TITLE
unexpected messaging when executing `amplify init -y` in an initialized project

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11201]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.2.3

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

```
aws-amplify/reproductions/my-project
➜  amplify init -y
Note: It is recommended to run this command from the root of your app directory
🛑 Invalid environment name: undefined

Resolution: Environment name must be between 2 and 10 characters, and lowercase only.
```

### Expected behavior

CLI should print a helpful warning

```
aws-amplify/reproductions/my-project
➜  amplify init -y
⚠️ Warning: project is already initialized
```

```
aws-amplify/reproductions/my-project
➜  amplify init -y
⚠️ Warning: Amplify project detected in this directory
```

```
aws-amplify/reproductions/my-project
➜  amplify init -y
⚠️ Warning: an Amplify project already exists in this directory
```

### Reproduction steps

1. `amplify init -y`
2. `amplify init -y`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Was able to reproduce the issue when running `amplify init -y` on an existing environment. 

Project Identifier: ae0b0f021127375a8cab89b09e712c52

**Comment by lindanip** [comment]
@josefaidt Im experiencing the same issue with `amplify init -y`, where you able to resolve or get help with this error?

**Comment by josefaidt** [comment]
closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/11579
