### ISSUE TITLE
Backend fails to initialize on preview branches

### ISSUE THREAD

**Issue by MiguelFERREIRA-1** [aws-amplify/amplify-cli#11202]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

10.2.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual change made

### Amplify Categories

hosting

### Amplify Commands

pull, push

### Describe the bug

When the preview for a branch tries to build the backend, it fails after it tries to initialize it.

### Expected behavior

Build successfully 

### Reproduction steps

1. Let an environment be created automatically from a GitLab merge request.
2. Wait for the preview to build 
3. Fail
![b8f67551-63c8-43b7-9cdb-387e0ff0d04f](https://user-images.githubusercontent.com/79586891/196504056-f2645d74-72e6-43e2-b8b9-ef90087c1ec6.jpg)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

2cca28720ab91624ef72f6d7667b5619

### Log output

<details>

```
# Put your logs below this line
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>3600</X-Amz-Expires>
<Expires>2022-10-18T13:46:32Z</Expires>
<ServerTime>2022-10-18T17:37:53Z</ServerTime>
<RequestId>2DYE5S6KVJ2W6JDC</RequestId>
<HostId>UMuv5RZqOUozQAEbNGDoJZoVorXoQWIUVUHUmXgO7eDqLhrb6tT42n7CSW3UeYYFJh5I17z5nvg=</HostId>
</Error


```

</details>

**Comment by josefaidt** [comment]
Hey @MiguelFERREIRA-1 :wave: thanks for raising this! As we begin to look into this issue could you describe what sort of changes you were looking to merge? Was this a new Lambda?

**Comment by MiguelFERREIRA-1** [comment]
Hello josef, no we were just trying to push frontend changes but for some reason our backend is failing during the build process
Just redeploying any of the pr branches that have failed causes this issue

**Comment by josefaidt** [comment]
Hey @MiguelFERREIRA-1 :wave: thanks for clarifying! From your project captured with `amplify diagnose`, I see you have `auth` and `storage` resources that have not been migrated. We introduced a resource migration in Amplify CLI version 7 iirc.

Would you mind trying this after migrating the resources with `amplify update auth` and `amplify update storage`? Each of these flows will prompt you to migrate the resource, and afterwards we should see a new `cli-inputs.json` file in place of `parameters.json`

**Comment by MiguelFERREIRA-1** [comment]
We managed to solve the issue. Thank you :)
