### ISSUE TITLE
amplify codegen crashes on Query with "primitive" return type

### ISSUE THREAD

**Issue by sgruessinger** [aws-amplify/amplify-cli#1121]
**Describe the bug**
amplify codegen crashes when query has a primitive return type (String / Int / Boolean).
Queries returning custom-types: - no problem there.

**To Reproduce**
1. Create a query in your schema like
`type Query {
   ...
   getMyNumber: Int
}`
2. run `amplify codegen`
3. See error

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 73.0.3683.86

**Additional context**
Error log from the shell
√ Downloaded the schema
√ Generated GraphQL operations successfully and saved at src\graphql
- Generating2019-03-26T07:11:10.773Z - error: uncaughtException: Cannot read property 'map' of undefined date=Tue Mar 26 2019 08:11:10 GMT+0100 (Mitteleuropäische Zeit), pid=26996, uid=null, gid=null, cwd=C:\Users\myusername\source\repos\myProject, execPath=C:\Program Files\nodejs\node.exe, version=v8.15.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\bin\amplify, codegen], rss=142589952, heapTotal=119484416, heapUsed=85017960, external=324182, loadavg=[0, 0, 0], uptime=1205738, trace=[column=17, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\typescript\codeGeneration.ts, function=Object.propertiesFromFields, line=289, method=propertiesFromFields, native=false, column=22, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts, function=interfaceDeclarationForOperation, line=77, method=null, native=false, column=5, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts, function=Object.values.forEach.operation, line=46, method=operation, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=37, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts, function=generateTypes, line=45, method=null, native=false, column=3, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts, function=Object.generateSource, line=35, method=generateSource, native=false, column=18, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\generate.ts, function=generate, line=106, method=null, native=false, column=7, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen\src\commands\types.js, function=projects.forEach, line=49, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=14, file=C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen\src\commands\types.js, function=generateTypes, line=24, method=null, native=false], stack=[TypeError: Cannot read property 'map' of undefined,     at Object.propertiesFromFields (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\typescript\codeGeneration.ts:289:17),     at interfaceDeclarationForOperation (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts:77:22),     at Object.values.forEach.operation (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts:46:5),     at Array.forEach (<anonymous>),     at generateTypes (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts:45:37),     at Object.generateSource (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\angular\index.ts:35:3),     at generate (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-graphql-types-generator\src\generate.ts:106:18),     at projects.forEach (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen\src\commands\types.js:49:7),     at Array.forEach (<anonymous>),     at generateTypes (C:\Users\myusername\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-codegen\src\commands\types.js:24:14)]`

**Comment by yuth** [comment]
The fix is released  is Amplify CLI 1.6.2
