### ISSUE TITLE
Copy the login key then paste it into the CLI to manually login

### ISSUE THREAD

**Issue by kumar-collab** [aws-amplify/amplify-cli#11221]
**Which Specific Feature is your question related to?**
amplify pull --appId xxxx --envName staging

Couldn't automatically log you into the Amplify CLI
Copy the login key then paste it into the CLI to manually login.

**Provide additional details e.g. code snippets**

![screenshot](https://user-images.githubusercontent.com/59207084/195915690-dcf0b2f5-ecb6-46e2-8794-c9480763e50f.PNG)

**Comment by josefaidt** [comment]
Hey @kumar-collab :wave: thanks for raising this! As we begin to investigate this I have a few follow-up questions:

- what version of the CLI are you using?
- how was the CLI installed?
- are you hitting "enter" in the CLI prompt when attempting to pull the app?

**Comment by kumar-collab** [comment]
what version of the CLI are you using?

Sanjiv:/MVS/release1 (master) $ aws --version                                                                                                                                                                                                       
aws-cli/1.19.112 Python/2.7.18 Linux/4.14.294-220.533.amzn2.x86_64 botocore/1.20.112 

how was the CLI installed?
npm install -g @aws-amplify/cli

Are you hitting "enter" in the CLI prompt when attempting to pull the app?
yes

**Comment by kumar-collab** [comment]
I have tried the following as well.

1. amplify diagnose --auto-send-on
2. Sanjiv:/MVS/app/project1018 (master) $ amplify pull --appId ddz38i3fxhc48 --envName staging

Learn more at https://docs.amplify.aws/cli/reference/diagnose/

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
⠋ Creating Zip
File at path: '/MVS/app/project1018/amplify/backend/backend-config.json' does not exist
✖ Creating Zip

**Comment by ykethan** [comment]
Hey @kumar-collab, tried replicating the this in Amazon Linux 2 instance and using the AWS instance connect mechanism to SSH into the instance. Observed the following.

on running a headless amplify pull the CLI prompts for the following.
```
Confirm login in the browser or manually paste in your CLI login key:
```
as the terminal does not support opening a new tab in the browser the terminal stays on the prompt. 
on hitting enter I observe the following. 

```
⠼ Confirm login in the browser or manually paste in your CLI login key:
🛑 Failed to authenticate with Amplify Studio: Provided token was invalid.
✔ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · no
? Select the authentication method you want to use: (Use arrow keys)
❯ Amplify Studio 
  AWS profile 
  AWS access keys 
```
does this align with what you are experiencing?

additionally, on selecting the profile and access key options do you also experience the following errors?
```
🛑 Invalid config undefined
Failed to get profile: Cannot read property 'accessKeyId' of undefined
```

**Comment by kumar-collab** [comment]
Hey @ykethan . This aligns with the issue. 
However it got resolved by installing a package.
After you install the package - sudo yum -y install xdg-utils
you can copy the CLI login key and then proceed

**Comment by JKKholmatov** [comment]
![image_2023-05-23_16-49-13](https://github.com/aws-amplify/amplify-cli/assets/98150894/c9665d66-b41c-437f-a8a6-b1cf0a488c7c)
I am not able to paste the login key to terminal, it is not accepting any manual entries, how to paste the key?

**Comment by ykethan** [comment]
Hey @JKKholmatov, could you let us know what browser are you utilizing? when running this command, which should open a new tab in the browser does it provide a CLI login key or a prompt to select `yes or no`. 
I was unable to reproduce the behaviour when utilizing windows powershell.

**Comment by JKKholmatov** [comment]
> Hey @JKKholmatov, could you let us know what browser are you utilizing? when running this command, which should open a new tab in the browser does it provide a CLI login key or a prompt to select `yes or no`. I was unable to reproduce the behaviour when utilizing windows powershell.

Hi! @ykethan Thank You for your quick response, I appreciate it.
Browser: Chrome
New tab: Provided CLI login key to copy paste.
After a while, i successfully logged in , it was my bad sorry.
I tried "ctrl + v" to paste in VSCode terminal, but then I found out that i should use "ctrl + shift + v"))

**Comment by elkee2003** [comment]
> > Hey @JKKholmatov, could you let us know what browser are you utilizing? when running this command, which should open a new tab in the browser does it provide a CLI login key or a prompt to select `yes or no`. I was unable to reproduce the behaviour when utilizing windows powershell.
> 
> Hi! @ykethan Thank You for your quick response, I appreciate it. Browser: Chrome New tab: Provided CLI login key to copy paste. After a while, i successfully logged in , it was my bad sorry. I tried "ctrl + v" to paste in VSCode terminal, but then I found out that i should use "ctrl + shift + v"))

After copying the CLI login key, where do I paste it? in the vscode terminal that is already running? If yes, I tried pasting by using "ctrl + shift + v" but it is not working. I also tried using "ctrl + v". Thank you as I await a favourable response

**Comment by JKKholmatov** [comment]
> After copying the CLI login key, where do I paste it? in the vscode terminal that is already running? If yes, I tried pasting by using "ctrl + shift + v" but it is not working. I also tried using "ctrl + v". Thank you as I await a favourable response

Yes copy the key and paste it to the running VSCode terminal after `CLI login key:`
![image_2023-05-25_10-14-10](https://github.com/aws-amplify/amplify-cli/assets/98150894/21cbb31b-2880-449e-b208-d68f602e97dc)

In my case, "`Ctrl` + `Shift`+ `V`" worked,

**Comment by ykethan** [comment]
hey @elkee2003, as @JKKholmatov had pointed out you may not see the token pasted. In my reproduction windows 11 environment with terminal CMD `ctrl + c` should paste the token.
