### ISSUE TITLE
Stack name: use env name instead of date-time value

### ISSUE THREAD

**Issue by RayStroud** [aws-amplify/amplify-cli#1123]
**Is your feature request related to a problem? Please describe.**
There are two reasons why this would be helpful:
- When using multiple environments, it's difficult to find a stack for a specific environment when there are many different ones with names that don't correlate to the env name.
- Referencing resources in different stacks is very difficult without being able to [access the stack name](https://github.com/aws-amplify/amplify-cli/issues/986). If the stack names uses the environment name, it would be easy to construct it using the env name, which is already accessible in the CloudFormation templates

**Describe the solution you'd like**
- When creating a new amplify environment, make the Stack Name `<ProjectName>-<EnvName>` instead of `<ProjectName>-<DateTimeValue>`

**Describe alternatives you've considered**
- Being able to [access the stack name](https://github.com/aws-amplify/amplify-cli/issues/986) would help with referencing resources in other CloudFormation templates, but it wouldn't help being able to locate a stack in the Console for a specific environment

**Comment by joshmello** [comment]
Glad this came up!

**Comment by plaa** [comment]
Was just coming to comment the same.  Completely impossible to know which one is which:

<img width="290" alt="Screenshot 2019-04-16 at 12 46 56" src="https://user-images.githubusercontent.com/1436281/56199852-5a459e80-6046-11e9-9d13-2b39fb291d05.png">

**Comment by yuth** [comment]
@RayStroud this is in our back log and we will pick this issue in upcoming sprint once the product team prioritizes this feature

**Comment by plaa** [comment]
I guess this one is already done and should be closed?

**Comment by yuth** [comment]
We have fixed this is #1354 and released in @aws-amplify/cli@1.6.6
