### ISSUE TITLE
`amplify pull` fails if `xdg-open` is not installed on the machine

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-cli#11240]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.20

### Amplify CLI Version

10.3.1

### What operating system are you using?

Amazon AL2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

When running `pull`, I am unable to auth because my machine does not have `xdg-open` installed. I used to be able to open the browser manully and paste the auth token in manually but the CLI now gets into a bad state and I'm unable to proceed.

```
❯ amplify pull --appId d17ydzgdwzuwbl --envName prod --debug
        Opening link: https://us-west-2.admin.amplifyapp.com/admin/d17ydzgdwzuwbl/prod/verify/?loginVersion=1
⠋ Confirm login in the browser or manually paste in your CLI login key:
🛑 spawn xdg-open ENOENT

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
⠼ Confirm login in the browser or manually paste in your CLI login key:
✔ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · yes




Learn more at https://docs.amplify.aws/cli/reference/diagnose/

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
⠋ Creating Zip
File at path: '/local/home/woolumc/AmplifyStudioOnCallTool/src/AmplifyStudioOnCallTool/packages/sns-listener/amplify/backend/backend-config.json' does not exist
⠹ Confirm login in the browser or manually paste in your CLI login key:

```

Pasting just keeps showing the same prompt.

### Expected behavior

I would expect that pasting in the token should just work and I can continue with the pull.

### Reproduction steps

1. Set up a new workspace on a machine without `xdg-open`
2. Run `amplify pull --appId <appId> --env <env>`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cwoolum** [comment]
If I go back to 10.0.0, it works again

**Comment by shimomut** [comment]
In my case, where I use Amazon Linux 2 on EC2, installing xdg-utils helped to resolve this issue.

```
sudo yum -y install xdg-utils
```

**Comment by cwoolum** [comment]
Just discovered this occurs when running `amplify open` as well.
