### ISSUE TITLE
Stale node_modules on deployment package

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#11248]
**Which Category is your question related to?**

amplify function

**Amplify CLI Version**

`10.0.0`

**What AWS Services are you utilizing?**

Lambda

When I try to deploy my function with `amplify push`, the deployments are successful. However, the deployment package in the Lambda seems to have an old version of the `node_modules` folder.

This creates the following problem:

If I update or add a dependency to my Lambda, run `npm install` within it's `src` folder, everything is normal and as expected. I can even test it with `amplify mock`.

However, once it is deployed, my Lambda no long works as expected because it's dependencies within `node_modules` seem to not have been correctly deployed.

Should I be doing any additional steps to make sure the node_modules is deployed correctly?

The only workaround(which is not feasible long-term) is to delete node_modules, deploy, install node_modules and then re-deploy.

Any insights is appreciated.

Could this be a bug?

**Comment by evcodes** [comment]
Is this a new error or something that came up with 10.0.0? Was this working before?

**Comment by alexboulay** [comment]
@evcodes In the past, I didn't rely too much on npm modules and never really experienced this.
However, we now have an npm module of our own which we update and expect the latest version to be used with our Lambdas.

If i check the zip inside `function/<lambdaFunctionName>/dist`, the node_modules folder is correct. Only once deployed, it is stale. I cannot understand what is going on.

**Comment by alexboulay** [comment]
I was traspiling ts/ to /src, copying over `node_modules` while omitting to copy `package.json` and `package-lock.json

**Comment by alexboulay** [comment]
> did you use yarn lock or package lock files? 

Package lock

**Comment by biller-aivy** [comment]
> > did you use yarn lock or package lock files? 
> 
> Package lock

Just delete it, and push

**Comment by alexboulay** [comment]
> > > did you use yarn lock or package lock files?
> > 
> > 
> > Package lock
> 
> Just delete it, and push

I didnt even have package.json, so thats probably why it was not working
