### ISSUE TITLE
Update resolver template version

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/amplify-cli#1124]
The transformer currently generates AppSync templates with `2017-02-28` and should be updated to use `2018-05-29`. See: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-changelog.html

We will need to look at the enhanced error handling in the response template as part of this work to ensure no breaking changes to existing APIs.

**Comment by MathiasBerwig** [comment]
In the last few days I'm unable to push-create an new `auth` with the following error:

```
Following resources failed

Resource Name: XXX-MFALambdaInputs-XXX (Custom::LambdaCallout)
Event Type: create
Reason: Response is not valid JSON


× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
```
I've also noticed some `response.FAILURE` changed to `response.FAILED` in my `auth/xxx-clouformation-template.yml`. 

Is it possible to this error be related to the issue?

**Comment by kaustavghosh06** [comment]
@undefobj Just checked and we're using 2018-05-29 v in all our resolver files today. Closing this issue :D
