### ISSUE TITLE
Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#1125]
**Describe the bug**
After adding a new type to my schema and splitting up schema into multiple files I am now not able to push changes either from the amplify console or the cli. 

I amalgamated back to one schema file. Commented out a connection on a new type (I was getting an only one resolver per field error). 

I recently migrated to the amplify console for hosting. Not sure if that has something to do with this but I was successfully building for almost a week.   

It appears as though my custom resolvers are now what's causing the error. Here is an example snippet from the logs. All my custom resolvers are failing:

`
UPDATE_FAILED QueryListNotificationsByUserNameResolver   AWS::AppSync::Resolver Tue Mar 26 2019 16:25:47 GMT-0400 (Eastern Daylight Time) No resolver found. (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 56927d1f-5005-11e9-b233-65c6f36d1bfd)
`

**To Reproduce**
I don't know what the exact steps are to create the issue because I've done a few things in the past couple days. 

**Expected behavior**
I expect my new type with the connection to be deployed. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 1.1.7

**Comment by aireater** [comment]
It looks like the custom resolvers were all deleted from the backend. I suspect I hit an edge case and the rollback failed.

**Comment by aireater** [comment]
I created dummy missing resolvers in the AppSync and now the amplify push is successful but the resolvers are not updated.

**Comment by aireater** [comment]
The custom queries were still in AppSync but no resolvers were attached. I attached dummy resolvers in the AppSync console (kept the defaults) then ran the push again and the resolvers were updated correctly.

My hunch is that when I split up the schema into multiple files I made a mistake by not putting them into a schema folder which may have caused the issue. I will try splitting up the schema files again when I get some spare time.

**Comment by kaustavghosh06** [comment]
@aireater Were you able to troubleshoot this?

**Comment by aireater** [comment]
@kaustavghosh06 I haven't had time yet.

**Comment by mikeparisstuff** [comment]
@aireater Glad you got this working. I believe you are correct and hit an edge case where CFN referenced something it thought existed but had actually been deleted. I have seen this before when making a change where one nested stack removed resolvers and another (sibling) stack was invalid causing a rollback. The first stack successfully deleted the resolvers, the sibling failed causing the rollback, and the first stack did not recreate the resolvers that were just deleted even though CFN thought they should exist. The cure for the error you posted is to go add dummy resolvers via the AppSync console or AWS CLI and then push again to put things back in working order.

```
UPDATE_FAILED <resolver-id> AWS::AppSync::Resolver <date> (Eastern Daylight Time) No resolver found. (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: <req-id>)
```
