### ISSUE TITLE
Geo - New HERE map styles（HERE Imagery, HERE Hybrid）

### ISSUE THREAD

**Issue by inariku** [aws-amplify/amplify-cli#11261]
### Is this related to another service?

Amazon Location Service

### Describe the feature you'd like to request

Yesterday (Oct 25, 2022), Amazon Location Service (covered by the Geo category) has added two new map styles (HERE Imagery, HERE Hybrid) for the HERE provider (here the [What's New post: Announcing two new HERE map styles for Amazon Location Service](https://aws.amazon.com/jp/about-aws/whats-new/2022/10/two-new-here-map-styles-amazon-location-service/)).

Just tried to create a new map resource in a blank project using v10.3.2 and the aforementioned map styles are missing:
```

✔ Do you want to configure advanced settings? (y/N) · yes
? Specify the map style. Refer https://docs.aws.amazon.com/location-maps/latest/APIReference/API_MapConfiguration.html …  (Use arrow keys or type to filter)
❯ Streets (data provided by Esri)
  Berlin (data provided by HERE)
  Explore (data provided by HERE)
  ExploreTruck (data provided by HERE)
  Topographic (data provided by Esri)
  Navigation (data provided by Esri)
  LightGrayCanvas (data provided by Esri)
  DarkGrayCanvas (data provided by Esri)
  Imagery (data provided by Esri)
```

### Describe the solution you'd like

Be able to select the new map styles when adding a new map resource in my Amplify project:

### Describe alternatives you've considered

Creating them manually, which would defeat the purpose of the CLI.

### Additional context

Currently, the new Map Style cannot be selected even from the management console.

![Screen Shot 2022-10-26 at 17 12 44](https://user-images.githubusercontent.com/96720398/197971511-573f0e9c-15bc-4480-9f65-62bc937d8073.png)

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by evcodes** [comment]
Thanks for reporting this issue, it has been merged so I am closing this issue
