### ISSUE TITLE
Adding Sign in with Apple auth errors with can't create HostedUIProvidersCustomResourceInputs (Custom::LambdaCallout)

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/amplify-cli#11264]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.3.2

### What operating system are you using?

macOS Ventura

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no. deleted the project and tried to re run the whole install as well, just in case.

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

After adding Sign in with Apple as auth I can no longer to push. It says:

The following resources failed to deploy:
Resource Name: HostedUIProvidersCustomResourceInputs (Custom::LambdaCallout)
Event Type: create
Reason: Received response status [FAILED] from custom resource.

Tried to delete the whole thing and run it again. But same thing happens. Not suing Sign in with Apple but just email / password sign in and it works fine.

### Expected behavior

Being able to push with Sign in with Apple auth

### Reproduction steps

Add auth with Sign in with Apple.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @helloniklas, thank you for reaching. Does the Amplify CLI provide a Cloudwatch log group? 
Could you let us know the error message being displayed in the Lambda log stream from the AWS Cloudwatch console. The log group should be of format `/aws/lambda/<application name>-<environment name>- HostedUIProvidersCustomR`

**Comment by helloniklas** [comment]
Seems the issue is that when I open the p8 file and select the private key and copy, it contain a carriage return line, so when pasting it into terminal to amplify it just uses the first line of the private key then automcatically moves to the next amplify question. Making sure the key is just one long line without line breaks seem to have fixed this.

**Comment by HappyMakadiyaS** [comment]
I have also faced this issue while doing amplify push after adding Sign in with the apple.
I have tried @helloniklas  approach to provide the p8 key in the console. Provide the key in a single line by removing carriage, spaces and \n and also removed the `-----BEGIN PRIVATE KEY-----` and  `-----END PRIVATE KEY-----`. Still facing the same issue.
