### ISSUE TITLE
Nested Stacks are split based on "concern" and not on size

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-cli#1127]
**Describe the bug**
Even with the NestedStack update, it is still relatively easy to hit the Stack size limit. Specifically, it's our "Connections" stack that has recently surpassed that limit.

This is similar to, but not quite a duplicate of #185 

**To Reproduce**
Have enough connections such that they break the stack size limit

**Expected behavior**
Split connections into multiple stacks if it goes past the 450kb size limit

Would be awesome if there was logic [here](https://github.com/aws-amplify/amplify-cli/blob/4b86e18693aea9e53b87ca8a2462dc85d0dbe6b7/packages/graphql-transformers-e2e-tests/src/deployNestedStacks.ts#L85) that would look at the size of the stringified JSON, and, if necessary, split the stack again, or, if even for a quick fix, minified the json output.

If I understand how the stacks work correctly, it should work to split a stack in two with something along the following lines.
1. check if the stringified stack object is smaller than the filesize limit
1. if it is, return the stringified stack object
1. if it isn't, then split the `Resources`  property of the stack object in half, and recurse to step 1 for each half,  return result from both halves
1. take array of strings, write to disk

Here is some code that (I believe) could be used to replace lines 85-88 of the [file in question](https://github.com/aws-amplify/amplify-cli/blob/4b86e18693aea9e53b87ca8a2462dc85d0dbe6b7/packages/graphql-transformers-e2e-tests/src/deployNestedStacks.ts#L85)

```
const filesize = 460800;

const getStackStrings(stackObject) => {
  const stringified = JSON.stringify(stackObject, null, 4);
  if (stringified < filesize) {
    return [stringified];
  } else {
    const allResourceList = Object.entries(stackObject.Resources);
    const secondHalfResourceList = allResourceList.splice(Math.floor(allResources.length / 2));
    const firstHalfResourceList = allResourceList; // b/c after the splice, that's what's left
    const objReducer = (acc, [key, value]) => {
      acc[key] = value;
      return acc;
    };
    const firstHalfResourceObject = firstHalfResourceList.reduce(objReducer, {});
    const firstHalfStackObject = {
      ...stackObject,
      Resources: firstHalfResourceObject,
    };

    const secondHalfResourceObject = secondHalfResourceList.reduce(objReducer, {});
    const secondHalfStackObject = {
      ...stackObject,
      Resources: secondHalfResourceObject,
    };
    const stringifieds = [];
    stringifieds.push(getStackStrings(firstHalfStackObject));
    stringifieds.push(getStackStrings(secondHalfStackObject));
    return stringifieds.flat();
  }
}

const writeStack = (stackObject, stackName, stackRootPath) => {

  const stacksToWrite = getStackStrings(stackObject);
  stacksToWrite.forEach((stack, idx) => {
    const fullStackPath = path.normalize(stackRootPath + '/' + stackName + idx + '.json'); 
    fs.writeFileSync(fullStackPath, stack);
  })
  
};

for (const stackFileName of stackNames) {
  writeStack(deployment.stacks[stackFileName], stackFileName, stackRootPath);
}
```

**Comment by meetrij** [comment]
not working with cli version update my amplify version 1.7.4 as mention in #185

**Comment by francesco-magalini** [comment]
same issue here with the connectionStack.json.
Any update or workaround?

**Comment by kaustavghosh06** [comment]
@francesco-magalini @nagey CloudFormation announced last week a tempalte size limit increase to 1 MB from 450 KB - this would alleviate much of the template size issues specially the connectionStack.json size.

**Comment by kaustavghosh06** [comment]
If you're still hitting errors after this limit increase please feel free to comment on this thread and I'll re-open this issue.
