### ISSUE TITLE
Amplify v10x does not work in headless mode

### ISSUE THREAD

**Issue by vloermatt** [aws-amplify/amplify-cli#11279]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli@10.3.2

### If applicable, what version of Node.js are you using?

16x

### Amplify CLI Version

10.3.2

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

configure, init, pull, push, status

### Describe the bug

Installing @aws-amplify/cli in our `lts-alpine` node pipeline using the headless mode CI/CD pipeline does not work. There are no outputs or errors after supposedly succesfully installing and attempting to run commands. Example: `amplify -v` has no output - not even `command not found`

We've recently had to upgrade the amplify/cli version used due to the deprecated python runtime used by the OpenSearchStreamingLambda. The last stable amplify/cli version we used in the pipeline was v7.6.26. I can confirm that all major versions following v7 does not perform as expected in our pipeline. 

### Expected behavior

We expect the CLI to be installed succesfully in the pipeline in order to execute amplify commands in headless mode

### Reproduction steps

1. Create a docker image from the `node:lts-alpine` image (or any node image for that matter) 
2. add `RUN npm install -g @aws-amplify/cli` to the DockerFile , or alternatively run the image and try installing manually using the CLI
3. Running amplify commands should yield no output 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I believe a [simlar issue](https://github.com/aws-amplify/amplify-cli/issues/10193) was experienced on Apple M1 machines

**Comment by edwardfoyle** [comment]
Hi @vloermatt this sometimes happens if the machine you are running on has a security policy that blocks the execution of binaries downloaded from the internet. The Amplify binary is placed at `~/.amplify/bin/amplify`. Can you check that your system is allowing execution of the binary?

**Comment by vloermatt** [comment]
Hi @edwardfoyle thanks for the response. I can confirm the binary is not executable. Getting output `cannot execute binary file`

**Comment by edwardfoyle** [comment]
@vloermatt in that case you will need to allow execution of the binary in your system settings.

I'm going to close this out but let us know if you run into additional issues after enabling execution of the binary.

**Comment by vloermatt** [comment]
Hi @edwardfoyle we tried making the binary executable by running `chmod +x amplify` - Still yielding the same unexpected results with no output from amplify-cli commands
