### ISSUE TITLE
Amplify v 10.4.0: 'No Amplify backend project files detected within this folder' in Amplify Console. No issues with previous versions.

### ISSUE THREAD

**Issue by hackmajoris** [aws-amplify/amplify-cli#11278]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.15.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

hosting

### Amplify Commands

env

### Describe the bug

Amplify v 10.4.0: 'No Amplify backend project files detected within this folder' in Amplify Console. No issues with previous versions.

### Expected behavior

Should found the backend environment.

### Reproduction steps

1. Upgrade to Amplify v10.4.0

### Log output

<details>

```
# Put your logs below this line

                                 [0mTag Changes Detected[0m
2022-10-27T22:47:33.242Z [INFO]: 
2022-10-27T22:47:33.265Z [INFO]: 🛑 No Amplify backend project files detected within this folder.
2022-10-27T22:47:33.266Z [INFO]: Resolution:
                                 Either initialize a new Amplify project or pull an existing project.
                                 - "amplify init" to initialize a new Amplify project
                                 - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
2022-10-27T22:47:33.598Z [ERROR]: !!! Build failed
2022-10-27T22:47:33.598Z [ERROR]: !!! Non-Zero Exit Code detected
2022-10-27T22:47:33.598Z [INFO]: # Starting environment caching...
2022-10-27T22:47:33.599Z [INFO]: # Environment caching completed
Terminating logging...
```

</details>

### Additional information
Project Identifier: a88954c5b3c47e78dce85b3e0fd819c8
_No response_

**Comment by edwardfoyle** [comment]
Hi @hackmajoris are you using the default amplify console build script or have you made any modifications? If you have made modifications, do you mind sharing your build script here?

**Comment by hackmajoris** [comment]
@edwardfoyle I have the same script https://github.com/aws-amplify/amplify-hosting/blob/main/scripts/amplifyPush.sh at the project level, and I call them like ./amplifyPush --simple. It's not modified. It looks like the result is different, because I did try with the default one and it works. I don't get why it's a different behavior. Could you tell?

**Comment by josefaidt** [comment]
Hey @hackmajoris :wave: thanks for raising this! Are you still experiencing this issue? Can you describe the changes made prior to upgrading the CLI and whether you are also using [Amplify Hosting's monorepo support](https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html)?

**Comment by hackmajoris** [comment]
@josefaidt Yes, it's a monorepo project configured with monorepo settings.

**Comment by josefaidt** [comment]
Hey @hackmajoris thanks for clarifying! Would you mind posting the monorepo spec you're using for Amplify Hosting? I believe this will look for an `amplify` directory at the specified `appRoot`, which may be pointing to the wrong directory

**Comment by hackmajoris** [comment]
> Hey @hackmajoris thanks for clarifying! Would you mind posting the monorepo spec you're using for Amplify Hosting? I believe this will look for an `amplify` directory at the specified `appRoot`, which may be pointing to the wrong directory

Here is are the configs:


At the console Environment Variables: `AMPLIFY_MONOREPO_APP_ROOT = apps/passbrains`

At the amplify.yml

```
version: 1
applications:
 - appRoot: apps/passbrains
   frontend:
       ....
   backend:
       ....
```

Let me know if you need more details.

**Comment by hackmajoris** [comment]
I'll close the issue. I figured out that I have some npm scripts which were called, and they changed the current directory. 
It works for Amplify versions < 10.4.0. 

The solution was to add amplifyPush --simple as a npm script in the base packages.json and run the script instead of amplifyPush --simple. This way it is assured that it will run always from the right directory.
