### ISSUE TITLE
amplify publish needs "hosting add" and crashed when publish 2

### ISSUE THREAD

**Issue by emeryaa** [aws-amplify/amplify-cli#1129]
`amplify publish`

Please add hosting to your project before publishing your project
Command: amplify hosting add

`amplify add hosting`
Hosting is already fully enabled.

`amplify remove hosting`
No resources added for this category

This is updated version of CLI

**Comment by UnleashedMind** [comment]
@emeryaa 
I need more information to investigate this issue, please do the following: 

1. remove and reinstall your amplify CLI, to make sure it is not in a corrupted state: 
```bash
$ npm remove -g @aws-amplify/cli
$ npm install -g @aws-amplify/cli
```
2. take a screen shot of the folder structure in inside `amplify/backend`
3. send the screen shot to me at zhoweimi@amazon.com
4. send the file `amplify/backend/amplify-meta.json` to me at zhoweimi@amazon.com

**Comment by kaustavghosh06** [comment]
@emeryaa Please delete the hosting folder in amplify/backend/hosting directory and try adding hosting using the CLI again.

**Comment by emeryaa** [comment]
Sorry for spam at other topics. I just dont understand who may delete my
issues about that. I will send you all info with screenshots within minutes.

**Comment by emeryaa** [comment]
I had reinstall amplify and sent you data in the attach as you request

**Comment by emeryaa** [comment]
Delete hosting folder and add it again  it helps.  But how I can restore
settings of api and auth products? I need configure it manualy again? From
admin panel of aws? as I do it before, when I had crashed publish project
at time before?

At time before I had configure again facebook authorization, cognito auth.
api schema, api resolvers and etc. Reason of it. Crashed publish project
with amplify publish command at the CLI. and Cycle of errors with adde
hosting to the project.

**Comment by UnleashedMind** [comment]
@emeryaa 
I did not receive your emails.

**Comment by emeryaa** [comment]
New issue with execute codegen api. Screenshot attached

**Comment by emeryaa** [comment]
![image](https://user-images.githubusercontent.com/26538670/55099343-f67c2580-50d8-11e9-8ada-021eee18503a.png)

**Comment by emeryaa** [comment]
Delete API folder from backend and execute codegen is not helps

![image](https://user-images.githubusercontent.com/26538670/55099651-7e622f80-50d9-11e9-9213-a4b5c34f1fa8.png)

**Comment by emeryaa** [comment]
Structure of folders

![image](https://user-images.githubusercontent.com/26538670/55099791-cd0fc980-50d9-11e9-8e90-3863f3e16d9c.png)

**Comment by emeryaa** [comment]
how I can restore
settings of api and auth products?

**Comment by UnleashedMind** [comment]
I need to check your amplify-meta.json, backend-config.json, and team-provider-info.json files, please send them over through email so I can investigate this issue.

**Comment by emeryaa** [comment]
Please check it in attach

**Comment by emeryaa** [comment]
Any update here?

**Comment by UnleashedMind** [comment]
We will investigate this issue further, but for now, delete the file ".graphqlconfig.yml" and then run `amplify codegen add --apiId <the-appsync-project-id>`

**Comment by emeryaa** [comment]
It's not working. Just a shit! I spend my time to meet with that soft from amazon. and I have to pay money to amazon for his services! It s not fucking opensource garbage when you get it all for free. I just confuse that service like amazon have such silly errors at his software.
I spend my time to meet with that soft and I want working decision for that issue and I dont want to meet the CLI of other services. 

as Amazon support team member you must to know how to make it work

If words has ends will start the war.

**Comment by emeryaa** [comment]
![image](https://user-images.githubusercontent.com/26538670/55212365-eb281780-5208-11e9-9f9b-a87bb3fdfa15.png)

**Comment by kaustavghosh06** [comment]
Hello @emeryaa . Sorry you're having difficulties. We want to help make you successful, however we do want all community members to communicate with each other and ask for help in a respectful manner. Please do be aware we have a Code of Conduct that should be followed: https://github.com/aws-amplify/amplify-js/blob/bfa477662591bbd7a92bbb8486778924589e4adb/.github/CODE_OF_CONDUCT.md

Please follow the following steps to get your API  in the Amplify Project using the codegen command.

1) First delete the `<amplify-project-root>/.graphqlconfig.yml` file (This step is very crucial since this will get rid of your inconsistent project state)

2) Run `amplify codegen add --apiId <the-appsync-project-id>` (Please don't run any other command like `amplify add codegen` or `amplify codegen` before running this command)

If you're not successful with this command. Please let me know the contents of your `<amplify-project-root>` directory and your terminal logs so that I can further assist you.

**Comment by emeryaa** [comment]
Yes, but I too confuse why amazon have such silly errors with his soft. This make me some nervous. 
Look, today to made modern a website for the world. I need to know JS, be able to project the db, know some of one backend language like a python,ruby, golang, php, need to know how to build apis, maybe later I need to know some additinal language for external fishes. And do I need to fight with such respectful service like amazon? Which it have a lot of services at his stack. And his CLI?? what is it?? Why it make me so nervous? Its basic functions! wtf??!

**Comment by emeryaa** [comment]
Yes, and Im not successful with this command. Its not working for me like I said before

this my files at the root directory

![image](https://user-images.githubusercontent.com/26538670/55263949-30d9f400-528c-11e9-93f6-63ead70fd640.png)

this like I execute commands in command line interface

![image](https://user-images.githubusercontent.com/26538670/55264084-a776f180-528c-11e9-9d84-d957f3a8cc26.png)

I just newly execute `amplify init`  `then amplify codegen add --apiId <the-appsync-project-id>`
Its not working for me!

**Comment by emeryaa** [comment]
Please update your software ASAP. I need to publish my website to aws. I want to pay my money to amazon and respectivly to you.

**Comment by kaustavghosh06** [comment]
@emeryaa Sometimes you can't view `.*` files on your editor. So, I would recommend removing it from the terminal using `rm .graphqlconfig.yml` command from your project root and then running `amplify codegen add --apiId <the-appsync-project-id>`

**Comment by emeryaa** [comment]
Fuck that I had remove this file from directory. It not helps

**Comment by emeryaa** [comment]
amplify codegen remove
then
amplify codegen add --apiId <the-appsync-project-id>

but api dont work with this configuration
[{"message":"Request failed with status code 401"}]

I have newly created auth and api. and manualy copy paste settings at admin panel of aws

**Comment by Rolando-Barbella** [comment]
Deleting `amplify/backend/hosting` and trying again, worked for me
