### ISSUE TITLE
React Tutorial GraphQL API addition does not authenticate

### ISSUE THREAD

**Issue by lahirian** [aws-amplify/amplify-cli#113]
**Describe the bug**
Following the steps as described in the section to add GraphQL backend in the react tutorial Appsync is not linked to the correct Cognito user pool.

**To Reproduce**
1. Following the steps as described in the section to add GraphQL backend in the react tutorial (https://github.com/aws-amplify/amplify-cli/blob/master/amplifycli_react_tutorial.md#add-graphql-backend)  
2. On the resulting web page click on GraphQL modification button. 
3. Nothing happens.
4. Developer console shows cognito failure.
5. AWS console shows that the settings in AppSync is pointing to a default Cognito pool called AppSyncUserPool and not the application specific user pool created in https://github.com/aws-amplify/amplify-cli/blob/master/amplifycli_react_tutorial.md#add-user-registration-and-sign-in
6. Once it is changed from console for AppSync to point to correct Cognito user pool it works.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@lahirian  Just submitted a fix for this -> #119
