### ISSUE TITLE
How to specify sortkey for dynamodb

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-cli#1130]
How can specify sort key e.g.

type Post @model {
    id: ID! # id: ID! is a required attribute.
    title: String!
    tags: [String!]!
}

How can i specify title as sort key ?

**Comment by kaustavghosh06** [comment]
@vjindalaurea We don't have that support yet, but we have an RFC for this feature which we're currently working on this feature based off this RFC - #1043

**Comment by kwhitejr** [comment]
Is there a known workaround?

**Comment by mikeparisstuff** [comment]
You cannot set the sort key on the table but you can create indexes with sort keys set using `@connection`. As mentioned above we are working on improving the indexing experience with DynamoDB and that will be updated in the RFC.

**Comment by marcschroeter** [comment]
is there an idea when you will support sortkeys?

**Comment by mikeparisstuff** [comment]
There is not set release date but updates will be put in this RFC #1062.

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.

**Comment by Liguo-Ma** [comment]
Hello how are you
type Conversation @model
{
  id:ID!
  messages:[Message]@connection(sortField: "createdAt",limit:50,keyName:"conversationMessage",fields:["id"])
  badge:Float
}
type Message @model
@key(name: "conversationMessage", fields: ["conversationId"],queryField: "getMessageByConversationId")
{
  id:ID!
  content:String!
  conversationId:ID!
  createdAt:AWSDateTime!
}
This is my database
I want to get conversation with messages that are sorted by createdAt
I tried like that but I cannot get "conversation" with messages that are sorted by createdAt
What is wrong with my database?
