### ISSUE TITLE
Amplify CLI lets you pick Singapore but when I try to use it via the console it says it's not available

### ISSUE THREAD

**Issue by tkdtaylor** [aws-amplify/amplify-cli#1132]
Specify the AWS Region
? region:
   us-east-1
   us-east-2
   us-west-2
   eu-west-1
   eu-central-1
   ap-northeast-1
 **>ap-southeast-1**
   ap-southeast-2
   ap-south-1

From the Console:

Region Unsupported
AWS Amplify is not available in Asia Pacific (Singapore). Please select another region.

Supported Regions
EU (London)
EU (Ireland)
Asia Pacific (Sydney)
US East (N. Virginia)
US East (Ohio)
US West (Oregon)

**Comment by swaminator** [comment]
The Amplify Console is currently not available in Singapore. Please create your app in the nearest supported region. Let me know if you face any difficulties.

**Comment by UnleashedMind** [comment]
@tkdtaylor 
Thanks pointing this out. 
Amplify Framework (the CLI and the Libraries) and the Amplify Console are two independent offerings from the Amplify family. Apparently, there's this discrepancy in the supported regions. I've notified the Amplify Console team about this.

**Comment by tkdtaylor** [comment]
Thanks @swaminator and @UnleashedMind for the feedback, I'll try to get in touch with the Console team to see if they know when the Console will be available in Singapore.
