### ISSUE TITLE
Amplify v10x still does not work in headless mode

### ISSUE THREAD

**Issue by vloermatt** [aws-amplify/amplify-cli#11331]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli@10.3.2

### If applicable, what version of Node.js are you using?

16x

### Amplify CLI Version

10.4

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

init, pull, push, status

### Describe the bug

Apologies for submitting another issue. [This issue](https://github.com/aws-amplify/amplify-cli/issues/11279) was closed but not resolved. No response on my latest feedback there. This is blocking us from releasing via our pipelines. We've tried making the amplify binary executable, but we're still not seeing any outputs from amplify commands.

Installing @aws-amplify/cli in our lts-alpine node pipeline using the headless mode CI/CD pipeline does not work. There are no outputs or errors after supposedly successfully installing and attempting to run commands. Example: amplify -v has no output - not even command not found

We've recently had to upgrade the amplify/cli version used due to the deprecated python runtime used by the OpenSearchStreamingLambda. The last stable amplify/cli version we used in the pipeline was v7.6.26. I can confirm that all major versions following v7 do not perform as expected in our pipeline.

### Expected behavior

We expect the CLI to be installed successfully in the pipeline in order to execute amplify commands in headless mode

### Reproduction steps

1. Create a docker image from the `node:lts-alpine` image (or any node image for that matter)
2. add RUN `npm install -g @aws-amplify/cli` to the DockerFile, or alternatively run the image and try installing manually using the CLI
3. Attempt to make the amplify binary executable by executing `chmod +x amplify` In the `~/.amplify/bin/amplify` directory

 Attempting to execute amplify commands should now yield no results

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
@vloermatt by any chance does installing with our curL script give a different result? It's possible the post-install script is failing for some reason. [Installation docs](https://docs.amplify.aws/cli/start/install/).

`curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL`

**Comment by vloermatt** [comment]
Hi @jhockett Thanks for the response. I've tried that before but would get an error stating that the binary cannot be found and that I should try using `npm`

However, I've managed to install the CLI on an amazon linux 2 image. It seems to be working in the pipeline. But now we are running into this error `The "path" argument must be of type string. Received undefined`. The is directly after the pipeline successfully pulls the backend environment. I've seen simular issues [here](https://github.com/aws-amplify/amplify-hosting/issues/2306) and also [here](https://github.com/aws-amplify/amplify-cli/issues/6227). But their resolutions yield no positive results for us

**Comment by vloermatt** [comment]
I should note that the docker image I used in our pipeline is based on the image used for builds when using amplify hosting. I tried deploying there and got the exact same error

**Comment by vloermatt** [comment]
Hi @ykethan It seems to be working. But it's very unstable. Pipelines succeed and then fail unexpectedly when trying to init. We're now seeing the `The "path" argument must be of type string. Received undefined` error again after just one successful deploy

**Comment by ykethan** [comment]
Hey @vloermatt, interesting. In order to dive deeper into the behaviour could you provide usthe following information.
1. Information on what the pipeline does.
2. Could you provide us the Amplify project identifier by running `amplify diagnose --send-report` in the root of your local Amplify application.
