### ISSUE TITLE
How to reset amplify build - envCache

### ISSUE THREAD

**Issue by artista7** [aws-amplify/amplify-cli#1133]
**Describe the bug**
I re-created dev environment using amplify cli and when i pushed the changes, amplify console was picking old stackInfo from envCache. I can't find any documentation of how to prevent using old cached values. Below are the logs:-

**logs**

//Getting Amplify CLI Cloud-Formation **stack info from environment cache
2**019-03-27T13:32:53.066Z [INFO]: # Start initializing Amplify environment: dev
2019-03-27T13:32:53.068Z [INFO]: STACKINFO={
    "awscloudformation": {
        "AuthRoleName": "old-authRole",
        "UnauthRoleArn": "arn:aws:iam::old-unauthRole",
        "AuthRoleArn": "arn:aws:iam::old-authRole",
        "Region": "us-east-1",
        "DeploymentBucketName": "old-deployment",
        "UnauthRoleName": "old-unauthRole",
        "StackName": "old",
        "StackId": "arn:aws:cloudformation:us-east-1:227484579606:stack/old"
    },
    "categories": {
        "auth": {
            "cognitols": {}
        }
    }
}
// Importing Amplify environment: dev (amplify env import)
2019-03-27T13:32:55.802Z [INFO]: Successfully added environment from your project
2019-03-27T13:32:55.809Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2019-03-27T13:32:57.242Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-03-27T13:32:58.538Z [WARNING]: - Initializing your environment: dev
2019-03-27T13:32:58.612Z [WARNING]: ✖ There was an error initializing your environment.
2019-03-27T13:32:58.613Z [INFO]: init failed
2019-03-27T13:32:58.616Z [INFO]: { NoSuchBucket: The specified bucket does not exist

**Comment by garyleefight** [comment]
@artista7 Hi, you can add -envCache --set stackInfo '' in the build spec, which will reset the envCache.

**Comment by garyleefight** [comment]
The example buildSpec looks like:
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by UnleashedMind** [comment]
Closing for now, comment on this if you still have the problem, we can re-open it.

**Comment by artista7** [comment]
Cool. Let me try

**Comment by patspam** [comment]
Please add this to the documentation, I got bitten by this too and it wasn't at all clear how to clear the cache.

**Comment by dabit3** [comment]
@garyleefight Hi, can you update your comment to use markdown code format?

It's kind of hard to read in the above format. Thanks for the info, it helps a lot!
