### ISSUE TITLE
Amplify CLI push, status not working on Ventura

### ISSUE THREAD

**Issue by iThink32** [aws-amplify/amplify-cli#11338]
I've tried to add an api on Ventura via the amplify cli but it fails. The error is as shown below.

The following errors occurs on every command I try and is bypassed by preceding it with sudo 
 EACCES: permission denied, open '.../.amplify/logs/amplify-cli-2022-11-05.log'
 
 The following line always shows up in read indicating an error
 
 ```
 MFALambda                      AWS::Lambda::Function          UPDATE_
 ```

 and the final error is
``` 
 The following resources failed to deploy:
Resource Name: MFALambda (AWS::Lambda::Function)
Event Type: update
Reason: Template error: IAM role ...ac_totp_lambda_role-preprod doesn't exist
URL: some long url


🛑 Resource is not in the state stackUpdateComplete

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

✅ Report saved: .../report-1667660570512.zip

the same when tried on an older version of Amplify works fine.

I followed this issue and used the workaround

https://github.com/aws-amplify/amplify-cli/issues/10640

Version of CLI facing the issue: the latest one installed when you run npm install -g @aws-amplify/cli
Version of CLI working fine: 8.0.0

**Comment by josefaidt** [comment]
Hey @iThink32 :wave: thanks for raising this! Would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml)? By doing so, this helps us gather additional context around your issue to effectively diagnose the issue

**Comment by iThink32** [comment]
@josefaidt this is the bug report, please do the needful https://github.com/aws-amplify/amplify-cli/issues/11446
