### ISSUE TITLE
There was an error initializing your environment. 🛑 Could not initialize platform for 'dev': invalid distance too far back

### ISSUE THREAD

**Issue by shubhankar-pandey** [aws-amplify/amplify-cli#11337]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

10.4.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Stopped the operation from pushing once after that the issue persisted.

### Amplify Categories

function, api

### Amplify Commands

env, pull, push

### Describe the bug

So had a breaking change in graphql file so what i did is reverted it using amplify pull.
 **At First pull it was successful after which error persisted!**
And show
`There was an error initializing your environment. 🛑 Could not initialize platform for 'dev': invalid distance too far back`

Error. Tried Many thing Deleted and reinstalled didn't worked. Pull not working in any case

### Expected behavior

Too get pushed correctly and able to pull changes

### Reproduction steps

1.Create a amplify project with react native
2. Add graphql schema (with breaking changes) and lamda function
3. `amplify push` then stop it before completion when it started uploading
4.  `amplify pull` the app
5. then push again with new graphql schema without breaking changes

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kieferenriquez** [comment]
Hey guys, 

Sadly 22 Jun 2023 few months after, amplify cli version 12.1.1 aws-cli/2.11.16 I am still getting error above.

I updated API > graphql schema but reverted all changes back as I thought the issue was because of that, apparently still getting the same exact issue as people above:

on amplify push
🛑 The provided token is malformed or otherwise invalid.

on amplify pull
🛑 Could not initialize platform for 'dev': The provided token is malformed or otherwise invalid.

Hope you guys can find solution here.

Cheers,
Kiefer
