### ISSUE TITLE
amplify publish needs "hosting add" and crashed when publish

### ISSUE THREAD

**Issue by emeryaa** [aws-amplify/amplify-cli#1134]
`amplify publish`
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

After crashed when publish project to aws I had init new amplify configuration
After that I don't seee any data before added to the project by amplify status

Api
Auth

I have these files at project dir

image

amplify publish still do not usable for publish project

**Comment by kaustavghosh06** [comment]
Duplicate issue.
