### ISSUE TITLE
Any change to a storage cloudformation.json template introduces invalid characters

### ISSUE THREAD

**Issue by tncbbthositg** [aws-amplify/amplify-cli#1135]
**Describe the bug**
I need to modify my storage cloudformation.json so that I can add a bucket policy after my storage bucket is created.  If I change anything about the file (including whitespace), I can no longer `amplify push` any changes.  I get this:

```UPDATE_FAILED               storageuserdata                     AWS::CloudFormation::Stack Wed Mar 27 2019 18:48:40 GMT-0400 (EDT) Template contains invalid characters```

**To Reproduce**
1. `amplify add storage`
2. Edit the `s3-cloudformation-template.json` file
3. `amplify push`
5. Revert change
6. `amplify push`
7. Continue seeing error
8. Cry a little inside
9. Out of desperation add a blank line to the top of the json file.
10. `amplify push`
11. See error yet again
12. Remove blank line from top of file
13. `amplify push`
14. "All resources are update in the cloud"
15. Manually remove hair from top of head

**Expected behavior**
I would expect the cloud formation file to be valid after adding valid CF JSON.  If nothing else, I would expect the file to be valid after reverting it to its original state.

**Desktop (please complete the following information):**
 - OS: OS X

**Additional context**
Editor: VIM

Amplify CLI version: 1.1.7
In addition to storage, this application includes Auth, Analytics, and an Api.  It's a react native application.

The issue, however, does not appear to be related to the application.  Indeed the issue is reproducable in a blank application.

Edit: It may be .swp file related.  Once I finish making the changes I'm working on, I'll try testing that theory.

**Comment by UnleashedMind** [comment]
I can not reproduce what you said: "If I change anything about the file (including whitespace), I can no longer amplify push any changes. :
Is it possible you that put some invalid changes to the template? 
If you can share with us your template, we will help you to dig deeper into the issue.

**Comment by tncbbthositg** [comment]
@UnleashedMind, I changed editors.  I think it's because of the swap file VIM creates.  I'm going to try to reproduce it specifically by adding a swap file and see what happens.  But, I won't be able to do that until next week.

**Comment by jkeys-ecg-nmsu** [comment]
Sounds like an encoding issue. Have you tried using a tool like Notepad++ to make sure the file encodings are the same?

**Comment by tncbbthositg** [comment]
I think it has to do with line endings.  I've been editing the json and yaml files with visual studio code and it works fine.  If I edit either of them with vim, then the file gets corrupted whenever I save. :( .

**Comment by johnf** [comment]
This happens if you have vi open while you do the push. The .swp file which is binary is also being uploaded to the S3 bucket and cloudformation is trying to parse it, hence invalid characters

Workaround till it's fixed is exit vi or close the file before push
