### ISSUE TITLE
Custom resolver templates ignored

### ISSUE THREAD

**Issue by struct78** [aws-amplify/amplify-cli#1136]
**Describe the bug**
Placing a custom resolver in the resolvers/ directory of an API fails to get picked up/fails silently.

**To Reproduce**
1. Add an API using the CLI
2. Create a schema with a single model `schema.graphql`
```
type Goal @model {
  id: ID!
  title: String
  type: String
  startDate: AWSDate
  endDate: AWSDate
}
```

2. Add a custom resolver that doesn't set a default limit of 10 

```
{
  "version": "2017-02-28",
  "operation": "Scan",
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": #if($context.args.limit)
$context.args.limit
  #else
null
  #end,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end
}
``` 

3. Run `amplify push`

**Expected behavior**
The custom resolver template should be used, instead the default one is used:

```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
{
  "version": "2017-02-28",
  "operation": "Scan",
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": $limit,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end
}
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.13.6
 - CLI version: 0.22-multienv.1

**Comment by kaustavghosh06** [comment]
Please upgrade your CLI to the main version using ‘npm install -g @aws-amplify/cli’ which was support for custom resolvers.

**Comment by struct78** [comment]
I need to use the multienv version, though. So I'm basically boned?

**Comment by kaustavghosh06** [comment]
The main version of the CLI supports mulitienv now.

**Comment by struct78** [comment]
Neat, that worked, thanks @kaustavghosh06
