### ISSUE TITLE
remove and update notifications with FCM thows errors

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#11376]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

10.4.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

notifications

### Amplify Commands

add

### Describe the bug

1. Adding a FCM notification channel without the proper API key and removing the resource re-prompts for API key

observe error:
```
🛑 Failed to disable the FCM channel
```

entering the right key did not solve the issue. `removing `All channels on Pinpoint resource` or `FCM  | » Firebase Push Notifications ` will throw the error

2. updating the notifications and reentering the API key will throw 
```
🛑 Cannot read property 'Enabled' of undefined
```

### Expected behavior

remove resource without errors 

### Reproduction steps
```
1. amplify add notifications
√ Choose the notification channel to enable · FCM  | » Firebase Push Notifications 
? Provide your pinpoint resource name: test
? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analytics events? (we recommend you allow this when getting started) Yes
? ApiKey: abcdef ->(random wrong key)
```
realize you added wrong key 
```
2. amplify remove notifications
√ Choose the notification channel to remove · All channels on Pinpoint resource : test
Disabling all notifications from the Pinpoint resource
? ApiKey <add a key>
🛑 Failed to disable the FCM channel
```
lets try to update the resource
```
3. amplify update notifications
√ Choose the notification channel to configure · FCM  | » Firebase Push Notifications 
The FCM channel is currently enabled
? Do you want to disable the FCM channel No
? ApiKey <any key>
√ The FCM channel has been successfully updated.
🛑 Cannot read property 'Enabled' of undefined
```
### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

f3bd5fd9e00178140378c43212566160

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @ykethan when you tried to remove the notification did you input anything into the `ApiKey` prompt? I was able to remove it without entering anything there. Same with `amplify update notification` 

```
➜  amplify update notification
✔ Choose the notification channel to configure · FCM  | » Firebase Push Notifications 
The FCM channel is currently enabled
? Do you want to disable the FCM channel Yes
? ApiKey 
✔ The FCM channel has been disabled.
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

**Comment by ykethan** [comment]
hey @josefaidt , yes i added the api key in again. let me try without the api key

**Comment by josefaidt** [comment]
Hey @ykethan I was not able to reproduce this issue, however I did notice a lot of duplicated lines coming from the automatic push event 

https://user-images.githubusercontent.com/5033303/201226293-84edb2ec-e9f8-43be-a1d4-656d82a976b7.mov

**Comment by ykethan** [comment]
Hey @josefaidt, hitting enter on API key prompt fixes the issue. But why does remove prompt for a API key when removing it?

**Comment by josefaidt** [comment]
After hopping on a quick call I realized I was reproducing by selecting "Yes" to "do you want to disable the FCM channel" where the repro steps here say "No". Despite the odd `ApiKey` prompt, after selecting "No" to this prompt we are able to reproduce

**Comment by josefaidt** [comment]
also seeing this on `amplify remove notification`

```
aws-amplify/reproductions/modeltest 
➜  ay remove notification
🛑 Cannot read property 'Id' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/


aws-amplify/reproductions/modeltest 
➜  ay remove notifications
🛑 Cannot read property 'Id' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

**Comment by lazpavel** [comment]
might be related to this: https://github.com/aws-amplify/amplify-cli/pull/11378
