### ISSUE TITLE
Amplify push does not complete "Browserslist: caniuse-lite is outdated"

### ISSUE THREAD

**Issue by PratteekB** [aws-amplify/amplify-cli#11425]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

curl, using the command on the documentation website

### If applicable, what version of Node.js are you using?

v18.12.0

### Amplify CLI Version

10.4.1

### What operating system are you using?

Windows 11 (version 10.0.22621 Build 22621)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes were made to the cloud resources managed by Amplify, however I am connecting to an existing AWS Cognito user pool. 

After following the docs on the AWS amplify website [amplify website](https://docs.amplify.aws/cli/auth/import/) I ran `amplify import auth` and my local amplify settings were updated with the correct Cognito Pool ID etc.

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

My local setup is fine, when I try and run `amplify push` I get the "successfully pulled backend environment dev from the cloud" tick however after responding 'yes' to the "are you sure you want to continue" prompt I get the following error:

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

I then proceed to run the command `npx browserslist@latest --update-db` and get this response: 

```
Latest version:     1.0.30001431
Installed version:  1.0.30001431
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes
```

however after then attempting to run `amplify push` again there is no change in the result.

### Expected behavior

I expect that after running `amplify push` my local amplify setup will be propagated into my AWS amplify backend and I can then use the AWS Cognito pool in my app development.

### Reproduction steps

1. Create an AWS Cognito Pool from the AWS console
2. Create a react native typescript template project
3. Install the Amplify CLI on your machine
4. Configure AWS amplify with the relevant IAM user roles and a user profile
5. Run `amplify import auth`
6. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hey @PratteekB, Thank you for reaching out. Currently a PR is in place to mitigate the issue: https://github.com/aws-amplify/amplify-cli/pull/11269
Could you upgrade the Amplify CLI to 10.5.0 using `amplify upgrade`? 
On testing the push on the newest version in my amplify application the warning message does not occur.

**Comment by PratteekB** [comment]
Excellent, can confirm the updated v10.5.0 has fixed this issue
