### ISSUE TITLE
adding/cloning env non-interactively

### ISSUE THREAD

**Issue by roundrobinjp** [aws-amplify/amplify-cli#11426]
### Amplify CLI Version

10.4.1

### Question

I need to clone existing amplify backend environment (which has S3AndCloudFront hosting) from bash script non-interactively.
How do I do this?

By the way, I can do it interactively using "amplify env add" command.
I need to do the same non-interactively.

**Comment by josefaidt** [comment]
Hey @roundrobinjp :wave: thanks for raising this! I believe you are looking for `amplify env add --envName mynewenv --yes`

**Comment by roundrobinjp** [comment]
@josefaidt 
Wow! It worked. Many thanks.

By the way, I googled a lot but could not find the info that you provided.
Where should I have looked for this?
Is there any command reference for amplify cli?

Anyway, thanks a lot.

**Comment by josefaidt** [comment]
Hey @roundrobinjp glad to hear it! That command can be found here https://docs.amplify.aws/cli/teams/commands/#commands-overview, and we're actively investigating an improved `help` command and supporting documentation
