### ISSUE TITLE
Can't add storage resource access permission to function using @mapsTo directive.

### ISSUE THREAD

**Issue by daichi-yamauchi** [aws-amplify/amplify-cli#11427]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.15.1

### Amplify CLI Version

10.4.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

I've changed model name in API GraphQL category with @mapsTo directive. (e.g. Account to User)
After that, I can't select resource access permission previous storage model (Account) executing amplify update function.

### Expected behavior

Be able to select the storage model before changed in update resource access permission of function because @mapsTo directive does not change DynamoDB Table.

### Reproduction steps

1. create graphql api category and make some model in schema.graphql.
2. `amplify push`
3. change model name with @mapsTo derective in the schema.graphql.
4. `amplify update function` > Resource access permissions > storage

### GraphQL schema(s)

<details>

```graphql
type Account @model {
  id: ID! @primaryKey
  name: String!
}
```
```graphql
type User @model @mapsTo(name: "Account") {
  id: ID! @primaryKey
  name: String!
}
```

</details>

### Additional information

You can avoid this bug temporary making previous model.

1. Add previous model in schema.graphql
2. `amplify update function` and update resource access permission.
3. Remove the previous model.

**Comment by ykethan** [comment]
Hey, thank you for reaching out. I tried reproducing this in my Amplify project.

1. Create a Amplify application and added api with the following schema
```graphql
type Task @auth(rules: [{allow: public}]) {
  id: ID!
  descption: String
}
```
2. added a function and provided the additional permissions.
```
amplify add function   
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: taskappa2a08d1d
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. storage
? Select the operations you want to permit on Task:@model(appsync) create, read

You can access the following resource attributes as environment variables from your Lambda function
        API_TASKAPP_GRAPHQLAPIIDOUTPUT
        API_TASKAPP_TASKTABLE_ARN
        API_TASKAPP_TASKTABLE_NAME
        ENV
        REGION
? Do you want to invoke this function on a recurring schedule? No
? Do you want to enable Lambda layers for this function? No
? Do you want to configure environment variables for this function? No
? Do you want to configure secret values this function can access? No
? Do you want to edit the local lambda function now? No
Successfully added resource taskappa2a08d1d locally.
```
As we observe the `permit on Task:@model(appsync)` indicated the Task model was recognised.

3. Pushed the application
4. updated the schema.graphql with the following schema.
```graphql
type Test @model @mapsTo(name: "Task") @auth(rules: [{allow: public}]) {
  id: ID!
  descption: String
}
```
5. ran `amplify update function`
```
? Select the Lambda function you want to update taskappa2a08d1d
General information
- Name: taskappa2a08d1d
- Runtime: nodejs

Resource access permission
- Task:@model(appsync) (create, read)

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. storage
? Select the operations you want to permit on Test:@model(appsync) create, read

You can access the following resource attributes as environment variables from your Lambda function
        API_TASKAPP_GRAPHQLAPIIDOUTPUT
        API_TASKAPP_TESTTABLE_ARN
        API_TASKAPP_TESTTABLE_NAME
? Do you want to edit the local lambda function now? No
```
updated the function and observed the flow recognized the change ` permit on Test:@model(appsync)`
6. added code to the function calling the Task DDB Database. Tested the function on console. observed the following output.
![image](https://user-images.githubusercontent.com/87995712/202518810-82ddb17b-72c5-4c44-8ea8-907faec216dd.png)
