### ISSUE TITLE
Migrating Auth/Lambda changes across environments

### ISSUE THREAD

**Issue by klaeuiM** [aws-amplify/amplify-cli#11437]
### Amplify CLI Version

10.5.0

### Question

I have dev and staging environments/branches. I updated Auth in the dev branch to require signin/signout using an allowlist, which creates a lambda function. This works flawlessly.

I then switched to the staging branch, checked out the staging environment, and merged the dev branch. Following this, when running `amplify status`, I expected function creation to be scheduled, but this is not so. Running `amplify codegen` or `amplify function build` does not make a difference. Running `amplify push` fails with AuthTriggerCustomLambdaStack cloudformation stack saying "Parameters: [functioneconappPreSignupArn, functioneconappPreSignupName] must have values"

What am I doing wrong? Thanks

Am I supposed to update the team-provider-info.json file manually? It is missing the function parameters under the staging heading.

**Comment by josefaidt** [comment]
Hey @klaeuiM  :wave: thanks for raising this! When you run `amplify status` do you see the newly created function in the resources list? If not you may be affected by this bug https://github.com/aws-amplify/amplify-cli/issues/8090

**Comment by klaeuiM** [comment]
I appreciate the help. It is indeed bug 8090 (I did not see the function in the resource list).

Anyone coming across this, the steps are (for moving from dev branch to staging branch):

git switch staging
amplify env checkout staging
git merge dev
amplify env checkout staging             # bug 8090
amplify push
git push origin staging

Thanks much!
