### ISSUE TITLE
Amplify version 10.4.0, there is a issue when run  "amplify env add <env_name>", if I run "amplify add notifications" for the current environment

### ISSUE THREAD

**Issue by yanlin96** [aws-amplify/amplify-cli#11432]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.5.5

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, totally rely on Amplify Cli 10.4.0 version

### Amplify Categories

notifications

### Amplify Commands

env, push

### Describe the bug

The issue is only Amplify cli 10.4.0, based on my test, I did not see the issue on Amplify cli 10.3.2.

While use 
1. `amplify add notifications` with "Email" in one environment, for example "dev", and run `amplify push` to the environment
2. `amplify env add prod` to create a new environment "prod".

The following error message will occur "Failed to enable the Email Channel"
If ignore this error, and run "amplify push", will see error "Cannot set property 'Id' of undefined". And through Amplify Console, See "No enabled categories"

### Expected behavior

No error shows while "clone a new environment"

All resources are in new environment

### Reproduction steps

1. `amplify init` to init a project, the name is "pinamplify"
2.  `amplify add notifications` And Choose Email for Push notifications, then, Amplify will interact to ask creating "Auth" and "Analytics (Pinpoint)". Looks like Amplify relying on Pinpoint to sending the "Push notification"
3. It will ask below questions
- From email to send email
- ARN of SES identity 
- IAM role
4. Once all finished, run amplify push, and it works

Then, change to another environment

1. amplify env add prod
2. It will pop up questions
- From email to send email
- ARN of SES identity 
- IAM role
However, an error occurs 

![image](https://user-images.githubusercontent.com/71164436/202568771-e5213968-f4f3-464d-bf03-275b73c909b1.png)

Ignore the error and push, the following error shows

![image](https://user-images.githubusercontent.com/71164436/202568959-85916b61-c039-42a3-869f-7100e9823dfb.png)

And in Amplify Console

![image](https://user-images.githubusercontent.com/71164436/202569055-c33d4e71-258f-43b8-9d79-f7139a30b6a7.png)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mjmostachetti** [comment]
Does this also cover the case when I checkout an existing environment and try to push changes that include notifications? I received the same error in red. 
"Cannot set property "Id" of undefined"

**Comment by yusukegoto** [comment]
> Does this also cover the case when I checkout an existing environment and try to push changes that include notifications? I received the same error in red. I'm on 10.5.1 and all new resources created successfully except for Notifications. "Cannot set property "Id" of undefined"

I have the same.
`amplify pull` failed with the same error `🛑 Could not initialize categories for 'testing': Cannot read property 'Id' of undefined` .
Plus it's weird that `amplify status` shows Notifications's operation as `Create` although I can see the Pinpoint IDs in the `./amplify/team-provider-info.json` .

**Comment by mjmostachetti** [comment]
@lazpavel Any updates? It's still an issue in 10.5.2. We added the Email category and now there is no work for us. When I checkout the environment that I just pushed up, I get this error below. `amplify status` also reports that everything will get a  `Create` operation even though if I look in AWS the resources are there - including pinpoint for 'myenv'. Any eta on a fix?

✔ Initialized provider successfully.
⠋ Retrieving channel information for Email.✖ There was an error initializing your environment.
🛑 Could not initialize categories for 'myenv':

**Comment by mjmostachetti** [comment]
@lazpavel I upgraded the CLI to 10.6.1. This issue still remains.
STR - Create new environment, push and you'll see this
✔ Code generated successfully and saved in file src/API.ts
🛑 Cannot set property 'Id' of undefined
Checkout original environment and then checkout the environment that I just created, and you'll see this again
✔ Initialized provider successfully.
⠋ Retrieving channel information for Email.✖ There was an error initializing your environment.

**Comment by yanlin96** [comment]
Hi team,

I have tried with 10.4.0 and 10.6.2 version of amply cli. However, looks like the issue is still there?

**Comment by kulikala** [comment]
Hi forks,

I've come up with a workaround for this issue.
My idea is to remove the entire `"notifications"` property from `amplify/backend/backend-config.json`.

```json
  "notifications": {
    ...
  },
```

If you want a one-liner command with `jq`, this is for you:

```shell
# Remove the "notifications" property from backend-config.json
cd amplify/backend; (rm backend-config.json; jq --monochrome-output --raw-output 'del(.notifications)' > backend-config.json) < backend-config.json; cd -
```

After creating a new environment, you can safely discard changes to this file without any effect.

```shell
# Create your new environment
amplify env add ${NEW_ENV_NAME}

# Discard changes to the file
git restore amplify/backend/backend-config.json

# Push to the remote and create resources
amplify push -y
```

You'll need to re-create notifications after pushing to the remote is complete.

```shell
# Add your notifications again
amplify add notifications
```
