### ISSUE TITLE
How do I automatically run code before `push`?

### ISSUE THREAD

**Issue by mhodgson** [aws-amplify/amplify-cli#1146]
** Which Category is your question related to? **
The push CLI command

** What AWS Services are you utilizing? **
Amplify, DynamoDB

** Provide additional details e.g. code snippets **
I'd like to write my custom stacks in something other than raw JSON. Preferable I could utilize Cloudform like the rest of the CLI codebase. Is there a way to provide a `before` hook or callback to the push command so that I can compile my Cloudform before the CLI attempts to push the new stacks to CloudFormation?

**Comment by jkeys-ecg-nmsu** [comment]
Maybe this is a dumb question, but is there a reason you can't just write a shell script that performs the commands and execute that script instead of push? You can use the `--yes` command to perform a headless push.

**Comment by mhodgson** [comment]
Absolutely not, but coming from other solutions like Serverless it feels like something I should be able to do. The platform offers the use of 'plugins', but as far as I can tell, there is no way to extend the existing commands, severely limiting the ability of plugin authors to provide advanced functionality. A few examples:

- A plugin that enables people to write their custom stacks in Cloudform.
- A plugin that takes the generated Typescript types for GraphQL and automatically generates React Hooks for working with them.
- A plugin to generate batch read/write queries/mutations for models.

Right now there is no way for plugin authors or developers to plug into the existing commands. I think a solution for before/after hooks (i.e. `onBeforePush`, `onAfterPush`) would enable a much richer developer experience, and allow plugin authors to make the whole experience more 'magical'.

**Comment by jkeys-ecg-nmsu** [comment]
You can't plug into the existing commands, but you can see the source for them so it's possible to extend them currently. 

I agree that asynchronous hooks would be a great enhancement.

**Comment by jkeys-ecg-nmsu** [comment]
Re batch operations: #1097, #1078, #1058.

**Comment by ykethan** [comment]
This functionality is currently supported via command hooks, please refer to https://docs.amplify.aws/cli/project/command-hooks/ for additional information.
