### ISSUE TITLE
Creating Api when Auth is manually configured

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1149]
** Which Category is your question related to? **
AWS Amplify API, AWS Amplify Auth

** What AWS Services are you utilizing? **
AWS Cognito, AWS DynamoDb

** Provide additional details e.g. code snippets **
Hi all i manually configured auth with existing cognito db, and when i try to add api, it is creating new auth. any suggestions?

**Comment by UnleashedMind** [comment]
@achutkiran 
Just to be more precise, are you trying to add REST API or GraphQL API?

**Comment by achutkiran** [comment]
@UnleashedMind I am adding GraphQl API with authorization as Amazon Cognito User Pool

**Comment by kaustavghosh06** [comment]
@achutkiran Which version of the CLI are you using?
Can you show what does your `amplify status` command show?

**Comment by achutkiran** [comment]
amplify version 1.1.8
![image](https://user-images.githubusercontent.com/26334163/55342484-866df680-546e-11e9-938a-35deca2c7708.png)

**Comment by kaustavghosh06** [comment]
@achutkiran If you choose API with Cognito User Pools, CLI creates an auth resource for you since your API is dependent on the Auth resource. Did you remove the auth resource using `amplify auth remove`? Also, are you using API Key or Cognito as your auth mode for the GraphQL  API?

**Comment by achutkiran** [comment]
@kaustavghosh06 Hi I manually configured Auth with preexisting Cognito user pool as defined in document. I am using Cognito as Auth mode for GraphQL API.
![image](https://user-images.githubusercontent.com/26334163/56064773-a4720b80-5d38-11e9-90ad-96dc3be69e88.png)

**Comment by kaustavghosh06** [comment]
@achutkiran By default, the GraphQL API creates a new cognito user pool for you (if the cognito option is selected). As a workaround, in the amplfy/backend/api/<api-name>/parameters.json file, you could modify/add the "AuthCognitoUserPoolId" and use your cognito user pool ID as a value out there for the GraphQL API to pick up that user pool.

**Comment by achutkiran** [comment]
@kaustavghosh06 ok thanks will try
