### ISSUE TITLE
Could not initialize platform for 'dev': self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sgvs-deloitte** [aws-amplify/amplify-cli#11500]
after installing aws amplify cli. am not able to take a pull or push due to self signed certificate chain issue not able to resolve or find any solution related in the internet

**Comment by josefaidt** [comment]
Hey @sgvs-deloitte :wave: what is the error you're receiving? Are there any additional details you can provide to help us narrow down the issue?

**Comment by sgvs-deloitte** [comment]
hey jose I resolved the issue

**Comment by askurat** [comment]
@sgvs-deloitte How did you resolve this?
