### ISSUE TITLE
unable to add new environment when project includes SMS notifications

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11503]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.5.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

notifications

### Amplify Commands

env

### Describe the bug

unable to add new environment with `amplify env add` when SMS notifications exist in the project:

```
➜  amplify env add --envName next --yes
Note: It is recommended to run this command from the root of your app directory
Using default provider  awscloudformation
✔ Initialized provider successfully.
⚠️ Pinpoint resource is only locally created
⚠️ Run "amplify push" to deploy the Pinpoint resource and then retry...
✖ There was an error initializing your environment.
🛑 Failed to enable the SMS channel.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: ba1638ce-3889-40d2-b99f-c737a81aacec
```

### Expected behavior

n/a

### Reproduction steps

1. `amplify init -y`
2. `amplify add notifications` > SMS
3. `amplify env add --envName next --yes`
4. observe error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Note: related to https://github.com/aws-amplify/amplify-cli/issues/11432

**Comment by ykethan** [comment]
PR: https://github.com/aws-amplify/amplify-cli/pull/11494 will address this.
