### ISSUE TITLE
upgrade Dotnet Lambda functions due to EOL for Dotnet 3.1 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#11510]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

Dotnet core 3.1 will reach end of support on December 2022. https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
Lambda function runtime support for Dotnet core 3.1 will reach end of support on Mar 2023. https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

upgrade lambda function Dotnet runtime to version 6.

### Describe the solution you'd like

upgrade lambda function Dotnet runtime to version 6.

### Describe alternatives you've considered

manual upgrade 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by sobolk** [comment]
https://app.asana.com/0/1202389680978480/1203477825372822/f

**Comment by sobolk** [comment]
https://github.com/aws-amplify/amplify-cli/pull/11569

**Comment by evcodes** [comment]
Closing as this was released already
