### ISSUE TITLE
'amplify init' fails. An error occurred when creating the CloudFormation stack

### ISSUE THREAD

**Issue by knut973** [aws-amplify/amplify-cli#11538]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

10.5.1

### What operating system are you using?

win 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

This is my first initalization, and first app (first time user, so AWS account is clean of any settings).

I followed the instructions here: https://docs.amplify.aws/cli/start/install/#install-the-amplify-cli
On 'amplify init' in my local project it fails. 

This is the error message in the CLI:

Deployment completed.
Deployed root stack amplify [ ======================================== ] 4/4
        UnauthRole                     AWS::IAM::Role                 DELETE_COMPLETE                Tue Dec 06 2022
        DeploymentBucket               AWS::S3::Bucket                DELETE_SKIPPED                 Tue Dec 06 2022
        AuthRole                       AWS::IAM::Role                 DELETE_COMPLETE                Tue Dec 06 2022
        amplify-amplify-dev-142546     AWS::CloudFormation::Stack     ROLLBACK_COMPLETE              Tue Dec 06 2022

An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 99c08f6a-4f94-4a3c-b025-bb139d37c710

----

I also tried creating an amplify app backend with the console. 
That also failed:

Initializing backend environment failed:
Command failed with exit code 1: amplify init --amplify {"envName":"staging","defaultEditor":"code","projectName":"Amplify","appId":"d19gmsqwp8y7e"} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --yes
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
Note: It is recommended to run this command from the root of your app directory
The following configuration will be applied:

Project information
| Name: Amplify
| Environment: staging
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm run-script build
| Start Command: npm run-script start

Amplify AppID found: d19gmsqwp8y7e. Amplify App name is: Amplify
Adding backend environment staging to AWS Amplify app: d19gmsqwp8y7e

CREATE_IN_PROGRESS amplify-amplify-staging-133007 AWS::CloudFormation::Stack Tue Dec 06 2022 13:30:07 GMT+0000 (Coordinated Universal Time) User Initiated
CREATE_IN_PROGRESS UnauthRole AWS::IAM::Role Tue Dec 06 2022 13:30:10 GMT+0000 (Coordinated Universal Time)
CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Tue Dec 06 2022 13:30:10 GMT+0000 (Coordinated Universal Time)
CREATE_IN_PROGRESS AuthRole AWS::IAM::Role Tue Dec 06 2022 13:30:11 GMT+0000 (Coordinated Universal Time)
CREATE_IN_PROGRESS UnauthRole AWS::IAM::Role Tue Dec 06 2022 13:30:11 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole AWS::IAM::Role Tue Dec 06 2022 13:30:11 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Tue Dec 06 2022 13:30:12 GMT+0000 (Coordinated Universal Time) Resource creation Initiated

CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Tue Dec 06 2022 13:30:33 GMT+0000 (Coordinated Universal Time)

CREATE_COMPLETE UnauthRole AWS::IAM::Role Tue Dec 06 2022 13:30:44 GMT+0000 (Coordinated Universal Time)
CREATE_COMPLETE AuthRole AWS::IAM::Role Tue Dec 06 2022 13:30:44 GMT+0000 (Coordinated Universal Time)
ROLLBACK_IN_PROGRESS amplify-amplify-staging-133007 AWS::CloudFormation::Stack Tue Dec 06 2022 13:30:45 GMT+0000 (Coordinated Universal Time) Template error: IAM role amplify-amplify-staging-133007-unauthRole doesn't exist. Rollback requested by user.

DELETE_IN_PROGRESS UnauthRole AWS::IAM::Role Tue Dec 06 2022 13:30:54 GMT+0000 (Coordinated Universal Time)
DELETE_IN_PROGRESS AuthRole AWS::IAM::Role Tue Dec 06 2022 13:30:55 GMT+0000 (Coordinated Universal Time)
DELETE_SKIPPED DeploymentBucket AWS::S3::Bucket Tue Dec 06 2022 13:30:55 GMT+0000 (Coordinated Universal Time)
DELETE_COMPLETE UnauthRole AWS::IAM::Role Tue Dec 06 2022 13:30:56 GMT+0000 (Coordinated Universal Time)
DELETE_COMPLETE AuthRole AWS::IAM::Role Tue Dec 06 2022 13:30:56 GMT+0000 (Coordinated Universal Time)
ROLLBACK_COMPLETE amplify-amplify-staging-133007 AWS::CloudFormation::Stack Tue Dec 06 2022 13:30:57 GMT+0000 (Coordinated Universal Time)

An error occurred when creating the CloudFormation stack
🛑 The following resources failed to deploy:
🛑 Initialization of project failed

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 23e7a99a-3c58-4240-a660-1ddceee17225.  

### Expected behavior

Project and amplify backend initalized

### Reproduction steps

 Unknown

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by JulianKarhof** [comment]
This has resolved itself for me, maybe try again now?

**Comment by josefaidt** [comment]
Hey @knut973 :wave: thanks for raising this! As @JulianKarhof noted, this issue should now be resolved. Can you try to run `amplify init` again?

**Comment by evcodes** [comment]
Between 4:45 AM and 6:19 AM PST, there were increased API error rates and latency for IAM APIs, which Amplify relies on. The issue has been resolved and the service is operating normally. We want to hear if that's the case for you, @knut973.

**Comment by knut973** [comment]
Hey, the issue is resolved and amplify init now runs as expected

Thanks!
