### ISSUE TITLE
Serverless Container Hosting fails to amplifyPush with suggested built-in policies of the Service Role

### ISSUE THREAD

**Issue by robertoandrade** [aws-amplify/amplify-cli#11567]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2ek5z3mhpk05c

### AWS Region

sa-east-1

### Amplify Hosting feature

Access control, Backend builds, Service role

### Describe the bug

When creating a new Amplify app and configuring it for Serverless containers as documented [here](https://docs.amplify.aws/cli/usage/containers/) with any Dockerfile/template, part of the setup once Amplify Hosting is enabled is to configure a Service Role with some default policies/permissions as documented [here](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html).

The problem is that once the app is connected to its git origin and it attempts to perform the `amplifyPush` and communicate with the AWS services, be CloudFormation, S3, etc and it assumes the Service Role, the permissions it's given do not allow it to perform some operation that fails the build every time.

### Expected behavior

The build should succeed as it does when performing `amplify push` from a local machine with an administrator access key.

### Reproduction steps

1. Create an Amplify app
2. Enable Container-based backends
3. Create an API project that uses AWS Fargate to deploy the containers
4. Configure Amplify Hosting to connect to the Git repo of source and connect to the backend, make sure to create the Service Role with the recommended permissions
5. Git push the generated configuration to the git repo to trigger a deployment
6. Notice how the backend build fails with lack of permissions to perform some operation

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
                                 # Starting phase: build
2022-12-08T07:53:51.183Z [INFO]: [0mAmplify AppID found: d2ek5z3mhpk05c. Amplify App name is: api[0m
2022-12-08T07:53:51.232Z [INFO]: [0mBackend environment dev found in Amplify Console app: api[0m
2022-12-08T07:53:53.666Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2022-12-08T07:53:54.205Z [WARNING]: - Building resource api/amplifyapi
2022-12-08T07:53:54.244Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-12-08T07:53:54.306Z [INFO]: ✅
2022-12-08T07:53:56.449Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-12-08T07:53:57.690Z [WARNING]: - Initializing your environment: dev
2022-12-08T07:53:58.216Z [WARNING]: - Building resource api/amplifyapi
2022-12-08T07:53:58.216Z [WARNING]: ✔ Initialized provider successfully.
2022-12-08T07:53:58.365Z [WARNING]: ✖ There was an error initializing your environment.
2022-12-08T07:53:58.366Z [INFO]: 🛑 You are not authorized to perform this operation.
2022-12-08T07:53:58.366Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2022-12-08T07:53:58.368Z [INFO]: 
2022-12-08T07:53:58.368Z [INFO]: Session Identifier: 6f618b1f-7130-4e5f-9bc1-bef1225da264
2022-12-08T07:53:58.579Z [ERROR]: !!! Build failed
2022-12-08T07:53:58.579Z [ERROR]: !!! Non-Zero Exit Code detected

```

</details>

### Additional information

[~/.amplify/logs/amplify.log](https://github.com/aws-amplify/amplify-hosting/files/10183357/amplify.log)

**Comment by josefaidt** [comment]
Hey @robertoandrade thanks for raising this! The "not authorized" error is interesting as upon further inspection of the logs I see

```
2022-12-08T09:09:56.838Z [INFO]: 🛑 The following resources failed to deploy:
                                 Resource Name: DeploymentAwaiter (AWS::CloudFormation::CustomResource)
                                 Event Type: update
                                 Reason: Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed
```

I am able to reproduce this using the provided steps, thank you for including the details! 
![image](https://user-images.githubusercontent.com/5033303/206763709-43561455-e12c-4a2b-ab51-6cda86e326b1.png)

As a workaround, please use the `AdministratorAccess` policy rather than the `AdministratorAccess-Amplify` policy for your service role. Additionally there is an existing feature request to improve this policy for container based deployments which is filed here https://github.com/aws-amplify/amplify-adminui/issues/662.

Closing as a duplicate feature request. Please refer to the provided workaround and the linked issue for further updates.

**Comment by zandieh** [comment]
@josefaidt @robertoandrade I'm facing the same issue. Note that I'm currently having `AdministratorAccess ` in my service role.
full log attached
[log (2).txt](https://github.com/aws-amplify/amplify-cli/files/12242907/log.2.txt)

**Comment by JLongley** [comment]
+1
