### ISSUE TITLE
Adding API with DynamoDB not triggering lambda

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#1157]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
After following the CLI to add CRUD operations with API Gateway and DynamoDB, I am unable to query my table items.  After throwing in a few log statements, I noticed the endpoint is not being triggered.  I verified the frontend is configured correctly and came across the following insights:

* The API Gateway trigger is throwing an error (after some digging, this seems to be more of a warning...I beleive.)
<img width="1248" alt="Screenshot 2019-04-01 02 12 25" src="https://user-images.githubusercontent.com/5106417/55309517-a7f5c080-5423-11e9-85e8-fb343c507829.png">

* In the default generated `GET` route, the path differs from how the endpoint is constructed when running the CLI commands to create a non-dynamo API.
`app.get(path + hashKeyPath, function(req, res) { } // There is a hashKeyPath` 
  * This variable is defined above, but because it's expected, a simple route of `/items` will fail.
  * Removing the `hashKeyPath` allows API Gateway to now trigger the lambda.
* Once the route is able to be triggered, an error will now appear in CloudWatch logs:
  * `ValidationException: One or more parameter values were invalid: Invalid number of argument(s) for the EQ ComparisonOperator`
  * I believe this is happening because `req.params` is an empty object and this object is needed so that dynamo knows what to query for (as part of the `KeyConditions` requirement.

**To Reproduce**
![Screenshot 2019-04-01 02 36 25](https://user-images.githubusercontent.com/5106417/55310819-07090480-5427-11e9-926a-b8b5a6368890.png)

**Expected behavior**

My use case is to create an API with dynamo integrated, then in the aws console I could add items to the database, and on the frontend, I could query for those all items.  

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Browser Chrome
 - Version 73

**Additional context**

The docs are scarce regarding scenarios where one would do this.  I'd be happy to submit a PR with a tutorial once this gets resolved.

**Comment by elorzafe** [comment]
@mtliendo the query for this will expect that you send the value for partition key for your table like this.

`API.get('\items\name1')` ( I assuming you add a record on your table with a name: `name1`) that will return an array that matches that partition key. If you have a sort key you could have a list of values.

You could also query the exact record by doing `API.get('\items\object\name1')` in case you had a sort key you will to add the sort key value like this `API.get('\items\object\name1\mysort1')`

**Comment by mtliendo** [comment]
@elorzafe thanks! Your nice explanation of how partionKeys work helped me query for a single item.  But in your example: `API.get('\items\name1')` that will allow me to query all items with `name1` as the value.  How would I just /GET all items in the table?

**Comment by mtliendo** [comment]
I'm thinking this may be when GSI's come into play, but I can't find a resource on how to use it in the context of Amplify.

**Comment by elorzafe** [comment]
@mtliendo I am glad it works! To get all the items from dynamo you need to do a scan for the table to get all items (instead of a query, query always require a partition key). Other option is to use your sortKey as the actual key of your data, and use the same id for the type (like person, or group). There is a nice talk about how to use dynamodb [here](https://www.youtube.com/watch?v=jzeKPKpucS0) it suggest to use only one table per app.

**Comment by mtliendo** [comment]
Oh wow, that's an interesting idea (regarding using the sort key and same id).  Your help is much appreciated.  Feel free to mark this as resolved.
