### ISSUE TITLE
receiving `Invalid environment name: undefined` when running `amplify init -y` in an initialized project

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11579]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.5.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

When running `amplify init -y` in an initialized project we receive `Invalid environment name: undefined`

### Expected behavior

We should receive a more helpful message such as

```
Amplify project ${appId} is already initialized for environment ${envName}. To create a new environment run `amplify add env`
```

### Reproduction steps

1. `amplify init -y`
2. `amplify init -y`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by Anshul-target** [comment]
Hello Sir ,I can solve this issue please assign me
