### ISSUE TITLE
The security token included in the request is invalid

### ISSUE THREAD

**Issue by luong12g** [aws-amplify/amplify-cli#11585]
I am trying to use localstack cognito with amplify.

I can login to cognito successful.

I also want to implement Social sign-in too.

First I create a profile locastack with key and secret

aws configure --profile localstack

then 
export AWS_ACCESS_KEY_ID=dummy
export AWS_SECRET_ACCESS_KEY=dummy
aws --endpointurl http://localhost:4566 kinesis list-streams

and I run 

amplifylocal init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project localstack
The following configuration will be applied:

Project information
| Name: localstack
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use localstack
🛑 The security token included in the request is invalid.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

I also try to run docker-compose with 
  environment:
      - HOSTNAME=localhost
      - DEBUG=1
      - PERSISTENCE="disabled"
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_API_KEY=4pwo1o14g2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - USE_SSL=false
      - DISABLE_CORS_CHECKS=1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1

I got the same result.

Any advices
Thanks

**Comment by josefaidt** [comment]
Hey @luong12g :wave: thanks for raising this! Would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml)? By doing so this will help us get a better understanding of the context of the issue in order to effectively diagnose.
