### ISSUE TITLE
Bug where override error message disappears during push

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-cli#11607]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.5.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Error message during push appears for a moment, but then gets swallowed by the cdk deploy refreshes

Customer had a real error he had to address, but needed to screen record and pause the video at the right moment in order see the error message

![image (3)](https://user-images.githubusercontent.com/4824042/207692999-1a80451d-b2c5-445c-a4bd-6946901a5a0e.png)

### Expected behavior

Error message sticks around without being overwritten

### Reproduction steps

N/A

### Project Identifier

N/A

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @johnpc :wave: thanks for raising this! To clarify, was this a CloudFormation error that was not surfaced at the end of the `amplify push` attempt?

**Comment by johnpc** [comment]
There was an error reading a property of undefined. The error came from override code with the control of the developer. 

The error message was good, but it was difficult to read because it only flashed on the screen for a brief period of time.

**Comment by josefaidt** [comment]
Hey @johnpc thanks for clarifying! Do you remember whether this was an issue with the provided types where perhaps the type assume a property exists where it doesn't? I typically run into errors immediately after push if there's an issue building the override.

**Comment by josefaidt** [comment]
I was able to reproduce this by attempting to use `Fn::GetAtt` and reference a resource that doesn't exist. When this happens the override will build properly but will fail during push. The failure is swallowed and the CLI appears to continue with the deployment despite not actually kicking off the CFN changes.

Marking as a bug

**Comment by edwardfoyle** [comment]
This is resolved in version 10.8.0 of the CLI. Please upgrade to try it out.
