### ISSUE TITLE
UNKNOWN: unknown error, readlink 

### ISSUE THREAD

**Issue by anu-IV** [aws-amplify/amplify-cli#11612]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

10.5.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made"

### Describe the bug

[report-1671116691554.zip](https://github.com/aws-amplify/amplify-cli/files/10238169/report-1671116691554.zip)

### Expected behavior

amplify status should give me the status of my app

### Reproduction steps

amplify pull
make changes
amplify update api
amplify status

### Project Identifier

3719f5f550ffd4fb8c429a52aba28300

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @anu-IV :wave: thanks for raising this! As we begin to look at this in more depth, would you mind sharing the full error you're receiving and full reproduction steps? Is the CLI erroring reading a specific file? Does this error only occur with `amplify status`?

**Comment by anu-IV** [comment]
This issue is resolved for me now.

Thanks and Regards,
Anu.

From: josef ***@***.***>
Sent: Tuesday, January 3, 2023 11:03 AM
To: aws-amplify/amplify-cli ***@***.***>
Cc: Anubhuti Srivastava ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [aws-amplify/amplify-cli] UNKNOWN: unknown error, readlink (Issue #11612)


Hey @anu-IV<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanu-IV&data=05%7C01%7Casrivastava%40intervision.com%7C168069397242417adb2408daeda3f50d%7C52163c7cf4174149971e3e0cb126f714%7C1%7C0%7C638083585706130344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8Nyfthadf16NaPL8krlYUdQtQnE0jnmq3%2BAI%2BcOZ8Gs%3D&reserved=0> I wanted to follow-up on this one after the holiday season to see if you're still experiencing this?

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws-amplify%2Famplify-cli%2Fissues%2F11612%23issuecomment-1369941497&data=05%7C01%7Casrivastava%40intervision.com%7C168069397242417adb2408daeda3f50d%7C52163c7cf4174149971e3e0cb126f714%7C1%7C0%7C638083585706130344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T6F%2FNLFeXRQQvNFYLjgbqwc5Sm6iDGimBmZ7Ia4W%2FqA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLSWJQ3Y5XFIUCNKLULGXLWQRESLANCNFSM6AAAAAAS723FTU&data=05%7C01%7Casrivastava%40intervision.com%7C168069397242417adb2408daeda3f50d%7C52163c7cf4174149971e3e0cb126f714%7C1%7C0%7C638083585706286583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V11K3JelNQv66y%2Fvv66rnkLZytpvG%2B1jKV6kNIRnnx4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

STOP & THINK BEFORE you CLICK links and/or OPEN attachments! This is an EXTERNAL EMAIL.
We appreciate our valued clients & partners and take securing assets & information very seriously. If you suspect phishing, report using the "Phish Alert Report" button.
