### ISSUE TITLE
Permission Denied issue

### ISSUE THREAD

**Issue by sam1610** [aws-amplify/amplify-cli#11615]
### How did you install the Amplify CLI?

nom

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I grant  S3 permission to the AWS Cognito Group Admin. But later I rolled back everything, since  the app was working correctly before I upgrade to the latest  version of  aws-amplify/cli 

### Describe the bug

amplify started by not displaying any result of   any amplify  Cli commands like   amplify status with a waring message :
🛑 EACCES: permission denied, open '/Users/Folder/.amplify/logs/amplify-cli-2022-12-15.log'

### Expected behavior

I should have the status of my resources running on the cloud, 

### Reproduction steps

upgraded. was-amplify/cli

### Project Identifier

194b7f2d-80dd-4acc-b26e-55471d305c1f

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

EACCES: permission denied, open '/Users/folder/.amplify/logs/amplify-cli-2022-12-15.log'

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/folder/troubleshooting/

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @sam1610 :wave: thanks for raising this! How was the CLI originally installed? And how was Node.js installed? This appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/11592

**Comment by rahulnainwal107** [comment]
I am also facing this issue. CLI is installed using sudo npm install -g @aws-amplify/cli.
node version - 18.12.1
npm version - 8.19.2

**Comment by rahulnainwal107** [comment]
Yes, EACCESS issue was there without sudo but now I am using amplify CLI version 8.0.3 which seems to work fine.

**Comment by sam1610** [comment]
> Hey @sam1610 👋 thanks for raising this! How was the CLI originally installed? And how was Node.js installed? This appears to be similar to #11592

I installed  the CLI  :  sudo  npm install -g  @aws-amplify/cli .

**Comment by josefaidt** [comment]
Hey @sam1610 apologies for the delay here. Are you still experiencing this issue? Were you able to resolve the EACCESS issue by following the guide above? Alternatively you can assume ownership over the folders created in your home directory but owned by root (`chown -R
 ~/.amplify`)

**Comment by josefaidt** [comment]
Hey @sam1610 just wanted to follow up on this issue. Are you still experiencing this?

**Comment by sam1610** [comment]
it was  related to my Own set of security I implemented .   Get rid of it by simple use of a root Account .

**Comment by josefaidt** [comment]
Hey @sam1610 glad to hear you were able to find a solution! Closing issue

**Comment by jgnovakdev** [comment]
@josefaidt this solution worked for me, the `~/.amplify` directory was owned by root. `chown -R me:staff ~/.amplify` on macOS worked fine, where `me` is my username.

**Comment by marksteven** [comment]
Had similar result after upgrading Amplify cli.
Have taken the steps (above) with no result so far.
Can get around it by sudo amplify init for instance but would like to not have to do the sudo
In case it was an install issue Ive removed and reinstalled amplify cli and even gone into Users/me/.aws/ and tried to adjust ownership. No joy.
Further poking around and it seems like it might be a new Mac issue
read here
https://dev.to/aws-builders/aws-amplify-cli-installation-guide-m1m2-2022-mac-edition-3cm2
Following Brians advice I
# invoke a root shell by logging in as the root user
sudo -i

# change directory into your specific user you want to adjust
cd ~MYUSER

# change ownership of the `.amplify` file to MYUSER
chown -R MYUSER .amplify

What we just did was change the ownership of the hidden directory .amplify installed under our user. If you want to find where this is, run ls -al and you should see a list of directories, including .amplify

✅ PART 3: Test
In a separate terminal window, check if you can run amplify help. If you get a response back and the CLI is running the help command

Although help command now works I am still having to sudo amplify commands even time.
Any thoughts out there?
