### ISSUE TITLE
Amplify Geo: New map style (Open Data Maps)

### ISSUE THREAD

**Issue by dayjournal** [aws-amplify/amplify-cli#11620]
### Is this related to another service?

Amazon Location Service

### Describe the feature you'd like to request

A new map style was announced today, but has not yet been added to the Amplify CLI.

https://aws.amazon.com/jp/about-aws/whats-new/2022/12/amazon-location-service-open-data-maps-preview/

### Describe the solution you'd like

Add New map style to "amplify add geo" in Amplify CLI.

### Describe alternatives you've considered

Because it is difficult to work manually.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by evcodes** [comment]
Hey @dayjournal, thanks again for your contributions! Would you be able to open a PR in the docs site to reflect this new map style. Specifically adding to this code snippet: https://docs.amplify.aws/cli/geo/maps/#map-style--map-data-provider

**Comment by dayjournal** [comment]
Hi, @evcodes. I have made a pull request to Amplify Documentation.
https://github.com/aws-amplify/docs/pull/4964

**Comment by evcodes** [comment]
Thanks for the contribution. We have merged your changes into dev and we are pending release to make changes to docs site and close this issue. I will keep you posted.

**Comment by josefaidt** [comment]
Closing as this has since been released 🎉 thank you for your time and contribution @dayjournal ! 🙌
