### ISSUE TITLE
How to migrate amplify setup to client's AWS account

### ISSUE THREAD

**Issue by Tom-Sziler** [aws-amplify/amplify-cli#11635]
### Amplify CLI Version

10.4.1

### Question

Hello, 

I have a working Amplify backend with some data set up within it. Everything works in our mobile app as we would expect.

The client has recently asked us to move this whole amplify setup into their aws account. 

Is there a guide on how to do this? I found one page with a very non-detailed 3 step process on how to do it. 

When I try to run amplify init, as suggested in the guide, it just seemingly re-creates my existing setup in our own AWS account. I have already created a new project for this app in the client's aws account and I tired to run amplify init --appId <their app id> but that also does not work. I get an access denied error. 

Is there some kind of guide I can follow to do this ?

**Comment by josefaidt** [comment]
Hey @Tom-Sziler :wave: thanks for raising this! If you are looking to simply create the same infrastructure in another AWS account, you can run `amplify add env` which will prompt for the target account's credentials. When running `amplify init` are you getting the prompt for the target AWS account you'd like to use for the new environment?

**Comment by Tom-Sziler** [comment]
Hi @josefaidt, 

here's my process currently: 

Pull fresh clone of repo

Option 1: 
- Run `amplify init` Result: 
![Screen Shot 2022-12-20 at 4 19 48 PM](https://user-images.githubusercontent.com/19979228/208777872-5db17748-b827-4ee2-87dd-6c48697c00b3.png)


Option 2:
- Run `amplify add env` Result: 
![Screen Shot 2022-12-20 at 4 20 23 PM](https://user-images.githubusercontent.com/19979228/208777954-c44b3af7-c258-4459-aec1-cb2e393978ca.png)

**Comment by Tom-Sziler** [comment]
One more update - I tried using the existing staging env with amplify init, but got the same error: 
![Screen Shot 2022-12-20 at 4 24 37 PM](https://user-images.githubusercontent.com/19979228/208778507-d580993a-dc35-4afe-a6ce-7bfbccb78a50.png)

**Comment by Tom-Sziler** [comment]
It looks like I can no longer even use my app as is with my old account, I am not able to do any amplify init to get the project running. I keep getting the 'access denied' error

**Comment by josefaidt** [comment]
Hey @Tom-Sziler when you originally pulled this backend did you choose "No" to "Do you plan on modifying this backend?"

**Comment by Tom-Sziler** [comment]
@josefaidt I chose yes

**Comment by Tom-Sziler** [comment]
I'm wondering if it would be easier at this point to just re-create the entire backend setup on the client amplify account?

**Comment by Tom-Sziler** [comment]
Ok so I was able to revert everything to work with my original AWS account and use the existing env that we started with. 

I logged out of my aws account and logged into the client's aws account for which I have full admin access. 

I ran `amplify add env` in my terminal and it worked, but the problem is that it adds this env to my existing account/appId, NOT the intended client aws account.

![Screen Shot 2022-12-21 at 9 04 21 AM](https://user-images.githubusercontent.com/19979228/208936459-a1193f8c-686a-4995-b7b8-997a6a71b01b.png)

**Comment by Tom-Sziler** [comment]
I ran the command again and used AWS profile as the authentication method and it looks like it succeeded again, but this time it added to an appId I have not seen. This is not the appId of my account nor the client aws account: 
![Screen Shot 2022-12-21 at 9 08 38 AM](https://user-images.githubusercontent.com/19979228/208937398-a3d4a7cd-516e-42f4-b18d-d803f648a49d.png)

**Comment by josefaidt** [comment]
Using "Amplify Studio" as the auth mechanism will deploy the environment to your current account

**Comment by Tom-Sziler** [comment]
@josefaidt where would I find that amplify/.config/local-aws-info.json file? I don't see it in my project in the amplify directory

**Comment by josefaidt** [comment]
Hey @Tom-Sziler thanks for clarifying! Is your `default` AWS profile pointing to the client's AWS account?

**Comment by Tom-Sziler** [comment]
@josefaidt How would I check that?

**Comment by Tom-Sziler** [comment]
Hey just wanted to reach back out - I did figure out how to change the profile to point at the client and got everything correctly moved over. After this whole experience, I can say that I wish the process was more clearly outlined in the docs because this was pretty tough to do

**Comment by josefaidt** [comment]
Hey @Tom-Sziler apologies for the delay here!! I'm glad to hear you were able to get things set up and moved over despite the experience. Do you have any particular callouts on the difficulties of setting this up? I'd like to use this information to improve the documentation 🙂

**Comment by Tom-Sziler** [comment]
Hi @josefaidt Yes, I got this all figured out. No specific callout, but the docs were pretty unclear. If I recall, it's a single page with a 3 step instruction list and not much context.
