### ISSUE TITLE
Auth - modifying attribute mapping for Identity Providers 

### ISSUE THREAD

**Issue by andreav** [aws-amplify/amplify-cli#11646]
### Amplify CLI Version

10.5.2

### Question

I have a working federated signIn with Google and Facebook.

I would like to retrieve name attribute from Identity Providers.

I think I need to add a new Attribute mapping "name" <--> "name".
From Aws Console it is here:

![image](https://user-images.githubusercontent.com/1358304/209167078-99cc8910-954e-4e6b-901b-3d48547d7270.png)

I tried manually changing `hostedUIProviderMeta` field inside `cli-inputs.json` + `amplify push auth` but it did not work (something similar to [this](https://github.com/aws-amplify/amplify-cli/issues/4981#issuecomment-666019896)) 

```
{
  "hostedUIProviderMeta": [
    {
      "ProviderName": "Facebook",
      "authorize_scopes": "email,public_profile",
      "AttributeMapping": { "email": "email", "username": "id", "name": "name" }
    },
    {
      "ProviderName": "Google",
      "authorize_scopes": "openid email profile",
      "AttributeMapping": {
        "email": "email",
        "username": "sub",
        "name": "name"
      }
    }
  ]
}

```

How can I accomplish it?

Thank you.

**Comment by josefaidt** [comment]
Hey @andreav :wave: thanks for raising this! This seems like a great question for our [community Discord server](https://discord.gg/invite/amplify)!

When creating the auth resource with `amplify add auth` we will be prompted for the required attributes upon signup:

```
What attributes are required for signing up? Email, Name
```

Upon selecting "email" and "name", and adding Facebook as a social provider we see the following attribute mapping in the auth's `cli-inputs.json`

```json
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Facebook\",\"authorize_scopes\":\"email,public_profile\",\"AttributeMapping\":{\"email\":\"email\",\"name\":\"name\",\"username\":\"id\"}}]",
```

Please note you will only be prompted for the required attributes during the initial creation of the auth resource. As shown below, updating the resource does not prompt for required attributes:

```
➜  amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, 
Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images
 or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control 
via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry
 at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use? 1164612cab279-12cab279
 Enter your redirect signin URI: http://localhost:3000/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:3000/
? Do you want to add another redirect signout URI No
 Select the OAuth flows enabled for this project. Authorization code grant
 Select the OAuth scopes enabled for this project. Phone, Email, OpenID, Profile, aws.
cognito.signin.user.admin
 Select the identity providers you want to configure for your user pool: Facebook
```

**Comment by andreav** [comment]
Thank you for your super fast response!
I will try removing and re-adding auth category as soon as possible and let you know.

**Comment by josefaidt** [comment]
Hey @andreav let me know how it goes! And I agree with you, would you mind adding a 👍 to this feature request? https://github.com/aws-amplify/amplify-cli/issues/7835

**Comment by andreav** [comment]
Hello @josefaidt!
I got it working exactly as you said, thank you.

As a minor note: now I have a new "Name" field in the SingUp with cognito form (as expected). 
Is it possible to hide it?

**Comment by sakaal** [comment]
I have almost the same issue, and I know how to handle it with required attributes, like explained above. However,  I want to map _optional_ attributes.

Sign in with Apple does not always return the name, if the user has decided to keep it private. So, to allow smooth sign-up experience, I need to make name optional. When I do this, Amplify configures Cognito completely without the name attribute mapping, so the name is not recorded even if it was present.

How can I achieve social identity provider attribute mapping for optional attributes?

**Comment by Ykauji** [comment]
+1 on this issue @sakaal mentioned. I want to be able to set them as optional, or perhaps with a default fallback value so we can keep our sign-in experience smooth.
