### ISSUE TITLE
Can't pull app with geo.

### ISSUE THREAD

**Issue by sobolk** [aws-amplify/amplify-cli#11641]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.20.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

Can't pull app after just adding geo and pushing.

### Expected behavior

App with geo can be pulled.

### Reproduction steps

1. amplify init -y
2. amplify add geo and follow defaults
3. amplify push
4. amplify pull

### Project Identifier

Session Identifier: c00d5b63-8269-41fe-8578-6e63c67294d3

### Log output

see screenshot
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5849952/208955869-21f6d80a-d458-436d-ad8d-b1187870c4d0.png">

### Additional information

.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @sobolk :wave: thanks for raising this! I am not able to reproduce using the provided steps. As a follow-up:

- can you post the project ID output from `amplify diagnose --send-report`?
- if you inspect the `amplify/team-provider-info.json` file do you see an `AmplifyAppId` set in the environment? (perhaps you've hit the app limit?)

**Comment by josefaidt** [comment]
Can you run `amplify init` again and choose your existing environment? This should generate the corresponding App ID

It appears you're affected by this issue https://github.com/aws-amplify/amplify-cli/issues/10838

**Comment by sobolk** [comment]
The app limit was the problem. Thank you @josefaidt .
