### ISSUE TITLE
Unable to add REST API: "There was an error adding the API resource"

### ISSUE THREAD

**Issue by benjaminliang2** [aws-amplify/amplify-cli#11656]
### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

Windows 10.0.19044

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made. 

### Describe the bug

Unable to add Rest API. Running `amplify add api` prompts me to select Rest or Graphql. Selecting either one produces error message. However, running `amplify status` after attempting to add REST api will show nothing, but it will show an api was added after attempting to add GraphQL 
![0](https://user-images.githubusercontent.com/28040242/209417367-5df501ff-0812-42bc-b943-bd6eb5576cbc.png)

### Expected behavior

Expect Rest API to be added. 

### Reproduction steps

`npm install -g @aws-amplify/cli expo-cli `
`npx create-expo-app amplified_todo`
`cd amplified_todo`
`amplify configure`
`amplify init`
`amplify add api`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @benjaminliang2, thank you for reaching out. Does this behaviour also occur on a different terminal. Could try using CMD or Powershell and let us know if a similar behaviour occurs?

**Comment by benjaminliang2** [comment]
Using CMD works! I have tried powershell before I get the same issue. Thanks!
