### ISSUE TITLE
How to create a new amplify nextjs application using existing dynamodb tables?

### ISSUE THREAD

**Issue by bipinparmar** [aws-amplify/amplify-cli#11688]
### Amplify CLI Version

 10.5.2

### Question

Hi contributors,

I have an amplify react (SPA) application with DynamoDB as the database. The DynamoDB tables currently have 12 tables (e.g. <model>-caqdgcpfbepxjmaoqdv5wsqbtm-dev), and a few contain 500K+ items. I recently decided to change my application to SSR and plan to use amplify with nextjs. I went through the tutorial on AWS and did not find any way for the new application to use the existing DynamoDB tables. The tutorial created a new set of DynamoDB tables (e.g., <model>-lbcfeyzzdgadftfslrzajlfywm4-dev). 

I am hesitant to copy data from old tables to new tables as the tables have a lot of data and are constantly updated using offline jobs. Is there a way that I can create an amplify nextjs application and connect my models to use the existing DynamoDB tables

I look forward to your help. 

Bipin

**Comment by josefaidt** [comment]
Hey @bipinparmar :wave: thanks for raising this! To better understand the question, are your existing DynamoDB tables from an existing Amplify project? And you're wanting to use that same API in your new Amplify project?

**Comment by bipinparmar** [comment]
Yes, the existing DynamoDB tables are from an existing Amplify (React) project. This existing project was created using "npx create-react-app react-amplified".  For nextjs, I am using "npx create-next-app next-amplified". 

I am not planning to keep both applications. I have okay to get help on either of these two options:
1. Make next-amplified application use the dynamodb tables created from the react-amplified application. Once I am successful, I will delete the react-amplified application
2. Update the react-amplified application to support SSR with nextjs

**Comment by josefaidt** [comment]
Hey @bipinparmar thanks for clarifying! Given the current limitation of not being able to import an existing GraphQL API, it is possible to run `amplify pull` into your new Next.js app to pull the existing project which will also pull the GraphQL API. From here you can select "Yes" to "do you plan on modifying this project" and use a different environment to change the hosting settings (for SSR) before going live with Next.js.

**Comment by bipinparmar** [comment]
If I use a different environment, will it not create a new set of Dynamodb tables using that environment and the new tables will be empty instead of containing the data from the existing tables?

**Comment by bipinparmar** [comment]
Based on your feedback, I followed these steps:
> npx create-next-app next-amplified
> cd next-amplified
Commit the project to a new git repo
> amplify pull 
The new app connected to the existing backend with the existing database. It pulled the schema. Now it looks like I will have to keep both git repos. I can update the models from both git repos. 

I want to delete the old git repo but I see this message when I execute amplify delete. I think that if I say yes, it will delete the backend and the databases. Will it?
>>>
Are you sure you want to continue? This CANNOT be undone. (This will delete all the environments of the project from the cloud and wipe out all the local files created by Amplify CLI)
<<<

**Comment by bipinparmar** [comment]
It looks I cannot connect another frontend that is not from the same repo. So my new nextjs application has to be in the same repo but different branch.

**Comment by josefaidt** [comment]
Hey @bipinparmar that is correct, `amplify delete` will delete the project including the Amplify project and corresponding backend. 

> It looks like I cannot connect another frontend that is not from the same repo. 

Ah, then yes I would suggest using a separate branch to rewrite the frontend with

**Comment by bipinparmar** [comment]
Hi @josefaidt in my haste to get the project going, I selected the new frontend with the existing backend (one that had data in dynamodb) on the AWS Amplify Console page. On my next commit, the frontend was built and the deployment created a new set of tables with empty data. The tables with data were deleted. I had not taken any backup nor did I have any auto backup. Life goes on. Amplify is not a good solution for large-scale applications IMO.
