### ISSUE TITLE
Amplify builds losing connection to github repo, and then failing to find AWS credentials after configuring.

### ISSUE THREAD

**Issue by Dagon-R** [aws-amplify/amplify-cli#11686]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes were made

### Describe the bug

My amplify app is consistently failing to build. 
Firs, it states `There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again`, which resolves itself without requiring a login on my part.
Then, it will state that `🛑 AWS access credentials can not be found.`. I have properly configured the Amplify CLI multiple times, and it was working previously. The only change is that I have added auth, following part 3 of [this guide](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/?ref=gsrchandson&id=updated).

### Expected behavior

Amplify app builds properly.

### Reproduction steps

1. Following [this guide](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/?ref=gsrchandson&id=updated):
2. Create a react app using npm create-react-app
3. Initialize a github repo and deploy it to a new amplify app, and then initialize the app locally.
4. Add auth with amplify, configure the project to use the auth resources and configure the app to display the auth interface.
5. Configure the backend into the CI/CD
6. Push the code changes to github, and wait for amplify to attempt to build.

### Project Identifier

[report-1672446547228.zip](https://github.com/aws-amplify/amplify-cli/files/10326608/report-1672446547228.zip)

### Log output

<details>

```
# Put your logs below this line
# Starting phase: build
2022-12-31T00:26:20.658Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-12-31T00:26:21.254Z [INFO]: 🛑 AWS access credentials can not be found.
2022-12-31T00:26:21.254Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2022-12-31T00:26:21.265Z [INFO]: 
2022-12-31T00:26:21.265Z [INFO]: Session Identifier: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2022-12-31T00:26:21.334Z [ERROR]: !!! Build failed
2022-12-31T00:26:21.334Z [ERROR]: !!! Non-Zero Exit Code detected
2022-12-31T00:26:21.334Z [INFO]: # Starting environment caching...
2022-12-31T00:26:21.334Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Dagon-R, Thank you for reaching out. Could you provide us the AppID? This can be found in the URL of your Amplify console application or at the end of the application Arn found under General option under App settings on the left side bar.

Additionally, could you also check if the Amplify hosting environment has a service role attached? this can also be found under the General option under App settings on the left side bar. if not, could you create a service role as suggested in https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html ,attach the role and retry the build.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/87995712/210391636-1c46bc30-efab-45f4-a84d-5553d00a29e2.png">

**Comment by Dagon-R** [comment]
Ok, the service role had gotten cleared, and that was what was causing the issue. Thank you for the help!

**Comment by ykethan** [comment]
Hey @Dagon-R, thank you for the confirmation. Please feel free in reaching out to us again, we would be happy in assisting you.
Closing the issue.

**Comment by ecumartesi** [comment]
Hello my amplify keeps telling me that there was an issue conneting to my repo when i try building for a second time
