### ISSUE TITLE
Wrong setting when using custom domain

### ISSUE THREAD

**Issue by sametkabay** [aws-amplify/amplify-cli#11692]
If you provide a custom auth.mydomain.com for OAuth in cognito, every time you run amplify push it overwrites aws-exports.js and changes:

`oauth: {
   domain: auth.mydomain.com --> gets changed to . "appname-env.auth.region.amazoncognito.com"
}`

https://github.com/aws-amplify/amplify-cli/blob/06300cc1444bf6e018cc50e18f9cce1967e00426/packages/amplify-frontend-javascript/lib/frontend-config-creator.js#L359-L362

If a custom domain name is used, '.auth.region.amazoncognito.com' should not be added to the end

**Comment by josefaidt** [comment]
Hey @sametkabay :wave: thanks for raising this! Would you mind porting this over to one of our issue templates?

**Comment by sametkabay** [comment]
@josefaidt I did. https://github.com/aws-amplify/amplify-cli/issues/11706
