### ISSUE TITLE
Google sign in not working since latest version of amplify-cli

### ISSUE THREAD

**Issue by ivan-georgiev-zetta** [aws-amplify/amplify-cli#11704]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.6.0

### What operating system are you using?

AWS Amplify default build container (amazonlinux:2)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes, same backend resources work with amplify ci/cd when setting `Amplify CLI` to 10.5.2 in AWS Console -> Amplify -> Build Settings -> Build image settings

### Describe the bug

When pushing to the connected branch, amplify CI/CD triggers and redeploys the backend and hosting environments. During redeploy, even though we don't have any auth or Cognito changes, we receive:
```
The following resources failed to deploy:
                                 Resource Name: HostedUIProvidersCustomResourceInputs (Custom::LambdaCallout)
```
When checking the lambda that is called by the Auth CFM template, the error there is:
```
InvalidParameterException: client_id, client_secret and authorize_scopes are all required idp details.    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) | 2023-01-04T09:58:48.250Z 4a312ff4-4a2a-4dc8-8d06-20e94d46de12 INFO InvalidParameterException: client_id, client_secret and authorize_scopes are all required idp details. at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
-- | --
```

We have correct `AMPLIFY_GOOGLE_CLIENT_ID`, `AMPLIFY_GOOGLE_CLIENT_SECRET` in AWS Amplify Console and `auth` category in team-provider-info.json.

If we change the Amplify CLI version like this:
![image](https://user-images.githubusercontent.com/45260208/210568622-59e4e93d-b845-482f-9fa9-6a8ec73db71b.png)
and then redeploy using the `Redeploy this version` button, everything works as expected.

### Expected behavior

1. Backend and Hosting redeploy passes

### Reproduction steps

1. Push something to an Amplify CI/CD connected branch

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @ivan-georgiev-zetta :wave: thanks for raising this! As we begin to dive deeper into your issue would you mind posting the project ID output from `amplify diagnose --send-report` or post the contents of `amplify/backend/auth/<resource-name>/cli-inputs.json`?

**Comment by caesarisme** [comment]
+1

10.6.0 have broken google auth as well as all cognito triggers in my project

**Comment by jeffking54** [comment]
+1 On this, I had to revert to 10.5.2 in my build, same issue as cognito triggers not working

**Comment by josefaidt** [comment]
Hey @jeffking54 :wave: thanks for chiming in here! What issues are you seeing for your Cognito triggers?

**Comment by ivan-georgiev-zetta** [comment]
> amplify diagnose --send-report

Hi @josefaidt , here is the Project Identifier: b6679eb3bdf3715e8cc6bef2b1a39fa6. Also here are the contents of an auth cli-inputs.json:
```
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "***_identity_pool",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "***b44969ad",
    "userPoolName": "***",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": "6",
    "passwordPolicyCharacters": [
      "Requires Lowercase",
      "Requires Uppercase",
      "Requires Numbers",
      "Requires Symbols"
    ],
    "requiredAttributes": [
      "email",
      "given_name"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "address",
      "birthdate",
      "family_name",
      "middle_name",
      "gender",
      "locale",
      "name",
      "nickname",
      "phone_number",
      "preferred_username",
      "picture",
      "profile",
      "updated_at",
      "website",
      "zoneinfo",
      "email",
      "given_name",
      "custom:country",
      "custom:timezone",
      "custom:default_org",
      "custom:secondaryAccounts",
      "custom:primaryAccount",
      "custom:first_day"
    ],
    "userpoolClientReadAttributes": [
      "address",
      "birthdate",
      "email",
      "family_name",
      "middle_name",
      "gender",
      "locale",
      "given_name",
      "name",
      "nickname",
      "phone_number",
      "preferred_username",
      "picture",
      "profile",
      "updated_at",
      "website",
      "zoneinfo",
      "email_verified",
      "phone_number_verified",
      "custom:country",
      "custom:timezone",
      "custom:default_org",
      "custom:linkedAccounts",
      "custom:secondaryAccounts",
      "custom:primaryAccount",
      "custom:first_day"
    ],
    "userpoolClientLambdaRole": "***b44969ad_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": true,
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "***",
    "serviceName": "Cognito",
    "useDefault": "manual",
    "sharedId": "b44969ad",
    "userPoolGroupList": [],
    "userPoolGroups": false,
    "usernameAttributes": [
      "email"
    ],
    "usernameCaseSensitive": false,
    "adminQueries": false,
    "hostedUI": true,
    "hostedUIDomainName": "***",
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"given_name\":\"given_name\",\"username\":\"sub\"}}]",
    "authProvidersUserPool": [
      "Google"
    ],
    "thirdPartyAuth": true,
    "authProviders": [],
    "triggers": {},
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": false,
    "useEnabledMfas": false,
    "dependsOn": [],
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"implicit\",\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"https://staging.***.com/federated/\",\"http://localhost:8080/federated/\"],\"LogoutURLs\":[\"https://staging.***.com/\",\"http://localhost:8080/\"]}",
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "permissions": []
  }
}
```

**Comment by jeffking54** [comment]
> 

The error in the logs on build is:

`2023-01-04T20:33:44.022Z [INFO]: UPDATE_FAILED AuthTriggerCustomLambdaStack AWS::CloudFormation::Stack Wed Jan 04 2023 20:33:39 GMT+0000 (Coordinated Universal Time) Output 'LambdaExecutionRoleArn' not found in stack 'arn:aws:cloudformation:us-west-2:XXXXXXXXX:stack/amplify-XXXXXXX-devo-140654-functionXXXXXXXXXXX18668adbPreSignup-1M7YAGTGWPLV0/6e2584f0-XXXX-XXXX-XXXX-0a21a37cbb4d'`

Nothing in the backend changed between the previous working deployment and this one.

**Comment by josefaidt** [comment]
Hey @jeffking54 I was able to reproduce the error you are receiving using the following steps. The oauth capabilities may not be necessary here but I wanted to simulate the setups described in this thread

1. install Amplify CLI 9.1.0
1. `amplify init -y`
2. `amplify add auth` > manual
  1. add facebook, google
  2. add PostConfirmation and Pre-Signup triggers
3. `amplify push -y` we want to be sure we've pushed with an older version of the CLI
4. create git repo and push `git init; gh repo create --source . --public; git add .; git commit -m '🚀'; git push -u origin main`
5. add hosting with Amplify Hosting `amplify add hosting`
6. the above step will trigger an automatic build which will fail looking for OAuth env vars
7. add the OAuth env vars
8. redeploy the failed build (Amplify Hosting by default will use the latest CLI version - 10.6.0)
9. observe build failure with:

```
2023-01-05T22:12:42.651Z [INFO]: UPDATE_COMPLETE auth117045ba02d0b            AWS::CloudFormation::Stack Thu Jan 05 2023 22:12:40 GMT+0000 (Coordinated Universal Time)
UPDATE_FAILED   AuthTriggerCustomLambdaStack AWS::CloudFormation::Stack Thu Jan 05 2023 22:12:42 GMT+0000 (Coordinated Universal Time) Output 'LambdaExecutionRoleArn' not found in stack 'arn:aws:cloudformation:us-east-1:814763596509:stack/amplify-11704-dev-134934-function117045ba02d0bPreSignup-19T64TCCNSPTS/b703fad0-8d43-11ed-991a-0ad83960a94d'
```

Continuing to investigate the OAuth issues, however I will mark this as a bug

**Comment by josefaidt** [comment]
To add on to my note above, upon encountering the error related to `AuthTriggerCustomLambdaStack` please upgrade your Amplify CLI locally and run `amplify push` manually. From here you will notice a [few changes](https://github.com/josefaidt/11704/commit/afc6f39afb1be3372ad34f1094622bbaf9000dcf), and further pushes to git will successfully build in Amplify Hosting

**Comment by josefaidt** [comment]
Moving to `pending-triage` to track Cognito Trigger issue separately in #11714

**Comment by josefaidt** [comment]
Hey @ivan-georgiev-zetta :wave: are you still experiencing this issue with the [latest version of Amplify CLI (10.7.2)](https://github.com/aws-amplify/amplify-cli/releases/tag/v10.7.2)?

**Comment by ivan-georgiev-zetta** [comment]
> Hey @ivan-georgiev-zetta 👋 are you still experiencing this issue with the [latest version of Amplify CLI (10.7.2)](https://github.com/aws-amplify/amplify-cli/releases/tag/v10.7.2)?

Hi @josefaidt , same error if I the use the latest version in the AWS console:

```
he following resources failed to deploy:
                                 Resource Name: HostedUIProvidersCustomResourceInputs (Custom::LambdaCallout)
                                 Event Type: update
                                 Reason: Received response status [FAILED] from custom resource.
```
And the logs of the CFT lambda:
```
"client_id, client_secret and authorize_scopes are all required idp details."
```

**Comment by kimfucious** [comment]
I got the same thing as mentioned [here](https://github.com/aws-amplify/amplify-cli/issues/9183#issuecomment-1435654362)

**Comment by josefaidt** [comment]
Hey @ivan-georgiev-zetta thanks for clarifying, and @kimfucious great callout. The following error message will be tracked as a part of #9183

```
client_id, client_secret and authorize_scopes are all required idp details.
```

As a workaround, run `amplify update auth` and step through the `Update OAuth...` prompt to re-enter your social credentials to run `amplify push` successfully.

Marking as a duplicate bug of #9183 and closing in favor of tracking the existing item.

**Comment by ivan-georgiev-zetta** [comment]
@josefaidt just keep in mind, the problem in here is only present after amplify cli 10.5.2 and only in the AWS console/automated amplify CICD. If we try to push locally, we are able to, so I am not sure the case is the same as https://github.com/aws-amplify/amplify-cli/issues/9183.

I think the difference is that locally we rely on deployment-secrets.json, but on the AWS Console there are `AMPLIFY_GOOGLE_CLIENT_ID` and `AMPLIFY_GOOGLE_CLIENT_SECRET`, which do not get respected after 10.5.2.
