### ISSUE TITLE
🛑 EBUSY: resource busy or locked, rmdir 'C:\Users\hp\.amplify\lib\amplify-dynamodb-simulator\emulator'

### ISSUE THREAD

**Issue by KinyanjuiJonathan** [aws-amplify/amplify-cli#11705]
🛑 EBUSY: resource busy or locked, rmdir 'C:\Users\hp\.amplify\lib\amplify-dynamodb-simulator\emulator'

This error has appeared after the upgrading amplify

**Comment by josefaidt** [comment]
Hey @KinyanjuiJonathan :wave: thanks for raising this! To better assist, would you mind porting this over to one of our [issue templates](https://github.com/aws-amplify/amplify-cli/issues/new/choose)?

**Comment by IvanFarkas** [comment]
I am getting it too

**Comment by innovimia-cto** [comment]
+1 - after upgrade

**Comment by 9037568** [comment]
Y'all could have fixed this bug 4 months ago, but chose not to because... ?
