### ISSUE TITLE
Amplify backend pull failed in web host app

### ISSUE THREAD

**Issue by diptigajjar** [aws-amplify/amplify-cli#11710]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.18.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

Amazon Linux 2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

We have set the CI/CD pipeline in amplify and since 22nd Dec the backend build is getting failed and throwing the error "Failed to pull the backend" as per the attached screenshot,

![build-error](https://user-images.githubusercontent.com/37132582/210712439-c043e439-6a8c-49dd-b76a-b1d42ccc50ba.png)

### Expected behavior

The build should be successfully completed. Here I'm attaching the last successful build screenshot, 

![build-success](https://user-images.githubusercontent.com/37132582/210712913-c90afe2e-16e3-4895-b81e-4febe284667a.png)

### Reproduction steps

1. Push any changes in the connected repository or redeploy any build version whether it is a success or failed.

### Project Identifier

7c9d13f9ca0676c32a6077bff44f9da2

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @diptigajjar, thank you for reaching out. Could you provide us the AppID, environment and failed build number?
additionally, could you provide us some additional information on the changes made when the build started to fail.

**Comment by diptigajjar** [comment]
> Hey @diptigajjar, thank you for reaching out. Could you provide us the AppID, environment and failed build number? additionally, could you provide us some additional information on the changes made when the build started to fail.

Hi @ykethan, please find the below details,
Web hosting AppID: d9di8grn1vkqy
Backend AppId: d1dr9766vtvftc
Environment: ddlfstg,
Failed build number: Build 288

See the below screenshot, those are the only changes we did, and the build started to fail.
![failed build changes](https://user-images.githubusercontent.com/37132582/210932327-18d58be7-83c5-43eb-885b-5b643f52d9b7.png)

**Comment by biller-aivy** [comment]
@diptigajjar are you on a mac? Can you try to download the current-cloud-backend.zip from the backend deployment bucket on s3?

**Comment by ykethan** [comment]
Hey @diptigajjar, I understand that the Amplify project utilizes a different application for front end and a different application for the backend. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/11072. Could you try adding the `AMPLIFY_BACKEND_PULL_ONLY` environment variable in your hosting/console Amplify application and also uncheck the fullstack CI/CD option, as this would only perform a pull on the backend and skip the init process. Refer to https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html for additional information on the supported environment variables.

**Comment by diptigajjar** [comment]
@ykethan the environment variable is set to true and we uncheck the CI/CD option, but still facing the same issue.

**Comment by ykethan** [comment]
Hey @diptigajjar, thank you for the information. If the `current-cloud-backend` may have been overridden we may have to
1. navigate to the s3 console and identify the deployment bucket for our app
2. download `#current-cloud-backend.zip`
3. unzip the contents, correct the files that may have been overridden, and re-zip the folder
4. re-upload the newly zipped archive to our s3 deployment bucket
5. deploy again

cc @biller-aivy on additional information information and confirmation on the remediation steps as the project setup is similar.

**Comment by biller-aivy** [comment]
@ykethan its time to create the deployment buckets with versions option on. I use this every time when it's broken again. This could help other persons in such situations too. It's hard when you must deploy ant can't.

**Comment by ykethan** [comment]
cc @swaminator @josefaidt for visibility on the use case.

**Comment by copeus** [comment]
same issue

**Comment by josefaidt** [comment]
Closing in favor of tracking #11072
