### ISSUE TITLE
How to safely delete a branched frontend that uses a shared backend?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#11746]
### Amplify CLI Version

10.6.1

### Question

Pre-Christmas we set up a new front end (called prod-2) by branching our existing production one in github. The CI will build this if we push just like any other branch. This branch was set to use an existing backend (I think this might have been done via Amplify Console rather than the CLI).

Turns out we don't need that new prod-2 frontend anymore and I want to delete it but I'm a little scared that it might delete the backend too...which is the live production backend! I've removed the backend link in the console for this frontend:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1674590/211809259-7ea33adb-4216-40d2-ae17-0bed5a9600cf.png">

There doesn't seem to be much advice or feedback or reassurance in the console about what will happen if I delete the frontend...will it kill off the backend too?

Under the "General" menu I can select the frontend and then in the Actions drop down select "Disconnect branch" which I think is the way to go about it. Or should I be doing this via the CLI? As I'm unsure if we set this up with the UI or not I'm not sure. I was thinking delete it in the UI should be fine?

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1674590/211809693-83fdd819-183a-4104-9601-ed49e7aa95c4.png">

When trying to "give it a go" at using the disconnect I always back off at this screen, to me its unclear if it will delete anything I don't want it to:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/1674590/211809928-e19ee711-e273-423a-8140-de21e7e014f9.png">

Can someone give me some pointers to smooth my nerves over about the best/correct way to remove this frontend?

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: 

> Under the "General" menu I can select the frontend and then in the Actions drop down select "Disconnect branch" which I think is the way to go about it. Or should I be doing this via the CLI? As I'm unsure if we set this up with the UI or not I'm not sure. I was thinking delete it in the UI should be fine?

Yes you are correct. From this menu we are able to disconnect the branch, which will remove the frontend and build history, but leave the backend environment untouched.
