### ISSUE TITLE
Allow renaming resources after initial creation

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#11757]
### Amplify CLI Version

10.6.1

### Question

For example, after executing the command `amplify add auth`, is it possible to rename the name of `auth` stack?

**Comment by josefaidt** [comment]
Hey @yaquawa :wave: thanks for raising this! Unfortunately it is not possible to rename the resource after the initial creation with Amplify CLI

**Comment by yaquawa** [comment]
@josefaidt Thanks got it🥲

**Comment by josefaidt** [comment]
Hey @yaquawa after looking into this feature request a bit further, this is not achievable given the CLI is creating Infrastructure-as-code and changing resource names will cause the old resource to be deleted in favor of the new resource. Please see [this comment](https://github.com/aws-amplify/amplify-cli/issues/165#issuecomment-422188208) on an older, similar feature request.

Closing issue
