### ISSUE TITLE
How to add FromAddress, Identity and RoleArn To Environment - Can't Remove Email Channel

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-cli#11768]
### Amplify CLI Version

10.6.1

### Question

I ran this ----

amplify update notifications
✔ Choose the notification channel to configure · Email
The Email channel is currently enabled
✔ Do you want to disable the Email channel (y/N) · yes
🛑 FromAddress, Identity or RoleArn is missing for the Email channel

Resolution: Provide the required parameters for the Email channel
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 3b2c9940-05e1-4947-875d-a56a7a421879

----

I didn't add the email channel myself, but when I run 'amplify update notifications' I don't see a prompt for any of these things. 

amplify update notifications
✔ Choose the notification channel to configure · Email
The Email channel is currently enabled
✔ Do you want to disable the Email channel (y/N) · no
✔ The 'From' Email address used to send emails · MYEMAIL
✔ The ARN of an identity verified with SES · MYARN
✔ The ARN of an IAM Role used to submit events to Mobile notifications' event ingestion service ·
✔ The Email channel has been successfully updated.

Where do I add them?

**Comment by josefaidt** [comment]
Hey @mjmostachetti :wave: thanks for raising this! While we have a few active bugs for notifications, it appears the missing inputs are coming from the following prompts:

```
✔ The 'From' Email address used to send emails · MYEMAIL
✔ The ARN of an identity verified with SES · MYARN
✔ The ARN of an IAM Role used to submit events to Mobile notifications' event ingestion service ·
```

Do you see this information captured in `amplify/team-provider-info.json` or `amplify/backend/backend-config.json`?

**Comment by mjmostachetti** [comment]
None of my inputs from those 3 questions are anywhere in the solution.

**Comment by mjmostachetti** [comment]
@josefaidt Are there any work arounds for this? Any ETA on a fixes for the notifications bugs?

**Comment by ykethan** [comment]
Hey, I was able to reproduce the issue. marking this as bug. Looking into workarounds.

**Comment by fujimonfn** [comment]
Notifications (and analytics) resource by Amplify is kind of buggy...
I managed to create notifications resource on dev env, but when I try to add new environment, it doesn't work.
![image](https://user-images.githubusercontent.com/22267438/213681919-04de9a88-6826-4f7e-b888-85be16afb718.png)

Once I run into it, I can't remove thoese resources ("amplify remove notifications" aloso fails with error "Cannot read property 'Id' of undefined")

Please help.

**Comment by ykethan** [comment]
Hey @fujimonfn, To mitigate the issue I was able to find a workaround. Please find the steps as follows.

For the error: `FromAddress, Identity or RoleArn is missing for the Email channel`

1. find the `.vscode` folder and set flag with `amplify/backend/amplify-meta.json` as false. As the file will be hidden in vscode.
2. open the `amplify-meta.json` file under the `amplify/backend` directory.
3. find `notifications` and under `outputs` add `RoleArn` with its value.

Then run `amplify update notifications` or `amplify remove notifications` to disable or remove notifications.
The team has been made aware into the situation on the error `Missing required key ApplicationId in params`. A PR is currently in place to mitigate this. Please refer to https://github.com/aws-amplify/amplify-cli/pull/11494

**Comment by josefaidt** [comment]
This is related/similar to https://github.com/aws-amplify/amplify-cli/issues/11819

**Comment by lazpavel** [comment]
Thiis issue will be fixed with the released of this [PR](https://github.com/aws-amplify/amplify-cli/pull/11883)
