### ISSUE TITLE
Cannot run amplify configure command in windows

### ISSUE THREAD

**Issue by icodenerd** [aws-amplify/amplify-cli#11765]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.13.0

### Amplify CLI Version

it's giving me error when running any amplify command

### What operating system are you using?

Windows 10 Enterprise

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

If I run any amplify command, it's giving me this error:

Downloading release from https://package.cli.amplify.aws/10.6.1/amplify-pkg-win-x64.tgz
Error fetching release: unable to verify the first certificate

### Expected behavior

I was hoping it would pop up some AWS login window in the browser.

### Reproduction steps

1. Run this command: npm install -g @aws-amplify/cli after verifying npm and node versions
2. Run this command: amplify configure
3. Error is being displayed as shown below:
Downloading release from https://package.cli.amplify.aws/10.6.1/amplify-pkg-win-x64.tgz
Error fetching release: unable to verify the first certificate

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @icodenerd :wave: thanks for raising this, and apologies for the delay here! Are you still experiencing this issue? Are you working behind a corporate proxy or VPN that would prohibit this connection? For what it's worth logs are captured to `~/.amplify/logs`, which may provide additional insight here.

**Comment by icodenerd** [comment]
> Hey @icodenerd 👋 thanks for raising this, and apologies for the delay here! Are you still experiencing this issue? Are you working behind a corporate proxy or VPN that would prohibit this connection? For what it's worth logs are captured to `~/.amplify/logs`, which may provide additional insight here.

Yes sir, I am working behind a corporate proxy. I couldn't find any additional information from the log files per your suggestion by the way

**Comment by josefaidt** [comment]
Hey @icodenerd thanks for clarifying! I would suggest taking a look at network issues related to Node.js behind a corporate proxy. For example, you can extend the Node.js certificate store by setting `NODE_EXTRA_CA_CERTS` https://nodejs.org/api/cli.html#node_extra_ca_certsfile

**Comment by icodenerd** [comment]
@josefaidt, I was able to resolve it by working with the security team. Thanks for your responses by the way.
