### ISSUE TITLE
How to change the permission for "Auth Role" of identity pool ?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#11769]
### Amplify CLI Version

10.6.1

### Question

After running `amplify add auth` Amplify created a "Auth Role" for identity pool like `amplify-PROJECT_NAME-stg-101337-authRole`.

Is it possible to change the content of the created policies in this role?
If it's not possible how to add some custom policies to this role?

In my case I want add an additional `s3:PutObjectAcl` permission to the created policy `Protected_policy_52759c6a`:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::XXX-stg/protected/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by ykethan** [comment]
Hey @yaquawa, thank you for reaching out. We can access/modify the auth role by utilizing the project override feature. Please refer to https://docs.amplify.aws/cli/project/override/ providing additional information.

**Comment by yaquawa** [comment]
@ykethan Thanks!
But I got an error after running `amplify override project`.

```sh
amplify override project
🛑 Packaging overrides failed.
Command failed with exit code 1: yarn install

Resolution: There may be errors in your overrides file. If so, fix the errors and try again.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

**Comment by yaquawa** [comment]
Thanks @ykethan !
How can I check the final cloudformation template before pushing it?

**Comment by ykethan** [comment]
hey @yaquawa, we can check the cloudformation template by first running `amplify build` then checking the build folder under the `amplify/backend/<resource name>/build` and `amplify/backend/awscloudformation/build`
![image](https://user-images.githubusercontent.com/87995712/212700850-16673cd4-39b7-455f-a878-8cfaa411a663.png)
additionally, you will need to comment out or set the flag to false in the setting.json under `.vscode` to view the cloudformation folder 
![image](https://user-images.githubusercontent.com/87995712/212701100-58696d4f-3619-4749-8531-9cb5fe31624b.png)

**Comment by yaquawa** [comment]
@ykethan Thanks! Can you give some example code for referring the S3 bucket from the `override.ts` ?

**Comment by ykethan** [comment]
Hey @yaquawa, to prevent any misunderstanding. Currently, Amplify override does not support importing/referring to existing resources such as `aws-exports`. But I was able to find a workaround on https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1035874372, https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1037656768 and https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1212640682. I would recommend thoroughly testing this in your dev environment before implementing this in your prod to identify any side effects.

**Comment by yaquawa** [comment]
Thanks @ykethan , close the issue and I'm going to watch the #9063.
