### ISSUE TITLE
Request failed with status code 403 with `Storage.put`

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#11786]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.2.0

### Amplify CLI Version

10.6.1

### What operating system are you using?

MacOS

#### 1.
Add the resource.
```
amplify add storage
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✔ Provide a friendly name for your resource that will be used to label this category in the project: · testfiles
✔ Provide bucket name: · testfiles
✔ Restrict access by? · Auth/Guest Users
✔ Who should have access: · Auth users only
✔ What kind of access do you want for Authenticated users? · create/update, read, delete
✔ Do you want to add a Lambda Trigger for your S3 Bucket? (y/N) · no
✅ Successfully added resource testfiles locally
```

#### 2.
Make a push.
```
amplify push
```

#### 3
SignIn using `Auth.signIn`, and then try to use `Storage.put`, and confirm that it works.

#### 4.
Update it a bit ( > Who should have access: · Auth and guest users)
```
amplify update storage
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✔ Restrict access by? · Auth/Guest Users
✔ Who should have access: · Auth and guest users
✔ What kind of access do you want for Authenticated users? · create/update, read, delete
✔ What kind of access do you want for Guest users? · read
✔ Do you want to add a Lambda Trigger for your S3 Bucket? (y/N) · no
✅ Successfully updated resource
```

#### 5.
Push it again.
```
amplify push
```

#### 6.
Try to use the same `Storage.put`, failed with status code 403.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @yaquawa, thank you for reaching out. From the provided steps I was unable to reproduce the issue. On pushing the updates storage options and running `Storage.put` the API call was able to upload the file as expected. Could you provide us some additional information on the changes made.

**Comment by yaquawa** [comment]
@ykethan 

> Could you try using Auth.currentAuthenticatedUser to check for the current signed in user?

Yes, I'm sure I have signed in user, and the location of the uploaded file is "protected" folder. The request URL was:
`https://PROJECT-stg.s3.ap-northeast-1.amazonaws.com/protected/ap-northeast-1%3A13255de0-fbc9-4167-9896-79119869a947/test.txt?x-id=PutObject`

In addition to that, I have checked the following:

* Authenticated-Role in the related identity pool
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::PROJECT-stg/protected/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::PROJECT-stg/protected/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
* The CORS settings of the related S3 bucket(`arn:aws:s3:::PROJECT-stg`)
```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2",
            "ETag"
        ],
        "MaxAgeSeconds": 3000
    }
]
```

**Comment by ykethan** [comment]
Hey @yaquawa, is this an imported auth/cognito user pool?
In my reproduction I created a user pool using the Amplify CLI. added the storage as provided in the reproduction steps.
added the `withAuthenticator` to login to the Cognito user. 

```
const result1 = await Storage.put("test.txt", "Protected Content", {
        level: "protected",
        contentType: "text/plain",
      });
```  
to upload a file.

observed the following
![image](https://user-images.githubusercontent.com/87995712/213306346-345d71ff-d0ef-4873-80e7-ace263495cc2.png)

if the you are utilizing the same steps. could you check the `Block Public Access settings for this account` in your AWS account?

**Comment by ykethan** [comment]
Hey @yaquawa, I was referring to the following selection on the account.

![image](https://user-images.githubusercontent.com/87995712/213481529-8c2f6b74-7767-4eed-8dbb-f7a41964c0b9.png)

could you try setting this and test the put operation.

**Comment by yaquawa** [comment]
@ykethan The problem is that the cognito user is assigned to a group, the role of the group doesn't have the "s3:PutObject" permission.

To resolve the issue you have to select "both" when asked for `Restrict access by`.

**Comment by yaquawa** [comment]
@slaat Yes, I noticed that, I think this is a bug.

**Comment by slaat** [comment]
not only is that a bug, that is a huge security issue. I was left to believe users are only able to access whatever I configured with the cli. This is really misleading and needs to be fixed urgently

**Comment by ykethan** [comment]
hey folks, noticed the thread conversation picking up here. There is currently a feature request here for support of S3 fine grained using Cognito user pool groups. Refer to https://github.com/aws-amplify/amplify-cli/issues/7567 and do subscribe to the issue for any further updates.
