### ISSUE TITLE
UserPoolClientLambda CREATE_FAILED latest version fresh install of Amplify CLI

### ISSUE THREAD

**Issue by ferrlan** [aws-amplify/amplify-cli#11803]
I am getting these errors the first time I am trying to push a new amplify app after adding "amplify add storage" and following the directions precisely in the documentation. Any help on this issue would be great appreciated so I can use Amplify.

<img width="896" alt="213262023-29e83925-de51-47b5-8561-161ec819ba29" src="https://user-images.githubusercontent.com/19779880/213262503-5e27acb3-1a5b-4c1b-b6ca-9249b158ca81.png">

**Comment by josefaidt** [comment]
Hey @ferrlan :wave: thanks for raising this! Would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml)? By doing so this will help gather additional context around the issue you're experiencing, and assist us with diagnosing the issue effectively.
