### ISSUE TITLE
Allow the use of several external layers

### ISSUE THREAD

**Issue by kouz75** [aws-amplify/amplify-cli#11808]
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

Lambda

### Describe the feature you'd like to request

Via amplify cli, we are not able to add several external layers to a lambda function. 
We can only add 1 external layer.
We need to manually update the cloudformation file if we need more layers.

### Describe the solution you'd like

update amplify cli to allow us to add several layer.

### Describe alternatives you've considered

update manually cf file to link the layer

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @kouz75, thank you for reaching out. Amplify CLI does allow Lambda function to add multiple layers upto 5 layers.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/87995712/213494851-66e1be90-86db-40d3-a01d-f401f326d98c.png">
 
 We can use `amplify update function` or `amplify add function` to add the layers external arn's. The input requires users to add layers using a comma separated input.
