### ISSUE TITLE
`Failed to start API` error when using `amplify mock api` command

### ISSUE THREAD

**Issue by jayscope** [aws-amplify/amplify-cli#11822]
```
Failed to start API Mocking. Running cleanup tasks.
🛑 Cannot read property 'stop' of undefined
```

I'm using a REST api with a gloang lambda function which has been modified to be compatable with APIGateway.

The function works fine when deployed.

[report-1674259062282.zip](https://github.com/aws-amplify/amplify-cli/files/10471058/report-1674259062282.zip)

**Comment by isaka1022** [comment]
@jayscope Hi, I faced same problem on my M1 Mac Book Pro, but I solved that by installing java referenced this.
https://github.com/aws-amplify/amplify-category-api/issues/848

**Comment by ykethan** [comment]
Hey @jayscope, as correctly pointed out by @isaka1022, you will need to have java installed. Refer to https://docs.amplify.aws/cli/usage/mock/  for information highlighting this requirement.
