### ISSUE TITLE
Missing cognito settings in aws-export.js

### ISSUE THREAD

**Issue by marcschroeter** [aws-amplify/amplify-cli#1183]
**Describe the bug**
I created a GraphQL API with cognito auth with the CLI. Cognito userpool is created but the aws-exports file looks incomplete
```
const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https:/xxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "null",
};
```
**Expected behavior**
I would expected further cognito configuration here, e.g:
```
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:REDACTED",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_REDACTED",
    "aws_user_pools_web_client_id": "REDACTED"
```

**Comment by haverchuck** [comment]
@marcschroeter Which version of the Amplify CLI are you using?

**Comment by marcschroeter** [comment]
1.1.8 @haverchuck

**Comment by kaustavghosh06** [comment]
@marcschroeter I wasn't able to reproduce this behavior. Could you show me your terminal logs (if you still have it), as to hwo you added your API using the amplify CLI?

**Comment by marcschroeter** [comment]
Unfortunately i dint have the terminal logs. I added the the API using amplify add api and then used graphql and choosed authorization type: cognito. How can i fix that now?

**Comment by kaustavghosh06** [comment]
@marcschroeter Did you use the Amplify console to choose the authorization type?

**Comment by kaustavghosh06** [comment]
Also, what's the terminal output when you run `amplify status`?

**Comment by marcschroeter** [comment]
I dont know why, but now its everythings inside the file..i added S3 hosting and deleted s3 hosting again and now the cognito settings are in the file. Thank you guys.
