### ISSUE TITLE
Pass cognito userpool id to Lambda

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1185]
**Is your feature request related to a problem? Please describe.**
I need a lambda to lookup list of cognito groups a user other than the logged-in user belongs to. This is pretty easy to write but in the context of multi-env the lambda needs to know which cognito user pool id to connect to. 

**Describe the solution you'd like**
user pool id should be passed as a parameter to the lambda

**Describe alternatives you've considered**
Hardcoding the user pool ids based on env or parsing identity.issuer in the passed claims (see https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html). 

Might be related to https://github.com/aws-amplify/amplify-cli/issues/689 and https://github.com/aws-amplify/amplify-cli/issues/678

**Comment by kstro21** [comment]
Probably using the same approach described in #1099 is the way to go with this one.

**Comment by kaustavghosh06** [comment]
@hisham Today we released an updated flow as a part of the functions category to pass resource identifiers like the cognito userpool ID to a lambda function as environment variables and also populate the corresponding lambda execution role to access the userpool ID. You can install the latest version of the CLI and go through the `amplify update function` flow to update your exisiting functions to access your Amplify generated resources in the project.

**Comment by LucasAndrad** [comment]
@kaustavghosh06 why this issue was closed man? _"Today we released an updated flow as a part of the functions category to pass resource identifiers like the cognito userpool ID ..."_ where are the docs? I saw this same comment from you many times here in many issues, sorry dude but we're not clairvoyant, we just want to use amplify. Thanks.

**Comment by kaustavghosh06** [comment]
@LucasAndrad  I've commented on this issue previously as to how to go about accessing the userpoolID in the comment and here's the documentation in the comment above - https://github.com/aws-amplify/amplify-cli/issues/1185#issuecomment-497212093 Did you give it a shot? What's the issue that you're facing? Here are the docs for reference - https://docs.amplify.aws/cli/function#function-templates
