### ISSUE TITLE
Amplify push can not track the new lambda and api after close the terminal

### ISSUE THREAD

**Issue by 6vvvvvv** [aws-amplify/amplify-cli#11862]
### Amplify CLI Version

10.6.1

### Question

Hi,

I have set up a new lambda and api in local but I have not deployed them since they are not done yet. But when I  shut down my laptop and I try to push it with amplify push the next day , the console does not recognize these lambda and api, it bothers me a lot and can someone please tell me how to solve this issue? No change on the configuration just the lambda code itself, so maybe it's related to the cache or something?

![image](https://user-images.githubusercontent.com/47306004/215157208-8da9f1c9-e40a-4a00-b6e4-bdb1ff65bb82.png)
There should be a <upload> function in the list above.

Thanks.

**Comment by josefaidt** [comment]
Hey @6vvvvvv :wave: thanks for raising this! To clarify a bit I have a few follow-up questions:

- Was this Function added in a separate environment and merged over with git? 
- are you experiencing an issue where pushing the function does not update the code in the Lambda Console?
- if you run `amplify env checkout <current-env-name>` does the Function show up in subsequent `amplify status` executions?

**Comment by 6vvvvvv** [comment]
> Hey @6vvvvvv 👋 thanks for raising this! To clarify a bit I have a few follow-up questions:
> 
> * Was this Function added in a separate environment and merged over with git?
> * are you experiencing an issue where pushing the function does not update the code in the Lambda Console?
> * if you run `amplify env checkout <current-env-name>` does the Function show up in subsequent `amplify status` executions?

Hi,
1.Well, I have two envs: staging and prod. I have been always working on staging. This functon has never been merged over git or pushed to prod and it is only developped in a seperated local branch.

2.If I'm not misunderstanding your question, I guess the answer yes. Everytime I develop the new lambda locally, the next day my console(command prompt) will never track this change if It's not merged. So that bothers me a lot.

3. WOW !!! You are amazing, the function and api shows up after I do the checkout to env staging!! But why it would help? Can you please explain a little?
![image](https://user-images.githubusercontent.com/47306004/215180816-75cc25e1-796e-4ef6-947b-21a4644e0ce9.png)

**Comment by josefaidt** [comment]
Hey @6vvvvvv glad to hear that worked for you! It sounds like you may be experiencing the issue described here https://github.com/aws-amplify/amplify-cli/issues/8090, which is slightly similar to https://github.com/aws-amplify/amplify-cli/issues/9790. Given this is now resolved I'll close this issue, and please subscribe to the linked bug reports for further updates.
