### ISSUE TITLE
Error enabling FCM channel

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-cli#11870]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v18.13.0

### Amplify CLI Version

10.6.2

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I'm getting a code error when trying to enable FCM notifications (note I had just disabled them, not sure if this happens on a new project)

```
$ amplify notifications update
✔ Choose the notification channel to configure · FCM  | » Firebase Push Notifications 
✔ Do you want to enable the FCM channel (Y/n) · yes
✔ ApiKey · AAAAK.....
✔ The FCM channel has been successfully enabled.
🛑 Cannot read property 'Enabled' of undefined

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: d0cb73e5-56d3-463c-ae6a-99a90993459c

I think this may be related to https://github.com/aws-amplify/amplify-cli/issues/11432

### Expected behavior

The FCM channel is being enbled succesfully, but the metadata in amplify/ is not being updated to reflect.

### Reproduction steps

1. amplify update notifciations
2. enable FCM

### Project Identifier

77e97f23b96b4348aa233d8544bbbe1b

### Log output

<details>

```
# Put your logs below this line
2023-01-29T23:58:11.216Z|info : amplify configure notifications  
2023-01-29T23:58:11.242Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-01-29T23:58:18.365Z|error : Cannot read property 'Enabled' of undefined
UnknownFault: Cannot read property 'Enabled' of undefined

```

</details>


### Additional information

_No response_

### Before submitting, please confirm:


- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @johnf, thank you for reaching out. I was able to reproduce this, marking this as bug.
