### ISSUE TITLE
Support for more than one test event to locally invoke lambda with? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1187]
**Is your feature request related to a problem? Please describe.**
It seems the `amplify function invoke` feature only supports one event in event.json. 

**Describe the solution you'd like**
I need to test multiple different kinds of events. 

**Describe alternatives you've considered**
Using the Lambda AWS console which has support for more than one event types. 

**Additional context**
Related to https://github.com/aws-amplify/amplify-cli/issues/691

**Comment by kstro21** [comment]
This was resolved in #1624 

When we run `amplify function invoke [my-function]` we will be asked for the relative path to the event:
>? Provide the relative path to the event: (event.json)

By default, it is **event.json**, but suppose we have a folder named **events/** that have the files `event-1.json` and `event-2.json`, we can answer the question with `events/event-1.json` and that file will be used as the Lambda event.

Take a look to the following SS that illustrate a simple example

![image](https://user-images.githubusercontent.com/5972646/61407163-1e231380-a8ab-11e9-8063-d3a4b94ab0e7.png)
