### ISSUE TITLE
Add DynamoDB Trigger using function update

### ISSUE THREAD

**Issue by ChadyG** [aws-amplify/amplify-cli#11872]
### Is this related to another service?

DynamoDB

### Describe the feature you'd like to request

The ability to add/update DynamoDB Trigger configurations using `amplify function update`.  Currently need to modify the cloudformation-template.json manually, or remove then re-create the function to add or remove DynamoDB Stream triggers to an existing function.

### Describe the solution you'd like

`amplify function update`
Should support modifying configurations for function triggers.

### Describe alternatives you've considered

- Manually modifying cloudformation-template.json.
- Removing existing function and re-creating using `amplify function new`
- Modifying Triggers in AWS console instead of Amplify CLI (does not preserve configuration when pushing to new environments)

### Additional context

Mentioned in #997

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @ChadyG, this appears to similar to https://github.com/aws-amplify/amplify-category-api/issues/198 and is currently being tracked in the API category repository. Please feel free in commenting and subscribing to the issue for further updates.
closing this as duplicate to prevent any miscommunication between issues.
