### ISSUE TITLE
 Event Type: update, Reason: Parameters: [authRoleName, unauthRoleName] must have values

### ISSUE THREAD

**Issue by Arnav7501** [aws-amplify/amplify-cli#11906]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.17.0

### Amplify CLI Version

10.7.0

### What operating system are you using?

MAc

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

If i run amplify push, I get the error:
Name: apiSocialMediaApp (AWS::CloudFormation::Stack), Event Type: update, Reason: Parameters: [authRoleName, unauthRoleName] must have values

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 582cce8b-5335-4eed-a835-ada81f34056e
 I saw someone else had this issue, but nobody gave a solution, they said it was patched in version 10.5.0, but im still getting this error.

### Expected behavior

I expected it to push the changes I made

### Reproduction steps

1. Install and set up Amplify Cli
2. Run amplify push

### Project Identifier

 8741d2665676fac5a5554da0cf079d3b

### Log output

<details>

```
# Put your logs below this line

zsh: no such file or directory: issue-date
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by andreav** [comment]
Similar issue here.
As soon as I modify any resouorce (i.e some lambda code), when I push I get an error like this:

```
🛑 The following resources failed to deploy:
Resource Name: auth<myAuthReosurceName> (AWS::CloudFormation::Stack)
Event Type: update
Reason: Parameters: [hostedUIDomainName, autoVerifiedAttributes, allowUnauthenticatedIdentities, hostedUI, smsVerificationMessage, breakCircularDependency, oAuthMetadata, mfaTypes, userpoolClientGenerateSecret, mfaConfiguration, authProvidersUserPool, adminQueries, permissions, resourceNameTruncated, 
userPoolGroups, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, useEnabledMfas, parentStack, resourceName, triggers, unauthRoleArn, requiredAttributes, authTriggerConnections, aliasAttributes, userpoolClientLambdaRole, authRoleArn, userpoolClientReadAttributes, emailVerificationSubject, sharedId, useDefault, identityPoolName, userPoolGroupList, authSelections, hostedUIProviderMeta, usernameCaseSensitive, serviceName, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, passwordPolicyCharacters, defaultPasswordPolicy] must have values
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/<mystakhere>/events
```

Cli version: 10.7.0

**Comment by josefaidt** [comment]
Hey @Arnav7501 :wave: thanks for raising this! What were the last few actions performed prior to receiving this error? Are you running `amplify push` or `amplify push api`?

@andreav while your issue is similar in that you are missing paramters' values, the effected resource is different and appears to have a different root cause. Would you mind filing a [separate bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml) for this?

**Comment by Arnav7501** [comment]
The last action i performed was adding a new model from amplify studio's UI. The model wouldn't update locally, even though my models had updated after i pulled the changes., so i ran amplify push in hopes of syncing the local files, which led to this error

**Comment by josefaidt** [comment]
Hey @Arnav7501 thanks for clarifying! 

> The model wouldn't update locally, even though my models had updated after i pulled the changes.

Were you running `amplify pull` to pull the changes you made in Studio? Were these changes deployed with Studio? And lastly, what sort of issues were you experiencing when attempting to update the model locally?

**Comment by josefaidt** [comment]
Hey @Arnav7501 are you still experiencing this?

**Comment by Arnav7501** [comment]
no sorry, I can't remember what i fixed, i think re-installing amplify fixed it

**Comment by yw14218** [comment]
Same problem I cannot update anything even after amplify pull. Any updates on any categories give erros:
``````
Event Type: update
Reason: Parameters: [hostedUIDomainName, oAuthMetadata, authProvidersUserPool, thirdPartyAuth, adminQueries, userPoolGroups, audiences, hostedUIProviderMeta] must have values
`````

**Comment by bilal-korir** [comment]
The following steps solved this issue for us:

1. Delete `./amplify` folder, delete `amplifyconfiguration.json` file, and delete `aws-exports.js`.
2. Run `amplify pull -y` command from the command line to bring back the amplify project back to your local machine. And when asked, do you want to edit this project in the future, select `Yes`.
3. Now when we run `amplify push -y` it works fine.

**Note*** this issue started to happen for us when we copied the whole project to a new directory/folder.
