### ISSUE TITLE
Path not working for adding APNS to Notifications

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-cli#11916]
### Amplify CLI Version

10.7.1

### Question

I have notifications already added to my environment, although the cli reads that it needs to create it, which is strange - this is new and happened before I upgraded from 10.7.0 to 10.7.1. How does amplify cli generate those statuses in the cli for what will happen upon push? 

Back to my main issue,
When I try to add my p12 file for APNS - it always fails. 
Are there any stipulations on the path to the p12 file? I've tried adding it to the current working directory, relative path and absolute path. None of them work. I've also added the same file manually to another environment through the pinpoint UI and that seems to work. Is it expecting a particular filename?

**Comment by mjmostachetti** [comment]
Is there any problem with me adding it manually to the pinpoint UI for the environment I'm working on so I can continue to test push notifications for iOS? I believe that the p12 will get blown out when I push to that environment from the cli again, but I need to keep working on this.

**Comment by ykethan** [comment]
Hey @mjmostachetti, thank you for reaching out. When adding the notifications of type APNS and providing a path, does the Amplify CLI throw an error and generate a report with project identifier?
if yes, could you check the report saved location for the zip. In the zip file could you open the error.json file which should contain the `downstreamException` block with a `message` key. This should provide you the reason for the failure. could you provide the error message generated here while removing any sensitive information. 

if not, could you provide us the project identifier here and we would be happy in diving deeper into the issue.

**Comment by mjmostachetti** [comment]
Where is the zip file generated? This is what is output:

MAC verified OK
🛑 Failed to enable the APNS channel.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 81f551fa-1bc4-4666-b701-bc66695d9768

**Comment by ykethan** [comment]
Hey @mjmostachetti, it appears the diagnose reporting is currently not turned on for the Amplify application. 
In order for the application to generate the report automatically on a failure we can run `amplify diagnose --auto-send-on`. on running the command, then add notifications and provide the same inputs as before. For example the output should show as follows 
```
amplify add notifications            
✔ Choose the notification channel to enable · APNS |  Apple Push Notifications   
✔ Select the authentication method for the APNS channel · Certificate
✔ The certificate file path (.p12):  · <path>/Certificates.p12
✔ The certificate password (if any):  · 
MAC verified OK
🛑 Failed to enable the APNS channel.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: <session identifier>

✅ Report saved: /var/folders/7n/vtvskf9s3czf2429q2kv9yz00000gr/T/<application name>/report-1676037624885.zip

✔ Done

Project Identifier: <project identifier>
```
The report saved attribute should provide you the location. on opening the zip the `error.json file` should contain the reason for failure. Do provide us the project Identifier, this would help us in diving deeper into the issue.

Additionally, if you would like to turn off the reporting later, you can run `amplify diagnose --auto-send-off. But I would suggest turning this assists us in troubleshooting an issue. Please refer to https://docs.amplify.aws/cli/reference/diagnose/ for additional information on the diagnose command.

furthermore, I have also filed a issue to improve this behaviour and expose the error message on the CLI directly. Please refer to https://github.com/aws-amplify/amplify-cli/issues/11940.

**Comment by jinglongwu** [comment]
Hi I had the same error and get this from the `error.json`. Please help.
```json
{
    "name": "NotificationsChannelAPNSFault",
    "classification": "FAULT",
    "options": {
        "message": "Failed to enable the APNS channel."
    },
    "downstreamException": {
        "message": "Resource not found",
        "code": "NotFoundException",
        "[Message]": "See error.Message for details.",
        "time": "2024-01-07T22:51:14.982Z",
        "requestId": "88b86af3-589f-467f-ba97-ada798194368",
        "statusCode": 404,
        "retryable": false,
        "retryDelay": 31.504166553577573
    },
    "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
}
```
