### ISSUE TITLE
@aws-amplify/cls package causing ESLint error

### ISSUE THREAD

**Issue by baronyoung** [aws-amplify/amplify-cli#1192]
**Describe the bug**
As of today, any time I install the @aws-amplify/cli package, even on a newly created CRA app, I get an esLint error...

>
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
>   "eslint": "5.12.0"

**To Reproduce**
1. Create new React project using create-react-app
2. Install @aws-amplify/cli package (both npm and yarn methods resulted in the same issue)
3. ESLint error shows up in IDE when editing .js files and 'yarn start' no longer will start the app.

**Desktop (please complete the following information):**
 - OS: MacOS
System Version:	macOS 10.14.3 (18D109)
Kernel Version:	Darwin 18.2.0

**Additional context**
I have many other packages installed and everything works fine until I install this one package.  It appears by doing an `npm ls eslint` that this package is installing eslint which I don't think it should be doing.  Again, even on a fresh application with no other modules than react, react-dom, and react-scripts, this still causes an error.

**Comment by baronyoung** [comment]
Update:  After removing the cli package, working for a while, then re-adding it, I'm no longer getting the error.  I can't explain why as I tried that numerous times earlier.

**Comment by kaustavghosh06** [comment]
@baronyoung I wasn't able to reproduce it either. It's strange that the CLI would've effects on create-react-app. If you still see this issue please re-open this issue or comment on it.

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 we experienced this issue (I a few months ago, a colleague a few days ago), but I advised my colleague to just add the preflight skip flag. I have a hard time imaginging that updating to the latest 5.x ES linter package will break anything. "Drive fast and take chances."
