### ISSUE TITLE
`amplify env add` then `amplify push` does not update aws-exports.js

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1193]
**Describe the bug**
I expected aws-exports.js to be updated after I add and push a new environment, instead I had to then run `amplify init` to update the file. 

**To Reproduce**
1. Checkout an existing environment 
2. Add a new environment using `amplify add`
2. Do `amplify push`
3. aws-exports.js is not updated

**Expected behavior**
aws-exports.js should be updated after I push a new environment

**Additional context**
Running 1.4.0

**Comment by kaustavghosh06** [comment]
@hisham The fix is currently in deployment. Will close out once we have the new version out.

**Comment by kaustavghosh06** [comment]
@hisham The issue should be fixed with v 1.5.0. Please feel free to re-open this issue if you're still seeing this behavior.
