### ISSUE TITLE
"invalid bit length repeat" after removing notifications and analytics

### ISSUE THREAD

**Issue by DemiAndrew** [aws-amplify/amplify-cli#11942]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.15.1

### Amplify CLI Version

10.4.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I originally set up my Amplify react native project with `notifications` and `analytics` services (ie. `amplify add notifications`). I decided to use Expo to manage my push notifications instead and thus tried to remove both services via `amplify remove notifications` and `amplify remove analytics`. Locally, it said the delete was successful but when trying to `amplify push`, I am given the cryptic error:

>  There was an error pulling the backend environment staging.
> 🛑 invalid bit length repeat

I tried to `amplify pull` to reset everything but now my amplify env seems to be in a bad state. After `amplify pull` I get a similar error:

>  Could not initialize platform for 'staging': invalid bit length repeat

So now I am stuck and can't make any changes to my `staging` environment. It has also effected others on my team who now get the same error when trying to push/pull to our `staging` env. Our development is at a standstill until we find a resolution

### Expected behavior

I would expect to be able to remove the `notifications` and `analytics` services locally via CLI and then push those changes successfully. Or be able to `amplify pull` to recover from a bad state.

### Reproduction steps

1. `amplify remove notifications` and `amplify remove analytics`
2. `amplify push`
3. `amplify pull staging`

### Project Identifier

9feca9b492db0b4293d8fd0b96b40d87

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @DemiAndrew :wave: thanks for raising this! While I work to reproduce this issue can you describe what notifications you had enabled in your project prior to removing and receiving this issue?

**Comment by DemiAndrew** [comment]
Hi @josefaidt thanks very much for helping look into this. I ended up connecting with an AWS Support Engineer who was able to solve my problem. Our findings are summarized here:

> Kindly allow me have a recap and to summarise our conversations with you.
> 
> 1. Initially, there was an issue when ran "amplify pull" -  "invalid bit length repeat"
> 
>     After several tries(upgrading CLI, ran it inside empty folder/fresh repo folder, etc.), we suspected the "#current-cloud-backend.zip" file on S3 is broken.
> 
>     Then we downloaded the file from S3 and confirmed that "#current-cloud-backend.zip" is broken (it can not be unzipped correctly).
> 
>     We believe this is a potential bug on Amplify CLI, but we need to restore the broken files and make sure our project can continue to be working.
> 
> 2. I could unzip it by using command line and see the files inside
>    
>     We tried re-zip them and upload to s3, then ran "amplify push" again
>     
>     a) 'jsonString' argument missing or empty.
> 
>         It means a file(.json) is empty, but don't know which file, so we checked and compared local json files and filled the empty file
> 
>     b) expected ":" but got "}" ..... 
>         
>        It means a file(.json) is broken, but don't know which file, so we looked for the broken file. Then downloaded json content from Cloudformation console, put them to the broken file.
> 
>     Note: I use the zipFile() in the Amplify CLI source code to make sure the zip function is working same with CLI.
> 
> The "amplify push" can work correctly after several re-zipping/re-uploading, and we can confirm that most of the files are back to normal after a basic inspection.
> 
> Also, we enabled the "versioning" on S3 bucket on both "staging" and "main" environment, which can prevent the broken files issue in future.

Essentially, the #current-cloud-backend.zip which is stored in s3 had become corrupted. This zip file is the source of truth that we `amplify pull` from. Running `amplify push` replaces this zip with our local `backend` folder. We manually repaired some malformed files in the `backend` folder in the `amplify` directory, zipped up my `backend` folder, and uploaded it to s3 (replacing `#current-cloud-backend.zip`). We believe there is a bug in the cli that corrupted these files. 

As noted, we enabled versioning on the s3 bucket which will keep a history of the `#current-cloud-backend` folder so that we always have a known good version to restore to if the zip file becomes corrupted again in the future
