### ISSUE TITLE
new environments are added with new Amplify App ID (separate projects)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#11950]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

10.7.1

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

When creating new environments in our Amplify projects, they are created as a separate Amplify project in the console with separate Amplify App ID's
![image](https://user-images.githubusercontent.com/5033303/217690742-103ab009-3e07-4217-aabb-aea7b497c871.png)

### Expected behavior

environments are created in the same Amplify project

### Reproduction steps

1. `amplify init -y`
2. `amplify add env` > `next`
3. visit Amplify console
4. observe multiple projects

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
@josefaidt did
```
amplify init -y
amplify add env
```

but the app did get created as following
![image](https://user-images.githubusercontent.com/87995712/217846488-669a0d08-dd7c-46c5-8a11-a4a769574524.png)

possibly related to naming of the project. will test that.

**Comment by ykethan** [comment]
created project named a11942 and followed same steps

![image](https://user-images.githubusercontent.com/87995712/217848626-624ef3c5-fb4d-49e8-97f0-06077a59446e.png)
![image](https://user-images.githubusercontent.com/87995712/217848809-ae32a346-b511-4800-ae25-382b3c4b70b2.png)

**Comment by josefaidt** [comment]
Hey @ykethan I just tried stepping through each of the following commands (using `next` as a sample name for consistency), but unfortunately new projects are getting created:

- `amplify add env next` > step through interactive prompts
- `amplify add --envName next --yes`
- `amplify add env` > `next` > step through interactive prompts
- `amplify init --envName next --yes`
- `amplify init` > "no" to "do you want to use an existing env.." > "next" > step through interactive prompts

**Comment by ykethan** [comment]
@josefaidt how does the project setup look like at the root and outside? also are there any abnormalities in the team-provider-info?
If you try creating an application in a entirely different directory from where your projects reside do you still see the same behaviour?

**Comment by josefaidt** [comment]
> how does the project setup look like at the root and outside?

I reproduced this as `a11950` in a fresh directory and no resources

> also are there any abnormalities in the team-provider-info?

team-provider-info looks fine, just different app id's

![image](https://user-images.githubusercontent.com/5033303/217899592-593a7395-3abe-4a88-b0da-669fdd57afc4.png)

> If you try creating an application in a entirely different directory from where your projects reside do you still see the same behaviour?

The original repro was in another issue's repro project `a11942` and the second repro is in a sibling directory

```
|- reproductions/
  |- a11942/
  |- a11950/
```

**Comment by ykethan** [comment]
hey @josefaidt, can you provide me zip of your Amplify project to try and reproduce the issue.

**Comment by josefaidt** [comment]
[asdfasdf.zip](https://github.com/aws-amplify/amplify-cli/files/10724528/asdfasdf.zip)

**Comment by josefaidt** [comment]
duplicate of #11580, closing
