### ISSUE TITLE
API+Fargate - Use Existing VPC

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-cli#11987]
### Amplify CLI Version

10.7.1

### Question

While deploying an API with Fargate container integration, Amplify always creates a new VPC and related resources. I'm looking to override this behavior to use an existing VPC.

I make the following changes, but amplify disregards them and overrides with the default.
- **backend/api/<apiname>/parameters.json**: add params pointing to existing subnet ids, security group id and VPC link id
- **backend/api/<apiname>/awscloudformation/build/root-cloudformation-stack.json**:  add CFT parameters for the above 3 and pass them as parameters to api nested stack
- **backend/api/<apiname>/afgapi-cloudformation-template.json**: add CFT parameters for the above 3 and Ref them at corresponding places

If Amplify respects my changes, I believe it should work as intended, except it always generates the default template files. Is there a way to configure Amplify to accept my changes overriding the default?

**Comment by josefaidt** [comment]
Hey @vgthoppae :wave: thanks for raising this! It appears you are encountering the issue documented as a feature request here https://github.com/aws-amplify/amplify-cli/issues/7049, where unfortunately on each push the CloudFormation template is overwritten. I'll mark this as a duplicate feature request.

You can override the project with `amplify override project`, however any changes applied to the API's CFN template will be overwritten

**Comment by vgthoppae** [comment]
Thanks @josefaidt for quick response. The "amplify add api" step (with Fargate container and default ExpressJS template) creates a root stack and 2 nested stacks (api and network). Looks like the "amplify override project" exposes only the AmplifyRootStackTemplate type with which you can only add new resources or parameters. Is there a way to get a handle on the API Stack since my aim is to make changes on that stack?

**Comment by josefaidt** [comment]
Hey @vgthoppae unfortunately we do not currently support overriding container-based API resources, however [CDK custom resources](https://docs.amplify.aws/cli/custom/cdk/) may assist here. Please consider adding a 👍 to #7049. I'll close this in favor of tracking the existing item to extend container-based resources, though I also wanted to mention our [community Discord server](https://discord.gg/invite/amplify) ask a medium for architectural patterns and experiences.
