### ISSUE TITLE
CLI version history / update log

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1198]
**Is your feature request related to a problem? Please describe.**
It seems like a lot of people on here are using Amplify to develop production and/or alpha environments that need stability, and are reluctant to upgrade to the latest NPM branch for fear of breaking the local environment by hitting an edge case or whatever else happens in between a dependency upgrade and a mental breakdown. 
 
**Describe the solution you'd like**
A short, concise log that details every update, fix or enhancement made for every semantic version of the CLI.

**Describe alternatives you've considered**
`npm i -g @aws-amplify/cli && echo 'hope push works after this and the upgrade was worth the dependency risk =)'`

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu Yes, I agree this would be something great to have and we're tracking this a part of this issue - https://github.com/aws-amplify/amplify-cli/issues/450
I'll update that thread once we have a better approach of announcing the changelog with the CLI.
