### ISSUE TITLE
Add Restapi and graph api both

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-cli#1200]
Currently  we add either rest api or graph ql api using amplify add api , but in our project we need graphql and rest api both .

How can we have both rest and graphql apis in same project ?

**Comment by wizawuza** [comment]
You can add both just by starting with a GraphQL API, and then later doing another "amplify add api" and selecting a REST API.

Or are you referring to doing the REST API on a Table created from the GraphQL API?

**Comment by kaustavghosh06** [comment]
@vjindalaurea Please let me know if you're still having this issue. Closing this issue for now.

**Comment by vjindalaurea** [comment]
@kaustavghosh06 , I am facing this problem : 
-  I first added a graphql api using amplify add api , it created some dynamo table
- then i tried to add rest api by again using amplify add api ,but it says : "There are no DynamoDB resources configured in your project currently" . I want to use same dynamodb tables with graphql and rest apis
