### ISSUE TITLE
<amplify mock api> - "Failed to start API Mocking"

### ISSUE THREAD

**Issue by zachegnermh** [aws-amplify/amplify-cli#12003]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.16.0

### Amplify CLI Version

10.6.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

added resources to graphQL schema and ran "amplify mock api"

### Describe the bug

attempting to run "amplify mock api", I receive an unknown error.

### Expected behavior

launch mock api as I have been using it locally

### Reproduction steps

1. make change to graphql schema, eg.) add model or field to existing model
2. run "amplify mock api"

### Project Identifier

686f8d7fabdbbdcdf584a874e1f2007d

### Log output

<details>

```
# Put your logs below this line
amplify mock api
✅ GraphQL schema compiled successfully.

Edit your schema at .\amplify\backend\api\appName\schema.graphql or place .graphql files in a directory at **directory path**

Failed to start API Mocking. Running cleanup tasks.
🛑 Failed to start API Mocking.. Reason: The request processing has failed because of an unknown error, exception or failure.

Project Identifier: 686f8d7fabdbbdcdf584a874e1f2007d

```

</details>

### Additional information

Have no issue running "amplify push" and changing cloud DB

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @zachegnermh :wave: thanks for raising this! While we begin to investigate this issue in more depth, do you experience this after deleting the mock database at `amplify/mock-data`?

**Comment by zachegnermh** [comment]
@josefaidt Thanks for getting back to me, I have not deleted anything from that folder as far as I am aware.

**Comment by josefaidt** [comment]
Hey @zachegnermh can you try removing that folder and restarting mock?

**Comment by zachegnermh** [comment]
Hi @josefaidt, that worked, it is running properly now. Thank you!
