### ISSUE TITLE
Multiple old versions of @aws-amplify/cli are broken

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-cli#1202]
**Describe the bug**

Our CodeBuild Pipeline for our amplify project started failing yesterday - after a bit of digging, I realized it was because 'new versions' of existing, stable releases of `@aws-amplify/cli` were released yesterday. Basically, my local `amplify-cli` worked fine, but when I removed it and re-installed the same version, it no longer worked.

Specifically, `amplify push` fails with the following: `error: uncaughtException: Cannot read property 'outputsForFrontend' of undefined`.  Additionally, `amplify init` no longer creates `src/aws-exports.js` (likely due to a related problem, given the error message).

I tested versions `1.1.6`, `1.1.7`, and `1.1.8`, and all of them have the same issue. I see that a number of releases were made yesterday with these tags, and I would guess one of those releases is to blame. I would also guess that version `1.1.5`, `1.1.4`, etc are affected.

**To Reproduce**

WARNING: IF YOU DO THIS YOUR LOCAL AMPLIFY-CLI WILL NO LONGER WORK

1. Delete your local `amplify-cli`
2. Re-install the same version via `yarn` or `npm`
3. Viola! It no longer works!

**Expected behavior**

I expect that existing release of a project won't be tampered with in such a way that re-installing them (or using them for a CI process) will suddenly fail. If you're gonna release a new version of `1.1.6` (or otherwise change the way it installs such that the tool has fundamentally changed), please label it as a new release (`1.1.6.1`, for example).

Thank you. Please either rollback these releases or do something to fix them ASAP.

**Comment by kaustavghosh06** [comment]
@zjullion I submitted a PR for this just sometime back and we're rolling out the change for the same. We do have integration tests but somehow this error didn't get caught for the same. We're in the process of writing more integration tests to handle scenarios like these as a part of our deployment process. Apologize for the inconvenicence and I'll update the thread once we have this fix rolled out.

**Comment by zjullion** [comment]
@kaustavghosh06 thanks for the hasty response. Apologies for my harshness here, it was unnecessary.

**Comment by kaustavghosh06** [comment]
@zjullion We published a version of the CLI with a fix (v 1.5.1). Let me know if you're still seeing this issue.

**Comment by zjullion** [comment]
@kaustavghosh06 I'm pretty sure both version `1.4.0` and `1.5.0` were always working (my team switched to `1.4.0` because of this bug, and I just tried `1.5.0` and found it to be working). Older versions (I just tested `1.1.6`) are still broken.

**Comment by kaustavghosh06** [comment]
@zjullion Got it, we unfortunately cannot re-publish to 1.1.6 version or the other older broken versions you're referring to but you could use the later versions (assuming that you're already doing so) of the CLI. 
We follow automated semantic versioning (using lerna) for our CLI npm versioning and this bug was introduced due to a patch fix. Unfortunately this bug wasn't caught in our integration tests suite and we fixed the issue after we got to know about it in later versions of the CLI.

**Comment by zjullion** [comment]
This seems really bad to me - if you're using amplify `1.1.6` as a team, and you need to setup a new machine, or start using a CLI process, or you have a new team member, some people's version of `1.1.6` is going to be fundamentally different than other people's version of `1.1.6`.

Basically, you guys are getting around hard-and-fast rules of both `npm` and `yarn` by allowing multiple instances of the same amplify version to exist. If you're doing to do this, you really should remove the old versions from `npm` and `yarn` - they shouldn't even be available to download if they aren't going to work.

**Comment by kaustavghosh06** [comment]
@zjullion I beleive this descrepency came in because the amplify core package refers to`^<version-number>` of a another amplify dependency which had the bug(amplify-frontend-javascript). As a solution, we could remove the carat (^) in our dependencies to prevent situations like this from happening in the future.

**Comment by kaustavghosh06** [comment]
or we should check in our `package-lock.json` to avoid this.

**Comment by zjullion** [comment]
I don't know the specifics of what you guys should pursue as a solution here, but `npm` absolutely recommends checking in `package-lock.json`, see: https://github.com/npm/cli/blob/latest/doc/files/package-lock.json.md

**Comment by kaustavghosh06** [comment]
@zjullion You're right. I submittied a PR which adds the package-lock to the CLI package so that your team doesn't have to face an issue like you did, in the future. Thank you for bringing this up.
Here's a link to the PR -> https://github.com/aws-amplify/amplify-cli/pull/1207

**Comment by zjullion** [comment]
Thanks @kaustavghosh06, appreciate the time you spent on this.

**Comment by ultradox** [comment]
It appears despite the error messages during install, the install works in the end. I did `sudo npm i -g @aws-amplify/cli@1.5.3` with errors e.g. `gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/build'` and many others. But when I run `amplify --version` I get 1.5.3
