### ISSUE TITLE
Updating Lambda function environment variables does not allow special characters

### ISSUE THREAD

**Issue by alex-griffiths** [aws-amplify/amplify-cli#12038]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

10.7.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

I'm trying to update environment variables for one of my lambdas. The purpose of the variable is to store the hostname of the app so that when we send emails, we can provide a link to app frontend. In my dev environment I'm able to set the variable to `localhost:3000` however, when I try to update it for my production environment with the actual hostname, I get an error about invalid characters. Currently I have to go and manually update the lambda's environment variables in the AWS console. Is there a way that I can actually configure the amplify cli to do this?

```
Enter the environment variable name: https://xxxx.xxxxx.xxxx.com
>> You can use the following characters: a-z A-Z 0-9 _
```

### Expected behavior

Providing a URL or really any variable with special characters should work as the values are just stored as strings in the `team-provider-info.json` file.

### Reproduction steps

1. Create a lambda function.
2. Configure it to include an environment variable.
3. Try input a variable with special characters such as a URL

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @alex-griffiths :wave: thanks for raising this! What is the use case for using a URL as the environment variable name?

**Comment by alex-griffiths** [comment]
We use the URL as the value, not the name of the variable. The name of the variable is `HOSTNAME`, and the value is the URL.

We store the URL as a variable because we use it in emails as a link to our frontend where users can redeem invites, or opt out of email communications. If there was a way to access the hostname of that amplify generates by default, I'd use that, but that doesn't seem possible at the moment.
