### ISSUE TITLE
 Send PostConfirmation signup event to a lambda written in .Net instead of Javascript

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-cli#12032]
### Amplify CLI Version

10.7.3

### Question

Is there a way to do this? 

If not, do you have an example of how I could forward the event to the .Net lambda from the JS code?

Thanks!

**Comment by josefaidt** [comment]
Hey @mjmostachetti :wave: thanks for raising this! Although we do not support creating Cognito triggers using runtimes other than Node.js, you can manually connect this using the following steps:

1. create an Amplify project `amplify init -y`
2. add auth `amplify add auth`
3. add a Function `amplify add function`
4. manually modify your `amplify/backend/backend-config.json` file to create the auth dependency on function:
	```json
    "auth": {
      "a12032007a59f0": {
        "customAuth": false,
        "dependsOn": [
          {
            "attributes": [
              "Arn"
            ],
            "category": "function",
            "resourceName": "a1203292aadb09"
          }
        ],
	```
5. run `amplify env checkout <current-env-name>` to initialize this change which will carry this change into `amplify/backend/amplify-meta.json`
6. override auth with `amplify override auth`
7. copy the following override code
	```ts
	import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

    export function override(resources: AmplifyAuthCognitoStackTemplate) {
      // this is generated by Amplify CLI after creating the dependency in backend-config.json
      const category = 'function'
      const resourceName = 'a1203292aadb09'
      const parameterName = 'Arn'
      const parameter = `${category}${resourceName}${parameterName}`

      // create parameter to consume
      resources.addCfnParameter(
        {
          type: 'String',
          description: 'my function arn',
          default: 'NONE',
        },
        parameter
      )

      // add property override in order to use CloudFormation parameter references
      // (using CDK to reassign this parameter will require a 'string' value)
      resources.userPool.addPropertyOverride('LambdaConfig', {
        PostConfirmation: {
          Ref: parameter,
        },
      })
    }
	```
8. push with `amplify push -y`
9. observe we have the Amplify-generated Function set as the Cognito PostConfirmation trigger!
![image](https://user-images.githubusercontent.com/5033303/220169067-cbbe0162-bf76-4145-8ca8-cf43f892d842.png)

With the overrides, this will overwrite existing trigger settings (i.e. existing Node.js trigger functions you created and set with Amplify CLI) and those will need to be patched in.needed.
