### ISSUE TITLE
amplify push: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by adithwip** [aws-amplify/amplify-cli#12085]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.0

### Amplify CLI Version

10.7.3

### What operating system are you using?

macOS 12.6 (21G115) Monterey

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I'm using AWS Amplify to try deploying my Shopify App.
I was following [this straightforward tutorial](https://shopifylearner.com/how-to-deploy-shopify-app-on-aws-amplify/) for the deployment.

I was also authenticated with my IAM User in the Amplify first configuration.
Followed [this Amplify doc](https://docs.amplify.aws/cli/start/install/).

### Expected behavior

Like in the tutorial, I should be able to push my Shopify App to Amplify.
Get my HTTPS URL and then put it on my Shopify App Urls.

### But instead, I got this error:
<img width="522" alt="Screen Shot 2023-02-23 at 8 18 33" src="https://user-images.githubusercontent.com/27177332/220785434-c0ec27e4-4c51-4858-86dd-bf8d5e6c1a56.png">

The error message should be straightforward.
But I don't understand why I'm not authorized to do `amplify push`

I already push the project that I initiated via CLI to the Amplify console.
But when I want to push my App via `amplify push` I'm not authorized.
I'm using a newly created IAM User when I configurated the Amplify CLI for the first time.
With `Administrator-Access-Amplify`.

<img width="441" alt="Screen Shot 2023-02-23 at 8 30 12" src="https://user-images.githubusercontent.com/27177332/220787101-f9d48b6f-a00d-4bd4-89dc-4d43f2d4956b.png">

### Reproduction steps

1. Run `amplify push`
2. Error occurs

### Project Identifier

Project Identifier: 37963ab2b3678f49359609633e574589

### Log output

<details>

```
# Put your logs below this line
amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/

✅ Report saved: /var/folders/fh/87f09n0n129105dchdjwhbg00000gq/T/shopifyapprecipe/report-1677108844063.zip

✔ Done

Project Identifier: 37963ab2b3678f49359609633e574589

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @adithwip :wave: thanks for raising this! I noticed the tutorial you included uses container based deployments which may require additional permissions (sorry for the vague error message! :mask:). While we work to improve this experience, can you try changing the policy on your IAM user to use `AdministratorAccess`?

**Comment by adithwip** [comment]
Thanks, @josefaidt 😄
It did work after I changed the policy to `AdministratorAccess`!

#

Another issue (let me know if I have to make a new Issue for this):

**I already put a `.Dockerfile` inside the desired directory.**
<img width="227" alt="Screen Shot 2023-02-24 at 7 41 03" src="https://user-images.githubusercontent.com/27177332/221047403-f38e9d60-7cb1-44d1-ab0c-843c24e8357e.png">

**But it seems the `.Dockerfile` isn't read.**
<img width="423" alt="Screen Shot 2023-02-24 at 7 41 26" src="https://user-images.githubusercontent.com/27177332/221047404-5ebe8496-06b9-44a3-be6b-a5b9c7aaf5dd.png">

I've tried to dig more profound the documentation and search for the error but seems to be no clue.

**Comment by josefaidt** [comment]
Hey @adithwip you'll want to use `Dockerfile` rather than `.Dockerfile`

**Comment by adithwip** [comment]
Thank you so much, @josefaidt 
It solved! Can't believe it was because of one `.`

**Comment by josefaidt** [comment]
Hey @adithwip glad to hear that worked for you 🙏
