### ISSUE TITLE
Add command "amplify docs"

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#1209]
**Is your feature request related to a problem? Please describe.**
I often find myself referring to the docs when developing to make sure that I'm following the latest docs.  However I find myself getting distracted when switching from the code to the docs.  Additionally, when I'm in the docs themselves, I find myself clicking around to get to the section that I care about most.

**Describe the solution you'd like**
I would like to propose (and implement) a new addition to the CLI: `amplify docs` that would take the user directly to the amplify site.

**Describe alternatives you've considered**
Additionally, through iteration, it would be nice to pass in flags to get to an even more exact spot: `amplify docs --react --auth`

**Comment by kaustavghosh06** [comment]
@mtliendo That's actually a great proposal. You could maybe start by opening up an RFC on the repo and we can get community and team responses out there :)
This is an ideal candidate for a thrid party CLI plugin :) - https://aws-amplify.github.io/docs/cli/plugins?sdk=js

**Comment by swaminator** [comment]
I think getting to the specific docs would be cool too. Eg
```
amplify api docs
```

**Comment by wizage** [comment]
I would love to write the actual plugin for this too!

**Comment by mtliendo** [comment]
https://www.npmjs.com/package/amplify-docs

**Comment by wizage** [comment]
@mtliendo This looks awesome! It would be cool to add automatic detection to see if a platform has already been detected, like if they are running amplify docs in a project they would automatically be sent to js/ios/android and then they would only need to provide or select a topic beyond that.

It would be cool to also auto generate the supported platform from the github of our docs so if the docs change you wouldn't have to maintain the links to the docs themselves and instead will auto generate the code.

It looks awesome though!

**Comment by wizage** [comment]
Something like this to do the auto updating: https://github.com/wizage/amplify-category-docs/blob/master/extensions/updateDocs.js

Pretty much clones it locally and scrapes the repo for all the current documentation and generates a file (json) that has a link to anything created. Better then updating it by hand.

**Comment by mtliendo** [comment]
Thanks for the feedback @wizage! Much appreciate.  My hope was that others like yourself would chime in with great feedback.  @kaustavghosh06 since this issue has some traction already, I'd be happy to close the RFC I posted, if you wanted to tag this one as RFC instead?

**Comment by wizage** [comment]
@mtliendo I just got done adding a lot of changes to my plugin. I got around the issues you were seeing with running `amplify docs ios` this is done by using the proper naming convention `amplify-category-docs`. I also have partial search done on mine so you can just say `amplify docs api` or `amplify docs js` and it will show you all available docs for you to go to from that search. 

https://github.com/wizage/amplify-category-docs

**Comment by mtliendo** [comment]
Ah, thanks so much for the insight.  I completely missed the naming convention part.  Your version looks more robust.  I went ahead and forked to take a closer look later on today/tonight. It introduces a few more dependencies, but I say that without knowing what could be listed as a peer-dep if this were to be included in the CLI itself.

Let's plan on keeping the discussion here if you're cool with that (instead of on our individual repos). That way it's a bit more open if anyone else wanted to chime in.

**Comment by kaustavghosh06** [comment]
@mtliendo Thanks for your  plugin which solves for this :). Closing this issue in favor of a 3rd party plugin - https://www.npmjs.com/package/amplify-category-docs
