### ISSUE TITLE
interactions auto generates intent name but does not allow to hit enter 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#12098]
### Amplify CLI Version

10.7.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

1. When stepping though the interactions flow and are required to provides an intent name. Amplify auto generated the name but does not auto complete but throws a error message.

![image](https://user-images.githubusercontent.com/87995712/221009295-776542dc-d1cf-4651-ad49-3d0da5b3b399.png)

2. hitting tab auto completes the name but still fails as it only expects letters and underscores 
3. also the sample utterance also generated the field with the resource name
![image](https://user-images.githubusercontent.com/87995712/221009871-9006e470-9402-4b10-b7df-bb1099710506.png)
4. occurs on slot step as well

### Expected behavior

the field should be empty and not incorrectly generate fields. if generating data should be of expected format

### Reproduction steps

1. a add interactions
2. hit enter until
`Give a unique name for the new intent`
3. observe resource name auto generated
4. hit tab and see it fails
5. enter random name 
6. on `Enter a name for your slot (e.g. Location)`, observe same behaviour

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
I'm able to reproduce. Marking this as a bug as this flow is inconsistent with flows such as `amplify add function`:

```
➜  amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: (a126818986751) 
```
