### ISSUE TITLE
Generate all Appsync resolvers locally.

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-cli#1210]
**Is your feature request related to a problem? Please describe.**
Creating a resolver locally involves using the correct file name and VTL. Currently, I copy-paste the existing resolvers to my local directory, to ensure I get the correct file name and base VTL.

**Describe the solution you'd like**
It'd be really really convenient if `amplify add api` could also generate all the resolver files locally (if `graphql` is selected).

**Comment by kaustavghosh06** [comment]
@potatopotaro We do put the resolvers in your local file system. It's located in `<project-root>/amplify/api/<graphql-api-name>/build/resolvers`.

Let me know if that's what you were looking for.

**Comment by potatopotaro** [comment]
@kaustavghosh06 apologies for the confusion. I meant that it'd be very convenient if the `api` module could generate **all** resolver files, versus devs having to create each resolver themselves.

**Comment by kaustavghosh06** [comment]
@potatopotaro Are you referring to custom resolvers? 
Based on whatever you have in your transformer, the CLI generates corresponding resolvers based on your schema structure and puts it in your `project-root>/amplify/api/<graphql-api-name>/build/resolvers` directory. 
You can also use the `ampify api gql-compile` command to create these resolvers based on your annotated schema before pushing it to the cloud.

**Comment by potatopotaro** [comment]
@kaustavghosh06 *facepalm* yep, silly me. Thanks!
