### ISSUE TITLE
Amplify + React Native. Run Amplify init and codegen on existing project. Is it possible?

### ISSUE THREAD

**Issue by RadoAz** [aws-amplify/amplify-cli#1211]
Hi all! I can't find answer to my question anywhere. 
I updated libs:
```
 "aws-amplify": "1.1.19",
    "aws-amplify-react-native": "2.1.7",
    "aws-appsync": "1.7.2",
    "aws-appsync-react": "1.2.7",
    "aws-sdk": " 2.432.0",
```
And now I want to use amplify mutation helpers and features of amplify-cli such as codegen etc...
Tell me please, can I connect existing project (React Native, AWS Appsync) with new amplify init features?

**Comment by kaustavghosh06** [comment]
@RadoAz Yes, you can use the CLI to perform codegen operations for an existing AppSync API.
Step 1 (Configure the CLI):
amplify configure
amplify init

Step 2 (Add Codegen for your AppSync API):
amplify add codegen --apiId <api-id>


More documentation regarding this can be found out here - https://aws-amplify.github.io/docs/cli/codegen?sdk=js

**Comment by RadoAz** [comment]
@kaustavghosh06 , Thank you very much! That works! Documentation is not clear. Your answer is!)) Thanks!
