### ISSUE TITLE
Help prompt should not allow you to select a resource when removing a category

### ISSUE THREAD

**Issue by evcodes** [aws-amplify/amplify-cli#12118]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.18.0

### Amplify CLI Version

10.7.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Added hosting to my project and then tried to delete the hosting category with command `amplify delete hosting`. I had the option of selecting a plugin module to execute.
![Screenshot 2023-02-27 at 11 32 45 AM](https://user-images.githubusercontent.com/22283303/221622932-8130b496-3725-48a6-9738-a33121ef5572.png)
[](url)

### Describe the bug

Allowing me to select a module to execute when inputting the wrong command.

### Expected behavior

Just go straight from the Warning to the help usage commands without allowing me to select anything from hosting. Customer might get confused thinking that delete 

### Reproduction steps

1. npm install -g @aws-amplify/cli
2. amplify init
4. amplify add hosting
5. amplify delete hosting

### Project Identifier

2d42ef56-95b2-4e97-85af-8bd1019b1252

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
This is related to https://github.com/aws-amplify/amplify-cli/issues/12065, where `amplify override hosting` has a similar result

**Comment by evcodes** [comment]
Closed with merged PR
