### ISSUE TITLE
Oauth domain is incorrect in aws-exports after running amplify auth update

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#12111]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

10.7.3

### What operating system are you using?

macOS 13.2.1 (22D68)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Over the years, I have made several manual changes to cloud resources.  Too numerous to remember.

### Describe the bug

I recently came back to a projects built on Amplify to do some updates.  Last update was Nov 2022.

Long story short, I had a few battles getting things working, but in the end, I'm almost there.

One of the things I needed to do was run `amplify auth update`.

The one thing that I cannot seem to fix is that the `aws-exports.js` file that gets auto generated has an entry for `oath/domain` that is set to a value that is incorrect and does not match the one that has been in the Amplify Console for years.  

The entry in the `aws-exports.js` file is:

```console
myapp-auth-prod.auth.us-west-2.amazoncognito.com
```
Whereas the entry in the Amplify Console is:
```console
myapp.auth.us-west-2.amazoncognito.com
```

For some reason `-auth-prod` has been inserted into the domain.  I've done a search for any match of that pattern in my local code, and it only exists in `aws-exports.js`.

I cannot find where I might change this on the "cli side" of things.

I do not wish to change the domain in the Amplify Console as the backend is shared.

The result of this that I need to maintain a copy of `aws-exports.js` with the "correct" domain and use that when configuring Amplify in the app.

### Expected behavior

After running `amplify auth update` the domain should not be changed and/or should reflect what is set in Amplify Console.

There should be an obvious way to update the domain on the "cli side".  Maybe there is, but I couldn't find it.

### Reproduction steps

1.  Go to an app that hasn't been updated in months.
2. Run `amplify auth update`, updating the Oauth for federated login.
3. Do an `amplify push`
4. View the oath/domain entry in `aws-exports.js` and see that it has had "-auth-envName" appended to the app name.

### Project Identifier

I've run `amplify diagnose --send-report`

Here's the identifier:  b797c482f6dbdb26fff6fdefa1d7ef18

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

My workaround for this is to maintain a copy of the `aws-exports.js` file and manually update the domain to match the domain in the Amplify Console.  Then use the copy when running `Amplify.configure()`

If there is a way to tell the cli to use a different domain, I can't find it.

Any advice toward helping me resolve this issue would be most appreciated.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @kimfucious :wave: thanks for raising this! This issue seems similar to https://github.com/aws-amplify/amplify-cli/issues/11706 where the OAuth domain was manually updated in the AWS Cognito Console, however it would be recommended to make these changes with [resource overrides](https://docs.amplify.aws/cli/auth/override/).

**Comment by kimfucious** [comment]
HI @josefaidt,

Thanks for the response.

For the record, I've not created a custom domain, I've just added a domain.  This was years ago now, and to the best of my recollection, I needed to do this, as the cli didn't do this prior.

Now, well long after that user pool was created and the domain added, running the update makes some assumptions, it seems.

I looked at the overrides stuff you mentioned, but it seemed way too complicated and kinda scary.  Since all I want to do is align what's in `aws-exports.js` about the domain name and what the actual domain name is, I'm gonna stick with my work-around as mentioned prior.

**Comment by josefaidt** [comment]
Hey @kimfucious thanks for the update, and understandable! You can also tweak the `hostedUIDomainName` property of your auth resource's cli-inputs.json if you'd like a shorter URL, however it will append the environment name to it (e.g. `short-prod`).

With the update and the existing feature request I will close this in favor of tracking the existing item, but let us know if changing `hostedUIDomainName` property isn't sufficient and we can re-open to address further 🙂
