### ISSUE TITLE
Profiles not loading after changes in 10.8.0

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-cli#12120]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v18.13.0

### Amplify CLI Version

10.8.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I'm using GitHub actions to run amplify in CLI.
This grabs credentials using the following action aws-actions/configure-aws-credentials@v1-node16 via OIDC

Previously I was doing the following

```bash
cat <<- 'EOF' > ~/.aws/config
[profile gladly]
credential_process=bash -c 'echo "{ \"Version\": 1, \"AccessKeyId\": \"${AWS_ACCESS_KEY_ID}\", \"SecretAccessKey\": \"${AWS_SECRET_ACCESS_KEY}\", \"SessionToken\": \"${AWS_SESSION_TOKEN}\", \"Expiration\": \"2031-11-24T17:12:42+00:00\" }"'
region=ap-southeast-2
EOF

REACTCONFIG="Not Relevant"
AMPLIFY="Not Releavnt"
FRONTEND="Not Relevant"

AWSCLOUDFORMATIONCONFIG="{\
  \"configLevel\": \"project\",\
  \"useProfile\": true,\
  \"profileName\": \"gladly\",\
  \"region\": \"ap-southeast-2\"\
}"

PROVIDERS="{\
  \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

echo n |  amplify pull \
  --appId $APPID \
  --amplify $AMPLIFY \
  --frontend $FRONTEND \
```

This now errors out with 
```
🛑 Failed to get profile credentials
Profile gladly not found
```

### Expected behavior

Amplify pull succeeds

### Reproduction steps

See above

### Additional information

I think this is related to the change at https://github.com/aws-amplify/amplify-cli/pull/11821/files#diff-81c461c201c6a399d242fcf6409027b42824db979bfd47388f25668e0dd3bb60R94-R104

Not that a filename is being passed to ```ProcessCredentials``` it acts differently. It is looking for ```[gladly]``` instead of ```[profile gladly]]]```

I've worked around it by removing ```profile``` from the config file but that's not technically what an ~/.aws//config is supposed to look like

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @johnf :wave: thanks for raising this! I was able to reproduce this issue using the provided information. Marking as a bug 🙂
