### ISSUE TITLE
Missing region in config

### ISSUE THREAD

**Issue by dan-hook** [aws-amplify/amplify-cli#12129]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.14

### Amplify CLI Version

10.8.0

### What operating system are you using?

WSL2 on Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, many.

### Describe the bug

I get the error "Missing region in config" when executing the following commands:

 $ amplify update api
? Select from one of the below mentioned services: GraphQL

General information
- Name: applicationname
- API endpoint: https://**************.appsync-api.us-east-1.amazonaws.com/graphql

Authorization modes
- Default: Amazon Cognito User Pool
- IAM

Conflict detection (required for DataStore)
- Disabled

? Select a setting to edit (Use arrow keys)
❯ Authorization modes 
  Enable conflict detection (required for DataStore) 🛑 Missing region in config

### Expected behavior

I expected to be able to update the api

### Reproduction steps

1. Update to 10.8.0
2. Run amplify configure and set up a new user with region us-east-1
3. Run amplify update api
4. Select GraphQL

### Project Identifier

9c19ea5526c1afd0a3e1987ea44f96af

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
hey @dan-hook, from the reproduction steps i noticed that the update api command was being in an existing application. wanted to confirm if you also ran `amplify configure project` and modify the profile setting?
do ensure that the user created is in the same account where the Amplify project exists. Do let me know if i may have misunderstood anything.

**Comment by dan-hook** [comment]
Thanks @ykethan.  I created the new user in a different account than the environment I was working in.  Creating the user in the same account resolved the issue.  
We have environments for this amplify application in three accounts (sandbox, integration, production).  What's the best way to manage credentials between accounts?

**Comment by ykethan** [comment]
> What's the best way to manage credentials between accounts?

hey @dan-hook, Are you referring to managing AWS credentials with multiple AWS profiles or under the context of AWS Profiles and Amplify environments? If the latter, we create and maintain a file `amplify/.config/local-aws-info.json` that contains references to each Amplify environment and their respective AWS profile/auth mechanism.

**Comment by dan-hook** [comment]
I started running into this issue again and I can't seem to resolve it this time.  I would like to understand what files amplify configure is changing.  I would prefer to bypass it and use profiles with SSO roles instead of IAM users.  

I'm still not sure why I'm getting the "missing region in config" error.
In my local-aws-info.json I have:
  "restore": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "sandbox-dan-amplify"
  },

And in my .aws/config I have:
[profile sandbox-dan-amplify]
sso_start_url=https://companynameaws.awsapps.com/start
sso_region=us-east-1
sso_account_name=sandbox-daniel.hook
sso_account_id=096*********
sso_role_name=AWSAdministratorAccess
region=us-east-1
credential_process=aws-sso-util credential-process --profile sandbox-daniel.hook.AWSAdministratorAccess

**Comment by josefaidt** [comment]
Hey @dan-hook there is currently a bug with AWS credentials from SSO credential_process, see https://github.com/aws-amplify/amplify-cli/issues/12174#issuecomment-1476927553. From the linked comment, your `~/.aws/config` would look like:

```ini
# ~/.aws/config
[profile sso-josef]
sso_session = josef
sso_account_id = xxx
sso_role_name = AdministratorAccess
region = us-east-1
credential_process = aws sso login --profile sso-josef
[sso-session josef]
sso_start_url = https://xxx.awsapps.com/start#
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

This will allow us to successfully authenticate, however in the active bug Amplify CLI fails to read credentials with this process

**Comment by josefaidt** [comment]
Closing in favor of tracking #12174 for `credential_process` fix
