### ISSUE TITLE
Amplify pull not working in flutter

### ISSUE THREAD

**Issue by veeramneni** [aws-amplify/amplify-cli#12179]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.0.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Added cognito authentication via Amplify studio

### Describe the bug

See below steps and error when I try to run amplify pull like this:

amplify pull --appId xxxxxxxxxxx --envName prod

⠴ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Amplify AppID found: d15vdehikertkk. Amplify App name is:xxxxxx
Backend environment prod found in Amplify Console app: xxxxxx
? Choose your default editor: Android Studio
? Choose the type of app that you're building flutter
Please tell us about your project
? Where do you want to store your configuration file? ./lib/
? Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment prod from the cloud.
✖ There was an error initializing your environment.
🛑 Could not initialize categories for 'prod': Unknown project type flutter

### Expected behavior

Expected to see amplify project pulled locally

### Reproduction steps

Create an empty amplify project 
Add authentication in amplify studio
Pull the project locally

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by evcodes** [comment]
In order to better repro this, here are the steps I followed:

1. Create an amplify app. And follow the flutter getting started guide.
2. Push the amplify app up the cloud.
3. Enable Studio
4. Add Auth via Amplify Studio
5. Try to pull the app down 

I have a few questions about the pull phase:

1. Are you trying to pull this app down to a fresh new environment or the same?
2. Are you using the same AWS Account or are you adding another developer?

**Comment by evcodes** [comment]
For step 5, I changed directory to a folder that was brand new and pulled the backend from Studio after creating the Authentication through Cognito User Pools. I did not test anything from Flutter but I wasn't able to get the error message that you got.

**Comment by veeramneni** [comment]
Thanks for the response. I am trying to pull this app down to fresh new environment and tried with same AWS account which was used to created the amplify app. After creating the issue, I wanted to make sure if it has anything to do with the User pool am using in cognito. So I created a new user pool and used that with 'amplify import auth'. I don't see the issue anymore. I suspect something's different with existing user pool. Just not sure what and we need to use existing user pool for this project. I will post if I can find anything that is different between existing and new user pool.

**Comment by veeramneni** [comment]
I narrowed it down to identity pool. As a workaround, I created a new identity pool but could never figure out why amplify gives me above error for existing identity pool. I am closing this ticket as I have a solution.
