### ISSUE TITLE
Support deleting AWS profiles with Amplify CLI

### ISSUE THREAD

**Issue by Josephenoch** [aws-amplify/amplify-cli#12201]
### Is this related to another service?

Amplify CLI

### Describe the feature you'd like to request

I want to delete some profiles that are outdated. Currently, it is impossible to do so.

### Describe the solution you'd like

Make it possible to delete a profile

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Adding `wontfix` for this feature request and closing in favor of modifying the files manually or using the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/customer-profiles/delete-profile.html)
