### ISSUE TITLE
My project is stuck in zombie state cannot pull nor push 

### ISSUE THREAD

**Issue by yanivams** [aws-amplify/amplify-cli#12214]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3rqssorvqkf17

### Region

us-east-1

### Environment name

dev

### Amplify CLI Version

10.7.0

### What operating system are you using?

Mac

### Browser type?

Chrome

### Describe the bug

My project is stuck in some zombie state. 

I created a lambda function pushed it, then removed it created 2 others and push again from this point I got to some inconsistency that I can't recover from. The pushed failed, so I remove than 2 new functions and try to push again and again failure. Now I can't pull the project nor push. 

When trying to pull I get this error: Failed to extract zip file: 
EEXIST: file already exists, symlink 'python3' -> 'path to the fucntion I am trying to delete/myenv/bin/python'

when I try to recover this by deleting the amplify folder I get this failure: Failed to pull the backend.

Please advise how to work around the problem, thanks.

### Expected behavior

I should be able to pull and get back to some consistent state.

### Reproduction steps

described above

### Project Identifier

f29ff0a5d1d1940318a05fc933b627b5

**Comment by ykethan** [comment]
Hey @yanivams , thank you for reaching out and apologies for the inconvenience. The Amplify CLI team is currently this behaviour. The workaround would be to modify your `#current-cloud-backend` zip  and re-upload the zip file. The steps have been outlined [here](https://gist.github.com/josefaidt/a117076b7bea81e1872e275176dbb23c). From the issues provided in the previous comment, deleting the `.temp` folder within the Amplify directory has also mitigated the issue. Please do let us know if you require any additional information.

**Comment by yanivams** [comment]
Thank you for your response. I was able to find a work around for this - it included manually changing the zip and a bunch of other files as well. I think the bug should be address soon. I was disappointed to see it is known for a few years now and had not been resolved, for me it burned a few days of work. For others it may burn even more
