### ISSUE TITLE
build issue aws amplify

### ISSUE THREAD

**Issue by MatthewGladkowski** [aws-amplify/amplify-cli#12213]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.19.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None made

### Describe the bug

I run into a build script issue. I understand that it is not in my scripts under my package. However, I do not know what to put into the script. I just want it to run my api.

### Expected behavior

run amplify publish:
publish to frontend (yes) and have it run

### Reproduction steps

amplify init
 - Enter <
 - Yes
 - AWS Access Keys (keys added)
 - US-east-2
 - Yes

 amplify add api
 - REST
 - Enter <
 - Enter <
 - Enter <
 - NodeJS
 - Serverless ExpressJS function (Integration with API Gateway)
 - No
 - No
 - No
 - No

amplify push
 - Yes

amplify hosting add
 - Amazon CloudFront and S3
 - DEV (S3 only with HTTP)
 - Enter <
 - Enter <
 - Enter <

amplify publish
 - Yes
 
 ERROR appears
![image](https://user-images.githubusercontent.com/115107906/224613681-66a34051-01f3-41dc-a5ae-06dc813aa8ac.png)

package: 
![image](https://user-images.githubusercontent.com/115107906/224612646-4216f37f-76f1-4691-841c-4293dafe7b61.png)

I check status with
amplify status
![image_2023-03-13_011326026](https://user-images.githubusercontent.com/115107906/224613495-d08ee3b7-1f39-46cf-a9f9-8630ae7f7dd1.png)

the REST API Endpoint has this error
![image_2023-03-13_010134159](https://user-images.githubusercontent.com/115107906/224612135-e5b1983f-59e0-4bd7-bad7-b99a1ac0497b.png)
and the Hosting Endpoint:
![image](https://user-images.githubusercontent.com/115107906/224612231-d1850417-1536-4226-b11c-2a507e39d395.png)

### Project Identifier

Project Identifier: 6af7648d47226c99e6855efb189d959c

### Log output

<details>

```
# Put your logs below this line
0 verbose cli /usr/local/share/nvm/versions/node/v16.19.0/bin/node /home/codespace/nvm/current/bin/npm
1 info using npm@8.19.3
2 info using node@v16.19.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/share/nvm/versions/node/v16.19.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/workspaces/COP4934-SD-Project/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/codespace/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/share/nvm/versions/node/v16.19.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 12ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 18ms
19 timing npm:load:configload Completed in 19ms
20 timing npm:load:mkdirpcache Completed in 4ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm run-script build
23 verbose argv "run-script" "build"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 6ms
27 verbose logfile logs-max:10 dir:/home/codespace/.npm/_logs
28 verbose logfile /home/codespace/.npm/_logs/2023-03-13T04_54_19_087Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 40ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run-script Completed in 5ms
36 verbose stack Error: Missing script: "build"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/usr/local/share/nvm/versions/node/v16.19.0/lib/node_modules/npm/lib/commands/run-script.js:98:13)
36 verbose stack     at async module.exports (/usr/local/share/nvm/versions/node/v16.19.0/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /workspaces/COP4934-SD-Project
38 verbose Linux 5.4.0-1104-azure
39 verbose node v16.19.0
40 verbose npm  v8.19.3
41 error Missing script: "build"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
43 timing npm Completed in 77ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /home/codespace/.npm/_logs/2023-03-13T04_54_19_087Z-debug-0.log
```

</details>

### Additional information

I looked up several sources and was left with no solution. I have been at this for hours and I'm turning for assistance because I am stuck. I would immensely appreciate any help at all. I will follow suggests and provide information requested to help.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @MatthewGladkowski, thank you for reaching out. wanted to get some information. were there any changes to the API gateway?
additionally, how is the API url being utilized. are you calling the api with the path? for example: `https://<id>.execute-api.us-east-1.amazonaws.com/<env stage>/items`.
on the API gateway console, are you able to run a test on the client in the `resources` under the path provided?

**Comment by MatthewGladkowski** [comment]
> Hey @MatthewGladkowski, thank you for reaching out. wanted to get some information. were there any changes to the API gateway? additionally, how is the API url being utilized. are you calling the api with the path? for example: `https://<id>.execute-api.us-
![image_2023-03-13_143227833](https://user-images.githubusercontent.com/115107906/224796858-6e1cd72e-958f-4594-805b-80a5e86aa2ac.png)
east-1.amazonaws.com/<env stage>/items`. on the API gateway console, are you able to run a test on the client in the `resources` under the path provided?

I changed the resources to match my api. using router names and get/put/etc. functions. i used the "hello world" preset for the home route (/items -> /routes). 
and using the url you suggested (my REST API endpoint) did fix that issue
![image_2023-03-13_143319941](https://user-images.githubusercontent.com/115107906/224797208-67918b80-0ced-4627-8290-0e0709f7c11a.png)
This is the layout for my urls
![image_2023-03-13_143109671](https://user-images.githubusercontent.com/115107906/224796558-182b2e7b-6079-4f4b-8df7-89235366ce5f.png)
I execute (url)/routes/users/all and get:
![image_2023-03-13_143450767](https://user-images.githubusercontent.com/115107906/224797507-f9bb7219-a1b5-499e-a56a-c4b6f3ca319b.png)

The purpose of that function is to output my array of objects (user data)
this works fine with localhost but I am having issues with it here.
Thank you for the help with the url addition. It did help so that's progress and I really appreciate it :)

**Comment by ykethan** [comment]
hey @MatthewGladkowski, from the error message it appears the Lambda function may be erroring out.
could you try using the test button as shown below to test the endpoint.
![image](https://user-images.githubusercontent.com/87995712/225394814-673105d4-beba-472f-a105-7605c685e04d.png)
if the test fails with the same error, this would point that the Lambda function code may be erroring out. I would suggest checking the Lambda function logs or the log group in the monitoring tab for any errors provided by the function.

Could you provide us some additional information on your use case? are you calling the API from your frontend?
if yes, are you utilizing amplify libraries to call the API? Please refer to https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/ providing information on this.

**Comment by ykethan** [comment]
hey @MatthewGladkowski, unfortunately lambda function has the limits as follows. https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
![image](https://user-images.githubusercontent.com/87995712/225398881-4617caa5-6d51-4a6d-a9d3-baab97f84056.png)
You may need to chunk the json payload and pass it the lambda function or may need to utilize a custom solution such as an S3 bucket to fetch the portion of data from storage bucket and process the data in the Lambda function.
 I was able to find this [article](https://theburningmonk.com/2020/04/hit-the-6mb-lambda-payload-limit-heres-what-you-can-do/) but as this is a 3rd part resource I would suggest testing your use case thoroughly before utilizing this in your prod if the solution meets your use case. 
 additionally, I would also suggest reaching out to the Lambda function support team for any additional information on the use cases.

**Comment by MatthewGladkowski** [comment]
> hey @MatthewGladkowski, unfortunately lambda function has the limits as follows. https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
> ![image](https://user-images.githubusercontent.com/87995712/225398881-4617caa5-6d51-4a6d-a9d3-baab97f84056.png)
> You may need to chunk the json payload and pass it the lambda function or may need to utilize a custom solution such as an S3 bucket to fetch the portion of data from storage bucket and process the data in the Lambda function.
>  I was able to find this [article](https://theburningmonk.com/2020/04/hit-the-6mb-lambda-payload-limit-heres-what-you-can-do/) but as this is a 3rd part resource I would suggest testing your use case thoroughly before utilizing this in your prod if the solution meets your use case. 
>  additionally, I would also suggest reaching out to the Lambda function support team for any additional information on the use cases. 

Thank you very much I will look into this. I believe I was able to successfully satisfy my original issue and I greatly appreciate your assistance as I was able to get my API working  :)
