### ISSUE TITLE
Sharing same dynamodb between enviornement

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-cli#1221]
Hi can we use same dynamoDB between multiple env ? in our case we need to have multiple appsync , but only one dynamoDB .

**Comment by mikeparisstuff** [comment]
You can use custom stacks to reference a single DynamoDB table but it is not currently supported via the GraphQL Transform alone. To learn more about referencing custom resources via custom stacks see this example using lambda here https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-an-aws-lambda-function. I'll also suggest taking a look at #1060 and #1062 and offering feedback there. With #1060 you will be able to write your own transformers for custom use cases that are not supported out of the box. #1062 is not final and will go through another round of design review that will address using existing tables as well as defining completely custom index structures and key schemas that can be used with models.
