### ISSUE TITLE
Bump `aws-cdk-lib` to `2.60.0` or newer in custom resources (v11.0.0)

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-cli#12224]
### Is this related to another service?

Extensibility

### Describe the feature you'd like to request

Version `v11.0.0` released support for CDK v2 in the extensibility helper/category. However new custom resources generated with the latest version of the CLI bring a version of `aws-cdk-lib` that it's over 3 months old (`~2.5.3`).

Before v11.0.0 it was possible to manually override the CDK version in the custom resource, however now the `@aws-amplify/cli-extensibility-helper` sets `aws-cdk-lib@~2.53.0` as dependency, which prevents us from updating the version in the custom resource.

The main issue here is that this version of `aws-cdk-lib` is pretty old and notably it's missing the stable version of `aws-cdk-lib/aws-appsync`, which was released in `2.60.0`.

### Describe the solution you'd like

It'd be great if in the short term you could update the `aws-cdk-lib` version [to at least `2.60.0`](https://github.com/aws/aws-cdk/releases/tag/v2.60.0), which is the version that promotes the `aws-cdk-lib/aws-appsync` package to stable.

In the medium/long term, it'd also be great if the custom resource could be more forgiving with the version allowing for overrides, but even just the point above in the next release of the CLI would be great.

### Describe alternatives you've considered

None, the fact that `@aws-amplify/cli-extensibility-helper` also brings a specific version of `aws-cdk-lib` as direct dependency means we can't install another version in the custom resource as this will equal to have two different CDK versions which breaks stacks (see error below):

<img width="806" alt="Screenshot 2023-03-14 at 08 15 08" src="https://user-images.githubusercontent.com/7353869/224960825-ae53edb5-51a5-4bb3-b28d-716b5efcbaed.png">

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by pbv0** [comment]
+1 having access to a more up-to-date CDK release would be very important to make it usable in my current project.

**Comment by LesitoT** [comment]
> +1 having access to a more up-to-date CDK release would be very important to make it usable in my current project.

+1

**Comment by alevzfdez** [comment]
+1

**Comment by vitrvm** [comment]
+1

**Comment by NachoFLizaur** [comment]
+1

**Comment by gbiagini97** [comment]
+1

**Comment by dreamorosi** [comment]
Folks, if you can help it, don't just comment +1.

It doesn't further the conversation and it's not nice/respectful towards the maintainers. If you'd like to express support for the feature/issue, [use reactions on the OP](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/).

**Comment by sobolk** [comment]
Please expect next version of CLI to be shipped with CDK `2.68.0`.
See https://github.com/aws-amplify/amplify-cli/pull/12240 for reference.

**Comment by dreamorosi** [comment]
Thank you @sobolk and the rest of the team for addressing this.

I for one appreciate the work you're doing and the response to this issue.

**Comment by hackmajoris** [comment]
Waiting fo this to be merged.
