### ISSUE TITLE
Using existing dynamodb in amplify cli

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-cli#1222]
Hi can we configure amplify to use existing dynamodb ?

**Comment by yuth** [comment]
@vjindalaurea in which service do you want to use the existing dynamodb table? Do you want to set the use the existing dynamodb table in storag category?

**Comment by vjindalaurea** [comment]
I want my appsync to use existing dynamodb tables in datasource section . 



![image](https://user-images.githubusercontent.com/25425699/55770759-1cbf9f00-5aa3-11e9-8be6-f5aa1e83b064.png)

**Comment by mikeparisstuff** [comment]
Hey @vjindalaurea, you can use custom stacks within the Amplify API category to target existing DynamoDB tables. You can learn more about how to do this here: https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-an-aws-lambda-function. The example here uses a Lambda function but the process is the same for a DynamoDB table.

I would also point you towards #1060 where we are discussing opening up ways that would allow you to build your own transformers. This would allow you to build your own directives that encapsulate your own custom behaviors. Please leave feedback if this helps.

**Comment by ASchwad** [comment]
Can i also use an existing dynamoDB for a REST API within Amplify? I cannot find any resources for this option
