### ISSUE TITLE
Amplify publish fails - Mac arm64

### ISSUE THREAD

**Issue by tarasowski** [aws-amplify/amplify-cli#12223]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.15.0

### Amplify CLI Version

11.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes

### Describe the bug

During an amplify publish operation the build phase fails with the following error:

error during build:
Error: 
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/darwin-arm64" package is present but this platform
needs the "@esbuild/darwin-x64" package instead. People often get into this
situation by installing esbuild with npm running inside of Rosetta 2 and then
trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
2 is Apple's on-the-fly x86_64-to-arm64 translation service).

If you are installing with npm, you can try ensuring that both npm and node are
not running under Rosetta 2 and then reinstalling esbuild. This likely involves
changing how you installed npm and/or node. For example, installing node with
the universal installer here should work: https://nodejs.org/en/download/. Or
you could consider using yarn instead of npm which has built-in support for
installing a package on multiple platforms simultaneously.

If you are installing with yarn, you can try listing both "arm64" and "x64"
in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

### Expected behavior

It should run the build and upload to the cloud, since when I ran npm run build it works all fine on my local machine, but fails when amplify tries to do so. 

### Reproduction steps

1. Install Svelte via vite (https://vitejs.dev/guide/)
2. amplify init
3. amplify add hosting
4. amplify publish -> here should it fail ( but has to be tested on arm64 architecture - Apple Silicon)

### Project Identifier

Project Identifier: 9dee0803ff3c0ac202eb884cf86277d9

### Log output

Cannod find any issue logs on my system.

### Additional information

I ended up with a simple hack of building manually on my local machine and let only the amplify upload the files from the dist directory. It works perfectly.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @tarasowski thanks for raising this! I was not able to reproduce this using the provided steps and I see the arm64 esbuild package in my node_modules, and I have a few follow-up questions:

- Are you switching terminals when installing dependencies or running Amplify commands? 
- What package manager are you using?
- How was Amplify CLI installed?
- If you run the same command with `--debug` does it print a stack trace?
