### ISSUE TITLE
I'm unable to push any updates to my resources and there are no errors

### ISSUE THREAD

**Issue by ZalgirisKaunas** [aws-amplify/amplify-cli#12248]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.21

### Amplify CLI Version

11

### What operating system are you using?

windows 

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I haven't made any manual changes recently.

### Describe the bug

I tried to update one lambda function that was not updated for a couple of years and it was configured to use node 10.x runtime.
I think it also got stuck while reverting to the last successful build.

![image](https://user-images.githubusercontent.com/19693550/225628680-994ef0e5-48b9-43e1-84ba-efb5529c4f2e.png)

After that whenever I try to do amplify push, it says job succeeded but it does not deploy anything and doesn't give any errors. If I do amplify push again the changes are still listed in the resources table that has to be pushed.

The whole process after trying push command is quick and show 0 deployment progress.

![image](https://user-images.githubusercontent.com/19693550/225630053-926d714a-52ea-4d81-b1e1-1c5f2f7d9770.png)

I tried pushing with various flags as well as doing env checkout test --restore. cloning the app backend, deleting amplify directory or specific resources manually but nothing works.

### Expected behavior

to deploy the resources

### Reproduction steps

it relates only to my project backend

### Project Identifier

f4886b112bb1887bb97fcd3eebeeb30f

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @ZalgirisKaunas :wave: thanks for raising this! What were the updates made to the function? Are you able to manually modify the Function's CloudFormation template to use `nodejs16.x` as the runtime?

**Comment by ZalgirisKaunas** [comment]
I managed to fix this by deleting the child cloudformation stack for the corrupted function in the console, restarting the revert process with "skip resources" tick on and updating my template files on my machine.
