### ISSUE TITLE
Publishing with node 8.12.0 results in error page

### ISSUE THREAD

**Issue by e2yerik** [aws-amplify/amplify-cli#1226]
**Describe the bug**
I have developed an application with Amplify, React and the Authentication module. During development, I worked with node 11.8.0 and publishing works without a problem. The app works on the amazon hosted environment.

When I change my node version to 8.12.0 (which is used by AWS Amplify Console), the deployment will get an error
```
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: EB80C60FE9487D80
HostId: fWtPF7lQEagnvH6XxRLMVHFQyxAD6dC3+bVTiG4AeNCHXuINgxsw2oJK2+535aL9RSBLz9HeEUk=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: AccessDenied
Message: Access Denied
```

**To Reproduce**
1. Set node version to 8.12.0
2. Run amplify push
3. Run amplify publish
4. Wait for the deployment to succeed and the browser will open. In the browser you will see the error.

**Expected behavior**
The app should serve login page

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3 (18D109)
 - Browser chrome
 - Version 72

**Relevant information**
_Amplify status:_
```
$ amplify status

Current Environment: servcat

| Category | Resource name        | Operation | Provider plugin   |
| -------- | -------------------- | --------- | ----------------- |
| Auth     | cognito8f0f2f1d      | No Change | awscloudformation |
| Hosting  | S3AndCloudFront      | No Change | awscloudformation |
| Function | ec2instancesfunction | No Change | awscloudformation |
| Function | ec2regionsfunction   | No Change | awscloudformation |
| Api      | ec2instancesapi      | No Change | awscloudformation |
| Api      | ec2regionsapi        | No Change | awscloudformation |

Hosting endpoint: http://aws-service-catalog-20190329132904-hostingbucket-servcat.s3-website-eu-west-1.amazonaws.com
```

**What I've tried**
`amplify update auth` to fix any problems with the `auth` module.

**Comment by juliacoleman11** [comment]
im getting the same issue but I am using node 10.16.3, has this been resolved?
