### ISSUE TITLE
Consistent failure on Amplify CI/CD pipeline.

### ISSUE THREAD

**Issue by bwang-movano** [aws-amplify/amplify-cli#12289]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19

### Amplify CLI Version

9.2.1

### What operating system are you using?

MAC

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

This happens very often in Amplify CI/CD pipeline.

  [31mAn error occurred when creating the CloudFormation stack[39m
2023-03-21T13:23:05.150Z [INFO]: 🛑 Stack [amplify-XXXXXXX-62609] already exists
2023-03-21T13:23:05.150Z [INFO]: Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
 [INFO]: Session Identifier: 39d3ef24-fd44-460a-8b4e-489d8eb4854b
2023-03-21T12:24:43.410Z [WARNING]: - Creating Zip
2023-03-21T12:24:43.466Z [INFO]: 
2023-03-21T12:24:43.466Z [INFO]: ✅ Report saved: /tmp/RingApp/report-1679401483417.zip
2023-03-21T12:24:43.466Z [WARNING]: - Sending zip
2023-03-21T12:24:44.972Z [WARNING]: ✔ Done
2023-03-21T12:24:44.972Z [INFO]: Project Identifier: 2706ed17bffa2b5bd75102381f6c922d

we have been running into this same errors consistently

### Expected behavior

CI/CD should work in a new ENV

### Reproduction steps

1. we have a repo with all amplify related resource.
2. We have initial Amplify Dev ENV, where CI/CD works,.
3 . clone the repo, add a new Amplify ENV, push, set up CI/CD pipeline from Amplify console with a git repo branch.
4. The initial build works from #3.
5. Make code changes, push to dev branch, dev branch builds fine.
6. Merge the changes into the newly created ENV from #3, the build fails with:

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @bwang-movano :wave: thanks for raising this! What sort of changes were made prior to receiving this? I attempted to make a frontend change and merge to no avail.

**Comment by bwang-movano** [comment]
I got this figured out, this i think should be document somewhere.

It turned out that team-provider-info.json is very important for CICD to work in different ENV.

If a amplify ENV is connected to a branch, and  team-provider-info.json in that branch does not have its own env entry, then amplify (cloudformation) attempts to create a root stack with the same name, because it was created at the time the ENV is created. 

Only if the ENV entry exists in  team-provider-info.json, cloudformation only updates it, instead of create it.

This should be documented somewhere I think, who would think that  team-provider-info.json is significant to CICD pipeline, most just think it is non-essential to build and run time, only developer collaboration.

You can close this issue. 

Thanks.

**Comment by josefaidt** [comment]
Hey @bwang-movano glad to hear you are up and running despite the experience. I've made a note to improve our documentation around this subject, but will close this for now
