### ISSUE TITLE
How to secure subscriptions ?

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-cli#1228]
**Which Category is your question related to?**
Amplify / AppSync

**Provide additional details e.g. code snippets**
Let's create a subscription that receive updates on some user account data : 
```
type Subscription{   
    onUpdateUserAccount(id: ID!):UserAccount @aws_subscribe(mutations:["updateUserAccount"])
}
```
From the client, you will pass the UserAccountID that you first got from a query, and everything will work. Securing the query is doable with custom VTL logic in the resolver.

How to protect someone from passing another ID than it's own ID when subscribing, and hence getting the UserAccount from someone else ? 

Subscriptions don't seem to be linked to resolvers in AppSync interface, do I need to create a sort of custom resolver here ? 

I would love being able to define the subscription with : onUpdate**My**UserAccount:UserAccount

**Comment by kaustavghosh06** [comment]
@vparpoil We recently added support for adding authorization for your subscriptions. Please take a look at the documentation out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions
