### ISSUE TITLE
Amplify pull fails

### ISSUE THREAD

**Issue by javoguadas** [aws-amplify/amplify-cli#12304]
### How did you install the Amplify CLI?

yarn 

### If applicable, what version of Node.js are you using?

v18.14.0

### Amplify CLI Version

11.0.3

### What operating system are you using?

Windows with WSL2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Amplify push is failing and try to do an Amplify pull
```
Pre-pull status:

    Current Environment: sampledev
    
┌──────────┬──────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name        │ Operation │ Provider plugin   │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ testregistrationlink │ Update    │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Auth     │ testregistrationlink │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting       │ No Change │ awscloudformation │
└──────────┴──────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✖ There was an error initializing your environment.
🛑 File at path: '/home/javo/dev/learn/test-registration-link/amplify/team-provider-info.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

### Expected behavior

The pull must restore de project from the cloud version

### Reproduction steps

Amplify pull

### Project Identifier

1396000e98de7be2177b1b3e6e446903

### Log output

<details>

```
# Put your logs below this line
2023-03-23T23:44:44.588Z|info : amplify pull core  
2023-03-23T23:44:44.624Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-03-23T23:44:53.195Z|error : File at path: '/home/javo/dev/learn/test-registration-link/amplify/team-provider-info.json' does not exist
UnknownFault: File at path: '/home/javo/dev/learn/test-registration-link/amplify/team-provider-info.json' does not exist

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @javoguadas :wave: thanks for raising this! Does this file exist in your project? How was the project pulled?

**Comment by javoguadas** [comment]
Yes.
The file exists.
[image: image.png]
The project was pulled with amplify pull
Atte:
Javier Guadarrama

**Comment by josefaidt** [comment]
Hey @javoguadas thanks for clarifying. Can you confirm this path contains the valid path to your project?

```
/home/javo/dev/learn/test-registration-link/amplify/team-provider-info.json
/home/javo/dev/learn/test-registration-link/ # project directory
```

I was not able to reproduce this issue

**Comment by javoguadas** [comment]
Yes that is the correct path

**Comment by josefaidt** [comment]
Hey @javoguadas thanks for clarifying. Are you working primarily from within WSL? We store a reference to the project's path in `amplify/.config/local-env-info.json` and I'm curious if this is a side effect of moving between WSL and PowerShell. Are you able to pull this project into a separate directory without error? If so, are you able to run `amplify pull --restore` in your current project directory and continue with updates without error?
