### ISSUE TITLE
Amplify push fails in monorepo using yarn workspaces due to node package dependency detector

### ISSUE THREAD

**Issue by acusti** [aws-amplify/amplify-cli#12306]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v19.8.1

### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

i have a monorepo (via yarn workspaces and yarn version `1.22.19`) with an amplify backend at the root of one of my frontend projects, as recommended in the [amplify CLI docs](https://docs.amplify.aws/cli/project/monorepo/). i upgraded to the latest version of the amplify CLI this morning (11.0.3) and i am no longer able to run `amplify push`, because it fails with the error:

```
🛑 Lockfile not found at location: /path/to/repo/frontend-project-folder/amplify/backend/yarn.lock
```

however, there shouldn’t be a `yarn.lock` file in `amplify/backend/` because i have a monorepo setup using yarn workspaces, so there is only a single `yarn.lock` file at the root of my repo.

### Expected behavior

i expect `amplify push` to succeed in a repo that is setup using yarn workspaces as a monorepo using the approach recommended by the [amplify CLI docs](https://docs.amplify.aws/cli/project/monorepo/).

### Reproduction steps

1. create a new amplify project using yarn workspaces
2. in the root of the main frontend project’s workspace, initialize a new backend
3. add a REST API and an override (e.g. https://docs.amplify.aws/cli/restapi/override/#add-a-cognito-user-pool-authorizer-to-your-rest-api) or a custom resource
4. run `amplify push`

### Project Identifier

4cce2c1871372609297d98c2261bc65e

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by acusti** [comment]
i looked through the PR that added the lockfile parsing: https://github.com/aws-amplify/amplify-cli/pull/11629

it’s being used to check for and warn about any cdk v1 dependencies, but it checks for `yarn.lock` exclusively at the [amplify `projectRoot`](https://github.com/aws-amplify/amplify-cli/commit/bc1bca947af243cab70cea484b4325da3f817198#diff-cb6dfbb2d014884a3749e658f8b2fcfdf71a6baa39adb732e08a1cbf83350d41R65) (`this.getLockFileContent(amplifyDetectorProps.projectRoot)`), so i don’t see how it could work with a monorepo setup.

as a note, my yarn `workspaces` array (in the root package.json) includes both the root directory of my primary frontend project and the `amplify/backend` project inside that frontend project.

**Comment by josefaidt** [comment]
Hey @acusti :wave: thanks for raising this! In a monorepo setting I can see the value behind adding the `amplify/backend` directory as a workspace, however I would like to note the caveat of installing function dependencies with shared workspace packages in Lambda Functions as it will cause issues if it installs with symlinks. Despite the caveat, this is a reasonable strategy and I will mark this as a bug for the team to evaluate further 🙂

**Comment by acusti** [comment]
@josefaidt `amplify push` doesn’t work with or without the `amplify/backend` directory as a workspace, i just documented my configuration for thoroughness

**Comment by acusti** [comment]
as a quick update, i just realized that my REST API cognito user pool authorizer override is now broken and all of my REST API routes are now returning `401` errors. i’m trying to build a version of the CLI locally that fixes the issue so i can run `amplify push` and fix my API, but if that is the consequence of this error (and not the consequence of something else that happened while i tried to make this work), it seems pretty severe.

**Comment by acusti** [comment]
i built a version of the amplify CLI locally that works and let me fix my REST API custom authorizer 😅

this version of `getLockFileContent` works in a repo that uses yarn workspaces:

```ts
  private getLockFileContent = (projectRoot: string): string => {
    let lockFileFullPath = path.join(projectRoot, this.packageManager.lockFile);
    let lockFileFullPathDir = path.parse(lockFileFullPath).dir;
    while (!fs.existsSync(lockFileFullPath) && lockFileFullPathDir.length > 1) {
      lockFileFullPath = path.resolve(lockFileFullPathDir, '../', this.packageManager.lockFile);
      lockFileFullPathDir = path.parse(lockFileFullPath).dir;
    }
    if (!fs.existsSync(lockFileFullPath)) {
      throw new AmplifyFault('LockFileNotFoundFault', {
        message: `Lockfile not found at location: ${lockFileFullPath}`,
      });
    }
    return fs.readFileSync(lockFileFullPath, 'utf-8');
  };
```
