### ISSUE TITLE
How to use specific method with REST API resource?

### ISSUE THREAD

**Issue by HumbleBeck** [aws-amplify/amplify-cli#1232]
** Which Category is your question related to? **
AWS Amplify REST API

** What AWS Services are you utilizing? **
AWS API Gateway, Lambda 

** Provide additional details e.g. code snippets **
Hello, my question contains 2 parts since they are related:
- how can I limit my api resource to specific method only? Its not possible to choose GET only or GET & POST, resource always created with all method.
- how can I use API Gateway parameter validation with amplify?

**Comment by elorzafe** [comment]
@HumbleBeck 
> how can I limit my api resource to specific method only? Its not possible to choose GET only or GET & POST, resource always created with all method. 
currently api can be configured with CRUD operations.
CREATE: POST
READ: GET
UPDATE: PUT, PATCH
DELETE: DELETE
those are the available options right now.

> how can I use API Gateway parameter validation with amplify?
In case you want to configure which query strings params or headers are allow, you need to edit those manually on the console. 

We can mark this as feature requests

**Comment by kaustavghosh06** [comment]
@HumbleBeck Alternatively, to unblock yourself now, you could edit the Cloudformation file in your `amplify/backend/api/<resource-name>/` directory for this feature.

**Comment by HumbleBeck** [comment]
@elorzafe as far I understand you talking about configuring it on express level which will trigger lambda everytime, instead it would be nice to put this responsibility on API Gateway which will lower response time & cost, correct me if I'm wrong.

@kaustavghosh06 Thanks, I did in this way, but whenever you adding new resource via `amplify api update`, all your previous changes will be overwritten.

**Comment by kaustavghosh06** [comment]
@HumbleBeck Yes, until we have in-built support for this in the CLI, you would have to manually manage the Cloudformation generated by the CLI for adding these fields.

**Comment by glynjackson** [comment]
Was this feature ever added? in 2021 there still does not appear to be a way to define a Rest API method.

**Comment by kaustavghosh06** [comment]
@Keydose We've fixed the issue tied to the "Maximum policy size 10240 bytes" - if you're using the latest version of the CLI. 
We're actively working on the overwriting of the CloudFormation file issue as well.
