### ISSUE TITLE
AWS SSO: Failed to get profile credentials

### ISSUE THREAD

**Issue by adcanis** [aws-amplify/amplify-cli#12330]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19.6.0

### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes made

### Describe the bug

[#12174](https://github.com/aws-amplify/amplify-cli/issues/12174) still persisting. This appears to be happening after the account exceeds the 8hr expiration. Attempts to re-login return 1 of 2 errors.

> Failed to get profile credentials. Unexpected token A in JSON at position 0

This error is on `amplify init`

> There was an error pulling the backend environment dev. The provided token has expired.

This is every time an amplify command is ran after `aws sso login --profile <profile>` to re-login. 

Following [#7361](https://github.com/aws/aws-cli/issues/7361) clearing the cookies on the start page, emptying `.aws/sso/cache` does not work. This is currently effecting 9 accounts

### Expected behavior

re-login should refresh token and commands should work

### Reproduction steps

1. from [this doc](https://docs.aws.amazon.com/singlesignon/latest/userguide/get-started-enable-identity-center.html), enable IAM identity center and create an org
2. add an account under "Multi-account permissions" > "AWS Accounts"
3. create a permissions set
4. create a group with permission set
5. create a user (e.g. "adcanis"), assign to group
6. grant access to the account added in step 2
7. log in using the "start url" (e.g. https://xxxxxx.awsapps.com/start)
8. following the instructions in `Command line or programmatic access` found on the "start url" using `aws configure sso` and following "option 2" to add credentials to `.aws/credentials`
9.  run `aws sso login --profile <profile name>`
10. initialize a new amplify project with `amplify init`
11. observe first error 

12. if session has expired, re-login via `aws sso login --profile <profile name>`
13. run `amplify push -y` for example and observe second error 

### Project Identifier

2274433f-fcef-4f58-baf3-6ebb90e99a30

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @adcanis thanks for raising this and apologies for the confusion! As mentioned in https://github.com/aws-amplify/amplify-cli/issues/12174 the fix is pending-release. I'll mark this as a duplicate and close in favor of tracking the existing item, but will update #12174 once this is released
