### ISSUE TITLE
Support detecting changes in auto-generated stacks in build or add `amplify push --force` command? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1235]
**Describe the bug**
It seems in some cases amplify does not detect changes when the generated cloud formation template or stacks in the GraphQL API build directory are changed. 

In such a case, I need a `--force` command to force a deployment. 

**To Reproduce**
1. Open a `<model>.json` in `amplify/backend/api/<your_api>/build/stacks/<model>.json`
2. Change `DataSourceName` for one of the resolvers to some other data source like another model's data source
3. Run `amplify status`
4. You'll see that no changes are detected

**Expected behavior**
Amplify status should detect changes when I change the generated build stacks. I am modifying the build stacks through a script I created to handle a case that is not supported through the new nested stacks design (changing the data source of an existing resolver without rewriting the whole model stack). 

**Additional context**
Running cli 1.5

**Comment by hisham** [comment]
Interestingly, if I do any little change to a file under `stacks/` it will want to update, but any change under `build/stacks` does not to do anything.

**Comment by kaustavghosh06** [comment]
@hisham The Transformer manages the build/ directory (and we do put this directory in the gitignore file and also exclude it from calculate the diff for an update) and we do not expect users to modify the same. 
If you want to modify a resolver generated by the transformer, I would highly encourage using custom resolvers instead.

**Comment by hisham** [comment]
Hi @kaustavghosh06 - I understand. Custom resolvers at this point however do not work well for some specific use cases, such as: 

1) Having multiple models that implement an interface and therefore connect to one data table (data source) instead of one table per model. See https://github.com/aws-amplify/amplify-cli/issues/202 and https://github.com/aws-amplify/amplify-cli/issues/1037. 

2) Connecting to dynamodb tables in a region that's different than the default appsync region. 

In these cases writing custom resolver stacks is too cumbersome and instead having scripts that are run before amplify push to modify the stacks in the build dir is a nicer hack. 

The custom resolver option is nice when you actually want to modify the default resolver code, but if you want to keep the default resolver code but change the data source, if you want to do that in the current "recommended" way, it means abandoning all the beautiful stacks the graphql transformer has generated and duplicating them with your own stacks, essentially abandoning the graphql transformer features. 

The other option is to implement a custom transformer but this would involve forking this repo and keeping it current which would be too cumbersome (see comment at https://github.com/aws-amplify/amplify-cli/issues/348#issuecomment-449447590). The BYOTransformer RFC however would make this easier (https://github.com/aws-amplify/amplify-cli/issues/1060). 

So until this happens I'm wrapping `amplify push` in my own custom script where other scripts are called before it to tweak the built stacks for my own needs. I am still using custom resolver functionality but only in cases where it makes sense like overriding the actual resolver code. You currently provide no convenient option to override the data source a generated default resolver connects to.

**Comment by kaustavghosh06** [comment]
@hisham With the latest version of the CLI (4.16.1) - we've released functionality for `amplify push --force` . Please let us know if this takes care of your request.

**Comment by kigorw** [comment]
@kaustavghosh06  on version 4.17.2 `amplify push --force` still asks for confirmation.

**Comment by kaustavghosh06** [comment]
Yes, amplify push --force will ask you for confirmation. If you want to avoid the confirmations use the --yes  parameter.
