### ISSUE TITLE
Should *-cloudformation-template.json files be git ignored?

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1237]
** Which Category is your question related to? **
Multi Team environments.

** What AWS Services are you utilizing? **
amplify env checkout branch
amplify publish

** Provide additional details e.g. code snippets **
Whenever amplify publish is called the *-cloudformation-template.json are updated. Should those be in version control? Thanks.

**Comment by kaustavghosh06** [comment]
@jarrettj Which cloudformation file specifically are you referring to?

**Comment by jarrettj** [comment]
These seem to be generated after running an amplify publish in all of my function directories.

**Comment by jarrettj** [comment]
These need to be added to git.

**Comment by kingarawana** [comment]
@jarrettj ever time i switch environments, the file is regenerated, which when i commit, would keep changing back and forth. Is this the intended outcome?
