### ISSUE TITLE
Support for custom GraphQL queries in the generated API

### ISSUE THREAD

**Issue by brunostuani** [aws-amplify/amplify-cli#1238]
**Is your feature request related to a problem? Please describe.**
One of the purposes of using GraphQL in your application is that you can query for specific fields in your API result. Out of the box Amplify works great, you define your schema and it generates all resolvers that connects to your database. It generates LIST and GET queries for every model, then it generates statements and types for those queries and wraps them into, my use-case, an Angular service. The problem comes when I want to have custom GQL queries that calls existing functions but just limits which fields are returned. If I have to do it, I have to construct this query myself and fetch the data, having no generated types for the result, and manually extending the generated API.

**Describe the solution you'd like**
The solution would be to allow custom queries -without resolvers-, generate types for them and moving them into the generated API.

**Describe alternatives you've considered**
Using type generation utilities to compile an external GraphQL file, and generating a new API extending the already generated one with the new function calls.

**Additional context**
n/a

**Comment by yuth** [comment]
@brunostuani codegen generated statements are meant to be used as a starting point and not exclusively in your project. We do support and encourage users to add/customize the statements as that is one of the main advantage GraphQL has over traditional rest APIs. If you add additional statements in a different file inside the statement folder, codegen generates types for those too.

Please feel free to comment if you have trouble adding custom statenents

**Comment by brunostuani** [comment]
Ah this is exactly what I was looking for. Maybe this is just not very discoverable.

Thanks!

**Comment by harryvu** [comment]
I have exactly same problem, I am struggling with custom queries like brunostuani. But I am not sure I understand the answer here. Says I have a very simple model below: 

type Note @model {
  id: ID!
  clientId: ID
  name: String!
  description: String
  completed: Boolean
  createdDate: DateTime
}

amplify generated the getNote, listNotes... in the queries.js under the src/graphql folder (the code fragment) below:

export const getNote = /* GraphQL */ `
  query GetNote($id: ID!) {
    getNote(id: $id) {
      id
      clientId
      name
      description
      completed
     createdDate
    }
  }
`;
...

but I'd like to add getSimpleNote in the simple-queries.js in the same folder:

export const getSimpleNote = /* GraphQL */ `
  query GetSimpleNote($id: ID!) {
    getSimpleNote(id: $id) {
      id
      clientId
      name
    }
  }
`;

then ran the amplify api gql-compile, but it never generate the custom queries I added above. What am I missing? Thank you.

**Comment by sudeep-quantelai** [comment]
> @brunostuani codegen generated statements are meant to be used as a starting point and not exclusively in your project. We do support and encourage users to add/customize the statements as that is one of the main advantage GraphQL has over traditional rest APIs. If you add additional statements in a different file inside the statement folder, codegen generates types for those too.
> 
> Please feel free to comment if you have trouble adding custom statenents

@yuth "queries.js" does not generate queries that are nested more than 2 levels deep (i.e if Model A -> Model B -> C the generated code only has elements from ModelA and Model B). I am pretty sure I have selected a value of 4 in the nested queries when setting up the API without understanding what it did at that time and I am assuming that is used here? If so, why are the elements for table C not being generated in the nested query. Any way I can check the value of nesting I have chosen just to be sure?

**Comment by Sourabh7749** [comment]
I am trying to Run a Simple Query to get Doctor details by userId. I checked for the documentation but was not able to find a way for defining a custom query. 

  query getDoctorsbyuserID($userId: String!) {
    getDoctorsbyuserID(userId: $userId) {
      id
      firstName
      lastName
      userId
    }
  }

The queries which are auto generated are working fine but not able to find a way to make custom query work. 


What are steps of writing custom queries in Amplify Graphql? Any document/blog ?

Frontend - Reactjs

P.S : I am new to Amplify.
