### ISSUE TITLE
No OTP during user registration

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-cli#124]
**Describe the bug**
Trying to follow Ed Lima's tutorial: https://medium.com/open-graphql/create-a-multiuser-graphql-crud-l-app-in-10-minutes-with-the-new-aws-amplify-cli-and-in-a-few-73aef3d49545

I get the app running with amplify serve, but when I goto register a user, I do not get an OTP on my phone. When I hit 'Resend code' there is no alert telling me that a code has been resent.

**Expected behavior**
Obtain OTP on phone.

**Comment by kaustavghosh06** [comment]
The default behavior is to obtain the code in your email. @haverchuck Could you confirm please?

**Comment by swaminator** [comment]
I checked my email as well and didn't get anything. Also, when I click on 'resend notification', there is no alert that the resend has happened.

**Comment by kaustavghosh06** [comment]
Talked to @swaminator. For some reason, the email was in the spam folder of his corporate email account.
