### ISSUE TITLE
Resource cannot be removed because it has a dependency on another resource.

### ISSUE THREAD

**Issue by charlieforward9** [aws-amplify/amplify-cli#12400]
### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deleted all the resources with name containing AdminQueries using AWS Resource Explorer.

### Describe the bug

I am trying to reset my authentication rules, specifically, just removing the required attributes when a user creates an account. When I try to `reset all auth settings and users` in Amplify Studio, deployment fails with the message 
> Resource cannot be removed because it has a dependency on another resource. Dependency: API Gateway - AdminQueries.

I used AWS Resource Explorer to remove all resources with AdminQueries in the name, but the error persists. I have also tried running it on the CLI, same issue.

### Expected behavior

I expect to reset my backend when I click the reset button, and have Amplify a) Remove all the dependencies automatically or b) Have a dependency manager within amplify studio that makes it simple to manage what to do with the dependencies (or docs to guide us on what to do). 

Alternatively, I would like to be able to adjust the attributes required from the user without having to reset my entire authentication configuration.

### Reproduction steps

![Screen Shot 2023-03-31 at 2 50 24 AM](https://user-images.githubusercontent.com/62311337/230464368-d9e8c1ef-3839-488f-9499-5e429d68c1d4.png)

Create an config like this. Then try to delete it.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @charlieforward9, thank you for reaching out. wanted to clarify some information.

> I have also tried running it on the CLI, same issue.

did you remove the AdminQueries api by running the following?
1. `amplify remove api`
2. select `AdminQueries (REST API)`
3. then `amplify remove auth` to remove Cognito user pool
4. then `amplify add auth` to add the Cognito user pool

As the auth recource depends on Admin Queries API, we will need to first remove the Admin Queries API then remove the auth resource as required.

**Comment by charlieforward9** [comment]
That solved my problem, I appreciate the rapid response. Thanks!
