### ISSUE TITLE
How to handle configuration of AWS service?

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1241]
** Which Category is your question related to? **
amplify api add
** What AWS Services are you utilizing? **
API Gateway
** Provide additional details e.g. code snippets **
What is the workflow for things that amplify does not currently have an option to configure.
A basic and probably popular example of this is CORS. I'm sure everybody would come across this issue sometime or another. 

What tools do you suggest one use? If I would like to keep the configuration within my project. Thanks.

Regards.

**Comment by kaustavghosh06** [comment]
@jarrettj You could probably modify the CFN file located in `amplify/backend/<category>/<resource-name>`.  What do you think about that?

**Comment by jarrettj** [comment]
Does that file not get overwritten?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jarrettj** [comment]
Never mind. I see what's needed. Found the CF templates in each features folder.  :)
