### ISSUE TITLE
Error code: InvalidParameterException - Message: "client_id, client_secret and authorize_scopes are all required idp details."

### ISSUE THREAD

**Issue by fmarmo90** [aws-amplify/amplify-cli#12417]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

11.0.3

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I started working on a new Amplify project that was created some time ago.

This project has enabled authentication with Facebook and Gmail.

After doing all the configuration stuff for the CLI to work, I executed the following command: `amplify pull --appId xxx --envName testing`.

After that, for some reason when I executed `amplify status`, I saw this:

![image](https://user-images.githubusercontent.com/7611591/230739264-0dd583d0-2350-43df-a1d1-fc1efcbcd388.png)

Amplify says that I've updated something but I haven't. I only did a pull, nothing more.

So, after that I tried to do `amplify push` because I hadn't made any changes to the project and I received the following error:

![image](https://user-images.githubusercontent.com/7611591/230739357-cb794ca7-c7e4-4c18-b17c-8fa7b9b7303c.png)

And when I went to the Cloudwatch logs I saw this message:

` 
"message": "client_id, client_secret and authorize_scopes are all required idp details.",
 "code": "InvalidParameterException",
`

Could this be a CLI version compatibility problem? I mean, maybe the project was created with an old version and I'm now using a higher one.

Thank you in advance!

### Expected behavior

I expected this to work well because I haven't made any manual changes to the project.

### Reproduction steps

I've created a new project from scratch, added Facebook authentication, then pushed it to my personal account.

After that, I pull it from the Aws Console into a new empty folder, make some changes and push it again and everything works as expected.

Unfortunately, I wasn't be able to replicate the error.

### Project Identifier

Project Identifier: 36b7c0bb9754be37a94da8ce180b5508

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @fmarmo90 it is recommended to migrate your auth resource in a non-production environment prior to migrating production, however this will primarily change how the resource is defined in your backend directory. For example, `parameters.json` will become `cli-inputs.json` and the CloudFormation template will be generated on `amplify build` and stored in a gitignored `build/` directory

**Comment by fmarmo90** [comment]
Hey @josefaidt, thank you so much for your help and the information! I was able to solve the problem using the amplify update auth!
