### ISSUE TITLE
Custom query  - How to pass aditional variables to *.req.vtl for composite primary key

### ISSUE THREAD

**Issue by timkuilman** [aws-amplify/amplify-cli#1242]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
GraphQL api

** What AWS Services are you utilizing? **
Appsync

** Provide additional details e.g. code snippets **

For the app I am currently working on I would like to change a query so that I can use a composite primary key.  I think I am almost there but  I can not figure out the last part. There is no documentation yet for this use case which is pretty common I think. Since I could not find any previous issues I try to follow my gut. 

Anyone here who can help me out? :)

Thanks in advance! 

Tim

### Schema.graphql 

```
type User @model {
  id: ID!
  name: String!
  questionAnswers: [Answer] @connection(name: "UserAnswers", keyField: "userId", sortField: "mySortField")
}

type Answer @model(queries: null) {
  id: ID!
  user: User! @connection(name: "UserAnswers", keyField: "userId", sortField: "mySortField")
  mySortField: String!
  userId: ID!
}

```

### Custom resolver (User.questionAnswer.req.vtl)
_Stored in the 'resolver' directory for custom resolvers._

I seeded my database with dummy data. When I replace $context.args.mySortKeyValue with a hardcoded value the resolver seems to work as expected. 

``` 
{
  "version": "2017-02-28",
  "operation": "Query",
  "query": {
      "expression": "#connectionAttribute = :connectionAttribute and #connectionAttributeSortKey = :connectionAttributeSortKey",
      "expressionNames": {
          "#connectionAttribute": "userId",
          "#connectionAttributeSortKey": "mySortField"
    },
      "expressionValues": {
          ":connectionAttribute": {
              "S": "$context.source.id"
      },
          ":connectionAttributeSortKey": {
              "S": "$context.args.mySortFieldValue"
      }
    }
  },
  "scanIndexForward":   #if( $context.args.sortDirection )
    #if( $context.args.sortDirection == "ASC" )
true
    #else
false
    #end
  #else
true
  #end,
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit":  #if( $context.args.limit )
"$context.args.limit"
  #else
null
  #end,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end,
  "index": "gsi-UserAnswers"
}
```

### I am using this custom query. 

 I expect that I need to add $myCustomValue somewhere 

```
      const userQuery = await API.graphql(
        graphqlOperation(
          `query GetUser($id: ID!, $mySortFieldValue: String! ) {
            getUser(id: $id) {
              id
              name
              questionAnswers(mySortFieldValue: $mySortFieldValue ) {
                items {
                  id
                }
                nextToken
              }
            }
          }`,
          {
            id: '37373329-722c-479e-83e3-bffd7c9614a0',
            mySortFieldValue: 'some-value'
          }
        )
      ).catch(e => console.log('Error ->', e));
```

**Comment by regenrek** [comment]
Whats your current output or error you get?

**Comment by timkuilman** [comment]
`"Validation error of type UnknownArgument: Unknown field argument mySortFieldValue @ 'getUser/questionAnswers'"`

**Comment by mikeparisstuff** [comment]
@timkuilman That error is coming from GraphQL and is complaining because your query is not validating against the schemas type system. The `User.questionAnswers` field does not take a top level argument with the name `mySortFieldValue`. You either need to update the definition of the field in your schema or change how you are calling the field (e.g. by default use `filter: { mySortFieldvalue: { eq: $mySortFieldValue } }`)

**Comment by timkuilman** [comment]
If I use filter I would not really be using the composite primary key right? It would filter the query result before returning that result to the app instead of only selecting the items based on the primary key. 

After reading your comment I changed my `type User` which includes the questionAnswers field to the following:

``` type User @model {
  id: ID!
  name: String!
  questionAnswers (mySortFieldValue: String): [Answer] @connection(name: "UserAnswers", keyField: "userId", sortField: "mySortField")
}
``` 

This is probably not how I am supposed to do change it since the error remains the same. Can you explain to me how I can change the schema correctly or perhaps send me a link to some documentation?

Thanks!

**Comment by timkuilman** [comment]
@mikeparisstuff I haven't figured this out yet. How can I get this to work? 

Thanks!

**Comment by mikeparisstuff** [comment]
With this schema: 

```graphql
type User @model {
  id: ID!
  name: String!
  questionAnswers: [Answer] @connection(name: "UserAnswers", keyField: "userId", sortField: "mySortField")
}

type Answer @model(queries: null) {
  id: ID!
  user: User! @connection(name: "UserAnswers", keyField: "userId", sortField: "mySortField")
  mySortField: String!
  userId: ID!
}
```

You can run this query:

```graphql
query {
  getUser(id: "1") {
    questionAnswers(mySortField: { eq: "123" }) {
      items {
        mySortField userId
      }
    }
  }
}
```

I recommend using the documentation pane of GraphiQL in the AppSync console's query page or any other open-source GraphiQL implementation in order to get familiar with your schema. Once it is deployed you can step through the shape of your API as well as get auto-complete and query linting/validation with helpful error messages that will help you answer questions like this in seconds.
