### ISSUE TITLE
"aws amplify add" bombs on macOS with quote problem if editor is emacs

### ISSUE THREAD

**Issue by shentonfreude** [aws-amplify/amplify-cli#1246]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
In the AWS Unicorn Trivia Workshop I spec'd Emacs as my editor when doing amplify init. When I later did amplify api add, and told it to let me edit the schema, it bombed with a quote issue:
```
$ amplify api add
? Please select from one of the below mentioned services GraphQL
? Provide API name: adminpanel
? Choose an authorization type for the API API key
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? Yes
? What best describes your project: Single object with fields (e.g., “Todo” with
 ID, name, description)
? Do you want to edit the schema now? Yes
Please edit the file in your editor: /Users/chris/Projects/training/nab2019-aws-workshop/amplify/backend/api/adminpanel/schema.graphql
? Press enter to continue
/Users/chris/.nvm/versions/node/v11.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: osascript -e 'tell application "Terminal" to do script "cd /Users/chris/Projects/training/nab2019-aws-workshop/aws-amplify-unicorntrivia-workshop-master; emacs --no-splash \"+1:1\" \"/Users/chris/Projects/training/nab2019-aws-workshop/amplify/backend/api/adminpanel/schema.graphql"'\"
266:268: syntax error: A “"” can’t go after this “"”. (-2740)

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:193:13)
    at ChildProcess.EventEmitter.emit (domain.js:481:20)
    at maybeClose (internal/child_process.js:1001:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
```

Looks like the final quotes are mixed up, as the following (manually entered) works:
```
...schema.graphql\""'
```
**To Reproduce**
1. Go to the unicorn trivia project
2. Enter: amplify api add
3. Specify Yes to editing the GraphQL schema
4. See error when it tries to tell macOS to launch Emacs with the sample schema file

**Expected behavior**
It should have launched Emacs in a terminal to edit the sample schema file.

**Screenshots**
Pasted terminal output above.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: none, I am in iTerm2
 - Version : n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: 
 - Browser
 - Version 

**Additional context**
The AWS engineers at the workshop suggested I create this ticket (and said very nice things about you all :-)

**Comment by kaustavghosh06** [comment]
@shentonfreude We've seen this issue with "Emacs" specifically. Let me try to find the root-cause for this as we're utilizing a third party lib for this functionality - https://www.npmjs.com/package/open-in-editor and I might've to open up an issue with them after investigating.

**Comment by mitsuyoshi4** [comment]
I've encounted same bug.

**Desktop information:**
* MacOS High Sierra / verison: 10.13.6
* Terminal: Mac's default terminal / version: 2.8.2 (404)
* Editor: Emacs 26.1

we should fix third party library 'open-in-editor' as below.
In lib/open.js
```
diff --git a/lib/open.js b/lib/open.js
index 4d08053..50df999 100644
--- a/lib/open.js
+++ b/lib/open.js
@@ -33,7 +33,7 @@ function makeArguments(filename, settings) {
     //   {filename}:1:2
     //   => "filename:1:2"
     //
-    .replace(/\{filename\}(\S*)/, function(m, rest) {
+    .replace(/\{filename\}(\w*)/, function(m, rest) {
       return quote(info.filename + rest, settings.escapeQuotes);
     });
 }
```

**Comment by kaustavghosh06** [comment]
@mitsuyoshi4 Thanks for the PR to the open-in-editor repo for this issue! Much appreciated.

**Comment by attilah** [comment]
Already fixed because dependency is changes in a recent PR.
