### ISSUE TITLE
amplify deploy on us-west-2 and faux region limits

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#12474]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.20.1

### Amplify CLI Version

11.0.4

### What operating system are you using?

ubuntu 22.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Amplify deploy to regular account, profile and region that I have been using a few years.  Currently hosting ~11 apps.  Deploy fails with message "You have reached the Amplify App limit for this account and region" even though service quota limit is 40.  If I destroy one app and try to redeploy the new one, same error.

---

Resolution: Use a different account or region with fewer apps, or request a service limit increase: https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 5eff38af-4289-4ef9-86d6-badabf04b957

### Expected behavior

Successful deployment

### Reproduction steps

amplify init (of next.js 13.3 app)
---
? Enter a name for the project bhaiv5foo
The following configuration will be applied:

Project information
| Name: bhaiv5foo
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm run-script build
| Start Command: npm run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

fooregularprofile

### Project Identifier

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
⠋ Creating Zip
No Amplify backend project files detected within this folder.
✖ Creating Zip

### Log output

<details>

```
# Put your logs below this line
~/.amplify/logs/amplify-cli-<issue-date>.log
bash: issue-date: No such file or directory

```

</details>

### Additional information

No problem deploying to us-west-1 but I want to keep stacks in one region

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by weisisheng** [comment]
Just tried with amplify cli version 11.0.5 and same result

**Comment by weisisheng** [comment]
Oddly my limit was bumped up, maybe ~75 and I can now build/deploy from the console on us-west-2.  Will try with cli and report back again soon.

And now I get a similar error on us-west-1 with less than 15 apps.  Bizarre

**Comment by josefaidt** [comment]
Hey @weisisheng what is your account ID?

**Comment by josefaidt** [comment]
Hey @weisisheng are you still experiencing this?

**Comment by artidataio** [comment]
When I run `amplify init` command on the latest `amplify-cli 12.0.3` on a fresh new folder without any frontend setup. I received the same error message :

> You have reached the Amplify App limit for this account and region

In the amplify console I only have 6 apps, while the limit is 25. Please advise.

**Comment by josefaidt** [comment]
Hey @artidataio in order to further troubleshoot your issue, please reach out to the AWS Support team: https://aws.amazon.com/support for additional assistance.
