### ISSUE TITLE
Failed to receive expected authentication tokens. Error: [Error: 'jsonString' argument missing or empty]

### ISSUE THREAD

**Issue by Syphini** [aws-amplify/amplify-cli#12473]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.17.0

### Amplify CLI Version

11.0.5

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I used Amplify studio to create a new backend environment for my existing Amplify app.
I then cloned the environment in the hosting console in order to create an environment with the name 'dev' before deleting the previous one.
Afterwards I attempted to pull the new environment to my local project using `amplify pull --appId xxx --envName dev` 
The CLI opened a new window to prompt me for my AWS credentials, and upon supplying them and allowing access, the following error appeared

![image](https://user-images.githubusercontent.com/44600408/232367150-7154d276-2bef-4d42-a26a-2e5c613a3e72.png)

The error appears after every subsequent attempt I've tried
I have re-cloned my repo and attempted to pull again with no change

### Expected behavior

Successfully pulling backend environment to local project

### Reproduction steps

The following steps were what I used, taking into account my repo was freshly cloned and my hosting app was new as well.

git clone project from repo
create amplify backend in hosting
clone amplify backend in hosting
pull new backend to CLI
attempt to login with Amplify Studio credentials

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
hey @Syphini thank you for reaching out. wanted to get some additional information on the reproduction steps and behaviour.
are you cloning a project from Github repository that contains a Amplify folder? if yes, are you running `amplify init` after cloning the project? 
Does the project contain `team-provider-info.json` present in the amplify folder ?

**Comment by Syphini** [comment]
Hey @ykethan,
The project previously did not contain an Amplify folder or an associated backend.
I had set up a new Amplify hosting instance connected to the Github repo, and then attempted to create a backend on the Amplify hosting side and pull that backend to my project locally for the first time, so no Amplify files were set up locally yet

**Comment by ykethan** [comment]
hey @Syphini, after the failed pull attempt. By any chance do you observe any `amplify-backup` or `amplify` folder added to the project. If yes, could you remove the folders and then retry the headless pull command at the root of your project. The Amplify CLI should open a tab in you browser to prompt for access.

**Comment by Syphini** [comment]
@ykethan when I pull the `amplify` and `amplify\backend` folders are generated with nothing inside before prompting me to login. When deleting them and trying again, the same issue happens.
The folders are generated, I'm prompted for login, the error message shows up in CLI when I try to login on the browser tab.

**Comment by jhockett** [comment]
Hey @Syphini, did you add any resources in Studio? If so, what types?

Can you please try pulling again with an additional `--debug` flag and share the output?

**Comment by ykethan** [comment]
@Syphini in addition to the question above. could you also let us know the type of terminal and browser being used.

**Comment by Syphini** [comment]
@jhockett no resources were added, I've only created an initial backend using Amplify Studio on web, and then cloned it immediately with a new name and deleted the original "staging" environment. 
I just tried re-creating a new Amplify Hosting app to see if it was app specific, but seems like the issue still occurs.

The debug flag outputs as follows:
```
C:\path\to\file>amplify pull --appId dnpdxhcmd0pus --envName dev --debug
Opening link: https://ap-southeast-2.admin.amplifyapp.com/admin/dnpdxhcmd0pus/dev/verify/?loginVersion=1
⠙ Confirm login in the browser or manually paste in your CLI login key:
🛑 Failed to receive expected authentication tokens. Error: [Error: 'jsonString' argument missing or empty]

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

AmplifyStudioLoginError: Failed to receive expected authentication tokens. Error: [Error: 'jsonString' argument missing or empty]
    at C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\utils\admin-login-server.js:142:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

'jsonString' argument missing or empty
Error: 'jsonString' argument missing or empty
    at Function.parse (C:\snapshot\repo\build\node_modules\amplify-cli-core\lib\jsonUtilities.js:82:15)
    at Function.readJson (C:\snapshot\repo\build\node_modules\amplify-cli-core\lib\jsonUtilities.js:51:32)
    at StateManager.setAmplifyAdminConfigEntry (C:\snapshot\repo\build\node_modules\amplify-cli-core\lib\state-manager\stateManager.js:183:63)
    at AdminLoginServer.storeTokens (C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\utils\admin-login-server.js:191:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\snapshot\repo\build\node_modules\@aws-amplify\amplify-provider-awscloudformation\lib\utils\admin-login-server.js:137:9

Session Identifier: 4170b0ad-e9ff-47b0-84ba-a847ccd5e270                                                                                      ⠹ Confirm login in the browser or manually paste in your CLI⠴ Confirm login in the browser or manually paste in your CLI login key:
√ An unexpected error has occurred, opt in to send an error report to AWS Amplify with non-sensitive project configuration files. Confirm  (y/N) · yes

Learn more at https://docs.amplify.aws/cli/reference/diagnose/

This project has been opted in automatically to share non-sensitive project configuration files. you can opt out by running 'amplify diagnose --auto-send-off'
- Creating Zip
File at path: 'C:\path\to\file\amplify\backend\backend-config.json' does not exist
× Creating Zip

C:\path\to\file>
```

@ykethan the browser is Google Chrome on the latest version, and the terminal is the Windows 10 CMD prompt, I've run the  terminal both normally and through Visual Studio code with no differences

**Comment by jhockett** [comment]
Hi @Syphini, thank you for the information! I was able to reproduce the issue by deleting the contents of `<home-dir>/.amplify/config.json`.

Note, the content of `<home-dir>/.amplify/config.json` is where we store JWTs to vend temporary AWS credentials, so it should NOT be shared.

Can you try deleting that file and retrying the login?

**Comment by Syphini** [comment]
@jhockett Thanks very much, that seems to have solved it! Just tried another pull and there was no issues.
I will mention however the file was in `<home-dir>/.amplify/admin/config.json` for me and was completely blank

**Comment by ykethan** [comment]
Glad to hear you are back up and running. Closing the issue, please feel free in reaching out to us again.
