### ISSUE TITLE
amplify add auth: Mandatory 'requiredAttributes' when using CLI + 'sign-up and sign-in with email or phone number'

### ISSUE THREAD

**Issue by Soek22** [aws-amplify/amplify-cli#1247]
CREATE_FAILED  [/Resources/**UserPool**/Type/Schema] 'null' values are not allowed in templates (forcing me to select at least one option for required attributes on sign-up)

**Describe the bug**
I can't add auth service with manual configuration without selecting required attributes. When creating user pools on the web console it is possible not setting mandatory fields for sign-up.

**To Reproduce**
1. amplify add auth service
2. ... configurations ...
3.  How do you want users to be able to sign in when using your Cognito User Pool?
 **Email and Phone Number**
4. ... configurations ...
5. What attributes are required for signing up?
**No attributes mandatory, no attributes selected**
6. amplify push
7. See error:
CREATE_FAILED serviceName AWS::CloudFormation::Stack datetime [/Resources/UserPool/Type/Schema] 'null' values are not allowed in templates
An error occurred when pushing the resources to the cloud
Resource is not in the state stackUpdateComplete

**Expected behavior**
I am allowing users to choose between mail/phone on signup to be their username alias unique identifier. If someone chooses to register using phone, I don't want to force them to use mail, and viceversa. I don't want them neither to introduce any other attribute as mandatory.
This configuration is feasible using the web console when creating user pools, but not accepted when using the CLI. 
There is a problem as the  gets "null" value when not selecting any attribute as required.

**Screenshots**
Expected outcome screenshot, not reachable through CLI (only web console).
![Screenshot1](https://user-images.githubusercontent.com/2856396/55922149-375b5a80-5c00-11e9-9f53-503aaec52cbe.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - @aws-amplify/cli@1.6.1

**Additional context**
![Screenshot2](https://user-images.githubusercontent.com/2856396/55922152-3f1aff00-5c00-11e9-8ca6-fd6129803ec6.png)

From: [Configuring User Pool Attributes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html) > Using Aliases to Simplify User Sign-Up and Sign-In > Option 2: User Signs Up and Signs In with Email or Phone Number Instead of Username > To configure a user pool for sign-up and sign-in with email or phone number
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html

**Comment by Soek22** [comment]
Thank you in advance!

**Comment by kaustavghosh06** [comment]
@Soek22 We're looking it and there's going to be a PR out for it soon.

cc: @haverchuck
