### ISSUE TITLE
amplify add auth aborts after first selection

### ISSUE THREAD

**Issue by ashleydass** [aws-amplify/amplify-cli#1248]
** Which Category is your question related to? **
AWS Amplify Auth

** What AWS Services are you utilizing? **
CloudFormation, Lambda, Cognito

** Provide additional details e.g. code snippets **
So I managed to add hosting and published my basic react app to CloudFront, which works as expected. However, when I try to add Auth by running the amplify auth add or amplify add auth commands, it brings me to the first set of questions, like so:

**Do you want to use the default authentication and security configuration? (Use arrow keys)
 Default configuration
  Default configuration with Social Provider (Federation)
  Manual configuration
  I want to learn more.**

and when I select Default configuration it aborts any further steps and takes me back to the prompt.

![image](https://user-images.githubusercontent.com/12193609/55927888-ff810100-5c59-11e9-86b5-c7d8d3f59c00.png)

My package.json contains this:

```javascript
{
  "name": "amplify",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack && webpack-dev-server --mode development",
    "build": "webpack"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.29.6",
    "webpack-cli": "^3.1.0",
    "copy-webpack-plugin": "^4.5.2",
    "webpack-dev-server": "^3.1.5"
  },
  "dependencies": {
    "@aws-amplify/auth": "^1.2.22",
    "aws-amplify": "^1.1.26",
    "aws-amplify-react": "^2.3.5"
  }
}
```

Am I missing anything obvious here?

**Comment by kaustavghosh06** [comment]
@ashleydass Take a look at my screenshot below. I was able to install the latest CLI (v 1.6.1) on a windows workspace and use powershell to add auth using the CLI and I was successful in doing so.
![Screen Shot 2019-04-11 at 2 44 52 PM](https://user-images.githubusercontent.com/7247658/55995198-bbe1c380-5c68-11e9-961c-246ad2f6ba74.png)

I'm using node v 8.12 on my windows workspace. Which node version are you using?

**Comment by ashleydass** [comment]
@kaustavghosh06 thanks for your response. 

I was on node v10.10.0 on windows and had installed aws-amplify as a local package by following the [Get Started guide](https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs). 

But with your tip I got it working locally by following these steps:

1. Upgraded to the latest v11.14.0 of node js
2. Uninstalled aws-amplify local package
3. Installed @aws-amplify/cli globally
4. Followed by configure and init

Finally ```amplify add auth``` didn't abort itself after the first prompt and life is back to normalcy now.

Thanks a ton.

**Comment by AegonKevinTaylor** [comment]
Just ran into the same issue on Windows, node -v 10.5.0

**Comment by AegonKevinTaylor** [comment]
> Just ran into the same issue on Windows, node -v 10.5.0

Can also confirm that I had to upgrade node to latest version and start over to get it to stop crashing when I ran the add auth command.
