### ISSUE TITLE
adding a new env without region in team provider info creates a new app

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#12496]
### Amplify CLI Version

11.0.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

remove env from team-provider-info

### Describe the bug

while testing Amplify, i noticed that removing the` Region ` from team-provider-info.json, creates a new amplify app.
if we then remove the new env created, the backend is deleted but the application created on hosting stays.

also observed (dev and ds are env names)

![image](https://user-images.githubusercontent.com/87995712/232875740-1dca26f0-d3c9-4256-a7f7-8cdf66e93872.png)

### Expected behavior

maybe reprompt for region is missing

### Reproduction steps

1. amplify init -> dev
2. remove `region` from `team-provider-info.json`
3. amplify add env staging
4. observe the appId is different
5. checkout to dev
6. env remove staging
7. check hosting the app is still there without the backend resources.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Closing as a "wontfix" as this is not a supported workflow (manually editing TPI). This was found when attempting to reproduce https://github.com/aws-amplify/amplify-cli/issues/12493
