### ISSUE TITLE
Amplify env add fails with Cannot read property 'Region' of undefined

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-cli#12493]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.21.3

### Amplify CLI Version

11.0.5

### What operating system are you using?

Pop Os

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Trying to add a new environment fails with error message: Cannot read property 'Region' of undefined

### Expected behavior

New environment should be created.

### Reproduction steps

1. git checkout -b sandbox
2. amplify env add sandbox
3. Select authentication method (happens with both profile & access keys)
4. Receive the error

### Project Identifier

f59e77335650fce92677ec2970143a9b

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by parvusville** [comment]
Hey @josefaidt . Nothing new is generated when I try to run amplify add, so there is to artifact for `sandbox` in `team-provider-info`. Sandbox environment-name is not previously used.

**Comment by josefaidt** [comment]
Hey @parvusville thanks for clarifying. Can you post the stack trace output from running the command with `--debug`?

**Comment by josefaidt** [comment]
Additionally, can you check to see whether you have a `Region` specified in the awscloudformation block of your `amplify/backend/amplify-meta.json` file?
![image](https://user-images.githubusercontent.com/5033303/233188962-947daa38-99e5-44b4-99ea-87362f4a9c9c.png)

**Comment by parvusville** [comment]
Hey @josefaidt. I do have a `Region` specified in the `awscloudformation` block. 

Here is the stack trace:

```
UnknownFault: Cannot read property 'Region' of undefined
    at genericErrorToAmplifyException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:125:49)
    at handleException (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/amplify-exception-handler.js:26:28)
    at process.<anonymous> (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:48:93)
    at process.emit (events.js:400:28)
    at processEmit [as emit] (/snapshot/repo/build/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (internal/process/execution.js:167:25)

Cannot read property 'Region' of undefined
TypeError: Cannot read property 'Region' of undefined
    at init (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/amplify-service-manager.js:134:80)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/amplify-provider-awscloudformation/lib/initializer.js:130:9)

Session Identifier: fdc13775-639e-429e-8e0d-010079c89f4d
```

**Comment by josefaidt** [comment]
Hey @parvusville thanks for checking on that! From the stack trace it appears to be coming from this line https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-provider-awscloudformation/src/amplify-service-manager.ts#L79

After the failed `env add` attempt is there a stray `sandbox` block in your team-provider-info.json? if so, can you remove it and try again? 

Would you be open to hopping on a quick call to debug (I can ping you on Discord to set it up) or sending a zip archive of your `amplify/` directory to amplify-cli@amazon.com?

**Comment by parvusville** [comment]
@josefaidt There is no changes to my team-provider-info.json, or any other changes on git diff. Quick call to debug sounds good, I already pinged you on discord.

**Comment by josefaidt** [comment]
Hey @parvusville thanks for hopping on a call with me! To recap, we saw an extra environment in the `amplify/team-provider-info.json` file that was missing its `awscloudformation` block with metadata, causing this check for `<env-in-team-provider-info>.awscloudformation.Region` to fail when creating a new environment. This stray block looked something like

```json
{
	"someenvironment": {
		"categories": {
			"auth": {
				"myauthresource": {}
			}
		}
	}
}
```

After removing this block we were able to successfully create another environment with `amplify add env`.

I'm going to add the `investigating` label on this issue while I look into why this stray artifact was present and report back with my findings

**Comment by josefaidt** [comment]
Hey @parvusville coming back to this, I have not yet been able to reproduce an instance where we are left with a stray environment with only the auth category listed. I'm going to close this issue for the time being but if this resurfaces please let us know!
