### ISSUE TITLE
Function category - Changes to src files not detected properly

### ISSUE THREAD

**Issue by kavengagne** [aws-amplify/amplify-cli#125]
**Describe the bug**
Using the the function category, changes to the files under the **src** directory are not detected properly when trying to build or push.

**To Reproduce**
1. Add a function with ``` amplify function add ```.
2. Push the changes to AWS with ``` amplify push ```.
    >A Zip file is created under the **dist** directory and is uploaded to AWS.
3. Open the **app.js** file under the **src** directory for that function and make some changes to it.
4. Save the changes and then run ``` amplify push ```.
    >No zip file is generated and the same file as the previous time is pushed to AWS.

**Expected behavior**
- A new zip file should be generated every time a change is detected.
- The change detection should check that at least one file has changed under the **src** directory.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Browser: Chrome

**Additional context**
The buildResource function in ``` packages/amplify-provider-awscloudformation/lib/build-resources.js ``` compares the src folder's atime to the lastPackageTimeStamp to determine if the zip file should be built. However, this does not work since the folder's access time is not updated when one of its files changes.

I will submit a Pull Request to fix the issue.

**Comment by kaustavghosh06** [comment]
Fixed pushed with latest npm publish -> 0.1.18

**Comment by betimer** [comment]
This one now happens again on 4.29.4. Issue needs to be re-opened
