### ISSUE TITLE
"The bucket does not allow ACLs" on amplify publish

### ISSUE THREAD

**Issue by danielleadams** [aws-amplify/amplify-cli#12503]
### Amplify CLI Version

all CLI versions

### Description

The Amplify CLI team is aware of a permissions change that has been made in the Amazon S3 service that may cause issues running amplify publish if you have added hosting after April 1, 2023.

S3 has changed a default that sets the ObjectOwnership on new S3 buckets to BucketOwnerEnforced from ObjectWriter - this change disables Access Control Lists (ACLs) on items uploaded to the bucket.

https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

### Workaround

In order to fix this issue on your hosting bucket, enable ACL permissions through AWS Console. To do this, perform the following steps:

#### 1. Open your hosting bucket and navigate to Permissions

Go to the hosting bucket in AWS Console. Be sure to go to the hostingbucket, and not the amplify-app bucket.

![Screenshot 2023-04-19 at 1 26 19 PM](https://user-images.githubusercontent.com/6271256/233198914-c9ac1c58-8759-4457-8bda-4f9830ff482e.png)

#### 2. Scroll to Object Ownership and click “Edit”

![Screenshot 2023-04-19 at 1 26 58 PM](https://user-images.githubusercontent.com/6271256/233198782-f751fd30-d119-45fd-8179-3de9ff6445e3.png)

#### 3. Enable ACLs with Object Ownership set to “Object Writer”

Then, click “Save changes”.

![Screenshot 2023-04-19 at 1 27 13 PM](https://user-images.githubusercontent.com/6271256/233198823-3d3efd45-d6df-403f-a6b1-c519e5b3f22e.png)

#### 4. Retry amplify publish

Once you’ve saved the changes, retry the publish on the machine you are running amplify on.

__Note:__ If you are using `Dev` mode with just the S3 bucket, you will also have to turn off "Block _all_ Public Access" on your S3 Bucket in the Permissions settings too.

**Comment by jjrdevspace01** [comment]
also seeing this on brand new amplify project using cloudfront - need a solution that doesnt involve making changes directly in console

**Comment by electronicalias** [comment]
Also seeing this issue on a new project.
As per the CLI advise on running the amplify diagnose --send-report, here is the identifier:
dc856d0b693a6f393f42b9188e3957ec

**Comment by electronicalias** [comment]
I got round the error by adding this to CloudFormation:
```"OwnershipControls": {
    "Rules": [
        {
            "ObjectOwnership": "BucketOwnerPreferred"
        }
    ]
},```

I'm not sure if this solves the original issue, although I'm still not able to render the page, but this could be due to propagation etc.

**Comment by realtebo** [comment]
Thanks @electronicalias , your snippet works and resolves the problem as if setup from AWS Console
