### ISSUE TITLE
"amplify push" wants to delete parameters

### ISSUE THREAD

**Issue by ericstoecker** [aws-amplify/amplify-cli#12509]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

11.0.5

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes.

### Describe the bug

- When trying to run "amplify push", amplify says it wants to delete parameters
- and the message "Cannot read property 'AMPLIFY_analytics_Pinpoint_Id' of undefined" shows up

### Expected behavior

- amplify push should not delete any parameters
- no "Cannot read property 'AMPLIFY_analytics_Pinpoint_Id' of undefined" should not show up

### Reproduction steps

1. create amplify project
2. add analytics, graphql api, lambda layer
3. run "amplify push"
4. add lambda with dynamodb-trigger
5. run "amplify push"
6. give lambda access to analytics
7. run "amplify push" (push should fail)

this failed with the error "No export named api###GraphQLAPIIdOutput:GetAtt:####Table:Name found"

9. give lambda access to graphql (to solve above problem)
10. add lambda to layer (to solve above problem)
11. run "amplify push" (should work now)
12. edit index.js of lambda
13. run "amplify push"
14. now you should see the bug

![image](https://user-images.githubusercontent.com/71395664/233448345-6dba9578-a09e-4abc-a5f1-4208ac3c03e6.png)

### Project Identifier

Project Identifier: 8e7ec6dac606d8af0b67897bb966c442

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @ericstoecker :wave: thanks for raising this! While we begin to investigate this in more depth, did you recently upgrade your copy of Amplify CLI? These parameters should be stored in `amplify/backend/backend-config.json` but not in `amplify-meta.json`. If this is the case in your project can you try deleting them from `amplify-meta.json` and run `amplify env checkout <current-env-name>`? This should remove them from the status output and block them from being unintentionally removed.

**Comment by ericstoecker** [comment]
Hi @josefaidt ! I'm sorry to disappoint you but neither `amplify env checkout <current-env-name>` works nor are the variables stored in my `backend/amplify-meta.json`, they are only in `amplify/backend/backend-config.json`. They are however stored in `#current-cloud-backend/amplify-meta.json`. But deleting them doesn't change anything since they are restored after doing `amplify env checkout <current-env-name>`.

I also checked out the previous commit so that my code matches with the version of the last `amplify push`. But even if I push this state which does not contain any changes, amplify cli wants to delete my parameters

**Comment by ericstoecker** [comment]
Hey @josefaidt. I went through all the steps again because I just wanted to try whether ignoring the message and simply running `amplify push` may solve the problem. However when doing so, amplify also deletes the parameters in `amplify/backend/backend-config.json` so now they are neither in the  `backend-config.json` nor in `amplify-meta.json` and would thus be deleted. I also tried to use the previous version of amplify-cli `11.0.5` but this didn't solve my problem. This is currently preventing me from pushing so it would be really helpful to get some news on this issue.

**Comment by josefaidt** [comment]
Hey @ericstoecker :wave: apologies for the delay here

> They are however stored in #current-cloud-backend/amplify-meta.json. But deleting them doesn't change anything since they are restored after doing amplify env checkout <current-env-name>.

If the parameters are in the `#current-cloud-backend/amplify-meta.json` file then you will need to download the `#current-cloud-backend.zip` from your project's deployment bucket in S3, unzip, remove the parameters from `amplify-meta.json`, re-zip and re-upload to s3. Steps similar to https://gist.github.com/josefaidt/be56f2a8a821b084b66e40ce51e20b44, but rather than modifying the schema file we will want to edit the amplify-meta file.

I'd also be happy to hop on a call and walk through this! If you are a member of our [community Discord server](https://discord.gg/invite/amplify) my username there is `josef`

**Comment by ericstoecker** [comment]
Hey @josefaidt. I was able to finally push without deleting all the parameters so this seems to have resolved the issue. Thanks for your help.

**Comment by maziarzamani** [comment]
I got the same problem when upgrading from 10.8 to 12.0.
