### ISSUE TITLE
generated Auth template is broken by lines

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-cli#1250]
**Describe the bug**
Amplify auth generate broken `template.yml` file under auth, the generated file it has a lot of spacing and it's throw an error when I'm trying to push the changes
the error is: `CREATE_FAILED               authcognitoef404596              AWS::CloudFormation::Stack Thu Apr 11 2019 10:30:03 GMT+0300 (GMT+03:00) [/Resources/UserPool/Type/Schema] 'null' values are not allowed in templates`

**To Reproduce**
1. amplify init
2. ampliy add api
3. amplify add auth
4. amplify push

**Screenshots**
this is part of the template file
<img width="994" alt="Screen Shot 2019-04-11 at 10 34 41 AM" src="https://user-images.githubusercontent.com/5736522/55939197-d6567580-5c45-11e9-95fa-5f3f72f41190.png">

**Comment by NuruddinBadawi** [comment]
I figure out this issue why it appears
when config the Auth via CLI, and when this question appears `What attributes are required for signing up?` I didn't add any required field, because I add the phone number as a username, so this is the primary failed for me and in my case, I just what the phone number is required.

so this question in the CLI if cause a problem if you keep it empty, it should be show message or prevent continue the steps until choosing a field.

**Comment by kaustavghosh06** [comment]
@NuruddinBadawi You're right. There needs to be an added validation for that step. Working on a PR right now.

**Comment by NuruddinBadawi** [comment]
@kaustavghosh06  are you need to make this question required to choose one? 

In my case, I use phone_number as a username so the username is required, so what if I don't need anything else required just phone_number? is it make sense? 

also now in the current situation, how I can deal just with phone_number in login and register, with password?

**Comment by kaustavghosh06** [comment]
@NuruddinBadawi Not sure i'm following out here. So the first question in the auth flow is tied to the "Attributes you want the user to **sign in** with" and the second question relates to "Attributes you want the user to **sign up** with". So if you want users to sign in with a phone number, you would also require the user to sign up with a phone number. Let me know if that doesn't make sense.

**Comment by kaustavghosh06** [comment]
And yes, we're making this question required to choose at least one.

**Comment by kaustavghosh06** [comment]
Merged he PR for this. Fix ill get release in the next version of the CLI.
