### ISSUE TITLE
Add more granular permissions to Amplify users

### ISSUE THREAD

**Issue by Thiamath** [aws-amplify/amplify-cli#12517]
### Is this feature request related to a new or existing Amplify category?

auth, storage, function

### Describe the feature you'd like to request

Hello there!

This is my use case:

I have a front-end team that is developing the web UI. I want them to be able to connect to the dev back-end environment in their local so that they can develop faster by still using a fully functional back-end. For that, they need the `aws-exports.json` file in their react environment to do the connections with Auth, data storage, lambda functions, etc.

BUT, they don't need any of the backend functions or all the configuration. And also, they don't need to access the full backend stuff in Amplify Studio.

On top of that, I'd like to keep the backend and the front-end in different repositories, but this way there's hard to keep them separated. Either I have a monorepo with all the stuff there, or I have the backend duplicated in the frontend and backend repos. Yes, I guess I could instruct the `.gitignore` file to ignore all the Amplify stuff, but it is still a problem to have the backend downloaded into the front-end team laptops.

Right now, the only way I can allow them to work like this is by giving them the `Full access` permission in Amplify Studio and making them run `amplify pull` in their locals only to recreate the `aws-exports.json` file.

### Describe the solution you'd like

My suggestion is:
- Increase the granularity in the Amplify user permissions so that there's not only "content creator" and "super-cow-powered-admin".
- Create a command in the Amplify CLI to recreate the `aws-exports.json` file without pulling the whole backend descriptors.

### Describe alternatives you've considered

I guess I could instruct the `.gitignore` file to ignore all the Amplify stuff, but it is still a problem to have the backend downloaded into the front-end team laptops.

Right now, the only way I can allow them to work like this is by giving them the `Full access` permission in Amplify Studio and making them run `amplify pull` in their locals only to recreate the `aws-exports.json` file.

### Additional context

I could help with testing this but unfortunately, I don't have enough time right now to help with the development.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by parvusville** [comment]
In the past I have just manually provided the aws-exports.json file for the developers, that do not need to modify backend. This way they don't have to do amplify pull, or anything else amplify cli related. 

For the frontend app (different app in the monorepo) we have set all the relevant values from aws-exports to environment variables, and use those values for Amplify.configure(...). This is not the most elegant solution, and does require setting up the env variables manually for every new environment, but it works.

**Comment by josefaidt** [comment]
Hey @Thiamath :wave: thanks for raising this! To echo @parvusville this would be the path of least friction, and will remove the need for pulling the `amplify/` backend directory. Frontend developers can use an IAM role/user with a minimal IAM Policy to allow `amplify pull` in order to create this file, however they will need to pull a subset of the backend, thus still creating an `amplify/` directory in some capacity.

This also seems like a great use case for https://github.com/aws-amplify/amplify-cli/issues/11131

**Comment by Thiamath** [comment]
> This also seems like a great use case for https://github.com/aws-amplify/amplify-cli/issues/11131


Yes @josefaidt , actually it is asking basically for the same thing there!

Unfortunately #11131 is 7 months old 😅. No rushing tho... I understand that these things take time.

If there's anything I can do...

**Comment by josefaidt** [comment]
Hey @Thiamath thanks for clarifying and for adding a 👍 to the request! It helps us gauge interest and prioritize! For the time being I would suggest either sharing the aws-exports.js file directly or use the CLI to pull the backend and generate this file.

I'll mark this issue as a duplicate feature request of #11131 and close in favor of tracking the existing request.
