### ISSUE TITLE
Use existing resources

### ISSUE THREAD

**Issue by adriatikgk** [aws-amplify/amplify-cli#1252]
Hi there,

I want to setup a cognito user pool and api gateway using AWS Web app and I will have two moile apps ios & android that use these same resources.

Im using amplify CLI for ios and android apps, but I dont know how to point to same CognitoUserPool and ApiGateway in both application, because if I make amplify add auth it creates two different CognitoUserPools for each project.

Is there any solution about that ?

**Comment by kaustavghosh06** [comment]
@adriatikgk You could follow the steps outlined here - https://aws-amplify.github.io/docs/cli/init#amplify-configure-project

Also you could take a look at thsi thread for more ideas around this - https://github.com/aws-amplify/amplify-cli/issues/582

**Comment by adriatikgk** [comment]
Thanks @kaustavghosh06

**Comment by willrust** [comment]
Link above is dead. Found the info here:
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends
