### ISSUE TITLE
APIGW names when using multi-env

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1253]
**Is your feature request related to a problem? Please describe.**
When you configure multi-env, the APIGW names are all the same for each env.

**Describe the solution you'd like**
It would be nice if you could append the env name to the APIGW function.

**Describe alternatives you've considered**
Maybe update the CF template myself.

**Comment by kaustavghosh06** [comment]
@jarrettj We decided to modify the stage for the api name for APIGW for each of the envs. This is a design decision we made as a team. But we could keep this issue open and see if there are more customers wanting this enhancement, based on which we can make this a priority.

**Comment by jarrettj** [comment]
Not really, I'll close it because updating the CF template was easy. 
Original:
```
"Type": "AWS::ApiGateway::RestApi",
"Name": "myFunction"
```

Change:
```
"Type": "AWS::ApiGateway::RestApi",
"Name": { "Fn::Join": [
            "",
            [
              "myfunction",
              "-",
              {
                "Ref": "env"
              }
            ]
          ]},
```

I'm fine to close this issue, thanks.
