### ISSUE TITLE
Update DynamoDB TTL

### ISSUE THREAD

**Issue by tobyloki** [aws-amplify/amplify-cli#12533]
### Amplify CLI Version

11.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

How would it be possible to update the default DynamoDB TTL of 43200 to 60? I see that a cloudformation stack gets auto generated for each of my graphql types in the amplify/backend/api/MyProject/build/stacks directory. I've pasted a screenshot of the parameter in my User.json stack. This parameter doesn't seem to modifiable unlike parameters like  DynamoDBBillingMode and DynamoDBEnablePointInTimeRecovery shown in the second screenshot. At least those parameters are specified in the Parameters section of the cloudformation stack, and can be overwritten in amplify/backend/api/MyProject/parameters.json, but not for BaseTableTTL. So how would I be able to modify this value?

![image](https://user-images.githubusercontent.com/35203563/234758130-e8e9046c-3461-4733-a298-c2254f5322ce.png)
![image](https://user-images.githubusercontent.com/35203563/234758137-55604e29-d19d-4683-82ed-eda03bfdc3ed.png)

### Expected behavior

Should be able to update DynamoDB TTL, preferably in the parameters.json file.

### Reproduction steps

N/A

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @tobyloki, 👋 thank you for reaching out. This issue appears to be similar to https://github.com/aws-amplify/amplify-category-api/issues/47
we can utilize the [API override](https://docs.amplify.aws/cli/graphql/override/) functionality to modify the TTL.
```
resources.models["Todo"].modelDatasource.dynamoDbConfig['deltaSyncConfig']['baseTableTtl'] = '60'
```

on pushing the project, we can confirm the TTL using the AWS CLI command: `aws appsync get-data-source --api-id <api id> --name <Table name>`

additionally, an example on modifying the timeToLiveSpecification can be found at https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive

**Comment by tobyloki** [comment]
Thanks. That's the answer I was looking for.
