### ISSUE TITLE
amplify add auth: required attributes lists "middle name" twice and given name never

### ISSUE THREAD

**Issue by paddlefish** [aws-amplify/amplify-cli#1254]
**Describe the bug**
amplify remove auth has middle name twice and given name never.  There is no way to create a cognito identity pool that requires given name.  And since cognito pools cannot be modified once created this means Amplify projects cannot use given name field at all.

As a workaround for now we're using name and family name.

**To Reproduce**
 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Ena
bles per-user Storage features for images or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: projectname
 Please enter a name for your identity pool. projectname
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Please provide a name for your user pool: projectname
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in when using your Cognito User Pool? Email
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up?
At this point it lists these attributes: 
The wizard allows you to select any of these attributes: address nickname birthdate phone number email picture family name preferred username gender profile middle name zoneinfo locale updated at middle name website name
Notice how middle name appears twice.
Also, it doesn't match the order that it lists the attributes in the web console forcognito user pool attributes

**Expected behavior**

The wizard allows you to select any of these attributes: address nickname birthdate phone number email picture family name preferred username gender profile given name zoneinfo locale updated at middle name website name

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4 (18E226) Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
 - Browser n/a -- this is from terminal

**Additional context**
I think this is due to "Middle Name" being listed twice in string-maps.js and "Given Name" not being listed.

**Comment by jkeys-ecg-nmsu** [comment]
You mean `amplify add auth`?

**Comment by paddlefish** [comment]
Oh yes, because cognito pools are immutable, every time I run I do a remove auth followed by add auth ... but yes it's the add step that's the issue here.  If I can edit the title I'll do that.

**Comment by jkeys-ecg-nmsu** [comment]
What makes you think user pools are immutable? I think the only immutable portion of user pools is that required attributes must be writable, and cannot be made read-only after the fact. But you can add custom attributes, add app clients, change Oauth flows, etc. after the pool has been created.

I think running `amplify auth configure` will allow you to update your user pool, although it doesn't fix the missing "gender" claim issue.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu I think whaat @paddlefish is referring to is that the sign in and sign up attributes for a cognito user-pool are immutable.(which is currently a service limitation).
@paddlefish I'm looking into this now. This looks like a bug,

**Comment by paddlefish** [comment]
I've been battling Amplify all week, so maybe I overstate the immutability of cognito pools.  However, I did find that trying to use `amplify update auth` doesn't let you do all that you can do with remove and add.  Specifically, we were trying to change the email vs username choice and the required attributes.  Those can only be changed by removing the pool and re-adding.
