### ISSUE TITLE
REST Api Choosing an existing Lambda

### ISSUE THREAD

**Issue by nesimventures** [aws-amplify/amplify-cli#12553]
### Description

Hello,
 I'm following this [documentation](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/flutter/#configure-api) to add REST API to my flutter project but I want to choose an existing Lambda to invoke instead of creating a new one, as I already have created Lambda separately. However the "amplify add api" command is not letting me chose  from an existing lambda.  Any idea why ?

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

[documentation](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/flutter/#configure-api)

### Screenshots

![image](https://user-images.githubusercontent.com/130711003/235372189-7fc2cb0a-d58d-4fe5-9aea-2a19d66da507.png)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @nesimventures, I've transferred this issue to the CLI repo. I don't believe this is currently possible, but could be wrong. Will let the CLI team verify and/or provide available workarounds.

**Comment by nesimventures** [comment]
Hi @ykethan, and thanks @dnys1 . I have tried many different ways and it seems like the only time it allows you to chose an existing lambda is if it was created using "amplify add function" or "amplify add api" which they add lambda function to the amplify project. However, in my case I have created the lambda using CDK so it's not recognizing it as part of the amplify project. Is there any workarounds or an amplify command that allows you to add existing AWS services to the amplify project ? By the way another workaround I'm working on is that I created the api through the CDK and trying to add it to the amplifyconfiguration.dart file but I'm running through some Authentication errors.

**Comment by evcodes** [comment]
I'm seeing that Use existing resource feature on the docs site only applies to Android or iOS: https://docs.amplify.aws/lib/project-setup/use-existing-resources/.

**Comment by dnys1** [comment]
The Flutter docs are located under a different URL: https://docs.amplify.aws/lib/restapi/existing-resources/q/platform/flutter/

@nesimventures, you can create the REST API with CDK (using IAM or User Pools Authorization) and add the endpoint to your configuration as noted in this document. In the case of IAM authorization, you'll need to also update your identity pool's unauthenticated/authenticated IAM roles with the correct permissions, respectively.

**Comment by evcodes** [comment]
Good catch, let me see if we can modify the cloudformation output to reference the ARN of the lambda function... Will get back to you with the results.

**Comment by nesimventures** [comment]
I'm current trying trying to implment what @dnys1  suggested but I keep getting Unauthorized error. 
![image](https://user-images.githubusercontent.com/130711003/235516286-ba6b078c-92e8-46f6-b8a4-5894e392a3a9.png)

Here is how I'm sending this post request:
![image](https://user-images.githubusercontent.com/130711003/235517400-b66a9329-84ad-4bcc-806f-e4e4efe36095.png)


Here is how I added the api manually to my amplifyconfiguration.dart I dotted out the keys by the way:
![image](https://user-images.githubusercontent.com/130711003/235517364-ca3efc3e-dfab-4360-9582-af02ac67ddbb.png)


Here is how I created the api through CDK : 
![image](https://user-images.githubusercontent.com/130711003/235516792-4249f93a-24c1-433b-aefe-f8f75468bde5.png)

**Comment by nesimventures** [comment]
I'm doing manual testing where I validated the generated token on the console but its still saying unauthorized.  this is how I'm getting the idToken:
![image](https://user-images.githubusercontent.com/130711003/235546419-eae25e8f-7143-4bdc-a79c-f259b4a9f968.png)
The response is screenshot:
![image](https://user-images.githubusercontent.com/130711003/235546484-6f9ae5cc-422d-418c-b0ba-3e82a00da34e.png)

**Comment by dnys1** [comment]
Hi @nesimventures, can you try without including Authorization headers? Amplify should do it automatically for you.

The issue could be that the ID token is be retrieved by calling:

```dart
final cognitoPlugin = Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
final result = await cognitoPlugin.fetchAuthSession();
final tokens = result.userPoolTokensResult.value;
final idToken = tokens.idToken.raw;
```

**Comment by nesimventures** [comment]
Yeah, that was the issue and its working now thanks @dnys1.
@evcodes Hopefully there is. a way that we can somehow modify the amplify cloudformation to include services that where created without using `amplify add ..` such as lambda.

**Comment by josefaidt** [comment]
Closing as this is now resolved
