### ISSUE TITLE
completeCallback not being fired

### ISSUE THREAD

**Issue by MarksASP95** [aws-amplify/amplify-cli#12550]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.17.0

### Amplify CLI Version

10.7.3

### What operating system are you using?

Ubuntu 20.04

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Installed Api, Auth, Functions and Storage. Also made Storage auth completely public for testing purposes.

### Describe the bug

I'm trying to upload a file to my storage with an input element.

```
function handleCaptureInputElementChange(e: Event) {
  const file = inputCaptureEl.files![0];
  console.log("uploading");
  Storage.put(file.name, file, {
    contentType: file.type,
    progressCallback: (progress) => {
      console.log("PROGRESS CALLBACK", progress);
      setShowUploadingText(true);
      setUploadingTextPerc((progress.loaded * 100) / progress.total)
    },
    errorCallback: (err) => {
      console.log("ERROR CALLBACK", err);
    },
    completeCallback: (event) => {
      console.log("COMPLETE CALLBACK", event);
    },
  })
}
```

The file uploads and `progressCallback` is working perfectly fine, but `completeCallback` never runs. The file finishes uploading and I can even see it in my Storage console.

![image](https://user-images.githubusercontent.com/13427229/235321758-78cebfc0-72d0-488a-8153-434c2e0f5e1a.png)
This is the last `progressCallback` log (total = loaded). There is no `completeCallback` log, even after a few minutes.

### Expected behavior

`completeCallback` should run when the file upload finishes.

### Reproduction steps

1. Create Vite Vanilla Javascript project
2. Install `aws-amplify: "^5.0.25"`
3. Configure Amplify app
4. `amplify add storage`
5. Go to studio and make bucket auth complete public
6. Add input of type file
7. Add event listener and add the provided function as a callback
8. Click on the file input and select a file

### Project Identifier

2f51e53183939ecec2d7ffa5637a79a0

### Additional information

`package.json`

Already tried `aws-amplify: "^5.0.25"` and `aws-amplify: "^5.1.14"` (latest)
```
{
  "name": "my_project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "typescript": "^4.9.3",
    "vite": "^4.2.0"
  },
  "dependencies": {
    "aws-amplify": "^5.1.4"
  }
}
```

### Before submitting, please confirm:

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by jaydip181** [comment]
I'm having same issue, Are you able to solve that?

**Comment by MarksASP95** [comment]
Yes. I closed this because it's not the right repo. What you must do is set `resumable` to `true` in order for `completeCallback` to work. When you do that you must call `resume()` to start uploading.
