### ISSUE TITLE
Cannot add "api" due to a cyclic dependency

### ISSUE THREAD

**Issue by belfortf** [aws-amplify/amplify-cli#12552]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.21.3

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

I have an Rest-API created through the CLI called "sessionsapi". There are currently 3 paths configured for this API. I'm now trying to add a new a path, so I did "amplify update api" and chose "REST" and "sessionsapi". I've then selected "Add another path" and named the path "/text". I have then selected "create a new Lambda function", gave it the name "text" and selected "Python".

I would expect to be able to create the new path, but not matter what I do, I always get "🛑 Cannot add sessionsapi due to a cyclic dependency". I have tried changing names and other parameters but I end up always getting the error above. I didn't find this error before so I think you won't be able to reproduce it.

### Expected behavior

I'd expect the path to be created.

### Reproduction steps

1. amplify update api
2. REST
3. "sessionsapi"
4. "Add another path"
5. /text
6. "create a new Lambda function"
7. "text"
8. "Python"
9. ? Do you want to configure advanced settings? No
10. ? Do you want to edit the local lambda function now? Yes
11. ✅ Succesfully added the Lambda function locally
✔ Restrict API access? (Y/n) · no
✔ Do you want to add another path? (y/N) · no
12. 🛑 Cannot add sessionsapi due to a cyclic dependency

### Project Identifier

Project Identifier: 4356f5d6df98431d31b1b5db279a7f73

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by evcodes** [comment]
Hey @belfortf, I am going to close this issue since we have not heard from you in a week. Please feel free to reopen if you have more information/comments
