### ISSUE TITLE
No Amplify backend project files detected within this folder for a front end app

### ISSUE THREAD

**Issue by CharlesAondo** [aws-amplify/amplify-cli#12569]
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

### Amplify CLI Version

11.1.1

### What operating system are you using?

Mac OS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Describe the bug

Amplify pull for front end app with no backend configured keep trying to pull the backend even though the application has no backend configuration. It gives this error  ProjectNotInitializedError: No Amplify backend project files detected within this folder.

### Expected behavior

Amplify pull should pull the application regardless of backend or not.

### Reproduction steps

1. create amplify app either with terraform or via ui
2. Run amplify pull
3. Select the app from the list 
4. You will get this error  ProjectNotInitializedError: No Amplify backend project files detected within this folder

### Log output

<details>

```
# Put your logs below this line

 
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @CharlesAondo, 👋 thank you for reaching.  Wanted to confirm some information, are you expecting Amplify CLI to pull only the front-end from the application that does not have a backend created on AWS console?
This is currently not a supported workflow, Amplify pull will only pull your backend environments. 

Curious on the error message ` ProjectNotInitializedError: No Amplify backend project files detected within this folder` as  in my reproduction in received a different message. running the pull command in empty directory provided me with `🛑 Cannot find backend environment in Amplify Console app: <app-name>`

**Comment by CharlesAondo** [comment]
Hey @ykethan  Yes, I was expecting the `amplify pull`  command to work on frontend app with no backend. Any idea on how I can trigger a build from the CLI for a front end app in amplify? because if the project does not pull the build will fail. I will appreciate an idea of how I can trigger the build using terraform because I am creating the app in terraform script. Thank you so much for your time.

**Comment by ykethan** [comment]
hey @CharlesAondo, you could try utilizing the incoming webhooks to trigger a build. For additional information, refer to https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html 

could you let let us know how were you trying to pull the app locally? was this is in a empty directory or existing Amplify directory? was the pull command being utilized with any arguments? 

cc: @hloriii

**Comment by CharlesAondo** [comment]
It was in the-same directory as my terraform script, so it is not an amplify directory, they app was created with a terraform script. This is the full story when I run amplify pull ` amplify pull
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use Amplify
? Which app are you working on? (Use arrow keys)
❯ Front End Dev (app-id) 
  Front End Production (app-id) 

🛑 Cannot find backend environment in Amplify Console app: Front End Dev

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: a0e86c2f-**********************`

**Comment by ykethan** [comment]
Hey @CharlesAondo, thank you for the information. If you require an additional information on the builds in AWS console. Please feel free in creating a issue on our [amplify-hosting repository](https://github.com/aws-amplify/amplify-hosting/issues).
Closing the issue. Do reach out to us again if you require any assistance.

**Comment by Jimgitsit** [comment]
Was this resolved? Did I miss something?

**Comment by justingatlin-ny** [comment]
I have the same problem.
When I try amplify pull or amplify add ap I get the response Cannot find backend environment in Amplify Console app: <app name>

I have not been able to create a back end or api yet.
