### ISSUE TITLE
What's the "right" way to manage ephemeral env vars for local development?

### ISSUE THREAD

**Issue by TheKayThatWasOrange** [aws-amplify/amplify-cli#12573]
### Amplify CLI Version

11.1.1

### Question

My team has a little app that uses a lot of functions. These functions reach out to lots of little services which we also run locally during development. Every one of these services has an ephemeral and disposable `ngrok` URL which changes frequently and is of no value to anyone other than the developer currently doing some development work on the app and its related services. These URLs have to be provided to the Lambda functions in order for anything to work at all.

Amplify has a concept of environments into which environment variables can be placed in order to share them out to individual functions in the project. In practice this seems to amount to them being added to a sizeable JSON tree in a file named `team-provider-info.json`. This "works," but is exceedingly onerous for the following reasons:

1) `team-provider-info.json` snowballs to a completely unmanageable size very, very quickly as more developers join the team and add more keys

2) There is no clear mechanism for communicating when keys are added/changed to other developers; every single person has to sit down and make the same little changes to `team-provider-info.json` every single time a change is necessary. Since we're developers, changes are necessary on an extremely regular basis.

3) A substantial amount of completely unnecessary repetition invariably manifests in cases where 20 different lambda functions all use the same 20 services. Now instead of updating one URL because you bounced a process, you have to edit 400 of them. Blind search-and-replace is perilous in this file as it contains everybody's everything, not just the stuff *you* care about right now.

4) Again, there is absolutely no value in sharing these kinds of keys with anyone who isn't physically typing code on my computer. It's not like this is the "staging" environment that everyone shares, these are *my* values which have meaning to *me* and me alone. They simply do not belong in Git or anywhere else.

I've read the docs and many, many issues related to the confusion surrounding env vars in Amplify that have come up over the years and I simply have not been able to determine whether there is any Amplify-approved means of accomplishing this seemingly basic task. In any other app on any other platform we'd have a `.env.example` file checked in to Git, it'd have a bunch of keys with no values in it and we'd tell new devs to copy it to `.env` and fill in the blanks. Then we'd be done and the new dev could boot the app and get to work doing something besides struggle to understand what Amplify is persisting where and when as they `checkout` other dev's environments and try to copy them, hoping they picked a good one to copy.

While I think there's a solid argument to be made in favor of reconsidering our overall architectural choices, we are where we are and we can't change everything at once. Is there a baked-in facility for this sort of local environment management which I am missing completely or is this one of those "our product managers don't care about that workflow so we're never going to do anything like that" sort of deals we've all come to know and love from AWS? 

Thanks.

**Comment by josefaidt** [comment]
Hey @TheKayThatWasOrange :wave: thanks for raising this and for providing the detailed write-up! 

> team-provider-info.json snowballs to a completely unmanageable size very, very quickly as more developers join the team and add more keys

> There is no clear mechanism for communicating when keys are added/changed to other developers; every single person has to sit down and make the same little changes to team-provider-info.json every single time a change is necessary. Since we're developers, changes are necessary on an extremely regular basis.

[It is not typically recommended to manually modify the `team-provider-info.json` file](https://docs.amplify.aws/cli/reference/files/#team-provider-infojson), however I see how this fits into your workflow well. 

> A substantial amount of completely unnecessary repetition invariably manifests in cases where 20 different lambda functions all use the same 20 services. Now instead of updating one URL because you bounced a process, you have to edit 400 of them. Blind search-and-replace is perilous in this file as it contains everybody's everything, not just the stuff you care about right now.

This is definitely highlighting a gap to [share environment variables](https://github.com/aws-amplify/amplify-cli/issues/8360) across Functions. Are you testing your Functions locally with `amplify mock function` or by other means? 

> Again, there is absolutely no value in sharing these kinds of keys with anyone who isn't physically typing code on my computer. It's not like this is the "staging" environment that everyone shares, these are my values which have meaning to me and me alone. They simply do not belong in Git or anywhere else.

Depending on the answer to the question above I have a few ideas of workarounds that you can leverage here to circumvent the tediousness of copy/pasting the same value over and over. But this is a great pitch for local-only env vars (similar to how you would typically reach for `.env.example.local`)

> I've read the docs and many, many issues related to the confusion surrounding env vars in Amplify that have come up over the years and I simply have not been able to determine whether there is any Amplify-approved means of accomplishing this seemingly basic task

>  Is there a baked-in facility for this sort of local environment management which I am missing completely 

Unfortunately there is not a way to manage these through the CLI today, however would you be open to hopping on a call to discuss your ideal secrets/env var management flow? If you're a member of our [community Discord server](https://discord.gg/invite/amplify) my username there is `josef` 🙂 , or you can send us an email at amplify-cli@amazon.com and we can take it from there!
