### ISSUE TITLE
Error publishing frontend code to s3 hosting bucket with Amplify

### ISSUE THREAD

**Issue by stevedsousa** [aws-amplify/amplify-cli#12586]
### Amplify CLI Version

1.11.1

### Question

Hi, I have updated to amplify version 11.1.1 and trying to publish to my hosting on an s3 bucket and now I'm getting this error, it mentions a workaround which I already have set up for the ACLs, but still shows the error, now the error says:

You are trying to host an application without a CloudFront distribution. This is not supported on S3 by default.
You will need to deploy your application to PROD or use this workaround for non-public dev apps only.

this is the workaround issue that I already set up:
https://github.com/aws-amplify/amplify-cli/issues/12503

on my amplify project a cloud front is not configured, there's one cloud front already set up manually on the AWS console, so is already one but is not directly created from amplify.

any ideas on how to resolve this problem??

**Comment by ykethan** [comment]
Hey @stevedsousa , 👋 thank you for reaching out. To remediate the issue you will need to run `amplify configure hosting` and select `CloudFront` to add the CloudFront distribution. Amplify CLI hosting category currently does not sync changes on the AWS console such as CloudFront distribution being manually configured.

**Comment by stevedsousa** [comment]
So is this like a new requirement added to the latest amplify version?, this was not required before, basically I need to update a lot of configuration because is now saying I need to set up the cloud front in amplify aside from the hosting configuration, which this is something I did not expect to happen.

Basically, I need to pass my current config to be then handled by Amplify, but will take time and configuration based that we have several environments all the way to prod, why was this added on this new version? is this like a new requirement every time you set up a new hosting environment? 

Can Amplify add something to say use this cloud front config already instead of adding a new one ???

**Comment by evcodes** [comment]
Hey @stevedsousa, we understand the frustration. This happened because S3 changed their configurations to not support ACLs by default on any new S3 bucket created. This broke our hosting with S3 and CloudFront for DEV environments.

In order to better understand your use case, what is the reason behind using the same CloudFront distribution for your application in different environments?

We understand that this is not ideal but we suggest the easiest way to get unblocked would be to tear down and recreate Hosting with S3 and CloudFront.

**Comment by stevedsousa** [comment]
We use cloud front distributions on diff env to assure all is working as expected as prod as we have a pre-prod environment and some others and should be as much as equal to the real thing before any changes go to prod, but that's not the problem, the problem is we need to configure now all of the apps because we need to set it up based on amplify and it will generate a new Id for that CF dist, so I need to plan this process if we want to keep up with the latest version of amplify, so yes is frustrating in a way because of the workaround and new config that is needed, I get that ACLs config has changed but it affected my current process because of that and now need to plan a migration of our services to be on amplify tied to the hosting buckets, thanks for the time to respond, have a great weekend.
