### ISSUE TITLE
How to override "userPoolClientWeb" client ID using amplify override ? 

### ISSUE THREAD

**Issue by shivennn** [aws-amplify/amplify-cli#12611]
### Amplify CLI Version

na

### Question

I am not able to find specific attr value for overriding "userPoolClientWeb" client ID.

```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';
export function override(resources: AmplifyAuthCognitoStackTemplate) {

}

```

I checked [customize-amplify-generated-cognito-auth-resources](https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-auth-resources) and [aws-resource-cognito-userpoolclient](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html).

**Comment by josefaidt** [comment]
Hey @shivennn :wave: thanks for raising this! Are the intentions to completely override the generated UserPool Client for web? or reference another, existing client?

**Comment by josefaidt** [comment]
Hey @shivennn after digging into this a bit further I am unable to find a way to force recreate this client or use an override to import. The easiest path forward would be to remove auth and add it again with the CLI to recreate entirely, however I understand this may not be feasible if there is production data from a live app. If this is the case, you can enable Deletion Protection for Cognito and remove it from your project, then use `amplify import auth` to import the same User Pool with the newly created client.
