### ISSUE TITLE
Generate aws-exports.js at build step

### ISSUE THREAD

**Issue by webjay** [aws-amplify/amplify-cli#12618]
### Amplify CLI Version

11.1.1

### Question

It seems odd that in order to generate `aws-exports.js` for a build step at i.e. Vercel (another cloud provider) I need to specify which code editor I use?!

https://docs.amplify.aws/cli/usage/headless/#sample-script-3

**Comment by webjay** [comment]
What is the minimum `npm run amplify pull -- --providers $PROVIDERS --amplify $AMPLIFY --frontend $FRONTEND --yes` required to just get `aws-exports.js`?

**Comment by josefaidt** [comment]
Hey @webjay :wave: thanks for raising this! If you have AWS credentials set on a profile you can use a script similar to https://gist.github.com/josefaidt/a8cd6071d250693fdae73c84bc5b23f7 or `amplify init --appId <app-id> --envName <env-name> --yes`

**Comment by webjay** [comment]
Very nice, thank you :)

**Comment by webjay** [comment]
`amplify init --appId <app-id> --envName <env-name> --yes` fails:
> Failed to resolve AWS credentials with --yes flag.

I have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY set in env.

**Comment by webjay** [comment]
Has AWS thought of making it possible to host anywhere else but on AWS?
