### ISSUE TITLE
Changes in resolver vtl template not updating in the cloud

### ISSUE THREAD

**Issue by matthieunelmes** [aws-amplify/amplify-cli#1261]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
I'm providing req and res vtl templates to override resolver templates. I've followed documentation as per:
https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

**To Reproduce**

1. Create schema.graphql

```
type Post @model {
    id: ID!
    product_id: ID!
    description: String
    date_time: String!
    product: Product
}

type Product @model {
    id: ID!
    name: String!
    affiliate_link: String
    category_id: ID!
    price: String
}
```

2. create Post.product.req.vtl under amplify/backend/<projectname>/resolvers
```
## Request
{
    "version": "2017-02-28",
    "operation": "GetItem",
    "key" : {
        "id" : { "S" : "${context.source.product_id}" }
    }
}
```

3. Create Post.product.res.vtl under amplify/backend/<projectname>/resolvers
```
## Response
$util.toJson($ctx.result)
```

4. Push to cloud
`amplify push`

5. After success push, log into the AppSync dashboard and the resolvers have not been linked. I'm still having to create these manually in the dashboard.

**Expected behaviour**
Be able to programmatically create resolvers through vtl templates and the CLI

**Comment by kaustavghosh06** [comment]
@matthieunelmes Which version of the CLI are you using? Also, are you using custom resolvers to override the resolvers generated by the Transformer?

**Comment by matthieunelmes** [comment]
@kaustavghosh06 CLI is V1.1.7

Ok yes, I'm trying to add a custom resolver to the ones generated from my schema.graphql definition.

I'm able to add the custom resolvers in the AppSync dashboard manually, but I want to be able to specify them in vtl templates for ease of use and to keep everything source controlled.

**Comment by matthieunelmes** [comment]
UPDATE

I managed to achieve the desired results by instead using the @connection directive in my schema definition.

This works fine for my current requirements of one-to-many relationships.
