### ISSUE TITLE
function mock errors are not stringified, printing `[object Object]`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#12626]
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

12.0.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

When mocking functions, if the function errors for any reason we are presented with a generic error message from CLI and the actual error as `[object Object]`

it appears to be going wrong here https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-util-mock/src/func/index.ts#L61

```
Ensuring latest function changes are built...
Starting execution...
🛑 sayhelloerror failed with the following error:
[object Object]
Finished execution.
```

### Expected behavior

error is printed

### Reproduction steps

1. `amplify init -y`
2. `amplify add function` > accept all defaults
3. add an error to the function template
	```js
	throw new Error('Hello from Lambda!')
	
	/**
	 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
	 */
	exports.handler = async (event) => {
	  console.log(`EVENT: ${JSON.stringify(event)}`)
	  return {
	    statusCode: 200,
	    //  Uncomment below to enable CORS requests
	    //  headers: {
	    //      "Access-Control-Allow-Origin": "*",
	    //      "Access-Control-Allow-Headers": "*"
	    //  },
	    body: JSON.stringify('Hello from Lambda!'),
	  }
	}
	```
4. `amplify mock function`
5. observe error

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Was able to reproduce the issue. marking as bug.
