### ISSUE TITLE
Passing cognito user pool web client id to lambda functions

### ISSUE THREAD

**Issue by Jegerh** [aws-amplify/amplify-cli#12647]
### Describe the feature you'd like to request

Related to https://github.com/aws-amplify/amplify-cli/issues/1695 that was never resolved.

being able to use Amplify inside a lambda function like we do in the frontend we need the param: aws_user_pools_web_client_id found on the aws-exports file that we pass to Amplify to configure it (Amplify.configure(aws_exports)).

### Describe the solution you'd like

pass the aws_user_pools_web_client_id param to lambda functions.

### Describe alternatives you've considered

NA

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @Jegerh :wave: thanks for raising this! While we do not currently support lifting the `aws-exports` file directly into the Lambda source code, you can dynamically modify the `SourceDir` of `amplify/.config/project-config.json` and re-run `amplify env checkout <current-env-name>` to generate this file inside the chosen source directory

**Comment by josefaidt** [comment]
Additionally, what is the use case for surfacing this web client ID to the Lambda?
