### ISSUE TITLE
Configuring Cognito SES settings.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1265]
** Which Category is your question related to? **
amplify auth add

** What AWS Services are you utilizing? **
Cognito and SES.

** Provide additional details e.g. code snippets **
How would you go about changing the SES settings via cloud formation? I've attached a screeshot as well.

![image](https://user-images.githubusercontent.com/777547/56040370-899e9780-5d36-11e9-9635-25ccc4762818.png)

Regards.

**Comment by kaustavghosh06** [comment]
@jarrettj Did you take a look at the Cloudformation fields supported by Cognito? Is SES supported in it?

**Comment by kaustavghosh06** [comment]
If it's not inherently supported by Cognito Cloudformation, then i would recommend writing a custom resource (lambda function) in your Cloudformation similar to some other custom resources we support as a part of the auth/cognito cloudformation currently.

**Comment by jarrettj** [comment]
Hi,

It does not look as though it is supported by CF. It should be, but when I update the CF template, the changes do not take effect. 
```
      EmailConfiguration:
        SourceArn: "arn:aws:ses:eu-west-1:*************:identity/test@example.com"
```

Seems to work, the from email changes. But there's no option to change the region, and I think that is why it breaks. Will post to the forums as well. Think this is more of a CF issue. For now I'll manually set it up. As once we go live, the User Pool will probably not change.

Thanks.

**Comment by mjmaix** [comment]
Hi @kaustavghosh06, EmailConfiguration should be supported by Cloudformation -> [link to UserPool EmailConfiguration](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html )

Caution is that any manually configured EmailConfiguration on the User Pool will be lost and reverted to DEFAULT if `aws auth push` is run.

Though it might not be a big issue if the User Pool does not change often, it is still a feature that will be very useful available on the CLI.

**Comment by sukeshn** [comment]
CloudFormation UserPool EmailConfiguration doesn't work. 

I gave following input in cloud formation template:

`arn:aws:ses:us-east-1:************:identity/support@xxxxxxx.com`

I get following CloudFormation error.

`1 validation error detected: Value ' arn:aws:ses:us-east-1:************:identity/support@xxxxxxx.com' at 'emailConfiguration.sourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:[\w+=/,.@-]+:([\w+=/,.@-]*)?:[0-9]+:[\w+=/,.@-]+(:[\w+=/,.@-]+)?(:[\w+=/,.@-]+)? (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 3522e111-4841-4f1b-8563-dc8957b68e28)`

**Comment by jarrettj** [comment]
If you are in the us-east region it should work. You copy/pasted your arn from the SES service? Very strange.

**Comment by sukeshn** [comment]
Jarrettj, sorry it was my bad, there was a whitespace at the start of the arn.

**Comment by jarrettj** [comment]
Cool man, glad you got it “working”. Hopefully better CF support is on the way for SES.


________________________________

**Comment by borisdayma** [comment]
@sukeshn I've been trying to achieve the same but am having some difficulty (not much experience with CloudFormation). Would you be able to explain in more details what you did?

Did you add a new custom resource [similar to this](https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916)?
Or did you update your `amplify/backend/function/CustomMessage`?
Or maybe both?

In the end I'd like any email to be sent from a custom email address.

**Comment by borisdayma** [comment]
@jarrettj Would it be possible to add details on how to do it in the documentation?
