### ISSUE TITLE
Cannot find module 'babel-types' (amplify cli after fresh install)

### ISSUE THREAD

**Issue by danfrost** [aws-amplify/amplify-cli#1268]
**Describe the bug**
After fresh install of amplify-cli I get the follow. I have uninstalled and reinstalled to check.

```
$ amplify
/Users/dan/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Cannot find module 'babel-types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dan/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/amplify-graphql-types-generator/lib/flow-modern/helpers.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**To Reproduce**
```
npm install -g @aws-amplify/cli
amplify
```

**Expected behavior**
Expecting to be able to configure. I haven't successfully run and/or configured amplify before.

**Desktop (please complete the following information):**
 - OS. OSX
- Node: v8.11.4
- NPM: 6.4.1

installation location:
```
$ which amplify
/Users/dan/.nvm/versions/node/v8.11.4/bin/amplify
```

**Comment by UnleashedMind** [comment]
@danfrost I was not able to reproduce this bug. 
could you check if the package @babel/types exists in the node_models folder of your @aws-amplify/cli installation?

**Comment by danfrost** [comment]
It doesn't. 

```
➜ which amplify
/Users/dan/.nvm/versions/node/v8.11.4/bin/amplify
```

```
$ ls -1 /Users/dan/.nvm/versions/node/v8.11.4/lib/node_modules/@aws-amplify/cli/node_modules/
amplify-category-analytics
amplify-category-api
amplify-category-auth
amplify-category-function
amplify-category-hosting
amplify-category-interactions
amplify-category-notifications
amplify-category-storage
amplify-category-xr
amplify-codegen
amplify-frontend-android
amplify-frontend-ios
amplify-frontend-javascript
amplify-provider-awscloudformation
babel-core
cfonts
chalk
eslint
folder-hash
fs-extra
gluegun
ini
inquirer
lodash
moment
open-in-editor
optionator
ora
promise-sequential
util
which
```

Is that what you needed?

**Comment by aknigam** [comment]
I am also facing the exact same issue:

    OS. OSX
    Node: v11.12.0
    NPM: 6.7.0

**Comment by aknigam** [comment]
I upgraded the npm version to 6.9.0. This resolved my issue.

**Comment by danfrost** [comment]
Did upgrade and reinstall but it's still not working for me.

```
$ npm uninstall @aws-amplify/cli -g --save
$ node --version                 
v10.15.3
$  npm --version
6.9.0
$ amplify
/Users/dan/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Cannot find module 'babel-types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dan/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/amplify-graphql-types-generator/lib/flow-modern/helpers.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

And:

```
$ ls -1 /Users/dan/.nvm/versions/node/v10.15.3/lib/node_modules/@aws-amplify/cli/node_modules
amplify-category-analytics
amplify-category-api
amplify-category-auth
amplify-category-function
amplify-category-hosting
amplify-category-interactions
amplify-category-notifications
amplify-category-storage
amplify-category-xr
amplify-codegen
amplify-frontend-android
amplify-frontend-ios
amplify-frontend-javascript
amplify-provider-awscloudformation
babel-core
cfonts
chalk
eslint
folder-hash
fs-extra
gluegun
ini
inquirer
lodash
moment
open-in-editor
optionator
ora
promise-sequential
util
which
```

**Comment by danfrost** [comment]
I did 

```
npm install -g babel-types
```

And now it works. Hope that helps.

**Comment by danfrost** [comment]
I also had to do
```
npm install -g cloudform-types
```
to get it to work. This is working for me now, but these seem like dependencies to put in the package, not manually install. Hope that helps.

**Comment by kaustavghosh06** [comment]
@danfrost We're not able to reproduce this issue as a team.
As a suggestion, I would recommend you to `npm uninstall -g @aws-amplify/cli` and then `npm install -g @aws-amplify/cli` to make this work for future versions of the CLI.

**Comment by YashYash** [comment]
Still seeing this issue. I installed babel-types and still no luck. I uninstalled and re-installed and still no luck.

node 
v8.15.1
npm 
6.4.1

➜  client amplify configure
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/flow-modern/codeGeneration.js:1
Error: Cannot find module '@babel/types'
Require stack:
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/flow-modern/codeGeneration.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/flow-modern/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/generate.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/add.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/module-loader.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/loaders/command-loader.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/runtime.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/domain/builder.js
- /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js
- /usr/local/lib/node_modules/@aws-amplify/cli/src/cli.js
- /usr/local/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/lib/flow-modern/codeGeneration.js:3:11)

**Comment by YashYash** [comment]
A quick update. Me and my friends have tried this on 3 computers now lol. Same issue. Amplify is installed successfully but we still no able to run any amplify commands since it is unable to find Error: Cannot find module '@babel/types'. We would love to give amplify a shot, but it looks like it's not going to be happening any time soon. You can see the stacktrace above. Coming from flow-modern/codeGeneration.js.

**Comment by kaustavghosh06** [comment]
@YashYash Did you upgrade to npm version 6.9.0?
