### ISSUE TITLE
EACCES Error on every command

### ISSUE THREAD

**Issue by aoh-escape** [aws-amplify/amplify-cli#12681]
### How did you install the Amplify CLI?

sudo npm install -g @aws-amplify/cli --unsafe-perm=true

### If applicable, what version of Node.js are you using?

20.1.0

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Not that I know of

### Describe the bug

Any command that starts with `Amplify` results in an error.
For example: `amplify configure` results in:
`EACCES: permission denied`

I also could not install amplify without sudo, as I would get this error:
`Error: Amplify CLI failed to install. Check your internet connection and try again`

### Expected behavior

I would like to run amplify configure and set up my environment

### Reproduction steps

`amplify configure`

### Log output

<details>

```
# Put your logs below this line
zsh: no such file or directory: issue-date

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @aoh-escape, 👋 thank you for reaching out. This appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/11615. 
If you are experiencing EACCESS issues installing global packages, please refer to the [npm documentation](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).
Alternatively you can assume ownership over the folders created in your home directory but owned by root (`chown -R ~/.amplify`)
