### ISSUE TITLE
S3 bucket for Storage not removed when removing environment

### ISSUE THREAD

**Issue by wbroek** [aws-amplify/amplify-cli#1269]
**Describe the bug**
When remove an environment and later adding one with same name (scenario is like create a dev environment, doing work on it. Removing the dev environment when work is finished, create a dev environment again for dev work) it fails because of existingt S3 bucket.

```
Following resources failed

Resource Name: S3Bucket (AWS::S3::Bucket)
Event Type: create
Reason: synappz-synappz dev already exists
```

**To Reproduce**
1. amplify env add synappzdev
2. amplify env remove synappzdev
3. amplify env add synappzdev

**Expected behavior**
When removing an environment the S3 buckets should be removed

**Comment by UnleashedMind** [comment]
@wbroek 
What is the version of the amplify-cli that you are using? 
execute `amplify -v` to find out. 
The latest amplify does not have this bug.

**Comment by wbroek** [comment]
@UnleashedMind thanks for the response, forgot to mention but working on version 1.6.1 and it happend again yesterday (the S3 bucket was still there)

**Comment by UnleashedMind** [comment]
What categories did you add to the environment?

**Comment by wbroek** [comment]
Below is my environment (with status)

Current Environment: um

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | ummmauth      | No Change | awscloudformation |
| Storage  | ummm          | No Change | awscloudformation |
| Api      | ummmgraphql   | No Change | awscloudformation |
| Api      | userapi       | No Change | awscloudformation |
| Function | userman       | No Change | awscloudformation |

**Comment by kaustavghosh06** [comment]
@wbroek `amplify delete` does not delete the S3 bucket right now but we're working on a feture to make this possible on a delete command. For now, you would have to delete the S3 bucket manually using the AWS console and then run `amplify push` again to prevent the Cloudformation error.

**Comment by wbroek** [comment]
Thank you for the response @kaustavghosh06 Know what to do for now

**Comment by deepaksingh007** [comment]
@kaustavghosh06  any update on this bug , I have the latest version of amplify and still getting the same error. Thanks

**Comment by cfbo** [comment]
This is still happening. Any news?

**Comment by PatrykMilewski** [comment]
It's also not working for me. Any plans to fix that? Using `--force` doesn't really help

**Comment by josefaidt** [comment]
Closing as this issue has been resolved since this issue was originally opened. If you are still experiencing this issue please [create a new issue](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml).
