### ISSUE TITLE
Update login to add social login using CLI

### ISSUE THREAD

**Issue by vinayChieve** [aws-amplify/amplify-cli#12694]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no manual changes made

### Describe the bug

When I run the command "update auth" and add the "Apply default configuration with Social Provider (Federation)", then I fill out the redirect urls. But when I get to the select social provider option, I get errors like :"Google (Your UserPool is configured to require preferred_username, which cannot be retrieved from Google)".I cannot reset my login schema because we already are live and have over 250 users. I also tried to use the studio and add the option from there, but the deployment failed.

### Expected behavior

I expected to follow the documentation steps for adding social login to work as shown, but I was not seeing the same input options as the ones shown in the documentation. 

### Reproduction steps

1. deploy signup/login auth scheme with email and preferred username as the first login methods. 
2. try to add the social login

### Project Identifier

[report-1685126915911.zip](https://github.com/aws-amplify/amplify-cli/files/11578985/report-1685126915911.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by lazpavel** [comment]
Hi @vinayChieve, we do not support `preferred_username` (aka `forceAliasAttributes: true` feature flag) with social providers. You can try the workaround mentioned in this comment: https://github.com/aws-amplify/amplify-cli/issues/9307#issuecomment-1031913881

**Comment by vinayChieve** [comment]
Hey, Thanks for the reference. A few things before I try that, since I already added the email and preferred_username login method, and have about 270 users already signed up, should I skip step 2? I cannot create a new app and also cannot lose or reset the user data we already have up.

**Comment by lazpavel** [comment]
@vinayChieve, yes, you should be able to just jump to step 3 from that workaround

**Comment by vinayChieve** [comment]
@josefaidt no, but the support team on Aws console was able to find a solution. Waiting to implement once all is worked out on their end.
