### ISSUE TITLE
The projection key is missing from dynamodb cli input

### ISSUE THREAD

**Issue by HarishTeens** [aws-amplify/amplify-cli#12691]
### The CLI type interface
https://github.com/aws-amplify/amplify-cli/blob/b01aa4baf90d6426bbcd4ef9c5603a3ea697c09c/packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthrough-types/dynamoDB-user-input-types.ts#L31

### The part where its hardcoded
https://github.com/aws-amplify/amplify-cli/blob/b01aa4baf90d6426bbcd4ef9c5603a3ea697c09c/packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-builder.ts#L119

Could someone please look into it?

**Comment by josefaidt** [comment]
Hey @HarishTeens :wave: thanks for raising this! Would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml)? This will help us gather additional context around the issue you are experiencing

**Comment by HarishTeens** [comment]
closing this PR. 
Created a new one with the appropriate template, New PR: https://github.com/aws-amplify/amplify-cli/issues/12709
