### ISSUE TITLE
Unable to checkout environment.

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-cli#12706]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.2

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I have several environments. When I try to checkout any of them, I get...

```
✖ Fetching updates to backend environment: qathree from the cloud.
✖ There was an error initializing your environment.
🛑 Packaging overrides failed.
Command failed with exit code 1: yarn install
warning package.json: No license field
warning overrides-for-auth-resource@1.0.0: No license field
error constructs@3.4.311: The engine "node" is incompatible with this module. Expected version ">= 16.14.0". Got "14.17.2"
error Found incompatible module.
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I deleted the amplify folder and tried to pull using amplify pull --appId xxxxxxx --envName qathree.

### Expected behavior

I would expect to be able to check out an environment. 

### Reproduction steps

Idk. It has been working up until now.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @LeoReubelt :wave: thanks for raising this! The error is coming from an unsatisfied engine requirement from the AWS CDK `constructs` package https://github.com/aws/constructs/blob/10.x/package.json#L73

More information on the `engines` key can be found here https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

In short, this is a mechanism to ensure the Node.js version used locally satisfies to the Node.js version constraints required by the package developer.

Can you try upgrading your node version locally to 16+?

**Comment by LeoReubelt** [comment]
thanks @josefaidt .  yeah, that works. thanks. what i don't understand is why it suddenly stopped working. is it related to upgrading the cli version? and we have no constructs package. so how can i tell what package is causing this?

**Comment by josefaidt** [comment]
Hey @LeoReubelt this will be installed in CDK custom resources and is a transient dependency for the overrides packages (in `amplify/backend/package.json`):

```json
{
  "name": "custom-resource",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@aws-amplify/cli-extensibility-helper": "^3.0.0",
    "aws-cdk-lib": "~2.68.0",
    "constructs": "^10.0.5"
  },
  "devDependencies": {
    "typescript": "^4.2.4"
  }
}
```

> is it related to upgrading the cli version?

This change was made to the constructs package ~3 weeks ago https://github.com/aws/constructs/commit/0b92b9a3ce866683aac5ddc571938a905ef7404b and appeared in v10.2.37

**Comment by LeoReubelt** [comment]
thanks.
