### ISSUE TITLE
Understanding the amplify-meta.json file

### ISSUE THREAD

**Issue by lindanip** [aws-amplify/amplify-cli#12719]
### Amplify CLI Version

11.1.0

### Question

Hey there

Im struggling with this error:
**amplify-meta.json' does not exist**
It seems every time I run amplify pull its not getting generated.
What do I need commands do I need to run when I clone my Github project on different machine or even on a remote machine through a script?

**Comment by ykethan** [comment]
Hey @lindanip, 👋 thank you for reaching out. This message normally occurs on project that has not been init'd `amplify init`.  
Does the repository contain `amplify/team-provider-info.json` file? 
If this a fresh clone of your project, you may need to run `amplify init`.

Could you reopen the issue with the bug template as this would enable us in collecting additional information such as reproduction steps and environment.

**Comment by lindanip** [comment]
So this is the script I've been trying to run on a remote server where the app apk file will be built, but its not generating the required files. the installation of amplify and AWS cli are successful

`#!/bin/bash

npm install -g @aws-amplify/cli
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
aws configure set aws_access_key_id $AWS_ACCESS_KEY
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region us-west-2
aws configure set default.output json
amplify init -y
amplify pull --appId <app-id> --envName dev
`

**Comment by ykethan** [comment]
Hey @lindanip, thank you for the information. From error message provided the issue occurs when passing a name of the project which does not meet the naming constraint `name must be between 2 and 10 characters, and lowercase only.`. when running `amplify init -y` the Amplify cli will refer to the present folder name and create the Amplify project with the name. To verify if the name may be causing this issue could you try creating a new folder with a longer name and lowercase only, then change directory to the folder and run `amplify init -y`. 

Additionally, this issue also occurs when running a init in project that have `amplify` and `amplify-backup` folder present from a previous failed pull or init.

I observed that you are pulling in a existing Amplify backend in the script. If the intention is to pull a existing project automatically using the script. After the configure step run we should be able to run  `amplify pull --appId <app-id> --envName dev -y` for Amplify CLI to generate the required files.

It would be great if you could provide some additional information on use case for the script.

**Comment by lindanip** [comment]
Hey, So my use case

I have an expo managed app that uses the amplify for auth and a post confirmation function.

Im using EAS (Expo application service), to build my app with `eas build`  but the build fails on the amplify configurations.

Im trying to configure amplify on `eas-build-pre-install` in the `package.json` with the script above.

e.g `"eas-build-pre-install": "sh ./scripts/eas_pre_build.sh",` 
note:  `/scripts/eas_pre_build.sh` this file contains the script`

So all I need for amplify to generate the required files so the app can finally build, its been weeks and Im still struggling, its really frustrating and this app is supposed to test by investors this week, everything else is working just the one problem , we've went through the docs over and over and we don't find any light.



Right now I'm struggling with a new error:

the command that cause it: `aws configure set default.output json --profile <aws-profile-name>`

the result:
```
`Could not initialize platform for 'dev': Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
Resolution: Review the error message and stack trace for additional information`
```

**Comment by lindanip** [comment]
> Hey, So my use case
> 
> I have an expo managed app that uses the amplify for auth and a post confirmation function.
> 
> Im using EAS (Expo application service), to build my app with `eas build` but the build fails on the amplify configurations.
> 
> Im trying to configure amplify on `eas-build-pre-install` in the `package.json` with the script above.
> 
> e.g `"eas-build-pre-install": "sh ./scripts/eas_pre_build.sh",` note: `/scripts/eas_pre_build.sh` this file contains the script`
> 
> So all I need for amplify to generate the required files so the app can finally build, its been weeks and Im still struggling, its really frustrating and this app is supposed to test by investors this week, everything else is working just the one problem , we've went through the docs over and over and we don't find any light.
> 
> Right now I'm struggling with a new error:
> 
> the command that cause it: `aws configure set default.output json --profile <aws-profile-name>`
> 
> the result:
> 
> ```
> `Could not initialize platform for 'dev': Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
> Resolution: Review the error message and stack trace for additional information`
> ```


Kindly assist

**Comment by ykethan** [comment]
Hey @lindanip, could you check the `amplify` -> `.config` -> `local-aws-info.json` which should be contain the attribute `profileName`. Could check if the profile name in the file and the profile name being set on aws configure match.

**Comment by lindanip** [comment]
Hey @ykethan,

I wanted to update you on the progress we've made regarding the issues we were facing. It seems that we have found a solution by using the script provided in the documentation (https://docs.amplify.aws/cli/usage/headless/#amplify-pull-parameters). Additionally, we decided to keep the AWS profile set to default.

Here's the script we used:

`
#!/bin/bash
set -e
IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"headlessaccesskeyid\",\
\"secretAccessKey\":\"headlesssecrectaccesskey\",\
\"region\":\"us-east-1\"\
}"
AMPLIFY="{\
\"projectName\":\"headlessProjectName\",\
\"appId\":\"amplifyServiceProjectAppId\",\
\"envName\":\"myenvname\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
`

We're grateful for your assistance throughout this process. Thank you very much.

**Comment by ykethan** [comment]
Hey @lindanip, glad to hear I was able to assist you. Do let us know if you require any further assistance.
