### ISSUE TITLE
Amplify push indicates one update, deletes all resources

### ISSUE THREAD

**Issue by onelittleant** [aws-amplify/amplify-cli#12717]
### How did you install the Amplify CLI?

npm install -g @aws/amplify-cli

### If applicable, what version of Node.js are you using?

v18.13.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Updated s3 bucket to allow public viewing.

### Describe the bug

I upgraded to the 12.0.3 cli to take advantage of the _deleted field in GraphQL filters.  I also added an API override to authentication to require admins for user creation:

/amplify/backend/auth/foundation/override.ts
`import {
  AmplifyAuthCognitoStackTemplate,
  AmplifyProjectInfo,
} from "@aws-amplify/cli-extensibility-helper";

export function override(
  resources: AmplifyAuthCognitoStackTemplate,
  amplifyProjectInfo: AmplifyProjectInfo
) {
  resources.userPool &&
    (resources.userPool.adminCreateUserConfig = {
      allowAdminCreateUserOnly: true,
    });
}`

Amplify status indicated an update to auth.  Amplify push then DELETED most of the PRODUCTION resources.  I cannot describe my shock.  We were setting up this production environment and had not moved any clients onto it.  I am mortified.  I don't know what happened, Amplify indicated a simple update and instead deleted my application.  I was unable to terminate the update once I saw the deletions happening.

### Expected behavior

The authentication update should have been deployed without issue.

### Reproduction steps

I do not know how to recreate this issue.

### Log output

<details>

```
# Put your logs below this line
amplify push
⠏ Building resource api/foundation✅ GraphQL schema compiled successfully.

Edit your schema at //amplify/backend/api/foundation/schema.graphql or place .graphql files in a directory at //amplify/backend/api/foundation/schema
✔ Successfully pulled backend environment production from the cloud.

    Current Environment: production
    
┌──────────┬─────────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name               │ Operation │ Provider plugin   │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ foundation                  │ Update    │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api      │ foundation                  │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ userPoolGroups              │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function │ S3Trigger6e0f618a           │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Storage  │ s3foundationstorage8557b4f8 │ No Change │ awscloudformation │
└──────────┴─────────────────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes

⚠️ 
We detected that you are using CDK v1 with custom stacks and overrides.AWS CDK v1 has entered maintenance mode on June 1, 2022

Impacted Files:

 - //sync/amplify/backend/package.json
Upgrade '@aws-amplify/cli-extensibility-helper' to latest version ^3.0.0

? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes

Deploying resources into production environment. This will take a few minutes. ⠹
Deploying resources into production environment. This will take a few minutes. ⠦
Deployment completed.
Deployed root stack foundation [ ======================================== ] 6/6
        amplify-foundation-production… AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Jun 01 2023 11:28:45…     
        authfoundation                 AWS::CloudFormation::Stack     UPDATE_COMPLETE                Thu Jun 01 2023 11:13:59…     
        apifoundation                  AWS::CloudFormation::Stack     DELETE_COMPLETE                Thu Jun 01 2023 11:28:44…     
        functionS3Trigger6e0f618a      AWS::CloudFormation::Stack     DELETE_COMPLETE                Thu Jun 01 2023 11:14:27…     
        storages3foundationstorage855… AWS::CloudFormation::Stack     DELETE_COMPLETE                Thu Jun 01 2023 11:14:16…     
        authuserPoolGroups             AWS::CloudFormation::Stack     DELETE_COMPLETE                Thu Jun 01 2023 11:14:39…     
Deployed auth foundation [ ======================================== ] 10/10
Deployed auth userPoolGroups [ ======================================== ] 8/8
        RoleMapFunctionInput           Custom::LambdaCallout          DELETE_COMPLETE                Thu Jun 01 2023 11:14:23…     
        adminGroup                     AWS::Cognito::UserPoolGroup    DELETE_COMPLETE                Thu Jun 01 2023 11:14:21…     
        LambdaCloudWatchPolicy         AWS::IAM::Policy               DELETE_COMPLETE                Thu Jun 01 2023 11:14:21…     
        syncGroup                      AWS::Cognito::UserPoolGroup    DELETE_COMPLETE                Thu Jun 01 2023 11:14:21…     
        syncGroupRole                  AWS::IAM::Role                 DELETE_COMPLETE                Thu Jun 01 2023 11:14:24…     
        adminGroupRole                 AWS::IAM::Role                 DELETE_COMPLETE                Thu Jun 01 2023 11:14:24…     
        RoleMapFunction                AWS::Lambda::Function          DELETE_COMPLETE                Thu Jun 01 2023 11:14:30…     

✔ Generated GraphQL operations successfully and saved at src/graphql
✅ GraphQL schema compiled successfully.

Edit your schema at //amplify/backend/api/foundation/schema.graphql or place .graphql files in a directory at //amplify/backend/api/foundation/schema
Successfully generated models. Generated models can be found in //src
✔ Code generated successfully and saved in file src/API.ts
Deployment state saved successfully.

GraphQL transformer version: 2

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✅ GraphQL schema compiled successfully.

Edit your schema at //amplify/backend/api/foundation/schema.graphql or place .graphql files in a directory at //amplify/backend/api/foundation/schema
✔ Synced UI components.
ned@ola-xps:~/$ amplify status

    Current Environment: production
    
┌──────────┬─────────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name               │ Operation │ Provider plugin   │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Api      │ foundation                  │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ foundation                  │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Auth     │ userPoolGroups              │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Function │ S3Trigger6e0f618a           │ No Change │ awscloudformation │
├──────────┼─────────────────────────────┼───────────┼───────────────────┤
│ Storage  │ s3foundationstorage8557b4f8 │ No Change │ awscloudformation │
└──────────┴─────────────────────────────┴───────────┴───────────────────┘

GraphQL endpoint: https://xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: xxxxxxxxxx

GraphQL transformer version: 2



```

</details>

### Additional information

I am not sure how to recreate this.  I'm afraid to push to any environments for fear of losing them.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by onelittleant** [comment]
Project Identifier: 239bc73782c8a4000aab8227c5ceb93c

1. Upgraded from 11.x, not sure exactly which.
2. I did not make any changes to the graphql filters myself.  I upgraded to the 12.0.3 cli because it added support for the _deleted field in the auto-generated graphql filters.

**Comment by kuhlmanp** [comment]
Thanks for those answers. Lastly, can you zip up your project directory and send it to amplify-cli@amazon.com so we can take a look?

**Comment by onelittleant** [comment]
Thank you.  I sent the file.  It is a .tar.gz but I had to rename it so that Gmail would allow me to send.

**Comment by onelittleant** [comment]
As an update, it looks like I upgraded the cli from 10.6.2 to 12.0.3

**Comment by kuhlmanp** [comment]
Hey, I just wanted to let you know that we are still looking into this. This morning a colleague and I attempted to rebuild your project using 10.6.2 and followed the instructions above to update to 12.0.3 but we didn't find the deletions on push.

If there's any other details you can provide or any other chronological steps we'd love to hear them. Until then we're continuing to explore the possibilities.

**Comment by onelittleant** [comment]
Thank you so much for looking into this.  I had to push --force to re-create the deleted resources.  The s3 bucket was somehow detached from the project and had to be manually deleted in order to get the push to go through.  On that push however the userPoolGroups resources were deleted!  Another push --force and they were created again.  I have since tried pushing/pulling with 10.6.2 and 12.0.3 and also variants of cli-extensibility-helper ^2.4.4 and ^3.0.0.  I have not been able to reproduce the deletion behavior.  Is there a way to diff the amplify build cloud formation templates with the live stacks prior to making a push for a santity check?

**Comment by kuhlmanp** [comment]
Apologies for the delayed response. The status displayed when using `amplify status` and when doing `amplify push` is supposed to reflect the differences that are about to be produced. In your specific case, we don't know why the status said there was no change and and then it reported resources were being deleted. Based on our attempts to repro and the data contained in the information you sent us, the messages displayed in your included logs are confusing.

**Comment by onelittleant** [comment]
Thank you for looking into this.  I am baffled.  It did happen just as those logs indicate.  I have not seen anything similar since I re-established the environment with push --force.  It would be nice to be able to see a more verbose diff of stacks during the push operation, down to the actual template diffs, though I don't know if that would have helped in this case.  I will certainly update this issue if I run into this again.

**Comment by ykethan** [comment]
Hey @onelittleant, wanted to provide some information on the verbose log provided on Amplify CLI. `amplify status --verbose` should provide a verbose output of the changes.  additionally, we can add a `--debug` flag to the ` amplify push` command to push in debug mode.

We will be closing the issue for now, please feel free in reaching out to us again and we would be happy in reopening this issue.
