### ISSUE TITLE
Run `go build` for Go Lambda functions on `amplify push`

### ISSUE THREAD

**Issue by michaelrios** [aws-amplify/amplify-cli#12720]
### Is this feature request related to a new or existing Amplify category?

function

### Is this related to another service?

Lambda, Go

### Describe the feature you'd like to request

Currently I have to run `go build` prior to running `amplify push` in order to have the binary pushed up in the zip to the lambda. The issue with this is this is when amplify push is run without the binary, the zip pushed up to the lambda does not have the binary, and this essentially breaks the lambda.

### Describe the solution you'd like

If when making the function using `amplify add function`, and Go has been selected as the runtime, one of the config files should have a default build command set to be something very simple like `GOOS=linux GOARCH=amd64 go build main.go` to ensure the binary is cross compiled for the lambda cpu/os.

### Describe alternatives you've considered

As very helpfully been suggested in the most recent office hours, I am using a `pre-push.sh` hook to run the build command. This is working, but as I add more Go lambdas, this could become cumbersome. This is also something anyone else new to amplify and trying to use Go (or any other compiled language), will get tripped up by.

At the very least this solution should be added to the documentation within the `amplify add function` doc, to help future devs in this situation.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @michaelrios, 👋 thank you for reaching out. On diving into the repository I observed Amplify should build Go lambda functions on a push.
https://github.com/aws-amplify/amplify-cli/blob/65d11e9311f09e4759c5e016d8678d14e3f114d1/packages/amplify-go-function-runtime-provider/src/runtime.ts#LL69C120-L69C120

Could you provide us some information on the local installed Go version and how the lambda function is currently configured?

**Comment by michaelrios** [comment]
I am running `go1.20.4`

Wasn't sure what aspect of the config would be useful, so I put the whole cloud formation template below.

I just ran `amplify push` again without the pre-push hook, and the binary did not get built with my current setup.

<details><summary>Details</summary>
<p>

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "{\"createdOn\":\"Mac\",\"createdBy\":\"Amplify\",\"createdWith\":\"11.1.1\",\"stackType\":\"function-Lambda\",\"metadata\":{}}",
  "Parameters": {
    "CloudWatchRule": {
      "Type": "String",
      "Default": "NONE",
      "Description": " Schedule Expression"
    },
    "deploymentBucketName": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
    "apiparentcubbyGraphQLAPIIdOutput": {
      "Type": "String",
      "Default": "apiparentcubbyGraphQLAPIIdOutput"
    },
    "apiparentcubbyGraphQLAPIEndpointOutput": {
      "Type": "String",
      "Default": "apiparentcubbyGraphQLAPIEndpointOutput"
    },
    "storagemsgmediaBucketName": {
      "Type": "String",
      "Default": "storagemsgmediaBucketName"
    }
  },
  "Conditions": {
    "ShouldNotCreateEnvResources": {
      "Fn::Equals": [
        {
          "Ref": "env"
        },
        "NONE"
      ]
    }
  },
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
        },
        "Handler": "main",
        "FunctionName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "parentcubby4d9d534cVideoProcessing",
            {
              "Fn::Join": [
                "",
                [
                  "parentcubby4d9d534cVideoProcessing",
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
        "Environment": {
          "Variables": {
            "ENV": {
              "Ref": "env"
            },
            "REGION": {
              "Ref": "AWS::Region"
            },
            "API_PARENTCUBBY_GRAPHQLAPIIDOUTPUT": {
              "Ref": "apiparentcubbyGraphQLAPIIdOutput"
            },
            "API_PARENTCUBBY_GRAPHQLAPIENDPOINTOUTPUT": {
              "Ref": "apiparentcubbyGraphQLAPIEndpointOutput"
            },
            "STORAGE_MSGMEDIA_BUCKETNAME": {
              "Ref": "storagemsgmediaBucketName"
            },
            "API_PARENTCUBBY_MESSAGETABLE_NAME": {
              "Fn::ImportValue": {
                "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:Name"
              }
            },
            "API_PARENTCUBBY_MESSAGETABLE_ARN": {
              "Fn::Join": [
                "",
                [
                  "arn:aws:dynamodb:",
                  {
                    "Ref": "AWS::Region"
                  },
                  ":",
                  {
                    "Ref": "AWS::AccountId"
                  },
                  ":table/",
                  {
                    "Fn::ImportValue": {
                      "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:Name"
                    }
                  }
                ]
              ]
            }
          }
        },
        "Role": {
          "Fn::GetAtt": [
            "LambdaExecutionRole",
            "Arn"
          ]
        },
        "Runtime": "go1.x",
        "Layers": [
          "arn:aws:lambda:us-east-1:441676138820:layer:parentcubby-ffmpeg:1"
        ],
        "Timeout": 300,
        "MemorySize": 3008
      }
    },
    "LambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::If": [
            "ShouldNotCreateEnvResources",
            "parentcubbyLambdaRolecf8aa22c",
            {
              "Fn::Join": [
                "",
                [
                  "parentcubbyLambdaRolecf8aa22c",
                  "-",
                  {
                    "Ref": "env"
                  }
                ]
              ]
            }
          ]
        },
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        }
      }
    },
    "lambdaexecutionpolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
                  {
                    "region": {
                      "Ref": "AWS::Region"
                    },
                    "account": {
                      "Ref": "AWS::AccountId"
                    },
                    "lambda": {
                      "Ref": "LambdaFunction"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    },
    "AmplifyResourcesPolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "appsync:GraphQL"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apiparentcubbyGraphQLAPIIdOutput"
                      },
                      "/types/Query/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apiparentcubbyGraphQLAPIIdOutput"
                      },
                      "/types/Mutation/*"
                    ]
                  ]
                }
              ]
            },
            {
              "Effect": "Allow",
              "Action": "s3:ListBucket",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:s3:::",
                      {
                        "Ref": "storagemsgmediaBucketName"
                      }
                    ]
                  ]
                }
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:PutObject",
                "s3:GetObject"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:s3:::",
                      {
                        "Ref": "storagemsgmediaBucketName"
                      },
                      "/*"
                    ]
                  ]
                }
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "dynamodb:Get*",
                "dynamodb:BatchGetItem",
                "dynamodb:List*",
                "dynamodb:Describe*",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:Update*",
                "dynamodb:RestoreTable*"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:dynamodb:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":table/",
                      {
                        "Fn::ImportValue": {
                          "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:Name"
                        }
                      }
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:dynamodb:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":table/",
                      {
                        "Fn::ImportValue": {
                          "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:Name"
                        }
                      },
                      "/index/*"
                    ]
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "LambdaTriggerPolicyMessage": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy-Message",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:ListStreams"
              ],
              "Resource": {
                "Fn::ImportValue": {
                  "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:StreamArn"
                }
              }
            }
          ]
        }
      }
    },
    "LambdaEventSourceMappingMessage": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": [
        "LambdaTriggerPolicyMessage",
        "LambdaExecutionRole"
      ],
      "Properties": {
        "BatchSize": 100,
        "Enabled": true,
        "EventSourceArn": {
          "Fn::ImportValue": {
            "Fn::Sub": "${apiparentcubbyGraphQLAPIIdOutput}:GetAtt:MessageTable:StreamArn"
          }
        },
        "FunctionName": {
          "Fn::GetAtt": [
            "LambdaFunction",
            "Arn"
          ]
        },
        "StartingPosition": "LATEST"
      }
    }
  },
  "Outputs": {
    "Name": {
      "Value": {
        "Ref": "LambdaFunction"
      }
    },
    "Arn": {
      "Value": {
        "Fn::GetAtt": [
          "LambdaFunction",
          "Arn"
        ]
      }
    },
    "Region": {
      "Value": {
        "Ref": "AWS::Region"
      }
    },
    "LambdaExecutionRole": {
      "Value": {
        "Ref": "LambdaExecutionRole"
      }
    },
    "LambdaExecutionRoleArn": {
      "Value": {
        "Fn::GetAtt": [
          "LambdaExecutionRole",
          "Arn"
        ]
      }
    }
  }
}

</p>
</details>

**Comment by ykethan** [comment]
Hey @michaelrios, thank you for information. tried reproducing the issue using the following steps.

1. Installed go version 
```
❯ go version
go version go1.20.4 darwin/arm64

```
2. Created a go function as a kenesis stream trigger and added permissions to API and DynamoDB resource. 
3. Then ran push with a debug on the Amplify dev cli and observed the build command being invoked.
I did not observe any error and observed the bin file being populated. 

Could you provide is the full error message/stack trace being displayed by the Amplify CLI?
what is the local version of Amplify CLI version and OS being utilized?

**Comment by michaelrios** [comment]
Thanks for following up @ykethan 
I get no error message, it just doesn't build the binary, and keeps going as if it did. I am currently running `amplify version 11.1.1`, and I am on MacOS 13.3.1

Is there something I might be missing in a config that would be needed to run the build command, or is it solely based on the runtime being set to go1.x?

**Comment by ykethan** [comment]
Hey @michaelrios, thank you for the information. Could you try upgrading to the latest version of the Amplify CLI the making a empty change on the function and the run `amplify push --debug`. 
Could you also confirm if the `go.mod` file is tied to 1.20?

**Comment by ykethan** [comment]
Hey @michaelrios, checking back in. By any chance was this empty function being deployed was an error on cloudformation push?

If yes, the reproduction steps I utilized are as follows.

1. amplify init
2. amplify add function -> add lambda function - example: nodejs
3. amplify push
4. then add a empty line in nodeJs function (amplify status should show as update on the function)
5. amplify add function -> then create a go function (amplify status should show one update and one create on the functions)
6. then amplify push

<img width="845" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/87995712/3a0d1168-f157-430d-8fb5-efbf3909ec03">

**Comment by lazpavel** [comment]
This issue should be fixed in 12.1.1
