### ISSUE TITLE
amplify delete should provide the ability to delete a single environment

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1275]
**Is your feature request related to a problem? Please describe.**
Amplify delete provides no way to tear down a single environment.  If I want to tear down one environment and I have multiple, amplify insists on tearing them all down.

**Describe the solution you'd like**
The ability to delete a single environment.  This seems so obvious I can't believe it's not a feature.

**Describe alternatives you've considered**
None

**Comment by et304383** [comment]
Closing this as I realized the amplify env command provides this.

**Comment by GeorgeBellTMH** [comment]
I believe it would be useful to be able to delete specific parts of an environment - for example delete DEV/API....right now you have to delete Auth which is annoying as all users get deleted...ideally we also 
have some way to delete API and retain the data somehow (backup to json?)....

**Comment by ultradox** [comment]
@et304383 please tell me how you managed to delete a single environment? I'm stuck in a rabbit hole... After setting up amplify multienv (dev and prod) and successfully pushing dev and prod to two seperate AWS accounts / environments, I tried tearing down the production environment.

`amplify --version` 1.5.3

```
$ amplify env checkout prod
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
2019-04-21T07:00:29.314Z - error: uncaughtException: Unexpected token export 

$ amplify status

Current Environment: prod

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | mymedkiwi       | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |

GraphQL endpoint: https://xxx.appsync-api.ap-southeast-2.amazonaws.com/graphql
GraphQL API KEY: xxx
Hosting endpoint: http://xxxx-hostingbucket-prod.s3-website-ap-southeast-2.amazonaws.com

$ amplify delete
? Are you sure you want to continue?(This would delete all the environments of the project from the cloud and wipe out all the local amplify r
esource files) Yes

Deleting env:dev

Deleting env:prod
⠴ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:dev

Stack with id mymedkiwi-xxx does not exist
```

**Comment by et304383** [comment]
```
amplify env remove
```

**Comment by kingarawana** [comment]
Is it normal that I still get the message:

`Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files)`

I had ran `amplify env remove dev`
