### ISSUE TITLE
No Amazon CloudFront and S3 hosting service is enabled

### ISSUE THREAD

**Issue by TheShareGroup** [aws-amplify/amplify-cli#12757]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.0.0

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I set up hosting to build/deploy on my dev branch using the AWS Amplify Web UI. Rather than Amplify hosting I need to use S3/Cloudfront so I attempted to change the settings via the command line by running the following command:

`amplify configure hosting`

I was then prompted to select the plugin module to execute. I selected "Amazon Cloudfront and S3" and was presented with the following error:

`🛑 No Amazon CloudFront and S3 hosting service is enabled.`

Note: I tried it on both my 'dev' and 'prod' environments with the same results.

### Expected behavior

I expect to be able to configure hosting for Cloudfront and S3

### Reproduction steps

1. Run the following command: `amplify configure hosting`

### Project Identifier

ac13ea3cf0fefac40d97d2b63e0a37bf

### Log output

<details>

```
# Put your logs below this line


2023-06-06T20:21:28.600Z|info : amplify configure hosting  
2023-06-06T20:21:28.639Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-06-06T20:21:41.834Z|error : No Amazon CloudFront and S3 hosting service is enabled.
UnknownFault: No Amazon CloudFront and S3 hosting service is enabled.

</details>


### Additional information

_No response_

### Before submitting, please confirm:


- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @TheShareGroup, 👋  thank you for reaching out. We will need to utilize the `amplify add hosting` to add `Amazon CloudFront and S3` to the project.

**Comment by TheShareGroup** [comment]
Adding the host first worked. thank you. I didn't think I needed to that since I had already done it in the UI but apparently not.  Glad its working now!

-Dan
________________________________

**Comment by ykethan** [comment]
Hey @TheShareGroup, glad i was able to assist you. 
Closing the issue. Please feel free in reaching out us again.
