### ISSUE TITLE
Using different parameters.json files in hosting backend

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1276]
** Which Category is your question related to? **
Hosting, CDN, backend Cloud Formation configuration files.

** What AWS Services are you utilizing? **
AWS CloudFront.

** Provide additional details e.g. code snippets **
Option to pass in custom CF template parameters.json file depending on environment.

**Comment by UnleashedMind** [comment]
@jarrettj 
Currently you can run 'amplify hosting configure' to configure different sections of the hosting service, including the CloudFront section, and those configuration changes are directly written into the template file.
And when you switch env, you are getting another set of resources. 
Can you be more specific on what configuration settings are you want to keep in the parameters file, and how should they depend on the env?

**Comment by jarrettj** [comment]
Hi,

Thanks for the response. 

I'm setting an alias for the CDN. Let's say my environments are example.com, develop-example.com, test-example.com. If we are allowed to use different parameter.json files, we would simple have a different value for each domain name. 

Let's say by default parameters.json is used. But first check if an environment specific parameters.json file exists. If we are on develop environment, check for develop-parameters.json. Hope that makes sense? It is more a nice to have.

My current solution is the following:
Added the following to parameter.json:
```
{
  domainName: "example.com"
}
```
Then I updated template.json:
```
"Conditions": {
...
  "IsProduction": {
      "Fn::Equals" : [ { "Ref": "env" }, "master" ]
  }
}
...
    "Properties": {
        "DistributionConfig": {
            "Aliases": [ {
              "Fn::If" : [
                "IsProduction",
                { "Ref": "domainName" },
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Ref": "env"
                      },
                      "-",
                      { "Ref": "domainName" }
                    ]
                  ]
                }
              ]
            } ],
...
```
Which yields the desired result, but it is pretty involved. Compared to having the value in the parameter.json file. If you know what I mean. Thanks.

Regards.

**Comment by artista7** [comment]
Hey @jarrettj did you find any answer?

**Comment by jarrettj** [comment]
That's the solution above. Added a domainName and then used it in the single parameters.json as above.

**Comment by MatteoInfi** [comment]
So currently there is no valid solution for this?

**Comment by kaustavghosh06** [comment]
@MatteoInfi You can do this based on what @jarrettj mentioned here - https://github.com/aws-amplify/amplify-cli/issues/1276#issuecomment-486581679
