### ISSUE TITLE
Tearing down enviornment does not delete pinpoint

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1278]
**Describe the bug**
Amplify creates pinpoint but does not delete it when tearing down.

**To Reproduce**
1. Create environment
2. Teardown environment

**Expected behavior**
Pinpoint app is gone.

**Comment by UnleashedMind** [comment]
@et304383 
Thanks for your feedbacks. 
This is a known issue, and we'll need to update the CLI to fix it.

**Comment by kaustavghosh06** [comment]
@UnleashedMind This issue is fixed in the latest version of the CLI.
