### ISSUE TITLE
AWS Amplify Cognito

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1279]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AWS Amplify

** What AWS Services are you utilizing? **
AWS Cognito
** Provide additional details e.g. code snippets **
When i do amplify add auth and doing manual configuration. I got these 2 options
User Sign-up, Sign-In, connected  with AWS IAM controls
User Sign-up, Sign-In only
What is difference between these 2 options can anyone explain in detail. Thanks

**Comment by haverchuck** [comment]
@achutkiran - The option 'User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)' will create both an Identity Pool and a Userpool.  The other option ('User Sign-Up & Sign-In only (Best used with a cloud API only)') will create only a Userpool.

**Comment by achutkiran** [comment]
@haverchuck if we are using amplify and not using identity providers do we need identity providers

**Comment by haverchuck** [comment]
@achutkiran -  You would need some sort of identity provider... so if you aren't using something like Google, you can use an identity pool.  You can also use both in tandem.
