### ISSUE TITLE
Dependency Issue regarding JDK 11, although JDK 11 is installed while amplify push

### ISSUE THREAD

**Issue by Urmi2107** [aws-amplify/amplify-cli#12816]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.20.0

### Amplify CLI Version

12.1.0

### What operating system are you using?

Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Not able to push the project. It's showing the following error:

Update JDK to >=11. Download link: https://amzn.to/2UUljp9
🛑 Missing required dependencies to package <function name>

Although java -version is shown as follows:
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-11.0.19.7.1 (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.19.7.1 (build 11.0.19+7-LTS, mixed mode)

### Expected behavior

We should be able to push the changes to the amplify

### Reproduction steps

1. Create a project with amplify init.
2. Added a API and corresponding lambda to connect to that API through amplify add api
3. Used a dependency that was created though maven using maven local() in build.gradle
4. After that, amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Urmi2107, 👋 thank you for reaching out. Could you try running `javac -version` does this return the same version as the `java -version`?

**Comment by Urmi2107** [comment]
@ykethan javac -version returns javac 1.7.0_321

**Comment by Urmi2107** [comment]
@ykethan Thank you. I changed javac version using "sudo alternatives --config javac" command. Now I am able to push the app. Thanks a lot.

**Comment by Urmi2107** [comment]
@ykethan Thank you. I changed javac version using "sudo alternatives --config javac" command. Now I am able to push the app. Thanks a lot.
