### ISSUE TITLE
Existing schema attributes cannot be modified or deleted after used amplify update auth 

### ISSUE THREAD

**Issue by JackDurden00** [aws-amplify/amplify-cli#12827]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v12.20.0

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

I can't push on AWS amplify because they need to update Auth because my version was too old.
I did amplify upate auth and after i did amplify push and i have this error:

Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)

### Expected behavior

push my backend with amplify push.

### Reproduction steps

Amplify update Auth
Amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @JackDurden00, 👋 thank you for reaching out. By any chance does the auth resource utilize any custom attributes?
similar to https://github.com/aws-amplify/amplify-cli/issues/9690

if yes, as suggested in https://github.com/aws-amplify/amplify-cli/issues/9690#issuecomment-1029420525 we will need to utilize `amplify override auth` to migrate the CFN templates.

**Comment by JackDurden00** [comment]
Hey, 

Thx for your answer and your time.

We use cognito AWS for the auth but i dont know if there are some custom attributes
I tried with to use amplify override auth but it doesn't work :( 

I have this error:

**Packaging overrides failed.**
Command failed with exit code 2: /Users/aymericvelozzo/Desktop/Mon MacBook/GIT/front/amplify/backend/node_modules/.bin/tsc --project /Users/aymericvelozzo/Desktop/Mon MacBook/GIT/front/amplify/backend/auth/front3ed64f01/build/tsconfig.resource.json
../override.ts(1,43): error TS2305: Module '"@aws-amplify/cli-extensibility-helper"' has no exported member 'AmplifyProjectInfo'.

**Comment by JackDurden00** [comment]
Ver  on my backend is

"dependencies": {
    "@aws-amplify/cli-extensibility-helper": "^2.3.0"
  },

**Comment by ykethan** [comment]
hey @JackDurden00, thank you for the information. It appears the project overrides utilize an older version of the `cli-extensibility-helper`. Please refer to the migration [documentation](https://docs.amplify.aws/cli/migration/aws-cdk-migration/) providing information on the upgrade.
essentially, for projects using `amplify overrides <category>` we need to upgrade `@aws-amplify/cli-extensibility-helper` to version `^3.0.0` in `amplify/backend/package.json`.
Could you try upgrading the version and then retry the override?

**Comment by JackDurden00** [comment]
i upgrad cli-extensibility-helper to 3.0.0 and the command amplify overrides auth worked.
 i had:
+ **add** cli-inputs.json
- **delete** front-cloudformation-template.yml
+ **add** override.ts
- **delete** parameters.json

i did **amplify push** and i have the same error:

_Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)_

**Comment by ykethan** [comment]
Hey @JackDurden00, were the auth custom attribute changes added to the `override.ts` file or the changes from the `front-cloudformation-template.yml` ported over to the `override.ts` file?
If no, we will need to re-add the auth custom attributes that you have previously configured on your Cognito user pool into `override.ts` file.
Please refer to https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-auth-resources providing an example on custom attributes.

**Comment by JackDurden00** [comment]
Oh thx, 
Its possible to send you front-cloudformation-template.yml because i'm not really sure what is the custom attribute that i need to use in override.ts ?

**Comment by JackDurden00** [comment]
my schema on template.yml:

 Schema:
        **_- Name: email
          Required: 'true'
          Mutable: 'true'
        - AttributeDataType: String
          Mutable: 'true'
          Name: lastSessionId
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'
        - AttributeDataType: String
          Mutable: 'true'
          Name: lastGuestId
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'
        - AttributeDataType: String
          Mutable: 'true'
          Name: lastGuideId
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'
        - AttributeDataType: String
          Mutable: 'true'
          Name: code
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'_**


i put just the attribute required: email
i had this line on my override:

  **resources.userPool.schema = [
    ...(resources.userPool.schema as any[]), //, // Carry over existing attributes (example: email)
    // myCustomAttribute,
  ];**


But always the same error when i push :(.

================================================

May be i need to put this syntaxe for the email ?
 const myCustomAttribute = {
    attributeDataType: 'String',
    mutable: true,
    name: 'email',
    required: true,
  }   ??



Can i send you my template.yml if i forgot some information ?

**Comment by ykethan** [comment]
Hey @JackDurden00, thank you for the information. yes we will need to add the remaining attributes as well. let me try and work on a reproduction and reach back here.

**Comment by ykethan** [comment]
Hey @JackDurden00, from the provided custom attributes  we will need to port them using the overrides functionality. Please refer to the construct and example as follows.

the user pool schema attributes:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html#cfn-cognito-userpool-schemaattribute-stringattributeconstraints

override.ts example:

```
  resources.userPool.schema = [
    ...(resources.userPool.schema as any[]), // Carry over existing attributes (example: email)
{
      attributeDataType: "String",
      mutable: true,
      name: "email",
      required: true,
 },    
{
      attributeDataType: "String",
      mutable: true,
      name: "code",
      required: false,
      stringAttributeConstraints: {
        maxLength: "256",
        minLength: "1",
      },
    },
...add remaining
  ];
```

**Comment by JackDurden00** [comment]
Hey,

It work !!!

just i deleted this object
    {
      attributeDataType: "String",
      mutable: true,
      name: "email",
      required: true,
    }

because i had this error
**Attribute names must be unique. Cannot use name - email**

email is already add with this : ...(resources.userPool.schema as any[])

Thx again for your time ^^

**Comment by JackDurden00** [comment]
Oh wait :(
 My local is broken now with a lot of error of my graph.

ex: Validation error of type FieldUndefined: Field 'disabled' in type 'Video' is undefined
strange because this field is not required and before its worked.

The change of the Auth change something on the graphQL ?

**Comment by ykethan** [comment]
Hey @JackDurden00, 

> Validation error of type FieldUndefined: Field 'disabled' in type 'Video' is undefined

does the GraphQL API utilize Datastore? 
The issues appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/9441 where the type was generated with a different casing.
could you try regenerating the types and provide us your schema with the type generated in the schema folder.
https://docs.amplify.aws/cli/graphql/client-code-generation/#amplify-codegen-statements

> Expected version ">= 16.14.0". Got "14.15.4" messaging

on installing a new node version, does restarting the the current terminal or opening a new terminal and then running the push command mitigate the message?

**Comment by JackDurden00** [comment]
I used amplify codegen (i see a change on backend-config-json)
File GraphDL: https://wetransfer.com/downloads/a1c72f2ae7ccdfb592a6ff544ebd435d20230623173009/849b98c8b328ee099a386a42a63db15820230623173039/ccc0ba?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Exemple of the prob with my graph:**
_Validation error of type FieldUndefined: Field 'audience' in type 'Session' is undefined @ 'listSessions/items/audience
Validation error of type FieldUndefined: Field 'disabled' in type 'Video' is undefined @ 'listVideos/items/disabled
Validation error of type FieldUndefined: Field 'password' in type 'Video' is undefined @ 'listVideos/items/password'
Validation error of type FieldUndefined: Field 'contentVideo' in type 'videoDynamicButton' is undefined @ 'listVideos/items/dynamicButtons/content_

NodeJs
i try everything restart my terminal, my mac , try to install with another command line for have nodejs 16.14.0
But my project told me that i'm on 16.14.0 but always the same error with amplify push :(

**Comment by ykethan** [comment]
@JackDurden00 could you run `amplify diagnose --send-report` and provide us the project identifier here.
https://docs.amplify.aws/cli/reference/diagnose/

**Comment by JackDurden00** [comment]
Project Identifier: eae652572bcf8650b5456debac0ccc98

**Comment by ykethan** [comment]
@JackDurden00 could you run the following commands and retry the push. 
```
$ amplify codegen remove
$ amplify codegen add
```
then reselect the codegen options.

**Comment by JackDurden00** [comment]
Always the same error with node.
and with amplify init ?

**Comment by JackDurden00** [comment]
i try to recreate a new env but i have some other errors :(.
I have another urgence.

I'll recreate another ticket, I'll tag you on it if you want.

Thx a lot, i will be back on this problem

**Comment by josefaidt** [comment]
Hey @JackDurden00 what is the node error you're experiencing? Can you confirm you are on a recent node version by running `node -v`? Is this error coming from one of your project's Functions?

Additionally I saw a mention to Video. Are you using the 3p video plugin by chance or is this a type you have defined in your schema?

**Comment by JackDurden00** [comment]
May be ist a conflict on my package with my computer, i try to recreate a new env amplify and restart all.
But i have a problem when i created a new env.
I will create a new issue for that.

i think you can close this issue.
Thx for your help for override !

**Comment by josefaidt** [comment]
Hey @JackDurden00 sure, no worries! I'll close this issue for now
