### ISSUE TITLE
Amplify console saying stack with id ab-websites-20190415111215 does not exist, when it does.

### ISSUE THREAD

**Issue by steveoaustin** [aws-amplify/amplify-cli#1282]
**Describe the bug**
My amplify console build is failing with an amplify-cli based project. It is saying that the stack does not exist, when it actually does. I can go into the cloudformation console and find the root stack with exactly the same id. I'm confused about how I can resolve this issue.

I'm happy to provide build logs to someone - I can send to an email.

**To Reproduce**
1. Commit to a project to trigger a build
2. Read the build logs, noticing the failure

**Expected behavior**
Amplify builds the project

**Screenshots**
The relevant lines of the build error: 
![Screenshot (2)](https://user-images.githubusercontent.com/21183137/56161785-70952100-5f98-11e9-983d-31eb074ea677.png)

The corresponding stack (which exists, and is in a valid state):
![Screenshot (3)](https://user-images.githubusercontent.com/21183137/56161828-8d315900-5f98-11e9-8305-3479163a5eee.png)

**Comment by swaminator** [comment]
Can you check what region you are in the AMplify Console and CloudFormation? I suspect you have deployed projects in different regions.

**Comment by steveoaustin** [comment]
they are deployed in us-east-1

**Comment by hzhenmin** [comment]
Can you also check if the amplify project is also in us-east-1?

**Comment by swaminator** [comment]
@steveoaustin if they are in the same region, please share your app arn. Found in General > App settings

**Comment by swaminator** [comment]
@steveoaustin following up here: Please email your appARn to aws-amplify-customer@amazon.com

**Comment by kaustavghosh06** [comment]
@steveoaustin are you unblocked on this issue?
