### ISSUE TITLE
Amplify push operation blocked because User Pool could not be founded

### ISSUE THREAD

**Issue by fabel84** [aws-amplify/amplify-cli#12821]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dwyf5dew0s2ha

### Region

eu-central-1

### Environment name

tvinidev

### What operating system are you using?

Mac

### Browser type?

Chrome

### Describe the bug

I'm not able to push any changes on amplify using command line interface. When I'm trying to execute the command `amplify push`,I received after some operation this error message:

`🛑 The following resources failed to deploy:
Resource Name: UserPoolClient (AWS::Cognito::UserPoolClient)
Event Type: update
Reason: User pool client does not exist. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 7225a268-52fa-441f-b18a-b15592dfb443; Proxy: null)
URL: ....

🛑 Resource is not in the state stackUpdateComplete
Name: UserPoolClient (AWS::Cognito::UserPoolClient), Event Type: update, Reason: User pool client does not exist. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: ....` 

I've tried to also launch an  `amplify pull` command before and the result is the same.

Any help woluld be appreciated.

### Expected behavior

After `amplify pull`, I'm expecting to receive `No changes detected` message, if I launch an  `amplify push` command. 
On the other hand, if I launch `amplify push` command after some new developments, I' m expecting that this developments will be deployed through amplify.

### Reproduction steps

1. Amplify pull;
2. Amplify push

**Comment by fabel84** [comment]
Hi @ykethan, thanks for the response. I've just checked on AWS Cognito console and user pool Client exists and has the exact name that I've found on cloudformation-template.json used to build auth reseouce in the cloud. On my knowledge there was no changes on auth resource. Any other suggestion?

**Comment by ykethan** [comment]
Hey @fabel84, thank you for the information. could you check the AWS CloudFormation console for nested stack for the auth resource with the name of stack in format `amplify-<app-name>-<env-nam>-<random-number>-auth`. In the nested could you verify the events section to confirm there was a update to the user pool client recently and the resources section for a UserPoolClient attribute value matches the user pool clientID.

**Comment by fabel84** [comment]
Hi @ykethan,
thank you for your suggestion. I've not found any stack name `amplify-<app-name>-<env-nam>-<random-number>-auth`, but I've problably found the stack you refer to. It is described as `Amplify Cognito Stack for AWS Amplify CLI`, and probably I've found the problem. 
In resources section infact I could find both UserPool and UserPoolClient. User pool refers correctly to my Cognito userPool , but UserPoolClient refers to a Client that doesn't exists. Probably someone has 'manipulate' client's app list on Cognito.
As i previously said, infact user Pool client has the exact name of the user pool Client in template.json, but has a different physical ID. Could I manipulate the stack to override the physical ID of the User Pool Client?

If not how can i force it using amplify?

Any suggestion would be appreciated

**Comment by ykethan** [comment]
Hey @fabel84, thank you for the information. Unfortunately, we have been unable to find a way to force recreate this client or use an override to import a existing client(https://github.com/aws-amplify/amplify-cli/issues/12611). This feature is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/10871.

The easiest path forward would be to remove auth and add it again with the CLI to recreate entirely, however I understand this may not be feasible if there is production data from a live app. If this is the case, you can enable Deletion Protection for Cognito and remove it from your project, then use amplify import auth to import the same User Pool with the newly created client(https://github.com/aws-amplify/amplify-cli/issues/12611#issuecomment-1548244403).

**Comment by josefaidt** [comment]
Hey @fabel84 are you still experiencing this?

**Comment by fabel84** [comment]
Hey @josefaidt, in my case the solution was prospected by @ykethan. Fortunately this issue occured in a Dev environment, so I follow his suggestion, and I've recreated the client. 

Thanks

**Comment by willb0246** [comment]
hello @ykethan and @josefaidt 

I had a similar problem where one of the amplify auto-created clients (the mobile one, with the client secret) was deleted from my production cognito console. I was wondering if I needed to create a new one of those before following the steps of:

> If this is the case, you can enable Deletion Protection for Cognito and remove it from your project, then use amplify import auth to import the same User Pool with the newly created client(https://github.com/aws-amplify/amplify-cli/issues/12611#issuecomment-1548244403).
