### ISSUE TITLE
Since upgrading to amplify 12, cli blocked by 'Packaging overrides failed.', and unable to update  "@aws-amplify/cli-extensibility-helper":  to 3.0.0 as per docs

### ISSUE THREAD

**Issue by johnemcbride** [aws-amplify/amplify-cli#12838]
### How did you install the Amplify CLI?

 npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

20.3.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Hmmm.... only manual changes would be Cognito user pools - added custom profile attributes and pointed to SES.

### Describe the bug

Since upgrading to v12, I have been unable to perform amplify push or pull, due to the error:

⠸ Fetching updates to backend environment: dev from the cloud.🛑 Packaging overrides failed.
Command failed with exit code 1: yarn install
warning package.json: No license field
error ../../package.json: Name contains illegal characters
yarn install v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Resolution: There may be errors in your overrides file. If so, fix the errors and try again.
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

This blocks cicd.

I have followed steps on  https://docs.amplify.aws/cli/project/troubleshooting/ and tried to change:
backend/package.json to have:
 "@aws-amplify/cli-extensibility-helper": "^3.0.0", but on each and every push/pull, the file reverts to 2.4.4 - where is this coming from?

For reference I have overridden an API to inject cognito user pool into a lambda.... this has worked for months, no issues.

The override file, offending package.json and diagnostic output attached.

### Expected behavior

Amplify push pull should work.

### Reproduction steps

Uhh.  Create a project on amplify v10, override, upgrade amplify to v12, try anything, suffer.

### Project Identifier

 29c55dc1c735579b84ff3576a044d285

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by johnemcbride** [comment]
override ts file here, but I don't think this is the issue:

// This file is used to override the REST API resources configuration
import { AmplifyApiRestResourceStackTemplate } from "@aws-amplify/cli-extensibility-helper";

export function override(resources: AmplifyApiRestResourceStackTemplate) {
  // Replace the following with your Auth resource name
  const authResourceName = "amplifyapp0cb91442";
  const userPoolArnParameter = "AuthCognitoUserPoolArn";

  // Add a parameter to your Cloud Formation Template for the User Pool's ID
  resources.addCfnParameter(
    {
      type: "String",
      description:
        "The ARN of an existing Cognito User Pool to authorize requests",
      default: "NONE",
    },
    userPoolArnParameter,
    { "Fn::GetAtt": [`auth${authResourceName}`, "Outputs.UserPoolArn"] }
  );
  // Create the authorizer using the AuthCognitoUserPoolArn parameter defined above
  resources.restApi.addPropertyOverride("Body.securityDefinitions", {
    Cognito: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      "x-amazon-apigateway-authtype": "cognito_user_pools",
      "x-amazon-apigateway-authorizer": {
        type: "cognito_user_pools",
        providerARNs: [
          {
            "Fn::Join": ["", [{ Ref: userPoolArnParameter }]],
          },
        ],
      },
    },
  });
  // For every path in your REST API
  for (const path in resources.restApi.body.paths) {
    // Add the Authorization header as a parameter to requests
    resources.restApi.addPropertyOverride(
      `Body.paths.${path}.x-amazon-apigateway-any-method.parameters`,
      [
        ...resources.restApi.body.paths[path]["x-amazon-apigateway-any-method"]
          .parameters,
        {
          name: "Authorization",
          in: "header",
          required: false,
          type: "string",
        },
      ]
    );
    // Use your new Cognito User Pool authorizer for security
    resources.restApi.addPropertyOverride(
      `Body.paths.${path}.x-amazon-apigateway-any-method.security`,
      [{ Cognito: [] }]
    );
  }
}

**Comment by ykethan** [comment]
Hey @johnemcbride, 👋 thank you for reaching out. From the information provided this error message stands out.

```
error ../../package.json: Name contains illegal characters
```

could check the name property in the `package.json`

**Comment by johnemcbride** [comment]
new versions of 3pm didn't like spaces in the root package.json file.   jeeez

**Comment by johnemcbride** [comment]
> Hey @johnemcbride, 👋 thank you for reaching out. From the information provided this error message stands out.
> 
> ```
> error ../../package.json: Name contains illegal characters
> ```
> 
> could check the name property in the `package.json`

spot on..... spaces in the name.  (which were always there......?)

**Comment by ykethan** [comment]
@johnemcbride this appears to be a change; ref: https://github.com/yarnpkg/yarn/issues/1120
