### ISSUE TITLE
Add Resource-based policy to allow Pinpoint invoke lambda function

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-cli#12849]
### Amplify CLI Version

10.5.2

### Question

Hey Guys, 

I try to connect a Pinpoint Journey with my Lambda function to invoke lambda based on a analytics event. 

So this is working when I use the Console to add a Resource-based policy: 

```
{
      "Sid": "custom-test",
      "Effect": "Allow",
      "Principal": {
        "Service": "pinpoint.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:eu-central-1:XXX:function:pinpointEventsHandler-develop",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:mobiletargeting:eu-central-1:XXX:apps/*"
        }
      }
    }
```

I can't find this part in the template at the console from cloudformation. 

With the Amplify CLI I can add this how? 

With the custom policy flow it is not working: 

```
{
    "Action": ["lambda:InvokeFunction"],
    "Resource": ["arn:aws:mobiletargeting:eu-central-1:XXX:apps/*"]
  }
```

Any Idea?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html

**Comment by biller-aivy** [comment]
Update: (I thought it was working, but at the moment I get this error when I add the permissions in console too)

Activity validation failed, jvbixqMWXk: Amazon Pinpoint couldn’t invoke the Lambda function that you specified for custom delivery. Verify that a function policy is assigned to the function and that Amazon Pinpoint is authorized to invoke the function.

**Comment by ykethan** [comment]
Hey @biller-aivy, 👋 thank you for reaching out. Support for Lambda resource policies is currently tracked on https://github.com/aws-amplify/amplify-cli/issues/9093.
If you could add a 👍 on the issue, this would help us prioritize the feature request.

**Comment by josefaidt** [comment]
Closing in favor of tracking #9093
