### ISSUE TITLE
Error: 'jsonString' argument missing or empty when running amplify --version command

### ISSUE THREAD

**Issue by khansa20** [aws-amplify/amplify-cli#12848]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

V5.3.1

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Just edited Amplify Ui but on the studio

### Describe the bug

I encountered an error while running the `amplify pull` command in my Amplify project. The error message displayed is `'jsonString' argument missing or empty`. I have followed the troubleshooting steps mentioned in the Amplify documentation, but the issue persists.

### Expected behavior

The `amplify pull` command should successfully pull the backend resources and update the local project configuration.

### Reproduction steps

1. Create a new Amplify project using the Amplify CLI.
2. Configure the necessary backend resources and push the project to the cloud.
3. In a separate environment or on a different machine, clone the Amplify project repository.
4. Run the `amplify pull` command from the project root directory.

### Project Identifier

When I try to run `amplify diagnose --send-report`
still, get this error:

🛑 'jsonString' argument missing or empty

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 83be0d05-6a00-4008-805c-db8e18f098f2
🛑 Failed to report error: 'jsonString' argument missing or empty

### Log output

<details>

```
🛑 'jsonString' argument missing or empty

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 83be0d05-6a00-4008-805c-db8e18f098f2
🛑 Failed to report error: 'jsonString' argument missing or empty


```

</details>

### Additional information

Additional information:
- I have verified that the `amplify` folder and the `amplify/team-provider-info.json` file exist in the project directory.
- I have valid AWS credentials configured on my system.
- I have tried updating the Amplify CLI to the latest version and clearing the Amplify configuration.

Session Identifier: 83be0d05-6a00-4008-805c-db8e18f098f2

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by lazpavel** [comment]
Hi @khansa20, can you upgrade to latest CLI, v12.1.1 and let us know you're still encountering this issue?

**Comment by ykethan** [comment]
Hey @khansa20, just to clarify and prevent any misunderstanding. Did deleting the `~/.amplify/admin/config.json` not mitigate the issues?
The workaround with steps is currently documented here: https://docs.amplify.aws/console/adminui/extend-cli/#authentication-tokens

additionally, when running `vi ~/.amplify/admin/config.json` do you observe a json with `jwtToken`? 
Note, the content of `~/.amplify/admin/config.json` is utilized to store JWTs to vend temporary AWS credentials and should **NOT** be shared.
