### ISSUE TITLE
Cloudformation template format.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1286]
** Which Category is your question related to? **
Cognito 
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Is there any reason why one CloudFormation template format is not used? In the Cognito CloudFormation template the format is YAML. Everything else I have seen is JSON. If I had to choose, I would make it all YAML. "Nice to have" :)

**Comment by UnleashedMind** [comment]
The CLI platform does NOT put a hard requirement for each category plugin on what template format to use. We actually found JSON is an easier format to use.
