### ISSUE TITLE
Amplify CLI fails to create secret in AWS SSM

### ISSUE THREAD

**Issue by krypticbit** [aws-amplify/amplify-cli#12878]
### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

18.16.1

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When I create a lambda and configure a new secret for it via the amplify CLI, the secret is not created (it does not appear in the AWS Secrets Manager).

### Expected behavior

I except the secret to appear in the AWS Secrets Manager and my lambda to be able to read the secret.

### Reproduction steps

Create a function with access to a secret key via the amplify CLI

### Project Identifier

3426d9e4749693f0bbf604ff45b62fa6

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @krypticbit :wave: thanks for raising this! Despite the naming/acronym, Amplify CLI will create parameters in [AWS Systems Manager (SSM) Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html). More details on how Amplify CLI uses SSM Parameter Store can be found on our docs https://docs.amplify.aws/cli/reference/ssm-parameter-store/

**Comment by krypticbit** [comment]
@josefaidt Ah, that was indeed the issue! I see that the Amplify CLI has created the secret in the parameter store as expected. Thank you for your assistance!
