### ISSUE TITLE
Support exporting all configuration as CloudFormation

### ISSUE THREAD

**Issue by p5** [aws-amplify/amplify-cli#12875]
### Describe the feature you'd like to request

If we are able to export the entire configuration as a a bunch of CloudFormation files, we would be able to perform analysis on the resources which would be created, and allow us to scan for overly permissive IAM permissions and other obvious misconfigurations that could lead to a security issue.

### Describe the solution you'd like

If we could run something like `amplify export --type cloudformation --output-dir ./output/` in a CI/CD pipeline, we would be able to run some sort of analysis tool on the generated CloudFormation files, and could prevent insecure configurations BEFORE they are created in our account, not after.

### Describe alternatives you've considered

There are no tools I could find that could scan the Amplify configuration for security issues, so the only other option would be retroactively scanning the resources in our AWS account.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @p5 :wave: thanks for raising this! What sort of validation are you looking to perform? With the existing setup and `export` functionality I think this could be done in a few ways:

- validate the templates found in `amplify/backend/**/*-template.json` and `amplify/backend/**/**/build/cloudformation-template.json`
- export and validate with CDK's `synth` output

**Comment by p5** [comment]
Bump (to try and run the workflow that failed)

**Comment by josefaidt** [comment]
Hey @p5 thanks for providing those details! I think either of the two options above can help with this! The `amplify/backend/awscloudformation` directory should include all relevant CloudFormation templates that you can use those tools to scan

**Comment by josefaidt** [comment]
Hey @p5 were you able to successfully run the scans on those files?

**Comment by DougalW** [comment]
@josefaidt - are those files complete enough to generate a totally new stack? My use case is 1. new client signs up through marketplace, 2) we use cloud formation to generate a complete Amplify stack for them to use

**Comment by josefaidt** [comment]
Hey @DougalW apologies for the delay; I missed this reply. I would lean on Amplify and its CLI to create environments, therefore yes it should be sufficient to generate an entirely new stack.

**Comment by josefaidt** [comment]
Hey @DougalW I wanted to follow-up here and see if you were still experiencing this? Were you able to create a new Amplify stack on the fly?

**Comment by DougalW** [comment]
Hi @josefaidt we implemented a devops pipeline in the end to handle this, but are experiencing significant issues with CloudFormation and resources: https://github.com/aws-amplify/amplify-cli/issues/13207

**Comment by josefaidt** [comment]
Hey @DougalW glad to hear it! And thank you for filing that issue separately; I see there's been some traction on that issue. I'll close this issue for now, and continue tracking 13207
