### ISSUE TITLE
Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api.

### ISSUE THREAD

**Issue by proffnick** [aws-amplify/amplify-cli#12873]
### Amplify CLI Version

12.1.1

### Question

Amplify failed to publish with the following error structure: `{
    "name": "UnknownNodeJSFault",
    "classification": "FAULT",
    "options": {
        "message": "Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api.",
        "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
        "code": "BadRequestException"
    },
    "downstreamException": {
        "message": "Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api.",
        "code": "BadRequestException",
        "time": "2023-06-28T11:45:52.091Z",
        "requestId": "4af837c9-466f-447a-81bc-02a22d4b7014",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 19.478282673057556
    },
    "resolution": "Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'",
    "code": "BadRequestException",
    "link": "https://docs.amplify.aws/cli/project/troubleshooting/"
}`
How do I troubleshoot this?

**Comment by josefaidt** [comment]
Hey @proffnick :wave: thanks for raising this! Where are you seeing this? Is this after executing a command? Please consider porting this over to use our [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml) to help us better understand the context of the issue you're experiencing.
