### ISSUE TITLE
Function CloudFormation parameters.json files.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1288]
**Is your feature request related to a problem? Please describe.**
No way to pass variables into the CloudFormation template of functions.

**Describe the solution you'd like**
Add a parameters.json file, even if it is an empty one. So we can add custom parameters to use in the CloudFormation template.

**Describe alternatives you've considered**
Currently I am hardcoding the values in the CloudFormation template.

**Additional context**
N/A

**Comment by kaustavghosh06** [comment]
@jarrettj You could create the `parameters.json` file in the `amplify/backend/functions/<name>/` directory and the CLI would detect and use the same to pass in params to the CFN file.

**Comment by jarrettj** [comment]
Hi,

Good day.

Thanks! That has done the trick. Much appreciated. 

Regards.
