### ISSUE TITLE
How to remove duplicate files from amplify/backend/awscloudformation/build/

### ISSUE THREAD

**Issue by Rurmux** [aws-amplify/amplify-cli#12899]
### Amplify CLI Version

12.1.1

### Question

I am facing an issue with duplicate JSON files appearing in the `amplify/backend/awscloudformation/build/` directory. How can I remove them?

The problem seems to have started when I had iCloud backup turned on for the project directory which caused duplicate files to be created on `amplify pull`. Example duplicate files are:
- `amplify/backend/function/otpauthCreateAuthChallenge/parameters 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/custom-policies 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/function-parameters 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/otpauthCreateAuthChallenge-cloudformation-template 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/src/package-lock 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/src/package 2.json`
- `amplify/backend/function/otpauthCreateAuthChallenge/src/event 2.json`
- `amplify/backend/awscloudformation/build/function/otpauthCreateAuthChallenge/otpauthCreateAuthChallenge-cloudformation-template 2.json`

I managed to stop the creation of duplicate files by turning off iCloud backup and removing the duplicates from my local environment. When i push-ed my changes and then pull-ed them, the duplicate files listed above disappeared **except** for the `cloudformation-template 2.json`'s and `root-cloudformation-stack 2.json` in the `./amplify/backend/awscloudformation/build/` directory, such as:
- `amplify/backend/awscloudformation/build/function/otpauthCreateAuthChallenge/otpauthCreateAuthChallenge-cloudformation-template 2.json`

How can I permanently remove these duplicates from the backend build? I've tried deleting them locally and then pushing the changes, but they keep reappearing after I pull them from the backend. 

Environment: MacOS Ventura 13.4, amplify CLI 12.1.1, building a Swift project.

Any guidance on how to address this issue would be appreciated.

**Comment by josefaidt** [comment]
Hey @Rurmux :wave: thanks for raising this! It appears these files may have gotten picked up and zipped with the backend state. Can you download the `#current-cloud-backend.zip` file from your project's deployment bucket, remove the duplicated files, re-zip and re-upload, and push?

**Comment by Rurmux** [comment]
That solved it! Thank you very much 🤩

**Comment by spesnova** [comment]
Hi @josefaidt 👋

If there're files like below:

```
amplify/backend/function/<FUNCTION_NAME>/<FUNCTION_NAME>-cloudformation-template.json
amplify/backend/awscloudformation/build/function/<FUNCTION_NAME>/<FUNCTION_NAME>-cloudformation-template.json
```

Can I consider they're duplicated ? And should I delete either file?
