### ISSUE TITLE
Querying for all children with the generated graphql schema/queries

### ISSUE THREAD

**Issue by peterjungx** [aws-amplify/amplify-cli#1290]
Amplify generated graphql schema and queries (generated from annotated one) are  inconsistent for one-to-many relationships.

**Describe the bug**
With the generated schema/queries, there is no way to:
1.  Specify the `limit` parameter for child elements in a get query .
1. Use the `nextToken` returned by child elements of a get query.
2. Filter on the ID of parent elements.

**To Reproduce**
I use a simplified version of the example Blog/Post schema:
```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog! @connection(name: "BlogPosts")
}
```
Note that I added the '!' for the BlogPosts connection: There should be no Post without a Blog. So wanting to get all Posts for a Blog is a natural thing.

The relevant section from the generated schema is this:
```
type Query {
  getBlog(id: ID!): Blog
  listPosts(filter: ModelPostFilterInput, limit: Int, nextToken: String): ModelPostConnection
}
```

I codegen with depth 2.

I want to load a Blog and its Posts. If the number of Posts exceeds 10, the getBlog query returns a `posts.nextToken`, but that is unusable:
1. The getBlog query does not accept `posts.nextToken` as a parameter. (Also there is no object corresponding to ModelPostConnection returned by amplify-js, that could be used with the nextToken)
2. Attempting to use the `posts.nextToken` in a listPosts query gives an error: 

```The provided starting key is invalid: The provided key element does not match the schema (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException;```

I could try to load the Posts separately from the Blog. But then:

3. The ModelPostFilterInput does not provide a `postBlogId` field to filter on (which btw. is being created for the createPost and updatePost mutations).

So my workaround for now is to fetch all Posts for all Blogs and to filter on the one Blog i am interested in client side, which is suboptimal. Also I do not want to fiddle with the generated schema. 

**Expected behavior**
1. I would expect to be able to control the `limit` parameter for one-to-many child elements in a get query.
2. I would expect to be able to use the `nextToken` returned by child elements in a get query in some obvious way. (This is possibly a shortcoming in amplify-js, or maybe there is a not so obvious way to use them, which I did not figure out myself, in which case the docs could need improvement.) (Also I would expect to be able to control the limit parameter for nested )
3. I would expect to be able to filter by the ID of a parent in a list query.

**Additional context**
aws-amplify v1.1.26

**Comment by wizawuza** [comment]
I'd just create a custom query to be honest. The generated queries are great for a starting point, but one of the points of GraphQL is to easily write your own queries.
For example:
```
query getBlog{
  getBlog(id:"whatever"){
    name
    Posts(limit:20, nextToken:"whatever", filter:<insert filter query>){
      items{
        title
      }
    }
  }
}
```

**Comment by peterjungx** [comment]
Ah, thank you very much! I was not aware that this would work, I am totally new to GraphQL. This solves my issue for now.

Nevertheless I feel that such a canonical scenario should be supported out of the box by the generated schema/queries. This whole amplify stuff is such a huge time saver, powerful and enabling, especially for noobs, but this small hiccup did cost me a day. Also the proposed solution is not so elegant imho because I would work with a template string to parse the nextToken into AND a parameter I am passing to `API.graphql`.

**Comment by yuth** [comment]
@peterjungx as @wizawuza Amplify CLI generated statements are meant to be used as a starting point. The generated statements don't include any arguments of the selection set intentionally as it makes it more complicated for cases where if there are multiple list operations in query. Consider the following example. 
```graphql
query GetBlog(
  $id: ID
  $postLimit: Int
  $postNextToken: String
  $commentsNextToken: String
  $commentsLimit: Int
) {
  getBlog(id: $id) {
    name
    Posts(limit: $postLimit, nextToken: $postNextToken) {
      items {
        title
        content
        comments(limit: $commentsLimit, nextToken: $commentsNextToken) {
          items {
            content
          }
        }
      }
    }
  }
}

```

**Comment by StriderHND** [comment]
> @peterjungx as @wizawuza Amplify CLI generated statements are meant to be used as a starting point. The generated statements don't include any arguments of the selection set intentionally as it makes it more complicated for cases where if there are multiple list operations in query. Consider the following example.
> 
> ```graphql
> query GetBlog(
>   $id: ID
>   $postLimit: Int
>   $postNextToken: String
>   $commentsNextToken: String
>   $commentsLimit: Int
> ) {
>   getBlog(id: $id) {
>     name
>     Posts(limit: $postLimit, nextToken: $postNextToken) {
>       items {
>         title
>         content
>         comments(limit: $commentsLimit, nextToken: $commentsNextToken) {
>           items {
>             content
>           }
>         }
>       }
>     }
>   }
> }
> ```

Is there a way to do something similar with a lists of blogs how I do pass the nextToken of each of the post and comments of a given blog.
