### ISSUE TITLE
"Amplify update auth" doesn't work 

### ISSUE THREAD

**Issue by Loempisey** [aws-amplify/amplify-cli#12903]
### Amplify CLI Version

12.1.1

### Question

Hello ! I have an issue when I run the command "amplify update auth" and the response is " Updating imported Auth resource is not supported " and I already upgrade amplify cli to the latest version. Is there any solution to solve this issue without remove auth and create a new one. I really appreciate with all your support. Thanks !

**Comment by josefaidt** [comment]
Hey @Loempisey :wave: thanks for raising this! Unfortunately we are not able to update an imported resource, and you will need to remove the imported auth, and create a new resource managed by Amplify with `amplify add auth`. More details around `amplify import auth` can be found here https://docs.amplify.aws/cli/auth/import/

**Comment by Loempisey** [comment]
Hello@josefaidt thanks for this support !
