### ISSUE TITLE
How to use an existing bucket and roles for hosting from aws-amplify

### ISSUE THREAD

**Issue by ArunPrasathSubramani** [aws-amplify/amplify-cli#1291]
** Which Category is your question related to? **
Hosting category

** What AWS Services are you utilizing? **
S3, cloudformation, IAM

** Provide additional details e.g. code snippets **
Can I pass parameters to the cloudformation template through config?

**Comment by UnleashedMind** [comment]
@ArunPrasathSubramani 
No, the current hosting category does NOT allow using existing buckets. 
If you want, I can mark this as a feature request and discuss with the team.

**Comment by matwerber1** [comment]
+1 on making this a feature request. My use case is that my organization's security policy requires that public buckets names first be whitelisted and configured in a certain way before they are actually used to serve public content. Being able to use a pre-existing bucket would be great!

**Comment by matwerber1** [comment]
Created a feature request here: #658
