### ISSUE TITLE
DiagnoseReportUploadError 

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-cli#12913]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.1.1

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

-

### Describe the bug

<img width="971" alt="Bildschirmfoto 2023-07-07 um 10 24 13" src="https://github.com/aws-amplify/amplify-cli/assets/88539760/20ffd6fb-a0f1-4f16-80ce-9f2f5a140ab1">

### Expected behavior

-

### Reproduction steps

- send me a mail where I can send the zip, than maybe you can check 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @biller-aivy :wave: thanks for raising this! Do you see any logs that stand out in `~/.amplify/logs` or is there a stack trace when you run the same command with `--debug`?

**Comment by biller-aivy** [comment]
> Hey @biller-aivy 👋 thanks for raising this! Do you see any logs that stand out in `~/.amplify/logs` or is there a stack trace when you run the same command with `--debug`?

just: 

2023-07-10T09:18:51.485Z|info : amplify diagnose core  {"send-report":true,"debug":true,"yes":false}
2023-07-10T09:18:51.593Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}

**Comment by 0618** [comment]
Hey @biller-aivy ! Do you still experiencing the issue?

To provide more information for investigation, could you paste the log or email zhamujun@amazon.com ?

Would you like to have a call for trouble-shooting?

**Comment by 0618** [comment]
I happened to see the same error when there was no env name.

<img width="853" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/11983489/76630678-2c18-417b-9c7f-9bca079246bb">

@biller-aivy could you make sure there's an env name? 

If you need more help, we are happy to set up a call with you.

**Comment by biller-aivy** [comment]
I just used 
- amplify diagnose --send-report --debug 

So I guess, yes there is a env name?!

**Comment by josefaidt** [comment]
Hey @biller-aivy apologies for the delay here but thank you for your continued patience. I'm going to mark this as a bug to add `--debug` support to the diagnose tool in order to better understand the underlying errors.

**Comment by ykethan** [comment]
Closing the issue, if you have any information that would enable us in reproducing this please feel free in reaching out to us.
