### ISSUE TITLE
Not possible to add redirects for Android denoted as "myapp://" through amplify cli

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#12930]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.0.0

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

% amplify update auth   
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Add/Edit signin and signout redirect URIs
 Which redirect signin URIs do you want to edit? 
 Do you want to add redirect signin URIs? Yes
 Enter your new redirect signin URI: myapp://
>> The value must be a valid URI with a trailing forward slash. HTTPS must be used instead of HTTP unless you are using l
ocalhost.

### Expected behavior

That I would be able to add the uris

### Reproduction steps

- Update auth
-  What do you want to do? Add/Edit signin and signout redirect URIs
-  Which redirect signin URIs do you want to edit? 
-  Do you want to add redirect signin URIs? Yes
- Enter your new redirect signin URI: myapp://

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by maziarzamani** [comment]
I also tried to remove the social login and added it back from scratch, same problem:

 amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Apply default configuration with Social Provider (Federation)
 What domain name prefix do you want to use? sashaauth
 Enter your redirect signin URI: myapp://
>> The value must be a valid URI with a trailing forward slash. HTTPS must be used instead of HTTP unless you are using l
ocalhost.

**Comment by josefaidt** [comment]
Hey @maziarzamani :wave: thanks for raising this! Can you share the full URI you are attempting to use? Despite the issue, you should also be able to set this directly in `amplify/backend/auth/<resource-name>/cli-inputs.json`

**Comment by maziarzamani** [comment]
> Hey @maziarzamani 👋 thanks for raising this! Can you share the full URI you are attempting to use? Despite the issue, you should also be able to set this directly in `amplify/backend/auth/<resource-name>/cli-inputs.json`

I attempted to set `my_app://`, but as far as I can see the CLI won't allow underscores in the name, we removed the underscore and was able to proceed. It seems like the oath lambda function is rejecting that type of naming.

**Comment by josefaidt** [comment]
Hey @maziarzamani glad to hear you've found a workaround! Out of curiosity was this failing after updating the value manually in `cli-inputs.json` and `amplify push`?

**Comment by maziarzamani** [comment]
> Hey @maziarzamani glad to hear you've found a workaround! Out of curiosity was this failing after updating the value manually in `cli-inputs.json` and `amplify push`?

Yes! No matter how we tried to add the URI it failed, it seems like underscores (`_`) are not allowed, so we dropped the underscore and created a clean URI

**Comment by josefaidt** [comment]
Hey @maziarzamani the lack of support for underscores seems to be on the Cognito side. I am, however, able to input `myapp://asdf/` into the CLI prompt

**Comment by maziarzamani** [comment]
> Hey @maziarzamani the lack of support for underscores seems to be on the Cognito side. I am, however, able to input `myapp://asdf/` into the CLI prompt

You can however close this ticket as we went with a non-underscore solution and got it working.
