### ISSUE TITLE
Creating multiple Cognito App clients to distinguish and separate settings and urls between apps (Web, iOS, etc.)

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#12932]
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Currently it only seems to be possible to create one Cognito App client which is utilized for everything. This unfortunately makes no sense as settings are usually different on web vs. iOS/android apps. It would make sense to be able to create separate clients that can be utilized in the project.

### Describe the solution you'd like

The ability to create separate clients which then can be selected in apps as well as web frameworks.

### Describe alternatives you've considered

Overriding auth and creating the clients manually, however this will break the aws-export file which gives a lot of convenience. 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @maziarzamani :wave: thanks for raising this! By default, when creating auth via `amplify add auth` we will create two separate Cognito User Pool Clients: one for web and one for mobile. For example, in a JavaScript/React project we see the following client ID in `aws-exports.js`

```
"aws_user_pools_web_client_id": "3rjo997hn0pn36fqmrf4iqeqp1",
```

And if I run `amplify configure project` to change over to an Android project we see the following generated in `amplifyconfiguration.json`

```
"CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_6UtcQOHXR",
            "AppClientId": "6lggo8h4eifbik48v2jda9uttd",
            "Region": "us-east-1"
        }
    },
```

**Comment by maziarzamani** [comment]
> Hey @maziarzamani 👋 thanks for raising this! By default, when creating auth via `amplify add auth` we will create two separate Cognito User Pool Clients: one for web and one for mobile. For example, in a JavaScript/React project we see the following client ID in `aws-exports.js`
> 
> ```
> "aws_user_pools_web_client_id": "3rjo997hn0pn36fqmrf4iqeqp1",
> ```
> 
> And if I run `amplify configure project` to change over to an Android project we see the following generated in `amplifyconfiguration.json`
> 
> ```
> "CognitoUserPool": {
>         "Default": {
>             "PoolId": "us-east-1_6UtcQOHXR",
>             "AppClientId": "6lggo8h4eifbik48v2jda9uttd",
>             "Region": "us-east-1"
>         }
>     },
> ```

Makes sense! However can I have an Android as well as iOS, and web individually setup, or will it always create two app clients regardless of the amount of apps I may have?

**Comment by josefaidt** [comment]
> However can I have an Android as well as iOS, and web individually setup, or will it always create two app clients regardless of the amount of apps I may have?

It will always create the two clients, however you can create additional clients using [auth overrides](https://docs.amplify.aws/cli/auth/override/). The caveat being the new client's ID will not be surfaced in the `amplifyconfiguration` files

**Comment by maziarzamani** [comment]
I gave up for now, and just wen't ahead with those two automatically generated client, so no solution for now..
