### ISSUE TITLE
amplify env remove test, removed all resources of prod branch

### ISSUE THREAD

**Issue by Weixuanf** [aws-amplify/amplify-cli#12954]
### Amplify CLI Version

can't remember (cuz I upgraded afterwards), but it wasn't the latest version 

### Question

I had my main amplify env branch prod, which includes all the resources (dynamo db tables, s3 buckets, cognito, ...)
then I did `amplify env add` another branch called test. I think I added it when I try to do `amplify push` on it, it throws exception: 🛑 Template error: instance of Fn::GetAtt references undefined resource authokband411e4d5b
which made me unable to finish `amplify push` (so I think no resources (dynamo tables, s3 buckets, ...) was generated for test branch 

so i decided to just remove this branch by `amplify env remove test`, then to my shock, it remove ALL my resources (dynamo db tables, s3 buckets, cognito, ...) in prod branch....maybe it's because the amplify push for test branch was never finish so it didn't link its own resources but instead linked prod's resources?? 

But anyway it resulted in a tragedy that the test branch and all my resources of prod branch was removed. prod branch was left with an empty branch with no resources.

I don't know if I did something wrong that resulted this

**Comment by josefaidt** [comment]
Hey @Weixuanf :wave: thanks for raising this! While we begin to look at this in more depth would you mind posting the project ID output from `amplify diagnose --send-report`?
