### ISSUE TITLE
AWS amplify cli installation issue 

### ISSUE THREAD

**Issue by umesh-meka** [aws-amplify/amplify-cli#1295]
while trying to installa with belo command in node.js in windows getting below isssue.
please let know i have done any mistakes.

C:\> npm install -g @aws-amplify/cli
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! path C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json.1762810370
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json.1762810370' -> 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json'
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json.1762810370' -> 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json.1762810370' -> 'C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\acorn-globals\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path:
npm ERR!       'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json.1762810370',
npm ERR!      dest:
npm ERR!       'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, rename \'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json.1762810370\' -> \'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path:
npm ERR!    'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json.1762810370',
npm ERR!   dest:
npm ERR!    'C:\\Users\\um41056\\AppData\\Roaming\\npm\\node_modules\\@aws-amplify\\cli\\node_modules\\acorn-globals\\package.json',
npm ERR!   parent: '@aws-amplify/cli' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\um41056\AppData\Roaming\npm-cache\_logs\2019-04-17T06_25_50_206Z-debug.log

**Comment by UnleashedMind** [comment]
@umesh-meka 
Is this a new installation or update? 
The easiest way to fix this is probably remove this directory C:\Users\um41056\AppData\Roaming\npm\node_modules\@aws-amplify
and run 
'npm install -g @aws-amplify/cli` 
again.

**Comment by umesh-meka** [comment]
Yes it's is a new installation.
Yeah I tried that way, but there was no folders created 'npm' folder...

**Comment by ultradox** [comment]
when running `sudo npm i -g @aws-amplify/cli@latest` (v1.6.3) I get errors shown below. Same errors also occur on v1.5.x, 1.4.x and 1.1.x. Seems multiple old versions have problem see https://github.com/aws-amplify/amplify-cli/issues/1202. However despite errors if you run amplify --version after install, I get 1.6.3. Not sure what the implications are as yet.
```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.8 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/lib'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/build'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fsevents
```

**Comment by umesh-meka** [comment]
> @umesh-meka
> Is this a new installation or update?
> The easiest way to fix this is probably remove this directory C:\Users\um41056\AppData\Roaming\npm\node_modules@aws-amplify
> and run
> 'npm install -g @aws-amplify/cli`
> again.

**Comment by UnleashedMind** [comment]
@umesh-meka 
Have you tried to use run as administrator? 
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc771525(v=ws.10)
