### ISSUE TITLE
Can't use `envName` in `override.ts` for API category

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-cli#12966]
I paid a little more attention to this comment and I saw that I was trying to use `amplifyProjectInfo` in an API's `override.ts`. 
Is there any workaround for the API category? Because I can't merge my changes otherwise.

> Hey folks in the thread 👋 this is now possible with resource overrides for all categories except for API (for now). You can upgrade to the latest CLI (11.0.3 at the time of writing) and upgrade the Extensibility helper - with CDK v2.
> 
> Once upgraded, you can add the second argument to the override function `amplifyProjectInfo` to get the project name and environment name! 🎉
> 
> ```ts
> import {
>   AmplifyAuthCognitoStackTemplate,
>   AmplifyProjectInfo,
> } from '@aws-amplify/cli-extensibility-helper'
> 
> export function override(
>   resources: AmplifyAuthCognitoStackTemplate,
>   amplifyProjectInfo: AmplifyProjectInfo
> ) {
>   console.log(amplifyProjectInfo.projectName, amplifyProjectInfo.envName)
> }
> ```

_Originally posted by @redjonzaci in https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1640157496_

**Comment by redjonzaci** [comment]
I need to use envName in my API `override.ts`.

**Comment by redjonzaci** [comment]
As a workaround, I got the `envName` by using `Fn::Select` and `Fn::Split` on `AWS::StackName` in `addPropertyOverride`.

**Comment by redjonzaci** [comment]
@josefaidt I wanted to override the OpenSearch domain name to be a specific string + envName, like Lambda function names are for example. As for the env parameter, it gave me an error when trying to access it like `"Fn::Sub": "${env}"`. But the workaround is okay.

**Comment by josefaidt** [comment]
Hey @redjonzaci thanks for clarifying and that sounds good! For what it's worth when you need to reference a CFN stack parameter you will also need to write the CFN block rather than CDK. This is largely different by the property names where CDK is camelCase and CFN is PascalCase.

Given the workaround I will mark this as resolved, but if you encounter this again please do not hesitate to reach back out by filing a bug report!
