### ISSUE TITLE
amplify import auth does not generate oauth block properly

### ISSUE THREAD

**Issue by PAKalucki** [aws-amplify/amplify-cli#12979]
### How did you install the Amplify CLI?

curl

### Amplify CLI Version

12.1.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

When running amplify import auth on existing Cognito pool with federated Google identity provider it generates only partial oauth block:
```
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:xxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-xxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {
        "domain": "xxx.eu-west-2.amazoncognito.com"
    },
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};
```

oauth block is missing scope, redirectSignIn, redirectSignOut and responseType

### Expected behavior

Import auth should generate valid oauth configuration

### Reproduction steps

1. Create AWS cognito pool with federated identity provider only, remove COGNITO provider from app client
2. Run amplify import auth

### Project Identifier

33739d596e34c742587a51ad8b9170f4

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @PAKalucki, thank you for reaching out. Could you let us know if the Cognito user pool App client has a `Allowed sign-out URLs` defined? if the sign-out URL was not defined could you add the sign-out URL, then reimport the Cognito user pool and push.
I was able to reproduce this behaviour when the Cognito user pool App client was configured without a sign-out  URL.

If the sign-out URL was defined, could you provide some additional information on the configurations applied on the Cognito user pool.

**Comment by PAKalucki** [comment]
@ykethan After defining the sign-out URL, the oauth is populated correctly, thank you.
