### ISSUE TITLE
Ensure Amplify has finished writing its JSONs before post- hooks execution

### ISSUE THREAD

**Issue by vessi-devs** [aws-amplify/amplify-cli#12971]
### Is this feature request related to a new or existing Amplify category?

function, api, hosting

### Is this related to another service?

No

### Describe the feature you'd like to request

We're "stabilizing" Amplify JSONs (for example team-provider-info.json and APIGatewayAuthStack.json) to make easy resolving Git conflicts and commiting them. That stabilization must be done after a `amplify publish` or `push` execution.

We started using the post-publish and post-push hooks to automate the operation on the JSONs, but we observe that sometimes the involved files get stabilized and sometimes not.

We experimented by "forking" a hook and freeing a detached child (the parent "dies" immediately, so Amplify thinks the hook has finished its job) which waits some seconds before performing the stabilization (during those seconds, it's expected that Amplify "messes" its JSONs). We found out that it worked, implying that Amplify doesn't ensure it finished its jobs before executing the post- hooks.

### Describe the solution you'd like

We would like Amplify to ensure it finished all of its jobs (in particular JSONs writing) before the post- hooks execution, so we can stabilize its JSONs by using those hooks without Amplify "messing" them in parallel.

### Describe alternatives you've considered

It would be great if Amplify itself stabilizes all of its JSON files. It would ease Git operations on them.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @vessi-devs :wave: thanks for raising this! The issue described here regarding the merge conflicts is something we're tracking in this active bug https://github.com/aws-amplify/amplify-cli/issues/7938

But for the hooks issue, what files in particular are you interacting with? Do you have a minimal reproduction of this by chance?

**Comment by vessi-devs** [comment]
Thanks @josefaidt for such a fast reply!

At the moment we're experimenting with:
- `amplify/team-provider-info.json`
- `amplify/backend/api/APIGatewayAuthStack.json`

but we plan to add all of the `-template.json` files too.

A minimal example for **post push** stabilizing `team-provider-info.json` is the following:

`post-push.js`
```
const ssstringify = require('safe-stable-stringify'); // npm i safe-stable-stringify
const fs = require('fs');
const pathLib = require('path');
const absBaseRoute = __dirname;

const fileRoute = pathLib.join(absBaseRoute, '../../amplify/team-provider-info.json');
const fileContents = fs.readFileSync(fileRoute, { encoding: 'utf8', flag: 'r' });
const jsonFile = JSON.parse(fileContents);
const stabilizedContent = ssstringify(jsonFile, undefined, 2); // Stabilize and beautify it
fs.writeFileSync(fileRoute, stabilizedContent);
process.exit(0);
```

It **does work** in Cloud9 but **it doesn't** on my local Ubuntu 22.04 LTS virtual machine. Both have Amplify 12.1.1 and Node 16.20.1. There's some subtlety which is probably related with some things running in parallel but on different platforms.

The solution which **works on both** enviroments is the following:

`post-push.js`
```
const { spawn } = require('child_process');
const child = spawn('node', ['stabilize.js'], { detached: true }); // Free and detach the child which stabilizes
child.unref();
process.exit(0); // Let the parent die immediately so Amplify continues and finishes its execution
```

`stabilize.js`
```
const ssstringify = require('safe-stable-stringify'); // npm i safe-stable-stringify
const fs = require('fs');
const pathLib = require('path');
const absBaseRoute = __dirname;

// Wait some seconds while Amplify messes its JSONs and exits
const holdTime = 5; // Wait 5 seconds
setTimeout(() => {
	const fileRoute = pathLib.join(absBaseRoute, '../../amplify/team-provider-info.json');
	const fileContents = fs.readFileSync(fileRoute, { encoding: 'utf8', flag: 'r' });
	const jsonFile = JSON.parse(fileContents);
	const stabilizedContent = ssstringify(jsonFile, undefined, 2); // Stabilize and beautify it
	fs.writeFileSync(fileRoute, stabilizedContent);
	process.exit(0);
}, holdTime*1000);
```

Thanks so much for your attention and time.

**Comment by vessi-devs** [comment]
You can run `node post-push.js` in the `hooks` directory to figure out what it does to `amplify/team-provider-info.json` contents.

**Comment by josefaidt** [comment]
Hey @vessi-devs thanks for clarifying and providing that information! It sounds like you're encountering some race condition. Does this consistently reproduce on your Ubuntu VM?

**Comment by vessi-devs** [comment]
Hi, on my Ubuntu VM the hook gets executed but Amplify always "wins" and messes the JSONs at the end.

I added a `console.log` to print the stabilized content to check what was written into the JSON file, yielding the expected stabilized content. After writing it, I even experimented with reading it back and print it to check what happened and its contents were stabilized again.

However, in Cloud 9 the hook always "wins" and the JSONs end up successfully stabilized after Amplify finishes its execution.

Thanks.

**Comment by josefaidt** [comment]
Hey @vessi-devs :wave: apologies for the delay here! Are you still experiencing this issue with more recent versions of the CLI? From the description it does appear there is some race condition at play, however I have not been able to successfully reproduce this. Is the Ubuntu VM running on your local machine?

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
