### ISSUE TITLE
After updating to v12.2.0 add serverless containers disappeared 

### ISSUE THREAD

**Issue by zandieh** [aws-amplify/amplify-cli#12988]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v19.4.0

### Amplify CLI Version

12.2.0

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

Following flow explained in amplify cli documents doesn't exist anymore

```
> REST
> API Gateway + AWS Fargate (Container-based)
> ExpressJS - REST template
? Do you want to access other resources in this project from your api? Y   # select yes
> storage  # select posts table              # select post table and all permissions
  ◉ create
  ◉ read
  ◉ update
  ◉ delete
> Do you want to restrict API access (Y/n)    # Will use Amazon Cognito if Yes is selected
```

https://docs.amplify.aws/cli/usage/containers/

### Expected behavior

Should be able to add serverless conrainers

### Reproduction steps

amplify add api
> REST

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @zandieh :wave: thanks for raising this! Did you run `amplify configure project` to enable container-based deployments? 
![image](https://github.com/aws-amplify/amplify-cli/assets/5033303/e7698220-291b-4608-9870-d5a9e6a78061)

**Comment by zandieh** [comment]
Hey @josefaidt , thanks for the response I enabled container-based deployment using `amplify configure project` and it worked fine. I guess I forgot to run it when I first initiated the project :)
