### ISSUE TITLE
Support amplifyProjectInfo in API category override.ts

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#12985]
### Describe the feature you'd like to request

Per https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1490911445, amplifyProjectInfo is not yet supported in the API category. I don't see a feature request to add support for this so I'm creating one here. Although https://github.com/aws-amplify/amplify-category-api/pull/1372/files implies it is supported in the API category? 

### Describe the solution you'd like

amplifyProjectInfo in API overrides like other categories. 

### Describe alternatives you've considered

There are workarounds described in https://github.com/aws-amplify/amplify-cli/issues/12966 and https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-1607775574 but they're not clear. 

### Additional context

I want to enable DynamoDBDeletion proection in our prod env tables but not other environments. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @hisham :wave: thanks for raising this! Despite the final messaging on that issue this is now supported for API overrides

```ts
// amplify/backend/api/<api-name>/override.ts
import {
  AmplifyApiGraphQlResourceStackTemplate,
  AmplifyProjectInfo,
} from '@aws-amplify/cli-extensibility-helper'

export function override(
  resources: AmplifyApiGraphQlResourceStackTemplate,
  amplifyProjectInfo: AmplifyProjectInfo
) {
  console.log({ amplifyProjectInfo })
}
```

![image](https://github.com/aws-amplify/amplify-cli/assets/5033303/abf09e5e-529c-4aea-81c5-f7c1c92521a0)

**Comment by hisham** [comment]
awesome, thank you @josefaidt :)
