### ISSUE TITLE
Unable to create file .circleci/com1.sh: No such file or directory

### ISSUE THREAD

**Issue by kavengagne** [aws-amplify/amplify-cli#130]
**Describe the bug**
When trying to clone the repository on Windows, we get an error with some files in the .circleci directory.

**To Reproduce**
```Batchfile
$ git clone https://github.com/aws-amplify/amplify-cli.git
Cloning into 'amplify-cli'...
remote: Counting objects: 25078, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 25078 (delta 37), reused 42 (delta 32), pack-reused 25006
Receiving objects: 100% (25078/25078), 27.10 MiB | 4.49 MiB/s, done.
Resolving deltas: 100% (12431/12431), done.
error: unable to create file .circleci/com1.sh: No such file or directory
error: unable to create file .circleci/com2.sh: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

**Expected behavior**
Repository cloned with no error.

**Desktop (please complete the following information):**
 - OS: Windows (All versions)

**Additional context**
This problem happens because the files are using names that are invalid on Windows:
- com1.sh
- com2.sh

As stated in the following page: [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file):

> Do not use the following reserved names for the name of a file:
>
>CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended.

**I can send a Pull Request to rename the files com_1.sh and com_2.sh, but someone will need to change it in circleci**

**Comment by kaustavghosh06** [comment]
We just published to npm with a fix for this. Please use the version -> 0.1.19.
Closing the issue, feel free to re-open if the issue persists.
