### ISSUE TITLE
API override.ts projectInfo is undefined in CI

### ISSUE THREAD

**Issue by thomas5631** [aws-amplify/amplify-cli#13004]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.2

### Amplify CLI Version

12.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I have created an override.ts for an Amplify-managed AppSync API as follows:
```typescript
import {
  AmplifyApiGraphQlResourceStackTemplate,
  AmplifyProjectInfo,
} from '@aws-amplify/cli-extensibility-helper'

export function override(
  resources: AmplifyApiGraphQlResourceStackTemplate,
  projectInfo: AmplifyProjectInfo
) {
  console.log({ projectInfo })
}
```

When I run `amplify push` locally, I can see the projectInfo as shown [here](https://github.com/aws-amplify/amplify-cli/issues/12985#issuecomment-1646314509). However, when I run through ci (which runs `amplifyPush --simple`), I have the following output:

```sh
2023-07-25T17:38:55.744Z [INFO]: { projectInfo: undefined }
```

### Expected behavior

Is there anything additional that is required in order to populate `projectInfo` in CI?

### Reproduction steps

1. run `amplify override api`
2. choose an api to override
3. populate the override.ts file with the above typescript code

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
update: I was able to reproduce the issue by setting the `build image settings` in Amplify hosting to an older version of Amplify CLI for example `11.0.5`

**Comment by thomas5631** [comment]
Hi @ykethan, thanks so much for the quick reply!

At the moment, the build image setting is set to `latest`, and the following is logged during the build:

```sh
2023-07-25T17:37:11.370Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 12.2.1
```

This is the backend portion of my amplify.yml:
```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm i
    build:
      commands:
        - amplifyPush --simple
  cache:
    paths:
      - node_modules/**/*
```

**Comment by ykethan** [comment]
Hey @thomas5631, could you confirm if the `amplify -> backend -> package.json` contains dependencies block with`"@aws-amplify/cli-extensibility-helper": "^3.0.4"`?

**Comment by thomas5631** [comment]
Yeah, after running `amplify override api`, a package.json was generated in `amplify -> backend -> package json` with `"@aws-amplify/cli-extensibility-helper": "^3.0.0"` 

I tried updating this to `"@aws-amplify/cli-extensibility-helper": "^3.0.11"`, but still see the same output.

**Comment by thomas5631** [comment]
I managed to find the issue - I had also pinned my node version to `16.14.2`. Unpinning the version and using the default of `16.19.0` has fixed the problem. Thanks for the help @ykethan! I'll close this issue now
