### ISSUE TITLE
Control generated Input 

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#1301]
So image the scenario where you're using a cache to maintain counts.

````
type Post @model {
  id: ID!
  commentCount: Int!
}
````

When querying, commentCount will always be non-null, but the generated Input type forces the commentCount field to be passed, when, in fact, we would be defaulting this to 0 in the mapping template.

````
input CreatePostInput {
  id: ID
  commentCount: Int!
}
````

There should be a field-level directive (@optional) or similar that will control how the corresponding input is generated.

````
type Post @model {
  id: ID!
  commentCount: Int! @optional
}
````

**Comment by wizawuza** [comment]
Omit the "!" after Int, and commentCount won't be required.
For example, change it to:
```
type Post @model {
  id: ID!
  commentCount: Int
}
```

**Comment by CodySwannGT** [comment]
Right, but on read, commentCount will never be null, so that isn't correct.

**Comment by CodySwannGT** [comment]
Actually, 1.6.3 allows you to include input types directly in your schema.grapql file and will not generate them if it sees they're already there.

Perfect
