### ISSUE TITLE
Ability to create a TypeScript Lambda function with the CLI

### ISSUE THREAD

**Issue by chrisl777** [aws-amplify/amplify-cli#13029]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

When creating a new Lambda function using the Amplify CLI, I walk through the CLI questions and finish. 

But then I have to do an extraordinary amount of copy and paste from other past solutions to make the function work with TypeScript. And even then, though I follow the Amplify docs, I still end up doing a bit of "guess and check" to get it working. 

### Describe the solution you'd like

It would be ideal to be able to specify "TypeScript" when running through the CLI options while creating the function. 

### Describe alternatives you've considered

I haven't considered other alternatives. Perhaps Nx may have an ability to generate a TypeScript Lambda. Though I am typically using Turborepo. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @chrisl777, thank you for reaching out. The feature is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/659. It would be great if you could thumbs up the issue.

Closing the issue as duplicate.

**Comment by chrisl777** [comment]
@ykethan Perfect, done! And thank you!
