### ISSUE TITLE
Create Cloudwatch Alarms for Lambda Functions

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1302]
**Is your feature request related to a problem? Please describe.**
What's the plan / proposed way to create alarms for lambda functions created in amplify cli. 

**Describe the solution you'd like**
Should the CLI manage alarms for these functions? Or should developers set them up manually? And it seems these alarms might need different settings in prod vs dev environments, or only enabled in prod. 

**Describe alternatives you've considered**
Currently setting them up manually through AWS console.

**Comment by UnleashedMind** [comment]
Currently the Amplify CLI does not create or manage CloudWatch alarms for lambda functions, you will have to manually create and manage them on the AWS CloudWatch console. 
I will also mark this as a feature request, the team will review it.

**Comment by yuth** [comment]
This feature request is put in the backlog. Our product manager will take a look at this issue and get it prioritized.

**Comment by kaustavghosh06** [comment]
@hisham I think the best way to go about this would be by manually managing them since this would vary vastly between different devs and projects.
