### ISSUE TITLE
Amplify CLI Sign in with Apple not working

### ISSUE THREAD

**Issue by howardkitto** [aws-amplify/amplify-cli#13048]
### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v18.13.0

### Amplify CLI Version

12.2.3

### What operating system are you using?

MaC

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I am trying to integrate a swift app using "Sign in with Apple" and my AWS back-end using Amplify.

I am trying to follow these instructions

URL page where content issue is:
https://docs.amplify.aws/lib/auth/social/q/platform/ios/

```
The configure auth category is inaccurate:
➜  $ amplify add auth
➜  Peakflow git:(AppleId) ✗ amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
 What domain name prefix do you want to use? ###
 Enter your redirect signin URI: myapp://
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: myapp://
? Do you want to add another redirect signout URI No
 Select the social providers you want to configure for your user pool: 
✅ Successfully added auth resource ### locally
```
I selected Sign in with Apple but the options to configure the social provider (as described in the instructions) are not shown and the resulting configuration is not complete (no social providers have been created):
```

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-west-2:###",
                            "Region": "eu-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-west-2###",
                        "AppClientId": "###",
                        "Region": "eu-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "###.auth.eu-west-2.amazoncognito.com",
                            "AppClientId": "###",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],  //No details are configured here
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}
```

### Expected behavior

I expected 

1. To be prompted to enter the Apple service details
2. For user and identity pools to be created
3. For the amplify config files to be updated within my swift project

### Reproduction steps

1. amplify add auth
2. select social sign-in with Apple

### Project Identifier

Project Identifier: ddd701997ab3e0fdb790cbfa0d51f2b7
[report-1690993820391.zip](https://github.com/aws-amplify/amplify-cli/files/12242534/report-1690993820391.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @howardkitto, thank you for reaching out. From the `aws-amplify-cli/2.0` I understand this is the `amplifyconfiguration.json` file. Was the auth resource pushed(`amplify push`) after the resource was created/updated?
As the attribute should get generated in the `amplifyconfiguration.json` file once we push. 

Additionally, If you would like to verify if the `socialProviders` has been added currently before a push, we can check the `backend-config.json` file present under the backend folder.

**Comment by howardkitto** [comment]
1. Yes, this is after `amplify push`
2. To be clear: once I select `Sign in with Apple` as a social provider the script exits and does not give me the opportunity to enter the apple credentials, so it it not surprising that no social providers are created. I suspect that is the location of the bug.

**Comment by ykethan** [comment]
Hey @howardkitto, 
> once I select Sign in with Apple as a social provider the script exits and does not give me the opportunity to enter the apple credentials

curious on this behaviour as i was unable to reproduce this issue in my environment. It would be great if you could provide us some additional information on the terminal being utilized and a screenshot/video of the behaviour?
Does running `amplify update auth` and updating the `sign in with apple` auth flow, have a similar behaviour?

**Comment by howardkitto** [comment]
Here is a screen recording:

https://drive.google.com/file/d/15PYPVeZyochQzqMIHhaKejuitAdtszvd/view?usp=sharing

Hopefully you can see that when I select Sing in with Apple there are no further options.
I just confirmed that the same thing happens when I use `amplify update auth`

**Comment by ykethan** [comment]
@howardkitto thank you for the video, this helped us in diving into the issue.
When selecting the `Sign in with Apple`, we need to use the <kbd>Spacebar</kbd> button for a selection instead of <kbd>Enter/return</kbd>.

The flow would show as follows until we hit <kbd>Enter/return</kbd>

https://github.com/aws-amplify/amplify-cli/assets/87995712/f4281964-70d5-45f5-ad0c-59d9d537651e

**Comment by howardkitto** [comment]
Oh wow I'm such a dufus! Thank you so much

**Comment by howardkitto** [comment]
Oh wow - I'm such a dufus. Thank you so much
