### ISSUE TITLE
Error on `amplify add storage` - ? Please choose partition key for the table

### ISSUE THREAD

**Issue by TomWhitehead-Evo** [aws-amplify/amplify-cli#1304]
**Bug**
When running `amplify add storage` and choosing a NoSQL Database, on the question `? Please choose partition key for the table:` no options are listed with the error:

> /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^
TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/inquirer/lib/prompts/list.js:121:53)

**To Reproduce**
1. run `amplify add storage`
2. select NoSQL Database
3. fill in table/column options
4. Error on ? Please choose partition key for the table

**Desktop:**
 - OS: macOS Mojave 10.14.4
- @aws-amplify/cli@1.6.3

**Additional context**
Amplify Auth is already setup in the project.

**Comment by UnleashedMind** [comment]
@TomWhitehead-Evo 
I was not able to reproduce the bug. 
It looks like a corrupted installation, please try to remove the amplify-cli and install it again.

**Comment by TomWhitehead-Evo** [comment]
I have re-installed the amplify-cli globally and the aws-amplify module in the project locally and still encounter the same error.
