### ISSUE TITLE
Categories not listed in Amplify Console - Only shown locally via amplify cli

### ISSUE THREAD

**Issue by speedhawk21** [aws-amplify/amplify-cli#13058]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.1

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac Ventura 13.4

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A - No manual changes were made

### Describe the bug

After adding api and a function and running 'amplify push -y', the services are correctly deployed.  Running 'amplify status' returns the correct service categories.  However, none of these changes are reflected in the Amplify Console.  When I navigate to the authentication section, it is showing a 400 error in the browser console indicating it is unable to find the user pool id.  

amplify status

    Current Environment: dev
    
┌──────────┬─────────────────┬───────────┬───────────────────┐
│ Category │ Resource name   │ Operation │ Provider plugin   │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Auth     │ flippera50fe6c3 │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ flipperapi      │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Api      │ flipperapi      │ No Change │ awscloudformation │
└──────────┴─────────────────┴───────────┴───────────────────┘

### Expected behavior

The expected behavior should be that all services deployed through amplify cli be listed in the amplify console.  

### Reproduction steps

Unable to reproduce.  This is an older project and I'm afraid that this is related to a version mismatch or some backward compatibility issue with older projects.  

### Project Identifier

Project Identifier: aa8a26493b97a7b17362c7ce1179e3a8

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

App ARN
arn:aws:amplify:us-west-2:877398883231:apps/d1cgplhw4ff2fc

Here is the error from the Amplify Console:

Failed to load resource: the server responded with a status of 400 ()
vendors.js:1 Uncaught (in promise) ResourceNotFoundException: IdentityPool 'us-west-2:ffd8f958-9e91-4874-8f8d-1fdd3ef63a20' not found.
    at constructor.extractError (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:1529477)
    at constructor.callListeners (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:1702041)
    at constructor.emit (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:1701751)
    at constructor.emitEvent (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2147407)
    at constructor.e (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2142924)
    at r.runTo (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2149269)
    at https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2149475
    at constructor.<anonymous> (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2143194)
    at constructor.<anonymous> (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:2147463)
    at constructor.callListeners (https://a.b.cdn.console.awsstatic.com/a/v1/376RUGPLZAU3JQ45XBPUB643ZJO7R4QP57YNKBO2ZEBQRI4DNTVQ/vendors.js:1:1702147)

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @speedhawk21, thank you for reaching out. Wanted to get some clarification on the console being utilized, is this the AWS Amplify console or the Amplify Studio console throwing the error on the authentication section?

For example: AWS console
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/0651dc74-28da-4608-864a-4b9b840fc90d)

Amplify Studio:

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/a1286566-43a3-408c-a726-472250df0108)

**Comment by speedhawk21** [comment]
It is the regular AWS amplify console.  I don't have studio enabled.  On Aug 4, 2023, at 10:10 AM, Kethan sai ***@***.***> wrote:﻿
Hey @speedhawk21, thank you for reaching out. Wanted to get some clarification on the console being utilized, is this the AWS Amplify console or the Amplify Studio console throwing the error on the authentication section?
For example: AWS console

Amplify Studio:

**Comment by ykethan** [comment]
Hey @speedhawk21, thank you for information. The AWS Amplify console currently does not list the API gateway resources. The API tab is expected to display the GraphQL API added to the project. 

> ResourceNotFoundException: IdentityPool 'us-west-2:ffd8f958-9e91-4874-8f8d-1fdd3ef63a20' not found. This is an old identity pool that has been updated to a new cognito instance, using amplify cli.

Tried reproducing the issue but did not observe any errors in the AWS Amplify console -> Authentication tab.  Could you provide us some additional information on how the auth resource was updated? for example prompt selection or manual updates etc.

**Comment by speedhawk21** [comment]
No, API and Functions should be listed in Backend Environments under deployment status.  The Authentication service that is listed goes to a broken page, attempting to pull an old Identity, which I have updated.  I have other amplify projects that show API and Functions listed on this page, so something is definitely broken with this project.  How do I resolve this?  The amplify web console is totally useless for this project.  

Please see the screen shot showing API and Functions are not listed, when they should be.  

<img width="786" alt="no-amplify-services" src="https://github.com/aws-amplify/amplify-cli/assets/8126555/640f8c7e-9a90-4a1e-b159-94b628869cec">

**Comment by speedhawk21** [comment]
Going to remove and rebuild the project.
