### ISSUE TITLE
Problem with auth migration

### ISSUE THREAD

**Issue by dan-hook** [aws-amplify/amplify-cli#13093]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.17.0

### Amplify CLI Version

12.2.3

### What operating system are you using?

Ubuntu (on WSL2)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made, to the best of my knowledge.  

### Describe the bug

I have an amplify environment that was last deployed with amplify 7.6.19
When I run amplify push, I get:
"Auth triggers have been configured using an older version of the CLI and must be migrated before they can be deployed"
Then running amplify update auth I eventually get "Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined"

The user pool does have a post confirmation trigger.  

vscode ➜ /workspaces/gene-panel-api/project (sandbox)(1.3vanilla ✗) $ amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Create your own module
Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined

### Expected behavior

I'm hoping to successfully migrate the auth trigger to the current version of the CLI.  

### Reproduction steps

1. I'm not sure how to reproduce this.  If I had to, I would create an auth resource with 7.6.19 
2. add a post confirmation trigger 
3. upgrade to 12.2.3
4. run amplify update auth

### Project Identifier

c37455c75a0b236cc110a2f4c2509776

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @dan-hook :wave: thanks for raising this! As we begin to look at this in more depth would you mind running the same command with `--debug` and paste the stack trace here?

**Comment by dan-hook** [comment]
It didn't display a stack trace:
vscode ➜ /workspaces/gene-panel-api/project (sbxc)(v1.4upgrade ✗) $ amplify update auth --debug
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

cli-inputs.json doesn't exist
✔ 
A migration is needed to support latest updates on auth resources.
Recommended to try in a non-production environment first. Run "amplify env add" to create or clone an environment.
Custom CloudFormation changes will NOT be preserved. Custom changes can be made with "amplify auth override" after migration.
Learn more about this migration: https://docs.amplify.aws/cli/migration/override
Do you want to migrate auth resource "genepanelapi8323d4d5"? (Y/n) · yes
Starting Migration Process
Migration is Successful
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
Error updating the Cognito trigger: The "path" argument must be of type string. Received undefined

**Comment by josefaidt** [comment]
Hey @dan-hook it's interesting that did not print a stack trace. I'll work with the team to resolve that, but

> Would it be worthwhile to try removing the trigger using amplify 7.6.19, then migrating without it, and adding it back using the latest amplify?

Yes, this would be the easiest path forward, however I'd like to take a look at what may be going wrong in the migration before you do so. Would you be open to sharing a zip archive of your `amplify/` directory? (without sensitive information)

**Comment by dan-hook** [comment]
Removing the trigger and then re-adding worked.  There probably won't be that many users going from version 7 to 12.  Thanks for your time.
