### ISSUE TITLE
Lack of line number/file name when error occurs stalls development

### ISSUE THREAD

**Issue by BarberEngineering** [aws-amplify/amplify-cli#1309]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
Others have requested amplify to be more 'verbose' and the requests get closed so here's an example.

? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types? This will overwrite your current graphql queries, mutations and subscriptions Yes
- Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
× An error occurred when pushing the resources to the cloud

Invalid input for parameter key AuthRoleName. Need to specify either usePreviousValue as true or a value for the parameter

**To Reproduce**
1. amplify auth had to be manually removed (couldn't deploy or remove due to yet another issue, related here but manually removing the entries was my only workaround)
2. Auth doesn't show under amplify status any more but obviously in one of my other items Auth role lingers

**Expected behavior**
"awsconfiguration.json line 56: Invalid input for parameter key.." thus letting me know what item is sending an AuthRoleName parameter

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chome
 - Version 1.5 (amplify)

**Additional context**
The lack of what amplify is doing wastes hours of research time usually followed with deleting everything then redeploying which is a terrible resolution. Please add a way to see what amplify is doing

**Comment by UnleashedMind** [comment]
@BarberEngineering 
Thanks for the feedbacks, we will discuss among the team.

**Comment by kaustavghosh06** [comment]
@BarberEngineering Could you please show your terminal logs? Which version of the CLI are you using?

**Comment by BarberEngineering** [comment]
Didn't save it and I removed everything and started new since I was told where the issue was. Wasted a day blind hunting then gave up. Was newest cli - 1.6.3

"Another example -  Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack" - every time we hit this it pretty much means hang it up, delete the resource and redeploy. Example output below. As a user, what is this telling me to do next? Ask it nicer? There's no '-force' and no actual indication of where / what it choked on so it's putting on the blindfold birdbox style. It's no big deal when you're just trying stuff out but if this was anywhere near prod, deleting the resource and starting over isn't really an option when you have real data.

UPDATE_ROLLBACK_COMPLETE stackname AWS::CloudFormation::Stack Wed Apr 24 2019 09:38:55 GMT-0500 (Central Daylight Time) 

DELETE_COMPLETE          authcognito                        AWS::CloudFormation::Stack Wed Apr 24 2019 09:38:54 GMT-0500 (Central Daylight Time) 

UPDATE_IN_PROGRESS       analytics         AWS::CloudFormation::Stack Wed Apr 24 2019 09:38:54 GMT-0500 (Central Daylight Time) 

UPDATE_IN_PROGRESS       storages3                  AWS::CloudFormation::Stack Wed Apr 24 2019 09:38:54 GMT-0500 (Central Daylight Time) 

UPDATE_IN_PROGRESS       authcognito                    AWS::CloudFormation::Stack Wed Apr 24 2019 09:38:54 GMT-0500 (Central Daylight Time) 

⠙ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack

⠹ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete

> @BarberEngineering Could you please show your terminal logs? Which version of the CLI are you using?

**Comment by kaustavghosh06** [comment]
@BarberEngineering We enhanced our cloud formation logging capabilities to point you to the exact resource/template if which you're having an issue with. Please take a look at the latest version of the CLI and let me know if you have more suggestions.
