### ISSUE TITLE
Considerations for Windows support without WSL

### ISSUE THREAD

**Issue by kavengagne** [aws-amplify/amplify-cli#131]
** Which Category is your question related to? **
aws-amplify cli

** Provide additional details e.g. code snippets **
Hi guys,
My main question would be: what are your plans for Windows support?
The CLI is not currently working on Windows without the Windows Subsystem for Linux.

I suspect many Windows developers will be puzzled by the problems they will face when using the WSL.
Adding to the fact that people using awsmobile-cli are being recommended aws-amplify/cli as the new cli to use.

I can help and try to find what are the causes of the problems on Windows and try to fix them but I would prefer to know the direction of the project beforehand.

Thank you,
Kaven

**Comment by kaustavghosh06** [comment]
@kavengagne  Thanks for all the help you've provided for making the CLI work on windows and also submitting a PR to fix the windows issues with Gluegun! Appreciate the contribution.

We do want to support windows but were suggesting using WSL due to the Gluegun dependency issue which you fixed.

**Comment by LosD** [comment]
@kaustavghosh06 If you just dropped that stupid menu system as a requirement for using amplify-cli, most issues would be gone instantly (and it could be scripted).

It's a pretty poor CLI when it can't run non-interactive.

**Comment by kaustavghosh06** [comment]
@LosD that’s exactly what hat we’re working on at the moment. Checkout this PR - https://github.com/aws-amplify/amplify-cli/pull/371

**Comment by LosD** [comment]
@kaustavghosh06 ah, that's perfect! Thanks for the heads up 🙂

**Comment by undefobj** [comment]
@LosD we are working on this as mentioned. One thing I would like to comment on though is your statements using words like "stupid". Please be respectful when commenting in our issues and [follow our Code of Conduct as outlined](https://github.com/aws-amplify/amplify-cli/blob/master/.github/CODE_OF_CONDUCT.md). We endeavor to make the experience great for all customer workflows, but we want to do so in a respectful and welcoming environment.

**Comment by LosD** [comment]
@undefobj I'm sorry, you're absolutely right.
