### ISSUE TITLE
Environment name is invalid.

### ISSUE THREAD

**Issue by foobarnes** [aws-amplify/amplify-cli#13101]
### Amplify CLI Version

12.2.3

### What operating system are you using?

macOS 13.4 (22F66)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I cannot `amplify env checkout [...]` one of my environments.

```shell
:) > amplify env checkout jason
🛑 Environment name is invalid.
[...]
```

```shell
:) > amplify env list        

| Environments |
| ------------ |
| *dev         |
| prod         |
| jason        |
```

```bash
:) > amplify env remove jason
🛑 Environment name is invalid.
[...]
```

```shell
:) > amplify pull --appId {{AMPLIFY_APP_ID}}
🛑 Environment 'jason' not found.
[...]
```

I was able to "select" the jason env like so:
```shell
:) > amplify env add jason
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile
✖ Initializing your environment: jason
✖ There was an error initializing your environment.
🛑 Could not initialize platform for 'jason': Missing required key 'Bucket' in params
```
```shell
:) > amplify env list        

| Environments |
| ------------ |
| dev          |
| prod         |
| *jason       |
```
```shell
:) > amplify status  
🛑 File at path: '[...]/amplify/#current-cloud-backend/amplify-meta.json' does not exist

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
[...]
```

### Expected behavior

Expected to be able to check out 

### Reproduction steps

I'm not sure how I got myself into this mess 🤷‍♂️

### Project Identifier

aae37be032a2f135dcdf89710fccdf92

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by foobarnes** [comment]
Thanks, @ykethan, where is `local-aws-info.json`? I can't find it. I don't have a `.config` directory in my `amplify` directory.

**Comment by ykethan** [comment]
@foobarnes the file may be hidden in VSCode, in you project directory under `.vscode` -> `settings.json`. set the `amplify/.config` as `false`.

**Comment by foobarnes** [comment]
Amazing, thank you so much! I need to learn my VSCode better 🥲

Trying now.
