### ISSUE TITLE
Is there a 'best practice' way to create SES Email Templates with Amplify?

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-cli#1310]
** Which Category is your question related to? **
None, really

** What AWS Services are you utilizing? **
SES

** Provide additional details e.g. code snippets **
Here's our use case:
Lambdas (built using amplify) are going to use SES templates to send emails. We could construct these templates using a separate cloudformation stack, but we would like to integrate them into our amplify backend (so that different environments can test different templates, etc). Is there a best way to do this?
Off the top of my head, I know we could put a cloudformation template under `api/stacks` (as a custom resource), but this feels very wrong, as that folder is really meant for connecting custom resources to AppSync.

**Comment by zjullion** [comment]
I suppose this is very much related to: https://github.com/aws-amplify/amplify-cli/issues/80

**Comment by kaustavghosh06** [comment]
@zjullion Currently, the way to implement this would be to implement a plugin for the same until we have support for a functionality mentioned in #80

**Comment by zjullion** [comment]
Found my own solution: https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916
