### ISSUE TITLE
Disabling automatic builds for functions

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [aws-amplify/amplify-cli#13107]
### Amplify CLI Version

12.1.1

### Question

I am using AWS Amplify for a rather simple web-based application. I have a few Lambda functions for this application, most of which are integrated with API Gateway. I recently started attempting to clean up my Lambda functions and reduce duplicated code. Due to my aversion to using Lambda Layers, I decided to adopt a custom build system that utilizes TypeScript and Webpack. I have a few scripts that bundles my lambda functions, zips them up, and runs `aws cloudformation package` to get them into S3 in preparation for `amplify push`. However, because there isn't a documented way to prevent Amplify from doing automatic builds for Lambda functions, I am constantly fighting Amplify for control over both the code and the CloudFormation templates for each of my functions. 

I have found that changing the `"build"` property in `amplify-meta.json` will tell Amplify not to touch Lambda functions and only deploy the CloudFormation template. However, from reading documentation, I figure that modifying `amplify-meta.json` isn't the best idea.

So, is there a way to instruct Amplify to let me have complete control over the build process for my Lambda functions?

**Comment by ykethan** [comment]
Hey @ChapterSevenSeeds, thank you for reaching. Unfortunately, the build process cannot be skipped for function build.
Curious, are you currently utilizing Amplify hooks to custom build the functions?
As Amplify CLI functions now support creating custom build command or script path using `amplify add function ` or modify the `amplify.state` file in the `function/src` folder. This was released in Amplify CLI v12.2.0
https://github.com/aws-amplify/amplify-cli/releases/tag/v12.2.0

for example modifying the script block to provide a custom command or script path.
```
{
  "pluginId": "amplify-nodejs-function-runtime-provider",
  "functionRuntime": "nodejs",
  "useLegacyBuild": true,
  "defaultEditorFile": "src/index.js",
  "scripts": {
    "build": "npm install --no-bin-links --production"
  }
}
```

**Comment by ChapterSevenSeeds** [comment]
@ykethan I am not using Amplify hooks to custom build the functions. I can look into that a bit more and experiment with it.

As for modyfing the `amplify.state` file, where does amplify expect me to place the build output? If my build command just transpiles `index.ts` to `index.js`, where should I have TypeScript put `index.js` so that Amplify can use it?

**Comment by ykethan** [comment]
Hey @ChapterSevenSeeds, the build output should the `/src`. Additionally, you may have to create your ts files outside the src folder to avoid zipping them.

**Comment by ChapterSevenSeeds** [comment]
@ykethan So, if I do this with a hook, I could do a pre-build-function hook which would run my webpack build, which would place the bundled files in their corresponding `/src` folders. Does that sound like it would work?

**Comment by ykethan** [comment]
Hey @ChapterSevenSeeds, using the pre-build hook should also work for the use case, but i recently filed a bug about the function build hooks here: https://github.com/aws-amplify/amplify-cli/issues/12746.
