### ISSUE TITLE
Optionally configure a PermissionsBoundary on IAM Roles

### ISSUE THREAD

**Issue by erik-am** [aws-amplify/amplify-cli#1311]
**Is your feature request related to a problem? Please describe.**
My team works in a corporate environment where each team has their own AWS account with some restrictions imposed by the company policies. One of those is that _every IAM Role should include a certain permissions boundary_.

Unfortunately there's not a way to include a permissions boundary in the IAM Roles that amplify-cli will generate in the CloudFormation stack. Because the "rootStackTemplate.json" already has IAM Roles, it means even the initialization of a new project will fail.

**Describe the solution you'd like**
It would be great if there was a possibility to configure a permissions boundary ARN that would be included on every generated IAM Role. This ARN is dependent on the environment. It could maybe be a parameter in `team-provider-info.json`.

**Describe alternatives you've considered**
Our team worked around this limitation by modifying the Amplify CLI source files on our local machines as follows:

 *  Edit `/usr/local/lib/node_modules/\@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/rootStackTemplate.json` and add `"PermissionsBoundary": {"Fn::Sub": "<ARN of boundary>"}`, to both AuthRole and UnauthRole.

*   `cd /usr/local/lib/node_modules/\@aws-amplify/cli/node_modules/graphql-dynamodb-transformer/`
    Edit `src/resources.ts` and add the following snippet to the `makeIAMRole` function:
    `PermissionsBoundary: Fn.Sub('<ARN of boundary>', {}),`
    Run `npm run-script build` to recompile the Typescript code.

*   The auth template is the only template we changed in our local project, because you will often generate it once and then extend it. You find this template in `amplify/backend/auth/<name>/<name>-cloudformation-template.yml` where you have to add `PermissionsBoundary: !Sub <ARN of boundary>` to the UserPoolClientRole.

Of course this is not a sustainable solution, as it means the CLI is hardcoded to a single environment.

**Additional context**

**Comment by UnleashedMind** [comment]
@erik-am 
Thanks for your feedbacks, I've marked this as feature request. 
It'd be great if you could suggest a cli workflow for this feature, e.g. should the CLI prompt for permission boundary ARN during 'amplify init' and 'amplify add auth', or should it be configure using 'amplify configure project'>

**Comment by mjavadi** [comment]
@UnleashedMind , our organiztion is in a similar situation where our IAM roles (we login via SSO and assume a role)  are ONLY allowed to be created if they include a security boundary as well as a prefix in the name.  The policies (if created separately) would have also fail if they don't have the require prefix in the name.  Many of the wizards in the AWS console or CLI based tools that don't allow selection of existing roles, run into an issue in our environment. I have mentioned this issue to our TAM, but wanted to also add the comment here before pointing the TAM to this article/issue.  

I am still fairly new to Amplify but I would think as part of configure project (amplify configure) where you pick the profile you could specify the arn for the boundary as the prefix for the names to be used (for role and policy).  The prefix could be used as part of other pieces if that make more sense (the CF stack, the S3,etc).

Thank you

**Comment by timclayton76** [comment]
@UnleashedMind, I'm really surprised this wasn't added as part of the initial release of the Amplify CLI, much less added since. Without it, the CLI is essentially useless for anyone in a medium to large organization or government role. You've essentially told us your market is small companies only. Mind blown.

I had to work around this limitation by configuring and deploying to a personal AWS account, then I had to provision everything by hand to match. And the Lambda integration still isn't working.

Very disappointed.

**Comment by machender1** [comment]
We have the same problem, do we have a solution for this?

**Comment by headstrongsolutions** [comment]
I'm also suffering similar issues, and having trouble understanding the local changes erik-am proposed as an interim measure, so is there any time-line on this?

Seems to me that a PermissionsBoundary is a good thing to use to secure down IAM roles from accidentally dangerous actions, therefore having the Amplify CLI be able to utilise this would be beneficial.

**Comment by renebrandel** [comment]
Hey folks - we're looking into this feature right now and using this as a tracking issue to prevent duplications. https://github.com/aws-amplify/amplify-cli/issues/4618
