### ISSUE TITLE
Is it possible to have Cloudfront+S3 on the main branch and Amplify hosting on feature branches?

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws-amplify/amplify-cli#13139]
### Amplify CLI Version

12.1.1

### Question

I'm using Cloudfront+S3 hosting for my Production environment.

I work with multi account setup. My Production environment is deployed with `amplify push` and `amplify publish` commands from the `main` branch in the "production AWS account".

Is it possible to have feature branches using the built-in Amplify hositng with authentication and continuous deployment in a separate AWS account?

**Comment by josefaidt** [comment]
Hey @ggorge-etiqa :wave: thanks for raising this! I believe you can accomplish this by manually logging in to your separate AWS account and link the repository from the AWS Amplify console. From there you will be able to enable feature branch deployments, while using your existing workflow to promote to production

**Comment by ggorge-etiqa** [comment]
@josefaidt I probably didn't understand your answer, could you link me some documentation?
If, on the other hand, my question is not clear, which is why I also changed the title, I would like to know if it is possible to have main branches hosted on Cloudfront+s3 and feature branches hosted on amplify hosting.

**Comment by josefaidt** [comment]
Hey @ggorge-etiqa my apologies, you can [create a new Amplify app and connect the git repository](https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html#step-1-deploy-frontend). From there you can enable feature-branch deployments that use their own backend. This is somewhat similar to our [team workflows doc](https://docs.amplify.aws/cli/teams/overview/) where you have:

- Amplify app 1 with a "main" environment (with its own App ID)
- Amplify app 2 that deploys feature branches (with a separate App ID)

**Comment by josefaidt** [comment]
Hey @ggorge-etiqa are you still experiencing this?

**Comment by ggorge-etiqa** [comment]
@josefaidt at the end I've chosed to use amplify managed hosting and configure a CloudFront CDN for production outside amplify.
