### ISSUE TITLE
RDS Plugin add-graphql-datasource is not honoring the CLI profile selected

### ISSUE THREAD

**Issue by mobilequickie** [aws-amplify/amplify-cli#1314]
**Describe the bug**
Amplify CLI is unable to see any RDS Aurora Serverless Clusters when using the 
add-graphql-datasource plugin. Yes, the cluster is in us-east-1 and Data API enabled.

**To Reproduce**
1. Amplify init
2. Select a NON-DEFAULT profile
3. Amplify add api, select GraphQL, API key, and all the defaults
4. $ amplfiy add-graphql-datasource
Results: No RDS cluster found

**Expected behavior**
A list of RDS Aurora Serverless clusters to choose from

**Screenshots**

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser Chrome
-  CLI Version: 1.6.3

**Additional context**

**Comment by mobilequickie** [comment]
Issue:  add-graphql-datasource is not showing the list of RDS Serverless Clusters when a user initializes an Amplify project (amplify init) using a non-default profile

Reason: The add-graphql-datasource plugin is using the default aws profile when looking for any RDS clusters instead of using the credentials from the specified profile during thie 'amplify init'.

**Comment by DaryMerckensGT** [comment]
Just as a dumb workaround until this is fixed, if you set whatever profile you're trying to use as the default one and have it source from the original default renamed as "real_default" or "OG_default", that'll work.
