### ISSUE TITLE
add-graphql-datasource - Not all AWS Secrets shown after selecting RDS Cluster 

### ISSUE THREAD

**Issue by mobilequickie** [aws-amplify/amplify-cli#1315]
CLI: 1.6.3

Issue: Using 'add-graphql-datasource' to connect my RDS Serverless cluster, it does not list all the avaialable AWS Secrets. I currently have 13 AWS Secrets in the us-east-1 region and this plugin is only showing 10. One of the remaining 3 is my actual secret needed to access the selected cluster.

1. add-graphql-datasource
2. select cluster
Actual Result: Only 10 max AWS secrets available to choose from.
Expected: Show all the secrets or pull the cluster's associated secrets, if that's possible.

Blocked

▶ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your API: my-serverless-cluster-rdsauroraserverlesscluster-ntj6ue34ehi1
? Select the secret used to access your Aurora Serverless cluster: 
  rds-db-credentials/cluster-<redacted>/mymasteruser 
  rds-db-credentials/cluster-<redacted>/mymasteruser 
  rds-db-credentials/cluster-<redacted>/mymasteruser 
❯ aurora-serverless-http-cluster-secret 
  rds-db-credentials/cluster-<redacted>/masteruser 
  rds-db-credentials/cluster-<redacted>/masteruser 
  rds-db-credentials/cluster-<redacted>/dennis

**Comment by mikeparisstuff** [comment]
@ashwindevendran is looking into this.

**Comment by kaustavghosh06** [comment]
The fix fo this issue was merged and released into the latest version of the CLI
