### ISSUE TITLE
Customizing API REST Endpoint

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#13156]
### Amplify CLI Version

12.3.0

### Question

I need to create an endpoint with the following criteria:

- Has caching on the server side
- Uses domain
- Can set api keys for customers and set usage plans
- Has rate limit

1. Is there a way to set this on amplify?
2. I was looking at [this](https://docs.amplify.aws/cli/custom/cdk/) but I'm not sure exactly how this fits in with the whole amplify ecosystem, is is different from `amplify override api`?

I need some high level guidance on this matter to create a scalable paid endpoint with the above criteria (which I can also use internally)

Note:

I tried using the cache for example while using the override method like the code below and it doesn't work:
```
import { AmplifyApiRestResourceStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiRestResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
    resources.cache = {
        enabled: true,
        ttl: Duration.seconds(3600),
    };
}
```

**Comment by ykethan** [comment]
Hey @afern247, thank you for reaching out. I was able to utilize the following example to add rate limit, cache and API key.

```
resources.deploymentResource.stageDescription = {
    throttlingRateLimit: 1,
    cacheClusterEnabled: true,
    cacheTtlInSeconds: 3000,
    cacheClusterSize: "0.5",
  };

  resources.restApi.apiKeySourceType = "HEADER";
  resources.restApi.body.securityDefinitions = {
    ...resources.restApi.body.securityDefinitions,
    "use-api-key-in-header": {
      type: "apiKey",
      name: "x-api-key",
      in: "header",
      "x-amazon-apigateway-api-key-source": "HEADER",
    },
  };
  const custSecurityRules = [{ "use-api-key-in-header": [] }];
  Object.values(resources.restApi.body.paths).forEach((path: any) => {
    path.options.security = custSecurityRules;
    path["x-amazon-apigateway-any-method"].security = custSecurityRules;
  });
```
originally solution posted on [rate limit](https://github.com/aws-amplify/amplify-category-api/issues/938) and [API key]( https://discord.com/channels/705853757799399426/1087775709235269663/1088952240099836006)

additionally, the discord thread provides an [example](https://discord.com/channels/705853757799399426/1087775709235269663/1088953501348020274) to setup usage plans using Amplify custom cfn resource. 

Currently, the use cases are feature requests here: https://github.com/aws-amplify/amplify-category-api/issues/938, https://github.com/aws-amplify/amplify-category-api/issues/438. Please feel free in adding a thumbs up.

> I was looking at [this](https://docs.amplify.aws/cli/custom/cdk/) but I'm not sure exactly how this fits in with the whole amplify ecosystem, is is different from amplify override api?

To clarify, Amplify overrides enables extending functionality on resource created by Amplify CLI. Amplify custom resources provides functionality to create resource that are not supported as first-class categories in the Amplify ecosystem.

**Comment by afern247** [comment]
thanks for the info
