### ISSUE TITLE
Amplify Studio scripts for "Try without AWS" are incomplete for fresh MacOS Silicon installs

### ISSUE THREAD

**Issue by thatdogmachine** [aws-amplify/amplify-cli#13155]
### How did you install the Amplify CLI?

curl - following the instructions at https://sandbox.amplifyapp.com/

### If applicable, what version of Node.js are you using?

n/a

### Amplify CLI Version

after taking corrective actions: 12.3.0

### What operating system are you using?

Mac M2 / silicon

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I elected to build a `to-do list`, with `flutter`

I accepted the defaults for `Data modeling`

then

```
curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

```

### Describe the bug

`curl... install...` fails with:
`Error: Amplify CLI failed to install...`

### Expected behavior

`Successfully installed...`

### Reproduction steps

`curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL`
on a fresh MacOS Silicon installation

### Project Identifier

n/a - issue is not related to the project, but the amplify install script / instructions

### Log output

n/a

### Additional information

This appears to be a side effect / consequence of what was discussed in https://github.com/aws-amplify/amplify-cli/issues/10193

As mentioned in https://github.com/aws-amplify/amplify-cli/issues/10193#issuecomment-1132201405 a workaround / solution is:
`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`

Rosetta will not be present on a fresh MacOS install, which may be representative of the less technical audience Amplify appears to want to cater to.

I've logged this as a new issue, as I'm reporting the fact this breaks the minimum viable setup experience in Amplify Studio, and thus may discourage people from exploring further.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @thatdogmachine :wave: thanks for raising this! This is a [known issue](https://github.com/aws-amplify/amplify-cli/issues/10193), and you will need to install Rosetta for Amplify CLI

```
softwareupdate --install-rosetta
```

**Comment by ykethan** [comment]
Documentation PR has been merged, closing issue.
