### ISSUE TITLE
API & Lambda function deleted by themselves

### ISSUE THREAD

**Issue by amit23234** [aws-amplify/amplify-cli#13171]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.14.0

### Amplify CLI Version

12.3.0

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I created 2 apis and 1 lambda function using the aws amplify cli in vs code. The resources were created in the respective consoles (api gateway & lambda) but then got deleted by themselves. 
Project Identifier: afb65268e8b881b747c160a78535b9e4

### Expected behavior

they shouldn't have automatically deleted.

### Reproduction steps

1. amplify push

### Project Identifier

afb65268e8b881b747c160a78535b9e4

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @amit23234, thank you for reaching out. On diving into the project logs observed this status `UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS`. Did you observe any failed push, because if the push failed this may cause the resources to rollback and remove them. Could you open the AWS CloudFormation console for the project stack and check for any error messages and present status of the stack.

**Comment by amit23234** [comment]
I don't see the api or the lambda function in CloudFormation. But this is
weird, because I was able to see the api and function in *API Gateway* and
*Lambda* respectively for like 5 minutes. When I hit refresh, it just
disappeared! Same with the REST API endpoint I got after the
*'amplify push'* command - it worked for 5 minutes (giving the 'Hello
Lambda' output) before it said internal error. The weird part is that I was
still showing the apis & lambda function in the */amplify/backend* folder
in VS Code.

This happened to me yesterday with 2 APIs I created and then the day before
yesterday with one API I created. I would really appreciate any help.

Thanks,
Amiteshwar

**Comment by ykethan** [comment]
@amit23234 On a rollback the nested stack may be deleted, could you check this under the Deleted status
Could you set the following in the CloudFormation. 
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/d2632d4c-70e5-4c4e-b260-75ec85ea2def)
and check the stack that contains api in the name(eg: amplify-<app-name>-staging-205217-apiapi02a725ca-W0QTJRWOSUOS)

Additionally, could you provide us information/reproduction steps on how the API was configured to reproduce this behavior?

**Comment by amit23234** [comment]
Yes! I see 2/3 in deleted. Why did they get deleted? I didn't do it.

**Comment by amit23234** [comment]
The APIs were configured in the Amplify CLI in VS Code with the usual steps
of

   1. API name
   2. API Path
   3. Connected Lambda Function

Added information: I was using query parameters for one lambda function and
path parameters for another.

- Amiteshwar

**Comment by ykethan** [comment]
@amit23234 in the deleted CloudFormation stack under the events did you observe any error messages?

Is the error message similar to the following?
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/a0965728-b237-48a9-ad4d-f380d6c846b7)
As i ran into this error when reproducing the behavior using path parameters. if not, could you provide me information/examples of the paths created using the CLI(with query parameters and path parameters)?

**Comment by josefaidt** [comment]
Hey @amit23234 I wanted to follow up here and see if you're still experiencing this?

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
