### ISSUE TITLE
Create cognito user

### ISSUE THREAD

**Issue by marcschroeter** [aws-amplify/amplify-cli#1317]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
auth

** What AWS Services are you utilizing? **
cognito

** Provide additional details e.g. code snippets **
We need to give cognito users within an admin group the possibility to create further cognito users. I understood that is not possible at the moment to create cognito users with amplify.  What alternatives concept do you see to let us create cognito users. Any help is much appreciate.

**Comment by kaustavghosh06** [comment]
@marcschroeter You could use the AWS CLI to do so. Have you tried this alternative?

**Comment by ambientlight** [comment]
@kaustavghosh06: 
I think this should be reopened.

Here is a valid usecase: you want to have a server-side lambda using AWSAppSynchClient that will use `AMAZON_COGNITO_USER_POOLS` authentification model. With sign-in API for server-based authentication (ADMIN_NO_SRP_AUTH) enable in user pool a lambda will go and do [serverside-authentification-flow](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html?icmpid=docs_cognito_console#amazon-cognito-user-pools-server-side-authentication-flow) which needs an actual user pre-existing. 

To have this all working gracefully across amplify environments and CF stack lifetimes maybe auth cloudformation template needs: 
1. https://docs.aws.amazon.com/en_pv/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html
2. CF custom resource with a lambda that would go and use [AdminSetUserPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserPassword.html)

but then this default password or the attribs to generate this default password in lambda will need to be to be passed to function category lambda, not having any knowledge on doing this but maybe this [how-to-create-and-retrieve-secrets-managed-in-aws-secrets-manager-using-aws-cloudformation-template](https://aws.amazon.com/blogs/security/how-to-create-and-retrieve-secrets-managed-in-aws-secrets-manager-using-aws-cloudformation-template/)

anyway for such seemingly simple usecase, this requires some work and maybe it would deserve to be abstracted, and I personally think this might fit with amplifies `auth` category
