### ISSUE TITLE
amplify init --providers $AMPLIFYPROVIDERS: profileName not taken into consideration

### ISSUE THREAD

**Issue by dr-dolittle** [aws-amplify/amplify-cli#13182]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.4.0

### What operating system are you using?

Ubuntu 22.04.3 LTS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I set up the provider config via

```
export AWSCLOUDFORMATIONCONFIG="{\
\"useProfile\":true,\
\"profileName\":\"${AWS_PROFILE_NAME}\"\
}"

export AMPLIFYPROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"
```

When I run `amplify init --providers $AMPLIFYPROVIDERS --yes` it does not consider the profile specified but deploys to default.

Using SSO

### Expected behavior

Deploy to the profile specified

### Reproduction steps

Obvious

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @dr-dolittle I wanted to follow up here and see if you're still experiencing this?

**Comment by dr-dolittle** [comment]
@josefaidt you can close the issue. Thanks
