### ISSUE TITLE
CDK - Adding custom resolver to Opensearch. How to get existing OpenSearch domain endpoint ? 

### ISSUE THREAD

**Issue by majirosstefan** [aws-amplify/amplify-cli#13183]
### Amplify CLI Version

11.0.3

### Question

This skeleton below has been created with "amplify add custom" command. Now I am trying to add custom JS resolver to the Opensearch / Appsync with CDK. 

**How can I reference existing Opensearch cluster ?** (Amplify-generated resource)

My idea was to create reference by using **.fromDomainEndpoint** method, but then I need to create somehow reference to that domain instead of hardcoding it as "hardcoding approach" would not be much maintainable when working with multiple environments.

```

import * as AmplifyHelpers from "@aws-amplify/cli-extensibility-helper";
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import { AmplifyDependentResourcesAttributes } from "../../types/amplify-dependent-resources-ref";

export class cdkStack extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    props?: cdk.StackProps,
    amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps
  ) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, "env", {
      type: "String",
      description: "Current Amplify CLI env name",
    });

    const { envName } = AmplifyHelpers.getProjectInfo();

    const dependencies: AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(
      this,
      amplifyResourceProps.category,
      amplifyResourceProps.resourceName,
      [
        {
          category: "api",
          resourceName: "lake", // <- Adjust with name of your API resource
        },
      ]
    );

    // Get the ID of the existing GraphQL API
    const apiId = cdk.Fn.ref(
      dependencies.api.lake.GraphQLAPIIdOutput // <- Adjust with name of your API resource
    );

    // References the existing API via its ID
    const api = cdk.aws_appsync.GraphqlApi.fromGraphqlApiAttributes(this, "API", {
      graphqlApiId: apiId,
    });


    const opensearch = api.addOpenSearchDataSource(
      "opensearch-datasource",
      cdk.aws_opensearchservice.Domain.fromDomainEndpoint(this, "domainEndpoint", **"?????????"**)
    ); 
    
    
    const openSearchResolver = dynamoDataSource.createResolver("ExecuteOpenSearchMutationResolver", {
      typeName: "Mutation",
      fieldName: "executeOpensearchResolver",
      runtime: new cdk.aws_appsync.FunctionRuntime(
        cdk.aws_appsync.FunctionRuntimeFamily.JS,
        cdk.aws_appsync.FunctionRuntime.JS_1_0_0.version
      ),
      code: cdk.aws_appsync.Code.fromAsset("./resolvers/openSearchRestaurantsByRadiusResolver.ts"),
    }); 
    
     }
 }
```

It looks like the Searchable has their own stack in the Cloudformation and domainEndpoint is one of its outputs (but I need to reference that somehow from CDK / probably a different stack).

**Comment by hackmajoris** [comment]
Don't now if it helps you, but today I created a custom OpenSearch VTL Resolver like this;

```js
 new appsync.CfnResolver(this, 'custom-resolver', {
      // apiId: retVal.api.new.GraphQLAPIIdOutput,
      // https://github.com/aws-amplify/amplify-cli/issues/9391#event-5843293887
      // If you use Amplify you can access the parameter via Ref since it's a CDK parameter passed from the root stack.
      // Previously the ApiId is the variable Name which is wrong , it should be variable value as below
      apiId: cdk.Fn.ref(dependencies.api.passbrains.GraphQLAPIIdOutput),
      fieldName: 'customUserSearchQuery',
      typeName: 'Query', // Query | Mutation | Subscription
      requestMappingTemplate: requestVTL,
      responseMappingTemplate: responseVTL,
      dataSourceName: 'OpenSearchDataSource', // DataSource name
    });
```

The  `fieldName: 'customUserSearchQuery',` is a new query at the GraphQL Schema.

**Comment by majirosstefan** [comment]
**Thank you! Yes, it helps.** 

_Btw, if you would add the `code` the and `runtime` properties in your code and remove `requestMappingTemplate` and `responseMappingTemplate`, you could use JS resolvers too.
CDK has 2 syntax' levels - you are using different one than me (they are called "L1" vs "L2")._

Maybe I am overcomplicating that but I would prefer not to hardcode dataSourceName as 'OpenSearchDataSource' _(Q for Amplify team: Could the datasource name be something else by default than "OpenSearchDataSource"??)_ that's why I wanted to access the domainEndpoint directly from Cloudformation - it turns out I should be able to do that, since it's one of the output parameters in Cloudformation stack and if I am not wrong,  all output params should be accessible with something like

`const domainName = cdk.Fn.importValue("nr-YOUR_GRAPH_QLAPI_NAME-ik4:GetAtt:OpenSearch:DomainEndpoint");
`

[Docs for importValue ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html)

If that would not be possible, I will use your approach.

**Comment by hackmajoris** [comment]
> _Btw, if you would add the `code` the and `runtime` properties in your code and remove `requestMappingTemplate` and `responseMappingTemplate`, you could use JS resolvers too. CDK has 2 syntax' levels - you are using different one than me (they are called "L1" vs "L2")._
> 

Thanks for this. This is way I asked about your package.json - to look which version you use. I just did the upgrade and playing around with JS resolvers. Seems to work. I'll convert the custom VTL resolver code to JS and I'll leave an working example here for others.

**Comment by ykethan** [comment]
@majirosstefan 
noticed the line `cdk.aws_appsync.Code.fromAsset`, assets are currently not supported in the custom resources. but you should be able to pass the resolver as inline as follows.
 
example for js unit resolver using custom resource

Schema

```
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type Todo @model {
  id: ID!
  name: String!
  description: String
}

type Query {
  querySomething(id: String!, name: String): Todo
}

```

Custom resource:

```
const requestJS = `
import { util } from '@aws-appsync/utils'

export function request(ctx) {
  return {
    operation: 'GetItem',
    key: util.dynamodb.toMapValues({ id: ctx.args.id }),
  }
}

export function response(ctx) {
  return ctx.result
}
      `;

// unit resolver
const resolver = new appsync.CfnResolver(this, "custom-resolver", {
  apiId: cdk.Fn.ref(retVal.api.<app-name>.GraphQLAPIIdOutput),
  fieldName: "querySomething",
  typeName: "Query", 
  dataSourceName: "TodoTable", // DataSource name
  runtime: {
      name: "APPSYNC_JS",
      runtimeVersion: "1.0.0",
    },
    code: requestJS,
});
```

**Comment by majirosstefan** [comment]
Thank you all for help!

I will close this issue since I got it working and the original question (_adding custom JS resolver for OpenSearch)_ has been answered.

I also needed to set "aws-cdk-lib" version to be "~2.80.0".

This is probably not a proper place for self promoting, but I have written blog post about setting everything up [here](https://stefan-majiros.com/blog/geo-search-with-aws-amplify-cdk-and-appsync-custom-js-resolvers/)

**Comment by ykethan** [comment]
@majirosstefan congratulations on the blog post and glad to hear the solution worked for your use case.

Additionally, I was hoping to see you would be available for quick chat on a private DM on discord. my handle is `ykethan`.
looking forward to hearing from you.

**Comment by hackmajoris** [comment]
@majirosstefan  just discovered some days ago, then you can't secure a VTL custom resolver, as written in the docs

![image](https://github.com/aws-amplify/amplify-cli/assets/3758212/7f5c1081-4747-4ef5-aa7d-dff27cee1786)

Did you by any change figured out a workaround?

**Comment by hackmajoris** [comment]
> @majirosstefan just discovered some days ago, then you can't secure a VTL custom resolver, as written in the docs
> 
> ![image](https://private-user-images.githubusercontent.com/3758212/269323170-7f5c1081-4747-4ef5-aa7d-dff27cee1786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTc3ODIsIm5iZiI6MTcwOTg5NzQ4MiwicGF0aCI6Ii8zNzU4MjEyLzI2OTMyMzE3MC03ZjVjMTA4MS00NzQ3LTRlZjUtYWE3ZC1kZmYyN2NlZTE3ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTEzMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E0ODc5NTEyMjg0NTI0ODNjOWNlM2JjMjQzMjA4M2JlMDRhYzkyYzMzMTdmMzA0MzI4YmNiODQxMjhmZWI5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VfrOUOgHM9MTg0Y_cRfkiB3vI-sMtzfXcmVaNDuoS50)
> 
> Did you by any chance figured out a workaround?

Late update: there is an work-around
