### ISSUE TITLE
Sort of data items

### ISSUE THREAD

**Issue by marcschroeter** [aws-amplify/amplify-cli#1318]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
api

** What AWS Services are you utilizing? **
dynamodb

** Provide additional details e.g. code snippets **
We want to develop a social media app. How can we show the latest posts first when its not possible to have sort keys at the moment?

**Comment by mikeparisstuff** [comment]
Until we have better support for custom indexes (#1062 will be updated again with new designs), you have a few options:

1. Use custom resources to define your DynamoDB tables with the sort keys of your choosing. This will also require your to configure an IAM role, AppSync data source, and AppSync resolvers manually. You can learn more about the API categories custom resources functionality here https://aws-amplify.github.io/docs/cli/graphql#api-category-project-structure. When building many-to-many relationships which it seems this might be, you can use an adjacency list pattern in DynamoDB https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html.

2. Use @connection and a bit of indirection.

```graphql
type UserFeed @model {
  id: ID!

  # Will configure the GSI such that the edges are partitioned by their "userFeedId" and sorted
  # by the date they were added in the feed.
  edges: [PostEdge] @connection(name: "UserFeedPostEdge", keyField: "userFeedId", sortField: "addedToFeedDate")
}
# When you create a PostEdge, you specify a "addedToFeedDate" that is effectively your posted date.
type PostEdge @model {
  id: ID!
  userFeedId: ID!
  addedToFeedDate: String
  post: Post @connection(name: "PostEdgePost")
  feed: UserFeed @connection(name: "UserFeedPostEdge", keyField: "userFeedId", sortField: "addedToFeedDate")
}
# The post itself might have its own date and can be distributed to people's feeds at a different time.
type Post @model {
  id: ID!
  title: String
  edges: [PostEdge] @connection(name: "PostEdgePost")
}
```

The custom index work aims to simplify these patterns as there are some known issues with defining GSIs based on @connection.

3. If the number of posts in a users feed is small you can consider storing the list of post ids on the **User** object and then configure a **BatchGetItem** resolver on **User.posts** to fetch the posts for the user.

**Comment by yareyaredesuyo** [comment]
How about adding this kind of FAQ things to docs? ( https://aws-amplify.github.io/ )

because, developer maybe not think Amplify (and appsync) sorting is difficult than thinking.


Adding docs to graphql sorting things is very helpful.
