### ISSUE TITLE
'amplify add api' silently crashing when choosing 'default' on Cognito

### ISSUE THREAD

**Issue by brunostuani** [aws-amplify/amplify-cli#1319]
**Describe the bug**
'amplify add api' crashes with no further information nor nothing.

**To Reproduce**
1. Install amplify CLI
2. > amplify init
3. > amplify add api
4. > GraphQL
5. > Provide API name: entities
6. > Amazon Cognito User Pool
7. [[[[ choose any of the first 3 options ]]]]

And now I'm back to my console, just like if amplify has died.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by kaustavghosh06** [comment]
Similar to #1341 and the issue was fixed via updating the node version.
