### ISSUE TITLE
Error when trying to add a new environment from cli

### ISSUE THREAD

**Issue by wangdavidhao** [aws-amplify/amplify-cli#13198]
### How did you install the Amplify CLI?

$ npm install -g @aws-amplify/cli 

### If applicable, what version of Node.js are you using?

20.2.0

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac M1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Hello !

I am trying to add a new env called `prod` on my project using
`amplify env add `<br/>
After submitting the name and the authentication method, I got this error:
`✖ Initializing your environment: prod`\
`✖ There was an error initializing your environment`\
`🛑 Could not initialize platform for 'prod': Missing required key 'Bucket' in params`<br>

But using the command `amplify env list`, the env is created (probably due to a new empty bloc named `prod` inside `team-provider-info.json`) and I am currently using this env: <br/>

`| Environments |`\
`| ------------ |`\
`| staging      |`\
`| *prod        |`

<br/>

Then, when I try to checkout to my staging env with `amplify env checkout staging`, I got this error:
<br/>

`✖ Initializing your environment: staging`\
`✖ There was an error initializing your environment.`\
`🛑 There was an error building the custom resources`\
`No package manager found. Please install npm, yarn, or pnpm to compile overrides for this project.`\

`Resolution: There may be errors in your custom resource file. If so, fix the errors and try again.\
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/`

But I am indeed inside my `staging` env, as stated when using the command `amplify status`:

`Current Environment: staging` <br/>

But now, If I want to push some changes using `amplify push` to `staging`, I get this error:

`No package manager found. Please install npm, yarn, or pnpm to compile overrides for this project.`

Now, I can't create a new environment, and when returning to my previous environment, it also doesn't work anymore.

Is there any possible solution to resolve this ? Thanks !!

### Expected behavior

New env is successfully created

### Reproduction steps

1. `amplify env add`
2. `amplify env checkout newEnv`
3. `amplify push`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @wangdavidhao :wave: thanks for raising this! I was not able to immediately reproduce this using CLI 12.4.0, however I have a few follow-up questions to better understand the context of the issue you are experiencing:

- would you mind posting the project ID output from `amplify diagnose --send-report`?
- are you able to consistently reproduce this? if so, what is the error and stack trace output from running the same command with `--debug`?
- the "npm missing" error is interesting, similar to the previous ask what is the output of `amplify env checkout staging --debug`?

Despite the issue, as a workaround, can you try the following:

1. remove gitignored files with `git clean -fXd` (this will remove the local `prod` env references stored in `amplify/.config/` and remove the affected `amplify-meta.json` file)
2. if the [`prod` CloudFormation stack](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filteringText=prod&filteringStatus=active&viewNested=false) exists, delete it
3. if the `prod` [S3 bucket](https://s3.console.aws.amazon.com/s3/home) remains after deleting the stack, empty and delete
4. pull the `staging` env with `amplify pull --appId <your-app-id> --envName staging` (this will initialize the project locally with the staging env)
5. retry creation of `prod` env with `amplify env add`

**Comment by josefaidt** [comment]
Hey @wangdavidhao  I wanted to follow up here and see if you're still experiencing this?

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.

**Comment by Dmitresky** [comment]
> Hey @wangdavidhao 👋 thanks for raising this! I was not able to immediately reproduce this using CLI 12.4.0, however I have a few follow-up questions to better understand the context of the issue you are experiencing:
> 
> * would you mind posting the project ID output from `amplify diagnose --send-report`?
> * are you able to consistently reproduce this? if so, what is the error and stack trace output from running the same command with `--debug`?
> * the "npm missing" error is interesting, similar to the previous ask what is the output of `amplify env checkout staging --debug`?
> 
> Despite the issue, as a workaround, can you try the following:
> 
> 1. remove gitignored files with `git clean -fXd` (this will remove the local `prod` env references stored in `amplify/.config/` and remove the affected `amplify-meta.json` file)
> 2. if the [`prod` CloudFormation stack](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filteringText=prod&filteringStatus=active&viewNested=false) exists, delete it
> 3. if the `prod` [S3 bucket](https://s3.console.aws.amazon.com/s3/home) remains after deleting the stack, empty and delete
> 4. pull the `staging` env with `amplify pull --appId <your-app-id> --envName staging` (this will initialize the project locally with the staging env)
> 5. retry creation of `prod` env with `amplify env add`

It helps me!
