### ISSUE TITLE
Access query/mutation input via AWS Lambda function

### ISSUE THREAD

**Issue by Shan4993** [aws-amplify/amplify-cli#1320]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

Ref: https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-an-aws-lambda-function 

Step 1 in this section "First create a function by running amplify add function..." When I create a function using amplify add function I have 3 options and I chose the Hello World one. Now when I follow these steps, regardless of the input i pass to this query, my graphql response will always be "Hello World". How can I access the input parameter in the request in my lambda function? 

** Which Category is your question related to? **
Usage

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
n/a

**Comment by ambientlight** [comment]
the arguments passed should be available under `event.arguments` given that used the request resolver template from that tutorial:

```
{
    "version": "2017-02-28",
    "operation": "Invoke",
    "payload": {
        "type": "Query",
        "field": "echo",
        "arguments": $utils.toJson($context.arguments),
        "identity": $utils.toJson($context.identity),
        "source": $utils.toJson($context.source)
    }
}
```

so changing your lambda code at `./amplify/backend/function/YOUR_FUNCTION/src/index.js` from

```js
exports.handler = function (event, context) { //eslint-disable-line
  console.log(`value1 = ${event.key1}`);
  console.log(`value2 = ${event.key2}`);
  console.log(`value3 = ${event.key3}`);
  context.done(null, 'Hello World'); // SUCCESS with message
};
```

to

```
exports.handler = function (event, context) { //eslint-disable-line
  console.log(event);
  context.done(null, event.arguments.msgP1 + event.arguments.msgP2); // SUCCESS with message
};
```

should do.

**Comment by kaustavghosh06** [comment]
@Shan4993 Closing this issue based on @ambientlight response. Please feel freee to respond on this thread or re-open the issue if you're still stuck.
