### ISSUE TITLE
Pull backend for backup and testing regardless of client

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#13205]
### Amplify CLI Version

12.4.0

### Question

Hey guys how can I pull the environment in an agnostic front end way so I can use it for:

- Backup on a github repo
- Add backend tests for CI/CD
- Update backend

Thanks

**Comment by josefaidt** [comment]
Hey @afern247 :wave: thanks for raising this! To better understand the use case is this intended to be completely headless in the sense the project can be pulled, tested, verified, and thrown away in a CI/CD pipeline? What sort of updates are you looking to make on the backend?

Regardless, you can run `amplify pull --appId <your-app-id> --envName <your-env-name> --yes` to automate pulling the project
