### ISSUE TITLE
Error Node when i use amplify push

### ISSUE THREAD

**Issue by JackDurden00** [aws-amplify/amplify-cli#13218]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.15.0

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

i add a new dependencies in a function (amplify add function) who need to have nodejs 16.15 min
i add this with yarn add.

But when i try to run amplify push i have this error:

**Command failed with exit code 1: yarn --no-bin-links --production
warning ../../../package.json: No license field
error phenix-edge-auth@1.2.7: The engine "node" is incompatible with this module. Expected version ">=16.15.0". Got "14.15.4"
error Found incompatible module.
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.**

But in my project i have no nodeJs 14.15.4 and no in my compute too.
I tried some solutions with no result.
I have no idea where is the problem of node.

amplify stock a node somewhere ?

### Expected behavior

Just amplify need to use a correct version of node (node of my project)

### Reproduction steps

yarn add package to a lambda function
amplify push

### Log output

<details>

```

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @JackDurden00 :wave: thanks for raising this! Unfortunately I was not able to reproduce this using yarn 1.x and Node 18/20 with the same npm package. Can you confirm the node version you are using locally?

I was able to reproduce this if I intentionally downgraded locally to use Node 14

```
🛑 Packaging lambda function failed with the error 
Command failed with exit code 1: yarn --no-bin-links --production
error phenix-edge-auth@1.2.7: The engine "node" is incompatible with this module. Expected version ">=16.15.0". Got "14.21.3"
error Found incompatible module.
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by JackDurden00** [comment]
Hey,
i use v16.15.0 installed with npm

**Comment by JackDurden00** [comment]
May be amplify saved on cache a node version.
Because impossible to find a version before node 16 :(

**Comment by JackDurden00** [comment]
sorry i install this node with nvm:

➜  function git:(stgxvii) ✗  nvm list
       v16.14.0
       v16.14.1
->     v16.15.0
         system
default -> 16.14.0 (-> v16.14.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v16.15.0) (default)
stable -> 16.15 (-> v16.15.0) (default)
lts/* -> lts/hydrogen (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.17.1 (-> N/A)

**Comment by josefaidt** [comment]
Hey @JackDurden00 thanks for clarifying! Can you confirm the version of Amplify CLI you are using? And what is the output of `which amplify` and `npm bin -g`?

**Comment by JackDurden00** [comment]
amplify version : 12.0.0
**which amplify** => .volta/bin/amplify
**npm bin -g** .nvm/versions/node/v16.15.0/bin

**volta list :**
Node: v16.20.1 (current @ /Users/aymericvelozzo/Desktop/Mon MacBook/GIT/front/amplify/backend/
    package.json)
    Yarn: v1.22.10 (default)
    Tool binaries available:
        amplify (default)

**Comment by JackDurden00** [comment]
i think the solution is delete amplify and reinstall it.

I use yarn on my project, what is the good practice for install amplify ?
i use curl or npm ?

**Comment by josefaidt** [comment]
Hey @JackDurden00 from the outputs of those commands it appears you have two Node.js version management tools installed and in use -- Volta and nvm. I'm not too acquainted with volta, but perhaps yarn is installed using the volta node version. What is the output of `yarn global bin`?

**Comment by JackDurden00** [comment]
i deleted all nvm node.
now i use just volta.

for yarn global bin : 

warning ../../../package.json: No license field
/usr/local/bin

**Comment by JackDurden00** [comment]
**which amplify**
/Users/aymericvelozzo/.volta/bin/amplify

**Comment by josefaidt** [comment]
Hey @JackDurden00 how was yarn installed? was that installed via npm or some other means like homebrew? Can you try reinstalling amplify using npm on node 16+?

**Comment by JackDurden00** [comment]
I don't remember how I installed Yarn.
I'm thinking of Homebrew.

First I delete amplify?
what is the best way to delete it?

**Comment by josefaidt** [comment]
the following will ensure Amplify CLI is removed

```
amplify uninstall
yarn global remove @aws-amplify/cli
# optionally remove leftover logs, metadata
rm -rf ~/.amplify
```

I would also suggest using [corepack](https://nodejs.org/api/corepack.html) (which comes with later versions of Node.js) to install yarn rather than the homebrew installation. The homebrew yarn installation will use the current node.js runtime installed by volta, but maintain a separate set of global dependencies

You can get started with yarn via corepack with `corepack enable` and `corepack prepare yarn@latest --activate`

**Comment by JackDurden00** [comment]
i uninstall amplify and add amplify directly with yarn (i don't remove yarn).
And now it work !!

May be my file amplify was blocked on a file node14, strange.

Thx for your time and your help :)
