### ISSUE TITLE
amplify init -y adds random strings to the project name 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#13217]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.4.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

If we create a folder say `rn` and run `amplify init -y` the project get created with a random variables added to it at the end of the name

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/d25c1ef9-77bf-435f-88c6-ff937b611b8d)

### Expected behavior

exit or prompt before automatically adding it

### Reproduction steps

1. `mkdir rn && cd rn`
2. ` amplify init -y`
3. open team-provider-info.json or AWS console to see the name.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
confirmed this is a bug
