### ISSUE TITLE
Lambda cannot find shared object file in layer

### ISSUE THREAD

**Issue by cappy123abc** [aws-amplify/amplify-cli#13214]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.20.0

### Amplify CLI Version

10.8.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I am upgrading the lambda and its associated layer to Node 16. I am generating the node_modules and libs for the layer using an Amazon docker image. The layer contains the javascript libraries canvas and fabric. After I amplify push and run the lambda I get an error as shown below. I'm not exactly sure where to put libraries in the layer such that they will be in the correct spot in the lambda. The problem mainly seems to be with canvas.

### Expected behavior

When I run the lambda the libraries will be found.

### Reproduction steps

1. Run build script for node module.
2. Push layer updates to AWS
3. Run lambda

### Log output

<details>

```
# Put your logs below this line
{
    "errorType": "Error",
    "errorMessage": "libX11.so.6: cannot open shared object file: No such file or directory",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: libX11.so.6: cannot open shared object file: No such file or directory",
        "    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)",
        "    at Module.load (node:internal/modules/cjs/loader:1076:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:911:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1100:19)",
        "    at require (node:internal/modules/cjs/helpers:119:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/canvas/lib/bindings.js:3:18)",
        "    at Module._compile (node:internal/modules/cjs/loader:1198:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1076:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:911:12)"
    ]
}


```

</details>

### Additional information

I am using a dockerfile similar to the one here: https://github.com/jwerre/node-canvas-lambda/tree/master

This generates file in a structure that when zipped creates the layer. It looks like the amplify-cli expects a different structure.

The structure of my layer is below:

photoslayer/
├── dist
├── lib
 │   └── nodejs
 │       └── node_modules
└── opt
    └── lib

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @cappy123abc :wave: thanks for raising this! Unfortunately we do not currently support deploying Lambda's or Lambda Layer's built with Docker. How were the dependencies added to the layer in your Amplify project? The error in question appears to be caused by a missing system lib

**Comment by cappy123abc** [comment]
I only used the Docker container (from amazonlinux:2) to generate the node modules and libs and then copied them into the layer folder. I didn't attempt to deploy a custom lambda container.  It looks from the error that the missing library is being searched for at the root of the lambda instead of the opt/ directory? I don't really know why that is.

**Comment by cappy123abc** [comment]
Update: I went into the lambda console and noticed that the layer version was wrong. For some reason the cli did not update the layer version when pushing. I updated it in the console and the lambda is now working.

**Comment by josefaidt** [comment]
Hey @cappy123abc glad to hear you were able to find a solution 🙏 from your local env if changes to the layer does not show it in an UPDATE state from `amplify status`, you can run `amplify env checkout <current-env-name>` which will bump the layer version ahead of `amplify push`

Out of curiosity are you also using Amplify Hosting with automated builds and deployments from git?

**Comment by cappy123abc** [comment]
Yes, we host our web app on amplify as well.

**Comment by josefaidt** [comment]
Are you running `amplify push` sometimes, along with committing to git and allowing Amplify Hosting to rebuild? There's an active issue where these Lambda and Lambda Layer versions get out of sync, which can potentially be the root cause here where the version was behind/wrong

**Comment by cappy123abc** [comment]
Yes, I have used both methods (amplify push and git push) on the same environment.

**Comment by josefaidt** [comment]
Ah it sounds like this is caused by the bug described here https://github.com/aws-amplify/amplify-cli/issues/12916, would you mind giving this a 👍 or adding your thoughts? I'll mark this as a duplicate bug report in the meantime and close in favor of tracking the existing issue, but please note that pushing with the CLI will cause the layer to revert to the code defined in the version deployed with the previous CLI `amplify push` execution rather than what was commited to git and built with Amplify Hosting

**Comment by cappy123abc** [comment]
Ok, will track the issue you have noted above. My lambda failed again after I did a recent merge of a feature and git pushed so I am keen to see what the fix is. Thanks.
