### ISSUE TITLE
EBUSY: resource busy or locked, rmdir 'C:\{local folder}\amplify\.temp\#current-cloud-backend\auth'

### ISSUE THREAD

**Issue by eamonjspain** [aws-amplify/amplify-cli#13233]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.17.1

### Amplify CLI Version

12.4.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

after running amplify pull i get ...
Do you plan on modifying this backend? Yes
× Fetching updates to backend environment: staging from the cloud.
× There was an error initializing your environment.
🛑 EBUSY: resource busy or locked, rmdir 'C:\September2023\AWSAmplify2\teams-and-tasks\amplify\.temp\#current-cloud-backend\auth'
Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

### Expected behavior

no error

### Reproduction steps

1. run amplify pull using id from amplify studio
2. Answer yes to "Do you plan on modifying this backend?"

### Project Identifier

2638153c-fb2c-4fcc-a2ee-34f4706e08fe

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by eamonjspain** [comment]
The issue seems to be resolved now, thank you.

I can't reproduce it now.

is this directory set up for use with OneDrive?
No

is this the first project you've attempted to pull?
No

was this directory empty before pulling?
No

I'm very new to this and have be following the Christian Nwamba YouTube
tutorial.

**Comment by josefaidt** [comment]
Hey @eamonjspain no worries! Glad to hear this hasn't popped back up. I'll close this issue for now, but if this pops back up please let us know by replying to this thread or opening a new bug report!
