### ISSUE TITLE
Mobile App - Switching Amplify Environments From One Build

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-cli#13232]
### Amplify CLI Version

12.2.3

### Question

Hello,
I have a mobile app with typical dev/staging/prod environments. To make builds, I switch my amplify environments before making the build for that environment. Is there anyway that I can pull resources down for all environments, so I can dynamically switch between my dev/staging/prod environments from one build, instead of having a different builds for each environment?
Thanks!

**Comment by josefaidt** [comment]
Hey @mjmostachetti :wave: thanks for raising this! When you mention the environment's build are you referring to `amplify build`/`amplify push` or something else? Environments can be pulled into the project locally with `amplify pull --appId <your-app-id> --envName <your-env-name>`, and can be checked out with `amplify env checkout <your-env-name>`

**Comment by mjmostachetti** [comment]
No. I'm talking about building my app once\ and not having to pull each
different amplify environment and making a separate apk for each. I'm
talking about somehow dynamically switching between them at runtime, if
that makes sense.

**Comment by josefaidt** [comment]
Hey @mjmostachetti thanks for clarifying! You can likely generate the necessary config files like `awsconfiguration.json` and `amplifyconfiguration.json` for each env (by running `amplify env checkout <your-env-name>`) to bundle with your application, however these config files will need to be regenerated if a change is made to your backend resources. Please also note that the GraphQL models will also need to be regenerated, and I'm not certain whether the Android/Swift libraries will work well with multiple instances of its API Client, but I can transfer this issue over for better guidance there

**Comment by mjmostachetti** [comment]
We only use amplify for cognito auth and we don’t plan to ever make changes
to it.

**Comment by josefaidt** [comment]
Hey @mjmostachetti since you're just using auth I'd say this would be pretty straightforward! Please note this setup will get complex if you add more backend resources. For what it's worth I think this is also a great question to ask in our [community Discord server](https://discord.gg/invite/amplify)!

**Comment by josefaidt** [comment]
Hey @mjmostachetti just wanted to follow-up here and see if you're still experiencing this?

**Comment by mjmostachetti** [comment]
Yeah. It wasn't a big deal. I just saved the different aws-exports.js objects for each environment and depending on the environment reconfigured amplify. Thanks.
