### ISSUE TITLE
Amplify Init just returns 🛑 Failed to get profile credentials

### ISSUE THREAD

**Issue by qwikag** [aws-amplify/amplify-cli#13237]
>amplify init

just returns 🛑 Failed to get profile credentials

This needs to be better documented within the tutorial/guide.

**Comment by reesscot** [comment]
Transferring to CLI repo, as this seems to be a CLI issue

**Comment by qwikag** [comment]
Hey @josefaidt ,
The problem is not the CLI Auth, the problem is the document does not advise how to use the CLI Auth Properly.
So yes it is a combination of the 2, yes CLI AUth is overly complex and not straight forward
There are multiple ways to do it to get a success.
But once it fails a person easily goes looking for the many solutions and then ends up mixing up the solutions create a complex mess of attributes,
So primarily this is a documentation issue, that needs its own place in the prerequisites or the like.
For the noob that is a nightmare. On my third time creating a project I still ran into hours of issues.

**Comment by josefaidt** [comment]
Hey @qwikag apologies for the delay here, and sorry to hear of the rough experience. While the CLI continues to improve its auth flow I will be sure to update the relevant documentation. Please note the known bug with AWS IAM Identity Center/SSO, which I believe we chatted about in another issue. I'll close this in favor of tracking the existing item https://github.com/aws-amplify/amplify-cli/issues/4488
