### ISSUE TITLE
Error: Failed to create models in the cloud

### ISSUE THREAD

**Issue by jvasanthan** [aws-amplify/amplify-cli#13249]
### Amplify CLI Version

9.1.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Describe the bug

I received the following error while pushing the API. 

"Failed to create models in the cloud: An error occurred while processing your request: Invalid backend-config.json file. Expected api.generateModels.service = AppSync and api.generateModels.providerPlugin = awscloudformation"

How to resolve this error?

### Expected behavior

No error

### Reproduction steps

Error appeared suddenly

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @jvasanthan, thank you for reaching out. Could you provide us the `backend-config.json` present under the amplify folder. It appears the `backend-config.json` is missing the following attributes in the `api -> <api-name> ` block
```
"providerPlugin": "awscloudformation",
 "service": "AppSync
 ```
 Observed the Amplify CLI is an older version, could you try upgrading the Amplify CLI version by rerunning `amplify upgrade` and retry the push as we have has some improvements in the CLI.

**Comment by jvasanthan** [comment]
@ykethan after updating Amplify CLI to latest, the error disappeared. I will test and let you know more.

**Comment by ykethan** [comment]
@jvasanthan glad to hear that, do let us know if the error reappears.
