### ISSUE TITLE
Overriding multiple stack templates

### ISSUE THREAD

**Issue by neuquen** [aws-amplify/amplify-cli#13257]
### Amplify CLI Version

12.4.0

### Question

I'm currently performing an override using `AmplifyRootStackTemplate` to update the `authRole` (I followed [this example](https://docs.amplify.aws/cli/project/override/#example-modify-authroles-iam-policies)).  I now need to also override the invite message template, which means I need to use `AmplifyAuthCognitoStackTemplate` (according to [this example](https://github.com/aws-amplify/amplify-cli/issues/9668#issuecomment-1027310286)).  However, I have not been able to find documentation on how to override both at the same time.

Will something like the below work?
```
import { AmplifyRootStackTemplate, AmplifyAuthCognitoStackTemplate} from "@aws-amplify/cli-extensibility-helper";

export function override(rootStackResources: AmplifyRootStackTemplate, authCognitoStackResources: AmplifyAuthCognitoStackTemplate) {
  const authRole = rootStackResources.authRole;
  // Rest of authRole code
  ...
  
  // Invite message override code
  const inviteMessageTemplate = {...};
  authCognitoStackResources.userPool.adminCreateUserConfig = {inviteMessageTemplate};
}
```

**Comment by neuquen** [comment]
I think I just found the answer to my own question.  I previously considered the fact that maybe I just needed two different override.ts files, and it looks like that is the case:

Running `amplify override project` is needed to override IAM roles:
> The command creates a new overrides.ts file *under amplify/backend/awscloudformation/* ...
Source: https://docs.amplify.aws/cli/project/override/

Running `amplify override auth` is needed to override the invite message template:
> The command creates a new overrides.ts file *under amplify/backend/auth/< resource-name >/* ...
Source: https://docs.amplify.aws/cli/auth/override/

I previously missed the fact that two separate commands would need to be run, and two different overrides.ts files would be created.

I'm keeping this open until I can confirm or someone from the amplify team confirms.

**Comment by josefaidt** [comment]
Hey @neuquen :wave: yes you will need to override each resource (including the project if necessary)

**Comment by neuquen** [comment]
I also tested this out and it worked great! Closing.
