### ISSUE TITLE
code generation for fragments does not use correct __typename 

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#1325]
**Describe the bug**
The amplify codegen utility does not properly assign the typename for nested fragments during code generation.  Root-level queries and all nested objects all have the properly generated __typename.  Fragments that contain other nested fragments instead have the typename as `string`.  

**To Reproduce**
Clone this repo: https://github.com/mwarger/amplify-codegen-fragment-bug-example

Take a look at the types file and the `blogDetailsFragment` in particular.  The posts object is created with a fragment and the __typename is `string`.

**Expected behavior**
The typename should be `"Post"` in the example above.

**Screenshots**
![image](https://user-images.githubusercontent.com/686823/56476221-44771580-645a-11e9-8860-eb42476daa71.png)

amplify -v
1.5.1

**Comment by mwarger** [comment]
@undefobj @mikeparisstuff Relatedly - have you all looked into use the apollo package for codegen?  I remember seeing that the appsync codegen used to be (probably still is) based on the previous version of apollo codegen.  

I tried running the actual apollo:codegen command against my schema.json file and the results were impressive.  It found the enums and nested queries correctly, as well as properly extracting individual types for list items (as opposed to my current approach of creating fragments for this purpose).  It seems robust, and has a watch mode to boot.  This could perhaps be a good replacement for the current package.  It also didn't have the bug mentioned above.

Would love to hear your thoughts.

**Comment by attilah** [comment]
@mwarger I tried to look into the issue, and I can see the output file, but cannot see how that ```custom-queries.ts``` was generated from the GraphQL definition you've in the repro repo. Could you please reproduce this with the latest version of the CLI and provide more details on how could I repro this issue?

**Comment by mwarger** [comment]
@attilah `custom-queries.ts` was created by me.  I created that myself to hold custom queries separate from the ones generated by the CLI (queries.ts).  

Sorry for the delay in getting back to you.  I will give this a try with the latest CLI.

**Comment by attilah** [comment]
@mwarger did you succeed with the latest version of the CLI?

**Comment by mwarger** [comment]
@attilah No, it's still showing the same behavior.  The `__typename` field is still just `String` when it should be `Post`.

**Comment by mwarger** [comment]
@attilah I provided a repository where you can reproduce it when I opened the issue.  All source files are provided.  Look in src/graphql.

**Comment by attilah** [comment]
Sorry, perhaps I miss something, but I can't see how that type fragment was generated, because I did not see where is it coming from. src/graphql is output of codegen and I can't see ```blogDetailsFragment``` anywhere in the repo, just in generated files.

What CLI commands were you using to generate that piece of core what you've in the screenshot?

**Comment by mwarger** [comment]
@attilah Only the `queries`, `mutations`, and `subscriptions` files are part of the codegen output.  These are regenerated every time.  The codegen looks at the `graphql/*.ts` path for type generation, so anything extra you put in there yourself (like I did with `custom-queries.ts`) is also used with the codegen tool.  The `blogDetailsFragment` is there.
