### ISSUE TITLE
ENOENT: no such file or directory, open 'Z:\.aws\config'

### ISSUE THREAD

**Issue by KingUgochukwu** [aws-amplify/amplify-cli#13268]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

12.4.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

amplify init returns the following error

C:\Users\v.anyanwu\Bridger\Developer\DNRC\dnrc_helper> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project dnrchelper   
The following configuration will be applied:

Project information
| Name: dnrchelper
| Environment: dev
| Default editor: Visual Studio Code        
| App type: flutter
| Configuration file location: ./lib/
? Initialize the project with the above configuration? Yes
? Select the authentication method you want to use: AWS profile
For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
🛑 ENOENT: no such file or directory, open 'Z:\.aws\config'

### Expected behavior

amplify should be initialized in directory

### Reproduction steps

1. Run amplify init

### Project Identifier

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
- Creating Zip
No Amplify backend project files detected within this folder.
× Creating Zip

Session Identifier: 8652a3ab-924b-405f-9335-8dec24dad3ce

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @KingUgochukwu, thank you for reaching out. Could you check if the config file is present inside `.aws` folder? We use the folder to fetch credentials for amplify IAM user to initialize amplify project.
the `.aws` folder on windows should be located on `C:\Users\<userid>\. aws\`.

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
