### ISSUE TITLE
Amplify console is not building my react frontend code correctly ? 

### ISSUE THREAD

**Issue by Private-SO** [aws-amplify/amplify-cli#1326]
**Describe the bug**

I had created a react project and integrated with `Amplify cli` . With `Amplify cli` i had i configured `auth` and `storage` and then i pushed to `codecommit` repo . With `Amplify console` i integrated my `codecommit` and deployed react app. First time when deploying it had triggered `buildspec.yml` which has frontend commands after i had made some little tweaks in the my frontend code and pushed it again. The tweaks were :  i added `react-router-dom@5.0.0` dependency and used it for routing my react-app components. This time amplify console completed the whole process without any error, but when i went into the `react-app` i found my `routes` were not working properly means when i clicked on the `page1` button instead of routing to `/page1` it is appending `/index.html` at the end of ` amplifyconsole url`. Just to test whether my `react-app` is correct or not i used `amplify add hosting` and kept it in `S3` . It had worked perfectly in `S3 http hosting`.  

**To Reproduce**
1. Create a react app locally and commit it to `codecommit` repo.
2. Integrated `codecommit` repo with `Amplify Console`.
3. Then made changes to your react app by enabling `routes` using `react-router-dom` and push it again(All the changes that i had did is in this [githubrepository](https://github.com/Private-SO/reactRoutesapp)

**Expected behavior**
When clicking on the navbar it need to route to me to a different page but it is not.

**Screenshots**
My `Amplify Console` process completed screenshot
![image](https://user-images.githubusercontent.com/26573898/56457254-6eb2cf80-6395-11e9-936d-454efdca6440.png)

React-app Navigation bar when ran locally : When clicked on `page 1` it routes to `page 1 component`.
![image](https://user-images.githubusercontent.com/26573898/56470307-4d6be500-6462-11e9-9112-960df4123774.png)

React-app Navigation bar when ran locally: When clicked on `page 2` it routes to `page 2 component`.

![image](https://user-images.githubusercontent.com/26573898/56470276-231a2780-6462-11e9-9216-4909c9163b1f.png)

**Desktop (please complete the following information):**
 - Windows
 - Browser [e.g. chrome]
 - amplify cli version -- 0.1.36

Let me know if any further information is needed from my side.

Any help is appreciated
Thanks

**Comment by swaminator** [comment]
@Private-SO there's probably an issue with the redirects setup. Checkout: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa
Can you goto App Settings > Redirects and share what you've set up there?

**Comment by Private-SO** [comment]
@swaminator . This is how my `redirects settings` looks like 

![image](https://user-images.githubusercontent.com/26573898/56512818-1b37b180-654e-11e9-9779-2f9dd8b811a6.png)

**Comment by swaminator** [comment]
In the build details page, can you expand the 'Deploy' tab? I'm guessing the pages are not being deployed correctly because the output folder is incorrect.

**Comment by Private-SO** [comment]
This is my `Deploy Tab` logs

```
2019-04-21T07:06:10 [INFO]: Starting Deployment
2019-04-21T07:06:11 [INFO]: Uploading asset-manifest.json
2019-04-21T07:06:11 [INFO]: Skipping upload of existing file favicon.ico
2019-04-21T07:06:11 [INFO]: Uploading index.html
2019-04-21T07:06:11 [INFO]: Skipping upload of existing file manifest.json
2019-04-21T07:06:11 [INFO]: Uploading service-worker.js
2019-04-21T07:06:11 [INFO]: Uploading precache-manifest.1c21b5de8791344d2a1dbf018fe4440c.js
2019-04-21T07:06:11 [INFO]: Uploading static/css/2.467d7a3d.chunk.css
2019-04-21T07:06:11 [INFO]: Uploading static/css/2.467d7a3d.chunk.css.map
2019-04-21T07:06:11 [INFO]: Uploading static/css/main.964f5c2e.chunk.css
2019-04-21T07:06:11 [INFO]: Uploading static/css/main.964f5c2e.chunk.css.map
2019-04-21T07:06:11 [INFO]: Skipping upload of existing file static/js/2.eacfdfcb.chunk.js
2019-04-21T07:06:11 [INFO]: Uploading static/js/2.eacfdfcb.chunk.js.map
2019-04-21T07:06:12 [INFO]: Uploading static/js/main.ffe79e54.chunk.js
2019-04-21T07:06:12 [INFO]: Uploading static/js/main.ffe79e54.chunk.js.map
2019-04-21T07:06:12 [INFO]: Skipping upload of existing file static/js/runtime~main.a8a9905a.js
2019-04-21T07:06:12 [INFO]: Skipping upload of existing file static/js/runtime~main.a8a9905a.js.map
2019-04-21T07:06:12 [INFO]: Skipping upload of existing file static/media/PUCimage.033445c7.jpg
2019-04-21T07:06:12 [INFO]: Updating Edge config
2019-04-21T07:06:12 [INFO]: Deployment finished.
```

This is my `buildspec.yml`

```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

**Comment by ajhool** [comment]
Are you able to go directly to page2 via the browser url input?

**Comment by Private-SO** [comment]
@ajhool  i cant go to the page 2 directly .  

This was my `amplify console` generated url `https://master.xxx.amplifyapp.com` when i clicking on the `page1` or `page2` link on the `navbar` as mentioned in the above screenshots , `amplify console` is routing the page to `/index.html`  (`https://master.xxx.amplifyapp.com/index.html)` which is rendering same contents that are in `https://master.xxx.amplifyapp.com`.  

I typed `/page1` , `/page1/` manually at the end of the url `https://master.xxx.amplifyapp.com/page1` but no use. It is still rendering `index.html` Since it is what mentioned in the `redirects settings` of amplify as present in above screenshot.

**Comment by swaminator** [comment]
@Private-SO we are currently investigating this and will get back to you today.

**Comment by Private-SO** [comment]
@swaminator thanks for giving me the update. Eagerly waiting for the response.

**Comment by anatonie** [comment]
@Private-SO 
Can you please try adding the following rewrite rule to your application:
```
Source address: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>
Target address: /index.html
Type: 200
```

**Comment by Private-SO** [comment]
@anatonie  The above rewrite rule worked perfectly well .  Now it is appending my `route` at the end of amplify `url` like this `https://master.xxxx..amplifyapp.com/page1/`.

What was the reason ? Could you explain the rewrite rule please ?
Do i need to add this rewrite rule whenever they are routes present in my frontend ?

Thanks

**Comment by anatonie** [comment]
This rule rewrites everything without one of the listed extensions to /index.html

Even though your URL is /page1, the content that is being served is still coming from /index.html
Your react-app uses react-router to show different content based on the path.

This means you need Amplify Console to rewrite requests for different pages to /index.html however you don't want to do that for ALL requests, just for pages. So this rule excludes things like stylesheets, images, javascript files, fonts, etc. 

You can read some more about it here: 
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by YaswanthC** [comment]
Thanks @anatonie for the explanation. What about the `console warnings` as mentioned in the above comment. Is there a way to avoid these ? Because by getting these we can't go for prod.

Thanks

**Comment by anatonie** [comment]
Those warnings are most likely because "map" files aren't excluded in the rewrite rule. Adding those to the list should let the map properly load.

**Comment by Private-SO** [comment]
Thanks @anatonie and @swaminator .
