### ISSUE TITLE
IAM profile permissions

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1327]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Documentation around the permissions needed to run the cli

**Comment by kaustavghosh06** [comment]
Closing this issue, since this is a duplicate and we're tracking this in #351.

**Comment by jarrettj** [comment]
Cool. Thanks.

**Comment by brandondurham** [comment]
I’m using Amplify purely for it’s auth features, and even then only to authenticate existing users (sign in, sign out, forgot password, create password). It seems like overkill to grant admin privileges when I’m using such a small portion of the toolset. And as the front-end developer, I don’t have those privileges anyway.

**Comment by undefobj** [comment]
IAM policy can be restricted for just the categories and features that you use as documented here: https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli

Additionally you can use MFA with short term IAM credentials: https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-roles--mfa
