### ISSUE TITLE
Getting Error: Cannot find module 'aws-sdk' in Lambda since switching to node18

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#13278]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

node18 in my Lambda

### Amplify CLI Version

12.5.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I've recently updated all my Lambdas to run on node18 instead of node16 following the manual steps in https://github.com/aws-amplify/amplify-cli/issues/10894

However to get it running again I've manually switched my Lambda back to node16.

### Describe the bug

When running my Lambda in production I get the following error:

Error: Cannot find module 'aws-sdk'

From what I've read (https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/) this is to be expected when switching to node18 as aws-sdk isn't bundled up for node18 as it was for node16.

Trouble is I'm not importing aws-sdk in my Lambda so I'm not sure where this error is coming from?

For now I've manually reverted back to node16 to get the Lambda running.

### Expected behavior

If I'm not importing aws-sdk I'm not sure why its complaining?

Its a Lambda created with Amplify CLI that I'm using in my schema via the @function directive. Its talking to GraphQL via axios but thats about it.

### Reproduction steps

Create a lambda.
Edited the cloudformation templates ala https://github.com/aws-amplify/amplify-cli/issues/10894#issuecomment-1251564540 but for node18
Push up
Run the Lambda

Now this Lambda was created on an older version of the CLI so I'm not sure if this is a fixed thing now or not.

### Project Identifier

This never works for me :(

### Log output

<details>

```
# Put your logs below this line
2023-09-27T13:33:38.717Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}



```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: thanks for raising this! With support for Node 18 in Lambda AWS SDK v2 was removed from the base image in favor of AWS SDK v3. As you have found downgrading to Node 16 will resolve this, however you can also install `aws-sdk` as a Function dependency ahead of migrating to use version 3 of the SDK

**Comment by josefaidt** [comment]
I am also curious about the issue you're experiencing with diagnose :eyes: do you get an error and/or stack trace if you run `amplify diagnose --send-report`?

**Comment by PeteDuncanson** [comment]
Hey @josefaidt my friend. 

I'll try that. So with v2 installed by default does that mean I don't have to import it? Im not importing anything from aws in my functions but maybe there's something global that im using somewhere and that's the issue. That would make sense. I'll check tomorrow. 

For your last comment there's an issue for it. Would love to get it sorted to help with stuff like this so feel free to cast an eye over it https://github.com/aws-amplify/amplify-cli/issues/10980

**Comment by ozbillwang** [comment]
Got the same issue when upgrade to nodejs18.x, since nodejs12.x is deprecated.

it related to the error https://github.com/aws-amplify/amplify-cli/issues/3173, but that ticket has been closed.

Not sure nodejs16.x, will take a try.  But not sure what can be done if nodejs16.x is deprecated later.

**Comment by krnrnee** [comment]
I am having this problem with the AdminQueries created by amplify update auth.  Works fine when I downgrade the runtime to "nodejs16.x" but when I upgrade to the recommended "nodejs20.x" or even "nodejs18.x" it doesn't. Not sure how to fix this since I am not hosing my front end (nextjs) on AWS.

**Comment by PeteDuncanson** [comment]
I'm never ashamed to be that one person that puts their hand up and says they don't know something. If I'm feeling confused others must be to.

Could I has for a hand holding walk through of how this issue should be found and fixed as currently I'm still unsure how to make it go away (other than leaving it running on Node 16).

What commands do we need to run? 
Where do we run them?
What files need editing?
What steps do we need to take to clear this up?

Give me a walk through like I'm an idiot so I can understand more and others coming behind can follow along without having to be the one to put their hand up :)

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: I went through the motions of upgrading an "older" project and captured the following notes:

1. install Amplify CLI 9.2.1 to simulate "older" project, run `amplify init`
2. add a Function with the base "Hello World" template
3. observe Function CloudFormation template is set to use the `nodejs14.x` runtime
4. push with `amplify push -y`
5. upgrade to latest Amplify CLI (12.10.1 at the time of writing)
6. find and replace `nodejs14.x` with `nodejs18.x` 
	<img width="417" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/5033303/8dd4ca17-f566-485b-bebc-a0f0ed362e43">
7. add `aws-sdk` to your Function's `package.json#dependencies` block
	```diff
	{
	  "name": "functionawssdkupgradce3aa97f",
	  "version": "2.0.0",
	  "description": "Lambda function generated by Amplify",
	  "main": "index.js",
	  "license": "Apache-2.0",
	  "dependencies": {
	+   "aws-sdk": "^2.1548.0"
	  },
	  "devDependencies": {
	    "@types/aws-lambda": "^8.10.92"
	  }
	}
	```
8. push with `amplify push -y`
9. 🎉 

This is assuming the Function source code is _not_ being migrated to use AWS SDK v3, which is now baked into the Node.js 18.x runtime for Lambda.

Let me know if this helps!

**Comment by krnrnee** [comment]
I had already migrated the rest of my project to the v3 SDK so what I ended up doing was to copy the Admin Queries source code from a new project that was generated with the Node.js 18x runtime to my older project.  Since I hadn't customized the actual generated Admin Queries code, this worked perfectly.  

This code can be found in the project folders under <your project>/amplify/backend/function/<your admin queries name>/src/

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue

**Comment by gusmd01** [comment]
> Hey @PeteDuncanson 👋 I went through the motions of upgrading an "older" project and captured the following notes:
> 
> 1. install Amplify CLI 9.2.1 to simulate "older" project, run `amplify init`
> 2. add a Function with the base "Hello World" template
> 3. observe Function CloudFormation template is set to use the `nodejs14.x` runtime
> 4. push with `amplify push -y`
> 5. upgrade to latest Amplify CLI (12.10.1 at the time of writing)
> 6. find and replace `nodejs14.x` with `nodejs18.x`
>    <img alt="image" width="417" src="https://private-user-images.githubusercontent.com/5033303/301570956-8dd4ca17-f566-485b-bebc-a0f0ed362e43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjk4MzIsIm5iZiI6MTcwODMyOTUzMiwicGF0aCI6Ii81MDMzMzAzLzMwMTU3MDk1Ni04ZGQ0Y2ExNy1mNTY2LTQ4NWItYmViYy1hMGYwZWQzNjJlNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDc1ODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQ2YzZiMWJjODk2MTkxN2UyYTAxNjAyOTMzOGU3OWQ5MTNiMjhiNTYwOWY4NTkzNDg5M2Y3ODQxZmI4ZGY1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E4JWhsLOW1IIPmyGYOJ4ziDFVJigOCD7hZNoharaVSg">
> 7. add `aws-sdk` to your Function's `package.json#dependencies` block
>    ```diff
>    {
>      "name": "functionawssdkupgradce3aa97f",
>      "version": "2.0.0",
>      "description": "Lambda function generated by Amplify",
>      "main": "index.js",
>      "license": "Apache-2.0",
>      "dependencies": {
>    +   "aws-sdk": "^2.1548.0"
>      },
>      "devDependencies": {
>        "@types/aws-lambda": "^8.10.92"
>      }
>    }
>    ```
> 8. push with `amplify push -y`
> 9. 🎉
> 
> This is assuming the Function source code is _not_ being migrated to use AWS SDK v3, which is now baked into the Node.js 18.x runtime for Lambda.
> 
> Let me know if this helps!

How do you do this update for UserPoolClientLambda?
