### ISSUE TITLE
codgen changes API.swift type names for queries ending in "ta"

### ISSUE THREAD

**Issue by airstance** [aws-amplify/amplify-cli#1328]
Yes, it's really odd.

Create a simple appsync api with the following schema.  The query must return a custom type for this bug to show up.

```
type Query {
	testa: obj
}

type obj {
	value: Int
}
```

Now generate the API.swift code

```
mkdir test
cd test
amplify init
amplify add codegen --api-id XXXXXXXXXXX
amplify codegen

```

The resulting API.swift files will contain

```
public final class Testa
Query: GraphQLQuery {
  public static let operationString =
    "query Testa {\n  testa {\n    __typename\n    value\n  }\n}"

  public struct Data: GraphQLSelectionSet {
    public static let possibleTypes = ["Query"]

    public static let selections: [GraphQLSelection] = [
      GraphQLField("testa", type: .object(Testum.selections)),
    ]

    ...
```

Notice the result object is named `Testtum` instead of `Testa`.  This is really annoying when writing the swift code dealing with the result.  This was found when creating delasync quries by adding "Delta" to the end of the normal query names.

**Comment by yuth** [comment]
Amplify codegen uses [inflected](https://github.com/martinandert/inflected/) to Singularize the name of the selection set and inflected has a [rule](https://github.com/martinandert/inflected/blob/master/src/defaults.js#L27) which converts `ta` -> `tum` and `ia` -> `ium`. 

I will add a black list which will stop changing `delta` -> `deltum`
