### ISSUE TITLE
Error on Amplify push - Error reading ResponseMappingTemplateS3Location from S3

### ISSUE THREAD

**Issue by oe-bayram** [aws-amplify/amplify-cli#13302]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.5.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

After updating the GraphQL schema I'm getting this error message:

```
The following resources failed to deploy:
Resource Name: QuerygetStudentauth0FunctionQuerygetStudentauth0FunctionAppSyncFunction7F78D853 (AWS::AppSync::FunctionConfiguration)
Event Type: update
Reason: Resource handler returned message: "Error occurred during operation 'Error reading RequestMappingTemplateS3Location from S3. Error message: The provided token is malformed or otherwise invalid. (Service: S3, Status Code: 400, Request ID: GV1JPW3532MCQ2TM, Extended Request ID: XxpZugolvm4pPZLWzuSdBjnyaryiQS5SvdY7RVzH1mlhP902zd7d6kYLcZnueH0Y2rjOpzgvRhY=)'." (RequestToken: ..., HandlerErrorCode: GeneralServiceException)
IsCustomResource: false

... some other resources

Resource is not in the state stackUpdateComplete
```

### Expected behavior

The push operation should be completed successfully.

### Reproduction steps

1. Update an existing graphql schema
2. push changes

### Project Identifier

Project Identifier: 5a9e6d4d3a8b6748d9de8830f1bf13fa

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @oe-bayram, thank you for reaching out. Wanted to get some additional information on the project; does the project utilize any temporary credentials or SSO?
How long does the push take to complete?

**Comment by oe-bayram** [comment]
Adding new fields, removing existing ones and even deleting a whole model (with --allow-destructive-graphql-schema-updates) causes the same issue.

**Comment by oe-bayram** [comment]
I'm uncertain of the specific reason, however, removing an **optional** field from a model before initiating a push operation resulted in the successful completion of subsequent push operations.
