### ISSUE TITLE
Saving Deployment State is extremely slow due to unoptimized glob

### ISSUE THREAD

**Issue by ErlendHer** [aws-amplify/amplify-cli#13301]
### Amplify CLI Version

12.5.2

### What operating system are you using?

MacOS Sonoma

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Irrelevant

### Describe the bug

During `amplify push`, the `saving deployment state` step of the push is taking more than 7 minutes to complete. 

After debugging and forking the CLI I've identified the issue and also have an (unfinished) fix that resolves this issue.

The problem is that when uploading the "studio-backend" files there is an unoptimized glob which recursively scans all the files/folders in the "amplify" folder. 

If you have a project with a significant amount of node_modules or other dependencies this adds a massive amount of overhead to the glob.

Adding `node_module` to the ignore pattern of the glob in our case reduced the time from 6 minutes and 46 seconds to 1.2 seconds which one could say is fairly significant.

This 6.5 minutes saved per deploy (and would be worse in the future once we've added more functions and thus more node_modules)

The below code fixes the problem. `packages/amplify-provider-cloudformation/src/utils/upload-current-cloud-backend.ts`
```TypeScript
/**
 * Publish files that Amplify Studio depends on outside the zip file so that can read
 * without streaming from the zip.
 */
const uploadStudioBackendFiles = async (s3: S3, bucketName: string) => {
  const amplifyDirPath = pathManager.getAmplifyDirPath();
  const studioBackendDirName = 'studio-backend';
  // Delete the contents of the studio backend directory first
  await s3.deleteDirectory(bucketName, studioBackendDirName);
  // Create a list of file params to upload to the deployment bucket
  const uploadFileParams = [
    'cli.json',
    'amplify-meta.json',
    'backend-config.json',
    'schema.graphql',
    'transform.conf.json',
    'parameters.json',
  ]
    .flatMap((baseName) => glob.sync(`**/${baseName}`, { cwd: amplifyDirPath, ignore: ['**/node_modules/**'] })) // added the ignore here
    .filter((filePath) => !filePath.startsWith('backend'))
    .map((filePath) => ({
      Body: fs.createReadStream(path.join(amplifyDirPath, filePath)),
      Key: path.join(studioBackendDirName, filePath.replace('#current-cloud-backend', '')),
    }));

  await Promise.all(uploadFileParams.map((params) => s3.uploadFile(params, false)));
};
```

### Expected behavior

I expected saving deployment state not to take more than 7 minutes.

Below are some benchmarks for how long the different actions took in the saving deployment state step:

| Task                                                      | Time                  |
|-----------------------------------------------------------|-----------------------|
| Zipping the #current-cloud-backend                        | 1.886s                |
| Uploading the .zip file                                   | 7.487s                |
| Deleting the old s3 directory for studio-backend          | 898ms                 |
| Performing the glob on the amplify directory              | 6 minutes 41 seconds  |
| Uploading the studio-backend files to s3                  | 558ms                 |

Question of the day: What is the bottleneck?

### Reproduction steps

1. Have a project with JavaScript lambda functions and node_modules
2. Run amplify push
3. Wait in agony after "saving deployment state" begins

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ethan021021** [comment]
+1

**Comment by josefaidt** [comment]
Hey @ErlendHer :wave: thanks for raising this with the detailed report! I've marked this as a feature-request to improve this behavior. Would you be open to filing a PR for this improvement?

**Comment by ErlendHer** [comment]
> Hey @ErlendHer 👋 thanks for raising this with the detailed report! I've marked this as a feature-request to improve this behavior, though would you be open to filing a PR for this improvement with the suggested changes?

I'll see if I can find the time for it. Would this require writing unit test for the suggested feature++?

**Comment by ErlendHer** [comment]
Opened a PR @josefaidt

**Comment by josefaidt** [comment]
Hey @ErlendHer thank you for taking the time to dig into this and file a PR! Let me bump this with the team 🙂

**Comment by ErlendHer** [comment]
It's been another week now, without any further activity @josefaidt
