### ISSUE TITLE
Amplify status Is showing wrong status

### ISSUE THREAD

**Issue by brijeshsoni1300** [aws-amplify/amplify-cli#13304]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

18.18.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

mac sonoma

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

amplify status is giving wired result

![Screenshot 2023-10-04 at 4 07 08 PM](https://github.com/aws-amplify/amplify-cli/assets/51873202/f7273b0b-fae5-4751-8f6b-2f4682e7a614)

### Describe the bug

it is showing that lambda is updated or deleted but at the same time amplify status -v is telling  no changes are there

### Expected behavior

it should show now changes as there are no changes between local and pushed version

### Reproduction steps

Not able to figure out, randomly its happning

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @brijeshsoni1300, thank you for reaching out. Could you run `amplify diagnose --send-report` and provide us the `Project Identifier` output. This would enable us in diving deeper into the issue.

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
