### ISSUE TITLE
Amplify uninstall uninstalls package even when answered No.

### ISSUE THREAD

**Issue by krosiek** [aws-amplify/amplify-cli#13314]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.7.0

### Amplify CLI Version

12.6.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

```
$:amplify uninstall                                                                                                                                
? Are you sure you want to uninstall the Amplify CLI? No
Not removing the Amplify CLI.


removed 26 packages in 175ms
$:amplify uninstall                                                                                                                              
zsh: command not found: amplify
```

### Expected behavior

When I answer No to the question `Are you sure you want to uninstall the Amplify CLI?` I expect the package not to be uninstalled.

### Reproduction steps

npm install -g @aws-amplify/cli@12.6.0
amplify uninstall
No

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @krosiek, thank you for reaching out. I was able to reproduce the issue, marking as bug. 

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/ac26ee96-5b2a-4946-b9c7-b9c5656ee4d8)

**Comment by ykethan** [comment]
Note: tested in CLI versions 12.0.1, 11.0.1 and 10.0.0, observed similar behavior.

**Comment by josefaidt** [comment]
Closing as a wontfix in favor of prioritizing Amplify (Gen 2) CLI interactions. While it is an undesirable/unexpected behavior, this functionality does not impact production workloads. 

Note when using npm to manage the Gen 1 CLI package `@aws-amplify/cli`, removing with `npm uninstall -g @aws-amplify/cli` will also invoke `amplify uninstall` and remove the local assets.
