### ISSUE TITLE
In nextjs 13, While pulling existing amplify backend, graphql folder is not added in src folder.

### ISSUE THREAD

**Issue by RZ-Jyothsna** [aws-amplify/amplify-cli#13315]
### Amplify CLI Version

12.6.0

### Question

In nextjs 13, While pulling existing amplify backend, graphql folder is not added in src folder. How to resolve this.

**Comment by ykethan** [comment]
Hey @RZ-Jyothsna, thank you for reaching out. We can generate the graphql folder by running `amplify configure codegen` and run the through the flow. If the project already has the `.graphqlconfig.yml` present, we can run `amplify codegen` to generate the folder.

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
