### ISSUE TITLE
Allow reconfigure EventSourceMapping after running `amplify add function`

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#13322]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

When using Amplify to create a Lambda function with event triggers, it's possible to specify the associated DynamoDB tables during the initial setup. However, there might be scenarios where you need to reconfigure or update the event source mappings to associate the Lambda trigger with different tables. This issue explores how to achieve this reconfiguration.

### Describe the solution you'd like

Users should be able to reconfigure the event source mapping for a Lambda function created through Amplify, allowing them to associate the function with different DynamoDB tables. The process for updating the event source mappings after the initial amplify add function command should be documented clearly.

### Describe alternatives you've considered

x

### Additional context

Where is what the doc says, but you can't "reconfigure" this after the initial setup.
<img width="752" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/13927101/783895e6-f959-420a-ba20-40f7068c69a7">

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @yaquawa, thank you for reaching out. The feature is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/4038. Please feel free in adding a thumbs up on the issue. 

Closing the issue as duplicate.
