### ISSUE TITLE
When I try to push graphql I get the error subscriptions.onCreate.forEach is not a function.

### ISSUE THREAD

**Issue by taro-nagano** [aws-amplify/amplify-cli#13330]
First, we created Grapfql using the command `amplify add api`.

Then I edited `schema.graphql` as follows.

Finally, we did an `amplify push`.

the following error occurred.

```
type Message
  @model (
    mutations: {create: "createMessage"}
    subscriptions:  {onCreate: "onCreateMessage"}
  )
  @auth(rules: [
    {allow: owner, operations:[read, create, delete]}
    {allow: private,  operations:[read]}
  ])
{
  id: ID!
  content: String!
}
```

 It would be helpful if you could let me know if you know the solution.

**Comment by josefaidt** [comment]
Hey @taro-nagano :wave: would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-category-api/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml)? This will help us gather additional context around the issue you are experiencing to effectively troubleshoot. Thanks!
