### ISSUE TITLE
Allow client secret in User Pool

### ISSUE THREAD

**Issue by AWS-crafter** [aws-amplify/amplify-cli#13334]
Allow client secret in User Pool: https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#scoped-configuration

### Describe the solution you'd like

Client secret works in User Pool

**Comment by ykethan** [comment]
Hey @AWS-crafter, thank you for reaching out. To better assist you are you looking to use the Amplify CLI to enable client secrets for the auth resource or looking to set the client secrets in `Amplify.configure()`?
If you would like to enable client secrets for the native and web clients we can utilize Amplify override for auth resource by running `amplify override auth` and utilize the following example:

```ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPoolClient.generateSecret = true
  resources.userPoolClientWeb.generateSecret = true
}
```

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
