### ISSUE TITLE
Unnecessary files with `amplify pull`

### ISSUE THREAD

**Issue by uzaymacar** [aws-amplify/amplify-cli#13335]
### Amplify CLI Version

12.7.0

### Question

Everytime I run `amplify pull` on my `dev` environment, I get quite a bit of unnecessary / duplicated files as shown in the screenshot attached to this ticket. How can I remove these from my environment?

![Screen Shot 2023-10-16 at 7 31 42 PM](https://github.com/aws-amplify/amplify-cli/assets/33473983/fcf2ec61-d2a0-42bf-af4e-d7c438191cd6)

**Comment by uzaymacar** [comment]
Yes @josefaidt, that is the problem indeed, cloud storage sync with iCloud. I'm closing the issue, thanks for the help.

**Comment by wongmrdev** [comment]
Where to download that zip and reupload?
