### ISSUE TITLE
Console CI/CD backend deployment fails for Python Lambda (Unable to import module)

### ISSUE THREAD

**Issue by dcfranca** [aws-amplify/amplify-cli#13349]
** Please describe which feature you have a question about? **
Ok, not exactly a cat dying, but I didn't know how to summarize it on the headline, so I decided to go with a clickbait.
To be honest, I don't know if this question fit best here or on `amplify-cli`, feel free to move it if needed.

I have the following scenario:
2 branches, each branch is linked to an Amplify environment
Branch: `dev` -> Amplify env: `dev`
Branch: `master` -> Amplify env: `staging`

They are connected via Amplify Console, so every time something is pushed to them, they deploy the environment, backend and frontend.

I have a lambda function, created via Amplify, which uses is a Python function, and uses `docxtpl` package, which uses `MarkupSafe`

I have a Pipfile with the following:
```
[packages]
docxtpl = "*"
```

Whenever I push the backend via amplify-cli it works fine, and my function works as expected.
However, every time I deploy it via amplify console (which means every time I update the branches), my function breaks, and I start getting the following errors on my logs:
>Unable to import module 'index': No module named 'markupsafe' 

What I sometimes do is adding this line to my Pipfile:
```
MarkupSafe = "*"
```
and pushing locally the backend again

But, tbh, I don't think this is the solution, it is just because it recognizes something has changed in the function and then re-deploy, because when I remove the MarkupSafe works as well

It is happening every time I happen to deploy, it is really annoying having to do it every time
Any clue what I can do to fix once for all? Or at least where to look for better debugging information?

Thanks

** Provide additional details**

**Comment by josefaidt** [comment]
Hey @dcfranca and @stemwinder apologies for the delay here, but I wanted to confirm whether y'all were still experiencing this issue?

**Comment by dcfranca** [comment]
> Hey @dcfranca and @stemwinder apologies for the delay here, but I wanted to confirm whether y'all were still experiencing this issue?

I haven't used Amplify for years now, so I don't know if this is still happening

**Comment by josefaidt** [comment]
Sorry about that @dcfranca I know it's been a few years on this one :/ I'll close this out for now as we have not received recent reports around this behavior, but will keep it in mind the event we do receive a report
