### ISSUE TITLE
How to run Admin like GraphQl mutations for users in Lambda?

### ISSUE THREAD

**Issue by szymondobrzanski** [aws-amplify/amplify-cli#13347]
### Amplify CLI Version

12.5.2

### Question

Hello,
Is there a possibility to run admin like GraphQl mutations for multiple users inside Lambda function?
My case is that I have app with Cognito user pool and each of users has it's own data stored in DynamoDb e.g.
```
type TodoDb @model @auth(rules: [{allow: owner, operations: [create, read, update]}]) {
  id: ID!
  param: Boolean!
}
```

I would like to have recurring Lambda function that each day makes a change in user record in _TodoDb_ table. I can't use DynamoDb SDK because updates in database won't be reflected in my app's frontend (DataStore is subscribing to AppSync, not to DB itself). How can I achieve that in Lambda using GraphQl client?

**Comment by rudyhadoux** [comment]
Do you know that ?
`@auth(rules: [{ allow: owner, ownerField: "members" }])`

**Comment by szymondobrzanski** [comment]
I figured it out, in case someone stumbles on similar issue I leave information how to deal with such case:
1.  Add rule for each model you'll want to run mutations/queries on for Admin group
```
type TodoDb @model @auth(rules: [{allow: owner, operations: [create, read, update]},
 { allow: groups, groups: ["Admin"]}]) {
  id: ID!
  param: Boolean!
}
```

2. In your User Pool create group called _Admin_ and add IAM role that has _AdministratorAccess-Amplify_ policy
3. Create user in User Pool e.g. admin@admin and add it to _Admin_ group
4. In your User Pool go to App Integrations -> scroll to the App client list -> click on client name -> edit App client information -> in Authentication flows add ALLOW_ADMIN_USER_PASSWORD_AUTH -> Save
5. Create Lambda in Amplify CLI with access to API and Auth categories
6. Add @aws-sdk/client-cognito-identity-provider to your newly created Lambda
7. Use following code to authenticate Admin user inside Lambda in order to get token needed for GraphQl client
```
const { CognitoIdentityProviderClient, AdminInitiateAuthCommand } = require("@aws-sdk/client-cognito-identity-provider");
const GraphQLClient = require("/opt/graphQLClient.js");

const cognitoClient = new CognitoIdentityProviderClient();


exports.handler = async (event) => {
    try {
        const adminUserInput = {
            UserPoolId: USERPOOLID,
            ClientId: CLIENT_ID,
            AuthFlow: "ADMIN_USER_PASSWORD_AUTH",
            AuthParameters: {
                "USERNAME": ADMIN_USERNAME,
                "PASSWORD": ADMIN_PASSWORD
            },
        };
        const adminUserCommand = new AdminInitiateAuthCommand(adminUserInput);
        const adminUserResponse = await cognitoClient.send(adminUserCommand);

        const token = adminUserResponse.AuthenticationResult.AccessToken;
        const gqlClient = new GraphQLClient(token);
       .
       .
       .
    } catch (error) {
        console.log('error: ', error)
        return error;
    }
};
```

8. Enjoy running mutations and queries for all users
