### ISSUE TITLE
Can we have a same login email for 2 diff userType?

### ISSUE THREAD

**Issue by yashBrahma** [aws-amplify/amplify-cli#13346]
### Amplify CLI Version

12.0.3

### Question

We have 2 diff userType "producer" and "consumer". Where if user signs up with the email "[prod@email.com ](https://support.console.aws.amazon.com/support/prod@email.com)" as producer we assign custom:userType attribute as "producer".

Now same user wants to sign up as a consumer with the same email "[prod@email.com ](https://support.console.aws.amazon.com/support/prod@email.com)" but the user already exists in the Cognito pool with userType as "producer". 

So is there any solution for this? Where user can use the same email for both userType.

Configuration -
  Cognito user pool sign-in options -
    User name
    Email
    Phone number

**Comment by ykethan** [comment]
Hey @yashBrahma, thank you for reaching out. we can utilize email alias, 
for example, `prod+producer@email.com` and `prod+consumer@email.com`. Cognito will treat these as separate emails on user signup.

Additionally, we can utilize username as signup mechanism, where for example we can create different usernames that are tied to the same email address and can add multiple emails as well.
`producer123` with email `prod@email.com` as "producer"
`consumer123` with email `prod@email.com` as "consumer"

**Comment by ykethan** [comment]
Closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
