### ISSUE TITLE
Amplify push keeps showing updates needed even successful Deploy on Data Amplify Studio

### ISSUE THREAD

**Issue by harrynguyen2510** [aws-amplify/amplify-cli#13340]
### Description

As usual when running command `Amplify push`, it fetches the changes between local and Amplify on cloud to show which changes needed to be updated, then we open **Data on Amplify Studio**, start to `Deploy`

In my cash, after Deploy successfully, I ran` Amplify push` again, it still shows Datastore API needed be updated, then I push again ->  deploy -> check again `Amplify push` locally, and it keeps shows "Datastore API needed be updated"
I did this process multiple time and still update needed

Note that I open new Studio page to make sure load new everytime when command run Amplify push locally done 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [x] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots
![Screenshot 2023-10-17 at 15 44 24](https://github.com/aws-amplify/amplify-flutter/assets/59348244/89e23f8f-fc67-4a23-b0b8-fb3486e99376)

_No response_

### Platforms

- [x] iOS
- [x] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.13.7

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by josefaidt** [comment]
Hey @harrynguyen2510 :wave: thanks for raising this! After deploying with Amplify Studio you can run `amplify pull` to sync the latest changes. If you run this command after deploying with Studio does it still show as UPDATE on every push?

**Comment by harrynguyen2510** [comment]
Thanks for reply, after Deploying with Amplify Studio, I ran locally Amplify push, it will automatically pull to sync the latest changes from Studio, and still shows as UPDATE on every push. This is the issue

**Comment by ykethan** [comment]
Closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
