### ISSUE TITLE
How to rebuild my app when pushing to cloudfront ?

### ISSUE THREAD

**Issue by Private-SO** [aws-amplify/amplify-cli#1334]
** Which Category is your question related to? **
This question is related to amplify_cli . In this i am using amplify add hosting feature and deploying my app in cloudfront. Now, i had made some changes to my app locally and want to push this new build to cloudfront. I tried this command `amplify configure hosting` but i didnt build my app since there is no change in the fields that it had asked me. The only change is in the `frontend side` . I know there is `amplify_console` service is there for it but just want to confirm is there any availability in cli. 

As a wokraround i am deleting my present cloudfront and adding  a new one which takes the new build but it is taking so time.  

Why i am asking this question is that when i am building my app using `amplify console` it is not building correctly. [checkout this issue](https://github.com/aws-amplify/amplify-cli/issues/1326)

** What AWS Services are you utilizing? **

AMPLIFY_CLI - 0.1.36

** Provide additional details e.g. code snippets **

```
D:\TECH\Codecommit\TodayReactApp>amplify configure hosting
? Specify the section to configure CloudFront
? Remove CloudFront from hosting No
? default object to return from origin index.html
? Default TTL for the default cache behavior 86400
? Max TTL for the default cache behavior 31536000
? Min TTL for the default cache behavior 60
? Configure Custom Error Responses No
? Specify the section to configure Publish
You can configure the publish command to ignore certain directories or files.
Use glob patterns as in the .gitignore file.
? Please select the configuration action on the publish ignore. (Use arrow keys)
? Please select the configuration action on the publish ignore. I'm done.
? Specify the section to configure I'm done.

D:\TECH\Codecommit\TodayReactApp>amplify push
| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Auth     | cognitoa545af85 | No Change | awscloudformation |
| Storage  | s3a254a175      | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
| Api      | todayreactapp   | No Change | awscloudformation |
? Are you sure you want to continue? No
```

**Comment by mtliendo** [comment]
Have you tried `amplify publish`? This command publishes both your client and backend resources.
https://github.com/aws-amplify/amplify-cli#commands-summary

**Comment by yuth** [comment]
`amplify publish` checks if there are any pending changes and if there are changes that needs to be pushed, it asks you if you want to do an `push` before publishing.

**Comment by Private-SO** [comment]
thanks @mtilendo and @yuth . Indeed `amplify publish` solved my problem.
I tried it many times since it is saying `Nochange`  i would go with `No` this time i tried `yes`. Then it automatically rebuild my frontend .

Thanks

```
D:\TECH\Codecommit\TodayReactApp>amplify publish
| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Auth     | cognitoa545af85 | No Change | awscloudformation |
| Storage  | s3a254a175      | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
| Api      | todayreactapp   | No Change | awscloudformation |
? Are you sure you want to continue? Yes
```

**Comment by mtliendo** [comment]
That's actually good insight.  Perhaps a PR should be raised to explicitly state that even though the backend won't change, any changes to the frontend will.
