### ISSUE TITLE
CLI created function assumes incorrect runtime when mocking

### ISSUE THREAD

**Issue by d-huck** [aws-amplify/amplify-cli#13352]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.8.0

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

IAM roles for functions in the cloud for interacting with other AWS resources such as SNS topic publication.

### Describe the bug

After creating a python lambda, amplify-cli attempts to run it using `nodejs` backend when mocking. The created function has the correct python skeleton and deploys as a python3.8 backend. 

### Expected behavior

`amplify mock function` should use the `python3.8` runtime and properly mock the function.

### Reproduction steps

1. `amplify create function`
2. Select python run time options
3. Do not update any special permissions
4. `amplify mock function <function_name>`

### Project Identifier

Project Identifier: 5ed20e93d1463f6c86d9ee36980bc7ef

### Log output

<details>

```
# Put your logs below this line

2023-10-20T00:11:16.509Z|info : amplify function mock snsGenerate 
2023-10-20T00:11:16.591Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-10-20T00:11:19.717Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["vibe"])
2023-10-20T00:11:19.721Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2023-10-20T00:11:19.722Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["vibe"])
```

</details>

### Additional information

When running `amplify update function`, the output banner has the following information:

```
➜ amplify update function          
? Select the Lambda function you want to update snsGenerate
General information
- Name: snsGenerate
- Runtime: nodejs
```

Once again, the function deploys and runs fine when deployed in the correct runtime. The relevant section of the cloudFormation json contains the correct runtime designation:

```
"Properties": {
        ...
        "Runtime": "python3.8",
        "Layers": [],
        "Timeout": 25
        ...
}
```

I attempted a forced `amplify pull` hoping that would correct the configuration to no avail. 

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @d-huck, thank you for reaching out. I was able to reproduce the issue by manually modifying the `amplify.state` file present in your `function/<function-name>`

for example modified the runtime in the state file

```
{
  "pluginId": "amplify-python-function-runtime-provider",
  "functionRuntime": "nodejs",
  "useLegacyBuild": false,
  "defaultEditorFile": "src/index.py"
}
```

output
<img width="329" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/87995712/51871ee7-7a1c-4b99-a075-96556dfe24bc">

could you let us know if the state file was modified or if are you utilizing any scripts such as hooks during the build phase.

**Comment by d-huck** [comment]
Hi @ykethan, I haven't set up any scripts for the build phase. Updating the `amplify.state` file fixed the issue and I'm able to mock locally again.

Looking at the git history, the file was never edited, but I believe the file was deleted in a git update. I recall seeing it pop up while staging changes and "rolling back" changes on the file, which would have deleted it before being committed after function creation. In this case, is the defined behavior of `amplify-cli` to simple recreate the file with default settings?

Either way, chalk it up to user error and thank you for your help :)

**Comment by ykethan** [comment]
Hey @d-huck, thank you for the information. I was able to reproduce the behaviour.
1. create a function `amplify add function` -> `python` as runtime
2. delete the state file
3. amplify push
observed the state file being recreated with runtime as `nodejs`

**Comment by ykethan** [comment]
On discussing with the Amplify team, the behaviour occurs as expected.
Closing the issue.
