### ISSUE TITLE
Aws amplify Appsync update schema

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1336]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AWS Amplify appsync

** What AWS Services are you utilizing? **
Appsync dynamodb
** Provide additional details e.g. code snippets **
Hi all, i first created schema as 
```
type User @model{
      id: ID!
      userId: ID!
}
```
later when i change userId: String! I am getting following error in cloud formation.
```CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename and update the stack again```

**Comment by mikeparisstuff** [comment]
This does look like an issue with your @model declaration. Do you have any stacks in your `stacks/` directory and if so did you change them at all?

**Comment by achutkiran** [comment]
Nope

**Comment by kaustavghosh06** [comment]
@achutkiran We weren't able to reproduce this issue. Could you please try adding a new API and do the same changes and see if the push succeeds? Also, what's the CLI version that you're using? Are you deploying it to the Amplify Console?

**Comment by achutkiran** [comment]
amplify version is 1.6.3. I'll try to create new api and update you

**Comment by kaustavghosh06** [comment]
@achutkiran Were you able to reproduce this?

**Comment by achutkiran** [comment]
Hi, I tried by adding new api and I am unable to reproduce this issue
