### ISSUE TITLE
Amplify Project Pull without GUI/User Interaction

### ISSUE THREAD

**Issue by NareshChinnusamy** [aws-amplify/amplify-cli#13371]
### How did you install the Amplify CLI?

CURL

### If applicable, what version of Node.js are you using?

node 16

### Amplify CLI Version

11.1.1

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I tried to pull the amplify project in my own CICD pipeline using the following command 
```bash
amplify pull --appId <app-id> --envName staging --yes
```
It prompts to browser to sign in with the AWS account.

But in the CICD pipeline, there is no GUI. How should I resolve this?

### Expected behavior

I want to perform **amplify pull --appId <app-id> --envName staging --yes** command in CICD pipeline without any user interactions

### Reproduction steps

1. Navigate to a particular react client project
2. Run amplify pull --appId <app-id> --envName staging --yes command
3. It prompts to browser

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @NareshChinnusamy, thank you for reaching. It appears the application has Amplify Studio enabled and is prompting to authenticate on the browser. 

To mitigate the issue we utilize the following options.

1. If the application does not utilize Amplify Studio 
Disable Amplify Studio on the AWS Amplify console. on selecting the Amplify App, on the left panel select `Amplify Studio settings ` and disable studio.  On re-running the pull command, this should automatically switch to using profiles.

2. Using headless command and pass in additional attributes:
We can utilize a script to run Amplify CLI headless command that will use the profile or keys. Refer to the example [here](https://github.com/aws-amplify/amplify-cli/issues/13362#issuecomment-1776039527)

**Comment by NareshChinnusamy** [comment]
Thanks for the Info. I got it to work with Headless Mode.
