### ISSUE TITLE
problem when pushing lambda with external library.

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#1337]
** Which Category is your question related to? **
Lambda function

** What AWS Services are you utilizing? **
lambda SES

** Provide additional details e.g. code snippets **
I want to send an email from a lambda function.
I have created a function with the CLI, and then I initialized with npm, to import a library to use in that function.
When pushing the function only the src folder is uploaded. 

I think I must edit the <function>cloud-formation-template.json so other resources can be attached and the SES policies also define for the role.

```
"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
                              "aws:asset:path": "./src",                
				"aws:asset:property": "Code"
			},

```
I need some guidance regarding how to edit correctly this function stack.
For the email function Im following this example
https://medium.com/@xoor/sending-emails-with-attachments-with-aws-lambda-and-node-js-e6a78500227c

Thanks!

**Comment by yuth** [comment]
@sergiorodriguez82 
> When pushing the function only the src folder is uploaded.

Amplify CLI runs `npm install` command on the `src` directory of the Lambda function. So if you have a `package.json` and add dependencies those will be uploaded along with your Lambda function code

> I think I must edit the cloud-formation-template.json so other resources can be attached and the SES policies also define for the role.

Yes you will have to edit the cloud-formation-template.json to support SES. We ***recommend to fine grain the access rule instead of  `FullAccess`*** to all the services used. If you were to give full permission to the resources listed in the blog post, your execution policy might look like this
```json
{
  "lambdaexecutionpolicy": {
    "DependsOn": ["LambdaExecutionRole"],
    "Type": "AWS::IAM::Policy",
    "Properties": {
      "PolicyName": "lambda-execution-policy",
      "Roles": [{ "Ref": "LambdaExecutionRole" }],
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents",
              "s3:*",
              "ses:*",
              "cloudwatch:*"
            ],
            "Resource": {
              "Fn::Sub": [
                "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
                {
                  "region": { "Ref": "AWS::Region" },
                  "account": { "Ref": "AWS::AccountId" },
                  "lambda": { "Ref": "LambdaFunction" }
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

**Comment by joebri** [comment]
@yuth 
```Amplify CLI runs npm install command on the src directory```
Maybe this is obvious to folks but I, for one, had completely missed this possibility (and don't recall seeing it in any documentation). Just this one line is going to save me all sorts of headaches! Thank you!
