### ISSUE TITLE
api/build//build/cloudformation-template.json and schema.graphql not created

### ISSUE THREAD

**Issue by dan-hook** [aws-amplify/amplify-cli#13385]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.9.0

### Amplify CLI Version

12.7.1, but also tried 11.1.1

### What operating system are you using?

Ubuntu on WSL2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes, but many custom resources in the application

### Describe the bug

In a fresh checkout of my project, I run 
amplify init --appId d1g66d3b03y7li
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: qa
Using default provider  awscloudformation
✔ Initialized provider successfully.
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✅ Initialized your environment successfully.

Then I run amplify push, which operates normally, but it gets to:
✔ Are you sure you want to continue? (Y/n) · yes
Installing dependencies from Pipfile.lock (ca2f74)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
**Could not read cloudformation template at path: /workspaces/gene-panel-api/project/amplify/backend/api/genepanelapi/build/cloudformation-template.json**

Additionally, api/project/amplify/backend/api/genepanelapi/build/schema.graphql is also not created, which means codegen won't work.  

**WORKAROUND**
If I edit my schema.graphql to add an extra line, everything works as expected.  
I could also probably copy the files from current-cloud-backend.  

### Expected behavior

If the api/build directory is missing, it should be rebuilt completely, including schema.graphql and cloudformation-template.json.  

This originally came up because I'm deploying this app in Github Actions.  I checkout the code, push it, then use the generated typescript queries and mutations to run tests on the deployed API.  There's value in running the tests even if schema.graphql hasn't changed because some of the Lambda functions that back the resolvers may have changed.  

### Reproduction steps

Create an amplify app with a graphql API.  Deploy it.  Commit to git (using the default [.gitignore](https://docs.amplify.aws/cli/reference/files/#gitignore) ) that leaves out the build directory.  Check it out into a fresh directory, and run amplify init and amplify push as described in the bug.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @dan-hook, thank you for reaching out. Could you run `amplify diagnose --send-report` and provide us the `Project Identifier` output on the terminal. 
Additionally, could you add the `--debug` to the init command and provide us the output.

**Comment by dan-hook** [comment]
Project Identifier: 04f83178cd073fa44470b41eeda4bb12

Running init with --debug prints out:
⠧ Initializing your environment: qaOverrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category
Overrides functionality is not implemented for this category

I ran amplify push -y --debug and got an additional line:
Deployment state saved successfully.

GraphQL transformer version: 2

**Not pulling components because this project is not Amplify Studio enabled.**

**Comment by ykethan** [comment]
Hey @dan-hook, Do you also observe the error message `Could not read cloudformation template at path: /workspaces/gene-panel-api/project/amplify/backend/api/genepanelapi/build/cloudformation-template.json`
when pulling the backend env in a fresh directory `amplify pull --appId <app-id> --envName qa`?

**Comment by ykethan** [comment]
@dan-hook, as a quick check, could you remove the `build` folder from the `backend/api/genepanelapi/`, then run `amplify build`. Could you then try doing a push with a empty change.

**Comment by dan-hook** [comment]
`amplify build` appeared to do nothing.  The empty push behaved the same as in the bug description, Displaying
`Could not read cloudformation template at path: /workspaces/gene-panel-api/project/amplify/backend/api/genepanelapi/build/cloudformation-template.json` and not building schema.graphql.

**Comment by dan-hook** [comment]
@ykethan Thanks for the effort you've put in.  I don't think we're going to resolve this, so I'll close this issue and work around it.

**Comment by ykethan** [comment]
@dan-hook would you be open for a call? want to make sure i document this behavior. 
I am available on discord, my handle is `ykethan`
