### ISSUE TITLE
Flutter GraphQL Issue

### ISSUE THREAD

**Issue by Tructivity** [aws-amplify/amplify-cli#13388]
### Amplify CLI Version

2.0

### Question

I am trying to add the AWS AppSync API plugin into the Flutter app to support GraphQL from the amplify backend that already exists. It sends an error message that the configuration failed and no API plugin was found when I ran my Flutter app.

Is the configuration in the image correct or is there any other way to add multiple plugins to amplify configuration.dart?
![image (3)](https://github.com/aws-amplify/amplify-cli/assets/30433012/f3e02390-3b4a-4e3d-bf6c-e7b5fa13ad3c)

**Comment by Tructivity** [comment]
@haverchuck @ykethan Can I get some help with this issue, please?

**Comment by Tructivity** [comment]
@salihgueler Can you help, please?

**Comment by ykethan** [comment]
@Tructivity Could you provide us the error message/output on the terminal?
when running `amplify codegen models` do you observe any error messages?

On diving into the documentation, could you try installing the libraries provided here https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#install-amplify-libraries
and initialize the Amplify API category using the call `Amplify.addPlugin()` method provided in the example. Then run `amplify codegen models`.

**Comment by Tructivity** [comment]
@ykethan The first image attached displays the configuration of plugins.

The second image shows the error I received when running the command "amplify codegen models."

Upon initially running the app, it displays the message: "No API plugin found."

Furthermore, we are not making any edits to the backend or pushing any changes. I have added a schema.graphql file to the project, but "amplify codegen models" is unable to locate it.

![image (4)](https://github.com/aws-amplify/amplify-cli/assets/30433012/0d4e979b-9470-421c-b2ca-db267f04269d)
![image (5)](https://github.com/aws-amplify/amplify-cli/assets/30433012/f78fc8c1-bbda-40e3-ace0-db9de07b1704)

**Comment by salihgueler** [comment]
@ykethan for this project, @Tructivity is trying to pull an Amplify project that they already have over Web into their Flutter project as well.

**Comment by Tructivity** [comment]
@salihgueler Yep, that's true

**Comment by ykethan** [comment]
Hey @Tructivity, could you try adding the `--model-schema` with the path to the schema file with the `amplify configure models` command.

@Tructivity to better understand, `over Web` meaning was the API added resources added on Amplify Studio or added via push in the same environment?
If the API was added on Amplify Studio, you should just be able to run the pull command to sync your resources locally.

**Comment by ykethan** [comment]
@Tructivity was able to get some additional information on the use case. I understand currently you have a application with a Amplify backend already present and would like to create a new frontend that utilizes existing backend resources.
Diving into this, we should be able to pull the backend environment `amplify pull --appId <app-id> --envName staging` and select `Do you plan on modifying this backend? No` which should pull your existing backend resource as immutable. If there an changes on the main backend, we should be able to run `amplify pull` to pull the changes.

**Comment by Tructivity** [comment]
@ykethan I have performed the amplify pull command for already existing amplify backend but it doesn't have added any plugins to amplifyconfiguration.dart and no models or schemas were added into the amplify folder yet the amplify backend has auth API and storage. Yet it's not fetching those into Flutter app and adding them automatically via the pull command. Is there any way to avoid this manual work?

![image (6)](https://github.com/aws-amplify/amplify-cli/assets/30433012/9cf992a0-a3c8-4526-bd64-ebc5fe0842a7)

**Comment by ykethan** [comment]
Hey @Tructivity, would you be open for a quick call? i am available on discord, my handle is `ykethan`.

**Comment by Tructivity** [comment]
@ykethan up to u but is it a big issue? I've contacted u there

**Comment by ykethan** [comment]
@Tructivity thank you for hopping on the call, were were able to import the resources and generate the models.
Closing the issue, please feel free in reaching out to us again.
