### ISSUE TITLE
When I try to do an amplify push I get this error: 🛑 Deployment is already in progress.

### ISSUE THREAD

**Issue by zandvakiliramin** [aws-amplify/amplify-cli#13392]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.8.0

### Amplify CLI Version

12.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I was trying to deploy an API using Amplify. The API was in a docker container, and Amplify was using the ECS for me. I did a ctrl + c in the middle to change something. Now when I want to push to the cloud I get this error.
🛑 Deployment is already in progress.

I checked the CloudFormation, and I can see it is stuck in a NESTED stack with the message UPDATE_IN_PROGRESS.

### Expected behavior

I need it to deploy my changes to the cloud

### Reproduction steps

1. Amplify add API
2. Select making an API using your own docker container
3. Amplify push
4. press ctrl + c in the middle

### Project Identifier

Project Identifier: 64645b8840605258eb3b7de823f2c831

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I resolved an issue like this (pressing ctrl + c in the middle of graphql api update) before by removing the file `deployment-state.json` from the S3 bucket and it worked. But this time that file does not exist in my Amplify's S3 bucket.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @zandvakiliramin, thank you for reaching out. you may have to manually cancel and rollback the update on the CloudFormation console, then run `amplify push`.
If the deployment on CloudFormation console performed the update, you could try running `amplify push --force` to redeploy the resources.

**Comment by zandvakiliramin** [comment]
Thanks @ykethan. Actually, a few hours later, it fixed itself and I was able to push successfully.
