### ISSUE TITLE
Deployment buckets in S3.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1340]
** Which Category is your question related to? **
S3 bucket creation.
** What AWS Services are you utilizing? **
S3 for hosting.
** Provide additional details e.g. code snippets **
Why are there so many S3 buckets for deployments? Named: {application_name}-{date}-deployment.

**Comment by yuth** [comment]
Amplify CLI creates a new buckets for each environment in the project. 

We could change the name of the deployment bucket to include the environment name so it makes it easy to distinguish

**Comment by jarrettj** [comment]
Thanks, that would be an awesome feature. Regards.
