### ISSUE TITLE
Unable to update stack if native client was removed

### ISSUE THREAD

**Issue by bynov** [aws-amplify/amplify-cli#13408]
### Amplify CLI Version

12.8.2

### Question

Hi,

I have an Amplify project with a Cognito User Pool.
By default, there were created two oAuth clients: Web client & Native client.

I accidentally removed native client and now I'm not able to perform any `amplify push` command at all. Error is something about `The following resource(s) failed to create: [UserPoolClientInputs]`, `User pool client does not exist`.
I checked logs and I believe it's because of missing native client. I created one more project, did the same and got the same error.

So my hunch is that native client id is set somewhere in the stack configuration and amplify trying to fetch it's secret.

Question: Is there a way to link another manually-created native client to an existing amplify configuration? I've checked docs here https://docs.amplify.aws/cli/auth/import/#add-environmental-variables-to-amplify-console-build and tried to use these env variables. However, it does not work. I tried both to set them on my local machine before executing `amplify push` and also tried to set them in AWS Amplify UI. Looks like `amplify push` command does not read these values.

**Comment by ykethan** [comment]
Hey @bynov, thank you for reaching out. Unfortunately, Amplify CLI does not support recreating user pool clients, this is currently being tracked as a feature request on https://github.com/aws-amplify/amplify-cli/issues/10871.
As a workaround, The easiest path forward would be to remove auth and add it again with the CLI to recreate entirely, however I understand this may not be feasible if there is production data from a live app. If this is the case, you can enable Deletion Protection for Cognito and remove it from your project, then use amplify import auth to import the same User Pool with the newly created client.
