### ISSUE TITLE
Amplify command not working

### ISSUE THREAD

**Issue by elkee2003** [aws-amplify/amplify-cli#13411]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dnxdny8iom5jq

### Region

us-east-1

### Environment name

VS code

### Amplify CLI Version

12.4.0

### If applicable, what version of Node.js are you using?

v18.14.2

### What operating system are you using?

Windows

### Browser type?

Google Chrome

### Describe the bug

- No amplify command is working, even `amplify version` is not working. I know the version I am using because I have checked before. 

- I also have another complaint of my data being unable to sync from amplify studio to my local server. I have made this complaint previously but I have not gotten a solution yet.

### Expected behavior

- Amplify commands like amplify help, amplify version, amplify init are meant to work or show something in my terminal
- My data is meant to sync from local server to remote server.

### Reproduction steps

running any command does not work. When I type a command nothing comes up. Please check attached.
![Screenshot (65)](https://github.com/aws-amplify/amplify-studio/assets/42178058/31c0f38c-3461-4ff7-b689-94edb5c0302e)

**Comment by elkee2003** [comment]
My node version is 18.14.2. Also, I have reattached the files    On Wednesday, November 15, 2023 at 04:26:01 PM GMT+1, Kethan sai ***@***.***> wrote:  
 
 


Hey @elkee2003, interesting. i was not able to reproduce in a windows environment. what is the npm and node version currently installed?

it appears the screenshot being referred to on the previous comment may have not come in.

**Comment by ykethan** [comment]
Thank you for the information, as a quick test could you try removing the `C:/user/<user-name>/.amplify` folder and if present remove the `C:/user/<user-name>/.amplify-pending-delete.exe` file.
Then install amplify CLI using `curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd`.
Do let us know if the behavior persists.

**Comment by elkee2003** [comment]
I tried what you see in the screenshot twice and I got same result. Should I resort to  npm i -g @aws-amplify/cli? It is important to note that my internet connection is ok
    On Wednesday, November 15, 2023 at 05:43:08 PM GMT+1, Kethan sai ***@***.***> wrote:  
 
 


Thank you for the information, as a quick test could you try removing the C:/user/<user-name>/.amplify folder and if present remove the C:/user/<user-name>/.amplify-pending-delete.exe file.
Then install amplify CLI using curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd.
Do let us know if the behavior persists.

**Comment by elkee2003** [comment]
I have installed it using `npm i -g @aws-amplify/cli`, and it worked. Thank you so much. Now about the Synchronization issue, I have been making complaints in the past about my data in amplify studio not automatically syncing with my data in the local server. The last time we spoke about this you said if the solution you gave me didn't work you were going to transfer me to your javascript team. 
    On Wednesday, November 15, 2023 at 05:43:08 PM GMT+1, Kethan sai ***@***.***> wrote:  
 
 


Thank you for the information, as a quick test could you try removing the C:/user/<user-name>/.amplify folder and if present remove the C:/user/<user-name>/.amplify-pending-delete.exe file.
Then install amplify CLI using curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd.
Do let us know if the behavior persists.

**Comment by ykethan** [comment]
Glad to hear that you were able to get the commands working, I also transferred the issue https://github.com/aws-amplify/amplify-js/issues/12573 to our JS repository for additional assistance.

Closing the issue.
