### ISSUE TITLE
amplify configure error FeatureFlags is not initialized

### ISSUE THREAD

**Issue by RuyCosta** [aws-amplify/amplify-cli#13410]
### How did you install the Amplify CLI?

npm 10.1.0

### If applicable, what version of Node.js are you using?

20.9.0

### Amplify CLI Version

12.8.2

### What operating system are you using?

windows 10 64bits

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No changes made

### Describe the bug

PS C:\users\ruy> amplify configure
🛑 FeatureFlags is not initialized

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 689480c9-8605-458c-9fda-dcb79237a1ae

PS C:\users\ruy\.amplify> amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
- Creating Zip
No Amplify backend project files detected within this folder.
× Creating Zip

No zip file created

### Expected behavior

amplify configure to run and setup the configuration for use in projects (amplify init) 

### Reproduction steps

1. user curl to install amplify cli -> OK
2. run amplify config and create the users and keys -> OK
3. use npm to install support packages listed in amplify site -> OK
4. run amplify init -> ERROR missing package body-parser
5. use npm to install body-parser -> OK
6. run amplify plugin -> OK
7. run amplify init -> ERROR missing package body-parser at C:\snapshot\... (C:|snapshot does not exist)
8. create C\snapshot and copy body-parser to the required location -> OK
9. run amplify plugin -> OK
10. run amplify init -> ERROR missing package express at C:\snapshot\...
11.  use npm to install express -> OK
12. copy express to the required location in C:\snapshot -> OK
13. run amplify plugin -> OK
14. run amplify init -> ERROR missing package express at C:\snapshot\...
15. uninstall amplify -> OK
16. remove C:\users\Ruy\.amplify and C:\snapshot
17. open a new powershell instance running as administrator
18. use npm to install amplify cli -> OK
19. check if C:\snapshot was ceeated -> NOT CREATED
20. run amplify config -> ERROR FeatureFlags is not initialized

### Project Identifier

No zip file is create by running amplify diagnose --send-report

### Log output

<details>

```
# Put your logs below this line
2023-11-15T09:28:55.292Z|info : amplify version core  
2023-11-15T09:31:40.570Z|info : amplify diagnose core  
2023-11-15T09:31:40.619Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-11-15T09:32:14.470Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2023-11-15T09:32:14.520Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-11-15T09:33:02.244Z|info : amplify configure core  
2023-11-15T09:33:02.291Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-11-15T09:33:33.118Z|error : FeatureFlags is not initialized
UnknownFault: FeatureFlags is not initialized
2023-11-15T09:33:48.255Z|info : amplify diagnose core  {"send-report":true,"yes":false}
2023-11-15T09:33:48.305Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-11-15T09:39:00.842Z|info : amplify init core  
2023-11-15T09:39:00.890Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-11-15T09:40:09.622Z|error : FeatureFlags is not initialized
UnknownFault: FeatureFlags is not initialized


```

</details>

### Additional information

I first thought the problem could be related to install without running as administrator because the C:\snapshot directory wasn't created but in fact my regular user can create files in the C:\ 
I've tried to redo the installation a few times using curl first and then npm as indicated in one of the message logs.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by RuyCosta** [comment]
Hello yekthan, first of all thanks a lot for your answer! It is similar to #11396, only in that case it looks like it was working normally, what ever happened with me as I was having errors while loading the libraries - that's the reason I've tried the reinstallation. I've looked for the amplify-pending-delete.exe but there was none so I've went through with the removal of the .amplify tree and made a new installation from a CDM terminal. It took longer as there was a timing-something message blinking around, but when finished the amplify configure failed the very same way... 
Anyway thanks again for the help and don't hesitate in asking me to look for more information at my PC or trying some other procedures :-)

**Comment by ykethan** [comment]
Hey @RuyCosta, interesting.  Would be open for a quick chat on discord? my handle is `ykethan`

**Comment by RuyCosta** [comment]
Sure thing, I'm usually available but yesterday I got some business to deal with and just saw your message today...
Let me know what time works better for you (by the way I'm in GMT)

**Comment by ykethan** [comment]
H3y @RuyCosta, sure. Do reach out, we can try to find an ideal time.

**Comment by RuyCosta** [comment]
I've sent a friend request...

**Comment by RuyCosta** [comment]
Thanks ykethan, it was really a issue from mc development pc as it works in another one, so I'm closing this issue.
