### ISSUE TITLE
How to add pipeline after matching template with CustomResources.json

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#1343]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **

** What AWS Services are you utilizing? **

** Provide additional details e.g. code snippets **

I can not find way to add pipeline after matching template with CustomResources.json.
Is there good waay to add it??

**Comment by yuth** [comment]
@bokuweb could you elaborate. Could you include what service you're using and what are you trying to achieve

**Comment by bokuweb** [comment]
@yuth Oops, sorry. i use amplify-cli with appSync.

I have a following schema now.

```
type A @model(mutations: null) {
  id: ID!
  b: B @connection(name: "conn")
}

type B @model(mutations: null, query: null) {
  canAccess: ID!
  as: [A] @connection(name: "conn")
}

type Query {
  getA(id: ID!): A
}
```

So, I would like to filter by `canAccess` with `Query.A.res.vtl`. However `$context.result` does not include `B`, it includes only `A { id: ID }`.... 

```
#if($context.result.b.canAccess != $context.identity.username)
    #set($errorInfo = {"status": 403});
    $utils.unAuthorized;
#else
    $utils.toJson($context.result);
#end
```

Is it possible with pipelines's `after mapping template` ?? If not, do you have any idea to do  it??

**Comment by yuth** [comment]
@bokuweb we recently added support for [field level auth](https://aws-amplify.github.io/docs/cli/graphql#field-level-authorization).

You can get update your schema as below to allow field level auth
```graphql
type A @model(mutations: null) {
  id: ID!
  b: B 
    @connection(name: "conn")
    @auth(rules: [{ allow: owner, ownerField: "canAccess" }])
}

type B @model(mutations: null, query: null) {
  canAccess: ID!
  as: [A] @connection(name: "conn")
}

type Query {
  getA(id: ID!): A
}
```

If you want to have some custom logic at the resolver  level of `type A.b` you could write a custom resolver inside the resolver folder of your project. The resolver would be named `A.b.req.vtl` and `A.b.res.vtl`

**Comment by bokuweb** [comment]
@yuth Thanks for your response!!

> we recently added support for field level auth.

Cool 🎉 I'll check it later :)

> custom resolver inside the resolver

Do you have any examples??

**Comment by yuth** [comment]
@bokuweb 
>  Do you have any examples??

https://aws-amplify.github.io/docs/cli/graphql#overwrite-a-resolver-generated-by-the-graphql-transform

**Comment by bokuweb** [comment]
@yuth Thanks :) 👍 

Ahh... Unfortunately, I don't use cognito user group, and I have a auth field as `String Set` because I refferred following document. I created a field like `PeopleCanAccess`. In this case I can not use field level `@auth` ? In this case I should use `custom resolver inside the resolver` or using other way (i.e. pipeline with lambda)??

https://docs.aws.amazon.com/ja_jp/appsync/latest/devguide/security-authorization-use-cases.html#reading-data

**Comment by mikeparisstuff** [comment]
@bokuweb If you need to filter by an attribute in type `B`, can you restructure such that you query that first and then traverse the connection? For example,

```
query {
  getB(filter: { canAccess: { eq: "123" } }) {
    canAccess
    as {
      id
    }
  }
}
```

You can use custom stacks to add pipeline functions using tables of your choosing as necessary. You can read more about how custom resources work within the Amplify CLI here https://aws-amplify.github.io/docs/cli/graphql#common-patterns-for-the-api-category. You can read more about pipeline resolvers here: .https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html

**Comment by bokuweb** [comment]
@mikeparisstuff  Thanks for your response. However  I guess It is not good if there is a malicious user.
For now I use `lambda` for Query. thanks :)
