### ISSUE TITLE
DynamoDB triggered lambda function retry limit

### ISSUE THREAD

**Issue by ggorge-me** [aws-amplify/amplify-cli#13438]
### Amplify CLI Version

12.6.0

### Question

My lambda function is triggered by DynamoDB stream. Is it possible to configure the advanced details like "Retry attempts" with amplify?

![image](https://github.com/aws-amplify/amplify-cli/assets/109138250/39a98178-1227-45b1-8d23-0d3b13657538)

**Comment by ykethan** [comment]
Hey @ggorge-etiqa, thank you for reaching out. We should be able to modify the CFN template on the Lambda function to add the retry attempts.
Under the `"Type": "AWS::Lambda::EventSourceMapping",` in the template on adding `"MaximumRetryAttempts": 10,` under properties and running push the function updated the retry.
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/b979d80a-7a15-468f-848e-c5321835db66)

But do note that the `-1` is the default value which will retry the event until it expires in the event stream.[CFN documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumretryattempts)
