### ISSUE TITLE
Missing attributes after recreating account using a social provider

### ISSUE THREAD

**Issue by steptro** [aws-amplify/amplify-cli#13431]
### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v18.16.1

### Amplify CLI Version

12.3.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Not sure if this is the correct place to create this issue. After signing up using a social provider for the second time when the account was deleted previously, several user attributes are missing. When you create an account for the second time the app is already known by the social provider. When revoking the app in the social provider and create the account again the attributes are set.

### Expected behavior

User attributes are set after signing up again after the user has deleted their account.

### Reproduction steps

1. Signup using a social provider with the following mapped attributes
<img width="864" alt="Screenshot 2023-11-26 at 17 32 46" src="https://github.com/aws-amplify/amplify-cli/assets/3731341/8c82e7f4-0c24-488b-86d1-2a0e543844df">
2. Delete account
3. Sign in / signup again using the social provider
4. Missing the firstName and lastName attributes

### Project Identifier

5675798e9d682c6bb49bd299ccfc6216

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @steptro, thank you for reaching out. On diving deeper into the issue I was able to find that this is currently an expected behaviour when using Apple as social provider.
The behaviour is currently being tracked on https://github.com/aws-amplify/amplify-js/issues/10182
The forum [here](https://developer.apple.com/forums/thread/119826?answerId=371443022#371443022) linked in the last comment on the issue provides this information.

**Comment by stephantromer-pon** [comment]
Hey @ykethan, thanks for responding so quickly! I will monitor the links you mentioned.
