### ISSUE TITLE
Using multienv and but not Amplify Console for continuous deployment and hosting

### ISSUE THREAD

**Issue by eunsanghandle** [aws-amplify/amplify-cli#1344]
**Which Category is your question related to?**
Multienv

**Provide additional details e.g. code snippets**
I am using multienv feature to have isolated backends for testing but I don't want to get tied into Amplify Console. Specifically I am intrigued to try out [Netlify Dev](https://www.netlify.com/products/dev/) or [its branch subdomain](https://www.netlify.com/docs/custom-domains/#branch-subdomains) feature. Is there any way to make this work?

**Comment by yuth** [comment]
Amplify CLI does not directly provide subdomains for branches. If you're using hosting and you want to have subdomain for each branch, you could try [CNAMEs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html) for cloudfront

**Comment by swaminator** [comment]
@eunsanghandle you get branch subdomains with the Amplify Console as well. The Amplify Console works well with the multienv functionality. In order to get it to work with other CI systems, you have to run amplify CLI commands in the build container.

**Comment by calspre** [comment]
Thanks @yuth for your reply! Netlify already supports [subdomains by branch](https://www.netlify.com/docs/custom-domains/#branch-subdomains) and I am not sure how CNAMEs would solve the problem.

Thanks @swaminator for your reply! Did you mean `npm install -g @aws-amplify/cli` and use `amplify env checkout`?

I was hoping to get the production/development resources in a more simpler approach, like:

```
import Amplify from 'aws-amplify'

// Only If there's something like this...
import { production_env_config, development_env_config } from './aws-exports'

process.env.node_env === 'production'
  ? Amplify.configure(production_env_config)
  : Amplify.configure(development_env_config)
```
