### ISSUE TITLE
Amplify commands not found despite installation 

### ISSUE THREAD

**Issue by NoellaMarie501** [aws-amplify/amplify-cli#13458]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

21.4.0

### Amplify CLI Version

not know can not run any amplify command

### What operating system are you using?

Ubuntu and Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes mad

### Describe the bug

I installed aws-amplify/cli with the command  `npm install -g @aws-amplify/cli` both on ubuntu and windows systems and the package was successfully added but i am unable to use any amplify command. I followed soo many debugging steps including checking the PATH on ubuntu and checking the symbolic link but it did not still help.

### Expected behavior

Amplify commands should execute as expected

### Reproduction steps

1. install amplify globally with npm : `npm install -g @aws-amplify/cli`
2. create a folder for project
3. navigate to project to run amplify commands :  `amplify configure` or `amplify init`

### Log output

<details>

```
# Put your logs below this line
sudo: amplify: command not found

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @NoellaMarie501, thank you for reaching out. In you working PC could you check the `~/.amplify/logs/` or `C:\Users\<username>\.amplify\logs` folders with the latest timestamp, do you observe any errors or logs?
Additionally, could you try running the CLI commands with the `--debug` flag.

**Comment by NoellaMarie501** [comment]
Hello @ykethan thank you for responding, with regards to checking the log file there are no errors or logs this is the only content of the file `2023-12-06T14:07:24.734Z|info : amplify version core `. About running the commands with the `--debug` flag i'm unable to run the commands because it says `amplify command not found

**Comment by ykethan** [comment]
@NoellaMarie501 thank you for the information. Do you observe a similar behaviour if you install Amplify CLI using the curl commands [here](https://docs.amplify.aws/react/start/getting-started/installation/#install-the-amplify-cli)

Was node/npm/amplify installed with sudo by any chance? Can you check the permissions on `~/.amplify` and see if root owns this directory? we could run `ls -al ~/.amplify` to check the permission. we may need to run `sudo chown -R $(whoami):$(id -gn) ~/.amplify` to mitigate the issue.

Are you able to run the binary directly with `~/.amplify/bin/amplify`?

**Comment by ykethan** [comment]
@NoellaMarie501 interesting, glad to hear the commands are now working. if the issue reappears do reach out to us and we would be happy in diving deeper. Closing the issue.

**Comment by relaycamp** [comment]
hi everyone,.

I am having the same problem.

I installed amplify cli on my new M2 Macbook Air and when I run amplify configure, the command immediately exits.

volta: 1.1.1
amplify cli: Latest version (not able to check because the command terminates)
amplify location: /Users/{myusername}/.volta/bin/amplify
