### ISSUE TITLE
Using "amplify add geo" appears to add the feature but no services are deployed in AWS

### ISSUE THREAD

**Issue by KingsleyStephens** [aws-amplify/amplify-cli#13464]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.18.1

### Amplify CLI Version

12.8.2

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I run "amplify add geo" and follow through the steps to add location search. When I do an "amplify push" I can see Geo and the placeIndex name in the list of resources it says it has deployed. However, when I look at the backend information in the Amplify Console I can see a list of the other three services I have enabled but not Geo. Also in the Location Services Console I can only see the name of a Place Index that I have created previously for another backend and not the one that Amplify is saying it has created. When I try to use the Geo API from JavaScript I get a 404 message saying it cannot find the API URL. I have searched in other regions associated with my account and cannot find the placeIndex service that was supposed to have been created.

### Expected behavior

The Geo placeIndex that Amplify says it has created should be visible in the Location Services Console and usable from the Geo API.

### Reproduction steps

When adding Geo from a freshly initialised project and empty folder it works as it should.

### Project Identifier

05eb17ec0fac728ff3640e0db511ebe8

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @KingsleyStephens, Thank you for reaching out. From the project identifier it appears the project contains `Location search (search by places, addresses, coordinates) ` as selection.

Tried reproducing the issue with the following steps

1. `amplify init`
2. `amplify add auth`
3. `amplify add geo`
4. selected `Location search (search by places, addresses, coordinates) `
5. then ran `amplify push`
6. `amplify geo console`

on the AWS console, observed the resource with env name created

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/9094464b-5fde-498b-a4b7-e6531c969c2b)


Are the reproduction steps similar to the environment geo resources?
Does the geo resource appear when running `amplify status`? 
Were there any errors observed on the push?

**Comment by KingsleyStephens** [comment]
Hi Kethan,
The reproduction steps are similar, and when I execute them in an empty folder I see the geo service deployed successfully. However, there seems to be something about my project that is problematic. 

![geopush](https://github.com/aws-amplify/amplify-cli/assets/32531520/03e8c3c2-2086-4ed5-86ff-7a19359e5efd)

In the console image you can see me do an update to the geo resource and do a push. Note that geoplaceIndex81fc0284 appears to update successfully.

![geoconsole](https://github.com/aws-amplify/amplify-cli/assets/32531520/793cad2e-78f8-4713-b814-122e39cee8c8)

However, in my geo console for that region you can see that there is another placeIndex that I have created for a previous backend, and not geoplaceIndex81fc0284.

I was getting errors in my console when I would do a push that were to do with UI component codegen. However, I resolved those errors by turning off Automatic Form Generation in the Amplify Console. The push experiment I did for the geo update above did not have any of those errors.

**Comment by ykethan** [comment]
Hey @KingsleyStephens, thank you for the confirmation. Could you remove the geo resource(`amplify remove geo`),`amplify push`, run `amplify status` to confirm the resource was pushed/removed, then re-add the geo resource and push. then run `amplify geo console` to confirm the resource on console.
I was not able to recreate the issue when creating a project with similar resources but wanted to check if recreating the index will create the resource on the AWS console.

**Comment by KingsleyStephens** [comment]
Hi Kethan, thanks for the suggestion to remove the faulty geo resource and add a new one in. A classic "turn it off and back on again" fix. Should have thought of that myself :) When I added a new geo resource and pushed, the location service was created and I can see it in my location services console. Problem solved, thanks!

**Comment by ykethan** [comment]
Glad to hear you were able to mitigate the issue. Closing the issue, please do reach out to us if this reoccurs.
