### ISSUE TITLE
Cannot access $PATH when mocking function

### ISSUE THREAD

**Issue by d-huck** [aws-amplify/amplify-cli#13460]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

21.2.0

### Amplify CLI Version

12.8.2

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

The related function has a layer set up in cloud resources to provide ffmpeg

### Describe the bug

When calling an executable provided by the lambda container and local system within code, lambda cannot find the executable locally. In my specific case, I am attempting to use `ffmpeg` to concatenate two retrieved videos in a lambda function. Code will run fine in the lambda, but I am unable to mock the function for local testing/verification.

### Expected behavior

When calling an executable provided on the local system, I expect for the executable to be called.

### Reproduction steps

1. `amplify add function`
2.  Select `Go` as runtime
3. Minimal code example:
```go
package main

import (
	"context"
	"log"
	"os/exec"

	"github.com/aws/aws-lambda-go/lambda"
)

type MyEvent struct {
	Name string `json:"name"`
}

func HandleRequest(ctx context.Context, event SNSEvent) (string, error) {
	cmd := exec.Command("ffmpeg", "-version")
	out, err := cmd.Output()
	if err != nil {
		log.Println("ffmpeg error", err)
		return "failure", err
	}

	log.Println(out)
	return "success", nil
}

func main() {
	lambda.Start(HandleRequest)
}
```
4. Mock function

### Project Identifier

5ed20e93d1463f6c86d9ee36980bc7ef

### Log output

<details>

```
# Put your logs below this line

2023-12-07T21:10:42.394Z|info : amplify function mock <functionName>
2023-12-07T21:10:42.493Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-12-07T21:10:58.511Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["<CONFIG>"])
2023-12-07T21:10:58.514Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"<REGION>"}])
2023-12-07T21:10:58.514Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["<CONFIG>"])

```

</details>

### Additional information

Guidance on how to set the $PATH variable for the local function would be sufficient to solve this issue

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @d-huck, thank you for reaching out. 
In reproducing, I was able to access the package by using the Absolute Path to the package i installed using HomeBrew.

```
package main

import (
	"context"
	"log"
	"os/exec"

	"github.com/aws/aws-lambda-go/lambda"
)

type MyEvent struct {
	Name string `json:"name"`
}

func HandleRequest(ctx context.Context, event MyEvent) (string, error) {
	cmd := exec.Command("/opt/homebrew/bin/ffmpeg", "-version")
	out, err := cmd.Output()
	
	if err != nil {
		log.Println("ffmpeg error", err)
		return "failure1", err
	}
	

	log.Println(out)

	return "success", nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

with mock output as 
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/81d4f5d6-e780-4e30-a731-a4db9d26f985)

you could try to set the path env var at the start of the function for testing.
Do note that, `amplify mock function` does not attempt to fully simulate the Lambda runtime environment. There may be some cases where the behavior of your function when mocking differs from executing in the cloud.

For example, mock runs on your local OS and does not attempt to emulate Amazon Linux which executes your function in the cloud. Testing with amplify mock function should be used to get quick feedback on the correctness of your function but should not be used as a substitute for testing in a cloud development environment.

**Comment by d-huck** [comment]
Thank you for reaching back out! This is a sufficient workaround for us, thank you again.
