### ISSUE TITLE
Cannot Pull Amplify Project that has symlink the #current-cloud-backend in deployment bucket 

### ISSUE THREAD

**Issue by ottinochris** [aws-amplify/amplify-cli#13463]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.18.2

### Amplify CLI Version

12.8.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have tried to download the #current-cloud-backend.zip. Remove the symlink, zip and re-upload. 

### Describe the bug

I have a situation where I leverage Prisma in a lambda layer. It was working well and I was able to push until I had someone else try and pull then I would get an error saying that the symlink does not exist. Specifically ENOENT: no such file or directory, stat {path to symlink}

 The error is similar to this issues https://github.com/aws-amplify/amplify-cli/issues/2948.  

What I tried to do is delete the amplify directory for the backend of the project, download the #current-cloud-backend.zip, remove the symlink, zip the directory back up, and then add it back into S3. However when I do this and try to pull I get a messaging asking me to get credentials, then I'm routed to Amplify Studio, where selecting the environment is stuck in a loop. 

If I add the original #current-cloud-backup.zip back to S3 then it resolves the amplify studio env selection issue (both for directory logging in or if prompted for credentials) but then obviously I'm back to the original symlink based pulling issue. 

### Expected behavior

I should be able to remove the amplify directory from my project, do `amplify pull` and it pull in the backend. 

### Reproduction steps

Initialize a project. 

Create a lambda layer with a symlink 

do an amplify push

try and do an amplify pull and the issue will start showing up

bonus: delete the amplify directory locally and still pulling will fail 

### Project Identifier

Can't do this since there is no backend project folders locally anymore. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ottinochris** [comment]
@ykethan as of now, I just drop in the original current-cloud-backend zip so that I am able to log into amplify studio OR attempt an 'amplify pull' When I do the pull now (since my backend has been completely removed locally) it just says ENOENT: no such file or directory, stat <path to offending file in the .temp directory that no longer exists)

**Comment by ottinochris** [comment]
Working with AWS Support I now see File at path: '<mypath>/amplify/#current-cloud-backend/amplify-meta.json' does not exist. This is a new error, with the original #current-cloud-backend file in place (that has the symlink)

**Comment by ykethan** [comment]
Hey @ottinochris, from the error it appears the `#current-cloud-backend.zip` may not have `amplify-meta.json` file , could verify the if the zip does have `amplify-meta.json` at the root?
if not, create a copy of `#current-cloud-backend.zip` as backup, 
unzip the `#current-cloud-backend.zip`, then add the local copy of `amplify-meta.json` at the root or use the file present at the root of the deployment bucket if you do not have a local copy, zip the `#current-cloud-backend.zip` and upload it. while zipping do ensure `current-cloud-backend` is not being zipped as a nested folder 

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/395d085c-5206-4a57-8a64-7e75fb509aed)

**Comment by ottinochris** [comment]
I have verified that there is amplify-meta.json in the #current-cloud-backend.zip that exists within the deployment bucket. The error is referencing my local env. What I have tried to do is pull down the #current-cloud-backup. Unzip it and add it to my amplify directory locally to ensure they are the same, then re-run amplify pull. When I do that I see 'ProjectNotInitializedError: No Amplify backend project files detected within this folder.'

**Comment by ykethan** [comment]
@ottinochris as a quick test, could try pulling the project into a new empty folder outside the existing project directory using `amplify pull --appId <app-id> --envName <env-name>`. Are you able to pull the backend or receive a similar error message?

**Comment by ottinochris** [comment]
@ykethan so I was actually able to resolve the pull by removing the sim links and zipping the archive in the way [Etep15] recommended in the issue you linked. Once I was able to pull in the environment again, I just added a script to the main package.json that builds the layer with a --no-bin-links flag so the symlink won't be generated again. Looks to be working again.

**Comment by ykethan** [comment]
@ottinochris glad to hear that you were able to mitigate the issue.
Closing the issue, please feel free in reaching out to us for any assistance.
