### ISSUE TITLE
Error outputting keys and certificates" when adding APNS notifications to Amplify

### ISSUE THREAD

**Issue by kayzkenny** [aws-amplify/amplify-cli#13474]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.10.0

### Amplify CLI Version

12.9.0

### What operating system are you using?

MacOS Ventura 13.6

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

In my Flutter project I'm trying to add notifications with APNS. When I do this I get the following error message after giving the path to the .p12 certificate and writing the non-existent password (just pressing enter):

```
amplify add notifications                                                                                                             ─╯
✔ Choose the notification channel to enable · APNS |  Apple Push Notifications   
✔ Select the authentication method for the APNS channel · Certificate
✔ The certificate file path (.p12):  · /Users/kehindeakeredolu/Desktop/freelance/light-app/carnet_light/assets/amplify.p12
✔ The certificate password (if any):  · 
Error outputting keys and certificates
806024E901000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
🛑 Command failed: openssl pkcs12 -in /Users/kehindeakeredolu/Desktop/freelance/light-app/carnet_light/assets/amplify.p12 -out /var/folders/n4/r1prvfbj5hs0m1hfkn9y2w180000gn/T/temp.pem -nodes -passin pass:
Error outputting keys and certificates
806024E901000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()


Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 142fb2ce-7946-471f-aab9-78ebeff10c44

✅ Report saved: /var/folders/n4/r1prvfbj5hs0m1hfkn9y2w180000gn/T/lightAppDev/report-1702484584474.zip

✔ Done

Project Identifier: d2ab3b97bdfa12d6121b99659aa629ee
```

### Expected behavior

Amplify notifications should be added to the project without any problems.

### Reproduction steps

Create Flutter project and add Amplify to it.
Follow the official guide to add Notifications to said project.

### Project Identifier

d2ab3b97bdfa12d6121b99659aa629ee

### Log output

<details>

```
# Put your logs below this line

2023-12-13T16:21:39.430Z|info : amplify add notifications  
2023-12-13T16:21:39.506Z|info : @aws-amplify/amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2023-12-13T16:23:06.910Z|error : Command failed: openssl pkcs12 -in /Users/kehindeakeredolu/Desktop/freelance/light-app/carnet_light/assets/amplify.p12 -out /var/folders/n4/r1prvfbj5hs0m1hfkn9y2w180000gn/T/temp.pem -nodes -passin pass:
Error outputting keys and certificates
806024E901000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

UnknownFault: Command failed: openssl pkcs12 -in /Users/kehindeakeredolu/Desktop/freelance/light-app/carnet_light/assets/amplify.p12 -out /var/folders/n4/r1prvfbj5hs0m1hfkn9y2w180000gn/T/temp.pem -nodes -passin pass:
Error outputting keys and certificates
806024E901000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @kayzkenny, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/12969.
Noticed your comment on the issue, did you try switching to LibreSSL in your terminal as suggested in the comment https://github.com/aws-amplify/amplify-cli/issues/12969#issuecomment-1642458812

**Comment by kayzkenny** [comment]
@ykethan i saw the comment, but can't find instructions on how to switch the LibreSSL. Can you point me in the find directions?

**Comment by kayzkenny** [comment]
@ykethan i was able to enable APNs.

I had to first install libressl using `brew install libressl` and add it to my path using `export PATH="/opt/homebrew/opt/libressl/bin:$PATH"`

This should be in the docs as most flutter devs might not figure this out on their own.

**Comment by true-glassy** [comment]
As @ykethan mentioned you have to 

1. `brew install libressl` 
2. `export PATH="/usr/local/opt/libressl/bin:$PATH"` (you have to know where is your liberssl was downloaded and use that in your export)

The command to know where is your liberssl was is `brew --prefix libressl`
