### ISSUE TITLE
We are unable to process your request. Please reach out to your support representative.

### ISSUE THREAD

**Issue by moldo1028** [aws-amplify/amplify-cli#13470]
### Amplify CLI Version

12.8.2

### Question

Hi,

I am trying to integrate AWS Amplify with my application. However, I am getting the error "We are unable to process your request. Please reach out to your support representative". All of my IAM preferences are set as expected with the AWS Amplify Admin access, and I followed every step in the initialization process. This is taking place after running "amplify init" in my project root directory. Am I missing something? I've tried every troubleshooting step I came across but am still having the same error message. Any help would be greatly appreciated.

**Comment by ykethan** [comment]
Hey @moldo1028, thank you for reaching out. 
The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/13124 which occurs on a account level.
Similar to the GitHub issue are you unable to create a application on the console as well?

If you have a premium support plan, could you open a support case under the Amplify Console Support with a brief explanation with the error and being unable to create resources.

If you do not have a support plan and see a Basic Support Plan in the AWS support console,
create a new support case under Account and Billing using the following headings:
Service: Account
Category: Other Account Issues
General Question
add a subject line say `Check Account Status - Amplify Console` and describe the issue you are experiencing such as the error message and unable to create a app. Do link the GitHub issue to the support ticket to help track the issue.

**Comment by moldo1028** [comment]
Hey @ykethan thank you for your response. I tried to create an application on the console as well, and am getting the same error. I did open a support case (basic support) but have not heard back yet, how long is the typical turnaround time? Thanks

**Comment by ykethan** [comment]
Hey @moldo1028, sorry to hear that. The support should provide a response soon. Could you provide us the case ID I can try to follow up with the team.

**Comment by eyalag** [comment]
I am getting the same issue, when creating a new app and when creating with existing repo.
Any solutions? @ykethan

**Comment by leeroyp** [comment]
Im also facing the same issue with amplify. Any solutions for this issue ? @ykethan

**Comment by ykethan** [comment]
Hey, as described here: https://github.com/aws-amplify/amplify-cli/issues/13470#issuecomment-1850691317. open a case on the AWS support console

**Comment by natef-GuruTech** [comment]
I'm running into this issue as well. I'd be very surprised if it was an account quota issue in my case because this would be my first Amplify app. 
My steps:
Begin from the Amplify console -> click "Get Started" under "Amplify Studio" -> Enter an app name and click "Confirm Deployment"

I get an error screen with this message:
>Creating your AWS Amplify app failed.
>We are unable to process your request. Please reach out to your support representative..

**Comment by kfuku1634** [comment]
I have had this issue.
Could I open the case instead? @ykethan

**Comment by ykethan** [comment]
Hey yes, do open a case with the support team [here](https://support.console.aws.amazon.com/support/home#/) so that they can dive into your account.

**Comment by kfuku1634** [comment]
I opened the case.
Case ID: 170917573001098

**Comment by kfuku1634** [comment]
I had my issue resolved at AWS support center, but I didn't see what is the factor.
You should open your issue at AWS support center.

**Comment by adamatdevops** [comment]
This issue accusers a lot during GitHub authorization process. Everything looks fine...But sometimes AWS takes you back to a different region
