### ISSUE TITLE
AppSync GraphQL: Add @connection data to a model as a batch

### ISSUE THREAD

**Issue by Jeyloh** [aws-amplify/amplify-cli#1347]
** Which Category is your question related to? **
AppSync, Mutation, Resolver

** What AWS Services are you utilizing? **
AppSync, GraphQLTransform, Cognito

** Provide additional details e.g. code snippets **

I have 2 models in schema.graphql (see image under). Radar.techList is an @connection with Tech. I want to create a feature where a Radar can be added with already added Tech. This means that all the Tech I want to add to the radar needs to be duplicated with another Tech.radar value. 

I tried to simply add Radar with an array of Tech, which returns 

```{"data":null,"errors":[{"path":null,"locations":null,"message":"The variables input contains a field name 'techList' that is not defined for input object type 'UpdateRadarInput' "}]}```

Is there any intended way of doing this? I see one solution which is to loop through all Tech and duplicate them while renaming the Tech.radar field. However, I'd prefer something more "batchy". 

![image](https://user-images.githubusercontent.com/10498512/56741475-3b948580-6773-11e9-9977-218c28dddb08.png)

**Comment by mikeparisstuff** [comment]
Currently, the way to do this is via a custom mutation or lambda resolver. You can read more about how to use custom resources to create custom resolvers & attach lambda function resolvers here https://aws-amplify.github.io/docs/cli/graphql#common-patterns-for-the-api-category.

PR #1346 implements the `@function` directive that provides a much simpler interface for configuring lambda resolvers (although the process is very similar under the hood). Once this is merged, you will be able to do:

```
type Mutation {
  createRadarWithTech(..): Radar @function(name: "CreateRadarAndTech")
}
```

I'd also point you to #1060 which discusses supporting custom transformers. With this you would be able to implement your own `@batchCreate` directive that configures the call in a reproducible way such that you can use it with multiple models.

**Comment by Jeyloh** [comment]
Hi @mikeparisstuff and thanks for the reply. PR #1346 is a very welcome feature. I've found a working solution for now which I'll replace with batchCreate solution when ready. I prefer that towards creating custom resolvers as for now. 

Thanks again! Love what you're doing here
