### ISSUE TITLE
I can't do an amplify pull

### ISSUE THREAD

**Issue by meganmuirhead** [aws-amplify/amplify-cli#13471]
### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v21.1.0

### Amplify CLI Version

12.8.2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

i am trying to do an amplify pull but i am getting this error

### Expected behavior

for amplify to do a pull

### Reproduction steps

in the root of my project directory i am running amplify pull and i get an error

### Project Identifier

amplify pull

### Log output

<details>

```
# Put your logs below this line
i34124@LVVYVN2RGQ Product Marketplace App % amplify pull

Pre-pull status:

    Current Environment: dev
    
┌──────────┬───────────────┬───────────┬─────────────────┐
│ Category │ Resource name │ Operation │ Provider plugin │
└──────────┴───────────────┴───────────┴─────────────────┘

✔ Successfully pulled backend environment dev from the cloud.
✅ 
Post-pull status:

    Current Environment: dev
    
┌──────────┬───────────────┬───────────┬─────────────────┐
│ Category │ Resource name │ Operation │ Provider plugin │
└──────────┴───────────────┴───────────┴─────────────────┘

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/i34124/Projects/Aws/Product Marketplace App.
🚫 folderNotFound: Amplify generated models not found at /Users/i34124/Projects/Aws/Product Marketplace App/amplify/generated/models
-- Recovery suggestion: Run amplify codegen models.
🛑 Command failed with exit code 1: /Users/i34124/.amplify/lib/aws-amplify-amplify-frontend-ios/resources/amplify-xcode import-models --path=/Users/i34124/Projects/Aws/Product Marketplace App

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

```

</details>

### Additional information

I am super new to amplify so i am not sure what i am doing wrong, i am so sorry 

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @meganmuirhead, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-swift/issues/3307.
Noticed a workaround on the issue: https://github.com/aws-amplify/amplify-swift/issues/3307#issuecomment-1769010621
Do subscribe to the linked issue for further updates,.
Marking this as duplicate and closing.
