### ISSUE TITLE
How to use the AWSTimestamp scalar

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1348]
When I `amplify push` a schema with the following model and hit yes to also generate my mutations I get a conflicting type.

`type Swipe
  @model
  @auth(rules: [{allow: owner}])
{
  id: ID!
  userId: ID!
  recipe: Recipe! @connection
  liked: Boolean!
  timestamp: AWSTimestamp
}`

My mutation expect a timestamp in form of a string, but graphQL want an Integer.

This works but is ugly and typescript linter is complaining here:
`timestamp: Math.round(new Date().getTime() / 1000)`

What is the proper way to send a AWSTimestamp value in my mutations ?

**Comment by mikeparisstuff** [comment]
With a model like this:

```graphql
type User @model {
  id: ID!
  userId: ID!
  dt: AWSDateTime
  ts: AWSTimestamp
}
```

you can run a mutation like this:

```graphql
mutation {
  createUser(input:{
    userId: "test",
    dt: "2019-04-26T19:45:13.970Z",
    ts: 1556307929337
  }) {
    id
    ts
    dt
    userId
  }
}
```

which will return:

```javascript
{
  "data": {
    "createUser": {
      "id": "b12052b3-a002-4025-90ac-cc6bd421bbda",
      "ts": 1556307929337,
      "dt": "2019-04-26T19:45:13.970Z",
      "userId": "test"
    }
  }
}
```

**Comment by sprucify** [comment]
My mutations in GraphiQL work fine, but during an `amplify push` you get the  option to automatically create the javascript functions that perform the mutations for you.
The attribute `timestamp` in that functions has a Typescript type string instead of int.

So it conflicts with the GraphQL backend

**Comment by sprucify** [comment]
No cache problem.
`amplify codegen` command set AWSTimestamp scalars as string types.

`export type CreateSwipeInput = {
  id?: string | null;
  liked: boolean;
  timestamp?: string | null;
  swipeRecipeId: string;
};`
