### ISSUE TITLE
npm i  @aws-amplify/cli

### ISSUE THREAD

**Issue by tphobe9312** [aws-amplify/amplify-cli#1349]
`npm ERR! Unexpected end of JSON input while parsing near '...rectories":{},"dist":'` while installation.

**Comment by ajhool** [comment]
Try `npm cache clean --force`

**Comment by tphobe9312** [comment]
already done

**Comment by yuth** [comment]
@tphobe9312 what OS are you using? Can you also include the version of NPM. 

Does NPM print for what package this is happening?

**Comment by tphobe9312** [comment]
OS is Win 10
npm -v is 6. something
no npm doesn't print any package.

**Comment by tphobe9312** [comment]
`npm -v`  6.4.1
`node -v`  v10.15.3

**Comment by tphobe9312** [comment]
slow internet might be the reason.
