### ISSUE TITLE
Running setup-dev on Windows ends with an error

### ISSUE THREAD

**Issue by kavengagne** [aws-amplify/amplify-cli#135]
**Describe the bug**
Running ``` npm run setup-dev ``` on Windows ends in error because the zip command does not exist.

**To Reproduce**
- Clone the repository with the .circleci files renamed to work on Windows
```Shell
git clone https://github.com/kavengagne/amplify-cli.git
cd amplify-cli
npm install
npm run setup-dev
...
lerna ERR! build Errored while running script in 'graphql-elasticsearch-transformer'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! 'zip' is not recognized as an internal or external command,
lerna ERR! operable program or batch file.
```

**Expected behavior**
This command should use a zip tool that works on all OS.

**Desktop (please complete the following information):**
 - OS: Windows (All Versions)

**Additional context**
The problem happens because the zip command does not exists on Windows.

I will send a Pull Request to fix it.
I'm using bestzip, which uses the native zip command on linux and a node implementation when zip is not available.

**Comment by kaustavghosh06** [comment]
We just published to npm with a fix for this. Please use the version -> 0.1.19.
Closing the issue, feel free to re-open if the issue persists.

**Comment by rahulbhankar786** [comment]
@kaustavghosh06 Not working with v0.1.19
