### ISSUE TITLE
[multienv] Auth did not update when switching to a different env

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#1350]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
I have three environments: (NONE, dev, production), where NONE is an obsolete env from before multienv was released. I am currently using the "dev" environment, but `amplify/backend/auth` and `aws-exports.js` are still stuck on the NONE version of Auth.

**To Reproduce**
Not sure how I got into this state. Will try to make up for lack of reproduction by providing config.

**Expected behavior**
`Amplify/backend/auth` should reflect my dev env configuration instead of my NONE env configuration while env is set to dev

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 1.6.4

**Smartphone (please complete the following information):**
 N/A

**Additional context**

[ substituted actual key with 1abcde ]
The desired userpool is: cognito1abcde_userpool_1abcde-dev
The current userpool is: cognito1abcde_userpool_1abcde

The desired userpool does exist, so it was created at some point.

---
`amplify env list`:

| Environments |
| ------------ |
| NONE         |
| *dev         |
| production   |

---

`amplify status`
| Category  | Resource name        | Operation | Provider plugin   |
| --------- | -------------------- | --------- | ----------------- |
| Auth      | cognito1abcde      | No Change | awscloudformation |
| Api       |  api       | No Change | awscloudformation |
| Storage   | contentphotos        | No Change | awscloudformation |
| Analytics | analytics      | No Change | awscloudformation |
| Function  | function1         | No Change | awscloudformation |
| Function  | function2 | No Change | awscloudformation |

---
```
current-cloud-backend/auth/cognito1abcde/parameters.json/
"userPoolName": "cognito1abcde_userpool_1abcde",
```

```
backend/auth/cognito1abcde/parameters.json/
"userPoolName": "cognito1abcde_userpool_1abcde",
```
I checked the dev stack in `team-provider-info.json` and confirmed that the dev stack contains the desired userpool. I also confirmed that the current userpool comes from the NONE environment.

I can provide the full team-provider-info.json, although I'm not sure if there is anything sensitive in there.

I also notice that there might be a parsing error for auth:
```
amplify get env --name dev
dev
--------------
Provider: awscloudformation
AuthRoleName: cognitoauth-20190109215055-authRole
UnauthRoleArn: arn:aws:iam::637593006276:role/cognitoauth-20190109215055-unauthRole
AuthRoleArn: arn:aws:iam::637593006276:role/cognitoauth-20190109215055-authRole
Region: us-east-1
DeploymentBucketName: cognitoauth-20190109215055-deployment
UnauthRoleName: cognitoauth-20190109215055-unauthRole
StackName: cognitoauth-20190109215055
StackId: arn:aws:cloudformation:us-east-1:637593006276:stack/cognitoauth-20190109215055/8d28dc00-1482-11e9-bc55-12391cfc54f4
--------------

Provider: categories
auth: [object Object]
--------------

**Comment by ajhool** [comment]
I have tried `amplify env pull` and the configuration did not change.

This week I had been planning on "redoing" auth to change the login requirements (the user currently needs a username + phone number + email + password... I would like to switch to just [ email OR phone number ] + password). So, if my auth is in a bad state, I would also be curious how to just replace it with a new setup rather than fix it.

**Comment by kaustavghosh06** [comment]
@ajhool Can you try doing `amplify env pull --restore`?

**Comment by ajhool** [comment]
`amplify env pull --restore` did not resolve the issue.

Output :
```
(a temporarily line that said something like "initializing dev environment")
✔ Initialized provider successfully.
Initialized your environment successfully.
```

`amplify env status` shows No Changes for all items.

I tried `amplify push` but I don't believe that it does anything when there are No Changes across the board. It did not generate a new `aws-exports.js`

The ultimate error occurs when trying to use the `Authenticator` component. There is a "no userpool" error when trying to sign in.

**Comment by ajhool** [comment]
I've "resolved" this issue by simply using `amplify remove auth` and creating a new one. I also found a potentially confounding issue, which I will address in a separate issue

**Comment by ajhool** [comment]
It appears that removing auth did not resolve this issue or perhaps introduced new ones.

I created a new Auth resource but amplify push is no longer working. The error appears to stem from:

```
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      UserPoolClientLambda                                             AWS::Lambda::Function      Tue May 14 2019 23:04:15 GMT-0400 (Eastern Daylight Time) Resource creation cancelled
CREATE_IN_PROGRESS UserPoolClientLambda                                             AWS::Lambda::Function      Tue May 14 2019 23:04:15 GMT-0400 (Eastern Daylight Time)       
```

I'm not sure what UserPoolClientLambda is, but it is not a custom function from me

**Comment by kaustavghosh06** [comment]
@ajhool I beleive this auth resource was created with previous versions of the CLI, before we upgraded our default Cloudformation tempaltes to Node 8.10. Here's a quick migration guide out here - https://aws-amplify.github.io/docs/cli/lambda-node-version-update#auth

**Comment by ajhool** [comment]
Sounds correct, thanks
