### ISSUE TITLE
There is already a Construct with name 'transformer-user-pool' in TransformerRootStack [transformer-root-stack]

### ISSUE THREAD

**Issue by Martin-HHH** [aws-amplify/amplify-cli#13502]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.10.0

### Amplify CLI Version

12.9.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No, only amplify push other times.

### Describe the bug

[MyPath] amplify push
√ Successfully pulled backend environment staging from the cloud.

    Current Environment: staging

[Removed the table intentionally]

√ Are you sure you want to continue? (Y/n) · yes
Cognito UserPool configuration
Use a Cognito user pool configured as a part of this project.
� There is already a Construct with name 'transformer-user-pool' in TransformerRootStack [transformer-root-stack]

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 8acd5ab2-3f84-40e4-ab43-5c636038ab54

### Expected behavior

I have not been able to produce the Cognito user for my requests to the API. I changed from API Key to Cognito but I was somehow not successful. The Cognito user pool is not created on Dev environment, though it is on testing and Prod.

### Reproduction steps

1. Just typed "amplify update api", chose GraphQL, authorization, then chose Cognito and nothing else happened.
2. Then I tried amplify push and the error above happened.

### Project Identifier

Project Identifier: 78090b52931979e32bf982114e250585

### Log output

I cannot find the route specified, sorry.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Martin-HHH, thank you for reaching out. Tried reproducing the issue but did not observe this behavior. 
Does the project have any auth overrides?
Could you try running `amplify pull` (should discard the previous changes), update the api authorization and run push?
was the auth resource added after running a `amplify env checkout` from a different environment such as testing or Prod?

**Comment by Martin-HHH** [comment]
Hi Kethan sai,

I resolved the issue by terminating the environment and initializing it
again. Now I don't face that issue.

I noted the Cognito Auth was not removed when I changed the authentication
mode in the API, though. I had to manually remove it, in case this helps.

No, there was only one environment in the amplify app.

Please, let me know how else I can help you.

Merry Christmas!
Martín.

**Comment by ykethan** [comment]
Hey @Martin-HHH, thank you for the information, glad to hear that you were able to mitigate the issue. Tried reproducing the  issue but did not observe this behavior but making a note of this behaviour for future references. I will close the issue for now, do reach out to us if the behavior reoccurs, we would be happy in reopening this.
