### ISSUE TITLE
Configure Google attribute mapping without marking as required

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-cli#13511]
### Amplify CLI Version

12.3.0

### Question

I went through the following guide: https://docs.amplify.aws/javascript/build-a-backend/auth/override-cognito/#customize-amplify-generated-cognito-auth-resources-with-social-providers, but it didn't work. And in the following issue https://github.com/aws-amplify/amplify-cli/issues/11646, I saw that marking attributes as required should allow the mapping, but is there a way without marking as required?

**Comment by redjonzaci** [comment]
I am looking into doing that through the post-push command hook, but I don't have access to the user pool ID.
Just mentioning it in case it helps with ideas.

**Comment by redjonzaci** [comment]
I also found the following issue https://github.com/aws-amplify/amplify-cli/issues/12910.

**Comment by ykethan** [comment]
Hey @redjonzaci, thank you for reaching out. you should be able to create a custom attribute as optional using the auth override. we have an example on https://docs.amplify.aws/javascript/build-a-backend/auth/override-cognito/#customize-amplify-generated-cognito-auth-resources

**Comment by redjonzaci** [comment]
Hey @ykethan, I need to configure the Google attribute mapping, not a custom attribute on the Cognito user pool.

**Comment by ykethan** [comment]
Hey @redjonzaci, thank you for the clarification, this looks similar to https://github.com/aws-amplify/amplify-cli/issues/12910#issuecomment-1714678419.
Update the attributes can be done when adding provider or removing a provider, it will cause the Lambda callout to fire and update the social providers with the new attribute mapping.
i was able to update the attribute, by running `amplify update auth` -> select the provider, then add the attribute in the `cli-inputs.json` in the `hostedUIProviderMeta` `AttributeMapping` then run push which should update the attributes. 
do note that running an update auth may override the changes.
To understand making an attribute optional are you referring to the following?
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/f991eb25-ba52-49e7-a22c-5ede94c746a7)

**Comment by redjonzaci** [comment]
I read in https://github.com/aws-amplify/amplify-cli/issues/11646 that if I mark attributes in Cognito as required, they will be added in the identity provider attribute mapping. 
But I was looking for a way to keep the Cognito attributes optional and still add them in the identity provider attribute mapping programmatically.
What I am not getting is why would an additional `amplify update auth` override the attribute mapping I provided previously in the `cli-inputs.json`?

**Comment by redjonzaci** [comment]
Also, the approach you're suggesting should work when creating new PRs?
I am testing this now and will reply again later.

**Comment by ykethan** [comment]
Hey @redjonzaci, when we create a auth resource with `amplify add auth`, you should be able to remove the required attributes. by default the cognito expects an attribute with sub and should be created as optional from my testing. you could then add the additional attributes in the `cli-inputs.json` and push

```
Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? <- removed here
 Do you want to enable any of the following capabilities? 
 What domain name prefix do you want to use? attribs6b68ffc7-6b68ffc7
 Enter your redirect signin URI: http://localhost:3000/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:3000/
? Do you want to add another redirect signout URI No
 Select the social providers you want to configure for your user pool: Google
```

on cognito

![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/7b0cd140-1e78-4a43-b5c1-e4a6af13b2d4)

**Comment by redjonzaci** [comment]
Let's say I have added `given_name` mapping to `cli-inputs.json`, will it be mapped when a new env is created?
This was my latest question.

**Comment by redjonzaci** [comment]
It worked. Thanks for the support and happy holidays @ykethan!

**Comment by ykethan** [comment]
@redjonzaci Glad to hear the suggestion worked. The `amplify add env` should not remove the changes. But noticed this behavior when we update the auth to add a new oauth provider the CLI overrides the `cli-inputs.json` file.

Closing the issue, do reach out to us if you require any assistance.
