### ISSUE TITLE
Inaccessible host: amplify.us-east-1.amazonaws.com at port 443

### ISSUE THREAD

**Issue by 779503982** [aws-amplify/amplify-cli#13519]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

"amplify publish" reports the following error:

Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
🛑 Inaccessible host: `amplify.us-east-1.amazonaws.com' at port `443'. This service may not be available in the `us-east-1' region.

The failure has persisted except for one success yesterday morning.

I have reports saved automatically. I am not sure if it contains sensitive information regarding my project. Please let me know if you need that.

Thanks,
MC

### Expected behavior

I wish amplify publish can be successful

### Reproduction steps

1. amplify publish

### Project Identifier

c6c0d0e9f3270b1a1a4c378371fcba86

### Log output

<details>

```
# Put your logs below this line
√ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev

┌──────────┬──────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name        │ Operation │ Provider plugin   │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Auth     │ ***     │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ***  │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ **** │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ***        │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ****           │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ****       │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ****      │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ****        │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Storage  │ ****        │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Hosting  │ ****       │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ ****          │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ ****          │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ ****       │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ ****      │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │****       │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Api      │ ****        │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****           │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****      │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****  │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****     │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****    │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****  │ No Change │ awscloudformation │
├──────────┼──────────────────────┼───────────┼───────────────────┤
│ Function │ ****              │ No Change │ awscloudformation │
└──────────┴──────────────────────┴───────────┴───────────────────┘

No changes detected

? Do you still want to publish the frontend? Yes
Publish started for amplifyhosting

> ***@0.1.0 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Compiled successfully.

File sizes after gzip:

  482.63 kB  build\static\js\main.***.js
  131.4 kB   build\static\css\main.***.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

√ Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
🛑 Inaccessible host: `amplify.us-east-1.amazonaws.com' at port `443'. This service may not be available in the `us-east-1' region.

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: *can provide if needed*

✅ Report saved: ***/report-1704722097128.zip

√ Done

Project Identifier: c6c0d0e9f3270b1a1a4c378371fcba86

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @779503982, thank you for reaching out. These types of issues indicate a problem at the network level. Are you currently operating behind a corporate proxy, on vpn, or have an anti-virus/anti-malware program that may be running?
similar issues: https://github.com/aws-amplify/amplify-cli/issues/12155#issuecomment-1453483173, https://github.com/aws-amplify/amplify-cli/issues/11190

**Comment by 779503982** [comment]
Hi @ykethan, thanks for your response! I don't have VPN installed on my laptop. Below is a screenshot of my "Virus & threat protection" in windows settings. It's an ASUS rog zephyrus laptop. I don't know which anti-virus/malware software is running. I will try to stop the software and try again. 
![image](https://github.com/aws-amplify/amplify-cli/assets/8560915/d32333e5-aab1-4992-9866-6a1547a1ec33)

**Comment by 779503982** [comment]
Ugh, just turned off the windows security protection like below, however it doesn't resolve the error.
![image](https://github.com/aws-amplify/amplify-cli/assets/8560915/d0b07feb-4820-4552-97c8-53ee2f87ee14)

Thanks,
MC

**Comment by 779503982** [comment]
I just tried to publish again with the wifi connected to my phone's hotspot, but it still doesn't work.

**Comment by 779503982** [comment]
Thank you very much. I don't have another PC at hand right now. 
This only occurs when running ```amplify publish```, ```amplify push``` has been working just fine.
In the new empty directory, ```amplify init``` throws the same error: _Inaccessible host: amplify.us-east-1.amazonaws.com at port 443. This service may not be available in the `us-east-1' region._

**Comment by 779503982** [comment]
Guess what, the first thing they say we should do if anything goes wrong -- to restart the computer, worked! I restarted it with  update, and ran `amplify publish` three times in a row, with and without virus protection. All of them worked. What do you think could've gone wrong, though I will definitely restart my computer next time the same error shows up?

**Comment by ykethan** [comment]
@779503982 interesting, if the restart worked. It may be an app was previously the deployment or the anti-virus/malware software might have needed a restart for the changes to take effect.

**Comment by 779503982** [comment]
Thank you very much!!
