### ISSUE TITLE
Corrupted remote qraphql schema. Post syntax checks, before schema upload during amplify push.

### ISSUE THREAD

**Issue by BlackBoxEngineering** [aws-amplify/amplify-cli#13528]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Windows / Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes yet

### Describe the bug

Amplify did not repeat its syntax checks immediately before uploading schema.
There was an opportunity to corrupt the schema between syntax checks and file upload.

### Expected behavior

I would expect a force or override command.

### Reproduction steps

1.) Edited an existing schema correctly
2.) Run "Amplify Push".
3.) During the process put a single character on a line at the top of the file.
4.) Allow the process to complete.
5.) Use amplify push or pull to see error.

### Project Identifier

e325a54048adef53f5a5bb7f0ba27994

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Error using amplify pull or push : Unexpected Name "y".
"y" was the typo on the first line of the schema

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @BlackBoxEngineering , thank you for reaching. From the provided steps, the issue appears to be similar to a [issue](https://github.com/aws-amplify/amplify-category-api/issues/88) open on the API repository, which is currently marked as bug. Please refer to the [comment](https://github.com/aws-amplify/amplify-category-api/issues/88#issuecomment-1129352642) providing a workaround.

Closing the issue as duplicate.
