### ISSUE TITLE
How to split Amplify project into multiple stacks. Error - Limit on the number of resources in a single stack operation exceeded

### ISSUE THREAD

**Issue by BBopanna** [aws-amplify/amplify-cli#13536]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

NO

### Describe the bug

We are getting this error on an amplify project - "Limit on the number of resources in a single stack operation exceeded".

Question is simple - How to split Amplify project into multiple stacks. Are there any documentation with references/examples ?

### Expected behavior

References/Documentation on - "How to split Amplify project into multiple stacks"

### Reproduction steps

Create an amplify project with AppSync GraphyQL API with 50+ entities and add around 6+ custom resource which build around 30 custom resolvers and try to amplify push to get the error - "Limit on the number of resources in a single stack operation exceeded"

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @BBopanna, thank you for reaching out. Currently, GraphQL API does provides support for splitting resolvers into custom named stack; [documentation](https://docs.amplify.aws/react/build-a-backend/graphqlapi/modify-amplify-generated-resources/#place-appsync-resolvers-in-custom-named-stacks).

**Comment by BBopanna** [comment]
Thankyou - problem seems to be around large number of custom resources added in amplify cdk - https://docs.amplify.aws/react/build-a-backend/graphqlapi/modify-amplify-generated-resources/#place-appsync-resolvers-in-custom-named-stacks 

Is there a way to break custom resources added via amplify cdk into multiple stacks ?

**Comment by ykethan** [comment]
@BBopanna , it is currently not supported to split the custom resource. From the number of resources provided on custom, the issue may be due to the number of resolvers on the GraphQL API.

**Comment by BBopanna** [comment]
Is there a way to create a new stack in the cdk part of amplify ?

This documentation talks about it when working entirely using cdk - https://docs.aws.amazon.com/cdk/v2/guide/stack_how_to_create_multiple_stacks.html

Is this possible in cdk part of amplify ?

**Comment by ykethan** [comment]
@BBopanna tried creating nested and creating a dependOn with a new stack but i have not been able to split the resource.

Examples tried:

```
const nst = new NestedStack(this, "nstsk", {});
this.node.addDependency(nst);

class NestedStack extends cdk.NestedStack {
  constructor(scope: Construct, id: string, props?: cdk.NestedStackProps) {
    super(scope, id, props);

    // Define resources for the nested stack here
    new cdk.aws_s3.Bucket(this, "MyBucket");
  }
}
```
push ran into `TemplateURL must be a supported URL.`

also tried 
```
this.node.addDependency(cdkStack1);

export class cdkStack1 extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    props?: cdk.StackProps,
    amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps
  ) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, "env", {
      type: "String",
      description: "Current Amplify CLI env name",
    });

    const amplifyProjectInfo = AmplifyHelpers.getProjectInfo();
    const sqsQueueResourceNamePrefix = `sqs-queue-stack1test`;
    const queue = new sqs.Queue(this, "sqs-queue-stack1", {
      queueName: `${sqsQueueResourceNamePrefix}-${cdk.Fn.ref("env")}`,
    });
  }
}
```

If the use case requires creating custom resources, I would suggest [Amplify Gen 2](https://docs.amplify.aws/gen2/) or using pure cdk with Amplify GraphQL API [construct](https://constructs.dev/packages/@aws-amplify/graphql-api-construct/v/1.5.3?lang=typescript) as an workaround.

**Comment by BBopanna** [comment]
Thankyou @ykethan for trying it out and sharing few more valuable resources - We are on Amplify Gen 1 - what are the possible ways we could go about now that you have mentioned that attempting to add new stack in amplify cdk is not working out ? Please advise.

**Comment by ykethan** [comment]
@BBopanna the workaround would be to limit the resources on `amplify push`, by removing some of the resources and push; then add them back in and push. 
From then number of resources provided the push is likely failing on the 50+ GraphQL models as the custom resources are only 6. you could try consolidating the models or temporarily remove some models and push. 
additionally, you could try creating a pure [cdk](https://aws.amazon.com/cdk/) app to create the custom resources.

**Comment by BBopanna** [comment]
Thankyou @ykethan, in light of the above road block and intent to break our app into smaller apps/services some questions 

1. Can we have same Cognito for 2 different Amplify envs - with the intent of breaking the app into two amplify apps ?

2. Can we migrate Amplify from Gen1 to Gen2? Please let us know any known limitations of services in Gen2.

3. How to eject amplify project to CDK project? Current documentation is too trivial on the same - https://docs.amplify.aws/javascript/tools/cli/usage/export-to-cdk/ it really does not export everything, lot of refactoring!

4. Can we export the DynamoDB table records of one amplify env and import those records to another amplify env - Production backup and restore? And Can we do the same for Cognito too - back up user credentials and restore ? OR can we link the same Cognito to the new env?

**Comment by BBopanna** [comment]
Thankyou @ykethan .

Why does commenting the resources in custom resources and pushing and the uncommenting and pushing working if we have truly hit a "Limit" problem. Limit should be a limit irrespective of commenting and uncommenting - What is truly happening here ?

**Comment by ykethan** [comment]
@BBopanna 
Commenting and un-commenting model definitions in your GraphQL schema toggle creation/deletion of underlying resources such as DynamoDB tables and AppSync resolvers for each of the operations. In some cases, auth resolvers are reused to reduce the amount of resources deployed, however this is not necessarily the case with the remaining pipeline resolvers and can inflate the stacks resources beyond the supported limit.

At this time, CloudFormation has a hard limitation of 2500 resources per nested stack and 500 resources per individual stack. Amplify created stacks are all under one root, nested stack is not fully adjustable at this time.
Complex GraphQL schema could be simplified to reduce the number of GraphQL resources in use e.g rewriting the schema to have less models. Using escape hatches like overrides and export may help to scale the application beyond the CLI generated architecture. 

You may be able to explore AWS CDK/Amplify Gen 2 (currently in public preview) which allows for a more IaC design that permits more freedom. However, these resources are all still under one nested stack, too but we can create new stacks as needed to mitigate this.

**Comment by BBopanna** [comment]
thankyou @ykethan

**Comment by ykethan** [comment]
Closing the issue, feel free in reaching out to us again if you require any further assistance.

**Comment by MarlonJD** [comment]
I was getting same error, I have 63 models, 10 functions. I add some models to custom stacks with https://docs.amplify.aws/gen1/flutter/build-a-backend/graphqlapi/modify-amplify-generated-resources/#place-appsync-resolvers-in-custom-named-stacks. and pushed with `amplify push --minify`. Gen 1 is works perfect now.

But I couldn't found solution on Gen 2
