### ISSUE TITLE
Custom resource can not reference files during deployment

### ISSUE THREAD

**Issue by Dennis-Dekker** [aws-amplify/amplify-cli#13545]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.16.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Not relevant changes for this issue

### Describe the bug

After following [this AWS guide](https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/) on how to connect graphql through AWS Appsync with AWS DynamoDB, I ran into an issue with deploying the custom resource to AWS Amplify. 

The goal is to create a new query in the schema.grapqhl file of the amplify backend/api folder, then to add a JS resolver that will fetch some data from DDB. While the general workflow did work, loading the JS resolver from a file does not.

Creating the custom resource worked fine, however, when I tried to add a JS resolver to my custom query the build errored on finding a file during the deployment:

```
🛑 The following resources failed to deploy:
Resource Name: APIJsResolver13C5C4E9 (AWS::AppSync::Resolver)
Event Type: create
Reason: Resource handler returned message: "Error occurr
ed during operation 'Error reading CodeS3Location from S
3. Error message: The specified bucket does not exist (S
ervice: S3, Status Code: 404, Request ID: 772EK6TY7DN4VG
DH, Extended Request ID: QRGdqUIXJfkx/vjbPcOwsx01gaCmeLj
K5caYgQ4ErOlfTus/nKTnOx0bTr8gL2iusFBCvZzvkXY=)'." (Reque
stToken: 1cef193e-2404-4ad2-0f55-4eb6d33dd796, HandlerErrorCode: GeneralServiceException)
```

The js file is located in the custom resource folder, and I have verified that it was added to the build folder created during the deployment (in the local build folder). Folder structure:

amplify:
&nbsp;&nbsp;backend:
&nbsp;&nbsp;&nbsp;&nbsp;custom:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jsResolvers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;build
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolvers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;testJsResolver.js:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cdk-stack.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jsResolvers-cloudformation-template.json
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolvers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;testJsResolver.js:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.npmrc (not changed)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cdk-stack.ts (see code below under "Additional information")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;package.json (not changed)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tsconfig.json (only added `"allowJs": true` )

The build only fails if I add the code with the Code.fromAsset function rom aws-cdk-lib/aws-appsync, it works if I use the Code.fromInLine function.

### Expected behavior

CDK should resolve the file reference.

### Reproduction steps

1. Create project
2. Add item model to schema
3. Add test query to schema
4. Use `amplify add custom` to create cdk resource
5. Copy paste cdk-stack code (see "Additional information" for code).
6. Add "allowJs": true to tsconfig.json
7. amplify push

### Project Identifier

e146314c59d34bb77745c891be2e93d1

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

```
// @ts-nocheck

import * as cdk from "aws-cdk-lib";
import * as AmplifyHelpers from "@aws-amplify/cli-extensibility-helper";
import { AmplifyDependentResourcesAttributes } from "../../types/amplify-dependent-resources-ref";
import { Construct } from "constructs";
import { dependencies } from "webpack";
import { Code, FunctionRuntime } from "aws-cdk-lib/aws-appsync";
import * as path from "path";

export class cdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps, amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, "env", {
      type: "String",
      description: "Current Amplify CLI env name",
    });

    const amplifyProjectInfo = AmplifyHelpers.getProjectInfo();

    const dependencies: AmplifyDependentResourcesAttributes =
      AmplifyHelpers.addResourceDependency(
        this,
        amplifyResourceProps.category,
        amplifyResourceProps.resourceName,
        [
          {
            category: "api",
            resourceName: "REDACTED",
          },
        ],
      );
    const apiId = cdk.Fn.ref(
      dependencies.api.beam3.GraphQLAPIIdOutput,
    );

    const api = cdk.aws_appsync.GraphqlApi.fromGraphqlApiAttributes(
      this,
      "API",
      {
        graphqlApiId: apiId,
      },
    );

    const dynamoDataSource = api.addDynamoDbDataSource(
      "dynamo-item-datasource",
      cdk.aws_dynamodb.Table.fromTableName(this, "tableTest", `Item-${apiId}-${amplifyProjectInfo.envName}`),
    );

    const resolverCode = `import { util } from "@aws-appsync/utils";

    export function request(ctx) {
      return {
        operation: "GetItem",
        key: util.dynamodb.toMapValues({ id: ctx.args.id }),
      };
    }

    export function response(ctx) {
      return {
        body: ctx.result,
        text: "Hello from JS resolver"
      };
    }`;

    const resolverPath = path.join(__dirname, "resolvers", "testJsResolver.js"); // This is the path to the resolver file

    const resolverCodeAsset = Code.fromAsset(resolverPath, resolverPath); // This is the code asset, which does not give error, only when used in the resolver below

    // const resolver = dynamoDataSource.createResolver("JsResolver", {
    //   typeName: "Query",
    //   fieldName: "getItem",
    //   runtime: new cdk.aws_appsync.FunctionRuntime(
    //     cdk.aws_appsync.FunctionRuntimeFamily.JS,
    //     cdk.aws_appsync.FunctionRuntime.JS_1_0_0.version,
    //   ),
    //   code: Code.fromInline(resolverCode) // This works!!!
    // });

    const resolver = dynamoDataSource.createResolver("JsResolver", {
      typeName: "Query",
      fieldName: "getItem",
      runtime: new cdk.aws_appsync.FunctionRuntime(
        cdk.aws_appsync.FunctionRuntimeFamily.JS,
        cdk.aws_appsync.FunctionRuntime.JS_1_0_0.version,
      ),
      code: Code.fromAsset(resolverPath, resolverPath), // This does not work!!!
    });
  }
}
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Dennis-Dekker, thank you for reaching out. Assets are currently not supported in Amplify custom category, please refer to a similar issue https://github.com/aws-amplify/amplify-cli/issues/9055 where the behavior is currently being tracked.
As a workaround the code will need to be added as inline. 
Closing the issue as duplicate.
