### ISSUE TITLE
Amplify Configure Wizard Failed

### ISSUE THREAD

**Issue by tchowdhury** [aws-amplify/amplify-cli#13556]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.11.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Windows 10 Pro

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I'm following the step outline in https://docs.amplify.aws/javascript/start/getting-started/installation/ to configure amplify using amplify-configure wizard. Follow the steps exactly and at the end getting an error "EPERM: operation not permitted, open 'C:\Users\TAPAJOYTI\.aws\credentials'" .. attached the error screenshot
![amplify_configure_error](https://github.com/aws-amplify/amplify-cli/assets/12083913/07520b91-2f73-40aa-b7ce-7a84eb5f66f8)

### Expected behavior

As par documentation the configuration is successful "Successfully set up the new user"

### Reproduction steps

run the command amply configure number of times and it shows the same error everytime

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @tchowdhury, Thanks for reaching out. Does this error also occur if you run the terminal with Admin access?

**Comment by tchowdhury** [comment]
Yes, I've open the terminal with run as admin option, still the same issue. Is there anyway I can manually add profile in the configuration file under .aws folder? If yes , is there any sample available so hat I can set up manually or alternatively, can I use my default aws profile (which has admin rights) to continue with amplify?

**Comment by ykethan** [comment]
Hey @tchowdhury, could try setting the profile using AWS CLI `aws configure` or manually adding them. https://docs.aws.amazon.com/cli/latest/userguide/welcome-examples.html
You should be to able to use the profile with admin permissions on `amplify init` but to follow best practises I would suggest using a profile with scoped down permissions.

**Comment by josefaidt** [comment]
Hey @tchowdhury did @ykethan 's note help resolve your issue?

**Comment by tchowdhury** [comment]
No, it doesn't. Anyhow I'm using my AWS admin profile. Quite disappointed , with the amplify documentation, steps/screenshots documented doesn't work and no alternatives have been documented either.

**Comment by josefaidt** [comment]
Hey @tchowdhury sorry to hear of the rough experience. Looking at the error again this, was node or the CLI installed with sudo/admin? If you run `which amplify` or `npm bin -g` what is the output? We've seen similar errors where the CLI is unable to write to a logfile in the `$HOME` directory

**Comment by ykethan** [comment]
Hey @tchowdhury, are you still experience this issue?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require any assistance.
