### ISSUE TITLE
DynamoDB deletion protection on production environment

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws-amplify/amplify-cli#13551]
### Amplify CLI Version

12.6.0

### Question

As deletion protection feature is available for DynamoDB.
announcement: https://aws.amazon.com/jp/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/
I'm wondering if it's possible to set this flag only to tables in the production environment.
Is it something we can do with `override.ts` ?

**Comment by ykethan** [comment]
Hey @ggorge-etiqa, thank you for reaching out. Could you clarify if the DynamoDB table was created on the storage category or the API category?

for example on a DynamoDB table created on storage category, we should be able to use overrides to enable deletion protection.

example:

```
import {
  AmplifyDDBResourceTemplate,
  AmplifyProjectInfo,
} from "@aws-amplify/cli-extensibility-helper";

export function override(
  resources: AmplifyDDBResourceTemplate,
  amplifyProjectInfo: AmplifyProjectInfo
) {
    if(amplifyProjectInfo.envName === "dev") {
  resources.dynamoDBTable.deletionProtectionEnabled = true;
    }
}

```

**Comment by ggorge-etiqa** [comment]
Hi @ykethan I think it's in the API category. The DynamoDB tables I want to protect from deletion are created by AppSync.

**Comment by ykethan** [comment]
@ggorge-etiqa thank you for the clarification. Please refer to this override example : https://github.com/aws-amplify/amplify-cli/issues/13465#issuecomment-1847511407

```
resources.models[<model>].modelDDBTable.deletionProtectionEnabled = true;
```

**Comment by ggorge-etiqa** [comment]
thanks @ykethan 

```
    if (amplifyProjectInfo.envName === "prod") {

        for (const model in resources.models) {      
            resources.models[model].modelDDBTable.deletionProtectionEnabled = true;
            console.log(resources.models[model].modelDDBTable); //ensure property is set
        }

    }
```

**Comment by ykethan** [comment]
@ggorge-etiqa noticed the issue was re-opened. Is there anything else i can assist on this?
