### ISSUE TITLE
"amplify add notifications" is not showing me the "APNS" item

### ISSUE THREAD

**Issue by atkreis** [aws-amplify/amplify-cli#13559]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.2.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Describe the bug

I am running "amplify add notifications" and the list given me is this:

% amplify add notifications
? Choose the notification channel to enable …  (Use arrow keys or type to filter)
❯ FCM  | » Firebase Push Notifications 
  In-App Messaging
  Email
  SMS

I need the APNs item.

Now, I did setup amplify push notifications in a development branch earlier, and APNs was listed and I was able to setup push notifications to my react native iOS app and it worked.  I then switched back to my main branch and wanted to merge the changes into this one, repeating some of the steps like "amplify add notifications".  But I cannot select APNS because it is not listed.

Any suggestions on how to get amplify to give me that option?  Reset something or clear a cache?  I've tried flushing npm cache, rm -rf node_modules, and a few other usual things.

Thanks,
Alex

### Expected behavior

APNS is one of the listed items when setting it up.

### Reproduction steps

See above.

### Project Identifier

c09af5259c6aae63cf8a3fc2829bd105

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @atkreis, thank you for reaching. Does the `Notifications` category appear in the matrix when running `amplify status`?
If not, could you run `amplify env checkout <current-env-name>`, then run `amplify status`?

**Comment by atkreis** [comment]
Hi @ykethan, "amplify status" shows Notifications listed:

```
% amplify status

    Current Environment: staging
    
┌───────────────┬───────────────┬───────────┬───────────────────┐
│ Category      │ Resource name │ Operation │ Provider plugin   │
├───────────────┼───────────────┼───────────┼───────────────────┤
│ Api           │ DEVHavda      │ No Change │ awscloudformation │
├───────────────┼───────────────┼───────────┼───────────────────┤
│ Auth          │ DEVHavda      │ No Change │ awscloudformation │
├───────────────┼───────────────┼───────────┼───────────────────┤
│ Analytics     │ devhavda      │ No Change │ awscloudformation │
├───────────────┼───────────────┼───────────┼───────────────────┤
│ Notifications │ devhavda      │ No Change │                   │
└───────────────┴───────────────┴───────────┴───────────────────┘
```

And `amplify add notifications` still shows me only the 4 items as before:

```
% amplify add notifications
? Choose the notification channel to enable …  (Use arrow keys or type to filter)
❯ FCM  | » Firebase Push Notifications 
  In-App Messaging
  Email
  SMS
```

I know Notifications is already configured (and seems to work), but what if I want to reconfigure or update the configuration?  Should I not be able to re-run the "add" command?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
