### ISSUE TITLE
app deploy fails with "lambda execution role already exists", while in reality it doesn't

### ISSUE THREAD

**Issue by alonsnir** [aws-amplify/amplify-cli#13567]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.9.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Ubintu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

```
🛑 The following resources failed to deploy:
Resource Name: LambdaExecutionRole (AWS::IAM::Role)
Event Type: create
Reason: aruggaLambdaRole5704a3e1-test already exists in stack arn:aws:cloudformation:eu-central-1:XXXXXXXXXX:stack/amplify-arugga-test-171255-functionpullRobotData-1SKXRCFA8NLLG/c8ebb100-80a6-11ee-8c1a-0655dace11f9


Resource Name: LambdaExecutionRole (AWS::IAM::Role)
Event Type: create
Reason: aruggaLambdaRolebc581e6a-test already exists in stack arn:aws:cloudformation:eu-central-1:XXXXXXXXXX:stack/amplify-arugga-test-171255-functionpushRobotData-2ETMI3BIHC18/c8ec2630-80a6-11ee-9d61-063ab5e351c9


🛑 Resource is not in the state stackUpdateComplete
Name: LambdaExecutionRole (AWS::IAM::Role), Event Type: create, Reason: aruggaLambdaRole5704a3e1-test already exists in stack arn:aws:cloudformation:eu-central-1:XXXXXXXXXX:stack/amplify-arugga-test-171255-functionpullRobotData-1SKXRCFA8NLLG/c8ebb100-80a6-11ee-8c1a-0655dace11f9, IsCustomResource: false

Name: LambdaExecutionRole (AWS::IAM::Role), Event Type: create, Reason: aruggaLambdaRolebc581e6a-test already exists in stack arn:aws:cloudformation:eu-central-1:XXXXXXXXXX:stack/amplify-arugga-test-171255-functionpushRobotData-2ETMI3BIHC18/c8ec2630-80a6-11ee-9d61-063ab5e351c9, IsCustomResource: false
```

already exists? let me check:
```
~$ aws iam list-roles --query 'Roles[?RoleName==`aruggaLambdaRole5704a3e1-test `].RoleName'
[]
```
an empty list returned.
Same if i search for that role in the Console - there is no such a role exists

### Expected behavior

provide correct information

### Reproduction steps

init an application, add lambda function, push

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @alonsnir :wave: thanks for raising this! Does the output of the AWS CLI command change without the trailing space on the role name?

```diff
- aws iam list-roles --query 'Roles[?RoleName==`aruggaLambdaRole5704a3e1-test `].RoleName'
+ aws iam list-roles --query 'Roles[?RoleName==`aruggaLambdaRole5704a3e1-test`].RoleName'
```

As a few follow-up questions:

- are you re-using the name of a previously-deployed Function?
- did a previous deployment that attempted to create the same Function fail?

**Comment by alonsnir** [comment]
hey @josefaidt
removing trailing space makes no difference - same output, an empty list.

- are you re-using the name of a previously-deployed Function?
yes, the application, with its functions has been previously deployed in that same region and with the same backend environment name.

- did a previous deployment that attempted to create the same Function fail?
no, it has deployed it properly. Actually, I created another backend environment and it deployed successfully.

It looks like there are some leftovers after environment deletion which prevents re-deployment with the same name

**Comment by josefaidt** [comment]
Hey @alonsnir can you try removing the orphaned role and re-attempt deployment?

**Comment by alonsnir** [comment]
Hi @josefaidt 
I cannot, since it's not found anywhere, not in the console and not via the aws cli

**Comment by josefaidt** [comment]
Hey @alonsnir ah yes, that's right. Would you mind sharing the project ID output from `amplify diagnose --send-report`? I want to take a look through the CFN templates and see if there are multiple resources. 

Additionally, do you see multiple stack events for this execution role in the AWS CloudFormation console, or multiple references to these two roles? Lastly, can you try removing and re-adding the affected Functions?

**Comment by alonsnir** [comment]
Hi @josefaidt 
Project Identifier:  128eaa85e5463eec4ba5be02178d354f

What are slack events in this context? Where do I see them in the CF console?

I have removed and then re-added the functions but same result:
```
The following resources failed to deploy:
Resource Name: LambdaFunction (AWS::Lambda::Function)
Event Type: create
Reason: pullRobotData-test already exists in stack arn:aws:cloudformation:eu-central-1:xxxxxxxxxxxx:stack/amplify-arugga-test-171255-functionpullRobotData-1SKXRCFA8NLLG/c8ebb100-80a6-11ee-8c1a-0655dace11f9
```

**Comment by josefaidt** [comment]
Hey @alonsnir there's an "Events" tab when you select a CloudFormation stack 
<img width="1049" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/5033303/85bbc3d8-970a-4217-9573-02eb87eb7179">

**Comment by alonsnir** [comment]
@josefaidt so I have found the leftover resources and after manual deletion all back to normal.
Thanks

**Comment by Ponjimon** [comment]
@alonsnir Sorry for adding a comment this late but do you happen to remember *where* exactly you have found the leftover resources? One of our devs is currently facing the same issue.
