### ISSUE TITLE
Amplify's auto-generated auth functions using deprecated version of Node.js (nodejs16.x)

### ISSUE THREAD

**Issue by chrislrobert** [aws-amplify/amplify-cli#13565]
### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v18.16.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

The auth support auth-generates four Lambda functions like the following:

1. amplify-login-custom-message-e832f3ae
2. amplify-login-create-auth-challenge-e832f3ae
3. amplify-login-define-auth-challenge-e832f3ae
4. amplify-login-verify-auth-challenge-e832f3ae

All four are created with a nodejs16.x engine, but that engine is past end of life and will be deprecated for support purposes this coming June. I've updated my CLI to 12.10.1, tried updating the auto and re-pushing, tried force-pushing, etc., but always nodejs16.x is used.

### Expected behavior

Expect:

1. New deployments use a newer version of Node.js to start
2. Existing deployments have a clear upgrade path

### Reproduction steps

1. Add auth to project
2. Push
3. Run `aws lambda list-functions --region us-east-1 --output text --query "Functions[?Runtime=='nodejs16.x'].FunctionArn"` to observe that the four auto-created functions are running on the EOL nodejs16.x.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @chrislrobert :wave: thanks for raising this! Later versions of the CLI like the version you are using will update the auto-generated Lambda's used to supplement the CloudFormation configuration for your Auth resources.

Runtime versions can be found in the auth trigger CloudFormation template inside your auth resource's `build/` directory. Can you try running `amplify update auth`, stepping through the prompts making no modifications, and see if this upgrades the runtime?

**Comment by chrislrobert** [comment]
> Hey @chrislrobert 👋 thanks for raising this! Later versions of the CLI like the version you are using will update the auto-generated Lambda's used to supplement the CloudFormation configuration for your Auth resources.
> 
> Runtime versions can be found in the auth trigger CloudFormation template inside your auth resource's `build/` directory. Can you try running `amplify update auth`, stepping through the prompts making no modifications, and see if this upgrades the runtime?

Thanks, @josefaidt, for the reply. Looking in the auth build folder, I can see that the templates in there do properly have `nodejs18.x`. And, if I list nodejs18 functions with `aws lambda list-functions --region us-east-1 --output text --query "Functions[?Runtime=='nodejs18.x'].FunctionArn"`, I can see that all of the functions labeled with my app+branch are v18. However, there are still these lingering nodejs16 functions triggering the warnings from AWS:

1. amplify-login-custom-message-e832f3ae
2. amplify-login-create-auth-challenge-e832f3ae
3. amplify-login-define-auth-challenge-e832f3ae
4. amplify-login-verify-auth-challenge-e832f3ae

Maybe those aren't actually connected to this specific app? Indeed, if I search the app's repo, there are no references. But I only have the one app, so if it's not linked to that app, where did they come from — and do you think it's safe to just go into Lambda and delete them?

**Comment by chrislrobert** [comment]
@josefaidt, I've done some Googling and have confirmed that these four functions aren't unique to me. They appear to be related to the admin UI, and there is a comment in https://github.com/aws-amplify/amplify-studio/issues/23 suggesting that there is no CloudFormation stack for those functions. Also, I see somebody has reported this very issue in https://github.com/aws-amplify/amplify-studio/issues/1085, so I'll add a comment there. Is that the better place to chase this down?

**Comment by ykethan** [comment]
@chrislrobert the lambda functions specified are related amplify studio, login flow. I see you already did add a comment on the issue. Will close this issue and followup on https://github.com/aws-amplify/amplify-studio/issues/1085 with the team.
