### ISSUE TITLE
CloudFormation did not receive a response from your Custom Resource [UserPoolClientInputs].

### ISSUE THREAD

**Issue by musukwamoshi** [aws-amplify/amplify-cli#13581]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.0

### Amplify CLI Version

v12.10.1

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Updated the runtime version of [UserPoolClientLambda] in cloudformation-temlate.yml to v18 in the backend/auth folder.  [UserPoolClientLambda] resource wouldn't create until the runtime update. But now [UserPoolClientInputs] fails

### Describe the bug

Logical ID: [UserPoolClientInputs]
Type: Custom::LambdaCallout

Creating of the above resource fails when cloning an existing env on aws using amplify

### Expected behavior

The resources get created successfully

### Reproduction steps

1.amplify pull --appId projectiedntifier --envName <insert name of env to clone>
2.amplify env add <insert name of cloned environment>
3.Updated the runtime version of [UserPoolClientLambda] in cloudformation-temlate.yml to v18 in the backend/auth folder
4.amplify push

Note, creation of [UserPoolClientLambda] fails without step 3

### Project Identifier

a654c50d1347b00bb26cfc532f1f832a

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

CloudFormation did not receive a response from your Custom Resource.  If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @musukwamoshi, Thank you for reaching out. From the information provided noticed the project utilizes a un-migrated auth resource. We can migrate the auth resource by running `amplify update auth` which should prompt to migrate by selecting `yes`.
The issue occurs on the Lambda function(UserPoolClientInputs) tied to Node.js 18 runtime which utilizes AWS SDK for javascript v3. Please refer to https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/ providing additional information on this change.
