### ISSUE TITLE
[hostedUIProviderCreds] do not exist in the template

### ISSUE THREAD

**Issue by R70YNS** [aws-amplify/amplify-cli#13587]
### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Unable to push latest changes to Amplify environment due to bug, 'Reason: [hostedUIProviderCreds] do not exist in the template. 

`~/.aws/amplify/deployment-secrets.json` contains the following for the environment: 

```
{
  "appSecrets": [
    {
      "rootStackId": "ROOT_STACK_ID",
      "environments": {
        "ENV_NAME": {
          "ENV": {
            "COGNITO_USER_POOL": {
              "hostedUIProviderCreds": "[]"
            }
          }
        }
      }
    }
}
```

But I still receive the issue when trying to push latest changes. 

Re-adding: 

```
{
    "hostedUIProviderCreds: "[]"
}
```
within `team-provider-info.json` auth field regenerates `deployment-secrets.json` but still fails to push with the above error remaining. 

Deleting the amplify directory, re-pulling and attempting to push new changes still results in the error. 

This issue has been reported in previous Github issues and still occurs in latest CLI.

- https://github.com/aws-amplify/amplify-cli/issues/6563
- https://github.com/aws-amplify/amplify-cli/issues/5942

### Expected behavior

Specifying `hostedUIProviderCreds` within  `deployment-secrets.json` should enable user to push changes to environment.

Pulling an environment should created default variable when unable to access environment variables related to identify providers. 

### Reproduction steps

Unsure, but most likely related to external authentication provider. 

- Add external authentication provider
- Pull/update amplify project 
- Remove authentication provider in AWS console
- Re-pull/update Amplify project
- Attempt to push changes

### Log output

<details>

```
# Put your logs below this line

🛑 The following resources failed to deploy:
Resource Name: XYZ (AWS::CloudFormation::Stack)
Event Type: update
Reason: Parameters: [hostedUIProviderCreds] do not exist in the template

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @R70YNS, thank you for reaching out. could you try running `amplify update auth`, select `Update OAuth social providers`, re-enter the credentials and run `amplify push`. This should update the `~/.aws/amplify/deployment-secrets.json` file

**Comment by R70YNS** [comment]
Hi @ykethan 

I've tried the above:

 ```
amplify update auth
Update OAuth social providers
(Purposely didn't select any) and pressed enter
amplify push 
```

This still results in being unable to push any updates, even with the updated `deployment-secrets.json` file

**Comment by R70YNS** [comment]
To confirm, it gave the same error message: 

```
🛑 The following resources failed to deploy:
Resource Name: authxyz (AWS::CloudFormation::Stack)
Event Type: update
Reason: Parameters: [hostedUIProviderCreds] do not exist in the template
```

Tested on both Mac & Linux

**Comment by R70YNS** [comment]
Another issue related to the above, raised awhile back.

https://github.com/aws-amplify/amplify-cli/issues/3642

Unfortunately the known fix of adding `"hostedUIProviderCreds": "[]"` to `team-provider-info.json` no longer seems to work, instead just prompting to generate `deployment-secrets.json` instead. 

Even though `deployment-secrets.json` contains the field `hostedUIProviderCreds` for the relevant environment it still fails as above.

**Comment by ykethan** [comment]
Hey @R70YNS, could you provide us the project identifier by running `amplify diagnose --send-report`?

> Remove authentication provider in AWS console

noticed this, could provide us some information on how the authentication provider was removed?

**Comment by R70YNS** [comment]
Project Identifier: bb01826d6e9e4d639ab999b6a0e018db

Authentication provider was removed via console via Cognito -> User pool -> Sign-in experience -> Federated Identity provider sign-in. I did notice though that the same thing was done in a different environment and this still works fine. 

In trying to resolve the above, I deleted the local amplify directory and re-pulled via `amplify pull --appId xyz --envName envName` but this still resulted in the same issue.

**Comment by ykethan** [comment]
Hey @R70YNS, could you try the following 

1. run `amplify update auth` -> `Update OAuth social providers`. deselect the providers.
2. remove the deployment secrets from `team-provider-info.json`
3. delete the `~/.aws/amplify/deployment-secrets.json` file
4. then run `amplify push`

**Comment by ykethan** [comment]
@R70YNS thank you for the information. From the project identifier did not observe any reference in the `cli-inputs.json` or `backend-config.json` but noticed a reference in the `root-cloudformation-stack.json`. Do you observe `hostedUIProviderCreds ` in the `amplify-meta.json` under the auth block?

**Comment by R70YNS** [comment]
Hi @ykethan 

I don't have an amplify-meta.json locally, but within the deploymentBucket in S3 there is an `amplify-meta.json` file. It only contains a `awscloudformation` field underneath `providers`. I cannot see a `hostedUIProviderCreds` within the file.

**Comment by R70YNS** [comment]
I've tried regenerating `deployment-secrets.json` aswell as modifying as below: 
{
      "rootStackId": "xxxx-xxxx-xxxx-xxxx",
      "environments": {
        "xxxx": {
          "ENV": {
            "COGNITO_USER_POOL": {
              "hostedUIProviderCreds": "[]"
            }
          },
          "auth": {
            "$RESOURCE_NAME": {
              "hostedUIProviderCreds": "[]"
            }
          }
        }
      }
    }
    
But both still fail with `Event Type: update, Reason: Parameters: [hostedUIProviderCreds] do not exist in the template`

**Comment by ykethan** [comment]
Hey @R70YNS, would be open for a quick call wanted to dive into the project. I am available on discord and my handle is `ykethan`
