### ISSUE TITLE
amplify-meta.json is deleted after 'amplify pull' operation failed though to locked folder on windows.

### ISSUE THREAD

**Issue by Eliav2** [aws-amplify/amplify-cli#13586]
### Amplify CLI Version

.

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

.

### Describe the bug

This platform just have too many bugs and it's completely taking way too much time to understand amplify specific problems rather than just setting frontend+backend+auth+hosting by yourself manually.

this time, amplify throw himself to bad state by deleting importent meta files from the amplify folder (like `amplify-meta.json`) if the operation fails because of 'access denied' to deleting a folder on windows:
```
 /c/Development/galsuchetzky-testinng │ dev +62 ?1 ···················································································· 3s │ galsuchetzky-testinng Py │ 17:37:19 ─╮ 
❯ amplify pull --appId do76opuqgdu5a                                                                                                                                             ─╯ 

Pre-pull status:

    Current Environment: main

┌──────────┬────────────────────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name                          │ Operation │ Provider plugin   │
............
└──────────┴────────────────────────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✖ Fetching updates to backend environment: main from the cloud.
✖ There was an error initializing your environment.
🛑 Could not initialize platform for 'main': EBUSY: resource busy or locked, rmdir 'C:\Development\galsuchetzky-testinng\amplify\backend\function\AppSyncLambdaAPI\src'
```

this file is not even tracked by git so even trying to pull fails:
```
❯ amplify pull --appId do76opuqgdu5a                                                                                                                                             ─╯ 
🛑 No Amplify backend project files detected within this folder.
```

luckily, JetBrains IDEs track local history for files even outside git so i was able to restore the amplify project to 'good' state.

you (the amplify team) should completely focus on stability rather than new features for now, because as a developer I'm completely upset with this platform as is just does not scale as your app grow.

### Expected behavior

.

### Reproduction steps

.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Eliav2, thank you for reaching out. While we dive into this, wanted to get some information. 
1. is the directory where the pull command in a cloud storage folder such as OneDrive?
2. Could you try re-running the command with `--debug` and provide us the output?
3. Additionally, could you verify the permissions on the directory?

**Comment by Eliav2** [comment]
The problem was that the folder was locked though to other process locking down the folder. I'm my case it was a terminal opened in the AppSyncLamndaAPI folder (see in the logs), it has nothing to do with permissions.

The CLI should not delete important meta files that are not tracked by git, and a graceful exit should restore the previous state if any critical operation was failed

**Comment by ykethan** [comment]
@Eliav2 from the information provided this appears to be a due to the `amplify-backup` that is extracted during a pull and aren't cleaned up during the failed build. similar to https://github.com/aws-amplify/amplify-cli/issues/13588#issuecomment-1942734721.  Removing the `amplify-backup` and `amplify` folder then re-running the pull command should mitigate the issue. 
closing the issue to track https://github.com/aws-amplify/amplify-cli/issues/13588#issuecomment-1942734721
