### ISSUE TITLE
Amplify remove auth produces error 🛑 The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by CloudInnovator** [aws-amplify/amplify-cli#13583]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.8.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Ubuntu 22.04.3 LTS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Amplify remove auth produces error 🛑 The "path" argument must be of type string. Received undefined. Prompt from CLI advised reporting this issue; however, auth resources were still removed

### Expected behavior

Gracefully executes removal of auth resources without prompting error.

### Reproduction steps

1. Manually Configure Auth using ``` amplify add auth ``` 
2. Terminate Process mid-configuration
3. Remove auth using ```amplify remove auth ```

### Project Identifier

Project Identifier: 3b74c96c0e62613566fb77c92fae1612

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @CloudInnovator, thank you for reaching out. wanted to get some additional information on the issue.
could try adding `--debug` when running the command and provide us the output with stack trace.

> Terminate Process mid-configuration
could you let know the step in which the process was terminated.

additionally, could you provide us the project identifier output by running `amplify diagnose --send-report`

**Comment by CloudInnovator** [comment]
Out for  ```amplify remove auth  --debug``` . Looks like auth was removed.  
```
You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

🛑 No resources added for this category

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

ResourceRemoveError: No resources added for this category
    at AmplifyToolkit.removeResource (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/remove-resource.js:35:15)
    at Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/commands/auth/remove.js:20:36)
    at Object.executeAmplifyCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:347:25)
    at /snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:157:47
    at executePluginModuleCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:139:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeCommand (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:37:9)
    at async Object.run (/snapshot/amplify-cli/build/node_modules/@aws-amplify/cli-internal/lib/index.js:121:5)
    ```
    Project identifier ``` Project Identifier: 3b74c96c0e62613566fb77c92fae1612
 ```

**Comment by ykethan** [comment]
Hey @CloudInnovator, thank you for the information. The issue appears to similar to https://github.com/aws-amplify/amplify-cli/issues/12433. The `amplify remove auth` should be removed as expected but does throw an unexpected error. 
Closing this issue in favor of tracking https://github.com/aws-amplify/amplify-cli/issues/12433. If you are experiencing any issues with the add and push when re-adding the auth resource do let us know.
