### ISSUE TITLE
Recover from a deleted imported identity pool

### ISSUE THREAD

**Issue by dan-hook** [aws-amplify/amplify-cli#13588]
### Amplify CLI Version

12.10.1

### Question

My amplify application uses an imported user pool and identity pool.  The identity pool was accidentally deleted, but the user pool is intact, as well as the authRole used by the identity pool.  This allowed me to recreate the identity pool.  Unfortunately, it has a different id so when I try to push the environment I get the error:
✖ There was an error initializing your environment. 🛑 The previously configured Identity Pool: 'genepanelapi8323d4d5_identitypool_8323d4d5__int' (us-east-1:2c54f815-40af-4e81-a1c8-45134d3d9b18) cannot be found.

I can't easily remove and reimport the auth, since my API is dependent on the auth and removing the API would end up being similar in effort to destroying the environment, then recreating it (and importing backups of the DDB tables).

**Comment by dan-hook** [comment]
I filed a support request with AWS, but I think the developers here are much better placed to answer the question than first line support is.  Where is the CLI getting the old value of the identitypool, and is there a way we can change that value through the console or AWS cli that bypasses any issues the amplify CLI may be having?

**Comment by ykethan** [comment]
Hey @dan-hook, On diving into this. I was able to update a imported auth resource that dependant on a project by utilizing the following steps.
1. update the `team-provider-info.json` file, auth block with new user pool and identity pool resource values. 
```
          "userPoolId": "",
          "userPoolName": "",
          "webClientId": "",
          "nativeClientId": "",
          "identityPoolId": "",
          "identityPoolName": "",
          "allowUnauthenticatedIdentities": <false>,
          "authRoleArn": "",
          "authRoleName": "",
          "unauthRoleArn": "",
          "unauthRoleName": ""
```
`<>` with new resources values
2. update the `amplify-meta.json` file , auth block output values to new user pool and identity pool resource values similar to above values.
3. `amplify status` if this does not have an update on any resource, trigger an update by say adding an lambda function which we can remove later
4. `amplify push`
After push completes, verify the `amplifyconfiguration.json` and `amplify-meta.json` has new Cognito resource values.
This should also update api as well, we can confirm this on the AppSync console.
5. if it does not update the API, we will need to trigger an update on the API by adding an empty line or via the `amplify update api`

Do let us know if this mitigates the issue.

**Comment by dan-hook** [comment]
> Do let us know if this mitigates the issue. Recommend testing this in a dev/test environments.

That worked!  Thank you for your help.
