### ISSUE TITLE
[Fixed] Amplify Deployment Error - The following resources failed to deploy - UserPoolClientLambda

### ISSUE THREAD

**Issue by JeetTatva** [aws-amplify/amplify-cli#13598]
Issue Description:

When deploying my Amplify project, I encountered the following error during the backend deployment phase:

`The following resources failed to deploy:
Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400)"`

I initially encountered this error while using Amplify CLI version 12.4.0. Even after upgrading to version 12.10.1, the error persisted. It seems to be related to an auto-generated Lambda function, and unlike user-created Lambda functions, I cannot manually update the runtime.

This issue has started occurring recently; previous deployments were successful. A prompt solution or workaround would be greatly appreciated.

**Comment by Syed-Hasnain-Askari** [comment]
Issue Description:

`
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 2fdb0891-8a62-4fd8-89cc-c5ce20ef4a51)"
`
I'm getting this error on Amplify deploy. I need help with this issue.

**Comment by JeetTatva** [comment]
I was able to solve this issue.
Note: Check if you use latest cli version in your machine, if not I would recommend to use it (As of now the latest version is 12.10.1). Do amplify push and check if it works on your machine. If it works in your machine and fails when deploying then follow the below steps. For some reason, the Amplify uses version 10.x when deploying it

(1) Go to Amplify Console
(2) Select your app
(3) Go to App Settings -> Build Settings
(4) Go to Build Image Settings -> Edit
(5) Update the live package updates for Amplify CLI to use latest version

![image](https://github.com/aws-amplify/amplify-cli/assets/144127130/e63b6ed5-7dc6-4ef6-a680-25137d16b67d)

**Comment by JeetTatva** [comment]
@Syed-Hasnain-Askari please check above comment if it helps

**Comment by VesnaBozic** [comment]
> I was able to solve this issue. Note: Check if you use latest cli version in your machine, if not I would recommend to use it (As of now the latest version is 12.10.1). Do amplify push and check if it works on your machine. If it works in your machine and fails when deploying then follow the below steps. For some reason, the Amplify uses version 10.x when deploying it
> 
> (1) Go to Amplify Console (2) Select your app (3) Go to App Settings -> Build Settings (4) Go to Build Image Settings -> Edit (5) Update the live package updates for Amplify CLI to use latest version
> 
> ![image](https://private-user-images.githubusercontent.com/144127130/307218362-e63b6ed5-7dc6-4ef6-a680-25137d16b67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjI1OTcsIm5iZiI6MTcwODgyMjI5NywicGF0aCI6Ii8xNDQxMjcxMzAvMzA3MjE4MzYyLWU2M2I2ZWQ1LTdkYzYtNGVmNi1hNjgwLTI1MTM3ZDE2YjY3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwMDUxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTUxMTQ1ZTVlMzg1MjUzMzUxZTg3NDE0ZWMyZDBlY2ZhZDQ2NDQzMzAyNjZmZGVjZGQwNWY2Y2M5YmE3MjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xFF63mo6VNNFLDTSQG10Cmr0beva4LF2yYykcKtCRHo)

This helped! I also added.
<img width="596" alt="Screenshot 2024-02-25 at 01 50 52" src="https://github.com/aws-amplify/amplify-cli/assets/61289765/f25aacf0-5c43-45fa-99f8-a2b30dfaec8a">

Thanks!

**Comment by Hasgar11** [comment]
Very big thanks! Was looking for hours to solve the issue and updating the CLI Version fixed it! thanks thanks thanks

**Comment by ykethan** [comment]
Hey, Amplify CLI ties the NodeJs to a specific version, you will need to upgrade the CLI version to update the UserPoolClientLambda created on the auth resource. 
Glad to hear you were able to mitigate the issue, closing this.
