### ISSUE TITLE
amplify push modify backend-config.json removing "parameters"

### ISSUE THREAD

**Issue by gzimbron** [aws-amplify/amplify-cli#13594]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

- I cloned a fully working repository to my new Mac,
- Pulled dev environment with: `amplify pull`
- Pulled test environment.
- All fine up to here.

Trying to re-publish web app manually:
- `amplify env checkout dev`
- `amplify publish -y`
	
At this point amplify modify amplify/backend-config.json removing "parameters".

I tryied to do it in my preview Mac and It works fine.

New mac requires to run `amplify pull` before publish. but we have "prod" environment where we need to deploy dev backend updates.

![CleanShot 2024-02-15 at 11 21 37@2x](https://github.com/aws-amplify/amplify-cli/assets/7065779/834722cc-579b-47fd-87a1-c8f311fc37d3)

### Expected behavior

- `amplify env checkout test`
- `amplify publish -y`
- deploy it to host correctly

### Reproduction steps

- clone app repo
- `amplify pull`
- `amplify pull --appId XXXXXX --envName test`
- `amplify env checkout dev`
- `amplify publish -y`

### Project Identifier

41de347992480064a5878862a835ef5e

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @gzimbron, the issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/13467. Does the repository also track the `team-provider-info.json` file and does it contain the function environment variables similar to https://github.com/aws-amplify/amplify-cli/issues/13467#issuecomment-1874581172?

**Comment by gzimbron** [comment]
Hi @ykethan , repository is ignoring this file.

Btw team-provider-info.json functions doesn't have "deploymentBucketName" and "s3Key"


team-provider-info.json must be tracked by git ?
