### ISSUE TITLE
Amplify Directory Structure

### ISSUE THREAD

**Issue by spesnova** [aws-amplify/amplify-cli#13592]
### Amplify CLI Version

12.10.1

### Question

If there're files like below:

```
amplify/backend/function/<FUNCTION_NAME>/<FUNCTION_NAME>-cloudformation-template.json
amplify/backend/awscloudformation/build/function/<FUNCTION_NAME>/<FUNCTION_NAME>-cloudformation-template.json
```

Can I consider they're duplicated ? And should I delete either file?

This question is basically about directory structure. What's the difference between `amplify/backend/function/` and `amplify/backend/awscloudformation/build/function/?` I have tried to find the answer in official docs and this repo but can't find it.

There's [a page about Files and Folders](https://docs.amplify.aws/javascript/tools/cli/reference/files/) in official doc. It says you can edit files under [`amplify/backend`](https://docs.amplify.aws/javascript/tools/cli/reference/files/#amplifybackend).  I'd like to know more details under `amplify/backend` folder.

If possible, I also want to know not only about under `amplify/backend` folder but also whole amplify project's directory structure details. This could save both maintainers' and users' time.

**Comment by ykethan** [comment]
Hey @spesnova, thank you for reaching out. Amplify manages resources under `amplify/backend/<resource-name>/` directory structure. Where for example: `amplify/backend/function/<FUNCTION_NAME>/` contains your function code and CloudFormation templates that are generated and deployed by Amplify, which is your current working directory.
The `amplify/backend/awscloudformation/build/function/` is a local build of the function CloudFormation template on a push/build ensures there aren't any inconsistencies that may cause deployment failures.
I would not recommend deleting them manually to prevent any push failures. To note, while it's safe to edit the function's CloudFormation template to modify settings such as runtime version or timeout, subsequent executions of `amplify update function` may overwrite your changes.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require any assistance.
