### ISSUE TITLE
Account Verification

### ISSUE THREAD

**Issue by codingforsuckers** [aws-amplify/amplify-cli#1360]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

Hi I'm trying to initialize my project with `amplify init` and I have thesame problem as the one mentioned in this post:
https://github.com/aws-amplify/amplify-cli/issues/972?_pjax=%23js-repo-pjax-container

Now they have listed a possible solution which is calling and verifying my account but  I don't know how to do this. Can anyone please explain to me how I can accomplish this.

Thanks.

**Comment by yuth** [comment]
You could follow the steps listed in the [docs](https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/). You could also get in touch with [AWS support](https://aws.amazon.com/contact-us/?nc1=f_m)

**Comment by codingforsuckers** [comment]
thanks but I already resolved my issue it was a problem with my system clock.
