### ISSUE TITLE
MFALambdaInputs keeps getting stuck

### ISSUE THREAD

**Issue by gusmd01** [aws-amplify/amplify-cli#13600]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

node16

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I have added a new ENV to the existing Amplify app, which has auth. While creating the resources for this new env, cloudformation keeps getting stuck at "MFALambdaInputs". I checked the logs for MFALambda, and found the following error -

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@aws-sdk/client-cognito-identity-provider'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@aws-sdk/client-cognito-identity-provider'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

I have also run "amplify update auth", but doesn't fix the issue. Another point to note is that I am overriding the node version for this lambda, since Node 14 support is no longer available.

Override code -
```
import { AmplifyAuthCognitoStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
    if(resources.userPoolClientLambda)
        resources.userPoolClientLambda.runtime = 'nodejs16.x';
    if(resources.mfaLambda)
        resources.mfaLambda.runtime = 'nodejs16.x';
}
```

### Expected behavior

New env creation should happen without any issues.

### Reproduction steps

1. Create a new Amplify project
2. Add auth
3. Add override as mentioned above
4. Amplify push

### Project Identifier

c9d297d589ce09db4f602aab2288ba1d

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
@gusmd01 Amplify CLI ties the Lambda function in the auth CFN template to a specific node version. To upgrade the NodeJS runtime version, the expected behavior is to upgrade the Amplify CLI version and run `amplify update auth`.

> Although I did get Cannot find module aws-sdk error when I had tried to override with Node18.

was this on a older version of Amplify CLI? 
Could you check the auth CloudFormation template to verify if the embedded Lambda imports AWS SDK v3 with the NodeJs 18 or the AWS SDK v2 with NodeJS 16 by checking the AWS SDK imports.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require any assistance.
