### ISSUE TITLE
Did you try the `amplify env pull` --restore command?

### ISSUE THREAD

**Issue by CloudInnovator** [aws-amplify/amplify-cli#13641]
Did you try the `amplify env pull` --restore command?

_Originally posted by @kaustavghosh06 in https://github.com/aws-amplify/amplify-cli/issues/1523#issuecomment-496645977_
            
This did not work for me.

**Comment by ykethan** [comment]
Hey @CloudInnovator, could you open the issue using our [templates](https://github.com/aws-amplify/amplify-cli/issues/new/choose) as it allows us to collect information that would assist in troubleshooting the issue.
