### ISSUE TITLE
Amplify push not working

### ISSUE THREAD

**Issue by AdewaleTalabi** [aws-amplify/amplify-cli#13645]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.2.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have been working on a react web application, and have tried to use currentAuthenticatedUser() in order to fetch the username, however, I have gotten an error that my user pool has not been configured. In order to solve this, I have tried to run the following commands:

npm install -g @aws-amplify/cli
amplify configure
amplify init
amplify add auth
amplify push

After using amplify push, I get an unknown error, I have used my accesskey and secret from my local machine to connect to AWS

### Describe the bug

 UNKNOWN: unknown error, readlink

### Expected behavior

I expect to be able to push my changes through to amplify 

### Reproduction steps

npm install -g @aws-amplify/cli
amplify configure
amplify init
amplify add auth
amplify push

### Project Identifier

Project identifier: d232737ada608efec9a495ea7eece088

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @AdewaleTalabi, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/12863. Is the project currently under a OneDrive or cloud folder? 
could you moving or creating the project in a different directory and try running push?
If this is not in a OneDrive folder, could you add `--debug` to `amplify push` and provide us the output?

**Comment by AdewaleTalabi** [comment]
Hi @ykethan, after moving the project into my external hard drive, I am able to push to the cloud now. Thank you!
