### ISSUE TITLE
Need help with env: amplify cli ignores changes for cloud-backend, studio is broken

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-cli#13656]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

20.9

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, there are some custom modification, its live app. There are ttl on ddb adjusted, permissions for Cognito triggers to access GraphQL API, custom cdk to create deployment role. Nothing unusual. 

### Describe the bug

Env got messed up and I don't know how to recover.

1. 'amplify status" shows deployed functions, and ignores local change in functions code 
2. "amplify env checkout prod" works but #current-cloud-backend doesn't have all deployed functions
3. "amplify build" does nothing

In addition Amplify Studio was messed up, it didn't show data Data Manager, had to disable and re-enable. It recovered after 10-15 min 

### Expected behavior

It's hard to know what's the state of the project. I don't even know where to look, given amplify status is completely useless.

### Reproduction steps

I don't know how it got into this state 

This is how it's not working:

 amplify update function
? Select the Lambda function you want to update postMessage
General information
- Name: postMessage
- Runtime: nodejs

Resource access permission
- xxx (Query, Mutation)

Scheduled recurring invocation
- Not configured

Lambda layers
- Not configured

Environment variables:
- NODE_OPTIONS: --enable-source-maps
- dummy: test <-- added this new variable

Secrets configuration
- Not configured

? Which setting do you want to update? Environment variables configuration
? Select what you want to do with environment variables: Remove existing environment variables
? Which environment variable do you want to remove: 
  NODE_OPTIONS 
❯ dummy 

amplify status - no changes!

### Project Identifier

DiagnoseReportUploadError
✖ Sending zip

### Log output

<details>

```
# Put your logs below this line
# bunch of lines like this, nothing really interesting
2024-03-18T19:19:24.616Z|info : amplify-provider-awscloudformation.aws-cfn.describeStack.cfn.describeStacks([{"StackName":"[***]rmation:us-[***]st-[***]75:stack/[***]ify-[***]iq-[***]od-[***]059-[***]b4bPreSignup-[***]EQI9WZ/[***]4d10-[***]b9-[***]ee-[***]a5-[***]1ebbd"}])

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by OperationalFallacy** [comment]
Amplify Studio broken again:

![image](https://github.com/aws-amplify/amplify-cli/assets/62673610/de9d27ce-0161-4c5f-86b0-df33ce7d2fa8)

Search bar is absent, model doesn't load data...

Can I get some help, please?

**Comment by josefaidt** [comment]
Hey @OperationalFallacy :wave: thanks for raising this! I suspect the Studio issue is somewhat related to the state mismatch you're seeing locally, but not for certain. Can you try force pushing with `amplify push --force` to force Amplify to take your local state as the current state?

Please note there is a separate issue tracking the bug where Functions created in a separate branch do not show up after merging onto the current https://github.com/aws-amplify/amplify-cli/issues/9790

**Comment by OperationalFallacy** [comment]
Thanks, @josefaidt  I'm trying to figure out how to do it in predictable way, force is not an option for updating a live website. 

How can I get information out of cli what and why its doing or not doing something?

**Comment by josefaidt** [comment]
Hey @OperationalFallacy assuming `amplify status` shows "no changes" across all resources, you can take your existing backend directory, zip it, and upload it in place of the `#current-cloud-backend.zip` in your app's deployment bucket. This will manually patch the state without invoking a CFN update, but I would recommend downloading/copying the existing zip archive beforehand.

This issue sounds similar to https://github.com/aws-amplify/amplify-cli/issues/13323, where there is another in the same realm https://github.com/aws-amplify/amplify-cli/issues/13327

**Comment by OperationalFallacy** [comment]
Thank you, I'll keep this workaround in mind. I see the local status started working again 🤷 
Changes in functions detected and pushed. I also saw amplify cli upgrade from 12.10.1, not sure if that may help, I didn't upgrade.

What about the studio? I rely on it for editing records, so it's pretty big inconvenience it doesn't pull or shows the records.

**Comment by OperationalFallacy** [comment]
![image](https://github.com/aws-amplify/amplify-cli/assets/62673610/94c40582-f57f-4697-9655-c87d71dc236a)

**Comment by OperationalFallacy** [comment]
So what's up with this Studio, is it now broken permanently for the environment?
The error on the screenshot is pretty obvious.
Is it something Amplify team can take care of? I even donated 10$ to the business support plan in the AWS account where its broken!

**Comment by ykethan** [comment]
@OperationalFallacy can you provide us your app-id and region?

**Comment by OperationalFallacy** [comment]
d1f25haz3u16j5 (this is broken studio), us-east-1 

d2bgfp3zb4o7c8 - for the reference, the studio in this env is working 

both deployed from the same codebase

**Comment by ykethan** [comment]
@OperationalFallacy does the project have a storage resource configured?
if yes, in the S3 deployment bucket, could you download the `/studio-backend/amplify-meta.json` file and check if the the storage block has outputs with `BucketName`?

**Comment by OperationalFallacy** [comment]
Thank you, that's was the root cause. 

```
  "storage": {
    "s3buck": {
      "dependsOn": [],
      "providerPlugin": "awscloudformation",
      "service": "S3",
      "lastPushTimeStamp": "2024-03-22T15:22:45.167Z"
    }
  }
  ```
  
I fixed it with `amplify update storage`, just went through the same setting, and it seems forced amplify to deter and deploy storage properly.
  
Not sure how and why amplify cli thought the resource was updated.
