### ISSUE TITLE
Experiencing deployment failure that says file size larger than 2GB

### ISSUE THREAD

**Issue by Alicewyz** [aws-amplify/amplify-cli#13651]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.11.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

AWS Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I was trying to run amplify publish for a web app made by react native, and the process failed after zipping all the artifacts. It shows the deployment error which says: file size (6865244160) is greater than 2 GiB

### Expected behavior

Amplify finish with success

### Reproduction steps

run amplify publish on my react native project (not open source)

### Log output

<details>

```
# Put your logs below this line
2024-03-15T05:18:38.930Z|error : File size (6927650816) is greater than 2 GiB
UnknownNodeJSFault: File size (6927650816) is greater than 2 GiB

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Alicewyz, thank you for reaching out. Diving into the error message this appears to be a NodeJS limit. You could try setting the `max-old-space-size` to a higher value and retry the publish. 
But curious on the size of the application, does the application utilize assets such as images being zipped up as well?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you require any assistance.
