### ISSUE TITLE
'Source image [id] does not exist. Provide a valid source image.' when I ran amplify push with custom resource

### ISSUE THREAD

**Issue by Zhuohui-Li** [aws-amplify/amplify-cli#13673]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When I ran `amplify push`  with custom resource, I got 
```
🛑 The following resources failed to deploy:
Resource Name: [resource_name] (AWS::Lambda::Function)
Event Type: create
Reason: Resource handler returned message: "Source image [id] does not exist. Provide a valid source image. (Service: Lambda, Status Code: 400, Request ID: [request_id])" (RequestToken: [request_token], HandlerErrorCode: InvalidRequest)

🛑 CFN Deployment failed for custom resources.
Name: [resource_name] (AWS::Lambda::Function), Event Type: create, Reason: Resource handler returned message: "Source image [id] does not exist. Provide a valid source image. (Service: Lambda, Status Code: 400, Request ID: [request_id])" (RequestToken: [request_token], HandlerErrorCode: InvalidRequest), IsCustomResource: true"
```

### Expected behavior

Amplify should build and deploy the lambda function

### Reproduction steps

1. `amplify add custom`
2. Choose cdk
3. In cdk-stack.ts, add the following code:
```typescript
const customFunction = new lambda.DockerImageFunction(this, "[function_id]", {
  functionName: "[function_name]",
  code: lambda.DockerImageCode.fromImageAsset(
    path.join(__dirname, "[path_to_dockerfile_folder]")
  ),
  architecture: lambda.Architecture.X86_64,
  initialPolicy: [
    new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ["s3:*"],
      resources: "[s3_resources]",
    }),
  ],
});
```
4. Run `amplify push`
5. Get
```
🛑 The following resources failed to deploy:
Resource Name: [resource_name] (AWS::Lambda::Function)
Event Type: create
Reason: Resource handler returned message: "Source image [id] does not exist. Provide a valid source image. (Service: Lambda, Status Code: 400, Request ID: [request_id])" (RequestToken: [request_token], HandlerErrorCode: InvalidRequest)

🛑 CFN Deployment failed for custom resources.
Name: [resource_name] (AWS::Lambda::Function), Event Type: create, Reason: Resource handler returned message: "Source image [id] does not exist. Provide a valid source image. (Service: Lambda, Status Code: 400, Request ID: [request_id])" (RequestToken: [request_token], HandlerErrorCode: InvalidRequest), IsCustomResource: true"
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @Zhuohui-Li, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/9935. Amplify CLI custom resource currently does not support using methods that use assets.
As a workaround, you can use `fromEcr` method provided on this comment https://github.com/aws-amplify/amplify-cli/issues/9935#issuecomment-1080930003

**Comment by Zhuohui-Li** [comment]
@ykethan Thanks a lot. That works for me.
