### ISSUE TITLE
Amplify console cant connect a second branch after successful Github App authentication

### ISSUE THREAD

**Issue by onejgordon** [aws-amplify/amplify-cli#13672]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.20.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Deploying a hosting only app with no backend. We've kept `aws-exports.js` in git to enable usage of Amplify React components (auth and S3) to existing resources.

### Describe the bug

After starting a fresh Github app in gen 1 Amplify, and connecting a repo and branch successfully, it's impossible to connect a second branch. Authentication flow with Github completes successfully, but on the "Add repository branch" screen, the next button is always disabled making it impossible to add a new branch.

<img width="829" alt="Screenshot 2024-03-26 at 11 00 08" src="https://github.com/aws-amplify/amplify-cli/assets/57584/5604f05e-adee-4581-93d4-674a5adb030b">

### Expected behavior

Ability to add a second branch from the same repo after the first one is created.

### Reproduction steps

1. Create a new Amplify (Gen 1) app
2. Choose Github as source
3. Authenticate
4. Choose repository with a hosting only setup (no amplify directory)
5. Choose branch to connect
6. First connected branch works well, can provision and deploy successfully
7. Click 'connect a branch' to add a second branch
8. See that authentication succeeds to Github, but as shown in screenshot above, impossible to click next to create the connection.

### Project Identifier

`amplify diagnose --send-report`
> No Amplify backend project files detected within this folder.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @onejgordon, the issue appears to be on Amplify hosting, tried to reproduce this in a project but did not observe this behavior. As the AWS Amplify Hosting repository currently only accepts new feature requests. For technical support, we encourage you to open a case with [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case).
On the case provide the App id and region, any errors observed in the browser debug console.
