### ISSUE TITLE
New amplify env still using previous configs 

### ISSUE THREAD

**Issue by yuth** [aws-amplify/amplify-cli#1370]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

Created from [AWS forum Post](https://forums.aws.amazon.com/thread.jspa?threadID=302371&tstart=0) on behalf of  ChrisDB

I've used the amplify CLI on a test app I have, and used it to create an API with Graphql, and the autocreated cognito user pool. I'm trying to create a new environment via `amplify env add`, but even after checking out and pushing the new environment, I am still seeing records from the first environment's DyanmoDB instance (even though I see another configured in the new stack). What is the expected behavior when creating new resources for amplify environments? I noticed that the resource name for the new environment are the same as the ones I initially created. Does this mean all the resources are shared across the environments?

**Comment by yuth** [comment]
ChrisDB could you answer the following
1. Whats the version of Amplify CLI you have installed (You can get the version by running `amplify -v`)
2. Whats the current environment you have checked out. You can see that by running `amplify status` in your project and it prints `Current Environment`
3. What front end are you using for the current project

**Comment by kaustavghosh06** [comment]
Closing as this is not reproducable.

**Comment by Lolodrom** [comment]
Hello!

We are currently facing the exact same Issue and I thought I might not create a new ticket for this.

Same scenario:

Created a "dev" environment. Cognito Pool and DynamoDB are created, we can implement everything, created some users, etc.

Then we created a new environment called "prod" with amplify env add prod, published it and it is now accessible via the generated URL.

For the "prod" env, a new AWS App Sync entry was generated, but the production environment is still using the "dev" DynamoDB + Cognito User Pool.

Is there a specific command, to create "new" instances for a certain environment? In our case "prod"?
