### ISSUE TITLE
Amplify push function does not push all files

### ISSUE THREAD

**Issue by kjsieffert** [aws-amplify/amplify-cli#13706]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

12.10.1

### What operating system are you using?

Linux

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Describe the bug

After adding or updating files other than index.js (such as utility js files), running 'amplify push' does not deploy these file to the backend or recognize the files as having been changed.  Note, I am using the Cloud9 editor.

### Expected behavior

Any new file added to the lamda src directory or any modified existing file should be recognized and pushed when the function is deployed to the backend via an amplify push

### Reproduction steps

Create a lambda function having an index.js file and a second file, like utility.js that is imported by the index.js file.
Deploy the new lambda function with 'amplify push'
modify the utility.js file in the editor (Cloud9)
run amplify status - it will incorrectly show nothing to update
run amplify push - it will incorrectly show nothing to push

please note - I am using the Cloud9 environment

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by biller-aivy** [comment]
Try every time before you push, a amplify env checkout ... 

This should be work

**Comment by kjsieffert** [comment]
Ahh thank you.  I will try this

**Comment by ykethan** [comment]
@kjsieffert was not able to reproduce the issue locally, but as @biller-aivy suggested did the env checkout mitigate the issue?

**Comment by kjsieffert** [comment]
@ykethan yes, thanks.  I no longer see the issue after running an env checkout.  This seems to get the front-end and backend back in sync.  Thanks
