### ISSUE TITLE
RDS using primary key and auto increment for ID.

### ISSUE THREAD

**Issue by integraitco** [aws-amplify/amplify-cli#1371]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
RDS API backend

** What AWS Services are you utilizing? **
RDS, Cognito,  AppSync

** Provide additional details e.g. code snippets **
Hi im trying to connect my app to an existing rds serverless cluster. 
First is that when running amplify api add a schema file is generated, and must have a Entity, in my case the entity was called User just as my Table.
Then When running the amplify api add-graphql-datasource there was an error because it has the same name... I find out that after several ours trying to fix it.. any way i left a type model entity called xxxxx and it works. I think the CLI must be more friendly when creating api with RDS backend during the add command.

Now, I want to create users in my table, but I want to be able to user the auto Increment attribute of the table primary key. 
How can I do this?

**Comment by dennisAWS** [comment]
+1  I want this too.
Here's an example VTL that passes in the 'id' from the client. I want this VTL to not take an 'id' and return the auto-generated id from the database. 

`{
  "version": "2018-05-29",
  "statements":   [
  	"INSERT INTO Customers VALUES (:ID, :NAME, :PHONE, :EMAIL)", "SELECT * FROM Customers WHERE id = :ID"
  ],
  "variableMap": {
  	":ID": "$ctx.args.createCustomersInput.id",
    ":NAME": "$ctx.args.createCustomersInput.name",
    ":PHONE": "$ctx.args.createCustomersInput.phone",
    ":EMAIL": "$ctx.args.createCustomersInput.email"
  }
}`

**Comment by integraitco** [comment]
> +1 I want this too.
> Here's an example VTL that passes in the 'id' from the client. I want this VTL to not take an 'id' and return the auto-generated id from the database. btw, I'm using the [VariableMap](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-rds.html) option.
> 
> `{ "version": "2018-05-29", "statements": [ "INSERT INTO Customers VALUES (:ID, :NAME, :PHONE, :EMAIL)", "SELECT * FROM Customers WHERE id = :ID" ], "variableMap": { ":ID": "$ctx.args.createCustomersInput.id", ":NAME": "$ctx.args.createCustomersInput.name", ":PHONE": "$ctx.args.createCustomersInput.phone", ":EMAIL": "$ctx.args.createCustomersInput.email" } }`

Hello dennis, any solution for this?
I think this is a very common use case, where ids must be handle in the database...
Im missing something on how to use amplify and RDS?

**Comment by kartikrao** [comment]
Try `SELECT * FROM Customers WHERE id = LAST_INSERT_ID()`

**Comment by scarefree** [comment]
> Try `SELECT * FROM Customers WHERE id = LAST_INSERT_ID()`

Are you suggesting doing a SELECT for every INSERT? Your suggested solution doesn't scale and is calling for disaster.

**Comment by kartik78** [comment]
@scarefree - Are you not going to return the inserted item back ? The statements block for a create item always has an INSERT followed by a SELECT. 

If you are that concerned about concurrently executing requests move the statements to a stored procedure and execute within a transaction, better still don’t use sequences, $util.autoId is safer.

**Comment by nikhname** [comment]
@integraitco, as @kartik78 mentioned, you can use $util.autoId to safely create a 128-bit randomly generated UUID for each new user. Feel free to comment/reopen if this solution doesn't work for you.
