### ISSUE TITLE
error saying parameter.json does not exist in auth folder

### ISSUE THREAD

**Issue by ahsan2hashmi** [aws-amplify/amplify-cli#13716]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20

### Amplify CLI Version

12.10.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

yes since I was unable to run amplify pull after i manually added the auth folder from the s3 deployment bucket into the directory manually after running amplify pull but before finishing local configurations.

### Describe the bug

Originally when I pull the project from git and ran amplify pull i would get an error like this
2022-11-14T06:16:50.802Z [WARNING]: ✖ There was an error initializing your environment. 2022-11-14T06:16:50.816Z [INFO]: 🛑 Failed to pull the backend. 2022-11-14T06:16:50.816Z [INFO]: File at path: amplify/backend/auth/xxxxxxxxxxxxxxxxxxx/parameters.json' does not exist

After deleting amplify folder and config files and running amplify pull app iid --- env name --
get this error 
🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: xxxxxxxxxxxxxxxxx

im able to pull the backend if I amplify pull --app id and manually add the auth folder from the s3 deployment bucket into the amplify directory manually after running amplify pull but before finishing local configurations.

Other notes:
- i am able to amplify push but not amplify pull. The amplify build also fails when deploying from github.
- the auth folder was also nested in some other folders and not in the root of the s3 deployment bucket
- I have live users so am not able to run amplify remove auth

### Expected behavior

run amplify pull and backend should update

### Reproduction steps

1. run amplify pull appid -xxxxx
2. get error 

### Project Identifier

Project Identifier: 9aca2a984adc2c198809949dbc7c5b96
Session Identifier: 34977174-b7e9-43f2-9086-fab981582108

### Log output

<details>

```
# Put your logs below this line

🛑 Failed to pull the backend.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

</details>

### Additional information

im able to pull the backend if I amplify pull --app id and manually add the auth folder from the s3 deployment bucket into the amplify directory manually after running amplify pull but before finishing local configurations.

Other notes:
- i am able to amplify push but not amplify pull. The amplify build also fails when deploying from github.
- the auth folder was also nested in some other folders and not in the root of the s3 deployment bucket
- I have live users so am not able to run amplify remove auth

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @ahsan2hashmi, thank you for reaching out. wanted to get some additional information on the issue. 

> the auth folder was also nested in some other folders and not in the root of the s3 deployment bucket

Do you observe duplicate file or a nested `#current-cloud-backend` folder in the zip? A screenshot of the structure would help us dive into this.

 could you provide us the full path in the error `amplify/backend/auth/xxxxxxxxxxxxxxxxxxx/parameters.json' does not exist`. As the parameters file should be present under the build folder of the auth resource.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
