### ISSUE TITLE
[Admin APIs] Pagination not working for listGroups API action

### ISSUE THREAD

**Issue by muvashi** [aws-amplify/amplify-cli#13722]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.19.0

### Amplify CLI Version

12.10.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

listGroups API action present in Admin Actions API is not giving correct results when number of groups present in Cognito user pool is more than 25. In first call, only 25 groups are returned.

### Expected behavior

25 groups should be returned along with value of NextToken to be used for subsequent calls.

### Reproduction steps

Install admin actions API, create more than 25 groups in Cognito user pool and invoke listGroups API.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by rtpascual** [comment]
The fix for this was released in version `12.12.0`
