### ISSUE TITLE
Can't authroize inti command line

### ISSUE THREAD

**Issue by InfoPrince21** [aws-amplify/amplify-cli#13720]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

12.11.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Yes, I created a user and gave permissions. 

### Describe the bug

🛑 User: arn:aws:iam::339712952329:user/RootPrince is not authorized to perform: amplify:CreateBackendEnvironment on resource: arn:aws:amplify:us-east-1:339712952329:apps/d2asptaadn0oid/backendenvironments/

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 775ac1e3-c343-4b71-bf26-88579bd468b5

### Expected behavior

I in fact have permissions set up for the user. 

### Reproduction steps

create a new account and follow the steps to set up. I followed steps needed to create an account and initialize it through visual studio line commands in the terminal.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @InfoPrince21, does the user profile have [AdministratorAccess-Amplify](https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AdministratorAccess-Amplify) attached?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
