### ISSUE TITLE
Install Amplify CLI on Windows :  next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### ISSUE THREAD

**Issue by ankit-927** [aws-amplify/amplify-cli#13736]
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd

### If applicable, what version of Node.js are you using?

v18.20.2

### Amplify CLI Version

latest version

### What operating system are you using?

Windows - 64-bit operating system

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Describe the bug

I run the below workflow but the curl command fails with an error. Is there something else to be done apart from running curl for Windows?

![amplify install issue](https://github.com/aws-amplify/amplify-cli/assets/168081692/f5e3d1fe-d3d8-4172-8bc7-d28b86be1a35)

After running the amplify install command (npm i -g @aws-amplify/cli) It takes more than 10 minutes to complete the run.
After the run is completed, when I'm checking the amplify version command - amplify -version
It is throwing this error
![npm install cmd](https://github.com/aws-amplify/amplify-cli/assets/168081692/4cc29d11-941f-4d8c-bf56-949a08e438e8)

After downloading and installing the package the package is not getting installed directly the terminal is closed within seconds

### Expected behavior

amplify file needs to be installed

### Reproduction steps

1. curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd
2. npm i -g @aws-amplify/cli

It is not working on my system

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @ankit-927, the issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/11765, when installing Amplify behind a corporate proxy or VPN. Are you utilizing a proxy or VPN?
if yes, I would suggested working with the company security team: https://github.com/aws-amplify/amplify-cli/issues/11765#issuecomment-1442095790 
https://github.com/aws-amplify/amplify-cli/issues/11765#issuecomment-1437263701

**Comment by ankit-927** [comment]
I'm not using any proxy or VPN and also not using any anti-virus.

**Comment by ykethan** [comment]
@ankit-927 found a similar issue [here](https://learn.microsoft.com/en-us/answers/questions/1320695/the-revocation-function-was-unable-to-check-revoca). This issue appears to be related to your network or network settings on your machine. Verify your local settings to check if a [proxy was set](https://support.microsoft.com/en-us/windows/use-a-proxy-server-in-windows-03096c53-0554-4ffe-b6ab-8b1deee8dae1) and suggest reaching out to your network Admins.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
