### ISSUE TITLE
Amplify init error: "We are unable to process your request"

### ISSUE THREAD

**Issue by raphaelgrau** [aws-amplify/amplify-cli#13737]
### Amplify CLI Version

12.11.1

### Question

Hello,

I try to create my Amplify project with the CLI and have this error : 
> 🛑 We are unable to process your request. Please reach out to your support representative.

Here is the logs of everything I do (first `amplify configure` then `amplify init`)

<img width="688" alt="Capture d’écran 2024-04-25 à 21 13 20" src="https://github.com/aws-amplify/amplify-cli/assets/33690908/bf86c926-fd49-4d8b-93be-f09c64c00c5f">

Any idea what is happening? 

Note that when I go on the console and try to add an Amplify project from there, I also got an error after typing the name of the project : 

<img width="1384" alt="Capture d’écran 2024-04-25 à 21 18 59" src="https://github.com/aws-amplify/amplify-cli/assets/33690908/17a1c6a0-6547-4583-9927-19d2d4b29080">

Thanks!

**Comment by ykethan** [comment]
Hey @raphaelgrau, thank you for reaching out. The issue appears to similar to https://github.com/aws-amplify/amplify-cli/issues/13124. Refer to the comment https://github.com/aws-amplify/amplify-cli/issues/13124#issuecomment-1761930499 providing information on opening a support case on the AWS console.

**Comment by raphaelgrau** [comment]
Hey @ykethan thanks for the info, I just had a chat with someone from support after opening a case (Case ID: 171407717500657). 

This is what I have been told :
> Thanks Raphael, your question requires technical support, we are basic support so we are not trained to give technical support and since you have a basic support plan we cant transfer you to tech support, but dont worry please allow me a few minutes to find information that might help you fix this issue

After noticing that my payment method was invalid, I updated it but it seems I am still encountering the same issue with Amplify.

Now the person from the support told me I had to reach fill out this form (https://aws.amazon.com/contact-us/sales-support/) to contact the sales team and get technical support.

**Comment by ykethan** [comment]
@raphaelgrau thank you for the update. The behavior is currently occurring on the account which the support team should be able to assist you on this.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
