### ISSUE TITLE
Creating API models - is not authorized to perform: apigateway:GET

### ISSUE THREAD

**Issue by RAISERALEX21** [aws-amplify/amplify-cli#13741]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).

### Which UI component?

Liveness

### Gradle script dependencies

**I'm working with AMPLIFY-UI-ANDROID/samples/liveness and following the setup guide** ->
_// amplify-ui-android/samples/liveness/README.md_

To the above, I do not understand well what would be needed within my permissions or if I need to make another change from the aws console., I hope for your comments.

### Environment information

Welcome to Gradle 8.2.1!
 
Here are the highlights of this release:
- Kotlin DSL: new reference documentation, assignment syntax by default
- Kotlin DSL is now the default with Gradle init
- Improved suggestions to resolve errors in console output
- Reduced sync memory consumption
 
For more details see https://docs.gradle.org/8.2.1/release-notes.html
 
 
------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------
 
Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa
 
Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_311 (Oracle Corporation 25.311-b11)
OS:           Mac OS X 10.16 x86_64

### Please include any relevant guides or documentation you're referencing

https://github.com/aws-amplify/amplify-ui-android/blob/main/samples/liveness/README.md

### Describe the bug

**The following screenshot shows the error:**
<img width="1581" alt="issue_liveness" src="https://github.com/aws-amplify/amplify-ui-android/assets/3058806/2703e750-a328-4106-bda0-5a55e32c98f6">

**But within my AWS console, I've added permissions to authorize my user. I'll attach a screenshot ->**
<img width="1536" alt="amplify-dev" src="https://github.com/aws-amplify/amplify-ui-android/assets/3058806/1f73c967-5d04-4c4c-877d-cebcc293a7e5">
<img width="943" alt="Captura de pantalla 2024-04-25 a la(s) 11 32 35 a m" src="https://github.com/aws-amplify/amplify-ui-android/assets/3058806/dfe2efa6-2d93-4f17-88e7-da01ca552382">

### Reproduction steps (if applicable)

**where I'm encountering an issue within the step:**
_Provision Backend API -> 3. Once finished, run amplify push to publish your changes._

next -> amplify push -> error!!
<img width="1581" alt="issue_liveness" src="https://github.com/aws-amplify/amplify-ui-android/assets/3058806/34f898af-60ef-4f94-aed9-8555f31bb4c7">

### Code Snippet

```java
// Put your code below this line.

```

### Log output

```
// Put your logs below this line


```

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:9923229d-e322-4d23-bbf8-b22c8ed3a2c7",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_k4H5NZqDH",
                        "AppClientId": "5nhoomrfgc2visru2stud45bct",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "liveness70a2b540-70a2b540-dev.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "5nhoomrfgc2visru2stud45bct",
                            "SignInRedirectURI": "myapp://callback/",
                            "SignOutRedirectURI": "myapp://signout/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

### Additional information and screenshots

AMPLIFY VERSION :
12.11.1
DEVICE:
macOS - version 12.7.4

**Comment by mattcreaser** [comment]
Although this was encountered while setting up the Liveness sample, this error occurs when executing `amplify push` with the CLI and is not related to the UI component itself. 

Transferring to the CLI repo for triage.

**Comment by ykethan** [comment]
Hey @RAISERALEX21, from the error message it appears this occurring on a IAM permission boundary set on the user the Amplify CLI is utilizing. Refer to this [post](https://repost.aws/knowledge-center/iam-access-denied-permissions-boundary) providing additional information. I would suggest checking the boundary permissions and enable `apigateway:GET` to mitigate this behavior.

**Comment by RAISERALEX21** [comment]
I've been trying to enable the permission as shown in the images... but so far, I haven't been successful, and I don't really have much experience with AWS IAM. Could you specify the steps I would need to follow to enable it?

I share my console settings in IAM.. ->
<img width="908" alt="Captura de pantalla 2024-04-26 a la(s) 9 45 31 a m" src="https://github.com/aws-amplify/amplify-cli/assets/3058806/0edcffe7-1e05-4e39-a240-3c1839d770f3">
<img width="701" alt="Captura de pantalla 2024-04-26 a la(s) 9 45 40 a m" src="https://github.com/aws-amplify/amplify-cli/assets/3058806/d4065b72-3bbd-46e1-9e86-f5cfe7a42cb4">

**Comment by ykethan** [comment]
@RAISERALEX21 The permission boundary is a additional layer of security in IAM, the allow permission need to exist on both.
Refer to documentation on [permission boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html).

The permissions boundary should be below the permissions policies section where you can add the necessary permmissions.
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/199329b2-cfbc-4a71-a91c-bdef78cccc80)

**Comment by ykethan** [comment]
@RAISERALEX21 Glad to hear I was able to assist you. Do reach out if you are experiencing any issue. Closing the issue.
