### ISSUE TITLE
Amplify CLI password policy defaults for Cognito auth are not following NIST best practices

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1375]
Default options still recommend ridiculous password complexity rules when this hasn't been a NIST recommended practice for years.

Please default all of these rules to unchecked.

**Comment by yuth** [comment]
@et304383 thanks for reporting this. I will do a bit more investigation to come up with good default password policy.

**Comment by yuth** [comment]
@et304383 could you please provide link to the NIST recommendation document you are referring to.

**Comment by et304383** [comment]
https://pages.nist.gov/800-63-3/sp800-63b.html

Tldr:
https://www.fpainc.com/blog/password-guidelines-from-nist

**Comment by yuth** [comment]
@et304383 just to make sure I understand you correctly, you are suggesting that Amplify CLI is creating a overly complex default password policy by enforcing the following
1. At least one upper case char
2. At least one lower case char
3. At least one number
4. At least one special char

You think the default password policy should only enforce character limit of 8 and not enforce above mentioned list

**Comment by et304383** [comment]
I believe users can do whatever they wish, but defaulting all of these requirements to ON suggests that AWS supports this outdated password complexity rubbish.

**Comment by yuth** [comment]
@aws-amplify/cli@1.6.10 includes the updated default password policy
