### ISSUE TITLE
Amplify push fails after adding a function

### ISSUE THREAD

**Issue by juri-diener** [aws-amplify/amplify-cli#13760]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.7.3

### Amplify CLI Version

11.0.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

So I added with amplify add function a new lambda function. Added in package.json the "type":"module". 
And wrote my function. Then added custom policies to the table and  wanted to push the changes, and amplify fails with this error: 

This function is the new created one.
In aws.console: 
Embedded stack arn:aws:cloudformation:eu-north-1:816334333069:stack/amplify-newapp-dev-c053d-functionacceptOrgFollowing-3DQVL14IIR53/2cb22be0-08bb-11ef-887e-0a25218daa9a5 was not successfully created: The following resource(s) failed to create: [LambdaFunction].

02/05/2024, 21:40:34 | amplify-newapp-dev-c053d | UPDATE_ROLLBACK_COMPLETE |  Failed(X)
02/05/2024, 21:40:33 | authnewapp248a1258 (auth) | UPDATE_COMPLETE | -
02/05/2024, 21:40:33 | apinewapp (api) | UPDATE_COMPLETE | -
02/05/2024, 21:38:47 | functionnewapp768a1253PostConfirmation (function) | UPDATE_COMPLETE | -
02/05/2024, 21:38:47 | functioncreateOrgAndEverything (function) | UPDATE_COMPLETE | -
02/05/2024, 21:38:36 | storagenewapp (storage) | UPDATE_COMPLETE | -
02/05/2024, 21:38:35 | amplify-newapp-dev-c053d | UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS

Until this error message below it takes like over 30 minutes until it appears . I don't think this is normal.
Rolled back (6 of 5)
🛑 ["Index: 4 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]

Then I tried to add a new env and tried to push it, and it worked. WHY?
Honestly it's kinda annoying, It really stops me in my development. 
Please solve this issue.

Maybe if I did something wrong then every hint is really appreciated.

### Expected behavior

Should work after adding Lambda functions

### Reproduction steps

amplify add function
amplify update function
Resource access permission
storage
amplify push

### Project Identifier

ebfc1cb67b3e849d27a343745c7d5874

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by juri-diener** [comment]
I tried to delete the function with amplify remove function and added again: Now I get this error:
🛑 The following resources failed to deploy:
Resource Name: LambdaFunction (AWS::Lambda::Function)
Event Type: create
Reason: acceptOrgFollowing-dev already exists in stack arn:aws:cloudformation:eu-north-1:816395333069:stack/amplify-examplebackendaws-dev-194204-functionacceptOrgFollowing-9ARCKG9E2E5I/24c1ff70-0662-11ef-96d9-0ecc2333e0de6


🛑 Resource is not in the state stackUpdateComplete
Name: LambdaFunction (AWS::Lambda::Function), Event Type: create, Reason: acceptOrgFollowing-dev already exists in stack arn:aws:cloudformation:eu-north-1: 816395333069:stack/amplify-examplebackendaws-dev-194204-functionacceptOrgFollowing-9ARCKG9E2E5I/24c1ff70-0662-11ef-96d9-0ecc2333e0de6

the examplebackendaws is a complete different app. So I don't understand the it's complaining the the function exists.

**Comment by ykethan** [comment]
hey @juri-diener, function with the same name cannot be created if the function exists in the region.
![image](https://github.com/aws-amplify/amplify-cli/assets/87995712/4f50947d-149a-4899-b697-523b6f11564e)

> ["Index: 4 State: {"deploy":"waitingForDeployment"} Message: Resource is not in the state stackUpdateComplete"]

It appears the stack failed to update on CloudFormation, could you check the stack events on the CloudFormation console for any notable errors? 
additionally, noticed the Amplify CLI version appears to be out of date, could you upgrade the CLI using `amplify upgrade`.

**Comment by juri-diener** [comment]
> hey @juri-diener, function with the same name cannot be created if the function exists in the region. ![image](https://private-user-images.githubusercontent.com/87995712/327795023-4f50947d-149a-4899-b697-523b6f11564e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTM2MDksIm5iZiI6MTcxNzY5MzMwOSwicGF0aCI6Ii84Nzk5NTcxMi8zMjc3OTUwMjMtNGY1MDk0N2QtMTQ5YS00ODk5LWI2OTctNTIzYjZmMTE1NjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3MDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzA5MDZjZGY1NzU1OTJkMmZiYjBlMjI2N2E5YTdjZjUwNzUxZjkwNzU2YWY2NWFiYmNiY2E3YjNlZmUzNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iIAxz2c7JZAhsGOhY8MBYetkggy7NRkqVlCissaWEig)
> 
> > ["Index: 4 State: {"deploy":"waitingForDeployment"} Message: Resource is not in the state stackUpdateComplete"]
> 
> It appears the stack failed to update on CloudFormation, could you check the stack events on the CloudFormation console for any notable errors? additionally, noticed the Amplify CLI version appears to be out of date, could you upgrade the CLI using `amplify upgrade`.

I had for couple days again the same issue. I created a function. And when I was done I wanted to push and again it failed.
This thing get's really annoying. If that will happen in production, this will be worse. 
Please prioritise this issue. 
Or help me if I'm doing something wrong or maybe my setup of the project has issues?

**Comment by ykethan** [comment]
Hey @juri-diener, can you run `amplify pull` to update your local project with the latest changes to `current-cloud-backend`, then update the resources such as functions locally and push.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
