### ISSUE TITLE
my broken deployment issue is going to cost me $2300 this month and wont delete! HELP

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-cli#13775]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

details on previous ticket

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

just trying to delete the project.  have backed up the dynamodb using a different s3 bucket and was using the aws amplify console to delete the backend services before deleting the project

### Describe the bug

I have a previous issue deploying here:
https://github.com/aws-amplify/amplify-cli/issues/13398

I tried a bunch of their suggestions but nothing seemed to unstick the deploymment.  I even had AWS 2 engineers trying to help me.  This is a fun side project, not a money making project and it has run costing me ~$40 a month for a few years.  6 months ago a deployment got stuck and I could no longer deploy, but the site still worked so it wasnt a big deal.  AWS Engineers looked for a bit  (2 hours on the phone) with me but then needed to regroup because they couldnt figure it out.  Here we are a few month later and i looked at billing and last month cost me $900 (its hitting lots of errors and logging a ton now) and this month has already cost me $889 and is projected to cost me $2300.  I backed up the data to s3 and decided to just delete the project backend first.  It WONT DELETE!!!! 

<img width="1089" alt="Screenshot 2024-05-12 at 2 25 50 PM" src="https://github.com/aws-amplify/amplify-cli/assets/4690960/f1010e32-4cb7-4aa3-be1b-cc4ec2bea6ac">

please help, i cant afford to pay $2300 a month for a silly project that i made a few years ago.

### Expected behavior

I should be able to delete the aws amplify backend using the existing tools for aws amplify

### Reproduction steps

I am just trying to delete a backend aws amplify service using the console and my deployment issue seems to also be blocking my deletion

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by contractorwolf** [comment]
<img width="563" alt="Screenshot 2024-05-12 at 2 36 03 PM" src="https://github.com/aws-amplify/amplify-cli/assets/4690960/2c9c1bb2-4044-4886-a655-2cdedd19c5e8">

**Comment by biller-aivy** [comment]
Go to cloudformation and delete the Projekte there. But better would be to check in cost editor what it is and delete or stop the Ressource which is called recursively maybe

**Comment by contractorwolf** [comment]
<img width="1234" alt="Screenshot 2024-05-12 at 5 06 31 PM" src="https://github.com/aws-amplify/amplify-cli/assets/4690960/2a0d0897-7c76-4512-9da2-e28058f4cfbb">

**Comment by contractorwolf** [comment]
as it turned out those were the same issues I was dealing with trying to deploy it for 8 months wouldnt allow me to delete it either.  Was getting stuck on some IDP thing that I eventually just decided to go nuclear and delete.  I was finally able to delete the whole project :/

**Comment by contractorwolf** [comment]
this is the same issue i was hitting:
https://github.com/aws-amplify/amplify-cli/issues/2096

**Comment by contractorwolf** [comment]
yeah but I am still working through the process to get the charges removed

**Comment by ykethan** [comment]
@contractorwolf following up on this, were you able to reach out to the account support team for assistance?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
