### ISSUE TITLE
GroupDataSource:Name cannot be deleted as it is in use by app...

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1377]
I was building my graphql.schema with regular `amplify push` commands.
I changed some @connection and all of a sudden my project get stuck.
I'm not able to `amplify push` anumore.
It rolls back to the last Cloudformation state

**Comment by yuth** [comment]
@sprucify Could you paste the snippet of changes you made to `@connection` in your schema. Could you also include cloud formation error

**Comment by sprucify** [comment]
I'm not exactly sure what I did
But I placed some named connections between these models:
`type GroupSwipe
  @model
  @auth(rules: [
    {allow: owner},
    {allow: owner, ownerField: "group", operations: [read] }
  ])
{
  id: ID!
  owner: String
  recipe: Recipe! @connection
  liked: Boolean!
  group: Group @connection
  timestamp: AWSDateTime
}

type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
}`

**Comment by sprucify** [comment]
UPDATE_ROLLBACK_IN_PROGRESS app-2019022182048-apidinnerapi-1GCI70SU7T-GroupSwipe-1BDQ4N60F4L AWS::CloudFormation::Stack Wed May 01 2019 19:25:12 GMT+0200 (GMT+02:00) Export xjepdp5jhdomwr7nhy6hm:GetAtt:**GroupSwipeDataSource:Name cannot be deleted** as it is in use by app-201900182048-apidinnerapi-1GCHH0SU7T-ConnectionStack-1GCT0E9QUD

**Comment by yuth** [comment]
This is a known limitation that has been reported in https://github.com/aws-amplify/amplify-cli/issues/1141. Could you try removing the connection first and then adding it with name as 2 separate `amplify push`

**Comment by sprucify** [comment]
No luck with that.
Is there any workaround (maybe on AWS dashboard side) to get me going for now?

**Comment by sprucify** [comment]
#1141 initially didn't fix my problem.
I ended up deleting all model structures that where touched by the failed @connection attempt
That got through

**Comment by lorensr** [comment]
For me the problem was #1425 which was fixed in `v1.6.10`
