### ISSUE TITLE
Aws Amplify Liveness

### ISSUE THREAD

**Issue by abhinav-ab-25** [aws-amplify/amplify-cli#13777]
### Amplify CLI Version

12.12.0

### Question

I am trying to integrate AWS Amplify for amplify liveness with my application. However, I am getting the error "We are unable to process your request. Please reach out to your support representative".This is taking place after running "amplify init" in my project root directory. Am I missing something? I've tried every troubleshooting step I came across but am still having the same error message. Any help would be greatly appreciated.
![Screen Shot 2024-05-13 at 9 51 47 AM](https://github.com/aws-amplify/amplify-cli/assets/72129012/ed67e1c8-9958-4324-b9f2-fa632d9037b6)

**Comment by ykethan** [comment]
Hey @abhinav-ab-25, thank you for reaching out. Refer to the comment on https://github.com/aws-amplify/amplify-backend/issues/1456#issuecomment-2103438983 providing information on the mitigation steps.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
