### ISSUE TITLE
AMplify push not working suddenly

### ISSUE THREAD

**Issue by irog-ai** [aws-amplify/amplify-cli#13784]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.16.0

### Amplify CLI Version

12.12.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

My application wasworking perfectly fine. Suddenly today when i do a amplify push i am getting exception.
[report-1715891880167.zip](https://github.com/aws-amplify/amplify-cli/files/15340862/report-1715891880167.zip)

### Expected behavior

Amplify push should update my lambda changes 

### Reproduction steps

[report-1715891880167.zip](https://github.com/aws-amplify/amplify-cli/files/15340881/report-1715891880167.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @irog-ai, thank you for reaching out. The error message appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/12315. Was the project folder recently re-named?
if yes could you try updating the stored project path at `amplify/.config/local-env-info.json` or by running `amplify configure project`.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
