### ISSUE TITLE
Howto create proper group permissions without using Cognito

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1379]
I have the following datastructure.
What I basically want to achieve is that people inside the same Group can **read only**  see each others Swipe data points.

```
type Swipe
  @model
  @auth(rules: [
    {allow: owner},
    {allow: groups, groupsField: "group"}
  ])
{
  id: ID!
  owner: String
  recipe: Recipe! @connection
  liked: Boolean!
  group: Group @connection(name: "GroupSwipes")
  timestamp: AWSDateTime
}



type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}
```

At the moment I get only my own Swipe data if I run my `ListSwipes()` query
Groups are dynamically created within the app, so Cognito wouldn't work here?
Cognito is also limited to 25 groups

**Comment by mikeparisstuff** [comment]
As of writing you have a few options.

1. Turn top level queries off for the model that you want to be read protected by the group. For example,

```graphql
type Group @model {
  id: ID!
  members: [String!]!

  # You can specify that only members of this group can access this connection field.
  swipes: [Swipe] 
    @connection(name: "GroupSwipes")
    @auth(rules: [{ allow: "owner", ownerField: "members" }])
}
# We turn queries off so there is no `Query.getSwipe` or `Query.listSwipes`.
# You can only access these swipes via `Group.swipes` which protected by the group membership.
# Only owners may mutate swipe objects.
type Swipe 
  @model(queries: null) 
  @auth(rules: [
    {allow: owner, operations: [create, update, delete]}
  ])
{
  id: ID!
  owner: String
  liked: Boolean!
  group: Group @connection(name: "GroupSwipes")
  timestamp: AWSDateTime
}
```

**Comment by sprucify** [comment]
I haven't tested this out yet, but the next issue would be, how do I add Cognito users to  `members: [String!]!` ?

**Comment by mikeparisstuff** [comment]
@sprucify 

**I haven't tested this out yet, but the next issue would be, how do I add Cognito users to members: [String!]! ?**

You would manually add the `username`, `sub`, or whatever attribute you want to use as the identity to the list of members on the object. 

To implement your access patterns, it depends if the authorization information lives on the model that is being operated or not. 

For example in **The creator of a Group is the only one that can delete / update a group**, if a **Group** contains and attribute **creatorId** and that **creatorId** contains a string equal to the **sub** claim in your JWT then you can use the auth directive to authorize **update** & **delete** operations.

```graphql
type Group 
  @model 
  @auth(rules: [
      { allow: owner, ownerField: "creatorId", identityField: "sub", operations: [update, delete] }
    ])
{
  id: ID!
  creatorId: String!
}
```

To implement access patterns that cross @connections for mutations you can write custom resolvers that fetch and validate information from one or multiple tables if using pipelines. The general ideal is that if the authorization information lives on a type that is not directly being operated on, you can use a pipeline resolver to first fetch that information and authorize before executing the write. If you are storing your members as a list of strings on the group, then you can use the built in @auth directive to authorize mutations. For these you can use steps like shown here: https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

**Comment by kaustavghosh06** [comment]
I'm gonna close this issue for now, if you till have any question feel free to comment on this or re-open this thread.
