### ISSUE TITLE
Parameters: [auth#appname#IdentityPoolId] do not exist in the template

### ISSUE THREAD

**Issue by PeterSchoell** [aws-amplify/amplify-cli#13797]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v21.5.0

### Amplify CLI Version

12.12.0

### What operating system are you using?

Microsoft Windows 10 Business

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

When attempting to update the auth category of a project the deployment fails with the following error.

```
🛑 The following resources failed to deploy:
Resource Name: authuserPoolGroups (AWS::CloudFormation::Stack)
Event Type: update
Reason: Parameters: [auth#appname#IdentityPoolId] do not exist in the template
```

### Expected behavior

The auth category changes can be deployed

### Reproduction steps

Have an Amplify project with auth category

Make some change to the auth 

Run amplify push -y.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @PeterSchoell, Could you provide us some additional information on the update made on the auth resource such as prompts selected and inputs provides. This would assist in reproducing the issue.
Could you check the `backend-config.json` and `amplify-meta.json`, if the `userPoolGroups` contains the `dependsOn` block with `IdentityPoolId`?

**Comment by PeterSchoell** [comment]
I have redone many settings, rebuilt and pushed some things. The result was that everything worked again at some point. Unfortunately, I cannot provide any further details. The problem must have taken me two weeks.

**Comment by sandeep-pracbee** [comment]
Related issue https://github.com/aws-amplify/amplify-cli/issues/14071
