### ISSUE TITLE
Command not found when using auth add on Windows

### ISSUE THREAD

**Issue by kavengagne** [aws-amplify/amplify-cli#138]
**Describe the bug**
Error when running ``` amplify auth add ``` on Windows. Command not found.

**To Reproduce**
1. ``` amplify init ```
2. ``` amplify auth add ```
3. Error will display and say Command not found.

**Expected behavior**
As stated in the documentation, ``` amplify auth add ``` should work properly.
Using ``` amplify auth enable ``` works because the file enable.js exists.

**Desktop (please complete the following information):**
 - OS: Windows (All versions)

**Additional context**
Commands are not resolved in the same way on Windows. A file with the name of the command needs to be present in the *commands* directory and a file with the name of the subcommand needs to be present in the *auth* directory.

**I will submit a Pull Request to propose a fix**

**Comment by kavengagne** [comment]
Hi,
I submitted a [Pull Request to gluegun](https://github.com/infinitered/gluegun/pull/385) to fix the issues with paths that amplify-cli is facing.

**Comment by kaustavghosh06** [comment]
@kavengagne  Thanks for the fix. Will close this issue once gluegun publishes the fix o npm.

**Comment by kaustavghosh06** [comment]
This issue should be fixed with the latest version of the CLI. Feel free to re-open if the problem still persists.
