### ISSUE TITLE
Amplify multi env

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1380]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AWS Amplify multienv
** What AWS Services are you utilizing? **
AWS Amplify
** Provide additional details e.g. code snippets **
Hi we are using git flow for managing project and are using multienv.
Problem is whenever someone working on common environment and push changes using amplify and share the branch. Other team member pulling branch and doing amplify status it is showing some updates (mainly for api and functions).

**Comment by kaustavghosh06** [comment]
@achutkiran Could you please provide more information regarding it? As to what is the `amplify status` output?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of information to proceed further with the issue.
