### ISSUE TITLE
Issue with amplify cli when trying to merge changes from a git branch into a new amplify env

### ISSUE THREAD

**Issue by dwrynngs** [aws-amplify/amplify-cli#13809]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.0

### Amplify CLI Version

12.10.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

ran amplify status after merging in changes to a new amplify env as per the team environments docs.  trying to add a feature to the new env ( a dynamodb table)

Bug report submitted with the following project id: 28784a7c3de959fea0ff45eaee68d6de

### Expected behavior

expected the amplify status command to show that the dynamodb table needed to be created.

### Reproduction steps

build a dev and stg env with a simple api.  then add a dynmodb table into the dev and merge dev to stg.  This is as per the docs at https://docs.amplify.aws/gen1/javascript/tools/cli/teams/ specifically the diagram 

<img width="868" alt="Screenshot 2024-06-06 at 13 12 41" src="https://github.com/aws-amplify/amplify-cli/assets/45206508/86a95ba1-9b39-4a63-a23b-ce5fb21458ff">

### Project Identifier

28784a7c3de959fea0ff45eaee68d6de

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by biller-aivy** [comment]
Just checkout the staging env again after merge

**Comment by ykethan** [comment]
Hey, following up on this issue as suggested running `amplify env checkout <existing-env-name>` should hydrate the `amplify-meta.json` file. Do let us know if this does not mitigate the issue.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
