### ISSUE TITLE
Getting an error following the AWS Amplify Team Environments docs

### ISSUE THREAD

**Issue by dwrynngs** [aws-amplify/amplify-cli#13808]
### Amplify CLI Version

12.10.2

### Question

I am trying to follow the team environment docs for amplify.  I have set up a dev env and then a stg env from the dev env.  I have them committed to separate git branches with the same names.  They work fine when set up.  

I then added a simple storage table to the dev env.  A simple dynamodb database using the command 'amplify add storage'.  That added correctly.  I then followed the example for 'Adding & deploying features in an environment'.  I checked out my stg branch, and changed amplify env to stg.  I then ran a git merge dev and resolved conflicts on some files (issue with gitignore).  I then tried an 'amplify status' command before I tried an 'amplify push'.  I got the following error using 'amplify status --debug'

![Screenshot 2024-06-06 at 13 04 36](https://github.com/aws-amplify/amplify-cli/assets/45206508/9d07115f-145f-4fe5-a0ed-b01d15b73432)

I cannot see what the issue is.  I searched for 'mfaConfig..' and only found it in the backend-config.json file.  There were not changes to the previous version that worked fine.  This is blocking me from using the team environments workflow on amplify.  I dont know if I am doing something wrong, or if there is a bug in amplify cli for this workflow.

**Comment by ykethan** [comment]
Hey @dwrynngs, thank you for reaching from the error `>>>>     mfaConfig..` , it appears the git merge has left over `>>>` in the file causing the push to fail.
Could you check the `amplify/backend/backend-config.json` and `amplify/backend/backend/cli-inputs.json` files for the `mfaConfiguration` and ensure this does not contain the arrow as provided in the error?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
