### ISSUE TITLE
New env added was created without storage (s3) and with Pinpoint Analytics disabled

### ISSUE THREAD

**Issue by joshuamoreno1** [aws-amplify/amplify-cli#13818]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.12.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I have a project named nock with a dev environment with Storage (S3) and Pinpoint Analytics Active. 
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/4c00bf7a-0fe9-4310-8664-ac1dc409af6e)

S3 Bucket created:

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/a0e84ec7-0c9e-4931-8a64-909441899d77)

But today I created a prod env with `amplify env add`. All works fine in command line but in AWS did not create a stack to s3 bucket.

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/f2f5c14c-457b-4138-8158-efb3ea3252c3)

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/01c17178-df85-4155-babf-b1b4c79f6792)

When I try to add again in new environment it fails:

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/446758ae-3e7c-4eaa-b33c-512a618a4007)

If I made "amplify status" in commnad line, all I get is "No Changes"

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/ea3f278b-906d-46ec-bb98-e54fa1acb97e)

I have problems also with Pinpoint Analytics, is not working and dev project is configured well, but prod not working.
Dev active:
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/67221708-58a8-4417-aa6b-cd25272f0c07)

Prod disabled:
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/b477b3d2-5f65-4af8-ae40-e11bb2e65b93)

On debug console i got these error:
```
#9      main.<anonymous closure>.<anonymous closure> (package:nock/main.dart:43:7)
<asynchronous suspension>
flutter: ConfigurationError
flutter: ConfigurationError {
  "message": "No Storage S3 plugin config detected."
}
flutter: #0      AmplifyAnalyticsPinpointDart._ensureConfigured (package:amplify_analytics_pinpoint_dart/src/analytics_plugin_impl.dart:51:7)
#1      AmplifyAnalyticsPinpointDart.recordEvent (package:amplify_analytics_pinpoint_dart/src/analytics_plugin_impl.dart:218:5)
#2      AnalyticsCategory.recordEvent.<anonymous closure> (package:amplify_core/src/category/amplify_analytics_category.dart:20:29)
#3      _rootRun (dart:async/zone.dart:1399:13)
#4      _CustomZone.run (dart:async/zone.dart:1301:19)
#5      _runZoned (dart:async/zone.dart:1804:10)
#6      runZoned (dart:async/zone.dart:1747:10)
#7      identifyCall (package:amplify_core/src/http/amplify_category_method.dart:147:10)
#8      AnalyticsCategory.recordEvent (package:amplify_core/src/category/amplify_analytics_category.dart:18:64)
#9      AnalyticsPinpointImpl.recordScreen (package:nock/infraestructure/amplify/analytics_pinpoint_impl.dart:8:29)
#10     AnalyticsMixin.sendAnalyticsScreenView (package:nock/ui/tools/mixins/analytics_mix<…>
flutter: ConfigurationError
flutter: ConfigurationError {
  "message": "Analytics not configured",
  "recoverySuggestion": "Please make sure to call: await Amplify.configure(amplifyconfig)"
}
```
Another things like cognito, graphql api, dynamodb tables and lambda functions works well.
 

### Expected behavior

When Ones creates a new amplifyenvironment storage and analytics project must to be created sucessfull.

### Reproduction steps

1. Create and amplify project with storage and pintpoint analytics
2. Create a new environment

### Project Identifier

3df5115b5daa14eb94ef9b42a1064c90

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by joshuamoreno1** [comment]
Hi there!, Any update? I have not be able to deploy production environment for my app.

**Comment by ykethan** [comment]
Hey @joshuamoreno1, to confirm in the projects `backend-config.json` and `team-provider-info.json` file do you observe references to the resource.
In the `prod` env on running `amplify pull`, does `amplify status` show the storage resource?
Does `amplify update storage` throw any errors?

**Comment by joshuamoreno1** [comment]
Hi there,

Yes, there are references:
### team-provider-info.json: 
Dev:
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/330dac00-c33c-4f6b-a664-7903726f903e)
Prod:
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/fc928be1-80f3-4417-8dae-b3c0ef33960d)

### backend-config.json

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/71842dd6-1084-4188-a4da-9c398a788f59)

But when I run `amplify pull` on `prod` env all works almost well but i see these error:

`Error: File at path: '/Users/dev/projects/nock/amplify/backend/storage/nockstorage/parameters.json' does not exist`

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/7f933745-cbba-491d-825b-d021177d156c)

And when I run `amplify status`: all is `No change`

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/0b80c5c1-a2bf-4ab1-93d4-57da6c77e139)

And when i run `amplify update storage`, I get an error similar to the first one

<img width="909" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/1558591/36e85b19-d296-4881-8980-bd3fceb38438">

**Comment by joshuamoreno1** [comment]
I was trying to fix it running amplify env checkout dev then amplify pull , copy the next file with differences:

File deleted:
![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/0d7aa125-a116-474d-b41e-40e547d4220f)

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/a7e45f5a-8434-4f19-baf2-3020fc0e830d)

And then run amplify push override but i get No changes

![image](https://github.com/aws-amplify/amplify-cli/assets/1558591/557bf948-8137-44fb-bdde-4e4e04ef6553)

**Comment by joshuamoreno1** [comment]
Hi, 

I removed storage in prod env, then add new storage, run amplify push, and all woking.

Its weird have to remove, but is now working well,

Thanks,
