### ISSUE TITLE
Redirection problem with Nextjs application deployed on aws s3 and cloundfront as static application

### ISSUE THREAD

**Issue by saharJ95** [aws-amplify/amplify-cli#13810]
### If applicable, what version of Node.js are you using?

21.6.1

### Amplify CLI Version

12.12.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Create s3 bucket and link it with cloudfornt (custom domain)

### Describe the bug

Redirection problem with Nextjs application deployed on aws s3 and cloundfront as static application

The Apps work fine but when we reload the route except index.html page it lands to home page  i.e. index.html

apps/user/list ---> after reload ---> apps/

### Expected behavior

should land to desired url 

### Reproduction steps

login to app 
route to other routes
refresh

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @saharJ95, thank you for reaching. This appears to be a behavior with the NextJs application, refer to this thread https://github.com/vercel/next.js/discussions/10522 providing additional information on this behavior.
