### ISSUE TITLE
gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Proxy Error

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-cli#13829]
### Amplify CLI Version

12.12.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

i get the the error in the title in the Build phase of the pipeline, are you able to check if there's more information about the error?

### Expected behavior

i expect the build to pass

### Reproduction steps

1. add a Go function
2. use yaml.v3 package

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by redjonzaci** [comment]
after that, i got: `gopkg.in/yaml.v2@v2.2.8: unrecognized import path "gopkg.in/yaml.v2": https fetch: Get "https://gopkg.in/yaml.v2?go-get=1": net/http: TLS handshake timeout`

**Comment by ykethan** [comment]
Hey @redjonzaci, thank you for reaching out. Tried reproducing the issue using the following but did not observe this error.

1. `amplify add function`
2. cd into the function src folder and ran `go get gopkg.in/yaml.v3` to install the package
3. used the example provided on https://github.com/go-yaml/yaml/tree/v3?tab=readme-ov-file#example 
4. then ran `amplify push` and did not observe any errors.

to confirm the reproduction steps provide a `yaml.v3` as package version but the error message suggest the error message on `yaml.v2`. Has the import been updated on the function code?

**Comment by redjonzaci** [comment]
thanks for trying! it seems like it was a transient issue.
