### ISSUE TITLE
Amplify deployment failed

### ISSUE THREAD

**Issue by mysklc** [aws-amplify/amplify-cli#13820]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.10.0

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Manual changes made.

### Describe the bug

Deployment job timed out. 

√ Zipping artifacts completed.
| **Deploying build artifacts to the Amplify Console..Job Timeout before succeeded**
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
🛑 Job Timeout before succeeded

**Resolution:** Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

**Session Identifier:** 74799a23-8921-47a0-8744-0df996e4aa30
**Project Identifier:** 5ad9f6befc532dcb4ac971f083bb35f6

### Expected behavior

Amplify successfully Published! 

### Reproduction steps

Executed the below commands in CLI
- amplify status 
- amplify push
- amplify publish 

### Project Identifier

Project Identifier: 5ad9f6befc532dcb4ac971f083bb35f6

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @mysklc, Does this occur when retrying the publish command? Could you add the `--debug` to the publish command and provide us the output?
Could you let us know the size of the build/dist folders?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
