### ISSUE TITLE
Feasibility of my idea using AWS Amplify Studio

### ISSUE THREAD

**Issue by GraceGreen02** [aws-amplify/amplify-cli#13839]
### Amplify CLI Version

npm v12.12.4

### Question

I have no knowledge about AWS. I have entry level knowledge about low code app development. I would like to build a scheduling and customer relationship management web app that is compatible with multiple devices (computer, phone and tablet). I need to do this in under 2 months. Is AWS amplify studio a good idea to use?

**Comment by ykethan** [comment]
Hey @GraceGreen02, thank you for reaching out. To better assist you, could you provide us your use case?

Amplify Studio is visual development environment to build you backend resources, create UI components and manage your data on your backend resources. refer to Gen 1 [Amplify Studio](https://docs.amplify.aws/gen1/react/tools/console/)  providing additional information on Amplify Studio. 
If this is new application I would suggest exploring our [Amplify Gen 2](https://docs.amplify.aws/react/) which use AWS CDK to build your backend resources and also supports managing your data on the console.

**Comment by GraceGreen02** [comment]
Thank you for your response. I am developing software for a horse riding facility. I want it to be able to schedule lessons and keep records on horses and clients. I only ever developed software in Mendix on a basic level

**Comment by ykethan** [comment]
Hey @GraceGreen02, thank you for the information on your use case. Amplify supports GraphQL API that uses DynamoDB to store your data should assist with your use case.
While I am not used Mendix, you should be able to use Amplify Studio which provides support for creating react components from a Figma file and then use the components in your frontend react application. You can create GraphQL Data models and manage the application data in Amplify Studio.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
