### ISSUE TITLE
cli creating lambda with multiple outdated node versions

### ISSUE THREAD

**Issue by murffious** [aws-amplify/amplify-cli#13831]
### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

18.18

### Amplify CLI Version

12.12.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

in the cloud formation template files I simply used IDE find and replace all to nodejs18.x and it pushed up to the cloud deploying fine. 

find and replace 
nodejs14.x
nodejs12.x

### Describe the bug

I used the amplify cli create various lambdas for auth, api and db triggers. During amplify push many lambda role and other lambda create errors were thrown. I found that the versions were out of date.  I found various outdated versions
nodejs14.x
nodejs12.x
in the cloud formation template files. 
I simply used IDE find and replace all to nodejs18.x and it pushed up to the cloud deploying fine. 

Someone should fix those. super fast. 

### Expected behavior

up to date CLI commands generate templates that have up to date lambda configuration 

### Reproduction steps

use cli to create  a fresh amplify project 
amplify add api 
follow cli prompts to add dynamo, api, auth, triggers with various lambdas  
deploy with push 

### Project Identifier

Project Identifier: d0bb465e41618d37d9d35162d00429a6

running amplify --version 12.12.3. on Mac OS 14.6 Beta (23G5052d) - using nvm node v18.18.0

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by murffious** [comment]
I would be happy to take this issue

**Comment by ykethan** [comment]
Hey @murffious, this is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/10894
with the upgrade path documented on 
https://docs.amplify.aws/gen1/react/build-a-backend/functions/configure-options/#updating-the-runtime
https://github.com/aws-amplify/amplify-cli/issues/10894#issuecomment-1251564540

Closing this as duplicate
