### ISSUE TITLE
Cognito refresh token expiration days inconsistency

### ISSUE THREAD

**Issue by Devashish007** [aws-amplify/amplify-cli#1385]
Hi team, 

According to the Cognito docs (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html), the Refresh token expiration (days). should be able to set to any value between 1 and 3650. 

However when we use the amplify cli to manually set up auth, the maximum value we are able to input for the Refresh token expiration days is capped at 365. As you can see at the last two lines of the amplify cli below: 

```Specify the app's refresh token expiration period (in days): 3650 ```
```>> Token expiration should be between 1 to 365 days. ```

Is this a known issue? I am using the latest build.

**Comment by mobilequickie** [comment]
+1
Agree. This should match the refresh token expiration limit of Cognito.

**Comment by giantGoldfish** [comment]
any update of when will this feature be implemented? thanks
