### ISSUE TITLE
Changes in cloudformation template get reverted when trying to push to the cloud

### ISSUE THREAD

**Issue by DrBallHard** [aws-amplify/amplify-cli#13861]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.12.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I made some changes specifically to the guest access for the getObject action for amplify storage. After updating this in cloudformation-template.json, I attempted to do an 'amplify push' but instead of pushing these changes it only pulls and reverts back to what it was before. It seems like it doesn't recognize these changes I made here:
```
          {
              "Action": "s3:GetObject",
              "Effect": "Allow",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:s3:::",
                      {
                        "Ref": "S3Bucket"
                      },
                      "/public/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:s3:::",
                      {
                        "Ref": "S3Bucket"
                      },
                      "/protected/*"
                    ]
                  ]
                }
              ]
            },
```

### Expected behavior

I expect this change to be recognized and then pushed to the cloud

### Reproduction steps

1. make a change in the getObject policy in cloudformation-template for storage
2. attempt to 'amplify push' these changes

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey, thank you for reaching out. If you are looking to modify the storage config i would suggest using the Amplify overrides to make the changes.
https://docs.amplify.aws/gen1/nextjs/build-a-backend/storage/modify-amplify-generated-resources/ 
Amplify CLI runs a pull before the push ensuring the local copy is in sync with the `current-cloud-backend`, the override provides the capability to modify the CloudFormation template on resources such as auth and storage using cdk.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
