### ISSUE TITLE
Cannot deploy AmplifyExportedBackend

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-cli#13871]
### Amplify CLI Version

12.12.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

`cdk deploy` fails with the following error:
`Error: Parameter with logical ID 'AppSyncApiName' was not found in the template`

### Expected behavior

should deploy

### Reproduction steps

https://docs.amplify.aws/gen1/react/tools/cli/usage/export-to-cdk/

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by redjonzaci** [comment]
tried the following blog post too and got the same error: https://aws.amazon.com/blogs/mobile/export-amplify-backends-to-cdk-and-use-with-existing-deployment-pipelines/

**Comment by redjonzaci** [comment]
any update?

**Comment by ykethan** [comment]
Hey, could you ensure if the `amplify-export-manifest.json` contains the `AppSyncApiName` parameter present with a value.

**Comment by redjonzaci** [comment]
it does, and i made no manual changes to what is generated by amplify export

**Comment by ykethan** [comment]
Hey @redjonzaci, tried reproducing this error with a sample API but could not reproduce this error. If you could share a zip of exported folder on a discord I can try to reproduce the error message and dive into possible mitigation steps.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
