### ISSUE TITLE
Remove dependency on unmaintained node-ip package from amplify-appsync-simulator

### ISSUE THREAD

**Issue by jwilson-anonyome** [aws-amplify/amplify-cli#13890]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v20.16.0

### Amplify CLI Version

2.16.4

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Describe the bug

amplify-appsync-simulator uses the [node-ip](https://github.com/indutny/node-ip) package to get the local IP address, where the simulator may be running.

The node-ip project is abandoned. It has a reported [security vulnerability](https://github.com/indutny/node-ip/issues/150). 

### Expected behavior

Build and run code using amplify-appsync-simulator without encountering failures or warnings due to security vulnerabilities.

### Reproduction steps

yarn audit

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

PR to remove the dependency in https://github.com/aws-amplify/amplify-cli/pull/13877

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
closing this as https://github.com/aws-amplify/amplify-cli/pull/13877 had been merged.
