### ISSUE TITLE
Color output of 'amplify push' CloudFormation progress

### ISSUE THREAD

**Issue by plaa** [aws-amplify/amplify-cli#1389]
**Is your feature request related to a problem? Please describe.**
Pushing always takes a few minutes. Whenever it fails, it's a hassle to browse through hundreds of lines of log to find where it failed the first time to find the issue.  You also don't see at a glance whether the update is still progressing or rolling back due to a failure.

**Describe the solution you'd like**
The CloudFormation progress should be colored based on the CF status. For example `CREATE_COMPLETE` and `UPDATE_COMPLETE` should be green, and `CREATE_FAILED` and `UPDATE_FAILED` should be in red.  Rollback-related statuses should also be colored appropriately.  (Either the whole line or only the status word could be colored.)

This would make it much quicker to find issues.  For example [StackMaster](https://github.com/envato/stack_master) uses this and it's a breeze to scan the logs.

**Comment by yuth** [comment]
@plaa what's the version of Amplify CLI you have. After Amplify CLI  version `1.1.5`, we show the stack error summary if push fails for any reason

**Comment by plaa** [comment]
That's true, but sometimes it also prints many pages which need to be gone through. The coloring would also help to see the progress _while_ the update is going on, see whether the update is progressing or rolling back, and allow starting easier debugging before the rollback has completed.

**Comment by plaa** [comment]
I just had a case where the cli output at the end 23 instances of `Reason: Resource update cancelled` and the real reason was still hidden in the long log.

**Comment by yuth** [comment]
This has been released in Amplify CLI version 1.6.7
