### ISSUE TITLE
"Invalid or unexpected token" when running "amplify graphql-seed run" extension

### ISSUE THREAD

**Issue by matthew-oneill** [aws-amplify/amplify-cli#13899]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.11.1

### Amplify CLI Version

12.12.6 (also tested by reverting to 7.26)

### What operating system are you using?

WSL2 Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When attempting to run the [amplify graphql-seed extenstion](https://www.npmjs.com/package/amplify-graphql-seed-plugin) via the `amplify graphql-seed run` command receiving `Invalid or unexpected token` error. This is occurring both locally and in the remote pipeline. We were previously using the extension without issue. 

Logs do not show any further information. 

### Expected behavior

Extension should run and seed dynamodb tables

### Reproduction steps

Have tested initializing an empty amplify project with the extension and the same error occurs.

1. `amplify init`
2.  `npm install -g amplify-graphql-seed-plugin`
3. `amplify plugin add amplify-graphql-seed-plugin`
4. `amplify graphql-seed init`
5. `amplify graphql-seed run`

### Project Identifier

9a4a8c6a9fba58492d03474835b8b2b3

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @matthew-oneill, thank you for reaching out. Noticed a similar issue on the [amplify-graphql-seed-plugin](https://github.com/awslabs/amplify-graphql-seed-plugin) repository: https://github.com/awslabs/amplify-graphql-seed-plugin/issues/39. As this is a third part plugin I would suggest reaching out on amplify-graphql-seed-plugin repository.
