### ISSUE TITLE
Amplify multi region app

### ISSUE THREAD

**Issue by stam0912** [aws-amplify/amplify-cli#13908]
### Amplify CLI Version

12.12.1

### Question

I need help to deploy the app in multiple regions. I created an Amplify app in ca-central-1 and now I would like to deploy it to ap-northeast-1 (both app sharing the same table).

I created a replica of the table to ap-northeast-1. After that, I created an appsync api using the global table as the data source with CDK and deployed it to ap-northeast-1. How can I create an Amplify app with an existing appsync api?  

I don't know if I'm on the right track. What is the proper way to deploy the app in multiple regions?

**Comment by ykethan** [comment]
Hey @stam0912, thank you for reaching out. I would suggest posting this in our [Amplify discord community](https://discord.gg/amplify) as the community of developers using Amplify may suggest alternatives and their implementation on your use case.

But you can you can utilize the `Amplify.configure` to pass in your existing API and config to reuse your existing or if you have an existing `amplify_configuration.json` you could utilize this to deploy in a new region.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
