### ISSUE TITLE
How to merge envs properly? Getting my team-provider.json overwritten.

### ISSUE THREAD

**Issue by christiansaavedra** [aws-amplify/amplify-cli#13917]
### Amplify CLI Version

12.12.6

### Question

Hello, I've been making changes in git branch develop and amplify env develop. I've pushed them both
Now, to merge these changes to the superior branch and env (staging), I've followed these instructions:  [here](https://docs.amplify.aws/gen1/javascript/tools/cli/teams/sandbox/)

So, I did git checkout staging, git pull, amplify pull staging. However, when i run 'git merge develop', my team-provider.json gets overriden (the only env appearing is the develop one, the staging is completely empited). 

I'm wondering what i am doing wrong and what are the correct procedures to succesfully merge my develop env in the staigng one.

**Comment by ykethan** [comment]
Hey @christiansaavedra, the `team-provider-info.json` contains the env information and metadata for all environments. Is the staging branch built of the main branch?
If the staging branch is build of the main the team provider should contain the main branch record as well. When git merging you will need to ensure the team provider is appended rather overridden.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
