### ISSUE TITLE
[Cognito Lambda Trigger]How to get outputs for parameters.json

### ISSUE THREAD

**Issue by ronaldwidha** [aws-amplify/amplify-cli#1397]
**Which Category is your question related to?**
Across categories, but in my case I was using Function, and Auth

**What AWS Services are you utilizing?**
I was trying to create `post confirmation` trigger in Cogito user pool, and have to make changes to the cloudformation template under auth. I created the triggered lambda function by adding a Function category. 

To hook up the output of the provisioned Function, into the Auth params, I worked out that under the target category (in my case, Auth), I had to do an: 
`Fn:GetAtt: [ "function" + CategoryName ], Outputs.OUTPUT`

This works, which is cool - but I couldn't find any documentation around it. Is this a supported feature? Can I expect this to be a stable behavior?

**Provide additional details e.g. code snippets**

Auth parameters.json
````
    "CognitoUserRegisteredLamdaArn": {
        "Fn::GetAtt": [
            "functionPostConfirmation",
            "Outputs.CognitoUserRegisteredArn"
        ]
    }
````

backend-config.json
````
...
	"function": {
		"PostConfirmation": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true,
			"dependsOn": []
		}
	}
```

**Comment by kaustavghosh06** [comment]
@ronaldwidha That's a good hack and we officially don't support it as a part of the CLI. Having said that, we're actively working on supporting Lambda triggers for Cognito and other categories and you'll have full support for this very soon.

**Comment by kaustavghosh06** [comment]
We've added support for Lambda Trigger support for the dynamo tables managed/added by the CLI using the `amplify add storage` command. Let me know if you find that useful. Please take a look at https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/ for more details.
