### ISSUE TITLE
Projectname contains capital letters - brakes the console build

### ISSUE THREAD

**Issue by zerdos** [aws-amplify/amplify-cli#1398]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
Having a Capital letter in the project name will eventually break the build in the first run.
So ```amplify init```, first question: Enter a name for the project: 
Here if you write something like this: MyAmazingTodoApp, then all directory will be generated with small letters (on Mac or windows), and when it runs on the console, suddenly there will be an errror.

**To Reproduce**
1. Use mac (with not case sensitive filesystem)
2. Project name: myApp
3. Create your app, push it, then try to make it working on the Amplify console.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UnleashedMind** [comment]
@zerdos 
Could you show us the error message? so we can investigate further?

**Comment by kaustavghosh06** [comment]
@zerdos Which version of the CLI are you using? I wasn't able to reproduce the issue with the latest version of the CLI. Please feel free to comment or re-open if you're still seeing this issue.
