### ISSUE TITLE
Cannot prompt error on 'amplify push'

### ISSUE THREAD

**Issue by jasonleenaylor** [aws-amplify/amplify-cli#13982]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13

### Amplify CLI Version

12.13.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

running 'amplify push' returns the status after the pull and then the following error:

 Cannot prompt for [Are you sure you want to continue?] in a non-interactive shell

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: 7e63d115-c303-49cb-9a4c-267ba8dbb65c

### Expected behavior

An actual prompt for continuing is displayed and I am able to push.

### Reproduction steps

1. Run `amplify push` in my existing project where I have made changes to add a new function.

### Project Identifier

efbc991ac28092ea209ab240c0550991

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @jasonleenaylor, thank you for reaching out. Are you using git bash by an chance in windows?
I would suggest switching to powershell or CMD to mitigate the issue.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
