### ISSUE TITLE
 Changes Not Detected in AWS Stack During UPDATE_IN_PROGRESS State

### ISSUE THREAD

**Issue by azadvt** [aws-amplify/amplify-cli#13999]
### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

v18.17.0

### Amplify CLI Version

12.13.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

 Our team is experiencing an issue where changes push to amplify it  is not being detected during the UPDATE_IN_PROGRESS state. Despite making modifications to the stack, the deployment process fails to recognize these changes and does not update the environment as expected.

https://github.com/user-attachments/assets/7e69ad41-ddf8-482b-a8ee-eace0a8ff5f8

![letest one](https://github.com/user-attachments/assets/c5bd1ceb-fecc-444c-93c3-10610ed64e1c)

### Describe the bug

Make changes to the AWS stack configuration (e.g., in a CloudFormation template).
Deploy the stack and initiate an update.
Observe that the stack enters the UPDATE_IN_PROGRESS state but does not apply or recognize the recent changes.

### Expected behavior

Expected Behavior: The AWS stack should detect and apply all recent changes during the update process.

### Reproduction steps

Run amplify pull to pull the latest environment setup in an empty directory.
Make any changes to the Amplify backend (e.g., modify a parameter in a resource configuration file).
Run amplify push to deploy the changes.

### Project Identifier

[report-1730106208042.zip](https://github.com/user-attachments/files/17540006/report-1730106208042.zip)

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @azadvt, thank you for reaching out. Could you provide us some additional information on the changes made on the resources(ex: lambda, api) during the deployment?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
