### ISSUE TITLE
Error NoSuchBucket after adding CNAME for custom domain

### ISSUE THREAD

**Issue by jugglingcats** [aws-amplify/amplify-cli#1401]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Custom domains

** What AWS Services are you utilizing? **
S3, CloudFront

** Provide additional details e.g. code snippets **
Created vanilla React app, added hosting, published. Site works using CloudFront url.

Added CNAME for my hosted zone to CloudFront host. Got following error:
```
Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>www.pupildiary.com</BucketName>
<RequestId>F1A86D44ECF44775</RequestId>
<HostId>
tbrL/dElfj8zPI+F6XcDUEGpaqO1/P1aHr6VM3TdZ3LaUhZmuR7TQMWFkasFSL+Ymyg5vm8OF2M=
</HostId>
</Error>
```

Manually added my hostname to alternate names in CloudFront. No change.

Main questions:
- Why isn't it working?
- How to add SSL config to amplify
- How to add alternate CNAMEs to amplify

Thanks!

**Comment by jugglingcats** [comment]
Just re-read the error and www.pupildiary.com is not the correct bucketname -- it is not the name of the bucket created by Amplify. I used the default without the timestamp so my bucketname is `pupildiary-hostingbucket-default` ('default' is the name of the env I created with amplify CLI).

I have read elsewhere that when CNAMEing to Cloudfront your bucket name has to match your sitename. Is there a way to modify the bucket name created by amplify CLI? And if not, perhaps I have to delete and re-create my amplify project, but then how can I prevent amplify adding the env to the bucket name?

Thanks

**Comment by jugglingcats** [comment]
I ran `amplify delete` and started again. This time I specified `www.pupildiary.com` as the bucket name and published. It created a bucket named `www.pupildiary.com-prod` (where prod is my env name).

I had to manually add my SSL cert and the alternate domain name in the CloudFront config. I hope this is not going to get blown away on each publish.

Anyway it is working now. Am wondering if I did something different the first time around, because it doesn't seem logical to me it would prefer the new bucket name to the old one!

**Comment by UnleashedMind** [comment]
Thanks for your feedbacks @jugglingcats 
If your modification on the CloudFront config is in the amplify/backend/hosting/S3AndCloudFront/template.json, and it's been successfully pushed, subsequent pushes will not change that file. So you should be good. 
I will mark this as an enhancement to see if we can do something the CLI to make this setup easier for the customers.

**Comment by jugglingcats** [comment]
It would be good to confirm if the hostname-as-part-of-bucket-name is really a requirement. If it is, would be good to point this out in the prompt for bucket name.

Would be great too if alternate name (CNAME) could be part of the amplify CLI prompts/config, and even the link to SSL cert.

**Comment by kaustavghosh06** [comment]
@jugglingcats You might want to try out Amplify Console- https://aws.amazon.com/amplify/console/ for your Hosting needs which has in-built support for custom domains.
