### ISSUE TITLE
Amplify codegen giving error -Invalid or incomplete schema, unknown type: AWSModelQueryMap. Ensure that a full introspection query is used in order to build a client schema.

### ISSUE THREAD

**Issue by BBopanna** [aws-amplify/amplify-cli#14010]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.18.0

### Amplify CLI Version

12.13.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

NO

### Describe the bug

amplify codegen is giving the below error from today for now reason - we did not change anything in our schema and yet this error and does NOT generate the models, queries, mutations etc

➜   amplify codegen
✔ Downloaded the schema
Invalid or incomplete schema, unknown type: AWSModelQueryMap. Ensure that a full introspection query is used in order to build a client schema.

### Expected behavior

codegen should successfully generate models, queries, mutations

### Reproduction steps

run the below command

amplify codegen

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ilfoxo** [comment]
Same for me!, i have many amplify projects. Today in one of them I ran "amplify codegen" and get the same error.

I tried with another project that i havent modified the code in many days (and was working) and got the same error.

Here my src/graphql/schema.json
[schema.json](https://github.com/user-attachments/files/17691740/schema.json)

OS: Windows 11
Node: 20.12.2
Amplify: 12.13.0

**Comment by peimarAVL** [comment]
We also receive following error for node version v21.6.1 :

The command we are running is: `npx @aws-amplify/cli codegen add --apiId XYX --region xx-central-x`

`"Invalid or incomplete schema, unknown type: AWSModelQueryMap. Ensure that a full introspection query is used in order to build a client schema."`

**Comment by Dennis-Dekker** [comment]
same here

**Comment by FernandoI7** [comment]
Same here:

Node: 18.20.4
Amplify: 12.10.3

**Comment by FernandoI7** [comment]
This should be raised as critical, because is breaking all pipelines

**Comment by BBopanna** [comment]
These jokers at AWS - Amplify have the least professional etiquette IMHO as they simply dont care - when the entire community is hit by this error - no response yet.

This is what addressed for us - Credit to (Nishant B) from internal developer support team who asked us to try these 

>> amplify codegen remove
>> amplify codegen add 
>> amplify codegen
>> amplify api gql-compile 
>> amplify codegen

you will notice that below changes in .graphqlconfig.yml

 projects:
   wfGraphQLAPI:
-    schemaPath: src/graphql/schema.json
**+    schemaPath: amplify/backend/api/wfGraphQLAPI/build/schema.graphql**
     includes:
       - src/graphql/**/*.ts
     excludes:

AND

        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
**_+        region: ap-south-1
+        apiId: null_**
        maxDepth: 3
extensions:
  amplify:

**Comment by phani-srikar** [comment]
The fix has been deployed to impacted regions. Please try running the `amplify codegen` and share your region information if you are still facing this issue.

**Comment by ykethan** [comment]
Closing the issue as a fix has been deployed and verified.
