### ISSUE TITLE
Error deploying resources: Access denied for 'DescribeKey' on AWS::KMS::Key

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/amplify-cli#14022]
### Describe the bug

I'm encountering an error when attempting to deploy resources using amplify push with the latest Amplify CLI. The error message is: "Unable to retrieve Arn attribute for AWS::KMS::Key, with error message Access denied for operation 'DescribeKey'."

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create AWS KMS using custom resources in Amplify.
2. Create Lambda functions that depend on KMS to decrypt existing secret.
3. Run amplify push to deploy the resources.
4. Observe the error message related to KMS permissions.
```

### Expected behavior

The resources should deploy successfully without encountering permission issues.

### Amplify Framework Version

2.44.0

### Amplify Categories

API, Auth, DataStore, Storage

### Dependency manager

Swift PM

### Swift version

6.0.2

### CLI version

12.13.1

### Xcode version

16.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 18.1

### Device

iphone 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ykethan** [comment]
Hey @rohit3d2003, thank you for reaching out. 
When creating custom resources using Amplify CLI, the CLI may require additional permissions outside the Amplify managed policy, [AdministratorAccess-Amplify](https://console.aws.amazon.com/iam/home#policies/arn:aws:iam::aws:policy/AdministratorAccess-Amplify). Please refer to the Amplify [IAM Policy](https://docs.amplify.aws/gen1/react/tools/cli/reference/iam/) documentation for additional information regarding the necessary permissions for Amplify CLI and for more information on providing additional permissions to your Amplify CLI IAM user refer to [AWS IAM User](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html#users_change_permissions-add-directly-console) documentation.

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
