### ISSUE TITLE
How to delete an env only locally if no more exists?

### ISSUE THREAD

**Issue by realtebo** [aws-amplify/amplify-cli#14025]
### Amplify CLI Version

11.0.0

### Question

I have a lot of envs locally. 
But a lot of them don't exist anymore

How to delete?

```
% amplify env list

| Environments |
| ------------ |
| *prod        |
| newprod      |
| newestprod   |
| provaprod    |
| staging      |
```

```
% amplify env remove provaprov
🛑 Environment name is invalid.
```

Please note: In my ``amplify/team-provider-info.json`` i only have `prod` and `staging`

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue
