### ISSUE TITLE
Amplify project no longer able to Deploy

### ISSUE THREAD

**Issue by mcnamara-charles** [aws-amplify/amplify-cli#14021]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.9.0

### Amplify CLI Version

12.13.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Starting today I've been having major issues with the amplify CLI. I use git for my project and I pushed from my laptop to my desktop, I ran amplify init when I got to my desktop and then ran `amplify pull --appId <app-id> --envName dev` to get my most recent changes. Everything in the cloud is currently working just fine. I made one little change to a lambda function and then tried to push and it told me that in many of my functions, the lambda layer I have (for psycopg2) was not found in their template. So I took steps to resolve this (even though there was no issue in the template) and then when I attempted to push it told me none of my functions were in my API's template. So I tried a bunch of other things and now I'm at the point where the error just says this:

🛑 The following resources failed to deploy:
🛑 Resource is not in the state stackUpdateComplete

That's so non-descript it's not even funny

### Expected behavior

I expected my infra to deploy.

### Reproduction steps

I have absolutely no idea how to reproduce this. I'm on gen 1 by the way

### Project Identifier

26d75bb160ce71aa8ff4caf8ac89271c

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by mcnamara-charles** [comment]
Okay, so I went back to my laptop and ran another `amplify push` and then ran amplify pull env command on my desktop again and it seems to be working. But this doesn't really identify what the problem was and it's not the first time I've seen this issue and I've seen it numerous times from other people reporting it

**Comment by Emesilver** [comment]
It seems that the amplify cannot access parameters created by other users than the amplify deploy user with this new version (12.13.1):

2024-11-19T12:17:15.905Z [INFO]: 🛑 Failed to download the following parameters from ParameterStore:
/amplify/d1ypv0tlz1seb0/stg/AMPLIFY_function_profile_appealOperatorEmails

I got this message on all parameters that I created manually with another user other than Amplify Deploy user.

**Comment by ykethan** [comment]
Hey @mcnamara-charles, thank you for reaching out. Could you try adding `--debug` to the pull command which should provide additional information such as stack trace to further dive into this.

@Emesilver refer to the documentation providing additional information on this
https://docs.amplify.aws/gen1/react/tools/cli/reference/ssm-parameter-store/

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue.
