### ISSUE TITLE
I have delete a api, now i want to undo the operation.

### ISSUE THREAD

**Issue by hafizali05** [aws-amplify/amplify-cli#1402]
** Which Category is your question related to? **
amplify add and remove api
** What AWS Services are you utilizing? **
AWS APPSYNC amplify api remove
** Provide additional details e.g. code snippets **

1: I have added an api
2. i made the changes to the api but havent pushed the changes
3. i didnt like the stuff i did in there and so i deleted it.
3. its as shown in the image.
4 now i want to undo the operation which says remove.

how do i do that.

P.S i havent done amplify push yet.

![image](https://user-images.githubusercontent.com/10105388/57180365-de3dba00-6e7f-11e9-8436-59cea6b6aa0d.png)

**Comment by UnleashedMind** [comment]
@hafizali05 
Just want to get exactly what happened. You've created and pushed your api before, and the api related resources have already been created in the cloud, right? 
Then you made local changes without pushing them to the cloud, but you don't want to keep those local changes.

**Comment by hafizali05** [comment]
I did amplify pull --restore and it was back to what I wanted.

**Comment by JoeLamptey** [comment]
I had a similar challenged but I resolved it by copying and replacing my #current_cloud_backend folder with the backend folder. In my case, the locally served app was faultless so check again before you follow this approach.
