### ISSUE TITLE
Bug: Latest Amplify cli does not work on multiple docker images

### ISSUE THREAD

**Issue by munch9** [aws-amplify/amplify-cli#14028]
### How did you install the Amplify CLI?

npm install -g @aws-alpine/cli

### If applicable, what version of Node.js are you using?

16/18

### Amplify CLI Version

12.13.1

### What operating system are you using?

Amazon Linux/Ubuntu/Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

In Alpine Install runs as if successful but no commands execute. 
Other OS's commands hang including amplify -v

### Expected behavior

Commands should execute correctly

### Reproduction steps

For Alpine 16/18/20
docker run -it node:20-alpine sh

Inside docker
npm install -g @aws-amplify/cli
amplify --version
amplify init

OR for non Alpine the same steps however commands hang indefinitely

### Project Identifier

N/A

### Log output

N/A

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @munch9, thank you for reaching out. This is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/10295.
currently support platforms
https://github.com/aws-amplify/amplify-cli/blob/7fbf29f56eb7335d20de0b5526fbed7795a2af09/packages/amplify-cli-npm/binary.ts#L22C1-L48C13

closing this issue as this is currently being tracked on https://github.com/aws-amplify/amplify-cli/issues/10295
