### ISSUE TITLE
Error Initializing AWS Amplify Environment: "Cannot read properties of undefined (reading 'securityType')

### ISSUE THREAD

**Issue by albiorixvimal** [aws-amplify/amplify-cli#14034]
### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.0

### Amplify CLI Version

12.13.1

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

I'm encountering an error while trying to initialize or configure my AWS Amplify environment. I am getting the error in amplify cli build.

What I've Tried:
Verified the contents of the aws-exports.js file:

Questions/Help Needed:
What could be causing the securityType property to be undefined?
Is there a specific step I’m missing during Amplify initialization or configuration?
Should securityType be automatically generated in the aws-exports.js file?

Any assistance or guidance would be greatly appreciated. Thank you!

### Expected behavior

Build should run sucessfully

### Reproduction steps

1. I attempted to initialize Amplify using the CLI (amplify init or amplify pull).
2. Integrated the configuration in my project (aws-exports.js) using Amplify.configure().
3. Ran the application or backend configuration process, which resulted in the above error.

### Log output

Updated to the latest versions of aws-amplify
The error message is as follows:
```
2024-12-06T07:01:04.780Z [WARNING]: - Fetching updates to backend environment: amplifydev from the cloud.
2024-12-06T07:01:08.775Z [WARNING]: - Building resource api/generateModels
2024-12-06T07:01:09.964Z [WARNING]: ✔ Successfully pulled backend environment amplifydev from the cloud.
2024-12-06T07:01:11.381Z [INFO]: :white_check_mark:
2024-12-06T07:01:13.020Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2024-12-06T07:01:14.046Z [WARNING]: - Initializing your environment: amplifydev
2024-12-06T07:01:17.976Z [WARNING]: - Building resource api/generateModels
2024-12-06T07:01:19.114Z [WARNING]: ✔ Initialized provider successfully.
2024-12-06T07:01:23.023Z [WARNING]: ✖ There was an error initializing your environment.
2024-12-06T07:01:23.028Z [INFO]: :octagonal_sign: Cannot read properties of undefined (reading 'securityType')
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @albiorixvimal, could you try adding `--debug` to the command and provide us the output? This should provide us some additional information such as stack trace

**Comment by albiorixvimal** [comment]
I have already given output with the debug command. you can see my amplify.yml file. see the attached screenshot.

![image](https://github.com/user-attachments/assets/00406b70-b7f4-4a3c-8e81-7df64d14a610)

**Comment by ykethan** [comment]
@albiorixvimal thank you for the getting back on this. On Amplify console, could you add the `AMPLIFY_ENABLE_DEBUG_OUTPUT` as `true` environment variable, this should enable the debug output on the command.
https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

additionally, could you provide us some information on the project, such as resources created in the project(API with auth modes, auth etc)?
Does this error also occur locally when running push or pull? could you run `amplify diagnose --send-report` and provide us the project identifier?

**Comment by ykethan** [comment]
Hey @albiorixvimal, thank you for the information. From the trace appear to be coming from the graphQL API transformer and noticed the key is referred from the `amplify-meta.json` file.
https://github.com/aws-amplify/amplify-cli/blob/b8b6498a350639d6bb798d6fcea167481a3718ae/packages/amplify-provider-awscloudformation/src/upload-appsync-files.js#L62-L72

Is the project using a GraphQL API using v1 transformer version? could you provide us the `cli.json` under the amplify folder? 
In your local project, `amplify/backend/amplify-meta.json` file in the api -> outputs object do you observe a key with `securityType`?

additionally, noticed a similar issue here: https://github.com/aws-amplify/amplify-cli/issues/1162#issuecomment-478671794
could you review the comment and let us know if this mitigates the error?

**Comment by albiorixvimal** [comment]
Updating the backend-config.json file with the comment you mentioned - https://github.com/aws-amplify/amplify-cli/issues/1162#issuecomment-478671794

```
"output": {
    "securityType": "AMAZON_COGNITO_USER_POOLS"
}
```
worked initially, but now I’m encountering a new error: graphql.schema not defined after applying these changes.

Now, I encountered an issue where I 
```
couldn’t find the schema at amplify/backend/api/generateModels/schema.graphql
```
 because there is no folder named generateModels in the api directory. However, after adding this output setting, the generateModels folder is created inside api, and due to that it looking for the schema and it causing issue.

I’m unsure whether this folder is autogenerated or if I need to make manual adjustments. I’m relatively new to Amplify and would appreciate guidance.

Here’s my current backend-config.json file:
```
"generateModels": {
    "output": {
        "securityType": "AMAZON_COGNITO_USER_POOLS"
    },
    "providerPlugin": "awscloudformation",
    "service": "AppSync"
}


```

here is cli.json as asked

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false,
      "respectprimarykeyattributesonconnectionfield": false,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": false
  }
}
```

Questions:
1. Is the generateModels field autogenerated? When I tried removing generateModels from the backend-config.json, it resulted in additional errors.
2. Could this securityType error be caused by changes in the latest version of Amplify?

**Comment by ykethan** [comment]
Glad to hear you were able to get this working. Closing the issue, do reach out if you require any assistance.
