### ISSUE TITLE
Failed build with amplify 1.6.6 and 1.6.7 in amplify console

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#1405]
**Describe the bug**
I'm getting the following error when running a build in the amplify console:

UPDATE_FAILED               GraphQLSchema                                            AWS::AppSync::GraphQLSchema Tue May 07 2019 00:09:06 GMT+0000 (UTC) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: F1A086E29BF333A1; S3 Extended Request ID: PYsiwinp7zph2JKu73c9YWkrswU7c0IBvrboFYzQUCb7n5a4gB9JnkexFezrexH9cAHxegWl6iA=)
                                 UPDATE_ROLLBACK_IN_PROGRESS blahblah-webapp-20190104232321-apislxgql-GGSVPLIA37NS AWS::CloudFormation::Stack  Tue May 07 2019 00:09:07 GMT+0000 (UTC) The following resource(s) failed to update: [GraphQLSchema].

**To Reproduce**
1. I'm not sure how to reproduce, but I know that I had a successful build Started at
5/6/2019, 12:53:53 PM

Every build after that has not worked and failed with the same error above.  The earliest failed build was Started at
5/6/2019, 7:06:41 PM

The most recent failed build was Started at
5/6/2019, 10:34:35 PM

I have manually installed amplify version 1.6.6 and 1.6.7 (which was published earlier today) with no luck.

Example:
#Starting phase: preBuild
#Executing command: npm i -g @aws-amplify/cli@1.6.6

**Expected behavior**
Would expect this to work.  it doesn't appear to be tied to a version of the amplify CLI specifically, as the build from earlier today that succeeded was using 1.6.6.  And since reverting to 1.6.6, it still fails...  

Did something change regarding appsync or cloudformation that may have caused this?

I have no changed anything with the API or backend configuration between the successful build earlier today and any of the failed ones.  I had only updated frontend (React) components.

Thanks for any advice.

**Comment by garyleefight** [comment]
@mwarger Could you send an email to aws-amplify-customer@amazon.com with you appArn?

**Comment by tbouron** [comment]
Just updated amplify CLI to 1.6.8 and I experience the same error. My AppSync configuration hasn't change and even though I do a `amplify function push`, I still can see the following in the logs:
```
UPDATE_FAILED GraphQLSchema AWS::AppSync::GraphQLSchema Wed May 08 2019 00:31:25 GMT+0100 (British Summer Time) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 1926A3499601CD8C; S3 Extended Request ID: yYW5zgcZPSGdxXpOzcO6ldjoMIuN8Ku76hAhPdZx/bd1hlb8/inyqpdV0eZdnLAc6NEuuxOGEl8=)
```

**Comment by tbouron** [comment]
Reverting to previous version of the CLI doesn't help (tried `1.6.7`, `1.6.6` or `1.6.5`)
Prior to updating the CLI, I was using `1.6.5` and it worked fined.

I'm now blocked: I cannot update my production application because of this!

**Comment by mwarger** [comment]
@garyleefight sent.

**Comment by garyleefight** [comment]
Hi, @mwarger @tbouron.
We found the issue is caused by a recent cli release. We changed the way we calculate the hashKey in order to fix a bug. What you can do is to force a one time update to API category. The easiest way is to add a space or comment to your `schema.graphql` file and then do an amplify push.

**Comment by mwarger** [comment]
Will give this a shot and report back. Thank you.

**Comment by tbouron** [comment]
@garyleefight I can confirm that modifying slightly the `schema.graphql` worked, thanks for the tip! 👍

**Comment by mwarger** [comment]
This worked for me as well. Thanks!

**Comment by oliverandersencox** [comment]
This has popped up for me out of nowhere. Im on the most recent version of amplify and simply added a field "currency" to a model. 

> Resource Name: arn:aws:appsync:eu-west-1:412541719178:apis/oa5z6sqzqnftzotyfqy3umdwpq/types/Query/resolvers/searchElasticRepeatedEvents (AWS::AppSync::Resolver)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A412541719178%3Astack%2Famplify-culture-app-dev-163322-apicultureApp-LLKPZYKA4FIS-CustomResourcesjson-AXJOMVAHQF0I%2Fb1de15c0-0198-11ea-893f-0a9c21152684/events


Resource Name: arn:aws:appsync:eu-west-1:412541719178:apis/oa5z6sqzqnftzotyfqy3umdwpq/types/Query/resolvers/searchElasticEvents (AWS::AppSync::Resolver)
Event Type: update
Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 751ABFC936DEBA16; S3 Extended Request ID: kJN9lnaXRMBZIXTkJqOBiKF4wXigRSY8U6MyMAui+hZ6IQAjgmP1ybOLB+CWig6Bv8JGMsnid3M=)
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A412541719178%3Astack%2Famplify-culture-app-dev-163322-apicultureApp-LLKPZYKA4FIS-CustomResourcesjson-AXJOMVAHQF0I%2Fb1de15c0-0198-11ea-893f-0a9c21152684/events

**Comment by slaat** [comment]
> Hi, @mwarger @tbouron.
> We find the issue is caused by a recent cli release. We changed the way we calculate the hashKey in order to fix a bug. What you can do is to force an one time update to API category. The easiest way is to add a space or comment to your `schema.graphql` file and then do an amplify push.

This is not a reasonable solution for this problem. I just faced it and did not know what to do until I found this "solution". Will there be another, maybe a more sustainable, solution anytime?

**Comment by IsaacTrevino** [comment]
`Resource Name: XXXXXXXXGraphQLSchema (AWS::AppSync::GraphQLSchema)
Event Type: update
Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: XXXXXXX; S3 Extended Request ID: XXXXXX
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-X#/stacks/XXX/events`

given the XXX is my attempt to cover confidential info. I have the following resources,
`| Category | Resource name        | Operation | Provider plugin   |
| --------   | --------------------   | ---------      | ----------------- |
| Storage  | S3AMPLIFY               | Create        | awscloudformation |
| Auth       | userPoolGroups       | No Change | awscloudformation |
| Auth       | MYAMPLIFYAUTH    | No Change | awscloudformation |
| Function | AdminQueriesXXXX | No Change | awscloudformation |
| Api          | AdminQueries         | No Change | awscloudformation |
| Api          | GRAPHQL                | No Change | awscloudformation |`

I believe it is due to the fact I am using dataStore as well, I just updated to 4.21.4
Using Node12.X

**Comment by slaat** [comment]
You have to make a change in the `schema.json` of the referenced graphql api. That worked out for me, but that means that **every time** I am changing something in my function I have to change something in the graphql schema. This in turn causes the `amplify push` to take very long making pushing to the server very tedious even if it is a minuscule change...

**Comment by jeffpball** [comment]
> Hi, @mwarger @tbouron.
> We find the issue is caused by a recent cli release. We changed the way we calculate the hashKey in order to fix a bug. What you can do is to force an one time update to API category. The easiest way is to add a space or comment to your `schema.graphql` file and then do an amplify push.

This just worked for me after struggling for two days to `amplify add auth` and `amplify push`. If anyone else is trying to add authentication to a react-native app using aws amplify this is the fix.
