### ISSUE TITLE
I only get back 10 connected items

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1411]
I have the following schema with a @connection between them.
```
type Swipe
  @model
{
  id: ID!
  owner: String
  recipe: Recipe! @connection
  liked: Boolean!
  group: Group @connection(name: "GroupSwipes")
  timestamp: AWSDateTime
}



type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}
```

When I run the generated `GetGroup()` like this:
```
this.apiService.GetGroup(this.groupID).then(query => { console.log(query.swipes.items)});

```

I get a maximum of 10 results back not more.
How do I control this limitation?

**Comment by vparpoil** [comment]
If you look into `amplify/backend/api/<apiName>/build/resolvers/Group.GetGroup.req.vtl` you will see that the first line is setting the limit for you to 10 because you are not telling AppSync the limit to use:
```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
```
Hence, if you need more items, pass the limit argument to your query.  More info [about the resolvers programming language here ](https://docs.aws.amazon.com/en_en/appsync/latest/devguide/resolver-mapping-template-reference-programming-guide.html)

**Comment by sprucify** [comment]
I don't have a `Group.GetGroup.req.vtl` resolver.
In Group.swipes.req.vtl I see a limit of 10 created.

And my generated function `GetGroup()` has only one parameter ìd`

```
async GetGroup(id: string): Promise<GetGroupQuery> {
    const statement = `query GetGroup($id: ID!) {
        getGroup(id: $id) {
.....
```

**Comment by mikeparisstuff** [comment]
@sprucify You need to parameterize your GraphQL query to suit your needs. The GraphQL codegen will auto-generate the basic queries/mutations but you have full control to add your own. Add a query like this to the directory containing your project's GraphQL query files.

```graphql
query GetGroupWithSwipes($id: ID!, $swipeLimit: Int) {
  getGroup(id: ID!) {
    id
    # ... any other fields
    swipes(limit: $swipeLimit) {
      items {
        id
        liked
      }
    }
  }
}
```

Then when you generate the API service file from the queries, it will be parameterized to accept both an id and swipeLimit.

**Comment by sprucify** [comment]
I ended up copying the generated GroupSwipes resolver to the resolver folder and fill in a fixed limit.
I didn't know I had also control over the queries. 

Thanks
