### ISSUE TITLE
amplify add tracking

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1412]
**Is your feature request related to a problem? Please describe.**
I frequently find myself going to third parties to add basic tracking in my apps. AWS Amplify is such a great and all encompassing tool. Wouldn't it be great if it would offer basic tracking?

**Describe the solution you'd like**
The command could look like:

```bash
amplify add tracking
```

and it would either

1. Enable a dashboard in the AWS console, or
2. Create routes and resolvers for tracking data.

Both solutions should show you:

1. Which user logged on how often over a given period of time.
2. Which user created which objects in the API.
3. Which user invoked which lamda function.

These three things alone would cover a lot of tracking needs (at least for early stage startups).

**Describe alternatives you've considered**
The alternative is to write these routes yourself, but then again you could use a (potiontially expensive) third party service.

**Comment by UnleashedMind** [comment]
@janhesters 
The existing analytics category does allow your app to track user activities. 
https://aws-amplify.github.io/docs/js/analytics

**Comment by janhesters** [comment]
@UnleashedMind Aaah I didn't know this. I will look into this and see if I can achieve the most basic tracking tasks with it. Thank you very much :)
