### ISSUE TITLE
Please provide a command to regenerate build directories

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1413]
**Is your feature request related to a problem? Please describe.**
If I run amp pull --restore by mistake after merging in branch changes (I think this is what I did) then I can get into a state where my build folders are wiped out.

**Describe the solution you'd like**
An amplify command to regenerate all the generated content based on the checked in code

It's extremely frustrating when I merge in a branch that adds storage then I can get into a state where I can't deploy that storage.

**Comment by renebrandel** [comment]
Hi - I'm closing this issue as it didn't get much traction. If we see more awareness for this feature in the future, please re-open a new issue or @-mention me here.
