### ISSUE TITLE
Correct procedure for amplify configure project for multiple hosted front ends.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-cli#1416]
I've got a project that requires multiple front ends... 

** Which Category is your question related to? **

Amplify-cli awscloudformation configure project.

** What AWS Services are you utilizing? **

Amplify-cli awscloudformation configure project.

** Provide additional details e.g. code snippets **
I have a project that is an administrative style of site that adds users, updates users, adds projects, data, etc... and I have multiple front ends that all use that same auth, api, storage... but not hosting. The other front ends need to be running on various other hosts.

What's the exact method of doing this... I've copied the amplify, src/graphql and awsexports.js to my new project, and I ran amplify configure project. Should I run amplify remove hosting first in that project, then amplify add hosting, or what's the exact procedure... It's just, the admin site is live right now, and I can't have it break from hosting removal.

**Comment by UnleashedMind** [comment]
Hosting is part to the backend resources for your project, if I'm understanding you correctly, you should not remove hosting, it will affect other frontend projects that are using the hosting. 
The Amplify CLI does not directly support this type of project setup at this moment, you can give this workaround a try: 
1. Use the Amdin project with the Amplify CLI to setup all the shared backend resources, get the aws-exports.js file from it, and insert it into the other projects as share-aws-exports.js, and use that to configure the Amplify library for them to use the shared backend resources. 
2. In each of the frontend projects, use Amplify CLI to init and setup the hosting for the particular frontend project.

**Comment by michaelcuneo** [comment]
Regardless of how it's meant to function... it does support this functionality it's written in the docs. I followed the docs partially and got it working by accident, somehow, but I cannot replicate.

I have a full project that I was working on... with Auth, Hosting, API, and Storage. I copied Amplify from that project to a new project, which needed to use the same resources, except hosting. I performed some kind of combination of setting up the new project using amplify configure project and removal of hosting, and re-adding hosting... and it works fine. I have two projects side by side, both sharing the entire back end I set up initially... but both have different hosting. So I know it definitely works. I just forget the procedure.

`The amplify configure project command is an advanced command and not commonly used for getting started or individual development projects. The command should be used in the following cases:

When wanting to modify the project and AWS configurations set during the amplify init step
When sharing your backend infrastructure code with multiple frontends`

The second part of this documentation is my use case... sharing the backend infrastructure code with multiple frontends... the whole purpose of multiple front ends is multiple hosting... otherwise how are they even multiple frontends? They can't all be hosted in the one spot.

**Comment by michaelcuneo** [comment]
Once I test and get the correct procedure, I'll push up the instructions.

**Comment by UnleashedMind** [comment]
`multiple frontends` means different types of frontends, like web, android or ios. 
The hosting category, when added, inserts  a nested child Cloudformation stack into the project's roost stack, and they work as a whole, if you remove hosting, you remove its nested stack from the project's root stack. 
When I said "The Amplify CLI does not directly support this type of project setup at this moment" in my previous reply, I meant currently you can not add multiple hosting buckets inside the hosting category, so there's only one hosting bucket associated with your project.

**Comment by michaelcuneo** [comment]
So, that means if I go backwards a bit and have a look at the two projects I have running side by side... theoretically one of their hosting buckets will not work? But... if I change a detail or two in the app (Version Number), and hit amplify publish -c on both... both one of them doesn't push up like it did yesterday... I not get a configuration issue.

`2019-05-10T00:32:11.574Z - error: uncaughtException: Cannot read property 'accessKeyId' of undefined.`

So something has obviously messed up anyway. So if I just make an administrative amplify project with all of the important stuff I need enabled and working... then just copy the exports out to each project and pull it in like normal without the amplify config... all will work? I just have to copy the build project up manually to the S3 for each individual app yeah? Sounds like a decent solution.

**Comment by kaustavghosh06** [comment]
@michaelcuneo That's correct. You would jut need to keep the aws_exports.js or the awsconfiguration.json file in sync with your multiple frontend projects.

**Comment by michaelcuneo** [comment]
Thanks for your help... I remember using awsexports ages ago for multiple projects, and for some reason it didn't occur to me, to just do that, it's working fine.
