### ISSUE TITLE
Add ability to set on demand for DynamoDB table added via Storage

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1417]
**Describe the solution you'd like**
Default DynamoDB tables to on demand with configuration to support provisioned throughput like GraphQL support has.

**Additional context**
#561 added this for GraphQL but not DynamoDB tables added via `amplify add storage`.

**Comment by UnleashedMind** [comment]
Thanks @et304383  for the feedbacks, we will review it in the team.

**Comment by ajhool** [comment]
I believe this feature is currently available by adding this field to your `amplify/backend/api/{YOUR_API_NAME}/parameters.json`:

```
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
```

example parameters.json:

```
{
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "AppSyncApiName": "myapi",
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "authmycustomer",
            "Outputs.UserPoolId"
        ]
    }
}
```

**Comment by NutterzUK** [comment]
Just a heads up that I am looking to work on this and make a pull request. I'm entirely new to the amplify project, but feel that this is somewhere I can contribute, as I am facing the same issue. @UnleashedMind @et304383.

**Comment by NutterzUK** [comment]
This should be fixable by merging: https://github.com/aws-amplify/amplify-cli/pull/4076

**Comment by ykethan** [comment]
This has been address with the override functionality for storage category. Please refer to https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-dynamodb-tables for additional information.
