### ISSUE TITLE
Add auth role configuration for DynamoDB table added via Storage just like S3

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-cli#1418]
**Describe the solution you'd like**
Just like is done when S3 is added via `amplify add storage` adding a DynamoDB table should also update the authRole to set permissions based on the cognito identity.

**Additional context**
For reasons I won't get into, I do NOT want to use AppSync.  Having the JS SDK write directly to DynamoDB just like S3 is a perfectly acceptable practice and Amplify should fully support this.

https://aws-amplify.github.io/docs/js/storage seems to make zero mention of the DynamoDB option when adding storage.  Is this even supported?  If not, please drop it from the Amplify CLI.

**Comment by undefobj** [comment]
Thank you for the feedback @et304383. We most likely would not add this feature to the DynamoDB piece of the Storage category as one of the goals of Amplify is to guide customers towards Best Practice patterns as it's easy to get lost in a sea of services and design complexity (including security issues). However for customers which have more specific knowledge of AWS - which it sounds as you might - we offer ways to accomplish what you're looking more and are working on alternatives in the future.

First you can always use the `Auth` category in the JS library to directly call an AWS service interface using the credentials that the client gets from Cognito. For example calling Route 53:

```
import Route53 from 'aws-sdk/clients/route53';
...

Auth.currentCredentials()
  .then(credentials => {
    const route53 = new Route53({
      apiVersion: '2013-04-01',
      credentials: Auth.essentialCredentials(credentials)
    });

    // more code working with route53 object
    // route53.changeResourceRecordSets();
  })
```

To assign credentials to the client with rights to call Route53 (or DynamoDB in your case) you could either modify the created CloudFormation which Amplify CLI creates before doing a push or alter the Cognito Roles the client assumes directly in the IAM console.

We are also working on another enhancement to the Auth config which might meet your needs in advanced use cases where you could alter the IAM policy that Cognito Identity gives out to clients and call services (such as DynamoDB) directly. You can read more about that here: https://github.com/aws-amplify/amplify-cli/issues/766
