### ISSUE TITLE
How can you create a custom CF stack unrelated of api/auth/etc?

### ISSUE THREAD

**Issue by plaa** [aws-amplify/amplify-cli#1426]
** Which Category is your question related to? **
Amplify cli

** What AWS Services are you utilizing? **
N/A

** Provide additional details e.g. code snippets **
We're planning to create an RDS database and access it from Lambda functions managed by Amplify.  I know that you can define custom stacks by adding them to `amplify/backend/api/myapi/stacks/` (at least in the case of GraphQL API, the directory is not present for REST APIs), but this stack is not related to any API.  I was looking for an `amplify add stack` command or similar.

We could create e.g. an API just for the purpose of providing a custom CF stack but that seems silly.  We don't want the DB stack to be in the same API as the logic accessing it for reasons discussed in #1406.

Is there a generic way to deploy custom stacks?  Furthermore, is there a way to ensure the DB stack is created (and the exported output values present) before the other CF stacks are created?

As a workaround we're considering that we'll have a database CF stack that must be manually created before the Amplify stacks are deployed, but it would be preferable to have everything deployed by Amplify.

**Comment by kaustavghosh06** [comment]
@plaa You could porbbaly write your own plugin to make this possible. You can take a look at the amplify video plugin as an example - https://github.com/awslabs/amplify-video
But having said, we're looking to having a custom stack directory structure similar to the graphql API custom stacks to solve your use-case.

**Comment by willkara** [comment]
@kaustavghosh06 Is the team envisioning something where you could define your own stacks/CFTs, include them in a directory and reference them in the parent build-stack?

**Comment by kaustavghosh06** [comment]
@willkara Yes, that's correct.

**Comment by kaustavghosh06** [comment]
@plaa Take a look at @zjullion's solution for supporting custom stacks outside of the one's supported by Amplify out here - https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916
We'll add a task to document this in our docs.
