### ISSUE TITLE
Change DynamoDB read and write reserved capacity

### ISSUE THREAD

**Issue by daaru00** [aws-amplify/amplify-cli#143]
Hi,

I try to change the default in `amplify/backend/api/<myapi>/cloudformation-template.json` and adding parameters to `amplify/backend/api/<myapi>/parameters.json` but both files are reset running `amplify push`.
I try to add parameters in `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` under "myapiname"->"Parameters" but nothing, `amplify push` say that are no changes.

How can be changed `DynamoDBModelTableReadIOPS` and `DynamoDBModelTableWriteIOPS` parameters set by default set to 5?

**Comment by bastianbb** [comment]
I need this too currently i'm stucked because i have a lot of Types in my GraphQL schema and i don't want 5 R/W units x table.
The opportunity to set units for the GSI created by a connection would be appreciated too.

**Comment by ronaldvanderrest** [comment]
+1 here as well... I actually want to scale down though

**Comment by jasondecarvalho** [comment]
I would like to be able to also change to on-demand pricing,
