### ISSUE TITLE
Codegen grapqhl subscriptions with nullable argument(s)

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-cli#1436]
**Is your feature request related to a problem? Please describe.**
Currently, the generated subscriptions don't support any parameters/arguments. So subscriptions trigger on any and all instances of a mutation.

**Describe the solution you'd like**
It'd be nice if I could at least pass a nullable ID argument to the subscriptions, if not specify additional arguments.

**Additional context**
Current Codegen (example):
```
type Subscription {
  onCreatePost: Post @aws_subscribe(mutations: ["createPost"])
  onUpdatePost: Post @aws_subscribe(mutations: ["updatePost"])
  onDeletePost: Post @aws_subscribe(mutations: ["deletePost"])
}
```

Requested Codegen (example):
```
type Subscription {
  onCreatePost(id: ID): Post @aws_subscribe(mutations: ["createPost"])
  onUpdatePost(id: ID): Post @aws_subscribe(mutations: ["updatePost"])
  onDeletePost(id: ID): Post @aws_subscribe(mutations: ["deletePost"])
}
```

I figure this would be a pretty fast and easy feature to implement and would add immense value to amplify for me.

**Comment by akshbhu** [comment]
Hi @potatopotaro 

You can write those subscrption in schema.graphql and amplify will direclty post these subscriptions in the build schema present in <apifolder>build/schema.graphql when you will run ```amplify push ``` or ```amplify api gql-compile```.

If this issue still persists , comment and I will reopen the issue.
