### ISSUE TITLE
Amplify CLI doesn't use correct AWS profile

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-cli#144]
**Describe the bug**
Amplify CLI keeps creating resources in my main AWS account NOT the account specified when running amplify configure

**To Reproduce**
1. amplify configure
2. log in to AWS console with account desired 
3. create user
4. enter key, secret and tell CLI to use this new profile
5. Run amplify init and recourse are created under default AWS account not the one listed in profile

**Expected behavior**
Deploy cloudformation templates to the AWS account specified in the profile settings

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
We fixed this with the latest version of the CLI. Which version are you using? Use ‘amplify -v’ command to check.

**Comment by tscole** [comment]
I've got 0.1.15 - looks like you're now on 0.1.18?

**Comment by kaustavghosh06** [comment]
Yes, correct.

**Comment by tscole** [comment]
@kaustavghosh06 updating to 0.1.18 does indeed seem to solve the issue. Thanks!

**Comment by stevemao** [comment]
0.1.28 still seems to have the same problem

**Comment by stevemao** [comment]
`amplify push` always uses my default profile.
