### ISSUE TITLE
Amplify Publish not pushing changes to cloud - won't update.

### ISSUE THREAD

**Issue by lowercase00** [aws-amplify/amplify-cli#1442]
**Describe the bug**
Yesterday, changes in my Vue project stopped being updated in the cloud.
I thought that it was because I had changed the version of my project at `packages.json` file.
So I deleted everything related to Amplify and my environment, cleared my related S3 buckets and `init` the project again. Today, everything was working fine - I'm 100% positive that I only made changes to the .vue files, but all of the sudden (after about 5 `publish` commands) it stopped pushing my updates to the cloud.

**Expected behavior**
When using the amplify publish command, the code should be updated in the cloud.

**Desktop (please complete the following information):**
macOS Mojave

**Additional context**
Using Vue-CLI

**Comment by UnleashedMind** [comment]
@lowercase00 
publish has 4 operations, executed in the following sequence:
1. executes `amplify push` to update the backend resources in the cloud 
2. builds your frontend application into the `"Distribution Folder"`
3. uploads the contents in the `"Distribution Folder"` into the deployment buckets. 
4. if CloudFront is enabled and you explicitly added the '-c' flag in the `amplify publish -c`, a invalidation request is sent to the CloudFront. 

I was not able to reproduce the bug. Could you be more specific which part of the above was broken? so we can investigate further.

**Comment by stayingcool** [comment]
I have the same problem today with Angular app. 
`amplify publish` is completing without any issues, however, the latest version of the front end is not being served through S3.
If I try to serve it locally (`npm start`) just to see if the changes are showing up and I do see the latest changes I have made.
Things that I have done, the issue is still at large:
1. Remove the contents of S3 bucket manually (Never did this before, just getting annoyed)
2. Run the `amplify publish` command

Any clues to see why the latest front end build is not showing up on S3.

Note : I'm using new cli (multiple env version: 0.2.2-multienv.1)

**Comment by stayingcool** [comment]
Just an update from myside, after reading other issues I did the following to get the issue resolved:
1. `amplify configure project`
2. Deleted the contents of S3 bucket (Not required in my opinion, was just desperate to get the latest changes) 
3. `amplify publish`

Note - By the way, I'm working on a multi-environment, chances are there that after bringing up an enviroment we might have to configure the project. Still new to multi-environment support functionality.

**Comment by lowercase00** [comment]
For me it works after deleting everything (S3 bucket and project).
My guess is that the `publish` is where the problem is, since just as @stayingcool when I run the project locally it works just fine (showing my updates). I chose to switch to `aws s3 sync` for now and adding a `deploy` script to my `packages.json` file:

`"deploy": "node build/build.js && aws s3 sync ./dist s3://mybucket --acl public-read"`

**Comment by kaustavghosh06** [comment]
@lowercase00 Were you checking for changes in your cloudfront instance or S3 instance?

**Comment by bradgreens** [comment]
I had this issue after moving the project to a different folder on my machine. I had to update the config file `./amplify/.config/local-env-info.json` to tell Amplify where to deploy from. Prior to that it was deploying the old code in another directory and it looked like it was not pushing changes.

**Comment by mikeRChambers610** [comment]
@bradgreens Thank you!!!

**Comment by MatteoInfi** [comment]
I have the exact same bug, is this fixed?

**Comment by mikeRChambers610** [comment]
@Matteolnfi did you try the above solution? Checking if you have the right source locarion for your project in: ./amplify/.config/local-env-info.json
