### ISSUE TITLE
Can't install amplify CLI on Windows

### ISSUE THREAD

**Issue by maslbl4** [aws-amplify/amplify-cli#1447]
**Describe the bug**
Can't install "aws-amplify/cli" on Windows 10

**To Reproduce**
1. npm install -g @aws-amplify/cli
2. See error
> npm ERR! Unexpected end of JSON input while parsing near '...BKi\n7yk6\r\n=1rHO\r\'

**Expected behavior**
aws-amplify/cli install successfully 

**Desktop (please complete the following information):**
 - OS: Windows 10 ver. 1809
 - NPM: 6.4.1 and 6.9.0

**Logs**
[2019-05-13T14_13_33_245Z-debug.log](https://github.com/aws-amplify/amplify-cli/files/3173306/2019-05-13T14_13_33_245Z-debug.log)

**Comment by kaustavghosh06** [comment]
@maslbl4  Which node version do you have installed? You need Node version >= 8.1x for the CLI.

**Comment by maslbl4** [comment]
@kaustavghosh06 I'm trying last LST and Current from https://nodejs.org/en/download/

**Comment by kaustavghosh06** [comment]
Seems like an npm cache issue. Please try -  npm cache clean --force
Related issue - https://github.com/vuejs-templates/webpack/issues/990
I wasn't able to reproduce this issue on my windows machine.

**Comment by maslbl4** [comment]
@kaustavghosh06 Thanks, this is helped
