### ISSUE TITLE
Amplify codegen

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1448]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify codgen

** What AWS Services are you utilizing? **
Amplify appsync
** Provide additional details e.g. code snippets **
I am using amplify appsync, i  am using complex object. When i use codegen for complex objects. It is showing like this
Export type S3ObjectInput {
bucket: string,
key: string,
region:string
}

localUri, mimeType are missing

**Comment by yuth** [comment]
@achutkiran could you share the `.grpahqlconfig.yml` file. Please obfuscate sensitive information lile API key and urls

**Comment by kaustavghosh06** [comment]
@achutkiran Please let us know if you're still having issues with this.
