### ISSUE TITLE
Is it intentional, that using MulitiEnv you only get one Database

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1454]
** Which Category is your question related to? **
[MultiEnv](https://aws-amplify.github.io/docs/cli/multienv?sdk=js)

** What AWS Services are you utilizing? **
Cognito, AppSync, DynamoDB, Pinpoint

** Provide additional details e.g. code snippets **
I have created a React app using Amplify with two Environments: Dev and Prod. Both use the categories Auth, API and Analytics.

All services now have two instances. (See example screenshot for analytics in Pinpoint below).

![Screenshot 2019-05-15 at 10 56 04](https://user-images.githubusercontent.com/31096420/57762670-35555180-7700-11e9-82eb-9ac38c17d32e.png)

The only service that still only has one instance is DynamoDB. No second database was created, instead both environments share the same one. Is this intentional? Is there a way to have one database for each environment?

**Comment by davekiss** [comment]
@janhesters when you provision your api with `amplify push` you should be seeing new DynamoDB tables that would look like `Table-${apiId}-${env}` where env is the name of your environment (in your case, one for `prod` and one for `dev`

**Comment by janhesters** [comment]
@davekiss You are right, it appeared now, after I added hosting to the prod environment.
