### ISSUE TITLE
Join model no longer generating correct files during publish

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-cli#1456]
Something must have changed in the CLI recently as minor changes to a schema that was publishing fine a week or two ago no longer are accepted during `amplify push` –– the join model that was manually created to work around the many-to-many shortcomings in amplify does not generate an expected JSON file in `amplify/backend/{project}/build/stacks/JoinModel.json` and I'm guessing any other files that are required as well

When I attempt to run `amplify push` it seems that amplify tries to create a table for the join model even though it already exists in the stack and errors out

```
CREATE_FAILED      PlaylistVideoTable                                                   AWS::DynamoDB::Table       Wed May 15 2019 10:03:11 GMT-0400 (Eastern Daylight Time) PlaylistVideo-projectid-dev already exists in stack `arn-goes-here`
```

Here's a look at a piece of my Schema which, as mentioned, was deploying fine a week or so ago. I tried downgrading to a previous version of amplify cli to no avail.

```
type Playlist
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Guests"], operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  position: Int!
  title: String
  description: String
  collection: Collection!
    @connection(name: "CollectionPlaylists", sortField: "position")
  videos: [PlaylistVideo]
    @connection(name: "PlaylistVideos", sortField: "position")
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type PlaylistVideo
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Guests"], operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  playlist: Playlist! @connection(name: "PlaylistVideos", sortField: "position")
  video: Video! @connection(name: "VideoPlaylists", sortField: "position")
  position: Int!
  actions: [PlaylistVideoAction]
    @connection(
      name: "PlaylistVideoActions"
      keyField: "playlistVideoId"
      sortField: "position"
    )
  metadata: AWSJSON
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type Video
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Guests"], operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  title: String!
  description: String
  visibility: Visibility
  url: AWSURL
  duration: Int
  width: Int
  height: Int
  status: VideoStatus
  thumbnails: [Thumbnail]
    @connection(name: "VideoThumbnails", sortField: "createdAt")
  tags: [Tag] @connection(name: "VideoTags", sortField: "createdAt")
  assets: [VideoAsset] @connection(name: "VideoAssets", sortField: "createdAt")
  playlists: [PlaylistVideo] @connection(name: "VideoPlaylists")
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

enum VideoStatus {
  uploading
  transcoding
  available
}
```

**To Reproduce**
Use the above schema to determine whether deployment works appropriately on initial and subsequent deployments.

**Expected behavior**
Tables are created if they don't exist and are updated if schema is changed between deployments

**Comment by mikeparisstuff** [comment]
What changed between deployments? If you changed something that will cause the underlying structure of the GSI created by an @connection to change then there is a known issue that will cause the stack update to fail. This is being solved by a new @key directive. To avoid this issue, try adding new @connection's and then removing old ones after pushing one time instead of trying to change a @connection in place.

**Comment by davekiss** [comment]
Closing this, I'm pretty sure I somehow pushed things into an unusable state by adding the recently-introduced `keyField` value to `@connection` and maybe by then removing it during troubleshooting? Either way, I'm going to be super careful with `@connections` moving forward as they've caused me to have to destroy and reproduce the API several times
