### ISSUE TITLE
amplify push error on auth resource

### ISSUE THREAD

**Issue by zoumengguang** [aws-amplify/amplify-cli#1461]
**Describe the bug**
I am currently trying to add an auth component to my app via Amplify CLI but I am getting the following error when trying to push the auth creation to the cloud:

`Resource Name: UserPoolClientLambda (AWS::Lambda::Function)`
`Event Type: create`
`Reason: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: f845ed54-774d-11e9-9e33-2782c0fd903a)`

I know I was able to push my auth resource before but after deleting it, remaking it, and attempting to push it again, the CLI gave me the error in question.

**To Reproduce**
1. Initialize an Amplify project
2. run `amplify add auth`
3. attempt `amplify push`
3. See error

**Expected behavior**
Successfully pushing the creation of the auth component to the cloud.

**Additional context**
I know AWS has been transitioning out of Node 6.10 lately, but does that possibly affect something in the script that is attempting to create a obsolete Lambda function in the cloud relating to the auth resource?

**Comment by kaustavghosh06** [comment]
I beleive this auth resource was created with previous versions of the CLI, before we upgraded our default Cloudformation tempaltes to Node 8.10. Here's a quick migration guide out here - https://aws-amplify.github.io/docs/cli/lambda-node-version-update#auth

**Comment by zoumengguang** [comment]
Nice, that fixed it. Thanks!

**Comment by Haugf** [comment]
@kaustavghosh06 link routes to https://docs.amplify.aws/
