### ISSUE TITLE
Amplify Publish Not Reflecting Changes

### ISSUE THREAD

**Issue by jmandivarapu1** [aws-amplify/amplify-cli#1465]
**Describe the bug**
I have Amplify Setup in my application which is working previously.
Now Yesterday I made change and did amplify publish...Everything is successfully but changes didn't got reflected in the live website.

**Debuging**: So to debug myself I went to the bucket in s3 and looked at the files manually and it's updated files with the changes...Then I went to the bucket hosting "Properties" then "Static Website Hosting" then clicked on the endpoint "http://courselabz-prod-release-redstone.s3-website-us-west-2.amazonaws.com" which is working and have all the changes inside it. So I want to know why even though s3 bucket and s3 bucket url is having updated changes why not my amplify hosted cloudfront url doesnt have my changes? "https://d19v75l5red964.cloudfront.net"
**To Reproduce**
1. Go to 'https://d19v75l5red964.cloudfront.net' (No changes)
2. Click on 'http://courselabz-prod-release-redstone.s3-website-us-west-2.amazonaws.com'(changes working)
**No Error Was thrown during the amplify publish command** [I tried publish multiple times still no change]
<img width="517" alt="Screen Shot 2019-05-16 at 10 40 08 AM" src="https://user-images.githubusercontent.com/21245519/57862855-0950d380-77c7-11e9-8e28-a338bb0efb09.png">

**Comment by kaustavghosh06** [comment]
@jmandivarapu1 Cloudfront doesn't immediately invalidate it's cache. If you want to immediately invalidate the cache, you would want to use the `-c` flag with the `amplify publish` command.

**Comment by MatteoInfi** [comment]
Same bug here, I have tried with the -c flag but still the same result.

**Comment by elankeeran** [comment]
@MatteoInfi did you got any solution, Im facing same issue.
