### ISSUE TITLE
How to override a stack to add custom GSI?

### ISSUE THREAD

**Issue by zfarrell** [aws-amplify/amplify-cli#1469]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync, DynamoDB

** Provide additional details e.g. code snippets **
I need to add a GSI to a table that was created by amplify/appsync which i'll then use in a custom resolver. I'm aware of #1062, but need something now. 

I was hoping that I could simply copy the stack from `amplify/backend/api/MyAPI/build/stacks/Model.json` to `amplify/backend/api/MyAPI/stacks/Model.json` but this seems to create a new stack called "Modeljson", rather than *override* the generated `Model` stack. 

Is there anyway to do this?

**Comment by hisham** [comment]
@zfarrel I have similar use case and what I do is run a script before amplify push to modify the cloud formation files in build/ to my needs. They are json files after all so fairly easy to modify in node.

**Comment by mikeparisstuff** [comment]
@zfarrell @hisham We are actively working on this and have a PR in progress. If you are interested in offering feedback, you can try the new `@key` directive today by cloning this fork: https://github.com/mikeparisstuff/amplify-cli and checking out the `feature/@key` branch. There are more instructions here https://github.com/mikeparisstuff/amplify-cli/blob/feature/@key/testing-custom-indexes.md.

**Comment by zfarrell** [comment]
thanks @hisham & @mikeparisstuff. 

@hisham - i took inspiration from your approach, however just threw something together quickly which is a version controlled script that utilizes the cli to update the table after amplify push is called the first time. i'm hoping this is a temporary solution, so didn't want to spend too much time on it.

@mikeparisstuff - would it be possible (or is it already possible) to add a hook as part of the graphql transformer logic that would allow (a plugin?) to make modifications before the stack cloudformation file is persisted to the build folder? The reality is amplify is always going to be missing _something_. Providing the ability to "safely" modify the cloudformation file without hacks like @hisham and I have done could help a lot.

**Comment by mikeparisstuff** [comment]
@zfarrell Yes in general I think this is a great idea and we have made progress towards enabling it. See this PR: https://github.com/aws-amplify/amplify-cli/pull/1396. We are working through this but the goal is to allow you to write, load, and distribute custom transformers that hook into the compilation process.

**Comment by zfarrell** [comment]
thanks @mikeparisstuff... this seems really promising. As mentioned in https://github.com/aws-amplify/amplify-cli/issues/1060#issuecomment-474199432, it would be extremely helpful to walk through a few use cases. For example, your write up for the `@function` docs is great.

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.
