### ISSUE TITLE
amplify console auth does not take to right region

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#1471]
**Describe the bug**

I tried to use `amplify console auth` and selected `Userpools`, it takes me to the page of UserPools but the pools are of us-east-1 where as my pool is in us-west-2. 

The console shows us-west-2 as the region but lists us-east-1 pools.

**Comment by kaustavghosh06** [comment]
Hey! Provided a fix for this - https://github.com/aws-amplify/amplify-cli/pull/1473
