### ISSUE TITLE
Cognito user pools with triggers

### ISSUE THREAD

**Issue by jmorecroft** [aws-amplify/amplify-cli#1475]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AWS Amplify
** What AWS Services are you utilizing? **
AWS Cognito triggers
** Provide additional details e.g. code snippets **
Hi,

We're attaching lambda pre-auth triggers to our Cognito User Pool and would like to use this same User Pool with our Amplify / AWS AppSync API. Unfortunately the Amplify toolset doesn't appear to support this - the user pool must be created new and triggers are not supported. This probably means I need to generate Amplify schema and resolver output and copy/paste into our current serverless deployment setup, along with associated additions to serverless.yml to create all these, the Dynamo DB tables etc, which really eliminates a lot of the benefit of the Amplify toolchain. 

Is anyone able to suggest a more scalable solution? Ideally (in our GitLab pipeline) we'd either,

1. Run serverless to generate our user pool, triggers and lambdas as we do now
2. Run amplify init, add api, push (in headless mode) with our API user pool referencing the pool created in step 1

OR, if amplify supported user pool triggers just eliminate the serverless step entirely.

**Comment by kaustavghosh06** [comment]
@jmorecroft We're actively working on supporting lambda triggers as a part of the Amplify project.

**Comment by kaustavghosh06** [comment]
I'll update this thread once we have it ready for release.

**Comment by jmorecroft** [comment]
Thanks for that. Great to see such speedy progress on this platform.

**Comment by kaustavghosh06** [comment]
We've added support for Lambda Trigger support for the dynamo tables managed/added by the CLI using the `amplify add storage` command. Let me know if you find that useful. Please take a look at https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/ for more details.
