### ISSUE TITLE
Document custom queries/mutations and resolvers

### ISSUE THREAD

**Issue by lorensr** [aws-amplify/amplify-cli#1477]
I can't find documentation corresponding with this merged PR:

https://github.com/aws-amplify/amplify-cli/pull/227

I and others wonder how resolvers for custom queries work, and how to maintain them through schema changes / pushes:

![image](https://user-images.githubusercontent.com/251288/57898921-fff85300-7828-11e9-8983-da556b78c844.png)

**Comment by wizawuza** [comment]
https://aws-amplify.github.io/docs/cli/graphql#api-category-project-structure

**Comment by kaustavghosh06** [comment]
@lorensr Please let me know if the link pasted by @wizawuza is something which you were looking for.

**Comment by lorensr** [comment]
Yes, thanks. Both the page and the sections in the page would be more discoverable if the page was included in the ToC on the left sidebar—should I open a separate issue for that?
