### ISSUE TITLE
Incomplete input classes 

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1480]
When I make a @connection between two types like is done here between Week and Recipe:
```
type Week
  @model
{
  id: ID!
  weeknumber: Int!
  recipes: [Recipe!] @connection(name: "WeekRecipes")
}

type Recipe 
  @model
{
  id: ID!
  title: String
  key: String
  image: String
  numberOfPersons: Int
  courses: [String]
  time: String
  energy: String
  proteine: String
  carbohydrates: String
  fat: String
  saturatedFat: String
  fibers: String
  salt: String
  sugar: String
  recipeTypes: [String]
  specials: [String]
  containsProducts: [String]
  diet: [String]
  ingredients: [Ingredient]
  preperation: [String]
  editDate: String
  menuSuggestion: String
  week: Week @connection(name: "WeekRecipes")
}
```

The `amplify codegen` generated input classes for type Week will look like this:

```
export type CreateWeekInput = {
  id?: string | null;
  weeknumber: number;
};

export type UpdateWeekInput = {
  id: string;
  weeknumber?: number | null;
};
```

There is no field `recipes` 
So during a creation of a Week, I can not link it to a Recipe

**Comment by mikeparisstuff** [comment]
When using connection, you associate objects on the **one** side of the connection. In this case you would create a **Recipe** and specify a **recipeWeekId**.

If you want to be able to create a **Week** alongside it's recipes, you can remove the `@model` from **Recipe** as well as the `@connection`s. For example, you would have:

```graphql
type Week
  @model
{
  id: ID!
  weeknumber: Int!
  recipes: [Recipe!]
}

type Recipe {
  id: ID!
  title: String
  key: String
  image: String
  numberOfPersons: Int
  courses: [String]
  time: String
  energy: String
  proteine: String
  carbohydrates: String
  fat: String
  saturatedFat: String
  fibers: String
  salt: String
  sugar: String
  recipeTypes: [String]
  specials: [String]
  containsProducts: [String]
  diet: [String]
  ingredients: [Ingredient]
  preperation: [String]
  editDate: String
  menuSuggestion: String
}
```

This will allow you to create weeks with recipes directly but it will also store the list of recipes as a list of map types in a DynamoDB attribute within the **Week** table. The downside of this approach is that the **Recipe** will no longer be a top-level type and thus you cannot fetch recipe objects directly.

**Comment by sprucify** [comment]
When both ends of the @connection has a @model tag, has the order in which they are placed in the .graphql file has influence who gets the `* * Id` field?

I'm confused by the examples in the Amplify Docs:
```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
Both ends of all the @connections have also a @model tag.

**Comment by mikeparisstuff** [comment]
@sprucify It is the cardinality of the connection that matters when placing the "* * Id" field. For example, when creating a one-to-many connection between "Blog" and "Post":

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
}
```

The "* * Id" will be injected on the "many" side i.e. the "Post" because we need to be able to "query Posts by blogId" in order to get the posts for a blog. As of writing there is no way to build bi-directional one-to-one connections and therefore the id is expected on both sides and the resolver uses a GetItem to fulfill the `@connection.
