### ISSUE TITLE
reference userpoolid in lambda template

### ISSUE THREAD

**Issue by integraitco** [aws-amplify/amplify-cli#1481]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
template policies definition

** What AWS Services are you utilizing? **
Cognito, lambda, apppsync

** Provide additional details e.g. code snippets **
Hi,  I want to add a cognito policy to my lambda function definition (in amplify). How can I ref the user Pool ID in this function? For now I have it to all (*) resources.. not ideal.
I added this to my function generated template
"lambdaexecutionpolicy": { "DependsOn": [ "LambdaExecutionRole" ], "Type": "AWS::IAM::Policy", "Properties": { "PolicyName": "lambda-execution-policy", "Roles": [ { "Ref": "LambdaExecutionRole" } ], "PolicyDocument": { "Version": "2012-10-17", "Statement": [ { "Sid": "logs", "Effect": "Allow", "Action": [ "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents" ], "Resource": { "Fn::Sub": [ "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*", { "region": { "Ref": "AWS::Region" }, "account": { "Ref": "AWS::AccountId" }, "lambda": { "Ref": "LambdaFunction" } } ] } }, { "Sid": "cognito", "Effect": "Allow", "Action": [ "cognito-idp: CreateGroup" ], "Resource": "*" } ] } } }

Any advice appreciated!

**Comment by kaustavghosh06** [comment]
@integraitco There isn't an easy way to do so right now, but we have an open PR to make this possible out here - https://github.com/aws-amplify/amplify-cli/pull/1462 
We're planning to merge this in a couple of days.

**Comment by zjullion** [comment]
@integraitco, this is actually pretty easy to do:

Near the bottom of your auth template (something like `amplify/backend/auth/cognito78b2fc/cognito78b2fc-cloudformation-template.yml` you'll see that `UserPoolId` is an output of the auth stack (note that it's not an export, just an output). However, you can use `amplify/backend/backend-config.json` to provide that output as a parameter to your lambda stack.

Modify your lambda's entry in `amplify/backend/backend-config.json` like so:
```
		"myLambda": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true,
			"dependsOn": [
				{
					"category": "auth",
					"resourceName": "cognito78b2fc",
					"attributes": [
						"UserPoolId"
					]
				}
			]
		},
```

You'll need to do an `amplify env checkout <myEnvironment>` for amplify to recognize these changes. At this point, your lambda is dependent on the auth stack to be deployed first, and will receive a parameter that looks like this: `authcognito78b2fcUserPoolId`. So, we can modify the lambda cloudformation template to accept the parameter:
```
	"Parameters": {
		"env": {
			"Type": "String"
		},
		"authcognito78b2fcUserPoolId": {
			"Type": "String"
		}
	},
```

You'll then want to make the changes you need to your lambda's execution policy to make this work.

**Comment by valeeum** [comment]
Thanks, very helpful.  How would you initialize Auth in the function itself?

**Comment by kaustavghosh06** [comment]
@valeeum What do you mean by initializing Auth in the function? You could maybe use the aws-sdk to access your AWS resources?

**Comment by valeeum** [comment]
@kaustavghosh06  i was hoping someone can share their code of how the aws-sdk library was initialized/configured as well as the CreateGroup call based off of the event and/or context arguments provided in the lambda function.

**Comment by plaa** [comment]
Is the `parameters.json` and `backend-config.json` functionality documented anywhere? Or is it even stable / can it break at any time?

I was trying to figure out how to do exactly what @zjullion described, but couldn't find it documented anywhere.  It's a huge shame that such a significant part of Amplify functionality is hidden and undocumented.

**Comment by kaustavghosh06** [comment]
@hisham Today we released an updated flow as a part of the functions category to pass resource identifiers like the cognito userpool ID (managed and genrated by the Amplify CLI) to a lambda function as environment variables and also populate the corresponding lambda execution role to access these resources. You can install the latest version of the CLI and go through the `amplify update function` flow to update your existing functions to access your Amplify generated resources in the project.

**Comment by andrew-aernos** [comment]
> @integraitco, this is actually pretty easy to do:
> 
> Near the bottom of your auth template (something like `amplify/backend/auth/cognito78b2fc/cognito78b2fc-cloudformation-template.yml` you'll see that `UserPoolId` is an output of the auth stack (note that it's not an export, just an output). However, you can use `amplify/backend/backend-config.json` to provide that output as a parameter to your lambda stack.
> 
> Modify your lambda's entry in `amplify/backend/backend-config.json` like so:
> 
> ```
> 		"myLambda": {
> 			"service": "Lambda",
> 			"providerPlugin": "awscloudformation",
> 			"build": true,
> 			"dependsOn": [
> 				{
> 					"category": "auth",
> 					"resourceName": "cognito78b2fc",
> 					"attributes": [
> 						"UserPoolId"
> 					]
> 				}
> 			]
> 		},
> ```
> 
> You'll need to do an `amplify env checkout <myEnvironment>` for amplify to recognize these changes. At this point, your lambda is dependent on the auth stack to be deployed first, and will receive a parameter that looks like this: `authcognito78b2fcUserPoolId`. So, we can modify the lambda cloudformation template to accept the parameter:
> 
> ```
> 	"Parameters": {
> 		"env": {
> 			"Type": "String"
> 		},
> 		"authcognito78b2fcUserPoolId": {
> 			"Type": "String"
> 		}
> 	},
> ```
> 
> You'll then want to make the changes you need to your lambda's execution policy to make this work.

where can I find the documentation on the parameter syntax? By the looks of `authcognito78b2fcUserPoolId`, it is formatted as
`<category: auth><resource: cognito78b2fc><attribute: UserPoolId>` on the receiving end of the dependent resource.

**Comment by zjullion** [comment]
@andrew-aernos: I don't believe this is documented anywhere
@kaustavghosh06: is it possible to get the parameter-passing format documented?

**Comment by ecomonestop** [comment]
@zjullion - I tried "<category: auth><resource: cognito78b2fc><attribute: UserPoolId>" as the parameter syntax, but its not working.  The parameter doesnt get passed and the cloudformation stack fails.

**Comment by ambientlight** [comment]
@ecomonestop: try adding in your category resource `parameters.json`, making sure resource name matches your auth resource name in `amplify-meta.json` as 

```
"AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "authcognito78b2fc",
            "Outputs.UserPoolId"
        ]
    },
```
then make sure you have it as parameter in your cloudformation template like:

```json
{
    "Parameters": {
        "AuthCognitoUserPoolId": {
            "Type": "String",
            "Description": "The id of an existing User Pool to connect. If this is changed, a user pool will not be created for you.",
            "Default": "NONE"
        },
    }
}
```

**Comment by zjullion** [comment]
> @zjullion - I tried "<category: auth><resource: cognito78b2fc><attribute: UserPoolId>" as the parameter syntax, but its not working. The parameter doesnt get passed and the cloudformation stack fails.

The parameter name should be in the format `authcognito78b2fcUserPoolId`, where `auth` is the category, `cognito78b2fc` is the resource, and `UserPoolId` is the attribute.

**Comment by rfpedrosa** [comment]
+1 on @zjullion request to have parameter-passing format documented (on "[Custom Cloudformation Stacks](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks)"?)

**Comment by oscarnevarezleal** [comment]
In case anyone else is looking for the format, this is it. ( documented [here](https://docs.amplify.aws/cli/usage/customcf) )
```
"Parameters": {
  // Rest of the parameters

  "authmycognitoresourceUserPoolId": { // The format out here is `<category><resource-name><attribute-name>` - we have defined all of these in the `backend-config.json` file above
     "Type": "String"
 }
},
```

**Comment by THPubs** [comment]
To add to the @kaustavghosh06 's answer...

1. Run `amplify update function`
2. Select which capability you want to update: `Lambda function (serverless function)`
3. Select the Lambda function you want to update `YOUR_FUNCTION_NAME`
4. Which setting do you want to update? `Resource access permissions`
5. Select the category `auth`
6. Select the operations you want to permit for API_ID `read`

At the end it will give you an environment variable where you can access the user pool id like this:

```
You can access the following resource attributes as environment variables from your Lambda function
	AUTH_MY_APP_ID_USERPOOLID
```

Use that in your function `process.env.AUTH_MY_APP_ID_USERPOOLID`
