### ISSUE TITLE
Multi-auth support for GraphQL Transformer

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-cli#1485]
** Which Category is your question related to? **
GraphQL Transformer

Hey fellas, with the new multi-auth support for Appsync, I was wondering what the ETA will be like for supporting this in the Amplify CLI. I've seen comments suggesting at least 1+ month(s), and the blog post states that support is being worked on.

If it is indeed the case that it'll be 1+ month(s)...

- Is there a hacky solution we can use for multi-auth right now?
- I assume editing our Amplify CLI generated Appsync from the Appsync console (or cloudformation, etc.) would be overwritten with the next `amplify push` correct?
- I'm guessing the best bet is to transform our GraphQL code, copy-paste the generated build code into a new Appsync project created outside of the Amplify CLI, and replace/drop-in the new multi-auth directives (e.g. @aws_api_key)?

Apologies if there's already an ongoing discussion elsewhere, on this specific subject. I couldn't find anything. Multi-auth support would be huge for my project, as currently, I'm using a very slow junction lambda function to make "unauthorized" requests.

**Comment by kaustavghosh06** [comment]
@potatopotaro We're actively working on supporting multi-auth as a part of the GraphQL Transformer and I'll have an update this thread as soon as we release this feature.

**Comment by kaustavghosh06** [comment]
We launched multi-auth support for AppSync API (which included public APIs - with API Keys + IAM) as a part of our CLI version 3.7+.
Please take a look at our documentation around it out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#public-authorization
