### ISSUE TITLE
Is there a way to logout/disable/delete a user remotely in Auth?

### ISSUE THREAD

**Issue by giantGoldfish** [aws-amplify/amplify-cli#1487]
**Is your feature request related to a problem? Please describe.**
Hello, I am writing to ask about ways to disable/logout/delete a user account remotely. I am developing React Native App with Expo. One possible use case is to automatically log out an old device if the system detect the user is logged in with another device.

**Describe the solution you'd like**
Is there currently a way to trigger a user to logout remotely using amplify?

**Describe alternatives you've considered**
If this request is not possible, my alternative solution will be to try implement a lambda function and disable the user through the AWS SDK for JS.

**Additional context**

**Comment by yuth** [comment]
@giantGoldfish I have added marked this as a feature request and our product team will review and prioritize this.

**Comment by jkeys-ecg-nmsu** [comment]
@yuth are AppSync subscriptions an appropriate way of triggering callbacks in client code? I'm experimenting with the idea of using subscriptions to trigger client-side logic from the backend whenever some relevant event occurs (i.e. onCreateSomeEventRecord).

**Comment by kaustavghosh06** [comment]
@giantGoldfish We released AdminQueries support last year - https://docs.amplify.aws/cli/auth/admin#enable-admin-queries which basically supports disabling a cognito user using APIGW. We spin up the Lambda function and APIGW  endpoint automatically for you from the CLI. Please let us know if you've more questions around it and if this doesn't solve your use-case.
