### ISSUE TITLE
Configuring roles for use with pre-existing AWS services

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-cli#1489]
** Which Category is your question related to? **
IAM, Roles

** What AWS Services are you utilizing? **
Lambda, Amplify

** Provide additional details e.g. code snippets **
I have pre-existing Lambdas and other Amazon resources. I'd like to be able to access them via Amplify but Amplify creates its own roles. What is the best way to allow Amplify to work with my pre-existing services?

Note, right now I'm manually attaching a policy to the roles that are created by Amplify. I could probably automate this using the aws cli if I knew what the names of the role were going to be but I don't see any way to do that. It would be nice if there was a hook into the cloudformation template that allowed me to specify policies for roles...

**Comment by kaustavghosh06** [comment]
@cliffordh The best way would be to use plugins to solve for your use-case or modifying the Cloudformation files generated by the CLI for you in the `amplify` dir in your project. Here's a link to our plugins doc - https://aws-amplify.github.io/docs/cli/plugins?sdk=js
