### ISSUE TITLE
Increase the limit for API list

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1496]
**Is your feature request related to a problem? Please describe.**
I need to make queries larger for more than 1000 entities without using `nextToken`.

**Describe the solution you'd like**
Increase the limit to [AWS AppSync's `forEach` to more than 1000.](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_appsync)

**Describe alternatives you've considered**
I could implement my logic with `nextToken` but that would take days, because it would add a lot more complexity into the app.

**Comment by ajhool** [comment]
This is an issue with AWS Appsync, not AWS Amplify. You should contact the AppSync team through AWS support to suggest that increase.

Frankly, I would highly recommend using nextToken to implement your query because AWS probably won't change that limit for a long time.

**Comment by YikSanChan** [comment]
Why not just manually set limit to 1000? That is the easiest fix.

**Comment by janhesters** [comment]
@ajhool Thank you for letting me know. Guess I will have to use `nextToken` then 😢 

@YikSanChan I need more than a thousand, which according to ajhool is apparently impossible.

**Comment by YikSanChan** [comment]
@janhesters No, it is possible, simply set the limit in your graphql query.
An example can be found https://docs.aws.amazon.com/appsync/latest/devguide/using-your-api.html:
```
query list {
    getTodos(limit:2){
        todos {
            id
            name
            status
            comments{
                commentid
                content
            }
        }
        nextToken
    }
}
```
Change to `limit: 2` to `limit: 5000` simply works, though ugly.

**Comment by janhesters** [comment]
@YikSanChan No, it doesn't (at least for me it didn't). Using it like you suggested gives me an error with a message that the limit is 1000.

**Comment by ajhool** [comment]
@janhesters Would you go to your AppSync console, go to your list resolver (eg. if your models is named "Comment", then search "listComments" in the Resolvers panel). Click on the datasource and post the resolver code here?

When I look at my resolvers, I don't actually see them using the  `forEach` operator on the retrieved items, so I believe that my resolvers would allow for more than 1000 items to be returned.

**Comment by janhesters** [comment]
@ajhool Sure, I'll give you everything. Here is the query I wrote:

```graphql
query list {
  listContacts(limit: 1001) {
    items {
      id firstName lastName
    }
  }
}
```

Here is the respose I get:

```json
{
  "data": {
    "listContacts": null
  },
  "errors": [
    {
      "path": [
        "listContacts"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 32,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "List size cannot exceed 1000"
    }
  ]
}
```

Here is the resolver for the request:

```vtl
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
{
  "version": "2017-02-28",
  "operation": "Scan",
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": $limit,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end
}
```

And for the response:

```vtl
## No Static Group Authorization Rules **


## [Start] If not static group authorized, filter items **
#if( ! $isStaticGroupAuthorized )
  #set( $items = [] )
  #foreach( $item in $ctx.result.items )
    ## No Dynamic Group Authorization Rules **


    ## [Start] Owner Authorization Checks **
    #set( $isLocalOwnerAuthorized = false )
    ## Authorization rule: { allow: owner, ownerField: "owner", identityField: "cognito:username" } **
    #set( $allowedOwners0 = $item.owner )
    #set( $identityValue = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
    #if( $util.isList($allowedOwners0) )
      #foreach( $allowedOwner in $allowedOwners0 )
        #if( $allowedOwner == $identityValue )
          #set( $isLocalOwnerAuthorized = true )
        #end
      #end
    #end
    #if( $util.isString($allowedOwners0) )
      #if( $allowedOwners0 == $identityValue )
        #set( $isLocalOwnerAuthorized = true )
      #end
    #end
    ## [End] Owner Authorization Checks **


    #if( ($isLocalDynamicGroupAuthorized == true || $isLocalOwnerAuthorized == true) )
      $util.qr($items.add($item))
    #end
  #end
  #set( $ctx.result.items = $items )
#end
## [End] If not static group authorized, filter items **

$util.toJson($ctx.result)
```

**Comment by janhesters** [comment]
@ajhool 

> I would actually say that this is an Amplify schema bug for allowing limits > 1000 if authorization is required.

Yes, I think that is the case right here. But still a greater limit would be neato! :)

**Comment by ajhool** [comment]
I'd recommend contacting that AppSync team via AWS support and closing this issue as Amplify can do nothing about the limit

**Comment by janhesters** [comment]
@ajhool Thank you.

**Comment by janhesters** [comment]
@ajhool I closed the issue, but I do have two more questions, maybe you know a solution for these 🤗 .

1. I'm basically building a contact list app. Up until now, no user had more than a thousand contacts. I display all contacts at once at several points in the app. Let's say I use a `useEffect` hook for example in the list of all contacts to fetch all contacts iteratively at once using the `nextToken` (until its `null`).

```js
useEffect(() => {
  iterativelyFetchContacts();
}, []);
```

The user can also `update` and `create` contacts.

```js
export default compose(
  // Using AppSync's helper methods for optimistic UI
  graphqlMutation(gql(createContact), ListContacts, 'Contact'),
  graphqlMutation(gql(updateContact), ListContacts, 'Contact'),
  // ... other HOCs
)(List);
```

If the user now updates a contact or creates one, the `ListContacts` query gets invoked which can only fetch 1000 contacts. This results in some contacts missing from the list, if he has more than a thousand. Is there a way to fix this, or do I have to implement optimistic updates myself if I have more than a thousand entities?

2. Is there a way to sort the incoming list based on custom fields? E.g. the entities in my app are sorted on the client by `firstName` and `lastName`. But if I had to add pagination the first thousand contacts in the database would obviously not be sorted alphabetically. I know there is a [`sortField`](https://aws-amplify.github.io/docs/cli/graphql#connection) in the GraphQL API, but only for `connection`'s and you can only sort based on one field.

**Comment by ajhool** [comment]
1. Not sure. If you're using Apollo, you can use the update function https://www.apollographql.com/docs/react/essentials/mutations#update to call the iterative query after a mutation. You could also just use an `isDirty` flag in your react component that recalls the iterative query. It's hard for me to imagine an application where a contact list of +1000 needs to worry too much about the few seconds after adding a contact

2. I'm actually not sure if AppSync returns items based on alphanumeric sorting of the primaryKey (or sortKey if primaryKeys are the same). But, if so, you might be able to make it work by setting the ID! of your schema like so:

```
// The userId prevents conflicts across users. (Eg. my John Doe contact is different from your John Doe contact).
const userId = getUserId(); // from Auth ??

// The contact's name.
const firstName = 'john';
const lastName = 'doe';

// A uuid in case a user has multiple John Doe contacts.
const uniqueId = uuid().substring(0, 5)

// concat those details in such a way that they are in alphanumeric order.
let primaryKey = userId.substring(0, 8) + firstName + lastName + uniqueId;

createContact(
  {
     id: primaryKey
     ...
  }
)
```

**Comment by janhesters** [comment]
@ajhool Thank you very much for your help. I'm going to look into these approaches 🙏
