### ISSUE TITLE
Amplify push for Angular fails

### ISSUE THREAD

**Issue by diegonat** [aws-amplify/amplify-cli#1497]
**Describe the bug**
amplify add auth
amplify push

the cloudformation process fails because nodejs6.10 is no longer supported by Lambda service.

CREATE_FAILED UserPoolClientLambda                                        AWS::Lambda::Function      Tue May 21 2019 16:12:12 GMT+0200 (Central European Summer Time) The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 6d8a9d59-7bd2-11e9-ac19-193f6e735be6)
⠙ Updating resources in the cloud. This may take a few minutes...

**Comment by diegonat** [comment]
outdated version of amplify. Resolved

**Comment by rohitbhardwaj** [comment]
Is Amplify push still broken? 

CREATE_FAILED UserPoolClientLambda                                           AWS::Lambda::Function      Mon May 27 2019 18:46:07 GMT-0400 (Eastern Daylight Time) The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 36ea103e-80d1-11e9-92fb-dbed7441121f)

**Comment by justinlevi** [comment]
@rohitbhardwaj do a code wide search in your project for `nodejs6.10` and update everywhere to `nodejs8.10`
