### ISSUE TITLE
No user Pool

### ISSUE THREAD

**Issue by tomptaylor** [aws-amplify/amplify-cli#1498]
Template format error: Unrecognized resource types: [AWS::Cognito::UserPool, AWS::Cognito::IdentityPoolRoleAttachment, AWS::Cognito::UserPoolClient, AWS::Cognito::IdentityPoo

**Comment by yuth** [comment]
@tomptaylor could you share the generated cloudformation file and parameter.json file. Please make sure you obfuscate sensitive information.

The file should be located in folder `<project-root>/amplify/backend/auth/<auth-resource-name>/` and it should be named `<cognito-some-random-id>-cloudformation-template.yml` and `paramaters.json`

**Comment by ajhool** [comment]
Possibly related, @tomptaylor #194 . Did you try adding Auth, Hosting, or Storage?

**Comment by kaustavghosh06** [comment]
@tomptaylor Please let us know if you're still stuck with this and feel free to re-open or comment on this thread for further help.
