### ISSUE TITLE
AWS Amplify not generating proper graphql input depth

### ISSUE THREAD

**Issue by dperconti** [aws-amplify/amplify-cli#1499]
**Which Category is your question related to?**
AWS Amplify code generation 

**What AWS Services are you utilizing?**

AWS Amplify API

**Provide additional details e.g. code snippets**

I am new to both graphql & AWS Amplify, so please forgive any ignorance :) 

I have a graphql schema like this:

```
    type Location @model @auth(rules: [{allow: owner}]){
      street: String
      city: String
      state: String
      zip: String
    }

    type Trip @model @auth(rules: [{allow: owner}]){
      id: String!
      ...
      location: Location
    }
```

I'm trying to create both the location and the trip at the same time with a mutation request like this:

```
    mutation {
      createTrip(input: {
          id: "someIdentifier",
          location: {
            street: "somewhere"
          }
      }) {
          id
          location {
            street
          }
      }
    }
```

But I'm getting an error like this:

```
    {
      "data": null,
      "errors": [
        {
          "path": null,
          "locations": [
            {
              "line": 2,
              "column": 21,
              "sourceName": null
            }
          ],
          "message": "Validation error of type WrongType: argument 'input' with value '...' contains a field not in 'CreateTripInput': 'location' @ 'createTrip'"
        }
      ]
    }
```

Checking the generated `schema.graphql` file, I see that there is indeed no `location` object on the input model:

```
    input CreateTripInput {
      id: String!
      ...
    }
```

How can I have amplify generate the proper input schema so that I can create both the Trip and the location objects at the same time?

### Other notes

- Manually updating the generated code in `/amplify/backend/api/myApi/build/schema.graphql` is not successful.
- Manually updating the schema in the dashboard works with:

```
input CreateTripInput {
         ...
	location: CreateLocationInput
}
```

**Comment by yuth** [comment]
@dperconti In your schema, I see that both `Trip` and `Location` have `model` directive. I don't see `@connection` directive connecting the `Trip` with `Location`. You may have to update your schema connecting to connect your models if you want them to be in 2 separate tables and want the ability to query `Trip` based on `Location`. Using 2 separate table you won't be able to create both `Trip` and `Location` in a single mutation
```graphql
    type Location @model @auth(rules: [{allow: owner}]){
      street: String
      city: String
      state: String
      zip: String
      trips: Trip @connection(name:"TripLocation")
    }

    type Trip @model @auth(rules: [{allow: owner}]){
      id: String!
      location: Location @connection(name:"TripLocation")
    }
```

If the `Location` data is very specific to a trip and you don't want to create a separate table, then get rid of `@model` directive from your `Location` type. Doing so would allow you to create Location as a part of same mutation
```graphql
    type Location {
      street: String
      city: String
      state: String
      zip: String

    }

    type Trip @model @auth(rules: [{allow: owner}]){
      id: String!
      location: Location
    }
```

**Comment by dperconti** [comment]
Perfect - the later recommendation was exactly what I needed. Do you recommend any resources that I can read up on to learn more about the different directive and their respective usages? Thank you again.

**Comment by yuth** [comment]
@dperconti we have the directives documented in https://aws-amplify.github.io/docs/cli/graphql#directives
