### ISSUE TITLE
Amplify codgen is not creating my custom resolvers

### ISSUE THREAD

**Issue by JoshMontgomery** [aws-amplify/amplify-cli#1503]
** What AWS Services are you utilizing? **
AppSync, DynamoDB, Lambdas

** Provide additional details e.g. code snippets **
I have an AppSync schema which I created on the AppSync console. I am building a react native mobile application and attempted to run the codgen command to generate my schema locally. It worked great, except some of the custom resolvers I had created did not get created locally and no longer function properly when a query is made. How can I utilize my custom resolvers and the codgen feature?

**Comment by yuth** [comment]
@JoshMontgomery what custom resolver did you add in the AppSync console? When you added those resolvers did you make any changes to your schema?

**Comment by JoshMontgomery** [comment]
@yuth I added a resolver to one of the fields of a type called Media. This was done on the AppSync console, however when I ran the codegen command the resolvers don't appear to be anywhere within my local project.

![image](https://user-images.githubusercontent.com/45075389/58198178-a9ed3a80-7c82-11e9-983a-028626388c23.png)

When I run the query from the AppSync console it works fine. If I run the query locally (after the codegen command is run) all fields of the Media type work fine except for those two resolvers I created

**Comment by yuth** [comment]
@JoshMontgomery Did you create your API using Amplify CLI's graphql-transformer? 

To give you more context,  does 2 things when dealing with AppSync API
1. GraphQL transformation which coverts your schema.graphql and generate resolvers, create a expanded schema (to include CRUDL operations from model) and generate CloudFormation resources which can be used for deployment
2. Codege which looks at your generated schema and generate statements(query, mutation and subscription) and client side types which makes it easier to make request to AppSync API.

So if you run just the codegen, it will update locally generated code if and only if there is some change in your schema. Any changes to resolver will not have any effect on codegen and amplify graphql-transformer is 1 way transform and we don't support syncing the changes from the existing API.

**Comment by JoshMontgomery** [comment]
@yuth I did not under the assumption that graphql transform wouldn't allow me to create models which require a dynamo table with a composite key?

**Comment by yuth** [comment]
@JoshMontgomery thanks. I supect this might be due having lower `maxDepth` set for codegen. Could you try running `amplify codegen --max-depth 4` and see if you do get the fields you're expecting.

**Comment by kaustavghosh06** [comment]
@JoshMontgomery Closing this issue for now, please let us know if you still are stuck with this issue. Hope @yuth's response helped.
