### ISSUE TITLE
GraphQL Transformer not generating Owner authorization rules for one-to-one AppSync connections

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1507]
**Describe the bug**
When connecting two models in a 1-to-1 relationship with the named @connection directive, Owner Authorization (`@auth`) rules are not created for the connection resolvers. This leads to an unauthorized error. 

Has the GraphQL transformer always been this way or is this a regression?

**schema.graphql**

```
type User
  @model
    @auth(
    rules: [
      {allow: owner, ownerField: "localOwner", mutations: [create, update, delete], queries: [get, list]},
      {allow: groups, groups: ["Admin"]}
    ]) 
{
  id: ID!          #alias to account
  localOwner: String!
  userProfile: UserProfile! @connection(name:"UserProfile")
  /* more */
}

type UserProfile @model 
    @auth(
    rules: [
      {allow: owner, ownerField: "localOwner", mutations: [create, update, delete], queries: [get, list]},
      {allow: groups, groups: ["Admin"]}
    ])  {
  id: ID! 
  localOwner: String!
  user: User! @connection(name:"UserProfile")
  /* more */
}
```

The getUser query correctly generates the owner authorization checks:

**Query.getUser.res.vtl (api/myApi/build)**
```
## [Start] Static Group Authorization Checks **
## Authorization rule: { allow: groups, groups: "["Admin"]" } **
#set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
#set( $allowedGroups = ["Admin"] )
#set($isStaticGroupAuthorized = $util.defaultIfNull($isStaticGroupAuthorized, false))
#foreach( $userGroup in $userGroups )
  #foreach( $allowedGroup in $allowedGroups )
    #if( $allowedGroup == $userGroup )
      #set( $isStaticGroupAuthorized = true )
    #end
  #end
#end
## [End] Static Group Authorization Checks **


## No Dynamic Group Authorization Rules **


## [Start] Owner Authorization Checks **
#set( $isOwnerAuthorized = $util.defaultIfNull($isOwnerAuthorized, false) )
## Authorization rule: { allow: owner, ownerField: "localOwner", identityField: "cognito:username" } **
#set( $allowedOwners0 = $ctx.result.localOwner )
#set( $identityValue = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
#if( $util.isList($allowedOwners0) )
  #foreach( $allowedOwner in $allowedOwners0 )
    #if( $allowedOwner == $identityValue )
      #set( $isOwnerAuthorized = true )
    #end
  #end
#end
#if( $util.isString($allowedOwners0) )
  #if( $allowedOwners0 == $identityValue )
    #set( $isOwnerAuthorized = true )
  #end
#end
## [End] Owner Authorization Checks **


## [Start] Throw if unauthorized **
#if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
  $util.unauthorized()
#end
## [End] Throw if unauthorized **

$util.toJson($context.result)
```

But the authorization rules (and with the constraints in my schema, I think the same authorization checks work) do not get created for the connection resolver:

**User.userProfile.res.vtl (api/myApi/build)**
```
## [Start] Static Group Authorization Checks **
## Authorization rule: { allow: groups, groups: "["Admin"]" } **
#set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
#set( $allowedGroups = ["Admin"] )
#set($isStaticGroupAuthorized = $util.defaultIfNull($isStaticGroupAuthorized, false))
#foreach( $userGroup in $userGroups )
  #foreach( $allowedGroup in $allowedGroups )
    #if( $allowedGroup == $userGroup )
      #set( $isStaticGroupAuthorized = true )
    #end
  #end
#end
## [End] Static Group Authorization Checks **


## No Dynamic Group Authorization Rules **


## No Owner Authorization Rules **


## [Start] Throw if unauthorized **
#if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
  $util.unauthorized()
#end
## [End] Throw if unauthorized **

$util.toJson($context.result)
```

**Additional context**
$ amplify -v
1.6.10

**Comment by jkeys-ecg-nmsu** [comment]
This also appears to be affecting one-to-many connections, but instead of generating resolvers that respond with 4xx errors they just always return empty `items` lists. (This was a major source of confusion, luckily our AppSync API is not production yet.)

**Comment by chrisl777** [comment]
This issue is happening for us as well. 

schema: 

```type Profile @model
    @auth(rules: [{allow: owner, ownerField: "userId"},
                  {allow: groups, groups: ["Admin"]}])
{
    id: ID!
    ...
    serviceId: ID
    service: Service @connection(name: "ProfileService", keyField: "serviceId")
    userId: ID
    user: User @connection(name: "ProfileUser", keyField: "userId")
    ...
}```

The resolver is missing the owner check for userId. 

Profile.service.res.vtl: 

```## [Start] Static Group Authorization Checks **
## Authorization rule: { allow: groups, groups: "["Admin"]" } **
#set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
#set( $allowedGroups = ["Admin"] )
#set($isStaticGroupAuthorized = $util.defaultIfNull($isStaticGroupAuthorized, false))
#foreach( $userGroup in $userGroups )
  #foreach( $allowedGroup in $allowedGroups )
    #if( $allowedGroup == $userGroup )
      #set( $isStaticGroupAuthorized = true )
    #end
  #end
#end
## [End] Static Group Authorization Checks **


## No Dynamic Group Authorization Rules **


## No Owner Authorization Rules **


## [Start] Throw if unauthorized **
#if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
  $util.unauthorized()
#end
## [End] Throw if unauthorized **

$util.toJson($context.result)```

**Comment by chrisl777** [comment]
@mikeparisstuff Any updates on a fix for this bug? It currently has rendered our site inoperative as our auth permissions are not correct.

**Comment by markalanbaker** [comment]
Any update on this would be helpful @mikeparisstuff.

**Comment by jkeys-ecg-nmsu** [comment]
@chrisl777 @markalanbaker if your auth directives are uniform across models (same owner field) you can just copy the owner authorization checks from the base resolvers (Query.getProfile, Mutation.createProfile) over to your connection resolvers. This should put you back into production at the very least.

**Comment by chrisl777** [comment]
@jkeys-ecg-nmsu Okay, we'll give that a try. I suppose that those checks we copy over could be overwritten by the Amplify CLI at some point? Would it be better to create custom resolvers?

**Comment by jkeys-ecg-nmsu** [comment]
Yes, future `amplify push`es will override those changes. It would probably be better to create custom resolvers, I'm not sure how you do those for connections and not queries/mutations against the base models though.

**Comment by mikeparisstuff** [comment]
@chrisl777 I'm not sure this is a bug. You're schema:

```graphql
type Profile @model
    @auth(rules: [{allow: owner, ownerField: "userId"},
                  {allow: groups, groups: ["Admin"]}])
{
    id: ID!
    ...
    serviceId: ID
    service: Service @connection(name: "ProfileService", keyField: "serviceId")
    userId: ID
    user: User @connection(name: "ProfileUser", keyField: "userId")
    ...
}
```

is putting the ownership authorization rule on the `Profile` type. The `Profile.service.res.vtl` resolver is fetching an object of type `Service` and thus does not follow the auth rules for `Profile` but instead follows the auth rules for `Service` which appears to have a static group authorization rule. The `Query.getProfile` resolvers should implement the check for `Profile` auth rules.

**Comment by mikeparisstuff** [comment]
@jkeys-ecg-nmsu What issue are you seeing exactly? There was a period where `@connection` fields could by-pass `@auth` rules placed on `@model`s but that path has since been protected and it sounds like that may be the confusion. Now `@auth` rules protect `@connection` paths which provides greater security to your API.

**Comment by houmark** [comment]
I'm pretty sure I hit this issue also.

Looks something like this.

**Model Application**
Main model, which is not directly queried by the user, but I want to grab a few fields from this model in the Interview query.

```graphql
type Application
  @model
  @searchable
  @key(name: "ByStatus", fields: ["status", "createdAt"], queryField: "itemsByStatus")
  @auth(rules: [{allow: groups, groups: ["admin"]}])
 {
  id: ID!
  name: String!
  status: ApplicationStatus!
  #.... more fields
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  lastUpdatedBy: User @connection
  interview: Interview
    @connection(name: "ApplicationInterview", sortField: "createdAt")
    # Tried without these rules here also, so I only had rules on the linked Interview->application field 
    @auth(rules: [
      { allow: owner, ownerField: "access", operations: [update, read]},
      { allow: groups, groups: ["admin"] }
    ])
  access: String
}
```


**Model Interview**
This is where I am quering with a Coginito user that has been given access to view the Interview with the `access` field.

```graphql

type Interview
  @model
  # @key(name: "ByOwner", fields: ["owner"], queryField: "itemsByOwner")
  @key(name: "ByHash", fields: ["hash"], queryField: "hash")
  @auth(rules: [

    # Defaults to use the "owner" field.
    { allow: owner },

    # Allow the owner to read and update
    { allow: owner, ownerField: "access", operations: [update, read] },

    # Admin users can access any operation
    { allow: groups, groups: ["admin"] }

    ])
  {
  id: ID!
  application: Application!
    @connection(name: "ApplicationInterview", sortField: "createdAt")
    @auth(rules: [
      { allow: owner, ownerField: "access", operations: [update, read]},
      { allow: groups, groups: ["admin"] }
    ])
  # ... more fields
  access: String
}
```

If I query from the Interview only, no problems. If I add:
```graphql
... fields
application {
  name
}
```
.... then I get the Unauthorized error pointing to the application field.

@mikeparisstuff Do you have any recommendations here? Did I hit the same issue as others in this thread?

**Comment by kaustavghosh06** [comment]
@houmark Are you seeing this error as an owner or admin?

**Comment by houmark** [comment]
Ugh, it's been a moment since I scratched this approach and moved to one that worked but I can confirm for sure it was as owner, but I think also admin.

**Comment by kaustavghosh06** [comment]
I beleive the` Interview @connection` field woudn't be able to access the Application model due to missing auth role specific to the owner - something like - `{ allow: owner, operations: [ read] }` on the Application model for the Interview @connection to read/query.

**Comment by houmark** [comment]
Would you mind trying to make a schema example of something that could work @kaustavghosh06 - then I'd be happy to test it out tonight and give feedback.

**Comment by mikeparisstuff** [comment]
```graphql
type Application
  @model
  @key(name: "ByStatus", fields: ["status", "createdAt"], queryField: "itemsByStatus")
  @auth(rules: [
      # This says you can only access an Application if you are an admin. 
      # This protects the @connection field too.
      {allow: groups, groups: ["admin"]},
      # This says you can only access an Application if you are the owner via the "access" field.
      # This also protects the connection but not any mutations.
      {allow: owner, ownerField: "access", operations: [read]},
  ])
 {
  id: ID!
  name: String!
  status: ApplicationStatus!
  #.... more fields
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  lastUpdatedBy: User @connection
  interview: Interview
    @connection(name: "ApplicationInterview", sortField: "createdAt")
  access: String
}

type Interview
  @model
  # @key(name: "ByOwner", fields: ["owner"], queryField: "itemsByOwner")
  @key(name: "ByHash", fields: ["hash"], queryField: "hash")
  @auth(rules: [

    # Only owners (via "owner" field) may view the interview.
    { allow: owner },

    # Allow the  (via "access") to read and update
    { allow: owner, ownerField: "access", operations: [update, read] },

    # Admin users can access any operation
    { allow: groups, groups: ["admin"] }

    ])
  {
  id: ID!
  application: Application!
    @connection(name: "ApplicationInterview", sortField: "createdAt")
    # These auth rules are protecting the `Interview.application` field based on
    # some information in the `Interview` object. This is different than the @auth rules
    # on `Application` because those auth rules are based on information in the `Application` object.
    # If the auth rule on Interview implements the check that you want then you don't need these.
    @auth(rules: [
      { allow: owner, ownerField: "access", operations: [update, read]},
      { allow: groups, groups: ["admin"] }
    ])
  # ... more fields
  access: String
}

```

**Comment by houmark** [comment]
Thanks @mikeparisstuff I will test this out tonight, but I can already say now that one thing I for sure did not have in my first attempt was the access field in both Models.

> With this as long as the user is marked in both access fields, your query will work as expected.
If this was the only part missing is hard to know as I don't know if I would hit another error after fixing it. It did cross my mind to add the `access` field to the other Model, but imho it should not be needed and I don't want the user to have access to the entire `Application`, only a few fields and only by accessing them through `Interview`. Is that at all possible now?

**Comment by houmark** [comment]
And this is becoming a good draft for updated docs on connection based Model access control :)

**Comment by houmark** [comment]
And I am curious on reading more on "There is another way to structure this but in order to avoid confusion I will stop." because that is field based access inside the Application? So I can control down to the field level what can be accessed?

**Comment by jkeys-ecg-nmsu** [comment]
I'm closing this because (1) `@connection` workflow correctly adds authorization to resolvers if you change from the legacy fields to the `operations` field, and (2) the `@key` directive seems to be much more popular and makes it easier to have a smaller schema. 

Feel free to re-open if you need this for tracking reasons

**Comment by tomrum** [comment]
I am having this problem too, have installed latest amplify. The owner field is not showing up in the appsync schema:

type Video @model {
id: ID!
video: String!
links: [BuyLink] @connection(keyName: "buyLinks", fields: ["id"])
}

type BuyLink @model( subscriptions: { level: public }), @auth (rules: [
{allow: owner, ownerField: "owner", operations: [create, update, delete, read]},
{allow: private, provider: iam, operations: [create, read, update, delete]}]),
@key(name: "buyLinks", fields: ["videoId", "link", "second"])  {
id: ID!
videoId: ID!
link: String!
second: Int!
votes: [Vote] @connection(keyName: "votes", fields: ["id"])
show: Boolean!
}

type Vote @model
@key(name: "votes", fields: ["BuyLinkId", "vote"]) {
id: ID!
BuyLinkId: ID!
vote: Int!
}

I want to have public read only for BuyLink model and owner having all privelege on BuyLink they have created. Then when that works I want same access for Video and Vote Models. Help please.

**Comment by jkeys-ecg-nmsu** [comment]
Hi @tomrum can you open a new issue to track this?
