### ISSUE TITLE
Big CloudFormation Template 

### ISSUE THREAD

**Issue by Ahmed2Game** [aws-amplify/amplify-cli#151]
**Describe the bug**
I have bug when i need to push my api i have very big schema.graphql file so i get this error when try push 

```
CREATE_IN_PROGRESS apiknightswar AWS::CloudFormation::Stack Tue Sep 11 2018 01:19:38 GMT+0200 (Eastern European Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               apiknightswar            AWS::CloudFormation::Stack Tue Sep 11 2018 01:19:40 GMT+0200 (Eastern European Standard Time) Template may not exceed 460800 bytes in size.               
UPDATE_ROLLBACK_IN_PROGRESS knightsar-20180911010749 AWS::CloudFormation::Stack Tue Sep 11 2018 01:19:40 GMT+0200 (Eastern European Standard Time) The following resource(s) failed to create: [apiknightswar].
```
so How to skip this problem ?

**Comment by Ahmed2Game** [comment]
The solution is to build cloudformation-template.json in cloudformation-template.yml size will be very small so need from amplify api gql-compile make cloudformation in YAML not in JSON who make it

**Comment by Ahmed2Game** [comment]
I have done the process manually and make cloudformation-template.yml put when use it get this problem
Template format error: Number of resources, 256, is greater than maximum allowed, 200
so we need options for big projects

**Comment by Ahmed2Game** [comment]
so we need add feature check if cloudformation template is not equal limit nested it to more one template

**Comment by Ahmed2Game** [comment]
we have problem with _ Template format error: Resource name Alliancecreator_player_idResolver is non alphanumeric.

**Comment by mikeparisstuff** [comment]
This is a known limitation that we are working towards solving with nested stacks. I have commented more on this in previously closed issues and mention the limits here https://github.com/aws-amplify/amplify-cli/pull/115.

**Comment by Ahmed2Game** [comment]
@mikeparisstuff  thanks for you but i work now in my project are you will get solution soon ?

**Comment by kaustavghosh06** [comment]
This is a duplicate issue. Tracking this issue as a part of #185
