### ISSUE TITLE
Amplify push is failing when testing the new feature/@key branch

### ISSUE THREAD

**Issue by stefantul** [aws-amplify/amplify-cli#1510]
I followed the steps specified in testing-custom-indexes.md, did amplify add api, got an error here:

` What attributes are required for signing up? (Press <space> to select, <a> to toggle all, <i> to invert selection)Email
Error: ENOENT: no such file or directory, open '/home/stefan/Coding/Tests/vido/testing-key/amplify/backend/auth/testingkeya59f6fdb/parameters.json'
`

Continued with amplify push and got:

`CREATE_FAILED               apitestingAPI                         AWS::CloudFormation::Stack Thu May 23 2019 11:43:51 GMT+0200 (EET) Parameters: [S3DeploymentBucket, S3DeploymentRootKey] must have values
`

**Comment by mikeparisstuff** [comment]
Hmm I am not seeing this locally but I have just rebased the repo off of master and fixed a few things that were upsetting circle CI. Can you pull and try again?

**Comment by stefantul** [comment]
I've tested again and it seems to be working now, thanks.

**Comment by mikeparisstuff** [comment]
Great!
