### ISSUE TITLE
S3Key changes after every function push

### ISSUE THREAD

**Issue by slaat** [aws-amplify/amplify-cli#1511]
** Which Category is your question related to? **
Function

** Provide additional details e.g. code snippets **
After every amplify push the S3Key of each function that has been changed gets updated which means that when I try to merge it, I have to look through the files and revert the s3Key changes (since I do not want to merge these). 

Is there any workaround or some way to get this data into a separate file? I am currently working in a team of two and we have our own branches and environments and a dev branch to which we are constantly merging to.

**Comment by kaustavghosh06** [comment]
Duplicate of #1194 
Closing this is favor of #1194.
