### ISSUE TITLE
Federated login secrets should not be stored in files that might be committed

### ISSUE THREAD

**Issue by jugglingcats** [aws-amplify/amplify-cli#1512]
**Is your feature request related to a problem? Please describe.**
When adding Facebook, Google, etc, using the CLI it prompts for app ids and secrets. This information is put into `nested-cloudformation-stack.yml` and `team-provider-info.json`. I can see in answer to https://github.com/aws-amplify/docs/issues/267 that the first of these is added to `.gitignore` but not the latter.

**Describe the solution you'd like**
I guess that `team-provider-info.json` could be added to `.gitignore` but this contains other information that should/could be checked in and is not very easily re-created.

**Additional context**
It should be possible to easily move an Amplify project from one PC to another via source control while manually re-creating the minimum amount of config (ie. only that which is secret).

**Comment by yuth** [comment]
You should put `team-provider-info.json` in `.gitignore` file if you're sharing your project publicly as [documented](https://aws-amplify.github.io/docs/cli/multienv?sdk=js#teamprovider)
> If you want to share a project publicly and open source your serverless infrastructure, you should remove or put the amplify/team-provider-info.json file in gitignore file.
