### ISSUE TITLE
DELETE_FAILED HostedUICustomResourceInputs

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-cli#1513]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, Auth, Hosted UI

** Provide additional details e.g. code snippets **
I am trying to push auth updates but receiving DELETE_FAILED messages. I have modified the CSS of the Hosted UI, added some custom attributes to my user pool, but nothing out of the ordinary.

DELETE_IN_PROGRESS HostedUICustomResourceInputs AWS::CloudFormation::CustomResource Thu May 23 2019 11:59:06 GMT-0400 (Eastern Daylight Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

DELETE_FAILED HostedUICustomResourceInputs AWS::CloudFormation::CustomResource Thu May 23 2019 11:59:09 GMT-0400 (Eastern Daylight Time) Failed to delete resource. See the details in CloudWatch Log Stream: 2019/05/23/[$LATEST]xxx

**Comment by kaustavghosh06** [comment]
@cliffordh I would need to see your parameters.json file and your Cloudformation file to rootcause this as the deffault cases work for me.
Would be also great to now the exact changes you've made to these files. Thanks!

**Comment by phlinhng** [comment]
Same problem HostedUICustomResourceInputs CREATE_FAILED and DELETE_FAILED

**Comment by kaustavghosh06** [comment]
@phlinhng Did you check the Cloudwqtch logs to find the error? I might be that the hosted UI domain name is not unique causing the stack to fail.

**Comment by phlinhng** [comment]
@kaustavghosh06 I checked but I can't figure how can my hosted UI domain be not unique (I didn't even know what hosted UI domain is for!). I think it was generate by `amplify add auth`. This happened after I start to create an auth.

**Comment by kaustavghosh06** [comment]
@phlinhng if you could share your CloudWatch error logs, we can see what went wrong in the deployment.

**Comment by phlinhng** [comment]
@kaustavghosh06 Thanks for helping! Sorry I don't know how to export it beautifully as a text file.
Is this working?

2019-05-29 | 状态 | 类型 | 逻辑 ID | 状态原因
-- | -- | -- | -- | --
21:33:22 UTC+0800UPDATE_ROLLBACK_COMPLETEAWS::CloudFormation::Stackawsmobileandroidnote-cloudclase-2019052921102221:30:06 UTC+0800DELETE_FAILEDAWS::CloudFormation::Stackauthawsmobileandroidnoted09d5119Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs].21:29:26 UTC+0800UPDATE_ROLLBACK_IN_PROGRESSAWS::CloudFormation::Stackawsmobileandroidnote-cloudclase-20190529211022The following resource(s) failed to create: [authawsmobileandroidnoted09d5119].21:29:25 UTC+0800CREATE_FAILEDAWS::CloudFormation::Stackauthawsmobileandroidnoted09d5119Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs, HostedUIProvidersCustomResourceInputs].21:25:47 UTC+0800UPDATE_ROLLBACK_COMPLETEAWS::CloudFormation::Stackawsmobileandroidnote-cloudclase-20190529211022实体 ID:arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022/1e722f60-8213-11e9-8195-0a4c9dfbdd9421:22:33 UTC+0800DELETE_FAILEDAWS::CloudFormation::Stackauthawsmobileandroidnoted09d5119Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs].21:21:52 UTC+0800UPDATE_ROLLBACK_IN_PROGRESSAWS::CloudFormation::Stackawsmobileandroidnote-cloudclase-20190529211022The following resource(s) failed to create: [authawsmobileandroidnoted09d5119].21:21:51 UTC+0800CREATE_FAILEDAWS::CloudFormation::Stackauthawsmobileandroidnoted09d5119Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs]. |   | 21:33:22 UTC+0800 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 |   |   | 21:30:06 UTC+0800 | DELETE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs]. |   | 21:29:26 UTC+0800 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 | The following resource(s) failed to create: [authawsmobileandroidnoted09d5119]. |   | 21:29:25 UTC+0800 | CREATE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs, HostedUIProvidersCustomResourceInputs]. |   | 21:25:47 UTC+0800 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 |   |   | 实体 ID:arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022/1e722f60-8213-11e9-8195-0a4c9dfbdd94 |   | 21:22:33 UTC+0800 | DELETE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs]. |   | 21:21:52 UTC+0800 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 | The following resource(s) failed to create: [authawsmobileandroidnoted09d5119]. |   | 21:21:51 UTC+0800 | CREATE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs].
  | 21:33:22 UTC+0800 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 |  
  | 21:30:06 UTC+0800 | DELETE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs].
  | 21:29:26 UTC+0800 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 | The following resource(s) failed to create: [authawsmobileandroidnoted09d5119].
  | 21:29:25 UTC+0800 | CREATE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46 was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs, HostedUIProvidersCustomResourceInputs].
  | 21:25:47 UTC+0800 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 |  
  | 实体 ID:arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022/1e722f60-8213-11e9-8195-0a4c9dfbdd94
  | 21:22:33 UTC+0800 | DELETE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully deleted: The following resource(s) failed to delete: [HostedUICustomResourceInputs].
  | 21:21:52 UTC+0800 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | awsmobileandroidnote-cloudclase-20190529211022 | The following resource(s) failed to create: [authawsmobileandroidnoted09d5119].
  | 21:21:51 UTC+0800 | CREATE_FAILED | AWS::CloudFormation::Stack | authawsmobileandroidnoted09d5119 | Embedded stack arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-1EQC89GKN1O2P/66cba650-8214-11e9-badb-0a3569efe79e was not successfully created: The following resource(s) failed to create: [HostedUICustomResourceInputs].

**Comment by kaustavghosh06** [comment]
@phlinhng this is the Cloudformation log. The Hosted UI functionality is to mocked through a Lambda function, which logs its error in a service called CloudWatch. You would have to go the AWS console and checkout the CloudWatch logs to narrow down the issue.

**Comment by kaustavghosh06** [comment]
As you can see the in the reason section it mentions to check CloudWatch logs for more details - ‘Failed to delete resource. See the details in CloudWatch Log Stream: 2019/05/29/[$LATEST]’

That link below  ties in to your CloudFormation stack, but for more details for deployment failures (in some cases like yours), you would have to dig through CloudWatch logs since Cloudformation doesn’t provide detailed information about the failure.

**Comment by phlinhng** [comment]
here it was.

13:29:07
START RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0 Version: $LATEST
START RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0 Version: $LATEST

13:29:09
2019-05-29T13:29:08.970Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	{ InvalidParameterException: Domain cannot contain reserved word: aws at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor
2019-05-29T13:29:08.970Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	{ InvalidParameterException: Domain cannot contain reserved word: aws
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Domain cannot contain reserved word: aws',
code: 'InvalidParameterException',
time: 2019-05-29T13:29:08.969Z,
requestId: 'bd138dc3-8215-11e9-a8e2-31213b0aedd6',
statusCode: 400,
retryable: false,
retryDelay: 55.69807442487216 }

13:29:09
2019-05-29T13:29:09.040Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Response body: {"Status":"FAILED","Reason":"See the details in CloudWatch Log Stream: 2019/05/29/[$LATEST]452c704296e54217b073e359cce75630","PhysicalResourceId":"2019/05/29/[$LATEST]452c704296e54217b073e359cce75630","StackId":"arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobi
2019-05-29T13:29:09.040Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Response body:
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2019/05/29/[$LATEST]452c704296e54217b073e359cce75630",
    "PhysicalResourceId": "2019/05/29/[$LATEST]452c704296e54217b073e359cce75630",
    "StackId": "arn:aws:cloudformation:us-east-1:378898728638:stack/awsmobileandroidnote-cloudclase-20190529211022-authawsmobileandroidnoted09d5119-IYREWJESJK35/826211a0-8215-11e9-b24a-0e3ecaa51b46",
    "RequestId": "7b6cc3a3-939f-4ed1-9eba-330c025790f8",
    "LogicalResourceId": "HostedUICustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "Domain cannot contain reserved word: aws",
            "code": "InvalidParameterException",
            "time": "2019-05-29T13:29:08.969Z",
            "requestId": "bd138dc3-8215-11e9-a8e2-31213b0aedd6",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 55.69807442487216
        }
    }
}


13:29:09
2019-05-29T13:29:09.180Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Status code: 200
2019-05-29T13:29:09.180Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Status code: 200

13:29:09
2019-05-29T13:29:09.180Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Status message: OK
2019-05-29T13:29:09.180Z	b8194c55-ec10-4a90-80ce-d2b169dba7f0	Status message: OK

13:29:09
END RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0
END RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0

13:29:09
REPORT RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0	Duration: 1996.01 ms	Billed Duration: 2000 ms Memory Size: 128 MB	Max Memory Used: 73 MB
REPORT RequestId: b8194c55-ec10-4a90-80ce-d2b169dba7f0	Duration: 1996.01 ms	Billed Duration: 2000 ms Memory Size: 128 MB	Max Memory Used: 73 MB	

13:29:35
START RequestId: dc3c4674-d64a-4731-b419-b97fced3fe41 Version: $LATEST
START RequestId: dc3c4674-d64a-4731-b419-b97fced3fe41 Version: $LATEST

13:29:36
2019-05-29T13:29:36.173Z	dc3c4674-d64a-4731-b419-b97fced3fe41	{ InvalidParameterException: No such domain or user pool exists. at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:7
2019-05-29T13:29:36.173Z	dc3c4674-d64a-4731-b419-b97fced3fe41	{ InvalidParameterException: No such domain or user pool exists.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'No such domain or user pool exists.',
code: 'InvalidParameterException',
time: 2019-05-29T13:29:36.173Z,
requestId: 'cd4a8d81-8215-11e9-aeac-05eafdf2891e',
statusCode: 400,
retryable: false,
retryDelay: 87.34838572013315 }

**Comment by kaustavghosh06** [comment]
Ah! As you can see the error is - InvalidParameterException: Domain cannot contain reserved word: aws
As a workaround, if you check your ‘<project-root>/amplify/auth/<resource-name>/parameters.json’, you’ll find a HostedUIDomainName key out there. If you remove ‘aws’ from that name, your deployment should succeed. I’ll mark this as a bug since the CLI should have validations when adding auth to avoid this type of error.

**Comment by trantiendat** [comment]
@kaustavghosh06 
Could I re-open this issue ? Because I meet the same problem too. But reserve word is not "aws", this time is "cognito".

![Screen Shot 2020-03-06 at 2 10 14 PM](https://user-images.githubusercontent.com/8804935/76060669-60bd6b80-5fb4-11ea-8916-ed09b58f84dd.png)
