### ISSUE TITLE
Improve sharing project workflow

### ISSUE THREAD

**Issue by lorensr** [aws-amplify/amplify-cli#1514]
(The following is in a single-env amplify project)

**Is your feature request related to a problem? Please describe.**

1. I make an amplify-related change and `amplify push`
2. I git commit and push
3. Teammates `git pull` and run the new code, and get various errors
4. Teammates figure out they need to run `amplify push`

**Solution A**

Change the default to be that teammates don't need to run `amplify push`.

**Solution B**

If A is not made the default, then:

- document how to set A up, eg a list of files to remove from `.gitignore`
- print a standard error in step 3 like "Your configuration is out of date. Run `amplify push`"

**Comment by slaat** [comment]
is the teammate doing amplify pull? I guess the error is, that the aws-exports.js file is not updating, correct?

**Comment by lorensr** [comment]
I don't know if that's the cause of the various errors. They're not running `amplify pull`, but regardless of whether the command is `amplify push` or `amplify pull`, I think the step 3-4 problem remains.

**Comment by slaat** [comment]
Well it depends. There is a reason why aws-exports.js is not included in git. It has to be generated in some way and that would be amplify pull/push

**Comment by ykethan** [comment]
Hey @lorensr , Since the team is sharing the same dev backend, periodically team members would need to pull in changes which their team members pushed for the dev environment to be in sync. Please refer to https://docs.amplify.aws/cli/teams/shared/ for additional information. Please do let us know if this aligns to your use case.

**Comment by lorensr** [comment]
@ykethan you're accurately describing the problem. The error message described above would resolve this DX FR

**Comment by josefaidt** [comment]
Hey @lorensr :wave: this is a great callout, and as we continue to improve our team-focused multi-env story we've added the `ops-multienv` label to track this alongside those efforts. In the mean time we will close this issue
