### ISSUE TITLE
CLI option to automatically confirm code generation

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#1515]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/686823/58294119-f5d8d600-7d8d-11e9-9a7e-1ee26e3e842c.png)

I want to be able to set a config flag or pass a CLI argument to automatically mark both of the above questions as Yes and continue the push.

**Comment by jkeys-ecg-nmsu** [comment]
`amplify push --yes`
