### ISSUE TITLE
Why @connection is creating GSI ?

### ISSUE THREAD

**Issue by rajababu3** [aws-amplify/amplify-cli#152]
**Which Category is your question related to?**
General Issue
**What AWS Services are you utilizing?**
API
**Provide additional details e.g. code snippets**

Below is the snippet I used to create a connection 
`
type User @model {
  cognitoId: ID!
  id: ID!
  username: String!
  email: AWSEmail
}
`

``
type Project @model {
  createdBy: User @connection
  members: [User] @connection
  invited: [User] @connection
  requested: [User] @connection
  ...
}
``

Why @connection is creating GSI? 
I am getting error 
`
InvalidDirectiveError: Cannot create connection Project.requested. Table [object Object] out of GSI capacity.
    at ResourceFactory.updateTableForConnection (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/resources.ts:41:19)
    at ModelConnectionTransformer._this.field (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql-connection-transformer/src/ModelConnectionTransformer.ts:195:44)
    at GraphQLTransform.transformField (/private/var/folders/mk/36m2f9gx7h5bblhkkx68fv1ck8cth9/T/tmp.QRmIY8in/amplify-cli/packages/graphql-transformer-core/src/GraphQLTransform.ts:293:33)
    at GraphQLTransform.transformObject (/private/var/folders/mk/36m2f9gx7h5bblhkkx68fv1ck8cth9/T/tmp.QRmIY8in/amplify-cli/packages/graphql-transformer-core/src/GraphQLTransform.ts:277:22)
    at GraphQLTransform.transform (/private/var/folders/mk/36m2f9gx7h5bblhkkx68fv1ck8cth9/T/tmp.QRmIY8in/amplify-cli/packages/graphql-transformer-core/src/GraphQLTransform.ts:220:34)
    at transformGraphQLSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:97:25)
    at Object.compileSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/utility-functions.js:10:40)
    at Object.executeProviderUtils (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/execute-provider-utils.js:7:52)
    at updateWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:233:25)
    at <anonymous>
There was an error updating the API resource
`

**How can I prevent it from creating GSI ?**

**Comment by mikeparisstuff** [comment]
The reason @connection makes a GSI is to enable efficient lookups of connected objects. For example, to allow **Post** objects to have many **Comment** objects we create a GSI on the **Comment** table's *postId* attribute so we can quickly query all **Comments** for a given post. It is not currently possible to disable creating GSIs but it is technically possible to allow you to specify which index to use but this has also not been implemented. The side effect of this is that the limit of 5 GSIs can impact how many connections you can have on a single type.

Can you share more information about your schema and use case so we can think about how to address the concern? Thanks.

**Comment by rajababu3** [comment]
Thanks for the response @mikeparisstuff!

My use case is simple:

I have Project model  which contains 4 fields that has reference to user model like below:

type User @model {
  cognitoId: ID!
  id: ID!
  username: String!
  email: AWSEmail
  phone: AWSPhone
  ip: AWSIPAddress
  online: Boolean
}

type Group @model {
  id: ID!
  name: String!
  photoURL: String
  description: String
  createdBy: User @connection
  members: [User] @connection
  invited: [User] @connection
  requested: [User] @connection
  type: GroupType!
  email: AWSEmail
  url: AWSURL
  phone: AWSPhone
  ip: AWSIPAddress
  projects: [Project] @connection(name: "GroupProjects")
}

type Project @model @searchable {
  id: ID!
  name: String!
  photoURL: String
  description: String
  createdBy: User @connection
  members: [User] @connection
  invited: [User] @connection
  requested: [User] @connection
  type: ProjectType!
  startTs: AWSDateTime
  dueTs: AWSDateTime
  endTs: AWSDateTime
  email: AWSEmail
  url: AWSURL
  phone: AWSPhone
  ip: AWSIPAddress
  group: Group! @connection(name: "GroupProjects")
}

I don't want back reference to user model so I haven't used **named** **connection**. 
Above code is generating error. Table out of capacity.

**Comment by mikeparisstuff** [comment]
Gotcha. Unfortunately, you can't have that many @connection fields on a single @model for now. In the future, we are looking into offering an association list pattern as an alternative to the GSI pattern for APIs that are more highly connected.

**Comment by MatthieuLab** [comment]
Hi @kaustavghosh06 

Any news on this topic? We have the same problem here

**Comment by grudra7714** [comment]
@kaustavghosh06  @mikeparisstuff 

Confused, i was able to compile this model successfully 
```
type Application @model {
    id: ID!
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    year: String!
    deleted: Boolean
    
    # Application has a 1:M relationship with Model1
    model1: [Model1] @connection

    # Application has a 1:M relationship with Model2
    model2: [Model2] @connection

    # Application has a 1:M relationship with Model3
    model3: [Model3] @connection

    # Application has a 1:M relationship with Model4
    model4: [Model4] @connection

    # Application has a 1:M relationship with Model5
    model5: [Model5] @connection

    # Application has a 1:M relationship with Model6
    model6: [Model6] @connection

    # Application has a 1:M relationship with Model7
    model7: [Model7] @connection


    fileConnection1: File @connection
    fileConnection2: File @connection
    fileConnection3: File @connection
    fileConnection4: File @connection
    fileConnection5: File @connection
    fileConnection6: File @connection

}
```

Initially in my model i had all the file connections like this
```

    fileConnection1: [File] @connection
    fileConnection2: [File] @connection
    fileConnection3: [File] @connection
    fileConnection4: [File] @connection
    fileConnection5: [File] @connection
    fileConnection6: [File] @connection
```
 When i tried to compile the schema, it gave me `Table [object Object] out of GSI capacity. ` error. 

My question is, Is the limitation on multiple 1:M relationship with a single model?
If it is then *how many* 1:M connections we can use?
(Also why 1:1 relationship worked?)

(Sorry i had to make all field names vague, but you get the point)

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.
