### ISSUE TITLE
Team workflow between windows and unix devices

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1522]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
When creating a project in Windows, then working on the same project in unix system (i.e. Ubuntu), when doing an _amplify api push_ it creates a src\graphql directory. This is due to Windows using backslash while unix has forward slash for accessing directories.

**To Reproduce**
1. create an amplify project in Windows
2. push to version control
3. clone in Ubuntu or your linux flavor of choice
4. amplify init
5. push an api update
6. Will generate a directory called src\graphql

**Expected behavior**
Should know the difference between windows and ubuntu directory structure

**Screenshots**
![image](https://user-images.githubusercontent.com/48229482/58390055-cfeb5400-8061-11e9-95cf-a9df60d4f0aa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04 and Windows 10 Pro
 - Amplify cli version 1.6.9

**Additional context**
There's a related bug within amplify/.config/project-config.json where the BuildCommand and StartCommand uses _npm.cmd_ (since project was initially created in Windows) and this command doesn't work on Linux.

`"BuildCommand": "npm.cmd run-script build",
      "StartCommand": "npm.cmd run-script start"`

![image](https://user-images.githubusercontent.com/48229482/58390177-72a3d280-8062-11e9-9c22-1d7ee86efe4f.png)

**Comment by nino-moreton** [comment]
Hi could we reopen this please @UnleashedMind  @kaustavghosh06 .. As of v1.9.0, it's still generating 
```
"src\\graphql/"
"src\\graphql\\schema.json"
```

when doing `amplify api push`. It's even worse now cause the `schema.json` has also been affected.

**Comment by kaustavghosh06** [comment]
@nino-moreton I just now generated a GraphQL API using the latest CLI version and the schem.json files were generated correctly.

```

CREATE_COMPLETE mytest2-dev-20190801171542-apimytest2-1Y194FTLF66FO AWS::CloudFormation::Stack Thu Aug 01 2019 17:19
GMT-0700 (Pacific Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE apimytest2 AWS::CloudFormation::Stack Thu Aug 01 2019 17:19:27 GMT-0700 (Pacific Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS mytest2-dev-20190801171542 AWS::CloudFormation::Stack Thu Aug 01 2019 17:19:29 G
700 (Pacific Daylight Time)
UPDATE_COMPLETE                     mytest2-dev-20190801171542 AWS::CloudFormation::Stack Thu Aug 01 2019 17:19:30 G
700 (Pacific Daylight Time)
√ All resources are updated in the cloud

GraphQL endpoint: https://v4qnuejncjgttknx72nup72nwi.appsync-api.us-west-2.amazonaws.com/graphql
GraphQL API KEY: da2-sgzfyoo7onc7tke3drarbin7qa

√ Downloaded the schema
√ Generated GraphQL operations successfully and saved at src\graphql
PS D:\Users\kaustavg\mytest2>
PS D:\Users\kaustavg\mytest2>
PS D:\Users\kaustavg\mytest2>
PS D:\Users\kaustavg\mytest2>
PS D:\Users\kaustavg\mytest2> ls


    Directory: D:\Users\kaustavg\mytest2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         8/1/2019   5:16 PM                amplify
d-----         8/1/2019   5:19 PM                src
-a----         8/1/2019   5:16 PM            205 .gitignore
-a----         8/1/2019   5:19 PM            267 .graphqlconfig.yml


PS D:\Users\kaustavg\mytest2> cd src
PS D:\Users\kaustavg\mytest2\src> ls


    Directory: D:\Users\kaustavg\mytest2\src


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         8/1/2019   5:19 PM                graphql
-a----         8/1/2019   5:19 PM            457 aws-exports.js


PS D:\Users\kaustavg\mytest2\src> cd .\graphql\
PS D:\Users\kaustavg\mytest2\src\graphql> ls


    Directory: D:\Users\kaustavg\mytest2\src\graphql


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         8/1/2019   5:19 PM            520 mutations.js
-a----         8/1/2019   5:19 PM            456 queries.js
-a----         8/1/2019   5:19 PM          53086 schema.json
-a----         8/1/2019   5:19 PM            427 subscriptions.js


PS D:\Users\kaustavg\mytest2\src\graphql>
```

Does this happen only when you're developing on a unix machine and then start using the same directory on a windows machine? What would be the steps to reproduce this?

**Comment by nino-moreton** [comment]
@kaustavghosh06  yes this particular Amplify project was created in Windows and I only used Ubuntu more recently. 

I'm thinking possible reproduction steps (can't test this right now since I only have my Ubuntu machine right now) are the ff:

1. Initiate a new amplify project in Windows. Add GQL models in the schema, push to git and amplify.
2. Pull the project in Ubuntu, amplify init, amplify pull --restore. Then when everything is in sync, make a change to the schema (any change that generates new queries/mutations) 
3. See error.
