### ISSUE TITLE
Remove aws-sdk from functions as default library

### ISSUE THREAD

**Issue by slaat** [aws-amplify/amplify-cli#1525]
**Is your feature request related to a problem? Please describe.**
The total size of a lambda function (dist file) is at about 8MB. Most of it is because of the aws-sdk library that is being included. Lambda Functions have this library preinstalled which means that this is not necessary. 

**Describe the solution you'd like**
Remove the aws-sdk as a default from the package.json dependencies

**Additional context**
Dist file size before: 8mb
Dist file size after: 700kb

Function folder size before: 45mb
Function folder size after: 3mb

The total size can be reduced by over 90%. My overall project size (a project with 17 functions) has reduced by ~800mb, which makes a huge difference.

**Comment by kstro21** [comment]
Ideally, `aws-sdk` is added in **package.json** as a **devDependencies**, later, in the process of _zipping_, only **production** dependencies are added, by using `npm install --production`.

**Comment by slaat** [comment]
That would still add about 40mb of data to the node_modules of each lambda function...
