### ISSUE TITLE
How do I create a composite key in graphql.schema?

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1528]
** Which Category is your question related to? **
AWS Amplify

** What AWS Services are you utilizing? **
API Gateway, DynamoDB, Lambda

** Provide additional details e.g. code snippets **
I just want to be able to specify 2 fields to be the primary key in for a given type in graphql.schema. Is this already available and I'm missing it?

**Comment by dancomanlive** [comment]
Maybe this is a possible answer: https://github.com/aws-amplify/docs/pull/689/files

**Comment by kaustavghosh06** [comment]
@rawadrifai We're soon be merging the custom indexes PR which would help with your case. I'll update this thread after the release.

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.

**Comment by rawadrifai** [comment]
Looks great!

**Comment by mjza** [comment]
@kaustavghosh06 
Custom indexes are not composite key. In the custom indexes still we have only the first column as the key. And the rest for sorting. Assume I need to index based on two columns! What is the solution?
