### ISSUE TITLE
Resource Updates are not consistent with GraphQL Schema and result in Validation Errors

### ISSUE THREAD

**Issue by selipso** [aws-amplify/amplify-cli#1529]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
Suppose I have a schema like the following:

```
type TodoItems {
  lastItem: Item
  items: [Item]
  id: ID!
}
type Item {
  id: ID!
  value: String
}
```

Now I replace the 'lastItem' field in TodoItems with `lastItem: String` to make the logic easier.

When making a request to the backend now, for some reason the older field type is still there in the resolvers and I get the following error when making a new request:

`"Validation error of type SubSelectionNotAllowed: Sub selection not allowed on leaf type String of field source @ 'createItem/lastItem'"`

**Expected behavior**
Resolver should update with the new field type even if the key is shared

**Comment by kaustavghosh06** [comment]
@selipso What is the query that you're running? Did you update your queries - if using codegen after changing the annotated schema?

**Comment by selipso** [comment]
I received the above error after updating the codegen. With the queries, I got a different error on the client side that prevented me from sending the request. The above message occurred as a response from AWS after a successful request. I had to create a new backend server with the updated schema to get rid of the above error.

**Comment by selipso** [comment]
I've noticed after version 1.7 this occurs much less and haven't been able to reproduce it since. Keep up the great work guys.
