### ISSUE TITLE
How to use same backend with multiple web projects and Amplify Console

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#1534]
** Which Category is your question related to? **
env and/or configure

** What AWS Services are you utilizing? **
CLI with console

** Provide additional details e.g. code snippets **
Related to this link: https://aws-amplify.github.io/docs/cli/init#amplify-configure-project

How is this supposed to be used when pushing to a multi-env project with the Amplify Console?  When I attempt to utilize the same backend for another project, it tries to re-create all the same resources and fails because they all already exist.  Please advise.  Thanks!

**Comment by kaustavghosh06** [comment]
@mwarger In your Amplify Console don't you get an option to select form your exisiting backends when you connect your repo? If you have checked in your team-provider-info.json file which is located in your amplify/ dir, you should be able to select from exisiting backends.

**Comment by mwarger** [comment]
This was a pre-existing project that I added the backend to.  I was doing it all manually before.  Can I do this in the build settings somewhere or do I need to kill the project and redo it?

**Comment by mwarger** [comment]
![image](https://user-images.githubusercontent.com/686823/58523139-f7890c00-8188-11e9-8348-2cc6919aad5d.png)

I get this when trying to connect my dev branch - I cannot choose any of the branches I have in the CLI for the other project, only the local one I'm using for development...  is this correct?

**Comment by kaustavghosh06** [comment]
You let the Console create it (using the CLI) you mean?

**Comment by mwarger** [comment]
@kaustavghosh06 Yes.

**Comment by kaustavghosh06** [comment]
Okay..then you would have to import these environments locally so that it shows up on that list on Amplify Console.

**Comment by mwarger** [comment]
How do I do that?

**Comment by kaustavghosh06** [comment]
https://github.com/aws-samples/create-react-app-auth-amplify#run-locally-with-the-amplify-cli

**Comment by mwarger** [comment]
Gotcha, I will give that a try this evening and report back.  Thank you.

**Comment by kaustavghosh06** [comment]
@mwarger Did you give it a try?

**Comment by mwarger** [comment]
I did, but I had some trouble with the environment where in the amplify console said it was trying to reference resources that did not exist. I'm going to try it again this evening after pushing an update.

**Comment by mwarger** [comment]
I got this working and it's great!  Thank you for your help!
