### ISSUE TITLE
How do I append to an array field in graphQL mutations? 

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1537]
** Which Category is your question related to? **
GraphQL Mutations

** What AWS Services are you utilizing? **
Amplify, DynamoDB, API Gateway

** Provide additional details e.g. code snippets **
In mutations.js I have something like this: 
```
export const updateChannel = mutation UpdateChannel($input: UpdateChannelInput!) {
  updateChannel(input: $input) {
    id
    description
    users
  }
};
```

users is an array of strings. How do I append an item without having to replace the whole array  every time?

**Comment by wizawuza** [comment]
This probably isn't the answer you want to hear, but one way is to do it server-side in the resolvers.
If you want to stick to VTL, check this out:
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-resolvers.html#modifying-the-updatepost-resolver-dynamodb-updateitem

Search for "list_append" on that page.

Or you can make a new mutation in lambda/node.js which may be easier but less efficient.

I'm not personally aware of a way to do it client-side other than what you are trying to avoid already (replace the whole array every time), but I'd be interested in hearing if someone else has an answer.

**Comment by rawadrifai** [comment]
so luckily, they just released the support for @function which solves my problem. I can do all sorts of things with a lambda.
