### ISSUE TITLE
Calling 'amplify push' (REST API) when adding custom HTTP headers doesn't deploy the API

### ISSUE THREAD

**Issue by ericowlie** [aws-amplify/amplify-cli#1539]
**Describe the bug**
Let's say I add a custom HTTP header (Access-Control-Allow-Headers) for one of my Rest API route in my API '*-cloudformation-template.json'.
When I call 'amplify push', everything is uploaded correctly to the cloud, but when I call my route I get CORS error because my custom header isn't allowed.
I need to go in the AWS API Gateway console and click on 'Action => Deploy API' to make things work.

**To Reproduce**
Add a custom HTTP header (Access-Control-Allow-Headers) for your Rest API in your API '*-cloudformation-template.json'.
Call 'amplify push'
Call your route to have the error.
Go in AWS API Gateway Console and click 'Action => Deploy API'.
Call your route again => it works.

**Expected behavior**
I should not have to go in the AWS API Gateway Console to Deploy again the API when calling 'Amplify push'

**Desktop (please complete the following information):**
 - OS: Windows
 - Amplify-cli version : 1.6.11

**Comment by kaustavghosh06** [comment]
@ericowlie There is a specific Cloudformation resource for deploying the API, so ideally that resource should be called/invoked only aftert he custom HTTP header is deployed - so you would ideally need a dependsOn block in the Cloudformation for the deploy resource.
