### ISSUE TITLE
CREATE_FAILED [HostedUICustomResourceInputs, HostedUIProvidersCustomResourceInputs]

### ISSUE THREAD

**Issue by phlinhng** [aws-amplify/amplify-cli#1540]
These message keep happen every time when I try to `amplify push` after adding or updating `auth`.    
Version: @amplify/cli 1.6.11

**Comment by kaustavghosh06** [comment]
@phlinhng We found out the root-cause for this issue in #1513 
Closing this, since it's a duplicate of #1513
