### ISSUE TITLE
Model connection to self

### ISSUE THREAD

**Issue by macs91** [aws-amplify/amplify-cli#1541]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
API, Storage, Auth

** Provide additional details e.g. code snippets **

How can I model a recursive relationship?

I tried with this one:
```graphql
type Folder @model {
  id: ID!
  parent: Folder @connection(name: "Folders")
  folders: [Folder] @connection(name: "Folders")
}
```
But when I try to create a folder I get this error: 
`The table does not have the specified index: gsi ....`

**Comment by SwaySway** [comment]
Hi @macs91 I'm able to create a folder using the following mutation request.
```
mutation CreateFolder($input: CreateFolderInput!) {
  createFolder(input: $input) {
    id
  }
}
{"input":{"id":"09", "folderParentId":"04"}}
```
Could you provide the mutation request which gives this error?
