### ISSUE TITLE
Team Environment - New API and Storage Not Being Created

### ISSUE THREAD

**Issue by darnmark64** [aws-amplify/amplify-cli#1542]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify API and Storage

** What AWS Services are you utilizing? **
API Gateway and DynamoDB

** Provide additional details e.g. code snippets **
My team member added a new API and two storage items. He checked in his updated backend-config.json file to Git and I pulled it down in my local respository. I see his new items in this file and in the api and storage folders. When I do an 'amplify status' they don't show up so 'amplify push' doesn't create them in my environment.

Here's the backend-config.json file:
{
    "auth": {
        "RAZRCognito": {
            "service": "Cognito",
            "providerPlugin": "awscloudformation"
        }
    },
    "function": {
        "NcsLocationsLambda": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRGetTokenFunction",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "MySQLLambda": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "NcsNumbersApi": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRGetTokenFunction",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RAZRManageUsersAPIFunction": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "auth",
                    "resourceName": "RAZRCognito",
                    "attributes": [
                        "UserPoolId",
                        "UserPoolARN"
                    ]
                }
            ]
        },
        "RAZRCognitoPostAuth": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "RAZRManageGroupsFunction": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "auth",
                    "resourceName": "RAZRCognito",
                    "attributes": [
                        "UserPoolId",
                        "UserPoolARN"
                    ]
                }
            ]
        },
        "RazrAlertWebhookLambda": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "RazrAlertClientConnect": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "RazrAlertClientDisconnect": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "RazrAlertClientNewAlert": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": []
        },
        "RAZRNcsMessageAPI": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRGetTokenFunction",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RAZRGetTokenFunction": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "storage",
                    "resourceName": "RAZRDynamoDBToken",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RazrAlertHistoryLambda": {
            "service": "Lambda",
            "providerPlugin": "awscloudformation",
            "build": true,
            "dependsOn": [
                {
                    "category": "storage",
                    "resourceName": "RazrAlertHistory",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        }
    },
    "api": {
        "NcsLocationsApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "NcsLocationsLambda",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "MySQLAPI": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "MySQLLambda",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "NcsNumbersApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "NcsNumbersApi",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RAZRManageUsersAPI": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRManageUsersAPIFunction",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RAZRManageGroupsApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRManageGroupsFunction",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RazrAlertWebhookApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RazrAlertWebhookLambda",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RAZRNcsMessageApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RAZRNcsMessageAPI",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        },
        "RazrAlertHistoryApi": {
            "service": "API Gateway",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "RazrAlertHistoryLambda",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        }
    },
    "storage": {
        "RazrAlertClientConnections": {
            "service": "DynamoDB",
            "providerPlugin": "awscloudformation"
        },
        "RAZRDynamoDBToken": {
            "service": "DynamoDB",
            "providerPlugin": "awscloudformation"
        },
        "RazrAlertHistory": {
            "service": "DynamoDB",
            "providerPlugin": "awscloudformation"
        }
    }
}

Here's the output of 'amplify status':

Current Environment: digitsmark

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Auth     | RAZRCognito                | No Change | awscloudformation |
| Function | NcsLocationsLambda         | No Change | awscloudformation |
| Function | MySQLLambda                | No Change | awscloudformation |
| Function | NcsNumbersApi              | No Change | awscloudformation |
| Function | RAZRManageUsersAPIFunction | No Change | awscloudformation |
| Function | RAZRCognitoPostAuth        | No Change | awscloudformation |
| Function | RAZRManageGroupsFunction   | No Change | awscloudformation |
| Function | RazrAlertWebhookLambda     | No Change | awscloudformation |
| Function | RazrAlertClientConnect     | No Change | awscloudformation |
| Function | RazrAlertClientDisconnect  | No Change | awscloudformation |
| Function | RazrAlertClientNewAlert    | No Change | awscloudformation |
| Function | RAZRNcsMessageAPI          | No Change | awscloudformation |
| Function | RAZRGetTokenFunction       | No Change | awscloudformation |
| Api      | NcsLocationsApi            | No Change | awscloudformation |
| Api      | MySQLAPI                   | No Change | awscloudformation |
| Api      | NcsNumbersApi              | No Change | awscloudformation |
| Api      | RAZRManageUsersAPI         | No Change | awscloudformation |
| Api      | RAZRManageGroupsApi        | No Change | awscloudformation |
| Api      | RazrAlertWebhookApi        | No Change | awscloudformation |
| Api      | RAZRNcsMessageApi          | No Change | awscloudformation |
| Storage  | RAZRDynamoDBToken          | No Change | awscloudformation |

C:\Users\MarkDarnell\projects\RazrApp>amplify -v
1.6.11

Are we doing something wrong? How do I pick up his additions?

Thanks.

**Comment by kaustavghosh06** [comment]
After you do a git pull, you would also need to run the ‘amplify env pull’ command. You should be able to see the resources as a part of your amplify status command then.

**Comment by darnmark64** [comment]
Thank you that worked. I see in the documentation (https://aws-amplify.github.io/docs/cli/multienv?sdk=js) a mention of 'amplify env pull' in team members sharing the same backend but not in the sandbox environments, which is what we are using, so I missed it. We now know for the future. Thanks again.
