### ISSUE TITLE
Amplify console frontend build fails

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#1545]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
My apps build fails when building in Amplify Console while it works perfectly on my local box and in vanilla node docker containers. 
I think it's related to relative imports, for example, to import a file in React we can do: 
`import "./assets/styles/main.css";` or `import "assets/styles/main.css";` yet the latter doesn't work with the Amplify console Runner. 
Any asistance here would be much appreciated.

PD: Is there a way in which I could configure my own custom runner in Amplify Console?

**Comment by VividKnife** [comment]
Hi, can you email your app arn to aws-amplify-customer@amazon.com? The app arn can be found under app -> general. Also include your build Id as well.

**Comment by damianrr** [comment]
Just did @VividKnife. Thank you.

**Comment by kaustavghosh06** [comment]
@damianrr Could you please open up an issue on this AWS Amplify Forum - https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0 since this issue is not tied to the Amplify CLI? thanks!

**Comment by VividKnife** [comment]
Hi @damianrr, we didn't receive your email yet.

**Comment by damianrr** [comment]
Hello, @VividKnife, I did sent it yesterday, anyway, I re-send it seconds ago. Thanks!
