### ISSUE TITLE
Amplify console can't add multiple custom domains and can't find generated cloudfront distribution.

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#1547]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
I've configured a custom domain name for my amplify project, however, I need 2 domains pointing to this website (ex: xxx.xxx.ca and xxx.xxx.com) and I'm finding 2 difficulties:
1. I can't find anywhere the cloudfront distribution generated when I link (successfully) my first domain
2. doesn't allow me to add a second domain.

Could anyone help me here?
Thanks.

**Comment by kaustavghosh06** [comment]
@damianrr Could you please open up an issue on this AWS Amplify Forum - https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0 since this issue is not tied to the Amplify CLI? thanks!
