### ISSUE TITLE
Can I use multiple buckets?

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#1549]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **

storage

** What AWS Services are you utilizing? **

appsync / s3 / dynamodb

** Provide additional details e.g. code snippets **

amplify cli v1.6.8

Can I use multiple buckets?
I tried `amplify add storage` however I got following result.

```
Amazon S3 storage was already added to your project.
```

Are there any workaround to treat multiple S3 buckets?

**Comment by kaustavghosh06** [comment]
The Amplify Framework provides support for a single bucket for your projects. The recommended way by S3 is to add an additional sub-folder - https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html to segragate your data instead of adding additional buckets. Would be great to know more about your use-case though.

**Comment by bokuweb** [comment]
@kaustavghosh06 Thanks for your reply. 

> . The recommended way by S3 is to add an additional sub-folder

Unfortunately I would like to use a bucket as a write only and another one as a public(readable and writeble)...

I can write a cloudformation template by hand, but where can I add it?At the least, I want to make another bucket be created by `amplify push` or `amplify init`. Is it possible??

**Comment by kaustavghosh06** [comment]
@bokuweb You could modify the storage cloudformation file to add one more Cloudformation S3 resource located in `amplify/backend/storage/<s3-cfn-file>`

**Comment by bokuweb** [comment]
@kaustavghosh06 Thanks :) I'll try it.

**Comment by bokuweb** [comment]
@kaustavghosh06 I tried following two cases however `new storage` is not created.
Do you have any information??

```
amplify/backend/storage/parameters.json
amplify/backend/storage/s3-cloudformation-template.json
```

```
amplify/backend/storage/another-stoarge/parameters.json
amplify/backend/storage/another-stoarge/s3-cloudformation-template.json
```

**Comment by kaustavghosh06** [comment]
@bokuweb  I would recommend adding the storage resource to the exisiting `amplify/backend/storage/s3-cloudformation-template.json` file.

**Comment by bokuweb** [comment]
@kaustavghosh06 Sorry, I misunderstood. I'll try it. Thanks :)

**Comment by AlessandroAnnini** [comment]
@bokuweb, did it work?

**Comment by bokuweb** [comment]
@AlessandroAnnini Sorry, I have not tried it yet. And I would like to add another storage by `amplify add storage` command...

**Comment by diego-palmeira** [comment]
> @bokuweb You could modify the storage cloudformation file to add one more Cloudformation S3 resource located in `amplify/backend/storage/<s3-cfn-file>`

A question about that, if I add a new S3 bucket to this file, will be it overridden and lose changes next time I try an amplify push? or these extras remain in the file and be ignored by Amplify cli?

It is possible to modify the generated CF templates?

Honestly, we are working in a mid-project with 8 lambdas and 10 or 15 services, and we have to go outside Amplify all the time with manual configurations, caused by many services not supported by Amplify small subset of functionality. If it wishes to be an enterprise tool, it should improve a lot the support about AWS services, currently, it's far away to be a productive tool.

**Comment by sorokinvj** [comment]
> The Amplify Framework provides support for a single bucket for your projects. The recommended way by S3 is to add an additional sub-folder - https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html to segragate your data instead of adding additional buckets. Would be great to know more about your use-case though.

One of the use-cases in my speech recognition app - is to have separate folders/buckets for source audios and resulted transcriptions. However, AWS Transcribe service doesn't understand folders. When you start a transcriptions job having 
```
    OutputBucketName: 'bucketName/folder'
```
Transcribe Service results in error:
```
code: "BadRequestException"
message: "1 validation error detected: Value 'bucketName/folder' at 'outputBucketName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]"
```

So im my app I have two options: 
1. Store results in the same bucket as source audio, maybe moving source audio in separate folder (which I can do with Storage.put(key, file))
2. Have a separate bucket for transcriptions, but set the permissions manually which for my level of AWS understanding seems to hard.

**Comment by charleslouis** [comment]
Hi

@sorokinvj did you figure something out ?

If it helps you or someone else reading : 
In S3 folder are not really folders. The folder is in the file name (the Key).
So it would be something like `OutputBucketName: 'myS3BucketName'`
Filename / Object key : `public/myfile.mp3`, `private/myfile.mp3`, `myfolder/myfile.mp3`, `public/myfolder/myfile.mp3`

**Comment by charleslouis** [comment]
Also, I would really find interest in being able to do add several S3 using `amplify storage add`.

Consider this :
- An app using images and videos, with user front App and a backoffice/CMS, Auth with cognito 
- upload video in one s3 then convert them using Mediaconvert and store them in another S3
- upload images in one s3 then convert them using Lambda and store them in another S3
- some images/videos could be accessed by anyone (landing page), some other only to authenticated users

At least for Mediaconvert (Transcribe too I guess) I think it’s better to have 2 buckets.
This mainly to avoid endless loop using event triggers ''All object create events" or "PUT" to trigger an event that will launch Mediaconvert.

Another (very hypothetical) solution is to enable Events triggers such as ''All object create events" on S3 to be set multiple times. Something like:
`ON ''All object create events" IN public/videos/in DO Trigger videoConvert`
`ON''All object create events" IN public/images/in DO Trigger imageConvert`

![image](https://user-images.githubusercontent.com/2117081/86505900-bc68fb80-bdd2-11ea-9cb2-289b0ea1649b.png)

**Comment by sorokinvj** [comment]
> Filename / Object key : `public/myfile.mp3`, `private/myfile.mp3`, `myfolder/myfile.mp3`, `public/myfolder/myfile.mp3`
@charleslouis That's the problem! AWS Transcribe just does not allow me to have '/' in the filename, so no "folders"!

**Comment by LucasAndrad** [comment]
This doesn't make much sense @kaustavghosh06 then why amplify allow us to have s3 trigger function if we can only have one bucket? They docs say we should use two buckets to prevent the function to get in a loop:
[Link here](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html)

**Comment by charleslouis** [comment]
@sorokinvj this is frustrating 😣 
Do you have a trigger and lambda between Transcribe and S3 ?
If so, can you hack your way by naming your files `public_myfolder_myfile.mp3` and string replace `_` by `/` (I know that's heavy but maybe it could work) ?

**Comment by sorokinvj** [comment]
> @sorokinvj this is frustrating 😣
> Do you have a trigger and lambda between Transcribe and S3 ?
I do yeah, when transcribe is finished,  cloudwatch receives an event and it trigger Lambda which make a Graphql mutations and my UI is notified by subscription. 

From my experience Amplify is great when you could find all the aws services as part of Amplify, but when you must reach services outside of the Amplify "eco-system" then you always need some hacky solutions which is sad, yeah

**Comment by Nagasai97** [comment]
Yes we can use multiple buckets using amplify

[this will help you for sure](https://medium.com/dnx-labs/using-multiple-buckets-aws-amplify-66083d7a4301)

![image](https://user-images.githubusercontent.com/75477919/101153096-f6704f00-3649-11eb-8168-3e9531b785cd.png)

**Comment by stleon** [comment]
I need support of multiple storages in my app too.

**Comment by Nagasai97** [comment]
> I need support of multiple storages in my app too.

yes you can do it using amplify

**Comment by AzherAleem** [comment]
> Yes we can use multiple buckets using amplify
> 
> [this will help you for sure](https://medium.com/dnx-labs/using-multiple-buckets-aws-amplify-66083d7a4301)
> 
> ![image](https://user-images.githubusercontent.com/75477919/101153096-f6704f00-3649-11eb-8168-3e9531b785cd.png)

@Nagasai97  How will you specify the environment name along with the bucket name since we can have the same bucket for different environments like 'storage-bucket-dev' and 'storage-bucket-staging'. How will you get the environment name at the front end?

**Comment by Nagasai97** [comment]
@AzherAleem I think you need to have multiple config files,differentiating with both environments and from their u need to use the bucket name....(I'm not sure)
Thankyou
