### ISSUE TITLE
Possible to use with AWS SAM?

### ISSUE THREAD

**Issue by 0xdevalias** [aws-amplify/amplify-cli#155]
**Which Category is your question related to?**

AWS SAM

**Provide additional details e.g. code snippets**

Is it possible to use AWS [SAM](https://github.com/awslabs/serverless-application-model) / [SAM CLI](https://github.com/awslabs/aws-sam-cli) together with Amplify?

**Comment by noelyoo** [comment]
Maybe this will be a help:
https://github.com/awslabs/serverless-application-model/issues/671#issuecomment-441301737

**Comment by kaustavghosh06** [comment]
@0xdevalias Yes, you can create a function using the `amplify add function` command and replace the Cloudformation tempalte with a SAM template. We do support it now.

**Comment by dtelaroli** [comment]
@kaustavghosh06 is there some documentation how to integrate SAM and Amplify?

I'm trying use SAM with Amplify and the amplify is ignoring one of my function:

`Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [PostbackFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.`

If I rename the LambdaFunction to MyLambdaFunction I get this error:

`TypeError: Cannot read property 'Type' of undefined
                                 at buildResource.then.then.s3Bucket (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:252:46)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by zjullion** [comment]
I'm also getting errors trying to convert a template:
```
Cannot set property 'S3Bucket' of null
An error occurred during the push operation: Cannot set property 'S3Bucket' of null
```
I've run `sam validate` on the template and got no errors.
@ammarkarachi or @attilah any ideas? Is this still supposed to work?

**Comment by zjullion** [comment]
Ok, I've narrowed down the problem: using `AutoPublishAlias` in the `Properties` of an `AWS::Serverless::Function` causes this issue. Very strange.
