### ISSUE TITLE
--invalidateCloudFront not working

### ISSUE THREAD

**Issue by dmitrybndar** [aws-amplify/amplify-cli#1550]
**Describe the bug**
I have a same amplify project on two computers - PC (win 10) and MacBook. Everything worked well on both, until I re-install windows on my PC, from that moment "--invalidateCloudFront" or "-c" flag dont dont work as expected on PC (on Mac still works well). I see message "CloudFront invalidation request sent successfuly." in console, but when I go to AWS CloudFront service and open "Invalidations" tab (in my distribution) there is no new invalidation, and CloudFront url of my project has cached files (old) until I create invalidation manually in "Invalidations" tab.

**To Reproduce**
I don't now how to reproduce it, cause its work well on macbook, and on my previous windows setup.

**Expected behavior**
"amplify publsh --invalidateCloudFront" command from my PC (win 10) creates new invalidation in cloud front 

**Screenshots**
![image](https://user-images.githubusercontent.com/26284696/58626440-8313b180-82dd-11e9-993c-10deb7b3199d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Thats probably not the issue with CLI, mb I do something wrong, but I tried a lot of things already such as re-install amplify-cli (different versions), cloning project from git in another folder and run "ampify configure", "ampify init" in it, making new aws profiles... but all unsuccessfully. Hope you can help me. Thanks!

**Comment by UnleashedMind** [comment]
Hi @dmitrybndar 
If you see the "CloudFront invalidation request sent successfully." message, that means the invalidation request has been sent to CloudFront. There might be some delay till it shows up in the CloudFront's web console. The update of the actual contents in the CloudFront edges will take even more time. 
We are not ruling out that this is a possible bug at this moment, though. What is the version of the installed Amplify CLI on your Windows 10 machine? so we can investigate further.

**Comment by dmitrybndar** [comment]
Hi @UnleashedMind 
Thanks for helping in this. Invalidation didnt show in web console even after a couple of days. But again - when I do the same from macbook (and did on previuos setup of win10) - invalidation appears in web console almost instantly after I see "CloudFront invalidation request sent successfully." in my terminal.
I tried different versions of Amplify CLI - 1.5.3; 1.6.3; 1.6.5 (thats is what I have on mac also); 1.6.11. But I have this problem with all of them. Thanks, again

**Comment by UnleashedMind** [comment]
Thanks @dmitrybndar 
I think I've found the bug. 
will send a fix soon

**Comment by dmitrybndar** [comment]
@UnleashedMind 
I've added you fix in package manually, and it works! Thanks a lot for resolving it so fast! )
