### ISSUE TITLE
Update existing lambda functions to inject identifiers from api or auth throws TypeError

### ISSUE THREAD

**Issue by foxfl** [aws-amplify/amplify-cli#1552]
**Describe the bug**
Updating to the latest version and based on [this comment](https://github.com/aws-amplify/amplify-cli/issues/1099#issuecomment-497212996) on #1099  you should be able to inject identifiers from auth or api category into functions. Updating a existing function to add the AWS AppSync Api ID results in a typeError. 

`Policies cannot be added for api TypeError: Cannot read property 'api' of undefined`

**To Reproduce**
See Screenshot. 

**Expected behavior**
Updating the function results in the AWS AppSync Api ID available as parameter in the cloudformation template. 

**Screenshots**
![AWS-CLI-Error](https://user-images.githubusercontent.com/22390669/58655718-0d2e3b00-831b-11e9-89c1-acaa76c15532.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.7.0

**Additional context**
I already setup the policies for the function with a hardcoded Api ID from appsync, maybe this is conflicting with the update process from the cli, but the error seems more like a reference was not found.

**Comment by kaustavghosh06** [comment]
@foxfl What does your `amplify/backend/function/functions-params.json` file show? 
Also, can you run the `amplify update function` command the second time around and see it you get the same error?

**Comment by foxfl** [comment]
@kaustavghosh06 Thanks for the fast reply. 
I tried to rerun to command yesterday which resulted in the same output.
Today i also tried to rerun the command which then didnt throw an error and outputed this:
`{
    "permissions": {
        "api": {
            "test_api": [
                "create",
                "read",
                "update",
                "delete"
            ]
        }
    }
} `
in the functions-params.json 

I also tried the same process on a different function in my project. First try results in the error. Second try updates the functions-params.json  succesfully as shown in the screenshot.

![AWS-CLI-Error_rerun](https://user-images.githubusercontent.com/22390669/58701913-99387500-83a4-11e9-9deb-4a6fd64da8fb.PNG)

**Comment by davidbiller** [comment]
jap, the second try is working. BUT:

UPDATE_FAILED               functioncalculateZscoreVariables   AWS::CloudFormation::Stack Mon Jun 03 2019 11:35:28 GMT+0200 (Mitteleuropäische Sommerzeit) Template format error: Parameter name API_AIVY_GRAPHQLAPIIDOUTPUT is non alphanumeric.


than i get this.

**Comment by foxfl** [comment]
@davidbiller 
You have to replace `API_AIVY_GRAPHQLAPIIDOUTPUT ` with  `api{your_api_name}GraphQLAPIIdOutput` (take a look at the default value) in your cloudformation templates for the function in the parameters section, that did the trick for me.

**Comment by davidbiller** [comment]
> @davidbiller
> You have to replace `API_AIVY_GRAPHQLAPIIDOUTPUT ` with `api{your_api_name}GraphQLAPIIdOutput` (take a look at the default value) in your cloudformation templates for the function in the parameters section, that did the trick for me.

in which file?

**Comment by foxfl** [comment]
> > @davidbiller
> > You have to replace `API_AIVY_GRAPHQLAPIIDOUTPUT ` with `api{your_api_name}GraphQLAPIIdOutput` (take a look at the default value) in your cloudformation templates for the function in the parameters section, that did the trick for me.
> 
> in which file?

In /amplify/backend/function/{your_function}/{your_function}-cloudformation-template.json

**Comment by davidbiller** [comment]
> > > @davidbiller
> > > You have to replace `API_AIVY_GRAPHQLAPIIDOUTPUT ` with `api{your_api_name}GraphQLAPIIdOutput` (take a look at the default value) in your cloudformation templates for the function in the parameters section, that did the trick for me.
> > 
> > 
> > in which file?
> 
> In /amplify/backend/function/{your_function}/{your_function}-cloudformation-template.json

Thx. I will try. 
Maybe a stupid question, but with the new permissions, what can i do with this? So i need this for the table names. BUT can i use graphQL(appsync) than in Lambda to get data? so for now i do this direct over dynamodb.

**Comment by foxfl** [comment]
> > > > @davidbiller
> > > > You have to replace `API_AIVY_GRAPHQLAPIIDOUTPUT ` with `api{your_api_name}GraphQLAPIIdOutput` (take a look at the default value) in your cloudformation templates for the function in the parameters section, that did the trick for me.
> > > 
> > > 
> > > in which file?
> > 
> > 
> > In /amplify/backend/function/{your_function}/{your_function}-cloudformation-template.json
> 
> Thx. I will try.
> Maybe a stupid question, but with the new permissions, what can i do with this? So i need this for the table names. BUT can i use graphQL(appsync) than in Lambda to get data? so for now i do this direct over dynamodb.

Yep, you should be able to access AppSync directly from the lambda function, as the update process has added a policy for the function to access AppSync and injects the App Id from AppSync (@kaustavghosh06 Correct me if I’m wrong here). The thing is, that from now on you don’t have to hardecord the App Id into the template. Also, the App Id gets injected into the lambda as an environment variable. You can still directly access DynamoDB, as your lambda acts as a resolver for a GraphQL field but for example, you can now trigger mutations from your lambda when you add access to the API, as a result from a streaming event or such.

**Comment by kaustavghosh06** [comment]
@foxfl You're right. Also, we fixed the issue in with the latest version of our CLI - 1.7.1.
cc: @davidbiller
