### ISSUE TITLE
"Expected JSON object for '$[filter]' but got a 'STRING' instead." when querying a custom index

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1554]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
I'm using the new @key directive for making custom indexes. When I try the following:
```
query ItemsByStatus{
  itemsByStatus(currentState:"inProgress", createdAt:{gt:"2019-01-01"}) {
    items {
      id
    }
  }
}
```
it works fine but when I add a filter like so:

```
query ItemsByStatus{
  itemsByStatus(currentState:"inProgress", createdAt:{gt:"2019-01-01"},filter:{isLatest:{ne:false}}) {
    items {
      id
    }
  }
}
```
it produces the `Expected JSON object for '$[filter]' but got a 'STRING' instead.` error.

For reference this is what my @key looks like:
`@key(
    name: "ItemssByStatus"
    fields: ["currentState", "createdAt"]
    queryField: "itemsByStatus"
  )`

copy pasted from the docs basically

**To Reproduce**
1. put in a @key directive in your model
2. query using the custom index
3. add a filter

**Expected behavior**
It should filter the query results based on given filter and not produce error

**Screenshots**
![image](https://user-images.githubusercontent.com/48229482/58676040-7056b680-8389-11e9-9d26-321639c55477.png)

**Additional context**
I should mention that this was on an existing amplify project. I just upgraded the CLI then slapped the @key directive on an existing model and was glad it worked when I pushed. It's just this filter thing somehow not converting to JSON object that's the problem.

**Comment by mikeparisstuff** [comment]
@nino-moreton Thanks for raising the issue. Fixed in https://github.com/aws-amplify/amplify-cli/pull/1580.
