### ISSUE TITLE
Add AppSync trust policy to generated IAM roles if API category exists in Amplify app

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1557]
I have not verified this is still a problem in the latest version of the CLI.

We were having a problem querying for relationships against a base User model with AppSync. After further investigation, the Amplify-generated authenticated role contained the following trust policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
      }
    }
  ]
}
```

I believe that AppSync requires a trust policy,  per AppSync documentation:

>AWS AppSync communicates with data sources using Identity and Access Management (IAM) roles and access policies. If you are using an existing role, a Trust Policy needs to be added in order for AWS AppSync to assume the role. (https://docs.aws.amazon.com/appsync/latest/devguide/security.html)

Once I updated the CLI-generated policy to this, relationships started working:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "appsync.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Is your feature request related to a problem? Please describe.**
Please consider adding this Trust Policy to the CLI generated trust policy for the role, if the API category is configured for that application.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu AppSync creates its own role as a part of the transformer and associates this policy to it. Why would we need to add this policy to our Auth role?

**Comment by jkeys-ecg-nmsu** [comment]
I was confused as to which policy AppSync was using. So why did we go from getting empty items lists to getting items back from Dynamo without any other changes? A mystery for another time I suppose. Thanks.
