### ISSUE TITLE
Add Golang/other lambda backend language support

### ISSUE THREAD

**Issue by 0xdevalias** [aws-amplify/amplify-cli#156]
Is your feature request related to a problem? Please describe.
I would like to be able to automagically deploy non-javascript based lambda functions (eg. golang)

Describe the solution you'd like
Add support for using any supported lambda languages, particularly Golang

Describe alternatives you've considered

Manually adding the required CloudFormation/etc to my repo.
Using pre-deployed lambda's (from AWS SAM or similar)
Additional context
N/A

**Comment by danielbayerlein** [comment]
Is there any recommendation on how best to deal with this issue at the moment?

**Comment by davidsteed** [comment]
Generally it would be really helpful to have some integration between sam and amplify. Sam supports different Lambda runtimes, whereas Amplify only supports Node.  If there was a way an Amplify api could be created that leveraged SAM scripts it would really help

**Comment by J-L** [comment]
Yeah,  this is a big deal for me too!

**Comment by stefangomez** [comment]
I commented on another ticket about implementing a python lambda. I'm something similar can be done for golang. Luckily after initial setup, there's no more work to do. just add code: https://github.com/aws-amplify/amplify-cli/issues/1505

**Comment by camstuart** [comment]
+1 for go lambda.

**Comment by bmilesp** [comment]
Also +1 for go lambda, go lambda local dev would be killer also!

**Comment by chris** [comment]
+1 as this is preventing me from using Amplify :( . (for lambda functions anyway)

**Comment by yhc44** [comment]
Im working on a golang integration for this package, so we can test golang lambdas locally soon.

Currently it is only working with serverless aws appsync.

So far im testing my AWS appsync graphql API with golang lambdas as datasource locally.

If you are interested do not hesitate to contact me :)

I will make a pull request very soon.

**Comment by bmilesp** [comment]
@yhc44 that's great news! I'd be glad to test out your integration!

-bp

**Comment by ppattewa** [comment]
Any updates on this ticket?

**Comment by kaustavghosh06** [comment]
We're actively working on getting Python, Java, Go, .NET support for Lambda runtimes support out soon.

**Comment by mrrainey** [comment]
@kaustavghosh06 Great news, I hate to have to ask this, but do you have an approximate time for this release? I'm working on my university final year project at the minute and would like to use python lambda functions with amplify, I cannot afford to if they are not released in the next 2-3 weeks. If I had an idea I could plan accordingly. Thanks.

**Comment by SolveForTech** [comment]
Great to hear support for more languages is coming! Does anyone happen to have a link to a guide on how to work around that for the time being? I'm attempting to integrate in python lambda functions.

**Comment by jrheling** [comment]
> Great to hear support for more languages is coming! Does anyone happen to have a link to a guide on how to work around that for the time being? I'm attempting to integrate in python lambda functions.

I found this bug when looking to work through that same situation, @SolveForTech. In the end I used Serverless Framework and the `aws-amplify-serverless-framework` plugin to connect the AWS config details between Serverless and the Amplify library on the client side.

I wrote up how I did it at https://medium.com/@jrheling/using-serverless-framework-with-the-amplify-client-library-9f3a1e2ee24f, in case that's of help to you.

**Comment by SolveForTech** [comment]
Thank you Josh!!!

**Comment by jnathanh** [comment]
genius workaround @stefangomez, thanks. I followed the same pattern for a golang lambda and it worked without a hitch. The only additional step I added was a `"preinstall": "go clean"` in the package.json.

**Comment by kaustavghosh06** [comment]
Hey guys, yesterday with Amplify CLI v4.18.0 we officially support Go, Java, Python and .NET runtimes along with local testing for these functions. Docs for the feature - https://docs.amplify.aws/cli/function#supported-lambda-runtimes

**Comment by bmilesp** [comment]
Yeeeess!! Thank you @kaustavghosh06 !

**Comment by flochaz** [comment]
In case of python function, it does not seems to build through Amplify due to the lack of python 3.8 on the Amazon Linux:2 image (only 3.7 is on it) ... will have to install it in prebuild phase or custom image ...
