### ISSUE TITLE
3 bugs of the new @key directives  

### ISSUE THREAD

**Issue by rarira** [aws-amplify/amplify-cli#1562]
**Describe the bug**
new @key directive is great but its autogenerated resolvers have at least 3 problems or something uncomfortable..
1. you have to input manually id(primary key) and sort key when create(putItem) a item
2. the autogenerated resolver with getItem operation of other type which has the connection to it should have both primary key and sort key to fulfill but it only has primary key
3. when creating named @key directive, I can't use already existed gsi which had been auto-generated by @connection directive

**To Reproduce**
I have both 'Class' and 'ClassTag' Type:
```
type Class
  @model
  @auth(rules: [{ allow: owner, ownerField: "classHostId" }])
  @key(fields: ["id", "dateStart"])
  @searchable {
  id: ID!
  title: String!
  center: Center! @connection(name: "ClassCenter")
  tags: [ClassTag] @connection(name: "ClassTag")
}

type ClassTag @model(mutations: null) {
  id: ID!
  class: Class! @connection(name: "ClassTag")
  tag: Tag! @connection(name: "TagClass")
}
```

### bug1. the autogenerated mutation resolver : I can't utilize $util.autoId() so I have to input id manually using uuidv4() everyime
....
```
## [Start] Set the primary @key. **
#set( $modelObjectKey = {
  "id": $util.dynamodb.toDynamoDB($ctx.args.input.id),
  "dateStart": $util.dynamodb.toDynamoDB($ctx.args.input.dateStart)
} )
## [End] Set the primary @key. **

## [Start] Prepare DynamoDB PutItem Request. **
$util.qr($context.args.input.put("createdAt", $util.defaultIfNull($ctx.args.input.createdAt, $util.time.nowISO8601())))
$util.qr($context.args.input.put("updatedAt", $util.defaultIfNull($ctx.args.input.updatedAt, $util.time.nowISO8601())))
$util.qr($context.args.input.put("__typename", "Class"))
{
  "version": "2017-02-28",
  "operation": "PutItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
  "id":   $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.args.input.id, $util.autoId()))
} #end,
  "attributeValues": $util.dynamodb.toMapValuesJson($context.args.input),
  "condition": {
      "expression": "attribute_not_exists(#id)",
      "expressionNames": {
          "#id": "id"
    }
  }
}
## [End] Prepare DynamoDB PutItem Request. **
```

### bug2. the autogenerated ClassTag.class.req.vtl : there should be "dateStart" key but only "id"

```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.classTagClassId, "___xamznone____"))
  }
}
```

## bug3. when I tried to add new @key directive
`  @key(name: "gsi-ClassCenter", fields: ["classCenterId", "dateStart"], queryField: "listClassByCenter")`
to 'Class' type and 'amplify push api'.. 
UPDATE_FAILED      ClassTable                     AWS::DynamoDB::Table   Sat Jun 01 2019 20:57:47 GMT+0900 (Korean Standard Time) Cannot update GSI's properties other than Provisioned Throughput. You can create a new GSI with a different name
so I have to use custom resolver and custom resources as before.

But in other type(which existed for many-to-many relation), i can successfully use named @key directive

```
type MyCenter
  @model
  @auth(rules: [{ allow: owner, ownerField: "myCenterUserId" }])
  @key(fields: ["id", "createdAt"])
  @key(name: "gsi-UserCenter", fields: ["myCenterUserId", "createdAt"], queryField: "listMyCentersByUser") {
  id: ID!
  center: Center! @connection(name: "CenterUser")
  user: User! @connection(name: "UserCenter")
  createdAt: AWSDateTime!
  myCenterUserId: String!
  myCenterCenterId: String!
}```

**Comment by mikeparisstuff** [comment]
@rarira Thanks for the post.

> bug1. the autogenerated mutation resolver : I can't utilize $util.autoId() so I have to input id manually using uuidv4() everyime

The intention of @key was to allow custom index structures so the `uuid()` functionality was not included. It would be possible to still use `uuid()` as the default in the case when you are trying to index on a field named "id".

> bug2. the autogenerated ClassTag.class.req.vtl : there should be "dateStart" key but only "id"

`@connection` has not yet been updated to leverage `@key`. We are aware of this and it is in the backlog to do so.

> bug3. when I tried to add new @key directive

This is related to having not updated @connection to work with @key yet. The issue is that the GSI created by the @connection does not have a sort field in its current form. If you changed the @key to `@key(name: "gsi-UserCenter", fields: ["myCenterUserId"], queryField: "listMyCentersByUser")` so that it matched the @connection it may work. The direction moving forward will be to enable @connection to use @key's so that @connection is no longer creating GSIs.

**Comment by undefobj** [comment]
@rarira I believe these have been addressed since the original issue was opened but please let us know if you're still having trouble.
