### ISSUE TITLE
Many-to-many queries - getting the data

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#1563]
I am using AWS Amplify with Ionic/Angular with graphQL as my backend.

I have a user record which has a favorites field, which is a many to many relationship with an Events. I have created a join table as specified by the AWS docs and community. 

```graphql
type FavoritedEvent @model(queries: null) {
  id: ID!
  event: Event! @connection(name: "favoriteEvents")
  user: User! @connection(name: "UserFavorite")
}
```

and my user model:

```graphql
type User @model {
  id: ID!
  role: UserRole
  firstName: String!
  lastName: String!
  email: String!
  location: String
  occupation: String
  websiteUrl: String
  stripeCustomerId: String
  activeMembership: Boolean
  membership: String
  social: [Social] @connection(name: "UserSocials")
  allowNotifications: Boolean
  allowLocation: Boolean
  profilePicture: String
  events: [UserEvent] @connection(name: "UserEvents")
  reviews: [Review] @connection(name: "UserReviews")
  favorites: [FavoritedEvent] @connection(name: "UserFavorite")
  categories: [String]
}
```

Now, Amplify auto generates an api service in my angular project, long with a graphql folder containing all the queries, mutations etc as .graphql files.

When I fetch a user, I want to be able to see all the events under their favorites but currently it only returns the id of the event.

I have tried adding the return fields to the .graphql queries file, and also in the service itself, but it does not have any effect.

How can I customise the generated Angular service to make it return nested field values from many to many connections?

**Comment by yuth** [comment]
@oliverandersencox Codegen by default limits depth of generated statement to 2. You could change the depth by running `amplify codegen configure` and increase the max depth. The other way to handle this is to write a custom query, and save it with a different  name in, `src/graphql` folder and codegen will include the queries from this new file
