### ISSUE TITLE
Functions accessing other resources?

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1564]
** Which Category is your question related to? **
Amplify functions

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
In Amplify 1.7, we're asked this question when adding a function:
![image](https://user-images.githubusercontent.com/24530625/58768711-2837bf80-8554-11e9-8fb3-310ec41c276b.png)

Is there any documentation on how to take advantage of the that?
The only difference I notice when I select access to other resources, is some additional roles for the lambda and process.env making some values available.

**Comment by kaustavghosh06** [comment]
@rawadrifai In addition to adding policies to the lambda execution role, you can also access amplify managed resources like your AppSync API through your lambda function through environment variables. For more details around this support, checkout - https://aws.amazon.com/blogs/mobile/amplify-framework-adds-support-for-aws-lambda-functions-and-amazon-dynamodb-custom-indexes-in-graphql-schemas/
