### ISSUE TITLE
Amplify Storage Permissions Prompt UX

### ISSUE THREAD

**Issue by smp** [aws-amplify/amplify-cli#1568]
**Describe the bug**
The _Storage_  component [documentation](https://aws-amplify.github.io/docs/js/storage) states the following under "Using S3"

>  If you set up your Cognito resources manually, the roles will need to be given permission to access the S3 bucket.

This implies the roles will be automatically configured if a user ***did not*** configure Cognito Identity Pool manually. However, even with auth added via Amplify _Auth_ component, I still had to add the inline policy document to the unathorized role in order to access *any* object in the storage bucket.

**To Reproduce**
1. Run amplify init 
2. Use Amplify CLI 1.7.0 to create _Storage_ component including auth and unath access for s3 with read access on both
3. Examine the inline policy document for the auth and unathroles associated to the newly created identity pool. The roles state "this role does not have any permissions yet"
4. Attempt to Storage.get on any object and you will receive 403
5. Manually add inline policy as stated in the documentation
6. Storage.get will succed

**Expected behavior**
Storage component should automatically add these inline policies if they are managed via Amplify-CLI. Alternatively the documentation could be updated to state that the policies

**Comment by smp** [comment]
@kaustavghosh06 I figured it out..PEBKAC 

In the prompt for permissions if I hover over 'read' or any other permission and press enter without first hitting space (to select radio button) the CLI continues on and doesn't add permissions. 

I wonder if we could supply a default or prompt the user when they haven't specified any permissions. Something like "Are you sure you don't want to specify any storage access permissions? If you don't add them here, you'll need to manually add them via IAM"

**Comment by kaustavghosh06** [comment]
@smp This issue is resolved in the latest version of the CLI - v 4.16.1 with storage. Let me know if you're still seeing this anywhere else.
