### ISSUE TITLE
@auth transform not correct

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#157]
**Describe the bug**

Using "amplify add api":

```
$ amplify add api
? Please select from one of the below mentioned services GraphQL
? Provide API name: notes
? Choose an authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? true
? What best describes your project: 
? What best describes your project: Objects with fine-grained access control (e.g., a proj
ect management app with owner-based authorization)
? Do you want to edit the schema now? (Y/n) 
? Do you want to edit the schema now? Yes
? Press enter to continue 
```

Using the following schema:

```
type Note 
    @model 
    @auth(rules: [{
		allow: owner, 
		ownerField: "userId", 
		identityField: "sub", 
		mutations: [create, update, delete],
		queries: [get, list]		
	}]) {
   id: ID!
   note: String!
}
```

This is the output of amplify/backend/api/notes/build/resolvers/Query.getNote.request

```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
  }
}
```

The bug is there is no code in the resolver to check for owner as allow owner only.

**Desktop (please complete the following information):**
macOS

$ amplify --version
0.1.19

**Comment by mikeparisstuff** [comment]
The authorization check for the getItem resolver happens in the response mapping template. Please look at Query.getNote.response.

**Comment by jaxondu** [comment]
@mikeparisstuff can't we use Query with FilterExpression instead of GetItem? DynamoDB tutorials I read normally is using the Query method, letting the database doing the guard rather than when data is retrieved out. Kind of waste of bandwidth by pulling the data out to do checking.

**Comment by kaustavghosh06** [comment]
@jaxondu  Are you still blocked?

**Comment by jaxondu** [comment]
@kaustavghosh06 blocked? The latest version CLI seems to work fine with my simple testing. The question I posted above is nick picking on the way the code is structured. Does not seem like a best practice the way you retrieve all data out and do the checking. You can close this case if it is acceptable to you.

**Comment by mikeparisstuff** [comment]
This is a good point. We can change the transform to always use Query operations instead of GetItem even when getting an item with a unique key as a slight optimization assuming this does not impact the latency of the call in DynamoDB. This isn't a bug and sounds like a lower priority issue but it has been added to the backlog.
