### ISSUE TITLE
amplify update function fails initially, then succeeds, but subsequent push fails.

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#1574]
Hello!

**Describe the bug**
Running "amplify update function" produces unexpected results.

I have a function "CreateUser" created with "amplify function". Previously I've manually configured the cloudformation template to add some env vars to pass the user pool information. Now that amplify supports this natively I thought to update. When I run the update function routine, and choose auth, it fails with an error: 

PS C:\Users\Ryan\workspace\voiced\front-office\dashboard\dashboard-api> amplify update function
Using service: Lambda, provided by: awscloudformation
? Please select the Lambda Function you would want to update CreateUser
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category auth
Auth category has a resource called FrontOfficeAuth
Policies cannot be added for auth
TypeError: Cannot read property 'auth' of undefined
    at Object.default (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\provider-utils\awscloudformation\service-walkthroughs\lambda-walkthrough.js:316:75)
    at C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\run-async\index.js:24:19
    at Object.exports.fetchAsyncQuestionProperty (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\inquirer\lib\utils\utils.js:21:29)
    at MergeMapSubscriber.obs.pipe.concatMap [as project] (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\inquirer\lib\ui\prompt.js:73:17)
    at MergeMapSubscriber._tryNext (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION

===

if I run this a second time it goes through the remaining steps. The first time it halts on line 316 of the lambda-walkthrough.js file. Specifically this line:
if (currentDefaults && currentDefaults.categoryPermissionMap[category]
                && currentDefaults.categoryPermissionMap[category][resourceName])

Changing that to this line, fixes the initial error but there is a subsequent problem:
if (currentDefaults  && currentDefaults.categoryPermissionMap && currentDefaults.categoryPermissionMap[category]
                && currentDefaults.categoryPermissionMap[category][resourceName])

After the auth update runs through I cannot push my code using "amplify push", I get another error:
UPDATE_IN_PROGRESS          functionCreateUser          AWS::CloudFormation::Stack Tue Jun 04 2019 12:58:25 GMT-0400 (Eastern Daylight Time)
UPDATE_IN_PROGRESS          apiFrontOfficeDashboardAPI  AWS::CloudFormation::Stack Tue Jun 04 2019 12:58:25 GMT-0400 (Eastern Daylight Time)
UPDATE_FAILED               functionCreateUser          AWS::CloudFormation::Stack Tue Jun 04 2019 12:58:26 GMT-0400 (Eastern Daylight Time) Template format error: Parameter name AUTH_FRONTOFFICEAUTH_USERPOOLID is non alphanumeric.
UPDATE_FAILED               apiFrontOfficeDashboardAPI  AWS::CloudFormation::Stack Tue Jun 04 2019 12:58:27 GMT-0400 (Eastern Daylight Time) Resource update cancelled
UPDATE_ROLLBACK_IN_PROGRESS dashboardapi-20190124155637 AWS::CloudFormation::Stack Tue Jun 04 2019 12:58:28 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to update: [apiFrontOfficeDashboardAPI, functionCreateUser].
\ Updating resources in the cloud. This may take a few minutes...

**To Reproduce**
Not sure, there may be something in my environment. I don't recall which version of amplify cli these functions were created with.

**Expected behavior**
The function to update and push successfully through cloudformation.

**Desktop (please complete the following information):**
Windows 10 (latest)
Powershell
Amplify CLI 1.7.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
It does seem to overwrite the cloudformation template the first time, albeit minus the auth info. The second time (or with the "fixed" code I provided) it overwrites with all the auth stuff. FWIW: As expected, all of my custom templating is gone in either case after the update is run.

This is not urgent for me, I've been able to restore the environment from the server for now and my code works fine. I'm just working on refactoring customizations as new features are made available to replace them so I have fewer exceptions to track. Thank you!

**Comment by kaustavghosh06** [comment]
@ryanhollander Could you please specify the function parameters from your cloudformation file?

**Comment by ryanhollander** [comment]
@kaustavghosh06 I'm not 100% on which you are asking for so...

These is the parameters section of the ...cloudformation-template.json file:

"Parameters": {
		"env": {
			"Type": "String"
		},
		"AUTH_FRONTOFFICEAUTH_USERPOOLID": {
			"Type": "String",
			"Default": "AUTH_FRONTOFFICEAUTH_USERPOOLID"
		}
	},

these is contents of function-parameters.json from the function:

{
    "permissions": {
        "auth": {
            "FrontOfficeAuth": [
                "create",
                "read",
                "update"
            ]
        }
    }
}

Please let me know if you need anything else. Thanks!

**Comment by jmsaucier** [comment]
This is happening for me as well on 1.7.0 when trying to update a function to add a second storage resource to it. 

If I need to create a separate issue for this let me know, but I'm thinking it's the same issue even though it's a different service.

> Using service: Lambda, provided by: awscloudformation
> ? Please select the Lambda Function you would want to update restapilambda
> ? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
> ? Select the category storage
> ? Storage has 5 resources in this project. Select the one you would like your Lambda to access transformations
> Policies cannot be added for storage
> TypeError: Cannot read property 'storage' of undefined
>     at Object.default (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:316:75)
>     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/run-async/index.js:25:25
>     at new Promise (<anonymous>)
>     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/run-async/index.js:24:19
>     at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/inquirer/lib/utils/utils.js:21:29)
>     at MergeMapSubscriber.obs.pipe.concatMap [as project] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/inquirer/lib/ui/prompt.js:73:17)
>     at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
>     at MergeMapSubscriber._next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
>     at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at MergeMapSubscriber.notifyNext (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
> 
> You can access the following resource attributes as environment variables from your Lambda function
> var environment = process.env.ENV
> var region = process.env.REGION
> 
> ? Do you want to edit the local lambda function now? (Y/n) n
> ? Do you want to edit the local lambda function now? No
> Successfully updated resource

When this happens, my function-parameters.json is changed from "{}" to "{"permissions": {}}". My lambda's cloudformation template loses the existing dynamodb Name and Arn, the backend-config.json's function entry loses the dependency on the old storage resource, and the one i try to update to is not added.
