### ISSUE TITLE
Can I point groupsField in @auth to a non-Cognito source?

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1575]
** Which Category is your question related to? **
Access control through Cognito? or not?

** What AWS Services are you utilizing? **
Amplify, GraphQL, DynamoDB, Cognito

** Provide additional details e.g. code snippets **
I cannot seem to get a good design for a very simple requirement. My users should be able to create groups. When others join groups they can see what that group is allowed to see.

The way I have it designed now is, every group is a group in Cognito. When users join a group they are added to the Cognito group. That group has access to data using the groupsField.
```
type MyData @model @auth(rules: [
  { allow: owner },
  { allow: groups, groupsField: "group", operations: [read] }
]) {
  id: String! 
  description: String
  group: String
}
```

Under this design, I am limited by the amount of Cognito groups I can create.
It sounds intuitive that I should be able to point groupsField to a source in Dynamo where scaling is no issue.

**Comment by ajhool** [comment]
The group field does mean Cognito groups and your dynamodb use case is not currently supported.

I cannot immediately think of an easy way for you to do this and still leverage Amplify's AppSync codegen. You might be able to fandangle the new @function directive into an `isUserInAuthorizedGroup(userId, groupId)` lambda function, but I'm not sure how you can slide that in before the codegen resolvers.

A feature request might be to have a custom Groups resolver. Amplify does purport to be a provider-agnostic framework, so it makes sense that Groups shouldn't be linked to Cognito, specifically. It looks like there is some demand for this feature, already: https://github.com/aws-amplify/amplify-cli/issues/1043#issuecomment-473473735

**Comment by rawadrifai** [comment]
@jordanranz thanks for transferring the issue. Do you need me to close it out here and re-open it under amplify-js?

**Comment by rawadrifai** [comment]
@ajhool I'd be surprised if there's no current way to do it. I think my design can be made better and independent of Cognito groups. But AWS should definitely clarify the recommended approach.

**Comment by rawadrifai** [comment]
Solved this with Amazon's help. The answer is to add a pre token generation trigger in cognito. In the lambda you customize the permissions after you pull from dynamo. 
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html#user-pool-lambda-pre-token-generation-trigger-source

**Comment by hisham** [comment]
@rawadrifai - did you setup the Pre-token generator lambda manually or via cloudformation? It does not seem it can be added via cloudformation. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html and https://forums.aws.amazon.com/thread.jspa?threadID=268907

**Comment by rawadrifai** [comment]
I did it manually. I’m not all that sophisticated with cloudformation. Id
rather wait for amplify to add ability to add triggers from cli.

**Comment by RossWilliams** [comment]
@rawadrifai with the latest amplify updates you can now do this with codegen triggers.

**Comment by hisham** [comment]
@RossWilliams this is not true for the pre-token trigger. See https://github.com/aws-amplify/amplify-cli/issues/1844
