### ISSUE TITLE
amplify push fails after adding new function

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#1577]
Hello!

**Describe the bug**
After adding two new functions using: "amplify add function", subsequent amplify push produces an error:

Following resources failed

Resource Name: dashb-Ampl-A2XACHSRLENP (AWS::IAM::Policy)
Event Type: create
Reason: Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 5c5c7e92-03ab-4820-bd9b-de7e79c135fc)

Resource Name: dashb-Ampl-197FRCX22U3K1 (AWS::IAM::Policy)
Event Type: create
Reason: Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: f25893e2-ba5f-4045-88cb-4ad11436961f)

Resource Name: ServiceRequestReplyMessaging (AWS::Lambda::Function)
Event Type: create
Reason: Resource creation cancelled

**To Reproduce**
1. run: amplify add function
2. name the function
3. Choose "Y" for the env variables question and then [enter] to select no additional permissions
4. run: amplify push --yes

**Expected behavior**
The function is pushed to lambda successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10
Powershell
amplify cli 1.7.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
none. 

Thank you.

**Comment by ryanhollander** [comment]
I should note that this one is blocking my progress. Thank you for your help.

**Comment by kaustavghosh06** [comment]
@ryanhollander Could you check your `amplify/backend/functions/<function-name>` and check for the "AmplifyResourcePolicy"? Do you have one?

**Comment by ryanhollander** [comment]
@kaustavghosh06 I do not have one.

**Comment by kaustavghosh06** [comment]
Can you share the cloudformation file that got generated for your new function?

**Comment by ryanhollander** [comment]
@kaustavghosh06 Sure, here you go.

{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Lambda resource stack creation using Amplify CLI",
    "Parameters": {
        "env": {
            "Type": "String"
        }
    
    },
    "Conditions": {
        "ShouldNotCreateEnvResources": {
            "Fn::Equals": [
                {
                    "Ref": "env"
                },
                "NONE"
            ]
        }
    },
    "Resources": {
        "LambdaFunction": {
          "Type": "AWS::Lambda::Function",
          "Metadata": {
            "aws:asset:path": "./src",
            "aws:asset:property": "Code"
          },
          "Properties": {
            "Handler": "index.handler",
            "FunctionName": {
                "Fn::If": [
                    "ShouldNotCreateEnvResources",
                    "ServiceRequestMessaging", 
                    {

                        "Fn::Join": [
                            "",
                            [
                                "ServiceRequestMessaging",
                                "-",
                                {
                                    "Ref": "env"
                                }
                            ]
                        ]
                    }      
                ]
            },
            "Environment": {"Variables" : { "ENV": {"Ref": "env"}, "REGION": { "Ref": "AWS::Region"}}},
            "Role": { "Fn::GetAtt" : ["LambdaExecutionRole", "Arn"] },
            "Runtime": "nodejs8.10",
            "Timeout": "25"
          }
        },
        "LambdaExecutionRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "RoleName": {
                    "Fn::If": [
                        "ShouldNotCreateEnvResources",
                        "dashboardapiLambdaRole72af1527", 
                        {

                            "Fn::Join": [
                                "",
                                [
                                    "dashboardapiLambdaRole72af1527",
                                    "-",
                                    {
                                        "Ref": "env"
                                    }
                                ]
                            ]
                        } 
                    ]
                },
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "lambda.amazonaws.com"
                                ]
                            },
                            "Action": [
                                "sts:AssumeRole"
                            ]
                        }
                    ]
                }
            }
        }
        ,"lambdaexecutionpolicy": {
            "DependsOn": ["LambdaExecutionRole"],
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "lambda-execution-policy",
                "Roles": [{ "Ref": "LambdaExecutionRole" }],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action":["logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"],
                            "Resource": { "Fn::Sub" : [ "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*", { "region": {"Ref": "AWS::Region"},  "account": {"Ref": "AWS::AccountId"}, "lambda": {"Ref": "LambdaFunction"}} ]}
                        }
                    ]
                }
            }
        }
        ,"AmplifyResourcesPolicy": {
            "DependsOn": ["LambdaExecutionRole"],
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "amplify-lambda-execution-policy",
                "Roles": [{ "Ref": "LambdaExecutionRole" }],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": []
                }
            }
        }
        
    },
    "Outputs": {
        "Name": {
            "Value": {
                "Ref": "LambdaFunction"
            }
        },
        "Arn": {
            "Value": {"Fn::GetAtt": ["LambdaFunction", "Arn"]}
        },
        "Region": {
            "Value": {
                "Ref": "AWS::Region"
            }
        }
    }
}

**Comment by kaustavghosh06** [comment]
You can remove the "AmplifyResourcesPolicy" block from the cloudformation file mentioned above to unblock yourself.

**Comment by ryanhollander** [comment]
Thank worked. Thanks! Is that going to be an issue for each new function I create from now on?

**Comment by kaustavghosh06** [comment]
@ryanhollander If you don't want to access any resources from your Lambda function, then you would answer No to env variables question and you wouldn't see this added policy.
We'll add some additional validations in our CLI to avoid this condition.

**Comment by kaustavghosh06** [comment]
You saw this issue since you selected "Y" to the env variables question but you didn't select any other resource or permissions after that which led to creation of an empty policy statement - which Cloudformation considers as malformed.

**Comment by ryanhollander** [comment]
I see. I misunderstood, I thought that was required to get the env and region data passed in and selecting additional access was an optional step. Thank you for taking the time to explain.

**Comment by swaminator** [comment]
I ran into the same issue.

**Comment by lanceharper** [comment]
Same here.

**Comment by kaustavghosh06** [comment]
@lanceharper Which version of the CLI are you using?

**Comment by lanceharper** [comment]
1.7.0

**Comment by kaustavghosh06** [comment]
Please update to the latest version. We’ve fixed this in our latest patch.

**Comment by lanceharper** [comment]
👍

**Comment by lanceharper** [comment]
is there a way to specify secrets in env variables using the cli?

**Comment by kaustavghosh06** [comment]
You can modify the Lambda Cloudformation file to pass anything custom you would like as environment variables. The file is located in ‘amplify/backend/function/<function-name>’ directory.

**Comment by lanceharper** [comment]
I would prefer to keep these out of the codebase since they are secrets. Something similar to what the serverless framework does: https://serverless.com/framework/docs/providers/aws/guide/variables/
