### ISSUE TITLE
How do subscribe to resource through multiple connections?

### ISSUE THREAD

**Issue by adjmaker** [aws-amplify/amplify-cli#1582]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Appsync subscriptions

** What AWS Services are you utilizing? **
Appsync

** Provide additional details e.g. code snippets **
How do I filter subscriptions based on a relations through connections?

Let's say:

A blog can have multiple posts (one to many), each post can have multiple tags (it's a many to many relationship).

```
type Tag {
  created_at: AWSDate
  posts(filter: ModelPostTagFilterInput, limit: Int, nextToken: String, sortDirection: ModelSortDirection): ModelPostTagConnection
  id: ID!
  text: String!
  updated_at: AWSDate
}
```

```
type Post {
  blog: Blog!
  tags(filter: ModelPostTagFilterInput, limit: Int, nextToken: String, sortDirection: ModelSortDirection): ModelPostTagConnection
  type: String
  upload_date: AWSDate!
  postBlogId: ID!
}
```

```
type PostTag {
  created_at: AWSDate
  post: Post!
  id: ID!
  tag: Tag!
  updated_at: AWSDate
  postTagPostId: ID!
}
```

```
type Blog {
  id: ID!
  title: String!
  posts(filter: ModelPostFilterInput, limit: Int, nextToken: String, sortDirection: ModelSortDirection): ModelPostConnection
}
```

Is it possible to subscribe to `createPostTag` mutation for PostTags for all the posts that belong to a certain blog id? I don't want to subscribe to all tags created mutation since they all won't belong to a particular blog. I also don't want to subscribe to `createPostTag` of all the posts in a blog individually since some blogs have hundreds of posts and creating individual subscription for each one was crashing the browser.

I've tried to pass in an array of post Ids that belong to a blog to a subscription but it didn't work: 
```
  onCreatePostTagOnPosts(postTagPostId: [ID!]): PostTag @aws_subscribe(mutations : ["createPostTag"])
```

**Comment by SwaySway** [comment]
Hi @adjmaker could you provide your schema before compilation?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of customer response/information. Please feel free to comment on this thread if you're still having any problems.
