### ISSUE TITLE
@model directive: Rename list query only works with get query

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1583]
**Describe the bug**
When you specify the `query` argument in the `@model` directive, just rename `list` and try to do a query you always receive the response:

```json
Must provide Source. Received: undefined
```

Only if you provide also a value for `get` it does work.

**To Reproduce**
1. `amplify add api`
2. Define a schema in which you use the `@model` directive with just a `list` argument

```graphql
# rename list query to be correct english
type Address @model(query: { list: "listAddresses" }) {
```

3. Try doing the query in the AppSync console (after you created an entity for the model).
4. See the error.

**Expected behavior**
I would expect the error not to happen.

A corollary to this is that overriding the name of `list` causes no `get` query to be generated at all! Which is also kind of unexpected. I would assume that, if you don't set the query (or mutation / subscription) explicitly to `null` it would still be generated (e.g. just specifying `get` still creates `list` and vice versa).

**Comment by mikeparisstuff** [comment]
@janhesters Can you try running the query via the SDK or other HTTP client to verify the issue?

**Comment by janhesters** [comment]
@mikeparisstuff Done. Ran it via methods in an app generated by Amplify, and it got he same result.

**Comment by mikeparisstuff** [comment]
Thanks for investigating. This will get picked up by a member of the team and we will report back. You can get around this limitation be explicitly specifying the get field in the `@model` declaration e.g. `@model(query: { get: "getAddress", list: "listAddresses" })`.

**Comment by janhesters** [comment]
@mikeparisstuff  That's what I did. Thank you 😊

**Comment by SwaySway** [comment]
Hi @janhesters this is the current implementation if you override any operations if will only generate the specified operations as specified in the `@model` [usage docs](https://aws-amplify.github.io/docs/cli/graphql#usage). Closing this issue for now. Should this need to change based on feedback, I can circle this back to the team as a potential feature request.

**Comment by janhesters** [comment]
@SwaySway Okay, I don't think it's a big issue, and there are way more important feature requests. Thank you for your time!

**Comment by gildniy** [comment]
`@model(queries: {
    get: "getAddress",
    list: "listAddresses"
})` is the right way to do it.
