### ISSUE TITLE
First amplify push errors out at end

### ISSUE THREAD

**Issue by wbroek** [aws-amplify/amplify-cli#1585]
**Describe the bug**
Created a totally new project and environment with the categories below; but when pushed for the first time everything looked ok and was also created in the cloud but it returned an error as the last line. After that it` amplify status` says everything needs to be created but it was all there?
```
Current Environment: kzwanger

| Category | Resource name          | Operation | Provider plugin   |
| -------- | ---------------------- | --------- | ----------------- |
| Auth     | kzwanger        | Create    | awscloudformation |
| Api      |kzwangergraphql | Create    | awscloudformation |
| Api      | userapi                | Create    | awscloudformation |
| Function | userman                | Create    | awscloudformation |
| Storage  | kzwanger        | Create    | awscloudformation |
```

The error it gave was:

`2019-06-05T11:16:10.633Z - error: uncaughtException: must provide pattern date=Wed Jun 05 2019 13:16:10 GMT+0200 (Central European Summer Time), pid=11257, uid=501, gid=20, cwd=/Users/wouter/stack/Projects/Clinicards/Clinicards Erasmus Kwestbare Zwangere, execPath=/usr/local/Cellar/node/11.14.0_1/bin/node, version=v11.14.0, argv=[/usr/local/Cellar/node/11.14.0_1/bin/node, /usr/local/bin/amplify, push], rss=144093184, heapTotal=113745920, heapUsed=70214616, external=833776, loadavg=[1.984375, 2.02783203125, 1.82958984375], uptime=1107313, trace=[column=11, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob/sync.js, function=new GlobSync, line=31, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob/glob.js, function=new Glob, line=129, method=null, native=false, column=9, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js, function=GlobAll.globNext, line=97, method=globNext, native=false, column=8, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js, function=GlobAll.run, line=78, method=run, native=false, column=41, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js, function=Function.globAll.sync, line=192, method=sync, native=false, column=28, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js, function=projects.forEach, line=27, method=forEach, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js, function=generateTypes, line=24, method=null, native=false, column=3, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/callbacks/postPushCallback.js, function=postPushCallback, line=32, method=null, native=false, column=5, file=internal/process/task_queues.js, function=processTicksAndRejections, line=86, method=null, native=false], stack=[Error: must provide pattern,     at new GlobSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob/sync.js:31:11),     at new Glob (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob/glob.js:129:12),     at GlobAll.globNext (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js:97:9),     at GlobAll.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js:78:8),     at Function.globAll.sync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/glob-all/glob-all.js:192:41),     at projects.forEach (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js:27:28),     at Array.forEach (<anonymous>),     at generateTypes (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js:24:14),     at postPushCallback (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/callbacks/postPushCallback.js:32:3),     at processTicksAndRejections (internal/process/task_queues.js:86:5)]`

If pushed again with `amplify push` everything was ok (because it was all there) and no errors where given; status then was `No Change`

**To Reproduce**
1. Create new project with new env
2. Add auth, api graphql, api api function, api storage
3. Push

**Expected behavior**
Finish and say everything is created, status `No Change`

**Desktop (please complete the following information):**
 - OS: MacOSX 10.14.5
 - Node v11.14.0
 - Amplify CLI 1.7.0

**Comment by kaustavghosh06** [comment]
@wbroek Are you seeing this issue with subsequent pushes as well?

**Comment by wbroek** [comment]
@kaustavghosh06 no, only at the first push at the moment

**Comment by kaustavghosh06** [comment]
@wbroek Did you say "Yes" or "No" to the codegen questions during push? This seems to be an issue with codegen. Also, could you share your `<project-root>/.graphqlconfig` file?

**Comment by wbroek** [comment]
@kaustavghosh06 Yes i did say to the codegen question (first push so there is no code?).
My `.graphqlconfig` is below
```
projects:
  kzwangergraphql:
    schemaPath: lambda/src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql

```

**Comment by lanceharper** [comment]
I saw this today as well in a new project. 

Amplify version: 1.7.1
Node version 8.11.3

**Comment by yuth** [comment]
@wbroek @lanceharper during the initial push, what was the answer for `Enter the file name pattern of graphql queries, mutations and subscriptions`?

**Comment by yuth** [comment]
@aws-amplify/cli@1.7.1 has the partial fix. Please comment/re-open if you still can reproduce this
