### ISSUE TITLE
Incorrect inputs generated from models with @key directive and lists

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-cli#1587]
Models with @key directive containing list members does not transform correctly - the generated input and filter models does not contain the lists.

The model:
```
type ListTest @model @searchable @key(fields: ["id","createdAt"]){
  id: ID!
  createdAt: AWSDateTime!
  physicalAddress:  [String]
  notificationEmails: [AWSEmail]
}
```
transforms to the following running `amplify api gql-compile`

```
type ListTest {
  id: ID!
  createdAt: AWSDateTime!
  physicalAddress: [String]
  notificationEmails: [AWSEmail]
}

input ModelListTestFilterInput {
  id: ModelIDFilterInput
  createdAt: ModelStringFilterInput
  physicalAddress: ModelStringFilterInput
  notificationEmails: ModelStringFilterInput
  and: [ModelListTestFilterInput]
  or: [ModelListTestFilterInput]
  not: ModelListTestFilterInput
}

input CreateListTestInput {
  id: ID!
  createdAt: AWSDateTime!
  physicalAddress: String             ###  should be [String]
  notificationEmails: AWSEmail    ###  should be [AWSEmail]
}

input UpdateListTestInput {
  id: ID!
  createdAt: AWSDateTime!
  physicalAddress: String
  notificationEmails: AWSEmail
}

```

This then affects the typescript models that are generated with `amplify codegen`

I've tested without the @key directive and then everything transforms/generates correctly

**Comment by D2KX** [comment]
Yeah I have noticed that aswell when I tried it a few days ago. Using @key with name, fields & queryFields works ok, but changing the primary key like you did will break lists.

**Comment by LYLeon** [comment]
I am seeing this issue as well.

**Comment by LYLeon** [comment]
@kaustavghosh06 Could you give us an estimate for the ETA of the release? Or is there another workaround for this issue? This is critical to our product. Thanks!

**Comment by mikeparisstuff** [comment]
This issue is being actively investigated and we will update here with more details.
