### ISSUE TITLE
Schema review + Accessing GraphQL IDE

### ISSUE THREAD

**Issue by ilrein** [aws-amplify/amplify-cli#1589]
** Which Category is your question related to? **

Graphql (schema)

** What AWS Services are you utilizing? **

AppSync

** Provide additional details e.g. code snippets **

I am able to deploy my ```schema.graphql``` when using the default options. When I tried to create my own, using the existing example, it would throw and error on create:

```
type Project 
  @model 
  @auth(rules: [
      {
        allow: groups,
        groups: ["Project_Managers"],
        queries: [get, list],
        mutations: [create, update, delete]
      },
      {
        allow: groups,
        groups: ["Employees", "Clients"],
        queries: [get, list],
        mutations: null
      }
    ])
{
  id: ID!
  title: String!
  description: String
  status: String
}
type Document
  @model
  @auth(rules: [
    {
      allow: groups,
      groups: ["Project_Managers", "Employees", "Contractors", "Clients"],
      queries: [get, list],
      mutations: [create, update, delete]
    }
  ])
{
  id: ID!
  content: String!
}
```

Is there something wrong with my schema syntax?

**Comment by kaustavghosh06** [comment]
@ilrein Are you still stuck with this issue?

**Comment by kaustavghosh06** [comment]
Closing this issue. Please re-open or comment on this thread if you're still stuck.
