### ISSUE TITLE
Add "--config-json" or similar to "amplify env import" as an alternative to using inline JSON with --config

### ISSUE THREAD

**Issue by bvdaakster** [aws-amplify/amplify-cli#1592]
**Is your feature request related to a problem? Please describe.**
The "amplify env import" command requires the --config parameter passing in a JSON object. It would be nice to have the option to use a file instead of inline JSON here. 

**Describe the solution you'd like**
Example:
`amplify env import --config-json ./env-config.json`
Desired result: the command loads the JSON object from the given file, like:
`amplify env import --config $(cat ./env-config.json)` on GNU/Linux.

**Describe alternatives you've considered**
Using `cat` as described above, unfortunately I switch a lot between Windows and GNU/Linux and am not too familiar with the PowerShell alternatives.

**Comment by renebrandel** [comment]
Hi - I'm closing this issue as it didn't get much traction. If we see more awareness for this feature in the future, please re-open a new issue or @-mention me here.
