### ISSUE TITLE
[Code Generation] Add support for SwiftUI

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#1593]
**Is your feature request related to a problem? Please describe.**
SwiftUI requires any data structs passed to `List()` and `ForEach()` to adhere to  the`Identifiable` protocol. This protocol is unique to SwiftUI and allwos you to uniquely identify which object is which to preform the operations required by SwiftUI.

**Describe the solution you'd like**
When presented the option to generate code you can choose from basic Swift or SwiftUI. The main difference between the two would be that in the List queries and Get queries the Item object would look something like: `public struct Item: GraphQLSelectionSet, Identifiable` instead of `public struct Item: GraphQLSelectionSet`.

**Describe alternatives you've considered**
The work around right now is to store each Item in a new struct that adheres to the protocol which becomes and expensive operation.

**Additional context**
SwiftUI docs can be found here: https://developer.apple.com/documentation/swiftui/

**Comment by wizage** [comment]
Closing as a work around has been found by using the `identified(by:)`. This will allow non-swiftui data structures to be used in the `List()` and `ForEach()`

Example code:
```swift
ForEach(talkStore.listTalks.identified(by:\.id)){ talk in
    TalkCell(talk: talk)
}
```

**Comment by undefobj** [comment]
@wizage could you add a PR to the docs repo?
