### ISSUE TITLE
Wrong cognito user pool ARN generation on AmplifyResourcesPolicy for functions

### ISSUE THREAD

**Issue by forgiangi** [aws-amplify/amplify-cli#1595]
**Describe the bug**
When creating a function with `amplify add function` and giving it permission to perform CRUD operation on a cognito user pool, the generated ARN for the policy has an extra double colon, leading to a AccessDeniedException when invoking the function.

**To Reproduce**
- amplify add auth (default configuration)
- amplify add function
-  Do you want to access other resources created in this project from your Lambda function? (Y/n) Yes
- Select auth
- select create, read, update, delete
-in [functionName]-cloudformation-template.json the AmplifyResourcesPolicy is generated with an extra double colon (arn:aws:cognito-idp::)

**Expected behavior**
The generated ARN should be **arn:aws:cognito-idp:** instead of **arn:aws:cognito-idp::**

**Comment by kaustavghosh06** [comment]
The fix for this is merged - #1610 and will be released to npm in our next release.

**Comment by yuth** [comment]
@aws-amplify/cli@1.7.1 has the fix

**Comment by WhiteAbeLincoln** [comment]
This was a huge headache for me today. I spent probably three hours trying to figure out why the [@function examples](https://aws-amplify.github.io/docs/cli/graphql#usage-2) and my custom lambda code was not working. Super frustrating.

Thanks for the quick response, though this probably shouldn't have been a problem in the first place. A unit test for the template generation could have probably caught it, and an integration test definitely would have.
