### ISSUE TITLE
@auth permissions do not work if data is inserted manually (not through graphql mutations)

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1597]
** Which Category is your question related to? **
Authorization

** What AWS Services are you utilizing? **
Lambda, Amplify, DynamoDB, API

** Provide additional details e.g. code snippets **
When inserting data using graphql mutations generated by codegen, and then I retrieve it with a query, the permissions for "owner" and "group" work great using @auth directive.

If I insert the data using a lambda, even with the correct owner and group information, the permissions do not work when querying the data. It gives unauthorized even for the owner.

My guess is that the mutation does more than inserting data, and I'm not so well versed with vtl to understand what's going on in the generated resolvers.

**Comment by kaustavghosh06** [comment]
@rawadrifai Could you show us the items that you're storing in DynamoDB - manually and through mutation?

**Comment by rawadrifai** [comment]
Sure thing. It looks exactly the same in DynamoDB:

![image](https://user-images.githubusercontent.com/24530625/59062627-22472480-885b-11e9-8128-f7eedbae5c7b.png)

This is my type in schema.graphql
```
type User @model @auth(rules: [
  { allow: owner, ownerField: "id" },
  { allow: groups, groupsField: "group", operations: [read] }
]) {
  id: String! 
  firstName: String 
  lastName: String
  group: String
  dobMonth: String
  dobDay: Int
  dobYear: Int
  address1: String
  address2: String
  country: String
  region: String
  city: String
  postalCode: String
  email: String
  enabled: Boolean
  community: Community @connection(name: "communityUsers")
}
```

The methods I'm inserting into this table are: 
1) auto generated mutations and 2) using AWS.DynamoDB.DocumentClient from a Lambda. 

1 results in queries respecting owner and group permissions.
2 results in 401.

**Comment by rawadrifai** [comment]
Found the answer. Do NOT insert using AWS.DynamoDB.DocumentClient. Rather insert with AWS.DynamoDB and you'll get the expected results.
