### ISSUE TITLE
Amplify hosting with CloudFront and S3 still allows direct access to the S3 bucket with HTTP

### ISSUE THREAD

**Issue by maitreya1975** [aws-amplify/amplify-cli#1599]
**Describe the bug**
Amplify Hosting (using the CLI with 'amplify add hosting') sets up CloudFront and S3 bucket but still allows direct access to the objects in S3.

**To Reproduce**
Create an app following the getting started guide.

1. amplify add hosting
1a - choose the PROD option for CloudFront and S3 (not the DEV option)

2. amplify push

3. amplify publish 

Now you can visit the cloudfront URL displayed by the output of the publish command just fine and it is a HTTPS URL.

However you can also craft the URL for the underlying hosting S3 bucket and view objects directly, using both HTTP and HTTPS.

The reason is that the objects are uploaded with ACL Public Read and this allows direct access. This does not match best practices for using S3 with CloudFront as described here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-cloudfront-to-s3-origin.html

Also, when S3 is used via CloudFront, static website hosting should be disabled so that all access is only allowed from CloudFront via HTTPS.

**Expected behavior**
The hosting S3 bucket is configured so that only CloudFront can access the static website.
Users trying to hit the S3 URLs directly with HTTP/HTTPS are denied access.

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: firefox
 - Version: 66.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UnleashedMind** [comment]
#2369 addressed this.
