### ISSUE TITLE
Deleting a Reflexive Connection take Multiple Tries

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-cli#1601]
**Describe the bug**
You cannot delete a reflexive connection (a connection from the model back to itself — think for a tree of nodes)

**To Reproduce**
1. Create a `@model` that has a named connection to itself
1. Try to delete that model, or that connection
1. In order to actually get it to work, you have to first un-name the connection, then delete the "back half" (that is to say, the half that includes a resolver), then delete the front-half.

**Expected behavior**
You should be able to remove this in a single `push` — not several

**Comment by kaustavghosh06** [comment]
@nagey Could you please share your annotated schema?

**Comment by kaustavghosh06** [comment]
@nagay Closing this issue due to lack of response. Please comment on this thread if you're till stuck with this issue.

**Comment by nagey** [comment]
Sorry, didn't see the notification on this, consider the following schema:
```
type Node @model {
  id: ID!
  parent: Node @connection(name: "NodeTree")
  children: [Node] @connection(name: "NodeTree")
}
```

If you wanted to delete this after creating it, you first have to comment out `parent` and `children` and run `amplify push` and then you can delete the model and run `amplify push` again.

**Comment by nagey** [comment]
@kaustavghosh06 if you want to re-open it is still the same sort of an issue.
