### ISSUE TITLE
I encount build setting not found error when I tried to connect branch at Amplify Console.

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1613]
**About bug**
I have two branches, develop and feature/#6_prepare_graphql_from_vue.
I could connect and deploy 'develop' branch, but, I coudn`t connect 'feature~' branch.

**Amplify Console Images**
This is a image when connecting and deploying to 'develop'branch'.
<img width="1036" alt="スクリーンショット 2019-06-07 12 36 43" src="https://user-images.githubusercontent.com/22259776/59080493-f3e14c00-8923-11e9-8e3a-64def82bd712.png">

This is a image when trying to connect 'feature~' branch.
<img width="1013" alt="スクリーンショット 2019-06-07 12 41 42" src="https://user-images.githubusercontent.com/22259776/59080564-55a1b600-8924-11e9-8512-f93ceabce0bb.png">

I think that these error is caused by branch name(character '#').

Would you please research it ?

** Environment **
Amplify CLI    =>    1.7.0
Vue    =>    3.8.2

**Comment by nimacks** [comment]
Hey @yukitaka13-1110, sorry for the late reply. We've added this as bug and will work on a fix. In the meantime, you can workaround this limitation by removing the `#` character in your branch.

**Comment by yukitaka13-1110** [comment]
Thank you for quick response !
As I expected, a character  '#' was the cause of the bug.
Thank you for verifying.
