### ISSUE TITLE
Cloudfront Permissions added for amplify auth resources broken in 1.7.1

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#1614]
**Describe the bug**
After updating with "amplify update function", new permissions are added to each resource. However, they do not apply properly to the resource (at least in case of auth) due to bad syntax. In the AmplifyResourcesPolicy in the cloudformation template lies the issue, for example:
```
"AmplifyResourcesPolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "amplify-lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"cognito-identity:Describe*",
								"cognito-identity:Get*",
								"cognito-identity:List*",
								"cognito-idp:Describe*",
								"cognito-idp:AdminGetDevice",
								"cognito-idp:AdminGetUser",
								"cognito-idp:AdminList*",
								"cognito-idp:List*",
								"cognito-sync:Describe*",
								"cognito-sync:Get*",
								"cognito-sync:List*",
								"iam:ListOpenIdConnectProviders",
								"iam:ListRoles",
								"sns:ListPlatformApplications"
							],
							"Resource": [
								{
									"Fn::Join": [
										"",
										[
											"arn:aws:cognito-idp::",
											{
												"Ref": "AWS::Region"
											},
											":",
											{
												"Ref": "AWS::AccountId"
											},
											":userpool/",
											{
												"Ref": "authFrontOfficeAuthUserPoolId"
											}
										]
									]
								}
							]
						}
					]
				}
			}
```

The Resource ARN is incorrect, it is sporting an extra : after "cognito-idp" Doing a search and replace in your functions directory for cognito-idp:: to cognito-idp: is a quick fix.

**To Reproduce**
run amplify update function, choose auth and any permission, remove any old permissions that remain in the cloudfront template and update with amplify push. Permission errors will show up in the cloudwatch logs when the functions are executed.

This is Amplify CLI 1.7.1.

**Comment by kaustavghosh06** [comment]
The fix for this is merged - #1610 and will be released to npm in our next release.

**Comment by ryanhollander** [comment]
Now that's what I call quick service! ;-) Thanks!

**Comment by yuth** [comment]
@aws-amplify/cli@1.7.1 has the fix
