### ISSUE TITLE
How to generate #current-cloud-backend build folder without successful push

### ISSUE THREAD

**Issue by ChrisFieldsII** [aws-amplify/amplify-cli#1615]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AWS Amplify push process

** What AWS Services are you utilizing? **
AWS Amplify

** Provide additional details e.g. code snippets **
Is it possible to generate the build folder for #current-cloud-backend? It somehow got deleted and the push process is now trying to create all resources again and throwing errors. I also have a use case where I need to modify the backend build folder before pushing because of inconsistencies between backend and #current-cloud-backend however it is auto-generated each push. Is this overridable?

**Comment by jkeys-ecg-nmsu** [comment]
Maybe this will solve your problem:

`amplify env pull ENV_NAME --restore && amplify push --yes`

**Comment by ChrisFieldsII** [comment]
Unfortunately it doesn't. `pull --restore` doesn't seem to pull all of my resources. I am stuck in a state where amplify push is trying to create 2 tables that already exists. I was able to see the stacks json files and stacks in cloud formation-template.json within the #current-cloud-backend folder and so was trying to copy that into `backend/build` folder as that doesn't pick up on the 2 already created stacks.

**Comment by yuth** [comment]
> Unfortunately it doesn't. pull --restore doesn't seem to pull all of my resources. I am stuck in a state where amplify push is trying to create 2 tables that already exists.

@ChrisFieldsII what resources are missing when you do an `amplify env pull --restore`. Are these the GraphQL API resources? Could you shed some light as to how you got to this state where those table got created?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of user response. Please feel free to commnet on this thread if you're still stuck and want to re-open this issue.

**Comment by RossWilliams** [comment]
pull --restore does not create the build directory in #current-cloud-backend. This breaks ensureMissingStackMappings from working, as it reads from build/stacks.
