### ISSUE TITLE
lambda function access resources behind my graphql api

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#1617]
** Which Category is your question related to? **
api, function

** What AWS Services are you utilizing? **
Lambda, Amplify, S3

** Provide additional details e.g. code snippets **
After `amplify function add` I am allowed to choose resources however available options don't include resources under my graphql endpoint, e.g., the dynamodb table created by `@model` directive.

What am I supposed to do? Is this by design or is it a work in progress feature request? If I want to access the dynamodb behind my graphql api, do I have a hardcode all the resource identifier? Thank you.

**Comment by janhesters** [comment]
Possible duplicate of https://github.com/aws-amplify/amplify-cli/issues/997.

**Comment by YikSanChan** [comment]
Close in favor of #997
