### ISSUE TITLE
Template limit size issue

### ISSUE THREAD

**Issue by psycura** [aws-amplify/amplify-cli#162]
**Describe the bug**
On `amplify push api` get error in console

> Template may not exceed 460800 bytes in size

I have a complex graphql schema, so my question is - how we can avoid this issue?

**Comment by Ahmed2Game** [comment]
#151 like this

**Comment by JustFly1984** [comment]
#185 Same issue.

**Comment by kaustavghosh06** [comment]
This is a duplicate issue. Tracking this issue as a part of #185

**Comment by sacrampton** [comment]
I am having a problem with Template Limits. I have a large number of models & connections so the "ConnectionStack.json" is generating more than 200 Resources in in this file, which in turn exceeds the CloudFormation limit of 200 Resources in a template.

I have tried to split is file into two by editing the cloudformation-template.json to have a "ConnectionStack" and "ConnectionStack01" pointing to ConnectionStack.json and ConnectionStack01.json - but I cannot get that two work during the push.

Any ideas on what to do when the Amplify generated ConnectionStack.json exceeds the 200 Resource Limit of CloudFormation?
