### ISSUE TITLE
local amplify folder lost

### ISSUE THREAD

**Issue by komushi** [aws-amplify/amplify-cli#1625]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
amplify-cli

** What AWS Services are you utilizing? **
cognito, dynamodb, appsync, s3

** Provide additional details e.g. code snippets **
After pushing and publishing to the prod env I lost my local amplify folder. The app code has backups on git server but the amplify folder does not. Is it possible to retrieve cloudformation backend info so I don't have to rebuild everything?

**Comment by yuth** [comment]
@komushi you can use `amplify env pull --restore`. This will restore your `amplify/backend` to what is pushed to the current env. You will loose all the changes that you haven't pushed (if there are any)  by using `--restore` flag.

**Comment by komushi** [comment]
Thanks a lot. I also tried "amplify env import" which works as well.

Just realized that it was needed to copy contents from amplify/current-cloud-backend to amplify/backend to sync it up manually
