### ISSUE TITLE
Unnamed connection to named connection data loss

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#1627]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync, Amplify

** Provide additional details e.g. code snippets **
Note: To better explain the question I create a github repo. See https://github.com/YikSanChan/test-connection.

I create an graphql API with unnamed connection. See [code](https://github.com/YikSanChan/test-connection/commit/7a9ccb7c032c3c7f078e2318209ca122924d32a1#diff-1cbf7d90f439fbe4d8fb4a895a19291d)

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection
}
type Post @model {
  id: ID!
  title: String!
}
```

After I `amplify push` the change, first I create a blog with id=X, then I create a few posts with blogPostsId=X. In related DynamoDB `Post` table, I can find a column `blogPostsId`. I also find `blogPostsId` in `schema.json`, see [code](https://github.com/YikSanChan/test-connection/commit/7a9ccb7c032c3c7f078e2318209ca122924d32a1#diff-18e6ae6c7d995602b7019232ba43b9feR978).

Then I want to change the unnamed connection to a named connection. As I happen to know about this [known issue](https://github.com/aws-amplify/amplify-cli/issues/1406#issuecomment-494533788) when changing too many at once updating `@connection` schema, I do this in 2 separate steps.

First, remove `@connection`. See [code](https://github.com/YikSanChan/test-connection/commit/81dbb94349f082d5e821432a47fcd3bc996e998c#diff-1cbf7d90f439fbe4d8fb4a895a19291dL4).

Second, add back `@connection` and this time a named connection. See [code](https://github.com/YikSanChan/test-connection/commit/52afe6b8911ba7bfbd3e66c554eb00c6add5e05b#diff-1cbf7d90f439fbe4d8fb4a895a19291d)

```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post]
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
}
```

However, this time, it takes `postBlogId` (See [code](https://github.com/YikSanChan/test-connection/commit/52afe6b8911ba7bfbd3e66c554eb00c6add5e05b#diff-18e6ae6c7d995602b7019232ba43b9feR989)) rather than `blogPostsId` when creating a `Post`, and the `blogPostsId` column in `Post` dynamoDB become useless. When I try to list a blog and all its related posts, no post is returned.

What approach I should take so that with named connection it still takes `blogPostsId` rather than `postBlogId`?

Some more context: I want named connection because I want to access a `Blog` from a `Post`. This is not doable with unnamed connection.

**Comment by SwaySway** [comment]
Hi @YikSanChan making changes to a connection will require a full delete of the old connection in order to create a new one on the same type.
One way to work with your current implementation is to create a another GSI which references the GSI created from `posts: [Post] @connection` See below.

```
type Blog @model {
  id: ID!
  name: String!
  description: String
  posts: [Post] @connection
  blogPosts: [Post] @connection(name: "BlogPosts", keyField: "blogPostsId")
}

type Post @model {
  id: ID!
  name: String!
  description: String
  blog: Blog @connection(name: "BlogPosts", keyField: "blogPostsId")
}
```
