### ISSUE TITLE
Ability to specify sortDirection for custom @key with sort key

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-cli#1629]
Currently when creating a custom GSI with the @key directive containing a sort key there is no way to specify the `sortDirection` which would generate the `scanIndexForward` section in the resolver.

E.g. for the model below
```gql
type Payment @model 
  @key(name: "CustomerPayments", fields: ["customer", "createdAt"], queryField: "customerPayments")
{
  id: ID!
  customer: ID!
  ...
}
```

It would be great to be able to specify `sortDirection` as a query input as well without having to override the input/resolver.

**Comment by davidbiller** [comment]
@mdw2000 
Can you explain, how i can change the sortDirection until here is an update? (In Resolver?)

**Comment by dseeker** [comment]
@davidbiller pardon my ignorance I'm trying to find more information about  $modelQueryExpression im the list req resolver. I want my listing to use query instead of scan, how does $modelQueryExpression gets defined so that it will switch to Query operation?
```
#if( !$util.isNull($modelQueryExpression) && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
```

**Comment by davidbiller** [comment]
> @davidbiller pardon my ignorance I'm trying to find more information about $modelQueryExpression in the list req resolver. I want my listing to use query instead of scan, how does $modelQueryExpression gets defined so that it will switch to Query operation?
> 
> ```
> #if( !$util.isNull($modelQueryExpression) && !$util.isNullOrEmpty($modelQueryExpression.expression) )
>   $util.qr($ListRequest.put("operation", "Query"))
>   $util.qr($ListRequest.put("query", $modelQueryExpression))
> #else
>   $util.qr($ListRequest.put("operation", "Scan"))
> #end
> ```

What do you want to do? 
Maybe i can help than better. But i guess, you should open a new Question, because this is not related to the Topic?!

**Comment by dseeker** [comment]
yes sorry, there are only 3 google results for $modelQueryExpression and this page is one of them. I just want to understand more, the conditional is there but how does calling listModel affect the DB operation to determine a Scan or Query? I know there are limitations for SCANs so I'm trying to get some clarification

**Comment by davidbiller** [comment]
> yes sorry, there are only 3 google results for $modelQueryExpression and this page is one of them. I just want to understand more, the conditional is there but how does calling listModel affect the DB operation to determine a Scan or Query? I know there are limitations for SCANs so I'm trying to get some clarification
> 
> generated list query:
> 
> > listReceipts(filter: ModelReceiptFilterInput, limit: Int, nextToken: String): ModelReceiptConnection
> 
> what value is there to pass to make it use Query instead of Scan? how does $modelQueryExpression gets defined?

They are seperate resolver. if you call a getModel than it will call a query resolver.
And on listModel it will call a scan, there you will get an nextToken.

**Comment by dseeker** [comment]
Query.getReceipt.req.vtl has a different resolver.
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
  "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
} #end
}
```

Query.listReceipts.req.vtl has 
```
$util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
```
but it's still unclear how to execute this from listModel.. anyway thanks for the reply I will stop hijacking the thread

**Comment by SwaySway** [comment]
closing this issue as the pr has been merged

@mdw2000 with this pr your @key query would look like the following
```gql
type Query {
	...
	customerPayments(
		customer: ID,
		createdAt: ModelStringKeyConditionInput,
		sortDirection: ModelSortDirection,
		filter: ModelPaymentFilterInput,
		limit: Int, 
		nextToken: String): ModelPaymentConnection
	...
}
```

**Comment by half2me** [comment]
What is `$modelQueryExpression` ? I don't see it being set anywhere, and its not coming from `$context` 😕
