### ISSUE TITLE
Static group auth for queries in res and not req?

### ISSUE THREAD

**Issue by boreview** [aws-amplify/amplify-cli#1630]
Is there a good reason I'm missing out on for putting static group auth in the response resolver template? Does that mean in case a user is not authorized via a group, we would read the table first, only to find out that we can't return the results?

**Comment by mikeparisstuff** [comment]
@boreview The reason for this is that, in the future, we would like to allow auth rules to be composed with and/or expressions in the future and some of the information necessary to evaluate a boolean expression composed of static & dynamic rules would not be available until the data was fetched. It is possible to encode some of these authorization checks as filter expressions but this is not generally applicable (e.g. you cannot encode a static auth check as a filter expression) and would not work across data sources. The current implementation makes an assumption on the shape of the XConnection object result and that auth check can be applied to any call that returns that shape.

**Comment by brene** [comment]
Closing as pending-response for longer than 14 days
