### ISSUE TITLE
Modelling friends in Amplify

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#1637]
With Amplify API I am trying to implement the abilty to add friends and store them under a user model. Something like this:

```graphql
type User @model {
   id: ID!
   name: String
   friends: [User] @connection(name: "friends")
}
```

Amplify doesnt yet support many to many, and the solution of creating a join model pullls the following error:  

```graphql
type UserFriends @model {
  id: ID!
  user_a: User!
  user_b: User!
  confirmed: Boolean!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

> Property AttributeDefinitions is inconsistent with the KeySchema of the table and the secondary indexes

Is there a particular approach with Amplify that could model friendships whilst also maintaining the ability to return the friend list within the user model?

**Comment by mikeparisstuff** [comment]
You can use the `@key` directive (https://aws-amplify.github.io/docs/cli/graphql#key) to implement an adjacency list pattern in DynamoDB (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html). This will allow you to create top level query fields that query the many-to-many relationship. We have an item in the backlog to introduce a new directive the implements similar `@connection` behavior but on top of `@key` but there is no ETA yet. We are working through a PR that introduces the ability to write your own transformer modules that could be used to implement directives that are specific to your application.

**Comment by oliverandersencox** [comment]
@mikeparisstuff thanks for the links, however I have had no luck trying to implement that. Would you be able to give an example of how I would model this Adjacency list pattern for the friend relationship.

Its a real blocker for me! Thank in advance :D

**Comment by avlonder** [comment]
Hi, the last post in this issue was some time ago but I am also looking for an example of how to implement a bidirectional friendship relation in AppSync... Any thoughts?

```
type User @model {
  id: ID!
  friends: [Friendship] @connect(name: "UserFriends")
  outgoingFriendRequests: [FriendRequest] @connect(name: "SenderRequests")
  incomingFriendRequests: [FriendRequest] @connect(name: "ReceiverRequests")
}

type Friendship @model {
  id: ID!
  user: User! @connect(name: "UserFriends")
  friend: User! @connect

type FriendRequest @model {
  id: ID!
  sender: User! @connect(name: "SenderRequests")
  receiver: User! @connect(name: "ReceiverRequests")
```

I'm not sure if the above schema makes any sense? Anyway, I do not see how to make the relation bidirectional: if one user creates/deletes a friendship, the other user does not know. Or am I wrong? Sorry, I'm quite new to all of this...

**Comment by vishnuprasadkv55** [comment]
I run into the same issue, have anyone got an update?
