### ISSUE TITLE
Queries return a lot of empty list with many users / items per table

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1639]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
DynamoDB, Cognito, GraphQL Transform
** Provide additional details e.g. code snippets **
I noticed when creating a schema using the `auth` directive the code that filters the item for the given owner of the query and item is in the resolver mapping of the corresponding model. 

E.g.:

```vtl
## No Static Group Authorization Rules **


## [Start] If not static group authorized, filter items **
#if( ! $isStaticGroupAuthorized )
  #set( $items = [] )
  #foreach( $item in $ctx.result.items )
    ## No Dynamic Group Authorization Rules **


    ## [Start] Owner Authorization Checks **
    #set( $isLocalOwnerAuthorized = false )
    ## Authorization rule: { allow: owner, ownerField: "owner", identityField: "cognito:username" } **
    #set( $allowedOwners0 = $item.owner )
    #set( $identityValue = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
    #if( $util.isList($allowedOwners0) )
      #foreach( $allowedOwner in $allowedOwners0 )
        #if( $allowedOwner == $identityValue )
          #set( $isLocalOwnerAuthorized = true )
        #end
      #end
    #end
    #if( $util.isString($allowedOwners0) )
      #if( $allowedOwners0 == $identityValue )
        #set( $isLocalOwnerAuthorized = true )
      #end
    #end
    ## [End] Owner Authorization Checks **


    #if( ($isLocalDynamicGroupAuthorized == true || $isLocalOwnerAuthorized == true) )
      $util.qr($items.add($item))
    #end
  #end
  #set( $ctx.result.items = $items )
#end
## [End] If not static group authorized, filter items **

$util.toJson($ctx.result)
```

In the DynamoDB docs it says that the [maximum limit for queries is 1MB](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html). Doesn't that mean, that if I have many users and even more items some users will get empty responses for their first couple of queries? Because as far as I know the filtering gets applied after the request. If the filter would be using a secondary index, you would avoid this, but since the filter is in the resolver template, you would get back empty responses, until you reach items created by the users. But if that user joined your service late, his items might be further back than just 1MB (or a limit of 1000 for each loops).

Does this make sense? Is this a bug? If this is true you could **only** query using GSI's and LSI's at scale, don't you?

**Comment by janhesters** [comment]
Okay, I made an example to make sure this is the actual behavior and *it confirms it*.

1. `npx create-react-app myapp && cd myapp && yarn add aws-amplify`
2. `amplify init`
3. `amplify add auth`
4. `amplify add api` choose simple todo schema.
5. Create two users in the Amplify console
6. Configure Amplify in `index.js`
7. Modify `App.js` to reflect the following

```jsx
import React, { useEffect, useState } from 'react';
import { API, Auth, graphqlOperation } from 'aws-amplify';
import './App.css';

import { listTodos } from './graphql/queries';
import { createTodo, deleteTodo } from './graphql/mutations';

const asyncForEach = async (array, callback) => {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array);
  }
};
const range = (start, end) =>
  Array.from({ length: end - start + 1 }, (x, i) => i + start);

function App() {
  const [todosCount, setTodosCount] = useState(0);

  useEffect(() => {
    async function loginAndCreateTodos() {
      try {
        // My users are named, testone@test.com and testtwo@test.com
        await Auth.signIn('testone@test.com', 'password');
        const todosData = await API.graphql(
          graphqlOperation(listTodos, { limit: 1000 })
        );
        console.log(todosData);
        const count = todosData.data.listTodos.items.length;
        setTodosCount(count);
        if (count < 1000) {
          console.log('Creating Todos ...');
          const dummyTodos = range(count, 1000).map(i => ({
            name: `Dummy${i}`,
          }));
          await asyncForEach(dummyTodos, async input => {
            await API.graphql(graphqlOperation(createTodo, { input }));
          });
          console.log('Done creating. Reload your app.');
        }
      } catch (error) {
        console.log(error);
      }
    }

    loginAndCreateTodos();
  }, []);

  return (
    <div className="App">
      <h4>Todo Count</h4>
      <p>{todosCount}</p>
    </div>
  );
}

export default App;
```

8. Log in with the first user. Wait until it says `"Creating Todos ..."` and `"Done creating. Reload your app."` in the console. Reload the app to see that there are now a thousand todos for this user. Furthermore, no more todos should be created at this point.
9. Log in with the second user using the AWS AppSync console and create a single todo.
10. Now reload the app again and you will see that it now says 999 todos and that it starts creating todos again.

As far as I can tell this is an issue with the code created by Amplify. It will affect applications with many users and could even cause just empty requests being returned. Filtering through the resolver is bad because of the [1000 for loop limit](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_appsync). Ideally you would filter using DynamoDBs filter and pass as a `nextToken` DynamoDB's `LastEvaluatedKey` if the queried items are more than [1MB in size](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html).

**Comment by janhesters** [comment]
**Another Update:**

The reverse works too and shows even better the problem. Follow all steps of my previous comment, but have the second user create his item first, then have the first user create his 1000 items. Now if the second user tries to do a list query it is empty just returning a `nextToken`.

**Comment by mikeparisstuff** [comment]
@janhesters Yes when building applications on DynamoDB you need to build support for your access patterns into your table design. If you need to look up objects based on some "ownership" attribute for example, then you should create a `@key` that uses that attribute and enables the access pattern. The @auth checks occur in the response mapping template because it makes the implementation data source agnostic and depends only on the shape of a `XConnection` result. The intention is that you can use `@key` to define support for your access patterns and use `@auth` to ensure that no one sees information that they shouldn't.

**Comment by janhesters** [comment]
@mikeparisstuff  Yes, that makes sense. I just suspect that people using Amplify might run into these problems, not understanding while it behaves the way it does. Which is why I think it might be more future proof to rewrite the auth checks from using the `velocity` templates' logic to using DynamoDB's `filter` alongside moving `nextToken` to just reflect `LastEvaluatedKey`.

Because as far as I know, the auto generated code always uses DynamoDB so there is no need to make it platform agnostic using the `.vtl` files, isn't it? Simultaneously, we could start teaching people proper NoSQL design in the docs (aka. go for only one `@model` in the whole schema and a lot of `null`able attributes = single table + optional attributes).

While I have no idea how Amplify works behind the scenes which is why I couldn't help out solving the template issue, I could help writing the docs.

**Comment by mikeparisstuff** [comment]
@janhesters If you are interested in helping write documentation, we are happy to help you help by reviewing PRs.

> moving nextToken to just reflect LastEvaluatedKey

The nextToken is an opaque cursor that is a encrypted, serialized version of the `LastEvaluatedKey`. Handling the conversion from the potentially complex key to the single string is done for you to make it easier to deal with.

> might be more future proof to rewrite the auth checks from using the velocity templates' logic to using DynamoDB's filter.

I see this largely as an implementation detail as the results from the query would be no different even if the auth check were implemented as a filter and you would still need to use @key to enable efficient access patterns. I am not opposed to considering new implementations for this but we should think through the design.

> aka. go for only one @model in the whole schema and a lot of nullable attributes = single table + optional attributes.

We have thought about this at length and supporting single table use cases was a goal of `@key`. You are welcome to implement single `@model` applications using `@key` and we will continue to make it easier to do so but will also continue to support multi table APIs. If you would like to help document design best practices as well as use cases and how to solve them that would be much appreciated.

**Comment by janhesters** [comment]
@mikeparisstuff

Thank you for your answer 🙏 

> If you are interested in helping write documentation, we are happy to help you help by reviewing PRs :)

Will continue to do that if I feel like I can provide good documentation.

> The nextToken is an opaque cursor that is a encrypted, serialized version of the LastEvaluatedKey. Handling the conversion from the potentially complex key to the single string is done for you to make it easier to deal with.

Didn't know that, learned something new, thank you 💡 I tried finding the code for the `nextToken` generation, but couldn't find it. Do you have any resources that I could read (code or docs) to help me understand this process and how `nextToken` is created better?

> I see this largely as an implementation detail as the results from the query would be no different even if the auth check were implemented as a filter

I feel like its more than just an implementation detail, because responses would be very different because you could query more than 1000 entities and items wouldn't be "ghosted" like in my example above.

> and you would still need to use @key to enable efficient access patterns.

True.

> If you would like to help document design best practices as well as use cases and how to solve them that would be much appreciated.

Sure, if I find the time, I'll gladly do so 👍 I might make a small PR just to link to the DynamoDB docs, because their best practices part is pretty great and I feel like mentioning that in the docs is a pareto solution.

**Comment by edlefebvre** [comment]
@janhesters don't you loose the advantages of GraphQL (get all data in one query) using a single DynamoDB table?

Unless you opt for a REST API?

**Comment by janhesters** [comment]
@edlefebvre AFAIK GraphQL is independent from the design of a NoSQL database. The DB doesn't care whether you choose REST, GraphQL or a message in a bottle to communicate between your backend and your client. Besides that, if you read the design guidelines for DynamoDB you will find that its recommended to come up with all necessary queries FIRST and then design you DB so that all those queries run efficient.

**Comment by edlefebvre** [comment]
@janhesters that's true. But maybe I can explain better what troubles me. Taking the example in the documentation : 

With this schema:
```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```

You can make this query:
```
query GetBlog($blogId:ID!) {
  getBlog(id:$blogId) {
    id
    name
    posts {
      items {
        id
        title
        comments {
          items {
            id
            content
          }
        }
      }
    }
  }
}
```

You get everything with this single query. How would you do the same query with a single table schema?

**Comment by janhesters** [comment]
@edlefebvre To understand that, you would need to read [this](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-relational-modeling.html).

**Comment by edlefebvre** [comment]
@janhesters thank you for sharing, but I already read it several times. I understand the logic behind this, but not the implementation with amplify / graphql. Maybe it's because I should denormalize data in a certain way...
