### ISSUE TITLE
How do I configure credentials in a CI environment?

### ISSUE THREAD

**Issue by bramski** [aws-amplify/amplify-cli#164]
** Which Category is your question related to? **
Hosting

** What AWS Services are you utilizing? **
Bitbucket/Cloudformation

** Provide additional details e.g. code snippets **
When I configure aws-amplify it gets me to input a key and access code and region.
I need to be able to configure this by the command line so that I can configure our CI environment to deploy the website.

**Comment by UnleashedMind** [comment]
I will mark this as a feature request.

**Comment by kaustavghosh06** [comment]
I think taking a look at our circle CI scripts which we use for our smoke tests would be helpful -> https://github.com/aws-amplify/amplify-cli/tree/master/.circleci 

Wr use "expect" to go through the CLI flow.

**Comment by kaustavghosh06** [comment]
@bramski Let me know if you're still blocked on this.
