### ISSUE TITLE
Amplify elastic search domain not found

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#1643]
**Describe the bug**
I am following the guide here: https://aws-amplify.github.io/docs/cli/graphql#key

On adding custom resolvers for elastic search based of location. I have everything set up and then went to add the resolvers exactly as described.

I used 'aws es list-domain-names' to get the domain of the elastic search and then on push get this error:

> Resource Name: QueryNearByEvents (AWS::AppSync::Resolver)
Event Type: create
Reason: No data source found named doin-io-ela... (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 8c585df8-8c29-11e9-81e0-394fe7a58a3c)

This is the domain created by amplify and copied exactly from the AWS console.

Here is the stack resource

` "QueryNearByEvents": {

      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": {
          "Ref": "AppSyncApiId"
        },
        "DataSourceName": "doin-io-elas....",
        "TypeName": "Query",
        "FieldName": "nearByEvents",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.nearByEvents.req.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.nearByEvents.res.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        }
      }
    }`

**Comment by oliverandersencox** [comment]
So for anyone else having this issue - it turns out you must leave this:

`  "DataSourceName": "doin-io-elas....",`

as 

`  "DataSourceName": "ElasticSearchDomain",`

Amplify has all the parameters sorted already

**Comment by mikeparisstuff** [comment]
The name of the AppSync data source that points to the elasticsearch domain is named "ElasticSearchDomain" by default. Any custom resolvers may reference the data source by that name.
