### ISSUE TITLE
Is it possible to rename a Resource Name?

### ISSUE THREAD

**Issue by OpTiCz27** [aws-amplify/amplify-cli#165]
** Which Category is your question related to? **
Resource Update

** What AWS Services are you utilizing? **
API Gateway

** Provide additional details e.g. code snippets **
After creating a resource (auth, api, function), is it possible to rename them?
For example:
`amplify api add`
`? Provide a friendly name for your resource to be used as a label for this category in the project: example1`

How can I rename example1 to something else without having to delete it and recreate it?

**Comment by UnleashedMind** [comment]
Hi @OpTiCz27 
Resource names can not be changed

**Comment by kaustavghosh06** [comment]
@OpTiCz27 Would recommend removing and adding the resource..since that's what actually will happen on the cloud if you decide to change resource names.

**Comment by kaustavghosh06** [comment]
Please feel free to re-open this if you still think this is an issue.

**Comment by cybercussion** [comment]
haha I did the same thing with a tutorial and apparently I will live with it because we all know demos go to production :)
