### ISSUE TITLE
AmplifyCLI not working with MFA-enabled IAM Role with Yubikey security key

### ISSUE THREAD

**Issue by dennisAWS** [aws-amplify/amplify-cli#1654]
Attempting to utilize the "assume role" (with MFA enabled using a YubiKey security key) feature of the Amplify CLI. Followed these instructions here:
https://aws-amplify.github.io/docs/cli/init#assuming-an-iam-role

The CLI

**Describe the bug**
The CLI attempts to init and sees that I have assume role with MFA but it appears to be only looking for a 6-digit passcode. I'm using a Yubikey 5C and the OTP that spits out is something like this: xxxxxxkngruddkdFAKEvihlnbcrvunuvuitedhcrucuc

**To Reproduce**
`amplify init                          
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project mfatest
? Enter a name for the environment master
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use yubikey
⠋ Initializing project in the cloud...Profile yubikey is configured to assume role
  arn:aws:iam::xxxxxxxxxx:role/MFAEnabledAdminIAMRole
It requires MFA authentication. The MFA device is
  arn:aws:iam::xxxxxxxxxxx:u2f/user/yubikey/default-VF3CTHISISTOTALLYFAKEJM6TBBM
⠇ Initializing project in the cloud
>> Must have length equal to 6
`

**Expected behavior**
For the CLI to prompt for the MFA code from the security key and authenticate the user.

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser None
 - Version Amplify CLI v1.7.2

**Comment by UnleashedMind** [comment]
@dennisAWS 
According to this document: 
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

The MFA TokenCode can only be of length 6.
