### ISSUE TITLE
Enable HTTP/2 protocol support

### ISSUE THREAD

**Issue by bakeruk** [aws-amplify/amplify-cli#1658]
Hi,

I've noticed whilst doing a Lighthouse audit of my site that the `HTTP/2` protocol is not enabled out-of-the-box with Amplify.

Currently all comms with Amplify use the `HTTP/1.1` protocol. I'm guessing this has not been enabled via the CloudFront distribution?

Is it possible to enable `HTTP/2` protocol support for Amplify or give me access to the CloudFront distribution so that I can enable it myself?

Cheers!

**Comment by yuth** [comment]
@bakeruk according to the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html) cloudfront by default enables HTTP 2
> HttpVersion
    (Optional) Specify the maximum HTTP version that you want viewers to use to communicate with CloudFront. The default value for new web distributions is http2. Viewers that don't support HTTP/2 automatically use an earlier HTTP version.
    For viewers and CloudFront to use HTTP/2, viewers must support TLS 1.2 or later, and must support Server Name Identification (SNI).
    In general, configuring CloudFront to communicate with viewers using HTTP/2 reduces latency. You can improve performance by optimizing for HTTP/2. For more information, do an Internet search for "http/2 optimization."
    Required: No
    Type: String
    Allowed Values: http1.1 | http2

If you explictly want to enable http2 please go ahead and update the cloudformation file inside `<project-root>/amplify/backend/hosting/S3AndCloudFront/template.json` and add `HttpVersion` to your DistributionConfig

**Comment by bakeruk** [comment]
Excuse this ticket. My tooling was showing connections as `HTTP/1.1` however after changing to another, connections show up as using the `HTTP/2` protocol.

Many thanks for the quick response!
