### ISSUE TITLE
How do I publish in a CI/non-terminal environment?

### ISSUE THREAD

**Issue by bramski** [aws-amplify/amplify-cli#166]
** Which Category is your question related to? **
Publish/Hosting

** What AWS Services are you utilizing? **
Cloudformation/S3

** Provide additional details e.g. code snippets **
How do I get rid of the required "Yes" at the start of a publish command?  I'd like to automate the deploy process.
<img width="717" alt="screen shot 2018-09-13 at 1 51 12 pm" src="https://user-images.githubusercontent.com/421781/45515124-1f038a00-b75c-11e8-85f7-b56c65f5418c.png">

**Comment by UnleashedMind** [comment]
This related to #164
Currently the CLI does not have enough support to take in command line parameters, neither does it take the --yes flag. 
I marked both issues as feature request, and it's in our backlog to add such support.

**Comment by kaustavghosh06** [comment]
I think taking a look at our circle CI scripts which we use for our smoke tests would be helpful -> https://github.com/aws-amplify/amplify-cli/tree/master/.circleci 

Wr use "expect" to go through the CLI flow.

**Comment by kaustavghosh06** [comment]
@bramski 

We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backward from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by kaustavghosh06** [comment]
Based on all of your feedback, we’ve released a beta version of the CLI (npm install -g @aws-amplify/cli@multienv)  to support multiple environments, team workflows and integrate with your CI/CD flows.
Please check out this documentation for more details - https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Also, as a part of our feedback mechanism, we’ve opened up another [GitHub issue](https://github.com/aws-amplify/amplify-cli/issues/508),  to track feedback from everyone, iterate on this beta version and then merge it to master.  We'll close this issue and track feedback in #508. Looking forward to your feedback on this release.

**Comment by kaustavghosh06** [comment]
Closing this issue since this problem is solved with the release of the multienv feature-set mentioned above. Please feel free to re-open the issue if you've further questions about this.

**Comment by lielran** [comment]
@kaustavghosh06 I think this is a real pain. it is not clear how to install amplify on ci and the headless scripts unclear. I would like to see a real solution to the problem

**Comment by ambientlight** [comment]
@lielran:
for references: the approach the worked for me is described in the end of https://github.com/aws-amplify/amplify-cli/issues/1236#issue-431091941
