### ISSUE TITLE
 Unexpected token < in JSON at position 2

### ISSUE THREAD

**Issue by vishwakalyanaraman** [aws-amplify/amplify-cli#1662]
**Describe the bug**
During the execution of `amplify-init` the console returns an error message:

```
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: <MY ENV NAME>
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use <MY PROFILE NAME>
✖ There was an error initializing your environment.
init failed
SyntaxError: Unexpected token < in JSON at position 2
    at JSON.parse (<anonymous>)
    at readJsonFile (/usr/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:11:15)
    at populateAmplifyMeta (/usr/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:93:31)
    at initializeEnv (/usr/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:28:7)
    at run (/usr/lib/node_modules/@aws-amplify/cli/src/lib/init-steps/s9-onSuccess.js:52:9)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**To Reproduce**
1. Clone https://github.com/dakshjotwani/Finder.git
2. `cd finder_app` 
3. `git checkout UI` and run `amplify-init`

**Expected behavior**
Successful initialization of the project

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Amplify Version: 1.7.1
 - npm Version: 6.9.0

**Comment by kaustavghosh06** [comment]
@vishwakalyanaraman The `backend-config.json` seems to be corrupted in the amplify/ directory. I don't seem to have access to https://github.com/dakshjotwani/Finder.git, so I can't take a look at the structure of that file.

**Comment by vishwakalyanaraman** [comment]
Hi there. Could I have your git ID so I can add you as a contibutor so you
can take a look at it? Thanks.


On Jun 14, 2019 at 11:46 AM, <Kaustav Ghosh <notifications@github.com>>
wrote:

@vishwakalyanaraman <https://github.com/vishwakalyanaraman> The
backend-config.json seems to be corrupted in the amplify/ directory. I
don't seem to have access to https://github.com/dakshjotwani/Finder.git, so
I can't take a look at the structure of that file.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws-amplify/amplify-cli/issues/1662?email_source=notifications&email_token=AFMEX6HLZ2R7F2LLJFQBVBLP2MZTRA5CNFSM4HYEY25KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXV2ONI#issuecomment-501983029>,
or mute the thread

**Comment by kaustavghosh06** [comment]
kaustavghosh06

**Comment by vishwakalyanaraman** [comment]
I've finally found the issue. There was an unmentioned merge conflict in
backend-config.json. The '<' character was a part of the HEAD and that was
causing the issue. Thanks for the help!
