### ISSUE TITLE
“Bucket already exists” when deploying with Amplify Console

### ISSUE THREAD

**Issue by awsed** [aws-amplify/amplify-cli#1667]
I noticed there’s a “bucketName" parameter in "amplify/backend/storage/xxxxxx/parameters.json” which means it'll always create a bucket with the same name. I get a “bucket already exists” error when trying to deploy a project in the Amplify Console.

The background is that my amplify project has file storage and I want to share my app using the Amplify Console "One-Click Deploy Button". I can delete my bucket and make it work only once however if I share the project with another dev and they try to deploy on their account using the "master" environment they'll get the same "Bucket Already Exists" error as S3 bucket names are unique.

I suggest to change the "bucketName" parameter to be the CloudFormation stack name + the environment name. That way we guarantee new deployments won't try to use existing buckets.

**Comment by kaustavghosh06** [comment]
@awsed We did add this feature and is a part of the latest version of the CLI - 4.16.1
The bucket names are randomized and leverage the Cloudformation uuid in it :)
