### ISSUE TITLE
No way to pass in metadata headers on website S3 object.

### ISSUE THREAD

**Issue by jonsmirl** [aws-amplify/amplify-cli#167]
Sometimes you need to add metadata on the website S3 objects in order to insert Cache-Control or Expires headers. Those headers then tell Cloudfront how long to cache that particular object. There needs to be some way to instruct 'amplify publish' to add these headers to a particular file when needed.

This is how you add them manually....

To add a Cache-Control or Expires header field to Amazon S3 objects using the Amazon S3 console

Sign in to the AWS Management Console and open the Amazon S3 console at https://console.aws.amazon.com/s3.
In the Amazon S3 console, in the buckets pane, click the name of the bucket that contains the files.
In the list of objects, select the first object to which you want to add a header field.
Click Actions and click Properties.
In the right pane, expand Metadata.
Click Add More Metadata.
In the Key list, click Cache-Control or Expires, as applicable.
In the Value field, enter the applicable value:
For a Cache-Control field, enter: max-age=number of seconds that you want objects to stay in a CloudFront edge cache
For an Expires field, enter a date and time in HTML format.
Click Save.

**Comment by kaustavghosh06** [comment]
@jonsmirl You can update the hosting Cloudformation template with this information you've mentioned above before you do a publish.

**Comment by jonsmirl** [comment]
I see that I could edit './#current-cloud-backend/hosting/S3AndCloudFront/template.json', but is that file safe to edit? Are any of the tools going to overwrite it?

**Comment by kaustavghosh06** [comment]
You can go ahead and edit it.
 It would be overwritten only if you go ahead and explicitly run the `amplify hosting configure` command to change some of the configurations tied to the hosting category.

**Comment by UnleashedMind** [comment]
You can run 
`amplify hosting configure`
and select to configure CloudFront when prompt. 
The CLI will lead you to specify the default cache behavior.

**Comment by kaustavghosh06** [comment]
@jonsmirl Let me know if the above-mentioned solutions worked for you. Feel free to re-open if the issue still persists.

**Comment by jonsmirl** [comment]
The easiest way I found to solve this was to modify the publish command to addon an aws cli copy of the files with the appropriate cache control. Like this:
aws s3 cp --cache-control='no-cache' build/sw.js s3://`jq -r .WebBucket ../config/stack.json`
