### ISSUE TITLE
Filters not generated for @connection type fields

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#1672]
Below is my schema definition in that there are 5 connection fields and among that 2 of them are reference to same table.
```
type VarietyStage @model @searchable {
	varietyStageId: ID!
	variety: VarietyMain @connection(keyField: "varId")
	stage: MasterStage @connection(keyField: "stageId")
	country: MasterLocation @connection(keyField: "locationId")
	year: String
	createdBy: UserMain @connection(keyField: "createdUserId")
	updatedBy: UserMain @connection(keyField: "updatedUserId")
	createdAt: String
	updatedAt: String
}
```
The issue is that filters are not generating for connection fields, as you can see below only the non connection field's filter inputs are been generated
```
input ModelVarietyStageFilterInput {
	varietyStageId: ModelIDFilterInput
	year: ModelStringFilterInput
	createdAt: ModelStringFilterInput
	updatedAt: ModelStringFilterInput
	and: [ModelVarietyStageFilterInput]
	or: [ModelVarietyStageFilterInput]
	not: ModelVarietyStageFilterInput
}
```

**Comment by ajhool** [comment]
Does amplify support filters/limits on connection fields? Have you tried this yet?

**Comment by mikeparisstuff** [comment]
Hey @meetrij you should be able to just add the fields to the type and they will be included in the filter inputs. The `@connection` directive automatically wires up using the underlying id when issuing the query to DynamoDB so the ids were not included as they are injected automatically. E.G. when traversing some `MasterStage.varietyStages` field, the DynamoDB query will automatically have the correct `stageId`. If you want to be able to traverse the same `MasterStage.varietyStages` and filter additionally on another field `locationId`, you can add the fields explicitly. 

E.G.

```graphql
type VarietyStage @model @searchable {
	varietyStageId: ID!
	variety: VarietyMain @connection(keyField: "varId")
	stage: MasterStage @connection(keyField: "stageId")
	country: MasterLocation @connection(keyField: "locationId")
	year: String
	createdBy: UserMain @connection(keyField: "createdUserId")
	updatedBy: UserMain @connection(keyField: "updatedUserId")
	createdAt: String
	updatedAt: String

        # If you add the fields, they will be filterable.
        locationId: ID
        ....
}
```

**Comment by meetrij** [comment]
@mikeparisstuff filters are not coming directly, you are correct if I add the fields as you mentioned like below
```
type VarietyStage @model @searchable {
	varietyStageId: ID!
	variety: VarietyMain @connection(keyField: "varId")
	stage: MasterStage @connection(keyField: "stageId")
	country: MasterLocation @connection(keyField: "locationId")
	year: String
	createdBy: UserMain @connection(keyField: "createdUserId")
	updatedBy: UserMain @connection(keyField: "updatedUserId")
	createdAt: String
	updatedAt: String

        # If you add the fields, they will be filterable.
        varId: ID
        stageId: ID
        locationId: ID
        createdUserId: ID
        updatedUserId: ID
        ....
}
```
It would be coming in filter section for 'VarietyStage' but how this in mutation section? and why not coming directly?

My types are

```
type VarietyStage @model {
	varietyStageId: ID!
	variety: VarietyMain @connection(keyField: "varId")
	stage: MasterStage @connection(keyField: "stageId")
	country: MasterLocation @connection(keyField: "locationId")
	year: String
	createdBy: UserMain @connection(keyField: "createdUserId")
	updatedBy: UserMain @connection(keyField: "updatedUserId")
	createdAt: String
	updatedAt: String
}
```
```
type MasterStage @model {
	stageId: ID!
	stageCode: String
	foundationCode: String
	description: String
}
```
```
type MasterLocation @model {
	locationId: ID!
	locationCode: String
	locationName: String
	locationLevel: Int
	parent: Int
}
```
...

**Comment by kaustavghosh06** [comment]
We don't support this currently, but as mentioned by @mikeparisstuff, you could acheive what you're trying to do by just adding the fields to the type.

**Comment by meetrij** [comment]
@kaustavghosh06 it's actually wrong method to add fields as it will come for mutation there I actually no need to add data and it also increases the size of schema which will result in another issue #185

**Comment by andre-scheffer** [comment]
Are there any news @meetrij, @kaustavghosh06? From my point of view it is absolutely necessary to be able to filter according to the connection IDs. And this cannot only work via a key field. If you subsequently decide on further filter criteria, then the entire table or at least parts of it must be deleted. This is not acceptable for a production environment. I think the whole filter and sorting mechanism needs a fundamental revision. It's nice how GraphQL works, but when I can't do the simplest things, the most beautiful tool doesn't add any value but slows me down.
