### ISSUE TITLE
Git pull resets amplify-meta.json

### ISSUE THREAD

**Issue by fatjoni** [aws-amplify/amplify-cli#1673]
**Describe the bug**
I have 2 envs, namely prod and dev. While i work in dev i type amplify status and no change is reported in any of the services.  Then i type amplify push and it confirms that no change is needed. when i press then later amplify env pull the amplify-meta.json is resetted and i have to copy the content from #current-cloud-backend in order to reverse the resetting of services.

The error that i receive then is as following:
× There was an error initializing your environment.
2019-06-16T18:00:02.274Z - error: uncaughtException: Cannot read property 'DeploymentBucketName' of undefined 

**To Reproduce**
1. amplify push
2. amplify env pull

**Expected behavior**
In this case it should report as git, that the env is up to date

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by UnleashedMind** [comment]
@fatjoni 

What is the version of your locally installed amplify CLI?

**Comment by kaustavghosh06** [comment]
@fatjoni You could use `amplify env pull --restore` to copy the #current-cloud-backend to backend.

**Comment by MontoyaAndres** [comment]
I got the same error when I try to get an environment from amplify (AWS services) to my local machine...
