### ISSUE TITLE
Add DynamoDB generated by API to amplify-meta.json

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1675]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to access the DynamoDB generated by `amplify add api` in a Lambda function.

**Describe the solution you'd like**
Add the DynamoDB's ARN, name etc. to `amplify-meta.json`. Then we could access it using environment variables.

**Describe alternatives you've considered**
In the second issue mentioned for additional context, I wrote done a manual workaround, which comes a potential security risk (secret key in repository).

**Additional context**
It would also be cool, if you could add the DynamoDB via `amplify update/add function` (see [this issue](https://github.com/aws-amplify/amplify-cli/issues/689) and [this issue](https://github.com/aws-amplify/amplify-cli/issues/997)).

*PS:*
Same goes for accessing the [AppSync backend (for mutations and queries)](https://github.com/aws-amplify/amplify-cli/issues/1678).

**Comment by UnleashedMind** [comment]
Thanks @janhesters for your feedbacks, our team will review the feature request and respond to you soon.

**Comment by kaustavghosh06** [comment]
@janhesters You can still access the DynamoDB table ARN's etc which you create as a part of your Amplify porject. I'm failing to understand the request out here.

**Comment by janhesters** [comment]
@kaustavghosh06 If you could tell me how, I would be very grateful 🙏🏻

As far as I'm concerned `amplify add/update function` neither gives you access to your DynamoDB created with `amplify add api` nor does it give you rights to do queries or mutations on your AppSync API.

My goal is to have a save way to access one of the two because I'd like to modify the database of my GraphQL API using Lambda functios. Safe meaning for example through environment variables.

**Comment by babu-upcomer** [comment]
@kaustavghosh06 Any update? What if I want to run a scheduled task using a `amplify add function` to populate one of the table created from schema using `amplify add api`?

**Comment by kaustavghosh06** [comment]
Hey guys, we do support this and expose the DDB tables generated by the GraphQL transformer to other categories now as a part of the latest CLI - v 4.16.1
Please take a look at - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation for more info
