### ISSUE TITLE
Amplify Console build issue.  Missing Asset files

### ISSUE THREAD

**Issue by DavidNelsonCordelia** [aws-amplify/amplify-cli#1677]
**Describe the bug**
I am missing some static files added to my web site when using the amplify console.   A normal build includes the files.  

**To Reproduce**
1. push new code into git
2. Wait for the site to be completly built
**Expected behavior**
1. look in the artifcacts download for the folder ".well-known/" with a single file in it.   No file is found

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]   windows
 - Browser [e.g. chrome, safari] chrome

**Additional context**
I am using angular 7 and it is what copies the static files  via 

 "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              { "glob": "**/*", "input": "src/.well-known/", "output": "/.well-known/" },  <--  this folder is missing
              "src/assets",
              "src/spreadsheets",
              "src/favicon.ico"
            ],
            "styles": [
              "src/scss/styles.scss"
            ],
            "scripts": []
          },

**Comment by UnleashedMind** [comment]
transfer issue to Amplify Console

**Comment by garyleefight** [comment]
Can you share your buildSpec file?

**Comment by garyleefight** [comment]
I doubt you have to change the output to /build/.well-known

version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

You have to ensure the assets folder is under the baseDirectory (in this case /build)

@DavidNelsonCordelia

**Comment by garyleefight** [comment]
We exclude . files by default. You have to add the full path of the asset file under the paths. eg. you have to change the files path to

files:
- '**/*'
- '.well-known/assetlinks.json'
