### ISSUE TITLE
S3 location not valid for DefinitionS3Location

### ISSUE THREAD

**Issue by dennyferra** [aws-amplify/amplify-cli#168]
**Describe the bug**
Using `amplify push` to create GraphQL API results in error in CloudFormation:

22:11:21 UTC-0700 | CREATE_FAILED | AWS::AppSync::GraphQLSchema | GraphQLSchema | S3 location not valid for DefinitionS3Location

Amplify 0.1.19

In my cloudformation script I see:
```
DefinitionS3Location": {
  "Ref": "schemaGraphql"
}
```
schemaGraphql: 
```
s3://revtmfront-20180911220914-deployment\amplify-appsync-files\schema.graphql.1536901715917
```

(Verified the file does exist)

**To Reproduce**
1. Add GraphQL API
2. Customize schema
3. Push

**Expected behavior**
API is created and no cloudformation error

**Desktop (please complete the following information):**
 - OS: Windows 10 with WSL

**Comment by hagiosofori** [comment]
Been experiencing the same thing for the past week. +1

**Comment by minhlong** [comment]
The same thing happened with me

**Comment by hagiosofori** [comment]
might it have anything to do with this..? https://github.com/aws/aws-cli/issues/3394

**Comment by thanhpd56** [comment]
Me too.
![image](https://user-images.githubusercontent.com/3794898/45726325-e2ff7780-bbe8-11e8-82a5-f6ba116e2a8e.png)

**Comment by kaustavghosh06** [comment]
Hey guys, are you all using windows?

**Comment by thanhpd56** [comment]
@kaustavghosh06 Yes, i'm using windows 10 build 17134.285.

**Comment by minhlong** [comment]
Hi @kaustavghosh06 
I am using

- Window 7
- aws-cli/1.16.16 Python/3.6.4 Windows/7 botocore/1.12.6
- amplify 0.1.19

Thanks so much,

**Comment by hagiosofori** [comment]
yhup.. using Windows 10 build 17134.285

**Comment by kaustavghosh06** [comment]
@dennyferra This seems like a  bug. Are you using WSL or native windows?

**Comment by dennyferra** [comment]
No longer an issue. I thought I was using WSL but I had misconfigured my default console in Cmder/ConEmu.

If it saves anyone else trouble: (Cmder/ConEmu) Settings > Startup > Tasks > Commands:
`%windir%\system32\bash.exe ~ -cur_console:p`

Additionally, I had to uninstall node/npm and reinstall in WSJ since my global packages were a mess.

**Comment by hagiosofori** [comment]
@dennyferra @kaustavghosh06  it only works in Linux?

**Comment by danilofuchs** [comment]
Still an issue for me on Windows. 
`{
"schemaGraphql":
"s3://projectname-20180923124713-deployment\\amplify-appsync-files\\schema.graphql.123456789"
}`
The slashes are clearly inverted.
Not using WSL

**Comment by kaustavghosh06** [comment]
Provided a fix for it to make it work natively on windows - https://github.com/aws-amplify/amplify-cli/pull/212
