### ISSUE TITLE
Amplify push with API do nothing

### ISSUE THREAD

**Issue by Qlenglet** [aws-amplify/amplify-cli#1685]
Hello,

I have a weird bug which is very frustrating for me and it break all my project. The issue is happening when I try to override the file 'schema.graphql'.
I am using Angular 8.
Each modification on this file is not taken when I launch the command amplify push. And the amplify cli see the modification but use the old file instead.

Amplify cli version :  1.7.3
Amplify installed on Angular: 1.1.28
Amplify angular installed: 3.0.3

Thanks for your help

**Comment by UnleashedMind** [comment]
Hi @Qlenglet 

Sorry to hear your frustration, what's the full path to the file `schema.graphql` that you modified? 

The file that will update your schema is `<your-project-root>/amplify/backend/api/<api-name>/schema.graphql`.

**Comment by Qlenglet** [comment]
It was a mistake from me. I closed this post since It's my mistake

Thanks
