### ISSUE TITLE
Expected scalar and got X

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1686]
Is there a way I can group my results based on a custom scalar?

```
type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}

type Schedule
  @model
  @key(name: "ByGroup", fields: ["group"], queryField: "schedulesByGroup")
{
  id: ID!
  recipe: Recipe! @connection
  group: Group!
  cookdate: AWSDateTime
  timestamp: AWSDateTime
}
```

What I like to query is "Give me all the schedules for group X"
But when I setup like the schema above I get an error saying: `Expected scalar and got Group`

**Comment by mikeparisstuff** [comment]
@sprucify The `@key` directive can only create indexes on top of scalar fields. If you want to index such that you can lookup resources by the logical then you can add a field `groupId: ID!` and then index on that.

**Comment by luizdanieldesouza** [comment]
Thanks Mike. How can @key be applied to '@connection' field. Example:

`type Content @model 
@key(name: "BySite", fields: ["site", "status"], queryField: "itemsBySite")
{
	id: ID!
	name: String!
	site: Site! @connection(name: "SiteProjects")
	status: Status!
}

enum Status {
	ACTIVE
	DELETED
}`

**Comment by sprucify** [comment]
I changed my structure as recommended, but this results in a rollback:

```
type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}

type Schedule
  @model
  @key(name: "ByGroup", fields: ["groupId"], queryField: "schedulesByGroup")
{
  id: ID!
  recipe: Recipe! @connection
  groupId: ID!
  cookdate: AWSDateTime
  timestamp: AWSDateTime
}
```

The error in the log: 
```
 One or more parameter values were invalid: Both ReadCapacityUnits and WriteCapacityUnits must be specified for index: ByGroup (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: *)
```

**Comment by sprucify** [comment]
I created a new issue for this #1714

**Comment by avlonder** [comment]
> @sprucify The `@key` directive can only create indexes on top of scalar fields. If you want to index such that you can lookup resources by the logical then you can add a field `groupId: ID!` and then index on that.

Is there a specific reason for this? Why, for example, can't we use @key(name: "byProductByStatus", fields: ["id", "status"]) where the status attribute is an enum instead of a scalar type?

**Comment by abrahamAlonzo** [comment]
@avlonder You can already do that https://docs.amplify.aws/cli/graphql-transformer/directives#key

**Comment by abrahamAlonzo** [comment]
i don't have this problem when a try to use the same schema in a new project :/

```
type Order @model
  @key(fields: ["id",  "status", "ownerId", "distributorCenterId"])
  @key(name: "byOwnerIdAndStatus", fields: ["ownerId"], queryField: "orderByStatus")
  @key(name: "byDistributorCenterIdAndStatus", fields: ["distributorCenterId"], queryField: "orderByDistrbutorAndStatus")
  @key(name: "byUserId", fields: ["distributorCenterId", "ownerId"], queryField: "orderByUser") {
  id: ID!
  ownerId: ID!
  distributorCenterId: ID!
  status: StatusOrder!
  comment: String
  createdAt: String
  distributorName: String
  imageUrlClient: String
  imageUrlDistrubutor: String
  ownerIdTest: String
  products: [Product]
  totalNumberOfProducts: Int
  totalPrice: Float
  updatedAt: String
}

type User @model {
  id: ID!
  city: String
  colony: String
  comments: [Comment]
  country: String
  createdAt: String
  distributorCenterId: ID!
  email: String
  externalNumber: String
  firstLastName: String
  firstName: String
  interiorNumber: String
  isActive: Boolean
  likes: [Like]
  orders: [Order] @connection(keyName: "byUserId", fields: ["id"])
  phone: String
  postalCode: String
  role: Roles
  secondLastName: String
  state: String
  street: String
  updatedAt: String
  username: String
}
```

**Comment by djsmedes** [comment]
Especially because you CAN use enums as part of composite sort keys by doing something like `@key(name: "byProductByStatus", fields: ["id", "status", "createdAt"])`. They're all just strings to Dynamo.
