### ISSUE TITLE
MacOS Mojave - Stuck at Amplify Configure Command

### ISSUE THREAD

**Issue by jynxdzn** [aws-amplify/amplify-cli#1694]
I've installed @aws-amplify/cli using node 8.12.0 and the installation was successful but when I run ```amplify configure``` my terminal freezes up at the prompt to name my IAM user. Normally it would redirect my browser to the IAM User page with the pre-filled inputs but instead nothing happens and I have to kill my node process. 

 - OS: macOS Mojave (10.14.4)
 - Browser: Google Chrome (75.0.3770.100 64-bit)

**Comment by UnleashedMind** [comment]
this is a duplicate issue to this #1688 
the fix has been merged and it's being released to production at this moment.
