### ISSUE TITLE
Passing cognito user pool web client id to lambda functions

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#1695]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
Feature: https://github.com/aws-amplify/amplify-cli/issues/1099 enabled us to pass some parameters (like region, graphqlid and cognito user pool id) to lambda functions (great work BTW), however, for being able to use Amplify inside a lambda function like we do in the frontend we still need the param: `aws_user_pools_web_client_id` found on the aws-exports file that we pass to Amplify to configure it (Amplify.configure(aws_exports)).

**Describe the solution you'd like**
pass the `aws_user_pools_web_client_id` param to lambda functions.

**Comment by jkeys-ecg-nmsu** [comment]
It would be nice if there was a Secrets category that would simplify the process of creating a new Secret in Secrets Manager and generate the code for the Functions category to decrypt that secret. But otherwise it's pretty simple to create a new secret, decrypt it from lambda, and go without much heartburn. I'll send you some sample code when I'm free of curr obligations.

**Comment by damianrr** [comment]
Thanks for your response @jkeys-ecg-nmsu. As I said in the other thread that you responded, my issue is that when I post a query to the GraphQL endpoint I don't know what would actually be the credentials that I need to pass (nor where to get them from) since in Amplify I just do: `Amplify.configure(aws_exports)` and that handles any required authentication and everything else.

**Comment by aprilmintacpineda** [comment]
I'm currently having this issue too. I have a lambda function using NodeJS. When it runs, it should insert a data into a dynamo db and I'm using aws appsync with graphql to do that instead of directly connecting to dynamo db.

I have to login with cognito to get access token and use that access token to make graphql queries (using graphql-request).

**Sample code**

```js
```

**Comment by SebSchwartz** [comment]
Another possible workaround is to put it inside **team-provider-info.json**:
```json
"categories": {
            "auth": {
                
            },
            "function": {
                "fonctionWithWebId": {
                    "userPoolWebClientId": "Your web client Id hardcoded",
                },
                "function2": {},
            }
        }
```
You can put it for every environement. You just needs to be careful when doing amplify init because it wipes the values sometimes. It doesn't change it when doing amplify env checkout.

To get it inside the function, you have to put inside **amplify/backend/function/fonctionWithWebId/fonctionWithWebId-cloudformation-template.json**:
```json
"Parameters": {
		"env": {
			"Type": "String"
		},
		"userPoolWebClientId": {
			"Type": "String",
			"Default": "userPoolWebClientId"
		},
}
...

"Resources": {
		"LambdaFunction": {
			...
			},
			"Properties": {
				...
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"AUTH_USERPOOL_WEB_CLIENT_ID": {
							"Ref": "userPoolWebClientId"
						}
					}
				},
....

```

**Comment by rehanbabertkxel** [comment]
I am facing a similar issue. 
I am surprised that in order to configure Amplify in Lambda we need both the User Pool Id and the Client Id but we only get User Pool Id in process.env. 
@SebSchwartz , adding it to the team-provider-info.json might expose it too.

**Comment by amuresia** [comment]
+1

**Comment by aprilmintacpineda** [comment]
And I ran into this issue again, this time when setting up the app in a CI/CD environment. The way I do it is by generating a `.env` file on the `src` of the function, and then using `dotenv` package to load it, the process depends on `aws-exports.js` which is not being committed to the repository, so it has to be generated before amplify push, but generating `aws-exports.js` on CI/CD is not as easy as generating it on your machine https://github.com/aws-amplify/amplify-cli/issues/3643 it would have been better if this was added into the environment by default just like the others variables.

**Comment by dan-danciu** [comment]
There might be an easier way (depending on your usecase):

Use IAM access.

make sure you add IAM access:
![image](https://user-images.githubusercontent.com/19431872/84203400-0c91be00-aab2-11ea-96ff-dbd8912dffb2.png)

Then in your schema add
`type MyType
  @model
  @aws_iam
  @aws_cognito_user_pools
  @auth(rules: [{ allow: private }, { allow: private, provider: iam }]) {
  etc: String!
}
`

Then follow the example in the amplify documentation here:
[Amplify Documentation](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda)

These lines = magic:
`
  const signer = new AWS.Signers.V4(gqlRequest, 'appsync', true)
  signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate())
`

**Comment by aprilmintacpineda** [comment]
My use case is creating a cognito user on a lambda function, which requires you to login to cognito with the pool id and web client id... any suggestions? pool id is already provided by amplify, but web client id is not, I'm unsure if there's a way to to get the web client id using the pool id.

**Comment by aprilmintacpineda** [comment]
Is anyone working on this at all? for me I'm using it for a lambda s3 trigger.

**Comment by MontoyaAndres** [comment]
I tried something like this; In the backend-config.json

```
"function": {
    "saveUser": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "ecommerceprojectcxxxxxxxxxx9f",
          "attributes": [
            "UserPoolId",
            "AppClientIDWeb" // This is the new value
          ]
        },
        {
          "category": "api",
          "resourceName": "ecommerceproject",
          "attributes": [
            "GraphQLAPIIdOutput"
          ]
        }
      ]
    }
  }
```

But I got this error:

```
UPDATE_FAILED               functionsaveUser                        AWS::CloudFormation::Stack Mon Aug 23 2021 17:35:49 GMT-0500 (Colombia Standard Time) Parameters: [authecommerceprojectc552709fc552709fAppClientIDWeb] do not exist in the template
```

How can we get this value from a lambda?

**Comment by MontoyaAndres** [comment]
I could fix it! It is a solution TOO manual but works great :).

First, in the `backend-config.json`, in your lambda function, you will add the `AppClientIDWeb` as an attribute, like this:

```
"function": {
    "saveUser": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "ecommerceprojectc552709fc552709f",
          "attributes": [
            "UserPoolId",
            "AppClientIDWeb" // new value, to get the cliend id of the UserPoolClientWeb
          ]
        },
        {
          "category": "api",
          "resourceName": "ecommerceproject",
          "attributes": [
            "GraphQLAPIIdOutput"
          ]
        }
      ]
    }
  }
```
Then, there's something hidden, if you do `cat amplify/backend/awscloudformation/nested-cloudformation-stack.yml` (Cat is a command from Linux), you will see the main stack, and this one has something interesting about our function:

```
"functionsaveUser": {
      "Type": "AWS::CloudFormation::Stack",
      "Properties": {
        "TemplateURL": "https://s3.amazonaws.com/amplify-ecommerceproject-develop-100856-deployment/amplify-cfn-templates/function/saveUser-cloudformation-template.json",
        "Parameters": {
          "deploymentBucketName": "amplify-ecommerceproject-develop-100856-deployment",
          "s3Key": "amplify-builds/saveUser-37524363594431644b31-build.zip",
          "authecommerceprojectc552709fc552709fUserPoolId": {
            "Fn::GetAtt": [
              "authecommerceprojectc552709fc552709f",
              "Outputs.UserPoolId"
            ]
          },
          "authecommerceprojectc552709fc552709fAppClientIDWeb": { // here's the value we need!!!!!!
            "Fn::GetAtt": [
              "authecommerceprojectc552709fc552709f", // This is the auth I created with `amplify add auth`
              "Outputs.AppClientIDWeb"
            ]
          },
          "apiecommerceprojectGraphQLAPIIdOutput": {
            "Fn::GetAtt": [
              "apiecommerceproject",
              "Outputs.GraphQLAPIIdOutput"
            ]
          },
          "env": "develop"
        }
      }
    },
```

So, we go to the stack of our function and add as a parameter:

```
"authecommerceprojectc552709fc552709fAppClientIDWeb": { // In my case is named like this, because the Auth stack was created like this
      "Type": "String",
      "Default": "authecommerceprojectc552709fc552709fAppClientIDWeb"
    }
```

There we go :). We can add it as an environment variable now:

```
"Environment": {
      "Variables": {
           ...,
           "AUTH_ECOMMERCEPROJECTC552709FC552709F_APPCLIENTIDWEB": {
              "Ref": "authecommerceprojectc552709fc552709fAppClientIDWeb"
            }
      }
}
```
