### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by RickCraig** [aws-amplify/amplify-cli#1699]
**Describe the bug**
I am getting the following error when trying to push:
```
Maximum policy size of 10240 bytes exceeded for role sussd-20190224131557-authRole (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: 5137ecee-941e-11e9-8ab3-8d65e5cd294e)
```
I have manually added permissions to allow me access to the VPC that has my Aurora Serverless database on it as follows (VpcConfig & ec2 actions) everything else is generated by amplify:

```
{
  ...
  "Resources": {
    "LambdaFunction": {
      ...
      "Properties": {
        ...
        "VpcConfig": {
          "SecurityGroupIds": [
            "sg-xxxxxxxx"
          ],
          "SubnetIds": [
            "subnet-xxxxxxxx",
            "subnet-xxxxxxxx",
            "subnet-xxxxxxxx"
          ]
        },
        ...
      }
    },
    "LambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        ...
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  {
                    "Ref": "AWS::StackName"
                  },
                  "UseDBPolicy"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "ec2:CreateNetworkInterface",
                    "ec2:DescribeNetworkInterfaces",
                    "ec2:DetachNetworkInterface",
                    "ec2:DeleteNetworkInterface"
                  ],
                  "Resource": "*"
                }
              ]
            }
          }
        ]
      }
    },
    ...
  },
  ...
}
```

I currently have 21 functions on the go, 12 of which have these permissions added. I can get away with ~13 functions before the policy limit is exceeded. I have the functions split over 5 API Gateways reasonably evenly (3 - 4 endpoints on each).

**Expected behavior**
Be able to push to AWS without exceeding policy character limits.

**Desktop:**
 - OS: Mac
 - Version: 10.14

**Thoughts:**
After a quick read I see that a few people had this issue with serverless, and serverless implemented this: https://github.com/serverless/serverless/pull/6212, is there anyway to do something similar?

**Comment by kaustavghosh06** [comment]
@RickCraig The policy limit seems to be from the IAM and yeah the solution you mentioned isn't ideal. I would opening up a support ticket with IAM out here - https://forums.aws.amazon.com/forum.jspa?forumID=76

**Comment by ziggy6792** [comment]
Hi guys. Check out my blog post which explains this issue and how to work around it by modifying your amplify cloud formation templates. https://ziggy6792.github.io/posts/amplify-lambda-dynamodb/#potential-maximum-policy-size-issue-when-running-amplify-push
