### ISSUE TITLE
amplify notifications add fails

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#17]
Do you want to request a feature or report a bug?
- bug

What is the current behavior?
- cannot add apns notifications

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
- I should be able to add apns notifications

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?

Latest version of cli.

commands used:
`amplify notifications add`

Logs:
```
➜  NotesAppWithPushNotifications git:(master) ✗ amplify notifications add
? Choose the push notification channel to enable. APNS
Successfully created Pinpoint app: NotesPushNotif
? Choose authentication method used for APNs Certificate
? The certificate file path (.p12):  Certificate.p12
? The certificate password (if any):
MAC verified OK
update channel error
2018-08-25T00:04:58.136Z - error: uncaughtException: Missing credentials
```

**Comment by UnleashedMind** [comment]
can you use the same .p12 file to enable APNS channel on the Pinpoint console?

**Comment by rohandubal** [comment]
I haven't tried that, but I was following the instructions mentioned in the doc. I can try it out later once I get a chance. Also, the error didn't give me much details on what I can correct.

**Comment by kaustavghosh06** [comment]
Should be fixed with the latest npm publish.
