### ISSUE TITLE
amplify auth add - no option to choose "Email address or phone number" vs "Username" 

### ISSUE THREAD

**Issue by pronevich** [aws-amplify/amplify-cli#170]
**Is your feature request related to a problem? Please describe.**
When creating cognito user pool with cli, it's automatically set Username as Sign In option. After pool was created, changes in aws website UI - restricted.

 

![image](https://user-images.githubusercontent.com/680439/45556323-a546cb80-b843-11e8-8229-897906f21b0d.png)

**Comment by haverchuck** [comment]
This is duplicate:

https://github.com/aws-amplify/amplify-cli/issues/102

**Comment by haverchuck** [comment]
#102
