### ISSUE TITLE
Aggregation operation on DynamoDB+ElasticSearch

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#1706]
** Which Category is your question related to? **
GraphQL API

** What AWS Services are you utilizing? **
AppSync, DynamoDB, ElasticSearch

** Provide additional details e.g. code snippets **
Let's assume I have defined the model in my Amplify app:

```graphql
type Item @model @searchable {
  id: ID!
  inventoryType: String!
  itemName: String!
  price: Int
}
```
I want to do things like:
```sql
SELECT DISTINCT(inventoryType) FROM Item;
SELECT SUM(price) FROM Item;
SELECT SUM(price) FROM Item WHERE inventoryType="xxx";
```
As they are complex query, I want to utilize ElasticSearch. The graphql query generated by `amplify codegen` is:
```js
export const searchItems = `query SearchItems(
  $filter: SearchableItemFilterInput
  $sort: SearchableItemSortInput
  $limit: Int
  $nextToken: Int
) {
  searchItems(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      inventoryType
      itemName
      price
    }
    nextToken
  }
}
`;
```
My questions are:
- Can I do the above operations by utilizing the generated query? 
- If yes, what are the queries (`filter`) look like? 
- If not, what is the right way to achieve this?

**Comment by krsnaa** [comment]
This seems like this is a valid questions re: aggregations on the GQL API. My guess is that it will require a custom VTL script. An official response/code-snippet would be appreciated.

**Comment by dtelaroli** [comment]
+1

**Comment by jasontll** [comment]
I have similar need to do aggregation on the Elasticsearch, currently I am hitting the Elasticsearch instance directly but it is not ideal as there's no way to securely query the ES instance without much modification. Anyone has any idea or workaround for this?

**Comment by Graig123git** [comment]
@jasontll can you not hit elasticsearch from AppSync if you are using it

**Comment by evrardts** [comment]
+1

**Comment by jasontll** [comment]
> @jasontll can you not hit elasticsearch from AppSync if you are using it

I am doing aggregation, there's no proper way to do it via Appsync GraphQL interface.

**Comment by renebrandel** [comment]
Hi folks - we're planning on addressing this as part of our new GraphQL transformer. The approach is captured here in our RFC: https://github.com/aws-amplify/amplify-cli/issues/7546 love to hear your feedback!

**Comment by renebrandel** [comment]
Feature is live! https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#aggregate-values-for-search-result-minimum-maximum-average-sum-terms
