### ISSUE TITLE
Get graphql id

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1707]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
lambda function
** What AWS Services are you utilizing? **
 aws lambda 
** Provide additional details e.g. code snippets **
 I want to access graphql Id, to generate dynamodb table names and i don't want to give lambda permission to acess appsync. How to do that. Thanks

**Comment by kaustavghosh06** [comment]
@achutkiran We don't support this out of the box in the CLI since this is not a common scenario. but at the same time you can update your cloudformation file located in `amplify/backend/function/<function-name>` to remove the Policies that you don't require.

**Comment by achutkiran** [comment]
Ok sure thanks
