### ISSUE TITLE
Guidance for managing a parallel Cloudformation/SAM stack.

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#1709]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
N/A

** What AWS Services are you utilizing? **
Auth, API, Analytics, Storage

** Provide additional details e.g. code snippets **
Alongside Amplify, we are using a SAM template to build databases, lambdas, sqs, etc. These resources interact with Amplify resources (eg. a lambda function might call the AppSync API created by Amplify). It would be nice to hook the SAM/Cloudformation deployments into the same commands that amplify uses (eg. amplify push would run sam deploy). There doesn't appear to be a documented way to do this.

Also, we're having a hard time pointing our cloudformation templates to Amplify-generated resources because there are randomly generated strings in addition to the env variables (eg. the DynamoDB table is named `SomeTable-obhasdofhawnosaf-dev` for our dev environment). It's unclear where this token is coming from and if Amplify exports it anywhere.

SAM makes simple to drop down to Cloudformation, does Amplify provide the same escape-hatch or hooks down to SAM or CloudFormation for custom resources?

**Comment by UnleashedMind** [comment]
@ajhool 
Thanks for the feedback, I will mark this as a feature request and put it in our backlog.

**Comment by kaustavghosh06** [comment]
@ajhool You can take a look at https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916 for adding custom cloudformation stacks to your project.
We're soon going to be adding official documentation for this as well.
Also, we merged this PR - #1763 sometime back, which would allow you to modify your function CFN file to a SAM file if need be, and then allow you to upload it to deploy it seamlessly via the Amplify CLI. This will be part of our next CLI release.

**Comment by kaustavghosh06** [comment]
@ajhool Please take a look at https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks to know more about custom Cloudformation stacks and the latest version of the CLI allows deploying of SAM CFN templates.
