### ISSUE TITLE
Restrict resolver creation during amplify push

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#1712]
** Which Category is your question related to? **
amplify push

** What AWS Services are you utilizing? **
appsync

** Provide additional details e.g. code snippets **
I have a type as mentioned below in which I do not need resolver template(both req and res) against each connection type country, trait, createdBy, updatedBy and variety

![issue](https://user-images.githubusercontent.com/51752377/59963242-e58f5480-950d-11e9-81a1-531129724365.jpg)

```
type VarietyProfile @model {
	profileId: ID!
	year: String
	country: MasterLocation @connection(keyField: "locationId")
	trait: MasterTrait @connection(keyField: "traitId")
	score: String
	note: String
	createdBy: UserMain @connection(keyField: "createdUserId")
	updatedBy: UserMain @connection(keyField: "updatedUserId")
	createdAt: String
	updatedAt: String
	variety: VarietyMain @connection(keyField: "varId")
}
```
How this could be done during amplify push?

**Comment by jkeys-ecg-nmsu** [comment]
If you don't need a foreign key between a field and another model's ID field, you should omit the connection directive. Is that what you mean? (What is the point of protecting it behind a connection directive and then deleting the resolver generated for that connection?)

**Comment by meetrij** [comment]
During data listing I need connected tables data and in mutation I need to insert that foreign key id into db. If I omit then it would not be in mutation correct? which would result in error at front end. Instead of DynamoDB I am connecting with Postgres. So in 'ListVarietyProfiles' getting all the data by joining different tables and no longer resolver template needed

**Comment by attilah** [comment]
@meetrij currently the ```@model``` directive does not support this, but for this level of customizability you could implement ```VarietyProfile``` without the directive and create your own mutations and resolvers where needed as custom resources.

Would that solve your problem?

**Comment by meetrij** [comment]
Thanks for the solution @attilah but that I can do, just wanted to know whether from <apllication-name>/resolvers/<templates> can I do anything?

**Comment by attilah** [comment]
No you cannot do it currently.

I'm closing this issue now, if you've further questions regarding this, please feel to reopen it at a later time.
