### ISSUE TITLE
Both ReadCapacityUnits and WriteCapacityUnits must be specified for index

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1714]
I wanted to make a datastructure to request GetSchedulesByGroup
I did this on other models before and that worked perfectly.
But on this Model I get error:

 `One or more parameter values were invalid: Both ReadCapacityUnits and WriteCapacityUnits must be specified for index: ByGroup (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: *)` and then it rolls back the deploy.

```
type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}

type Schedule
  @model
  @key(name: "ByGroup", fields: ["groupId"], queryField: "schedulesByGroup")
{
  id: ID!
  recipe: Recipe! @connection
  groupId: ID!
  cookdate: AWSDateTime
  timestamp: AWSDateTime
}
```

Does it have to do with capacity settings of the table Schedules?

amplify-cli 1.7.5

**Comment by mikeparisstuff** [comment]
Hey, the behavior for GSI throughput provisioning sits behind a condition that depends on the value of the 'DynamoDBBillingMode' key in `parameters.json`. To help track this down can you tell me if you see a value for the key `DynamoDBBillingMode` in your `parameters.json`?

**Comment by sprucify** [comment]
Yes I have `PAY_PER_REQUEST` set in parameters.json
When I set my table on `On demand` scaling in my AWS panel, the `amplify push` succeeded.
