### ISSUE TITLE
Parameters: [googleClientId] must have values

### ISSUE THREAD

**Issue by calspre** [aws-amplify/amplify-cli#1719]
**Describe the bug**
Could not deploy to the Amplify console when I `amplify update auth` and:
```
What do you want to do? Walkthrough all the auth configurations
...
Do you want to enable 3rd party authentication providers in your identity pool? Yes
```

**To Reproduce**
1. `amplify update auth`
2. `What do you want to do? Walkthrough all the auth configurations`
3. `Do you want to enable 3rd party authentication providers in your identity pool? Yes`
4. Finish the configuration process and `amplify push`
5. Commit changes which kick off a new build in Amplify console.
6. Build fails with this error `Parameters: [googleClientId] must have values`

**Expected behavior**
Should build.

**Additional context**
I am using google oAuth and amplify 1.7.5.

**Comment by attilah** [comment]
@calspre Could you please share the initial steps you used for configuring the auth category, to make it easier to reproduce?

**Comment by calspre** [comment]
@attilah As far as I remember I used the preconfigured one with social providers:

```
Do you want to use the default authentication and security configuration? 
Default configuration with Social Provider (Federation)

How do you want users to be able to sign in when using your Cognito User Pool?
Email and Phone Number

What attributes are required for signing up?
Email

...

Select the social providers you want to configure for your user pool
Google
```

I can't be certain but I *think* I followed the above steps.

As for the manual configuration, once I select 'no' for the question 'do you want to enable 3rd party authentication providers in your identity pool?' Everything worked the same as before.

**Comment by kaustavghosh06** [comment]
@calspre Do you check in your team-provider-info file into your git repo which is hooked up to the Amplify console?
Also, are you re-using the same backend that you generated using the CLI locally or did you create a new environment via the Amplify console?

**Comment by calspre** [comment]
Hi @kaustavghosh06 thanks for the follow-up.

> Do you check in your team-provider-info file into your git repo [...]

I am not sure what you mean by "check in".

> Also, are you re-using the same backend [...}

Hmm, I didn't know you could create a new environment via the Amplify console. I generally push code to the GitHub repo which is hooked up to the Amplify console, which then kicks off a new build. I have two branches (`dev`, `master`) that are connected to the Amplify console (`dev.site.amplifyapp.com`, `master.site.amplifyapp.com`) I guess I am "re-using the same backend" in this case.

One thing I did (I am not sure if this is related) was setting a new Amplify console project twice because I couldn't change the GitHub repo it was connected to. In other words: 

- I set up a repository called 'foo' linked to Amplify project 'A' 
- Then I restarted a repo called 'bar' linked to Amplify project 'B'
- Both projects use the same backend generated by Amplify CLI
- Amplify project 'A' is now outdated but not deleted yet

I thought this issue was related to that specific scaffolding question ('do you want to enable 3rd party authentication providers in your identity pool?'), but do you think I did something different that causes this error?

**Comment by kaustavghosh06** [comment]
@calspre The googleClientId should be a part of the `team-provider-info.json` file if that's checked into git and the CLI picks it up from there. Can you check your `team-provider-info` to check if you have the googleClientId out there?

**Comment by calspre** [comment]
@kaustavghosh06 Ah, yes. I tried with the `dev` branch again and but the build failed nonetheless. I can confirm `googleClientId` is included:

<img width="952" alt="Screenshot of Google Chrome (12-07-2019, 16-46-00)" src="https://user-images.githubusercontent.com/29621109/61111443-8b5a3180-a4c4-11e9-9cbf-19431f324fe8.png">

**Comment by kaustavghosh06** [comment]
@calspre Were you able to diagnose/reproduce the issue? Our team wasn't able to reproduce this in the last couple of weeks.

**Comment by calspre** [comment]
@kaustavghosh06 I no longer use amplify so I can't tell if this issue persists. If no one else reported a similar issue you can close this -- I probably did something wrong.
