### ISSUE TITLE
Invalid GraphQL type names are generated for @key when name contains dashes or other characters

### ISSUE THREAD

**Issue by dantonijevic** [aws-amplify/amplify-cli#1720]
**Which Category is your question related to?**

GraphQL API

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

 I am using this newly introduced @key directive when creating my scheme. Currently I have a scheme with primary and one GSI. It looks like this

```
type Item @model
  @key(fields: ["id", "version"])
  @key(name: "type-subtype", fields: ["type", "subtype"])
{
  id: ID!
  version: String!
  type: String!
  subtype: String!
}
```

I want to change GSI defined here to be:

```
@key(name: "version-type-subtype", fields: ["version", "type", "subtype"])
```
 but I am getting `Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.` error when trying to push.

Can someone help? Is there any constraint using sort key from primary index as hash in GSI that I am not aware of?

Thanks

**Comment by attilah** [comment]
@dantonijevic just to confirm, do you've ```fileds``` or ```fields``` in your schema?, since that typo could make the schema invalid.

**Comment by dantonijevic** [comment]
@attilah Yeah, typo is just in a post, not in actual code.

**Comment by attilah** [comment]
@dantonijevic thanks for confirming it, we will look into it then.

**Comment by mikeparisstuff** [comment]
@dantonijevic It is not possible to edit an existing GSI. To make this work, you should create a new `@key` on the updated fields and then remove the existing `@key`. There is a note about this here https://aws-amplify.github.io/docs/cli/graphql#evolving-apis-with-key

**Comment by dantonijevic** [comment]
@mikeparisstuff Thank you for the response.

I actually tried with a fresh AppSync project and tried to define a GSI with 3 fields which got me the same error as above. I created a repo to demonstrate - [here](https://github.com/dantonijevic/amplify-GSI-test/blob/master/amplify/backend/api/keys/schema.graphql) is the schema I am trying to push where the current DynamoDB table deployed has `type-subtype` GSI defined together with the primary index `(id, version)`. 

<img width="1266" alt="Screenshot 2019-07-01 at 20 26 40" src="https://user-images.githubusercontent.com/3730543/60459138-9c8f7c80-9c40-11e9-83b2-056bd0cb5f7e.png">

So, with this push I was expecting this third index `version-type-subtype` to be deployed but no luck.

Note that I am using`aws-amplify/cli@1.7.8`

**Comment by mikeparisstuff** [comment]
The issue appears to be with the dashes in your GSI names. I will record this as a bug and it will get picked up by a member of the team. In the meantime, you can get around this issue by removing the dashes in `name` argument passed to @key and instead use only GraphQL safe characters. E.G. use `@key(name: "VersionTypeSubtype")` instead of `@key(name: "version-type-subtype")`.

**Comment by dantonijevic** [comment]
Thanks! I am closing the issue.
