### ISSUE TITLE
Support Node10 for AWS Lambda

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1721]
[Now that Node10 is available for Lambda functions](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/?nc1=h_ls), I was wondering whether there are any plans to support it? 😊 As far is I know, the Lambda functions generated by Amplify are in Node 8.

**Comment by attilah** [comment]
@janhesters you can update the node version of the generated function to be node 10 without problems.

Since node 10 is the current LTS version, I'll take the question to the team about changing default version of the generated lambda functions to 10 by default, thanks for raising this question.

**Comment by janhesters** [comment]
@attilah Thank you for the answer. I'll try that out. Feel free to close this issue, or to leave it open for the team 😊

**Comment by kaustavghosh06** [comment]
@janhesters We merged the PR (#1748 )which allows all the new lambda functions generated as a part of the functions category would now be Node 10 runtime. This will be a part of our next CLI release.

**Comment by janhesters** [comment]
@kaustavghosh06 Wow, great, thank you 😊
