### ISSUE TITLE
CircleCI Orbs for Amplify Deploys

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#1727]
## Problem
At the moment it is somewhat difficult and time consuming to leverage external CI systems like CircleCI to deploy Amplify code bases. 

The documentation makes references to [various scripts](https://aws-amplify.github.io/docs/cli/multienv#quick-tips) but doesn't really explain what they do or how to configure them.

## Request
I would like the ability to leverage [CircleCI orbs](https://circleci.com/orbs/) to handle deploys for AWS Amplify tooling. AWS already has various Orbs for the AWS CLI and AWS S3. This would open the tooling up to a wider audience and toolsets that are commonly used by developers.

Related Issue: https://github.com/aws-amplify/amplify-cli/issues/1322

**Comment by attilah** [comment]
@amcdnl since we've an ongoing discussion about better CI support at #1322 I'm closing this issue in favor of that one.
