### ISSUE TITLE
Access multiple Dynamodb tables from a single Lambda

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1737]
** Which Category is your question related to? **
Function and Storage.

** What AWS Services are you utilizing? **
Lambda and DynamoDB.

** Provide additional details e.g. code snippets **
How would you allow a function to use more than one dynamodb table? At the moment a role is created with access to dynamodb.

**Comment by kaustavghosh06** [comment]
Is the DynamoDB table part of the Amplify project which was created using `amplify add storage`?

**Comment by jarrettj** [comment]
I used the amplify api add. Then realized I don’t need all of that, api and function. Just the storage. The table just hold counters. So I update the counter via another function.


________________________________

**Comment by attilah** [comment]
@jarrettj Are you still stuck with this or you're good as you figured it out on your own?

**Comment by jarrettj** [comment]
I manually add the need CF template updates. It's obviously a hack, but it works. :) 
In my parameters.json:
```
"functionArn": "arn:aws:dynamodb:eu-west-1:****:table/function-develop"
```
In template.json:
```
{
							"Effect": "Allow",
							"Action": [
								"dynamodb:GetItem",
								"dynamodb:Query",
								"dynamodb:Scan",
								"dynamodb:PutItem",
								"dynamodb:UpdateItem",
								"dynamodb:DeleteItem"
							],
							"Resource": [
								{
									"Ref": "functionArn"
								}
							]
						}
```

What I would need is a way to pass a role that gets included in environments and updated accordingly by the cli. Will write up a better feature request.

**Comment by BrianBu01** [comment]
`"PolicyDocument": {
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"dynamodb:GetItem",
				"dynamodb:Query",
				"dynamodb:Scan"
			],
			"Resource": [
				{
					"Fn::Sub": [
						"arn:aws:dynamodb:${region}:${account}:table/${table}-${env}",
						{
							"region": {
								"Ref": "AWS::Region"
							},
							"account": {
								"Ref": "AWS::AccountId"
							},
							"table": "2ndTableNameHere",
							"env": {
								"Ref": "env"
							}
						}
					]
				}
			]
		}
	]
}`

still not ideal but a bit better than what you have.

**Comment by jarrettj** [comment]
I was indeed forced to do the same. Because I am using environment feature in amplify. Just forgot to update this post, thanks. :)
