### ISSUE TITLE
How to add appsync datasource to api that is already exist.

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1738]
#### problem
I generate environment as follows
```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | resource       | No Change    | awscloudformation |
| Auth     | resource       | No Change | awscloudformation |
| Storage  | resource       | No Change | awscloudformation |
```
I selected appsync and create DynamoDB table from GraphQL schema.
<img width="1278" alt="スクリーンショット 2019-06-27 17 50 12" src="https://user-images.githubusercontent.com/22259776/60251873-52d32900-9904-11e9-855d-284a0194e4d1.png">

Next, I want to add new datasource to api.
Searching in web, I had no idea.
What should I do ?

**Comment by attilah** [comment]
@yukitaka13-1110 in projects where the CLI is managing the resources for you, DataSources are always handled for you by the CLI, you do not need to manage them manually for the GraphQL schema types where you specified ```@model```. You have the ability to use custom resources and create new data sources or other type of resources, but I guess this is not relevant to your case.

Could you please tell us more about what are you trying to achieve? Perhaps share the schema what you currently have.

**Comment by yukitaka13-1110** [comment]
@attilah Thank you for quick response !
I want to create two DynamoDB tables by using graphql schema.
Now, I create DynamoDB table automatically by usign the shcema as follows

```graphql
type PanInfo @model @key(fields: ["category", "name"]) {
  category: String!
  name: String!
  price: String
  auther: String
}
```

I want to create another table. Can I create it if I define another type ?
Is there another way?

**Comment by kaustavghosh06** [comment]
Yes @yukitaka13-1110 You can create another type with the @model annotation.
Read more about it out here - https://aws-amplify.github.io/docs/cli/graphql#graphql-transform

**Comment by yukitaka13-1110** [comment]
@kaustavghosh06 Thank you so much !
