### ISSUE TITLE
not able to push because of [CAPABILITY_AUTO_EXPAND]

### ISSUE THREAD

**Issue by OukhouyaAyoub** [aws-amplify/amplify-cli#1740]
<img width="1142" alt="Screenshot 2019-06-27 at 13 50 12" src="https://user-images.githubusercontent.com/49235567/60265135-3ffd2c00-98e5-11e9-9ebb-eea9e2d8cad2.png">
I added functions, then I changed them to SAM serverless functions in the cloudformation template. When I tried to push the changes : create is failing (cf the picture attached) because of [CAPABILITY_AUTO_EXPAND] required.
Do you know how to check it via amplify cli ?

**Comment by attilah** [comment]
@OukhouyaAyoub If I understand your problem, what you need to do is add the ```Capabilities: CAPABILITY_AUTO_EXPAND``` to your Serverless parameters, so SAM will pass that to CloudFormation.

If I misunderstood your problem please share a repro project so we can look into it.

**Comment by OukhouyaAyoub** [comment]
@attilah 
amplify add function : then I change in the cloudformation template generated, to a AWS::Serverless:Function
When I : amplify push  Im getting the error shown in my previous screenshot
My question is how to pass this parameter or force it with amplify cli ? Thanks

**Comment by attilah** [comment]
@OukhouyaAyoub I think you cannot do that now, let me change this to a feature request and get back to the team to discuss it.

**Comment by kaustavghosh06** [comment]
@OukhouyaAyoub We added support for this as a part of #1763 PR and this will be part of our next CLI release.
