### ISSUE TITLE
How to do field level @auth for bi-directional one-to-many @connection?

### ISSUE THREAD

**Issue by ovidb** [aws-amplify/amplify-cli#1752]
**Which Category is your question related to?**
AppSync / GraphQL Transformer

**What AWS Services are you utilizing?**
AppSync / Dynamo
**Provide additional details e.g. code snippets**

I'm trying to figure out how can you protect a one-to-many `@connection` with `@auth` against mutations that shouldn't be allowed. (ie: deny a specific user to run a mutation that will end-up inserting posts as another user.)

Starting with your example for protecting a mutation I tried doing something like this:
```
type User @model @auth(rules: [{ allow: owner, ownerField: "id" }]) {
  id: ID!
  posts: [Post]
    @connection(name: "UserPosts")
    @auth(rules: [{ allow: owner, ownerField: "id" }])
}

type Post @model {
  title: String!
  user: User!
    @connection(name: "UserPosts")
    @auth(rules: [{ allow: owner, ownerField: "userPostId" }])
}
```
Then say there already is a user with an id of `regular-user-id`
Apparently my auth rules don't stop another user, say with id of: `malicious-user-id` to run this mutation:
```
mutation {
  createPost(input:{
    title:"Oh this is BAD!"
    postUserId: "regular-user-id"
  }) {
    title
  }
}
```
Running a simple query to make sure this really happened:
```
query {
  getUser(id:"regular-user-id"){
    posts{
      items
      {
        title
      }
    }
  }
}
=> 
{
  "data": {
    "getUser": {
      "posts": {
        "items": [
          {
            "title": "Regular User title"
          },
          {
            "title": "Oh this is BAD!"
          },
        ]
      }
    }
  }
}
```

I tried various ways to figure this one out and couldn't find any documentation about bi-directional field level authentication. I'm fairly new to AppSync so I think I must be not getting something, but then this is such common use-case scenario that I'm really surprised there isn't more documentation about it.

Some help would be really appreciated.

**Comment by UnleashedMind** [comment]
Hi @ovidb 
Change your schema to this and try again: 

```graphql
type User @model @auth(rules: [{ allow: owner, ownerField: "id" }]) {
  id: ID!
  posts: [Post] @connection(name: "UserPosts")
}
type Post @model @auth(rules: [{ allow: owner, ownerField: "postUserId" }]) {
  id: ID!
  user: User! @connection(name: "UserPosts")

  # This field is handled automatically by @connection
  # postUserId: String!
}
```
