### ISSUE TITLE
gluegun error (migration not working)

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-cli#1757]
Hi,

I am currently unable to migrate my project to the new CLI, it is failing on GraphQL api and i've decided for now to not waste precious time on it. I am using the most recent version of aws-amplify (v1.7.8 i believe).

So if i attempt to continue as normal, and i get the following error:

```
usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: enabledProviders.includes is not a function
```

How do i resolve this?

**Comment by kaustavghosh06** [comment]
You would have to migrate for your project to be compatible with the latest version of the CLI. Closing this issue since we're tracking your migration issue us #1758.
