### ISSUE TITLE
Migration of project to latest CLI version failing

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-cli#1758]
My migration of my existing project to the latest CLI version is failing, currently on the GraphQLSchema block:

`UPDATE_FAILED               GraphQLSchema                                         AWS::AppSync::GraphQLSchema Mon Jul 01 2019 11:49:39 GMT+0100 (British Summer Time) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 6E21786RDE39200E; S3 Extended Request ID: +x4mat4ehOAvgwkRVYyTlay6nrkLJWtshjYN93FEVZJaxKRf08D747nV6YlT534afowEKGJFS4A=)`

What needs to be done to rectify this?

**Comment by kaustavghosh06** [comment]
@chai86 Is it tied to #1757? Or are you past that stage?

**Comment by chai86** [comment]
No, this is for actually migrating the project, so still valid. #1757 is related to opting not to migrate.

**Comment by kaustavghosh06** [comment]
@chai86 Looks like the API Key that you'd used to configure your AppSync API initiallly has expired. You can renew this, by setting a parameter. Please read this to know more - https://aws-amplify.github.io/docs/cli/graphql#apikeyexpirationepoch

**Comment by kaustavghosh06** [comment]
@chai86 Also, did you make any modifications to the S3 deployment bucket which was generated by the CLI when you first configured the app?
