### ISSUE TITLE
No such module 'API8CD9941BMysampleappcdbClient' when following the AWS tutorial [1]

### ISSUE THREAD

**Issue by syumaK** [aws-amplify/amplify-cli#176]
** Which Category is your question related to? **
Add Cloud APIs to Your Mobile App using Amplify on iOS platform

** What AWS Services are you utilizing? **
Mobile-hub
Api-gateway ( through Cloud-Logic)

** Provide additional details e.g. code snippets **
When following the AWS tutorial [1] for iOS on how to add Cloud APIs to Your Mobile App using Amplify, I run into the following issue/exception at Step 3  of the section "Connect to your backend" - No such module 'API8CD9941BMysampleappcdbClient' even though I have the following import statement "import API8CD9941BMysampleappcdbClient"

<img width="868" alt="screen shot 2018-09-18 at 8 12 11 pm" src="https://user-images.githubusercontent.com/13468243/45708665-54580f80-bb82-11e8-99b1-a57cde77749a.png">

[1] https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-cloud-logic.html#add-aws-cloud-logic-backend-overview

**Comment by desokroshan** [comment]
@syumaK you don't have to import the generated client code file. After adding the file to your project as mentioned in the 1.d of the "Connect to your backend " section, you should be able to invoke it directly as in the snippet on documentation page. so you can just get rid of the import statement.

**Comment by kaustavghosh06** [comment]
Feel free to re-open this issue if the problem still persists.
