### ISSUE TITLE
Can't sign up with custom attribute of cognito by using Auth.signUp

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1761]
### Problem
Auth In aws-amplify and vue, 
I found the documents as follows

https://aws.amazon.com/jp/blogs/mobile/aws-amplify-adds-support-for-custom-attributes-in-amazon-cognito-user-pools/

I tried this but failed.

I found same issue as follows 

#2167

I try again but failed with the following error.

```
{
    code: "InvalidParameterException", name: "InvalidParameterException",
    message: "Attributes did not conform to the schema: custom:s…re_name: Attribute does not exist in the schema.↵"
}
```
Why did this error occured ?

```
 private get signUpParams () : SignUpParams {
    return {
      username: this.username,
      password: this.password,
      attributes: {
        email: this.email,
        family_name: this.familyName,
        given_name: this.givenName,
        'custom:store_name': this.storename
      }
    }
  }

  private handleSignUpClick () {
    const self = this
    Auth.signUp(self.signUpParams)
      .then(user => {
        return router.push('/verify')
      }).catch(err => {
        console.error(err)
      })
  }
```

### Depencency
aws-amplify    =>    1.1.29
aws-amplify-vue    =>    0.2.12

**Comment by yukitaka13-1110** [comment]
Thank you for transfering !

**Comment by kaustavghosh06** [comment]
@yukitaka13-1110 I beleive you have another thread where you were able to figure out how to add custom attributes to your user-pool cloudformation configurations on create. Closing this issue for now. Feel free to re-open if you've further questions.

**Comment by yukitaka13-1110** [comment]
@kaustavghosh06 I could do it. Thank you so mush !

**Comment by nihp** [comment]
I have added the custom attributes, but it failed to signUp with my attributes value.

I am using aws-amplify-react-native package.

Here I need to change only the UI for signUp. But the functionality of the screen is same as the default signUp screen.

I have used Auth.signUp method to make the signUp, but it failed to signUP.

Anyone can clarify this. **Attributes did not conform to the schema: name: The attribute is required\n**

```
Auth.signUp({
			username: this.state.email,
			password: this.state.password,
			attributes: {email: this.state.email},
		})
```

Note: My default screens works fine before. Customized UI is not working.

**Comment by zohaib-enquizit** [comment]
In case if custom attributes, you need to go to your respective client settings and check this attribute as readable and writable.

**Comment by yathu** [comment]
@nihp please check your parameter json    ```
 "requiredAttributes": [
        "email",
        "preferred_username"
    ],
```

for auth via email, I think you need to pass `preferred_username`. in my case its worked.

    ```
final option = CognitoSignUpOptions(userAttributes: {
      'email': email.trim(),
      'preferred_username': username.trim()
    });

    try {
      final res = await Amplify.Auth.signUp(
          username: email.trim(), password: password.trim(), options: option);
      return res.isSignUpComplete;
    } catch (e) {
      throw e;
    }
```
