### ISSUE TITLE
Using the @key directive on an existing type

### ISSUE THREAD

**Issue by cmoel** [aws-amplify/amplify-cli#1762]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AWS AppSync & DynamoDB

** Provide additional details e.g. code snippets **
I have a GraphQL `Student` type and backed by a DynamoDB table. I created the table before the `@key` directive was available and I'd like to add another key now. The documentation I found for it, though, doesn't seem to give me what I need to know: https://aws-amplify.github.io/docs/cli/graphql#evolving-apis-with-key. The `@key` I'd like to add is
`@key(name: "ByOwner", fields: ["owner", "status"])`

1. I added the GSI using the DynamoDB console with the partition key as `owner` and the sort key as `status`, projecting all attributes, with 1 RCU and 1 WCU (since my project is still in development),
2. Running `amplify push` (`amplify --version` tell me I'm on version 1.7.6) in my terminal starts the CloudFormation update but the update fails with this message:
```
UPDATE_FAILED      StudentTable          AWS::DynamoDB::Table   Sat Jun 29 2019 21:03:14 GMT-0400 (EDT) One or more parameter values were invalid: Both ReadCapacityUnits and WriteCapacityUnits must be specified for index: ByOwner (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: JVHAP8HH91AH666NTQQ6TFRQ83VV4KQNSO5AEMVJF66Q9ASUAAJG)
```
3. Taking a look at the `ByOwner` index in the DynamoDB console, I noticed the size is 0 bytes and it says it has an item count of 0.

I've also tried this without adding the GSI to the table first and I get the same error.

Is there something I'm doing wrong or something else I need to do to prepare to add this GSI and `@key` directive?

Thanks!

---

### UPDATE FROM THE NEXT DAY

The `ByOwner` index has become populated: the Size is 11.78 KB and Item Count is 28 (the same number of items in the main/default index). I ran describe table on the table and this is what it says about the index I'm trying to add the `@key` directive to:
```
{
  "IndexName": "ByOwner",
  "KeySchema": [
    { "AttributeName": "owner", "KeyType": "HASH" },
    { "AttributeName": "status", "KeyType": "RANGE" }
  ],
  "Projection": {
    "ProjectionType": "ALL"
  },
  "IndexStatus": "ACTIVE",
  "ProvisionedThroughput": {
    "NumberOfDecreasesToday": 0,
    "ReadCapacityUnits": 1,
    "WriteCapacityUnits": 1
  },
  "IndexSizeBytes": 11777,
  "ItemCount": 28,
  "IndexArn": "arn:aws:dynamodb:us-east-1:514873594615:table/Student-swtluuapnjgzvbi7edmq4j3mzq-master/index/ByOwner"
}
```

It looks like the everything is set up correctly with the index but I'm still getting the same error.

**Comment by mikeparisstuff** [comment]
Hey to help debug this issue can you confirm the value for key "DynamoDBBillingMode" in `parameters.json` within the api project.

**Comment by cmoel** [comment]
I did change the capacity in the DynamoDB Console to Provisioned but I didn't change "DynamoDBBillingMode" in `parameters.json`.

**Comment by kaustavghosh06** [comment]
@cmoel Did changing the "DynamoDBBillingMode" in your parameters.json file solve the issue for you?

**Comment by cmoel** [comment]
Hey, thanks for the reply. As I've learning more about DynamoDB over the past few days, I've decided to go for a single-table design. It doesn't look like Amplify currently supports this, is that correct? I haven't checked if changing the value for "DynamoDBBillingMode" resolves this because I'm more interested in the single-table design.

**Comment by kaustavghosh06** [comment]
Technically, you can use a single table to model your data (by using a single @model) and use the @key directive to for indexing the data. Please take a look at https://aws-amplify.github.io/docs/cli-toolchain/graphql#key for information around the @key directive

**Comment by cmoel** [comment]
Oh that's true! I hadn't thought to use a single @model directive.

Looking a bit into that strategy, it looks like I would only have 1 generated GraphQL object type then? Is that correct? I'd love if the @model directive generated the same schema parts (for things like connections and `ModelStringFilterInput`, etc.) but there was a way to configure the mapping between the GraphQL type and and the storage mechanism without needing to dig into the VTL templates.
