### ISSUE TITLE
Is it possible to setting automation of email verification when amplify auth add ?

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-cli#1767]
Simply, usage or feature request.
I want to automate email verification.
It is easy to realize using lambda pre-signup event trigger.
In aws-amplify/cli, is it possible ?

```js
var AWS = require('aws-sdk');
exports.handler = (event, context, callback) => {
    var confirm = {
        "autoConfirmUser": true,
        "autoVerifyEmail": true
    };
    event.response = confirm;
    context.done(null, event);
};
```

**Comment by kaustavghosh06** [comment]
@yukitaka13-1110 We're actively working on automating this for you using lambda triggers. You would see an update regarding this soon. I'll update this thread once we have the release out.

**Comment by yukitaka13-1110** [comment]
@kaustavghosh06 Thank you for quick response !
That's great !! I'm looking forward to it.

**Comment by davidbiller** [comment]
i guess its in the new rls 1.8.0 now.

**Comment by yukitaka13-1110** [comment]
@davidbiller Oh, really? I tried to find the change about cloudformation but couldn't find it.
Now I found out the target commits [c6fc838](https://github.com/aws-amplify/amplify-cli/commit/c6fc838)
Thank you for quick announcement !

**Comment by kaustavghosh06** [comment]
We've added support for Lambda Trigger support for the dynamo tables managed/added by the CLI using the `amplify add storage` command. Let me know if you find that useful. Please take a look at https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/ for more details.
