### ISSUE TITLE
Pass dynamic params to Elasticsearch

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#1768]
I am using a schema with @searchable. And I have a mapping template like:

```
"params": {
        "body": {
            "query": {
                "bool" : {
                    "must" : [

                        { "match" : { "monday": $ctx.args.params.monday }},
                        { "match" : { "tuesday": $ctx.args.params.tuesday }},
                        { "match" : { "wednesday": $ctx.args.params.wednesday }},

...
```

Is there a possibility to set the part in **must** dynamically (so from the code). I need more flexibility based on a filter that a customer is using, so I can't predefine all the musts.

**Comment by SwaySway** [comment]
@rpostulart Could you provide your schema as well?
Are you referring to how to change your filter in code?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of user response. Please feel free to re-open if you're still seeing this issue.
