### ISSUE TITLE
Do custom resolvers emit events to subscribers?

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1772]
** Which Category is your question related to? **
AppSync, Dynamo

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
If we create a mutation type in our schema.graphql and inside a custom resolver mapped to a lambda with @function. Let's say this resolver inserts data in one of the tables. The `onCreate` subscribers do not receive any events. I am assuming this is expected behavior. Is there a way to fire events through lambda custom resolvers?

**Comment by yuth** [comment]
@rawadrifai If your custom resolver for the mutation returns the inserted data, then the subscription should fire.

**Comment by rawadrifai** [comment]
Hi @yuth 
Do you know if codegen creates subscriptions for @function mutations?

I have something like this in my schema 
```
type Mutation {
  joinChannel(channel: String, invitee: String): String @function(name: "joinChannel-${env}")
}
```
By  return you mean `context.succeed(data)` ?
What would a subscription look like if it were to fire when the lambda returns?

**Comment by SwaySway** [comment]
@rawadrifai Since you specified a custom mutation in the schema you will need to add a custom subscription as well.
```gql
type Subscription {
  onJoinChannel: String @aws_subscribe(mutations: ["joinChannel"])
}
```
