### ISSUE TITLE
nextToken in dynamo client in aws-sdk

### ISSUE THREAD

**Issue by artista7** [aws-amplify/amplify-cli#1777]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

I saw, resolver templates uses a param nextToken for paginated query/scan in dynamo db. Is there a similar provision if we use dynamo client from aws-sdk directly?

**Comment by orozcoadrian** [comment]
yes, but I recommend using dynamodb's "document interface", which handles pagination for you automatically. See note at the end of [this section](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Pagination):

> The AWS SDKs handle the low-level DynamoDB responses (including the presence or absence of LastEvaluatedKey), and provide various abstractions for paginating Scan results. For example, the SDK for Java document interface provides java.util.Iterator support, so that you can walk through the results one at a time.

**Comment by SwaySway** [comment]
Closing this ticket. Should you have any additions questions/issue about the resolver template please feel free to reopen.
