### ISSUE TITLE
Apply a default filtering

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1780]
A snippet of my schema looks like this:

```
type Swipe
  @model
{
  id: ID!
  owner: String
  recipe: Recipe! @connection
  liked: Boolean!
  group: Group @connection(name: "GroupSwipes")
  timestamp: AWSDateTime
}



type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}
```

In my app I only want the GroupSwipes created in the last 7 days.
So I thought I move Group.swipes.req.vtl to my resolvers folder.

How can I set a default filtering here?
Since I not yet know how to do date filtering correctly I started testing with the `liked` Boolean field

```
#set( $limit = $util.defaultIfNull($context.args.limit, 5000) )
#set( $filter = $util.defaultIfNull($context.args.filter, "{liked: {eq: true}}") )
#set( $query = {
  "expression": "#connectionAttribute = :connectionAttribute",
  "expressionNames": {
      "#connectionAttribute": "swipeGroupId"
  },
  "expressionValues": {
      ":connectionAttribute": {
          "S": "$context.source.id"
    }
  }
} )
{
  "version": "2017-02-28",
  "operation": "Query",
  "query":   $util.toJson($query),
  "scanIndexForward":   #if( $context.args.sortDirection )
    #if( $context.args.sortDirection == "ASC" )
true
    #else
false
    #end
  #else
true
  #end,
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": $limit,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end,
  "index": "gsi-GroupSwipes"
}
```

But this still gives my both `liked == false` and `liked == true` items

**Comment by SwaySway** [comment]
@sprucify one option is that you can edit the query itself so you can apply the filter. Should generate a graphql query for ListGroups which in the generated query you can set a default to avoid specifying this in a call to your appsync api.

```graphql
query ListGroups(
  $filter: ModelGroupFilterInput  # replace with a filter here ex { "liked": { "eq": True } }
  $limit: Int
  $nextToken: String
) {
...
}
```

**Comment by sprucify** [comment]
That filter is just passing to the resolver right?
Because the problem with this approach is that my api.service.ts file will be overwritten on every `amplify codegen` command.

That is why I copied the build resolver to the resolvers folder.
But placing exact the same filter `{ "liked": { "eq": True } }` in there, it is not working.

**Comment by sprucify** [comment]
I got it working for liked == true by adding the following line in my resolver:
`#set( $context.args.filter = {"liked": {"eq": true}})`

My swipe model also contains a timestamp field of type AWSTimestamp

```
{
            "id": "d7604e82-3921-4ee5-98e2-e506e8eaf220",
            "liked": true,
            "timestamp": "2019-07-05T17:09:38+02:00"
          }
```
How do I set the filter to get only the data of the past 7 days?

**Comment by sprucify** [comment]
I think that can't be done in resolvers, since this is pretty static.
Why is there no filter option generated by `amplify codegen` on @connection fields?

**Comment by SwaySway** [comment]
@sprucify amplify codegen does code generation based on schemas. This type of implementation you are referring to here is changing the VTL resolver templates. Which is certainly an option as we do have documentation on [custom resolvers](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers). Using a custom resolver in this usecase might be a good option.
