### ISSUE TITLE
Invalid syntax error during installation

### ISSUE THREAD

**Issue by falej** [aws-amplify/amplify-cli#1781]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
When running the `sudo npm install -g @aws-amplify/cli` there is an error from gyp package that says
`
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
gyp ERR! System Darwin 16.7.0
`
But the installation finishes correctly and the CLI is working 

**To Reproduce**
Node version: 10.15.3
NPM version: 6.10.0
run command `sudo npm install -g @aws-amplify/cli`

**Expected behavior**
Run without errors, probably some warning, but no errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - Browser (N/A)
 - Version (N/A)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
Please refer to this issue which has an explaination to this - #783 
This is tied to a specific version of node + fsevents installed globally in your system and in no ways does it affect the installation and usage of the CLI.

**Comment by falej** [comment]
Thanks Ghosh!

alejandroflores
______________________________
E: alejandro.x.flores@gmail.com
