### ISSUE TITLE
Use defined AuthCognitoUserPoolId in CustomResources.json

### ISSUE THREAD

**Issue by at0mat** [aws-amplify/amplify-cli#1785]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
API / AUTH

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **

Looking to define groups in CustomResources.json for my auth userpool.

I get "Unresolved resource dependencies [AuthCognitoUserPoolId]" on amplify push after adding the following to CustomResources.json

```
"UserPoolGroupAdmin": {
  "Type": "AWS::Cognito::UserPoolGroup",
  "Properties": {
    "GroupName": "admin",
    "UserPoolId": {
      "Ref": "AuthCognitoUserPoolId"
    }
  }
}
```

**Comment by kaustavghosh06** [comment]
Could you share your `amplify/backend/<api-name>/parameters.json` file?

**Comment by kaustavghosh06** [comment]
Also, you would need to add  the following to your `amplify/backend/<api-name>/stacks/CustomResources.json` file in the Parameters section.
```
"AuthCognitoUserPoolId": {
            "Type": "String",
            "Description": "The id of an existing User Pool to connect. If this is changed, a user pool will not be created for you.",
        }
```

It would be a nice enhancement if we add this automatically when we configure the API with Cognito User pool.

**Comment by at0mat** [comment]
`{
    "AppSyncApiName": "greendata",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "authgreendatae8d1f094",
            "Outputs.UserPoolId"
        ]
    }
}`

**Comment by at0mat** [comment]
Adding that parameter automatically may be all I am looking for if that's what's necessary to use it. I'll add the parameter manually this evening and leave the outcome here as a comment.

**Comment by at0mat** [comment]
Adding the parameter was all that was required in my particular case. Automatically adding that parameter would be a great addition.

**Comment by WinstonN** [comment]
In my case I was following this tutorial, https://dev.to/beavearony/aws-amplify-cli-how-to-automatically-add-a-user-to-a-cognito-user-pool-with-a-lambda-trigger-208j when I got this error
```
Template format error: Unresolved resource dependencies [AuthCognitoUserPoolId] in the Resources block of the template
```
Google brought me to this tread, and adding https://github.com/aws-amplify/amplify-cli/issues/1785#issuecomment-510573986 gave me a syntax error
I adde the code to `amplify/backend/api/application_name/stacks/CustomResources.json`

Removing the comma fixed it as below
```
"AuthCognitoUserPoolId": {
      "Type": "String",
      "Description": "The id of an existing User Pool to connect. If this is changed, a user pool will not be created for you."
    }
```
