### ISSUE TITLE
Wrong resolver created on @connection when primary partition key name differs from "id" for "one-to-one" relations (also sort key doesn't included in resolver)

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#1786]
**Describe the bug**
I've created following schema in Graphql Transform language:

```
type User @model {
  id: ID!
  nickname: Nickname @connection(name: "UserNickname", keyField: "partKey", sortField: "sortKey")
}

type Nickname @model @key(fields: ["partKey", "sortKey"]) {
  partKey: ID!
  sortKey: ID!
  owner: User! @connection(name: "UserNickname", keyField: "nicknameOwnerId")
}
```

When I had pushed this schema I received following resolver for connection (User.nickname.req.vtl) :

```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.partKey, "___xamznone____"))
  }
}
```

And as result I have next bug when I'm trying to perform query connected relation: **The provided key element does not match the schema**

I could manually replace this resolver with right one, and then query succeeds.

**Expected behavior**
In case of **one-to-one** relations I should receive something like this:
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "partKey": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.partKey, "___xamznone____")),
      "sortKey": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.sortKey, "___xamznone____"))
  }
}
```

Also for **one-to-one** connection with partition key and sort key next input data did generated:
```
input CreateUserInput {
  id: ID
  partKey: ID
}
```

istead of:
```
input CreateUserInput {
  id: ID
  partKey: ID
  sortKey: ID
}
```

**Comment by mikeparisstuff** [comment]
Hey @lenarmazitov, we have a work item on the backlog to add a new directive that allows creating relationships but that leverages the `@key` directive. In the meantime, you can implement this use yourself by writing a customer resolver that uses the @key index (see https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers). You should also be able to drop the correct input type definition and the transform will not overwrite it.

**Comment by lenarmazitov** [comment]
@mikeparisstuff 

So how about this type of transform schema:

```

**Comment by lenarmazitov** [comment]
@mikeparisstuff 

But how about thing when I write this in transform syntax:
```
type User @model {
  id: ID!
  nickname: Nickname @connection(name: "UserNickname", keyField: "partKey", sortField: "sortKey")
}
```

After compilation I get only keyField generated nor sortKey in **input type** in schema.graphql:
```
input CreateUserInput {
  id: ID
  partKey: ID
}
```

Is this right behaviour?
Also resolver for relation, we described that it consists from partition key and sort key in connection directive...
Sorry, but seems like sortField functional is incomplete yet, may be I wrong...
