### ISSUE TITLE
AppSync GraphQL Transform - creating models with a @key and then connecting them to other models

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#1800]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AppSync GraphQL Transform

** What AWS Services are you utilizing? **
AppSync, DynamoDB, Cognito

** Provide additional details e.g. code snippets **
I'm trying to create an `Invitation` model that will have a `code` which is a `String` as its primary key in the database (a unique code), then when creating a `User` (also a model) the invitation code must be provided, and that invitation will be connected to the user - meaning that I can access the user who used the invitation when querying the invitation, and I can also get the invitation code that was used when querying the user.

the Invitation model -
```gql
type Invitation @model {
  code: String!
  used: Boolean!
  user: User @connection(name: "UserInvitation")
}
```

the User model - 
```gql
type User @model {
  id: ID!
  firstName: String!
  lastName: String!
  invitation: Invitation! @connection(name: "UserInvitation")
}
```
How can I create that sort of connection?

**Comment by davidbiller** [comment]
1. Why you want the Code as primary key? (If you use it like you do it here, the invitation code is already in the user Object.)
2. Check out the keyfield in the @connection section of the docs.
3. If you really want it as primary key, check the @key section of the docs. (But if you use it as primary key, you only get an new resolver like getInvitationByUser)

Point 3, i am not sure, but you destroy the GSI from the connection. 
Check this: https://github.com/aws-amplify/amplify-cli/issues/1656#issuecomment-504125698

**Comment by idanlo** [comment]
@davidbiller The reason I wanted to use the code field as the primary key is so that when creating the user instead of passing an id which is a uuid string I would simply pass the code and then it will automatically link to the invitation.

The thing I ended up doing was removing the `code` field and treating the `id` field as if it is the code, so when creating an invitation I would give it in an id of `123456` which is actually the code, and when creating a user I would enter the code as the `id` field and it will automatically link to the invitation, that way the code is also unique because it's a primary key like an actual ID.

Another question I wanted to ask is how can I link the `user` field in the `Invitation` model to the actual user when the user is created - for example currently when creating an invitation the `user` will be null but I want it to reference the user that used the invitation code when it is created, is that something I have to do manually whenever creating a user (updating the Invitation to connect to the user) or use a lambda function that gets triggered when a user is created, or maybe is there a way to automatically do this? I'm not sure I explained myself well so tell me if you don't understand my question

**Comment by walterg2** [comment]
@idanlo I was looking to do something similar as you (use a non-ID field as the primary key) and wanted to have a connection created to that table. In my case, I was looking to use an email as the primary key (as this is for a user table and emails need to be unique), but it appears the `keyField` does _not_ change how the GraphQL request attempts to `GetItem` on the child record, just what the table column will be named in that specific table.

For some AWS folks, the schema I was working with was:

```graphql
type User {
  email: String!
  firstName: String!
  lastName: String!
  teams: [TeamMember] @connection(name: "UserTeamMemberConnection")
}

type TeamMember {
  id: ID!
  teamId: Team! @connection(name: "TeamTeamMemberConnection")
  userId: User! @connection(name: "UserTeamMemberConnection", keyField: "email")
  position: String!
}

type Team {
  id: ID!
  name: String!
  description: String!
  teamMembers: [TeamMember!]! @connection(name: "TeamTeamMemberConnection")
}
```

**Comment by idanlo** [comment]
@walterg2 to set fields as the primary-key for the table you need the @key directive.

**Comment by walterg2** [comment]
Ah, that's my bad... I manually added that stuff above and missed the directives. Corrected directives are:

```graphql
type User
@model
@key(name: "email")
{
  email: String!
  firstName: String!
  lastName: String!
  teams: [TeamMember] @connection(name: "UserTeamMemberConnection")
}

type TeamMember
@model
{
  id: ID!
  teamId: Team! @connection(name: "TeamTeamMemberConnection")
  userId: User! @connection(name: "UserTeamMemberConnection", keyField: "email")
  position: String!
}

type Team
@model
{
  id: ID!
  name: String!
  description: String!
  teamMembers: [TeamMember!]! @connection(name: "TeamTeamMemberConnection")
}

**Comment by idanlo** [comment]
Is there any update on this? I ran into this again while trying to create my table with a primary key that includes 2 fields, and I want it to have an array of other models but I don't know how to connect them

**Comment by SwaySway** [comment]
@idanlo 
Adding a connection where the pimary field is based on a different value (from a change in key) is an active issue we are working on. https://github.com/aws-amplify/amplify-cli/issues/2296

Regarding your original query - If you are looking to connect multiple users with a single invitation then what you are looking for is a one-to-many connection.
```gql
type Invitation
	@model {
	id: ID!
	used: Boolean!
	user: [User] @connection(name: "UserInvitation")
}
type User @model {
	id: ID!
	firstName: String!
	lastName: String!
	invitation: Invitation! @connection(name: "UserInvitation")
}
```
The id can simply be the code you are referring to that when querying for either an invitation you can see a list of users which used said invitation "code" and when listing users you can see the invitation "code" they used.

**Comment by idanlo** [comment]
thanks @SwaySway, what you suggested is what I ended up using 3 months ago but I ran into a different problem now, where I have a model that its primary key is made from 2 fields in the model and I want it to have an array of other models, so those other models need to reference the first model somehow, and there is currently no way to do that. 
If you didn't understand my use case feel free to tell me and I'll try to explain it better

**Comment by SwaySway** [comment]
@idanlo There is a workaround for a connection on custom primary keys.
There is a fix in the works to address this as well. Please refer to
View https://github.com/aws-amplify/amplify-cli/issues/2100

**Comment by idanlo** [comment]
Closed due to support for @key directive with @connection directive in recent updates
