### ISSUE TITLE
amplify add codegen claims API does not exist in selected region

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#1802]
**Describe the bug**
amplify add codegen claims a pre-existing AppSync API does not exist in the selected region (us-east-1) when I have verified that it does.

**To Reproduce**
1. Create AppSync API from the AppSync console or CLI
2. Create new Amplify project
3. run the generated `amplify add codegen` command from the AppSync API console
4. observe the bug claiming it does not exist in us-east-1 (see screenshots)

**Expected behavior**
The pre-existing AppSync API is found and the introspection schema is downloaded and added to the Amplify project.

**Screenshots**
![image](https://user-images.githubusercontent.com/22964702/60905246-e7595780-a231-11e9-8459-9aa903a57c89.png)
![appsync-bug](https://user-images.githubusercontent.com/22964702/60905420-4c14b200-a232-11e9-86f1-65d153320b65.png)

**Comment by yuth** [comment]
@jkeys-ecg-nmsu do you have Amplify CLI using the credential that has access to the selected AppSync API?

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu I just tried this out and we couldn't reproduce this issue. Please let us know if the local AWS profile is tied to the same AWS account which you used to generate the AppSync API.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu We tried this with a couple of team members and this doesn't seem to be an issue with anyone - nor has anyone else in the community come accross this. My hunch is that the AWS credentials that you're using locally is for a different AWS account. Please feel free to comment on this thread if you're still stuck on this issue.

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 sorry it's been frenetic at work, so I haven't had time to follow up. It's actually no longer needed for my project to track multiple APIs but I'll still confirm this is not a bug and was a credentials error ASAP.
