### ISSUE TITLE
Cant create a new ENV after update to v1.8.0  - no such file or directory ... function-parameters.json

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#1806]
**Describe the bug**
Cant create a new ENV after update to v1.8.0 

**To Reproduce**
Do you want to use an existing environment? (n)
Enter a name for the environment: develop
Do you want to use an AWS profile? (Y) - default
...
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
Do you want to configure Lambda Triggers for Cognito? (n)

`✖ There was an error initializing your environment.
init failed
{ Error: ENOENT: no such file or directory, open '/Users/davidbiller/Desktop/Developer/aivy-rn-app/amplify/backend/function/aivy/function-parameters.json'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:351:35)
    at Object.readJsonFile (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:11:33)
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/provider-utils/awscloudformation/index.js:427:42)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/index.js:115:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/Users/davidbiller/Desktop/Developer/aivy-rn-app/amplify/backend/function/aivy/function-parameters.json' }`

If i choose Y or N the same result. 

**Additional context**

amplify --v
1.8.0

//Seems there is no aivy/function-parameters.json
Note: aivy is not a function, it is the project name.
My functions are direct in the functions folder.

**Comment by dbramwell** [comment]
I'm suffering from this issue as well. It seems in previous versions of amplify the `function-parameters.json` wasn't generated when adding a function. In my project some functions have this `function-parameters.json` and some don't.

A simple fix could be checking if the file exists. Not sure if this is the best solution though. I'll make a pull request.

**Comment by davidbiller** [comment]
> I'm suffering from this issue as well. It seems in previous versions of amplify the `function-parameters.json` wasn't generated when adding a function. In my project some functions have this `function-parameters.json` and some don't.
> 
> A simple fix could be checking if the file exists. Not sure if this is the best solution though. I'll make a pull request.

The individual functions have the file by me.
I see rather that he searches again a json in the functions folder itself?!
//see in my post - aivy is not a function name, it is the projekt name

**Comment by haverchuck** [comment]
@davidbiller - Thanks for posting this issue, and thanks for the PR @dbramwell.
