### ISSUE TITLE
Change data source to Lambda function atonce

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#1809]
Following are my data sources generated using CLI

![data_sources](https://user-images.githubusercontent.com/51752377/60984623-a52b3580-a359-11e9-8118-38314b85fcfa.JPG)

How could I change the data source of all tables to Lambda Function without going to AWS console via CLI

![data_source](https://user-images.githubusercontent.com/51752377/60984642-b07e6100-a359-11e9-92f4-547aded18104.JPG)

**Comment by yuth** [comment]
There is no straight forward way to change the data source to Lambda functions from DDB without loosing the tables. If you use [@function](https://aws-amplify.github.io/docs/cli-toolchain/graphql#function) directive, the DDB data source will be deleted as those are no longer the data sources from Transformers perspective and you will have to create them on your own
