### ISSUE TITLE
AppSync not available in certain regions => push fails 

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-cli#1811]
**Describe the bug**
amplify v1.7.8
The error message when pushing to a region where AppSync is not available is not explicit and could be enhanced so the user understand what is happening

**To Reproduce**

- Setup your project in eu-west-3 zone (AppSync is not supported here)
- amplify add api
- code some graphql
- amplify push

```
CREATE_FAILED      apiname    AWS::CloudFormation::Stack Thu Jul 11 2019 10:54:56 GMT+0200 (CEST) Template format error: Unrecognized resource types: [AWS::AppSync::GraphQLApi, AWS::AppSync::GraphQLSchema, AWS::AppSync::ApiKey]
```

**Expected behavior**
The best user experience would be to tell the user from the first `amplify init` command that the selected region is not fully compatible with amplify features. That would avoid having to move the project later from one region to another...

**Comment by kaustavghosh06** [comment]
@vparpoil Did you setup your profile using the Amplify CLI? When you run `amplify configure`, we just show you the supported regions where all the services are available. But, yes I do agree it would good to have some logic in init to check for the region in your selected profile and throw an error message if it' not supported.

**Comment by vparpoil** [comment]
@kaustavghosh06 Thanks for the explanation. I actually did setup my profile manually because I was using it on another setup with the serverless framework, this is why I didn't saw the error message

**Comment by kaustavghosh06** [comment]
@vparpoil If you configured your profile using the `amplify configure` command - you would be prompted for only regions supported by the services (supported by the CLI). As an when services become available in other regions, we'll expand the region-list which we display as a part of the `amplify configure` command.
