### ISSUE TITLE
How to modify generated update resolver to support create-or-update?

### ISSUE THREAD

**Issue by kwhitejr** [aws-amplify/amplify-cli#1812]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Api: Appsync generated code.

** What AWS Services are you utilizing? **
Appsync

** Provide additional details e.g. code snippets **
I simply want to modify certain generated resolvers (i.e. `Mutation.updateXYZ.req.vtl`) to support create-or-update, in order to cut down on have a bunch of conditional checks in front end code.

In the most straightforward form of the issue, the update resolver requires an `id` field that does not yet exist. For example:

```
{
  "version": "2017-02-28",
  "operation": "UpdateItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
  "id": {
      "S": "$context.args.input.id" // if this doesn't exist, create with $util.autoId()
  }
} #end,
  "update": $util.toJson($update),
  "condition": $util.toJson($condition)
}
```

Essentially I don't understand where in the generated updateXYZ vtl code to put a check for an `id` input + autoId if missing.

**Comment by kaustavghosh06** [comment]
@kwhitejr You could use Custom resolvers to overwrite the auto-generated transformer resolvers. You can find more documentation out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers
Please feel free to re-open this issue if you're still stuck.

**Comment by kwhitejr** [comment]
@kaustavghosh06 Hi Kaustav, thanks for the quick replay. I know about replacing resolvers, and usually I can get away with minor adjustments to the generated code. For the mutation `update` resolver code, however, I'm a little overwhelmed, not sure where to start.
