### ISSUE TITLE
Amplify can detect and integrate with Appsync-backing Dynamo table streams when adding Function

### ISSUE THREAD

**Issue by kwhitejr** [aws-amplify/amplify-cli#1814]
**Is your feature request related to a problem? Please describe.**
When creating a lambda with `amplify function add`, Amplify should provide the option to integrate with a Dynamo Stream from tables associated with Appsync apis. Currently, Amplify does not appear to detect these tables.

**Describe the solution you'd like**
The integration described above.

**Describe alternatives you've considered**
Used `amplify function add` to create a Hello World lambda, then (1) manually updated lambda permissions in generated CloudFormation and (2) added connection to Dynamo Stream in the Dynamo console.

**Additional context**
Using version `1.1.30`, here is CLI experience where Amplify did not find the Appsync-integrated DynamoDB tables:
```
> amplify function add
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: myNewLambdaFunction
? Provide the AWS Lambda function name: myNewLambdaFunction
? Choose the function template that you want to use: CRUD function for Amazon DynamoDB table (Integration with Amazon API Gateway and Amazon Dy
namoDB)
? Choose a DynamoDB data source option Use DynamoDB table configured in the current Amplify project
There are no DynamoDB resources configured in your project currently
? Choose a DynamoDB data source option
❯ Use DynamoDB table configured in the current Amplify project
  Create a new DynamoDB table
```

**Comment by RossWilliams** [comment]
You can modify the function's cloudformation template to add the event source mapping since every table's stream arn is exported. An example:
```json
{
    $MY_RESOURCE_NAME: {
            "Type": "AWS::Lambda::EventSourceMapping",
            "Properties": {
                "BatchSize": 1,
                "Enabled": true,
                "EventSourceArn": {
                    "Fn::ImportValue": {
                        "Fn::Join": [
                            ":",
                            [
                                {
                                    "Ref": "AppSyncApiId"
                                },
                                "GetAtt",
                                $MY_DYNAMO_TABLE_NAME,
                                "StreamArn"
                            ]
                        ]
                    }
                },
                "FunctionName": {
                    "Fn::GetAtt": [
                        $MY_LAMBDA_FUNCTION_RESOURCE_NAME,
                        "Arn"
                    ]
                },
                "StartingPosition": "LATEST"
            },
            "DependsOn": [
                 $MY_LAMBDA_FUNCTION_RESOURCE_NAME,
            ]
        }
}
```
The import value is a direct copy from the Outputs -> Export property in your table's autogenerated cloudformation stack.  
You probably also need to update your function properties in backend-config.json to add a dependsOn for the AppSyncApiId property if it isn't already.

**Comment by kwhitejr** [comment]
@RossWilliams Thanks for this assistance. Finally got some time to give it a go. Ran into some hiccups:

1. When using `Fn::ImportValue`, it seems that you cannot include usage of Ref or GetAtt:
> For outputs, the value of the Name property of an Export can't use Ref or GetAtt functions that depend on a resource.
> Similarly, the ImportValue function can't include Ref or GetAtt functions that depend on a resource.

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html

2. As a quick workaround, I've just hardcoded the right value for now. Regardless, I continue to get the following error from CloudFormation:

> CREATE_FAILED      LambdaEventSource AWS::Lambda::EventSourceMapping Sat Jul 27 2019 18:02:22 GMT-0700 (PDT) Cannot access stream arn:aws:dynamodb:us-east-1:XXXXXXXXX:table/Rating-myapiid-dev/stream/2019-07-17T05:22:48.968. Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 24092502-1a58-486f-89f8-fdf74f5bfd6f)

This error comes in spite of having already added this Statement to the `AmplifyResourcesPolicy`:
```
...,
{
	"Effect": "Allow",
	"Action": [
		"dynamodb:Describe*",
		"dynamodb:Get*",
		"dynamodb:List*"
	],
	"Resource": [
		{
			"Fn::Sub": [
				"arn:aws:dynamodb:${region}:${account}:table/Rating-${apicpapiGraphQLAPIIdOutput}-${env}/stream/*",
				{
					"region": {
						"Ref": "AWS::Region"
					},
					"account": {
						"Ref": "AWS::AccountId"
					}
				}
			]
		}
	]
}
```

`apicpapiGraphQLAPIIdOutput` and `env` are helpfully provided by Amplify as parameters. Anyway, I've tried a variety of `DependsOn` combinations to try to ensure that `AmplifyResourcesPolicy` gets created before `LambdaEventSource`, but nothing changes that error message. The event logs show the `LambdaEventSource` attempting to update and failing before the `AmplifyResourcesPolicy` update events kick off. Thoughts?

**Comment by kwhitejr** [comment]
Quick (maybe unhelpful) update, but I made the `LambdaEventSource` depend on every other resource in the CF file and it worked. 🤷‍♂

**Comment by RossWilliams** [comment]
@kwhitejr The limitations of Fn::ImportValue relate to cross-stack references. If you are working inside Amplify all templates should be in the same stack-set. I think you discovered it works when setting the right dependsOn. This is what I referenced as part of backend-config.jsson but did not explain fully. Glad it worked out in the end for you.

**Comment by kaustavghosh06** [comment]
We released this feature as a part of our latest CLI version release - 4.16.1.
You can checkout the documentation out here for more information - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation
