### ISSUE TITLE
How do I access User Pools created by Amplify CLI authentication component  through AWS console/ Cognito?

### ISSUE THREAD

**Issue by thelovesmith** [aws-amplify/amplify-cli#1817]
Hello, 

I followed this [Tutorial](https://hackernoon.com/building-jamstack-applications-with-gatsby-and-aws-amplify-framework-d7e2b9e7117e) to create a Gatsby app that allows users to signup and signin via the aws-amplify **{ withAuthenticator }** . I successfully created those functions via Amplify CLI following the Amplify Docs. I was able to log in and I received verification emails. So, I know that the code is working and Amplify is working. However, I want to see my list of verified users that is supposedly saved on the cloud. However, when I go to AWS Cognito to view my user pools like it says in the docs, there are no pools and i am only given the option to create a new one. 

My question is, can I access my user pool that was created through the Amplify CLI? 
If so, how do I access them, through Cognito, AWS, IAM ? 
I can't find any answers. 
Also, I know Amplify is creating and documenting users SOMEWHERE because I am getting the verification emails, and I can login to my app successfully. I just don't understand how to access them. In Firebase you can access your verified users easily via your Firebase console. I assume you can access your verified users in AWS, but I'm guessing when using Amplify its a different case.
Where is the user information that is being created though Amplify being stored? How do i access the information? 

** AWS Amplify CLI**

**Comment by yuth** [comment]
You could use the following command
`$ amplify auth  console`

**Comment by thelovesmith** [comment]
Okay thank you!! 
So pretty much if I want to access the specific services that were generated using Amplify CLI I have to go through the CL?? Because I tried accessing this same page through AWS and couldn't get to it. I assume i can also  use this 'console' command to access the other services such ass AppSync or DynamoDB?

Thank you for your time!!

**Comment by yuth** [comment]
>So pretty much if I want to access the specific services that were generated using Amplify CLI I have to go through the CL?? Because I tried accessing this same page through AWS and couldn't get to it.

You should be able access it from console directly. You should be logged in using the right credentials and you should be in the right region on the console for this to be shown.

>  I assume i can also use this 'console' command to access the other services such ass AppSync or DynamoDB?

Most of the categories support this but some categories may not have the command implemented.

**Comment by thelovesmith** [comment]
Yeah I originally thought it was a credentials issue but I was definitely logged in as the right user but couldn't find anything that I initialized vie Amplify CLI. But after running the above command everything is now available lol 

Thanks very much!!
