### ISSUE TITLE
Amplify push with Api change overrides schema.json path

### ISSUE THREAD

**Issue by amirmishani** [aws-amplify/amplify-cli#1818]
**Describe the bug**
I have a mono repo setup where my `/amplify` folder sits in the root of the project and my `/graphql` folder is located in a shared package like so `packages/core/src/graphql/schema.json`. When I'm pushing changes in the API the **schemaPath** setting in my `.graphqlconfig.yaml` file is always overwritten. The actual mutation and query file paths are respected and only the schemaPath is changed to a default `schemaPath: src/graphql/schema.json`

**To Reproduce**
1. Move your `/graphql` directory somewhere other than `/src`
2. Refelect the change in your `.graphqlconfig.yaml`
3. Change something in your GraphQL schema
4. use `amplify push` and confirm updates to GraphQL API and generating GraphQL statements.
5. Observe GraphQL statements correctly being placed in new location but a new `/graphql/schema.json` created in the root of your project AND in your `.graphqlconfig.yaml` the **schemaPath** changed back to `schemaPath: src/graphql/schema.json`

**Expected behavior**
I expect the **schemaPath** setting to be respected and not overwritten.

**Comment by kaustavghosh06** [comment]
We don't expose the schemaPath custom configuration and is hardcoded currently. I'm adding this as an enahncement so that this schemaPath is configurable and not overwritten.

**Comment by amirmishani** [comment]
Awesome thanks!
