### ISSUE TITLE
Additional configurations/settings for @searchable

### ISSUE THREAD

**Issue by mjmaix** [aws-amplify/amplify-cli#1819]
**Is your feature request related to a problem? Please describe.**
I'm looking into cost-savings during development. The current generated Elasticsearch instance t2.small could be t2.micro (Probably)
```
Elasticsearch version 6.2
Availability zones 1
Instance type t2.small.elasticsearch
Number of instances1
Storage type EBS
EBS volume type General Purpose (SSD)
EBS volume size 10 GB
```

**Describe the solution you'd like**

I would like to have an additional configuration to support version `2.3` and `t2.micro instance`.

I reviewed the [GraphQL Elasticsearch-transformer](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-elasticsearch-transformer/src/resources.ts) but the smallest is `t2.small`.
An option I'm looking at is to set Elasticsearch instance to `t2.micro` for development as mentioned here [Supported Instance Types](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html) but the supported version should be `Elastisearch 2.3/1.5`.

The issue with this could be missing features or incompatibility with AppSync. Maybe, a bit slow but this is a tradeoff. If this is the case then it can't be helped.

**Describe alternatives you've considered**
There's no other cost-saving that I'm aware of.

**Additional context**

|  Type  | Price Per hour | Hours per month | $ Per Month  | 
|---|---|---|---|
|  t2.micro.elasticsearch |   0.018 |  730 |   13.14| 
|  t2.small.elasticsearch |   0.036 |   730|   26.28|  

The `t2.micro` instance would cost half the price.

**Comment by renebrandel** [comment]
Hi - we now provide a mechanism for you to override Amplify-generated resources including the @searchable related resources: https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive
