### ISSUE TITLE
@key for ID which is auto filled by resolver using autoId()

### ISSUE THREAD

**Issue by kams-mash** [aws-amplify/amplify-cli#1821]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
amplify-cli

** What AWS Services are you utilizing? **
appsync, dynamodb

** Provide additional details e.g. code snippets **
I have the following model:
```
type Machine @model
      @key(fields: ["id", "userId"])
{
  id: ID!
  userId: ID!
  name: String
}
```
With this, the client has to explicitly provide the `id` value in the `createMachine` mutation, but I want to auto populate `id` using `$util.autoId()` in the resolver - in order to do this I removed the `id` from the model above, but when I try to `amplify push` I get an error specifying I cannot use `@key` directive on non-existent `id`.

(Similarly I'd like to autofill `userId` in the resolver and not have the client populate this in the mutation.)

Is it possible for @key directive to be used which is helpful in creating indexes on the dynamodb datasources, while still not having to specify `id` in the schema so that the client does not have to populate this in the mutation?

**Comment by kams-mash** [comment]
NVM, I learned that instead of removing `id` from the `Machine @model`, I have to actually update my schema.graphql and add my custom `input CreateMachineInput` which does not have `id` property - this will allow the clients to not have to send the `id` while still allowing the resolver to autofill using `$util.autoId()`.

**Comment by seanim0920** [comment]
Did you manage to figure out how to autofill a userId in the resolver?
