### ISSUE TITLE
Amplify invoke function

### ISSUE THREAD

**Issue by sceptyk** [aws-amplify/amplify-cli#1822]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
function

** What AWS Services are you utilizing? **
none

** Provide additional details e.g. code snippets **

What does 'amplify function invoke FUNCTION_NAME' do other than running node script? Do I need it when testing function?

My current usage:
1. Run script that invokes all the functions in the backend with custom events
2. Inspect returned values from the handlers
3. Check which executions failed

Now, I just want to know if I could just execute handlers directly without running them through 'amplify function invoke'. It would make it much simpler to inspect the returned values and I could also avoid hacking optional questions about handler function file and handler function to invoke.

Are there any plans on the roadmap to upgrade testing of functions so that it is not limited to a single function with a single event.json? It would be extremely helpful especially since the @function directive was added.

**Comment by kaustavghosh06** [comment]
@sceptyk Yes, you could drectly call the handler function. The CLI just wraps around the event object from the specified file - `event-xyz.json` and then passes it to the handler to test the function.

We do support multiple event files. Please take a look at - https://github.com/aws-amplify/amplify-cli/issues/1187#issuecomment-512544471 for more details around it.

**Comment by sceptyk** [comment]
@kaustavghosh06 Thanks for the reply, it answers my question. I was actually still on the older version of cli and didn't notice you can use multiple event files. Thanks for pointing this out.
