### ISSUE TITLE
Modify Locally Generated API

### ISSUE THREAD

**Issue by lanbau** [aws-amplify/amplify-cli#1823]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify add api

** What AWS Services are you utilizing? **
Appsync
** Provide additional details e.g. code snippets **

Hi i have a question and can’t seem to find it anywhere.

I would like to modify a locally generated API
- it can be either graphql or REST

Q. Do i have to manually edit the config files under the generated amplify folder?

I found this issue (https://github.com/aws-amplify/amplify-cli/issues/1402)
However, it seems that you have to delete the files manually and recreate a new API via amplify add api.

**Comment by UnleashedMind** [comment]
When you add an API, you can see what's been created for you by the Amplify CLI under the folder `amplify/backend/api/<api-name>`, you can locally edit them before you run `amplify push` to push your local changes to the AWS cloud.
