### ISSUE TITLE
Reason: ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, nodejs8.10, python2.7, python3.6, python3.7.

### ISSUE THREAD

**Issue by DeniseJames** [aws-amplify/amplify-cli#1824]
**Describe the bug**
Using 'amplify push" I get this error:

Following resources failed

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: ZipFile can only be used when Runtime is set to e

**To Reproduce**
1. amplify init
2. amplify add auth
3. amplify add storage
4. amplify push

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Nodejs 12.4

**Additional context**

Current Environment: bssenv

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Auth     | cognito3619aa48 | Create    | awscloudformation |
| Storage  | buysellstorage  | Create    | awscloudformation |
? Are you sure you want to continue? Yes
/ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authcognito3619aa48   AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:20 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS authcognito3619aa48   AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:19 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS storagebuysellstorage AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:19 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS storagebuysellstorage AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:18 GMT-0500 (Central Daylight Time)
\ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS buysell-20190715031528-authcognito3619aa48-1CZ0NK1V2ZPUU AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:20 GMT-0500 (Central Daylight Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS buysell-20190715031528-storagebuysellstorage-CHG305SRYHWY AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:19 GMT-0500 (Central Daylight Time) User Initiated
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS S3Bucket AWS::S3::Bucket Mon Jul 15 2019 03:16:24 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS S3Bucket AWS::S3::Bucket Mon Jul 15 2019 03:16:22 GMT-0500 (Central Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Mon Jul 15 2019 03:16:27 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Mon Jul 15 2019 03:16:27 GMT-0500 (Central Daylight Time)
\ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Mon Jul 15 2019 03:16:45 GMT-0500 (Central Daylight Time)
CREATE_COMPLETE    SNSRole  AWS::IAM::Role         Mon Jul 15 2019 03:16:40 GMT-0500 (Central Daylight Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE S3Bucket AWS::S3::Bucket Mon Jul 15 2019 03:16:45 GMT-0500 (Central Daylight Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPool AWS::Cognito::UserPool Mon Jul 15 2019 03:16:49 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Mon Jul 15 2019 03:16:49 GMT-0500 (Central Daylight Time) Resource creation Initiated
/ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS S3AuthPolicyRW AWS::IAM::Policy Mon Jul 15 2019 03:16:49 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS S3AuthPolicyRW AWS::IAM::Policy Mon Jul 15 2019 03:16:48 GMT-0500 (Central Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolClientWeb AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:54 GMT-0500 (Central Daylight Time)
CREATE_COMPLETE    UserPoolClient    AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:54 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:54 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:54 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:52 GMT-0500 (Central Daylight Time)
CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:16:52 GMT-0500 (Central Daylight Time)
\ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE S3AuthPolicyRW AWS::IAM::Policy Mon Jul 15 2019 03:16:54 GMT-0500 (Central Daylight Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Mon Jul 15 2019 03:16:58 GMT-0500 (Central Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Mon Jul 15 2019 03:16:58 GMT-0500 (Central Daylight Time)

CREATE_COMPLETE buysell-20190715031528-storagebuysellstorage-CHG305SRYHWY AWS::CloudFormation::Stack Mon Jul 15 2019 03:16:56 GMT-0500 (Central Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE storagebuysellstorage AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:07 GMT-0500 (Central Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED   buysell-20190715031528-authcognito3619aa48-1CZ0NK1V2ZPUU AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:15 GMT-0500 (Central Daylight Time) The following resource(s) failed to create: [UserPoolClientLambda].
CREATE_FAILED   UserPoolClientLambda                                     AWS::Lambda::Function      Mon Jul 15 2019 03:17:14 GMT-0500 (Central Daylight Time) ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, nodejs8.10, python2.7, python3.6, python3.7.
CREATE_COMPLETE UserPoolClientRole                                       AWS::IAM::Role             Mon Jul 15 2019 03:17:11 GMT-0500 (Central Daylight Time)                                                      
- Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS buysell-20190715031528 AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:22 GMT-0500 (Central Daylight Time) The following resource(s) failed to create: [authcognito3619aa48].         
CREATE_FAILED               authcognito3619aa48    AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:21 GMT-0500 (Central Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:976999488553:stack/buysell-20190715031528-authcognito3619aa48-1CZ0NK1V2ZPUU/d386e2d0-a6d8-11e9-8adb-0a16600979f0 was not successfully created: The following resource(s) failed to create: [UserPoolClientLambda].
\ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS                           authcognito3619aa48    AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:30 GMT-0500 (Central Daylight Time)
DELETE_IN_PROGRESS                           storagebuysellstorage  AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:30 GMT-0500 (Central Daylight Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS buysell-20190715031528 AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:28 GMT-0500 (Central Daylight Time)
- Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS buysell-20190715031528-authcognito3619aa48-1CZ0NK1V2ZPUU AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:30 GMT-0500 (Central Daylight Time) User Initiated

DELETE_IN_PROGRESS buysell-20190715031528-storagebuysellstorage-CHG305SRYHWY AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:30 GMT-0500 (Central Daylight Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS UserPoolClient       AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:17:35 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    UserPoolClientRole   AWS::IAM::Role               Mon Jul 15 2019 03:17:34 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    UserPoolClientWeb    AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:17:33 GMT-0500 (Central Daylight Time)
DELETE_IN_PROGRESS UserPoolClientRole   AWS::IAM::Role               Mon Jul 15 2019 03:17:33 GMT-0500 (Central Daylight Time)
DELETE_IN_PROGRESS UserPoolClientWeb    AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:17:32 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    UserPoolClientLambda AWS::Lambda::Function        Mon Jul 15 2019 03:17:32 GMT-0500 (Central Daylight Time)

DELETE_COMPLETE    buysell-20190715031528-storagebuysellstorage-CHG305SRYHWY AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:34 GMT-0500 (Central Daylight Time)
DELETE_SKIPPED     S3Bucket                                                  AWS::S3::Bucket            Mon Jul 15 2019 03:17:34 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    S3AuthPolicyRW                                            AWS::IAM::Policy           Mon Jul 15 2019 03:17:33 GMT-0500 (Central Daylight Time)
DELETE_IN_PROGRESS S3AuthPolicyRW                                            AWS::IAM::Policy           Mon Jul 15 2019 03:17:32 GMT-0500 (Central Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS SNSRole        AWS::IAM::Role               Mon Jul 15 2019 03:17:40 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    UserPool       AWS::Cognito::UserPool       Mon Jul 15 2019 03:17:39 GMT-0500 (Central Daylight Time)
DELETE_IN_PROGRESS UserPool       AWS::Cognito::UserPool       Mon Jul 15 2019 03:17:37 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE    UserPoolClient AWS::Cognito::UserPoolClient Mon Jul 15 2019 03:17:37 GMT-0500 (Central Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE storagebuysellstorage AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:41 GMT-0500 (Central Daylight Time)
| Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE buysell-20190715031528-authcognito3619aa48-1CZ0NK1V2ZPUU AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:43 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE SNSRole                                                  AWS::IAM::Role             Mon Jul 15 2019 03:17:42 GMT-0500 (Central Daylight Time)
| Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE buysell-20190715031528 AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:53 GMT-0500 (Central Daylight Time)
DELETE_COMPLETE          authcognito3619aa48    AWS::CloudFormation::Stack Mon Jul 15 2019 03:17:52 GMT-0500 (Central Daylight Time)
- Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
\ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, nodejs8.10, python2.7, python3.6, python3.7.

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete

**Comment by UnleashedMind** [comment]
@DeniseJames 
I was not able to reproduce the error. 
What is the Amplify CLI version that you are using? 

Also please open this file: `<project-root>/amplify/backend/auth/<auth-resource-name>/xxxxxxx-cloudformation-template.yml` and search for `UserPoolClientLambda` and let us know what is the value for `Properties/Runtime`

**Comment by DeniseJames** [comment]
@UnleashedMind I created another cognito amplify app for another angular app and it worked fine. I have not checked to see if I inadvertenly changed doing this amplify install on another frontend app.

I am using amplify 1.1.7 version

Here are the properties runtime.

Properties:
      PolicyName: !Ref userpoolClientLogPolicy
      Roles: 
        - !If [ShouldNotCreateEnvResources, !Ref userpoolClientLambdaRole, !Join ['',[!Ref userpoolClientLambdaRole, '-', !Ref env]]]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: !Sub  
              - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
              - { region: !Ref "AWS::Region",  account: !Ref "AWS::AccountId", lambda: !Ref UserPoolClientLambda}
    DependsOn: UserPoolClientLambdaPolicy

**Comment by UnleashedMind** [comment]
Please get the latest version of the Amplify CLI 1.8.2
Amplify CLI works with node lts versions 8.16.0 and 10.16.0
