### ISSUE TITLE
"Runtime": "nodejs10.x" - external NPM Modules

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#1827]
Amplify 1.8.1
The new Runtime is now: "Runtime": "nodejs10.x"
After this update, i cant use loadash in the lambda functions.
Is this planed? Else its better to let it on 8.1 at first?

**Comment by UnleashedMind** [comment]
@davidbiller 
I guess you are referring to the functions category? 
We released an update to the CLI after Lambda started to support nodejs10.x
https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/
Following that, all the newly added functions category resource will have default runtime of nodejs10.x

**Comment by kaustavghosh06** [comment]
@davidbiller Node 10.16.0 is the LTS for NodeJS and is the recommended version to use even for Lambda. If you have your external dependencies which do not work with the LTS, then you can optionally change the Node versio in the cloudformation file located in `amplify/function/<name>-cloudformation-template.json`.

**Comment by davidbiller** [comment]
It is loadash. So I guess it should work. But not pre Installed?
