### ISSUE TITLE
How to allow API access for Unauthorized Users

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#1829]
** Which Category is your question related to? **
`Auth` & `API`

** What AWS Services are you utilizing? **
An app initialized via `Amplify init` and with provisioned `API`, Lambda function (REST/CRUD), and `DynamoDB` table via the `Amplify CLI`.  The site was then published by connecting to a repo via the `AWS Amplify Console`.

The API has been configured (via the CLI) to allow all access for authorized users and only GET for unauthorized users.

The basic thing I'm trying to allow GETs on the DynamoDB through the API Gateway for all users.  This **does** work for authorized users.  This **does not** work for unauthorized users.

I'm using Auth.signIn() and Auth.signOut() without `<Authenticator>`, which works (tokens are in local storage and the API returns data w/o errors,  though it throws an error even after a successful login:

```console
 Error: No credentials, applicationId or region
```
I've enabled CloudWatch logs for the API and I'm seeing:

```console
The client is not authorized to perform this operation.
```
I've checked the Identity Pool and see that `Enable access to unauthenticated identities` is enabled/checked.

I've checked the `unAuth` IAM role and the following policy is attached (I've x'd out stuff here), which looks correct:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "execute-api:Invoke"
            ],
            "Resource": [
                "arn:aws:execute-api:us-west-2:xxxxxxxxxxxx:xxxxxxxxxx/dev/GET/items/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

I feel like I'm either having a fundamental misunderstanding of how an unauthorized user should be able to access the API, or I'm missing some key step along the way.

Any advice would be appreciated.

Thanks.

**Comment by kaustavghosh06** [comment]
You can allow "Guest" or "Unauthenticated" users by updating your API backend using the CLI. Use `amplify update api` and in the CLI flow "Allow Guest users" to access the API.

**Comment by kimfucious** [comment]
Hi @kaustavghosh06 ,

Thanks for the follow-up.

I did do that on the initial setup of the API, but on your suggestion I ran the update on the applicable API path with the output below.

I did notice that the defaults for Auth and Guest users were already set to what I believe I set them to originally:  Auth with full access, and Guests with only read access, so there were no changes to push.

Regardless, what I wound up doing is changing my app structure so that the guest pages are accessing (S3) Storage directly and not using the API methods (for DynamoDB).  

This just kinda worked out in avoiding the whole issue.  If this problem comes up in another scenario, I'll open a new issue.

```console
? Please select from one of the below mentioned services REST 
? Please select the REST API you would want to update myAwesomeApi 
? What would you like to do Update path
? Please select the path you would want to edit /items 
? Provide a path (e.g., /items) /items    
? Choose a Lambda source Use a Lambda function already added in the current Amplify project 
? Choose the Lambda function to invoke by this path myAwesomeLambda 
? Restrict API access Yes
? Who should have access? Authenticated and Guest users
? What kind of access do you want for Authenticated users? (Press <space> to select, <a> to toggle all, <i> to invert selection)create, read, update, delete 
? What kind of access do you want for Guest users? (Press <space> to select, <a> to toggle all, <i> to invert selection)read 
```
