### ISSUE TITLE
Resolver not picking up Cognito user groups

### ISSUE THREAD

**Issue by conana** [aws-amplify/amplify-cli#183]
**Describe the bug**
Problem: Trying to use dynamic groups with @auth, the 'list' mutation returns no data.

**To Reproduce**
Using the default settings for Cognito User Pools as set up by amplify. Using the following model:

```
type TestAuth 
  @auth(rules: [
    {allow: groups, groupsField: "participants", mutations: [update, delete], queries: [get, list]} , 
    {allow: groups, groupsField: "watchers", mutations: [], queries: [get, list]}
  ])
  @model  
  {
    id: ID!
    content: String!
    participants: String
    watchers: String
  }
```

Amplify has generated the resolver for 'ListTestAuths' as follows:
```
## START: Filter Authorized Items. **
#set( $items = [] )
#foreach( $item in $ctx.result.items )
    #set( $isAuthorizedLocal = false )
      #set( $allowedGroups = $item.participants )
      #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isAuthorizedLocal = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isAuthorizedLocal = true )
      #end
    #end
  #end
    #set( $isAuthorizedLocal = false )
      #set( $allowedGroups = $item.watchers )
      #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isAuthorizedLocal = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isAuthorizedLocal = true )
      #end
    #end
  #end
  #if( $isAuthorized == true or $isAuthorizedLocal == true || $isAuthorized == true or $isAuthorizedLocal == true )
$util.qr($items.add($item))
  #end
#end
#set( $ctx.result.items = $items )
## END: Filter Authorized Items. **

$util.toJson($ctx.result)
```

Dynamo contains a single record as follows:

| "id (S)" | "__typename (S)" | "content (S)" | "createdAt (S)" | "participants (S)" | "updatedAt (S)" | "watchers (S)" |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| "af35f2fa-ba51-4a35-adc4-c70b92101e5b" | "TestAuth" | "foobie" | "2018-09-20T15:25:47.268Z" | "testauth-p-1" | "2018-09-20T15:25:47.268Z" | "testauth-w-1" |

The logged-in user is a member of both groups as confirmed in the Cognito UI:

> Groups | testauth-p-1 , testauth-w-1

Code to retrieve data in App.js as follows:

```
const listTestAuths = `query listTestAuth {
  listTestAuths{
    items {
      id
      content
      participants
      watchers
    }
  }
}`
...
  listTestAuths = async () => {
    console.log('listing test auths');
    const allTestAuths = await API.graphql(graphqlOperation(listTestAuths));
    alert(JSON.stringify(allTestAuths));
  }
```
1. Make a call to listTestAuths
2. Data returned is 
> {"data":{"listTestAuths":{"items":[]}}}

**Expected behavior**
The single TestAuth object should be returned.  I have not yet figured out how to debug resolvers to inspect the contents of `$userGroups` nor am I sure how/where it is set, but the results are consistent with it being empty.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 62
 - Amplify 0.1.19

**Additional context**
The [GraphQL Transform Tutorial](https://github.com/aws-amplify/amplify-cli/blob/master/graphql-transform-tutorial.md) states there is a 
>...currently a bug with the user pool creation. To make this work you need to have your own user pool and then pass the id via a CloudFormation parameter. The Amplify CLI user pool with the default setting doesn't work (a fix is in the works).

I couldn't locate a github issue for this bug. Could the problem be due to a Cognito config setting I can change?

**Comment by mikeparisstuff** [comment]
I will try to reproduce this and report back with what I find.
