### ISSUE TITLE
Using cognito through lambda (for listing users) across multiple amplify environments

### ISSUE THREAD

**Issue by bwobbones** [aws-amplify/amplify-cli#1831]
** Which Category is your question related to? **
 Amplify Functions and Auth

** What AWS Services are you utilizing? **
Cognito
Lambda
API Gateway

** Provide additional details e.g. code snippets **
I have created 3 environments using `amplify env` - development, test and production.  As expected this has created 3 cognito user pools and 3 functions, one for each environment.

I have a requirement to list the users in my cognito pool, using something like `cognitoidentityserviceprovider.listUsers` which requires that i set the userPoolId manually.  

Is there a way to get the userPoolId using the current amplify environment, or is the only way to send the userPoolId via the request from the front end?

**Comment by bwobbones** [comment]
Thanks, any idea of what the variable might be called?

**Comment by RossWilliams** [comment]
authcognito

> Thanks, any idea of what the variable might be called?
in your index.js file for the function at the top will be a comment with the variable name.
process.env.AUTH_COGNITO${PROJECT_NAME}_USERPOOLID

**Comment by kaustavghosh06** [comment]
@bwobbones We also append the env var names at the top of your function as comments. Also after you update your function to access these resources, we print out the process env names. Please feel free to respond on this thread if you need further help.

**Comment by bwobbones** [comment]
thanks @kaustavghosh06 i'll give that a try.
