### ISSUE TITLE
Custom domain with OAuth flow?

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-cli#1834]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I have a successful OAuth flow working, however, when going through the flow with Google it is showing, do you want to authorize amazoncognito.com, instead of my domain name. I tried using the CLI "amplify auth update" but that doesn't let me specify a custom domain. Is there a way to specify that custom domain outside of manually in the AWS console?

**Comment by cliffordh** [comment]
I do get prompted for a "name", but it's not a domain name, the CLI makes the OAuth endpoint something like "mysite-beta.auth.us-east-1.amazoncognito.com". I would prefer instead to simply have "auth.mysite.com". I can only do that by manually configuring awsexports and setting the custom domain in Cognito.

**Comment by cliffordh** [comment]
This temporary workaround will allow me to not lose updates to aws_exports:

import aws_exports from '@/aws-exports'

var my_exports = JSON.parse(JSON.stringify(aws_exports))
my_exports.oauth.domain = 'https://auth.mysite.com'
Amplify.configure(my_exports)

Testing this, but I believe this will work.

**Comment by kaustavghosh06** [comment]
@cliffordh Unfortunately, Cognito appends the "auth.us-east-1.amazoncognito.com" domain to your provided domain name - which is the behavior on the cognito console as well.
