### ISSUE TITLE
Change Sorting Direction for Score (Int) with @Key  

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#1836]
** Which Category is your question related to? **
@Key Sorting Direction

** What AWS Services are you utilizing? **
Amplify CLI - AppSync - DynamoDB

** Provide additional details e.g. code snippets **

I try to use @key to sort for ByOwnerByDecisionByScore

```graphql
type Careerinteract @model @auth(rules: [{ allow: owner }]) @key(name: "ByOwnerByDecisionByScore", fields: ["owner", "decision", "score"], queryField: "careerInteractByOwnerByDecisionByScore") {
  id: ID!
  owner: String!
  decision: Int
  createdAt: String
  updatedAt: String
}
```

than i use it like this:
```js
await query("careerInteractByOwnerByDecisionByScore", {
      owner: UserStore.userID,
      decisionScore: { gt: { decision: 1, score: 1 } }
    });
```

So now i get all my own, and only with decison: 1 and all interacts with more than score: 1. in this order:
1, 2, 3...

What i try to do is: 

get all interacts with decison: 1 and sorted for score. DESC like 100, 99, 88...

I guess this is the same Request:
https://github.com/aws-amplify/amplify-cli/issues/1629

Update: I Added now the "scanIndexForward": false to the Resolver. Works.

**Comment by attilah** [comment]
@davidbiller `@key` now supports `sortDirection` when 2 or more fields are specified in the directive.

**Comment by ivenxu** [comment]
> `sortDirection`

@attilah , could you please direct the doc how to apply the sortDirection  on @key?

**Comment by thomasklein-winemaker** [comment]
Hi @attilah!

I tried
```
@key(name: "someName", fields: ["someField, "createdAt"], sortDirection: "DESC")

=> Error: Unknown argument "sortDirection" on directive "@key".
```
and just in case
```
@connection(keyName: "someName", fields: ["id"], sortDirection: "DESC")

=> 
Error: Unknown argument "sortDirection" on directive "@connection".
```

I noticed that the schema itself does mention the `sortDirection` on the generated connection. However, I'm not sure how to use that in a Query.

```
type MyType {
   id
...
   someField(createdAt: ModelStringKeyConditionInput, filter: ModelSomeFieldFilterFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelSomeFieldConnection
}
```

both error that the `sortDirection` is not supported (version 4.27.3)
