### ISSUE TITLE
Pre-push hook for plugins to build resources.

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#1837]
**Is your feature request related to a problem? Please describe.**
When developing plugins for Amplify, most CloudFormation stacks are nested CloudFormation stacks and you want to be able to push updates that happen any of the supporting CloudFormation stacks. This could be anything from changing a GraphQL schema, to a Swagger file for API gateway, a lambda function zip, or just a video config file.

**Describe the solution you'd like**
I would like to move away from this idea for pushing resources [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/lib/push-resources.js#L41). This is not only not scalable as you guys write more plugins for the native CLI, it also adds a lot of unnecessary steps to the push function. 

My proposed solution is to follow the same model developed for post push hooks [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/extensions/amplify-helpers/on-category-outputs-change.js#L32). The only difference between these two would be to keep the pre-hooks in the provider.

Another benefit for doing this, is if/when another provider is release, then you wouldn't have to duplicate extra code as it would live in the plugin itself.

**Describe alternatives you've considered**
Provide a warning with the post-hook that the push didn't change anything and the should use the unique plugin push code.

**Additional context**
Semi-related to: #1146 but with a proposed solution, more use cases, and more distinct wording. (not related to scripting as well).

**Comment by kaustavghosh06** [comment]
@wizage With the new plugin system, you can now have a plugin and have a pre-push event hook for it :D
