### ISSUE TITLE
Lambda Trigger support for Auth - not all triggers listed in CLI

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-cli#1838]
** Which Category is your question related to? **
amplify auth add/update - lambda triggers for Cognito
** What AWS Services are you utilizing? **
auth
** Provide additional details e.g. code snippets **

Just saw [this blog post](https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/) about amplify cli now supporting auth lambda triggers. I've installed the latest cli version (1.8.1) and when i run `amplify auth update` under `Which triggers do you want to enable for Cognito` these are the only options I see: Create Auth Challenge, Custom Message, Define Auth Challenge, Post Authentication, Post Confirmation, Pre Sign-up, and Verify Auth Challenge Response.

In the developer guide section about [lambda triggers for user pool workflows](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) there are several more options listed, including Pre Authentication. Is there a plan to add support for these other triggers to the CLI? Or is there some reason why I'm not seeing these other triggers when I run `amplify auth update`?

**Comment by kaustavghosh06** [comment]
We've merged a fix for this - #1843. This will be part of our next npm release.
