### ISSUE TITLE
No way to set Pre-Token trigger function for Cognito through Amplify / Cloudformation

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1844]
**Is your feature request related to a problem? Please describe.**
I see Amplify CLI now has official support for Cognito Triggers. Great. However, Cognito for whatever reason still does not support adding a pre-token trigger through cloudformation. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html and https://forums.aws.amazon.com/thread.jspa?threadID=268907. 

This limits ability to use Amplify CLI to configure this trigger. 

**Describe alternatives you've considered**
Manually setting this trigger through Cognito console. 

**Additional context**
I realize this limitation is not a limitation of Amplify CLI but Cognito. Still, it should be in Amplify CLI team's interest to push the Cognito team to add setting this trigger via Cloudformation. I don't understand why they have not done that yet since this has been requested since 2017 - see https://forums.aws.amazon.com/thread.jspa?threadID=268907

**Comment by hisham** [comment]
To add more context - this type of trigger is handy when trying to use the graphql's transformer's group authentication, seehttps://github.com/aws-amplify/amplify-cli/issues/1575

**Comment by kaustavghosh06** [comment]
Yes, there are two triggers - "PreToken Generatio" and "Migrate User" which are not currently supported by Cognito Clooudformation and we'll work with them to get a timeline/solution on this.

**Comment by ricklove** [comment]
This seems to be supported by cloud formation now:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html

Unfortunately, I haven't worked with cloud formation directly (I have been using the amplify cli).

@hisham Do you know how to set this up in an amplify-cli generated project?

**Comment by ricklove** [comment]
I am trying to add this to support multi-tenant data within an amplify-cli project.

**Comment by ricklove** [comment]
@haverchuck How do you use this with amplify-cli?

**Comment by kaustavghosh06** [comment]
@hisham I beleive we have the pre-token generation option for the auth trigger a s apart of the amplify add/update auth CLI flow which was merged as a part of #2126
