### ISSUE TITLE
How to stream video, but only to authenticated users?

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#1849]
**Which Category is your question related to?**

I've seen this blog: https://aws.amazon.com/blogs/media/introducing_aws_amplify_video/

There it's described that both live and on demand video streaming is now possible in Amplify. 

My questions are:

1) I have a large number of videos and I'm looking to control access per video to specific users (which are Cognito users). Video's should not be publically available in any way.

2) How do I do a live streaming session, and again only to authenticated users?

**Background:** We're building a membership portal with learning videos where only paid users can access the content. If they leave their membership and in some way have gotten the direct link to the stored video (view source for example), how can I prevent that they won't be able to access it?

**What AWS Services are you utilizing?**

Amplify with Cognito, AppSync, DynamoDB etc.

**Comment by UnleashedMind** [comment]
To the Amplify CLI, the amplify video is a third party plugin, you can directly post issues on their github repo

https://github.com/awslabs/amplify-video

**Comment by houmark** [comment]
Thanks, sometimes it can be hard to figure out where something is being done in AWS land... I found an existing ticket over there for this exact request, bud sadly this is not yet possible and there doesn't seem to be a timeline on when that will be.
