### ISSUE TITLE
Template may not exceed 460800 bytes in size.

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-cli#185]
**Describe the bug**
Template may not exceed 460800 bytes in size.

Template is autogenerated and the size is 523Kb.

**Expected behavior**
if generated code exceeding the limit, it should be divided to sub-stack.

If you have some solution, please share.

**Comment by JustFly1984** [comment]
Thank you! This is amazing news!!! We are screwed with our current project implementation development, and can't deploy to production new features since last week, cos our project www.agrariansupply.com is developing at fast pace. Please post any news as soon as it possible to use amplify-cli again.

Thank you for your work, it really improves our development workflow.

**Comment by JustFly1984** [comment]
Is there any update?

**Comment by JustFly1984** [comment]
Any news?

**Comment by JustFly1984** [comment]
Hey guys, why is it taking so long?

**Comment by kunwarVivek** [comment]
Hi,
any updates on this issue. Is there any workaround for this problem.

**Comment by JustFly1984** [comment]
@ kunwarVivek  
We are using lambdas with graphql resolvers to DynamoDB instead of Amplify as workaround.

**Comment by JustFly1984** [comment]
I feel like AWS spending not enough for open-source support (((

**Comment by kaustavghosh06** [comment]
@JustFly1984 We’re actively working to support this currently. We have a design for this and have started work on it but it’s notboeiduction ready yet.

**Comment by kunwarVivek** [comment]
Team,

Atleast suggest a workaround.

We have not more than 12-15 tables with couple of 1 to many relationships
and we are stuck.

Regards
Kunwar
+91-9980915147

**Comment by darrylmack** [comment]
Any news on this? Stuck in an app with 20 tables and 8 have one-to-many relationships.

**Comment by darrylmack** [comment]
@kaustavghosh06 In the interim, is there a workaround. Splitting the CloudFormation templates doesn't seem possible as the cli generates the template. Is it possible to generate the template with fewer tables. and then edit the schema directly in the AWS console?

Or will that overwrite the local schema.graphql on next amplify push?

**Comment by kaustavghosh06** [comment]
@darrylmack We're still working on this as the solution for this isn't trivial.
For the interim, you could create the API on the Appsync console, using the contents present in amplify/api/<api-name>/build/ directory and then could probably do a codegen on that API using the
`amplify add codegen --apiId XXXXXX`. This also adds the appsync API to your aws_exports.js file which would be accessible by your frontend code via the AWS Amplify JS lib.

**Comment by kunwarVivek** [comment]
Hi,

Will " amplify add codegen " create the corresponding dynamodb tables and
roles that are required to access the tables .

Regards
Kunwar
+91-9980915147

**Comment by afuyo** [comment]
Hi
``` 
amplify add codegen --apiId XXXXX
```   generates invalid subcommand. Is this a valid command?

**Comment by rajababu3** [comment]
Hi, 
Is there any update for this issue? 
How long will this take ?

**Comment by aireater** [comment]
@kaustavghosh06 I updated the schema in AppSync console. 

When I run: ```amplify add codegen --apiId modernapp``` I get the following error: ```Codegen support only one GraphQL API per project```

How do I get around this?

**Comment by chasen** [comment]
I am having this issue as well, i saw in another post that the auto-generated template uses pretty print for the json output making my template file. 959KB however just minifying(removing the whitespace) reduces that size to 207KB under the max size. 

Maybe while you work on fixing the issue you could release a stop gap version that used a minified json file?

**Comment by JustFly1984** [comment]
Is there any update? It is been 3 months since I opened an issue.

**Comment by stanleycyang** [comment]
Yeah would love to see at least a workaround on this issue. Just completely blocked

**Comment by randallprince** [comment]
Started using AppSync a week or so ago. Finalized my tables yesterday and then this pops up. It would be nice to have an ETA or some help on the creation of the DynamoDB tables as though I have the schema setup now, I can't actually do anything since the tables still need to be built. I'm going to try @chasen 's solution as that seems pretty reasonable at the moment. Thanks guys!

**Comment by randallprince** [comment]
Actually just tried the manual compression to no avail. Opened up CloudFormation and the CloudFormation Designer on the failed process, replaced the template with the minified JSON file, but after trying to run it, during validation I get the following error: 

> Template is not valid: Template format error: Number of resources, 203, is greater than maximum allowed, 200

So, the file size seems to be somewhat related to how resources are limited. Now to look around and see if it's possible to maximum resource ceiling manually.

Hopefully, someone who might be slightly closer to the limit might be able to move past this error. Good luck!

**Comment by stanleycyang** [comment]
@JustFly1984 we ended up just having to write our own resolvers and connect our databases, which sucks but it is what it is. Hope that helps you move forward

**Comment by JustFly1984** [comment]
@stanleycyang We are ended up pretty the same destination. That is sucks that tool like this promises gold, but provides copper in best case scenario.

**Comment by undefobj** [comment]
@JustFly1984 @stanleycyang @randallprince @chasen @rajababu3 @darrylmack @kunwarVivek @christianto88 

We are very close to implementing a solution for this. Unfortunately it was a very complex problem to resolve and implement stack and template partitioning in the core deployment processes of the transformer. We also have a custom resolvers solution as well which will let you override both GraphQL fields and templates as well as implement your own CloudFormation overrides. If you could keep an eye on this PR: https://github.com/aws-amplify/amplify-cli/pull/581 and help test it out to validate the solution that will help us release faster. We're trying our best to get this out in the coming weeks.

**Comment by nagey** [comment]
would be really great to get a solution to this published.

**Comment by ffabinhoo** [comment]
I am having the same problem. Any update on this matter?

**Comment by stanleycyang** [comment]
Looks like they [merged](https://github.com/aws-amplify/amplify-cli/pull/581) the branch to amplify/multienv now!

**Comment by kaustavghosh06** [comment]
Hey guys,
The fix for this has been merged to the main cli verison. Please use `npm install -g @aws-amplify/cli` to install the latest version of the CLI.

**Comment by meetrij** [comment]
@kaustavghosh06 not working with cli version update

**Comment by kaustavghosh06** [comment]
@meetrij What does your schema look like? Interested in knowing the number of models and number of connections in your annotated schema.

**Comment by lr001dev** [comment]
So, I updated my cli and I'm getting this error:

`AWS::CloudFormation::Stack Wed Oct 14 2020 00:02:12 GMT-0700 (Pacific Daylight Time) Template
 may not exceed 468992 bytes in size.`

My api-cloudformation.json is breaking the limit, so not sure how to fix this....
