### ISSUE TITLE
How Can I Apply environment changes to different environment or switch without apply the changes

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#1855]
** Which Category is your question related to? **
multiple environments 

** What AWS Services are you utilizing? **
Cognito, Appysnc, API Gateway, Lambda

** Provide additional details e.g. code snippets **
Let's say 
1. Master environment starts with simple API Gateway
2. Create a Dev environment from Master and add more categories in Dev environment
3. Now want to apply the same changes that done in Dev to the Master 

What is the best/recommended approach to do this?

**Comment by UnleashedMind** [comment]
Yes
Using your example, just run `amplify env checkout Master` from the Dev env, and your Master env will have the newly added categories locally, then run `amplify push` to create them in the AWS.
Just remember each env has its own set of backend resources.

**Comment by monaye** [comment]
@UnleashedMind 
I was able to merge the changes to Master from Dev. 
I actually saw some mentioning about `checkout` but I always had in mind that `checkout` is more like switching and didn't think that it will merge. looking at the document also wasn't clear. 
Anywhere, thank you for your help.

**Comment by monaye** [comment]
@UnleashedMind 
 How can I switch to different env without applying the changes in current env?

**Comment by monaye** [comment]
I guess this will do the trick 😉 
https://github.com/aws-amplify/amplify-cli/issues/1862#issuecomment-513025583
