### ISSUE TITLE
How to run a Lambda function locally that accesses protected resources?

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1860]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
Lambda, AppSync, Cognito
** Provide additional details e.g. code snippets **
I'm still learning to use AWS Lambda functions. I generated mine using the Amplify framework. The Lambda function I use needs to access an AppSync API. Therefore it has the following express middleware:

```js
const tapRoute = f => R.tap(route => route.use(f));

const hydrateClient = tapRoute(async function(req, res, next) {
  try {
    const url = process.env.API_SAYMAPPSYNCAPI_GRAPHQLAPIENDPOINTOUTPUT;
    const region = process.env.REGION;
    AWS.config.update({
      region,
      credentials: new AWS.Credentials(
        process.env.AWS_ACCESS_KEY_ID,
        process.env.AWS_SECRET_ACCESS_KEY,
        process.env.AWS_SESSION_TOKEN
      ),
    });
    const credentials = AWS.config.credentials;
    const appsyncClient = new AWSAppSyncClient(
      {
        url,
        region,
        auth: {
          type: 'AWS_IAM',
          credentials,
        },
        disableOffline: true,
      },
      {
        defaultOptions: {
          query: {
            fetchPolicy: 'network-only',
            errorPolicy: 'all',
          },
        },
      }
    );
    const client = await appsyncClient.hydrated();
    req.client = client;
    next();
  } catch (error) {
    console.log(error);
    next(error);
  }
});
```

As you can see I need to access the environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`. When I run the function in the cloud, it automatically gets the values for these variables. How can I get them locally? Which access key do I need to use and how do I get its secret access key and the session token? 

To run the function locally I use `amplify function invoke <name-of-function>`.

**Comment by UnleashedMind** [comment]
@janhesters 

1. Login to AWS and Navigate to the IAM console, https://console.aws.amazon.com/iam/home#/home
2. On the left pane, select `Users`
3. In the `Users` console, select or add an user with proper settings, e.g. Access type is `Programmatic access` and permission is `AdministratorAccess` or other appropriate access level suitable for your app. 
4. Choose `Security credentials` -> `Create access key` to get the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, you don't need to `AWS_SESSION_TOKEN` if you are not assuming roles and using temp credentials.
5. In your local dev computer, export those as environment variables

**Comment by kaustavghosh06** [comment]
You can set these access key and secret keys as environment variables in your local system.

**Comment by janhesters** [comment]
@UnleashedMind Thank you.
