### ISSUE TITLE
auth add on Windows 10 command line not completing

### ISSUE THREAD

**Issue by rscott14** [aws-amplify/amplify-cli#1861]
**Describe the bug**
When running `amplify auth add` on windows 10 command line (cmd.exe) the execution suddenly ends after selecting any of the available configuration options.  The result is that you are kicked back out to the terminal prompt.  I have found no way around this to install auth config on windows 10.

**To Reproduce**
1. `amplify init`
2. `amplify auth add`
3. select - Default Configuration (any option selected has same results)

**Expected behavior**
For the "Default Configuration" I would expect to be able to continue with the auth setup to completion.  This has worked fine in prior versions of the cli.

**Screenshots**
*Notice how the next option selection shows up but then kicks out to the command prompt. Any of the options chosen has the same result.
![image](https://user-images.githubusercontent.com/12652486/61466011-2892eb00-a947-11e9-915a-b9db3aa87d02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- node version: v10.9.0
- npm version: 6.2.0
- amplify version: 1.8.2

**Additional context**
`amplify hosting add` works fine

**Comment by haverchuck** [comment]
@rscott14 I've reproduced this issue on node v.10.9.0, but the behavior seems correct on 10.16.0 (their latest stable, I believe) as well as 12.0.0.  We will continue looking into this issue, but in the meantime you could try using one of those versions of node?

**Comment by rscott14** [comment]
@haverchuck I've updated the node version to 12.6 and no longer see the issue.  Updating did the trick. Thanks!
