### ISSUE TITLE
How can I create a new environment based off of another env. 

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#1862]
** Which Category is your question related to? **
multi-environment 

** What AWS Services are you utilizing? **
Cognito, AppSync/Dynamo, Elasticsearch, Lambda 

** Provide additional details e.g. code snippets **
Let's say I have two env, `DEV`, `FEATURE1`.  
If I am currently in `FEATURE1`, but want to create a `FEATURE2` env based on `DEV`. What would be the workflow? (**notes: there are Category changes in FEATURE1 that are not ready**)

**Comment by nino-moreton** [comment]
Wouldn't you just create a git branch from DEV named FEATURE2 and create an amplify env on that branch?

**Comment by monaye** [comment]
as far as I know when you run `amplify add env` it will create an environment based off of your current env.  
so, creating the branch from Dev and run `amplify add env` doesn't give you the stacks from `DEV` but `FEATURE1`.

**Comment by UnleashedMind** [comment]
@monaye 

1.  from FEATURE1, run `amplify env checkout DEV`
2. now you are in DEV, run `amplify env pull --restore` to shake off the new features from FEATURE1
3. run `amplify env add FEATURE2`
