### ISSUE TITLE
My app has an extreme amount of AWS Key Management requests

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-cli#1867]
Last week I deployed my app to public for the first time without promoting it yet.
So we test the app with approx 4 users, but I'm worried about the costs I already see in my AWS dashboard. So when the app scales we probably are not gonna make it financial wise.

Can we implement better cache structure? The answer is yes, but still the amount of AWS Key Management request is already at 50k+ for this month (halfway Juli)
This is the only free tier metric in red, so assume my costs is vaporized here.

My schema is as follows and we use `CreateSwipe` and `GetGroupSwipes` the most in our app.

```
type Ingredient
{
  amount: String
  name: String
  unit: String
}

type Recipe 
  @model
  @key(name: "ByWeek", fields: ["weeknumber"], queryField: "recipiesByWeek") 
{
  id: ID!
  title: String
  key: String
  image: String
  numberOfPersons: Int
  courses: [String]
  time: String
  energy: String
  proteine: String
  carbohydrates: String
  fat: String
  saturatedFat: String
  fibers: String
  salt: String
  sugar: String
  recipeTypes: [String]
  specials: [String]
  containsProducts: [String]
  diet: [String]
  ingredients: [Ingredient]
  preperation: [String]
  editDate: String
  menuSuggestion: String
  weeknumber: Int!
}

type Swipe
  @model
{
  id: ID!
  owner: String
  recipe: Recipe! @connection
  liked: Boolean!
  group: Group @connection(name: "GroupSwipes")
  timestamp: AWSDateTime
}

type Group
  @model
 {
  id: ID!
  owner: String
  groupname: String!
  groupcode: String!
  swipes: [Swipe] @connection(name: "GroupSwipes")
}

type Schedule
  @model
  @key(name: "ByGroup", fields: ["groupId"], queryField: "schedulesByGroup")
{
  id: ID!
  recipe: Recipe! @connection
  groupId: ID!
  cookdate: AWSDateTime
  timestamp: AWSDateTime
}
```

I think it has to do with nested queries during `GroupSwipes` but I can not pinpoint the issue yet.
I'm around $2.73 per active user, so I have to find the issue.

I use the automatic generated API functions generated with `amplify codegen --max-depth 5`
These are returning more data back then I needed, but reducing this will not reduce the amount of requests

**Comment by houmark** [comment]
I'm also seeing high usage of a recently released web app in relation to KMS. This could also be a high cost and a blocker for us as the web app will be released to external users.

Understanding why there's such a high amount of KMS requests would be a nice first phase, but it seems like a bug that KMS is being called as much for farily low traffic applications. Our web app went into production and is used by a few users since a few weeks back and this month we are forecasted to have ~33k KMS requests. That's almost more or around the number of API call requests I'm estimating we are doing this month?!

**Comment by davidbiller** [comment]
Do you use Lambda Functions?

**Comment by kaustavghosh06** [comment]
@sprucify Do you use KMS for storing your keys/env-vars in the lambda function resolvers?

**Comment by davidbiller** [comment]
> @sprucify Do you use KMS for storing your keys/env-vars in the lambda function resolvers?

Is this the standard setup if we add api access to the lambda from the cli?

**Comment by kaustavghosh06** [comment]
@davidbiller No

**Comment by sprucify** [comment]
> @sprucify Do you use KMS for storing your keys/env-vars in the lambda function resolvers?

I don't know.
Just basic `ampliy push` and `amplify codegen`
Nothing chanced manually as far as I know.

How can I check this?

**Comment by sprucify** [comment]
My Cloudwatch shows `consumedwritecapacityunits` errors and most of my costs are because of setting the provisioning units higher.

So simple queries causes many (nested) requests, at least that's what I think is happening

**Comment by ErickTamayo** [comment]
I started developing an app a month ago, I only have 2 tables and checking the free tier consumption, I already consumed 20k requests! note: I'm developing this all by myself.

![image](https://user-images.githubusercontent.com/4788817/61727211-23abae00-ad30-11e9-8ce4-888100699cef.png)

**Comment by nikhil-dabhade** [comment]
@sprucify @houmark @ErickTamayo We did a deep dive on the details you provided and wanted to share the observations and next steps.

Amplify CLI enables the server side encryption, as a best practice, with a configurable custom KMS key generated for you when using REST with DynamoDB. This means that every API call that you are making is invoking KMS keys to encrypt/decrypt your DynamoDB data. We completely understand the value in making this a configurable option and have started the work on this right away. It has dependencies on the CloudFormation service team and we are working with them to get in this in as soon as possible in the coming days. In the meantime, an approach to change this behavior immediately at your end would be to configure your setup to use using the following steps:
 
1. Go to your DynamoDB tables on the AWS Console which are provisioned by the CLI as a part of your GraphQL API. 
2. In the Overview tab, as shown in the image below, select the “Manage Encryption” options, and select the “Default” option in the modal which opens up.

 
![image](https://user-images.githubusercontent.com/16342547/61907272-01f22880-aee2-11e9-876a-a4ba63c259e6.png)


This will disable the use of custom KMS keys and potentially address the costs concerns, while still keeping the server-side encryption intact without using a custom KMS key. This value will not be overwritten on the next 'amplify push'.

In addition, the CLI version 1.8.4 does not have the custom KMS key configured as default when creating new API’s. It uses an AWS owned CMK which keeps the encryption at rest intact.
Once we have the fixes from Cloudformation team, which makes this item configurable, you can switch to the new CLI, opt out of using a custom KMS key for DynamoDB encryption and continue using the original backend. 

Hope this helps.

**Comment by houmark** [comment]
Thank you @nikhil-dabhade. That's great news and thanks for the very prompt reaction to this issue.

I'm left with a few questions, that maybe you can clarify:

- Changing the configuration in the DynamoDB console has no downtime or any other issues related from client side? Good to know to make sure we can take pre-cautions when doing this change
- Is this not affecting GraphQL frontends at all? I read it's only related to REST end points. Or is this REST between GraphQL resolvers and DynamoDB?
- Once the CLI has this feature fully integrated, we should update the Storage to have the same setting locally as we set in DynamoDB for consistency, so it would be important that this configuration is also possible to do in the CLI by updating the storage configuration and not just when creating a new one.

**Comment by sprucify** [comment]
Thanks a lot @nikhil-dabhade to dive into this issue.
I set all my tables to Default CMK.
I will update the results in costs reduction here soon

**Comment by tgjorgoski** [comment]
any news on this?

**Comment by houmark** [comment]
I think it defaults to the default now, but unfortunately, when I add a new model/collection in DynamoDB it's still defaulting to KMS because it seems like I'm locked into the old way of doing it. Too early to tell for us if this lowered the request amount, but have a hunch that it did.

**Comment by tgjorgoski** [comment]
Ah, OK, I don't know what the defaults are, but  I changed the parameter according to PR #1887 , and then provisioned a new environment , and the tables were not using KMS.

**Comment by houmark** [comment]
@tgjorgoski Nice, I had missed that one-liner. Will try adding it to see if my next model comes out as default without provisioning a new environment.

**Comment by houmark** [comment]
Actually, I did see this a while back and the reason for not trying it out is the requirement to create a new environment before adding it. I don't need a new environment, I need the ones I have fixed. I guess I have to live with manually changing KMS on new DynamoDB tables in the future.

**Comment by undefobj** [comment]
Hello I believe this issue was resolve with an update last year. Please let us know if  you are still seeing issues.
