### ISSUE TITLE
deleted appsync data still being returned by amplify api call

### ISSUE THREAD

**Issue by klaop57** [aws-amplify/amplify-cli#1868]
** Which Category is your question related to? **
amplify api

** What AWS Services are you utilizing? **
appsync one-to-many sample with 1 added type: User

** Provide additional details e.g. code snippets **
amplfy version I'm using = `1.1.28`

I am developing an Expo (React Native) app.
Inside my main `<App />` component, inside `componentDidMount`, I perform the following:

```js
const foundUser = await appsyncClient.query({
  query: gql(queries.getUserByOwner)
  variables: { owner: user_id },
});
if (!foundUser.data.getUserByOwner.items.length) {
  console.log('appsync user does not exist');
} else {
  console.log(`appsync user exists, dynamodb user.id = ${foundUser.data.getUserByOwner.items[0].id}`);
}
```

So now I've updated my `schema.graphql` and did `amplify remove api` + `amplify push` (i did it this way since simply pushing the updated schema lead to some errors, this happens quite often).

So all dynamodb tables were deleted and recreated, and are now thus empty. Still, the above code will return me a very old response. I am puzzled as to how this can happen as **that dynamodb table + data was deleted, when looking in dynamodb in aws console, I can see all tables are empty!**

Also restarting Expo on my phone etc. didn't resolve the problem.

Is there something I need to do to "flush" old data? or maybe some option to amplify to disable caching?

**Comment by kaustavghosh06** [comment]
@klaop57 Can you run `amplify console api` to check the data-sources connected to your API? I'm wondering if this is the the data returned from the on-device/browser cache? Did you try clearing your local cahce?

**Comment by klaop57** [comment]
@kaustavghosh06 thanks for your suggestions.

## on-device cache
I've emptied `expo` cache by doing `expo r -c` as described [here](https://stackoverflow.com/questions/51998636/how-can-i-clean-reset-cache-of-react-native-using-expo-not-sure-if-it-is-cach), still the same issue though.

## connected Data Source
So I've ran `amplify console api`, and I end up at the appsync page, if I check the Data Sources, click on the User Table, I get a user table which is empty (which is expected since I `amplify remove api` followed by `amplify add api`). 

## caching issue on AWS side?
Also I've not worked on this during the last 2+ days so if it was a caching issue on AWS side it should by now have been gone, which it isn't.

# Conclusion
I still have the same problem, I get a User table "user" returned, even though the dynamodb table is empty..

so the code I exec is:

```js
const user_id = (await Auth.currentAuthenticatedUser()).attributes.sub;

const foundUser = await appsyncClient.query({
  query: gql(queries.getUserByOwner),
  variables: { owner: user_id },
});
```

**Comment by kaustavghosh06** [comment]
@klaop57 Are you still able to get the data from your API?

**Comment by klaop57** [comment]
So I managed to solve it by:
1. save the `schema.graphql` file of the api
2. `amplify remove api`
3. then renaming the query (since it was a `queryField` query)
4. `amplify add api`, pasting in the original schema from step 1 as schema
5. `amplify push`

what exactly was causing it is still a mystery to me

**Comment by kaustavghosh06** [comment]
@klaop57 This seems like a momentary service issue. Please let me know if you're still seeing this.

**Comment by amin79** [comment]
@klaop57 I have the same problem. Could you please let e know what should I do?

**Comment by JECamachoR** [comment]
I am having the exact same problem.

**Comment by amin79** [comment]
@JECamachoR did you try Datastore.clear() ?
