### ISSUE TITLE
How does one overwrite an auto-generated resolver with a pipeline resolver

### ISSUE THREAD

**Issue by youjinphea** [aws-amplify/amplify-cli#1871]
**Which Category is your question related to?**
amplify api

**What AWS Services are you utilizing?**
AppSync with @key directive

**Provide additional details e.g. code snippets**
I have the following schema
```graphql
type A
  @model(queries: null, mutations: null)
  @key(
    name: "ByBbyC"
    fields: ["id", "status", "createdAt"]
    queryField: "AbyBbyC"
  ) {
  id: ID
  status: Status!
  createdAt: String
}
```

and I'm trying to attach a custom pipeline resolver to the query `AbyBbyC` in the stack under `stacks/`
```json
"OrdersByRestaurantByStatusResolver": {
  "..."
  "Type": "AWS::AppSync::Resolver",
  "Properties": {
    "..."
    "Kind": "PIPELINE",
    "TypeName": "Query",
    "FieldName": "AbyBbyC",
  }
}
```

I get the following error after doing an `amplify push`
```
Resource Name: OrdersByRestaurantByStatusResolver (AWS::AppSync::Resolver)
Event Type: create
Reason: Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: xxx)
```

Thanks

**Comment by mikeparisstuff** [comment]
@youjinphea We have an item in the backlog to provide a more generalized solution to adding pipeline resolvers from within the Amplify CLI that would cover use cases like this. In the meantime, you are able to implement this yourself using [custom resolvers](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers). To do this:

1. Copy the content of the `Query.AbyBbyC.req/req.vtl` from `build/` into `resolvers`.
2. Remove `queryField: "AbyBbyC"` from `@key` to stop that from being auto-generated.
3. Run `amplify push`.
4. Add the `AWS::AppSync::FunctionConfiguration` resources to the custom stack.
5. Add the pipeline `AWS::AppSync::Resolver` to a custom stack that references the FunctionConfiguration resources.

**Comment by youjinphea** [comment]
Awesome. That works, thank you!

**Comment by idanlo** [comment]
@mikeparisstuff can you please explain or link a resource explaining how to do this? I didn't completely understand what you are trying to say - first of all I don't know how to do step 4 and 5, and after doing those how do I add the functions and set the order of calling them (like creating a pipeline resolver from the AppSync console)

**Comment by c0dingarchit3ct** [comment]
Just an fyi, the normal 'override' is not working 10 months after announcement still, I have the details in #3002

**Comment by andriworld** [comment]
As @c0dingarchit3ct confirmed in #3002, it works now just by creating an override copy of the .vtl file from `build/resolvers/` into `resolvers/` and pushing.
