### ISSUE TITLE
Amplify init command freezes after I select default editor: Visual Studio Code

### ISSUE THREAD

**Issue by GIOkafor** [aws-amplify/amplify-cli#1882]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
When I try initializing amplify in my Angular 7 project using the command `amplify init` it starts up the process and asks me for my default editor. Once I select Visual Studio Code, the process freezes. 

I've tried letting it run for hours but it doesn't get past that screen. 

Also tried downgrading from 1.8.2 to 1.7.5 but the same thing happens.

Also tried selecting other text editors but still no luck.

**To Reproduce**
1. Initialize new angular project `ng new appName`
2. Install @aws-amplify/cli `npm install @aws-amplify/cli`
3. Run `amplify configure`
4. Run `amplify init`
5. Select text editor
6. See error

**Expected behavior**
Was expecting it to initialize amplify and generate a aws-exports.js file

**Screenshots**
![image](https://user-images.githubusercontent.com/7291283/61711097-42ef0f00-ad21-11e9-8f38-1419f8d4ab1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.142

**Additional context**
- Node version v10.16.0
- Npm version 6.9.0
- Angular CLI 7.2.4
- Angular 7.2.15

**Comment by GIOkafor** [comment]
Just tested this on a different computer and everything works as it should, don't know if it only happens when you re-install the aws amplify CLI on a machine that already had it installed.

**Comment by UnleashedMind** [comment]
@GIOkafor 
Seems like one of the inquirer (one of the Amplify CLI dependencies) issues that once popped up
https://github.com/aws-amplify/amplify-cli/issues/1688
I'd suggest to remove Amplify CLI completely from the original computer, reinstall and try again.

**Comment by GIOkafor** [comment]
I did so by running `npm uninstall -g @aws-amplify/cli` from an admin console. It ran successfully but amplify didn't uninstall and the issue persists

**Comment by GIOkafor** [comment]
You were right, despite running npm uninstall, aws amplify **did not uninstall**.

I ran `which amplify` and it showed me where it was installed, so I went ahead and deleted all the associated files, ran the install command and it worked.

Thanks for the assist.
