### ISSUE TITLE
Amplify assignes the wrong dynamodb table name  the app.js file it creates, and also adds a mandatory suffix env name to the dynamodb table created

### ISSUE THREAD

**Issue by kshitijbhat330** [aws-amplify/amplify-cli#1884]
**Description of  the bug**
amplify assigns the "resource-name" of the dynamodb (which is set when amplify add api was invoked) to a variable "tablename" and uses that in the app.get() functions. Which gives error upon performing get operation.
Amplify also adds a mandatory "env" name as a suffix to the dynamodb  table which we want to create.
Suppose, the table I want to create :  good-students
my envname ( which is not allowed to be empty in amplfy init command): "dev"
table being created by amplify has the name:  good-students-dev
I believe including the env name should be made optional.

**To Reproduce**
Initialization:
1. Command: amplify init
2. Enter envname: dev
3. Enter project name: "studentproject"
4. AWS Profile: default (any profile of your choice)
5. Select Editor: VS code
6. Select framework: react

Adding API:
1. Command:  amplify add api
2. Select : REST API
3. Add a dynamodb table
4. Resourcename: "studentdynamodb"
5. Table name:  "good-students"
6. Lambda (Any resource name and lambda name of your choice. in my case:  Lambdaname: getStduents)

go to amplify -> backend -> function -> getStudents -> app.js
refer the variable: tablename.

**** screenshots **********
![image](https://user-images.githubusercontent.com/42442346/61739969-823a5180-ad5b-11e9-86a9-c21585cc8b25.png)

![image](https://user-images.githubusercontent.com/42442346/61739066-b44ab400-ad59-11e9-9cc7-2d3f637e177f.png)

![image](https://user-images.githubusercontent.com/42442346/61739306-291dee00-ad5a-11e9-9058-aead419e854e.png)

![image](https://user-images.githubusercontent.com/42442346/61739437-65e9e500-ad5a-11e9-9d98-5a41e99c0191.png)

The same table name is being used in dynamodb.query():

![image](https://user-images.githubusercontent.com/42442346/61739865-4f905900-ad5b-11e9-8c1e-0bddc5636260.png)

**Comment by kaustavghosh06** [comment]
@kshitijbhat330 
If you look at your screenshot above, after the tableName insitialization, there is a conditions:
```
if(process.ENV && process.env.ENV !== NONE) {
   tableName = tableName + '-' + process.env.ENV;
}
```

So the tableName is concatenated by the enviornment name. Out here `process.env.ENV` would be `dev` for your case.

**Comment by kshitijbhat330** [comment]
My point exactly. 
The table created: good-students-dev
The variable tablename contains the string: "studentdynamodb-dev"

and later in the code, you can see that the queryparams is: 

  let queryParams = {
    TableName: tableName,
    KeyConditions: condition
  } 

which is used in the below statement
  dynamodb.query(queryParams, (err, data) => {
    if (err) {
      res.statusCode = 500;
      res.json({error: 'Could not load items: ' + err});
    } else {
      res.json(data.Items);
    }
  });


this means it performs query on wrong table.

Correct me if I am wrong

**Comment by kaustavghosh06** [comment]
@kshitijbhat330 You can unlock yourself for the moment by changing the tableName in your Lambda function code from "good-students" to "studentdynamodb" to currently unblock yourself while we dig into the auto-generated code issue.

The `"hashKeyPath" (i.e "/:id" )"`  path is a requirement since the your table has a primary key (id i beleive) which needs to be present in a query without which the operation won't succeed.

**Comment by kshitijbhat330** [comment]
@kaustavghosh06 
Thank you, 

Regarding "hashKeyPath" (i.e "/:id" )" path as a requirement :

I think there should be a function to perform the  " SELECT * from tablename " to return all recrods in a dynamodb table without any filter condition. In this case, the app.get() function returns an error as it performs dynamodb.query() and there is no filter condition passed to it. 

I have created a custom code for that which might be helpful.

`/*###############################
  Custom Get method for dynamodb
  ###############################*/


app.get(path , function(req, res) {
  //if(Object.keys(req.params).length == 0){
  if(Object.keys(req.query).length == 0){
    let queryParams = {
      TableName: tableName
    } 
  
    dynamodb.scan(queryParams, (err, data) => {
      if (err) {
        res.statusCode = 500;
        res.json({error: 'Could not load items: ' + err});
      } else {
        res.json(data.Items);
      }
    });
  }
  else {
    var condition = {}
    condition[partitionKeyName] = {
      ComparisonOperator: 'EQ'
    }
    
    if (userIdPresent && req.apiGateway) {
      condition[partitionKeyName]['AttributeValueList'] = [req.apiGateway.event.requestContext.identity.cognitoIdentityId || UNAUTH ];
    } else {
      try {
        condition[partitionKeyName]['AttributeValueList'] = [ convertUrlType(req.query[partitionKeyName], partitionKeyType) ];
        //condition[partitionKeyName]['AttributeValueList'] = [ convertUrlType(req.params[partitionKeyName], partitionKeyType) ];
      } catch(err) {
        res.statusCode = 500;
        res.json({error: 'Wrong column type ' + err});
      }
    }

    let queryParams = {
      TableName: tableName,
      KeyConditions: condition
    } 
    dynamodb.query(queryParams, (err, data) => {
      if (err) {
        res.statusCode = 500;
        res.json({error: 'Could not load items: ' + err});
      } else {
        res.json(data.Items);
      }
    });
  }

});`

**Comment by kshitijbhat330** [comment]
Hi Team,
Can you please provide any updates regarding this?

**Comment by kaustavghosh06** [comment]
@kshitijbhat330 Which specific update are you looking for? We've fixed the wrong incorrect tableName generation mentioned in your description here - https://github.com/aws-amplify/amplify-cli/issues/1884#issue-471887412

**Comment by kshitijbhat330** [comment]
Hi Kaustav, 

If you read my comments below your description, you can see that we are not able to get the support from amplify to add the existing DynamoDb table. 
Suppose if I do not want my table to have the suffix of env name to it, It would still force the env name at the end of the table name which you have to create new for every new amplify template you create. Please refer the screenshots I have attached in my earlier comments
