### ISSUE TITLE
How to integrate serverless template aws-python with React JS? 

### ISSUE THREAD

**Issue by kshitijbhat330** [aws-amplify/amplify-cli#1885]
** Which Category is your question related to? **
MY REST API endpoints are created with serverless. I have created a React application. I am trying to implement a functionality where a button click should trigger the lamda function which in turn returns the performs query on a dynamodb table.
** What AWS Services are you utilizing? **
aws amplify, aws cognito
** Provide additional details e.g. code snippets **

**Comment by UnleashedMind** [comment]
@kshitijbhat330 
Thanks for your feedbacks and sorry to hear your frustration. 
I will mark this as a feature request, the CLI team will review it, you will be updated.

**Comment by kshitijbhat330** [comment]
@UnleashedMind , @haverchuck ,

thanks very much.

**Comment by kshitijbhat330** [comment]
Hi Team, Can you please provide any update regarding this?

**Comment by Alk3m1st** [comment]
I believe this has been resolved now? support for various lambda runtimes was added within the last few months I believe.

**Comment by siegerts** [comment]
Closing since multiple runtimes are now supported. Also, the default options for creating a REST API include Python. 

https://docs.amplify.aws/cli/function#supported-lambda-runtimes
