### ISSUE TITLE
@connection won't let you change sortField

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#1891]
**Describe the bug**
Deployed this:
````
entries: [Entry] @connection(name: "CompetitionEntries", sortField: "createdAt")
````

Then changed it to this:
````
entries: [Entry] @connection(name: "CompetitionEntries", sortField: "voteCount")
````

**To Reproduce**
Running the above will give you an error that a GSI can't be modified other than provisioned throughput

**Expected behavior**
The GSI should be dropped and re-added automatically

**Comment by UnleashedMind** [comment]
@CodySwannGT 
This is a known limitation of the DynamoDB, as documented here
https://aws-amplify.github.io/docs/cli-toolchain/graphql#generates-3
Please follow the note in that document section if you need to change an @connection

**Comment by CodySwannGT** [comment]
Got it. Thanks!
