### ISSUE TITLE
Multiple relations between same two models

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-cli#1894]
** Which Category is your question related to? **
Api

** What AWS Services are you utilizing? **
AppSync - graphql

** Provide additional details e.g. code snippets **
This naive implementation won't work and that's ok, but what's the _best, cleanest_ way to workaround the fact that you cannot use the same relation more than once between models?

```graphql
type Trade @model {
  id: ID!
  seller: User @connection(name: "UserTrade")
  buyer: User @connection(name: "UserTrade")
}

type User @model {
  id: ID!
  givenName: String
  familyName: String
  trades: [Trade] @connection(name: "UserTrade")
}
```

**Comment by UnleashedMind** [comment]
You can use this schema for your use case: 
```graphql
type Trade @model {
  id: ID!
  seller: User @connection(name: "TradeSeller")
  buyer: User @connection(name: "TradeBuyer")
}

type User @model {
  id: ID!
  givenName: String
  familyName: String
  sells: [Trade] @connection(name: "TradeSeller")
  buys: [Trade ] @connection(name: "TradeBuyer")
}
```
I also marked this as an enhancement, because the gql-transformer could error or show warning message, instead of letting this compile.

**Comment by AlessandroAnnini** [comment]
Thanks @UnleashedMind , that's just the solution I ended up using, but your answer is an important validation.
