### ISSUE TITLE
Resolver templates are wrongly rendered on @connection fields

### ISSUE THREAD

**Issue by babu-upcomer** [aws-amplify/amplify-cli#1896]
**Describe the bug**
$ctx.source fields are wrongly rendered in the @connection resolver's request mapping templates.

**To Reproduce**

Model,

```
type Event
    @model
    @auth(rules: [
        { allow: owner, ownerField: "inviter", identityField: "sub" }
        { allow: groups, groups: ["everyone"], operations: [read] }
    ])
{
    id: ID!
    title: String
    time: AWSDateTime!
    inviter: User! @connection(name: "UserEvents")  # GSI with User
}
```

Request mapping template auto-generated,
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.eventInviterId, "___xamznone____"))
  }
}
```

Query,
```
query ListEvents {
    listEvents(filter: {time: {ge: "2019-07-16T12:30:00Z"}}) {
        items {
            id
            title
            time
            inviter {
              	id
                preferredUsername
                cognitoUsername
            }
        }
        nextToken
    }
}
```
Throws "Cannot return null on non-nullable field" as the User items was tried to fetch with `$ctx.source.eventInviterId` as in the request template. I wonder from where that `eventInviterId` is generated. I edited the resolver to use `$ctx.source.inviter` instead and it worked.

**Expected behavior**
The fields name in the schema model should match with the request mapping resolvers.

**Comment by kwhitejr** [comment]
For the @connection resolvers completely break down when combining @key custom partition keys with many-to-many relationships.

**Comment by nikhname** [comment]
@babu-upcomer could you provide the full schema which produced that request mapping template?

**Comment by nikhname** [comment]
@babu-upcomer eventInviterId is autogenerated when a keyField is not provided in the @connection. To avoid this you can provide your own keyField, like @connection(name: "UserEvents",  keyField:"ID")

**Comment by nikhname** [comment]
@kwhitejr could you provide your schema and resolver code for some more context about this issue?

**Comment by kaustavghosh06** [comment]
Closing this issue for now based on @nikhname's response.
