### ISSUE TITLE
Adding auth fail to push

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#1897]
**Describe the bug**
I'm creating a new project with api and Cognito auth

**To Reproduce**
- When requested, check email as method for Cognito authentication
- add confirmation link (enter whatever you want as subject and message)
- all other value default
- amplify push

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Node 12.7.0
 - npm 6.10.2

**Error**
Following resources failed

Resource Name: UserPool (AWS::Cognito::UserPool)
Event Type: create
Reason: 1 validation error detected: Value 'functionvdp3dcf8667CustomMessageArn' at 'lambdaConfig.customMessage' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:[\w+=/,.@-]+:([\w+=/,.@-]*)?:[0-9]+:[\w+=/,.@-]+(:[\w+=/,.@-]+)?(:[\w+=/,.@-]+)? (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 8facc4dd-fe6a-4ecc-ad54-7df4319f5ac7)

Obviously it rollback

**Comment by haverchuck** [comment]
@artecoop In the cloudformation console, can you check the Parameters section in the auth stack, and  post the value listed for `functionvdp3dcf8667CustomMessageArn`?

**Comment by JarrydTrokis** [comment]
I'm also having the same problem. Interestingly, this only happened with the updated version of the cli. Previously, I had been running on 1.7 — since running on 1.8, I started seeing the bug.

@artecoop I did find that by creating **auth** first, then creating **api**, I managed to get things up and running.

**Comment by artecoop** [comment]
Thanks for the comment and input.
First of all, I want to apologize for posting in the wrong repo.

I can confirm, as @JarrydTrokis suggested, that the flow:
- amplify add auth
- amplify push
- amplify add api
- amplify push 

did the trick.

You can close the issue when needed.

**Comment by kleingtm** [comment]
I see this bug on both 1.8.5 and 1.8.6 (macOS, npm 6.9.0).

For what it's worth, it doesn't happen if I use a default(ish) setup. However, if you choose to manually edit a variety of options during `amplify add auth`, it'll fail.

**Comment by kaustavghosh06** [comment]
We have a PR out for this - #1897 and we'll publish the fix to npm as soon as we merge it.

**Comment by kaustavghosh06** [comment]
hey guys, we've merged the fix for this and the fix will be part of our next npm release.
