### ISSUE TITLE
So how do I actually authenticate and access my graphql api inside a lambda function

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1901]
** Which Category is your question related to? **
Amplify function and api

** What AWS Services are you utilizing? **
Amplify (So AppSync and Lambda)

** Provide additional details e.g. code snippets **
So I've added a new function in my existing amplify project using [following this blog post](https://aws.amazon.com/blogs/mobile/amplify-framework-adds-support-for-aws-lambda-functions-and-amazon-dynamodb-custom-indexes-in-graphql-schemas/) but instead of `storage` I wanted to access my GraphQL API so I chose `api` and went through the rest of the CLI setup. After pushing it generated a lambda function with 4 environment variables:

- GRAPHQLAPIENDPOINTOUTPUT
- GRAPHQLAPIIDOUTPUT
- ENV
- REGION

So how do I actually connect now to my GraphQL endpoint and start querying? Do I just add apollo client? I'm not sure how to authenticate and access. The blog's only example is using storage and no further documentation for accessing an Amplify GraphQL API.

Also not sure if relevant but in my amplify project, I authenticate using the API via Cognito user pools

**Comment by RossWilliams** [comment]
One option is to add a "service" user to cognito and login inside your lambda before calling the graphql endpoint. There is a good writeup here: https://www.floom.app/blog/aws-appsync-with-lambda

**Comment by nino-moreton** [comment]
closing in favor of #1678  .. which will be solved in a cleaner way using secondary auth option (i.e. Cognito main and IAM secondary auth) with #1916
