### ISSUE TITLE
Add Storage => Domain already exists

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-cli#1902]
Similar to #1845 

**Describe the bug**
I have Auth, Function and Api services in place.
I added Storage service and pushed.
The error on Cloudwatch has this messages:
1. message: `Domain already exists. `, code: `AccessDeniedException`
2. message: `User XXXXX is not authorised to perform: cognito-idp:DeleteUserPoolDomain on resource: XXXXX` code: `InvalidParameterException`
3. same as n.2
4. same as n.2

But the bucket on S3 is created

**Expected behavior**
successful s3 storage creation and use on the project

**Additional context**
amplify version: 1.8.5

**Comment by AlessandroAnnini** [comment]
I noticed that every time a add a custom attribute to my Cognito users then I have this error when I add storage

**Comment by kaustavghosh06** [comment]
@AlessandroVol23 I suspect what's happening is that, when you're modifying/adding a custom attribute (which are immutable and shouldn't be updated after creation), Cloudformation is creating a new user-pool for you (with the new custom attributes), retaining the old one and trying to spin up a new hosted UI (with the same domain) as the previous user-pools hosted UI domain which still exists. 
To get around this, you might want to delete the old cognito user-pool and remove the hosted UI endpoint using the AWS console to make the push succeed.

**Comment by AlessandroAnnini** [comment]
I see, thanks for the explanation @kaustavghosh06 , where exactly can I remove the hosted UI endpoint?

**Comment by kaustavghosh06** [comment]
@AlessandroAnnini From your AWS cognito console.
