### ISSUE TITLE
Amplify push error, Unknown directive "key"

### ISSUE THREAD

**Issue by turleydesigns** [aws-amplify/amplify-cli#1911]
** Which Category is your question related to? **
Amplify CLI, sort key

** What AWS Services are you utilizing? **
AppSync, DynamoDB, GraphQL, and Lambda

** Provide additional details e.g. code snippets **
When trying to add a @key to a model in the schema.graphql, I am getting an error when pushing the changes with amplify.   I have @aws-amplify/cli@1.8.5 installed. 

```
✖ An error occurred when pushing the resources to the cloud

Schema Errors:
Unknown directive "key".
GraphQL request (50:3)
49: type Message @model
50:   @key(fields: ["created"]) {
      ^
51:   id: ID!
```

Here is the model: 

```
type Message @model
  @key(fields: ["created"]) {
  id: ID!
  message: String!
  link: String!
  created: String!
}
```

I read through the documentation (https://aws-amplify.github.io/docs/cli-toolchain/graphql#key) and it seems like this should work.  

 Am I missing something?

**Comment by andrewbtp** [comment]
+1 Also getting this issue.

**Comment by kaustavghosh06** [comment]
@turleydesigns & @andrewbtp Can you run `amplify -v` and check the Amplify CLI version? My hunch is that the CLI didn't update correctly on your system.

**Comment by turleydesigns** [comment]
```
$ amplify -v
$ 1.6.8
$ npm install -g @aws-amplify/cli
$ ...
$ + @aws-amplify/cli@1.8.5
$ updated 1 package in 41.658s
```

@kaustavghosh06  1.6.8

@andrewbtp Thanks, I have tried this before, and tried it again now, still getting the same error.

**Comment by kaustavghosh06** [comment]
@turleydesigns After you install the latest CLI, can you check `amplify -v` and see if the CLI updated globaly correctly?

**Comment by kaustavghosh06** [comment]
@turleydesigns We weren't able to reproduce this issue with the latest version of the CLI. As mentioned above, after installing/.updating the version of the CLI, can you check the latest version using `amplify -v` and make sure that it updated to the latest version of the CLI?

**Comment by turleydesigns** [comment]
@kaustavghosh06  
```
$ amplify -v
$ 1.6.8
```

that is the latest, correct?

**Comment by kaustavghosh06** [comment]
@turleydesigns 1.10.0 is the latest version.
