### ISSUE TITLE
s3Trigger lambda function inline policy getting overwritten

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#1913]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**

1. the inline policy name for the S3TriggerBucketPolicy varies based on when the trigger is applied. when trigger is applied to existing bucket, "s3-trigger-lambda-execution-policy" is used. if not "amplify-lambda-execution-policy" is used. (see logic here: https://github.com/aws-amplify/amplify-cli/blob/54a8dbe8925a4e73358b03ba927267a2df328b78/packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js#L418)
2. "amplify-lambda-execution-policy" is the name of the inline policy used for all trigger cases. if you try to grant access to multiples resources, the inline policy just gets overwritten. e.g.: if you want your s3Trigger lambda function to have access to the API, the inline policy granting access to the API ends up getting overwritten. (first the role is created by the function cfn template, then the role is updated by the storage cfn which can overwrite the existing inline function)

**To Reproduce**
1. amp add storage with trigger
2. amp add api
3. amp update function, grant API access
4. result is that storage cfn will overwrite the function cfn inline prolicy

this does not happen if you define the trigger after the bucket is created

Also note about "S3TriggerBucketPolicy": technically it is not a bucket policy since not applied to an S3 bucket; but to a role.

**Comment by jkahn117** [comment]
Confirmed, just experienced same behavior.

Added Amplify Storage, the trigger function has GetObject, ListBucket, PutObject, and DeleteObject permissions on the bucket created.

Function needs access to the bucket and GraphQL API created by Amplify, so run `amplify function update` and select appropriate permissions for API category. Resulting policy covers AppSync only, S3 permissions are lost.

On attempting to add S3 permissions back by running `amplify function update` again and selecting Storage, receive an error message: "Error: Cannot add S3TriggerXXXXXXXX due to a cyclic dependency." Lambda environment variables are updated, but contain default values.

**Comment by kaustavghosh06** [comment]
@jkahn117 @onlybakam I tried to go through the flow that you've mentioned. The S3 permissions are not lost, but they're present in the S3 cloudformation template. In the S3 cloudformation template, could you check if the policies exist? you should see something like this in the S3 Cloudformation template.

```json
"TriggerPermissions": {
            "Type": "AWS::Lambda::Permission",
            "Properties": {
                "Action": "lambda:InvokeFunction",
                "FunctionName": {
                    "Ref": "functionS3Trigger45af1fbbName"
                },
                "Principal": "s3.amazonaws.com",
                "SourceAccount": {
                    "Ref": "AWS::AccountId"
                },
                "SourceArn": {
					"Fn::Join": [
						"",
						[
							"arn:aws:s3:::",
							{
			                    "Fn::If": [
			                        "ShouldNotCreateEnvResources",
			                        {
			                            "Ref": "bucketName"
			                        },
			                        {
			                            "Fn::Join": [
			                                "",
			                                [
			                                    {
			                                        "Ref": "bucketName"
			                                    },
			                                    "-",
			                                    {
			                                        "Ref": "env"
			                                    }
			                                ]
			                            ]
			                        }
			                    ]
			                }
						]
					]
                }
            }
        },



```

**Comment by kaustavghosh06** [comment]
@jkahn117 @onlybakam Could you please check if you can reproduce with v 1.12.0?

**Comment by jkahn117** [comment]
@kaustavghosh06 I just ran the same flow on a fresh project and all worked properly. I had been looking in the function stack, not S3, though I thought I had checked the final permissions that were pushed as well.

It's possible that I tripped myself up in attempting to add Storage access in `function update` which leads to a cyclical dependency and then looked at the permissions. Would it be possible to remove the Storage option for access when updating a trigger function? Or note mark it as already having access?

**Comment by nikhname** [comment]
@jkahn117 thanks for the feedback. We will consider marking the storage option or removing the option to avoid confusion in the future.

**Comment by onlybakam** [comment]
i dont think this issue is fixed. if you repeat the steps i provided then look at the resource: `S3TriggerBucketPolicy` that is applied to the lambda execution role, you see that it is create a policy with the exact same name of the inline policy for role. this will then overwrite the policy and remove existing permisions

**Comment by mhzbg** [comment]
This is still happening in 4.29.1.

If you add the trigger and then update the function access. It will loose S3 the permission set by storage/add trigger.

If you modify storage access from function, then cloud-formation fails and the whole stack gets broken. 
What is a viable workaround ?

**Comment by robertosannazzaro** [comment]
I confirm I am getting the same issue: I am trying to trigger a function when uploading a .csv file in S3, to read the file and put its content in Dynamo, however, I am getting the error `Cannot add S3Trigger4f853757 due to a cyclic dependency`.

Do you know any workaround for this?

**Comment by rduenasf** [comment]
I had the same problem as @mhzbg while trying to give an S3 Trigger access to my graphql API it lost access to its storage

**Comment by duncangroenewald** [comment]
Yes me too - any workaround for this - one or the other keeps getting overridden.  Can someone clarify if this is a bug in amplify-cli or CloudFormation?   

Can I manually edit something somewhere to fix this so that deployment works ?

**Comment by jroebu14** [comment]
I experienced loss of access to storage with these steps:

1. amplify add storage - add trigger (at the same time as adding storage)
2. amplify update function - grant API access

If I remember correctly I tried these steps and got it working:

1. amplify remove storage
2. amplify remove function - select the trigger function
3. amplify push
4. delete S3 bucket in console
5. amplify add storage (do not add trigger function just now)
6. amplify update storage - add trigger function
7. amplify update function - grant API access

It's not ideal but hopefully it helps anyone stuck in the same situation.
