### ISSUE TITLE
Aurora Postgres Serverless Support?

### ISSUE THREAD

**Issue by larryranches** [aws-amplify/amplify-cli#1914]
As of July 9th 2019, AWS Aurora Postgres Serverless is now in GA (https://aws.amazon.com/blogs/aws/amazon-aurora-postgresql-serverless-now-generally-available/)

The current amplify docs under Transforms > Relational Databases specifically states _"The Amplify CLI currently supports importing serverless Amazon Aurora MySQL 5.6 databases running in the us-east-1 region."_

Is the docs out of date and does Amplify Cli currently support AWS Aurora Posgres Serverless or should we expect an upcoming future release to support this?

**Comment by RossWilliams** [comment]
@larryranches Amplify relies on the Data API Aurora Serverless. This is still only available for the MySQL-compatible version.

**Comment by larryranches** [comment]
@RossWilliams Gotcha, thank you!

**Comment by kaustavghosh06** [comment]
@larryranches Yes @RossWilliams is correct. We rely on the availability of the Data API in those regions for the CLI to work with it. We'll be adding more regions as and when the Data API is available in other regions.

**Comment by timrchavez** [comment]
Can we re-open this given postgresql has support for data API and `add-graphql-datasource` appears to be implemented in terms of mysql-ism (e.g. `show databases`.. I believe the analog in postgresql is `SELECT datname FROM pg_database;` but feel free to correct me if I'm wrong)

**Comment by stefanotauriello** [comment]
Is there any update for Postgresql?

**Comment by jesper-bylund** [comment]
I can't believe the documentation doesn't really explain any of this.
