### ISSUE TITLE
GSI using Partition Key

### ISSUE THREAD

**Issue by cocacrave** [aws-amplify/amplify-cli#1917]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
API: @key directive
Storage: Dynamodb

** What AWS Services are you utilizing? **
Dynamodb

** Provide additional details e.g. code snippets **
How do you create new GSI using the table partition key as the GSI's partition key?
Adding @key.fields' partition key as the table partition key, the stack that gets created uses LSI. Even with @key.name given.
However in DynamoDB console, I can create the same GSI I tried above no problem.

Same scenario with amplify storage add. The table partition key is not even listed as an option for GSI partition key.

**Comment by kaustavghosh06** [comment]
@cocacrave You can use the @key directive as follows. 
`@key (name: "gsi-name", fields [<partition-key>, <sort-key>]`
This would create a GSI for you  based on the fileds you insert in the partition key and sort key params above. To learn more you can checkout - https://aws-amplify.github.io/docs/cli-toolchain/graphql#key
