### ISSUE TITLE
Cognito user can't login.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1919]
** Which Category is your question related to? **
Authentication.

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I've enabled Cognito. And created a migration script. I've tested it and all works. 

The problem is I have one user, that's not able to login. I've manually set the password. Tried recreating the user. Tried a password reset. Just can't get the user to successfully sign in. 

If I sign in as the user and the user is migrated to Cognito and they try and use the login screen it wants to call a challenge, but I don't know what that is for? 

If I delete the user and they try to sign in, it says the user does not exist. And the migration lambda is not called at all.

What is strange, is that on my browser it all works for this specific user. But on their system it does not. I have tried multiple browsers and cleared cache to no avail. And we are copy/pasting credentials so it is not a typo.

Any ideas what I could do next? The user is in another country, maybe that affects Cognito?

Regards.

**Comment by kaustavghosh06** [comment]
@jarrettj This seems like very specific to the Cognito service. You would want to open up a forum post with the Cognito Service team to engage on this issue - https://forums.aws.amazon.com/forum.jspa?forumID=173

**Comment by jarrettj** [comment]
Thanks.

**Comment by jarrettj** [comment]
On a side note, how would one debug/log the authentication flow from an amplify project? If the login screen is a built in module. We currently use the angular directive supplied.
