### ISSUE TITLE
GeoJSON format in amplify to elasticseach

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#1921]
I have a schema like this

```
type Event @model @searchable{
  id: ID!
  date: String!
  maxParticipants: Int
  polygon: Location
  subscribers: [Subscriber]
  courseTimetable: [CourseTimetable]
  afterpartyLocation: String
  lastDateToSubscribe: String
  eventOwner: Subscriber! @connection
}

type Subscriber @model @searchable{
  id: ID!
  name: String!
  email: String!
  phone: String
  device: String
  addressLocation: Location!
  dieetWishes: String
  events: [Event] @connection
  planning: [Planning] @connection(name: "SubscriberPlanning")
}

type Planning @model{
 id: ID!
 event: Event
 subscriber: Subscriber @connection(name: "SubscriberPlanning")
 location: Location
 course: String
 type: String
 time: String
 notificationSend: Boolean
}

type Location {
  coordinates: [[[String]]]
}
```

I made this schema to align with the geoJson format which elasticsearch is opting for. 
This gives me this data in elasticsearch:

```

"polygon": {
            "coordinates": [
              [
                [
                  "51.89600366973369,5.604579537426986"
                ],
                [
                  "51.88589816283178,5.598937488274174"
                ],
                [
                  "51.882074887477046,5.620585782912315"
                ],
                [
                  "51.891197214447004,5.622057621577596"
                ]
              ]
            ]
          },
```

But geoJSON is having a structure like (without the double quotes):

"polygon": {
            "coordinates": [
              [
                [
                  51.89600366973369,5.604579537426986
                ],
            ]
       ]
}

How can I get this structure in elasticsearch from dynamodb?

**Comment by RossWilliams** [comment]
You have specified the coordinates field as [[[String]]], this needs to be [[[Float]]] if you want the value to be treated like a number. Also, your existing index likely now has the wrong mapping for this field. you will need to send data into a new index, or delete and re-create the existing index.

**Comment by rpostulart** [comment]
Ok, but how can you construct a geo float like 51.89600366973369,5.604579537426986

**Comment by RossWilliams** [comment]
I'm not familiar with geo float in Elasticsearch. A geo_shape of type point is an array with two floating point numbers. add two numbers into an array. If you add this to dynamo, it will be stored as a number (if your schema specifies "coordinates" as an array of Float)
```json
"polygon" : {
        "type" : "point",
        "coordinates" : [MY_LATITUDE_AS_FLOAT, MY_LONGITUDE_AS_FLOAT]
    }
```
or you can use the geo_point syntax with your schema and specify lat and lon, and not use an array.
```gql
type Location {
  lat: Float!
  lon: Float!
}
```

**Comment by rpostulart** [comment]
Yes but this wil create coordinates : [{ lat: 12312313, lon: 12312313}]
And I don't want an object, just a purely array with the coordinates. Or am I wrong?

**Comment by RossWilliams** [comment]
you are not wrong. There are multiple ways to implement geo points in elasticsearch, so I showed two different ways to represent a coordinate. It sounds like you want to use geo_shape instead of geo_point, so use the first code block from above. But your question is more about elastic search data types than a feature or bug in the amplify cli.

**Comment by rpostulart** [comment]
Ok I will dive into this and yes I maybe have a need for better GEO support in Amplify, but this is not a real issue.
