### ISSUE TITLE
Update changes to the environment made by one developer to the other developers. Specifically the Storage service.

### ISSUE THREAD

**Issue by orozcojair** [aws-amplify/amplify-cli#1930]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@orozcojair Are the team members working on the same environment/AWS account?

**Comment by orozcojair** [comment]
yes, we are all working off the `dev` environment under the same AWS account

**Comment by kaustavghosh06** [comment]
If you try using `amplify env pull --restore` doesn't that sync up whatever is there in the cloud?

**Comment by orozcojair** [comment]
i tried both `pull` and `checkout` with --restore and they didnt work

**Comment by kaustavghosh06** [comment]
What’s the error message that you got?

**Comment by orozcojair** [comment]
No error message, actually I got a successful message but nothing changes.

**Comment by orozcojair** [comment]
![Screen Shot 2019-07-31 at 10 05 41 AM](https://user-images.githubusercontent.com/983866/62232319-c8ef0380-b37a-11e9-986d-11dcbf26cdfd.png)

**Comment by orozcojair** [comment]
as you can see after running both commands i get  the success message but I dont get the `Storage` service that my teammate added in his machine. He has pushed twice already to AWS and still nothing

**Comment by nino-moreton** [comment]
You need to pull in changes from git then do the amplify env pull so something like (assuming you're in dev branch of git:

make sure you're in amplify's dev branch as well by doing `amplify env checkout dev`
`git pull origin dev`
`amplify env pull`

**Comment by orozcojair** [comment]
hi nino 
this is the same advise you gave to a different individual a while ago and it has the same flaw. Both developer cannot be in the same git branch.. but i appreciate you trying

**Comment by kaustavghosh06** [comment]
@orozcojair Even if you're not using git, and if all your developers are working on the same backend (i.e same AWS account and region), then `amplify env pull --restore` should sync up every one's changes. I've validated this and I would want to know more about your project. 
After you run `amplify env pull --restore`, what do you see when you run `amplify status`?

**Comment by orozcojair** [comment]
the expectation is that i see 4 services, the 3 you see in my picture plus the newly added service Storage.

Also I would have expected the file `aws-exports.js` to include the S3 bucket name but i didnt get.

We updated our Amplify cli yesterday as well to fix the other issue you commented and tried running `aws env pull --restore` to see if that would help and it didnt

**Comment by orozcojair** [comment]
@kaustavghosh06 in your tests did you try to sync Storage as the service?

**Comment by orozcojair** [comment]
This morning I had a conversation with @swaminator about the issue with synchronizing the Storage service, he requested that I ping him in this issue so that he can investigate.

@swaminator let me know if this is sufficient or if you need anything else. Thank you for your time this morning 🙇
