### ISSUE TITLE
Auth error when accessing lambda function in another lambda function

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1931]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I go through the amplify cli to add function resource access in my other function (giving it all CRUD access), then when I try to invoke the lambda function inside the other lambda, it says: 
`AccessDeniedException`

**To Reproduce**
1. Create function (let's call it functionA) through amplify CLI
2. Create another function resource (call it functionB) through amplify CLI
3. Update functionA through `amplify update function` and add access to functionB granting functionA all CRUD access to functionB resource.
4. Invoke functionB inside functionA and get Auth error

**Expected behavior**
Giving one lambda function resource access to another lambda function resource through `amplify update function` should grant proper Auth stuff

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Here's the code I use in functionA to invoke functionB:
```
const aws = require('aws-sdk');
const lambda = new aws.Lambda({
  region: process.env.REGION //generated by amplify cli
});

const event = {...}

lambda.invoke({
  FunctionName: process.env.FUNCTION_FUNCTIONB_NAME, //generated by amplify cli when giving a function access to another function resource
  Payload: JSON.stringify(event, null, 2)
}, function(error, data) {
  if (error) {
    console.log('error', error);
  }
  if(data.Payload){
   console.log("yey", data.Payload)
  }
});
```

**Comment by kaustavghosh06** [comment]
@nino-moreton Could you specify what exact auth error you're seeing?

**Comment by nino-moreton** [comment]
hey @kaustavghosh06 here's the exact error message (i've censored some sensitivee stuff)

```
AccessDeniedException: User: arn:aws:sts::265681005590:assumed-role/***********LambdaRoleca1b6038-dev/*******************Fn-dev is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:**-***********-2:265681005590:function:********-dev
```

**Comment by nikhname** [comment]
@nino-moreton could you provide your cloudformation template and the full functions you used to produce this error for some more context?

**Comment by kaustavghosh06** [comment]
@nino-moreton Closing this issue due to lack of requester information. Please comment on this thread if you're still seeing this issue.
