### ISSUE TITLE
API.ts - error All files must be modules when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#1932]
The generated API.ts file throws an error when using typescript.

Contents of API.ts:
---
/* tslint:disable */
//  This file was automatically generated and should not be edited.
---
The error on compiling is:
All files must be modules when the '--isolatedModules' flag is provided.

My understanding is the issue is that there is nothing being exported or imported in this file (it's essentially empty). Why is this file generated by codegen if it's going to be empty? 

Temporary fix is to delete the API.ts after running amplify codegen.

**Comment by kaustavghosh06** [comment]
@GeorgeBellTMH We fixed this issue a while back and if you use the latest CLI version, you'll see content in that file - which could be used in your app.

**Comment by Rexingleung** [comment]
how to deal

**Comment by glueCod** [comment]
@kaustavghosh06 how did you fix that?
