### ISSUE TITLE
Allow different auth directives in AppSync for connections

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1933]
*Which Category is your question related to?*
API

*What AWS Services are you utilizing?*
AppSync, Cognito

*Provide additional details e.g. code snippets*
For context: I'm aware of [this PR](https://github.com/aws-amplify/amplify-cli/pull/1916).

Until the PR is merged (and probably even after) there is a problem with directives.

**TL;DR**: How can you give `@aws_iam` access from a one to many connection on a model?

If I have a schema like this (please be sure to read the update at the end of the issue):

```graphql
type Address @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  departureTripData: [TripData] @connection(name: "TripDataDepartureAddresses")
}

type TripData @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  departureAddress: Address! @connection(name: "TripDataDepartureAddresses")
  matches: [Match] @connection(name: "MatchTripData")
}

type Match @model {
  id: ID!
  trip: TripData! @connection(name: "MatchTripData")
}

type Query {
  scanTrips(filter: ModelTripDataFilterInput): TripResponse
}

type TripResponse {
  items: [TripData]
}

# Imported from the builds/schema.graphql file
input ModelTripDataFilterInput {
  id: ModelIDFilterInput
  and: [ModelTripDataFilterInput]
  or: [ModelTripDataFilterInput]
  not: ModelTripDataFilterInput
}

input ModelIDFilterInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
}
```

The default permission for the API is Cognito User Pools. I want to be able to control the access. So, I use the AppSync console to give `@aws_iam` permissions to `scanTrips` and `TripResponse`. This way only someone with `IAM` permissions can use the `scanTrips` query. Additionally, I give `Address`, `Match`, `ModelMatchConnectian` (which you can only see in the build folder and in the AppSync schema) and `TripData` both `@aws_iam` and `@aws_cognito_user_pools` permissions.

Now, if I use the console to execute the `scanTrips` query, I get the following error, if I try to access departureAddress:

```json
{
  "data": {
    "scanTrips": {
      "items": [
        null
      ]
    }
  },
  "errors": [
    {
      "path": [
        "scanTrips",
        "items",
        0,
        "departureAddress"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 40,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access departureAddress on type TripData"
    }
  ]
}
```

If I exclude `departureAddress` and include `matches` it works.

```graphql
# Doesn't work
query scanTrips {
  scanTrips {
    id
    items {
      id departureAddress {
        id name
      }
    }
  }
}

# Works!
query scanTrips {
  scanTrips {
    items {
      id
      matches {
        items {
          id
        }
      }
    }
  }
}
```

How can I get the connection form trip to departure address work for the `scanTrips` query with `@aws_iam` while not allowing `@aws_cognito_user_pools`?

**Update:** I found the reason. Here is the response `.vtl` template for `TripData.departureAddress.res.vtl`.

```velocity
## No Static Group Authorization Rules **


## No Dynamic Group Authorization Rules **


## [Start] Owner Authorization Checks **
#set( $isOwnerAuthorized = $util.defaultIfNull($isOwnerAuthorized, false) )
## Authorization rule: { allow: owner, ownerField: "owner", identityField: "cognito:username" } **
#set( $allowedOwners0 = $ctx.result.owner )
#set( $identityValue = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
#if( $util.isList($allowedOwners0) )
  #foreach( $allowedOwner in $allowedOwners0 )
    #if( $allowedOwner == $identityValue )
      #set( $isOwnerAuthorized = true )
    #end
  #end
#end
#if( $util.isString($allowedOwners0) )
  #if( $allowedOwners0 == $identityValue )
    #set( $isOwnerAuthorized = true )
  #end
#end
## [End] Owner Authorization Checks **


## [Start] Throw if unauthorized **
#if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
  $util.unauthorized()
#end
## [End] Throw if unauthorized **

$util.toJson($context.result)
```

Since the `I_AM` authed AppSync console (or Lambda function) is NOT the owner, it gets permission denied.

Is there a way to check in `.vtl` templates for whether the request comes from `I_AM` to avoid throwing permission denied?

**Comment by janhesters** [comment]
[I've found out](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity) that there is a `ctx.identity.claims` argument. But, I can't find how you can differentiate between someone with `I_AM` credentials or a Cognito user. I want to allow `I_AM` and have the `owner` checks for Cognito users.

**Comment by attilah** [comment]
@janhesters this scenario is handled by the PR you mentioned. When you've 2 auth providers enabled for the same operation, the resolver is different, it has 2 parts:
- Determine the auth mode from the request
- If it is user pool, then do the check you see already, otherwise skip that block

This enabled the caller to bypass the owner check if they were authenticated through ```IAM``` in that request.

**Comment by janhesters** [comment]
Hi @attilah , thank you again for your answer. Quick follow up: Do you have any idea when the PR will be merged? 😊 We need this for our team 🙏🏻

**Comment by attilah** [comment]
I'd say soon, but no explicit timeline, the code is there, we have some pending reviews, we'd like to ship this feature as well ;-)

**Comment by janhesters** [comment]
@attilah That's awesome and thank you for your answer 😊
