### ISSUE TITLE
Adding reCaptcha to existing auth

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1934]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, Lambda

** Provide additional details e.g. code snippets **
Saw this link https://aws-amplify.github.io/docs/cli-toolchain/quickstart#adding-a-lambda-trigger.
But how would you configure that for an existing User Pool? Thanks.

**Comment by kaustavghosh06** [comment]
@jarrettj You can use `amplify update auth` and add triggers to the auth resource configured as a part of your Amplify project.

**Comment by jarrettj** [comment]
Hi,

Good day, and thank you. 

It's not that obvious that you have to run through a bunch of options before you get there. 
<img width="895" alt="Screenshot 2019-08-01 at 22 52 27" src="https://user-images.githubusercontent.com/777547/62326685-018ff980-b4af-11e9-82a8-fc98a54a7a04.png">

Regards.

**Comment by dbashford** [comment]
This would be a nice thing to bubble up so you don't have to go through all the options
