### ISSUE TITLE
Mutation multiple row data insert to db

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#1935]
I have a type as shown below
```
type MasterCrop @model {
	cropId: ID!
	cropCode: String
	cropName: String
}
```
Mutation generated against this is like
```
createMasterCrop(input: CreateMasterCropInput!): MasterCrop
updateMasterCrop(input: UpdateMasterCropInput!): MasterCrop
deleteMasterCrop(input: DeleteMasterCropInput!): MasterCrop
```
API.service.ts file generated like this
```
export type CreateMasterCropInput = {
  cropId: string;
  cropCode?: string | null;
  cropName?: string | null;
};
```
suppose I want to add multiple data like
```
1, RC, Rice
2, WT, Wheat
3, CN, Corn
```
in a single API call, how could I do? As now only provision to add single row item at a time.

**Comment by pigmanbear** [comment]
See batch resolvers in the Appsync documentation: 

https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

But, depending on your use case, just remember dynamo has a batch limit of 25 (splitEvery by ramda in a composition can come in handy there)

> BatchWriteItem
> A single BatchWriteItem operation can contain up to 25 PutItem or DeleteItem requests. The total size of all the items written cannot exceed 16 MB.

Or, when performing the mutation, you can do something like ) :
```
const CreateMasterCrop = `mutation CreateMasterCrop($input: CreateMasterCropInput! ){
  createMasterCrop(input: $input){
    ${MasterCropInput}
  }
}`

const crops = [
  { input: { cropId: 1, cropCode: 'RC', cropName: 'Rice' } },
  ...otherCrops,
]
const mutateManyItems = mutation => async items =>
  Promise.all(
    items.map(input => API.graphql(graphqlOperation(mutation, input)))
  )

mutateManyItems(CreateMasterCrop)(crops).then(...).catch(...)
```

**Comment by kaustavghosh06** [comment]
@meetrij I agree with @pigmanbear's explainaton but you should be aware of AppSync throttling levels if you're using a Proime.all() from your client - it's basically 1,000 queries per second. You can find more information out here - https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_appsync
