### ISSUE TITLE
Parameter count xx is greater than max allowed 60 in auth

### ISSUE THREAD

**Issue by tluolamo** [aws-amplify/amplify-cli#1937]
**Describe the bug**
Using version 1.8.5 of the cli I updated my auth configuration and now when I try to push the changes I get this error:
```
UPDATE_FAILED               authcognitoxxxxxxx         AWS::CloudFormation::Stack Wed Jul 31 2019 09:54:54 GMT+0200 (Central European Summer Time) Template format error: Parameter count 68 is greater than max allowed 60
```
**To Reproduce**
1. execute 'amplify auth update'
2. Select 'Walkthrough all the auth configurations'
3. Complete the flow configuring various options
4. execute 'amplify push'
5. See the error and your push is rolled back

**Expected behavior**
I expect to be able to use the amplify cli as designed and not encounter errors during push

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by kaustavghosh06** [comment]
@tloulamo Could you please show your parameters.json file (hiding sensitive info) located in amplify/backend/ auth/<resource-name> directory?

**Comment by ghariosk** [comment]
I am also getting a similar error with :
```
CREATE_FAILED               authwazifa0b6ef5b9        AWS::CloudFormation::Stack Wed Jul 31 2019 18:51:11 GMT+0300 (Eastern European Summer Time) Template format error: Parameter count 65 is greater than max allowed 60
```

**Comment by tluolamo** [comment]
@kaustavghosh06 do you still want my parameters file? Seems there is a fix already by @haverchuck

**Comment by kaustavghosh06** [comment]
@tluolamo Yes, we've identified the issue and we'll release a fix for this as soon as the pR gets merged.

**Comment by kaustavghosh06** [comment]
@tluolamo We've merged the fix for this and it will be part of our next release.

**Comment by Zurdge** [comment]
Has this issue been fixed? 
I'm currently getting the same issue when pushing my updated Auth.

Setting Auth to the default setup pushes correctly however when using "Walkthrough all the auth configurations" and adding "Add User To Group" i cannot push it through.
