### ISSUE TITLE
property `schemapath` in file `graphqlconfig.yml` is being reset after `amplify codegen`

### ISSUE THREAD

**Issue by orozcojair** [aws-amplify/amplify-cli#1943]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
In my graphqlconfig.yml file, i set the `schemaPath` property to `graphql/schema.json` 
after i run `amplify codegen` i noticed that my file was created under folder `src/graphql/schema.json` and my property `schemaPath` was re-written to `src/graphql/schema.json`

The discrepancy here is that the other properties such as `includes` and `generatedFileName` remain as i set them, it is only `schemaPath` that keeps getting being prepended with the `src` folder path.

**To Reproduce**
Modify graphqlconfig.yml file, set property `schemaPath` to `schemaPath: graphql/schema.json`
run `amplify codegen`

**Expected behavior**
The expected behavior is that the file `schema.json` is under folder `{projectRoot}/graphql/`
and not under `{projectRoot}/src/graphql/` and that the graphqlconfig.yml property `schemaPath` remains as I had modified it before.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@orozcojair Whcih version of the CLI are you using? We fixed this as a part of this PR - https://github.com/aws-amplify/amplify-cli/pull/1864 and it's a part of the latest version of the CLI.

**Comment by orozcojair** [comment]
my version is definitely older than 13 days ago so I will update

**Comment by orozcojair** [comment]
yes this solved the issue. Thank you
