### ISSUE TITLE
Amplify API push produces "export tablename is already exported by stack" error

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1947]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I have an existing Amplify project with multiple models in Schema named like so:
Client
ClientQuestion

When I upgrade my amplify from anything above 1.7.5, I get the error (censored some sensitive stuff)
`*****************-20190415075708-api****************-198U880ZN9V67-**********-TG9K7AW7JKIR AWS::CloudFormation::Stack Thu Aug 01 2019 08:04:16 GMT+0800 (Philippine Standard Time) Export with name zbqivknx75f4dogfim7vbga2mq:GetAtt:SortableClientTable:StreamArn is already exported by stack ********-20190415075708-api************-198U880ZN9V67-Client-98762U932HO5`

**To Reproduce**
1. Create two models with almost same name like: QuestionClient and Client
2. do amplify API push command (make sure your amplify CLI is above 1.7.6
3. See error

**Expected behavior**
Should just push successfully

**Additional context**
Opening this issue since #1581 is closed but isn't actually solved yet and no one wants to reopen that issue :/
I've tried to use versions 1.9.0 and 1.8.6 which is supposed to have the fix but this still happens

**Comment by nino-moreton** [comment]
UPDATE:
Just found out this will only error out on EXISTING amplify projects upgrading from 1.7.5 to a newer version (I think from >1.7.6)

**Comment by kaustavghosh06** [comment]
@nino-moreton I've repoped #1581 and we're digging into it. Closing this in favor of #1581.
