### ISSUE TITLE
Is it safe to remove the old CoginitoUserPool was created by AmplifyCLI ? 

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#1952]
** Which Category is your question related to? **
auth

** What AWS Services are you utilizing? **
AppSync + Lambda + Cognito + APIGateway

** Provide additional details e.g. code snippets **
Not until recently if I change the CognitoUserPool's attributes, Amplify CLI throw the error. 
the reason why it throws the error is here: https://github.com/aws-amplify/amplify-cli/issues/1845
but, I noticed today that it is now creating the new CognitoUserPools with new attributes but leaving the old one behind. 
Is it safe to remove the old userpool?

**Comment by kaustavghosh06** [comment]
@monaye If you don't have any active users in it and don't are about the data, then yes you can go ahead and get rid of it.

**Comment by monaye** [comment]
@monaye 
Thanks, I just wanted to make sure if the resources are somehow still refereeing in the CloudFormationStack or somewhere.
