### ISSUE TITLE
Error on Amplify Console Build when using 1.9.0

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#1959]
**Describe the bug**
Version 1.9.0 on Amplify Console CI build step throws the following error:
![212](https://user-images.githubusercontent.com/3125784/62335557-c74e4880-b4fe-11e9-9dc5-ede1d357e569.PNG)

My Build Setting:
![11](https://user-images.githubusercontent.com/3125784/62335563-cddcc000-b4fe-11e9-80fb-f5e4e041d01d.PNG)

**To Reproduce**
1. Go to **Amplify Console**
2. Click on **Build Setting**
3. Add` npm install -g @aws-amplify/cli@1.9.0` on build command. 
4. Trigger a build

**Expected behavior**
It works on version 1.7.5

**Comment by kaustavghosh06** [comment]
@incr3m We just now pushed a fix for this to npm (v 1.10.0). Please install this version of the CLI and try again and let me know if you still see this.

**Comment by incr3m** [comment]
Seems fine now. Thank you @kaustavghosh06
