### ISSUE TITLE
How to update query depth after schema creation?

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#1962]
** Which Category is your question related to? **

API/GraphQL

** What AWS Services are you utilizing? **

GraphQL

** Provide additional details e.g. code snippets **

The default query depth when intializing a graphql schema is 2, however as my schema becomes more defined, I found myself needing to nest certain items within the schema, thus making the depth 4.  Without a way to update this, everytime I add a field or update my schema and have codegen run, some fields are ommitted in my queries.js and mutations.js files because they are nested deeper that 2.

Is there a way to update the depth so that updating my schema doesn't regenerate resolvers that require manual additions?

**Comment by SwaySway** [comment]
Yea to update this you can run
`amplify codegen configure`
