### ISSUE TITLE
Is there some way to use code you know that will be generated by Graphql tranform?

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#1963]
Hi, I have a question about **@function** directive in Graphql transform.

I want to restrict access to CRUD operations and turn it through AWS Lambda via @function directive and I want to use **input type** which will be generated automatically for some model by Graphql transform. 
Example:

```
type User @model {
  id: ID!
  name: String
}
type Mutation {
  submitUser(input: CreateUserInput!): User @function(name: "submitUser")
}
```

But when I'm trying to compile this I have an error: **Error: Type "CreateUserInput" not found in document**

Is there some way to use code you know that will be generated?

**Comment by SwaySway** [comment]
You can specify CreateUserInput before the gql schema gets compiled, the same way you defined adding the function in Mutation
```gql
type User @model {
  id: ID!
  name: String
}

input CreateUserInput {
  id: ID
  name: String
}

type Mutation {
  submitUser(input: CreateUserInput!): User @function(name: "submitUser")
}
```
