### ISSUE TITLE
Amplify codegen types crashes if you add a file to the src/graphql/ directory

### ISSUE THREAD

**Issue by rakannimer** [aws-amplify/amplify-cli#1967]
**Describe the bug**

Adding a file that doesn't export graphql statements as strings will make `amplify codegen types` and therefore `amplify push` crash without explanation into what happened.

In particular graphql.parse throws [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-types-generator/src/loading.ts#L60).

**To Reproduce**

Steps to reproduce the behavior with `amplify codegen types`:

1. Init an amplify project with all the defaults: `amplify init`
2. Add an API to your project: `amplify add api`
3. Create a new file inside `src/graphql` called whatever.(t|s)sx?
4. From this file export anything that isn't a valid graphql statement
5. Run `amplify codegen types`
6. Cli crashes without providing a hint

Steps to reproduce the behavior with `amplify push`:

1. Init an amplify project with all the defaults: `amplify init`
2. Add an API to your project: `amplify add api`
3. Push with Amplify and answer with defaults: `amplify push`
4. Create a new file inside `src/graphql` called whatever.(t|s)sx?
5. From this file export anything that isn't a valid graphql statement
6. Edit your schema in any way
7. Run `amplify push`
8. Cloud resources will be created successfully but the cli will mysteriously crash at the end 

**Expected behavior**

The cli should either ignore files that it did not generate or tell the user what happened or maybe the name of the file where it failed and warn not to add files in this directory.

I'd be happy to provide a PR to fix this if you'd like !

Cheers :)

**Comment by SwaySway** [comment]
@rakanimer 
After adding the file - did you change the schema and then do a push?

**Comment by SwaySway** [comment]
I was not able to run into that problem here's what I tried doing 
- Added api then push with following settings
```console
? Do you want to generate code for your newly created GraphQL API Yes
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions (Y/n)
```
- Added a custom query into a separate file in src/graphql/
- amplify push
```console
✔ All resources are updated in the cloud

GraphQL endpoint: https://*****.appsync-api.us-west-2.amazonaws.com/graphql
GraphQL API KEY: ******

✔ Downloaded the schema
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ Downloaded the schema
✔ Code generated successfully and saved in file src/API.ts
```

Is it possible for you to provide what the custom file was that you added?

**Comment by rakannimer** [comment]
Hey @SwaySway,

> After adding the file - did you change the schema and then do a push?

Yes, sorry I forgot to mention that, you can change the schema in anyway (e.g. add a field to a type) and then push.

I created a simple repo to reproduce the problem : https://github.com/rakannimer/amplify-codegen-crash-repro

The file I added is [here](https://github.com/rakannimer/amplify-codegen-crash-repro/blob/master/src/graphql/custom-queries.ts).

### Repro without push : 
1. Clone https://github.com/rakannimer/amplify-codegen-crash-repro
2. amplify init
3. amplify codegen types

The cli should crash here after logging : 

```sh
✔ Downloaded the schema
```

### Repro with push : 
1. Clone https://github.com/rakannimer/amplify-codegen-crash-repro
2. amplify init
3. amplify push

The cli should crash after updating/creating cloud resources for the project

Thanks for your time !

**Comment by SwaySway** [comment]
@rakannimer 
Ah I see that's because codegen is expecting a graphql operation within the graphql.
What kind of fix do you have in mind for a PR?

**Comment by rakannimer** [comment]
When this problem happened with me it took me some time to figure out why it was happening and what I did wrong.

So, to make it easier to debug for the next person, I was thinking we could wrap the graphql.parse code [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-types-generator/src/loading.ts#L74) with a try catch block and if it fails we would throw and log something to the user telling them which file parsing failed.

What do you think ?

**Comment by SwaySway** [comment]
@rakannimer Sounds good - We are open to PRs I can take a look once it's up.

**Comment by rakannimer** [comment]
Awesome, I opened https://github.com/aws-amplify/amplify-cli/pull/2045 we can maybe close this issue and move the discussion there.

**Comment by SwaySway** [comment]
Closing this issue as the PR has been merged
