### ISSUE TITLE
Switching accounts and resources not re-built

### ISSUE THREAD

**Issue by mlynch** [aws-amplify/amplify-cli#197]
**Describe the bug**

When switching an app to a new AWS Account, there doesn't appear to be any easy way to rebuild all the resources you already have locally. I ran `aws configure` to change my account to the new AWS Account and IAM role, then ran `aws init` again. 

I still see the old resources in the `amplify/backend` folder, and `#current-cloud-backend` is set to that folder (and has the same contents), but Amplify doesn't seem to know about it.

**To Reproduce**
1. Take an amplify app and run amplify configure to change the AWS user underneath
2. Run amplify init to re-init the project (unsure if this is necessary but without it the sources aren't seen either)
3. run amplify status or amplify push, notice no resources are listed

**Expected behavior**
I'd expect all my local resources to be re-built on the new account

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X high sierra
 - CLI: 0.1.19

**Comment by kaustavghosh06** [comment]
Hey Max. We're currently working on a feature to support multiple environments/stages (with potentially different AWS configs), which would allow you to clone the resources to that specific env. I'll update this thread once we have the feature out.

**Comment by kaustavghosh06** [comment]
@mlynch 
We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backward from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by kaustavghosh06** [comment]
Based on all of your feedback, we’ve released a beta version of the CLI (npm install -g @aws-amplify/cli@multienv)  to support multiple environments, team workflows and integrate with your CI/CD flows.
Please check out this documentation for more details - https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Also, as a part of our feedback mechanism, we’ve opened up another [GitHub issue](https://github.com/aws-amplify/amplify-cli/issues/508),  to track feedback from everyone, iterate on this beta version and then merge it to master.  We'll close this issue and track feedback in #508. Looking forward to your feedback on this release.

**Comment by kaustavghosh06** [comment]
Closing this issue since this problem is solved with the release of the multienv feature-set mentioned above. Please feel free to re-open the issue if you've further questions about this.
