### ISSUE TITLE
Prevent accidental delete of DynamoDB tables

### ISSUE THREAD

**Issue by BabyDino** [aws-amplify/amplify-cli#1970]
** Which Category is your question related to? **
DynamoDB/`@model` directive

** Provide additional details e.g. code snippets **
```
type Order @model @key(fields: ["customerEmail", "createdAt"]) {
    customerEmail: String!
    createdAt: String!
    orderId: ID!
}
```

Hi everyone,

Let's assume the code above. We have multiple environments connected to AWS Amplify. Let's also assume that our production database (DynamoDB based on `@model`) is up and running with a couple of million rows.

Now, let's change the type name from `Order` to `Test` (for whatever reason, this is still hypothetical). We `amplify push` it and two things happen:

1. The `Test-<apiId>-dev` DynamoDB table is _created_
2. The `Order-<apiId>-dev` DynamoDB table is **_deleted_**

Without warning, all our existing data is gone. So, we can create a custom role which prevents table deletion, based on this: https://aws-amplify.github.io/docs/cli-toolchain/usage?sdk=js#iam-policy-for-the-cli

However, we feel that we are missing something. We definitely want to prevent accidental deletes, both for Amplify (`amplify delete`) and DynamoDB tables.

Because we currently use a MySQL database, we use Lambda as a layer. In Amplify it is really easy to connect to to a pre-existing Lambda function (without creating it using `amplify add function`). So we can create and delete what we want without "damaging" the database.

So in an ideal world, we would like to connect to a pre-existing DynamoDB (like Lambda) which would be unaffected by an `amplify delete` or a change in type name. However by reading #1222 it seems that this is possible by creating a custom resolver. Before we explore this option further, we would really like to know if (and what) we are missing here.

#1060 seems like worth the wait, but we are having a hard time imagining that others don't have the same issue we are facing. Anyone that can point us in the right direction? Any help would be greatly appreciated!

**Comment by kaustavghosh06** [comment]
@BabyDino We can by default have a "Retain" policy on all the DDB tables generated by the GraphQL transformer to avoid these mistakes. Do you think that would be a good solution? Or do you think having a top level configuration for this policy would be ideal?

**Comment by BabyDino** [comment]
@kaustavghosh06 Retain would certainly help but in case of a mistake, typo, etc. the table becomes "orphaned"(?). If we correct the mistake we have to connect back to the original table, i.e. connect to an existing DynamoDB table.

I do understand the complexity of `@model` and `@key` directives and the fact that DynamoDB doesn't like index modifications (LSI's etc.). However, and I'm just thinking out loud here, I feel that since DynamoDB is fairly table design critical we would rather set-up the tables ourselves manually and design them to our liking before connecting them to Amplify/AppSync. This would basically means that if `@model` accepts arguments like `@function` would create a desired situation.

For example: `@model(name: "OurTableName-${env}")` would connect to our existing table and no table modifications (including delete) would take place when something changes. Of course, the `@key` directive has to match our manually defined keys. This would be solely our responsibility. Basically this solution could allow for some more manual intervention.

Does this make any sense at all?

**Comment by dallinwright** [comment]
This has bitten me many times, a workaround for now I use is assigning an explicte deny to the automation account for DynamoDB delete operations.

**Comment by BabyDino** [comment]
@dallinwright I figured that if you add `"DynamoDBEnablePointInTimeRecovery": "true"` to `parameters.json` a backup will remain available for 35 days when you delete a table. This is acceptable for us now. This is not part of the docs as far as I know: https://aws-amplify.github.io/docs/cli-toolchain/graphql#configurable-parameters

CC @kaustavghosh06

**Comment by ajhool** [comment]
Just lost my dynamo tables from a cli issue and can confirm that this would have been quite nice.

**Comment by jon144** [comment]
EC2 instances have a 'Termination Protection' setting.  If a DynamoDB table had something similar I would enable it for all my Production tables.  This type of protection is really needed to prevent accidents.

**Comment by maximelebastard** [comment]
Hi, something new about that ? What is the proper way to protect our production data from accidents ?

**Comment by zetsnotdead** [comment]
This is really important. Is it being looked at?

**Comment by ianmartorell** [comment]
I recently accidentally deleted my entire Amplify project including DynamoDB tables and all. Fortunately I able to spin a new project and recover all the data from backups. I'm now looking at how to secure everything so this doesn't happen again. 😂

CloudFormation has termination protection for stacks, but I'm still concerned about individual resources such as tables being accidentally deleted.

**Comment by l-hendriks** [comment]
Serverless has stack policies (see eg https://www.orangejellyfish.com/blog/protecting-cloudformation-stacks-with-stack-policies/) which are just cloudformation rules to prevent certain operations on certain resources.

It would be great if we could add a directive to prevent this as well in a model

**Comment by JvdWest** [comment]
I agree this is an issue. We won't be using the @model directive since this is not safe at all for production environments. A table name change or accidental removal of the @model section will wipe your data. 

Yes, you have the DynamoDB back-ups, but it's still a risky business and hard to fix in a short amount of time. 

My advice. You should either have a serverless project to deploy your DynamoDB and AppSync separate from Amplify. Or even better, Terraform your DynamoDB table and use serverless to deploy AppSync. 

Another option is to create CRUD Lambdas to update DynamoDB tables without using Amplify. All of which is quite a lot of admin, but safer.

I think a fix from Amplify could be to prevent table replacements and deletions in general. If I change the table name, just create the new table, without deleting the previous one. If I remove a data @model, just leave it be. Allow to explicitly delete tables if you really want to.

**Comment by mark-hayward** [comment]
I feel amplify cannot be a production ready service when it can delete my dynamo tables on a whim.

**Comment by VeronicaM** [comment]
> I feel amplify cannot be a production ready service when it can delete my dynamo tables on a whim.

I second that. No warning, no transparency into what is happening, no checking if you are sure you about the consequences of your choice. Very disappointing experience 😞

**Comment by CodySwannGT** [comment]
Having just experienced this with our User Pool, I can concur. Kind of necessary to be able to protect resources.

**Comment by GeorgeBellTMH** [comment]
#5972 would be helpful...

**Comment by josefaidt** [comment]
Hey y'all :wave: we really appreciate the feedback here! This is now safeguarded on `amplify push` with `--allow-destructive-graphql-schema-updates` 

> The following schema updates require replacement of the underlying DynamoDB table:
> 1. Removing or renaming a model
> 2. Modifying the [primary key](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key) of a model
> 3. Modifying a Local Secondary Index of a model (only applies to projects with [secondaryKeyAsGSI](https://docs.amplify.aws/cli/reference/feature-flags/#secondaryKeyAsGSI) turned off)

> When trying to push a schema change with one or more of these updates you will see an error message explaining that you will lose ALL DATA in any table that requires replacement

https://docs.amplify.aws/cli/graphql/overview/#update-schema

In this case we also may see some benefit in using the `@mapsTo` directive

> Amplify supports renaming models in a GraphQL schema by using the @mapsTo directive. Normally when renaming a model, Amplify will remove the underlying table for the model and create a new table with the new name. Once a table contains production data that cannot be deleted, @mapsTo can be used to specify the original name.

https://docs.amplify.aws/cli/graphql/schema-evolution/#renaming-models-while-retaining-data

Closing issue. If you are still experiencing this issue or feel the features do not quite cover your use case please reply back to this thread and we can re-open to investigate further 🙂
