### ISSUE TITLE
GraphQL transform

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-cli#1971]
** Which Category is your question related to? **
amplify api

** What AWS Services are you utilizing? **
aws amplify graphql transform

** Provide additional details e.g. code snippets **
Hi guys, 
I was wondering if we can create a user like this following example using aws amplify graphql transform in the schema. The user was created using the stripe API and the application just need to listen to the subscription changes. 
![image](https://user-images.githubusercontent.com/36496259/62445045-ac036780-b7a2-11e9-807c-745f8a540879.png)
This is what I have so far but I don't see any documentation on how to do the above example. 
![image](https://user-images.githubusercontent.com/36496259/62445067-b887c000-b7a2-11e9-8c18-f7837bfe087d.png)

**Comment by SwaySway** [comment]
Hi @totaland
Yes this is possible when you use the `@model` directive upon compilation a subscription type is generated which you can use.
[View Docs here on the @model transformer](https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage)
