### ISSUE TITLE
Allow fully-parameterized arguments for `amplify function invoke`

### ISSUE THREAD

**Issue by gabehollombe-aws** [aws-amplify/amplify-cli#1975]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use `amplify function invoke` without having to respond to a lot of interactive command prompts. Instead, I'd like to be able to pass all of the items as flags to the command line invokation.

**Describe the solution you'd like**
I'd like to be able to run something like `amplify function invoke myFuncName --handler-file=index.js --handler-function=handler --event='{"foo": "bar"}'`

Even better would be if it could try sane defaults like `index.js` and `handler` , preventing me from having to specify these for the common case where they haven't been changed.

**Comment by SwaySway** [comment]
Closing in favor of this feature-request #1992
