### ISSUE TITLE
General architecture questions about Amplify CLI

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#1976]
Sorry if I missed it in the documentation, but I couldn't find a description of the general architecture used in Amplify CLI.
Specifically I'm confused by the following

- Where are the choices I make when using amplify add and amplify update stored?
- When are the CFN templates created and updated?
- Is it possible to change those CFN templates to add our own resources? When will those changes be overwritten?

I think having general understanding of how this part works can help Amplify CLI users make some better informed decisions.

**Comment by kaustavghosh06** [comment]
@tgjorgoski  Let me try to answer your questions out here:

* The choices are stored as config file present inside your `<app-name>/amplify/<category>/<Resource-name> folder` in the form of cloudformation templates files  and  `parameters.json` file located inside the same directory.

* The CFN templates are added during `amplify <category> add` command and updated durung the `amplify update <category>` command

* Yes, you can for certain cataegories. you can read more about custom cloudformation templates out here in our documentation  - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks
You can alternatively, used a 3rd party plugin - https://www.npmjs.com/package/amplify-category-template to make use of your own resources and CFN files.

We have https://aws-amplify.github.io/docs/cli-toolchain/usage#architecture in our docs which explains as to how the CLI is architected in the form of plugins and touches the file artifacts generated by the CLI - going over the amplify add/update/push commands.

**Comment by tgjorgoski** [comment]
Thanks!
So, am I to understand that Amplify CLI, or more precisely category plugins are not storing the configuration choices form  in any simpler form, but they are in fact directly generating CFN templates?
I was imagining there is some configuration file which stores the basic configuration, and that the CFNs could be regenerated at any time based on that config.

**Comment by kaustavghosh06** [comment]
@tgjorgoski I would say it's not the same accross all categories. For AppSync, we have a concept of annotated schema, which defines your infrastructure and based on that we generate the CFN templates.
