### ISSUE TITLE
GraphQL API with @searchable accepts only Int as nextToken

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#1977]
We currently have a model with 1000+ records, using searchable query returns a **Long number** as nextToken. now, trying to fetch the next results seems impossible right as it only accepts **Int**.
 
![image](https://user-images.githubusercontent.com/3125784/62517380-e3811b00-b859-11e9-9d81-c5e5e027d2f8.png)

Is there a work around to fetch the next results?

I'm using **amplify cli version 1.10.0**

**Comment by SwaySway** [comment]
This change is included in the #1775 which also aims to solve #800 and make nextToken into a string.
Closing a duplicate to track in #800
