### ISSUE TITLE
auth category ignored in headless amplify init/configure project

### ISSUE THREAD

**Issue by Joespower** [aws-amplify/amplify-cli#1979]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
CI / Headless
** What AWS Services are you utilizing? **
Amplify CLI
** Provide additional details e.g. code snippets **
I'm attempting to use the headless feature of amplify CLI to pass parameters to amplify init/configure project (I've tried both). According to the best documentation I've been able to find, this code should initialize my project and add the auth category. Initialization appears to be successful, but the auth doesn't get added (or even attempted from what I can tell).  When run, I receive no errors. I have tried different syntaxes for the AUTHCONFIG section, especially surrounding the empty array, but even in the scenarios where I've received no errors (and there have been a few), the auth never gets added. Am I misusing the --categories flag here?? See below code:

```
#!/bin/bash
cd /home/ec2-user/environment/photo-albums

set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"

AMPLIFY="{\
\"projectName\":\"photo-albums\",\
\"envName\":\"master\",\
\"defaultEditor\":\"none\"\
}"

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

AUTHCONFIG="{\
\"useDefault\":\"default\",\
\"usernameAttributes\":\"username\",\
\"additionalQuestions\":"[]"\
}"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes

```

**Comment by kaustavghosh06** [comment]
@Joespower Do you have auth already added to your project? What does you `amplify/backend/backend-config.json` file look like?

**Comment by Joespower** [comment]
@kaustavghosh06 no, I started with a clean project.  When I cat the file I get the below output:

Admin:~/environment/photo-albums (master) $ cat amplify/backend/backend-config.json                                                                            
{}Admin:~/environment/photo-albums (master) $ 

This is after several attempts to get this to work, and running amplify delete after.

**Comment by kaustavghosh06** [comment]
@Joespower You would need to add `auth` using `amplify add auth` command and then use the script mentioned above for CI/CD. There is no way to add auth in a headless moth currently. Curious to know where you read about the following configs:

```
AUTHCONFIG="{\
\"useDefault\":\"default\",\
\"usernameAttributes\":\"username\",\
\"additionalQuestions\":"[]"\
}"

```

**Comment by Joespower** [comment]
I'm confused.  I must not understand the use case for headless.  I based my bash code on sample code that is specifically called out in the documentation [here](https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli).  Also, the sample code is [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/sample-headless-scripts/headless_init_env_auth.sh).  I wanted a different outcome for authentication than what the example code gave, so I searched for documentation on what to use and found none.  I ended up basing what I chose on:

[](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/supported-services.json)
 -AND-
[](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/assets/string-maps.js)

...Using the prompts for the auth stuff to locate a key and the mappings to identify a value that should work.  Could you maybe elaborate on what you mean by your statement?  Esentially, my end goal is to have an automated (scripted) test deployment based on the parameters that drive my project.  I thought that's what this was for...

**Comment by kaustavghosh06** [comment]
@Joespower So the script out here would be to create a new env and passing in params which the auth category would need if auth is already added via the CLI (this information is env specific and based off the `amplify/backend/team-provider-info.json` file.

**Comment by jmcgeheeiv** [comment]
I also see this ignored--my `amplify/backend/backend-config.json` file is empty when I use `amplify init --categories`. When I use `amplify add auth`, I do get stuff added to `amplify/backend/backend-config.json`.

FWIW, this functionality was supposedly added in #465, but the attributes set by @Joespower's do not appear in the test.

**Comment by bwalsh** [comment]
Burning way too much time on this.   Various git issues ranging back years.  Clearly stated in the doc and in the samples that it should work.   No fixes, workarounds or even a clear admission of a bug.  Disappointing.

**Comment by kaustavghosh06** [comment]
@jmcgeheeiv @bwalsh There isn't a headless way of adding the auth category as of today and none of our docs state that way. The headless commands are currently just used in CI/CD enviornments for initing a new env based of an existing environment and pushing resources initialized using the CLI to the cloud. @bwalsh What are you trying to achieve?

**Comment by bwalsh** [comment]
Handoff to corporate devops so that they can reliably create amplify
instances.

**Comment by jmcgeheeiv** [comment]
@bwalsh, I found a non-interactive build very useful while iterating to find find the right versions of node, angular, amplify, etc.

Then, once things started to come up, I committed my Angular/Amplify project to Git and began to use the [Team environment](https://docs.amplify.aws/cli/teams/overview) workflow, beginning with:
```shell
amplify init --app gitURL
```
This does stuff like `amplify add auth` and `amplify add storage` completely automatically. The Team environment workflow seems much more solid and well-used. Importantly, it gets you the infrastructure-as-code that your corporate DevOps team needs.

However, I could not use `--providers` to specify the Amplify administrator profile:
```shell
yes "" | amplify init --app gitURL --providers '{...}'   # Uses the default administrator profile
```
so it is still not possible to create an Amplify project without human intervention (headless). But it is still quite an improvement.

As a workaround, you could:
- Name your Amplify administrator account `default` (rather odious), or
- Perhaps commit `amplify/.config/local-aws-info.json` to Git, contrary to `.gitignore`. I have not tried this yet.

Regarding the above `yes "" | amplify init ...` trick, see #4242.
