### ISSUE TITLE
No targetable endpoints for push notifications in Pinpoint after registering endpoint

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#1983]
** Which Category is your question related to? **
notifications

** What AWS Services are you utilizing? **
Pinpoint, Amplify

** Provide additional details e.g. code snippets **
Hi - I followed the tutorial to enable push notifications in my amplify project. I generated a .p12 file and referenced it when adding notifications. I added analytics to my project. I added all the necessary code as well. When the app launches it requests permission for push notifications. I see an endpoint has registered in Pinpoint. But it tells me that there are no targetable endpoints (see attached). I repeated the process a few times with no luck. Has anyone seen this before?

![image](https://user-images.githubusercontent.com/24530625/62593335-2a3b3900-b88b-11e9-9b42-2ffc669527a4.png)

**Comment by rawadrifai** [comment]
I was able to see the endpoint by adding `optOut: 'NONE'` in my Analytics.updateEndpoint({...}). 
I am trying to send a test message using the endpoint id.. which I assume is the address. Pinpoint says endpoint does not exist.

here's the call to updateEndpoint:
```
    Analytics.updateEndpoint({
      address: 'rawad1', // The unique identifier for the recipient. For example, an address could be a device token, email address, or mobile phone number.
      attributes: {

        hobbies: ['piano', 'hiking'],
      },
      channelType: 'APNS', // The channel type. Valid values: APNS, GCM
      demographic: {
      },
      location: {

      },
      metrics: {

      },

      optOut: 'NONE',

      userId: 'rawad1',

      userAttributes: {
        interests: ['football', 'basketball', 'AWS']

      }
    }).then(() => {
      console.log('updated endpoint')
    });
```

**Comment by dantasfiles** [comment]
I found the [AWS CLI easier to use for testing push notifications than the Pinpoint console](https://medium.com/@dantasfiles/testing-push-notifications-with-aws-amplify-9126bd621d3a). You have more possible commands you can run for testing and those commands give useful return values. Pinpoint console just says the equivalent of "I can't send your test message, sorry."
