### ISSUE TITLE
Querying Many to Many

### ISSUE THREAD

**Issue by DanNeish** [aws-amplify/amplify-cli#1986]
I'm using an Amplify API Graphql backend and Cognito User Pool for a react app. I have several many-to-many relationships and am struggling to work out the most efficient way to query them.
The schema is below.

```gql
type User @model {
  id: ID!
  email: AWSEmail!
  firstName: String!
  projects: [ProjectCollaborator!]! @connection(name: "UserProjects")
  assignedTasks: [TaskAssignee!]! @connection(name: "UserAssignedTasks")
}

type Project @model @versioned {
  id: ID!
  name: String!
  description: String
  state: ProjectState!
  dueDateTime: AWSDateTime
  tasks: [Task!]! @connection(name: "ProjectTasks")
  taskOrder: [ID!]! # an array to set the desired order of tasks
  collaborators: [ProjectCollaborator!]!
    @connection(name: "ProjectCollaborators")
}

enum ProjectState {
  ACTIVE
  ON_HOLD
  COMPLETED
}

type Task @model @versioned {
  id: ID!
  name: String!
  state: TaskState!
  dueDateTime: AWSDateTime
  project: Project! @connection(name: "ProjectTasks")
  assignees: [TaskAssignee!]! @connection(name: "TaskAssignees")
}

enum TaskState {
  ACTIVE
  COMPLETED
}

# MANY-TO-MANY JOIN TABLES
type ProjectCollaborator @model {
  id: ID!
  project: Project!
    @connection(name: "ProjectCollaborators", sortField: "dueDateTime")
  collaborator: User! @connection(name: "UserProjects")
}

type TaskAssignee @model {
  id: ID!
  task: Task! @connection(name: "TaskAssignees", sortField: "dueDateTime")
  assignee: User! @connection(name: "UserAssignedTasks")
}
```

What would be the best way to obtain the following data:
1. Get Projects where userId is in Collaborator, State is ACTIVE, sort by DueDate ASC.
2. Get Tasks where userId is in Assignee, State is ACTIVE, sort by DueDate ASC.
3. Get next 3 Tasks in actionOrder where Project=X, userId in Assignees and State is Active

I have looked into using GSIs on the tasks table for example:
```gql
@key(
    name: "ByState"
    fields: ["state", "dueDateTime"]
    queryField: "actionsByState"
   )
```
This form of GSI makes it efficient to get all Active tasks or all Active tasks with dueDateRange=X. I don't know how to also specify the assignee. Querying through the User model can return all tasks assigned to that user, but how would you efficiently return only those tasks that have a State of Active?
Any advice would be greatly appreciated.

**Comment by SwaySway** [comment]
@DanNeish Are you referring to using the `@key` on the many-to-many types?

**Comment by DanNeish** [comment]
@SwaySway In that example I'm referring to using the @key on the `type Task @model`. In this case, to solve number 2, my approach would be to query through the User (tasks) -> TaskAssignee -> Task (where state = ACTIVE). How would you do that query?

**Comment by SwaySway** [comment]
@DanNeish Yea you can add a @key directive for case 1 & 2.
For example in case two you can change the Task Type to the following
```gql
type Task @model @versioned @key(name: "ByState", fields: ["state"], queryField: "tasksByAssignee") {
  id: ID!
  name: String!
  state: TaskState!
  dueDateTime: AWSDateTime
  project: Project! @connection(name: "ProjectTasks")
  assignees: [TaskAssignee!]! @connection(name: "TaskAssignees")
}
```
With this you can do a query on tasks based on assignees the sortDirection is by default (though after this pr #1990 you should be able to specify sortDirection). The query would look like the following
```gql
query TasksByAssignee {
  tasksByAssignee(state: ACTIVE) {
    items {
      name
      state
      assignees {
        items {
          assignee {
            firstName
            email
          }
        }
      }
    }
  }
}
```

For your last case you could use the task IDs as a way to order them for projects since this looks like a one to many connection.

**Comment by DanNeish** [comment]
@SwaySway thanks for the feedback. In your TasksByAssignee example query, how would you then also limit it to a particular assignee (user ID)?

**Comment by SwaySway** [comment]
@DanNeish 
Since you created the type taskassignee you can use the TaskAssigneeID, since it's unique to student/task as a filter when listing the assignees.
