### ISSUE TITLE
Is it possible to create composite GSI 

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-cli#1987]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
GraphQL Transform

** What AWS Services are you utilizing? **
Amplify Cli

** Provide additional details e.g. code snippets **

When i add composite key in GraphQl transform an UPDATED_FAILED issue is responding. 

UPDATE_FAILED               GraphQLSchema                                           AWS::AppSync::GraphQLSchema Wed Aug 07 2019 11:55:26 GMT+0200 (GMT+02:00) Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.

Here is my Schema : 

```gql
type Directory
	@model	
	@key(name: "gsi-ByOwnerIdOByMailDateAsc", fields: ["ownerId", "email", "createdAt"], queryField: "getDirectoryByOwnerIdOByMailDateAsc")
  	@auth(
    	rules: [
      		{allow: owner, ownerField: "ownerId", identityField: "sub"},
    	]) 
	{
	id: ID!
	ownerId: String		
	createdAt: AWSDateTime
	updatedAt: AWSDateTime	
	givenName: String
	familyName: String
	email: String 
}
```

If i remove the key line, the push is going well. The issue is really going from the composite key line.
Maybe it isn't yet possible to create a composite index or am i doing something wrong ?

**Comment by SwaySway** [comment]
Adding a dash in the name creates an input type with the dash, which is not a valid schema.
- View AppSync Type Docs [here](https://docs.aws.amazon.com/appsync/latest/APIReference/API_Type.html)

Removing the dash, or even replacing it with an underscore, would be create a valid GraphQL Schema.
