### ISSUE TITLE
Error when trying to install v1.11.0 in Ubuntu

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#1994]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I do `npm i -g @aws-amplify/cli` it ends with these errors:
```
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/home/******/.cache/node-gyp/11.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@aws-amplify/cli/node_modules/kerberos/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@aws-amplify/cli/node_modules/kerberos/.node-gyp'
gyp ERR! System Linux 5.0.0-23-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@aws-amplify/cli/node_modules/kerberos
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

Even when trying the command with `sudo` it doesn't work.

**To Reproduce**
1. Install @aws-amplify/cli@1.11.0 on Ubuntu

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04

**Additional context**
Installing 1.10.0  works fine

**Comment by kaustavghosh06** [comment]
What’s the error that you get with sudo?

**Comment by nino-moreton** [comment]
Same error

**Comment by nino-moreton** [comment]
Did a bit more searching and apparently as per #943 if I add in the `--unsafe-perm` flag after sudo, it installs fine.

Not sure if I should keep this open @kaustavghosh06

**Comment by kaustavghosh06** [comment]
@nino-moreton Yes, I've seen using `npm install -g @aws-amplify/cli@beta --unsafe-perm=true` make the installation work (and resolve the gyp issues) for certain npm versons  installed.
