### ISSUE TITLE
amplify-cli output log is overly verbose, repetitive and redundant

### ISSUE THREAD

**Issue by krsnaa** [aws-amplify/amplify-cli#2001]
**Is your feature request related to a problem? Please describe.**
The output of a long-running process like `amplify push` is extremely verbose, repetitive and redundant. For eg., the output of a simple `add api` operation is 294 lines, without word-wrapping. Of the above, a full 64 lines are `Updating resources in the cloud. This may take a few minutes...`. If you take into account the 80-120 character widths of most IDEs, you are looking at a significant multiple of the above and pages and pages of logs.  There is significant potential to improve clarity around the reporting. 

**Describe the solution you'd like**
A simple in-place table of resources being created/updated with the current status of the operation alongside it would be much better at providing a clear picture of the resources in play and their current status. Right now, one would have to laboriously parse pretty much every single line of the logs to find the various stacks, roles, resolvers and other resources created. 

**Describe alternatives you've considered**
If there is really a use-case for such a verbose log that is being generated at the moment, it could be dumped into a file or can be displayed on stdout with a --verbose flag.

**Additional context**
Let's not forget that for most people trying out amplify-cli, this is probably their first touchpoint on the AWS compute stack. If not, they probably would have been targeting AppSync directly. Ensuring clarity of messaging and logs should be high on the list of priorities.

**Comment by jhockett** [comment]
Hi @krsnaa, this feature was introduced in https://github.com/aws-amplify/amplify-cli/pull/10720. You can try it out in the latest release!
