### ISSUE TITLE
Possible issue with directories for local development

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#2002]
**Describe the bug**
It seems like duplicate directories may be created when running a local mock... I'm not sure if this is intended or not.  src\graphql is being created, as well as src\API - these seem weird.

**To Reproduce**
1. run `amplify mock` in the root of a project
**Expected behavior**
It seems like it should use the directory structure that's already there?

**Screenshots**
![image](https://user-images.githubusercontent.com/686823/62741302-08af8e00-ba00-11e9-9afc-4f01e207ea7a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX

amplify -v
1.11.0

**Comment by yuth** [comment]
@mwarger thanks for reporting this. Could you please clarify the following. 
1. You are using Mac or windows?
2. The directory that gets created is inside `src`. By that I mean the directory is`<proj-root>/src/src/graphql`

**Comment by mwarger** [comment]
@yuth I'm using Mac.

2 - It's being created outside.

![image](https://user-images.githubusercontent.com/686823/62746130-d9a31780-ba13-11e9-997a-ad2823b7fd4a.png)

**Comment by yuth** [comment]
I suspect this has to do with how we join the path. Just curious if updated the codegen on windows to get `\` in the path.

**Comment by yuth** [comment]
this is fixed in #2212
