### ISSUE TITLE
Removing CLI generated resources after creating new environment via Console

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#2009]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
CLI

** What AWS Services are you utilizing? **
API Gateway Cognito, DynamoDB & S3 Storage

** Provide additional details e.g. code snippets **
- I initialized an app, using amplify init, and (stupidly) called the environment "beta".
- I provisioned resources, using the CLI.
- I linked the app to a Github repo in the console and created a new environment, deploying from the master branch.
- This created all new services.
- I copied S3 and DynamoDB data to the newly created storage.
- I recreated users in the Cognito user pool

Everything seems to be working lovely in the new environment.

**QUESTIONS**:  I don't really need or want the beta environment services any more, but I'm not sure of the consequences of deleting them via the CLI.  What's the proper way to remove them that will enable me to continue to deploy via pushes to my repo?

**Comment by kimfucious** [comment]
Further to this (yes, I'm confused):

I've created a new branch in my repo (dev) and connected it in the Amplify Console.  So now, I have two deployments both front and back ends.

On my local dev machine, I still have the beta env.

QUESTION:  What's the best way to align the envs in the CLI with those in the console?

My ultimate goal is to:
- develop in dev (locally) in a separate front/back end from prod
- push changes to the dev branch, which get auto-deployed for testing (this works)
- merge dev to master and auto deploy a production build

Right now, all the work done in local is still accessing the beta env created with cli.  And I want to access the dev env that was created via the console.

**Comment by kimfucious** [comment]
Okay, it think I've figured this out, and I was making it way more complicated that it really is.

I made the diagram below to get it straight in my brain.  Kindly let me know if my understanding is correct.

![Amplify Envs](https://user-images.githubusercontent.com/26792769/62825238-bbcfe100-bbd2-11e9-92bc-6ba8084e421d.jpg)

**Comment by kimfucious** [comment]
draw.io file is [here](https://www.draw.io/?lightbox=1&highlight=FF8000&edit=_blank&layers=1&nav=1#R7V1bc6M4Fv41qe1%2BaApduD3GdtzTVT1bvdO7OzNPKRlkm2mMWMCJ3b9%2BJRAYIXwbX8jFSVViCSEkne8cnfNJyHdouFh9Tkky%2F5UFNLqDZrC6Q6M7CD0X8L8iY11mWNApM2ZpGJRZYJPxPfxJZaYpc5dhQDOlYM5YlIeJmumzOKZ%2BruSRNGXParEpi9SnJmRGtYzvPon03N%2FDIJ%2FLXGB7mwu%2F0HA2l492q%2F4tSFVY9iSbk4A9N7LQwx0apozl5afFakgjMXbVuJT3jbdcrRuW0jg%2F5IaY0f%2F%2B65%2F0tz8%2BT8n8839%2BQWsTfhI3FI3L11WPacAHQCZjFvN%2Fg5Qt44CKekyeYmk%2BZzMWk%2BgrYwnPBDzzL5rnayk%2BsswZz5rni0he5U1M1380E3%2BKygyrSo5WsvIytW6mvtE0XNCcpjIzy0ma3wvZ8gw%2FIlkW%2BlX2OIyqZ5YdE73ZOmAyK2PL1Kc7RsmVwCPpjOY7ygGnlivXB8p4q9M1vzGlEcnDJ7UhRCJzVpfbCI9%2FkPI7RpaorPiJREv5qDtokwUX0SCeZOLfUGoJNO%2BThD9kkJLYn3P9apXTQJHTVa6KNKVZ%2BJNMigJCKgkL47zokjW4s0Y8h0ThLBYi4uMthDd4omkectW6lxcWYRCI%2BwcRmdBoQPwfswJpQxaxtHgumhY%2FdYtEDXTVpfiyJRt1a8p5B%2FR1YcnqP5mGaUOrrGytPPJgccrKv4mhadSMlUo%2FQcMBCGMIkMXtI%2FActUI2nWYcdW101C3%2B%2B4BBV1b%2Bhr7%2Fqah7t%2FL3oMClvPtSYMvtUuBIKF6WkFiRlP2%2FpZg4Bn6pK%2FeikbPJB8Q7wBWAP9%2FETv3Rhh83d%2FBPM%2FH%2FfpFE4VT0jluFjPF65bN428vHleWq7El65gZcsG%2FDlJKcd8iM6bPAUPwUpixeCNy8nU5%2BWJCMG9aPW7v09m042mvDMTaham7RaUZcVgNNA1kOwNAt%2FjrYvZbVrgZHsRJXNeNn8OHOaNurSOHy3ln3dI49FWCuY1RuQ1VJ2TR53wUQAfY6frNQtDhZZnP%2B70NOs%2Fzju%2FT5zG4IyOpNA7iqx1f5aqe6fKBVrWXYALgutF0EMPDQ9Xw%2BoMn5jfp8h9sF1KfT51ma8jY8s69fmp5JObGT%2BjL3a0STgoD%2FDejTe9DgEr%2B7ZnxgIldRthOjtsvrJHA0CHwu7PVvNGEd8n%2FOPtFVwrUyM%2F7K9Ot05UdLob1tONQMlJB8QLJ5reENhGR5yn7QSpjSHkzDKGrI1zQdb2RXEPjGsjAPWSdovrYKTFies0UHqnJhWHTw8SYnovWL1UzQiwb5uUypwWezx5SPDa%2BWiZHfjjPNcGxFDrYdBTU2NKRmPm94P0vCdN5g%2FKq884eD1lVMtUKnyUqbXFpppAOdcOOZ%2FdJtqN9o3d7rdY1oEjHRIiZiv6YP1na92jrcLiE8tiIaHN8JalnEfe%2FRf7O2SLz23yCsHJwzhXvVvFI1sXbgruWwVdHFFiuwUfiHTW5%2F%2FtsrNib2icakuJV3jKwbBaSGbcWVbaq4AqC1iLOnPNxTHltoV3n%2BoWzxeSHbuRBx4zGPr%2Fp98JgVHfFeWUxvL4sJLEslmU6MaWQtqHXH5WaxrpWNlmDZMo%2FCmA7rhXwhyymL84YQ%2BO9YPHXAo4EgpMq1McLYhY1rozDlFZVxRyzmQD2QGQwBsmwt6mmKW4mTzhXWNNAreiinYQCrtBwV8UiSJeVwTMOVaIceEj1n2OA6UEyEX3zRHqES5Se11ILEZEaF%2BXj0pa08S%2BzkANcwGz%2BqC4bdjkjKcfVIynG3A%2FgkVx2h1%2BRDvTHC%2FFiXCGCVvsFot4fTot%2FV4pdxcBDeG%2FqphPtmpe4th2y7jQRCluF5tms6wMYIQ5VuwZZh7QFSB6vejvUM13MBcFzsYhN67vW2UmB7p4U5G62%2BCvN6CY5%2FLlfgoExt7IlIrBuJtjVpmCZ4pG0KWtHdJnDrZ28WPpUE6saWWMYDzrYpDViOYXqNGQ%2Bp9Zet1hb8OmyduhfIxddeO8T68oOG5LbHkXG7khkZmdJ8bcQtiLY8rOlUDE%2BXhzUeyyvncqo0T6nlPO43cocbM%2Bip5quuouHioA6yGF2KLAYH7ArQBqghtqRhIaRmd5HxW9YPwkWxjVZzZmX%2BKFzMeK%2BicCL6lvmEh7TjEX2SAbuRPc3OIxYAVbrDtjWpdFH4GO6afE5jib39chHTcXLBmRerxgtadpe33hgjWC1XK%2BscyL4UdnW%2BqFjNVPkOM6PpU%2BjTTBs%2F1ScaCK7BFL4RHIpUYVGVjHbaUTOAnhJ1qBnttKNmgHb1oPV80G5gI0NLKdWbreebjQYWDmFnIN0OmKWONyzA8zzM6feEFLPtMzf0BwSnnbFoCWfxyK4YtLj6yD8%2B%2BhFbBo%2BkpJXas0Md6TfnE9no3fNBRKeSqPLDePa1SI3QLjJBMWUHWaEdqq5rYY%2BKpccpX%2B5%2F1fTnJOalJvm3ESgth6B71Lf5AHXs0pZ57Rzs4lb2QdpsQRpscCMwsw3gScqCpZ9LriXphHkY8PaE%2BfqRxBzjPjdb2eOGfrkIzqolAtUzQfoU6HZMgQ68FAb3z3%2BnMn%2B2eY%2BQcxzzBx0HgPfD%2FGXoopBrbbipvNze%2BL7LYw6PHH7xOMzxHzzw3g3mgnVMFiyYXBF5uJJ0X8gDVzB3Yws72DsOekMHIDB%2BN9AjSfg4Izl9JgfvDjsD%2BvjM2jP64BXQ57gPJj4OfSPTGgLn3aAvIotJQK4IPAR7XmCzD2CfLs1yIKzusX9xNAfSNwzKbX03nuPGc7wensPe8hJNj5qlb6C%2F8RyvnufYhrOa5zBUg98304F1FJ7d%2B7pRHZemOo5FXe9kB77C3rob23EdtuNY8PXOd%2BADljdvfMer4TuOxV%2FvjId1QOB5YzxeA%2BNxtLfXO%2BdxANV7ac7Dxl5bIy3wt1gPfKnYDOobzKr3F2%2B8x433eE28xxZd7FG3dEbxxnu8ft5jj81%2FWfs7rNsGj5fggZ3KehyFud45j%2BptyBvn8QY4j6Og1zvjYV1hc9GN8bge43EU%2BvrnO7rePLzxHa%2BR7zjOy%2Bud7XgB77F4yFO1ESDDa%2F442hgBu8MXFq%2F7NDkSdKkx072Ub2VoERYHQv1OJxz4VD%2F9afO%2BcGuE96pNQx8OPWHtoPPeBg9j2KUyxXFsz2U%2FHmc0pmnxvmfB2ND04YmWxA04TVX2v1hx5be6bN0J%2BHe5lWe7TOUpJzeJ7pBoVU31NmOl6IaLIXBMDyMT819A61db%2BsOA42jCvPBJqnwM7hrvaotvKECnf4PGizilC0kp7T2Twu71sNZqen2hp%2Be%2BOWHDPoWN9JWLzoMa9%2BYMBRE%2BTllxalf74MfdB4Kc6st72BoVdv4IX966R%2BbAeje%2BfLFMMS2kc5Z30D0XKpNXtUWiL8%2Fd61oiLyE6LSBp%2BrWEN0ezCVRNEdVPa4sYl%2BSdPG%2FaXBB%2FzvHZcQpxwOJ%2FiMqXmTi%2FbkL8H9yedJTziyPuAtHAkPC%2FW4%2Fz0zWMD0fZg5d6VFzKciKVYefS0%2BmhEfQsw8MAODZ2TMt1W6c%2BmpYBoG1bNo%2BhHLBjOUo%2BoH1MiVLbJ2watunayHG5gUEAnOGrL3hy801oZfHN18mhh%2F8D), if anyone cares to do something with it.

**Comment by kaustavghosh06** [comment]
@kimfucious The above diagram seems correct and thank you for this. This is one of the use-cases when a developer would have his/her own sandbox environments (in your case dev env) and then use probably a different environments for test and master.

**Comment by kaustavghosh06** [comment]
Also you can use `amplify env remove <env-name>` from the CLI to delete all the resources for your environemnt - `env-name`. You can also import the backend resources generated by the Amplify console using a CLI command (`amplify env import`) which you can easily copy from the Amplify console by following these instructions - https://github.com/aws-samples/create-react-app-auth-amplify/blob/master/README.md#run-locally-with-the-amplify-cli

**Comment by kimfucious** [comment]
Thanks for the clarification, @kaustavghosh06 

And thanks for the tip regarding the import of the backend into the CLI via `env import`.  This made a light bulb go off for me, which was dim before.
