### ISSUE TITLE
Is it possible to use same GSI for @key and @connection

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#2011]
I have table with connection to other table:

```gql
type Entity @model
{
  id: String!
  conn: [Conn] @connection(name: "Connections", keyField: "fromId", sortField: "toId")
}

type Conn @model
    @key(name: "Connections", fields: ["fromId", "toId"], queryField: "listConns")
{
  id: ID!
  fromId: String!
  toId: String!
  from: Entity! @connection(name: "Connections", keyField: "fromId", sortField: "toId")
}
```

When I push this schema, I got two absolutely identical GSI indexes but with defferent names.

I need to query both related connection and separate query, how can I reach this?

**Comment by attilah** [comment]
@lenarmazitov ```@key``` and ```@connection``` is two different independent feature in separate modules, so currently there is no way to associate the same generated GSI with them. I mark it as a feature request and will discuss with the team about possible solutions.

**Comment by kaustavghosh06** [comment]
@lenarmazitov Right now this is not possible, but we're actively working on a feature to make this possible.
