### ISSUE TITLE
Dynamic group @auth returns records with null/undefined groups field

### ISSUE THREAD

**Issue by struct78** [aws-amplify/amplify-cli#2013]
**Describe the bug**
Using dynamic group authorisation allows records with null/undefined values in the groupsField to be returned, and possibly updated and deleted.

**To Reproduce**
1. Create a simple GraphQL schema and `amplify push` it.

```
type Record @model @auth (rules: [
	{ allow: groups, groupsField: "groups", operations: [read, update] }
]) {
    id: ID!=
    name: String!
    groups: [String]
}
```

2. Add a record to DynamoDB **without** the groups field set (or set the value to null)
```
{ 
    id: "b33716a0-c310-498b-b91b-cd195fd80d07",
    name: "Secret test record"
}
```

3. Add a record to DynamoDB with the groups field set to an empty array OR insert the ID of a group you've set up in Cognito.

```
{ 
    id: "8c779bef-0130-46b6-8762-7df98ce54652",
    name: "Super secret test record",
    groups: []
}
```

3. Call listRecords API endpoint. The super secret test record with the groups field with the empty array is excluded successfully, the secret test record with the missing groups field is not.
```
{
  data: {
     listRecords: {
       items: [{ 
         id: "b33716a0-c310-498b-b91b-cd195fd80d07",
         name: "Secret test record"
       }]
     }
  }
}
```

**Expected behavior**
I would expect that if the groupsField value is missing, it should not be returned. 

Playing around with the response mapping template, I was able to fix the problem by changing this line from:

```
    ## Authorization rule: { allow: groups, groupsField: "groups" } **
    #set( $allowedGroups = $item.groups)
```

to: 
```
    ## Authorization rule: { allow: groups, groupsField: "groups" } **
    #set( $allowedGroups = $util.defaultIfNull($item.groups, []) )
```

**Comment by attilah** [comment]
Thanks @struct78 for reporting, we'll take a look and discuss this behavior with the team.
