### ISSUE TITLE
Auth - Template format error: Parameter count xxx is greater than max allowed 60

### ISSUE THREAD

**Issue by Zurdge** [aws-amplify/amplify-cli#2015]
I'm trying to add users to a group when they signup.

Using the default Auth configuration I am able to create and update my Auth without any issues and it pushes correctly

If I select "Walkthrough all the auth configurations" and use the option "Add user to group" then I cannot push my updated Auth config.

The Error I get is -
"UPDATE_FAILED               authwebportaldaf1c410        AWS::CloudFormation::Stack Mon Aug 12 2019 17:25:44 GMT+0900 (Japan Standard Time) Template format error: Parameter count 63 is greater than max allowed 60"

I found this post - https://github.com/aws-amplify/amplify-cli/issues/1937

However I wasn't sure if it resolved or not...

Is this a bug or am I doing something wrong?

**Comment by ssypi** [comment]
It seems to be fixed in cli version 1.11.0. Check your version with "amplify -v". I also had to run "amplify update auth" again after updating to the fixed cli, just pushing didn't work.

**Comment by kaustavghosh06** [comment]
@Zurdge @ssypi is right. We fixed it in the latest version of the CLI. If you go through the `amplify auth update` flow and then run `amplify push`, you should be able to make this work. Please comment on  this issue if you're still getting the same error.
