### ISSUE TITLE
Amplify-category-auth uses Jest as normal dependency

### ISSUE THREAD

**Issue by KLaci** [aws-amplify/amplify-cli#2017]
**Describe the bug**
Amplify-category-auth project contains Jest as a normal dependency instead of it being just a devDependency.

**To Reproduce**
1. Go to https://github.com/aws-amplify/amplify-cli/blob/8bbb701317f6d6df78afed250e1e40e3c54c3b86/packages/amplify-category-auth/package.json

**Expected behavior**
Jest should be provided as a devDependency.

**Comment by attilah** [comment]
@KLaci thanks for the reporting, I've reviewed every package in the project and fixing where we have this or a similar problem.
