### ISSUE TITLE
Add `amplify push -y`

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#2018]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to push changes to the cloud while working on other stuff. I frequently forget to hit `y` a couple of times, especially after changes to the API. And I see my coworkers do the same. Sometimes you work on something else, come back after 10 minutes and see that the CLI waits for you to hit enter.

**Describe the solution you'd like**
It would be cool to have a CLI command that just `y`esses the prompts, e.g. `amplify push -y`.

**Describe alternatives you've considered**
There are no alternatives. This is a small quality of life improvement that can help prevent human error and wasted time.

**Comment by kaustavghosh06** [comment]
@janhesters We aleady have this - you just missed one of the dashes in front of your `y` in the command. The headless command is `amplify push --y`

**Comment by janhesters** [comment]
@kaustavghosh06 Oh wow, my bad, sorry. Thank you very much!
