### ISSUE TITLE
Issue Reading @auth Protected Model With Shared @connection

### ISSUE THREAD

**Issue by amcbb** [aws-amplify/amplify-cli#2020]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
AppSync, Amplify, Cognito
** Provide additional details e.g. code snippets **

I am struggling with an issue surrounding mixed usage of @auth and @connection tags.  Please see the sample schema, desired restrictions, and description of the problem below.

```gql
type UserTypeA @model @auth(rules: [{allow: owner}]){
	id: ID!
	field: String
	models: [MyModel] @connection(name: "TypeMyModel")
}

type UserTypeB @model{
	id: ID!
	data: String
	models: [MyModel] @connection(name: "TypeBModel") @auth(rules: [{ allow: owner }])
}

type MyModel @model @auth(rules: [{allow: owner}]){
	modelData: String
	typeA: UserTypeA @connection(name: "TypeMyModel")
	typeB: UserTypeB @connection(name: "TypeBModel")
}

```
Restrictions:
> UserTypeA should only be accessible by the UserTypeA owner
> UserTypeB should be accessible by all except only the UserTypeB model owner should be able to see the "models" field (hence the field level authorization tag)
> MyModel desired restrictions are a bit more complicated, and this is where the issue lies.

I want both UserTypeA and UserTypeB owners to be able to query MyModel if UserTypeA and UserTypeB have a connection with the same MyModel.  The issue is, UserTypeB receives null when trying to retrieve the field typeA (authorization failure) on MyModel queries.  UserTypeA is able to read both fields since UserTypeB does not have a model level @auth tag.

How can I allow UserTypeB to read the typeA field on MyModel if and only if they share that same connection to MyModel.

**Comment by attilah** [comment]
@amcbb It I understand correctly the use case you described, one possible solution came to my mind if you could try it, but custom resolvers would be the best for this specific requirement.

```graphql
type UserTypeA @model @auth(rules: [{allow: owner, ownerField: "userTypeAOwner"}]){
	id: ID!
	field: String
	models: [MyModel] @connection(name: "TypeMyModel")
}

type UserTypeB @model{
	id: ID!
	data: String
	models: [MyModel] @connection(name: "TypeBModel") @auth(rules: [{ allow: owner, ownerField: "userTypeBOwner" }])
}

type MyModel @model @auth(rules: [{allow: owner, ownerField: "userTypeAOwner"}, {allow: owner, ownerField: "userTypeBOwner"}]){
	modelData: String
	typeA: UserTypeA @connection(name: "TypeMyModel")
	typeB: UserTypeB @connection(name: "TypeBModel")
}
```

This way you'll not overlap your two different authz rules and perhaps could fulfil your specific use case.
Custom resolvers could also help you since this is a filtering on the already retrieved data, that could be a cleaner way. With the ```@auth``` rule you used I'm not sure this can be done, since the generated code does not have the knowledge to differentiate on "how" would you like to use the owner.

**Comment by amcbb** [comment]
@attilah thank you for the reply and suggestion.  I ended up trying two separate ownerfields as you suggested and created duplicate UserTypeA fields in MyModel rather than relying on the @connection to retrieve the data since it still returned null.  I put the duplicate UserTypeA fields into a separate type (non @model so it could not be queried).  This seems to produce the desired effect but is more sloppy than just writing custom resolvers as you suggested.
