### ISSUE TITLE
amplify push fails due to "You have exceeded the maximum number of indexed tables that can be created simultaneously"

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#203]
**Describe the bug**
It seems if you specify more than 5 models in your schema.graphql at once with connections to each then amplify push will fail since dynamodb allows maximum 5-10 simultaneous table creations depending on number of secondary indexes. See https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-tables. Amplify CLI does not seem to respect that and so the push fails. 

**To Reproduce**
1. amplify add api
2. Create schema with more than 5 models and connections with each, or just 10 or more models with no connections
3. amplify will create one table per model
4. amplify push
5. the push fails.

**Expected behavior**
Amplify should throttle table creation according to dynamo limitations. 

**Logs**
Specific error from the push log: 

`CREATE_FAILED      S3ObjectTable                                                          AWS::DynamoDB::Table        Mon Sep 24 2018 12:18:40 GMT-0600 (Mountain Daylight Time) Subscriber limit exceeded: You have exceeded the maximum number of indexed tables that can be created simultaneously (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: LimitExceededException; Request ID: MN31PQQ36PSVO3JPSIKN0IN2C3VV4KQNSO5AEMVJF66Q9ASUAAJG)`

**Additional context**

**Comment by hisham** [comment]
Oh looks like this is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/161

Feel free to close this issue then.

**Comment by kaustavghosh06** [comment]
Tracking this in #161. Closing this issue since its a duplicate.
