### ISSUE TITLE
GraphQL schema with AWSTimestamp generate error in Mock API

### ISSUE THREAD

**Issue by iotFab** [aws-amplify/amplify-cli#2032]
**Describe the bug**
AWSTimestamp not supported by amplify mock api
Schema working with amplify add API.

> Error: Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?
Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?

**To Reproduce**
1. create a file with graphql schema 

> type Measure @model @key(fields: ["id","ts"]){
  id: String!  
  ts: AWSTimestamp! 
  payload: AWSJSON 
}

2. run `amplify mock api`
 
3. See error

> Creating table MeasureTable locally
Failed to start API Mock endpoint Error: Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?
Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?
Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?
Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?
Unknown type "AWSTimestamp". Did you mean "AWSTime" or "AWSDateTime"?

**Expected behavior**
GraphQL schema used by mock api successfully.
> Edit your schema at /aws/prototypes/amplify/space-explorer/amplify/backend/api/spaceexplorer/schema.graphql or place .graphql files in a directory at /aws/prototypes/amplify/space-explorer/amplify/backend/api/spaceexplorer/schema
Creating table MeasureTable locally
Running GraphQL codegen
✔ Generated GraphQL operations successfully and saved at src/graphql
AppSync Mock endpoint is running at http://172.0.0.20:20002

**Desktop (please complete the following information):**
 - OS:  MacOS Mojave 10.14.6
 - Browser chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)
 
**Additional context**
The same schema is working well with `Amplify add api`

**Comment by attilah** [comment]
Thanks @iotFab for reporting this issue, we've identified, that ```AWSTimestamp``` is missing from ```appsync-scalars``` and causing this error.

**Comment by kevinsalerno** [comment]
+1
