### ISSUE TITLE
Parse issue when using composite key with a AWSDateTime format

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-cli#2033]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Graphql query

** What AWS Services are you utilizing? **
AppSync with Amplify CLI

** Provide additional details e.g. code snippets **

With the request below, the amplify api return this error : 
"Variable 'updatedAt' has an invalid value. Unable to parse `2019` as a valid DateTime Object."

But it seems to me that i proceed in the same way as in the graphql transform's documentation. 
In the exemple given, the createdDate is also an AWSDateTime and the query is 
`statusCreatedAt: { beginsWith: { status: IN_TRANSIT, createdAt: "2019" }})`

```js
let res = await API.graphql(graphqlOperation(quesries.getFilesByOwnerIdOByTypeUpdatedAtDesc, 
              { 
              ownerId: ownerId,
              typeUpdatedAt: {beginsWith: {type:'FAC', updatedAt:"2019" }},
              limit: 10,
              nextToken: nextToken
            }
            ));

```
Transform Schema : 

```gql
type File
	@model
	@key(name: "ByOwnerIdOByUpdatedAtAsc", fields: ["ownerId", "updatedAt"], queryField: "getFilesByOwnerIdOByUpdatedAtAsc")
	@key(name: "ByOwnerIdOByTypeUpdatedAtDesc", fields: ["ownerId", "type", "updatedAt"], queryField: "getFilesByOwnerIdOByTypeUpdatedAtDesc")
  	@auth(
    	rules: [
      		{allow: owner, ownerField: "ownerId", identityField: "sub"},
    	]) 
	{
	id: ID!
	ownerId: String	
	createdAt: AWSDateTime
	updatedAt: AWSDateTime
	S3Object: S3Object
	name: String!
	size: Int
    visibility: Visibility
	type: String
}
```

**Comment by attilah** [comment]
@mlafo thanks for reporting this issue, I was able to reproduce this problem. The problem is that ```ModelFileByOwnerIdOByTypeUpdatedAtDescCompositeKeyInput``` is generated looks like this:
```graphql
input ModelFileByOwnerIdOByTypeUpdatedAtDescCompositeKeyInput {
  updatedAt: AWSDateTime
  type: String
}
```

To support the lexicographical comparison for the date part of the value ```updateAt``` should be a ```String```.

**Comment by mlafo** [comment]
Tanks @attilah 
I guess we have to modify the generated schema while waiting for the problem to be fixed ?

**Comment by attilah** [comment]
@mlafo digging deeper into the root cause I found out that if you move the definition of ```type``` above ```createdAt```, ```updatedAt```, we'll actually map that to string correctly, so it is a short term fix for your case.

```graphql
type File
    @model
    @key(name: "ByOwnerIdOByUpdatedAtAsc", fields: ["ownerId", "updatedAt"], queryField: "getFilesByOwnerIdOByUpdatedAtAsc")
    @key(name: "ByOwnerIdOByTypeUpdatedAtDesc", fields: ["ownerId", "type", "updatedAt"], queryField: "getFilesByOwnerIdOByTypeUpdatedAtDesc")
    @auth(
        rules: [
            {allow: owner, ownerField: "ownerId", identityField: "sub"},
        ])
{
    id: ID!
    ownerId: String	
    S3Object: S3Object
    name: String!
    size: Int
    visibility: Visibility
    type: String
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}
```

**Comment by mlafo** [comment]
@attilah
It works !
I would never imagine this kind af workaround.
