### ISSUE TITLE
CLI Slowness

### ISSUE THREAD

**Issue by tnguyen01** [aws-amplify/amplify-cli#2036]
Amplify CLI on my system (Mac) is extremely slow on any command to the point that it's almost unusable. If I execute a specific command for the first time in a new shell/terminal (or after idling for a while), it can take 15s or more. If I execute the same command again, execution time gets better and it can eventually executes in about 5s after a few times for simple commands like version or help. Other commands like status/function invoke/etc take longer, even after multiple executions.

Here're some samples:
```
$ time amplify --version
1.11.0

real	0m17.554s
user	0m5.858s
sys	0m1.823s

$ time amplify --version
1.11.0

real	0m8.254s
user	0m4.992s
sys	0m1.291s

$ time amplify --version
1.11.0

real	0m5.364s
user	0m4.568s
sys	0m0.820s

$ time amplify --version
1.11.0

real	0m5.497s
user	0m4.701s
sys	0m0.872s

$ time amplify --help                                                               
...
real	0m5.711s
user	0m4.972s
sys	0m0.895s

$ time amplify --help                                                               
...
real	0m16.185s
user	0m5.895s
sys	0m1.793s
```

These results are on node 10.16.2, it was way worse with node 8.16. I've also tried version 1.10.0 of the cli and it's also slow but I can to around 3.5s min execution time vs. 5s on version 1.11.0. 
I've seen a a few other people have similar timings.

Is this normal/expected?

**Comment by kaustavghosh06** [comment]
We’re aware of the slowness but 15 seconds seems unusual. We are making this faster and better with this PR #1823 which would be released soon.

**Comment by nino-moreton** [comment]
Here's mine on windows running consistently slow (using cmder w/ git bash):
```
$ time amplify version
1.11.0
real    0m17.016s
user    0m0.105s
sys     0m0.154s

$ time amplify version
1.11.0
real    0m17.076s
user    0m0.045s
sys     0m0.167s

$ time amplify version
1.11.0
real    0m18.410s
user    0m0.075s
sys     0m0.137s

$ time amplify version
1.11.0
real    0m17.176s
user    0m0.015s
sys     0m0.199s

time amplify help
...
real    0m17.739s
user    0m0.076s
sys     0m0.167s

time amplify help
...
real    0m18.425s
user    0m0.122s
sys     0m0.214s

time amplify help
...
real    0m18.604s
user    0m0.045s
sys     0m0.184s
```

**Comment by attilah** [comment]
I'm closing this issue since the PR in progress will address this behavior and is already referenced in the comment above.
