### ISSUE TITLE
Can't run amplify-dynamodb-simulator from a build container

### ISSUE THREAD

**Issue by rakannimer** [aws-amplify/amplify-cli#2037]
**Describe the bug**

Ran into this error while trying to run `amplify mock api` from the console (to test my app before deploying)

I narrowed the problem down to ampliy-dynamodb-simulator failing to acquire a port and launch.

After turning on logging, I get : 

```
[dynamodb-emulator] launching {
                                 retry: 0,
                                 givenOptions: { dbPath: '/tmp/emulator-1565678633261', port: null }
                                 }
2019-08-13T06:43:53.269Z [INFO]: ℹ️  [dynamodb-emulator] found open port { port: 62224 }
2019-08-13T06:43:53.272Z [INFO]: ℹ️  [dynamodb-emulator] Spawning Emulator: {
                                 args: [
                                 '-Djava.library.path=./DynamoDBLocal_lib',
                                 '-jar',
                                 'DynamoDBLocal.jar',
                                 '-port',
                                 62224,
                                 '-dbPath',
                                 '/tmp/emulator-1565678633261'
                                 ],
                                 cwd: '/codebuild/output/src410304939/src/amplify-api-mock-in-console/node_modules/amplify-dynamodb-simulator/emulator'
                                 }
2019-08-13T06:43:53.374Z [INFO]: ℹ️  [dynamodb-emulator] Emulator has started but need to verify socket
2019-08-13T06:43:54.387Z [WARNING]: ❌  [dynamodb-emulator] Port bound but by another process ... time to retry
2019-08-13T06:43:54.389Z [INFO]: ℹ️  [dynamodb-emulator] Queue retry in 20
```

**To Reproduce**

1. Fork https://github.com/rakannimer/amplify-api-mock-in-console
2. Connect it with Amplify Console
3. Scroll down to last line of logs in the Frontend section
4. See the error

or one-click-reproduce : 

[![amplifybutton](https://oneclick.amplifyapp.com/button.svg)](https://console.aws.amazon.com/amplify/home#/deploy?repo=https://github.com/rakannimer/amplify-api-mock-in-console)

**More context** 

- I tried changing build images to node:latest with no success.

- I tried to reproduce the problem in an Amazon Linux instance and an Ubuntu instance, but could not.

- On my mac locally it works as expected.

EDIT : Same error happens on CircleCI so it might not be an Amplify Console specific issue

**Comment by swaminator** [comment]
Moving to the CLI team to investigate.

**Comment by rakannimer** [comment]
After further digging I found that the problem is from `amplify-dynamodb-simulator`'s dependency on [port-pid](https://github.com/radiovisual/port-pid) which itself depends on the [netstat](https://github.com/radiovisual/netstats) package which depends on having `lsof` installed.

In the docker instances used by AWS Console, @VividKnife, CircleCI and I, `lsof` was not installed. And since port-pid fails silently the module was interpreting it as the dynamodb emulator failing to start.

Installing lsof( `apt-get -y install lsof`) fixes the problem.

I can try submitting a PR to port-pid but I will probably wait for @yuth's PRs to be merged first : https://github.com/radiovisual/netstats/pull/2 & https://github.com/radiovisual/port-pid/pull/7

**Comment by attilah** [comment]
@yuth, what do you think of moving from ```port-pid``` dependency to ```detect-port``` which has no native external process dependencies. Are we interested in the process that is using the port or we just need a free port to launch the simulator on?

detect-port: https://www.npmjs.com/package/detect-port
