### ISSUE TITLE
Email/Username case sensitive and uniqueness

### ISSUE THREAD

**Issue by VetBoard** [aws-amplify/amplify-cli#204]
**Describe the bug**
While using Amplify CLI to add auth functionality, the default cognito configuration allows multiple accounts with the same email and furthermore, with the same username if there are only some uppercase or lowercase chars.

So your user can signUp with an user "MyUser" and then someone else can signUp with a username "myuser", and even further, both of them can have the same email.

**To Reproduce**
1. run amplify add auth (With manual or default setup)
2. run amplify push
3. Implement sign up front-end and sign up several users with the same username and email. You can try different lowercase and uppercase variations
4. The users with the same email and same username (Only differences in cases) are in cognito dashboard.

**Expected behavior**
I think this is the expected behavior given the final cognito configuration... BUT the advanced set up should allow us to set the uniqueness of an email and the way to check if the username exists even when the only variation is the cases.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome, Firefox
 - Version: 0.1.22

![image](https://user-images.githubusercontent.com/26911718/45979829-e98d5500-c015-11e8-886f-9f43c24c6ed8.png)

Look at that, same username, only case variations and, all of them the same email

**Comment by kaustavghosh06** [comment]
@haverchuck, do you know if there is a parameter which we could be set via Cloudformation to support this use case?

**Comment by bijanmmarkes** [comment]
👍

**Comment by bradennapier** [comment]
https://github.com/aws-amplify/amplify-cli/issues/814

**Comment by kaustavghosh06** [comment]
Duplicate issue. Tracking this as a part of #814
