### ISSUE TITLE
GraphQL @connection input for array of types

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-cli#2048]
With the following schema, what does the `createSet` mutation expects for input? Is it the entire list of `Picture` objects?
```graphql
type Set @model {
  id: ID!
  user: String!
  pictures: [Picture!]! @connection
}

type Picture @model {
  id: ID!
  file: S3Object!
  rating: Int
  appearedForRanking: Int
}

type S3Object {
  bucket: String!
  key: String!
  region: String!
}
```

**Comment by RossWilliams** [comment]
With one to many relationships the foreign key normally resides on the “many” side, in your case Picture, so the Picture object will have a setId property, and Set would not have a reference to Picture.

You cannot use the createSet mutation to update more than 1 row at a time without writing custom resolvers, as batch mutations are not yet supported in Amplify. This means you would need to create the Picture objects separately from the Set object. Custom resolvers for batch mutations are not easy, especially if you have multiple environments. If you do need to have a batch create, using a lambda function would be far easier.

**Comment by attilah** [comment]
@RossWilliams thanks for answering question to @ylador. I'm closing the issue as the question was answered. @ilyador, Amplify forums are a better place to ask generic questions like this, the community will help there ;-)
