### ISSUE TITLE
amplify mock api - stuck while creating tables locally

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#2064]
**Describe the bug**
I am attempting to run the new `amplify mock api` which allows local mocking and testing for AppSync, this then outputs `GraphQL schema compiled successfully.` and continues to create the DynamoDB tables locally, then I see each table being created and after creating 10 tables, at the 11th table it is just stuck without any output, I left it running for about an hour and nothing.
note - our schema has 11 `@model`s so maybe this happens for the last table

**To Reproduce**
1. `amplify api add`
2. create your GraphQL schema
3. `amplify push`
4. `amplify mock api` - this command will never load all of your tables

**Expected behavior**
Should load all tables locally and open the GraphQL console locally, or give an error saying that it couldn't load table X for reason Y.

**Screenshots**
![image](https://user-images.githubusercontent.com/28350511/63162293-cb17ba00-c02a-11e9-82bc-0ca611439cec.png)

**Desktop (please complete the following information):**
 - OS: [MacOs 10.14.6]
 - Browser [chrome]
 - Version [76.0.3809.100]

**Additional context**
@aws-amplify/cli version - 1.12.0

**Comment by kaustavghosh06** [comment]
@idanlo Could you share your annotated schema? Would help us debug this issue further.

**Comment by idanlo** [comment]
@Lasim just wondering, how does java have anything to do with this? The Amplify CLI is written in JavaScript

**Comment by rakannimer** [comment]
@idanlo the [dynamodb simulator](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html) that the cli uses to mock the api is a JAR file. 

The amplify cli uses java to start a local instance of dynamodb using the JAR file. [Relevant code](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-dynamodb-simulator/index.js#L124).

**Comment by yuth** [comment]
@idanlo I tried a schema which has more than 10 models and DynamoDB tables got created. Could you share an sample schema with which we can reproduce this

**Comment by yuth** [comment]
@idanlo please feel free to comment here if you're still facing this issue

**Comment by idanlo** [comment]
Still facing this issue, 2 months later - 
![image](https://user-images.githubusercontent.com/28350511/69900489-b6aec180-137c-11ea-97d4-f12e1bbe3fdd.png)

**Comment by idanlo** [comment]
Please re-open

**Comment by idanlo** [comment]
I actually created a new one, so this can be closed as it will not get as much attention as the new one  I guess
