### ISSUE TITLE
using @auth with nested objects

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#2065]
** Which Category is your question related to? **
AppSync, GraphQL Transform

** What AWS Services are you utilizing? **
AppSync, Cognito, DynamoDB

** Provide additional details e.g. code snippets **
In my app I need a way to use the @auth directive for models which are a few layers below the actual users, example scenario - there is a Business model, which has an array of Employees (also a model), the Employee model has the @auth directive with its ownerField set correctly, and I want to give the Employees of the Business read access to the business, so what I thought of doing is this - 
```gql
type Business @model @auth(
  rules: [
    { allow: owner, ownerField: "employees", operations: [read] }
  ]
) {
  id: ID!
  employees: [Employee!] @connection
}

type Employee @model @auth(rules: [{ allow: owner, ownerField: "username" }]) {
  id: ID!
  username: String!
}
```
in this scenario - does the @auth directive go into the `username` of each Employee in the `employees` list and check if they are allowed to read from the Business?
If not, is there a different way I can use the @auth directive for an array of models?

**Comment by RossWilliams** [comment]
You can go the other way, allow employees access to the Employee model they own (as you already have), and then be able to navigate to the Business model. You would need to close off direct queries to the Business model with @model(queries: null). You can create an 'Employees' cognito group to give read-only access to the business model, just make sure all employees are in this group.

The result is that no one directly accesses Business for queries, and your fined-grained access rules are enforced by other models.

**Comment by idanlo** [comment]
@RossWilliams I had this idea but didn't know if it was good practice or not because my data goes a few layers deep and I have not described it entirely here so that the question will be understandable.
Thanks, I'll probably do it this way until the @auth directive is improved

**Comment by RossWilliams** [comment]
You could manually manage storing Employee Id keys on your Business model as an array and use the "ownerField" to enforce rules. But it would be your responsibility to keep these in sync.

To help think about why @auth doesn't by default doesn't cover your case, your Business to Employee relationship as a one to many relationship, so the foreign key sits in the Employee model. An AppSync Resolver is meant to work on a single table, so the response template will not have access to any Employee information, and so can't use it to enforce authentication. Allowing @auth to work in the other direction as well has downsides, as items in dynamodb are restricted to 400KB, and total response size is limited to 1MB.

**Comment by idanlo** [comment]
If I want to store IDs in an array I need to set up my own custom resolver for a `list_append` method correct? Do you have any resources that show how to do that with AppSync-generated resolvers (for example my updateBusiness auto generated resolver - I don't want to rewrite it but only add the ability to store an array of IDs and push to it)

**Comment by RossWilliams** [comment]
You need a custom resolver, You can copy the existing  resolver from the build/ folder and make the modifications you need for the updateExpression. I’d be interested in seeing how you make the template, having a hard time coming up with a clean design in my head except to make a top level mutation just for this task.

**Comment by idanlo** [comment]
@RossWilliams I actually had a question about that too - I don't want to mess with the VTL language too much so I'll probably create my own top level custom resolver too, but this creates a problem where if I write a mutation that also does an action on the Business but also inserts the user id into the array of IDs which one will happen first? I need the inserting ID to the array to be first, so does the order in which you write your mutations matter in GraphQL or are they all called simultaneously?

**Comment by RossWilliams** [comment]
I’m not understanding your needs or plan. It sounds like you want to use a pipeline resolver, but the amplify cli does not support these yet. You will need to use AppSync directly, or write CloudFormation templates yourself.

**Comment by attilah** [comment]
@idanlo reading the responses from @RossWilliams I think you have your questions answered, so I'm closing the issue. Thanks @RossWilliams.

@idanlo feel free to reopen the issue if something new comes up.
