### ISSUE TITLE
Single DynamoDB table

### ISSUE THREAD

**Issue by pspanchal** [aws-amplify/amplify-cli#2067]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
DynamoDB recommends using a single DynamoDB table. However, the @model in AppSyc GraphQL transform creates multiple DynamoDB tables. This is against best practice and will cause slower response times.

**Describe the solution you'd like**
@model should look at the schema and try to group the Types connected via @connection in a single DynamoDB table. This is best practice per DynamoDB.

**Describe alternatives you've considered**
While in Dev / Test the performance is not a big deal. But when we do performance testing this is critical to avoid slow performance in Production. 

**Additional context**
@model schema is a brilliant idea, but more needs to be done to make the performance optimum

**Comment by kaustavghosh06** [comment]
@pspanchal This question has been asked a couple of times out here - please read through this response to know more about our reasoning as to why we wanted to ahead with the multiple tables design - https://github.com/aws-amplify/amplify-cli/issues/431#issuecomment-444303514
We already have a geature request for having a single DDB option as well. Closing this in favor of that request.

**Comment by AlessandroVol23** [comment]
@kaustavghosh06 Could you post the feature request please because I can't find it. 
Thanks! :-)
