### ISSUE TITLE
ERROR: invalid subcommand on amplify codegen generate

### ISSUE THREAD

**Issue by psycura** [aws-amplify/amplify-cli#207]
After the last update of amplify i`m unable to generate types based on my graphql operations.
i receive :

> invalid subcommand

in the console.

**Comment by kaustavghosh06** [comment]
@psycura  We made an update to the codegen commands. Please take a look at the documentation PR- https://github.com/aws-amplify/amplify-js/pull/1747/files

You might just want to run `amplify codegen` for the CLI to generate the types as well as all the GraphQL statements (queries, mutations and subscriptions)

**Comment by kaustavghosh06** [comment]
We merged the docs. Please let me know if the issue still persists with the above-mentioned command.

**Comment by psycura** [comment]
Thank you, its works.
But statements generation have issue with no consistent code generation if i have some relations in my schema, part of relations is built into parent model query and part of relations is inserted as nextToken, with no additional fields

**Comment by kaustavghosh06** [comment]
Tracking this issue in https://github.com/aws-amplify/amplify-cli/issues/222
