### ISSUE TITLE
ALL attributes included in index created by @key directive.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#2073]
Is it possible to choose attributes which will be included in index created by @key directive?

**Comment by attilah** [comment]
@lenarmazitov using the ```fields``` property in the ```@key``` definition you can tell which fields you want to include, see the [docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#key] for more details.

Closing the issue, but if something new comes up, feel free to reopen it. For generic questions like this the Amplify forums are a better place to ask and get help from the community.

**Comment by RossWilliams** [comment]
@attilah I think the question by the title is different. The question is about choosing which attributes are projected into the index, rather than which attributes can be used for the primary key.

**Comment by lenarmazitov** [comment]
> @attilah I think the question by the title is different. The question is about choosing which attributes are projected into the index, rather than which attributes can be used for the primary key.

@attilah  yes, thats what I mean.
