### ISSUE TITLE
1.12.0 can't access functions due to CORS error

### ISSUE THREAD

**Issue by nino-moreton** [aws-amplify/amplify-cli#2078]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
1.11.0 all my lambda functions were working fine and after upgrading to 1.12.0, all the lambda functions are not working due to CORS error
```
Access to XMLHttpRequest at 'https://********.execute-api.**-******-2.amazonaws.com/***/SomeLambdaFn' from origin 'http://***.****.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I already have added `Access-Control-Allow-Origin` in my headers so this shouldn't be happening.

**To Reproduce**
1. Create function using 1.11.0
2. Upgrade to 1.12.0
3. Run function and see CORS error

**Expected behavior**
Should still be allowed to access my lambda functions like how it was during 1.11.0 update

**Comment by kaustavghosh06** [comment]
@nino-moreton After upgrading to 1.12.0, what changes did you make to your function before deploying?

**Comment by nino-moreton** [comment]
@kaustavghosh06 just some insignificant `console.log()` text change

**Comment by kaustavghosh06** [comment]
Are you accessing this function directly from your app client or via API Gateway/AppSync?

**Comment by nino-moreton** [comment]
@kaustavghosh06 I'm using @aws-amplify's `API` so I do API.post(...) and/or API.get(...)

**Comment by nino-moreton** [comment]
@kaustavghosh06 should also mention that after making this change, rolling back to 1.11.0 still produces this error and doesn't reverse the effect :(

**Comment by kaustavghosh06** [comment]
@nino-moreton This is very strange. I had a project with an older version of the CLI and I upgraded to 1.12.0 and didn't receive the errors with the following client code to call my REST API's. Can you try creating a test API with a lambda function and check if you're seeing the same issue?

```js
 post = async () => {
    console.log('calling api');
    const response = await API.post('myapi', '/items', {
      body: {
        id: '1',
        name: 'hello amplify!'
      }
    });
    alert(JSON.stringify(response, null, 2));
  }
  get = async () => {
    console.log('calling api');
    const response = await API.get('myapi', '/items/object/1');
    alert(JSON.stringify(response, null, 2));
  }
  list = async () => {
    console.log('calling api');
    const response = await API.get('myapi', '/items/1');
    alert(JSON.stringify(response, null, 2));
  }
```
Are you seeing this issue with authenticated or unauthenticated users making the API call?

**Comment by nino-moreton** [comment]
I shall try it with a brand new project.

I'm encountering this issue with an authenticated (cognito) user making the API call.

**Comment by nino-moreton** [comment]
sorry was my fault I guess. Couldn't replicate in a new project.

**Comment by erhard** [comment]
What was he error ?  I made the screencast https://www.youtube.com/watch?v=PswB47WJ4Xk
it runs locally with amplify function invoke on port 3000.  But pushing it I get a CORS Failure.
Even if I extend the CORS header with the http function names....

Maybe it is the Api Gateway but how do I manage cors there with amplify ?

Has anybody an idea ?

Should I make a new request to this boat or can it be reopened ?
