### ISSUE TITLE
Custom names for plural queries

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#2081]
**Is your feature request related to a problem? Please describe.**
AppSync automatically adds an 's' at the end of a model name when it is a plural query, meaning if you have a model called User then the `list` query for that model will be `listUsers` which is good. But if you have a model named `Business` or `Person` then the `list` query will be `listBusinesss` or `listPersons` which is grammatically incorrect.

**Describe the solution you'd like**
Maybe have a larger database for storing singular-plural names or let the user customize the name of the query, because if I enter this in my schema file - 
```
type Query {
  listBusinesses: [Business]
}
``` 
then it will display an error saying that it is trying to overwrite a query. I can go into the AWS AppSync console and manually change that but then I will have to do that every time I push.

**Describe alternatives you've considered**
I don't have any alternatives

**Additional context**
![image](https://user-images.githubusercontent.com/28350511/63255454-7a000400-c27e-11e9-8da0-d51d3548e991.png)

**Comment by RossWilliams** [comment]
To piggy-back on this, acronyms and initialisms for type names get mangled for the auto-generated connection indexes. 'GCHQ' type with a 'site' connection parameter becomes gCHQSiteId.

**Comment by mcanvar** [comment]
I am currently facing this when I trying to generate `Address`. It generates ie `listAddresss` instead of `listAddresses`.

**Comment by lseemann** [comment]
I'm bumping into this with a type of `Company`. My kingdom for `listCompanies` instead of `listCompanys`.

**Comment by kldeb** [comment]
@lseemann you can change the name of the generated list query inside of the model directive.

**Comment by lseemann** [comment]
That would be amazing. What's the correct syntax for that? I've not been able to find anything in the docs.

**Comment by kldeb** [comment]
@lseemann see here: 

https://docs.amplify.aws/cli/graphql-transformer/model

**Comment by lseemann** [comment]
So it is. I wish the docs were more explicit, but it appears the following does the trick:

```
type Company
  @model(
    queries: { get: "getCompany", list: "listCompanies" }
  )
 ...
}
```

Thank you!

**Comment by cjihrig** [comment]
I'm going to close this as it has been implemented in a few ways (by default in v2 of the transformer, via the `improvepluralization` feature flag in v1, and manual override as described in the previous comment).
