### ISSUE TITLE
Facebook auth: Unauthenticated access is not supported for this identity pool.

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#2082]
**Describe the bug**
I'm using defaultSocial params and created a new facebook app (in dev for facebook). I updated the auth to edit facebook information (different env). I pushed my changes and publish the ui again. On cognito console, all informations about facebook are the new ones. When I try to login, I receive this error from cognito-identity. Also, I have a PostConfirmation lambda trigger that is configured but got no error on the logs (no logs at all). In the identity provider, I don't see my facebook identity. On the screen, I got the facebook confirmation dialog and got this error after accepting it. Identity provider is well configured regarding role auth and unauth role.
I hope I gave all needed information, don't hesitate to ask if you need more information.

**To Reproduce**
```shell
amplify auth update
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Facebook, Google
  
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID. 
 
 Enter your Facebook App ID for your identity pool:  XXXXXXX
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 
 
 Enter your Google Web Client ID for your identity pool:  XXXXXXXX
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to use an OAuth flow? Yes
 What domain name prefix you want us to create for you? projectname
 Which redirect signin URIs do you want to edit? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to add redirect signin URIs? No
 Which redirect signout URIs do you want to edit? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to add redirect signout URIs? No
 Select the OAuth flows enabled for this project. Authorization code grant
 Select the OAuth scopes enabled for this project. (Press <space> to select, <a> to toggle all, <i> to invert selection)Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the identity providers you want to configure for your user pool: (Press <space> to select, <a> to toggle all, <i> to invert selection)Facebook, Google
  
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID. 
 
 Enter your Facebook App ID for your OAuth flow:  XXXX
 Enter your Facebook App Secret for your OAuth flow:  XXXX
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 
 
 Enter your Google Web Client ID for your OAuth flow:  XXXXX
 Enter your Google Web Client Secret for your OAuth flow:  XXXX
? Do you want to configure Lambda Triggers for Cognito? No
Successfully updated resource projectname locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

```
**Expected behavior**
To be able to log in via Facebook.

**Desktop (please complete the following information):**
Amplify CLI 1.8.1

**Comment by attilah** [comment]
@SebSchwartz could you please clarify these:
 
> In the identity provider, I don't see my facebook identity.

Where exactly?

> I got the facebook confirmation dialog and got this error after accepting it.

What is the error you're seeing?

**Comment by SebSchwartz** [comment]
> @SebSchwartz could you please clarify these:
> 
> > In the identity provider, I don't see my facebook identity.
> 
> Where exactly?
> 
When I browse the identities in the Federated Identities console.

> > I got the facebook confirmation dialog and got this error after accepting it.
> 
> What is the error you're seeing?

When it does a request to: https://cognito-identity.eu-west-1.amazonaws.com/
I've as response:
x-amzn-errormessage: Unauthenticated access is not supported for this identity pool.
x-amzn-errortype: NotAuthorizedException:
Error code: 400 

In the status bar:
myurl/?error_description=Exception+processing+authorization+code&state=ioYus2q2bv8quSZ7iiUhJBqsEpDJhzpk&error=server_error#_=_

**Comment by attilah** [comment]
@SebSchwartz could you please confirm this value: ```amplify/backend/auth/cognito[nnn]/parameters.json``` ```allowUnauthenticatedIdentities```?

I guess this is ```false```, because you answered No, to the related question during the ```auth update```.

**Comment by SebSchwartz** [comment]
Yes it's:     "allowUnauthenticatedIdentities": false,

**Comment by attilah** [comment]
Please change, push and try it, to see what is the result after the change.

**Comment by SebSchwartz** [comment]
I can now see the identity inside Federated Identities console.
I don't have http error (receiving 200).
But still the same error message :(

Here is request/response header with idpresponse?code=...:
```
Request:
Request URL: https://rentguruf3085b86-f3085b86-test.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse?code=CODE&state=LongStuff

Response:
location: https://myurl/?error_description=Exception+processing+authorization+code&state=N2YqY4Oo8V4nDAeWI5Ej2fqC1dVqLMBJ&error=server_error
server: Server
set-cookie: csrf-state=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
status: 302
strict-transport-security: max-age=31536000 ; includeSubDomains
x-amz-cognito-request-id: ID
x-application-context: application:prod:8443
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

```

**Comment by SebSchwartz** [comment]
I saw the pending-response label after my response so in case of mis-refresh, commenting again ;)

**Comment by attilah** [comment]
At this point I cannot tell if it is an Amplify JS error or a configuration error without the concrete details, let me summon @elorzafe perhaps they saw a similar error before.

**Comment by SebSchwartz** [comment]
I may have a new interesting error I got keeping playing/testing stuffs (the final error is still the same but I got also this error):

?error_description=attributes+required%3A+%5Bgiven_name%2C+family_name%2C+email%5D

**Comment by SebSchwartz** [comment]
When I remove this given_name attribute which doesn't exist on Facebook API, it's working.
Mapping should be: first_name -> given_name

**Comment by kaustavghosh06** [comment]
@SebSchwartz Did you configure the custom attribute for `given_name` in the cognito console or was it configured using the CLI?

**Comment by SebSchwartz** [comment]
I configured it using the CLI with previous version.
