### ISSUE TITLE
Unable to update qraphQL schema

### ISSUE THREAD

**Issue by Mknight492** [aws-amplify/amplify-cli#2089]
currently onusing window with WSL

using amplify version 1.12.0

I created a graphQL schema with amplify add api

I now want to update the schema and I have tried with amplify update api and amplify api gql-compile. It doesn't update the schema in ./build despite saying the schema has compiled correctly (it will say this even if it's a completely invalid schema). 

Once a hit amplify push it will override my schema changes (these changes have been made in the correct location i.e. api/<apiname>.schema.graphql).

This was working for me previously before changing amplify versions - I can't remember which version to revert to however.

At this stage I will have to delete the API and add other along with rewriting some cloud-formation templates.

**Comment by attilah** [comment]
@Mknight492 if you want to work on the GraphQL schema, you just have to edit the ```.graphql``` file in ```<projectdir>/amplify/backend/api/<api name>/schema.graphql``` file and then ```amplify push```.

```amplify api gql-compile``` will actually apply the transforms and builds the ```.graphql``` file and the resolver files into the ```<projectdir>/amplify/backend/api/<api name>/build``` folder.

I'm closing this issue, but if something new comes up, feel free to reopen it. I would suggest to follow the tutorials to get more information about how commands are working.

**Comment by Mknight492** [comment]
@attilah Thanks for you quick response.

I think you've misunderstood my problem.

I defined a schema with amplify add api.

I'm then am unable to update it.

I have tried using amplify push, amplify api gql-compile and amplify update api.

I tried to make it clear that It was the <projectdir>/amplify/backend/api/<api name>/schema.graph file that gets overridden with amplify push.

I believe this is a bug and the amplify cli is not working as intended

**Comment by attilah** [comment]
@Mknight492 please provide *exact* repro steps, because the CLI is never touching customer provided files, the CLI creates its own files if needed, in case of GraphQL compilation we create the one in the build folder.

**Comment by Mknight492** [comment]
Nevermind I was making edits in the   #current-cloud-backend directory. Sorry about that.

**Comment by mdsadique2** [comment]
facing the exact same issue. when I do "amplify status" it detects the changes in API, but when I do 'amplify push' the changes are overridden with the previous state i.e. before edit and message say no changes.
