### ISSUE TITLE
amplify codgen keeps changing schema.json even though nothing has changed

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#209]
**Describe the bug**
Running amplify codegen repeatedly with no actual changes in AppSync UI makes schema.json constantly change. 

**To Reproduce**
Run amplify codegen multiple times without changing anything in the appsync console. 

**Expected behavior**
If there is no change in graphql schema / resolvers then there should be no change in local schema.json or anything else. 

**Screenshots**

Screenshots of the diffs of schema.json after each amplify codegen.

![dry-eye-frontend vim git difftool 235x73 2018-09-25 09-16-31](https://user-images.githubusercontent.com/81853/46024294-b5f90c00-c0a3-11e8-84ec-83b098ad7ef5.png)
![dry-eye-frontend vim git difftool 235x73 2018-09-25 09-17-09](https://user-images.githubusercontent.com/81853/46024330-c9a47280-c0a3-11e8-8dc1-3cc64e9b9776.png)
![dry-eye-frontend vim git difftool 235x73 2018-09-25 09-19-24](https://user-images.githubusercontent.com/81853/46024481-1daf5700-c0a4-11e8-9520-c8e340aa8fbe.png)

**Desktop (please complete the following information):**
 - OS: OSX

**Additional context**
It seems it's just flipping stuff back and forth. If src/graphql/schema.json is expected to be commit in git then this is annoying.

**Comment by kaustavghosh06** [comment]
@hisham We download the schema each time you run the codegen command and since the schema is a JSON object, there isn't a way to order it. What you could do is that you could use the `-nodownload` flag along with the codegen command which won't download the new schema.json file each time you run a codegen command.

**Comment by ryansb** [comment]
Internally, there could be a step to sort the JSON keys like https://github.com/substack/json-stable-stringify so that each run would create a consistently ordered schema.

**Comment by kaustavghosh06** [comment]
@hisham I beleve this issue if fixed. Please let me know if you still see this.
