### ISSUE TITLE
Best way access table name from custom resolvers

### ISSUE THREAD

**Issue by iparrabb** [aws-amplify/amplify-cli#2092]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
AppSync DynamoDB

** What AWS Services are you utilizing? **
AppSync DynamoDB

** Provide additional details e.g. code snippets **
I have a project with multiple environments and need access to DynamoDB tables from custom resolvers with AppSyncApiId and env variables.

CustomResources.json
```js
"AddCustomItemResolver": {
	"Type": "AWS::AppSync::Resolver",
	"Properties": {
		"ApiId": {
			"Ref": "AppSyncApiId"
		},
		"DataSourceName": "ItemTable",
		"TypeName": "Mutation",
		"FieldName": "addCustomItem",
		"RequestMappingTemplateS3Location": {
			"Fn::Sub": [
				"s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Mutation.addItems.req.vtl",
				{
					"S3DeploymentBucket": {
						"Ref": "S3DeploymentBucket"
					},
					"S3DeploymentRootKey": {
						"Ref": "S3DeploymentRootKey"
					}
				}
			]
		},
		"ResponseMappingTemplateS3Location": {
			"Fn::Sub": [
				"s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Mutation.addItems.res.vtl",
				{
					"S3DeploymentBucket": {
						"Ref": "S3DeploymentBucket"
					},
					"S3DeploymentRootKey": {
						"Ref": "S3DeploymentRootKey"
					}
				}
			]
		}
	}
}
```

Mutation.addItems.req.vtl
```js
#set($items = [])
#foreach($item in ${ctx.args.items})
  $util.qr($item.put("__typename", "Item"))
  $util.qr($item.put("id", $util.defaultIfNullOrBlank($item.id, $util.autoId())))
  $util.qr($items.add($util.dynamodb.toMapValues($item)))
#end
{
  "version" : "2018-05-29",
  "operation" : "BatchPutItem",
  "tables" : {
    "ItemTable-{AppSyncApiId}-{env}": $utils.toJson($items)
  }
}
```

How I can set ItemTable-{AppSyncApiId}-{env} dynamically for each environment?

Thanks!

**Comment by kaustavghosh06** [comment]
@iparrabb Currently AppSync resolvers doesnt support passing in environment variables but I've informed the AppSync service team to add this to their backlog.

**Comment by kevcam4891** [comment]
Is anyone actively working on this? I need this too, and may work on a PR if it is not being actively worked on.

**Comment by kevcam4891** [comment]
#1946

**Comment by kevcam4891** [comment]
Similar to #1946

**Comment by nathanqueija** [comment]
Any updates on this issue? Is it something that is going to be implemented or we still have to create custom functions to have the table name and environment in the custom resolvers functions? I'm finding it really hard to understand how I can achieve that not because the content is hard, but because there is no information about it anywhere.

**Comment by SwaySway** [comment]
Closing this in favor of #1774 for visibility.
