### ISSUE TITLE
Workflow for multi-account environments

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#2094]
** Which Category is your question related to? **
Multi-env

** What AWS Services are you utilizing? **
Hosting, appsync (with aurora), cognito

** Provide additional details e.g. code snippets **
I wonder if the proposed flow for multi env is working for multiple aws account. I will have 5 different aws account (rootAccount, iamShared, dev, test, prod) and want to be sure that I can work with multiple environment as I will have a user in a shared iam account and one assume role in each other aws account (dev, test & prod). Will it work in this configuration? If not, what do you suggest for one aws account per environment?

**Comment by jkeys-ecg-nmsu** [comment]
@SebSchwartz yes, as long as you have named profiles setup for each IAM user. I name each profile the same name as each AWS account to keep it simple. 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by kaustavghosh06** [comment]
@SebSchwartz What @jkeys-ecg-nmsu mentioned is correct. Each of your `env` is associated with an AWS profile so as long as your AWS profiles map to your different AWS accounts, you should be good.

**Comment by SebSchwartz** [comment]
Thanks for answers ;)
