### ISSUE TITLE
Invalid autogenerated queries for composite sort key

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#2095]
**Describe the bug**
If we will create composite sort key via @key directive, and then generate queries we will get wrong query.

**To Reproduce**
Schema:
```
type Table @model @key(fields: ["id", "type", "target"]) {
  id: String!
  type: String!
  target: String!
}
```

autogenerated query:
```
export const getUser = `query GetUser($id: String!, $type: String!, $target: String!) {
  getUser(id: $id, type: $type, target: $target) {
    id
    type
    target
  }
}`
```
Above query is wrong, because we do not have attributes type and target.

**Expected behavior**
Is autogenerated query should work out of the box?
How can we query **type#target** attribute, seems like it is also impossible?

**Comment by kaustavghosh06** [comment]
@lenarmazitov Could you explain more about this "do not have attributes type and target."?
You have type and target as required attributes in your schema.

Also, the auto-generated AppSync resolvers take care of concatening the corresponding fields you pass in your query. Did you try testing this query?

**Comment by lenarmazitov** [comment]
I mean we do not have mentioned attributes for query and as a result when I perform the query result is:
```
{
  "data": {
    "getUser": null
  },
  "errors": [
    {
      "path": [
        "getUser",
        "type"
      ],
      "locations": null,
      "message": "Cannot return null for non-nullable type: 'String' within parent 'User' (/getUser/type)"
    },
    {
      "path": [
        "getUser",
        "target"
      ],
      "locations": null,
      "message": "Cannot return null for non-nullable type: 'String' within parent 'User' (/getUser/target)"
    }
  ]
}
```

**Comment by RossWilliams** [comment]
Can you show your item with the $id you are trying to get as it appears in dynamodb with any sensitive information removed?

**Comment by lenarmazitov** [comment]
![image](https://user-images.githubusercontent.com/600133/63455302-33183700-c455-11e9-88f5-cbc016a7a9ec.png)

**Comment by RossWilliams** [comment]
your schema has type and target as required attributes. Amplify assumes any items you insert will have these two properties. But the item you show in your screenshot does not have these attributes.

If you look at your Mutation.createTable.req.vtl file in the build/resolvers folder you should see a line:
$util.qr($ctx.args.input.put("type#target","${ctx.args.input.type}#${ctx.args.input.target}")) which generates the compound range key. If you are using graphQL to insert the item, type#target will only be populated when you have a type and target properties on the item.

Are you doing any additional custom work outside of amplify? Are you saying that you can insert an item with the compound range key without its parts as well, and there is a bug?

**Comment by lenarmazitov** [comment]
@RossWilliams but when I created schema via Graphql transform I described this attributes.
This screenshot of successful mutation. 
The bug is in autogenerated graphql mutations and queries. There is this 2 attributes in any query and mutation presents, which is not exist, but still queried.

**Comment by attilah** [comment]
@lenarmazitov you're right, ```type``` and ```target``` should not be in the field list of the query results as they're not persisted as individual attributes.

**Comment by jkeys-ecg-nmsu** [comment]
If Amplify supported Local Secondary Indexes, OP could simply change his primary index to be `["id"]` and create a local secondary index with the sort keys. @lenarmazitov then you would just use whichever generated query you wanted, the LSI query or the primary index query.

**Comment by SwaySway** [comment]
Hello @lenarmazitov
Are you still running into this issue?
Using the following schema the following was generated for me.
```gql
# graphql/mutations
mutation CreateTable($input: CreateTableInput!) {
  createTable(input: $input) {
    id
    type
    target
  }
}

# graphql/queries
query GetTable($id: String!, $type: String!, $target: String!) {
  getTable(id: $id, type: $type, target: $target) {
    id
    type
    target
  }
}
```
Where a create table input is defined by
```ts
type CreateTableInput = {
  id: string,
  type: string,
  target: string,
};
```

When I did a mutation the following is entered into dynamodb I received the following.
![image](https://user-images.githubusercontent.com/7465495/71391903-f30bc100-25ba-11ea-99c8-b15138009754.png)

Doing a get query I don't see that error.
Running on Amplify CLI v4.17.

Is the mutation you are doing removing those values? Based on the screenshot I only see the primary key and sort key. Did the mutation not populate those fields as well?

One thing I could see here is that sort key could potentially be its own argument value similar to the list query.
```gql
# for example
query GetTable($id: String!, $typeTarget: ModelTablePrimaryCompositeKeyInput! ) {
  getTable(id: $id, typeTarget: $typeTarget) {
    id
    type
    target
  }
}
# where modeltableprimarycompositekeyinput is defined by
input ModelTablePrimaryCompositeKeyInput {
  type: String
  target: String
}
```

**Comment by kaustavghosh06** [comment]
@lenarmazitov Closing this issue for now based on the response above. Please let us know if you're still stuck with this and we'll re-open the issue.
