### ISSUE TITLE
Will Amplify-CLI ever support Windows?

### ISSUE THREAD

**Issue by hagiosofori** [aws-amplify/amplify-cli#210]
Will Amplify-CLI ever support Windows? I know it currently supports Windows Subsystem on Linux (WSL), and I'm trying to practice with it on a Windows 10 Home PC, meaning I can't access the WSL.. Should I just look for an alternative?

**Comment by kaustavghosh06** [comment]
Did you try using the latest version of the CLI?

**Comment by hagiosofori** [comment]
yhup...

tried globally re-installing aws-amplify/cli
tried globally updating aws-amplify/cli

and tried the Getting Started tutorial.. still end up getting the same error: `CREATE_FAILED               GraphQLSchema                                               AWS::AppSync::GraphQLSchema Tue Sep 25 2018 18:34:10 GMT+0000 (Coordinated Universal Time) S3 location not valid for DefinitionS3Location
`

**Comment by kaustavghosh06** [comment]
Provided a fix for this issue - https://github.com/aws-amplify/amplify-cli/pull/212
Will publish by end of day today.

**Comment by hagiosofori** [comment]
works beautifully! thanks for the persistent work @kaustavghosh06 ... much appreciated!
