### ISSUE TITLE
After taking codegen, the generated service has enum in PASCALCASE though enum case is LOWERCASE.

### ISSUE THREAD

**Issue by vaparth6** [aws-amplify/amplify-cli#2103]
**GraphQL schema:**

`input UserInput {
   preferredLanguage: lang
}`

`enum lang {
  en
  hi
}`

In this GraphQL schema, **lang** enum type haven't used PascalCase.

**Amplify Codegen:**
So while i take the **CodeGen**, amplify by default take enum type **Lang**(PascalCase) instead of **lang** in generated files. you can see in below image:

![IMG_20190821_123406](https://user-images.githubusercontent.com/45867781/63410114-2fae8c80-c410-11e9-8ca2-9f44fa4a86fe.jpg)

**Library Versions:**
npm: 6.9.2
node: 10.15.0
amplify: 1.12.0

**Comment by ammarkarachi** [comment]
@vaparth6 You can override some of the code-gen .graphqlconfig.yml using [reference](https://graphql-code-generator.com/docs/plugins/java#namingconvention-namingconvention-default-value-change-casepascalcase). Sorry for the delay

**Comment by kaustavghosh06** [comment]
@vaparth6 This issue doesn't entail the Amplify CLI and ties in to the Apollo gradle plugin which is not managed by the Amplify CLI team.
