### ISSUE TITLE
Work with credentials from environment

### ISSUE THREAD

**Issue by aztecrex** [aws-amplify/amplify-cli#2106]
**Is your feature request related to a problem? Please describe.**
We use federated credentials obtained through STS:AssumeRole in our development environments.  `amplify init` expects there to be an IAM user profile or available permanent IAM user credentials when it runs. So it fails in our case.

**Describe the solution you'd like**
Use the same credentials resolution method (environment and flags) that the aws CLI uses. That has the advantage of cohesion in the AWS ecosystem.

**Comment by josefaidt** [comment]
Hey @aztecrex :wave: apologies for the delay here! This should now be possible as the CLI will allow us to initialize a project using a [headless `amplify init`](https://docs.amplify.aws/cli/usage/headless/#sample-script) script to pass access keys from environment variables

```sh
#!/bin/bash
set -e
IFS='|'

ENV_NAME="dev"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"us-east-1\"\
}"

AMPLIFY="{\
\"envName\":\"$ENV_NAME\",\
\"defaultEditor\":\"code\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

echo "Initializing Amplify project for env: $ENV_NAME"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes
```

Closing issue 🙂 if you are still experiencing this issue or feel this does not quite cover your use case please reply back to this thread and we can re-open to investigate further!
