### ISSUE TITLE
Onboard a front-end dev to an Amplify project

### ISSUE THREAD

**Issue by epheat** [aws-amplify/amplify-cli#211]
This question is related to a few issues that have already been raised (#186, #104, as well as a few from the amplify-js repo).

I'm working on an Amplify project, and I want to have another developer help out with the front-end. However, if he clones the repository he can't run the front-end, since he doesn't have the generated `aws-exports.json` file. From browsing issues and reading the documentation it seems like he'd need to run `amplify configure` and `amplify push` to generate the necessary files before he is able to run the front-end.

I guess my first question would be: is it recommended that this new developer provision the entire backend on his own AWS account? Is it possible to let this new developer simply use the resources already provisioned on my AWS account for his front-end development?

Thanks!

**Comment by kaustavghosh06** [comment]
@epheat How I would do this, is htat I would share the amplify/ dir in a version control and the new developer would need to fetch the amplify/ dir in the project, setup his/her IAM user using `amplify configure` tied to the same AWS account. 
Once the user has done that, the user can run the `amplify configure project` command in the project dir/, which would setup (through a CLI walkthrough), the entire project with the users AWS profile and utilize the same AWS backend.

**Comment by kaustavghosh06** [comment]
Also, we're currently working on environment/stages for an Amplify project which would enable users to clone resources and work on a separate branch if needed, but we currently don't support that. But what we do allow is the usage of the same Amplify backend by multiple devs through the steps mentioned above.

**Comment by epheat** [comment]
Ok, thanks. I'll try that out tonight. But in the case of a strictly front-end dev, I'm not exactly a huge fan of needing to share the credentials of an Administrator IAM User for my AWS account for him to use during `amplify configure`.

Would it work to just share the `src/aws-exports.js` file with the front-end dev for him to place in his src/ directory? That way, he wouldn't even have to worry about using amplify.

**Comment by kaustavghosh06** [comment]
Yup, that would work as well! If the frontend dev doesn't need to do any of the backend deployment stuff, then sharing just the aws_exports.js file would do - which is all that is needed to make SDK calls using Amplify JS lib from whatever frontend you're using.
