### ISSUE TITLE
Update boilerplate for .gitignore (multi env)

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#2110]
**Describe the bug**
Today I had a call with @kaustavghosh06 and it was mentioned that some files that I currently do not have in `.gitignore` could safely be ignored and this would mean much less noise in my git.

This issue is to hopefully get an updated list of files that can safely be added to .gitignore without causing any problems by not being cloud pushed to the cloud.

I currently have this list in `.gitignore` related to Amplify:

```gitignore
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
# updated to not be .js specific
aws-exports.*
awsconfiguration.json
/amplify/backend/function/typeform/src/.env
/amplify/backend/function/users/src/.env
# added after todays call
/src/graphql/schema.json
```

When moving between environments and doing `amplify env pull` I "randomly" get various cloud formation files, which I am also curious to see if they can enter in .gitignore. That would mean even less noise for me (and with noise comes confusion for new adopters of Amplify).

So this is a request to have an updated list somewhere in the documentation so that I can add that in my setup and for Amplify to also add these to the auto-generated `.gitignore` (which I believe mine is a result of).

**Comment by danhumphrey** [comment]
Should `amplify/\#current-cloud-backend` really be in .gitignore?

What if you have a master and dev git branch (for instance) and want a corresponding prod and dev amplify env. Shouldn't the appropriate backend be pinned to the git branch so the checkout of branch also updates the amplify environment?

**Comment by davidsteed** [comment]
No because it is regenerated when you do an amplify init from files that are checked in

**Comment by josefaidt** [comment]
Closed due to age and this has been updated since
