### ISSUE TITLE
Socket timeout during amplify publish

### ISSUE THREAD

**Issue by leantide** [aws-amplify/amplify-cli#2121]
**Describe the bug**
Error: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

**To Reproduce**
1. Make updates to a lot of lamda functions (see table below)
2. execute `amplify push` or `amplify publish`
3. Wait about 1.5 minutes (in which push process is building lamdas)
4. Socket timeout error occurs

**Expected behavior**
Socket is either kept alive or re-established without a fatal timeout

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a
 - Version: @aws-amplify/cli@1.11.0

**Additional context**
 amplify status during publish:

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Function | settings        | Update    | awscloudformation |
| Function | membership      | Update    | awscloudformation |
| Function | teams           | Update    | awscloudformation |
| Function | products        | Update    | awscloudformation |
| Function | nodes           | Update    | awscloudformation |
| Function | kanban          | Update    | awscloudformation |
| Auth     | redgazelle      | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
| Storage  | settings        | No Change | awscloudformation |
| Storage  | membership      | No Change | awscloudformation |
| Storage  | teams           | No Change | awscloudformation |
| Storage  | products        | No Change | awscloudformation |
| Storage  | releases        | No Change | awscloudformation |
| Storage  | features        | No Change | awscloudformation |
| Storage  | items           | No Change | awscloudformation |
| Storage  | users           | No Change | awscloudformation |
| Storage  | counters        | No Change | awscloudformation |
| Storage  | authorization   | No Change | awscloudformation |
| Storage  | inProgress      | No Change | awscloudformation |
| Storage  | completed       | No Change | awscloudformation |
| Storage  | accepted        | No Change | awscloudformation |
| Storage  | planned         | No Change | awscloudformation |
| Storage  | userfiles       | No Change | awscloudformation |
| Api      | settings        | No Change | awscloudformation |
| Api      | membership      | No Change | awscloudformation |
| Api      | teams           | No Change | awscloudformation |
| Api      | products        | No Change | awscloudformation |
| Api      | nodes           | No Change | awscloudformation |
| Api      | kanban          | No Change | awscloudformation |

**Comment by leantide** [comment]
Mitigation: push one item at a time

amplify function push settings
amplify function push membership
etc.

**Comment by UnleashedMind** [comment]
@leantide 
I was not able to reproduce the error. 
Could you send a screen shot with the error messages?

**Comment by leantide** [comment]
Unfortunately, in order to reproduce, I think I would have to tear down my backend which is no fun.
But I did copy and paste the error message. It said: "Error: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed."

The error seemed like a direct result of a long 1.5 minute build time, probably not that there happened to be many lambdas involved. Do your reproduce efforts involve a long build time? You probably won't see it otherwise.

**Comment by UnleashedMind** [comment]
Lambda function build is a local operation, it does not involve server connection. It's puzzling why there was such error, that's why I was trying to get the original error message screenshot to get more information.

**Comment by leantide** [comment]
Could the server connection be opened before the local build operation commenced?

In any case, I just deleted all my lambda 'dist' folders and rebuilt and did not encounter the error. Given the questionable association, and that I cannot reproduce, and that there is a workaround, I will close this. Thank you for your efforts.
