### ISSUE TITLE
Storage( dynamodb ) specified during amyplify init is not being generated

### ISSUE THREAD

**Issue by oscarnevarezleal** [aws-amplify/amplify-cli#2125]
** Which Category is your question related to? **
CI / Headless

** What AWS Services are you utilizing? **
Amplify CLI

** Provide additional details e.g. code snippets **

I'm trying to initialize an amplify project using headless amplify CLI, part of this initialization requires a database creation using DynamoDb as the storage engine. I've used a fork version of [this script](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/sample-headless-scripts/headless_init_env_auth.sh) but it seems I might be doing something wrong since the database isn't created, not to say that the whole _--categories_ flag is being ignored.

According to the [docs](https://aws-amplify.github.io/docs/cli-toolchain/usage#headless-mode) there is not such a thing as a documented  _--categories_ flag for amplify ```init``` command but it exists on the sample scripts [this script](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/sample-headless-scripts/headless_init_env_auth.sh)

Am I missing something? this is the content ( **$CATEGORIES** ) I pass to amplify init on the _--categories--__ argument

```json
{
  "storage": {
    "usersTable": {
      "service": "DynamoDB",
      "providerPlugin": "awscloudformation",
      "providerMetadata": {
        "s3TemplateURL": "https://s3.amazonaws.com/myapp-dev-20190731130334-deployment/amplify-cfn-templates/storage/usersTable-cloudformation-template.json",
        "logicalId": "usersTable"
      },
      "lastPushTimeStamp": "2019-08-15T14:00:04.271Z",
      "output": {
        "PartitionKeyName": "email",
        "Region": "us-east-1",
        "Arn": "arn:aws:dynamodb:us-east-1:048xxxxxxxxx:table/users-dev",
        "StreamArn": "arn:aws:dynamodb:us-east-1:048xxxxxxxxx:table/users-dev/stream/2019-08-12T18:35:51.674",
        "PartitionKeyType": "S",
        "Name": "users-dev"
      },
      "lastPushDirHash": "2J+8sTotqquf3dZYkXgZfk1KV8Y="
    }
  }
}

```

This is the command I'm running, there are no errors.
```
amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes
```

**Comment by kaustavghosh06** [comment]
@oscarnevarezleal Headless creation of resources/categories is not supported yet. the `categories` flag is used to just pass in parameters to the cloudformation templates and not to create the resources. You would have to go through the CLI flow to add the resources once and then use the headless scripts (mentioned above) to automate your deployments.

**Comment by oscarnevarezleal** [comment]
Noted, thanks for clarifying this.
