### ISSUE TITLE
How do we host an Amplify app in multiple AWS accounts?

### ISSUE THREAD

**Issue by tclindner** [aws-amplify/amplify-cli#2127]
**Which Category is your question related to?**
Hosting

**What AWS Services are you utilizing?**
Only hosting

**Provide additional details e.g. code snippets**
Please see below

First, thank you for all of your work on this product :raised_hands:. 

### Background

We are trying to use Amplify to host a single page app. Our organization has separate AWS accounts for each environment (e.g. dev, qa, prod).

We are able to create an app and an initial environment in our first AWS account without any issues. When we try to create our second environment in our second AWS account we get an error. Please see how to reproduce for more details.

### Context

| Software | Version |
| --- | --- |
| OS | `macOS 10.14.6` |
| Node | `v10.15.3` |
| npm | `v6.10.3` |
| Amplify cli | `v1.12.0` |
| AWS cli | `aws-cli/1.16.98 Python/2.7.10 Darwin/18.7.0 botocore/1.12.88` |

### Steps to reproduce

  1. Edit `~/.aws/config`. Enter the following 
```
[default]
output = json
region = us-east-1

[profile dev]
output = json
region = us-east-1

[profile qa]
output = json
region = us-east-1
```
  2. Edit `~/.aws/credentials`. Enter the following
``` 
[default]
aws_access_key_id = <access_key_id>
aws_secret_access_key = <secret_access_key>

[dev]
aws_access_key_id = <access_key_id>
aws_secret_access_key = <secret_access_key>

[qa]
aws_access_key_id = <access_key_id>
aws_secret_access_key = <secret_access_key>
```
  3. Run `amplify init` in the terminal.
  4. Enter a name
  5. Set environment to `dev`
  6. Set the default editor to `Visual Studio Code`
  7. Set the type of app to `javascript`
  8. Set the javascript framework to `vue`
  9. Set the source directory path to `src`
  10. Set the distribution directory path to `dist`
  11. Set the build command to `npm -v` <-- Intentionally set to this since our CI does the build.
  12. Set the start command to `npm run-script serve`
  13. Answer `y` to do you want to use an AWS profile. 
  14. Select the `dev` profile.
  15. Let the cli do its thing. Output: `Your project has been successfully initialized and connected to the cloud!`
  16. Run `amplify hosting add`
  17. Select `DEV (S3 only with HTTP)` for environment setup.
  18. Use the default hosting bucket name
  19. Use the default index doc
  20. Use the default error doc 
  21. Run `amplify publish`. Prompt lists one category, `hosting` with an operation of `Create`.
  22. Respond `y` to are you sure you want to continue question. Let the cli do its thing. Output: `Your app is published successfully.`. We can see a CloudFormation stack in `dev` and we can hit the app.
  23. Run `amplify env add`
  24. Respond `n` to use existing environment question.
  25. Set environment to `qa`
  26. Answer `y` to do you want to use an AWS profile. 
  27. Select the `qa` profile. This is aligned with our `qa` AWS account.
  28. Let the cli do its thing. Output: `Your project has been successfully initialized and connected to the cloud!`
  29. Run `amplify publish`. Prompt lists one category, `hosting` with an operation of `Create`. (Same as for dev).
  30. Respond `y` to are you sure you want to continue question.
  31. **`Receive error`**. We can see a CloudFormation stack in `qa`. It is in a `UPDATE_ROLLBACK_COMPLETE` state.

### Error output

> Note: Project name has been replaced with `********`.

```
UPDATE_IN_PROGRESS ********-qa-20190823131148 AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:24 GMT-0500 (Central Daylight Time) User Initiated             
CREATE_IN_PROGRESS hostingS3AndCloudFront             AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:28 GMT-0500 (Central Daylight Time)                            
CREATE_IN_PROGRESS hostingS3AndCloudFront             AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:29 GMT-0500 (Central Daylight Time) Resource creation Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS ********-qa-20190823131148-hostingS3AndCloudFront-16PWPPDKDG4NZ AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:29 GMT-0500 (Central Daylight Time) User Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS S3Bucket                                                                AWS::S3::Bucket            Fri Aug 23 2019 14:48:32 GMT-0500 (Central Daylight Time)                                                                
CREATE_FAILED      S3Bucket                                                                AWS::S3::Bucket            Fri Aug 23 2019 14:48:33 GMT-0500 (Central Daylight Time) ********-20190823130603-hostingbucket-qa already exists
CREATE_FAILED      ********-qa-20190823131148-hostingS3AndCloudFront-16PWPPDKDG4NZ AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:33 GMT-0500 (Central Daylight Time) The following resource(s) failed to create: [S3Bucket].        
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED hostingS3AndCloudFront AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:40 GMT-0500 (Central Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:617410213153:stack/********-qa-20190823131148-hostingS3AndCloudFront-16PWPPDKDG4NZ/fad86cd0-c5de-11e9-a658-0a4c9dfbdd94 was not successfully created: The following resource(s) failed to create: [S3Bucket]. 
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS ********-qa-20190823131148 AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:40 GMT-0500 (Central Daylight Time) The following resource(s) failed to create: [hostingS3AndCloudFront].
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS ********-qa-20190823131148 AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:56 GMT-0500 (Central Daylight Time) 
DELETE_IN_PROGRESS                           hostingS3AndCloudFront             AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:58 GMT-0500 (Central Daylight Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS ********-qa-20190823131148-hostingS3AndCloudFront-16PWPPDKDG4NZ AWS::CloudFormation::Stack Fri Aug 23 2019 14:48:58 GMT-0500 (Central Daylight Time) User Initiated
DELETE_SKIPPED     S3Bucket                                                                AWS::S3::Bucket            Fri Aug 23 2019 14:49:00 GMT-0500 (Central Daylight Time)               
⠙ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE ********-qa-20190823131148-hostingS3AndCloudFront-16PWPPDKDG4NZ AWS::CloudFormation::Stack Fri Aug 23 2019 14:49:00 GMT-0500 (Central Daylight Time) 
⠦ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE          hostingS3AndCloudFront             AWS::CloudFormation::Stack Fri Aug 23 2019 14:49:09 GMT-0500 (Central Daylight Time) 
UPDATE_ROLLBACK_COMPLETE ********-qa-20190823131148 AWS::CloudFormation::Stack Fri Aug 23 2019 14:49:09 GMT-0500 (Central Daylight Time) 
⠙ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠙ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: S3Bucket (AWS::S3::Bucket)
Event Type: create
Reason: ********-20190823130603-hostingbucket-qa already exists


✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
2019-08-23T19:49:30.451Z - error: uncaughtException: Resource is not in the state stackUpdateComplete
```

### Expected

We expect our app to be created in our `qa` AWS account similar to how it was created in our `dev` AWS account.

### Other notes

* We think cross account hosting is possible based on [#1907](https://github.com/aws-amplify/amplify-cli/issues/1907) and [#2094](https://github.com/aws-amplify/amplify-cli/issues/2094).
* We attempted to use the functionality outlined in [#508](https://github.com/aws-amplify/amplify-cli/issues/508).
* We attempted to verify our profiles were configured properly based on notes found in [#1072](https://github.com/aws-amplify/amplify-cli/issues/1072).

Please let me know if you have have any questions! Thank you in advance for the help. :tada:

**Comment by kaustavghosh06** [comment]
@tclindner In your AWS S3 console, can you check if you already have a bucket named - " ********-20190823130603-hostingbucket-qa"?
It looks ike you have one based on the error logs
`CREATE_FAILED      S3Bucket                                                                AWS::S3::Bucket            Fri Aug 23 2019 14:48:33 GMT-0500 (Central Daylight Time) ********-20190823130603-hostingbucket-qa already exists`

If you have it, then if you manually delete it from the S3 console and run an `amplify push` again, then your deployment should succeed.

**Comment by tclindner** [comment]
Thank you, @kaustavghosh06! Thanks for the super fast reply 🏅  There is one! I deleted it and did an `amplify push` again and it worked ✅ . Do you know if the steps outlined above are correct? It feels like we are missing something which is causing the manual delete step.

**Comment by kaustavghosh06** [comment]
@tclindner It seems like there was an unsuccessful deployment and it failed to rollback/delete the S3 bucket. We already have this in our backlog to delete S3 buckets on deployment failures.

**Comment by tclindner** [comment]
Thank you, @kaustavghosh06 👍

**Comment by aukaurea** [comment]
@kaustavghosh06 is the failed buckets remove automatic feature is done?
