### ISSUE TITLE
How does one see the output of a database trigger?

### ISSUE THREAD

**Issue by garrett-gottlieb** [aws-amplify/amplify-cli#2128]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? ** logging/output/testing/debugging

** What AWS Services are you utilizing? ** AppSync, DynamoDB, Lambda database trigger

** Provide additional details e.g. code snippets **
```bash
amplify add storage
// ...
? Select from the following options Create a new function
Successfully added resource mydbTriggerac33164d locally
Successfully updated resource mydbTriggerac33164d locally
? Do you want to edit the local mydbTriggerac33164d lambda function now? Yes
Please edit the file in your editor: /Users/me/Sites/myamplifyproject/amplify/backend/function/mydbTriggerac33164d/src/index.js
? Press enter to continue
Successfully added resource thinkdb locally

Some next steps:
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
```

After creating a db trigger function with the boilerplate code:
```js
exports.handler = function(event, context) {
  //eslint-disable-line
  console.log(JSON.stringify(event, null, 2))
  event.Records.forEach(record => {
    console.log(record.eventID)
    console.log(record.eventName)
    console.log('DynamoDB Record: %j', record.dynamodb)
  })
  context.done(null, 'Successfully processed DynamoDB record') // SUCCESS with message
}
```
I want to test it to see how it works. So I run
```bash
amplify mock
```
and head to the GraphiQL at http://192.168.2.145:20002/ and run a create mutation on my database like
```graphql
mutation MyMutation {
  __typename
  createPost(input: {text: "test2"}) {
    id
    text
  }
}
````
But I get no output in my console. I'm wondering where I can find it, or how to find out if the trigger is even running.

Thanks!

**Comment by kaustavghosh06** [comment]
@garrett-gottlieb We recently added a feature to attach a trigger to the DDB tables generated by the GraphQL transformer. You can checkout the documentation out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation

You'll see the result of this operation locally with amplify mock. Let me know if this doesn't answer or solve your issue by commenting on this thread. Closing this issue.
