### ISSUE TITLE
How to send an email using just Amplify backend custom business logic

### ISSUE THREAD

**Issue by Monder87** [aws-amplify/amplify-cli#2131]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
api , @fuction directive , email, custom business logic

** What AWS Services are you utilizing? **
amplify-cli, react, graphQl

** Provide additional details e.g. code snippets **

I  used amplify to create the back end of my react app, all worked fine regarding auth and create, update, delete and query data in my graphQL api, but i just feel confused how to add other business logic on my app.
I m quite new to serverless appsync stack so probably i just miss some concept here.
This is the scenario:
I have a request a demo form in my website that is accessible to everyone without auth, in this form everyone can compile the form and send me one email straight to my company mailbox.
Normally in a typical rest api i would send the form data to my back end endpoint and process some business logic there, for example using the Amazon SES api to send a email to my address.
But with appsync  i m kind of confused, where to put my functions?
The most closest result to achieve this was to use Lambda resolver with  ```amplify add function``` and using  the @function directive in my graphQL schema:

my function index.js:

```
const sendEmail = () => {
  console.log("Sending email!");
  return { value: true };
};

const resolvers = {
  Query: {
    sendEmail: () => {
      return sendEmail();
    }
  }
};

exports.handler = async (event, context) => {
  const typeHandler = resolvers[event.typeName];
  if (typeHandler) {
    const resolver = typeHandler[event.fieldName];
    if (resolver) {
      var result = await resolver(event);
      console.log("Email Sent!");
      console.log(result);
      return result;
    }
  }
  context.done(null, "Hello World"); // SUCCESS with message
};

```
my function package.json

```
{
  "name": "sendEmail3",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0"
}
```

my schema:

```
type Query {
  sendEmail: Response @function(name: "sendEmail3-${env}")
}

type Response {
  value: Boolean
}
```
Doing this i could send a email or whatever other business logic needed with just a simple graphQL query from my react app:

```
API.graphql(graphqlOperation(queries.sendEmail))
    .then(response => {
      console.log(response);
    })
    .catch(e => {
      console.log(e);
    });
```
so far so good, but the problem is that i need do all this with users that are not logged in, so i got a 
```
No current user
```
error, cause is not being authenticated being public. 
Now i m really not sure if this is the right approach, if yes please if someone can help me to understand how to process queries without authentication, if is wrong approach  please if you can help me to understand how to implement this.
Thanks

**Comment by Monder87** [comment]
ok i still didn't founded a clear and easy way to process queries without authentication.
So far i followed  [this](https://github.com/dabit3/appsync-auth-and-unauth) written by @dabit3 , but in my case just didnt work.
i followed all the steps:
1.
``` 
amplify init 
```
2.
```
amplify add auth
```
```
 Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito. 
 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IA
M controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: sandbox
 Please enter a name for your identity pool. sandbox
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Please provide a name for your user pool: sandbox
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? (Press <space> to select, <a> to toggle all, <i> to invert selection)E
mail
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert
 selection)
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
Successfully added resource sandbox locally
```
3. amplify add auth

```
? Please select from one of the below mentioned services GraphQL
? Provide API name: sandbox
? Choose an authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project
? Do you have an annotated GraphQL schema? Yes
? Provide your schema file path: 
francescos-MacBook-Air:sandbox francesco$ amplify add api
? Please select from one of the below mentioned services GraphQL
? Provide API name: sandbox
? Choose an authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? Yes
? What best describes your project: One-to-many relationship (e.g., “Blogs” with “Posts” and “Comments”)
? Do you want to edit the schema now? Yes
Please edit the file in your editor: 
? Press enter to continue 
GraphQL schema compiled successfully.
```

4.
```
amplify push
```
5.

In the AppSync API dashboard settings, change the authentication type to AWS Identity and Access Management (IAM), and i did it.

6.

In aws.exports.js on the client app, change aws_appsync_authenticationType to AWS_IAM, and i did it.

7.

In the Cognito dashboard, click "Manage Identity Pools" & click on your identity pool.

8.

Click "Edit Identity Pool" to see your "Unauthenticated role" & "Authenticated Role"
i copy the role , in my case is : 
```
arn:aws:iam::698989474885:role/sandbox-sandbox-20190827091153-unauthRole
``` 
9.
Open the IAM console & find the "Unauthenticated role" from step 8, which i found it successfully
 but once i tried to add this inline policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:<REGION>:<ACCOUNTID>:apis/<APIID>/types/Query/fields/sendEmail"
            ]
        }
    ]
}
```
in review your policy i get: 
```
This policy does not grant any permissions. To grant access, policies must have an action that has an applicable resource or condition. For details, choose Show remaining Learn more
```
so i am stock again, please help i am quite in hurry to finish my app.

**Comment by kaustavghosh06** [comment]
@Monder87 The CLI now supports out of the box IAM support for AppSync API's as a part of the GraphQL transformer. Please take a look at it out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#public-authorization and let us know if you're still stuck.

**Comment by jobypthomas** [comment]
@Monder87 I tried to use the method to send email from Amplify using aws-sdk and SES(). However ses.sendEmail() is not invoking. However, I was able to send email from the console. I think it is some permission issue. I tried to attach the role SES execution policy to the lambda function role using AWS Console but without luck. Any pointers?

**Comment by gmunizc** [comment]
Hi @jobypthomas, I am currently dealing with the exact same issue. Have you come across any solution?
