### ISSUE TITLE
Trying to read transformer config file on new amplify project throws error

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#2132]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

```
amp --version
1.12.1-authSubRelease.3
```

**Describe the bug**
Reading transformer config file on new amplify project throws error.

https://github.com/aws-amplify/amplify-cli/blob/31d70106d8fe9f65f6ab6eaf0a293e9fff170ab1/packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js#L58

there is no `cloudBackendDirectory ` folder in a new project.
trying to do `path.join(projectDir, TRANSFORM_CONFIG_FILE_NAME);` will throw an error

**To Reproduce**
1. create a new amplify project 
2. add an api and schema with @auth directive

**Expected behavior**
should default to new resource dir and create new config file. could so something like this:

```javascript
  const transformerConfig = await readTransformerConfiguration(cloudBackendDirectory || resourceDir)
```

**Comment by onlybakam** [comment]
the `cloudBackendDirectory` is actually meant to point to this `#current-cloud-backend`, so my suggested fix is not correct. but nonetheless, the directory does not exist on new project. should the reading/writing just be skipped?

**Comment by SwaySway** [comment]
Closing as this issue as it has been addressed in the latest release of the Amplify CLI.
