### ISSUE TITLE
add-graphql-datasource - aurora serverless - request template missing quotes

### ISSUE THREAD

**Issue by acme-one** [aws-amplify/amplify-cli#2133]
version: amplify-category-api: 1.11.0

"amplify api add-graphql-datasource" fails to add required single quotes in request template SELECT statements.

**To Reproduce**
Given an existing project with an api, and a serverless database with table "Whatever":
amplify api add-graphql-datasource

**Expected behavior**
Working request templates should be generated from the database schema.

example: Query.getWhatever.req.vtl

Should have single quotes around id param in the SELECT statement:
{
  "version": "2018-05-29",
  "statements":   ["SELECT * FROM Whatever WHERE id='$ctx.args.id'"]
}

**Actual behavior**
Missing single quotes.
{
  "version": "2018-05-29",
  "statements":   ["SELECT * FROM Whatever WHERE id=$ctx.args.id"] 
}

This results in all queries returning null:
{
    "data": {
        "getWhatever": null
    }
}

This applies to all templates except "list" (eg, getWhatever, createWhatever, updateWhatever)

**Comment by nikhname** [comment]
@acme-one I was not able to reproduce queries returning null using the rds transformer. Single quotes around the id param are not required in the resolver - the correct behavior with queries and mutations occurs without them. Could you provide more details about the steps you took to reach queries returning null so that I can try to reproduce this?

**Comment by nikhname** [comment]
What is the type of id in your schema?

**Comment by acme-one** [comment]
> What is the type of id in your schema?

I was using VARCHAR field for the primary key 'id' 

Exact steps to reproduce:

From RDS Query Editor:

CREATE TABLE `Pets` ( `id` varchar(45) NOT NULL, `name` varchar(45) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8

> amplify add api

(chose the basic "Todo" example)

> amplify api add-graphql-datasource

> amplify push

The simplest way to verify the issue is in the appsync console. Run this mutation:

mutation CreatePets {
  createPets(createPetsInput: {
    id: "abc",
    name: "Dino",
  }) {
    id
		name
  }
}

This successfully creates the row, but returns null:

{
  "data": {
    "createPets": null
  }
}

Now, edit the mutation named "createPets" in the appsync console, and add single quotes to the id param in the SELECT statement as follows:

"statements":   ["INSERT INTO Pets $colStr VALUES $valStr", "SELECT * FROM Pets WHERE id='$ctx.args.createPetsInput.id'"]

Add another Pet...

mutation CreatePets {
  createPets(createPetsInput: {
    id: "bcd",
    name: "Fido",
  }) {
    id
		name
  }
}

The return value will be correct:

{
  "data": {
    "createPets": {
      "id": "bcd",
      "name": "Fido"
    }
  }
}

Regarding the single quotes, I was using this for guidance, which uses single quotes in the SELECTS. https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html

**Comment by nikhname** [comment]
@acme-one Thank you for providing your exact steps, I was able to reproduce this behavior. This is a bug - single quotes should be generated around the id parameter since the type of id is varchar in  your table. We will work on a fix that generates the correct template based on the type of id.
