### ISSUE TITLE
Amplify should generate filter options for non-scalar types (subtypes or @connection types)

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2145]
For a type such as:
```graphql
type Package @model {
  id: ID!
  desc: String!
  company: Company! @connection
  servicetype: ServiceType! @connection
  price: Float!
  active: Boolean!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```
Amplify listPackages ModelPackageFilterInput supports only scalar types

id: ModelIDFilterInput
desc: ModelStringFilterInput
price: ModelFloatFilterInput
active: ModelBooleanFilterInput

ModelPackageFilterInput should allow filter by servicetype without the need to add a custom Query and Resolver in Appsync.

Similar issue to:
https://stackoverflow.com/questions/55000366/how-to-filter-a-non-scalar-type-in-appsync-amplify

**Comment by yuth** [comment]
@blairtaylor In your schema, package has 1 to 1 connection to both `Company` and `ServiceType`. Filtering is possible and useful only when the connection is 1 to many. 

If your schema was 1 to many `companies` and 1 to many `servicetypes` as shown below, then you would be able to filter both `companies` and `servicetypes`.
```graphql
type Package @model {
  id: ID!
  desc: String!
  companies: [Company] @connection(name: "PackageCompany")
  servicetypes: [ServiceType] @connection(name: "PackageService")
  price: Float!
  active: Boolean!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}```

When the connection is 1 to 1, there is only one record for both `company` and `servicetype` and there is nothing to filter.

**Comment by blairtaylor** [comment]
Thanks. I did not implement the 1:* relationship between Company and Package as it caused an error when attempting amplify api push. I had to reverse that change. Will have to investigate further.

If we could focus on the relationship between Package and ServiceType. There is one ServiceType per Package and each ServiceType can belong to multiple Packages. I should be able to filter Packages by ServiceType but the syntax described above does not work ie. servicetype(filter: {active: {eq: true}})  

This is what the schema looks like:

type Package @model {
  id: ID!
  desc: String!
  company: Company! @connection
  servicetype: ServiceType! @connection(name: "PackageService")
  price: Float!
  active: Boolean!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type ServiceType @model {
  id: ID!
  name: String!
  desc: String!
  active: Boolean
  company: Company @connection
  packages: [Package] @connection(name: "PackageService")
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

I believe this is modeled correctly. Let me know what I am doing wrong.

**Comment by yuth** [comment]
If you want to show all the packages that are active for a service type then you could use a query similar to this

```graphql
query getActivePackagesForService($id: ID!) {
  getServiceType(id: $id) {
    active
    desc
    id
    name
    packages(filter: {active: {eq: true}}) {
      items {
        desc
        id
        price
        createdAt
      }
    }
  }
}

```

**Comment by blairtaylor** [comment]
Thanks. We'll use this approach.

**Comment by ranjan-purbey** [comment]
> Amplify does create a filter when the connection is many to 1 or many to many. When the connection is t to 1 like in the above schema, there is no filtering needed. If you have a schema like below you should be able to filter it by passing arguments to your
> 
> ```graphql
> type Package @model {
>     id: ID!
>     desc: String!
>     company: Company! @connection(name: "PackageCompany")
>     servicetype: ServiceType! @connection(name: "PackageService")
>     price: Float!
>     active: Boolean!
>     createdAt: AWSDateTime
>     updatedAt: AWSDateTime
> }
> 
> type ServiceType @model {
>     id: ID!
>     name: String
>     packages: [Package] @connection(name: "PackageService")
> }
> 
> type Company @model {
>     id: ID!
>     name: String
>     packages: [Package] @connection(name: "PackageCompany")
> }
> ```
> 
> ### Query
> 
> ```graphql
> query getCompany {
>   getCompany(id: "package-id") {
>     name
>     id
>     package(filter: {active: {eq: true}}) {
>       items {
>         active
>         createdAt
>         desc
>         id
>         price
>       }
>     }
>   }
> }
> ```

In the query `getCompany`, shouldn't the argument be `id: 'company-id'` instead of `id: 'package-id'`
