### ISSUE TITLE
GraphQL Transform `keyField` in `@connection` directive is broken.

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-cli#2148]
**Describe the bug**
When using the `keyField` in `@connection`, the relationship does not work and the query returns an error.

I have tested this locally and in the service..

1. Create an AppSync API from the Amplify CLI
2. Add the following shema:
```
type Talk @model {
  id: ID!
  name: String!
  description: String!
  comments: [Comment] @connection(name: "TalkComments")
}

type Comment @model {
  id: ID!
  message: String
  createdAt: String
  talk: Talk @connection(sortField: "createdAt", name: "TalkComments", keyField: "talkId")
}
```

Run the following operations in this order:

```graphql
mutation createTalk {
  createTalk(input: {
    name: "Talk 1"
    description: "Cool talk"
  }) {
    id name description
  }
}

mutation createComment {
  createComment(input: {
    talkId: "<TALK_ID>
    message: "Great talk"
  }) {
    id message
  }
}

query listTalks {
  listTalks {
    items {
      id
      name
      description
      comments {
        items {
          message
        }
      }
    }
  }
}
```

**Expected behavior**
The comments array is populated with the comment.

**Screenshots**
<img width="478" alt="Screen Shot 2019-08-26 at 8 09 29 PM" src="https://user-images.githubusercontent.com/1857282/63738078-74398e00-c83d-11e9-992b-b01139ee07bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
CLI Version: 1.12.0 & the latest from Yathi's release

**Comment by RossWilliams** [comment]
You are using a Many to One connection, and the keyField on the Many side directive is used to find the hash key on the One side. In this case your many side @connection does not include keyField, so  the default ID is used, commentTalkId, not talkId. 
However, when the cli sets up the One side, it uses the specified keyField to set the GSI hash key.
Result is wrong key is used in lookup.

At a code level, graphql-connection-transformer/src/ModelConnectionTransformer.ts 'field' method part 2 is the problem. Specifically, validateKeyField does not throw an error when the keyField passed in is undefined. If passing in undefined threw an error, this issue would not be deployed and a user could correct the schema.

From a code architecture standpoint, tsconfig.json does not have strict null checks enabled. The validateKeyField definition is not correct if you turn on strict null checks, and I can't see a good reason why this is not enabled.

Documentation on this is not clear, and DX does not seem good. The need to match keyFields on both connections could be eliminated by replicating the use of 'associatedSortFieldName' for the keyField name as well.

**Comment by cottageGrove** [comment]
@mikeparisstuff currently having trouble adding the sortField to my schema. It's quite similar to the fix you posted but I get this error. 

Attempting to edit the global secondary index gsi-UserOrder on the OrderTable table in the Order stack. 
An error occured during the push operation: Attempting to edit the global secondary index gsi-UserOrder on the OrderTable table in the Order stack.
