### ISSUE TITLE
How do we use S3Object?

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#215]
** Which Category is your question related to? **
Storage/AppSync

** What AWS Services are you utilizing? **
Storage/AppSync

** Provide additional details e.g. code snippets **
Relevant link: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-react.html#complex-objects

How should we currently use S3Object?  There was a convention to follow previously, and it worked well.  Is this advised going foward?  If so, how?

**Comment by austinamorusocfc** [comment]
I also was wondering and have further questions.
https://github.com/aws-amplify/amplify-cli/issues/274

**Comment by kaustavghosh06** [comment]
This issue seems to have been fixed with the latest version. Please look at #274 for more info. Please feel free to re-open this issue if the problem still persists. Thanks!
