### ISSUE TITLE
Cannot Create a trigger on a  DynamoDB created with the CLI

### ISSUE THREAD

**Issue by horacioh** [aws-amplify/amplify-cli#2153]
**Describe the bug**
I tried to create a trigger from a DynamoDB table created from the CLI but I got some errors on the console

**To Reproduce**
1. `amplify add api`: and create a simple model (im my case I create this:
```
type Lead @model {
  id: ID!
  fullname: String!
  email: AWSEmail!
  phone: String!
  serviceType: Service
  comment: String
}

enum Service {
  RESIDENCIAL
  COMERCIAL
  INDUSTRIAL
}
```
1. `amplify add function`: create a simple function. add whatever name. no edit needed
1. `amplify push`
1. `amplify api console`
1. go to the triggers tab and create a new trigger from an existing Lambda Function
1. in the popup, Select the previous function created and leave the other inputs as is.
1. click on create nad you will see the error below
```
Cannot access stream arn:aws:dynamodb:eu-west-1:115238827609:table/Lead-xwwfwne24nd43feacszaupqof4-staging/stream/2019-08-25T15:08:37.527. Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4f297881-6498-49c3-b237-97e902972409)
```

**Expected behavior**
I expect the trigger to be created and let me edit/update my function on my editor and push it via the amplify cli.

**Screenshots**
<img width="1680" alt="Screen Shot 2019-08-27 at 6 02 34 PM" src="https://user-images.githubusercontent.com/725120/63788084-2c763d80-c8f5-11e9-9224-39cb11217b3b.png">

<img width="1680" alt="Screen Shot 2019-08-27 at 5 51 37 PM" src="https://user-images.githubusercontent.com/725120/63788102-326c1e80-c8f5-11e9-8e16-7e108217c1c9.png">

<img width="899" alt="Screen Shot 2019-08-27 at 2 50 39 PM" src="https://user-images.githubusercontent.com/725120/63789202-30a35a80-c8f7-11e9-9105-ed0e59c525b0.png">

**Desktop (please complete the following information):**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

Google Chrome:

      Version: 76.0.3809.100
      Obtained from: Identified Developer
      Last Modified: 8/6/19, 2:29 AM
      Kind: Intel
      64-Bit (Intel): Yes

**Additional context**
I tried it with a function created from the cli and with another functionc reated directly in the console. on both cases I got the same error so my assumption is that cloudformation is not doing something on the DynamoDB and prevent this to work properly.

**Comment by horacioh** [comment]
thanks for the solution @kaustavghosh06 !
I'm not too familiar with all AWS tools, can you give me a more detailed step by step?
- where do I need to add this code you mentioned?
- do I need to change something in the console?
- can everything be done via de CLI and this snippet?

thanks!

**Comment by kaustavghosh06** [comment]
@horacioh Sorry for the late response:

1. You would need to modify this via the console for tables managed by the GraphQL transformer, but this should soon be addressed out of the box - as a part of the CLI - as a part of this PR - https://github.com/aws-amplify/amplify-cli/pull/2463

2. In the meanwhile, you can go the Lambda console - go to your Lambda function trigger -> Find out the Lambda Execution Role Name -> Attach the policy mentioned above as a part of the Lambda execution role in the IAM console.

3. Answered in 1.
