### ISSUE TITLE
@model directive with queries parameter renames the query after some time

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#2155]
**Describe the bug**
I have a `Business` model and the `list` query for it is `listBusinesss` which is wrong and should be `listBusinesses`, so I used the `queries` parameter on the @model directive like so -
`@model(queries: { get: "getBusiness", list: "listBusinesses })`, and it worked fine, but then after a few hours I get an error in my app - 
```
"Validation error of type FieldUndefined: Field 'listBusinesses' in type 'Query' is undefined @ 'listBusinesses'"
```
and I went to the AWS AppSync console and checked the queries there, and there it is - `listBusinesss`. I didn't touch the console during that time

**To Reproduce**
1. create graphql schema
2. use the @model queries parameter to set the query name for the `list` query
3. wait a few hours

**Expected behavior**
the `list` query should stay with the name that I gave it in the schema

**Screenshots**
I wrote a note to see how long it takes it to change (not exact times, this is when I figured it out) -
![image](https://user-images.githubusercontent.com/28350511/63795898-a4e8f880-c90d-11e9-89e8-2a86eeaeff1b.png)

**Comment by kaustavghosh06** [comment]
@idanlo Did you test your app after immeidately pushing the schema using the CLI?
Also, did the push succeed or did it rollback? You can check for the logs in the AWS Cloudformation Console.

**Comment by idanlo** [comment]
@kaustavghosh06 Yes I immediately tested it.
The push looked like it succeeded looking at the CLI (no errors) but I haven't checked Cloudformation

**Comment by kaustavghosh06** [comment]
@idanlo Are you still seeing this issue? Our team wasn't able to reproduce this behavior.

**Comment by idanlo** [comment]
@kaustavghosh06 A few days after I wrote this issue it stopped happening
