### ISSUE TITLE
Why is authorization in queries put in the response resolver instead of request?

### ISSUE THREAD

**Issue by amirmishani** [aws-amplify/amplify-cli#2156]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
Appsync & DynamoDB
** Provide additional details e.g. code snippets **
So I've noticed that authorization checks for mutations are happening in the request resolver which makes sense, you can't touch data unless you're authorized. But when it comes to queries it's the opposite, authorization is happening on the response, which means it is still safe to use but you're forced to incur charges by hitting the database first. Is there some technical reason I'm missing here?

**Comment by undefobj** [comment]
The authorization metadata lives on the item itself inside DynamoDB, so a read must take place either way. For instance on owner based checks the record itself must be read before performing a comparison with the user context.
