### ISSUE TITLE
amplify 2.0 CLI fails GQL-COMPILE with TypeError

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#2167]
Hello!

**Describe the bug**

This is in the 2.0.0 release of the CLI.

After an initial "amplify push" subsequent amplify push or gql-compile attempts will fail until "amplify env pull" is executed. The error is reported to the console as: TypeError: Cannot convert undefined or null to object

**To Reproduce**
upgrade to the 2.0.0 CLI
make a change to your api
run amplify push
once the update completes: make another change to your api and run "amplify api gql-compile"

**Expected behavior**
The api should compile successfully.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10, Powershell

FWIW: I have several models that are not using @auth and get the new warning when compiling, the error appears right after the warning.

Thank you.

**Comment by kaustavghosh06** [comment]
@ryanhollander Could you please send it to us at `amplify-cli@amazon.com`?

**Comment by ryanhollander** [comment]
@kaustavghosh06 just sent. Thanks!

**Comment by gabriel-wilkes** [comment]
I also have this issue on a Mac, so it certainly isn't platform specific.

**Comment by yuth** [comment]
@ryanhollander @gabriel-wilkes do you happen to have any custom resolvers or resources in your project?

**Comment by ryanhollander** [comment]
@yuth Yes, I have a few custom data sources, roles, functions, and resolvers.

**Comment by gabriel-wilkes** [comment]
Yes, I have a custom resolver which required a custom resource

**Comment by yuth** [comment]
@ryanhollander  @gabriel-wilkes Do you mind sharing a minimal project which can reproduce this issue. Please send it to `amplify-cli@amazon.com`

**Comment by gabriel-wilkes** [comment]
Thanks, I have sent the minimal project now.

**Comment by yuth** [comment]
> Thanks, I have sent the minimal project now.

@gabriel-wilkes I looked at your project. Its a bug in the graphql-transformer which is not related to Amplify CLI v 2.0. It was an existing bug. We will have a fix for this but in the mean time you could unblock yourself by adding `Outputs` section to  `<project-root>/amplify/#current-cloud-backend/api/jscreenapp/build/stacks/CustomResources.json` 

```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "An auto-generated nested stack.",
    "Metadata": {},
    "Parameters": {
        "AppSyncApiId": {
            "Type": "String",
            "Description": "The id of the AppSync API associated with this project."
        },
        "AppSyncApiName": {
            "Type": "String",
            "Description": "The name of the AppSync API",
            "Default": "AppSyncSimpleTransform"
        },
        "env": {
            "Type": "String",
            "Description": "The environment name. e.g. Dev, Test, or Production",
            "Default": "NONE"
        },
        "S3DeploymentBucket": {
            "Type": "String",
            "Description": "The S3 bucket containing all deployment assets for the project."
        },
        "S3DeploymentRootKey": {
            "Type": "String",
            "Description": "An S3 key relative to the S3DeploymentBucket that points to the root\nof the deployment directory."
        }
    },
    "Conditions": {
        "ShouldNotCreateEnvResources": {
            "Fn::Equals": [
                {
                    "Ref": "env"
                },
                "NONE"
            ]
        },
        "HasEnvironmentParameter": {
            "Fn::Not": [
                {
                    "Fn::Equals": [
                        {
                            "Ref": "env"
                        },
                        "NONE"
                    ]
                }
            ]
        },
        "AlwaysFalse": {
            "Fn::Equals": [
                "true",
                "false"
            ]
        }
    },
    "Resources": {
      .... your resources
    },
    "Outputs": {} # include this
}
```

**Comment by gabriel-wilkes** [comment]
Thanks @yuth, that fixed the issue!

**Comment by ryanhollander** [comment]
@yuth @kaustavghosh06  I'm sorry, I can no longer reproduce the issue! It seems to have gone away on it's own while I was working on my API. If it shows back up I'll re-open. Thanks for looking into it.

**Comment by ryanhollander** [comment]
OK, So I spoke too soon...

**Comment by yuth** [comment]
@ryanhollander does your custom stack have `Outputs` and `Resources` section? The GraphQL Transformer has a bug where if the custom stack is missing either of these keys it crashes. I have raised #2176  which should fix this problem

**Comment by ryanhollander** [comment]
@yuth I'll test that, thanks.

**Comment by ryanhollander** [comment]
@yuth ok, it looks like adding: "Outputs": {} to my #current-cloud-backend/api/.../build/stacks/CustomResovlers.json fixed the first issue during gql-compile, however now I get a new error during push about my "NoneDataSource" which is a data source with the type of "None" I use for some pipeline functions and is defined in the CustomResolvers.json. 

UPDATE_FAILED               apiFrontOfficeDashboardAPI     AWS::CloudFormation::Stack Fri Aug 30 2019 21:04:14 GMT-0400 (Eastern Daylight Time) Template format error: Unresolved resource dependencies [NoneDataSource] in the Resources block of the template

Running "amplify env pull" resolves it, as does removing the build directory in #current-cloud-backend and running push.

I've done some diffs and in no case does the "Outputs":{} item appear, after I pull the env the #current-cloud-backend/api/.../build/ directory is not present.

Thanks.
