### ISSUE TITLE
No such file or directory error when using amplify mock api

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2170]
Steps to reproduce:

amplify mock api

Error message:

Error: ENOENT: no such file or directory, lstat 'D:\code\aws\amplify\marketbox\amplify\backend\api\marketbox\resolvers\Subscription.onUpdateUserInvitation.res.vtl'

I receive the same error message for all my schema types.

Schema has 30 types. I can send via email for further diagnosis if this helps.

Platform is Windows 10. Amplify version is 2.0.0

**Comment by kaustavghosh06** [comment]
@blairtaylor Can you please send us your schema at `amplify-cli@amazon.com`?

**Comment by blairtaylor** [comment]
Done. Thanks.

**Comment by attilah** [comment]
@blairtaylor I tried to reproduce it with the latest version of the CLI and it worked. Would you give it a try and get back to us?

**Comment by attilah** [comment]
Closing due to lack or response for quite some time.
