### ISSUE TITLE
One table with nested items return null.

### ISSUE THREAD

**Issue by Jscott388** [aws-amplify/amplify-cli#2171]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
GraphQL

** Provide additional details e.g. code snippets **

I only need one table but I have nested items.
```graphql
type Property @model {
    Address: String
    Media: [Media] # I don't want @connection because I just need one table
}

type Media {
     URL: String
     Order: Int
}
```

I don't need a separate table for media, because I am fetching through a real estate API and saving the documents. The API response is structure as one response with the media objects.

The property query will not return the correct response. Media is Null. 

DynamoDB is saving the object in the table but I believe is a map structure. Something like:
```
{ 'M": { "S": something something... 
```
I can't recall specifically as I deleted the project to restart over but ending up with same thing. 

How can i use one table to house the nested media objects and correctly query with the array of nested items.

**Comment by yuth** [comment]
Media should return the values. Could you share the query and mutations that you are using when you get the response as null.

I tried your schema with appsync and created a record using the following mutation
```graphql
mutation create {
  createProperty(input: {Address: "foo", Media: [{URL: "Foo", Order: 10}]}) {
    Address
    Media {
      URL
      Order
    }
  }
}
```
and when I run the following query 
```graphql
query list {
  listPropertys {
    items {
      Address
      Media {
        URL
        Order
      }
    }
  }
}
```

I get the response as expected
```json
{
  "data": {
    "listPropertys": {
      "items": [
        {
          "Address": "foo",
          "Media": [
            {
              "URL": "Foo",
              "Order": 10
            }
          ]
        }
      ]
    }
  }
```

**Comment by Jscott388** [comment]
Let me double check this.

**Comment by yuth** [comment]
Feel free to comment if you are still seeing the issue
