### ISSUE TITLE
Crash when running `amplify add api`

### ISSUE THREAD

**Issue by joshwnj** [aws-amplify/amplify-cli#218]
**Describe the bug**
When running `amplify add api` the cli crashed on selecting "Do you want to edit the schema now":

```
? Do you want to edit the schema now? Yes
TypeError: fs.copyFileSync is not a function
    at serviceWalkthrough (/Users/josh/.nvm/versions/node/v8.3.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:164:6)
    at <anonymous>
There was an error adding the API resource
```

This seems to be due to running in an older node version (I was using v8.3.0), as `fs.copyFileSync` was only added in v8.5.0 according to the docs: https://nodejs.org/api/fs.html#fs_fs_copyfilesync_src_dest_flags

Perhaps we could check the user's node version and warn if they're running an older versions?  I'd be happy to put together a PR if you agree on this course :)

**To Reproduce**
1. In a new project run `amplify add api`
2. On "Do you want to edit the schema now?" select Yes
3. See error

**Desktop (please complete the following information):**
 - Node Version 8.3.0

**Comment by kaustavghosh06** [comment]
@joshwnj  Please use Node version >= 8.11.x.

**Comment by joshwnj** [comment]
Thanks @kaustavghosh06 . I've submitted #224 as an easy way to prompt users with old node versions to upgrade.

**Comment by kaustavghosh06** [comment]
Merged it. Thanks for the PR @joshwnj

**Comment by ardeshir** [comment]
Seems this error happens with node v10.7.0 still.

Do you want to edit the schema now? Yes
Error: EISDIR: illegal operation on a directory, copyfile '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/../appsync-schemas/single-object-schema.graphql' -> '/Users/administrator/cargill/presigned-url-lambda/amplify/backend/api/signedurl/schema.graphql'
    at Object.copyFileSync (fs.js:1697:3)
    at serviceWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:204:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the API resource
