### ISSUE TITLE
src/graphql -> query and mutations not generating

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-cli#2190]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by yuth** [comment]
Could you share the `<project-root>/.graphqlconfig.yml` so we could reproduce this issue. Please make sure you obfuscate sensitive information like API Keys
