### ISSUE TITLE
Deleting record with connections causes nullable error

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#2195]
** Which Category is your question related to? **
API

I have created a pretty large app with Amplify and am testing the removal on records from the user dashboard. 

The delete call works great and removes the records from their requested tables.

However I have noticed that if I delete a record which has connections to other records, pulling the records with subsequent connections will now give this error:

> Cannot return null for non-nullable type

or in a specific example :

>  Cannot return null for non-nullable type: 'Entity' within parent 'Subscriber'

Now I understand why this is happening as the Subscriber record has a connection to an entity which has now been deleted. 

Is there a way to ensure the connection die with the deleted record? I don't want to use a deleted field to deal with deletion as the database will grow very very fast.

Is there a best practice for deal with deleting records in amplify and their subsequent connections?

**Comment by yuth** [comment]
@oliverandersencox from error message it looks like the error happens due to the constraints that were put in the GraphQL schema. Could you share a sample schema where we can reproduce this error when an record is deleted.

**Comment by oliverandersencox** [comment]
@yuth you are correct. It turns out I have the required flag on the fields with connections and when removed, this no longer occured
