### ISSUE TITLE
Amplify CLI Migration fails

### ISSUE THREAD

**Issue by fabianjj** [aws-amplify/amplify-cli#2196]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify CLI fails to migrate to newer version. 

**To Reproduce**
1. I have a project configured with an older version of the CLI.
2. Update the CLI to 3.0.0.
3. Try almost any amplify command (this triggers a request to migrate).
4. Try migrating.
5.

During the migration the following appears a bit in:

```
⠴ Migrating your project
The following types do not have '@auth' enabled. Consider using @auth with @model
         - TripComponent
         - PackItem
         - TripComponentConnection
         - TripPackItemExclude
         - TripPackItemInclude
         - Trip
         - User
         - TripParticipation
         - PackAssign
         - PackList
         - PackListEntry
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 

⠙ Migrating your projectReverting API migration.
⠋ Migrating your project
```

And at the end, all I get is the following error:

```
⠋ Migrating your projectAPI successfully reverted.
✖ There was an error migrating your project.
migration operations are rolledback.
Cannot convert undefined or null to object
```

**Expected behavior**
I expect the automatic migration command to work. I haven't really changed anything in the API other than a simple graphql schema. 

**Desktop (please complete the following information):**
 Using WSL in Visual Studio Code.

**Comment by yuth** [comment]
@fabianjj could you share a sample schema where we can reproduce this issue

**Comment by houmark** [comment]
Oh, migration is necessary?

On a related note, using ANY command in Amplify CLI with a new version (for example `amplify status`), Amplify CLI should detect that the project is running configuration based on an older and clearly with a WARNING text in red color explain how to migrate or have an option to migrate all services/categories in with one acceptance by the user.

I want to test this out, but considering this bug report, I think I will hold off a bit :)

**Comment by houmark** [comment]
Feature request related to my comment opened in #2202.

**Comment by fabianjj** [comment]
@houmark: Using any command for me triggers the request for migration, including a red warning text. It does not allow any command to be performed unless a migration is made. Declining to migrate cancels the command.

**Comment by fabianjj** [comment]
@yuth, here is the schema I'm using:

`type TripComponent @model {
  id: ID!
  name: String!
  packItems: [PackItem!]! @connection(name: "ComponentPackItems")
  tripsThatHaveComponent: [TripComponentConnection!]! @connection(name: "TripComponentTrip")
}

type PackItem @model {
  id: ID!
  name: String!
  description: String
  tripComponent: TripComponent! @connection(name: "ComponentPackItems")
  tripsThatExcludeItem: [TripPackItemExclude!]! @connection(name: "PackItemExcludeTrip")
  tripsThatIncludeItem: [TripPackItemInclude!]! @connection(name: "PackItemIncludeTrip")
  mandatory: Boolean!
  perTrip: Boolean!
}

type TripComponentConnection @model(queries: null) {
  id: ID!
  trip: Trip! @connection(name: "TripTripComponent")
  tripComponent: TripComponent! @connection(name: "TripComponentTrip")
}

type TripPackItemExclude @model(queries: null) {
  id: ID!
  trip: Trip! @connection(name: "TripPackItemExclusion")
  excludedItem: PackItem! @connection(name: "PackItemExcludeTrip")
}

type TripPackItemInclude @model(queries: null) {
  id: ID!
  trip: Trip! @connection(name: "TripPackItemInclusion")
  includedItem: PackItem! @connection(name: "PackItemIncludeTrip")
}

type Trip @model {
  id: ID!
  name: String!
  participants: [TripParticipation!]! @connection(name: "TripParticipants")
  tripComponents: [TripComponentConnection!]! @connection(name: "TripTripComponent")
  tripExcludes: [TripPackItemExclude!]! @connection(name: "TripPackItemExclusion")
  tripIncludes: [TripPackItemInclude!]! @connection(name: "TripPackItemInclusion")
  packAssigns: [PackAssign!]! @connection
  isDraft: Boolean!
}

type User @model {
  id: String!
  name: String!
  tripParticipations: [TripParticipation!]! @connection(name: "UserTrips")
  tripDraft: Trip @connection
}

type TripParticipation @model {
  id: ID!
  trip: Trip! @connection(name: "TripParticipants")
  participant: User! @connection(name: "UserTrips")
  packList: PackList @connection(name: "ParticipationPackList")
}

type PackAssign @model {
  id: ID!
  packItem: PackItem! @connection
  user: User @connection
  PackListEntry: PackListEntry @connection
}

type PackList @model {
  id: ID!
  tripParticipation: TripParticipation! @connection(name: "ParticipationPackList")
  userExcludes: [PackItem!]! @connection
  userIncludes: [PackItem!]! @connection
  PackListEntries: [PackListEntry] @connection
}

type PackListEntry @model {
  id: ID!
  packItem: PackItem! @connection
  owned: Boolean!
  packed: Boolean!
}`

**Comment by houmark** [comment]
> @houmark: Using any command for me triggers the request for migration, including a red warning text. It does not allow any command to be performed unless a migration is made. Declining to migrate cancels the command.

Also `amplify status`?

**Comment by fabianjj** [comment]
@houmark Yes, amplify status as well.

**Comment by yuth** [comment]
@fabianjj do you have a custom resource in your GraphQL API? We have had https://github.com/aws-amplify/amplify-cli/issues/2167, which was caused due to missing `Outputs` section in custom resources

**Comment by fabianjj** [comment]
@yuth not that I’m aware of, it should only be the schema. 

I do use a separate AWSconfig file from the auto-generated one  when I run my app (if I remember correctly it was because I got the wrong cognito user pool).

**Comment by yuth** [comment]
@fabianjj could you share a project which we can reproduce this on. You could share it privately by sending it to amplify-cli@amazon.com

**Comment by fabianjj** [comment]
@yuth. Sure, I can share the project I'm working on. Should I include all the contents of the amplify folder as well, or is there anything I can exclude?

**Comment by yuth** [comment]
Please include all the contents of amplify folder

**Comment by fabianjj** [comment]
All right, thanks. An email should be on its way.

**Comment by yuth** [comment]
I was able to reproduce the issue. I am working on a fix for this

**Comment by fabianjj** [comment]
Great, please let me know if there’s anything else I can do to assist.

**Comment by fabianjj** [comment]
With the latest version, the migration does go thorugh (I'm facing other problems trying to update some of my resources, but that's a separate issue.
