### ISSUE TITLE
DynamoDB indexes not being removed on amplify push rollback

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#2197]
**Describe the bug**
Not exactly sure how I got to the point where a rollback happened, but I did. After that I went into a loop of rollbacks until I realized the root of the problem.

After my initial rollback the DynamoDB tables where deleted. My theory is that I did a push in CLI and later I committed code to Git which triggered a Console automatic deployment/push but I did not commit the schema.graphql so it removed my tables (this should not happen when the Console is deploying maybe or we should have the chance to protect tables?).

Anyways, in the following attempts to push using CLI, I noticed in the flow of errors that it was trying to create an index to a new schema on an existing table (this table was in my schema since project day 1 and was doing a named connection to the new table, hence the automatically created index). When I looked at the DynamoDB browser console, the index was there, even after the rollback completed. This also happened on another table so it was not a single bird.

So once a situation happens and Amplify ends up doing rollback, Amplify fails to clean up to a clean rollback state, which then blocks future pushes even if the original problem is corrected. Manually deleting the index(es) solves the problem.

**To Reproduce**
Not exactly sure what's the simplest way to reproduce but it should be easy to confirm that DynamoDB indexes are not deleted on rollback.

**Expected behavior**
Amplify should in the best case delete the indexes on rollback, to prevent this from becoming blocking on the next push. In addition, an attempt to create an index should maybe not be blocking but only a warning so it does not result in a rollback.

**Additional context**
I'm using Amplify CLI 3.0.0 in both CLI and Console.

**Comment by yuth** [comment]
@houmark thank you for reporting this issue. This is the limitation that cloud formation has when dealing with DynamoDB as [documented](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html)
> Global secondary indexes to be created on the table. You can create up to 20 global secondary indexes.

> Important

> If you update a table to include a new global secondary index, AWS CloudFormation initiates the index creation and then proceeds with the stack update. AWS CloudFormation doesn't wait for the index to complete creation because the backfilling phase can take a long time, depending on the size of the table. You can't use the index or update the table until the index's status is ACTIVE. You can track its status by using the DynamoDB DescribeTable command.

> If you add or delete an index during an update, we recommend that you don't update any other resources. _If your stack fails to update and is rolled back while adding a new index, you must manually delete the index._

We are brainstorming how best we can handle this from Amplify CLIs side. We have a couple of ideas how we should handle this
1. If the rollback happens, show an error message and asking users if they want to delete the newly created indexes 
2. Before doing a push, check if the GSI is present from previous deployment and then remove it.

We still need to investigate if there are any other side effects of doing either of this, but I have added this into our backlog and will get it prioritized .

**Comment by houmark** [comment]
Yes, I think 1 and 2 both apply here.

AN UPPERCASE RED message at the end of the rollback would at least notify me to go and delete the indexes manually (I guess it knows which indexes it created, so it could point me pretty deep to the index). If that can even result in a prompt in the CLI which gives me the option to safely delete the exact indexes, then that's even better.

And doing an index comparison before push to see if this push would create indexes that conflicts, bail out and warn to the user. That at least is much faster to correct for me as a dev, than to wait for minutes before it fails, starts rolling back, and then that takes another 5-10 mins. I guess this could solve other edge cases where this happens due to other reasons (for example if I created an index manually with the same name).

**Comment by kaustavghosh06** [comment]
@houmark We have a sanity check in place right now which runs before `amplify push`- exactly as you've mentioned above to prevent this issue. We have in our backlog to make this experience between by queueing DDB deployments in a scenario like yours.
