### ISSUE TITLE
Projects do not appear in MobileHub

### ISSUE THREAD

**Issue by ryanwmarsh** [aws-amplify/amplify-cli#22]
Do you want to request a feature or report a bug?
🐞

What is the current behavior?
**Amplify projects created with the CLI do not appear in MobileHub**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**1.  `create-react-native sample-app`
2. `cd sample-app`
3. `amplify configure`
4. `amplify init`
5. Check MobileHub in AWS Console**

What is the expected behavior?

**Project should appear in MobileHub console.**

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?

**0.1.13**

**Comment by UnleashedMind** [comment]
you meant amplify init? 
amplify-cli does not use Mobile Hub as its backend, it directly provisions aws resources for you.

**Comment by jarrettj** [comment]
Hi,

Good day.

But if it is replacing awsmobile-cli it should. Or not? I don't quite understand. As I see no reference to awsmobile-cli documentation anymore.

Regards.

**Comment by 0xR** [comment]
Currently it is really confusing whether you should use the amplify-cli or the awsmobile-cli. Both can be used to do amplify, whatever that means. The difference seems to be the usage of mobile hub. But does that mean that you just won't be able to use the mobile hub web UI or are there more differences?

Please write documentation / blogpost to clarify this.

**Comment by ryanwmarsh** [comment]
@UnleashedMind 
> you meant amplify init? 

Yes, corrected. 

@0xR yes it's more than a little confusing, check this out. 
![awsmobile amplify question 2018-08-26 10_58_27](https://user-images.githubusercontent.com/824046/44630170-1539f400-a91f-11e8-9437-b59c59b57a01.gif)

**Comment by jadbox** [comment]
I'm also starting a new web project with Cognito auth and wondering if amplify-cli will be preferred route to take. It seems awsmobile-cli hasn't had much git activity compared to this project, but I don't know if I'm reading too much into it. Also I'm not sure how I can migrate Cognito that was created with awsmobile over to amplify-cli...

**Comment by jarrettj** [comment]
Yup I don’t see a migration path either. You would have to manually set it up. I deleted my awsmobile and started over. As the docs for it points at amplify. Think they jumped the gun here. Left a lot of people most confused.
