### ISSUE TITLE
Is there a native way to query AppSync fror createdAt and upadtedAt?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-cli#2200]
Those fields exist in the DB but it seems like there is no way to query for them with GraphQL and the autogenerated resolvers.

**Comment by yuth** [comment]
Please feel free to re-open or comment on the issue if this does not answer your question.

**Comment by bob-lee** [comment]
Related discussion: https://github.com/aws-amplify/amplify-cli/issues/401

On `@aws-amplify/cli@3.2.0`, after I added fields for timestamps and `amplify push`, I could query them:
```
type MyTable
{
  id: ID!
  createdAt: AWSDateTime # <-- added
  updatedAt: AWSDateTime # <-- added
  ...
```
