### ISSUE TITLE
Amplify CLI should inform the user of possible migration with any command

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#2202]
**Is your feature request related to a problem? Please describe.**
I am running Amplify CLI 3.0.0, but my project started in early version 1.x. It's not clear to me that migration is preferred or necessary until I do some kind of update to a service. This may or may not create side effects or issues when pushing a project.

**Describe the solution you'd like**
Any command in the CLI, including a simple status with `amplify status` should detect a possible necessary or optional migration due to the project running on an older version vs. the current CLI and offer the user to do a project-wide migration or at least offer to migrate service/category one by one.

**Comment by kaustavghosh06** [comment]
@houmark We added to the CLI a few months back an update message if a newer version of the Amplify CLI is available on npm and steps to get the latest version. After updating the CLI version, if there's migration required, we prompt customers for the related migration for consent before migration. Closing this issue and please let us know if there's more we can do on this front from the CLI UX point of view.
