### ISSUE TITLE
Mock resolvers do not adhere to velocity template version

### ISSUE THREAD

**Issue by nateiler** [aws-amplify/amplify-cli#2211]
I noticed a discrepancy in the execution of a response resolver between the Mock and Cloud instances.

```
query GetPreferences {
  getPreferences {
    id
  }
}
```

req.vtl
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
    "id": $util.dynamodb.toDynamoDBJson($ctx.identity.claims.get("cognito:username"))
  } #end
}
```

res.vtl
```
#if( $util.isNullOrEmpty($context.result) )
    #set ($result = {})
    $util.qr($result.put("id", $ctx.identity.claims.get("cognito:username")))
    $util.toJson($result)
#else
    $util.toJson($ctx.result)
#end
```

When mocked, if a result is empty the response template is still executed.  Per [upgrade docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-changelog.html#aws-appsync-resolver-mapping-template-version-2018-05-29) I changed the request template version to "2018-05-29" and both Mock and Cloud produced the same results.

I wasn't aware of the impact regarding different template versions, but made the change to 'req.vtl' to:
```
{
  "version": "2018-05-29",
  "operation": "GetItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
    "id": $util.dynamodb.toDynamoDBJson($ctx.identity.claims.get("cognito:username"))
  } #end
}
```

**Comment by visusnet** [comment]
Seems to be related to https://github.com/aws-amplify/amplify-cli/issues/2134
