### ISSUE TITLE
how to control mandatory fields for create mutation in @ model

### ISSUE THREAD

**Issue by pspanchal** [aws-amplify/amplify-cli#2215]
** Which Category is your question related to? **
create function in @model.  

** What AWS Services are you utilizing? **
When creating an @model if I mark ! next to the field then the create function adds it as a mandatory field too. But thats not what I want. For instance, ID is a mandatory field from the schema perspective. But when create mutation is auto-created, I want the resolver to auto-generate it and not force ID to be passed as an argument.

**Comment by yuth** [comment]
@pspanchal If you have a schema similar to 
```graphql
type Task @model(subscriptions:null)
{
  id: ID!
  title: String!
  description: String!
}
```
the generated createTask mutations input makes `id` an optional parameter. If the `id` is missing, the resolver automatically creates an unique id as shown below

```graphql
#... 
input CreateTaskInput {
  id: ID
  title: String!
  description: String!
}

type Mutation {
  createTask(input: CreateTaskInput!): Task
 # other mutation
}

```

**Comment by pspanchal** [comment]
Thanks @yuth. When I am using amplify mock it is forcing me to use the ID. Would this then be an issue just with the mock then?

**Comment by pspanchal** [comment]
Also, I may have some fields that are generated in the resolver based on the ID. Example groupsCanAccess, groupsCanEdit etc... So they are mandatory from the schema perspective. But from the mutation perspective, I want them to be not passed as an input. So how to achieve this too? In mock as well as regular graphQL API

**Comment by pspanchal** [comment]
> @pspanchal If you have a schema similar to
> 
> ```graphql
> type Task @model(subscriptions:null)
> {
>   id: ID!
>   title: String!
>   description: String!
> }
> ```
> 
> the generated createTask mutations input makes `id` an optional parameter. If the `id` is missing, the resolver automatically creates an unique id as shown below
> 
> ```graphql
> #... 
> input CreateTaskInput {
>   id: ID
>   title: String!
>   description: String!
> }
> 
> type Mutation {
>   createTask(input: CreateTaskInput!): Task
>  # other mutation
> }
> ```

Thanks @yuth it seems that if I mention @key annotation then I have to specify id in mutation. Is this a bug or a feature?
type Task @model(subscriptions:null)
  @key(fields: ["id"]) {
  id: ID!
  title: String!
  description: String!
}

**Comment by yuth** [comment]
@pspanchal its expected that user to pass the fields that are part pf `@key`. `@key` directive and recommended to be used only if you want to use different field as key or when you want to use  composite key.

We don't have plans to support making field declared as non null field in mutation
