### ISSUE TITLE
User "sub" in pre signup trigger

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#2219]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I am attempting to access the user sub in my pre signup trigger and it appears that it is only accessible if I choose "**Email address or phone number**" under _How do you want your end users to sign in?_ If I choose "**Username**" it is not available. 

It seems Cognito swaps in the sub for *event.userName* in my lambda function when using email/phon number auth.

I would ideally like users to be able to sign in with a username as well. Am I out of luck with accessing the sub in my pre signup lambda trigger?

**Comment by oste** [comment]
Sorry if this is not the right place for this type of question. I wasn't sure if this might reach the right person. I think it definitely makes sense to expose the sub in preSignup trigger. It seems like the right place to copy the user into a database and the sub allows for a good connection.

I do wish the sub was a uuid v1 instead of v4 so it can be timestamped but I highly doubt that will ever change :)

**Comment by UnleashedMind** [comment]
We will contact the Cognito service team for this, in the meanwhile, you can also create a post in their forum 
https://forums.aws.amazon.com/post!default.jspa?forumID=173

**Comment by UnleashedMind** [comment]
@oste 
We will inform the Cognito service team about your issue, will keep you updated.
You can so post a new thread in the Cognito forum
https://forums.aws.amazon.com/forum.jspa?forumID=173

**Comment by oste** [comment]
thanks @UnleashedMind I actually already cross posted there, here it is https://forums.aws.amazon.com/message.jspa?messageID=915060#915060

Thanks for keeping this one active. Hoping sub can be provided as a param for Pre Signup Triggers.

**Comment by kaustavghosh06** [comment]
@oste The Cognito team responded to your request at - https://forums.aws.amazon.com/message.jspa?messageID=915060#915060 and they mentioned that "Sub" is not supported at the moment and provided alternatives. Please correspond on that thread for further questions.
