### ISSUE TITLE
API GraphQL - Is it possible to partially update nested field?

### ISSUE THREAD

**Issue by thedgbrt** [aws-amplify/amplify-cli#2223]
** Which Category is your question related to? **
Api - GraphQL

** What AWS Services are you utilizing? **
DynamoDb

** Provide additional details e.g. code snippets **
I apologize in advance if this is a case of bad fundamental GraphQL understanding on my part, I'm pretty new to it. I digged for a couple hours on the web but didn't find a clear explanation for this.

I have a couple of models similar to these:
```graphql
type UserProfile @model {
  id: ID!,
  name: String!
  answers: Answers!
}

type Answers {
  _1: Int!
  _2: Int!
  _3: Int!
}
```

When creating a UserProfile, all fields from Answer are required, as I want them to be.
However when updating, I would like to be able to update only one answer. This doesn't seem to be possible.

Running this returns an error, saying that I also need to specify answer _2 and _3
```graphql
updateUserProfile(id: $id, answers: {_1: 8}) {
    answers {
      _1
    }
  }
```

To try and fix it, I did overwrite `UpdateUserProfileInput` and made sure all answers were optional, like this:
```graphql
type UpdateUserProfileInput {
  name: String
  answers: AnswersUpdateInput
}

type AnswersUpdateInput {
  _1: Int
  _2: Int
  _3: Int
}
```

However now, when I run the update query with only one answer, it erases the other one from the db, which I don't want.

So my question is: is it possible to update only one field of a nested type?

**Comment by UnleashedMind** [comment]
@thedgbrt 
No, it's not possible. 
You can either spread the answers out in the definition of the original UserProfile model, or create a Answers model and a connection between the UserProfile and the Answers model.

**Comment by thedgbrt** [comment]
@UnleashedMind thanks, that’s what it seemed like. I guess spreading out is a good idea. I hadn’t thought if it but it’s a simple way to solve it.
