### ISSUE TITLE
Feature request: Custom env variables in lambdas

### ISSUE THREAD

**Issue by thedgbrt** [aws-amplify/amplify-cli#2227]
The update mentioned in [684](https://github.com/aws-amplify/amplify-cli/issues/684#issuecomment-497212548) allows lambdas to access env vars generated by other amplify resources. However we still need a way to add custom environment variables to a project. I have a lambda that interacts with an external service via an API Key, I need a simple way to declare it through the amplify-cli.

I tried setting it manually from the lambda page on the AWS Console. However if I later update the function permissions to access different resources via amplify (and therefore have amplify attach new environment variables), it erases it on the next push.

### Possible api for it
```
amplify add variable
? variablename **MyCustomEnvVariable**
? value **TheValue**
```

and then optin from the lambda:
```
amplify function update
? Please select the lambda function you would want to update **mylambda**
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project?  **Yes**
? Select the category **variables**
? Select the variable name **MyCustomEnvVariable**
```

It would then become available in the lambda as process.env.MyCustomEnvVariable.

Secrets would need to be defined per `amplify env` environments. When switching environments, there could be a warning to mention that there are missing variables set up:
```
amplify env checkout staging
**warning: you haven't defined a value for MyCustomEnvVariable in this environment yet, make sure to call 'amplify variable update'***
Successfully initiated staging environment.
```

### Alternative considered
I considered AWS Secret manager as an alternative but:
1. it is not integrated into amplify, unnecessarily complexifying my workflow
2. it is overkill / expensive for simple API Keys that don't require advanced security

Please let me know if something like this is doable or not. If it can be considered by the amplify team, I can take responsibility for setting up an RFC and then speccing out the whole thing.

**Comment by diego-palmeira** [comment]
+1
I need a way to add env variables to my lambdas using amplify and per environment (dev, pre, pro)
Thank you

**Comment by jonoirwinrsa** [comment]
Not a built in solution but you can inject some values using bash + JQ in the CI

    jq '.Resources.LambdaFunction.Properties.Environment.Variables = .Resources.LambdaFunction.Properties.Environment.Variables + {"Your key": "your value"}' your-func-cloudformation-template.json > "$tmp" && mv "$tmp" your-func-cloudformation-template.json

**Comment by dtelaroli** [comment]
+1

**Comment by dansmith65** [comment]
+1

**Comment by StefanV85** [comment]
+1

**Comment by Lasim** [comment]
+1

**Comment by amuresia** [comment]
+1

**Comment by bastianbb** [comment]
+1

**Comment by chantlong** [comment]
+1

**Comment by Bulletninja** [comment]
+1

**Comment by mrgrue** [comment]
+1

**Comment by sw-yx** [comment]
there is a chance that @eliecer2000 might have worked on this functionality in https://github.com/aws-amplify/amplify-cli/issues/3961 - just cross tagging

**Comment by eliecer2000** [comment]
If I have it, but only to add variables in AWS, not to test the lambda function locally, I can share the repository to try to do a merge. regards

**Comment by eliecer2000** [comment]
https://github.com/eliecer2000/amplify-cli

**Comment by r0zar** [comment]
Where would the variables be stored? locally? will there be an option to pass them in at build time?

**Comment by flogy** [comment]
Would love to have this feature too. I think it is very important to be able to set environment variables for Lambda functions, e.g. when accessing a third-party API.

**Comment by marianolc** [comment]
+1 Would be this the place to store third party api credentials?

**Comment by freeform-ryan** [comment]
> Not a built in solution but you can inject some values using Bash + JQ in the CI
> 
> Add the ENV var to the Amplify console and run the following before building the backend:
> 
> ```
> jq '.Resources.LambdaFunction.Properties.Environment.Variables = .Resources.LambdaFunction.Properties.Environment.Variables + {"Your lambda env var key": $YOUR_ENV_KEY}' your-func-cloudformation-template.json > "$tmp" && mv "$tmp" your-func-cloudformation-template.json
> ```

How do you determine the path and name of `your-func-cloudformation-template.json`?

**Comment by jonoirwinrsa** [comment]
@freeform-ryan it's been a while since I've looked at this but I think its: 
```
amplify/backend/function/<function-name>/<function-name>-cloudformation-template.json
```

So you will need to know which lambda's you want to add the ENV vars to. Alternatively you could find all files that end with `-cloudformation-template.json` but that doesn't really sound like a nice solution - neither of these do really..

**Comment by freeform-ryan** [comment]
@jonoirwinrsa Thanks!

**Comment by mansdahlstrom1** [comment]
Dropped a solution for now here https://github.com/aws-amplify/amplify-cli/issues/684#issuecomment-738702705, maybe it could be helpful to find a solution as it would be great to have a more official solution

**Comment by raffibag** [comment]
I'd settle for a feature (or anti-feature?) that just doesn't overwrite the custom env values set from within the AWS console.

**Comment by mcrysler** [comment]
Any updates on this?

**Comment by dgills** [comment]
+1

**Comment by renebrandel** [comment]
Hi everyone! I wanted to let you know that we're actively working on this feature. 
We're aiming to bring environment variable & secrets support to the `function` category.

For environment variable support: you can use #7101 as our work-in-progress PR.
