### ISSUE TITLE
Error: Schema is not configured for subscriptions -> Not generating GraphQL API

### ISSUE THREAD

**Issue by Soek22** [aws-amplify/amplify-cli#2228]
**Describe the bug**
I am not able to get API.swift generated/updated when setting custom model operation names with 'null' subscriptions (removing subscriptions entirely).

**To Reproduce**
1. Define a 'schema.graphql' where I set custom named operations, plus 'subscriptions' to 'null'.

```
type Parent
  @model(
    queries:
    {
      get: "getParent",
      list: "listParents"
    },
    mutations:
    {
      create: "createParent",
      update: "updateParent",
      delete: "deleteParent"
    },
    subscriptions: null
  )
  @auth(rules: [{allow: owner, operations: [create, update, delete, read]}])
{
  id: ID!
  name: String!
  description: String
  childs: [Child] @connection(name: "ParentChild")
}


type Child
  @model(
    queries:
    {
      get: "getChild",
      list: "listChilds"
    },
    mutations:
    {
      create: "createChild",
      update: "updateChild",
      delete: "deleteChild"
    },
    subscriptions: null
  )
  @auth(rules: [{allow: owner, operations: [create, update, delete, read]}])
{
  id: ID!
  name: String!
  parent: Parent! @connection(name: "ParentChild")
  related: [Child]
}
```

2. Perform `$ amplify api push` (or `$ amplify codegen types`) 
3. I get 'Schema is not configured for subscriptions' error, and my API.swift doesn't get updated/generated. 
![Error](https://user-images.githubusercontent.com/2856396/64537045-6b0aef80-d31a-11e9-9f4c-38a79b7e8d92.png)

4. Schema on The AppSync Console gets updated correctly –without subscriptions, as expected–. `$ amplify codegen statements` is working fine.

**Expected behavior**
I expected to be able to configure custom schema with named operations and without subscriptions, getting the API generated by Codegen.

**Desktop (please complete the following information):**
 - OS: macOS 10.15 beta (19A546d)
 - amplify -v: 3.0.0

**Additional context**
- Project target & SDK: iOS (native, swift)

**Other comments**

I have also tried with the following syntax:
```
  @model(
    queries:
    {
      get: "getParent",
      list: "listParents"
    },
    mutations:
    {
      create: "createParent",
      update: "updateParent",
      delete: "deleteParent"
    },
    subscriptions: 
    {
      onCreate: null,
      onUpdate: null,
      onDelete: null
    }
  )
```
In this case I get the API.swift generated, but both local and cloud contain subscriptions. 'Null' is ignored.

**Comment by Soek22** [comment]
I get same error when using the following syntax:
`subscriptions: { level: OFF }`

**Comment by orr-levinger** [comment]
still hapenning Schema is not configured for subscriptions
