### ISSUE TITLE
Image Rekognition issue

### ISSUE THREAD

**Issue by MohdAbid1092** [aws-amplify/amplify-cli#2229]
when i compare two images in amazon console it wil give 85% similarity score but when i compare these image programatically it gives 16% similarity score (source image is person id and target image is person image)

but when i compare only person images it will give fine result most of the time
why this is happening i am unable to resolve it please help me

**Comment by UnleashedMind** [comment]
@MohdAbid1092 
When you said "compare these image programatically", did you mean you used the Amplify-CLI's prediction category to get those inconsistencies? or should we open an ticket for the Rekognition team?

**Comment by UnleashedMind** [comment]
Closing this issue due to lack of requester activity/response. Please feel free to comment on this thread if you’re still stuck on this issue.
