### ISSUE TITLE
Owner authed subscriptions not firing

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-cli#2233]
I'm unable to get subscriptions for any models with owner specified as `@auth` rule

E.g. this is a model with both owner and static group auth - the owner field is being set correctly on create:
```
type Voucher @model @searchable @versioned
   @key(fields: ["company","id"])
   @auth(rules: [
           { allow: owner },
           { allow: groups, groups: ["Admin", "CompanyManager", "LocationManager"] }
   ])
{
...
...
```

Client side subscription:

```
API.graphql(graphqlOperation(onCreateVoucher, {
            owner: authData.username,
        })).subscribe({
            next: (data) => {
                console.log('ON_CREATE_VOUCHER');
                dispatch({type: 'ON_CREATE_VOUCHER', data: data});
            },
            error: (e) => {
                    Sentry.captureException(e);
            }
        })
```

I've tested with different users - owner only, static group allowed and both owner and static group and the subscription never fires.   It only works if I add the `@model (subscriptions: { level: PUBLIC })` setting which is not ideal.

Is there something i'm missing?

amplify-cli: @3.0.0
nodejs: @10.16

**Comment by SwaySway** [comment]
@mdw2000 In your mutation response did you include the owner field as well?
```gql
mutation CreateVouch {
  createVoucher(input: {
    id: "someID"
    company: "someCompany"
    ...
  }) {
    ...
    owner
  }
}
```

**Comment by mdw2000** [comment]
@SwaySway - thank you I was not aware of the mutation requirement - that resolved the issue!
