### ISSUE TITLE
Expected Iterable, but did not find one for field [field name].

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2243]
**Describe the bug**
When running `amplify mock` a query returns the following error: 

`Expected Iterable, but did not find one for field User.accountHistory.`

User looks like this:

```
type AccountHistory {
  accountId: ID!
  viewedAt: AWSDateTime!
}

type User @model [...@keys etc] {
  id: ID!
  userName: String!
  firstName: String!
  lastName: String!
  accountHistory: [AccountHistory]
}
```

This correctly creates a List of Maps in DynamoDB which I can query without error when connected to the server. 

**To Reproduce**
1. Create a type with an Iterable (like tags on a blog post) that isn't a connection but a list
2. Create an entry in the database, the iterable field can be left null.
3. Run `amplify mock`
4. run query against mock
5. See error

**Expected behavior**
Ability to read from Iterables from `amplify mock`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox 70.0b4
 - Amplify 3.0.0

**Comment by yuth** [comment]
@aireater  Could you share the mutation you used to create the `User` and query used that produces this error.

Also do you have run subscriptions running against mock?

**Comment by aireater** [comment]
> @aireater Could you share the mutation you used to create the `User` and query used that produces this error.

```
mutation CreateAir {
  createUser(
    input: {
      userName: "aireater"
      firstName: "Air"
      lastName: "Eater"
    }
  ) {
    id
    userName
  }
}
```

I tried adding `accountHistory: null` then tried `accountHistory: []` to the mutation. Adding the empty list stopped the error. 

Any query would cause the error, even if the field wasn't being returned, for example: 

```
query ListUsers {
  listUsers {
    items {
      id
      userName
    }
  }
}
```

> Also do you have run subscriptions running against mock?

None.

**Comment by yuth** [comment]
Please feel free to re-open or comment if this is still reproducible
