### ISSUE TITLE
"invalid subcommand" when trying to add codegen to project

### ISSUE THREAD

**Issue by rayhaanq** [aws-amplify/amplify-cli#225]
When I use the `amplify add codegen` command, I get an `invalid subcommand` error. I've tried both `amplify add codegen` and `amplify codegen add` with no luck. I've added a graphql api using the cli and wanted to publish it. However, since I'm using Typescript, I think I'm supposed to use codegen because I was getting an error when trying to publish my app at the time of publishing:

```
Template format error: Unrecognized resource types: [AWS::AppSync::GraphQLApi, AWS::AppSync::Resolver, AWS::AppSync::DataSource, AWS::AppSync::GraphQLSchema, AWS::AppSync::ApiKey]
```

**To Reproduce**
1. Go to project root
2. run `amplify codegen add`

 - Amplify CLI Version: 0.1.24
 - OS: Windows 10

**Comment by kaustavghosh06** [comment]
@rayhaanq  Which region are you trying to deploy? The above-mentioned error pops up when trying to publish to a region which doesn't yet have support for AppSync.

**Comment by kaustavghosh06** [comment]
Also, if you're using v 0.1.24, just `amplify codegen` command should work after you've deployed your app.

**Comment by rayhaanq** [comment]
oh okay, thanks for that. So most of my backend is in `eu-west-2`. Is there any way to change just amplify to `eu-west-1`?

**Comment by kaustavghosh06** [comment]
Yup. you can create a new AWS profile using the `amplify configure` command and select from one of the supported regions:
```
  'us-east-1': 'US East (N. Virginia)',
  'us-east-2': 'US East (Ohio)',
  'us-west-2': 'US West (Oregon)',
  'eu-west-1': 'EU (Ireland)',
  'eu-central-1': 'EU (Frankfurt)',
  'ap-northeast-1': 'Asia Pacific (Tokyo)',
  'ap-southeast-1': 'Asia Pacific (Singapore)',
  'ap-southeast-2': 'Asia Pacific (Sydney)',
  'ap-south-1': 'Asia Pacific (Mumbai)',
```
Then you can run `amplify configure project` at the root of your project and choose the newly created profile (in the step above) for your project.

**Comment by rayhaanq** [comment]
ah, so there's no way to change the region only for one specific service? I tried updating the cloudformation-template but it looks like that's auto generated too...

**Comment by rayhaanq** [comment]
sorry, I'll rephrase my question. Is it possible to have auth and hosting in `eu-west-2` and only api in `eu-west-1`?

**Comment by kaustavghosh06** [comment]
Yeah, we do not support multi-region support for a project.
The services added to the project would belong to one region i.e the parent Cloudformation stack is deployed to one specific region. (one of the above-mentioned regions)
