### ISSUE TITLE
amplify add codegen gives error

### ISSUE THREAD

**Issue by lahirian** [aws-amplify/amplify-cli#226]
**Describe the bug**
I am following the steps outlined in the blog https://aws.amazon.com/blogs/mobile/aws-appsync-releases-new-guided-api-builder/ . However step 8 gives me the following error:

bash-3.2$ amplify add codegen --apiId XXXXXXXXXXXXXX
There are no Code Gen APIs available.
 Add by running amplify codegen add

If I try to put "add" after codegen I get same error.
bash-3.2$ amplify codegen add --apiId XXXXXXXXXXXXXX
There are no Code Gen APIs available.
 Add by running amplify codegen add

Either this is a bug or the documentation is not clear.

**Comment by mikeparisstuff** [comment]
Can you please provide the version of amplify-cli that you are using? Also are you replacing the XXX.. with the real id of your API?

**Comment by kaustavghosh06** [comment]
Please use the latest version of the CLI -> 0.1.24 for the cod gen function you’re trying to implement.
