### ISSUE TITLE
Storage trigger fails when looking for object in protected bucket

### ISSUE THREAD

**Issue by jkahn117** [aws-amplify/amplify-cli#2269]
**Describe the bug**

Storage Trigger function failed on an object uploaded to a protected bucket. Object keys in protected buckets contain a colon (:) character as part of the Cognito ID. The event arriving at Lambda contained the key with the colon encoded as "%3A", this caused my function to fail on `GetObject` because the expected object did not exist. Fix was to replace the encoded character.

For example, the event contained a key like the following: "protected/us-east-1%3Af1234-5162-4d60-8453-7ccf90cbfd56/images/f1906a64-d3b8-4648-b124-21efecc32cce.jpeg" but should have been "protected/us-east-1:f2051234-5162-4d60-8453-7ccf90cbfd56/images/f1906a64-d3b8-4648-b124-21efecc32cce.jpeg".

**To Reproduce**

1. Add Storage with Trigger
2. Create Lambda function that writes incoming event to CloudWatch
3. Storage.put(key, file, { level: 'protected' })
4. Review event data

**Expected behavior**

Function should not fail due to object not being found; however, this is not an issue specific to Amplify. Perhaps a note in documentation when using protected or private storage would be most appropriate for now.

**Comment by jkahn117** [comment]
@kaustavghosh06 Amplify is not involved to what I can tell. File lands in S3 and it generates the event that is pushed to Lambda.

**Comment by tgjorgoski** [comment]
Copied from somewhere in AWS docs, probably can be added to other examples/documentation, of how to actually get the name of the file which you can then pass to s3 API:

const fileKey = decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, " "));

**Comment by kaustavghosh06** [comment]
@jkahn117 Yeah, unfortunately this is not Amplify related and you can get past this by using the decodeURIComponent() function in your lambda function as mentioned by @tgjorgoski
