### ISSUE TITLE
Option to allow usage of SSM in Lambda function

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#2278]
**Describe the solution you'd like**
SSM is a good way to keep keys for external services safe. At this time, it's necessary to manually modify a Lambda functions execution role in order to read SSM key/values.

Adding an SSM option in the CLI which attaches the correct policy would be nice.

With the recently released multi auth, which makes it possible to do GraphQL operations from Lambda without "workarounds", and this added, I would no longer have to do any significant manual "tweaks" to make our setup run. I guess I would not be the only one.

**Describe alternatives you've considered**
We are manually adding the policy to enable SSM in each Lambda function.

**Comment by josefaidt** [comment]
Hey @houmark :wave: thank for your raising this request! This feature has been released with [Amplify CLI v5.1.0](https://github.com/aws-amplify/amplify-cli/releases/tag/v5.1.0) which has a corresponding [blog post](https://aws.amazon.com/blogs/mobile/configure-environment-variables-and-secrets-for-your-lambda-functions-with-amplify-cli/) demonstrating the new functionality. More information can be found on our documentation site:

- Environment variables -- https://docs.amplify.aws/cli/function/env-vars
- Accessing secrets -- https://docs.amplify.aws/cli/function/secrets

Closing due to release 🙂

**Comment by houmark** [comment]
Dreams do come true (they just take longer than you hope)!

**Comment by houmark** [comment]
@josefaidt Update here. While I appreciate this is now added to Amplify, unless I missed something in initial testing, there seems to be a major flaw in the design and implementation of the secrets feature; **Secrets are stored _per_ function**.

We have many functions currently using the same secret(s) for example API keys for external platforms. With the current implementation, we would have to add this secret and duplicate it for every single function. When a secret is updated we have to not only go through our source code to be sure we find all of the uses and update every single function with the new value. That's not really optimal. Being able to share a secret globally (preferred) or at least add secrets to layers so we could load the layer and then the secrets there, would be much better.

As is, this feature is pretty useless for a majority of the secrets we store, because we will go from a non-official single store situation per secret to redundantly stored secrets and that opens for a forgotten secret being updated down the line.

My suggestion for a backward-compatible option for this would be to add another step to adding a secret:
"Would you like this secret to be available to other functions?"

If the user says "Yes" then it name and create the secret in such a way it can be retrieved by any function and any function could list "global secrets" with a listing feature inside the secrets management in the CLI. It will be backward compatible because all secrets created since release of this feature will be "local" and this function only (but Amplify users can go back and remove those and re-add them as global if they wish).

Alternatively allow layers to have secrets added so we can go function -> layer -> secret and that way only store the secret one place.

For us, having a non-standard setup where we manually give functions access to SSM in IAM in order to load secrets we have typed in in the AWS Console UI beats the Amplify implementation, and such, we will not be using this feature until improved to avoid redundancy.

Looking forward to your feedback.

**Comment by houmark** [comment]
Having thought about this a bit more, I am not sure adding global secrets is the perfect solution here because layers cannot access Amplify CLI-created secrets at all at this time? We are just starting to test out layers and since layers cannot create secrets using the CLI, the current implementation is very limited, because you won't be able to create a layer for API related features to a specific external platform (a very common use case I would think) and then use secrets created in the CLI to access that external platform.

I'm really hoping I missed something obvious here, otherwise, it seems to me that this feature has been implemented without considering one of the most requested and recently released features on the platform.

**Comment by renebrandel** [comment]
@houmark - thanks for the detailed feedback. I'm curious what would be the perfect set up for you?

> For us, having a non-standard setup where we manually give functions access to SSM in IAM in order to load secrets we have typed in in the AWS Console UI beats the Amplify implementation, and such, we will not be using this feature until improved to avoid redundancy.

For this, we are looking into enabling customers to more easily provide functions with custom policies to access existing resources. Maybe that's the way to go? (RFC coming soon)

For the "standard" set up, we've seen that most customers usually have "one function <-> many secrets" setup. Our intent is to expand this feature in the future to enable secret sharing. If so, would you prefer to have it enabled via:
1. layers, or
2. your other suggestion on: `"Would you like this secret to be available to other functions?"`, or
3. have the new function give an option of `"access an existing secret from another function?"`

Looking forward to your feedback.

**Comment by houmark** [comment]
Thanks for the feedback @renebrandel.

Considering this feature was released as is, I think options 1 and 3 combined are what makes the most sense. Meaning you can add to a layer and load an existing secret from any function if you like to. That way existing secrets are globalized by default and can be used once this feature improvement is released. If layers do not have any way to add secrets, then we would struggle with refactoring our existing codebase to use layers, something we have been eagerly waiting to start with for the longest time. We would attempt to use our manually added policy to the layer if possible (did not yet test that).

I guess Amplify will have to parse all functions JSON files to list all existing secrets in order to show a list of secrets available. It's important that it's not going straight to the Parameter Store and listing account secrets there because you could by accident delete secrets that have been created manually for whatever reason.

I really like the feature for just giving a function IAM access to the service, so that secrets can be managed outside of Amplify as this also makes us able to get rid of our manually added policy and have a setup that's cleaner, while stile using the same secrets we created years ago. And this should also apply to layers so that you can give a layer IAM access to external services.

I hope this is the feedback you were looking for — if not let me know if you want anything elaborated.

**Comment by renebrandel** [comment]
hi @houmark - as promised, here's the RFC to enable additional policies, would love to get your feedback on this: https://github.com/aws-amplify/amplify-cli/issues/7792
