### ISSUE TITLE
Amplify mock cannot find function

### ISSUE THREAD

**Issue by set321go** [aws-amplify/amplify-cli#2280]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I had an amplify project with appsync, function & storage. I upgraded to amplify 3 and i tried to use `amplify mock` when it tries to start it complains that it cannot find the function `Failed to start API Mock endpoint Error: Lambda function command-processor does not exist in your project.`. The function does exist because when i run `amplify push` it is in the output
```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Function | bookings      | Update    | awscloudformation |
| Api      | bookings      | No Change | awscloudformation |
| Storage  | eventstore    | No Change | awscloudformation |
```
and when sending a request to appsync the lambda is invoked (its broken but it gets invoked).

**To Reproduce**
I don't know what the prereq is to get into this state but once you are
1. run `amplify mock`

**Expected behavior**
Mock instance is started successfully

Is there any way for me to get amplify cli to log more details?

**Comment by yuth** [comment]
Could you share the schema snippet where you're using the function.

**Comment by set321go** [comment]
schema extract
```
type Mutation {
  createCommand(command: Command!): Boolean @function(name: "command-processor-${env}")
}
```

extract from cloud formation template in function directory
```
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
				"aws:asset:path": "./src",
				"aws:asset:property": "Code"
			},
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"command-processor",
						{
							"Fn::Join": [
								"",
								[
									"command-processor",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"REGION": {
							"Ref": "AWS::Region"
						},
						"API_BOOKINGS_GRAPHQLAPIIDOUTPUT": {
							"Ref": "apibookingsGraphQLAPIIdOutput"
						},
						"API_BOOKINGS_GRAPHQLAPIENDPOINTOUTPUT": {
							"Ref": "apibookingsGraphQLAPIEndpointOutput"
						},
						"STORAGE_EVENTSTORE_NAME": {
							"Ref": "storageeventstoreName"
						},
						"STORAGE_EVENTSTORE_ARN": {
							"Ref": "storageeventstoreArn"
						}
					}
				},
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs10.x",
				"Timeout": "25",
```

one thing i did notice is that the directory name and the template file do not match the name of the lambda defined in the resources section. dir `backend/function/bookings` and `bookings-cloudformation-template.json` not sure if thats important.

**Comment by pharcosyle** [comment]
Workaround: it works if you use the lambda resource name instead of the lambda name in your function directive. So if you set up your lambda with the amplify cli like this:

? Provide a friendly name for your resource to be used as a label for this category in the project: myfunclabel
? Provide the AWS Lambda function name: myfunc
...

Then the directive ```@function(name: "myfunclabel-${env}"``` will work when you run mock api. You'll have to change it back to ```@function(name: "myfunc-${env}"``` when you push though.
