### ISSUE TITLE
Cannot read property 'defaultAuthentication' of undefined

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#2283]
I just updated to the most recent version of the cli today (13 sept) and now when I try to run amplify push, It gives me this error:

> Cannot read property 'defaultAuthentication' of undefined

There is nothing I can do to change that, and I have absolutely no idea why it would be giving that error.

I have my current environment working fine, and then did the following steps:
- amplify env add
This created my environment from my current one.

I then ran: amplify push, and was given that error.

**Comment by houmark** [comment]
Possibly fixed or related to the bug(s) fixed in #2276

**Comment by kaustavghosh06** [comment]
Please take a look at https://github.com/aws-amplify/amplify-cli/issues/2260 for workaround.

**Comment by kaustavghosh06** [comment]
@oliverandersencox and @houmark This issue is fixed and merged and pending release. Also, please take a look at the workaround mentioned above and let me know if you're still blocked.

**Comment by houmark** [comment]
Will you rush out a new release with this and the other issue that seems to have a PR already to avoid more people getting stuck in updating over the weekend? Also, release notes are still not available in the changelog for 3.2.0. I thought you'd work towards improving that. Having no release notes days after release does not seem to make good on that promise?

**Comment by houmark** [comment]
@kaustavghosh06 I believe this is the "master" changelog to keep an eye on here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/CHANGELOG.md

**Comment by Burry** [comment]
I'm glad that a fix for this issue is pending release, but it is very disappointing to see Amplify continue to release breaking changes without any changelog updates. It has been a tremendous burden on our team to take such a defensive approach to our tools, having to anticipate that things could break in mysterious, undocumented ways at any time.
