### ISSUE TITLE
Error when updating amplify-cli

### ISSUE THREAD

**Issue by kesteinbakk** [aws-amplify/amplify-cli#2288]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Error after upgrading the cli

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
I had a graphQl schema working fine, recently pushed with no errors. To verify I added a field before the update and pushed it using amplify push. Everything ok. I updated the amplify-cli (because I would like to try multiple authentications).  I removed the test field in the schema and got the following error on push: 

> ✖ An error occurred when pushing the resources to the cloud
> 
> Cannot read property 'defaultAuthentication' of undefined
> An error occured during the push operation: Cannot read property 'defaultAuthentication' of undefined

Do I have to change anything on the backend in order to use the newest version of the amp cli?

**Comment by ChristopheBougere** [comment]
Same issue for me, just updated to 3.2.0

**Comment by heitorlessa** [comment]
As per https://github.com/aws-amplify/amplify-cli/issues/2260#issuecomment-530926035, running `amplify api update` and accepting the options I used unblocked my CI.
