### ISSUE TITLE
Independently use amplify-graphql-types-generator?

### ISSUE THREAD

**Issue by jwnx** [aws-amplify/amplify-cli#2292]
** Which Category is your question related to? **
amplify-graphql-types-generator

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **

Hello everyone,

I'm trying to use the `amplify-graphql-types-generator` subpackage as a way to generate typescript classes from my graphql schemas. Then, import those schemas as objects later on aws cdk and magically deploy it all to aws. What I tried is:

```
yarn run amplify-graphql-types-generator --schema "users.graphql"
```
and...

```
yarn run amplify-graphql-types-generator users.graphql --schema "users.graphql"
```
Both gave me errors.

There is no readme for `amplify-graphql-types-generator`, so I'm not sure what it wants from me. Is possible to use it as I described?

Thanks,

**Comment by alexmcmanus** [comment]
`yarn run` will only run something that _you_ define in your `package.json` file. See https://yarnpkg.com/lang/en/docs/cli/run/. 

There is no standalone CLI for the generator. However, you can call the generator via code - either write your own CLI, or actually integrate it into your CDK source. It is undocumented however, and you're going to have to browse the source code to work out how to use it. If you are using Typescript, see also #2451. 

I've been exploring this and I'm still working out the details. To give you a starting point, this script will log the schema using a cut-down set of transformers:
```js
const fs = require('fs')
const GraphQLTransform = require('graphql-transformer-core').default
const DynamoDBModelTransformer = require('graphql-dynamodb-transformer').default
const ModelAuthTransformer = require('graphql-auth-transformer').default
const ModelConnectionTransformer = require('graphql-connection-transformer').default
const VersionedModelTransformer = require('graphql-versioned-transformer').default

const transformers = [
  new DynamoDBModelTransformer(),
  new VersionedModelTransformer(),
  new ModelConnectionTransformer(),
  new ModelAuthTransformer()
]

const transformer = new GraphQLTransform({
  transformers
})

const deploymentResources = transformer.transform(
  fs.readFileSync('schema.graphql').toString()
)
console.log('deploymentResources: ', Object.keys(deploymentResources))
console.log('Schema:\n', deploymentResources.schema)
```

See also https://github.com/aws-amplify/amplify-cli/blob/bf5b09ecbb2e18db2922069bcdea27b15681ed84/packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js

**Comment by kaustavghosh06** [comment]
@jwnx Why not just use the `amplify codegen types` command instead of yarn in your script? You can list amplify as a dev dependency of your project, just like yarn?

**Comment by yuth** [comment]
> There is no readme for `amplify-graphql-types-generator`, so I'm not sure what it wants from me. Is possible to use it as I described?

`amplify-graphql-types-generator  --help` shows all the possible options for this command.

The `amplify-graphql-types-generator` needs a schema, which is entire schema for your GraphQL API. This should include All type declaration and possible query, mutation and subscription. It also needs a list of files that include the statements to which you want to generate the types (this is subset of schema and the query you want to use in your application). So the command should look like

```shell
amplify-graphql-types-generator <appspecific-query.graphql> --schema <path-to-schema/schema.graphql> --target ts
```
