### ISSUE TITLE
Bug when using add-graphql-datasource on tables with reserved keywords as name.

### ISSUE THREAD

**Issue by changdaniel** [aws-amplify/amplify-cli#2293]
**Describe the bug**

If you use amplify api add-graphql-datasource on a database with a table named with a reserved keyword, like "Group" or "Select" or in my case "Order," the command will fail with the error message "BadRequestException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1." I created the table Order with CREATE TABLE `Order` and this seems to make the command fail.

**To Reproduce**
1. Create aurora serverless database
2. Create a table with a reserved keyword name using delimiters.
3. amplify api add-graphql-datasource

**Expected behavior**

A schema generated without failing.

**Desktop (please complete the following information):**
 - Pop!_OS 18.10
 - Newest amplify cli version

**Comment by vic-blt** [comment]
I have the same issue with a table named 'order'.
