### ISSUE TITLE
Best way to share code between lambda functions

### ISSUE THREAD

**Issue by Jkap7788** [aws-amplify/amplify-cli#2295]
** Which Category is your question related to? **
Functions

** What AWS Services are you utilizing? **
Lambda, S3

Hi, I was just wondering what the best way is to share code between lambda functions in Amplify.
I am not sharing an entire library of code, more like some useful utility functions that house common business logic. 
I am aware of lambda layers but think they are overkill for this kind of use case.

I would love to be able to create a directory in the repo that contains common code and then 'require' that code in the lambda functions.
Is there any way to require code outside the scope of the lambda function src directory and bundle that into the lambda code before deploying to the cloud?

Thanks a lot!

**Comment by attilah** [comment]
@Jkap7788 you've the some choices:
- Copy the shared file as part of your build process
- Use a monorepo with Lerna and consume the shared pieces as a package
- Use lambda layers

Lambda layers is the one that CLI will support and it is tracked in #1696, so closing this as a duplicate.
