### ISSUE TITLE
'amplify init' does not generate aws-exports.js

### ISSUE THREAD

**Issue by kwkecw** [aws-amplify/amplify-cli#23]
Do you want to request a feature or report a bug? Bug

What is the current behavior?
Following [AWS Amplify Getting started](https://aws-amplify.github.io/amplify-js/media/quick_start?platform=react-native) guide for react-native, after step 4 which is `amplify init`, this command completes successfully without generating an aws-exports.js file in the source folder nor anywhere.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
Expect aws-exports.js to be generated.

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
Amplify CLI 0.1.14
Node v10.2.0

Previously worked with awsmobile init

Also, noticed that if I run `amplify configure project` while switching type of app [android, ios, javascript] then I do successfully get an aws-exports.js in my source folder. But the content is rather lacking.

**Comment by kaustavghosh06** [comment]
@kwkecw We'll have the docs updated. Thanks!

**Comment by tetreault** [comment]
Did this ever get updated in the docs? The react native docs jump right into code referencing aws-exports, without mentioning the need to add storage and run publish first.

**Comment by matwerber1** [comment]
Hi - I'm still not getting aws-exports.js. Steps are - 

```
 $ amplify init             (defaults for react, vs code editor)
 $ amplify add auth   (accept defaults)
 $ amplify push 
```

I am intentionally leaving out ```add hosting``` (and therefore ```amplify publish```) because I want to test locally without creating a new S3 bucket. I may choose to manually edit the configs to use an existing bucket at a later time.

**Comment by appsols-dev** [comment]
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment]
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment]
> I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, eg: D:/ or C:/.
> I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

You can update it using "amplify update project"

**Comment by nmontana42** [comment]
> I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, eg: D:/ or C:/.
> I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

Hey I am having the same issue and don't know how to update it. Can you run me through changing the path
