### ISSUE TITLE
Errors with $util.time when mocking locally

### ISSUE THREAD

**Issue by chrisco255** [aws-amplify/amplify-cli#2300]
**Describe the bug**
Noticed two errors when working with the `$util.time` utility functions. 
1. `$util.time.nowFormatted("yyyy-MM-dd")` is giving minutes instead of the month for the MM value. I dug into the source code a bit, and it looks like the Node.js time library that is being used for this has slightly different formatting rules than AppSync's. In `dateformat` lib, MM represents minutes. In AppSync, `mm` is supposed to represent minutes. Not sure which one is the correct UTC/ISO implementation, but this causes some confusion when testing locally.

2. `$util.time.epochMilliSecondsToISO8601()` does not work locally. In this case it will throw an error: `"Cannot read property 'first_line' of undefined"`

**To Reproduce**
1. Edit any VTL template.
2. Add a line including the above time utilities and store in a variable.
3. "Log" the variable out with `$util.error()`
4. Run `amplify mock` and hit the resolver you edited

**Expected behavior**
Time utils should work locally

**Comment by attilah** [comment]
@chrisco255 thanks for reporting the issue, it seems that formatting is different as you described, we'll look into it.
