### ISSUE TITLE
Confused on best way to share backend code 

### ISSUE THREAD

**Issue by gxedwards** [aws-amplify/amplify-cli#233]
Creating a new amplify project is very nice with the new CLI but I have found both sharing with team mates on the same project and also putting on another machine a very frustrating experience.

I have seen the varied issues (211, 185, 38) on various tricks but I have come to a crashing standstill. 

Does anybody happen to have a step by step on how to 

1) Pulling down an existing code fragment and firing up their own version of the code
or 
2) Successfully re initializing an existing project on a different machine (just to make it harder one machine is windows and the other is linux). This would mirror what would happen if two people were sharing an environment too.

I have updated my .gitignore based on the discussions. Right now though I don't see how I can clone an existing project , the existing backend code is not being recognized and the cloud formation files do contain a lot of references to the original build. Feels like I am going around in circles

Perhaps I am being dense. I really like the concept of what this does, but right now it feels like outside of an individual  working on their own there are too many hoops.

Right now on a clean install you seem to have to do an init (otherwise it says you don't have an amplify project), then amplify configure project but I seem to have to rerun all my add commands manually which kind of defeats the purpose it feels.

Enlightenment would be appreciated. Cheers

**Comment by mwarger** [comment]
I'm curious about this as well - I have my cloudformation code checked in, but it seems necessary to be able to check it all out on another machine and run it.  This way, I could run `amplify init` and it would pick up the configuration I already have and push that out (even if it's a totally new AWS account for testing, or if I had another dev spin up a project in a separate account).  I would like for it to just use the cloudformation templates that are already present to replicate the environment.

Is re-running `amplify add ...` for all the services and selecting all the same options really the way to do this?  

Is there anything currently in the works to mitigate this problem?  If there is, I'd love to know if it's possible to lend any assistance, as I'd love for this feature to exist.

Thanks for all the hard work on this.

**Comment by yuth** [comment]
> I have updated my .gitignore based on the discussions. Right now though I don't see how I can clone an existing project , the existing backend code is not being recognized and the cloud formation files do contain a lot of references to the original build. Feels like I am going around in circles

Could you please clarify the following
- What entries are added to `.gitignore`?
- What commands  did you run after cloning your project?
- Are there specific errors that you get?

**Comment by mriccid** [comment]
The discussion here is helpful: https://github.com/aws-amplify/amplify-cli/issues/104

I was able to clone an existing project and get it working by doing the following:

1. Run `amplify configure project`. This will fix the paths in `amplify/.config/project-config` (although I did have to fix an absolute path for the  `frontendHandler.javascript` manually, not sure why this wasn't fixed by `configure project`)
2. Add `/amplify/.config` to the `.gitignore` file. When I cloned the project, that folder wasn't ignored
3. Revert the changes to `amplify/#current-cloud-backend/amplify-meta.json` and `amplify/backend/amplify-meta.json` as some of the timestamps were modified after running `configure project`. 

You should now be able to run commands like `amplify publish`

**Comment by kaustavghosh06** [comment]
@mriccid Were you able to publish to a different AWS account? or was it the same AWS backend?

**Comment by mriccid** [comment]
@kaustavghosh06 this was publishing to the same AWS account, using the resources already defined in config files that had been committed. Another developer had published the project from their machine, so the resources existed. The problems seemed to arise only from issuew with `project-config.json`

**Comment by mwarger** [comment]
I was not able to get the project to recognize all my amplify parts.  It recognized the API, and flagged it as an update, without recognizing any of the others (S3, Auth, Hosting).  I made sure that my `project-config.json` was pointing to the correct locations.

**Comment by kaustavghosh06** [comment]
@gxedwards @mriccid @mwarger 

We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backward from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by kaustavghosh06** [comment]
Based on all of your feedback, we’ve released a beta version of the CLI (npm install -g @aws-amplify/cli@multienv)  to support multiple environments, team workflows and integrate with your CI/CD flows.
Please check out this documentation for more details - https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Also, as a part of our feedback mechanism, we’ve opened up another [GitHub issue](https://github.com/aws-amplify/amplify-cli/issues/508),  to track feedback from everyone, iterate on this beta version and then merge it to master.  We'll close this issue and track feedback in #508. Looking forward to your feedback on this release.

**Comment by kaustavghosh06** [comment]
Closing this issue since this problem is solved with the release of the multienv feature-set mentioned above.
