### ISSUE TITLE
AppSync Resolver multiline string

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#2331]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
I have a simple AppSync request resolver like this, I am finding it hard to maintain long MySQL queries in a single line. I wasn't able to find any solutions for a multiline string in VTL. Is there a standard for handling multiline strings in VTL?

```
{
  "version": "2018-05-29",
  "statements": ["SELECT this.Post as that, that.Post as this, this.Tag as thatTag, that.Tag as thisTag FROM POST JOIN TAG ON TAG.Post_id = POST.id"]
}
```

**Comment by attilah** [comment]
@oste I think your best option is to move the select statement out to a variable, since with VTL you can have multiline strings in ```#set```.

```
#set ($statement = "
SELECT
    this.Post as that
FROM
    POST
")

and then reference the variable from your JSON construct at the second half of the template.

I'm closing the issue, but feel free to reopen it if something new comes up.

**Comment by oste** [comment]
@attilah that was one of the first things I tried that I hoped would work. It is giving an error. 

```
{
  "data": {
    "listPosts": null
  },
  "errors": [
    {
      "path": [
        "listPosts"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unable to parse the JSON document: 'Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: (String)\"\n{\n  \"version\": \"2018-05-29\",\n  \"statements\": [\"\n  SELECT\n
```

**Comment by oste** [comment]
I tried that. I was missing `$util.escapeJavascript`.

This works:

```
#set ($statement = "
SELECT
    this.Post as that
FROM
    POST
")

{
  "version": "2018-05-29",
  "statements": ["$util.escapeJavaScript($statement)"]
}
```

Thanks.

**Comment by Dellybro** [comment]
This doesn't seem to work for me, even when i use escapeJavasScript any ideas? I get unrecognized escape character

**Comment by oakstreetrec** [comment]
Agreed, even with util.escapeJavaScript, I still get unrecognized escape character

**Comment by oakstreetrec** [comment]
Dellybro - this worked for me:

{
    "version": "2018-05-29",
    "statements": [
        $util.toJson($multiline_sql)
    ]
}

**Comment by Dellybro** [comment]
> Dellybro - this worked for me:
> 
> ```
> {
>     "version": "2018-05-29",
>     "statements": [
>         $util.toJson($multiline_sql)
>     ]
> }
> ```

Thank you thank you thank you
