### ISSUE TITLE
Stack Mapping Broken by recent CLI Upgrade

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#2335]
**Describe the bug**
CloudFormation has a limit of 200 Resources in a stack and my ConnectionStack.json file has exactly 200 Resources in it. I needed to add more connections so created a transform.conf.json file to direct resources to an overflow (ie. ConnectionStack2.json). This worked perfectly - compiled and pushed perfectly with the resources defined in transform.conf.json into ConnectionStack2.json.

However, I upgraded my amplify cli about a week ago and it stopped working. Now if I add any more resources to transform.conf.json this file is overwritten with the previous version and it has a "Version" label appended to the bottom of the file.

**To Reproduce**
In a version prior to 3.2.0 I had the following transform.conf.json

{
    "StackMapping": {
        "AssetVisitAttributecrowdResultsResolver": "ConnectionStack2",
        "CrowdResultscrowdSourcingJobResolver": "ConnectionStack2",
        "CrowdResultsuomResolver": "ConnectionStack2"
      }
}

This compiled and deployed correctly with these resources in the ConnectionStack2.json file.

Now after upgrading to 3.2.0 about a week ago, I edit the transform.conf.json as follows:

{
    "StackMapping": {
        "AssetVisitAttributecrowdResultsResolver": "ConnectionStack2",
        "CrowdResultscrowdSourcingJobResolver": "ConnectionStack2",
        "CrowdResultsuomResolver": "ConnectionStack2",
        "FieldListCrowdResults": "ConnectionStack2",
        "FieldListcrowdResultsResolver": "ConnectionStack2",
        "CrowdResultsfieldListResolver": "ConnectionStack2"
       }
}

Prior to amplify 3.2.0 this would have added 6 resources to ConnectionStack2. But what happens now is that my transform.conf.json reverts to the previous version with a version label as follows:

{
    "StackMapping": {
        "AssetVisitAttributecrowdResultsResolver": "ConnectionStack2",
        "CrowdResultscrowdSourcingJobResolver": "ConnectionStack2",
        "CrowdResultsuomResolver": "ConnectionStack2"
      },
     "Version": 4
}

And I end up with 203 resources in ConnectionStack.json and 3 resources in ConnectionStack2.json

**Expected behavior**
I expect 200 resources in ConnectionStack.json and 6 resources in ConnectionStack2.json and for them to be successfully deployed with push.

**Additional context**
The @connection directive in Amplify Transform is great - but, it generates 3 resources for each one. So not being able to do this stack mapping means I'm limited in my ability to define my data model.

**Comment by sacrampton** [comment]
Just upgraded to amplify 3.8.0 and this issue still exists. It happens when I do the compile.

**Comment by kaustavghosh06** [comment]
We’re still investigating the stack mapping issue and that’s why we haven’t commented or closed this issue. With 3.8.0 we’ve fixed the ‘no-gql-override’ issue which you’d another GitHub issue opened for.

**Comment by sacrampton** [comment]
Understood.

Further to this, previous versions of the amplify api gql-compile would warn if the number of resources in a stack (ConnectionStack.json specifically) was greater than 200. The current 3.8.0 version (and the previous 3.7.0 version) give a successful compilation message with no warning that the number of resources exceeds the limit. You only learn this when trying to push to CloudFormation.

Previous versions would warn you when you exceed the 200 resource limit and would advise you to resolve the issue through the transform.conf.json file for stack mapping.

**Comment by sacrampton** [comment]
I found a work around to get this to deploy successfully - it is somewhat convoluted, but it worked.

Firstly, for a number of reasons I always separate compile and push. So before I execute the compile I copy the new transform.conf.json (with version tag) into the #current-cloud-backend folder and into the backend folder. The new transform.conf.json shown below.

{
"StackMapping": {
"AssetVisitAttributecrowdResultsResolver": "ConnectionStack2",
"CrowdResultscrowdSourcingJobResolver": "ConnectionStack2",
"CrowdResultsuomResolver": "ConnectionStack2",
"FieldListCrowdResults": "ConnectionStack2",
"FieldListcrowdResultsResolver": "ConnectionStack2",
"CrowdResultsfieldListResolver": "ConnectionStack2"
},
"Version": 4
}

I then perform the amplify api gql-compile command. Then I copy the original transform.conf.json back into the #current-cloud-backend folder and the backend folder. Then I do the amplify push --no-gql-override --yes and it successfully deploys.

**Comment by attilah** [comment]
@sacrampton to help me better understand the repro and workaround steps, separate it to steps, please add your corrections in a comment.

1. When you've the failure:
- there is no transform,conf.json in your #current-cloud-backend folder
- api gql-compile
- push with no compile

result: Failure

2. When it works with your workaround
- there is no transform,conf.json in your #current-cloud-backend folder
- api gql-compile
- copy the generated transform.conf.json into #current-cloud-backend folder
- api gql-compile again
- ??? here is what I don't know what is the "original transform.conf.json" file?
- push with no compile

I'd appreciate if you could send us the transform.conf.json files in the various stages of your workaround to amplify-cli@amazon.com

**Comment by attilah** [comment]
@sacrampton
>Previous versions would warn you when you exceed the 200 resource limit and would advise you to resolve the issue through the transform.conf.json file for stack mapping.

I checked the code and we still apply rules for this validation, but my guess is that because your workaround copies the transform.conf.js file so there will be no actual difference in the mapping, we'll not process the rules, because the rule processing is happening over the diffs in the deployed and "to be deployed" stacks.

**Comment by sacrampton** [comment]
@attilah here are the steps I took.

I have emailed you transform.conf1.json, transform2.conf.json and transform3.conf.json (obviously all named transform.conf.json in their various folders).

1 What happened when I had a failure
* I put tranform.conf2.json in the backend folder
* api gql-compile
* My transform.conf2.json in the backend folder was overwritten with transform.conf1.json
* I didn't even try to push because I knew there were now 203 resources in ConnectionStack.json (in previous versions api gql-compile would warn of this - but 3.7.0 onward no longer warns when resources are greater than 200).

2. When it worked
* Because I wasn't trying to push to cloudformation that there must be a transform.conf.json on my local disk that was getting copied. So I looked in #current-cloud-backend and found the transform.conf.json that was overwriting my transform.conf2.json in the backend folder. So I started experimenting.
* I over-wrote the #current-cloud-backend version with transform.conf3.json and also copied it to the backend folder
* api gql-compile - this successfully compiled the stacks with the right resources
* push --no-gql-override - this failed because it was having some sort of clash with all the new resources that I was trying to create.
* So I restored the original transform.conf1.json back into the #current-cloud-backend and backend folders. I did not recompile - just restored the original json files.
* push --no-gql-override - this successfully deployed.

**Comment by sacrampton** [comment]
I have not trialed this - but would it work if I just deleted the transform.conf.json from the #current-cloud-backend folder?

**Comment by sacrampton** [comment]
Just on this warning message (https://github.com/aws-amplify/amplify-cli/issues/2335#issuecomment-532996376) - this was occurring on V3.7.0 upwards before I tried  my workaround. It was generating a ConnectionStack.json with 203 resources and not giving any warning about it.

After my work around there were 197 resources so no warning should have been given (and it wasn't).

**Comment by sacrampton** [comment]
I just installed 3.9.0 and this issue has not changed. When are you expecting to deploy?
