### ISSUE TITLE
I cannot change to an env

### ISSUE THREAD

**Issue by ben-elsen** [aws-amplify/amplify-cli#2338]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I try amplify status, I see that I use dev, when I try amplify env list I see that I have an qa env as well, when I try amplify checkout qa, I get the following error: Please pass in a valid environment name. Run amplify env list to get a list of valid environments.
When I try amplify env get --name qa, I do get the info of the qa env.

**To Reproduce**
1. amplify env add (follow the input steps and let's call it dev)
2. amplify status (this shows we use dev)
3. amplify env list (this shows dev)
4. amplify env add (follow the input steps and let's call it qa)
5. amplify status (this shows qa)
6. amplify env list (this shows dev and qa but qa with an * so we use qa)
3. amplify env checkout qa (this shows: Please pass in a valid environment name. Run amplify env list to get a list of valid environments.)

**Expected behavior**
Switch th the qa env with the amplify env checkout qa command.

**Additional context**
I use Cloud9

**Comment by kaustavghosh06** [comment]
Which version of the CLI are you using?

**Comment by kaustavghosh06** [comment]
@ben-elsen We've reproduced the issue. To unblock, please use the following flow:
```
f45c89966b0d:mybetatest kaustavg$ amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: (Use arrow keys)
dev 
❯ qa 

```

**Comment by ben-elsen** [comment]
Thanks!
