### ISSUE TITLE
Guest Access to AWS AppSync does not work properly 

### ISSUE THREAD

**Issue by borisdering** [aws-amplify/amplify-cli#2349]
**Describe the bug**
As describe in the documentation it should be possible to grant guest access to the AppSync GraphQL API. Unfortunately, I was not able to configure this feature due to the error message: "User is not signed in, please sign in to use this API." via iOS SDK, even when I did every step as recommend in the docs. I choose "connected with AWS IAM controls" which will allow me to select Allow unauthenticated logins. I also double checked the console and under settings in my AppSync service the default configuration for authorization mode the default behaviour is **ALLOW**.

**To Reproduce**

1. Initialise new project with "amplify init"
2. Add api with GraphQL endpoint "amplify add api" go through each step and make sure that you choose "connected with AWS IAM controls" and later on "Allow unauthenticated logins". This will configure an api and auth service. 

**Expected behavior**
I'm expecting to be able to grant access to users with guest role. 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: In my case its iOS, but I thinks it relates to any other platform too. 

**Smartphone (please complete the following information):**
- None

**Additional context**
It make amplify and unable for mobile clients. It must be possible to grant guest access to any application. 

**Sample code**
None

**Comment by attilah** [comment]
@borisdering Please tell us which version of the CLI are you using, since in the latest release we added support for multiple authorization modes, for AppSync, which is covered here: https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=ios

By using the ```@auth(rules:[{allow:public, provider: iam}])``` directive on a type, the CLI will generate the appropriate IAM policies for you that will be deployed together with the API.

I'm closing the issue as the question is answered, but if something new comes up, feel free to reopen it.

**Comment by borisdering** [comment]
Hi @attilah, first of all thank you for the fast response. I personally don't use any GraphQL Transform, because I couldn't design an appropriate schema with directives, I had to create custom resolvers instead. Anyways long story short, I did tried your solution but the cli framework did respond with a syntax error. I did found a nice solution on how to grant access to guests. I did attach a inline policy to the unauthenticated role: 
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:<REGION_ID>:<ACCOUNT_ID>:apis/<API_KEY>/types/Query/*"
            ]
        }
    ]
}
`
and set the authentication mode in AppSync to IAM. Im currently working with iOS so I had to change the credentials provider to the mobile client, like this:
`            // You can choose the directory in which AppSync stores its persistent cache databases
            let cache = try AWSAppSyncCacheConfiguration()
            
            // AppSync configuration & client initialization
            let config = try AWSAppSyncServiceConfig()
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: config,
                                                                  credentialsProvider: AWSMobileClient.sharedInstance(),
                                                                  cacheConfiguration: cache)
            self.client = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            // Set id as the cache key for objects. See architecture section for details
            self.client?.apolloClient?.cacheKeyForObject = { $0["id"] }
`
also make sure if anyone reads this, you need to change the authmode in your aws configuration file to 
`    
"AppSync": {
    "Default": {
         "ApiUrl": "API_URL",
         "Region": "REGION_ID",
         "AuthMode": "AWS_IAM"
     }
},
`
By the way, my current version is 1.12.0.
