### ISSUE TITLE
Make @auth protect subscription fields fails

### ISSUE THREAD

**Issue by nookale** [aws-amplify/amplify-cli#2361]
**Describe the bug**
The following schema:
```gql
type Post @model @auth(rules: [{allow: owner}]) {
    id: ID!
    title: String
    owner: String
}
```

Successfully creates the following type Subscription:
```gql
type Subscription {
    onCreatePost(owner: String): Post
    onUpdatePost(owner: String): Post
    onDeletePost(owner: String): Post
}
```

While the following schema (note the combination of "allow:owner" and "ownerField"):
```gql
type Post @model @auth(rules: [{allow: owner, ownerField: "writer"}]) {
    id: ID!
    title: String
    writer: String
}
```

Will create:
```gql
type Subscription {
    onCreatePost: Post
    onUpdatePost: Post
    onDeletePost: Post
}
```

Making authorizing the subscription not possible.

**To Reproduce**
- Create react app.
- Amplify init
- Amplify add auth
- Amplify add api => graphQL
- Create schema.graphql (see code above)
- Amplify push
- Go to Appsync console and check the schema.

Is this intended? "owner" and "ownerField" must not be used together?

**Expected behavior**
Using "owner" and "ownerField" will also automatically create a type Subscription which allows authentication.

**Desktop (please complete the following information):**
 - OS: windows 10

Thanks!

**Comment by attilah** [comment]
@nookale what version of the CLI are you using?

**Comment by nookale** [comment]
@attilah 3.2.0

**Comment by SteffeyDev** [comment]
I have the same issue as above, except for me it appears the addition of the `operations` field prevent the correct generation of the subscription type.  I need the owner to be able to read and and get subscription updates, but not create, delete, or update.  I tested, and removing the `operations` field does fix the issue.  However, this allows the user to write, which should not be allowed for my application.

Schema:
```
type VMInstance
   @model
   @key(fields: ["userId"])
   @auth(rules: [
     { allow: owner, ownerField: "userId", operations: [read] }
   ])
 {
   userId: ID!
   otherProperties: String!
}
```

Actual output:
```
type Subscription {
   onCreateVMInstance: VMInstance @aws_subscribe(mutations: ["createVMInstance"])
   onUpdateVMInstance: VMInstance @aws_subscribe(mutations: ["updateVMInstance"])
   onDeleteVMInstance: VMInstance @aws_subscribe(mutations: ["deleteVMInstance"])
 }
```

Expected output:
```
type Subscription {
   onCreateVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["createVMInstance"])
   onUpdateVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["updateVMInstance"])
   onDeleteVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["deleteVMInstance"])
 }
```

CLI Version: 4.11.0

Reproduction steps same as above, but with different schema.

**Comment by SteffeyDev** [comment]
@SwaySway let me know if I am doing something wrong or if you would like me to open a new issue for this
