### ISSUE TITLE
Updating GSI not retaining older GSI 

### ISSUE THREAD

**Issue by jtushar53** [aws-amplify/amplify-cli#2374]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
If you already have one GSI and when you try to add another it replaces existing GSI instead of appending new to existing GSI array

**To Reproduce**
1. **amplify add storage**
2. Add all info and Add one GSi 'gsi-one'
3. **amplify push**
4. **amplify update storage**
5. add new field and add GSI 'gsi-two'
6. the new gsi will be added to GlobalSecondaryIndexes array replacing the older one. 

**Expected behavior**
It should update / append to existing GlobalSecondaryIndexes in template
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ammarkarachi** [comment]
Closing issue PR has been merged
