### ISSUE TITLE
custom mutation to call Velocity Template

### ISSUE THREAD

**Issue by pspanchal** [aws-amplify/amplify-cli#2376]
** Which Category is your question related to? **
AWS Amplify Cli

** What AWS Services are you utilizing? **
@model on AWS Amplify 

** Provide additional details e.g. code snippets **
I have created my schema with @model and am trying to limit customer inputs for a create Mutation. Hence I created a new mutation function called createNewX with desired inputs with fields that are a subset of the createX mutation automatically created by @model. Now I have also created the velocity template resolver for createNewX and placed it in resolvers folder (not the resolvers in the build folder). The question, however, is - "How to map the mutation declared in the schema to the VTL resolver request and response file"? The documentation shows how to do the same for lambda function but the ask here is around the mapping to Velocity templates. 

Thanks

**Comment by pspanchal** [comment]
Found some documentation here - https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

Followed it. But it is not clear where to put the resolver files? Should I be uploading to s3? Or should I simply put it in the resolvers folder? I did the latter but still receiving an error stating that the .vtl file not found.

**Comment by kevcam4891** [comment]
It should be as simple as placing your .req and .res (and sometimes not even .res) resolvers into the `resolvers` folder. Whatever is in that folder overrides what ever resolver is naturally created by the CLI. Is the override not working as anticipated?

**Comment by pspanchal** [comment]
Yes, it is not working as you are suggesting. Even if I change the name of the vtl file in the Resources section it always throws the same error that the response vtl file is not found. Please note that I am doing amplify mock api. and have not yet done amplify push. Could this just be a bug with mock??

**Comment by yuth** [comment]
We had a [bug](https://github.com/aws-amplify/amplify-cli/issues/2306) in mock where the resolver template names were not honored. We fixed it in https://github.com/aws-amplify/amplify-cli/pull/2355 and as released in Amplify CLI 3.10.0. 

Please feel free to comment here/re-open the issue if this is not resolved in the latest release.

**Comment by alireza8101** [comment]
The problem still exists. Amplify CLI  4.6.0
