### ISSUE TITLE
init failed TypeError: Cannot read property 'configLevel' of undefined

### ISSUE THREAD

**Issue by andrew-aernos** [aws-amplify/amplify-cli#2382]
Amplify CLI version:
3.9.0

Platform:
Windows 10

When trying to create an new environment (with a name that I've used before but have removed since), it fails with the following issue.
```
amplify env add
? Do you want to use an existing environment? No
? Enter a name for the environment dev
Using default provider  awscloudformation
init failed
TypeError: Cannot read property 'configLevel' of undefined
    at getAwsConfig (C:\Users\Andrew\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\initializer.js:65:21)
    at Object.run (C:\Users\Andrew\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\initializer.js:44:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by UnleashedMind** [comment]
Hi @andrew-aernos 

What's the Operating system you ran the amplify cli on? 
could you also run `amplify -v` and find out the version of the cli?

**Comment by andrew-aernos** [comment]
> Hi @andrew-aernos
> 
> What's the Operating system you ran the amplify cli on?
> could you also run `amplify -v` and find out the version of the cli?

Amplify CLI version: 3.9.0
Platform: Windows 10

**Comment by andrew-aernos** [comment]
Strangely I can add another environment with the name 'prod' for production.

**Comment by andrew-aernos** [comment]
Found a lingering environment of the name 'dev' in the amplify/.config/local-aws-info.json. There must've been a inconsistent environment removal.

The fix was to remove the `<your old env name>` environment name block, and then add the environment of the same name again with `amplify env add`.

**Comment by UnleashedMind** [comment]
not sure what was the cause of the incomplete env removal. I tested and the environment is actually removed from the `amplify/.config/local-aws-info.json` file. 
Could you try a `amplify env remove` again and see if you still have the incomplete env removal?

**Comment by andrew-aernos** [comment]
I couldn't reproduce my issue after I manually removed the offending environment from the local-aws-info.json. 

Not sure what caused it in the first place, I did find left-over 'dev' stack on the cloud along with its resources. probably a stupid/impatient me terminated the process while roll-back was in place and the local-aws-info.json wasn't updated (??). 

As of now I tried `amplify env remove <myenv>` and it **does** remove the environment from the local-aws-info.json as expected.

**Comment by sopranolinist** [comment]
@UnleashedMind I experienced the exact same issue. I tried running `amplify env remove staging` again (staging being the name of the environment in my case) and I received the response `No environment found with the corresponding name provided`. So just like @andrew-aernos I had to manually delete the entry in my `local-aws-info.json` file.
