### ISSUE TITLE
Unnecessary Amplify init on Codegen

### ISSUE THREAD

**Issue by borisdering** [aws-amplify/amplify-cli#2383]
** Which Category is your question related to? **
Why do I need to init a project when I just want to use the codegen subtooling? 

** What AWS Services are you utilizing? **
- Amplify cli

** Provide additional details e.g. code snippets **
amplify codegen types --nodownload

**Comment by nikhname** [comment]
Hi @borisdering, you can use codegen without init by including your schema (named schema.graphl) or instrospection schema (named schema.json) in the root directory of your project and running amplify add codegen. Then, if you want to update your types, save you changes to the schema/introspection schema and run amplify codegen types. The --no-download flag is not needed outside of an amplify project.

For more about this flow, take a look at flow 5 in the docs for this workflow: https://aws-amplify.github.io/docs/cli-toolchain/graphql#workflows
