### ISSUE TITLE
Ability to have custom Category templates

### ISSUE THREAD

**Issue by dbrunet73** [aws-amplify/amplify-cli#2392]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
We would like to be able to customize the CF templates generated in any category (AUTH, API, etc). So i am proposing that you have an option available that when we add a new Amplify Category, that it offers the option to use a template (current state) or custom template. If we choose custom, then amplify would just create an empty template that we can populate with all the relevant values required for our app. This template would not go through all the edits that you do when you validate the templates, but should have edits to ensure the template is in the correct format. 

**Describe the solution you'd like**
When adding a new category: 
amplify add api
Select either to generate from a template or custom
>Template Auth
>Custom Auth
If template is selected then the normal process will execute. 
If Custom is selected then an empty template with only the basic details is created. 
The custom template will have to be updated manually and maintained manually. 

**Describe alternatives you've considered**

Have looked at different ways to do this, but they all have some inconsistencies and issues. 

**Additional context**
This would allow us to better take advantage of new features on aws services as they are released, since we don't have to wait for the CLI to be updated with the changes to the service.

**Comment by UnleashedMind** [comment]
@dbrunet73 
The CloudFormation template generated by the CLI can be edited before you run `amplify push` to actually create/update the aws resources. 
However, if you manually modify the CLI generated template, some of the Amplify CLI commands such as `amplify <category> update` may break, and if the template is not valid, `amplify push` will fail because CloudFormation update will fail.

**Comment by kaustavghosh06** [comment]
@dbrunet73 You may also want to take a look at - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks for custom Cloudformation stack support.
