### ISSUE TITLE
Custom Cloudformation Stacks to manage growing list of custom resolvers and its dependencies

### ISSUE THREAD

**Issue by andrew-aernos** [aws-amplify/amplify-cli#2398]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify CLI custom categories and resources

** What AWS Services are you utilizing? **
Amplify, AppSync GraphQL custom resolvers, Cloudformation

** Provide additional details e.g. code snippets **
Amplify version 3.9.0
Following the guidelines here https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks

My CustomResources.json is getting out of hand with all the custom resolvers, appsync datasource, the underlying dynamodb/lambda and its required iam service roles. I don't really know what is the best practice for managing this. The dependency is illustrated below:

![aws-cloud-stack](https://user-images.githubusercontent.com/40867426/65560374-3f2f6280-def3-11e9-8d71-52d2c4b04dbc.png)

**_Approach 1 - Package by type_**
Define custom categories and resources, and defined dependsOn in the backend-config.json

```
amplify/backend

-/api
--/Api
---/stacks/CustomResources.json
--/Resolver
---/Resolvers
---api-resolver-template.json  (!) can't get reference to the needed "S3DeploymentBucket" and "S3DeploymentRootKey" parameters.

-/datasource
--/FooDataSource
---/foo-datasource-template.json

-/iam
--/FooServiceRole
---/foo-servicerole-template.json

-/storage
--/FooTable
---/foo-table-template.json
```

_Problem with this approach:_ 
I'm stuck trying to get "S3DeploymentBucket" and "S3DeploymentRootKey" needed for the Resolvers. One weird way I'm trying is to get them output from the api's nested stack in stakcs/CustomResources.json but I can't seem to find documentation on how to reference output from a nested stack.

_**Approach 2 Package-by-feature**_
Much more ideal and scalable, for each new feature it can independently define its own set of dependencies, datasource type and resolvers. for ex. User

![image](https://user-images.githubusercontent.com/40867426/65727177-dcada200-e06b-11e9-917c-45eefcd39c3a.png)

Problem with this pattern is currently as of amplify 3.9.0, the appsync service doesn't bundle up everything and upload all the assets, making nested-stack reference impossible if it is organized this way by the developer client. Is there is a way to hook into the appsync service build process to have it bundle everything and load the asset to S3 ???

I'm short of just flattening the package-by-feature pattern to prefixes, which to me would be another absolute hell to deal with.

**Comment by SwaySway** [comment]
@andrew-aernos Are you looking at retrieving S3DeploymentBucket and S3DeploymentRootKey to save custom resolvers in S3?

**Comment by SwaySway** [comment]
Feel free to reopen/comment if you have further questions.
