### ISSUE TITLE
ModelConnectionTransformer does not create filter inputs on fields

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#24]
Version: 0.1.13

Simple Schema:

```graphql
type Post @model {
	id: ID!
	things: [Thing!] @connection
}

type Thing @model(queries: null, mutations: null) {
	id: ID!
}
```

Generates:

```graphql
type Post {
  id: ID!
  things(filter: ModelThingFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelThingConnection
}
```

however, `ModelThingFilterInput` is not generated.

In this case due to @model declation on Thing, the listThings function is not created and `generateFilterInputs` is not called for `Thing` (i.e.: this bug is masked by the fact that the filter can be created for other fields). In ModelConnectionTransformer, I think there is a typo/bug:

https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts#L307

should be:

```typescript
this.generateFilterInputs(ctx, returnType)
```

**Comment by mikeparisstuff** [comment]
This issue can be closed.
