### ISSUE TITLE
Additional configurations on Storage Bucket

### ISSUE THREAD

**Issue by DanielMuller** [aws-amplify/amplify-cli#2401]
** Which Category is your question related to? **
Storage

** What AWS Services are you utilizing? **
Amplify-CLI, Storage, Auth

** Provide additional details e.g. code snippets **
Somehow related to #2279, on being able to extend cloudformation templates generated by Amplify.
 
My app just uses Storage and Auth (no API) to allow users store and retrieve files.

I create a storage bucket with `amplify add storage`. So far so good.

I now want to tweak some of this bucket settings, mainly:
* Enable transfer acceleration
* Enable lifecycles
* Add custom tags

I could modify `amplify/backend/storage/stackName/s3-cloudformation-template.json`, but my changes will be overwritten by any `amplify storage update`.

Is there a way to add this via an additional "plugin-like" template file? Or do I need to manage my  bucket without amplify as a "custom resource", in which case I loose the role policies managed by Amplify.

**Comment by kaustavghosh06** [comment]
@DanielMuller You could go ahead and modify the Cloudformation file for the S3 storage resource localted in `amplify/backend/storage/<resource-name>` directory to add these additional configurations if you need it.

**Comment by kaustavghosh06** [comment]
Also, I don't believe `amplify storage update` will overwrite your changes. Did you verify this behavior?

**Comment by DanielMuller** [comment]
> Also, I don't believe `amplify storage update` will overwrite your changes. Did you verify this behavior?

Just tested it with "Acceleration" and a "Lifecycle", and indeed it doesn't get overwritten after `amplify storage update` (I changed the auth rules and added a trigger).

I wrongly assumed that the Cloudformation template would be rewritten on any CLI change without even trying it out.
