### ISSUE TITLE
Joint access to DynamoDB record with AppSync using Dynamic Group Authorization

### ISSUE THREAD

**Issue by kevinold** [aws-amplify/amplify-cli#2405]
** Which Category is your question related to? **
Authentication and Authorization

** What AWS Services are you utilizing? **
Amplify CLI 3.9.0, AppSync, Cognito, DynamoDB

** Provide additional details e.g. code snippets **

I have a requirement of having 2 users with shared access to a DynamoDB Item.

I cannot use a Cognito Group for the users, as I wish to have 2 users that sign up via social authentication "connect" to each other, so the "group" would be a dynamic one, in which the "PeopleCanAccess" list is perfect.

I understand via https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html#reading-data in the "Use Case: Multiple People Can Read" how my resolver should be for the read case.

"Use Case: Multiple Owners" under "Writing Data" (https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html#writing-data) says it is for the PeopleCanAccess, but I'm confused with this expectedOwner example.

Using the common Todo's app, here's the scenario for what I need to accomplish in this "shared todos" version of the app:

1. UserA registered with the service
2. UserA can do the usual CRUD for a list of todo's
3. UserA can "invite" UserB to their Todo List (thinking a Lambda to do this with an invite code of some sort"
4. UserB registers via invite code
5. UserB has access to Todo's
6. When UserA or UserB CRUD's Todo's, PeopleCanAccess is updated accordingly.
7. Thinking through this, using the invite mechanism I described in step 3, I'd have an attribute on UserA's record to holder UserB's ID. When a Todo item is CRUD'd by UserA, I'd envision the resolver to write UserB to the PeopleCanAccess list.

I've looked into Dynamic Group Authorization in the GraphQL Transform: https://aws-amplify.github.io/docs/cli-toolchain/graphql#dynamic-group-authorization and tried to combine them with Custom Claims: https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-claims

I've setup a test project (https://github.com/kevinold/amplify-notes-test) which:

- Limited a Task type to use the Dynamic Groups https://github.com/kevinold/amplify-notes-test/blob/master/amplify/backend/api/amplifynotes/schema.graphql#L5

- Defines the Pre Token Gen Lambda to add a claim with a hard coded user_group: https://github.com/kevinold/amplify-notes-test/blob/master/amplify/backend/function/amplifynotestest79fd735aPreTokenGeneration/src/alter-claims.js#L6

I have verified that the claim is present in the JWT:

<img width="938" alt="Screen Shot 2019-09-25 at 8 10 17 AM" src="https://user-images.githubusercontent.com/21967/65603869-11d2cb00-df6c-11e9-944c-09cd30780536.png">

In the screenshots attached I've populated the DynamoDB table with example records, one of which has the "test-group1", but as you can see from the other screenshot no items are returned.

<img width="731" alt="Screen Shot 2019-09-24 at 10 34 57 PM" src="https://user-images.githubusercontent.com/21967/65603278-fdda9980-df6a-11e9-99d3-62ab2dc093e6.png">

<img width="1276" alt="Screen Shot 2019-09-24 at 10 36 04 PM" src="https://user-images.githubusercontent.com/21967/65603277-fdda9980-df6a-11e9-8db2-a3b3bc04e23b.png">

I did try various Dynamic Group auth rules, but none of them worked.

```
{ allow: groups, groupsField: "groups" }
{ allow: groups, groupsField: "groups", groupClaim: "user_groups" }
{ allow: groups, groupsField: "groups", groupClaim: "user_groups", queries: ["list"] }

```
I have a suspicion that I might not be able to use Dynamic Groups with the Custom Claim, but am hoping so, since my groups will be dynamic.

In addition, I do not see anything about using a custom VTL template for my resolver related to Dynamic Group Authorization.  If I should use one, please advise.

Please let me know of any changes I can make to get Dynamic Group Authorization working.

**Comment by SwaySway** [comment]
Merged PR #2180 fixes this issue as well marking as pending-release

**Comment by kevinold** [comment]
@SwaySway @RossWilliams Thanks for your patches!


I have tested with the fix merged in #2180 pulling the latest master, compiling and deploying my project via `amplify-dev`

My auth rule is defined as:

`## Authorization rule: { allow: groups, groupsField: "groups", groupClaim: "user_groups" } **`

and produces the following response template

```
## [Start] Determine request authentication mode **
#if( $util.isNullOrEmpty($authMode) && !$util.isNull($ctx.identity) && !$util.isNull($ctx.identity.sub) && !$util.isNull($ctx.identity.issuer) && !$util.isNull($ctx.identity.username) && !$util.isNull($ctx.identity.claims) && !$util.isNull($ctx.identity.sourceIp) && !$util.isNull($ctx.identity.defaultAuthStrategy) )
  #set( $authMode = "userPools" )
#end
## [End] Determine request authentication mode **
## [Start] Check authMode and execute owner/group checks **
#if( $authMode == "userPools" )
  ## No Static Group Authorization Rules **


  ## [Start] If not static group authorized, filter items **
  #if( ! $isStaticGroupAuthorized )
    #set( $items = [] )
    #foreach( $item in $ctx.result.items )
      ## [Start] Dynamic Group Authorization Checks **
      #set( $isLocalDynamicGroupAuthorized = false )
      ## Authorization rule: { allow: groups, groupsField: "groups", groupClaim: "user_groups" } **
      #set( $allowedGroups = $util.defaultIfNull($item.groups, []) )
      #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("user_groups"), []) )
      #if( $util.isString($userGroups) )
        #if( $util.isList($util.parseJson($userGroups)) )
          #set( $userGroups = $util.parseJson($userGroups) )
        #else
          #set( $userGroups = [$userGroups] )
        #end
      #end
      #foreach( $userGroup in $userGroups )
        #if( $util.isList($allowedGroups) )
          #if( $allowedGroups.contains($userGroup) )
            #set( $isLocalDynamicGroupAuthorized = true )
          #end
        #end
        #if( $util.isString($allowedGroups) )
          #if( $allowedGroups == $userGroup )
            #set( $isLocalDynamicGroupAuthorized = true )
          #end
        #end
      #end
      ## [End] Dynamic Group Authorization Checks **


      ## No Owner Authorization Rules **


      #if( ($isLocalDynamicGroupAuthorized == true || $isLocalOwnerAuthorized == true) )
        $util.qr($items.add($item))
      #end
    #end
    #set( $ctx.result.items = $items )
  #end
  ## [End] If not static group authorized, filter items **
#end
## [End] Check authMode and execute owner/group checks **

$util.toJson($ctx.result)
```

I have verified this response template should return the correct data via testing in the AppSync console.

My test data I chose "Context with Cognito User Pools auth" with a value of:

```{
    "arguments": {
        "filter": {},
        "limit": 85,
        "nextToken": "Hello, world!"
    },
    "source": {},
    "result": {
        "nextToken": "Hello, world!",
        "items": [
            {
                "id": "1",
                "groups": [
                    "test-group1"
                ]
            },
            {
                "id": "2",
                "groups": [
                    "test-group2"
                ]
            },
            {
                "id": "3",
                "groups": [
                    "test-group3"
                ]
            }
        ]
    },
    "identity": {
        "sub": "uuid",
        "issuer": "https://cognito-idp.{region}.amazonaws.com/{userPoolId}",
        "username": "my-username",
        "claims": {
            "user_groups": "test-group1"
        },
        "sourceIp": [
            "x.x.x.x"
        ],
        "defaultAuthStrategy": "ALLOW"
    }
}
```

The test returned:

<img width="909" alt="Screen Shot 2019-09-26 at 10 48 51 PM" src="https://user-images.githubusercontent.com/21967/65740887-e0631800-e0af-11e9-8f36-86ab1f4a7bd4.png">

Unfortunately, my frontend (https://github.com/kevinold/amplify-notes-test/blob/master/src/App.js#L27-L33) when querying the data after login does not receive data.

<img width="1278" alt="Screen Shot 2019-09-26 at 10 53 17 PM" src="https://user-images.githubusercontent.com/21967/65741057-7c8d1f00-e0b0-11e9-9ea2-16fef68ff388.png">

I have not been able to spot the bug.

Please let me know if you have additional ideas.  

Thanks!

cc @undefobj

**Comment by RossWilliams** [comment]
Your frontend is using the Access Token in the authorization header, custom claims will be on the Id Token

**Comment by kevinold** [comment]
> Your frontend is using the Access Token in the authorization header, custom claims will be on the Id Token

@RossWilliams Great catch, but I'm still seeing the error with Cognito auth. :(

**Comment by RossWilliams** [comment]
I deployed your project and used the AppSync Console Queries tab to test the endpoint using Cognito auth and was able to insert and list data. The API and schema design appear to work properly from my testing.

It's not clear to me what you mean by "the error with Cognito auth"? Have you tried to make the request using the Id Token?

**Comment by kevinold** [comment]
> I deployed your project and used the AppSync Console Queries tab to test the endpoint using Cognito auth and was able to insert and list data. The API and schema design appear to work properly from my testing.

Yes, I am able to do all this in the AppSync Console without issue.

> It's not clear to me what you mean by "the error with Cognito auth"? Have you tried to make the request using the Id Token?

What I am not able to do is see the data in my React application.  I see this after I login as a user:

<img width="1278" alt="65741057-7c8d1f00-e0b0-11e9-9ea2-16fef68ff388" src="https://user-images.githubusercontent.com/21967/65802293-dfc69200-e140-11e9-99a2-8d34b1c039dc.png">

Amplify is configured correctly https://github.com/kevinold/amplify-notes-test/blob/master/src/App.js#L9

I had to wire this up manually in the Cognito console since I switched Cognito auth instances, but I've hardcoded the group in the pre token generator:

https://github.com/kevinold/amplify-notes-test/blob/master/amplify/backend/function/amplifynotestest79fd735aPreTokenGeneration/src/alter-claims.js#L6

Is there additional configuration I'm missing on the client side for using the Id Token?  I think not as I am getting the user details back when I look in localStorage.

**Comment by RossWilliams** [comment]
Yes, there is more work for you to do on the client side, and you will need to connect your id token to the authorisation header manually if you want to use this approach. Use the custom request header ([docs])(https://aws-amplify.github.io/docs/js/api#set-custom-request-headers-for-graphql) configuration option to inject the Id token for the Auth header. You can get the id token from: ```await Auth.currentSession()).getIdToken().getJwtToken()```. Be aware that there are many scenarios where this is not a good idea and not recommended, and you need to be familiar with OAuth concepts to determine if it is appropriate in your context.

The reason for this is a bit complicated,  but hopefully this will ease / redirect your frustration. 

Using an Id token for authorisation is in many cases not a good idea. Id tokens are for providing identification data, in and  can contain a lot of PII. This becomes more important when federation is involved, as you are passing unnecessary PII to third parties. Access tokens are meant to be used to provide authorisation information. Amplify-JS authors want to support using access tokens and discourage using id tokens for authorisation for these reasons.

However, Cognito provides limited (almost none) support for adding authorisation information to access tokens. Instead they offer id token customisation. Cognito has been a stagnant product for quite some time. I think I first saw a feature request for modifying access tokens in a request from 2017. On the other hand, pre token lambda recently got cloudformation support after being on the feature request list for a few years. Maybe one day access tokens can be customised.

While it would be nice to be able to request a feature to any group in AWS and have it actioned, you might be better off filing a feature request with the Cognito team directly.

**Comment by kevinold** [comment]
@RossWilliams Thanks for this info.  I do not recall ever having to do this customization before nor can I find reference in the documentation directing this https://aws-amplify.github.io/docs/js/authentication

I have refactored (https://github.com/kevinold/amplify-notes-test/commit/c483f46df7637af10c71468bba0f9ae34deb9c03) to override the `Authorization` header (https://github.com/kevinold/amplify-notes-test/commit/c483f46df7637af10c71468bba0f9ae34deb9c03#diff-14b1e33d5bf5649597cdc0e4f684daddR9-R16), but I am still not able to get a list of tasks for the user I just logged in as.

<img width="1272" alt="Screen Shot 2019-09-28 at 11 06 53 AM" src="https://user-images.githubusercontent.com/21967/65819275-24553a80-e1e0-11e9-80a0-40cbe080688c.png">
<img width="1277" alt="Screen Shot 2019-09-28 at 11 07 43 AM" src="https://user-images.githubusercontent.com/21967/65819284-3fc04580-e1e0-11e9-84dd-f50b8b0e887d.png">


In addition, I'm noticing that if I try to call `Auth.currentCredentials()` I receive a console error: `NotAuthorizedException: Unauthenticated access is not supported for this identity pool.`.  this is weird, as I have just authenticated as the user and I am able to see it's details:

<img width="1279" alt="Screen Shot 2019-09-28 at 11 10 43 AM" src="https://user-images.githubusercontent.com/21967/65819329-b0676200-e1e0-11e9-9d99-d6c636783e83.png">
<img width="1277" alt="Screen Shot 2019-09-28 at 11 09 51 AM" src="https://user-images.githubusercontent.com/21967/65819330-b0676200-e1e0-11e9-905c-cac642333e56.png">

I am going to implement a v2 version of this test project implementing from scratch so that I am certain all the resources are fresh.

**Comment by kevinold** [comment]
@RossWilliams I was able to get things working with the Id Token override for the Authorization header as you described. Thanks for your help.

Details and an example of this setup working:

I created a fresh project off of @dabit3's https://github.com/dabit3/aws-appsync-react-workshop jumping straight to adding Cognito Auth with no API Key: 

https://github.com/kevinold/amplify-workshop-dabit3

- Added Cognito Auth with Pre Token Generation with hard coded Dynamic Group on a claim field "user_groups" with "test-group1"
https://github.com/kevinold/amplify-workshop-dabit3/blob/master/amplify/backend/function/amplifyreactapp304200aaPreTokenGeneration/src/alter-claims.js#L5

- Configure Talk with owner rule and Dynamic Group Auth rule specifying the `groupsField` of `groups` (https://github.com/kevinold/amplify-workshop-dabit3/blob/master/amplify/backend/api/ConferenceAPI/schema.graphql#L15) and a `groupClaim` field of `user_groups` (which maps to the claim in https://github.com/kevinold/amplify-workshop-dabit3/blob/master/amplify/backend/function/amplifyreactapp304200aaPreTokenGeneration/src/alter-claims.js#L5) https://github.com/kevinold/amplify-workshop-dabit3/blob/master/amplify/backend/api/ConferenceAPI/schema.graphql#L5-L6

- For testing purposes only, I set the `groups` field in the client https://github.com/kevinold/amplify-workshop-dabit3/blob/master/src/App.js#L87, but would love to have this done on the server if I can figure out how

- Configure Amplify to use the Id Token for the Authorization header:
https://github.com/kevinold/amplify-workshop-dabit3/blob/master/src/App.js#L10-L17

**Comment by RossWilliams** [comment]
> For testing purposes only, I set the groups field in the client https://github.com/kevinold/amplify-workshop-dabit3/blob/master/src/App.js#L87, but would love to have this done on the server if I can figure out how

The @auth directive protects the create operation. If a user tried to set the groups field to a group they don't belong the request will be rejected. Does this solve your problem? Otherwise you will need to use a @function directive.
