### ISSUE TITLE
Multi App Hosting and Resource Sharing

### ISSUE THREAD

**Issue by magjack** [aws-amplify/amplify-cli#2406]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
I have been using aws amplify to create a multi frontend application with the same backend. The solution I have employed is described here https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends. This works well for features such as auth, graphql and api features. However, It doesn't perform well for hosting as when I add hosting to an amplify environment since I am sharing the same environment across both apps, it overwrites the hosting configuration. This makes it difficult to use aws amplify console for a CI/CD pipeline.   

**Describe the solution you'd like**
The hosting of an aws amplify project could be separated from other shareable resources such as auth and data resources. The hosting config could be set up in for app one and then a .amplifyignore file could be employed so when I setup the config in the second app it doesn't overwrite the first when I push and pull the environment between the apps. 

**Describe alternatives you've considered**
The ability to share resources between different amplify enviroments would also solve this solution as you could create 2 different environments for both apps. These environments could then both be configured with the same Cognito or AppSync resources, however, have a different hosting config. This could be implemented by asking the user when they are adding a resource to an enviroment if there is already a resource created they would like to connect to instead of always creating a new one per environment. 
eg. 

```
$ amplify add api \n
? Please select from one of the below mentioned services (Use arrow keys) GraphQL \n
? Make use of existing resource(y/n) y
? Please select an existing resource  (Use arrow keys) \n
appSync-Dev
appSync-Sit

```

**Comment by swaminator** [comment]
Have you used the Amplify Console for hosting your app with multienv? The flow works well with multienv: https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html#team-workflows-with-amplify-cli-backend-environments

**Comment by magjack** [comment]
I used the Amplify console and it has my desired behaviour of being able to host 2 apps independently and make use of the same backend code. My confusion came from adding hosting to an environment with amplify-cli and I thought this had to be configured before you could use the amplify console. I have since removed all hosting done via the cli in favour of the console. Thank you.
