### ISSUE TITLE
Issues with migrating to multi envs from a previous custom multi env setup

### ISSUE THREAD

**Issue by wmcbain** [aws-amplify/amplify-cli#2407]
**Note**: I initially sent this to the amplify team email and was told to post here. If anyone has any feedback on this it would be greatly appreciated 🙌🏻.

**Issue**:

Our team has been trying to migrate our amplify-cli to the latest version and we’re reaching out for advice on how to proceed as we’ve run into some issues. Our setup is a little unique which makes it a bit more challenging than using the migration tool or following the manual migration guide.

Our project is React and prior to trying to migrate we were using version 0.1.42 of the CLI. Since multiple environments weren’t supported until version 1.0 we created two configs, appended .staging or .production to the files, and copied those files to the amplify defined locations based on the environment we were trying to target.

Unfortunately this setup is fragile and somewhere along the way our #current-cloud-backend for our staging and production targets fell out of step with what is actually there. With version 0.1.42 we can’t pull or restore the environment to get the #current-cloud-backend. In our specific case we’ve pushed storage and the S3 buckets are live, but amplify status shows that it wants to Create the resource.

Since this didn’t work we’ve tried upgrading to the latest version of the cli, 3.9.0, and following the migration guide to use multiple environments. I’m familiar with how the new cli now uses the env name to name and create resources. However we already have the names and resources defined so I’ve tried skipping the conditions around the env variable and using amplify env checkout to add the configs per environment.

After migrating we are able to use amplify status and get a response. But we’re still unable to restore the #current-cloud-backend with amplify env pull or using the restore flag. The error we receive is that the key for the resource doesn’t exist when it tried to do the pull. They key it’s looking for is #current-cloud-backend.zip. 

So right now we’re a bit stuck on adding new Amplify features or modifying existing configs until we can finish this migration and sync with the #current-cloud-backend. 

What we’re looking for is advice on how to proceed with this migration without affecting our production environment. The staging environment can be reprovisioned and if we need to migrate to new user pools we can do that to. Using amplify push in this scenario seems risky and we want to make sure we get this right.

**Comment by kaustavghosh06** [comment]
@wmcbain Did you get an error log - stating if the migration failed or succeeded?

**Comment by kaustavghosh06** [comment]
@wmcbain Also, it'll be super helpful to know your current directory structure after the migration and what's the error you're getting when trying to push again or creating a new environment.

**Comment by wmcbain** [comment]
@kaustavghosh06 

I did not use `amplify migrate` as we have two environments that already exist within the project. I've migrated our staging configuration using the manual migration guide. However I've avoided adding the conditions to the templates that change resource names based on the env variable.

I've made some progress but I'm still catching errors trying to `amplify push`.

```sh
$ amplify push

Current Environment: staging

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | Staging       | Update    | awscloudformation |
| Storage  | Staging       | No Change | awscloudformation |
? Are you sure you want to continue? Yes
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          app-redacted-123 AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:48 GMT-0400 (Eastern Daylight Time) User Initiated                                                                         
UPDATE_IN_PROGRESS          UnauthRole           AWS::IAM::Role             Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time)                                                                                        
UPDATE_IN_PROGRESS          AuthRole             AWS::IAM::Role             Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time)                                                                                        
UPDATE_IN_PROGRESS          storageStaging       AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time)                                                                                        
UPDATE_IN_PROGRESS          authStaging          AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time)                                                                                        
UPDATE_FAILED               storageStaging       AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time) Parameters: [env] do not exist in the template                                         
UPDATE_COMPLETE             authStaging          AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time)                                                                                        
UPDATE_FAILED               UnauthRole           AWS::IAM::Role             Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time) Resource update cancelled                                                              
UPDATE_FAILED               AuthRole             AWS::IAM::Role             Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time) Resource update cancelled                                                              
UPDATE_ROLLBACK_IN_PROGRESS app-redacted-123 AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:52 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to update: [AuthRole, storageStaging, UnauthRole].
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS authStaging        AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:03 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS AuthRole           AWS::IAM::Role             Wed Sep 25 2019 15:53:03 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS UnauthRole         AWS::IAM::Role             Wed Sep 25 2019 15:53:03 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE    storageStaging     AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:03 GMT-0400 (Eastern Daylight Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE authStaging AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:03 GMT-0400 (Eastern Daylight Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                              UnauthRole           AWS::IAM::Role             Wed Sep 25 2019 15:53:20 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE                              AuthRole             AWS::IAM::Role             Wed Sep 25 2019 15:53:20 GMT-0400 (Eastern Daylight Time) 
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS app-redacted-123 AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:21 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS                           storageStaging   AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:22 GMT-0400 (Eastern Daylight Time) 
UPDATE_IN_PROGRESS                           authStaging     AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:22 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE                              storageStaging   AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:22 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE                              authStaging     AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:22 GMT-0400 (Eastern Daylight Time) 
UPDATE_ROLLBACK_COMPLETE                     app-redacted-123 AWS::CloudFormation::Stack Wed Sep 25 2019 15:53:22 GMT-0400 (Eastern Daylight Time) 
⠸ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠦ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: app-redacted-123-authRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-2%3A686711563431%3Astack%2Fapp-redacted-123%2F5f4720e0-baa4-11e8-b387-020cf0d94894/events


Resource Name: app-redacted-123-unauthRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-2%3A686711563431%3Astack%2Fapp-redacted-123%2F5f4720e0-baa4-11e8-b387-020cf0d94894/events
```

**Comment by kaustavghosh06** [comment]
@wmcbain "UPDATE_FAILED               storageStaging       AWS::CloudFormation::Stack Wed Sep 25 2019 15:52:51 GMT-0400 (Eastern Daylight Time) Parameters: [env] do not exist in the template 

^This is the main issue. If you add the "env" as a parameter in your Cloudformation templates, you should be good - since the CLI auto-injects the env parameter as input for each of the Cloudformation templates at deploy time. So if the Cloudformation tempaltes don't have "env" as an input parameter, you would see Cloudformation failures like the one above. The auto-migration would've injected this in your templates.

**Comment by wmcbain** [comment]
@kaustavghosh06 Sorry for going silent on this issue but I was still blocked by this and needed tome onto other work.

I'm still seeing this failure and the error isn't making a lot of sense. I'm including the env parameter in the template:

```
  "Parameters": {
    "bucketName": {
      "Type": "String"
    },
    "authPolicyName": {
      "Type": "String"
    },
    "unauthPolicyName": {
      "Type": "String"
    },
    "authRoleName": {
      "Type": "String"
    },
    "unauthRoleName": {
      "Type": "String"
    },
    "unauthPermissions": {
      "Type": "String"
    },
    "authPermissions": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    }
  },
```

However when I run `amplify push` I still get the following error:

```
UPDATE_FAILED               storageuserStorage   AWS::CloudFormation::Stack Wed Oct 02 2019 12:04:10 GMT-0400 (Eastern Daylight Time) Parameters: [env] do not exist in the template                                         
UPDATE_FAILED               UnauthRole           AWS::IAM::Role             Wed Oct 02 2019 12:04:10 GMT-0400 (Eastern Daylight Time) Resource update cancelled                                                              
UPDATE_FAILED               AuthRole             AWS::IAM::Role             Wed Oct 02 2019 12:04:10 GMT-0400 (Eastern Daylight Time) Resource update cancelled    
```
