### ISSUE TITLE
Any way to avoid duplicated data from graphql query

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#2408]
Say you have a graphql schema like this:

<img width="662" alt="Screenshot 2019-09-25 at 22 16 44" src="https://user-images.githubusercontent.com/1822105/65636233-34073000-dfe2-11e9-81ed-7209749be814.png">

If you want to get all the required data for rendering the chat in a single query, the query would look something like this:

<img width="356" alt="Screenshot 2019-09-25 at 22 11 17" src="https://user-images.githubusercontent.com/1822105/65635861-7419e300-dfe1-11e9-9954-b249546d2650.png">

But of course that means that there will be possibility for huge duplication of data about users in the response (wasting resources everywhere). 
Is there any way in Amplify to specify so that the server returns each individual Users' data just once in the whole response, and then in other places it uses just the id?
Any other idea of how to approach this? (Besides the obvious way of fetching just users' ids, and then fetching user's data in separate graphql query) . Thanks!

**Comment by SwaySway** [comment]
@tgjorgoski You can specify what you would like as a response in the graphql query. So if you didn't want to duplicate the data for chat you can limit the info to just the user and not include the chat
```gql
query {
  getChat(id: "....") {
    id
    content
    createdAt
    user {
      id
      email # and other necessary info related to user and not add chat related info
   } 
  }
}
```

If you have any other questions on this please feel free to comment.

**Comment by tgjorgoski** [comment]
@SwaySway , I'm affraid you didn't understand the question.
I want to get the chat messages including WHO wrote them. However if e.g. 1 person wrote 500 of the messages, if you get user data with each message you will receive 500 times the same user info.
Now, of course you can request JUST the id, and AFTER the initial query, make additional one requesting the details.
However, I'm asking if there is a way to do it using just a single query, so that ALL the details for the user will be present the first time that user data is encountered, but not the following times.

I read somewhere in the Apollo Client documentation somewhere that it will handle the case nicely using its data normalization - it just needs the data to be there the first time the item is encountered.
Also,  there are libraries like  https://github.com/gajus/graphql-deduplicator , which are supposed to do that, removing the duplicated data from the resulting query. However it would be better if there is a way/option that the duplicated data isn't included in the query result in the first place.

**Comment by SwaySway** [comment]
@tgjorgoski
I don't believe this is possible with a getChat query at least not out of the box.
Another thing to consider would be adding a one-to-many `@connection` between a User and Message.

**Comment by tgjorgoski** [comment]
Thanks @SwaySway .  I  haven't looked into the possibility of building custom appsync pipelines, but wonder if something like this could be done by adding  a lambda function and runing that deduplicator library before returning the response.

And I wonder another thing, do the default AppSync resolvers which connect to DynamoDB make multiple requests in this kind of case (when they need to return the same user multiple times), or is this cached internally? Not that it would help knowing this, but certainly it might affect the number of queries done against DynamoDB, and how much is spent for such query.

**Comment by nikhname** [comment]
@tgjorgoski The requested will not be cached internally in the resolvers. Feel free to reopen/comment if you have further questions.

**Comment by Slowly** [comment]
> @SwaySway , I'm affraid you didn't understand the question.
> I want to get the chat messages including WHO wrote them. However if e.g. 1 person wrote 500 of the messages, if you get user data with each message you will receive 500 times the same user info.
> Now, of course you can request JUST the user id, and AFTER the initial query, make additional one requesting the details.
> However, I'm asking if there is a way to do it using just a single query, so that ALL the details for the user will be present the first time that user data is encountered (the first comment in the query results), but not the following times (in the following comments, it would include just the user id).
> 
...Exactly, that is one of the things that I find annoying about graphQL. SQL does not duplicate data like this, and has aggregation and the DISTINCT keyword to further reduce duplicates.
