### ISSUE TITLE
I am stuck while installing aws-amplify/cli 

### ISSUE THREAD

**Issue by Muazzamkhan95** [aws-amplify/amplify-cli#2409]
can any one help me in fixing this issue. really quick
![asdfasdf](https://user-images.githubusercontent.com/17087133/65639642-eef2f600-e001-11e9-97cc-15e2b06b04da.PNG)

ERROR LOG
[2019-09-25T21_04_22_588Z-debug.log](https://github.com/aws-amplify/amplify-cli/files/3654778/2019-09-25T21_04_22_588Z-debug.log)

**Comment by kaustavghosh06** [comment]
@Muazzamkhan95 What's the node version you're running?

**Comment by Muazzamkhan95** [comment]
> @Muazzamkhan95 What's the node version you're running?

v10.15.3

**Comment by Muazzamkhan95** [comment]
@kaustavghosh06 

![image](https://user-images.githubusercontent.com/17087133/65641173-886fd700-e005-11e9-8261-bc2adfa8a8e1.png)

**Comment by kaustavghosh06** [comment]
Can you try running `npm install -g @aws-amplify/cli --unsafe-perm=true --allow` and let me know if you see any errors?

**Comment by kaustavghosh06** [comment]
@Muazzamkhan95 I was able to successfully install the CLI in windows - on powershell just right now

<img width="831" alt="Screen Shot 2019-09-25 at 2 36 28 PM" src="https://user-images.githubusercontent.com/7247658/65641541-e9fe5a00-dfa1-11e9-8916-2ca9011164aa.png">

**Comment by Muazzamkhan95** [comment]
Thanks @kaustavghosh06  these extra flags worked
![image](https://user-images.githubusercontent.com/17087133/65641615-b0136f00-e006-11e9-8f33-e4a6aae35327.png)
