### ISSUE TITLE
Amplify config and Amplify init Error ! 

### ISSUE THREAD

**Issue by Muazzamkhan95** [aws-amplify/amplify-cli#2410]
![image](https://user-images.githubusercontent.com/17087133/65642015-aa6a5900-e007-11e9-84a6-e538300de38e.png)

![image](https://user-images.githubusercontent.com/17087133/65641901-68411780-e007-11e9-8c68-6e8bbb7c8abe.png)

**Comment by kaustavghosh06** [comment]
@Muazzamkhan95 This is super weird. I've seen this issue before in one of the threads and the user re-installed the CLI using yarn - `yarn global add @aws-amplify/cli` and got rid of this error. We'll deep dive into this but in the meanwhile you can try yarn and let me know if this worked.

**Comment by Muazzamkhan95** [comment]
have a look at yarn errors
![image](https://user-images.githubusercontent.com/17087133/65642465-b9054000-e008-11e9-98c9-6791f5c74ddf.png)

**Comment by UnleashedMind** [comment]
@Muazzamkhan95 
Ignore the npm installation errors for now, and try to run the `amplify configure` and `amplify init` commands, see if they succeed. 
If not, try to run `amplify plugin list` -> `active plugins` and see if it contains `awscloudformaiton`

**Comment by Muazzamkhan95** [comment]
![image](https://user-images.githubusercontent.com/17087133/65642735-69734400-e009-11e9-9545-ec5331d17e96.png)

**Comment by Muazzamkhan95** [comment]
@UnleashedMind there is nothing like  **awscloudformation**

**Comment by UnleashedMind** [comment]
Thanks. 
Could you do the following: 
- go to C:\Users\muazz\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\node_modules 
See if you can find the plugins: packages that start with `amplify-', and see if you have `amplify-provider-awscloudformaiton`

**Comment by UnleashedMind** [comment]
then do a `amplify plugin scan`, and see if it resolves your issue. 
BTW, this is not a typical issue, but we've seen this happen on Windows.

**Comment by Muazzamkhan95** [comment]
Yes i have `amplify-provider-awscloudformaiton`
![image](https://user-images.githubusercontent.com/17087133/65643202-88bea100-e00a-11e9-8d06-7302ad7ed4bd.png)

**Comment by UnleashedMind** [comment]
great!
- do a 'amplify plugin scan`, 
- run 'amplify plugin list` -> 'active plugins` -> scroll down and see if there's a `awscloudformation`
- if yes, you are good to go
- if not, run `amplify plugin add` and paste the full path `C:\Users\muazz\AppData\Local\Yarn\Data\global\node_modules@aws-amplify\cli\node_modules\amplify-provider-awscloudformation`, see if you get an error.

**Comment by Muazzamkhan95** [comment]
after running scan there is no fix..

![image](https://user-images.githubusercontent.com/17087133/65643321-e652ed80-e00a-11e9-9454-9a641ee65a37.png)

**Comment by UnleashedMind** [comment]
How about `amplify configure`? it is also still failing?

**Comment by Muazzamkhan95** [comment]
Successfuly added Plugin.

![image](https://user-images.githubusercontent.com/17087133/65643824-24044600-e00c-11e9-8c4b-6f7c937129fb.png)

**Comment by Muazzamkhan95** [comment]
It Worked ! @UnleashedMind 

![image](https://user-images.githubusercontent.com/17087133/65643871-3bdbca00-e00c-11e9-99f2-75b98e90171e.png)

**Comment by UnleashedMind** [comment]
great!
but that's only step one. 
We need to figure about the frontend plugin issues. Please check the same for the `amplify-frontend-javascript` plugin

**Comment by Muazzamkhan95** [comment]
oohk... let me do it really quick

**Comment by Muazzamkhan95** [comment]
i have amplify-frontend-javascript in me directory..

**Comment by UnleashedMind** [comment]
great! add it manually like before, and run `amplify init` again.

**Comment by Muazzamkhan95** [comment]
I am really thankful Dear @UnleashedMind 
it worked..
i was tackling with this error for more then 6 hours :)
Thanks alot
![image](https://user-images.githubusercontent.com/17087133/65644246-303cd300-e00d-11e9-8de8-d39c3920eb02.png)

**Comment by UnleashedMind** [comment]
No problem.
Please let us know the Operating System, we need to investigate more on this.

**Comment by Muazzamkhan95** [comment]
![image](https://user-images.githubusercontent.com/17087133/65644424-a2151c80-e00d-11e9-81a4-5b67ac1d5ffc.png)

**Comment by UnleashedMind** [comment]
Thanks

**Comment by Muazzamkhan95** [comment]
@UnleashedMind can you please tell me which plugin i needed for this.
![image](https://user-images.githubusercontent.com/17087133/65645506-359c1c80-e011-11e9-83c7-6f9e4552b3ba.png)

**Comment by UnleashedMind** [comment]
try this: 

- `amplify plugin configure` -> `scannable plugin directories` -> `add` -> and paste this: `C:\Users\muazz\AppData\Local\Yarn\Data\global\node_modules@aws-amplify\cli\node_modules\`

**Comment by Muazzamkhan95** [comment]
> try this:
> 
> * `amplify plugin configure` -> `scannable plugin directories` -> `add` -> and paste this: `C:\Users\muazz\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\node_modules\`

@UnleashedMind Not worked.

**Comment by Muazzamkhan95** [comment]
these are all plugins configured.... but getting error while running amplify auth add 
![image](https://user-images.githubusercontent.com/17087133/65647208-68491380-e017-11e9-972a-2a0d8765ae15.png)

**Comment by UnleashedMind** [comment]
because the `auth` plugin is not found. 
Could you do a `amplify plugin list` and try to local `auth`?

**Comment by Muazzamkhan95** [comment]
did't understand.

**Comment by Muazzamkhan95** [comment]
![image](https://user-images.githubusercontent.com/17087133/65647862-7f890080-e019-11e9-8a2e-fcabd288a908.png)

**Comment by Muazzamkhan95** [comment]
its fixed .... thanks @UnleashedMind  for you help..

the issue was that..
on window there is some rules or something which is preventing to scan plugins so you have to add plugins manualy ...

`amplify plugin configure -> scannable plugin directories -> add -> and paste this: C:\Users\muazz\AppData\Local\Yarn\Data\global\node_modules\`

by using this,,
