### ISSUE TITLE
Team-members sharing the same dev backend

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2421]
I'm following the instructions here: 

https://aws-amplify.github.io/docs/cli-toolchain/quickstart#team-members-sharing-the-same-dev-backend

When the developer follows the instructions he is taken to the AWS console but he is logged into his account. 

I couldn't find anything in the documentation to complete the setup.

I copied the IAM user that was created when I configured my amplify account and created that for him.
 
We ended up editing the files directly in the .aws directory. 

How is this supposed to be done? Does amplify required developers to be added to the account?

**Comment by UnleashedMind** [comment]
There are two ways to do this. 
1. In the IAM console of the team's account, add an IAM user for the team member, and the team member should log into the aws using the team IAM user's credentials. Then the team member should put the credentials into the configuration files  ~/.aws/credentials and ~/.aws/config as a profile. Run `amplify configure project` on the project and select this profile for aws accesses. 

2. If an outside contributor is also working on the same project, and he needs access to the same backend, you can create a role for the contributor in the IAM. There's a detailed write up for it in our document on how this should be done: https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-roles--mfa

**Comment by aireater** [comment]
Thanks @UnleashedMind. Closing.
