### ISSUE TITLE
Odd response resolver generated.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#2422]
**Describe the bug**
I get this kind of response resolvers for some mutations when I execute **amplify push**:
![image](https://user-images.githubusercontent.com/600133/65706402-17770080-e093-11e9-9fb9-1fa6d5bd85f7.png)

Mutation successfully updates table. But nested objects which I request in mutation have NULL value.

When I replace response resolver with simple:
```
$util.toJson($context.result)
```
the problem dissapears

Also I noticed that when I execute mutation with such resolver, in a CloudWatch I see 2 simultaneous mutations was performed. First one has correct response template mapping, second one with empty result **{}**.

**Comment by SwaySway** [comment]
@lenarmazitov The duplication of this set has been fixed in the latest release.
Are you using per-field `@auth`? If you are this is to protect the subscription which you can read more about here: 
https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions

**Comment by lenarmazitov** [comment]
Sorry for closing issue, but bug still exists.

**Description**
Everything works fine for mutation if in response file *Mutation.updateUser.res.vtl:* we **do not** have string:
```
#set( $context.result.operation = "Mutation" )
```

<img width="926" alt="Screenshot 2019-10-05 at 19 39 25" src="https://user-images.githubusercontent.com/600133/66258009-be9d1b80-e7a8-11e9-9b7c-513d9559beeb.png">

But if we have then response will be:
<img width="926" alt="Screenshot 2019-10-05 at 19 42 57" src="https://user-images.githubusercontent.com/600133/66258013-cf4d9180-e7a8-11e9-9e30-276dbeb1a423.png">

In schema I'm using per field @auth directive for field **avatar** here.

**Comment by SwaySway** [comment]
@lenarmazitov That is to protect fields in the subscription as specified in the docs.
If you would like the response in the mutation you can can either subscriptions to either off or public.
```gql
type User 
    @model (subscriptions: { level: public  }) # or off
    @auth(rules: []) {
        # user fields
    }
```

**Comment by lenarmazitov** [comment]
@SwaySway thank you, I just have found it in documentation, sorry for disturbing.

https://aws-amplify.github.io/docs/cli-toolchain/graphql#per-field-with-subscriptions
