### ISSUE TITLE
add-graphql-datasource is not showing list of secrets

### ISSUE THREAD

**Issue by TrueLecter** [aws-amplify/amplify-cli#2423]
**Describe the bug**
No keys available to select

**To Reproduce**
1. Create new project, `amplify init`, `amplify add api`
2. Create RDS instance (Aurora PostgreSQL compatible with PostgreSQL 10.7, serverless)
3. Execute `amplify api add-graphql-datasource`, try to complete quiz.

**Expected behavior**
Being able to use RDS as datasource.

**Screenshots**
If I just press enter, this happens
![image](https://user-images.githubusercontent.com/5520406/65714173-45fcd780-e0a3-11e9-84c1-98f5a7975c8e.png)

**Additional context**
 - OS: Windows 10
 - `amplify -v`: 3.10.0

**Comment by UnleashedMind** [comment]
@TrueLecter 
Did you select the "serverless" mode when you create the RDS database? 
It is required to select the "serverless" mode as stated in our document.

**Comment by TrueLecter** [comment]
Yes. All clusters were created with serverless template. Role shown as serverless in console as well.

**Comment by UnleashedMind** [comment]
@TrueLecter 
Did you create the password for the "master" user? and then use the query editor to create a database in the newly created cluster? 
I will send a PR to guard against those scenarios, and print out error messages.

**Comment by TrueLecter** [comment]
Ok, so I was able to finally connect to database in Query Editor. However, not I'm getting next issue: 
![image](https://user-images.githubusercontent.com/5520406/65798068-6bf4ab80-e179-11e9-87b6-238624a006c3.png)

I was also getting an error, stating that there was no database named <master username>. After that I created database with name same as username and started receiving issue regarding unrecognized configuration parameter.

**Comment by Genkilabs** [comment]
This seems to still be the case (CLI ver. 4.12.0). Is there any info on when amplify will support Postgres?
(in fact, I did not find any documentation that it was _not_ supported beyond this issue...)

**Comment by stefanotauriello** [comment]
Is there any update, please?
