### ISSUE TITLE
Elasticsearch returns error "Elasticsearch:UserIllegalArgumentException"

### ISSUE THREAD

**Issue by udeshx** [aws-amplify/amplify-cli#2424]
**Describe the bug**
when @searchable is used in the graphql.schema file the elasticsearch cluster returns an error when queried from the app and the console.

**To Reproduce**
query the instance of elasticsearch via the graphql console or app

to solve the issue I have tried
upgrading amplify cli
upgrading elasticsearch from 6.2 to 6.8
removing @searchable and running amplify update api
adding back @ searchable and running amplify update api to re-prevision elasticsearch

**Expected behavior**
return a list of items that match the search

**Screenshots**
![appsync search not working](https://user-images.githubusercontent.com/28942294/65716526-ae1ede00-e0e2-11e9-9688-503985e91f5b.PNG)
![no indices](https://user-images.githubusercontent.com/28942294/65716527-ae1ede00-e0e2-11e9-959a-55e95e0157e0.PNG)

**Additional context**
It appears there are no indices being built could this be the issue?
The actual error is below
`"{
  "data": {
    "searchMarkets": null
  },
  "errors": [
    {
      "path": [
        "searchMarkets"
      ],
      "data": null,
      "errorType": "Elasticsearch:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Elasticsearch responded with an error: Not Found"
    }
  ]
}"`

**Comment by udeshx** [comment]
Still not fully solved
It was that the index was not being created.

![index built](https://user-images.githubusercontent.com/28942294/65718573-28516180-e0e7-11e9-9b5a-8dd26de30247.PNG)
Now the console works, but the app is still failing

![console works but app still fails](https://user-images.githubusercontent.com/28942294/65718572-28516180-e0e7-11e9-9fd3-66f29687123e.PNG)

I don't know what took so long for the index to be built.
Is there typically a time delay? 
It took about an hour.

**Comment by udeshx** [comment]
The application failing could be related to the issue linked below.
The issue could be the codegen that is creating the search query.
could be a similar issue to this
https://github.com/aws-amplify/amplify-cli/issues/2080

query SearchMarkets(

  $filter: SearchableMarketFilterInput
  $sort: SearchableMarketSortInput
  $limit: Int
  $nextToken: String
) {
  searchMarkets(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) `

**Comment by udeshx** [comment]
It appears to be working now.
I believe the cause was a delay in the creation of the indices.

**Comment by udeshx** [comment]
Since it is working I'll close the issue.
Thanks for the help

**Comment by junejie** [comment]
There's an issue the lambda attached from dynamodb.

I just add layer in lambda nad  i didn't upgrade to 6.8
This post helps me https://github.com/aws-amplify/amplify-cli/issues/2353
