### ISSUE TITLE
s3 Trigger Lambda function permission update to include s3 iam bug

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#2425]
**Describe the bug**
When adding s3 read permission to an existing s3 trigger the generated iam policy is not correct.

Notice how the Resource name is set to `arn:aws:s3:::storagetestBucketName/*`
<img width="878" alt="Screen Shot 2019-09-26 at 2 51 38 PM" src="https://user-images.githubusercontent.com/350275/65717246-d79e2200-e06e-11e9-8c2a-1816f4195e89.png">

Here is the IAM policy
```
        {
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::storagetestBucketName/*"
            ],
            "Effect": "Allow"
        }
```

It seems like it is using the newly added environment variable. This is added to my function index.js `var storageTestBucketName = process.env.STORAGE_Test_BUCKETNAME`

I will also note that the Environment Variable is not visible in the Lambda console. I only see `ENV`, `REGION` and the two others related to API access `API_TEST_GRAPHQL`...

**To Reproduce**
1. amplify function update
2. choose s3 trigger
3. Select yes to change permission and select Storage
4. Give the Storage category read access

**Expected behavior**
The policy is added correctly and the function can read from s3.

**Comment by kaustavghosh06** [comment]
@oste So the issue is that the `process.env.STORAGE_Test_BUCKETNAME` is undefined in your lambda function?

**Comment by oste** [comment]
Yes and I don't think the Ian policy is correct. I could be wrong if that's using a variable of some sort.

**Comment by kaustavghosh06** [comment]
@oste Could you please check the lates version of the CLI and test it end to end? it seems to be working for me. Please comment on this issue if you're still getting permission issues.
