### ISSUE TITLE
AWS Ampolify not generating Google Sign in parameters in awsconfiguration.json for iOS

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [aws-amplify/amplify-cli#2434]
**Describe the bug**
The amplify CLI is not asking for the iOS client id, when authentication is added to the Xcode project. The documentation link https://aws-amplify.github.io/docs/ios/authentication#google-with-cognito-identity states that it will ask for Google web client id and iOS client id. But it never asked for iOS client id. It asked for web client id and secret only.

`> $ amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Defau
lt configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email and Phone Number
 Do you want to configure advanced settings? No, I am done.
 What domain name prefix you want us to create for you? bookcase70a56be9-70a56be
9
 Enter your redirect signin URI: http://localhost:4000/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:4000/
? Do you want to add another redirect signout URI No
 Select the social providers you want to configure for your user pool: Google
  
 You've opted to allow users to authenticate via Google.  If you haven't already
, you'll need to go to https://developers.google.com/identity and create an App 
ID. 
 
 Enter your Google Web Client ID for your OAuth flow:  
 Enter your Google Web Client Secret for your OAuth flow:  
Successfully added resource bookcase70a56be9 locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
`

**To Reproduce**
1. Run amplify init inside the Xcode project
2. Run amplify add auth
3. Select Default configuration with Social Provider (Federation)

**Expected behavior**
It must ask for iOS client id for setting Google federated login.

**Screenshots**
None

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@sivaprasad-kiranum Do you see a JSON object like the one below in the `awsconfiguration.json` file?

```
GoogleSignIn = {
      Permissions: 'xxxxxxx',
      'ClientId-WebApp': xxxxxx,
}
```
