### ISSUE TITLE
@auth directive doesn't work as expected when combining {allow: owner} and {allow: private, provider: userPools}

### ISSUE THREAD

**Issue by arnaud-cortisse** [aws-amplify/amplify-cli#2436]
** Which Category is your question related to? **
Amplify Javascript --> GraphQL Transform --> Directives --> @auth

** What AWS Services are you utilizing? **
Cognito, S3, AppSync.

** Context **
A website has a marketplace you can sell products on. 
Users can create markets and add products to them. 
Users are identified via Cognito.
There is a relationship (Market <--> Products) using a named connection:
```gql
type Market
  @model
  @searchable {
  id: ID!
  name: String!
  products: [Product]
    @connection(name: "MarketProducts", sortField: "createdAt")
  owner: String
  createdAt: String
}

type Product
  @model
  ) {
  id: ID!
  description: String!
  market: Market @connection(name: "MarketProducts")
  shipped: Boolean!
  owner: String
  createdAt: String
}
```

** Expected behavior **
Here is what I would like to achieve:
1) Only the owner of a market can update / delete / create markets.
2) Only the owner of a product can update / delete / create products and associate them to a market.
3) Only identified users can see markets and products.

** Question **
How would go about it? How would you configure the @auth directives? 

** Additional notes **
Even though it seems to be a pretty common use case, I've a tried plenty of stuff and I can't seem to get it right... 
Either users could see other users' markets but not the products they contain or users could see everything but could also add products to another user's market.

** What I tried **
I tried this combination:
![image](https://user-images.githubusercontent.com/28689103/65763669-370a3980-e124-11e9-9bef-80375f37bf1f.png)
```gql
type Market
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update, delete] }
      {
        allow: private
        provider: userPools
        identityClaim: "sub"
        operations: [read]
      }
    ]
  )
  @searchable {
  id: ID!
  name: String!
  products: [Product]
    @connection(name: "MarketProducts", sortField: "createdAt")
  owner: String
  createdAt: String
}

type Product
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update, delete] }
      {
        allow: private
        provider: userPools
        identityClaim: "sub"
        operations: [read]
      }
    ]
  ) {
  id: ID!
  description: String!
  market: Market @connection(name: "MarketProducts")
  shipped: Boolean!
  owner: String
  createdAt: String
}
```
but in this case, any user can create markets or products on behalf of someone else.
2) I also tried plenty of other stuff that (I've been trying to solve this problem for hours), in my opinion, make no sense. So I won't post them here.

** Environment **
    "aws-amplify": "^1.1.40"
    "aws-amplify-react": "^2.4.4"

**Comment by attilah** [comment]
@arnaud-cortisse could you please try these auth rules on both entities:
```
@auth(
    rules: [
        { allow: owner, operations: [create, update, delete], identityClaim: "sub" }
        { allow: private, operations: [read], identityClaim: "sub" }
    ]
)
```

for ```private``` ```userPools``` is the default provider so you don't need to specify it, but since you're using ```sub``` to identify the user I'd use it across the schema.

From your requirement you're saying that "only owners can create markets". Owners of what? since you're creating a market with the authenticated user, that user will become the owner of THAT given market.

The same stands for products. If you need to enforce market ownership for products, then you need to access the products through the market type and not directly, OR you can use a pipeline resolver and first you can validate if the passed in marketId for the product is owned by the authenticated user or not. You only need these enforcements/validations for the create operations, since after creation the owner rules will be effective.

**Comment by arnaud-cortisse** [comment]
@attilah thanks for your response.

> @arnaud-cortisse could you please try these auth rules on both entities:
> 
> ```
> @auth(
>     rules: [
>         { allow: owner, operations: [create, update, delete], identityClaim: "sub" }
>         { allow: private, operations: [read], identityClaim: "sub" }
>     ]
> )
> ```
> 
> for `private` `userPools` is the default provider so you don't need to specify it, but since you're using `sub` to identify the user I'd use it across the schema.

I tried it but like you said a little further, that doesn't enforce market ownership (which I need, otherwise, anyone can pretend he or she is someone else and put products in someone else's market).

> From your requirement you're saying that "only owners can create markets". Owners of what? since you're creating a market with the authenticated user, that user will become the owner of THAT given market.

Right, that's what I expected.

> The same stands for products. If you need to enforce market ownership for products, then you need to access the products through the market type and not directly...

So, you mean something like this:

```gql
type Market
  @model
  @auth(
    rules: [
      {
        allow: owner
        operations: [create, update, delete]
        identityClaim: "sub"
      }
      { allow: private, operations: [read], identityClaim: "sub" }
    ]
  )
  @searchable {
  id: ID!
  name: String!
  products: [Product]!
  owner: String
  createdAt: String
}

type Product {
  description: String!
  market: Market
  file: S3Object!
  price: Float!
  shipped: Boolean!
  owner: String
  createdAt: String
}
```

where "Product" doesn't have a @model directive?
In this case, is it still possible auto-generate IDs for products on the server side without having to create a custom resolver?

> OR you can use a pipeline resolver and first you can validate if the passed in marketId for the product is owned by the authenticated user or not. You only need these enforcements/validations for the create operations, since after creation the owner rules will be effective.

Sounds good... though it's a shame I need to learn and write VTL for such a common use case...

Thanks again!

**Comment by attilah** [comment]
You've to create your custom resolver, but it is not that hard as it seems and CLI has support for that.

When it comes to pipeline resolvers you are not tied to VTL, you can do Lambda functions with the language of your choice as well or combine them. Currently the CLI does not have built-in support to create the pipeline resolvers, but it is something we'd like to add in the future.
