### ISSUE TITLE
How to delete a resource with amplify cli for only one environment?

### ISSUE THREAD

**Issue by cremich** [aws-amplify/amplify-cli#2437]
Hi together,

imagine i have configured one environment with the aws amplify cli (production). In the production environment i have configured a hosting resource with S3/CDN and a auth resource. Now i want to create a dev environment that only contains a auth resource.

Do i have the ability to configure those environments independent from each other? If i create a new environment via amplify add env and after that publish the stack i get the summary based on the previous created production environment:

| Category | Resource name           | Operation | Provider plugin   |
| -------- | ----------------------- | --------- | ----------------- |
| Hosting  | S3AndCloudFront         | Create    | awscloudformation |
| Auth     | auth2d58178c            | Create    | awscloudformation |

What happens if i now delete the hosting resource. Will this affect my production environment as well?

I would like to split dev and production environments to use no hosting for the dev environment. This should be used more or less for developers to use services like cognito during their local development. But i want a production (and later a staging) environment with a configured hosting resource.

Is this possible? I also asked this on [stackoverflow](https://stackoverflow.com/questions/58135371/how-to-delete-a-resource-with-amplify-cli-for-only-one-environment)

** Which Category is your question related to? **
Environments
** What AWS Services are you utilizing? **
* S3
* Cognito

** Provide additional details e.g. code snippets **

**Comment by kaustavghosh06** [comment]
@cremich Yes, this should be possible. Deleting hosting from your `dev` environment shouldn't affect your cloud resources in the `prod` environment. To manage these environments independently - like in your case, whenever you checkout an env - you should use `amplify env checkout <env-name> --restore` so that the changes of say `dev` environment do not get carried over to the environment you are checking out.

**Comment by cremich** [comment]
Hi @kaustavghosh06 
thanks for your response. I will have a deeper look into it. What i observed so far:

I added the production environment to my master branch and published the stack (containing auth and cloudfront based hosting). 

Then i create a dev branch from master and do a `amplify delete hosting`. This results in a complete deletion of the hosting stack. If i keep the dev branch isolated this is fine. But in the moment i merge the dev to master or vice versa this will cause some troubles, right?

Imagine i would merge the state of the dev branch into master this would result in losing the hosting stack in the master as well. And with that in my production environment. 

Or am i missing something here :thinking:

**Comment by kaustavghosh06** [comment]
@cremich Yes, you would have to unfortunately selectively merge the contents when merging from dev -> master if you're selectively managing these environments with a disparity in the resource types.

**Comment by AsemK** [comment]
I think hosting currently is setup on the console, so having it on multiple environment will not create multiple hosting.
In case you want this for other resources (functions, apis... etc), there is another solution that depend on modifying the cloudformation file related to the resource that you want to remove. You can add a creation condition for the resource based on the environment value {"Ref": "env"}
This solution doesn't require you to merge selectively as the other ones
example that creates a lambda function only in the _prod_ environment :
```javascript
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Lambda Function resource stack creation using Amplify CLI",
  "Parameters": {
    "env": { "Type": "String" }
  },
  "Conditions": {
    "ShouldCreate": { "Fn::Equals": [{ "Ref": "env" }, "prod"] } // condition is true when in prod environment
  },
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Condition": "ShouldCreate",  // create only when condition is true
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        // ...
      }
    },
    // ... rest of resources (add condition to all resources)
  },
  "Outputs": {
    "Name": {
      "Value": { 
        "Fn::If": ["ShouldCreate", { "Ref": "LambdaFunction" }, "NONE"] // value is NONE if resource not created
      },
      // ... rest of outputs (make all of them NONE if not resource not created)
    }
  }
}
```
