### ISSUE TITLE
Only deploy build to S3 hosting bucket

### ISSUE THREAD

**Issue by pigmanbear** [aws-amplify/amplify-cli#244]
**Is your feature request related to a problem? Please describe.**
The ability to only push changes to deployment bucket. Often times, the only thing changing is the React project and I do not need to do anything more than sync the local build folder with the hosting bucket without all of the ```amplify publish``` ceremony

**Describe the solution you'd like**
As part of the toolchain, perhaps ```amplify publish --hosting``` or ```amplify hosting publish``` and it would use the command when configuring for building (yarn build, etc.) and add update the files in the bucket. 

**Describe alternatives you've considered**
Any option allowing to push a new build to deployment bucket as part of the toolchain.

So the opposite of ```amplify serve``` it would seem

**Comment by kaustavghosh06** [comment]
@pigmanbear 

We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backward from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by kaustavghosh06** [comment]
@pigmanbear  With the latest version of the CLI, if you don't have any backend changes, we do not execute the backend push functionality and jusy build and upload the build/ directory for your frontend app. Please let me know if that's something if you were looking for.
