### ISSUE TITLE
Amplify push keeps resetting my oauth.domain in aws-exports.js

### ISSUE THREAD

**Issue by mooser** [aws-amplify/amplify-cli#2448]
If you provide a custom auth.mydomain.com for OAuth in cognito, every time you run amplify push it overwrites aws-exports.js and changes: 

```
oauth: {
   domain: auth.mydomain.com --> gets changed to . "appname-env.auth.region.amazoncognito.com"
}
```

I can't figure out where it is pulling the amazoncognito url from...

**Comment by kaustavghosh06** [comment]
@mooser Can you check your `amplify/backend/amplify-meta.json` file and see if the above domain is present there?

**Comment by mooser** [comment]
Thanks, it doesn't seem to be in amplify/backend/amplify-meta.json

I tried all the patterns I could think of for the string: 
"appname-env.auth.region.amazoncognito.com"

Stripping various parts of it out, trying to locate where it is written in the configs...  But it doesn't turn up anywhere in the project.

**Comment by sandeepsdixit** [comment]
Exactly what do I need to do in amplify-meta.json? Removing  "HostedUIDomain": "myapp-dev" gets recreated when I do amplify push. Please advise.

**Comment by kaustavghosh06** [comment]
@mooser Looks like you'd setup oAuth domain using the Amplify CLI but also modified your aws-exports.js file manually to have your custom domain. In this case the value configured in the Amplify CLI takes precedence and on a subsequent push the oAuth domain value will be replaced in the aws-exports.js file. We don't support custom-domains for oAuth from the Amplify CLI out of the box yet but we have that as an open feature-request.

**Comment by Jason-Reich** [comment]
@mooser This workaround is working for me:

index.tsx (or index.js)--

```
...

import awsConfig from "./aws-exports";

...

awsConfig.oauth.domain = `auth.mydomain.com`;
Amplify.configure(awsConfig);
```
