### ISSUE TITLE
Error: Only one resolver is allowed per field

### ISSUE THREAD

**Issue by mooser** [aws-amplify/amplify-cli#2449]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **

amplify push

** What AWS Services are you utilizing? **

appsync

** Provide additional details e.g. code snippets **

I am new to amplify.   Is it safe to say the experience of using amplify is all about finding ways to work around: "stackUpdateComplete error?" after amplify push?

I experience this error every single day during app development, and I end up having to delete everything and start over multiple times a day.  I've learned that you have to be very delicate with schema updates.  So I've been very delicate, yet the error still happens every day.  

For example, when changing a type in my schema, I've found the best way is to completely comment it out, then run a push (to hopefully delete everything) and then uncomment the type, modify it, and amplify push and hope for the best.  

Here's an example where resolvers are not being cleaned up properly and you can probably reproduce and fix it.

```
type Something {
   id: ID!
   hello: String! 
}

type HasSomething {
   id: ID!
   something: Something @connection
}
```

So I comment out "HasSomething" and amplify push to delete it.  Success (or not).
Then I uncomment it and amplify push and it fails.  

> Reason: Only one resolver is allowed per field.

> ✖ An error occurred when pushing the resources to the cloud
> 
> Resource is not in the state stackUpdateComplete
> An error occured during the push operation: Resource is not in the state stackUpdateComplete

1. Can you reproduce? 
2. Can you fix?

**Comment by kaustavghosh06** [comment]
@mooser The "One resolver per field" error/bug is a know AppSync service bug and we're actively working with the service team to get this fixed. There is already an issue opened up out here - https://github.com/aws-amplify/amplify-cli/issues/682 which we're using to track this and https://github.com/aws-amplify/amplify-cli/issues/682#issuecomment-471084364 mentions about a workaround for this.
