### ISSUE TITLE
Type definitions are missing for most modules

### ISSUE THREAD

**Issue by alexmcmanus** [aws-amplify/amplify-cli#2451]
Module `graphql-transformer-core` has typescript definitions - but in order to use it standalone, you need a bunch of other modules that do not. E.g. `graphql-dynamodb-transformer`. Given the source code is Typescript, there doesn't seem to be any reason why you wouldn't also generate type definitions for all of the modules (excepting a few modules where `allowJs` is set: amplify-cli, amplify-graphql-explorer, amplify-graphql-types-generator, amplify-ui-tests).

When you alter the `tsconfig.json` to generate type definitions, a few minor type errors emerge in the `amplify-cli` build (PR to follow).

```
import { DynamoDBModelTransformer } from 'graphql-dynamodb-transformer'
```
results in an `Could not find a declaration file for module` error on compilation.

**Expected behavior**
Published NPM packages to include type definitions, except where `allowJs` setting makes that impossible.

**Comment by renebrandel** [comment]
Closing as the related PR is merged.
