### ISSUE TITLE
Adding Custom CFN Stack for unsupported types fails

### ISSUE THREAD

**Issue by nick-town** [aws-amplify/amplify-cli#2455]
**Describe the bug**

After following the procedure described [here](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks) to add an API Gateway to an Amplify project, the `amplify push` command results in an error.

**To Reproduce**
1. Follow the process described [in the third bullet of this documentation](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks) to setup a custom category name of 'gateway' with a custom resource name of 'proxy' in an Amplify project with a successfully deployed GraphQL API, Hosted App and Lambda function.
2. Do an `amplify env checkout nickenv`, followed by `amplify push`
3. See
```bash
Current Environment: nickenv

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Gateway  | proxy           | Create    | awscloudformation |
| Function | proxyfn         | Update    | awscloudformation |
| Api      | graphz          | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, stat '...amplify/backend/gateway/proxy/src/package.json'
An error occured during the push operation: ENOENT: no such file or directory, stat '...amplify/backend/gateway/proxy/src/package.json'
```
**Expected behavior**

I expect the custom cloudformation template in the file `amplify/backend/gateway/proxy/template.json` to be pushed to the cloud.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Amplify CLI Version 3.10.0

**Comment by kaustavghosh06** [comment]
@nick-town Can you please share your `amplify/backend/backend-config.json` or `amplify/backend/amplify-meta.json` file?

**Comment by nick-town** [comment]
I worked around this by manually running the Cloudformation template using aws-cli. I had kept the files in the `amplify/backend/gateway/proxy/` directory and just removed the following entries from `amplify/backend/backend.config.json`:
```json
"gateway": {
         "proxy": {
                 "service": "APIGateway",
                 "providerPlugin": "awscloudformation",
                    "dependsOn": [
                         {
                                 "category": "function",
                                 "resourceName": "proxyfn",
                                 "attributes": [
                                         "Arn"
                                 ]
                         }
                 ]
         }
 },
```
When I added them back and did `amplify env checkout <myenv>`, followed by `amplify push`the templates were executed as I expected. Unless I made a typo previously the only difference was that I'm now on version 3.11 of the amplify-cli.

You'll notice that I got dependencies and parameter references to work too. You should perhaps document this, or warn against it, if it will be unsupported in future releases.

Thanks, you can close this now.
