### ISSUE TITLE
你们的移动开发能不能简单一点？？？？？？？？？？？？？？！！！！！！！！！！

### ISSUE THREAD

**Issue by yehuijifeng** [aws-amplify/amplify-cli#2460]
web服务器使用起来还算方便，为什么移动开发，不管ios还是android都是那么复杂的去配置证书和密钥？？？？
入门步骤这么多，我只需要一个上传“s3”的功能而已，如今已经无法正确使用“s3”。最无语的集成

**Comment by kaustavghosh06** [comment]
@yehuijifeng Could you please explain to us more of your use-cases?

**Comment by YikSanChan** [comment]
@yehuijifeng 你应该解释自己遇到的问题，尝试过的方案，以及哪个问题解决不了（提供错误信息），而不是宣泄情绪。

I recommend closing the issue as it is not constructive and without useful information.
