### ISSUE TITLE
[AppSync] Amplify codegen doesn't generate the correct queries

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#2465]
**Describe the bug**
Imagine having this graphql schema
```
type Commessa @model {
    id: ID!
    no: String!
    date: AWSDateTime!
    customer: Customer! @connection
}
```
When launching `amplify mock api` for example (or `amplify push` to commit to production), the cli generates queries, mutations and subscriptions.
But in queries, listCommessas doesn't show the connection to Customer:
```
export const listCommessas = `query ListCommessas(
  $filter: ModelCommessaFilterInput
  $limit: Int
  $nextToken: String
) {
  listCommessas(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      no
      date
    }
    nextToken
  }
}
`;
```
I have to manually add it. 
Curiously, `getCommessa` query is generated correctly. Also, during mock, if I open the AppSync Mock endpoint, I can build correct queries, so the schema is correctly parsed.

**Desktop (please complete the following information):**
 - OS: Fedora 30
- Amplify-cli: 3.10.0

**Comment by kaustavghosh06** [comment]
@artecoop What did you set your max depth level for codegen? Can you set it to 3 and see if you see this issue.

**Comment by artecoop** [comment]
@kaustavghosh06 you're right. This closes the issue. Thank you very much
