### ISSUE TITLE
IAM Role Names for @function directive are not unique enough.

### ISSUE THREAD

**Issue by daannijkamp** [aws-amplify/amplify-cli#2468]
**Describe the bug**
Automatically generated IAM Role Names for `@function` directive are not unique enough.
Will result in `AWS::IAM::Role already exists in (other) stack error` 

**To Reproduce**
1. Create a new serverless.com project
2. Give it a long service name, for example: `long-service-name-functions`
3. Create multiple functions, for example `do-something` and `get-something`
4. This will result in lambda function with the name `long-service-name-functions-prod-do-something` and `long-service-name-functions-prod-get-something`
5. Use the Lambda functions as `@function` directive
6. For example:
```
type Query {
  getSomething(email: String): String
    @function(name: "long-service-name-functions-prod-get-something")
}

type Mutation {
  doSomething(email: String): String
    @function(name: "long-service-name-functions-prod-do-something")
}

``` 
7. amplify push
8. An automatically generated IAM Role Name is created `LongServiceNameFunctionsPr-xxxxxxxxxxxxxxxxxxxxxxxxxx-production` for both functions. And will result in an `AWS::IAM::Role already exists in (other) stack` error 

**Expected behavior**
- support long prefixes in (serverless) lambda functions

**Comment by danshirley1** [comment]
Does anyone have any workarounds for this in the meantime, manual steps will do?

**Comment by babu-upcomer** [comment]
@danshirley1 We got the issue recently too. These kind of cloudformation limitations are becoming a huge blocker for Amplify in a greater extent. @SwaySway Is their any workaround?

**Comment by daannijkamp** [comment]
@danshirley1 @babu-upcomer the +/- first 27 characters of the lambda function name is used for the IAM Role Name.
The only workaround is to use shorter Lambda function names (more likely that the first 27 characters are unique)  
Don't know whether this is a limitation of Cloudformation or Amplify.

**Comment by daannijkamp** [comment]
@SwaySway Adding a hash based on the full string (for example md5) as a prefix to the simplifyName function (https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-common/src/util.ts#L16), do you think this can work?

**Comment by SwaySway** [comment]
@daannijkamp Yea it's a cloud formation limit that is 64 characters on the iam role name which is created for the lambda function.
Which is comprised of the following
- `functionName-GraphQLAPI_ID-Hash`

One option would be to remove the api id and that alone could be unique with the function name and the hash.

**Comment by SwaySway** [comment]
Closing this as the pr for this has been merged.
