### ISSUE TITLE
Use amplify codegen without setting up amplify project

### ISSUE THREAD

**Issue by wyjiao** [aws-amplify/amplify-cli#247]
**Is your feature request related to a problem? Please describe.**
We have an AppSync project with an AppSync schema set up. We want to use the 'codegen' feature to generate API code or type annotations based on a GraphQL schema and query documents. However, in order to use that, the Amplify CLI requires to set up an Amplify project, which sets up the infrastructure of deploymentBucket, cloudformation stack etc, which we already have. We want to have the amplify codegen without setting up those infrastructures.

**Describe the solution you'd like**
We setup all infrastructure, appsync schema by ourselves. We run a command like 'amplify add codegen --apiId xxxxxxxxxxxxxxxxxx', it will generate the API.ts file and queries.ts, mutations.ts files locally.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by yuth** [comment]
We will investigate how best we can support codegen without setting up the amplify project. 

How ever in the mean time you could try using  [amplify-graphql-docs-generator](https://www.npmjs.com/package/amplify-graphql-docs-generator) for generating statements and [aws-appsync-codegen](https://www.npmjs.com/package/aws-appsync-codegen) for generation of types . Both these packages have cli interfaces.

 The only thing that would be missing compared to that of amplify cli is that you will have to download the introspection schemas

**Comment by wyjiao** [comment]
Hi @yuth,

We tried using aws-appsync-codegen but it has an error for generating types for 'AWSDateTime'. We had a thread there and get the suggestion to request a feature here: 
https://github.com/awslabs/aws-appsync-codegen/issues/17

**Comment by javiertc** [comment]
The same is happening to me. I already have the project deployed in AppSync and I don't want to create a new CloudFormation template. Is there any way in Amplify cli to create a copy of the remote environment, modify it and then publish the changes.

**Comment by wyjiao** [comment]
Hi @yuth, 
Any structure including AWSDateTime would break the code-gen, for example:
`
type Data{
  localTime: AWSDateTime
}
`

**Comment by yuth** [comment]
@wyjiao thanks for reporting this. We are in the process of forking [aws-appsync-codegen](https://www.npmjs.com/package/aws-appsync-codegen) and once its forked we will add support for all AWS scalar types.

**Comment by kaustavghosh06** [comment]
Closing this issue. We currently have the ability to run the command ` 'amplify add codegen --apiId xxxxxxxxxxxxxxxxxx` to do codegen for an already provisioned GraphQL API. Also we forked the ` aws-appsync-codegen` package and have support for AWS scaler types.

**Comment by larryonoff** [comment]
It would be great reopening this issues. Because I hope that Amazon team will implement the functionality requested.

**Comment by undefobj** [comment]
@kaustavghosh06 reopening. Let's chat about implementation when I'm back in office.

**Comment by barticus** [comment]
+1 for this.
We have what I imagine is a typical dev set up of backend separate to frontend.
Backend has created the appsync implementation and has shared the schema, frontend can't generate code without creating their own separate stacks first? 
Seems like overkill.

**Comment by robotizac** [comment]
Is there any news on the feature?

**Comment by yuth** [comment]
We don't have anything to report yet. I have tagged the issue and will speak to the team to get this prioritized

**Comment by RadoAz** [comment]
Hi all! Any updates? We started to develop with 
``` "aws-amplify": "0.4.1",
    "aws-amplify-react-native": "0.2.11",
    "aws-appsync": "1.7.0",
    "aws-appsync-react": "1.2.5",
    "aws-sdk": "2.383.0",```
And now we want to update. But without setting amplify-cli, because we have backend separately done. Settings of amplify-cli made weird things with app :(

**Comment by b-nroths** [comment]
If I understand the issue correctly, I believe you can just copy the generated .graphqlconfig.yml file to your base directory.  This will allow you to run amplify codegen without setting up the project.

**Comment by jkodroff** [comment]
Assuming my understanding is correct, that basically full admin privs are required just to do codegen when all that should be required is `appsync:GetIntrospectionSchema`, and there's no obvious way to get around this requirement, this is a very serious flaw in the design of the CLI.

I find this particularly concerning because this is a tool written by AWS.  It's my feeling that if you referred this design to pretty any of your colleagues who have a decent understanding of cloud security, I believe they would raise similar concerns.

I'm not saying this to shame anyone - it's just that this flaw can put your users in a really bad position as their application matures.  I'm currently responsible for AWS infrastructure on a project and now I have to choose between allowing much broader IAM access than I am comfortable with, or telling a mobile development team that they will have to move to Apollo, which I really hope generates very similar code to Amplify, or else they will have to do significant rework.

**Comment by kaustavghosh06** [comment]
@jkodroff You could potentially limit your different teams to assume different IAM roles (With different set of policies) for more advanced scenarios and also have advanced security settings like token validation/expiration.
We have covered one scenarios out here - https://aws-amplify.github.io/docs/cli-toolchain/usage#step-by-step-guide-to-create-and-assume-an-iam-role

**Comment by jkodroff** [comment]
@kaustavghosh06 The docs above explain how to create and assume a role using the AWS CLI (which I already know how to do), but they do not seem to explain how to use that role to avoid having to set up broad permissions just to do codegen with Amplify.

Could you maybe provide some additional info on how to use an existing role?

Is there any way to use Amplify's codegen feature by itself against an existing AppSync (or other GraphQL) endpoint without granting such broad permissions and deploying actual infrastructure via CloudFormation?

**Comment by AbeEstrada** [comment]
I can't find a way to use `codegen` without setting up an Amplify project

I added a `.graphqlconfig.yml` to my base directory

```
projects:
  My AppSync App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        maxDepth: 2

```
...
```
❯ amplify configure codegen
You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```
...
```
❯ amplify add codegen --apiId xxxxxxxxxxxxxxxxxxxxxxxxxxx
You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

**Comment by kaustavghosh06** [comment]
We release support for this as a part of our CLI version 3.8.
Please take a look at Flow 5 - https://aws-amplify.github.io/docs/cli-toolchain/graphql#workflows- out here for more information around codegen without `init` flow.

**Comment by Console32** [comment]
@kaustavghosh06 The provided link is dead. could you update it so it can be found :)

**Comment by Console32** [comment]
Found it after some digging, but still does not allow amplify codegen models without a project setup. :( 
https://docs.amplify.aws/cli/graphql-transformer/codegen#workflows

**Comment by chriszirkel** [comment]
Did anyone manage to get it working without initialising a project? 

I'm using Amplify DataStore for my GraphQL api. With `amplify pull` I can generate the models, so all types that are resolved as a dynamoDB table (@model directive on type). However, I added some more queries on the Query type, but those are not generated.

Amplify generates `schema.js` file for the models, but I would additionally need to copy the `schema.json` file from by backend to the frontent project, just to get the missing queries generated. 

Why?

**Comment by ShengHow95** [comment]
@chriszirkel I believe that's because your frontend project is generating the `*.js` code from local `schema.json` or `schema.graphql` file. In order to fix this, I suppose you could actually try to use `awscli` to get the latest schema and only then you do the `amplify codegen`.

Sample `awscli` to get the latest schema: `aws appsync get-introspection-schema --api-id XXXXX --format json ./schema.json`

**Comment by chriszirkel** [comment]
> @chriszirkel I believe that's because your frontend project is generating the `*.js` code from local `schema.json` or `schema.graphql` file. In order to fix this, I suppose you could actually try to use `awscli` to get the latest schema and only then you do the `amplify codegen`.
> 
> Sample `awscli` to get the latest schema: `aws appsync get-introspection-schema --api-id XXXXX --format json ./schema.json`

Indeed that worked for **types** and **statements**. However, I still need to call `amplify pull` to get schema for DataStore and generated the **models**.

Wouldn't it be possible to have one call to `awcli appsync get-introspection-schema` to get the schema and second call to `amplify codegen` for models, statements and types?

**Comment by themse** [comment]
it's still necessary to generate `models` without `amplify pull`. Any updates or workarounds?
