### ISSUE TITLE
Amplify add api command not working 

### ISSUE THREAD

**Issue by julia-cassella** [aws-amplify/amplify-cli#2471]
I am trying to create a react app with aws aplify as the Backend. I have gone through all the set up and configurations for linking my aws account with the app. However when I try and run: 
'sudo amplify add api' I get this error: 

"TypeError: Cannot read property 'run' of undefined at service walkthrough (/usr/local/lib/node_modules/@aws-amplify/cli ...... /appSync.walkthrough.js:119) as procress.tick_callBack (internal/process/next_tick.js:68:7)

**To Reproduce**
1. Sudo npm install -g @aws-amplify/cli@latest
2. sudo amplify configure
3. sudo gem install cocoapods
4. mkdir myNewApp
5. cd myNewApp
6. sudo npx create-react-app newApp
7. cd newApp
8. sudo amplify init
9. sudo npm install --save aws-amplify
10. sudo npm install --save aws-amplify-react
11. sudo amplify add auth
12. sudo amplify push
13. sudo amplify publish
14. sudo amplify add api 
15 (a) Selected: GraphQL
     (b) Provide API name --> chose the suggested one given 
     (c) selected amazon cognito user pool for api authentication
     (d) selected no for "do you have an annotated schema"
ERROR occurs after enter

There should be more promts that follow this to create a graphQL directory and allow you to set up the APIs. 

 - OS: MacOS
 - Version 10.14.6

I have tried updating my NodeJS to the latest version (10.16.3) and I am still encountering the issue.

**Comment by kaustavghosh06** [comment]
Which CLI version are you using? And what's the error you're seeing after you hit enter?

**Comment by julia-cassella** [comment]
The error that I am getting is: "TypeError: Cannot read property 'run' of undefined at service walkthrough (/usr/local/lib/node_modules/@aws-amplify/cli ...... /appSync.walkthrough.js:119) as procress.tick_callBack (internal/process/next_tick.js:68:7)

And the CLI is the latest one, I believe it is ^3.1.0. I just installed it yesterday using sudo npm install  -g @aws-amplify/cli@latest. I also tried it with cli version 1.1.7 per someone's suggestion for a similar issue encountered with amplify add analytics command error

**Comment by kaustavghosh06** [comment]
@julia-cassella Can you check `amplify -v` to confirm the version and then a screenshot of the exact flow for adding the API? (I tried to follow the steps and wasn't able to reproduce the issue). Also, curious to know as to why you would be needing sudo for each of the amplify commands.

**Comment by yuth** [comment]
@julia-cassella are you still facing this issue? What version of Amplify CLI do you have installed? You can find the version by running `amplify -v`

**Comment by julia-cassella** [comment]
So I just reinstalled everything and it worked! None of the versions that I reinstalled changed so I really dont know what was causing the issue. And I am using amplify 3.11.0
