### ISSUE TITLE
Modifying Amplify function causes deployment error during amplify function push

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2477]
We made some small changes to an existing function to add some console.log statements.
Only console.log statements were added.

executed:
amplify function build
amplify function push

Unable to deploy function. Please see logs below.

received the following:
Parameters: [S3DeploymentRootKey, S3DeploymentBucket] must have values

As a workaround, should we remove the function and recreate?
The function has nothing to do with S3 and has no S3 related functionality.

These are the relevant logs:

UPDATE_FAILED      apimarketbox           AWS::CloudFormation::Stack Wed Oct 02 2019 10:48:06 GMT-0400 (Eastern Daylight Time) Parameters: [S3DeploymentRootKey, S3DeploymentBucket] must have values
UPDATE_FAILED      functionchangeuserrole AWS::CloudFormation::Stack Wed Oct 02 2019 10:48:06 GMT-0400 (Eastern Daylight Time) Resource update cancelled
...
UPDATE_FAILED               functionstripechargecard     AWS::CloudFormation::Stack Wed Oct 02 2019 10:48:17 GMT-0400 (Eastern Daylight Time) Resource update cancelled

Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete

**Comment by kaustavghosh06** [comment]
Can you try doing an ‘amplify push’ instead?

**Comment by blairtaylor** [comment]
amplify push successfully deployed the modified function. Thank you.
