### ISSUE TITLE
Angular Codegen not generating Queries that return Arrays as an Array object.

### ISSUE THREAD

**Issue by jasontripleps** [aws-amplify/amplify-cli#2478]
**Describe the bug**
When running codegen on a custom Query, it generates the type of the function as QueryObject, rather than Array<QueryObject>

**To Reproduce**

1. Create a new Angular project with Amplify, with api and a function.
2. Add a new Query like below:
```
type Query {
	testQuery:[QueryObject] @function(name: "testfunction-${env}") 
}

type QueryObject {
	test: String
}
```
3. Perform Angular codegen

**Expected behavior**
function would generate as
`async TestQuery(): Promise<Array<TestQueryQuery>>`

**Actual behavior**
Function generates as `async TestQuery(): Promise<TestQueryQuery>`

**Comment by jasontripleps** [comment]
Alternatively it could be that the type is supposed to generate as `TestQueryQuery = Array<{test: string}>` and not `TestQueryQuery = {test: string}`

**Comment by hoegertn** [comment]
Anything new here? This breaks a lot of code and needs ugly code like `(result as unknown as any[])`

**Comment by jasontripleps** [comment]
> Anything new here? This breaks a lot of code and needs ugly code like `(result as unknown as any[])`

My workaround currently is to have a field where the api is used that's (for example) a: Array<MyType> then to just do a = await api.testQuery() (testQuery return type in this case would be declared as Promise<MyType>) and add a @ts-ignore above this line. It's nasty, but it allows you to use the typescript autocomplete wherever you're using variable 'a'.
