### ISSUE TITLE
Confusion regarding additional permissions granted to lambda: API category

### ISSUE THREAD

**Issue by ambientlight** [aws-amplify/amplify-cli#2479]
**Which Category is your question related to?**
amplify-category-function

**What AWS Services are you utilizing?**
Lambda to add execution calling graphql API

**Provide additional details**
When adding additional permissions to lambda to call Graphql API, it is confusing that **operation** create actually is what adds `appsync:GraphQL` action to execution policy statement. I messed it up originally specifying read, since all I needed is to execute queries and not mutations in my lambda but it has no relation to the question asked, since the question actually asks about what to allow in manipulating appsynch itself.

```
? Please select the Lambda Function you would want to update lambdarelay
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category api
Api category has a resource called coreapi
? Select the operations you want to permit for coreapi
 ◯ create
❯◉ read
 ◯ update
 ◯ delete
```

Specifically at:
https://github.com/aws-amplify/amplify-cli/blob/46bcab20e2a9cebb6b68f2b3298f88cf9dd49e47/packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js#L630-L679

It might make sense to rename those, given that these permissions mainly allow to manipulate appsync function/resolvers/etc themselves. [awsappsync-resources-for-iam-policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsappsync.html#awsappsync-resources-for-iam-policies)

**Comment by SwaySway** [comment]
@ambientlight Are you looking at giving crud operations on the GrpahqlAPI to a function?

**Comment by ambientlight** [comment]
@SwaySway: everything works for me as expected I have `'appsync:GraphQL` in execution policy, just the confusing part is that in 'appsync:GraphQL' action is under `create` operation in CLI selector

**Comment by kaustavghosh06** [comment]
@ambientlight Yes, we have this behavior currently, but we're looking to scope these policies down based on the GraphQL API type - or at the least based on Mutations/Queries/Subscriptions.

**Comment by mruzekw** [comment]
Just ran into this as well. Just needed to be able to `read`, but found I also needed to enable `create`. I would expect any of the CRUD permissions to add `appsync:GraphQL`.

**Comment by josefaidt** [comment]
Closing as this has since been completed. To generate GraphQL permissions instead of CRUD permissions please refer to [generateGraphQLPermissions](https://docs.amplify.aws/cli/reference/feature-flags/#generateGraphQLPermissions) feature flag
