### ISSUE TITLE
Adding @auth with rules but without [] silently does not do anything

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#248]
Was trying to add @auth to one of my models and ended up doing the following: 

`@auth(rules: {allow: owner})`

Running gql-compile showed everything went successfully when in fact the resolvers were not updated appropriately to enforce the auth rule. 

After investigation and re-reading the documentation, all I had to do was add [] as your documentation states like this: 

`@auth(rules: [{allow: owner}])`

Then everything worked as expected. 

Would have been nice if the compiler detected this and errored out. Would have saved me some time. Or perhaps was smart enough so that if rules is set to an object then it would interpret that as an array with one object in it. 

Running 0.1.27 on OSX.

**Comment by mikeparisstuff** [comment]
@hisham This is surprising as it should be getting caught by the GraphQL validation functions. I will look into this and figure out whats going on.

**Comment by SwaySway** [comment]
@hisham Are you still experiencing this issue?

**Comment by hisham** [comment]
I just tested it like so: 

```
type HelloModel @model @auth(rules: { allow: owner }) {
  id: ID
}
```

Running `amplify api gql-compile` returns: 

`TypeError: rules is not iterable`

So at least now it shows error. Whether you want to support the case of one rule that is not iterative is up to you. It would be syntactic sugar at this point so I"d classify this request now as an enhancement not a bug.

**Comment by SwaySway** [comment]
Closing this issue.
Should there be more interest in adding single rules not in a list we can open a enhancement for that.
