### ISSUE TITLE
Inform users of amplify-cli when there is an update available

### ISSUE THREAD

**Issue by daannijkamp** [aws-amplify/amplify-cli#2488]
**Is your feature request related to a problem? Please describe.**
When there is a new version of the Amplify CLI, I will not be notified.
Other Packages, for example [npm-check-updates](https://www.npmjs.com/package/npm-check-updates), give me a notification when a new version is available. For this they use [update-notifier](https://www.npmjs.com/package/update-notifier).

**Describe the solution you'd like**
I would like to see the update-notifier implemented.

**Describe alternatives you've considered**
Based on the weekly 4+ million downloads, [update-notifier](https://www.npmjs.com/package/update-notifier) seems to be a good standard.

**Additional context**
[Link](https://github.com/tjunnone/npm-check-updates/blob/master/bin/ncu#L14) to example code how [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) uses [update-notifier](https://www.npmjs.com/package/update-notifier)

**Comment by ericclemmons** [comment]
As an alternative, ZEIT has [update-check][2] which was a result of some issues [they've detailed in a twitter thread][1].

It is similar in size, has [~200k weekly downloads][4], and may be worth comparing to, or as a potential alternative _if_ we experience any [similar issues][1] with `update-notifier`.

[1]: https://twitter.com/notquiteleo/status/983193273224200192
[2]: https://github.com/zeit/update-check
[3]: https://github.com/zeit/now/blob/d8935cf121afe44e4e8c895ab327c9b74403e4e8/packages/now-cli/src/index.js#L120-L154
[4]: https://www.npmjs.com/package/update-check

**Comment by ericclemmons** [comment]
Closed via #4046!
