### ISSUE TITLE
How to validate or modify an input before a mutation?

### ISSUE THREAD

**Issue by kevinwolfdev** [aws-amplify/amplify-cli#2499]
**Which Category is your question related to?**
api

**What AWS Services are you utilizing?**
api, function

**Provide additional details e.g. code snippets**
I am trying to create a RSS reader, which has the following type:

```graphql
type Feed @model {
  id: ID
  url: String!
  title: String!
  description: String
}
```

On my UI, I want the user to enter a URL, which will check if it is a valid RSS URL and then generate a `Feed` object by using [`rss-parser`](https://npm.im/rss-parser)

The problem I have is that I am currently doing that validation on the frontend (which may lead to unintended behaviour by manually calling `createFeed` or `updateFeed` mutations with wrong data).

I am wondering if there is any way to validate and build the object before calling `createFeedMutation`, so maybe changing `createFeed(input: CreateFeedInput!)` to `createFeed(url: String!)` and then calling `PutItem` operation from DynamoDB.

A solution I came up with was to avoid automatically generating `createFeed` and `updateFeed` resolvers and instead chain two `@function`s:

```graphql
type Feed @model(mutations: null) {
  id: ID
  url: String!
  title: String!
  description: String
}

type Mutation {
  createFeed(url: String!): Feed
    @function(name: "GenerateFeed-${env}")
    @function(name: "CreateFeed-${env}")
  updateFeed(url: String!): Feed
    @function(name: "GenerateFeed-${env}")
    @function(name: "UpdateFeed-${env}")
}
```

And the `GenerateFeed` function:

```js
const Parser = require('rss-parser')

exports.handler = async function generateFeed(event, context) {
  try {
    const parser = new Parser()

    const { feedUrl: url, title, description } = await parser.parseURL(
      event.arguments.url
    )

    context.succeed({ url, title, description })
  } catch (err) {
    context.fail('Please enter a valid RSS URL')
  }
}
```

But I got stuck on that because:

1. When I create the `CreateFeed` and `UpdateFeed` functions through `amplify add function` and I'm asked to choose what other resources I want to access, the `Feed` table generated by `@model` doesn't appear under the `Storage` category, so I don't know how to get the table name.
2. I don't know if that is going to work with `amplify mock`, because I also don't know if Amplify also mocks DynamoDB calls within lambda resolvers.

This might be related with #1055.

**Comment by undefobj** [comment]
This could potentially be addressed with upcoming improvements to `@model` mutation input types. See https://github.com/aws-amplify/amplify-cli/issues/2429

cc @attilah

**Comment by lucido-apps** [comment]
@kevinwolfdev Any updates on this? would you share the solution you eventually implemented? Thanks!

**Comment by lucido-apps** [comment]
@kevinwolfdev Another question. You said above that:

> A solution I came up with was to avoid automatically generating createFeed and updateFeed resolvers and instead chain two `@function`s:

When I try to do this, I get the following error from `amplify` cli:

`Object type extension 'Mutation' cannot redeclare field createFeed`

How did you get past this error?

Thanks!

**Comment by viczam** [comment]
You can overwrite resolvers using vtl   
\- https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers  
\- https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-programming-guide.html

**Comment by lucido-apps** [comment]
@viczam I know I can overwrite resolvers using `VTL`, but I was trying to overwrite them using `Lambda` resolvers. There's a subsection in the docs I overlooked though, I'll check it out now: https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-resolver-that-targets-an-aws-lambda-function

**Comment by GeorgeBellTMH** [comment]
I would love an @validation on tables, which would create a lambda function Validate(TableName, CreateOrUpdate, InputValues):ValidationResult

This way you could write your own validation against multiple fields at a time, you could even potentially return a ValidationResult that was [{field, value, isValidBool, reason}], so some fields could be updated and others wouldn't be...with the results returned to the mutation caller.

**Comment by GeorgeBellTMH** [comment]
Optionally an @validation on fields could allow for only selected fields being passed to the lambda validate function, which would allow for performance improvements on large objects.
