### ISSUE TITLE
GraphQL: how to avoid orphanage

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#2501]
Hello all!

Imagine to have 2 types, one referring to another via the `@connection` keyword. I can create and update whatever I want, but I can also delete, which create this question:

can I **_block_** deletion of **_connected_** items?

Similar to SQL with delete on the foreign key.
This will keep consistency on my data.

**Comment by SwaySway** [comment]
@artecoop The connected item shouldn't be deleted.
(e.g. delete post comments under post will still exist and point to null)
Is there a mutation operation that is deleting the connected item for you?

**Comment by kennyrulez** [comment]
Hello @SwaySway, I'm writing with my personal account and not the company one to not let you wait until Monday to have my answer.

imagine having a simple one-to-many relationship
```
type Foo @model {
    id: ID!
    name: String!
    bars: [Bar] @connection(name : "FooBars")
}

type Bar @model {
    id: ID!
    count: Int!
    foo: Foo @connection(name: "FooBars")
}
```

Easy peasy. Amplify will generate standard mutations for both models.
Add some data, and when adding a `Bar` add the relation to Foo, so the one-to-many is complete.

Now call the `deleteBar ` mutation with some Id in the `Bar` table. I'm able to delete, making the state of the  relative `Foo`  record inconsistent.

**Comment by yuth** [comment]
@kavengagne, 

> Now call the `deleteBar ` mutation using some Id taken from the `Bar` table. I'm able to delete, making the state of the relative `Foo` record inconsistent.

could you elaborate what you mean by relative state of `Foo` record inconsistent. Do you see the deleted `Bar` item when you run the following query?
```gql
query ListFoo {
  listFoos {
    items {
      id
      name
      bars {
        items {
          id
          count
        }
      }
    }
  }
}
```

**Comment by artecoop** [comment]
Thans @yuth for your response.

I forgot to mention, and I'm very sorry for, that **connections are non nullable**. So if I delete the bar, the ListFoo query does not return nothing, both on my app or in the mock endpoint.
If I check the errors, I got: "Cannot return null for non-nullable field Foo.bar".

This is why I say it's inconsitent: I actually can delete a record that can be referenced as exernal key for some other record in other tables without a warning.

**Comment by yuth** [comment]
@artecoop If you define your schema where `bars` are non-nullable, then the GraphQL validation is going to fail like you described in your previous comment.

Amplify generated resolvers won't be handling this use case as this is business logic and the possible solution to this might depend your use case.

**Comment by artecoop** [comment]
@yuth, man this sucks. And somewhat feels incomplete: I have a validation for not forget to add a field when using the create mutation, but nothing to help when it's time to delete. This adds complexity to user code, yet not removing the possibility of bug. Shame
