### ISSUE TITLE
@searchable or condition not working as expected

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-cli#2506]
**Describe the bug**
I have a simple schema like so:

```
type Video @model @searchable {
  title: String
  tags: [String]
}
```

From the front end, I am submitting a GraphQL query with the following variables

```
            searchVideos({
              variables: {
                filter: {
                  title: { match: e.target.value }
                }
              }
            });
```

This query works and returns the expected results. So does this one:

```
            searchVideos({
              variables: {
                filter: {
                  tags: { match: e.target.value }
                }
              }
            });
```

As soon as I try to combine both of them into one query with an `or` condition, the query suddenly returns no results

```
          searchVideos({
              variables: {
                filter: {
                  title: { match: e.target.value },
                  or: [{ tags: { match: e.target.value } }]
                }
              }
            });
```

**Expected behavior**
Results are returns if either field matches as described at https://aws-amplify.github.io/docs/cli-toolchain/graphql#searchable

**Additional context**
Using amplify-cli 3.10.0

**Comment by TrueLecter** [comment]
The structure of `or` filter is the following: 
```
filter: {
    or: [
         field1: condition1,
         field2: condition2,
         ....
    ]
}
```

So if you want to have both `filter` and `tags` fields to be in `or` statement, your request should be changed to following:
```
searchVideos({
  variables: {
    filter: {
      or: [
        title: { match: e.target.value },
        tags: { match: e.target.value }
      ]
    }
  }
});
```

**Comment by davekiss** [comment]
Ah, that's the missing ticket – documentation tripped me up. Thanks!
