### ISSUE TITLE
Looks very promising. Flutter/Dart support needed

### ISSUE THREAD

**Issue by mzuniga84** [aws-amplify/amplify-cli#251]
Would love to see support for other lambda runtimes as well as code generation for flutter/dart

**Comment by rhokstar** [comment]
In regards to at least solutioning for identity, there's the Unofficial Amazon Cognito Identity Provider Dart SDK: [https://github.com/jonsaw/amazon-cognito-identity-dart](url)

**Comment by Katekko** [comment]
Waiting for Flutter!

**Comment by haverchuck** [comment]
@mzuniga84 @rhokstar @Katekko We just released a [developer preview of amplify-flutter](https://aws.amazon.com/about-aws/whats-new/2020/08/amplify-flutter-now-available-as-developer-preview/).  It is not yet full featured and only has a few categories, but it's ready for a little test drive.

**Comment by kaustavghosh06** [comment]
@mzuniga84 Please follow the Flutter repo - https://github.com/aws-amplify/amplify-flutter for more updates and enhancements :) Closing this issue in the CLI repo for now.
