### ISSUE TITLE
Breaking Change with @auth?

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#2513]
**Describe the bug**
Prior to the latest update, field-level auth rules worked for mutations. Now they don't seem to.

For example

````
type User 
  @model 
  @auth(rules: [
    {allow: owner, ownerField: "id", operations: [update, create]},
    {allow: groups, groups: ["Admins"], operations: [update, create]}
  ])
{
  id: ID!
  name: String
  pendingBalance: Int @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [update, create, read]},
    {allow: owner, ownerField: "id", operations: [read]},
  ])
}
````

Then with the mutation:
````
mutation UpdateUser($input: UpdateUserInput!) {
      updateUser(input: $input) {
        id
       name
       pendingBalance
      }
    }
````

In that instance, pendingBalance is always null on the returned updateUser.

Prior to updating, I would get the pendingBalanced returned regardless of whether the user was in the Admins groups

**Comment by SwaySway** [comment]
@CodySwannGT This changed was added to protect fields in the subscription.
Should you need the response in the mutation you can set the field model subscription level to either off or public
```gql
@model (subscriptions: { level: public })
```
Docs: https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions

**Comment by yuth** [comment]
Feel free to comment if you still have questions about this.
