### ISSUE TITLE
How to keep revision history of a @versioned model?

### ISSUE THREAD

**Issue by andrew-aernos** [aws-amplify/amplify-cli#2515]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
GraphQL transform directive `@versioned`

** What AWS Services are you utilizing? **
AWS Amplify, DynamoDB, Cloudformation 

** Provide additional details e.g. code snippets **
I'm trying `@versioned` directive to keep data consistent in a multi-user/editor app, I'm wondering if it is feasible to **store each change as new rows** instead of overwriting an existing row with the correct expectedVersion.

The closest thing I came across is this best practice doc on sort keys in DynamoDB [Using Sort Keys for Version Control](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html). How might I implement the custom resolver and/or custom cloudformation to provision the DynamoDB datasource for this use case?

**Comment by yuth** [comment]
Amplify CLI `@versioned ` directives intended use is to provide a mechanism to handle conflict resolution, and it does not provide support to storing different revisions of the record. We have RFC https://github.com/aws-amplify/amplify-cli/issues/1055, which has possible ways to implement auditing. Please feel free to leave a comment there so we take your use case into consideration when we build the pipeline resolvers.
