### ISSUE TITLE
More debug information when receiving Cannot read property XXX of undefined

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#2521]
There are a number of errors in recent days Cannot read property 'XXX' of undefined when pushing...where XXX is often a common thing - like request, length, etc. making it impossible to figure out what the issue is quickly - especially for newbies to Amplify.

To help debug these issues it would be helpful to get a more detailed message - either saying which template is wrong, or which file the error is occurring in, and ideally the line number where it is expected (or that is undefined)...this will help us manually update our files if necessary, and increase the ease of explaining defects to the project team.

**Comment by josefaidt** [comment]
Closing due to recent efforts to improve and consolidate error messaging.
