### ISSUE TITLE
Unable to add 'auth' feature

### ISSUE THREAD

**Issue by antypko** [aws-amplify/amplify-cli#2522]
**Describe the bug**
Having least possible IAM permissions it is not possible to add 'auth' resources to amplify.

**To Reproduce**

1. Start adding permissions which listed in errors during `amplify add auth` command.
Set of Cognito related permissions required for adding default amplify auth:
`"Effect": "Allow",
 "Action": [
                "cognito-idp:DeleteUserPool",
                "iam:DeleteRolePolicy",
                "cognito-idp:CreateUserPoolClient",
                "cognito-idp:DeleteUserPoolClient",
                "cognito-identity:SetIdentityPoolRoles",
                "cognito-idp:CreateUserPool",
                "cognito-identity:CreateIdentityPool",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "cognito-identity:DeleteIdentityPool"
 ],
 "Resource": "*"`
2. Launch `amplify add auth` check default config without Federation
4. See error "Internal Failure"

**Expected behavior**
Either auth provider is added or there is an error that shows what additional permissions you need.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Comment by josefaidt** [comment]
Closing due to age and inactivity. @antypko I know it has been quite some time since this was originally opened. If you are still experiencing this issue please reply back to this thread and we can re-open to investigate further 🙂
