### ISSUE TITLE
Amplify Add Auth command does not provision needed permission in IAM

### ISSUE THREAD

**Issue by ashika01** [aws-amplify/amplify-cli#2525]
**Describe the bug**
After configuring auth using `amplify add auth` for federated sign in, there is an error on the console.
![Screen Shot 2019-10-08 at 9 26 43 AM](https://user-images.githubusercontent.com/35131273/66414198-c843a080-e9ad-11e9-8318-7ef326617fba.png)
Going into aws console and editing IAM roles' permission solves the problem.

**To Reproduce**
1. create a basic react app and go to its root directory
2. run `amplify init`
3. then do `amplify add auth`
4. I am using manual configuration option and the configuration looks like this.
<img width="1425" alt="Screen Shot 2019-10-08 at 9 13 50 AM" src="https://user-images.githubusercontent.com/35131273/66413882-2328c800-e9ad-11e9-8568-c57c50a7fe92.png">

Similarly google was also configured and got a message saying `Successfully added resource`
5. then run `amplify push` which was successful as well.

**Expected behavior**
Expected `amplify add auth` to create proper permissions for us.

**Desktop (please complete the following information):**
 - OS: macOS mojave (10.14.6)
 - Browser: Chrome
 - Version: 77

**Comment by kaustavghosh06** [comment]
Do you see the Error as a guest or authenticated user?

**Comment by ashika01** [comment]
As an auth user.

**Comment by kaustavghosh06** [comment]
@ashika01 Could you please use the latst version of the CLI? I tested the flow mentioned above with it (v 3.17.0) and was able to make auth and unauth calls to access AWS resources using Amplify JS. Please reply on this thread if you're still seeing this.
