### ISSUE TITLE
Can only use alphanumerics in api resources added with Amplify cli

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#2526]
Hello, if you try `amplify add api` and you specify `/something_somemthing` as the path, it will fail claiming it only takes alphanumerics. That's not the reality in API Gateway though. Is there a reason Amplify does not accept underscores for example in api paths?

**Comment by rawadrifai** [comment]
btw - I was able to manually change it.. it's just the cli that prevents underscores.

**Comment by kaustavghosh06** [comment]
@rawadrifai Yeah, we use the path name in various Cloudformation resources which do not allow alphanumeric characters. We would have to refactor our Cloudformation templates to allow this behavior.

**Comment by renebrandel** [comment]
Thank you for raising this issue! Given that this enhancement hasn't gotten much traction, we're going to be closing it for now. If more people are running into this, we're more than happy to re-open the issue.
