### ISSUE TITLE
Hosting Issue on the Chrome Browser

### ISSUE THREAD

**Issue by MattWlodarski** [aws-amplify/amplify-cli#2528]
**Describe the bug**
When I publish an app update with amplify publish --invalidateCloudFront I do see the update on Mozilla and Chrome if I navigate to the website with the cloud front domain name. However, if I navigate to the website using my custom domain name (I created through route 53), chrome does not pull up the updated version while mozilla does.

**To Reproduce**
1. Run amplify publish --invalidateCloudFront
2. Wait for the update to complete and load data to the edge locations
3. Refresh browsers to see if the new version is presented on Chrome and Mozilla using a custom domain name (not the cloud front domain)

**Expected behavior**
Update is published then viewable after refreshing the webpage on both Chrome and Mozilla using a custom domain name.

**Comment by jkeys-ecg-nmsu** [comment]
Can you try running it this way also?

Open DevTools in Chrome, navigate to Network, toggle `Disable cache`. Then re-run your website in Chrome and see if it pulls your updated website. 

This is a problem we are also experiencing and don't yet have a global solution outside of forcing a refresh of the page on the client whenever we publish.

**Comment by MattWlodarski** [comment]
Well I just woke up this morning and refreshed the chrome webpage and now it is showing the new version. For some reason it took chrome a lot longer to grab the new files.

**Comment by UnleashedMind** [comment]
This seems to be about Chrome cache behavior, you can probably google how chrome caches works and how it caches DNS records.
