### ISSUE TITLE
Add summary of changes to each category when `amplify status` reports a category has been updated

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#2532]
**Is your feature request related to a problem? Please describe.**
Sometimes I will checkout a branch, pull changes, initiate an environment with `amplify init`, use an existing (expected) environment. Then I run `amplify status`, and oftentimes the API category will be in the Update state.

**Describe the solution you'd like**
I would like the CLI to record changes to categories so these changes can be reviewed from the CLI before doing an `amplify push`. Something simple like:

```
| Category | Resource name                     | Operation | Provider plugin   |
| -------- | --------------------------------- | --------- | ----------------- |
| Api      | my-api-name                      | Update    | awscloudformation |
  *modifications detected:  
      --schema.graphql has been modified
      --Foo.req.vtl (custom resolver) has been modified
```

**Describe alternatives you've considered**
Run `amplify env pull [env-name] --restore` after every checkout, which seems to restore the local Amplify config to match the cloud as you would expect to already be the case upon checking out a git branch, running amplify init, and choosing an existing environment.

But I'd rather understand why it's giving me an Update operation when I expect a No Change.

**Comment by josefaidt** [comment]
Hey @jkeys-ecg-nmsu :wave: we can now view granular resource modifications using `amplify status -v`! Closing this issue for now, however if you feel this does not quite cover your use case please feel free to respond to this issue and we can re-open to investigate further 🙂
