### ISSUE TITLE
I'd like to get Amplify auth username on Amplify function with Amplify REST API.

### ISSUE THREAD

**Issue by hi120ki** [aws-amplify/amplify-cli#2534]
This is future request of Amplify REST API authorisation.

I'd like to get Cognito (Amplify auth) username on Amplify function with Amplify REST API.
(A logged-in user call my api, I'd like to get this user's username on Lambda.)

First, I created Amplify auth, and created Amplify REST API.
(function type > Serverless framework with express.js)
(Restrict API access > Authenticated users only)

I'd like to get Cognito username on Amplify function, but I can't get property related with Cognito username on Lambda function.

(This is my lambda code. I think I can get username from "req" property, but I can't.)

```javascript
app.post("/test", function(req, res) {
  ...
```

Maybe Amplify REST API's "Restrict API access" is configured by IAM Permissions with Cognito.
<https://docs.aws.amazon.com/apigateway/latest/developerguide/permissions.html>
I think this is why I can't get username on Lambda.

An alternative solution is using "Control Access to a REST API Using Amazon Cognito User Pools as Authorizer".
<https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html>

Will you support this way?

Getting username who call API is necessary to build secure system.
I'm waiting for your great support. Thank you.

**Comment by jkeys-ecg-nmsu** [comment]
Hey @hi120ki, since you're talking about authenticated users, you should be able to get away with something like this:

`
import { Auth} from 'aws-amplify';

  //inside some async function, AFTER the user has authenticated with Cognito
  const tokens = await Auth.currentSession();
  const userName = tokens.getIdToken().payload['cognito:username'];
`

Let me know if that is helpful.

**Comment by elorzafe** [comment]
@hi120ki what if you send the JWT on the body of the request and then validate the token on your function and extract the username?

**Comment by hi120ki** [comment]
Thank you for answering my question.

https://aws-amplify.github.io/docs/js/api#cognito-user-pools-authorization
I read this document, and have already tried to set JWT token into header, but this causes 403 error. (API Gateway blocked API call).

To do this, I have to set  "custom authorizer" to API Gateway.
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html

But, today's amplify-cli may not support to set this.

**Comment by yuth** [comment]
I am adding this to our backlog, once the product team prioritizes this we will work on this issue.

**Comment by jkeys-ecg-nmsu** [comment]
@hi120ki does the preflight request return 200?

**Comment by hi120ki** [comment]
@jkeys-ecg-nmsu Yes, OPTIONS request returns 200. But POST request returns 403.

**Comment by AlaDouagi** [comment]
@yuth is retrieving user data on back-end side (that made a request) still not possible with Amplify?
I'm concerned about many security flaws with the app that I'm currently working because of this feature lack...

**Comment by pnewhook** [comment]
This seems strongly related to #3390. I'm concerned the approach suggested above of passing username from the client would be a huge security hole.
Manually configuring a custom authorizer as @hi120ki suggests might be a good first step, but we need the CLI to not overwrite our configuration on every `amplify push/publish`

**Comment by josefaidt** [comment]
Hey @hi120ki :wave: as @pnewhook pointed out this is related to the feature request: https://github.com/aws-amplify/amplify-category-api/issues/345

In the meantime we can leverage a [REST API override](https://docs.amplify.aws/cli/restapi/override/#add-a-cognito-user-pool-authorizer-to-your-rest-api) to create and attach a Cognito authorizer to ultimately retrieve values such as `username` in our Lambda's:

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
export async function handler(event) {
  console.log(`EVENT: ${JSON.stringify(event)}`)

  const { claims } = event.requestContext.authorizer
  return {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': '*',
    },
    body: JSON.stringify(`Hello, ${claims['cognito:username']}!`),
  }
}
```

Closing in favor of tracking https://github.com/aws-amplify/amplify-category-api/issues/345, please subscribe to the linked issue for further updates 🙂
