### ISSUE TITLE
Custom mutation @function not included in AppSync IAM policy 

### ISSUE THREAD

**Issue by warrenmcquinn** [aws-amplify/amplify-cli#2540]
**Describe the bug**
Adding custom mutations to a GraphQL schema does not effect proper IAM policy.  For example, I have a custom @function mutation called `deleteItem` which is supposed to be accessible via @aws_iam:

```
type Mutation {
      deleteItem(itemId: String): String @function(name: "functions-${env}") @aws_iam
}
```

However, when the API is pushed, the generated IAM auth policy for `appsync:GraphQL` **does not include** the following line:

```
"arn:aws:appsync:{region}:{account_id}:apis/{api_id}/types/Mutation/fields/deleteItem",
``` 

Thus I am unable to make an authenticated request to AppSync for that specific mutation. As a workaround, I edit the IAM policy every time I push the API.

Perhaps this is an oversight because `type Mutation` isn't a `@model` and thus cannot use the `@auth` directive? If so, what is the best practice to ensure that this custom function is accessible & secure?

**Expected behavior**
IAM policy enabling custom mutation access should be included in auth policy.

**Comment by warrenmcquinn** [comment]
Digging into the codebase: [makeIAMPolicyForRole](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-auth-transformer/src/resources.ts#L1005) is called directly via `ModelAuthTransformer.ts`, so it would appear that I would need to ensure that these `@function`s are defined under a type that use the `@model` transform.

**Comment by warrenmcquinn** [comment]
Can confirm that moving `@function` field definitions to be under `@model` types allows for the proper authentication via IAM policy generated by `makeIAMPolicyForRole`.

It's not perfectly granular authentication though -- the generated policy uses a wildcard like this:
```
 'arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${apiId}/types/${typeName}/*',
```

The codebase also seems unaware of this use-case, as evidenced by the comment [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-auth-transformer/src/resources.ts#L1010) which is contradicted by the case handled by the `else` block -- the case pertaining directly to this issue.

Perhaps we can meet in the middle here and work toward some specific IAM policy roles for these `@functions`?

**Comment by warrenmcquinn** [comment]
Just did some testing and hit a snag. 

Adding `@function` fields to my `@model` creates unwanted behavior, because the auto-generated GraphQL queries for the model define the `@function` field as something to be returned. This leads to undesired executions of the `@function` lambda handler.

So, I'm stuck. 

Either I forego auto-generated GraphQL queries and maintain everything manually, or I manually edit the IAM policy to allow execution of custom Mutations.

**Comment by yuth** [comment]
`@aws_iam` directive is a pass through to AppSync service. Amplify CLI generate policies for IAM only when `@auth` directive is used. In your case since you are adding mutation directly, you will have to use custom stack and add policy in your `<proj-root>/amplify/backend/api/<api-name>/stacks/CustomResources.json` like this. I am allowing authRole to access the mutation in the example below 
```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "An auto-generated nested stack.",
    "Metadata": {},
    "Parameters": {
        "AppSyncApiId": {
            "Type": "String",
            "Description": "The id of the AppSync API associated with this project."
        },
        "AppSyncApiName": {
            "Type": "String",
            "Description": "The name of the AppSync API",
            "Default": "AppSyncSimpleTransform"
        },
        "env": {
            "Type": "String",
            "Description": "The environment name. e.g. Dev, Test, or Production",
            "Default": "NONE"
        },
        "S3DeploymentBucket": {
            "Type": "String",
            "Description": "The S3 bucket containing all deployment assets for the project."
				},
				"authRoleName": {
					"Type": "String"
				},
        "S3DeploymentRootKey": {
            "Type": "String",
            "Description": "An S3 key relative to the S3DeploymentBucket that points to the root\nof the deployment directory."
        }
    },
    "Resources": {
        "AuthRolePolicy": {
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "appsync-authrole-policy",
                "Roles": [
                    {
                        "Ref": "authRoleName"
                    }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": ["appsync:GraphQL"],
                            "Resource": [
                                {
                                    "Fn::Sub": [
                                        "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${apiId}/types/${typeName}/fields/${fieldName}",
                                        {
                                            "apiId": {
                                                "Ref": "AppSyncApiId"
                                            },
                                            "typeName": "Mutation",
                                            "fieldName": "deleteTodo"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    },
    "Conditions": {
        "HasEnvironmentParameter": {
            "Fn::Not": [
                {
                    "Fn::Equals": [
                        {
                            "Ref": "env"
                        },
                        "NONE"
                    ]
                }
            ]
        },
        "AlwaysFalse": {
            "Fn::Equals": ["true", "false"]
        }
    },
    "Outputs": {
        "EmptyOutput": {
            "Description": "An empty output. You may delete this if you have at least one resource above.",
            "Value": ""
        }
    }
}

```

**Comment by warrenmcquinn** [comment]
Awesome, that really helps. Thanks so much @yuth. Closing the issue now.

**Comment by houmark** [comment]
@yuth I have a question related to this.

When you manually add these fields and modify CustomResources.json as you described above, it seems that the authRole Role produced in IAM will only hold those exact lines. I believe that this very same Role normally would hold all the resources configured with in `@auth` with `provider: iam` in `schema.graphql`.

Does this mean that if I need to do this to allow access to a `@function` then I will also manually need to add all the rest of my access for IAM?

**Comment by ohsik** [comment]
I'm getting this error when `amplify push` with the policy added to add to CustomResources.json.
What did I miss??
```
UPDATE_FAILED CustomResourcesjson AWS::CloudFormation::Stack Thu May 07 2020 10:46:27 GMT-0400 (Eastern Daylight Time) Template format error: Unresolved resource dependencies [authRoleName] in the Resources block of the template
```
