### ISSUE TITLE
Check failed: stack_overflow().

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#2550]
**Describe the bug**
I updated the amplify cli today (version 3.12.0) and now get an error when attempting to run `amplify storage update`

The full error is:

#&#x2060;
#&#x2060; Fatal error in , line 0
#&#x2060; Check failed: stack_overflow().
#&#x2060;
#&#x2060;
#&#x2060;
#&#x2060; FailureMessage Object: 0x7ffeefbfcc10Illegal instruction: 4

**To Reproduce**
`npm install -g @aws-amplify/cli`
`amplify storage update`

**Expected behavior**
The command works as expected

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOs Catalina
- Browser: n/a
- Version: 3.12.0

**Additional context**
Running `amplify status` or `amplify env checkout ....` commands work fine

**Comment by mattk-** [comment]
Working in 3.11.0

**Comment by yuth** [comment]
@danhumphrey what version of NodeJS do you have running?
@mattk- are you using this with catalina?

**Comment by danhumphrey** [comment]
@yuth I'm running 11.6.0

**Comment by warrenmcquinn** [comment]
I just upgraded to Catalina and I'm seeing this with `amplify update api` as well:

```
#
# Fatal error in , line 0
# Check failed: stack_overflow().
#
#
#
#FailureMessage Object: 0x7ffeefbfdc90[1]    22391 illegal hardware instruction  amplify api update
```

**Comment by UnleashedMind** [comment]
This is a very strange bug, I did reproduce it with our latest version as well (Amplify-CLI v3.13.0), it's also inconsistently popping up for node version 10.16.2 and 10.16.3 (LTS) too. 
But it's working fine for node version 12.11.1 (latest version). 

I've logged a issue on node github repo. 
For now, try to use the CLI on node version 12.11.1. 
We will continue to monitor this bug, and keep you updated.

**Comment by houmark** [comment]
Also happening for me on 3.14.0. There's not an update without something breaking, doh...

**Comment by UnleashedMind** [comment]
We released a new version last night, v3.15.0.
Please install the latest version and check if you are still having the issue.

**Comment by warrenmcquinn** [comment]
`v3.15.0` works for me on MacOS Catalina, `node v12.8.0`! Thanks!

**Comment by royalaid** [comment]
I know this issue is closed and I don't want to nerco it but I wanted to add that I was 3.14.0 on Windows and was experiencing this issue. Updating to 3.15.0 fixed it. Thanks for the quick fix!
