### ISSUE TITLE
Graphql-transformer-core library in amplify-cli: Expected type AuthStrategy, found private.

### ISSUE THREAD

**Issue by CaptainChemist** [aws-amplify/amplify-cli#2558]
**Describe the bug**

I'm getting a validation error with the graphql-transformer-core library when it runs in the amplify console, but not when I run it locally. It has a problem with the type 'private' which I need to use with an iam type. This is the error:

````
{ SchemaValidationError: Schema Errors:
Expected type AuthStrategy, found private.
GraphQL request (13:16)
 12:       { allow: owner, operations: [read] }
 13:       { allow: private, provider: iam, operations: [create, read] }
 ^
 14:     ]
 Field "provider" is not defined by type AuthRule.
 GraphQL request (13:25)
 12:       { allow: owner, operations: [read] }
 13:       { allow: private, provider: iam, operations: [create, read] }
 ^
 14:     ]
 at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:191:19)
 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:100:49
 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:43:23)
 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:24:53)
 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:58) name: 'SchemaValidationError' }
````

The particular model I am using is the following:

````
type UserCourse
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Admin"] }
      { allow: owner, operations: [read] }
      { allow: private, provider: iam, operations: [create, read] }
    ]
  ) {
  id: ID!
  course: Course! @connection(name: "UserCourse")
  owner: String
  userCourseCourseId: ID
}
````

**Comment by attilah** [comment]
@CaptainChemist what version of the CLI are you using, I see that you're using NVM, could you please test with Node 8.x that the same problem happening or not?

1. if you remove the private rule is the schema compiling?
2. if you removed the private rule, and add ```provider: userPools``` to the owner rule, is the schema compiling?

**Comment by CaptainChemist** [comment]
@attilah I'm using node 10.15.3 on my computer where it works and I can tell that the amplify console is using 10.16.0 where it fails. Even when I change to 10.16.0 on my computer it still deploys just fine. On my computer I am using amplify version 3.13.0. Amplify console does not log which version it is using so I cannot tell what is being run in the amplify ci/cd pipeline.

1. Yes, everything deploys on the amplify console when that private rule is commented out. 

2. I changed that line to `{ allow: owner, provider: userPools }` and now I get an error that provider is not defined by AuthRule even though I can see it as an allowed type in the `@auth` documentation. This was an interesting test- I wonder what is going on with this running in the amplify console because both of these rules should definitely be allowed.

````
Field "provider" is not defined by type AuthRule.
                                 GraphQL request (13:23)
                                 12:       { allow: owner, operations: [read] }
                                 13:       { allow: owner, provider: userPools }
                                 ^
````

**Comment by CaptainChemist** [comment]
I can confirm that doing the following will force amplify console to use node 8 and in that case, everything compiles correctly. Still not sure why the difference between node 8 and 10 but I'm glad that I can get something working!

````
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - nvm use $VERSION_NODE_8
        - npm install -g @aws-amplify/cli
        - amplifyPush --simple
````

**Comment by attilah** [comment]
@CaptainChemist as it is a GraphQL validation error, I think that the default CLI version the console is using does not have the multi-auth capability which added the ```provider``` property to the ```@auth``` rules. I think it is a good practice to always specify for Amplify Console which version of the CLI you want to use, which should be the same what you're using to develop your product on your machine.

So I think it was not Node version but the CLI's version that caused the problem for you.

I'm closing this issue now, but if something comes up, feel free to reopen the issue or open a new one.

**Comment by CaptainChemist** [comment]
This was an excellent suggestion @attilah. You are totally right that I do not need to use node version 8- I just confirmed that adding the following line to the build step fixes the issue:

```
npm install -g @aws-amplify/cli@3.15.0
```

Thanks so much!

**Comment by bagubits** [comment]
Dear all,

I have the same issuee, but it's not working for me with the latest versions...
I have node 8.9 and node 10.9 (and i have tested with the two version, obtaining the same error).

My schema is

```
type Ad 
  @model 
  @key(fields: ["id", "status", "createdAt"])
  @key(name: "byStatus", fields: ["status", "createdAt"], queryField: "itemsByStatus")
  @auth(rules: [
      { allow: owner },
      { allow: public, queries: [get, list], mutations: null },
      { allow: groups, groups: ["Users"], queries: [get, list], mutations: null }
    ]) {
  id: ID!
  type: Animal!
  title: String!
  description: String!
}
```

When i run amplify push I get the following error

```
Schema Errors:

Expected type AuthStrategy, found public.

GraphQL request (87:16)
86:       { allow: owner },
87:       { allow: public, queries: [get, list], mutations: null },
                   ^
```

Running "> amplify --version" I get 1.12.0.
The version installed of amplify-cli is @aws-amplify/cli@3.16.0

Could you help me please?

**Comment by jonnyleeharris** [comment]
Using the following to annotate a model:

``@auth(rules: [
  { allow: groups, groups: ["Admin","SpecTeam"] },
  { allow: private, provider: iam, operations: [create, read, update, delete] }
])``

Locally, amplify push works, but when the AWS Amplify Console attempts to build, the following error occurs:

``init failed
2019-11-14T16:45:19.219Z [INFO]: { SchemaValidationError: Schema Errors:
                                 Expected type AuthStrategy, found private.
                                 GraphQL request (53:12)
                                 52:   { allow: groups, groups: ["Admin","SpecTeam"] },
                                 53:   { allow: private, provider: iam, operations: [create, read, update, delete] }
                                 ^
                                 54: ])
                                 Field "provider" is not defined by type AuthRule.
                                 GraphQL request (53:21)
                                 52:   { allow: groups, groups: ["Admin","SpecTeam"] },
                                 53:   { allow: private, provider: iam, operations: [create, read, update, delete] }
                                 ^
                                 54: ])
                                 at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:191:19)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:100:49
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:43:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:24:53)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:15:58) name: 'SchemaValidationError' }``

**Comment by aprilmintacpineda** [comment]
@attilah sorry for the tag, I'm tagging you because you were the one who closed this. I encountered this on the CI/CD. Do we really have to do `npm i -g @aws-amplify/cli` on the preBuild phase every time? Can't we just tell amplify to use a particular version and then it will automatically do that for us, because the build is already kind of slow, I'm actually looking for ways to speed it up.
