### ISSUE TITLE
Getting started guide results in a public S3 bucket

### ISSUE THREAD

**Issue by stilvoid** [aws-amplify/amplify-cli#256]
**Describe the bug**
Running through [the getting started guide](https://aws-amplify.github.io/amplify-js/media/quick_start) results in an S3 bucket being created for hosting the website. The bucket has public read permissions and so falls short of I'm sure many folks security controls.

**To Reproduce**
1. Deploy hosting using the Amplify CLI

**Expected behavior**
Provide a very clear warning during the hosting deployment that Amplify will create a public bucket

**Comment by Gyja** [comment]
Yup. I got the same thing. 

Provide the information in the **documentation** around a **Public bucket** as well as in the **CLI** **before** the action is **committed**.

**Comment by wagneraw** [comment]
To be more specific, I don't think this is purely a documentation fix. When you run "amplify add hosting" and choose "PROD" to provision S3 + Cloudfront, it's provisioning a publicly accessible bucket and a Cloudfront distribution, where it should be provisioning a Cloudfront distribution with OAI(origin access identity) setup for the S3 bucket along with a S3 bucket policy that only allows access from the Cloudfront Distribution.

**Comment by kaustavghosh06** [comment]
@wagneraw You’re correct. Which version of the CLI are you currently using? We merged this PR -> https://github.com/aws-amplify/amplify-cli/pull/236 a couple of days back and it is a part of the latest CLI version.

**Comment by wagneraw** [comment]
I'm on 0.1.28, which I thought was the latest?

amplify-js-app/ $ amplify --version
0.1.28

**Comment by kaustavghosh06** [comment]
@wagneraw Just checked our version control and saw that the PR got merged and is in an alpha npm branch. We'll publish it to a stable version to NPM in the next couple of days.
