### ISSUE TITLE
Add option to specify DeletionPolicy for API category and default to retain for provisioned Data Sources

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#2567]
**Is your feature request related to a problem? Please describe.**
`amplify push` can be a dangerous option if schema.graphql models were erroneously dropped during merges. 

**Describe the solution you'd like**
Give us the option to set the DeletionPolicy for each model (wish list) or at least the entire API stack. This would make `amplify push` a more forgiving operation because even if the model gets removed from the schema on the AppSync side, it can still be restored without any data loss. I also think this should be the default behavior. In the event that the user truly does want to drop a model/table with data loss, they can switch the DeletionPolicy back to Delete in order to run the `amplify push`.

**Describe alternatives you've considered**
Write a custom git pre-push hook that parses the new schema.graphql for all models, then compares that against the list of all Data Sources for that API, and reject the push if it would drop a table.

**Comment by houmark** [comment]
This is actually a bit scary to think about. One simple ***** (or a bug in Amplify? Plenty of those) and the production database and its data can be gone with no warnings in seconds. Amplify should default to protect any database table and have the user explicit confirm that they want to delete it on schema changes.

**Comment by jkeys-ecg-nmsu** [comment]
Seems like this could be implemented on a per-model basis simply by adding one or two new directives, something like this:

`@retentionPolicy(retain: true)`

Then parse the retain field and inject that into the DeletionPolicy for each model's stack.

**Comment by undefobj** [comment]
> Seems like this could be implemented on a per-model basis simply by adding one or two new directives, something like this:
> 
> `@retentionPolicy(retain: true)`
> 
> Then parse the retain field and inject that into the DeletionPolicy for each model's stack.

In general it's best practice to try and keep implementation specific details outside of your datamodel. Not always possible but that's the top level guidance for custom directives. That being said we can look at implementing this in different ways for the whole platform. I've set a tag for this in the backlog.

**Comment by jkeys-ecg-nmsu** [comment]
@undefobj thank you for the advice and for tagging this FR.

**Comment by jkgwm** [comment]
Another option is to setup the database separately, with the desired retention policy, then use amplify to setup your API and pass references for the database resources. I think this prevents confusion and easier maintenance. Today this is might be possible by modifying the generated CF templates for the API if you are comfortable with cloudformation, but future implementations of the CLI could make this possible.

I don't love that Amplify API 'owns' the database it interacts with when using the CLI to setup. What if I want to make a feature stack but use the same data 'environment' as my DEV env? Its impossible to share the database when the API stack 'owns' the data stack.

**Comment by cyrfer** [comment]
Another option is to setup the database separately, with the desired retention policy, then use amplify to setup your API and pass references for the database resources. I think this prevents confusion and easier maintenance. Today this is might be possible by modifying the generated CF templates for the API if you are comfortable with cloudformation, but future implementations of the CLI could make this possible.

I don't love that Amplify API 'owns' the database it interacts with when using the CLI to setup. What if I want to make a feature stack but use the same data 'environment' as my DEV env? Its impossible to share the database when the API stack 'owns' the data stack.

**Comment by flogy** [comment]
I just released a custom GraphQL directive for Amplify to set the deletion policy of generated DynamoDB tables to `Retain`. Like this it **won't be deleted anymore** when you change the name of a type or remove a type entirely!

In the end you can just add `@retain` directive to your schema like this:
```graphql
type Todo @model @retain {
  id: ID!
  title: String!
  description: String
}
```

Check out the full installation instructions: https://github.com/flogy/graphql-retain-transformer

And please leave a ⭐️ if you like it! 😊 Thanks!

**Comment by josefaidt** [comment]
Hey y'all :wave: really appreciate the feedback here! Copying a [response from a related issue](https://github.com/aws-amplify/amplify-cli/issues/1970#issuecomment-1075578972):

Unintended loss of data when renaming models is now safeguarded on `amplify push` with `--allow-destructive-graphql-schema-updates` 

> The following schema updates require replacement of the underlying DynamoDB table:
> 1. Removing or renaming a model
> 2. Modifying the [primary key](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key) of a model
> 3. Modifying a Local Secondary Index of a model (only applies to projects with [secondaryKeyAsGSI](https://docs.amplify.aws/cli/reference/feature-flags/#secondaryKeyAsGSI) turned off)

> When trying to push a schema change with one or more of these updates you will see an error message explaining that you will lose ALL DATA in any table that requires replacement

https://docs.amplify.aws/cli/graphql/overview/#update-schema

In this case we also may see some benefit in using the `@mapsTo` directive

> Amplify supports renaming models in a GraphQL schema by using the @mapsTo directive. Normally when renaming a model, Amplify will remove the underlying table for the model and create a new table with the new name. Once a table contains production data that cannot be deleted, @mapsTo can be used to specify the original name.

https://docs.amplify.aws/cli/graphql/schema-evolution/#renaming-models-while-retaining-data

---

We can also leverage [overrides](https://docs.amplify.aws/cli/graphql/override/) to manually override the `DeletionPolicy`

```ts
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override({ models }: AmplifyApiGraphQlResourceStackTemplate) {
  models.Todo.modelDDBTable.addOverride('DeletionPolicy', 'Retain')
}
```

Which upon `amplify build` we can see the DeletionPolicy is overridden from `Delete` to `Retain`

```json
"Resources": {
  "TodoTable": {
    "Type": "AWS::DynamoDB::Table",
    "Properties": {},
    "UpdateReplacePolicy": "Delete",
    "DeletionPolicy": "Retain"
  },
```

Closing issue. If you are still experiencing this issue or feel the features do not quite cover your use case please reply back to this thread and we can re-open to investigate further 🙂
