### ISSUE TITLE
How to define my own GraphQL queries or subscriptions?

### ISSUE THREAD

**Issue by darrentarrant** [aws-amplify/amplify-cli#257]
Say I have this simple model

```
type Customer @model {
  id: ID!
  name: String!
  companyId: String!
}
```

Once i run amplify api push or gql-compile amplify will generate a graphql.schema in the 'amplify/backend/.../build' folder containing queries, mutations and subscriptions to get, create and update these models and to subscribe to changes and creations of them.

But, how do I modify or override what's in the built graphql.schema to do things like:

- Make companyId a required filter input when getting lists of customers?
- Add companyId as a filter to subscriptions?

For a multi-tenant app something like companyId is the discriminator to ensure a user only sees and can work with data belonging to their company. Obviously I could write UI code to achieve this but I'd rather have it within my backend API.

**Comment by kaustavghosh06** [comment]
Closing this issue. Please, feel free to re-open this issue if the problem still persists. 
Support for custom queries and mutations is covered as a part of #74. Closing it as a duplicate

**Comment by ChenLi0830** [comment]
Hi @mikeparisstuff, in the amplify auto-generated schema.graphql file, mutation uses its own `input` type. Namely: 
````
type Mutation {
  createMessage(input: CreateMessageInput!): Message
}
````
Do we need to adjust Subscription's argument accordingly? Something like 
````
type Subscription {
  onCreateMessage(input: CreateMessageInput): Message @aws_subscribe(mutations: ["createMessage"])
}
````

**Comment by ChenLi0830** [comment]
In order to **add arguments in Subscriptions**, I also tried to use the method described here - https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html. I tried to manually create mutations whose input are arguments instead of an `input` type, and try to subscribe to the argument.  However, it doesn't work for me either. 

Any help would be highly appreciated.
