### ISSUE TITLE
RegEx Error when switching to an env

### ISSUE THREAD

**Issue by gkpty** [aws-amplify/amplify-cli#2572]
**Describe the bug**
Getting an error in the amplify CLI when trying to switch to another environment called test. i set up CD for the environment in the Amplify console and its working fine but i cannot switch to this environment locally.

i get the following error:

```
There was an error initializing your environment.
2019-10-11T23:35:35.367Z - error: uncaughtException: 1 validation error detected: Value '2019/08/26/[$LATEST]xxx' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]* date=Fri Oct 11 2019 18:35:35 GMT-0500 (Eastern Standard Time)
```
I have made sure that all the attributes in the `team-provider-info.json` are correct and i have deleted the enviornment and re-imported using amplify env import but i continue getting the same error.

i created this same issue in the aws amplify repo as well
https://github.com/aws-amplify/amplify-js/issues/4173

**Comment by kaustavghosh06** [comment]
Which CLI version are you using locally?

**Comment by gkpty** [comment]
Indeed it seems i hadn't updated the CLI in a while.. updating the CLI to 3.14 solved my issue. 

Thanks a lot for the quick response!
