### ISSUE TITLE
Adding @auth public to one field exposes the entire model

### ISSUE THREAD

**Issue by yonatanmn** [aws-amplify/amplify-cli#2576]
cli@3.14.0

schema :

```gql
type Thing @model
    @auth(rules: [
    { allow: groups, groups: ["admins"]  },
])
    {
        id: String!
        text: String
        publicText: String @auth(rules: [{ allow: public, operations: [read]}])
    }

```

query (with API-KEY): 
```gql
query ListThings(
  $filter: ModelOpenFilterInput
  $limit: Int
  $nextToken: String
) {
  listOpens(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      text
      publicText
    }
    nextToken
  }
}
```

Without adding the "allow: public" rule the result is "Unauthorized" as expected. This is true for `getThing` query as well, but `mutation` seems to work fine (returning only public fields)

**Comment by RossWilliams** [comment]
Seems related to #2241

**Comment by attilah** [comment]
@yonatanmn how is your auth config looks like? what providers are configured, which one is the default?

**Comment by yonatanmn** [comment]
@attilah  - sorry for late response. missed it somehow. 
I'm using a user pool without social provider. (Is that an answer to your question?)

**Comment by kaustavghosh06** [comment]
@yonatanmn I believe what Attila meant was the authorization types for your GraphQL schema.

**Comment by yonatanmn** [comment]
@kaustavghosh06 the entire schema is written in the first post

**Comment by attilah** [comment]
@yonatanmn what is the default auth mode and which one is the additional. Based on your issue you've User Pools and API Key enabled. Which one is the default?

**Comment by SwaySway** [comment]
Hello @yonatanmn the data model is not exposed if you are using API Key as your default mode of authentication, however if you are using Cognito User Pools as your default mode of authentication, you will need to add rules on the other fields to explicitly deny access to users who use apiKey as a mode of authentication. This is outlined in the documentation:
[GraphQL Transform Field Level Authorization](https://aws-amplify.github.io/docs/cli-toolchain/graphql#field-level-authorization)
```gql
type Todo 
  @model
{
  id: ID! 
  updatedAt: AWSDateTime! @auth(rules: [{ allow: groups, groups: ["ForbiddenGroup"] }])
  content: String! @auth(rules: [{ allow: owner, operations: [update] }])
}
```

An example of this implementation would be

```gql
type Post
  @model
  @auth(rules: [
    { allow: groups, groups: ["admins"]  }
  ]) {
    id: String! @aws_cognito_user_pools # deny users who are authenticated via @aws_api_key
    text: String @aws_cognito_user_pools # 
    publicText: String @auth(rules: [
    { allow: groups, groups: ["admins"]  } # ensuring users in the "admins" group are still allowed actions on this field
      { allow: public, operations: [ read ], provider: apiKey }
    ])
}
```

Thanks for the raising this question, as a takeaway we can look a little further at making some improvments on field level @auth to make it more straightforward as a part of our roadmap.

**Comment by yonatanmn** [comment]
Thanks @SwaySway , I'll check that!
