### ISSUE TITLE
amplify env remove does not remove all resources

### ISSUE THREAD

**Issue by rfpedrosa** [aws-amplify/amplify-cli#2579]
**Describe the bug**
`amplify env remove` does not remove all resources previously created with amplify cli. Resources that are not removed are:
- Analytics category / Pinpoint (`amplify add analytics`);
- S3 buckets used to deploy;

In the long term, AWS account gets messy with unused resources and it makes the creation of new environments with the same name to fail.

**To Reproduce**
1. amplify env add (let say that new environment is called 'newenv')
2. amplify push
2. amplify add analytics
3. amplify env remove newenv

**Expected behavior**
AWS Pinpoint as well S3 buckets used to deploy are removed.

**Additional context**
NA

**Comment by UnleashedMind** [comment]
@rfpedrosa 
This is a known behavior. 
Most resource names are marked with time stamps to avoid name clashes. 
I marked this as a enhancement request.

**Comment by jkeys-ecg-nmsu** [comment]
@UnleashedMind is there a reason that the DeploymentBucket resource defaults to Retain?

**Comment by UnleashedMind** [comment]
Because it might contain useful data for our customers.

**Comment by jkeys-ecg-nmsu** [comment]
@UnleashedMind ah I see. So then why doesn't the API stack default to retain?

**Comment by ammarkarachi** [comment]
Closing this issue the PR has been merged
