### ISSUE TITLE
aws update api fails

### ISSUE THREAD

**Issue by yonatanmn** [aws-amplify/amplify-cli#2580]
`aws update api` 
result - 
```
#
# Fatal error in , line 0
# Check failed: stack_overflow().
#
#
#
#FailureMessage Object: 0x7ffeefbfde20[1]    53245 illegal hardware instruction  amplify update api
```

mac catalina, amplify@3.14

```
$ amplify status: 

 amplify status    

Current Environment: dev

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Auth     | xxx | No Change | awscloudformation |
| Api      | xxx         | No Change | awscloudformation |
| Hosting  | S3AndCloudFront   | No Change | awscloudformation |

GraphQL endpoint: https://xxx.appsync-api.eu-west-1.amazonaws.com/graphql
GraphQL API KEY: da2-xxx
Hosting endpoint: http://xxx-hostingbucket-dev-dev.s3-website-eu-west-1.amazonaws.com

```

**Comment by UnleashedMind** [comment]
We've noticed this bug started to popping up since last Thursday. 
#2550
We are root causing it. 
What is the node version on your computer? Could you update to node version 12.11.1 and try again?

**Comment by yonatanmn** [comment]
mine was 12.8. fixed it in another way. see it was solved fast :) thx

**Comment by UnleashedMind** [comment]
We released a new version last night, v3.15.0.
Please install the latest version and check if you are still having the issue.

**Comment by tracknemo** [comment]
> We released a new version last night, v3.15.0.
> Please install the latest version and check if you are still having the issue.

Just to clarify, latest version of node correct?

**Comment by kaustavghosh06** [comment]
Latest version of the Amplify CLI.

**Comment by tracknemo** [comment]
> Latest version of the Amplify CLI.

Thank you, this worked. For anyone unsure of what command to run, it is npm install -g @aws-amplify/cli
