### ISSUE TITLE
Issue related to amplify push for @function for multiple queries with multiple function

### ISSUE THREAD

**Issue by trupa7** [aws-amplify/amplify-cli#2583]
I created one function and  create one query with that
```gql
type Query{
   custom_query @function(name:"myfunction")
}
```
and I deployed with amplify console ---> deploy (it's worked there)

and after that I added one more function and one more custom_query
```gql
type Query{
   custom_query @function(name:"myfunction")

   custom_query2 @function(name:"myfunction2")
}
```
and I tried to push through amplify cli (amplify push)

I updated the stack but I unable to see the changes in appsync console--->queries

**Comment by UnleashedMind** [comment]
@trupa7 
After you deploy through Amplify Console, how did you bring the project to your local development environment?

**Comment by trupa7** [comment]
First I added api from amplify cli 
1. amplify init
2. amplify add api
then updated my schema
and pushed my code to git 
I set up amplify deploy from console.
It deployed backed   
then I made some changes in my schema and tried amplify push from amplify cli instead of pushing code to git.

So, Is it advisable to do that or we can either use amplify deploy or amplify push. to push amplify api updates?

**Comment by SwaySway** [comment]
@trupa7 Are you managing two different environments (prod from cli and dev from console).
If you are using one environment then you can push from either cli (amplify push) or console (using git push).

**Comment by trupa7** [comment]
@SwaySway : one environments. But If I push from console(git push) and if u do amplify status after completion of git push .It still show api status to update. And if you make push from cli with schema change it will make a push but I unable to see the changes in appsync

**Comment by kaustavghosh06** [comment]
@trupa7 If you deployed via Amplify console first - I believe it deployed a separate backend from what you have locally.

**Comment by trupa7** [comment]
> @trupa7 If you deployed via Amplify console first - I believe it deployed a separate backend from what you have locally.

@kaustavghosh06 : Thanks . I think we can close this issue.
