### ISSUE TITLE
auth field that allows to read and update, can read and update, but update does not return value

### ISSUE THREAD

**Issue by yonatanmn** [aws-amplify/amplify-cli#2589]
cli@3.14.0, macos catalina, node@12.11.1, 

schema :
```gql
type Thing @model
    @auth(rules: [
        { allow: groups, groups: ["admins"]  },
        { allow: groups, groupsField: "projectAccountId", operations: [ read ] }

])
    {
        id: String!
        text: String
        canChangeThis: String @auth(rules: [       
         { allow: groups, groupsField: "projectAccountId", operations: [ read, update ] },
        ])
    }
```
query works as expected. 
mutation of `updateThing`:

```gql
mutation UpdateThing($input: UpdateThing!) {
  updateThing(input: $input) {
    id
    text
    canChangeThis
  }
}
variables: {
id: "xxx"
canChangeThis: "something new"
}
```

mutation works, but the returned object is : 
```gql
{
id: "xxx"
text: "what was here"
canChangeThis: null  // 
}
```
**expected** -
`canChangeThis` should be "something new" and not null

perhaps related to :https://github.com/aws-amplify/amplify-cli/issues/2576

**Comment by SwaySway** [comment]
@yonatanmn This is related to per-field auth with subscriptions. If you do not need `@auth` on subscriptions you can either set it to public or off
`@model(subscriptions: { level: public } })`

View the docs here:
https://aws-amplify.github.io/docs/cli-toolchain/graphql#per-field-with-subscriptions
