### ISSUE TITLE
Add pre-push and post-push hooks to allow custom functionality 

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#2590]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to abort push attempts if some condition fails, and to notify a service if the push attempt succeeds (as two examples of use cases these hooks would help accomplish). I cannot find any reference to CloudFormation lifecycle hooks, so this would be a novel addition to the CloudFormation ecosystem and might drive adoption. The closest I can find is the stack-update-complete API, which I assume is called by Amplify to determine under the hood whenever a stack update has finished.

**Describe the solution you'd like**
I would like to specify either a local script, or a Lambda ARN that the environment profile has permission to invoke, as pre- and post-push hooks.

**Describe alternatives you've considered**
Try to replicate the same functionality with git hooks, which would not not solve the problem of someone using `amplify push` outside of a CI/CD workflow that relies on git.

**Comment by UnleashedMind** [comment]
The Amplify CLI does not have feature that allows end-user scripts to to be invoked in a life cycle events. However, the Amplify CLI plugin platform does broadcast pre-push and post-push events to the plugins if they subscribe to those events. As a work around if you really need this feature for now, you can write a utility plugin that subscribe to those events. 
https://aws-amplify.github.io/docs/cli-toolchain/plugins#authoring-a-cli-plugin

**Comment by jkeys-ecg-nmsu** [comment]
@UnleashedMind sorry if this is a dumb question, I'm not much of a shell programmer. 

Would a custom plugin executing a pre-push hook execute on the same thread as the `amplify push`, so I could just kill the thread if my conditions fail? Or would there need to be some IPC / message passing to accomplish such a goal?

**Comment by UnleashedMind** [comment]
Most likely the plugin will be written with either JS or TS.
It'll be on the same thread, and yes you can use process.exit(1) to terminate the execution of the whole command.

**Comment by josefaidt** [comment]
Hey folks :wave: this feature request has since been addressed with the introduction of [Amplify CLI Command Hooks](https://docs.amplify.aws/cli/project/command-hooks/), which enable you to run a script at different lifecycle events.

Closing issue
