### ISSUE TITLE
Undo 'amplify function update'

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#2594]
When I update a function and for example set permission on API in the project then I am not able to undo this. Because If I go again to '**amplify update function' > update permissions > uncheck the boxes > enter**, then I receive this error: You must select at least one operation.

I want to undo this because I received **Circular dependency between resources** when I set permissions from a function on API resource.  

The only option is left is to manually update the cloudformation template.

**Comment by kaustavghosh06** [comment]
@rpostulart Could you please send a screenshot of the validation error? I tried to reproduce it locally and was able to de-select/un-check all the categories and then proceed with the next questions without any validation to remove all the policies/permissions for the previously selected categories:

```bash
f45c89966b0d:apigw4 kaustavg$ amplify-dev function update
Using service: Lambda, provided by: awscloudformation
? Please select the Lambda Function you would want to update apigw4ae76773b
? Do you want to update permissions granted to this Lambda function to perform on other resources
 in your project? Yes
? Select the category 

You can access the following resource attributes as environment variables from your Lambda function
var environment = process.env.ENV
var region = process.env.REGION

? Do you want to edit the local lambda function now? No
Successfully updated resource
```

**Comment by rpostulart** [comment]
This is the screenshot after I deselected the options:

<img width="569" alt="Screenshot 2019-10-17 at 07 19 01" src="https://user-images.githubusercontent.com/21346629/66979647-9bc70d00-f0ae-11e9-9e75-c0f7df9e91d6.png">

**Comment by rpostulart** [comment]
<img width="569" alt="Screenshot 2019-10-17 at 07 21 52" src="https://user-images.githubusercontent.com/21346629/66979716-d4ff7d00-f0ae-11e9-9093-f85b61a1e282.png">

**Comment by kaustavghosh06** [comment]
@rpostulart If you just de-select the resource in the previous question option, all the CRUD operations for that resource would go away. Did you try doing that?

**Comment by rpostulart** [comment]
Sorry again: this is the screenshot after I deselected them:

<img width="569" alt="Screenshot 2019-10-17 at 07 21 52" src="https://user-images.githubusercontent.com/21346629/66979765-f6f8ff80-f0ae-11e9-8751-e7757db6495f.png">

**Comment by rpostulart** [comment]
@kaustavghosh06 : yes you are right, then it's working! Thx
