### ISSUE TITLE
Amplify CLI yields TypeError on almost all commands

### ISSUE THREAD

**Issue by fabianjj** [aws-amplify/amplify-cli#2595]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
All CLI commands that seems to touch the cloud now yields the following error in some form:
`The 'request' argument must be string. Received type undefined`

Simply running "amplify status" seems to show the correct status, followed by:

`The 'request' argument must be string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at /home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/esm/esm.js:1:224803
    at Object.<anonymous> (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/esm/esm.js:1:251922)
    at Object.t (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/esm/esm.js:1:279775)
    at n (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/esm/esm.js:1:279589)
    at /home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:54:44
    at Array.forEach (<anonymous>)
    at AmplifyToolkit.<anonymous> (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:53:31)
    at step (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:33:23)
    at Object.next (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:14:53)
    at fulfilled (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/show-helpful-provider-links.js:5:58)`

**To Reproduce**
I haven't changed anything in the AWS environmnet for weeks, only updated the CLI.

**Expected behavior**
I expect not to receive errors.

**Desktop (please complete the following information):**
@aws-amplify/cli@3.15.0
Windows 10
Visual studio code, Ubuntu WSL.

**Comment by UnleashedMind** [comment]
We've noticed unrelated issues when the Amplify CLI is running on Ubuntu WSL. 
can you do a fresh re-install and try to run the CLI directly on the windows cmd.exe or powershell?

**Comment by fabianjj** [comment]
@UnleashedMind: 
I installed the @aws-amplify/cli using powrshell in the same directory, ran ampliy configure project,  which went through without showing any issues.

I can now run "amplify status" in powershell without running into any problems, but as soon as i try to do "amplify push" i get the following error:

`× An error occurred when pushing the resources to the cloud

Missing credentials in config
An error occured during the push operation: Missing credentials in config`

Event though I entered a correct IAM user during "amplify configure project" and the CLI didn't throw any errors at that point.

**Comment by jkeys-ecg-nmsu** [comment]
@fabianjj you probably have your AWS credentials set up in ~/.aws in WSL, and Powershell isn't reaching into the WSL filesystem.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by UnleashedMind** [comment]
@fabianjj 
- follow the doc and setup the credentials files under <home>/.aws/config and <home>/.aws/credentials file
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
- run `amplify configure project` again in powershell

**Comment by fabianjj** [comment]
@UnleashedMind , @UnleashedMind:

I've moved the contents of _~/.aws_ to _%UserProfile%\.aws_. Now I get a little bith further, but _amplify push_ fails rather quickly and yields the following error:

`UPDATE_FAILED      authicepackcfa592d6cfa592d6 AWS::CloudFormation::Stack Thu Oct 17 2019 21:28:29 GMT+0200 (GMT+02:00) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, allowUnauthenticatedIdentities, hostedUI, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, useDefault, userpoolClientGenerateSecret, mfaConfiguration, identityPoolName, thirdPartyAuth, authSelections, permissions, resourceNameTruncated, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, parentStack, resourceName, triggers, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, requiredAttributes, passwordPolicyCharacters, userpoolClientLambdaRole, defaultPasswordPolicy] must have values
UPDATE_FAILED      apiicepack                  AWS::CloudFormation::Stack Thu Oct 17 2019 21:28:29 GMT+0200 (GMT+02:00) Parameters: [S3DeploymentRootKey, S3DeploymentBucket] must have values  `

It seeems like there's more to in than the _.aws_ folder and the _amplify configure project_ command to set my project back up in powershell. Any thoughts?

**Comment by fabianjj** [comment]
Update:
I updated my WSL Ubuntu installation and the original error no longer appears.

However, I'm running into the same issue as in my previous comment when trying to update using WSL, which keeps me from implementing the cloud changes I wanted to make.

**Comment by DavidNelsonCordelia** [comment]
I am getting similiar problems to these    I just updated the @aws-amplify/cli today  (and everthing else) and started seeing these issues.

One additional item.  If I try a comand like amplify function ....    the catagory does not exist  The catagory pluggins seem not to be loaded

**Comment by UnleashedMind** [comment]
@DavidNelsonCordelia 
what OS did you run your amplify CLI on? 
could you run a fresh `amplify plugin scan` and then `amplify plugin list` -> `active plugins`, check what are in your system.

**Comment by kaustavghosh06** [comment]
@fabianjj Can you check your `amplify/.config/project-config.json` file and see if the absolute path to your project is entered correctly?

**Comment by UnleashedMind** [comment]
@fabianjj 
You can probably try these steps to restore your project: 
- backup your local changes
- `amplify env pull --restore`
- `amplify api gql-compile`
- apply your local changes from the backup.
- `amplify push`

**Comment by CSHaze** [comment]
@DavidNelsonCordelia
Thank you, I was having this problem and also getting
```? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)```, with nothing after it (enter would exit), when running ```amplify config```. Reinstalled multiple times, nothing worked.

 ```amplify plugin scan``` fixed it.

**Comment by jkeys-ecg-nmsu** [comment]
Off-topic, but: the Amplify team could probably save themselves a lot of time responding to issues if there was a FAQ or How-To guide on remediating Amplify-managed CF stacks that are in an unhappy state. One of the major appeals of the Amplify CLI is that it builds and manages stacks for you so you can focus on development, but then when something goes wrong there's very little guidance on how to remediate.

**Comment by DavidNelsonCordelia** [comment]
after a amplify plugin scan and then list I get the output below.   I will do a new global install tomorrow 

core: @aws-amplify/cli@3.15.0
{ packageName: '@aws-amplify/cli',
  packageVersion: '3.15.0',
  packageLocation:
   'C:\\Users\\nelson\\Documents\\code\\onlinecoop\\node_modules\\@aws-amplify\\cli\\',
  manifest:
   { name: 'core',
     type: 'core',
     commands:
      [ 'categories',
        'configure',
        'console',
        'delete',
        'env',
        'help',
        'init',
        'migrate',
        'publish',
        'push',
        'run',
        'status',
        'plugin',
        'version' ],
     commandAliases: { h: 'help', serve: 'run', ls: 'status' } } }

**Comment by DavidNelsonCordelia** [comment]
AI am on Windows 10.      A reinstall of "@aws-amplify/cli"  globally did not help.     I see i have it installed locally as well,    is that a problem?

**Comment by DavidNelsonCordelia** [comment]
A gloabl reinstall of "@aws-amplify/cli"   did not help.       When i do Amplify configure,   i get: 

? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)

and no providers are shown.

I am running on windows 10

**Comment by UnleashedMind** [comment]
@DavidNelsonCordelia 
Could you get this file  `<root>\Users\<username>\.amplify\plugins.json` and send it over to us? 
This is our email address: amplify-cli@amazon.com 

did you use "npm" or "yarn" to install the Amplify CLI? are you running on Powershell or cmd.exe?

**Comment by DavidNelsonCordelia** [comment]
Here is the file.   I am using NPM in a cmd.exe (admin )


[plugins.zip](https://github.com/aws-amplify/amplify-cli/files/3745642/plugins.zip)

**Comment by DavidNelsonCordelia** [comment]
I think I am resolved now.  I took a very careful uninstall of everthing about the amplify cli both globally and in the project.

**Comment by fabianjj** [comment]
@kaustavghosh06 
I've verified that this path is correct (I've tried both with forward slashes and escaped backslashes).

@UnleashedMind 
The command `amplify env pull --restore` does not work, as I haven't migrated to "environments" yet (I had enough issues getting through the migration as it was, and the documentation and in-cli descriptions for creating "environments" were'nt really clear about what would happen to existing data in the "NONE" environment).

I have also tried doing a global reinstall of @aws-amplify/cli and amplify-provider-cloudformation, which didn't seem to help.

**Comment by heitorlessa** [comment]
> @DavidNelsonCordelia
> Thank you, I was having this problem and also getting
> `? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)`, with nothing after it (enter would exit), when running `amplify config`. Reinstalled multiple times, nothing worked.
> 
> `amplify plugin scan` fixed it.

I've just run into this after upgrading from 3.17 to 4.2 and running **`amplify plugin scan`** resolved my issue

**Comment by ufo525** [comment]
> > @DavidNelsonCordelia
> > Thank you, I was having this problem and also getting
> > `? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)`, with nothing after it (enter would exit), when running `amplify config`. Reinstalled multiple times, nothing worked.
> > `amplify plugin scan` fixed it.
> 
> I've just run into this after upgrading from 3.17 to 4.2 and running **`amplify plugin scan`** resolved my issue

This also solved my problem on Ubuntu 19.10, thanks.

**Comment by chrisfowler** [comment]
Checking and updating the `"envName": <value>` in `amplify/.config/local-env-info.json` so it matches the `Current Environment: <value>` shown after calling `amplify status`, solved this for me. 

Can see `Current Environment: <value>` before the error text kicks in.

Not sure how it got out of whack though.

**Comment by truca** [comment]
This is my battle tested process whenever Amplify is not behaving:

(I have amplify CLI package installed globally)
- reinstall packages for amplify-cli (amplify plugins sometimes dissapear, not sure why)
- scan for amplify plugins on my project
- reconfigure project

```
cd ~/.config/yarn/global/node_modules/@aws-amplify/cli
yarn
cd -
amplify plugin scan
amplify configure project
```
