### ISSUE TITLE
gql-compile combines split extended types in built schema, but doesn't generate resolvers/cfn resources

### ISSUE THREAD

**Issue by andrew-aernos** [aws-amplify/amplify-cli#2596]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
gql-compile combines split extended types in built schema, but doesn't generate resolvers/cfn resources

Something weird on type extension within `type` marked / not marked with `@model`. I'm aware of this one issue https://github.com/aws-amplify/amplify-cli/issues/1025#issuecomment-475883560

**To Reproduce**
I'm running into something weird similar related to multiple extensions across different split schema. For example, the A is marked with @model, and B is not.

```gql
# in A.graphql
type A @model{
  content: String
}

type Query {
  echo(msg: String): String @function(name: "someFunc-${env}"
}

type Mutation {
  createA(content: String): A @function(name:"someFunc-${env}")
}
```
and in a separate `.graphql` file for B type
```gql
# in B.graphql
type B {
  content: String
}

[extend / leave out extend] type Mutation {
  createB(content: String): B @function(name:"someFunc-${env}")
}

```

Scenario 1: When I add **extend** on B's Mutation fields:

gql-compile generates build/schema.graphql does include the Mutation fields
gql-compile **doesn't** generate the resolvers in the build/resolvers '
gql-compile **doesn't** generate appsync::resolver cfn resources in build/stacks/FunctionDirectiveStack.json
amplify push will proceed, but the B's Mutation type fields are left resolver-less.

Scenario 2: When I don't add **extend** on B's Mutation fields

gql-compile generates build/schema.graphql **doesn't** include the Mutation fields
gql-compile does generate the resolvers in the build/resolvers '
gql-compile does generate appsync::resolver cfn resources in _`build/stacks/FunctionDirectiveStack.json`_
amplify push will fail with error `No field named createB found on type Mutation`

![image](https://user-images.githubusercontent.com/40867426/66966549-7c8a9a00-f032-11e9-8abf-6b5941fab08e.png)

The weird part is in the second scenario, gql-compile generates everything for fields that aren't in build/schema.graphql

**Expected behavior**

I expect when I `extend` the Mutation type with more fields, theses fields are added to the schema AND generates the appropriate resolvers and cfn to provision the resources.

**Additional context**
**Amplify CLI version: 3.11.0**

**Comment by UnleashedMind** [comment]
@andrew-aernos 
I reproduced what you reported here. 
Initially I marked this issue as a bug, because from a developer's perspective, if type extension is supported, this shouldn't be the expected behavior. 
However, the graphql.org [documentation](https://graphql.org/learn/schema/) does not have the specification for the keyword "extend". 
And the JS reference implementation does not support it either, see [issue](https://github.com/graphql/graphql-js/issues/922#issuecomment-493724046)
I've changed the tag to "enhancement", and it will pending our PM's review to prioritize its actual implementation.  
For now, do not use the keyword extend, and make sure there's no duplicate type definitions as it is a known issue per #1025

**Comment by andrew-aernos** [comment]
> @andrew-aernos
> I reproduced what you reported here.
> Initially I marked this issue as a bug, because from a developer's perspective, if type extension is supported, this shouldn't be the expected behavior.
> However, the graphql.org [documentation](https://graphql.org/learn/schema/) does not have the specification for the keyword "extend".
> And the JS reference implementation does not support it either (see [issue](https://github.com/graphql/graphql-js/issues/922#issuecomment-493724046)).
> I've changed the tag to "enhancement", our team will review and prioritize its actual implementation.
> For now, do not use the keyword `extend`, and make sure there's no duplicate type definitions as it is a known issue per #1025

To avoid duplicate type, I prefixed `extend` type with its model name. For example, type `Foo`
would have its `Mutation` rename to `FooMutation`

```
type FooMutation {
    createFoo()
    updateFoo()
}
```

on Angular, But now the generated API.service.ts doesn't generate CreateFoo(). I'm assuming the codegen only generates the Query, Mutation and other aws directive types?

**Comment by andrew-aernos** [comment]
as a hack I'm trying to copy over the built resolvers and the FunctionDirectiveStack resources into my own /resolvers and/stacks respectively, but now I'm stuck at setting up the custom stacks for `@function` type. The resolver stack my custom FunctionDirectiveStack  PipelineConfig field depends on "InvokeXXXLambdaDataSource", but the built FunctionDirectiveStack.json doesn't output this functionId


```
// generated in each resolver resource in `build/stacks/FunctionDirectiveStack.json`
                "PipelineConfig": {
                    "Functions": [
                        {
                            "Fn::GetAtt": [
                                "InvokeXXXLambdaDataSource",
                                "FunctionId"
                            ]
                        }
                    ]
                },
```
