### ISSUE TITLE
Receiving error on `amplify push`

### ISSUE THREAD

**Issue by jakobpack** [aws-amplify/amplify-cli#2599]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When trying to `amplify push`, I receive the following error while updating:
`UPDATE_FAILED      apizivi                          AWS::CloudFormation::Stack Thu Oct 17 2019 13:13:50 GMT+0200 (CEST) Parameters: [S3DeploymentRootKey, S3DeploymentBucket] must have values`.

I don't have these parameters in `api/parameters.json`. But I also don't have storage configured.

**Desktop:**
 - OS: macOS
 - Version `3.15.0`

**Additional context**

My `api/parameters.json`:
```
{
    "AppSyncApiName": "zivi",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": "false",
    "APIKeyExpirationEpoch": "0"
}
```

My `backend-config.json`:
```
{
	"api": {
		"zivi": {
			"service": "AppSync",
			"providerPlugin": "awscloudformation",
			"output": {
				"authConfig": {
					"additionalAuthenticationProviders": [],
					"defaultAuthentication": {
						"authenticationType": "AWS_IAM"
					}
				}
			}
		}
	},
	"auth": {
		"ziviauth": {
			"service": "Cognito",
			"providerPlugin": "awscloudformation",
			"dependsOn": [
				{
					"category": "function",
					"resourceName": "ziviauthPostConfirmation",
					"triggerProvider": "Cognito",
					"attributes": [
						"Arn",
						"Name"
					]
				}
			]
		}
	},
	"hosting": {},
	"function": {
		"ziviauthPostConfirmation": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		}
	}
}
```

**Comment by SwaySway** [comment]
@jakobpack Is there a deployment root key specified in the build folder?
Located in `amplify/backend/api/<API_NAME>/build/parameters.json`

**Comment by UnleashedMind** [comment]
Try to do a `amplify api gql-compile` before you push, see if that fixes the problem.

**Comment by jakobpack** [comment]
> @jakobpack Is there a deployment root key specified in the build folder?
> Located in `amplify/backend/api/<API_NAME>/build/parameters.json`

@SwaySway Yes, there is!
I tried to put these values in `api/<API_NAME>/parameters.json`, but that didn't work

**Comment by jakobpack** [comment]
> Try to do a `amplify api gql-compile` before you push, see if that fixes the problem.

@UnleashedMind Doesn't work unfortunately..

**Comment by juniarz** [comment]
Try running ‘amplify init’

**Comment by jakobpack** [comment]
> Try running ‘amplify init’

@juniarz That did something.. I'm now getting a different error:
`API key not found: <API_KEY> (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: X)`

I've tried to set the `APIKeyExpirationEpoch` to `-1` in the `api/API/parameters.json` to get a new key, but that didn't work.
I'm now stuck with this error.

Not sure if the first error has something to do with that.

**Comment by jakobpack** [comment]
I've now removed the api via `amplify remove api` and re-added it.
It's working now.

**Comment by juniarz** [comment]
Ahh sorry for the late response, you receive that error because CF is trying to remove the API key that was generated previously but could not be found because you changed the auth mode to IAM.

To resolve this issue in the future, all you have to do is:

1. Change auth mode back to API KEY
2. Amplify push
3. Change back to desired auth mode
4. Amplify push
