### ISSUE TITLE
Publish fails

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#26]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Running publish throws npm error

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
This is using an angularjs app.
ng build --prod or amplify publish
```
ERROR in node_modules/ionicons/dist/types/generated.d.ts(7,10): error TS2305: Module '"/Users/thejj/work/angular/projects/admin/node_modules/@stencil/core/dist/index"' has no exported member 'JSXElements'.
node_modules/@ionic/core/dist/types/utils/overlays.d.ts(9,82): error TS2344: Type 'keyof B' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

What is the expected behavior?
It should build successfully and publish to aws.

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
0.1.14

**Comment by kaustavghosh06** [comment]
@jarrettj Does ng build —prod throw the same error?

**Comment by jarrettj** [comment]
Yes. Correct. I've tried that.

**Comment by kaustavghosh06** [comment]
the `ng build` command is an angular command which the CLI just uses to just build your frontend app code. If that errors out I believe there's some issue with your app frontend code. (Seems like an issue with the Ionic code).

**Comment by kaustavghosh06** [comment]
@jarrettj Let me know if this issue is resolved around the `ng build` command.

**Comment by jarrettj** [comment]
Hi

Good day.

Yes it is. You can close this issue. Turned out to be a stencil, ionic and ionicons related issue. Had to downgrade ionicons.

Thanks.

Regards.
