### ISSUE TITLE
how can I include the "total" count in SearchableConnection?

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#2600]
if I specify @searchable directive, Amplify generates SearchableConnection type but it doesn't have a total int defined but response resolver has it. 
How can I include a total in the schema? or any workaround??

**Comment by houmark** [comment]
There seems to be no workaround at this time. I'm also hoping this will be wired in all the way soon as it provides useful information for pagination etc. when using ES for listing/filtering.

**Comment by UnleashedMind** [comment]
There's a PR out for this, #2602.

**Comment by SwaySway** [comment]
PR #2602 has been merged marking as pending-release

**Comment by houmark** [comment]
@SwaySway I commented on the PR right now as I believe your solution is not correct as it will just count the amount of results returning while the amount we are looking for is the *total* amount for the query ignoring `limit`. Please see my line comment on the PR.

**Comment by kaustavghosh06** [comment]
We're tracking this as an enhancement as a part of #1865
