### ISSUE TITLE
Cannot add function with CRUD function for DynamoDB

### ISSUE THREAD

**Issue by ianshea** [aws-amplify/amplify-cli#2601]
**Describe the bug**
When trying to add a function with the option "Use DynamoDB table configured in the current Amplify project" Amplify informs me "There are no DynamoDB resources configured in your project currently."

**To Reproduce**
1. $ `amplify add function`
2. Fill out details (use defaults for category & name)
3. Select CRUD function for Amazon DynamoDB table
4. Select Use DynamoDB table configured in the current Amplify project

**Expected behavior**
A selection menu of the tables in my project to select from

**Additional context**
I have 3 `@models` in my schema, and 3 tables for the current environment.

**Comment by kaustavghosh06** [comment]
@ianshea The tables which show up in that list are the DDB tables which are configured using the `amplify add storage` flow and not via the GraphQL transformer flow (with @model). Having said that, there's a PR out there - #2463

**Comment by ianshea** [comment]
Good to know. Thanks! Will keep an eye out for the release.

**Comment by kaustavghosh06** [comment]
We recently added a feature to attach a trigger to the DDB tables generated by the GraphQL transformer. You can checkout the documentation out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation
