### ISSUE TITLE
`amplify init` fails to ask providers.  amplify CLI unusable

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#2604]
**Describe the bug**
Using amplify CLI 3.15.0 on Mac OS, `amplify init` asks to select a cloud provider but proposes no option.

Consequences : 
- all subsequent `amplify` command fails.
- `providers` section of config file is empty
```
cat amplify/.config/project-config.json
{
    "projectName": "Landmarks",
    "version": "2.0",
    "frontend": "ios",
    "providers": []
}
```

- amplify-meta.json is not a valid JSON file 
```
$ cat amplify/#current-cloud-backend/amplify-meta.json
undefined
```

**To Reproduce**
```
amplify init #(accept defaults)

Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project Landmarks
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!
```

**Expected behavior**
I should be able to initialize a project with CLI 3.15 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14, building an iOS project
 - Browser n/a
 - Version 3.15.0

**Comment by sebsto** [comment]
Justed tested with a fresh React project, same behaviour.  This is not specific to iOS

**Comment by sebsto** [comment]
Revert back to version 3.0.0 is a workaround for me : 
```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project Landmarks
? Enter a name for the environment dev
? Choose your default editor: None
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
⠴ Initializing project in the cloud...
```

```
$ amplify --version && node --version && npm --version
3.0.0
v12.12.0
6.11.3
```

**Comment by sebsto** [comment]
Root cause is `awscloudformation` plugin is not activated.  CLI does not scan for plugin at startup. 
Forcing a scan with 

```amplify plugin scan```

solved the problem.

**Comment by sebsto** [comment]
amplify plugin scan is run based on the last run timestamp. My guess is whatever verision you upgraded from had a different plugin file and since the timestamp was still valid it went forward without scanning. Suggestions to fix: Always run plugin scan on init of a new project, keep track of amplify verisions and on verision upgrade force a plugin scan again.

**Comment by sgrinich** [comment]
@sebsto this reproduces for me on amplify 3.17 after running ampliy plugin scan.
