### ISSUE TITLE
How to get Origin header into lambda

### ISSUE THREAD

**Issue by austinamorusocfc** [aws-amplify/amplify-cli#2609]
** Which Category is your question related to? **
Appsync resolver lambda

** What AWS Services are you utilizing? **
Appsync and lambda

** Provide additional details e.g. code snippets **
I would like to access the http origin header in the lambda. Our team would like to be able to differentiate in our lambda if a request is coming from dev.ourdomain.com or test.ourdomain.com

**Comment by kaustavghosh06** [comment]
@austinamorusocfc Are you using Amplify Console or the CLI (S3+Cloudfront) for hosting your app? Also the CLI by default passes the "env" name i.e dev or prod to your lambda function which can be access using in the "process.env.ENV" variable in your lambda function.

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of response. Please feel free to comment on this thread if you have further questions.
