### ISSUE TITLE
`amplify publish` doesn't error out if no files were published.

### ISSUE THREAD

**Issue by allanhortle** [aws-amplify/amplify-cli#261]
**Describe the bug**
If the `DistributionDir` doesn't point to a valid folder the publish step logs out exactly the same messages as if it did point to a valid folder.

The only difference is that `✔ Uploading files successful.` happens much faster.

**To Reproduce**
1. Go to `.amplify/config/project-config.json`
2. Change `DistributionDir` to a broken path
3. run `amplify publish`
4. Notice that there is no error.

**Expected behavior**
Amplify publish should warn or error out if you have tried to publish nothing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3760524/46508054-fb28f500-c87e-11e8-84c2-26e49a49de0f.png)

**Comment by jasondebolt** [comment]
I’m having the same issue. My files aren’t being deployed to S3 and I’m not getting an error so I cannot debug.

**Comment by allanhortle** [comment]
Fair enough if you don't have the time to focus on this but its pretty developer unfriendly.
The cli lists the built files and then implies they were uploaded successfully. Could you not make a half fix and change the message to `n files uploaded successfully`? That way it would at least read `0 files uploaded successfully`

**Comment by kaustavghosh06** [comment]
@allanhortle We took your concern and submitted a PR for it out here - https://github.com/aws-amplify/amplify-cli/pull/694
I’ll update this thread when the PR is merged.

**Comment by UnleashedMind** [comment]
#694 was merged.
