### ISSUE TITLE
Change all GraphQL actions to batch

### ISSUE THREAD

**Issue by aej11a** [aws-amplify/amplify-cli#2610]
*Is your feature request related to a problem? Please describe.*
In order to create, read, update, or delete **multiple** items in DDB with *one* GraphQL request, users need to define their own resolvers / schema to use DDB batch actions. This is a complex and confusing task, even admitted by @mikeparisstuff . It is definitely a barrier for anyone new to AWS, which seems to be a huge portion of Amplify's market and userbase.

*Describe the solution you'd like*
**Convert *ALL* schema fields to batch actions by default** Any request that uses an `input` type as an argument would instead use an array of those input types.

*Describe alternatives you've considered*

1. Add batch queries and mutations instead of replacing old ones. This wouldn't be terrible but it would add a huge amount of repetitive code to the schema.
2. Continue requiring users to define their own schema for batch requests.

*Additional context*
To get one item (or create one item), the user would just pass an array containing only one input.

**Comment by undefobj** [comment]
Batch operations only have individual operations on items, so this wouldn't work since you couldn't do operations like Queries or List. You also cannot do conditions which would mean all of the `@auth` logic for writes wouldn't be usable. Finally the error handling and unprocessed keys is much more complex.

Batch operations are really great for data ingestion use cases, like when you want to write sensor data with measurements to multiple tables. They start to hit some limitations for others.

Stepping back from the implementation lets focus on your use case. What are you trying to accomplish that you cannot today with standard `@model` resolvers? Why does your use case require updating multiple items simultaneously?

**Comment by aej11a** [comment]
@undefobj thanks for your time and response.


In theory, could Amplify just map graphql queries to BatchGetItem instead of Query?


I didn’t know about the inability to use `@auth` logic


In terms of my use case, simplest way to explain it is -> a user should be able to post more than one comment on a post at once (create multiple posts at once that each have a postId linking them to the one post). Am I missing an easier way to do that?

On Oct 21, 2019, at 5:45 PM, Richard Threlkeld <notifications@github.com> wrote:

﻿

Batch operations only have individual operations on items, so this wouldn't work since you couldn't do operations like Queries or List. You also cannot do conditions which would mean all of the @auth logic for writes wouldn't be usable. Finally the error handling and unprocessed keys is much more complex.

Batch operations are really great for data ingestion use cases, like when you want to write sensor data with measurements to multiple tables. They start to hit some limitations for others.

Stepping back from the implementation lets focus on your use case. What are you trying to accomplish that you cannot today with standard @model resolvers? Why does your use case require updating multiple items simultaneously?

**Comment by undefobj** [comment]
> @undefobj thanks for your time and response. In theory, could Amplify just map graphql queries to BatchGetItem instead of Query? I didn’t know about the inability to use `@auth` logic In terms of my use case, simplest way to explain it is -> a user should be able to post more than one comment on a post at once (create multiple posts at once that each have a postId linking them to the one post). Am I missing an easier way to do that?

No the database operation would be less efficient compared to a DynamoDB operation which is optimized for efficient querying over indexes in a partitioned system with provisioned throughput. "Get" operations which Batch operations are part of the family of function to retrieve individual items which imposes certain restrictions. For instance you can only get 25 items at a time.

For your use case you can send multiple GraphQL operations at a single time, you just need to craft your statement appropriately with an alias for each different operation. For example:

```
mutation {
  createPost(input:{
    author:"First"
  }){
    id
  }
  
  Second:createPost(input:{
    author:"Second"
  }){
    id
  }
}

```

Notice I created an alias on the second mutation with `Second:`
