### ISSUE TITLE
Amplify mock keeps adding `amplify\mock-data` to the .gitignore file

### ISSUE THREAD

**Issue by ThijsTyZ** [aws-amplify/amplify-cli#2624]
**Describe the bug**
Each time I run `amplify mock` another line of `amplify\mock-data` is added to the `.gitignore` file.

**To Reproduce**
run `amplify mock`
check the .gitignore file

**Expected behavior**
If the .gitignore file already has the line `amplify\mock-data` it should not add another one

**Screenshots**

**Desktop**
 - OS: Windows 10 Pro
 - Version 1903

**Comment by ammarkarachi** [comment]
@ThijsTyZ Can you let us know the Amplify the CLI version you are using?

**Comment by ThijsTyZ** [comment]
3.9.0

**Comment by kaustavghosh06** [comment]
Fix for this has been merged and released.
