### ISSUE TITLE
amplify mock does not use the sourceDir to generate the TypeScript files

### ISSUE THREAD

**Issue by ThijsTyZ** [aws-amplify/amplify-cli#2625]
**Describe the bug**
In the project-config.json I have set the `SourceDir` value to `"projects/amplify/src"`. However `amplify mock` still generates the `mutations.ts` and `queries.ts` in the `src/graphql` folder. The `API.ts` file and the `aws-export.js` file is created in the correct location (`projects/amplify/src`)

**To Reproduce**
Change the `SourceDir` to `"projects/amplify/src"` and run `amplify mock`.

**Expected behavior**
All generated TypeScript files should be located in `"projects/amplify/src"`

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1903

**Additional context**
Complete content of `amplify/.config/project-config.json`:
```
{
    "projectName": "MyProject",
    "version": "2.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "react",
        "config": {
            "SourceDir": "projects/amplify/src",
            "DistributionDir": "projects/amplify/dist",
            "BuildCommand": "npm.cmd run-script build",
            "StartCommand": "npm.cmd run-script start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```

**Comment by kaustavghosh06** [comment]
@ThijsTyZ It looks at the src location mentioned in `<project-root>/.graphqlconfig.yml` file. Can you check that file?

**Comment by ThijsTyZ** [comment]
Thanks, that solved it. That was pointing to the wrong folder.

That was not clear that this is using a different settings file. Also during the `amplify init` it didn't ask me for this.

**Comment by ThijsTyZ** [comment]
By the way, now I changed this `docsFilePath` prop in the `.graphqlconfig.yml` file, there is actually code generated in the `API.ts` file. Before that, the `API.ts` stayed empty.

**Comment by ThijsTyZ** [comment]
So maybe there is a bug here. I will re-open this issue. If you think this is not a bug, feel free to close it.

**Comment by kaustavghosh06** [comment]
@ThijsTyZ It was a bug in a previous version of the CLI, but we fixed it and is part of the current latest version of the CLI.
Also, the path for codegen is asked not during init step but during your first push of an AppSync API.
