### ISSUE TITLE
Searchable is returning no data, but using list data was return

### ISSUE THREAD

**Issue by divait** [aws-amplify/amplify-cli#2627]
**Describe the bug**
After create my schema I try to access  the data of my team in using `listTeam()`, but for some users the data returns empty items with nextToken and have to make a while until data appear, so to avoid this I try to get the data using `searchTeams()`, but it return  empty items and not nextToken, like it was no data.

I have the following schema:

```graphql
type User
  @model
  @key(name: "ByEmail", fields: ["email"], queryField: "itemsByEmail")
{
  id: ID!
  name: String!
  email: String!
  company: String
  owner: String
  createdAt: AWSDateTime
  teams: [Member] @connection (name: "UserTeams") # One to many
}
type Team
  @model
  @searchable
  @auth(rules:[
    { allow: owner },
    { allow: owner, ownerField: "access", operations: [read] }
  ])
{
  id: ID!
  name: String!
  user: User @connection
  access: [String]!
  members: [Member] @connection (name: "TeamMembers") # One to many
}
type Member
  @model (queries: { get: "getMember" })
{
  id: ID!
  role: Role!
  createdAt: AWSDateTime
  team: Team @connection (name: "TeamMembers")
  user: User @connection (name: "UserTeams")
}
```

**Comment by houmark** [comment]
I have also experienced list queries to somewhat randomly only return some of the results expected or skipping of items, which I have not yet figured out. Adding `@searchable` to the model seems much more stable and I have not yet had items "missing" for no particular reason.

Now, did you add `@searchable` at a later time? Adding `@searchable` will not sync old items from your DynamoDB table, which could explain why you have an empty result set. A solution is to create a Lambda function and a dummy field on your `@searchable` model and then update that field, which should sync all your data to Elasticsearch. For example an `Int` field and set it to `1`. It's a bit of work, but trivial in the end.

Finally, you can load up the Elasticsearch Service dashboard, click your domain on the left, and then click Indices to see which models it has synced and then look at the `Count` value, which should be more or less the same amount of items as you have in DynamoDB table for that model.

**Comment by kaustavghosh06** [comment]
@divait As @houmark asked previously, did you add @searchable at a later stage?

**Comment by divait** [comment]
> @divait As @houmark asked previously, did you add @searchable at a later stage?

Yes

**Comment by kaustavghosh06** [comment]
@divait The CLI doesn't do a data migration for you to move existing data from DyanmoDB to Elasticsearch. You would have to do it yourself with a script to stream in existing data from DynamoDB to Elasticsearch.
