### ISSUE TITLE
Lambda environment variables wiped after changing node runtime

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-cli#2629]
**Describe the bug**

After updating my node runtime for my lambda functions from "nodejs8.10" to "nodejs10.x" the environment variables that I had assigned in the AWS Lambda console were wiped away.

**To Reproduce**

1. Launch an Amplify project with at least one lambda with the nodejs8.10 runtime
2. In the AWS Lambda console add environment variables
3. Update the \<lambdaname\>-cloudformation-template.json file so `"Runtime": "nodejs10.x"`
4. Go back to the AWS Lambda console and you’ll see that all the environment variables have ben wiped away

**Expected behavior**

I would expect the environment variables to persist. My staging environment suddenly stopped working because some needed variables were missing.

**Comment by kaustavghosh06** [comment]
@mrcoles Does your Cloudformation template have these enviornment variables? 
You can find the Cloudformation file for the function in `amplify/backend/amplify/function/<function-name>` directory.

**Comment by mrcoles** [comment]
@kaustavghosh06 no, I set them manually in AWS lambda function console page. I don’t want them in my source code and they’re also different between per env.

**Comment by houmark** [comment]
@mrcoles I'd recommend you to look at Systems Manager -> Parameter Store for "environment variables". It's straight forward to pull parameters from the store in your Lambda code and avoid using environment variables completely. This way you have them encrypted in the Parameter Store and load them in your code.

The only thing you have to make sure of is that your Lambda function has a policy to have read access to the Systems Manager and my wish is that Amplify will integrate that, so you don't have to create and attach the policy manually on each function (you only have to do this once though).

**Comment by kaustavghosh06** [comment]
@mrcoles The source of truth are the Cloudformation files and the environment variables set on the console would be erased on the next amplify push command. As @houmark recommended, if these environment variables are sensitive i would recommend using Systems Manager Parameter Store to store them, although the CLI doesn't support it out of the box today.

**Comment by mrcoles** [comment]
@houmark are there SLA performance metrics on how much time querying the Systems Manager Parameter Store would take? It feels like the temporary nature of Lambda functions means that my functions will likely have to query this store on every single request and I’d like to know that I’m not introducing a bunch of extra overhead and/or costs.

@kaustavghosh06 if I used the Systems Manager Parameter Store, could I add my own cloudformation files to my project (since I can’t use the CLI to add it) or would I just configure it separately and then reference it from within my project?

**Comment by houmark** [comment]
I cannot say but I have not noticed any slowdowns and it seems the query is cached, so it's very fast. And you can cache the result in memory of the Lambda function so you don't even go to the Parameter Store if your Lambda stays hot (and in addition, you should make sure to query all values as an array to the Parameter Store, this way you are not going to the Paraneter Store multiple times). There's a good amount of free calls to the Parameter Store included in AWS, but of course, if you are doing millions of calls per day, then you can expect an additional charge.

I would also like the possibility of having env variables integrated with Amplify, but this opens other issues of having secure values in the source code. Parameter Store has been stable for me since day one.

**Comment by kaustavghosh06** [comment]
@mrcoles Yes, you can use custom cloudformation stacks - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks or modify your lambda cloudformation stack to add the SSM resource.

**Comment by kaustavghosh06** [comment]
@mrcoles Please let us know if you still have more questions around this.

**Comment by musiquarc** [comment]
Hello, 
I had exactly the same issue -- and I understand the answer you gave, thank you very much. But isn't it a bit weird / dangerous that a simple upgrade of node can programmatically wipe out all Env Variables ? 
Thank you, m.
