### ISSUE TITLE
Allow option to create dynamo tables with encryption at rest enabled

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#263]
**Is your feature request related to a problem? Please describe.**
Tables created by amplify cli appsync api have encryption disabled. This is one of these settings that can only be turned on when tables are created. 

**Describe the solution you'd like**
An option in amplify to by default turn on encryption for tables. Why don't you always turn it on anyways? There's no cost to encryption at rest. 

**Describe alternatives you've considered**
Currently have to create dynamo db tables outside of amplify cli to get this setting.

**Comment by mikeparisstuff** [comment]
This is on our backlog along with automatically enabling auto scaling for DynamoDB tables.

**Comment by mikeparisstuff** [comment]
This has since been enabled.
