### ISSUE TITLE
Incorrectly generated schema.json for netsted objects

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-cli#2633]
**Describe the bug**
My schema.json does not have a definitions for netsted objects. My mutations and query js files are correctly generated - include all nested objects, it's just schema.json which is wrong.

**To Reproduce**

1. use schema:
```gql
type S3Object @model @auth(rules: [{allow: owner}]) {
  bucket: String!
  region: String!
  key: String!
}

type Car @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  description: String
  createdAt: String
  file: S3Object!
}
```
Amplify will generate the correct mutation/query files but schema.json definition of Car will not have S3Object. As a result i am not able to call mutations and getting error:
"The variables input contains a field name 'file' that is not defined for input object type 'CreateCarInput' ",

**Expected behavior**
S3Object should be defined in schema.json

**Smartphone (please complete the following information):**
React-native app with amplify: all mobile emulators and phones.

**Amplify context**
React Native

**Comment by Amplifiyer** [comment]
Looks like a cli-related issue. Assigning to the CLI repo

**Comment by kaustavghosh06** [comment]
@michalgarcarz Are you using the mutation generated for you by the CLI?
What's the mutation created for you in your `src/graphql/mutations.js` file?

**Comment by kaustavghosh06** [comment]
Also, you don't need @auth and @model directive on the S3Object since its just a special type - inferred by AppSync and not a model/DDB table. You can read more about it out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#s3-objects

**Comment by michalgarcarz** [comment]
hi @kaustavghosh06 - i wanted to mutate it and had a hope it's supported, but you are right, at the end i do not need it, without @auth/@model it works fine, thanks !

**Comment by michalgarcarz** [comment]
hi @kaustavghosh06 - i wanted to mutate it and had a hope it's supported, but you are right, at the end i do not need it, without @auth/@model it works fine, thanks !
