### ISSUE TITLE
amplify env checkout <env> should update aws-exports.js file

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#2635]
**Describe the bug**

When you do `amplify env checkout <env>` the `aws-exports.js` file does not update, it will still contain settings of the previous environment.

To work around this, you can do `amplify init` and choose an existing environment and choose the <env> you checkout to.

**To Reproduce**

1. Check `aws-exports.js`
2. Do `amplify env checkout <env>` 
3. Check `aws-exports.js`
4. Realize that it hasn't changed to reflect the environment settings you are in.

**Expected behavior**

`amplify env checkout <env>` should update `aws-exports.js` file to reflect the settings of the current environment you checkout to.

**Additional context**

To work around this, you can do `amplify init` and choose an existing environment and choose the `<env>` you checkout to.

**Comment by attilah** [comment]
@aprilmintacpineda it seems to be a valid request, I marked it as a bug, thanks for reporting it.

**Comment by kaustavghosh06** [comment]
@aprilmintacpineda This should be fixed in the latest version of the CLI. Please report back if you're still seeing this issue.

**Comment by KristineTrona** [comment]
I am currently on CLI version 4.11.0 and I am still having this issue. Creating a new env through ``amplify add env`` did not update aws-exports.js file. Running ``amplify init`` or ``amplify env checkout <environmentName>`` does not update the aws-exports.js either.

**Comment by superunrelated** [comment]
Still not solved as of amplify -v 4.12.0

**Comment by bwalsh** [comment]
Still not solved amplify -v 4.18.1
Disappointing.

**Comment by ivankokus** [comment]
still not solved in
amplify -v
4.40.0

**Comment by aprilmintacpineda** [comment]
Hmmm, maybe it's a recurring bug? @attilah @kaustavghosh06?

**Comment by regischow** [comment]
If you run checkout with restore it will update (v4.44.0)
`amplify env checkout dev --restore`

**Comment by maroy1986** [comment]
Still not solved as of today... Amplify 4.46.1. Pulled a fresh copy of my repo on a new computer, ran `amplify init`, choose the proper environment and whatnot, finally ran `amplify pull` and the `aws-export.js` file is not there.
