### ISSUE TITLE
Unable to add Function

### ISSUE THREAD

**Issue by fabianjj** [aws-amplify/amplify-cli#2637]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
II'm unable to upadte my backend. After receving some errors detailed in [2595](https://github.com/aws-amplify/amplify-cli/issues/2595), I was able to get a little bit closer to updating the backend.

Whenever I try to push changes, i receive the following error:

`
UPDATE_FAILED               apiicepack                  AWS::CloudFormation::Stack Mon Oct 28 2019 18:02:21 GMT+0100 (Central European Standard Time) Parameters: [S3DeploymentRootKey, 
S3DeploymentBucket] must have values

UPDATE_FAILED               authicepackcfa592d6cfa592d6 AWS::CloudFormation::Stack Mon Oct 28 2019 18:02:21 GMT+0100 (Central European Standard Time) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, allowUnauthenticatedIdentities, hostedUI, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, useDefault, userpoolClientGenerateSecret, mfaConfiguration, identityPoolName, thirdPartyAuth, authSelections, permissions, resourceNameTruncated, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, parentStack, resourceName, triggers, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, requiredAttributes, passwordPolicyCharacters, userpoolClientLambdaRole, defaultPasswordPolicy] must have values
UPDATE_COMPLETE             functionS3Triggerfb2115f4   AWS::CloudFormation::Stack Mon Oct 28 2019 18:02:21 GMT+0100 (Central European Standard Time)

UPDATE_FAILED               hostingS3AndCloudFront      AWS::CloudFormation::Stack Mon Oct 28 2019 18:02:20 GMT+0100 (Central European Standard Time) Parameters: [bucketName] must have values` 

The only change I'm trying to push is creating a lambda function.

**Desktop (please complete the following information):**
 - OS: Ubuntu WSL on Windows 10.
Powershell on Windows 10.
 

**Additional context**
I've previously tried all the suggestions in  [2595](https://github.com/aws-amplify/amplify-cli/issues/2595), but it was closed before I was able to reply.

**Comment by kaustavghosh06** [comment]
@fabianjj Can you check the version of the CLI you're using? `amplify -v` will give you that info. Also, in your `amplify/.config/localp-env-info.json` can you check the project path? Is that set correctly?

**Comment by davidbiller** [comment]
Must have values... known from this issue: https://github.com/aws-amplify/amplify-cli/issues/2519

**Comment by kaustavghosh06** [comment]
@fabianjj Were you able to resolve the issue?

**Comment by fabianjj** [comment]
@kaustavghosh06 I'm runnuiing version 3.17.0 of the CLI and the projectPath  amplify/.config/local-env-info.json points to my src folder, I've tried changing it to one step higher as well, but I get the same error. I've not been able to resolve the issue.

@davidbiller I tried the same thing as you mention in [the last comment](https://github.com/aws-amplify/amplify-cli/issues/2519#issuecomment-547128103). But I don't have an "APIKeyExpirationEpoch" in any of my project files. I think I may have previously removed it to solve a previous problem.

I receice the following error when trying to run `amplify update auth`:
```
Error: ENOENT: no such file or directory, open 'C:/Users/fabia/Documents/Web/create2/my-app/amplify/backend/auth/icepackcfa592d6cfa592d6/parameters.json'
    at Object.openSync (fs.js:450:3)
    at Proxy.writeFileSync (fs.js:1212:35)
    at Object.saveResourceParameters (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/resourceParams.js:25:6)
    at saveResourceParameters (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:110:12)
    at serviceQuestions.then (/home/fabian/.nvm/versions/node/v11.4.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:330:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
There was an error adding the auth resource
```
I've checked, and the parameters.json file does exist (It it the parameters for my existing auth).

**Comment by davidbiller** [comment]
@fabianjj 
Did you tried amplify init before?
This could help. Or pull —restore your env first

**Comment by fabianjj** [comment]
@davidbiller Thanks, that seems to have fixed my issue. I had tried that several times earlier, but I guess in between updateding the CLI and whatnot the issue is now resolved.
