### ISSUE TITLE
Elasticsearch complement for reads and writes

### ISSUE THREAD

**Issue by josoroma** [aws-amplify/amplify-cli#2638]
** Category: AppSync **

Hi hackers!

Context: Please suppose we use amplify js to create an Appsync endpoint using the **@search** directive.

I was wondering... what the differences are between using **AWS.DynamoDB.DocumentClient()** and **AWS.HttpRequest(appsyncUrl, region)** approaches. We would like to find out if both approaches are automatically using or not the Elasticsearch complement for reads and writes to the **DynamoDB + Elasticsearch** strategy?

 * https://serverless-stack.com/chapters/add-a-create-note-api.html

```
new AWS.DynamoDB.DocumentClient()
```

 * https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

```
new AWS.HttpRequest(appsyncUrl, region);
```

**Comment by kaustavghosh06** [comment]
@josoroma  With approach `1` i.e `AWS.DynamoDB.DocumentClient()` you're directly querying your DynamoDB wheras with approach `2` i.e with  `AWS.HttpRequest(appsyncUrl, region)` you'd be querying AppSync (a managed GraphQL service) using GraphQL queries.

Both the approaches will trigger the Lambda associated with the DynamoDB to stream results to Elasticsearch.

**Comment by josoroma** [comment]
@kaustavghosh06 Thank you for clarifying, very useful.
