### ISSUE TITLE
Sharing amplify config between React.JS App, and XCode Swift App.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-cli#2641]
** Which Category is your question related to? **

Amplify Cli Initialisation.

** What AWS Services are you utilizing? **

Amplify Cli

** Provide additional details e.g. code snippets **

I have a problem where, I'm developing a React.JS administrative portal... which will set up accounts, clients, users, etc... and add them to an API.

I want to also use the exact same data, inside a XCode .swift app.

If I amplify init it will remake a new project, if I amplift init project, it will allow me to pull the React.JS config into the swift project, but I don't want it to be React.JS, I want it to be XCode, so I can pull in appSyncClient, etc... and use it with XCode, is there a way to switch between React.JS and XCode/Swift, while pulling / initialising the project inside the XCode folder?

Or do I have to do something manually with the awsconfiguration.json and somehow create an API.swift...

**Comment by michaelcuneo** [comment]
I have tried copying the amplify folder to the XCode directory, then I've ran amplify configure project, and it has allowed me to switch this instance to iOS, and it appears to work fine, it creates me a awsconfiguration.json that I can add to my project, and if I run aws codegen it will recreate the src/graphql folder with my API inside... it does not however create me an API.swift file?

**Comment by michaelcuneo** [comment]
If I run the app using the ios Samples here... https://aws-amplify.github.io/docs/ios/api

I get Error initializing appsync client. invalidConfigFile

**Comment by kaustavghosh06** [comment]
@michaelcuneo Do you have a .graphqlconfig file in the root of your project? If yes, does it have the target set to swift? You can configure the target language to swift by running the  `amplify codegen configure` command.

**Comment by michaelcuneo** [comment]
I do not have this file I don't think, when I transferred the amplify folder over I didn't realise I had to also transfer over any configs. Looks like this will solve it... I'll give it a go in a few minutes and report.

**Comment by kaustavghosh06** [comment]
@michaelcuneo Please let us know if you're still stuck on this.
