### ISSUE TITLE
Simple sorting on GraphQL model

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#2643]
** Which Category is your question related to? **
GraphQL schema

** What AWS Services are you utilizing? **
amplify, appsync, dynamodb

** Provide additional details e.g. code snippets **
Consider this schema: 
```
type Category @model @key(fields: ["seoName"]) {
    seoName: String!
    name: String!
    description: String
    order: Int!
    deleted: Boolean
}
```
I want to list all my categories ordered by the `order` field.

If I modify the key as `@key(fields: ["seoName", "order"])` and I specify sortDirection in the query, the ordering does not appear to work.

I even tried to add a second `@key` condition like
```
type Category @model @key(fields: ["seoName"]) @key(name: "ByOrder", fields: ["seoName", "order"], queryField: "itemsByOrder") {
...
}
``` 
But i got an error:
```
InvalidDirectiveError: Invalid @key "ByOrder". You may not create a @key where the first field in 'fields' is the same as that of the primary @key unless the primary @key has multiple 'fields'. You cannot have a local secondary index without a sort key in the primary index.
```
I'm rather new to graphql but this is driving me crazy.

**Comment by jkeys-ecg-nmsu** [comment]
[Relevant StackOverflow question](https://stackoverflow.com/questions/58358719/graphql-sorted-query-based-on-user-attribute).

**Comment by matt-e-king** [comment]
@artecoop if you are going to declare both your primary key and a secondary index, you have to turn your primary key into a composite primary key by provide a sort key, like this:
```
type Category @model
    @key(fields: ["seoName", "createdAt"])
    @key(name: "ByOrder", fields: ["seoName", "order"], queryField: "itemsByOrder")
{
    seoName: String!
    createdAt: String!
    name: String!
    description: String
    order: Int!
    deleted: Boolean
}
```
In the snippet above notice I added "createdAt" as an example.

That said, even after getting getting rid of that error I **cannot** get a successful simple ordering to work either. I recently submitted this issue detailing my struggles: https://github.com/aws-amplify/amplify-cli/issues/2634

So I guess I'm kind of in the same boat as you still :)

**Comment by artecoop** [comment]
Yo @matt-e-king, as you can see, there are few other people waiting for this answer that, albeit simple, not so straightforward. 
I found more struggle working on amplify and graphql than with other projects, as I admit I'm pretty new on serverless and grapqhl. Let's wait an official response.

**Comment by attilah** [comment]
@artecoop please refer to my comment here: https://github.com/aws-amplify/amplify-cli/issues/2634#issuecomment-565170377 and watch the videos about DynamoDB to understand how is DynamoDB different from the SQL world (where I was also coming from).

As for your sample, you can have an additional column: ```type```  which would be used as a discriminator field for all category items and you could define a ```@key``` where with the ```order``` as the sort key:

```graphql
type Category
  @model
  @key(fields: ["seoName"])
  @key(fields: ["type", "order"], name: "byOrder", queryField: "listByOrder")
{
    seoName: String!
    name: String!
    description: String
    order: Int!
    deleted: Boolean
    type: String!
}
```

If you create some items:
```graphql
mutation CreateCategories {
  C1: createCategory(input: {
    seoName: "seo1"
    name: "Seo #1"
    order: 10,
    type: "Category"
  }) {
    seoName
  },
  C2: createCategory(input: {
    seoName: "seo2"
    name: "Seo #2"
    order: 20,
    type: "Category"
  }) {
    seoName
  },
  C3: createCategory(input: {
    seoName: "seo3"
    name: "Seo #3"
    order: 1,
    type: "Category"
  }) {
    seoName
  },
  C4: createCategory(input: {
    seoName: "seo4"
    name: "Not Seo #4"
    order: 30,
    type: "Category"
  }) {
    seoName
  }
}
```

Then you can test the ```@key``` defined query by getting all categories in descending order:
```
query ListByOrder {
  listByOrder(
    type: "Category"
    sortDirection: DESC
  ) {
    items {
      seoName
      name
      order
    }
  }
}
```

Also you get filtering capabilities as well so for example you can filter on ```name``` and get the categories in ascending order:
```graphql
query ListByOrder {
  listByOrder(
    type: "Category"
    filter: {
      name: {
        beginsWith: "Seo"
      }
    }
    sortDirection: ASC
  ) {
    items {
      seoName
      name
      order
    }
  }
}
```

I'm closing the issue as the question was answered, if something new comes up, feel free to reopen it or create a new one.
