### ISSUE TITLE
Using output of nested stacks in other nested stacks?

### ISSUE THREAD

**Issue by chadkouse** [aws-amplify/amplify-cli#2645]
I'm building my own stacks for my API and was going along great building 1 stack per dynamodb table, essentially -- 1 stack per data source since all of my basic resolvers operated on only a single data source.

However now I'm trying to include my pipeline resolvers - which include functions that reference various data sources.  I thought I would be able to get the function ids out of their stacks as `Output` properties -- but the problem is the nested stacks get created in an unpredictable order so it's a race condition if the output exists by the time I try to reference it.

I don't see a way to determine this order or tell a stack that it depends on another stack.  My solution for now is to just put all of these things into 1 big stack which isn't great for maintainability.

I also tried adding a custom stack as explained [in the docs](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks) and make it depend on my api stack but my problem there is I think the `service` still needs to be `AppSync` -- which seemed to basically just not work.  Any advice or am I stuck for now with 1 big stack?

**Comment by attilah** [comment]
@chadkouse It is not clear to me which parts of your solution are you leveraging the CLI and what is being done manually. Please explain it in more details and a look at your directory structure could also help, but we need more clarification.
That is true that currently custom stacks/resources are supported only in the API category, it is not something that we support today at project level and I assume that is something that you'd need?

**Comment by chadkouse** [comment]
Thanks for responding! To clear things up here is how I am doing things:
1. DynamoDB tables are being created and maintained manually (I just found things too easy to mess up using the schema to generate the tables)
1. Lambda functions (used in pipeline resolvers) are being created and maintained manually
1. The AppSync portion as far as defining the schema and all of it's resolvers is all being done using CFN templates and the amplify cli

Directory structure is as follows:
```
- amplify/                             
   + #current-cloud-backend/           
   - backend/                          
     - api/                            
       - myapiname/                  
         + build/                      
         - resolvers/
              ... many vtl files ...                  
         + src/                        
         - stacks/
              SomeTable.json                     
              SomeOtherTable.json
              AnotherTable.json
              ...etc...
           parameters.json
           schema.graphql
           transform.conf.json
```

I'm finding that slowly I'm having to merge all of the files under `stacks` into one big stack because they reference each others data sources (and functions) for resolvers (and pipeline resolvers) -- and I can't seem to get information about those things to be shared across the sibling stacks.  Also since I can't determine the order of the sibling stacks being created I can't ensure that their outputs will be available when needed.  Hope I'm kinda making sense here :dizzy_face:

**Comment by attilah** [comment]
@chadkouse it turns out that I was wrong about not supporting custom cloudformation resources, there is a way to include them in your project and they don't have to be connected to an AppSync API. Take a look at the documentation here if it would help your case: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks

I'd suggest to generate a GraphQL API with the CLI with some types and check out how we structure/reference the related resources, arranging the stacks. Perhaps with proper (multiple) nesting - instead of 1 big monolith - you can achieve the same for your purposes.

Regarding parameter passing, there are some samples in the comments of this issue: https://github.com/aws-amplify/amplify-cli/issues/1002

Get back to us if this helps, so we can close the issue then.

**Comment by ambientlight** [comment]
@chadkouse: most straightforward way to go is using [Fn::ImportValue](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html). For short, your nested stack outputs have extra property: `Export` that define export name. Those exported values are available globally within a aws region (you can see all exported values in CloudFormation console). They can latter be thrown in any other stack with `Fn::ImportValue`, hope this helps

**Comment by chadkouse** [comment]
I'll be trying these suggestions soon thanks for the info.  One question, you mention multiple nesting?  Is this something that can be done within my amplify project or do you mean outside of the project?

**Comment by attilah** [comment]
@chadkouse under multiple nesting I meant root-nested-nested structure, like a wrapper stack over others. I'm closing the issue as the other part of the question was answered by @ambientlight

**Comment by berenddeboer** [comment]
Note that export and import are only useful in unrelated stacks. Amplify generates a single CloudFormation stack. Particularly custom stacks in the api category are generated *concurrently*.

If you use custom stacks as per the documentation use the dependsOn feature. That works well.

**Comment by naedx** [comment]
> @chadkouse under multiple nesting I meant root-nested-nested structure, like a wrapper stack over others. I'm closing the issue as the other part of the question was answered by @ambientlight

How do I go about solving this problem using multiple nesting? I expect that I would configure a resource of type `AWS::CloudFormation::Stack`. Do I put the nested stack within the /stacks directory or elsewhere?
