### ISSUE TITLE
Removing Elastic Search with @searchable tag

### ISSUE THREAD

**Issue by walter-scott** [aws-amplify/amplify-cli#2646]
When building my API, I set up some models to be searchable by using the @searchable tag. However, even though I am not using the functionality, the Elastic Search costs are really hurting me. 

If I remove the searchable tag and do an amplify push, should that take care of everything, or do I need to also do something inside AWS to stop being charged?

**Comment by kaustavghosh06** [comment]
If you just remove @searchable tag from your schema, the elasticsearch cluster would be removed.

**Comment by hugozap** [comment]
IMO the amplify team should add a warning to the docs because adding a simple @searchable attribute results in the costs increasing dramatically. Just received a surprise billing and this was the culprit.

**Comment by JuanmanDev** [comment]
+1 https://github.com/aws-amplify/amplify-cli/issues/3860 

> @kaustavghosh06 IMO the amplify team should add a warning to the docs because adding a simple @searchable attribute results in the costs increasing dramatically so extra precaution should be taken with this. Just received a surprise billing and having an (unused) @searchable attribute was the reason.

**Comment by seanim0920** [comment]
+1

> +1 #3860
> 
> > @kaustavghosh06 IMO the amplify team should add a warning to the docs because adding a simple @searchable attribute results in the costs increasing dramatically so extra precaution should be taken with this. Just received a surprise billing and having an (unused) @searchable attribute was the reason.
