### ISSUE TITLE
AppSync with AWS_IAM Authorization support

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-cli#2647]
**Is your feature request related to a problem? Please describe.**
If my understanding is correct currently Amplify does not support AppSync with auth model AWS_IAM Authorization. The most commonly used is with Cognito User Pool.
That is causing limitations especially when working with federated identities (facebook, google).

**Describe the solution you'd like**
When "amplify add api" for graphql/AppSync we should be able to set auth model to AWS_IAM Authorization. This way in the code we should be able to run all graphql operations when having right credentials fetched for example via Auth.federatedSignIn(). 

**Describe alternatives you've considered**
RIght now we need to build roles in IAM manually (attach permissions policy for App Sync).

**Comment by kaustavghosh06** [comment]
@michalgarcarz Are you using the latest version of the CLI? We added support for IAM over a month back. Read more here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#public-authorization

**Comment by michalgarcarz** [comment]
Wow, i've missed that - that is exactly what i need, thanks !
