### ISSUE TITLE
Is there an easy way to assign a single and unique endpoint to each custom node lambda resolver?

### ISSUE THREAD

**Issue by josoroma** [aws-amplify/amplify-cli#2648]
** Category: Appsync **

Hi!

Is there an easy way to assign a single and unique endpoint to each custom node lambda resolver?

Thanks a bunch!

**Comment by kaustavghosh06** [comment]
@josoroma Are you using the Amplify CLI? And could you give us more details around the question?

**Comment by josoroma** [comment]
@kaustavghosh06 yes I do, I am using Amplify CLI, as far as I know, GraphQL approach provided by Appsync provides a unique endpoint, but I was wondering whether it would be possible to offer an endpoint for each resolver?

**Comment by kaustavghosh06** [comment]
@josoroma The way you would ideally use AppSync is that, you'll have one endpoint (best practice) and based on your request (query or mutation), the GraphQL endpoint returns the desired results (you can also specify what return values you need for your app). Read more about GraphQL out here - https://graphql.org/ and AppSync out here - https://aws.amazon.com/appsync/resources/

**Comment by josoroma** [comment]
Thanks @kaustavghosh06 

yes, I know that, One Endpoint to Rule Them All, I have been using amplify and appsync in my last 2 projects, but a client ask this because for some weird reason he wants that.
