### ISSUE TITLE
Why is my project not listed in the amplify console?

### ISSUE THREAD

**Issue by iamdavidmartin** [aws-amplify/amplify-cli#2655]
** Which Category is your question related to? **
Amplify

** What AWS Services are you utilizing? **
Amplify, AppSync, DynamoDB

** Provide additional details e.g. code snippets **
I'm considering refactoring my current backed to Amplify. I've put together a test project, added hosting, pushed it and published it. I can access the boilerplate react-app from the web. But there is no project listed in my console (https://console.aws.amazon.com/amplify/home?region=us-east-1#/).

I've double checked that I've deployed to the correct region (us-east-1).

The CLI commands I've used, in sequence, are:
amplify init
amplify add api
amplify push
amplify add hosting
amplify publish

Why isn't my project showing up in the Amplify console?

**Comment by attilah** [comment]
@iamdavidmartin Amplify CLI and Amplify Console is not connected this way, you've to add your source repository to Amplify Console and use it to build and deploy your project utilizing Amplify CLI.

Take a look at this docs page: https://docs.aws.amazon.com/en_pv/amplify/latest/userguide/deploy-backend.html

I'm closing the issue but if you think you've more question, please ask in the Amplify Console forum as it is more connected to that service.
