### ISSUE TITLE
Public graphql API - Expected type AuthStrategy, found public.

### ISSUE THREAD

**Issue by bagubits** [aws-amplify/amplify-cli#2658]
Dear all,

I have an issuee with Amplify Graphql API,
I have node 8.9, node 10.9 and node 12.13 (and I have tested with all versions, obtaining the same error).

My schema is

```
type Ad 
  @model 
  @key(fields: ["id", "status", "createdAt"])
  @key(name: "byStatus", fields: ["status", "createdAt"], queryField: "itemsByStatus")
  @auth(rules: [
      { allow: owner },
      { allow: public, queries: [get, list], mutations: null },
      { allow: groups, groups: ["Users"], queries: [get, list], mutations: null }
    ]) {
  id: ID!
  type: Animal!
  title: String!
  description: String!
}
```

When i run amplify push I get the following error

```
Schema Errors:

Expected type AuthStrategy, found public.

GraphQL request (87:16)
86:       { allow: owner },
87:       { allow: public, queries: [get, list], mutations: null },
                   ^
```

Running "> amplify --version" I get 1.12.0.
The version installed of amplify-cli is @aws-amplify/cli@3.16.0

Could you please help me finding a solution?
I double check all, also made the API again from zero but without success...

Thanks

**Comment by kaustavghosh06** [comment]
@bagubits Looks like the CLI installation isn't successful. Can you run `npm install -g @aws-amplify/cli` and make the CLI is globakly installed correctly? 
`amplify -v` should return 3.17.0.

**Comment by bagubits** [comment]
Unbelivable... My global install of the cli, was not updated. Sorry. And many thanks for support.
