### ISSUE TITLE
Added Auth with social providers using CLI, but federation providers do not show up in the Cognito dashboard

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#2662]
**Describe the bug**
We would like to use federation with custom react components (no hosted UI). So, we configured Facebook, Amazon, and Google as explained, here:  https://aws-amplify.github.io/docs/js/cognito-hosted-ui-federated-identity#google-sign-in-instructions and we used Amplify cli to add Auth + social provider ids and tokens. However, auth is not working and when I navigate to AWS Console -> Cognito -> User Pools -> myamplifyuserpool -> federation -> identity providers, the providers are not configured with the expected values. 

**To Reproduce**
Not sure

**Expected behavior**
The Cognito dashboard should show the properly configured Social Providers or an error if I'm initializing them incorrectly

**Comment by kaustavghosh06** [comment]
@ajhool In the CLI what are the steps that you followed to set this federation up?

**Comment by ajhool** [comment]
I was getting confused between Identity Pool federation and cognito pool federation. Adding the hosted ui integration has resolved the issue. I'm a little confused about how to integrate the hosted ui rather than using the Authenticator component in react, but that's a separate issue
