### ISSUE TITLE
Master and dev env confusion

### ISSUE THREAD

**Issue by chrisbyers** [aws-amplify/amplify-cli#2664]
**Which Category is your question related to?**
Not sure

**Amplify CLI Version** 
3.15.0

**What AWS Services are you utilizing?**
AppSync, Cognito, DynamoDB, and Amplify

**Provide additional details e.g. code snippets**
When I run the "amplify env list" command, it only shows "dev".  When I run npm start, it tries to connect to the dev backend.  Currently, my dev backend is not up-to-date as I have been working only with the master components.

However, if I run "amplify publish" or "amplify push", it fails when trying to push to an S3 static site. If instead I use git to commit my changes in the sandbox to my master branch, the Amplify console kicks in and builds/installs the site (everything works).  I guess I'm just confused, because when I commit files via git to the master branch (my only branch, I don't have a dev), everything is pushed seemingly okay, and the backend utilizes the -master named services.  When I run "npm start", it only utilizes the dev services.  

I don't really need a dev/master distinction for what I'm doing.  I would like to run locally using only the master backend and just do away with a dev backend altogether (for now), but I can't seem to figure out how to get the master environment out of AWS and in locally (how to get the one that already exists in AWS and is used when I check files in through git).  I basically don't understand why "master" isn't already in my local env, and/or how to get it in.

Thanks!

**Comment by jkeys-ecg-nmsu** [comment]
>When I run the "amplify env list" command, it only shows "dev".

Try running `amplify env pull master` from your master branch (assuming your prod env is named `master`).

**Comment by chrisbyers** [comment]
Thanks, I actually tried that earlier, but it says "Initializing environment: dev" then ✔ Initialized provider successfully.
Initialized your environment successfully.  After this, "amplify env list" still shows only "*dev"

**Comment by jkeys-ecg-nmsu** [comment]
@chrisbyers do you have your local `master` env version controlled? 

You could try looking in your DeploymentBucket (look in the CloudFormation root stack for your `master` project) and see if that contains a copy of your env config. I'm fuzzy as to whether or not Amplify backs up your templates to S3 (never been an issue for us with version control).

**Comment by chrisbyers** [comment]
I don't believe I ever created a local master env.  That's part of the problem.  I initially started using amplify back in March.  I don't believe the Amplify Console was available at the time.  I would just "amplify publish" following the guide, and everything worked, and there was no -dev or -master that I can recall.  I had only created a "dev" environment to start out.  I'm fairly certain there was only 1 backend resource for each resource I used as well.  Fast forward a couple of months not working on the project, and I updated to the latest amplify cli, had a ton of problems, but finally got it working by using the Amplify Console instead of publish due to some similar errors others had online, and it generated a new -dev and -master resource in all of my backend resources.  I remember being confused because my Cognito resource that I had been using stopped working and I could no longer login, so I went to look and found the new -dev and/or -master pools there.  I'm sorry if that doesn't make a whole lot of sense.  I'm still very new to most of this technology unfortunately.  I feel like I may have started using it during a heavy modification to the architecture or cli or something and my local env is just busted, but I would like to recover it if possible.

I'm not familiar with CloudFormation, new to me, but I did find the Deployment bucket under the master root stack, wasn't sure what to look for after that though.  Thanks for your time.

**Comment by jkeys-ecg-nmsu** [comment]
@chrisbyers Btw I'm not an Amp dev, just a well-intentioned Good Samaritan. (I say that because I'm often unsure of how useful my contributions are having never really done a deep dive into the CLI codebase.) 

I didn't grep from your OP that you were using the CLI and now deployed successfully to the console. So what's happening is you have **one** Amplify **CLI** (backend) environment, named `dev` -- as an aside for any future readers, if you created a single-env project before the multienv stable release, it would have been called `NONE` -- but you are connecting _two_ **branches** to the Amplify **Console**. These branches both refer to the `dev` backend. 

Does that clear up your confusion?

Obviously it doesn't help you solve the problem with not being able to publish from the command line, so if you want to elaborate on the errors you encountered with that it might be possible to get that fixed too.

**Comment by attilah** [comment]
@chrisbyers Amplify CLI environment and git branch names are now connected, it depends on you and your team how you utilize this functionality. You can find the docs about it here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#setting-up-master-and-dev-environments perhaps it helps with your understanding.

**Comment by chrisbyers** [comment]
Thanks Atilla. I already read through that documentation, which is great for setting up a new environment, but I want to pull the master env from the cloud so that when I run npm start, the local front end uses the master env. I did not see anything related to that in the documentation. My git repo is on a master branch. My "amplify env list" shows dev. What do I need to do to get master locally?

**Comment by jkeys-ecg-nmsu** [comment]
@attilah how are they connected? The documentation you link suggests giving each branch the same name as it's environment.

@chrisbyers read my comment please

>I didn't grep from your OP that you were using the CLI and now deployed successfully to the console. **So what's happening is you have one Amplify CLI (backend) environment, named dev** -- as an aside for any future readers, if you created a single-env project before the multienv stable release, it would have been called NONE -- **but you are connecting two branches to the Amplify Console. These branches both refer to the dev backend.**

Make sense?

**Comment by chrisbyers** [comment]
Thanks @jkeys-ecg-nmsu .  Yes, I did.  I am actually creating a new PWA for the same client, so I started fresh with amplify following the documentation above word for word to see what I did wrong, if anything.  I pretty much accepted the defaults, and yes I remember NONE as the env first go around.

As you mention, I suspect I got stuck in a transition from single-env to multi-env unfortunately.  I don't actually understand what you mean by two branches referring to the dev backend, but I've been messing around in the config files, maybe I'll figure something out.

Let me just make sure I state clearly again what is happening.  If I run npm start, it uses the -dev backend resources.  If I use git to commit a change, it pushes those changes to the amplify console which is only using the -master backend resources.  I only have a master branch in git.  Are you saying if I create a develop or dev branch in git, and do the push, it will use the -dev backend resources?  I would be fine with that.  I might try it anyway.  :)

I will be converting my new app (created with CLI command line) to Amplify Console soon following the guide, so maybe I will have a better understanding after that.

Thanks,
Chris

**Comment by jkeys-ecg-nmsu** [comment]
How many non-nested Amplify-managed CloudFormation stacks do you have in your account? If the answer is one, you only have one backend. I believe that for the Amplify Console, the suffix is derived _from the branch name, not the env name_.

Can you take screenshots of the backend settings for each Amplify Console branch?
