### ISSUE TITLE
How to push the modification in code after hosting react app using amplify docs?

### ISSUE THREAD

**Issue by rahuls24** [aws-amplify/amplify-cli#2665]
I host my app on S3 using amplify-cli and after some days I some change in my code that is reflect on my local machine. How to push these changes to cloud so that it will reflected on cloud also.

I am new to AWS. Please help me

**Comment by attilah** [comment]
@rahuls24 I assume you're utilizing the hosting category. When you make changes to your site code, ```amplify push``` and ```amplify publish``` commands are the ones that can help to update resources in the cloud. Please take a look at the docs and some Getting Started guides, they're the best resources in cases like this.

Docs can be found here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#hosting

Also if you'd like to publish your changes when you push to your source repository you could utilize Amplify Console to make it happen automatically: https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html

**Comment by rahuls24** [comment]
I add one new component and import it my app.js in my reactJs project but when I run amplify push then I got a message on console that no change occurs.
Please help me to commit the change to cloud as well as it only reflected on my local machine not on cloud
