### ISSUE TITLE
It is not possible to add "AWS::Pinpoint::EmailTemplate" custom resource

### ISSUE THREAD

**Issue by celica-vladimir** [aws-amplify/amplify-cli#2666]
It is not possible to add "AWS::Pinpoint::EmailTemplate" custom resource.

No such resource AWS::Pinpoint::EmailTemplate
An error occured during the push operation: No such resource AWS::Pinpoint::EmailTemplate

Amplify CLI Version: 3.16.0
 - OS: Windows
 - Node Version: v10.16.3

It seems that amplify cli is using old cfn-lint https://github.com/martysweet/cfn-lint#cfn-lint--- instead of cfn-python-lint https://github.com/aws-cloudformation/cfn-python-lint. Do you plan to switch to new one?

**Comment by celica-vladimir** [comment]
old version was poroblem

**Comment by shnjp** [comment]
If you don't mind me asking, can you tell me how you handled the situation?

In my environment, the "No such resource AWS::MediaStore:: Container" and I'm having trouble with it. I think it's because cfn-lint is deprecated, as you commented.

**Comment by Raees678** [comment]
@shnjp did you ever find an answer to this?
