### ISSUE TITLE
[Auth] Add new usergroup and admin api feature to default advanced settings

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#2668]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the solution you'd like**
When you select default configuration and after selecting how the user should sign in you are presented with a question: `Do you want to configure advanced settings?`

It would be great to add the creation of user groups and the addition of the admin API to the advanced configure settings.

**Describe alternatives you've considered**
Users can go add it later with `amplify update auth` but it might be nice for other plugins to write special permissions to the user groups file after going through the auth walkthrough.

Provide a headless way to add user groups to existing auth groups so plugins can manually add user groups if they require it or if a user wants to add it. This allows you to add more features to S3 that might be hidden by default.

**Additional context**

**Comment by josefaidt** [comment]
Closing as this has since been completed. You are now able to update/add groups from `amplify update auth`, and Admin Queries API is included in the walkthrough
