### ISSUE TITLE
generating custom variables for aws-exports.js

### ISSUE THREAD

**Issue by kkesley-shine** [aws-amplify/amplify-cli#2670]
**Is your feature request related to a problem? Please describe.**

I have a case where I have existing AWS resources and I'd like to integrate it with my React project.

The good thing about amplify is the ability to checkout an environment (e.g. `amplify env checkout dev`) and an appropriate `aws-exports.js` (in case of js project) will be automatically updated.

However, that only works when we create resources using amplify cli. It'd be really great if we can do it for existing resources. 

Example:  I have multiple Appsync API for multiple environments. It'd be great if I can save the API urls somewhere in amplify so it can be picked by my team members when they're checking out one of our amplify envs

**Describe the solution you'd like**

If there's a command to create a custom value for `aws-exports.js`, that'd be great. e.g. `amplify add variables --env dev` or something like that. and when the user executes `amplify push` the variables should appear in `aws-exports.js`

We need a solution to generate the file without pushing the backend resources as well (if no changes in backend, we can use this command). Something like `amplify push --config-only`.

The variables should not clash with existing variables generated by amplify.

**Describe alternatives you've considered**

An alternative that I can think of is to create the file manually and reference it using `process.env`. However, this is inferior compared to amplify's flexibility in swapping environment.

**Comment by jkeys-ecg-nmsu** [comment]
@kkesley-shine the AppSync API endpoint is already a part of the aws-exports.js for each env. There is currently a bug where `env checkout <env>` [does not update aws-exports.js](https://github.com/aws-amplify/amplify-cli/issues/2635).

**Comment by kkesley-shine** [comment]
@jkeys-ecg-nmsu but what if the AppSync API is not created by amplify itself? I have 2 existing AppSync API (made manually). How can I include the API endpoint in the `aws-exports.js` in a way that if I checkout to `dev` env, it will point to `appsync A` and if I checkout to `prod` env, it will point to `appsync B` ?

**Comment by jkeys-ecg-nmsu** [comment]
@kkesley-shine you would add each AppSync environment to their respective Amplify environments with `amplify api add-graphql-datasource`. [See this documentation](https://aws-amplify.github.io/docs/cli-toolchain/graphql#how-does-this-work) for an explanation of how it works.

**Comment by kkesley-shine** [comment]
@jkeys-ecg-nmsu I tried `amplify api add-graphql-datasource` but it seems to only support Aurora? Am I missing something here?

and using `amplify add codegen [--apiId <api-id>]` only works when you have 1 graphql API as it says *"Codegen support only one GraphQL API per project"* when I tried to add another API from different environment

But anyway, the feature request is not only for GraphQL API. How about existing Cognito Identity Pool resources? how can I add it in `aws-exports.js` and switch it between environments?

**Comment by jkeys-ecg-nmsu** [comment]
@kkesley-shine do you want multiple AppSync APIs per environment? I'm confused as to what you're trying to achieve here.

If you do it as described in the OP, you would not face the "one GraphQL API per project" because both environments would only have one associated API.

**Comment by kkesley-shine** [comment]
@jkeys-ecg-nmsu Sorry if I'm not being clear..

So what I'm trying to achieve is to have 1 environment connect to 1 appsync API.
Therefore, when I have _prod and dev_ environments, I'd like to have a _prod and dev_ appsync API too (**2 appsync API in total**)

However, those appsync APIs are not created by amplify (I'm using `serverless framework`). How can I put my appsync endpoint in `aws-exports` if the appsync api is not created by amplify?

Moreover, how can I put my Cognito Identity Pool ID (2 of them for _dev and prod_) in my `aws-exports`?

Ultimately, I'd like to run `amplify checkout env dev` and get that configs (1 appsync endpoint and 1 cognito identity pool id`) for dev

and when I `amplify checkout env prod`, I'd also like to get the config for prod (different endpoint and identity pool id).

**Comment by attilah** [comment]
@kkesley-shine thanks for the ideas, I marked it as an enhancement.

**Comment by renebrandel** [comment]
Hi - I'm closing this issue in favor of our RFC: #3977 
In addition, we've already started making progress in this issue with the ability to import existing Cognito resources. Check out our launch announcement here: https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/
