### ISSUE TITLE
@model and @key used together prevent fields from generating

### ISSUE THREAD

**Issue by gmreburn** [aws-amplify/amplify-cli#2671]
**Describe the bug**
Using `@model` and `@key` prevent the `id`, `createdAt` and `updatedAt` fields from being generated if any of those fields are used as fields in `@key`.

The error received in AppSync when creating the record: "Variable 'createpostinput' has coerced Null value for NonNull type 'ID!'"

I saw the VTL mutation (Mutation.createPost.req.vtl) generated applies output of `graphql-key-transformer` package before the `graphql-dynamodb-transformer` package outcome. This means the `@key` annotation uses the `$ctx.args.input.id` supplied in the request without the "cleanup" made in the other package.

When the `graphql-dynamodb-transformer` runs it overrides `$ctx.args.input.id` with `$util.defaultIfNullOrBlank($ctx.args.input.id, $util.autoId())` when the field is null. This means the VTL template interprets two different values for the same field. See screen shots for more context.

**Amplify CLI Version**
3.17.0

**To Reproduce**
add model to schema.graphql

```
type Post @model @key(fields: ["id", "createdAt"]) {
  id: ID!
  createdAt: AWSDateTime!
}
```

push changes to the cloud
```
# amplify push
```

create a post without supplying the id or createdAt field
```
mutation createPost($createpostinput: CreatePostInput!){
  createPost(input: {}){
    id
    createdAt
  }
}
```

**Expected behavior**
A new row should be created in the Post DynamoDB table with the id value built from $util.autoId() and the createdAt time should be built by $util.time.nowISO8601() in the VTL template

**Screenshots**
![image](https://user-images.githubusercontent.com/5257753/68079749-9ced7f00-fdbc-11e9-9b46-4e47172e198c.png)
![image](https://user-images.githubusercontent.com/5257753/68079782-27ce7980-fdbd-11e9-96e3-3144a03133f8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v8.11.4

**Additional context**
As a work around, the user must supply values for ID, createdAt, and/or updatedAt fields.

**Comment by attilah** [comment]
@gmreburn thanks for reporting, we'll look into it!

**Comment by VIZULR** [comment]
Hi, any news on this? I've also encountered the same issue. Like @gmreburn said, the only work around I found was to supply my own ID and createdAt values. Is there a better / alternative method to sort via createdAt? Cheers
