### ISSUE TITLE
Multi ENV - GraphQL - prevent query deleted fields

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#2675]
How do you proceed if you have two ENV, one develop a Production and you don't want to risk any errors in the GraphQL call?

Suppose I delete a field in the GraphQL API from the user.
The moment I push on Production, the users get an error in the React Native app, because the field is queried, but is not there anymore. 

Currently I use Expo OTA updates to provide the users directly with the new queries.

**Comment by undefobj** [comment]
With GraphQL when you evolve your APIs, it's generally recommended not to delete a field until you know that clients are no longer using it. So if you have a schema in production the first step should be to make a field optional, and then add any new fields as needed. When you know the field isn't being used any longer (with AppSync you can turn on logging to see the requests coming in along with the selection set) then you can safely remove the field from your schema.
