### ISSUE TITLE
Ability to delete a single resource (ideally by "resource name")

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-cli#2677]
**Is your feature request related to a problem? Please describe.**
I've just run amplify delete and deleted all resources in my environment (it did warn me)
 

**Describe the solution you'd like**
What i really would have liked to do was delete a single api-gateway or storage or lambda

**Describe alternatives you've considered**
I ran amplify delete, but this clearly isn't what I was looking for.

**Additional context**
I read the docs, but maybe I missed something?

**Comment by kaustavghosh06** [comment]
@blomm You can just an `amplify remove <category` followup by an `amplify push` to remove a specific resource from the cloud.

**Comment by blomm** [comment]
are you sure? it's not documented. 
when you say category, do you mean 'api' or 'storage'? ideally it would prompt me which resource with the category to remove, so I don't have to remove the whole 'category'

**Comment by kaustavghosh06** [comment]
@blomm It asks you to remove a specific `resource` as a part of the workflow when you run `ampllify remove <category>`. Optionally you can run `amplify remove <category> <resource-name>`

**Comment by blomm** [comment]
thanks @kaustavghosh06, are you able to update the cli documentation to include this information, for others in the future?
