### ISSUE TITLE
Lock down @key-generated GSI with @auth

### ISSUE THREAD

**Issue by patspam** [aws-amplify/amplify-cli#2681]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
3.16.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
I'm using `schema.graphql` to control my DynamoDB schema.

I needed a GSI for backend use, so I used `@key` with `queryField`. However I don't want that GSI to appear in GraphQL codegen or to be accessible from the client - am I able to suppress it and/or lock it down with `@auth`?

**Comment by jkeys-ecg-nmsu** [comment]
@patspam are you observing behavior that GSI queries are not respecting `@auth` directives?!

**Comment by patspam** [comment]
Hopefully just lack of understanding on my part (and perhaps documentation on yours..).

Does `@auth` apply to all GSIs created for a model?

**Comment by attilah** [comment]
@patspam since the ```@key``` generated queries are list operations, if you've an ```@auth``` rule for ```read``` operation those will be applied to that query as well, so you can lock it down.

I'm closing the issue, but if something new comes up or have related question, feel free to reopen it.
