### ISSUE TITLE
GraphQL: required relations are not respected

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#2682]
Amplify cli v3.17.0
Take this schema:
```
type Book @model {
    id: ID!
    isbn: String!
    title: String!
    authors: [BookAuthors!]! @connection(name: "BookBook")
}

type BookAuthors @model()  {
    id: ID!
    book: Book! @connection(name: "BookBook")
    autor: Author! @connection(name: "BookAuthors")
}

type Author @model {
    id: ID!
    name: String!
    books: [BookAuthors] @connection(name: "BookAuthors")
}
```
The above graphql code will have these requirements:
- every book MUST have 1-to-N authors
- every author can have 0-to-N books
- an author can have multiple books
- the many to many relations are granted by the type BookAuthors. Both book and author here are required.

Where is the bug? Well I can create a book without specifying authors. But the exclamation marks are in place, so a create mutation must fail if the `authors` field is not specified.

Why?

**Comment by attilah** [comment]
It is not a bug, this is how many-to-many is working. If you look at the compiled schema your create mutation type looks like this:

```graphql
input CreateBookInput {
  id: ID
  isbn: String!
  title: String!
  _version: Int
}
```

It does not have ```authors```. The connecting type must be handled separately and enforced from higher level.

If you like to enforce it at the GraphQL schema level, then you can have a custom mutation which accepts the input type as you said and use a custom pipeline resolver that updates both data sources (Book, BookAuthors) behind the scenes.
