### ISSUE TITLE
asyncWrite is not a function - NODE v10.15.1

### ISSUE THREAD

**Issue by chrisj-skinner** [aws-amplify/amplify-cli#2683]
**Describe the bug**
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

**Amplify CLI Version**
CLI install

**To Reproduce**
When installing the CLI with **EITHER** of the installs using NODE version 10.15.1
https://github.com/aws-amplify/amplify-cli#install-the-cli

**Expected behavior**
Expect a clean and easy install...

**Screenshots**
![image](https://user-images.githubusercontent.com/5794048/68202745-2e770f80-ffbc-11e9-8f1a-69be4ac18141.png)

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Node Version. 10.15.1

**Additional context**
Switched to Node v9.10.1 and install worked fine

**Comment by attilah** [comment]
Based on this: https://npm.community/t/asyncwrite-is-not-a-function-at-node-10-3-0-and-npm-6-1-0/193 it seems to be a node10 vs. npm specific issue and not related to the CLI.

Try the solutions/workarounds in the post, I'm closing the issue as it is out of scope for the Amplify CLI.
