### ISSUE TITLE
Delete Mutations do not work with both @key and @versioned directives

### ISSUE THREAD

**Issue by mdlavin** [aws-amplify/amplify-cli#2688]
**Describe the bug**
When a `@model` type has both primary `@key` and `@versioned` directives, the generated Delete*Input type is missing the `expectedVersion` attribute.  

**Amplify CLI Version**
3.17.0

**To Reproduce**
1. Create a `@model` type with a `@versioned` directive and one extra field.
2. Generate the schemas and verify that the Delete*Input type has a expectedVersion attribute
3. Add a new default `@key` directive
4. Regenerate the schemas and see that the Delete*Input type loses the expectedVersion

**Expected behavior**
The `expectedVersion` attribute should be included in the Delete*Input input type.

**Comment by mdlavin** [comment]
I believe that the problem _might_ be at https://github.com/aws-amplify/amplify-cli/blob/384e0b4a444653bafc4f8dfb377b70d50a7c0bef/packages/graphql-key-transformer/src/KeyTransformer.ts#L680 where the fields are reset without considering the expectedVersion flag. It seems like the `replaceUpdateInput` function might have a better pattern to avoid losing the expectedVersion flag

**Comment by attilah** [comment]
Thanks for reporting it is a known issue and the fix is included in this PR: https://github.com/aws-amplify/amplify-cli/pull/2628 which will be merged soon.

Meanwhile you can fix this issue by adding the given input type to your schema, that way the CLI will not overwrite it, so you can add that field.

Test it please and get back to us with the result.

**Comment by attilah** [comment]
@mdlavin did you have a chance to test the suggested workaround?

**Comment by mdlavin** [comment]
Sorry, no. Since I saw that a complete fix was coming soon, I just avoided the use of just `@key` for now. I can try your workaround this morning in about a two hours

**Comment by mdlavin** [comment]
The workaround does not appear to work for me. The generate schema seems to override the `Delete*Input` type that I added and the same problem of a missing `expectedVersion` error happens

**Comment by attilah** [comment]
Closing the issue as the fix is released.
