### ISSUE TITLE
Updating an amplify Auth implementation

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#2691]
**Which Category is your question related to?**

Auth

**Amplify CLI Version** 
3.12

**Provide additional details e.g. code snippets**

Using the CLI is great to get started, but incredibly difficult (in my opinion) to make changes.

I have a working Signup, Sign-In, Forgotten Password etc...  process which also uses a Lambda trigger to add a user to a group... I would like to add an additional "Post Confirmation" trigger, but I can't seem to do this without impacting existing settings.

When I ....

`amplify update auth`

it is very difficult to walk through the existing settings without making changes.. I simply want to add a new "custom" Lambda trigger, but I'm diffing the existing files and seeing multiple changes such as:

`
-    "authSelections": "identityPoolAndUserPool",
+    "authSelections": "userPoolOnly",
`

At this point, I have backed out of the change, reverted all files and regretted starting this project with amplify.

How do I make a simple update like adding a new Lambda PostConfirmation module?

**Comment by amirmishani** [comment]
@danhumphrey I have the same question, did you find your answer is that why you closed this question?

**Comment by danhumphrey** [comment]
> @danhumphrey I have the same question, did you find your answer is that why you closed this question?

Hi @amirmishani, I find the update process to be clunky as the CLI prompts don't always default to the previously selected options and it's pretty easy to inadvertently choose a different option during update. This is what I had done in this instance and maybe you have done the same?

**Comment by swaminator** [comment]
@danhumphrey sounds like a quick UX fix. Do you mind walking through your step-by-step flow after doing `amplify update auth`?

**Comment by NTonani** [comment]
@danhumphrey Would also appreciate the steps you took to add a lambda trigger. I do not see that functionality supported through the CLI based on options presented to me with `amplify auth update`:

> Apply default configuration with Social Provider (Federation)
  Walkthrough all the auth configurations
  Create or update Cognito user pool groups
  Create or update Admin queries API

I am using `4.6`. Apparently you were able to do this with `3.12`?

**Comment by NTonani** [comment]
Seems this worked for me -

1. `Walkthrough all the auth configurations`
2. `User Sign-Up, Sign-In, connected with AWS IAM controls...` NOTE: Use this as otherwise CFN update will fail with missing IdentityPoolId. See https://github.com/aws-amplify/amplify-cli/issues/2096#issuecomment-523746110

Eventually there is the following - `Do you want to configure Lambda Triggers for Cognito?` 
Can then select trigger and provide custom logic.

**Comment by danhumphrey** [comment]
> Seems this worked for me -
> 
> 1. `Walkthrough all the auth configurations`
> 2. `User Sign-Up, Sign-In, connected with AWS IAM controls...` NOTE: Use this as otherwise CFN update will fail with missing IdentityPoolId. See [#2096 (comment)](https://github.com/aws-amplify/amplify-cli/issues/2096#issuecomment-523746110)
> 
> Eventually there is the following - `Do you want to configure Lambda Triggers for Cognito?`
> Can then select trigger and provide custom logic.

Yep, that's what I did.

**Comment by pantareh** [comment]
> 
> 
> @danhumphrey sounds like a quick UX fix. Do you mind walking through your step-by-step flow after doing `amplify update auth`?

@swaminator, @danhumphrey, what's the resolution here? should we follow the cli or update the amplify generated configuration files directly?

Thanks

**Comment by danhumphrey** [comment]
Hi @pantareh I'm not sure where this currently stands as this is 7 months old. Initially, I found the CLI difficult to follow and repeat the original config options, but I think that it was eventually resolved using only the CLI and not resorting to editing files.

@swaminator my suggestion (for all CLI actions) would be an easy to read history of all questions, options and inputs in a history file, organised in a single file as per the CLI inputs and outputs.

**Comment by pantareh** [comment]
@danhumphrey 
Yes. I just realized that. thanks!
I still don't understand why this approach is chosen over file editing. With file editing you can diff and track changes. It's weird that that CLI is now practically becoming a chat UI with all these questions :-)
