### ISSUE TITLE
@connection and sorting direction

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-cli#2692]
**Which Category is your question related to?**
GraphQL

**Amplify CLI Version** 
v3.17.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**

I find amplify documentation in it's simple form, confusing.
Get this schema
```
type Book @model {
    id: ID!
    title: String!
    prices: [Price]! @connection(name: "BookPrices", sortField: "validity", limit: 1)
}

type Price @model {
    price: Float!
    validity: AWSDateTime!
    book: Book! @connection(name: "BookPrices", sortField: "validity")
}
```
It's easy to define a query in graphiql (both on mock and production) that show a book and it's last price (by using the `validity` field as sort field).
```
query MyQuery {
  __typename
  getBook(id: "12345") {
    title
    prices(sortDirection: DESC) {
      items {
        price
        validity
      }
    }
  }
}
```
Now, I want to replicate the same query on my javascript app (it's an angular app written in typescript if that can help), but I don't know how, and I can't find any direction on amplify documentation.

Please help

**Comment by attilah** [comment]
After you generate the code with ```amplify codegen``` for angular project the CLI generates a ```src/app/API.service.ts``` file (with default settings) which contains all the default queries and mutations as callable code.

Based on that you can add your custom queries to other parts of the code wherever you like.

I'm closing the issue, but if something new comes up feel free to reopen it.

**Comment by artecoop** [comment]
@attilah thanks for your response. What I cant find in documentation is how to create a custom query. Being a young tech, I can't find a tutorial on internet. Could you please point me in the right direction?
