### ISSUE TITLE
Error thrown Expecting a Boolean got string_input_userpoolClientGenerateSecret

### ISSUE THREAD

**Issue by purefan** [aws-amplify/amplify-cli#2693]
**Describe the bug**
Running `DEBUG=* amplify mock` 
```
? Are you sure you want to continue? Yes
2019-11-06T10:48:58.344Z - debug: Error thrown: crit: Expecting a Boolean, got 'string_input_userpoolClientGenerateSecret' (Resources > UserPoolClient > Properties > GenerateSecret)
2019-11-06T10:48:58.347Z - debug: Error thrown: crit: Expecting a Boolean, got 'string_input_allowUnauthenticatedIdentities' (Resources > IdentityPool > Properties > AllowUnauthenticatedIdentities)
```

To fix it I edited the cloudformation-template.yml file:
```
   allowUnauthenticatedIdentities:
     Type: String
+    AllowedValues: [true, false]

   userpoolClientGenerateSecret:
     Type: String
+    AllowedValues: [true, false]
```

I believe these are set [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js#L38) and [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js#L58)

Can open a PR if wanted

**Amplify CLI Version**
3.17.0

**To Reproduce**
`amplify mock`

**Expected behavior**
Not to show errors

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v10.17.0

**Comment by attilah** [comment]
@purefan what is contained in your project that produces this? just having a user pool will generate these debug errors? Could you add the repro steps?

PRs are always welcome, go ahead and submit a fix+test, thank you!

**Comment by purefan** [comment]
Hi @attilah I think its just that, a user pool, nothing special in this project to be honest. A colleague of mine initialized the amplify project a couple of hours before I got to this error so Im pretty sure its a barebones project. Will work on adding a couple of tests and the PR during the weekend, small changes really but they get labeled as critical (or thats how I interpret _debug: Error thrown: crit_) and for a newcomer they can be really confusing ("what did I do to trigger this?")

**Comment by nikhname** [comment]
Hey @purefan! Do you have any updates on your PR for this?

**Comment by kaustavghosh06** [comment]
@purefan Would be great if you could let us know if you're looking into the fix for this.

**Comment by purefan** [comment]
Hi guys, sorry, the end of the year kept me busy. I did try to write tests but even following the Contrib file instructions I kept getting errors, and without tests I cant push a merge request. In another issue someone from the team managed to write some tests for my code and that seems to be going forward, it requires 3 pairs of eyes to approve and that takes time...

**Comment by edwardfoyle** [comment]
Hi @purefan, just tried to repro this issue with the latest version of the CLI and was unable to. Feel free to reopen if you are still running into this with the latest version.
