### ISSUE TITLE
Auth Lambda Triggers and Storage

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#2696]
**Which Category is your question related to?**

Auth / Storage

**Amplify CLI Version** 

3.12.0

**What AWS Services are you utilizing?**

Auth and Storage

**Provide additional details e.g. code snippets**

I want my custom Post Confirmation trigger to have access to my storage arn - how can I do this locally so that it persists and can safely be pushed to other environments? 

Is my only option to edit the '...PostConfirmation-cloudformation-template.json' file? Is this safe to do?

**Comment by kaustavghosh06** [comment]
@danhumphrey Did you try `amplify function update` and give it access to your storage resource?

**Comment by danhumphrey** [comment]
No, I didn't know I could do that - thank you.
