### ISSUE TITLE
AMPLIFY PUSH FAILING IN RECENT DAYS - IDENTICAL CONFIG PREVIOUSLY WORKED

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#2697]
**Describe the bug**
My Cloudformation Stack starts with status "UPDATE_COMPLETE" (Green) before I initiate amplify push. The code I push is correct - last week it correctly pushed and updated on the cloud. But now this same code is failing with the following error

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

I have reproduced this in two separate accounts and get identical results.

If I look at the Cloudformation Events for this stack I see that the earliest error event was this...

Embedded stack arn:aws:cloudformation:XXXX was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [CustomResourcesjson]. 

So I manually do "Continue update rollback" from the Stack Actions menu on the Cloudformation console. This fails a couple of times, but eventually I get back to status "UPDATE_ROLLBACK_COMPLETE".

**Amplify CLI Version**
Amplify 3.17.0

**To Reproduce**
I'm not sure how to reproduce outside of my environment.

However, I have the following steps work around the problem.

- I perform the PUSH as defined above (amplify push --no-gql-override --yes)
- The push fails as described above
- Go to CloudFormation and Continue Update Rollback until the Stack gets to "UPDATE_ROLLBACK_COMPLETE" status.
- I perform PUSH again and after it starts to deploy I terminate  (CTRL-C) which causes the CloudFormation stack to terminate the update and returns to the "UPDATE_COMPLETE" status (Green).
- I peform PUSH again and it successfully deploys.

If I follow that workflow every time in every account is successfully deploys - but it always fails first as described.

**Expected behavior**
Successfully push changes to the cloud without having to follow this workflow. Last week the same code was deploying successfully - this week it is not.

**Desktop (please complete the following information):**
 - I am using Cloud9 to run Amplify
 - I am using Node 10.16.0

**Additional context**
I have a large database with 44 Tables in DynamoDB. I have progressively pushed this database to the cloud in order to work around the GSI limitations. I have identical instances in DEV, TEST, PROD in completely separate accounts and the issue is being experienced in all accounts.

**Comment by sacrampton** [comment]
Stacks that appear to be consistently causing issues are [SearchableStack, ConnectionStack, ConnectionStack2]. I use transform.conf.json to overflow resources from ConnectionStack to ConnectionStack2 - I have over 300 resources defined across these 2 stacks.

**Comment by kaustavghosh06** [comment]
@sacrampton Ddi you upgrade your CLI from last week to this week?

**Comment by sacrampton** [comment]
I didn't upgrade the CLI - the problem occurred on a version that was previously working (3.15.0).  However, in an effort to see if a newer version of the CLI fixed the problem I upgraded to 3.17.0

**Comment by sacrampton** [comment]
If I keep doing the manual go to CloudFormation and Continue Update Rollback until the Stack gets to "UPDATE_ROLLBACK_COMPLETE" status then amplify push it will eventually succeed - but it can take many times of pushing, failing, rollback before it actually does succeed. Again, the fact that it eventually succeeds means that my schema.graphql and the rest of the build is valid.

**Comment by attilah** [comment]
@sacrampton can you reproduce it outside of Cloud9, locally with your environment? Do you've custom content in CustomResources.json?

**Comment by sacrampton** [comment]
I have not tried to reproduce outside of Cloud9 (its a non-trivial exercise for me to do that - I use Cloud9 because I've set it up to be many times faster than my local environment). However, the issue is identical on 3 separate Cloud9 instances in 3 separate AWS accounts. I do have a lot of custom content in CustomResources.json - however there have been no edits to this file since 18th October (exactly 3 weeks ago - and this problem only started in recent days).

I am eventually able to get a successful push every time - but it might take me 4 or 5 attempts to do so and having to manually roll back in CloudFormation each time.

**Comment by sacrampton** [comment]
Whatever was done on the Cloudformation side of things seems to have resolved itself.
