### ISSUE TITLE
Issue running mock via CLI

### ISSUE THREAD

**Issue by forstmeier** [aws-amplify/amplify-cli#2704]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Running mock via CLI

**Amplify CLI Version** 
3.17.0

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Lambda and DynamoDB

**Provide additional details e.g. code snippets**
I'm in the process of adding `@auth` to several types and I wanted to run the server locally to test against the mock. To do that, I wanted to try running `amplify mock` but that generates the following error:

```
The following types do not have '@auth' enabled. Consider using @auth with @model
	 - Billing
	 - Connection
	 - Datastore
	 - Package
	 - PackageConnection
	 - Action
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 

Failed to start API Mock endpoint Error: openIDConnectConfig is not configured for defaultAuthentication
```
I'm unable to pin down the exact source of the error regarding the configuration message above.

**Comment by markwhitfeld** [comment]
If you just run the `amplify update api` command and follow the prompts to set the authentication details for open id connect then that should create the correct settings in your amplify metadata for you.

**Comment by yuth** [comment]
The graphql transformer checks to see the requested provider like `oidc` is enabled for GraphQL API and throws error if  they are not enabled. Like @markwhitfeld mentioned, run `amplify api update` and when updating the setting select `Yes, I want to make some additional changes.` for ` Do you want to configure advanced settings for the GraphQL API` and enable `OpenID Connect`
