### ISSUE TITLE
@function calls deployed function not created with amplify

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2707]
**Which Category is your question related to?**
api, graphql transform, function

**Amplify CLI Version** 
3.15.0

When using `@function` to connect to lambdas deployed outside of amplify is it possible to include the env variable to manage connecting to the environment's version of that function? Assuming that we follow the same naming convention that maps to the envs setup in amplify.

**Comment by kaustavghosh06** [comment]
@aireater Do you want to pass env variable to the lambda function deployed outside an amplify project as a part of the graphql annotated schema?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of information requested. Please comment on this if you're still stuck on this and want us to re-open.
