### ISSUE TITLE
Authoring custom Graphql transformer documentation or example

### ISSUE THREAD

**Issue by moshir** [aws-amplify/amplify-cli#2713]
**Which Category is your question related to?**

Writing a custom Graphql transformer, as suggested [here](https://aws-amplify.github.io/docs/cli-toolchain/plugins#custom-graphql-transformers)

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
Mostly dynamodb, lambda, elasticsearch

**Provide additional details e.g. code snippets**
Hi, i've been searching for a way to write a custom Graphql trasnformer
The documenation mentions the `graphql-transform` package, but i did not find hhow to write my own transform, and how the cli can support adding one. 

Is there any documentation or example about writing a simple one ?

**Comment by yuth** [comment]
We have to docs for custom transformer plugin in PR https://github.com/aws-amplify/docs/pull/992/

**Comment by hisham** [comment]
Here's an example I just published: https://github.com/hisham/graphql-lowercase-transformer

@lowercase transformer to convert strings to lowercase before saving to dynamodb.
