### ISSUE TITLE
how to run a function before all generated resolvers ?

### ISSUE THREAD

**Issue by moshir** [aws-amplify/amplify-cli#2714]
**Which Category is your question related to?**
`@function` directive 

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
lambda, dynamodb

**Provide additional details e.g. code snippets**

As an example, i have a custom lambda function which performs custom **authorization** checks before an action. (@auth directive does not match my requirements, where users can belong to hundreds of groups). The function acts as a gate keeper, throwing an Unautorized exception when the user is not allowed to perform the action on a resource, otherwise forwarding  the initial request.

I'd like to run this "gatekeeper" function before the generated vtl runs.
As per the documentation, the @function directive overrides the vtl.
Is it possible to implement some sort of pipeline resolver mixing lambda and vtl.

Another example might be to use a custom lambda function to filter items out from a vtl.

I was thinking about a custom directives like 
```graphql
enum Action{
  CREATE 
 UPDATE 
 DELETE
 ALL
}
directive @before(actions:[Action], function:String!) on OBJECT


```

That would be used as follow:
```graphql

type MyType 
@model
@before(actions:[ALL], function : "check"){
   id : ID! 
  name : String!
  description : String
}
```
When query/mutation is run, the check function is called with all initial arguments, the function performs whatever logic it needs to do and can also update the arguments, including $context.stash and the execution resumes to the generated VTL.

**Comment by yuth** [comment]
Amplify CLI out of the box won't have support for this but a custom directive can be written as you mentioned. We recently added support for custom transformer plugin. We have docs for [transformer plugin](https://aws-amplify.github.io/docs/cli-toolchain/plugins#custom-graphql-transformers) and docs for how to use these custom plugins in PR https://github.com/aws-amplify/docs/pull/992.

The other alternative is to chain `@function` directive as [documented](https://aws-amplify.github.io/docs/cli-toolchain/graphql#function) under `Chaining functions` section

**Comment by deagudelo** [comment]
Did you solve this issue? Is that directive available somewhere? What about an @after following similar logic?
