### ISSUE TITLE
Documentation for autogenerated non-core/unexpected lambda resources

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#2716]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
We're trying to account for the resources that Amplify autogenerates and are having difficulty understanding some of the resources that appear to be meta-resources. For instance, the Auth module generates a Cognito userpool and IAM policies (as would be expected) but also appears to generate 4 lambdas (possibly more for other amplify configurations):

```
OAuthCustomResource
HostedUICustomResource
HostedUIProvidersCustomResource
UserpoolClientLambda
```

It's unclear if these resources are used at runtime or just as deployment utilities. 

**Describe the solution you'd like**
If these are runtime resources, then documentation for these resources explaining what they do. The documentation could exist in a section in the general docs and/or in the actual lambda function code, which can be viewed in the aws console.

Alternatively, if these are just deployment utilities, then they should be cleaned up after use.

**Describe alternatives you've considered**
Reading the code. The functions appear to return a secret, but it is unclear when these functions are called and what exactly they're doing.

**Additional context**

**Comment by yuth** [comment]
These resources are deployment utils. These are created as the some the resources that Amplify CLI wants to provision are not exposed as CloudFormation resource types and the only way to provision them using cloudformation is to use CustomResources as described in [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html)

> Alternatively, if these are just deployment utilities, then they should be cleaned up after use.

These resources lambdas are provisioned and maintained by CloudFormation stack and are used to update and delete these resources in subsequent cloudformation update. These can be removed only when the CloudFormation stacks get delete
