### ISSUE TITLE
Where to put custom GraphQL Transformer

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#2718]
I've been reading documentation here: https://aws-amplify.github.io/docs/cli-toolchain/plugins?sdk=js#custom-graphql-transformers

I didn't find an information about where do i put my transform code so amplify will use it?

Can you please provide an example on where to put and how to connect it with the existing amplify project

**Comment by yuth** [comment]
The docs for custom transformer plugins are in PR https://github.com/aws-amplify/docs/pull/992/

**Comment by kaustavghosh06** [comment]
@artyom-melnikov Please let us know if you're still stuck on this based on the response above. Closing this issue for now.
