### ISSUE TITLE
Question on sorting using @searchable and searchXXX methods

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2720]
I am having issues getting the sort order correct on query searchXXX methods.

This works in AppSync. Data is ordered correctly:

```
query searchProviderRatingss {
  searchProviderRatings(filter: { providerId: { eq: "123" }}, 
    sort: { field: createdAt, direction: desc }) {
    items {
      id
      createdAt
    }
  }
}
```

In code if I specify the sort like this:

``
let sort = { field: "createdAt", direction: "asc" };
``
``
queries.searchProviderRatings ( {filter}, {sort} )
``

It does not work. Query returns but not sorted.
I cannot specify the fields as in AppSync as the code would not compile.

How should the sort be specified in code so that it works as it does in AppSync?

**Comment by yuth** [comment]
@blairtaylor which client are you using to run the query. Is it Amplify GraphQL Client or AWS AppSync SDK?

**Comment by blairtaylor** [comment]
Amplify GraphQL Client

**Comment by yuth** [comment]
You should have a generated query for `searchProviderRationgs` 
```javascript
const searchProviderRating = `query searchProviderRatings(
    $filter: SearchableProviderFilterInput
    $sort: SearchableProviderSortInput
    $limit: Int
    $nextToken: String
) {
    searchProviderRatings(filter: $filter, sort: $sort, limit: $limit, nextToken: $nextToken) {
        items {
            id
            createdAt
        }
    }
}`
```

The above query takes a`filter` and `sort` arguments which can be passed using the following code

```javascript
const result = await API.graphql(
    graphqlOperation(searchProviderRating, {
        filter: { providerId: { eq: '123' } },
        sort: { field: 'createdAt', direction: 'asc' }
    })
);

```

**Comment by blairtaylor** [comment]
Thanks. That is working for me now.
