### ISSUE TITLE
Use existing backend like Cognito user pools and DynamoDB tables  to a new backend

### ISSUE THREAD

**Issue by yahavb** [aws-amplify/amplify-cli#2721]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
We use the CLI for deploying backend components like Cognito user pools, lambda functions, GraphQL etc. We also use the amplify console to deploy the frontend components, which is based on React. As far as frontend application updates, every time we have new version coming up, we deploy it as a new GitHub branch as frontend in the amplify console that uses existing backend. We test, and then we merge to the master branch. For this scenario, we are all good. 

However, when we need to update backend components, we get into situations that require us to rebuild the entire backend components. This is a great concern for us as we need to restore existing data from existing components like DynamoDB, cognito user pools and S3 buckets. We explored a few ways to solve this issue. The first was to deploy new resources and restore from old ones. This is sub-optimal in the case of DynamoDB and Cognito. DynamoDB charged by I/O and we end up paying more than we want for this migration every time Amplify CLI has an issue. Cognito backup and restore requires the migrated users to verify the email, mobile number again as the verification token is not migratable. 

**Describe the solution you'd like**
We want to be able to specify existing backend components that holds live data like user info

**Describe alternatives you've considered**
We  built backend resources like Storage and Auth using existing resources. We were able to succeed with the storage but could not do it with Cognito. We could not do it because it complicates the deployment process and force us to modify CloudFormation templates in undocumented places. 

**Additional context**

**Comment by yuth** [comment]
Amplify CLI uses cloudformation under the covers to manage all the AWS resources. Cloudformation does not allow attaching existing resources to an stack.

> However, when we need to update backend components, we get into situations that require us to rebuild the entire backend components. This is a great concern for us as we need to restore existing data from existing components like DynamoDB, cognito user pools and S3 buckets.

Could you elaborate why the entire backend needs to be rebuild when you have to update the components? The cloudformation should handle updating of existing resources without loosing data. Is there any specific problem that you faced when updating existing resources?

**Comment by jkeys-ecg-nmsu** [comment]
Hey @yuth,

What an unfortunate time to mention CF doesn't support importing existing resources :P

https://aws.amazon.com/blogs/aws/new-import-existing-resources-into-a-cloudformation-stack/

CF now supports it natively as of today, so there's no service (CF) reason that Amplify cannot allow importing existing resources.

**Comment by undefobj** [comment]
@jkeys-ecg-nmsu the individual services still need to onboard to this functionality before Amplify can use the feature. There are only a handful today: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by jkeys-ecg-nmsu** [comment]
Hope to see this soon to make Amplify CLI operations more forgiving. (I also want soft deletion of AppSync APIs -- endpoints and IDs -- and Cognito app clients, but that's outside of your control.)

**Comment by renebrandel** [comment]
Hi - I'm closing this issue in favor of our RFC: #3977 
In addition, we've already started making progress in this issue with the ability to import existing Cognito resources. Check out our launch announcement here: https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/
