### ISSUE TITLE
CMD file with amplify cli

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-cli#2724]
**Which Category is your question related to?**
Utility, CI/CD

**Amplify CLI Version** 
Newest version

Hi I wonder if you have an example of running amplify cli command using .cmd file or .sh file? I want to incorporate amplify aws with Jenkins to automate the setup of amplify project.

**Comment by yuth** [comment]
We have [documentation](https://aws-amplify.github.io/docs/cli-toolchain/usage#headless-mode) of headless mode and some sample headless [scripts](https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-cli/sample-headless-scripts) in our repository.

**Comment by totaland** [comment]
Thank you, it is exactly what I wanted.
