### ISSUE TITLE
amplify mock - RDS and Elasticsearch & custom Elasticsearch

### ISSUE THREAD

**Issue by phngs** [aws-amplify/amplify-cli#2725]
Hello,

1.) Am I right that mocking to develop locally currently only works for DynamoDB and Lambda, but not RDS (Aurora Serverless with DataAPI) and Elasticsearch?
How do you develop your GraphQL schema and queries? Always deploying them?

2.) Is it possible to use ES without having it created by Amplify, i.e. deploy it myself and enter it in one of the config files. The requirement here would be to have different ES clusters for different Amplify environments (e.g. dev & prod).

Thanks

**Comment by yuth** [comment]
> 1.) Am I right that mocking to develop locally currently only works for DynamoDB and Lambda, but not RDS (Aurora Serverless with DataAPI) and Elasticsearch?
How do you develop your GraphQL schema and queries? Always deploying them?

Mock does not support running RDS and ElasticSearch at this time. At this time only the way to to test them is by deploying them.

>2.) Is it possible to use ES without having it created by Amplify, i.e. deploy it myself and enter it in one of the config files. The requirement here would be to have different ES clusters for different Amplify environments (e.g. dev & prod).

Unfortunately there is no out of the box support for this. One workaround might be to use `@function` directive to call a custom lambda function which could be used to communicate with the ES cluster
