### ISSUE TITLE
Socket hang up during 'amplify push'

### ISSUE THREAD

**Issue by paragao** [aws-amplify/amplify-cli#2726]
**Describe the bug**
After the project is created, and some resources are added (such as API, Notifications, Storage, and so on), when running 'amplify push' sometimes it may hang up with the message: "socket hang up". When that happens, the console hangs in a specific part of the update and keep showing the same message 'Updating resources in the cloud. This may take a few minutes...' . The command never finishes running but the resources are updated successfully in the cloud. The problem is that if you run a 'amplify status' after canceling the above command, then the status of the resource will show up as it has not been updated. 

**Amplify CLI Version**
3.17.0

**To Reproduce**
Difficult to say because it is intermitent. I have checked my internet connection and everytime that happened I had stable connectivity to the cloud (was using AWS Console, for example) and it wasn't a connectivity to the cloud problem.

**Expected behavior**
When running 'amplify push' that the command returns correctly and update the status of the resources deployed in the cloud.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (Mojave)
 - Node Version: v10.16.0

**Additional context**
OUTPUT: 
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE apireactadmingeofences                  AWS::CloudFormation::Stack Wed Nov 13 2019 10:28:33 GMT-0200 (Brasilia Summer Time) 
UPDATE_COMPLETE reactadmingeofences-beta-20191026151323 AWS::CloudFormation::Stack Wed Nov 13 2019 10:28:33 GMT-0200 (Brasilia Summer Time) 
⠏ Updating resources in the cloud. This may take a few minutes...(node:39477) UnhandledPromiseRejectionWarning: NetworkingError: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:39477) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39477) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Updating resources in the cloud. This may take a few minutes...^C

**Comment by jkeys-ecg-nmsu** [comment]
If the update is successful but the local #current-cloud-backend folder is not updated to match -- which I think happens after push is successful -- that would explain why you're getting an Update instead of No Operation.

If you try running `amplify env pull <env-name> --restore` does it work to restore your local enviro to match what you had just pushed? (Make sure you're using version control before running this operation...)

**Comment by yuth** [comment]
Push operations are idempotent. So running push once again should not change anything in the cloud and it should be pretty quick as there are no changes to cloud resources.

Amplify CLI Polls the cloudformation to show the status. From the error it looks like the error is happening when polling the CloudFormation. I am marking this as an enhancement to better handle the polling error

**Comment by jkeys-ecg-nmsu** [comment]
@yuth in OP's example the CF update succeeds but Amplify CLI thinks it failed and is still showing Update operations.
