### ISSUE TITLE
Updating Authorization Mode in Amplify-CLI

### ISSUE THREAD

**Issue by Rodiot89** [aws-amplify/amplify-cli#2729]
** Which Category is your question related to? **
Amplify CLI 3.14.0

** What AWS Services are you utilizing? **
Appsync / Amplify CLI / GraphQL

** Provide additional details e.g. code snippets **
I can change the authorization mode for my AppSync api in the browser, i.e. from API Key to Cognito user pools. By copying the new appsync config into the awsconfiguration.json and updating my code the app runs fine.
However, performing an "amplify push" resets the local configuration to API Key.
How can one change the authorization mode via the amplify cli?

**Comment by yuth** [comment]
Updating API Auth mode can be  done by running `amplify api update`. Feel free to comment here if you still have additional question

**Comment by Rodiot89** [comment]
I currently dont have an auth method attached in amplify cli, meaning when I run `amplify status`  only the api is showing up. When I run `amplify api update` it wants to create a new userpool, which is not what I want because I already have my pool running.
But than the question is where does the backend get the information from to reset the auth method?
