### ISSUE TITLE
Invalid lambda function output : Invalid JSON

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#2735]
**Describe the bug**

I'm using amplify auth and have a working model which uses a post confirmation hook with the following functionality:

- add user to group
- custom (added later)

My custom function is now adding the user to DynamoDB and doing some additional stuff so I no longer need to make use of the `add user to group` so I am using `amplify update auth` to remove this. 

After I `amplify push` and signup up and verify a user, I see the error 'Invalid lambda function output : Invalid JSON'

There are no errors reported in CloudWatch and my custom function has completed successfully. Also, the user is actually confirmed in the user pool.

Additionally, but not a high priority is that the PostConformation lambda still has the `GROUP` environment variable set after removing the `add user to group` functionality

**Amplify CLI Version**
3.17

**To Reproduce**

**1.** 
`amplify update auth`
What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AW
S IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? Yes
 Enter the minimum password length for this User Pool: 8
 Select the password character requirements for your userpool: (Press <space> to select, <a> to toggle all, <i>
to invert selection)Requires Lowercase, Requires Uppercase, Requires Numbers, Requires Symbols
 Specify the app's refresh token expiration period (in days): 15
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: (Press <space> to select, <a> to toggle all, <i> to invert selection)Email
 Specify write attributes: (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito (Press <space> to select, <a> to toggle all, <i> to invert se
lection)Post Confirmation
? What functionality do you want to use for Post Confirmation (Press <space> to select, <a> to toggle all, <i> t
o invert selection)Create your own module

**2.** sign up and verify a user

**Expected behavior**

Sign up and conformation process completes successfully

**Desktop (please complete the following information):**

irrelevant I assume but Mac OS Catalina

**Comment by danhumphrey** [comment]
it appears that I have to use the `callback(null)` call to prevent this, although this didn't cause an issue until I removed the add to group functionality.

**Comment by yogeshwar607** [comment]
In case you are using async function  , then callback(null,event) does not work out , have a look at this reference for more details  - https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html

**Comment by ctjlewis** [comment]
@danhumphrey This actually seems to be an active bug, and using the "add user to group" functionality with Amplify Auth (advanced settings) actually causes the Lambda to fail with `"Invalid lambda function output : Invalid JSON"`.
