### ISSUE TITLE
Amplify Init Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by arikog** [aws-amplify/amplify-cli#2739]
**Describe the bug**

**Amplify CLI Version**
3.17.0

**To Reproduce**
Amplify Configure (create IAM User(
Amplify Init

**Expected behavior**
Expected the init process to create the resources (S3 and IAM roles) and initialize successfully

**Screenshots**
<img width="970" alt="Screen Shot 2019-11-14 at 10 16 22 AM" src="https://user-images.githubusercontent.com/16949026/68884967-22303800-06c9-11ea-82eb-5fd66f3c3dad.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.12.0

**Comment by yuth** [comment]
@arikog are you using a proxy. Are you using any self signed certificates in your computer?

**Comment by arikog** [comment]
@yuth thanks for response. yeah i'm using my work laptop and the error persists wether i'm connected to the VPN or not.

I have not added any certificates so I'm assuming I'm using a self signed certificate 

Ideally if there's a way to run "Amplify Init" with ignore/not verify ssl option, I think that would be helpful

Let me know if I can clarify anything else

**Comment by arikog** [comment]
> @arikog are you using a proxy. Are you using any self signed certificates in your computer?

**Comment by arikog** [comment]
> @arikog are you using a proxy. Are you using any self signed certificates in your computer?

**Comment by yuth** [comment]
@arikog did you figure out how to resolve this?

**Comment by arikog** [comment]
@yuth nope! still stuck

**Comment by yuth** [comment]
You might be able to disable certificate check by setting `NODE_TLS_REJECT_UNAUTHORIZED` environment variable but it its not __recommended__ to ignore the SSL errors.

**Comment by arikog** [comment]
@yuth I see. Is there another way? also would I set by doing 

set NODE_TLS_REJECT_UNAUTHORIZED=0?

**Comment by arikog** [comment]
@yuth it didn't help. I got the same error after.

<img width="1133" alt="Screen Shot 2019-11-14 at 5 34 44 PM" src="https://user-images.githubusercontent.com/16949026/68910047-3e51ca80-0705-11ea-9047-71458aee087a.png">

**Comment by shhalumittal** [comment]
I have similar issue and couldn't resolve this.

**Comment by edwardfoyle** [comment]
@arikog Checking in... have you been able to resolve this? Have you tried running any commands using the [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html)?

**Comment by edwardfoyle** [comment]
Also, have you tried with the latest version of the CLI?

**Comment by SwaySway** [comment]
Closing due to lack of response. Please comment below to re-open the issue, should you still run into this.

**Comment by mittasau** [comment]
ran into same issue on Mac OS, any resolution?

**Comment by rodrigoords** [comment]
Same error here, any suggestion ? I´m using behind proxy

**Comment by edwardfoyle** [comment]
You may need to add custom certs to the node process. Node uses a different trust store than the system one. See https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs
