### ISSUE TITLE
Guidance on aliased GraphQL operations in a single request

### ISSUE THREAD

**Issue by devnantes44** [aws-amplify/amplify-cli#2747]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Aliased GraphQL operations  in a single request - Many-To-Many - AppSync

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
AppSync

**Expected behavior**
Most efficient way to add many editors to a post, using only one request.

**Provide additional details e.g. code snippets**
Regarding the example with many-to-many provided here: https://github.com/aws-amplify/docs/pull/900/files#diff-a8516a884b9597a490fdec8e8c96ce9a , I'm looking for guidance on aliased GraphQL operations in a single request.

The documentation gives the following schema:
 ```
type Post @model {
    id: ID!
    title: String!
    editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}
# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
    @model(queries: null)
    @key(name: "byPost", fields: ["postID", "editorID"])
    @key(name: "byEditor", fields: ["editorID", "postID"])
{
    id: ID!
    postID: ID!
    editorID: ID!
    post: Post! @connection(fields: ["postID"])
    editor: User! @connection(fields: ["editorID"])
}
type User @model {
    id: ID!
    username: String!
    posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```
And the following mutations to create users and posts:
```
mutation CreateData {
    p1: createPost(input: { id: "P1", title: "Post 1" }) {
        id
    }
    p2: createPost(input: { id: "P2", title: "Post 2" }) {
        id
    }
    u1: createUser(input: { id: "U1", username: "user1" }) {
        id
    }   
    u2: createUser(input: { id: "U2", username: "user2" }) {
        id
    }
}
```
After users and posts are created, we can create a connection between them creating a PostEditor object:
```
mutation CreateLinks {
    p1u1: createPostEditor(input: { id: "P1U1", postID: "P1", editorID: "U1" }) {
        id
    }   
    p1u2: createPostEditor(input: { id: "P1U2", postID: "P1", editorID: "U2" }) {
        id
    }
    p2u1: createPostEditor(input: { id: "P2U1", postID: "P2", editorID: "U1" }) {
        id
    }
}
```
So far, I was able to create this connection in my app, but with a mutation for every user:
```
const users = [{id: "U1", username: "user1"}, {id: "U2", username: "user2"}];
        const post = { id: "P1", title: "Post 1" };
        /*
        After creating two users and a post using the approriate mutations
        Using the CreatePost join below to make user1 and user2 editor on Post 1
        */
        function graphqlCreatePostEditor(editorID) {
            return new Promise((resolve, reject) => {
              resolve(
                API.graphql(graphqlOperation(createPostEditor, {
                  input: {
                      postID: post.id,
                      editorID
                    }
                }))
              )
            })
          }
  
        let promises = users.map(user=> {
            return graphqlCreatePostEditor(user.id)
            .then(e => {
                console.log(e)
            return e;
            })
        });

        Promise.all(promises)
            .then(results => {
                console.log(results)
            })
            .catch(e => {
                console.error(e);
            })
```
My use case involves to be able to add many editors to a post in one single request. For example, the post creator will be able to select 50 users, then add them as editor of the post newly created. Is there a better way to handle this use case than creating a promise and doing a mutation for every connection (it seems not efficient for 50 users)?

I can provide more code if needed.

**Comment by attilah** [comment]
@devnantes44 I think as it is a custom use case perhaps using a custom mutation with custom resolvers is the best solution, utilizing Batch operations for DynamoDB.

@janhesters has a blog article about batch operations: https://medium.com/@jan.hesters/creating-graphql-batch-operations-for-aws-amplify-with-appsync-and-cognito-ecee6938e8ee
