### ISSUE TITLE
`amplify add auth` not adding anything according to CLI

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#275]
**Describe the bug**
Amplify auth appears to not be added when using a fresh project after running `amplify init`

**To Reproduce**
1. Run `amplify init`
2. Run `amplify add auth`
3. Run `amplify push`
4. See this
```
amplify push
| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |
? Are you sure you want to continue? true
√ All resources are updated in the cloud
```

Potentially related - running `amplify status` returns this:
```
amplify status
| Channel | Status   |
| ------- | -------- |
| APNS    | Disabled |
| FCM     | Disabled |
| Email   | Disabled |
| SMS     | Disabled |
```

I have not seen this before and it seems strange.

**Expected behavior**
There should be auth listed in the status.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

amplify -v
0.1.27

**Comment by kaustavghosh06** [comment]
@mwarger This is a known issue and is tied to our underlying CLI framework - gluegun, and there is a fix provided for the same -> https://github.com/infinitered/gluegun/issues/384, but they haven't gotten a chance to publish a new version to NPM. Once they do so, we'll have this fixed. For the time being, you could use `amplify auth push` to push your auth resources or use WSL as recommended by us for the time being.

**Comment by jamonholmgren** [comment]
@kaustavghosh06 I posted on the other issue too, but could you try beta 12 and see if it fixes this issue on Windows?

**Comment by kaustavghosh06** [comment]
@mwarger We published a new version of the CLI to npm, version -> 0.1.32 with fixes for windows. Feel free to re-open the issue if the problem still persists.
