### ISSUE TITLE
Amplify push - Existing schema attributes cannot be modified or deleted - AWSCognitoIdentityProvider

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-cli#2753]
**Describe the bug**

Amplify push is erroring about attributes being updated / deleted when updating auth confirmation trigger, although no changes have been made and attributes reflects as expected in the stackformation template, even after running amplify env pull  --restore

`Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null)` error is thrown, although no updates to attributes are made to userpool. Cloudformation shows the expected schema as shown in the user pool.

```
      Schema:

        -
          Name: email
          Required: true
          Mutable: true

        - AttributeDataType: "String"
          Mutable: true
          Name: companyName
          StringAttributeConstraints:
              MaxLength: 256
              MinLength: 1

        - AttributeDataType: "String"
          Mutable: true
          Name: userType
          StringAttributeConstraints:
              MaxLength: 256
              MinLength: 1

        - AttributeDataType: "String"
          Mutable: true
          Name: companyIdentifier
          StringAttributeConstraints:
              MaxLength: 256
              MinLength: 1

        - AttributeDataType: "String"
          Mutable: false
          Name: companyId
          StringAttributeConstraints:
              MaxLength: 256
              MinLength: 1
```

![Userpool schema attributes from](https://i.imgur.com/q0eXp24.png)

**Amplify CLI Version**
3.17.0

**To Reproduce**
1. amplify env pull --restore (amplify status shows no changes)
2. update lambda post auth trigger by adding a console log (amplify status shows changes to function only)
3. amplify push (error shows and rollback occurs)

**Expected behavior**
Error should not throw for editing / deleting schema when no change is made to auth / userpool.

Would also be nice to display which attribute / attributes are causing the error.

**Desktop (please complete the following information):**
 - Mac
 - Node Version v10.15.3

**Comment by SteffeyDev** [comment]
@dylan-westbury I am seeing the exact same issue as you did, auth failing to update but even amplify status shows no changes to the auth.  How did you fix?

**Comment by danielblignaut** [comment]
@dylan-westbury I am seeing the same issue. Any idea on how to fix?

**Comment by danielblignaut** [comment]
@SteffeyDev did you ever figure this out? I've seen your other issue raised but cant see any detail on the fix in particular... I managed to sort out once but seems to be coming back again and again.

Seems to only happen to me after I added storage categroy.

**Comment by SteffeyDev** [comment]
I forget exactly, but check out the generated build files in the awscloudformation category and make sure the final stack file that is actually run contains the needed attributes  That may have been the issue. I may have also just rebuild from scratch, I have a nifty script that will rebuild the whole amplify scratch pretty quickly and then you can force-delete the old one.

**Comment by SteffeyDev** [comment]
I ended up not adding the storage category again and using S3 outside amplify to be safe

**Comment by SteffeyDev** [comment]
@danielblignaut Ran into the same issue again tonight and actually found a solution.  When you run amplify add storage, it regenerates your auth cloud formation template yaml file and unsets any modifications, then uploads and runs the changed version.  However, even if you fix it and run again, it does not update in the deployment bucket.

To fix, take your correct auth-cloudformation-template.yml file and upload it to the deployment bucket in S3 (project_name-random_number-deployment) inside the amplify-cfn-templates/auth folder.  You should overwrite the bad template file in there (that is probably missing your attributes) with your good template file, and then run amplify push again and it should work.  At least it did for me :).

Seems like an issue with amplify push, it doesn't upload your new yaml auth template before running the stack in the cloud even though you've changed it back to original.

**Comment by SteffeyDev** [comment]
Let me know if you would like additional details on how to fix, I know that wasn't super detailed

**Comment by dylan-westbury** [comment]
I can't recall the exact resolution, but I believe we were facing an error unrelated to the error message that was showing
