### ISSUE TITLE
Region choice issue while running the command "amplify configure".

### ISSUE THREAD

**Issue by theskiesmore** [aws-amplify/amplify-cli#276]
** Which Category is your question related to? **
Configuration for a new project.

** What AWS Services are you utilizing? **
Cognito, Lambda, RDS, etc

** Provide additional details e.g. code snippets **
The new project will run on ap-northeast-2 region.
But, I can't choose the region because the region was not on the list.
Did I something wrong or is there any reasons?

**Comment by kaustavghosh06** [comment]
@theskiesmore, Currently we support these following regions but we have in our roadmap to add more regions in the future.

```
  'us-east-1': 'US East (N. Virginia)',
  'us-east-2': 'US East (Ohio)',
  'us-west-2': 'US West (Oregon)',
  'eu-west-1': 'EU (Ireland)',
  'eu-central-1': 'EU (Frankfurt)',
  'ap-northeast-1': 'Asia Pacific (Tokyo)',
  'ap-southeast-1': 'Asia Pacific (Singapore)',
  'ap-southeast-2': 'Asia Pacific (Sydney)',
  'ap-south-1': 'Asia Pacific (Mumbai)',
```

**Comment by animalmagnetic** [comment]
Same here for London. Please let us know when we should expect new regions to be available.

**Comment by espozbob** [comment]
> ** Which Category is your question related to? **
> Configuration for a new project.
> 
> ** What AWS Services are you utilizing? **
> Cognito, Lambda, RDS, etc
> 
> ** Provide additional details e.g. code snippets **
> The new project will run on ap-northeast-2 region.
> But, I can't choose the region because the region was not on the list.
> Did I something wrong or is there any reasons?

If you already configured amplify with other regions, just modify a ./aws/configure file with your region.
Then you must choose a profile "default" after "amplify init".

**Comment by hyochan** [comment]
> 'ap-northeast-1': 'Asia Pacific (Tokyo)',

'ap-northeast-2': 'Asia Pacific (Seoul)',

**Comment by MatteoInfi** [comment]
same here `us-west-1`...

**Comment by novusli** [comment]
Can't find ```us-west-1```

**Comment by anaibol** [comment]
Can't find sao paulo region

**Comment by cchalfan1** [comment]
2021 here - @kaustavghosh06 `us-west-1` still unsupported?

**Comment by kaustavghosh06** [comment]
@cchalfan1 Yes, but we're planning on addition support for it soon.

**Comment by Warkanlock** [comment]
``us-north-1`` still unsupported?
