### ISSUE TITLE
auth checks not being removed from resolver templates after rules are deleted from schema

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#2765]
I was attempting to work-around this issue: https://github.com/aws-amplify/amplify-cli/issues/2727

I had a group auth rule and a `private` auth rule, and removed the group for now to just make sure that the `private` rule was working.

**Describe the bug**
The auth rules I had removed for group are not reflected in the resulting resolver templates.

**Amplify CLI Version**
amplify -v
3.17.0
**To Reproduce**
Have an auth rule with a group defined.  Push/build in console/gql-compile to get the resulting resolvers.
Remove the auth rules for the group.
Compile again.
The group auth rules are still there (and still being enforced when they shouldn't be)

**Expected behavior**
The auth rules should work.

**Comment by mwarger** [comment]
@attilah @undefobj @UnleashedMind @yuth Could someone please advise on how to force an update to my backend resolvers?  Since posting this, other changes I've made to auth do not appear to have any effect.  I'm very confused as to why this.  Thank you.

**Comment by undefobj** [comment]
@mwarger there was a fix for this in the linked issue that has been merged. We're trying to do a release with a new version of the CLI that will address this.

**Comment by kaustavghosh06** [comment]
@mwarger The fix for this issue has been merged. Please let us know if you're still seeing this issue.
