### ISSUE TITLE
Subscription updates not triggered through graphql api

### ISSUE THREAD

**Issue by Flos** [aws-amplify/amplify-cli#2768]
**Subscriptions**
I would like to have the live data on my Amplify App. 
But I have an external Lambda (Different project) which needs to update a database table in the Amplify project. What is the recommended way to do that? 

**Amplify CLI Version** 
3.15.0

**What AWS Services are you utilizing?**
Amplify, DynamoDB, Cognito, Lambda

**Provide additional details**
I tried right now:
- open app twice with in different browsers and update in one browser --> DB updated, client notified. (Subscription works in general)
- update the DynamoDB with a dynamo db query, somehow I was just hoping that there is a stream handler which notifies the subscribers ---> DB updated, but client not notified.
- use the graphql API with iam authentication  ---> DB updated, but client not notified.
- use the graphql API with cognito user pool (default auth) #2715  --> DB updated, but client not notified

***Model***
```gql
type Topic @model @auth(rules: [
                                {allow: owner},
                                {allow: public, provider: iam}
                                ]
                        )
{
  id: ID!
  title: String!
}
```

***Update mutation run from ...console.aws.amazon.com/appsync/home...***
```gql
mutation updateTopic{
    updateTopic(input:{id:"8e4880e2-19ab-428f-9c0d-7ef2f5d8d322", title:"test221122"}){
      title
    }
  }

```

***Subscription self implemented to overcome issue #2552***
```ts
export function OnUpdateTopicListener(owner: string): Observable<OnUpdateTopicSubscription> {
  // console.log("OnUpdateTopicListener", owner);
  const statement = `subscription OnUpdateTopic($owner: String!) {
          onUpdateTopic(owner: $owner) {` + query + `
        },
      }`;
  const gqlAPIServiceArguments: any = {
    owner
  };

  return API.graphql(
    graphqlOperation(statement, gqlAPIServiceArguments)
  ) as Observable<OnUpdateTopicSubscription>;
}
```

I can't use the generated amplify client to trigger updates in the other project.
What is the recommended approach in my situation?

**Comment by SwaySway** [comment]
Hello @Flos 
If I'm understanding this correctly your lambda exists in a different project and would like updates on another project (said Amplify App)?
If so the lambda can trigger a mutation which could effectively update your db. This mutation could can be subscribed and you can receive updates for it.

Or is the db separate from db created from `topic @model`

**Comment by kaustavghosh06** [comment]
Closing this due to lack of response. If you're still stuck on this, please feel free to comment on this issue and we'll re-open this.
