### ISSUE TITLE
[@auth] access control using object / field auth

### ISSUE THREAD

**Issue by bob-lee** [aws-amplify/amplify-cli#2778]
**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
My requirement for my object is two fold:
- signed-in user can CRUD all fields
- public apiKey access can read all fields and can update only `state` field and can't create / delete

**Tried this:**
```
type MyObject 
  @model(subscriptions: null)
  @auth(rules: [
    {allow: private}
  ])
{
  id: ID!
  name: String
  state: String
    @auth(rules: [
      {allow: private, operations: [create, read, update, delete]},
      {allow: public, provider: apiKey, operations: [read, update]}
    ])
}
```
**What's happening ok:**
private access can CRUD all fields.
public access can't create / delete, can read all fields and can update `state` field.
**What's happening not ok:**
public access can still update `name` field. How can I disable this?

#2241 maybe related, current document is too confusing for me to fully understand..

**Comment by ammarkarachi** [comment]
@bob-lee I am working on this, will get back to you.

**Comment by ammarkarachi** [comment]
Hi @bob-lee , to restrict access you would need to define the ```allow:private``` rule on all the field to restrict access. We are in the process of making improvements to this work around.

**Comment by bob-lee** [comment]
@ammarkarachi thanks for update. I tried below hoping public access cannot update `state` field but had no success.
```
type MyObject 
  @model(subscriptions: null)
{
  id: ID!
    @auth(rules: [
      {allow: private},
      {allow: public, provider: apiKey, operations: [read, update]}
    ])
  name: String
    @auth(rules: [
      {allow: private},
      {allow: public, provider: apiKey, operations: [read, update]}
    ])
  state: String
    @auth(rules: [
      {allow: private},
      {allow: public, provider: apiKey, operations: [read]}
    ])
}
```

**Comment by ammarkarachi** [comment]
@bob-lee I am sorry for the delay. I would suggest using Cognito for finer grained control over fields. Let me know if that answers your question
