### ISSUE TITLE
Using @auth directive with @key directive

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2781]
**Which Category is your question related to?**
GraphQL transform. 

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
dynamodb, appsync, cognito, s3

**Provide additional details e.g. code snippets**

Here's the use case: 

- new users create account through wizard like pages
- want to capture email in db right away in case new user exits before completing all steps
- allow new user to create customer record via public auth (apiKey) 
- want to check for email existence in case where user exited before finishing process and returns to complete
- BUT don't want to open up customer type for anyone to read. 
- there is a byEmail key which will be used. 

Can I put the public read auth on the key and limit the fields returned to just the email was entered? All I need is to know if it exists or not.

Or do I need to create my own cusom resolver (create customer) where I do the check?

**Comment by yuth** [comment]
GraphQL transformer supports [field level auth](https://aws-amplify.github.io/docs/cli-toolchain/graphql#field-level-authorization). If you rely on subscription on your user type, the behavior changes when you add field level auth. This is documented [here](https://aws-amplify.github.io/docs/cli-toolchain/graphql#field-level-authorization)
