### ISSUE TITLE
AccessDeniedException when calling API with IAM

### ISSUE THREAD

**Issue by vdiaza** [aws-amplify/amplify-cli#2783]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created a API through the amplify CLI, but I am not able to make the connection to my local app.
everytime that I do the call I get a 403 error with "AccessDeniedException" as well as the CORS error. I did enable CORS on the API as well as in the Lambda Function.

I did try many things such as using a mock instead of lambda and I get the same error, The only way I could make it work from my local is by deactivating the IAM Auth. 

It may be something with the policies (something that I dont understand much), But i have still tried many things with those as well.

**Amplify CLI Version**
3.16.0

**Screenshots**
https://ibb.co/19rnhGd
https://ibb.co/jRYhMBq
https://ibb.co/bQgZ9yN
https://ibb.co/5kPxgy2

**Desktop (please complete the following information):**
 - OS: MAC
 - Node Version. v12.13.0

**Additional context**

**Comment by rrrix** [comment]
Is IAM your "default authentication" mechanism (or is Cognito or API Key the default?) 

If IAM is not the primary auth mechanism, you have to add either `@aws_iam` or something like `@auth(rules: [{allow: public, provider: iam}])` to your root Query / types / fields / etc. I've ended up adding it to literally every type I have (along with `@aws_api_key`) so my team and our integrations are all authorized on everything. 

Docs regarding `@auth` and `allow: public` (why IAM is "public" is beyond me): https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#public-authorization

**Comment by vdiaza** [comment]
I forgot to mention that this issue only happens with API gateway. With AppSync works fine. If I make it public works, but when i set IAM as auth it gives me the 403 error.

**Comment by kaustavghosh06** [comment]
@vdiaza Could you tell me the CLI flow you used to setup the API?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of requested information. Please feel free to re-open or comment on this issue if you're still stuck.
