### ISSUE TITLE
amplify generate doesn't generate correct GraphQL operation files except for src directory

### ISSUE THREAD

**Issue by SokichiFujita** [aws-amplify/amplify-cli#2788]
**Describe the bug**

`amplify generate add` asks `Enter the file name pattern of graphql queries, mutations and subscriptions` in the generation wizard. But if the top level directory is not `src`, the file generation fails as `To Reproduce` section. I'm not sure this behavior is expected specification or not.

**Amplify CLI Version**

```
amplify --version
3.17.0
```

**To Reproduce**

```
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions app/graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code app/graphql/API.ts
? Do you want to generate code for your newly created GraphQL API Yes
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ Code generated successfully and saved in file app/graphql/API.ts
```

1. GraphQL operation files are generated in `src/graphql/**/*.ts`
2. The content of `app/graphql/API.ts` is empty.

**Expected behavior**

1. GraphQL operation files are generated in `app/graphql/**/*.ts`
2. The content of `app/graphql/API.ts` is not empty.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: `v12.6.0`

**Comment by aireater** [comment]
There is at least one other issue logged for this problem and it looks like it was reported a long time ago. 

If the team is busy on other features can someone point out in the code where to fix this and one of us can take a crack at it?

**Comment by SwaySway** [comment]
Hello @kldeb are you still running into this issue?

If so could you include `.graphqlconfig.yml` ?

**Comment by kaustavghosh06** [comment]
Closing due to lack of requested information. If you're still stuck on this please feel free to comment on this thread.
