### ISSUE TITLE
Using "amplify api gql-compile" and "amplify codegen" without "amplify init"

### ISSUE THREAD

**Issue by ChrisWun** [aws-amplify/amplify-cli#279]
** Which Category is your question related to? **
Feature Request / Usage

** What AWS Services are you utilizing? **
AWS Appsync

** Provide additional details e.g. code snippets **
The AWS Amplify CLI can be used to define a GraphQL API. It is also possible to generate Resolvers, a CloudFormation Template and Typescript Types for a defined schema in schema.graphql.

I'd like to use these features without an initialized amplify Project. Something like
`amplify api gql-compile --schema <path to schema.graphql> --output <path to output folder for Resolvers and CloudFormation Template>` and `amplify codegen --schema <path to schema.graphql> --output <path to output folder for generated Code>`

Is this possible?

My current workaround is to move the generated files back and forth between a demo project (where amplifiy is initialized) and the target project.

**Comment by UnleashedMind** [comment]
We recommend to use the Amplify CLI only on initialized projects, even if hacks like this might work in certain, it's not guaranteed to work for feature updates.
