### ISSUE TITLE
Manage Cognito user pool from within lambda function

### ISSUE THREAD

**Issue by aprat84** [aws-amplify/amplify-cli#2790]
**Which Category is your question related to?**
Functions

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
api + auth + function

**Provide additional details e.g. code snippets**

So I started a project with GraphQL API + Cognito user pools auth.

In my schema.graphql I created a `Employee` entity like so:

```graphql
type Employee
@model(
    queries: {get: "getEmployee"},
    mutations: {},
    subscriptions: {}
)
@auth(
    rules: [{
        allow: groups,
        groups: ["admin"],
        operations: [read, create, update, delete]
    }, {
        allow: owner,
        ownerField: "email",
        identityClaim: "username",
        operations: [read]
    }]
) {
    id: ID!
    email: String!
    name: String!
    code: String!
    isEnabled: Boolean
}
```

For testing purposes I only created a simple `getEmployee` query.

Then I created a function using `amplify add function` and granted it full permissions to `auth` resource (my user pool).
I associated a graphql mutation field to this function:
```graphql
input CreateEmployeeInput {
    email: String!
    name: String!
    code: String!
    isEnabled: Boolean!
}

type Mutation {
    createEmployee(input: CreateEmployeeInput!): Employee 
        @function(name: "create-employee-${env}")
}
```

So far so good.

Now, inside my lambda function I'm trying to achieve 2 steps:
1- Create a new user in my cognito user pool
2- Create an employee in the Employee dynamodb table

So, to instantiate a new `CognitoIdentityServiceProvider`, I need an `accessKeyId` and an `secretAccessKey`.

```js
const cognitoServiceProvider = new AWS.CognitoIdentityServiceProvider({
    region: process.env.REGION,
    credentials: {
        accessKeyId: 'XYZ',
        secretAccessKey: 'abcdef'
    }
});
const result = await cognito.adminCreateUser({
    UserPoolId: process.env.AUTH_XXXXXX_USERPOOLID,
    MessageAction: 'SUPPRESS',
    Username: 'some@email.com',
    TemporaryPassword: 'random_string'
}).promise();
```

Note: only admins can create users. Users can't sign up themselves.

First question: why I need to pass in the credentials if my function, by it's role created by amplify, already should have full access to my user pool?

Second question: In case it's impossible to avoid passing credentials to instantiate `CognitoIdentityServiceProvider`, how can I pass them to the lambda?
- Hardcoding them into the JS code or cloudformation JSON is not an option (gross)
- Manually edit function environment variables from the AWS console is not an option either (too verbose)
- Can't save them to SecretsManager, cause I would need another pair of credentials to query for them
- Amplify doesn't give a solution to create and automatically pass custom environment variables to it's functions

**EDIT**

If I deploy to the cloud with `amplify push`, then it works, in the cloud. But I can't mock in local, cause I get the following error within the function:
```js
ConfigError: Missing region in config
```

**Comment by undefobj** [comment]
Lambda has it's own execution role, and you shouldn't be using secret keys when instantiating this object. You should be able to do something like:

```javascript
const { CognitoIdentityServiceProvider } = require('aws-sdk');
const cognitoIdentityServiceProvider = new CognitoIdentityServiceProvider();
```

The Lambda role will then be used. I recommend you take a look at the [Admin Actions](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions) feature of the CLI which does all this out of the box including scoping the Lambda role to just have permissions on your User Pool.

**Comment by aprat84** [comment]
Thanks for your fast reply!

I edited the first message. The fact is that, as you said, once deployed to the cloud everything works. Lambda function executes using its role, so it can access every resource I gave access via the amplify cli. So, yes, with your code I can connect and manage everything in my Cognito user pool.

My problem is when mocking (working in my local machine). Then I receive this error: `ConfigError: Missing region in config`.
I can't write code and then wait for `amplify push` to test it. The `push` action takes 30s to 1min to complete, even the lightest change...

I had a look at the Admin actions feature, but if I understood it correctly, this is something for the frontend. I have no frontend attached to this project. Also, there's no `createUser` action.

So, at the end, I just want to develop fast in my local machine, mocking/simulating every resource I added to amplify project, and then push to the cloud. Is it not possible?

**Comment by undefobj** [comment]
Cognito User Pools isn't available with local mocking, only simulating a JWT token is possible at this time.

**Comment by SourceCode** [comment]
I'm confronted with this issue as well but something I am realizing is the amazon side is heavily tested, so mocking their services expected responses when my request is validated for type/data that it should suffice. (Although less than ideal...)
