### ISSUE TITLE
Add tags to all Amplify resources

### ISSUE THREAD

**Issue by Morras** [aws-amplify/amplify-cli#2794]
**Is your feature request related to a problem? Please describe.**
It can be difficult to get an overview of all resources provisioned by Amplify. This would be greatly helped if all the resources had a common tag.

**Describe the solution you'd like**
All resources tagged with an "amplify-project" tag.
Ability to add other custom tags.

**Comment by Morras** [comment]
Yes, sorry for my very late reply.

What I am trying to do is to get a quick view of all resources provisioned by Amplify for a given project. I know that I can look through all the stack instances and see what was deployed, but it would be even better if I can find them via resource groups.

Another use case would be for companies who might be required to tag resources with certain compliance tags like environment or cost centre.

**Comment by simontegg** [comment]
It would also be useful to tag resources with their `env`. That way any custom IAM polices can reference these resources based on tags, rather than resource names or arns (which may get recreated)

**Comment by abwaters** [comment]
This is important for AWS Amplify to be managed by enterprise projects where teams share AWS accounts. bump

**Comment by heschlie** [comment]
We're running into this as well to run into a better understanding of where AWS costs are going, is this on the roadmap anywhere?

**Comment by ChristopheBougere** [comment]
Same need here, my use case is to configure a backup plan on AWS Backup service.
A default tag like this would be great: `${projectName}-${env}-${category}` (so I can easily define different backup rules for storage and API).

**Comment by renebrandel** [comment]
Hi folks. I'm closing this issue as we've launched resource tagging support. See #365
