### ISSUE TITLE
@aws-ampliyf/cli: Revoking permissions granted to Lambda function causes update failures

### ISSUE THREAD

**Issue by matt-e-king** [aws-amplify/amplify-cli#2795]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When using the CLI, if you grant permissions to a Lambda function, one of the changes codegen makes is appending an object to the `NAME_OF_FUNCTION.dependsOn` array in the `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` files.

But if you use the CLI (`amplify function update`) to revoke permissions granted to a Lambda function it doesn't remove those `dependsOn` entries within the `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` files. 

The CLI does remove references to the permissions in the Lambda's cloud formation template, the `function-parameters.json` file, and remove the `env` variables from the handler index.js file. But NOT the  `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` files. So now if you then attempt to run `amplify push` it will result in an error that looks something like this:
```
<NAME_OF_FUNCTION> AWS::CloudFormation::Stack Wed Nov 20 2019 09:41:09 GMT-0700 (Mountain Standard Time) Parameters: [ <LIST_OF_PARAMETERS> ] do not exist in the template
```
The `<LIST_OF_PARAMETERS>` are the concatenated property values under the `NAME_OF_FUNCTION.dependsOn` that STILL exist in the `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` files that were never removed by the CLI.

The worked around is to manually remove those unwanted `dependsOn` entries. What made this difficult to track down is that `amplify-meta.json` is not tracked in git so you can't even monitor what changes are happening in that file.

**Amplify CLI Version**
3.17.0

**To Reproduce**
- Create a new amplify project and environment
- Add auth, api and a single function, which we will call `functionOne` for this example
- `amplify push` - do this just to create a clean slate
- `amplify function add`, and then let's call this function `functionTwo`
- When the CLI asks you `Do you want to access other resources created in this project from your Lambda function?` let's add `read` permissions to both the `api` and the function `functionOne`
- Locate `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json`, inside those file you should see something like:
```
"functionTwo": {
		"service": "Lambda",
		"providerPlugin": "awscloudformation",
		"build": true,
		"dependsOn": [
				{
					"category": "function",
					"resourceName": "functionOne",
					"attributes": [
							"Name"
					]
				},
				{
					"category": "api",
					"resourceName": "apiExample",
					"attributes": [
						"GraphQLAPIIdOutput",
						"GraphQLAPIEndpointOutput"
					]
				}
		]
}
```

- Now run `amplify function update`, select `functionTwo` and remove ALL permissions granted in the previous step
- Locate `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` - the `dependsOn` entries for `functionTwo` have NOT been removed
- This will cause an UPDATE_FAILED on the next `amplify push`

**Expected behavior**
For the CLI to remove any related `dependsOn` entries in `amplify/backend/backend-config.json` and `amplify/backend/amplify-meta.json` when revoking permissions granted via the `amplify function update` steps.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - node v12.10.0

**Comment by houmark** [comment]
I've hit a similar bug, but I was trying to add access to storage from a function.

I was able to `amplify push` in the CLI but I was not able to deploy using the Amplify Console (I even tried updating my Schema to see if that would make the Console pick up changes. didn't help).

It would fail with this error message:

```
2020-03-01T10:37:13.656Z [INFO]: UPDATE_FAILED               functionwhatever         AWS::CloudFormation::Stack Sun Mar 01 2020 10:37:09 GMT+0000 (Coordinated Universal Time) Output 'storagemystorageBucketName' not found in stack 'arn:aws:cloudformation:us-east-1:83-redacted:stack/project-dev-20190616124718-mystorage-1RFZGQK5KY8IR/7a30a2a0-2894-11ea-8fbe-0a254e00bc9f'
                                 UPDATE_ROLLBACK_IN_PROGRESS project-dev-redacted AWS::CloudFormation::Stack Sun Mar 01 2020 10:37:10 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [functionwhatever].
```

I tried messing around in various JSON templates, but I was unable to figure out what was happening and the "solution" was to `amplify function update` and remove access to storage, and then just find another way to access S3 in this function. This was a one time job that was running against a CSV file so I ended up putting the CSV in a public bucket, so my Lambda function did not need the access.

Something is definitely broken here. It's ~3 months after this bug report and it seems nobody from AWS has done any debugging? @kaustavghosh06?

**Comment by houmark** [comment]
And for the record, I'm running Amplify CLI 4.13.4, which is the current most recent version.

**Comment by abouroubi** [comment]
Have the same bug with the lastest version of the cli 4.18.1

**Comment by edwardfoyle** [comment]
This fix is available in the latest version of the CLI. Please install the latest version to get the changes.
