### ISSUE TITLE
Unique many-to-many relations

### ISSUE THREAD

**Issue by kozlovvski** [aws-amplify/amplify-cli#2808]
Hey!
In [Amplify docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql) I found how to implement many-to-many connection:

```graphql
type Post @model {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
  @model(queries: null)
  @key(name: "byPost", fields: ["postID", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "postID"]) {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```

This works fine, but I miss one thing: how can I make sure that my connections are unique? For example, I can add a `PostEditor` with same `postID` and `editorID` twice.

Also, if possible, I would like to ensure that on backend. My current solution is to create `id` based on `postID` and `editorID` but that happens on frontend and therefore is insecure.

Thanks!

**Comment by undefobj** [comment]
If you leave out the `id` from the input args then a UUID will be created automatically in the backend. Using an identifier isn't insecure from the client, but yes a better solution is to have the backend create these to ensure uniqueness. The docs show short identifiers for conceptual reasons in the tutorial to avoid copy/paste.

**Comment by ammarkarachi** [comment]
Closing issue
