### ISSUE TITLE
Generated graphql query for @key ignores depth setting

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#2810]
**Describe the bug**
I accepted the default 2 level depth of generation for queries, mutations and subscriptions. This depth is not being respected by a query generated from a key defined in the schema. 

I'm also using mock to develop locally so this means every time I run mock I get an error that the node I need is missing. 

Also, because the generated code can't be moved to another directory I'm going to have to create a workaround with different files. 

Granted, this adds small steps to my development. But it also slows me down in the beginning stages of a project where I'm trying to iterate quickly and the schema isn't settled yet.

**Amplify CLI Version**
3.17.0

**To Reproduce**
1. create a type with a connection to another type
2.  create a key for the parent type
3. run codegen statements or mock
4. see that the connected type is not included in the output

**Expected behavior**
Include child node in query items 

**Desktop (please complete the following information):**
 - OS: macOS
 - Node: v12.10.0

**Comment by attilah** [comment]
@aireater please update to the latest version of the CLI and share the schema you're trying to use as well as tell us what language/framework you're running codegen against.

**Comment by aireater** [comment]
I'm generating javascript code. 

here's the relevant parts of the schema:

```gql
type Customer
  @model
  @key(
    name: "customersByEmail"
    fields: ["email"]
    queryField: "customersByEmail"
  ) 
{
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  utility: Utility! @connection
  owner: String
}

type Utility
  @model
{
  id: ID!
  name: String!
  owner: String!
}

```

and here's the code generated:

```js

export const customersByEmail = `query CustomersByEmail(
  $email: String
  $sortDirection: ModelSortDirection
  $filter: ModelCustomerFilterInput
  $limit: Int
  $nextToken: String
) {
  customersByEmail(
    email: $email
    sortDirection: $sortDirection
    filter: $filter
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      firstName
      lastName
      email
      owner
    }
    nextToken
  }
}
`;
```

**Comment by attilah** [comment]
@kldeb this is working as expected. I talked with @yuth and the reason why you can't see the ```utility```  field is that the ```items``` in list operations also counts as a level. If you change the ```maxDepth``` to 3, then first level of nesting will be visible in list operations as well.
