### ISSUE TITLE
amplify push fails after adding auth with manual configuration

### ISSUE THREAD

**Issue by peejayess** [aws-amplify/amplify-cli#2820]
**Describe the bug**
I attempted to add auth to my existing amplify project and it fails to push it when I use a manual configuration.  If I use the default configuration it pushed ok.

**Amplify CLI Version**
3.17

**To Reproduce**
I added the auth and then tried to push it
> amplify add auth
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up & Sign-In only (Best used with a cloud API only)
 Please provide a friendly name for your resource that will be used to label this category in the project: <a custom resource name>
 Please provide a name for your user pool: <a customer userpool name>
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Email
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OPTIONAL (Individual users can use MFA)
 For user login, select the MFA types: (Press <space> to select, <a> to toggle all, <i> to invert selection)SMS Text Message
 Please specify an SMS authentication message: <Appname> - Verification Code {####}
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: <Appname> - Account Verification Code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email, Name
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
Successfully added resource aequipstagingauth locally

>amplify push

**Expected behavior**
It pushes it successfully

**Screenshots**
The errors I got prior to rollback starting was:

| Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout      Sun Nov 24 2019 13:35:55 GMT+0000 (Greenwich Mean Time) Output 'IdentityPoolId' not found in stack 'arn:aws:cloudformation:eu-west-2:305655101386:stack/amplify-<appname>-staging-181051-auth<appname>stagingauth-14ZEDJKONEON8/1cece110-0ebf-11ea-b181-02ea235e602c'

The error I got after the rollback had completed was:

Following resources failed

Resource Name: UpdateRolesWithIDPFunctionOutputs (Custom::LambdaCallout)
Event Type: create
Reason: Output 'IdentityPoolId' not found in stack 'arn:aws:cloudformation:eu-west-2:305655101386:stack/amplify-<appname>-staging-181051-auth<appname>stagingauth-14ZEDJKONEON8/1cece110-0ebf-11ea-b181-02ea235e602c'

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

**Desktop (please complete the following information):**
 - OS: windows and Powershell
 - Node Version. 10.16.3

**Additional context**

**Comment by selipso** [comment]
I'm getting the same error in the latest version. Before getting the `Resource is not in the state stackUpdateComplete` error, I've also received this error message during the push:

```
UPDATE_IN_PROGRESS          apikapisce                 AWS::CloudFormation::Stack Sun Nov 24 2019 18:51:39 GMT-0800 (Pacific Standard Time)                                                                                                                            
UPDATE_FAILED               apikapisce                 AWS::CloudFormation::Stack Sun Nov 24 2019 18:51:40 GMT-0800 (Pacific Standard Time) Parameters: [unauthRoleName, authRoleName] must have values                                                                
CREATE_IN_PROGRESS          authuserPoolGroups         AWS::CloudFormation::Stack Sun Nov 24 2019 18:51:40 GMT-0800 (Pacific Standard Time)                                                                                                                            
CREATE_FAILED               authuserPoolGroups         AWS::CloudFormation::Stack Sun Nov 24 2019 18:51:41 GMT-0800 (Pacific Standard Time) Resource creation cancelled  
```

I added Auth as part of adding API with both Cognito and IAM authentication for public and private objects.

**Comment by BardiaN** [comment]
Recent changes on both CLI & App sides are super super buggy, I wasted like 2 days of my time and still no success! :/
I really missed the days that Amplify wasn't supporting some resources/options and I used to do it manually in parameters or CloudFormation stacks.
I'm simply trying to deploy the same Cognito user pool that was in the project for the last few weeks and was working fine, but It gets stuck in creates/update the stack because of two resources that stay in "UPDATE_IN_PROGRESS" or "DELETE_IN_PROGRESS" forever!!!
MFALambdaInputs: type of Custom::LambdaCallout
UserPoolClientInputs: type of Custom::LambdaCallout

I already have 2 stacks with "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS" status and apparently I have to contact support to deal with them and since Technical Support is not included in the basic plan, I have to upgrade :/

**Comment by kaustavghosh06** [comment]
This seems related to #2096 
Please use the workaround mentioned out here - https://github.com/aws-amplify/amplify-cli/issues/2096#issuecomment-523746110
