### ISSUE TITLE
nextToken is returning empty result even though there are still data.

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#2822]
**Describe the bug**

nextToken is returning empty result even though there are still data.

**Amplify CLI Version**
3.17.0

**To Reproduce**

Model:

```graphql
type TestModel @model @searchable {
  id: ID!
  someFloat: Float
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

generated graphql queries

```js
export const listTestModels = `query ListTestModels(
  $filter: ModelTestModelFilterInput
  $limit: Int
  $nextToken: String
) {
  listTestModels(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      someFloat
      createdAt
      updatedAt
    }
    nextToken
  }
}
`;
export const searchTestModels = `query SearchTestModels(
  $filter: SearchableTestModelFilterInput
  $sort: SearchableTestModelSortInput
  $limit: Int
  $nextToken: String
) {
  searchTestModels(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      someFloat
      createdAt
      updatedAt
    }
    nextToken
    total
  }
}
`;
```

On AppSync console > Queries try out:

```graphql
query (
  $nextToken: String
  $limit: Int
  $sort: SearchableTestModelSortInput
) {
  searchTestModels (
    limit: $limit
    sort: $sort
    nextToken: $nextToken
  ) {
    items {
      id
      someFloat
    }
    nextToken
    total
  }
}
```

on your first fetch, set the following variables:

```json
{
  "limit": 2,
  "sort": {
    "field": "someFloat",
    "direction": "desc"
  },
  "nextToken": null
}
```

Here's a sample result:

```js
{
  "data": {
    "searchTestModels": {
      "items": [
        {
          "id": "e51de79c-dbb9-4bd1-8ca1-dafc4a8ed986",
          "someFloat": 1574647081660
        },
        {
          "id": "5522c548-0e86-45e2-abb1-c45408fe91ca",
          "someFloat": 1574647086187
        }
      ],
      "nextToken": "1.5746471E12",
      "total": 10
    }
  }
}
```

On the next fetch, you can use the `nextToken` you received.

Here in the example, I tried using the `nextToken` **RAW**, i.e., I did not do anything about it like this:

```json
{
  "limit": 2,
  "sort": {
    "field": "someFloat",
    "direction": "desc"
  },
  "nextToken": "1.5746471E12"
}
```

And also tried to parse (JS: `parseFloat`) it like this:

```json
{
  "limit": 2,
  "sort": {
    "field": "someFloat",
    "direction": "desc"
  },
  "nextToken": "1574647100000"
}
```

The result will always be empty:

```json
{
  "data": {
    "searchTestModels": {
      "items": [],
      "nextToken": null,
      "total": 10
    }
  }
}
```

**Expected behavior**

Should not return empty result.

**Screenshots**
N/A

**Some context**

I encountered this bug because of this --> https://github.com/aws-amplify/amplify-cli/issues/2775

My work around was to use `Float` (because `BigInt` is not available) instead of `AWSDate` and then I'll just store `timestamp` as returned by JS: `new Date().getTime()` to make LTE and GTE work.

**Comment by ammarkarachi** [comment]
@aprilmintacpineda Thanks for submitting this issue. We apologize for the delay. We will be looking into this and getting back to you

**Comment by SwaySway** [comment]
Hello @aprilmintacpineda I tried replicating this issue it seems that it returns a blank as it seems the values between the two floats are roughly close to each other. This seems to be related with how elasticsearch handles floats.

- [ES Issue noted before where floating points have been known to loose precision](https://discuss.elastic.co/t/getting-max-value-of-a-long-field-without-losing-precision/92574)

I'll review this with the team for potential enhancements we can add on our end related to this issue.

**Comment by renebrandel** [comment]
Hi folks - we're planning on addressing this as part of our new GraphQL transformer. The approach is captured here in our RFC: https://github.com/aws-amplify/amplify-cli/issues/7546 love to hear your feedback!

**Comment by renebrandel** [comment]
Hi this should be addressed now. https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#paginate-over-search-results
