### ISSUE TITLE
Hosting with different CloudFront options in multi-environment

### ISSUE THREAD

**Issue by kqumsieh** [aws-amplify/amplify-cli#2829]
** Which Category is your question related to? **
Hosting
** What AWS Services are you utilizing? **
CloudFront, S3

Here is my scenario: in my PROD environment I want CloudFront enabled.  So I do that, CloudFormation is updated and checked into repo.   Next feature, developer creates a branch off of master branch (where CloudFront is enabled), add their feature, and promote the changes.  Now CloudFront cloudfromation is promoted throughout the different environment adding CloudFormation to all the environments.

This is my first time using Amplify in a Production application.  Thank you in advance for your assistance.

**Comment by kaustavghosh06** [comment]
@kqumsieh Is the request out here to not have Cloudfront enabled in different environments?

**Comment by josefaidt** [comment]
Closing due to age and inactivity. @kqumsieh if this is something you would still like to see please reply back to this thread and we can re-open to investigate further
