### ISSUE TITLE
@auth groups clarification 

### ISSUE THREAD

**Issue by austinamorusocfc** [aws-amplify/amplify-cli#283]
** Which Category is your question related to? **
Aws Amplify graphql transform / aws appsynce

** What AWS Services are you utilizing? **
Aws appsync

** Provide additional details e.g. code snippets **
Would it be problematic to just put a read and write group for auth on every object that needs access control? 

```

# Individual accessing data
type User @model 
@auth(
    rules: [
      {allow: groups, groupsField: "readGroups", queries: [get, list]},
      {allow: groups, groupsField: "writeGroups" mutations: [create, update, delete]}
    ]) 
{ 
    id: ID!
    # Name of user
    name: String!
    # Email of user for login and contact
    email: String!
    # Date user was created
    createDate: AWSTimestamp!
    # Last time user logged in
    lastLogin: AWSTimestamp
    readGroups: [String]
    writeGroups: [String] 
}

```

**Comment by mikeparisstuff** [comment]
I don't see a problem with it however I think in your case you will want to pass explicit nulls to "mutation" and "query" to make this work as expected. E.G.

```
@auth(
    rules: [
      {allow: groups, groupsField: "readGroups", queries: [get, list], mutations: null},
      {allow: groups, groupsField: "writeGroups" mutations: [create, update, delete], queries: null}
    ])
```

**Comment by kaustavghosh06** [comment]
Closing this issue. Please, feel free to re-open this issue if the problem still persists.
