### ISSUE TITLE
Configure Amplify function to be able to access DynamoDb 

### ISSUE THREAD

**Issue by Tigerspike-Mike** [aws-amplify/amplify-cli#2830]
**Is your feature request related to a problem? Please describe.**
It's painful to have to manually add the AWS managed DynamoDb roles to the generated policies for functions created by Amplify. 

**Describe the solution you'd like**
When setting up the function via the CLI I would like the option to add the dynamoDb access roles required to allow the deployed Lambda to have permissions to interact directly with DyanamoDb

**Describe alternatives you've considered**
The only option available is to manually add the policies to the generated role.

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by kaustavghosh06** [comment]
@Tigerspike-Mike Did you add the DyanmoDB table via the Amplify CLI?

**Comment by alikadir** [comment]
>   @Tigerspike-Mike Did you add the DyanmoDB table via the Amplify CLI?
@kaustavghosh06 no

**Comment by josefaidt** [comment]
Hey @alikadir :wave: while the Amplify CLI enables you to grant your Lambda access to the underlying DynamoDB tables of your Amplify-managed AppSync API, the CLI will not allow you to grant access to tables managed outside the Amplify project. Instead it would be recommended to use the functions' [`custom-policies.json` file](https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function) to grant access to resources managed outside the project.

Closing issue as a `wontfix`
