### ISSUE TITLE
How can I use hosted UI with cognito user pool?

### ISSUE THREAD

**Issue by groundswel** [aws-amplify/amplify-cli#2832]
** Which Category is your question related to? **
Auth,
** What AWS Services are you utilizing? **
 Cognito
** Provide additional details e.g. code snippets **
With amplify-cli how can I use the hosted UI? i.e. I am using amplify add auth to add authentication and create the cognito user pool. When I create the cognito user pool standalone I can use the hosted UI in my javascript app. How can I do the same with amplify?

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html
 
Please note I am not looking for integrating Cognito with any third party IDP like Facebook or google.

**Comment by kaustavghosh06** [comment]
@groundswel You can use the CLI you can `amplify add auth` and then choose the ` Default configuration with Social Provider (Federation) ` for Hosted UI with Cognito user pools.

**Comment by groundswel** [comment]
> @groundswel You can use the CLI you can `amplify add auth` and then choose the `Default configuration with Social Provider (Federation)` for Hosted UI with Cognito user pools.

What worked for me was using the HOC in my react app.
