### ISSUE TITLE
How to set lambda region different from graphql api region?

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#2834]
**Which Category is your question related to?**
Rest API, Lambda Function

**What AWS Services are you utilizing?**
Cognito, AWS AppSync, AWS Amplify, Lambda etc.

**Provide additional details e.g. code snippets**
I would like to send SMS to list of people via SNS. Mumbai Region doesn't support SMS via SNS. & nearest region that supports SMS is Singapore.

Also I would like to send emails via SES. And Singapore doesn't support SES but Mumbai does support SES. 

**I would rather have graphql in Mumbai because its close to my customers & only sms via Singapore. How do I do that with lambda functions?**

**Comment by attilah** [comment]
Currently this is not supported, the resources must be in the same region.

**Comment by kaustavghosh06** [comment]
@apoorvmote Do you have these lambda functions calling SNS and SES in an already deployed lambda function?

**Comment by apoorvmote** [comment]
@kaustavghosh06 I currently don't them deployed but I can deploy them. Its better this way because my preferred Lambda Language is Golang but Amplify forces me to use express.

**Comment by kaustavghosh06** [comment]
@apoorvmote Okay, in that case you can deploy the lambda functions yourself in your preferred region and then reference them in the annotated graphql schema like this:
```
@function(name: "<function-name>", region: "<your-region>")
```

**Comment by apoorvmote** [comment]
@kaustavghosh06 You are talking about custom lambda resolvers for CRUD operations on graphql backed by database. See following example taken from Amplify Docs
```
type Query {
  echo(msg: String): String @function(name: "echofunction", region: "us-east-1")
}
```
I am looking for different workflow. Imagine customer fills their payment information and hits "Buy Now" button. I will create rest API backed with lambda function. The lambda will make request to payment gateway if that purchase is successful then customer will receive email and SMS notification about their purchase. Email and SMS is done with SES and SNS. 

When I create rest API I get following options
```
apoorvmote@Apoorvs-Air multi-region % amplify add api
? Please select from one of the below mentioned services REST
? Provide a friendly name for your resource to be used as a label for this category in the project: apic9f09979
? Provide a path (e.g., /items) /items
? Choose a Lambda source 
❯ Create a new Lambda function 
```
There is absolutely no option to use existing Lambda function. Amplify forces you to create new function every time.

**Comment by kaustavghosh06** [comment]
@apoorvmote Yes, currently there is no way to re-use existing lambda function code which is deployed outside the Amplify project (and in another region) since that would hinder with your  Infrastructure as code setup and also you wouldn't be able to extend your infrastructure to multiple environments.

**Comment by kaustavghosh06** [comment]
@apoorvmote Please let us know if you have more questions around this. Closing this issue.
