### ISSUE TITLE
Can't create environment name of 2 characters

### ISSUE THREAD

**Issue by moransk8** [aws-amplify/amplify-cli#2837]
**Describe the bug**
When using the version 4.0.0 I can't create an environment name with only two characters.

Running amplify init and then choose the environment name "ci".

This is the error when I tried to create an environment named "ci":
Failed to create backend environment.The environment name ci is invalid. Environment name should be between 2 and 10 characters (only lowercase alphabets)

- Version [4.0.0]

**Comment by rowanu** [comment]
It looks like [this is already fixed](https://github.com/aws-amplify/amplify-cli/blob/8b225c1f9f16fed303adaaa91831bac7752d579d/packages/amplify-cli/src/lib/init-steps/s0-analyzeProject.js#L81) in `master`.

**Comment by ammarkarachi** [comment]
Hey @moransk8, I am closing this issue since 4.2.0 has already addressed it. Thanks!
