### ISSUE TITLE
Error while during 'amplify init' where inaccessible host: Unknown endpoint This service is not avaliable in the us-east region 

### ISSUE THREAD

**Issue by awesome2live** [aws-amplify/amplify-cli#2840]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by awesome2live** [comment]
![issue](https://user-images.githubusercontent.com/13610815/69611613-2dce1800-1054-11ea-92f3-bf104e3b4e43.PNG)

**Comment by ammarkarachi** [comment]
@awesome2live can you update us with the Amplify-cli version you are using?

**Comment by awesome2live** [comment]
i got it was proxy problem we have set up https://github.com/aws-amplify/amplify-cli/issues/459 this following was the solution
