### ISSUE TITLE
How to use the npm package in lamda function when using amplify?

### ISSUE THREAD

**Issue by higherstar** [aws-amplify/amplify-cli#2848]
**Lamda **
Hello?
I want to implement to payment using strip with lamda function.
But then I met some issues to use the npm package `strip`.
I tried to upload lamda function to the aws using amplify push after install this package using `npm install strip`.
But I could not find this package in lamda funciton and met errors.
Could you help me?
How can I implement it using amplify?

**Comment by kaustavghosh06** [comment]
Closing this due to lack of customer response.
