### ISSUE TITLE
Failed To Pull Backend

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-cli#2855]
Hi, so I've been pushing many changes to my Github today that only affect my front end, and about an hour ago I got home, fixed some router issues and pushed my project. Now when the build process on Amplify runs I get the following error:

`2019-11-27T06:55:10.237Z [INFO]: Failed to pull the backend.
2019-11-27T06:55:10.239Z [INFO]: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
                                 at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:19:32)
                                 at Generator.next (<anonymous>)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:5:58)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)` 

I'm not quite sure whats causing the issue. My first idea was to undo what I did and all I did was change <Router> to <BrowserRouter> and then back to <Router> and it didn't solve anything. Then I updated Amplify CLI from something like 3.17 to 4.0.0 and pushed my changes everything. And still the same error. At one point I actually passed the build went on to deployment and it just printed (And sorry I don't have the original log)
-Starting Build
-Build Failed
-Exit
No errors, nothing. Just 3 lines.

I've added some screenshots below, if anyone has the time it would be very much appreciated if I could receive some help! 

![Screenshot from 2019-11-26 23-02-20](https://user-images.githubusercontent.com/10494843/69701036-d5713780-10a0-11ea-8e23-a73d6ef7b6cf.png)
![Screenshot from 2019-11-26 23-03-34](https://user-images.githubusercontent.com/10494843/69701112-00f42200-10a1-11ea-906e-7e9a6d736cff.png)

**Comment by MBach** [comment]
Same here :boom: ! This is insane, I am with a customer in the end of a sprint in order to go live and we cannot work...
Please provide a way to rollback to previous release, or to provide some documentation to fix amplify/cli.

**Comment by MBach** [comment]
OK so @Rafcin 
Go to AWS Amplify Console, then, All Apps > [Your App name] > Build image settings > Edit button > change from latest to 3.17.0:

![image](https://user-images.githubusercontent.com/1532657/69713128-44cc4300-1104-11ea-9f99-4be604f04bf0.png)

**Comment by Rafcin** [comment]
I was on CLI 3.17 when I had the issue and then upgraded to 4.0.0 and had the same issue. Did this work for you?

**Comment by Rafcin** [comment]
Oh actually I see what you mean. Sorry its 4am and i'm still awake

**Comment by aireater** [comment]
This is horrible. I just got off a call where I had to assure someone that Amplify was the right tool for this project because of other issues we're encountering. I get back to my desk and think I'll show him how much I get done....

I personally think the Amplify team is moving too fast with new features and the console team is not in sync.

**Comment by Rafcin** [comment]
Agreed. We can always try to riot 🤣

**Comment by Rafcin** [comment]
Ah but as funny as this is for a few moments, I really hope a fix comes. I don't exactly want to deal with going down a version and messing anything up.

**Comment by aireater** [comment]
I'm sure it will get fixed soon. I assume there's a push to get a lot done for reinvent next week.

**Comment by ammarkarachi** [comment]
@aireater @Rafcin @MBach, This is know issue we have rolled out a fix in 4.2.0. Please update and try again

**Comment by Rafcin** [comment]
I can confirm this works on the 4.2 version. Uninstall Amplify as it seems
to take issue with running the update command and then rebuild.

**Comment by ammarkarachi** [comment]
@Rafcin Thanks!, I will be closing this for now, don't hesitate to reopen or submit another issue if you run into other problems
