### ISSUE TITLE
@searchable item with stringset value can't be indexed to Elasticsearch

### ISSUE THREAD

**Issue by rarira** [aws-amplify/amplify-cli#2860]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When type with @searchable notation, all item refreshed should be indexed to elasticsearch using lambda which is deployed with amplify cli, but if the item has a value with stringset(maybe, number set also), indexing can't be done with this error (cloudwatch log).

```
f179a897-b185-42c4-98ea-07a1b7ba67b2	Traceback (most recent call last):
  File "/var/task/python_streaming_function.py", line 225, in lambda_handler
    return _lambda_handler(event, context)
  File "/var/task/python_streaming_function.py", line 195, in _lambda_handler
    doc_json = json.dumps(doc_fields)
  File "/var/lang/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/lang/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
```

**Amplify CLI Version**

4.1.1 ... all version below was the same

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
```gql
type Class
  @model
  @searchable {
  id: ID!
  title: String!
  blockedBy: [String]
}

```
fails to be indexed because of 'blockedBy' which is stringset.

**Expected behavior**
it would be best if it could be indexed with stringset value, 
but I just expect that if there is stringset, indexing should be done without that.

I could possibly achieve that  in this case  by inserting these lines to DdbToEsFn python lambda code after line 185:
```
  # Delete StringSet
        if "blockedBy" in ddb[image_name]:
            del ddb[image_name]["blockedBy"]

```

but I think it's just temporary.

**Comment by SwaySway** [comment]
@rarira I tried replicating your issue from the schema given above.
I was not able to run into this issue.
Is it possible for you to send over a zip of your project?
<amplify-cli@amazon.com>

**Comment by rarira** [comment]
> @rarira I tried replicating your issue from the schema given above.
> I was not able to run into this issue.
> Is it possible for you to send over a zip of your project?
> [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)

I’m afraid I can’t..
Do you mean that a document with blockedBy string set is successfully indexed to es?
 
for examples.

updateClass(id:ID, blockedBy:[string1,string2,string3]) 

Is the job successfully indexed without lambda error I mentioned above?

**Comment by SwaySway** [comment]
Yea I did not run into that issue using the Console.
Are you using the AmplifyJS for these graphql operations?

**Comment by rarira** [comment]
> Yea I did not run into that issue using the Console.
> What client are you using to make these calls?

I use react-apollo client on appsync

**Comment by SwaySway** [comment]
@rarira Are you able to send the log where the lambda first logs the event? I'd to see if I can replicate it.

Log should start with something like the following
```
[DEBUG] 2019-12-11T19:36:50.57Z ... Event: {'Records': [{'eventID': '...
```

**Comment by rarira** [comment]
> @rarira Are you able to email the log where the lambda first logs the event? I'd to see if I can replicate it.
> 
> Log should start with something like the following
> 
> ```
> [DEBUG] 2019-12-11T19:36:50.57Z ... Event: {'Records': [{'eventID': '...
> ```


```
[DEBUG]	2019-12-11T19:55:05.835Z	360e758f-46ee-4db6-9a88-26c9fdea2b1c	Event: {'Records': [{'eventID': 'b75a65c75078fd00f233de6dac018ec9', 'eventName': 'MODIFY', 'eventVersion': '1.1', 'eventSource': 'aws:dynamodb', 'awsRegion': 'ap-northeast-2', 'dynamodb': {'ApproximateCreationDateTime': 1576094104.0, 'Keys': {'id': {'S': '0e105f2d-0ae6-4440-bdad-e92b9399616f'}}, 'NewImage': {'isLongTerm': {'BOOL': False}, 'numOfReported': {'N': '1'}, '__typename': {'S': 'Class'}, 'memo': {'S': '요기요기로 샘은 첨 구해 보네요\n필라도 하고 싶어요,dd,'}, 'numOfClass': {'N': '2'}, 'dateEnd': {'N': '1561129200'}, 'title': {'S': '샘 구함 테스트용'}, 'tagSearchable': {'S': '번지'}, 'timeEndString': {'S': '03:00+09:00'}, 'createdAtEpoch': {'N': '1566838557'}, 'createdAt': {'S': '2019-08-26T16:55:57.501Z'}, 'dayOfWeek': {'S': '[null,null,null,null,"thu",null,"sat"]'}, 'timeStart': {'N': '1560963600'}, 'dateStart': {'N': '1560956400'}, 'id': {'S': '0e105f2d-0ae6-4440-bdad-e92b9399616f'}, 'regionSearchable': {'S': '경기 성남시 분당구'}, 'updateCounter': {'N': '3'}, 'updatedAt': {'S': '2019-08-26T17:15:07.040Z'}, 'timeEnd': {'N': '1560967200'}, 'numOfApplications': {'N': '0'}, 'classCenterId': {'S': '6e6f244a-2874-4de1-ac55-679d5f889afa'}, 'classHostId': {'S': 'rarira'}, 'blockedBy': {'SS': ['Kakao_1068809107']}, 'classFee': {'N': '30000'}, 'classStatus': {'S': 'closed'}, 'expiresAt': {'N': '4716639219'}, 'timeStartString': {'S': '02:00+09:00'}, 'firstCreatedAt': {'S': '2019-06-12T07:33:48.700Z'}}, 'OldImage': {'isLongTerm': {'BOOL': False}, 'numOfReported': {'N': '1'}, '__typename': {'S': 'Class'}, 'memo': {'S': '요기요기로 샘은 첨 구해 보네요\n필라도 하고 싶어요,,'}, 'numOfClass': {'N': '2'}, 'dateEnd': {'N': '1561129200'}, 'title': {'S': '샘 구함 테스트용'}, 'tagSearchable': {'S': '번지'}, 'timeEndString': {'S': '03:00+09:00'}, 'createdAtEpoch': {'N': '1566838557'}, 'createdAt': {'S': '2019-08-26T16:55:57.501Z'}, 'dayOfWeek': {'S': '[null,null,null,null,"thu",null,"sat"]'}, 'timeStart': {'N': '1560963600'}, 'dateStart': {'N': '1560956400'}, 'id': {'S': '0e105f2d-0ae6-4440-bdad-e92b9399616f'}, 'regionSearchable': {'S': '경기 성남시 분당구'}, 'updateCounter': {'N': '3'}, 'updatedAt': {'S': '2019-08-26T17:15:07.040Z'}, 'timeEnd': {'N': '1560967200'}, 'numOfApplications': {'N': '0'}, 'classCenterId': {'S': '6e6f244a-2874-4de1-ac55-679d5f889afa'}, 'classHostId': {'S': 'rarira'}, 'blockedBy': {'SS': ['Kakao_1068809107']}, 'classFee': {'N': '30000'}, 'classStatus': {'S': 'closed'}, 'expiresAt': {'N': '4716639219'}, 'timeStartString': {'S': '02:00+09:00'}, 'firstCreatedAt': {'S': '2019-06-12T07:33:48.700Z'}}, 'SequenceNumber': '919705800000000006790823899', 'SizeBytes': 1430, 'StreamViewType': 'NEW_AND_OLD_IMAGES'}, 'eventSourceARN': 'arn:aws:dynamodb:ap-northeast-2:082649551475:table/Class-p7nt6t7fgvbw5jnh3yi2cuy3dy-dev/stream/2019-06-01T12:52:42.248'}]}
```

here is the log...
I just update data using dynamodb console directly,
I'm afraid I can't follow this any more today, see you and thanks.

**Comment by SwaySway** [comment]
Given the schema it would convert blockedBy into a list of strings as show below
```
'blockedBy': {'L': [{'S': 'third element'}]}
```
Are you explicitly including a string set?  If not could you send the resolver template for this?
`Mutation.createClass.req.vtl` or `Mutation.updateClass.req.vtl`

Located in 
`amplify/backend/api/<API_NAME>/build/resolvers'

**Comment by rarira** [comment]
> Given the schema it would convert blockedBy into a list of strings as show below
> 
> ```
> 'blockedBy': {'L': [{'S': 'third element'}]}
> ```
> 
> Are you explicitly including a string set? If not could you send the resolver template for this?
> `Mutation.createClass.req.vtl` or `Mutation.updateClass.req.vtl`
> 
> Located in
> `amplify/backend/api/<API_NAME>/build/resolvers'

Oh... do I have to use List of Strings not StringSet to be indexed to ES?
Indeed I have custom resolver explicitly including a StringSet as belows

```
$util.qr($context.args.input.put("updatedAt", $util.defaultIfNull($ctx.args.input.updatedAt,
$util.time.nowISO8601())))
$util.qr($context.args.input.put("__typename", "Class"))

{
  "version": "2017-02-28",
  "operation": "UpdateItem",
  "key": {
    "id": {"S": "${ctx.args.input.classId}"}
  }, 
  "update": {
    "expression": "SET updatedAt = :upTime ADD blockedBy :user#if(($context.arguments.input.numOfReported)), numOfReported :number#{end}",
    "expressionValues" : {
      ":user":{ "SS": [ "${ctx.args.input.blockedBy}" ] },
      ":upTime": {"S": "${ctx.args.input.updatedAt}"}
      #if(($context.arguments.input.numOfReported))
      ,":number": {"N": ${ctx.args.input.numOfReported}}
      #end
    }
  }

```

If I had to use 'List of String', is there any way to delete an item from that list by value not index?
I know that DELETE works only for sets so now I have to use StringSet..

and that means DdbToEsFn lambda still can't work with sets and I think it is a bug.
at least it should be documented properly

**Comment by SwaySway** [comment]
@rarira
Yes the lambda does not work with sets as it converts the streamed data into json.
This json is included in the payload to elasticsearch.

One way to solve this would be to change the set into a list so it can be included in the payload and it supported under [elasticsearch's field datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html)

**Comment by rarira** [comment]
> @rarira
> Yes the lambda does not work with sets as it converts the streamed data into json.
> This json is included in the payload to elasticsearch.
> 
> One way to solve this would be to change the set into a list so it can be included in the payload and it supported under [elasticsearch's field datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html)

Ok, I know that, but I have to use stringset because it supports DELETE update expression. Moreover I don’t need my stringset data to be indexed, so just want the lambda to process document before indexing so that if the document has string set, it can be indexed successfully without stringset.

**Comment by SwaySway** [comment]
Closing this issue as the pr has been merged.
