### ISSUE TITLE
cli is unusable: No options shown for "Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)"

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-cli#2861]
**Describe the bug**

the cli started popping up errors such as:
- amplify Cannot find module 'strip-indent'
- The 'request' argument must be string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
  
I've started to just delete things, amplify remove env, amplify delete, none of these worked, so i deleted the amplify folder, and now when i try to recreate the amplify project I get the above error

One thing I did do earlier was to deploy a lambda with serverless : "serverless deploy"

could this have broken everything? I'm in a very bad place at the moment.

**Amplify CLI Version**
4.1.1
I'm using NVM with node version 12.

The necessary plugin exists, from what I can see:

 ⁨.nvm⁩ ▸ ⁨versions⁩ ▸ ⁨node⁩ ▸ ⁨v12.10.0⁩ ▸ ⁨lib⁩ ▸ ⁨node_modules⁩ ▸ ⁨@aws-amplify⁩ ▸ ⁨cli⁩ ▸ ⁨node_modules⁩ ▸ ⁨amplify-provider-awscloudformation

**Expected behavior**

**Comment by yuth** [comment]
It appears a dependency was missing but our CI process didn't flag and stop a build. We're in the process of resolving this and pushing out a new version, then we'll deep dive into why the dependency didn't get flagged. I'll respond here once the new build is out.

**Comment by yuth** [comment]
We have released Amplify CLI version `4.2.0` which should fix this error. Please feel free to re-open or comment if you're still facing issue with Amplify CLI `v4.2.0`

Could you see if you can use the [amplify pull](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#amplify-pull) command to restore your application

**Comment by evertson90** [comment]
I also have this issue at the moment since upgrading to version 4.1.1. I tried to do an "Amplify update auth" and now nothing works anymore. I also have no options when it asks me "Select the backend providers" and when I press enter I get the following:

`✖ There was an error initializing your environment.
init failed
TypeError: Cannot read property 'loadResourceParameters' of undefined
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:344:41)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:213:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by kyanet** [comment]
@blomm  if you are using yarn this may helps you.
https://github.com/aws-amplify/amplify-cli/issues/34
> How I eventually got it working is that I switched from using yarn to npm. Using npm with a global install of @aws-amplify/cli works now, and I can choose the app type on the second step of amplify init.

**Comment by blomm** [comment]
@kyanet thanks, all was sorted when I installed version 4.2 of the CLI. there was an issue with the previous deployment missing dependencies which was sorted in 4.2

**Comment by attilah** [comment]
Fixed and released from 4.2.0+
