### ISSUE TITLE
What goes in owner field for email based logins

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2862]
**Which Category is your question related to?**
Auth, API, GraphQL Transform

**Amplify CLI Version** 
3.17.0 

What value goes into an owner field for owner auth when using email for the login? I noticed the username is a uuid...

**Comment by attilah** [comment]
@aireater I'd always specify ```sub``` because that will be unique no matter what is user to authenticate the user. Currently ```username``` is the default, that's why you see it there, but email is another cognito builtin attribute, it is not taking over the place of the username field.
