### ISSUE TITLE
Error adding Auth

### ISSUE THREAD

**Issue by apekshajain** [aws-amplify/amplify-cli#2863]
I am getting the following error adding auth 

amplify add auth
No services defined by configured providers for category: auth

amplify -v
4.1.1

Environment : Cloud9

**Comment by yuth** [comment]
We have released Amplify CLI version `4.2.0` which should fix this error. Please feel free to re-open or comment if you're still facing issue with Amplify CLI `v4.2.0`

**Comment by Townsheriff** [comment]
Having same issue with version 4.6.0.
