### ISSUE TITLE
Domain name prefix default is invalid

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-cli#2869]
**Describe the bug**

When running `amplify add auth`, a domain prefix default is provided, but when pressing <kbd>Enter</kbd>, an error message indicates it is invalid.

**Amplify CLI Version**

`4.2.0`

**To Reproduce**

1. `npx create-react-app photo-albums`
1. `cd photo-albums`
1. `amplify add auth`
1. Select `Default configuration with Social Provider (Federation)`
1. Press <kbd>Enter</kbd> to select all the defaults.

**Expected behavior**

The CLI should remove `_` from the default.

```js
"Photo_Albums-1234FIVEsixSEVEN".toLowerCase().replace(/[^a-z0-9-]/g, "")
// "photoalbums-1234fivesixseven"
```

**Screenshots**

```console
❯ amplify add auth
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
 What domain name prefix you want us to create for you? (photo_albums69a26ebf-69a26ebf) photo_albums69a26ebf-69a26ebf
>> The value must be a valid domain name format.  A valid format consists of lowercase alphanumeric characters or hyphens. Hyphens cannot be at the beginning or end of the string. The domain cannot use the reserved words 'aws' or 'amazon'.
```

**Desktop (please complete the following information):**
 - OS: mac
 - Node Version. `v13.2.0`

**Comment by ericclemmons** [comment]
Same for `amplify add cli`:

```console
❯ amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: photo-albums
>> You can use the following characters: a-z A-Z 0-9
```

**Comment by kaustavghosh06** [comment]
#3099 fixes this issue. We just merged it and should be a part of our next release (v4.12)

**Comment by ericclemmons** [comment]
Thanks @kaustavghosh06!
