### ISSUE TITLE
When do I set up amplify configure

### ISSUE THREAD

**Issue by dongw00** [aws-amplify/amplify-cli#287]
** Which Category is your question related to? **
amplify configure

** What AWS Services are you utilizing? **
amplify

** Provide additional details e.g. code snippets **
Specify the AWS Region
? region:  list....

When do I set up ampify configure, my region is omitted. (np-northeast-2)

**Comment by kaustavghosh06** [comment]
We currently support the regions listed below. We'll be adding support for more regions in the future.

```
  'us-east-1': 'US East (N. Virginia)',
  'us-east-2': 'US East (Ohio)',
  'us-west-2': 'US West (Oregon)',
  'eu-west-1': 'EU (Ireland)',
  'eu-central-1': 'EU (Frankfurt)',
  'ap-northeast-1': 'Asia Pacific (Tokyo)',
  'ap-southeast-1': 'Asia Pacific (Singapore)',
  'ap-southeast-2': 'Asia Pacific (Sydney)',
  'ap-south-1': 'Asia Pacific (Mumbai)',
```

**Comment by bearchit** [comment]
Any plan for support ap-northeast-2?
