### ISSUE TITLE
Pretty print all templates consistently, so that diffs are easier to read

### ISSUE THREAD

**Issue by rowanu** [aws-amplify/amplify-cli#2878]
**Is your feature request related to a problem? Please describe.**
I've only been using the Amplify CLI for a while, and in that time I've found it hard to track the changes that my CLI commands are making, because the resulting templates do not seem to be consistent (e.g. indenting, ordering, etc).

**Describe the solution you'd like**
It would be great to make the outputted files as consistent as possible so that they can be easily compared with previous versions, to see that the CLI is doing what's expected.

This could be done by tweaking the [generate](https://github.com/aws-amplify/amplify-cli/blob/167092585cd4a527f80ec00a988706f9ed06717d/packages/amplify-cli/src/context-extensions.ts#L311) call that is being used to generate templates. This would use `JSON.stringify` for JSON files, and something like [js-yaml](https://www.npmjs.com/package/js-yaml) for YAML.

Note that the `paramsFile` is already being written in a consistent manner, because it uses `JSON.stringify`.

**Additional context**
I'd be happy to do a PR for this if the idea is acceptable.

**Comment by josefaidt** [comment]
Closing as the resources' CloudFormation templates have since been migrated to an ephemeral `build/` directory
