### ISSUE TITLE
amplify mock api - stuck while creating tables locally

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#2892]
I already have an issue which was closed because of inactivity but this is still an issue and the `mock` ability hasn't worked for me once. #2064 

**Describe the bug**
I am attempting to run the new `amplify mock api` which allows local mocking and testing for AppSync, this then outputs `GraphQL schema compiled successfully.` and continues to create the DynamoDB tables locally, then I see each table being created and after creating 10 tables, at the 11th table it is just stuck without any output, I left it running for about an hour and nothing.
note - our schema has 11 `@model`s so maybe this happens for the last table

**To Reproduce**
1. `amplify api add`
2. create your GraphQL schema
3. `amplify push`
4. `amplify mock api` - this command will never load all of your tables

**Expected behavior**
Should load all tables locally and open the GraphQL console locally, or give an error saying that it couldn't load table X for reason Y.

**Screenshots**
![image](https://user-images.githubusercontent.com/28350511/63162293-cb17ba00-c02a-11e9-82bc-0ca611439cec.png)

Even after deleting the entire schema and only creating one model like so -
```
type Hello @model {
  id: ID!
}
```

![image](https://user-images.githubusercontent.com/28350511/69913144-9ba38680-143c-11ea-82fa-53cffcbfd31f.png)

**Desktop (please complete the following information):**
 - OS: [MacOs 10.15.1]
 - Browser [chrome]
 - Version [78.0.3904.108]

**Additional context**
@aws-amplify/cli version - 4.2.0

**Comment by idanlo** [comment]
When running the command `amplify mock` I get this *error code* after going to `http://localhost:20005` -
![image](https://user-images.githubusercontent.com/28350511/69913324-f63de200-143e-11ea-812d-c6bd813cbc18.png)

**Comment by ammarkarachi** [comment]
@idanlo Thanks for bringing this to our attention. Does it break with one model or does it just print "error"?

**Comment by idanlo** [comment]
It prints a `error` after going to the endpoint and attempting to perform a query

**Comment by ammarkarachi** [comment]
@idanlo if you are ok with it could you share your schema over email at amplify-cli@amazon.com

**Comment by idanlo** [comment]
@ammarkarachi After updating to the latest amplify cli and running `amplify mock api`, all tables are created locally but then I get a lot of `Failed to parse Lambda function cloudformation in function-cloudformation-template.json`

**Comment by idanlo** [comment]
In the end of the schema I have a `type Mutation` declaration with all the lambda function calls (mutations that use the @function directive), and these cause errors like `Lambda function X does not exist`, when I remove the `type Mutation` declaration with all the `@function` calls the mock works

**Comment by ammarkarachi** [comment]
Can you share your syntax you are currently using? This is what the transformer expects

`type Mutation {
  putString(msg: String): String @function(name: "putString-${env}")
}`

**Comment by idanlo** [comment]
@ammarkarachi  Yes, this is exactly what my syntax looks like

**Comment by ammarkarachi** [comment]
@idanlo We will need more information in regards to steps performed or the state of you application  to resolve this

**Comment by danny-waite** [comment]
I'm getting the same issue, with any type with a @model directive

**Comment by ammarkarachi** [comment]
@idanlo @danny-waite Can you give me more context? If you could share your schema it would greatly help

**Comment by ammarkarachi** [comment]
@idanlo @danny-waite Do you still need help with this?
