### ISSUE TITLE
Changing API for amplify codegen

### ISSUE THREAD

**Issue by ChrisWun** [aws-amplify/amplify-cli#290]
** Which Category is your question related to? **
Amplify codegen

** What AWS Services are you utilizing? **
AWS Appsync API

** Provide additional details e.g. code snippets **
With the command `amplify add codegen --apiId xyz` it is possible to set up `codegen` for an `appsync api`. Unfortunately, I found no way to change the api. Is that possible? If not, I would like to have such a functionality.

**Comment by yuth** [comment]
We don't have a provision to change the API but will add it as a feature request. For the time being you could delete `.graphqlconfig.yml` file in your project root and add the API again by running `amplify add codegen --apiId #####`

**Comment by ChrisWun** [comment]
Thanks for the workaround :)
