### ISSUE TITLE
API module for GraphQL doesn't detect change after configure additional auth types

### ISSUE THREAD

**Issue by vcamarggo** [aws-amplify/amplify-cli#2900]
**Describe the bug**
After changing the additional auth type for API module, amplify status doesn't detect any change.

**Amplify CLI Version**
4.2.0

**To Reproduce**
amplify init
amplify add api
GraphQL
default authorization type for the API Amazon Cognito User Pool (everything default)
amplify push
amplify update API
default authorization type for the API Amazon Cognito User Pool
additional auth types? Yes
additional authorization types: API key
amplify status

**Current behavior**
| Api      | myprojtest         | No Change | awscloudformation |

**Expected behavior**
| Api      | myprojtest         | Update    | awscloudformation |

**Desktop (please complete the following information):**
 - OS:  Windows10
 - Node Version: 6.13.1

**Comment by attilah** [comment]
@vcamarggo This is a known issue, thanks for reporting.

**Comment by kaustavghosh06** [comment]
We've implemented `amplify push --force` with version 4.16.0. You can use that to deploy just your auth settings - without having a need to change the schema or your Cloudformation file.
