### ISSUE TITLE
Cannot delete "Notifications" category

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-cli#2903]
**Describe the bug**
I thought I had deleted my "Analytics" category using the amplify cli, as it had no reference to Pinpoint instances or "Analytics" categories. It turns out that this was not the case, and the Pinpoint instance still existed, despite not appearing in the cli (using `amplify status`). So I opted to delete the Pinpoint instance in the respective AWS console itself. I've always had trouble deleting the Notifications category, however, it wasn't causing errors like it is now (e.g. `not authorized to perform mobiletargeting:UpdateEndpoint...`).

I can start the CLI walkthrough of `amplify remove notifications` but when I'm prompted to delete the respective Pinpoint instance (which no longer exists), and select yes, I get the following error:

```
$ amplify remove notifications --force
? Choose what to remove. The Pinpoint application
? Confirm that you want to delete the associated Amazon Pinpoint application Yes
✖ Pinpoint project deletion error
Application not found
NotFoundException: Application not found
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
```

**Amplify CLI Version**
```
$ amplify -v
4.2.0
```

**To Reproduce**
Create an instance of the "Notifications" category and manually delete the Pinpoint instance through the AWS console/dashboard. You should no longer be able to `amplify remove` the "Notifications" category.

**Expected behavior**
I expect to be able to remove the "Notifications" category cli-reference, either through the CLI's walkthrough or by deleting all references to the category in the codebase.

**Desktop (please complete the following information):**
 - OS: `macOS 10.15.1`
```
$ node -v
v12.9.1
```

**Additional context**
I can't recall how, but through some tinkering in the `amplify` folder, I was able to delete the "Analytics" category cli-reference, that I had to create for the "Notifications" category. I believe I deleted all references to it in the `amplify` folder.

**Comment by potatopotaro** [comment]
If there's a way to do it manually/technically (e.g. cloudformation), please share, as I wouldn't mind such a solution. This bug is currently blocking me from my work.

**Comment by UnleashedMind** [comment]
The Pinpoint project has already deleted by you manually on the Pinpoint console (we do not recommend doing that), obviously you won't be able to delete it again. The Notifications category does not use Cloudformation for security reasons. 

You will need to remove all the Notifications and Analytics related contents from your local project's `amplify` folder. Follow these steps: 
1. Thoroughly backend up your project codebase just in case things go unexpected.
2. Remove the `"notifications"` section in the `amplify-meta.json` and `backend-config.json` files in both the `backend` and `#current-cloud-backend` folder. 
3. Remove the `"analytics"` section in the `amplify-meta.json`  and `backend-config.json` files in both the `backend` and `#current-cloud-backend` folder. 
4. Remove the `"analytics"` subfolders in both the `backend` and `#current-cloud-backend` folder. 
5. Remove the `"notifications"` section from the `team-provider-info.json` file

You will also need to manually remove pinpoint related fields the frontend configuration file, for js projects, it's `src/aws-exports.js`, remove these two lines. 
```
...
    "aws_mobile_analytics_app_id": "xxxx",
    "aws_mobile_analytics_app_region": "xxx"
```

**Comment by kaustavghosh06** [comment]
@potatopotaro Please let us know if you're still stuck on this issue. Closing this issue for now.
