### ISSUE TITLE
In app set to ap-southeast-2 region, it creates pinpoint in the us-west-2 region

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#2913]
Why are the apps in southeast-2 region mapped to pinpoint projects in the us-west-2 region, when there seems to be support for pinpoint AWS service in ap-southeast-2 (Sydney) region also?
Would it be OK if I create the analytics pinpoint category, change the mapping myself, and then do amplify push?

**Comment by UnleashedMind** [comment]
Amazon Pinpoint has expanded its supported regions, the current Amplify CLI region mappings were set up in the December of 2018, when Pinpoint was not available in that region. 
We will update the mappings.

**Comment by tgjorgoski** [comment]
Thanks, I guess you will open the necessary tickets for that work, so if yes, I guess we can close this one, and I will wait for the update :)
