### ISSUE TITLE
CloudFormation Error: Template may not exceed 460800 bytes in size.

### ISSUE THREAD

**Issue by rrrix** [aws-amplify/amplify-cli#2914]
**Describe the bug**

CloudFormation Error "Template may not exceed 460800 bytes in size." when trying to use `amplify push`. My schema.graphql is very large and quite complex.

This is _**not**_ a duplicate of #185, #162, or #151, since those were created before Amplify CLI supported nested/split stacks. 

**Amplify CLI Version**
4.3.0

**To Reproduce**

I've setup a demonstration schema and repository specifically for this issue:

`amplify init --app https://github.com/rapticore/amplify-stack-size-bug.git`

It's composed of:
- GraphQL API with complex schema.graphql
- Cognito Auth

![image](https://user-images.githubusercontent.com/3194704/70037901-3189ff00-156c-11ea-9628-7b35ab2cafc3.png)

**Expected behavior**
Deployment was successful.

OS: MacOS 10.15 Catalina
Node v12.13.0

**Comment by attilah** [comment]
This is at the edge of bug/enhancement, we'll investigate the possible solutions for it, probably new nested stacks must be introduced to get over this size limitation.

**Comment by kaustavghosh06** [comment]
@rrrix Looks like the "connections" stack is getting the template exceed error. If you re-structure your app to have fewer @connections - you can get past this error.

**Comment by rrrix** [comment]
Hey @kaustavghosh06, just an FYI - I've forked the `amplify-cli` project (https://github.com/rapticore/amplify-cli) and converted everything to use YAML for all CloudFormation templates, and fixed many other bugs too. This bug/feature request still stands though, since I don't want to maintain my own fork. :)  Plus I want all my @connection's. I'm honestly surprised that I'm the first person to experience this - I doubt I will be the last.

**Comment by kaustavghosh06** [comment]
@rrrix Would it be possible for you to submit PR's for your bugs/fixes which you have? We can take a look at it and merge it into our CLI repo.

**Comment by oliverandersencox** [comment]
@rrrix I've had this a few times. Is there really a limit of the number of connections and models!!!?

**Comment by rrrix** [comment]
Yes, I don't think there are any test cases or clear limits on exactly how many resources one can have in an Amplify project. 

My company has **completely** abandoned Amplify CLI in favor of AWS CDK, which is immeasurably more robust and scalable, and improving at a breakneck pace, albeit more complex. 

Some questions which should really be already answered:
* How many tables can an Amplify project support?
* How many connections can it support?
* How many Lambda functions, buckets, or other resources can it support? 
* What other limits, generally, should users be aware of when adding resources? 

Of course there is always the option of using the custom CloudFormation nested stack.... But that defeats the whole purpose of what Amplify is for IMO. 

Just my $0.02.
