### ISSUE TITLE
cli creates aws-exports.js for a mobile project, even though I selected Javascript during amplify init

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-cli#2916]
**Describe the bug**
amplify init, chose 

> ? Enter a name for the project amp
> ? Enter a name for the environment dev
> ? Choose your default editor: Visual Studio Code
> ? Choose the type of app that you're building javascript
> Please tell us about your project
> ? What javascript framework are you using angular
> ? Source Directory Path:  src
> ? Distribution Directory Path: dist
> ? Build Command:  npm run-script build
> ? Start Command: ng serve
> Using default provider  awscloudformation

...and the resulting aws-exports file only contained
```
const awsmobile = {
    "aws_project_region": "eu-west-1"
};

export default awsmobile;

```

whereas I was expecting a different format in this style (but not exactly like this obviously, as I haven't added auth or api yet):

```
Auth: {
    identityPoolId: 'ca-central-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    region: 'ca-central-1',
    userPoolId: 'ca-central-xxxxxxxxxx',
    userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxx',
  },
  API: {
    endpoints: [
      {
        name: 'ApiGateway',
        endpoint: 'https://xxxxxxxxxx.execute-api.ca-central-1.amazonaws.com/Dev/',
        region: 'ca-central-1'
      }
    ]
  }
```

**Amplify CLI Version**
4.2

**Additional context**

**Comment by UnleashedMind** [comment]
You need to add the API category and push before you can get such configuration section. 
After `amplify init` completes
1. run `amplify api add` and select REST as the API type
2. run `amplify push`

**Comment by kaustavghosh06** [comment]
@blomm Please let us know if you're still stuck on this issue. Closing this issue for now.
