### ISSUE TITLE
Environment gets removed despite entering "No"

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-cli#2929]
**Describe the bug**
After running `amplify env remove <ENV_NAME>` (in this case `ENV_NAME = staging`).

I was prompted with `Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files)`. I selected "No" (by entering the `n` character) and yet the CLI still deleted the environment locally.

**Amplify CLI Version**
```
$ amplify -v
4.5.0
```

**To Reproduce**
1. Create at least 2 environments
2. Run `amplify env list` and notice your environments
3. Run `amplify env remove <ENV_NAME>`
4. When prompted with `Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files)`, type `n` and press enter.
5. Run `amplify env list` and notice you're missing the env you provided in step 3.

**Screenshots**
(Note: Sorry I don't have a screenshot of `amplify env list` with `staging`, you'll have to trust that it existed 😅)

![Screen Shot 2019-12-05 at 3 01 37 AM](https://user-images.githubusercontent.com/16728256/70221184-83b65600-170d-11ea-9f7e-f50bc6d639fd.png)
![Screen Shot 2019-12-05 at 3 05 20 AM](https://user-images.githubusercontent.com/16728256/70221183-83b65600-170d-11ea-90ca-e0745b7e136e.png)

**Desktop (please complete the following information):**
 - OS: `OS X 10.15.1`
 - Node Version: `v12.9.1`

**Comment by potatopotaro** [comment]
Semi related: https://github.com/aws-amplify/amplify-cli/issues/2930

**Comment by kaustavghosh06** [comment]
Fix for this has been merged and released with v4.7.
