### ISSUE TITLE
@function directive causes CREATE_FAILED on FunctionDirectiveStack

### ISSUE THREAD

**Issue by dsoffiantini** [aws-amplify/amplify-cli#2934]
I added a custom mutation with lambda resolver to my schema, but once i tried to deploy it via amplify push, the build consistently fails with the error: 
`S3 error: The bucket you are attempting to access must be addressed using the specified endpoint.`

Code I added

```
type Mutation {
  createFoo(name: String!) : String @function(name: "myfunction-${env}")
}
```

Both the function and api were previously deployed. As soon as I remove the @function directive, the build works fine but no mutation is added.

**Comment by attilah** [comment]
@dsoffiantini could you share the steps you used to add the custom mutation and lambda resolver, or better a repro project that we could use? Any other error from CF on why the creation failed would also help.

**Comment by dsoffiantini** [comment]
Sure!

To create the lambda, I used the `amplify add function` to create a lambda with permissions on my api. Afterwards, I ran `amplify push` to deploy the lambda to the cloud. This worked fine.

Next I added the following to my graphql type code:
```
input EmailInput {
  toAddresses: [String!]!
  html: String
}

type Mutation {
  createEmail(input: [EmailInput!]!): String @function(name: "my-function-${env}")
}
``

and tried to run amplify push, but I was getting the above error. I've seen updated the amplify cli and I get
```
Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
```

but again as soon as I remove the @function directive it deploys fine.

**Comment by kaustavghosh06** [comment]
@dsoffiantini Which region are you trying to deploy to?

**Comment by undefobj** [comment]
@dsoffiantini Are you still having trouble?

**Comment by RidhwanDev** [comment]
I'm currently having this exact problem, deploying to eu-west-1
