### ISSUE TITLE
Amplify Mock  AWSAppSyncRealTimeProvider Connection error

### ISSUE THREAD

**Issue by riacoding** [aws-amplify/amplify-cli#2935]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Create a fresh react project and add amplify to it with an API. On running `amplify mock api` the graphql subscriptions are not working as expected with the AWSAppSyncRealTimeProvider having a connection failed exception after timeout.

**Amplify CLI Version**
Amplify/Cli@4.5.0

**To Reproduce**
Following demo from aws blog post by Nikhil Dabhade
[https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/](https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/)

```
npx create-react-app myapp
amplify init
amplify add api
npm i aws-amplify
```

replace App.js with code below

```
import React, { useEffect, useReducer } from "react";
import Amplify from "@aws-amplify/core";
import { API, graphqlOperation } from "aws-amplify";
import { createTodo } from "./graphql/mutations";
import { listTodos } from "./graphql/queries";
import { onCreateTodo, onUpdateTodo } from "./graphql/subscriptions";

import config from "./aws-exports";
Amplify.configure(config); // Configure Amplify

const initialState = { todos: [] };
const reducer = (state, action) => {
  switch (action.type) {
    case "QUERY":
      return { ...state, todos: action.todos };
    case "SUBSCRIPTION":
      return { ...state, todos: [...state.todos, action.todo] };
    default:
      return state;
  }
};

async function createNewTodo() {
  const todo = { name: "Use AppSync", description: "Realtime and Offline" };
  await API.graphql(graphqlOperation(createTodo, { input: todo }));
}
function App() {
  const [state, dispatch] = useReducer(reducer, initialState);

  useEffect(() => {
    getData();
    const subscription = API.graphql(graphqlOperation(onCreateTodo)).subscribe({
      next: eventData => {
        const todo = eventData.value.data.onCreateTodo;
        dispatch({ type: "SUBSCRIPTION", todo });
      }
    });
    return () => {
      subscription.unsubscribe();
    };
  }, []);

  async function getData() {
    const todoData = await API.graphql(graphqlOperation(listTodos));
    dispatch({ type: "QUERY", todos: todoData.data.listTodos.items });
  }

  return (
    <div>
      <div className="App">
        <button onClick={createNewTodo}>Add Todo</button>
      </div>
      <div>
        {state.todos.map((todo, i) => (
          <p key={todo.id}>
            {todo.name} : {todo.description}
          </p>
        ))}
      </div>
    </div>
  );
}
export default App;
```
`amplify mock api`
`npm start `

**Expected behavior**
From the http://localhost:20002/ local endpoint using graphiql to create a mutation create a todo item. This would then be automatically updated on the http://localhost:3000/ endpoint via the graphql subscription.

**Screenshots**
![Screen Shot 2019-12-05 at 8 44 23 PM](https://user-images.githubusercontent.com/365494/70298551-e0198400-17a6-11ea-86e4-d610f5759809.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.6
 - Node Version. 10.17.0 

**Additional context**
The mutations are being persisted to the local database and the changes can be viewed by refreshing the page, however, the websocket is not updating in realtime.

**Comment by attilah** [comment]
@riacoding Mock does not yet support the new WebSocket based subscriptions, only MQTT and the code you're trying to run using the new AmplifyJS library is leveraging the new WebSocket based subscriptions, hence creating this error for you.

**Comment by riacoding** [comment]
@attilah is there a roadmap to have this feature implemented? I understand the issue but it seems more of a regression as it was working in 1.2.4. I have been looking at the repo ,Am I right to assume that the mock would need to implement a pure WS server instead of MQTT to handle the new AWSAppSyncRealtimeProvider?

**Comment by narayanncube** [comment]
@riacoding - any success on this?

**Comment by riacoding** [comment]
They said it’s in the pipeline for getting fixed but there is no timeline
as of yet

**Comment by narayanncube** [comment]
Ok

Thanks for replying

**Comment by camin-mccluskey** [comment]
any update on this @riacoding

**Comment by riacoding** [comment]
Not at this time. Last I heard it was on the backlog but with no priority.
Hopefully the more awareness the quicker the fix

**Comment by dillonharless18** [comment]
Facing this issue as well still.

**Comment by passedByMe** [comment]
we are at the second wave of god damn covid! 
this thing is still not working...

**Comment by PeterMitrano** [comment]
+1 for this fix

**Comment by mgarabedian** [comment]
Unsure if this is the same original issue above, but I filed this bug regarding Mock AppSync Subscriptions.
https://github.com/aws-amplify/amplify-cli/issues/9621

**Comment by josefaidt** [comment]
Hey y'all as noted in @mgarabedian 's comment this item is currently being tracked on #9621. Closing in favor of tracking 9621. As a workaround we can use a proxy or frontend app config to rewrite `/graphql/realtime` to `/graphql` during mock.
