### ISSUE TITLE
Using a pre existing function for auth triggers

### ISSUE THREAD

**Issue by Jkap7788** [aws-amplify/amplify-cli#2936]
Hi,

Is it possible to use a pre-existing lambda function as an auth trigger (e.g preSignup, postConfirmation, etc.)

Currently, the cli will create a lambda function under the function category.

Would we be able to override this behaviour by supplying a lambda arn to use instead?

Thanks!

**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
3.17

**Comment by kaustavghosh06** [comment]
@Jkap7788 This is not currently supported out of the box, but you can take a look at the Auth cloudformation template and replace the postConfirmation attribute to your custom function name (which is outside of the Amplify project)

**Comment by Jkap7788** [comment]
@kaustavghosh06 Thanks for the reply, will probably migrate over to a function managed by the cli, I'm wary of changing the auth template manually as my changes may be overwritten in the future.

Thanks!

**Comment by ChristopheBougere** [comment]
I am currently using lambdas deployed with Serverless for my custom AppSync resolvers, and it works well. It is quite easy to define the lambda name using the `${env}` variable: `@function(name: "serviceName-${env}-lambdaName")`.

It would be very useful to have the same capability for lambda triggers.

@Jkap7788 @kaustavghosh06 Could we reopen this issue, and mark it as a feature request?
