### ISSUE TITLE
Disabling DEBUG logging in python_streaming_function raises KeyError

### ISSUE THREAD

**Issue by PatrykMilewski** [aws-amplify/amplify-cli#2938]
**Describe the bug**
When I try to remove DEBUG Lambda environment variable, to stop lambda from logging debug messages, it raises KeyError exception:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    DEBUG = True if os.environ['DEBUG'] is not None else False
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
```

**Amplify CLI Version**
latest

**To Reproduce**
Remove DEBUG lambda environment variable from deployed python_streaming_function or simply try to run this code without DEBUG env variable:
`DEBUG = True if os.environ['DEBUG'] is not None else False`

**Expected behavior**
When I unset DEBUG env variable, it shouldn't raise KeyError and stop logging debug logs.

I will fix it myself and create Pull Request.

**Comment by PatrykMilewski** [comment]
Oh wait, I can't create a new Pull Request? Anyways, it should be fixed like this:
`DEBUG = True if os.environ.get('DEBUG') is not None else False`

**Comment by ammarkarachi** [comment]
@PatrykMilewski thanks for submitting this issue. As for the pull request you can create one what you would have to do is.

- Fork amplify-cli
- Make changes and push on a branch from your fork
- Create a pull request using the branch on your fork

**Comment by SwaySway** [comment]
Closing this issue as the fix has been merged.
