### ISSUE TITLE
Access Denied on amplify push

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#2941]
**Describe the bug**
After update to 4.5.0, when attempting to push changes, pull dev env, amplify init (to try to refresh the project?) or mock I get the following error: 

`Fetching updates to backend environment: dev from the cloud.(node:44678) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied`

The pulling dev env messages hangs and I have to terminate it. 

**Amplify CLI Version**
4.5.0

**To Reproduce**
Not sure, just upgraded to latest CLI, nothing else changed in the project. 

**Expected behavior**
Ability to push after upgrade. 

**Desktop (please complete the following information):**
 - OS: mac
 - Node Version. 12.10.0

**Comment by aireater** [comment]
Tracked down problem. I called one of my profile's "default" and i believe it was overwritten by the aws cli when i entered credentials for another account.

**Comment by jasonprado** [comment]
@kldeb How did you determine that you had mismatched profiles and how did you fix it?

**Comment by kldeb** [comment]
@jasonprado i can't remember how i figured it out. i changed the name of the default profile that amplify was using in `~/.aws/credentials` to be more descriptive and let aws-cli have the default name.

**Comment by carlosortizpacheco** [comment]
@jasonprado  
in my case I had this error because I am working with different aws accounts ... Run **amplify configure** and when you get to the part where it asks for your credentials (API Key and Secret Key) put them for that account ... In my case this works...

**Comment by aditi172** [comment]
> @jasonprado
> in my case I had this error because I am working with different aws accounts ... Run **amplify configure** and when you get to the part where it asks for your credentials (API Key and Secret Key) put them for that account ... In my case this works...

I'm having the same issue but even after configuring amplify again with proper creds my issue still persists
....
(node:13148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
| Fetching updates to backend environment: dev from the cloud.

**Comment by nicolasheady** [comment]
> > @jasonprado
> > in my case I had this error because I am working with different aws accounts ... Run **amplify configure** and when you get to the part where it asks for your credentials (API Key and Secret Key) put them for that account ... In my case this works...
> 
> I'm having the same issue but even after configuring amplify again with proper creds my issue still persists
> ....
> (node:13148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:13148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> | Fetching updates to backend environment: dev from the cloud.

You ever fix this? I've been having this same issue for two days now...
