### ISSUE TITLE
Copy last stable local Amplify configuration into a format that can be version controlled and used as a disaster recovery solution when a local environment becomes corrupted

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#2942]
**Is your feature request related to a problem? Please describe.**
A lot of issues on this page stem from local environments getting corrupted, which if you're not careful can lead to all sorts of other knock-on effects like deleting CF stacks, individual resources, etc., which then lead to more knock-on effects: see the post about someone who accidentally deleted their user pool and had to switch from SRP_AUTH to USER_PASSWORD_AUTH as a result, which then caused an SDK method to break.  

**Describe the solution you'd like**
There should be an escape hatch/reset button for local environments. That would lead to workflows where developers hit the reset button before they hit push. This state, in my opinion, should be saved upon each call to `amplify status` which reports that all categories are in a `No Update` status. 

It would also allow you to re-initialize a project from any branch -- presumably a branch that maps to an env, say branch `alpha` with a version controlled local config for Amplify env `alpha` -- assuming that the user is optionally reprompted for some environment variables, like directory path.

**Describe alternatives you've considered**
As far as I know (docs are updated quite frequently nowadays, which is a really great problem to have!) there is no documentation or generic advice on how to fix corrupted local environments.

**Additional context**
The best issues are those that are never written.

**Comment by jkeys-ecg-nmsu** [comment]
Related to #898 but more focused on checkpointing projects in a version controlled manner as a safety and quality of life improvement.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu We recently launched support for "amplify pull" command which takes advantage of the fact that the Amplify service now stores the state of our Amplify app and this state can be easily restored with the `amplify pull` command.
