### ISSUE TITLE
amplify add api crashes when creating a GraphQL api

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-cli#2943]
**Describe the bug**
When I run the following commands to generate a GraphQL API for React it crashes. 

```
> amplify add api
? Please select from one of the below mentioned services: GraphQL
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/pr
ovider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:1
import { getDataStoreLearnMore } from '../sync-conflict-handler-assets/syncAssets';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (vm.js:379:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

**To Reproduce**
Run `amplify add api`

**Expected behavior**
Continue with creation API flow without errors.

**Screenshots**
NA

**Desktop:**
 - OS: macOS 10.14.6
 - Browser: Version 78.0.3904.108 (Official Build) (64-bit)
 - Node: 13.3.0
 - npm: 6.13.1
 - Amplify CLI: 4.5.0

**Comment by attilah** [comment]
Fixed in: https://github.com/aws-amplify/amplify-cli/pull/2954
