### ISSUE TITLE
Datastore: amplify codegen model (amplify-modelgen) generates string instead of String type in schema.js

### ISSUE THREAD

**Issue by jordan-patapoff** [aws-amplify/amplify-cli#2945]
**Describe the bug**
`amplify codegen model` (amplify-modelgen) generates `string` instead of `String` type in schema.js

When following the [Amplify DataStore – Simplify Development of Offline Apps with GraphQL](https://aws.amazon.com/blogs/aws/amplify-datastore-simplify-development-of-offline-apps-with-graphql/) blog post, I noticed that the `/graphql` API resource was not returning the `title` property, resulting in odd UI behavior:

![no_title](https://user-images.githubusercontent.com/42149384/70378905-23750f00-18db-11ea-8559-96b10c1ab78c.gif)

The root of the issue seems to be that `amplify codegen model` (or `npm run amplify-modelgen`) generates `string` instead of `String` `type` for the `title` property in `/src/models/schema.js`

<img width="207" alt="Screen Shot 2019-12-07 at 10 30 56 AM" src="https://user-images.githubusercontent.com/42149384/70379030-b6fb0f80-18dc-11ea-81ba-83592892e4e3.png">

When updating the `type` to `String`, the demo app from the blog post works as expected.

**Amplify CLI Version**
4.5.0

**To Reproduce**
Follow the directions specified on [this blog](https://aws.amazon.com/blogs/aws/amplify-datastore-simplify-development-of-offline-apps-with-graphql/) or @sebsto's [abbreviated instructions](https://github.com/sebsto/amplify-datastore-js-e2e)

**Expected behavior**
The `amplify codegen model` command should generate schema.js where the `String` data type is properly cased, where the `S` is capitalized.

**Desktop (please complete the following information):**
 - OS: Amazon Linux. Cloud9 Cloud9Default AMI. ami-0433265c8b987b1a0
 - Node Version: v10.17.0

**Comment by sebsto** [comment]
@nikhname tahnks for addressing this quickly.  Do you know in what version the fix will be available ?

**Comment by undefobj** [comment]
@sebsto @jordan-patapoff this has now been released to npm
