### ISSUE TITLE
Codegen: Arguments in Result Fields Support

### ISSUE THREAD

**Issue by arvinkx** [aws-amplify/amplify-cli#295]
This issue is a continuation of #264 

The generation of the graphql files seem to complete now but the validation fails with the error `Validation of GraphQL query document failed`. I believe the issue is related to the warnings in the original error message about "limit" not being provided (example: `.../graphql/queries.graphql: Field "videos" argument "limit" of type "Int!" is required but not provided.`). 

I've included a snippet of the schema below, it looks like the generation isn't adding the extra arguments (limit and nextToken) for the fields: posts, videos, stories, etc. Are arguments in result fields not supported?

Actual Schema that the mutation returns
```
type User {
    username: String!
    preferred_username: String!
    picture: String!
    email: String!
    name: String!
    family_name: String!
    posts(limit: Int!, nextToken: String): PostConnection
    videos(limit: Int!, nextToken: String): VideoConnection
    stories(limit: Int!, nextToken: String): StoryConnection
    podcasts(limit: Int!, nextToken: String): PodcastConnection
    notifications: NotificationConnection
    followerCount: Int!
    followingCount: Int!
    followerIds: [String!]!
    followingIds: [String!]!
    followingTags: [String!]
}
```
What's being generated (this mutation returns a User but the field `posts`, for example, should have the arguments, limit and nextToken):
```
mutation UpdateFollowingTags($tags: String!) {
  updateFollowingTags(tags: $tags) {
    username
    preferred_username
    picture
    email
    name
    family_name
    posts {
      items {
        id
        date
        updatedAt
        title
        authorId
        content
        likesCount
        video
        isLiked
      }
      nextToken
    }
    videos {
      items {
        id
        authorId
        date
        viewCount
        category
        upvotesCount
        upvotes
        downvotesCount
        downvotes
        title
        alternativeTitle
        thumbnailUrl
        alternativeThumbnailUrl
        description
        videoUrl
        videoLength
        tags
      }
      nextToken
    }
    stories {
      items {
        id
        date
        authorId
        image
        video
      }
      nextToken
    }
    podcasts {
      items {
        id
        date
        updatedAt
        url
        authorId
        description
        likesCount
        isLiked
      }
      nextToken
    }
    notifications {
      items {
        userId
        notificationId
        date
        likes
        newLikesCount
        followers
        newFollowersCount
      }
    }
    followerCount
    followingCount
    followerIds
    followingIds
    followingTags
  }
}
```

**Comment by yuth** [comment]
Thanks for reporting this, in the mean time could you add the a default value for the `limit`.

**Comment by arvinkx** [comment]
@yuth Thanks, I've added default values and got passed that issue but it seems there is an issue with using non-null arrays in arguments as well. The places I have `$tags: [String!]!` seem to be replaced with a single item instead of an array. I've included an example below (`$users` should be `$users: [String!]!`:
```
...
query GetUsers($users: String!) {
  getUsers(users: $users) {
...
```
