### ISSUE TITLE
Deploying app using latest amplify cli (4.5.0) gives authentication errors in client app 

### ISSUE THREAD

**Issue by GodbayPlanet** [aws-amplify/amplify-cli#2951]
**Describe the bug**
After upgrade of amplify cli from 3.15.0 to 4.5.0 version client app gives authentication errors.

I have the following model 
```
type Project
  @model(subscriptions: { onUpdate: ["onUpdateProject"] })
  @auth(
    rules: [
      {
        allow: private
        provider: userPools
        operations: [read, create, update, delete]
      }
      { allow: public, provider: iam, operations: [read, update] }
    ]
  ) {
  id: ID!
  title: String!
  category: String!
  donationTarget: Int!
  ...
}
```
I have two authentication types, `userPools` and  `IAM`, where `userPools` is default one(I specified it when adding api using amplify cli) and IAM is additional authentication type.

In Amplify Console under the `Build Settings` there is `Live package updates` section where I can specify what version of Amplify CLI I want and if I don't specify anything it will use the latest version of amplify cli. 
The result of using the latest version of amplify cli will be that the app uses IAM as default authentication type which is different from one that I have specified in the code.

Also if I log result from Amplify.configure(awsconfig) I can see that 
`"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"` is missing which is not the case when I deploy app with 3.15.0 version.

If I specify Amplify CLI version 3.15.0 everything works as expected.

I tried to update my `api` and `auth` with 4.5.0 version but that didn't make any difference.

What I am missing here, why `"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"` is missing when I deploy app with 4.5.0 version?

**Expected behavior**
`"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"` should not be missing when deploying app with Amplify cli 4.5.0 version.

**Comment by GodbayPlanet** [comment]
Workaround to this is to go to `Build settings` and under `Live package updates` add `Amplify CLI` 4.5.0 version. 
It's really weird because the latest version of amplify cli is 4.5.0 and if you don't explicitly specify version in Build settings it will somehow not include aws_appsync_authenticationType in Amplify configure.

**Comment by attilah** [comment]
@GodbayPlanet when there is no version specified, that does not mean the latest version of the CLI will be used. You've to specify 'latest' or a specific version, see the docs here: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates.
