### ISSUE TITLE
"npx amplify-app" fail on Windows

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#2955]
I'm trying to follow the instructions in https://github.com/sebsto/amplify-datastore-js-e2e -but running into npx issues.

I'm running these versions on a Windows 10 pc
-> Node - 10.16.3
-> NPM - 6.9.0
-> Amplify CLI - 4.5.0

I follow the steps without issue until I get to "npx amplify-app" and I get this message:

npx: installed 103 in 33.207s
😟 Amplify CLI version >=4.0.0 not found.
😅 Installing Amplify CLI. Hold tight.
spawn npm ENOENT

As I said, before I run this I confirm I have 4.5.0 installed (amplify -v), but the npx amplify-app is not seeing that and failing.

**Comment by sacrampton** [comment]
For what its worth, in following the instructions in the blog article the following npx command works

"npx create-react-app amplify-datastore --use-npm"

But the following npm command does NOT work

"npm run amplify-modelgen"

I use amplify codegen models to get the models compiled.

**Comment by kaustavghosh06** [comment]
The fix for this is merged in #3100. This would be available in the next CLI release (v4.12)
