### ISSUE TITLE
There are missing attributes when I am using Amplify DataStore. How do I get all attributes of the data via AWS data store?

### ISSUE THREAD

**Issue by ykbryan** [aws-amplify/amplify-cli#2958]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify Data Store

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.5.0

**What AWS Services are you utilizing?**
AWS AppSync

**Provide additional details e.g. code snippets**

I am unable to get other attributes (not all). Refer to the screenshot below and note that I have missing attributes `title` and `description`. How do I `query` properly?

```
  async function listPosts() {
    const posts = await DataStore.query(Post, Predicates.ALL);
    console.log(posts);
  }
```

![Screenshot 2019-12-10 07 50 31](https://user-images.githubusercontent.com/1001146/70482922-ebabd880-1b21-11ea-856a-d1df6291e55a.png)

**Comment by manueliglesias** [comment]
Hi @ykbryan 

Did you modify your schema to add/remove fields? If so,  did you run `npm run amplify-modelgen` and `npm run amplify-push` after doing it?

**Comment by ykbryan** [comment]
> Hi @ykbryan
> 
> Did you modify your schema to add/remove fields? If so, did you run `npm run amplify-modelgen` and `npm run amplify-push` after doing it?

yes, i did `npm run amplify-modelgen` and `npm run amplify-push`. (many times, in fact)
the schema is updated, models/schema.js also has the attributes.

**Comment by ykbryan** [comment]
Updates: I can add another field with type `Int` but not with type `String`. Any clue why? @manueliglesias 

![Screenshot 2019-12-10 11 14 21](https://user-images.githubusercontent.com/1001146/70492094-3e938900-1b3e-11ea-87e2-061873a6019f.png)

**Comment by ykbryan** [comment]
![Screenshot 2019-12-10 11 27 15](https://user-images.githubusercontent.com/1001146/70492632-0725dc00-1b40-11ea-842d-306631f1a732.png)

I found it. The schema.js generated via codegen for models is giving `string` instead of `String` for its type. Is this a bug?

**Comment by undefobj** [comment]
@ykbryan I think this issue is what you're running into: https://github.com/aws-amplify/amplify-cli/pull/2947
We merged a fix of this yesterday but the release is having a bit of trouble. Trying to get it out tonight stay tuned.

**Comment by ykbryan** [comment]
> @ykbryan I think this issue is what you're running into: #2947
> We merged a fix of this yesterday but the release is having a bit of trouble. Trying to get it out tonight stay tuned.

Ooo.. i was looking for `METADATA_SCALAR_MAP` earlier. :) Good to know!

**Comment by undefobj** [comment]
@ykbryan the new CLI has been released to npm and this should now be resolved. Please let us know if you're still having trouble.

**Comment by ykbryan** [comment]
@undefobj I re-ran `npx amplify-app` and `npm run amplify-modelgen`, it didn't work. \
And i removed the node_modules, and re-ran the 2 commands again, it still didn't work. 
The amplify version I am in is **4.6**

**Comment by undefobj** [comment]
Is the string still showing a lowercase "s"?

**Comment by ykbryan** [comment]
> Is the string still showing a lowercase "s"?

yes, do i miss any step/ anything?

**Comment by undefobj** [comment]
A couple other customer reported they're not having this issue on 4.6. Can you run an `amplify -v` and confirm, then re-run model generation again and look at the schema.js file again to confirm?

**Comment by ykbryan** [comment]
Just did `amplify version` and it is **4.6**

here's what i did:
```
create-react-app newapp
npx amplify-app
npm run amplify-modelgen
```

And I still see the lowercase `string`.

**Comment by manueliglesias** [comment]
Hi @ykbryan 

Can you try using `@latest` when running the npx script?

```sh
create-react-app newdatastore
npx amplify-app@latest
npm run amplify-modelgen
```

**Comment by ykbryan** [comment]
> Hi @ykbryan
> 
> Can you try using `@latest` when running the npx script?
> 
> ```shell
> create-react-app newdatastore
> npx amplify-app@latest
> npm run amplify-modelgen
> ```

Just just did. Still facing lowercase `string` error in **modelgen**

**Comment by undefobj** [comment]
@ykbryan I think there could be an issue with your local npm setup. I've just tried this again locally as have several customers and they don't have the issue. Can you try globally uninstalling the CLI, as well as removing any references in your `/usr/local/bin/` directory (run `which amplify` to see where it's being invoked from).

**Comment by ykbryan** [comment]
@undefobj @manueliglesias 
When i run `which amplify`, it is still pointing to the old amplify version in the `~/.nvm` instead of the one at `/usr/local/bin`.

I've also cleared all `node_modules`, re-run the  commands to test again & it works.
```
create-react-app testapp
npx amplify-app
npm run amplify-modelgen
```
