### ISSUE TITLE
GraphQL Private Object with 2 Public Fields

### ISSUE THREAD

**Issue by Jupdi** [aws-amplify/amplify-cli#2962]
**Which Category is your question related to?**
API/ GraphQL Schema
**Amplify CLI Version** 
3.15.0
**What AWS Services are you utilizing?**
API
**Provide additional details e.g. code snippets**
Hi,
i have a model with around 20 fields. Two of these fields should be accessible for every registered user ({allow: private, operations: [read]}). All other fields should be readable by a group of users added to the model ({ allow: owner, ownerField: "myOwnerfield", operations:[read]}). All other opertations should only be accessible to the owner({allow: owner}).
The way i got it working was this:
```gql
type myModel
  @model
  @auth(rules:[
      {allow: private, operations: [read]}
      {allow: owner}
    ])
{
  id: ID
  field1: String
  field2: String @auth(rules: [{ allow: owner, ownerField: "myOwnerfield" operations:[read]}{allow: owner}])
  field3: String @auth(rules: [{ allow: owner, ownerField: "myOwnerfield" operations:[read]}{allow: owner}])
  field4: AWSDate @auth(rules: [{ allow: owner, ownerField: "myOwnerfield" operations:[read]}{allow: owner}])
  field5: String @auth(rules: [{ allow: owner, ownerField: "myOwnerfield" operations:[read]}{allow: owner}])
  ...
}

```
But if i add the rules to all the fields im getting an error "Invalid request template given, must be less than 64kb in size"  same as here : [https://github.com/aws-amplify/amplify-cli/issues/2698](https://github.com/aws-amplify/amplify-cli/issues/2698)

So i tried mit minimize the size of the auth, but that didn't work. No i don't have any private access.

```gql
type myModel
  @model
  @auth(rules:[
      {allow: owner}
      { allow: owner, ownerField: "myOwnerfield", operations:[read]}
    ])
{
  id: ID @auth(rules:[{allow: private, operations: [read]}])
  field1: String @auth(rules:[{allow: private, operations: [read]}])
  field2: String
  field3: String
  field4: AWSDate
  field5: String
  ...
}

```
Another solution i did come up with was moving all the private fields into another model, but that brings with it other problems. 
Is there any way to get this to work in an easy manner?

Thanks in advance

**Comment by SwaySway** [comment]
Hello @Jupdi we are looking a little further into making some improvements on field level @auth to make it more straightforward as a part of our roadmap. While is not immediately possible with one type of authorization one way you can publicly query on two fields is by using multi-auth.

In the example below you can use IAM auth to allow unauthenticated users (in this case public) to query on id and field1. While the other fields have aws cognito rules (defined in the type) are enforced on the other fields.

```graphql
type myModel
  @model
  @auth(rules:[
	{ allow: owner, ownerField: "ownerField", operations:[read] }
	{ allow: owner }
]){
	id: ID @auth(rules: [
			{ allow: public, operations: [read], provider: iam } 
		]) @aws_cognito_user_pools
	field1: String @auth(rules: [
			{ allow: public, operations: [read], provider: iam } 
		]) @aws_cognito_user_pools
	field2: String @aws_cognito_user_pools
	field3: String @aws_cognito_user_pools
	field4: AWSDate @aws_cognito_user_pools
	field5: String @aws_cognito_user_pools
	ownerField: String @aws_cognito_user_pools
	owner: String @aws_cognito_user_pools
}
```

**Comment by kaustavghosh06** [comment]
Closing this issue. If you're still stuck on this please feel free to comment on this thread.
