### ISSUE TITLE
Old CLI version in Amplify Console

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#2966]
Trying to deploy and we're erroring on:

````
Unknown argument "keyName" on directive "@connection". Did you mean "name"?
````

**Comment by swaminator** [comment]
@CodySwannGT set the version to the 'latest' in the live updates section of the Amplify Console: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

**Comment by CodySwannGT** [comment]
Much obliged!
