### ISSUE TITLE
S3 User Uploads Bucket created by amplify does not accept large files

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#297]
**Describe the bug**
Can't upload large files to the user uploads bucket that amplify generates without modifying CORS configuration. To fix, the CORSConfiguration of the S3 bucket needs to include     `<ExposeHeader>ETag</ExposeHeader>`. See https://github.com/aws/aws-sdk-js/issues/191

**To Reproduce**
- amplify add storage
- go through instructions to create user uploads s3 bucket
- Use appsync to upload the files

**Expected behavior**
- Any file uploaded successfully regardless of size (file I was uploading was 9mb)

**Screenshots**
With the default CORS configuration, GraphQL will fail with error of 'No access to ETag property on response. Check CORS configuration to expose ETag header.'

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by elorzafe** [comment]
That issue was fixed with PR #579
