### ISSUE TITLE
Should Lambda Function Cloudformation Templates be in version control?

### ISSUE THREAD

**Issue by imgntn** [aws-amplify/amplify-cli#2973]
**Which Category is your question related to?**
Workflows, version control, lambda

**Amplify CLI Version** 
4.6.0

**What AWS Services are you utilizing?**

Lambda Functions

I have `master` and `dev` git branches, as well as `production` and `test` amplify environments.

Any time i `amplify push` it writes change to the cloudformation template file for all lambda functions at `/amplify/backend/function/functionName/functionName-cloudformation-template.json`

This requires another git commit and is just pretty confusing to me.   then if merge dev into master, those templates have the `test` environment lambda cloudformation templates.

is it safe to add these cloudformation templates to the gitignore?  

should amplify push be writing changes locally?  should i wait until after the amplify push to commit?  

here's the steps i'm doing :)

-----------------------------------

```
init amplify (environment name: production)
amplify function add
amplify push
* note that function cloudformation template changes (and added a package lock file)

$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   amplify/backend/function/gamewriting944f3c98/gamewriting944f3c98-cloudformation-template.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        amplify/backend/function/gamewriting944f3c98/src/package-lock.json


? do i commit the template changes and add the package lock at this point?


git add --all
git commit -a -m 'post amplify push #1'
git checkout -b dev 
amplify add env test
amplify push

*  note more changes to cloudformation template

On branch dev
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   amplify/backend/function/gamewriting944f3c98/gamewriting944f3c98-cloudformation-template.json

no changes added to commit (use "git add" and/or "git commit -a")


git commit -'post amplify push #2'

git checkout master
git merge dev

amplify env checkout production

$ amplify status

Current Environment: production

| Category | Resource name       | Operation | Provider plugin   |
| -------- | ------------------- | --------- | ----------------- |
| Function | gamewriting944f3c98 | Update    | awscloudformation |
| Auth     | gamewriting1dc137f5 | No Change | awscloudformation |


amplify push

*note update to cloudformation file


...etc.


have i gotten something wrong?  should 
`amplify/backend/function/*/*-cloudformation-template.json` be in the gitignore so that file never gets added in the first place?  seems like it gets generated by amplify push


$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   amplify/backend/function/gamewriting944f3c98/gamewriting944f3c98-cloudformation-template.json
        modified:   amplify/team-provider-info.json

no changes added to commit (use "git add" and/or "git commit -a")```

**Comment by kaustavghosh06** [comment]
@imgntn The S3 Key in the Lambda Cloudformation template is generated dynamically based on the hash of the `'src/` directory for Cloudformation to know that there is a change in your source code and hence trigger a build - otherwise it won't trigger a build. 

Having said that if you don't intend to modify your lambda Cloudformation or add any environment variables to it via the `amplify update function` functionality, then it's safe to keep it in gitignore to avoid conflicts.

**Comment by imgntn** [comment]
thanks for the clarification!

**Comment by teezeit** [comment]
Hi @kaustavghosh06. In my case I need to modify the lambda Cloudformation (add permissons, eg. `"cognito-idp:AdminCreateUser"`).

What is the procedure?

Should this file not be independent of the amplify environment, like all other `xxx-cloudformation-template` files?

**Comment by avlonder** [comment]
I use lambda functions with custom Timeout, MemorySize, environment variables, ... 
What should I do? Every time I go to one of my branches (dev, test, prod), the bucketname changes.
