### ISSUE TITLE
Excluding "devDependencies" in Lambda Function's built version

### ISSUE THREAD

**Issue by BardiaN** [aws-amplify/amplify-cli#2976]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

`amplify push` command

**Amplify CLI Version** 

4.5.0

**What AWS Services are you utilizing?**

AWS Lambda Function, AWS Lambda Layer

**Provide additional details e.g. code snippets**

I'm using AWS Lambda Layer in my projects and I'm handling the deployment part manually and only include it in the Lambda CloudFormation file under the "Layers" section and it works fine. However, because I moved my dependencies to my layer, I have also moved them to "devDependencies" in Lambda's package.json. Why? Because I have tests inside the `src` folder of my lambda functions and in order to run those tests I need my packages to be around.

The problem is that I noticed my lambda size is still too big and when I checked, amplify is installing my "devDependencies" and it's basically doubling the total size because of the layer I have.
Finally, my question: 
** isn't amplify supposed to install npm packages with `--production` flag? If not, how I can set it to do so?**

I'd really appreciate any input or thoughts.

_P.S. I checked and same thing is happening in Amplify Console Build and it makes sense because it's using the same command `amplify push --simple`_

**Comment by BardiaN** [comment]
Just to give you an update, I've also taken a look into the amplify-function-plugin and tried to manipulate "amplify:build" & "amplify:push" in my own function's script to create a production build, but no success in that. I know these parts are pretty new, but some documentation would be really appreciated for these scripts and how to use them. 
The only part of document that I found related to this topic was in aws-amplify website regarding the "amplify:generateReport".
Anyway, if you guys think I can contribute in any way, just let me know, I'd be happy to work on a fix for this problem.

**Comment by foxfl** [comment]
One workaround could be to create an additional package.json in the root folder of your function (above /src) which only holds your dev dependencies and also to add your test files to the root folder, as the deployment package is built upon the /src folder

**Comment by BardiaN** [comment]
> One workaround could be to create an additional package.json in the root folder of your function (above /src) which only holds your dev dependencies and also to add your test files to the root folder, as the deployment package is built upon the /src folder

Hey @foxfl,
Thank you for your comment. It seems like a good solution to me. I'll try it and post the result in this issue.

**Comment by BardiaN** [comment]
> One workaround could be to create an additional package.json in the root folder of your function (above /src) which only holds your dev dependencies and also to add your test files to the root folder, as the deployment package is built upon the /src folder

Worked like a charm for me. I'm gonna close this issue. Thanks again @foxfl
