### ISSUE TITLE
is it necessary to do sanitization of user input? and when?

### ISSUE THREAD

**Issue by monaye** [aws-amplify/amplify-cli#2978]
I am new to nosql. When I looking at the generated resolver, none of the user input is sanitized. 
When I search google for a "NoSQL injection", some results came back, but all of the articles are not clear enough. 
When I open the AWS support ticket, they said : 

> I understand you are trying to utilise resolver mapping templates to sanitise inputs to prevent nosql injection. Please let me know if my understanding is incorrect.

> Currently, AppSync hasn’t a feature to automatically identify, mitigate or avoid SQL injections. As you may know, the only means that we have now is sanitise the inputs via regex or use procedure and parameterised inputs.  Please see the documentation [1] for a few examples and suggestions to sanitise inputs. 
As it shows you can use regex expressions to fine-tune the inputs. However this is a limited data massaging technique and does not really ensure prevention nosql injection. 

> You may use Lambda resolver as a proxy to detect any injection to DyanmoDB but that does add a layer of complexity, cost and possibly latency. It does sound like a good adition to the service therefore I have gone ahead and created a feature request on your behalf to the AppSync team on your behalf for AppSync built-in NoSQL injection detection.   However, we are not able to provide you an ETA or ensure that this feature will be implemented.

> [1] Tutorial: Aurora Serverless  - Input Sanitization - https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html#input-sanitization 

Since the link support team provide is for the RDS, it really doesn't answer my question. 
Is it necessary to do sanitization of the user input? if so when?

**Comment by kaustavghosh06** [comment]
@monaye What sort of input sanitization are you looking for?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of user response. Please feel free to comment on this if you're still stuck with this issue and we'll re-open this issue.
