### ISSUE TITLE
API: @Connection with @Auth returns null

### ISSUE THREAD

**Issue by Jupdi** [aws-amplify/amplify-cli#2981]
I have an field level auth on a Connection, that always returns null.
Removing the auth lets me get all data. Using a wrong auth returns me an auth error, but with the correct user i neither get the data nor an error.
The auth on the users field works perfectly.

Here is my Code:

```gql
type MyModel
  @model
  @auth(rules:[
      {allow: private, operations: [read]}
      {allow: owner, operations: [update,delete]}
    ])
{
  fieldl1: ID!
  fieldl2: String
  users: [String] @auth(rules: [{ allow: owner, ownerField: "users"}, {allow: owner}])
  modelData: MyModelData
    @connection(name:"MyModelMyModelData")
    @auth(rules: [{ allow: owner, ownerField: "users"}, {allow: owner}])
}

type MyModelData
@model(queries: null)
@auth(rules:[
    {allow: private, operations: [read]}
    {allow: owner, operations: [update,delete]}
  ])
{
  fieldl1: ID!
  fieldl2: AWSDate
  fieldl3: String
  fieldl3: Int
  myModel: MyModel @connection(name: "MyModelMyModelData")
}

```

**Comment by edwardfoyle** [comment]
@Jupdi This does appear to be a bug. While we investigate a fix, can you see if adding an `owner: String` field to both of your models solves the problem?

**Comment by edwardfoyle** [comment]
We have updated our documentation to include instructions on how to handle this case: https://aws-amplify.github.io/docs/cli-toolchain/graphql#owner-authorization

We are still working on a more intuitive long-term solution but for now you should specify 'create' permissions in your owner auth rule to ensure that an owner is always stored with the record. If you only want certain roles to be able to create entities, but want owners to perform other operations, then you will need to ensure that when those other roles create the entity that they specify an owner for it.
