### ISSUE TITLE
Amplify mock ignore .eslintrc file

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#2990]
**Is your feature request related to a problem? Please describe.**
I placed and .eslintrc file in `amplify/backend/function` to customize the errors for node. `amplify mock` is trying to parse this file.

**Describe the solution you'd like**
ignore .eslintrc files

**Describe alternatives you've considered**
moving the file into the dir with each function. 

**Additional context**
error message: 
```
Failed to parse Lambda function cloudformation in [...]/amplify/backend/function/.eslintrc/.eslintrc-cloudformation-template.json

Error: ENOTDIR: not a directory, open '[...]/amplify/backend/function/.eslintrc/.eslintrc-cloudformation-template.json'
Failed to parse Lambda function cloudformation in [...]/amplify/backend/function/[...]PostConfirmation/[...]PostConfirmation-cloudformation-template.json

Error: Could not find ref for "GROUP"
```

**Comment by siegerts** [comment]
Closing as this doesn't seem break the `mock` capability anymore given the steps below:

```
amplify add function
```

```
? Select which capability you want to add: Lambda function (serverless function)


? Provide an AWS Lambda function name: restgraphql00abcdeb
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource restgraphql00abcdeb locally
``` 

- Add `.eslintrc.js` to `/function/restgraphql00abcdeb` directory -> `amplify mock function restgraphql00abcdeb` runs as expected

- Add `/.eslintrc/.eslintrc-cloudformation-template.json` to `/function/restgraphql00abcdeb` directory -> `amplify mock function restgraphql00abcdeb` runs as expected
