### ISSUE TITLE
Provide a helper to allow 3rd party plugins to add to the exports file

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#2991]
**Is your feature request related to a problem? Please describe.**
Currently today the frontend plugins hard code support for what values are imported and appending to the file can be dangerous as you don't know when the generation can happen.

**Describe the solution you'd like**
Provide either a new field in the `amplify-plugin.json` that includes if you want to export to the exports folder or not. Or provide a function that is called by all frontend plugins to get all values that the category plugins want to output and append them to the output in the respective dictionary. 

**Describe alternatives you've considered**
Pull request to support my plugin, but this isn't scalable

**Additional context**

**Comment by josefaidt** [comment]
Closing as a `wontfix` in favor of not granting third party plugins the ability to modify the `aws-exports.js` file that is shipped with your client code.
