### ISSUE TITLE
Setting up Cognito infrastructure - to use Amplify or not to use 

### ISSUE THREAD

**Issue by NTonani** [aws-amplify/amplify-cli#2993]
_**Create Cognito infra through Amplify or separately create and manage CF templates?**_ 

I understand Amplify provides a way to setup and deploy a User Pool through the CLI, but it seems to create a soft dependency between the app in which Amplify is being used for and the backend infra (the CF templates are created in the frontend app dir, changes must be made through it).

We have an immediate use case for Cognito User Pool authn, and while the use case is against a React app, the pool will be leveraged by other clients in the future, as well extended into Identity Pools for authz. I am concerned that taking advantage of Amplify comes at a cost (full disclosure I have barely touched its surface so not sure what the full cost is). However, if we don't create the infra through Amplify, it seems connecting an external Cognito User Pool isn't fully supported (workarounds mentioned here https://github.com/aws-amplify/amplify-cli/issues/779) - which we'll need to do no matter what as we have multiple apps that will want to use it. 

Just looking for some suggestions for managing and deploying infra - seems there are tradeoffs either way.

**Comment by NTonani** [comment]
Perhaps best practices are documented somewhere that I'm not able to find?

**Comment by kaustavghosh06** [comment]
@NTonani It seems like you want to use the same AWS resources accross multiple frontend apps. We have documents this use case out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends

**Comment by NTonani** [comment]
Yes that is a helpful guide once committing to using Amplify for managing infrastructure. Is that currently the preferred method, over managing it independently? 

I'm mainly concerned with the coupling between the app and the backend infra it seems to force. Take, for example, managing infra for multiple apps (app1, app2, app3) within app1. Suppose app2 has a use case which requires extending the infra. Now, per best practices (backend definition residing in initial app - app1), and maintaining a single source of truth, app1 must be involved. Hence the coupling. 

Managing independently would resolve this, however I have read that Amplify support becomes inconsistent when connecting pre-existing infra. Is there a doc on such tradeoffs - managing infra for multiple apps in Amplify vs not? If not, it would be beneficial. Thanks.

**Comment by NTonani** [comment]
Ah - seems we can manage a separate repository for Amplify. At least it decouples the apps. Will move forward with this.

**Comment by kaustavghosh06** [comment]
@NTonani Cool! Let us know if you are stuck with any other issues.

**Comment by NTonani** [comment]
@kaustavghosh06 After creating an Amplify app in a new repo, multiple envs, and pushing infra, I tried connecting my first frontend and when I ran `amplify pull` I got the following:

> No Amplify apps found. Please ensure your local profile matches the AWS account or region in which the Amplify app exists.
Failed to pull the backend.

This lead me to manually attach my repo to a new Amplify Console app, though it links it as the frontend and not backend. Even still, after reading [Amplify Console now provides visibility into backend environments provisioned by the Amplify CLI](https://aws.amazon.com/about-aws/whats-new/2019/11/amplify-console-now-provides-visibility-into-backend-environments-provisioned-by-the-amplify-cli/) I presumed I wouldn't have to do that at all! Article states:

> When you initialize a project with the Amplify CLI, the Amplify Console creates an app project that provides a list of backend environments

Not sure if there has since been a rollback of the feature, but `amplify console` brings me back to the create page, indicating no app was setup when I initialized my repo. 

How can I best setup an Amplify app with my backend repo? Thanks!

**Comment by kaustavghosh06** [comment]
@NTonani Did you deploy the AWS resources with 4.6.0 as well?

**Comment by NTonani** [comment]
@kaustavghosh06 Just checked that as well. I believe what happened is I updated when `amplify pull` failed, but earlier provisioned resources with <4.0... 

Is there a way to retroactively create/assign an app? Or do I need to teardown?

**Comment by NTonani** [comment]
I ended up deleting and starting over as I wasn't far in. I will note the [quickstart#workflow](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#workflow) guide will not work as mentioned if frontends are not sharing a directory unless Amplify version is >=4.0. Might be worth mentioning there.

Thanks for the help.
