### ISSUE TITLE
Update Node runtime to "nodejs10.x"

### ISSUE THREAD

**Issue by yuyokk** [aws-amplify/amplify-cli#2999]
Team,

Got the following email from AWS

> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 8.10, which will reach its EOL at the end of 2019.

> What’s happening?

> The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].

> For Node.js 8.x, there will be 2 stages to the runtime deprecation process:

> 1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10

> 2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10

> After this period, both function creation and updates will be disabled permanently. However, existing Node 8.x functions will still be available to process invocation events.

Will you please update Node runtime to v10 for amplify project resources by default?

Thanks

**Comment by yuyokk** [comment]
Also question - how to update runtime for the following lambdas

![Screenshot 2019-12-14 11 48 31](https://user-images.githubusercontent.com/1225343/70847705-c1328600-1e67-11ea-89e4-86c31a64dca1.png)

I updated all runtimes to "node10.x" locally for the project, pushed changes but these lambdas still use 8.

**Comment by UnleashedMind** [comment]
@yuyokk 
We are in the process of updating the nodejs versions in lambda backed custom resources.

**Comment by kaustavghosh06** [comment]
Hello, we released a new version of the Amplify CLI (v4.9+), which automatically updates your Cloudformation files to use Node 10.x runtime for your Lambda functions.
Please take a look at https://aws-amplify.github.io/docs/cli/lambda-node-version-update for documentation around this and feel free to comment on this thread or open up an issue if have issues with this migration.
