### ISSUE TITLE
Filters not generated for non-scalar model type fields

### ISSUE THREAD

**Issue by brianhilst** [aws-amplify/amplify-cli#300]
**Describe the bug**
I have a type with field that is a non-scalar type field and the generated filter for the type doesn't allow filtering by the non-scalar field.  In the schema.graphql example below, type Profile has a category: Category @connection field, but the generated ModelProfileFilterInput doesn't include a filter by Category.

**To Reproduce**
1. Create a type Profile and another type Category.  
2. Add category: Category @connection member to Profile. See attached schema.
3. amplify push and note that the generated ModelProfileFilterInput in schema.graphql doesn't include a filter by Category.  See below for the generated ModelProfleFilterInput type.

**Expected behavior**
ModelProfileFilterInput should contain a way to filter on the Category (e.g. profileCategoryId: ModelIDFilterInput).

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Original schema.graphql**
```
type Customer @model 
{
	id: ID!
	owner: String!
	active: Boolean!
	email: AWSEmail!
	firstName: String!
	lastName: String!
	addressLine1: String
	addressLine2: String
	addressCity: String
	addressState: String
	addressPostalCode: String
	addressCountry: String
	phone: AWSPhone
	latitude: String
	longitude: String
	joinDate: AWSDate!
	deleteDate: AWSDate
}

type Provider @model 
{
	id: ID!
	owner: String!
	active: Boolean!
	email: AWSEmail!
	firstName: String!
	lastName: String!
	addressLine1: String
	addressLine2: String
	addressCity: String
	addressState: String
	addressPostalCode: String
	addressCountry: String
	phone: AWSPhone
	latitude: String
	longitude: String
	joinDate: AWSDate!
	deleteDate: AWSDate
	promotionalHours: Int
	purchasedHours: Int
	cheated: Boolean
	profiles: [Profile] @connection(name: "ProviderProfiles")
}

type Category @model {
	id: ID!
	name: String!
	active: Boolean!
	group: CategoryGroup #@connection(name: "GroupCategories") 
}

type CategoryGroup @model {
	id: ID!
	name: String!
	categories: [Category] #@connection(name: "GroupCategories")
}

type Profile @model 
{
	id: ID!
	owner: String!
	active: Boolean!
	biography: String!
	category: Category @connection
	clicked: Boolean!
	hourlyRate: Float
	light: LightStatus
	lighted: AWSDateTime
	lightActivated: AWSDateTime
	provider: Provider @connection(name: "ProviderProfiles")
}

enum LightStatus {
	off
	inactive
	active
}
```

**Generated schema.graphql**

Here is a subset of the generated schema.  Note there is no way to filter a Profile by Category.
```
type Query {
  ...
  listProfiles(filter: ModelProfileFilterInput, limit: Int, nextToken: String): ModelProfileConnection
}

input ModelProfileFilterInput {
  id: ModelIDFilterInput
  owner: ModelStringFilterInput
  active: ModelBooleanFilterInput
  biography: ModelStringFilterInput
  clicked: ModelBooleanFilterInput
  hourlyRate: ModelFloatFilterInput
  lighted: ModelStringFilterInput
  lightActivated: ModelStringFilterInput
  and: [ModelProfileFilterInput]
  or: [ModelProfileFilterInput]
  not: ModelProfileFilterInput
}
```

**Comment by ChrisWun** [comment]
I have the same problem. 
Interestingly, the mutations have a corresponding field, exactly what I miss in the FilterInputs.
For Example:
```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```

Results in
```
input CreateCommentInput {
  content: String
  commentPostId: ID
}

input ModelCommentFilterInput {
  id: ModelIDFilterInput
  content: ModelStringFilterInput
  and: [ModelCommentFilterInput]
  or: [ModelCommentFilterInput]
  not: ModelCommentFilterInput
}
```
I miss the field commentPostId in ModelCommentFilterInput.

Are there any workarounds?

**Comment by mikeparisstuff** [comment]
@ChrisWun and @brianhilst Thank you for bringing up. This does look like a missing feature. I will make a note of this and will report back when this use case has been accounted for.

**Comment by brianhilst** [comment]
The work-around listed above doesn't work.  While adding the keyField param does give control over the keyField name, it doesn't add it to the filters.  If you add it manually as shown above for postId: ID!, you end up with the field listed twice in the generated files which won't deploy without an error.

**Comment by ChrisWun** [comment]
@mikeparisstuff Thanks for the workaround. It works for me.
@brianhilst What does your updated schema look like?

**Comment by mikeparisstuff** [comment]
@brianhilst Were you able to make this work?

**Comment by ChrisWun** [comment]
Unfortunately, I found out that also enums are not generated in the FilterInputs.
Is there a workaround to Filter by enum-Values?

**Comment by hisham** [comment]
+1. Just ran into a case where I needed to filter based on enum. I guess I will do the filtering on the client side for now.

**Comment by rohit3d2003** [comment]
I also ran into a similar problem where-in one of my model class has and Id and two 'String' properties. The generated filter input only has 'Id' field while the other fields are ignored. Any idea?

**Comment by mayteio** [comment]
We manually put in the filter after pushing to amplify in the appsync console. See `activityDogId` below.

```
input ModelActivityFilterInput {
	id: ModelIDFilterInput
	comment: ModelStringFilterInput
	image: ModelStringFilterInput
	data: ModelStringFilterInput
	*activityDogId: ModelIDFilterInput*
	and: [ModelActivityFilterInput]
	or: [ModelActivityFilterInput]
	not: ModelActivityFilterInput
}
```

**Comment by mwarger** [comment]
> +1. Just ran into a case where I needed to filter based on enum. I guess I will do the filtering on the client side for now.

I just tried this as well.  Have a set of enum values that I wanted to filter on (provided in a dropdown) - would love to be able to filter on these as they would just be represented as string values and typed as such.

**Comment by apertureless** [comment]
I ran into the same issue.

I have following simplified schema

```graphql
type Country @model {
  id: ID!
  name: String!
  code: String!
  tracks: [Track] @connection(name: "CountryTrack")
}

type Track @model
  id: ID!
  name: String!
  country: Country! @connection(name: "CountryTrack")
  lng: Float
  lat: Float
  length: Float
  curves: Int
  website: String
  trackImage: String
  information: String
}
```

Now I want to query all tracks in a certain country. 
On the dynamodb level this works. Because the `Track` table does have the `trackCountryId` column. So I can perform a scan operation and filter on the `trackCountryId`. However this does not work in GraphQL, because `trackCountryId` is not included in the TrackFilterInput.

I could change that in the AppSync Console, but it would get overwritten by amplify in the next push.

**Comment by mwarger** [comment]
> The fix is to instead create a filter input per DynamoDB index and then we can automatically add connection key fields without worrying about opening the possibility for a valid query that will always throw an error.

@mikeparisstuff - Just curious if there has been any progress on this or if a different solution has presented itself in the meantime?  Thank you for all you do!

**Comment by mikeparisstuff** [comment]
@mwarger Yes, filtering by enum values has been added and pushed to new version of the CLI.

@apertureless You can do the query you want like this:

```graphql
query GetTracksByCountry {
  getCountry(id: "my-country") {
    tracks {
      items {
        ... # all tracks returned here are for this country.
      }
    }
  }
}
```

You can also add the track id if you want it explicitly by adding it to your model (we leave this up to you if you want to expose the underlying id):

```graphql
type Track @model {
  id: ID!
  name: String!
  country: Country! @connection(name: "CountryTrack")

  # add this if you want to expose it. It is already in the table.
  trackCountryId: ID!
  lng: Float
  lat: Float
  length: Float
  curves: Int
  website: String
  trackImage: String
  information: String
}
```

Keep in mind that filter expressions are performed after DynamoDB reads the records from the partition. As a result, the query that I put above will be more efficient than a top level query through `listTracks` that includes a filter. Once we have custom index support you will be able to achieve a similar effect through a top level query. See https://github.com/aws-amplify/amplify-cli/issues/1062 for more details.

**Comment by kaustavghosh06** [comment]
Please feel free to re-open if you're still seeing this issue.

**Comment by sceptyk** [comment]
@mikeparisstuff It looks like filtering by enum is still missing from searchable filter. Would it be something you are planning to update as well?

**Comment by artista7** [comment]
Hey @kaustavghosh06 , this does not seem to work when we have only have one-to-one connection like:-
student {
    id: ID!
    name: String
}
resume{
  id: ID!
  title: String
  studentId: String
  student: student @connection(keyField: "studentId", sortField: "createdAt")
  createdAt: String
}

In this case - 1. resumeStudentId is used as connecting field, and also no index is created on studentId/resumeStudentId field.

Am i doing something wrong?

**Comment by rarira** [comment]
> @mikeparisstuff It looks like filtering by enum is still missing from searchable filter. Would it be something you are planning to update as well?

yes..it still doesn't work either.

**Comment by houmark** [comment]
+1 for missing @searchable filters on enum type fields.

@mikeparisstuff this seems like a really annoying limitation as enum's are often used for a status field or another field that's used for filtering client side. I'm off to converting all my enums into Strings so I can filter on... not gonna hold my breath for another basic missing feature being added.

**Comment by houmark** [comment]
@mikeparisstuff I converted to a String for my status field and now AppSync lets me use it as a filter, and to my surprise, Elastic Search already had the field indexed as text, so this did not require further migration.

It seems to me, the only thing missing here is that AppSync resolvers creates the filter field for searchable just like it does for enums without searchable (listing queries). That should not be too hard? It looks like there's just one wire that needs to be hooked in for it being possible to filter on an enum type field all the way to Elastic Search.

**Comment by houmark** [comment]
At this time, we are not really enforcing the enum fields in any way, so the only benefit we had was that GraphQL / AppSync would choke and complain if trying to add a non-existing enum value, so, for now, I can swap to using a String type field and hope for a simple quick fix that will enable us to go back to enums while keeping the possibility to filter in searchable queries.

Adding these filters fields manually in AppSync is not a valid workaround for us as this is prone to be forgotten and creates downtime while it's done (continues deployment will overwrite the Schema).

**Comment by aireater** [comment]
I was able to add my enum to my SearchableProposalFilterInput. In my schema, status is an enum. Used SearchableStringFilterInput: 

```gql
input SearchableProposalFilterInput {
  id: SearchableIDFilterInput
  [...]
  status: SearchableStringFilterInput
  and: [SearchableProposalFilterInput]
  or: [SearchableProposalFilterInput]
  not: SearchableProposalFilterInput
}
```

It works. 

Note: you have to add the searchable input types to your schema file to get rid of gql-compile errors.

**Comment by houmark** [comment]
Thanks @aireater 

Looks like a doable workaround, but this really should be added in the "core", to avoid having a redundant configuration that needs to be maintained as the schema changes.

**Comment by rarira** [comment]
> Please feel free to re-open if you're still seeing this issue.
This issue must be re-opened, because enum type is still missing from searchable filter on v1.12.0

**Comment by babu-upcomer** [comment]
@mikeparisstuff The solution you proposed is not yet compatible with `sortField` on @connection directives with a enum value. Is this being tracked on a different issue? If so can you reopen this one?

**Comment by LpmRaven** [comment]
I think I have found the right issue. I am trying to query my products, filtered by categories and subCategories. My products can have multiple categories and multiple subCategories. With my current schema below I cannot query my products and filter by categories or subcategories. The filters don't exist.

I tried to add a "categorieIds" and "subCategorieIds" to the product type but "All fields provided to an @connection must be non-null scalar or enum fields" so that simply is not possible when you have multiple categories and subCategories.

Any suggestions would be much appreciated! 

schema.graphql
```graphql
type Product @model
  @key (fields: ["globalIdColor"])
  {
  name: String!
  formattedName: String!
  slug: String!
  globalId: String!
  globalIdColor: String!
  categories: [ProductCategory!]! @connection(keyName: "categoryByProduct", fields: ["globalIdColor"])
  subCategories: [ProductSubCategory!]! @connection(keyName: "subCategoryByProduct", fields: ["globalIdColor"])
  updatedAt: AWSDateTime!
  createdAt: AWSDateTime!
}

type Category @model
  @key(fields: ["slug"])
  {
  name: String!
  formattedName: String!
  slug: String!
  products: [ProductCategory!]! @connection(keyName: "productByCategory", fields: ["slug"])
}

type SubCategory @model
  @key(fields: ["slug"])
  {
  name: String!
  formattedName: String!
  slug: String!
  products: [ProductSubCategory!]! @connection(keyName: "productBySubCategory", fields: ["slug"])
}

# join model
type ProductCategory @model(queries: null)
  @key(fields: ["productId", "categoryId"])
  @key(name: "categoryByProduct", fields: ["productId", "categoryId"])
  @key(name: "productByCategory", fields: ["categoryId", "productId"]) {
  productId: String!
  categoryId: String!
  product: Product! @connection(fields: ["productId"])
  category: Category! @connection(fields: ["categoryId"])
}

# join model
type ProductSubCategory @model(queries: null)
  @key(fields: ["productId", "subCategoryId"])
  @key(name: "subCategoryByProduct", fields: ["productId", "subCategoryId"])
  @key(name: "productBySubCategory", fields: ["subCategoryId", "productId"]) {
  productId: String!
  subCategoryId: String!
  product: Product! @connection(fields: ["productId"])
  subCategory: SubCategory! @connection(fields: ["subCategoryId"])
}
```
Here is an example of the product query.
```graphql
 const productQuery = `
    query ($nextToken: String){
        appSync {
            listProducts (
               filter: {
                       // filter by categories and subCategories
               }
               nextToken: $nextToken
            ){
                items {
                    name
                    formattedName
                    slug
                    globalId
                    globalIdColor
                    updatedAt
                    createdAt
                    categories {
                        items {
                            category {
                                name
                                formattedName
                                slug
                            }
                        }
                    }
                    subCategories {
                        items {
                            subCategory {
                                name
                                formattedName
                                slug
                            }
                        }
                    }
                }
                nextToken
            }
        }
    }`
```

**Comment by amcdnl** [comment]
Why is this closed? Seems like its still an issue...

**Comment by Niretech** [comment]
Is there an update on this? I still get this error when trying to filter by owner.

`The variables input contains a field name 'owner' that is not defined for input object type 'ModelLessonFilterInput'`
