### ISSUE TITLE
Overwriting existing resolvers does not work

### ISSUE THREAD

**Issue by c0dingarchit3ct** [aws-amplify/amplify-cli#3002]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Either this is a bug or better documentation on how to overwrite resolvers
**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.5.0

**What AWS Services are you utilizing?**
Auth & API & Lambda

**Provide additional details e.g. code snippets**
I need to overwrite the Input to a mutation resolver to add extra values to the fields (I am using a PreTokenGeneration Lambda to insert an extra group to achieve multi-tenancy).

this is my graphql
```gql
type data
  @model
  @auth(
    rules: [
      {
        allow: groups
        groups: ["Managers"]
        queries: [get, list]
        mutations: [create, update, delete]
      }
      {
        allow: groups
        groups: ["Employees", "others"]
        queries: [get, list]
        mutations: null
      }
    ]
  ) {
  id: ID!
  title: String!
  tenant: String
}
type PrivateNote @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  content: String!
}
```

I have created a _Mutation.createData.req.vtl_ file in the resolver directory and it has some extra lines to the original one

When I do Amplify Push, I see the new modified file under Amplify->build->resolvers directory

But the resolver on AppSync is never updated.

Following the advice of someone, I went through the rabbit hole of custom resolvers, very little documentation on how to do it, and after hours I got the dreadful "Two resolvers for the same field" and I gave up.

The documentation suggests placing the files in the resolver directory should work but it is not!

**Comment by Soek22** [comment]
Hello, it sounds like you are missing the "Add a resolver resource to a stack in the stacks/ directory."

I have followed this example and it is working fine for me:
https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

**Comment by Soek22** [comment]
Well, not sure if that step is necessary only for "added" resolvers, or is it also needed for overwritten ones.

**Comment by yuth** [comment]
> I need to overwrite the Input to a mutation resolver to add extra values to the fields (I am using a PreTokenGeneration Lambda to insert an extra group to achieve multi-tenancy).

Transformer has a way to specify custom claims (`identityClaim` and `groupClaim`) as documented [here](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-claims), if you just need to insert that value into the the DynamoDB table. This would keep all the auth rules you have in sync where as custom resolvers, you would make sure the auth logic gets updated when the `@auth` rules are updated.

**Comment by c0dingarchit3ct** [comment]
> > I need to overwrite the Input to a mutation resolver to add extra values to the fields (I am using a PreTokenGeneration Lambda to insert an extra group to achieve multi-tenancy).
> 
> Transformer has a way to specify custom claims (`identityClaim` and `groupClaim`) as documented [here](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-claims), if you just need to insert that value into the the DynamoDB table. This would keep all the auth rules you have in sync where as custom resolvers, you would make sure the auth logic gets updated when the `@auth` rules are updated.

That is pretty cool but won't work with me, I am doing multi-tenancy so inserting in each record a 'tenant' field that I get from the group, which gets injected from the user custom attributes, the queries will filter against that field later.

**Comment by c0dingarchit3ct** [comment]
> Well, not sure if that step is necessary only for "added" resolvers, or is it also needed for overwritten ones.

Nobody is 'sure', that is my definition of 'needs documentation'!

**Comment by c0dingarchit3ct** [comment]
> Hello, it sounds like you are missing the "Add a resolver resource to a stack in the stacks/ directory."
> 
> I have followed this example and it is working fine for me:
> https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model
That document is as clear as mud, what is the `ApiId.ref' ? how is that related to the parameters on the top section of the _CustomResources.json_
Do we have any examples of that? and as you said in your other document is there any documentation of this? each error takes between 10 to 12 minutes with messages that are very cryptic like this 

![Fullscreen_2019-12-16__6_50_PM](https://user-images.githubusercontent.com/13644773/70952723-166fc280-2035-11ea-8277-b1d7bd452037.png)

**Comment by Soek22** [comment]
Hello @c0dingarchit3ct,

 `AppSyncApiId` leave it as is. That string is auto replaced when pushing to backend.

Replace with your data:

- Resolver name right after the opening `“Resources”: {` and before the “type”.
- DataSourceName value
- TypeName value
- FieldName value
- Request and Response MappingTemplateS3Location path value according to your Type/Field name. 

Add as many resolvers as you need inside the `“Resources” { }` tags, separated by commas:

`
{
"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "An auto-generated nested stack.",
	"Metadata": {},
	"Parameters": ...
      ...
      ...
...

”Resources” : {
      “EmptyResource” : {
              ...
        },
      “Resolver1name” : {
              “type” :  "AWS::AppSync::Resolver",
              ...
         },
      Resolver2name” : {
              “type” :  "AWS::AppSync::Resolver",
              ...
        }
  }
}
`

**Comment by c0dingarchit3ct** [comment]
That was very precise, I have finally concluded that this was 'CloudFormation' so I went to gain more information and came to the same conclusion.
Good news: I gained some cloudformation knowledge and spent some time looking at the Amplify generated stack
Bad news, I am in the 'Only one resolver is allowed per field'? 

I tried to delete the resolver in AWS, that didn't work
I even tried to create a new environment and that did not work!
I read somewhere that this is by design! I am not sure how is that a decision that makes sense? being worried about breaking changes, you introduce something that will force me to change every table in my App and break everything else? the field in question is the Mutation 'createData' that creates the record,d other fields will be ListDatas and getData! this is a sample App I am trying to play with, my current App has 4 different types, of which I need to replace all create, list & get ? that is 12 fields that I have to delete and then push and then introduce?
Not a very good choice if you ask me!
![amplify_push_and_CustomResources_json_—_react-sem](https://user-images.githubusercontent.com/13644773/70959590-af5d0880-204a-11ea-8cf3-ba49c19caf5a.png)

**Comment by c0dingarchit3ct** [comment]
I had to go back to the original post from February 

https://aws.amazon.com/blogs/mobile/amplify-adds-support-for-multiple-environments-custom-resolvers-larger-data-models-and-iam-roles-including-mfa/

> After creating your AWS AppSync API, you will now have a new empty folder called resolvers created in your Amplify project in the API folder.
> To create a custom resolver, create a file (i.e. Query.getTodo.req.vtl) in the resolvers directory of your API project.
> The next time you run amplify push or amplify api gql-compile, your resolver template will be used instead of the auto-generated template. You may similarly create a Query.getTodo.res.vtl file to change the behavior of the resolver’s response mapping template.

It is really baffling that 10 months later those simple steps mentioned above are not working!

**Comment by c0dingarchit3ct** [comment]
I have found out that there was no need to modify the Custom Resources at all, I had to put the files in the 'resolvers' directory and make sure they match the names!. again the documentation sucks but alas, at least it is working now!
