### ISSUE TITLE
What is the difference between `amplify codegen` and `amplify api gql-compile`?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#3010]
**Which Category is your question related to?**
GraphQL / API

**Amplify CLI Version** 
4.6.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**

Is `amplify codegen` a new command? I can swear I was using `amplify api gql-compile` to generate local strongly typed models, but now `amplify codegen` does this? What is the difference between these two commands?

**Comment by yuth** [comment]
> Is amplify codegen a new command?

No this command has been around from the day we released Amplify CLI

> I can swear I was using amplify api gql-compile to generate local strongly typed models

`amplify api gql-compile` compiles the graphql schema and generates resolvers and cloud formation templates based on the transfomer directives that are present in the schema. This is used for deployment to cloud. Where as codegen generates GraphQL statements and types/classes that are used by the frontend. 

Feel free to comment/open if additional clarification is needed.
