### ISSUE TITLE
Add existing resources to amplify project

### ISSUE THREAD

**Issue by RubberDuckDestroyer** [aws-amplify/amplify-cli#3012]
**Which Category is your question related to?**
Amplify AppSync API/DynamoDB/Cognito

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
AWS Amplify, AppSync, DynamoDB, Cognito

I am fairly new to Amplify, I have a local Vue project and a previously created DynamoDB table and a Cognito user pool in AWS. 

1. I want to connect my table to the local amplify app backend so that I can use it with this app.
Can I use any of the following steps to connect my Amplify app to the previously created table
- Create a new API (done), connected to the previously created database
OR
- Connect an existing AppSync API created in the console to this local amplify app.
 I tried using `amplify codegen` after adding the apiID, as it says to do that in the AWS AppSync console. It updates the `src/graphql` files but I don't know how I can get the backend api files in the `amplify/backend/api/` folder to update with the corresponding api files.

2. I also want to use an existing Cognito user pool with the app and I have no idea how to do that.

Any help or info on the same will be helpful.
Cheers!

**Comment by yuth** [comment]
Amplify CLI does not allow you to reuse existing DynamoDB table as graphql-transformer creates and update these tables based on your GraphQL schema.

>     1. want to connect my table to the local amplify app backend so that I can use it with this app.
>        Can I use any of the following steps to connect my Amplify app to the previously created table
> 
> 
>     * Create a new API (done), connected to the previously created database


When using Amplify CLI graphql-transformer it is not possible to connect to previously created table



>     * Connect an existing AppSync API created in the console to this local amplify app.
>       I tried using `amplify codegen` after adding the apiID, as it says to do that in the AWS AppSync console. It updates the `src/graphql` files but I don't know how I can get the backend api files in the `amplify/backend/api/` folder to update with the corresponding api files.

`amplify codegen` command generates only the code needed for your applications front end and it would download the resolvers and you won't be able change the schema and push using `amplify push` command


> I also want to use an existing Cognito user pool with the app and I have no idea how to do that.

No, the CLI does not support using the existing cognito userpools.

Feel free to comment here if you have more questions

**Comment by RubberDuckDestroyer** [comment]
Alright, thank you for the response and the explanation for `amplify codegen`, I understand it better now. 👍 

I had another question, can I connect my backend to an existing AppSync API so I can change the schema of it's database and push locally instead of using the AWS Console to do the same?  

I was going through my local API that was created by the AppSync console, and I see a `CustomResources.json` file. By any chance, can I use this to connect to an existing AppSyn API? 
![Screen Shot 2019-12-18 at 11 19 57 AM](https://user-images.githubusercontent.com/24650979/71039208-7dea5700-2188-11ea-8338-e28e88c9acda.png)
![Screen Shot 2019-12-18 at 11 21 50 AM](https://user-images.githubusercontent.com/24650979/71039279-a1150680-2188-11ea-92e2-470e934d6755.png)

Here's a pic of the file in my backend.

**Comment by RubberDuckDestroyer** [comment]
@yuth Any update on the question? Can I connect my amplify app to an existing Appsync API??
