### ISSUE TITLE
Allow to remove current env

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#3013]
When i try to execute `amplify env remove <ENV_NAME>` i get this message

```
You cannot delete your current environment. Please switch to another environment to delete your current environment
If this is your only environment you can use the 'amplify delete' command to delete your project
```

This makes no sense. Our team uses amplify and we need to create new envs a lot (like every day - after merges with main branch etc). And of course we need to remove envs after we are done with task. With this restriction, we are forced to clean up resources manually

**Comment by yuth** [comment]
This is similar to how git behaves. You won't be allowed to delete the current branch you're in. 

>  Our team uses amplify and we need to create new envs a lot (like every day - after merges with main branch etc). And of course we need to remove envs after we are done with task. With this restriction, we are forced to clean up resources manually

You don't have to remove the environment manually. The only restriction when removing environment is that, it should not be active environment that is checked out. You could switch to a different environment and then remove it
```sh
$ amplify env checkout <an-existing-env>
$ amplify env remove <the-env-you-want-to-remove>
``` 

Please feel free to comment here if this does not solve the issue

**Comment by artyom-melnikov** [comment]
> This is similar to how git behaves. You won't be allowed to delete the current branch you're in

@yuth Amplify has huge differences with git so i don't think that approach applicable

1. `amplify init` has side effects (while `git checkout -b` not)
Amplify creates some resources during init (some roles and buckets) and also can have an issue because of env name collision as far as i remember. Cleanup is required after `amplify init`, but not required after `git checkout -b`

2. Poor conflict resolution on `amplify push`
There are many (really **many**) cases when `amplify push` will not be able to deploy changes to the existing environment. But what's worse it will mark everything as `updated` after that, preventing you from re-pushing fix. The fastest way to resolve it is to cleanup env and deploy new one.

That's how i see the development workflow with amplify:
1. `git checkout -b <some-feature-branch>`
2. `amplify init <some-name-for-this-branch>`
3. Write code - initial changes
4. `amplify push` - initial push
....
5. Write code / merge other branches
6. `<amplify undeploy>` - Remove current env from cloud
7. `amplify push` - Push to cloud again
....
8. `<amplify undeploy>` - cleanup after done with development
9. `git push origin HEAD` - done with development

Steps 5-7 can be repeated many times. The problem is, `<amplify undeploy>` is proposed to have 3 steps (checkout other env, remove current, init current again), which adds a lot of pointless actions every time.

You also want to remove current env before git push (because you don't want to include info about temp branch into `team-provider-info`)

Ideally amplify should provide a command to forcefully undeploy all resources related to current env from cloud (including those added on `amplify init`) and, optionally, cleanup all local files to not pollute git commit with pointless data

**Comment by cunneen** [comment]
This doesn't solve your main problem, but to recreate an environment (e.g. because of the push errors) I do this:

1. `amplify env add` - create a new `temp` environment (does an `env checkout` too)
2. `amplify env remove <environment_name>` - remove the env you wanted to remove
3. `amplify env add` - recreate the env you just removed (does an `env checkout`)
4. `amplify env remove temp` - remove the `temp` environment
