### ISSUE TITLE
Ionic IOS rejected by app store

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#3014]
I went to push my application apple yesterday and it was rejected due to the way Amplify handles authentication of social providers:

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

This stops my project dead. Is there any way around this, or any plans to enable social authentication in an ionic app using a web URL in which i can open within using the ionic pop over browser?

**Comment by elorzafe** [comment]
duplicated from https://github.com/aws-amplify/amplify-js/issues/4585 we will look into this on Amplify JS repo
