### ISSUE TITLE
Access parameter store from lambda function - invoking on client

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#3015]
**Which Category is your question related to?**
function

**Amplify CLI Version** 
4.5.0

**Provide additional details e.g. code snippets**
I'm storing 3rd party api keys in parameter store that lambda needs to access. Works fine on server but I would like to test the function on the client. I get an error "Missing credentials in config". How can I access the Parameter store while testing locally?

**Comment by yuth** [comment]
>  I would like to test the function on the client. I get an error "Missing credentials in config". How can I access the Parameter store while testing locally?

By client do you mean running [`amplify mock function <function-name>`](https://aws-amplify.github.io/docs/cli-toolchain/usage#function-mocking-setup)? If thats the case, we don't have support for mocking Parameter Store.

**Comment by aireater** [comment]
@yuth  Either via mock or invoke. Is there a flag that I can test for in the function that informs the function it is being called by mock or invoke?

**Comment by aireater** [comment]
I think I answered my own question. I'll add .env files and in event.json i'll set a flag for local and handle it in the code. 

Closing.

**Comment by aireater** [comment]
Also, I'm going to assume that I can use host: '192.168.1.11:20002' in the headers sent when  in mock to manage as well. Would be nice to have a flag set so the host doesn't need to be hardcoded.
