### ISSUE TITLE
Multiple Auth question

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#3018]
**Which Category is your question related to?**

Auth

**Amplify CLI Version** 

4.6.0

**What AWS Services are you utilizing?**

App Sync

So I was reading about [Supporting backend and internal processes with AWS AppSync multiple authorization types]https://aws.amazon.com/blogs/mobile/supporting-backend-and-internal-processes-with-aws-appsync-multiple-authorization-types/)

And this seems like what we need to do, however, I can't get completely there.

For example, let's say my background/internal process is adding/subtracting money from a user's balance - something we ONLY want admins and internal processes to do.

````
type Account 
  @model 
  @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [read, update, create]},
    {allow: private, provider: iam, operations: [read, update, create]},
  ])
{
  id: ID!
  accountUserId: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  email: AWSEmail!
  balance: Int!
}
````

This will correctly allow a user in the Admins cognito group to perform the operations.

Similarly, the second rule will allow IAM authorized roles to perform the operations.

However, I'm pretty sure the second rule will allow ANYONE logged into a cognito pool to perform the operations, which is obviously not good.

How can we ONLY allow only a specific IAM role to perform the operations?

**Comment by attilah** [comment]
@CodySwannGT To support your scenario you can put ```@aws_iam``` on the type and on the related queries, mutations, and create the appropriate policies for your custom role. Another thing about IAM based access is that if you create Lambda function in the project then you can choose to access the API resource from that function and then you can attach/update/modify the policies as needed for the Lambda Execution role of that function.

I'm closing the issue as it was answering your question, but if something new comes up, feel free to reopen it or open a new one if not related.

**Comment by CodySwannGT** [comment]
Thanks so much for the reply.

So, let's say I want to prevent an instance of User from ever being deleted, so I have these rules:

````
type User 
  @model 
  @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [read, update, create]},
    {allow: private, provider: iam, operations: [read, update, create]}, #internal process
    {allow: owner, ownerField: "id", operations: [read, update, create]},
    {allow: public, provider: cognitoPools, operations: [read, create]}, #any signed in user
    {allow: public, provider: iam, operations: [read]}, #Guest users
  ])
{
}
````

I thought this would achieve what I wanted, but [according to the docs ](https://aws-amplify.github.io/docs/cli-toolchain/graphql#owner-authorization), it appears that everyone would have the ability to delete since I don't explicitly list it.

Is that correct?
