### ISSUE TITLE
How to get an Amplify configuration file ?

### ISSUE THREAD

**Issue by dancomanlive** [aws-amplify/amplify-cli#302]
** Which Category is your question related to? **

** What AWS Services are you utilizing? **

** Provide additional details e.g. code snippets **

**Comment by kaustavghosh06** [comment]
@dancomanlive  Could you please describe issue a bit more? Hard to decipher the issue from the description.

**Comment by kaustavghosh06** [comment]
Please feel free to re-open this issue if the problem still persists.
