### ISSUE TITLE
Pass input to `amplify pull`

### ISSUE THREAD

**Issue by youjinp** [aws-amplify/amplify-cli#3021]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify

**Amplify CLI Version** 
4.6.0

**Question**
Is there a way to pass input to the command `amplify pull`? 

Currently it asks a bunch of questions when called:

```sh
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use <...>
? Which app are you working on? <...>
Backend environment 'prod' found. Initializing...
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
? Do you plan on modifying this backend? Yes
```

My goal is to automate changing the backend env, and it doesn't seem like `amplify pull` takes in any input besides `--app-id` and `--envName`?

**Why not just switch branch with `--app-id` and `--envName`?**
Because all the backend environments have different `appIDs` and the cli will complain with 
```sh
Amplify appId mismatch.
You are currently working in the amplify project with Id <...>
```

**Current process**
1. delete amplify folder
2. call `amplify pull`
3. manually enter answers
4. wait
5. run automated script

**Comment by UnleashedMind** [comment]
Yes, you can pass in appId and envName like this: 

`amplify pull --appId xxxx --envName xxxx`

**Comment by kaustavghosh06** [comment]
@youjinp We'll document this. Thanks for bringing this to our attention.

**Comment by youjinp** [comment]
For anyone coming across this, I have figured out the inputs required to run `amplify pull` in headless mode.

Here's the script

```sh
AWS_CONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"my-profile\"\
}"

FRONTEND="{\
\"frontend\":\"ios\"\
}"

AMPLIFY="{\
\"envName\":\"my-env-name\",\
\"appId\":\"my-app-id\",\
\"defaultEditor\":\"code\"\
}"

amplify-dev pull \
--awscloudformation $AWS_CONFIG \
--frontend $FRONTEND \
--amplify $AMPLIFY \
--yes
```
