### ISSUE TITLE
Storage creating bucket name with env twice

### ISSUE THREAD

**Issue by Chakron** [aws-amplify/amplify-cli#3031]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

adding s3 storage

**Amplify CLI Version** 

4.6.0

**What AWS Services are you utilizing?**

Amplify CLI, s3

**Provide additional details e.g. code snippets**

When I type "amplify add storage" in my beta environment, follow the instructions, and enter an s3 bucket name of "test" (just an example) I end up with an s3 bucket named "testbeta-beta". My prod environment is similar - I get a bucket named "testprod-prod". Is it intentionally appending the environment name twice, or am I misunderstanding something? It seems like it would need to do it once, but I don't understand why it's happening twice. I'm not sure if this is a bug or not, or if its going to affect my ability to interact with these s3 buckets in the future.

**Comment by kaustavghosh06** [comment]
@Chakron Ideally it shouldn't add the env names twice and I tested it on my local machine us-east-1 region and the CLI didn't add the env name twice.
Having said that, this shouldn't affect your app or it's usage if the ` "aws_user_files_s3_bucket"` set in the `src/aws_exports.js` file (in case of  JS projects) is set correctly to the right bucket.

**Comment by Chakron** [comment]
Thanks for taking a look and trying to recreate the issue @kaustavghosh06. It's strange, this is a new project and I've just used the latest version of the Amplify CLI to create my resources. No idea why this is happening, but unless it becomes a problem in the future it doesn't look like I have too much to be concerned about other than the strange name. Maybe someone else will run into this and comment here.

**Comment by yonatanganot** [comment]
We are facing the issue when creating new storage resource.

**Comment by yonatanganot** [comment]
We are facing the same issue when creating new storage resource.
