### ISSUE TITLE
Multi-Env Admin Queries CloudFormation Template 

### ISSUE THREAD

**Issue by james-iacabucci** [aws-amplify/amplify-cli#3034]
I'm struggling with how the new admin queries features handles its cloud formation templates in a multiple env scenario.  I'm using cli v4.6. 

I have my master branch and prod env working great. I then create a branch for test, do a "amplify env add", and configure my test env. 

When I amplify push, I notice the AdminQueriesXXX-cloudformation-template.json file is updated in the /backend/function/AdminQueriesXXX folder. The S3Bucket is updated with the name of deployment bucket for my test env.

Unlike team-provider-info.json, which has sections for each env, if commit this to test, then merge into master, won't I have the wrong values?

...
"Runtime": "nodejs8.10",
 "Timeout": "25",
 "Code": {
 -	"S3Bucket": "amplify-ccash-app-production-105206-deployment",
 +	"S3Bucket": "amplify-ccash-app-test-233939-deployment",
 	"S3Key": "amplify-builds/AdminQueries5e09c66a-476f32364e2b6e343048-build.zip"
 }

Thanks!

**Comment by kaustavghosh06** [comment]
@james-iacabucci Lambda cloudformation works a bit differently. Whenever there is a change to your lambda function code, for Cloudformation to know that there is a change in the `src/`, we need to generate a unique S3Key and stick it in the Cloudformation file dynamically. This S3Key generation happens dynamically on an `amplify push` based upon the environment you're in. So even if you push back your changes to the test branch, on the next `amplify push` command another unique S3 key would be generated and put in the Cloudoformation file. 

I would recommend putting this Lambda Cloudformation file in gitignore if you don't intend to change configuration settings for this file in the future to avoid the S3 Key changes after every `amplify push`.

**Comment by alexkates** [comment]
I'm also experiencing this issue, though with a slight caveat. I have had to make changes to the lambda's cloudformation to support https://github.com/aws-amplify/amplify-cli/pull/2463#issuecomment-554980258

Because of the above change, It's necessary to keep the cloudformation template in version control. Any other work around for his?

**Comment by kaustavghosh06** [comment]
@alexkates As I've mentioned above, the S3Keys are generated dynamically and it won't affect your push to the cloud. We are working on a long term solution to move this key to a build folder whcih can be gitignored.

**Comment by bob-lee** [comment]
Not sure what's the smooth way of deploying code changes to multiple environments. I have two envs - `dev` and `prod` and using `amplify console` for CI/CD. Often when I make a PR to prod, I have to fix conflicts on those cloudformations templates. Do I never have to `amplify push` if I'm happy with `amplify console`?

**Comment by tobiasfeil** [comment]
> @james-iacabucci Lambda cloudformation works a bit differently. Whenever there is a change to your lambda function code, for Cloudformation to know that there is a change in the `src/`, we need to generate a unique S3Key and stick it in the Cloudformation file dynamically. This S3Key generation happens dynamically on an `amplify push` based upon the environment you're in. So even if you push back your changes to the test branch, on the next `amplify push` command another unique S3 key would be generated and put in the Cloudoformation file.
> 
> I would recommend putting this Lambda Cloudformation file in gitignore if you don't intend to change configuration settings for this file in the future to avoid the S3 Key changes after every `amplify push`.

Remember not doing `git rm --cached amplify/backend/function/AdminQueriesXXX/AdminQueriesXXX-cloudformation-template.json` as you would normally do when gitignoring a file, since you still want it to remain in the repository.
