### ISSUE TITLE
API codegen models iOS: [String] field converted to List<String>?

### ISSUE THREAD

**Issue by Soek22** [aws-amplify/amplify-cli#3035]
new `API` in preview, `bug`, `code-gen`
**Describe the bug**
`[String]` field defined on graphql schema gets converted to` List<String>?` when generating models. List definition is `List<ModelType: Model>` (as per _Pods/Amplify/List+Model.swift_) so I get `Type 'String' does not conform to protocol 'Model'` error at build time.

**Amplify CLI Version**: amplify -v: 4.6.0
**Platform target**: iOS

**To Reproduce**

GraphQL schema:
**status: [String]**
```
type Task @model {
    id: ID!
    title: String!
    description: String
    status: [String]
}
type Note @model {
    id: ID!
    content: String!
}
```

**Expected behavior**
I need to be able to create String arrays (and other primitive types: Int, etc.), not only model arrays/collections.

Related issues: https://github.com/aws-amplify/amplify-ios/issues/257

**Comment by Soek22** [comment]
`ModelFieldType` doesn't contemplate the possibility of collection of basic types as per `Pods/Amplify/ModelSchema+Definition.swift`.

**Comment by Soek22** [comment]
BTW, **should this kind of issues be reported to https://github.com/aws-amplify/amplify-ios ?**
It is a `$ amplify codegen models` , but it is a specific amplify iOS module issue, so maybe doesn't affects to Javascript/Android implementation.

**Comment by drochetti** [comment]
Hi @Soek22, thanks for reporting this and for providing your feedback and details about the issue. This is a limitation indeed and we're discussing a fix for this.
