### ISSUE TITLE
Auth - from mail to sms code

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#3038]
Is it possible to change the Auth process? From mail to SMS. 

I want all new users to register via SMS. 
So get the SignUp Code via SMS. Or even make it selectable. 

![Bildschirmfoto 2019-12-19 um 17 13 35](https://user-images.githubusercontent.com/7137361/71189928-e8cc8880-2283-11ea-9821-5639a0687ac8.png)

i can see this in the console

**Comment by kaustavghosh06** [comment]
@davidbiller The Cognito console won't allow you to do this correct?
 I believe they don't have support for this migration/change use-case at the moment.

**Comment by davidbiller** [comment]
> @davidbiller The Cognito console won't allow you to do this correct?
> I believe they don't have support for this migration/change use-case at the moment.

Jap, it’s not possible to change this in the console. 
So is there a workaround for this? 
I guess I can’t create a new userpool and get the accounts than from the old one, and use this is my amplify project.

**Comment by kaustavghosh06** [comment]
The only way currently is to create a new user pool with these configurations and there are ways to migrate users from one user pool to another - 
https://aws.amazon.com/blogs/mobile/migrating-users-to-amazon-cognito-user-pools/ if you want to try that out.

**Comment by davidbiller** [comment]
> The only way currently is to create a new user pool with these configurations and there are ways to migrate users from one user pool to another -
> https://aws.amazon.com/blogs/mobile/migrating-users-to-amazon-cognito-user-pools/ if you want to try that out.

Thanks. 
Will check this, and will check if or how I can change the userpool than in my amplify env.
