### ISSUE TITLE
DataStore does not support 1 to 1 connection with both sides of connection as optional field

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#3040]
** Which Category is your question related to? **
DataStore
** What AWS Services are you utilizing? **
DataStore
** Provide additional details e.g. code snippets **
I have parent / child objects in GraphQL. The following code will generate the error "DataStore does not support 1 to 1 connection with both sides of connection as optional field". If I make parentAsset mandatory (!) then there is no error.

THIS FAILS
```
type Asset @model
{
  id: ID!
  name: String!
  description: String
  assetParentAssetId: ID
  parentAsset: Asset @connection
}
```

THIS WORKS
```
type Asset @model
{
  id: ID!
  name: String!
  description: String
  assetParentAssetId: ID
  parentAsset: Asset! @connection
}
```

However, not every object will have a parent, so in my app its invalid to have this as a mandatory field. AppSync / GraphQL does not have this restriction and the schema works fine in AppSync.

**Comment by yuth** [comment]
@sacrampton Can a parent asset have multiple child assets? If it can, then after merging pr #3046 you could update your schema as follows.
```gql
type Asset @model
{
  id: ID!
  name: String!
  description: String
  parentAsset: Asset @connection(name: "assetParentChild")
  childAssets: [Asset] @connection(name: "assetParentChild")
}
```

This should allow you to have parent/child relationship, where an asset can be either be without a parent (root asset) or an asset can be with out any child( leaf asset)

**Comment by sacrampton** [comment]
Yes this would fix my issue - I will watch for #3046 availability

**Comment by sacrampton** [comment]
I just reinstalled everything (+ @aws-amplify/datastore@1.0.3 / + @aws-amplify/core@2.2.1) / amplify cli 4.7.0

Same error on the above example code you provided.

**Comment by yuth** [comment]
This fix was not part of the last release.  It should be included in the next one
