### ISSUE TITLE
How to access requested fields or modify one of them in the SELECT query

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3049]
Hello,

In my SQL database I save identifiers as BINARY(16), because they are UUID. However, in the app and API level, I am using the hexadecimal representation, given that this is more friendly.

Right now I am creating a template to modify the current logged user. This has 2 statements, an UPDATE and a SELECT.
At the moment, I don't have problems with the UPDATE statement. Basically I use the code already generated. But regarding the SELECT query, I have a small problem. I would like to convert the userId, using something similar to:
`"SELECT HEX(userId) as userId, morefields, morefields.... FROM User WHERE userId=UNHEX('$id')"
`But it is very annoying having to write all the fields (in this case, there are like 30).
I cannot use
`"SELECT * FROM User WHERE userId=UNHEX('$id')"
`Because that returns userId in the wrong format.

Is there anything I can do?
I though one solution could be using the same trick I do here with the input parameters, but using the requested parameters. Problem is, I don't see that and I don't know if that is possible.

```
#set( $updateList = {} )
#foreach( $entry in $ctx.args.updateUserInput.keySet() )
  #set( $discard = $updateList.put($entry, "'$ctx.args.updateUserInput[$entry]'") )
#end
#set( $update = $updateList.toString().replace("{","").replace("}","") )

#set( $selectList = {} )    ## not working, it should be requested parameters, not input.
#foreach( $entry in $ctx.args.updateUserInput.keySet() )
	#if ($entry == "userId")
    	#set( $discard = $updateList.put("HEX(userId) as userId") )
    #else
        #set( $discard = $updateList.put($entry) )
	#end
#end
#set( $select = $selectList.toString().replace("{","").replace("}","") )

#set($id = "123e4567e89b12d3a456426655440000")
####set($id = $context.identity.sub.replace("-",""))
{
  "version": "2018-05-29",
  "statements":   ["UPDATE User SET $update WHERE userId=UNHEX('$id')", 
  				"SELECT select FROM User WHERE userId=UNHEX('$id')"]
}
```

**Which Category is your question related to?**
Templates code generation,

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
AppSync and Aurora Serverless

**Comment by nikhname** [comment]
> I cannot use
"SELECT * FROM User WHERE userId=UNHEX('$id')" Because that returns userId in the wrong format.
If I understand correctly, you are trying convert the userId to hex in the SELECT query?
Would using "SELECT HEX(userId) FROM User WHERE userId=UNHEX('$id')" solve this problem?

**Comment by Ricardo1980** [comment]
@nikhil-dabhade 
Yes.

Sometimes what is saved in the data base does not match with the graphql data model.
An example is AWSTimestamp, that is an integer (evidently), but in MySQL, TIMESTAMP is a string like '1970-01-01 00:00:01'. This is clearly incompatible and in order to use AWSTimestamp we need something like:

SELECT HEX(userId) as userId, cast(UNIX_TIMESTAMP(createdAt) as unsigned) as createdAt, type FROM User

Regarding the userId in my case, my data base has BINARY(16) and the graphql uses the ID type (which is a string). So, similar case, we need to convert it. You don't use Binary type in the graphql schema to identify instances, right?

So, the problem is, how can I solve this without having to modify all my resolvers everything I add or modify a field? Doing that manually is working, but it is very annoying.

Thanks for suggestions.

**Comment by nikhname** [comment]
@Ricardo1980 Thats correct we do not use a Binary type in the graphql schema, only ID type. 

From mySQL perspective it is best practice to list out each of the fields selected, since it ensures consistency and best performance. So your current solution 

"SELECT HEX(userId) as userId, morefields, morefields.... FROM User WHERE userId=UNHEX('$id')" 

looks good to me from a correctness point of view.

We will look into autogenerating this code since it is a hassle to make changes to the resolvers for every change in schema.

**Comment by Ricardo1980** [comment]
Thanks @nikhame 
The for loop I have is a bit ugly. 
Try to add this to your tasks please. 
I close the ticket.
