### ISSUE TITLE
How to access GraphQL endpoint from Lambda function?

### ISSUE THREAD

**Issue by silkyfray** [aws-amplify/amplify-cli#3057]
**Which Category is your question related to?**
Accessing GraphQL inside Lambda function.

**Amplify CLI Version** 4.2.0

**What AWS Services are you utilizing?**
GraphQL API, Lambda

**Provide additional details e.g. code snippets**
In my function I am trying to access the graphql endpoint as described in the  [GraphQL from Lambda](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda.
) section of the docs.
![image](https://user-images.githubusercontent.com/2873559/71310781-df702700-240f-11ea-8b15-23fe17247064.png)

How do I expose the graphql endpoint as an environmental variable that is not hardcoded to the actual url but a reference to the url?

So far I tried adding a variable in the `myfunction-name-cloudformation-template.json` like so
![image](https://user-images.githubusercontent.com/2873559/71310700-1db91680-240f-11ea-9151-283a89d23133.png)
but didn't have any luck.

**Comment by gaochenyue** [comment]
it is already an environment variable. It is a reference to aws_appsync_graphqlEndpoint in aws-exports.js

**Comment by silkyfray** [comment]
Thanks @gaochenyue . How do I go about referencing `aws_appsync_graphqlEndpoint` from the lambda function? The following would not work since it's outside the function directory:
```
const appsyncUrl = require('../../../../../src/aws-exports').default.aws_appsync_graphqlEndpoint
```

**Comment by kaustavghosh06** [comment]
@silkyfray You can do an `amplify update function` and in the flow request access to the Amplify resource - in your case the AppSync API. This will automatically inject the environment variables into the lambda function (which includes the graphql endpoint).

**Comment by kaustavghosh06** [comment]
@silkyfray Closing this issue. Please let me know if you're still not unblocked based on my last response.
