### ISSUE TITLE
How to request a subset of fields using AppSync/API.swift?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3071]
Hello,

Using the code generated in API.swift, it seems it is possible to send partial mutations, that is, no need to update an entire object, just update what exactly I want. Cool. 
But I don’t know how to do the same when requesting data. I mean, the point of using GraphQL is to solve the under fetching and over fetching problem, but I don’t see how to do that using the code generated by “amplify api gql-compile”

For example, let’s say I have this schema:

```
type User {
	  userId: ID!
	  dob: AWSDate!
  	state: UserState!
	email: String!
        ...
       other 30 fields
       …
}

type Query {
    loggedUser: User
}
```

If I only want to know the id and state, I should send something like:

```
query LoggedUser {
	loggedUser {	
		id
		state
	}
}
```

But, I don’t see a way to do that when using the API.swift file.

What do I have to do?
Right now, when using API.swift, all fields are always retrieved, which is not very nice.
Any recommendation?
Thanks.

**Which Category is your question related to?**
code generation

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
AppSync for iOS. Aurora.

**Comment by Ricardo1980** [comment]
OK, I found a way, it was not clear in Amazon docs, but I found some clues in Apollo docs.
https://www.apollographql.com/docs/ios/tutorial/tutorial-query-ui/

Basically, create a customQuery.graphql with the new queries and put it inside the graphql folder.
Run "amplify codegen"
API.swift is updated and you can use the new nested types.

I would recommend to mention this in amplify docs, it is not clear.

**Comment by nikhname** [comment]
@Ricardo1980 Yes, codegen supports the use of custom queries, mutations and subscriptions in the way you mentioned. If it this is not clear enough in the docs please feel free to raise an issue in the docs repository: https://github.com/aws-amplify/docs. Closing this issue based on your solution
