### ISSUE TITLE
AppSync console sample project Tasks App error

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#308]
**Describe the bug**
On AppSync Console, create new API, select Tasks App under "Start from a sample project". This will create a CloudFormation stack. The stack creation at the end is ROLLBACK with error.

**Additional context**
Stack ID: 
arn:aws:cloudformation:us-east-1:004855210358:stack/AppSync-Task-TasksApp-2018290rMY/b4e6a670-d20e-11e8-ad56-50fae98974fd

Events: 
21:16:58 UTC+0800 | CREATE_FAILED | AWS::AppSync::DataSource | AppSyncDDBDataSource | Caller credentials can only be used with AWS IAM authenticated API (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: ecd61bbd-d20e-11e8-9240-a3993c08f506)

**How to repeat this error?**
Visit AppSync console and create a new API based on the Tasks App sample project.

**Comment by kaustavghosh06** [comment]
Please open an issue in the AWS forums - https://forums.aws.amazon.com/tags/appsync for Appsync service/console related questions. Thanks!
