### ISSUE TITLE
Amplify update causes useless error

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#3085]
Just updated the Amplify CLI. Ran amplify push after changing the redirect URLS and was given this error:

> Syntax Error: Expected Name, found String "version"
> An error occured during the push operation: Syntax Error: Expected Name, found String "version"

Any ideas?

**Comment by UnleashedMind** [comment]
@oliverandersencox 
Please provide more information so we can investigate;
- Operating system
- Amplify CLI version
- Nodejs Version 
- Which categories are added to your backend (e.g. api, auth, etc.), which category gave you the error?

**Comment by oliverandersencox** [comment]
@UnleashedMind 
- Mac OSX Catalina 10.15.1
- Amplify Cli - 4.9.0
- Node JS - 13.5.0
- I have Auth, Api and Storage all working absolutly fine.

This morning I ran the command to install/update the amplify client

I then ran 'amplify update auth' so as ti change the redirect URL's to work with my IOS app as I have done many times before. 

After I then ran amplify push and was immediately presented with the error.

I was able to add to my api just after the update, in which amplify push api worked just fine, so I would presume the auth part is causing the issue.

**Comment by oliverandersencox** [comment]
@UnleashedMind I have tried everything I can think of and nothing is resolving this issue. It happens everytime i run 'amplify push' or amplify push auth/api etc.

I recently upgraded to node 10 in which amplify asked me if I would like it to update everything to node 10, in which I said yes.

I cannot do anything until a solution is found. The error message indicates its a graphQL parsing error but it doesn't give a reason.


> Syntax Error: Expected Name, found String "version"
> GraphQLError: Syntax Error: Expected Name, found String "version"
>     at syntaxError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/error/syntaxError.js:24:10)
>     at expect (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1299:32)
>     at parseName (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:92:15)
>     at parseField (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:295:21)
>     at parseSelection (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:284:72)
>     at many (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:1348:16)
>     at parseSelectionSet (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:272:17)
>     at parseOperationDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:194:21)
>     at parseExecutableDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:172:12)
>     at parseDefinition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graphql/language/parser.js:146:12)

**Comment by kaustavghosh06** [comment]
@oliverandersencox This doesn't seem to be related to the Node version update but seems ties to your GraphQL schema. Could you please share your schema?

**Comment by aprilmintacpineda** [comment]
extremely awful dev experience

`An error occured during the push operation: Syntax Error: Expected Name, found @` and I only added a field to the graphql schema.

**Comment by kaustavghosh06** [comment]
@oliverandersencox Were you able to resolve this issue?

**Comment by aprilmintacpineda** [comment]
Don't you dare!
