### ISSUE TITLE
Amplify mock doesn't include aws-sdk

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#3087]
**Which Category is your question related to?**
amplify mock, function

**Amplify CLI Version** 
4.6.0

My understanding is that aws-sdk is automatically included in lambdas. I have a function that uses the aws-sdk to access the parameter store. For local mocking I use dotenv. 

Mock is complaining "Error: Cannot find module 'aws-sdk'" when running the function from `amplify mock` (via graphql call).

Does aws-sdk need to be npm install'ed for functions that use it to access other aws services or can it be omitted? Is this a bug with mock or am i not understanding when to install aws-sdk?

**Comment by kaustavghosh06** [comment]
@aireater Yes, you can include that in dev dependencies in your package.json for the lambda function for local mocking.
