### ISSUE TITLE
How to decouple the authentication and application

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#3092]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Best practices on architecting and decoupling multiple applications that use common authentication user pool

**Amplify CLI Version** 

latest version

**What AWS Services are you utilizing?**
AWS Appsync

This is more of the best practices question, I have a couple of applications that use a common authentication. I am just trying to understand the best way to decouple the authentication and the 2 interdependent applications.

The need to decouple the authentication pieces to be managed by admin users in a separate sub-account of AWS as it is a shared service and would like it to be completely decoupled from a number of applications. I also have 2 applications that use the same authentication cognito user pool. The dependency between the 2 applications is that 1 application calls the other to get pricing information.

Hence questions:
1. How to decouple the authentication and authorization into a separate account as it is a shared authentication service used to authenticate many app-sync applications
2. How can I have multiple applications preferably on top of same shared DynamoDB database and yet leveraging common authentication service mentioned in #1
3. How to have multiple frontends (Web - React, Angular, Vue.js Native - ReactNative, Amplify Native iOS, Native Android etc...) - for single backend graphQL API

**Comment by kaustavghosh06** [comment]
@arkllc Have you checked our Cognito User Pool groups? - https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html

Please find answers to your questions inline:

1) How to decouple the authentication and authorization into a separate account as it is a shared authentication service used to authenticate many app-sync applications

This is currently not possible with the Cognito service restrictions. Both the Cognito user pool  
(used for authentication) and Cognito identity pool (used for authorization) need to a part of the same account.

2) How can I have multiple applications preferably on top of same shared DynamoDB database and yet leveraging common authentication service mentioned in #1

We do not support this use-case of making use of an existing DynamoDB with an new API. It's on our radar to support it though.


3) How to have multiple frontends (Web - React, Angular, Vue.js Native - ReactNative, Amplify Native iOS, Native Android etc...) - for single backend graphQL API

This is a very common use-case which the CLI supports. You can read more about this out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends

**Comment by arkllc** [comment]
Thanks. Would be good if there is some guidance given on how to separate the auth from appsync app
