### ISSUE TITLE
PostConfirmation trigger fails after node runtime upgrade

### ISSUE THREAD

**Issue by multidis** [aws-amplify/amplify-cli#3093]
**Describe the bug**
Post-confirmation lambda trigger fails:
```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'add-to-group'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Cannot find module 'add-to-group'",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:562:25)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at Runtime.exports.handler (/var/task/index.js:10:25)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

**Amplify CLI Version**
4.9.0

**To Reproduce**
When configuring `auth` include "Add users to group" option and let Amplify create the default function for that. Then try signing up a new user.

**Expected behavior**
Post-confirmation lambda trigger should succeed.

**Desktop (please complete the following information):**
Irrelevant (AWS Lambda runtime)

**Additional context**
Can be fixed, for example, by modifying `parameters.json`: change
`"modules": "add-to-group",`
to
`"modules": "./add-to-group",`
to ensure node looks for the corresponding source file in `src/`.

NOTE to the Amplify team: perhaps other functions need to be checked for a similar case of importing modules from local files? @kaustavghosh06 
https://github.com/aws-amplify/amplify-cli/pull/3044
https://github.com/aws-amplify/amplify-cli/issues/2617

**Comment by kaustavghosh06** [comment]
@multidis We have documented the change out here - https://aws-amplify.github.io/docs/cli/lambda-node-version-update and made this link available as a part of the migration in the CLI for customers to be aware about this change in the Lambda function code.
