### ISSUE TITLE
nested-cloudformation-stack.yml uses backup (tilde) files for custom CFN

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#3096]
**Describe the bug**

The generated `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` uses the backup file for it's custom stack:

```
		"AuroraCluster": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplify-amplify-js-app-ireland-145750-deployment/amplify-cfn-templates/Aurora/cloudformation-template.yml~",
				"Parameters": {
					"rdsDatabaseName": "TESTDB",
					"env": "ireland"
				}
			}
		}
``` 

I'm editing with Emacs, so it tends to create a backup file with the same name but ending in `~` (tilde).

**Amplify CLI Version**
4.9.

**To Reproduce**
Copy `amplify/backend/<custom-category>/<custom-resource>/cloudformation-template.yml` to `cloudformation-template.yml~` and execute `amplify push` to update `nested-cloudformation-stack.yml`.

**Expected behavior**
It should never use backup files. It should look for exact endings of '.yml' or '.json', not any filename having this as part of the filename.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10.
 - Node Version: 10.18.0

**Comment by berenddeboer** [comment]
This happens at more places. Just saw this during an `amplify push`:

```
Invalid extension .json~ for stack CustomResources.json~
An error occured during the push operation: Invalid extension .json~ for stack CustomResources.json~
```

**Comment by attilah** [comment]
@berenddeboer while we're working on fixing the issue as a workaround you could reconfigure emacs to always create the backups in 1 directory instead where the file exists or disable backups.
