### ISSUE TITLE
Cannot subscribe me with graphql

### ISSUE THREAD

**Issue by ecentinela** [aws-amplify/amplify-cli#3098]
**Which Category is your question related to?**
graphql-transform

**Amplify CLI Version** 
4.9.0

**What AWS Services are you utilizing?**
amplify, cognito, dynamodb, graphql

**Provide additional details e.g. code snippets**
When I try to subscribe me to a *membership* create operation with the following code

```
API.graphql(
    graphqlOperation(onCreateMembership)
).subscribe({
    next: (data: any) => {
        console.log('added', data);
    }
})
```

the websocket requests returns me the following sentence:

```
{"type":"error","id":"9999671a-0f69-4db8-8b36-9980d8000f62","payload":{"errors":[{"message":"Variable 'owner' has coerced Null value for NonNull type 'String!'"}]}}
```

I though that the owner property is automatically filled by amplify with my logged in use (I'm logged in with the amplify-react component), but it seems that this is not the case...

This is my graphql schema and the graphql operations are created automatically by amplify.

```
enum Recurrence {
    MONTHLY
    ANNUAL
}

type Service @model @auth(rules: [{allow: private}]) {
    id: ID!
    image: String!
    name: String!
    price: Float!
    recurrence: Recurrence!
}

type Membership @model @auth(rules: [{allow: owner}]) {
    id: ID!
    service: Service! @connection
    contractedAt: String!
}
```

Is there anything wrong with my code?

**Comment by SwaySway** [comment]
Hello @ecentinela 
Since there is a rule on only allowing owner on the type Memberships an owner is a requirement in when doing the `onCreaateMembership` operation.

Docs on authorizing subscriptions:
https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions
