### ISSUE TITLE
Profiles example.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#31]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
I can't find a detailed list of what IAM permissions to assign when using profiles. Currently I've just assigned full permissions to the resources as they failed during a publish.

Or does it just need a power user? Thanks.

Regards.
JJ

**Comment by kaustavghosh06** [comment]
@jarrettj  The IAM user would need Admin access for the CLI to deploy various resources in your AWS account.

**Comment by jarrettj** [comment]
Thanks.
