### ISSUE TITLE
Adding support for multi-tenancy using third-party authentication providers

### ISSUE THREAD

**Issue by forstmeier** [aws-amplify/amplify-cli#3101]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

My team is currently using [Auth0](https://auth0.com/) as our third-party OIDC provider but using this and the Amplify `@auth` transformer is proving to be difficult when implementing multi-tenancy.

**Describe the solution you'd like**

Ideally, something where additional fields can be passed in, possibly with the `allow: groups` option, would be ideally combined with the `providers: oidc` option in the transformer. Being able to pass in arrays/multiple values from the received third-party token (in this case from Auth0) could be handled in a similar manner to how the `owner` field is currently managed.

**Describe alternatives you've considered**

We were able to get the "single user" `@auth` working using the `provider: oidc` option for the `owner` field. However, this was limited as no arrays can be passed in.

Switching over to the `groups` option caused additional difficulties trying to set up/implement Cognito pools. Because we're still using Auth0, we tried "mirroring" user profiles into the Cognito pools but this is not fully working and a pretty clunky workaround.

**Additional context**

If a better option to what we're trying (combining third-party providers like Auth0 with "group"-level configurations) with multi-tenancy, any suggestions would be welcome.

It's worth noting that there are several open issues that address similar/important aspects of this issue:
- #2705 is very similar, if not the same, request; we're specifically interested in supporting multi-tenancy
- #2241 raises some technical/security issues that are important to keep in mind
- #177 is another issue that might need to be addressed using third-party providers
- #18 and #1578 as well

**Comment by jphgardner02** [comment]
This is something i am interested in.

**Comment by RossWilliams** [comment]
When using the group auth there is a property "groupClaim" which you can point to any claim in your token, and it accepts a JSON stringify-ed array of values. This might help you as its a pretty generic escape hatch and doesn't rely on cognito, just whatever claim is in the token.

I haven't used other identity providers with Amplify, so this advice might not help for your specific issue.

**Comment by RossWilliams** [comment]
I'm not sure if there is a technical reason why groups is blocked from being used with oidc providers, other than the confusion it could cause users who don't realise they would have to specify a custom groupClaim property.

In packages/graphql-auth-transformer/src/ModelAuthTransformer.ts:2022 there is a check, but it would be interesting to remove this and see if group auth with groupClaim works for your case.

**Comment by SwaySway** [comment]
I believe this merged pr might addresses using groups with oidc as a provider.

https://github.com/aws-amplify/amplify-cli/pull/2719

**Comment by SwaySway** [comment]
Closing this issue as the pr has been merged and is included in the latest release.
