### ISSUE TITLE
Managing branches and environments

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#3102]
*Which Category is your question related to?**
all of them

**Amplify CLI Version** 
4.10.0

I'm following the "Environments and Teams" part of the documentations.

When I add a function, for example, i want to add it to another branch once my testing is done. So I check out the branch using git, then i merge the branch where i have the new function into the "new" branch. I don't see the new function listed in amplify status before or after the push. The functions are not in the team provider info json file either. 

My maind development branch is built using the amplify console but my secondary branch is pushed via CLI. 

How should I manage this use case?

**Comment by kaustavghosh06** [comment]
@kldeb After you merge the changes to your git branch, did you do `amplify env checkout <env-name>`? Do you see the function in your `amplify/backend/backend-config.json`?

**Comment by kldeb** [comment]
@kaustavghosh06 yes, `git checkout branch_name` then  `amplify env checkout <env-name>`. The functions are in `backend-config.json`

**Comment by kaustavghosh06** [comment]
After `amplify env checkout <env-name>`, the functions don't show up in the `amplify-meta.json` file?

**Comment by kldeb** [comment]
@kaustavghosh06 I just ran env checkout now and it shows up (after the push) and now the status indicates that the functions will be created.

**Comment by kaustavghosh06** [comment]
@kldeb Okay, cool. I just tried re-producing this to see if this is an issue but the functions showed up after `amplify env checkout <env-name` in another env. 
Let me know if you're able to reproduce it with any other resource or category.

**Comment by kaustavghosh06** [comment]
Closing this issue. Please let me know if you're able to reproduce.
