### ISSUE TITLE
Many-to-many relationship with custom key is not possible

### ISSUE THREAD

**Issue by tw1t611** [aws-amplify/amplify-cli#3104]
Hi,

just tried to add a many-to-many relationship, where one type has a custom key defined.
The error tells, that the key must be of type `ID`.

Example from the docs (modified to have a custom key field):
```gql
type Post @model @key(fields: ["title"])
 {
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["title"])
}

type PostEditor
  @model(queries: null)
  @key(name: "byPost", fields: ["title", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "title"]) {
  id: ID!
  title: String!
  editorID: ID!
  post: Post! @connection(fields: ["title"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```

However, it should be possible to combine a key of `String` and `ID`
```gql
  @key(name: "byPost", fields: ["title", "editorID"])
```

The error message in this case would be `title field is not of type ID`.

Reproduction:
1. Create the schema
2. amplify push

This feature may not be implemented yet and would therefor not be a bug. It seems like this should work as a "basic" `@connection` use case, however. Please make this a feature request, if it isn't a bug.

**Comment by attilah** [comment]
@tw1t611 in the connection transformer we're not enforcing the ```ID``` type, we are just checking if both side of a connection has the same type. Trying out the schema above works as expected, ```amplify api gql-compile``` succeeds with the latest version of the CLI.

What version of the CLI were you using? Please try out with the latest version and get back to us.

**Comment by tw1t611** [comment]
@attilah it is the latest version.
While building the reproduction, I realized, that I wrote `name` instead of `keyName`.
That was absolutely my fault. The error message was a bit misleading though.
Sorry for the noise.

**Comment by attilah** [comment]
@tw1t611 no worries, and thanks for the feedback on the error message.
