### ISSUE TITLE
Jenkins integration (CI integration)

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-cli#3105]
**Is your feature request related to a problem? Please describe.**
I am currently using Jenkins to work on new project and automate the CI part of the project. I can't seem to find aws-amplify/cli plugin in Jenkins. 

**Describe the solution you'd like**
A plugin for aws-amplify/cli to use with Jenkins

**Describe alternatives you've considered**
A way to integrate or use aws-amplify/cli with Jenkins 

**Additional context**
I am not quite sure how to integrate aws-amplify/cli with Jenkins to automate the build and deploy and any of the commands that aws-amplify/cli can do. 

I checked the headless mode but I am not sure how Jenkins will understand the amplify commands without installing aws-amplify/cli plugin - which is not available.

**Comment by kaustavghosh06** [comment]
@totaland I have typically seen CI systems install the CLI on every build. So you can use `npm install -g @aws-amplify/cli` to install the CLI as a part of your build step.

**Comment by totaland** [comment]
@kaustavghosh06 thanks mate it works
