### ISSUE TITLE
AppSync backup file resolvers also uploaded to S3 (ending with ~)

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#3107]
**Describe the bug**
`amplify push` uploads any file found in the `resolvers/` directory, including clear backup files such as 'Query.getSomething.req.vtl~` (created by editor such as Emacs).

**Amplify CLI Version**
4.9.0

**To Reproduce**
Copy a `.vtl` file to `.vtl~`.

**Expected behavior**
Should skip backup files.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10.
 - Node Version. 10.18.0

**Comment by attilah** [comment]
@berenddeboer it is related to #3096 as the CLI does not expect any additional unsupported/unhandled files to be present under the root it manages.

**Comment by kaustavghosh06** [comment]
Closing this issue as we're tracking this as a part of #3096
In the meanwhile you can take a look at the recommendation by @attilah out here - https://github.com/aws-amplify/amplify-cli/issues/3096#issuecomment-570280657
