### ISSUE TITLE
How to upgrade AWS Amplify CLI?

### ISSUE THREAD

**Issue by duckjones** [aws-amplify/amplify-cli#3119]
**Which Category is your question related to?**
I'm running into issues with auth, I've incorporated an oauth flow, Google and Facebook logins, and a PostConfirmation lambda trigger. My auth template now has 67 parameters and won't push. As far as I can tell, this issue appears to have been resolved in version 1.11.0? But I can't seem to update past version 1.10.0. I can't figure out what the actual latest version is, from the Github repo, it appears to be 4.11.0, which I have. Any tips on updating? 

**Amplify CLI Version** 

v1.10.0

**What AWS Services are you utilizing?**
auth
api
hosting

**Provide additional details e.g. code snippets**
I'm referencing the issue in #1937 and the fix version from #2015

**Comment by nikhname** [comment]
Hi @duckjones, you can update the cli to the latest version by running the following command: 
npm install -g @aws-amplify/cli@latest
Please feel free to comment if you have further questions.

**Comment by duckjones** [comment]
I just realized the issue, not too long ago I had downgraded my node version for some compatibility testing on a different project, forgot to set it back to the latest. Once I did that, I was able to use npm to update amplify to the latest version.

**Comment by Haugf** [comment]
Hi I just fixed this I believe! What you need to do is go to your Backend/Auth/ directory and find your *.yaml file

From there search for the AWS::Lambda::Function service and change the runtime environment to nodejs12.x

Not sure why the default is node 8. I was running in so many circles trying to figure this out. Hope it helps
