### ISSUE TITLE
How to model connections when AppSync uses Aurora?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3120]
Hello,

Imagine I have a table called Likes and another one called Posts in my RDS database.
A Like is related with exactly one Post. And one Post is related with many likes. Then, in GraphQL I have this:

```
type Like {
	id: ID!
	createdAt: AWSTimestamp
	post: Post!
}

type Post {
	id: ID!
	text: String!
	createdAt: AWSTimestamp
}

type Query {
	getLikes: [Like]
}

schema {
  query: Query
}
```
In my app, I want this query:

```
query GetLikes {
  getLikes {
    id
    createdAt
    post {
      id
      createdAt
      text
    }  
  }
}
```

As you can see, that retrieves a list of likes, but at the same time, it retrieves a post per like.
Problem is, I don't know how to do that exactly when using Aurora. It seems that when using DynamoDB, we can use the directive @connection but I don't see any documentation about this when using Aurora.

Can you help me with this? How can I do it?

Thanks a lot.

**Comment by nikhname** [comment]
@Ricardo1980 Unfortunately we do not support one-to-many connections in the graphql schema with RDS databases. However you could consider creating the relationship in SQL by making the primary key of the Post table the secondary key of the Likes table.

**Comment by Ricardo1980** [comment]
@nikhname 
Thanks for reply.

My question was about 1 to 1 relationship. Is that possible? (One like has one post, or zero, no more)

What about 1 to many? Are you going to support that in the future?

Does this mean we don't have the GraphQL N+1 problem when using Amazon because, well, you removed the possibility to have it? 

One suggestion: If I had known that, I would not have used AWS. I would recommend to mention this in your documentation. It is very annoying spending time on a technology and then realise it is not properly implemented.

Thanks!

**Comment by kaustavghosh06** [comment]
@Ricardo1980 We use @connection's and @keys for DDB since it doesn't have features like RDS to model 1-many or many-many relationships. As @nikhname  mentioned, if you're using RDS, you can model your tables to support 1-1, 1-many or many-many relationships. Your recommendation or ask is not clear out here.

**Comment by Ricardo1980** [comment]
Thanks @kaustavghosh06 

OK, let me confirm this.
If I have this query (the data model is up there):

```
query GetLikes {
  getLikes {
    id
    createdAt
    post {
      id
      createdAt
      text
    }  
  }
}
```

In the request mapping vlt I have one SQL query that combines all that info and returns a list of rows, something like:

SELECT likeId, likeCreatedAt, postId, postCreatedAt, postText,... FROM.... (probably using a left join)

And in the response mapping vlt, I have to manually convert that to the proper hierarchy, something similar to this (probably the code is wrong but you get the idea):

```
#if($ctx.error)
    $utils.error($ctx.error.message, $ctx.error.type)
#end

#set($likes = $utils.rds.toJsonObject($ctx.result)[0])
#set($likesProcessed = [])
#foreach ($like in $likes)
    #set($postProcessed = {})
    $util.qr($postProcessed.put("id", $like.postId))
    $util.qr($postProcessed.put("createdAt", $like.postCreatedId))
	$util.qr($postProcessed.put("text", $postText))

	#set($likeProcessed = {})
	$util.qr($likeProcessed.put("id", $like.likeId))
	$util.qr($likeProcessed.put("createdAt", $like.likeCreatedAt))
	$util.qr($likeProcessed.put("post", $postProcessed))


	$util.qr($likesProcessed.add($likeProcessed))
#end

$util.toJson($likesProcessed)
```

Am I right?
If that is the case, clearly this is a workaround the although it works here, it does not allow me to release all the potential GraphQL has.
Does AWS know about this and will fix this in the future?

Thanks a lot.

**Comment by Ricardo1980** [comment]
Anyone?
@nikhname 
@kaustavghosh06 
Thanks!

**Comment by nikhname** [comment]
@Ricardo1980 Could you clarify what your SELECT statements look like in the request template?

```SQL
SELECT *
FROM `City` as `C`
JOIN `Event` as `E`
ON `C`.`id` = `E`.`cityId`
JOIN `Sport` as `S`
ON `S`.`id` = `E`.`sportId`
WHERE `C`.`id` = 1;

```

**Comment by nikhname** [comment]
@Ricardo1980 Could you clarify the SELECT statement you use in your request mapping template?

Could it be something like this?
```SQL
SELECT id, createdAt, ...
FROM `Likes` as `L`
JOIN `Post` as `P`
ON `Likes`.`id` = `P`.`likeId`
WHERE `C`.`id` = 1;
```

**Comment by Graig123git** [comment]
can the @auth directive be used with AppSync Auroura ?

**Comment by nikhname** [comment]
@Graig123git The @auth directive cannot be used with Aurora at this time but it is an enhancement we are looking into. Closing this issue due to lack of response on original topic but feel free to reopen/comment
