### ISSUE TITLE
IAM Auth - How to restrict @Auth to a particular IAM role. The document just says IAM

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#3121]
**Which Category is your question related to?**
AWS AppSync @auth 

**Amplify CLI Version** 

Not applicable

**What AWS Services are you utilizing?**
AWS AppSync GraphQL transform

How to restrict a particular IAM role to access AppSync API. In the example below as mentioned in the documentation, https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js  in GraphQL transform section

"
type Post @model @auth (rules: [{ allow: private }]) {
  id: ID!
  title: String
  owner: String
  secret: String
    @auth (rules: [{ allow: private, provider: iam, operations: [create, update] }])
}

In the example above the model is protected by Cognito User Pools by default and anyone with a valid JWT token can perform any operation on the Post type, but cannot update the secret field. The secret field can only be modified through the configured IAM policies, from a Lambda function for example."

However, how do I ensure that not any lambda function can update the secret field?  Ideally, the lambda function that is running with a specified IAM role - let's say "AllowAppSyncCall" only should be allowed to update the secret field.

How can I achieve this?

**Comment by kaustavghosh06** [comment]
@arkllc The IAM role should be specified on your Lambda function (in the execution role). If the Lambda doesn't have access to it (in your account) - then your API won't be able to call it. It's not possible to do the reverse.

**Comment by kaustavghosh06** [comment]
@arkllc Let me know if you have any other questions.

**Comment by arkllc** [comment]
Thanks @kaustavghosh06 This is good for now. However, something to consider is that for Cognito userPool or ever OIDC you do allow specific static groups or dynamic groups and I can annotate those in the schema. However for IAM I can not list a group (or a role in IAM terminology). So its a bit inconsistent. I think it would be good if the AppSync cli tries to extend the role in the @model too.
