### ISSUE TITLE
Using a Lambda function in place of a @model in GraphQL

### ISSUE THREAD

**Issue by mentoc3000** [aws-amplify/amplify-cli#3122]
I am attempting to use a Lambda function to supply data as part of an AppSync GraphQL endpoint. I don't want to store the data coming out of that external API, just an ID number, but I do want to use the GraphQL syntax to supply the only the fields that are needed. Essentially, I want to duplicate the capabilities of the `@connection` directive between a `@model` and a non-moal.

Below is a simplified example of what I'd like to achieve.

```graphql
type Car {
    id: ID!
    make: String
    model: String
}

type Driver @model {
    id: ID!
    name: String
    car: Car @function(name: "carsearch")
}
```

The `carsearch` Lambda function would take the carId and return the make and model of the car in the shape of the Car type. The Driver database would store the driver ID and the car ID and access use the `carsearch` function to get the car details. A query could be something such as:

```graphql
query GetDriver {
    getDriver(id: 123) {
        name
        car {
            make
       }
    }
}
```

I know that I could create a lambda function for each field of the Car type, but for many fields that would require many calls and be inefficient. I hope there is a way to do this such that the lambda function can retrieve all of the fields from the external API and AppSync can use only what is needed.

**Amplify CLI Version** 
3.11.0

**What AWS Services are you utilizing?**
AppSync, DynamoDB, Lambda, Cognito

**Comment by tgjorgoski** [comment]
The lambda can return the whole subset at once e.g.:
`return { make:"Toyota",  model: "Corolla" }`

And the lambda can access the fields of which are already resolved e.g.:
`const driverId = event.source.id`

About the car id... did you try if you can access it with:
`const carId = event.source.carId` ( the name of the field in DynamoDB  in the Driver table)

(Also not sure if you need to return that field from the lambda too, or it is not necessary, e.g.:
return { carId: carId, make:"Toyota",  model: "Corolla" }

**Comment by mentoc3000** [comment]
@tgjorgoski But wouldn't that require the following schema

```graphql
type Car {
    id: ID!
    make: String
    model: String
}

type Driver @model {
    id: ID!
    name: String
    carId: ID
}
```

and thus need two API calls to get all of the desired data?

**Comment by mentoc3000** [comment]
It looks like the best approach is to use a resolver pipeline to transform the request, allowing reuse of the getCar lambda resolver. The schema would look like this:

```graphql
type Car {
    id: ID!
    make: String
    model: String
}

type Driver @model {
    id: ID!
    name: String
    car: Car @function(name: "getCarId-${env}") @function(name: "getCar-${env}")
}

type Query {
    getCar(id: ID!): Car @function(name: "getCar-${env}")
}

input CreateDriver {
    id: ID!
    name: String
    carId: ID
}

input UpdateDriver {
    id: ID!
    name: String
    carId: ID
}
```

The custom `CreateDriver` and `UpdateDriver` would store `carId` in the DynamoDB instead of the `Car` itself. The lambda function `getCar` takes a carId and accesses the external API to return the `Car` data. `getCarId` would pull the carId from `event.source.carId` and pass it to `getCar`, allowing for good code reuse.

Now my only struggle is how to pass the carId from `getCarId` to `getCar`.

**Comment by LoganArnett** [comment]
@mentoc3000 curious to know if you resolved your last issue? I am looking to implement something similar and having some issues

**Comment by mentoc3000** [comment]
I did chain the two functions as I showed in this comment. The first function gets the car id

```js
exports.handler = function(event, context, callback) {
  const result = { carId: event.source.carId };
  callback(null, result);
};
```

which gets passed to the second function. The id input will be in two different places in the arguments depending on if it's called directly or via another function, so I checked both.

```js
exports.handler = async function getCar(event, context, callback) {
  var carId;
  if (event.arguments && event.arguments.id) {
    carId = event.arguments.id;
  } else if (event.prev.result && event.prev.result.carId) {
    carId = event.prev.result.carId;
  } else {
    return null;
  }
  ...
};
```

This was some time ago, so apologies if the solution is incomplete or has some errors.
