### ISSUE TITLE
API_KEY is not passed to lambda as a environment variable in mock mode

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3124]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I add API_KEY auth as an additional auth type to my API. When I start mock, the fake API_KEY is added to aws-exports.js, but in the lambda function process.env.API_KEY returns null
I wonder how you pass the API_KEY as environment variable in the example below
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

**Amplify CLI Version**
4.7.0

**To Reproduce**
1. Create an auth with API_KEY auth type
2. Add a lambda function and print process.env.API_KEY
3. Add the function as a resolver to an AppSync query.
4. amplify mock
5. Invoke the AppSync query

**Expected behavior**
process.env.API_KEY should contain the key value in aws-exports.js file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v8.11.1

**Additional context**
I hard code the key value in the lambda function as a workaround

**Comment by rweng** [comment]
For me, it is not only mock where this does not work, but also regular lamda functions.  I tried everything I can think of, from adding it to the stacks parameters, adding it to `backend-config.json -> function -> dependson` (where it just gets replaced when updating the function via the CLI), ... Looks to me right now, the only way to use graphql from a lamda function is either not use API_KEY authentication, or setting it manually :(

**Comment by gaochenyue** [comment]
API_KEY is for mock. When deploying in the cloud, use IAM, although it is not documented very well.

**Comment by kaustavghosh06** [comment]
@gaochenyue Are you accessing the Lambda function as a resolver for the AppSync API or are you invoking the AppSync API via a  Lambda function?

**Comment by gaochenyue** [comment]
@kaustavghosh06 We are doing both. Browser initiates the request from AppSync API 1 with a function resolver and the resolver function call AppSync API 2. The first request is Cognito auth and second request is API_KEY auth.

**Comment by kaustavghosh06** [comment]
For mock you can set your local process env variables to your API Key. Are you referring to the ability of setting the API_KEY as environment variables when giving access to a lambda function for an AppSync API?

**Comment by gaochenyue** [comment]
@kaustavghosh06 yes, could you please pass API KEY as an environment variable to function automatically when starting mock mode so I can have an env reference in the function, e.g. process.env.API_KEY

**Comment by kaustavghosh06** [comment]
@gaochenyue Yes we're tracking this as a feature request.

**Comment by escape-velocity-labs** [comment]
I'm having the same issue, any updates?

**Comment by gaochenyue** [comment]
@escape-velocity-labs IAM is supported with mock. API_KEY is not needed anymore unless you have other reasons to use API_KEY with mock

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.
