### ISSUE TITLE
Auth Rules not working

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#3127]
This is a simplified example, but it still doesn't work:

**Schema**

````
type User 
  @model 
  @auth(rules: [
    {allow: owner, ownerField: "id", operations: [read, update, create]},
    # {allow: groups, groups: ["Admins"], operations: [read, update, create]},
    # {allow: private, provider: userPools, operations: [read, create]},
    # {allow: private, provider: iam, operations: [read, update, create]},
    # {allow: public, provider: iam, operations: [read]},
  ])
{
  id: ID!

  balance: Int @auth(rules: [
    # {allow: groups, groups: ["Admins"], operations: [read, update, create]},
    # {allow: private, provider: iam, operations: [read, update, create]},
    {allow: owner, ownerField: "id", operations: [read]},
  ])
}
````

**Query**

````
const entry = useQuery(gql(`query GetUser($id: ID!) {
    getUser(id: $id) {
      id
      balance
    }
  }`), {variables: {id: !!user ? user.id : "<>"}});
````

the result is that the balance field is always null.

If I run the same query from AppSync console, it works as expected

**Comment by CodySwannGT** [comment]
Follow up. Even though this had nothing to do with mutations or subscriptions, adding the following "fixed" my problem

````
@model (subscriptions: { level: public }) 
````

Clearly that's still a bug, though.

**Comment by SwaySway** [comment]
Hello @CodySwannGT A few questions here
- What version of the CLI are you using?
- What is your default mode of authentication for API?
- Did you do the creation and query operations as the same user?

Using the schema you provided above I did the following

create a record as `user1`
```gql
mutation CreateUser {
  createUser(input: {
    id: "user1",
    balance: 111
  }) {
    id
    balance
  }
}
```
retrieve the record as `user1`
```gql
query GetUser {
  getUser(id: "user1"){
    id
    balance
  }
}
```
I am able to retrieve the record.

**Comment by CodySwannGT** [comment]
1. 4.6.0
2. cognito
3. yes

To be clear, I can retrieve the record, but the "balance" field is null

**Comment by SwaySway** [comment]
@CodySwannGT Can you provide the response resolver code for get user?

Should be located under:
`amplify/backend/api/<API_NAME>/build/resolvers/Query.getUser.res.vtl`

**Comment by CodySwannGT** [comment]
````
$util.toJson($ctx.result)
````

**Comment by SwaySway** [comment]
@CodySwannGT 
The other resolver code as well under `*/getUser.*.vtl`
And the code for user balance: `amplify/backend/api/rulez/build/resolvers/User.balance.res.vtl`

**Comment by CodySwannGT** [comment]
````
$util.toJson($context.source.balance)
````

Keep in mind, that's AFTER i made this change and it started working:

````
@model (subscriptions: { level: public }) 
````

**Comment by CodySwannGT** [comment]
I'm not sure this could be any more maddening.

Here's another example from schema.graphql:

````
type Redemption 
  @model (subscriptions: { level: public }) 
  @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [update, create]},
    {allow: private, provider: iam, operations: [update, create]},
    {allow: owner, ownerField: "redemptionUserId", operations: [update, create]},
  ])
{
  id: ID!
  createdAt: String
  updatedAt: String

  redemptionUserId: ID!
  redemptionPromotionId: ID!
  redemptionCampaignId: ID!

  promotion: Promotion @connection
}

type User 
  @model (subscriptions: { level: public }) 
  @auth(rules: [
    {allow: owner, ownerField: "id", operations: [update, create]},
    {allow: groups, groups: ["Admins"], operations: [update, create]},
    {allow: private, provider: iam, operations: [update, create]},
  ])
{
  id: ID!
  legacyId: String
  displayName: String
  createdAt: String
  updatedAt: String
  agreedToTermsAt: String
  notifyViaEmailOnAll: Boolean
  notifyViaPushOnAll: Boolean
  notifyViaEmailOnLongshot: Boolean
  notifyViaPushOnLongshot: Boolean
  notifyViaEmailOnTeam: Boolean
  notifyViaPushOnTeam: Boolean
  notifyViaEmailOnSport: Boolean
  notifyViaPushOnSport: Boolean
  agreedToCcTermsAt: String


  userSportId: ID
  userTeamId: ID

  sport: Sport @connection(name: "SportUsers", sortField: "createdAt")
  team: Team @connection(name: "TeamUsers", sortField: "createdAt")
}
````

Then if we run them in AppSync console:

[Redemptions](https://www.dropbox.com/s/1gz3hw3u6folzyl/Screenshot%202020-01-08%2008.34.45.png?dl=0)

[Users](https://www.dropbox.com/s/8itf04cjw92z83h/Screenshot%202020-01-08%2008.35.16.png?dl=0)

**Comment by SwaySway** [comment]
I tried to replicate this with v4.6 though I'm still able to create a user as 'user1' and retrieve that same record as 'user1' with the balance value not set to null.
> Keep in mind, that's AFTER i made this change and it started working:

If you remove this `subscriptions: public` do you still run into this issue?
If you can email, amplify-cli@amazon.com, `amplify/` folder I can take a look at what was generated.

This other schema you provided seems unrelated to the first.
Could you open a different issue for that?

**Comment by CodySwannGT** [comment]
Yes on both, but it might be a bit on the first request. We're up against a deadline on this project and had to hack around this issue, so it'll take some time to put it back the way it was.

**Comment by CodySwannGT** [comment]
@kaustavghosh06 - What was the resolution?

**Comment by kaustavghosh06** [comment]
@CodySwannGT I believe you opened up #3147 as requested by @SwaySway?

**Comment by CodySwannGT** [comment]
@kaustavghosh06  I did, but the original issue here has not be resolved from my standpoint. 

@SwaySway said he couldn't repro, but it was 100% reproducible on our end. I just don't have the schema right now because we had to hack a very non-solution into our code base to meet a deadline

**Comment by kaustavghosh06** [comment]
@CodySwannGT Okay, please send us the schema once you get time as requested and we'll look into it.

**Comment by CodySwannGT** [comment]
Just to confirm, per @SwaySway recommendation, **yes** if we change the following line:

````
@model (subscriptions: { level: public })
````

to

````
@model
````

The issue immediately returns and ``balance`` is again null.

I will send the amplify folder shortly

**Comment by CodySwannGT** [comment]
Welp. Literally did the same thing again. Added and removed the above line and the problem is gone.

I also upgraded to the latest CLI, so maybe that was it?
