### ISSUE TITLE
yarn global add fails

### ISSUE THREAD

**Issue by UnleashedMind** [aws-amplify/amplify-cli#3131]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
install the CLI globally using `yarn global add  @aws-amplify/cli` fails with the following message: 
```bash
error upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.16.2"
error Found incompatible module.
```

**Amplify CLI Version**
The latest version 4.11.0

**To Reproduce**
Run `yarn global add  @aws-amplify/cli`

**Expected behavior**
The Amplify CLI is installed without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Sierra version 10.12.6
 - Node Version. v10.16.2
 - yarn version: 1.21.1

**Additional context**

**Comment by smakinson** [comment]
I am seeing a similar issue, but in the build logs in Amplify console. Let me know if I should create a new 
issue or it can be answered here.

First the part that I think I have resolved, I was seeing: 
`The engine "node" is incompatible with this module. Expected version ">= 10.18.1". Got "10.16.0"`
and based on this: https://stackoverflow.com/questions/56444337/how-to-change-node-version-in-provision-step-in-amplify-console

I added `- nvm use 12` as the first thing under commands and that seems to fix that issue, my question is, is that the correct way to go about it?

and the error I have not yet resolved:
` The engine "yarn" is incompatible with this module. Expected version ">= 1.21.1". Got "1.16.0"`

I have tried setting an override for yarn in the "Live package updates" section but it doesn't seem to pick it up. Is that the correct way to go about it?

![Screen Shot 2020-04-14 at 12 57 16 PM](https://user-images.githubusercontent.com/16784/79253423-31223e80-7e51-11ea-8255-4485afbf8dbd.png)

Thank you!
