### ISSUE TITLE
Amplify fails when deploying UserPoolClientLambda

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#3136]
```
CREATE_FAILED UserPoolClientLambda                                                AWS::Lambda::Function      Tue Jan 07 2020 11:08:48 GMT+0300 (Moscow Standard Time) The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a402ec74-23f4-42df-b20d-f5f403ad4685)
```

Please bump version of the UserPoolClientLambda's runtime

**Comment by artyom-melnikov** [comment]
Updated in recent version

**Comment by sorokinvj** [comment]
Hey Artyom! What should I update in order to fix this? amplify cli use nodejs8 by default and I am having troubles initializing new projects with cli

**Comment by binarytide** [comment]
I'm getting this even after updating runtimes to `nodejs12.x` ```Following resources failed

Resource Name: UpdateRolesWithIDPFunction (AWS::Lambda::Function)
Event Type: create
Reason: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. ```

**Comment by kaustavghosh06** [comment]
@binarytide Are you using the latest version of the CLI? It used Node 10.x

**Comment by artyom-melnikov** [comment]
@sorokinvj You need yo update amplify to the recent version. Then after you'll do amplify init it will suggest you to update version of the auth lambda runtime

**Comment by sorokinvj** [comment]
> @sorokinvj You need yo update amplify to the recent version. Then after you'll do amplify init it will suggest you to update version of the auth lambda runtime

updated to 4.11.0 and everything fixed. Thanks!
