### ISSUE TITLE
Custom pipelineFunctions are not override generated ones

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#3137]
I have a couple of templates in `api/<...>/build/pipelineFunctions` folder. They are autogenerated. 

I copied one into `api/<...>/pipelineFunctions` and modified but it is not pushed (generated version is used instead of my own)

**Comment by SwaySway** [comment]
@artyom-melnikov Do the pipeline functions have the same name?

**Comment by AryanJ-NYC** [comment]
Even newly written `pipelineFunctions` aren't being copied into the `/build` folder.

**Comment by SwaySway** [comment]
Closing in favor of #4192 - The PR is listed in this issue as well.
