### ISSUE TITLE
Parameters: [sceneId, region, projectName, url] must have values

### ISSUE THREAD

**Issue by JoeShi** [aws-amplify/amplify-cli#3138]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When trying to remove an XR resource. Failed, and the CLI error message is
```
Parameters: [sceneId, region, projectName, url] must have values
```

**Amplify CLI Version**
4.10.0

**To Reproduce**
```
amplify init
amplify add auth
amplify push
# add two xr
amplify add xr
amplify add xr
# remove one xr resource
amplify remove xr
```

**Expected behavior**
Expected the resource XR can be removed.

**Screenshots**
![Screen Shot 2020-01-07 at 7 39 38 PM](https://user-images.githubusercontent.com/2173635/71893303-330ba000-3186-11ea-8680-ee1734bd5d98.png)
![Screen Shot 2020-01-07 at 7 39 51 PM](https://user-images.githubusercontent.com/2173635/71893307-356dfa00-3186-11ea-983e-78ad8990c730.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Node Version. v12.13.1

**Comment by kaustavghosh06** [comment]
@JoeShi can you check your `<project-path>/amplify/.config/local-env-info.json` and check your projectPath key and see if it's correct?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response. Please comment on this thread if you're still stuck on this issue.
