### ISSUE TITLE
amplify env remove <environmentName> asks to delete all environments instead of just one

### ISSUE THREAD

**Issue by KristineTrona** [aws-amplify/amplify-cli#3140]
**Describe the bug**
I currently have two environments:

```
| Environments |
| ------------ |
| test         |
| *develop     |
```
I am trying to remove test environment by running ``amplify env remove test``. The prompt I get is:

``? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files) ``

I thought this is the message you are supposed to get when writing ``amplify delete``, as it would wipe all environments from the cloud. ``amplify env remove test`` should only offer to remove all cloud resources for the 'test' environment.

**Amplify CLI Version**
4.11.0

**Expected behavior**
Running ``amplify env remove <env name>`` should only delete the specified environment instead of all project environments. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.12.0

**Comment by chrisfowler** [comment]
Am getting this same behaviour when trying to remove one of my environments. Has this bug been fixed? Am using 4.13.0 of CLI. Reluctant to proceed as do not want to delete all environments from the cloud.

```
❯ amplify env list

| Environments |
| ------------ |
| *dev         |
| staging      |
| prod         |
| develop      |

❯ amplify env remove develop
? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and w
ipe out all the local amplify resource files) No

❯ amplify --version
4.13.0
```

**Comment by kaustavghosh06** [comment]
@chrisfowler This was an issue with the wording of the message - not the functionality. The wording has has been fixed in the latest version of the CLI - 4.13.4

**Comment by chrisfowler** [comment]
@kaustavghosh06 Thank you for prompt response. 

Was worth a checking. Would hate to be the one to delete `prod`

**Comment by kaustavghosh06** [comment]
@chrisfowler Totally get it!

**Comment by jrweth** [comment]
@chrisfowler Having the same issue with the wording after upgrading to 4.13.4.  I realize it is just the message of the wording, but it still makes me nervous to proceed.

**Comment by chrisfowler** [comment]
@jrweth Yes. 4.13.4 doesn't appear to have the updated messaging. I did a test project and it only delete the env I requested, so proceeded with main project. All went well.
