### ISSUE TITLE
Strange behavior with auth transform

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#3147]
Example below:

````gql
type Redemption 
  @model (subscriptions: { level: public }) 
  @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [update, create]},
    {allow: private, provider: iam, operations: [update, create]},
    {allow: owner, ownerField: "redemptionUserId", operations: [update, create]},
  ])
{
  id: ID!
  createdAt: String
  updatedAt: String

  redemptionUserId: ID!
  redemptionPromotionId: ID!
  redemptionCampaignId: ID!

  promotion: Promotion @connection
}

type User 
  @model (subscriptions: { level: public }) 
  @auth(rules: [
    {allow: owner, ownerField: "id", operations: [update, create]},
    {allow: groups, groups: ["Admins"], operations: [update, create]},
    {allow: private, provider: iam, operations: [update, create]},
  ])
{
  id: ID!
  legacyId: String
  displayName: String
  createdAt: String
  updatedAt: String
  agreedToTermsAt: String
  notifyViaEmailOnAll: Boolean
  notifyViaPushOnAll: Boolean
  notifyViaEmailOnLongshot: Boolean
  notifyViaPushOnLongshot: Boolean
  notifyViaEmailOnTeam: Boolean
  notifyViaPushOnTeam: Boolean
  notifyViaEmailOnSport: Boolean
  notifyViaPushOnSport: Boolean
  agreedToCcTermsAt: String


  userSportId: ID
  userTeamId: ID

  sport: Sport @connection(name: "SportUsers", sortField: "createdAt")
  team: Team @connection(name: "TeamUsers", sortField: "createdAt")
}
````

Then if we run the generated queries in AppSync console:

[Redemptions](https://www.dropbox.com/s/1gz3hw3u6folzyl/Screenshot%202020-01-08%2008.34.45.png?dl=0) (Unauthorized)

[Users](https://www.dropbox.com/s/8itf04cjw92z83h/Screenshot%202020-01-08%2008.35.16.png?dl=0) (Works just fine)

Default auth is user pools. Secondary is IAM

**Comment by SwaySway** [comment]
Hello @CodySwannGT Are you still running into this issue?

I see that you are trying the redemptions query using iam auth, though in your schema those with iam are not granted auth access on read (get/list).

**Comment by CodySwannGT** [comment]
So I’m not sure. Unfortunately, we don’t have the luxury of waiting on fixes so we went another direction. 

As to your question, though, I’m 99% sure the docs say if you don’t specify who has read access then all have read access. 

The docs were very confusing on this point though so I could be wrong.

**Comment by SwaySway** [comment]
Yes though when using iam auth it grants access if it's specified.
In this case `{allow: private, provider: iam, operations: [update, create]},` creates policies for the authorized role to allow update and create mutations.

https://aws-amplify.github.io/docs/cli-toolchain/graphql#combining-authorization-rules

**Comment by kaustavghosh06** [comment]
@CodySwannGT Closing this issue. Please let me know if you have more questions around this.
