### ISSUE TITLE
owner subscriptions causing error: '...of type "String!" is required but not provided.'

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#3148]
Framework: Angular 8
Amplify Cli - fresh install today

The responses in regards to the issue that follows have not been useful at all, and i feel maybe I am not explaining well.

I have a messaging system (realtime chat) in which a a conversation (model) links a business and a user together and messages are stored as a connection within this conversation.

On the business website I was expecting to use Amplify subscriptions to implement a real time chat system, however I have been unable to do so using many approaches. 

I have implemented authentication rules and multiple owners so as a user generated message will still be streamed into the subscription, given the user will be the owner and not the business. If the business creates the message, then there is no problem as they are the owner. Hence I then followed the docs by creating an owners array which will have owner auth rules applied.

However the only way I can get the subscription to fire is by making the subscription public, which is not ideal.

Could one of the amazon team (@mikeparisstuff @kaustavghosh06 etc) perhaps give some pointers here on how I can achieve the firing of subscriptions.

The models:

Conversation:

```gql
type ConvoLink @model(subscriptions: null) {
  id: ID!
  status: String
  createdAt: Float!
  updatedAt: Float!
  messages: [Message] @connection(name: "ConvoMsgs", sortField: "createdAt")
  user: User @connection(name: "UserConversations")
  entity: Entity @connection(name: "EntityConversations")
}
```

The message

```gql
type Message @model
  @auth(rules: [
    { allow: owner },
    { allow: owner, ownerField: "owners" }
  ])
{
  id: ID!
  messageConversationId: ID!
  conversation: ConvoLink @connection(name: "ConvoMsgs")
  content: String!
  contentType: String
  author: String!
  entity: String!
  receiver: String!
  owner: String!
  owners: [String]!
  status: String
  createdAt: Float!
  updatedAt: Float!
}
```

This completed the push operation to the API, however on graphQL codegen, it fails to create the subsections with the following errors:

> .../Ariba/src/graphql/mutations.ts: Field "onCreateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onUpdateMessage" argument "owner" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onUpdateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onDeleteMessage" argument "owner" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onDeleteMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onCreateMessage" argument "owner" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onCreateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onUpdateMessage" argument "owner" of type "String!" is required but not provided.
> .../Ariba/src/graphql/mutations.ts: Field "onUpdateMessage" argument "owners" of type "String!" is required but not provided.

These seem to be warnings however as after, the API file displays the subscription I need:

```js
export const onCreateMessage = `subscription OnCreateMessage($owner: String!, $owners: String!) {
  onCreateMessage(owner: $owner, owners: $owners) {
    id
    messageConversationId
    conversation {
      id.....
```

And finally my angular service call:

```js
   this.amplify.api().graphql(graphqlOperation(onCreateMessage, { owner: id}))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

However it never fires, and the only time I have got it to fire is when I changed the subscriptions to public. 

This has been a blocker for weeks now, so any help would be great!

**Comment by SwaySway** [comment]
Hello @oliverandersencox 
In the provided schema there are two owner based rules
```gql
@auth(rules: [
    { allow: owner },
    { allow: owner, ownerField: "owners" }
  ])
```
Since owner is a required field for subscriptions, (based on the auth change to subscriptions view here: [authorizing subscriptions docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions))
An current owner is required for the `ownerField group: "owner"` and required to exist in the `ownerField: "owners"`.

>...
export const onCreateMessage = `subscription OnCreateMessage($owner: String!, $owners: String!) {
  onCreateMessage(owner: $owner, owners: $owners) {
...

The graphql  operation should contain the id for owner and owners
```js
 this.amplify.api().graphql(graphqlOperation(onCreateMessage, { owner: id, owners: id }))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

**Comment by oliverandersencox** [comment]
@SwaySway I updated the model and removed the standard owner field as its not needed and so we are left with just the owners field.

I then run exactly as you have expressed (the same way that the amplify guides explain) and still it never fires:

AND I am still getting these errors:

> .../Ariba/src/graphql/subscriptions.ts: Field "onUpdateBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onDeleteBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onCreateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onUpdateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onDeleteMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onCreateBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onUpdateBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onDeleteBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onCreateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onUpdateMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onDeleteMessage" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onCreateBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onUpdateBooking" argument "owners" of type "String!" is required but not provided.
> .../Ariba/src/graphql/subscriptions.ts: Field "onDeleteBooking" argument "owners" of type "String!" is required but not provided.

The function call:
```
console.log('DYNAMO STREAMS INITIALISED')
this.amplify.api().graphql(graphqlOperation(onCreateMessage, { owners: publisherId }))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

The subscriptions simply do not work when using owner fields which is ridiculous!

**Comment by SwaySway** [comment]
@oliverandersencox the operation has a requirement of two arguments `owner and owners`.
Did you try the following operation below?
```js
// onCreateMessage needs owner and owners
 this.amplify.api().graphql(graphqlOperation(
    onCreateMessage, { owner: id, owners: id }))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

**Comment by oliverandersencox** [comment]
@SwaySway Yes I tried that and it did not work. I passed in both the owner and owners and it never fires.

What I'm saying is I then update my model to reflect this: 

```
@auth(rules: [
    { allow: owner, ownerField: "owners" }
  ])
```

and then also tried this:

```
// onCreateMessage needs owner and owners
 this.amplify.api().graphql(graphqlOperation(
    onCreateMessage, { owners: id }))
      .subscribe((newMessage: any) => {
         console.log('NEW MESSAGE RECEIEVED');
         console.log(newMessage)
      }, 
      err => console.log(err))
```

None of them work. I have tried with other models and it seems any subscription with authentication simply does not get fired.

**Comment by oliverandersencox** [comment]
@SwaySway there arent any proper docs or much info on subscriptions, and I have asked for help from the AWS team numerous times

**Comment by SwaySway** [comment]
@oliverandersencox A few questions here

- If you try this from the api console does it give back the same result? 
 - to open console use `amplify console api`
- When you tried it with the following `@auth` rule did it give an error or did the subscription not go through?

**Comment by SwaySway** [comment]
Update
I was able to find the issue.
The argument for `owners` should be a list for the subscription operations.

**Comment by oliverandersencox** [comment]
@SwaySway 'The argument for owners should be a list for the subscription operations.' can you explain this:

I tried passing the owners as an array containing one of the owners, both and just the owner (not an array). None of them every fired when creating a message from my IOS app, in which the owner array is set to contain the IOS device user ID and the website amplify app user ID as the other owner (current user). 

I did notice however that if I pass an array to the subscription is always returns a 'Not authroized error'

```
:
path: ["onCreateMessage"]
data: null
errorType: "Unauthorized"
errorInfo: null
locations: Array(1)
0: {line: 2, column: 3, sourceName: null}
length: 1
__proto__: Array(0)
message: "Not Authorized to access onCreateMessage on type Subscription
```

It seems that if multiple owners are involved, the subscriptions simply do not work. Correct me if I'm wrong?

**Comment by oliverandersencox** [comment]
@SwaySway I presume the approach I'm trying to take is the sole reason for multiple owners.

User App 
- sends a message to the business App
- Message sets the owners as the user and the business app user (publisher)
- owners field - [userId, publisherId] so as both users are able to subscribe to onCreateMessage and effectively have realtime chat

Business App
- listens to onCreatemessage for all messages in which they are an owner and therefore in the owners array.

**Comment by kaustavghosh06** [comment]
We released a fix for this with v4.14.1. Please let us know if you're still stuck with this issue.

**Comment by slatemates** [comment]
We are facing the same issue . If the subscriber is one of the "owners" and we subscribe using
onCreate(owners:id) , it doesnt work.  As a workaround we modified the onCreate(owners : String) to
onCreate(owners :[String]). Now we must the whole list owners to subscribe to any changes on the object.

**Comment by slatemates** [comment]
[https://github.com/aws-amplify/amplify-cli/issues/2512](url) . This might help

**Comment by MontoyaAndres** [comment]
I'm having this issue with an existing table created

https://github.com/aws-amplify/amplify-js/discussions/5441

**Comment by oliverandersencox** [comment]
@kaustavghosh06 you claim this is fixed? I am having no luck again after reattempting to try and get this implemented. 

The generated query:

```
export const onCreateBooking = /* GraphQL */ `
  subscription OnCreateBooking($owners: String) {
    onCreateBooking(owners: $owners) {
      id...
```

and then my code:

  ```
private listenForNewBookings(): void {
    console.log('BOOKING LISTENER ENABLED');
    const stream = this.amplify.api().graphql(graphqlOperation(onCreateBooking, { owners: <OWNER HERE>}))
    console.log(typeof(stream))
    
    stream.subscribe({
      next: (evt) =>{
        console.log('NEW BOOKING MADE WOOOOO');
        console.log(evt)
      }
    });
  }
```

This never emits. Surely this is resolved by now?

**Comment by oliverandersencox** [comment]
@SwaySway see above please

**Comment by oliverandersencox** [comment]
After reading other posts I have also tried this, which also did not work.

```
const stream: Observable<any> = this.amplify.api().graphql(graphqlOperation(onCreateBooking, { owners: OWNER HERE }))
    stream.subscribe((evt) => {
      console.log('NEW BOOKING EVENTS');
      console.log(evt)
    })
```

**Comment by oliverandersencox** [comment]
In the network tab the initial graph requests gets what seems to be the correct resonse, which is even more consuing as to why the subscription never emits:

{"extensions":{"subscription":{"mqttConnections":[{"url":"wss://a....","topics":["4125../onCreateBooking/240.."],"client":"af6...."}],"newSubscriptions":{"onCreateBooking":{"topic":"412541719...","expireTime":1589727672000}}}},"data":{"onCreateBooking":null}}

**Comment by oliverandersencox** [comment]
@kaustavghosh06 still nothing when trying all the solutions above - it simply wont detect the booking creation. Any help would be great

**Comment by oliverandersencox** [comment]
@kaustavghosh06 i've come to revisit this again, and still trying all the above approaches the subscription never emits!
