### ISSUE TITLE
Amplify Cognito: No Current User

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3151]
**Which Category is your question related to?**
Amplify, Appsync, GraphQl, Lambda

**Amplify CLI Version** 
4.6.0

**What AWS Services are you utilizing?**
Cognito Authentication, API_KEY Authentication, Lambda

**Provide additional details e.g. code snippets**
I have Cognito Authentication enabled in my app and I am calling a Lambda function from my Angular Client.
What I want t do is that I want to call Graphql from the Lambda function?
To do so, I have configured aws-amplify inside my lambda function and have passed the configurations to the "Amplify.default.configure" method.
But when I run the query, it says "No current user". Does anyone know how to configure amplify in Lambda function with the user which called the Lambda function?

For now to work, I have added Multi Auth to allow access to Graphql using the appsync_api_key and I have hardcoded that inside the lambda function but I want to get rid of that ASAP.

**Comment by rehanbabertkxel** [comment]
@kaustavghosh06 , can you help?

**Comment by kaustavghosh06** [comment]
@rehanbabertkxel Amplify JS doesn't have NodeJS support yet and supports only frontend frameworks for now (Angular in your case).  Please take a look at - https://aws-amplify.github.io/docs/js/angular

You can make a call to your GraphQL endpoint which will call a function which can have access to your Cognito User Pool (and you would probably have to use the AWS JS SDK for your cognito requests).

**Comment by rehanbabertkxel** [comment]
@kaustavghosh06 , how would the "Lambda function" have access to the Cognito User Pool? How can I extract the required information from the process.env to access the User Pool?
Can you refer a good example for that?

**Comment by kaustavghosh06** [comment]
If you run `amplify function update` and go through the flow, you should be able to give access to your cognito user pool - created using amplify. For more info - you can take a look at - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#functions-examples
