### ISSUE TITLE
Has domain been removed from aws-exports.js?

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-cli#3155]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

The first time I generate an `auth` configuration it had `domain` included like this:

```
    "oauth": {
        "domain": "testa311c-7a11c-dev.auth.us-east-1.amazoncognito.com",
...
        ],

```

However it's no longer included in `aws-exports`after I updated the CLI.  Has this been removed?

We can login to the AWS Console to get it, but it was very convenient to see it in the `aws-exports` file ...

**Comment by fireflysemantics** [comment]
I think I may know what happened here and I'm testing it out now.

For one I accidentally deleted the entire domain prefix when running the `amplify add auth` and I think this caused the cloudformation to be created without a domain.

So maybe put a validation check in there to make sure that it cannot happen.

Upon realizing this I ran `amplify delete` and nuked everything.

I think when we do this `aws-exports.js` is not deleted ... so the old configuration was still hanging around after running `amplify add auth` again.

These are just my hunches ... I'm testing it all out now.

**Comment by fireflysemantics** [comment]
OK `domain` is back.  I think the problem there was that I deleted the prefix accidentally when asked for it.  I thought the CLI would just put in a random one.

Pretty sure the second part of the problem is that when running `amplify delete` it does not delete `aws-exports.js` so even if we rerun `amplify add auth` the old configuration is not updated ... hence I still did not see domain ...

**Comment by ammarkarachi** [comment]
@fireflysemantics The `aws-exports.js` deletion is being worked on right now. I will close this issue for now. Feel free to reach out.
