### ISSUE TITLE
Extensible GraphQL "groupsField" auth using concatenation in rule

### ISSUE THREAD

**Issue by paulsson** [aws-amplify/amplify-cli#3157]
**Multi-tenancy context scenario:**
3 GraphQL types:
Business
Location
User

A Business has many Locations (1 to many relationship)
A Business has many Users (1 to many relationship)
Location <-> User (many to many relationship)

GraphQL schema types:
```
type Business
  @model
  @auth(rules: [
    # allows BusinessAdmins to read and update if the calling user is assigned to the Business
    { allow: groups, groupsField: "id", operations: [read, update] }
  ]) {
  id: ID!
  name: String!
  locations: [Location] @connection(keyName: "byBusiness", fields: ["id"])
  users: [User] @connection(keyName: "byBusiness", fields: ["id"])
}

type Location
  @model
  @auth(rules: [
    # grants BusinessAdmins all operations if the calling user is assigned to the same Business
    { allow: groups, groupsField: "businessID" }
    # allows LocationAdmins to read and update if the calling user is assigned to the same Location
    { allow: groups, groupsField: "id", operations: [read, update] }
  ])
  @key(name: "byBusiness", fields: ["businessID", "name"]) {
  id: ID!
  businessID: ID!
  name: String!
  business: Business! @connection(fields: ["businessID"])
  users: [LocationUser] @connection(keyName: "byLocation", fields: ["id"])
}

type User
  @model
  @auth(rules: [
    # grants BusinessAdmins all operations if the calling user is assigned to the same Business
    { allow: groups, groupsField: "businessID" }
  ])
  @key(name: "byBusiness", fields: ["businessID","emailAddress"]) {
  # id is the Cognito User Pool user sub
  id: ID!
  businessID: ID!
  emailAddress: AWSEmail!
  # role holds the value determining whether the user is a BusinessAdmin or LocationAdmin
  role: Role
  business: Business! @connection(fields: ["businessID"])
  locations: [LocationUser] @connection(keyName: "byUser", fields: ["id"])
}

enum Role {
  BUSINESS_ADMIN
  LOCATION_ADMIN
}

type LocationUser
  @model
  @auth(rules: [
    # allows LocationAdmins to create, read, update, and delete if the calling user is assigned to the same Location
    { allow: groups, groupsField: "locationID" }
  ])
  @key(name: "byLocation", fields: ["locationID", "userID"])
  @key(name: "byUser", fields: ["userID", "locationID"]) {
  id: ID!
  locationID: ID!
  userID: ID!
  location: Location! @connection(fields: ["locationID"])
  user: User! @connection(fields: ["userID"])
}
```

For RBAC (Role Based Access Control) we have the concept of a "BusinessAdmin" and a "LocationAdmin".
A "BusinessAdmin" has CRUD permissions for the Business and all of its associated Locations.
A "LocationAdmin" has CRUD permissions for the Locations that the User is associated with and read-only permissions to the Business that they belong to.
The best way to do this is to base the auth rules off of the “id” of the Business and Location. I am able to add the Business and Location ids nice and easily to the user’s JWT token thanks to the great work by the Amplify team on the "AuthPreTokenGeneration" Cognito trigger.

**Is your feature request related to a problem? Please describe.**
My auth rules work great for the "BusinesAdmin" scenario since:
* each Business has an ‘id’ which I can use in an auth rule to grant BusinessAdmin type permissions
* each Location record has a "businessID" which I can use in an auth rule to grant BusinessAdmin type permissions since a BusinessAdmin should be able to manage all Locations of a Business.

**The problem** I am having is allowing a User with the "LocationAdmin" role to have read-only access up the relationship hierarchy to “their” Business. I know what Business a User is assigned to but I am already using the Business ‘id’ in my auth rule to grant BusinessAdmin permissions on my Business type and I don’t have another field in my Business type to define the LocationAdmin auth rule with.

**Describe the solution you'd like**
It would be amazing to have the ability to extend a “groupsField” in auth rules by simply concatenating a string to the “groupsField” in the auth rule. This would allow the capability to define many different auth rules based on a single type’s field.

**Example** with made up syntax but hopefully it demonstrates the idea:
```
type Business
  @model
  @auth(rules: [
    # allows BusinessAdmins to read and update if the calling user is assigned to the Business
    { allow: groups, groupsField: "id", operations: [read, update] }
    # allows LocationAdmins to read if the calling user is assigned to the same Business
    { allow: groups, Fn::Join ["-" [groupsField: "id", "read"]], operations: [read] }
  ]) {
  id: ID!
  name: String!
  locations: [Location] @connection(keyName: "byBusiness", fields: ["id"])
  users: [User] @connection(keyName: "byBusiness", fields: ["id"])
}
```
Then in my AuthPreTokenGeneration lambda for LocationAdmin users I could just concatenate “-read” to the Business id before I add it as a group in the JWT group claims. This would place a group into the group claims that matches the auth rule demonstrated above.

**Describe alternatives you've considered**
A much less ideal solution would be to setup a DynamoDB event trigger that would fire on create/insert of items into a Table that would then have to add another field to the DynamoDB record whose value would be the concatenation of the record id + “-read” in order to get this use case and design to work.
I would have to do this for every table that has a similar scenario where CRUD actions need to be granted to certain users and then where read-only permissions need to be granted to other users.

**Additional context**
Maybe there is another way to do this, but I haven’t been able to find anything in the docs or through my testing. Any and all help is much appreciated!

Cheers!
Erik

**Comment by RossWilliams** [comment]
Have you looked at turning off top-level read access to Business? Force all reads to go from User -> Business or User -> Location -> Business. Use field auth rules to only allow owners of User to read Business from User, and LocationAdmins to read from Location to Business. Then you free up your id property for mutation protection. on the Business model itself. I'm having a hard time reasoning about all your auth rules, but the general principal of turning off top level queries of the model and enforcing read access by restricting access to either connecting models or through field auth rules should get you to your solution.

Also FYI, you aren't protected Business create or delete operations. This is unlikely to be what you want.

**Comment by paulsson** [comment]
Thanks Ross! I have not tried field auth rules yet, but will give them a try and report back.
I should be able to test this out later today or tomorrow.

Thanks,
Erik

**Comment by paulsson** [comment]
@RossWilliams do I have to turn off top-level read access to Business, @model(queries: null), in order for this to work?
We have the concept of a "root admin" or "super admin" who must be able to manage all Businesses (including list and get). If I turn of top-level read access on Business my "root admin" users will no longer be able to call "listBusinesses".
Here is what I tried but I am still getting unauth "Not Authorized to access business on type User".
```
type User
  @model
  @auth(rules: [
    { allow: owner, ownerField: "id", operations: [read, update] }
    # grants 'root admin' to manage all users
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
    # grants BusinessAdmins all operations if the calling user is assigned to the same Business
    { allow: groups, groupsField: "businessID", operations: [create, read, update, delete] }
  ])
  @key(name: "byBusiness", fields: ["businessID","emailAddress"]) {
  # id is the Cognito User Pool user sub
  id: ID!
  businessID: ID!
  emailAddress: AWSEmail!
  # role holds the value determining whether the user is a BusinessAdmin or LocationAdmin
  role: Role
  business: Business! @connection(fields: ["businessID"])
    @auth(rules: [
      { allow: owner, ownerField: "id", operations: [read] }
    ])
  locations: [LocationUser] @connection(keyName: "byUser", fields: ["id"])
}

type Business
  @model
  @auth(rules: [
    # grants 'root admin' to manage all businesses
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
    # allows BusinessAdmins to update if the calling user is assigned to the Business
    { allow: groups, groupsField: "id", operations: [update] }
  ]) {
  id: ID!
  name: String!
  locations: [Location] @connection(keyName: "byBusiness", fields: ["id"])
  users: [User] @connection(keyName: "byBusiness", fields: ["id"])
}
```

**Comment by attilah** [comment]
@paulsson reading up on the problem you've and the proposed solution is mainly two parts, one is a system design question the other one is a proposed change to the CLI, so I answer separately.

About the proposed changes: I see the use case but it is too specific to make it into the CLI native directives at this point, but I'll mark this issue as an enhancement to keep it around it more customers are requiring similar solutions then they can find it and express their need.

About the system design: In addition to the suggestion that @RossWilliams presented I had a different idea, not sure if that would work for you: In your PreTokenGeneration Lambda, what if you'd add one more claim to the token to represent the Location related group membership, so in your groups ```@auth``` rule you'd use a different "field" from the token of the authenticated user?

**Comment by paulsson** [comment]
@attilah @RossWilliams I have finally gotten back to more testing on my use case and your suggestions.

Amplify CLI version:
```
amplify -v
4.13.2
```
The 2 main GraphQL schema type definitions from when I attempted the suggested field level @auth rule for User.business are at the end of this reply.

@attilah can you elaborate on your suggestion? I am already adding the Location IDs into the JWT indicating Location membership. My main problem is I need Users who are members of a Business and can be either be a BusinessAdmin or not a BusinessAdmin to have different @auth rules. All Users who are members of a Business should have read access but only the BusinessAdmin group (dynamic group, value is the Business ID) should have mutate access. I am using the Business ID as the group field for BusinessAdmin group membership and there is not another field on Business that I can use for a "read" @auth rule. 

**Recap:** this Amplify and GraphQL service is for a multi-tenant SaaS product where each model type "Business" is a different customer of our SaaS product. Each Business's data/information must only be accessible by Users who are members of that Business. As the service provider and owner of this product, we must have "Admin" rights to list, query, and administer (mutate) every Business that uses our product.
This seems like a very common scenario.

For our model User we have 3 groups / roles of users:
* **Admin** (static group) Must be able to read (get and list) all Businesses and mutate all Businesses.
* **BusinessAdmin** (dynamic group added by PreTokenGenerationFunction, value of the group in the JWT token is the ID of the model Business). BusinessAdmins need CRUD access to ONLY the Business they belong to.
* **LocationAdmin** (dynamic group added by PreTokenGenerationFunction, value of the group in the JWT token is the ID of the model Location). LocationAdmins need to have read access to ONLY the Business they belong to.

@RossWilliams suggestion of adding @auth at the field level for "User.business" seemed promising but this won't work for me because the top-level @auth rules on the model Business type are still applied even when entry point is User. We must have top-level read access turned on for Business so that our "Admin" static group of Users can listBusinesses and getBusiness for all Businesses.

The 2 main GraphQL schema type definitions from when I attempted the suggested field level @auth rule for User.business are at the end of this reply. It fails with unauthorized and reviewing the .vtl files for User.business I can see why.

I can see the GraphQL transform is generating velocity template (.vtl) files for both:
* **User.business.req**: contains the userPools authMode checks for the field level @auth rules on User.business field. Auth check in this req template passes and runs the DynamoDB query.
* **User.business.res**:  contains ALL the @auth rule checks placed on the top-level Business type even though my entry point is not Business. This isn't necessary or desired (at least for my use case) because I want only the @auth rules applied from my entry point of User and to only use the field level @auth rules on User.business for accessing a Business from User. I still get unauthorized error because of this.
I can post these .vtl files if that will help understand what I described above.

```
type User
  @model(subscriptions: { level: off })
  @auth(rules: [
    # allow the requesting user to read and update their own record
    { allow: owner, ownerField: "id", operations: [read, update] }
    # allow users in the "Admin" static group all CRUD operations
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
    # grants BusinessAdmins create,read,update if the calling user is assigned to the same Business. This allows self-service of Users within own Business.
    { allow: groups, groupsField: "businessID", operations: [create, read, update] }
  ])
  @key(name: "byBusiness", fields: ["businessID","emailAddress"]) {
  # id is the Cognito User Pool user sub
  id: ID!
  businessID: ID!
  emailAddress: AWSEmail!
  # role holds the value determining whether the user is a BusinessAdmin or LocationAdmin
  role: Role
  business: Business!
    @connection(fields: ["businessID"])
    @auth(rules: [
      { allow: owner, ownerField: "id", operations: [read] }
    ])
  locations: [LocationUser] @connection(keyName: "byUser", fields: ["id"])
}

type Business
  @model
  @auth(rules: [
    # grants 'root admin' to manage all businesses
    { allow: groups, groups: ["Admin"], operations: [create, read, update, delete] }
    # allows BusinessAdmins to update if the calling user is assigned to the Business
    { allow: groups, groupsField: "id", operations: [read, update] }
  ]) {
  id: ID!
  name: String!
  locations: [Location] @connection(keyName: "byBusiness", fields: ["id"])
  users: [User] @connection(keyName: "byBusiness", fields: ["id"])
}

enum Role {
  ORG_ADMIN
  LOC_ADMIN
}
```
I can open an AWS support ticket referencing this github issue if that will help.
Please let me know if anything is unclear.

Thanks!
Erik

**Comment by attilah** [comment]
One thing I'd try is to turn this auth logic you want into VTL code and implement since it seems you've all the data you need, but the @auth rules cannot do what you like, which is a custom logic for your case, a  custom resolver could solve it.

**Comment by paulsson** [comment]
I solved this using custom claims added by my cognito pre-token generation lambda trigger and using 'groupClaim' in my '@auth' rules to reference my custom claims.
This requires you to pass the id_token instead of the access_token JWT in the 'Authorization' header unfortunately, but not a big deal. Just another hoop to jump through.
This doesn't require any custom resolvers to be written at least.
It is ashamed that https://github.com/aws-amplify/amplify-cli/issues/317 has gotten no traction yet, as this would solve so many peoples problems to support multi-tenancy of customer data instead of having to slog through so much work and trouble shooting down in the weeds.
You can see just google searching 'amplify api auth multi tenancy' how many people are having this issue and hacking around it, for example:
https://medium.com/@dantasfiles/multi-tenant-aws-amplify-cc3252c4def4

If we had the and/or functionality for defining '@auth' rules this would be super straight forward!
