### ISSUE TITLE
Local AppSync and DynamoDB

### ISSUE THREAD

**Issue by LpmRaven** [aws-amplify/amplify-cli#3169]
Is there a way of using Amplify to set up a local version of my AppSync and DynamoDB? It is slow and becoming costly to develop against my cloud services. I haven't seen any documentation on this topic, did I miss it?

**Comment by ammarkarachi** [comment]
Hi @LpmRaven , we have a way to run a mock without pushing to cloud services. You can do this running `amplify mock api` and `amplify mock storage`. More [info](https://aws-amplify.github.io/docs/cli-toolchain/quickstart?sdk=js#mocking-and-testing)

**Comment by LpmRaven** [comment]
@ammarkarachi Thanks
