### ISSUE TITLE
S3 bucket name is not pushed to the lambda environment variable 

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3174]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created a function which depends on a S3 storage. I set the dependency with "amplify update function" and selected the storage as dependency. The cloud formation template got updated with the environment variable "STORAGE_APP_BUCKETNAME" which references the parameter storageappBucketName. After I successfully run "amplify push", checked the environment variable on the lambda console and found that the STORAGE_APP_BUCKETNAME was not set to the correct bucket name. Instead it is set to the default value storageappBucketName

**Amplify CLI Version**
4.12.0

**To Reproduce**
1. Amplify add storage
2. Amplify add function and set the storage as dependency
3. Amplify push

**Expected behavior**
The lambda environment variable STORAGE_APP_BUCKETNAME should be set to the S3 bucket name

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 10

**Additional context**
The lambda role policy is using the wrong bucket name as well
{
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                **_"arn:aws:s3:::storageappBucketName/*"_**
            ],
            "Effect": "Allow"
        }

**Comment by kaustavghosh06** [comment]
@gaochenyue Did yolu remove your Storage resources and added a new one?

**Comment by kaustavghosh06** [comment]
If you removed and added a new storage bucket, you can run `amplify update function` to select the new storage resource, and that'll rectify the Lambda policies.

**Comment by gaochenyue** [comment]
@kaustavghosh06 I tried to remove the storage, recreate and update function dependency to select the new storage, but it still pushed the default bucket name to environment variable

**Comment by ohlr** [comment]
@kaustavghosh06 can you reopen?
I added storage and afterwards run `amplify update function` to give lambda permission to s3.
But the env variable is the default one.

I believe this is a bug.
