### ISSUE TITLE
Export with name #### is already exported by stack #### since merge from nodejs 8.10 to 10.x

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-cli#3175]
**Describe the bug**
Since updating from nodejs8.10 to nodejs 10.x I now get the following error running amplify serve

Export with name #### is already exported by stack ####

**Amplify CLI Version**
4.12.0

**To Reproduce**
Edited and replaced all instances throughout the project... 
"Runtime": "nodejs8.10", to "Runtime": "nodejs10.x"

**Expected behavior**
A succesful push/serve.

**Desktop (please complete the following information):**
Mac
Node Version. 10.14.1

**Comment by nikhname** [comment]
Could you provide the error you see when running amplify serve?
If you have resources that were created before amplify version 4.10.0, they must be updated manually. Please refer to this section of the docs: https://aws-amplify.github.io/docs/cli/lambda-node-version-update#node-version-update

**Comment by nikhname** [comment]
@michaelcuneo Did you run amplify init since migrating to nodejs 10.x ?

**Comment by michaelcuneo** [comment]
I have tried both updating the project manually, and updating to the latest version of the cli, and updating automatically, and/or manually. Both seem to be an issue. For now I've reverted to an earlier version of my project that doesn't have any API changes so that I can continue working until I find a solution.

**Comment by kaustavghosh06** [comment]
@michaelcuneo Were you able to make this work?
