### ISSUE TITLE
Error uploading JSON in Mock Storage

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3177]
**Which Category is your question related to?**
Storage

**Amplify CLI Version** 
4.6.0

**What AWS Services are you utilizing?**
S3, Mocked S3

**Provide additional details e.g. code snippets**
I am trying to upload a JSON file to the mocked storage at 'localhost:2005' and the file is uploaded correctly and I get the key to the file in response. But when I try to download the file from the mocked storage, it is a corrupted file:

Code to download:

const result: any = await Storage.get(`key`, { level: 'public', download: true });
const data = await new Response(result.Body).json();

But when I do the same with the original bucket on S3 without "amplify mock". Both the upload and download works perfectly.

Can anyone tell what could be the issue with mocked storage?
I am not even getting any errors.

Code for Uploading JSON file:

const config = {
      contentType: 'application/json',
      level: 'public'
    };
await Amplify.Storage.put('key', JSON.stringify(object), config);

**Comment by rehanbabertkxel** [comment]
@kaustavghosh06 , can you please help.

**Comment by ammarkarachi** [comment]
@rehanbabertkxel Can you print the string and see what the string looks like before you parse it?

**Comment by rehanbabertkxel** [comment]
@nikhname , @ammarkarachi , the object before stringify is:

{ __typename: 'UserData',
  id: 'a9a394ea-feaa-4bf9-a612-d80aa38e6b31',
  name: 'Test Mock Storage',
  users: null,
  completionStatus: null,
  parentId: null,
  time:
   { __typename: 'Time',
     cDate: 1578985237505,
     mDate: null,
     rDate: null,
     freq: null },
  Type: 'ROOT',
  Manager: null,
  logo:
   { __typename: 'S3File',
     id: null,
     name: 'logo.png',
     names: null,
     typeId: 'a9a394ea-feaa-4bf9-a612-d80aa38e6b31',
     fileType: 'LOGO',
     contentType: 'image/png',
     length: null,
     key: 'a9a394ea-feaa-4bf9-a612-d80aa38e6b31/LOGO/logo.png.png' },
  integrate: null,
  Setting:
   { __typename: 'Setting',
     dueInDays: null,
     fre: 'ANN',
     sur: 'high',
     art: null,
     access: 'PHYSICAL' },
  createdBy: null,
  createdAt: 1578985237505,
  modifiedBy: null,
  modifiedAt: 1578985237505,
  Details: null,
  effect: 'HEALTH' }

After JSON.stringify:

{"__typename":"UserData","id":"a9a394ea-feaa-4bf9-a612-d80aa38e6b31","name":"Test Mock Storage","users":null,"completionStatus":null,"parentId":null,"time":{"__typename":"Time","cDate":1578985237505,"mDate":null,"rDate":null,"freq":null},"Type":"ROOT","Manager":null,"logo":{"__typename":"S3File","id":null,"name":"logo.png","names":null,"typeId":"a9a394ea-feaa-4bf9-a612-d80aa38e6b31","fileType":"LOGO","contentType":"image/png","length":null,"key":"a9a394ea-feaa-4bf9-a612-d80aa38e6b31/LOGO/logo.png.png"},"integrate":null,"Setting":{"__typename":"Setting","dueInDays":null,"fre":"ANN","sur":"high","art":null,"access":"PHYSICAL"},"createdBy":null,"createdAt":1578985237505,"modifiedBy":null,"modifiedAt":1578985237505,"Details":null,"effect":"HEALTH"}

Please let me know if you need anything else.

**Comment by nikhname** [comment]
@rehanbabertkxel What code are you using to download the JSON file? Are you able to open the corrupted file at all?

**Comment by bilalashraf1710** [comment]
@nikhname please find the code for download in my post question.

**Comment by rehanbabertkxel** [comment]
@nikhname please find the code for download in the question above.

**Comment by rehanbabertkxel** [comment]
@nikhname , any update on this?

**Comment by rehanbabertkxel** [comment]
@akshbhu , in which amplify version is this expected to work?
