### ISSUE TITLE
JSON validation in amplify mock is less strict than AppSync

### ISSUE THREAD

**Issue by ThijsTyZ** [aws-amplify/amplify-cli#3180]
**Describe the bug**
When running `amplify mock` your request template can contain invalid JSON. Like keys without quotes or trailing comma's. But if you deploy this to AppSync it will break. E.g. `amplify mock` works fine when your request template (Query.getX.req.vtl) looks like this:
```
{
   x: 1,
}
```
Note that `x` has no quotes and there is a trailing comma. After deploying this, it will fail on AppSync.

**Amplify CLI Version**
3.9.0

**To Reproduce**
Remove the quotes of a prop in the request template or add a trailing comma. Test your project with `amplify mock`, that still works. Now run `amplify push`. It will fail online.

**Expected behavior**
If it fails online, it should also fail using `amplify mock`

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version.  v12.13.1

**Comment by ThijsTyZ** [comment]
I want to state that this is a really annoying issue. The `amplify mock` feature cannot be trust. It looks like everything works fine during development, but after deployment it's broken.

So I hope you can find a solution for this issue shortly.

**Comment by ThijsTyZ** [comment]
Just discovered an other issue which is related I think. The following response mapping template **works** with `amplify mock` but breaks when you deploy it:

```
#if($ctx.result && $ctx.result.error)
  $utils.error($ctx.result.error.message, $ctx.result.error.status, $ctx.result.error.code, $ctx.result.error.description))
#else
  $util.toJson($ctx.prev.result)
#end
```
To get this working after push you need to have quotes:
```
#if($ctx.result && $ctx.result.error)
  $utils.error("$ctx.result.error.message", "$ctx.result.error.status", "$ctx.result.error.code", "$ctx.result.error.description"))
#else
  $util.toJson($ctx.prev.result)
#end
```

**Comment by berenddeboer** [comment]
@ThijsTyZ I suggest you always wrap stuff coming from `$context` in `$util.toJson()`.

**Comment by ElvenMonky** [comment]
In fact AppSync does support JSON5 (at least trailing comma). So fix above just broke parsing of some of our VTL that did use this feature.

Any considerations to reverse this `fix`?

**Comment by ElvenMonky** [comment]
Gotcha, makes sense. I think it's fine for us to stick to valid JSON for the time being.
