### ISSUE TITLE
Fine grain Access to GraphQL with IAM and Userpool Groups

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-cli#3182]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
GraphQL

**Amplify CLI Version** 
4.11.0

**What AWS Services are you utilizing?**
Appsync, Cognito, IAM

**Provide additional details e.g. code snippets**
Hi, i'm trying to create an app where users who sign up and choose to be a provider get assigned the provider role and have access to create posts. Once a post is created only the owner of the post is allowed to edit it and update/delete it. I should note Admins also are allowed to do this. After some playing around with GraphQL and doing research, it seems very difficult to find a proper way to do this. Some people say to add inline policies to unauth and authed classes. (I will allow unauthed users to see the posts as well) so they can access the graphql mutations and queries. Unfortunately it's not all so clear and the documentation lacks the information I need to solve it, so I come here. 

This is really important issue to me because if it's the case that I can't create the project how its supposed to be and i'll have to tear down a lot of what I wrote.

Currently my graphql configuration is setup as follows:
```
type store @model   
  @auth(rules: [

    { allow: owner, operations: [read, update, delete] },

    { allow: public, provider: iam, operations: [read] },

    { allow: groups, groups: ["Admin"], operations: [read, create, update, delete] },

    { allow: groups, groups: ["StoreManager"], operations: [create] }

  ]) {
  id: ID!
  storeName: String!
  address: String!
  city: String!
  zip: String!
  phone: String!
  website: String!
  email: String!
  about: String!
  imgs: [String!]!
  owner: String
}

type storeHours @model {
  id: ID!
  day: String!
  hour: String!
}
```
If i'm correct how this should have worked, Mangers would be allowed to create and then the owner  of the post would be allowed to update, read and delete. Admins would be able to do it all and unauthed users and users would just be allowed to read.

**Comment by dantasfiles** [comment]
What isn't working like you want? 
The only thing that jumps out at me is that you'll probably need to add a line to your `Mutation.createStore` resolver that ensures that the `owner` field gets filled automatically by your backend, not by your StoreManager user.

Something like  `$util.qr($ctx.args.input.put("owner", $ctx.identity.claims.get("username")))`

**Comment by Rafcin** [comment]
I actually decided to go with ApiKey to publicly read and and then a group
for creation and it seems to work.

**Comment by nikhname** [comment]
Closing for now, if you have further questions please comment below.
