### ISSUE TITLE
Amplify stuck in update state

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#3184]
I updated the the most recent amplify this morning and then ran 'amplify update api' and set the new redirect URLs, which I have done hundreds of times before with no issue. 

However this time it is stuck at:

>  UPDATE_IN_PROGRESS HostedUICustomResource          AWS::Lambda::Function Tue Jan 14 2020 14:49:03 GMT+0000 (Greenwich Mean Time) 
> ⠹ Updating resources in the cloud. This may take a few minutes...

I then cancelled the CLI command and no cannot run and amplify updates as it says:

> An error occured during the push operation: Stack:arn:aws:cloudformation:eu-west-1:412541719178:stack/amplify-culture-app-dev-163322/8de22d00-016b-11ea-999a-06982f8c16e4 is in UPDATE_IN_PROGRESS state and can not be updated.

I have checked the cloud formation and it still says update in progress.. 3 hours later?

How can I get around this?

**Comment by oliverandersencox** [comment]
now tried with my other environment and both get stuck and no error ever appears. It just stays in . update mode.

Again any progress testing on IOS and Android is completely halted after an update! very frustrating

**Comment by oliverandersencox** [comment]
@kaustavghosh06 any ideas here, I'm due to release on Friday!

**Comment by kaustavghosh06** [comment]
@oliverandersencox Did you take the option to auto update your Lambda runtimes to Node 10.x after updating the CLI? Did you make any other changes to your Lambda code before pushing?

**Comment by oliverandersencox** [comment]
@kaustavghosh06 I did indeed do the auto update and you can see this reflected. I dont actually have any lambda functions in my project and nor have I ever had any. I do have some custom auth policies in the custom resources.

I did indeed look at those as well. 

I was on the most recent version of amplify before this update and everything was fine.

The lambda update were done a long time prior to this issue popping up

**Comment by kaustavghosh06** [comment]
@oliverandersencox I would need to take a look at your Cloudformation files to root cause this. If you send it over to amplify-cli@amazon.com, I can take a deeper look and figure out what’s going on.

**Comment by oliverandersencox** [comment]
@kaustavghosh06 I take it that is just the awscloudformation folder within the backend folder?

**Comment by kaustavghosh06** [comment]
No, the ‘amplify’ folder.

**Comment by kaustavghosh06** [comment]
@oliverandersencox Thanks for sending over the files. Which region are you trying to deploy to? I was able to successfully create an environment and deploy the resources. 
One way to check what's going on with the "HostedUICustomResource" is to check the AWS Cloudwatch logs in the console for that Lambda function and see if it is erroring out on something. 
Did you by any chance change your Hosted UI Domain name recently? 
Hosted UI Domain names need to be globally unique and cannot be re-used.

**Comment by kaustavghosh06** [comment]
You can find your Hosted UI Domain name in this file - `amplify/backend/auth/cultureapp7df34888/parameters.json` under the `hostedUIDomainName` key.

**Comment by oliverandersencox** [comment]
@kaustavghosh06 there arent any logs for that lambda function in either prod or dev.

I have had the domain name for a few months now with no problems

**Comment by oliverandersencox** [comment]
I checked in the OauthCustom... lambda function and its erroring with this: '"Error: Cannot find module 'cfn-response'",'

**Comment by kaustavghosh06** [comment]
@oliverandersencox Which region are you deploying your stck in? 
The module `cfn-response` should be directly injected by the Cloudformation service. I can check with the Cloudformation team with you.

**Comment by kaustavghosh06** [comment]
Also, this looks exactly similar to - #3168

**Comment by oliverandersencox** [comment]
@kaustavghosh06 in which case this guide:

https://aws-amplify.github.io/docs/cli/lambda-node-version-update

solved it. Thanks for the rapid help!
