### ISSUE TITLE
Is there an example to invoke function1 from function2 that works for both mock and cloud?

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3185]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
I have to invoke function1 from function2. I know that I can add function1 as a dependent resource of function2 and I can invoke function1 with aws_sdk by the name of function1. However aws_sdk doesn't work with mock. Is there a way to invoke function1 that works for both mock and cloud?

**Amplify CLI Version** 
4.12.0

**What AWS Services are you utilizing?**
auth
appsync
dynamodb
s3
lambda
cloudwatch

**Provide additional details e.g. code snippets**
Here is how we invoke function1 from function2

var aws = require('aws-sdk');
var lambda = new aws.Lambda({
  region: 'us-west-2'
});

lambda.invoke({
  FunctionName: 'function1',
  Payload: JSON.stringify(event, null, 2) 
}, function(error, data) {
  if (error) {
    context.done('error', error);
  }
  if(data.Payload){
   context.succeed(data.Payload)
  }
});

**Comment by kaustavghosh06** [comment]
@gaochenyue You won't be able to do this in mock I believe. 
Where you able to get the invoke functionality working in the cloud? We don't have an example for this in our documentation as we didn't think it was a very common usecase

**Comment by gaochenyue** [comment]
@kaustavghosh06 Thanks. It is not common if only sync request is needed. We are running into a scenario that we would like to trigger multiple lambda in parallel without waiting for the results in the parent lambda. AppSync can only support sync request while we would like to invoke lambda as an event

**Comment by gaochenyue** [comment]
Is it possible to create a mock endpoint for lambda function (like S3 mock endpoint ) and simulate some common used interfaces. e.g Invoke.

**Comment by kaustavghosh06** [comment]
@gaochenyue I would recommend using AppSync or API Gateway backed up by Lambda if you're looking for an endpoint. Lambda intrinsically doesn't provide or support an endpoint for access.

**Comment by kaustavghosh06** [comment]
@gaochenyue Closing this issue. If you're still stuck on this - please comment on this thread.
