### ISSUE TITLE
No option while configuring

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-cli#3190]
**Describe the bug**
When I finish installing amplify/cli version 4.12.0, I tried the following command: amplify configure.
Then I have only one line of code show up in command line:
![image](https://user-images.githubusercontent.com/36496259/72406215-2b13b780-37a7-11ea-9281-7e980bedae49.png)

There is nothing else after that line.
**Amplify CLI Version**
4.12.0

**To Reproduce**
going to command prompt, install using yarn global add @aws-amplify/cli
after installed, run the following command: amplify configure

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Node Version. 10.16.2
yarn version 1.21.1

**Comment by totaland** [comment]
I found the issue after a few hours of searching. #2410

**Comment by nikhname** [comment]
This is an issue with windows permissions that we may look into in the future. Please feel free to comment if you have further issues.
