### ISSUE TITLE
How can I setup pipeline resolvers using amplify and Aurora?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3192]
Hello,

I would like to use pipeline resolvers.
Basically, take the current user location (Longitude and Latitude) using a SQL query (I use Aurora) and pass it to the next resolver in order to get a list of users nearby that location.

The thing is, I don't see any documentation about that. 

Do I have to modify the file .-rds.json manually and create the .req.vtl and .res.vtl files?
How do I setup this using amplify command line tool?
Any explanation is welcome.

Here:
https://github.com/sid88in/serverless-appsync-plugin#pipeline-resolvers

I found this:
https://medium.com/@joshua.a.kahn/building-aws-appsync-pipeline-resolvers-with-aws-cloudformation-d57d648ecd34
But I don't see how 2 resolvers are executed. Do you have any example?

Thanks a lot for suggestions.

**Which Category is your question related to?**
velocity resolvers, aurora and amplify

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
Amplify CLI

**Comment by nikhname** [comment]
Hi @Ricardo1980, we do not support pipeline resolvers in the CLI at present. We are working on this however and have an RFC #1055 that you may comment on if you would like, specifically for supporting your use case in the RDS transformer.

**Comment by Ricardo1980** [comment]
OK, thanks, I will check that RFC.
