### ISSUE TITLE
Managing Roles

### ISSUE THREAD

**Issue by jtushar53** [aws-amplify/amplify-cli#3193]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
So we are trying to welcome AWS in our org but there are lots of challenges and planning going on. So we've create an application where we created 4 lambda functions with 3 dynamodb tables. for these each services everytime a new role is created that too with random strings at the end. Imagine when you have around 7-8 apps (we may migrates some of our apps to aws), each one of them are having on an average of 7-8 lambda function and 5-6 Dynamo tables managing each and every role will be a pain.
**Describe the solution you'd like**
It would be great if we name the role ourselved instead of amplify adding random string to it. Most importantly if we can reuse existing roles and modify minor resources in it.

**Describe alternatives you've considered**

**Additional context**

**Comment by nikhname** [comment]
@jtushar53 We add the string to the end of roles to avoid conflicts in cases where the role name is too long and must concatenated. Thank you for the feature request we will discuss allowing users to name the roles given that we make a check to avoid conflicts. 

Meanwhile, to make it easier to manage your roles, you should consider using tagging of roles: 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html

Please comment if you have further questions.

**Comment by josefaidt** [comment]
Closing in favor of tags and overrides for category resources and the following feature request for overriding roles on init https://github.com/aws-amplify/amplify-cli/issues/11256
