### ISSUE TITLE
InvalidIdentityPoolConfigurationException error when calling Auth.currentCredentials()

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#3198]
**Describe the bug**
When calling `Auth.currentCredentials();` for unauthenticated user I get the following error: 

> InvalidIdentityPoolConfigurationException: "Invalid identity pool configuration. Check assigned IAM roles for this pool."

**Amplify CLI Version**
4.12.0

**To Reproduce**
- Added auth category, enabled unauthenticated users in cognito pool
- added storage with guest user access to storage
- call `Auth.currentCredentials(); `
- see error

**Expected behavior**
Unauthenticated user should be able to upload files to s3. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version. v12.10.0

**Comment by kldeb** [comment]
I need to allow unauthenticated users the ability to upload files to the s3 bucket using storage. I managed to get past this error by upgrading all the front end libraries but I'm still getting `CredentialsError: "Missing credentials in config"` when trying to put the file.

**Comment by kldeb** [comment]
Figured it out. Wrong identity pool id in unauth role trust relationship. Not sure how that happened. Hopefully it stays fixed after next push.

**Comment by kaustavghosh06** [comment]
@kldeb That's super weird. Did you remove auth and add auth again in your Amplify project?

**Comment by kldeb** [comment]
@kaustavghosh06 yes, i had trouble setting up auth the first time around.

**Comment by kaustavghosh06** [comment]
@kldeb I removed auth -> pushed -> added new auth and the trust relationship reflected the new identity pool. Glad you found the root-cause, I'm closing this issue for now, if there are other folks running into this issue, I'll re-open.
