### ISSUE TITLE
npm run amplify-modelgen generating "type": “string"

### ISSUE THREAD

**Issue by awsed** [aws-amplify/amplify-cli#3199]
GraphQL expects a "String" scalar however modelgen with the Amplify CLI 4.12.0 creates a “string" type in `models/schema.js` with React. Which means the field doesn't show up in IndexedDB locally when using the Amplify DataStore. Manually editing the `models/schema.js` and changing to "String" solves the problem

Sample schema I was testing with:

`type Note @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  note: String
}`

**Comment by dabit3** [comment]
Thanks @awsed, I ran into the same issue and that worked for me also.

**Comment by yuth** [comment]
@dabit3  @awsed could you try deleting the esm cache. It should be located in `<global-node-path>//lib/node_modules/@aws-amplify/cli/node_modules/.cache`.

**Comment by dabit3** [comment]
Thanks @yuth I'll give it a shot. Is this something to be concerned about for users in the future? I.e. is this an issue with npx or just the way node caches globals in general?

If they are following our exact instructions, will this pop up again in the future as we continue to iterate to newer versions? If so, maybe we should consider either letting them know to delete their cache when using npx for a new project or account for the cached files in some other way.

**Comment by yuth** [comment]
@dabit3 Amplify CLI uses [ESM](https://github.com/standard-things/esm) to support ES modules, which maintains a cache. I am investigating to see what would be the impact Of disabling the esm cache (in terms of load times). Longer time solution would be to run the code through typescript or bable transpiler which coverts this to a common js import
