### ISSUE TITLE
Name should only contains letters, numbers, _ and - 

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-cli#3201]
**Describe the bug**

I've just updated the CLI to version 4.12.0 in the hope that I can push to AWS and resolve the nodejs8.10 - nodejs10.x upgrade.

I have Auth, Function and Storage which all worked and pushed successfully before the upgrade.

The name format is as follows:

| Category | Resource name                    | Operation | Provider plugin   |
| -------- | -------------------------------- | --------- | ----------------- |
| Auth     | resourcename               | Update    | awscloudformation |
| Function | resourcenamePostConfirmation | Update    | awscloudformation |
| Storage  | db                               | No Change | awscloudformation |

**Amplify CLI Version**
4.12.0

**To Reproduce**
amplify push

**Expected behavior**
Functions are updated to nodejs10.x as expected

**Actual behavior**
✖ An error occurred when pushing the resources to the cloud

Name should only contains letters, numbers, _ and -
An error occured during the push operation: Name should only contains letters, numbers, _ and

**Desktop (please complete the following information):**
 - MacOS Catalina
 - Node Version. 11.6.0

**Comment by danhumphrey** [comment]
I have narrowed this down and resolved the issue - my `projectName` in `project-config.json` contained a `.` however, this isn't new - it always has and I've pushed many times successfully.

**Comment by joemsak** [comment]
Would be nice to see the error message show where to fix this :) thank you!
