### ISSUE TITLE
Possible to use storage plugin with 3rd party (openid connect) auth?

### ISSUE THREAD

**Issue by chadkouse** [aws-amplify/amplify-cli#3205]
**Which Category is your question related to?**
Storage

**Amplify CLI Version** 
4.6.0

**What AWS Services are you utilizing?**
DynamoDB, Lambda, S3, Cloudfront

**Provide additional details e.g. code snippets**
I'm wondering if it's possible to add storage without requiring the use of cognito?

**Comment by SwaySway** [comment]
Hello @chadkouse currently the cli does not support IAM with OIDC.
As of now there is a dependency on Cognito for it's identity pool which is used to apply auth and unauth policies.
