### ISSUE TITLE
DataStore code generation for multiple frontends

### ISSUE THREAD

**Issue by jkahn117** [aws-amplify/amplify-cli#3210]
**Describe the bug**
DataStore code generation fails when following documentation for multiple frontends. The Amplify CLI seems to expect that the `amplify` directory exists; however, it does *not* exist in cases after an `amplify pull` in which the developer opts to not manage the backend from the project.

**Amplify CLI Version**
4.12.0

**To Reproduce**

1. Create frontend 1 (e.g. React)
2. Initialize new Amplify project and add API. Generate model code.
3. Create frontend 2 (e.g. iOS app) that will use same backend.
4. Use `amplify pull` to retrieve the backend project. Select the desired project. When prompted with the question "Do you plan on modifying your backend (Y/n)?", select "No" per [documentation](https://aws-amplify.github.io/docs/cli-toolchain/quickstart). Two files will be created in project: (1) `amplifyconfiguration.json` and (2) `awsconfiguration.json`. (NOTE: the amplify directory will be briefly created and then destroyed when selecting No).
5. Attempt to generate model classes for DataStore using `amplify codegen models`.

Error:

```
You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
Error: You are not working inside a valid amplify project.
```

**Expected behavior**
Code generation should complete successfully, creating model classes, etc.

**Comment by kaustavghosh06** [comment]
@jkahn117 Currently we need the schema.graphql file in the `amplify` folder to generate the models. If you say 'Yes' to the question above - `Do you plan on modifying your backend (Y/n)` then the amplify directory would be generated with the schema.graphql file in it and you'll be able to execute `amplify codegen models`

**Comment by kaustavghosh06** [comment]
Closing based on the last response. Please comment on this thread if you're still stuck and we'll re-open the issue.

**Comment by zuhair-naqvi** [comment]
My client is supposed to have read only access to the backend. I tried amplify pull, selected no for `Do you plan on modifying your backend (Y/n)`, got aws-exports.js created. Then created an amplify folder and dropped the schema.graphql exported from the console. When I run` amplify codegen models` I still get:

`You are not working inside a valid Amplify project.
Use 'amplify init' in the root of your app directory to initialize your project, or 'amplify pull' to pull down an existing project.
undefined`

What are my options if I want to use DataStore in a client which isn't supposed to update the backend?

**Comment by mir1198yusuf** [comment]
I think you might need some auth directives on models based on which client should be allowed access ..
