### ISSUE TITLE
How do I run an existing Amplify project on a new machine?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-cli#3214]
Since `aws-exports` is not part of the git repo, how do I recreate it without building a whole new Amplify project?

**Comment by kaustavghosh06** [comment]
@ilyador Do you have the `amplify/team-provider-info` in your repo? If yes, you can just run `amplify init` and select your existing environment and the CLI will setup the amplify project on a new machine with the exports file.

**Comment by ilyador** [comment]
@kaustavghosh06 Thanx, how do I create `team-provider-info`?

**Comment by kaustavghosh06** [comment]
It should’ve been created for you - and should be a part of the git repo - since it’s not put into the gitignore by default.

**Comment by ilyador** [comment]
@kaustavghosh06 I have created multiple projects and never had this file created.

**Comment by kaustavghosh06** [comment]
Are you sure it isn’t located in your ‘amplify’ folder? Which version of the CLI did you use to create these projects?

**Comment by kaustavghosh06** [comment]
@ilyador Let me know if you're still stuck on this and I'll re-open this issue.
