### ISSUE TITLE
Regarding IAM permissions

### ISSUE THREAD

**Issue by srajsushmitha** [aws-amplify/amplify-cli#3216]
Hi, what are the permissions required for an IAM user to init and configure amplify(only analytics) because I don't want to give admin permission. Could anybody please help me with that since I didn't find any documentation or any information regarding that.
Thanks

**Comment by kaustavghosh06** [comment]
@srajsushmitha You can find more information regarding the scoped policies out here - https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli
