### ISSUE TITLE
amplify version 4.12.0 -- can't reset node.js runtime to latest

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#3217]
**Describe the bug**

Related to #3179 (closed) and others recently, I am unable to update settings to newer nodejs so future additions fail.

**Amplify CLI Version**
4.12.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

amplify init ( I incorrectly hit <enter> the first and only time asked about nodejs runtimes, then not asked again in subsequent 'amplify init' or new git branches (in attempt to fix))

**Expected behavior**

Some options to manually reset node.js to proper runtime.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

Ubuntu 19.10
Node 12.14.1

Thanks in advance!

**Comment by hisham** [comment]
Yes I'm getting this as well. Similar repro steps.

**Comment by kaustavghosh06** [comment]
@weisisheng For more clarity, is your issue about the fact you answered `No` to this question `Confirm to update the NodeJS runtime version to 10.x (Y/n) ` but now you are not able to automatically migrate your Lambda function runtimes?

**Comment by hisham** [comment]
Hi @weisisheng I was able to fix. Just go to your amplify/.config/project-config.json and change your project version to anything (mine was at 2.0 and I changed to 2.1). Then run an amplify command (e.g. amplify status) and the script will prompt again to upgrade.

**Comment by kaustavghosh06** [comment]
Yeah, I was going to recommend changing to 1.0 and the CLI will ask the question again. The above works too as mentioned @hisham
