### ISSUE TITLE
List, delete aws user profile

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3227]
**Which Category is your question related to?**

Configure AWS Profile

**Amplify CLI Version** 

v.3.17.0

**What AWS Services are you utilizing?**

Amplify 

**Provide additional details e.g. code snippets**

AWS recommends changing access key id and secret access key id every few days. `amplify configure` helps to add new user profile. But I would like to list existing user profiles and delete profile that I no longer want or need. Edit option would also be great so I can just update access key id and secret key id of existing profile.

I tried all of the following commands

- `amplify configure help`
- `amplify configure update`
- `amplify configure remove`
- `amplify configure list`

None of them seems to work.

**Comment by gvhuyssteen** [comment]
This can be easily done through the AWS CLI.

**To list profiles**
`aws configure list`

**All available commands**
`aws configure help`

**Manually change the profile keys**
~/.aws/credentials (Linux & Mac) or %USERPROFILE%\.aws\credentials (Windows)

Reference:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by apoorvmote** [comment]
@gvhuyssteen Thanks for the tip.

If anyone else is interested in updating aws credentials then this is what worked for me

`aws configure --profile myProfileName`

I don't see any option to delete profile but at least I can update access key id and secret key id after the values becomes stale over time.
