### ISSUE TITLE
Spinning down architecture

### ISSUE THREAD

**Issue by sekaru** [aws-amplify/amplify-cli#3228]
**Which Category is your question related to?**
API, Storage, ElasticSearch

**Amplify CLI Version** 
4.11.0

**What AWS Services are you utilizing?**
Cognito, S3, DynamoDB, ElasticSearch

**Provide additional details e.g. code snippets**
How would one go about spinning down the architecture Amplify creates? For example, if I want to take a break I don't want a ElasticSearch instance sitting there and still billing me.

Is it also possible to just spin down individual services? Like if I wanted to delete all my DynamoDB tables and then re-create them later?

**Comment by SwaySway** [comment]
Hello @sekaru
Currently the Amplify CLI does not have an option to spin down services.
If you want to delete your dynamodb tables from say your graphql schema but keep the design you can comment those out and cloudformation will remove those tables for you. The same is applicable for removing `@searchable` from your schema.

**Comment by sekaru** [comment]
That seems to work just fine. Thanks!
