### ISSUE TITLE
Should I use always "id" or can I use "postId", "userId"....? [caching]

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3238]
I see that in the examples we have
`appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }`

My data base has different entities, each one with a different key field name. Something like userId, postId, commentId...
Is it better that I use always "id"? BTW, I use UUID, so they are globally different.

I don't mind changing that right now, because I am still developing my app.

Thanks for suggestions.

**Which Category is your question related to?**
GraphQL modeling

**Amplify CLI Version** 
4.1.2

**What AWS Services are you utilizing?**
AppSync

**Comment by SwaySway** [comment]
Hello @Ricardo1980 
If you are using a RDS backed API there shouldn't be an issue with using any other kind of ID (e.g. postID, userid, ...) though if you are using a DynamoDB backed API it is supported with `@key` and `@connection` directives though there can be unintended side effects as id is used as a sort of default when referencing `@model` types.

**Comment by Ricardo1980** [comment]
Thanks @SwaySway 
Quick question: are you going to implement @connection and/or @key in the future for RDS? Because if that is the case (or likely), then perhaps it is better to use rename my userId, commentId.... to id, right?
Thanks.
