### ISSUE TITLE
Finish cleanup after running Amplify Delete

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#3239]
**Describe the bug**
When you run `amplify delete` you expect everything to be blown away in your account and in the client. Which should include the amplify project in the console and the files generated.

**Amplify CLI Version**
4.12.0

**To Reproduce**
1. Create a new amplify project
1. Add backend resources 
1. Then run `amplify push`
1. After completed, run `amplify delete`
1. Observe that the project still exists on the console page
1. Observe that the `aws-exports`, `graphql/schema.json`, `.graphqlconfig.yml` file still exists.

**Expected behavior**
An environment cleaned of all amplify items both on the client and in the backend

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.13.1

**Comment by kaustavghosh06** [comment]
@wizage We have this feature in 4.13.0 where we delete the aws_exports.js file, the .graphqlconfig and the `graphql/` directory.

@ammarkarachi is looking into deleting the amplify console app on an `amplify delete`.

**Comment by kjetilge** [comment]
I still have this problem and I'm using version 4.13.4. ```.graphqlconfig.yml``` is not deleted when doing ```amplify delete```

By the way, it would perhaps be nice if schema.json was backed up somewhere, so it can easily be reused.
