### ISSUE TITLE
Amplify GraphQL API push fails after switching to another machine and using the latest CLI

### ISSUE THREAD

**Issue by nickchauhan** [aws-amplify/amplify-cli#3245]
**Describe the bug**
I was trying to run my application on a new Mac machine so I installed the latest version of Amplify-CLI (4.13.1) to configure the project. I then tried to push my changes on AWS it failed.

Then I tried to push the changed on AWS using my Windows Machine ( which I used for initiating the project) which has the amplify-CLI version (3.17.0) it failed.
 
I then tried to restore the environment using `amplify env pull --restore` & tried to push the changes it failed. (on both machine)

When I try to push the API I'm getting the following errors.
```
** CREATE_FAILED EngagementUserExport with name ymiqon4xvnfships2j4dta5whi:GetAtt:EngagementUserTable:Name is already exported by stack**
```

I haven't done any changes in the API. Still, the CLI shows that I have updated my API Category I think it is due to whitespaces. It was working fine up till now but all of sudden it started throwing errors and now I'm not able to push any changes on AWS.

```console 
CREATE_FAILED EngagementUser AWS::CloudFormation::Stack Thu Jan 23 2020 15:25:15 GMT+0530 (India Standard Time) Embedded stack arn:aws:cloudformation:eu-west-1:225064100650:stack/configapp-dev-20190621150353-apiconfigApp-4YPORZVU39XB-EngagementUser-1JVEEBLZZWYHM/6e1a0780-3dc6-11ea-af0c-06d4f42323aa was not successfully created: Export with name ymiqon4xvnfships2j4dta5whi:GetAtt:EngagementUserTable:Name is already exported by stack configapp-dev-20190621150353-apiconfigApp-4YPORZVU39XB-User-11KB8EXJFLXH1    

UPDATE_FAILED User           AWS::CloudFormation::Stack Thu Jan 23 2020 15:25:15 GMT+0530 (India Standard Time) Embedded stack arn:aws:cloudformation:eu-west-1:225064100650:stack/configapp-dev-20190621150353-apiconfigApp-4YPORZVU39XB-User-11KB8EXJFLXH1/05659270-9409-11e9-93f5-0a0272c6a610 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Export ymiqon4xvnfships2j4dta5whi:GetAtt:EngagementUserTable:StreamArn cannot be deleted as it is in use by configapp-dev-20190621150353-apiconfigApp-4YPORZVU39XB-SearchableStack-1VHIRTP6PHQRW
```

**Amplify CLI Version**
On Initial Windows Machine - 3.17.0
On Macbook  - 4.13.1

**To Reproduce**
1. create amplify project and add API using amplify version 3.17.0 on a windows machine.
2. push your code in the AWS cloud. `amplify api push`
3. create amplify project and add API using amplify version 4.13.1 on a mac machine.
4. try to push the API

**Expected behavior**
Since I have used the latest CLI version on another machine it should be backwards compatible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 & macOS Catalina 10.15.2
 - Node Version.  Windows : v11.10.1 , Macbook : 13.7.0

**Additional context**
I read similar issues on the GitHub. Some suggest to remove the API category and add it again using the latest CLI but that will remove all the data in the database and create new tables in DynamoDB, which shouldn't be the correct solution.

**Comment by nikhname** [comment]
@nickchauhan Are you using the same environment name on the new project/machine as the old project?

**Comment by nickchauhan** [comment]
@nikhname Yes I'm using the same environment.

**Comment by edwardfoyle** [comment]
Hi @nickchauhan, this looks similar to #2928. Can you try the suggestion there about changing the selection index in your CloudFormation template to be the number component of your stack name (ie. index 2 because that will select the number from "configapp-dev-20190621150353" when splitting on "-")

**Comment by edwardfoyle** [comment]
@nickchauhan Closing due to lack of response. If you are still running into issues after trying the suggestion above, please reopen.
