### ISSUE TITLE
How to make a relationship of data from user pool to aws appsync model

### ISSUE THREAD

**Issue by yvescoinpass** [aws-amplify/amplify-cli#3251]
** Which Category is your question related to? **
Auth, API
** What AWS Services are you utilizing? **
 Cognito, AWS AppSync,
** Provide additional details e.g. code snippets **

I am new to amplify and appsync. I am trying to create a Post model that needs to have a relationship of the user who is creating the Post. The problem is my user is from cognito user pool.

How should I create a relationship of this?

I create amlify api like this

```
? Please select from one of the below mentioned services: GraphQL
? Choose the default authorization type for the API API key
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): 7
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API Amazon Cognito User Pool
Cognito UserPool configuration
Use a Cognito user pool configured as a part of this project.
? Configure conflict detection? No
```
Here is my current Post model 

```
type Post @model @versioned @aws_cognito_user_pools @auth(rules:[{allow: owner, queries:null},{allow: public}]){
  id: ID!
  title: String!
  content: String
  thumb: String
  slug: String!
  allow_comments: Boolean
  owner: String!
  version: Int!
  comments: [Comment] @connection(name: "PostComments")
}
```

I can't find any documentation how to build something like this.

"aws-amplify": "^2.2.1",
"aws-amplify-react": "^3.1.2",

**Comment by sorokinvj** [comment]
@yvescoinpass the field owner of the Post type will be populated automatically with the user.username (because of the @auth(rules:[{allow: owner}]) )

**Comment by SwaySway** [comment]
Hello @yvescoinpass if you are looking at adding authorization based solely on the user who created the post you can use `@auth(rules:[{allow: owner}]) )` as stated by @sorokinvj.

View our `@auth` docs here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth

Should you run into any `@auth` related issues please feel free to comment below.

**Comment by yvescoinpass** [comment]
Hello @SwaySway  @sorokinvj  I tried it but it only returns `{ownser:"user1"}`. It can't return the whole information of that user as an object?

here is my query 

```
query ListPost {
  listPosts{
    items {
      owner
    }
  }
}

mutation CreatePost {
  createPost(input:{
    title:"title 1",
    add_to_nav: true,
    post_type: "post",
    slug: "tittle-1"
  }) {
    owner
  }
}
```

and here is the result `query ListPost`

```
{
  "data": {
    "listPosts": {
      "items": [
        {
          "owner": "user1"
        },
      ]
    }
  }
}
```

**Comment by sorokinvj** [comment]
> Hello @SwaySway @sorokinvj I tried it but it only returns `{ownser:"user1"}`. But what I want is the whole information of that user from cognito user pool as an object. Is that possible?

If you want it in the same response when you got all the info about Post, no I don't think its possible, but you can make another request to Cognito and fetch everything connected to user1

**Comment by yvescoinpass** [comment]
Thank you. Ok good to know that it its not possible. Can you give me a link to the documentation where I can request for the information of the user on Cognito User Pool?

**Comment by sorokinvj** [comment]
@yvescoinpass Sure! I use amplify framework in my app, so I communicate with Cognito via

```
import { Auth } from 'aws-amplify';

Auth.currentAuthenticatedUser()
.then(user => console.log(user))
.catch(err => console.log(err));
```

Here are the docs - https://aws-amplify.github.io/docs/js/authentication

**Comment by yvescoinpass** [comment]
Ok thank you so much @sorokinvj

**Comment by yvescoinpass** [comment]
I have an update on this question.  What I did is just @sorokinvj  advice. I created a new Model UserProfile on my schema.graphql. 

Here is my new schema.graphql 

```
type UserProfile
	@model
	@versioned
	@aws_cognito_user_pools
	@auth(
		rules: [
			{
				allow: owner
				provider: userPools
				operations: [read, create, update, delete]
			}
			{ allow: public, provider: apiKey, operations: [read] }
		]
	) {
	id: ID!
	username: String!
	first_name: String!
	last_name: String!
	email: String!
	version: Int!
	picture: String
	post: [Post] @connection(name: "UserProfilePost")
}

type Post
	@model
	@versioned
	@aws_cognito_user_pools
	@auth(
		rules: [
			{
				allow: owner
				provider: userPools
				operations: [read, create, update, delete]
			}
			{ allow: public, provider: apiKey, operations: [read] }
		]
	) {
	id: ID!
	title: String!
	content: String
	thumb: String
	slug: String!
	allow_comments: Boolean
	post_type: String!
	add_to_nav: Boolean!
	version: Int!
	comments: [Comment] @connection(name: "PostComments")
	user_profile: UserProfile! @connection(name: "UserProfilePost")
}

```

After logged in I fetch the user pool data when I got the data. 

Then I try adding it on user_profile table but the owner is null? 

This means that the API still didn't recognize me as a logged in user?

Here is the code to my logged in component

```
handleSumbmit(e) {
		e.preventDefault();

		this.setState({ authenticating: true });

		const { username, password } = this.state;

		Auth.signIn({
			username: username,
			password: password
		})
			.then(res => {
				console.log(res);
				this.setState({
					has_error: false,
					error_message: ""
				});
				this.setState({ authenticating: false });
				this.getCurrentUser(); // GET THE CURRENT LOGGED IN USER INFO
			})
			.catch(err => {
				console.log("handleSumbmit:", err);
				this.setState({ authenticating: false });
				this.setState({
					has_error: true,
					error_message: err.message
				});
			});
	}
	
	async getCurrentUser() {
		try {
			let user = await Auth.currentAuthenticatedUser();
			console.log("getCurrentUser", user);

			this.checkUserProfile(user); // CHECK IF THIS USER IS ALREADY ADDED IN USER PROFILE TABLE
		} catch (err) {
			console.log(err);
		}
	}

	async checkUserProfile(user_pool_data) {
		try {
			let { data } = await API.graphql(
				graphqlOperation(GetUserProfile, {
					id: user_pool_data.attributes.sub
				})
			);
			console.log("checkUserProfile", data);

			if (!data.getUserProfile) {
				this.addUserProfile(user_pool_data); // ADD A USER PROFILE FOR THIS USER
			} else {
				this.setAuthenticatedUser(user_pool_data, 1);
			}
		} catch (err) {
			console.log(err);
		}
	}

	async addUserProfile(user_pool_data) {
		try {
			let user_profile = {
				id: user_pool_data.attributes.sub,
				username: user_pool_data.username,
				first_name: user_pool_data.attributes.given_name,
				last_name: user_pool_data.attributes.family_name,
				email: user_pool_data.attributes.email
			};
			await API.graphql(
				graphqlOperation(CreateUserProfile, { input: user_profile })
			);
			console.log("addUserProfile", user_profile);
			this.setState({ confirm_success: true });
			this.setAuthenticatedUser(user_pool_data, 1);
		} catch (err) {
			console.log(err);
		}
	}
```

@swaminator  @SwaySway  maybe you know about this?

**Comment by ianmartorell** [comment]
Why not get rid of the `UserProfile` type altogether and get those fields directly from the Cognito User Pool attributes?

**Comment by yvescoinpass** [comment]
@ianmartorell  Then how can I make a relationship to it in another table on my dynamodb?

**Comment by ianmartorell** [comment]
You could use a custom resolver like this: https://github.com/aws-amplify/amplify-cli/issues/1352#issuecomment-487176176. I haven't tried this myself though. Since I only need to get the profile for the current user, I can just use the `Auth` class from Amplify js.

**Comment by sorokinvj** [comment]
@yvescoinpass how do you define CreateUserProfile in your code? do you import it from the graphql/mutation.js? could you provide the mutation query?

**Comment by deviant32** [comment]
I am also experiencing this, when I create a 1 to 1 relationship it doesn't update the ownership of the second object being saved.

**Comment by harinair** [comment]
IMHO - directly hitting Cognito for user information does not sound appetizing, especially since there are no easy ways to do batch reads. My take is to create Lambda and trigger Lambda using Cognito events. Using that technique, you will be able to sync the User attributes to a Userprofile table. Yes, it creates duplication of data, but this is much easier to manage.

**Comment by bravcmo** [comment]
I built a User model in GraphQL for the api before deciding to try the Auth features of Amplify.  My User model appears it was merged into the Cognito-generated one.  However, the data in AdminUI shows a separate notion of User and retained that data.  Would welcome other input on how to peer App-related attributes with the Auth User data.  Thanks
