### ISSUE TITLE
Upload file to amplify mock in react native - FileReader.readAsArrayBuffer is not implemented

### ISSUE THREAD

**Issue by jfdesgagne** [aws-amplify/amplify-cli#3253]
**Describe the bug**
When uploading a file from react-native to s3 via amplify mock storage (S3), I'm getting the following error [Error: FileReader.readAsArrayBuffer is not implemented]

When running in non mock state, everything works just fine.

**To Reproduce**

```
const response = await fetch(image.path);
const buffer = await response.blob()
const filename = uuid();
const result = await Storage.put(filename, buffer, {
    level: 'public',
    contentType: image.mime,,
});
```

**Expected behavior**
To be able to upload images using arraybuffer in mock

**Smartphone (please complete the following information):**
- Device: Simulator, Iphone 11
- OS: ios 13.3

**Comment by jfdesgagne** [comment]
To give more context, I'm using this camera picker: https://github.com/ivpusic/react-native-image-crop-picker

I'm able to upload the image to the cloud without mock, as well as visualize the image locally which is stored at /Users/<user>/Library/Developer/CoreSimulator/Devices/ED05B123-2E8B-4137-8DB1-36B6058F43E4/data/Containers/Data/Application/C91957F0-F780-48AE-9339-D929033695AB/tmp/react-native-image-crop-picker/76089AE1-B037-48E9-8695-22C8BEC16788.jpg

**Comment by akshbhu** [comment]
@jfdesgagne I tried it on my end and it was working correctly. Are you still facing this issue?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of information. Please comment on this thread if you're still stuck on this issue.

**Comment by 10centmedialabs** [comment]
Having the same issue. During mock, it throws this error. However, when pushed to the cloud, no issues at all. @akshbhu Did you succeed with this when mocking storage?

**Comment by lukepushlabs** [comment]
I'm getting this issue during mock as well. Using expo's image picker and sample code from amplify documentation on uploading an image to S3 (My internet connection is bad and sometimes causes AWS issues due to that and maybe is the real cause)

**Comment by djkmiles** [comment]
- Expo SDK 37, managed
- Fails when using `amplify mock [storage]`
- Array-buffer error can be patched
- Then fails with message "Network failure"
- All Amplify/Storage functions eg list, put, get fail this way
- Recommend adding `Amplify.logger.level = "DEBUG"` to App.js/config

**Comment by djkmiles** [comment]
While this is left to continue by AWS, I would recommend using `amplify mock api` to avoid interruption
