### ISSUE TITLE
[bug] Cannot read property 'directives' of undefined

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#3264]
After upgrading from 4.12.0 to 4.13.0 - I receive the following error:

```
✖ An error occurred when pushing the resources to the cloud
Cannot read property 'directives' of undefined
An error occured during the push operation: Cannot read property 'directives' of undefined
```

**Comment by kldeb** [comment]
I'm getting this error as well when running amplify mock and deploying via amplify console with 4.13.0.

**Comment by SwaySway** [comment]
Hello @amcdnl we are aware of this issue could you please try v4.13.1?

**Comment by amcdnl** [comment]
yup fixed it - thanks!

**Comment by zilurrane** [comment]
Hiii
Am getting same error while running ```amplify codegen models```
amplify version = 4.21.3
