### ISSUE TITLE
Attach additional policies to the authRoles

### ISSUE THREAD

**Issue by damonmiller** [aws-amplify/amplify-cli#3266]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.12.0

**What AWS Services are you utilizing?**
Amplify, Cognito, SNS/SMS

**Provide additional details e.g. code snippets**
Within our Amplify React app we want to be able to access the SNS/SMS service to know whether a user's phone number has been opted out so we can prompt the user and allow them to opt back in.  I have created an IAM policy for this and have been manually adding the policy to the auth roles created by Amplify and this works just fine in the app. 
 But I would really like to attach those policies to the roles during the deployment.  Is there anyway to attach additional policies within the Amplify CLI or even by manually changing an CloudFormation file in the amplify folder?  Or am I going about this the wrong way?  If so, what is a better way to accomplish this?

Appreciate any assistance and thank you for making Amplify so awesome!

**Comment by sakhmedbayev** [comment]
I have the same question. Please provide an answer.

**Comment by kaustavghosh06** [comment]
@sakhmedbayev You can use custom stacks as mentioned out here - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks and use the the auth or unauth role using "Ref": "UnauthRoleName" and attach your custom policies.

**Comment by kaustavghosh06** [comment]
Closing based on my last response. If you've further questions, please comment on this thread.

**Comment by athewsey** [comment]
Would just like to get some more clarification for this solution if I can:

In my setup the CF template that actually *creates* the authRole appears to be the `amplify/backend/cloudformation/nested-cloudformation-stack.yml` which is **excluded from source control** by standard config...

According to the docs:

> For majority of the other [not GraphQL] categories, you can locally edit and manage the Cloudformation file generated by the CLI

...so I interpret I could edit `amplify/backend/auth/{RESNAME}/{RESNAME}-cloudformation-template.yml` (which *is* included in VCS and already receives `authRoleArn` as a parameter) to [attach a policy to an existing role](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-attach-managed-policy/).

...but would this actually be preserved if somebody later uses the Amplify CLI to edit the auth service?

What about if somebody clones my app into a new environment with `amplify init --app <github url>`?

Or if I want the change to be persistent, do I instead need to go through those documented steps to make a *new, separate, custom* CloudFormation template solely to configure my authRole policies?
