### ISSUE TITLE
Cannot view/update MFA settings using `amplify update auth` command

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#3268]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am getting this error whenever I try to push. MFA is set to "optional" in my User pool
`Reason: Cannot turn MFA functionality ON, once the user pool has been created.`

When I try to update the MFA settings, the CLI skips over the MFA prompt:

```
amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resour
ce could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connecte
d with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and
more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) (Use
 arrow keys)
  Yes
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No // I believe there should be a setting here about MFA
 Email based user registration/forgot password: (Use arrow keys)
> Enabled (Requires per-user email entry at registration)
  Disabled (Uses SMS/TOTP as an alternative)

```

**Amplify CLI Version**
4.13.1

**Comment by yuth** [comment]
@blazinaj could you clarify that you already had auth category configured and this error started happening after doing an `amplify auth update` and running `amplify push`?

Could you share your `paramter.json` for auth category so I could see how auth category was configured and why its not showing `MFA` related questions

**Comment by UnleashedMind** [comment]
Closing due to lack of response.
