### ISSUE TITLE
Amplify mock error

### ISSUE THREAD

**Issue by mdebo** [aws-amplify/amplify-cli#3270]
Hi
I'm not able to use amplify mock anymore.
I have an appsync API with a mutation:
```gql
type Mutation {
  myMutation(ownerId: String!): Creche
    @function(name: "myLambda-${env}")
    @aws_iam
    @aws_api_key
}
```
myLambda is a lambda function which has access to appsync AND to a dynamoDB storage
Each time i run `amplify mock` I get this error:
```
Failed to parse Lambda function cloudformation in /Users/mathias/Projects/kandiz/amplify/backend/function/kandiz6c93529ePreTokenGeneration/kandiz6c93529ePreTokenGeneration-cloudformation-template.json

Error: Could not find ref for "storageUserRoleTableName"
Failed to parse Lambda function cloudformation in /Users/mathias/Projects/kandiz/amplify/backend/function/myLambda/myLambda-cloudformation-template.json

Error: Could not find ref for "storageUserRoleTableName"
Failed to start API Mock endpoint Error: Lambda function myLambda does not exist in your project.
Please run amplify add function
```

If I remove the mutation from the schema OR the right for permission to access to my dynamo table everything is OK. Do you have any ideas?

Version of cli used: 4.13.1
Step to reproduce:
 1- create a storage (amplify add storage) 
2-create a function that has permission to this storage (write for exemple) 
3- add `@function` directive to a custom mutation 
4-run amplify mock

**Comment by mdebo** [comment]
After searching through the existing issues, it seems my problem is very similar to this: #2453

**Comment by edwardfoyle** [comment]
Hi @mdebo, could you provide more details on how you created your function? From the error output above, it looks like you have two functions," myLambda" and "kandiz6c93529ePreTokenGeneration." When going through the function creation CLI did you select "CRUD function for Amazon DynamoDB ..." or one of the other options?

Could you also elaborate on how you are toggling the ability for your lambda to access the dynamodb storage?

If possible, it may help in debugging if you could provide a zip file of your project workspace. Or if that is not possible, could you upload your lambda function CloudFormation templates?

**Comment by edwardfoyle** [comment]
Hi @mdebo if you're still having this issue please follow up with additional information so I can try to repro.

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of requested information. Please comment if you're still stuck with this issue.
