### ISSUE TITLE
@auth subscription schema generation incorrect when using owner auth with `operations: [read]`

### ISSUE THREAD

**Issue by SteffeyDev** [aws-amplify/amplify-cli#3272]
I have the same issue as in #2361, except for me it appears the addition of the `operations` field prevents the correct generation of the subscription type.  I need the owner to be able to read and and get subscription updates, but not create, delete, or update (lambda will be doing the mutations, want to get subscriptions on front-end).  I tested, and removing the `operations` field does fix the issue and result in the correct schema generation.  However, this allows the user to write, which should not be allowed for my application.

Schema:
```
type VMInstance
   @model
   @key(fields: ["userId"])
   @auth(rules: [
     { allow: owner, ownerField: "userId", operations: [read] }
   ])
 {
   userId: ID!
   otherProperties: String!
}
```

Actual output:
```
type Subscription {
   onCreateVMInstance: VMInstance @aws_subscribe(mutations: ["createVMInstance"])
   onUpdateVMInstance: VMInstance @aws_subscribe(mutations: ["updateVMInstance"])
   onDeleteVMInstance: VMInstance @aws_subscribe(mutations: ["deleteVMInstance"])
 }
```

Expected output:
```
type Subscription {
   onCreateVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["createVMInstance"])
   onUpdateVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["updateVMInstance"])
   onDeleteVMInstance(userId: String): VMInstance @aws_subscribe(mutations: ["deleteVMInstance"])
 }
```

**Amplify CLI Version**
CLI Version: 4.12.0

**To Reproduce**
* Create react app.
* Amplify init
* Amplify add auth
* Amplify add api => graphQL
* Create schema.graphql (see code above)
* Amplify push
* Go to Appsync console and check the schema.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.14.1

**Additional context**
See all of #2361 and the resulting pull request for guidance.

**Comment by SwaySway** [comment]
Hello @SteffeyDev owner auth is not enforced on the subscription by adding read. It is based on the respective mutation action, thus if the owner is allowed to create they can also see the subscription for that respective mutation.

**Comment by SteffeyDev** [comment]
@SwaySway thanks for the info, how could I set up my project so that owners can only read and get subscription updates but not modify?

**Comment by SwaySway** [comment]
@SteffeyDev There is a workaround highlighted in this comment though based on customer needs we can look into implementing a different operation to split read and create rules.

https://github.com/aws-amplify/amplify-cli/issues/2636#issuecomment-567286984

**Comment by SteffeyDev** [comment]
@SwaySway That workaround looks helpful, thanks!  That should work if needed.  I like your `listen` idea, that would work perfectly for my use case and I'm sure many others.  My project is in development for the next few months, do you think the `listen` operation could be added in that time range?  If so I will just wait to restrict permissions on my api.

**Comment by SwaySway** [comment]
@SteffeyDev I'll review that enhancement with the team. Please follow #2636 for updates on that.
Closing as duplicate.
