### ISSUE TITLE
Cannot recreate team-provider-info.json

### ISSUE THREAD

**Issue by kernwig** [aws-amplify/amplify-cli#3274]
**Describe the bug**
After issue #3273  deleted the `team-provider-info.json` file, I tried to recreate it per the instructions at https://aws-amplify.github.io/docs/cli-toolchain/quickstart#team-members-sharing-the-same-dev-backend

Upon issuing `amplify init` though, it does not ask `Do you want to use an existing environment?` as shown in the documentation - it proceeds to create a new project in Amplify Console with the same name as the old one.

**Amplify CLI Version**
4.10.0

**To Reproduce**
Create an Amplify project, delete `team-provider-info.json`, and then try and pull the environment back from the cloud.

**Expected behavior**
I expect to be able to reconnect tho the cloud resources without a `team-provider-info.json` file, as is recommended for public repositories at the end of this part of the documentation: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#sharing-projects-outside-the-team-

**Screenshots**

**Desktop (please complete the following information):**
- OS: Mac v10.15.2
- Node Version: 10.16.3

**Comment by keponk** [comment]
ran into a similar situation. Was able to repopulate the file it using `$ amplify pull --appId abcxyz123 --envName dev` , same line displayed on the amplify console to start editing an environment. For this to work I needed to delete the amplify folder itself though.

**Comment by tabrza** [comment]
I also ran into something similar and found that the following command helped resolve the issue
```
amplify configure project
```
pulled from this issue [#3161](https://github.com/aws-amplify/amplify-cli/issues/3161)

**Comment by siegerts** [comment]
Hi All :wave: - I've opened a [PR against the docs](https://github.com/aws-amplify/docs/pull/3060) to address the [now] broken link + provide a solution using `amplify pull`.

Thanks, @keponk for your earlier comments : ) 

In summary - 

> Ensure the root of your project has the `amplify` folder set up in order to be able to re-use existing environments. 
>
> If the **team-provider-info.json** file is missing: 
> 1. Backup and remove the `amplify` folder 
> 2. Pull the environment from the root of your project folder using the `amplify pull --appId <app-id> --envName <env-name>` command displayed in the Amplify Console for your application
