### ISSUE TITLE
Using @searchable directive does not return nextToken correctly

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-cli#3280]
Transcribed from https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/324, originally filed by @amuresia.

---

**Describe the bug**
When using the `@searchable` directive, the pagination is wrong. If all of the records have been returned (i.e. by having a high limit and just a few entries in the table) the nextToken is not set to null, instead it's set to the last item id.

**To Reproduce**
1. Create the resources with the schema provided below
2. Fire off a search that returns all of the results in the table

Query example:
```gql
query test {
  searchItems(limit: 100, filter: {
    name: {
      match :"test"
    }
  }) {
    items {
      id
      name
    }
    nextToken
  }
}
```
**Expected behavior**
nextToken should be set to null if there are less than 100 items in the table (less than the limit, meaning that all of the results were retrieved in one go)

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.15.0
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Additional context**
Schema example:
```gql
type Item
@model
@searchable
@auth(rules: [{ allow: owner, ownerField: "itemOwnerId", operations: [create, update, delete] }]) {
    id: ID!
    owner: User! @connection(name: "UserItem")
    name: String!
}
```

---

Followup by @palpatim:

@amuresia Thanks for reporting the issue. I've been able to confirm this behavior in the AppSync console, and it looks like the generated VTL in the ElasticsearchDomain resolver populates this:

```
#set( $es_items = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    #set( $nextToken = $entry.sort.get(0) )
  #end
  $util.qr($es_items.add($entry.get("_source")))
#end
$util.toJson({
  "items": $es_items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```

My read of this VTL is that it loops over every entry in the result set and sets `$nextToken` to field 0 of the result. I don't know if the resolver can inspect the result to know if there are legitimately more but we'll ask the CLI team to take a look.

**Comment by SwaySway** [comment]
Hello @amuresia
The `@searchable` directive uses [Search After](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-search-after.html) to perform pagination. Which is why it returns a value of the last item in the response.
