### ISSUE TITLE
npm run amplify-modelgen giving throw er; // Unhandled 'error' event 

### ISSUE THREAD

**Issue by jitendra-koodo** [aws-amplify/amplify-cli#3282]
Following this [guide ](https://aws.amazon.com/blogs/aws/amplify-datastore-simplify-development-of-offline-apps-with-graphql/) with React Native app, but getting this error 

`$> npm run amplify-modelgen

> test@0.0.1 amplify-modelgen E:\...\amplify\datastore\test
> node amplify\scripts\amplify-modelgen.js

Running codegen...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn amplify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.1 amplify-modelgen: `node amplify\scripts\amplify-modelgen.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.0.1 amplify-modelgen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\npm-cache\_logs\2020-01-27T18_53_52_973Z-debug.log`

**Amplify CLI Version**
4.13.1

**To Reproduce**
As per mentioned in doc above. Only change is React Native app.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version :  v10.16.2

**Additional context**

Amplify status is empty (as expected since its a just local Datastore)
$> amplify status

Current Environment: test

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |

Detailed logs:
`0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Jitendra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'amplify-modelgen' ]
2 info using npm@6.7.0
3 info using node@v10.16.2
4 verbose run-script [ 'preamplify-modelgen',
4 verbose run-script   'amplify-modelgen',
4 verbose run-script   'postamplify-modelgen' ]
5 info lifecycle test@0.0.1~preamplify-modelgen: test@0.0.1
6 info lifecycle test@0.0.1~amplify-modelgen: test@0.0.1
7 verbose lifecycle test@0.0.1~amplify-modelgen: unsafe-perm in lifecycle true
8 verbose lifecycle test@0.0.1~amplify-modelgen: PATH: C:\Users\Jitendra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\xampp\htdocs\git\amplify\datastore\test\node_modules\.bin;C:\Users\Jitendra\bin;E:\Program Files\Git\mingw64\bin;E:\Program Files\Git\usr\local\bin;E:\Program Files\Git\usr\bin;E:\Program Files\Git\usr\bin;E:\Program Files\Git\mingw64\bin;E:\Program Files\Git\usr\bin;C:\Users\Jitendra\bin;C:\Python27;C:\Python27\Scripts;C:\Python38\Scripts;C:\Python38;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;E:\Program Files\TortoiseSVN\bin;E:\Program Files\Git\mingw64\bin;C:\WINDOWS\System32\OpenSSH;E:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Amazon\AWSCLI\bin;E:\Program Files\nodejs;E:\xampp\php;F:\tools;F:\tools\libwebp-0.4.1-windows-x64\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_231\bin;C:\Users\Jitendra\AppData\Roaming\npm;C:\Users\Jitendra\AppData\Local\Android\Sdk\platform-tools;E:\Program Files\Microsoft VS Code\bin;C:\Users\Jitendra\AppData\Local\Microsoft\WindowsApps;C:\Users\Jitendra\AppData\Local\Yarn\bin;E:\ML\spark-2.3.1-bin-hadoop2.7\bin;C:\Users\Jitendra\AppData\Local\Android\Sdk\emulator;E:\Program Files\Git\usr\bin\vendor_perl;E:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle test@0.0.1~amplify-modelgen: CWD: E:\xampp\htdocs\git\amplify\datastore\test
10 silly lifecycle test@0.0.1~amplify-modelgen: Args: [ '/d /s /c', 'node amplify\\scripts\\amplify-modelgen.js' ]
11 silly lifecycle test@0.0.1~amplify-modelgen: Returned: code: 1  signal: null
12 info lifecycle test@0.0.1~amplify-modelgen: Failed to exec amplify-modelgen script
13 verbose stack Error: test@0.0.1 amplify-modelgen: `node amplify\scripts\amplify-modelgen.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Jitendra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Jitendra\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid test@0.0.1
15 verbose cwd E:\xampp\htdocs\git\amplify\datastore\test
16 verbose Windows_NT 10.0.18362
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jitendra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "amplify-modelgen"
18 verbose node v10.16.2
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@0.0.1 amplify-modelgen: `node amplify\scripts\amplify-modelgen.js`
22 error Exit status 1
23 error Failed at the test@0.0.1 amplify-modelgen script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by nikhname** [comment]
@jitendra-koodo does running 'amplify codegen model' work?

**Comment by jitendra-koodo** [comment]
@nikhname 

$>  amplify codegen model
No AppSync API configured. Please add an API


Though command runs but it does not work really. It asks to configure API but API does not need to be configured if working only with local Datastore as per other AWS docs.

**Comment by jitendra-koodo** [comment]
Would love to know about any workaround to move forward?

**Comment by nikhname** [comment]
@jitendra-koodo  you do not need to provision your API with a push but you still need to have an GraphQL schema within your project to generate models. Does your project have a schema locally? If not, to move forward please run amplify add api and follow the steps to add a schema.

**Comment by nikhname** [comment]
As a side note, running npx amplify-app should generate a boilerplate API/GraphQL schema for you. Please comment if this was not the case

**Comment by jitendra-koodo** [comment]
@nikhname Looks like RN support is not officially ready yet : https://github.com/aws-amplify/amplify-js/issues/4527 .  Would you still suggest to move ahead with the steps you mentioned above? Last time I checked, npx amplify-app did not create API folder on Windows 10.

**Comment by nikhname** [comment]
@jitendra-koodo I would suggest waiting for RN support and then moving forward with adding an API. Closing this issue, please comment if you have further questions.
