### ISSUE TITLE
Peer dependency missing

### ISSUE THREAD

**Issue by leantide** [aws-amplify/amplify-cli#3284]
**Describe the bug**
npm ERR! peer dep missing: inquirer@^5.0.0 || ^6.0.0, required by inquirer-autocomplete-prompt@1.0.1

Seems maybe you have upgraded to inquirer@7.0.4 but  inquirer-autocomplete-prompt feels it needs  inquirer@^5.0.0 || ^6.0.0. Maybe the dependency can be upgraded if compatible to avoid error.

**Amplify CLI Version**
4.13.1

**To Reproduce**
npm -g install @aws-amplify/cli

**Expected behavior**
no error

**Comment by kaustavghosh06** [comment]
@leantide  inquirer-autocomplete-prompt doesn't seem to be a CLI dependency. 

Is there any other globally installed node_modules in your system which require  inquirer-autocomplete-prompt?

**Comment by leantide** [comment]
Well, when I run `npm -g list inquirer` I get 15 references into @aws-amplify:

/usr/local/nvm/versions/node/v12.14.0/lib
└─┬ @aws-amplify/cli@4.13.1
  ├─┬ amplify-category-analytics@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-api@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-auth@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-function@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-hosting@2.1.9
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-interactions@2.1.9
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-notifications@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-predictions@2.1.9
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-storage@2.1.9
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-category-xr@2.1.9
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-codegen@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-frontend-android@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-frontend-javascript@2.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  ├─┬ amplify-provider-awscloudformation@4.13.1
  │ └── UNMET PEER DEPENDENCY inquirer@7.0.4  deduped
  └── UNMET PEER DEPENDENCY inquirer@7.0.4 

and then I get 15 copies of this error, 1 for each of the above references.

npm ERR! peer dep missing: inquirer@^5.0.0 || ^6.0.0, required by inquirer-autocomplete-prompt@1.0.1

**Comment by leantide** [comment]
Maybe it is a dependency of your dependency on inquirer.

**Comment by kaustavghosh06** [comment]
@leantide Does that prevent you from the CLI installation?

**Comment by leantide** [comment]
No. It still installs.

Also, from a high level, I have not noticed any deficiency of function of the cli.

**Comment by yuth** [comment]
it looks like interaction category uses inquirer-autocomplete-prompt.

**Comment by kaustavghosh06** [comment]
@yuth Yes, @attilah diagnosed this sometime back and has a plan for this I believe.

**Comment by leantide** [comment]
I still have this issue in v4.18.1

**Comment by GerardKetuma** [comment]
Also have this issue with v4.18.1. It does not affect functionality but also doesn't give me full confidence when I see this:
<img width="1016" alt="amplify" src="https://user-images.githubusercontent.com/683242/81030686-43d7d400-8e4f-11ea-84f7-1d6426e94c73.png">

**Comment by mrjackyliang** [comment]
Also by entering the `sudo npm list -g --depth=0` command, also lists the error.

**Comment by fones** [comment]
Still present in 4.21.0

**Comment by huberv** [comment]
Still present in 4.21.4

**Comment by mav1283** [comment]
Yeah i have the same problem, does anyone solved this already?

**Comment by mrjackyliang** [comment]
Doesn't seem like anyone is working on this issue🤔

**Comment by attilah** [comment]
There is an open PR for that given dependency that is not merged since April, once that is merged we can bump the dependency version in the CLI and this will go away: https://github.com/mokkabonna/inquirer-autocomplete-prompt/pull/106 another alternative solution is to move to enquirer which has this prompt type in the box.

**Comment by kevcam4891** [comment]
How are we looking on this?

**Comment by mrjackyliang** [comment]
Just tested it, seems fixed!
