### ISSUE TITLE
How to add frontend configuration items depending on the environment, similar to aws-exports.js?

### ISSUE THREAD

**Issue by mrducky4** [aws-amplify/amplify-cli#3286]
I'm using amplify-cli with different environments (dev, test, prod). I see how aws-exports.js contains different configuration values for different environments. Now I want my frontend to access an existing  REST API. This existing API is not managed by amplify, and it does have different URLs for different environments.

What is the best practice for configuring something like this that depends on the environment, but is not managed directly by amplify? Is there a way to add my own custom key-value pairs to aws-exports.js, where the values are different for different environments?

**Comment by kaustavghosh06** [comment]
@mrducky4 You can add a custom key value pair to your aws_exports.js file but you'd have to then manipulate that in your client code based on the environment. 

Why not manage a separate file for these values and use it separately for your API-GW needs on the client app?

**Comment by mrducky4** [comment]
A separate file would be fine. But how can my client app tell which environment it is running in? I looked for something like "environment": "dev" in aws-exports.js, but can't find anything. I'm probably missing something simple, I'm new to amplify and react.

**Comment by mrducky4** [comment]
I see @yuth labeled this as an enhancement rather than a question. Does that mean there is currently no good way to accomplish what I'm trying to do? Is there any way at all?

**Comment by mrducky4** [comment]
I found what I was looking for. I needed to use REACT_APP_xxxx environment variables at build time, described in [Create React App docs](https://create-react-app.dev/docs/adding-custom-environment-variables/). In Amplify Console, I can enter these environment variables with different values for different branches, to be used at build time. I assume the other frontend frameworks have a similar mechanism.

So this solves my problem, it is fine with me to close this issue. But if you think this is a useful enhancement request you can keep it open.

**Comment by MatteoInfi** [comment]
But this looks like a temporary workaround rather than a valid solution. At least according to what is written on the `aws-exports.ts` file. 
```
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
```

**Comment by josefaidt** [comment]
Hey @mrducky4 :wave: this is accomplishable through providing API details to `Amplify.configure()` in your frontend app https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js/#manual-setup-reference-existing-rest-api

```js
import { Amplify, API } from 'aws-amplify';

Amplify.configure({
    // OPTIONAL - if your API requires authentication 
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab', // REQUIRED - Amazon Cognito Identity Pool ID
        region: 'XX-XXXX-X', // REQUIRED - Amazon Cognito Region
        userPoolId: 'XX-XXXX-X_abcd1234', // OPTIONAL - Amazon Cognito User Pool ID
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3', // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    },
    API: {
        endpoints: [
            {
                name: "MyAPIGatewayAPI",
                endpoint: "https://1234567890-abcdefgh.amazonaws.com"
            },
            {
                name: "MyCustomCloudFrontApi",
                endpoint: "https://api.my-custom-cloudfront-domain.com",

            }
        ]
    }
});
```

Closing issue in favor of manual approach. Please also refer to https://github.com/aws-amplify/amplify-cli/issues/4364 for further updates regarding adding the environment name to `aws-exports.js`
