### ISSUE TITLE
Deploying via CI

### ISSUE THREAD

**Issue by steveparkerSG** [aws-amplify/amplify-cli#3292]
What is the appropriate way of deploying via CI tool (e.g. Jenkins)? I have my project in github with the generated .gitignore. After clone, I use a headless script such as is below:

```
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":false\
}"
AMPLIFY="{\
\"envName\":\"master\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes
```

With init, this immediately triggers cloudformation updates, I think replacing the deployment bucket. Should I modify the .gitignore with something to prevent this?

If I instead try to pull, I get the following error

```
Failed to pull the backend.
TypeError: Cannot read property 'region' of undefined
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/attach-backend.js:18:81)
    at Object.attachBackend (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:29:3)
```

**Comment by SwaySway** [comment]
Hello @steveparkerSG 
if you are looking at CI options with Amplify I would recommend looking at Amplify Console.
https://github.com/aws-amplify/amplify-console

As for using a script I would recommend taking a look a the amplifyPush script
https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh

**Comment by UnleashedMind** [comment]
The error you got is a bug in the headless `amplify pull` if the config level is set to 'general', I've sent a fix for it. For now, please use 'project' config level in your headless parameter, and provide a profile for it (see the sample below).

CI work would be: 
- You push your development to code repo (such as github), your CI engine is notified and pulls down the latest development. 
- Then in the CI engine, you will need to fully setup your project by either running the headless 'amplify pull' script if you know the Amplify Console AppId, or the headless 'amplify init` script if you don't have it or your project is setup in a region that does not have Amplify Console Service. After this step, the frontend config file, such as the aws-exports.js file for the javascript web app, is in place.
- Continue with your frontend build and deployment...

Sample Headless Pull: 

``` bash
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"appId\":\"AmplifyConsoleAppId\",\
\"envName\":\"dev\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify pull \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--no-override \
--yes
```

Sample Headless Init: 
```bash
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"projectName\":\"cicdproject\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"

amplify-dev init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--codegen $CODEGEN \
--yes
```

**Comment by steveparkerSG** [comment]
This approach works often, but it's completely inconsistent. When I run the script to deploy certain changes, it works fine, updating CloudFormation as expected. Other times, I get auth issues e.g.

```
Error: Profile configuration is missing for: default
    at Object.getProfiledAwsConfig (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/system-config-manager.js:82:11)
```

```
Error: Unable to upload trigger files to S3
    at uploadFiles (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:49:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

These occur directly after some CloudFormation updates have succeeded.

**Comment by UnleashedMind** [comment]
@steveparkerSG 
I will check on those and if those were bugs, will send the fixes. Thanks for pointing them out.

**Comment by steveparkerSG** [comment]
The issue here is around how much amplify init does. It tries to do a full deploy, giving me no chance to run `amplify pull` before a deployment. Therefore every single time I run a CI job, it thinks it has changes, and repeats a redundant deployment. 

If I locally do an amplify pull for the enviroment and check-in the generated cloudformation stack files, then all is fine, but this is no kind of workflow at all. As it stands I'm better off doing local deploys.

**Comment by UnleashedMind** [comment]
Have you tried to run the `amplify pull` command in headless mode? 

https://aws-amplify.github.io/docs/cli-toolchain/usage#amplify-pull-parameters

You can supplied the credentials and region in a profile and put in the headless command parameter

**Comment by steveparkerSG** [comment]
@UnleashedMind I gave up trying to make it work, it was just too inconsistent and difficult. I moved deploys into Amplify Console as suggested by @SwaySway, which has made my life a lot easier.

**Comment by kaustavghosh06** [comment]
Closing this issue. @steveparkerSG Let us know if you have any issues deploying via the console.

**Comment by ajhool** [comment]
@UnleashedMind 

Please consider reopening this issue because "use Amplify Console" for CI is not a real solution. For example, my app needs to deploy to a Server-Side Rendering engine and I use next.js + now/vercel to do that. In order to use `amplify env` successfully, I have to be able to create a production `aws-exports.js` in CI and keep `aws-exports.js` in .gitignore.

**Comment by ahansson89** [comment]
"use Amplify Console" is not the solution for this. I get too many errors with `amplify init` trying to deploy before the stack is ready for it. Please decouple init and push so that we can get some decent deployment consistency or at least provide a flag for `amplify init --no-push` so that we can choose when we do that in our pipelines outside of Amplify Console, which is just not cutting it for advanced pipelines or if you are just deploying a backend without a web frontend.

**Comment by cyrfer** [comment]
For those coming here for examples with Jenkins or other CICD, I assume the doc linked below is the current interface.
https://docs.amplify.aws/cli/usage/headless

**Comment by scartill** [comment]
The following fragment may help:


echo "n\n" | amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS
