### ISSUE TITLE
Bug, codegen for enum on swift

### ISSUE THREAD

**Issue by jorge-rocksaucestudios** [aws-amplify/amplify-cli#3297]
**Describe the bug**
The enun generated causes compilation errors

**Amplify CLI Version**
4.12.0

**To Reproduce**
amplify pull
amplify configure codegen
amplify codegen

**Expected behavior**
for ...
enum UserStatus {
  ...
  UNKNOWN
  ...
}

It should only generate 7 cases, 

if an enum in GraphQL has a property named "UNKNOWN", amplify code gen creates a build error in swift 5, generating case plus UNKNOWN(...)

- NO IS NORMAL ....

**Screenshots**
...

**Desktop (please complete the following information):**
 - OS: [macOS Catalina, Version 10.15.2  MacBook Pro (15-inch, 2018)]
 - Node Version. v13.6.0

**Additional context**
Intergration SDk with iOS, with AppSync and Cognito

**Comment by yuth** [comment]
@jorge-rocksaucestudios  Could you share a minimal schema which can cause this error in Swift generated code

**Comment by olivoil** [comment]
@yuth this happens when following the example for the `me` in [amplify's @function documentation](https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js)

The following schema will created a `UserStatus` enum with two `unknown` values, one based on the graphql enum value `UNKNOWN`, one for Swift 5's `@unknown default` entry:

```
type Query {
  me: User @function(name: "ResolverFunction")
  echo(msg: String): String @function(name: "ResolverFunction")
}
# These types derived from https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminGetUser-property
type User {
  Username: String!
  UserAttributes: [Value]
  UserCreateDate: String
  UserLastModifiedDate: String
  Enabled: Boolean
  UserStatus: UserStatus
  MFAOptions: [MFAOption]
  PreferredMfaSetting: String
  UserMFASettingList: String
}
type Value {
  Name: String!
  Value: String
}
type MFAOption {
  DeliveryMedium: String
  AttributeName: String
}
enum UserStatus {
  UNCONFIRMED
  CONFIRMED
  ARCHIVED
  COMPROMISED
  UNKNOWN
  RESET_REQUIRED
  FORCE_CHANGE_PASSWORD
}
