### ISSUE TITLE
`amplify codegen model` generates Swift `enum`s that don't conform to `Codable`

### ISSUE THREAD

**Issue by cpiro** [aws-amplify/amplify-cli#3299]
In the latest version 4.13.1, generated Swift `enum`s don't conform to `Codable`. For example:

```graphql
type Post {
  kind: PostKind
}

enum PostKind {
  interesting
  boring
}
```

While attempting to build the generated output, the Swift compiler fails with the following errors:
- Type `Post` does not conform to protocol `Decodable`
- Type `Post` does not conform to protocol `Encodable`
- Cannot automatically synthesize `Encodable` because `PostKind?` does not conform to `Encodable`

### Expected behavior
The output `enum` should be declared to conform to `Codable`. By adding the following lines to `amplify/generated/models/PostKind.swift` by hand, the compiler succeeds at synthesizing `Codable` implementations for `PostKind`, and my project builds correctly:

```swift
extension PostKind: Codable {
}
```

### Versions
```
$ uname
Darwin
$ amplify -v
4.13.1
$ node -v
v13.6.0
$ swift --version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.2.0
```

### To Reproduce
Install the CLI, then run `amplify init`, `amplify add api`, and `amplify codegen model`, then compile the generated code. I choose `ios` as the "type of app that you're building".

```
$ npm install -g @aws-amplify/cli@latest
[...]
+ @aws-amplify/cli@4.13.1

$ amplify init
[...]
? Choose the type of app that you're building ios
[...]

$ cat > minimal.graphql
type Post {
  kind: PostKind
}
enum PostKind {
  interesting
  boring
}

$ amplify add api
[...]
? Provide your schema file path: minimal.graphql
[...]

$ amplify codegen model

GraphQL schema compiled successfully.

Edit your schema at [...] or place .graphql files in a directory at [...]
Successfully generated models. Generated models can be found [...]

**Comment by yuth** [comment]
What version of Amplify CLI is used to generate the swift code?

**Comment by cpiro** [comment]
The latest, 4.13.1. See above: 
```
$ amplify -v
4.13.1
```

**Comment by yuth** [comment]
This needs changes in Amplify iOS Data store client which is tracked in https://github.com/aws-amplify/amplify-ios/issues/246
