### ISSUE TITLE
npm install -g @aws-amplify/cli fails with errors

### ISSUE THREAD

**Issue by rafachurre** [aws-amplify/amplify-cli#33]
Do you want to request a feature or report a bug?
BUG

What is the current behavior?
When installing AWS Amplify CLI, it fails logging the following errors and warnings

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! path C:\Users\rafae\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\npm\node_modules\ansistyles
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\rafae\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\rafae\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\npm\node_modules\.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rafae\AppData\Roaming\npm-cache\_logs\2018-08-27T10_51_24_414Z-debug.log

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
run the command > npm install -g @aws-amplify/cli

What is the expected behavior?
install the Amplify CLI with no errors

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
Trying to install the latest version available in npm, using Windows10

**Comment by RoniqueRicketts** [comment]
I have this issue right now, I uninstalled the CLI and reinstalled it same issue.
