### ISSUE TITLE
functions that listen to S3 events

### ISSUE THREAD

**Issue by gavinwilliams** [aws-amplify/amplify-cli#330]
Is this possible without having to interact with the AWS console?

**Comment by kaustavghosh06** [comment]
@gavinwilliams That's not possible currently. I'm marking this as a feature request to discuss with the team.

**Comment by et304383** [comment]
Any word on this?

**Comment by kaustavghosh06** [comment]
@gavinwilliams We've released Lambda triggers functionaity for S3. You can find more information out here - https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/
