### ISSUE TITLE
Accessing AppSync in Lambda

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#3302]
**Which Category is your question related to?**
AppSync, Lambda, Auth

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
AppSync, Lambda, Auth

**Provide additional details e.g. code snippets**
I set up a graphql AppSync API using amplify and I need to be able to query it in a lambda function. How can I do that? I am using Cognito User Pools for authentication on the graphql API and I am not sure how to configure a request in order to query the API in a lambda function. I have read the documentation on [building a lambda client](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html) that seems to achieve what I want, but I am confused about the proper auth mode I should be using as the docs mention both Cognito User Pools and IAM as possiblities. In the context of my app, the lambda function is called when a user wants to send an email to another user. I basically want to query the graphql API, and then shoot an email off.

**Comment by dantasfiles** [comment]
Here's one example: https://github.com/aws-amplify/amplify-cli/issues/3221#issuecomment-576807990

**Comment by dantasfiles** [comment]
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

**Comment by yuth** [comment]
Feel free to comment here if you are still having issues in using the docs linked above

**Comment by karrettgelley** [comment]
@yuth Hey so I copied the code from the docs and tried to run a query and I get the following error: "No operation matches the provided operation name <some operation>". But when I look at my graphql api, <some operation> is there, and I can in fact query it via the console. What might this mean? I made to to give crud rights to my lambda function on the graphql api
