### ISSUE TITLE
Working with GraphQL playground / Queries after enabling Cognito is unclear

### ISSUE THREAD

**Issue by IljaDaderko** [aws-amplify/amplify-cli#331]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
When creating GraphQL api that uses `@auth` template, we require to use Cognito as authentication mechanism.

After it is set up, we need to authenticate in AppSync console -> Queries in order to use GraphQL playground and view documentation. Authentication dialog requires `ClientID`, `Username` and `Password` and there are several issues I found

1. ClientID / AppID generated by aws amplify have `...app_clientWeb` and `...app_client` details. I initially used `...app_client` one that has a secret and kept getting errors until I realised that I need to use another app id that has no secret. I feel like all of this is a bit unclear at the moment.

2. In AppSync console name `ClientID` is used instead of `App client ID` from Cognito.

3. Assuming my app only uses federated sign in mechanisms from google and facebook, how would I use them to log into AppSync console, since it only allows for username and password auth? Regarding this, say we only want to allow facebook login, is it possible to disable default username / email login?

**Comment by mikeparisstuff** [comment]
Thanks for the suggestion. It seems like you were able to figure it out but here is a suggestion for others that may be facing this same confusion. You can easily find metadata such as the User Pools ClientID by looking at `amplify-meta.json` file in your project. Inside it you will see a section per category with high level details on the project's resources. For example, you will see something like this for the auth category.

```
"auth": {
		"cognito6765b762": {
			"service": "Cognito",
			"providerPlugin": "awscloudformation",
			"providerMetadata": {
				"s3TemplateURL": "https://s3.amazonaws.com/searchtest-20190307103316-deployment/amplify-cfn-templates/auth/cognito7291b784-cloudformation-template.yml",
				"logicalId": "cognito7291b784"
			},
			"lastPushTimeStamp": "2019-03-08T23:00:06.545Z",
			"output": {
				"AppClientSecret": "1h8s2pnltdgr8ajalsudmn9491als8dje8ald82j801pstcm16q",
				"UserPoolId": "us-west-2_9sald7wkjdf",
				"AppClientIDWeb": "6abi2s6g29a83jdlkf3preikc0t",
				"AppClientID": "7q8c80ma7sdjwldibde3d6gl5c",
				"IdentityPoolId": "us-west-2:d4d76bea-202d-4116-b83e-a5a7dhcac3357",
				"IdentityPoolName": "cognito6765b762_identitypool_18djal762__dev",
				"UserPoolName": "cognito6765b762_userpool_71jd9762"
			},
			"lastPushDirHash": "hUSB7DNp5ehFUrAhH882KMJxNd8="
		}
	}
```

When using the AppSync console's query tab, you will use the "AppClientIDWeb" for the Client ID as well as your own username & password for the user configured in the user pool. I will make an note to update the docs with this information.
