### ISSUE TITLE
Iteratively work and switching between environments

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-cli#3310]
**Which Category is your question related to?** 
Environments

**Amplify CLI Version**  
4.12.0

**What AWS Services are you utilizing?** 
Cognito, Appsync, Lambda

**Provide additional details e.g. code snippets**
I have 3 envs and 3 git brances:

| env  | branch  |
|---|---|
| develop  | develop  |
|  test | test  |
|  prod | master  |

I followed the [Environments and Teams - Concept documentation](https://aws-amplify.github.io/docs/cli-toolchain/quickstart?sdk=js#concepts-1)
and using this workflow:
![](https://aws-amplify.github.io/docs/cli-toolchain/images/AmplifyEnvAddDeploySwitching.jpg)

every time that I merge develop into test branch the `cloudformation-template.js` of every function added to the project is messed up with the merge origin data written over the destination branch data

I noticed that the values of files
`<function_name>-cloudformation-template.json`

in the properties paths:
`Resources > LambdaFunction > Properties > Code > S3Bucket`
`Resources > LambdaFunction > Properties > Code > S3Key`

are always overwritten and later I have to make another commit fixing every template.

This should be somehow prevented .

Is this behavior normal or am I doing something wrong?

**Comment by kaustavghosh06** [comment]
@AlessandroAnnini Please follow the guidance provided in https://github.com/aws-amplify/amplify-cli/issues/3456.

**Comment by kaustavghosh06** [comment]
Also here - https://github.com/aws-amplify/amplify-cli/issues/3034
