### ISSUE TITLE
AppSync - amplify gql compile - add distinct compile directory

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-cli#3317]
Hi,

Once we have defined a schema (with `@model` directives), running `amplify gql compile` or `amplify push` implies a generation of stacks and resolvers in a `build` directory.

We can override these files: for example we can hide `Mutation.createX.req.vtl` in `resolvers` directory that will be set in `build` directory instead of automatically generated one.

What is then difficult to manage is to check after modifying our `schema.graphql` file if we need to update or customized `Mutation.createX.req.vtl`

What I do is:

- first rename `Mutation.createX.req.vtl` into `Mutation.createX.req.back`
- run `amplify gql compile`
- compare generated file with customized one

It would be great if we could have a distinct directory (called `compile` for example) that contains result of automatic generation, in order to easily compare deployed content with compiled one

**Comment by ChristopheBougere** [comment]
I have the same issue, which makes me commit generated files of 100 lines just to add 2 lines. Each time I update my `@auth` or the schema, I have to ensure that VTL files are still up to date.

Another solution that I can think is to have some static placeholders in a VTL (things like `beforeAuth`, `afterAuth`, `beforePreparingRequest`, `afterPreparingRequest`).
And we would store pieces of code to include in multiple files `api/{apiName}/resolvers/{resolverName}/{placeholderName}.vtl`.
