### ISSUE TITLE
Function : Could not retrieve file from S3

### ISSUE THREAD

**Issue by TheUncharted** [aws-amplify/amplify-cli#3318]
**Describe the bug**
After granting read permission to perform on storage S3 to the function, 
the function can't get an object in s3  and return the message ""Could not retrieve file from S3: The specified bucket does not exist"

The generated iam policy and bucket name seems to be not correct.

In aws, the bucket name seem to be not replaced by its true value/name
[screenshot](https://imgur.com/8GDhAYa)

Same in lambda logs, the environment variable is not replaced : 
STORAGE_RECIPE_BUCKETNAME: 'storagerecipeBucketName',

In the cloudformation template : 

```
 {
    "Effect": "Allow",
    "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:DeleteObject"
    ],
    "Resource": [
        {
            "Fn::Join": [
                "",
                [
                    "arn:aws:s3:::",
                    {
                        "Ref": "storagerecipeBucketName"
                    },
                    "/*"
                ]
            ]
        }
    ]
}
```

In amplify-meta.json

```
"storage": {
    "recipe": {
        "service": "S3",
        "providerPlugin": "awscloudformation",
        "dependsOn": [
            {
                "category": "function",
                "resourceName": "myfunction",
                "attributes": [
                    "Name",
                    "Arn",
                    "LambdaExecutionRole"
                ]
            }
        ],
        "providerMetadata": {
            "s3TemplateURL": "https://s3.amazonaws.com/xxxxxxxx-deployment/amplify-cfn-templates/storage/s3-cloudformation-template.json",
            "logicalId": "storagerecipe"
        },
        "lastPushTimeStamp": "2020-02-01T16:21:19.347Z",
        "output": {
            "BucketName": "recipexxxxxxxxxxxxxxxxxxxxx-dev",
            "Region": "eu-west-1"
        },
        "lastPushDirHash": "xxxxxxxxxxxxxxxxxxxxxxx"
    }
},
```

If I change manually the policy in aws to target the right bucket name it works

**Amplify CLI Version**
4.13.13

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
- amplify update function
- choose function
- Do you want to update permissions granted to this Lambda function to perform on other resources in your project?  --> yes
- Select the category --> storage
- Select the operations you want to permit for <NAME> --> create, read, update, delete

**Expected behavior**
The function is able to get/read an object in S3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 + wsl
 - Node Version : v12.14.0

**Additional context**
The function is triggered by s3, it works fine

**Comment by kaustavghosh06** [comment]
What's your environment name? Isn't your env-name attached to your bucket?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of requested information. Please comment on this thread if you're still seeing this issue.
