### ISSUE TITLE
amplify mock api throws dynamodb emulator error for amplify version 4.13.1

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#3319]
**Describe the bug**
Failed to start API Mock endpoint Error: max retries hit for starting dynamodb emulator

**Amplify CLI Version**
$ amplify --version
4.13.1

**To Reproduce**
I had amplify mock api command working perfectly fine. I just upgrade the amplify-cli package using the command -- $ npm install -g @aws-amplify/cli

The package upgraded properly to 4:13.1 and then the amplify mock would not start with the above error

**Desktop (please complete the following information):**
I am using Cloud9 Amazon Linux

$ node -v
v10.16.2

**Additional context**

I think I was on 4.12 before the upgrade

**Expected behavior**
The local DynamoDB should run and it should create the local tables. Please note that I did not change anything in the schema that could have caused this issue. 

Also when I press ctrl-c to exit the process, I keep getting the following error that does not go away.
^C(node:3863) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stop' of undefined
    at APITest.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:74:41)
    at Generator.next (<anonymous>)
    at /home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:4:12)
    at APITest.stop (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:58:16)
    at APITest.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:31:32)
    at Generator.next (<anonymous>)
    at /home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:8:71
    at new Promise (<anonymous>)
(node:3863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arkllc** [comment]
I tried a few things but it still did not work. 
Based on another issue, I ensured that lsof is installed.
Also tried upgrading node to 12.14.1

Based on https://github.com/aws-amplify/amplify-cli/issues/2062 I tried installing 

brew cask install java

but I am on amazon linux and using Cloud9 IDE and cask is only valid on MacOS. Appreciate any help. Interestingly it just started once I upgraded to the latest amplify cli. Not sure how to solve this now.

**Comment by arkllc** [comment]
So after struggling with this issue for more than a week, I was finally able to solve it. The problem is that some package(s) in amplify version 4.13.1 or 4.13.2 needs the Java 1.8+. And Amazon Linux comes with java version 1.7. So I had to upgrade the Java as outlined here https://stackoverflow.com/questions/28302616/how-can-i-upgrade-to-java-1-8-on-an-amazon-linux-server 

Such a bummer as I lost a week...

**Comment by arkllc** [comment]
thanks for fixing this

**Comment by niyazpk** [comment]
This is not a user error. The error message should be fixed so that others will not run into the same issue.
