### ISSUE TITLE
Error updating API since updating to the latest amplify-cli

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-cli#3330]
I am receiving this error while updating graphql API with `amplify serve/push/publish`

`
CREATE_FAILED fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-ProjectStaff-1BMX33S2FV7H4 AWS::CloudFormation::Stack Tue Feb 04 2020 15:31:44 GMT+1100 (Australian Eastern Daylight Time) Export with name kxs65t6t6ndxrf3mna34iollhm:GetAtt:ProjectStaffDataSource:Name is already exported by stack fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-Staff-1RZTFGK7TTJKK
`
For some reason, I have the exact same identical dev stack, but the dev side works fine, the master one fails with this error...

I'm not sure what is happening, but the problem has only occurred since updating to the latest amplify-cli.

**Comment by UnleashedMind** [comment]
CloudFormation export key names are unique per region in your AWS account.
In you case, these two DIFFERENT stacks are exporting the same key
- fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-ProjectStaff-1BMX33S2FV7H4
- fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-Staff-1RZTFGK7TTJKK
You can open your CloudFormation console in that particular region and click open `Exports` to see all the exports. The Amplify CLI in general decorates the export keys with a random string to avoid conflicts. 
Could you check if you can remove the other stack that's causing the conflict?

**Comment by michaelcuneo** [comment]
I haven't changed any stacks manually or modified anything for this to occur... why would it suddenly do this? I've been searching through the CloudFormation Exports area for ProjectStaff... and Staff... If I delete any of these, will it delete my dynamoDB tables, or anything like that?

I've just screenshot the entire area filtered by Stacks, and Exports. It appears as though. ProjectStaff doesn't exist?

<img width="1917" alt="Screen Shot 2020-02-05 at 11 09 24 am" src="https://user-images.githubusercontent.com/12700009/73798877-5028a280-4808-11ea-8a5c-5405dc4d3ad5.png">

<img width="2619" alt="Screen Shot 2020-02-05 at 11 10 55 am" src="https://user-images.githubusercontent.com/12700009/73798879-5454c000-4808-11ea-839b-e7585cacb911.png">

<img width="2619" alt="Screen Shot 2020-02-05 at 11 11 10 am" src="https://user-images.githubusercontent.com/12700009/73798886-56b71a00-4808-11ea-863e-d14a76397ed8.png">

**Comment by michaelcuneo** [comment]
From what I can see here... ProjectStaff and Staff are both exported with the exact same stack names?

Export Name | kxs65t6t6ndxrf3mna34iollhm:GetAtt:StaffTable:Name
Export Value | Staff-kxs65t6t6ndxrf3mna34iollhm-master
Stack Name | fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-Staff-1RZTFGK7TTJKK

Export Name | kxs65t6t6ndxrf3mna34iollhm:GetAtt:ProjectStaffTable:Name
Export Value | ProjectStaff-kxs65t6t6ndxrf3mna34iollhm-master
Stack Name | fastlab-master-20190705141744-apifastlab-1ERF9XZ1ZFB5U-Staff-1RZTFGK7TTJKK

**Comment by michaelcuneo** [comment]
Ahh yes. If I filter by stack name, there are indeed issues. The ProjectStaff and Staff resources, are both using the Staff stack.

<img width="1589" alt="Screen Shot 2020-02-05 at 11 49 48 am" src="https://user-images.githubusercontent.com/12700009/73801230-e3b0a200-480d-11ea-8b48-04b676d59442.png">

What would be the best case to move forward here?
Back up all the DynamoDB Tables, Delete the Staff Stack, then try an amplify push?

**Comment by michaelcuneo** [comment]
It wouldn't allow me to delete the highest nested stack, it kept verifying my delete then rolling back to 'UPDATE_ROLLBACK_FAILED', so I've tried deleting the apifastlab stack holding all of the API Stacks, and this one appears to be actually removing the stacks, but now obviously it has dumped all my tables, so I'll just have to remove API and restore it all from the backups.

**Comment by michaelcuneo** [comment]
I managed to get everything back up by deleting the entire API stack. Pushed it back up, restore all my databases from backups, enabled the old/new ARN Steam management, and edited my IAM Roles to suit the new API ID.

All is well again.
