### ISSUE TITLE
@key on model search for multiple values for the fields

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#3331]
**Which Category is your question related to?**
graphql / DynamoDB

**Amplify CLI Version** 

4.13.1

**What AWS Services are you utilizing?**

AppSync / DynamoDB

**Provide additional details e.g. code snippets**

```
type Foo
  @model

  @key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime,
  status: PublicationStatus,
....
```

This will generate something like this:
```
  async FooStatusUpdatedAt(
    status?: PublicationStatus,
    updatedAt?: ModelStringKeyConditionInput,
    sortDirection?: ModelSortDirection,
    filter?: ModelFooFilterInput,
    limit?: number,
    nextToken?: string
  ): Promise<FooStatusUpdatedAtQuery> {
    const statement = `query FooStatusUpdatedAt($status: PublicationStatus, $updatedAt: ModelStringKeyConditionInput, $sortDirection: ModelSortDirection, $filter: ModelFooFilterInput, $limit: Int, $nextToken: String) {
        fooStatusUpdatedAt(status: $status, updatedAt: $updatedAt, sortDirection: $sortDirection, filter: $filter, limit: $limit, nextToken: $nextToken) {
```

This is great, but what if I want to search for multiple PublicationStatus values? Right now I only see a way to search for a single status. Is there another way of doing this without? (w/o multiple queries)

**Comment by dantasfiles** [comment]
The three ways I know of are to 1) do multiple fooStatusUpdatedAt queries, 2) do a DynamoDB *Scan* with the `listFoo` operation on an `and` filter (which is reall non-optimal), or 3) use a batch operation ([Link 1](https://medium.com/@jan.hesters/creating-graphql-batch-operations-for-aws-amplify-with-appsync-and-cognito-ecee6938e8ee) - [Link 2](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html)) Which one you choose is determined by your particular needs.

**Comment by malcomm** [comment]
@dantasfiles - thank you for your response. 

**1) Multiple Queries.** I'm really trying to avoid this, because I have a table that will have a lot of items in it and pagination. I have 8 different statuses here in play and so just managing all that gets a little complicated quickly. Not to mention really inefficient.

**2) Scan/List.** I'm currently doing this but the data coming back is not sorted by what I want ("updatedAt"). This is one of the reasons why I have a named @key with a sort field on it.

**3) Batch operations.** Batch operations just seem so painful. I wasn't aware of them until now, so thank you. I scanned the links you sent and I don't see a great pathway to write a simple get for these, I will continue to look into them, but this seems less than ideal.

But that still has me scratching my head on this one ... why not just support multiple here? (via the normal and, or, eq ... etc.)

**Comment by dantasfiles** [comment]
2. The reason your scans are not coming back sorted is because your default primary index, used by the `listFoo` operation, is `id`. You have to override that with an additional directive like `@key(fields: ["id", "updatedAt"])`. 
Scans touch every element of a DynamoDB table, so they can be very expensive and you want to avoid them.

There's another way--I remembered a post I read:
https://dev.to/open-graphql/graphql-recipes-building-apis-with-graphql-transform-3jp0#events-app

```
type Foo
  @model
  @key(name: "FooStatusUpdatedAt", fields: ["queryName","status"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime,
  status: PublicationStatus,
  queryName: String!
```
The queryName of every item is always `"Foo"`

The gives you   
`fooStatusUpdatedAt(queryName: String, status: ModelStringKeyConditionInput, sortDirection: ModelSortDirection, filter: ModelFooFilterInput, limit: Int, nextToken: String): ModelFooConnection`
where `ModelStringKeyConditionInput` is
```
input ModelStringKeyConditionInput {
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  between: [String]
  beginsWith: String
}
```

It's not what you want, but maybe you can figure something clever out with the `between` or  `beginsWith` conditions

**Comment by malcomm** [comment]
Yeah during my reply to you I was investigating the primary index. I got stopped by two things:

```
type Foo
  @model
  @key(fields: ["id", "updatedAt"])
  @key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime,
  status: PublicationStatus,
....
```

Resulted in this:
```
The primary @key on type 'StudyEncounter' must reference non-null fields.
```

So I've run into this before ... and I have to say **createdAt** and **updatedAt** should be automatically available and we shouldn't have to declare them in the schema. To get around this, I have to do:

```
  updatedAt: AWSDateTime!,
```

So now, I'm required to supply an **updatedAt** from the client .... which is just wrong. 

Even with that ... I changed the primary index and got this error:

```
UPDATE_FAILED SubscriptiononUpdateFooResolver AWS::AppSync::Resolver Tue Feb 04 2020 12:55:28 GMT-0800 (Pacific Standard Time) Resource update cancelled                                                                                                                                                 
UPDATE_FAILED FooTable                        AWS::DynamoDB::Table   Tue Feb 04 2020 12:55:28 GMT-0800 (Pacific Standard Time) CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename Foo-wgujhut...2zme-foodev and update the stack again.
```

So I'm guessing I have to manually delete the index and then allow this update to happen to re-create. This is really frustrating from an app dev perspective.

**Comment by dantasfiles** [comment]
So the "dumb" solution to the "I'm required to supply an updatedAt from the client" issue is to change the line in Mutation.createFoo.req.vtl to 
```
$util.qr($context.args.input.put("createdAt", $util.time.nowISO8601())
```

For the second issue, you might have to do an `amplify remove api` first or something unpleasant.

**Comment by malcomm** [comment]
@mikeparisstuff - I wonder if you might be able to weigh in on this. Basically at this point I have a model looking like this:

```
type Foo
  @model
  @key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime,
  status: PublicationStatus,
```

And then I try and change the primary index to:

```
type Foo
  @model
  @key(fields: ["id", "updatedAt"])
  @key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime!,
  status: PublicationStatus,
```

And I can't do an ```amplify push```. This is even after I manually delete the primary index. IMHO - amplify-cli should be smart enough to see that the primary index is no longer there and re-create no?

Also if you might be able to provide any insight into the fact that my original problem (see description).

Thank you!

**Comment by malcomm** [comment]
OK so I just realized that I was not actually deleting the primary index (I don't think there's really a way to do this??? - not sure why that's not supported by DynamoDB???).

**Comment by edwardfoyle** [comment]
You are correct that once a DynamoDB table has been created, the primary key cannot be changed.

I'm going to close this issue and continue to follow up in #3347 because it seems like they are both converging to the same underlying problem.
