### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by erhard** [aws-amplify/amplify-cli#3332]
**Which Category is your question related to?**
CORS Request

**Amplify CLI Version** 
4.9.0

**What AWS Services are you utilizing?**
function, api(Rest).   
What was he error ?  I made the screencast https://www.youtube.com/watch?v=PswB47WJ4Xk
it runs locally with amplify function invoke on port 3000.  But pushing it I get a CORS failure.
Even if I extend the CORS header with the http function names in the app.js

Maybe it is the Api Gateway but how do I manage cors there with amplify ?

**Comment by edwardfoyle** [comment]
@erhard can you provide more information on how you set up the function? Using the "Serverless express function" option when creating the lambda function should take care of CORS configuration. Using the latest version of the CLI I was able to invoke the API without issue.

**Comment by erhard** [comment]
@edwardfoyle  Thanks for your response.  I have found the Error :   If there is no slash in the path this error comes up.    You can simply test it: API.get("aname", "/items").   and API.get("aname","items") (in chrome)  I do not know why this misleading error comes up.
