### ISSUE TITLE
codegen on pull: Codegen when pulling in another frontend

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#3334]
**Is your feature request related to a problem? Please describe.**
When doing ```amplify pull```, if codegen is present in the main project (also with apiId), execute a codegen il the project that is pulling amplify.

**Describe the solution you'd like**
Would be great if CLI generates all graphql types and statements when pulling in another frontend (even when codegen is added with apiId).

**Comment by kaustavghosh06** [comment]
Closing as a duplicate of #5251
