### ISSUE TITLE
Auto-Generated Resolvers does not work with custom Partition Key and Sort Key

### ISSUE THREAD

**Issue by lesmuc** [aws-amplify/amplify-cli#3336]
**Describe the bug**
Models with directive @versioned cannot be updated or deleted with the auto-generated resolver.

**Amplify CLI Version**
4.13.1

**To Reproduce**
Steps to reproduce: https://aws-amplify.github.io/docs/cli-toolchain/graphql#versioned
Result: Conflict, Changes are rejected, title is not updated.

**Expected behavior**
Like described in the example above, title should be updated and version should be raised from 1to 2, because it's a valid update without any conflict.

**Comment by attilah** [comment]
@lesmuc Could you please be more specific on what operations are not working, what is your schema, mutation, input and expected result. You are referring to the ```updatePost

**Comment by lesmuc** [comment]
@attilah Here is the schema from the documentation:
[schema.graphql.txt](https://github.com/aws-amplify/amplify-cli/files/4169190/schema.graphql.txt)

$ amplify push && amplify codegen

And here are the auto-generated resolver:
[createPost.txt](https://github.com/aws-amplify/amplify-cli/files/4169232/createPost.txt)
[updatePost.txt](https://github.com/aws-amplify/amplify-cli/files/4169231/updatePost.txt)
[deletePost.txt](https://github.com/aws-amplify/amplify-cli/files/4169230/deletePost.txt)

The **createPost** works as expected, created
{
  "data": {
    "createPost": {
      "id": "65fe804f-25cb-468b-b18c-59be84cf03ab",
      "title": "Conflict detection in the cloud!",
      "version": 1
    }
  }
}

But the following **updatePost** leads to a **Conflict encountered on version mismatch between client and server**.
mutation Update($postId: ID!) {
  updatePost(
    input:{
      id: $postId,
      title: "Conflict detection in the cloud is great!",
      expectedVersion: 1
    }
  ) {
    id
    title
    version # will be 2
  }
}

[updatedPostLogs.txt](https://github.com/aws-amplify/amplify-cli/files/4169240/updatedPostLogs.txt)

**Comment by attilah** [comment]
@lesmuc am I correct that when you setup your API you said yes to conflict resolution? If that's the case then that setting is for the DataStore feature, not for the ```@versioned``` directive. For the version directive you don't need any additional feature like conflict resolution to be configured.

**Comment by lesmuc** [comment]
@attilah Thanks for your help and message. You're right!
Removed the @versioned directive from the schema. The datastore is still configured with AUTOMERGE. But unfortunately I still get a **rejected** by the server. Please see below for details.

[schema.graphql.txt](https://github.com/aws-amplify/amplify-cli/files/4180948/schema.graphql.txt)

The createPost works as expected, here is the response:

`{
  "data": {
    "createPost": {
      "id": "test-post-id",
      "title": "This is just a test post.",
      "_lastChangedAt": 1581341446800,
      "_version": 1,
      "_deleted": null
    }
  }
}`

But the following updatePost does not update the item with the title. Only the version was incremented. 

**Update Post Mutation**

`mutation UpdatePost($input:UpdatePostInput!) {
  updatePost(input:$input) {
    id
    title
    _lastChangedAt
    _version
    _deleted
  }
}`

**Input variables**

`{
  "input": {
    "id": "test-post-id",
    "title": "This is just an UPDATE for the test post."
  }
}`

**Result**
{
  "data": {
    "updatePost": {
      "id": "test-post-id",
      "title": "This is just a test post.",
      "_lastChangedAt": 1581341792100,
      "_version": 2,
      "_deleted": null
    }
  }
}

And in the CloudWatch logs we see the rejection.
[UpdatedPostLogs.txt](https://github.com/aws-amplify/amplify-cli/files/4181091/UpdatedPostLogs.txt)

**Comment by lesmuc** [comment]
@attilah I've got help from the AWS support team. Here is the answer:

This issue seems to be related how amplify generates the schema based on the introduction of a custom primary key. When I use the model without defining user id as the primary key by using the default id as the primary key, it works as expected and doesn't throw this error. However when defining a custom primary key it fails each time.

**Comment by attilah** [comment]
@lesmuc we've multiple things colliding here I think:
- If you want to call the mutations AND have optimistic concurrency:  use the @versioned directive and do not enable sync, you can use custom Id fields with @key.
- If you want to use DataStore which gives you much more capabilities in terms of managing the data and conflicts for you, then turn on sync, and do not use @versioned directive as there is no need for that. In this case do not call the mutations by hand since all those fields what the CLI generates for DataStore enabled projects will be automatically handled by the DataStore client libraries. This currently does not support custom Id fields.

Please pick a version of the two that is closer to your use case. I'm closing the issue if something new comes up feel free to reopen it or open a new one.

**Comment by lesmuc** [comment]
> * If you want to use DataStore which gives you much more capabilities in terms of managing the data and conflicts for you, then turn on sync, and do not use @versioned directive as there is no need for that. In this case do not call the mutations by hand since all those fields what the CLI generates for DataStore enabled projects will be automatically handled by the DataStore client libraries. This currently does not support custom Id fields.
> 
> Please pick a version of the two that is closer to your use case. I'm closing the issue if something new comes up feel free to reopen it or open a new one.

Sorry, but I'm not happy about that. From the documentation it's not obviously that custom id fields are not supported. So for me it's a bug and this should be solved. 

And a colleague from the AWS support team (Garreth B.) confirmed this issue already by saying:

> This issue seems to be related how amplify generates the schema based on the introduction of a custom primary key. When I use your model without defining user id as the primary key by using the default id as the primary key, it works as expected and doesn't throw this error. However when defining a custom primary key it fails each time. This seems to be a bug related with how Amplify performs its transformation to generate your model If you are still in contact with the Amplify service team on Github can you confirm with the Amplify team if this is the expected behavior.

**Comment by patstahl** [comment]
I was following @dabit3 's nice tutorial at https://github.com/dabit3/next.js-amplify-workshop, but this issue prevents any update mutations for me as well. Had some other issues with using DataStore, so using the API library with the GraphQL models has worked nicely so far. Hope you can find a fix for it, or perhaps mention the issue with any workaround in the workshop repo.
