### ISSUE TITLE
No such resource AWS::WAFv2::IPSet

### ISSUE THREAD

**Issue by tlindsay42** [aws-amplify/amplify-cli#3339]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Added WAFv2 resources to my project's API Gateway CloudFormation template, attempted to get the WAFv2 IPSet ARN attribute to reference in the WAFv2 WebACL IPSetReferenceStatement.Arn property, and get the following error when I attempt to push: `No such resource AWS::WAFv2::IPSet`. After discussing this with the CloudFormation & Uluru teams, we found that if I import as a new stack via the UI, the same template provisions successfully.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
`4.13.1`

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. Init a new project with Amplify CLI
1. Add API
1. Add the following resource in the API CloudFormation template
   ```json
    "IPSetV2": {
      "Type": "AWS::WAFv2::IPSet",
      "Properties": {
        "Addresses": ["[insert test IPv4 CIDR block]"],
        "Description": "Test IPSetV2",
        "IPAddressVersion": "IPV4",
        "Name": "test-ipsetv2",
        "Scope": "REGIONAL"
      }
    },
   ```
1. Add the following output in the API CloudFormation template
   ```json
    "IPSetV2": {
      "Description": "The WAFv2 IPSet",
      "Value": {
        "Fn::GetAtt": [
          "IPSetV2",
          "Arn"
        ]
      }
    }
   ```
1. `amplify push -y`
1. Receive error: `No such resource AWS::WAFv2::IPSet`

**Expected behavior**

Amplify CLI should not throw an error for a valid get attribute call.

**Screenshots**

**Screenshot 1: Console error**
![image](https://user-images.githubusercontent.com/11078689/73795169-9da50100-476f-11ea-959d-4c5239f6899e.png)

**Screenshot 2: CloudFormation Console: Template tab when template is imported via UI**
![image](https://user-images.githubusercontent.com/11078689/73795357-042a1f00-4770-11ea-91f5-2648fcdb2031.png)

**Screenshot 3: CloudFormation Console: Outputs tab when template is imported via UI**
![image](https://user-images.githubusercontent.com/11078689/73795286-e0ff6f80-476f-11ea-9d18-7bd052d6588b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
   `Ubuntu 18.04.3 LTS`
 - Node Version. You can use `node -v` to check the node version on your system
   `v12.14.0`

**Additional context**

N/A

**Comment by kaustavghosh06** [comment]
@tdslinden With the latest version of the CLI I was able to deploy an IPSetV2 resource. Please make sure to add this resource under the "Resource" key

```
"Resources": {
		"IPSetV2": {
			"Type": "AWS::WAFv2::IPSet",
			"Properties": {
				"Addresses": [
					"10.1.1.1"
				],
				"Description": "Test IPSetV2",
				"IPAddressVersion": "IPV4",
				"Name": "test-ipsetv2",
				"Scope": "REGIONAL"
			}
		},

```

If you're still stuck, you can send your Cloudoformation file to `amplify-cli@amazon.com` and we can dig deeper.

**Comment by tlindsay42** [comment]
@kaustavghosh06, you only followed half the steps to reproduce, which is why you failed to duplicate the issue.

Also, just updated the CLI and confirmed that I can still duplicate. Will send an email as requested.

**Comment by UnleashedMind** [comment]
Reproduced the issue.
The Amplify CLI uses ["cfn-lint"](https://www.npmjs.com/package/cfn-lint) to validate the Cloudformation template file. 
In this particular case, there is an issue with its validation.

**Comment by Ochaun** [comment]
This is still an issue.

**Comment by baartch** [comment]
The same happens to me with `AWS::WAFv2::WebACL`

```
Invalid CloudFormation template: /home/****/****/amplify/backend/customResources/WAF/template_WAF.yaml
No such resource AWS::WAFv2::WebACL
```

But, the good thing to me is, the resource is being created and works fine.
![image](https://user-images.githubusercontent.com/26668031/117117671-1d18ea00-ad90-11eb-84f6-cb7752ab4dc7.png)
