### ISSUE TITLE
Is there a way to delete a specific elasticsearch index?

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#3341]
We have already many indices in our elasticsearch but I want to recreate a specific index, so I'm planning to delete that index only. I tried removing the searchable flag but that didn't do it.

**Amplify CLI Version** 
4.13.1

**Comment by davidbiller** [comment]
@aprilmintacpineda 
Go to ElasticSearch Console - there is a link to your KIBANA Dashboard. 
In Kibana - go to dev tools:
than:

DELETE /indexName

**Comment by aprilmintacpineda** [comment]
Hmmm... So I need to "sort of" hack it? :( why though?

**Comment by SwaySway** [comment]
@aprilmintacpineda Are you looking to re-use an index name with a new mapping?

**Comment by aprilmintacpineda** [comment]
@SwaySway Yes, but only to change the data types :D Basically this is to apply the work around for https://github.com/aws-amplify/amplify-cli/issues/3340 So I figured out that ElasticSearch is inferring the data types from the first input it receives, I thought If I added another record that might result to a different data type on the, say instead of `2020-02-02` which would be inferred as `Date`, I added a new record `txt_2020-02-02` which would now be inferred as a string, it would update the data type, but it didn't, so I figured I would have to "recreate" the index for that model.

**Comment by SwaySway** [comment]
@aprilmintacpineda A workaround I might be able to suggest here is a re-index.
This python gist is an example of how to alias and re-index your types if you are looking to change the type.

https://gist.github.com/SwaySway/41548b31f48b00dc18080c08d1583601

**Comment by aprilmintacpineda** [comment]
HI @SwaySway I haven't tried that workaround and I suppose that would actually work, but it would be a really really helpful feature to have a button that I could simply click to achieve this as oppose to running a script every time.
