### ISSUE TITLE
.gitignore not created

### ISSUE THREAD

**Issue by alexladerman** [aws-amplify/amplify-cli#3342]
I run `amplify init` but no `.gitignore` file is created nor does it append to an existing file if present.

**Comment by UnleashedMind** [comment]
@alexladerman 
What Amplify CLI version are you using? and what is your dev box's operating system? 
Did you allow the `amplify init` command to execute to its completion?

**Comment by alexladerman** [comment]
@UnleashedMind 4.11

**Comment by kaustavghosh06** [comment]
@alexladerman Which OS are you on?

**Comment by alexladerman** [comment]
MacOS 10.15.1

**Comment by UnleashedMind** [comment]
Did you allow the amplify init command to execute to its completion?
We are not able to reproduce the issue.

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of requested information. Please respond to this issue if you're still stuck.
