### ISSUE TITLE
problem trying to 'amplify init' to create prod env

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-cli#3343]
I'm trying to intialise a new environment with 

> amplify init 

for prod (as shown in the Environments and Teams sections: [https://aws-amplify.github.io/docs/cli-toolchain/quickstart])

Do you want to use an AWS profile? **Yes**
Please choose the profile you want to use **amplify-my-profile**
You project is associated with multiple Amplify Service Apps in the region eu-west-1
TypeError: options.Push is not a function
    at SelectFromExistingAppId (/Users/mb/.nvm/versions/node/v12.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-manager.js:310:11)

init failed

I've gone in and console.logged out the value for: appIdsInTheSameLocalProjectAndRegion
`[ 'd2meqvq92i0efd', 'd2meqvq92i0efd' ]`
this value is the AmplifyAppId value for my dev and stage environements, which I managed to create fine.

options is set to [ 'd2meqvq92i0efd', 'd2meqvq92i0efd' ]
options.Push(NONE) is the line where it's failing...

I'm trying to do all this while on my master branch (which will be prod)
What am I doing wrong, please help.

**Comment by blomm** [comment]
very odd, I've edited Push to be push and have managed to get a bit further along

**Comment by UnleashedMind** [comment]
What is the version of your locally installed Amplify CLI? 
Execute `amplify -v` to find out.

**Comment by blomm** [comment]
hi, editing Push to be push allowed the init process to complete. not sure how push got replaced with Push.
