### ISSUE TITLE
Amplify Cloud Build - Amplify Pull using Service Role

### ISSUE THREAD

**Issue by dbhagen** [aws-amplify/amplify-cli#3346]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out a way to have the cloud builds of my projects generate the aws-exports.js file during the build. Right now, it seems I have to commit that into the repo for the project to build successfully, which means my keys are stored in a repo. Not the best standard.
My thought is that I'm providing a service role to the web project anyway. Shouldn't the build node be able to inherit that role and fire off "amplify pull --appId XXXXXXX --envName XXXX" (preferably arguments automatically filled in by environment variables).

I would love to hear that this is here and I'm stumbling around it, so if that's true, please fill me in!

**Describe alternatives you've considered**
Right now I use GPG to encrypt the aws-exports.js file using a pre-commit hook, and then decrypt the file during the build process. This is hard to port to different workstations contributing to the same project.

**Comment by UnleashedMind** [comment]
@dbhagen 
Are you working on the Amplify Console?

**Comment by dbhagen** [comment]
@UnleashedMind Yes, I'm working with the Amplified CLI and Amplify Web Console. The web console has a role assigned to it that has Admin permissions on the AWS account.

My goal is to keep all the things you mentioned out of my commits/the source repo, but need to have the app build through the Amplify Web Console build pipeline. I'm trying to impliment a `amplify pull --appId XXXXXXXX --envName dev` call in the `amplify.yaml` build script, but that results in errors I've submitted in this issue: https://github.com/aws-amplify/amplify-cli/issues/3413

**Comment by kaustavghosh06** [comment]
@dbhagen Looks like you were able to get pass the error in #3413. Closing this issue, let us know if you have any more issues around this.
