### ISSUE TITLE
Allow more than one GraphQL API in a project

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#335]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to add more than one GraphQL endpoint in a project. There are use cases where multiple GraphQL endpoints are required, for security isolation, for code maintenance, or for multiple backend microservices.

**Describe the solution you'd like**
To allow multiple GraphQL endpoints in an Amplify project. To share Amplify CLI created resources (e.g. DynamoDB, User Pool) between these endpoints in a project.

**Comment by mikeparisstuff** [comment]
Thanks for the feature request. We will use this ticket to track this item as we prioritize. It would be nice to allow multiple APIs in one project. The goto use case to me is to allow a publically available API with IAM auth enabled and then a user based API with user pools enabled in the same project.

**Comment by Jeyloh** [comment]
> Thanks for the feature request. We will use this ticket to track this item as we prioritize. It would be nice to allow multiple APIs in one project. The goto use case to me is to allow a publically available API with IAM auth enabled and then a user based API with user pools enabled in the same project.

This use case you're describing is what got me here. I want to add data to a database which should be publically available without logging in with Cognito. Add data while logged in and read it from anywhere. Is there any other thread since this got closed, or will it be re-opened when feature is being worked on?

**Comment by masbaehr** [comment]
Why was this closed? I also need this as i need to access different graphql endpoints for different tasks obviously. 
A very hacky solution would be this:

Configuration

```javascript
 API: {
  graphql_endpoint: '',//this needs to be empty!
  graphql_endpoint_iam_region: 'eu-central-1',
  endpoints: [
    {
      name: "Live",
      endpoint: "https://??????????.execute-api.eu-central-1.amazonaws.com/live/endpoint1"
    },
    {
      name: Beta1",
      endpoint: "https://??????????.execute-api.eu-central-1.amazonaws.com/beta/endpoint1",
    },
    {
      name: "Beta2",
      endpoint: "https://??????????.execute-api.eu-central-1.amazonaws.com/beta/endpoint2",
    }
  ],
  graphql_headers: async () => { const currentUser = await Auth.currentSession(); return {
   'Authorization': "????"
  }}
}

```


Usage
```javascript
//switch api before each request when needed by setting it manually into the graphl_endpoints config
API._options.graphql_endpoint = API._options.endpoints[0].endpoint;
//execute graphql 
const data = await API.graphql(graphqlOperation("query", { }));
```

**Comment by jskrt** [comment]
Any updates on this?

**Comment by matwerber1** [comment]
Wanted to share my +1. 

My use case is that I first created an API using the standard DynamoDB-backed data source, but now want to migrate some, but not all, aspects of the API to Aurora Serverless as they're a better fit for relational querying. I'd like to slowly migrate feature by feature, and it would be *awesome* to be able to use the out-of-the-box Amplify CLI capabilities to declare both APIs side by side.

**Comment by masbaehr** [comment]
I'm using the way that i posted above, and honestly the only drawback i see is that if you change the endpoint you have to change it back. 

So basically the solution is there, it should only be improved. Maybe a helper function could be made which changes back the endpoint do the default one (first) if a call to a different one has been made

**Comment by michaelwittig** [comment]
@jaxondu could you reopen the feature request? You might not be interested in it anymore, but others seem to be :)

**Comment by ngault** [comment]
I second @michaelwittig's view.  It's a major deficiency of Amplify to only allow one GraphQL API per project.

**Comment by MontoyaAndres** [comment]
Any news?

**Comment by CRanaboldo** [comment]
Its easy in old world of SQL etc why so hard in the serverless world?

**Comment by epomeranz** [comment]
Any updates on this request?

**Comment by masbaehr** [comment]
I for myself gave up on waiting.. Migrated away from amplify. Prefer doing everything myself.. But the actual opened thread is the other one  you might want to ask there . https://github.com/aws-amplify/amplify-cli/issues/6139 Also look on the workaround i posted above, it should still work as of today.

**Comment by ngault** [comment]
It's strange to see AWS silent on a request that is clearly driven by their largest customers.  

The narrative now circulating in the developer community that Amplify is only for small apps and can't connect to pre-existing resources on AWS has to change.  When a two-year-old product like NextJS can connect to AWS resources better than Amplify, then what's the point?

**Comment by renebrandel** [comment]
hi folks wanted to provide an update on this. We're looking into how to enable this feature but don't have a clear timeline yet. Our current thinking is to attach this work to the #6217. Let's use #6139 as the tracking issue.
