### ISSUE TITLE
Many to One Relationship question.

### ISSUE THREAD

**Issue by siddharthsharma94** [aws-amplify/amplify-cli#3351]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
App Sync / GraphQL Transform

`Amplify Version 4.12.0`
** Provide additional details e.g. code snippets **
So I'm essentially trying to create the following relationship.

I have the following models.

```gql
type Listing @model{
  id: ID!
  createdBy: User @connection(name: "userListingConnection")
  ...
  favoritedBy: [UserFavorite] @connection(name:"listingFavoritedByUser")
}

type UserFavorite @model(queries:null){
  user: User! @connection(name:"userFavoriteListing")
  listing: Listing! @connection(name:"listingFavoritedByUser")
}

type User @model {
  name: String!
  id: ID!
  age: String
  listings: [Listing] @connection(name: "userListingConnection") //these are the listings the user created
  favorites: [UserFavorite] @connection(name:"userFavoriteListing")
}
```
I'm doing a many to many relationships approach, and while this works, this feels tacky and incorrect. I don't really care about what Listing has been favorited by which user. I can't seem to figure out how to have multiple one to many connections between 2 object types.

I just want a User to be able to favorite a listing and be able to query a user's favorited listings.

**Comment by UnleashedMind** [comment]
@siddharthsharma94 
I actually think your original approach is the right approach, the "create" relationship between user and listing is one to many, but the "favorite" relationship is many to many, and you do need a userFavorite to bridge them.

**Comment by siddharthsharma94** [comment]
any update on this ?

**Comment by UnleashedMind** [comment]
@siddharthsharma94 
See my previous comments, not sure why you felt the original approach is "tacky and incorrect".

**Comment by siddharthsharma94** [comment]
So didn’t mean it in a negative connotation way,I just figured that having an unnecessary field on the listings that I didn’t need wasn’t the correct approach. Although it’s working, I feel like I could be more efficient and not have an unused column.
