### ISSUE TITLE
Field level @auth directive with @connection

### ISSUE THREAD

**Issue by imonzalvo** [aws-amplify/amplify-cli#3353]
**Which Category is your question related to?**
@auth directive

**Amplify CLI Version** 
4.13.1

I've been working with amplify for some months, and I'm trying to use field-level `@auth` directive with `@connection`.
This is how part of my schema looks like:
```gql
type Branch
  @model
  @auth(rules: [
    { allow: public, operations: [read] }, 
    { allow: private, provider: userPools }
  ]) 
  {
  id: ID!
  address: String!
  phone: AWSPhone!
  email: AWSEmail!
  name: String!
  description: String
  image: String
  bookings: [Booking!] @connection(name: "BranchBookings") 
    @auth(rules: [
      { allow: owner, ownerField: "editors", operations: [update, read, delete] }
    ])
  editors: String
}

type Booking
  @model
  @auth(rules: [
    { allow: public, operations: [read] },
    { allow: private, provider: userPools }
  ]) {
  id: ID!
  createdAt: AWSDateTime!
  start: AWSDateTime!
  end: AWSDateTime!
  status: BookingStatus!
  branch: Branch! @connection(name: "BranchBookings")
  clientEmail: AWSEmail
  clientPhone: AWSPhone
  clientName: String
  clientFamilyName: String
}
```

I want that anyone with an API KEY can query bookings info, and I want anyone with an API KEY to have access to Branch info. 
But just the **editors** should have access to a Branch's bookings.
The thing is that none of these directives have effects on my getBranch resolver. 

The actual behavior is that when any logged in user queries a branch's bookings, it receives null.

So is this schema okay? Am I missing something?

**Comment by attilah** [comment]
@imonzalvo since my suspicion is around the `open` failing, would you do these steps:

- create a directory
- npm init -y
- npm i open
- touch index.js
- add this code piece to index.js:
```js
const open = require('open');

try {
    open('https://console.aws.amazon.com', { wait: false });
} catch (e) {
    console.log(e);
}
```
- node index.js

And tell me what happened.

**Comment by attilah** [comment]
@imonzalvo could you please elaborate more on the bookings "owner" auth? since bookings is stored in a different table, how would you want to enforce ownership on it this way? `editors` is stored on `Branch`, but `branchId` is stored in `Booking`, so a `Booking` has no notion of `editors`.

**Comment by imonzalvo** [comment]
@attilah Thans for your response.

Okay, I understand what you mean. I did not fully understand how this work.
But, is there a way to achieve what I'm trying to do here? Namely, allow per-field auth on entities.

In this case I want just Branch's editors to have access to it's bookings.
