### ISSUE TITLE
Creating Amplify Project for DynamoDB

### ISSUE THREAD

**Issue by rgjoshi** [aws-amplify/amplify-cli#3354]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
New project creation

**Amplify CLI Version** 
4.13.1

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
DynamoDB

**Provide additional details e.g. code snippets**
I already have DynamoDB setup with Tables etc. I also have setup IAM and Cognito Identity. I want to access my dynamoDB tables from my Android App. As per AWS Mobile Hub developer document, I have to create a project first. However, I don't find any similar method in Amplify (now that Mobile Hub is merged into Amplify). Please guide.

**Comment by UnleashedMind** [comment]
AWS Mobile Hub is deprecated, for new projects, please use Amplify. 
Amplify Storage category does not support using existing DynamoDB tables. You might consider these two options: 
1. Use the Amplilfy Rest API, and the lambada function behind the API can access your existing table. This can be some complexities going down this route. 
2. Use Amplify Storage, the Amplify CLI will create a new table for you, and you will need to migrate the existing data to the new table.

**Comment by UnleashedMind** [comment]
closing the issue, feel free to comment or open another issue if you still have questions.
