### ISSUE TITLE
AppSync GraphQL Transform - update mutation returning null for connection directive field

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-cli#3355]
**Describe the bug**
Executing an update mutation for a model that uses the connection directive is returning null data, even though the underlying DynamoDB data exists and is correct.

**Amplify CLI Version**
4.13.1

**To Reproduce**
I used `amplify add api` to  create the following GQL schema:
```gql
type Position @model {
  id: ID!
  title: Title @connection
}
type Title @model {
  id: ID!
  name: String
  description: String
}
```

In the AppSync console, I am able to populate data in my DynamoDB Position and Title tables just fine with the generated create mutations,  but when I run the following update mutation it returns null for `title`, even though when I look in my Position table it contains the correct value for the corresponding `positionTitleId` field. Here is a sample update mutation request and response.

Request:
```gql
mutation UpdatePosition {
  updatePosition(input: {id: "88e92d80-fa6e-41b1-866f-48e48341506b", positionTitleId: "de3c8105-8b59-46c8-a7c5-5180d7d1bf9e"}) {
    id,
    title {
      id
    }
  }
}
```

Response:
```js
{
  "data": {
    "updatePosition": {
      "id": "88e92d80-fa6e-41b1-866f-48e48341506b",
      "title": null
    }
  }
}
```

But in Dynamo the `positionTitleId` field is correctly set to `de3c8105-8b59-46c8-a7c5-5180d7d1bf9e`

**Expected behavior**
The expected response would be this:
```js
{
  "data": {
    "updatePosition": {
      "id": "88e92d80-fa6e-41b1-866f-48e48341506b",
      "title": {
        "id": "de3c8105-8b59-46c8-a7c5-5180d7d1bf9e"
      }
  }
}
```

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.3
 - Node Version: 11.14.0

**Additional context**
The same thing happens with the Apollo client in my code: the network response says `null` for `title` so I'm unable to display the correct data in my app. But since it's happening in AppSync console too, I'm guessing it doesn't have anything to do with my code, but rather with the way the API was created/generated.

**Comment by sopranolinist** [comment]
Unable to reproduce today.

**Comment by deviant32** [comment]
I am having the same issue with the latest version, I believe it's from the generated code.  Do you have any updates for this?
