### ISSUE TITLE
Use Path Parameter in REST API

### ISSUE THREAD

**Issue by hamasayu** [aws-amplify/amplify-cli#3357]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
Amplify CLI does not allow path names like `{proxy}` and cannot create a resource with path parameters in a REST API.

```
$ amplify add api
? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: apic1460ef0
? Provide a path (e.g., /items) /{proxy}
>> You can use the following characters: a-z A-Z 0-9 - /
```

**Describe the solution you'd like**
Please make it possible to use path parameters when creating or updating a REST API resource.

**Describe alternatives you've considered**
Alternatively, this can be achieved by writing a custom CloudFormation template.

**Additional context**
\-

**Comment by edwardfoyle** [comment]
Hi @hamasayu if you check the generated CFN template, a proxy endpoint prefixed by the path you specify here is generated. Ie. If you specify `/user/settings`, `/user/settings/{proxy+}` is generated.

We will add support for path parameters such as `/user/{id}` to our backlog.

**Comment by sravyadalavai-vl** [comment]
how to use path params in function.

**Comment by Nicolas-Ould** [comment]
Hi @sravyadalavai-vl, did you get an answer by any chance? I see that this feature has been merged on February 21st but I'm not able to find how to implement it. Anyone can help?
