### ISSUE TITLE
Error on running Amplify configure project

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3358]
**Which Category is your question related to?**
amplify configure project

**Amplify CLI Version** 
0.1.45

**Provide additional details e.g. code snippets**
I have an existing project and when I try to configure it on a new machine, I get the following error

```
Error occured during configuration.
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at run (/usr/local/lib/node_modules/@aws-amplify/cli/src/lib/config-steps/c1-configFrontendHandler.js:8:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Following is my `project-config.json` file
```json
{
    "projectName": "project-name",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist",
            "BuildCommand": "npm run-script build",
            "StartCommand": "ng serve"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```
Environment Details:
OS: MacOs
Node Version: 13.8

**Comment by rehanbabertkxel** [comment]
@nikhname , can you please look into it and let me know what might be wrong in this configuration?

**Comment by UnleashedMind** [comment]
@rehanbabertkxel 
Please update the Amplify CLI version to the latest and try again. 
`npm install -g @aws-amplify/cli`

**Comment by rehanbabertkxel** [comment]
@UnleashedMind , thank you for the response.
I have already tried that with no luck. What can be the other possible reasons for this issue?

**Comment by nikhname** [comment]
@rehanbabertkxel your project config looks correct for an angular project. Do you see the same error when you run amplify configure project with 4.13.2?

**Comment by rehanbabertkxel** [comment]
@nikhname , I have resolved it.
The issue was that I was using nvm and an old version of amplify was installed with the node version I was using.
I removed nvm and node, installed node again and installed amplify latest version and everything works like a charm now.
Thanks for the response. :)
