### ISSUE TITLE
Using the GraphQL API codegens in the backend

### ISSUE THREAD

**Issue by andrestone** [aws-amplify/amplify-cli#3361]
** Which Category is your question related to? **
Functions
** What AWS Services are you utilizing? **
AWS Lambda
** Provide additional details e.g. code snippets **

Is there a standard workflow to consume the GraphQL API codegens in a lambda function? If not, what would be a good approach?

**Comment by andrestone** [comment]
Hey @ericclemmons , can you help me on this?

**Comment by kaustavghosh06** [comment]
@andrestone You can invoke a GraphQL API from your Lambda function using these steps -  https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda and then you can have a build hook ( https://aws-amplify.github.io/docs/cli-toolchain/usage#build-options) to your Lambda function to copy over the generate code from the `graphql/` folder to the lambda function folder

**Comment by andrestone** [comment]
Thanks for the comment., @kaustavghosh06.
