### ISSUE TITLE
Separate configuration for multiple AWS accounts

### ISSUE THREAD

**Issue by waqas-syed** [aws-amplify/amplify-cli#3363]
**Is your feature request related to a problem? Please describe.**
Me and my team have different AWS accounts that are totally independent of each other and cannot see each other's resources. I am aware of the environment workflow where we can have different environments but here is the problem.

Let's say I create a new environment dev. There are 2 other developers that are going to need to use this environment as is when it's configuration is committed to the repository. But all of us have different AWS accounts. The only person who can actually push changes to the Amplify console is me; the one who created the environment originally.

My problem now lies in the fact that how can the other 2 developers use the same dev environment and push their changes to it? Is there a way so that every developers Amplify configuration can be updated locally specific to their accounts, so we can use the same Amplify configuration for an environment yet pushing it to different AWS accounts?

Or does the only solution lie in each developer creating a new environment for themselves and using it for their development? But then I am confused that how would we merge Amplify changes from 3 different accounts to a single production environment?

**Comment by SebSchwartz** [comment]
You can create a role in your account that can be assumed from the other devs in your team and allow them to push changes. They will need to configure the profile in their aws/config aws/credentials file and then choose this role when running amplify init.
In the doc, it's well explained for such role assuming: https://aws-amplify.github.io/docs/cli-toolchain/usage#step-by-step-guide-to-create-and-assume-an-iam-role

Hope it answers your question.

**Comment by UnleashedMind** [comment]
@waqas-syed 

We would suggest the same as @SebSchwartz did.

**Comment by waqas-syed** [comment]
@SebSchwartz @UnleashedMind Thank you for the suggestion. It came handy.

On a similar note, due to some security reasons, we don't want to put the details of the production environment in the code repo and also we cannot give permissions to it other than designated personnel only. 

Is there a way in AWS in general and Amplify in particular to instead place variables in the Amplify config files, which at deployment time, can pick up their values from a file placed somewhere on the local machine? Does such a use case exist?

**Comment by RossWilliams** [comment]
@waqas-syed I use dotenv to manage this, and don't use the aws-exports file. dotenv can read an environment variable (ENVFILE) for the correct .env file to read details from, then in my app I bootstrap the envrionments with the following code (Config is a wrapper around dotenv):

```ts
Amplify.configure({
        aws_project_region: Config.AWS_PROJECT_REGION,
        aws_cognito_identity_pool_id: Config.AWS_COGNITO_IDENTITY_POOL_ID,
        aws_cognito_region: Config.AWS_COGNITO_REGION,
        aws_user_pools_id: Config.AWS_USER_POOLS_ID,
        aws_user_pools_web_client_id: Config.AWS_USER_POOLS_WEB_CLIENT_ID,
        Auth: {
          identityPoolId: Config.AWS_COGNITO_IDENTITY_POOL_ID,
          region: Config.AWS_PROJECT_REGION
        }
      });
if (Config.ENABLE_ANALYTICS) {
        Analytics.configure({
          autoSessionRecord: true,
          AWSPinpoint: {
            appId: Config.AWS_PINPOINT_APP_ID,
            region: Config.AWS_PINPOINT_REGION,
            mandatorySignIn: true
          }
        });
      }
```

Deploying to different accounts / environments is then just a case of setting the right value to ENVFILE, having that file, and having correct aws credentials.

**Comment by waqas-syed** [comment]
@RossWilliams This is exactly what I need. I have some options to go from here but I would be interested in knowing how you do it, so I have a couple of questions:

1) Are you doing this in node? Because my project is in Angular and dotenv doesn't work with it. If you do this in a web project, can you please give an example link that might help?!

2) How do you handle variables in team-provider-info.json file? I am implementing something based on [this script](https://aws-amplify.github.io/docs/cli-toolchain/quickstart?sdk=js#environment-related-commands) where I insert variables into this script by reading them from a config file and running this script results in me getting the team-provider-info.json. Is there a better way to do it?

**Comment by RossWilliams** [comment]
1. For web projects I do this with webpack using DefinePlugin.
```js
const envFilePath = path.resolve(
  __dirname,
  "../" + (process.env.ENVFILE || ".env")
);

config.plugins.push(
    new webpack.DefinePlugin({
      __WEB_CONFIG__: JSON.stringify(
        dotenv.config({ path: envFilePath }).parsed
      )
    })
  );
```

2. With ENV files, we don't use team-provider-info.json and added it to our gitignore. If we need to collaborate in a dev's AWS account, we just need the .env file to be sent. If we need to push into another person's account we can get the info we need from Cloudformation.

**Comment by waqas-syed** [comment]
@RossWilliams Thank you!
