### ISSUE TITLE
Can I use codegen with cloudformation (without amplify CLI)?

### ISSUE THREAD

**Issue by LpmRaven** [aws-amplify/amplify-cli#3365]
Is it possible to generate the graphql resolvers for appsync using cloudformation rather than the amplify CLI?

I wish to reproduce my Appsync and DynamoDB stack in cloudformation as the rest of our services use that.

**Comment by kaustavghosh06** [comment]
I'm not super clear about your question. Some more details would be helpful. 
 Amplify CLI generated Cloudformation files for you and the corresponding resolvers which it reference in it's Cloudformation files.

**Comment by LpmRaven** [comment]
@kaustavghosh06 thanks for the reply, I will try to clarify my situation and hopefully make my question clearer.

All of our stacks are managed through cloudformation, as all of the AWS services we use are available through cloudformation alone. We do not wish to use amplify CLI to deploy appsync and dynamodb, we wish to do this through cloudformation in the AWS console. We do not use any custom resolvers. The only way I can find to generate the default resolvers (with codegen) is to use amplify CLI. The generated cloudformation stacks are very confusing and have external file references. It is unclear which generated cloudformation file would need to be used and/or what modification I would need to make to reference the external resolver files.

1. Is there a way to use codegen to generate the resolvers without using amplify CLI?
2. If not, what steps would I need to take to deploy the appsync and dynamodb stack without using amplify CLI for deployment?

**Comment by yuth** [comment]
>  1. Is there a way to use codegen to generate the resolvers without using amplify CLI?

the graphql-transformer is published to NPM as a separate package along with all the transformer plugins. If Amplify CLI does not fit your need, then you could use the transformer directly without using the Amplify CLI, [similar to how the CLI uses it](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js#L250). 


>   2\. If not, what steps would I need to take to deploy the appsync and dynamodb stack without using amplify CLI for deployment?

Amplify CLI generates the Cloud Formation stack inside the build directory of the API which can be deployed with out using Amplify CLI as long as the right parameters are passed to the stack. Some of the common parameter that needs to be passed are
- AppSyncApiName
- env
- S3DeploymentBucket - this is the name of the bucket where the resolver templates and schema is uploaded 
- S3DeploymentRootKey - the path in the deployment bucket where the build folder is uploaded

If your API has auth directive with user pool then you will have to pass these as well
- AuthCognitoUserPoolId
- authRoleName
- unauthRoleName

Just keep in mind if you're managing the stacks directly, then the sanity check would not be available to you which checks for changes in your Dynamo Db Indexes and warns about possible deployment failures

**Comment by LpmRaven** [comment]
thanks @yuth
