### ISSUE TITLE
Deleting Cognito Pool = unrecoverable state?

### ISSUE THREAD

**Issue by dan-rxr** [aws-amplify/amplify-cli#3368]
The user pool for one of my envs was accidentally deleted, which seemingly prevents any further interactions via Amplify CLI from working successfully. In fact, I can't even remove the user pool through `amplify auth remove` because apparently "other amplify dependencies rely on this resource".

Is this environment just permanently broken and beyond recovery? Seems like an incredibly fragile setup if that's the case.

**Comment by kaustavghosh06** [comment]
@dan-rxr If you deleted your cognito user pool and all your other resources depend on it - then the authorization for that wouldn't work. I would create a new environment if you do not want to re-create all the resources again. This would create a new userpool for you as well.

**Comment by dconlon-monigo** [comment]
It is funnier than you think...if you make changes to an unmodifyable property of a UserPool(e.g. custom attributes) created by amplify outside of an amplify push(via cli or web console) then you also get into an unrecoverable state. There are several sharp edges you have to look out for.

Is there anything we can do to make this a better experience? e.g. split out the UserPools from the main cf stack and have a parallel system of cf-stacks to handle them, where we can force delete them and repair references prior to managing the rest of an amplify project? or do we wait for UserPools to be less brittle and allow for updating of all properties? (I'm not across the limitations of why there are immutable properties of UserPools - I'm assuming a technical limitation in the current implementation)

**Comment by kaustavghosh06** [comment]
@dconlon-monigo We've raised these concerns to the Cognito team regarding the immutable properties of user-pools and they're actively working on making this experience better.

**Comment by maximelebastard** [comment]
Do you have some news about this ? How can we recover from a deleted user pool ?
This is a great concern for us too, especially regarding our production
