### ISSUE TITLE
autogenerated fields with @model

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#3369]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
Some fields in a @model schema must be auto-generated, for example UUID, incremental number, timestamp, current_date. Currently, there is no way to mention the same in the schema. 

Currently, only IDs can be generated provided they are not passed by the caller in a mutation. But such system-generated information should not be allowed to be overwritten by the user. 

**Describe the solution you'd like**

Allow new annotation @system-generated ({name:field_name_1, value:auto_uuid}, {name:field_name_2, value:auto_increment_number}, {name: field_name_3, value:auto_date_time}, {name: field_name_4, value: timestam_nanoseconds} )

The format is not important, but the functionality is.

**Describe alternatives you've considered**
One alternative is to implement this logic using a pipeline resolver or a lambda function. Both are overkill of functionality and this is something should be made available by default in the system.

**Comment by UnleashedMind** [comment]
@arkllc 
Could you describe in more details on the  @system-generated  annotation you proposed? 
such as, Is it applied to the type level or field level?  how should it be transformed? etc.

**Comment by arkllc** [comment]
It should be applied at the field level. Also, the implementation is straightforward. The corresponding fields should always be generated in the Velocity template by using either the current ISO timestamp for date fields and UUI for unique ID. For the sequence number, a call needs to be made to the table to identify the current sequence number and then increment by 1. Now I can see why sequence numbers can be tricky due to race conditions in a highly concurrent system so it need not be supported in dynamodb systems. The RDBMSs typically have the sequence number capabilities so it may be slightly easier to support. Overall I don't think the sequence number implementation is all that important but the UUID, Timestamps and current DateTime are more important.

**Comment by arkllc** [comment]
@UnleashedMind please let me know if you have any further questions

**Comment by arkllc** [comment]
@UnleashedMind  could you please provide an update if we could expect this feature to be released sometime in near future?

**Comment by kaustavghosh06** [comment]
@arkllc I believe you can leverage this community created @auto transformer for auto-generating certain fields or create your own custom transformer based on your requirements on the fields. 
@auto directive 3rd party plugin reference - https://github.com/hirochachacha/graphql-auto-transformer
