### ISSUE TITLE
amplify push fails because GraphQL schema ID field is not of type Int

### ISSUE THREAD

**Issue by TheBenck** [aws-amplify/amplify-cli#3375]
**Describe the bug**
`amplify push` fails because ID type is not of type Int

**Amplify CLI version**
4.13.1

**To Reproduce**
```
amplify push
? Are you sure you want to continue? Yes
```

**Expected behavior**
Successfully push backend environment to the cloud.

**Screenshots**
```
✖ An error occurred when pushing the resources to the cloud

managerId field is not of type Int
```

_schema.graphql_
```
type Writer implements Person 
  @model
  @searchable
  @key(name: "byManager", fields: ["managerId", "hourlyPay"])
  @auth(rules: [
    {allow: groups, groups: ["Admin"]},
    {allow: public, provider: iam, operations: [read]}
  ])
{
  id: ID!
  managerId: ID!
  name: String!
  hourlyPay: Float!
  manager: Manager! @connection(fields: ["managerId"])
}

type Manager implements Person 
  @model
  @searchable
  @auth(rules: [
    {allow: groups, groups: ["Admin"]},
    {allow: public, provider: iam, operations: [read]}
  ])
{
  id: ID!
  name: String!
  department: String
  writers: [Writer!]! @connection(keyName: "byManager", fields: ["id"])
}
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Node Version 10.15.0

**Additional context**
The error goes away if I change managerId to an Int on the Writer type but ID is what I want.

**Comment by edwardfoyle** [comment]
What is the type of the ID field on your Person interface? I was able to repro a similar error message when that was set to Int.

**Comment by edwardfoyle** [comment]
@TheBenck Closing due to lack of response. If you are still having issues feel free to reopen with additional details.
