### ISSUE TITLE
amplify mock api  shows a blank AppSync Mock endpoint page when api is created with auth type "API key" and "IAM"

### ISSUE THREAD

**Issue by utsabroy** [aws-amplify/amplify-cli#3376]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
amplify mock api is not working with auth type "API key" and "IAM". It gives a blank page. the command works if the auth type is "Amazon Cognito User Pool"

**Amplify CLI Version**
4.13.2

**To Reproduce**
Create a simple react app. 
Run amplify add api 
Choose the default authorization type for the API -> API key or IAM
After Api is created run amplify mock api
Open AppSync Mock endpoint page
The page is blank 
In the browser console you will see the Javascript error

<img width="1440" alt="Screen Shot 2020-02-07 at 5 19 03 PM" src="https://user-images.githubusercontent.com/5227292/74075024-025d9700-49ce-11ea-83f0-71497a3af8e8.png">

Now run amplify update api and change the auth to "Amazon Cognito User Pool"
Run amplify mock api
Now the AppSync Mock endpoint page works fine 

<img width="1438" alt="Screen Shot 2020-02-07 at 5 24 23 PM" src="https://user-images.githubusercontent.com/5227292/74075251-bc550300-49ce-11ea-8592-3fc98d0586fd.png">

 
**Expected behavior**
The local graphql schema query page should open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] - MAC
 - Node Version. You can use `node -v` to check the node version on your system
v12.15.0

**Additional context**

**Comment by ChrisSargent** [comment]
I'm having this issue but I only have the API key auth turned on - in the `aws-exports.js` file there is no value for the api key, like when running in cloud.

**Comment by waltermvp** [comment]
Im getting this and am using cognito + IAM

**Comment by waltermvp** [comment]
Had the same issue no longer ocurring in 4.13.4
