### ISSUE TITLE
Auth allows update for items from different owners

### ISSUE THREAD

**Issue by shivangp** [aws-amplify/amplify-cli#3377]
I'm trying to create an amplify API that allows users to store the profile information in a User table in Dynamo DB. I'm using @auth directive to set owner for the and want to make sure users can only update their own profile. My schema is as follows where ID is the ID from my cognito user pool:

```gql
type User
	@model(subscriptions: { level: public })
	@auth(
		rules: [
			{ allow: public, provider: iam, operations: [read] }
			{
				allow: owner
				ownerField: "id"
				identityClaim: "sub"
				operations: [read, create, update]
			}
			{ allow: groups, groups: ["CommunityAdmin"] }
		]
	)
	@key(fields: ["id"])
	@key(
		name: "byUsername"
		fields: ["username"]
		queryField: "userByUsername"
	) {
	id: ID!
	identityId: String
	email: String!
	username: String!
	about: String	
}
```

From the appsync console I'm logged in as a user from my user pool and if I try to perform following update mutation, it will allow me to update another user's about field:

```gql
mutation {
  updateUser(input: {
    	id:"<SOME OTHER USER ID>",
    	about:"Test update"
  }) {
    id
    username
    about
  }
}
``` 

How can setup @auth so only the owner can only update their own profile?

**Comment by mtliendo** [comment]
@shivangp Looking into this. Will try to duplicate and resolve.
