### ISSUE TITLE
DataStore-like ORM 

### ISSUE THREAD

**Issue by andrestone** [aws-amplify/amplify-cli#3378]
**Which Category is your question related to?**
DataStore / Lambdas

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
AppSync, DynamoDB, Lambda

**Provide additional details e.g. code snippets**

Is there any implementation or workaround to make the DataStore ORM API available on the backend (That would be without the actual data store and sync, using the API to talk directly to the DynamoDB)

If not, is it something to be considered or it's just out of the project scope?

Thanks.

**Comment by andrestone** [comment]
Any interest?

**Comment by kaustavghosh06** [comment]
@andrestone This is an interesting idea. It's a feature request that we'll look at in the future and measure community interest. If you want to work on it, you can maybe open up an RFC with ideas before starting implementation.
