### ISSUE TITLE
'Type "AWSURL" not found in document' when generating models

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3379]
**Describe the bug**
When I run command `amplify codegen models` I get the error
>Type "AWSURL" not found in document

**Amplify CLI Version**
Amplify 4.13.2

**To Reproduce**
`yarn create react-app resources --template typescript`
`amplify init`
`amplify add api`
use this schema
```
type Resource @model
    @auth(rules: [{ allow: owner }]) {
    id: ID!
    title: String!
    link: AWSURL
}
```
`amplify codegen models`

**Expected behavior**
Schema should be validated and generated.

**Desktop:**
 - OS: Windows 10
 - Node Version. 12.15.0

**Comment by apoorvmote** [comment]
Exact same error for following types
* `AWSEmail`
* `AWSDate`
* `AWSPhone`

Temporary fix is to use type `String` everywhere

**Comment by attilah** [comment]
@apoorvmote thanks for reporting the issue, I was able to reproduce it.

**Comment by apoorvmote** [comment]
@attilah I would also like to create request for official documentation of adding datastore to existing project. Or adding api and then generating models. 

Because the `npx amplify-app@latest` is failing for me and lots of other users. And all of them are ignoring because they thinks its very unstable and not ready for production.

**Comment by attilah** [comment]
@apoorvmote we did have an issue with the amplify-app that was released with 4.13.1 of the CLI, and last week we published a fixed version with 4.13.2. Could you please try it?

**Comment by apoorvmote** [comment]
@attilah I did try it with 4.13.2 in the past and I tried it again right now. I get following error.
```
🎸 Creating base Amplify project
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn amplify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn amplify',
  path: 'amplify',
  spawnargs: [ 'init', '--quickstart' ]
}
```
Desktop:

* OS: Windows 10
* Node Version. 12.15.0
* AWS Amplify-cli 4.13.2

**Comment by attilah** [comment]
Oh I see you are on Windows. It is a Windows specific issue. Let me open a separate issue for it.

**Comment by apoorvmote** [comment]
Ok now its working on mac. In my previous test it failed on both macOS and Windows. Now it only fails on windows. 
However I still like to use API graphql query operation for deeply nested queries. e.g. fetch specific blog then all posts for the blog and all comments for each post.

**Comment by apoorvmote** [comment]
Working from today's release.
