### ISSUE TITLE
Setting up google / facebook authentication in react-native app

### ISSUE THREAD

**Issue by IljaDaderko** [aws-amplify/amplify-cli#338]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**

I was trying to set up google authentication following these steps

1. Generated credentials for ios and web clients of my app in google cloud console
2. `amplify update auth` (already had auth set up as I am using `@auth` in my graphql api)
3. Went ahead and configured everything to use google as third party provider (it was odd I only got asked for web client id here, more on this latter). I also disabled email password recovery here and used sms instead.
4. `amplify push`
5. I added federated sign in as follows
```js
        await Auth.federatedSignIn(
          'google',
          { token: idToken, expires_at: idTokenExpirationDate },
          { email, name }
        );

        const currentUser = await Auth.currentAuthenticatedUser();
```
I logged out all data passed to `Auth` (tokens, expiry, user etc...) and am sure it is correct.

Yet, when I try to log in I get following error:

> Token is not from a supported provider of this identity pool

Am I missing something? I logged into aws console and went to user pool in Cognito that was generated by amplify, inside it nothing related to google is enabled, do I need to do this manually i.e. Add web client details in and tick / enable `Google` as option in my web and app clients?

And finally related to only using web token everywhere, when I get user idTokens and other data from Google, it actually comes from ios where I use ios client id from google plist (react native project)? I need to use ios client id as I am using native google sdk, is this an issue?

**Comment by IljaDaderko** [comment]
UPDATE: I just tried same process with completely new app, just to make sure this was not related to `update` command. Got same result :/

**Comment by powerful23** [comment]
@IljaDaderko can you check your Cognito Federated Identity Pool configuration to see if Google is one of the provider?

**Comment by haverchuck** [comment]
@IljaDaderko  - Thanks for posting.  Google authentication is represented a little bit differently in the Cognito console. Can you check the following in the console and let us know what you see?

1. In the identity pool, check Authentication Providers -> OpenID.  You should see something to the affect of 'accounts.google.com' with a selected checkbox.

2. In the IAM console, check 'Identity Providers'.  You should also an entry for Google, which in turn should have an 'audience'.

**Comment by IljaDaderko** [comment]
@haverchuck I can confirm that neither OpenID provider nor IAM have anything related to `accounts.google.com`

CLI did create Cognito user pool and some cognito related IAM roles correctly though, this is fresh project with auth added and pushed, on latest cli version.

Here are some things I can think of that deviate from ordinary setup

1. Amplify init uses user from `us-east-2`
2. During guided cli setup I disabled non authenticated users
3. I also disabled email/password login and am using SMS option

Everything else so far seems ok, cli generates AppSync, Cognito, CloudFormation, S3 etc... correctly by the looks of it.

**Comment by haverchuck** [comment]
@IljaDaderko -  do you see your webclient id under Identity Pool ->  Authentication Providers -> Google + in the Cognito console?

**Comment by IljaDaderko** [comment]
@haverchuck yes its there, I also noticed this message

> Note: If you need to associate more than one Google Client ID to this Identity Pool (e.g. you want to enable login with Google from both iOS and Android apps, which need different IDs), you will have to set up Google as an OpenID provider from the IAM Console by following the instructions in OpenID Connect Providers in the Cognito Developer Guide.

In my Google console, I created to oAuth credentials for web and ios client, cli asked for web one only, where as react-native ios app is using google plist file that has different client id for ios.

Never the less error I get implies that I don't have google sign in enabled at all?

> Token is not from a supported provider of this identity pool

**Comment by IljaDaderko** [comment]
@haverchuck Looked through Cognito again this morning, here is some additional data that might help you

**Identity Pool**
1. Dashboard page has `Google Sign-In` mentioned (no reference to `accounts.google.com`)
2. Under `Edit identity pool` client id is present in `Google +` tab, nothing in OpenID

**User Pool**
1. Nothing related to OpenID or Google is enabled under `Federation` nor `App Integration`

**IAM**
1. Identity providers are empty

All of the above I checked making sure I am on the same `us-east-2` region and there are Cognito bits generated by cli, just seems it was incomplete?

**Comment by IljaDaderko** [comment]
@haverchuck I went ahead and did that, this gets past initial error I had, but now returns

> Invalid login token, Incorrect token audience

I assumed this is related to `2` from your guide, so I went ahead and made sure that my iOS apps google plist client id is same one I added to IAM audience and yep its all there (I also have my web client id there), so I am not sure why I am getting this error now.

Can it somehow be related to having `Google +` entry besides `OpenID` one in my identity pool under authentication providers (as this entry is only using web client id)? Should I try to remove it somehow?

---

On a bit of unrelated note, since react-native apps can have multiple clients (web, ios, android), perhaps it is worth to add additional guided cli step to `amplify add auth` that (when google is selected) asks user to choose what clients they have (i.e. 3 checkboxes web, android, ios) and then subsequently asks to enter related client id's?

**Comment by haverchuck** [comment]
@IljaDaderko -  Yes, I think your suggested change to the CLI is exactly what is needed. 

I was able to get this to work by following the steps I listed above, and then adding the following to my test app:

```
export default class App extends React.Component {
  async signIn() {

    const loginConfig = {
      androidClientId: '',
      androidStandaloneAppClientId: '',
      iosClientId: '<your_ios_id>.apps.googleusercontent.com',
      iosStandaloneAppClientId: '',
      webClientId: '',
      behavior: 'system',
      scopes: ['email', 'openId', 'profile']
    }

    let res = await Expo.Google.logInAsync(loginConfig);
    if (res.type === 'success') {
      // sign in with federated identity
      Auth.federatedSignIn('google', { token: res.idToken}, { name: 'USER_NAME' })
        .then(credentials => {
          console.log('got aws credentials!!!!');
        }).catch(e => {
          console.log(e);
        });
    }
  }

  // ...

  render() {
    return (
      <View style={styles.container}>
        <Authenticator>
        </Authenticator>
        <Button title="googlesignin" onPress={this.signIn.bind(this)} />
      </View>
    );
  }
}
```
There might still be an issue with getting the session after this point, which we will be taking a look at.

And yes, we need to update our documentation!

**Comment by IljaDaderko** [comment]
@haverchuck Awesome. I am not using expo, have native google sdk set up, which uses ios client id and I used web one in cli, I think this is my issue, should probably use ios everywhere for now (will check this tomorrow to be absolutely sure, away from mac for a while atm).

That cli change would be much appreciated! I can help out with doc pr if you drop few bullet points here :) Will this process still be done through cli or will we need to perform those manual steps now?

I guess we should keep this issue open until fix is shipped?

**Comment by haverchuck** [comment]
@IljaDaderko - For now these will need to be manual, but yes eventually this should be totally automated through CLI.  It's in our backlog. 

Our federated signin documentation shows a non-Expo method for getting the google token... I'm assuming that's what you are using.

**Comment by IljaDaderko** [comment]
`window.gapi.auth2.getAuthInstance();` this is bit of documentation you are referring to as non-Expo method, correct? I believe this method only works for env's that expose `window`

My implementation is based on https://github.com/react-native-community/react-native-google-signin
I will be testing it with just iOS client id today, as I'm pretty confident I don't need to specify web one at this time. I also believe that adding additional client id's to IAM `audience` has any effect at the moment, it seems as if amplify is only using one client id that was defined during cli setup.
