### ISSUE TITLE
UnrecognizedClientException in Lambda

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#3380]
**Which Category is your question related to?**
Lambda, IAM, AppSync

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
Amplify, Lambda, AppSync

**Provide additional details e.g. code snippets**
I added a lambda function using the amplify cli and I gave it crud access to my graphql api, also created by the amplify cli. In my lambda function i create a record using the documtenation about [interfacing with graphql from lambda](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda). However, I get the following error:

**errorType: 'UnrecognizedClientException', message: 'The security token included in the request is invalid.'**

I checked IAM and the roles were properly created for my lambda function. What should I do? I can paste my code but it looks exactly like the documentation mentioned above, but with a different query and environment variables

**Comment by kaustavghosh06** [comment]
@karrettgelley Could you provide the API call details you make from the Lambda function? What Auth types have you configured on your AppSync API?

**Comment by attilah** [comment]
@karrettgelley to clarify, you added the GraphQL API first, then you did an add function, where you specified the required access during the question flow?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response. Please comment on this thread if you're still stuck.
