### ISSUE TITLE
amplify init gives AccessDenied error

### ISSUE THREAD

**Issue by niranjanshukla** [aws-amplify/amplify-cli#3383]
**Issue**: Running `amplify init` gives ⠼ Initializing your environment: dev(node:44978) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied

**Notes**:
1. Tried separately on multiple local directories by cloning the repo again. Error persists.
2. With the same amplify credentials, amplify init runs successfully on another project's repository on the same local machine.

**Versions**:
<project root>$ amplify -v
4.6.0
<project root>$ node -v
v10.16.0

**Steps to reproduce**:
<project_root> $ `aws-adfs login --adfs-host <hostname> --profile <profile name> --region ap-southeast-2 --role-arn <arn>`

[authenticator authenticator.py:authenticate] [44892-MainProcess] [4414887360-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Password: <entered system password>
Enter your Symantec VIP Access code:<entered access code>
Going for aws roles
 
        Prepared ADFS configuration as follows:
            * AWS CLI profile                   : <profile name>
            * AWS region                        : 'ap-southeast-2'
            * Output format                     : 'json'
            * SSL verification of ADFS Server   : 'ENABLED'
            * Selected role_arn                 : <arn>
            * ADFS Server                       : <host name>
            * ADFS Session Duration in seconds  : '3600'
            * Provider ID                       : 'urn:amazon:webservices'
            * S3 Signature Version              : 'None'
            * STS Session Duration in seconds   : '3600'
            * SSPI:                             : 'False'
            * U2F and default method            : 'True'
        
<project root>$ `aws --profile <profile name> sts get-caller-identity`
{
    "Account": `<account name>`, 
    "UserId": `<user id>`, 
    "Arn": `<arn>`
}
<project root> $ `amplify init`
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation
 
For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
 
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use <profile name>
⠼ Initializing your environment: dev(node:44978) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:816:35)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:44978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇

**Comment by kaustavghosh06** [comment]
@niranjanshukla Looks like the AWS creds you have associated with your profile on your machine doesn't have access to the account where the dev environment was originally initialized. To cross-check this, check your "amplify/team-provider-info.json` file and for that environment check the AppID and see if you can locate that in your AWS Amplify console - for the same account for which you have your pfile configured for.

**Comment by niranjanshukla** [comment]
@kaustavghosh06  This is how my amplify/team-provider-info.json looks like:

{
    "dev": {
        "awscloudformation": {
            "AuthRoleName": `<auth role>`
            "UnauthRoleArn": `<arn>`
            "AuthRoleArn": `<authRoleArn>`
            "Region": "ap-southeast-2",
            "DeploymentBucketName": `<bucket name>`,
            "UnauthRoleName": `<Unauth role name>`,
            "StackName": `<stack name>`,
            "StackId": `<stack ID>`
        },
        "categories": {
            "auth": {
                `<is this field the app ID ?>`: {
                    "googleAppIdUserPool": `<google app ID user Pool>`,
                    "googleAppSecretUserPool": `<google app ID secret>`,
                    "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\",\"client_id\": `<client ID>`,\"client_secret\":`<client secret>`}]"
                }
            }
        }
    }
}

Could you please point to the app ID field I should cross check in this configuration (I have highlighted a possible field)? Also, where in AWS Amplify Console can I find the required App ID?

**Comment by niranjanshukla** [comment]
Additional input -- when I log into the AWS Amplify console to see the apps I have access to, I get the below error

```
List apps call failed
User: <arn> is not authorized to perform: amplify:ListApps on resource: arn:aws:amplify:ap-southeast-2:<code>:apps/*
```

Is this access permission related to the AccessDenied error above?

**Comment by niranjanshukla** [comment]
Upon checking with the AWS admin team, the configuration in amplify/team-provider-info.json was fixed. That resolves the issue.

This issue may be closed.

**Comment by sai-kante** [comment]
check ~/.aws/credentials
amplify uses `default` provider by default.

**Comment by onkartibe** [comment]
I am facing the same issue, any clues?

amplify -v
4.40.0

node -v
v10.21.0

MacOs

Error:
`User: arn:aws:iam::XXXX:user/ABC is not authorized to perform: amplify:ListApps on resource: arn:aws:amplify:ap-southeast-1:XXX:apps/* with an explicit deny`
