### ISSUE TITLE
How can I use multi pools?

### ISSUE THREAD

**Issue by eliecer2000** [aws-amplify/amplify-cli#3385]
I would like to know if it is possible from the CLI to be able to create several pools, since I have several front-end all will use the same database but the configuration of users is different, since by one of the frontend you will have access with the telephone number only , another only with email and the last one only by username, so I created the pools manually and it works, but is there a possibility to create them from the CLI?

**Comment by attilah** [comment]
@eliecer2000 this scenario is not supported by the CLI and you cannot use existing resources in CLI managed projects yet either. Would you give more information about your use case that requires you to have 3 user pools? Perhaps there could be another way to solve the specific use case you've.

**Comment by eliecer2000** [comment]
Thank you very much for your budget, I have solved the issue of multipools by cheating the CLI, you have to do a couple of manual configurations, such as trust relationships that you must place all the arm of each pool, and in appsync place the additional pools, the Rest does very well.

It would be an excellent option to modify the CLI.

**Comment by eliecer2000** [comment]
Thank you very much for your response, I have solved the issue of multipools cheating the CLI, you have to make a couple of manual configurations, such as the trust relationships that you must place all the arm of each pool, and in appsync place the additional pools, the Rest does very well.

It would be an excellent option to modify the CLI.

**Comment by attilah** [comment]
@eliecer2000 Could you please elaborate on the steps needed and what escape hatches the CLI could add to enable scenarios like yours, so we could turn it into an enhancement from question.

**Comment by attilah** [comment]
Closing due to the lack of response. Feel free to reopen if you can provide some input on my previous question about how can we enhance the CLI experience.

**Comment by eliecer2000** [comment]
Sorry for my absence, I explain in detail, I have 3 applications with the same database but with different ways to login. one needs the telephone number to enter, the other application needs to enter by email and the last one only with the username taking into account that it needs both an email and a telephone number for verification.

what I did was to deceive the CLI so that I could create the 3 pools, so they have roles to access the databases, manually in dynamodb you give access to the identification group and that's it.
