### ISSUE TITLE
Accessing API Gateway from Lambda

### ISSUE THREAD

**Issue by leantide** [aws-amplify/amplify-cli#3386]
**Which Category is your question related to?**
Lambda Functions

**Amplify CLI Version** 
4.13.2

**What AWS Services are you utilizing?**
function, gateway

**Provide additional details e.g. code snippets**
I would like to access a Gateway API from my Lambda (for example, "https://4s6edhqkj5.execute-api.us-east-1.amazonaws.com/dev")

I run `amplify function add` and choose `serverless express function` and request access to other resources and specify `api`, and choose the specific api.

Amplify CLI auto-generates function code which provides variables containing the environment (ex. 'dev'), the region (ex. 'us-east-1') and API name (ex. 'myApi').

But to do a https fetch/request, I would also need the api Id (ex. '4s6edhqkj5') to construct the url. Is this available? 

Or is there a better way to access the Gateway API using the aws-sdk that doesn't involve the api Id?

**Comment by leantide** [comment]
API Gateway provides apiId via $context.apiId variable. Wondering if access to this can be added to cloudformation templates used by Amplify CLI.

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html

**Comment by hanna-becker** [comment]
Is this actually working? I added and api and lambda function and connected the two with 'amplify add api', but when I access the REST api id value from the environment, it just gives me a placeholder value (apiappRestApiId) instead of the actual id.
Ampify CLI version 4.38.0
