### ISSUE TITLE
[appsync][mock] VTL compiler does not support JavaString.split()

### ISSUE THREAD

**Issue by marcoreni** [aws-amplify/amplify-cli#3389]
**Describe the bug**
According to VTL spec we should be able to use standard Java String functions (eg. `string.split()`). JavaString apparently supports only length() and replaceAll().

Is there a smart way to add all the missing methods other than scripting them one by one?

I know that we may have some differences on the Regexp handling, but not having the methods is limiting.

**Amplify CLI Version**
latest

**To Reproduce**
Use a VTL, for example:
```vtl
#set($testSplitParam = $ctx.args.testParam.split("-"))
```

**Expected behavior**
Value should be splitted into an array

**Comment by attilah** [comment]
@marcoreni the current mock implementation does not have all of the methods implemented yet. As we've a full VTL implementation in JavaScript and not bridging into a Java implementations the missing methods must be added. I mark this issue as an enhancement.

Would you like to contribute some of the missing functionality to mock and create a PR? we'd be more than happy to help with that.

**Comment by attilah** [comment]
@marcoreni thanks for the PR!
