### ISSUE TITLE
Cannot set identityField to custom attribute using @auth

### ISSUE THREAD

**Issue by mkrn** [aws-amplify/amplify-cli#340]
**Describe the bug**
When using @auth directive and "owner" type rule with identityField set to `custom:fieldName` the generator creates invalid template code

**To Reproduce**
Create a model 
```
type PigRun @model @auth(rules: [{
  allow: owner,
  ownerField: "pigRunClientId",
  identityField: "custom:company"
}]) {
  id: ID!
  client: Company! @connection(name: "CompanyPigRuns")
}

type Company @model {
  id: ID!
  name: String!
}
```
The generated resolver templates will use invalid `$ctx.identity.custom:company` syntax in Ownership check sections

**Expected behavior**
I would expect the generators to use `$ctx.identity.claims.get("custom:company_id")` syntax that have worked for me with ID token before. 

**Desktop (please complete the following information):**
 - amplify -v 
0.1.28

**Comment by mkrn** [comment]
The workaround is to set claims in Pre Token Generation Trigger lambda,

like this:
```
exports.handler = (event, context, callback) => {
    const { request } = event;
    const { userAttributes } = request;

    event.response = {
        "claimsOverrideDetails": {
            "claimsToAddOrOverride": {
                "company": userAttributes['custom:company'],
            }
        }
    };

    // Return to Amazon Cognito
    callback(null, event);
};```

But leaving this here as a potential to improve for newcomers and first time users. The `identityField` is largely undocumented as well, so could be worth extending documentation for cases like this.

**Comment by mkrn** [comment]
Another gotcha for newcomers is to make sure to use `idToken`:

In your front-end code:
```
Amplify.configure({
  ...aws_exports,
  graphql_headers: async () => {
    try {
      const token = (await Auth.currentSession()).idToken.jwtToken;
      return { Authorization: token }
    }
    catch (e) {
        console.error(e);
        return {};
        // return { Authorization: await asyncLocalStorage.getItem("jwt") }
    }
  }
});```

**Comment by mikeparisstuff** [comment]
This is interesting. I think I agree that we should use `.get(identityField)` instead of dot notation to allow for this use case. This will also require changing the default identityField from `username` to `cognito:username` which is how it shows up in the claims object.

**Comment by mikeparisstuff** [comment]
Addressed in https://github.com/aws-amplify/amplify-cli/pull/354. @mkrn it would be great to get your eyes on it if you have a few minutes.

**Comment by mkrn** [comment]
@mikeparisstuff  Thanks, trying to setup for development will update as soon as I'm able to check it

**Comment by kaustavghosh06** [comment]
This issue is fixed and would be a part of the next CLI version (0.1.30).

**Comment by halilduygulu** [comment]
I still did not understand how to use any other field than default owner value. Asked here https://github.com/aws-amplify/amplify-cli/issues/7386
