### ISSUE TITLE
How to query by a type column + userId + createdAt

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-cli#3404]
** Which Category is your question related to? **

AWS Amplify + GraphQL Queries

** What AWS Services are you utilizing? **
Cognito + AWS AppSync,
** Provide additional details e.g. code snippets **

```
type MyTable
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "userId", operations: [create, update, read] }
    ]
  )
  @key(
    fields: [“type”, "createdAt"]
    name: "SortByType"
    queryField: "listByType"
  ) {
  id: ID!
  userId: String!
  type: String!
  createdAt: AWSTimestamp!
}
```

The column type can be "A" or "B".

I query by

```
await API.graphql(
        graphqlOperation(listByInterval, {
          type: 'A',
          sortDirection: ModelSortDirection.DESC,
        })
```
The query will automatically query by the logged in userId.
Amplify has a default limit of 10.

If my data is on the 20th row, The first search will return me 0 results.
If I set the limit to 30, I get my results back.

So I tried changing the schema to 3 key fields and kept my Database to less than 10 items.

```
await API.graphql(
        graphqlOperation(listByInterval, {
          userId: userId
          typeCreatedAt: {
            eq: {
              type: 'A',
            },
          },
          sortDirection: ModelSortDirection.DESC,
        })
```
My createdAt timestamps are based on AWSTimestamp
I still get 0 results even though I have items in the DB that match it.

I am not sure what I am doing wrong, so any advice would be appreciated.

**Comment by RossWilliams** [comment]
AppSync will filter the results of your query after they are fetched from the database (the @auth rules). You need to make your database query only return items related to the user. In general, do not use @auth directives to filter results.

Change your "SortByType" @key fields to ["userId","type","createdAt"] instead so that all results from the database are associated with your user when you query using this key.

**Comment by chantlong** [comment]
@RossWilliams 
Thanks.
In my post earlier, when I mentioned I tried 3 keys, I meant what you said regarding using.
> ["userId","type","createdAt"]

I tried that and used the query without specifying the `createdAt`
```
await API.graphql(
        graphqlOperation(listByInterval, {
          userId: userId
          typeCreatedAt: {
            eq: {
              type: 'A',
            },
          },
          sortDirection: ModelSortDirection.DESC,
        })
```
and with only 10 items in my database with a limit of 10 set, I still got 0 results back.

> In general, do not use @auth directives to filter results.
How is my current @auth rule filtering results?
Specifying the userId in the `$filter` didn't help either.

**Comment by chantlong** [comment]
Any updates on this?

**Comment by RossWilliams** [comment]
You can leave off the createdAt in the example, it’s not required

**Comment by chantlong** [comment]
I am not sure if this is actually an amplify bug, but more of a AppSync bug.

I have tried replicating the same thing with my own app. Instead of `createdAt`, I have `time` as `AWSDateTime`, which is composite sort key of `['userId', 'type', 'time']`

After pushing I can confirm that DynamoDB has the index of `type#time`. I'm not sure if it's normal but the `size` of the index was 0 and the `Item Count` was 0.

Anyways, when I go to AppSync and test a query like 

```
query SortByUserIdAndTypeAndTime($userId:String, $type:Int, $time:String) {
  SortByUserIdAndTypeAndTime(userId: $userId, typeTime: {
    eq: {
      type: $type
      time: $time (optional)
    }
  }) {
    items {
    	id
  	}
  }
}

QUERY VARIABLES
{
  "userId": "XXX"
  "type": 1
}
```
I get back zero results which doesn't make sense because I do have data in the DB that matches that requirement.

**Comment by RossWilliams** [comment]
You likely don’t have an attribute on your items with a 
Key “type#time”. If you add a GSI with a compound sort key, existing items will not have the compound key added to them, you will need to write a migration. New items added via AppSync resolvers will have the new compound key added.

**Comment by chantlong** [comment]
@RossWilliams 

>  If you add a GSI with a compound sort key, existing items will not have the compound key added to them, you will need to write a migration.

Thank you. That seems to make sense. Let me try this out and report my findings.
For writing migrations for existing items, do you have any resources you can share. I'm assuming this is outside the scope of the amplify cli. I'm guessing it's like using an aws sdk and using DynamoDB methods etc.

**Comment by chantlong** [comment]
@RossWilliams It is as you said. It works for new data added in, I just need to migrate my existing data. Thanks a bunch!

**Comment by undefobj** [comment]
@chantlong are you unblocked for us to close this issue? Thanks.

**Comment by chantlong** [comment]
@undefobj Yes thank you, will close this issue.
