### ISSUE TITLE
Misleading "amplify env remove" confirmation prompt

### ISSUE THREAD

**Issue by dantasfiles** [aws-amplify/amplify-cli#3417]
**Describe the bug**
When removing a single environment in CLI v.4.13.2, `amplify env remove` asks a misleading confirmation message:
> Are you sure you want to continue? **(This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files)**

**Amplify CLI Version**
4.13.2

**To Reproduce**
- Run `npx react-native init EnvRemoveTest`
- Initialize Amplify with `env` environment
```
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project EnvRemoveTest
? Enter a name for the environment env 
```
- Add `newenv` environment
```
> amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment newenv
```
- List environments
```
> amplify env list
| Environments |
| ------------ |
| env          |
| *newenv      |
```
- Remove `env` environment. *This is where the scary confirmation prompt shows up.*
```
> amplify env remove env
? Are you sure you want to continue? (This would delete all the environments of the project from the cloud and wipe out all the local amplify resource files) Yes     
- Deleting resources from the cloud. This may take a few minutes...
Deleting env:env
√ Successfully removed environment from the cloud
Successfully removed environment from your project locally
```
- List environments
```
> amplify env list      
| Environments |
| ------------ |
| *newenv      |
```

**Expected behavior**
The confirmation prompt should ask whether you're sure you want to delete the `env` environment.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: 13.8.0

**Comment by ammarkarachi** [comment]
@dantasfiles Thanks for bringing this up we are aware of this issue we will be publishing a fix in the next release
