### ISSUE TITLE
Adding custom query with @aws_auth directive doesn't work

### ISSUE THREAD

**Issue by mkrn** [aws-amplify/amplify-cli#342]
**Describe the bug**
When adding custom query to `type Query` and attempting to use @aws_auth from standard AWS Amplify docs it throws an error with Unknown directive "aws_auth".

**To Reproduce**
Add following to your schema:
```
enum UserStatus {
  UNCONFIRMED,
  CONFIRMED,
  ARCHIVED,
  COMPROMISED,
  UNKNOWN
}

type User {
  username: String!
  sub: String!
  email_verified: Boolean
  phone_number_verified: Boolean
  phone_number: String
  email: String!
  company: Company
  create_date: String
  last_modified_date: String
  enabled: Boolean
  status: UserStatus
  groups: [String]
}

type Query {
  getUser(username: String!): User
  @aws_auth(cognito_groups: ["Admin"])
  listUsers: [User]
  @aws_auth(cognito_groups: ["Admin"])
}
```
2. amplify push
3. Error message would appear `Schema Errors: Unknown directive "aws_auth".`

**Expected behavior**
I would expect @aws_auth directive to be passed on to generated schema as-is as per https://docs.aws.amazon.com/appsync/latest/devguide/security.html 

Use case: create custom type User and custom queries and mutations to manage cognito users through Lambda resolvers accessible only by Admins.

**Desktop (please complete the following information):**
- amplify cli 0.1.28

**Comment by mikeparisstuff** [comment]
Hey @mkrn, thanks for bringing this up. This is fixed here https://github.com/aws-amplify/amplify-cli/pull/345

**Comment by kaustavghosh06** [comment]
This issue is fixed and would be a part of the next CLI version (0.1.30).
