### ISSUE TITLE
Version 4.13.2 on Mac: unexpected token error

### ISSUE THREAD

**Issue by DanielLopez-nbcuni** [aws-amplify/amplify-cli#3421]
**Describe the bug**
After installing amplify-cli via `npm install -g @aws-amplify/cli`. Running any amplify command throws an error.
```
/usr/local/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:47
    catch {
          ^

SyntaxError: Unexpected token {
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (module.js:664:10)
```

**Amplify CLI Version**
4.13.2

**To Reproduce**
- Install `@aws-amplify/cli@4.13.2`
- Run `amplify configure` .. or pretty much anything w/ amplify. Event `amplify -v` fails

**Desktop:**
 - OS: Mac : High Sierra : 10.13.6
 - Node Version: v8.16.0

**Comment by DanielLopez-nbcuni** [comment]
Downgrading to V4.13.0 works fine.

**Comment by attilah** [comment]
@DanielLopez-nbcuni I see you're running Node 8, as Node 8 became unsupported the minimum version for Amplify CLI is Node 10. The problem probably you see is caused by ES6 compatibility in Node 8. Please upgrade to at least Node 10.

**Comment by ricardoguim** [comment]
@attilah It would be great to document this change as well at https://aws-amplify.github.io/docs/ the first thing I checked was the Node version but the setup was informing Node 8 as minimum version.

**Comment by Dafeesh** [comment]
Experienced the same issue. The main installation page still says that Node 8.x is required.
https://aws-amplify.github.io/docs/
