### ISSUE TITLE
CORS error when including javascript file in another domain

### ISSUE THREAD

**Issue by joshglazer** [aws-amplify/amplify-cli#3423]
I am deploying an angular application through amplify and would like to include some static images and one of the generated javascript files into a different application.  I am running into CORS issues and am seeing the following error in my console:

No 'Access-Control-Allow-Origin' header is present on the requested resource.

I have tried a handful of things to fix this, but none have worked.  Can someone please let me know how to fix this?

**Comment by kaustavghosh06** [comment]
@joshglazer Are you using the Amplify CLI or the Amplify console to deploy your application?

**Comment by joshglazer** [comment]
Hi @kaustavghosh06, everything was set up using the Amplify CLI, but I did make a few small changes in the console while trying to fix it.

**Comment by hisham** [comment]
If using amplify console, you can add CORS via ampliify.yml. See https://github.com/aws-amplify/amplify-console/issues/216

Otherwise if using amplify hosting via S3, you can add CORS settings to the s3 bucket. See https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by kaustavghosh06** [comment]
@joshglazer Please take a look at @hisham's recommendation. I would follow that to modify the generated Cloudformation for your hosting resource located in the `amplify` folder.
