### ISSUE TITLE
Hosted UI Endpoint not working

### ISSUE THREAD

**Issue by gaboucand** [aws-amplify/amplify-cli#3428]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
amplify status returns the following kind of url: 
Test Your Hosted UI Endpoint: https://mydomain.auth.eu-west-1.amazoncognito.com/login?response_type=code&client_id=25flgv0rtcmidjo&redirect_uri=http://localhost:/

This url does not work at all.
Moreover it differs from the one provided buy the aws console.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.11.0
**To Reproduce**
amplify auth update
  Walkthrough all the auth configurations
  Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls 
  Allow unauthenticated logins?: no
 Do you want to enable 3rd party authentication providers in your identity pool? : no
 Do you want to add User Pool Groups?:no
 Do you want to add an admin queries API?:no
  Multifactor authentication (MFA) user login options:off
  Email based user registration/forgot password: enable
                  default
                  default
  Do you want to override the default password policy for this User Pool?: no
  Specify the app's refresh token expiration period (in days): (default)
 Do you want to specify the user attributes this app can read and write? N
Do you want to enable any of the following capabilities? (select nothing)
 Do you want to use an OAuth flow? yes
     -->then go ahea

**Expected behavior**
The Url should be the same as the one provided by aws console

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

In file:  packages/amplify-provider-awscloudformation/lib/display-helpful-urls.js
    function: showHostedUIURLs

The problem comes from the following snippet, where URL parameter 'response_type' is hard coded: 
if (redirectURIs.length > 0) {
        const testHostedUIEndpoint = `https://${HostedUIDomain}.auth.${Region}.amazoncognito.com/login?response_type=code&client_id=${AppClientIDWeb}&redirect_uri=${redirectURIs[0]}\n`;
        context.print.info(chalk`Test Your Hosted UI Endpoint: {blue.underline ${testHostedUIEndpoint}}`);
      }

**Comment by gaboucand** [comment]
The same issue affects the following function:

import { Auth } from 'aws-amplify';
Auth.federatedSignIn()

**Comment by ammarkarachi** [comment]
@gaboucand Does the url not show you a sign in page?

**Comment by gaboucand** [comment]
Hi ammarkarachi,

The result depends on the cognito user pool settings.
If you set "_Allowed OAuth Flows_ " to "_implicit grant_" or "_client credentials_",
 then the "Auth.federatedSignIn()) call would return an error.

This is due to the hard coded response type  "_response_type=code_".
It look like it is expected that the user pool is set to use only "_Autorisation code grant_".

Regards
