### ISSUE TITLE
generate graphql schema portion from data source like Elastic Search Mappings

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#3429]
How can I populate my GraphQL schema from another data source? Since ElasticSearch Mappings define what I want my client to use, can I hook into the code generation lifecycle?

Ideally I would be able to mix hand-written schema types with generated schema types, from a variety of sources (at least ES Mappings).

** Which Category is your question related to? **
Api, GraphQL, Plugins

** What AWS Services are you utilizing? **
AppSync, Elastic Search

** Provide additional details e.g. code snippets **
I'm using the latest version of Amplify.

**Comment by SwaySway** [comment]
Hi @cyrfer 
Are you talking about backfilling data from one datasource to another? or are you referring to having a elasticsearch mapping and graphql schema be in parity with types?

**Comment by cyrfer** [comment]
@SwaySway I am talking parity with types.

Right now a developer must hand-type all the `types` in the schema. If a developer wants to expose an existing data store with a defined schema, much care must be taken to type the schema exactly the same.

As a developer, I wish to expose the contents of a datastore via a new API I am writing. I would like to make sure the way I expose it models the data accurately. A tool at my disposal is the Mappings from Elastic Search. I could imagine writing code to transform the schema of the ES data into snippets for a GraphQL schema file.

Is there a part of the plugin lifecycle that would allow me to insert snippets into the GraphQL schema, much the way the AWS directives contribute many snippets?
