### ISSUE TITLE
RootUrl of another API gateway lambda function as environment variable

### ISSUE THREAD

**Issue by alexladerman** [aws-amplify/amplify-cli#3431]
** Which Category is your question related to? **
api & function
** What AWS Services are you utilizing? **
Amplify, Lambda, API Gateway
** Provide additional details e.g. code snippets **
I have two lambda functions each with their own API gateway. One requires authentication, the other is public. The authenticated endpoint will send a purchase order to a 3rd party payment processor.  The order must include the callback url which will receive the order confirmation. I thus need the restapi-id of the public endpoint in order to construct the callback url:

https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/ 

How do I access it as a parameter in the private lambda function?

**Comment by edwardfoyle** [comment]
Hi @alexladerman you are correct that the API ID does not currently get auto-wired into the lambda CFN template. While we investigate adding this by default, here are the manual steps to make it accessible in your lambda. I'm calling the callback API "callbackAPI" (very creative) and the lambda that calls it "purchaseFunc"

in `amplify/backend/api/callbackAPI/callbackAPI-cloudformation-template.json` add the following at the bottom within the "Outputs" block.
```json
"ApiId": {
  "Description": "API ID",
  "Value": {"Ref": "callbackAPI"}
}
```

In `amplify/backend/function/purchaseFunc/purchaseFunc-cloudformation-template.json` within the "Parameters" block at the top add
```json
"apicallbackAPIApiId": {
  "Type": "String",
  "Default": "apicallbackAPIApiId"
}
```
Then, within the `Resources.LambdaFunction.Properties.Environment.Variables`block  in the same file add 
```json
"API_CALLBACKAPI_APIID": {
  "Ref": "apicallbackAPIApiId"
}
```
In `amplify/backend/backend-config.json` within `function.purchaseFunc` add 
```json
"dependsOn": [
  {
    "category": "api",
    "resourceName": "callbackAPI",
    "attributes": [
      "ApiName",
      "ApiId"
    ]
  }
]
```
If there are already entries in the dependsOn list, add the above to it.

Finally, to wire everything together, go to `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` and within the `functionpurchaseFunc.Properties.Parameters` stack add
```
"apicallbackAPIApiId": {
  "Fn::GetAtt": [
    "apicallbackAPI",
    "Outputs.ApiId"
  ]
}
```
After doing this, the purchaseFunc will have access to the API ID via the API_CALLBACKAPI_APIID environment variable and can construct the URL.

Hope this helps get you unblocked while we investigate a better solution.

**Comment by alexladerman** [comment]
Ah, thanks. I'd assumed all the cloudformation templates were managed by
amplify-cli and best not to be tampered with manually.
