### ISSUE TITLE
[Feature Request] Set up Apple Sign-In Hosted UI through Amplify CLI

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#3434]
**Is your feature request related to a problem? Please describe.**
Apple Sign-In with HostedUI is missing from `amplify add auth` flow. 

**Current experience**
1. `amplify init`
2. `amplify add auth`
3. Choosing some defaults with social provider
4. Enter redirect signin URI/redirect signout URL as usual
5. Select Facebook and Google to be configured as social providers for the user pool
6. After finishing the steps on the individual Facebook and Google developer sites, go back to the CLI and enter information needed for the OAuth flow, such as for facebook the AppID and AppSecret. For Google, the Web Client ID and Web Client Secret.
7. `amplify push` to provision the Cognito User Pool with hosted UI configured. You will see the hosted UI endpoint.

8. Go over to https://aws.amazon.com/blogs/security/how-to-set-up-sign-in-with-apple-for-amazon-cognito/  and follow the step 1 to set up the Identifier on Apple's Developer portal. Information needed for this step is the hosted UI endpoint like `https://<your domain>/oauth2/idpresponse`

9. Step 2 from the blog is to select Sign In with apple, provide the Apple Services ID, Team ID, Key ID, and private key. Update Attribute mappings. And enable app client via App Integration -> App client settings -> select Sign in with Apple.

10. Launching the HostedUI or going to the endpoint should show the sign in with apple button. If launching the HostedUI from `AWSMobileClient`, the hostedUI parameter is "SignInWithApple".

11. Testing sign in, and upon successful sign in, should redirect to the redirect sign in URL specified earlier.

**Describe the solution you'd like**
- Is it possible to replace steps 9 that is done through the Cognito Userpool console with CLI flow?

**Additional context**
A callout here is that we need the HostedUI endpoint for step 8, which we don't get until after `amplify push` (I think). The Apple set up flow might be different from Facebook/Google, so there needs some investigation on the actual solution for this.

**Comment by attilah** [comment]
@lawmicha no, it is currently not possible through the CLI.

**Comment by lawmicha** [comment]
related https://github.com/aws-amplify/docs/issues/1127

**Comment by lawmicha** [comment]
any timeline for this? we're currently patching existing docs with cognito's blog https://github.com/aws-amplify/docs/pull/1220 and just want to track when to update the docs again

**Comment by lawmicha** [comment]
Android's flow https://github.com/aws-amplify/docs/issues/1250

**Comment by josefaidt** [comment]
Closing as this has since been addressed, reference https://github.com/aws-amplify/amplify-cli/issues/3929
