### ISSUE TITLE
GraphQL Explorer for "amplify mock api" stopped working after upgrading to CLI 4.13.3

### ISSUE THREAD

**Issue by dantasfiles** [aws-amplify/amplify-cli#3435]
**Describe the bug**
GraphQL Explorer for `amplify mock api` stopped working after upgrading to CLI 4.13.3

**Amplify CLI Version**
4.13.3

**To Reproduce**
I have an existing React Native app that I successfully ran the GraphQL Explorer on `amplify mock api` a few days ago.

Today, I ran `npm -g install @aws-amplify/cli@latest` to get CLI v.4.13.3

Now when I run `amplify mock api` (no errors are shown in terminal) and then open GraphQL Explorer, a blank page opens and I get the following errors in Chrome Developer Tools (**see screenshots below**)

I downgraded the CLI back to 4.13.2, and cleared my browser cache, and it worked again.

**Screenshots**
**Working in 4.13.2**
![image](https://user-images.githubusercontent.com/9329599/74595883-12e8bf80-5015-11ea-9057-3f096773dbcd.png)
**Not working in 4.13.3**
![image](https://user-images.githubusercontent.com/9329599/74595895-55aa9780-5015-11ea-9ce1-f03706196ca8.png)
**Working again after downgrade to 4.13.2**
![image](https://user-images.githubusercontent.com/9329599/74595912-a02c1400-5015-11ea-94f0-7c25f5648b24.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 13.7.0

**Comment by dantasfiles** [comment]
I upgraded the screenshots in the original post.

**Comment by arkllc** [comment]
facing the same issue

**Comment by shaunprocterdev** [comment]
I have the same issue as the 'Not working in 4.13.3' screengrab, with the same status message/code for the relevant js and css files. Except downgrading doesn't resolve the issue for me. I was on v14.3.3 and have tried downgrading to v14.3.2 and v14.3.1. I have also tried node v13.8.0 and v10.16.3.

**Comment by dantasfiles** [comment]
@shaunprocterdev after downgrading to 4.13.2, I had to clear my browser cache for the site before it would work again

**Comment by shaunprocterdev** [comment]
Thanks @dantasfiles! That forced me to revisit it and down grading to v4.13.2 resolved the issue. It turns out that when I was swithcing between versions of node I was mistakenly thinking I was downgrading versions of the cli but my amplify binary was still v4.13.3.

**Comment by kaustavghosh06** [comment]
We've root-caused the issue and working on a fix for this which will be released soon.
cc: @attilah

**Comment by gautamkshitij** [comment]
So that works if you open localhost:20002 
https://github.com/aws-amplify/amplify-cli/issues/4002
