### ISSUE TITLE
Latest version 4.13.3-- can not init due to plugins error.

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#3439]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Upgraded to aws-amplify/cli@4.13.3.

Attempt to init a new gatsby project to upload it to amplify fails with the following--

Error: Found no provider plugins
Run 'amplify plugin scan' to scan your system for provider plugins.
init failed

Scanning for plugins...
The following official plugins are missing or inactive:
    awscloudformation: provider | amplify-provider-awscloudformation@4.13.3
    codegen: util | amplify-codegen@2.13.3
    mock: util | amplify-util-mock@3.14.0
Plugin scan successful

To my knowledge, there should have been no change to these plugins as they worked the last 72 hours.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.3.3

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

amplify init

**Expected behavior**

Expect to complete init without error as I have done the last few weeks and then setup git push to deliver to amplify

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

Ubuntu 19.04, node version 12.15.0

**Additional context**
Have tried re-installing aws-amplify/cli, reinstalled all node_modules (local).  I saw in prior errors of this kind on windows, users had to manually link plugins giving file path and name.  I didn't see similar way to do on linux.

**Comment by weisisheng** [comment]
After about 6 hours of grubbing around, found this recommendation, #2746.  Removing the yarn global dir and reinstalling using npm seems to fix my problem.  Ugh.

**Comment by codypenta** [comment]
Can confirm this issue is still relevant as of today, using yarn (on windows FWIW) will not let you init correctly. You need to install the cli with npm.

**Comment by simpleauthority** [comment]
Can also confirm, just experienced this.

**Comment by noise-machines** [comment]
Could we add a note to the docs specifying that you *must* use npm and *must* install the CLI globally? In the JS ecosystem, you can normally use yarn or npm as you please, and install globally or locally, so this behavior is quite confusing.

**Comment by simpleauthority** [comment]
Would move to reopen this issue, as it is still an issue.

What is the best avenue? New issue and reference this, or ping someone on the team to reopen?

How about I start with pinging OP and asking for reopen: @weisisheng

**Comment by weisisheng** [comment]
I don't know what the protocol is for re-opening but feel free if you wish to keep alive.

**Comment by volkanunsal** [comment]
I'm having the same issue, despite the fact that I installed the CLI using npm and globally.

**Comment by waelio** [comment]
? Choose your default editor: Visual Studio Code
Found no provider plugins
Run 'amplify plugin scan' to scan your system for provider plugins.
Error: Found no provider plugins
    at getProviders (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\init-steps\s2-initProviders.js:50:15) 
    at initProviders (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\init-steps\s2-initProviders.js:32:29)
    at Object.run (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\commands\init.js:29:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.executeAmplifyCommand (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\index.js:236:9) 
    at async executePluginModuleCommand (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\execution-manager.js:164:5)
    at async Object.executeCommand (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\execution-manager.js:35:9)     
    at async Object.run (C:\Users\wahbe\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\index.js:112:9)
