### ISSUE TITLE
Perhaps a bug when adding auth with custom challenge flow.

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3441]
**Describe the bug**

When adding auth and selecting "Custom Auth Challenge Flow", several lambda functions are created.
For each one we have several files, one of them is index.js

```
exports.handler = (event, context, callback) => {
  const modules = process.env.MODULES.split(',');
  for (let i = 0; i < modules.length; i += 1) {
    const { handler } = require(`./${modules[i]}`);
    handler(event, context, callback);
  }
};
```

When I try to use that flow, I receive this error:

Printing description of error:
```
▿ Optional<Error>
  ▿ some : AWSMobileClientError
    ▿ invalidLambdaResponse : 1 element
      - message : "Invalid lambda function output : Invalid JSON"
```

However, after adding:
`context.done(null, event);`
to all this files (3 or 4, in my case 4 because I also added pre sign up manually), I don't receive that error anymore (I receive others, but that is another story....).

This is how the code looks like when working:
```
exports.handler = (event, context, callback) => {
  const modules = process.env.MODULES.split(',');
  for (let i = 0; i < modules.length; i += 1) {
    const { handler } = require(`./${modules[i]}`);
    handler(event, context, callback);
  }
  context.done(null, event);
};
```

I don't know if this is related but I also updated:
"Runtime": "nodejs10.x",
To
"Runtime": "nodejs12.x",
from (function name)-cloudformation-template.json

BTW, why do we have all this boiler plate code for such simple functions? Is it really necessary to have "index.js" and "boilerplate-create-challenge.js", why not everything in "index.js"?

**Amplify CLI Version**
4.13.3

**To Reproduce**
amplify auth add
select custom auth flow.
try to use it.

**Expected behavior**
Lambda functions should work.

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.3
 - Node Version. v13.2.0

**Comment by ammarkarachi** [comment]
@Ricardo1980 are your handlers returning values? The error is thrown because an undefined i return from you function in index.js

**Comment by Ricardo1980** [comment]
Hello @ammarkarachi 

I think so, here you have my pre sign up lambda function:

boilerplate-pre-sign-up.js:
```
"use strict";

exports.handler = async (event) => {
    console.log('Received EVENT', JSON.stringify(event, null, 2));
    event.response.autoConfirmUser = true;
    event.response.autoVerifyPhone = true;
    return event;
};
```

index.js:
```
/*
  this file will loop through all js modules which are uploaded to the lambda resource,
  provided that the file names (without extension) are included in the "MODULES" env variable.
  "MODULES" is a comma-delimmited string.
*/

exports.handler = (event, context, callback) => {
  const modules = process.env.MODULES.split(',');
  for (let i = 0; i < modules.length; i += 1) {
    const { handler } = require(`./${modules[i]}`);
    handler(event, context, callback);
  }
};

```

**Comment by Ricardo1980** [comment]
@ammarkarachi  I think the problem is in the structure created by amplify CLI.
Check my response here:
https://github.com/aws-amplify/amplify-cli/issues/3443

**Comment by ammarkarachi** [comment]
@Ricardo1980 Does it work in node 10.x?

**Comment by kaustavghosh06** [comment]
@Ricardo1980 With the change you made to the Lambda function, does it work with NodeJS 10.x runtime? Is it backwards compatible?

**Comment by Ricardo1980** [comment]
@kaustavghosh06 I tried to use NodeJS 10.x runtime in the 4 functions this code in all those index.js files
```
exports.handler = (event, context, callback) => {
  const modules = process.env.MODULES.split(',');
  for (let i = 0; i < modules.length; i += 1) {
    const { handler } = require(`./${modules[i]}`);
    handler(event, context, callback);
  }
};
```
And I receive the same error:
"Invalid lambda function output : Invalid JSON"

BTW, can you explain to me the steps to remove everything about that boiler plate structure?
I think it is useless for such small methods, and causing errors.

Thanks a lot.

NOTE: If I use node12 and I put my actual code in index.js, then it works.
