### ISSUE TITLE
Should amplify env checkout prompt me to configure Lambda Triggers for Cognito?

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3442]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.12.0

**What AWS Services are you utilizing?**
Cognito, Lambda

**Provide additional details e.g. code snippets**
When I run `amplify env checkout staging` I'm always prompted with `Do you want to configure Lambda Triggers for Cognito?` Is this intended? 

```
git:(staging) amplify env checkout staging
✔ Initialized provider successfully.
? Do you want to configure Lambda Triggers for Cognito? No
Initialized your environment successfully.
```

**Comment by kaustavghosh06** [comment]
@alexkates The questions depends on which environment you're checking out from. Is the environment that you're checking out from has Lmabda triggers configured?

**Comment by alexkates** [comment]
We have 1 environment named prod that has 2 lambda triggers for cognito, preSignUp and customMessage. Staging is a brand new environment that we are trying to create.

**Comment by alexkates** [comment]
Hey guys, it's been a while but this is still an outstanding issue... is there any more information I can provide to help move this along?

**Comment by ammarkarachi** [comment]
Hi @alexkates, sorry for the delay. The env shouldn't prompt you if you have executed the `amplify push` command. Is this the case?

**Comment by alexkates** [comment]
I'm not. This is also happening if I create a new environment. I'm relying on the Amplify build/deploy pipelines to do this for me. Here is what I'm doing...

1. git checkout master && git pull
2. amplify pull (not entirely sure if this is needed)
3. Amplify env add
   Use an existing env? no
   Enter name of env
   Do you want to use a profile? Yes, default
   **Do you want to configure Lambda Triggers? No**
8. Inspect team-provider-info.json to make sure it makes sense.
9. git add . && git commit -m “provisioning new env” && git push
10. git checkout -b newenv && git push -u origin newenv

**Comment by ammarkarachi** [comment]
@alexkates you could create an environment without the triggers and then create a new environment off of that. Normally you would need to go through a trigger setup if you are cloning from an environment that already has one.

**Comment by kaustavghosh06** [comment]
@alexkates Closing this issue based on @ammarkarachi's response. Please let us know if you're still stuck.
