### ISSUE TITLE
Customising aws_cognito_user_pools annotation

### ISSUE THREAD

**Issue by steveparkerSG** [aws-amplify/amplify-cli#3446]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.11.0

**Provide additional details e.g. code snippets**

Given

```graphql
type Mutation {
  createSomething(input: AWSJSON): Something @function(name: "createSomething-${env}")
}
```

How can I scope this custom mutation to permit only certain cognito groups? Does the `@aws_cognito_user_pools` annotation take any arguments? There doesn't appear to be any docs on it.

**Comment by kaustavghosh06** [comment]
@steveparkerSG You can probably use the @auth directive and scope it to groups. You can read more here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth

**Comment by steveparkerSG** [comment]
@kaustavghosh06 using @auth on a custom mutation gives warnings about the auth affecting the root type. Everything else I've read says this doesn't work on custom mutations.

**Comment by ammarkarachi** [comment]
@steveparkerSG Can you try it with the lates version this should be working now.

**Comment by kaustavghosh06** [comment]
@steveparkerSG Let us know if you're still stuck on this. As @ammarkarachi mentioned above - this should be fixed in the latest version of our CLI.
