### ISSUE TITLE
amplify push new environment fails

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3449]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
We are trying to create a new environment using `amplify env add` and then try to push using `amplify push` but it fails when attempting to create a function.

**Amplify CLI Version**
4.13.3

**To Reproduce**
For our stack...
1. `amplify env add newenv`
2. `amplify push`

**Expected behavior**
The newenv to be created.

**Screenshots**
Console output...
```
✖ An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, stat '/Users/me/Repositories/myProject/amplify/backend/function/myFunction/src/node_modules/.bin/acorn'
An error occured during the push operation: ENOENT: no such file or directory, stat '/Users/me/Repositories/myProject/amplify/backend/function/myFunction/src/node_modules/.bin/acorn'
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.14.1

**Additional context**
We have created custom cloudformation resources in this project, following the guide on how to do this. We've also had to manually update the function cloudformation templates and commit them to git. Also, when we look at this environments cloudformation stack, it's reporting created successful and all of our resources appear to have been created.

**Comment by kaustavghosh06** [comment]
@alexkates Are you using acorn CLI as a part of your build script as a part of  a function?

**Comment by alexkates** [comment]
As far as I can tell I'm not explicitly using acorn in any of our backend services. I believe acorn is also a dependency of one of our dev-dependencies in our backend functions. 

That being said, it is a non-development dependency in the root's package.json.

**Comment by alexkates** [comment]
Quick update, we were able to get the new env to push successfully by moving our backend lambda's dev-dependencies located in each package.json up to normal dependencies. Obviously not ideal, but that's how we were able to get past this. I don't mind providing more input for debugging this for the future, just let me know if you need any more information from me. We are also going to keep investigating since it'd be ideal for us to have our lambda functions as slim as possible.

**Comment by ammarkarachi** [comment]
@alexkates can you share the structure of you project?

**Comment by alexkates** [comment]
@ammarkarachi 
```
➜  myapp git:(master) ✗ amplify status

Current Environment: prod

| Category | Resource name            | Operation | Provider plugin   |
| -------- | ------------------------ | --------- | ----------------- |
| Api      | api1                     | No Change | awscloudformation |
| Storage  | storage1                 | No Change | awscloudformation |
| Storage  | storage2                 | No Change | awscloudformation |
| Storage  | storage3                 | No Change | awscloudformation |
| Function | function1                | No Change | awscloudformation |
| Function | function2                | No Change | awscloudformation |
| Function | function3                | No Change | awscloudformation |
| Function | function4                | No Change | awscloudformation |
| Function | function5                | No Change | awscloudformation |
| Function | function6                | No Change | awscloudformation |
| Api      | api2                     | No Change | awscloudformation |
| Api      | api3                     | No Change | awscloudformation |
| Api      | api4                     | No Change | awscloudformation |
| Auth     | auth1                    | No Change | awscloudformation |
```
