### ISSUE TITLE
gitignore custom cloudformation files?

### ISSUE THREAD

**Issue by ambriglia** [aws-amplify/amplify-cli#3456]
**Which Category is your question related to?**
Functions (APIs)

**Amplify CLI Version** 
4.11.0

**What AWS Services are you utilizing?**
Lambdas, Cloudformation, API Gateway, S3

**Provide additional details e.g. code snippets**
Referencing [this issue](https://github.com/aws-amplify/amplify-cli/issues/968) and [this issue](https://github.com/aws-amplify/amplify-cli/issues/3034) it sounds like we should be gitignoring our cloudformation templates. How does that make sense? We are making custom changes to the generated cloudformation templates... how will amplify pick those changes up if they are gitignored?

**Comment by edwardfoyle** [comment]
@ambriglia which CFN files are you modifying? The CFN files in each category are not ignored and are safe to update. The only one that you should generally not make changes to is `amplify/backend/awscloudformation/nested-cloudformation-stack.yml`

**Comment by ambriglia** [comment]
We heavily modify our lambda and api gateway templates. However, your response conflicts with the two issues I referenced. Both those issues seem to suggest to gitignore any cloudformation template file to get around the s3key and s3bucket dynamic names multiple environment git conflict issue.

**Comment by edwardfoyle** [comment]
You should gitignore `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` (which is ignored by default when running `amplify init`). As @kaustavghosh06 mentioned [here](https://github.com/aws-amplify/amplify-cli/issues/3034#issuecomment-569988489), you should include modified resource CFN files in your repo and can safely ignore diffs on the s3key.

**Comment by ambriglia** [comment]
Does this logic also apply to the s3Bucket name?

**Comment by edwardfoyle** [comment]
Yes the bucket name will change based on which environment was last pushed, but it won't break anything to include it in your repo. It will cause your lambdas to be updated on every push when switching environments even if there was no change to the lambda. If you want to avoid this you can exclude s3bucket and s3key diffs when merging between branches.

**Comment by alexkates** [comment]
I know this was closed, but is there any updates on the feature mentioned by @kaustavghosh06 [here](https://github.com/aws-amplify/amplify-cli/issues/3034#issuecomment-569988489)?
