### ISSUE TITLE
What IAM user is used with amplify function invoke?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#3461]
**Which Category is your question related to?**
functions

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
Lambda

**Provide additional details e.g. code snippets**
I'm invoking a function locally using `amplify function invoke`. The lambda tries to get a secret from secrets manager. But I am getting an error like this: 

`AccessDeniedException: User: arn:aws:iam::<redacted> is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:<redacted>`

Looking into it, it looks like amplify function invoke is using the wrong iam user. It's using an iam user in another aws account I have where there is another project (in a separate dir) that is also using amplify cli. 

How does amplify function determine under which IAM user to invoke the lambda under? Everything else with my amplify (e.g. amplify push) works fine.

**Comment by hisham** [comment]
Ok I resolved this. It seems that amplify function invoke uses the default aws profile as specified in ~/.aws/credentials, and not the profile set for the amplify project via the amplify configure command. 

So to me this seems like a bug. amplify function invoke should use the credentials specifieid in the amplify configure command, not the default in ~/.aws/credentials.

**Comment by kaustavghosh06** [comment]
@hisham Yes, the CLI doesn't do anything special for this. It follows aws-sdk's chain of rules - i.e it first looks at process env variables for the creds and then the default profile and then uses it to sign AWS requests. I believe you can specify the profile name you want to use in your aws sdk configuration in the Lambda function.

**Comment by kaustavghosh06** [comment]
@hisham Let us know if my response needs more clarification or if you have more questions around this. Closing this issue.
