### ISSUE TITLE
Amplify Publish with the -c flag

### ISSUE THREAD

**Issue by MattWlodarski** [aws-amplify/amplify-cli#3463]
I am hosting an ionic/angular project with CloudFront. Whenever I run amplify publish -c , a new Invalidation request is sent to CloudFront, however, this does not actually invalidate the cache. I have determined that it is because the object path that gets auto-set by amplify is /*. If I manually create an invalidation request using an object path of * instead of /*, it works just fine.

Is it possible to configure my amplify project to use * instead of /* for the object path so I don't have to manually create an invalidation request each time?

**Comment by UnleashedMind** [comment]
The Amplify CLI sends invalidation request on "/*", and according to the CloudFront [documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html)
```
To invalidate all of the files in a distribution:
/*
```

**Comment by SwaySway** [comment]
Closing issue due to lack of response. Should you still experience issues with this feel free to comment below.
