### ISSUE TITLE
Conditional Check for custom primary key 

### ISSUE THREAD

**Issue by Gl0ntz** [aws-amplify/amplify-cli#3468]
**Is your feature request related to a problem? Please describe.**

I am not sure if this is a known thing. I searched for similar open issues haven't found any.
When I set a custom primary key for a model like this example : 
```graphql
type Project @model @key(fields:["projectId"]) {
     projectId:ID!
     projectName:String
}
```

When I run the auto generated CreateProject Mutation there is no conditional check for the primary key projectId. Instead it overwrites any existing items with the same primary key.

**Describe the solution you'd like**

Since we are describing the @key directive, I am assuming the CLI can do this automatically while it provisions the resolvers?
Also what will be the behaviour for compound primary keys with hash keys and sort keys?

**Describe alternatives you've considered**

 I was able to solve my issue by editing the resolver for Mutation create Project and adding 
``` json
#set( $condition = {
  "expression": "attribute_not_exists(#projectId)",
  "expressionNames": {
      "#projectId": "projectId"
 }})
```

**Comment by RossWilliams** [comment]
@ammarkarachi enhancement? Seems like a bug that graphql-dynamodb-transformer functionality that fails to account for the primary key not always being 'id'. Its not documented for the user that changing the pk name comes at the cost of broken features.

**Comment by ammarkarachi** [comment]
@RossWilliams you are right it should be treated as a bug

**Comment by bdunks** [comment]
I've just come across the same issue.

It looks [the logic to check for a custom primary key using `ModelObjectKey`](https://github.com/aws-amplify/amplify-cli/blob/1f374373061fff59b97e0f7ab3b3b84d1412416e/packages/graphql-dynamodb-transformer/src/resources.ts#L515-L523) already exists in the `makeUpdateResolver` method. 

Perhaps the same or similar logic, swapping `attribute_exists` for `attribute_not_exists`, could be applied to where the [primary key is hard coded to `id`](https://github.com/aws-amplify/amplify-cli/blob/1f374373061fff59b97e0f7ab3b3b84d1412416e/packages/graphql-dynamodb-transformer/src/resources.ts#L400-L404) in the makeCreateResolver method?

**Comment by attilah** [comment]
Closing in favor for #7261
