### ISSUE TITLE
Second @auth rule in GQL Transform overwrites VTL response template, removing owner auth checks

### ISSUE THREAD

**Issue by gabehollombe-aws** [aws-amplify/amplify-cli#3469]
**Describe the bug**
Using the GraphQL Transform @auth directive, when I use only `@auth( rules: [ {allow: owner} ]) ` then the VTL response template is properly generated to restrict items to the currently authenticated user. However when I have multiple like this:

``` graphql
@auth(
  rules: [
    {allow: owner},
    {allow: private, operations: [read]},
  ]
) 
```

then the VTL response mapping template for the ListFoo query (where Foo is my model type name) returns only:

``` 
$util.toJson($ctx.result)
```

**Amplify CLI Version**
Tested with Amplify CLI versions 4.13.3 and 4.13.4

**To Reproduce**
Try a schema like 

``` graphql
type Foo 
@model 
@auth(
  rules: [
    {allow: owner},
    {allow: private, operations: [read]},
  ]
) 
{
  id: ID!
  name: String!
}
```
run an `amplify push` and then look at the ListFoo resolver's response mapping template that was generated by the GraphQL Transform.  It should be filtering out items based on owner, but it doesn't. 

**Expected behavior**
I expect multiple auth rules to work together and not overwrite each other.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Node Version v13.8.0

**Comment by RossWilliams** [comment]
> It should be filtering out items based on owner, but it doesn't.

Auth rules grant access when any one rule authorises the action. Your private rule allows anyone with a JWT token from the user pool to access the data. JWT checking it done at the AppSync level, so the vtl resolver appears correct in this case, as owner auth is not needed to read the model.

> I expect multiple auth rules to work together and not overwrite each other.

With these two auth rules on your model, can you describe the authorisation you would expect to see in more detail? If you want to restrict reads to owners, you can remove the ```allow: private``` rule.

**Comment by gabehollombe-aws** [comment]
Thanks for the reply @RossWilliams  -- I misunderstood how {allow: private} works and forgot to add `provider: iam` to my private auth rule to achieve what I intended (which was owner auth via cognito user pool, iam auth for a lambda granting read access).
