### ISSUE TITLE
How to to update value for @key field 

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-cli#3470]
**Which Category is your question related to?**
API 

**Amplify CLI Version** 
4.13

** What AWS Services are you utilizing? **
AWS AppSync + Lambda + DynamoDB

** Provide additional details e.g. code snippets **
E.g. Sample code, versions of Amplify you are using

I am unable to update the `status` field on my `Item` model.

The schema is as follows:

```graphql
type Item
  @model
  @key(fields: ["id", "status", "createdAt"])
  @key(
    name: "ByStatus"
    fields: ["status", "createdAt"]
    queryField: "itemsByStatus"
  )
 {
  id: ID!
  quantity: Int
  status: RepairStatus!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime

}
enum RepairStatus {
  Pending
  PackageEnRoute
  WaitingForPackage
  PackageReceived
  InRepair
  Repaired
  InTransit
}

```
When I attempt to update the any of the @key fields (`status` or `chargeDate`) like so:

``` js
    const updateVars = {
      input: {
        id: item.id,
        status: "PackageEnRoute", // Attempting to change to a different status
        chargeDate: item.chargeDate,
        quantity: event.target.value
      }
    };
    await updateItemFunction({
      variables: updateVars
    });
  };

```

DynamoDB throws the following error :

``` js
errors:
   [ { path: [Array],
       data: null,
       errorType: 'DynamoDB:ConditionalCheckFailedException',
       errorInfo: null,
       locations: [Array],
       message:
        'The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: 43UPEFGHDVQF9UKUF78MQN7CSRVV4KQNSO5AEMVJF66Q9ASUAAJG)' } ] }
```

The VTL is pretty complicated to debug. Can anyone point out if I'm using something incorrectly?

**Comment by waltermvp** [comment]
Seems you cannot update the sortKey value (which contains `status`)  https://stackoverflow.com/questions/56709500/dynamodb-update-an-attribute-used-as-sort-key 

is there a pattern/step I'm missing here?

**Comment by waltermvp** [comment]
#3475

**Comment by RossWilliams** [comment]
you can make the key a GSI by giving it a name, hash key and sort key on GSIs can be updated.

**Comment by waltermvp** [comment]
@RossWilliams due to my ignorance, can you please show me what that would look like in the schema using @key?

**Comment by waltermvp** [comment]
<img width="2052" alt="Screen Shot 2020-02-19 at 4 08 07 PM" src="https://user-images.githubusercontent.com/1158238/74876680-168c8700-5332-11ea-97da-2deffcd6fa2a.png">
The schema above does generate a GSI named ByStatus. I think there is something missing in my understanding of this.

**Comment by RossWilliams** [comment]
your model has two @key directives. The first @key directive does not specify a name, so it is the key structure on the primary table. After inserting an item, the values of the keys on the primary table cannot be changed.

If you need to change the 'status' property, do not add it as a key on the primary table.

Looking at your key design, i think you are better off removing the first @key directive completely. The way you have set it up, you will be unable to fetch an item without knowing the id, status, and createdAt values. You probably just want to access items by id on the primary table.

Unfortunately, you cannot modify the main table key structure after it has been created. If you are just testing things out, the fastest thing to do is just create a new environment after removing the @key directive.

**Comment by waltermvp** [comment]
@RossWilliams I knew I was misunderstanding something. Makes sense, ill give it a shot in a few and close the ticket. Thank you!

**Comment by waltermvp** [comment]
That was it thank you very much.
