### ISSUE TITLE
Update E2E tests and function builds to handle spawned process' exit codes properly as failure 

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#3473]
**Describe the bug**

During E2E test runs in CI launched child process exit code handling must be reviewed, and all other places where we're spawning processes. Make sure we're handling non-zero exit codes properly in tests and during normal runs like ```amplify push```, which implies a function build step, which can fail at ```npm install```.

**Comment by kaustavghosh06** [comment]
The fix for this is merged?

**Comment by yuth** [comment]
> The fix for this is merged?

No. this is the follow up task from the PR. We need to investigate this
