### ISSUE TITLE
Is amplify support multiple hosting?

### ISSUE THREAD

**Issue by juunone** [aws-amplify/amplify-cli#3479]
**Which Category is your question related to?**
Hosting

**Amplify CLI Version** 
`3.17.0`

**What AWS Services are you utilizing?**
I want to add another hosting my repositories, but it's return error
`Error: Hosting is already fully enabled.`

e.g.
``` 
first env deploy to s3
second env deploy to cloudfront
```
can i deploy multiple hosting my repositories?

so thank you for amplify team. it's getting me to comfortable to develop

**Comment by ammarkarachi** [comment]
@juunone Amplify does not support multiple hosts, Don't hesitate to reach out if you have any other questions.

**Comment by kaustavghosh06** [comment]
@juunone Having said that you can do this with the Amplify console  hosting service - https://aws.amazon.com/amplify/console/
cc @swaminator

**Comment by juunone** [comment]
> @juunone Having said that you can do this with the Amplify console hosting service - https://aws.amazon.com/amplify/console/
> cc @swaminator

great!! i can hosting service with aws console
