### ISSUE TITLE
@auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3480]
**Describe the bug**
In schema when I limit access to groups then I cannot generate datastore models and cannot push to the cloud

**Amplify CLI Version**
amplify 4.13.4

**To Reproduce**
`npx create-react-app notes --use-npm --template typescript`
`npx amplify-app@latest`
`amplify init`
`amplify add auth` everything default
`amplify update auth` to create cognito user group "admin"
then update graphql schema to following
```
type Note @model
  @auth(rules: [{allow: groups, groups: ["admin"]}]) {
  id: ID!
  content: String!
}
```
or 
```
type Note @model
  @auth(rules: [{allow: owner}]) {
  id: ID!
  content: String!
}
```
After this step all of the following commands fail with same exact error as title
`npm run amplify-modelgen`
`amplify codegen models`
`amplify push`

everything fails with following error
`@auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.`

alternatively I used the following method
`npx create-react-app notes --use-npm --template typescript`
`npx amplify-app@latest`
updated graphql schema
```
type Note @model {
  id: ID!
  content: String!
}
```
`npm run amplify-push`
`amplify add auth` everything default
`amplify push`
updated graphql schema to 
```
type Note @model
  @auth(rules: [{allow: owner}]) {
  id: ID!
  content: String!
}
```
now I tried to push
`amplify push`
Now my auth is created schema is on update stage and I still get the same error

**Expected behavior**
It should generate models and should be able to push to cloud.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 12.16.1

**Comment by kaustavghosh06** [comment]
@apoorvmote Did you run `amplify update api` to use Cognito as the auth mode?

**Comment by apoorvmote** [comment]
@kaustavghosh06 No I didn't and when I tried it worked. Thanks.

For others who are interested I did following.
`npx create-react-app notes --use-npm --template typescript`
`npx amplify-app@latest`
then update graphql schema without auth to whatever you want. e.g.
```
type Note @model {
  id: ID!
  content: String!
}
```
then you need to initialize amplify project you can do with `amplify init` but I went with recommended approch to just push everything to aws
`npm run amplify-push` I am sure there are options to be add on this line
`amplify add auth` add any auth settings you like
change graphql schema to make use of this auth e.g.
```
type Note @model
  @auth(rules: [{allow: owner}]) {
  id: ID!
  content: String!
}
```
**NOW HERE IS THE MISSING STEP**
`amplify update api`
Protect the api with congnito auth.
then simply `amplify push` and it just works.
