### ISSUE TITLE
Scoped filtering for unauthenticated users

### ISSUE THREAD

**Issue by DanielMuller** [aws-amplify/amplify-cli#3481]
**Which Category is your question related to?**
Appsync

**Amplify CLI Version** 
4.13.4

**What AWS Services are you utilizing?**
appsync, cognito

**Provide additional details e.g. code snippets**

Using a simple "blog app", registered users can create new posts. Anonymous users can read the posts.

I want to apply a default filter for anonymous users, so that they can't see not yet published posts.

I tried to find a similar request in the issues, but didn't find anything in the same area. Sorry if it is already there and I didn't look hard enough.

A simplistic schema to explain:
``` graphql
type Post
  @model
  @auth(rules: [
    {allow: private, provider: userPools}
    {allow: public, provider: iam, operations: [read]}
  ])
{
  id: ID!
  title: String!
  content: String!
  status: status!
  publishedAt: AWSDateTime
}

enum Status {
  draft
  published
}
```

I want to be able to use a default filtering to only display posts with `status='published' and pubishedAt<now` to public users.

I could achieve this by passing the filter from the client, but I want to enforce the filtering to not have data leakage.

How could I achieve this server side?
- some kind of clever owner/group rule in @auth ?
- resolver override: how to identify auth vs unauth users? How to play with `now` in VTL?
- Lambda resolver ?

Thanks for guiding me into the right direction.

**Comment by ammarkarachi** [comment]
Hi @DanielMuller , You could write a custom resolver as shown [here](https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers) and access the identity through the context as shown [here](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity) and compare date using nowISO or nowEpoch in the [context util](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html). Let me know if you need more info on how to go about it

**Comment by DanielMuller** [comment]
Thanks @ammarkarachi for pointing me to the right resources.
I definitively need to try this way.

Currently, as a workaround, I implemented a REST API querying the DynamoDB tables via Lambda.
