### ISSUE TITLE
When importing Angular AmplifyService it introduces ERROR in Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-cli#3483]
Cross posting.  Is Amplify JS Still alive?
https://github.com/aws-amplify/amplify-js/issues/4920

**Comment by kaustavghosh06** [comment]
@fireflysemantics Yes, it's very much alive and I've informed the team to take a look at your request. 
We look at GitHub issues at first come first serve basis and the team will review the request accordingly.
