### ISSUE TITLE
Upgraded to 4.13.0 breaks graphql query/subscription/mutation generation

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3484]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Using amplify 4.13.0, `amplify mock` seems to cause subscriptions, queries and mutations to regenerate with invalid syntax. See the screenshots sections for details here.

**Amplify CLI Version**
4.13.0

**To Reproduce**
1. Upgraded the @aws-amplify/cli package from 4.12.0 to 4.13.0.
2. `amplify mock`
3. src/graphql files are generated in a different format that normal, and it doesn't look valid.

**Expected behavior**
I'd expect the query/mutation/subscription files to be generated as strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/632749/74960033-99b4e800-53d9-11ea-8fe5-8ef17fcbfc73.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.14.1

**Additional context**
Downgrading to 4.12.0 for now resolves this for me. Also, I'm not finding anything in the 4.13.0 release notes that would be pertinent.

**Comment by kaustavghosh06** [comment]
@alexkates This change is a part of this PR - https://github.com/aws-amplify/amplify-cli/pull/2706
The added change is just for syntax highlighting. Did you check with your app and see if the queries/mutations/subscription are broken?

**Comment by alexkates** [comment]
I did not. My local Amplify GraphiQL Explorer was not working, at which point I submitted this bug. The explorer is simply a blank page.

**Comment by kaustavghosh06** [comment]
Can you upgrade to @latest version of the CLI? We fixed a few UI errors in the mock UI in the latest version. Please let us know if you're still seeing a blannk page with v 4.13.4.

**Comment by alexkates** [comment]
Ok will do. I'll get to it today/early tomorrow. Thanks!

**Comment by kaustavghosh06** [comment]
@alexkates Did you get a chance to validate?

**Comment by kaustavghosh06** [comment]
Closing this issue. Please let us know if you're still stuck on this issue.
