### ISSUE TITLE
issue with amplify-cli

### ISSUE THREAD

**Issue by wildergd** [aws-amplify/amplify-cli#3489]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

i am having this issue... i am using "amplify add auth", i am changing two things:
- required attributes where i am setting none.. 
- oauth flow where i am setting implicit grant
when i do amplify push it fails with the following error. it only happens when i use auth... 

Following resources failed
✖ An error occurred when pushing the resources to the cloud
Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by kaustavghosh06** [comment]
@wildergd Which CLI version are you using?

**Comment by kaustavghosh06** [comment]
Also, can you provide us with more information tied to the failure? More Cloudfromation stack trace?

**Comment by kaustavghosh06** [comment]
Closing due to lack of requested information.
