### ISSUE TITLE
Plugin Creation best practices

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#349]
** Which Category is your question related to? **
Plugin creation
** What AWS Services are you utilizing? **
CloudFormation and S3
** Provide additional details e.g. code snippets **
So I looked through the documentation provided [here](https://aws-amplify.github.io/docs/cli/plugins), and it goes through setting up the environment. It would be nice to know what the best practices are for storing the CloudFormation templates and how you would deploy them. I noticed that in some plugins they stage the templates in a S3 bucket then deploy the template.

On top of the best practices what is the common way of doing the staging before pushing and how would I implement the staging into pushing or is the pushing handled by the CLI by default?

**Comment by axptwig** [comment]
i am having this issue too!

**Comment by wizage** [comment]
Discussion happening in #1101
