### ISSUE TITLE
default values for certain fields in @model

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#3491]
**Is your feature request related to a problem? Please describe.**
In @model there are some fields that I would like them to have a default value if none is specified at creation time.

**Describe the solution you'd like**
For both scalar and non-scalar field types it would be good if a default value can be specified in @model

**Describe alternatives you've considered**
An alternative is to do an implementation in lambda or velocity. However, both have cost and maintainability implications

**Comment by secretshardul** [comment]
+1

**Comment by benjeater** [comment]
+1

**Comment by arkllc** [comment]
@nikhname @ammarkarachi @yuth could you please provide an update if we could expect this feature to be released sometime in near future?

**Comment by SwaySway** [comment]
Closing in favor of #5959
