### ISSUE TITLE
aws-exports.js is not created when running amplify init

### ISSUE THREAD

**Issue by bradthurber** [aws-amplify/amplify-cli#35]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
amplify init is supposed to create an aws-exports.js file according to [Getting started instructions](https://aws-amplify.github.io/amplify-js/media/quick_start?platform=react)

I don't see the file

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
1. Open WSL Ubunutu (amplify init is currently broken in native Windows. See #34) 
2. Create a react app
3. In react app directory, run amplify init answering all of the prompts
4. Note that an aws-exports.js file is not created

What is the expected behavior?
aws-exports.js file created

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
Windows 10 with WSL
Amplify 0.1.14

**Comment by kaustavghosh06** [comment]
The aws_exports.js file gets created after your first amplify push command. We will be updating the docs with this.

**Comment by kernelsoe** [comment]
I have same troubles here.

Tried many things. Added categories and pushed.

No 

> aws-export.js

file in src/

and then added hosting and published again.

Nothing happened!

Running on macOS.

Please fix this as soon as possible.

Thanks a lot AWS team!

**Comment by kernelsoe** [comment]
@kaustavghosh06 
Please see the detailed output here.

[](https://github.com/aws-amplify/amplify-cli/issues/94)

**Comment by davej** [comment]
Also seeing this problem with React.

**Comment by kaustavghosh06** [comment]
@strefethen The aws_exports.js contains information regarding the resources you push after you add via `amplify add <category>` which is made available to your frontend code to utilize. After you init, we don't add any category automatically for you and your exports file would literally be an empty file and of no value. 
On a side note, based on the feedback from users we do add an aws_exports.js file (literally an empty file) as a part of our beta build (to support multiple environments and team workflows), which you can install using `npm install -g @aws-amplify/cli@multenv` command.

**Comment by kaustavghosh06** [comment]
@strefethen Also, as a part of our docs [regarding architecture and CLI flow] [https://aws-amplify.github.io/docs/cli/concept?sdk=js], we have mentioned exactly what files get generated as a part of the `amplify init` command. I don't beleive there is any place where we mention about the aws_exports.js getting generated as a part of the `init` command. Please let us know any reference to it and Iwe'll make sure to make that change in the documentation. I've added an additional PR -> https://github.com/aws-amplify/docs/pull/253 to make this more clear.

**Comment by strefethen** [comment]
@kaustavghosh06 thanks for the reply. FWIW, I've done an amplify add auth (which seemed to work) and I'm still not seeing the file created. I'm trying to build an RN app and selected iOS in amplify init.

Btw, the reference is here: https://aws-amplify.github.io/docs/js/react and there is no mention of having to do amplify push before it's created.

> The ./src/aws-exports.js file that’s created has all of the appropriate cloud resources defined for your application. Edit ./src/App.js to include the Amplify library, configurations, and React HOC.

**Comment by kaustavghosh06** [comment]
@strefethen Added a PR for this as well -> https://github.com/aws-amplify/docs/pull/254/files for more clarification.

**Comment by appsols-dev** [comment]
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment]
I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, ed: D:/ or C:/.
I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

**Comment by daniyal-intellicel** [comment]
> I had the same issue. What I was doing wrong was when I was setting my source destination during "amplify init", I was giving this "/src". So this is not the correct path as this means the initial destination of your partition, eg: D:/ or C:/.
> I update the source destination to "src" only and it works, and now I have aws-export.js file in it.

You can update it using "amplify update project"

**Comment by kosaikham** [comment]
I think I found a solution for this because it works for me. check this out:  [Here](https://github.com/aws-amplify/amplify-cli/issues/186#issuecomment-444071716)

**Comment by leesh22** [comment]
I ran `amplify api update` then `amplify push` and that fixed it for me

**Comment by oscar-gallog** [comment]
It's 2020 and this is still happening. When you run amplify init you don't get a aws-exports.js file. AT ALL. Even if you create an API, add auth, and push, nothing happens.

Any idea how to fix this?

**Comment by kaustavghosh06** [comment]
@oscar-gallog Which CLI version are you using? During `amplify init` what are the options that your provide for your frontend project. The location of the `aws-exports.js` file is determined based on the responses to those questions.

**Comment by oscar-gallog** [comment]
Ok, I'm not sure what happened, but I run the command amplify init again and the file was created. Not sure what was the problem. If anyone is having this issue try running again the command.

**Comment by kabagema** [comment]
A solution i found 

- Delete the amplify folder 
- update or add awsmobile 
- amplify init
and the aws-export.js was created
