### ISSUE TITLE
API Add GraphQL can not query attributes by @auth

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#350]
**Describe the bug**
Amplify API Add GraphQL with @auth schema, query those custom attributes using AppSync console returns error.

**To Reproduce**
1. Create a new Amplify project with amplify init
2. amplify add api and select GraphQL
3. Setup API with Cognito User Pool authoriser
4. Use the following schema:

type Note 
    @model 
    @auth(rules: [{allow: owner, ownerField: "user"}])    
    {
  id: ID!
  content: String
}

5. amplify push
6. Go to AppSync console > Query. Login Cognito user.
7. Create a note with createNote mutation. The query result is OK:
{
  "data": {
    "createNote": {
      "id": "e514d430-7946-4dce-9eda-d42a20caa4af",
      "content": "Hello World Note 1"
    }
  }
}
8. Check DynamoDB, a record is created with fields id, content, user, createdAt, updatedAt
9. Run the query:
query ListNotes {
  listNotes {
    items {
      id
      content
      user
    }
  }
}
10. Get back the following error:
{
  "data": null,
  "errors": [
    {
      "path": null,
      "locations": [
        {
          "line": 13,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Validation error of type FieldUndefined: Field 'user' in type 'Note' is undefined @ 'listNotes/items/user'"
    }
  ]
}

**Expected behavior**
The resulted schema by Amplify CLI does not list those fields (user, createdAt, updatedAt) inserted by resolvers. 

**Additional context**
amplify --version
0.1.29

**Comment by mikeparisstuff** [comment]
This is because you are not adding the `user: String` field to your Note type. Change your Note type to this and it will work as expected.

```graphql
type Note
@model
@auth(rules: [{allow: owner, ownerField: "user"}])
{
  id: ID!
  content: String
  user: String
}
```
