### ISSUE TITLE
Backend (API) -  v1 - v2

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#3502]
I have now changed my backend. 
In the current version (production) there is a lambda that is called after the registration, which then creates a profile at DynamoDB. 

In the new version of the app, I don't need this anymore. Accordingly I have also deleted the Lambda function under (develop). 

If I now deploy the backend, but the users are still working with the current frontend app, then they cannot register. 

How do you do that? I cannot create a new env for the new frontend. Because I would lose users and data. 
Is there a possibility?

**Comment by SwaySway** [comment]
Hello @davidbiller 
What is your current workflow for deploying changes?
Are you using Amplify Console?

**Comment by davidbiller** [comment]
@SwaySway 
Yes I am using the cli.

At the moment I am pushing the new Frontend code for the new Api functions with expo code push in the same moment when I am pushing the backend. 

This time, I am working with a new sdk of expo. So I cant use codePush.

**Comment by attilah** [comment]
@davidbiller what exactly has changed in the registration why users cannot register? Are you sending any information from the client app (like app version) which would enable you to act differently during registration in some Cognito triggers? Is the new app calling a different endpoint? There are a lot to this problem that is specific to you use case and not related to the CLI itself. Please send some details and I try to help.

**Comment by attilah** [comment]
Closing due to lack or response, feel free to reopen it if needed.
