### ISSUE TITLE
How to add existing amplify back end to the amplify front end? 

### ISSUE THREAD

**Issue by yvescoinpass** [aws-amplify/amplify-cli#3505]
** Which Category is your question related to? **
Auth, Storage, API

** What AWS Services are you utilizing? **
Cognito, AWS AppSync,

** Provide additional details e.g. code snippets **
I accidentally deleted my amplify frontend and I created a new one. How do I add again the existing amplify back end to the newly created amplify app? 

I followed the steps on the backend tab 

1. `amplify init --appId ("ID OF YOUR NEW AMPLIFY APP")`.

2. Instead of `amplify add CATEGORY HERE`. I use `amplify update CATEGORY HERE`

Then `amplify push`

But when I check the amplify app on the AWS console there still no backend integrated to it.

Am I doing correct?

`aws-amplify": "^2.1.0`
`@aws-amplify/cli@4.13.4`

**Comment by nikhname** [comment]
@yvescoinpass which version of the CLI are you using?

**Comment by yvescoinpass** [comment]
Hello @nikhname, thanks for the time responding to my question. I am using `@aws-amplify/cli@4.13.4`

**Comment by UnleashedMind** [comment]
Try to follow these steps to first recover, and then add a new backend Env if you want to.

1. `amplify pull --appId <your-project-appId> --envName <your-existing-backend-env>`
2. `amplify init` and select the existing backend env if prompted

Now your amplify folder structure is fully setup, they you can add new backend env by 

`amplify env add`

**Comment by yvescoinpass** [comment]
I got an error while trying to input my the name of the env 

`Cannot find backend environment master in Amplify Console app`

I am really sure that the name of the env was master. I think the env was deleted too when I accedentally deleted the amplify app?

**Comment by yvescoinpass** [comment]
I think the issue was I deleted my the whole amplify project on AWS Console but I still have the existing amplify code base on my github repo. 

So what I did was

1. Created a new amplify project on aws console. 
2. Connect the existing repository on github
3. On my local machine I `git pull` the repo.
4. `amplify init --appId ("ID OF YOUR NEW AMPLIFY APP")`.
5. Then. I use `amplify update CATEGORY HERE`
6. Then amplify push 

That's it then the back-end is working again but it is not just showing on Aws Amplify Console Backend Environments tab tab

**Comment by FemkeBuijs** [comment]
Same here, when adding an extra environment (add env) it shows up in the backend tab of the console, but the already existing environments are not showing.

**Comment by UnleashedMind** [comment]
Recovering the deleted Amplify Console project is not in the Amplify CLI's normal workflow. 
But there's the following hack that triggers the CLI post push check that you can try: 

1. On your local amplify project, run `amplify env checkout <the-missing-endName-on-Console>` 
2. open the `amplify-meta.json` files in both the `backend` and `#current-cloud-backend` folder, make sure the `providers.awscloudformation` does not contain the field `AmplifyAppId", remove it if it's there.
3. open the `team-provider-info.json` file, make sure the  '<env>.awscloudformation`  does not contain the field `AmplifyAppId", remove it if it's there.
4. make an tiny dummy change in the backend, such as adding a space in in the template file of `amplify/backend/storage` 
5. run `amplify push`

**Comment by FemkeBuijs** [comment]
Works like a charm @UnleashedMind, thanks!!

**Comment by miguel258** [comment]
its incredible have so many problems deploying a aws amplify app, and manage more than one env accross different aws accounts...
