### ISSUE TITLE
aws_user_files_s3_bucket in aws-exports doesn't match bucket name in storage mock server

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3510]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When using Storage.list API to list files under a path, it uses the wrong bucket in the S3 mock server. For example,  
request: http://localhost:20005/bucketname221137-dev/?prefix=public
response: 
```
<?xml version="1.0" encoding="utf-8"?>
<ListBucketResult>
  <Name>bucketname-dev</Name>
  <Prefix>public/</Prefix>
  <KeyCount>0</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <Delimiter></Delimiter>
  <IsTruncated>false</IsTruncated>
</ListBucketResult>
```

In the request, the bucket name is bucketname221137-dev, but the server failed to find any files because the mock bucket name, bucketname-dev, doesn't match. The bucket name used by Storage.list comes from aws-exports.js. It includes the stack id, but the mock server creates a bucket without the stack id

**Amplify CLI Version**
4.12.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
1. create a storage with Amplify Cli
2. upload a file with Storage.put
3. list the uploaded file with storage.list

**Expected behavior**
storage.list should return the uploaded file

**Screenshots**

**Desktop (please complete the following information):**
Mac
Node: v8.11.1

**Additional context**
Here is the root cause 
Line 34 of amplify-cli/packages/amplify-util-mock/src/storage/storage.ts
this.bucketName = `${storageParams.bucketName}-${localEnvInfo.envName}`;
the bucket name in mock server is the name followed by environment name, however in the frontend the bucket name is assembled with stack id as below. 
```
"BucketName": {
                    "Fn::If": [
                        "ShouldNotCreateEnvResources",
                        {
                            "Ref": "bucketName"
                        },
                        {
                            "Fn::Join": [
                                "",
                                [
                                    {
                                        "Ref": "bucketName"
                                    },
                                    {
                                      "Fn::Select": [
                                          3,
                                          {
                                              "Fn::Split": [
                                                  "-",
                                                  {
                                                      "Ref": "AWS::StackName"
                                                  }
                                              ]
                                          }
                                      ]
                                    },
                                    "-",
                                    {
                                        "Ref": "env"
                                    }
                                ]
                            ]
                        }
                    ]
                },
```

I would suggest to not include stack id and environment in mock mode. Simply use the bucketName in the storage parameter file because currently there is no way to dynamically pass the bucket name to function and we have to hard code the bucket name in function-parameters.js. If the bucket name has environment name, every developer has to use their own bucket name. If the environment name has to be kept, please make sure the bucket name can be passed to functions dynamically

**Comment by nikhname** [comment]
@gaochenyue could you provide your aws-exports file, or send a zip file of your amplify folder to amplify-cli@amazon.com? You could also try deleting your aws-exports file and running amplify mock storage again.

**Comment by nikhname** [comment]
Could you also provide the code you used to do a Storage.put and Storage.list?

**Comment by gaochenyue** [comment]
@nikhname Thanks. I tried many times to recreate aws-exports file but the bucket name always include stack id. I will send you the code soon.

**Comment by gaochenyue** [comment]
Hi @nikhname, I changed the title of this issue to make it more generalized

Here is the aws-exports.js before starting mock

{
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fad2345f-6daf-45af-b734-******************",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_******************",
    "aws_user_pools_web_client_id": "******************",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://******************.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "bucketname221137-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};

Here is the aws-exports.js after starting mock
{
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fad2345f-6daf-45af-b734-******************",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_******************",
    "aws_user_pools_web_client_id": "******************",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://10.63.198.58:20002/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_user_files_s3_bucket": "bucketname221137-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_user_files_s3_dangerously_connect_to_http_endpoint_for_testing": true
};

The appsync endpoint is successfully converted to the mock server, but the S3 bucket name stays the same. This bucket name matches the one in the cloud, but the S3 mock server uses the bucket name without the stack id (bucketname-dev).

**Comment by gaochenyue** [comment]
@nikhname Here is the root cause
https://github.com/aws-amplify/amplify-cli/blob/b25cfd00b21416a82ecefda1f6498206ef71531b/packages/amplify-util-mock/src/storage/storage.ts#L153-L157
On line 156 should be placed before line 55 and 54, otherwise it overrides whatever before

**Comment by akshbhu** [comment]
@gaochenyue Thanks for pointing that out but the code above only generates aws_exports file. 
and S3 local server also uses bucketname with stack ID.
Regarding your problem , Can you show me your Storage.list api call. In the mean time You can try to delete the old awsexports file and again running amplify mock storage

**Comment by gaochenyue** [comment]
Thanks @akshbhu, my code of storage.list is trial, not sure if it helps, but here it is anyway
`
path = owner.instance + '/ff/' + moment(owner.createdAt).valueOf();
Storage.list(path, {
        'public',
    });
`
I tried many times to recreate the aws_exports file, but always got the same issue. It copies whatever in the storage output of amplify-meta.json.
My observation is that the local S3 server doesn't include stack id in the bucket name. It reference the bucketName in parameters.json of storage and is followed by the env name. The code snippet above clearly shows this naming pattern.

**Comment by akshbhu** [comment]
@gaochenyue  Can you send a zip file of your amplify folder to amplify-cli@amazon.com?

**Comment by gaochenyue** [comment]
@akshbhu @nikhname I have sent you the project in a zip file

**Comment by gaochenyue** [comment]
@akshbhu this issue can be reproduced quickly
1. create a sample Amplify project
2. amplify add storage
3. amplify push 
4. amplify mock

Open browser, visit http://localhost:20005/{bucketname}{stackId}-{env}. it returns 
NoSuchKey The specified key does not exist. {bucketname}{stackId}-{env}
visit  http://localhost:20005/{bucketname}-{env}. it returns
<ListBucketResult>
<Name>{bucketname}-{env}</Name>
<Prefix/>
<KeyCount>0</KeyCount>
<MaxKeys>1000</MaxKeys>
<Delimiter/>
<IsTruncated>false</IsTruncated>
</ListBucketResult>
