### ISSUE TITLE
Data aggregation with datastore

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3518]
** Which Category is your question related to? **
Datastore
** What AWS Services are you utilizing? **
Cognito, AWS AppSync, Dynamodb
** Provide additional details e.g. code snippets **
I store transactions on dynamodb with amplify and appsync. 
After every transaction I just want to create total sold productwise.
Transaction example is 
Product A sold 3 qty
Product B sold 10 qty
Product A sold 5qty
Product B sold 4 qty
I want to create total per month
Feb 2020 Product A sold 8qty
Feb 2020 Product B sold 14qty

Currently I do this with dynamodb streams and lambda. But how can I do this with Datastore predicate. 
I should emphasize that **most transactions added (to dynamodb/appsync) are done offline**

**Comment by apoorvmote** [comment]
@undefobj I deleted my comment by mistake but thank god you have read and responded already.
Also the PR you mentioned #2463  is merged like 5 hours ago. So it should be coming to cli in next couple of days. Its much easier than manually attaching and maintaining the lambda trigger.

**Comment by SebSchwartz** [comment]
> write back to the table by doing a mutation against the AppSync API (**don't write direct to DynamoDB otherwise the delta sync and versioning wouldn't work**). 

@undefobj It would be great to put this in the amplify doc. 
How would you suggest we import lots of data inside a table quickly? For some users of our app, we have a csv that we need to import inside dynamo table for their account. So we already have a lambda to read this csv and put inside dynamo via PutItem but if I want the delta sync to work (or if they could receive the data later on when they refresh their jwt token could be ok too), what do you suggest?

Thanks in advance ;)

**Comment by undefobj** [comment]
What is "lots of data"? If it's just a few hundred records or less it's probably just easier to do a GraphQL mutation with a for-loop just like any client. If it's thousands of records I'd probably recommend writing to the base table but *not* putting any version value, that way the sync processor could pick it up at the next base query client catchup period.

**Comment by undefobj** [comment]
> @undefobj I deleted my comment by mistake but thank god you have read and responded already.
> Also the PR you mentioned #2463 is merged like 5 hours ago. So it should be coming to cli in next couple of days. Its much easier than manually attaching and maintaining the lambda trigger.

Yes we just merged and are working on docs and publishing process.

**Comment by SebSchwartz** [comment]
> What is "lots of data"? If it's just a few hundred records or less it's probably just easier to do a GraphQL mutation with a for-loop just like any client. If it's thousands of records I'd probably recommend writing to the base table but _not_ putting any version value, that way the sync processor could pick it up at the next base query client catchup period.

Ok so if I don t put _version in my item, it will be sync later on to the client. Do I need to put updatedAt value?
Thanks for your answer

**Comment by apoorvmote** [comment]
@undefobj couple of quick questions about datastore.

This is very big one.

Can datastore replace redux? (I am using it with react). I am thinking of eliminating redux.

And can I eliminate custom @key based on my access pattern? Why bother adding keys(other than relationships of course) because I can add predicates locally?

**Comment by SebSchwartz** [comment]
> @undefobj couple of quick questions about datastore.
> 
> This is very big one.
> 
> Can datastore replace redux? (As far as fetching graphql data with react is concerned). I am thinking of eliminating redux.
> 
Yes it can, we don't have redux at all.
> And can I eliminate custom @key based on my access pattern? Why bother adding keys(other than relationships of course) because I can add predicates locally?
> 
It depends if you want to query dynamo with those key. GrapQL will generate you some query like entityByCustomKey.
> Does amplify support offline uploading of images to s3? Via datastore or any other method? If not then will it support in future?

I think there are nothing out of the box for this, maybe you could try with the Storage category but i don't think it handles it.

**Comment by apoorvmote** [comment]
> Yes it can, we don't have redux at all.

Really great to hear that

> > And can I eliminate custom @key based on my access pattern? Why bother adding keys(other than relationships of course) because I can add predicates locally?
> 
> It depends if you want to query dynamo with those key. GrapQL will generate you some query like entityByCustomKey.

If I am making graphql query & not use datastore then its not for specific key. The power of graphql is fetching everything. e.g. specific blog, all of its blog posts & all comments for each individual posts. That is lacking in datastore.

And major use case for key is to fetch records by date. I need top whatever records from before today and latest. Not before today but older records like 3 months ago.  In your experience does datastore fails to show records. 

I am trying to understand in which scenario do you need to use custom key that datastore cannot do.

**Comment by undefobj** [comment]
We recently launched the functionality discussed above for using Lambda triggers from an `@model` type. Documentation can be found here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation

Please let us know if you have any trouble with this.

**Comment by lenarmazitov** [comment]
> > What is "lots of data"? If it's just a few hundred records or less it's probably just easier to do a GraphQL mutation with a for-loop just like any client. If it's thousands of records I'd probably recommend writing to the base table but _not_ putting any version value, that way the sync processor could pick it up at the next base query client catchup period.
> 
> @undefobj Ok so if I don t put _version in my item, it will be sync later on to the client? Do I still need to put updatedAt and _lastChangedAt value in my PutItem or nothing except __typename, id and fields?
> Thanks for your answer

Hi @SebSchwartz did you found out answer to your question?
