### ISSUE TITLE
Running amplify configure ignores AWS CLI credentials

### ISSUE THREAD

**Issue by ryudice** [aws-amplify/amplify-cli#3521]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Running amplify configure takes me to the AWS console eventhough I have an AWS CLI profile set

**Amplify CLI Version**
4.13.4

**To Reproduce**
Run `amplify configure` with AWS CLI credentials file set

**Expected behavior**
Should use existing AWS CLI credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/125211/75359327-df5e2e80-5879-11ea-96b9-fceb652fa89e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Node Version v12.16.1

**Additional context**

**Comment by SwaySway** [comment]
@ryudice Are you configuring the CLI for the first time or are you running this command on an existing amplify project?

**Comment by kaustavghosh06** [comment]
If you already have an AWS Profile set already, then you don't need to go through the amplify configure step. You can select your already set profile when going through the `amplify init` flow. `amplify configure` is for customers who do not have any profile set.

**Comment by ryudice** [comment]
`amplify init` doesnt pickup my credentials either:

![image](https://user-images.githubusercontent.com/125211/75459336-d8502280-5944-11ea-84e9-c6408f114dcd.png)

**Comment by ryudice** [comment]
> @ryudice Are you configuring the CLI for the first time or are you running this command on an existing amplify project?

@SwaySway I'm running it for the first time on a gatsby project.

**Comment by UnleashedMind** [comment]
@ryudice 
How did you set the profile on your computer? 
It should be in these two files:
 `<home-dir>/.aws/credentials` and `<home-dir>/.aws/config`

Here's the documentation on how it should be setup
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

The `amplify configure` command is a convenience tool to help you to set up a profile in those files. 
Seems like you should following through the `amplify configure` steps and get the profile correctly setup.

**Comment by ryudice** [comment]
@UnleashedMind 
I have the profile configure in ~/.aws/credentials. I have the AWS_PROFILE environment variable set, so I was expecting the amplify CLI to use the profile set through the AWS_PROFILE environment variable just like the aws CLI does, is this not the expected behavior?

**Comment by UnleashedMind** [comment]
No, the amplify CLI does not use the AWS_PROFILE environment variable. 
From what I see in your screen shot, I don't think the Amplify CLI recognizes your profile settings.

**Comment by UnleashedMind** [comment]
closing the issue, feel free to open another one if needed.
