### ISSUE TITLE
Cannot initialize my amplify project anymore after creating and pushing a symbolic link in lambda function

### ISSUE THREAD

**Issue by daajack** [aws-amplify/amplify-cli#3522]
**Describe the bug**
Hi,
I cannot initialize my environnment anymore, after pushing a symbolic link, the pushed was ok, but after pushing a second time, it ended with an error "Error: EEXIST: file already exists, symlink '../../../../../src/graphql' -> '/web/amplify/.temp/#current-cloud-backend/function/importPI/src/graphql"
I cannot pull, status or anything on my repo.

I tried from a clean cloned directory, and i have the same error, i also tried to recreate the link, in both backend and #current-cloud-backend.

It seems that my last push corrupted my amplify repo.
Should I edit it in S3 or something like that ?

Thanks for your help.

**To Reproduce**
amplify init --appId <key>

**Expected behavior**
Initialize without error

<details>
  <summary><strong>Environment</strong></summary>
  System:
    OS: Linux 4.15 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 465.46 MB / 3.85 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  npmPackages:
    @material-ui/core: ^4.0.0-rc.0 => 4.9.3
    aws-amplify: ^1.1.28 => 1.3.3
    aws-amplify-react: ^2.3.8 => 2.6.3
    bootstrap: ^4.3.1 => 4.4.1
    node-sass: ^4.6.0 => 4.13.1
    npm-run-all: ^4.1.5 => 4.1.5
    ra-cognito: ^1.0.4 => 1.0.4
    ra-data-simple-rest: ^2.9.2 => 2.9.9
    ramda: ^0.26.1 => 0.26.1
    react: ^16.12.0 => 16.12.0
    react-dom: ^16.12.0 => 16.12.0
    react-dropzone-uploader: ^2.11.0 => 2.11.0
    react-geosuggest: ^2.12.0 => 2.12.1
    react-html5-camera-photo: ^1.5.4 => 1.5.4
    react-pager: ^1.3.3 => 1.3.3
    react-router-dom: ^5.1.2 => 5.1.2
    react-scripts: 3.0.1 => 3.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.13.4
    npm: 6.13.6

</details>

**Additional context**
root@f7627e0b8be2:/web# amplify init --appId <key>
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
✖ There was an error initializing your environment.
init failed
Error: ENOENT: no such file or directory, stat '/web/amplify/.temp/#current-cloud-backend/function/importPI/src/graphql'

**Comment by kaustavghosh06** [comment]
@daajack I think your issue is tied to the fix provided out here - https://github.com/aws-amplify/amplify-cli/pull/3406
Please take a look at the workaround provided by @RossWilliams in the PR

**Comment by daajack** [comment]
Hi thanks for your quick answer, but i'm sorry i cannot find the workaround you're talking about. The patch is not yet published right ? should i do something with cloudformation template ? I did not found any build directory, in initialized repo or new cloned one.

Another question, I pushed a new commit to my repo where i replace my symlink with a directory, should i reset it to symlink state before removing the symlink again ?

I'm sorry, but i cannot see where is the problem actually, in my git repo, s3 host, cloudformation or elsewhere.

**Comment by daajack** [comment]
I should add that trace, coming on first init :


init failed
Error: ENOENT: no such file or directory, stat '/web/amplify/.temp/#current-cloud-backend/function/importPI/src/graphql'
    at Object.statSync (fs.js:948:3)
    at Object.statSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/util/stat.js:90:33)
    at copyDirItem (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:119:29)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at mkDirAndCopy (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
    at onDir (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/web/amplify/.temp/#current-cloud-backend/function/importPI/src/graphql'
}

**Comment by RossWilliams** [comment]
Sorry I don’t think this is related to my PR linked above, maybe it’s another PR you are thinking of?

**Comment by daajack** [comment]
I cannot find anything.
I think i did a really bad symlink connected to src, that was stupid. And the symlink has been added somewhere where it is invalid. Sadly the push didnt see anything and pushed all this with success. :/ I think my best solutions is to go to s3 where the backend is stored and find a file with that symlink, edit it, remove it and re-upload the file.

**Comment by SwaySway** [comment]
@daajack What version of the CLI are you using?

**Comment by daajack** [comment]
@aws-amplify/cli: 4.13.4

**Comment by daajack** [comment]
> 
> 
> @daajack What version of the CLI are you using?

@aws-amplify/cli: 4.13.4

**Comment by daajack** [comment]
I finally fixed my bug by removing the symlink from the #current-cloud-backend.zip in my S3 bucket.
Should i close the bug ?

**Comment by ShepelievD** [comment]
@daajack may u please help me resolve the issue? Have the same situation

**Comment by daajack** [comment]
Hi, maybe you re-zipped wrongly your  #current-cloud-backend.zip, with a sub-repository in it.

**Comment by ShepelievD** [comment]
@daajack thanks for the response. You were right, I re-zipped it wrong. Thanks 🙏
