### ISSUE TITLE
Unable to add @key to an existing model

### ISSUE THREAD

**Issue by alvincrespo** [aws-amplify/amplify-cli#3523]
Hey, Amplify team!

I was hoping to get some assistance around adding sorting to an existing app. I was trying to add the `createdAt` to the `@key` directive, according to this [stackoverflow answer](https://stackoverflow.com/a/56497643/2587695).

When adding `@key` to an existing type model - I get an error when trying to run `aws publish`. 

Any help would be fantastic.

Thanks for this awesome tool, loving it so far!

**Which Category is your question related to?**

API

**Amplify CLI Version** 

```
➜  amplify -v
4.13.4
```

**What AWS Services are you utilizing?**

| Category | Resource name            | Operation | Provider plugin   |
| -------- | ------------------------ | --------- | ----------------- |
| Api      | XXXXXXXXXXXXXXXX         | Update    | awscloudformation |
| Auth     | XXXXXXXXXXXXXXXX         | No Change | awscloudformation |
| Hosting  | XXXXXXXXXXXXXXXX         | No Change | awscloudformation |
| Storage  | XXXXXXXXXXXXXXXX         | No Change | awscloudformation |

**Provide additional details e.g. code snippets**

**Error**

```
✖ An error occurred when pushing the resources to the cloud

Attempting to edit the key schema of the ImageTable table in the Image stack.
An error occured during the push operation: Attempting to edit the key schema of the ImageTable table in the Image stack.
```

**Updated Schema**

```
// amplify/backend/api/chainappterparty/schema.graphql
type Image @model @key(fields: ["createdAt"]) {
  id: ID!
  long: String!
  lat: String!
  image: String!
  createdAt: String!
}
```

**Original Schema**

```
type Image @model {
  id: ID!
  long: String!
  lat: String!
  image: String!
}
```

**Comment by kaustavghosh06** [comment]
@kesteinbakk You're right - the primary index of a DDB table cannot be changed once the table is provisioned. Thw workaround would be a two step process:
1. Remove the model (if you're fine with loosing the data stored in DDB)
2. Add the model back with the desired @key attributes

**Comment by arealmaas** [comment]
@kaustavghosh06 Thanks, but that failed for me as well. Getting an error that the stack already contains an export of the table name. I actually need to delete the stacks entirely, or make a new name for the table... Did you actually have any luck with this?
