### ISSUE TITLE
amplify-cli doesn't read role_arn, source_profile from ~/.aws/credentials unlike awscli

### ISSUE THREAD

**Issue by hirochachacha** [aws-amplify/amplify-cli#3528]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
I put `role_arn` and `source_profile` settings on `~/.aws/credentials`.
After several hours of investigation, it turned out that `amplify-cli` only accepts these setting from `~/.aws/config`.

**Describe the solution you'd like**
It seems `awscli` accepts putting any config on `~/.aws/credentials`.
I expect the same behavior here.

**Describe alternatives you've considered**
Printing error message like `"~/.aws/credentials cannot include role_arn, use ~/.aws/config instead"`.

**Additional context**

**Comment by SwaySway** [comment]
Hello @hirochachacha this is supported in the CLI.

View the docs on that here: https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-roles--mfa

**Comment by hirochachacha** [comment]
@SwaySway Thank you for your reply. Yes I know `role_arn` is supported on `amplify-cli`. 

https://github.com/aws-amplify/amplify-cli/blob/dcc811a7df3bf86095c8eba712d5e4a2ce7dc83b/packages/amplify-provider-awscloudformation/lib/system-config-manager.js#L64-L69

But I said it doesn't support the same way as `awscli`. `awscli` allow us to write `role_arn` on `~/.aws/credentials` while `amplify-cli` don't. That confused me a lot because we usually tended to think `awscli` is standard tool, so I expected `amplify-cli` has the same behavior. Even if putting `role_arn` on `~/.aws/credentials` is bad practice and `awscli` is too permissive, I'd like to get some warning at least.
