### ISSUE TITLE
add --disable-rollback option for push command

### ISSUE THREAD

**Issue by hirochachacha** [aws-amplify/amplify-cli#3529]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
Current policy always incur rollback even if it's unwanted.
In current project, I need to wait 20-30 mins for pushing resources from scratch.
Sometimes, amplify command fails, then I have to wait extra 20-30 mins for rollback which I don't want to.

**Describe the solution you'd like**
I guess adding a command option for enabling [DisableRollback](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#createStack-property) is good enough.

**Describe alternatives you've considered**

**Additional context**

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.
