### ISSUE TITLE
Unable to query as both Authenticated and Unauthenticated user

### ISSUE THREAD

**Issue by jasontripleps** [aws-amplify/amplify-cli#3532]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

AppSync GraphQL Api

**Amplify CLI Version** 

4.12.0

**What AWS Services are you utilizing?**

AppSync, Cognito, Lambda

**Provide additional details e.g. code snippets**

I have a basic Query that pulls data from a Lambda function. Code snippet below:

```graphql
type Query {
  getTests: [Test] @function(name: "myapi-${env}")
}


type Test {
  id: Int
  name: String
}
```

I want this API to be available whether the user is logged into the App (via cognito) or not. So no auth controls around this.

Using cognito auth, it works when the user is logged in, but not when they are not (despite cognito having allow unauthenticated users checked in the identity pool). Using IAM, it works when the user is not logged in, but not when they are.

I've tried adding `@aws_cognito_user_pools` and/or `@aws_iam` to the function Query, but nothing seems to work.

I don't know if this is a bug, or if i'm doing something wrong, but any help would be appreciated

**Comment by jasontripleps** [comment]
I should also point out that I'm just calling this through the Amplify JS codegen for Angular.

**Comment by SwaySway** [comment]
Hello @jasontripleps if you add `@aws_iam` a policy that allows access to the operation and the type is also needed. One way you can add access to the type and the operation would be like the following
```graphql
type Query @aws_cognito_user_pools {
  getTests: [Test] @function(name: "myapi-${env}") @auth(rules: [{allow: public, provider: iam} ])
}

type Test @aws_cognito_user_pools {
  id: Int @auth(rules: [{allow: public, provider: iam} ])
  name: String @auth(rules: [{allow: public, provider: iam} ])
}
```

`@auth` will generate the iam policy to access the type and the operation.

**Comment by jasontripleps** [comment]
@SwaySway Thanks a lot. I'll try that now! I assume in this case I should have cognito as the default authentication of the API?

**Comment by jasontripleps** [comment]
My problem now is that I'm getting a Template may not exceed 460800 bytes in size. error.

Looking like it's because it's making an IAM policy for every field. Is there any way around this?

**Comment by jasontripleps** [comment]
Have tried just doing a single function to bring the number of IAM policies down (just to test it) and I'm getting  `No data source found named NONE (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID:<SOME_CODE>)`

I do also have nested types, if that makes a difference?

For example

```
type Query @aws_cognito_user_pools {
  getTests: [Test] @function(name: "myapi-${env}") @auth(rules: [{allow: public, provider: iam} ])
}

type Test @aws_cognito_user_pools {
  id: Int @auth(rules: [{allow: public, provider: iam} ])
  name: String @auth(rules: [{allow: public, provider: iam} ])
  test2: Test2 @auth(rules: [{allow: public, provider: iam} ])
}

type Test2 @aws_cognito_user_pools {
  id: Int @auth(rules: [{allow: public, provider: iam} ])
  name: String @auth(rules: [{allow: public, provider: iam} ])
}
```

**Comment by attilah** [comment]
Closing in favor of #27611 as it seems like the duplicate.
