### ISSUE TITLE
auth permission

### ISSUE THREAD

**Issue by mightiesthero** [aws-amplify/amplify-cli#3535]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
permission with iam provider work different from amazon cognito provider

with amazon cognito provider if read operation not provided, user with no group can read model 
but with iam provider i cannot read

if i add operations read with iam provider, then user with iam authentication can read 
but user with no group or user with group with no read operation cannot read

**Amplify CLI Version**
4.13.1

**To Reproduce**
Create schema like this

```graphql
type ProductCategory
  @model
  @auth(
    rules: [
      # admin
      { allow: groups, groups: ["admin"], operations: [create, update, delete] }
      # iam for lambda
      { allow: private, provider: iam, operations: [create, update, delete] }
    ]
  ) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime

  name: String!
  description: String
}
```

**Expected behavior**
graphql using iam permission can read listProductCategorys (same permission with if provider amazon cognito)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. 13.5.0

**Additional context**

**Comment by SwaySway** [comment]
Hello @mightiesthero rules for the iam as an auth provider are different that userPools. The operations you wish to allow for IAM must be specified so the policy for read can be added to the authorized role.

View `@auth` on combing auth rules here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#combining-authorization-rules

**Comment by mightiesthero** [comment]
Thank you for the response @SwaySway 

but if i can the schema into this

```
type ProductCategory
  @model
  @auth(
    rules: [
      # admin
      { allow: groups, groups: ["admin"], operations: [create, update, delete] }
      # iam for lambda
      { allow: private, provider: iam, operations: [read ,create, update, delete] }
    ]
  ) {
  id: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime

  name: String!
  description: String
}
```

user with admin group or user with no group cannot read this model.
do you have a solution for this?
