### ISSUE TITLE
How to change the createdAt time format ?

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#3545]
Hi,

I would like to change the time format of createdAt like this :
```
$util.qr($context.args.input.put("createdAt", $util.defaultIfNull($ctx.args.input.createdAt, **Date.now().toString()**)))
```
But when I do "amplify push", nothing new is detected.

How to fix it or is it a way to sort createdAt initial format ?

**Comment by SwaySway** [comment]
Hello @rudyhadoux if you are referring to having a custom resolver please view the docs here on custom resolvers: https://aws-amplify.github.io/docs/cli-toolchain/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

If you run into any issues related to this please comment below

**Comment by rudyhadoux** [comment]
Ok thanks.
