### ISSUE TITLE
Deployment of Lambda function that processes a DynamoDb stream

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#3552]
We want to add a lambda function that processes a dynamodb stream in our amplify app.
We are able to achieve it by adding the following policy to lambdaexecutionpolicy in the function's cloudformation template
```
{
    "Effect": "Allow",
	"Action": [
		"dynamodb:GetRecords",
		"dynamodb:GetShardIterator",
		"dynamodb:DescribeStream",
		"dynamodb:ListStreams"
	],
	"Resource": [
		"arn:aws:dynamodb:<region>:<accountnum>:table/<tablename>/stream/<timestamp>"
	]
}

```	
and by adding following EventSourceMapping to the function's cloudformation template.

```
"ATableTrigger": {
	"Type": "AWS::Lambda::EventSourceMapping",
	"DependsOn": [
		"LambdaExecutionRole",
		"lambdaexecutionpolicy"
	],
	"Properties": {
		"BatchSize": 10,
		"Enabled": true,
		"EventSourceArn": "arn:aws:dynamodb:<region>:<accountnum>:table/<tablename>/stream/<timestamp>",
		"FunctionName": {
			"Fn::GetAtt": [
				"LambdaFunction",
				"Arn"
			]
		},
		"StartingPosition": "LATEST"
	}
}

```

The issue is we have to hard-code the arn of the stream inside this cloudformation template.
Is there any way to obtain this stream arn from cloudformation stack or supplying to amplify push via some sort of environment settings?

**Comment by onhate** [comment]
like you do GetAtt for the function you could do it for the Table, no?

```
"Fn::GetAtt": [
    "TableName",
    "Arn"
]
```

**Comment by kaustavghosh06** [comment]
@blairtaylor Is this table managed or created by the Amplify CLI?

**Comment by blairtaylor** [comment]
Created via the Amplify CLI.

**Comment by blairtaylor** [comment]
The solution suggested by @onhate works. We'll close the issue. Thanks.
