### ISSUE TITLE
Lambda custom resolver returning @model should fill fields

### ISSUE THREAD

**Issue by elgutierrez** [aws-amplify/amplify-cli#3556]
**Which Category is your question related to?**
AppSync, GraphQL, Lambda

**Amplify CLI Version** 
4.13.2

**What AWS Services are you utilizing?**
AppSync, Lambda

**Provide additional details e.g. code snippets**
I have the following GraphQL model: 
```
type Doc @model {
  id: ID!
  ... other props
}

type Event @model {
  id: ID!
  ... other props
  author: User @connection
  replies: [Reply] @connection(name: "EventReplies", sortField: "createdAt")
}

type Mutation {
  setDocProps(docId: ID!, props: AWSJSON): DocProps @function(name: "doclistsSetDocProps-${env}")
} 

type DocProps {
  doc: Doc
  events: [Event]
}
```
The mutation `setDocProps` is resolved by a Lambda function that does some operations, modify some fields on `Doc` and create some `Events` depending on the modified props. This function returns the modified `Doc` entity and the created `Event`s. 

```
const doc = await updateDoc(docId, props)
const events = await createEvents(doc, props)
return {
   doc,
   events
}
```
The issue is that many fields are returned `null` when I call `setDocProps` from the frontend, even though they are returned from the resolver. Is there a way to force AppSync to populate those fields?

**Comment by attilah** [comment]
@elgutierrez when it comes to customer resolver, then it is the customer resolver's responsibility to resolve fields, `@model` is not connected in any way. To isolate the problem I'd suggest to see what the Lambda returns. I don't know if you've any `@auth` rules defined which could filter out certain fields from the result? Another way to troubleshoot is to test the mutation from the AppSync console itself if you see correct results there or not.

**Comment by kaustavghosh06** [comment]
@elgutierrez Closing this based on @attilah's response. Let us know if you're still stuck on this issue.
