### ISSUE TITLE
Amplify init without remote stack check

### ISSUE THREAD

**Issue by artyom-melnikov** [aws-amplify/amplify-cli#3557]
Hi! I'm using only two functions from Amplify, which are `amplify api gql-compile` and `amplify codegen`. I'm doing all deployment through aws cdk

I wonder if I can do headless amplify init without validating the existing stack?

```
- Initializing your environment: default
× There was an error initializing your environment.
init failed
Error [ValidationError]: Stack with id amplify-xxxxxx-153820 does not exist
```

Or can i invoke those  two apis without `amplify init`?

Thanks!

**Comment by SwaySway** [comment]
@artyom-melnikov What is your current configuration like with CDK?
If you are running `amplify init` on an existing amplify project it will generate the necessary config files.

**Comment by artyom-melnikov** [comment]
@SwaySway So i really like that annotated schema from amplify, but for my case it's deployment is not very suitable.

My flow is:
 - perform `amplify init` - i want to discard this step
 - Generate final schema and resolvers (`amplify api gql-compile`)
 - Parse `build/stacks/*.json` files and get resolver <-> datasource mapping
 - With CDK create all required resources and attach resolvers according to the mapping from Amplify, use generated templates from the `resolvers` folder
 - After deploy manually generate aws-exports.js 

The problem with amplify init is that our team has many ppl and we spread across different regions and as far as i understand they all will need their own envs (because we have different aws profiles etc)

My idea was to somehow mock the init process, so amplify will just generate schema. Do you have any ideas how can i do that?
