### ISSUE TITLE
getaddrinfo ENOTFOUND on amplify push

### ISSUE THREAD

**Issue by jtpdev** [aws-amplify/amplify-cli#3558]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Throws: **An error occured during the push operation: getaddrinfo ENOTFOUND** when I try to push the project.

**Amplify CLI Version**
4.6.0

**To Reproduce**
I configure another account in my amplify project and ran **amplify init** to init with a new environment. Then I ran **amplify status** and all is setup to create, so I ran **amplify push** to push to the new account and throws: **An error occured during the push operation: getaddrinfo ENOTFOUND**

**Expected behavior**
I just want to push my project.

**Screenshots**
It is not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Node Version. v13.5.0

**Additional context**
My project was build with Ionic 4. And it's worked with old account. Before I switch accounts.

**Comment by SwaySway** [comment]
Hello @jtpdev if you are moving your project to a new account you can try running `amplify configure project` to reconfigure the aws credentials for the project.

View docs here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#amplify-configure-project

**Comment by jtpdev** [comment]
I already do it. But without doing anything the error stopped.
