### ISSUE TITLE
Amplify CLI Plugin Scan Failed

### ISSUE THREAD

**Issue by martinpapacodes** [aws-amplify/amplify-cli#3560]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify CLI Plugin scan failed.

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

 ~/D/4/taskmaster   notifications ±  amplify -v
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)
 ~/D/4/taskmaster   notifications ±  

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

I uninstalled and reinstalled Amplify CLI. Keep getting the same errors over and over.

 ~/D/4/taskmaster   notifications ±  amplify -v
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)
 ~/D/4/taskmaster   notifications ± 

**Comment by SwaySway** [comment]
Hello @martinpapacodes What OS are you installing the CLI on?

**Comment by martinpapacodes** [comment]
macOS Mojave
Version 10.14.6

**Comment by UnleashedMind** [comment]
Interesting to see the error is from a ts file. It should 
How did you install the Amplify CLI?

**Comment by kaustavghosh06** [comment]
@martinpapacodes I've seen this error when using Node version < 10.x

What's the node version you're using?

**Comment by adamosimpson21** [comment]
I'm having the same issue as OP. 
Node version: 12.16.1
NPM version: 6.13.14
yarn version: 1.22.0
OS: Windows 10 Home, Version 1809, OS Build 17763.1039

I installed the amplify cli in my root directory C:\npm install -g @aws-amplify/cli 
I successfully got to the post-install.js, "Successfully installed the Amplify CLI...Javascript Getting Started...". Anytime I run an amplify command, I receive the same error as OP. This includes amplify init, amplify -v, etc. This is the same error whether I run them in the root directory or my project directory. 

I've tried reinstalling node, npm, yarn, webstorm, and amplify, and have also deleted and re-cloned my project from github. The set-up has worked for other members of my team without issue, but does not work on my environment, although it was working roughly 2 months ago when we began the project. Error started last week when we re-visited the project (I did have to pull it from master this time around.)

Willing to provide any other information necessary to assist with troubleshooting :)

**Comment by montycheese** [comment]
Is there any movement on this? We're having the same issue also.

**Comment by quinlayen** [comment]
I have been having same exact problem.  I was using amplify cli fine without issue, then suddenly started to receive this error with every amplify command.  I have tried uninstalling and reinstalling node, npm, amplify but end up with 

amplify configure
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)
➜  healthisland git:(develop) amplify -v
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)

**Comment by kaustavghosh06** [comment]
Hey guys, could you'll please install the latest version of the CLI - 4.14.1 and see if you're having this issue. As a a part of the latest release we clear the esm cache for the amplify CLI which I suspect is causing this issue.

**Comment by quinlayen** [comment]
Hi @kaustavghosh06 .  unfortunately that didnt do it for me.  Here is my output:


----------------------------------------
Successfully installed the Amplify CLI
----------------------------------------


Javascript Getting Started - https://aws-amplify.github.io/docs/js/start


Android Getting Started - https://aws-amplify.github.io/docs/android/start


iOS Getting Started - https://aws-amplify.github.io/docs/ios/start

+ @aws-amplify/cli@4.14.1
updated 1 package in 30.37s
➜  healthisland git:(develop) ✗ amplify configure
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)
➜  healthisland git:(develop) ✗ amplify -v
Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan (/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)

**Comment by adamosimpson21** [comment]
Steps I took:
C:\ npm -g uninstall @aws-amplify/cli
successfully uninstalled, then
C:\ npm -g install @aws-amplify/cli@4.14.1
reached post install screen (successfully installed the amplify cli, JavaScript getting started...)
C:\ amplify -v
Result: plugin scan failed (same error as before)
C:\mydirectory\myproject
Result: plugin scan failed (same error as before)

No changes with 4.14.1

**Comment by yunityio** [comment]
This issue is blocking some of our new developers from onboarding onto our Amplify-based project. 

Any update on this issue?

**Comment by UnleashedMind** [comment]
I've tried on different node versions and different CLI versions and I couldn't reproduce. 
Could you please go to this line of the code ` /usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11`, and insert one line of code to help us to diagnose? 
```js
    print.error(JSON.stringify(e));
```

**Comment by adamosimpson21** [comment]
The exact spot for me was a little different than mentioned, but I think I found the right place for the print statement: (was line 121 for me). It produced the read out:

`C:\>amplify -v
Scanning for plugins...
Plugin scan failed.
{"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Users\\adamo\\.amplify\\plugins.json"}
Plugin scan failed.
Error: Plugin scan failed.
    at scan (C:\Users\adamo\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\plugin-manager.ts:138:4)`

**Comment by UnleashedMind** [comment]
It seems the CLI does not have the permission to open an essential file resided in `~/.amplify/plugins.json`. 
This can be caused by reasons like, the file is open by some other program, or you didn't grant the CLI permission to access it. 
You can remove that file (which will be regenerated by the CLI upon scan), and then run `amplify plugin scan` with admin right.

**Comment by montycheese** [comment]
That seems to have solved the problem. @UnleashedMind

**Comment by quinlayen** [comment]
@UnleashedMind this worked for me as well.  Thank you.

**Comment by kaustavghosh06** [comment]
Looks like its the same issue for everyone on this thread. Please let us know if @UnleashedMind's workaround didn't work for you and we'll re-open the thread.

**Comment by quinlayen** [comment]
Unfortunately it started again just days after following @UnleashedMind
workaround.  The original problem seems to still need to be addressed.

**Comment by GABAnich** [comment]
```bash
cp ~/.amplify/plugins.json ~/Desktop
sudo rm -rdf ~/.amplify
mkdir ~/.amplify
touch ~/.amplify/plugins.json
```

Finally, we need copy entity (not file) ~/Desktop/plugins.json to ~/.amplify/plugins.json

That works for me

**Comment by GABAnich** [comment]
Or, simply
```bash
sudo chown -R <user> ~/.amplify
```
