### ISSUE TITLE
The client is not authorized to perform this operation. Error when Trying to use a new environment to call a REST API endpoint.

### ISSUE THREAD

**Issue by danmight** [aws-amplify/amplify-cli#3562]
** Which Category is your question related to? **
Auth, API (REST), Functions

** What AWS Services are you utilizing? **
Cognito, API Gateway 

** Provide additional details e.g. code snippets **
Amplify CLI 4.13.4

Scenario:
I created an app and developed on my localhost.

I then hooked it to the Amplify Console and created a new branch and backend called staging (which is a new environment).

In my master branch I make a REST API put call to the API Gateway which then invokes a lambda function. 

When I try to exectute the same exact code on the staging branch using the staging REST API call that was created from the master I get an error in Cloudwatch that says: The client is not authorized to perform this operation and I get a 403 CORS error in my browser under developer tools, however, the OPTIONS request works fine based on the log and returns a status 200, but the next line is the not authorized one. 

I would imagine it has something to do with authentication that needs to get adjusted between the master and staging branch backends that didn't get set right when I ran amplify env add and made the staging.

Any suggestions or data I could provide someone to see if they can help?

**Comment by danmight** [comment]
This might be related to this issue I just posted [https://github.com/aws-amplify/amplify-js/issues/5058](url)

Looking into it more, it's not a CORs issue for sure. 

I don't think the cognito authRole added by amplify is getting used. S3 is also having problems. I got around this one by making a Cognito Authorizer and skipped using IAM roles to call the API.

With this issue I just posted I think I'm narrowing it down to that, but I don't have a way that I know of to get around the S3 issue like I did with the cognito authorizer.

**Comment by danmight** [comment]
UPDATE: I found out how to make S3 work, but I'm still using cognito authorizers for the API gateway. Solution in the issue referenced above. I'm fine with using authorizers since they work fine. I'm just more concerned that I feel like something is going on that I'm missing and could possibly be an issue in production one day on something else.

**Comment by edwardfoyle** [comment]
Hi @danmight I was able to set up a REST API in different environments and switch between them without issue using Cognito for authentication. Just make sure you clear browser cookies or use incognito mode when switching environments as user session data may conflict.

As far as using IAM roles, can you provide more details about how you are doing that? aws-exports.js does not have an automated way of working with IAM. You can still get it to work by assuming a role that has permissions to call the API and following the instructions [here](https://aws-amplify.github.io/docs/js/api#custom-request-headers) and [here](https://aws.amazon.com/premiumsupport/knowledge-center/iam-authentication-api-gateway/) for setting the accessKey and secretKey in the request. However, you should never hardcode an IAM role secretKey in client-side code which is why the best practice is to assume a role using the Cognito authorizer.

**Comment by danmight** [comment]
@edwardfoyle When cognito is setup cognito it creates a role named amplify-{project name}-{env nam}-221151-authRole. In the Identify pool there is a setting that shows authenticated users should assume that role. I guess I assumed when you create a REST API with Amplify and require authenticated users then leaving the method authentication option on the default AWS_IAM selection would work. However, it does not for me. Apparently my authenticated users are not being given the authRole that is created since I keep getting denied when I try to call the API when logged in. However, if I make a cognito authorizer and select that as the method authentication it works fine and the API call goes through and returns successfully. Is that correct, or if I have the identify pool settings correct should my authenticated user be able to use the API end point through the authRole if I have it set to AWS_IAM in API Gateway? Based on one of the links you sent it sounds like they should.

![image](https://user-images.githubusercontent.com/47647812/76269323-c751bc00-6236-11ea-99f4-31c98dd62844.png)

**Comment by edwardfoyle** [comment]
@danmight When you use Cognito authorization, logged in users will assume the IAM authRole and that role is configured to be able to access the API so you should be able to leave AWS_IAM as the authorization on the API. If that's not working for you then something is probably not configured correctly. Did you configure the Cognito user pool and authorizer using the CLI? If possible, can you repro the issue in a new project and give the exact CLI question / answer flow that led to the problem?

**Comment by danmight** [comment]
@edwardfoyle No problem. I can do that when I get a chance. I first noticed the problem when I was halfway through my app and decided it was time to make a staging environment, so I was all set up for a better testing and deployment process before the web app was live. I made my staging environment from the master by doing `amplify env add` then selected "no" to using a current environment. I then created a new branch in my git repository called staging and pushed it to AWS then my git repository. The staging would not allow my REST APIs to work but the master one worked fine. I blew away the amplify environment after days of trying to figure it out. I deleted the staging branch as well and just had my master branch with no amplify. I did `amplify init` and added all my code back by building the REST API with lambda functions, etc... and tested it and the master branch was no longer working either with the new master environment after I blew the original one away. Since then the only way for me to get the REST APIs to work is cognito authorizers. I built the authorizers in the API gateway console directly. In any case, if I can reproduce it and provide the flow from the CLI I will.

One interesting thing to note, on the issue I referenced a few comments up where my .put was also not working I got that fixed by going into the identity pool and switching cognito to assume "the default role" which is the authRole. It had defaulted to "from token". That was also denying access, but when I switched it to "default role" my cognito user assumed the proper authRole and was able to execute the .put. Does the REST API, without using a cognito authorizer, rely on a token to get the role it needs to assume? That might be the common denominator if my tokens are somehow using a bad access key or secret key? Totally speculating as I've not looked at the code base how all that works.

**Comment by edwardfoyle** [comment]
@danmight any update here? Minimal repro steps would be very helpful if you have a chance to follow up

**Comment by danmight** [comment]
Edward, my apologies. I never circled back on this. However, I was having
an auth problem on another issue, I think someone else found out what is
going on.

If you look at this issue:
https://github.com/aws-amplify/amplify-js/issues/5058 we were finding that
we were not getting the authRole assigned and some steps to how we could
recreate it.

**Comment by edwardfoyle** [comment]
@danmight Thanks for following up! I was able to repro the issue, but I was able to fix it by running the following CLI commands:
```
$ amplify update storage
? Please select from one of the below mentioned services: Content (Images, a
udio, video, etc.)
? Restrict access by? (Use arrow keys)
  Auth/Guest Users
  Individual Groups  <== select this option if you only want to authorize groups
❯ Both               <== select this option if you want to authorize groups and users
  Learn more

... other auth questions ...

? Select groups: (Press <space> to select, <a> to toggle all, <i> to invert
selection)
❯◉ yourUserGroup     <== select authorized groups here

... more questions ...
``` 
Then run `amplify push` and you should be able to perform the operations you authorized by singing in as a user in a pool. This was also run with the latest version of the CLI (4.18). Let me know if that solves the issue for you!

**Comment by danmight** [comment]
That’s awesome, thank you for that!!
