### ISSUE TITLE
Amplify project multi env with GraphQL APIs

### ISSUE THREAD

**Issue by KrustyHack** [aws-amplify/amplify-cli#3563]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Amplify, AppSync, multi env (dev/prod)

**Amplify CLI Version** 

3.15.0

**What AWS Services are you utilizing?**

* Amplify
* AppSync
* Cognito
* Lambda

**Provide additional details e.g. code snippets**

I have 2 environments for my Amplify project : dev and prod. Each one got a dedicated Cognito Pools, allowing me to tests auth mechanics without breaking prod users.

I want to do same with my AppSync API : have one for dev, one for prod to allow me to test my app on dev env without breaking prod env.

What is the best approach to do that ? I have tried having 2 AppSync APIs but CodeGen only allow one per project.

If you have any guidelines or tips I'm totally lost.

**Comment by SwaySway** [comment]
Hello @KrustyHack multi-env follows a git workflow so you could effectively have a branch called dev paired with a dev env. This should let you have a different `.graphqlconfig.yml`.

Mutli-Env Docs: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#concepts-1

**Comment by KrustyHack** [comment]
Ay,

Thanks ! It's more clear now !

I was totally lost and didn't understand what amplify env stand for and what was relationship with git branches.

Your schema is very nice, I will print it I think.

Sad I didn't find it before in the docs. :(

Thanks again !
