### ISSUE TITLE
AppSync Mock - Unable to convert document to class ...LambdaVersionedConfig.

### ISSUE THREAD

**Issue by NeillGiraldo** [aws-amplify/amplify-cli#3574]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
On `amplify-appsync-simulator@0.23.0` this request mapping template works 

```
#**
The value of 'payload' after the template has been evaluated
will be passed as the event to AWS Lambda.
*#
{
  "version" : "2017-02-28",
  "operation": "Invoke",
  "payload": {
    "arguments": $util.toJson($context.args),
    "field": "changeUser",
  }
}

```

however on the current version is not working.

**Amplify CLI Version**
amplify-appsync-simulator@1.14.0

**To Reproduce**
Example provided in the description

**Expected behavior**
Should Invoke lambda data source

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v10.15.3

**Comment by nikhname** [comment]
@NeillGiraldo what error message do you see when you try this?

**Comment by NeillGiraldo** [comment]
Hi @nikhname, This is the error that is being thrown.
```
{
  "data": {
    "changeUser": null
  },
  "errors": [
    {
      "message": "Unable to convert {\n  \"version\" : \"2017-02-28\",\n  \"operation\": \"Invoke\",\n  \"payload\": {\n  \t\"arguments\": {\"username\":\"changedUser\"},\n    \"field\": \"changeUser\",\n  }\n} to class com.amazonaws.deepdish.transform.model.lambda.LambdaVersionedConfig.",
      "errorType": "MappingTemplate",
      "data": null,
      "errorInfo": null,
      "path": [
        "changeUser"
      ],
      "locations": [
        {
          "line": 6,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

**Comment by NeillGiraldo** [comment]
Hi @nikhname , I checked a bit deeper and it was because of the trailing comma at the end of the payload. JSON.parse was failing because of it.

**Comment by kaustavghosh06** [comment]
We do strict evaluation of the JSON which is the recommended practice. Let us know if you're still stuck with this.
