### ISSUE TITLE
Amplify-Tools does not generate amplifyxc.config with existing amplify project

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#3579]
Please see https://github.com/aws-amplify/docs/issues/1176 or transfer it over here. It already contains a lot of information.

**Describe the bug**
When developer uses amplify-tools with existing amplify project, ampifyxc.config is missing. Is this expected? what is the developer experience in this case? does the developer go to their terminal to continue to run commands like `amplify codegen models`?

**Comment by nikhname** [comment]
@lawmicha This is not expected behaviour, the helper file should be created even if the amplify folder exists. Could you try running npm uninstall -g amplify-app and build again to see if it is working with the latest version of amplify-app. I was not able to reproduce this locally

**Comment by nikhname** [comment]
Transferred this issue and closing this one
