### ISSUE TITLE
@auth with list of owners results in "type mismatch error, expected type LIST"

### ISSUE THREAD

**Issue by DanNeish** [aws-amplify/amplify-cli#358]
**Describe the bug**
When creating an item that has auth specified as a list of owners without specifying the owner on creation results in the owner field being automatically assigned a "string" rather than ["string"].

**To Reproduce**
Create a new Amplify project with amplify init

amplify add api and select GraphQL

Setup API with Cognito User Pool

Create the following schema
```
type Task
  @model 
  @auth(rules: [
    { allow: owner, ownerField: "collaborators" }
  ]) {
  id: ID!
  name: String!
  description: String
  collaborators: [String]
}
```

amplify push

Go to AppSync console > Query. Login as a user.

Run the following mutation
```
mutation CreateTask {
    createTask(input: { name: "task 1", description: "task 1 description" }) {
        id
        name
    	description
    	collaborators
    }
}
```
This is the result
```
{
  "data": {
    "createTask": {
      "id": "f4c7dc5c-22eb-44b3-aff6-0bb360596487",
      "name": "task 1",
      "description": "task 1 description",
      "collaborators": null
    }
  },
  "errors": [
    {
      "path": [
        "createTask",
        "collaborators"
      ],
      "locations": null,
      "message": "Can't resolve value (/createTask/collaborators) : type mismatch error, expected type LIST"
    }
  ]
}
```
The Task dynamo DB table contains the user ID in the collaborators field as a string:
`collaborators: "abcd"`

**Expected behavior**
As per the documentation [here](https://aws-amplify.github.io/docs/js/graphql)
Expected result is collaborators is assigned a list with the ID of the owner.
```
{
  "data": {
    "createTask": {
      "id": "ef3ee7ae-781b-440f-9079-caa4ac88961f",
      "name": "task 1",
      "description": "task 1 description",
      "collaborators": ["abcd"]
    }
  }
}
```

**Additional context**
@aws-amplify/cli v0.1.27

**Comment by mikeparisstuff** [comment]
Is this your exact schema?

```graphql
type Task
  @model 
  @auth(rules: [
    { allow: owner, ownerField: "collaborators" }
  ]) {
  id: ID!
  name: String!
  description: String
  collaborators: [string]
}
```

If so you need to capitalize "string" to be "String".

```graphql
type Task
  @model 
  @auth(rules: [
    { allow: owner, ownerField: "collaborators" }
  ]) {
  id: ID!
  name: String!
  description: String
  collaborators: [String]
}
```

The schema validation should have caught this. I will look into why it didn't error at build time.

**Comment by DanNeish** [comment]
@mikeparisstuff sorry I made a mistake, I had tried many different ways before I simplified it down to the schema I provided and manually updated the string field - you are correct, it should be `String`, the schema validation does flag this as an error.

I have run through the steps on a new project and copied the exact code that was used (updated in the original post. The error still exists.
