### ISSUE TITLE
Use owner as the primary key for settings table

### ISSUE THREAD

**Issue by jarkin13** [aws-amplify/amplify-cli#3584]
** Which Category is your question related to? **
Appsync + Backend files
** What AWS Services are you utilizing? **
Cognito, AWS AppSync, Api, Auth
** Provide additional details e.g. code snippets **
I would like to make the `owner` the primary key, here is the code for my `@model`

```
type User 
	@model(
		queries: { get: "getUser" }, 
		mutations: { create: "createUser", update: "updateUser" }
	) 
	@key(fields: ["owner"])
	@auth(rules: [
		{ allow: owner },
		{ allow: private, operations: [read] }
	]) {
		owner: String!
		email: String!
		phoneNumber: String
		image: String
		noviaties: [NoviatyUser] @connection(keyName: "byUser", fields: ["owner"])
		status: Status
}
```

If I go into my Appsync api, I can update 

```
input CreateUserInput {
	owner: String!
	email: String!
	phoneNumber: String
	image: String
	status: Status
}
```
to:
```
input CreateUserInput {
	email: String!
	phoneNumber: String
	image: String
	status: Status
}
```

and go into the resolver and comment out the following:
```
## [Start] Set the primary @key. **
#set( $modelObjectKey = {
  "owner": $util.dynamodb.toDynamoDB($ctx.args.input.owner)
} )
## [End] Set the primary @key. **
```

It works as should, however every time I run `amplify push` I have to update this. I was wondering how I can make the owner the primary key and how can I add/view/update my resolvers in my files?

**Comment by kaustavghosh06** [comment]
@jarkin13 The CLI doesn't overwrite self-specified types. So if you have your input type defined in the schema, the transformer won't overwrite it. Also, the transformer supports custom resolvers, for which you can take a look out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers

**Comment by sregg** [comment]
@jarkin13 I had the same issue and I fixed it by replacing
```
owner: String!
```
with
```
owner: String
```
(removed the `!`)
