### ISSUE TITLE
Field level group auth returns null when subscribptions are activated

### ISSUE THREAD

**Issue by azatoth** [aws-amplify/amplify-cli#3594]
**Describe the bug**
If having a schema like following:

```GraphQL
type MyModel
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["MyGroup"], operations: [read, update] }
      { allow: private, provider: iam, operations: [create, delete, read, update] }
    ]
  ) {
  id: ID!
  file: S3Object! @auth(rules: [{ allow: groups, groups: ["MyGroup"], operations: [read] }])
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  status: Status!
}

enum ProtectionLevel {
  private
  protected
  public
}

type S3Object {
  protection: ProtectionLevel!
  bucket: String!
  path: String!
  region: String
}
```

and the generated mutation is as following:

```js
export const updateMyModel = /* GraphQL */ `
  mutation UpdateMyModel(
    $input: UpdateMyModelInput!
    $condition: ModelMyModelConditionInput
  ) {
    updateMyModel(input: $input, condition: $condition) {
      id
      file {
        protection
        bucket
        path
        region
      }
      createdAt
      updatedAt
      status
    }
  }
`;
```

and as a user who is in group "MyGroup" update for example the `status` field, the updateModel mutation will return `null` for the `file`field even though it has data in it. A normal get or list will return this field in its output though.

**Amplify CLI Version**
4.13.4

**Expected behavior**
I expect it to include the S3Object object in the updated output

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node: v13.7.0

**Additional notes:**
Setting `subscriptions: null` on the model will fix the issue.

**Comment by yuth** [comment]
@azatoth this is done to prevent data from reaching to a subscriber who is not authorized to see it. AppSync services does not have capabilities to change the selection set of the subscription and sends the all the fields in the mutation selection set to all the subscribers. To prevent unauthorized users accessing the data through subscription, any field that has field level auth set, is set to null before sending to clients.

**Comment by SwaySway** [comment]
Closing this issue should you still have any questions related to this please feel free to comment below.
