### ISSUE TITLE
Specify Lambda IAM role

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#36]
Do you want to request a feature or report a bug?
Feature.

What is the current behavior?
A new IAM role is generated for each lambda function.

What is the expected behavior?
Allowed to pass the name of an IAM role to reuse in lambda functions.

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
0.1.14

**Comment by kaustavghosh06** [comment]
@jarrettj You can still modify the Lambda Cloudformation template and add your own role if needed and that role would be used as the execution role.
Also, if this helps - today we released an updated flow as a part of the functions category to pass resource identifiers like the cognito userpool ID  or graphql ID (managed and generated by the Amplify CLI) to a lambda function as environment variables and also populate the corresponding lambda execution role to access these resources. You can install the latest version of the CLI and go through the `amplify update function` flow to update your existing functions to access your Amplify generated resources in the project.

**Comment by jarrettj** [comment]
If you manually create a role, you would lose all the auto-generated stuff that amplify cli does to the role. And that's more work than having a proliferation of roles in the Console I guess. I choose the lesser evil!
