### ISSUE TITLE
4.14.1 elasticsearch transform bug

### ISSUE THREAD

**Issue by rarira** [aws-amplify/amplify-cli#3602]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I have to upgrade from 4.13.1 to 4.14.1 because of this issue #3493 
and pagination token issue had been solved but there happens to be another big issue in elasticsearch transform..
I think #2860 happens again 
when there is existing string set data in elasticsearch index, the item can't be updated accordingly with dynamodb update and there was very strange outcome that elasticsearch stores duplicate item with different id instead of updating.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.14.1
when rolled back to 4.13.1 there is no problem

**Expected behavior**
stringset data can be dealt with properly
I hope there will be changelog update if there is a breaking change like this

**Comment by SwaySway** [comment]
Hello @rarira 
This seems related to supporting `@key` in `@searchable` we'll investigate on a fix to avoid duplicate records. In the meantime one potential workaround you can do is use the lambda function from the old version below and in the latest release of the cli you can add that zip into a folder functions and it will be overridden.

Old Streaming Lambda Function: https://github.com/aws-amplify/amplify-cli/blob/16419f4d9e1733ed0ada064f9ced604083ee4703/packages/graphql-elasticsearch-transformer/streaming-lambda/python_streaming_function.py

**Comment by brene** [comment]
Hi @rarira - I'm closing this per #3705

**Comment by rarira** [comment]
@brene I just tested new 4.17.1 and it seems that it solved this issue but your backfill python script doesn't work as expected...

at first, I acknowledged that I'm not good at elasticsearch so it might be my fault.

I have a Conv model which has 'user1state' which is string and this string is 'ISO date string' or just plain string. 
```
type Conv
  @model
  @searchable {
  user1state: String
}
```

but your backfill script map this field automatically type "date" so other items with 'just plain string'  failed indexing.

```
"user1state": {
   "type": "date"
},

```

so I had used custom mapping before populating all of my indices as below 

```
PUT conv
{
   "mappiings" : {
...
...
    }
}

```

but in this case, backfill script doen't work at all..

**Comment by SwaySway** [comment]
@rarira The reason this might be happening is because the python stream lambda will push the record from the dynamodb stream into elasticsearch. During this time the types being used in the record are inferred. 

Does the string `user1state` have a date format?

**Comment by rarira** [comment]
> @rarira The reason this might be happening is because the python stream lambda will push the record from the dynamodb stream into elasticsearch. During this time the types being used in the record are inferred.
> 
I also understand the process.

> Does the string `user1state` have a date format? Did this run against an already existing index or was it deleted before running the script?

I mentioned that the string ‘user1state’  has either “iso date string” or “just plain string”. And of course there was no populated index before running script. So I needed to “backfill”

And I also that if there exists index with custom field type mapped, for example, “user1state”: “text” the script doesn’t work at all, I mean no dynamoDb item indexed.
