### ISSUE TITLE
Clone Env Correctly

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-cli#3611]
Recently I have been using Amplify more and more, and the one thing I discovered is cloning environments is rough. I have policies in certain services because Amplify claims you need these to have certain functions working. It would be great to have the ability to clone an env and have the policies copied and their ARN paths updated. Or if there is a policy just prompt the use to check it before the cli continues.

**Comment by kaustavghosh06** [comment]
@Rafcin Do you use the CLI to manage your backend infrastructure? How and where do you write these custom policies?

**Comment by Rafcin** [comment]
I have a dev env and a prod env setup. The policies I change through the AWS console. I guess what I mean is say I setup elastic search with a geopoint. In the dev tools section of Kibana I have commands setup to rest my mapping if I update graphql, or my s3 storage bucket has policies to make certain things public. On cognito I set custom attributes for my users, and although it copies my groups I still need to set read and write access to the attributes. So small details such as those.

**Comment by yuth** [comment]
Amplify CLI uses CloudFormation to create resources. Any changes made to those resources using AWS Console, are not tracked by ClouFormation (so by Amplify CLI). If you want to change things that are created by amplify console follow you could follow our [escape hatches](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks) as documented in our docsite

**Comment by yuth** [comment]
Please comment on this thread if you have any further question
