### ISSUE TITLE
Change AWS Account for CLI

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#3613]
So i have my company account in aws and i have a private aws account. 

So when i want create an app for me, how can i do this?

when i run amplify init, it asks me if i want to use my default user, but not the account.

**Comment by nikhname** [comment]
Hi @davidbiller to use a different AWS account run ```amplify configure``` and follow the steps to configure a new profile. You can then choose that profile the next time you run ```amplify init```
