### ISSUE TITLE
Multi env doesn't update gitignore files

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3617]
**Describe the bug**
Adding multiple environment doesn't update gitignore files.

**Amplify CLI Version**
4.16.0

**To Reproduce**
`npx create-react-app multi-env --use-npm --template typescript`
`npx amplify-app@latest`
`amplify init` with prod env
`amplify push`
`git add .`
`git commit -m 'master commit'`
`git checkout -b dev`
`amplify init` with dev env

**Expected behavior**
With multiple enviornments it should update gitignore file so when I merge dev branch with master then things won't get mixed up. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 on windows 10 wsl
 - Node Version. 12.16.1

**Comment by karrettgelley** [comment]
What things in particular are getting mixed up? I notice when I use multiple environments, the team-provider-info.json changes after a merge, thus requiring another commit, but what is happening in your case?

**Comment by apoorvmote** [comment]
In my case `npx amplify-app@latest` will automatically initialize amplify environment but will not add anything in `.gitignore`. Or if you initialize amplify after `npx amplify-app@latest` with either `amplify init` or `amplify env add` it will not update `.gitignore` file. This causes whole slew of problems after.

And yes the for me also `team-provider-info.json` also changes after the merge.

**Comment by kaustavghosh06** [comment]
@apoorvmote Ideally `amplify init` should add this to .gitignore. We're looking into it.
