### ISSUE TITLE
Each time I change amplify environment there is update for admin queries function

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3618]
**Describe the bug**
I am using default admin queries lambda function. I have 2 environment master & dev. I also have 2 git branches master & dev. Each time I change `amplify env checkout` master or dev followed with appropriate `git checkout` master or dev. There is always update for admin queries function. 
I suspect there is some issue with auto generated `.gitignore` file. So here is my `.gitignore`
```
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*

#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplify-gradle-config.json
amplifyxc.config
```

**Amplify CLI Version**
4.16.0

**To Reproduce**
`npx create-react-app notes --use-npm --template typescript`
`amplify init` with master env
`git commit`
`git checkout -b dev`
`amplify init` with dev env
`amplify add auth` default selection
`amplify update auth` to add admin group and admin queries api
`amplify push`
then I tested with `withAuthenticator` and some ui
`git commit`
`git checkout master && amplify env checkout master`
`git merge dev`
`amplify push`
then again I tested if its working 
`git commit` master then also merge master with dev
now here onwards when I `git checkout` dev or master with appropriate `amplify env checkout` dev or master there is always update for admin queries function

**Expected behavior**
Everything should be upto date. No update to admin queries function when I change env.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 on windows 10 wsl
 - Node Version. 12.16.1

**Comment by yuth** [comment]
Admin Query lambda has the deployment bucket hard coded in the cloudformation template. The deployment bucket name changes between environment. The template should be updated to Ref the Deployment bucket from the root stack

**Comment by apoorvmote** [comment]
Thanks for finding the reason. I don't know cloud formation template programming. And I tried to learn based on everything else in the file. Because everything else in admin queries is updated based on env. I went through aws documents for cloud formation and still its just confusing to me.

Temperorily I just copy pasted `DeploymentBucketName` from `team-provider-info.json` to `S3Bucket` from `adminQueriesCloudFormation.json`. And it seems to solve the problem. Only issue is I have to do that manually every time I merge dev with master.

**Comment by apoorvmote** [comment]
@yuth Another thing that is really bothering me is my react web app either after `Auth.signIn()` or after `Auth.currentAuthenticatedUser()` It makes few requests to cognito that result in 400 response. It doesn't affect the app. 

The official error is as follows `xhr.js:81 POST https://cognito-identity.eu-west-1.amazonaws.com/ 400`

It continues to make multiple requests again and again without affecting login. But I see lots of red errors in console. It is driving me crazy.

**Comment by kaustavghosh06** [comment]
@apoorvmote We're tracking the function bucket and key name enhancement out here in this ticket https://github.com/aws-amplify/amplify-cli/issues/3068
For the Amplify JS library issue tied to `Auth.currentAuthenticatedUser()`  - are you still stuck? If yes, I would highly recommend opening up a new issue out here - https://github.com/aws-amplify/amplify-js

**Comment by apoorvmote** [comment]
@kaustavghosh06 I have lost faith in the multi env setup. It's more reliable to just create 2 different project 
1. prod
1. dev

And even if you fix it I would never use multi env with production again. I will try with dev version because I don't care if it fails.
