### ISSUE TITLE
UnauthorizedException: Invalid API key

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3619]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After I upgraded from 4.12.0 to 4.16.0, API Key auth doesn't work with mock anymore. Here is the error message when I tried to list objects with AppSync mock client. If I change the version back to 4.12.0, everything works again. 
{
  "errors": [
    {
      "errorType": "UnauthorizedException",
      "message": "UnauthorizedException: Invalid API key"
    }
  ]
}

**Amplify CLI Version**
4.16.0

**To Reproduce**
create a sample project with Amplify cli
make sure you add API KEY auth to the schema
Run amplify mock
open the url http://localhost:20002/
run any list query with API KEY auth

**Expected behavior**
API KEY auth should work with mock

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v8.11.1

**Additional context**

**Comment by yuth** [comment]
Is there anything else you have custom for the API? Could you also share whats the API Key value used my mock. This can be found by clicking on `Update Auth` and selecting `API Key` in the auth config modal. It should have the value `da2-fakeApiId123456`.

**Comment by gaochenyue** [comment]
@yuth I don't have custom for the API. My key value is da2-fakeApiId123456

**Comment by yuth** [comment]
Would it be possible to see what see what is sent in the HTTP request header `x-api-key` when an request is made

**Comment by gaochenyue** [comment]
Thanks @yuth 
Here is my HTTP Request header
```
POST /graphql HTTP/1.1
Host: 192.168.1.178:20002
Connection: keep-alive
Content-Length: 111
Accept: application/json
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
x-api-key: da2-fakeApiId123456
Content-Type: application/json
Origin: http://192.168.1.178:20002
Referer: http://192.168.1.178:20002/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```

Here is the request body
```
{"query":"query MyQuery {\n  listOrders {\n    nextToken\n  }\n}\n","variables":null,"operationName":"MyQuery"}
```

Here is the response
```
{"errors":[{"errorType":"UnauthorizedException","message":"UnauthorizedException: Invalid API key"}]}
```

**Comment by attilah** [comment]
@gaochenyue could you please share your schema? I see `MyQuery` in the request body above, is that possible that you only have this error for custom queries? or is it a `@key` query?

**Comment by gaochenyue** [comment]
Thanks @attilah
Here is where ```MyQuery``` comes from
![Screen Shot 2020-03-14 at 10 34 35 AM](https://user-images.githubusercontent.com/9857112/76684155-ed34e300-65df-11ea-9cc1-65c0db6022fc.png)

yes, it is a ```@key``` query

Here is the schema
```
type Product
    @model
    @versioned
    @auth(
        rules: [
            { allow: owner, operations: [create, update, delete, read] }
            { allow: private, provider: iam, operations: [create, update, delete, read] }
            { allow: public, provider: apiKey, operations: [create, update, delete, read] }
        ]
    )
    @key(fields: ["instance", "sku"]) {
    id: ID! ##UUID
    instance: String!
    inst: String! 
    sku: String!
    length: Float!
    lengthUnit: LengthUnit!
    width: Float!
    widthUnit: LengthUnit! 
    height: Float!
    heightUnit: LengthUnit! 
    weight: Float!
    weightUnit: WeightUnit! 
    packages: Int! 
    owner: String
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}

enum LengthUnit {
    CM 
    IN 
}

enum WeightUnit {
    LB 
}
```
