### ISSUE TITLE
Adding facebook fedarated identity users to admin group?

### ISSUE THREAD

**Issue by IljaDaderko** [aws-amplify/amplify-cli#362]
**Which Category is your question related to?**
Auth

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I used CLI to set up facebook login in my app and was able to successfully log in. I can also see entry in my cognito identity pools.

With everything going good thus far I went to cognito user pool, but could not see any new user entries there. I created Admin group, but can't add any users there since I don't see the entries from identity pool.

I assumed thats how I can add users to create auth rules like `@auth` that allows owner and admin to access some data.

What confuses me is that in my user pool facebook is not enabled, I believe cli handles it differently via openid?

Is this expected limitation or am I missing something? Since if we assume app only uses facebook and google login for example, does it mean the groups feature of `@auth` can not be used?

**Comment by haverchuck** [comment]
@IljaDaderko  - Logging in via facebook would not automatically add a user to the userpool.
