### ISSUE TITLE
Are there any limits on how many amplify environment we can create?

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#3620]
Are there any limits on how many amplify environment we can create?

**Comment by yuth** [comment]
Each Amplify Environment uses a CloudFormation stack. The only limit is that the number of CloudFormation stacks an account can have.

**Comment by kaustavghosh06** [comment]
@incr3m Please let us know if you have more questions around this based on @yuth's response. Closing this issue for now.
