### ISSUE TITLE
S3 private files for multiple users 

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#3621]
Hi,

I do manage to store private files but only the owner can get these files (with Storage.vault(key)) with AWS Cognito authentication and verification (JWT).

How to get these files for multiple authorized users like for a chat application ?

I want that **only members** can get images :
```graphql
type Conversation

  @model(subscriptions: { level: public })
  @auth(
    rules: [
      { allow: owner, ownerField: "members" }
      { allow: groups, groups: ["admin"], operations: [read] }
    ]
  ) {
  id: ID!
  **members: [String!]!**
  user: User @connection(name: "UserConversations")
  messages: [Message] @connection(name: "ConversationMessages")
  createdAt: String
  updatedAt: String
}
```

**Comment by akshbhu** [comment]
Hi @rudyhadoux 

I think to access S3 private files in your chat application, you can give access to them via Presigned urls.

These are the steps that you can follow
1) Store the image in S3
2) Do a  mutation to create the User in the GraphQL API using the image id
3) Query the image data from the API using image id
4) Get a signed URL for the image from S3.

With this url members user will be able to access private images in S3.

Let me know if this  works or related to your question.

**Comment by rudyhadoux** [comment]
Thanks for your answer.

But I do not understand at all. Create the User in the GraphQL API using the image id ?????

In a chat conversation users already exist.

**Comment by rudyhadoux** [comment]
It is a problem of amplify auth storage api.

We should set members for private files.

**Comment by rudyhadoux** [comment]
It is a feature request.

Like explained here too :
https://github.com/aws-amplify/amplify-cli/issues/1847

**Comment by rudyhadoux** [comment]
The right answer is maybe here. I have to test it.

The way this was handled in the @auth directive was nice. An identifyField was added to the @auth directive that allowed for backward compatibility and made it easy to update to identityField: sub for those who wanted to.

**Comment by VicFrolov** [comment]
@rudyhadoux Is there any documentation on `identifyField` I can not find any in the @auth directive page: https://docs.amplify.aws/cli/graphql-transformer/auth#auth

**Comment by rudyhadoux** [comment]
Hi,
I finally use pre-signed URLs.
I put the URL in a private member of an Amplify object.
