### ISSUE TITLE
Mocked lambda triggers on S3 buckets cannot operate on locally hosted S3 bucket

### ISSUE THREAD

**Issue by whtevn** [aws-amplify/amplify-cli#3629]
**Service:** Amplify Mock

**Describe the bug**
When `amplify mock` is running, S3 triggers are run with the default profile. Because of this, the triggers cannot operate on the files created in `amplify/mock-data/S3/...`

**Amplify CLI Version**
4.13.4

**To Reproduce**

Set up the following S3 Trigger

```
import { S3 } from 'aws-sdk';
exports.handler = async function(event, context) {
  const s3 = new S3();
  const Key = event.Records[0].s3.object.key;
  const Bucket = event.Records[0].s3.bucket.name;
  const CopySource = `/${Bucket}/${Key}`;
  console.log(await s3.listBuckets().promise());
  await s3.copyObject({ Key: `${Key}-copy`, Bucket, CopySource }).promise()
  context.done(null, 'success');
}
```

run `amplify mock`

upload a file to the local 

**Expected behavior**

I had expected the trigger to run with roughly the same execution role that it would in context of the trigger when hosted. It was surprising to me that the trigger has no access to the file that is referenced in the actual event of the lambda function 

The buckets which come back in the `listBucket` correspond to the buckets available to my default aws cli profile. 

```
(node:56570) UnhandledPromiseRejectionWarning: NoSuchBucket: The specified bucket does not exist
```

**Desktop:**
 - OS: Mac
 - Node Version: 13.9.0

**Additional context**
I found this bug which indicates similar functionality on `amplify function invoke` from the cli  https://github.com/aws-amplify/amplify-cli/issues/3461

although, in this case I do not want it to run as if invoked by my developer account, but instead as the execution role analogous to the one that would be used for my hosted function 

in my case, it seems like the only viable answer is to not use local mocking. There does not seem to be a way that I can find to make my lambda triggers see the local s3 filesystem, unless I am missing something, which is totally possible. Thank you for your time.

**Comment by akshbhu** [comment]
Hi @whtevn 

Right now you are endpoint in S3 server.
I think to connect your AWS S3 client  to mock S3 server in lambda code, you need to set some flags in S3 constructor.
```javascript
// setup an local endpoint
  let ep = new AWS.Endpoint('http://localhost:20005');

// make your constructor  with these parameters

  s3 = new S3({
    apiVersion: '2006-03-01',
    endpoint: ep.href,
    s3BucketEndpoint: true,
    sslEnabled: false,
    s3ForcePathStyle: true,
  });
```

**Comment by kaustavghosh06** [comment]
@whtevn Please let us know if you're still stuck on this issue based on @akshbhu 's response. Closing this issue.
