### ISSUE TITLE
Error pushing after upgrade from @aws-amplify/cli@1.1.2 to 4.16.0

### ISSUE THREAD

**Issue by dsinyakov** [aws-amplify/amplify-cli#3631]
```
$ sw_vers -productVersion
10.13.6
```
```
$ npm -version
6.13.7
```
```
$ node -v
v13.2.0
```
```
$ amplify --version
Scanning for plugins...
Plugin scan successful
4.16.0
```

```
$ amplify push
⠧ Fetching updates to backend environment: dev from the cloud.(node:92150) UnhandledPromiseRejectionWarning: RangeError [ERR_INVALID_OPT_VALUE]: The value "2355633253" is invalid for option "size"
    at Function.alloc (buffer.js:345:3)
    at Object.alloc (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:136:28)
    at Object.concat (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:175:28)
    at Request.HTTP_DONE (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:396:36)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:306:26)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:478:20)
(node:92150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Fetching updates to backend environment: dev from the cloud.
```

**Comment by UnleashedMind** [comment]
@dsinyakov 

What resources have you added to your project? 
could you send the zip of your amplify folder to us? amplify-cli@amazon.com

**Comment by dsinyakov** [comment]
my amplify dir is 8.9G. what can be sacrificed?
```
$ du -h -d 2
 12K	./.config
 16K	./#current-cloud-backend/auth
2.7G	./#current-cloud-backend/function
  0B	./#current-cloud-backend/storage
 12K	./#current-cloud-backend/hosting
728K	./#current-cloud-backend/api
2.7G	./#current-cloud-backend
 16K	./backend/auth
2.8G	./backend/function
 12K	./backend/awscloudformation
  0B	./backend/storage
 12K	./backend/hosting
728K	./backend/api
2.8G	./backend
1.9G	./.temp/#current-cloud-backend
3.5G	./.temp
8.9G	.
```

**Comment by dsinyakov** [comment]
In terms of resources, I use functions, API (both REST and graphQL), auth and hosting
```
$ amplify status

Current Environment: dev

| Category | Resource name        | Operation | Provider plugin   |
| -------- | -------------------- | --------- | ----------------- |
| Function | someFunc                           | Update    | awscloudformation |
| Hosting  | S3AndCloudFront      | No Change | awscloudformation |
| Auth     | cognitod40aca7e      | No Change | awscloudformation |
| Api      | someApi            | No Change | awscloudformation |
| Api      | someApi         | No Change | awscloudformation |
| Function | someFunc   | No Change | awscloudformation |
```
Note: function/api names changed

**Comment by UnleashedMind** [comment]
1. are there large node_modules folders under both `amplify/#current-cloud-backend/function` and `amplify/backend/function`? the node_modules folders can be dropped. 
2. the `.temp` folder can be dropped

**Comment by UnleashedMind** [comment]
which version of the CLI did you use to add the `function` resources?

**Comment by dsinyakov** [comment]
> which version of the CLI did you use to add the `function` resources?

1.1.2

**Comment by dsinyakov** [comment]
> 1. how did you `function` folders get to that large? what's in them? are there large node_modules folders under both `amplify/#current-cloud-backend/function` and `amplify/backend/function`? the node_modules folders can be dropped.
> 2. the `.temp` folder can be dropped

the main contributor to the size are zips in function/*/dist. Let me clean those up

**Comment by dsinyakov** [comment]
> @dsinyakov
> 
> What resources have you added to your project?
> could you send the zip of your amplify folder to us? [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)

Sent

**Comment by UnleashedMind** [comment]
@dsinyakov 
The error is very likely due to the large size of your `#current-cloud-backend`.
Could you please follow these steps to tell us a zip file's size:
1. In the `amplify/backend/amplify-meta.json` file, find the name of the deployment bucket: `providers.awscloudformation.DeploymentBucketName`
2. Go to your AWS S3 console, and locate the deployment bucket
3. In the deployment bucket, local the file `#current-cloud-backend.zip` and its size shown on the screen. 

What is the file size? is it over 2G?

**Comment by dsinyakov** [comment]
> @dsinyakov
> The error is very likely due to the large size of your `#current-cloud-backend`.
> Could you please follow these steps to tell us a zip file's size:
> 
> 1. In the `amplify/backend/amplify-meta.json` file, find the name of the deployment bucket: `providers.awscloudformation.DeploymentBucketName`
> 2. Go to your AWS S3 console, and locate the deployment bucket with the name from step 1.
> 3. In the deployment bucket, local the file `#current-cloud-backend.zip` and its size shown on the screen.
> 
> What is the file size? is it over 2G?

The size is 45.4 KB

**Comment by dsinyakov** [comment]
I zipped the locally saved #current-cloud-backend, uploaded it to S3 and was able to run `amplify push` successfully.

**Comment by dsinyakov** [comment]
Thanks for all the help

**Comment by aditi172** [comment]
@UnleashedMind can you please help me out here... 
I was having the same issue when I checked that there is no s3 bucket available with the DeployementBucketName in my console so I created one and added the zipped #current-cloud-backend files to it after which the amplify push command did work but only to give another error
ERROR:

UPDATE_ROLLBACK_COMPLETE amplify-mariocart-dev-54945 AWS::CloudFormation::Stack Fri Jul 24 2020 03:53:29 GMT-0700 (Pacific Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
| Updating resources in the cloud. This may take a few minutes...

Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

NOTE: amplify-mariocart-dev-54945 is the name of my deployementbucket that I had to create manually
**I've been stuck with this for quite sometime and I'd really appreciate any sort of help to get myself over this issue**
