### ISSUE TITLE
When using a custom resolver with lambda, how to preserve directives (e.g. @connection, @searchable, @auth, etc)

### ISSUE THREAD

**Issue by VicFrolov** [aws-amplify/amplify-cli#3633]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
I am using AmplifyJS API with the graphql option, and have used the api to create various `@models`, `@connections`, used `@auth`, and have various models `@searchable`. For simplicity, here are two models:

```
type Note @model @searchable @auth(
    rules: [
      {allow: owner, ownerField: "owner", operations: [create, read, update, delete]},
    ]) {
  id: ID!
  content: String!
  user: User @connection(fields: ["userID"])
  userID: ID!
}

type User @model @searchable {
  id: ID!
  name: String!
}
```

I wanted to add a few operations when `createNote` runs, so I made a custom resolver with lambda following (https://aws-amplify.github.io/docs/cli-toolchain/graphql#add-a-custom-resolver-that-targets-an-aws-lambda-function), this would do some calculations on the side in lambda for me.

I realized this does not persist the logic of @searchable, @connection, @model, and so I am wondering how I can do a custom resolver? I've also seen @function, and am wondering if I do something like:

```
type Mutation {
  createNote @function(name: 'MyCustomFunction')
}
```

if that would do it, and what the differences are between @function and the link I shared above for custom resolvers with lambda functions.

**Comment by yuth** [comment]
@VicFrolov the graphql-transformer does not support `@auth` owner rules in a function. Only supported rules for `@auth` in a `@function` is static groups.

A workaround would be to create custom mutation and have auth check in the lambda function. The `@connection` and `@searchable` should work without any additional code as searchable work out of DynamoDB streams, and `@connection` creates additional additional field level resolver

```gql
input CreateNoteInput {
  id: ID
  content: String!
  userID: ID!
}

type Mutation {
    createNoteWithCustomLogic(input: CreateNoteInput!): Note
        @function(name: "MyCustomFunction")
}
```

Your lambda function should have acces to current users identity inside `event.identity['username']` or `event.identity['sub']` which you can use to insert into the record.

**Comment by renebrandel** [comment]
Hi - we've now built in the ability to slot in your own custom logic in between Amplify-generated resolvers. Let me know if this addresses your concerns: https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers

**Comment by renebrandel** [comment]
@-mention if it doesn't. Happy to re-open. Thank you for filing the original issue!
