### ISSUE TITLE
Is there a simple way to update a custom resolver previously created with AppSync console? 

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-cli#3635]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
API

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.14.1

**What AWS Services are you utilizing?**
API, Auth

**Provide additional details e.g. code snippets**

I attached an Aurora datasource to a `getTodos` resolver via AppSync following these instructions: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html.
I find it daunting to keep writing my business logic in the console plus I want to version control the resolvers code. 

I learnt from Amplify docs that I can place the code of my resolver in `/resolvers/Query.getTodos.req.vtl`. I was expecting that running amplify push would override the console resolver code but it didn't happen. 

I suspect that because I need to update the stacks/CustomResources.json. Is that the case?
If so isn't that too much code/steps for a simple task (against the philosophy of Amplify)? 
Given that AppSync is aware of the stacks, can't the CLI reuse/pull that data?

**Comment by yuth** [comment]
> I suspect that because I need to update the stacks/CustomResources.json. Is that the case?
> If so isn't that too much code/steps for a simple task (against the philosophy of Amplify)?
> Given that AppSync is aware of the stacks, can't the CLI reuse/pull that data?

Amplify CLI is capable of using the resolver from this folder if its used in along with `@model` directive. But if its used with RDS, then we CLI does not have understanding of your schema or how the resolvers are named. 

CLI does support importing existing data schema from [RDS](https://aws-amplify.github.io/docs/cli-toolchain/graphql#relational-databases) and generates the necessary CloudFormation files and creates the resolver templates. Once its imported, these resolver templates can be maintained in version control

**Comment by mdegrees** [comment]
Thanks @yuth for the quick answer. In fact, at first, I went off to create an RDS data source from the CLI with `amplify api add-graphql-datasource` but realized that amplify asks for a database to do the @model scaffolding. The app I'm building is a multi-tenant with a tenant per database so I had to break free from @model. 

So I'm left off with the option of creating custom resolvers. And from what I understand adding custom resolvers would entail declaring them in the /stacks. I can imagine how complex that would get with a 100+ resolver. The only elegant option I can think of is using lambda resolvers. 

is there is a solution I'm not aware of?

**Comment by yuth** [comment]
> I went off to create an RDS data source from the CLI with `amplify api add-graphql-datasource` but realized that amplify asks for a database to do the @model scaffolding. The app I'm building is a multi-tenant with a tenant per database so I had to break free from @model.

When an RDS data source is imported, Amplify CLI does not use `@model` directive. It looks at the tables in in RDS and creates types based on the columns in the table, and generate CRUDL resolvers for the tables. The generated resolvers are pretty basic but these resolvers are static (unlike DynamoDB based one where tables are managed by Amplify CLI) and encouraged to be edited based on the application requirements.

**Comment by mdegrees** [comment]
Ah I see. So any chances Amplify will support multi-tenant? the only multi-tenant architecture possible right now is adding a tenantId as a row for tables. Any chances that Amplify supports multi databases or table prefixing? browsing the issues it's a recurrent use case where it becomes inevitable to "eject" the scaffolding.

**Comment by mdegrees** [comment]
#3654
