### ISSUE TITLE
Why are all API Gateway names the same?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#3636]
I have a REST API endpoint setup through amplify cli. One for prod, and I just added another env for development. The API Gateway names however are exactly the same making it hard to distinguish which is which in the AWS Console. Why don't you name them differently like you do with lambda functions? Why not add something to the description. 

See screenshot - I blurred out some things though: 

<img width="774" alt="API Gateway 2020-03-10 14-16-21" src="https://user-images.githubusercontent.com/81853/76355353-c2921400-62d9-11ea-9b28-f9d3f82799c6.png">

**Which Category is your question related to?**
api

**Amplify CLI Version** 
4.16.1

**What AWS Services are you utilizing?**
API Gateway

**Provide additional details e.g. code snippets**

**Comment by yuth** [comment]
@hisham thanks for the suggestion. I have added this to our backlog

**Comment by kaustavghosh06** [comment]
@hisham For API Gateway we keep the API name the same but change the "stage" name for the API based on your environment. This was a design decision which was made at the start. Would it be possible to view the stage name on the console to differentiate between the environments?

**Comment by hisham** [comment]
I see. Ok thanks for the clarification.

**Comment by smakinson** [comment]
@hisham I agree it would be nice to be able to see the stage name in the list since the api names are identical.

**Comment by hisham** [comment]
@kaustavghosh06 if you guys implement `amplify api console` that would mitigate this a bit. Currently this command returns 'Opening console functionality not available for this option`
