### ISSUE TITLE
[ANGULAR] Is aws-export.js content sensible ?

### ISSUE THREAD

**Issue by KrustyHack** [aws-amplify/amplify-cli#3639]
**Which Category is your question related to?**
- angular
- amplify
- configuration

**Amplify CLI Version** 

4.13.4

**What AWS Services are you utilizing?**
- Amplify
- AppSync
- Lambda

**Provide additional details e.g. code snippets**

Maybe stupid question : is aws-export.js a sensible file ?

Currently I need to manually configure Amplify :

`Amplify.configure({MYCONFIG});` in main.ts

And this file is in my git repo.

That's why I'm asking if content is sensible or not.

Thanks !

**Comment by yuth** [comment]
Amplify CLI generates this file based on the categories  that are added in your project. This file is not added to your git repository as this file is considered as a runtime file by the CLI.

> Currently I need to manually configure Amplify :
Amplify.configure({MYCONFIG}); in main.ts

Amplify Javascript libs are can be used in a project where CLI is not used. This allows the library to work with out neededing know about the Amplify CLI

**Comment by KrustyHack** [comment]
Ay,

Thanks. So it's not a sensible file, right ?

**Comment by yuth** [comment]
Do you mean sensitive? The data in the `aws-export.js` is not treated as sensitive, but should not be checked into your git repository

**Comment by KrustyHack** [comment]
Ay,

Yes sensitive sorry. :p

Mh so I will see how I can do that because actually I don't use aws-export.js but a manually crafter main.ts file :

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import Amplify from 'aws-amplify';
Amplify.configure({ALL MY CONFIG HERE});

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));

```
