### ISSUE TITLE
Sync data from Aurora Serverless to Elasticsearch

### ISSUE THREAD

**Issue by davegariepy** [aws-amplify/amplify-cli#3640]
** Which Category is your question related to? **
data sources, `@searchable` graphql transform
** What AWS Services are you utilizing? **
Aurora Serverless, ElasticSearch

I would like to sync data from Aurora Serverless to Elasticsearch for text based search by users. It seems like Dynamodb does this automatically, but how would this be done with Aurora Serverless?

Thanks

**Comment by yuth** [comment]
Amplify CLI does not have support for ElasticSearch support for Aurora Serverless. In case of DynamoDB, the data modelling and creation of the tables are managed Amplify CLI as defibed by the GraphQL Schema. When you import Aurora Serverless, the schema is generated based on the Database schema. CLI does not have support for any directives for the imported data source.

I am going to mark this as a feature request, and add it to our backlog
