### ISSUE TITLE
Axios external REST calls in API Lambda with express hanging

### ISSUE THREAD

**Issue by skyride99** [aws-amplify/amplify-cli#3645]
I am using express service. Sometimes I need to make an external call to another server. Using Axios the call never returns.

```
axios.post(PROFILE, {}, {headers: {
    'Authorization': req.headers.authorization,
    'Content-Type' : 'application/json',
    "Accept": "application/json"
  }}).then(response => {
    console.log('inside with data ', response.data.response)
    res.json({success: 'get call succeed!', data: 'test2'})
  })
```

**Comment by skyride99** [comment]
However I can make the same call in a regular lambda function.

**Comment by yuth** [comment]
Is there a specific error you get if you have a `.catch()` handler

**Comment by skyride99** [comment]
It continues for 30 seconds and then time out. Catch never gets hit.
The same code works inside a regular lambda function without express. 
```
app.get('/test2', function(req, res) {
  axios.post(PROFILE, {}, {headers: {
    'Authorization': req.headers.authorization,
    'Content-Type' : 'application/json',
    "Accept": "application/json"
  }}).then(response => {
    console.log('inside with data ', response.data.response)
    res.json({success: 'get call succeed!', data: 'test2'})
  }).catch(err => {
    console.log(err)
    res.json({success: 'get call failed', data: 'test2'})
  })
});
```

**Comment by kaustavghosh06** [comment]
@skyride99 It would be hard to debug a lambda  code remotely - if you've added any custom logic to it. We can take a stab at it if you send your amplify folder to amplify-cli@amazon.com

**Comment by skyride99** [comment]
I figured it out. I am using DAX and the service is in a VPC.
