### ISSUE TITLE
provider: userPools does not add @aws_cognito_user_pools to user schema

### ISSUE THREAD

**Issue by isaiahtaylor** [aws-amplify/amplify-cli#3647]
**Describe the bug**
Adding `@auth(rules: [{allow: private, provider: userPools, operations: [create, update, delete, read]}])` to the schema and running `amplify api gql-compile` does not add the `@aws_cognito_user_pools` directives to the compiled schema as expected.

**Amplify CLI Version**
4.13.4

**To Reproduce**
Add `@auth(rules: [{allow: private, provider: userPools, operations: [create, update, delete, read]}])` to a type in your schema and run `amplify api gql-compile`. Check `amplify/backend/api/frontendapi/build/schema.graphql`, no references to `@aws_cognito_user_pools`.

**Expected behavior**
Expected `provider: userPools` to add `@aws_cognito_user_pools` directives to the generated schema.

**Additional context**
I assumed https://github.com/aws-amplify/amplify-cli/pull/1916 would provide this behavior.

**Comment by yuth** [comment]
Is Cognito the default auth provider for your API? Amplify CLI does not add default auth provider directive in the output schema

**Comment by kaustavghosh06** [comment]
@isaiahtaylor Closing this issue. Let us know if you're still facing issues after deployment.
