### ISSUE TITLE
Amplify publish doesn't update s3 or cloudfront

### ISSUE THREAD

**Issue by braganic** [aws-amplify/amplify-cli#3648]
**Describe the bug**
Amplify publish or amplify publish -c doesn't update code changes on s3 or cloudfront. I've even tried changing env and returning but no luck

**Amplify CLI Version**
4.13.4

**To Reproduce**
Add hosting (Cloudfront) 
Publish
Make code changes
Publish again = doesn't reflect changes

**Expected behavior**
Updated code should appear on s3 / cloudfront but it doesn't

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version. 10.15.3

**Comment by kaustavghosh06** [comment]
@braganic What's you check you `amplify/.config/project-config.json` file and see if the Source and Distribution directories are set to correct paths?

It should look something like this:

```json
 "javascript": {
        "framework": "none",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm run-script start"
        }
    }

```

**Comment by braganic** [comment]
Hi K, thanks for your reply, it's set correctly

    "javascript": {
        "framework": "react",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "build",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm run-script start"
        }
    },

**Comment by UnleashedMind** [comment]
I guess you've chosen the PROD configuration to use S3 and Cloudfront when you ran `amplify hosting add`?
`amplify publish -c`  uploads the update frontend build artifacts (in the distribution folder), and sends an invalidation requests to the CloudFront, if your project is big, it can still take a while for the CloudFront to update its caches. 

If you suspect that something is wrong, check these to get at which point it went wrong: 
1. in the distribution folder, check that your build artifacts reflect what you have updated, If not, then it means the frontend build command hasn't been correctly set or invoked
2. go to the S3 console and find the hosting bucket, you can find the bucket name in `amplify/backend/amplify-meta.json` `hosting.S3AndCloudFront.output.HostingBucketName`. check the files there are the same as updated build artifacts in the distribution folder.

**Comment by braganic** [comment]
Thank you @UnleashedMind . Build command works properly, and builds updated code. 
The issue appears when uploading this code to the s3, which never happens. Last update to s3 was 2 days ago. Any idea what might be happening? Again, the first amplify publish works, it's the next ones that don't upload anything (they do build)

**Comment by UnleashedMind** [comment]
I just tried using the latest of the Amplify CLI (v.4.16.1) and I was not able to reproduce. 
Both new files and updated files are uploaded to the S3 hosting bucket. 

We've seen some customers misconfigure the CLI, like specifying the distribution directory to be "build", but it's actually "dist". Please double check on those details. 

When you configure the CLI to use both S3 and CloudFront, you won't be able to directly access the files' contents in the hosting bucket, you can see them in the bucket, but you will need to download it to view their contents.

CloudFront can take a long time to build and refresh its caches.

On some of your comments:

-  "The issue appears when uploading this code to the s3, which never happens."
Could you add a dummy file to the **root** of the distribution directory,  like "checkupload.html" with some plain text in it,  and execute `amplify publish -c` to see if it's uploaded? 

- "Last update to s3 was 2 days ago. " 
Just to avoid any misunderstanding between us, I want to mention that the S3 hosting bucket itself does get updated, only its content gets updated.

**Comment by braganic** [comment]
did a new amplify init and now its working
thanks for your help

**Comment by vikmn** [comment]
I am doing a publish using the amplify and it does say that the app has been published but when i navigate to the cloudfront url i am provided with , i seem to get an access denied error
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DKEY8Y1YCZ1YEQ7T</RequestId>
<HostId>d+pKE2hMdtbRbgnfiTKWzK0oxr2i9823iAc/JcHKFX3v8ErdJtk4svKRnZj+foqRLhvD01sGuqM=</HostId>
</Error>
Any ideas whats missing on my configuration?
