### ISSUE TITLE
`amplify pull` not pulling down Cognito user pool trigger data

### ISSUE THREAD

**Issue by fi5u** [aws-amplify/amplify-cli#3653]
**Describe the bug**
In the _Triggers_ settings in Cognito User Pools, I have set a trigger to one of my Lambda functions. After running `amplify pull`, it does not pull down the trigger settings to my local code. When I do the opposite, and `amplify push` with an empty `triggers` object in _parameters.json_, it overwrites the previously selected setting in the User Pool trigger section and nullifies it.

**Amplify CLI Version**
4.16.1

**To Reproduce**
In _amplify > backend > auth > [id] > parameters.json_ ensure the _triggers_ object is empty. On the Cognito console, under triggers settings, select a Lambda function as a trigger. Run `amplify pull`.

**Expected behavior**
The triggers object is populated locally with data about the Lambda function to trigger.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.14.1

**Comment by yuth** [comment]
Amplify CLI uses cloudformation to provision resources, does not support syncing of the changes that are made using the Console. All the changes have to be pushed using CloudFormation and `push` operation should be done using Amplify CLI for `pull` command to get that change

**Comment by fi5u** [comment]
Thanks, although I don't fully understand. So I'm able to `amplify push` trigger settings for Cognito set in _paramters.json_, but `amplify pull` won't pull those same setting back to the local environment?

My aim is to define all settings not in the console, but in my code. I only wanted to `pull` the trigger settings so I can see what the syntax is like. Is the example json [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-identity-pools-working-with-aws-lambda-trigger-sources) what I should use to configure a trigger from _parameters.json_? If so, I'm a little confused where I identify which Lambda function to call (is it `callerContext.clientId`?). Should the `request` object be empty, since Cognito would fill that in? If I'm looking in the wrong place, do you have a link to the documentation for the `triggers` object in _parameters.json_? Thanks.

**Comment by kaustavghosh06** [comment]
@fi5u Sorry for the late response, but `amplify pull` wouldn't be able to pull in changes made from the cognito console. `amplify pull` helps in bringing down CloudFormation stack changes made by another team-member (if there are multiple devs working on the project). You can configure cognito triggers using the amplify add/update flow.
