### ISSUE TITLE
Unable to add AWS Amplify categories after updating to CLI version 4.16.1

### ISSUE THREAD

**Issue by Jay2113** [aws-amplify/amplify-cli#3658]
**Describe the bug**
I was initially having issues using the Node 8.x runtime and amplify-cli recommended me to update to node 10.x or higher, so I updated Node to the latest 12.x runtime but it was not being reflected and the issues persisted. I updated amplify-cli to the latest version that is 4.16.1 to ensure that the updated Node runtime is reflected. After updating to the latest versions, amplify init works fine but when I try adding a new category such as:

amplify add auth
I receive the following error:

<img width="1126" alt="amplify-auth-error" src="https://user-images.githubusercontent.com/38470430/76571033-f8c3c500-648c-11ea-91bf-06e69aafe45c.png">

amplify add api
I receive the following error:

<img width="1120" alt="amplify-api-error" src="https://user-images.githubusercontent.com/38470430/76571070-07aa7780-648d-11ea-82fc-ceea9dfe5189.png">

**Amplify CLI Version**
4.16.1

**To Reproduce**
Create a new basic iOS App, initialize Amplify, and add a new category using the following command:

cd $Project_Directory
amplify init
amplify add auth / amplify add api

**Expected behavior**
Add an authentication backend by setting up an Amazon Cognito User Pool to act as the backend for letting users sign up and sign in.

**Screenshots**
<img width="1126" alt="amplify-auth-error" src="https://user-images.githubusercontent.com/38470430/76574946-311ad180-6494-11ea-8aba-23841948b78f.png">

<img width="1120" alt="amplify-api-error" src="https://user-images.githubusercontent.com/38470430/76574954-3546ef00-6494-11ea-8be4-6c9d7715042b.png">

**Desktop:**
- OS: Mac
- Node Version: 12.2.0
- NPM Version: 6.9.0

**Comment by yuth** [comment]
@Jay2113 this might be related to outdated ESM cache. Could you try evicting the ESM cache. It should be located inside the node_modules folder of Amplify CLI

You could use the following command to clean it up
```sh
cd "$(npm -g prefix)/lib/node_modules/@aws-amplify/cli/node_modules/.cache"
rm -rf esm
```

**Comment by kaustavghosh06** [comment]
Also, did you use yarn or npm to install the CLI?

**Comment by Jay2113** [comment]
Yes, evicting the ESM cache worked!! I used npm to install the CLI. Thank you for the quick response.
