### ISSUE TITLE
amplify push dry run?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#366]
** Which Category is your question related to? **
deployment for all categories

Is there a way to do a dry run of 'amplify push' to see what changes it would make without actually doing anything? I understand CloudFormation supports something like this through change sets. Does amplify expose this somehow?

**Comment by kaustavghosh06** [comment]
@hisham What other information do you think would be valuable to you before pushing local configurations to the cloud? 
The `amplify status` command does provide an overview of whats getting created/updated/deleted with your next push but would like to know better about the specific needs.

**Comment by denissabramovs** [comment]
Same here, would like to know if some resource will be deleted and re-created...

**Comment by renebrandel** [comment]
Hi @hisham @denissabramovs - we've now launched the ability to use `amplify status -v` to give you a "cdk diff"-like experience. It'll indicate every single resource change. LMK if this is addresses your concern. If not, @mention me, and let's discuss further!
