### ISSUE TITLE
Removing a field from dynamodb doesn't remove it from elasticsearch

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#3660]
This is for an @searchable model

So if you create something like

```gql
@model
@searchable
Listing {
  featuredAt: String
}
```

And then you create an object of that model with a featuredAt date string, everything works just fine in search query like this:

````gql
featuredAt: {
              exists: true
            },
````

But then if you update the dynamo data and remove "featuredAt", the featuredAt data from elastic search is not removed and you still get the item returned in search queries

**Comment by yuth** [comment]
@CodySwannGT does the search filter that you have option to filter based on the value of `featuredAt`? Or is the issue that `featuredAt` remains in the Elastic Search cluster?

**Comment by CodySwannGT** [comment]
The issue is that ``featuredAt`` remains in the cluster.
Subsequently, when I run queries against the data set in Dynamo, ``featuredAt`` is null. But when I query against ES, it is not.

**Comment by kaustavghosh06** [comment]
@CodySwannGT What's the version of the CLI that you used to push your changes?

**Comment by CodySwannGT** [comment]
4.13.1

**Comment by SwaySway** [comment]
Hi @CodySwannGT 
Are you still experiencing this issue?
I was not able to reproduce, with 4.13.1 and latest.
I tried to reproduce with this schema:
```gql
type Post @model @searchable {
	id: ID!
	title: String!
	tag: String
	createdAt: AWSDate
	updatedAt: AWSDate
} 
```
I used tag is the field I set to null and it removed it from from table and the index as well.

**Comment by CodySwannGT** [comment]
Hey @SwaySway 

[This was actually the culprit](https://aws-amplify.github.io/docs/cli-toolchain/graphql#migration-warning)

Although, I didn't figure that out before I deleted the who ES index and recreated it.
