### ISSUE TITLE
Concurrent Subscription limit for Amplify GraphQL client

### ISSUE THREAD

**Issue by montycheese** [aws-amplify/amplify-cli#3671]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.10.0

**What AWS Services are you utilizing?**

Amplify Stack with a GraphQL based backend.

**Provide additional details e.g. code snippets**

What AWS services does the amplify GraphQL API client use under the hood? I ask because I'm curious to know if there is a hard limit on the number of concurrent subscriptions across all clients using GraphQL based APIs that were created through amplify.

The service I'm creating is expecting to have anywhere from 1000's to 100,000's of concurrent users.

Thanks.

**Comment by undefobj** [comment]
Amplify uses [AWS AppSync](https://aws.amazon.com/appsync/) as the managed GraphQL service, which has default limits published in your account [Service Quotas page](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html).

You should always do your own benchmarking however there are some numbers on the AppSync subscriptions shown in this blog post: https://aws.amazon.com/blogs/mobile/appsync-realtime/
