### ISSUE TITLE
Push Failing. Referencing Deleted Resource

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#3673]
**Describe the bug**
I was trying to add an api route to my REST api using a custom lambda. I was getting errors pushing it (a whole other story. Still don't know why). So I did an amplify pull to get back to the current setup. Then when I try to update another service to test the push. I'm getting errors referencing that API resource. But when I do amplify update api the route doesn't show up. Not sure what I should do. Don't want to just start deleting things from the console because I'm worried it will break things.
**Amplify CLI Version**
4.16.1
**To Reproduce**
create an api route that somehow fails on push
do amplify pull
try to update something else and then push again
**Expected behavior**
The api route should no longer be part of the project. because it unsuccessfully pushed the first time and then no longer exists locally.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Additional context**

**Comment by UnleashedMind** [comment]
@julien-tamade 

Could you go to the Cloudformation console, and check if the nested stack of your REST API is in a Failed state? that's probably preventing you from updating it.

**Comment by julien-tamade** [comment]
@UnleashedMind the status for the rest api is UPDATE_ROLLBACK_COMPLETE. Also on a side note, when I checkout another branch and run amplify pull, the API gateway endpoint in the amplifyconfiguration.json doesn't change, which is an issue when generated thing new api gateway generated code form my swift project.

**Comment by kaustavghosh06** [comment]
amplify pull will only pull in changes if your deployment is successful. Do you see all the routes in your API Gateway console which you configured using the CLI before the push failed?

**Comment by kaustavghosh06** [comment]
Closing due to lack of requested information. Please comment on this thread if you're still stuck.
