### ISSUE TITLE
Custom Resolvers (seemingly) incompatible with @auth directive.

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-cli#3682]
**Describe the bug**
It would appear that there's no way to affect the permissions of a custom resolver via the @auth directive, or via a custom stack.

**Amplify CLI Version**
4.16.1

**To Reproduce**
1. have a custom resolver with it's own `.stack` file (as described in the docs)
1. Add an `@auth` directive to say allow IAM & Cognito auth
1. Get an error that you can only have one type of resolver per field

**Expected behavior**
1. Either the above works magically -OR-
1. Pass the `authRoleName` and `unauthRoleName` into the custom resolver

**Additional context**
I've got custom resolvers (that look up an object via two fields and require a match, instead of one).

These resolvers map onto a query in my schema. I want to automatically create the policy that would allow public access to these fields. The @auth directive was my first go, but that caused an error because my custom resolver stack was defining a resolver, and @auth was trying to define another one.

I also can't do the auth myself in my custom resolver, because the auth roles aren't passed in. This should be a simple fix to just pass the auth roles in as params when generating the cf-template.

**Comment by kaustavghosh06** [comment]
@nagey Could you share with us a sample schema as to how you're setting this @auth directive?

**Comment by nagey** [comment]
the schema context was along the lines of:

```
type Query {
  myCustomResolvedQuery(id: ID!, nonce: String!): SomeObject @aws_iam @aws_cognito_pools @auth(rules:[{ allow: public, provider: iam }])
```

This very much doesn't work. We are setting up the resolver for `myCustomResolvedQuery` in a custom stack in the `stacks` directory.

Thinking about this, and reading through the code, I don't believe that my option 1 for expected behavior is viable, and that the #2 is the only possible way to make it happen.

If we had the auth & unauth role names in the custom stack as parameters (they're not currently passed it would seem), then we could manually define the IAM policies for them.

**Comment by SwaySway** [comment]
Hello @nagey 
Are you still experiencing issues with
Did you add the resolver cfn portion inside CustomResources.json?
I tested this on 4.16.1 and the latest version of the CLI and it generated a policy for the unauth role to access the query. It also passed the `@aws_cognito_user_pools`.

Schema I used
```gql
type Post {
	id: ID!
	title: String!
	tag: String
	createdAt: AWSDate
	updatedAt: AWSDate
}
# the resolver would read from posts from another table that has posts.
type Query {
	customGet(id: ID!): Post @aws_cognito_user_pools @auth(rules: [{ allow: public, provider: iam }])
} 
```
