### ISSUE TITLE
New directive @trigger for GraphQL Transform

### ISSUE THREAD

**Issue by lexfaraday** [aws-amplify/amplify-cli#3684]
**Is your feature request related to a problem? Please describe.**
When using the "amplify add api" command I can't to attach a lambda trigger to insert/update actions for the DynamoDB table generated from the scheme with the GraphQL Transform way. Now I'm attaching the lambda manually from AWS Console.

**Describe the solution you'd like**
Could be helpful to add a functionality like the @function in the GraphQL scheme in order to attach a lambda for the insert/update actions, here is an example:

type TableExample @model @key(fields: ["id"])
  @auth(rules: [ { allow: owner ownerField: "owner" operations: [create, read, update, delete] } ]) 
 **@trigger(name: "ThisGeneratesALambdaAttachedToThisTable")**
{
  id: String!
  alias: String
}

If the trigger already exists, just attach it, if not create and attach an empty lambda template.

**Describe alternatives you've considered**
amplify add function

**Additional context**
If I create a DynamoDB table with "amplify add storage" I can attach a lambda to this table, but the generated table from "amplify add api" I can't.

**Comment by undefobj** [comment]
@lexfaraday We recently added this capability here can you check it out? https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation

**Comment by lexfaraday** [comment]
@undefobj Which version I should to use? I've updated with "yarn upgrade", but I can't see the "Lambda Trigger" option within this version:

─ @aws-amplify/analytics@1.4.3
├─ @aws-amplify/api@1.3.3
├─ @aws-amplify/interactions@1.2.3
├─ @aws-amplify/predictions@1.2.3
├─ @aws-amplify/pubsub@1.3.3
├─ @aws-amplify/ui@1.2.3
├─ @aws-amplify/xr@0.3.3
├─ @aws-crypto/crc32@0.1.0
├─ @aws-sdk/eventstream-marshaller@0.1.0-preview.2
├─ @aws-sdk/is-array-buffer@0.1.0-preview.1
├─ @aws-sdk/types@0.1.0-preview.1
├─ @aws-sdk/util-buffer-from@0.1.0-preview.1
├─ @aws-sdk/util-hex-encoding@0.1.0-preview.1
├─ @aws-sdk/util-utf8-node@0.1.0-preview.1

With this option from "amplify add function" I think is enough, but could be more clear to have a complete scheme with each resource used by the Graphql model, this could helps to new coming developer for the project maintaining.

Thanks!!!

**Comment by kaustavghosh06** [comment]
@lexfaraday Thanks for the recommendation.  We'll look for more community interest on this before implementing.
