### ISSUE TITLE
add auth - SNS IAM role duplicated when project name contains a hyphen "-"

### ISSUE THREAD

**Issue by edwardsray** [aws-amplify/amplify-cli#3687]
**Describe the bug**
Recent code change assumes project name does not contain a hyphen.
#2709
Commit: fe0e979812bd3142a56a62bf15444cbb3dbbb6bb
File: auth-template.yml.ejs
Code:      RoleName: !If [ShouldNotCreateEnvResources, '<%=`${props.resourceNameTruncated}_sns-role`%>', !Join ['',[ 'sns', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]

The Select assumes the Split has three parts. With the hyphen involved in the project name the random id looked for selects the environment, which creates a duplicate SNS role name. Duplicated from another project with the same environment.

The use case is create-react-app which doesn't allow capital letters in the project name, so a hyphen was used. The default project name for amplify init then had a hyphen. 

**Amplify CLI Version**
4.16.1

**To Reproduce**
create two directories:
project-1
project-2
In each "amplify init", take the default and give them the same environment.
In each "amplify add auth", take the defaults, amplify push -y

**Expected behavior**
The second push would succeed without issue.

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows
Node Version:12.14.0

**Additional context**

**Comment by clodal** [comment]
I am also facing this issue. Without the hyphen it works fine.

**Comment by superjova** [comment]
Also experiencing the same thing with a hyphen in the project name

**Comment by domezi** [comment]
Same problem. Creating a new project without hyphens fixed it for me.

**Comment by christensen143** [comment]
I see this is closed but thought I would chime in on a simpler solution. I did the following:

1) Deleted the Amplify folder in my project
2) When to the Amplify console and got the command to amplify pull --appId <appId> --envName <envName> from the backend tab.
3) Ran the command which reinitialized my project.
4) Pushed for a build

This is a bit nicer than starting a new project without hyphens which may not be a choice for some.
