### ISSUE TITLE
write EPROTO 4592985536:error:1408F10B

### ISSUE THREAD

**Issue by daltlc** [aws-amplify/amplify-cli#3688]
I cannot push a simple built Amplify/ React project successfully to the cloud. I have tried multiple times, making sure I am up to date on Amplify CLI, Node, NPM and Expo. 

I had 2 projects that worked fine yesterday and now today, I am getting this error. I have tried fresh projects multiple times. 

I have cleared every API within AppSync.
Cleared all tabled in DynamoDB.
Deleted all Cognito groups.
Deleted all S3 buckets.

I do as the following:

expo init newProject

Navigate to project and run amplify init ( I have already done amplify configure and have my profile there correctly)

After that is done I run amplify add api > API key > Single Object with fields

That all runs successfully, then I run amplify push.

This is what I get from there. The schema groups and tables are created on the console but does not create any mutation, queries within project and also has this error. 

bash-5.0$ amplify push
Scanning for plugins...
Plugin scan successful
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | demoshare     | Create    | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - Todo
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth 

GraphQL schema compiled successfully.

Edit your schema at /Users/DaltonCarr/Desktop/DC/Projects/demoShare/amplify/backend/api/demoshare/schema.graphql or place .graphql files in a directory at /Users/DaltonCarr/Desktop/DC/Projects/demoShare/amplify/backend/api/demoshare/schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS apidemoshare                 AWS::CloudFormation::Stack Tue Mar 17 2020 15:05:57 GMT-0700 (Pacific Daylight Time)               
UPDATE_IN_PROGRESS amplify-demoshare-dev-135132 AWS::CloudFormation::Stack Tue Mar 17 2020 15:05:53 GMT-0700 (Pacific Daylight Time) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-demoshare-dev-135132-apidemoshare-1SQ1ZJ8QYR5FZ AWS::CloudFormation::Stack Tue Mar 17 2020 15:05:58 GMT-0700 (Pacific Daylight Time) User Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    Todo AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:05 GMT-0700 (Pacific Daylight Time) 
UPDATE_IN_PROGRESS Todo AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:05 GMT-0700 (Pacific Daylight Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    CustomResourcesjson AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:13 GMT-0700 (Pacific Daylight Time) 
UPDATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:12 GMT-0700 (Pacific Daylight Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    GraphQLAPIKey AWS::AppSync::ApiKey Tue Mar 17 2020 15:06:23 GMT-0700 (Pacific Daylight Time) 
UPDATE_IN_PROGRESS GraphQLAPIKey AWS::AppSync::ApiKey Tue Mar 17 2020 15:06:22 GMT-0700 (Pacific Daylight Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-demoshare-dev-135132-apidemoshare-1SQ1ZJ8QYR5FZ AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:26 GMT-0700 (Pacific Daylight Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE apidemoshare AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:32 GMT-0700 (Pacific Daylight Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-demoshare-dev-135132 AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:34 GMT-0700 (Pacific Daylight Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE amplify-demoshare-dev-135132 AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:46 GMT-0700 (Pacific Daylight Time) 
UPDATE_COMPLETE apidemoshare                 AWS::CloudFormation::Stack Tue Mar 17 2020 15:06:46 GMT-0700 (Pacific Daylight Time) 
✖ An error occurred when pushing the resources to the cloud

write EPROTO 4592985536:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

An error occured during the push operation: write EPROTO 4592985536:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

**Amplify CLI Version**
4.16.1

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.6
 - Node Version: 11.10.1 I have tried 12.6 as well.  

I have restarted my machine, deleted all node packages, uninstall amplify and re installed.

**Comment by daltlc** [comment]
I understand this would be a https to http issue between client and server but not sure where that could be going wrong with basic setup.

**Comment by UnleashedMind** [comment]
"This is what I get from there. The schema groups and tables are created on the console but does not create any mutation, queries within project and also has this error." 
Queries and Mutations are only generated on your local project after a success push, seems like the error occurred right there when the CLI tries to call the serve to retrieve the schema and then use it for the codegen. 

Are you running the CLI behind a proxy? Have you check on this thread: 
https://npm.community/t/ssl-routineswrong-version-number/6048

**Comment by daltlc** [comment]
I am not running a proxy. I created an entirely new aws account, did the same steps and everything worked fine, so it's something within the console. I believe I cleared out anything that could be creating conflicts with that.

**Comment by UnleashedMind** [comment]
@daltlc 
I'm going to close the issue if you are not blocked anymore. 
let me know if you want this to be open again.
