### ISSUE TITLE
Can't access DynamoDB tables created by GraphQL API on a new lambda function

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#3693]
**Describe the bug**
Whenever creating a new lambda function using `amplify add function` or adding a REST API using `amplify add api` and choosing REST, the CLI asks for a function template to use, and when I choose `CRUD function for Amazon DynamoDB table (Integration with Amazon API Gateway and Amazon
DynamoDB)` and I try to use existing DynamoDB tables, it says there aren't any tables. I guess you could use #2463 in order to make it work for creating lambda functions for accessing tables, and not just triggers for tables.

**To Reproduce**
`amplify add api`, choose `GraphQL`, create some `@model`s, then `amplify add api`, choose `REST`, and use `CRUD function for Amazon DynamoDB table (Integration with Amazon API Gateway and Amazon
DynamoDB)` as template, select `DynamoDB table configured in the current Amplify project` and you get an error.

**Expected behavior**
The user should be able to see a list of all tables, also tables created using the `@model` directive on the GraphQL schema

**Comment by UnleashedMind** [comment]
I will mark this as an enhancement. 
In the current implementation, only DynamoDB tables created using the amplify storage category is checked.

**Comment by iShavgula** [comment]
I'm using amplify version 4.16.1 and this works for me.

**Comment by idanlo** [comment]
@iShavgula Are you sure? can you share a screenshot of a lambda function creation with access to DynamoDB tables created by AppSync?

**Comment by iShavgula** [comment]
<img width="1027" alt="Capture d’écran 2020-03-20 à 13 02 06" src="https://user-images.githubusercontent.com/6018680/77161916-0e4b7700-6aab-11ea-8bcf-b56e77d74cec.png">

**Comment by idanlo** [comment]
@iShavgula That's amazing, I didn't know it was in the storage category. This helps a lot, I was doing it manually until now. Weird how @UnleashedMind marked this as an enhancement if it already exists

**Comment by idanlo** [comment]
@iShavgula I tried doing this all along, guess I needed to create a `Hello World` function
![image](https://user-images.githubusercontent.com/28350511/77162202-122fc700-6ab4-11ea-9e4f-99859329572c.png)

**Comment by iShavgula** [comment]
@idanlo it has not been long time since it’s available, maybe couple of days.

**Comment by davidhgray** [comment]
i would also like to see this functionality described by @idanlo.  i have an IoT device that can only write a REST API (i.e., POST), but i want to be able to read that data on a mobile device using AppSync/GraphQL.  so two different APIs (GQL and REST) need to be able to talk to the same DynamoDB.  i created the DB using "amplify create api" > "graphql ", and now need to create a REST API that points to that @model-created DB.

**Comment by idanlo** [comment]
@davidhgray look at the comments above, there is an image showing how to do that

**Comment by davidhgray** [comment]
for some reason, at the "select the category" step, when i select "storage", no DBs are shown to me.  it's as if the CLI is just skipping this step.  [
![Screenshot from 2020-07-13 01-15-51](https://user-images.githubusercontent.com/24255795/87273208-797be780-c4a6-11ea-8105-6bc6773802a9.png)
](url)

**Comment by idanlo** [comment]
@davidhgray maybe you should create a new issue, this one is already buried in the list and no one will see it if I re open

**Comment by ripley** [comment]
From the image you have not selected "storage" category. Need to press space when the item is highlighted to select.

> @idanlo for some reason, at the "select the category" step, when i select "storage", no DBs are shown to me. it's as if the CLI is just skipping this step. [ ![Screenshot from 2020-07-13 01-15-51](https://user-images.githubusercontent.com/24255795/87273208-797be780-c4a6-11ea-8105-6bc6773802a9.png) ](url)
