### ISSUE TITLE
cli generated group Role does not have Path

### ISSUE THREAD

**Issue by gwnoseworthy** [aws-amplify/amplify-cli#3695]
I am currently attempting to view IAM group roles that have been created and assigned via the amplify cli so that i can attach additional Policies, IAM API currently only allows for filtering via PathPrefix so i am unable to query resources without getting full list of IAM Roles on my account.

When using Amplify CLI to create a group role it creates an IAM Role to attach to the group.
This Role is generated as region-appid-groupnameRole

would like to see iam group role created as
prefix: region/appid
name: groupnameRole

alternatively the role name could remain the same and the prefix could be added.

this would allow for filtering of iam roles that have been generated by amplify cli using the PrefixPath parameter available to the IAM API ListRoles allowing for better external managment

**Comment by kaustavghosh06** [comment]
@gwnoseworthy the format is actually <userPoolID>-group<groupName>GroupRole
We took this decision for this format when we built this feature out. Changing this might break a bunch of existing customers and wouldn't recommend on doing that at this point. We'll keep your feedback in mind with our new features.
