### ISSUE TITLE
How to setup for sorting in a many-to-many relationship?

### ISSUE THREAD

**Issue by amirmishani** [aws-amplify/amplify-cli#3699]
**Which Category is your question related to?**
API. specifically GraphQL schema directives and many-to-many relationships

**Amplify CLI Version** 
4.16.0

**What AWS Services are you utilizing?**
Congnito, Appsync

**Provide additional details e.g. code snippets**
Looking at the [this example](https://github.com/aws-samples/aws-appsync-chat) from AWS to create a chat app and I find the need to sort User conversations by Conversation.updatedAt. User could potentially end up with thousands of conversations and I need to only query the latest 100 conversations and of course sort by the latest. Can this be done with the updated @auth directive and the newer way of setting up [many-to-many](https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage-2) relationships?

```graphql
type User 
  @model 
  @auth(rules: [{ allow: owner, ownerField: "id", queries: null }]) {
  id: ID!
  username: String!
  conversations: [ConvoLink] @connection(name: "UserLinks")
  messages: [Message] @connection(name: "UserMessages")
  createdAt: String
  updatedAt: String
}

type Conversation
  @model(
    mutations: { create: "createConvo" }
    queries: { get: "getConvo" }
    subscriptions: null
  )
  @auth(rules: [{ allow: owner, ownerField: "members" }]) {
  id: ID!
  messages: [Message] @connection(name: "ConvoMsgs", sortField: "createdAt")
  associated: [ConvoLink] @connection(name: "AssociatedLinks")
  name: String!
  members: [String!]!
  createdAt: String
  updatedAt: String
}

type Message 
  @model(subscriptions: null, queries: null) 
  @auth(rules: [{ allow: owner, ownerField: "authorId" }]) {
  id: ID!
  author: User @connection(name: "UserMessages", keyField: "authorId")
  authorId: String
  content: String!
  conversation: Conversation! @connection(name: "ConvoMsgs")
  messageConversationId: ID!
  createdAt: String
  updatedAt: String
}

type ConvoLink 
  @model(
    mutations: { create: "createConvoLink", update: "updateConvoLink" }
    queries: null
    subscriptions: null
  ) {
  id: ID!
  user: User! @connection(name: "UserLinks")
  convoLinkUserId: ID
  conversation: Conversation! @connection(name: "AssociatedLinks")
  convoLinkConversationId: ID!
  createdAt: String
  updatedAt: String
}
```

**Comment by RossWilliams** [comment]
To restate your issue in more generic terms: you need to sort a model by some value that only exists in an adjacent model. In your case sort conversation by the maximum updatedAt property on the list of messages.

There is a client-side and server-side solution to this, but you need to modify the updatedAt property on conversations when a message is inserted. The client-side solution is to make two mutations, one to create the message and another to update the conversation time stamp. The server-side solution is to use a DynamoDB stream trigger on the message table to run a custom lambda to update the conversation item’s updatedAt property. Amplify recently added updates to help setup the stream triggers for you.

Then you need a GSI on Conversation. Add a directive to the type @key(name: “byUserUpdated”, fields:[“owner”,”updatedAt”], queryField: “recentUserConversations”)

**Comment by jhockett** [comment]
Hi @amirmishani, I believe the answer to your question is yes, the use case is covered by the newer style @connection and @key directives. @RossWilliams posted a lot of good information, did you still have any questions?

I think a rough draft of the schema (barely tested) could look something like the following:
```graphql
type User
  @model
  @auth(rules: [{ allow: owner, ownerField: "id", queries: null }])
{
  id: ID!
  username: String!
  conversations: [ConvoLink] @connection(keyName: "byUserUpdated", fields: ["id"])
  messages: [Message] @connection(keyName: "userMsgs", fields: ["id"])
  createdAt: String!
  updatedAt: String!
}

type Conversation
  @model(
    mutations: { create: "createConvo" }
    queries: { get: "getConvo" }
    subscriptions: null
  )
  @auth(rules: [{ allow: owner, ownerField: "members" }])
{
  id: ID!
  messages: [Message] @connection(keyName: "convoMsgs", fields: ["id"])
  associated: [ConvoLink] @connection(keyName: "associatedLinks", fields: ["id"])
  name: String!
  members: [String!]!
  createdAt: String!
  updatedAt: String!
}

type Message
  @model(subscriptions: null, queries: null)
  @auth(rules: [
    { allow: owner, operations: [create, update, delete] }
  ])
  @key(name: "userMsgs", fields: ["authorId", "messageConversationId", "createdAt"])
  @key(name: "convoMsgs", fields: ["messageConversationId", "createdAt"]) {
  id: ID!
  author: User @connection(fields: ["authorId"])
  authorId: ID!
  content: String!
  conversation: Conversation! @connection(fields: ["messageConversationId"])
  messageConversationId: ID!
  createdAt: String!
  updatedAt: String!
}

type ConvoLink
  @model(
    mutations: { create: "createConvoLink", update: "updateConvoLink" }
    queries: null
    subscriptions: null
  )
  @key(name: "byUserUpdated", fields: ["convoLinkUserId", "updatedAt"])
  @key(name: "associatedLinks", fields: ["convoLinkConversationId"])
{
  id: ID!
  user: User! @connection(fields: ["convoLinkUserId"])
  convoLinkUserId: ID!
  conversation: Conversation! @connection(fields: ["convoLinkConversationId"])
  convoLinkConversationId: ID!
  createdAt: String!
  updatedAt: String!
}

type Subscription {
  onCreateConvoLink(convoLinkUserId: ID!): ConvoLink
    @aws_subscribe(mutations: ["createConvoLink"])
  onCreateMessage(messageConversationId: ID!): Message
    @aws_subscribe(mutations: ["createMessage"])
}
```

**Comment by jhockett** [comment]
Closing this for now @amirmishani. If you have additional issues or questions please comment below.
