### ISSUE TITLE
How to re-init existing project

### ISSUE THREAD

**Issue by jadbox** [aws-amplify/amplify-cli#37]
I've already set up a project in github that uses Amplify cli to create an Auth service. However when I pull down the project on another computer, running `init` again seem to create a new project. With awsmobile, I could run `awsmobile init my-project-id` to set up the project on a new machine. How do I reuse the same setup [in this case, a specific Cognito service] when pulling down my project on another machine?

Another related question, if I already have an existing Cognito service that I created manually, how could I tell amplify-cli to use it for the auth service?

**Comment by UnleashedMind** [comment]
Currently the amplify cli init does not have the ability to link to an existing backend project, so the `awsmobile init project-id` workflow is not available. 
Current the auth category does not allow you to use an existing cognito service that you configured on the console. 
I will mark these as feature requests.

**Comment by jadbox** [comment]
@UnleashedMind okay thanks. I'll stick to awsmobile-cli for now as I need to work with existing Cognito services.

**Comment by kaustavghosh06** [comment]
@jadbox 

We're currently brainstorming and working towards providing a CI/CD workflow as a part of the Amplify CLI, and in doing so we want to work backward from the customer needs and we've opened up an issue (#286) as a part of the CLI repo to track this story.
Would be great, if you guys could take a look at it and respond back with some answers to the questions mentioned in the issue (#286) which would give us a better idea about your needs. Thanks!

**Comment by rizerzero** [comment]
@jadbox Hi, did you find a solution or a workflow that works for you ?

**Comment by kaustavghosh06** [comment]
@rizerzero  We're actively working right now on making inter-team and intra-team workflows, and CI/CD workflows better as a part of the Amplify CLI (based upon our RFC #286) which should solve this issue and make your experience of re-initing an existing project and sharing of a project within teams simpler.

**Comment by kaustavghosh06** [comment]
@lestephane  Just to give you an idea, we're close to complete with the beta version of team-workflows and CI/CD flows as part of the Amplify CLI and working actively on our documentation. As soon as we launch it, I'll update this thread (expect an announcement sometime next week).

This release should answer all your questions above. Seems like we've taken into considerations all your above recommendations :)

**Comment by kaustavghosh06** [comment]
Based on all of your feedback, we’ve released a beta version of the CLI (npm install -g @aws-amplify/cli@multienv)  to support multiple environments, team workflows and integrate with your CI/CD flows.
Please check out this documentation for more details - https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Also, as a part of our feedback mechanism, we’ve opened up another [GitHub issue](https://github.com/aws-amplify/amplify-cli/issues/508),  to track feedback from everyone, iterate on this beta version and then merge it to master.  We'll close this issue and track feedback in #508. Looking forward to your feedback on this release.

**Comment by kaustavghosh06** [comment]
Closing this issue since this problem is solved with the release of the multienv feature-set mentioned above.

**Comment by EralpB** [comment]
I'm assuming this is still the case after 2 years, I can't just send an "id" to my app developer to start a project....

**Comment by byennen** [comment]
broken again

**Comment by tvkit** [comment]
I mistakenly selected the wrong IAM profile which resulted in "access denied".  I used the following Amplify settings from _.gitignore_ to determine how to rerun the **init** process:

I basically removed the Amplify artifacts not tracked by git.  

Zip your project before making changes!

```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation

```

**Comment by david-mcafee** [comment]
Since there is still some confusion regarding pulling an existing project on a new machine, here is how: 

To generate the `aws-exports.js` file in an existing project (or checkout a backend environment that exists in the console but does not show up locally), follow these steps:

1. Go to the AWS console
2. Choose `AWS Amplify`
3. Find the app
4. Go to `Backend environments`
5. Find the backend environment
6. Click `Edit backend`
7. Run the command that is listed there, something like: 
    - `amplify pull --appId YOUR_APP_ID --envName YOUR_ENV_NAME`
