### ISSUE TITLE
Amplify CLI Plug-In: Amplify push doesn't push all resources copied over from amplify.copyBatch()

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#370]
**Describe the bug**
When writing a plug-in Amplify push doesn't upload all the files (only the cloudformation templates) found in the backend directory created for the resource. This should be a desired behavior to upload anything that is written using amplify.copyBatch() to S3.

**To Reproduce**
1. Create a new amplify plugin not associated with any of the default Amplify support services.
1. Copy a few files over to the resource directory using copyBatch()
1. Observe only the template files being uploaded to S3.

**Expected behavior**
Upload all resources to S3 so they can be used. For example a zip file for deploying a lambda function.

**Desktop (please complete the following information):**
 - OS: Mac

**Work around**
Resources hosted in another bucket not great but used until this is fixed.

**Comment by UnleashedMind** [comment]
That's the intended behavior of the awscloudformation provider plugin. 
For the third party plugin, if you want to upload other contents into the deployment bucket, you have two choices: 
- you can write the logic into the category plugin
- you can write another provider plugin to upload the contents, and your category plugin uses the new provider plugin instead of the default awscloudformation provider plugin.

**Comment by wizage** [comment]
Should that be the intended behavior if we want to encourage users to use cloudformation as the default provider?

**Comment by wizage** [comment]
If moving forward on this it is decided that this is intended behavior then it should be documented.

Also, it should then be documented on how to communicate with AWS services. Including where to get credentials and should we use the default node-js AWS sdk.

**Comment by kaustavghosh06** [comment]
@wizage I agree, we need code-specific documentation for our context/extensions which we expose to our plugins. Is there anything you're specifically blocked on?

**Comment by kaustavghosh06** [comment]
@wizage That's awesome! Would be great to know about your plugin. Would probably be our first 3rd-party Amplify CLI plugin :D Super excited to learn more.
