### ISSUE TITLE
Multiple REST APIs or one general REST API?

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#3701]
**Which Category is your question related to?**
API

**What AWS Services are you utilizing?**
AppSync, S3, Cognito, DynamoDB

**Provide additional details e.g. code snippets**
For my app I have used until now a single GraphQL API, but I feel like it's very hard to do business logic on VTL, so I thought I will keep GraphQL just for the queries and some mutations, and for the business logic I will create a REST API (for example a user can only update his info under certain circumstances). But what should I do, create one REST API with many endpoints for my entire application (a pretty big and complicated app) or have multiple REST APIs for couple of modules that exist in my architecture.
Which one is preferred?

**Comment by kaustavghosh06** [comment]
@idanlo It's actually a design decision which you'd have to make based on your use-case. I would separate REST API's (with endpoints) if they have separate configuration needs (like auth) and have widely varied business logic.

**Comment by KarthickSelvam** [comment]
Should we use amplify update api or amplify add function?
