### ISSUE TITLE
eslint doesn't ignore generated files from template

### ISSUE THREAD

**Issue by akgm3i** [aws-amplify/amplify-cli#3706]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
#3278 resolved files from code generator.
As well generated files also from template file should include `/* eslint-disable */`.

**Describe the solution you'd like**
Append `/* eslint-disable */`

**Describe alternatives you've considered**

**Additional context**

**Comment by kaustavghosh06** [comment]
@akgm3i Which files are you specifically referring to? Cloudformation templates?

**Comment by akgm3i** [comment]
I'm referring to files generated from `amplify api gql-compile` command.
like mutations.ts, queries.ts, subscriptions.ts.

I'm sorry for the confusion.

**Comment by UnleashedMind** [comment]
those files are generated by codegen, not gql-compile

**Comment by akgm3i** [comment]
`// eslint-disable` just disable only one line.
disable whole file needs `/* eslint-disable */`.
and I had forgot `aws-exports.js`, `amplify-config.js`.
