### ISSUE TITLE
[WARNING]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#3708]
Amplify CLI v4.16.0 && 4.16.1

Was having this issue before, with 4.13. The 4.16.0 update seemed to fix it but now it sprung back up. Getting this same error when running `amplify publish` locally, and during the auto-builds in Amplify Console.

**Comment by UnleashedMind** [comment]
Could you take a screenshot and share it here?

**Comment by blazinaj** [comment]
I think this is an issue now with react-scripts, it is tied with the frontend build command. I'm sorry for asking about it here. I set the --max_old_space_size flag in my build script and seemed to fix it. Thanks for the quick response. 
```
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts --max_old_space_size=8192 build",
    "test": "react-scripts test",
    "test:cov": "react-scripts test --coverage",
    "test:debug": "react-scripts --inspect-brk test --runInBand",
    "eject": "react-scripts eject"
  },
```

**Comment by charleslouis** [comment]
If anyone comes here looking to build a JS frontend on Amplify, it seems that it comes from the difference in the way memory is handled by node v10 vs node v12.

Check how you can add `nvm use $VERSION_NODE_12` to your build settings as explained by @atlesp here https://github.com/aws-amplify/amplify-console/issues/440#issuecomment-602626451
![image](https://user-images.githubusercontent.com/2117081/87630450-ce855b00-c73d-11ea-8e3a-cc2edc4632cd.png)

**Comment by mikhael28** [comment]
@blazinaj your solution worked perfectly - thank you @charleslouis I'm sure that would have helped as well!
