### ISSUE TITLE
Calling "amplify init" with "--yes" pushes on the cloud at the end of initialization

### ISSUE THREAD

**Issue by ericowlie** [aws-amplify/amplify-cli#3721]
**Describe the bug**
When calling "amplify init" in headless mode using ```--yes``` option, after the initialization the cli pushes the project on the cloud like if I called ```amplify push --yes```.

This is important for me because I try to initialize it on ```Amplify Console``` in which I need to use the ```--yes``` option. The behaviour is reproductible outside of ```Amplify Console```, on Windows.

**Amplify CLI Version**
4.16.1

**To Reproduce**
In any initialized or not initialized Amplify project :

The followiong initialization works fine (but asks me to select a profile or some other things) :
```$ amplify init --amplify "{\"envName\":\"myEnv\"}"```

The following initialization does not ask me anything but, once the initialization in done, the amplify cli pushes to the cloud :
```$ amplify init --amplify "{\"envName\":\"myEnv\"}" --yes```

**Expected behavior**
```$ amplify init --amplify "{\"envName\":\"myEnv\"}" --yes``` should not launch a push after initialization.

**Desktop**
 - OS: Windows
 - Node 12.16.1

**Additional context**
Here is some context about my amplify project :
- It is not yet initialized on my computer
- It contains a ```team-provider-info.json``` with some environments
- It contains a ```.config/project-config.json``` generated by amplify cli on the initial initialization
- It does not contain an ```aws-exports.js```
- I have a unique profile configured in ```~/aws/credentials``` and ```~/aws/config```

**Comment by UnleashedMind** [comment]
the --yes flag will try to use the default values for any prompt and carry out the command execution without interruptions, it only prompt if it can not get any meaningful default answer to a prompt from the CLI. 
If you already have the team-provider-info in the project when you run the `init` command,  the CLI knows about the backend environments of the project, and knows where to retrieve the necessary information to reconstruct the full `amplify` folder structure and the frontend config file (`aws-exports.js`) for you to continue the development on this local environment. 
Not sure what you mean by the `init` command launches `push`. If you project "not yet initialized" on your computer,  the `amplify` folder structure is not fully setup, you won't be able to use the amplify commands to update the resources, and if there's no update, there's no change to push.

**Comment by ericowlie** [comment]
What I mean by the ```init``` command launches ```push```, is that once the normal process of ```amplify init``` is finished, instead of giving me the hand on the terminal, it goes through the same process as an ```amplify push``` would once you said you're ok to push the changes.
And even if there is actually no changes to push (which is the case because I am just initializing), it pushes anyway the whole project on AWS.

**Comment by UnleashedMind** [comment]
The `push` workflow will update the resource on the cloud based on your local changes, when you run init, your local development has not been setup yet, there is nothing to `push`.
Could you take a screenshot and show the `push` that was launched by the `init` workflow?

**Comment by moacirosa** [comment]
I was facing the same problem and **removing the `--yes` parameter looks to resolve**. In my case, I was trying to configure a CI and I want to:

1. `git clone`
2. `amplify init`
3. `amplify status`
4. `amplify push`

However, as @ericowlie has reported, an undesired `push` was run during `init` process. What do you think is the better approach in this case? Maybe that `--yes` could be better explained if the current behavior is correct. What do you think?

**Comment by ericowlie** [comment]
Here is a screenshot of what happens without the ```--yes``` option :
![no](https://user-images.githubusercontent.com/48712727/77554398-46412880-6eb6-11ea-979f-2e39fe5662b5.PNG)
(As I have a non default named profile, Amplify asks me to choose the profile on my project, which is not the case on this screenshot because I use the default profile)

Here is a screenshot of what happens with the ```--yes``` option :
![yes](https://user-images.githubusercontent.com/48712727/77555060-20685380-6eb7-11ea-98dd-7a7da88ef974.PNG)

**Comment by moacirosa** [comment]
Yeap... Pretty the same for me. In the workflow I was trying, it was possible to resolve using a script similar to the _Sample script_ from https://docs.amplify.aws/cli/usage/headless removing the `--yes` parameter.

**Comment by kaustavghosh06** [comment]
@ericowlie The --yes is designed in a way such that we does and init + push (if you're initing a new env).

**Comment by esteban-uo** [comment]
hi @UnleashedMind 👋 

It seems to be this behaviour was changed recently. Testing on 4.32.1 I have to init then push as headless. Could you confirm this? 

Thanks!
