### ISSUE TITLE
How to take advantage of /* GraphQL /* comments

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#3738]
Hi,

I noticed that codegen for JS/TS adds ` /* GraphQL */` comments before the query/mutation strings.
I assume that it is used by some editor plugins and/or linters for syntax highlighting / checks /  autocomplete? 
Anyone knows of any tools that use this comment annotation, and how to configure them?

**Comment by attilah** [comment]
@tgjorgoski all the IDE/editor plugins that are based on [gql](https://www.npmjs.com/package/%40playlyfe/gql) package are supporting this, it enables you various features like jump to definition and such things when a GraphQL code snippet encountered in code files. For VS Code you need this [plugin](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode).
