### ISSUE TITLE
Datastore base query in multi tenant app

### ISSUE THREAD

**Issue by mdebo** [aws-amplify/amplify-cli#3743]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Datastore

**Amplify CLI Version** 
4.16.1

Hi, 
I ask myself how the base query done by the sync engine works. Does it pull from remote db random data at bootstrap, or it is based on query done in the frontend (like apollo cache).
Hi, I would like to know if there is any way to configure the base query done by datasore sync engine. In the context of a multi tenant app, it's not efficient to get unscoped data.

**Comment by undefobj** [comment]
Please take a look at this video and written explanation on how the sync process works: https://aws-amplify.github.io/docs/js/datastore#how-it-works

Are you looking to filter and sort data when you say "configure the base query"?  Can you be more specific with your use case?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response. @mdebo Please let us know if you need more information than the one provided above by @undefobj
