### ISSUE TITLE
initTriggerEnvs path issue, no such file or directory

### ISSUE THREAD

**Issue by chriswessells** [aws-amplify/amplify-cli#3746]
**Describe the bug**
I am contributing to an existing Amplify project. I download the source code and run `amplify init`. In the process It asks if I want to create a Lambda. Regardless of my answer I get the error `Error: ENOENT: no such file or directory, open` referring to `.nvm/versions/node/v10.17.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/PreTokenGeneration.map.json`

I installed amplify 4.16.1 and the bug does not exist. 

**Amplify CLI Version**
4.17.1

**To Reproduce**
Create a working project with a version prior to 4.17.x or have an existing working Amplify project, then in a new account on a new machine, download the source code from the working project and initialize the project. Answer N when it asks to create the Lambda.

**Expected behavior**
I expect the project to successfully initialize when I provide an appropriate response. In this project I expect the N response to successfully complete the initialization

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v10.17.0

**Comment by no-creative-name** [comment]
I have the same problem, just with the CustomMessage trigger. 
Error: ENOENT: no such file or directory, open 'C:\Users\timo.mayer\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-function\lib\provider-utils\awscloudformation/../../../amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/CustomMessage.map.json'

**Comment by chriswessells** [comment]
@no-creative-name  For me, I installed amplify-cli@4.16.1 which solved my problem.

I found the problem and submitted a pull request to fix it.

**Comment by ammarkarachi** [comment]
@chriswessells does `amplify init` prompt you to create a lambda?

**Comment by chriswessells** [comment]
@ammarkarachi Yes, `amplify init` prompts me to create a lambda. I tried many options from select one lambda auth option to selecting all, to no lambda. All options gave me the same error. I spoke with the team who created the amplify project and for that project they said answer "No" to creating a lambda.

**Comment by ammarkarachi** [comment]
@ChristopheBougere Can you share your init script?

**Comment by kldeb** [comment]
Same problem with post confirmation add to group. Downgrade to 4.16.1 solved it.

Please re-open. 

```
There was an error initializing your environment.
init failed
{ Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/PostConfirmation.map.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at readJsonFile (/usr/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/read-json-file.js:13:35)
    at AmplifyToolkit.getTriggerMetadata [as _getTriggerMetadata] (/usr/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/trigger-flow.js:223:49)
    at AmplifyToolkit.getTriggerEnvInputs [as _getTriggerEnvInputs] (/usr/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/trigger-flow.js:302:38)
    at initTriggerEnvs (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:217:51)
    at updateConfigOnEnvInit (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:203:27)
    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:99:34
    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/PostConfirmation.map.json' }```

**Comment by chriswessells** [comment]
Hi @kldeb the code fix was merged into master yesterday. I don't know when the code will be released, but it is fixed and the issue is appropriate to be closed.
