### ISSUE TITLE
Querying items by GSI

### ISSUE THREAD

**Issue by cipriancaba** [aws-amplify/amplify-cli#3760]
** Which Category is your question related to? **
DataSource DynamoDB GraphQL API
** What AWS Services are you utilizing? **
AWS AppSync
** Provide additional details e.g. code snippets **

```graphql
type Meal
  @model(subscriptions: null)
  @auth(
    rules: [
      {
        allow: owner
        operations: [create, read, update, delete]
        ownerField: "userId"
        identityClaim: "custom:userId"
      }
    ]
  )
  @key(name: "byUser", fields: ["userId"]) {
  id: ID!
  
  userId: ID
}
```

I have the above schema for a simple Meal datatype and using the `listMeal` query generated by amplify. Authentication works via Cognito

** Expected result **
All the `Meal` items that have the userId of the authenticated user

** Actual result **
When there are less than 100 items in the DynamoDB table, works as expected, however when there are more than 100, the returned result is always empty

My assumption is that this is due to the fact that the `listMeal` generated query uses scan and the graphql query returns a nextToken. This is not manageable for large tables of 100000 items.

However, because the index is already there, and I just want to access all the items with a specific `userId`, does amplify generate a graphl query  that I could use to query the table? What is the solution for this use case?

![Screenshot 2020-03-24 23 58 28](https://user-images.githubusercontent.com/695515/77487863-7abbd280-6e2b-11ea-8439-f23f52216566.png)

**Comment by undefobj** [comment]
Transferring to CLI repo. Can you try with some larger limit sizes?

**Comment by cipriancaba** [comment]
If I increase the limit size it works for now, but I assume will no longer work when I have 100.000 in the table.. So, the question really is how can I trigger a `query` operation in the dynamoDB table rather than a `scan`, because that will definitely solve my problem

**Comment by undefobj** [comment]
GraphQL codegen should give you appropriate queries to run which correspond to DDB queries. Do you see them?

**Comment by cipriancaba** [comment]
I've just created a separate repo with the simplified schema

https://github.com/cipriancaba/amplify-repro/blob/master/src/graphql/queries.ts

The only query is `ListMealsQuery` which seems to work with the `scan` rather than `query` exposing the issue I mentioned earlier

**Comment by undefobj** [comment]
Can you explicitly specify a queryField for the name of your GraphQL query to correspond to your DynamoDB query?

**Comment by cipriancaba** [comment]
That worked, thank you.. Here is the change for anyone interested in the matter https://github.com/cipriancaba/amplify-repro/commit/7ee84e68cedfa714cd3cbd7d85e9e643427b67da

The only downside is that the userId is not being pre-populated, considering it's an owner field https://github.com/cipriancaba/amplify-repro/blob/8fbf0bd528d3da914cbd126039d910d4d2032d0b/amplify/backend/api/amplifyrepro/schema.graphql#L60

However, that works fine when using the default listMealsQuery https://github.com/cipriancaba/amplify-repro/blob/8fbf0bd528d3da914cbd126039d910d4d2032d0b/src/graphql/queries.ts#L63

**Comment by RossWilliams** [comment]
@cipriancaba the default listMealsQuery does not pre-populate the userId in the request template. It filters non-owner Meals after fetching from dynamoDB in the response template. you will have the same problem with a large table as you described in your earlier comment.

In both cases you should specify the primary key to avoid issues / surprises.
