### ISSUE TITLE
Multiple Environments S3 Deployment Bucket

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3762]
**Which Category is your question related to?**
Amplify Multiple Environments

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
Environments, Lambda functions, S3, Cognito

What I am trying to achieve?
I am trying ti create an environment for each of my developer and once they are done doing the changes, I can merge there code in dev and run "amplify push" on the "dev" environment to reflect all the changes in dev.

The issue I am facing?
The issue is that I opened the cloudformation file for a lambda function and saw the following json there

"Runtime": "nodejs10.x",
				"Timeout": "25",
				"Code": {
					"S3Bucket": **"amplify-cygov-app-dev-120906-deployment",**
					"S3Key": "amplify-builds/addCognitoUser-54576461712f69675976-build.zip"
				}

You can find this code under the Lambda->Properties section in cloudformation file of any lambda function.

The bold part has the environment name in it which is confusing me. If I merge this dev env into my production and run "amplify push", will this update to "amplify-cygov-app-prod"?

If not can anyone recommend me how to achieve this work flow in my team?

**Comment by kaustavghosh06** [comment]
@rehanbabertkxel The S3Bucket and S3Key parameters are re-generated on an `amplify push` - hence merging it would regenerate it again for the environment you're pushing from.

**Comment by rehanbabertkxel** [comment]
@kaustavghosh06 , yes I understood it the day I posted it. Forgot to close the issue.
Thanks for the explanation. Closing this issue.
