### ISSUE TITLE
Issue with Multiple Env and Redirect URI

### ISSUE THREAD

**Issue by challapradyumna** [aws-amplify/amplify-cli#3763]
**Is your feature request related to a problem? Please describe.**
Our project has 2 environments dev and prod. Both of them are deployed in two different AWS accounts. The issue here is around Federated user pool logins. When I checkout between env the redirect URIs are also carried to the other env but the endpoints are different between the environments. I have to manually change the redirect URI when I am making pushes between environments. 

**Describe the solution you'd like**
The Redirect URI's should be env based but not the same for all env

**Describe alternatives you've considered**
The solution is to never make a full push but to push only the changes that need to be updated. If redirect URI's have to be changed then do a restore first and then make the changes in the respective environment.

**Comment by ammarkarachi** [comment]
@challapradyumna After creating a new environment you would have to manually walkthrough to update the URL and then run `amplify push` to save the updated url. This would make sure the URLs are saving between environments

**Comment by challapradyumna** [comment]
The original issue was resolved but then I've run into an issue with multiple redirect URIs in a single environment. I guess that was already reported and being worked upon.

**Comment by ammarkarachi** [comment]
@challapradyumna Thanks for the response. What's the issue with multiple redirect URI?

**Comment by challapradyumna** [comment]
Hey I just checked with the dev team they are still having the issue with the redirect URI's. 

There are two places where Redirect URI's are present. 

1. aws-exports.js - The redirect URI's are changing according to the env
2. amplify update auth - When I check the redirect URLs by selecting add/update redirect URI's then it still holds the previous environment redirect URIs. And we need to change the redirect URI every time we need to deploy in different environment. 

I hope the issue is clear now.

**Comment by ammarkarachi** [comment]
@challapradyumna Is this immediately after you create a new environment? When you create a new environment say 'prod' and you had 'dev' checked out. What's going to happen is the dev environment is going to be cloned to your prod. Once the 'prod' values are edited and pushed the values will be present in your current cloud backend.

**Comment by challapradyumna** [comment]
This is a constant thing that happens every time we checkout between environments.

**Comment by bishonbopanna** [comment]
This issue exists and needs to be addressed please.
