### ISSUE TITLE
Remove Auth not working

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-cli#3765]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Template error: instance of Fn::GetAtt references undefined resource "ProjectName"
An error occured during the push operation: Template error: instance of Fn::GetAtt references undefined resource "ProjectName"

Before this i removed one Lambda function manually. If its reason how i fix this ?

**Amplify CLI Version**
4.17.1

**Comment by ammarkarachi** [comment]
Hi @anarerdene ,

We would some more information to help you

- Can you elaborate on the steps that resulted on this error?

- What resources did you have using your auth workflow?

Thanks

**Comment by anarerdene** [comment]
Hi @ammarkarachi .

1.  I  updated my Auth using "amplify update auth" then adding user group named "admin". After this i pushed it to server. Everything was ok.

2. After this i logged in AWS cloud and cleaning some unnecessary functions. I think i removed CLI generated function too.

3. I tried remove auth but its bugged

![image](https://user-images.githubusercontent.com/2210568/77574527-1cffb700-6f0d-11ea-89e9-a53c9aaa0d78.png)

**Comment by kaustavghosh06** [comment]
@anarerdene Would be helpful if you share you `amplify/backend./amplify-meta.json` and `amplify/backend/backend-config.json` - did you modify any of these files? 
Which exact resources did you remove from the AWS Console?

**Comment by ammarkarachi** [comment]
@anarerdene Do you still need help with this particular issue?
