### ISSUE TITLE
Explain what the "enter a name for the environment" means

### ISSUE THREAD

**Issue by selbekk** [aws-amplify/amplify-cli#3766]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
When I run `amplify init` for the first time, I am asked "Enter a name for the environment" as the second question. This doesn't make a whole lot of sense to me. 

Should I write production, because my app is going to end up in prod at some point? Should I write test or dev, because that's the first place I'm going to deploy? Or should I write "earth" because I feel clever?

**Describe the solution you'd like**
I'd love a better description for this option, or perhaps it could just be set by default. This would help me not feel confused as a beginner.

**Comment by ammarkarachi** [comment]
Hi @selbekk, you can find more information for the environment [here](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#environments-and-teams)

**Comment by selbekk** [comment]
> Hi @selbekk, you can find more information for the environment [here](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#environments-and-teams)

Thanks! This makes sense - but I would love to automatically understand this without reading through all the docs 😙

**Comment by brene** [comment]
Hi @selbekk - this is good feedback! What do you think of these options:

Option 1 - Provide examples in the prompt
```
Enter a name for the environment (ex: dev, prod): 
```

Option 2 - Provide a default value "dev"
```
Enter a name for the environment: (dev)
```

**Comment by selbekk** [comment]
Thanks! How about giving some context about what the environment is?

Examples are good, but they don’t explain what the context of the question is. 

Could we add a paragraph explaining the context of the question?

**Comment by brene** [comment]
We try to minimize the content in the init flow as much as possible. So I'd rather adjust the sentence to make it clearer than adding too much description.

@selbekk - what if we just remove environment all together from the init flow and just initialize it to dev in the background?
When you actually need to add additional environments through `amplify env add` is probably where you actually care about it. There, we can add additional description. Wdyt?

**Comment by selbekk** [comment]
Sounds great!

That being said - why do you think it’s important to keep explanations through the init flow to an absolute minimum?

**Comment by brene** [comment]
To be clear: it should be an absolute minimum in which the customer still understands what's happening. I'll take this back to the team and how to progress from here. Thanks for the fast feedback loop!

**Comment by selbekk** [comment]
Yeah I understand - but perhaps the premise that "it should be an absolute minimum" isn't correct? I love info while going through a process like this. If possible, a link to more details would also be a great addition.

**Comment by brene** [comment]
@selbekk after some more discussion with other customers, I've submitted a PR to make "dev" the default environment. #4201 
Thanks for the feedback. We'll keep iterating on this.

**Comment by JPVan** [comment]
I've got a similar experience. I'm setting up an environment for a real project for the first time, and I have no idea what this question is asking. Maybe if you don't want to have more explanation, you could include a link to the place in the docs that has enough information for me to answer the question? I don't even know if this environment is for my front end or back end or both. And what best practices are, etc. Thanks for what you do. I love Amplify.

**Comment by JPVan** [comment]
On reading more, "dev" seems like a very suitable default. And I understand you not wanting an overly chatty interface.
