### ISSUE TITLE
How to apply field level public auth and keep other fields owner only?

### ISSUE THREAD

**Issue by patcito** [aws-amplify/amplify-cli#3774]
**Which Category is your question related to?**

AppSync

**Amplify CLI Version** 

4.16.1

**What AWS Services are you utilizing?**

Auth/Api/Function/Storage

**Provide additional details e.g. code snippets**

This is my current model, it is accessible only to owner and for all CRUD operations.

```
type StripeAccount
  @model
  @auth(rules: [{ allow: owner, operations: [create, update, delete, read] }]) {
  id: ID!
  accessToken: String
  livemode: String
  refreshToken: String
  tokenType: String
  stripePublishableKey: String
  stripeUserId: String
  scope: String
}
```
I would like to also allow `read` operations to `stripePublishableKey` and `id` fields for `public`. I tried several solutions as [discussed on this twitter thread](https://twitter.com/undef_obj/status/1242672925322252293) but none worked (it made all fields readable to public instead of just the two I wanted).

**Comment by SwaySway** [comment]
Hello @patcito 
One way to do this would be using apiKey or IAM as an auth provider.  If you use one them to allow public on fields there will need to be explicit definitions on what fields a user will have access to.
```gql
# using apiKey auth as an example
type StripeAccount
  @model
  @auth(rules: [{ allow: owner, operations: [create, update, delete, read] }]) {
  id: ID @auth(rules: [
{ allow: public, operations: [read], provider: apiKey }]) @aws_cognito_user_pools
  accessToken: String @aws_cognito_user_pools
  livemode: String @aws_cognito_user_pools
  refreshToken: String @aws_cognito_user_pools
  tokenType: String @aws_cognito_user_pools
	owner: String @aws_cognito_user_pools
  stripePublishableKey: String @auth(rules: [
{ allow: public, operations: [read], provider: apiKey }]) @aws_cognito_user_pools
  stripeUserId: String @aws_cognito_user_pools
  scope: String @aws_cognito_user_pools
}
```
This deny-by-default behavior here is something we are looking into.
RFC on `@auth` behavior: https://github.com/aws-amplify/amplify-cli/issues/1043

**Comment by patcito** [comment]
@SwaySway thanks! This worked great.
