### ISSUE TITLE
Upload to S3 send a 403 forbidden error after adding user to cognito group created with CLI

### ISSUE THREAD

**Issue by daajack** [aws-amplify/amplify-cli#3778]
**Describe the bug**
I cannot upload images to s3 with an 403 (forbidden) error, from a user member of the cognito group create via amplify cli.

**Amplify CLI Version**
4.16.1

**To Reproduce**
- add a cognito group with amplify auth update
- add user to group in cognito console
- try upload image with Storage.Put(...)

**Expected behavior**
Upload with success

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v13.8.0

**Additional context**
I can upload with user not member of the group

**Comment by kaustavghosh06** [comment]
Did you give all the CRUD permissions to the user pool group in the `amplify storage add/update` flow?

**Comment by daajack** [comment]
> 
> 
> Did you give all the CRUD permissions to the user pool group in the `amplify storage add/update` flow?

Thanks ! I didn't. After giving all CRUD access to the user pool group, it works.
I choosed "Both" as "Restrict access".
I thought that giving CRUD access to auth users would allow members of a group to have same access.
Thanks for your help.

```
amplify storage update
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Restrict access by? Both
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? read
? Select groups: admin
? What kind of access do you want for admin users? create/update, read, delete
? Do you want to add a Lambda Trigger for your S3 Bucket? No
Successfully updated resource
```

NB: I had to delete property "triggerFunction: NONE" in storage/xxx/parameters.json to push as mentionned in [this issue](https://github.com/aws-samples/amplify-photo-gallery-workshop/issues/12#issuecomment-516495429)

**Comment by lukepushlabs** [comment]
Also getting this issue.

**Comment by daajack** [comment]
> 
> 
> Also getting this issue.

@lukepushlabs, did you try my solution ?
> After giving all CRUD access to the user pool group, it works.
> I choosed "Both" as "Restrict access".
