### ISSUE TITLE
@connection directive doesn't create an one-to-many relationship using primary key.

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-cli#3782]
**Describe the bug**
@connection directive doesn't create an one-to-many relationship using primary key.

**To Reproduce**
1. Create two types (account and book) at schema. 
2. Account uses @key to declare _userId_ as its simple primary key. 
3. Book uses @key to declare _userId_ and _createdAt_ as its composite primary key.
4. Account uses @connection next to its _books_ field to connect with book type with "userId" as primary key.
5. Create an account followed by creating a book using the same _userId_ .
6. Query account and its _books_ field shows null.

```graphQl
type account
	@model
	@key(fields: ["userId"])
	) {
	userId: String!
	books: [book] @connection(fields: ["userId"])
}

type book
	@model
	@key(fields: ["userId", "createdAt"])
	) {
	userId: String!
        createdAt: String!
	title: String
        author: String
}
```

**Expected behavior**
When account is query, it's _books_ field should show the book created.

**Comment by jhockett** [comment]
Hi @xitanggg!

>     3. Book uses @key to declare _userId_ and _createdAt_ as its composite primary key.

In this case, userId would be the primary key and createdAt is the sort key.
See: https://aws-amplify.github.io/docs/cli-toolchain/graphql#definition-1

Here's how I created the schema to get the queries working using the new style of connections:
See **Has Many** relationships: https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage-2

```graphql
type Account @model
  @key(fields: ["userId"]) {
  userId: String!
  books: [Book] @connection(keyName: "byAccount", fields: ["userId"])
}

type Book @model
  @key(name: "byAccount", fields: ["userId", "createdAt"]) {
  userId: String!
  createdAt: String!
  title: String
  author: String
}
```

When I use the above schema and run mock, I can have books shown successfully by running the following mutations and queries:

```graphql
mutation MyMutation {
  createAccount(input: {userId: "user1"}) {
    userId
  }
}

mutation MyMutation2 {
  createBook(input: {
    userId: "user1",
    createdAt: "1",
    author: "Tolkien",
    title: "The Hobbit"
  }) {
    createdAt
    author
    title
    userId
  }
}

query MyQuery {
  getAccount(userId: "user1") {
    userId
    books {
      items {
        title
      }
    }
  }
}
```

Let me know if that helps and or if you still have more questions.

**Comment by xitanggg** [comment]
@jhockett Thank you for taking at look at this and your thorough example. 

I understand this issue can be solved by adding a secondary index, in which you specify `keyName: "byAccount"` at `@connection' and `name: "byAccount"` at `@key`. It confuses me as why the connection is not automatically created simply by using primary index as is the way I created the schema (hence why I emphasize "primary key" in my question, we can create more secondary index with partition key and sort key if we like of course). I believe each secondary index we add creates added cost. It seems wasteful and buggy to me as why this doesn't work right out of the box in its most natural primary index table form. Thanks.

**Comment by jhockett** [comment]
Apologies for misunderstanding your post the first time. You're correct, it's not currently possible to avoid the use of a secondary index in this case.

**Comment by xitanggg** [comment]
Ok. Thanks for confirming. It will be helpful if this feature is added.

**Comment by xitanggg** [comment]
I just checked. This issue has been resolved sometimes ago (idk by which commit). The [documentation ](https://docs.amplify.aws/cli/graphql-transformer/connection#connection) also makes a note `If keyName is not provided, then @connection queries the target table’s primary index.` Good work Amplify team!
