### ISSUE TITLE
Error: Plugin scan failed.

### ISSUE THREAD

**Issue by akmalrasool** [aws-amplify/amplify-cli#3784]
Unable to use amplify command.
On each amplify command I am getting the following error.

Scanning for plugins...
Plugin scan failed.
Plugin scan failed.
Error: Plugin scan failed.
    at scan

Installed using npm i -g @aws-amplify/cli --unsafe-perm=true

It was working few days ago.

 - OS: Linux
 - Node Version. 10.16.3

Kindly help ASAP.

**Comment by kaustavghosh06** [comment]
@akmalrasool You'll have to instal the CLI globally - `npm install -g @aws-amplify/cli`

**Comment by akmalrasool** [comment]
@kaustavghosh06 Sorry about that but I installed it globally.

**Comment by kaustavghosh06** [comment]
@akmalrasool Is there any other stack trace after the following message:

Error: Plugin scan failed.
at scan

**Comment by akmalrasool** [comment]
@kaustavghosh06 This is the exact error:
Error: Plugin scan failed.
    at scan (/home/akmalrasool/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11)

**Comment by UnleashedMind** [comment]
This is a duplicate issue as this one: 
https://github.com/aws-amplify/amplify-cli/issues/3560

Please use this hack to diagnose ( we will soon update the CLI to print out error log)
/usr/local/lib/node_modules/@aws-amplify/cli/src/plugin-manager.ts:137:11, and insert one line of code before it to help us to diagnose?

    print.error(JSON.stringify(e));
After you add the line, do a npm run build at /usr/local/lib/node_modules/@aws-amplify/cli/

**Comment by akmalrasool** [comment]
@UnleashedMind Tried this but no help!

**Comment by UnleashedMind** [comment]
`sudo amplify plugin scan` still give you the error? 

Then use the hack to diagnose, what's the error message that's printed out?

**Comment by UnleashedMind** [comment]
Closing the issue due to lack of response. 
Feel free to open a new issue if you still have the problem.
