### ISSUE TITLE
.cmd left in project config when changing from windows to non windows after running 'amplify configure project'

### ISSUE THREAD

**Issue by TigerJ** [aws-amplify/amplify-cli#379]
**Description**
When a project that was configured on windows is moved to a non-windows environment and reconfigured using 'amplify configure project' the resulting configurations do not correctly remove the build and start '.cmd' suffix from npm. This does not happen when transitioning a project from a non-windows to a windows environment.

**To Reproduce**

1. Go to a project configured on windows and commit it to a remote repo
2. Go to a non-windows OS and clone the repo
3. run 'amplify configure project'
4. open amplify/.config/project-configure.json
5. note the .cmd artifacts that are not properly updated

**Expected behavior**
running amplify configure project on a non-windows OS should update windows specific json values with non-windows strings

This will cause publish errors for anyone moving a project from windows to a non-windows OS until they update their config manually and remove the .cmd from the npm key value pairs

**Comment by kaustavghosh06** [comment]
@TigerJ  Did you move the amplify directory from a non-windows machine to a windows machine?

**Comment by TigerJ** [comment]
@kaustavghosh06 yes the amplify directory is part of my repo so it is cloned and moved with the other files between my windows machine and my macbook

**Comment by rdickert** [comment]
My team just came across this as well (we are on cli@multienv). In /amplify/.config/project-config.json, you have to manually change anything in `BuildCommand` and `StartCommand`, and these are in source control. 


I wonder if this could be solved by [cross-spawn`(https://www.npmjs.com/package/cross-spawn)? This was mentioned to me by a colleague; I haven't used it, but it looks like it might solve the problem (try replacing [this require statement](https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/amplify-frontend-javascript/lib/builder.js#L2) with

```
const spawn = require('cross-spawn');
```

(Sorry, I don't have time at the moment to coordinate trying this with our windows users, or I'd just give it a go)

At the very least, I'd like to at least be able to run a shell script to call the correct package. All we're trying to do is `yarn build` or `yarn.cmd build`.

**Comment by kaustavghosh06** [comment]
Hey guys,  beleive this issue is solved with the latest version of the CLI. Coul you'll please confirm if you're still seeing the same behavior.
