### ISSUE TITLE
amplify push throws error UPDATE_ROLLBACK_FAILED state and can not be updated.

### ISSUE THREAD

**Issue by stayingcool** [aws-amplify/amplify-cli#3792]
**Describe the bug**
**# amplify push**
Throws the following error:
Stack:arn:aws:cloudformation:eu-west-1:478576439851:stack/pna/-956b-068bfa33c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.
An error occured during the push operation: Stack:arn:aws:cloudformation:eu-we39851:stack/pna-956b-068b3c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.

**Amplify CLI Version**
4.17.2

**To Reproduce**
Execute amplify push

**Expected behavior**
amplify push should the code changes were done to a function

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version: v10.15.1

**Additional context**
After enhancing the code of a function I want and executed amplify push as a part of code push mechanism. It failed with the following error:
Stack:arn:aws:cloudformation:eu-w9851:stack/pna/-956b-068bfa33c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.
An error occured during the push operation: Stack:arn:aws:cloudformation:eu-w439851:stack/pna-956b-03c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.

**Done so far**
1. Went to the AWS cloud Formation and identified that one of the functions in the stack used an old version of nodejs runtime to nodejs12.x. Then ran the amplify push command again. I still saw the same error.

2. Upgraded the version of amplify cli to 4.17.2. Then ran the amplify push command again. I still saw the same error.

2. Went to the AWS cloud Formation and clicked on "Continue Update Rollback" under the Stack. The update failed, looking at the events I see that the same nested item is failing:
Embedded stack arn:aws:cloudformation:eu-57:stack/pna-auth21a-25b48e was not successfully updated. Currently in UPDATE_ROLLBACK_FAILED with reason: The following resource(s) failed to update: [UserPoolClientLambda].
**Note -** Not able to "Continue Update Rollback"  under the above NESTED STACK, however the ROOT STACK throws that error on  "Continue Update Rollback".

I'm very nervous always running any of the AWS amplify commands. I have wasted quite a lot of time in reading the amplify issues and upgrading the versions.

**I'm not sure how I'm going to get through this issue as I have a small window of downtime tomorrow before the web application will be back in production. Please assist!**

**Comment by stayingcool** [comment]
It is already two days past my production deployment window. I have a similar issue in the Dev environment as well. The issue has been open for 3 days, can I have someone to work with me?

**Comment by stayingcool** [comment]
Four days and still no assistance on an issue that mentions that the production deployment is blocked out! There are people who are waiting for functionality.

Is there someone who even looks at these issues?

**Comment by kaustavghosh06** [comment]
@stayingcool In your `amplify/backend/` folder there would be Cloudformation files - you can manualy change the NodeJS versions of those files to v12.x. These maybe include files in the ``amplify/backend/auth` directory as well. What are the resources you have in your Amplify project? You can find that out using amplify status.

**Comment by brene** [comment]
@stayingcool - can we get on a call together or can send us your zipped `amplify` folder to amplify-cli@amazon.com ? This will help us diagnose the issue faster.

**Comment by brene** [comment]
DM me on Twitter to agree on a time for a call if needed. twitter.com/renebrandel

**Comment by stayingcool** [comment]
> @stayingcool In your `amplify/backend/` folder there would be Cloudformation files - you can manualy change the NodeJS versions of those files to v12.x. These maybe include files in the ``amplify/backend/auth` directory as well. What are the resources you have in your Amplify project? You can find that out using amplify status.

I updated the NodeJS version to nodejs12.x in the dev environment to begin with. 

Here is the output of amplify status:
$ amplify push
Scanning for plugins...
Plugin scan successful
✔ Successfully pulled backend environment devfirst from the cloud.

Current Environment: devfirst

| Category | Resource name                | Operation | Provider plugin   |
| -------- | ---------------------------- | --------- | ----------------- |
| Auth     | cognito8146221a              | Update    | awscloudformation |
| Function | pnamarch0503function         | Update    | awscloudformation |
| Function | pnamarch0503activityfunction | Update    | awscloudformation |
| Function | feemarch0503augsearch        | Update    | awscloudformation |
| Hosting  | S3AndCloudFront              | No Change | awscloudformation |
| Storage  | ordersmarch0503              | No Change | awscloudformation |
| Storage  | activitiesmarch0503          | No Change | awscloudformation |
| Storage  | pnamarch0506prodattachments  | No Change | awscloudformation |
| Storage  | feemarch0503augsearch        | No Change | awscloudformation |
| Api      | pnamarch0503                 | No Change | awscloudformation |
| Api      | pnamarch0503activity         | No Change | awscloudformation |
| Api      | feemarch0503augsearch        | No Change | awscloudformation |

Then ran amplify push again:
✖ An error occurred when pushing the resources to the cloud

Stack:arn:aws:cloudformation:eu-west-1:478576439851:stack/pnamar05first-20190511104149/91c6a4b0-7385-11e9-956b-068bfa33c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.
An error occured during the push operation: Stack:arn:aws:cloudformation:eu-west-1:478576439851:stack/pnamar05first-20190511104149/91c6a4b0-7385-11e9-956b-068bfa33c7ce is in UPDATE_ROLLBACK_FAILED state and can not be updated.

**Comment by kaustavghosh06** [comment]
@stayingcool We use Lambda Custom resources in the "Auth" Cloudformation tempaltes as well - which need to be updated to v 12.x or 10.x as well. From your previous comment, it looked like a deployment in the auth stack failed - 

The following resource(s) failed to update: [UserPoolClientLambda].

Could you provide the "UPDATE_FAILED"  Cloudformation events from your terminal? That woould help us better guide you.

**Comment by stayingcool** [comment]
> @stayingcool - can we get on a call together or can send us your zipped `amplify` folder to [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com) ? This will help us diagnose the issue faster.

@brene - After zipping the folder it is 62 MB. I'm not sure if I'll be able to send that as an attachment in an email. 

Any other alternatives to share the zipped amplify folder?

**Comment by stayingcool** [comment]
> @stayingcool We use Lambda Custom resources in the "Auth" Cloudformation tempaltes as well - which need to be updated to v 12.x or 10.x as well. From your previous comment, it looked like a deployment in the auth stack failed -
> 
> The following resource(s) failed to update: [UserPoolClientLambda].
> 
> Could you provide the "UPDATE_FAILED" Cloudformation events from your terminal? That woould help us better guide you.

There is no verbose information. Here is the screenshot:
<img width="1332" alt="amplify push error" src="https://user-images.githubusercontent.com/31205483/78087636-6ff5d480-740d-11ea-805c-31284b417530.png">

**Comment by kaustavghosh06** [comment]
I see. So you've tried a few methods mentioned here - https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-update-rollback-failed/ to change the state of your stack from "UPDATE_ROLLBACK_FAILED" state correct? `amplify push` wouldn't work unless the stack changes from the UPDATE_ROLLBACK_FAILED state. We're engaging with the Cloudformation team to see what can be done about this.

**Comment by stayingcool** [comment]
Yes. I want through this already by looking at other similar amplify issues. One thing to note though I couldn't see the Advanced option in the UI to skip a resource.

AWS CloudFormation console:

1.    Open the AWS CloudFormation console.

2.    From the Stack Name column, select the stack that's stuck in UPDATE_ROLLBACK_FAILED status.

3.    Choose Actions, and then choose Continue Update Rollback.

4.    (Optional) If you want to skip the resources, choose Advanced Options, and then enter the logical IDs of the resources that you want to skip.

**Comment by UnleashedMind** [comment]
@stayingcool 
In the meanwhile, you can try to skip the failed resources in the rollback, the following two short doc provides more information on how to get them done: 
https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-update-rollback-failed/
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-continueupdaterollback.html#nested-stacks

**Comment by UnleashedMind** [comment]
After the rollback is successful, and the stacks are in the "....COMPLETE" status, we can then check on your project, and make sure all the nodejs versions are correctly set, 
https://aws-amplify.github.io/docs/cli/lambda-node-version-update
Then we can try to execute another push.

**Comment by stayingcool** [comment]
I just ran the command to skip a resource. The command did not throw any console output, just completed it. 
Then by looking at the stack events in CloudFormation I see that it failed again with this error:

Timestamp | Logical ID | Status | Status reason
-- | -- | -- | --
2020-04-01 12:03:03 UTC+1100 | pnamar05first-20190511104149 | UPDATE_ROLLBACK_FAILED | Nested stack resources can only be skipped when their embedded stack statuses are one of [DELETE_COMPLETE, DELETE_IN_PROGRESS, DELETE_FAILED]

**Comment by UnleashedMind** [comment]
Have you tried to use the steps pointed out in the second doc for the nested stacks? 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-continueupdaterollback.html#nested-stacks

**Comment by stayingcool** [comment]
Thanks, I did not by referencing the ChildStackName.Logical_IDOfFailingResource. I think the RollBack completed.
Not sure though why the UI should show that in RED:
<img width="729" alt="UPDATE_ROLLBACK_COMPLETE" src="https://user-images.githubusercontent.com/31205483/78089962-94a17a80-7414-11ea-8e6f-7afdacd7ac43.png">

**Comment by brene** [comment]
> @brene - After zipping the folder it is 62 MB. I'm not sure if I'll be able to send that as an attachment in an email.

Yes, just upload it to any cloud storage Google Drive, OneDrive etc. and share the link via the email address. After we received it, you can disable the link.

**Comment by UnleashedMind** [comment]
Great!
Please find a way to share your amplify folder, make sure it's not public just in case it has confidential information. 
And you can go ahead with the checks on the node versions in the codebase. Use this doc as a guideline
https://aws-amplify.github.io/docs/cli/lambda-node-version-update

**Comment by stayingcool** [comment]
Thanks, amplify push went through the DEV environment successfully. 👍 

I have a similar issue in the PROD as well. I have to find another deployment window tonight to see if this will push the code changes there as well.

**Comment by stayingcool** [comment]
Thank you all @UnleashedMind , @brene and @kaustavghosh06 👍 

My production deployment went through good, this issue is good to close now.
