### ISSUE TITLE
Cannot read property 'forcePush' of undefined

### ISSUE THREAD

**Issue by killallskywalker** [aws-amplify/amplify-cli#3793]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Before updating to latest version , it dont have any problem to push the resources to the cloud . 

**Amplify CLI Version**
4.17.2

**To Reproduce**
Run amplify mock for the first time after creating the graphql resource and user pool resource 

**Expected behavior**
It supposed push the resource to aws services  . 

**Screenshots**
Screenshot provided 

**Desktop (please complete the following information):**
 - Macos catalina V.10.15.3
 - Node version - v12.16.1

**Comment by Jay2113** [comment]
I observed a similar error while using Amplify Storage API and trying to run amplify mock. This error is observed when I run amplify mock without pushing the auth resources to the backend.

**Screenshot of the error**

![Error](https://user-images.githubusercontent.com/38470430/77832450-95809680-710c-11ea-8b9c-53b82143c340.png)

However, now if I run amplify auth push the auth resources are pushed and updated in the backend. Amplify mock now runs as expected too!

**Amplify CLI Version**
4.17.1

**Comment by jhockett** [comment]
@killallskywalker thanks for the report. I can confirm what @Jay2113 said, and just running ```amplify push``` before ```amplify mock``` works for now
