### ISSUE TITLE
Using email instead of sub for ownership

### ISSUE THREAD

**Issue by egoossens** [aws-amplify/amplify-cli#3794]
**Which Category is your question related to?**

Auth

**What AWS Services are you utilizing?**

Cognito, AWS AppSync

**Provide additional details e.g. code snippets**

In multiple online examples, such as https://aws-amplify.github.io/docs/cli-toolchain/graphql#ownership-with-create-mutations, the user's email is used instead of the automatically generated sub. How can I configure this? I want my users to be identified by their email address and not sub. How can I use email as username, or at least include it as a identity claim in the access tokens? Thanks.

**Comment by yuth** [comment]
If you're using Cognito generated JWT token, the token should have the `email` passed in the field. You could update your`@auth` directive to use `email` as  `identityClaim` as [documented](https://docs.amplify.aws/cli/graphql-transformer/directives#custom-claims)

```gql
type Post @model
@model
@auth(rules: [
    {allow: owner, identityClaim: "email"},
])
{
  id: ID!
  owner: String
  postname: String
  content: String
}
```

**Comment by egoossens** [comment]
Thanks for getting back. I did try that at the time, without success. Is the context object populated with an ID token or an access token?  I parsed the Cognito generated access token and it didn't contain an email claim.

For the time being I switched to another service but if I get a chance to try again I'll let you know.

**Comment by vesters** [comment]
This way (identifyClaim: "email") did not work for me. I kept getting "DynamoDB:ConditionalCheckFailedException" when trying to update records.

My setup is more or less vanilla. Done with "amplify add auth"

Anything extra one has to do to get email included?

**Comment by yuth** [comment]
> Is the context object populated with an ID token or an access token? I parsed the Cognito generated access token and it didn't contain an email claim.

No the conext get populated with the token that is sent when making the GraphQL query.  Amplify JS sends `accessToken` by default but idToken` can be sent using the following code snippet

```javascript
amplify.configure({
  ...aws_exports,
  graphql_headers: async () => {
    try {
      const token = (await Auth.currentSession()).idToken.jwtToken;
      return { Authorization: token }
    }
    catch (e) {
        console.error(e);
        return {};
    }
  }
});
```

**Comment by vesters** [comment]
I'll try that. Thank you for this helpful snippet. 

Not sure where I could have found this in the docs, it does seems a bit hidden to me.

**Comment by jarrodwatts** [comment]
Just wanted to say a massive thank you @yuth - that works 😄💯 
I'd love to see some more info about this covered in the docs too.

**Comment by jarrodwatts** [comment]
I've just noticed using your solution breaks SSR Support in Next.JS😢. 
```No current user```: Any suggestions?
