### ISSUE TITLE
Pipeline resolvers, without lambda function

### ISSUE THREAD

**Issue by mdepascale** [aws-amplify/amplify-cli#3797]
**Which Category is your question related to?**
I'm trying to create a pipeline of resolvers without lambda function

**Amplify CLI Version** 
4.17.2

**Provide additional details e.g. code snippets**
```graphql
type Blog @model(mutations: null, subscriptions: null) {
     id: ID!
     name: String!
}

type Post @model(mutations: null, subscriptions: null){
     id: ID!
     title: String!
}

type Query {
     doubleResolver(ID: ID!): Blog
}
```

Let's say, for no particular reason, I want to create a Post and read a Blog, 
- can a resolver do an update and a get operation? something like [transact resolver](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-transact.html) but with update and get

Edit: I did more researches and found out the answers to the previous questions, now I just leave this one because I couldn't find it anywhere

**Comment by ammarkarachi** [comment]
@mdepascale Yes, you can use update/get in each resolver. Each function in the pipeline gets its own resolver.

**Comment by mdepascale** [comment]
thank you
