### ISSUE TITLE
Cannot add trigger lambda function on S3 bucket

### ISSUE THREAD

**Issue by daajack** [aws-amplify/amplify-cli#3800]
**Describe the bug**
I cannot add an existing trigger lambda function to my also existing storage bucket. I receive an error `Unable to validate the following destination configurations.`
I also tried to attach a new function but i had another error.
`Parameters: [storages3856d6b6aBucketName] do not exist in the template`

**Amplify CLI Version**
4.16.1

**To Reproduce**
With an existing storage and existing lambda function make :
```
amplify storage update
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Restrict access by? Both
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? read
? Select groups: admin
? What kind of access do you want for admin users? create/update, read, delete
? Do you want to add a Lambda Trigger for your S3 Bucket? Yes
? Select from the following options Choose an existing function from the project
? Select from the following options buildThumbnails
Successfully updated resource buildThumbnails locally
Successfully updated resource
```
**Screenshot**
`UPDATE_FAILED      S3Bucket           AWS::S3::Bucket         Mon Mar 30 2020 13:54:25 GMT+0000 (Coordinated Universal Time) Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: EF01864E188C4025; S3 Extended Request ID: IcbEGuwtOoxg9hooqiK/PkExQDv5TLJc7IcDd7GNAv42fim718j095qOgihok2f/PQtes2kttTE=)`

**Expected behavior**
Add a lambda trigger to S3 bucket

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v13.8.0

**Comment by kaustavghosh06** [comment]
Which region are you deploying to?

**Comment by daajack** [comment]
> 
> 
> Which region are you deploying to?

eu-central-1

**Comment by akshbhu** [comment]
Hi @daajack 

I am not able to reproduce the  issue by following the steps mentioned above.

1) Can you try this with the latest cli version and check if the issue is still occurring?
2) Can you mail the zip of amplify folder to amplify-cli@amazon.com so that I can reproduce the above issue?

**Comment by daajack** [comment]
I attached the trigger from the S3 console, and it works. Obviously, this is not a good solution.

1. I tried with last version but nothing changed
2. I cannot send it by email, the compressed directory is more than 300MB !

**Comment by akshbhu** [comment]
Hi @daajack 

I am not able to reproduce the issue by following the steps as you mentioned. 
Can you try with latest amplify version if the issue is still persists?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response. Please comment on this thread if you're still stuck with this issue.

**Comment by qinqin-wang** [comment]
I have the same issue, @daajack have you resolved this issue?

Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 3E691431C510D24B; S3 Extended Request ID: IxDayz31qkjA32r31SFIUGPgQRBx9rcQQFLEQRLSSTHnBXOCRky70ZQvcsBE2x2Lr1woe6WNMB4=; Proxy: null)

**Comment by daajack** [comment]
Hi,
First @kaustavghosh06, sorry for lack of response, I stopped working on that project :)
As I remember @qinqin-wang, i didn't really solved the problem. I just added manually the trigger into the s3 admin console.
