### ISSUE TITLE
"Learn More" Amplify Plugin Init Event Prompt

### ISSUE THREAD

**Issue by smp** [aws-amplify/amplify-cli#3809]
**Describe the bug**
When initializing a new Amplify CLI plugin and selecting the "learn more" radio button for "Which CLI events do you..." the CLI continues on as if I had selected "continue." It should emit information about each event to enable the user to make a choice regarding events. 

**To Reproduce**
$ amplify plugin init
? What should be the name of the plugin: amplify-chat
? Specify the plugin type category
? What Amplify CLI events do you want the plugin to handle?  (Select "learn more" and see the prompt continue on from this option)

**Comment by UnleashedMind** [comment]
Moving the cursor to `Learn more` does NOT select it, make sure you press the <space> key and the `Learn more` is actually selected before you press <enter> key, then you will see the information about the events.

**Comment by smp** [comment]
Ohhhhhh, I see, this is quite confusing for the first time user, but I understand why it's like this. It seems like the "learn more" radio button shouldn't be an option in this case as I would assume that by selecting "learn more" along with the default selections and hitting "enter" I would be learning more and continuing on from this prompt.  

I would suggest putting the explanation sentence into the radio button selection and omitting "learn more" from the radio selection. Unless there is a better way to "learn more" through this radio selection prompt.

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks. This is the behavior of a library that the CLI uses.
