### ISSUE TITLE
Installed amplify-cli and got this error: ENOENT: no such file or directory, ...team-provider-info.json'

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-cli#3812]
@UnleashedMind  I have just moved to a new machine and my project was running beautifully on the new machiine(with Api, Auth, Storage services via Amplify). I realised i needed to interact with amplify-cli, so I then installed `npm install -g @aws-amplify/cli`. I ran `amplify status`: 

```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | project     | Update    | awscloudformation | <-strangely updated?
| Auth     | project837477  | No Change | awscloudformation |
| Storage  | projectStorage | No Change | awscloudformation |
```

Strangely Api updated even though i've made no changes. Anyway, when i ran `amplify push`, i got the following error. 
`An error occurred during the push operation: ENOENT: no such file or directory, team-provider-info.json'`. This file exists, just as it did in my project folder on my last machine.

Then i tried `npm install -g @aws-amplify/cli@4.11.0` but still no luck to push. What on earth is going on? I'm paralyzed in my tracks right now and i have to kick on and complete this project. Please help!!

**Comment by kaustavghosh06** [comment]
@chai86 How did you move these files to your new machine? Did you also copy the `amplify/.config/local-env-info.json` from your old machine to the new one?

**Comment by chai86** [comment]
@kaustavghosh06 That file doesn't seem to exist in my current amplify folder (or even my old machine). I've only ever used amplify-cli (no console).

**Comment by chai86** [comment]
Current amplify folder: <img width="527" alt="Screen Shot 2020-03-31 at 18 25 39" src="https://user-images.githubusercontent.com/43324724/78056468-15149c80-737d-11ea-8638-5ee905302904.png">

cloud-backend-folder:
<img width="681" alt="Screen Shot 2020-03-31 at 18 26 17" src="https://user-images.githubusercontent.com/43324724/78056522-35445b80-737d-11ea-9f86-f7e42c274e61.png">

backend folder:
<img width="719" alt="Screen Shot 2020-03-31 at 18 27 12" src="https://user-images.githubusercontent.com/43324724/78056585-4c834900-737d-11ea-8d8d-663c72e1a23d.png">

This is the first time i'm interacting with amplify on this new machine

**Comment by kaustavghosh06** [comment]
It won't show up on your finder since its a . file - you'll have to look access it via your terminal or you'll have to enable "showing of hidden folder" for your Mac finder.

**Comment by chai86** [comment]
Found it thanks. I just checked, its precisely the same as the one on my new machine. I haven't run amplify configure (why would I? It's precisely the same project on a different machine, which is working and don't want to risk messing my current project up). Any idea whats missing here?

```
{
    "projectPath": "/Users/mitansolanki/Documents/GitHub/ProjectName",
    "defaultEditor": "code",
    "envName": "dev"
}
```

**Comment by UnleashedMind** [comment]
@chai86 
Could you just zip up your project's `amplify` folder and send the zip file over to us for diagnosis?

**Comment by chai86** [comment]
Sure no problem, let me know when you guys receive it.

**Comment by kaustavghosh06** [comment]
@chai86 Just try running `amplify configure project`. I believe the "projectPath" for your new machine would be different than your previous machine right? `amplify configure project` should be able to rectify that.

**Comment by chai86** [comment]
Yes project path has changed only slightly. I'm going to try and set the same project path as before and try again, to try not to risk an amplify configure yet. I'll give that a try and if not, i'll need guidance on the `amplify configure project` or `amplify pull`. Speak soon

**Comment by seanvm** [comment]
I just ran into a similar issue. I'm curious, in the path does it reference `amplify` twice?

e.g. `/amplify/amplify/team-provider-info.json`?

**Comment by chai86** [comment]
@seanvm nope just once

**Comment by chai86** [comment]
> @chai86 Just try running `amplify configure project`. I believe the "projectPath" for your new machine would be different than your previous machine right? `amplify configure project` should be able to rectify that.

@kaustavghosh06 I changed my path to the one i was using before, but now when i run `amplify push` i get the error: 
```
✖ There was an error pulling the backend environment dev.
An error occured during the push operation: ENOENT: no such file or directory, open '/Users/username/.aws/credentials
```

When i run `amplify configure project` it's like doing an `amplify init`. I'm being asked:

```
? Enter a name for the project: ProjectName
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using (Use arrow keys)
  angular 
  ember 
  ionic 
  react 
❯ react-native 
  vue 
  none 
etc....
```

I do not want to replace or ruin anything in my current backend or current project! Should i continue this process?

**Comment by chai86** [comment]
@UnleashedMind any thoughts on the above?

**Comment by chai86** [comment]
I also tried `amplify env add` to then hopefully then do an `amplify pull` and i received: 

```
Users-MBP-2:projectname username$ amplify env add
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✖ There was an error initializing your environment.
init failed
Error: ENOENT: no such file or directory, open '/Users/username/.aws/credentials'
    at Object.openSync (fs.js:462:3)
    at Proxy.readFileSync (fs.js:364:35)
    at Object.readFileSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:100:36)
    at Config.set (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:507:39)
    at Config.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:342:12)
    at Config.each (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:341:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/username/.aws/credentials'
}
```

Whats going on here?

**Comment by kaustavghosh06** [comment]
@chai86 Have you setup your new system with the AWS creds ad have an AWS profile on it?

**Comment by chai86** [comment]
@kaustavghosh06 No. I just copied my old react native project folder over. How do i do that? 

Also, won't amplify configure replace all my existing Auth, Api, Storage services?

**Comment by chai86** [comment]
I see it now! When i show hidden folders from my old machine, i see the `/username/.aws` folder. Let me copy that over to the new machine and try.

**Comment by kaustavghosh06** [comment]
@chai86 No amplify configure would setup AWS creds on your system. It won't replace all my existing Auth, Api, Storage services.

**Comment by chai86** [comment]
Perhaps getting somewhere now: BUT when i run `amplify status` i get:

`Current Environment: dev`

```
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth       | App5088f2a2  | Create    | awscloudformation |
| Api          | AppAsync        | Create    | awscloudformation |
| Storage  | AppS3storage | Create    | awscloudformation |
| Api         | AppAsync         | Update   | awscloudformation |
```
I can't afford for these services to get replaced/messed up if i `amplify push` 😳

**Comment by kaustavghosh06** [comment]
Is this because you are did an env add as mentioned here - https://github.com/aws-amplify/amplify-cli/issues/3812#issuecomment-608022843
Please go back to your original env - by using `amplify env chceckout <env-name>`
Copy your credentials file doesn't affect your `amplify` backend contents.

**Comment by chai86** [comment]
@kaustavghosh06 Phew, that command `amplify env checkout dev` did it. Then, what do i run? `amplify configure`?

**Comment by kaustavghosh06** [comment]
Your profile should be setup now. Can you check if you can `amplify push` now after making changes?

**Comment by chai86** [comment]
That's `amplify push`ed successfully 👌🏻

**Comment by UnleashedMind** [comment]
There's no need to create restore point, when you clone your project to another dev machine, you just need to make sure that the new machine has the proper aws configuration files under ~/.aws, and then run `amplify pull` and `amplify init` in sequence to setup your local development environments.

**Comment by nicog98** [comment]
> I just ran into a similar issue. I'm curious, in the path does it reference `amplify` twice?
> 
> e.g. `/amplify/amplify/team-provider-info.json`?

This is the problem for me, were you able to solve?

**Comment by r9software** [comment]
So the problem in my case it was I stoped the process in the middle causing a crash in amplify
I deleted everything inside of 
/home/whatever/.nvm/versions/node/v12.18.4/lib/node_modules/@aws-amplify/
and reinstalled amplify, that worked

**Comment by 0cv** [comment]
Spent quite some time and I figured out where it is. There is a file called `local-env-info.json` where the path to the project is configured. This is the file which needs to be updated when the path of the repo change. Now `amplify push / publish` works again
![image](https://user-images.githubusercontent.com/1253866/106720247-852a2980-6603-11eb-83f7-141791d466f6.png)

**Comment by tdnghia98** [comment]
> Spent quite some time and I figured out where it is. There is a file called `local-env-info.json` where the path to the project is configured. This is the file which needs to be updated when the path of the repo change. Now `amplify push / publish` works again
> ![image](https://user-images.githubusercontent.com/1253866/106720247-852a2980-6603-11eb-83f7-141791d466f6.png)

Thanks, works perfectly
