### ISSUE TITLE
Add Conflict Detection stops ElasticSearch streaming

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#3818]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
My team is implementing DataStore. As part of that implementation on our existing API we have updated the API to allow CONFLICT DETECTION. When I use AppSync to create a record it correctly adds a _version field and _lastChangedAt field. If I use an update command it correctly increments the _version field. And finally, if I delete the record a _deleted field is created and set to true and the _version is incremented.

What is not happening is that these records are no longer streaming to ElasticSearch.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.17.2

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

I reproduced this by creating a new API from scratch (amplify init, amplify add api (use standard one shown below and add searchable), amplify push) - then create a record and it doesn't go into ElasticSearch - but works in DynamoDB

type Todo
@searchable
@model {
  id: ID!
  name: String!
  description: String
}

**Expected behavior**

I expect that the record in its entirety should go into ElasticSearch - including the _version, _deleted and _lastChangedAt fields so that I can retrieve that information from ElasticSearch

**Additional context**

The workflow in my solution is that our app reads data from ElasticSearch and writes to DynamoDB - so I need to be able to query for what is deleted (exclude) and get the version in ElasticSearch

**Comment by sacrampton** [comment]
See attached screen shot from CloudWatch showing that "Cannot generate dynamic mappings of type [_version] for [_version]"

So I went to Kibana and tried to define _version as follows:

PUT /bom/_mapping/doc
{
    "properties": {
        "_version": {
            "type": "integer"
        }
    }
}

But then I got this error

{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[PIgDj_T][x.x.x.x:9300][indices:admin/mapping/put]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Field [_version] is defined twice in [doc]"
  },
  "status": 400
}


So when I looked up online, it appears that _version is a reserved variable in ElasticSearch....

So the Lambda function appears to be trying to stream _version to ElasticSearch, but that is when it then goes off the rails....


![ES ERROR](https://user-images.githubusercontent.com/6362888/78112913-a0a82f00-744a-11ea-8361-c9fb56505a5f.png)

**Comment by sacrampton** [comment]
Looks like #3796 is the same issue

**Comment by sacrampton** [comment]
If _version is a reserved field in ElasticSearch, can we modify python_streaming_function.py to map from _version to something else like __version or something similar?

**Comment by sacrampton** [comment]
@ammarkarachi

**Comment by sacrampton** [comment]
Last comment, I note that __typename has two(2) "__" - if you change it all to __version, __deleted, __lastChangedAt then there is no conflict with anything in ElasticSearch.

**Comment by ammarkarachi** [comment]
@sacrampton thanks for the research I will mark it as a bug and we are likely going to introduce some kind of conflict detection

**Comment by attilah** [comment]
Duplicated issue, closing in favor of: #3796
