### ISSUE TITLE
TransactWriteItems resolver, how to assign DynamoDb table name

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#3819]
AppSync resolvers support **TransactWriteItems** operation and in **transactItems** I have to define DynamoDb table for each item, but Amplify adds some suffix to table names. Is there some way to retrieve this suffix in resolver?

**Which Category is your question related to?**
Amplify, AppSync, DynamoDb resolver, TransactWriteItems.

**Amplify CLI Version** 
4.17.2

**Comment by lenarmazitov** [comment]
Seems like Amplify is not yet supported TransactWriteItems. I got this error:

```
{
  "data": {
    "createMessage": null
  },
  "errors": [
    {
      "path": [
        "createMessage"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unsupported operation 'TransactWriteItems'."
    }
  ]
}
```

**Comment by attilah** [comment]
@lenarmazitov you don't need to access the table name as it is defined as part of your DataSource definition, the resolver's output JSON will be directed to the configured DynamoDB table automatically.

In the AppSync documentation there is a full [example](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-transact.html) for TransactWriteItems.

If this does not answer your question, please elaborate on your use case which requires the table name in the resolver.

**Comment by lenarmazitov** [comment]
@attilah
but **table** is mandatory field like described [here](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html#aws-appsync-resolver-mapping-template-reference-dynamodb-transact-write-items) 

Now I stuck with error **Unsupported operation 'TransactWriteItems'.**  
Though Transact**Get**Items works fine.

**Comment by lenarmazitov** [comment]
@attilah I think it will be very useful if transactions will be available in Amplify. 
Because we can get rid of some pipeline resolvers, which perform conditional check.
Why we should get rid of pipeline resolvers? Because DataStore and new versioning are not supported pipeline resolvers.

**Comment by lenarmazitov** [comment]
seems like same issue already [exists](https://github.com/aws-amplify/amplify-cli/issues/2092)

closing this then.

**Comment by regenrek** [comment]
Hi @lenarmazitov did you find a solution for the error:

```"Unsupported operation 'TransactWriteItems'."```

**Comment by lenarmazitov** [comment]
@regenrek 

Check if you use old mapping template version. Currently there are two versions **2018-05-29** and **2017-02-28**. Try to use new one.
You can read [here](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-changelog.html)

Somehow I had this issue with new version, write if you find out how to reproduce this.
