### ISSUE TITLE
Can I enable previews using the CLI?

### ISSUE THREAD

**Issue by berniedurfee** [aws-amplify/amplify-cli#3820]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Hosting

**Amplify CLI Version** 
4.17.2

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**

**Comment by attilah** [comment]
@berniedurfee could you please provide some context on your question? what kind of "preview" you'd like to enable?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
