### ISSUE TITLE
Invoking the Hello World lambda function locally returns nothing

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#3823]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
1. Create a "Hello World" lambda function.
2. Invoking the function locally returns nothing.
```
$ amplify function invoke myLambda
Using service: Lambda, provided by: awscloudformation
? Provide the name of the file that contains your handler function: index.js
? Provide the name of the handler function to invoke: handler
? Provide the relative path to the event JSON object: event.json
Testing function locally
```
3. No errors and no response data. The function name is correct - retrieved from the `amplify status` command results.

The function is simply the "Hello World" function example provided. 

The event.json test data I've tried is:

```
{
    "httpMethod": "GET",
    "path": "/generate"
}

```
and the original example

```
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}

```

The function worlds once deployed and testing from the browser.

**Amplify CLI Version**
4.17.2

**To Reproduce**
As above ^

**Expected behavior**
The same result as when invoking via the browser.
"Hello from Lambda!"

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Node v 12.11.1

**Comment by nikhname** [comment]
Hi @kylekirkby, we now use ```amplify mock <yourFunction>``` for this functionality. Could you give that a try and see if this issue persists?

**Comment by attilah** [comment]
@kylekirkby please upgrade to the 4.18.0 version and use the above command to invoke it locally.

**Comment by stevelizcano** [comment]
This issue is still going on, in 4.18 if I init a new amplify function, edit nothing,  push it to the cloud, it errors and says "CustomMessage failed with error index.handler is undefined or not exported."

**Comment by reefloretto** [comment]
> This issue is still going on, in 4.18 if I init a new amplify function, edit nothing, push it to the cloud, it errors and says "CustomMessage failed with error index.handler is undefined or not exported."

getting the same error as @stevelizcano

**Comment by nikhname** [comment]
@stevelizcano @reefloretto This is a known issue that we have a fix for (https://github.com/aws-amplify/amplify-cli/pull/3928), it is pending a release. As a workaround you can move the index.js file to your src folder and do a push.
