### ISSUE TITLE
API mock fails to start with inline Request-/ResponseMappingTemplate

### ISSUE THREAD

**Issue by jwoehrle** [aws-amplify/amplify-cli#3834]
**Describe the bug**
when using a graphql api with a custom CFN template which includes an inline `RequestMappingTemplate` or `ResponseMappingTemplate` the api mocking crashes at startup:
```
$amplify mock api
GraphQL schema compiled successfully.

Edit your schema at xxx/schema.graphql or place .graphql files in a directory at xxx/schema

Failed to start API Mock endpoint SyntaxError: Unexpected token u in JSON at position 0
```

**Amplify CLI Version**
```
$amplify --version                                                                                             
4.17.2
$node --version                                                                                                
v12.11.1
$yarn --version                                                                                                
1.22.4
```
**To Reproduce**
See the example project at https://github.com/jwoehrle/amplify-issue-inline-template. Specifically the custom CFN with inline template:
https://github.com/jwoehrle/amplify-issue-inline-template/blob/master/amplify/backend/api/example/stacks/CustomResources.json#L40-L54

try to run `amplify mock api`

**Expected behavior**
1. The mock runs also with inline mapping templates
2. in case of failure the mock returns a concise error message

**Desktop (please complete the following information):**
 - OS: Mac 
 - Node Version: 12.11.1

**Additional context**
I was able to trace down the issue to https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/CFNParser/resource-processors/appsync.ts#L181-L182

It seems like the CFNParser is only looking for `RequestMappingTemplateS3Location ` and `ResponseMappingTemplateS3Location ` and not taking into account that one can inline the template into the CFN. I confirmed that using the S3Location makes the mock come up. 

However in my case I cannot use the workaround of using an s3 location as I need a stack `Ref` value to inject the environment and apiId into the template (see https://github.com/aws-amplify/amplify-cli/issues/1946#issuecomment-536469005). 

Best
Jörg

**Comment by yuth** [comment]
Amplify CLI 4.20.0 has this fix
