### ISSUE TITLE
timeline for migration path from mobile CLI to amplify CLI

### ISSUE THREAD

**Issue by sadooghi** [aws-amplify/amplify-cli#385]
We have already built an app using Mobile CLI but want to transfer to amplify CLI. Can you please provide timelines for the migration path from Mobile CLI to Amplify CLI (i.e. support/import existing resources from mobile hub to amplify). We want to invest resources for the transition and we (and many other people using Mobile hub) would better utilize their resources if they knew rough timelines for the migration. For instance is it ~1-2 months, ~6-7 months or over a year.

**Comment by swaminator** [comment]
@sadooghi We just released a Mobile Hub to Amplify CLI migrator that you can access here: https://github.com/awslabs/amplify-mobilehub-migrator. This will help you import your Mobile Hub resources into an Amplify project, give you an exports file, and allow you to leverage Amplify CLI features such as GraphQL APIs, Codegen, and the GraphQL Transform. Would love your feedback.
