### ISSUE TITLE
Bug in $util.transform.toDynamoDBFilterExpression with nested ors

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#3850]
**Describe the bug**
A filter query with nested ORs in AppSync does not map to a correct DynamoDB Expression. Some values are overwritten. 

**Amplify CLI Version**
4.16.1

**To Reproduce**

1. Simplified graphql schema to setup the repro: 

```
type Clinic @model {
   id: ID!
  patients: [Patient!] @connection(name: "ClinicPatients", sortField: "updatedAt")
}

type Patient @model {
   id: ID!
   phone: AWSPhone
}
```

2. Now create a clinic in the db as well as a patient that belongs to that clinic with phone # of 5039260766 

Now run the following graphql query (let's call it Query A): 

```
query GetPatientsForClinic {
   getClinic(id: "<your-id-here>") {
      id
      patients (
      limit: 1000
         filter: {
        or: [
            {
               phone: {
                eq:"5039260766"
              }
          },
           {
              or: [
                {
                  phone: {
                    eq: "5038768765"
                  }
                }
            ]
          }
        ]
      }
    ) {
      items {
        phone
      }
      nextToken
    }
   }
}
```
**You will get no patients back.** 

Now run the following query (let's call it Query B): 

```
query GetPatientsForClinic {
   getClinic(id: "<your-id-here>") {
      id
      patients (
      limit: 1000
         filter: {
        or: [
            {
               phone: {
                eq:"5039260766"
              }
          },
           {
              phone: {
                eq: "5038768765"
              }
          }
        ]
      }
    ) {
      items {
        phone
      }
      nextToken
    }
   }
}
```

**You will correctly get patient with phone # 5039260766 back.** 

**Expected behavior**
Like Query B, Query A should also return the patient. 

**Additional context**
The problem is the dynamodb expression generated for Query A is wrong. It is the following: 

`    "transformedTemplate": "{\n  \"version\": \"2017-02-28\",\n  \"operation\": \"Query\",\n  \"query\":   {\"expression\":\"#connectionAttribute = :connectionAttribute\",\"expressionNames\":{\"#connectionAttribute\":\"patientClinicId\"},\"expressionValues\":{\":connectionAttribute\":{\"S\":\"<your-id-here>\"}}},\n  \"scanIndexForward\":   true\n  ,\n  \"filter\":   {\"expression\":\"((#phone = :or_0_phone_eq) OR (#phone = :or_0_phone_eq))\",\"expressionNames\":{\"#phone\":\"phone\"},\"expressionValues\":{\":or_0_phone_eq\":{\"S\":\"5038768765\"}}}\n  ,\n  \"limit\": 1000,\n  \"nextToken\":   null\n  ,\n  \"index\": \"gsi-ClinicPatients\"\n}"
`

**You can see there is only one phone # in this expression, the phone # of 5039260766 is missing.** 

This is the dynamodb expression for Query B - it is correct: 

`    "transformedTemplate": "{\n  \"version\": \"2017-02-28\",\n  \"operation\": \"Query\",\n  \"query\":   {\"expression\":\"#connectionAttribute = :connectionAttribute\",\"expressionNames\":{\"#connectionAttribute\":\"patientClinicId\"},\"expressionValues\":{\":connectionAttribute\":{\"S\":\"<your-id-here>\"}}},\n  \"scanIndexForward\":   true\n  ,\n  \"filter\":   {\"expression\":\"((#phone = :or_0_phone_eq) OR (#phone = :or_1_phone_eq))\",\"expressionNames\":{\"#phone\":\"phone\"},\"expressionValues\":{\":or_0_phone_eq\":{\"S\":\"5039260766\"},\":or_1_phone_eq\":{\"S\":\"5038768765\"}}}\n  ,\n  \"limit\": 1000,\n  \"nextToken\":   null\n  ,\n  \"index\": \"gsi-ClinicPatients\"\n}"`

**You can see both phone #s (5039260766 and 5038768765) are in this expression.**

**Comment by SwaySway** [comment]
Hello @hisham the second Query B is the correct way to format that query. The first, Query A, is essentially generating a filter where the 2nd statement has nothing to `OR` against, which could lead to the utility function formatting the expression value incorrectly.
ex. `( (statement1) OR (statement2 OR) )`

We'll take note of this as a potential validation enhancement to discuss with the AWS AppSync team.

**Comment by hisham** [comment]
Hi @SwaySway  - the example I gave is just a simplified repro case. I ran into this bug in cases where there were multiple conditions in the OR and values were getting overridden. From my testing this is a bug not an enhancement.

Here is an example of a more realistic query that was incorrectly mapped to a dynamodb expression - in this case I want patients with phone === 5039260766 OR (phone === 5038768765 OR email === test@gmail.com): 

```
query GetPatientsForClinic {
   getClinic(id: "<your-id-here>") {
      id
      patients (
      limit: 1000
         filter: {
        or: [
            {
               phone: {
                eq:"5039260766"
              }
          },
           {
              or: [
                {
                  phone: {
                    eq: "5038768765"
                  },
                  email: {
                    eq: "test@gmail.com"
                  },
                }
            ]
          }
        ]
      }
    ) {
      items {
        phone
      }
      nextToken
    }
   }
}
```
It didn't work. If you want, I can try again and send you more details including the dynamodb expressions it maps to.

**Comment by hisham** [comment]
Just realized you can argue the second query I sent is also not "optimal". Here is a third query that is more realistic and is closer to the query we were running: 

It's basically` patient === 5039260766 || ( firstName === john && lastName === smith && (phone === 5038768765 || email === test@gmail.com))`

```
query GetPatientsForClinic {
   getClinic(id: "<your-id-here>") {
      id
      patients (
      limit: 1000
         filter: {
        or: [
            {
               phone: {
                eq:"5039260766"
              }
          },
           {
              { firstName: 'john' },
              { lastName: 'smith'},
              or: [
                {
                  phone: {
                    eq: "5038768765"
                  },
                  email: {
                    eq: "test@gmail.com"
                  },
                }
            ]
          }
        ]
      }
    ) {
      items {
        phone
      }
      nextToken
    }
   }
}
```
