### ISSUE TITLE
Many-to-Many relationship for single type

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-cli#3861]
**Which Category is your question related to?**
GraphQL schema

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
I am trying to define a many-to-many relationship for a single type. The use case is people who are related to one another in a supervisor/subordinate situation, where supervisors can have multiple subordinates and vice versa. I've tried the following (using the many-to-many example in the GraphQL [documentation](https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage-2) as a guide) but I am getting errors when I try to query data. Is it possible to define many-to-any for a single type? If so, what am I doing wrong?

Schema:
```
type Person @model {
  id: ID!
  title: Title! @connection
  mainSupervisor: Position @connection
  subordinates: [SuperSub]
    @connection(keyName: "bySupervisor", fields: ["id"])
  supervisors: [SuperSub]
    @connection(keyName: "bySubordinate", fields: ["id"])
}

type SuperSub
  @model(queries: null)
  @key(name: "bySupervisor", fields: ["supervisorID", "subordinateID"])
  @key(name: "bySubordinate", fields: ["subordinateID", "supervisorID"]) {
  id: ID!
  supervisorID: ID!
  subordinateID: ID!
  supervisor: Person! @connection(fields: ["supervisorID"])
  subordinate: Person! @connection(fields: ["subordinateID"])
}
```
Query:
```query ListPersons {
  listPersons(limit: 1000) {
    items {
      id,
      supervisors {
        items {
          id
        }
      }
      subordinates {
        items {
          id
        }
      }
    }
  }
}
```
Error message:
`The table does not have the specified index: bySupervisor`
`The table does not have the specified index: bySubordinate`

When I examine the SuperSub table in DynamoDB it has both `bySupervisor` and `bySubordinate` GSI partition keys, but the Person table doesn't and I don't see why AppSync would expect it to have those keys.

Supervisor/subordinate is not the primary purpose of this app so I'd rather not define additional Supervisor and Subordinate types. But if that's the only way to accomplish this, then I can definitely try it out.

**Comment by sopranolinist** [comment]
Any update on this?

**Comment by nikhname** [comment]
Hi @sopranolinist, yes you can create a self-referential many-to-many relationship for the Person type. Just be sure to name the connections separately to avoid conflicts. 

```graphql
type Person @model {
  id: ID!
  subordinates: [Person] @connection(name: "PersonSubordinate", fields: ["id"])
  supervisors: [Person] @connection(name: "PersonSupervisor", fields: ["id"])
  description: String
}
```
Please feel free to comment if you have further questions.

**Comment by sopranolinist** [comment]
@nikhname this appears to be two separate 1-to-many connections, not two linked 1-to-many connections, which is what I'm after. Suppose I have two Persons, `123` and `456`. If I implement your suggested schema and then run the following mutation to make `123` a supervisor of `456`:

```
updatePerson(input: {
    id: "456"
    supervisorID: "123"
  }) {
    id
  }
```
And then do the following query:
```
listPersons {
    items {
      id
      supervisors {
        items {
          id
        }
      }
      subordinates {
        items {
          id
        }
      }
    }
  }
```
The output from the query shows that Person `123` has subordinate `456` but Person `456` does **not** have supervisor `123`:
```
        {
          "id": "456",
          "supervisors": {
            "items": []
          },
          "subordinates": {
            "items": []
          }
        },
        {
          "id": "123",
          "supervisors": {
            "items": []
          },
          "subordinates": {
            "items": [
              {
                "id": "456"
              }
            ]
          }
        }
```

I'm looking for a schema that would update both Person items, after running the above mutation, to produce the following query output:
```
        {
          "id": "456",
          "supervisors": {
            "items": [
              {
                "id": "123"
              }
            ]
          },
          "subordinates": {
            "items": []
          }
        },
        {
          "id": "123",
          "supervisors": {
            "items": []
          },
          "subordinates": {
            "items": [
              {
                "id": "456"
              }
            ]
          }
        }
```

**Comment by sopranolinist** [comment]
Also, while I can list multiple people as subordinates, e.g. `1` and `3` are supervisors of `2`:

```
  {
    "id": "2",
    "supervisors": {
      "items": [
        {
          "id": "1"
        },
        {
          "id": "3"
        }
      ]
    }
  }
```

I can't figure out how to make those same people supervisors for multiple different people, e.g. `1` and `3` are supervisors of both `2` and `4`:

```
  {
    "id": "2",
    "supervisors": {
      "items": [
        {
          "id": "1"
        },
        {
          "id": "3"
        }
      ]
    }
  },
  {
    "id": "4",
    "supervisors": {
      "items": [
        {
          "id": "1"
        },
        {
          "id": "3"
        }
      ]
    }
  }
```

**Comment by sopranolinist** [comment]
Ok, the following schema appears to be working for me. It took me a bit to figure out how to adapt the many-to-many example [here](https://docs.amplify.aws/cli/graphql-transformer/directives#many-to-many-connections) to a single type instead of two different types (other unrelated schema fields have been left out).

```
type Person
  @model {
  id: ID!
  .
  .
  .
  supervisors: [SuperSub] @connection(keyName: "bySubordinate", fields: ["id"])
  subordinates: [SuperSub] @connection(keyName: "bySupervisor", fields: ["id"])
}

type SuperSub
  @model
  @key(name: "bySupervisor", fields: ["supervisorID", "subordinateID"])
  @key(name: "bySubordinate", fields: ["subordinateID", "supervisorID"]) {
  id: ID!
  supervisorID: ID!
  subordinateID: ID!
  supervisor: Person! @connection(fields: ["supervisorID"])
  subordinate: Person! @connection(fields: ["subordinateID"])
}
```

**Comment by nikhname** [comment]
These connections looks good to me, please feel free to comment if there are further questions!
