### ISSUE TITLE
GraphQLResult import error in generated API.service.ts

### ISSUE THREAD

**Issue by mcroker** [aws-amplify/amplify-cli#3863]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Generated src/app/API.service.ts generates this compile error
```
ERROR in src/app/API.service.ts:6:31 - error TS2307: Cannot find module '@aws-amplify/api/lib/types'.

6 import { GraphQLResult } from "@aws-amplify/api/lib/types";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This seems to be a new regression defect, following updating aws-amplify package to 3.0.5. (@latest at time of issue).

**Amplify CLI Version**
4.17.2

**To Reproduce**
Generate any schema using amp-cli 4.17.2 with aws-amplify 3.0.5

**Expected behavior**

The definition seems to have moved, and replacing the generated code with
```
import { GraphQLResult } from "@aws-amplify/api/lib"
```
resolves the issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by yuth** [comment]
Closing the issue as the fix is merged. Please feel free to re-open if the issue still persists
