### ISSUE TITLE
Only one CloudFormation template is allowed in the resource directory

### ISSUE THREAD

**Issue by pnm563** [aws-amplify/amplify-cli#3866]
Trying to add a function using the command `amplify function add`. At the edit local lambda function prompt, an `UnhandledPromiseRejectionWarning` is seen. However, the function wizard finishes and reports success.

On sending `amplify push`, an error occurs saying "Only one CloudFormation template is allowed in the resource directory". The push is not successful.

I have managed to successfully push `auth` and `storage`. Only `function` reports these errors.

**Amplify CLI Version**
4.17.1

**To Reproduce**
Run `amplify function add`. See the screenshots for the answers that were given that led to the error.

**Expected behavior**
I expected the command to push the changes to the AWS environment successfully, as they had done for `auth` and `storage`

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
Windows 10 Pro Build 18363
node version 12.16.1

**Additional context**
Text file containing the exception also attached
![Capture](https://user-images.githubusercontent.com/21175423/78456104-b19aaf80-7699-11ea-8d3d-e445a14d5aff.PNG)
[UnhandledPromiseRejectionWarning.txt](https://github.com/aws-amplify/amplify-cli/files/4431932/UnhandledPromiseRejectionWarning.txt)

**Comment by kaustavghosh06** [comment]
@pnm563 This was a bug tied to windows platform which we fixed in v4.17.2. Could please install the latest version of the CLI - remove the added function and then re-add it with the latest version of the CLI? Please comment on this issue if you still see the same issue.

**Comment by pnm563** [comment]
@kaustavghosh06 All working now, thank you. 👍
