### ISSUE TITLE
Cannot get GraphQL Endpoint in Lambda function 

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#3867]
I've added the permission for my lambda function to access my GraphQL API but when I access `process.env` the variable is not added instead I get the name of the variable again?

I'm not sure if it's related but the variables that amplify adds to the top of the lambda functions source are duplicated..

```
var apiXGraphQLAPIIdOutput = process.env.API_SOCIALIMAGEAPP_GRAPHQLAPIIDOUTPUT
var apiXGraphQLAPIIdOutput = process.env.API_SOCIALIMAGEAPP_GRAPHQLAPIIDOUTPUT
```

but when logging this value to the console in my Lambda function I'm getting this returned:

```
 env: {
    API_SOCIALIMAGEAPP_GRAPHQLAPIENDPOINTOUTPUT: 'apisocialimageappGraphQLAPIEndpointOutput',
    AWS_LAMBDA_FUNCTION_VERSION: '$LATEST',
```

I've run:
```
amplify update function
```
and made sure that the function has access to the graphql api.

I've also run 
```
amplify update api
```
to make sure the api has the correct IAM auth permission.

I'm also using the latest cli version:
`4.18.0-beta.3`

All my other process.env variables are fine but the GraphQL endpoint one is incorrect. Any ideas folks? Am I missing something trivial here?

Best regards!

Kyle

**Comment by kylekirkby** [comment]
I've just created another lambda function with the Hello World template and the permissions to access GraphQL. This function outputs the GraphQL endpoint correctly. So somehow, the function I described above had got itself into a "confused and broken" state. Maybe to do with the duplicate variables being added by amplify?

A hacky solution to those who get stuck with this :)

**Comment by edwardfoyle** [comment]
Hi @kylekirkby, [this commit](https://github.com/aws-amplify/amplify-cli/commit/d586863aabcb1ad2fc4d8ee1bd0e693a4d86d0ea) fixes the duplicate environment variable issue. I'm going to close this issue and track the missing graphQL permissions here: https://github.com/aws-amplify/amplify-cli/issues/3941
