### ISSUE TITLE
Cognito Groups Limit

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3877]
**Which Category is your question related to?**
Cognito Groups Limit

**What AWS Services are you utilizing?**
Cognito User Pool Autnetication

**Provide additional details e.g. code snippets**
I was using the Cognito user pool for authentication in my app but when I created more than 500 groups, it threw an error saying that I have exceeded the limit. 

But When I saw the documentation for Cognito, it says that the hard limit is 10,000.
https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html

Which one is correct?

If its 500 then what should I do to increase it?

**Comment by undefobj** [comment]
Limits can be increased through a support case: https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

**Comment by rehanbabertkxel** [comment]
@undefobj , in the AWS Cognito docs, it says that 10,000 is a hard limit for the Number Of Cognito Groups in a User Pool.
Is there a way to increase that or not?

**Comment by kaustavghosh06** [comment]
@rehanbabertkxel You’ll have to contact AWS support as @undefobj mentioned, to increase the limit to the hard limit. By default all AWS accounts have a soft limit which is 500 in this case, but can be increased on a per case/account basis to the hard limit after contacting AWS support.

**Comment by rehanbabertkxel** [comment]
@kaustavghosh06 , how can I check the limit on my account?

**Comment by kaustavghosh06** [comment]
@rehanbabertkxel I don't believe you can check service limit on the AWS Console. The AWS support will be able to help you out though.
