### ISSUE TITLE
One to one connections

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#3878]
I'm getting the following error when I attempt to compile my schema:

`InvalidDirectiveError: Connection is to a single object but the keyName <key-name> was provided which does not reference the default table.`

Is it possible to define a one-to-one relationship with a keyName argument? 

**Which Category is your question related to?**
GraphQL compile

**Amplify CLI Version** 
4.17.2

**Comment by undefobj** [comment]
Can you please provide your schema?

A 1:1 relationship would be covered by "Has One" in the following `@connection` documentation: https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection

**Comment by kldeb** [comment]
@undefobj I'm confused about how to set a one to one using `@key`...

For this use case, a customer can only be referred by one other customer, but can refer many customers. 

Here's the stripped down schema with relative parts:

```gql
type Customer
  @model
  @key(fields: ["customerId"])
{
  customerId: ID!
  firstName: String!
  lastName: String!
  referrals: [Referral]
    @connection(keyName: "referralsByCustomer", fields: ["customerId"])
  referredBy: [Referral]
    @connection(keyName: "referralsByReferralCustomer", fields: ["customerId"])
  owner: String
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type Referral
  @model
  @key(fields: ["referralId"])
  @key(
    name: "referralsByCustomer"
    fields: ["customerId"]
    queryField: "referralsByCustomer"
  )
  @key(
    name: "referralsByReferralCustomer"
    fields: ["referralCustomerId"]
    queryField: "referralsByReferralCustomer"
  ) {
  referralId: ID!
  firstName: String!
  lastName: String!
  email: String!
  customerId: ID!
  referralCustomerId: ID
  owner: String
  createdAt: AWSDateTime
}
```

if i change: 
```gql
  referredBy: [Referral]
    @connection(keyName: "referralsByReferralCustomer", fields: ["customerId"])
```
to:

```gql
  referredBy: Referral
    @connection(keyName: "referralsByReferralCustomer", fields: ["customerId"])
```
then gql-compile reports error above.

It just occurred to me that i probably need to store the referral id in the customer as well and then lookup on referralId.

**Comment by kldeb** [comment]
When I added the id to the customer type with a connection this issue came up: https://github.com/aws-amplify/amplify-cli/issues/3275

**Comment by edwardfoyle** [comment]
Hi @kldeb yes you are correct, you'll need to store the referralId with the customer. Unfortunately there's no great workaround to #3275 at this time. You might be able to get the behavior you want by putting a placeholder value for referralId in the customer record if there is no referralId for the customer:
```graphql
type Customer @model {
	id: ID!
	referredBy: Referral @connection(fields: ["referralId"])
	referralId: ID!
	name: String!
}

type Referral @model {
	id: ID!
	name: String!
}
```
When creating a customer without a referral, you can put a placeholder value in the referralId which means that the referredBy field is going to come back null in queries.

I'm going to close this issue and you can track the progress of optional connections in #3275

**Comment by kylekirkby** [comment]
I'm getting this error when attempt to compile the following schema. Any ideas @edwardfoyle @akshbhu ?

```gql

type User
	@model
	@key(name: "byUserEmail", fields: ["email"]) {
	id: ID!
	name: String!
	email: ID!
	status: UserStatus!
	bio: String
	groups: [GroupUser] @connection(keyName: "byUser", fields: ["email"])
	image: String
	twitter: String
	github: String
	website: String
}
type GroupUser
	@model
	@key(name: "byUser", fields: ["userId", "groupId"])
	@key(name: "byGroup", fields: ["groupId", "userId"]) {
	id: ID!
	groupId: ID!
	userId: ID!
	user: User! @connection(keyName: "byUserEmail", fields: ["userId"])
	group: Group! @connection(fields: ["groupId"])
}
type Group
	@model {
	id: ID!
	name: String!
	users: [GroupUser] @connection(keyName: "byGroup", fields: ["id"])
	permissions: [GroupPermission] @connection(keyName: "byGroup", fields: ["id"])
	permissionSets: [GroupPermissionSet] @connection(keyName: "byGroup", fields: ["id"])
}
```

results in:

```bash

$ amplify api gql-compile
$ InvalidDirectiveError: Connection is to a single object but the keyName byUserEmail was provided which does not reference the default table.
```

**Comment by edwardfoyle** [comment]
@kylekirkby The has-one connection on GroupUser.user can only reference the primary index of the User table (ie. you can't specify a keyName for has-one connections

**Comment by kylekirkby** [comment]
> @kylekirkby The has-one connection on GroupUser.user can only reference the primary index of the User table (ie. you can't specify a keyName for has-one connections

Thanks for the info @edwardfoyle! 🎉
