### ISSUE TITLE
Custom Resolver - Unsupported operation 'BatchDeleteItem'/'BatchPutItem'

### ISSUE THREAD

**Issue by regenrek** [aws-amplify/amplify-cli#3889]
Hi,

I've written a custom resolver with `BatchPutItem`and `BatchDeleteItem`. Everytime I run a mutation with this resolver I get 

```json
{
  "data": {
    "batchDeleteBusinessList": null
  },
  "errors": [
    {
      "path": [
        "batchDeleteBusinessList"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 38,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unsupported operation 'BatchDeleteItem'."
    }
  ]
}
```

or `"message": "Unsupported operation 'BatchPutItem'."`

* req
```
#set($ids = [])
#foreach($id in ${ctx.args.input})
    #set($pkey = {})
    $util.qr($pkey.put("id", $util.dynamodb.toString($id)))
    $util.qr($ids.add($pkey))
#end
{
  "version": "2018-05-29",
  "operation": "BatchDeleteItem",
  "tables": {
      "BusinessList-dzqohgcrhvhptkhcfvrvlkxdsy-dev": $utils.toJson($ids)
  }
}
```

* Mutation.batchDelete.res.vtl.
```
#if ($ctx.error)
    $util.appendError($ctx.error.message, $ctx.error.type)
#end
$util.toJson($ctx.result.data["BusinessList-dzqohgcrhvhptkhcfvrvlkxdsy-dev"])
```

* Mutation.batchDelete.res.vtl
```
  batchDeleteBusinessList(input: [
    "c279aa14-0f68-4a26-a18f-bb854cb185c9",
    "8465e9f1-765c-43a6-9b19-a6b73b7fb762"
  ]) {
    id
  }
```

Any ideas?

**Comment by SwaySway** [comment]
Hello @regenrek 
Do you have Conflict Detection Enabled in your GraphQL API?

**Comment by regenrek** [comment]
Hi @SwaySway 

I'm not sure. I think I chose "no" on amplify cli. I mean I have a _version field in dynamodb. So I'm not 100% sure about it.

How can I track this or how is it related to the error so I can inspect it.

**Comment by SwaySway** [comment]
You can check if this is enabled by checking your `transformer.conf.json` if it contains a ResolverConfig set up. I was able to get this working on a project that does not have conflict detection enabled and I was able to reproduce this issue on a project with this enabled.

**Comment by regenrek** [comment]
Hi

@SwaySway thank you very much this was the last piece of the puzzle. 

This issue was driving me crazy the whole weekend. It's well hidden in the docs I expected to read something the confliction detection constraint here 
- https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html or here
- https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

Thanks!

**Comment by grant-d** [comment]
@SwaySway , is `TransactionWriteItems` supported with Conflict Detection? I don't see anything specifically about that in the doc you mentioned (unless I missed it)
Getting a similar error and guessing it's related
