### ISSUE TITLE
Make auto-generated cognito user pool & identity pool use project name

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-cli#389]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When a new API is created using the Amplify CLI, the CLI autmatically recognizes this & uses it as the name in the prompt. Currently, when using the CLI to create authentication using the preconfigured options, the CLI creates a project name similar to cognitode149d10_userpool_de149d10
 & cognitode149d10_identitypool_de149d10. Is there any way we could prepend the project name to these strings so they will be more intuitive?

**Comment by dabit3** [comment]
@d8niz not sure, I'll cc @haverchuck @mlabieniec

**Comment by webberwang** [comment]
The names are very unfriendly, having some way to choose them would be great

**Comment by markcarroll** [comment]
Do you have any update?

Can I manually change the Cognito name in the local files before I do a `amplify push`? The random name is quite unfriendly, especially when you have more than one Amplify project in your Cognito account.

**Comment by dabit3** [comment]
cc @kaustavghosh06, any ideas on this? Seems like we could use at least the folder name to generate the name for the cognito user pool, or maybe the name in package.json?

**Comment by kaustavghosh06** [comment]
@dabit3 Yes, I'll prioritize this. Should be a relatively simple task. Any PR takers? :)
The change would go into this file and line number - https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/assets/cognito-defaults.js#L31

**Comment by dabit3** [comment]
Would something like this work?

```
const path = require('path')
const projectPath = process.cwd()
const normalizedPath = path.basename(projectPath)

const generalDefaults = () => ({
  resourceName: `${normalizedPath}_cognito${sharedId}`,
  authSelections: 'identityPoolAndUserPool',
  ...roles,
});
```

**Comment by kaustavghosh06** [comment]
@dabit3 

You can change const generalDefaults = () -> const generalDefaults = (projectName) since I checked that we pass in projectName to this function but just don't define it as a parameter in the generalDefaults() function and then use {projectName} instead of "cognito" . GIve that a try, I think that should work.

**Comment by dabit3** [comment]
So something like this? :

```
const path = require('path')
const projectPath = process.cwd()
const normalizedPath = path.basename(projectPath)

const generalDefaults = projectName => ({
  resourceName: `${normalizedPath}_ projectName`,
  authSelections: 'identityPoolAndUserPool',
  ...roles,
});
```

**Comment by kaustavghosh06** [comment]
@dabit3 You don't need the normalizedPath since projectName is already derived from your projectPath (or customizable during the amplify init step).

**Comment by dabit3** [comment]
So just:

```
const generalDefaults = projectName => ({
  resourceName: `${projectName}_{sharedId}`,
  authSelections: 'identityPoolAndUserPool',
  ...roles,
});
```

**Comment by kaustavghosh06** [comment]
Correct!

**Comment by dd-ssc** [comment]
I've applied that patch locally and can confirm Cognito pools now contain the project name.
I can't say how much this helps me. Thank you very much! 👍

**Comment by dabit3** [comment]
cc @kaustavghosh06

**Comment by dd-ssc** [comment]
However, upon continuing with the setup work, I encounter this error:

```
$ amplify push

Current Environment: develop

| Category | Resource name       | Operation | Provider plugin   |
| -------- | ------------------- | --------- | ----------------- |
| Auth     | <project>_<some ID> | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠧ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

Template format error: Resource name auth<project>_<some ID> is non alphanumeric.
```

**Comment by yuth** [comment]
@aws-amplify/cli@1.6.10 includes the fix
