### ISSUE TITLE
Analyzer for field in ElasticSearch

### ISSUE THREAD

**Issue by cinash** [aws-amplify/amplify-cli#3890]
** Which Category is your question related to? **
`@searchable` annotation
** What AWS Services are you utilizing? **
AWS Elasticsearch
** Provide additional details e.g. code snippets **
How can I specify the analyzer on a field in elasticsearch? The question is more general, but what I have is a field that is a list of elements separated by comma, and would like to index them using pattern analyzer so that when I search for multiple values in the field it sorts me correctly by relevance.

**Comment by SwaySway** [comment]
Hello @cinash currently the `@searchable` directive does not expose a way to analyze fields as it currently only creates a search query. An example how you could potentially achieve this is by adding `@function` on the field which can be evaluated and analyze the said list of strings against the cluster you have deployed through `@searchable`.
As an example of a potential implementation you could add `@function` to the field.
Example below
```graphql
type Post
  @model
  @searchable
  {
    id: String
    title: String
    description: String
    tags: [String] @function(name: "MyLambdaFunction")
  }
```

**Comment by nikhname** [comment]
If you have further questions please feel free to comment below

**Comment by raelmiu** [comment]
@SwaySway Two questions, first: does that actually work? And secondly, how does it work? Does it post additional information to ES? Is it called by the Dynamo-stream-to-ES lambda?

**Comment by evrardts** [comment]
+1 Would be nice to have an example of the function, thanks a lot!
