### ISSUE TITLE
Help with using Admin Queries

### ISSUE THREAD

**Issue by arhoy** [aws-amplify/amplify-cli#3896]
I am trying to follow along with the following article [here](https://aws.amazon.com/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/)

Namely the part where they add a user to a group using admin queries.

I am not sure what I am doing wrong as I am not able to make a request to this call. My nextToken is empty and not sure where or how they are getting this value

At the end of the day what I am want to be able to do is during signup process add a user to a specific cognito group and have admin users be able to make changes in the React application

Here is my code.

```

import React from 'react';
import { Section } from '../../../reusableStyles/sections/Sections';
import { Auth, API } from 'aws-amplify';
export const Test = () => {
  let nextToken;
  const getCurrentUser = async () => {
    const user = await Auth.currentAuthenticatedUser();
    console.log(user.signInUserSession.accessToken.payload['cognito:groups']);
  };

  const listEditor = async () => {
    let apiName = 'AdminQueries';
    let path = '/listUsersInGroup';
    let myInit = {
      queryStringParameters: {
        groupname: 'developers',
        token: nextToken,
      },
      headers: {
        'Content-Type': 'application/json',
        Authorization: `${(await Auth.currentSession())
          .getAccessToken()
          .getJwtToken()}`,
      },
    };
    console.log(path);
    const { NextToken, ...rest } = await API.get(apiName, path, myInit);
    try {
      nextToken = NextToken;
      console.log('next token is', nextToken);
      return rest;
    } catch (error) {
      console.error('There as an Error', error);
    }
  };
  getCurrentUser();
  listEditor();

  return <Section>Testing </Section>;
};


```

**Comment by SwaySway** [comment]
Hello @arhoy 
Are you getting a specific error when you try to run this?

**Comment by nikhname** [comment]
If you're experiencing errors here please comment and we'll reopen the issue.
