### ISSUE TITLE
Multiple Frontends

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3900]
**Which Category is your question related to?**
Amplify Multiple Frontends

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
Amplify Multiple Frontends

**Provide additional details e.g. code snippets**
I have a project already built with Angular8 + Amplify.
Now I want to use the same backend with my React fronend app.
I saw the docs and it told me to run amplify pull and say No if the backend is not required and I did the same and it created the "asw-exports" file for me.

The issue is that now I want to run "amplify codegen" to create my service for React app.
The CLI asked to do a "amplify codegen add" before doing "amplify codegen" and I did the same.
Then it asked me to copy the schema.graphql file and paste it in the root folder and I did that and then ran "amplify codegen" but it gave me errors for all directives that:

Unknown directive "function".
Unknown directive "auth"

Can anyone help me in creating the service file that I can use?

**Comment by swaminator** [comment]
@rehanbabertkxel Please refer to: https://docs.amplify.aws/cli/teams/multi-frontend

**Comment by UnleashedMind** [comment]
@rehanbabertkxel 
If you do not plan to do any development of the backend in your React frontend app, what you've done is correct. 
You need to get the transformed schema in place for the codegen to work, not the original one with the GraphQL transformer directives such as @function and @auth. 
You can get the schema from the AppSync Console. Or you can run `amplify codegen --apiId <api-id>`. Check the [document](https://aws-amplify.github.io/docs/cli-toolchain/graphql#amplify-add-codegen-) for more details.

**Comment by rehanbabertkxel** [comment]
@UnleashedMind , thank you.
I exported the schema.json file from appsync and put it into my project and ran amplify codegen add. It created the .graphqlconfig.yml file and then I ran amplify codegen and it created all the quesries in the ./src/graphql/ folder. Now I can easily use those in my Javascript functions.
Thanks.
