### ISSUE TITLE
amplify codegen does not generate code

### ISSUE THREAD

**Issue by andreialecu** [aws-amplify/amplify-cli#3901]
**Describe the bug**

I'm attempting to generate typescript models for a graphql API and running `amplify codegen models` does not do anything. No new files are generated.

The graphql types have `@model` on them.

**Amplify CLI Version**

```
$ amplify -v
4.18.0
```

**To Reproduce**

```
$ amplify -v
4.18.0

$ amplify codegen models

GraphQL schema compiled successfully.

Edit your schema at S:\Projects\x\amplify\backend\api\x\schema.graphql or place .graphql files in a directory at S:\Projects\x\amplify\backend\api\x\schema
Successfully generated models. Generated models can be found \s\Projects\x\src
```

No new files are generated.

**Expected behavior**

From what I understand, the command should generate models based on the graphql types.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 12.8.0

**Comment by andreialecu** [comment]
Running the same command via Ubuntu using WSL works and generates the proper files. 

I'm not sure why it doesn't work on Windows. Probably some (permission?) error is being ignored somewhere.

```
$ amplify -v
Scanning for plugins...
Plugin scan successful
4.18.0

$ amplify codegen models

GraphQL schema compiled successfully.

Edit your schema at /s/Projects/x/amplify/backend/api/x/schema.graphql or place .graphql files in a directory at /s/Projects/x/amplify/backend/api/x/schema
Successfully generated models. Generated models can be found /s/Projects/x/src

$ ls ./src/models 
index.d.ts  index.js  schema.d.ts  schema.js
```

**Comment by andreialecu** [comment]
Update, `amplify codegen` itself doesn't update anything either via Windows on this machine. Only works via WSL. Not sure why, 

I think ideally there should be some sort of error shown.

**Comment by andreialecu** [comment]
Figured out what is happening

`amplify push`

results in this error: 

```
× There was an error pulling the backend environment dev.
An error occured during the push operation: ENOENT: no such file or directory, open '\s\Projects\x\amplify\team-provider-info.json'
```

The file exists, but the way it's looking for it is wrong.

The problem seems to be in `amplify/.config/local-env-info.json`, the `projectPath` is set to `"/s/Projects/x"` which is wrong under Windows, but valid under WSL.

Looks like there could be some better handling of paths in this case, and throwing errors from `amplify codegen` as well.

I think ideally the `projectPath` shouldn't be hardcoded in that file. Would make portability between Windows and WSL easier in this case.

**Comment by andreialecu** [comment]
Got hit by this bug again in a different scenario here: https://github.com/aws-amplify/amplify-cli/issues/3980#issuecomment-614770114

**Comment by sw-yx** [comment]
sympathies.

**Comment by yesidherreraIT** [comment]
any update?

**Comment by kaustavghosh06** [comment]
@andreialecu I believe the issue out here was that you were sharing the same amplify project (in the same filesystem) in Windows OS and then WSL. Would recommend having two separate folders (clones) for Windows OS and WSL as we require the project-paths for various computations. You can keep the clones in sync using `amplify pull`
