### ISSUE TITLE
Best way to recreate Tables if you do @key updates

### ISSUE THREAD

**Issue by regenrek** [aws-amplify/amplify-cli#3903]
Hi,

I want to relate to this issue/comment: https://github.com/aws-amplify/amplify-cli/issues/3816#issuecomment-609934335

While developing and testing with amplify the graphql schema evolves and gets changed most of the time. Whats the best and fastest way to recreate tables without thinking about data loss

1. How can I recreate mock tables with new schema?
2. How can I recreate tables with new schema in dynamodb?

Example error message:
```
Failed to start API Mock endpoint Attempting to add a local secondary index to the BusinessTable table in the Business stack. Local secondary indexes must be created when the table is created.
Cause: Adding a @key directive where the first field in 'fields' is the same as the first field in the 'fields' of the primary @key.
How to fix: Change the first field in 'fields' such that a global secondary index is created or delete and recreate the model.
```

Regards

**Comment by undefobj** [comment]
@regenrek We are also discussing this in: https://github.com/aws-amplify/amplify-cli/issues/2384

Do you have any thoughts on how the workflow would be best for you here? One thought is a "production/locked" and "dev/unlocked" mode for safety purposes, where in the dev mode the tables are automatically recreated on certain foundational schema changes.

**Comment by regenrek** [comment]
The workflow for this is now the following:

- Clean schema and add 1 Test @model
- Remove Custom Resolvers
- push 
- Put schema back 
- push
- Hope everythings goes well

Thank I will close this in favour of #2384
