### ISSUE TITLE
Generated template file contains a ton of trailing whitespace

### ISSUE THREAD

**Issue by miketheman** [aws-amplify/amplify-cli#391]
**Describe the bug**
When following the tutorial to generate a template for auth, the resulting template yml file contains tons of trailing whitespace which makes adding to source control appear like a problem, as a `git status` will show red when there's trailing whitespace.

**To Reproduce**
Seen specifically with https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs - the resulting local file named `amplify/backend/auth/cognito12345678/cognito12345678-cloudformation-template.yml`.

**Expected behavior**
I would expect any generated files from templates to adhere to good file practices (trailing whitespace, new lines at the end of files, etc) so as to minimize the conflict between developers with different settings.
If there is an actual reason for this, consider recommending an `.editorconfig` entry to projects that could use it.

**Comment by miketheman** [comment]
@attilah likely a good practice. I've used pre-commit.com in other projects before quite successfully.

**Comment by ChristopheBougere** [comment]
+1 on applying prettier or at least respecting best practices like trailing spaces and new lines
My editor fix this on save, which makes a lot of diff when editing something in the generated files while I would like to keep the change as small as possible. Of course, I could disable it, but I think this would be better to do in amplify cli

**Comment by ykethan** [comment]
The behaviour has been updated in the recent CLI release. closing the issue.
