### ISSUE TITLE
Scheduled Lambda Trigger causes amplify push to fail

### ISSUE THREAD

**Issue by AbirAbbas** [aws-amplify/amplify-cli#3911]
**Describe the bug**

UPDATE_FAILED      functionrebateFunction AWS::CloudFormation::Stack Thu Apr 09 2020 00:42:04 GMT-0400 (Eastern Daylight Time) Parameters: [CloudWatchRule] do not exist in the template

**Amplify CLI Version**

4.18.0

**To Reproduce**
Added scheduled lambda trigger to existing function using amplify update function

parameters.json:

{
    "CloudWatchRule": "cron(30 * * * ? *)"
}

**Comment by akshbhu** [comment]
Hi @AbirAbbas 

Can you tell me the steps how you setup the trigger schedule to reproduce it?
Also can you share the CFN file for this lambda function?

**Comment by AbirAbbas** [comment]
`? Please select the Lambda Function you would want to update rebateFunction
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? No
? Do you want to update or remove the function's schedule? Yes
? Select from the following options: Update the schedule
? At which interval should the function be invoked: Custom AWS cron expression
? Custom Schedule expression(Learn more: https://amzn.to/3akXtJF) 30 * * * ? *
? Do you want to edit the local lambda function now? No`

and cloudformation:

`{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Lambda resource stack creation using Amplify CLI",
	"Parameters": {
		"env": {
			"Type": "String"
		},
		"storageOrderName": {
			"Type": "String",
			"Default": "storageOrderName"
		},
		"storageOrderArn": {
			"Type": "String",
			"Default": "storageOrderArn"
		},
		"storageMatrixName": {
			"Type": "String",
			"Default": "storageMatrixName"
		},
		"storageMatrixArn": {
			"Type": "String",
			"Default": "storageMatrixArn"
		},
		"storageMiscName": {
			"Type": "String",
			"Default": "storageMiscName"
		},
		"storageMiscArn": {
			"Type": "String",
			"Default": "storageMiscArn"
		},
		"functionorderFunctionName": {
			"Type": "String",
			"Default": "functionorderFunctionName"
		},
		"functionnotificationFunctionName": {
			"Type": "String",
			"Default": "functionnotificationFunctionName"
		},
		"storageRestaurantName": {
			"Type": "String",
			"Default": "storageRestaurantName"
		},
		"storageRestaurantArn": {
			"Type": "String",
			"Default": "storageRestaurantArn"
		}
	},
	"Conditions": {
		"ShouldNotCreateEnvResources": {
			"Fn::Equals": [
				{
					"Ref": "env"
				},
				"NONE"
			]
		}
	},
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
				"aws:asset:path": "./src",
				"aws:asset:property": "Code"
			},
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"rebateFunction",
						{
							"Fn::Join": [
								"",
								[
									"rebateFunction",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"REGION": {
							"Ref": "AWS::Region"
						},
						"STORAGE_ORDER_NAME": {
							"Ref": "storageOrderName"
						},
						"STORAGE_ORDER_ARN": {
							"Ref": "storageOrderArn"
						},
						"STORAGE_MATRIX_NAME": {
							"Ref": "storageMatrixName"
						},
						"STORAGE_MATRIX_ARN": {
							"Ref": "storageMatrixArn"
						},
						"STORAGE_MISC_NAME": {
							"Ref": "storageMiscName"
						},
						"STORAGE_MISC_ARN": {
							"Ref": "storageMiscArn"
						},
						"FUNCTION_ORDERFUNCTION_NAME": {
							"Ref": "functionorderFunctionName"
						},
						"FUNCTION_NOTIFICATIONFUNCTION_NAME": {
							"Ref": "functionnotificationFunctionName"
						},
						"STORAGE_RESTAURANT_NAME": {
							"Ref": "storageRestaurantName"
						},
						"STORAGE_RESTAURANT_ARN": {
							"Ref": "storageRestaurantArn"
						}
					}
				},
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs10.x",
				"Timeout": "25",
				"Code": {
					"S3Bucket": "deliveryapplication-abir-20190921230401-deployment",
					"S3Key": "amplify-builds/rebateFunction-595a44344b367631646f-build.zip"
				}
			}
		},
		"LambdaExecutionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"deliveryapplicationLambdaRole2bc62c9a",
						{
							"Fn::Join": [
								"",
								[
									"deliveryapplicationLambdaRole2bc62c9a",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Principal": {
								"Service": [
									"lambda.amazonaws.com"
								]
							},
							"Action": [
								"sts:AssumeRole"
							]
						}
					]
				}
			}
		},
		"lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						}
					]
				}
			}
		},
		"AmplifyResourcesPolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "amplify-lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageOrderArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageOrderArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query"
							],
							"Resource": [
								{
									"Ref": "storageRestaurantArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageRestaurantArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageMatrixArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageMatrixArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageMiscArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageMiscArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:Get*",
								"lambda:List*",
								"lambda:Invoke*"
							],
							"Resource": [
								{
									"Fn::Join": [
										"",
										[
											"arn:aws:lambda:",
											{
												"Ref": "AWS::Region"
											},
											":",
											{
												"Ref": "AWS::AccountId"
											},
											":function:",
											{
												"Ref": "functionorderFunctionName"
											}
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:Create*",
								"lambda:Put*",
								"lambda:Add*",
								"lambda:Get*",
								"lambda:List*",
								"lambda:Invoke*",
								"lambda:Update*"
							],
							"Resource": [
								{
									"Fn::Join": [
										"",
										[
											"arn:aws:lambda:",
											{
												"Ref": "AWS::Region"
											},
											":",
											{
												"Ref": "AWS::AccountId"
											},
											":function:",
											{
												"Ref": "functionnotificationFunctionName"
											}
										]
									]
								}
							]
						}
					]
				}
			}
		},
		"CloudWatchEvent": {
			"Type": "AWS::Events::Rule",
			"Properties": {
				"Description": "Schedule rule for Lambda",
				"ScheduleExpression": {
					"Ref": "CloudWatchRule"
				},
				"State": "ENABLED",
				"Targets": [
					{
						"Arn": {
							"Fn::GetAtt": [
								"LambdaFunction",
								"Arn"
							]
						},
						"Id": {
							"Ref": "LambdaFunction"
						}
					}
				]
			}
		},
		"PermissionForEventsToInvokeLambda": {
			"Type": "AWS::Lambda::Permission",
			"Properties": {
				"FunctionName": {
					"Ref": "LambdaFunction"
				},
				"Action": "lambda:InvokeFunction",
				"Principal": "events.amazonaws.com",
				"SourceArn": {
					"Fn::GetAtt": [
						"CloudWatchEvent",
						"Arn"
					]
				}
			}
		}
	},
	"Outputs": {
		"Name": {
			"Value": {
				"Ref": "LambdaFunction"
			}
		},
		"Arn": {
			"Value": {
				"Fn::GetAtt": [
					"LambdaFunction",
					"Arn"
				]
			}
		},
		"Region": {
			"Value": {
				"Ref": "AWS::Region"
			}
		},
		"LambdaExecutionRole": {
			"Value": {
				"Ref": "LambdaExecutionRole"
			}
		},
		"CloudWatchEventRule": {
			"Value": {
				"Ref": "CloudWatchEvent"
			}
		}
	}
}`

**Comment by AbirAbbas** [comment]
`? Please select the Lambda Function you would want to update rebateFunction
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? No
? Do you want to update or remove the function's schedule? Yes
? Select from the following options: Update the schedule
? At which interval should the function be invoked: Custom AWS cron expression
? Custom Schedule expression(Learn more: https://amzn.to/3akXtJF) 30 * * * ? *
? Do you want to edit the local lambda function now? No`

**Comment by AbirAbbas** [comment]
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Lambda resource stack creation using Amplify CLI",
	"Parameters": {
		"env": {
			"Type": "String"
		},
		"storageOrderName": {
			"Type": "String",
			"Default": "storageOrderName"
		},
		"storageOrderArn": {
			"Type": "String",
			"Default": "storageOrderArn"
		},
		"storageMatrixName": {
			"Type": "String",
			"Default": "storageMatrixName"
		},
		"storageMatrixArn": {
			"Type": "String",
			"Default": "storageMatrixArn"
		},
		"storageMiscName": {
			"Type": "String",
			"Default": "storageMiscName"
		},
		"storageMiscArn": {
			"Type": "String",
			"Default": "storageMiscArn"
		},
		"functionorderFunctionName": {
			"Type": "String",
			"Default": "functionorderFunctionName"
		},
		"functionnotificationFunctionName": {
			"Type": "String",
			"Default": "functionnotificationFunctionName"
		},
		"storageRestaurantName": {
			"Type": "String",
			"Default": "storageRestaurantName"
		},
		"storageRestaurantArn": {
			"Type": "String",
			"Default": "storageRestaurantArn"
		}
	},
	"Conditions": {
		"ShouldNotCreateEnvResources": {
			"Fn::Equals": [
				{
					"Ref": "env"
				},
				"NONE"
			]
		}
	},
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
				"aws:asset:path": "./src",
				"aws:asset:property": "Code"
			},
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"rebateFunction",
						{
							"Fn::Join": [
								"",
								[
									"rebateFunction",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"REGION": {
							"Ref": "AWS::Region"
						},
						"STORAGE_ORDER_NAME": {
							"Ref": "storageOrderName"
						},
						"STORAGE_ORDER_ARN": {
							"Ref": "storageOrderArn"
						},
						"STORAGE_MATRIX_NAME": {
							"Ref": "storageMatrixName"
						},
						"STORAGE_MATRIX_ARN": {
							"Ref": "storageMatrixArn"
						},
						"STORAGE_MISC_NAME": {
							"Ref": "storageMiscName"
						},
						"STORAGE_MISC_ARN": {
							"Ref": "storageMiscArn"
						},
						"FUNCTION_ORDERFUNCTION_NAME": {
							"Ref": "functionorderFunctionName"
						},
						"FUNCTION_NOTIFICATIONFUNCTION_NAME": {
							"Ref": "functionnotificationFunctionName"
						},
						"STORAGE_RESTAURANT_NAME": {
							"Ref": "storageRestaurantName"
						},
						"STORAGE_RESTAURANT_ARN": {
							"Ref": "storageRestaurantArn"
						}
					}
				},
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs10.x",
				"Timeout": "25",
				"Code": {
					"S3Bucket": "deliveryapplication-abir-20190921230401-deployment",
					"S3Key": "amplify-builds/rebateFunction-595a44344b367631646f-build.zip"
				}
			}
		},
		"LambdaExecutionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"deliveryapplicationLambdaRole2bc62c9a",
						{
							"Fn::Join": [
								"",
								[
									"deliveryapplicationLambdaRole2bc62c9a",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Principal": {
								"Service": [
									"lambda.amazonaws.com"
								]
							},
							"Action": [
								"sts:AssumeRole"
							]
						}
					]
				}
			}
		},
		"lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						}
					]
				}
			}
		},
		"AmplifyResourcesPolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "amplify-lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageOrderArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageOrderArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query"
							],
							"Resource": [
								{
									"Ref": "storageRestaurantArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageRestaurantArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageMatrixArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageMatrixArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:Put*",
								"dynamodb:Create*",
								"dynamodb:BatchWriteItem",
								"dynamodb:Get*",
								"dynamodb:BatchGetItem",
								"dynamodb:List*",
								"dynamodb:Describe*",
								"dynamodb:Scan",
								"dynamodb:Query",
								"dynamodb:Update*",
								"dynamodb:RestoreTable*"
							],
							"Resource": [
								{
									"Ref": "storageMiscArn"
								},
								{
									"Fn::Join": [
										"/",
										[
											{
												"Ref": "storageMiscArn"
											},
											"index/*"
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:Get*",
								"lambda:List*",
								"lambda:Invoke*"
							],
							"Resource": [
								{
									"Fn::Join": [
										"",
										[
											"arn:aws:lambda:",
											{
												"Ref": "AWS::Region"
											},
											":",
											{
												"Ref": "AWS::AccountId"
											},
											":function:",
											{
												"Ref": "functionorderFunctionName"
											}
										]
									]
								}
							]
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:Create*",
								"lambda:Put*",
								"lambda:Add*",
								"lambda:Get*",
								"lambda:List*",
								"lambda:Invoke*",
								"lambda:Update*"
							],
							"Resource": [
								{
									"Fn::Join": [
										"",
										[
											"arn:aws:lambda:",
											{
												"Ref": "AWS::Region"
											},
											":",
											{
												"Ref": "AWS::AccountId"
											},
											":function:",
											{
												"Ref": "functionnotificationFunctionName"
											}
										]
									]
								}
							]
						}
					]
				}
			}
		},
		"CloudWatchEvent": {
			"Type": "AWS::Events::Rule",
			"Properties": {
				"Description": "Schedule rule for Lambda",
				"ScheduleExpression": {
					"Ref": "CloudWatchRule"
				},
				"State": "ENABLED",
				"Targets": [
					{
						"Arn": {
							"Fn::GetAtt": [
								"LambdaFunction",
								"Arn"
							]
						},
						"Id": {
							"Ref": "LambdaFunction"
						}
					}
				]
			}
		},
		"PermissionForEventsToInvokeLambda": {
			"Type": "AWS::Lambda::Permission",
			"Properties": {
				"FunctionName": {
					"Ref": "LambdaFunction"
				},
				"Action": "lambda:InvokeFunction",
				"Principal": "events.amazonaws.com",
				"SourceArn": {
					"Fn::GetAtt": [
						"CloudWatchEvent",
						"Arn"
					]
				}
			}
		}
	},
	"Outputs": {
		"Name": {
			"Value": {
				"Ref": "LambdaFunction"
			}
		},
		"Arn": {
			"Value": {
				"Fn::GetAtt": [
					"LambdaFunction",
					"Arn"
				]
			}
		},
		"Region": {
			"Value": {
				"Ref": "AWS::Region"
			}
		},
		"LambdaExecutionRole": {
			"Value": {
				"Ref": "LambdaExecutionRole"
			}
		},
		"CloudWatchEventRule": {
			"Value": {
				"Ref": "CloudWatchEvent"
			}
		}
	}
}

**Comment by AbirAbbas** [comment]
nevermind issue is caused by updating my CLI not specifically the lambda trigger.

**Comment by AbirAbbas** [comment]
scratch that the issue persists. I checked without the lambda trigger and everything works fine, when the lambda trigger is added it breaks.

**Comment by amuresia** [comment]
+1 same over here. `CloudWatchRule` is referenced in the template, but it's not created as a resource.

**Comment by akshbhu** [comment]
Hi @amuresia 

Can you add these into your CFN file under Parameters section and check if its working as workaround.
```
		"CloudWatchRule": {
			"Type": "String",
			"Default": "NONE",
			"Description": " Schedule Expression"
		},
```
By the time I will fix this issue. Thanks for reporting this.

**Comment by amuresia** [comment]
The above does not fix the issue I'm afraid.
The CF template reads as:
```
		"CloudWatchEvent": {
			"Type": "AWS::Events::Rule",
			"Properties": {
				"Description": "Schedule rule for Lambda",
				"ScheduleExpression": {
					"Ref": "CloudWatchRule"
				},
				"State": "ENABLED",
				"Targets": [
					{
						"Arn": {
							"Fn::GetAtt": [
								"LambdaFunction",
								"Arn"
							]
						},
						"Id": {
							"Ref": "LambdaFunction"
						}
					}
				]
			}
		},
		"CloudWatchRule": {
			"Type": "String",
			"Default": "NONE",
			"Description": " Schedule Expression"
		},
```

**Comment by kaustavghosh06** [comment]
@amuresia You need to add it to the "Parameters" block.

**Comment by akshbhu** [comment]
Hi @amuresia 
Yes , you need to add that block under parameters section. I am adding a template for your reference
```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Lambda resource stack creation using Amplify CLI",
	"Parameters": {
		"CloudWatchRule": {
			"Type": "String",
			"Default": "NONE",
			"Description": " Schedule Expression"
		},
		"env": {
			"Type": "String"
		}
	},
	"Conditions": {
		"ShouldNotCreateEnvResources": {
			"Fn::Equals": [
				{
					"Ref": "env"
				},
				"NONE"
			]
		}
	},
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
				"aws:asset:path": "./src",
				"aws:asset:property": "Code"
			},
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"cronissued0325385",
						{
							"Fn::Join": [
								"",
								[
									"cronissued0325385",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"REGION": {
							"Ref": "AWS::Region"
						}
					}
				},
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs12.x",
				"Timeout": "25",
				"Code": {
					"S3Bucket": "amplify-cronissue-dev-224210-deployment",
					"S3Key": "amplify-builds/cronissued0325385-317234474d5553526641-build.zip"
				}
			}
		},
		"LambdaExecutionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"cronissueLambdaRole7efeb4e4",
						{
							"Fn::Join": [
								"",
								[
									"cronissueLambdaRole7efeb4e4",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Principal": {
								"Service": [
									"lambda.amazonaws.com"
								]
							},
							"Action": [
								"sts:AssumeRole"
							]
						}
					]
				}
			}
		},
		"lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						}
					]
				}
			}
		},
		"CloudWatchEvent": {
			"Type": "AWS::Events::Rule",
			"Properties": {
				"Description": "Schedule rule for Lambda",
				"ScheduleExpression": {
					"Ref": "CloudWatchRule"
				},
				"State": "ENABLED",
				"Targets": [
					{
						"Arn": {
							"Fn::GetAtt": [
								"LambdaFunction",
								"Arn"
							]
						},
						"Id": {
							"Ref": "LambdaFunction"
						}
					}
				]
			}
		},
		"PermissionForEventsToInvokeLambda": {
			"Type": "AWS::Lambda::Permission",
			"Properties": {
				"FunctionName": {
					"Ref": "LambdaFunction"
				},
				"Action": "lambda:InvokeFunction",
				"Principal": "events.amazonaws.com",
				"SourceArn": {
					"Fn::GetAtt": [
						"CloudWatchEvent",
						"Arn"
					]
				}
			}
		}
	},
	"Outputs": {
		"Name": {
			"Value": {
				"Ref": "LambdaFunction"
			}
		},
		"Arn": {
			"Value": {
				"Fn::GetAtt": [
					"LambdaFunction",
					"Arn"
				]
			}
		},
		"Region": {
			"Value": {
				"Ref": "AWS::Region"
			}
		},
		"LambdaExecutionRole": {
			"Value": {
				"Ref": "LambdaExecutionRole"
			}
		},
		"CloudWatchEventRule": {
			"Value": {
				"Ref": "CloudWatchEvent"
			}
		}
	}
}
```

**Comment by AbirAbbas** [comment]
adding it to Parameters solved it for me!

**Comment by akshbhu** [comment]
@AbirAbbas 
Thanks for the update. I will write a fix for this so that there wont be any workarounds.

**Comment by amuresia** [comment]
Yup, that worked for me too. Should I keep it in or will it clash when the fix is released?

**Comment by akshbhu** [comment]
Hi @amuresia 
Nice to know that it worked.
You can keep that in CFN file, it wont be affected by the release.
