### ISSUE TITLE
AppSync Inconsistent Identity Username ($ctx.identity.claims.get("username"))

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#3916]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created two Amplify projects. Both projects use cognito auth. When I invoke a lambda function with appsync resolver, the usernames passed to the functions are different. One project has sub and the other has email

Project1
```
        {"identity": {
            "claims": {
                "sub": "073009d9-4ff8-4d13-8393-f058c7f72420",
                "aud": "51tid7p8scum93qrglhl5np25r",
                "email_verified": true,
                "event_id": "603d620f-7bbb-4cb6-9304-e674c578bbe4",
                "token_use": "id",
                "auth_time": 1586293126,
                "iss": "********************",
                "phone_number_verified": false,
                "cognito:username": "073009d9-4ff8-4d13-8393-f058c7f72420",
                "exp": 1586457947,
                "iat": 1586454347,
                "email": "name@example.com"
            },
            "defaultAuthStrategy": "ALLOW",
            "groups": null,
            "issuer": "*********************",
            "sourceIp": [
                "***.**.**.**"
            ],
            "sub": "073009d9-4ff8-4d13-8393-f058c7f72420",
            "username": "073009d9-4ff8-4d13-8393-f058c7f72420"
        }
}
```
The username is sub id in project 1

Project2
```
identity:
   { claims:
      { sub: 'fd23c5b8-92ce-43bb-a28a-051e7b242c91',
        aud: '7oln0r5fndneov2tsg5r0us3sa',
        email_verified: true,
        event_id: 'b73f0c23-c87a-4eda-a764-c64aaceb8b53',
        token_use: 'id',
        auth_time: 1586453392,
        iss:
         '***********************',
        phone_number_verified: false,
        'cognito:username': 'name@example.com',
        exp: 1586456992,
        iat: 1586453392,
        email: 'name@example.com' },
     defaultAuthStrategy: 'ALLOW',
     groups: null,
     issuer:
      '****************',
     sourceIp: [ '***.**.**.**' ],
     sub: 'fd23c5b8-92ce-43bb-a28a-051e7b242c91',
     username: 'name@example.com' },
```
The username is email in project 2

**Amplify CLI Version**
4.12.0
**To Reproduce**
not sure how to reproduce

**Expected behavior**
consistent username value. It should be either email or sub id all the time

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 10

**Additional context**

**Comment by SwaySway** [comment]
Hello @gaochenyue
How did you setup auth on both projects?

**Comment by gaochenyue** [comment]
@SwaySway I set auth with default options. Which username is expected, sub or email?
Thanks

**Comment by SwaySway** [comment]
@gaochenyue Did you setup both projects with same selection? As in both had email selected?
