### ISSUE TITLE
REST api id with amplify status

### ISSUE THREAD

**Issue by smakinson** [aws-amplify/amplify-cli#3919]
Minor potential feature request here. Would it be possible to show the id for a `api` item for the currently checked out env when `amplify status` is run? Or is it trying to stick with cols that work for all categories?

**Comment by SwaySway** [comment]
Hello @smakinson 
Are you referring to a GraphQL API? If so you do the endpoint when running `amplify status`. Should you need more information regarding you can run `amplify console api`, this will open up your AppSync API in the AWS Console. Is there a specific use case you have where you need the API ID?

**Comment by smakinson** [comment]
@SwaySway Sorry about that, I'm thinking of the REST api. Similar to the column shown in the list in the console. It a convenience feature idea since the REST api's have the same name for all environments.
