### ISSUE TITLE
Creating two types with similar names gives an IAM role already exists error.

### ISSUE THREAD

**Issue by varunpsr** [aws-amplify/amplify-cli#3921]
**Describe the bug**
We've got two types defined in our schema namely `UserSubscriptionDeliveryTimings` and `UserSubscriptionDeliveryDays`. When we created the first type, it created an IAM role `UserSubscriptionDeliv-role-docnrn3g2bfyllul3wm6kshbpi-develop` and that worked, when we created the second type, it tried to create an IAM role with the same name for some reason.
Running `amplify mock` worked for us but `amplify push` fails.
I know the type names could have been shorter but we already types with the names `DeliveryTimings` and `DeliveryDays`.

**Amplify CLI Version**
4.16.1

**To Reproduce**
1. Create the types in your schema.graphql
2. Verify that the code works with `amplify mock api`
3. Run `amplify push` to push changes online.

**Expected behavior**
`amplify push` should have run seamlessly and created the necessary tables, queries and mutations.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.14.0

**Additional context**
We have a lot of types defined in our project, > 20

**Comment by varunpsr** [comment]
Removing the `UserSubscriptionDeliveryDays` from schema.graphql should have successfully run `amplify push` but now, not able to Push anything to Amplify. 😐

**Comment by akshbhu** [comment]
Hi @varunpsr 

 For the workaround you can name the types with length <=21 chars.
By the time I will fix this issue. Thanks for reporting this.

**Comment by varunpsr** [comment]
Glad I could be of help.
