### ISSUE TITLE
The directive "auth" can only be used once at this location.

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#3924]
Hi, I can't do Amplify any more.

For every amplify push I have this error message :
The directive "auth" can only be used once at this location.

**Comment by mdoesburg** [comment]
@rudyhadoux Can you post your graphql schema here please, so we can help you?

**Comment by rudyhadoux** [comment]
type Particulier
  @model(subscriptions: { level: public })
  @auth(
    rules: [
      {
        allow: groups
        groups: ["utilisateurs"]
        operations: [create, update, read, delete]
      }
      {
        allow: groups
        groups: ["professionnels"]
        operations: [create, update, read, delete]
      }
    ]
  ) {
  id: ID!
  email: String!
  telephone: String
  nom: String!
  prenom: String!
}

**Comment by rudyhadoux** [comment]
I think error messages are too incomplete.

**Comment by mdoesburg** [comment]
I am not sure if this will work, because I can't test it right now, but can you try adding commas in between the 2 rules and after the allow and groups line. Like this:

```graphql
type Particulier
  @model(subscriptions: { level: public })
  @auth(rules: [
    {
      allow: groups,
      groups: ["utilisateurs"],
      operations: [create, update, read, delete]
    },
    {
      allow: groups,
      groups: ["professionnels"],
      operations: [create, update, read, delete]
    }
  ]) 
{
  id: ID!
  email: String!
  telephone: String
  nom: String!
  prenom: String!
}
```

**Comment by rudyhadoux** [comment]
There was a bigger schema that worked well.
I was surprised because it is the first time I have this error message.
