### ISSUE TITLE
CustomMessage failed with error index.handler is undefined or not exported --> Cognito Lambda Triggers

### ISSUE THREAD

**Issue by Jay2113** [aws-amplify/amplify-cli#3926]
**Describe the bug**
The Amplify CLI provides Lambda trigger templates, I am trying to implement the Email Verification Link with Redirect template. While trying to complete the CLI Auth workflow I encounter some access denied blocks from CloudFormation. Also, when I try to register a new user, the Lambda should be triggered but I get the following error: "CustomMessage failed with error index.handler is undefined or not exported."

**Amplify CLI Version**
4.18.0

**To Reproduce**
Create a basic React App. Initialize a new Amplify project and add the Auth workflow. My configuration is as follows:

![Screen Shot 2020-04-07 at 4 47 16 PM](https://user-images.githubusercontent.com/38470430/79013164-13de2f00-7b36-11ea-9d0b-08f25f65d03f.png)

**Expected behavior**
This trigger template allows us to define an email message with a link to a static S3 bucket that we control, where the user’s account will be confirmed and they can then be redirected to a URL of your choice (presumably our application). The URL will automatically contain the username as a query string parameters.

**Screenshots**

Error:
![Screen Shot 2020-04-07 at 4 46 43 PM](https://user-images.githubusercontent.com/38470430/79013426-b39bbd00-7b36-11ea-96e6-7b3e34eb875e.png)

CF Access Denied Blocks:
![Screen Shot 2020-04-07 at 4 48 30 PM](https://user-images.githubusercontent.com/38470430/79013481-d928c680-7b36-11ea-94b2-395ae8e73be9.png)

![Screen Shot 2020-04-07 at 4 48 21 PM](https://user-images.githubusercontent.com/38470430/79013486-dcbc4d80-7b36-11ea-9a53-31da9478bd27.png)
 
![Screen Shot 2020-04-07 at 4 48 06 PM](https://user-images.githubusercontent.com/38470430/79013499-e3e35b80-7b36-11ea-81cd-20a6e5dc7d90.png)

![Screen Shot 2020-04-07 at 4 47 51 PM](https://user-images.githubusercontent.com/38470430/79013511-e940a600-7b36-11ea-95df-b4372ddff58f.png)

**Desktop:**
 - OS: Mac
 - Node Version: 13.11.0

**Comment by SwaySway** [comment]
Hello @Jay2113 
We are currently investigating this issue.
If you move the index.js file inside `src/` of the function and push does that work for you?

**Comment by Jay2113** [comment]
Hi @SwaySway 
Yes, I moved index.js inside the src/ folder. The Lambda function triggers now. However, when I try to visit the confirmation link that I receive in my email it gives me a 403 Forbidden error.

**Comment by Aabhusan** [comment]
i  am facing the same issue, @Jay2113  did you solved the issue?
