### ISSUE TITLE
Cognito federated login across separate apps sharing same backend

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#3933]
**Which Category is your question related to?**
Auth

**What AWS Services are you utilizing?**
API Gateway, Cognito, DynamoDb, Lambda, S3

**Amplify CLI Version** 
4.18.0

**Scenario:**  

React (web) project created with amplify-cli

Second React Native project (expo), using first project’s backend via amplify pull

A Cognito user pool is used for Auth, and I’ve setup FederatedSignIn.

Both apps can sign in using username/password via Cognito.

The problem is that the callback/signout URLs in the app client are different between web and React Native, so only one app can use `federatedSignIn`, while the other gets a redirect_uri mismatch.

I can fudge this by manually editing the user pool app client to have URLs for both web and React Native and manually updating the aws-exports.js file in each app respectively with the correct URLs for the platform.

Alternatively, I could create separate app clients in the user pool, so that I can use different callback/signout URLs, though I'm unsure (yet, because I haven't tried it) how to tell one app to use one client and the other to use another.

Either way, it seems that I'll need to be modifying the `aws-exports.js` file, which gets overwritten on each `amplify push`, so that's no fun at all.

Any thoughts on best practice here?

Thanks! 🌮

**Comment by ashika01** [comment]
@kimfucious I guess manual setup would work for this right? Have you tried configuring using [Amplify.configure()](https://aws-amplify.github.io/docs/js/authentication#manual-setup)

**Comment by kimfucious** [comment]
@ashika01 thanks for that.  I think you're spot on with your recommendation.

My insane laziness has caused me to gloss over that section of the docs for long enough! 😉 

I shall attempt that and report back here with my findings.

**Comment by kimfucious** [comment]
Okay, I looked at this, and I'm still a bit confused.

Looking at the docs [here](https://aws-amplify.github.io/docs/js/authentication#manual-setup), my problems are:

1.  All the properties in `aws-exports.js` are snake case, and those in the example docs are camel case.  No biggie if the property names matched up, but they don't really.  For example, there is `aws_project_region` and `region`.

2.  The `aws-exports.js` file has more entries than the example for manual configuration as shown in the aforementioned docs.  I assume that this is because the docs section that I'm looking at is specifically for Auth, so it doesn't include things like API, DynamoDB, and S3.  But I could be assuming wrong.

3.  In the docs mentioned above, everything auth related looks to be in an Auth object, so I'm not sure where how to add non-auth things into `Authentify.configure({...})`.  

For example, should I handle `aws_dynamodb_all_tables_region` like this?

```js
Amplify.configure({
  Auth: {...},
  Storage: {
    dynamoDbAllTablesRegion: "us-west-2"
  }
})
```
I think you can see I'm basically guessing here...

I have looked into the `amplify` directory, and I do see some potential matches in various files, but this seems like an effort of very uncertain guesswork.
 
So, that said, I'm not sure how to go about creating a manual config file based on the existing `aws-exports.js` file below without some sort of documentation that details the mapping of all potential `aws-exports.js` properties to a manual configuration.  I have Googled the quite a bit, but I cannot find such a beast.

```js
const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-1234567890-1234-1234-5678-123456789098",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_aBcDeFgHi",
  aws_user_pools_web_client_id: "1234567890abcdefghij12345",
  oauth: {
    domain: "mydomain-auth-dev.auth.us-west-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://localhost:3000/apple-callback",
    redirectSignOut: "https://localhost:3000",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_dynamodb_all_tables_region: "us-west-2",
  aws_dynamodb_table_schemas: [
    {
      tableName: "myDynamoTable-dev",
      region: "us-west-2",
    },
    {
      tableName: "myDynamoTable-dev",
      region: "us-west-2",
    },
    {
      tableName: "myOtherDynamoTable-dev",
      region: "us-west-2",
    },
  ],
  aws_user_files_s3_bucket: "myBucket-s3-storage12345-dev",
  aws_user_files_s3_bucket_region: "us-west-2",
  aws_cloud_logic_custom: [
    {
      name: "myAPI",
      endpoint: "https://1234567abc.execute-api.us-west-2.amazonaws.com/dev",
      region: "us-west-2",
    },
  ],
};

export default awsmobile;
```

**Comment by kimfucious** [comment]
Hang on... I just found this at the bottom of the Amplify Getting Started

![image](https://user-images.githubusercontent.com/26792769/79714936-7389c680-82fc-11ea-9b64-2635268475da.png)

Let's see how far I get...

**Comment by kimfucious** [comment]
Ya know... I think that I've been really dumb about this.

About halfway through mapping the configuration parameters, I had an epiphany.

I mean, I already have `API.configure(awsconfig)` in my project to configure Amplify, where `awsconfig` is the imported `aws-exports.js` file.

So, why not copy the `aws-exports.js` file to something like `aws-config.js`, customize there, and import that instead?  

And if the back-end changes, I can check the `aws-exports.js` after a `amplify pull` and make the necessary changes to the `aws-config.js` file.

This works.  I got no idea why, I'd want or need to go through the mapping exercise I somehow thought I needed to do.

**Comment by kaustavghosh06** [comment]
@kimfucious Apologize for the late response on this. The Amplify CLI creates the aws-exports.js for you which you can then use with your Amplify JS lib. If you intend to do this manually, you can construct an object in memory or have a file of your own as you mentioned above - which you can then can export and use as a part of your `Amplify.configure()` function.

**Comment by kaustavghosh06** [comment]
Also, for the callback/signout URLs for different frontends I've seen customers be smart of splitting the redirectSignIn and redirectSignOut string and filter out the required URL's dynamically on the URL and then re-configure the Amplify client using the `Amplify.configure(<modified-object>)` call. 
Having said that, this is still a workaround and the CLI + libraries can  do a better job  of handling and filtering out the correct URLs when multiple redirectURL's are configured for social-federation . cc @sammartinez @renebrandel

**Comment by kimfucious** [comment]
Thanks for the feedback @kaustavghosh06 

What I've wound up doing, for the project for which I opened this ticket, is the following:

In the webapp (where the backend is maintained), I've gone full manual with the awsconfig.  I'm using environment variables to perform conditional configuration for dev, staging, and prod.

In the native app (React Native using Expo), I've resorted to using npm scripts to publish the app.  There are different files for each environment:

**Expo files**
* app.dev.json
* app.staging.expo.json
* app.prod.expo.json

**aws-export files**
* aws-config.dev.js
* aws-config.staging.js
* aws-config.prod.js

Each of the above `aws-export` files has respective entries for the callback urls, that align with their Cognito userpool, like:
```js
redirectSignIn: "myCoolApp://",
redirectSignOut: "myCoolApp://",
```
To start the app for developement, there's in `package.json`:
```json
"start": "cp app.dev.json app.json && cp aws-config.dev.js aws-config.js && expo start",
```
To publish the app (via Expo), there's this:
```json
"publishStaging": "cp app.staging.json app.json && cp aws-config.staging.js aws-config.js && expo publish",
"publishProd": "cp app.prod.standalone.json app.json && cp aws-config.prod.standalone.js aws-config.js && expo publish",
```
While probably not the most elegant solution, this is what I'm working with now.  Any suggestions for improvement would be welcome.

Also, one thing that's kind of a pain, is the `src/graphql` directory.  Whever I make changes to the schema (at the webapp), or do someting that updates the queries, mutations, etc., I need to manually copy those files over to the native app.  Any advice on that would be great too!

**Comment by kaustavghosh06** [comment]
@kimfucious This is interesting. So you're not using the Amplify CLI to manage your client-side configurations for you? 
The reason I'm asking is that if you were using the Amplify CLI - it would manage generating the aws-exports.js file and the src/graphql codegen files for you without you having to do it manually as you've described above ^^

**Comment by kimfucious** [comment]
Hi @kaustavghosh06, thanks for the reply.

To clarify, I do use the amplify cli on the web app.  

I had an issue a while back with mismatches related to federated login, as I have multiple URLs in Cognito Apple client settings.  For example in Dev, the callback URL(s) has two entries: one for the react native app (expo) and one for the web app:
```console
exp://192.168.1.116:19000/--/, https://localhost:3000/auth-callback/
```
I discovered that, client-side, there must be only one url in the `aws-exports.js` `redirectSignIn` entry to get the federated sign in mismatch resolved, which is why I'm doing the manual thing described above for both the web app and the native app.  Otherwise, after each push the redirects in `aws-exports.js` are changed to whatever is in `amplify/backend/auth/../parameters.json/"oAuthMetaData"` on the web app.

Regardling graphQL, I'm using amplify CLI on the webapp to do the codegen, but the native/expo app isn't initialized with amplify.  I'm not pulling anything, so my configurations are all manual there, including `aws-export` files and the `src/graphql` directory.

I realize that I often don't know what I'm doing and figuring things out along the way, so there is probably a better way to be managing the native app.  

If you could point me to some good docs on how to make this less of a kludge, and easier to maintain, I'd be most appreciative.

**Comment by kaustavghosh06** [comment]
@kimfucious Are you still stuck on this?
