### ISSUE TITLE
Hit upon 200 graphql resource limit upon addition of Aurora data source

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#3934]
**Describe the bug**
I added an Aurora Serverless data source to a brand new GraphQL Api. The data in the db is from an established piece of software with a relational db consisting of 49 tables. There are 1700 or so users in this db and the tables hold various data about them. So it's not that big of a data set. After doing `amplify api add-graphql-datasource` I got error of ` UnhandledPromiseRejectionWarning: InvalidMigrationError: The <redact>.json stack defines more than 200 resources.`

**Amplify CLI Version**
4.18.0

**To Reproduce**
Add an Aurora Serverless data source with a sizeable relational db. 

**Expected behavior**
Should just work. 

**Additional Info**

```
(node:19916) UnhandledPromiseRejectionWarning: InvalidMigrationError: The <redact>-rds.json stack defines more than 200 resources.
at cantHaveMoreThan200Resources (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/sanity-check.ts:263:13)
    at Object.check (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/sanity-check.ts:53:9)
    at Object.buildProject [as buildAPIProject] (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/amplifyUtils.ts:36:7)
    at transformGraphQLSchema (/Users/hisham/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:457:29)
(node:19916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hisham** [comment]
Also looking at the code that throws this exception, it's supposed to give me this message but it doesn't: 

        `The ${stackName} stack defines more than 200 resources.`,
        'CloudFormation templates may contain at most 200 resources.',
        'If the stack is a custom stack, break the stack up into multiple files in stacks/. ' +
          'If the stack was generated, you have hit a limit and can use the StackMapping argument in ' +
          `${TRANSFORM_CONFIG_FILE_NAME} to fine tune how resources are assigned to stacks.`

**Comment by SwaySway** [comment]
@hisham 
Is the stack that is giving you the error a model generated stack?

**Comment by hisham** [comment]
Not sure what you mean by "model generated". Yes it is an auto-generated stack based off of the schema in the relational db. I did not use @model transforms or anything like that. It is a brand new GraphQL API with only the relational db data source added. 

I guess this is an expected limitation, and I'm supposed to use the "StackMapping" attribute somehow. But I think I will just remove some of the resolver resources, as I only need read access to this database and there will remove all mutation and delete resolvers.

**Comment by langfors** [comment]
Also running into this limitation in a medium sized project with 54 tables.  Is Amplify only designed to be used in small projects?

**Comment by kaustavghosh06** [comment]
@hisham CloudFormation and the CLI both has increased the limit to 500 resources now. Are you still running into this limitation with your app?

**Comment by hisham** [comment]
Hey @kaustavghosh06 - I went an alternate route and have no need to connect to this db anymore. So you can go ahead and close this ticket and if I end up doing something similar in future and running into issue I'll open new ticket. If you really want me to test I can but I have no need currently to connect to a large db that might hit the resource limit.
