### ISSUE TITLE
Multiple Frontends (React + IOS)

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3938]
**Which Category is your question related to?**
Multiple Frontends (React + IOS)

**Amplify CLI Version** 
4.13.1

**Provide additional details e.g. code snippets**
I am building an IOS app. But the AWS Amplify developer I have does not have much knowledge of IOS. So what he is suggesting me is that he will build the backend for the app by configuring it with a React application and then I can use the same backend in my IOS app by using "Amplify Multiple Frontends" feature.

The app needs to have a manual and a federated signup feature, so I just want to confirm if the approach we are going to use will work or not as later on after the backend is complete I will write the code for the federated signin seperately in my IOS app and then will call the same graphql by generating it using "amplify codegen" in my IOS app.

What do you suggest? Is this good enough or should I use some other approach?

Thanks in advance.

**Comment by SwaySway** [comment]
Hello @rehanbabertkxel 
Using this method is helpful when sharing the same Amplify backend across multiple frontends, in this case React + iOS.

Docs here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends
