### ISSUE TITLE
Fetch Facebook Data

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#3940]
**Which Category is your question related to?**
Cognito Social Provider Signup

**Amplify CLI Version** 
4.13.1

**What AWS Services are you utilizing?**
AWS Cognito

**Provide additional details e.g. code snippets**
After signup using Federated Signup feature, is there a way by which I can fetch some user information from facebook, i.e; User_Image, User_Name?

What are the ways by which this can be achieved?

**Comment by edwardfoyle** [comment]
Hi @rehanbabertkxel, have you run into an issue with the Amplify CLI or an Amplify frontend library related to this? If you are able to get an access token from Facebook, then retrieving additional information would be a matter of the permissions that the access token grants (specified by the user that has logged in) and reading their documentation on how to retrieve user information.

If you're running into an issue with a resource provisioned with the Amplify CLI or another Amplify library, we'll be happy to help you out!
