### ISSUE TITLE
Datastore says createdAt & updatedAt is undefined

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3943]
**Describe the bug**
My schema is
```
type Post @model {
  id: ID!
  name: String!
  createdAt: String
  updatedAt: String
}
```
As per my schema both `createdAt` and `updatedAt` are `string | undefined`.

But when I save it 

`const results = await DataStore.save( new Post({ name }) )`

then I get following error.

`"Field createdAt should be of type string, undefined received. undefined"`

`"Field updatedAt should be of type string, undefined received. undefined"`

**Amplify CLI Version**
4.18.0

**Expected behavior**
I want to add value created from the server. I don't want to define values.

**Desktop:**
 - OS: Ubuntu 18.04 on Windows WSL 2
 - Node Version. 12.16.2

**Additional context**
if I had to add `createdAt` or `updatedAt` then is the following code acceptable??

`createdAt: (new Date()).toISOString()`

I need them just for sorting purposes only.

**Comment by saevarb** [comment]
I believe this may because you have not enabled DataStore for your API. I had some similar issues. 

Run `amplify update api` and there should be an option to enable DataStore, and then run `amplify push` -- your queries and such should be updated and the values should be created by the backend.

**Comment by apoorvmote** [comment]
@saevarb I have enabled it and it doesn't work. Are you aware that amplify resolvers automatically add `owner`, `createdAt` & `updatedAt` field. But if you define them in your schema then you cannot leave it empty while submitting & hoping that amplify resolvers will fill in the details. This is across API & Datastore.

**Comment by apoorvmote** [comment]
In recent update of `@aws-amplify/datestore` from 2.0.7 to 2.0.8 the issue has fixed itself.
