### ISSUE TITLE
`keyField` Support for DataStore

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3944]
**Describe the bug**
If I create schema as follows
```
type Blog @model {
  id: ID!
  title: String!
  posts: [Post] @connection(name: "BlogPosts", keyField: "blogID")
}
type Post @model {
  id: ID!
  content: String!
  blog: Blog @connection(name: "BlogPosts", keyField: "blogID")
}
```
When I try to save `Post` 

`const original = await DataStore.query(Blog, blogID)`
`const results = await DataStore.save( new Post({ content, blog: original}))`

then I get following error

`"The variables input contains a field name 'postBlogId' that is not defined for input object type 'CreatePostInput' "`

**Amplify CLI Version**
4.18.0

**Expected behavior**
I should be able to use `keyField` with DataStore.

**Desktop:**
 - OS: Ubuntu 18.04 on Windows WSL 2
 - Node Version. 12.16.2

**Comment by SwaySway** [comment]
Related to https://github.com/aws-amplify/amplify-cli/issues/3909

**Comment by undefobj** [comment]
@apoorvmote  Can you take a look at the [latest docs for Relational modeling](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) with DataStore and use the latest library version? We made some improvements to the CLI, the library on how it handles this internally, and tried to be explicit about schemas in the documentation including how to use `@key`.
