### ISSUE TITLE
Adding Python API emits default code that errors with "Malformed Lambda proxy response"

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/amplify-cli#3948]
When doing `amplify add api` and selecting Python, the `index.py` Lambda function that it creates returns the following error when invoked via API gateway:

```
Mon Apr 13 11:04:06 UTC 2020 : Execution failed due to configuration error: Malformed Lambda proxy response
Mon Apr 13 11:04:06 UTC 2020 : Method completed with status: 502
```

This is the code generated:

```python
def handler(event, context):
    print("received event:")
    print(event)
    return {
        "message": "Hello from your new Amplify Python lambda!",
    }
```

The above code would work with the new HTTP API, but not with REST API, as `isBase64Encoded`, `body`, etc. are required in the response.

**Amplify CLI Version**
4.18.0

**To Reproduce**
`amplify add api` and accept the defaults, but select Python.

**Expected behavior**
Return HTTP 200

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3 
 - Node Version: 13.12.0

**Comment by edwardfoyle** [comment]
Hi @mrichman The provided hello world templates are just meant to be a starting point. You can update the contents of the lambda to satisfy your use case. That being said, we are looking at adding more template types in the future

**Comment by mrichman** [comment]
A starting point, if not minimally functional, should at least include a comment as to what to do next. This does neither.
