### ISSUE TITLE
AmplifyDataStore Table Clarification

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3956]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
N/A

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.18.0

**What AWS Services are you utilizing?**
AppSync, Cognito, Lambda, DDB, S3

**Provide additional details e.g. code snippets**
What appears to be randomly, a table called AmplifyDataStore-appId-envName has appeared in each environment. There is no data in any of them. Can you provide some insight into this table? How/when is it created? What is it used for?

**Comment by edwardfoyle** [comment]
Hi @alexkates this table is used for the "Delta Sync" feature of DataStore to manage conflicts. There is some information on it in our docs [here](https://aws-amplify.github.io/docs/js/datastore#how-it-works)
