### ISSUE TITLE
Amplify pull creates duplicate files

### ISSUE THREAD

**Issue by pbishnupuri** [aws-amplify/amplify-cli#3962]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am on amplify 4.18.0 and every time I pull my app amplify pull --appId xxxxxxxxxxx, I get duplicate files. I have already given my terminal full disk access.  
![image](https://user-images.githubusercontent.com/31415137/79290541-fab8e380-7e91-11ea-9bf1-7523ad6f8e4e.png)

**Amplify CLI Version**
4.18.0

**To Reproduce**
Just do amplify pull with my appID

**Expected behavior**
Duplicate files

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. You can use `node -v` to check the node version on your system

**Comment by pbishnupuri** [comment]
Adding question because no one has responded for a while

**Comment by UnleashedMind** [comment]
I can not reproduce the issue. 
It seems to be a write access permission problem, have you tried to run the command with `sudo`?
By the way, ` --appId xxx` is only needed when you first pull a backend environment of a Amplify Console App into a local development machine. You don't need to provide the command line parameter in subsequent pulls of the same backend environment.

**Comment by kaustavghosh06** [comment]
Closing due to lack of response and reproducibility.
