### ISSUE TITLE
Cannot save AWSPhone into Datastore

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3964]
**Describe the bug**
My schema is 
```
type User @model {
  id: ID!
  mobileNumber: AWSPhone!
}
```
When I save phone number 
```
const user = await DataStore.save(new User({
            mobileNumber: '5089180293'
        }))
```
Then I get following error

### "Variable 'mobileNumber' has an invalid value. Unable to parse `5089180293` as a valid phone number."

**Amplify CLI Version**
4.18.0

**Expected behavior**
It should save my number

**Desktop:**
 - OS: Ubuntu 18.04 on windows wsl2
 - Node Version. 12.16.2

**Comment by edwardfoyle** [comment]
Hi @apoorvmote based on the documentation [here](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) it looks like AWSPhone expects the string to be "whitespace delimited or hyphenated". Can you see if that works?

**Comment by apoorvmote** [comment]
I updated from `@aws-amplify/datastore` version 2.0.7 to 2.08 and it started working without whitesapce delimiter or hyphen
