### ISSUE TITLE
Deployment and Downtime Clarification

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3973]
** Please describe which feature you have a question about? **
Deployments

** Provide additional details**
I have a few general question about deployments and downtime. 
1. During the backend phase of the build when CloudFormation stacks are updating, what kind of downtime should I expect? Does it depend on the change set and services changing? Can you offer some information about how the main services are affected during deployment including AppSync, APIGW, Lambda and DynamoDb?
2. Similar question to 1 but with respect to the front end deployment phase. How is CloudFront and S3 affected during deployment.

**Comment by alexkates** [comment]
Thanks everyone, that's all the clarification I was looking for!

**Comment by houmark** [comment]
As everyone said, and just a tip if you didn't think of it. Make sure you don't delete resources in one deployment that your current frontend code depends on / uses, then you can have zero downtime. Deprecate and remove fully in a later deployment when you are sure everyone is on the new frontend version.

**Comment by alexkates** [comment]
Great tip. Thanks!
