### ISSUE TITLE
How to add access to API for Cognito Identity Pool via Amplify CLI?

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#3975]
**Which Category is your question related to?**
API, Auth

**Amplify CLI Version** 
`4.18.0`

**What AWS Services are you utilizing?**
AppSync, Cognito

**Provide additional details e.g. code snippets**
1. `amplify add api`, choose IAM, and `amplify push`
```
? Please select from one of the below mentioned services: `GraphQL`
? Choose the default authorization type for the API `IAM`
```

2. `amplify add auth`, choose a few default configuration.

3. `amplify push` to create the AppSync backend and Cognito User Pool/Identity Pool.

4. `amplify add functions`, and give it access to API
```
? Do you want to access other resources created in this project from your Lambda function? `Yes`
? Select the category `api`
```
ref: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

5. `amplify push` and find your way to the lambda in AWS Console, verify that the lambda has the right permissions to talk to AppSync. 
![image](https://user-images.githubusercontent.com/1365977/79388756-be819380-7f22-11ea-915c-51eb74ddcb54.png)

Going over to the `amplify-lambda-execution-policy` that was added to the IAM Role for that lambda shows
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "appsync:Create*",
                "appsync:StartSchemaCreation",
                "appsync:GraphQL",
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*",
                "appsync:Delete*"
            ],
            "Resource": [
                "arn:aws:appsync:us-west-2:1111111111:apis/abc123/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

Amplify API can make calls to AppSync using Amplify Auth with sigV4 signing on the request. Common use case is that I want to create an app that shows some data even when the user has not signed up. I want to allow unauthenticated users to only do certain GraphQL operations and authenticated users to do more. 

docs have an example of restricting access https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-iam-authorization
```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
            "appsync:GraphQL"
         ],
         "Resource": [
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Query/fields/<Field-1>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Query/fields/<Field-2>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Mutation/fields/<Field-1>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Subscription/fields/<Field-1>"
         ]
     }
   ]
}
```

Is there a way to enable access to API from `amplify add auth` like we do with functions, storage, etc? Not sure if i missed a decision tree somewhere. Or is this use case complex enough since it really depends on the developer's GraphQL operations that they'll have to go into AWS Console to modify their identity pool's unauth/auth role anyways?

**Comment by kaustavghosh06** [comment]
What's your use case out here? 
Is it giving unuathneticated access to customers for your AppSync API?

**Comment by kaustavghosh06** [comment]
The granularity that you're looking for could be solved by @auth directive which works with Cognito user pool auth type. Out there you can define field level auth rules and accomplish the use-case that you've described above.

**Comment by lawmicha** [comment]
hey @kaustavghosh06 thanks for replying. In general, i'm just trying to understand how to use IAM auth as the mode of authentication from an app. It sounds like @auth directive has what I need. Let me try this out and see if we can improve the example schemas that can be chosen as part of the `amplify add api` flow. i'll also re-verify that using @auth with iam provider will probably fail at `amplify push` if `amplify add auth` hasn't been added yet.

The use case example is; from my app i want to limit the actions the users can perform when they are unauthenticated (read only) verse authenticated (read/write/etc) with IAM auth. It looks the experience is I can continue to use @model and decorate it with @auth directive with multiple rules on the directive like
https://aws-amplify.github.io/docs/cli-toolchain/graphql#combining-authorization-rules

 the mobile app requires the user to sign in with user pools while another app only requires  only query to get some data. 

I forgot about @auth directive supporting `iam` as a provider. I'll try creating a sample schema describing a typical use case, something from here https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth to verify my understanding and the the backend provisioning, ie. auth is created, cognito identity pool with roles having the correct policies, etc. and perhaps it can serve as sample when developers run `amplify add api`.

**Comment by lawmicha** [comment]
didn't get a chance to look into this again, will close this for now, the link above in general is related to auth modes on the API.
