### ISSUE TITLE
authPreSignup default function fails

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#3979]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After adding the auth authPreSignup signup failes with error: CustomMessage failed with error index.handler is undefined or not exported. (In broeser)

When running amplify mock authPreSignup it failes with error: 
```
(node:4238) UnhandledPromiseRejectionWarning: Error: Could not load lambda handler function due to Error: Cannot find module '/..../amplify/backend/function/authPreSignup/src/index'
```

CustomMessage failed with error index.handler is undefined or not exported.

**Amplify CLI Version**
4.18.0

**To Reproduce**
1. Add authPreSignup
2. Run amplify mock function authPreSignup -> missing src/index.js
3. Log in from browser: -> index.handler is undefined or not exported

**Expected behavior**
Both mocking and actual backend should just work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version v10.17.0

**Additional context**
If I add src/index.js, mockin works (using the code below).
If I change authPreSignup/index.js to:
```
exports.handler = (event, context, callback) => {
  callback(null, event);
};
```
Then it works.
I've also succeded with exporting "custom" in env, but don't remember exactly how.

In total this is not a good developer experience. It feels like a bug.

**Comment by edwardfoyle** [comment]
This is fixed by #3928. We are planning to do a release that includes this change by the end of the week

**Comment by djkmiles** [comment]
It's not enough to just move that file because the whole package/zip/tree isn't being made properly, the dependencies are unavailable. This issue is not closed, this is a critical issue that prevents release. It affects other cognito trigger functions as well, such as post-confirmation

It's not cool to be closing issues until they are handled

Version 4.18.0 does not fix this

**Comment by edwardfoyle** [comment]
@djkmiles Sorry, you're right, you also need to move the package.json file into the src folder. Everything in the src folder will be zipped and uploaded to Lambda. #3928 above will fix the issue, but we ran into some other issues getting a release out last week so it's not available yet. I'll reopen until the release is complete

**Comment by edwardfoyle** [comment]
@djkmiles This should be fixed in the latest release (4.18.1). Feel free to reopen if you're still running into issues.

**Comment by kjetilge** [comment]
So I tried the same as above again today using ```amplify --version
4.19.0```

```
amplify mock function funcnameAuthPreSignup
Provide the path.... src/event.json
Could not find ref for "modules". Using unsubstituted value.
Could not find ref for "DOMAINWHITELIST". Using unsubstituted value.
Could not find ref for "DOMAINBLACKLIST". Using unsubstituted value.
Starting execution...
ffba7AuthPreSignup failed with the following error:
{ code: 'MODULE_NOT_FOUND' }
Finished execution.
```

So It still does'n wor out-of-the-box.

**Comment by edwardfoyle** [comment]
Hi @kjetilge I believe that is a problem with mock and not with the lambda function itself. We are tracking the issue where environment variables are not loaded into mock correctly in #4085. Does the function work as expected when uploaded to Lambda via `amplify push`?

**Comment by kjetilge** [comment]
Using ```amplify --version 4.20.0``` it works when uploaded to via Lambda push but not with mock.

**Comment by borisilic** [comment]
I'm having a similar issue with PostConfirmation:

```
-> amplify mock function frontend3a437cf5PostConfirmation

frontend3a437cf5PostConfirmation failed with the following error:
{
  type: 'Lambda:Unhandled',
  message: "Cannot find module './modules'\n" +
    'Require stack:\n' +
    '- /home/boris/Documents/development/frontend/amplify/backend/function/frontend3a437cf5PostConfirmation/src/index.js\n' +
    '- /home/boris/.nvm/versions/node/v12.14.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js'
}

```

**Comment by amirmishani** [comment]
Just tested this with Amplify 4.32.1 and seeing the same issue.

**Comment by ThierDev** [comment]
Tested in Amplify 4.40.0 and getting the same issue too
