### ISSUE TITLE
Amplify daily downtime

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-cli#3984]
Recently we have seen downtime lasting 2-15 minutes on the GraphQL / API Gateway / DynamoDB queries where we just get a `null` result for a normal query when we expect a list of results. Not sure where it happens, logs were not helpful, but maybe I am not looking the right places.

This seems to affect our production environment more than anything else, as our development environment will actually work while production is down and I have not noticed downtime on the development environment but 1-2 times daily on production.

Who can look into this for us and present a solution? We cannot have 5-30 minutes of downtime per day in our production environment. We currently do not have a support plan as we haven't really had the need and I am reluctant to pay $29-$100 monthly to be able to report downtime.

**Comment by edwardfoyle** [comment]
@houmark Do you see any failures in the metrics for AppSync, API Gateway or DynamoDB? You can view the metrics by going to the AWS Console -> CloudWatch -> Metrics -> then pick the service to see metrics available for that service.

Are you getting a null response for GraphQL queries, REST API queries or both? And what is the timeframe of the failures?

**Comment by houmark** [comment]
Sorry for the delay here.

Today we had downtime twice more, one 8 hours ago and another within the last hour.

Here are some screenshots and pasted in query results. In logs for AppSync have not been able to see any logged errors in metrics, as AppSync returns 200 OK and the problem seems to be somewhere else, but DynamoDB was also responsive in the AWS Console while our platform was unresponsive.

Also, this is not a client-side error or issues with the internet at the client. I have users in Dublin, Ireland, users in California, USA, and I am in South America right now. Everyone experienced the downtime at the same time.

```
{data: {searchMembers: null},…}
data: {searchMembers: null}
searchMembers: null
errors: [{path: ["searchMembers"], data: null, errorType: "ExecutionTimeout", errorInfo: null,…}]
0: {path: ["searchMembers"], data: null, errorType: "ExecutionTimeout", errorInfo: null,…}
data: null
errorInfo: null
errorType: "ExecutionTimeout"
locations: [{line: 2, column: 3, sourceName: null}]
0: {line: 2, column: 3, sourceName: null}
message: "Execution timed out."
path: ["searchMembers"]
0: "searchMembers"
```

Screenshot 1:
https://a.cl.ly/RBuvXAEe

Screenshot 2:
https://a.cl.ly/yAu2LzyZ

Over the course of 8-10 months, we saw occasional downtime, like once a week or two weeks for a few minutes, but in the last 2-3 weeks we are seeing it daily and even several times a day.

Could this be one or more instances going unhealthy somewhere and not being removed automatically or very slowly removed, then coming back online later, only to go down again? We have experienced such behavior with other AWS services in the past (Athena instances, which are not part of the platform which becomes unresponsive, so not applicable in this case).

**Comment by edwardfoyle** [comment]
@houmark This seems like a service issue and not a CLI issue. You can search / post in the AppSync forum [here](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0). Unfortunately there's not much we can investigate as we don't own those services.
