### ISSUE TITLE
How can I add a Global Secondary Index to an Existing Table containing data

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#3986]
**Which Category is your question related to?**

amplify push

**Amplify CLI Version** 

3.9.0

**What AWS Services are you utilizing?**

Api

**Provide additional details e.g. code snippets**

schema.graphql

BEFORE

```
type Industry @model {
  id: ID!
  name: String!
}
```

AFTER

```
type Industry @model
  @key(name: "ByName", fields: ["name"], queryField: "industryByName") {
  id: ID!
  name: String!
}
```

ERROR

Attempting to add a local secondary index to the IndustryTable table in the Industry stack. Local secondary indexes must be created when the table is created.
An error occured during the push operation: Attempting to add a local secondary index to the IndustryTable table in the Industry stack. Local secondary indexes must be created when the table is created.

**Comment by edwardfoyle** [comment]
Hi @christodupreez The schema you have above should create a GSI. Can you try updating to the latest version of the CLI (4.18.0) and trying again?
