### ISSUE TITLE
RDS role already exists in stack

### ISSUE THREAD

**Issue by mdepascale** [aws-amplify/amplify-cli#3988]
**Describe the bug**
While pushing into the cloud amplify tries to create an already created role

**Amplify CLI Version**
4.17.2

**To Reproduce**
- any changes to the rds autogenerated CF template
- amplify push

**Expected behavior**
amplify push doesn't create any existing role

**Screenshots**
`CREATE_FAILED      RelationalDatabaseAccessRole    AWS::IAM::Role                      Fri Apr 17 2020 14:32:52 GMT+0200 (Central European Summer Time) role-APPSYNC_ID-dev already exists in stack arn:aws:cloudformation:XXX:XXX:stack/amplify-XXX-XXX-XXXjson-XXX/XXX`

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v12.16.1

**Additional context**
```
"RelationalDatabaseAccessRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "role",
              {
                "Ref": "AppSyncApiId"
              },
              {
                "Ref": "env"
              }
            ]
          ]
        },
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "appsync.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "RelationalDatabaseAccessPolicy",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "rds-data:ExecuteSql",
                    "rds-data:ExecuteStatement",
                    "rds-data:DeleteItems",
                    "rds-data:GetItems",
                    "rds-data:InsertItems",
                    "rds-data:UpdateItems"
                  ],
                  "Resource": [
                    {
                      "Ref": "rdsClusterIdentifier"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "secretsmanager:GetSecretValue"
                  ],
                  "Resource": [
                    {
                      "Ref": "rdsSecretStoreArn"
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    }
```
Amplify tries to create this role, but it exists
(we solve it by doing some amplify pull and manual changes, but we encounter it almost every day and it's getting annoyed)

**Comment by mdepascale** [comment]
> we solve it by doing some amplify pull and manual changes

of course it doesn't work anymore, are there any news? **we literally can't push**
we tried upgrading amplify cli to 4.18.0 but the issue persists

**Comment by brene** [comment]
Hi @mdepascale - are you free to jump on a call for this? We'd like to do a next-level investigation and resolve this issue for you. Can you DM me on Twitter, so we can align on a good time for the call? twitter.com/renebrandel

**Comment by ArshAulakh59** [comment]
I'm stuck with the same issue. Trying to recreate ElasticSearch IAM role in my case. Would be great help to fix this :)

**Comment by nikhname** [comment]
@mdepascale what changes were made to the RDS cloudformation template?
@ArshAulakh59 were there any changes made to the CF templates on your project?

**Comment by UnleashedMind** [comment]
@mdepascale 
If you are not blocked anymore after the call, we are going to close the issue.   

@ArshAulakh59 
Could you create another issue with detailed description how to reproduce?

**Comment by dbtorrance** [comment]
I am experience this same issue with my project. Is there another issue tracking this now? I could use some help to resolve if anyone has suggestion as well :)

**Comment by mdepascale** [comment]
@dbtorrance sorry I should have added some info
what we had found out is, if you rename your rds-autogenerate-stack changing from uppercase to lowercase, github doesn't find the changes and it messes with amplify's push
We were able to fix it by removing the rds-autogenerate-stack, committing it, and paste the rds-autogenerate-stack and committing it back on
