### ISSUE TITLE
amplify push error

### ISSUE THREAD

**Issue by ashishlata** [aws-amplify/amplify-cli#3989]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

**Amplify CLI Version** 
4.17.2

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
amplify 

**Provide additional details e.g. code snippets**
<img width="468" alt="Capture1" src="https://user-images.githubusercontent.com/47843502/79573384-32877d00-8084-11ea-8e7f-c5b5aa05ffc0.PNG">

problem:

while pushing my lambda function to cloud it's giving below error ,as i attached in the snap
✖ An error occurred when pushing the resources to the cloud

Only one CloudFormation template is allowed in the resource directory
An error occured during the push operation: Only one CloudFormation template is allowed in the resource director

**Comment by edwardfoyle** [comment]
@ashishlata when you check your function folder do you have 0 or multiple cloudformation templates in there? Can you try updating to the latest version of the CLI and creating the function again?

**Comment by wildergd** [comment]
i am also having this issue... my environment node v12.13.1, amplify v4.18.0... 
the problem only accurs when i add auth category.... if i add hosting or any other it works fine....
my steps:
>amplify init
>amplify add auth 
Using service: Cognito, provided by: awscloudformation
Do you want to use the default authentication and security configuration? Default configuration
How do you want users to be able to sign in? Username
Do you want to configure advanced settings? No, I am done.
>amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name             | Operation | Provider plugin   |
| -------- | ------------------------- | --------- | ----------------- |
| Auth     | fashionclipsreactb76708ce | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠋ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠙ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

PD: attached amplify folder generated by amplify-cli

[amplify.zip](https://github.com/aws-amplify/amplify-cli/files/4501594/amplify.zip)

**Comment by edwardfoyle** [comment]
@wildergd I'm not sure that's the same issue. Do you see the error "Only one CloudFormation template is allowed in the resource directory..." in the error message? If not, could you open a separate issue for the problem you're seeing so we can track it separately. Thanks!

**Comment by jhockett** [comment]
Closing this issue due to lack of response.
