### ISSUE TITLE
Multiple custom Mutations not triggering Lambda function. 

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#3997]
**Which Category is your question related to?**
- API
- Functions

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.18.0

**What AWS Services are you utilizing?**

- Lambda
- AppSync GraphQL API

**Provide additional details e.g. code snippets**

Hi all,

I've been struggling to add a second custom Mutation in my GraphQL schema. These custom Mutations should trigger lambda functions to determine whether a user enough resources in their account (tiered usage limits) to add say a Template or a Project. The first function I added is working and being triggered by my React App. Everything works fine for adding Projects. I added a second Mutation using the `extend type Mutation` syntax. Everything is identical to the the addProject Mutation/Function with the neccessary tweaks. However, when executing the Mutation in the React app the lambda function is not triggering and checking the App Sync UI on the AWS management console shows that another lambda function was not added. Any idea as to what I'm doing wrong here? Is this a bug?

```graphql
type Mutation {
  addProject(name: String!): String
    @function(name: "createProject-${env}")
}

extend type Mutation {
  addTemplate(
    name: String!
    type: String!
    width: String!
    height: String!
  ): String @function(name: "createTemplate-${env}")
}
```

The strange thing is that the first Mutation works but the second doesn't the only difference is the `extend type Mutation` syntax. Is this what is causing the issue with the Amplify CLI not creating the second function entry in AppSync?

Thanks in advance! Best regards and hope all is well,

Kyle

**Comment by kylekirkby** [comment]
So I got this working by changing my GraphQL schema as follows:

```graphql
type Mutation {
  addProject(name: String!): String
    @function(name: "createProject-${env}")
}

extend type Mutations {
addTemplate(
    name: String!
    type: String!
    width: String!
    height: String!
  ): String @function(name: "createTemplate-${env}")
}

```
to

```graphql
type Mutation {
  addProject(name: String!): String
    @function(name: "createProject-${env}")
  addTemplate(
    name: String!
    type: String!
    width: String!
    height: String!
  ): String @function(name: "createTemplate-${env}")
}

```

Is this intended behavior?  Hope this helps someone!

Cheers!

Kyle

**Comment by SwaySway** [comment]
Hello @kylekirkby 
If your schema file is in one location then the 2nd format is the right format for this.
The use of `extends` on operations is used by the GraphQL transformer when you split your schema in different files. Ref here: https://aws.amazon.com/blogs/mobile/merging-graphql-schema-files-and-more-with-the-cli/

**Comment by kylekirkby** [comment]
Arhh makes sense! Thanks @SwaySway !
