### ISSUE TITLE
Auth enable flow asks SMS message customization question even when TOTP only is selected

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-cli#40]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
The auth enable flow asks SMS messgae customization question even when MFA only is selected.

**Comment by imoark** [comment]
What is the solution to this?? Also, it seems that you CANNOT just set TOTP as the MFA method. Somehow, the SMS is also choose, and set as the current MFA method.

**Comment by et304383** [comment]
Why was this closed?  This is STILL an issue.
