### ISSUE TITLE
Aurora: MySQL vs Postgres Support

### ISSUE THREAD

**Issue by kennandavison** [aws-amplify/amplify-cli#4001]
Hi, moving over to AppSync and did a bit of testing of Aurora Serverless MySQL and Postgres!

`add-graphql-datasource` appears to only be supported partially by MySQL and not at all by Postgres. Decorator support (@model/@auth) is only available for DynamoDB, but with MySQL over Postgres you get the plus of editing schema.graphql locally + being able to push to AppSync and having resolvers autogenerated on initial database check (Postgres does no resolver generation). 

Does this sound right/am I missing any other advantages? Also, any word on when MySQL will get @model support/Postgres will have parity with MySQL?

I guess my high level goal is to understand if MySQL is more 1st class than Postgres here (deciding between the two still).

Related: 
* https://github.com/aws-amplify/amplify-cli/issues/1914
* https://github.com/aws-amplify/amplify-cli/issues/3081

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
AppSync + Amplify + Aurora RDS Serverless Postgres/MySQL

**Comment by nikhname** [comment]
@kennandavison You are correct, with MySQL you will be able to generate a schema from the tables used in Aurora and modify it locally. The resolvers will be autogenerated as you mentioned. We are discussing @ model and @ auth support in the RDS transformer in the future. 

Please feel free to comment if you have further questions.

**Comment by cookmscott** [comment]
@nikhname are there any examples or guides you know of that highlight how to do so? I feel like the [documentation](https://docs.amplify.aws/cli/graphql-transformer/relational) should mention the current limitations of what the cli provides out of the box.
