### ISSUE TITLE
Mock API not working with amplify-cli 4.18.0

### ISSUE THREAD

**Issue by gautamkshitij** [aws-amplify/amplify-cli#4002]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I upgraded the amplify cli and the mock API isn't working anymore though If I use `curl` I still get a GraphQL response.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
`4.18.0`
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
- add some GraphQL API with `@model` attribute
- run `amplify mock API`
- 
![Screen Shot 2020-04-18 at 7 26 52 PM](https://user-images.githubusercontent.com/3483377/79677889-91471680-81aa-11ea-9e6a-34dd25c9986d.png)

Though `curl` works

```
curl 'http://192.168.50.103:20002/graphql' -H 'Connection: keep-alive' -H 'Accept: application/json' -H 'DNT: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36' -H 'x-api-key: da2-fakeApiId123456' -H 'Content-Type: application/json' -H 'Origin: http://192.168.50.103:20002' -H 'Referer: http://192.168.50.103:20002/' -H 'Accept-Language: en-US,en;q=0.9' --data-binary '{"query":"query MyQuery {\n  list {\n    items {\n      name\n      id\n      number {\n        phoneNumber\n        id\n      }\n    }\n  }\n}\n","variables":null,"operationName":"MyQuery"}' --compressed --insecure
```

**Expected behavior**
Mock API should work!

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v13.13.0

**Comment by gautamkshitij** [comment]
Same as this - though the recommended solution claims that this has been fixed in latest versions
https://github.com/aws-amplify/amplify-cli/issues/3435

**Comment by gautamkshitij** [comment]
Wait a minute - so this shows http://localhost:20002/ `graphiql` explorer and things work :| maybe just update the console.log output from `amplify mock API`? 

Also - the default `auth ` was IAM - had to change it to the API key. The icon for that was hiding in a corner (spent almost 30 mins to find why the queries were not working - since I started getting 
```
message": "Not Authorized to access blahBlah on type Query",
      "errorType": "Unauthorized"
```
)

**Comment by gautamkshitij** [comment]
Ok! it works on firefox http://192.168.50.103:20002/ but not on chrome. a

**Comment by akshbhu** [comment]
Hi @gautamkshitij 

Is the amplify mock still stuck on chrome?

**Comment by gautamkshitij** [comment]
Yes 💯 - Just did `amplify mock api` - and didn't open it in chrome. I am happy to pair and demo as well!

**Comment by gautamkshitij** [comment]
I think we can less prioritize it - since it's working. But definitely panicked after upgrading amplify and spending horus figuring out why it didn't. Hopefully people will this Issue and the solution (which is just try localhost or firefox)

**Comment by akshbhu** [comment]
Just to be sure , are you opening the Graphql endpoint mentioned in the console when you run ```amplify mock api```.
Something like this 

```AppSync Mock endpoint is running at http://10.0.0.135:20002```

**Comment by gautamkshitij** [comment]
Yes! Whatever amplify mock api gives me the link to check

**Comment by gautamkshitij** [comment]
@akshbhu  - i can confirm it work on chrome - but i have to clear my cache - every single time.

**Comment by akshbhu** [comment]
Okay. Good to know it works. May be update chrome to latest version will solve this. For now I am closing this issue , if you are still stuck , you can comment on this and I will reopen this issue.
