### ISSUE TITLE
Is it possible to have multiple Graphql APIs ?

### ISSUE THREAD

**Issue by abouroubi** [aws-amplify/amplify-cli#4004]
**Which Category is your question related to?**
AWS CLI

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**
I'm trying to add a new API to my project, but it seems I'm limited to one, is this really the case ?
When running `amplify add api` I have this error `You already have an AppSync API in your project. Use the "amplify update api" command to update your existing AppSync API.`, I don't want to update the existing one, I want a new API.

**Comment by siddharthsharma94** [comment]
why would you want 2 GraphQL Apis in one project? If you have a need for a 2nd one, I'd just create a new project and just use the 2nd one there.

**Comment by abouroubi** [comment]
Why would I create a new API related to the same project in another one ?
I have 2 business cases for the same project and I want to separate them in two different api's

**Comment by siddharthsharma94** [comment]
GraphQL's paradigm kind of implies everything should be in an all in one setting. I think Amplify projects have limits on this to enforce this. Maybe with proper logic abstraction, one API could work? If not I don't see how you can make a 2nd GraphQL API in one project.

**Comment by SwaySway** [comment]
The CLI currently does not support more than one GraphQL API per environment. What you can do is create a GraphQL API in a different environment. This would allow you to have a different API in your dev environment as opposed to your prod environment.

Docs on Environments: https://docs.amplify.aws/cli/teams/overview#setting-up-master-and-dev-environments

**Comment by JPVan** [comment]
I considered multiple APIs as a way to save high volume daily data locally and then summarize it for saving in the cloud. I was hoping that I could use one API locally only with DataStore, and the other Amplify API with DataStore and AppSync. But Amplify isn't meant to be used this way. Is there another way of accomplishing this? If I could force my Amplify app into offline (DataStore only) mode, that would do it for me, but that also doesn't seem to be a feature (yet) either.
