### ISSUE TITLE
how to get custom cloudformation to deploy

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#4006]
**Which Category is your question related to?**
[Custom](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#custom-cloudformation-stacks)

**Amplify CLI Version** 
```bash
$ amplify -v
4.18.0
```

**What AWS Services are you utilizing?**
Step Functions, AppSync, Lambda, etc

**Provide additional details e.g. code snippets**
I'm trying to pass the ARN of a Step Functions statemachine into a Lambda. This is way harder than it should be. I started passing a hard-coded ARN via `amplify/team-provider-info.json` (which took a long time to discover support for) but  the statemachine is growing and it will need access to resources created from amplify (API) so I can no longer create the statemachine outside of amplify (chicken vs egg).

I followed the instructions for Custom Cloudformation support,  but nothing seems to pick it up.

I added this to `amplify/backend-config.json` :

```json
{
  "function": {
     "createdByAmplify": {
        "dependsOn": [
          {
            "category": "customWorkflow",
            "resourceName": "audio",
            "attributes": [
              "stateMachineArn"
            ]
          }
        ]
      }
  },
  "customWorkflow": {
    "audio": {
      "build": true,
      "service": "StepFunctions",
      "providerPlugin": "awscloudformation"
    }
  }
}
```

...as well as the folder `amplify/customWorkflow/audio` and the CF templates to make the needed stuff.

I removed the placeholder I had in `amplify/team-provider-info.json` that supplied the parameter to a function resource for the 

Running `amplify status` shows no signs of my custom stack. Running `amplify push` tells me there are no changes. Running `amplify push --force` results in a cloudformation error that `stateMachineArn` is not defined and there is no evidence of an attempt to create any resources defined in the custom stack.

Ive been stuck on annoying things using amplify that I can do easily when I'm not using amplify. I'll need to ditch it soon. I'd prefer not to ditch it but maybe I should save myself the trouble. Help please. This is my final call.

**Comment by SwaySway** [comment]
Hello @cyrfer 
After making those changes in your amplify project if you run `amplify env checkout <current-env-name>` and `amplify status` does it show your custom stack?

**Comment by dwamianm** [comment]
@cyrfer ... I am not sure if you are still looking for help here but I recommend doing something like the following:

Step 1: I recommend creating a section in your `backend-config.json` so they are obvious when running push. In the below example you would put them under a `stateMachines` folder under `amplify>backend` folder.

`"stateMachines": {
    "scheduleSmsStateMachine": {
      "service": "StepFunction",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "functionItDependsOn",
          "attributes": ["Name"]
        },
        {
          "category": "function",
          "resourceName": "anotherFunctionItDependsOn",
          "attributes": ["Name"]
        }
      ]
    },`

Step 2: Then run `amplify env checkout <current-env-name>` as @SwaySway pointed out before.
Step 3: I dont recommend naming the CF template `template`. The amplify docs does't do a good jump of telling you this but it you name it `template` then amplify will only pick up the first of last file of this name that it finds... that took me a whole day to figure out...

Instead, follow the convention that amplify follows in other folders and name it after the resource... e.g. If you have a state machine foo... name the CF template `fooStateMachine-cloudformation-template.yaml`... `.js` if you prefer

Step 4: Be sure to Output your statemachine ARN in the CF template by giving it a sweet name in the Outputs section. 

e.g

`Outputs:
  MyFooStateMachine:
    Description: Arn of MyFooStateMachine
    Value: !Ref MyFooSM` <--- that is whatever name you give the State Machine under "Resources" in the CF template

Step 5: (and this is another quirk)
include the state machine reference under "Parameters" in the CF template of the lambda that will call it with the name <category><resource-name><attribute-name>

e.g. "stateMachinefooStateMachineMyFooStateMachine": {
			"Type": "String",
			"Default": "stateMachinefooStateMachineMyFooStateMachine"
		},

Step 5: Run Then run `amplify env checkout <current-env-name>` for good measure

Good luck

**Comment by cyrfer** [comment]
@SwaySway I think I ran "amplify env pull" and it wiped out my changes. I don't see my files anymore. I do see a new folder called `amplify/backend/awscloudformation/nested-cloudformation-stack.yml`

This project must be one of the most confusing things Ive ever used. I think the goals are good, so I keep trying, but why is it designed with so my fragility?

**Comment by cyrfer** [comment]
@dwamianm how did you figure all that out? it doesn't seem logical.

**Comment by cyrfer** [comment]
@SwaySway I think I needed to run `amplify pull` first. It was the only way I could get amplify to recognize when I changed `backend-config.json`.

I noticed some clear instructions over [here](https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916), and now my `backend-config.json` includes only this change:
```json
  "stateMachine": {
    "audio": {
      "providerPlugin": "awscloudformation"
    }
  },
```

After adding the folders and files,
`amplify/backend/stateMachine/audio`
* parameters.json  (must not be valid JSON content, I had left it an empty file at first!)
* template.json

I can finally get `amplify status` to recognize the new cloudformation. Running `amplify push` deploys the nested stack and succeeds as expected.

Now i'm wondering how I can pass the output of my statemachine stack to my function stack so my Lambda can execute the state machine. I've seen people say that [Fn::ImportValue](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) is the best way.

**Comment by cyrfer** [comment]
OMG I discovered a great feature in amplify. I wish I knew where it was documented. Apparently I can modify the `parameters.json` file in my function stack, and that will pass cloudformation parameters. The really interesting thing is that you can tell amplify to import a output value of another stack like this:

```json
{
  "stateMachineArn": {
    "Fn::GetAtt": [
        "stateMachineaudio",
        "Outputs.StateMachineArn"
    ]
  }
}
```

`stateMachineArn` is the parameter needed by my function stack. `stateMachineaudio` is the weird naming convention @dwamianm  warned me of.

**Comment by dwamianm** [comment]
> @dwamianm how did you figure all that out? it doesn't seem logical.

@cyrfer ...some of it was trial and error. Some of it was getting to understand cloudformation templates better... and believe it or not...some of it (a very small part) is in the amplify documentation here https://docs.amplify.aws/cli/usage/customcf
