### ISSUE TITLE
Question about Many to Many Likes to Own Self Object with @connection

### ISSUE THREAD

**Issue by siddharthsharma94** [aws-amplify/amplify-cli#4008]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
GraphQL Transform

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

So Basically what I'm trying to do, is create a Dating kinda app. In this, a user can like someone or they  can be liked by someone who they dont yet like. How would I do this in the schema, I'm getting kinda confused.

So far I have this

```javascript
type User @model {
  id: ID!
  name: String!
  age: Int
   ...
  likes: [UserLike] @connection(name: "UserLikesSomeone")
}

type UserLike @model(queries: null) {
  id: ID!
  likedUser: User @connection(name: "UserLikesSomeone")
}
```

but this doesn't seem to work and it makes sense why it doesn't work because there is no connection from where this like originated. 

How would i connect the UserLike to the user performing the like, since the @connection needs a 2nd half. Would i need to add a field or something to the user. I'm just getting confused I think.

**Comment by jhockett** [comment]
Hi @siddharthsharma94! I would leverage the @key directive like so:

```graphql
type User @model {
  id: ID!
  likes: [Like] @connection(keyName: "byOriginUser", fields: ["id"])
  likedBy: [Like] @connection(keyName: "byTargetUser", fields: ["id"])
}

type Like @model(queries: null)
  @key(name: "byOriginUser", fields: ["originUserId"])
  @key(name: "byTargetUser", fields: ["targetUserId"])
{
  id: ID!
  originUserId: ID!
  originUser: User @connection(fields: ["originUserId"])
  targetUserId: ID!
  targetUser: User @connection(fields: ["targetUserId"])
}
```
Let me know if that helps. I'm closing this issue for now, but feel free to comment if you have further questions and we can re-open the issue.
