### ISSUE TITLE
Amplify CLI install using npm fails

### ISSUE THREAD

**Issue by NashifAlam** [aws-amplify/amplify-cli#4011]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Installation 

**Provide additional details e.g. code snippets**
On attempting
`npm install -g @aws-amplify/cli`
Installation fails after sometime

**Output**
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated `           
`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated `            
`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended `
`for usage due to the number of issues. Please, upgrade your dependencies to the actual version of 
core-js@3.`
`npm ERR! Maximum call stack size exceeded`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\Nashif Alam\AppData\Roaming\npm-cache\_logs\2020-04-20T09_56_51_282Z-debug.log`

**Debug Files**
[2020-04-20T09_56_51_282Z-debug.log](https://github.com/aws-amplify/amplify-cli/files/4502668/2020-04-20T09_56_51_282Z-debug.log)

**Comment by akshbhu** [comment]
Hi @NashifAlam 

One thing you can try is deleting node_modules installed and try reinstalling them again using 
``` javascript
npm install
```
Let me know if it works for you?

**Comment by NashifAlam** [comment]
I have already tried it but after deleting node_modules npm gets corrupt, hence I had to reinstall it.

**Comment by NashifAlam** [comment]
I figured out the problem, it was not with the Amplify CLI but with Nodejs,
On installing Nodejs v13.13 the problems ceased and the CLI installed successfully, the problem was with the previous versions of Nodejs

**Comment by NashifAlam** [comment]
> 
> 
> Hi @NashifAlam
> 
> One thing you can try is deleting node_modules installed and try reinstalling them again using
> 
> ```js
> npm install
> ```
> 
> Let me know if it works for you?

I have already tried it but after deleting node_modules npm gets corrupt, hence I had to reinstall it.

**Comment by thisismydesign** [comment]
Having the same issue.

> Try deleting node_modules installed and try reinstalling them

The docs propose a global install so that isn't really an option.
