### ISSUE TITLE
Could not find ref for "GROUP". Using unsubstituted value.

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#4012]
Why am i getting `Could not find ref for "GROUP". Using unsubstituted value.` every time i run amplify mock? Is something broken in my project? 

**Which Category is your question related to?**
`amplify mock` command

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
appsync, cognito, ddb, s3

**Comment by edwardfoyle** [comment]
@kldeb It means that there is a ref for GROUP somewhere in your CloudFormation templates but mock was unable to determine what the ref was to, so it defaulted to using the literal string "GROUP". If that reference is something that you manually added to your templates then it's probably fine that mock can't resolve it as long as you have made sure there is something in place in the cloud to resolve it there. If the ref is something created by Amplify it's possible that there is some issue.

Have you seen any issues related to resolving that value when you push your resources?

**Comment by AbirAbbas** [comment]
getting this issue as well, the refs were autogenerated by amplify update function, like dynamodb storage names, arns, etc. also amplify mock doesn't work on expressjs lambda fuinctions

**Comment by kldeb** [comment]
@edwardfoyle I logged this issue a while ago, could be related: https://github.com/aws-amplify/amplify-cli/issues/2841

**Comment by ammarkarachi** [comment]
@kldeb It's basically a warning message if it doesn't find the value in your CFN template but is later set using the amplify-meta.json which is generated after a successful push

**Comment by AbirAbbas** [comment]
> @kldeb It's basically a warning message if it doesn't find the value in your CFN template but is later set using the amplify-meta.json which is generated after a successful push

I've had a successful push and it still provides the same message. I've tested this on a brand new project as well to ensure it wasn't just my project that was having issues but it persists there as well.
