### ISSUE TITLE
Does Amplify package up the entire node_modules folder?

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-cli#4018]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

API

**Amplify CLI Version** 
4.18.0

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

API Express Server

**Provide additional details e.g. code snippets**

When we run `amplify push` does that package up the entire `node_modules` folder and push it to cloud formation, or is the `node_modules` recreated on the AWS side?

I have local dependencies that are provided by Verdaccio.  If the `node_moduels` folder is recreated, then obviously Verdaccio installed dependencies will fail.

Also asked on SO:
https://stackoverflow.com/questions/61339972/does-the-aws-amplify-push-package-up-the-entire-node-modules-folder

**Comment by edwardfoyle** [comment]
@fireflysemantics `amplify push` packages up everything in `src` within the function directory which should include your node modules

**Comment by fireflysemantics** [comment]
I figured it would do that, however as soon as I include the local dependency the entire function call to the express server fails.

This is my test:

//const stripeapi = require('@fireflysemantics/stripe')

If I uncomment this, so that that dependency is included, and push the function call starts failing.

How do I debug this on the AWS side?
