### ISSUE TITLE
AppSync Lambda mock is broken

### ISSUE THREAD

**Issue by bboure** [aws-amplify/amplify-cli#4019]
**Describe the bug**

Using the `callback()` function in lambdas no longer works with the AppSync simulator.

Example:
````js
export default function (event, context, callback) {
  setTimeout(() => {
    callback(null, "response");
  }, 1000);
}
````

The response is always null.

The issue seems to have been introduced [here](https://github.com/aws-amplify/amplify-cli/pull/3254/files#diff-83f15b92fdd2f8b2d0ce1db08fd96fd9R83)

The reason is that the above function returns undefined, and `context.done(null, null);` is called immediately. When `callback()´ is finally called, it is already too late.

**Amplify CLI Version**
Starting at `amplify-util-mock@3.13.2`

**To Reproduce**
Use the example lambda above with the AppSync simulator.

**Expected behavior**
`invokeFunction()` should wait for the lambda to call the callback.

**Additional context**
Introduced in #3254 

cc: @ammarkarachi

**Comment by akshbhu** [comment]
Hi @bboure 
You have to return a promise here.
``` javascript
return new Promise(() => setTimeout(() => {
callback(null, "response");
}, 1000));
```

**Comment by bboure** [comment]
Thank you @akshbhu 
I know I can just return a promise 😄 

Problem is, I am using https://github.com/middyjs/middy and internally it uses the callback instead of promises. 
So that is kinda out of my hands.

**Comment by royalaid** [comment]
I just want to echo that I am encounter this issue too and because I am using Clojurescript it is much more ergonomic for me to use the callback argument instead of a promise

**Comment by ammarkarachi** [comment]
@bboure This would break users that return null/undefined after a lambda function is invoked. Right now the way your code is structured you are still returning an undefined. I have no hook to wait on for your use case

**Comment by bboure** [comment]
@ammarkarachi Thank you for your feedback.

I think there should be basically 2 use cases:
- null/undefined is be returned by the callback (`callback(null, null);`)
- a promise is returned by the lambda, and that promise resolves as null/undefined

What is the use-case of returning null/undefined directly ?

**Comment by ammarkarachi** [comment]
@bboure In issue #2502 the GraphQL API when returning no data would face this problem

**Comment by bboure** [comment]
@ammarkarachi I am not sure in what circumstances a lambda would return anything else than a promise.
I see that on [this line](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/execute.ts#L79) we are assuming that the lambda is returning a promise (use of `await`). Which is not always the case.
I assume that your use case in #2502 is expecting a promise resolving to something falsy?

So, in order to fix this issue, what if we checked the returned value of the lambda first?
The [current logic](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/execute.ts#L80-L84) should only be executed in case of a promise.

If not, then, the [callback](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/execute.ts#L65-L67) is assumed to be called by th e lambda itself.
