### ISSUE TITLE
After removing cloudFront  (Hosting endpoint information is not updated).

### ISSUE THREAD

**Issue by rizerzero** [aws-amplify/amplify-cli#402]
Hi,
After removing cloudfront i noticed that the endpoint information is never updated when i use amplify status command even after making a push or a publish.
even if my amplify publish is uploading the files to the S3 and not to cloudflare it still shows the cloudflare endpoint. 

1. amplify publish ( publish to s3 bucket check status to see the hosting endpoint) 
2. amplify hosting configure to add cloudfront  
3. amplify push 
4. amplify status (you can see that the endpoint now is cloudflare endpiont 
5. amplify hosting configure to remove cloudfront 
6. apmify push 
7. amplify status (you can see that the endpoint is still cloudflare and not the dev s3 bucket) 
this information is false ( i can not relay on the git status to be sure i'm pushing to S3 or to cloudFlare 

**Expected behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/1518379/48063072-342cf000-e1c4-11e8-9bd3-41c02443189d.png)

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser chrome 
 - Version :70

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks, this is a known issue, we are working to resolve it.

**Comment by rizerzero** [comment]
By the way i think that the command amplify status should be added to the workflow on the documentation to me it's clear that the right process should be : 

0. Make a change 
1. Push 
2. Check with "status" that everything is ok and the that the correct destiniation is configured (prod/dev) 
3.Publish

**Comment by UnleashedMind** [comment]
@nirvdrum 
There's no workaround at the moment, the urls are in the `amplify/backend/amplify-meta.json` file,  as  "CloudFrontSecureURL",  "WebsiteURL", but of course the `CloudFrontSecureURL` is no longer working after the CloudFront is removed.
