### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#4020]
Hi,

I use Amplify services from eu-west-1 and "amplify push" is very very slow...

Any problems currently ?

**Comment by akshbhu** [comment]
Hi @rudyhadoux 

There can be some minor problems. If the operations continue to be slow or problematic, please circle back on this.

**Comment by rudyhadoux** [comment]
Ok thanks.

**Comment by tobiasfeil** [comment]
Still very slow. Created a small-to medium-sized Vue project, then 
```
amplify init
amplify add auth
amplify add api
amplify push
```
takes about 4 minutes. I mean I only have 1M upload speed but I don't think it's trying to upload very large files!?

**Comment by rudyhadoux** [comment]
I don't understand, you did "amplify add hosting" ?
Because your commands are for back-end, not for your front-end bundles.
4 minutes seems to me to be a normal time laps.

**Comment by tobiasfeil** [comment]
No, I haven't done hosting. For now, my goal isn't to deploy anything, just to update the resources (cognito, appsync) in the cloud, like is done [here](https://www.youtube.com/watch?v=cr4LN2U-V34). I don't understand that 4 minutes is normal... There's not that much that needs to be updated?

**Comment by rudyhadoux** [comment]
If you test you can delete and re-create. I do that and it speeds up.
