### ISSUE TITLE
wildcard query for searchable acting weird with spaces

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4026]
**Describe the bug**

Sample data:

```js
[
  {
    id: 'uuid',
    title: 'auto focus textfield'
  },
  {
    id: 'uuid',
    title: 'auto search label'
  },
  {
    id: 'uuid',
    title: 'auto label reports'
  },
  {
    id: 'uuid',
    title: 'disable auto commit on complete'
  }
]
```

The query below works fine and returns all the fields data with "auto" in them,

```graphql
{
  searchMyModel (
    filter: {
      title: {
        wildcard: "auto"
      }
    }
  ) {
    items {
      id
      title
    }
  }
}
```

But when you start adding spaces:

```graphql
{
  searchMyModel (
    filter: {
      title: {
        wildcard: "auto focus"
      }
    }
  ) {
    items {
      id
      title
    }
  }
}
```

I'm expecting this to return:

```js
[
  {
    id: 'uuid',
    title: 'auto focus textfield'
  }
]
```

but it returned:

```js
[]
```

as it's the only one with `auto` and `focus` on the title. I tried adding asterisk all over the place, `*auto focus`, `auto focus*`, `*auto focus*`, `auto*focus`, `*auto*focus*` but none of them worked.

 I'm thinking of it in a way that `like %search%` operator works in MySQL, I might be thinking about it the wrong way but that's the functionality we are looking for.

**To Reproduce**

1. Add sample model

```graphql
MyModel @model @searchable {
  id: ID!
  title: String
}
```

2. Insert the sample data seen above.
3. Execute the queries seen above (aws appsync).

**Expected behavior**

See above

**Screenshots**
N/A

**Smartphone (please complete the following information):**

Not particular to any device.

**Additional context**

See above.

**Sample code**

See above.

**Comment by akshbhu** [comment]
Hi @aprilmintacpineda 

Since the data you are searching on is analyzed data, it wont find ```auto focus ``` in the inverted table created by elasticsearch. Thats why it is coming as empty.
You have to search for both fields in the query as an example
```graphql
query search2{
  searchTodos(filter: {
    and:[
      {
        name : {
          eq : "auto"
        }
      },
      {
        name : {
          eq : "focus"
        }
      }
    ]
  }) {
    nextToken
    total
  }
}
```
Let me know if you are still stuck on this.

**Comment by akshbhu** [comment]
Let me know if above issue is solved. For now I am closing this issue , if you are still stuck , you can comment on this and I will reopen this issue.

**Comment by DavidBrear** [comment]
This worked for me. What I ended up doing was this
```
const splitQuery = query.toLowerCase().split(" ");
const joinedQuery = splitQuery.map((part: string) => ({
  name: { regexp: `.*${part}.*` },
}));```

Then in my filter I just did `filter: { and: joinedQuery } ` Thanks @akshbhu for the advice!

**Comment by quorth0n** [comment]
@DavidBrear while not related to this ticket, from what I can tell you will likely run into performance issues for any queries beginning with a wildcard, see: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-regexp-query.html and https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-wildcard-query.html

>Note: The performance of a regexp query heavily depends on the regular expression chosen. Matching everything like .* is very slow as well as using lookaround regular expressions. If possible, you should try to use a long prefix before your regular expression starts. Wildcard matchers like .*?+ will mostly lower performance.

>In order to prevent extremely slow wildcard queries, a wildcard term should not start with one of the wildcards * or ?. The wildcard query maps to Lucene WildcardQuery.
