### ISSUE TITLE
'IdentityPoolId' not found in stack

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#4027]
I've 2 backend environments, dev and prod that maps to git branches dev and master.
For a while I've been working on my dev branch/environment, I added a couple cognito triggers, nothing too fancy and when I merge to master and push to prod environment I get this error:

UPDATE_FAILED UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Tue Apr 21 2020 14:29:55 GMT-0400 (Eastern
 Daylight Time) Output 'IdentityPoolId' not found in stack 'arn:aws:cloudformation:us-east-1:155161765563:stack/
portal-20190528145021-authcognitoPortal-1HZS1G5013XMR/9e18cf10-817a-11e9-9e50-0a82639e0346'

I DO have (always have had it) an Identity pool. I'm not sure how could I troubleshoot this. Any help would be appreciated.

Thanks.

**Comment by akshbhu** [comment]
Hi @damianrr 

Can you tell me the steps so that I can reproduce this and also the amplify version you are working on?

**Comment by damianrr** [comment]
Hello @akshbhu, 

My amplify-cli version is 4.13.4. As for steps, the only thing that I did was adding a Pre Authentication and a Post Confirmation Cognito hooks. Both set to custom modules. Let me know if you need more details.

Thanks.

**Comment by akshbhu** [comment]
I think we have the fix for this in the version 4.17.2.Please upgrade to latest version and try again.

Let me know if you still facing any issue after that.

**Comment by damianrr** [comment]
That solved it. Thanks!
