### ISSUE TITLE
api best practices

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#4031]
First of all, kudos for the amplify-cli team. It has been a really nice experience getting my project immediately up to speed with the auto-generated schema, resolvers and resources. I typically write a schema with model, key and connection directives, compile and push it to the cloud, and then I write some custom pipeline resolvers in the AppSync console and make minor changes to the remote schema if necessary. Everything goes fine, until the moment that I want to make big changes that force me to modify my original local schema (for example, adding some additional type and some additional directives) and run the amplify push command. In 50% of the cases, it returns an error, which I cannot resolve unless I reinstall the whole api. I know you guys are working on a pull command that "decompiles" the schema which would probably solve my problem, but in the meantime, is there a way to avoid the hassle of having to completely remove my api and the associated resources and to rewrite the functions for my pipeline resolvers? Currently, I am literally copy-pasting all these functions. A solution for this would save me a huge amount of time (and irritation).

**Comment by SwaySway** [comment]
Hello @avlonder 
Currently CLI does not support pipeline resolvers out of the box. Though this is something we as a team are looking into. The RFC below has a few workarounds mentioned as well. Please follow that thread for updates related to pipeline resolvers.

RFC here: https://github.com/aws-amplify/amplify-cli/issues/1055
