### ISSUE TITLE
Auth CustomMessage Lambda not building correctly

### ISSUE THREAD

**Issue by magjack** [aws-amplify/amplify-cli#4032]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify CLI is not building the Custom message/ Verification link lambda function that comes standard when you set up verification link with amplify auth. It is only including the verification-link.js and excluding the index.js file that is required to make the function work. 

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
v4.18.0

**To Reproduce**
Using `amplify add auth`. follow the path to add email verification with redirect link 
![image](https://user-images.githubusercontent.com/40371034/79970571-02c4e480-848b-11ea-8677-5205ac0962b7.png)

Then you get default source tree: 
![image](https://user-images.githubusercontent.com/40371034/79970851-74049780-848b-11ea-8e25-4065f79440aa.png)

Then run `Amplify function build `. the created package only include verification-link.js

![image](https://user-images.githubusercontent.com/40371034/79971061-bcbc5080-848b-11ea-8022-aca048b7cec1.png)

**Expected behavior**
The created package should include index.js as the entry point for Lambda otherwise it fails to execute when invoked. Alternative would be to change the cloud watch template to target verification-link.js instead of index.js

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version v12.16.0

**Comment by nikhname** [comment]
@magjack This should be fixed with the latest release. Do you still see this when using v4.18.1?

**Comment by nikhname** [comment]
Please comment if this issue persists with the latest version of the cli.
