### ISSUE TITLE
Stuck at "GraphQL schema compiled successfully." after generating GraphQL code

### ISSUE THREAD

**Issue by twistapp** [aws-amplify/amplify-cli#4035]
**Describe the bug**
I've used the CLI to connect to my Aurora MySQL and generate the GraphQL annotations, and now I'm trying to push my changes with `amplify push`, but the CLI seems to be stuck at:

```
GraphQL schema compiled successfully.
```

**To Reproduce**

1. Generate GraphQL annotations with `amplify api add-graphql-datasource`
2. Publish it with `amplify push` or `amplify publish

**Expected behavior**

From what I understood based on the docs, I should see in the AppSync dashboard a new API, which never happens.

**Comment by akshbhu** [comment]
Hi @twistapp 

Ca you tell me the amplify version you are currently working on? 
Also , Is it showing any error or is it stuck after ```amplify push``` command?

**Comment by twistapp** [comment]
Hey @akshbhu, after rebooting it started working again, not sure what happened. The version of amplify that I'm using (CLI) is 4.18.0, and there were no errors.

**Comment by akshbhu** [comment]
Hi @twistapp 

Glad to know that it worked. For now I am closing this issue , If you are still stuck , feel free to comment on this and I will reopen this issue again
