### ISSUE TITLE
trigger-dynamodb.js is missing when creating a Lambda DynamoDB trigger

### ISSUE THREAD

**Issue by jon144** [aws-amplify/amplify-cli#4037]
**Describe the bug**
When creating a Lambda function and using it as a DynamoDB trigger the cli reports that
trigger-dynamodb.js is missing.

Error message:
(node:20840) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-dotnet-function-template-provider\resources\lambda\Trigger\trigger-dynamodb.js'

trigger-dynamodb.js is not found at: 
https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-dotnet-function-template-provider/resources/lambda/Trigger

**Amplify CLI Version**
4.18.0

**To Reproduce**
PS C:\source\repos\demo1> amplify add function
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: functionA
? Provide the AWS Lambda function name: functionA
? Choose the function runtime that you want to use: **.NET Core 3.1**
? Choose the function template that you want to use: Trigger (DynamoDb, Kinesis)
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream
? Choose a DynamoDB event source option Use storage category DynamoDB table configured in the current Amplify project
? Choose from one of the already configured DynamoDB tables tableA
? Do you want to access other resources created in this project from your Lambda function? No
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
 (node:20840) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-dotnet-function-template-provider\resources\lambda\Trigger\trigger-dynamodb.js'
    at Object.statSync (fs.js:933:3)
    at Object.statSync (C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.isFile (C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\context-extensions.js:136:43)
    at Object.generate (C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\context-extensions.js:278:36)
    at AmplifyToolkit.copyBatch [as _copyBatch] (C:\Users\XXX\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\copy-batch.js:17:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Expected behavior**
Create a .cs file with a template for the trigger.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v12.16.2

**Additional context**
Maybe it should be looking for DynamoDB.cs.ejs instead of trigger-dynamodb.js?

**Comment by akshbhu** [comment]
Hi @jon144 

Thanks for reporting the bug. We will pick this issue in the upcoming sprint.

**Comment by andyhopp** [comment]
Hello! The code change that resolves this issue will be in the next release, but in the meantime you can clone/build a local copy of amplify CLI that can run side-by-side with the regular release. (see: https://github.com/aws-amplify/amplify-cli#contributing on how to build/use amplify-dev)

**Comment by edwardfoyle** [comment]
The fix for this has been released in Amplify v 4.18.1
