### ISSUE TITLE
amplify function update re-applies existing permissions to cloudformation template

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#4051]
**Describe the bug**
When calling `amplify function update` and adding permissions to your lambda function, the CLI takes all the existing permissions, re-applies them to the cloudformation template and then adds the new permission.

After calling `amplify function update` multiple times the template becomes too big and we cannot push it to the cloud.

**Amplify CLI Version**
4.18.0

**To Reproduce**
`amplify add function` - create a lambda function and give it permissions for something.
`amplify push` - push the function.
`amplify function update` - update the function and add another permission to something else, 
then look at the cloudformation template for that function and you can see that the permission that you enabled in the creation of the lambda function now exists twice in the template.

**Expected behavior**
Adding permissions to lambda functions will only add the newly selected permissions and keep all the old ones. Or remove all permissions from the template and re-apply them all, no duplicates.

**Comment by akshbhu** [comment]
Hi @idanlo 

Can you elaborate the steps what permissions you added and if possible to share the part of CFN template where the duplication happened. 
You can also mail the zip folder to amplify-cli@amazon.com.

**Comment by idanlo** [comment]
@akshbhu I cannot share my template with you currently unfortunately. AFAIK this is almost the same issue as #3930 but it affects the CFN template and not the schema. 
This happens every time you add a permission to a function, and then add another (different) permission

**Comment by edwardfoyle** [comment]
@idanlo This should be fixed in the latest version of the CLI (4.19.0)
