### ISSUE TITLE
amplify status shows Update when changing env? 

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-cli#4056]
**Describe the bug**
I have two amplify enviroments: `dev` and `prod`.
If my current env is `prod`, when I do `amplify env checkout dev` followed by `amplify status`. I would see all my functions show `Update` though nothing is being changed. Why is this? I would expect to see `No Change`. My current workaround is to do `amplify env pull --restore` every time after I do `amplify env checkout xxx` to make sure I didn't modify anything.

**Amplify CLI Version**
4.16.1

**To Reproduce**
Create an amplify env `dev` and `auth` with admin query function enabled, push to cloud. 
Duplicate `dev` to be `prod` and push `prod` to cloud. 
Change from `prod` to `dev` and do `amplify status`, observe admin query status to be `Update`. 

**Desktop (please complete the following information):**
Windows

**Comment by kaustavghosh06** [comment]
Please take a look at a similar issue out here - https://github.com/aws-amplify/amplify-cli/issues/1850#issuecomment-592435957

These values changing should not prevent pushing resources, and changes to these lines can be safely ignored. When pushing a resource, these templates get updated with correct s3 bucket keys. If you want to keep git history clean, your team could decide not to commit changes these lines, but any changes should not have a negative effect.Having said that, we're looking into ways and tracking as to how we can avoid this altogether.
cc @UnleashedMind
