### ISSUE TITLE
TypeError: Cannot read property 'output' of undefined at transformGraphQLSchema

### ISSUE THREAD

**Issue by bakeano** [aws-amplify/amplify-cli#4058]
**Describe the bug**
Trying to use an option on amplify cli, during API UPDATE, i got an error: ```TypeError: Cannot read property 'output' of undefined at transformGraphQLSchema```

**Amplify CLI Version**
4.18.0

**To Reproduce**
1. amplify api udate
2. Select GraphQL service
3. Select option: Enable DataStore for entire API

**Expected behavior**
Dont know the exact expected behavior (personal speculations below)
1. Maybe create the section "dataStore" inside the file `amplifyconfiguration.json` that already exists.
2. Maybe create the file `amplifyconfiguration.json` if it does not exists, and add  the "dataStore" section.

**Screenshots**
![DataStoreError](https://user-images.githubusercontent.com/11425603/80182973-fd27e580-85d5-11ea-9b6d-82f5fbb8b379.png)

**Desktop (please complete the following information):**
 - OS: Debian 9.12
 - Node Version: v10.20.1

**Additional context**
Using Android Studio 3.6.2
And getting this error, and issue reported on the Amplify android project: [com.amplifyframework.AmplifyException: Unknown/bad category type: dataStore #384](https://github.com/aws-amplify/amplify-android/issues/384)

my actual **amplifyconfiguration.json**
```
{
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://$endpointID$.appsync-api.$region$.amazonaws.com/graphql",
                    "region": "$region$",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }
}
```
my graphQL schema
```
type PhotoReport @model
  @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  name: String!
  uploadButtonText: String!
  definition: AWSJSON!
  job: AWSJSON!
  templateId: Int!
  status: AWSJSON!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  deletedAt: AWSDateTime
  photoReportObjects: [PhotoReportObject] @connection
}

type PhotoReportObject @model
  @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  type: String!
  name: String!
  precedence: Int!
  photoReportID: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  deletedAt: AWSDateTime
  photoGroups: [PhotoGroup] @connection
}

type PhotoGroup @model
@auth(rules: [{allow: private, provider: iam}]) {
    id: ID!
    name: String!
    precedence: Int!
    photoReportObjectID: ID!
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    deletedAt: AWSDateTime
    photos: [Photo] @connection
}

type Photo @model
@auth(rules: [{allow: private, provider: iam}]) {
    id: ID!
    name: String!
    pictureURI: String!
    photoGroupID: ID!
    userId: Int!
    statusName: String!
    details: AWSJSON
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    deletedAt: AWSDateTime
}
```

**Comment by SwaySway** [comment]
Hello @bakeano before going into through the question workflow for `Enable DataStore for API` did you already have DataStore enabled?

**Comment by bakeano** [comment]
Hi @SwaySway,

I will try to list the exact steps i make:

1. create a new android project
2. install amplify cli
3. `amplify init`
4. `amplify configure`

After step 4 amplify is installed on the android project and the amplify directory is generated, the only category set up is API (i did not add it, that category is included on installation), **i am not sure if dataStore is included on API at this point**:

5. `amplify push`
6. i create an Application Class on android and try to initialize AWSMobileClient
7. when the API Plugin is added all work fine
8. include all dependencies as documentation, and when the DataStore plugin is added on initialization, that result on an error reported on this issue - [com.amplifyframework.AmplifyException: Unknown/bad category type: dataStore #384](https://github.com/aws-amplify/amplify-android/issues/384)

After step 8 trying to resolve that issue and adding a new auth method to the API i see the option describe above `Enable DataStore for Entire API` on amplify cli

9. i add a new auth method to the API and hit the option `Enable DataStore for Entire API`, no errors here
10. `amplify push`
12. i try to run the android app and i see that the issue described on step 8, adding the datastore plugin is still present
13. i try hitting **again** on amplify cli `Enable DataStore for Entire API`, from this moment on the issue reported here arise

At this point the file `amplifyconfiguration.json` does not have a dataStore section.

Thanks !!

**Comment by bakeano** [comment]
Hi all,

Amplify cli is updated to 4.18.1, same issues still persist.

thanks!

**Comment by SwaySway** [comment]
@bakeano 
Based on the response on this thread the CLI does not generate any inputs within `amplifyconfiguration.json`. It seems this will be addressed in the next release.
https://github.com/aws-amplify/amplify-android/issues/384#issuecomment-628278528

Regarding the error you ran into 

> i got an error: TypeError: Cannot read property 'output' of undefined at transformGraphQLSchema

I was able to reproduce this and I'm marking this as a bug. Should you need to reconfigure your datastore settings a current workaround would be to select `Walkthrough all configurations`.

**Comment by gHashTag** [comment]
Why is this error occurring?
```amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Enable DataStore for entire API
Cannot read property 'output' of undefined
TypeError: Cannot read property 'output' of undefined
    at transformGraphQLSchema (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:397:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at updateWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-walkthrough.js:469:3)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:176:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:158:7)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:24:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:47:5)```

**Comment by gHashTag** [comment]
In order to solve this I had to do it again: walkthrough all configurations

**Comment by bakeano** [comment]
@SwaySway thanks for your reply, and solution proposed!
