### ISSUE TITLE
Function's "read" access to GQL API doesn't work

### ISSUE THREAD

**Issue by adeelnawaz** [aws-amplify/amplify-cli#4061]
**Describe the bug**
When a function is allowed only "read" operation on a GQL API, and the function's source tries to run a Get query via AppSync GraphQL client using IAM credentials, then it constantly gets response code 401. Adding any other operation along with "read" fixes this issue.

**Amplify CLI Version**
4.18.0

**To Reproduce**
- Create a GraphQL API via `amplify api add`
- Create a function via `amplify function add`
- Select category "api" to be accessible via this new lambda function
- Select only "read" as permissible operation
- Run GraphQL API query from lambda function using AppSync GraphQL client

**Expected behavior**
The Get query should execute successfully.

**Desktop:**
 - OS: Linux Mint 19.01
 - Node Version: v13.12.0

**Additional context**
When only "read" operation is permitted, then the `AmplifyResourcesPolicy.Properties.PolicyDocument.Statement[0]` from cloudformation template looks like this:
```
{
	"Effect": "Allow",
	"Action": [
		"appsync:Get*",
		"appsync:List*"
	],
	...
}
```
this results in a 401 response. If I add `appsync:GraphQL` to allowed actions, then this problem is solved. Adding another operation along with "read" (e.g. "create", "update") also adds this action to the policy statement, which solves the problem. Perhaps the cloudformation template generation is missing `appsync:GraphQL` while it's necessary for AppSync client to work properly.

Sample lambda code:
```js
const AWS = require('aws-sdk');
const appsync = require('aws-appsync');
const async = require('async');
const gql = require('graphql-tag');
require('cross-fetch/polyfill');

const region = process.env.REGION
const apiSkylightGraphQLAPIEndpointOutput = process.env.API_SKYLIGHT_GRAPHQLAPIENDPOINTOUTPUT

AWS.config.update({
  region: region
});

const credentials = AWS.config.credentials;

exports.handler = async (event) => {

  console.log('event received:' + JSON.stringify(event));

  //create appsync client - using IAM permissions
  const graphqlClient = new appsync.AWSAppSyncClient({
    url: apiSkylightGraphQLAPIEndpointOutput,
    region: region,
    auth: {
      type: 'AWS_IAM',
      credentials: credentials
    },
    disableOffline: true
  });

  const getLight = gql`query GetLight($id: ID!) {
      getLight(id: $id) {
          id
          name
          owner
      }
  }`;

  //execute the query
  try {
    console.log('executing getLight query');

    //execute the get query to see if the light exists
    const light = await graphqlClient.query({
      query: getLight,
      variables: {
        id: event.arguments.input.id
      }
    });

    return {
      statusCode: 200,
      body: JSON.stringify({message: 'Success'})
    };
  } catch (err) {
    return {
      statusCode: 400,
      body: JSON.stringify({message: err.message})
    };
  }
};
```

Error:
```
{
    "errorType": "Error",
    "errorMessage": "Network error: Response not successful: Received status code 401",
    "graphQLErrors": [],
    "networkError": {
        "errorType": "Error",
        "errorMessage": "Response not successful: Received status code 401",
        "response": {
            "size": 0,
            "timeout": 0
        },
        "statusCode": 401,
        "result": {
            "errors": [
                {
                    "errorType": "UnauthorizedException",
                    "message": "Permission denied"
                }
            ]
        },
        "stack": [
            "Error: Response not successful: Received status code 401",
            "    at throwServerError (/var/task/node_modules/apollo-link-http/lib/bundle.umd.js:35:17)",
            "    at /var/task/node_modules/apollo-link-http/lib/bundle.umd.js:58:13",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        ]
    },
    "message": "Network error: Response not successful: Received status code 401",
    "stack": [
        "Error: Network error: Response not successful: Received status code 401",
        "    at new ApolloError (/var/task/node_modules/apollo-client/bundle.umd.js:85:32)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1039:45",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1411:21",
        "    at Array.forEach (<anonymous>)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1410:22",
        "    at Map.forEach (<anonymous>)",
        "    at QueryManager.broadcastQueries (/var/task/node_modules/apollo-client/bundle.umd.js:1405:26)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:988:35",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by SwaySway** [comment]
Hello @adeelnawaz we do have docs here on how to access your GraphQL API from lambda.
Docs: https://docs.amplify.aws/cli/function#graphql-from-lambda
Should you have any issues with this set up please comment below.

**Comment by kaustavghosh06** [comment]
@adeelnawaz You'll have to give "create" access as well along with "read" to execute the GraphQL operations from the Lambda function. Please let us know if after adding "create" permissions as well you're not able to execute the GraphQL operations.

**Comment by alxistn** [comment]
Up ! I have the exact same error

**Comment by alxistn** [comment]
Any news here ? I'm still having the issue

**Comment by vadimmelnicuk** [comment]
I get 401 error using a similar approach. Have you found a solution?

**Comment by alxistn** [comment]
Nope, and I am going to switch to firebase in the near future because this github and its 800+ issues are tiresome, gl though

**Comment by vadimmelnicuk** [comment]
> Nope, and I am going to switch to firebase in the near future because this github and its 800+ issues are tiresome, gl though

Ah, I agree, It is sometimes hard to find a straight answer to some niche questions regarding AWS. Btw, it seems like I found an approach that works. You should try adding an AppSync Policy for your Lambda IAM Role i.e., AWSAppSyncInvokeFullAccess. Also, make sure you allowed 'iam' public or private queries in your schema for your Light type definition.
