### ISSUE TITLE
MINOR... but changing maxDepth in graphqlconfig.yaml  doesn't trigger an update signal to amplify push

### ISSUE THREAD

**Issue by jsgphd** [aws-amplify/amplify-cli#4067]
**Describe the bug**
MINOR, but still worth fixing... When changing the depth using aws config codegen it does not generate a dirty state to know to push the graphql api.

The work around is to just add a space into your schema.graphql to trigger an update to make the amplify push succeed.

**To Reproduce**
do an amplify push to make sure nothing is pending.
Change the depth using aws config codegen to something different.
do a amplify push and it will say no changes.

**Expected behavior**
The amplify push should say that API of graphql needs to be updated.

**What is Configured?**
my graphqlconfig.yaml went from not having a entry for maxDepth to now having maxDepth: 8

**Comment by ammarkarachi** [comment]
@jsgphd Thanks for opening this issue, you could always use `amplify push --force` to push undetected changes

**Comment by RossWilliams** [comment]
This is not a bug, there are no API changes needed when depth is changed. This only changes the codegen queries. You can always queries to arbitrary depths regardless of the depth property set for codegen purposes
