### ISSUE TITLE
S3 naming convention not same between environments. Can't push due to capitals

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#4074]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
in an environment I created a Storage resource called AppStorage with bucketname app-storage. Everything went fine. I am now on my production branch and trying to do the same but I get an error when pushing "Bucket name should not contain uppercase characters"

For some reason it's factoring in the Resource name when trying to create the s3 bucket. If i change the resource name to lower case it will succeed but then I end up with a weird bucketname like storageAppStoragestorageapp-storage or something (I can't remember), instead of the app-storage-****-env that i got on my other branch.
**Amplify CLI Version**
4.18.0

**To Reproduce**
I'm not sure.

**Expected behavior**
I would expect the resource creation in one branch to work in the other the same way.

**Screenshots**

**Desktop (please complete the following information):**
Mac - Node -v12.16.1

**Additional context**

**Comment by akshbhu** [comment]
Hi @julien-tamade 

Can you share the ```team-provider-info.json``` file and ```amplify-meta.json``` file for both environments to easily debug the issue.

**Comment by julien-tamade** [comment]
@akshbhu is there a non-public way I can share these?

**Comment by ammarkarachi** [comment]
@julien-tamade you can email us amplify-cli@amazon.com

**Comment by ammarkarachi** [comment]
@julien-tamade I am closing this issue, Let us know if you need more help with this.
