### ISSUE TITLE
One-to-many relationship - Failed compiling GraphQL schema

### ISSUE THREAD

**Issue by atgillette** [aws-amplify/amplify-cli#4075]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Running `amplify add api` and selecting `One-to-many relationship` from `What best describes your project` throws an error:

`Failed compiling GraphQL schema:
id field is not of type String
? Correct the errors in schema.graphql and press Enter to re-compile.`

  

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.18.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

`? Please select from one of the below mentioned services: GraphQL`
`? Provide API name: myapi`
`? Choose the default authorization type for the API API key`
`? Enter a description for the API key: demo`
`? After how many days from now the API key should expire (1-365): 7`
`? Do you want to configure advanced settings for the GraphQL API No, I am done.`
`? Do you have an annotated GraphQL schema? No`
`? Do you want a guided schema creation? Yes`
`? What best describes your project: One-to-many relationship (e.g., “Blogs” with “Posts” and “Comments”)`
`? Do you want to edit the schema now? Yes`

**Expected behavior**

No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by akshbhu** [comment]
Hi @atgillette 

We have already made the change for this issue in this PR:https://github.com/aws-amplify/amplify-cli/pull/4070.

For the workaround you can use the following code 
```graphql
type Post @model @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}
```
You can the ```BlogID``` from ```String!``` to ```ID!``` as explained in above code.

Let me know if are still stuck on this issue.

**Comment by atgillette** [comment]
Thx @akshbhu.
