### ISSUE TITLE
Function Triggers are not exporting index.handler

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#4077]
**Describe the bug**
Given a scenario where a developer wants to create either a whitelist or blacklist via a presignup lambda in the auth flow, the application with cause on on an attempted signup because there is no `index.handler` file. instead theres a file structure as such:

-function
  - functionName
    - src
      - email-filter-whitelist.js

Upon attempting to sign in, the application errors out because there is no` index.handler`, instead, there is only a `email-filter-whitelist.js` file.

**Amplify CLI Version**
`4.18.0`

**To Reproduce**
```sh
amplify add auth
```
* Select the default flow
* In auth flow, add lambda trigger
* add whitelist function
* Add a whitelisted domain
* Have React app setup with auth components
* Attempt to sign in

**Expected behavior**
The index.handler file should either be present, or the cloud resources should be updated to  look for the required handle file

**Screenshots**

![image](https://user-images.githubusercontent.com/5106417/80296147-28c5df80-873e-11ea-91ff-a8c6460c239d.png)

Above is my solution, however I believe it would be best if this came by default.

Upon trying to create a PR, I was unsure on where to add this. I'd love to take this on as a contribution 🤩 

I looked in the following folder structure, but was unsure since the whitelist and blacklist are in the same directory.

![image](https://user-images.githubusercontent.com/5106417/80296198-84906880-873e-11ea-91b3-f584a1ed1b41.png)

**Comment by mtliendo** [comment]
Actual error message is captured at this point on my stream: https://youtu.be/X8YNggWylws?t=1905

**Comment by akshbhu** [comment]
Hi @mtliendo 

Can you update to the latest version i.e. 4.18.1 and check if that is working?
Let know if you are still facing this issue?

**Comment by mtliendo** [comment]
Looks like I was a day late, dollar short 😅 

Updating fixed it!
