### ISSUE TITLE
AppSync and Stripe connection issues

### ISSUE THREAD

**Issue by bastiancleverfit** [aws-amplify/amplify-cli#4078]
**Describe the bug**
I'm calling Stripe through a function called as an AppSync resolver (Amplify @function directive) and i'm experiencing connection issues, Stripe services randomly respond me with: "An error occurred with our connection to Stripe."
Before calling the function with a resolver i was using it through an endpoint from a REST API (API Gateway generated with Amplify CLI too) and this error never showed up.
I'm wondering if AppSync closes the connection with external calls too quickly, so it leads to timeouts.
It happens with all types of Stripe calls so it's not bounded to a specific API.

**Amplify CLI Version**
4.18.1

**To Reproduce**
Make a random call to stripe (API version: 2020-03-02; NPM package version: ^8.47.0) from a Lambda Resolver (NodeJS).

**Expected behavior**
Return the correct responses from Stripe API.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.15.0

**Comment by ammarkarachi** [comment]
@bastiancleverfit Is the error originating from the Stripe Service?

**Comment by bastiancleverfit** [comment]
@ammarkarachi Yes Stripe is giving me this error randomly.
But i have a version of my API where i'm making the calls from an API Gateway and this is never happening.

**Comment by bastiancleverfit** [comment]
I have some news from Stripe Support, they checked for errors in system and from their end there is nothing, they said that probably the cause of the problem is in my infrastructure.
Since this is an issue that could potentially affect everybody using AppSync + External Services and i'm in the AWS Basic Support Tier (I'm not even in production), i hope that this helps you proceeding with further investigations with this problem that breaks the billing process of my app.

**Comment by ammarkarachi** [comment]
@bastiancleverfit Can you provide us with the Lambda function? Based on my current understanding the problem lies in the Lambda function not in the functionality of the Amplify CLI.

**Comment by bastiancleverfit** [comment]
@ammarkarachi yes in fact I didn't mentioned nothing about the CLI but probably a connection problem in AWS AppSync, anyway this is the code of my Lambda:

`require('dotenv').config();
var stripe = require("stripe")(process.env.STRIPE_SECRET, {
    apiVersion: '2020-03-02'
});

exports.handler = async (event) => {
    const customerId = event.identity.claims["custom:customer"] || null;

    if(!customerId) {
        return {
            fullName: "",
            companyName: "",
            pecAddress: "",
            streetAddress: "",
            city: "",
            zip: "",
            country: "",
            state: "",
            taxCode: "",
            taxType: "",
            phoneNumber: ""
        };
    }

    try {
        const customer = await stripe.customers.retrieve(customerId);
        return {
            fullName: customer.name,
            companyName: customer.description,
            pecAddress: customer.metadata.pecAddress.length
                ? customer.metadata.pecAddress
                : "",
            streetAddress: customer.address.line1,
            city: customer.address.city,
            zip: customer.address["postal_code"],
            country: customer.address.country,
            state: customer.address.state,
            taxCode: customer["tax_ids"].data[0]["value"],
            taxType: customer["tax_ids"].data[0]["type"],
            phoneNumber: customer.phone
        };
    } catch (error) {
        switch (error.type) {
            case 'StripeConnectionError':
                throw new Error("connection-error");
                break;
            default:
                throw new Error(error);
                break;
        }
    }
};`

**Comment by kaustavghosh06** [comment]
@bastiancleverfit AppSync resolver has a timeout of 30 seconds. Does your request take more than 30 seconds?

**Comment by bastiancleverfit** [comment]
@kaustavghosh06 no it usually takes less than 100ms even when the error happens.

**Comment by ammarkarachi** [comment]
@bastiancleverfit I am uncertain but this seems to be an issue an AppSync side,  you could check the execution time on the cloudwatch logs. You can follow up with AppSync [here](https://github.com/aws/aws-appsync-community)
