### ISSUE TITLE
federated identities not included in aws-exports.js

### ISSUE THREAD

**Issue by adrianhall** [aws-amplify/amplify-cli#408]
**Describe the bug**
When you set up third party federated identities in JavaScript/React, the docs say you need a "federated" object like this:

```
const federated = {
    google_client_id: '',
    facebook_app_id: '',
    amazon_client_id: ''
};

return (
    <Authenticator federated={federated}>
)
```

However, the Amplify CLI does not produce such an object in the aws-exports.js file.

**To Reproduce**
1. Run `amplify init`
2. Run `amplify add auth`
3. Add google, amazon, or facebook identity support
4. Run `amplify push`
5. Check the aws-exports.js file - no app IDs are stored.

**Expected behavior**
I'd expect the aws-exports.js file to include the federated application IDs.  As a best case, I'd expect a "federated" object within the awsmobile export, e.g.

```
const awsmobile = {
  // other settings...
  federated: {
    "google_client_id": "some-id",
    "facebook_app_id": "some-id",
    "amazon_client_id": "some-id"
  },
 // rest of the settings
};
```

This format will allow you to easily do use this:

```
import awsmobile from './aws-exports';

return (
    <Authenticator federated={awsmobile.federated}>
)
```

instead of what is in the Amplify docs suggest now.

**Comment by kaustavghosh06** [comment]
The Amplify libraries recommend using Hosted UI for authentication and social federation and the the CLI outputs oAuth configurations necessary for the authenticator and client libraries to function correctly. Closing this issue.
