### ISSUE TITLE
How do I remove DataStore from my amplify project?

### ISSUE THREAD

**Issue by raelmiu** [aws-amplify/amplify-cli#4082]
This is a general usage question:
I have a project set up that uses DataStore. But due to https://github.com/aws-amplify/amplify-js/issues/5119 I cannot use DataStore. 

It looks like the schema is very different from projects without DataStore set up, so my question is:  How does one remove datastore to use amplify without it again?

**Comment by ammarkarachi** [comment]
@raelmiu You would have to delete the ResolverConfig from the transformer.conf.json

**Comment by raelmiu** [comment]
@ammarkarachi and then? When I did the modelgen function is updating the API.ts file again. But all the extra data fields etc are still there.

**Comment by ammarkarachi** [comment]
@raelmiu Can you delete them and invoke `amplify push`

**Comment by raelmiu** [comment]
I seem to have a lot of boilerplate still in the code, but everything does work. Thank you @ammarkarachi

**Comment by Basovs** [comment]
> This is a general usage question:
> I have a project set up that uses DataStore. But due to [aws-amplify/amplify-js#5119](https://github.com/aws-amplify/amplify-js/issues/5119) I cannot use DataStore.
> 
> It looks like the schema is very different from projects without DataStore set up, so my question is: How does one remove datastore to use amplify without it again?

Hi!

1.) type in terminal - 'amplify update api'
2.) choose - 'GrapQl'
3.) choose - 'Disable DataStore fro entire API'

DONE - have a nice day!

**Comment by nipoonp** [comment]
> > This is a general usage question:
> > I have a project set up that uses DataStore. But due to [aws-amplify/amplify-js#5119](https://github.com/aws-amplify/amplify-js/issues/5119) I cannot use DataStore.
> > It looks like the schema is very different from projects without DataStore set up, so my question is: How does one remove datastore to use amplify without it again?
> 
> Hi!
> 
> 1.) type in terminal - 'amplify update api'
> 2.) choose - 'GrapQl'
> 3.) choose - 'Disable DataStore fro entire API'
> 
> DONE - have a nice day!

nice one mate

**Comment by AyazAI** [comment]
Can I disable Data modeling? I have enabled data modeling which designing schema!
