### ISSUE TITLE
Error accessing api reference from lambda function mock

### ISSUE THREAD

**Issue by bit-piotr** [aws-amplify/amplify-cli#4085]
**Describe the bug**
After creating a sample project, and adding a function configured to access the model storage, the amplify mock function command returns errors about accessing the referenced API:

Fn::ImportValue could not find ${apitestGraphQLAPIIdOutput}:GetAtt:TodoTable:Name in exports. Using unsubstituted value.
Fn::ImportValue could not find ${apitestGraphQLAPIIdOutput}:GetAtt:TodoTable:Name in exports. Using unsubstituted value.
Could not find ref for "apitestGraphQLAPIIdOutput". Using unsubstituted value.

**Amplify CLI Version**
4.18.1

**To Reproduce**
amplify init

amplify add api
```
? Please select from one of the below mentioned services: GraphQL
? Provide API name: test
? Choose the default authorization type for the API API key
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): 7
? Do you want to configure advanced settings for the GraphQL API No, I am done.
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? Yes
? What best describes your project: Single object with fields (e.g., “Todo” with
 ID, name, description)
? Do you want to edit the schema now? No
```
amplify add function
```
Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this categ
ory in the project: testfa1a9b6d
? Provide the AWS Lambda function name: testfa1a9b6d
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World
? Do you want to access other resources created in this project from your Lambda
 function? Yes
? Select the category api
Api category has a resource called test
? Select the operations you want to permit for test create, read, update

You can access the following resource attributes as environment variables from your Lambda function
        API_TEST_GRAPHQLAPIENDPOINTOUTPUT
        API_TEST_GRAPHQLAPIIDOUTPUT
	ENV
	REGION
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
Successfully added resource testfa1a9b6d locally.
```

Mock run the function:

 ```
amplify mock function testfa1a9b6d
? Provide the path to the event JSON object relative to /home/piotr/workspace/te
st/amplify/backend/function/testfa1a9b6d src/event.json
Fn::ImportValue could not find ${apitestGraphQLAPIIdOutput}:GetAtt:TodoTable:Name in exports. Using unsubstituted value.
Fn::ImportValue could not find ${apitestGraphQLAPIIdOutput}:GetAtt:TodoTable:Name in exports. Using unsubstituted value.
Could not find ref for "apitestGraphQLAPIIdOutput". Using unsubstituted value.
Starting execution...
Result:
{"statusCode":200,"body":"\"Hello from Lambda!\""}

```

**Expected behavior**
Function having access to env variables with names of Dynamodb table

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version.
v12.16.2

**Comment by edeuxk** [comment]
Same error

**Comment by glauberfc** [comment]
Same error

**Comment by bit-piotr** [comment]
Actually, similar issue occurs for me after deployment:

Embedded stack arn:aws:cloudformation:eu-central-1:*:stack/amplify-*-113055-functioncron-19P88OJ5F07BV/58b38860-8ac6-11ea-b067-0ac41be8cd2e was not successfully created: No export named *GraphQLAPIIdOutput:GetAtt:EventTable:Name found
--

**Comment by ammarkarachi** [comment]
@bit-piotr I tried reproducing the error and I can see the API_TEST_GRAPHQLAPIENDPOINTOUTPUT & API_TEST_GRAPHQLAPIIDOUTPUT being populated after invoking an `amplify push` if you disregard the error.

**Comment by bit-piotr** [comment]
Hi @ammarkarachi, thanks for reaching out.

The problem is that I cannot even push this stack to the cloud, as it encounters an error and does a rollback which deletes the function/functions

Please let me know if I can provide any more details that could be helpful in pinpointing/resolving this issue?

[amplify-push-output.txt](https://github.com/aws-amplify/amplify-cli/files/4573252/amplify-push-output.txt)

**Comment by ammarkarachi** [comment]
@bit-piotr Can you push just the api and by invoking `amplify push api` and see if the outputs in cloudformation have the outputs it's trying to find?

**Comment by ammarkarachi** [comment]
@bit-piotr After some digging I was able to reproduce the issue, You would need to access grant access to API also along with granting access to the GraphQL DynamoDb table. Also as of now we are not supporting the AppSync @model table in mock.

**Comment by BennettSmith** [comment]
Could you please elaborate on the highlighted portion of your earlier statement.  I am interested in building a set of integration tests that exercise my GraphQL API and Lambda functions using `amplify mock`.  I was under the impression we could use mock with a GraphQL schema that uses `@model` and `@auth`.  Is that not true?

> @bit-piotr After some digging I was able to reproduce the issue, You would need to access grant access to API also along with granting access to the GraphQL DynamoDb table. **Also as of now we are not supporting the AppSync @model table in mock**.
