### ISSUE TITLE
What is the default hosting for an app?

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#4086]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.18.0

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
When creating a new amplify app, prior to ever running `amplify add hosting`, how is my app hosted? In Route53, I see DNS records pointing to CloudFront, but I don't see a distribution in the CloudFront console.

**Comment by UnleashedMind** [comment]
As you've probably seen, when you execute `amplify hosting add`, you will be prompted to select either 'Amplify Console` or `CloudFront and S3` to host your web application.
The `Amplify Console` is the newer service provided by Amplify and is the default choice. 
For `Amplify Console`, your app will be served via CloudFront.
For `CloudFront and S3`, if you choose `PROD`, your app will be served via CloudFront. And if you choose `DEV`, it will be served directly in a S3 hosting bucket. 
Here's our [Doc](https://docs.amplify.aws/cli/hosting) for hosting, you can check for more detailed description. 

Did you choose 'Amplify Console` or `CloudFront and S3` when you ran `amplify hosting add`?

**Comment by alexkates** [comment]
Neither. I cancelled the command because I wanted to understand how the app is being hosted even though I haven't configured it yet.

**Comment by alexkates** [comment]
Any more information needed from my end?

**Comment by UnleashedMind** [comment]
If start in a local development, and ran `amplify init` on your project, your project's frontend is not hosted by amplify until you run `amplify hosting add` and then `amplify push`. 
If you start from Amplify Console by click `Connect app` and connect an app in a repo (e.g. GitHub), then you app's frontend is hosted by amplify (through CloudFront). 
Which route did you take?

**Comment by alexkates** [comment]
Ah that makes sense. We connected via the Amplify Console by clicking `connect app`. This explains why I didn't need to run `amplify hosting add`. Any thoughts about why I don't see the a CloudFront distribution in the CloudFront console?

**Comment by kaustavghosh06** [comment]
@alexkates Amplify Console is a fully managed hosting service - it doesn't create a  CloudFront distribution in your AWS account.

**Comment by alexkates** [comment]
Oh very interesting... So If I want to manage my own distribution, I need to re-configure the hosting?

**Comment by kaustavghosh06** [comment]
CLI provides you the option to do so with the `amplify add hosting` capability.

**Comment by alexkates** [comment]
I'm still having issues here. Take a look at my command output...

```
➜  amplify git:(master) amplify add hosting      
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuo
us deployment)
You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.
➜  amplify git:(master) amplify configure hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuo
us deployment)
Amplify Console hosting is not enabled.
```

**Comment by brene** [comment]
@alexkates - can you try running `amplify remove hosting` and then running `amplify add hosting` again?

**Comment by brene** [comment]
That'll essentially decommission your existing hosting solution and allow you to setup hosting from scratch again.

**Comment by alexkates** [comment]
```
➜  amplify git:(master) amplify remove hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
Amplify Console hosting is not enabled.
```

**Comment by brene** [comment]
@alexkates - do you have time to jump on a call? I’m curious on how you got into that state. If you’re up for it DM me on Twitter: twitter.com/renebrandel

**Comment by swaminator** [comment]
@alexkates You have enabled hosting in the Amplify Console and not through the CLI. To remove hosting with Amplify Console, please visit the console and disconnect your frontend branches and then run `amplify add hosting` from the CLI.

**Comment by alexkates** [comment]
@swaminator I think you are right... and that would answer my original question.

**Comment by psudocode** [comment]
> If you start in a local development by running `amplify init` on your project, your project's frontend is not hosted by amplify until you run `amplify hosting add` and then `amplify publish`.
> If you start from Amplify Console by clicking `Connect app` and connect an app in a repo (e.g. GitHub), then you app's frontend is hosted by Amplify Console (through CloudFront) when it finishes the setup.
> Which route did you take?

so when we start by clicking `Connect App`, we don't need `amplify publish`?

**Comment by narumolp** [comment]
>amplify add hosting  // I incorrectly selected manual instead of continuous
>amplify publish
>amplify remove hosting
>amplify add hosting // then I get below message

_Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous
 deployment)?
You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches._

What do I have to do for the 'manage your branches'? Please help!

**Comment by little-bamboo** [comment]
```
amplify add hosting // I incorrectly selected manual instead of continuous
amplify publish
amplify remove hosting
amplify add hosting // then I get below message
```

I'm also dealing with this same error.  After adding manual hosting through the CLI, I wanted to switch to a CI/CD workflow.  After removing hosting, I'm getting the same error:

```
on macbook-pro client on 🌱 master [🗑📝] via ⬢ v12.18.3 on 🅰 (us-west-2) took 46s 
➜  amplify add hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.
```
