### ISSUE TITLE
amplify push failed with `Attempting to create an index which already exists`

### ISSUE THREAD

**Issue by taneba** [aws-amplify/amplify-cli#4094]
**Which Category is your question related to?**
Api (graphql), @key directive usage, amplify push rules

**Amplify CLI Version** 
4.16.1

**What AWS Services are you utilizing?**
API

**Provide additional details e.g. code snippets**
I'm working in a team and rebase my working branch onto develop branch where couple of @keys are modified. I probably took wrong operation (ran push, pull back and forth), but what I end up stacking with this error `Attempting to create an index which already exists`. That index certainly exits when I look DynamoDB table's index tab, so seems like there's a conflict between remote env and local schema.

So I have 2 main questions:

 1. How `Attempting to create an index which already exists` error can happen? I want to know how to update my remote env accurately and what should not to do to avoid this error.
 2. How can I recover from this error? I can't complete `amplify push` whatsoever.

**Comment by taneba** [comment]
I've kind of solved with removing particular index manually on the aws console but no sure if it is an accurate way to resolve the conflicts. 
I'm afraid that It can cause any other problems :(

**Comment by RossWilliams** [comment]
This most likely occurred because you or a team member previously attempted to push an update with multiple GSI operations on a single table (which is not allowed) and the update failed. Cloudformation will not revert these failed changes and you must manually bring you stack back into alignment through the console or aws-cli. Unfortunately your experience is how most people learn about this issue. Going forward make sure to inspect @key and @connection changes in the schema between pushes to ensure there are not multiple GSI operations on a single table at once.

**Comment by taneba** [comment]
@RossWilliams 
Thank you for pretty clear explanation! Yes I definitely have tried to update more than 2 @keys and failed. And didn't expected that it does not handle revert operation.
I hope this behavior and precaution to be clearly documented because this can easily happen when developing a large-scale app in a team.

**Comment by blazinaj** [comment]
What is the fix for this? I've tried removing the offending @connection, then pushing, then re-adding it but get the same error.

**Comment by RossWilliams** [comment]
you must manually bring you stack back into alignment through the console or aws-cli. This means for the console, go into your DynamoDB table, browse to the index tab, and remove the created index.

The reason for this is that Cloudformation does not wait for the index creation to finish, so it is unable to roll back.

**Comment by NotSoShaby** [comment]
I feel like this should be re-opened. the rollback should include the index removal and `amplify push` should validate that there isn't multiply GSI operations before starting to create these indexes.

**Comment by econtentmaps** [comment]
+1

**Comment by ldaudet** [comment]
+1, this should definitely be handled by amplify

**Comment by dylan-westbury** [comment]
+1 handled by amplify

**Comment by vincent38wargnier** [comment]
I think the main problem is to find what causes the failure of the push. 
Once you know that the pb is creating an index that already exists it's easy to fix.

But to get this error written in the CLI I had to make several changes to my gprahql until this error popped. The errors thrown by the CLI are almost useless most of the times I feel.
