### ISSUE TITLE
Add new ClientIds

### ISSUE THREAD

**Issue by bastiancleverfit** [aws-amplify/amplify-cli#4095]
**Which Category is your question related to?**

Auth

**Amplify CLI Version** 

4.18.1

**What AWS Services are you utilizing?**

AWS Cognito

**Provide additional details e.g. code snippets**

Is it possible to add a new clientId to Auth through the CLI?
I have a NodeJS postConfirmation Lambda where in a switch-case i want to add users in specific groups based on the clientId they are coming from.
If it's not currently possible do that, do you have any other suggestion that can suit the case?

**Comment by ammarkarachi** [comment]
@bastiancleverfit Are you using clientIds for the sole purpose of identifying users?

**Comment by bastiancleverfit** [comment]
@ammarkarachi yes. The reading access to user attributes could be shared in my case.

**Comment by ammarkarachi** [comment]
Would you be able to use the user attributes to figure out the group the user must belong to?

**Comment by bastiancleverfit** [comment]
I saw [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html#cognito-user-pools-lambda-trigger-syntax-post-confirmation) that i can pass a **clientMetadata** object, maybe i can pass a value that i can check in Post Confirmation lambda to add the user to the correct group. I'm going to try that.

**Comment by ammarkarachi** [comment]
@bastiancleverfit Do you require any more information regarding this? I will be closing this issue do not hesitate to re open this issue if you need more help.
