### ISSUE TITLE
Support for Cognito Authorizers on Api endpoints

### ISSUE THREAD

**Issue by nibab** [aws-amplify/amplify-cli#4097]
**Is your feature request related to a problem? Please describe.**
Currently, Amplify allows you to restrict apis to authenticated users through IAM credentials. Some of my use cases require me to get the userId associated with a specific request. This is impossible to do with IAM creds. Why not allow Cognito Authorizers as well ? This way I can get the user id through the request context.

**Describe the solution you'd like**
When specifying auth during api creation, add an option for cognito-based auth for the api. At the very least, export the UserPoolId and Lambda Arn so that I can use them in customResources.json to set this up on my own.

**Describe alternatives you've considered**
Currently, I go to the APIG console and set the authorizer manually. This would be trivial to do in a cloudformation template and I've considered adding it as a custom resource in the customResources.json template, but there is no UserPoolId export that I can use as a parameter for the template, which introduces hardcoding - at which point I might as well modify everything manually.

**Comment by ammarkarachi** [comment]
@nibab Are you using GraphQL or Rest?

**Comment by nibab** [comment]
Rest

**Comment by ammarkarachi** [comment]
Hi @nibab,

We don't have this in the CLI yet out of the box but it is being prioritized for release as of now. 
Yes you could either do it through the console but also manage it in the cloudformation [here](https://github.com/aws-amplify/amplify-cli/issues/3390#issuecomment-614389780). You would need to export the userPoolArn from the auth file to use it. Let me know if this helps

**Comment by ammarkarachi** [comment]
@nibab I am closing this issue since it's a duplicate you can follow #3390 for updates of the release
