### ISSUE TITLE
Cognito AppClient use cases?

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#4100]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
My application provisioned two Cognito AppClients when configuring the auth category. They have names like `app0e4a2c7f_app_client` and `app0e4a2c7f_app_clientWeb` Is there any documentation that speaks to when it is appropriate to use one vs the other?

**Comment by ammarkarachi** [comment]
@alexkates One is for the web client,  `app0e4a2c7f_app_clientWeb` does not have a secret option since JavaScript clients have the source open. While `app0e4a2c7f_app_client` is for native apps with the client secret option enabled.

**Comment by alexkates** [comment]
> app0e4a2c7f_app_clientWeb does not have a secret option since JavaScript clients have the source open.
Not sure I completely understand this. Is this differentiation documented anywhere in the Amplify documentation? I can't seem to find much on it.

**Comment by ammarkarachi** [comment]
We don't have the differentiation documented yet but there is more documentation on Cognito User Pool App Client [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html)

**Comment by alexkates** [comment]
Thanks for the information!

**Comment by jszyba** [comment]
What is the reasoning for creating both, considering the framework is chosen during the init phase. Wouldn't it make more sense to only create the one app client needed for the client application for a number of reasons including cost, reducing redundant unnecessary code and configs on the Cognito, Lambda, and Cloudformation side? Not to mention within the client application itself. I've read every bit of the Amplify docs, including the above "resolved" issue to address this, but nowhere does it make explicit that the web app client is for Javascript apps and the ordinary app client is for native apps.
