### ISSUE TITLE
The provided key element does not match the schema when using PK and SK on 1:n

### ISSUE THREAD

**Issue by benjamin79** [aws-amplify/amplify-cli#4101]
Hi,

i´m not sure if it is me or a bug:

As soon as both! the the following models have a PK and a SK i get the error:

> The provided key element does not match the schema

The data is written to the db though. I don´t understand why there is the error. But i see that amplify codegen models puts in the relation in the createPerson query. If i remove it the createPerson works without error 

```graphql
    location {
      id
      name
    }
```

``` graphql
type Person @model @key(fields: ["customerID", "id"]) {
  id: ID!
  name: String!
  customerID: ID!
  locationID: ID!
  location: Location @connection
}

type Location @model @key(fields: ["customerID", "id"]) {
  id: ID!
  name: String!
  customerID: ID!
}

type Customer @model {
  id: ID!
  name: String
}
```

```graphql
mutation CreatePerson($input:CreatePersonInput!) {
  createPerson(input:$input) {
    id
    name
    customerID
    location {
      id
      name
    }
  }
}

```
```json
{"input": {
 "id": 1,
 "customerID": 1,
 "locationID": 1,
 "name": "Doe"
}
}
```

**Which Category is your question related to?**
Schema

**Amplify CLI Version** 
4.18.0

**Comment by ammarkarachi** [comment]
@benjamin79 is the relationship **one to one** or **one to many**?

**Comment by ammarkarachi** [comment]
@benjamin79 The connection should have the fields defined as show below.

```graphql
type Person @model @key(fields: ["customerID", "id"]) {
  id: ID!
  name: String!
  customerID: ID!
  locationID: ID!
  location: Location @connection(fields: ["customerID", "locationID"])
}
```

**Comment by benjamin79** [comment]
@ammarkarachi 
thank you very much. That seems to work. A person can only have one location. But a location can be in many persons.
