### ISSUE TITLE
Validating Many to Many Relationship Existance?

### ISSUE THREAD

**Issue by kennandavison** [aws-amplify/amplify-cli#4107]
**Which Category is your question related to?**
Amplify schema.graphql access patterns

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
AppSync/Amplify

Hi, wondering if anyone has guidance on quick validation of many to many relationship between 2 tables given the ids of both connected tables. This might be more of a general noSQL question, but would I be better off just creating a separate table for this where the id is a concat of the 2 ids?

**Comment by jhockett** [comment]
Hi @kennandavison, have you seen our documentation on this? It shows a working example schema and some queries.
https://docs.amplify.aws/cli/graphql-transformer/directives#many-to-many-connections

Closing this issue for now. Let me know below if there's anything that needs to be clarified or if you have further questions and we can re-open the issue.
