### ISSUE TITLE
How to customize @connection ?

### ISSUE THREAD

**Issue by isheejong** [aws-amplify/amplify-cli#4109]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
``` graphql transformation. ```

**Amplify CLI Version** 
You can use `amplify -v` to check the amplify cli version on your system

```
amplify -v 
4.18.1
```

**What AWS Services are you utilizing?**
``Cognito, AppSync, Dynamodb``

**Provide additional details e.g. code snippets**

Hi, there

As far as I know, If "@connection" use in schema.graphql, Amplify CLI  generate the additional schema as default. 

```
type Cart @aws_api_key
@aws_cognito_user_pools {
	id: ID!
	memberId: String
	sessionId: ID
	cartType: CART_TYPE!
	cartName: String!
	orderSummary: AWSJSON
	orderSummaryInfo: AWSJSON
	createTime: AWSDateTime
	updateTime: AWSDateTime
	cartItems(
		filter: ModelCartItemFilterInput,
		sortDirection: ModelSortDirection,
		limit: Int,
		nextToken: String
	): ModelCartItemConnection
}
```

```
filter: ModelCartItemFilterInput,
		sortDirection: ModelSortDirection,
		limit: Int,
		nextToken: String
```

Above additional schema was created from "@connection", But I reckon these schema don't need, so I don't want to generate these schema, how to customize similar with @model(queries : "", mutations : "", subscribe : "");

**Comment by ammarkarachi** [comment]
@isheejong We don't currently support this can you elaborate on what you are trying to do so we can recommend you an approach to fit your use case?

**Comment by isheejong** [comment]
Thank you for replying.
1. @connection creates some additional models, all of which are not required.
2. AppSync has a problem in that the viewing the schema on the screen becomes slower as the number of models increases.
3. When the number of models increases, the build time of the amplify CLI also takes longer.
So I want to minimize the generated model.

**Comment by kaustavghosh06** [comment]
@isheejong You can use `@model (mutations: null,queries:null, subscriptions: null)` to not create queries/mutations/subscriptions for a model.
