### ISSUE TITLE
Including _version in delete requests, unable to filter _deleted items from list response.

### ISSUE THREAD

**Issue by drixta** [aws-amplify/amplify-cli#4111]
**Which Category is your question related to?**
Using AWS Amplify API to delete items through AWS Appsync

**Amplify CLI Version**
4.18.1

**What AWS Services are you utilizing?**
AWS Appsync, DynamoDB

**Provide additional details e.g. code snippets**
While using API.graphql to delete items from my database I have 2 following issue:

Issue \# 1:

Here is my request to delete a photo from the frontend:
```
API.graphql(graphqlOperation(mutations.deletePhoto, {
      input: {
        id: photoId,
        _version: 1,
      }
    })) as unknown as {
      data: DeletePhotoMutation
    }
```
Currently, there's no way for me delete an item without including the `_version` of the item without running into an error:

```
errorType: "ConflictUnhandled"
message: "Conflict resolver rejects mutation."
```
Is this intended? Or am I missing something.

Issue \# 2 :

When I successfully deleted the item using the API by adding in the `_version` attributes, I verified that the `deleted` attributes in DynamoDB is `false`,

![Screen Shot 2020-04-28 at 8 51 43 PM](https://user-images.githubusercontent.com/2681321/80559353-1cd25b80-8992-11ea-8d0c-43738ec9c21a.png)

When I list all the items again, I couldn't find a way to filter out `deleted` items from server side. The generated types for the filter is like so:
```
export type ModelPhotoFilterInput = {
  id?: ModelIDInput | null,
  albumId?: ModelIDInput | null,
  bucket?: ModelStringInput | null,
  and?: Array< ModelPhotoFilterInput | null > | null,
  or?: Array< ModelPhotoFilterInput | null > | null,
  not?: ModelPhotoFilterInput | null,
};
```

So now I have to fetch all items from serverside and filter deleted items out on the front end like so
```
const listPhotosByAlbum = async (input: ListPhotosByAlbumQueryVariables): Promise<any> => {
  const response = await API.graphql(graphqlOperation(queries.listPhotosByAlbum, input)) as unknown as {
    data: ListPhotosByAlbumQuery
  };
  return response.data.listPhotosByAlbum.items.filter(item => item._deleted !== true);
};

```
 which isn't ideal considering the number of deleted items can grow indefinitely and slow down the response.

Appreciate if anyone can share their experience.

**Comment by raelmiu** [comment]
Same issue, shouldn't Appsync Resolvers filter out `_deleted=true` ?

**Comment by undefobj** [comment]
> **Which Category is your question related to?**
> Using AWS Amplify API to delete items through AWS Appsync
> 
> 
> **Amplify CLI Version**
> 4.18.1
> 
> 
> 
> **What AWS Services are you utilizing?**
> AWS Appsync, DynamoDB
> 
> 
> 
> **Provide additional details e.g. code snippets**
> While using API.graphql to delete items from my database I have 2 following issue:
> 
> Issue \# 1:
> 
> Here is my request to delete a photo from the frontend:
> ```
> API.graphql(graphqlOperation(mutations.deletePhoto, {
>       input: {
>         id: photoId,
>         _version: 1,
>       }
>     })) as unknown as {
>       data: DeletePhotoMutation
>     }
> ```
> Currently, there's no way for me delete an item without including the `_version` of the item without running into an error:
> 
> ```
> errorType: "ConflictUnhandled"
> message: "Conflict resolver rejects mutation."
> ```
> Is this intended? Or am I missing something.
> 
> Issue \# 2 :
> 
> When I successfully deleted the item using the API by adding in the `_version` attributes, I verified that the `deleted` attributes in DynamoDB is `false`,
> 
> ![Screen Shot 2020-04-28 at 8 51 43 PM](https://user-images.githubusercontent.com/2681321/80559353-1cd25b80-8992-11ea-8d0c-43738ec9c21a.png)
> 
> When I list all the items again, I couldn't find a way to filter out `deleted` items from server side. The generated types for the filter is like so:
> ```
> export type ModelPhotoFilterInput = {
>   id?: ModelIDInput | null,
>   albumId?: ModelIDInput | null,
>   bucket?: ModelStringInput | null,
>   and?: Array< ModelPhotoFilterInput | null > | null,
>   or?: Array< ModelPhotoFilterInput | null > | null,
>   not?: ModelPhotoFilterInput | null,
> };
> ```
> 
> So now I have to fetch all items from serverside and filter deleted items out on the front end like so
> ```
> const listPhotosByAlbum = async (input: ListPhotosByAlbumQueryVariables): Promise<any> => {
>   const response = await API.graphql(graphqlOperation(queries.listPhotosByAlbum, input)) as unknown as {
>     data: ListPhotosByAlbumQuery
>   };
>   return response.data.listPhotosByAlbum.items.filter(item => item._deleted !== true);
> };
> 
> ```
>  which isn't ideal considering the number of deleted items can grow indefinitely and slow down the response.
> 
> Appreciate if anyone can share their experience.
> 

@drixta it looks like you setup a sync enabled endpoint but are calling it using the API category instead of DataStore. Did you intend to do this? That's why the version is required. If you didn't intend to do this I'd recommend just creating an app and using `amplify add api` through the standard flow.

**Comment by ammarkarachi** [comment]
@drixta I am closing this issue, do not hesitate to re-open if you have any further questions.

**Comment by drixta** [comment]
> @drixta it looks like you setup a sync enabled endpoint but are calling it using the API category instead of DataStore. Did you intend to do this? That's why the version is required. If you didn't intend to do this I'd recommend just creating an app and using amplify add api through the standard flow.

@ammarkarachi What's the difference between a sync enabled endpoint and a regular endpoint was I'm unaware about this? I did create the endpoint using `amplify add api` so I'm curious what caused the difference.

Is it the `Configure conflict detection` portion during the setup? If so what option is for the regular endpoint, which one Is for the sync endpoint

**Comment by undefobj** [comment]
> > @drixta it looks like you setup a sync enabled endpoint but are calling it using the API category instead of DataStore. Did you intend to do this? That's why the version is required. If you didn't intend to do this I'd recommend just creating an app and using amplify add api through the standard flow.
> 
> @ammarkarachi What's the difference between a sync enabled endpoint and a regular endpoint was I'm unaware about this? I did create the endpoint using `amplify add api` so I'm curious what caused the difference.
> 
> Is it the `Configure conflict detection` portion during the setup? If so what option is for the regular endpoint, which one Is for the sync endpoint

Yes correct conflict resolution is enabling sync. I'd suggest running `amplify update api` and turning off.

**Comment by ivenxu** [comment]
> > > @drixta it looks like you setup a sync enabled endpoint but are calling it using the API category instead of DataStore. Did you intend to do this? That's why the version is required. If you didn't intend to do this I'd recommend just creating an app and using amplify add api through the standard flow.
> > 
> > 
> > @ammarkarachi What's the difference between a sync enabled endpoint and a regular endpoint was I'm unaware about this? I did create the endpoint using `amplify add api` so I'm curious what caused the difference.
> > Is it the `Configure conflict detection` portion during the setup? If so what option is for the regular endpoint, which one Is for the sync endpoint
> 
> Yes correct conflict resolution is enabling sync. I'd suggest running `amplify update api` and turning off.

Which **Configure conflict detection**  should be used?

**Comment by Mentioum** [comment]
> > > > @drixta it looks like you setup a sync enabled endpoint but are calling it using the API category instead of DataStore. Did you intend to do this? That's why the version is required. If you didn't intend to do this I'd recommend just creating an app and using amplify add api through the standard flow.
> > > 
> > > 
> > > @ammarkarachi What's the difference between a sync enabled endpoint and a regular endpoint was I'm unaware about this? I did create the endpoint using `amplify add api` so I'm curious what caused the difference.
> > > Is it the `Configure conflict detection` portion during the setup? If so what option is for the regular endpoint, which one Is for the sync endpoint
> > 
> > 
> > Yes correct conflict resolution is enabling sync. I'd suggest running `amplify update api` and turning off.
> 
> Which **Configure conflict detection** should be used?

I have exactly the same question.  Which option should we select if we want to disable this.

(Although Ideally I'd much rather be able to filter on _deleted as mentioned in in this issue https://github.com/aws-amplify/amplify-cli/issues/4230#issue-616194162 )

**Comment by LawrenceNorman** [comment]
I have to agree with Mentioum & drixta, seems like an unnecessary pain to have filter out deleted items on the client side, and not enable a query of non-deleted items from the server.  I'm running into this same issue, and it's too bad that I can't filter or do something to query out the _deleted items server side via : listBlogs(filter: {type: {notContains: "_deleted"}}), I guess I will look at creating my own field "trash", move the item to the "trash", delete it, and then filter it out non trash from my main queries, but that seems like lot of extra unnecessary steps.

**Comment by undefobj** [comment]
@LawrenceNorman @Mentioum are you using the [API Category in your app client code](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js)? As [mentioned above](https://github.com/aws-amplify/amplify-cli/issues/4111#issuecomment-622656877) the reason the items which are marked for deletion are coming through is because you have syncing enabled on your endpoint which is not designed to work with the API category but rather the [DataStore category](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js). When you're using DataStore it uses this metadata to remove the items from the local storage medium, so no extra filtering is needed there. The API category from your client code isn't designed for synching which is why you shouldn't enable it if you're trying to interface with your GraphQL endpoint directly.

**Comment by Mentioum** [comment]
> @LawrenceNorman @Mentioum are you using the [API Category in your app client code](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js)? As [mentioned above](https://github.com/aws-amplify/amplify-cli/issues/4111#issuecomment-622656877) the reason the items which are marked for deletion are coming through is because you have syncing enabled on your endpoint which is not designed to work with the API category but rather the [DataStore category](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js). When you're using DataStore it uses this metadata to remove the items from the local storage medium, so no extra filtering is needed there. The API category from your client code isn't designed for synching which is why you shouldn't enable it if you're trying to interface with your GraphQL endpoint directly.

Thanks @undefobj that makes sense as to why it's not working.  That being said... I'm using both...

I'm using the datastore from my mobile PWA and the CLI from ReTool for my administration views.  What would you recommend in this scenario?

**Comment by undefobj** [comment]
If you're using both, then you're going to have to independently track versions in your app state (sending the current version when you perform update mutations with API directly) and handling deletion filtering locally. Using both categories together isn't something we fully support OOTB today. It's on the roadmap, but to be transparent it's a bit away.

**Comment by Mentioum** [comment]
@undefobj ok no problem, that's what I ended up doing anyway ( I actually quite like sending the version with updates, it was only the _deleted field which annoyed me, since I wanted to add it to an index so I could filter it out... ).  

Looking forward to seeing how far I and my team can push Amplify, some frustrations so far, with getting up to speed so quickly definitely outweighs the frustrations for now 👍 .

**Comment by ivenxu** [comment]
> @LawrenceNorman @Mentioum are you using the [API Category in your app client code](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js)? As [mentioned above](https://github.com/aws-amplify/amplify-cli/issues/4111#issuecomment-622656877) the reason the items which are marked for deletion are coming through is because you have syncing enabled on your endpoint which is not designed to work with the API category but rather the [DataStore category](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js). When you're using DataStore it uses this metadata to remove the items from the local storage medium, so no extra filtering is needed there. The API category from your client code isn't designed for synching which is why you shouldn't enable it if you're trying to interface with your GraphQL endpoint directly.

Could you please indicate how to disable the sync if it was enabled accidentally at the beginning?

**Comment by LawrenceNorman** [comment]
Good to know that having both DataStore and GraphQL API going together might cause issues if you're not careful.  @ivenxu I kept running into issues with deletion and after reading https://github.com/aws-amplify/amplify-cli/issues/2384
I figured out I had to resort to: 
amplify api remove 
followed by 
amplify add api
and then I just put my graphql db on an api key and opted to not configure conflict detection, and now my graphql mutations seem to be working well.

**Comment by cybercussion** [comment]
I actually ran into this on accident.  I added extra auth on a API so a Lambda could also make edits to AppSync/GraphQL and it asked me what I wanted to do about conflict resolution.  I picked 'AutoMerge' and ran into the same behavior.  I started to edit my schemas to include `_deleted`, `_version` but I thought I'd have the exact same issue having to filter off these records.  Thanks for mentioning the conflict detection, the only way I figured out I could change data was by passing the _version and I didn't want to get into this.  I will also attempt to remove this but I start to quiver every time I execute `amplify update api` :)

**Comment by micahwalter** [comment]
Hi,
I am having an issue I think it related to this thread. When I use the Amplify Admin UI to edit "Content" it requires the Datastore feature to be enabled, but this seems to result in items being marked as "deleted" with no way to easily filter them in a GraphQL query. I'm building a simple Nuxt web app and just used the `amplify add api` and created a Todo table through the CLI. Everything seems to work just fine except this deleted items issue.
-m

**Comment by xho** [comment]
> Hi,
> I am having an issue I think it related to this thread. When I use the Amplify Admin UI to edit "Content" it requires the Datastore feature to be enabled, but this seems to result in items being marked as "deleted" with no way to easily filter them in a GraphQL query. I'm building a simple Nuxt web app and just used the `amplify add api` and created a Todo table through the CLI. Everything seems to work just fine except this deleted items issue.
> -m

@micahwalter hi, I am doing exactly the same with Nuxt and I think I enabled Datastore when I turned on the Admin UI management feature. Did you end up filtering the results in javascript after the GraphQL query? C_

**Comment by martinrojas** [comment]
> Hi,
> I am having an issue I think it related to this thread. When I use the Amplify Admin UI to edit "Content" it requires the Datastore feature to be enabled, but this seems to result in items being marked as "deleted" with no way to easily filter them in a GraphQL query. I'm building a simple Nuxt web app and just used the `amplify add api` and created a Todo table through the CLI. Everything seems to work just fine except this deleted items issue.
> -m

I have encountered the same issue. It seems that if you want to be able to use the Amplify Admin UI then datastored is enabled and removing it breaks the admin UI, but then it makes graphQL API unusable
