### ISSUE TITLE
Performing query on indexed AWSDateTime field 

### ISSUE THREAD

**Issue by Sinisterish** [aws-amplify/amplify-cli#4114]
**Describe the bug**
additional key was added with 
```graphql
@key(name: "ByTime", fields: ["startTime"], queryField: "listEventsByTime")
```

when performing the following query with amplify mock 
```graphql
query MyQuery {
  listEventsByTime(startTime: {gt:  "2020-04-29T23:00:00.000Z"}) {
    items {
      startTime
      id
    }
  }
}
```
it runs successfully, after successful push the same query fails in the aws appsync query console and the code i run on my react app
error message:
```json
{
  "data": null,
  "errors": [
    {
      "path": null,
      "locations": [
        {
          "line": 2,
          "column": 21,
          "sourceName": null
        }
      ],
      "message": "Validation error of type WrongType: argument 'startTime' with value 'ObjectValue{objectFields=[ObjectField{name='gt', value=StringValue{value='2020-04-29T23:00:00.000Z'}}]}' is not a valid 'AWSDateTime' @ 'listEventsByTime'"
    }
  ]
}
```

**Amplify CLI Version**
4.17.2

**To Reproduce**
add the following model and use the query mentioned above
```graphql
type Event
  @model
  @key(fields: ["id"])
  @key(name: "ByTime", fields: ["startTime"], queryField: "listEventsByTime")
  @auth(
    rules: [
      { allow: owner, operations: [create, update, delete] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  eventHash: String!
  title: String!
  link: String!
  hostId: String!
  host: User @connection(name: "EventHost", fields: ["hostId"])
  content: String!
  createdOn: AWSDateTime @auth(rules: [{ allow: private, operations: [read] }])
  startTime: AWSDateTime!
  image: S3Object
}
```

**Expected behavior**
the query should finish successfully on both the mock env and aws appsync console

**Screenshots**
![image](https://user-images.githubusercontent.com/30870308/80613464-008ff680-8a46-11ea-8693-821b596ba642.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v12.13.1

**Additional context**
I tried to delete the API and recreate it, This didn't help

**Comment by akshbhu** [comment]
Hi @Sinisterish 

I dont think this query will work on mock also but response will be different. Appsync console will return a validation error and mock will will return a null list.

A follow up question to debug this:  Does above said query worked for you in amplify mock i.e does it returns a proper list of events or a null list everytime?

**Comment by Sinisterish** [comment]
even if you are correct from the docs it is shows that its possible to have different keys configured and use them with operations like in my example 
[docs](https://docs.amplify.aws/cli/graphql-transformer/directives#how-to-use-key)
in the docs the difference is that they are using two keys instead of one, how would you filter a date key if my query is not valid?

**Comment by akshbhu** [comment]
Hi @Sinisterish 

Your query is prefectly fine. But the Index you made in the schema 
```graphql
@key(name: "ByTime", fields: ["startTime"], queryField: "listEventsByTime")
```
As per documentation the first query argument passed to a query (the hash key) must use strict equality and the second attribute (the sort key) may use gt, ge, lt, le, eq, beginsWith, and between.

In this case you are using sort operations on hash key i.e ```startTime``` .

Can you try passing a hash key  as any field  and sort key  as  ```startTime``` in the schema and check the result for same query?

Let me know if the works for you?
