### ISSUE TITLE
Multiple Environment Multiple Frontend Workflow

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#4119]
**Which Category is your question related to?**
amplify cli, multi-env, multi-frontend

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
AppSync, Cognito, Storage

**Provide additional details e.g. code snippets**
I've been working on a react/amplify app for a while. I have multiple environments set up and it works great. However, I'm trying to create a react-native version now, and I'm wondering how I can enjoy the same CI/CD workflow with my react-native project. I know how to pull an existing backend to the project and that works fine for one environment, but I need a multi-environment, multi-frontend flow. How can I achieve the following:

```
react-native repo/dev => amplify dev env
react-native repo/master => amplify master env
react repo/dev => amplify dev env
react repo/master => amplify master env
```

So that when I am working on my dev branch in the react-native repo I can merge changes (`git checkout master && git merge dev`) and also have the master branch be connected to the master env.

Is there an equivalent to the following workflow with multiple frontends:

```
git checkout master
git merge dev
amplify env checkout master
amplify push
git push
```

The above works well for my react project which has all of the amplify files, but I can't figure out how to do a similar thing in my react-native project.

**Comment by SebSchwartz** [comment]
Have you tried `amplify pull`?
-> https://docs.amplify.aws/cli/teams/multi-frontend

**Comment by karrettgelley** [comment]
@SebSchwartz Like I said, I don't have issue with pulling a specific environment. For instance, I can do `amplify pull` and get the dev environment. I'm just not sure how to implement a multi-environment, multi-frontend workflow

**Comment by UnleashedMind** [comment]
@karrettgelley 
As @SebSchwartz pointed out above, the document https://docs.amplify.aws/cli/teams/multi-frontend has the recommended multiple frontends workflow. 
The Amplify Console's CICD experience is only for web apps. If you have a react-native app that's sharing a backend with your webapp, it's recommended to develop your backend environments in the webapps, and when when they are done, just run `amplify pull` in your native app to generate the frontend config file amplifyconfiguration.

**Comment by karrettgelley** [comment]
@UnleashedMind I just don't understand the docs. Suppose I make changes to the schema in the repo with the amplify folder. How do I get the changes on my react-native repo? When I run amplify pull my schema does not change and therefore amplify codegen does not generate the updated statements. Do I have to re-copy the schema.graphql/schema.json and paste it into the react-native repo again?

**Comment by UnleashedMind** [comment]
@karrettgelley 
after you make the changes to the schema, you need to run `amplify push` to push your changes to the  cloud. You need to wait till gfter the `amplify push` command is executed successfully, then go to to your native app, run `amplify pull` to generate the frontend config file.

**Comment by Tex-Tang** [comment]
@karrettgelley Hi, I'm currently working on this as well. What I did was pull different env according to the branch and use .gitattribute to prevent replace when merge.

Example :
I have a repository to setup all the schema, auth, api....
And for another platform repo, I will pull configuration files from different environments to different branch. ( dev, test, prod ). To prevent replace when merge, for instance, merge from dev to test will replace your configuration file which is what we don't want. I will create a .gitattribute to handle that.
