### ISSUE TITLE
Is Amplify Console the only compatible CI/CD platform? If so, why?

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#4120]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify CLI (Auth + S3)

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
AWS Cognito + AWS S3 + other services that are outside the scope of amplify

**Provide additional details e.g. code snippets**

We are building an SSR react web app (ie. can't be deployed to S3, needs a server):
  - Amplify CLI to handle Auth + Storage infrastructure
  - dev, staging, prod environment in Amplify
  - Website is not deployed to AWS.

Our existing CI is on gitlab and builds all kinds of monorepo things related to the application.

Two questions:
1. Currently or at any point in the future, will Amplify CLI only be compatible with Amplify Console for CI/CD? If so, is this documented in Amplify CLI?

2. Currently or at any point in the future, will the Amplify team only provide documentation for using Amplify CLI in CI/CD alongside Amplify Console, leaving devs to with minimal support in how to use Amplify CLI in other CI/CD platforms?

Related issues:
#1388
https://github.com/aws-amplify/amplify-console/issues/413

**Comment by RossWilliams** [comment]
I have no knowledge of the Amplify team or its plans...

The console hardly does any work for deployment, it just runs a few shell commands. The push command is published in the amplify-console repo. A lot of the documentation discusses how to use the CLI directly to manage a set of environments. You would be doing the same tasks inside a GitLab runner.

Its very easy to run your own deployment pipeline, and likely faster and cheaper than using the Amplify Console. If you aren't hosting on CloudFront, there is very little upside to using it. Just make sure your team understands Cloudformation for when you run into issues.

**Comment by kaustavghosh06** [comment]
@ajhool We do support headless scripts for your CI/CD needs. You can refer to our documentation out here - https://docs.amplify.aws/cli/usage/headless 
Many of our customers have used this to script their pipelines for CI/CD. Let me know if you have any further questions around this.
