### ISSUE TITLE
Generate iOS client code for REST APIs

### ISSUE THREAD

**Issue by berlund** [aws-amplify/amplify-cli#4121]
Hi!

I have a backend with a REST API that is shared between a react front end and an iOS app. When making backend related changes in the same git repo where the react app lives, I want to get that changes into the generated iOS code in the iOS git repo.

I can do a `amplify env pull` in the iOS repo and the generated code is produced when doing a `amplify push` (according to the documentation). Since I don't make changes in the backend here but rather in the react repo, there are no changes to be published from the iOS repo and Amplify will not generate code for my new APIs. 

I can get around by running `amplify push --forced`. 

However, this doesn't seem right and I always get nervous using a `--forced` flag. So, I'd like to know if `amplify codegen` is intended even for REST APIs. If not, what is the recommended way the (re)generate iOS client code?

Thanks for helping,

Lars

**Which Category is your question related to?**
Rest API

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
API Gateway, Lambda, DynamoDB

**Provide additional details e.g. code snippets**

**Comment by ammarkarachi** [comment]
@berlund we don't generate client code for REST, It is only available for GraphQL Api. Also the flag that enables Amplify CLI to push regardless of changes is `--force`

**Comment by berlund** [comment]
Hi ammarkarachi,

Thanks for replying my question. Where does the code placed in ‘generated-src’ come from in an iOS project. Also, at https://docs.amplify.aws/sdk/api/rest/q/platform/ios#set-up-your-backend, it is explained that “Once the deployment completes a folder called generated-src will be added in the folder directory.”

I was wondering if I could trigger that code generation without issuing the `amplify push —force` command.

Best regards,

Lars

**Comment by kaustavghosh06** [comment]
@berlund We actually use the API Gateway service API to fetch the client-code. This would be possible only after deploying your changes to the API Gateway service. As of now we don't have a way in the CLI to generate the client code locally without deploying the changes to the cloud.

**Comment by berlund** [comment]
Ok, thanks for clarification!
