### ISSUE TITLE
API gateway gives cannot GET / after creation api with "amplify add api"

### ISSUE THREAD

**Issue by bitlejac** [aws-amplify/amplify-cli#4123]
**Describe the bug**
i've created api with amplify add api, created lambda, created storage table in dynamo
after i try to test GET endpoint in API gateway it gives me 404

**To Reproduce**
amplify add api, add storage, add lambda function

**Expected behavior**

i am able to test API gateway GET method from UI

**Screenshots**
<img width="929" alt="Screenshot 2020-04-29 at 15 04 51" src="https://user-images.githubusercontent.com/14184888/80601993-d8e16400-8a2e-11ea-997d-f0deb34ad77e.png">

cognito is set to currently accept unauthenticated calls 
 
i've followed documentation to create api for react app,
all seems to be set, i can see dynamo table arn in lambda
also API gateway is properly configured.

but still i am not sure why i am getting this error?
just wanted to see did anyone else experienced the same issue? thanks

**Comment by ammarkarachi** [comment]
@bitlejac Can you provide the steps you used to provision this resource?

**Comment by bitlejac** [comment]
so here it is, steps first to add api, since i tried now to add new one:

<img width="917" alt="Screenshot 2020-04-30 at 09 08 53" src="https://user-images.githubusercontent.com/14184888/80682241-6a4de600-8ac2-11ea-8e3a-47847d1ba5e6.png">
<img width="936" alt="Screenshot 2020-04-30 at 09 09 31" src="https://user-images.githubusercontent.com/14184888/80682262-70dc5d80-8ac2-11ea-81f0-9eff52e704d6.png">

and steps for provisioning :
<img width="1237" alt="Screenshot 2020-04-30 at 09 07 17" src="https://user-images.githubusercontent.com/14184888/80682331-936e7680-8ac2-11ea-9548-3edc01377cda.png">
<img width="1332" alt="Screenshot 2020-04-30 at 09 07 32" src="https://user-images.githubusercontent.com/14184888/80682342-99fcee00-8ac2-11ea-86e4-847d4b35c333.png">

**Comment by edwardfoyle** [comment]
@bitlejac If you take a look at the app.js file generated by the CRUD template, it expects the GET path to be `/movers/moverId`. The CRUD template comes with a lot of overhead that is primarily directed towards customers that are coming from AWS Mobile Hub. If you are trying to set up a new REST API, you will probably be better off starting from the "serverless" template instead
