### ISSUE TITLE
Control `amplify init` profile via AWS_PROFILE and/or --profile

### ISSUE THREAD

**Issue by jmcgeheeiv** [aws-amplify/amplify-cli#4126]
**My problem**
I am automating the creation of my Angular/Amplify project using Ansible. I am stuck on running `amplify init` in Ansible. Ansible does not provide a good way to navigate the `amplify init` menus. I have discovered that interactively, ``j`` works as the down arrow key, but I cannot get even ``j`` to work as input to Ansible `expect`.

For the most part, I am able to use the `amplify init` defaults, which requires no menu navigation using arrow keys.

The problem comes when I try to specify the Amplify administrator profile. [The AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) says that `AWS_PROFILE` and `--profile` can be used to specify the profile. It would be nice if this worked for `amplify init`. To verify, I tried,

    AWS_PROFILE=AmplifyAdministrator amplify init --profile=AmplifyAdministrator

but the default profile remains ``default``:

> Note: It is recommended to run this command from the root of your app directory
> ? Enter a name for the project mediatekaiotcom
> ? Enter a name for the environment dev
> ? Choose your default editor: Visual Studio Code
> ? Choose the type of app that you're building javascript
> Please tell us about your project
> ? What javascript framework are you using angular
> ? Source Directory Path:  src
> ? Distribution Directory Path: dist
> ? Build Command:  npm run-script build
> ? Start Command: ng serve
> Using default provider  awscloudformation
> 
> For more information on AWS Profiles, see:
> https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
> 
> ? Do you want to use an AWS profile? Yes
> **? Please choose the profile you want to use (Use arrow keys)**
>  **AmplifyAdministrator**
>  **amplify-administrator**
>  **❯ default**

**Expected behavior**
For the sake of automating Amplify setup, and for the sake of consistency, it would be nice if `amplify` used `AWS_PROFILE` and/or `--profile`.

Another workable alternative is to have an `amplify init` mode or configuration file that allows literal text input.

**Desktop (please complete the following information):**
- Amplify: 4.18.1
- OS: Ubuntu 18
- Node Version: v12.16.2

**Describe alternatives you've considered**

As mentioned above, I discovered that ``j`` acts as the down arrow key, but in Ansible, ``jj`` does not have the desired effect.

Another approach I tried was to extract all the profile values using:

    aws configure --profile AmplifyAdministrator get <parameterName>

Then I tell `amplify init` that I do not want to use a profile. However, I still need to use arrow keys to select the region.

**Comment by SwaySway** [comment]
Hello @jmcgeheeiv 
You can run amplify init in headless mode.
Docs here: https://docs.amplify.aws/cli/usage/headless#amplify-init-parameters

**Comment by jmcgeheeiv** [comment]
Yes, I at last found those docs. Thank you.

I figured it out and wrote up [how use Ansible to run `amplify init`](https://stackoverflow.com/questions/61529399/how-to-run-aws-amplify-init-in-an-ansible-playbook).
