### ISSUE TITLE
amplify push fails due to s3 permanent redirect

### ISSUE THREAD

**Issue by tthew** [aws-amplify/amplify-cli#4129]
**Describe the bug**

`amplify push` fails due to s3 301'ing.

Interestingly in my case it reports `The bucket is in this region: us-east-1` even though my project is configured to use `eu-central-1`

**Amplify CLI Version**

4.18.1

**To Reproduce**

This has happened a number of times to me and there is no discernable pattern to reproduce, other than adding some amplify services, pushing (it;ll succeed a few times) then add some more services or make say a schema change and then pushing again leads to the push failing.

**Expected behavior**

Push should succeed.

**Screenshots**

I see the following errors in the output:

```sh
UPDATE_FAILED      GraphQLSchema AWS::AppSync::GraphQLSchema Thu Apr 30 2020 15:44:29 GMT+0200 (Central European Summer Time) The bucket is in this region: us-east-1. Please use this region to retry the request (
Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 5B953F953E19A80F; S3 Extended Request ID: zeO6Y5i8RKA3MjEebgiDlJBfqRIibBMbuF+09j0Xa9eYzk5by7H09fNDaZ+QxoAMQHSJ++ilWJc=)
UPDATE_IN_PROGRESS GraphQLSchema AWS::AppSync::GraphQLSchema Thu Apr 30 2020 15:44:28 GMT+0200 (Central European Summer Time)

...

⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-XXX-XXX-01215-apiamplifyDatasource-T9RSVPPKQ8Q4 AWS::CloudFormation::Stack Thu Apr 30 2020 15:44:30 GMT+0200 (Central European Summer Time) The following resource(s) fail
ed to update: [GraphQLSchema].
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-XXX-XXX-01215 AWS::CloudFormation::Stack Thu Apr 30 2020 15:44:34 GMT+0200 (Central European Summer Time) The following resource(s) failed to update: [apiamplifyDatasourc
e].

UPDATE_FAILED               apiamplifyDatasource        AWS::CloudFormation::Stack Thu Apr 30 2020 15:44:34 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:eu-central-1:575024130701:
stack/amplify-XXX-XXX-01215-apiamplifyDatasource-T9RSVPPKQ8Q4/d46d94b0-8a66-11ea-850e-06b323d6b6e2 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(
s) failed to update: [GraphQLSchema].
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Node Version. 12.16.1

**Comment by JanBussieck** [comment]
I am encountering the exact same issue. MacOS 10.14.6 and also Node Version. 12.16.1.

**Comment by ammarkarachi** [comment]
@tthew What resources have you provisioned in your project?

**Comment by ammarkarachi** [comment]
I tried reproducing this but wasn't successful are there any other resources that you are using in your project?

**Comment by JanBussieck** [comment]
For what it's worth after I killed `amplify mock` that was running in a different tmux session the error disappeared.

**Comment by tthew** [comment]
> are there any other resources that you are using in your project?

I had added an auth service prior to running into this issue. Running `amplify update auth`  again and then running `amplify update api` appears to have resolve the issue.

**Comment by 8brandon** [comment]
@JanBussieck  @ammarkarachi.  I had the exact same thing, was getting the error  
```
UPDATE_FAILED               GraphQLSchema                                                        AWS::AppSync::GraphQLSchema Sun May 03 2020 11:12:47 GMT+0200 (Central European Summer Time) The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID

```

When I tried ran amplify publish for hosting, and I had `amplify mock` running in another tab.

Once I killed `amplify mock` and ran amplify publish again, I had no issues.

**Comment by tthew** [comment]
I can confirm I'm seeing the same behaviour. 

With `amplify mock` running there appear to be changes to the DataStore that cause the push to fail. When `amplify mock` is not running everything works as expected.

**Comment by vikgold** [comment]
> For what it's worth after I killed `amplify mock` that was running in a different tmux session the error disappeared.

This workaround solves it. Error started appearing after I updated aws-amplify to the latest version this morning.

**Comment by SwaySway** [comment]
Closing issue - Should you run into this issue again please comment below.

**Comment by defmementomori** [comment]
> I can confirm I'm seeing the same behaviour.
> 
> With `amplify mock` running there appear to be changes to `amplifyDatasource` that cause the push to fail. When `amplify mock` is not running everything works as expected.

I had same situation.
once I stop `amplify mock`, I can amplify push successfully.
