### ISSUE TITLE
@auth private IAM vs everyone Cognito group on graphQL

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-cli#4131]
Is there a difference in usage of allowing IAM auth on a graphQL and adding users to an everyone group on sign up in cognito and using that. 

Mainly because I am having trouble working with private and even public with accessing nested types and just usage in general. One solution https://stackoverflow.com/questions/59588247/why-cant-i-read-relational-data-when-i-use-iam-for-auth-but-can-read-when-auth here suggested adding an additional type for connections to allow access which sort of worked for public but the private I ended up ditching for the everyone Cognito group.
```graphql
type ModelUserFollowConnection @aws_iam @aws_cognito_user_pools{
  items: [UserFollow]
  nextToken: String
}
```
Is that the recommended way of allowing nested access with IAM?

It's getting complicated for me to troubleshoot because takes some time to push changes and sometimes because I am changing `@key` I need to delete the whole table and then because I delete the table I have to readd back with multiple connections which cause the stackoverflow thing so I ultimately just completely remove the GraphQL API and restart...Its a process

Here's what I'm attempting to get working

```graphql
type User 
@model(subscriptions: null)
@key(fields: ["id", "username"]) // either this or next line would be fine
@key(name: "byUsername", fields: ["username", "createdAt"])
@auth(rules: [
  {allow: public, provider: iam, operations: [read]},
  {allow: groups, groups: ["everyone"], operations: [read]},
  {allow: owner, identityField: "sub" , operations: [create, read, update, delete]},
  {allow: groups, groups: ["admin"], operations: [create, read, update, delete]}
]){
  id: ID!
  username: String!
  email: String! @auth(rules: [{ allow: owner, identityField: "sub" , operations: [create, read]},{allow: groups, groups: ["admin"], operations: [create, update, read, delete]}])
  emailOptOut: String! @auth(rules: [{ allow: owner, identityField: "sub" , operations: [create, update, read]},{allow: groups, groups: ["admin"], operations: [create, update, read, delete]}])
  accountType: String!
  bio: String
  following: [UserFollow] @connection(keyName: "byFollower", fields: ["id"])
  followers: [UserFollow] @connection(keyName: "byFollowed", fields: ["id"])
  createdAt: String
  owner: String
}

type UserFollow
  @model( subscriptions: null)
  @auth(rules: [
    {allow: public, provider: iam, operations: [read]}, 
    {allow: owner, identityField: "sub" , operations: [create,read, delete]},
    {allow: groups, groups: ["everyone"], operations: [read, update]},
    {allow: groups, groups: ["admin"], operations: [create,read,update, delete]}])
  @key(name: "byFollower", fields: ["followerID", "followedID"])
  @key(name: "byFollowed", fields: ["followedID", "followerID"]) {
  id: ID!
  followedUsername: String!
  followerUsername: String!
  followedID: ID!
  followerID: ID!
  followed: User! @connection(fields: ["followedID"])
  follower: User! @connection(fields: ["followerID"])
  status: String
  createdAt: String
}
type ModelUserFollowConnection @aws_iam @aws_cognito_user_pools{
  items: [UserFollow]
  nextToken: String
}
```

**Comment by SwaySway** [comment]
Hello @24jr
Using the `@aws_iam` or the `@aws_cognito_user_pools` directives are used to specify the auth level in AppSync. Docs here: https://docs.aws.amazon.com/appsync/latest/devguide/security.html#using-additional-authorization-modes

If you specify these directives, or in this case `@aws_iam` you would need to specify the policies that allows either the authenticated and/or unauthenticated role to have access on the type via [Custom Resources](https://docs.amplify.aws/cli/usage/customcf).

What version of the CLI are you using? I tried to reproduce this without the following addition.
```gql
type ModelUserFollowConnection @aws_iam @aws_cognito_user_pools{
  items: [UserFollow]
  nextToken: String
}
```
After running `amplify api gql-compile` I noticed in the `build/` (located in `amplify/backend/api/<MY API NAME>/build/` that the cloudformation template, `cloudformation-template.json` did include the `@aws_iam` and `@aws_cognito_user_pools`. Could you maybe provide a more detailed flow into the kind of issue you are running into?

**Comment by 24jr** [comment]
I think the problem I was having was because I added queries: null to the model and then IAM public calls weren't working on the @key queries that I made. I just spent a while making a project to display my issue then figured that out so I'll save you the long set up I did

**Comment by tgjorgoski** [comment]
@24jr  , so, how did you solve it in the end? Did you just remove the queries:null and allow queries to be created in the end, in order to solve the nested access through IAM ?

**Comment by 24jr** [comment]
@tgjorgoski Yeah I'm guessing it autogenerates the access control for queries and if you say null it must just not generate them and doesn't realize @key are queries. Idk for sure on that but yeah removing queries: null seemed to allow for the IAM public auth to work. Also I didn't double check on nested just direct but I think it should work
