### ISSUE TITLE
Amplify push fails: stuck with UPDATE_ROLLBACK_IN_PROGRES

### ISSUE THREAD

**Issue by bindhyeswari** [aws-amplify/amplify-cli#4133]
My amplify push fails with the folowing output:
``` 
Stack:arn:aws:cloudformation:us-west-2:065858725437:stack/amplify-wordsearch-prod-120221/b2ec0b50-8787-11ea-a27c-06184e4e65e6 is in UPDATE_ROLLBACK_IN_PROGRESS state and can not be updated.
An error occured during the push operation: Stack:arn:aws:cloudformation:us-west-2:065858725437:stack/amplify-wordsearch-prod-120221/b2ec0b50-8787-11ea-a27c-06184e4e65e6 is in UPDATE_ROLLBACK_IN_PROGRESS state and can not be updated.
```

**Comment by ammarkarachi** [comment]
@bindhyeswari Can you check if an earlier push had failed with your stack?

**Comment by bindhyeswari** [comment]
The issue happened when I was trying to push a simple graphql api setup. The cli was stuck on a UPDATE operation for an hour. So I killed the cli op and when I tried to push again, after a while, it gave me the same error, albeit for the UPDATE operation. 

So I navigated to the AWS Console, and tried to cancel the stack update activity. That too, got stuck.

**Comment by bindhyeswari** [comment]
@ammarkarachi The rollback took a while, but it has completed. I will try out with a new stack and update here if the issue persists.
