### ISSUE TITLE
Unauth policies using auth policy names?

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/amplify-cli#4135]
There are unauthenticated policies (`S3UnauthPolicy*`) which reference the `'authPolicyName'` parameter. Should they not be `'unauthPolicyName'`? Also, the `'unauthPolicyName'` parameter is never used.

https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json#L121

This template is referenced by the [docs](https://docs.amplify.aws/lib/storage/getting-started/q/platform/js#using-amazon-s3).

**Comment by ammarkarachi** [comment]
@mrichman The template linked here isn't being used anymore you can find the template used to generate the cloud formation [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json.ejs). Thanks for bringing this to our attention and do not hesitate to open with any new information you have for us.
