### ISSUE TITLE
How can I turn on debug mode?

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-cli#4136]
I have the issue `TypeError: Cannot read property 'type' of undefined` when I use `amplify api gql-compile` for sure it's related to my GraphQl model but I have no more information.

How can I turn on debug mode?

PS: I' new on GraphQl API and I prefer to learn so please don't ask me to provide my model first. If the issue looks to not be related to my model I will come back to you.

Version:
node v13.13.0
amplify 4.18.1

**Comment by ammarkarachi** [comment]
@Hideman85 If you could share your Schema with us we could help you debug this issue. This looks like an error originating from amplify-cli.

**Comment by Hideman85** [comment]
In file: `graphql-connection-transformer/lib/ModelConnectionTransformer.js`
```
function getFieldType(fields, fieldName) {
    return fields.find(f => f.name.value === fieldName).type;
}
```
It currently looking for the attribute id

But in my case I use a different name for my primary key and I miss to specify @key for that model.

You should notify the user:
`Did you miss the attribute 'id' in your model or to set the primary key like '@key(fields: ["myKey"])'?`

And for others that looking for debugging level there is nothing about that (at least for gql-compile) maybe it would be good to introduce a logger?

**Comment by josefaidt** [comment]
Closing as this has since been addressed with a recent release of Amplify CLI where commands can now be run with a `--debug` flag to print the error's stack trace.
