### ISSUE TITLE
Reference generated types in schema

### ISSUE THREAD

**Issue by isaiahtaylorhh** [aws-amplify/amplify-cli#4140]
**Is your feature request related to a problem? Please describe.**
I'm writing a custom lambda resolver for a field which is basically making a mock connection. We've keyed our dynamo DB in a way that connections are thus far not able to take advantage of. Since this is basically just a connection with a bit of extra functionality, I'd like to still have `filter`, `sortDirection`, our timestamp, etc.

When defining the inputs of the function, I want to be able to say:

```gql
type Taco
  @model
{
  customConnection(filter: ModelDataPointFilterInput, sortDirection: ModelSortDirection): @function
}
```

etc. That is, **I want to be able to reference the types that will be eventually generated.**

**Describe the solution you'd like**
I'd like a syntax to mark a type as "should be generated." Maybe `$`? `gql-compile` will fail if these types do not get generated.

**Describe alternatives you've considered**
The alternative is a lot of copy and paste / renaming from the generated schema.

**Comment by SwaySway** [comment]
Hello @isaiahtaylor 
If I'm understanding this you would like the types `ModelDataPointFilterInput` and `ModelSortDirection` beforehand? If so this types are created as after evaluating the before schema. If you are looking to add them into the schema you would need to add them in the before schema, then the transformer would read these are overwrites and not recreate the types.

**Comment by isaiahtaylor** [comment]
@SwaySway this is certainly a valid path in simple scenarios (copy-pasting the types into the before schema), but with more complicated types it would be nice to be able to reference types that other connections depend on eventually.

**Comment by SwaySway** [comment]
@isaiahtaylor These inputs are mainly used against a DynamoDB backed datasource. Perhaps another potential enhancement to discuss with the team would be creating a connection against a specified DynamoDB table? I assume these arguments (filter and direction) are mainly used to generate a payload to DynamoDB in the lambda function?

**Comment by isaiahtaylor** [comment]
Pasting is fine for us for now. Fine with closing this.

**Comment by BracketJohn** [comment]
I'd also be interested in a solution for this! 

For now, we're also copy and pasting, but re-using would certainly be nicer. For us, it would be nice to re-use generated input types in a Query that resolves from a Lambda function like so:

```gql

type LocationScore {
    noise: Float
    shopping: Float
    view: Float
}

[...]

type Query {
  locationScoreCalculations(locationScore: LocationScoreInput!): LocationScore @function(name: "locationScoreCalculations-${env}")
}
```
