### ISSUE TITLE
Missing awsconfiguration.json

### ISSUE THREAD

**Issue by alexcoliveira1** [aws-amplify/amplify-cli#4142]
**Which Category is your question related to?**
Missing `awsconfiguration.json`.
Don't know if it is a bug, so I decided to start with a question.
Even after running `amplify init` and later on `amplify mock api` I can't find this file, am I missing any steps?

I need that file because the [documentation says](https://docs.amplify.aws/cli/usage/mock#awsconfigurationjson-example) that it is where I have `DangerouslyConnectToHTTPEndpointForTesting` set while local testing my GraphQL API without HTTPS.

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
"Only" Amplify, I'm following the [getting started guide with React Native](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react-native#connect-frontend-to-api)

**Provide additional details e.g. code snippets**
As mentioned above, same as getting started guide. I missed this file when trying to run my Todo application with expo in web browser.

`xhr.js:172 Mixed Content: The page at 'https://localhost:19006/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.0.2:20002/graphql'. This request has been blocked; the content must be served over HTTPS.`

**Comment by SwaySway** [comment]
Hello @alexcoliveira1 
After running `amplify push` did it not create the `awsconfiguration.json` file?

**Comment by alexcoliveira1** [comment]
@SwaySway no it didn't, I have run it twice now and no signs of it.
```
$ ls *aws*
aws-exports.js
```

**Comment by kaustavghosh06** [comment]
In your init step did you mention that the type of your project is "js" type? If it's JS type - then the aws-exports.js file is created. awsconfiguration.json file is created only if the project type is iOS and Android. You can change it by going through the `amplify configure project` command.

**Comment by alexcoliveira1** [comment]
I see, so if I have react-native(js) project, how do I bypass the insecure warning I'm receiving when trying to run my application with `expo start` and the graphql with `amplify mock api`?

**Comment by edwardfoyle** [comment]
When mocking the API, you should see `"aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true` in your aws-exports file. However that flag only allows the Amplify client to connect to your local mock server. It seems like you may have some sort of browser security measure or other library that is blocking the request over http
