### ISSUE TITLE
When will the London Region support will be available?

### ISSUE THREAD

**Issue by animalmagnetic** [aws-amplify/amplify-cli#415]
I would like to configure my mobile project serverless via amplify cli but I can't see London (west-2) support in the configuration. 

Is there any approx. date for this region support? I really want to avoid moving between regions.

**Comment by kaustavghosh06** [comment]
@animalmagnetic  I cannot comment on the timeline for this. As soon as the AWS services we support as a part of the CLI are available in London, we'll make it available as a part of the CLI.

**Comment by kaustavghosh06** [comment]
@@animalmagnetic We launched London support with CLI version 1.1.8.

**Comment by animalmagnetic** [comment]
Thank you!
