### ISSUE TITLE
Validation error of type UnknownType: Unknown type... Model xxx FilterInput

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#4150]
**Which Category is your question related to?**
API - GraphQL

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
API, Auth, DynamoDb, Lambda, AppSync

**Scenario detail**
Frankly, I don't know if this is a bug or not, so I'm posting it here, after souring Google and coming up short for a solution.  It's highly likely that I'm doing something stupid, so keep that in mind.

I've created a basic setup with `amplify init`, adding `auth` and `api`, following this pretty decent article found [here](https://medium.com/@fullstackpho/aws-amplify-multi-auth-graphql-public-read-and-authenticated-create-update-delete-1bf5443b0ad1).

In `schema.graphql`, I've setup a type, named `FibIndex`, basically replacing `Task` in the aforementioned doc.

After an `amplify push`, CodeGen does a bunch of heavy lifting, and I can run a query like the below in the AWS AppSync Console (with IAM auth provider), after creating an entry with a signed-in user (via User Pool Provider):

```js
query listFibIndexs {
  listFibIndexs {
    items {
      index
      value
    }
  }
}
```
On my local machine, when I run:  `API.graphql(graphqlOperation(queries.listFibIndexs));`, I receive the following error in the browser console. 
```console
"Validation error of type UnknownType: Unknown type ModelfibIndexFilterInput"
```
**Why this is weird** is because the error shows `ModelfibIndexFilterInput` with a lower-case `f` for `fibIndex`.  

I've searched my codebase and the schema file in the AppSync console, and `ModelfibIndexFilterInput` does not exist.  Only `ModelFibIndexFilterInput`, with a capital `F` exists.

I'm at a loss of how to troubleshoot this.  Any pointers?

Thanks

**listFibIndexs in queries.js**
```
export const listFibIndexs = /* GraphQL */ `
  query ListFibIndexs(
    $filter: ModelFibIndexFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listFibIndexs(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        index
        value
        owner
      }
      nextToken
    }
  }
`;
```

**Comment by yuth** [comment]
@kimfucious I tried reproducing this but could not. Can you please clarify the following
- Does you see any of the `query.js`, `mutation` and `subscription` inside `graphql\` have reference to `ModelfibIndexFilterInput` (see `fib` is lowercase here)
- What version of Amplify JS library are you using to make request to the service
- Is this run using Amplify mock or are you calling the AppSync endpoint

**Comment by kimfucious** [comment]
Hi @yuth, thanks for the response.

Oddly, this problem somehow fixed itself after me coming back to it a day later.  No changes were made, only the app was restarted.

I'm gonna chalk this up to me doing something stupid, though I've no idea what or how.

Anyhow, to answer your questions:

Yes, I did a search of the entire codebase, and `ModelfibIndexFilterInput` does not exist.

I'm using the `@aws-amplify/api": "^3.1.9` package, with the following React pattern, not using mock.
```js
  useEffect(() => {
    API.graphql(graphqlOperation(queries.listFibIndexs)).then(
      (fibIndexesData) => {
        dispatch({
          type: "SET_INDEXES",
          payload: fibIndexesData.data.listFibIndexs.items
        });
      }
    );
  }, []);
```
