### ISSUE TITLE
Access Graphql in Python Lmbda Function

### ISSUE THREAD

**Issue by rehanbabertkxel** [aws-amplify/amplify-cli#4152]
**Which Category is your question related to?**
Amplify Add Function (Python Lambda)

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
AWS AMPLIFY, AWS LAMBDA FUNCTION, Graphql

**Provide additional details e.g. code snippets**
I have an old scheduling algorithm that is already written in Python which reads some excel files and rum the algorithm on that data.
Now I want the same code to run on data fetched using GRAPHQL. I have created those tables in dynamodb using appsync schema after running "amplify add api".

How can I fetch data using GraphQl in my Python Lambda function added using "amplify add function"?

**Comment by yuth** [comment]
@rehanbabertkxel We dont have any specific recommendation for the python GraphQL client library at this moment. 

I can point to couple of blog posts which go in detail on how to implement your own library for making requests to AppSync
For query and mutation - https://towardsdatascience.com/connecting-to-a-graphql-api-using-python-246dda927840
Subscriptions - https://aws.amazon.com/blogs/mobile/appsync-websockets-python/
