### ISSUE TITLE
API access unauthenticated error using IAM as an additional auth mode on client

### ISSUE THREAD

**Issue by hello2all** [aws-amplify/amplify-cli#4159]
**Which Category is your question related to?**
Multiple auth modes on API

**Amplify CLI Version** 
4.4.0

**What AWS Services are you utilizing?**
Amplify Auth, Amplify API, Lambda resolver

**Provide additional details e.g. code snippets**
My API has the default auth mode set as cognito user pool and one additional auth mode as IAM. However when I access the API with the following code with amplify generated `aws-exports.js` config:

```js
    const res = await API.graphql({
      query: queries.getHanShanRate,
      variables: {input: {currency: 'CNY'}},
      authMode: 'AWS_IAM'
    });
    console.log(res);
```
I get the following error with code 401:

```json
{
  "errors" : [ {
    "errorType" : "UnauthorizedException",
    "message" : "Permission denied"
  } ]
}
```
However in the Appsync web console, using the IAM auth mode do the same query returns the expected result shown in the screen shot below:

![Screenshot 2020-05-04 at 4 17 18 PM](https://user-images.githubusercontent.com/7988581/80947584-0cebc900-8e23-11ea-9cff-523d701170e7.png)

Do I need additional IAM configurations on the client side? The documentation is lacking in this regard and there isn't much examples that I can follow. My graphql schema as shown in AppSync web console (as current graphql transform library does not yet support multiple auth modes):

```gql
# this query invokes a lambda resolver to get data from an external source
type Query {
	getHanShanRate(input: getReferenceRateInput): ReferenceRateResult
		@aws_iam
}

type ReferenceRateResult @aws_iam {
	currency: Currency
	rate: Float
	fee: Float
	feeCurrency: Currency
	updatedAt: AWSDateTime
}
```

My intention for this setup is straight forward: I need to open some APIs to unauthenticated users while other APIs are protected by cognito user pool by default. Is there a better way of achieving the same goal?

**Comment by yuth** [comment]
> My graphql schema as shown in AppSync web console (as current graphql transform library does not yet support multiple auth modes):

Could you elaborate what do you mean by this? The transformer does support multi auth. Its documented [here](https://docs.amplify.aws/cli/graphql-transformer/directives#public-authorization) how to use public auth using IAM.

If you're doing type extension, then you will have to add IAM policy that allows UnAuth role access that query.

**Comment by hello2all** [comment]
@yuth Oh, maybe I was not up to date. I was under the impression that `@aws_iam` is not available for Amplify CLI GraphQL Transform library from this [post](https://amazonaws-china.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/), in which it states:

**As of this post, the AWS Amplify CLI GraphQL Transform library does not yet support multiple authorization types though it is on the roadmap & being worked on.**

Anyway, I just tried the method provided in the documentation using the following implementation: 
```
  getHanShanRate(input: getReferenceRateInput): ReferenceRateResult
    @function(name: "rates-${env}")
    @auth(rules: [{ allow: public, provider: iam }])
```
Unfortunately I have this warning in mock server:
```
Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
```
and the frontend still has 401:
```
{ "errors": [{ "errorType": "UnauthorizedException", "message": "UnauthorizedException:Invalid JWT Token" }] }
```

**Comment by hello2all** [comment]
It still puzzles me why Appsync web console has the correct response while the client doesn't. 🤔

**Comment by yuth** [comment]
> It still puzzles me why Appsync web console has the correct response while the client doesn't. 🤔

When using AppSync console, IAM auth uses your current IAM user which most probably is an Admin user with all the privileges.



> @yuth Oh, maybe I was not up to date. I was under the impression that `@aws_iam` is not available for Amplify CLI GraphQL Transform library from this [post](https://amazonaws-china.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/), in which it states:

We added multi auth support in Amplify CLI in third quarter last year.

> Unfortunately I have this warning in mock server:
> 
> ```
> Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
> ```

This should be OK as you're using the static authorization rule here and Auth will work as expected.  Mock does not fully support IAM, it just treats any IAM request as an authorized requst.





> and the frontend still has 401:
> 
> ```
> { "errors": [{ "errorType": "UnauthorizedException", "message": "UnauthorizedException:Invalid JWT Token" }] }
> ```

What do you pass as `authorization` HTTP header when you make request to GraphQL API? From the error message it looks like the `authorization` header is missing in your request

**Comment by hello2all** [comment]
@yuth I updated `amplify-js` to the latest version, now the frontend gets 200 response. It seems the older version of `amplify-js` might sign header differently than the latest version.

However now the graphql throws error complaining not having authorised access to the return type items:

```
{
   "data":{
      "getHanShanRate":{
         "currency":null,
         "rate":null,
         "fee":null,
         "feeCurrency":null,
         "updatedAt":null
      }
   },
   "errors":[
      {
         "message":"Not Authorized to access currency on type ReferenceRateResult",
         "errorType":"Unauthorized",
         ...
         ]
      },
     ...
   ]
}
```
The response is a user defined type:
```
type ReferenceRateResult {
	currency: Currency
	rate: Float
	fee: Float
	feeCurrency: Currency
	updatedAt: AWSDateTime
}
```

Since `ReferenceRateResult` is not attached to a `@model` directive, it can not be annotated with `@auth`. Therefore I resorted using `@aws_iam` decorator in appsync web console:

```
type Query {
	getHanShanRate(input: getReferenceRateInput): ReferenceRateResult
		@aws_iam
}

type ReferenceRateResult @aws_iam {
	currency: Currency
	rate: Float
	fee: Float
	feeCurrency: Currency
	updatedAt: AWSDateTime
}
```
With the modifications above both AppSync web console query and client have the correct response.

**Comment by hello2all** [comment]
Regarding Amplify CLI GraphQL Transform, there are two aspects IMO should further improve:
1. Should support `@auth` directive on non model types; or non model types should be accessible to un-authenticated access by default.
2. `@auth` decorator should only be applied to a field in the `type Query` instead of the root type. For example, in my `schema.graphql` the decorator is annotated to a field in `type Query`:

```
type Query {
  myQuery(input): myResponse @auth(rules: [{ allow: public, provider: iam }])
}
```
I'd expect in AppSync console auth directive is on `myQuery` field:

```
type Query {
  myQuery(input): myResponse @aws_iam
}
```
However the current behaviour is:
```
type Query @aws_iam {
  myQuery(input): myResponse
}
```

**Comment by djsmedes** [comment]
I'm not sure if this is related, but perhaps - I just ran into issues with a lambda being unauthorized to access the API under perhaps similar conditions, and was able to figure out a workaround. Here's the issue I opened with the details: https://github.com/aws-amplify/amplify-cli/issues/4306

**Comment by kaustavghosh06** [comment]
@hello2all Are you still stuck on this issue? For non-model types you can use @aws_iam decorator and the transformer will passthrough this directive. cc @attilah

**Comment by hello2all** [comment]
@kaustavghosh06 Thank you, this issue has been resolved. You may close this thread.
