### ISSUE TITLE
Cannot create function with no parameters

### ISSUE THREAD

**Issue by isaiahtaylor** [aws-amplify/amplify-cli#4162]
**Describe the bug**
You can't specify a function with no parameters in the graphql schema.

```gql
# This fails with "Syntax Error: Expected Name, found )"
type Pizza {
  flavor(): [string] @function(name: "...")
}

# This succeeds
type Pizza {
  flavor(noop: Boolean): [string] @function(name: "...")
}

```

**Amplify CLI Version**
4.18.1

**Expected behavior**
The ability to have a function with no parameters.

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Node v12.16.1

**Additional context**
I don't need parameters because this function will grab `ctx.source` for everything that is needed.

**Comment by yuth** [comment]
@isaiahtaylor If you dont need specify parameter to the query then you should not have `()` parenthesis in query. This the requirement of GraphQL spec
```gql
type Pizza {
  flavor: [string] @function(name: "...")
}
```

**Comment by isaiahtaylor** [comment]
Thanks, works great.
