### ISSUE TITLE
Enable DynamoDB Point In Time Recovery through Amplify CLI

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4163]
**Which Category is your question related to?**

I want to enable to DynamoDB Point In Time Recovery - but can't see where I should set this up in my Amplify project.

**Amplify CLI Version** 

4.18.1

**What AWS Services are you utilizing?**

AppSync, DynamoDB, ElasticSearch

**Provide additional details e.g. code snippets**

I can see the api/<name>/build/stacks/<table>.json has a specification for enable Point In Time Recovery. I can't see where I can put this in as a default value so that all my tables have Point In Time Recovery enabled.

```
        "DynamoDBEnablePointInTimeRecovery": {
            "Type": "String",
            "Description": "Whether to enable Point in Time Recovery on the table",
            "Default": "false",
            "AllowedValues": [
                "true",
                "false"
            ]
        }
```

**Comment by yuth** [comment]
You can enable this by adding a new property called `DynamoDBEnablePointInTimeRecovery` and setting it to `"true"` in `amplify/backend/api/<api-name>/parameters.json`
```json
{
    "AppSyncApiName": "<api-name>",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": "false",
    "DynamoDBEnablePointInTimeRecovery": "true"
}
```

Feel free to comment here if this does not resolve the issue

**Comment by sacrampton** [comment]
@yuth - thanks for this. I did try that initially - unsuccessfully. I'll try it again and confirm it workd.

**Comment by sacrampton** [comment]
I confirm that worked perfectly - guess I did something stupid in my first attempt. Thanks
