### ISSUE TITLE
Query Limit does not work properly with API GraphQL

### ISSUE THREAD

**Issue by edeuxk** [aws-amplify/amplify-cli#4166]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I try to get X elements from AppSync with query Limit but it does not work properly.

**Amplify CLI Version**
4.18.1

**To Reproduce**
Schema.graphql

```
type InventoryRoom
    @model
    @auth(rules: [
        { allow: private, operations: [read] }
        { allow: groups, groups: ["admin"] }
    ])
{
    id: ID!
    name: String
    items: [InventoryItem] @connection(keyName: "byRoom", fields: ["id"])
}

type InventoryItem
    @model
    @key(name: "byRoom", fields: ["roomID"])
    @auth(rules: [
        { allow: private, operations: [read] }
        { allow: groups, groups: ["admin"] }
    ])
{
    id: ID!
    name: String!
    volume: Int!
    imageKey: String
    imageIdentityId: String
    roomID: ID!
    room: InventoryRoom! @connection(fields: ["roomID"])
}

```

**Expected behavior**
I except to receive 5 items if I enter limit: 5

**Screenshots**
Limit 5: got 2
![image](https://user-images.githubusercontent.com/8247995/81056902-b4bcd180-8ecb-11ea-8859-7481e401fdac.png)

Limit 10: got 3
![image](https://user-images.githubusercontent.com/8247995/81056984-dcac3500-8ecb-11ea-8a24-8b4e1f166812.png)

Limit 500: to list all
![image](https://user-images.githubusercontent.com/8247995/81057005-e6359d00-8ecb-11ea-8d29-95b22d70ed84.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Node Version. v12.16.2

**Comment by yuth** [comment]
When using @auth directive, filtering of the record happens in the response mapping template of the resolver, which means the number of results you get would sometimes be less than the limit passed to the query.

This is a limitation of DynamoDB where query operation will read up to the maximum number of items set (if using the Limit parameter) or a maximum of 1 MB of data and then apply any filtering to the results using FilterExpression.

**Comment by edeuxk** [comment]
But my database is 4kb.
I would like to know if this is an issue or something I should fix on my own.

**Comment by yuth** [comment]
DynamoDB first loads the number of records that are specified in the `limit` and then does the filtering of those records. So there is nothing that can be done other then having a larger limit and loading next page if the response has `nextToken`

**Comment by edeuxk** [comment]
Ok so, DynamoDB first loads records that maybe user does not have access and apply a filter on it..

In theory, the user can have no records on first query and need to go through multiple nextToken queries to fulfill his datatable.

It's not a bug?

**Comment by alxistn** [comment]
> DynamoDB first loads the number of records that are specified in the `limit` and then does the filtering of those records. So there is nothing that can be done other then having a larger limit and loading next page if the response has `nextToken`

This is means that by having, let's say 1000 records in my database, if I query the list with the @auth directive on my graphql model, and DynamoDB can only load let's say, 200 on them records and THEN apply the filter, if the record I'm looking for is the 201th, it will not be returned ?

**Comment by LucasAndrad** [comment]
Issues on Amplify are almost always left behind, people are asking questions here so why nobody answered? Why there is no link to some doc or somewhere with an explanation? Why is this issue closed? @edeuxk @alxistn asked great questions and I also didn't get why Dynamo works that way in this case. @yuth

**Comment by alxistn** [comment]
You can find a better explanation here: https://github.com/aws-amplify/amplify-cli/issues/4177#issuecomment-624755354

**Comment by dutzi** [comment]
This is awful.

Where is it documented? How is this considered expected behavior?
