### ISSUE TITLE
Reproduce SAM behavior for Lambda environement variables

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-cli#4168]
**Is your feature request related to a problem? Please describe.**

There is no easy way to inject environement variables when invoking a Lambda using `amplify function invoke`

**Describe the solution you'd like**

AWS SAM provides a conveinient --env-vars option to their command. See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html#serverless-sam-cli-using-invoke-environment-file

**Describe alternatives you've considered**

I'm currently using the dotenv library to load a local env file. It's painful because:
- I have to remember to remove it before pushing
- If I want to commit it, there is no clear way to tell my Lambda to only use it when invoked locally
- It's not great for the team to explain them this hack

**Additional context**
I guess copying SAM is the most straightforward way to do it as it fits the AWS environment and the underlaying services.

**Comment by yuth** [comment]
Are these custom environment variables or are these the ones injected by Amplify CLI (`ENV` and `REGION`)? If its the later case, then `amplify mock function <function-name>` should automatically inject those variables.

**Comment by maximelebastard** [comment]
Hi yuth,

It's for the AdminQueries autogenerated function, so you say they're supposed to be injected ?

```
ENV
GROUP
REGION
USERPOOL
API_MYPROJECT_GRAPHQLAPIOUTPUT
```
I just tested the commands `amplify mock function AdminQueriesecxxxxxx` and `amplify function invoke AdminQueriesecxxxxxx` and doing a `console.log(process.env)`. None of them are automatically injected those env vars.

I don't think that's related, but I get this error when running `amplify mock` alone
```
Mock does not handle CloudFormation resource of type AWS::Elasticsearch::Domain. Skipping processing resource ElasticSearchDomain.
Data source of type AMAZON_ELASTICSEARCH is not supported by local mocking. A NONE data source will be used.
Failed to start API Mock endpoint Error: Could not get resource ElasticSearchDomain
```

**Comment by ammarkarachi** [comment]
@maximelebastard The api end point cannot be mocked but the function you are creating we should be able to mock after a successful push.

**Comment by loganpowell** [comment]
@yuth 
> Are these custom environment variables or are these the ones injected by Amplify CLI (ENV and REGION)? If its the later case, then amplify mock function <function-name> should automatically inject those variables.

I believe @maximelebastard is referring (as I am in my support of reopening this issue) to setting our own custom `.env` variables (as we normally do in Node). For example, API keys, etc...
