### ISSUE TITLE
Support async style for node lambda functions in local invoke + creation of sample code

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#417]
**Is your feature request related to a problem? Please describe.**
I'm new to Lambda but it seems the default hello world example uses the old Node v4 context object way of return results (see https://stackoverflow.com/questions/47906116/context-vs-callback-in-aws-lambda). 

And if I use the latest "async" way of doing things the local invoke doesn't show the results returned by async.   

**Describe the solution you'd like**
All examples should use the latest recommended way of writing lambda methods which I believe is the 'async' way that comes with node v8

**Describe alternatives you've considered**
context and callback methods work fine right now.

**Comment by kaustavghosh06** [comment]
@hisham I believe we converted all of our NodeJS functions to async style and mock should be working with our templates. Are you still having issues with this?

**Comment by hisham** [comment]
Haven't run into issues in a while, closing. Thanks! :)
