### ISSUE TITLE
Most trending searches for post

### ISSUE THREAD

**Issue by Graig123git** [aws-amplify/amplify-cli#4173]
**Which Category is your question related to?**
ElasticSearch
**What AWS Services are you utilizing?**

  AppSync + Elastic-search

**Provide additional details e.g. code snippets**

I have the following Post Schema that  defines a list of posts within my application.
```gql
type Post @model 
@searchable
@auth(rules: [{ allow: private }]) {
  id: ID!
  title: String!
  des: String!
  searchTags:[String!]
}
```
I am using the @searchable directive to stream data into elastic search which is all working fine.
I executed the following query for searches 
```js
await API.graphql(graphqlOperation(queries.searchPosts, {
    filter: {
        searchTags: { wildcard: value.toLowerCase() + "*" },
    }
}))
```
which returns a wildcard result for the searchTags field N.B. searchTags field is an array of string so searchTags can be ["Fatty food","vacations","Trips"]. This is all working fine and a number of post is returned once they match the wildcard results. Now i want to do some aggregation on the Post table to see the top 10 Posts returned from the query base on a specific time frame aka trending post  but i am not sure how to do this. Thanks in advance for any assistance.

**Comment by yuth** [comment]
If you need this to be based on a date range, you will have to update your schema to include `createdAt` and `updatedAt` fields so those dates get exoposed in your schema and you should be able filter them. These timestamps should already in DynamoDB tables

```gql
type Post @model 
@searchable
@auth(rules: [{ allow: private }]) {
  id: ID!
  title: String!
  des: String!
  searchTags:[String!]
  createdAt: String
  updatedAt:String
}
```

Once you these dates, you should be able to update your search filter to include these dates

**Comment by Graig123git** [comment]
@yuth Yes those fields are already in the schema, any code example or idea on how i could write 
the AppSync  query to achieve this ?

**Comment by yuth** [comment]
We don't have support for range query yet for `createdAt` and `updatedAt` fields but we have an PR https://github.com/aws-amplify/amplify-cli/pull/3432 in works to add support to add this.

**Comment by Graig123git** [comment]
@yuth ok i see, lets simplify the requirements and remove the range. So now i just want to see the top Posts results base on the searchTags query. How could i achieve this ?

**Comment by yuth** [comment]
@Graig123git what make a post top post? Is it the based on 👍 on the post? In the sample type you posted I don't see any field we can use to sort

**Comment by Graig123git** [comment]
@yuth  in the post schema the searchTags field is an array if string that is searchable using the 
@searcahe directive. So a top Post or top 5 list of post should be based on the amount of times 
a specific searchTag word is search using elasticsearch.  so if i have the following searchTags
["Fatty food", "Vacation", "Trips"] and ["Programming", "Java","Javascript"] which ever one of these words appear the most using elastic search would leave to that post been the top post.

**Comment by Graig123git** [comment]
@yuth is it clearer to you what am trying to achieve ? am trying to achieve something similar
to this post https://discuss.elastic.co/t/find-trending-article/209158

**Comment by ammarkarachi** [comment]
@Graig123git We don't support querying aggregations as of yet but this is an enhancement which we will be prioritizing in our upcoming sprints.

**Comment by Graig123git** [comment]
@yuth  thanks for the response, any possible work around for now that you could suggest ?

**Comment by ammarkarachi** [comment]
The workaround although not trivial can be achieved by using the function directive
```graphql
type Query {
  getTopHits(msg: String):[CountPostsBySearchTags] @function(name: "aggregation-${env}")
}
type CountPostsBySearchTags {
/#  model to ES's aggregation response
/# "aggregations" : {
/#      "trending" : {
/#        "doc_count" : 847,
/#        "keywords" : {
/#          "doc_count" : 847,
/#          "bg_count" : 301038,
/#          "buckets" : [ ]
/#       }
/#     }
}
```
And implement a resolver for the aggregation query as show here
https://docs.amplify.aws/cli/graphql-transformer/resolvers

**Comment by renebrandel** [comment]
Hi we now support date range queries and more aggregation queries. Would love to get your thoughts on if that addresses your issue here: 

https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#aggregate-values-for-search-result-minimum-maximum-average-sum-terms

you can supply the lowerbound and upperbound date ranges via the query below.
```graphql
query MyQuery {
  searchPosts(filter: {
    createdAt: {
      range: ["...", "...."]
    }
  }) {
    items {
      createdAt
      name
    }
  }
}
```

**Comment by renebrandel** [comment]
@-mention me if this doesn't fully address your use case.
