### ISSUE TITLE
Hugo & React to have same appsync Graphql API 

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#4175]
**Which Category is your question related to?**
Graphql API, Appsync 

**Amplify CLI Version** 
v 4.18.1

**What AWS Services are you utilizing?**
Cognito, Lambda, SES, Pinpoint

**Provide additional details**
I would like to collect emails on static hugo website. I would save email addresses in dynamodb.
I would like to manage list via react app and send bulk email with SES and Lambda.

**My question is can Hugo and React share same Graphql API?**

**Comment by yuth** [comment]
Same API can be used with both Hugo and React app. Amplify CLI supports using same backend with mulitple front-ends with `amplify pull` command. Its documented [here](https://docs.amplify.aws/cli/teams/multi-frontend#workflow)

**Comment by apoorvmote** [comment]
Thanks! Hugo integration to amplify is relatively new so I just wanted to confirm that its considered as just another frontend.
