### ISSUE TITLE
Sharing documents for only two authenticated users

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#4176]
Hi,

I am a fan of AWS Amplify but there is a lack. Because there is no way to allow two people to see a single document. By example for a chat app.

I think it's a bad practice to create an infinite number of groups each time we have a new duo.

**Comment by yuth** [comment]
@rudyhadoux is this related to Cognito groups and how group authorization works in GraphQL transformer?

**Comment by rudyhadoux** [comment]
It is related to @auth possibilities and features.

**Comment by rudyhadoux** [comment]
@auth allows to use owner or groups, but not two users.

**Comment by yuth** [comment]
@rudyhadoux I wonder if you could use [dynamic group auth](https://docs.amplify.aws/cli/graphql-transformer/directives#dynamic-group-authorization) this to solve the issue

**Comment by rudyhadoux** [comment]
According to this page
https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html
Cognito user groups maximum is 10000.
But with a big chat app by example that is not enough.

**Comment by yuth** [comment]
Transformer supports [custom claims](https://docs.amplify.aws/cli/graphql-transformer/directives#custom-claims) and you could pass idToken with custom group field which can be generated as part of (Cognito Pre Token Generation Lambda Trigger )[https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html]

**Comment by rudyhadoux** [comment]
I will study that. Thanks.

**Comment by rudyhadoux** [comment]
In fact the question is : how to make "storage.vault.get( key )" accessible only for two users ?

**Comment by yuth** [comment]
You probably can do this with @function directive and then generate [signed url](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)

**Comment by rudyhadoux** [comment]
Yes but for me it should be an internal functionality of the Amplify Framework, that we should be able to use directly. In any case, thank you for your help.

**Comment by rudyhadoux** [comment]
I think it is the same problem here :
https://github.com/aws-amplify/amplify-js/issues/2203
