### ISSUE TITLE
Update-Conflict related to an API error and Lambda not supporting node8.10 any longer

### ISSUE THREAD

**Issue by peterjungx** [aws-amplify/amplify-cli#4179]
**Describe the bug**
Updating the Amplify-CLI version to 4.18.1 brought my amplify-based web-app into a corrupt state: The CloudFormation stack is stuck in the state UPDATE_ROLLBACK_FAILED that I need to resolve manually. Besides reporting the issue I would need some guidance on resolving the issue manually without data loss.

I updated my amplify cli to the new version. Upon first invocation of `amplify status` I answered the prompt to update the Nodejs runtime from node8.10 to node10.x with `Yes`. 

I then invoked `amplify push` to update the app's lambdas and cognito (that has the inline lambda `UserPoolClientLambda`). 

During deployment, there then was an unrelated UPDATE_FAILED error in my GraphQL API component, for which there is a closed amplify-cli issue #2626 [here](https://github.com/aws-amplify/amplify-cli/issues/2626), the error message being `Parameters: [CreateAPIKey] do not exist in the template`.

CloudFormation then attempted a rollback, which failed, because the old runtime of the lambdas node8.10 is not supported by AWS Lambda anymore.

As per Amplify docs the resulting `UPDATE_ROLLBACK_FAILED` state needs to be resolved manually. According to what I have read, the only way to get out of this state is to either complete the rollback (which in this case is not possible, because the template I want to roll back to cannot be changed and the settings in that template are not supported anymore) or to delete the stack. (Is this understanding correct?)

This happened to me in my test env, so I do not have a problem with deleting that stack. The prod env is still untouched and runs the node8.10 runtime. The problem is that the User accounts of our customers that cognito holds would be lost when we delete the prod stack, so we need a reliable way of updating the prod env, but no way to test because we do not have a working replica of the prod stack anymore. 

**Amplify CLI Version**
4.18.1

**Comment by yuth** [comment]
@peterjungx did your API have any change to be pushed before the migration script got triggered?

cc @UnleashedMind

**Comment by peterjungx** [comment]
No. I did not make any changes to the schema and `amplify status` showed `No Change` in the Operation column in the Api categories.

**Comment by UnleashedMind** [comment]
Try to use the steps pointed out in this issue #3792 to first bring the stack back to a COMPLETE status, we can then work to upgrade the node version.

**Comment by peterjungx** [comment]
@UnleashedMind Thank you for the response! You pointed me in the right direction and the problem is solved.

The steps here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-continueupdaterollback.html#nested-stacks did bring me on the right track. I gained a better understanding of what is going on in continue update rollback. This needed three iterations to complete, but I am there.

Afterwards I could solve the update issue with the extra space in the schema as per https://github.com/aws-amplify/amplify-cli/issues/2626 to force template recalc on that part.

Thanks!
