### ISSUE TITLE
[Feature  Request]  Automatic Check for Newer CLI Version

### ISSUE THREAD

**Issue by fuji8bit** [aws-amplify/amplify-cli#4180]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
Since the Amplify Client libraries and the CLI work together, errors can occur when the CLI is out of date.  I've run into issues that are resolved simply by updating the amplify-cli to the latest version.

**Describe the solution you'd like**
I'd like amplify-cli to do an automatic check for a newer version and alert the user if it exists (like some other node packages do).  Perhaps during "amplify init".

**Describe alternatives you've considered**
automatic update is a bad idea, and checking on every CLI command is too much.

**Additional context**
I've seen the problem show itself at "amplify push", where it gives me state errors.

**Comment by yuth** [comment]
@fuji8bit we already have this feature implemented in https://github.com/aws-amplify/amplify-cli/pull/4046 and its pending release.
