### ISSUE TITLE
Should "Email and Phone #" be "Email or Phone #"?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4184]
**Is your feature request related to a problem? Please describe.**
When setting up a new Cognito Userpool through amplify cli, one of the sign up options is "Email and Phone #". Does that mean user has to enter both email and phone # or one or the other? Not clear. 

The Cognito UI is much clearer than that: 

<img width="471" alt="User Pools - Amazon Cognito 2020-05-06 11-45-50" src="https://user-images.githubusercontent.com/81853/81210473-2873e280-8f8f-11ea-8853-89b157db618a.png">

**Describe the solution you'd like**
More clear language in the option or through the "I want to learn more"

**Comment by yuth** [comment]
@hisham  Thanks for the feedback. It means User can use either email or phone number as their login name as shown in the screenshot.

**Comment by brene** [comment]
@hisham - thanks for reporting this. I've got a PR out to address this issue.
