### ISSUE TITLE
Default to case insensitive usernames and emails in cognito? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4185]
**Is your feature request related to a problem? Please describe.**
Looks like cognito has a new property to make usernames and emails case insensitive. See https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-service-now-supports-case-insensitivity-for-user-aliases/ and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html

**Describe the solution you'd like**
It seems like this should be default when amplify cli sets up auth. It looks like Cognito service will make this default eventually.

**Comment by lukeramsden** [comment]
Definitely +1 from me, in fact I'd love if somebody could enlighten me as to a scenario where case sensitive usernames/emails are ever a good idea? Especially emails. Seems weird to me that it's even an option in Cognito.

**Comment by renebrandel** [comment]
@hisham @lukeramsden - agree. We will make this change. cc @asmajlovicmars

**Comment by attilah** [comment]
Fixed in: https://github.com/aws-amplify/amplify-cli/pull/6065

**Comment by Stvad** [comment]
agh, missed this by a few weeks and there is no way to update existing pool :(
