### ISSUE TITLE
Can't delete and create auth category at same time

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4186]
**Describe the bug**
I'm playing around with adding an auth category. Ended up pushing one, but need to change some immutable attributes so deleted it and creating a new one, so now queued up, I have one create and one delete to be pushed to aws. 

Running amplify push fails however with the following: 

```
CREATE_FAILED      amplify-... AWS::CloudFormation::Stack Wed May 06 2020 12:15:34 GMT-0600 (Mountain Daylight Time) The following resource(s) failed to create: [SNSRole].                                                                                                                                                  
CREATE_FAILED      SNSRole                                                           AWS::IAM::Role             Wed May 06 2020 12:15:34 GMT-0600 (Mountain Daylight Time) snshishamdev-hishamdev already exists in stack arn:aws:cloudformation:us-east-1:9142...:stack/amplify-...
```

**Amplify CLI Version**
4.18.1

**Expected behavior**
Should just work. To workaround, I had to delete and add in two separate pushes.

**Comment by ammarkarachi** [comment]
@hisham This should be fixed in the release 4.20
