### ISSUE TITLE
Merge additions to configuration file without destroying customer updates

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/amplify-cli#419]
**Is your feature request related to a problem? Please describe.**
Yes - The JavaScript library and iOS/Android SDKs rely on `aws-exports.js` and `awsconfiguration.json` to interact with services not only managed through the CLI, but also independent resources they created in their AWS account. In some situations today a customer might add something (like Kinesis information) and then run `amplify add auth` which would overwrite the configuration file.

**Describe the solution you'd like**
Union the customer provided configuration along with the Amplify CLI controlled config into the same file, with neither negatively impacting the other.

**Describe alternatives you've considered**
Manually copying everything before running Amplify CLI commands.

**Additional context**
Out of scope is the use case when a customer provides resource information (Cognito, AppSync, etc.) that the Amplify CLI provides as well. In these cases where there is conflict we should default to not overwriting the customer information.

**Comment by kaustavghosh06** [comment]
@undefobj We added this feature as a part of the latest version of the CLI :)

**Comment by brataaaan** [comment]
@kaustavghosh06 Could you please give an example of how this works now? Don't find an example in the docs. :-)
