### ISSUE TITLE
Customizing appsync functions created by @function directive

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#4192]
**Which Category is your question related to?**
API, GraphQL

When using the @function directive, it creates the AppSync function with the data source as the lambda function, but the resolvers are static and cannot be overwritten (according to what I see), they are created inside `build/pipelineFunctions`.

I want to find a way to change that resolver, so for example I want to handle errors in a custom way, that allows me to send custom data when I throw errors. Is there a way to do that other than going to the AppSync console and manually changing the resolver?

**Amplify CLI Version** 
4.18.0

**Comment by idanlo** [comment]
The source of this problem is here - https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-function-transformer/src/FunctionTransformer.ts#L133 as you can see this function creates the resolver with static content, but maybe there is an option to overwrite it, like when creating resolvers in the `resolvers` folder overwrites existing resolvers (doesn't work in this use case).

**Comment by davekiss** [comment]
Related, would it somehow be possible to provide pipeline templates without `@function` that can still be used as a resolver for a `@model` even before any pipeline transformers are available?

Getting desperate for generated pipeline functionality and this is a great first step
