### ISSUE TITLE
graphql api uses cognito userpool created outside of amplify project

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#4197]
**Is your feature request related to a problem? Please describe.**
Please improve support for graphql apis that use cognito user pools created outside the amplify project.

One success story is that I was able to get Amplify to be flexible. I had low expectations, but Amplify impressed me when I wanted to:
1.	Make a GraphQL Api with amplify
2.	That uses a cognito user pool created outside of the amplify project

**Describe the solution you'd like**
Solutions include:
1. always allowing manual configuration like what is (barely) possible today.
2. have the cli interview support the option to use a cognito user pool per environment.
3. allow environment-specific uses of different cognito user pools.

**Describe alternatives you've considered**
I have not considered alternatives.

**Additional context**

These notes helped me, but I want to be sure they will be possible going forward.
https://github.com/aws-amplify/amplify-cli/issues/779#issuecomment-597837742

**Comment by renebrandel** [comment]
Hi closing this item as it is addressed via the import auth feature we've launched a while back. See: https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/
