### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource - Running from Lambda

### ISSUE THREAD

**Issue by voojo** [aws-amplify/amplify-cli#4200]
**Describe the bug**
I am trying to send an email using AWS SES that was configured using Amplify and is run from Lamda. I keep default CORS configs that are automatically generated while creating the function but still getting error:

`Access to XMLHttpRequest at 'https://xxx.execute-api.region_xxx.amazonaws.com/Prod/sendEmail' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Looks like those CORS settings are not being attached to the response config (screenshot from console/Network): 
![image](https://user-images.githubusercontent.com/9327144/81278319-cc27c600-9055-11ea-985c-4573470f38d6.png)

**Lamda code snippet**
```js
// Enable CORS for all methods
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});`

**calling it here:**

`
app.post('/sendEmail', async (req, res) => {
  const { emailAddress, emailSubject, emailBody } = req.body;

  try {
    ses.sendEmail(
      {
        Source: config.adminEmail,
        ReturnPath: config.adminEmail,
        Destination: {
          ToAddresses: [config.adminEmail]
        },
        Message: {
          Subject: {
            Data: ""
          },
          Body: {
            HTML: {
              Charset: "UTF-8",
              Data: `${emailBody}`
            }
          }
        }
      },
      (err, data) => {
        if (err) {
          console.log(err)
        } else {
          res.json({
            message: "Success!",
            data,
            req
          })
        }
      }
    )
  }
  catch (err) {
    res.status(500).json({ error: err })
  }

});
```

This issue looks the same but it was closed without solution: [(https://github.com/aws-amplify/amplify-js/issues/4721 )]

**Comment by ammarkarachi** [comment]
@voojo What's the error you get when you execute it in a non browser environment?

**Comment by voojo** [comment]
@ammarkarachi I am getting internal server error message and HTTP error 502 - Bad Gateway. Email is coming through tho but either via Postman or in a browser I am getting errors.

**Comment by ammarkarachi** [comment]
Hi @voojo, We will need more information on what steps you used to create the API. Are you using the Amplify API category the provision the resources?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
