### ISSUE TITLE
Get all input (Y|N) in the very beginning on amplify push

### ISSUE THREAD

**Issue by fatjoni** [aws-amplify/amplify-cli#4205]
Since it takes long time to amplify push, i find my self that i am waiting doing something else while it has stopped asking me  
?Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?

It would be great if i could confirm or deny these in the beginning and have some peace of mind.

**Comment by ammarkarachi** [comment]
@fatjoni `amplify push --yes` would confirm all prompts

**Comment by fatjoni** [comment]
Thanks a lot!
