### ISSUE TITLE
S3 usage assumes commercial AWS partition

### ISSUE THREAD

**Issue by kastork** [aws-amplify/amplify-cli#4213]
**Describe the bug**

The initialization process creates an S3 bucket for deployment of artifacts like lambdas, cf templates, etc.

Then in many places in generated json and yml files, that bucket is referred to.  These generated references all start out with `https://s3.amazonaws.com/...`

That URL won't work if you are in a partition such as the US Gov cloud (or, I assume, any of the China partitions) because the bucket wasn't created in the commercial partition.

**Amplify CLI Version**
1.38.0

**To Reproduce**

* Initialize a project.
* Add the Auth module choosing to include some lambdas and auth queries
* push

**Expected behavior**

The push succeeds

**Actual behavior**

```bash
An error occurred when pushing the resources to the cloud

S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
An error occured during the push operation: S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```

**Desktop (please complete the following information):**
 macos Catalina
node 12.16.3

**Additional context**

**Comment by UnleashedMind** [comment]
The Amplify CLI currently only support these regions: 

  'us-east-1': 'US East (N. Virginia)',
  'us-east-2': 'US East (Ohio)',
  'us-west-2': 'US West (Oregon)',
  'eu-west-1': 'EU (Ireland)',
  'eu-west-2': 'EU (London)',
  'eu-central-1': 'EU (Frankfurt)',
  'ap-northeast-1': 'Asia Pacific (Tokyo)',
  'ap-northeast-2': 'Asia Pacific (Seoul)',
  'ap-southeast-1': 'Asia Pacific (Singapore)',
  'ap-southeast-2': 'Asia Pacific (Sydney)',
  'ap-south-1': 'Asia Pacific (Mumbai)',

**Comment by SwaySway** [comment]
Closing this issue as the CLI currently does not support GovCloud regions.
