### ISSUE TITLE
Add support for 'PreventUserExistenceErrors'

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4214]
Cognito supports this setting (PreventUserExistenceErrors) which will prevent cognito from disclosing to the frontend whether a user exists in the userpool or not. 

Does not look like amplify cli supports this setting. It can be added in the cloudformation file manually but the cli will reset it if 'amplify update auth' is run.

**Comment by LoganArnett** [comment]
Is this underway or can I open a PR for this?

**Comment by josefaidt** [comment]
Hey :wave: this can now be accomplished with the use of [overrides](https://docs.amplify.aws/cli/auth/override/)! Using the following override we are able to enable PreventUserExistenceErrors

```ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPoolClient.addPropertyOverride(
    'PreventUserExistenceErrors',
    'ENABLED'
  )
}
```

![image](https://user-images.githubusercontent.com/5033303/206056436-1eba0862-0ba4-4e44-857b-07276cd7a399.png)

Closing issue 🙂
