### ISSUE TITLE
S3 mock failed to list file key in Windows

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#4222]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
In the Windows system, launch amplify mock and open the url http://localhost:20005/becketname-env. It returns the following result. The key are all undefined. This issue only happens in Windows for me.
![16421589210313_ pic_hd](https://user-images.githubusercontent.com/9857112/81588171-1f678480-9386-11ea-997d-af8514a17680.jpg)
 

**Amplify CLI Version**
4.18.1

**To Reproduce**
create a amplify project with S3 storage
add some files to the S3 storage
amplify mock
visit http://localhost:20005/becketname-env in the browser

**Expected behavior**
key shows the file name

**Screenshots**
see it above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 12

**Comment by akshbhu** [comment]
Hi @gaochenyue 

To reproduce this can you also tell me the aws-amplify and aws-amplify-react libs version you are using?

**Comment by gaochenyue** [comment]
@akshbhu I'm using Amplify Cli 4.18.1. I use Vue.js, but this issue can be reproduced without frontend. To reproduce, you just have to start mock and visit http://localhost:20005/becketname-env in the browser.

**Comment by akshbhu** [comment]
Hi @gaochenyue 

Thank you for your patience and apologies for the delay.I want know the aws-amplify lib version to reproduce this error as there is some changes in lib version from 2.x to 3.x.

**Comment by gaochenyue** [comment]
@akshbhu no problem.
Here are all my amplify related libs
'''
        "@aws-amplify/api": "^2.1.2",
        "@aws-amplify/pubsub": "^2.1.2",
        "aws-amplify": "^2.2.1",
        "aws-appsync": "^2.0.0",
'''

Thanks
