### ISSUE TITLE
When changing username case sensitivity I get: "Updates are not allowed for property - UsernameConfiguration"

### ISSUE THREAD

**Issue by simeon-smith** [aws-amplify/amplify-cli#4227]
**Describe the bug**
When trying to use the new
```
      UsernameConfiguration:
        CaseSensitive: false
```
CloudFormation attribute for the UserPool in the cloud formation template I get `Updates are not allowed for property - UsernameConfiguration`

**Amplify CLI Version**
4.19.0

**To Reproduce**
Add the attribute to the users cloud formation template.

**Expected behavior**
I should be able to update this attribute. I'm using emails and need to make them case insensitive.

**Additional context**
Deleting and recreating the user pools (suggested here: https://github.com/aws-amplify/amplify-cli/issues/3494#issuecomment-598194358) is not feasible. This is an active production application.

**Comment by UnleashedMind** [comment]
It is due to restrictions from the Cognito that updates on those properties are not allowed, the Amplify CLI prints out warning messages about the restrictions when the auth category is first added into the project.

**Comment by simeon-smith** [comment]
Is there somewhere I can report this as an issue? The restriction is an issue.

**Comment by brene** [comment]
@simeon-smith can you file a support ticket through the AWS Console? That'll be the best way to reach the right team.

**Comment by yogeshwar607** [comment]
@simeon-smith got any solution ?
