### ISSUE TITLE
DataStore/Conflict Detection not support _TTL in ElasticSearch

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4228]
**Describe the bug**
The new 4.19.0 version of the CLI implemented a fix to allow DynamoDB records with a _version field to stream to ElasticSearch by enabling external versioning. I tested created and update and this works fine.

However, when we delete a record in AppSync it adds a _deleted=true field and a _ttl field with an epoch time 30 days out. The _ttl field is, similar to _version, a meta_data field in ElasticSearch so the deleted record does not stream to ElasticSearch so the record remains "undeleted" in ElasticSearch forever.

In CloudWatch the following error shows up when you try to stream a deleted record:

            "status": 400,
            "error": {
                "type": "mapper_parsing_exception",
                "reason": "Field [_ttl] is a metadata field and cannot be added inside a document. Use the index API request parameters."
            }

**Amplify CLI Version**
 4.19.0

**To Reproduce**
With conflict detection enabled use the delete*( ) resolver to delete a record - the deleted record will fail to stream to ElasticSearch

**Expected behavior**

I expect the deleted record to stream to ElasticSearch. We can't have a record that is flagged as deleted in DynamoDB showing as not deleted in ElasticSearch.

This is related to issue #3796 that has been closed.

**Comment by sacrampton** [comment]
Hi @yuth , @ammarkarachi , @kaustavghosh06 , @undefobj , @edwardfoyle - this is a critical problem that still means that you can't use ElasticSearch with conflict detection enabled.

I'd suggest a valid fix that should be achievable would be to modify your streaming lambda to strip out the _ttl attribute when you send it to ElasticSearch. There is no need to use ElasticSearch's own _TTL since DynamoDB will do that and send the delete to ElasticSearch (from what I understand). So as long as you are not streaming the _ttl field to ElasticSearch it should work fine.

https://www.elastic.co/blog/ttl-documents-shield-and-found

**Comment by sacrampton** [comment]
Hi @yuth , @ammarkarachi , @kaustavghosh06 , @undefobj , @edwardfoyle , @UnleashedMind 

Sorry to keep bugging you on this - but this is a critical issue. You delivered a partial fix to ElasticSearch synchronization under #3796 (which is now closed), but since it fails on delete then this means we still can't move forward with DataStore (remain dead in the water here).

Hope you can take a look at this bug - and at least update its status that it is a bug and needs an urgent fix.

Thanks

**Comment by brene** [comment]
@sacrampton - apologies for not providing an update earlier. @SwaySway is actively looking into this as we speak.

**Comment by sacrampton** [comment]
Which version of the CLI has this been implemented in? Thanks

**Comment by SwaySway** [comment]
Hello @sacrampton
This fix is currently in queue for the next release, after ver 4.20.

**Comment by sacrampton** [comment]
Any estimate on when 4.21 will release?

**Comment by ammarkarachi** [comment]
Hi @sacrampton, We released 4.21 today morning

**Comment by sacrampton** [comment]
Hi @ammarkarachi  - thanks, will start testing it asap

**Comment by sacrampton** [comment]
Hi @ammarkarachi  - I have just got to testing this now - had to stand up a completely separate instance to sort these things out.

The behaviour you have implemented in this solution is to delete the record in ElasticSearch rather than set a _deleted and _ttl flag in ElasticSearch - so ElasticSearch will only have the non-deleted records and DynamoDB will have the deleted and live records.
