### ISSUE TITLE
Custom GraphQL schema directives

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-cli#4229]
**Which Category is your question related to?**
AppSync

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.13.1

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
Does AppSync support custom graphql schema directives? Or are we limited to the [directives](https://docs.amplify.aws/cli/graphql-transformer/directives) mentioned in the amplify cli docs?

**Comment by yuth** [comment]
AppSync does not support custom graphql directives. You can add support for the custom directives in Amplify CLI by writing custom graphql transformer plugin which can add additional logic to the request and response mapping template used by AppSync
