### ISSUE TITLE
type definition for query and mutation only a part of the fields

### ISSUE THREAD

**Issue by gankkank** [aws-amplify/amplify-cli#423]
** Which Category is your question related to? **

type definition for query and mutation

** What AWS Services are you utilizing? **

appsync, graphql

** Provide additional details e.g. code snippets **

I want:

1. `create` allow field `file` and `otherParam`, but not `id` field

2. `update` only allow `otherParam`

3. `list` to have field `id` 

The following code snippet is not working.

If I defined `id`field in type, `create` will allow the user to set id. If I remove id field, `list` query will also remove `id` field.

And how can I set only to allow certain fields in update mutation?

```
type Identity @model @auth(rules: [{ allow: owner, identityField: "sub" }]) {
    id: ID!
    file: String!
    otherParam: String
}
```

**Comment by mikeparisstuff** [comment]
Unfortunately this support is not yet possible, however, it will be when support for custom resolvers is finished in the CLI. In the future you will be able to remove the auto-generated update mutation and then create your own update mutation yourself. I have recorded this issue as another feature request for custom resolvers.

**Comment by kaustavghosh06** [comment]
Closing this issue as duplicate since it's tracked in #574
