### ISSUE TITLE
Amplify gets an appClientId from nowhere and now can't update the stack

### ISSUE THREAD

**Issue by danielfranca** [aws-amplify/amplify-cli#4233]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm developing an application using Amplify
Everything was doing fine, I have done some changes on my `dev` environment to include Social login, and it was working fine locally

Then when I tried to deploy using Amplify Console CD it was failing, after digging into it I found the solution [here](https://github.com/aws-amplify/amplify-console/issues/206) using a custom script for the `amplify simplepush`

Just to put this on context

After having everything working again, I was happy to push my changes to `staging`
So, I have changed my branch, checkout the `staging` environment and tried to push

And then I got stuck in an error raised saying that it can't find the AppClientID

> Resource Name: XXXXXXXXXXX (AWS::Cognito::UserPoolClient)
Event Type: update
Reason: User pool client does not exist. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: YYYYYYYYYYYYYYYYYY
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/xxxxxxxxxxx

The URL goes to a **The page you are looking for does not exist.** page
The client Id, true, it doesn't exist, and I have no idea why it is trying to update it

So I looked at both
`amplify/#current-cloud-backend/amplify-meta.json`
and 
`amplify/backend/amplify-meta.json`

Both contain a line of code like this (on the auth->output section):

    "AppClientID": "XXXXXXXXXX"

The `#current-cloud-backend` is supposed to come from the cloud, so I'm not supposed to touch it, but I have no idea how it did get that code, the `dev` appClient is not this code either.

So, I tried changing the code to (on the `amplify/backend/amplify-meta.json` file):
    "AppClientID": "MY-VALID-ID"

and then pushing again

But the error continues, and then the `amplify/backend/amplify-meta.json` was updated with the wrong id again

I thought about running `amplify push -f`, but I'm afraid it is gonna mess things up

Any idea what might be causing it and how to fix it?

**Amplify CLI Version**
4.19.0

**To Reproduce**
> Resource Name: XXXXXXXXXXX (AWS::Cognito::UserPoolClient)
Event Type: update
Reason: User pool client does not exist. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: YYYYYYYYYYYYYYYYYY
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/xxxxxxxxxxx

**Expected behavior**
The correct Cognito UserPoolClient should be fetched and update accordingly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - 13.13.0

**Additional context**

**Comment by UnleashedMind** [comment]
"AppClientID" is the cognito user pool app client id, seems like it's from another environment, and not recognized in the `staging` backend env. 
Could you describe in more details on what happened "So, I have changed my branch, checkout the staging environment and tried to push"? 
What you can try is in the same local git branch, run `amplify env checkout staging`, and then run `amplify status` to make sure the auth is in the `create` status, and then run `amplify push`

**Comment by danielfranca** [comment]
I have looked at all my environments, none of them has this code on an appClientId of Cognito

I had run `amplify pull --restore`, and apparently this weird appClientId is already on the cloud somehow, because it shows up on my `amplify-meta.json` even after restore.

I had an authentication before, only not with social providers, so it won't be on `create` mode, only update.
If I go on my dev branch and run `amplify env checkout stg` I'm asked to input my oauth key/secrets for Facebook/Google login, after doing that running `amplify status` I do see

> | Auth     | myApp             | Update    | awscloudformation |

Every time I try to push I get the error above, telling me the resourceId of the userPoolClient was not found, even after manually changing the value on the `amplify-meta.json` file

**Comment by danielfranca** [comment]
There is something really bad with my setup
After restoring my staging env with `amplify env pull --restore`
I decided to apply only my changes on the API, So I merged only a branch that I was working on changes on the API
Then I checked amplify status, which showed correctly that only the API has changed

Then tried to push it `amplify api push`

And I got a weird error
>UPDATE_FAILED      authmyapp                 AWS::CloudFormation::Stack Tue May 12 2020 21:15:53 GMT+0200 (Central European Summer Time) Parameters: [userPoolGroupList, resourceNameTruncated, dependsOn] must have values

I tried to grep `userPoolGroupList` trying to make sense of this error message, but no success, no idea why it did even tried to do something on auth again if I was just pushing changes on the API.

**Comment by danielfranca** [comment]
I did:
`aws cognito-idp describe-user-pool-client --user-pool-id <region-poolId> --client-id <INVALID ID>` On all my user pools, none of them have this userpool client id
But everytime I do a pull restore my `amplify-meta.json` gets updated with: `"AppClientID": "INVALID ID"`

Something like
```
    "auth": {
        "myproject": {
            "service": "Cognito",
            "providerPlugin": "awscloudformation",
            "output": {
                "GoogleWebClient": "111111111.apps.googleusercontent.com",
                "AppClientSecret": "aaaaaaaaaaa",
                "UserPoolId": "region-pooId",
                "AppClientIDWeb": "VALID ID",
                "AppClientID": "INVALID ID",
                "FacebookWebClient": "2222222222",
                "IdentityPoolId": "region:Id",
                "IdentityPoolName": "myproject__env",
                "UserPoolName": "mypoolname"
            },
            "lastPushTimeStamp": "2020-05-13T20:48:29.797Z",
            "providerMetadata": {
                "s3TemplateURL": "https://s3.amazonaws.com/myproject-deployment/amplify-cfn-templates/auth/lexis-cloudformation-template.yml",
                "logicalId": "authmyproject"
            },
            "lastPushDirHash": "XXXXXXXXXXXXXX="
        }
    },
```

**Comment by danielfranca** [comment]
I tried going on full rad mode now and checked the S3TemplateURL that it shows on the amplify-meta file
I thought that maybe that is where it was getting the invalid id, maybe that was Amplify "point of truth"... so, I have changed the id there, crossed my fingers and did a pull.... 
Nope, back to the invalid one

**Comment by danielfranca** [comment]
Could someone help me with that? My deployment is blocked due to this issue
@UnleashedMind

**Comment by danielfranca** [comment]
What I believe has happened is the following:

I have added auth to my amplify project months ago
Eventually, I noticed one of the created clients were not being used, so I have deleted it from the console.
I had not updated the auth during months
Now that I have introduced the social authentication Amplify tried to update and because of hte client Id not existing anymore it can't.

Should have a way to make Amplify aware of this removal and not try to update it

**Comment by brene** [comment]
@danielfranca - we're looking into this issue now. We need some more details from you. Are you able to go over this on a chat? Can you DM me on twitter to align on a good time? https://twitter.com/renebrandel

**Comment by danielfranca** [comment]
@brene Hey, thanks
Two things, I don't have Twitter, but for me, it works any time after 5:30 pm CEST
Can we use another tool? If there's no other way I can make a throwaway account just for that.
And, I have just created a ticket on AWS support :'( What is the best way to coordinate it, so you don't duplicate efforts?

**Comment by brene** [comment]
@danielfranca you can alternatively join our discord community here: https://discord.gg/jWVbPfC to chat with me 1:1 (AFAIK, you don't need to sign-up for it and can just join as guest)

**Comment by UnleashedMind** [comment]
@danielfranca 
Could you zip up your amplify folder and send it to us? 
amplify-cli@amazon.com

**Comment by danielfranca** [comment]
@UnleashedMind Just did :)

**Comment by danielfranca** [comment]
Should I try the hack we discussed, changing the deployment bucket, or should I wait a bit more?

**Comment by danielfranca** [comment]
bad luck, your anti-virus engine didn't like the attachment:

```
The message (MID 758444620) could not be fully scanned by the anti-virus engine.

And, This message timed out during scanning.

Actions taken:
    Message quarantined
```

**Comment by danielfranca** [comment]
Maybe I can send it over Discord?

**Comment by UnleashedMind** [comment]
I'm sending you an email

**Comment by danielfranca** [comment]
@UnleashedMind 
I've tried the hack
* Went to the S3 Deployment Bucket
* Downloaded the `#current-cloud-backend.zip`
* Replaced the wrong clientId with the correct one
* Uploaded it
* Replaced the `appClientId` with the correct one on my local `amplify/backend`
* Double checked that there is no more reference to this Id elsewhere
* Tried to push it again

As soon as the push starts running I can see that the clientId is set back to the wrong one on my local backend (not in the cloud one)
And then I get the same error again

I've uploaded my amplify folder to Firefox Send, as soon as I get your email I'll email back with the link/password.

**Comment by danielfranca** [comment]
I'd workaround it creating a new environment, copying everything on my DynamoDb Tables to the new ones, copying my S3 bucket storage, and re-creating the users.

This was not ideal, of course, but as it is still not in production it could be done without much disruption. However, I would like to understand this issue to avoid this happening on a production environment, which would lead to way worse consequences to the users.

**Comment by UnleashedMind** [comment]
Because the Amplify CLI uses CloudFormation to create the AWS resource, and If you delete a resource from an AWS CloudFormation stack, then you must remove the resource from your AWS CloudFormation template. Otherwise, your stack fails to update, and you get an error message. 

For this particular case, you removed the User Pool App Client,  which was depended on by multiple other resources, so removing it from the template became very complicated. And the CLI has the pull operation before push, which will revert your local changes and make things even harder to recover. 

So, try not to manually update or delete the resources created by the Amplify CLI, specially in the production environment, it can be very hard to recover.

**Comment by UnleashedMind** [comment]
@danielfranca 
Are you still blocked?  Let us know what else we can help.

**Comment by danielfranca** [comment]
I understand that, but mistakes happen and would be nice if we can import external changes into the CloudFormation stack, or even do some kind of dry run in order to sync the environments.

I'm not blocked anymore, because I have created a new environment.

**Comment by ammarkarachi** [comment]
@danielfranca thanks for the update, let us know if you need any more assistance.
