### ISSUE TITLE
Amplify Mock doesn't delegate all environment variables?

### ISSUE THREAD

**Issue by StefanV85** [aws-amplify/amplify-cli#4234]
**Describe the bug**
When i have an Lambda Function in my Project and simulate the call via "amplify mock function" or in combination with an GraphQL API and "amplify mock" (Trigger the Lambda via Amplify GraphQL Explorer) i doesn't have access to all my environment variables.

As far as i know, amplify doesn't support handling of environment variables. 
But i would expect that all my environment variables of the current operating system (windows) are accessible. 
Some Environment Variables are delegated to the Lambda Function Call.
I have access to the following ones: 
HOMEDRIVE
HOMEPATH
LOGONSERVER
PATH
REGION
SYSTEMDRIVE
SYSTEMROOT
TEMP
USERDOMAIN
USERNAME
USERPROFILE
WINDIR

But this is just an subset of my environment variables on my system. 
We aren't all environment variables accessable? And could anyone tell me the place where the environment variables are defined which are delegated?

Kind Regards
Stefan

**Amplify CLI Version**
4.18.0

**To Reproduce**
amplify init
amplify add function
amplify mock function
 ==>The Lambda doesn't have all environment variables. 

**Expected behavior**
Access to all Variables which are defined in the local system

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.14.1

**Comment by ammarkarachi** [comment]
@StefanV85 We don't currently set any system but I will mark this as a possible enhancement.

**Comment by StefanV85** [comment]
@ammarkarachi thanks for your answer.

But when i run the function locally via "amplify mock" i would assume that i can access all my local environment variables out-of-the-box. Or why should it be necassary that the amplify framework set the variables explicitly?

For example: My Lamda Function looks like this: 
`AWS = require('aws-sdk');
exports.handler = async (event, context) => {
    console.log(Object.keys(process.env).length);
    console.log(JSON.stringify(process.env));
    return null;
};` 

The first console.log should log the number of environment variables which are available.
if i run "amplify mock function ...." in the terminal, it tells me that i have 13 environment variables. which are defenetly not all of my local environment variables.


**Now the interresting thing:** 
If i configure a launch configuration in visual studio code, to be able to debug the amplify mock
`    {
        "type": "node",
        "request": "launch",
        "name": "Amplify Mock",
        "program": "${env:APPDATA}/npm/node_modules/@aws-amplify/cli/bin/amplify",
        "args": [
          "mock",
          "function",
          "MyLambdaFunction",
          "--event",
          "./src/event.json"
        ],
        "console": "integratedTerminal" 
    }`

And let Visual Studio start this launch configuration, i also execute the lambda function locally, BUT NOW i have 60 environment variables. All my local environment variables are accessible.

i doesn't have a clue, what makes this difference... Do you have an idea?

Kind Regards
Stefan

**Comment by ammarkarachi** [comment]
Hi @StefanV85, The mock function is ran in a separate process from the one on which the CLI is currently running and it doesn't have access to the same process variables.

**Comment by cyrfer** [comment]
I need a variation of this. I don't really desire for my local system's environment variables to leak into the local Lambda execution environment. But what I do need is for the local Lambda execution environment to provide the environment variables expected when in the cloud.

I mentioned this in #4635 which was closed in favor of this ticket, but I see them as different, even competing, goals.

**Comment by thomasklein-winemaker** [comment]
Thus I understand that for mocking it is expected to hardcode in the values of the env variables?

**Comment by cyrfer** [comment]
@thomasklein-winemaker that is the only thing I've been able to do reliably. I keep a version of my lambda configuration outside of my repo so I can swap it in for local testing, and then revert before pushing to aws.

**Comment by montycheese** [comment]
+1 This issue prevents our team from being able to use the mock feature as we depend on env variables to init the AWS Config among other things.

**Comment by montycheese** [comment]
I was actually able to inject ENV variables while running `amplify mock function <lambdaname>` by prepending the env variables in the CLI

e.g. 

`ENV=beta TABLE_NAME=Foo amplify mock function LambdaName`

**Comment by edwardfoyle** [comment]
We have made several improvements to mock in the latest version of the CLI. We have modified the behavior to NOT leak any system environment variables into the mock process (to be more consistent with the environment that will be available when executing in the cloud). But we have also implemented a .env file escape hatch where you can provide custom environment variables to the mock process if you want. You can read more documentation on this here: https://docs.amplify.aws/cli/usage/mock#function-mock-environment-variables

**Comment by mgarabedian** [comment]
Thanks for pointing this out @edwardfoyle.  This is a good addition.
