### ISSUE TITLE
Removing permissions for existing storage from Lambda breaks push

### ISSUE THREAD

**Issue by AbirAbbas** [aws-amplify/amplify-cli#4239]
**Describe the bug**

I've removed access to a table in my lambda function using amplify function update workflow, in doing so now I can't push as I get the error Parameters [storageTableName, storageTableArn] do not exist in the template (which is obviously not supposed to exist as I removed access to the table for this lambda function)

**Amplify CLI Version**
4.18.1

**To Reproduce**
amplify update function
remove access to an existing table

**Expected behavior**
Once access is removed the lambda function should be updated and environment variables for that table should be removed.

**Comment by AbirAbbas** [comment]
Currently I had to add back access to the table to get my amplify push working again.

**Comment by edwardfoyle** [comment]
Hi @AbirAbbas I was able to repro this bug. Until we can get a fix out, a workaround is to remove the relevant "dependsOn" sections from the `amplify-meta.json` and `backend-config.json` files
```json
"function": {
        "myFunc": {
            "build": true,
            "providerPlugin": "awscloudformation",
            "service": "Lambda",
            "dependsOn": [  // <= remove the relevant element from this list
                {
                    "category": "storage",
                    "resourceName": "myDDBTable",
                    "attributes": [
                        "Name",
                        "Arn"
                    ]
                }
            ]
        }
    }
```

**Comment by edwardfoyle** [comment]
The fix for this has been released. Please install the latest version of the CLI to get the updates.

**Comment by kenbankspeng** [comment]
@edwardfoyle fyi, this bug exists in the latest cli (4.29.7). Only after using your workarounds above was I able to push without the error.
