### ISSUE TITLE
dynamic code path in function cloudformation template

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#4243]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When pushing lambda to the cloud, it always writes the S3Bucket and S3Key to the cloudformation template file. It makes git pop up this file even there is no real change for the lambda function. Why not keep it in the memory instead of writing to the template file.
`"Code": {
					"S3Bucket": "amplify-project-stage-225809-deployment",
					"S3Key": "amplify-builds/project-4f694b5151624f356c64-build.zip"
				}`			

**Amplify CLI Version**
4.18.1

**To Reproduce**

**Expected behavior**
pushing lambda won't change the cloudformation template file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12

**Additional context**

**Comment by kaustavghosh06** [comment]
@gaochenyue Yes this dynamic S3Bucket and key is required in the CloudFormation template for the CloudFormation service to detect for any changes and deploy the Lambda function. We're working on a better way to do this - but at this point this is the way we're handling uploading updates to the Lambda function via Cloudformation.
