### ISSUE TITLE
[MOCK Storage] fails 

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-cli#4244]
**Describe the bug**
Amplify project with auth, api and storage
Working correctly with cloud services.

When running `amplify mock`,  I get the following message: `Mock Storage endpoint is running at http://localhost:20005`

When trying to access that address, I get an `error` message in the terminal and a blank screen in the browser.

**Amplify CLI Version**
4.19.0

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Comment by kaustavghosh06** [comment]
@lambda0xff mock storage doesn't have an UI. It runs on http://localhost:20005 and you can use that endpoint to mock your Client-side API's using the Amplify client libraries.
This tutorial walks you through this  - https://aws.amazon.com/blogs/aws/new-local-mocking-and-testing-with-the-amplify-cli/
