### ISSUE TITLE
[Signing a request from Lambda] Code example from official documentation does not work

### ISSUE THREAD

**Issue by Albert-Gao** [aws-amplify/amplify-cli#4246]
Amplify CLI
4.19.0

The example here: https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda

Does not work:

`const appsyncUrl = process.env.API_BACKENDGRAPHQL_GRAPHQLAPIENDPOINTOUTPUT;`

There is no such env.

The whole env object is like this:

```json
{
    "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
    "AWS_SESSION_TOKEN": "----------",
    "AWS_LAMBDA_LOG_GROUP_NAME": "/aws/lambda/createCompany-dev",
    "LAMBDA_TASK_ROOT": "/var/task",
    "LD_LIBRARY_PATH": "/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
    "AWS_LAMBDA_RUNTIME_API": "127.0.0.1:9001",
    "AWS_LAMBDA_LOG_STREAM_NAME": "2020/05/13/[$LATEST]685a59424d494e2c958dce9cba9a1f93",
    "ENV": "dev",
    "AWS_EXECUTION_ENV": "AWS_Lambda_nodejs12.x",
    "AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2:2000",
    "AWS_LAMBDA_FUNCTION_NAME": "createCompany-dev",
    "PATH": "/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
    "AUTH_TCAUTH_USERPOOLID": "us-east-1_dObUMRljJ",
    "AWS_DEFAULT_REGION": "us-east-1",
    "PWD": "/var/task",
    "AWS_SECRET_ACCESS_KEY": "---------",
    "LAMBDA_RUNTIME_DIR": "/var/runtime",
    "LANG": "en_US.UTF-8",
    "NODE_PATH": "/opt/nodejs/node12/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task",
    "AWS_REGION": "us-east-1",
    "TZ": ":UTC",
    "AWS_ACCESS_KEY_ID": "-------",
    "REGION": "us-east-1",
    "SHLVL": "0",
    "_AWS_XRAY_DAEMON_ADDRESS": "169.254.79.2",
    "_AWS_XRAY_DAEMON_PORT": "2000",
    "AWS_XRAY_CONTEXT_MISSING": "LOG_ERROR",
    "_HANDLER": "index.handler",
    "AWS_LAMBDA_FUNCTION_MEMORY_SIZE": "128",
    "_X_AMZN_TRACE_ID": "Root=1-5ebbe635-5cb952b7289cb418d3fde5b8;Parent=13520c35651f3fbd;Sampled=0"
}
```

**Comment by dabit3** [comment]
For this example you can hardcode the endpoint or set the environment variable manually in the Lambda console.

Supporting custom environment variables is something in the backlog for the CLI.

**Comment by kaustavghosh06** [comment]
@Albert-Gao Did you add permissions for your function using the `amplify add/update function` flow for it to access the GraphQL endpoint?

**Comment by Albert-Gao** [comment]
Thanks for reply guys!

@kaustavghosh06  I added, how to verify that?

@dabit3 I can, but it will not be very scalable. 

- I have 3 env, so one URL for each is 3 URLs for a single function.
- Code sharing. I currently have two customized resolvers. There is no way to share the code but copy and paste or publish a private package.

While this could be simply done from the CLI by providing these at build time.

The last problem is, the documentation looks like it's just there, do we need to update the doc?

Anyway, the doc is already 10x better than previous one, thanks for the great work. :)

**Comment by kaustavghosh06** [comment]
In the docs we mention this "Create a Lambda function with amplify add function and make sure to give access to your GraphQL API when prompted for in the amplify add function flow" and this should access to the Lambda function for the GraphQL API. You don't need to hardcode it.
Can you check your `amplify/function/<function-name>/function-parameter.json` and  see the contents of it? Does it have the permissions for the API set?

**Comment by Albert-Gao** [comment]
```javascript
{
    "permissions": {
        "auth": {
            "tcAuth": [
                "create"
            ]
        }
    }
}
```

Thanks, it's not there.

Since the update procedure doesn't contain updating this part, I removed and re-added the API + function.

Now I can see it in the env object

```json
{
"API_GRAPHQL_GRAPHQLAPIIDOUTPUT": "123qwe",
    "API_GRAPHQL_GRAPHQLAPIENDPOINTOUTPUT": "https://123.appsync-api.us-east-1.amazonaws.com/graphql",
}   
```

The name is different, it is `API_GRAPHQL_GRAPHQLAPIENDPOINTOUTPUT`. not `API_BACKENDGRAPHQL_GRAPHQLAPIENDPOINTOUTPUT`.

Thanks!

**Comment by kaustavghosh06** [comment]
@Albert-Gao This is the syntax basically `API_<API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`. In this case your API_NAME is BACKENDGRAPHQL hence the env var name is `API_BACKENDGRAPHQL_GRAPHQLAPIENDPOINTOUTPUT` We print this out after you go through the amplify function update flow like this for reference:

```
Using service: Lambda, provided by: awscloudformation
? Please select the Lambda Function you would want to update authtrigtes001ae614DefineAuthChallenge
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category api
? Api has 3 resources in this project. Select the one you would like your Lambda to access authtrigtes
? Select the operations you want to permit for authtrigtes create, read, update, delete

You can access the following resource attributes as environment variables from your Lambda function
	API_AUTHTRIGTES_GRAPHQLAPIENDPOINTOUTPUT
	API_AUTHTRIGTES_GRAPHQLAPIIDOUTPUT
	ENV
	REGION
```
I submitted a docs PR for this - https://github.com/aws-amplify/docs/pull/1768 to be more explicit.
