### ISSUE TITLE
Feature Request: Better monorepo support

### ISSUE THREAD

**Issue by lukeramsden** [aws-amplify/amplify-cli#4249]
**Is your feature request related to a problem? Please describe.**
I have 2 front-ends, a React SPA and a React Native app, in one monorepo. I would like to host the React SPA, but also codegen to both projects. I figured out that `.graphqlconfig.yml` can take multiple projects and codegen for API.ts etc works fine for multiple folders, which just leaves `aws-exports.js`

EDIT: `amplify codegen` accepts multiple folders, but `amplify mock` emits error `Codegen support only one GraphQL API per project`. Seems like a bug in `amplify mock`.

**Describe the solution you'd like**
`aws-exports.js` to be generated in to multiple source folders, potentially by `project-config.json` becoming an array?

**Describe alternatives you've considered**
My current solution is to have a script copy `aws-exports.js` from the web workspace to the mobile workspace, but I feel like this is a common enough use-case to warrant first-class functionality.

**Additional context**
I've seen previous issues about multi-project setups, but they seemingly have all been closed with a link to https://docs.amplify.aws/cli/teams/multi-frontend, but I feel like proper support not just for monorepos but also for multiple hosted web frontends would be very useful.

**Comment by renebrandel** [comment]
Hi @lukeramsden - we've created a dedicated guide for monorepo setups: https://docs.amplify.aws/cli/usage/monorepo In addition this RFC might tackle some of the codegen requests: https://github.com/aws-amplify/amplify-cli/issues/6898
