### ISSUE TITLE
Amplify Push Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied)

### ISSUE THREAD

**Issue by rjgleave** [aws-amplify/amplify-cli#4250]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

I was running through the online amplify tutorial. After adding auth, I tried to do 'amplify push'. I received this error on the console: 

Resource Name: vcmkiltzy5gkjkl5b356mnp4jeGraphQLSchema (AWS::AppSync::GraphQLSchema) Event Type: update Reason: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: E01E00EA1D83E1A4; S3 Extended Request ID: o1TjyAOTHt25fnBuJveKTKYJl9G2QyfRWu5UVauMrJeNUaISRtIMMZvF9Z5g2pCQN5siayE8x3c=)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by SwaySway** [comment]
Hello @rjgleave
Did you init this amplify project with a restricted IAM Role?

**Comment by rjgleave** [comment]
Hi Josue…   actually, per the tutorial, I created a new user, which had Admin privileges, for the init process

**Comment by rjgleave** [comment]
Actually, I just ran init again, and I think I picked default….  Could that be the problem?

**Comment by UnleashedMind** [comment]
seems like you also added GraphQL API ? did you manually update any of the files inside the `amplify` folder?

**Comment by SwaySway** [comment]
If you run into any more issues related to this please comment below.
