### ISSUE TITLE
@connection and @auth - When User is not the Owner of the connected item

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4252]
I use two models that are connected with the @connection. 

That all worked out fine. I now use GraphQL in a Lambda to calculate configs and store them into the table. For this to work configs has now got @auth -> iam. 

But now answers can't access it apparently. 

Is there a solution? 

 "aws-amplify": "^2.2.5",

```
type ExamConfig
  @model
  @auth(rules: [{ allow: private, provider: iam }]) {
  id: ID!
  answers: Answer @connection(name: "configs", keyField: "id")
}

type Answer
  @model
  @auth(rules: [{ allow: owner }, { allow: private, provider: iam }])
  @key(
    name: "ByExamId"
    fields: ["exam_id", "createdAt"]
    queryField: "answersByExamIdByDate"
  )
  @key(name: "ByOwner", fields: ["owner"], queryField: "answersByOwner") {
  id: ID!
  owner: String!
  exam_id: String!
  config: ExamConfig @connection(name: "configs", keyField: "exam_id")
  createdAt: String
  updatedAt: String
}
```

**Comment by UnleashedMind** [comment]
do you mean the Lambda function can't access the answers? 
How did you set the execution role's policy for the Lambda function?

**Comment by davidbiller** [comment]
> did you mean the Lambda function can't access the answers?
> How did you set the execution role's policy for the Lambda function?
> 
> BTW, there’s an error in the schema, in line 5 of type ExamConfig it should be `answers: [Answer]`

@UnleashedMind 
Nope. I guess the AppSync Resolver cant access the ExamConfig anymore.

**Comment by UnleashedMind** [comment]
how did you try to access the GraphQL API? does client (such as AppSync client) have the proper credential setup?

**Comment by davidbiller** [comment]
> how did you try to access the GraphQL API? does client (such as AppSync SDK) have the proper credential setup?

@UnleashedMind 
throught the amplify sdk yes. 

Answers are there in the response, but the field config is null with message: access denied

```export const answersByOwner = /* GraphQL */ `
  query AnswersByOwner(
    $owner: String
    $sortDirection: ModelSortDirection
    $filter: ModelAnswerFilterInput
    $limit: Int
    $nextToken: String
  ) {
    answersByOwner(
      owner: $owner
      sortDirection: $sortDirection
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        owner
        exam_id
        config {
          id
          item_count
          zscore_mean
          zscore_deviation
          heighest_score_answer
        }
        updatedAt
      }
      nextToken
    }
  }
`;```

**Comment by SwaySway** [comment]
Hello @davidbiller 
Are you running a lambda function to trigger an AppSync operation?
If so we do have documentation for setting that up.
Docs: https://docs.amplify.aws/cli/function#graphql-from-lambda

This goes over how to properly call your GraphQL operation as the amplify library does not support Node.

**Comment by SwaySway** [comment]
Closing this issue due to lack of response. Should you have any further issues please comment below to re-open.
