### ISSUE TITLE
File uploads without auth/user sign in

### ISSUE THREAD

**Issue by roballsopp** [aws-amplify/amplify-cli#4253]
I'd like to set up file uploads from my mobile app with amplify, but I don't want to require any kind of user sign in/account creation. I'm currently just using an api key to get things into dynamo, and I'd like to stick with that if possible. When I follow any documentation I can find to setup S3 storage (including the Advanced Workflows docs [here](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/js)), it always seems to require that I setup some sort of user auth/sign in process. Is it possible to just use my existing api key to make this happen?

**Which Category is your question related to?**
Storage

**Amplify CLI Version** 
4.18.1

**Comment by UnleashedMind** [comment]
You need to follow the steps listed in the [document](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/js#complex-objects) to setup `Complex object` workflow. 
You can not use an existing AppSync API key to authorize access to a separate S3 storage category resource.

**Comment by roballsopp** [comment]
Ok thanks. I found some more detail about this in https://github.com/aws-amplify/amplify-js/issues/1318, so I'll follow that issue for updates
