### ISSUE TITLE
`amplify delete` command

### ISSUE THREAD

**Issue by ChrisSargent** [aws-amplify/amplify-cli#4256]
Please, make it clearer that this deletes ALL of your local files, irrecoverably. Current message is, "wipe out all the local amplify resource files". I thought this meant it would remove all the cloudformation templates and custom resource files, not my entire project. So I've just wiped out a full day's work...

Or at the very least, just move the files to the recycle bin.

**Comment by brene** [comment]
Hi @ChrisSargent - thank you for your feedback! @UnleashedMind will be pushing a fix soon to update the label to:
```
Are you sure you want to continue? This CANNOT be undone.
(This would delete ${environmentText} of the project from the cloud
and wipe out all the local Amplify files in the "./amplify" folder)
```

**Comment by ChrisSargent** [comment]
Hi @brene - no worries, thanks for the quick turnaround, much appreciated! :-)

**Comment by UnleashedMind** [comment]
Thanks for the feedback, I'm closing the issue since the text update has been merged.
