### ISSUE TITLE
enable-admin-queries  

### ISSUE THREAD

**Issue by DavidNelsonCordelia** [aws-amplify/amplify-cli#4259]
I am trying to setup some admin actions for AUTH per this documentation:
 https://docs.amplify.aws/cli/auth/admin#enable-admin-queries

for an existing app  so i am doing amplify auth update instead of amplify auth add

I just updated to amplify cli 3.15

I do not get any of the options to configure admin queries to show up on a update.

Do i have to start from no user pool and then add from scratch?  this isn't very viable we have 1000+ users in an existing pool.

**Which Category is your question related to?**
AUTH

**Amplify CLI Version** 
3.15

**What AWS Services are you utilizing?**
auth,storage, functions, api 

**Provide additional details e.g. code snippets**

**Comment by kaustavghosh06** [comment]
@DavidNelsonCordelia Can you update to the latest version of the CLI - 4.19.0? You don't need to re-create a user-pool to use this feature.
