### ISSUE TITLE
Subscriptions not working with amplify-appsync-simulator

### ISSUE THREAD

**Issue by Mudassir-23** [aws-amplify/amplify-cli#4264]
@yuth  Thanks for working on subscriptions with **amplify-appsync-simulator**.

I'm facing a problem testing subscriptions, I'm assuming subscription endpoint is **ws://${IP_ADRESS}:{PORT}/graphql** 

when I subscribe, a message "listening" continues to show up but on mutation, nothing would happen with a subscription(no data is received). 

i tried with **ws://${IP_ADRESS}:{PORT}/** endpoint as well.

I'm using graphql playground to test subscriptions. I'm using
`"amplify-appsync-simulator": "^1.19.0"`

Is anyone else facing a similar issue?

**Comment by yuth** [comment]
@Mudassir-23 Are you using Amplify JS API category client to listen to subscription?

**Comment by Mudassir-23** [comment]
@yuth I'm using graphql playground to listen to subscriptions. I'm able to work with mutations and queries with graphql playground. But is it like subscriptions won't work with this? Can u please point me to some tutorial where we are using amplify js for connecting to the simulator.

**Comment by yuth** [comment]
> I'm using graphql playground to listen to subscriptions. I'm able to work with mutations and queries with graphql playground. But is it like subscriptions won't work with this?

By playground do you mean the GraphiQL interface that is shipped with Mock? That interface does not have support for subscription.

> Can u please point me to some tutorial where we are using amplify js for connecting to the simulator.

We have this documented in our [Getting started](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js#connect-frontend-to-api) section
The following code snippet does the subscription

```js
// other imports
import { onCreateTodo } from './graphql/subscriptions'

const SubscriptionResult = document.getElementById('SubscriptionResult');

API.graphql(graphqlOperation(onCreateTodo)).subscribe({
  next: (evt) =>{
    SubscriptionResult.innerHTML = `SUBSCRIPTION RESULTS`
    const todo = evt.value.data.onCreateTodo;
    SubscriptionResult.innerHTML += `<p>${todo.name} - ${todo.description}</p>`
  }
});
```

**Comment by SwaySway** [comment]
Closing this issue. Should you run into any issues related to this please comment below.

**Comment by brno32** [comment]
My colleagues and are I also having issues with subscriptions not working. We're using the `serverless-appsync-simulator` wrapper so I'm linking to the issue I've opened there https://github.com/bboure/serverless-appsync-simulator/issues/54

**Comment by imolorhe** [comment]
I believe the subscription protocol used in GraphQL playground is different from the one used in appsync (MQTT-based) so they wouldn't work. I think the [Altair GraphQL client](https://altair.sirmuel.design/) would help here as well. _It supports the regular websocket subscriptions as well as subscriptions for AppSync_
