### ISSUE TITLE
Queries not generated for secondary index

### ISSUE THREAD

**Issue by TheBenck** [aws-amplify/amplify-cli#4265]
**Which Category is your question related to?**
API(GraphQL)

**Amplify CLI Version**
4.18.0

**Provide additional details e.g. code snippets**
I want to query the data based on a secondary index ("slug" in this case) but the only queries that are generated are for the primary index and search:

- `getBook(id: ID!): Book`
- `listBooks(id: ID, filter: ModelBookFilterInput, limit: Int, nextToken: String, sortDirection: ModelSortDirection): ModelBookConnection`
- `searchBooks(filter: SearchableBookFilterInput, sort: SearchableBookSortInput, limit: Int, nextToken: String): SearchableBookConnection`

Is it possible to get a query like `getBookBySlug(slug: String!): Book` in addition to the primary index query? Or is the solution just to make `slug` the primary index?

```
type Book
  @model
  @searchable
  @key(name: "bySlug", fields: ["slug"])
{
  id: ID!
  slug: String!
  name: String!
}
```

**Comment by sudeep-quantelai** [comment]
If you add a @key directive the queryFields option will create a query based on that key. Here is a code snippet

`@key (name: "allPeriods", fields:["keyValue","method","predDate"],queryField:"getModelPerfforMethod")`

This will generate`
getModelPerfforMethod(ticker: String, methodPredDate: ModelModelPerformanceAllPeriodsCompositeKeyConditionInput, sortDirection: ModelSortDirection, filter: ModelModelPerformanceFilterInput, limit: Int, nextToken: String): ModelModelPerformanceConnection`

The only issue that I have found is that you now have to construct the composite key if your sort key has more than one fields. I wish they create a resolver that takes care of this and allows you to enter individual values and the key is constructed behind the scenes.

**Comment by UnleashedMind** [comment]
@TheBenck 
Please check our [document](https://docs.amplify.aws/cli/graphql-transformer/directives#key) on the @key directive. 
As @sudeep-quantelai  pointed out, query will be generated if you add the `queryField` in the @key definition.
To make the @key directive generate primary key, omit the "name" field in the @key definition.

**Comment by TheBenck** [comment]
Ah, I missed that part. Thank you @sudeep-quantelai and @UnleashedMind !
