### ISSUE TITLE
Can a CLI upgrade break appsync?

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#4266]
** Please describe which feature you have a question about? **

Amplify/Appsync

** Provide additional details**

Yesterday I had a properly working API setup (Amplify / Appsync).  I upgraded the system aws-amplify cli from 4.13.0 to 4.19.0 on Unbuntu 19.04.  Today making changes to the graphql schema, I get the error "cannot update more than one GSI at a time".  This is regardless if I am adding another field to an existing type or a brand new type (not using any directives like @connection or @key, only @auth since the beginning).  I believe this has been a long running problem and as was under impression it was a cloud formation bug but not one I have experienced.  Please advise if possible.  Thanks in advance.

**Comment by kaustavghosh06** [comment]
@weisisheng Could you please let us know the before and after schemas and the exact changes you're trying to make? Thanks.

**Comment by weisisheng** [comment]
Thanks for the fast response.  Since I am trying to make quicker progress on my MVP, I removed the API and am rebuilding the graphql schema with a simpler base then adding additional directives.  Will report back if/when the issue surfaces again.

**Comment by kaustavghosh06** [comment]
Okay, please let us know. Thanks! Closing this issue for now.
