### ISSUE TITLE
Amplify with EC2 resolvers instead of Lambda?

### ISSUE THREAD

**Issue by gautamkshitij** [aws-amplify/amplify-cli#4271]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
So we know amplify can support lambda resolvers - however, we know lambda functions can be expensive if they are long-running - do we have support to launch an ec2 container and that completes the resolution?

**Describe the solution you'd like**
`amplify add ec2-instance` 
`mutation test(input) @ec2-instance(name: "my-ec2-instance")`
**Describe alternatives you've considered**
Well keep using lambda functions and pay up.

**Additional context**

**Comment by UnleashedMind** [comment]
The Amplify CLI currently does not have such functionality.

**Comment by kaustavghosh06** [comment]
This should be a feature request for AppSync service to support additional data sources to be used with the resolvers. You can add your request to their queue here - https://github.com/aws/aws-appsync-community
