### ISSUE TITLE
GraphQL descriptions filtered out during codegen

### ISSUE THREAD

**Issue by CurtisHumphrey** [aws-amplify/amplify-cli#4273]
**Describe the bug**
If I add a description to a field like
```
  # flag for if they are current
  is_active: Boolean!
```

The resulting schema.graphql in the build folder and in the introspection call are both missing the description.  It seems that it is being parsed out.

**Amplify CLI Version**
4.18.1

**To Reproduce**
Add a `# description` above any field in graphql and do something like `amplify mock api`

**Expected behavior**
The introspection call that powers viewers like graphiql should have field descriptions that match the text given in the `# note`

**Desktop (please complete the following information):**
 - Mac
 - Node Version: 14.1

**Comment by SwaySway** [comment]
Currently the CLI does not support comments in the schema. This is an enhancement you can track here https://github.com/aws-amplify/amplify-cli/issues/1393

Closing as a duplicate.
