### ISSUE TITLE
Error adding Admin API to existing app with Auth 

### ISSUE THREAD

**Issue by pseudyx** [aws-amplify/amplify-cli#4279]
**Describe the bug**
When trying to add Auth Admin API, via "Amplify update auth" to an existing Amplify App. It adds locally, but I get the following error when I run "Amplify push":

× An error occurred when pushing the resources to the cloud

,audited 99 packages in 1.857s
found 6 vulnerabilities (2 low, 4 high)
  run npm audit fix to fix them, or npm audit for details
,The system cannot find the path specified.
The system cannot find the path specified.
npm WARN adminqueries@1.0.0 No repository field. 

I have run npm audit locally and only have 2 vulnerabilities, so it appears to be an issue on the server side.

**Amplify CLI Version**
@aws-amplify/cli@4.20.0

**To Reproduce**
Create a react-app and add Amplify. 
Added Amplify auth defaults (no admin api)
have been running the app for 3 weeks with no issues, in which time added Storage, and GraphQL API.
Attempted: Amplify update auth -> update or create admin api
adds locally.
Amplify push = error

**Expected behavior**
Add Amplify backend and generate front end code for admin api

**Screenshots**
![image](https://user-images.githubusercontent.com/515559/82007782-67e8b000-96ae-11ea-9473-7654d5ee150d.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Node Version. v12.16.1

**Additional context**
its adding admin api to amplify app that already has auth, storage and api running.

**Comment by pseudyx** [comment]
After updating node, now I jsut get the error: "npm WARN adminqueries@1.0.0 No repository field."

**Comment by pseudyx** [comment]
I just tried to create a new app from the beginning...
Installed amplify, initialised, then amplify add auth, followed the manual configuration steps (not defaults) and added Admin API. 
everything adds locally... then when I Amplify Push, I get the error: "npm WARN deltaAuthCustomMessage@2.0.0 No repository field."

where deltaAuth is the resource name for auth, and i assume CustomMessage is the lambda function for account verification... is this an error with the lambda package.json 

{
  "name": "deltaAuthCustomMessage",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0"
}

should it have a repository field as the error suggests?


![image](https://user-images.githubusercontent.com/515559/82062603-b2e5e000-970d-11ea-95ea-2b21a5fe15c5.png)

**Comment by pseudyx** [comment]
I just attempted to update and push another Amplify app in the account (which doesnt have auth Admin API) with no issues. but attempting to push the above app, and still get error

**Comment by SwaySway** [comment]
Closing this issue in favor of #4296
