### ISSUE TITLE
CLI Version 4.20.0 fails push

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4282]
**Describe the bug**
I was prompted to upgrade to amplify 4.20.0 - which I did. My stack which worked perfectly on 4.19.0 failed, with CloudFormation status UPDATE_ROLLBACK_FAILED.

**Amplify CLI Version**
4.20.0

**To Reproduce**
`amplify api gql-compile`
`amplify push --no-gql-override --yes`

**Expected behavior**
Push is successful

**Desktop (please complete the following information):**
 - Cloud9 - aws linux
 - node v10.16.3

**Additional context**
How can we downgrade to Amplify 4.19.0 whilst this issue is being resolved.

**Comment by sacrampton** [comment]
Actually I downgraded to 4.19.0 and same issue is happening...
![image](https://user-images.githubusercontent.com/6362888/82033132-a64a9300-96df-11ea-83ab-a79c4ee70b4a.png)

**Comment by SwaySway** [comment]
Hello @sacrampton 
It looks like your stack is not updated from the previous push. 
Are there any errors on your amplify stack in cloudformation? It seems there was a failure in the last amplify push.
I see you are using `amplify push --no-gql-override --yes` are there any changes being made to the stack?

**Comment by sacrampton** [comment]
Hi @SwaySway @UnleashedMind 

I figured this was some sort of intermittent issues on the back end so I tried again just now with 4.19.0 and got this error. I upgraded to 4.20.0 and go exactly the same error. Seems some sort of token problem - I'm using Cloud9 so am already logged in and have all the credentials.

It never progresses to get the backend from the cloud.

![image](https://user-images.githubusercontent.com/6362888/82101884-1c3b1280-9751-11ea-9227-5ec0721cdc3b.png)

**Comment by sacrampton** [comment]
And now - without me changing anything at my end - I can now successfully push my stack. Didn't change anything from yesterday - just executed the same "amplify push --no-gql-override --yes" and this time it succeeded.

Something obviously going on at the back end was blocking this - but at least for now its working
