### ISSUE TITLE
Amplify Add API hanging

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#429]
**Describe the bug**
When adding an API for Graphql and you edit your model using VSCode it will hang until you close the VSCode window.

**To Reproduce**
1. Default editor is set to VSCode
1. Set up an API and when you get to editing your model it will open VSCode
1. Change your model and then save the file
1. Hit enter in the terminal and it will go through and create the backend folder.
1. Observe the backend folder is created but it won't end the command until VSCode is closed.

**Expected behavior**
The API command will exit when you hit enter to continue.

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by kaustavghosh06** [comment]
@wizage  I wasn't able to reproduce the issue with the version of my VSCode. Which version of VSCode are you using and does this happen repeatedly?

**Comment by jerekapyaho** [comment]
I just ran into this error on Visual Studio Code 1.32.3 running on macOS 10.14.3, with Amplify CLI 1.1.8 (npm 6.9.0, node v11.12.0). The `amplify add api` command terminates only after you close the Visual Studio Code window used to edit the GraphQL schema.
