### ISSUE TITLE
How to configure Elasticsearch Mappings

### ISSUE THREAD

**Issue by raelmiu** [aws-amplify/amplify-cli#4291]
**Which Category is your question related to?**
@searchable

**What AWS Services are you utilizing?**
Elasticsearch Service

**Provide additional details e.g. code snippets**
I'm using @searchable to match queries through elastic search, however the mapping is missing a core piece of information.

My model:
```gql
Note {
  id: ID
  content: string
  references: [ID]
}
```

In this case the references should increase the score of the referenced note id. But I'm unable to find any way to affect the mapping. This must be possible in some way?

**Comment by raelmiu** [comment]
Is there even a way to do this? The lambda that's streaming my Notes to ES should be able to do this I believe. But I can't really figure out how.

**Comment by SwaySway** [comment]
Hello @raelmiu 
You are able to override the generated ES lambda function by providing your own streaming function zipped into `amplify/backend/api/<your_api_name>/functions/` under your api folder.

As for how to configure your mapping this is something we would encourage to use our community discord [discord.gg/amplify](https://discord.com/invite/amplify).

**Comment by raelmiu** [comment]
@SwaySway I just want to add that there's a total of 80 ppl on that discord, and this is the third "forum" for Amplify I've been sent to. No wonder ppl are confused and end up in GitHub issues.
