### ISSUE TITLE
Subscriptions with arguments not working

### ISSUE THREAD

**Issue by Stereobit** [aws-amplify/amplify-cli#4292]
**Describe the bug**
I'm not able to receive any updates from subscriptions when using arguments in my application. I am able to reproduce the issue using the chat sample app while only using the AWS console so I'll leave any other setup out here.

**To Reproduce**
* Create new AppSync App
* Pick Chat Sample
* Run Query

```
subscription {
  subscribeToNewMessage(conversationId: "myNewId") {
    content
    createdAt
  }
}
```

* Run Query

```
mutation CreateMessage {
  createMessage(content: "Second!" conversationId: "myNewId" createdAt: "This afternoon" id: "messageOneId") {
    content
    createdAt
  }
}
```

**Expected behavior**
The subscription receives the results of the `createMessage` mutation.

**Additional context**
If I remove the argument from the subscription it works as expected 
```
type Subscription {
  subscribeToNewMessage: Message @aws_subscribe(mutations: ["createMessage"])
}

subscription {
  subscribeToNewMessage {
    content
    createdAt
  }
}
```

**Comment by attilah** [comment]
@Stereobit I was able to reproduce the issue with the Amplify Console, the AppSync team will look into that.

That sample is not built with the Amplify CLI, but if I understand correctly your app where the problem surfaces is created with the CLI? If so, please share the schema and any repro steps I can use to reproduce your exact issue.

**Comment by SwaySway** [comment]
Hello @Stereobit 
This question seems geared more towards the appsync community repo. I would suggest opening an issue there https://github.com/aws/aws-appsync-community or in their forums https://forums.aws.amazon.com/tags/appsync.

Should you have any issues related to the CLI please comment below.

**Comment by Stereobit** [comment]
Hey @attilah thanks for the update. I'm currently not using the CLI so I guess it's fair to close this issue. I'll follow @SwaySway advice and open one in the community.

**Comment by Stereobit** [comment]
@attilah I've now figured out what the issue is. My assumption was that the subscriptions are filtered by the arguments I send in my mutation, not the ones I receive. If I add the field to my mutation it works:

```
mutation CreateMessage {
  createMessage(content: "Second!" conversationId: "myNewId" createdAt: "This afternoon" id: "messageOneId") {
    conversationId
    content
    createdAt
  }
}
````
