### ISSUE TITLE
Amplify push not working with Admin API

### ISSUE THREAD

**Issue by pseudyx** [aws-amplify/amplify-cli#4296]
**Describe the bug**
Created new Amplify App
Amplify add Auth
Select manual and add Admin API

**Amplify CLI Version**
v4.20.0

**To Reproduce**
Amplify add auth
follow prompts for manual setup (not the all defaults option) (create group "admin")
select to add Admin API
allow Admin API access from group "admin"
Amplify Push 

**Expected behavior**
Amplify push to create and provision resources in aws.

**Screenshots**
![image](https://user-images.githubusercontent.com/515559/82134071-c9d42180-9836-11ea-9167-c92e8110d257.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v12.16.3

**Additional context**
am able to create and push Amplify resources (auth, graphQL, REST API, Storage) without Admin API. But addint Admin API failes to push, on both new apps and adding to existing apps.

**Comment by attilah** [comment]
@pseudyx could you please share the full question/answer to see if there is a combination of answers causing this or not. Do you have access to a non-windows machine to be able to help us see if it is platform related issue or not?

**Comment by pseudyx** [comment]
@attilah 
Please find question/answers as requested:

amplify add auth
 Do you want to use the default authentication and security configuration? **Manual configuration**
 Select the authentication/authorization services that you want to use: **User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)**
 Please provide a friendly name for your resource that will be used to label this category in the project: **deltaAuth**
 Please enter a name for your identity pool. **delta_identitypool**
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) **Yes**
 Do you want to enable 3rd party authentication providers in your identity pool? **No**
 Please provide a name for your user pool: **delta_userpool**      
 How do you want users to be able to sign in? **Email**      
 Do you want to add User Pool Groups? **Yes**  
? Provide a name for your user pool group: **admin**   
? Do you want to add another User Pool Group **Yes**
? Provide a name for your user pool group: **legion**
? Do you want to add another User Pool Group **No**
√ Sort the user pool groups in order of preference · **admin, legion**
 Do you want to add an admin queries API? **Yes**
? Do you want to restrict access to the admin queries API to a specific Group **Yes**
? Select the group to restrict access with: **admin**
 Multifactor authentication (MFA) user login options: **OFF**       
 Email based user registration/forgot password: **Enabled (Requires per-user email entry at registration)**
 Please specify an email verification subject: **Your verification code**
 Please specify an email verification message: **Your verification code is {####}**
 Do you want to override the default password policy for this User Pool? **No**
 What attributes are required for signing up? **Email, Name**
 Specify the app's refresh token expiration period (in days): **30**
 Do you want to specify the user attributes this app can read and write? **Yes**
 Specify read attributes: **Email, Name, Picture, Profile**
 Specify write attributes: **Picture, Profile**
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? **No**
? Do you want to configure Lambda Triggers for Cognito? **No**

**Comment by pseudyx** [comment]
@attilah the above worked on Linux.
its just on windows machine it doesn't work

**Comment by attilah** [comment]
@pseudyx thanks for confirming it narrows down the issue repro.
