### ISSUE TITLE
Temp directories left in amplify after environment removal

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#4298]
**Describe the bug**
After removing a back-end env, using `amplify env remove test`, the environment is successfully removed from the cloud; however, a temp directory remains in the amplify directory.

🤷 Frankly, I'm not sure this is a bug, as this could be intentional as "safety" mechanism for accidental deletion or for some other reason.

**Amplify CLI Version**
4.19.0

**To Reproduce**
1. Remove a backend environment with `amplify env remove test`
2. Look in amplify directory and see `test` directory with `.temp` content
```console
└───test
    └───.temp
        └───#current-cloud-backend
            ├───api
            │   └───myAPI
            ├───auth
            │   └───myAuthxxxxxxxx
            ├───function
...
```
**Expected behavior**
The removed env should be completely removed from the working directory, unless this is intentional, in which case there is no bug.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. 10.19.0

**Comment by attilah** [comment]
@kimfucious thanks for reporting it it seems to be an issue.
