### ISSUE TITLE
amplify plugin init NOT working as per the docs

### ISSUE THREAD

**Issue by dpandya** [aws-amplify/amplify-cli#4311]
**Describe the bug**
The `amplify plugin init` command is not working as per the [documentation](https://aws-amplify.github.io/docs/cli-toolchain/plugins?sdk=js)

**To Reproduce**
1. Install `amplify-cli`
```
npm install -g @aws-amplify/cli
```
2. Create `my-plugin` dir
```
mkdir my-plugin
```
3. CD to `my-plugin` dir
```
cd my-plugin
```
4. Attempt to initialize the plugin
```
amplify plugin init
```
5. Type `my-plugin` for `What should be the name of the plugin:`
6. Select `category` for `Specify the plugin type`
7. Select all events `PreInit, PostInit, PrePush, PostPush` for `What Amplify CLI events do you want the plugin to handle?` Hit ENTER

**Expected behavior**
The plugin dir `my-plugin` should be initialized

**Actual behavior**
It errors out with the following error
`Cannot load command amplify plugin new`

**Desktop (please complete the following information):**
 - OS: macOS Mojave (Version 10.14.6)

**Additional context**
Further debugging by adding extra console log lines in the `plugin.ts` file reveals the following error
```
Error: ENOENT: no such file or directory, stat '/Users/<username>/.nvm/versions/node/v12.16.0/lib/node_modules/@aws-amplify/cli/lib/templates/plugin-template'
```

**Comment by attilah** [comment]
@dpandya could you please try to reproduce it with the latest version of the CLI, since I was not able to reproduce it, it was working as intended.

**Comment by dpandya** [comment]
I just tested now. I am also not able to reproduce the issue anymore. Closing the issue.
