### ISSUE TITLE
Datastore Relational Example for js does not work completely

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#4312]
https://docs.amplify.aws/lib/datastore/relational/q/platform/js#updated-schema

type Post @model {
  id: ID!
  title: String!
  rating: Int!
  status: PostStatus!
  comments: [Comment] @connection(name: "PostComments")
}

type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}

As written the above does not work, codegen and model codegen is successful, objects can be created on the client (locally), but the data does not sync with DynamoDB due to src/models/schema.js having the following:

  "association": {
                        "connectionType": "BELONGS_TO",
                        "targetName": "postId"
                    }

postId does not exist in the mutation, so the mutation fails.

Using the latest version of CLI and JS.

**Comment by undefobj** [comment]
Could you try this again with the latest CLI and library version? We just released an update along with new example in the documentation.

**Comment by kaustavghosh06** [comment]
@GeorgeBellTMH did you get this to work?

**Comment by erikth23** [comment]
@GeorgeBellTMH  were you able to get this to work? Having a similar problem, but can't find a solution

**Comment by erikth23** [comment]
For those coming here later, this post is sort of helpful: [5955](https://github.com/aws-amplify/amplify-js/issues/5955)
