### ISSUE TITLE
Use of RDS vs DynamoDB with Amplify

### ISSUE THREAD

**Issue by sudeep-quantelai** [aws-amplify/amplify-cli#4318]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Use of RDS vs DynamoDB with Amplify

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.18.1

**What AWS Services are you utilizing?**
DynamoDB, AppSync, Amplify, Cognito

**Provide additional details e.g. code snippets**
While DynamoDB is the default for GraphQL what are the pros and cons of using DynamoDB vs. RDS. Also can I use Postgres with AppSync GraphQL? From the documentation you cannot generate @models on anything other than DynamoDB?

**Comment by attilah** [comment]
@sudeep-quantelai The CLI provide tools for the GraphQL transformer for DynamoDB only through the `@model` directive and the generated resolver code depends heavily on the capabilities of DynamoDB itself.

The CLI support of adding Aurora Serverless datasources to the GraphQL API, but no `@model` support. See the documentation about this here: https://docs.amplify.aws/cli/graphql-transformer/relational

Postgres is not supported, if you've *detailed* use cases about what you'd like to see as far as CLI support for Aurora/RDS please open a new issue so we can track that as an enhancement.

**Comment by yogeshwar607** [comment]
@attilah any future plans of supporting aurora postgres with @model & other directives or amplify will remain tightly coupled with DynamoDB only
