### ISSUE TITLE
Deleting schema entity and then re-creating it results in `Resource is not in the state stackUpdateComplete` error

### ISSUE THREAD

**Issue by reefloretto** [aws-amplify/amplify-cli#4330]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I removed two object types from my GraphQL schema and ran `amplify push`. The push was successful, but I then realized I actually needed those types. To recreate them, I reverted my `schema.graphql` to the version in which those types were present. I then ran `amplify push`. 

The push failed with the following errors:
```
Embedded stack arn:aws:cloudformation:us-east-1:249716397406:stack/amplify-goodstuff-carmack-154501-apigoodstuff-5SNR0FDXIFXG/7c49c570-8277-11ea-a59d-0a4db9a5d67f was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [Good, Rating]. The following resource(s) failed to update: [Request, Message, User].
```

**Amplify CLI Version**
```
% amplify -v
4.20.0
```

**To Reproduce**
- Remove one or more types from your `schema.graphql` file.
- Run `amplify push` (succeeds)
- Re-add those types _exactly as they were before_ (i.e. revert `schema.graphql` to its state prior to the type deletion)
- Run `amplify push` (fails)

**Expected behavior**
It should be possible to re-add types that once existed but were removed.

**Desktop (please complete the following information):**
 - OS: Mac 10.15.4
 ```
% node -v
v12.16.1
```

**Comment by attilah** [comment]
@reefloretto I tried to reproduce this issue since we have e2e tests for these kind of schema updates and I was not able to reproduce it.

Can you share your schema with us? and full repro steps?

**Comment by reefloretto** [comment]
> @reefloretto I tried to reproduce this issue since we have e2e tests for these kind of schema updates and I was not able to reproduce it.
> 
> 
> 
> Can you share your schema with us? and full repro steps?

for sure! will have some updates within the next few hours

**Comment by reefloretto** [comment]
> @reefloretto I tried to reproduce this issue since we have e2e tests for these kind of schema updates and I was not able to reproduce it.
> 
> Can you share your schema with us? and full repro steps?

for context: i got a bit lucky last night. i was able to create a _new_ environment and then _revert_ the modified schema back to its version prior to the type deletions (restored from version control) and the subsequent push on _in that env_ was OK. (this is presumably because there weren't any orphaned exports/resources in that new env because it was brand new.)

however. i created a new env today and was able to repro this bug, exactly as experienced yesterday.

1. `amplify env add repro` (based on latest working production env)
1. `amplify push --yes` (to get new env up-to-date with latest prod)
1. modify schema from [before](https://gist.github.com/reefloretto/b6d7be40311b1ea914bb672bfc50e68a) to [after](https://gist.github.com/reefloretto/9b650687c89305a53333216b17957132) state
1. `amplify push --yes` (successful)
1. revert schema from [after](https://gist.github.com/reefloretto/9b650687c89305a53333216b17957132) to [before](https://gist.github.com/reefloretto/b6d7be40311b1ea914bb672bfc50e68a)
1. `amplify push --yes` (failed)

<img width="1440" alt="Screenshot 2020-05-20 19 36 24" src="https://user-images.githubusercontent.com/11042411/82508088-fce61180-9ad1-11ea-8f39-19cf72ccb84d.png">

**Comment by reefloretto** [comment]
as an additional note -- i think this has partially to do with the fact that the "delete" operations in amplify don't appear to be as comprehensive as i'd expect. for example, i just deleted the "bad env" and i had to go in and remove some orphaned cloudformation nested stacks _after the fact_ (i.e. after the cli-initiated env deletion completed). seems off 🤔 

FYI this screenshot was the result of me deleting nested cloudformation stacks related to the bad env; i didn't trigger these table deletions manually.

<img width="1440" alt="Screenshot 2020-05-21 19 24 06" src="https://user-images.githubusercontent.com/11042411/82615566-bc050000-9b98-11ea-977f-f792976e240f.png">

**Comment by thomasklein-winemaker** [comment]
This is still reproducible with 4.40.1. Didn't have the time to update to the latest version, though I reckon it shouldn't make a difference. 
Basically I'm forced to create a renamed table and leave the orphaned table for good.
