### ISSUE TITLE
No JavaString equals method

### ISSUE THREAD

**Issue by rickfoxcroft** [aws-amplify/amplify-cli#4334]
The current implementation has no equals method for the JavaString class in the amplify-appsync-simulator package

**Comment by rickfoxcroft** [comment]
fixed by #4316

**Comment by attilah** [comment]
@rickfoxcroft thanks for the suggestion and the PR as well!

**Comment by rickfoxcroft** [comment]
> @rickfoxcroft thanks for the suggestion and the PR as well!

Thanks for the quick feedback @attilah . It looks like @yuth has given the thumbs up to #4316. Are we ready to merge this?
