### ISSUE TITLE
CustomMessage trigger & HTML email message?

### ISSUE THREAD

**Issue by smakinson** [aws-amplify/amplify-cli#4339]
I generated a CustomMessage trigger in hopes of sending a decent html email when users sign up. I initially tried to paste the html into the text area in the user pool admin/console in the browser, but saw validation error, so I thought I'd try using the trigger, however I am seeing the same error. The docs say:

> "For email, the maximum length for the message is 20,000 UTF-8 characters, including the verification code. HTML tags can be used in these emails."

Is there more information on the allowed html? Is it not possible to send a completely html email with a design (body tag, style tags, tables, images, html comments because if IE `<!--[if (mso)|(IE)]>`, etc)?

**Which Category is your question related to?**
auth

**Amplify CLI Version** 
4.20.0

**Comment by attilah** [comment]
@smakinson This is related to Cognito capabilities, please check the documentation here: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-email-verification-message-customization.html

For further questions it is a better place to ask in the Cognito Forums: https://forums.aws.amazon.com/forum.jspa?forumID=173

**Comment by smakinson** [comment]
@attilah I was hoping there is more documentation, the only thing mentioned on that page is 

> "HTML tags can be used in these emails."

but it seems there must be some rules around it since it is rejecting a full html page for the email. I think the information on this would be better as part of the documentation. Is there a place to request this if it does not exist?

I have tried temporarily removing the `<style>` tag and content to see if it is the  `{` and `}` in there causing the issue as mentioned on the forum, but I see the same error. The html does contain `{####}`

The error is:
`at 'emailVerificationMessage' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]* (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException;`

forum links:

https://forums.aws.amazon.com/thread.jspa?messageID=840827&#840827
https://forums.aws.amazon.com/thread.jspa?messageID=943959&#943959
https://forums.aws.amazon.com/thread.jspa?messageID=943961&#943961

**Comment by ianmartorell** [comment]
I was having this same issue, and it turned out there was a weird special character in my HTML, and that was the reason it didn't satisfy the constraint. Once I removed it, it started working great, with `style`, `head`, `html` and even `doctype` tags!

For future reference, the HTML can be tested here: https://regex101.com/r/y8G6bF/2
