### ISSUE TITLE
How am I supposed to use Amplify Environment variables in my Lambda @functions?

### ISSUE THREAD

**Issue by Billybobbonnet** [aws-amplify/amplify-cli#4347]
**Which Category is your question related to?**
Environment variables, Amplify and Lambda

This is a pretty straightforward feature and question. It has been mentioned in many issues here

- https://github.com/aws-amplify/amplify-cli/issues/684
- https://github.com/aws-amplify/amplify-cli/issues/678

Or elsewhere: 

- https://www.reddit.com/r/aws/comments/dia7bn/how_do_you_access_amplify_environment_variables/
- https://stackoverflow.com/questions/57446615/creating-process-env-variables-using-aws-amplify

And the [terrible documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html) does not help, only the first part of it (setting the variables) makes sense.

Here is from where I started, what I went through and what didn't work. Let me know if I have missed something.

**_Where I started_**
I wanted to remove the api id from dynamoDB generated tables for @model, in order to have a table name e.g. "project-dev" instead of "Project-6ezfre56g4erg-dev". It would have been much easier, to reference it, especially since I have multiple api using the same table.

As I understood it, Amplify is opinionated and it abstracts the implementation details, we then cannot have both custom data sources and an API generated through the @model directive.

I still tried to update the cloudFormation template of my nested stack to remove the apiId from the table name (`GetAttGraphQLAPIApiId`) everywhere it was mentionned, but the update rollback: 
``` yaml
"TableName": {
                    "Fn::If": [
                        "HasEnvironmentParameter",
                        {
                            "Fn::Join": [
                                "-",
                                [
                                    "Project",
                                    {
                                        "Ref": "GetAttGraphQLAPIApiId"
                                    },
                                    {
                                        "Ref": "env"
                                    }
                                ]
                            ]
                        },
```

Again, this is a managed approach, so I guess I should comply with it. However, when you offer a managed approach, it should consider that the AppSync data sources are exposed, can be changed, and that it has no consequence on the API. This is very inconsistent with the managed approach and misleading to say the least.

**_So I needed environment variables_** to store my table names. I found the documentation, switched to the managed hosting of the frontend apps to have the possibility to add environment variables (no idea why it is mandatory) and defined my env variables at the amplify app level as mentioned [here](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#setting-env-vars).

I expected these global, app level, env variables to be global env variables. However, as far as I know, they are not. In my lambda workers, I cannot find them at the `process.env` level. Why are they not inherited? Am I missing something?

I really don't want to manually add to my 50+ lambda workers local env variables, at the lambda level.

I also tried to update the cloudFormation template of the lambda with the same approach than the snippet above but `GetAttGraphQLAPIApiId` is not available. Since I can't have custom table names, I am back to square one.

Since it seems that Amplify env variables are exposed at build step, I tried to assign them to the backend at the build level in the `amplify.yml` file. No luck there either, it fails to build if I assign a variable.

I really like Amplify but this issue has made me lose a lot of time and was a real disappointment. I still think I could have missed something so I took the time to write all this. Please consider the effort and let me know how I should proceed to have my env variables available in my lambda workers, or change my tables names to custom names while keeping the @model directive benefits.

**Comment by kaustavghosh06** [comment]
@Billybobbonnet Apologize for the confusion out here. Did you try out the `amplify update function` flow to add the table names generated by the GraphQL transformer (i.e data sources) as environment variables to the function? We provide that flow and it's documented out here -https://docs.amplify.aws/cli/function#function-templates
Unfortunately at this time, the lambda functions generated by the CLI do not inherit the env variables defined in the Amplify Console. The env variables defined in the Amplify console is just used in your build configs and are build time environment variables.

**Comment by Billybobbonnet** [comment]
@kaustavghosh06 Thank you for your answer. I'll look into the doc you mentioned.

**Comment by djsmedes** [comment]
> Unfortunately at this time, the lambda functions generated by the CLI do not inherit the env variables defined in the Amplify Console. The env variables defined in the Amplify console is just used in your build configs and are build time environment variables.

@kaustavghosh06 - is there a feature request ticket for this functionality? And is there a workaround - some better way of centrally managing e.g. a cryptographic secret and automatically getting it into lambdas as an environment variable without putting it into a file that will be in version control?

**Comment by anandsathe67** [comment]
Any chance this will be picked up in a upcoming release? Becoming a real headache to deal with

**Comment by dabit3** [comment]
@anandsathe67 we're working on this now, unsure of a date but will try to come back soon with something close.

**Comment by esteban-uo** [comment]
hi @dabit3 do you have a PR or an Issue to track the status of it? many thanks

**Comment by mvsantos013** [comment]
I need so much this feature. Any update about this?

**Comment by alexboulay** [comment]
Any updates? Would be cool to have a native solution

**Comment by dmsolutionz** [comment]
Why is this closed? We are facing similar issues when we want to set env vars...

**Comment by econtentmaps** [comment]
+1. Bit silly not having this, really.

**Comment by Trevor-mc2** [comment]
+1

**Comment by akash87** [comment]
+1

**Comment by amlcodes** [comment]
+1

**Comment by jkolaric** [comment]
+1

**Comment by mahanh** [comment]
+1

**Comment by jwmock** [comment]
+1

**Comment by tpeace** [comment]
@dabit3 - there are a lotta prayers being sent into the void here. Is there any update on making this crucial feature work?  If you could check, I would really appreciate it. Thanks!  It would be real nice to have env vars in Lambdas.

**Comment by ssamakar** [comment]
+1

**Comment by SourceCode** [comment]
+1

**Comment by Trevor-mc2** [comment]
Hey gang. 

So, FYI, it's totally possible to _manually_ add ENV vars to the Lambda after it has been created by Amplify, if you just need your Lambda to have access to ENV vars.  I manually copied mine from the Amplify config into the AWS webtop...  Just to get up and running.  

Go to **Lambda > Functions > Configuration** and scroll down to the **Environment variables** section.  🤦‍♂️  And set your env vars by hand.  That avoids the hassle of inserting them via a script, or having to integrate with AWS Secrets Manager.

**Comment by dmsolutionz** [comment]
> Hey gang.
> 
> So, FYI, it's totally possible to _manually_ add ENV vars to the Lambda after it has been created by Amplify, if you just need your Lambda to have access to ENV vars. I manually copied mine from the Amplify config into the AWS webtop... Just to get up and running.
> 
> Go to **Lambda > Functions > Configuration** and scroll down to the **Environment variables** section. 🤦‍♂️ And set your env vars by hand. That avoids the hassle of inserting them via a script, or having to integrate with AWS Secrets Manager.

These will be overwritten by amplify at some point... Trust me, I did this as the first thing, somewhere along the road it will update the CF template and remove them, potentially breaking your applications.

**Comment by ogiogi93** [comment]
+1

**Comment by octaneC8H18** [comment]
Hi

Any update on this?

**Comment by dabit3** [comment]
Coming back to this since it's a popular topic in order to address some ways to implement environment variables today in Lambda with Amplify (until the CLI implements this feature natively).

There are two main approaches (other than manually adding values in the Lambda console):

1. If your value is secret, you can use [Secrets Manager](https://aws.amazon.com/secrets-manager/). To do so, you first need to create a secret in the [secrets manager](https://console.aws.amazon.com/secretsmanager) console.

Next, add a statement to the `PolicyDocument` in __amplify/backend/function/<function_name>/<function-name-cloudformation-template>.json__ to give the Lambda function permission to use the secret:

```
{
  "Effect": "Allow",
  "Action": [
    "secretsmanager:GetSecretValue"
  ],
  "Resource": {
    "Fn::Sub": [
      "arn:aws:secretsmanager:${region}:${account}:secret:key_id",
      {
        "region": {
          "Ref": "AWS::Region"
        },
        "account": {
          "Ref": "AWS::AccountId"
        }
      }
    ]
  }
}
```

Next, access the token in your function:

```js
const AWS = require('aws-sdk')

const secretsManager = new AWS.SecretsManager()
const secret = await secretsManager.getSecretValue({ SecretId: 'YOUR_KEY' }).promise()

console.log(secret.SecretString)
```

There are a few approaches outlined in [this](https://github.com/aws-amplify/amplify-cli/issues/684#issuecomment-453639271) thread.

2. If your value is just a configuration value you can configure the CloudFormation configuration locally to set the value - in __amplify/backend/function/<function_name>/<function-name-cloudformation-template>.json__

For this purpose there is a section in the template - `Parameters` - that you can set.

```json
"Parameters" : {
  "MyKey" : {
    "Type" : "String",
    "Default" : "my-environment-variable"
  }
}
```

And then use these parameters in `Environment` declaration:

```json
"Environment":{
   "Variables":{
      "MY_ENV_VAR":{
         "Ref":"MyKey"
      }
   }
}
```

You can also specify a CFN param in team-provider-info.json under __<env>.categories.function.<func name>__ if you want to specify environment-specific parameters

**Comment by calvinchso** [comment]
@dabit3 , in the case of using team-provider-info.json, how should the lambda function access the env variable value? Thanks!
