### ISSUE TITLE
Make ModelStringFilterInput support NOT_NULL | NULL

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#4350]
It would be useful to be able to filter lists using filter:{column:NOT_NULL|NULL} L.... ModelStringFilterInput could implement it or a new ModelNullableStringFilterInput could be used on columns that allow nulls.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.QueryFilter.html

**Comment by attilah** [comment]
@GeorgeBellTMH the referenced page is a legacy way to query DynamoDB operations and that is not supported by the CLI generated filters, the `filter` argument members are mapped to the DynamoDB Conditional Expressions, see the docs of the supported operations [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html).

With the simple `Todo` I inserted some data with null and not null `description` field and here is the query to be able to do a `null` and `not null` query:

```graphql
query {
  Null: listTodos(filter: {
    not: {
      description: {
        attributeType: string
      }
    }
  }) {
    items	{
      id
      description
    }
  }

  NotNull: listTodos(filter: {
    description: {
      attributeType: string
    }
  }) {
    items	{
      id
      description
    }
  }
}
```

The result is:
```
{
  "data": {
    "Null": {
      "items": [
        {
          "id": "T3",
          "description": null
        },
        {
          "id": "T1",
          "description": null
        },
        {
          "id": "T2",
          "description": null
        }
      ]
    },
    "NotNull": {
      "items": [
        {
          "id": "T5",
          "description": "NotNull"
        }
      ]
    }
  }
}
```

I'm closing the issue as the question was answered if something new comes up feel free to reopen the issue or create a new one.
