### ISSUE TITLE
Change User Pool In Android Application

### ISSUE THREAD

**Issue by FazalHussain** [aws-amplify/amplify-cli#4354]
I am trying to integrate amplify in my application to authenticate user. I have already created user pool and I would like to change the user pool but when I change the configuration in 

> awsconfiguration.json

 and run a command `amplify push` or `amplify pull` it will change the keys to default.

Related: https://github.com/aws-amplify/aws-sdk-android/issues/1739

**Check the related issue one of your team member said I am transferring this issue to cli team**

**Amplify CLI Version** 

4.20.0

**What AWS Services are you utilizing?**

Cognito Pool using with Amplify

**awsconfiguration.json**

`{
        "CognitoUserPool": {
        "Default": {
            "PoolId": "xxxxxxxxxxx",
            "AppClientId": "xxxxxxxxxxxx",
            "AppClientSecret": "xxxxxxxxxxxxxxxxx",
            "Region": "xxxxx"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "xxxxxx"
        }
    }
}`

**Comment by SwaySway** [comment]
Hello @FazalHussain 
Currently the CLI does not support importing existing UserPools, though you can manually configure the UserPool. Docs here: https://docs.amplify.aws/sdk/auth/getting-started/q/platform/android#manual-setup

The use case of importing a resource such as a UserPool is something we are currently looking into please follow the RFC for updates.
RFC: https://github.com/aws-amplify/amplify-cli/issues/3977
