### ISSUE TITLE
Use existing cognito userPool with amplify graphql / datastore

### ISSUE THREAD

**Issue by bkniffler** [aws-amplify/amplify-cli#4356]
**Is your feature request related to a problem? Please describe.**
Currently it seems impossible to use an existing userPool (deployed via cdk) with an amplify graphql API, at least there is no option with the CLI.

**Describe the solution you'd like**
Introduce the ability to add an existing userPoolId/clientId/etc with the CLI.

**Comment by SwaySway** [comment]
@bkniffler This is something we currently looking into as a part of this RFC https://github.com/aws-amplify/amplify-cli/issues/3977

Closing this issue in favor of the RFC.

**Comment by kierancrown** [comment]
Was there any updates on this?
