### ISSUE TITLE
Intermediary many-to-many table with `queries: null` does not create auth perms

### ISSUE THREAD

**Issue by quorth0n** [aws-amplify/amplify-cli#4361]
**Describe the bug**
Intermediary many-to-many table with `queries: null` does not create auth perms. Removing `queries: null` will successfully result in 

**Amplify CLI Version**
4.18.1

**To Reproduce**
1. Generate intermediary many-to-many relation, disabling direct queries with `@model(queries:null)`
2. Add authorization permissions to model using `@auth` directive.
3. `amplify push`
4. Check generated AppSync schema, no auth directives are carried to the model. Attempting to traverse many-to-many relation in either direction will fail with `Unauthorized`
5. Remove `queries:null` from intermediary table, run ``amplify push`
6. Generated AppSync schema now contains proper auth directives such as `@aws_api_key`, etc. 

**Expected behavior**
I would expect authorization for the many-to-many relations to be configurable using the @auth directive on the table itself. If this was not the intention, and we are not supposed to configure auth from the intermediary table but rather at the field-level, I believe this should be documented. In either case, I'm willing to submit a PR to address this.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Node Version: 10.13.0

**Additional context**
Sample schema:
```graphql
type Post
  @model {
  tags: [TaggedPost] @connection(keyName: "byPost", fields: ["id"])
}

type TaggedPost
  @model(queries: null)
  @auth(
    rules: [
      { allow: private }
      { allow: public, provider: apiKey, operations: [read] }
    ]
  )
  @key(name: "byPost", fields: ["postID", "tagName"])
  @key(name: "byTag", fields: ["tagName", "postID"]) {
  postID: ID!
  tagName: ID!
  post: Post! @connection(fields: ["postID"])
  tag: Tag! @connection(fields: ["tagName"])
}

type Tag
  @model
  @key(fields: ["name"]) {
  name: ID!
  description: String
  posts: [TaggedPost] @connection(keyName: "byTag", fields: ["name"])
}
```

**Comment by SwaySway** [comment]
Hello @quorth0n 
Since the queries are disabled for tagged post are you looking at allowing access to tagged post from Post and/or Tag? You can add field auth on Post and Tag to allow read on TaggedPosts
An example of this kind of implementation below
```gql
type Post
  @model {
  id: ID!
  tags: [TaggedPost] @connection(keyName: "byPost", fields: ["id"]) @auth(rules: [ { allow: public, provider: apiKey, operations: [read] } ])
}

type TaggedPost
  @model(queries: null)
  @auth( rules: [
    { allow: private }
  ] )
  @key(name: "byPost", fields: ["postID", "tagName"])
  @key(name: "byTag", fields: ["tagName", "postID"]) {
  id: ID!
  postID: ID!
  tagName: ID!
  post: Post! @connection(fields: ["postID"])
  tag: Tag! @connection(fields: ["tagName"])
}
type Tag @model {
  id: ID!
  description: String
  posts: [TaggedPost] @connection(keyName: "byTag", fields: ["id"]) @auth(rules: [ { allow: public, provider: apiKey, operations: [read] } ])
}
```

**Comment by quorth0n** [comment]
@SwaySway thank you, that is the solution I ended up using and accurately addresses my use case. I believe a quick blurb in the docs may be helpful in case anyone else shares this question, let me know if you'd like me to submit a PR to include that.
