### ISSUE TITLE
How to add one custom resolver in the auto-generated stack cloudformation template

### ISSUE THREAD

**Issue by darshannahar** [aws-amplify/amplify-cli#4363]
**Which Category is your question related to?**
api

**Amplify CLI Version**
4.20.0

**What AWS Services are you utilizing?**
Appsync

**Provide additional details e.g. code snippets**
I want to replace one of the auto-generated Create mutation resolver by a custom resolver to use TransactWriteItems for dynamoDB.

1. Is there a way to just overwrite only the impacted resources (IAMRole, DataSource and Resolver) in the autogenerated  stack template? I do not want to maintain the entire cloudformation template myself for resources that I am not touching.
1. Is there any other way / directive to add TransactWriteItems resolver?

**Comment by ammarkarachi** [comment]
@darshannahar what are you trying to achieve maybe there is a potential we can guide you with?

**Comment by darshannahar** [comment]
Lets take below example.
There are two models: Blog and Comment. One Blog can have many comments and a comment belongs to exactly one blog.
On the page where we show blogs, we also want to show total comment count.
Now it is not efficient to retrieve all comments for each blog and then take a count. Hence, on the blog model we have a property called Comment count.
Whenever a new comment is added (or deleted) - We want to transactionally write to both DynamoDBs - Add a comment in Comment Table and Increment the comment-count in Blog table.

I know this can also be done using DynamoDB stream + lambda - above is an analogy, so lets assume we need to go with the architecture to dual write to both tables.

Hence in the vtl for createComment mutation, I want to update both tables transactionally. I can do this by overriding and creating custom createComment mutation resolver. But I do not want to manually maintain entire cloud-formation template for blogs and comments. I would rather prefer a mechanism to override few resources created in the auto-generated cloud-formation template.

@ammarkarachi Please let me know if you have any questions. Could you guide here?

**Comment by edwardfoyle** [comment]
Hi @darshannahar you can overwrite just one of the resolvers and still have all the rest be auto generated. The easiest way to do it is to copy the resolver you want to modify from `amplify/backend/api/build/resolvers` into `amplify/backend/api/resolvers` (outside of the build folder). Make sure to keep the filename the same, but you can modify the contents of the file and it will update that resolver.

However, since it looks like you are trying to write to multiple tables on an update operation, you may need to write a custom lambda resolver. Documentation on how to do that can be found [here](https://docs.amplify.aws/cli/graphql-transformer/directives#function)

**Comment by darshannahar** [comment]
@edwardfoyle Can't I use TransactWriteItems apis from DynamoDB in a single resolver? The only outstanding issue is that I need a role that has access to multiple tables as described [here](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-transact.html#permissions). Unfortunately, I am not finding a way in amplify to do this.

**Comment by edwardfoyle** [comment]
@darshannahar Sorry for the delayed response; somehow didn't see that you responded. You've probably resolved your issue by now, but yes you could make a custom VTL resolver that uses TransactWriteItems. You would have to modify the policy applied to the role of the AppSync data source in the CFN template manually as we do not expose a way to configure that. You'll also have to take care that the modified CFN is not overwritten when you update the API using Amplify.
