### ISSUE TITLE
Remove Admin Queries in "amplify update auth"

### ISSUE THREAD

**Issue by ASchwad** [aws-amplify/amplify-cli#4366]
How can i remove the admin queries API? I cannot remove the api endpoint or the function. When i try to do that, i get referenced to amplify update auth. I cannot find an option in the amplify update auth cli to remove the admin query. Can i do this manually in the cloudformation files?

**Which Category is your question related to?**

amplify cli (update auth)

**Amplify CLI Version** 
4.18.0

**Comment by kaustavghosh06** [comment]
@ASchwad Did you try removing the REST API  using `amplify remove api` command and selection 'AdminQueries' and then `amplify remove function` to get rid of the Lambda backed function. I just tried to out and was able to remove my API resource.

**Comment by ASchwad** [comment]
Thanks!
