### ISSUE TITLE
API_PORTAL_GRAPHQLAPIIDOUTPUT in cognito hooks?

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#4368]
Hello,

Is it possible to get the variable API_PORTAL_GRAPHQLAPIIDOUTPUT inside cognito hooks? AFAIK we can only grant access to it with `amplify function add/update` yet cognito hooks aren't handled that way but inside `amplify auth update`.

Thanks.

**Comment by ammarkarachi** [comment]
Hi @damianrr we don't support adding support but you could add  a custom workflow to your auth workflow as shown in the [docs](https://docs.amplify.aws/cli/usage/customcf)

**Comment by josefaidt** [comment]
Closing as issue has since been resolved. To grant access to your GraphQL API from the Cognito trigger, run `amplify update function` and follow the prompts to grant resource permissions.
