### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by varunpsr** [aws-amplify/amplify-cli#4369]
**Describe the bug**
When we run `amplify push` on our project, we get an error `Maximum policy size of 10240 bytes exceeded for role mspbeLambdaRole53878999-staging (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded.`
We have 51 types in our schema and 27 lambda triggers, this error came up when we wanted to push the 27th lambda function.

**Amplify CLI Version**
4.20.0

**Expected behavior**
Push to the cloud without any hiccups.

**Desktop (please complete the following information):**
 - OS: Windows and Mac
 - Node Version. 12.14.0

**Comment by ammarkarachi** [comment]
@varunpsr We have a way off minifying CF templates can you try using `amplify push --minify-stack-template`. Let me know if this helps

**Comment by SwaySway** [comment]
Closing as a duplicate of #3815
