### ISSUE TITLE
API gateway as a proxy

### ISSUE THREAD

**Issue by iudelsmann** [aws-amplify/amplify-cli#437]
**Which Category is your question related to?**
API Gateway

**What AWS Services are you utilizing?**
API Gateway, Lambda

**Provide additional details e.g. code snippets**
Hello all. In my application we currently need to use a custom authenticator for our request (we do not use cognito, not yet at least). We solved this with an API gateway that serves as a proxy to appsync, performing the authentication and then forwarding the request. Is it possible to create/describe this using amplify cli, or must all endpoints run lambda functions? (obs: I don't mind if I have to edit the descriptors manually)

**Comment by kaustavghosh06** [comment]
@iudelsmann AppSync provides a range of security options. The CLI currently provides API key and Cognito authentication support and you could probably leverage that instead of using an API GW proxy. Let me know if you've more questions around it.
