### ISSUE TITLE
Can't `amplify push` 'cannot read join property of null' error

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#4372]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I basically added a couple of cognito hooks and tried to `amplify push` my changes and I get the following error: "An error occurred when pushing the resources to the cloud
Cannot read property 'join' of null. An error occurred during the push operation: Cannot read property 'join' of null" see this: https://imgur.com/a/qTydLGM

**Amplify CLI Version**
Amplify version: 4.18.0

**Comment by damianrr** [comment]
FYI: this is also happening with latest Amplify CLI: 4.21.0

**Comment by kaustavghosh06** [comment]
@damianrr How were you able to resolve the issue?

**Comment by damianrr** [comment]
@kaustavghosh06 I restored my backend (`amplify pull --restore`) (and added my auth hooks again and it changed the error, now at least it tries to push. 
I'm having now: `(AWS::AppSync::GraphQLSchema Tue May 26 2020 12:12:59 GMT-0400 (Eastern Daylight Time) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;)` I was about to do some digging to be sure it wasn't an error on my side, and if not, open a ticket with the appropriate error message.

**Comment by kaustavghosh06** [comment]
@damianrr I believe the above issue is due to your API Key being expired. You can find the resolution steps out here  to rotate your API Key -  https://docs.amplify.aws/cli/graphql-transformer/config-params#createapikey

**Comment by damianrr** [comment]
That was it @kaustavghosh06. Thanks.

**Comment by KandarpAjvalia** [comment]
https://github.com/aws-amplify/amplify-cli/issues/3213#issuecomment-635741833

**Comment by mruzekw** [comment]
I'm also running into this now. Already try these steps:

>deleting node_modules and yarn.lock
>npm install (not using yarn now)
>amplify push

They worked for the env I was on, but the moment I switched to a different env, it reoccured. Redoing the steps doesn't help.

Happens on push and publish.

**Comment by mruzekw** [comment]
Turned out I had some old lambda references in the Amplify config files. Something was missed when I removed the lambda I guess. Manually removing the references put me in the clear.

**Comment by Tom-RulesCube** [comment]
I'm getting this exact message. After an attempt at merging new work from another branch/env ... 
from the new env:
```
amplify env checkout oldenv
amplify push
git add .
git commit ...
# other dev checks out project, amplify status seems right, makes changes
amplify push
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

Cannot read property 'join' of null
An error occurred during the push operation: Cannot read property 'join' of null
```

**Comment by Tom-RulesCube** [comment]
We generally avoid using `amplify pull` because it seems to result in crashed environments like this and this is, essentially, a dress rehearsal for mergin into the release branch for a beta, so some pressure here on finding a path to manage branches and merges here --- before we could hack around it

**Comment by Tom-RulesCube** [comment]
... and then he notices this issue is closed ... will open a new one

**Comment by jeremie-olivier** [comment]
I got this got it fixed using `amplify remove function` instead of doing a `rm -Rf myFunctionFolder`

**Comment by ahtokca** [comment]
> Turned out I had some old lambda references in the Amplify config files. Something was missed when I removed the lambda I guess. Manually removing the references put me in the clear.

yes. For it was the issue as well. backend-config.json had references to non existing lambdas! Thanks a lot !

**Comment by jjborie** [comment]
`backend-config.json had references to non existing lambdas`

@ahtokca thank you, got exactly the same issue!

**Comment by prog585** [comment]
I have referenced a lamda function in my schema but not created it in local environment. After adding missing function pushed and it worked.

**Comment by flogy** [comment]
For me it was that the `src` directory inside the function directory was missing.
