### ISSUE TITLE
"Amplify Publish" fails -  Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by prakash-mu** [aws-amplify/amplify-cli#4378]
Hello,
When I perform "amplify publish" it fails with the message that  `Cannot read property 'name' of undefined at Object.publish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/index.js:39:13)**`

I am using cloud9 IDE with a docker for react-native-expo.

I package.json I has added the line in scripts "build": "expo build:web",

```
⠦ Deploying build artifacts to the Amplify Console..Job Timeout before succeeded
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
**Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.publish (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/index.js:39:13)**
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ammarkarachi** [comment]
@prakash-mu Can you let us know the CLI version you are using and the resources you have provisioned?
