### ISSUE TITLE
amplify-appsync-simulator `$util.isNullOrEmpty` returns false for empty string

### ISSUE THREAD

**Issue by MainAero** [aws-amplify/amplify-cli#4386]
https://github.com/aws-amplify/amplify-cli/blob/4c0c692fa6cab2e8461f20099581ff8d7d7504f8/packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts#L73

should be `return !value;` or?

**Comment by ammarkarachi** [comment]
@MainAero Thanks for bring this to our attention we will have a fix out soon.

**Comment by edwardfoyle** [comment]
Based on discussion in https://github.com/aws-amplify/amplify-cli/pull/4394, closing this as a wontfix
