### ISSUE TITLE
Question: amplify-appsync-simulator `$util.isString` returns false for string

### ISSUE THREAD

**Issue by MainAero** [aws-amplify/amplify-cli#4390]
Why does this function compares against `JavaString`?

https://github.com/aws-amplify/amplify-cli/blob/4c0c692fa6cab2e8461f20099581ff8d7d7504f8/packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts#L92

**Comment by ammarkarachi** [comment]
In velocity the values get typed to Java types and we only need to check for that.
