### ISSUE TITLE
Amplify Aurora serverless SQL injection

### ISSUE THREAD

**Issue by geoffreyaguero** [aws-amplify/amplify-cli#4391]
Hi There,

I'm using Amplify to create a GraphQL API with an Aurora Serverless datasource. I'm currently trying to fix a problem with an apostrophe that is breaking my query which is a completely different issue but now this makes me wonder if the **default resolvers** that Amplify generate when running `amplify api add-graphql-datasource` are susceptible to SQL injection.

I'd appreciate if you can clarify this.

**Comment by undefobj** [comment]
Hi @geoffreyaguero the default resolvers use the input sanitization from the AppSync documentation: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html#input-sanitization
That being said we encourage all customers to review their input vectors and apply additional controls if necessary.
