### ISSUE TITLE
How to connect android app with AppSync with already working app of iOS with the appsync?

### ISSUE THREAD

**Issue by parthsoni42** [aws-amplify/amplify-cli#4395]
I want to know that I have make a working app with usage of AWS AppSync and amplify datastore in iOS. The app has working mutations of the data.

Now I have build android app with the same feature but it has created a new API and tables in my AWS DynamoDB and AWS AppSync. 

**Expected behaviour** 
Both app should be connect with one DynamoDB and AppSync API.

Can any anyone guide me on this?

Thanks in advance.

**Comment by ammarkarachi** [comment]
With Amplify you can have multiple frontends with a single backend you can find more info [here](https://docs.amplify.aws/cli/teams/multi-frontend)

**Comment by parthsoni42** [comment]
Thank you @ammarkarachi for the reply. I will try by the following document provided by you.
