### ISSUE TITLE
aws_exports not updating after `amplify env checkout xxxx`

### ISSUE THREAD

**Issue by bwalsh** [aws-amplify/amplify-cli#4396]
**Describe the bug**
aws_exports not updating after `amplify env checkout xxxx`
https://github.com/aws-amplify/amplify-cli/issues/2635

**Amplify CLI Version**
amplify -v
4.18.1

**To Reproduce**
* Create two environments with auth.
* Push same to host
* use `amplify env checkout xxxx`

**Expected behavior**
The aws_exports file should update.

**Comment by ammarkarachi** [comment]
@bwalsh We have released version 4.21.0 this Tuesday. It should have been fixed.
