### ISSUE TITLE
Lambda BatchInvoke on local environment

### ISSUE THREAD

**Issue by lucabernardino** [aws-amplify/amplify-cli#4404]
When calling BatchInvoke on a Lambda function in app sync the payload and response changes so that now app sync expects an array of values for both. This is fine, except when writing code and testing locally BatchInvoke does not work. Calling the Lambda function locally with Amplify will always treat the function call as a regular "Invoke" and so its difficult to test. It's annoying to have two different responses, one for local and one for the real appsync environment.

Am I missing something here? Whats the best way to BatchInvoke a Lambda function and have it consistent across local and once deployed?

**Comment by ammarkarachi** [comment]
Are you trying to call AppSync API from mock Lambda function?

**Comment by lucabernardino** [comment]
Not exactly. Whenever I run amplify mock and I'm testing my code locally BatchInvoke will still call the Lambda function once for reference instead of batching them together. For example say I had this graphQL structure

`
listUsers {
     name
     email
     posts {
        title
        description
     }
}
`

If the response returns 2 users then BatchInvoke will ensure that the posts field lambda function gets called only once. Thereby preventing the N+1 issue.

However when doing this locally the lambda function still gets called twice, making it hard to test and debug
