### ISSUE TITLE
Document how to generate  team-provider-info.json

### ISSUE THREAD

**Issue by MarshHawk** [aws-amplify/amplify-cli#4408]
I accidentally irrecoverably deleted team-provider-info.json

Instead of starting over, I would like to be able to regenerate this file if I have the rest of the project including files with secrets. 

Also, if this is already possible, can you document the process maybe?

**Comment by UnleashedMind** [comment]
@MarshHawk 
How many backend environment have you created for your project? do you still remember their names? and the aws regions that they are created in? 
You can go to the S3 deployment bucket and find the zip file #current-cloud-backend.zip for each of the backend environment. 
The information needed to reconstruct the team-provider-info.json file is available in those files.

**Comment by UnleashedMind** [comment]
Closing the ticket now for lack of response.
Feel free to open a new ticket if this is still an issue.
