### ISSUE TITLE
@searchable directive changes Int to Float + Does not work with Date formats.

### ISSUE THREAD

**Issue by mikeRChambers610** [aws-amplify/amplify-cli#4411]
**Describe the bug**
@searchable directive changes Int type to Float type in elastic search. This breaks the range filter because float cant handle big numbers. Also, @searchable does not work with the Date scalar types. This eliminates 90% of all use cases where you would apply a range filter to @searchable.

**To Reproduce**

Using AppSync via console and @searchable directive.

**Expected behavior**
Int should be passed to elastic search as an Int or even a Double but not a Float.

Thanks for the help in advance!

**Comment by ammarkarachi** [comment]
@mikeRChambers610 do you have a schema I can work for the int to date issue? We have a fix in review for the date types https://github.com/aws-amplify/amplify-cli/pull/3432

**Comment by quorth0n** [comment]
@mikeRChambers610 as a temporary workaround before the PR is merged, maybe you can look to this solution to perform range queries with the proper Date* scalar https://github.com/aws-amplify/amplify-cli/issues/1044#issuecomment-575212129
