### ISSUE TITLE
Amplify Mock does not allow GSI sort keys to be null during mutation 

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#4413]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify Mock does not allow GSI sort keys to be null during mutation in 4.22.0
It used to work until 4.18.0

**Amplify CLI Version**
4.22.0

**To Reproduce**
Create a @Key model with secondary keys. Now try to create new entries with the GSI sort key as null. Now try the mutation and create an entry with no value for GSI Sort Key attribute (something like createdAt). This will throw an error stating that the sort key can not be null. Now revert to amplify cli version 4.18.0 and the error goes away. 

**Expected behavior**
GSI sort keys can be null that is how partial or sparse indexes work in DynamoDB. 

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: AWS AMI for Cloud9
 - Node Version. Not applicable

**Additional context**
Not Applicable

**Comment by arkllc** [comment]
Any updates? I just tried Amplify cli version 4.24.2 and the issue still persists.

**Comment by arkllc** [comment]
Dear @ammarkarachi 
appreciate any updates you can provide.

**Comment by kaustavghosh06** [comment]
Hi @arkllc Sorry for the lack of response on this thread. We'll be looking into this issue.

**Comment by arkllc** [comment]
Thanks @kaustavghosh06 I am stuck on older version until this bug is fixed So appreciate if you keep me posted as you make progress

**Comment by arkllc** [comment]
Hi @yuth, thanks for the response. I just logged in into GitHub so sorry for the late response. 

Yes, it is a runtime error. I have not pushed the changes actually test it out. Are you saying that this is not allowed in even when its pushed and not limited to mock?

Please refer to DynamoDB documentation here - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html

Here is the section on the page - 
"A global secondary index only tracks data items where its key attributes actually exist. For example, suppose that you added another new item to the GameScores table, but only provided the required primary key attributes.
Because you didn't specify the TopScore attribute, DynamoDB would not propagate this item to GameTitleIndex. Thus, if you queried GameScores for all the Comet Quest items, you would get the following four items. A similar query on GameTitleIndex would still return three items, rather than four. This is because the item with the nonexistent TopScore is not propagated to the index."

So what I am trying to do is actually allowed per DynamoDB documentation. So AppSync / amplify-cli should not throw an error. 

Also, the bug referenced is not saying that sort key must be mandated. It is simply pointing out that the way it is stored causes some issues. But the fix somehow forces the gsi sort key to be mandatory and that's where it is incorrect as highlighted above.

**Comment by arkllc** [comment]
Hi @yuth Any updates on this is greatly appreciated.

**Comment by arkllc** [comment]
@yuth any updates here? I am stuck here. Hence the question.

**Comment by nikhname** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-cli/issues/5468
