### ISSUE TITLE
amplify add analytics - AWS Pinpoint reports CORS policy issue. 

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#4414]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Add AWS Pinpoint functionality using the documented method:
amplify add analytics
* allowing unauthenticated access

Try to record an event a react web app and receive a CORS policy issue:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pinpoint.us-east-1.amazonaws.com/v1/apps/805e7c17fed........../endpoints/9331d680-a11a-11ea-812e------------ (Reason: CORS header 'Access-Control-Allow-Origin' missing)

I've done everything your documentation states but I cannot record an event. Surely I shouldn't need to start messing around with IAM policies to record an event?

**Amplify CLI Version**
4.18.0

**To Reproduce**
As above. Add analytics and try to record an event. Check developer console and see the CORS policy issue.

**Expected behavior**
I've done everything your documentation states but I cannot record an event. Surely I shouldn't need to start messing around with IAM policies to record an event?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - NodeJS: v12.11.1

**Comment by ammarkarachi** [comment]
@kylekirkby I can see that an OPTIONS method to pinpoint is throwing an unauthenticated. We will be investigating this

**Comment by kylekirkby** [comment]
@ammarkarachi - thanks for looking into this!

**Comment by kylekirkby** [comment]
Any update on this? It appears my issue is related to using Cognito User Groups. The users in a group don't have the permissions to push analytics to pinpoint. I'm trying to resolve using a very hacky approach noted here:

https://github.com/aws-amplify/amplify-js/issues/2908

I believe that the amplify team will need to update the permission for user groups (if used) to push to pinpoint.
Best regards,

Kyle

**Comment by BruceWheaton** [comment]
I just ran into this. For authenticated users, though. 
I had to make a role (the pinpoint console has a snippet to copy), and assign it to the role for *every* group in my user pool.

**Comment by kaustavghosh06** [comment]
@BruceWheaton That's a workaround which should work. Or you can attach policies to groups based on the steps mentioned here - https://docs.amplify.aws/cli/auth/groups#group-access-controls

**Comment by kaustavghosh06** [comment]
@kylekirkby Are you still blocked on this issue?

**Comment by yonatanganot** [comment]
@kaustavghosh06 we also having this issue.
Do you have an estimation for a native solution?

**Comment by josefaidt** [comment]
swapping feature-request for pending-triage to reconfirm whether this is still active

**Comment by josefaidt** [comment]
Closing as this issue has since been resolved. After adding analytics we are able to successfully record events

```js
import { Analytics } from 'aws-amplify'

export default function HomePage() {
  return (
    <div>
      <h1>Home Page</h1>
      <button onClick={() => Analytics.record({ name: 'Clicked button' })}>
        Click me
      </button>
    </div>
  )
}
```

![image](https://user-images.githubusercontent.com/5033303/216731725-a5bc26e2-879e-4e16-a4c4-e55ed490383f.png)
