### ISSUE TITLE
AppSync resolver TransactWriteItems have no permissions to access other than current table.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#4420]
**Describe the bug**
Assume we have 2 different tables (models) in amplify project.
Now we try to modify resolver for one table and replace operation PutItem with TransactWriteItems. In TransactWriteItems we modify both tables and when we perform mutation  we get error something like this:
```
arn:aws:sts::12312312313:assumed-role/TableOne-role/APPSYNC_ASSUME_ROLE is not authorized to perform dynamodb:UpdateItem on resource TableTwo.
```

**Expected behavior**
It would be great to have permissions to operate with multiple tables in one resolver via TransactWriteItems

**Comment by nikhname** [comment]
Hey @lenarmazitov, could you give a bit of detail about your use case for accessing multiple tables with the same resolver?

**Comment by lenarmazitov** [comment]
1. make aggregation updates in one resolver via TransactWriteItems.
2. make conditional checks before modify data via TransactWriteItems.

Instead of create lambda resolver it may be convenient just copy and modify resolver.

**Comment by nikhname** [comment]
@lenarmazitov By default we give transact permissions to only one table but you can manually add transact permissions to other tables by adding the table to ```Resource``` in the role: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-transact.html
