### ISSUE TITLE
Amplify update storage - add function error

### ISSUE THREAD

**Issue by pseudyx** [aws-amplify/amplify-cli#4423]
**Describe the bug**
Adding Lambda function through Amplify update storage.
accepting default create new function.
Amplify push returns error "An error occured during the push operation: Resource is not in the state stackUpdateComplete" 

**Amplify CLI Version**
4.21.0

**To Reproduce**
after successfully pushing Add storage, with options for allow auth and guest access.
go through Amplify update storage to add a function.

**Expected behavior**
lambda function successfully pushed to amplify backend.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. 12.16.3

**Additional context**
existing amplify project was pulled onto a new linux machine.
the only operations performed on the new linux machine is amplify pull and amplify update storage

**Comment by ammarkarachi** [comment]
@pseudyx Can you check what's the status of your stack in cloudformation?
