### ISSUE TITLE
API creation: Option to select DynamoDB billing mode

### ISSUE THREAD

**Issue by secretshardul** [aws-amplify/amplify-cli#4426]
**Is your feature request related to a problem? Please describe.**
When creating a new GraphQL API, DynamoDB billing mode is configured by default as ```PAY_PER_REQUEST```. The CLI does not provide an option to use ```PROVISIONED``` billing. This is a problem for those wishing to remain under AWS free tier.

**Describe the solution you'd like**
The CLI should provide an option to use ```PROVISIONED``` billing and set read/write capacity units.

**Describe alternatives you've considered**
A workaround is to manually edit the API's ```parameters.json``` file.
```
{
    "AppSyncApiName": "myAPI",
    "DynamoDBBillingMode": "PROVISIONED",
    "ReadCapacityUnits": 5,
    "WriteCapacityUnits": 5,
    "DynamoDBEnableServerSideEncryption": "false",
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "authrgoAuth",
            "Outputs.UserPoolId"
        ]
    }
}
```

**Additional context**
According to #661, ```PROVISIONED``` throughput was the default option some time back.

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.

**Comment by SamWSoftware** [comment]
Can this issue be re-opened please. The ability to select PAY_PER_REQUEST would be very useful
