### ISSUE TITLE
Really strange behavior...anyone else experience?

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#4429]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

AWS Amplify CLI

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.21.0

**What AWS Services are you utilizing?**

Amplify, appsync, cognito, s3, etc

**Provide additional details e.g. code snippets**

Two days ago updated to latest amplify-cli and sdk, now using expressvpn vpn as I have done for a few years, I can't reach endpoints in the US or Asia from the CLI.  Don't know how to explain as I am not that savvy at DNS issues.  If others have any ideas, much appreciated.

**Comment by nikhname** [comment]
@weisisheng, which regions in Asia and the US are unable to be reached?

**Comment by weisisheng** [comment]
They are ap.southeast.1 and us.west.2.  I have done some scouring around the last few days and still can't find anything related to this type of issue + VPNs.  Using lantern or outline, both work although I have to monkey around with setting proxies on the CLI.

**Comment by nikhname** [comment]
Hi @weisisheng the unavailability is outside of the scope of the CLI, and unfortunately we do not support using VPNs at this time so we can't provide any insight as to why expressvpn stopped working with those regions.

**Comment by vfulco** [comment]
Sure, I understand. It was suggested in one of the discord groups that I post here, so gave it a shot.  Cheers.
