### ISSUE TITLE
Can't get amplify CLI to install where I can "see" it 

### ISSUE THREAD

**Issue by Jvalal** [aws-amplify/amplify-cli#443]
**Describe the bug**

Trying to follow the instructions n the gatsby page to install aws amplify and it doesn't work! 

When I try and configure it tells me "command not found".

![image](https://user-images.githubusercontent.com/3803053/48440511-ee30d880-e73d-11e8-8b22-4202081209e9.png)

**Comment by kaustavghosh06** [comment]
Can you just run ‘npm install -g @aws-amplify/cli’ without the i?

**Comment by Jvalal** [comment]
sure- no dice.

![image](https://user-images.githubusercontent.com/3803053/48440828-c68e4000-e73e-11e8-9929-eff8603c6b4c.png)

**Comment by yuth** [comment]
what is your PATH. You can find this by running
```bash
echo $PATH
```

**Comment by Jvalal** [comment]
![image](https://user-images.githubusercontent.com/3803053/48441294-030e6b80-e740-11e8-9e67-6e085d95d136.png)


/Users/jkidd/GoogleDrive/PROJECTS/MachineLearning/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

**Comment by yuth** [comment]
What version of `node`  do you have installed?

**Comment by Jvalal** [comment]
10.11.0

![image](https://user-images.githubusercontent.com/3803053/48441682-fdfdec00-e740-11e8-8842-88bc0f8bc76e.png)

**Comment by yuth** [comment]
Thanks. Can you check if you have `@aws-amplify/cli` in your `/usr/local/lib/node_modules/` directory

**Comment by Jvalal** [comment]
nope, not there. 

![image](https://user-images.githubusercontent.com/3803053/48442209-66010200-e742-11e8-8e75-0929dff47a07.png)

**Comment by kaustavghosh06** [comment]
@Jvalal IC an see where the issue could be from your screenshots: 
After, successful `npm install -g @aws-amplify/cli`, here's how the `/usr/local/lib/node_modules/` and the `/usr/local/bin/` should look like:

![screen shot 2018-11-13 at 12 58 03 pm](https://user-images.githubusercontent.com/7247658/48442699-cb092780-e743-11e8-8a57-bf8d9bce04f5.png)

As you see there's @aws-amplify in the node_modules/ dir and amplify in bin/

From your screenshots i inferred that that the above mentioned files/packages are added in `/Users/jkidd/.node_modules_global/node_modules` & `/Users/jkidd/.node_modules_global/bin`. So you might want to add `/Users/jkidd/.node_modules_global/bin` to your $PATH. Also to cross-verify, please check `/Users/jkidd/.node_modules_global/bin` to see if `ampify` exe is present.

**Comment by Jvalal** [comment]
thanks- how would I do that. I always thought adding the -g added it globally. So I guess I'm not sure how that's behainvg then?

**Comment by kaustavghosh06** [comment]
@Jvalal Your setup seems different from an usual node setup. It might be tied to how you installed node. 
To add dir to your path open up your` ~/.bashrc` file and add `export PATH="/Users/jkidd/.node_modules_global/bin:/Users/jkidd/.node_modules_global/node_modules:$PATH"`

**Comment by Jvalal** [comment]
ok. that wasn't done on purpose, probably a mistake on my side. So, anything that gets me to a "normal" install would be helpful

**Comment by kaustavghosh06** [comment]
@Jvalal When you run `npm install -g <any-cli>` it downloads it in `/usr/local/bin/` (given you're not using nvm) and since `/usr/local/bin/` is in your `$PATH`, its able to pick it up. In your case, the global node directory is set to `/Users/jkidd/.node_modules_global/bin` and all the CLI's or package installed would be installed would be installed in `/Users/jkidd/.node_modules_global/bin`. Since `/Users/jkidd/.node_modules_global/bin` is not defined in your $PATH, hence the command won't be found. Once you add it to your $PATH as mentioned above, it should work as expected. Note: Once you change your $PATH, you might have to re-start your terminal for the change to take into affect.

**Comment by kaustavghosh06** [comment]
@Jvalal  You can learn more the bashrc file and editing it out here -> https://answers.ros.org/question/87866/how-to-edit-the-bashrc-file/

**Comment by yuth** [comment]
Closing. Please feel free to re-open

**Comment by Jvalal** [comment]
I completely fumbled something here. I thought I updated the file, but no none of the commands work and I can't find the file any more.

![image](https://user-images.githubusercontent.com/3803053/48451026-7672a600-e75d-11e8-8f9a-32b5b46bb833.png)

**Comment by Jvalal** [comment]
UGH! still no dice after updating bash.

![image](https://user-images.githubusercontent.com/3803053/48498465-2d693300-e7eb-11e8-9376-e8e5ce333ba4.png)

**Comment by Jvalal** [comment]
*bump*

**Comment by yuth** [comment]
If you run `~/.npm-globa/bin/amplify` you should see amplify help screen. The problem you are facing is your npm bin folder is not in your system PATH. Just to be clear this is not an amplify issue, but how your NPM and PATH are configured.

You could try running the following command in terminal
```bash
echo "PATH=$PATH:/User/jkidd/.npm-globa/bin/amplify"  >> ~/.bashrc
```

**Comment by Jvalal** [comment]
Yes, I can see that help screen. Yes, I ran that in the terminal, but I don't know if anything happened. Ultimately it's me not understanding how to resolve the larger issue.

![image](https://user-images.githubusercontent.com/3803053/48640253-fcbfff80-e98a-11e8-975e-ddaa4bb6c320.png)

**Comment by yuth** [comment]
I had made a typo in the snippet I had provided earlier(which is updated now). If the command was successful, then if you do `echo $PATH` in your shell, you should see `/User/jkidd/.npm-globa/bin/` printed along with previously set path.

**Comment by Jvalal** [comment]
ran it and just got this 
![bash](https://user-images.githubusercontent.com/3803053/48657842-29583380-e9ec-11e8-8147-c12541fce30a.gif)
