### ISSUE TITLE
When creating an AppSync using Amplify CLI, how to integrate with existing Coginito userpool and identity.

### ISSUE THREAD

**Issue by isheejong** [aws-amplify/amplify-cli#4430]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
AppSync and Cognito

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
`4.21.0`

**What AWS Services are you utilizing?**
AppSync
Cognito

**Provide additional details e.g. code snippets**

Hi there,

If I would create the AppSync using amplify CLI, it will be need to integrate Cognito UserPool and IdentityPool. however, in case that Cognito was already provisioned, how to integrate the Appsync with existing Cognito in amplify CLI?

**Comment by ammarkarachi** [comment]
@isheejong For now you would have overwrite the config created by CLI with existing values but we are working on an implementation to make that more seamless to.

**Comment by isheejong** [comment]
> @isheejong For now you would have overwrite the config created by CLI with existing values but we are working on an implementation to make that more seamless to.

Thank you for response. 
Our team has a plan to enhance our application which was implemented by amplify as monolithic to microservices architecture based on micro frontends. 

👍 
Thanks :)

**Comment by jhockett** [comment]
Hi @isheejong, we have an RFC for importing existing resources into an Amplify project. 
See here: https://github.com/aws-amplify/amplify-cli/issues/3977

Closing this issue since it's being tracked in the RFC.
