### ISSUE TITLE
AWS CLI Command Issue

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#4431]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I try to create schema using AWS CLI command `aws appsync start-schema-creation --api-id xxxxxxxxxxxxxxxxxxxxxxxxxx --definition file://D:\path\to\file\file.graphql --profile xxxx --region us-xxxx`

It's not creating all the schema definitions, the file size is 195 KB but only 152 KB is been created when checked Appsync console

**Amplify CLI Version**
3.0.13

**Expected behavior**
Contains following
```
{
    "status": "SUCCESS",
    "details": "Successfully created schema with 586 types."
}
```
but getting only
```
{
    "status": "SUCCESS",
    "details": "Successfully created schema with 496 types."
}
```
Using AWS CLI version 2 for Windows machine

**Comment by nikhname** [comment]
Hi @meetrij this is the Amplify CLI repository, I recommend you create an issue here: https://github.com/aws/aws-cli

**Comment by meetrij** [comment]
@nikhname Thank you
