### ISSUE TITLE
Not able to build new iOS project

### ISSUE THREAD

**Issue by Leinadzet** [aws-amplify/amplify-cli#4432]
**Describe the bug**

After I integrate the amplify-tools.sh script "${PODS_ROOT}/AmplifyTools/amplify-tools.sh" into my project I cant build it anymore. It generates all the associated files and folders but that's it. 

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/8782897/83411838-49f2ad80-a419-11ea-8ab6-faff63eba2dc.png">

**To Reproduce**
1. created the Xcode Project "Todo"
2. installed pods, see pod file: 

<img width="669" alt="image" src="https://user-images.githubusercontent.com/8782897/83412305-24b26f00-a41a-11ea-92d9-4e914e95fbe7.png">

Got no errors while doing so:

![Screenshot 2020-06-01 at 15 06 40](https://user-images.githubusercontent.com/8782897/83412328-2da34080-a41a-11ea-81fc-8945d9cc6f4c.png)

There are a ton of warnings only shown really shortly, after that I just see "Build Failed" and cant make the app run. It is also not generating the model files when I set "modelgen=true". 

<img width="233" alt="image" src="https://user-images.githubusercontent.com/8782897/83411992-a3f37300-a419-11ea-885c-9b067fdcb834.png">

**Expected behavior**

**Screenshots**

**macOS Version:**
<img width="253" alt="Screenshot 2020-06-01 at 15 09 28" src="https://user-images.githubusercontent.com/8782897/83412397-490e4b80-a41a-11ea-859c-6fc308b62e2e.png">

** Xcode Version:**
<img width="301" alt="Screenshot 2020-06-01 at 15 09 00" src="https://user-images.githubusercontent.com/8782897/83412388-44e22e00-a41a-11ea-91dc-8293746abc3d.png">

**Cocoapod Version:**
1.9.3

**Node Version:**
12.14.0

**Amplify CLI Version:**
4.21.0

**Comment by nikhname** [comment]
We made a change to amplify-app and the structure of the generated files which may have fixed this. The warnings you are describing seem related to amplify-ios, I would suggest creating an issue in their repo if you want to pursue this further.

**Comment by Leinadzet** [comment]
Okay - will do so. 

Thanks

Daniel
