### ISSUE TITLE
Combining non-unique sorting and pagination with @searchable

### ISSUE THREAD

**Issue by quorth0n** [aws-amplify/amplify-cli#4434]
I'm trying to combine pagination using nextToken with sorting in a single graphql query, like so: 
```js
  const topPosts = await API.graphql(
    graphqlOperation(searchPosts, {
      sort: {
        field: 'totalScore',
        direction: 'desc',
      }
    })
  );
```
In my case, the `totalScore` field is a float. Thus, because the way the resolver is generated, this will be the only field used for the ElasticSearch `sort` parameter.
```
## ...
"sort": [{$sortField0: { "order" : $util.toJson($sortDirection) }}],
## ...
```

This is a problem when attempting to paginate on the returned data. In my case totalScore is a non-unique field, and thus cannot be used by itself for the `search_after` parameter in the ES request. The nextToken returned will always be the totalScore of the last item queried.

To work around this, I attempted to override the generated searchPosts resolver:
```
  "params": {
      "body":     {
                #if( $context.args.nextToken )"search_after": ,$context.args.nextToken, #end
                "size": #if( $context.args.limit ) $context.args.limit #else 100 #end,
                "sort": [{$sortField0: { "order" : $util.toJson($sortDirection) }} #if( $sortField == "id" ) #else, {"_id": { "order": "desc" }} #end],
                "version": false,
                "query": #if( $context.args.filter )
$util.transform.toElasticsearchQueryDSL($ctx.args.filter)
```
I also overrode the relevant SearchInput type in my schema to accept and return `nextToken` as an array. Thus, with this code, I intended for the field to be sorted by my specified field, while using the unique id as a tie-breaker. Then the returned nextToken would be an array of the last returned item for both. However, when using this array in the request with the above code, my ID was not parsed properly as a String and would throw a syntax error in the VTL. Let me know how I should best approach my scenario.

**Which Category is your question related to?**
AWS ElasticSearch via @searchable 

**Amplify CLI Version** 
4.20.0

**What AWS Services are you utilizing?**
AppSync, ES

**Comment by not-only-code** [comment]
Same problem here.

**Comment by capitan-ariete** [comment]
> Same problem here.

IDEM. Same problem here

**Comment by dogsonacid** [comment]
same

**Comment by yaquawa** [comment]
same here, #6729
I also tried the workaround, but not sure why it won't work.. @quorth0n have you solved this problem?

**Comment by danielesalvatore** [comment]
Same here

**Comment by renebrandel** [comment]
Hi folks - we're planning on addressing this as part of our new GraphQL transformer. The approach is captured here in our RFC: https://github.com/aws-amplify/amplify-cli/issues/7546 love to hear your feedback!

**Comment by matteocarpi** [comment]
hey @renebrandel that's great news! Do you have any clue about the timeline? I know it might be a tricky question to answer, but even a rough idea would be mega useful. Like planning on releasing in a month, 1 year 5 years or 10? :D.

Thanks!!!
M

**Comment by renebrandel** [comment]
Hi folks - this feature is launched now. https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#paginate-over-search-results
