### ISSUE TITLE
Return trigger function response

### ISSUE THREAD

**Issue by user32-2** [aws-amplify/amplify-cli#4435]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify storage trigger

**Amplify CLI Version** 
4.20.0

**What AWS Services are you utilizing?**
Amplify

**Provide additional details e.g. code snippets**
Is it possible to get the callback response from a Storage trigger within my React application? The trigger fires successfully and is doing what I expect but I am unable to find a way to get a response.

**Where the function is triggered**
```     
Storage.put(this.props.uploadSource+'-'+this.props.tenant+'.csv', file, {
          contentType: 'text/csv'
      })
      .then (console.log)
      .catch(err => console.log(err));
```

**The lambda function response**
```
exports.handler = async (event, context, callback) => {
...
    console.log('API JSON Response2 = ${JSON.stringify(response2, null, 2)}');
    callback(null, "Lambda function complete");
  }
```

**Comment by kaustavghosh06** [comment]
@user32-2 The Storage trigger is an async process and there isn't a simple way to get it back as a part of your Storage.put() call which you make from your client. You'd need to either use some sort of a notification system to get a response back to your client. You can use DDB to maybe track a unique jobId or use SNS - but Amplify doesn't provide an out of a box solution for it at the moment.
