### ISSUE TITLE
Failed to start API Mock endpoint TypeError: arn.split is not a function

### ISSUE THREAD

**Issue by jaidisido** [aws-amplify/amplify-cli#4438]
**Describe the bug**
I receive error `Failed to start API Mock endpoint TypeError: arn.split is not a function` when I run `amplify mock`. However, I am able to push the amplify backend to the cloud without any issue.

**Amplify CLI Version**
Tested with amplify cli 4.18.0, 4.20.0 and 4.21.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
```amplify mock
Scanning for plugins...
Plugin scan successful

GraphQL schema compiled successfully.

Edit your schema at /Users/jaidi/Workspace/Otavalo/src/Otavalo/source/web/otavalo/amplify/backend/api/otavalo/schema.graphql or place .graphql files in a directory at /Users/jaidi/Workspace/Otavalo/src/Otavalo/source/web/otavalo/amplify/backend/api/otavalo/schema
Could not find ref for "authotavaloUserPoolId". Using unsubstituted value.
Failed to start API Mock endpoint TypeError: arn.split is not a function
```

**Expected behavior**
Being able to mock

**Screenshots**
No screenshots, but I have sent the project to amplify-cli@amazon.com

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.6
 - Node Version. v13.12.0

**Additional context**
Our backend uses a combination of:
- Cognito
- Lambda functions
- Custom AppSync Pipeline Resolvers

**Comment by mousamm** [comment]
I am facing the same issue, was there an update/resolution for this?

**Comment by jaidisido** [comment]
Update here. After removing the resources created in CustomResources.json entirely, amplify mock worked once more. I still don't know what is causing the issue but at least I know it's there
