### ISSUE TITLE
Cannot add new environment

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-cli#4441]
**Describe the bug**
Cannot add a new environment
**Amplify CLI Version**
4.21.0
**To Reproduce**
amplify env add newdev
**Expected behavior**
Environment to be created

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.5 Beta
 - Node Version. 13.11.0

**Additional context**
```
amuresia@Andreis-MacBook-Pro-2 infra % amplify env add newtest
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything

amuresia@Andreis-MacBook-Pro-2 infra % amplify env list

| Environments |
| ------------ |
| test         |
| prod         |
| *dev         |
amuresia@Andreis-MacBook-Pro-2 infra % amplify status

Current Environment: dev
...
```

**Comment by nikhname** [comment]
Hi @amuresia, you would need to enter 'No' for the question ```? Do you want to use an existing environment?``` to add the new environment. Feel free to comment if you have further questions

**Comment by amuresia** [comment]
Hi @nikhname, I want to copy an existing environment i.e. re-create existing resources so I believe `Yes` was the correct choice in `Do you want to use an existing environment?`. The output indicates that the operation was successful and that the new environment was created, however it was not and I can't check it out.

**Comment by nikhname** [comment]
Hey @amuresia, answering ```No``` will copy over the existing resources as well as create a new environment with the name you provide (which you can optionally use different credentials with). We will work on making this flow and documentation clearer.

**Comment by nikhname** [comment]
Mentioned in the docs here - https://docs.amplify.aws/cli/teams/overview#setting-up-master-and-dev-environments
