### ISSUE TITLE
TooManyBuckets: You have attempted to create more buckets than allowed

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4444]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Creating new environment throws error saying this:

```
CREATE_FAILED      S3Bucket AWS::S3::Bucket Wed Jun 03 2020 10:19:42 GMT+0800 (Philippine Standard Time) You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: -----; S3 Extended Request ID: -----
CREATE_IN_PROGRESS S3Bucket AWS::S3::Bucket Wed Jun 03 2020 10:19:41 GMT+0800 (Philippine Standard Time)
```

**Amplify CLI Version**

4.18.0

**To Reproduce**

Just create a new environment then do amplify publish.

**Expected behavior**

Should not happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.0.0

**Additional context**

I encountered this earlier when I created another environment, on the second try it worked, but on this one it has been 3rd try but still on shows error.

**Comment by ammarkarachi** [comment]
@aprilmintacpineda Can you check on the console how many buckets are in your account? There is a soft limit of 100 buckets

**Comment by aprilmintacpineda** [comment]
Oooh, I didn't know about the bucket limit. Yes, we have 100 buckets.

**Comment by aprilmintacpineda** [comment]
I ran around to check as many buckets as I could, looks like amplify leaves behind some buckets when you delete an environment. You can tell if the bucket is being used or not by looking at the contents and checking when the last update was, for me, some buckets were updated months ago.

**Comment by ammarkarachi** [comment]
I believe this has been fixed in an earlier version. Currently when removing an environment also removes its deployment bucket

**Comment by aprilmintacpineda** [comment]
I'm using version 4.18

**Comment by nikhname** [comment]
@aprilmintacpineda could you please try this with version 4.21.1?

**Comment by aprilmintacpineda** [comment]
What is the expected output when using version 4.21?

**Comment by nikhname** [comment]
With 4.21.1 if environments are removed in other projects the buckets should also be deleted allowing you to be below the hard limit of 100 buckets. If those projects were already deleted you will need to manually delete their buckets in the console or through [aws-cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html)
