### ISSUE TITLE
Support rate limiting either via an @auth argument or an @limit directive

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-cli#4451]
**Is your feature request related to a problem? Please describe.**
It's common that applications need to rate limit actions like voting, creating posts, ... . As far as I know, there is no quick and easy way to achieve this with Amplify CLI.

**Describe the solution you'd like**
It would be great if we can do something like: 
```javascript

 @limit(
    rules: [
      { limit: 'user', operation: 'create', count: 150, period: 'hour' },
    ])
```
to limit the user to 150 create operation per an hour. 

**Describe alternatives you've considered**
To achieve this today (AFAIK), you have to customize the resolver.

**Comment by nikhname** [comment]
Hi @mdegrees, you could also achieve this by writing a custom transformer for @limit, documented here: https://docs.amplify.aws/cli/usage/plugin#custom-graphql-transformers.
We will discuss adding this as a CLI feature

**Comment by mdegrees** [comment]
@nikhname thank you for pointing me out to the customer transformers, will give it a detailed look

**Comment by zeroedin** [comment]
@nikhname im interested in this issue and the the link you posted above on Jun 3rd but it appears to be broken. I receive a 404.  Is there another link that you could share on this topic?

**Comment by zeroedin** [comment]
@mdegrees did you figure anything out with custom resolvers?  I would also like to implement a rate limit on my models.  Anything you can share?
