### ISSUE TITLE
[Question] Why is Java Development Kit required to run `amplify mock api`?

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4456]
**Which Category is your question related to?**
amplify mock

**Amplify CLI Version** 

4.21.0

**What AWS Services are you utilizing?**
n/a

**Provide additional details e.g. code snippets**

![image](https://user-images.githubusercontent.com/6764957/83684163-26965100-a619-11ea-8779-080a7a6fa8f3.png)

why is this required? just trying to understand. Oracle has an extremely user hostile download process for the JDK that involves taking a ton of personal information. i dont believe you are best served with them as a hard dependency. the fact that the JDK is not mentioned anywhere in this repo or docs also makes me wonder if this dependency is accidental. i'd love to know!

**Comment by sw-yx** [comment]
the installer doesnt even run on macos
![image](https://user-images.githubusercontent.com/6764957/83684692-0a46e400-a61a-11ea-9215-bb54444429f9.png)

**Comment by nikhname** [comment]
Hi @sw-yx, ```amplify mock api``` uses a local dynamodb emulator to simulate your tables which requires JRE. It is mentioned in the docs here https://docs.amplify.aws/cli/usage/mock that Java is required for local mocking

**Comment by nikhname** [comment]
Installing the entire JDK is not necessary if that is blocking, you could try installing just the runtime environment instead https://www.oracle.com/java/technologies/javase-jre8-downloads.html

**Comment by sw-yx** [comment]
ah ok. yes that's what i downloaded. thanks Nikhil!

**Comment by nikhname** [comment]
Thanks for the suggestion, we will discuss adding the link in the CLI or docs
