### ISSUE TITLE
Graphql api working for auth disabled users

### ISSUE THREAD

**Issue by yepes** [aws-amplify/amplify-cli#4472]
**Which Category is your question related to?**

Authentication

**Amplify CLI Version** 

4.21.1

**What AWS Services are you utilizing?**

Api, Auth

**Provide additional details e.g. code snippets**

Graphql Api and Auth added on a brand new project.

I go to Amplify console -> myapp -> api -> GraphQL API and click on View in AppSync. On the run query part, I run a sample query like this:
```
{
  listTodos {
    items {
    	name
  	}
  }
}
```
And the response is a UnauthorizedException. This is expected and working right.

Then, if I log in with a cognito user, the response is some example TODOS. This is also fine.

If I go to Cognito and disable the user, I can still run the query. I was a expecting an unauthorized or something else than actually being able to query for my data (as the **user is disabled**).

**Comment by nikhname** [comment]
@yepes what steps did you take to disable auth for that user?

**Comment by SwaySway** [comment]
Closing this issue due to lack of response.
