### ISSUE TITLE
[Feedback]mock api command failed

### ISSUE THREAD

**Issue by sdbeng** [aws-amplify/amplify-cli#4474]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

Hi there,
I'm trying to run mockup tests to test my amplify api.

Following instructions:
After I run: `amplify mock api` I get this message,
Failed to start API Mock endpoint Error: Command failed with exit code 1: java -version
No Java runtime present, requesting install.

So I try fixing this by clicking on the more info button, assuming it wants java which it doesn't make sense to me. After that I being asked to install the flash software on my mac. Not sure why.
mac OS: Catalina

**Comment by mauerbac** [comment]
Actually, looks like there is a fix here -> https://github.com/aws-amplify/docs/issues/1711. I will close this issue in favor of keeping that issue open to fix the docs.
