### ISSUE TITLE
Add User To Group Cognito Trigger gets incorrect handler assigned in Lambda Function.

### ISSUE THREAD

**Issue by Huetarded** [aws-amplify/amplify-cli#4475]
@secretshardul Yes, I am using this and it works great at adding users to whichever group you'd like after they are verified.

However, I would add that there is a bit of a bug present when using this feature. The file that is created by Amplify is called "add-to-group.js", but the handler for that function that gets assigned in AWS is "index.handler". So, upon first push, I have found that I need to log into the console and fix the handler reference (change to "add-to-group.handler") before it will function correctly.

It would be great if Amplify would either name the file "index.js" or assign the correct handler to it when pushing the resources to AWS.

![amplify-add-to-group-bug](https://user-images.githubusercontent.com/8525740/83691652-645a9180-a5a7-11ea-8fa1-4781f17335cc.png)

_Originally posted by @Huetarded in https://github.com/aws-amplify/amplify-js/issues/1213#issuecomment-638474782_

**Comment by edwardfoyle** [comment]
@Huetarded thanks for reporting this, it's definitely a bug. While we work on a fix, I would recommend you either rename the file locally or change the handler name in the function CloudFormation template rather than making the change in the console. That way everything will stay in sync across multiple pushes.

**Comment by akshbhu** [comment]
Hi @Huetarded 

Closing this as it is already fixed in previous versions. You can try with our latest version.

If the problem still occurs , comment on it and ill reopen the issue
