### ISSUE TITLE
amplify configure does nothing

### ISSUE THREAD

**Issue by screendriver** [aws-amplify/amplify-cli#4485]
**Describe the bug**

When I call `amplify configure` it does nothing. Instead I just see

```sh
❯ npx amplify configure
? Select the backend providers. (Press <space> to select, <a> to toggle all, <i> to invert selection)
```

but nothing more

**Amplify CLI Version**

4.21.1

**To Reproduce**

I just entered `amplify configure` but nothing more.

**Expected behavior**

Should open the AWS console and let me create an IAM user.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Node Version: 14.2.0

**Comment by screendriver** [comment]
I found out that here is already an issue about this: https://github.com/aws-amplify/amplify-cli/issues/839

Installing the amplify CLI globally is unfortunately a show stopper for me.

**Comment by sw-yx** [comment]
maybe reopen and change the issue to ask for the CLI to not rely on global install?

any extra info on why it is a show stopper would be helpful, to motivate the discussion

**Comment by screendriver** [comment]
@sw-yx done: https://github.com/aws-amplify/amplify-cli/issues/4491
