### ISSUE TITLE
Generating API with amplify codegen produces an empty (just imports) API.service.ts file.

### ISSUE THREAD

**Issue by fishermr** [aws-amplify/amplify-cli#4486]
Generated previously from a /backend schema and the API.service.ts was generated correctly.

I updated my schema in /backend/api/<my api>/schema.graphql.  ran the following commands:
amplify api gql-compile
amplify codegen
Did not work.  Then did amplify push.  
Still did not work. Then did amplify configure codegen followed by api gql-compile and codegen
Still did not work.

Lost as to what to try next without doing an amplify init.

Versions:
Macintosh 10.14.6
amplify cli 4.18.0
angular/cdk  8.2.3
angular/core 8.2.14
angular/compiler 8.2.14
<img width="561" alt="Screen Shot 2020-06-07 at 11 49 18 AM" src="https://user-images.githubusercontent.com/1569806/83973525-0256a080-a8b5-11ea-94db-9cfdc7a48b35.png">

node 12.15.0

Steps to reproduce:
1. Update schema under local dir /backend
2. amplify push
3. Verified in Appsync schema is correct
4. amplify api gql-compile
5. amplify codegen

Expectations:
The API.service.ts file was generated with all proper source for managing the data store through this API.

**Comment by richardissuperman** [comment]
does your schema.graphql file contains directives models?

**Comment by fishermr** [comment]
The following is one simple definition I have and the others follow this layout:
type Device @model{
  id: ID!
  cuuid: String
  puuid: String
  code: String
}

**Comment by davidmpaz** [comment]
Hello,

i just start learning amplify and its tooling. I have hit this same issue. 
Is there any feedback? 

Greetings,
David

**Comment by kaustavghosh06** [comment]
Apologize for the lack of response on this thread. We'll be looking into this issue.
