### ISSUE TITLE
Update change secondary index with composite sort key on DDB datasource

### ISSUE THREAD

**Issue by yuntaoL** [aws-amplify/amplify-cli#4489]
**Describe the bug**
I use update mutation on a DDB data source which has a secondary global index with a composite sort key, I didn't specify any field from the composite key, but the composited key was updated to the value of the field name.

**Amplify CLI Version**
4.21.1

**To Reproduce**
```gql
type MyQuery
  @model
  @key(
    name: "ByOwner"
    fields: ["owner", "queryType", "createdAt"]
    queryField: "listMyQueryByOwner"
  ){
  id: ID!
  queryType: String!
  owner: String!
  status: STATUS!
  createdAt: String
  ...
}
```
When I use the following mutation to update status field
```gql
mutation UpdateMyQueryStatus(
  $input: UpdateMyQueryInput!
  $condition: ModelMyQueryConditionInput
) {
  updateMyQuery(input: $input, condition: $condition) {
    id
    queryType
    owner
    status
    createdAt
  }
}

{
     input: {
        id: "id_value",
        status: "COMPLETED"
      }
}
```

The composite sort key `queryType#createdAt` was updated to `"${ctx.args.input.queryType}#${ctx.args.input.createdAt}"`

**Expected behavior**
The value of the composite soft key should not be changed.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.3.0

**Additional context**
The generated code
```
$util.qr($ctx.args.input.put("queryType#createdAt","${ctx.args.input.queryType}#${ctx.args.input.createdAt}"))
```
set sort key value without any condition. It should check if there is any value change in input.

**Comment by akshbhu** [comment]
Closing in favour of #3664
