### ISSUE TITLE
Limit param for API graphql list queries doesn't work as expected

### ISSUE THREAD

**Issue by brianhilst** [aws-amplify/amplify-cli#449]
**Describe the bug**
The limit parameter for the API graphql list queries appears to limit the number of records searched rather than the number of records returned.  I'm not sure if this is by design, but if it is, then how do you control the page size when paginating results?

**To Reproduce**
```
const filter: ModelUserFilterInput = { owner: { eq: username}}
const promise = API.graphql(graphqlOperation(gqlToString(queries.ListUsers), {"filter": filter, limit: 1}))
```
**Expected behavior**
Return the one matching record where owner===username.  Instead, zero items are returned along with a nextToken.  Setting the limit to 1000 (or anything above the number of records) causes it to return the 1 matching record.

**Additional context**
This may just be due to a lack of documentation on using the limit and nextToken params.

**Comment by yuth** [comment]
This is a know issue which was is discussed in 
https://github.com/aws-amplify/amplify-cli/issues/352#issuecomment-433097656

**Comment by mikeparisstuff** [comment]
The behavior is a result of underlying DynamoDB semantics (which is DynamoDB filters are applied after the underlying partition performs the scan from disk). You can get around this by providing the **username** as the **id** when you create a user so you can get a single user by username. As @yuth mentioned there is an example in #352 that talks about this.

**Comment by kaustavghosh06** [comment]
Closing this issue. Please feel free to reopen is the issue still persists.
