### ISSUE TITLE
`amplify storage add/update` for a **NoSQL Database** doesn't create attributes other than the partition and sort keys. 

### ISSUE THREAD

**Issue by tsteelematc** [aws-amplify/amplify-cli#4498]
**Describe the bug**
When running `amplify storage add/update` and choosing NoSQL Database, I can't seem to get any attributes to show up in the generate cloud formation template other than attributes specified as either the partition or sort key.

**Amplify CLI Version**
4.21.1

**To Reproduce**
amplify storage add
NoSQL
Attribute 1, string
Attribute 2, string
Partition key, Yes, attribute 1
Sort key, No
...

Nothing is generated for Attribute 2 : - (

If I make attribute 2 the sort key, it will get generated. But I can't get any other attributes to be generated and/or pushed to AWS.

**Expected behavior**
All attributes be properly generated and able to be pushed to AWS.

**Screenshots**
![image](https://user-images.githubusercontent.com/21085175/84085991-6f009680-a9ac-11ea-9b7b-1017f632844d.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 13.01

**Additional context**
None

**Comment by tsteelematc** [comment]
As I poked around the code, I found that this appears to be filtering the attributes down to just the 'used' ones. May naive, first-blush, look into what that means is that 'used' means 'used as partition, sort, gis, blah, blah, blah...

![image](https://user-images.githubusercontent.com/21085175/84459752-d5481c00-ac2d-11ea-91a2-34df9044b5a3.png)

Not sure this is helpful, but thought I'd share. Thanks.

**Comment by akshbhu** [comment]
Hi @tsteelematc 

```AttibuteDefinitions ``` can only consists of key schema for the table and indexes. Check here for the documentation:https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-attributedef.html.

DynamoDB only requires partition key and sort key to insert elements in the table. Rest non primary attributes you can add without mentioning in CFN template. Check here for examples :  https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.WriteData.html.

For now I am closing the issue. If you face anymore problems comment on this and Ill reopen this issue.
