### ISSUE TITLE
How to change data type for GraphQL once created using amplify CLI

### ISSUE THREAD

**Issue by tabrza** [aws-amplify/amplify-cli#4500]
**Which Category is your question related to?**
GraphQL and DynamoDB setup using amplify CLI

**Amplify CLI Version** 
4.18.0

**Provide additional details e.g. code snippets**
I followed the instructions on this [page](https://aws.amazon.com/blogs/mobile/amplify-framework-adds-support-for-aws-lambda-functions-and-amazon-dynamodb-custom-indexes-in-graphql-schemas/) and all worked as expected. However, for ID in order to ensure it remains unique, I would like to use a string instead of int (which i defined at setup). 

schema file looks like this
```
<project-root>/amplify/backend/api/<api-name>/schema.graphql 

type Customer @model {
  id: ID!
  name: String!
  createdAt: String
}

type Mutation {
  addEntry(id: Int, email: String, createdAt: String): String @function(name: "addEntry-${env}")
}
```
As you can see, as ID is defined as ID over here, I can't directly change to String from what I can see. In the mutation however I could change Int to String. However, the auto generated mutations.js file still expects an Int data type. Pls advise!

**Comment by brene** [comment]
@tabrza - did you rerun `amplify push` after your changes has been made?

I just tried your schema and made the edit from `addEntry(id: Int ....)` to `addEntry(id: String ...)`.

After running `amplify push` again to regenerate the code, the mutations.js file updated accordingly.

**Comment by tabrza** [comment]
@brene - thanks for your response
as ID had been predefined in the CLI build to INT, i was getting an error the value was invalid (graphQL to dynamoDB using lambda). 
What I ended up doing is setting id to string, running amplify push and then changing it back to ID
Step 1)
```
type Customer @model {
  id: String!
  name: String!
  createdAt: String
}

type Mutation {
  addEntry(id: String, email: String, createdAt: String): String @function(name: "addEntry-${env}")
}
```

Step 2)
```
type Customer @model {
  id: ID!
  name: String!
  createdAt: String
}

type Mutation {
  addEntry(id: ID, email: String, createdAt: String): String @function(name: "addEntry-${env}")
}
```

the above worked like a charm
