### ISSUE TITLE
amplify cli v4.21.1 introduces graphql mutation dynamo error

### ISSUE THREAD

**Issue by trevorah** [aws-amplify/amplify-cli#4502]
**Describe the bug**
`amplify push` with v4.21.1 results in an api stack that where sending `createThing` graphql mutations results in consistant failure with the following error:

```json
{
  "data": {
    "createFoo": null
  },
  "errors": [
    {
      "path": [
        "createFoo"
      ],
      "data": null,
      "errorType": "DynamoDB:AmazonDynamoDBException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "One or more parameter values were invalid: Type mismatch for key id expected: S actual: NULL (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: REDACTED)"
    }
  ]
}
```

The same action with v4.21.0 (and earlier) results in no error.

**Amplify CLI Version**
@aws-amplify/cli@4.21.1 (@aws-amplify/cli@4.21.0 is fine)

**To Reproduce**
`amplify push` and then send a `createFoo` mutation to the api.

Schema:

```graphql
type Foo
  @model
  @key(
    name: "byBar"
    fields: ["barID"]
    queryField: "fooByBar"
  ) {
  barID: ID!
  Bar: Bar! @connection(fields: ["barID"])
  something: [Something]
    @connection(keyName: "byBar", fields: ["barID"])
}
```

Autogenerated mutation that creates error when used:

```graphql

mutation CreateFoo(
  $input: CreateFooInput!
  $condition: ModelFooConditionInput
) {
  createFoo(input: $input, condition: $condition) {
    barID
    bar {
      (stuff)
    }
  }
}
```
With the input type being:

```graphql
input CreateFooInput {
  barID: ID!
}
```

**Expected behavior**
I expect the mutation to create a new Foo entry in dynamo and no error to be thrown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.16.2

**Comment by emijay** [comment]
May I ask if this issue has been fixed? It was working fine until recently where I am also encountering an error each time I try to create a new item.
