### ISSUE TITLE
How to use Multiple API with single cognito

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-cli#4504]
**Which Category is your question related to?**

Appsync API,  Cognito

**Amplify CLI Version** 

4.17.1

How to use Multiple API with single cognito(userpool).

**Comment by SwaySway** [comment]
Hello @anarerdene 
Currently using the same Cognito Userpool in different APIs is not supported. We have an RFC open for this.
RFC: https://github.com/aws-amplify/amplify-cli/issues/3977

Please follow this thread for updates.
