### ISSUE TITLE
[bug] Error: ENOENT: no such file or directory, open (...)/amplify/backend/backend-config.json

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4505]
**Describe the bug**

running `amplify pull` on a freshly cloned repo causes this error:

```bash
$ amplify pull    

Pre-pull status:

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | reactdraw     | Create    | awscloudformation |

Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error pulling the backend environment dev.
ENOENT: no such file or directory, open '/Users/wanshawn/Amplify/aws-amplify-appsync-graphql-real-time-canvas/amplify/backend/backend-config.json'
Error: ENOENT: no such file or directory, open '/Users/wanshawn/Amplify/aws-amplify-appsync-graphql-real-time-canvas/amplify/backend/backend-config.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at initEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/index.js:59:33)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.js:43:52
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Amplify CLI Version**
4.21.1
 
**To Reproduce**

1. fork https://github.com/aws-samples/aws-amplify-appsync-graphql-real-time-canvas and deploy to amplify via https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2&code=08c4fe1c44851eb67099#/create/template so it deploys to amplify FIRST. 
2. clone the repo and then `amplify pull`.

**Expected behavior**

No error, or nice message telling me what to do next, instead of hard crash

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] macosx
 - Node Version. You can use `node -v` to check the node version on your system 12.18

**Comment by sw-yx** [comment]
sorry i couldn't repro this - i think it may have to do with wrongly set region in my console vs my cli - but we did have a good discussion on Chime about how we should do error handling for missing files in general. there are a lot of paths the user can take to accidentally have missing files, and amplify can't account for all of those at source. we may need to have a better missing file handling strategy. 

for example, in trying to repro, i ran into another (different but similar) one:

![image](https://user-images.githubusercontent.com/6764957/84534590-cd1ada00-ad1c-11ea-9a64-68f177d9806a.png)

**Comment by Guneetgstar** [comment]
@sw-yx why did you closed the issue? It's still present. When I call `amplify push api` and enter `y` as the api is ready for a push, it fails with the same error. I neither can generate `GraphQl` code.

**Comment by sw-yx** [comment]
it was my report, i closed it as i could no longer repro :) please feel free to open your own issue with exact steps. having precise steps is important, as this error can have many different causes.
