### ISSUE TITLE
[Codegen] Annotate Android models when @auth directive is defined

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-cli#4509]
**Is your feature request related to a problem? Please describe.**

Currently, the [GraphQL transformer @auth directive](https://docs.amplify.aws/cli/graphql-transformer/directives#auth) is not supported on Android.  Codegen simply ignores it if present on the `schema.graphql`.

**Describe the solution you'd like**

Codegen should be updated to add an `@AuthRule` annotation for each @auth directive rule in the schema.  This annotation was recently added to the [amplify-android library](https://github.com/aws-amplify/amplify-android/).  See a sample schema and expected codegen output in the description of https://github.com/aws-amplify/amplify-android/pull/559

**Comment by nikhname** [comment]
Closed by https://github.com/aws-amplify/amplify-cli/pull/4717
