### ISSUE TITLE
How to filter simple nested object

### ISSUE THREAD

**Issue by Jmales** [aws-amplify/amplify-cli#4510]
**Which Category is your question related to?**
Filtering nested GraphQL

**Amplify CLI Version** 
4.21.1

**What AWS Services are you utilizing?**
GraqhQL

**Provide additional details e.g. code snippets**
I've been at this for hours now and wasn't able to figure it out.

I have a table in my GraphQL API:
```
type ad @model {
   id: ID!
   price: Int!
   description: String
   car: Car!
}

type Car{ //this type is used in many tables. This is just a type declared for reusable purposes, I don't want a table with this data
   brand: String!
   quantity: Int!
}
```

**listAds** is automatically generated by amplify and I can filter by description or price but NOT by car, or car.brand. I tried a lot of combinations and can't get it to work.

How can I achieve such a simple thing, without having to make a new resolver, which will be overwritten every time I do "amplify push"?

**Comment by viczam** [comment]
Please let us know how did it go. It's something I plan to use myself and I somehow expected to be available already.

**Comment by SwaySway** [comment]
Closing as a duplicate of #2311

In this thread there is a potential solution on how to address this:
https://github.com/aws-amplify/amplify-cli/issues/2311#issuecomment-532859188
