### ISSUE TITLE
Sign in and sign out URLs are being sorted

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#4517]
When a change is made to `oAuthMetadata` in `amplify/backend/auth/[name]/parameters.json`, specifically to the `CallbackURLs` and `LogoutURLs` (per the below) and an `amplify push` is executed, the `Sign in and sign out URLs` in the Cognito user pool UI are re-ordered.

```console
"oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"https://localhost:3000/auth-callback/\", \"exp://localhost:19000/--/\"],\"LogoutURLs\":[\"https://localhost:3000/\", \"exp://localhost:19000/--/\"]}"
```
It appears that someone/thing is doing a sort on the array, to make it alphabetically ascending.

This would not be a problem, except for the issue I've raised [here](https://github.com/aws-amplify/amplify-js/issues/6041), where the order of the entries is affecting the social login process in an admittedly strange case.

This may not be an Amplify CLI problem, as the array gets sorted if I changed the entries directly in the Cognito user pool UI, so if you want to pass this issue there, I would understand.

**Amplify CLI Version**
4.19.0

**To Reproduce**
1.  Change `oAuthMetadata` so that there is an array of non-alphabetically ascending entries.
2.  Do an `amplify push`
3.  Look in the user pool to see that the entries are in a different order than originally entered.

**Expected behavior**
I would expect that the entries in the Cognito user pool UI match how they are coded in the parameters.

**Comment by ammarkarachi** [comment]
Hi @kimfucious I see it's sorted on the console but it looks like the sorting doesn't occur on the CLI side. I have contacted the Cognito team requesting their investigation into this issue. You can also find some additional help [here](https://forums.aws.amazon.com/forum.jspa?forumID=173)

**Comment by kimfucious** [comment]
Hi @ammarkarachi , thanks for the follow up.

The issue regarding sorting does not affect the client side, as I can control `aws-exports.js` with manual configuration.

It does affect users hitting the User Pool (in the console), however, which is the problem for me at this point.

If there's a ticket/issue I can track on the other side of the fence, kindly let me know so that I may observe and potentially provide more info.

**Comment by kaustavghosh06** [comment]
@kimfucious Is this still an issue on your side? I haven't heard about any issues tied to the order of the redirect URI's on the cognito service side. Also, I see the corresponding issue on the Amplify JS repo closed out - https://github.com/aws-amplify/amplify-js/issues/6041  Please let us know if you're still stuck on this.
