### ISSUE TITLE
Amplify Tools breaks Xcode project

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#4518]
**Describe the bug**
`npx amplify-app` breaks my Xcode project. 
Before running the tool, my project has a `Resources` folder containing references to `jpg` files.
After running the tool, the `Resources` folder is removed and a new `Recovered References` folder appears in my project.

Recovered Folder is an Xcode created folder where it stores lost file references. 

Files on the hard drive are unaffected.

**Amplify CLI Version**
```
amplify --version
4.21.2
```

**To Reproduce**
Follow the instructions in the Amplify iOS Workshop : 

1. Download the sample app : https://amplify-ios-workshop-new.go-aws.com/20_getting_started/20_bootstrapping_the_app.html

Observe a `Landmarks/Resources` folder exists in the project.

2. Configure Amplify in the project (these instructions are copy / paste from Amplify doc) 
https://amplify-ios-workshop-new.go-aws.com/20_getting_started/30_configuring_amplify.html

After building the project in the last step, the `Landmarks/Resources` is removed from the project and a `Recovered References` folder appears in the project.

**Expected behavior**
Amplify Tools should not alter the structure of the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/401798/84280578-c8490100-ab37-11ea-82eb-3f499db86e31.png)

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.5
 - Node Version. You can use `node -v` to check the node version on your system
```
node --version
v14.4.0
```

**Comment by nikhname** [comment]
Related issue - https://github.com/apache/cordova-node-xcode/issues/113
PR - https://github.com/apache/cordova-node-xcode/pull/112
