### ISSUE TITLE
'amplify delete' deletes all my project, including source files

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#4519]
**Describe the bug**
When typing `amplify delete`, the CLI not only deletes my amplify configuration, but it cleans up the entire project, deleting all my source files as well.

**Amplify CLI Version**
amplify --version
4.21.2

**To Reproduce**
Follow the steps described in the Amplify iOS workshop 

1. Download a Sample Project : https://amplify-ios-workshop-new.go-aws.com/20_getting_started/20_bootstrapping_the_app.html

2. Configure Amplify Tools : https://amplify-ios-workshop-new.go-aws.com/20_getting_started/30_configuring_amplify.html

3. in the project directory, type `amplify delete`

**Expected behavior**
`amplify delete` should delete the amplify configuration and backend infrastructure but should not delete my project source files !

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.5
 - Node Version. You can use `node -v` to check the node version on your system
 node --version
v14.4.0

**Additional context**
```bash
➜  Landmarks amplify delete
? Are you sure you want to continue? This CANNOT be undone. (This would delete all the environments of the project from the cloud and wipe out all the local fil
es created by Amplify CLI) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:amplify
✔ Project deleted in the cloud
ENOTEMPTY: directory not empty, rmdir '/Users/stormacq/Downloads/amplify-ios-workshop/Complete/Landmarks'
Error: ENOTEMPTY: directory not empty, rmdir '/Users/stormacq/Downloads/amplify-ios-workshop/Complete/Landmarks'
    at Object.rmdirSync (fs.js:865:3)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:308:25)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at Object.rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:39:10
    at Array.forEach (<anonymous>)
    at Object.deleteAmplifyConfig [as deleteConfig] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:32:27)
    at AmplifyToolkit.deleteProject [as _deleteProject] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/delete-project.js:36:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➜  Landmarks ls -al
total 16
drwxr-xr-x@ 3 stormacq  1896053708    96 Jun 10 16:53 .
drwxr-xr-x  8 stormacq  1896053708   256 Jun 10 16:35 ..
-rw-r--r--@ 1 stormacq  1896053708  6148 Jun 10 16:53 .DS_Store
```

**Comment by ammarkarachi** [comment]
@sebsto what version of the CLI was used when the project was first built?

**Comment by nikhname** [comment]
@sebsto did you use the ```amplify-tools``` script or ```npx amplify-app``` when building your project?

**Comment by nikhname** [comment]
@sebsto also, is there a .graphql-config.yml present in the root of your project before running the delete command?

**Comment by sebsto** [comment]
Sorry for the delay replying to you - timezone :-)  I chat with @nikhame this morning on Chime and learned you manage to reproduce.
