### ISSUE TITLE
UnauthorizedException for custom field annotated with @aws_iam @aws_cognito_user_pools

### ISSUE THREAD

**Issue by naedx** [aws-amplify/amplify-cli#4520]
**Describe the bug**
Amplify-cli does not generate IAM auth policies for custom query field annotated with `@aws_iam @aws_cognito_user_pools`. This results in UnauthorizedException response from a web client.

**Amplify CLI Version** 
4.21.2

**Which Category is your question related to?**
AppSync, Cognito, IAM, DynamoDB

**To Reproduce**
1. Set up multi auth on a project using amplify cli, allowing for both authorized and unauthorized users via userpools and AWS_IAM. Userpools is set as default.
2. Create schema similar to the following having a custom query resolver field `customGetTask`:

```graphql
# schema.json
type Task 
  @model(queries: null, mutations: null, subscriptions: null) 
  @key(fields: ["id"]) 
  @auth(rules: [
    {allow: owner, ownerField: "creator", operations: [create, read]}, 
    {allow: groups, groups: ["admins"], operations: [create, update, delete, read]},
    {allow: private, operations: [read]},
    {allow: public, provider: iam, operations: [read]}
  ]) 
{
  id: ID!
  creator: String
  status: String
  title: String!
  details: AWSJSON
}

type Note 
  @model(mutations: null, subscriptions: null) 
  @key(fields: ["id"]) 
  @auth(rules: [
    {allow: owner, ownerField: "creator", operations: [create, read]}, 
    {allow: groups, groups: ["admins"], operations: [create, update, delete, read]},
    {allow: private, operations: [read]},
    {allow: public, provider: iam, operations: [read]}
  ]) 
{
  id: ID!
  creator: String
  status: String
  note: String
}

type Query {
      customGetTask(taskId: String!, detailsFilter: String): Task @aws_iam @aws_cognito_user_pools
}

```

3. On running `amplify api gql-compile` or `amplify push` the following _cloudformation-template.json_ is generated:

```javascript
// cloudformation-template.json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "An auto-generated nested stack.",
    "Metadata": {},
    "Parameters": {
        //...
    },
    "Resources": {
        "AuthRolePolicy01": {
            //...            
        },
        "UnauthRolePolicy01": {
            "Type": "AWS::IAM::ManagedPolicy",
            "Properties": {
                "Roles": [
                    {
                        "Ref": "unauthRoleName"
                    }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "appsync:GraphQL"
                            ],
                            "Resource": [
                                {
                                    "Fn::Sub": [
                                        "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${apiId}/types/${typeName}/*",
                                        {
                                            "apiId": {
                                                "Fn::GetAtt": [
                                                    "GraphQLAPI",
                                                    "ApiId"
                                                ]
                                            },
                                            "typeName": "Note"
                                        },
                                        
                                        //...
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },

        //...
            
}
```

**Issue**: Calls to the graphql field from a client result in "UnauthorizedException" even though accessing the resolver is successful from the _AppSync > Queries_ console. I observe that no policy is added to the `AuthRolePolicy01` or `UnauthRolePolicy01` in the _cloudformation-template.json_ for my custom resolver field `customGetTask`. 

**Expected behavior**
1. The query on the custom field `customGetTask` should succeed in the AppSync console and from a web client.
2. The generated _cloudformation-template.json_ should reflect authorization policies for the custom field `customGetTask` on the IAM role.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: v12.16.3

**Additional context**
Specifying ``` graphql @model(queries: {get: "customGetTask"} ``` creates the expected policies but removes the ability to configure the parameters of the custom field.

**Comment by SwaySway** [comment]
Hello @naedx 
Using AppSync's authorization directives will indicate to AppSync which authorization method to use. This directive will not create the necessary policies to access the field. To add the policies you would have to add them into the `CustomResources.json`.

Another option would be using `@auth` on a query operation. As it would do the following:
- Add the necessary appsync directives such as `@aws_iam` and `@aws_cognito_user_pools`
- Add the policies into the unauth and auth roles based on the rule given in the schema
- Create resolver code to authorize access via cognito.

An example of how this could be implemented would be the following
```gql
type Query {
      customGetTask(taskId: String!, detailsFilter: String): Task
        @auth(rules: [{ allow: private, provider: userPools }, {allow: private}])
}
#  CustomResource edits would still be needed for the to link the VTL code to the operation
```
