### ISSUE TITLE
Appsync CloudFormation Template Limit Exceeded

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#4522]
**Which Category is your question related to?**
AppSync

**Amplify CLI Version** 
v4.21.1

**What AWS Services are you utilizing?**
Appsync, Cognito, S3, DynamoDB, Lambdas

**Provide additional details e.g. code snippets**
My Schema has 25 models, and will probably Continue to grow as our functionality increases. I feel there's a general issue with the way Amplify approaches Partition and Sort Keys, in that it is not really using DynamoDB to its fullest, which results in us needing so many different tables. We're running into cloudformation template restrictions and are needing to go in and add ex: (subscription: null, queries: null) etc. to all of our models to try to strip down functionality as needed.

**Comment by julien-tamade** [comment]
Thanks for the response @SwaySway. Will using minify prevent my team from using amplify push?

**Comment by SwaySway** [comment]
No as it's a flag used to remove whitespace from the generated graphql json cfn templates.
