### ISSUE TITLE
DS_Store files corrupting isBackendDirModifiedSinceLastPush hash results for `amplify status`

### ISSUE THREAD

**Issue by kevcam4891** [aws-amplify/amplify-cli#4525]
**Describe the bug**
If .DS_Store files get generated on a mac in one of your lambdas, for example, when you run `amplify status`, unless your cloud directory has that file, too, will show status as Operation = Update

**Amplify CLI Version**
4.21.1

**To Reproduce**
Open a Finder window inside of any of your function/*/src directories. .DS_Store file should be created by your mac. Run `amplify status`.

```
| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Function | MyFunctionName        | Update    | awscloudformation |
```

**Expected behavior**
I expect this file to not be considered when generating the directory hash (and potentially even other system-generated files, I just know this to be an issue with mac.) Or potentially honor a .gitignore list of files when hashing which would allow this file to be added. There are potentially a few ways to correct this.

The method that generates a directory hash is at:
`./packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 14.0.0

**Additional context**

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.
