### ISSUE TITLE
aws cli is a required dependency

### ISSUE THREAD

**Issue by jameslporter** [aws-amplify/amplify-cli#453]
**Describe the bug**
amplify cli fails to create resources if you do not have aws cli installed and configured properly ahead of time.

I'm fairly confident aws cli is an implied but never stated dependency. 

**To Reproduce**
Steps to reproduce the behavior on a new machine.
1. install amplify cli as directed
2. run amplify init answering questions and providing credentials when asked
3. add features
4. push and see it fail like below

UPDATE_COMPLETE                     station-20181114140356 AWS::CloudFormation::Stack Wed Nov 14 2018 14:11:36 GMT-0600 (Central Standard Time) 
✖ An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, open '/Users/jamesporter/.aws/credentials'

**Expected behavior**
Installation instructions should make it clear aws cli is a dependency and aws creds need to be configured. Amplify cli should also check for it.

**Comment by kaustavghosh06** [comment]
@jameslporter . Quick Question. When you ran an `ampify init`, did you choose an existing profile in your system or did you manually enter your access and secret key? 
Also, could you look into the `amplify/.config/aws-info.json` file and let me know the contents of the same?

**Comment by jameslporter** [comment]
It prompted me for access key & secret. Had recently switched machines which is why I had not yet installed aws cli.

aws-info.json contents below:

{
    "awsConfigFilePath": "/Users/jamesporter/.amplify/awscloudformation/xgWsT9E5YP"
}

**Comment by UnleashedMind** [comment]
what features have you added? 
just trying to reproduce the issue.

**Comment by kaustavghosh06** [comment]
@jameslporter  We've pushed a fix for it and its in our publish pipeline.
