### ISSUE TITLE
Amplify auto-generated Lambda fns

### ISSUE THREAD

**Issue by maprokes** [aws-amplify/amplify-cli#4531]
I was asked a question about some autogenerated lambda functions and I couldn't find additional info about Amplify auto-generated lambda functions, so I'm asking here. By checking the logs, these lambdas were executed just once during creation, so I'd like to understand what happens if I delete them, because having unused lambdas doesn't really make sense.

These are the lambda functions that are deployed alongside our other lambdas:

- UpdateRolesWithIDPFunction
- RoleMapFunction
- UserPoolClientLambda

What is the purpose?
Can I safely delete them? Are these lambdas re-created?

**Which Category is your question related to?**
Amplify

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.21.1

**What AWS Services are you utilizing?**
Auth
Appsync
DynamoDB
S3

**Comment by kaustavghosh06** [comment]
@maprokes These functions are necessary when you update or even delete a stack. These are custom resources used in CloudFormation for creating, updating, deleting AWS resources which don't have CloudFormation support yet. You can read more about it out here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html

**Comment by maprokes** [comment]
Thanks @kaustavghosh0
