### ISSUE TITLE
✖ Zipping artifacts failed.

### ISSUE THREAD

**Issue by mluis** [aws-amplify/amplify-cli#4532]
**Describe the bug**
amplify publish builds correctly but fails on zip artifacts.

**Amplify CLI Version**
4.21.3

**To Reproduce**
$ amplify publish

**Expected behavior**
amplify should be enable to zip and perform publish.
the message should be accurate on how and where it failed.

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Node Version: v13.2.0

**Additional context**
Please ask.

**Comment by SwaySway** [comment]
Hello @mluis
What kind of error message is shown?
To better reproduce this are you able to share your project to amplify-cli@amazon.com?

**Comment by mluis** [comment]
The only message shown was "Zipping artifacts failed." and the app quit. Perhaps I should had written a better issue title.

I had to setup everything again. On my end the project is now running although I couldn't understand what was wrong before.

**Comment by jonnyparko** [comment]
check that it is building in the directory you expect

**Comment by mluis** [comment]
@jonnyparko I think the cli should state exactly what's the problem.

**Comment by jonnyparko** [comment]
@mluis Ah gotcha I see that now. My bad!

**Comment by patelatharva** [comment]
In case of React app, your_app/amplify/.config/project-config.json should be something like this:
```
{
    "projectName": "blah",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "react",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm run-script start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```

**Comment by Rolando-Barbella** [comment]
Any update on this one? there is not even an error on the console, what is _Zipping artifacts failed_ supposed to mean?

**Comment by Rolando-Barbella** [comment]
If you are using gatsby, you need to make sure that `"DistributionDir": "public",`

**Comment by Freakrishnal** [comment]
I'm getting ZIPPING ARTIFACTS FAILED when i tried **amplify publish** from amplify CLI. The problem is no error is written. I didn't do any fancy thing. This is my first time and i simply followed tutorial steps in amplify.

**Comment by Rolando-Barbella** [comment]
@Freakrishnal if show your __app/amplify/.config/project-config.json_ file, or even your project, that could help

**Comment by Freakrishnal** [comment]
@Rolando-Barbella  this is my project-config.json. You can find code here https://github.com/Freakrishnal/FirstAmplify.git

{
    "projectName": "TestAmplify1",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist/TestAmplify1",
            "BuildCommand": "npm.cmd run-script build",
            "StartCommand": "ng serve"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}

**Comment by KandarpAjvalia** [comment]
check if the directory that the app will be served from exists. For me, I was using Next and React and Amplify console was looking for directory named "out", but the build command in my package.json was not correct. I changed the package.json's build command and the "out" directory was created and Amplify was able to zip it without any issues/

**Comment by martysweet** [comment]
I also had the not so helpful "Zipping artifacts failed." message after pulling down a project on a new development environment.

As mentioned above, setting the `javascript.config.DistributionDir` to the correct build directory resolved the issue for me.
The file to look at is `amplify/.config/project-config.json`

It looks like the generic error is thrown here https://github.com/aws-amplify/amplify-cli/blob/2c84b71687a0ebcdeb92ebe462c8cf4eab8c9e3c/packages/amplify-console-hosting/hosting/manual/publish.js#L31-L34

https://github.com/aws-amplify/amplify-cli/blob/2c84b71687a0ebcdeb92ebe462c8cf4eab8c9e3c/packages/amplify-console-hosting/hosting/manual/publish.js#L52-L60

Without knowing more about the codebase - Possibly moving the configuration out of this scope and checking the directory exists before triggering the zip is the solution?

- Get config
- Check path exists or throw error "Build Path doesn't exist error"
- Pass buildPath and projectPath to zipArtifacts - the generic response is applicable for other failures

**Comment by ferchop2002** [comment]
My Problem was I put "DistributionDir": "build" instead of "DistributionDir": "dist" and it works

**Comment by Freakrishnal** [comment]
> I also had the not so helpful "Zipping artifacts failed." message after pulling down a project on a new development environment.
> 
> As mentioned above, setting the `javascript.config.DistributionDir` to the correct build directory resolved the issue for me.
> The file to look at is `amplify/.config/project-config.json`
> 
> It looks like the generic error is thrown here
> 
> https://github.com/aws-amplify/amplify-cli/blob/2c84b71687a0ebcdeb92ebe462c8cf4eab8c9e3c/packages/amplify-console-hosting/hosting/manual/publish.js#L31-L34
> 
> https://github.com/aws-amplify/amplify-cli/blob/2c84b71687a0ebcdeb92ebe462c8cf4eab8c9e3c/packages/amplify-console-hosting/hosting/manual/publish.js#L52-L60
> 
> Without knowing more about the codebase - Possibly moving the configuration out of this scope and checking the directory exists before triggering the zip is the solution?
> 
> * Get config
> * Check path exists or throw error "Build Path doesn't exist error"
> * Pass buildPath and projectPath to zipArtifacts - the generic response is applicable for other failures

Woww...This really helped. My issue is fixed. project path is coming wrong in my case.
