### ISSUE TITLE
Email Verification Link with Redirect is using confirmSignUp() instead of verifyUserAttribute() - should use both

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4534]
**Describe the bug**

I have activated customMessage via CLI. 

I use Passwordless login. 
So I have a Lambda **usersPreSignup**

```exports.handler = (event, context, callback) => {
  // Confirm the user
  event.response.autoConfirmUser = true;

  // Set the email as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty("email")) {
    event.response.autoVerifyEmail = true;
  } 
```

This means that the user does not receive a mail the first time he logs in. This is also ok. 
Well, if he changes his e-mail address, he'll get the mail. The mail goes out.
I would like to confirm the new e-mail here with link instead of code. 
So when the user click the link from the customMessage lambda, there will be an endless loader... 
i logged the err and it is becuase the User is already CONFIRMED. So i checked the function and yes: `cognitoidentityserviceprovider.confirmSignUp()` is used. 

But the function should do "email verification" 
https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers 

So i want to check if the user is Confirmed. If yes, check is the Mail verified?
if not do:

`cognitoidentityserviceprovider.verifyUserAttribute()`

This function want params:

```  var params = {
    AccessToken: "" /* required */,
    AttributeName: "email" /* required */,
    Code: code /* required */,
  };
```

But in this lambda i dont have the accessToken. 
I added it hardCoded, and it works. 

So is there an other way to verify the mail per link instead of code? Or can we add the accessToken to this customMessage lambda so i can add it as param to the link? (is this secure?)

**Amplify CLI Version**
4.18.0

**Comment by kaustavghosh06** [comment]
Closing due to lack of further customer response.
