### ISSUE TITLE
Upgraded from an 1.5 year old version to 4.22

### ISSUE THREAD

**Issue by carstenmuellerlemberg** [aws-amplify/amplify-cli#4541]
Hello,

I followed the auto-migration step as descibed here.

https://aws-amplify.github.io/docs/cli/migrate

When I used amplify push I go the message nothing has changed.
What is is expected to change?

I assume I also should change the node version from 8 to 10/12. Isn't that done automatically?

Regards,
Carsten

**Comment by carstenmuellerlemberg** [comment]
Hi,

within the cloud-formation template I see that code:

![image](https://user-images.githubusercontent.com/25705263/84474813-cb550600-ac8b-11ea-98d1-2794d2721251.png)

What is the approach to migrate that one?

Regards,
Carsten

**Comment by SwaySway** [comment]
Hello @carstenmuellerlemberg 

>When I used amplify push I go the message nothing has changed.
What is is expected to change?

Depending on the changes needed to be made based on the migration docs. Where there any changes that needed to be addressed?

> I assume I also should change the node version from 8 to 10/12. Isn't that done automatically?

The Amplify CLI versions 4.10.0 or higher will change the runtime of the functions being used in your project. We also have migration docs on this as well.
Docs: https://docs.amplify.aws/cli/migration/lambda-node-version-update

**Comment by carstenmuellerlemberg** [comment]
Hi,
I tested again and I have seen that node.js version has been changed.
The question for me is how is hosted UI updated etc. or some code sitting in the yaml template file.

**Comment by SwaySway** [comment]
There is an update because the custom resource is backed by a nodejs lambda function. This code in the yaml file you are referring to is what manages the hostedUI resource.
For any issues you should experience through this please comment below. If you have any further questions we recommend joining our discord community [here.](https://discord.gg/TrsguzP)
