### ISSUE TITLE
Never ending "Initializing project in the cloud..." message on "amplify init"

### ISSUE THREAD

**Issue by alexandrefilipiak** [aws-amplify/amplify-cli#4542]
Never ending "Initializing project in the cloud..." message on "amplify init"

**Amplify CLI Version**
4.21.20

**To Reproduce**
I was running "amplify init", and then I had a power shortage, and the internet connexion was cut.
When trying agin, I got a never ending message "Initializing project in the cloud..."
This is not the first project I initialized.
I already initialized several ones with the same profile before. And it was all right.
So I guess this disconnection from the internet triggered the problem.
Also I tried with another brand new projet, tried with other brand new profiles, and still can't make it work.

**Expected behavior**
The "amplify init" command should return and give a success notification.

**Screenshots**
![image](https://user-images.githubusercontent.com/65644177/84490858-c8224000-acb4-11ea-9c0e-3156e440d48d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v10.16.1

**Additional context**

**Comment by alexandrefilipiak** [comment]
After more than half an hour, the cli finally stopped with following error  :
![image](https://user-images.githubusercontent.com/65644177/84495962-2a7f3e80-acbd-11ea-83c4-ff1b283d3462.png)

It seems the CLI can't create the roles AuthRole and UnAuthRole.

However my user has the administrator access:
![image](https://user-images.githubusercontent.com/65644177/84496156-81851380-acbd-11ea-9c4b-10ee0e42ad7e.png)

**Comment by sintaro** [comment]
same here

**Comment by alexandrefilipiak** [comment]
I tried a previous Amplify CLI version (4.21.2).
And no more problem.

So you must have added a bug on latest version.

Hope that helps.

Alexandre

**Comment by SwaySway** [comment]
There was some API Issues with IAM that are now resolved as noted in the service health dashboard.
https://status.aws.amazon.com/

Should you have any issues related to this again please comment below.
