### ISSUE TITLE
Cognito - username is mail instead of sub after passwordless login (customAuthChallenge)

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4543]
i use the usersCreateAuthChallenge / usersDefineAuthChallenge ... 
When i create the user, the username is the sub from cognito. So in the most example code from amplify doc is the username used for calls. 

so now when i log in with the customAuthChallenge, the user is logged in, but the cognito username is now the mail of the user instead of the sub.

**Comment by davidbiller** [comment]
@SwaySway 
As WorkAround i use now user.attributes.sub instead of user.username.
But in the AppSync Resolver i found this:
`#set( $identityValue = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )`

So i guess we need to fix this correct with the username?!

**Comment by davidbiller** [comment]
FYI:
So i checked an other Lambda (called per Appsync - Amplify GraphQL). 
In my DoSomeThingsLambda the identity.claims.username is correct username == sub. 
So in FrontEnd username == mail
When i call a Lambda per AppSync, it seems that username is == sub.

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
