### ISSUE TITLE
Leftover temporary directories cause hard crash

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4550]
**Describe the bug**
see below

**Amplify CLI Version**

4.21.1

**To Reproduce**

1. on any repo
2. `amplify pull`
3. CANCEL (ctrl C) while you are halfway through
4. then run `amplify pull --appId d81hnxt3a5de --envName devs`
5. get this error:

![image](https://user-images.githubusercontent.com/6764957/84536168-d5c0df80-ad1f-11ea-9b79-ba3fa5302fae.png)

because the `amplify-backup` folder was copied out and left there because it wasnt cleaned up

**Expected behavior**

there are a few ways to tackle this

- `amplify pull` should not do any filesystem operations until all the steps are complete
- when copying and a preexisting file is detected, prompt for overwrite
- cleanup temp folders/files on SIGKILL or whatever the windows equivalent is

cc @attilah

**Comment by attilah** [comment]
Fixed in #4553
