### ISSUE TITLE
Old CloudFormation stacks randomly appearing after deleting/re-creating project.

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-cli#4554]
**Describe the bug**
Hi! Yesterday I had problems while pushing a new Hello World Lambda function with project resources access using the Amplify CLI (push kept failing, unfortunately I did't save the error trace at the moment) so I deleted the project using `amplify delete` to start fresh.

When re-creating the project (after making sure that everything was cleaned up on my AWS account), some random CloudFormation nested stacks started to appear on the CF console.

From the Amplify console I can see Authentication and API on my backend environment (even if I have not added them), but the most important thing is that I can't clean that. When I run `amplify pull` it says that there is nothing to pull, same thing on push (locally I have a clean project).

It has been impossible to go forward with this project due to awful and strange errors/bugs.

Sorry that I can't provide you with more details. I will proceed to manually delete the ghost created CloudFormation nested stacks to see if I can get all synchronised again.

**Amplify CLI Version**
@aws-amplify/cli@4.21.3 globally installed using npm v6.14.5.

**To Reproduce**
N/A.

**Expected behavior**
N/A.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Node Version. v14.4.0

**Additional context**
N/A.

**Comment by ernestostifano** [comment]
UPDATE: I've just finished cleaning everything up. I've used a CloudFront template from a clean Amplify project and manually corrected drifts. Everything seemed to be ok and in sync. However, once I redeployed one of the connected branches (manually from Amplify console) (along with my dev backend environment), all the CloudFormation stacks appeared again. The whole project seems to be messed up.

**Comment by ernestostifano** [comment]
UPDATE: Figured it out. There was an old version of my backend environment commited in my connected branches. Each time that I manually re-deployed a branch, my whole environment got overwritten. I also found that this was caused because of an option that can only be set when connecting the first branch od the project (something about updating the backend environment on every commit). I don't know how useful could that option be, at best it creates multiple sources of truth and this behaviour is not documented anywhere. No warnings about the environment being overwritten either.

**Comment by attilah** [comment]
@ernestostifano I see that you figured out and solved the problem. Since the console is connected to your branches source control is the source of truth.

Is there anything we can make it to have a better UX/DX either in Amplify CLI or Amplify Console side?

If yes, please describe the missing scenario, so we can turn it into a feature request/enhancement either in the CLI or Console. If not, just close the issue.
