### ISSUE TITLE
Use @aws-amplify/api-graphql instead of deprecated @aws-amplify/api in graphql code generator

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4555]
**Is your feature request related to a problem? Please describe.**

The amplify GraphQL API service code generator (I'm using angular target), imports from @aws-amplify/api. Specifically it imports `import API ... from '@aws-amplify/api`. 

API however is now deprecated. See https://github.com/aws-amplify/amplify-js/blob/164d66bb17019cf24f469f12c129b8d04db3a8f0/packages/api/src/index.ts#L24. 

**Describe the solution you'd like**
You should use named imports and import from the @aws-amplify/api-graphql package. 

**Describe alternatives you've considered**
Change the auto-generated code after it's generated, or not using the generated API.service.ts altogether. 

**Additional context**
They made these changes to reduce package sizes of frontend apps.

**Comment by attilah** [comment]
@hisham thanks for the suggestion, we'll look into it. I mark it as an enhancement.
