### ISSUE TITLE
AppSync Condition Update doesn't work with mock

### ISSUE THREAD

**Issue by gaochenyue** [aws-amplify/amplify-cli#4556]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
AppSync Condition Update doesn't work in mock. 

Schema
```
type Billing
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update, delete, read] }
      {
        allow: public
        provider: apiKey
        operations: [create, update, delete, read]
      }
    ]
  )
  @key(fields: ["owner"]) {
  owner: String!
  stripCustomerId: String
  paymentMethod: String
}
```
Mutation
```
export const updateBilling = /* GraphQL */ `
  mutation UpdateBilling(
    $input: UpdateBillingInput!
    $condition: ModelBillingConditionInput
  ) {
    updateBilling(input: $input, condition: $condition) {
      owner
      stripCustomerId
      paymentMethod
      createdAt
      updatedAt
    }
  }
`;
```
Run the query to list all the existing data
```
query MyQuery {
  listBillings {
    items {
      createdAt
      paymentMethod
      owner
      stripCustomerId
      updatedAt
    }
  }
}

Response:
{
  "data": {
    "listBillings": {
      "items": [
        {
          "createdAt": "2020-06-13T19:19:22.092Z",
          "paymentMethod": "test",
          "owner": "test",
          "stripCustomerId": "test",
          "updatedAt": "2020-06-13T19:19:22.092Z"
        }
      ]
    }
  }
}
```

Run the update mutation in AppSync mock console
```
mutation MyMutation {
  updateBilling(input: {owner: "test", paymentMethod: "test2", stripCustomerId: "test2"}, condition: {stripCustomerId: {attributeExists: true, eq: "test"}}) {
    stripCustomerId
    paymentMethod
  }
}

response:
{
  "data": {
    "updateBilling": null
  },
  "errors": [
    {}
  ]
}

```
Checked the data again. It was not updated

The same queries work in the cloud
```
Response in the cloud when running the same update mutation above
{
  "data": {
    "updateBilling": {
      "stripCustomerId": "test2",
      "paymentMethod": "test2"
    }
  }
}
```

**Amplify CLI Version**
4.21.1

**To Reproduce**
see description

**Expected behavior**
Condition update works with mock as it does in cloud

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Mac
 - Node Version. 10

**Additional context**

**Comment by attilah** [comment]
@gaochenyue upon checking the condition you try to use, that seems to be invalid. You specify 2 conditions within one expression object, you need an `and` enclosure for the checks.

```graphql
condition: {
  and: [
    stripCustomerId: { eq: "test"}
    stripCustomerId: { attributeExists: true }
   ]
}
```

But the `eq` also covers the attribute existence, no need for that, a pure equality condition is enough based on the expression you defined.

As the question has been answered I'm closing the issue if something new comes up, feel free to reopen the issue.

**Comment by alialaa** [comment]
Hello @attilah, I also get this in the mock server. I don't think what you mentioned in your answer is what was causing the problem. Here are screenshots for the same mutation in the mock server and on the appsync console:

<img width="775" alt="Screen Shot 2020-09-01 at 11 49 36 PM" src="https://user-images.githubusercontent.com/324106/91910343-20168480-ecaf-11ea-95c6-8426b2f9ba78.png">
<img width="1028" alt="Screen Shot 2020-09-01 at 11 49 46 PM" src="https://user-images.githubusercontent.com/324106/91910353-2442a200-ecaf-11ea-945f-0f924a55f3d9.png">

**Comment by djwood** [comment]
I'm seeing the same issue with Amplify CLI 4.27.2. Do we need to open a new issue?
