### ISSUE TITLE
Does generated API.service.ts support authMode?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4558]
**Which Category is your question related to?**
GraphQL API & Code Generator

**Amplify CLI Version** 
4.21.3

**What AWS Services are you utilizing?**
AppSync 

**Provide additional details e.g. code snippets**
I'm confused by the generated API.service.ts Angular service. I created an API with primary auth mode of user pool, and secondary auth mode of api key. 

I have correctly annotated the graphql schema like follows: 

```
type Query {
  helloWorld(
    msg: String!
  ): String
    @function(name: "MyGraphQLResolverFn-${env}")
    @auth(rules: [{ allow: public, provider: apiKey }])
}
```

But when I try to call this via API.service.ts. I get error message of "No credentials". So then I change the autogenerated code to pass authMode as follows: 

```
    const response = (await API.graphql({
      ...graphqlOperation(statement, gqlAPIServiceArguments),
      authMode: GRAPHQL_AUTH_MODE.API_KEY
    })) as any;
```

And things work. 

So is this auto-generated code just out of date and does not support auth mode? Shouldn't the auto-generated code be smart enough to look at the graphql schema and use the appropriate auth mode when calling the graphql endpoint?

**Comment by attilah** [comment]
@hisham based on the snippet you sent when you've Cognito configured as default that just means that the already logged in user's credentials (JWT token) will be submitted along with your GraphQL request. When you receive the "No credentials" error message from AmplifyJS that means that there is no currently logged in user. API Key authentication just requires you to configure Amplify from `aws-exports.js`, that's the reason why it works.

Make sure that before the GraphQL call you have a logged in user. `Auth.currentCredentials` should return a logged in user if there is one. Check the Amplify JS docs for more information and if you encounter issues around it, I suggest to open an issue in that repository.
Docs: https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#configure-your-application

**Comment by hisham** [comment]
I understand and you're correct - I have no cognito logged in user at the time. But this API is only accessible through apiKey and apiKey is set. So why is cognito logged in user required if the api is accessible via api key? I'm still writing my code so have no cognito login functionality implemented yet and am using apiKey to connect to the graphql api and test it for now during development. 

I kind of see what you mean, that the GraphQL API was setup with a user pool. So you're saying all access to that API require a logged in cognito user even if certain things in the schema require only apiKey?

**Comment by hisham** [comment]
It's a bit confusing, since the backend (AppSync) clearly allows access to that graphql api with api key as the auth mode and no logged in cognito user.
