### ISSUE TITLE
Clarify security implications of using ID Token vs. Access Token for AppSync authorization

### ISSUE THREAD

**Issue by lennybr** [aws-amplify/amplify-cli#456]
When using AppSync with Amazon Cognito User Pool as the authorization type, only the ID Token (by referencing `$context.identity`) is passed along to the resolvers for authorization checks. Per [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html) and [*aws-amplify/amplify-cli* auth transformers](https://aws-amplify.github.io/docs/cli/graphql#auth) this is expected, but it goes against OID specs that say only the Access Token should be used for authorization.

Since the ID Token can't be revoked (as expected), a user can be removed from a Cognito User Pool Group, but continue to perform actions thru AppSync as if they are still an authorized member of that Group, for up to an additional 60 minutes (until the ID Token expires, a hard limit of Cognito User Pools).

Following OID specs, shouldn't this type of authorization be checked against the Access Token instead. Since Access Token's can be revoked with [global-sign-out](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/global-sign-out.html), as long as AppSync checks that the Access Token is still valid, this eliminates the risk.

**To Reproduce**
1. Create an AppSync model using @auth group type rule
2. Create a user and add them to relevant group in Cognito User Pool
3. Perform protected action (which succeeds as expected)
4. Remove user from relevant group in Cognito User Pool
5. Perform protected action again with same ID Token (should fail as they are no longer a member of the respective group, but instead succeeds)

**Expected behavior**
AppSync uses the Access Token instead of the ID Token for any authorization other than ownership. Potentially provide access thru similar `$context.access` with AppSync ensuring that the Access Token is still valid.

This came up [here](https://github.com/aws-amplify/amplify-js/issues/1772#issuecomment-432313882) as well.

**Comment by undefobj** [comment]
AppSync supports both the IdToken as well as the Access Token, but yes best recommended practice is to use the Access Token which the documentation in your link outlines:

```
const client = new AWSAppSyncClient({
  url: GRAPHQL_API_ENDPOINT_URL,
  region: GRAPHQL_API_REGION,
  auth: {
    type: AUTH_TYPE,
    // Get the currently logged in users credential from 
    // Amazon Cognito User Pools.
    jwtToken: async () => (
        await Auth.currentSession()).getAccessToken().getJwtToken(),
  },
  // Uses Amazon IAM credentials to authorize requests to S3.
  complexObjectsCredentials: () => Auth.currentCredentials(),
});
```

The GraphQL transformer also accounts for this as well in the `@auth` directive.

**Comment by lennybr** [comment]
Thanks for clarifying that we can pass in `Auth.currentSession().getAccessToken().getJwtToken()` and then `$context.identity` actually references the Access Token.

But I was still able to manually substitute with the ID Token as there appears to be no check that a user is actually using the Access Token and not the ID Token. I had to add something like the following to the resolver to check that it is the right token:

```
#if( $ctx.identity.claims.token_use != "access" )
  $util.unauthorized()
#end
```

Is that the right solution to ensure a valid Access Token is being used? Thanks for the help and clarification.

**Comment by undefobj** [comment]
Gotcha so you would like to have either documentation or a way to restrict specifically to an IdToken, potentially in the `@auth` directive of the GraphQL transformer. Is that correct?

**Comment by lennybr** [comment]
Fair enough. It may be worth some documentation to help those transitioning from other auth services that do follow that best practice -- but that's really more for Cognito than Amplify docs. Thanks @undefobj.

**Comment by erik-induro** [comment]
@undefobj What is the status of this? Not having custom claims available for authorization in the resolvers is a pain for multi-tenant solutions where using Cognito Groups isn't reasonable due to limits. I see the following as my options:

1. Change the Amplify SDK to pass the identity token. (I don't want to modify the vendor code or use the identity token since I can't revoke it and have to wait for it to expire)
2. Use the AWS SDK instead and pass the identity token. (I lose the benefit of the generated code and token refresh and the aforementioned reasons to not use the identity token)
3. Overwrite the resolvers to use the access token to lookup the user's claims and use them. (I have to overwrite every generated resolver and add another call in each request which removes a good bit of the benefit of using amplify over appsync directly)

I'm open to suggestions on other options and would love an update on how to best handle custom claims. Thanks!

Am I missing any?

**Comment by kaustavghosh06** [comment]
@erik-induro We’re working on the @auth directive to support this (adding a field for custom claims) and auto-generate the resolvers accoridngly. Closing this in favor of a similar request - https://github.com/aws-amplify/amplify-cli/issues/1899

**Comment by zoellner** [comment]
My hunch is that one of the biggest issues with ID vs. Access Token is that there's no way to get the IdentityID from an access token. Can't use Pre Token Generation Lambda Trigger to add things to the access token and there's not API to get an identity pool id from an access token/UserID.
There are a ton of questions on github and stackoverflow that don't seem to address this directly but have that fundamental missing link.
