### ISSUE TITLE
Trying to use model within post-confirmation function

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#4568]
**Describe the bug**
When the user is registered with the method `Auth.signup` and this one confirmed the code received by email. I want to execute the post-confirmation trigger and update a User table made through the method @model on the schema.graphql file.

I updated the Auth like this:

```
andres@DESKTOP-CPTOQVN:~/TeVi$ amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Create your own module
Succesfully added the Lambda function locally
? Do you want to edit your custom function now? No
Successfully updated resource tevi locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
```

And then I did `amplify push`. Then when the function was completed, I updated this one like this:

```
andres@DESKTOP-CPTOQVN:~/TeVi$ amplify update function
Using service: Lambda, provided by: awscloudformation
? Please select the Lambda Function you would want to update teviPostConfirmation
? Do you want to update permissions granted to this Lambda function to perform on other resources in your project? Yes
? Select the category storage
? Storage has 12 resources in this project. Select the one you would like your Lambda to access User:@model(appsync)
? Select the operations you want to permit for User:@model(appsync) create, update

You can access the following resource attributes as environment variables from your Lambda function
        API_TEVI_GRAPHQLAPIIDOUTPUT
        API_TEVI_USERTABLE_ARN
        API_TEVI_USERTABLE_NAME
        ENV
        REGION
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? No
Successfully updated resource
```

Then I did `amplify push` and I got this error:

```
andres@DESKTOP-CPTOQVN:~/TeVi$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name        | Operation | Provider plugin   |
| -------- | -------------------- | --------- | ----------------- |
| Function | teviPostConfirmation | Update    | awscloudformation |
| Auth     | tevi                 | No Change | awscloudformation |
| Api      | tevi                 | No Change | awscloudformation |
| Storage  | s3c1026a67           | No Change | awscloudformation |
? Are you sure you want to continue? Yes
⠼ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

Circular dependency between resources: [functionteviPostConfirmation, authtevi, UpdateRolesWithIDPFunctionOutputs, apitevi, UpdateRolesWithIDPFunction]
An error occured during the push operation: Circular dependency between resources: [functionteviPostConfirmation, authtevi, UpdateRolesWithIDPFunctionOutputs, apitevi, UpdateRolesWithIDPFunction]
```

This is the `backend-config.json` I have right now:

```
{
    "auth": {
        "tevi": {
            "service": "Cognito",
            "providerPlugin": "awscloudformation",
            "dependsOn": [
                {
                    "category": "function",
                    "resourceName": "teviPostConfirmation",
                    "triggerProvider": "Cognito",
                    "attributes": [
                        "Arn",
                        "Name"
                    ]
                }
            ]
        }
    },
    "api": {
        "tevi": {
            "service": "AppSync",
            "providerPlugin": "awscloudformation",
            "output": {
                "authConfig": {
                    "additionalAuthenticationProviders": [
                        {
                            "authenticationType": "AWS_IAM"
                        }
                    ],
                    "defaultAuthentication": {
                        "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                        "userPoolConfig": {
                            "userPoolId": "authtevi"
                        }
                    }
                }
            }
        }
    },
    "storage": {
        "s3c1026a67": {
            "service": "S3",
            "providerPlugin": "awscloudformation"
        }
    },
    "function": {
        "teviPostConfirmation": {
            "build": true,
            "providerPlugin": "awscloudformation",
            "service": "Lambda",
            "dependsOn": [
                {
                    "category": "api",
                    "resourceName": "tevi",
                    "attributes": [
                        "GraphQLAPIIdOutput"
                    ]
                }
            ]
        }
    }
}
```

**Amplify CLI Version**
4.21.3

**Expected behavior**
Work with the post-confirmation function and create or update content on the User table with this one.

**Desktop (please complete the following information):**
 - OS: Windows - WSL2
 - Node Version. v14.4.0

How can I fix it :/?

**Comment by attilah** [comment]
@MontoyaAndres the error message is actually correct since you are creating a circular dependency between your resources with the `update function` command.

Your API depends on Cognito for authentication, your function depends on Auth, and from the function you want to access the API.

To make it work, you've to break the circular dependency in some way, today the CLI does not have a feature that would support this scenario.

On possible solution could be to create a custom CloudFormation stack, which does the additional IAM access grants for the function to invoke the GraphQL API and make that stack dependent on the API and Auth stack.

I mark this issue as an enhancement, since I see that the DX part could be made better to do additional checks in the update flow and warn customers that this relationship would create a circular dependency, so it does not just fails at deploy but would block the creation of the circular dependency. A longer term enhancement could be to enabling such scenario with the CLI itself.

**Comment by MontoyaAndres** [comment]
Thanks! Do you have any resources that can help me to fix it? Maybe something about how to create a custom CloudFormation stack, which does the additional IAM access grants... I don't know how to do that ☹️

**Comment by MontoyaAndres** [comment]
I could fix it by executing another lambda through the post-confirmation one, this is the whole cloud formation template of the post-confirmation lambda:

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Lambda resource stack creation using Amplify CLI",
	"Parameters": {
		"GROUP": {
			"Type": "String",
			"Default": ""
		},
		"modules": {
			"Type": "String",
			"Default": "",
			"Description": "Comma-delimmited list of modules to be executed by a lambda trigger. Sent to resource as an env variable."
		},
		"resourceName": {
			"Type": "String",
			"Default": ""
		},
		"trigger": {
			"Type": "String",
			"Default": "true"
		},
		"functionName": {
			"Type": "String",
			"Default": ""
		},
		"roleName": {
			"Type": "String",
			"Default": ""
		},
		"parentResource": {
			"Type": "String",
			"Default": ""
		},
		"parentStack": {
			"Type": "String",
			"Default": ""
		},
		"env": {
			"Type": "String"
		}
	},
	"Conditions": {
		"ShouldNotCreateEnvResources": {
			"Fn::Equals": [
				{
					"Ref": "env"
				},
				"NONE"
			]
		}
	},
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Metadata": {
				"aws:asset:path": "./src",
				"aws:asset:property": "Code"
			},
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"teviPostConfirmation",
						{
							"Fn::Join": [
								"",
								[
									"teviPostConfirmation",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"Environment": {
					"Variables": {
						"ENV": {
							"Ref": "env"
						},
						"MODULES": {
							"Ref": "modules"
						},
						"REGION": {
							"Ref": "AWS::Region"
						},
						"GROUP": {
							"Ref": "GROUP"
						}
					}
				},
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs10.x",
				"Timeout": "25",
				"Code": {
					"S3Bucket": "amplify-tevi-dev-112553-deployment",
					"S3Key": "amplify-builds/teviPostConfirmation-6a6d2f6f482f2f586966-build.zip"
				}
			}
		},
		"LambdaExecutionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Fn::If": [
						"ShouldNotCreateEnvResources",
						"teviPostConfirmation",
						{
							"Fn::Join": [
								"",
								[
									"teviPostConfirmation",
									"-",
									{
										"Ref": "env"
									}
								]
							]
						}
					]
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Principal": {
								"Service": [
									"lambda.amazonaws.com"
								]
							},
							"Action": [
								"sts:AssumeRole"
							]
						}
					]
				}
			}
		},
		"lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:InvokeFunction"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:lambda:${region}:${account}:function:addUser-${env}",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										},
										"env": {
											"Ref": "env"
										}
									}
								]
							}
						}
					]
				}
			}
		}
	},
	"Outputs": {
		"Name": {
			"Value": {
				"Ref": "LambdaFunction"
			}
		},
		"Arn": {
			"Value": {
				"Fn::GetAtt": [
					"LambdaFunction",
					"Arn"
				]
			}
		},
		"LambdaExecutionRole": {
			"Value": {
				"Ref": "LambdaExecutionRole"
			}
		},
		"Region": {
			"Value": {
				"Ref": "AWS::Region"
			}
		}
	}
}
```

But the thing is in this part:

```
                   "lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						},
						{
							"Effect": "Allow",
							"Action": [
								"lambda:InvokeFunction"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:lambda:${region}:${account}:function:addUser-${env}",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										},
										"env": {
											"Ref": "env"
										}
									}
								]
							}
						}
					]
				}
			}
		}
```

If you see the line `PolicyDocument` you can see the new statement, following this comment https://github.com/aws-amplify/amplify-cli/issues/663#issuecomment-452029345 just replace `arn:aws:lambda:${region}:${account}:function:addUser-${env}` with your function, `addUser` is mine.

Then, in the post-confirmation lambda, I added this code:

```
const aws = require("aws-sdk");

const lambda = new aws.Lambda({
  region: process.env.REGION,
});

exports.handler = async (event, _, callback) => {
  try {
    await lambda
      .invoke({
        FunctionName: `addUser-${process.env.ENV}`, // my other function
        Payload: JSON.stringify(event, null, 2),
      })
      .promise();
  } catch (error) {
    callback(error);
  }

  callback(null, event);
};
```

**Comment by ataibarkai** [comment]
Thank you for updating this information on here @MontoyaAndres.

Did you define your addUser lambda outside of amplify? I tried what you describe here with an amplify-defined createUser lambda, and I just get yet another circular dependency:
`[functioncreateUserObject, UpdateRolesWithIDPFunctionOutputs, apiAdminQueries, authvokea90410f7, authuserPoolGroups, functionAdminQueriesc9648803, apivoke, functionvokea90410f7PostConfirmation, UpdateRolesWithIDPFunction]`

(which is not altogether unexpected..)

**Comment by MontoyaAndres** [comment]
@ataibarkai I created the function using Amplify. I don't know if maybe Amplify has updated something and now it's not working as expected. One thing you can do is look for information about "how to execute a lambda within other lambda" or something. Or other is just to do it on the front end, when the user adds the confirmation code on the page, then you'll execute the graphql mutation to save the user...

**Comment by ataibarkai** [comment]
Turns out the error was the result of a cache invalidation issue. The solution does still work

**Comment by FOMSON** [comment]
Same issue...

This https://github.com/aws-amplify/amplify-cli/issues/1874 seems related.

Also, after 3 days of trying all sorts of things, a 'workaround' I came up with is to **create a GraphQL custom reslver to handle signing up**. This way would allow to have access to all other AMplify resources without this circular dependency issue...

**Comment by half2me** [comment]
I'm having this exact issue. All I wanted to do was copy the user details from cognito into dynamodb after the user signs up.
Didn't think this was such an advanced scenario. Is there some guide on how to setup the correct IAMs etc?

**Comment by mjza** [comment]
As it has been discussed, we can solve this problem by invoking a function from another. 

First, we assume that you used `amplify update auth` and added `Cognito Post Confirmation` function to add the user to a group. 

Also it seems you followed the [this tutorial](https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js) to make a function for adding user to a custom model after confirmation event. However, you cannot follow the last step of this tutorial as only one function can be bind to the `Post confirmation` trigger. So let us bind our first function to `Post confirmation` trigger and keep this new function unbind. I assume that you named this recent function as `addusertotable`.

If you have added a function with `amplify update auth`, you will have a file which is called `add-to-group.js`, modify the function as follow:

```js
/* eslint-disable-line */ const aws = require('aws-sdk');

// My defined function starts here
var addUserToTable = function (event, context) {
  // Call function to add user to table Users
  var lambda = new aws.Lambda({
    region: process.env.AWS_REGION
  });

  var params = {
    FunctionName: 'addusertotable-' + process.env.ENV,
    InvocationType: 'RequestResponse',
    Payload: JSON.stringify(event, context)
  };

  lambda.invoke(params, function (err, data) {
    if (err) {
      console.error(err);
    } else {
      console.log(params.FunctionName + ': ' + data.Payload);
    }
  });
};
// My defined function ends here

exports.handler = async (event, context, callback) => {
  // Call function to add user to table Users
  addUserToTable(event, context); // this is also my code to call my defined function
  // Rest are original code from amplify template 
  // Add group to the user
  const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider({ apiVersion: '2016-04-18' });
  const groupParams = {
    GroupName: process.env.GROUP,
    UserPoolId: event.userPoolId,
  };

  const addUserParams = {
    GroupName: process.env.GROUP,
    UserPoolId: event.userPoolId,
    Username: event.userName,
  };

  try {
    await cognitoidentityserviceprovider.getGroup(groupParams).promise();
  } catch (e) {
    await cognitoidentityserviceprovider.createGroup(groupParams).promise();
  }

  try {
    await cognitoidentityserviceprovider.adminAddUserToGroup(addUserParams).promise();
    callback(null, event);
  } catch (e) {
    callback(e);
  }
};
```

As it has been discussed [here](https://github.com/aws-amplify/amplify-cli/issues/663), we need to add a segment to the lambda policy that allows us to invoke the secondary lambda function (i.e. addusertotable). 

Then find the `xyzPostConfirmation-cloudformation-template.json` file, and then change its `PolicyDocument` entry like this:

```json
"PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
                  {
                    "region": {
                      "Ref": "AWS::Region"
                    },
                    "account": {
                      "Ref": "AWS::AccountId"
                    },
                    "lambda": {
                      "Ref": "LambdaFunction"
                    }
                  }
                ]
              }
            },
            {
              "Effect": "Allow",
              "Action": "lambda:InvokeFunction",
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:lambda:${region}:${account}:function:addusertotable-${env}",
                  {
                    "region": {
                      "Ref": "AWS::Region"
                    },
                    "account": {
                      "Ref": "AWS::AccountId"
                    },
                    "lambda": {
                      "Ref": "LambdaFunction"
                    },
                    "env": {
                      "Ref": "env"
                    }
                  }
                ]
              }
```

Actually what I have added is the second object inside the `Statement` array. 

Please note that `addusertotable` is the name of the custom function.

**Comment by wvidana** [comment]
@attilah is anyone looking into this? There are several issues, mostly closed in favor of this one.

Building an application that relies on Cognito auth means that everything depends on Cognito, so it is impossible to add any Lambda triggers using the Amplify

**Comment by wvidana** [comment]
https://github.com/aws-amplify/amplify-cli/issues/2076

**Comment by mcottingham** [comment]
@aws-amplify-ops I'm sure I speak for the group when I say we would love an update on this.  Seems there are many people having the same issue, and all threads are being referred back here where there is no official solution.  It is not an acceptable solution to rely on the client to call a 'create profile' event upon first login.  Some of our applications trigger a lot of custom logic and events upon successful account creation and we need to have this functionality.  Any idea when it will be fixed?

**Comment by gstamatakis** [comment]
Although the workaround of calling another lambda is working, I was wondering if there is any way to access a resource like DynamoDB from inside a trigger (e.g PostConfirmation). It's a very common usecase after all.

**Comment by dorontal** [comment]
Same issue here... very stuck for several days. I am faced with two choices: 
1) Wait for the Amplify team to take care of this basic but crucial use-case issue
2) Try one of the suggested solutions above, which has high overhead of learning, trying, and later (when Amplify solves this in a cleaner way) changing back to the Amplify team's solution - I thought one of the goals of Amplify was that we don't have to deal much with complicated cloudformation template code or issues(?).

For now our team picks (2), to wait, because too much time will be lost otherwise and we can work on other stuff.

Therefore, despite having a fantastic product, Amplify team, it could be made a heck of a lot more useful once this important issue is fixed.  Thanks very much, regardless, for your great work on the Amplify project.

**Comment by kylekirkby** [comment]
@attilah is there any update from the Amplify team on whether this **very sought after** and **common** use-case will be supported soon?

**Comment by akshbhu** [comment]
Hi All,

We are actively discussing this with our internal team for a general solution or atleast to support this Common use case.

**Comment by droidgeek1** [comment]
@akshbhu Thanks for leading discussion but I am having hard time follow thru all these issues and understand what fix was finally implemented. Would appreciate a simple example for guidance on how to access adminApi for cognito and also model (becomes dynamodb  table) from PostConfirmation trigger. I got the latest 4.50.. CLI but still see cyclical dependency when trying to 'amplify update function' on PostConfirmationTrigger lambda when giving both auth and storage . Help!!

**Comment by droidgeek1** [comment]
@akshbhu I was able to resolve my problems. PostConfirmation trigger has access to model now. But one perhaps a newbie question. Env variable did not have right userPoolId but had correct model/table name in the environment as it has Ref vs tablename has the whole Import function. Is that bug or intentional?

**Comment by benrosen** [comment]
For anyone still seeing this issue, make sure you update your local installation of Amplify to the latest version as per [these instructions from AWS](https://docs.amplify.aws/cli/usage/upgrade).

**Comment by chris-mds** [comment]
Updated the CLI to latest version and worked for the existing environment.
Now when I try to create a new environment the error occurs again

```
git branch -c newbranch
git checkout newbranch
amplify env add // newbranch
amplify push // newbranch

```
Circular dependency between resources error again.

Existing branches works like expected.

**Comment by akshbhu** [comment]
Hi @chris-mds 

We have introduced a FF : breakCircularDependency which you can set to true in cli.json in your project. This flag when set to true will set auth triggers with custom lambda resource which breaks auth dependency on functions.

Let me know if this helps?

**Comment by akshbhu** [comment]
Hi @chris-mds 

This file mist be present in the your amplify project under this path : `<amplify-project-name>/amplify/cli.json`
You can also find the documentation here: https://docs.amplify.aws/cli/reference/feature-flags#configuration

**Comment by chris-mds** [comment]
Hi @akshbhu,

File is missing even after rerun amplify init. Can I manually create it and add the FF to it?
Like so?

`{
  "features": {
breakCircularDependency: true
}
}`

**Comment by chris-mds** [comment]
Hi @akshbhu,

weird things are happening, when I manually add the cli.json file:
I get the following error

`...AuthPostConfirmationArn' at 'lambdaConfig.postConfirmation' failed to satisfy constraint: Member must satisfy regular expression pattern: arn...`

Looks like there are some strange dependencies between the cli and Cognito?

**Comment by akshbhu** [comment]
Hi chris

I guess you haven't updated auth when enabling FF , my bad I should have informed you regarding this. You should update amplify to latest version.

So when you enable FF , you should do ```amplify update auth``` with same previous settings , this will break the dependency of auth with functions and will create a new trigger template in auth backend folder.

Can you try amplify update auth after enabling FF to true in cli-test.json?

**Comment by chris-mds** [comment]
Hi @akshbhu,

Tried it now with a lot of different variations but I can't get it working. The push itself works not, but it always fails with updating the user pool. When updating the pool with same previous settings, the new trigger template in auth backend folder don't work. The triggers removed from the pool and when manually adding them again, all permissions for the functions are gone. So updating auth broke the entire configuration. Had to reset it from my prod env.

**Comment by droidgeek1** [comment]
Hi @akshbhu,

My verification code emails stopped coming after adding following to cli.json. It did break circular dependency for me though which was good but then how do I fix my verification email. Previously I did not have cli.json.
{
  "features": {
    "graphQLTransformer": {
      "addMissingOwnerFields": true,
      "validateTypeNameReservedWords": true,
      "enableIterativeGSIUpdates": false
    },

    "auth": {
      "enableCaseInsensitivity": true,
      "breakCircularDependency": true
    }
  }
}

**Comment by sananbintahir** [comment]
@droidgeek1 I'm having the same issue. For some reason even though email is passed to AutoVerifiedAttributes in the cloudformation file, when you do amplify push the verified attributes are set to none. The only way to fix it is to go to Cognito console, select the user pool, go to 'MFA and verifications', and select email under "Which attributes do you want to verify?" Pretty sure its a bug

**Comment by macsj200** [comment]
I also found that the auth email is not being sent after setting the FF to true.

**Comment by akshbhu** [comment]
Hey Guys I am looking into this  and reopening this issue for this bug.

**Comment by macsj200** [comment]
@akshbhu thank you! I tried `amplify pull` after setting the verify attribute to `Email` and it didn't pick up a diff. I'm not sure which CloudFormation template values control this field but it doesn't seem to be in sync anymore.

**Comment by droidgeek1** [comment]
@sananbintahir  Thank you. I also had to same.
@akshbhu When would this be fixed? I also got charged for SMS when in fact I do not want to use SMS. But the bug has SMS selected on the web-console. It does not let me de-select.

**Comment by droidgeek1** [comment]
@sananbintahir wondering if you use SMS and if not, were you able to disable on the console?

**Comment by sananbintahir** [comment]
@droidgeek1 It's enabled for me too, but I want to use SMS anyways so it's not a problem

**Comment by bpmweel** [comment]
I have tried to fix my circular dependency by setting `breakCircularDependency` to true in my cli.json. This helped to alleviate the circular dependency, but it somehow managed to removed the access to add users to a group from the PostConfirmation function (which it provides out of the box previously).

I got the error message: 
```
"errorType": "AccessDeniedException",
  "errorMessage": "User: arn:aws:sts::204861241826:assumed-role/receipt09937347PostConfirmation-{myenv}/receipt09937347PostConfirmation-{myenv} is not authorized to perform: cognito-idp:CreateGroup on resource: arn:aws:cognito-idp:...",
...
```

I added the following block from a previous version of the couldformation-template and it started working again (I redacted the appId).
```json
  {appId}PostConfirmationAddToGroupCognito:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: {appId}PostConfirmationAddToGroupCognito
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminAddUserToGroup
              - cognito-idp:GetGroup
              - cognito-idp:CreateGroup
            Resource: !GetAtt
              - UserPool
              - Arn
      Roles:
        - !Join ['',["{appId}PostConfirmation", '-', !Ref env]]
```


Is this a bug with the breakDependency fix or did I do something wrong here?

**Comment by akshbhu** [comment]
Hi All

Trigger permissions issue is tracked here:https://github.com/aws-amplify/amplify-cli/issues/7582
