### ISSUE TITLE
AWSTimestamp comparison operations not working

### ISSUE THREAD

**Issue by lkolodziejek** [aws-amplify/amplify-cli#4572]
**Describe the bug**
Query's comparison operators are not working properly with AWSTimestamp data type. 
Following error is return from GraphQL when e.g. 'lt' operator is used on AWSTimestamp item:
_Variable 'lt' has an invalid value. Expected type 'Int' but was 'Long'."_

**Amplify CLI Version**
4.21.3

**To Reproduce**
Define item in schema as AWSTimestamp. Try to use ModelIntInput or FilterInput to parameterize query.

**Expected behavior**
GraphQL to expect AWSTimestamp and not Int

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v14.2.0

**Comment by attilah** [comment]
@lkolodziejek I tried to reproduce this issue, but works as expected from mock and from AppSync console as well. I think that it is possible that you've a client library side error in your project and it is not related to the CLI or AppSync or the generated schema/types.

I've used the following schema and operations to try to reproduce your issue:

```graphql
type Person @model {
  id: ID!
  name: String!
  ts: AWSTimestamp
}
```

Operations:
```graphql
mutation M {
  P1: createPerson(input: {
    id: "P1"
    name:"Person #1"
    ts: 1592331111
  }) {
    id
    name
    ts
  }  
  P2: createPerson(input: {
    id: "P2"
    name:"Person #3"
    ts: 1592331222
  }) {
    id
    name
    ts
  }  
  P3: createPerson(input: {
    id: "P3"
    name:"Person #3"
    ts: 1592331333
  }) {
    id
    name
    ts
  }  
}


query Q {
  listPersons
  (
    filter: {
      ts: {
        lt: 1592331333
      }
    }
  )
  {
    items {
      id
      name
      ts
    }
  }
}
```

Get back to us some details about the error where are you seeing it, can it be a client side type error.

**Comment by lkolodziejek** [comment]
Thank you for the response.
I had in my database timestamp elements in Java Timestamp format (in miliseconds), instead of AWSTimestamp format (seconds only).
