### ISSUE TITLE
Amplify multi-env issue with auth Google federated auth provider

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#4584]
**Describe the bug**
I've got a working `develop` git branch (amplify env = develop) and I'm ready to merge my amplify changes and push my product to production. I've checked out to the `master` branch (amplify env = master). I've fixed some merge conflicts which were showing in my amplify/backend/resource/cf.json files complaining about different env values (surely this shouldn't be the case).  I've then run `amplify env check master` which then asked me to enter my Google Auth Provider Client Id/Secret - which I did. After which I run `amplify push` to then get presented with the following error:

```shell
 UPDATE_FAILED      auth2ad5d26 AWS::CloudFormation::Stack Tue Jun 16 2020 21:08:21 
GMT+0100 (British Summer Time) Parameters: [googleClientId] do not exist in the template
```

**Amplify CLI Version**
4.21.0

**To Reproduce**
As described above.

**Expected behavior**
`amplify push` to create my resources successfully and not complain about a missing googleClientId which I'd just entered.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version: v12.11.1

**Additional context**
Any help would be appreciated with this one folks! If I find the cause and/or a solution I'll update as always.

BR,

Kyle

**Comment by attilah** [comment]
@kyleboss could you please provide some more information to help you better? so you've two environments and your project has cognito + google configured and when you checkout the branches and Amplify CLI asks for your Google client id and secret you supply them, but push fails as CloudFormation cannot find those parameters in the supplied filed.

Could you verify that those secret/id values are present in your filesystem where you are executing the push from?

**Comment by kylekirkby** [comment]
@kyleboss ? :D I run `amplify auth update` and updated my Google Auth provider Client ID / secret and it magically worked! And @attilahboss exactly has you described apologies if the initial issue was a bit rambly.

Best regards,

**Comment by attilah** [comment]
Sorry autocomplete of GH failed me did not popped up your alias for some reason :( Glad you made it work, closing the issue, if something comes up feel free to reopen this issue or open a new one!

Cheers!

**Comment by kylekirkby** [comment]
> Sorry autocomplete of GH failed me did not popped up your alias for some reason :( Glad you made it work, closing the issue, if something comes up feel free to reopen this issue or open a new one!
> 
> Cheers!

@attilah no worries - I just thought I may have come across the wrong way :D I don't want to anger the amplify team :D
