### ISSUE TITLE
Improve experience with amplify-tools using @auth models and datastore for iOS

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/amplify-cli#4585]
**Is your feature request related to a problem? Please describe.**
While trying to debug a reported bug with `@auth` models, I created a new iOS project w/ Amplify tools.  I started out with having amplify tools to generate models, but because the models have @auth, while running amplify-tools as part of the build process within xcode, amplify tools complains that the project has no CognitoUserPools authentication provider configured.

Not knowing how to rememdy this, I went to run `amplify add auth`, to which was given an error of:
```
Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify”.
```
At this point, it is unclear how if i should run `amplify init`, since i already have a generated amplifyconfiguration.json -- so it's unclear if the error message is correct in telling me that i need to be running `amplify init`

This experience is really confusing.  There doesn’t seem to be much documentation on amplify tools, so when you go slightly “off script” things break and lead to more head scratchy moments.

While syncing up with other teammates, it seems that i should have not used amplify-tools and just used amplify init, amplify add api, and generated the code manually.

**Describe the solution you'd like**
At the very least, amplify tools should tell me that this is not supported, and give me some remedy steps on how to move forward.  Ideally, I should be able to use amplify-tools for some of the more annoying tasks (e.g. adding various files to my project automatically), while being able to use the CLI manually.

**Describe alternatives you've considered**
Not using amplify tools.

**Additional context**

**Comment by attilah** [comment]
@wooj2 I sorry that you've this experience. To fully understand your situation I need some clarification about the current state.

If you clone the code freshly from source control and the repo has an existing Amplify project, you always need to run `amplify init` to get into the up to date state, configured state. If the project already had an environment which had its cloud resources deployed they'll be picked up and used, then amplify-tools - in fact he CLI itself - will detect it  and tooling should just work.

To be able to help better, tell more about what steps did you do to in that working directory?

**Comment by SwaySway** [comment]
We are aware this is an issue with using amplify scripts outside of the CLI. We are looking at how we can improve this experience. As an issue to track for updates please follow this thread: https://github.com/aws-amplify/amplify-cli/issues/4272
