### ISSUE TITLE
Get _version from @searchable resolver

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4589]
**Which Category is your question related to?**

I created an issue (#3818) regarding _version from DynamoDB being sent to ElasticSearch. That has been implemented and now I need to be able to get _version out of ElasticSearch. To do this I set "version": true" in the searchable request resolver. If I do a search with this query directly in the Kibana console in ElasticSearch I can see the data that is being returned.

```
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "classification",
        "_type": "doc",
        "_id": "9531fbe2-0bec-450d-82a9-3db2b248b484",
        "_version": 14,
        "_score": 1,
        "_source": {
          "_lastChangedAt": 1591569649866,
          "created": "2020-06-07T07:06:07.274Z",
          "__typename": "Classification",
          "name": "Example",
          "id": "9531fbe2-0bec-450d-82a9-3db2b248b484",
        } } ] } }
```

I have made 2 modifications to the standard generated reponse resolver below - one on the 3rd last line to be able to get the total number of records returned by the query (works perfectly), and one on the 8th line to update the current item with a _version field - however, nothing I try will seem to allow me to add this field to be returned by the response resolver.

```
#set( $items = [] )
#set( $nextToken = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    $util.qr($nextToken.add($entry.get("sort")))
  #end
  $util.qr($items.add($entry.get("_source")))
  $util.qr($items.put("_version", $entry.get("_version")))
#end
$util.toJson({
  "items": $items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```

**Amplify CLI Version** 
4.21.3

**What AWS Services are you utilizing?**

AppSync, DynamoDB, ElasticSearch Service

**Comment by attilah** [comment]
@sacrampton when looking at the code, this line looks suspicious to me:

` $util.qr($items.put("_version", $entry.get("_version")))`

That sets the `_version` field on `items` not on a given entry in the `items` array, isn't it the source of the problem? you want the `_version` for each item in the `items`, not?

**Comment by sacrampton** [comment]
Thanks for the response @attilah - appreciate it. Yep - that is the line that is not working.

Appreciate any suggestions you might have. The "for" loop is cycling through each $entry in $context.result.hits.hits and the previous line of code is adding an $item for each $entry and doing so successfully. This is "adding" a new $entry in the $items, so in the problem line of code you highlight I "put" a field on the current $item that has just been "added" in the previous line.

Regardless - whatever I'm doing is not working and I'm grateful for any suggestions.

**Comment by sacrampton** [comment]
Hi @SwaySway  / @attilah - just wondering if you've had any further thoughts on this.

If I search for a record with @searchable then I want to update it I have to have the _version for the record. If I've already done a search on ElasticSearch then I don't want to have to go back to DynamoDB to get the _version when its available in ElasticSearch - if I can just get it from the resolver. I appreciate this is probably a bit of VTL-101, but I'm kind of stuck here.

**Comment by SwaySway** [comment]
@sacrampton 
When enabling `@searchable` with DataStore. You could use that generate piece of resolver code.
```
#set( $es_items = [] )
#foreach( $entry in $context.result.hits.hits )
  #if( !$foreach.hasNext )
    #set( $nextToken = $entry.sort.get(0) )
  #end
  #set( $row = $entry.get("_source") )
  $util.qr($row.put("_version", $entry.get("_version")))
  $util.qr($es_items.add($row))
#end
$util.toJson({
  "items": $es_items,
  "total": $ctx.result.hits.total,
  "nextToken": $nextToken
})
```
I think the piece you are looking for is the adding `_version` from the entry and adding that into the same object that is `_source`. You could do this by first adding `_source` into a map and then add `_version`.

**Comment by sacrampton** [comment]
@SwaySway - thanks so much for this - I'll work on it today and confirm

**Comment by sacrampton** [comment]
Works brilliantly - thanks so much for your effort.
