### ISSUE TITLE
No updates are to be performed.

### ISSUE THREAD

**Issue by ignacio-dev** [aws-amplify/amplify-cli#4592]
Amplify version: 4.21.3

Right after using 'amplify add video' and adding a Livestream with the following parameters:

 Please select from one of the below mentioned services: Livestream
? Provide a friendly name for your resource to be used as a label for this category in the project: mylivestream
? Do you want to modify any advanced video encoding parameters? No
? Input Security Group:  0.0.0.0/0
? MediaLive ingest type:  RTMP_PUSH
? Encoding Profile:  FULL (6 renditions)
? Auto Start:  Yes
? Where do you want to stream to? MediaStore
✔ All resources built.

I try to run 'amplify push' and get the following:
✔ All resources copied.
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Video    | mylivestream  | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠇ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

No updates are to be performed.
An error occured during the push operation: No updates are to be performed.

**Comment by SwaySway** [comment]
Hello @ignacio-dev 
This could be an issue with the video category. Did you open an issue in their repo here?
https://github.com/awslabs/amplify-video

**Comment by attilah** [comment]
@ignacio-dev could you share any further error messages from the CloudFormation console?

**Comment by attilah** [comment]
@ignacio-dev I was able to reproduce it, reach out to the plugin's repository about this issue as @SwaySway suggested.

I'm closing the issue, if something new comes up feel free to reopen it if there is something wrong on the CLI side.
