### ISSUE TITLE
Generated code is missing fields in generated inputs

### ISSUE THREAD

**Issue by dkhunt27** [aws-amplify/amplify-cli#4594]
**Describe the bug**
The code generated API.ts (specifically the inputs) are missing/dropping fields

**Amplify CLI Version**
4.21.1

**To Reproduce**
Run amplify add api (graphql, apikey, annotated graphql schema (see below), all others defaults)
Run amplify mock api (typescript, statement depth 4, all others defaults)
Then if you check src/graphql/mutations.ts createDraftState, its input is CreateDraftStateInput
CreateDraftStateInput is defined in amplify/backend/api/[API NAME]/build/schema.graphql
Which uses DraftedPlayerInput, but is missing draftee field... as well as other inputs missing fields

- DraftedPlayerInput is missing draftee field
- DraftedPlayerSelectionInput is missing selectedBy field
- DraftedTeamInput is missing draftTeam, sponsor, toBeSlotted fields
- and most other inputs that have custom types are missing fields

**Expected behavior**
I would expect those generated inputs to include all the fields that are in the schema

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.18.0

**Additional context**
annotated graphql schema:

type Draftee @model {
  id: ID!
  key: String!
  position: String!
  rating: String!
  sponsor: Boolean!
  coach: Boolean!
  linked: String
  line: Int!
}

type DraftTeam @model {
  id: ID!
  key: String!
  coach: String!
}

type DraftStateSelection {
  pick: Int
  selection: Draftee
  selectedBy: DraftTeam
}

type DraftedPlayerSelection {
  pick: Int!
  selectedBy: DraftTeam!
}

type DraftedPlayer {
  draftee: Draftee!
  selected: DraftedPlayerSelection
  teamKeyAvailability: [String!]!
}

type DraftedTeamSelection {
  pick: Int!
  selection: Draftee!
}

type DraftedTeam {
  draftTeam: DraftTeam!
  sponsor: Draftee
  selected: [DraftedTeamSelection!]
  toBeSlotted: [Draftee!]
}

type DraftState @model @key(fields: ["id", "pick"]) {
  id: ID!
  pick: Int!
  previousSelection: DraftStateSelection
  draftedPlayers: [DraftedPlayer!]!
  draftedTeams: [DraftedTeam!]!
}

**Comment by attilah** [comment]
@dkhunt27 the issue you're seeing is by-design as you are modeling connections between `@model` and `non-model` type which is not supported for nested types. `@model` only supported on top-level types as they're persisted as separate entities in their own storage.

If `DraftedPlayer` would have a model its generated input type would still not have a `draftee` property but an `id` field that references the other side of the `@connection`. I think that your `DrafeState` type is a many-to-many connection type between teams and players, look at the documentation about how to model this kind of connection: https://docs.amplify.aws/cli/graphql-transformer/directives#connection

It is a modeling problem not a code problem in this case, but I bring this scenario to the team and get back if we've something to share about this particular scenario.

I'm closing the issue, feel free to reopen it if something new comes up or open a new issue.

With the modeling question I'd suggest to visit our [discord](https://discord.gg/amplify) community where community members can help you better.

**Comment by dkhunt27** [comment]
@attilah thanks for the feedback
