### ISSUE TITLE
Subscription events are no longer being received

### ISSUE THREAD

**Issue by cjsedwards** [aws-amplify/amplify-cli#4601]
**Describe the bug**
I have a subscription defined in amplify graphql, and being subscribed in Vue. The subscription events were being received, but recently stopped working.

**Amplify CLI Version**
4.21.3

**To Reproduce**
Here is part of the definition:
```
type Mutation {
  addMessage(channelID: ID!, content: String!): ID @function(name: "orchestraBackend-${env}") @auth(rules: [{allow: private, provider: userPools}])
}

type Subscription {
  onNewMessage(channelID: ID!): ID @aws_subscribe(mutations: ["addMessage"])
}
```

**Comment by cjmartin** [comment]
I'm seeing the same issue on multiple (AppSync) projects, all managed by Amplify. One of them is in active development but I'm also seeing failed subscriptions on older projects that haven't been touched in months.

**Comment by SwaySway** [comment]
A few questions here
- Are you seeing any errors when you try to run the subscription? 
- Are you using Amplify Lib or are you running these subscriptions from the console?

There is another issue on subscriptions not triggering we are tracking. We'd like to dive into this more and see they might be related. https://github.com/aws-amplify/amplify-cli/issues/4462

**Comment by cjsedwards** [comment]
Hi @SwaySway , thanks for looking into this.  

I'm using the Amplify libraries.  I get back a subscription objection successfully with no errors.

**Comment by attilah** [comment]
I talked with the service team and there was a temporary issue with subscriptions that is resolved by now, please retry and if the issue persist get back to us, however the issue is not CLI related but we can help by asking the team in these situations. Another forum could be to ask in our community on discord at: https://discord.gg/amplify

**Comment by cjsedwards** [comment]
@attilah Can you tell me more about the cause of the issue?  The subscription issue has not resolved on my end.  Some of my subscriptions are working, but the one I specified in this issue is not.

**Comment by cjsedwards** [comment]
@brene This issue is still happening, can we reopen this please?

**Comment by brene** [comment]
Cc @attilah @UnleashedMind

**Comment by brene** [comment]
Hi @cjsedwards - I've been chatting with the AppSync PM. They were aware of an issue and it was fixed on June 18 at 8:50 UTC+2. Can you create a support ticket for the AWS AppSync team? That way they can pursue this issue further.

**Comment by cjsedwards** [comment]
@brene Where do I do that? I don't see an AppSync github repo or a way to submit issues to them.

**Comment by brene** [comment]
You can do so in the AWS console. Let me know if you have any other questions around this.
![image](https://user-images.githubusercontent.com/4989523/85166157-bc39ff00-b21b-11ea-9820-ebda95f70e77.png)

**Comment by yuth** [comment]
@cjsedwards when the subscription is triggered, can you see the `start` and `start_ack` message in websocket? You can find this in Network tab of Developer tools
![Screen Shot 2020-07-02 at 2 14 20 PM](https://user-images.githubusercontent.com/511386/86409737-55323680-bc6e-11ea-978a-654a3a23d485.png)

**Comment by cjsedwards** [comment]
Ok yes I am seeing this, I sent a message as well test test it out, and I didn't receive anything after the start_ack.
![image](https://user-images.githubusercontent.com/6901289/86410237-aabf1100-bc77-11ea-8fb2-a4bd8f554353.png)

**Comment by cjsedwards** [comment]
And I can confirm that I did send a message with the same channelID, here is the request I sent:
![image](https://user-images.githubusercontent.com/6901289/86410401-f671ba80-bc77-11ea-85ea-142c9523d2c1.png)

**Comment by yuth** [comment]
@cjsedwards would it be possible to share your schema. The part I am specifically interested in is the graphql transformers output schema (which is located in `<project-root>/amplify/backend/api/<api-name>/build/scheam.graphql`) the subscription type. I am wondering if the `onNewMessage` subscription has `@aws_subscribe(mutation:["addMutation"])`

**Comment by cjsedwards** [comment]
@yuth 
![image](https://user-images.githubusercontent.com/6901289/86415334-f5468a80-bc83-11ea-9099-0ac5298dc6fa.png)

**Comment by yuth** [comment]
I see the subscription is wired correctly, and websocket connection for subscription is open and subscription has started. I am not sure why messages are not delivered to this subscription. I will ask the service team to help us diagnose this further.

**Comment by yuth** [comment]
@cjsedwards Do you have multiple subscriptions running at the same time? For instance one of the sub has `channelId` as parameter and others don't have it

**Comment by cjsedwards** [comment]
Yes, my Vue app has a subscription to onCreateUnreadMessageCount, onUpdateUnreadMessageCount, and onDeleteUnreadMessageCount that are running at the same time.

**Comment by yuth** [comment]
@cjsedwards could you share the query used for the subscription and the mutation that used to trigger the subscription

**Comment by cjsedwards** [comment]
Subscription:
{"query":"subscription OnNewMessage($channelID: ID!) {  onNewMessage(channelID: $channelID)}","variables":{"channelID":"3f84f782-ab68-4135-9dc3-8041589d621b"}}

Mutation:
{"query":"  mutation AddMessage($channelID: ID!, $content: String!) {   addMessage(channelID: $channelID, content: $content)  }","variables":{"channelID":"3f84f782-ab68-4135-9dc3-8041589d621b","content":"Test message"}}

**Comment by yuth** [comment]
@cjsedwards In your mutation I don't see selection set containing `channelID`. Subscriptions do work based on your mutation selection set. Subscription filtering happens  based on the data sent by mutation and in the above mutation there is no `channelID` no subscription event will be sent.

Could you try running this again with the following mutation and see if you get an subscription message
```js
{
    "query": `mutation AddMessage($channelID: ID!, $content: String!) {
  addMessage(channelID: $channelID, content: $content) {
    channelID
  }
}
`,
    "variables": {
        "channelID": "3f84f782-ab68-4135-9dc3-8041589d621b",
        "content": "Test message"
    }
}
```

**Comment by cjsedwards** [comment]
@yuth I can't do this, because the mutation returns an ID rather than a message:
addMessage(channelID: ID!, content: String!): ID @function(name: "orchestraBackend-${env}") @auth(rules: [{allow: private, provider: userPools}])

The reason I have done this is that I've had to lock down the read access to the Message type, so I have a separate query that calls lambda to read messages.

The mutation does return the ID currently without it being specified in the mtuation.

**Comment by cjsedwards** [comment]
I'm trying to wrap the scalar into a type, and see if that'll fix the issue.

**Comment by cjsedwards** [comment]
@yuth 
That did not fix it, here is the mutation and subscription now:
"mutation AddMessage($channelID: ID!, $content: String!) { addMessage(channelID: $channelID, content: $content) { messageID  }}"

 "{"query":"subscription OnNewMessage($channelID: ID!) {onNewMessage(channelID: $channelID) { messageID  }}","variables":{"channelID":"3f84f782-ab68-4135-9dc3-8041589d621b"}}"

**Comment by yuth** [comment]
@cjsedwards, AppSync subscription does not fetch data from the data source itself, but rather depends on the data that is sent from the mutation. From what I can see, the mutation selection set just has `messageID` and the subscription filtering is happening based on `channelID`. The subscription engine will not fire subscription, because `addMessage` mutation does not send any `channelID` to subscription engine, and the subscription engine has no way to figure out to which channel a message was sent. 

You can read more about how Subscription works on AppSync [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html). I would like to quote a section from the documentation (with my emphasis)

> If you use the pure WebSockets client, selection set filtering is done per client, as each client can define its own selection set. In this case, the subscription selection set must be a subset of the mutation selection set. For example, a subscription addedPost{author title} linked to the mutation addPost(...){id author title url version} receives only the author and title of the post. It does not receive the other fields. However, _if the mutation lacked the author in its selection set, the subscriber would get a null value for the author field (or an error in case the author field is defined as required/not-null in the schema)_.

**Comment by cjsedwards** [comment]
@yuth thank you, I misunderstood and thought the subscription was filtering on the arguments being passed in.

I will add channelID to my output object, and see if that resolves the issue.  I appreciate the help with this!

**Comment by cjsedwards** [comment]
@yuth It's working now, thanks very much!
