### ISSUE TITLE
GraphQL API Schema on push: 'Object type extension 'Mutation' cannot redeclare field createConversation'

### ISSUE THREAD

**Issue by infosharkio** [aws-amplify/amplify-cli#461]
Issues with the schema when using amplify create api (GraphQL).
After 'amplify push', I get the error:
'Object type extension 'Mutation' cannot redeclare field createConversation'

Example schema taken from: [https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular](url)

I've added @model annotation to User, UserConversations, Message, Conversation

```
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Conversation @model {
  createdAt: String
  id: ID!
  messages(after: String, first: Int): MessageConnection
  name: String!
}

type Message @model {
  author: User
  content: String!
  conversationId: ID!
  createdAt: String
  id: ID!
  isSent: Boolean
  recipient: User
  sender: String
}

type MessageConnection {
  messages: [Message]
  nextToken: String
}

type Mutation {
  createConversation(createdAt: String, id: ID!, name: String!): Conversation
  createMessage(content: String, conversationId: ID!, createdAt: String!, id: ID!): Message
  createUser(username: String!): User
  createUserConversations(conversationId: ID!, userId: ID!): UserConversations
}

type Query {
  allMessage(after: String, conversationId: ID!, first: Int): [Message]
  allMessageConnection(after: String, conversationId: ID!, first: Int): MessageConnection
  allMessageFrom(after: String, conversationId: ID!, first: Int, sender: String!): [Message]
  allUser(after: String, first: Int): [User]
  me: User
}

type Subscription {
  subscribeToNewMessage(conversationId: ID!): Message @aws_subscribe(mutations: ["createMessage"])
  subscribeToNewUCs(userId: ID!): UserConversations @aws_subscribe(mutations: ["createUserConversations"])
  subscribeToNewUsers: User @aws_subscribe(mutations: ["createUser"])
}

type User @model {
  cognitoId: ID!
  conversations(after: String, first: Int): UserConverstationsConnection
  id: ID!
  messages(after: String, first: Int): MessageConnection
  username: String!
  registered: Boolean
}

type UserConversations @model {
  associated: [UserConversations]
  conversation: Conversation
  conversationId: ID!
  user: User
  userId: ID!
}

type UserConverstationsConnection {
  nextToken: String
  userConversations: [UserConversations]
}
```

**Comment by warrenmcquinn** [comment]
Doesn't the `@model` directive already generate the `createConversation` mutation?

https://aws-amplify.github.io/docs/cli/graphql#generates

**Comment by infosharkio** [comment]
Right- I noticed they generate the mutations.

So I've removed the Mutation type from my schema because I don't have anything else to put in it yet.

Now when doing an 'amplify push', I get:

`CREATE_FAILED      DeleteUserConversationsResolver                   AWS::AppSync::Resolver     Fri Nov 16 2018 14:58:02 GMT-0500 (Eastern Standard Time) Type Mutation not found (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: ec3ac73f-e9d9-11e8-aec5-173c10065b32`

**Comment by mikeparisstuff** [comment]
@infosharkio Can you please provide your updated schema so I can help debug?

**Comment by kaustavghosh06** [comment]
@infosharkio Are you still blocked?

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of issue creator response. Please feel free to re-open if this issue still exists.

**Comment by zeitoune** [comment]
Hi, 
I am facing the same issue as @infosharkio.
Basically, I was managing my schema in the AWS appsync console.
I wanted to add elasticsearch, adding @model @searchable to one of my types in my schema.graphql.
When I do amplify push I get an error message.

# Object type extension 'Query' cannot redeclare field listProducts

Adding the @model afterwards is causing the issue.
How can I solve this ?
Thanks for your help !
