### ISSUE TITLE
GraphQLSchema: NoSuchKey / The specified key does not exist.

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#4612]
**Describe the bug**
Push in latest update 4.21.4 does not work for me:

`amplify push` fails with odd error messages:

```
UPDATE_FAILED               GraphQLSchema
AWS::AppSync::GraphQLSchema Fri Jun 19 2020 16:21:23 GMT+1200 (New Zealand Standard Time)
The specified key does not exist.
(Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: E236F3C36A8F008C; S3 Extended Request ID: sYqzOjHDdjjatnRJzSHkRAaynqn7VbOOEsWbflblgyu/vvdjCsQIk9DsKcxRU6sSk99Syj/uxto=)
```

**Amplify CLI Version**
4.21.4

**To Reproduce**
Seems to be 100% reproducible: go to 4.21.4 and it fails, back to 4.21.3 and it works.

**Expected behavior**
Push working as usual.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node Version: v12.18.0

**Additional context**
Rollback to 4.21.3 and everything works.

**Comment by SwaySway** [comment]
@berenddeboer 
A few questions here
- Was the command `amplify push --force` or `amplify push --yes`?
- Was an update needed before doing the push?
- What were the steps taken that lead up to this error?

**Comment by attilah** [comment]
@berenddeboer thanks for reporting the issue for your case an `amplify push --force` will provide a workaround to unblock you.

In the meanwhile stay on .3, the recent fix for hashing has a regression which is causing this failure.

**Comment by SwaySway** [comment]
Closing this issue as we have deprecated version 4.21.4 due issues with `@key`. Should you experience any issues related to this in the latest version, as of now v4.21.3. Please comment below.

**Comment by IsaacTrevino** [comment]
This issue thread seems more appropriate for my last comment:
https://github.com/aws-amplify/amplify-cli/issues/4232#issuecomment-646690031

One work around I found in v4.21.4 was push an update for both api and storage, which succeeded. For instance I added a space on schema.graphql and modified the storage with group user r/w privileges.

off topic:
fyi complex objects(images, files , etc..) only works when you enable both Auth & User Groups, gives me 'access denied' when using Auth Users only.

**Comment by dylan-westbury** [comment]
Hi @SwaySway 

Our CI/CD (appcenter) process for react native fails occasionally, our pre-build script calls `npm install -g @aws-amplify/cli` and does an amplify push. We eventually resolve by hacking at the schema file and force pushing. 

Here is an example of error with request ID if helps.

Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 3A188FA775B43D4F; S3 Extended Request ID: f5Xj2Bp7+fn4CIVmA+XPWp2e0JGj2l2ZyDI9/kZnTIu78+DDZ5D/x2gwvOxroZJvEIYASmWFXfs=; Proxy: null)
