### ISSUE TITLE
Validation error of type VariableTypeMismatch: Variable type 'String' doesn't match expected type 'String!'

### ISSUE THREAD

**Issue by josh-tncarry** [aws-amplify/amplify-cli#4617]
**Describe the bug**
When building my project using the CLI version `4.21.4` there are breaking changes introduced into the compiled GraphQL schema. Parameters to queries based on a GSI that were previously not designated as required `!` are now designated as required.

While the auto-generated queries will be updated, this will cause any user generated queries to fail if they are not updated.

**Amplify CLI Version**
4.21.4

**To Reproduce**
Create a simple `@model` in the graphql schema file with an additional `@key` with a specified top level query.

```graphql
type Quiz
  @model
  @key(
    name: "ByCourseId"
    fields: ["courseId"]
    queryField: "quizesByCourseId"
  ) {
  id: ID!
  courseId: ID
}
```

Run the `amplify api gql-compile && amplify codegen` commands

Using the CLI version `<= 4.21.3` will produce a compiled graphql query that looks like this:

`quizesByCourseId(courseId: ID, ...`

And a autogenerated query that looks like this:

```javascript
export const quizesByCourseId = /* GraphQL */ `
  query QuizesByCourseId(
    $courseId: ID
```

Whereas using the CLI version `4.21.4` will produce a compiled graphql query that looks like this:

`quizesByCourseId(courseId: ID!, ...`

And an autogenerated query that looks like this:

```javascript
export const quizesByCourseId = /* GraphQL */ `
  query QuizesByCourseId(
    $courseId: ID!
```

**Expected behavior**
While this may in fact be the "correct" way to compile this, it *is* a breaking change. If someone were to deploy this to a shared backend without also updating the corresponding queries the impact to production could be pretty severe.

This is not a patch fix, or even a minor update, but a change that will result in breakages. People will need to appropriately plan for an update like this to ensure it does not cause problems.

**Desktop (please complete the following information):**
 - Irrelevant. This is behavior intrinsic to the CLI and not dependent on OS.

**Additional context**
I found out about this because I have my Amplify Console set to use the latest CLI. The front-end compilation failed, but the back-end had already been deployed causing previously working queries to start failing.

**Comment by egyangel** [comment]
Same problem here

**Comment by attilah** [comment]
@josh-tncarry @egyangel we had fixes around `@key` that made it constrained as in your `@key` definition `courseId` is the partition key, hence it is mandatory.

I'm taking it to the team for triage to get the best way to resolve it.

**Comment by dasearle** [comment]
Same issue, has broken the API for me

**Comment by jane-clickfrenzy** [comment]
Same issue here, any updates? Thanks.

**Comment by SwaySway** [comment]
Closing this issue as we have deprecated version 4.21.4 due issues with @key. Should you experience any issues related to this in the latest version, as of now v4.25.0, please comment below.
