### ISSUE TITLE
Better handling of id fields in GraphQL API

### ISSUE THREAD

**Issue by sudeep-quantelai** [aws-amplify/amplify-cli#4619]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
It is an annoyance that a field that is a required field of type 'Id' has always to be passed in a create mutation when I want the field to be populated with a UUID. 

**Describe the solution you'd like**
It looks like if you want an id field to be populated with UUID then that field can only be called 'id'. I want to name my id fields and not have to pass it in and have it be populated with a UUID if I dont pass in a value and use the value I pass in if I do pass it in. This is how DBs work for autoid fields

**Describe alternatives you've considered**
Right now I have to override the velocity template in order to do the same.

**Comment by attilah** [comment]
@sudeep-quantelai which version of the CLI you're using? because we had fixes around automatically assigning values to `id` fields.

**Comment by sudeep-quantelai** [comment]
4.18.1

**Comment by attilah** [comment]
@sudeep-quantelai update to the latest version and compile your schema with `amplify api gql-compile` and see if the changes we made since that version will work as you expected, as we had fixes with auto assignment of `id` fields after 4.18.1.

**Comment by sudeep-quantelai** [comment]
Thanks for the feedback. Can you please point me to the specs of that implementation so I have a better idea of how it is implemented?

**Comment by ammarkarachi** [comment]
Hi @sudeep-quantelai,

You could refer to the [Changelog](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-dynamodb-transformer/CHANGELOG.md)
