### ISSUE TITLE
Error on push with Python Lambda function

### ISSUE THREAD

**Issue by dave-moser** [aws-amplify/amplify-cli#4621]
**Describe the bug**
After adding a Python Lambda function to my Amplify project and attempting to push, I receive a UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

This causes the push to exit with failure.

**Amplify CLI Version**
4.21.4

**To Reproduce**
- amplify add function
- select Python and generate the function
- amplify push

**Expected behavior**
Push should complete without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/54151448/85177901-f7472d00-b231-11ea-93fa-259b74b0ecc3.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.14.1

**Additional context**
If I manually set an environment variable: PIPENV_VERBOSITY=-1 I am able to run the push successfully.

**Comment by SwaySway** [comment]
Closing this as the fix has been merged and will be included in the next release after v4.24,
