### ISSUE TITLE
Table:StreamArn cannot be updated as it is in use by SearchableStack

### ISSUE THREAD

**Issue by ArshAulakh59** [aws-amplify/amplify-cli#4624]
**Describe the bug**
Same as #4054. 
Since it is closed I'm opening it as a new issue.

**Amplify CLI Version**
4.21.4

**To Reproduce**
Changed environment from 'development' to 'production'. Now cannot push changes to cloud.

**Expected behavior**
Should be able to push the changes to cloud.

**Error log**
```
UPDATE_ROLLBACK_IN_PROGRESS upgamegolf-prod-20191128172603-apiupgamegolf-165EM35DLQIN7-User-1PL1YHEZCEHG9 AWS::CloudFormation::Stack Sat Jun 20 2020 20:38:31 GMT+0530 (India Standard Time) Export mbkujtcs7nfkvhrzih2nhg5ani:GetAtt:UserTable:StreamArn cannot be updated as it is in use by upgamegolf-prod-20191128172603-apiupgamegolf-165EM35DLQIN7-SearchableStack-1MMY49OEZ5XG2
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Comment by ArshAulakh59** [comment]
Thanks for the great tool Amplify team 😄

Just wanted to see if there were any updates on a permanent fix for this? I've missed a pretty important deadline trying to get this to work 😞

**Comment by ArshAulakh59** [comment]
Just to communicate the severity of the issue, this is blocking me from pushing my changes from development to production hence causing delays in closing sales of the product.
If I could get a temporary workaround if a permanent fix is not available yet, that would work for now as well. Thanks. 😊

**Comment by akshbhu** [comment]
Hi @ArshAulakh59 

For the workaround you can take a look at previous comment : https://github.com/aws-amplify/amplify-cli/issues/4054#issuecomment-647618153.
Let me know if this works for you.

 We are actively working towards such issues so that customers do not have to face such unexpected situations.

**Comment by ArshAulakh59** [comment]
Hi @akshbhu thanks for the response. I tried the workaround and other comments but nothing worked. Had to delete my entire api category from amplify and create anew. This caused about 2 days downtime for my product 😞.

**Comment by ArshAulakh59** [comment]
Open to discuss details if needed to help resolve the issue.

**Comment by jhockett** [comment]
Hi @ArshAulakh59 did you make any changes outside of the CLI commands before the error occurred? Such as manual cloudformation edits or changes in the console.
