### ISSUE TITLE
spawn does not work on Windows. Please use cross-spawn.

### ISSUE THREAD

**Issue by CharlesStover** [aws-amplify/amplify-cli#4626]
I'm using a Windows machine and Yarn2 as a package manager.

`amplify serve` crashes with `spawn yarn ENOENT` when my `StartCommand` is set to `yarn start`.

**As a workaround, Windows developers can change the `StartCommand` to `yarn.cmd start`.**

Instead of `spawn`, please use the [cross-spawn](https://www.npmjs.com/package/cross-spawn) package for supporting both Windows and Linux environments.

**Comment by akshbhu** [comment]
Hi @CharlesStover 

Thanks for reporting this issue, we'll look into it.

**Comment by CharlesStover** [comment]
I'm not as fluent in the Amplify source code, but it looks like these may be the problematic lines that need to migrate from `{ spawn } from 'child-process' to `{ spawn  } from 'cross-spawn'`.

- Start: https://github.com/aws-amplify/amplify-cli/blob/25c53ce81a74c3f706f60b0519eda0a4338edbf7/packages/amplify-frontend-javascript/lib/server.js#L18
- Build: https://github.com/aws-amplify/amplify-cli/blob/25c53ce81a74c3f706f60b0519eda0a4338edbf7/packages/amplify-frontend-javascript/lib/builder.js#L18
