### ISSUE TITLE
migrating schema to to @key directive

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#4634]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

API

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.21.3

**What AWS Services are you utilizing?**

Api
Cognito
Storage

**Provide additional details e.g. code snippets**
Hi!
I'm trying to migrate my schemas to the new directives specification documented in:
https://docs.amplify.aws/cli/graphql-transformer/directives#key

I have a couple of projects that used the connections just with names.

I didn't found any guide on how to migrate... Is there a way to migrate this schemas?

The only solution I found so far is to remove the old api (amplify remove api command) and then create a new one with the keys directives.  This approach is not useful when data migration is required.

By the way, any recommendation on how to export/import data into dynamodb is also appreciated.

**Comment by akshbhu** [comment]
Hi @sergiorodriguez82 

There is no existing documentation for this. Can you tell us you specific usecase you want to achieve with this so that we can answer based on that?

**Comment by sergiorodriguez82** [comment]
> Hi @sergiorodriguez82
> 
> There is no existing documentation for this. Can you tell us you specific usecase you want to achieve with this so that we can answer based on that?

Sure, here is what my entity right now:
```

type Participant
  @model
  @versioned
 {
  id: ID!
  state: EntityState!
  idType: String!
  idNumber: String!
  dob: String!
  name: String!
  ...
  company: Company! @connection(name: "companyParticipants")

}

```

This is what the update I want to make to the model.

```
type Participant
  @model 
  @versioned
  @key(name: "byCompany", fields: ["companyID", "idNumber"], queryField:"participantsByCompany")
{
  id: ID!
  state: EntityState!
  idType: String!
  idNumber: String!
  dob: String!
  name: String!
 ...
  companyID: ID!
  company: Company! @connection(fields: ["companyID"])  
}
```

When this change made the schema stop compiling.

**Comment by yuth** [comment]
@sergiorodriguez82 
> When this change made the schema stop compiling.

Do you get any errors when this happens or is it just connection is not working as expected?

When you add a connection with name, the `@connection` transformer adds a new field with name `<oneSide><manySide>Id` which in your case is in `Participant` table with field named `participantCompanyId`. So if you want to move the above schema, to `@connection` with `fields` then you can do this

```graphql
# Old schema with connection name
type Participant @model {
  id: ID!
  state: EntityState!
  idType: String!
  idNumber: String!
  dob: String!
  name: String!
  company: Company! @connection(name: "companyParticipants")
}

type Company @model {
  id: ID!
  name: String!
  participants: [Participant] @connection(name: "companyParticipants")
}
```

```graphql
#new schema with @connection and fields
type Participant
  @model
  @versioned
  @key(
    name: "byCompany"
    fields: ["participantCompanyId"]
    queryField: "participantsByCompany"
  ) {
  id: ID!
  state: EntityState!
  idType: String!
  idNumber: String!
  dob: String!
  name: String!
  # companyID: ID!
  participantCompanyId: ID!
  company: Company! @connection(fields: ["participantCompanyId"])
}

type Company @model {
  id: ID!
  name: String!
  participants: [Participant] @connection(fields: ["id"], keyName: "byCompany")
}


```

**Comment by sergiorodriguez82** [comment]
Thanks!
