### ISSUE TITLE
DataStore owner + IAM auth rule combination not working

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-cli#4638]
**Which Category is your question related to?**
- DataStore
- `@auth` directive

**Amplify CLI Version** 
4.21.3

**Provide additional details e.g. code snippets**
Hey @undefobj, you stated [here](https://github.com/aws-amplify/amplify-cli/issues/1678#issuecomment-505039534) that using a User Pool user inside a Lambda to call the AppSync API is bad practice, and though I agree, I am unable to make the IAM auth rule work in conjunction with the owner rule on the DataStore.

This is my GraphQL schema:
```graphql
type SharedContent
  @model
  @auth(rules: [
    { allow: owner },
    { allow: private, provider: iam }
  ])
{
  id: ID!
  content: String
  owner: String
}
```
It generates the following subscriptions:
```graphql
onCreateSharedContent(owner: String!): SharedContent @aws_subscribe(mutations: ["createSharedContent"]) @aws_iam @aws_cognito_user_pools
onUpdateSharedContent(owner: String!): SharedContent @aws_subscribe(mutations: ["updateSharedContent"]) @aws_iam @aws_cognito_user_pools
onDeleteSharedContent(owner: String!): SharedContent @aws_subscribe(mutations: ["deleteSharedContent"]) @aws_iam @aws_cognito_user_pools
```
And results in the following warnings/errors:
```
[WARN] 26:54.58 DataStore - Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onDeleteSharedContent'"}]}
[WARN] 26:54.97 DataStore - Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateSharedContent'"}]}
[WARN] 26:54.156 DataStore - Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onUpdateSharedContent'"}]}
```

I've posted about it [here](https://github.com/aws-amplify/amplify-js/issues/6108#issuecomment-647708908) as well. The only way I can currently keep all subscriptions working, and have the capability to run mutations from my Lambda is by using [Schema 5](https://github.com/aws-amplify/amplify-js/issues/6108#schema-5) from my examples, and logging in as a User Pool user that is part of the Admin group inside the Lambda. The Lambda is created using `amplify function add` and has proper access.

**Comment by SwaySway** [comment]
Closing this issue as the related PR was merged.
