### ISSUE TITLE
 @key on not-required fields

### ISSUE THREAD

**Issue by kaustavghosh06** [aws-amplify/amplify-cli#4642]
**Describe the bug**
Following is my annotated GraphQL schema
```graphql
type Todo @model 
@key(name: "byName", fields: ["name", "description"], queryField: "byNameDescription") {
  id: ID!
  name: String!
  description: String
}
```
Step 1: I create a todo item with just the `name` as input in the mutation. 
Step 2: Run the following query:
```graphql
query GetByName {
  byNameDescription(name: "<same-name-used-in-mutation-above>") {
    items {
      id
      name
    }
  }
}
```
_**The above query returns an empty list**_

The reason for this is that we index "name" with "description" as the sort key and in my create mutation I'm  able to create the record just with a `name` since `description` is not required but the record is not indexed in the `byName` GSI since the `description` field is not required - resulting in the query returning empty results.

**Expected behavior**
There could be two things which could potentially happen:
1) Validation check pre-push to see if there's a not-required field used with @key to either warn or disallow the user to push 
2) Logic in resolvers to add null values to not-required fields if those fields are not passed as inputs in the mutation

**Amplify CLI Version**
4.21.3

**Comment by akshbhu** [comment]
Hi @kaustavghosh06 

I am able to reproduce this bug.Thanks for reporting this.
