### ISSUE TITLE
Newly added function cannot be pushed

### ISSUE THREAD

**Issue by dubchoi** [aws-amplify/amplify-cli#4643]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Add a new function via `amplify function add` in an existing project.
Push fails with followingg error:

UPDATE_FAILED      <my auth resource id> AWS::CloudFormation::Stack Mon Jun 22 2020 20:11:19 GMT-0700 (Pacific Daylight Time) Parameters: [userPoolGroupList, adminQueries, permissions, resourceNameTruncated, userPoolGroups, dependsOn, parentStack, triggers] must have values

**Amplify CLI Version**
4.21.3

**To Reproduce**
Not sure how I got into this state.
I've tried running amplify env pull --restore

**Comment by akshbhu** [comment]
Hi @dubchoi 

From the error it seems the parameters are not defined in the CFN file. 

To easily reproduce: 
1) Can you upload your CFN file which is giving this error on push?
2) Can you tell the steps or commands you entered which lead to this error?

**Comment by dubchoi** [comment]
Uploaded the auth cloudformation (id's scrubbed).
Please let me know if this is sufficient to debug.
I don't know exact steps that led me here, but I was having trouble pushing cognito lambda functions at first, and so had deleted/created them a few times. To my knowledge I never modified this file directly though.

[auth-cloudformation-template.yml.zip](https://github.com/aws-amplify/amplify-cli/files/4820682/auth-cloudformation-template.yml.zip)

**Comment by akshbhu** [comment]
Hi @dubchoi 

Thanks for uploading CFN file. I also need the CloudFormation file for each category might be functions in your case.You can upload those files here or if it contains sensitive information you can email it to amplify-cli@amazon.com with this issue in the subject

**Comment by dubchoi** [comment]
I fixed this by manually adding those parameters to my cloudformation configuration. Since I can't quite figure out exact steps that led me here, I'll close this.
