### ISSUE TITLE
Can I configure custom http response headers?

### ISSUE THREAD

**Issue by toritroniks** [aws-amplify/amplify-cli#4644]
**Details**
I need to set some headers to the response of some files.
I found that it is possible by using the Amplify Console (https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html)
But for specific reasons I am not using the console. I am deploying the app by using the `amplify publish` command.
Is there a way to do this with the current amplify cli? or changing some configuration?
If there isn't, this will probably turn into a feature request.

Thank you in advance.

**Amplify CLI Version** 
4.20.0

**Comment by akshbhu** [comment]
Hi @toritroniks 

I don't think we currently support this through cli. we will surely take this up into consideration for a feature request or enhancement.

**Comment by akshbhu** [comment]
hi @toritroniks 

May I know specific usecase you want to achieve?

**Comment by toritroniks** [comment]
@akshbhu 

In my case, there are mainly 2 use cases.

1. Specify the Cache-Control and Pragma response header for specific files, to avoid local browser and proxy cache.
2. Include some security headers in the response. (Specifically: `X-Frame-Options: SAMEORIGIN`)

The second one was from a security check using OWASP ZAP. It complained that the header wasn't set.

If you need any more information, just let me know.

**Comment by kaustavghosh06** [comment]
@toritroniks Did you consider modifying the generated CloudFormation files located inside the `amplify/hosting/<resource-name>` directory for this? Did you run into roadblocks while customizing the generated CloudFormation file?

**Comment by toritroniks** [comment]
Hi, @kaustavghosh06
sorry for the late response.

Correct me if I’m wrong, but I don think it’s possible to set the response headers of the files inside the S3 bucket with CloudFormation.

If there is a way, I would really appreciate some guidance!

right now the only thing I can think of is to run some script to edit the files metadata after the deploy... but it’s far from ideal.

If there is no way to set it with cloudformation, I believe this is an important enhancement!
