### ISSUE TITLE
[Bug: Android] Removing plugin via CLI doesn't clean up amplifyconfiguration.json

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-cli#4651]
**Describe the bug**
For an Amplify Android project, running `amplify remove api` *should* remove the entry from amplifyconfiguration.json, but doesn't.   I've only experienced this bug with the API category, but I imagine it is probably an issue with all categories.

**Amplify CLI Version** 
`4.21.3`

**To Reproduce**
On an existing Amplify Android project with an API added:

1. Remove the API: `amplify remove api`
2. Add a new API: `amplify add api`
3. Push changes: `amplify push`

Note, this only occurs when trying to remove and add an API at the same time.  If you run `amplify push` between step 1 and 2, this bug is not a problem.

Expected: API should not be in `app/src/main/res/raw/amplifyconfiguration.json`
Actual: API is present in `app/src/main/res/raw/amplifyconfiguration.json`

**Expected behavior**
Plugin should be removed from amplifyconfiguration.json when customer runs `amplify remove <category>`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.16.1

**Comment by akshbhu** [comment]
Hi @richardmcclellan 

Thanks for reporting this. I have reproduced this and you are correct, its happening in all categories.

**Comment by kaustavghosh06** [comment]
After removing the resource, you’d have to run amplify push to remove the resource from the cloud and that’s when the values are removed form the amplifycondogirarion.json file. Are you seeing the values even after a push?

**Comment by richardmcclellan** [comment]
I just did some more testing on this.  The issue does NOT occur with the following sequence:

```
amplify remove api
amplify push
amplify add api
amplify push
```

The issue DOES occur with this sequence:

``` 
amplify remove api
amplify add api
amplify push
```

Basically, if you try to remove/add in the same push, it doesn't clean up the old api from the `amplifyconfiguration.json`.

**Comment by jhockett** [comment]
Maybe we can make it clearer in the `amplify remove x` success message that `amplify push` is required to remove the resource in the cloud.

**Comment by richardmcclellan** [comment]
The issue is not forgetting to call `amplify push`.   The issue occurs when you try to remove AND add an API in the same `amplify push` step.  So, I suppose we add messaging so that customers do one at a time.  But I'm not sure that's any better than the current workaround, which is to simply delete the old entry from `amplifyconfiguration.json`.

**Comment by jhockett** [comment]
Sorry for not being more clear. Doing one remove at a time is also what I was getting at. 

We could also check resource status on `amplify add api` and any other relevant categories and if there is a pending removal, print a helpful error message explaining that the removal must be pushed before a new resource of that category can be created

**Comment by richardmcclellan** [comment]
> We could also check resource status on `amplify add api` and any other relevant categories and if there is a pending removal, print a helpful error message explaining that the removal must be pushed before a new resource of that category can be created

This would work!

**Comment by josefaidt** [comment]
Hey @richardmcclellan this issue should now be fixed 🙂 after removing and adding an API before `amplify push` I noticed the GraphQL API's information was updated in the `amplifyconfiguration.json` file.

Closing issue
