### ISSUE TITLE
Binary "Buffer" type data makes amplify mock server no longer responsive

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4656]
**Describe the bug**
If a function resolver returns an item with binary data (Buffer), amplify mock will hang and no longer be reachable. 

**Amplify CLI Version**
4.21.3

**To Reproduce**
Have a function resolver return an object along the lines of: 

export interface Image {
  name: String
  data: Buffer;
}

**Expected behavior**
amplify mock should show error or not return the info. The real AppSync backend handles this correctly - it will not return the data field if it is not in the graphql schema. 

**Desktop (please complete the following information):**
 - OS: OSX, node v13.2.0

**Additional context**
Obviously graphql does not support Buffer types, so I have my lambda resolver remove data before passing it to graphql, but these things shouldn't cause the mock server to just silently fail and no longer be responsive for future requests.

**Comment by akshbhu** [comment]
The fix is included in amplify-cli version 4.26.0. Let me know if you anymore issues , comment on this and I will open the issue again.
