### ISSUE TITLE
Amplify function not create API gateway trigger

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#4661]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When creating a lambda function, the api gateway trigger is not being configured.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.21.3

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Add function with amplify cli
select Serverless express function (Integration with Amazon API Gateway)
leave the generated function unchanged
then push changes

**Expected behavior**
a function with a api gateway trigger.

**Screenshots**
![image](https://user-images.githubusercontent.com/38695777/85499525-62349300-b5a7-11ea-8eba-647f93ccdb64.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

Im trying to add a push notification logic to my app. For this I have created the function to check for the notification keys.
Im having problems testing the function as there is no endpoint to test.

Thanks

**Comment by akshbhu** [comment]
Hi @sergiorodriguez82 

It seems that you haven't added api in your project. You can use ```amplify add api``` and you can select the above lambda function to attach to your api category resource.After adding api and ```amplify push``` you will get a api endpoint in aws-exports.js file

**Comment by sergiorodriguez82** [comment]
Hi, thanks for your response.
The function I added is missing the API gateway trigger, not the amplify api end point. Im not sure If I made myself clear.. Take a look at the AdminQuieries api that is also generated with amplify, this api, creates a lambda app with a api gateway and its endpoint. 
![image](https://user-images.githubusercontent.com/38695777/85603686-37355800-b616-11ea-82c6-d4569208c29b.png)

When I create this function I was expecting to have the api gateway trigger, maybe is something with the scheduled part of the function I added that the function to be called once a day.

**Comment by akshbhu** [comment]
Hi @sergiorodriguez82 

I think I understand the confusion here. Yes you are correct Admin queries lambda function also setup API gateway trigger.
I think this functionality is missing from functions when adding serverless function. I will mark this issue as bug.

For the workaround , One thing you can try out is ```amplify add api```. You can find detailed documentation [here](https://docs.amplify.aws/cli/restapi#rest-endpoint-that-triggers-new-lambda-functions).

This way also you can setup a lambda function with API gateway trigger. Either you can setup a new lambda function or you can link for old lambda function.

Let me know if this works for you?

**Comment by kaustavghosh06** [comment]
@sergiorodriguez82 I'm looking at this issue and was wondering what flow did you use? 
1) are you looking to add an APIGW in front of your scheduled function added with the amplify add function?
2) did you add an api using the add api flow to connect your function to a corresponding function? If you did that pushed, the lambda function would show up in the APIGW console and would proxy the API requests to the Lambda function.

**Comment by sergiorodriguez82** [comment]
Hi!, this was some time ago, I was creating a test api, I do not recall what was the en of this... Anyway thanks for your reply and help. If needed I will reopen!.
BR
Sergio
