### ISSUE TITLE
Unable to call a lambda function via REST 

### ISSUE THREAD

**Issue by delahayethierry** [aws-amplify/amplify-cli#4664]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Call a python backend function from the js frontend

**Amplify CLI Version**  4.21.3

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

AWS Amplify, AWS Lambda

**Provide additional details e.g. code snippets**

I am trying to make a super simple Amplify app that calls one lambda function. From what I understood here: https://github.com/aws-amplify/amplify-cli/issues/959 , it is better to use a lambda function in the same project.

I created a simple python lambda function using amplify add api. The code is the hello world for now:

def handler(event, context):
  print('received event:')
  print(event)
  return {
    'message': 'Hello from your new Amplify Python lambda!'
  }

I then try to call it from App.js:

API.configure(awsconfig);
Amplify.configure({
    API: {
        endpoints: [
            {
                name: "functionname",
                endpoint: "/functionendpoint"
            }
        ]
    }
});

async function getData() {
    try {
        const data = await API.get('functionname', '/functionendpoint', {})
        SomeDiv.innerHTML += data.message
    } catch (err) {
        console.log(err)
    }
};

I am, however, only able to get 403s (on the deployed version) or 404s (locally). I assume I am missing some parameter to tell the frontend where to find the method, but I can't figure which one.

I am pretty sure I missed something, but I couldn't find a similar issue / solution by either playing with the code or looking for similar issues.

**Comment by akshbhu** [comment]
Hi @delahayethierry 

It seems you are setting a regional endpoint. There might be some problem in ```/functionendpoint```. Amplify highly recommend to use  API gateway endpoint as described [here](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js#aws-regional-endpoints)

You cab try ```API.get(apiName, path) ``` as shown in this link [here](https://aws-amplify.github.io/amplify-js/api/classes/apiclass.html).

Let me know if that works for you?
