### ISSUE TITLE
auth update leads to `Resource is not in the state stackUpdateComplete`

### ISSUE THREAD

**Issue by tkolleh** [aws-amplify/amplify-cli#4668]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Unable to update resources error; `Resource is not in the state stackUpdateComplete`

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

`4.21.3`

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

`amplify update auth`

Update admin queries and auth resource. Remove functions for custom message, post signup confirmation, and pre-signup.

```
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected wit
h AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? Yes
? Select any user pool groups you want to delete:
? Do you want to add another User Pool Group No
✔ Sort the user pool groups in order of preference · admin, manager, associate, client
 Do you want to add an admin queries API? Yes
? Do you want to restrict access to the admin queries API to a specific Group Yes
? Select the group to restrict access with: associate
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Dashboard App Verification | code de vérification
 Please specify an email verification message: <h4 id="dashboard-app-verification">Dashboard App Verification</h4> <p>Please enter the following verification code for dashboard access.</p><pre><code>{####}</code></pre><p>Veuillez saisir le code de vérification pour l’accès au tableau de bord.</p>
 Do you want to override the default password policy for this User Pool? Yes
 Enter the minimum password length for this User Pool: 8
 Select the password character requirements for your userpool: Requires Lowercase, Requires Uppercase, Requi
res Numbers, Requires Symbols
 Specify the app's refresh token expiration period (in days): 45
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: Email, Family Name, Given Name, Phone Number
 Specify write attributes:
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
Successfully updated AdminQueries8c62bb67 function locally
Successfully updated AdminQueries API locally
Removing resource authresourceCustomMessage...
Successfully removed resource
Removing resource authresourcePostConfirmation...
Successfully removed resource
Removing resource authresourcePreSignup...
Successfully removed resource
Successfully updated resource authresource locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
```

**Expected behavior**

Resource(s) updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

OS: macOS Catalina 10.15.5 19F101 x86_64
Shell: zsh 5.7.1
Node: v12.14.1

**Additional context**

Stuck trying to update the `auth` and `function` resources.

Using amplify version `4.21.3` I intend to update `auth` and `function` resources. I continue to get `stackUpdateComplete` errors. Along with:
```
UPDATE_FAILED      authuserPoolGroups           AWS::CloudFormation::Stack Wed Jun 24 2020 13:28:23 GMT-0400 (Eastern Daylight Time) Parameters: [authauthresourceIdentityPoolId, authauthresourceAppClientID, authauthresourceAppClientIDWeb, authauthresourceUserPoolId] do not exist in the template
```
I've tried to push changes per resource such as `amplify <resource name> push` and in general with `amplify push`. Both result in the same error message `Resource is not in the state stackUpdateComplete`. What does this mean? That the cloud services state is different from my local? Seems too obvious since the point of the push is to update the state.

**Comment by tkolleh** [comment]
Any updates on this?

**Comment by ammarkarachi** [comment]
@tkolleh There should be an error `[authauthresourceIdentityPoolId, authauthresourceAppClientID, authauthresourceAppClientIDWeb, authauthresourceUserPoolId] ` why these resources weren't created earlier. Can you share the error you got?

**Comment by tkolleh** [comment]
Thanks for following up. I've moved on from this error...ended up rebuilding the project. There have been multiple releases since my post thus I wont attempt to recreate the error.

**Comment by ammarkarachi** [comment]
@tkolleh Sorry for the delay in responding back. Let us know if you are facing any other issues.
