### ISSUE TITLE
[Feedback] Add instructions to update the build output path for angular 8

### ISSUE THREAD

**Issue by cremich** [aws-amplify/amplify-cli#4669]
**Page**: [`/start/getting-started/nextsteps/q/integration/angular`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/angular)

**Feedback**:
Hey there, thanks for this tutorial. I recognized, that I have to update the build outputPath property of my angular.json config in order to get the deployment work. Otherwise the application build root will be `diet/<projectName>`

The amplify hosting mechanism expects in the default configuration the app under the root path and not in a subfolder. Therefore the initial request to the amplify hosted domain results in an error page.

**Comment by renebrandel** [comment]
I'm marking this as a bug. The expected distribution path for Angular apps when you run `amplify init` should be `dist/{project-folder-name}` and not `dist/`
