### ISSUE TITLE
[Feedback] amplify mock step fails if Java JDK is not installed

### ISSUE THREAD

**Issue by andersr** [aws-amplify/amplify-cli#4670]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

The command `amplify mock api` on the page https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#optional-test-your-api results in an error if the correct Java JDK is not installed. 
```bash
 ~ amplify mock api  
Failed to start API Mock endpoint Error: max retries hit for starting dynamodb emulator
```

In my case, this fix worked: https://github.com/aws-amplify/amplify-cli/issues/2062#issuecomment-533700476.

It might make sense to add a note regarding the Java JDK dependency for this step.

**Comment by andersr** [comment]
@akshbhu - my current version is `4.21.1` - however I am not sure if that was the version I used when posting this issue.

**Comment by akshbhu** [comment]
Hi @andersr 

We have fixed this error message  to give a warning to have java version >= 8 and error if java is not installed in previous amplify version. Can you try with current version to check if error still persists?

**Comment by janaka** [comment]
I get the following error and pop up. Running amplify-cli v4.26.0

Could find any mention of this dependency in pre-reqs etc. presume I don't actually need the JDK just the runtime. Would be good to have instructions. Not depending on Java would be even better. Java always feels clunky as a tool dependency. 

![image](https://user-images.githubusercontent.com/51779/89224760-f0e9f600-d5d0-11ea-8008-d3fbebe54852.png)

**Comment by jupitercow** [comment]
As of December 1, 2020:
`Error: Calling brew cask install is disabled! Use brew install [--cask] instead.`

> From the maintainer:
> ...
> brew cask commands were deprecated on 2020-12-01 with the release of Homebrew 2.6.0.

([https://news.ycombinator.com/item?id=25528475](https://news.ycombinator.com/item?id=25528475))

Use:
`brew install --cask oracle-jdk`

amplify --version: 4.40.1

**Comment by akshbhu** [comment]
Hi @janaka 

Yes Installing JRE will work fine. Here we are checking for java version >= 8 as it is a requirement for DynamoDB local which we are using to mock api.

Closing this issue as it seems to be solved. If you are still stuck after upgrading java version , feel free to comment and Ill reopen this issue again

**Comment by chinna2580** [comment]
unable to start the serverless.
 still gets the following error:
 Serverless: ERROR: Error: max retries hit for starting dynamodb emulator

i have the following java version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

lsof already installed
