### ISSUE TITLE
Lambda Trigger for DynamoDB Stream doesn't work out of the box

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-cli#4671]
**Describe the bug**
On a project with a GraphQL API, create a function triggered on a DynamoDB Stream. Request access to your storage in read.
Push that new function.
You get a CloudFormation Error.
 
`CREATE_FAILED      functionUpdateEmailPicture AWS::CloudFormation::Stack Wed Jun 24 2020 21:55:35 GMT+0200 (Central European Summer Time) Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs`

**Amplify CLI Version**
4.21.3

**To Reproduce**
````
amplify function add
Lambda Trigger
Amazon DynamoDB stream
Use API category graphql @model backed DynamoDB table(s) in the current Amplify project 
Select a model
Do you need access to other resources ? Yes
storage
bucket
````

You get a cloud formation template file generated. Pay attention to the usages of "Fn::ImportValue". The one giving read access to the bucket is not valid.

**Expected behavior**
I expect that function to be pushable out of the box and to comply with Cloud Formation template rules.

**Desktop (please complete the following information):**
 - OS: MacOS X Catalina
 - Node Version. v14.4.0

**Additional context**
I can't find anything on the docs about those ${xxx} vars in the Amplify documentation, which doesn't helps for debugging

**Comment by maximelebastard** [comment]
Can anyone give me what the CLI is supposed to generate so that I can fix that issue manually ?

**Comment by akshbhu** [comment]
Hi @maximelebastard 

Thanks for the patience. I reproduce the issue based on your steps described above. I have a question

Is the issue occurring when importing ```graphqlAPID``` output or the one you said above giving access to bucket?

**Comment by maximelebastard** [comment]
Hey @akshbhu thanks for analyzing my ticket. Glad you were able to reproduce.
It's the graphqlAPIID that were used in ImportValue in order to recreate the ARN of the Dynamo table.

**Comment by akshbhu** [comment]
hi @maximelebastard 

The error is coming because ```apiYouresourceNameGraphQLAPIIdOutput``` is missing from CFN template.
For the workaround you can do ```amplify update function``` and choose api in the list to grant your function permission to your API . This will set the parameters in the CFN file.

Let me know if that works for you?

**Comment by markjoachim** [comment]
Same error appears if the (other) access is granted to another function.

? Provide a friendly name for your resource to be used as a label for this category in the project: **function1**
? Provide the AWS Lambda function name: **function1**
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: Lambda trigger
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream
? Choose a DynamoDB event source option Use API category graphql @model backed DynamoDB table(s) in the current Amplify project
Selected resource loyaltyRoverAPI
? Choose the graphql @model(s) **modelType**
? Do you want to access other resources created in this project from your Lambda function? Yes
? Select the category function
? Function has 7 resources in this project. Select the one you would like your Lambda to access **function2**
? Select the operations you want to permit for **function2** read

You can access the following resource attributes as environment variables from your Lambda function
        ENV
        FUNCTION_AADEPARTURE_NAME
        REGION
? Do you want to invoke this function on a recurring schedule? No
? Do you want to edit the local lambda function now? Yes

CREATE_FAILED               function**function1**                AWS::CloudFormation::Stack Fri Jul 03 2020 14:16:26 GMT+0200 (Central European Summer Time) Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs

**Comment by UnleashedMind** [comment]
@maximelebastard 
Are you still having the issue? I used the latest version of the CLI (4.26.0) and I was not able to reproduce it. 
Please check and confirm.
