### ISSUE TITLE
@Auth can't remove read access for specific fields of a model

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#4674]
**Which Category is your question related to?**
AppSync

**Amplify CLI Version** 
4.21.1

**What AWS Services are you utilizing?**
Cognito, Appsync, Pinpoint, Lambda

I have a User model in my graphql schema and am having auth issues. I want some fields (like username and name) to be accessible to other users but other fields (like email) not to be. I initially added an `@auth` header to the model for `{ allow: private, operations: [read]}` thinking I could add individual lines for the fields I want to hide like `{ allow: private, operations: []}`, but unfortunately that doesn't work because you have to specify an operation and I'm trying to remove all operations. The other option is to leave out the auth header from the model and define `{ allow: private, operations: [read]}` for the lines I want to be accessible to other users, but if you leave the header from the model then you can't retrieve user properties through other models and you can't list users anymore. For example If I want to get the username of a Post's author, I can no longer query the user through the user connection of the post. Essentially either all of the fields have to be accessible or none of them.

Are there any work arounds or functionality I'm missing? Or can this be taken as a feature request? I think this is really crucial to security for apps built on Amplify. Thanks!

**Comment by akshbhu** [comment]
Hi @julien-tamade 

you can also post this question on amplify discord community for quick answer :  https://discord.com/invite/jWVbPfC and Other users working on same usecase will reply on that.

**Comment by ammarkarachi** [comment]
Hi @julien-tamade ,
As an example below you could create an explicit rule to restrict access to a certain group by defining a field level auth. You can find documentation for you reference [here](https://docs.amplify.aws/cli/graphql-transformer/directives#field-level-authorization)
```graphql
type Todo
  @model
{
  id: ID! @auth(rules: [{ allow: private, operations: [read]}])
  owner: String @auth(rules: [{ allow: private, operations: [read]}])
  email: String! @auth(rules: [{ allow: groups, groups: ["ForbiddenGroup"], operations: [] }])
}
```

**Comment by julien-tamade** [comment]
The issue I'm experiencing is that I need to be able to allow general access to the model for private but remove access for everybody to specific items. If I don't declare general access then I can't query this model through another model. For instance getting a user's username when querying a post. So i add [{ allow: private, operations: [read]}] to the whole model, but then I'm trying to figure out to remove that read access for private users because [] doesn't seem to cancel out the [read] access outlined before.
Does that make sense? I haven't tried in 2 weeks though so not sure if you have made upgrades.

Here's what I'm hoping would work, but private users still can access email and subscriptionId. 
```
type User
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "id", identityClaim: "username", operations: [read, create, update] }
      { allow: public, provider: apiKey, operations: [read, create, update, delete] }
      { allow: public, provider: iam, operations: [read, create, update, delete] }
      { allow: private, operations: [read]}
    ]
  ) {
id: ID!
username: String
firstName: String
email: String @auth(rules: [{ allow: private, operations: [] }])
subscriptionID: String @auth(rules: [{ allow: private, operations: [] }])
```
Another option could be to remove the global auth header and just add access to the desired lines
```
type User
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "id", identityClaim: "username", operations: [read, create, update] }
      { allow: public, provider: apiKey, operations: [read, create, update, delete] }
      { allow: public, provider: iam, operations: [read, create, update, delete] }
    ]
  ) {
id: ID! @auth(rules: [{ allow: private, operations: [read] }])
username: String @auth(rules: [{ allow: private, operations: [read] }])
firstName: String @auth(rules: [{ allow: private, operations: [read] }])
email: String
subscriptionID: String
```
But then I can't query through other models, Like a user through a post to get their username

Thanks!
