### ISSUE TITLE
Amplify @auth - Access to certain rows for owner and certain rows for everyone

### ISSUE THREAD

**Issue by sudeep-quantelai** [aws-amplify/amplify-cli#4675]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
@Auth on GraphQL schema

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.21.3

**What AWS Services are you utilizing?**
Amplify, AppSync, DynamoDB

**Provide additional details e.g. code snippets**
I have a use case in Amplify GraphQL where I need certain rows to be access by only the owners (people who created them) and other rows to be readable by everyone. How can I achieve that using Amplify @auth parameters. There is a attribute value in the model that determines which are owner accessed and which are general read. How do I use the @auth to achieve this? I can easily use two tables to do this but there are some common processes that act on all rows in the same way.

Has anyone implemented this and can they share an example?

**Comment by andrewbtp** [comment]
Have you looked at this part of the documentation? It seems to cover the exact use case you're describing.
[Amplify Docs - Directives:Auth](https://docs.amplify.aws/cli/graphql-transformer/directives#auth)

**Comment by sudeep-quantelai** [comment]
@andrewbtp  It covers when you want certain fields to be protected. Not sure about treating records different ways.

**Comment by andrewbtp** [comment]
https://docs.amplify.aws/cli/graphql-transformer/directives#owner-authorization like that?

**Comment by sudeep-quantelai** [comment]
@andrewbtp  Not really. There are two sets of records. One set is templates that the other records can be created from. The templates can be viewed by anyone but the records created from the templates should be visible only to the person that created them or an Admin group. The latter part is what is described in the documentation. I have them in different tables right now and it all works well. I need to combine them into one table because there are operations that work on both the templates and the records created from them and having them in different tables means code to account for that difference. 

Thanks to the reference to discord.com will post there as well.

**Comment by andrewbtp** [comment]
Could combine the owner rule with the [dynamic group rule](https://docs.amplify.aws/cli/graphql-transformer/directives#dynamic-group-authorization). On sign up, assign every new user to a group "all" and on the records you want everybody to see, include that in the `groups` field.

**Comment by sudeep-quantelai** [comment]
Hmm.. that could be a workaround. I am wondering if there is anything I can do on the Resolver to achieve this.

**Comment by akshbhu** [comment]
Hi @sudeep-quantelai 

You can go through our documentation on @auth for this usecase. If you want to achieve by resolvers , you can post on the amplify discord community: https://discord.com/invite/jWVbPfC
