### ISSUE TITLE
amplify add notifications creates a Pinpoint resource in us-west-2 even if Pinpoint is available in user's default region

### ISSUE THREAD

**Issue by ArionMiles** [aws-amplify/amplify-cli#4686]
**Describe the bug**
Adding notifications and selecting FCM (I haven't tried others) creates a Pinpoint resource in `us-west-2` (Oregon) region by default, even when the AWS Profile I've set for my account is set to `ap-south-1`, even in `./aws/config`.
AWS Pinpoint is available in `ap-south-1` region.

**Amplify CLI Version**
4.21.3

**To Reproduce**
```
$ amplify add notifications
APNS
>FCM
Email
SMS

Provide pinpoint resource name: (xyz)
apiKey: **************

# This opens the pinpoint console, and the region is us-west-2
$ amplify console notifications
```

**Expected behavior**
The region of the Pinpoint resource should be whatever the default region of the AWS profile being used by Amplify CLI if Pinpoint is available in that region, else default to something else.

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - OS: Windows 10 (2004) OS Build: 19041.329 
 - Node Version: v12.18.0

**Comment by akshbhu** [comment]
Hi @ArionMiles 

Thanks for reporting this.  We have similar issue which is marked for enhancement.You can comment and follow updates on the this.
Closing in favour of #2710
