### ISSUE TITLE
How to add an existing AWS Lambda function to a amplify project?

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#4687]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.19.0

Is there a way to add an existing AWS Lambda function to a amplify project?

**Comment by akshbhu** [comment]
Hi @sakhmedbayev 

Currently ampify cli doesnt support integration with  existing resources. There is RFC for this  : https://github.com/aws-amplify/amplify-cli/issues/3977. You can comment or update on this RFC to support your usecase and track the status.

If you use case is to add existing lambda function to you graphql api, you can check [here](https://docs.amplify.aws/cli/graphql-transformer/directives#usage-1) 

I am closing this issue for now, but feel free to comment and I can again reopen it.
