### ISSUE TITLE
Resources name changed when using block letters

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#469]
**Describe the bug**
When using a name like `HelloWorld` for my project, the cli changes the resource names to `elloorld` by removing `H` and `W` which are the only block letters.

**To Reproduce**
1. `amplify init` with project name `HelloWorld`
2. `amplify analytics add` with resource name `HelloWorld` (default)

**Expected behavior**
Resource should be named `HelloWorld`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Using CLI version 0.1.34

**Comment by kaustavghosh06** [comment]
The change is in deployment phase from beta to prod.

**Comment by sebsto** [comment]
What version will include the above fix ?
I still have the same issue on v0.1.44

```
$ amplify --version
0.1.44

$ ls
AmplifyApp README.md

$ aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --query StackSummaries[].StackName --output table
-----------------------------------------------------------------------
|                             ListStacks                              |
+---------------------------------------------------------------------+
|  mplifypp-20190131164420-apiamplifyrestapi-16ONGHM6T9Q2G            |
|  mplifypp-20190131164420-functionamplifyrestapilambda-B0BUHFK8YM1M  |
|  mplifypp-20190131164420-authcognitof549ec4a-JJEDB2QD4KRO           |
+---------------------------------------------------------------------+
```
