### ISSUE TITLE
"Enable DataStore for entire API" expected behavior

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/amplify-cli#4690]
**Describe the bug**
While using Amplify on iOS, it is possible to start out using an API w/ GraphQL, and then desire to use the option:
`Enable DataStore for entire API`.

Going through this workflow with the Amplify CLI will appropriately update resolvers and the service but does not backfill data to allow it to be compatible with our DataStore implementation.

Customers are running into this issue.  Originally reported here:
https://github.com/aws-amplify/amplify-ios/issues/507

**Amplify CLI Version**
$ amplify -v
4.21.3

**To Reproduce**
1.  Create an API with GraphQL with datastore disabled, and conflict resolution unconfigured
2.  Make a mutation using the console, or programatically via `API.mutate(...)`
Note that the entries made in dynamo will only NOT have the following two fields:
```
_lastChangedAt
_version
```

3.  Enable Datastore by using the CLI:
```
amplify update api
```
Then choose: `GraphQL`
Then Choose: `Enable DataStore for entire API`

4.  Enable Conflict resolution:
```
amplify update api
```
Then choose the following options:
```
? Please select from one of the below mentioned services:
   GraphQL
? Select from the options below
   Walkthrough all configurations
? Choose the default authorization type for the API
   API key
? Enter a description for the API key:
   restaurantdatastore
? After how many days from now the API key should expire (1-365):
   365
? Do you want to configure advanced settings for the GraphQL API
   Yes, I want to make some additional changes.
? Configure additional auth types?
   No
? Configure conflict detection?
  Yes
? Select the default resolution strategy
  Auto Merge
? Do you want to override default per model settings?
  Yes
? Select the models from below:
  Restaurant
? Select the resolution strategy for Restaurant model
  Auto Merge
```

5.  Update (iOS or Android) application code to enable DataStore Library

**Observed behavior**
Upon starting the application, datastore will throw errors because the existing data that was persisted by the mutations made while datastore was not enabled does not include:
```
_lastChangedAt
_version
```
iOS customers see an error (android probably seems something similar):
```
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`
```

**Expected behavior**
Discussion is needed, but a couple ideas on what we should do:
1.  Selecting `Enable DataStore for entire API`, should also kick off a workflow which forces customers to turn on Conflict resolution
2.  When pushing this configuration to the backend, the existing table in the dynamo tables should be backfilled to have 
```
_lastChangedAt (set to the time that datastore was enabled)
_version (set to 1)
```

**Screenshots**
None

**Desktop (please complete the following information):**
Not applicable

**Additional context**
Not applicable

**Comment by enteleca** [comment]
I am having this issue. If the DynamoDB table is clear with no data in it, synchronization is good to go. Once I start inserting data upstream into the DynamoDB table, syncing is still good to go. 

The problem occurs when I am fetching and querying data from the DynamoDB table and back into my iOS application. The data that now has the additional "__typename" "_lastChangedAt" and "_version" fields does not match my application and gives and error while syncing. The data is no longer synced.

Any guidance here? This is a really important issue for me. Thank you.

**Comment by enteleca** [comment]
@renebrandel was this issue fixed? Is there documentation on how to go about navigating this?
