### ISSUE TITLE
Update failed in S3 for Admin Queries API after CLI 4.22.0 update

### ISSUE THREAD

**Issue by selipso** [aws-amplify/amplify-cli#4699]
**Describe the bug**
I have a mid-sized project that doesn't use S3. Yet I'm getting an S3 related error with my GraphQL Schema. The only change I'm trying to make is to remove the Admin queries API from being restricted to a user group (trying to call it with IAM credentials instead).

**Amplify CLI Version**
The project was created in AWS Amplify 4.21.x and worked well with this CLI.

**To Reproduce**
Create an AWS Amplify CLI project in version 4.21.x with an Admin Queries API that is only accessible to a specific Cognito user group (say "Admin"). Deploy everything so that it is in the cloud. Switch to 4.22.0 and remove the auth requirement for the Admin Queries API. Try to redeploy and get the following error when deploying:

```
UPDATE_FAILED      GraphQLSchema AWS::AppSync::GraphQLSchema Mon Jun 29 2020 00:04:07 GMT-0700 (Pacific Daylight Time) The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 3E146055521C959F; S3 Extended Request ID: YWEwd2Ba68pVCCSwC9qkzBVpOUrBTIGLfZ0sVE5tfbSwsyiCIhsIW6KqQRrqBfz2/NMLnvMA4A8=)
```

**Expected behavior**
The auth setting behind the admin queries API should update as expected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Node Version 12.14.1

Edit: On further investigation, I believe the API was created with an older CLI version (don't remember exactly which one but maybe 4.13?). So for the reproduction try creating the GraphQL API with that version first. Then update the admin queries API as described. What I found strange was that updating the admin queries API to select the 'No' option for **Do you want to only give specific groups access to the Admin Queries?** did not allow me to give permissions to IAM users instead. 

Edit 2: Project was created between May 4 and May 6 of this year. Not sure which CLI version this corresponded to but I'm sure it was the latest one as of early May.

**Comment by selipso** [comment]
For anyone else experiencing this, the workaround I found is to save the GraphQL file, delete your API's delete your admin queries, and then add them again. Unfortunate but I was able to save my Cognito resources and lambda triggers.

**Comment by yuth** [comment]
@selipso  by any chance do you know the exact version of Amplify CLI that was used to init project (like 4.21.3 or 4.21.4)

> I have a mid-sized project that doesn't use S3. Yet I'm getting an S3 related error with my GraphQL Schema. The only change I'm trying to make is to remove the Admin queries API from being restricted to a user group (trying to call it with IAM credentials instead).

Amplify CLI behind the scene uses S3 to store the deployment artifact and from the error above it seems to be related how GraphQL Schema is picked up by cloudformation. One way you could save the project is to just add an empty line to your `schema.graphql` and try to redeploy and the file should be uploaded.

**Comment by selipso** [comment]
I didn't mention this earlier but I updated my original comment with the above information as best as I could

**Comment by LucasAndrad** [comment]
I also have some problems with API and v 4.22 posted here in this issue #4753 and removing and adding all API's again didn't work.

**Comment by kaustavghosh06** [comment]
@selipso These seemed to be an intermittent issue since we haven't had reports tied to this in the last couple of months and our team wasn't able to reproduce. Can you let us know if you're still able to see this?
