### ISSUE TITLE
CLI CI/CD solution incompatible with now.sh

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#4701]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
We would like to use Gitflow or Github Flow to deploy feature branches, staging, dev, master/prod, etc. However, To generate the correct enviornment, we need to call something like "amplify env init --some-env". This creates a major problem because not all CI/CD environments allow for a build step like that. Amplify is configuring projects in ways that are not compatible or normal with normal node/react flows.

**Describe the solution you'd like**
The better solution would be to include all or multiple possible build configurations in a centralized "amplify.config" type file. Then, an ENV variable could be set to choose the `dev` or `staging` or `prod`environment at runtime. This way, we could merge a dev branch into staging into master without needing to change code. Each of those environments would contain the configuration for `dev` and `staging` and `prod` and an env variable would switch between them all.

**Describe alternatives you've considered**
Adding a build step. This is not natively possible when deploying with `now.sh` which is an extremely popular tool.

**Additional context**
I understand that Amplify console could be used, but Amplify console is new and extremely buggy and a proprietary build system should not be necessary in order to use Amplify frontend, particularly because it's becoming the recommended frontend SDK for aws mobile apps.

**Comment by yuth** [comment]
@ajhool I have added this to our backlog which will go through our prioritization and will be picked up once this is prioritized.
