### ISSUE TITLE
[GraphQL Transform] API request fails with empty array input for conflict resolution backend

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#4708]
**Describe the bug**
When I provision a conflict enabled backend with a Model containing an embedded type, saving the model with empty array fails.

**Amplify CLI Version**
`4.22.0`

**To Reproduce**
1. amplify init, amplify add api
2. schema.graphql
```gql
type User
@model
{
  id: ID!
  messages: [Message]
}

type Message
{
  id: ID!
  sender: MessageSender!
  description: String!
  createdAt: AWSDateTime!
}
enum MessageSender {
  guest
  user
}
```
3. amplify push

4. amplify console api, make a request like so (this is successful):

<img src="https://user-images.githubusercontent.com/1365977/86055126-32a2e200-ba10-11ea-9593-4478eb6b7476.png" width="500">

5. using `null` is also successful
<img src="https://user-images.githubusercontent.com/1365977/86055186-42bac180-ba10-11ea-829a-0d5bdd3b44f3.png" width="500">

6. Enable conflict resolution: `amplify update api`, choose `GraphQL`, Select from the options below `Enable DataStore for entire API`, amplify push, 

7. go to the dynamoDB table and delete the rows, make sure no data from the non-conflict resolution enabled backend remains

8. Make a request with the same empty array as messages

<img src="https://user-images.githubusercontent.com/1365977/86055932-777b4880-ba11-11ea-833c-fc49ec13d7ff.png" width="1080">

9. messages = `null` works

<img src="https://user-images.githubusercontent.com/1365977/86056165-da6cdf80-ba11-11ea-83f1-5bac0cd884e8.png" width="1080">

**Expected behavior**
Step number 8, where we pass in an empty array for messages, should not fail. Did i miss something here? How do I debug this further?

**Comment by yuth** [comment]
@lawmicha The validation of the argument is done by the AppSync service and I think it is error is because DDB does not support storing empty list. There isnt much the CLI can do in this case

**Comment by lawmicha** [comment]
> @lawmicha The validation of the argument is done by the AppSync service and I think it is error is because DDB does not support storing empty list. There isnt much the CLI can do in this case

Thanks for the quick reply, do you know why it works when conflict resolution isn’t enabled? And fails when conflict resolution is enabled?

**Comment by yuth** [comment]
I can only speculate, it might have to do with the sync table data

**Comment by lawmicha** [comment]
this is related to a service issue, can this be re-opened to keep track?

**Comment by lawmicha** [comment]
Please reopen
