### ISSUE TITLE
amplify mock does not handle AWSPhone like the real appsync

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4709]
**Describe the bug**
Passing empty string for AWSPhone would cause AppSync to respond with:
 
<img width="413" alt=" Essential App · GitLab 2020-06-29 16-16-12" src="https://user-images.githubusercontent.com/81853/86061339-dba70800-ba23-11ea-88df-bbeb3a6cd50d.png">

But with amplify mock, no error is thrown. 

**Amplify CLI Version**
4.22.0

**To Reproduce**
Use a schema like this and pass an empty string `''`

input Person {
  phone: AWSPhone
}

**Expected behavior**
amplify mock and AppSync should behave similarly.

**Comment by symposiumjim** [comment]
Any updates on this? I am not throwing the exclamation point on this however cannot create a record with an empty string.

**Comment by Trevor-mc2** [comment]
+1 on this..  AppSync should allow '' as a valid AWSPhone.

**Comment by attilah** [comment]
In the latest version of the CLI it works the same way as the service providing the following error message for empty strings:
```json
{
  "errors": [
    {
      "message": "Expected type AWSPhone, found \"\"; Query error: Not a valid phone number",
      "locations": [
        {
          "line": 5,
          "column": 12
        }
      ]
    }
  ],
  "data": null
}
```

A workaround is to pass in `null` for empty phone numbers, that works as expected as well.
