### ISSUE TITLE
Issue with API Key as secondary Auth

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#4726]
**Describe the bug**
I am trying to get the following to work

```
type Item
@model
@auth(rules: [
  { allow: owner},
  { allow: groups, groups: ["Admin"] },
  { allow: private, operations: [read] },
  { allow: public, operations: [read] }  #<- For public access
])
```

But when I run this i get this issue
```                                                                                                                         
amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Update auth settings
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API 
@auth directive with 'apiKey' provider found, but the project has no API Key authentication provider configured.
```

If I delete the code ` { allow: public, operations: [read] } ` I don't get the issue and the process finishes but then when I readd the code and run mock api or anything related it doesn't work again with the same error. 

When I choose API Key as the secondary config option it also doesn't ask me about the API Key validation length (time) which it does when I start with API key and do Cognito as the second choice.

**UPDATE**
If I push / publish there is no API KEY authorization added in AWS AppSync

I have tried following videos or read issues I have found but it doesn't work for me, or maybe I am misunderstanding something. 

https://www.youtube.com/watch?v=yR-gJ2hMIPk

**Amplify CLI Version**
4.22.0

**To Reproduce**
Create a GraphQL API with Cognito as default. Try and add API key afterwards and it won't work

**Expected behavior**
That it should work. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Node Version v14.4.0

**Comment by yuth** [comment]
@Zanndorin When choosing additional auth type, you will have to select API Key using `<space bar>`, pressing `<return>` key does not select the any values. So if you chose API Key as one of the additional auth type you should see `API Key` as value next to the `? Choose the additional authorization types you want to configure for the API` question
![Screen Shot 2020-07-01 at 2 54 59 PM](https://user-images.githubusercontent.com/511386/86295277-125b5a80-bbab-11ea-8803-a13ceedcf07a.png)

**Comment by Zanndorin** [comment]
yeah, that was the issue...

thanks.
