### ISSUE TITLE
amplify mock function should list function names to select from if no function name provided

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4727]
**Is your feature request related to a problem? Please describe.**

Amplify CLI sometimes does not let us choose function names (e.g. in the case of congito triggers) so remembering their name by memory is hard. If I enter 'amplify mock function', I should be presented with a list of functions to pick from. Instead I get this error: 

`Specify the function name to invoke with "amplify mock function <function name>"
`

**Describe alternatives you've considered**
Run amplify status and copy and paste the function name before running amplify mock function command.

**Comment by edwardfoyle** [comment]
This has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.
