### ISSUE TITLE
"amplify add function" with permissions to analytics service fails. 

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-cli#4728]
**Describe the bug**
Trying to create lambda trigger with **amplify add function**
If I attach analytics service to function I get error:

```The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument```

**Amplify CLI Version**
4.22.0

**To Reproduce**
- amplify add function
- choose lambda trigger
- "Do you want to update permissions granted to this Lambda function to perform on other resources
 in your project?" - Choose analytics
- make other steps
- amplify push

**Comment by yuth** [comment]
@lenarmazitov which analytics service did you use? Was it Pinpoint or Kinesis? 



> * choose lambda trigger
> 
> * "Do you want to update permissions granted to this Lambda function to perform on other resources
>   in your project?" - Choose analytics

Did you use `amplify update function` flow to give permission? And what are the permissions that were granted.

**Comment by lenarmazitov** [comment]
@yuth I found what happened. I move my project to new directory and forget to update projectPath in amplify/.config/local-env-info.json 

Now I've tried and got success.

**Comment by lenarmazitov** [comment]
Problem seems like this is problem only with Analytics dependency in lambda function

CREATE_FAILED               functionCommonTrigger        AWS::CloudFormation::Stack Wed Jul 08 2020 21:45:20 GMT+0300 (Moscow Standard Time) Template format error: Unresolved resource dependencies [analyticsprojectNameRegion, analyticsprojectNameId] in the Resources block of the template

**Comment by lenarmazitov** [comment]
When you change cloudformation and amplify-meta.json and backend-config.json manually and push all fine.
But next you try to perform any update on function, and analytics removed from everywere I just changed manually and pushed. And error got back

**Comment by lenarmazitov** [comment]
Steps to reproduce:

1. init amplify project
2. add some api
3. add analytics
4. amplify add function (choose additional resources access select **api**)
5. amplify push
6. amplify update function (update additional resources select **analytics**)
7. amplify push (here should fail)

**Comment by waltermvp** [comment]
@lenarmazitov what manual changes did you make for a successful push? thank you in advance
