### ISSUE TITLE
(Multi-Auth) Adding IAM Auth to Graphql Api

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#4733]
**Describe the bug**
I have a graphql appsync api set up with Cognito User Pools auth by default. I have a lambda function and I am trying to allow it to hit up the graphql api. In order to do this, the lambda needs authentication, and I would like to use the IAM strategy. After following the docs about [connecting a lambda to an appsync api](https://docs.amplify.aws/cli/function#signing-a-request-from-lambda) I am unable to do so.

**Amplify CLI Version**
4.22.0

**To Reproduce**
amplify init
amplify add api (create a graphql api with cognito user pool authentication)
amplify add api (add a new api with a lambda function that has CRUD accessto the graphql api)
amplify update api (update the graphql api and configure IAM as a second auth type)
edit the lambda and add the[ following documentation](https://docs.amplify.aws/cli/function#signing-a-request-from-lambda) to one of the http methods (i.e. the post method)
Then try to hit up the method either by testing it in the console or with something like API.post('MyLambdaApi', '/item')

You will get the following error:
    ```{
      errorType: 'UnauthorizedException',
      message: 'Unable to parse JWT token.'
    }```

**Expected behavior**
After adding IAM auth to the graphql api, the lambda should be able to make a call to the graphql api. However, any call is rejected. I suspect that the system is expecting Cogito credentials because IAM doesn't use JWT, right?

**Comment by yuth** [comment]
@karrettgelley where is the lambda running? Is it in the mock or is it in the cloud. 

From the error message, it looks like the Authorization header might be missing in the request. Would it be possible to log the request header and see what is being passed to AppSync?

**Comment by karrettgelley** [comment]
@yuth I figured it out.

In order to allow a lambda to hit up appsync with IAM authentication, you must also specify the `@auth` directive on the models:

```
type SomeModel @model @auth(rules: [{allow: private}, {allow: private, provider: iam}]){
    id: ID!
}
```

The above example allows both cognito user pools and IAM access, which is sufficient for my react client and lambda to access the api. I wish the docs pointed this out a little better but there you go

**Comment by yuth** [comment]
Awesome. I am going to mark this as documentation issue
