### ISSUE TITLE
[Possible Bug] amplify configure url string has `undefined` for region

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4735]
**Describe the bug**

run `amplify configure` and look closely at the URL

![image](https://user-images.githubusercontent.com/6764957/86403828-0e315900-bce1-11ea-8de1-38abe435adc3.png)

**Amplify CLI Version**
4.21.3 

**Expected behavior**

probably it is supposed to say the region. ALTERNATIVELY if the region doesnt matter we should probably not ask for it.

**Comment by aalaap** [comment]
`undefined` is definitely not what I would expect in the URL, especially after having specifically chosen a region in the earlier step. The presented URL opens up a blank IAM user creation page, *where as replacing the `undefined` with `us-east-1` (or any other region) pre-fills the values as expected*.

Interestingly, there's this Amplify configuration tutorial by @dabit3 from 2018 that also puts `undefined` in the URL, but it appears to work fine for him.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/fWbM5DLh25U/0.jpg)](https://www.youtube.com/watch?v=fWbM5DLh25U)

Is the video edited or is this how it's supposed to work?

**Comment by sw-yx** [comment]
i think having an unrecognized region probably falls back to whatever your pre-existing region was. for the vast majority of customers this will be fine which is why this bug has not gone detected. therefore i suspect we should simply stop asking  for the region since this info is unused.

**Comment by aalaap** [comment]
@sw-yx It doesn't fallback for me. If the URL contains `undefined`, it doesn't pre-fill any values and throws you at the first step, instead of the final one. That definitely isn't the expected behaviour.
