### ISSUE TITLE
amplify status shows hosting subdomain url as null.domain.com 

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#4737]
**Describe the bug**

`amplify status` on a webapp that is hosted with amplify returns 
```
Amplify hosting urls: 
┌──────────────┬──────────────────────────────────────────────┐
│ FrontEnd Env │ Domain                                       │
├──────────────┼──────────────────────────────────────────────┤
│ master       │ https://master.mydomain.amplifyapp.com       │
│              ├──────────────────────────────────────────────┤
│              │ https://null.mydomain.com                    │
│              ├──────────────────────────────────────────────┤
│              │ https://www.mydomain.com                     │
└──────────────┴──────────────────────────────────────────────┘
```
From the AWS Console
```
URL | Branch | Redirects to
https://mydomain.com | master | https://www.mydomain.com
https://www.mydomain.com | master | -

```

**Amplify CLI Version**
4.22.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
I expect it to say `https://mydomain.com` instead of `https://null.mydomain.com`

**Comment by jhockett** [comment]
@Zanndorin does the `https://mydomain.com` work correctly? Is this just a printout issue?

**Comment by Zanndorin** [comment]
@jhockett 
Yes this is probably only a printout issue.

https://null.mydomain gives a 404
while https://mydomain gives a 200
