### ISSUE TITLE
 TypeError: Cannot read property 'join' of null on production deploy

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-cli#4740]
Hello, 
I've an Amplify app with 2 git branches and corresponding backend environments (dev - dev, master - prod). My dev branch/env is working properly, deploys correctly when I push and so on. Now I just merged my dev into my master branch, resolved a minor conflicts and when I `amplify push` to prod I get this [error](https://imgur.com/a/DkTWqfU) on the Amplify Console deployment (the resources where in fact updated AFAIK) since I do an `amplify status` and I get no changes.
I've no clue on how to debug/fix this and this merges carries critical business features that I need to deploy today :( so any help on how to solve it would be extremely appreciated!

My amplify cli version is: 4.21.1

Thanks.

**Comment by mykeels** [comment]
![](https://i.imgur.com/212Kepj.png)
