### ISSUE TITLE
[ENV] Develop to Production - CLI is not recognizes new functions (custom Auth) // Fn::GetAtt references

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4741]
I created a customAuth flow in my develop env. 
i pushed it to develop and all is fine. 

then:
`git checkout production
``amplify env checkout production
``git merge develop`

than there are some merge conflicts:
![Bildschirmfoto 2020-07-03 um 17 31 35](https://user-images.githubusercontent.com/7137361/86482859-10340000-bd53-11ea-822d-7ec6bbe3a418.png)

When i want to push my changes to amplify i get en error:

**Template error: instance of Fn::GetAtt references undefined resource functionaivyusersCreateAuthChallenge
An error occured during the push operation: Template error: instance of Fn::GetAtt references undefined resource functionaivyusersCreateAuthChallenge**

i removed all changes and tried amplify env checkout production --restore
than again... but same. 

Normaly there should be create actions in the amplify status.

Amplify: 4.18.0

**Comment by jhockett** [comment]
Hi @davidbiller, can you share the cloudformation templates for "functionaivyusersCreateAuthChallenge"?

If you prefer not to share publicly, please send an email to amplify-cli@amazon.com with the template attached. Please set the subject to "GitHub issue 4741"

**Comment by davidbiller** [comment]
@jhockett 

```

{
--
2 | "AWSTemplateFormatVersion": "2010-09-09",
3 | "Description": "Lambda resource stack creation using Amplify CLI",
4 | "Parameters": {
5 | "CHALLENGEANSWER": {
6 | "Type": "String",
7 | "Default": ""
8 | },
9 | "modules": {
10 | "Type": "String",
11 | "Default": "",
12 | "Description": "Comma-delimmited list of modules to be executed by a lambda trigger. Sent to resource as an env variable."
13 | },
14 | "resourceName": {
15 | "Type": "String",
16 | "Default": ""
17 | },
18 | "trigger": {
19 | "Type": "String",
20 | "Default": "true"
21 | },
22 | "functionName": {
23 | "Type": "String",
24 | "Default": ""
25 | },
26 | "roleName": {
27 | "Type": "String",
28 | "Default": ""
29 | },
30 | "parentResource": {
31 | "Type": "String",
32 | "Default": ""
33 | },
34 | "parentStack": {
35 | "Type": "String",
36 | "Default": ""
37 | },
38 | "env": {
39 | "Type": "String"
40 | }
41 | },
42 | "Conditions": {
43 | "ShouldNotCreateEnvResources": {
44 | "Fn::Equals": [
45 | {
46 | "Ref": "env"
47 | },
48 | "NONE"
49 | ]
50 | }
51 | },
52 | "Resources": {
53 | "LambdaFunction": {
54 | "Type": "AWS::Lambda::Function",
55 | "Metadata": {
56 | "aws:asset:path": "./src",
57 | "aws:asset:property": "Code"
58 | },
59 | "Properties": {
60 | "Handler": "index.handler",
61 | "FunctionName": {
62 | "Fn::If": [
63 | "ShouldNotCreateEnvResources",
64 | "aivyusersCreateAuthChallenge",
65 | {
66 | "Fn::Join": [
67 | "",
68 | [
69 | "aivyusersCreateAuthChallenge",
70 | "-",
71 | {
72 | "Ref": "env"
73 | }
74 | ]
75 | ]
76 | }
77 | ]
78 | },
79 | "Environment": {
80 | "Variables": {
81 | "ENV": {
82 | "Ref": "env"
83 | },
84 | "MODULES": {
85 | "Ref": "modules"
86 | },
87 | "REGION": {
88 | "Ref": "AWS::Region"
89 | },
90 | "CHALLENGEANSWER": {
91 | "Ref": "CHALLENGEANSWER"
92 | }
93 | }
94 | },
95 | "Role": {
96 | "Fn::GetAtt": [
97 | "LambdaExecutionRole",
98 | "Arn"
99 | ]
100 | },
101 | "Runtime": "nodejs10.x",
102 | "Timeout": "25",
103 | "Code": {
104 | "S3Bucket": "aivy-rn-app-develop-20190803185319-deployment",
105 | "S3Key": "amplify-builds/aivyusersCreateAuthChallenge-4f356953782f384d654b-build.zip"
106 | }
107 | }
108 | },
109 | "LambdaExecutionRole": {
110 | "Type": "AWS::IAM::Role",
111 | "Properties": {
112 | "RoleName": {
113 | "Fn::If": [
114 | "ShouldNotCreateEnvResources",
115 | "aivyusersCreateAuthChallenge",
116 | {
117 | "Fn::Join": [
118 | "",
119 | [
120 | "aivyusersCreateAuthChallenge",
121 | "-",
122 | {
123 | "Ref": "env"
124 | }
125 | ]
126 | ]
127 | }
128 | ]
129 | },
130 | "AssumeRolePolicyDocument": {
131 | "Version": "2012-10-17",
132 | "Statement": [
133 | {
134 | "Effect": "Allow",
135 | "Principal": {
136 | "Service": [
137 | "lambda.amazonaws.com"
138 | ]
139 | },
140 | "Action": [
141 | "sts:AssumeRole"
142 | ]
143 | }
144 | ]
145 | }
146 | }
147 | },
148 | "lambdaexecutionpolicy": {
149 | "DependsOn": [
150 | "LambdaExecutionRole"
151 | ],
152 | "Type": "AWS::IAM::Policy",
153 | "Properties": {
154 | "PolicyName": "lambda-execution-policy",
155 | "Roles": [
156 | {
157 | "Ref": "LambdaExecutionRole"
158 | }
159 | ],
160 | "PolicyDocument": {
161 | "Version": "2012-10-17",
162 | "Statement": [
163 | {
164 | "Sid": "Stmt1591815357695",
165 | "Action": "*",
166 | "Effect": "Allow",
167 | "Resource": "*"
168 | },
169 | {
170 | "Sid": "Stmt1591815400511",
171 | "Action": "*",
172 | "Effect": "Allow",
173 | "Resource": "*"
174 | },
175 | {
176 | "Effect": "Allow",
177 | "Action": [
178 | "logs:CreateLogGroup",
179 | "logs:CreateLogStream",
180 | "logs:PutLogEvents"
181 | ],
182 | "Resource": {
183 | "Fn::Sub": [
184 | "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
185 | {
186 | "region": {
187 | "Ref": "AWS::Region"
188 | },
189 | "account": {
190 | "Ref": "AWS::AccountId"
191 | },
192 | "lambda": {
193 | "Ref": "LambdaFunction"
194 | }
195 | }
196 | ]
197 | }
198 | }
199 | ]
200 | }
201 | }
202 | }
203 | },
204 | "Outputs": {
205 | "Name": {
206 | "Value": {
207 | "Ref": "LambdaFunction"
208 | }
209 | },
210 | "Arn": {
211 | "Value": {
212 | "Fn::GetAtt": [
213 | "LambdaFunction",
214 | "Arn"
215 | ]
216 | }
217 | },
218 | "LambdaExecutionRole": {
219 | "Value": {
220 | "Ref": "LambdaExecutionRole"
221 | }
222 | },
223 | "Region": {
224 | "Value": {
225 | "Ref": "AWS::Region"
226 | }
227 | }
228 | }
229 | }

```


So i created a new branch from develop. 
git checkout -b live
All is working here. So i pushed the backend from this branch now, and will use live instead of production. But would be good to know what i did wrong.

**Comment by davidbiller** [comment]
@jhockett 
now again with the new branch "live"

i created a new function called apigate. 

pushed in develop

now i merged develop to live. 

In backend-config.json is a merge conflict now. i can see there the new function, so i tried with current and incoming changes, both is the same state in the amplify status result = no new function

when i search for apigate:

 
<img width="601" alt="Bildschirmfoto 2020-07-08 um 20 02 37" src="https://user-images.githubusercontent.com/7137361/86954315-0ac12600-c156-11ea-9542-d9ea02dc1d13.png">

**Comment by davidbiller** [comment]
The strange thing is: my api changes (schema changes) are there. So status say that api want to update.

**Comment by UnleashedMind** [comment]
After you checked out to the production environment, you don't need to run `git merge develop` for the backend changes, the changes you make in the `develop` env will be carried over to the newly checked out env, you will see that if you run `amplify status`. At this point you can decide if to push the changes to the cloud in the production env. if yes, just run `amplify push`, if no run `amplify pull --restore`.

**Comment by davidbiller** [comment]
So the Flow ist than: 

git checkout production
Git merge develop
Amplify env checkout production

?

**Comment by kaustavghosh06** [comment]
@davidbiller Yes the above command flow should work. Did you give that a shot already?

**Comment by davidbiller** [comment]
Not yet. I followed the Flow from the docs. 

git checkout production
Amplify env checkout production
Git merge develop 

Get some merge conflicts...

**Comment by kaustavghosh06** [comment]
Yeah, you'd have to resolve the merge conflicts - based on your merge from production to git. Which files are you most concerned about wrt to the git merge?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
