### ISSUE TITLE
gql-compile fallen out of sync with schema when using environments

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/amplify-cli#4742]
**Describe the bug**
I believe I am having issues with my schema being out of sync with code generated from `gql-compile` and distinctions between [multiple environments](https://docs.amplify.aws/cli/teams/sandbox)

**Amplify CLI Version**
4.18.1

**To Reproduce**
I am unclear on exactly how to reproduce but this is roughly how I think this issue arose:
If I have time I will also attempt to reproduce the problem on another blank project and if I find out any more I will post.

* I created a project with appsync dynamodb and pushed a few attempts at a schema (dev CF stack)
* There were certain schema changes I couldn't try on existing tables so I followed [sandpit environment instructions here](https://docs.amplify.aws/cli/teams/sandbox) to create a second (sandpit) environment on another local git branch
* I made more drastic changes for experimentation purposes to `schema.graphql` and pushed a number of changes to a new stack (sandpit CF stack)
* I then switched back to my original dev environment and carried on working until I realised that though changes to my graphql file where being pushed to AWS and showing correctly in AWS console, changes where not being applied to local files such as the `./src/models/` folder.

**Expected behavior**
Not to fall out of sync.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v12.16.1

**Comment by jhockett** [comment]
Hello @scottkelso. I have a few questions to help me better understand this issue:

What do you mean by out of sync exactly?

Did you recompile with `gql-compile` after changing environments?

Did you merge your sandpit git branch into your original environment?

**Comment by scottkelso** [comment]
Sure, apologies I still haven't had a chance to recreate on a new project yet. Hopefully, these answers will help for now.

**What do you mean by out of sync exactly?**

Changes made in `schema.graphql` file (when pushed) do not get applied to local files in `./src/models/`. E.G. I make a change to the values in an enum class...

`enum Status { available partial unavailable }` --> `enum Status {IGNORE BOOKED PARTICAL UNAVAILABLE }`

and they do not persist in the `./src/models/index.js`...
```
const Status = {
  "AVAILABLE": "available",
  "PARTIAL": "partial",
  "UNAVAILABLE": "unavailable"
};
```

**Did you recompile with gql-compile after changing environments?**
Yes, I always try `amplify api gql-compile` but unfortunately in this situation it does nothing.

**Did you merge your sandpit git branch into your original environment?**
Yes, I did merge some changes from my sandpit branch into another branch a while back:

![image](https://user-images.githubusercontent.com/26043376/86773124-21c82100-c04d-11ea-86ab-46aea7b8d943.png)

**Comment by scottkelso** [comment]
Further to what actually has fallen out of sync:

Files in `src/graphql/` such as `mutations.js`, `queries.js`, `subscriptions.js` eta update correctly.
Files in `src/models/` such as `index.d.ts`, `index.js`, `schema.d.ts`, `schema.js` do not update correctly, however I have just remembered that these are updated with `amplify codegen models`, not `amplify api gql-compile` as per [instructions](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#manual-model-generation)

I did think there was something else that indicated something not lining up correctly but until I reproduce this issue I will close this issue as I have moved on.
