### ISSUE TITLE
[Feature Request] `amplify configure` should work for existing IAM user

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4744]
**Is your feature request related to a problem? Please describe.**

when cloning down an existing project and running `amplify configure`, i would like to use an existing IAM user, but the CLI doesnt let me:

![image](https://user-images.githubusercontent.com/6764957/86399007-1c7b7700-bcd9-11ea-9f03-bad5460532cc.png)

i have to go lookup an existing iam user and then put it in, then it send me back to the console... 

then i have to go and get an accessKeyId and secretAccessKey - this is secret so i guess this is irreducible and i have to create a new one regardless.

**Describe the solution you'd like**

`amplify configure` should:

- be aware if i already have an existing IAM user locally configured, and tell me that i am already configured.
- offer a list of existing IAM users I have that I can reuse

**Describe alternatives you've considered**
do nothing

**Comment by jhockett** [comment]
`amplify init` initializes your project and provides a list of profiles to use. Whereas `amplify configure` sets up an IAM profile. Is there a need to use configure instead of init here?

**Comment by sw-yx** [comment]
well that points to some confusion @dabit3 and i had about what `configure` actually does then. the naming is a little confusing if it is only used to create an IAM user.

just to be clear - there is no globally configured IAM profile? all profiles are local? and `amplify configure` lets you create and switch to a new profile? am i reading all that right?

happy to do a meeting internally to clear this up

**Comment by 9horses** [comment]
You can see what `amplify configure` does quite explicitly in this video from @dabit3 : https://youtu.be/fWbM5DLh25U

On the other hand, `amplify help` says this about `configure`:
`  configure           Configures the attributes of your project for amplify-cli, such as switching front-end framework and adding/removing cloud-provider plugins.`

**Comment by sw-yx** [comment]
thanks, i am aware. i am pointing out that `amplify configure` is overoptimized for the new user experience because it always sends you out to create a new IAM user.

**Comment by 9horses** [comment]
@sw-yx - totally agree.  My point was simply that the output `amplify help` is incorrect and rather misleading.

**Comment by mxswat** [comment]
+1

**Comment by lincetto** [comment]
+1

**Comment by amlcodes** [comment]
+1, is there no way to bypass this? Without configure with existing user it's near impossible/infuriating to use vscode remote devcontainers in an amplify project

**Comment by arancauchi** [comment]
Yeah this hit me on the head pretty bad too when I had to reconfigure my existing stack, I really thought that `configure` meant configure, and not `create and configure`

**Comment by ObinnaAka** [comment]
I don't know if this counts as a solution, but if you use "amplify configure" and change the username to an existing user instead of the default, it works. When it redirects you to the console to create a new user, you can just ignore it and use the credentials from the existing user instead.

**Comment by sw-yx** [comment]
yup @ObinnaAka I get that. but this developer experience is far from good enough and that's what I'm holding the team accountable for

**Comment by ObinnaAka** [comment]
Oh yes, in that case I very much agree. I've spent hours trying to fix problems that could have been solved with proper naming (e.g. this one). The documentation is good at times, but could definitely be much better.

**Comment by my-name-is-nheo** [comment]
> I don't know if this counts as a solution, but if you use "amplify configure" and change the username to an existing user instead of the default, it works. When it redirects you to the console to create a new user, you can just ignore it and use the credentials from the existing user instead.

@ObinnaAka Have you tried this method before? Were there any consequences?

**Comment by ObinnaAka** [comment]
@my-name-is-nheo Yes it did. I was able to get it working and I don't think there were any consequences in particular.

**Comment by my-name-is-nheo** [comment]
@ObinnaAka Yes, it worked great for me. I have noticed sometimes AWS engineers tries to be overly helpful with their documentations. You can create an IAM through the console, and as long as the name matches when configuring your Amplify project, just skip and enter your access and secret keys!

**Comment by Ebugo** [comment]
wow, thanks guys... So I just need to use `amplify init`, instead of `configure`...

**Comment by marlonmarcello** [comment]
Any way to change profiles without having to create a new IAM user as well?
If for some reason I changed the name of a profile from [work] to [default] for example, I just wanna change that on Amplify without having to `configure` it all again and have to create a new IAM user.

**Comment by jhockett** [comment]
> Any way to change profiles without having to create a new IAM user as well?
> If for some reason I changed the name of a profile from [work] to [default] for example, I just wanna change that on Amplify without having to `configure` it all again and have to create a new IAM user.

You can use `amplify configure project` to change profiles.

**Comment by marlonmarcello** [comment]
Thank you @jhockett !

**Comment by fireflysemantics** [comment]
OK - I was confused about this too.

So I followed what it said here and this worked fine:
1) `amplify configure`
2) Log in to AWS
3) Enter the existing user name
4) Just cancel out of the Web Setup
5) Enter existing existing AWS credentials in the CLI

And that's it.  The existing credentials are reused.

**Comment by rohitRohi123** [comment]
open your .aws directory in mac it available at  path "user/username/.aws".
In that path you get two files i.e config and credentials. Here you can set a profile for an existing IAM user then you can initialize amplify with this profile. 


https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by rohitRohi123** [comment]
open your .aws directory in mac it available at  path "user/username/.aws".
In that path you get two files i.e config and credentials. Here you can set a profile for an existing IAM user then you can initialize amplify with this profile. 


https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by david-mcafee** [comment]
I've just merged [a PR](https://github.com/aws-amplify/docs/pull/4008) to our docs outlining the correct path for this. From the PR: 

> It is recommended to create a new IAM user for every device that installs the Amplify CLI, rather than attempt to use an existing IAM user used on another device. Having a distinct user for each machine provides the best level of visibility and control without breaking the deployment of your app, allowing for the quick deactivation of an individual machine if needed.

Hope this clears up the issue! Please feel free to re-open if there are further questions ☺️

Related: #5718

**Comment by lexi89** [comment]
> I've just merged [a PR](https://github.com/aws-amplify/docs/pull/4008) to our docs outlining the correct path for this. From the PR:
> 
> > It is recommended to create a new IAM user for every device that installs the Amplify CLI, rather than attempt to use an existing IAM user used on another device. Having a distinct user for each machine provides the best level of visibility and control without breaking the deployment of your app, allowing for the quick deactivation of an individual machine if needed.
> 
> Hope this clears up the issue! Please feel free to re-open if there are further questions ☺️
> 
> Related: #5718

Kinda get it but kinda don't. I got a new machine and have to set up a new AWS user for it? Now I'm going to exist twice in IAM and Cloudtrail. And then what if I use another machine temporarily? 3 IAM users? No bueno. 

I end up banging my head against amplify startup every single time I move to a new machine as an existing user. Ideal flow surely is: install the CLI, punch in creds, download the repo, hit `amplify serve` and get started. Definitely still an open issue. Hope this gets picked up 🙏

**Comment by gothriveandy** [comment]
> wow, thanks guys... So I just need to use `amplify init`, instead of `configure` for an already existing IAM user...

This is correct. And you just put the name of your existing project in:
?  Enter a name for the project
