### ISSUE TITLE
Subscription has different response depending query

### ISSUE THREAD

**Issue by cdac901** [aws-amplify/amplify-cli#4745]
**Describe the bug**
Subscription has different response depending query

**Amplify CLI Version**
4.22.0

**To Reproduce**
1.- Create schema:

```gql
type TestSubscription @model(subscriptions: { level: off }) {
  id: ID!
  companyID: ID!
  text: String
}

type Subscription {
  onCreateTestSubscription(companyID: ID!): TestSubscription @aws_subscribe(mutations: ["createTestSubscription"])
}
```

2.- Run amplify push api in terminal
3.- Open 2 AWS AppSync Console - Project Name - Query in navigator

In first query console add and run:

```gql
subscription {
  onCreateTestSubscription(companyID: "1"){
    id,
    companyID,
    text
  }
} 
```

I run 3 test:
In second query console add and run mutation:

First test:
```gql
mutation {
  createTestSubscription(input: {
    companyID: "1",
    text: "test"
  }){
    id
  }
}
```

See response subscription: no response (Why?)

Second test:
```gql
mutation {
  createTestSubscription(input: {
    companyID: "1",
    text: "test"
  }){
    id,
    companyID
  }
}
```

See response subscription: 

```
{
  "data": {
    "onCreateTestSubscription": {
      "id": "d6f38d85-89b8-43c2-a4cc-9fd4800d0de0",
      "companyID": "1",
      "text": null <---- why null?
    }
  }
}

```

Third test:
```gql
mutation {
  createTestSubscription(input: {
    companyID: "1",
    text: "test"
  }){
    id,
    companyID,
    text
  }
}
```

See response subscription (Ok!): 
```json
{
  "data": {
    "onCreateTestSubscription": {
      "id": "86f13eeb-8523-46db-9d03-111222527eed",
      "companyID": "1",
      "text": "test"
    }
  }
}
```

**Expected behavior**
The subscription response should not be associated with the query output fields.

**Comment by jhockett** [comment]
Hi @cdac901, the AppSync response is dependent on the query output fields by design. The third approach is the correct one.

**Comment by cdac901** [comment]
Thanks for response, I suggest placing this clarification in the [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html)

Issue closed.
