### ISSUE TITLE
Amplify storage - change bucket

### ISSUE THREAD

**Issue by al3x88** [aws-amplify/amplify-cli#4746]
Hi,
as described in this tutorial:
https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios#initialize-amplify-storage

I integrated Amplify storage with my iOS app. The thing is that this conf created a new S3 bucket, when what I was looking for was to link to my existing bucket.
Could someone please explain me how to achieve this?

**Comment by jhockett** [comment]
This is not yet possible with the CLI. See the RFC for this feature: https://github.com/aws-amplify/amplify-cli/issues/3977

**Comment by al3x88** [comment]
ok fyi as a work around I created a lambda script to copy each created object to the target bucket
