### ISSUE TITLE
ImportValue issue on dynamodb lambda trigger template

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#4748]
**Describe the bug**
Template is throwing error on push:

CREATE_FAILED      functionjcProcessDMAlerts    AWS::CloudFormation::Stack Sun Jul 05 2020 14:35:44 GMT-0400 (Eastern Daylight Time) Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs

`"Resource": {
								"Fn::ImportValue": {
									"Fn::Sub": "${apijcmobileGraphQLAPIIdOutput}:GetAtt:DirectMessageTable:StreamArn"
								}
							}`

`"EventSourceArn": {
					"Fn::ImportValue": {
						"Fn::Sub": "${apijcmobileGraphQLAPIIdOutput}:GetAtt:DirectMessageTable:StreamArn"
					}
				},`

**Amplify CLI Version**
4.22.0

**To Reproduce**
Created a lambda trigger on a table, with all permissions given to auth/api/analytics

**Expected behavior**
Should push succesfully

**Desktop (please complete the following information):**
Mac

**Comment by GeorgeBellTMH** [comment]
Originally introduced in: #987 and #3552

**Comment by a-ursino** [comment]
Using the full value instead of `${apiGraphQLAPIIdOutput}:GetAtt:ReservationTable:StreamArn` solved the problem. Obviously this solution is less ideal. 
Any idea on how to make `${apiGraphQLAPIIdOutput}:GetAtt:ReservationTable:StreamArn` work?

```
AWS::CloudFormation::Stack Sun Jul 26 2020 07:03:15 GMT+0200 (Central European Summer Time) Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs
```

**Comment by UnleashedMind** [comment]
The Cloudformation does not allow such usage:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
```
For outputs, the value of the Name property of an Export can't use Ref or GetAtt functions that depend on a resource.

Similarly, the ImportValue function can't include Ref or GetAtt functions that depend on a resource.
```
