### ISSUE TITLE
Cannot `amplify push` after `amplify add storage`

### ISSUE THREAD

**Issue by RealSlimMahdi** [aws-amplify/amplify-cli#4751]
**Describe the bug**
Cannot push after adding s3 + Trigger function to the project

**Amplify CLI Version**
4.22.0

**To Reproduce**
start project with
- auth
- Api + apiLambda + DynamoDb
- Push
- add storage S3 + trigger

**Expected behavior**
I would like to be able to push and correctly add s3 bucket + trigger

**Screenshots**
Current Environment: devone

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Function | S3Triggerd07eb612 | Create    | awscloudformation |
| Storage  | s3emailsecoav2    | Create    | awscloudformation |
| Function | apiEcoaFunction   | Update    | awscloudformation |
| Auth     | ecoav20119404c    | No Change | awscloudformation |
| Api      | apiecoa           | No Change | awscloudformation |
| Storage  | ecoaDynamoDb      | No Change | awscloudformation |

? Are you sure you want to continue? Yes
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      functionS3Triggerd07eb612    AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:33 GMT+0200 (Central European Summer Time) Resource creation cancelled                                                                                                                                     
UPDATE_COMPLETE    storageecoaDynamoDb          AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time)                                                                                                                                                                 
UPDATE_FAILED      authecoav20119404c           AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time) Parameters: [hostedUIDomainName, oAuthMetadata, googleClientId, authProvidersUserPool, hostedUIProviderMeta, hostedUIProviderCreds] do not exist in the template
UPDATE_IN_PROGRESS storageecoaDynamoDb          AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time)                                                                                                                                                                 
CREATE_IN_PROGRESS functionS3Triggerd07eb612    AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time) Resource creation Initiated                                                                                                                                     
UPDATE_IN_PROGRESS authecoav20119404c           AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time)                                                                                                                                                                 
CREATE_IN_PROGRESS functionS3Triggerd07eb612    AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:31 GMT+0200 (Central European Summer Time)                                                                                                                                                                 
UPDATE_IN_PROGRESS amplify-ecoav2-devone-110628 AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:27 GMT+0200 (Central European Summer Time) User Initiated                                                                                                                                                  
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-ecoav2-devone-110628-functionS3Triggerd07eb612-JWLGVU1SLN14 AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:32 GMT+0200 (Central European Summer Time) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-ecoav2-devone-110628 AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:33 GMT+0200 (Central European Summer Time) The following resource(s) failed to create: [functionS3Triggerd07eb612]. The following resource(s) failed to update: [authecoav20119404c]. 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Mon Jul 06 2020 13:36:35 GMT+0200 (Central European Summer Time) 
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Mon Jul 06 2020 13:36:35 GMT+0200 (Central European Summer Time) Resource creation Initiated
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    LambdaFunction      AWS::Lambda::Function Mon Jul 06 2020 13:36:53 GMT+0200 (Central European Summer Time)                            
CREATE_IN_PROGRESS LambdaFunction      AWS::Lambda::Function Mon Jul 06 2020 13:36:53 GMT+0200 (Central European Summer Time) Resource creation Initiated
CREATE_IN_PROGRESS LambdaFunction      AWS::Lambda::Function Mon Jul 06 2020 13:36:52 GMT+0200 (Central European Summer Time)                            
CREATE_COMPLETE    LambdaExecutionRole AWS::IAM::Role        Mon Jul 06 2020 13:36:50 GMT+0200 (Central European Summer Time)                            
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS lambdaexecutionpolicy AWS::IAM::Policy Mon Jul 06 2020 13:36:55 GMT+0200 (Central European Summer Time) Resource creation Initiated
CREATE_IN_PROGRESS lambdaexecutionpolicy AWS::IAM::Policy Mon Jul 06 2020 13:36:55 GMT+0200 (Central European Summer Time)                            
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    storageecoaDynamoDb AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:58 GMT+0200 (Central European Summer Time) 
UPDATE_IN_PROGRESS storageecoaDynamoDb AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:58 GMT+0200 (Central European Summer Time) 
UPDATE_COMPLETE    authecoav20119404c  AWS::CloudFormation::Stack Mon Jul 06 2020 13:36:58 GMT+0200 (Central European Summer Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                              storageecoaDynamoDb          AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:01 GMT+0200 (Central European Summer Time) 
UPDATE_COMPLETE                              authecoav20119404c           AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:01 GMT+0200 (Central European Summer Time) 
DELETE_IN_PROGRESS                           functionS3Triggerd07eb612    AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:01 GMT+0200 (Central European Summer Time) 
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-ecoav2-devone-110628 AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:00 GMT+0200 (Central European Summer Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      lambdaexecutionpolicy                                               AWS::IAM::Policy           Mon Jul 06 2020 13:37:02 GMT+0200 (Central European Summer Time) Resource creation cancelled
DELETE_IN_PROGRESS amplify-ecoav2-devone-110628-functionS3Triggerd07eb612-JWLGVU1SLN14 AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:01 GMT+0200 (Central European Summer Time) User Initiated             
⠙ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS LambdaFunction        AWS::Lambda::Function Mon Jul 06 2020 13:37:28 GMT+0200 (Central European Summer Time) 
DELETE_COMPLETE    lambdaexecutionpolicy AWS::IAM::Policy      Mon Jul 06 2020 13:37:27 GMT+0200 (Central European Summer Time) 
DELETE_IN_PROGRESS lambdaexecutionpolicy AWS::IAM::Policy      Mon Jul 06 2020 13:37:27 GMT+0200 (Central European Summer Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role        Mon Jul 06 2020 13:37:29 GMT+0200 (Central European Summer Time) 
DELETE_COMPLETE    LambdaFunction      AWS::Lambda::Function Mon Jul 06 2020 13:37:29 GMT+0200 (Central European Summer Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-ecoav2-devone-110628-functionS3Triggerd07eb612-JWLGVU1SLN14 AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:31 GMT+0200 (Central European Summer Time) 
DELETE_COMPLETE LambdaExecutionRole                                                 AWS::IAM::Role             Mon Jul 06 2020 13:37:31 GMT+0200 (Central European Summer Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-ecoav2-devone-110628 AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:35 GMT+0200 (Central European Summer Time) 
DELETE_COMPLETE          functionS3Triggerd07eb612    AWS::CloudFormation::Stack Mon Jul 06 2020 13:37:35 GMT+0200 (Central European Summer Time) 
⠹ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠸ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: ampli-lamb-4NPLX0O41QUO (AWS::IAM::Policy)
Event Type: create
Reason: Resource creation cancelled

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Node Version 13.12.0

**Additional context**
N/A

**Comment by jhockett** [comment]
Hi @RealSlimMahdi I wasn't able to reproduce this issue with the given steps. Can you provide further details on how you set up `ecoav20119404c` in the auth category?
