### ISSUE TITLE
query using AWS.HttpRequest not working with mock api but works using axios

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#4752]
**Describe the bug**
When making a query to the API as described [here](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda), the query only works with the proper deployed API. The same query using axios works fine.

**Amplify CLI Version**
4.22.0

**To Reproduce**
Deploy an api with an apiKey with this schema:
```
type License @model (subscriptions: { level: off }) # @searchable
  @auth(rules: [
    { allow: public, provider: apiKey },
  ])
{
  id: ID!
  innehaver: String
}
```
run ```amplify mock api``` and insert a "license" using GraphiQl.

with the enclosed files try:
```node list-licenses-awsRequest.js```
This failes with the following error:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.2:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

If I try the same thing after inserting a "License" to the deployed api it works as expected.

When making the same query using axios like this:
```node list-licenses.js```
It works with both the mock api and deployed api

**Expected behavior**
The query should work the same way for both mock and the proper api when using AWS.HttpRequest

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v10.17.0

[list-licenses-scripts.zip](https://github.com/aws-amplify/amplify-cli/files/4878956/list-licenses-scripts.zip)

**Comment by yuth** [comment]
@kateglee apologies for late response. The attached code is in `list-licenses-awsRequest.js`, you're using an `https` client and mock server supports only http. In order to support both mock and actual server you will have to conditionally use either `http` or `https` client as shown below (which is just updated version of the attached code)

```js
const https = require("https");
const http = require("http");
const AWS = require("aws-sdk");
const urlParse = require("url").URL;

const apiKey = "da2-fakeApiId123456";
const appsyncUrl = "http://localhost:20002/graphql";
const region = "us-east-1-fake";

// const apiKey = 'qwertyuiop'
// const appsyncUrl = 'https://qwertyuiop.appsync-api.eu-west-1.amazonaws.com/graphql'
// const region = 'eu-west-1'

console.log(AWS.config.sslEnabled);
const endpoint = new urlParse(appsyncUrl).hostname.toString();

const graphqlQuery = `query listLicenses {
  listLicenses {
    items {
      id
      innehaver
    }
  }
}`;

const request = async () => {
  console.log(appsyncUrl);
  const req = new AWS.HttpRequest(appsyncUrl, region);

  req.method = "POST";
  req.headers["Content-Type"] = "application/json";
  req.body = JSON.stringify({
    query: graphqlQuery,
    operationName: "listLicenses",
  });
  req.headers["x-api-key"] = apiKey;

  let res;
  res = await new Promise((resolve, reject) => {
    // choose the appropriate client for making request
    const requestClient = req.endpoint.protocol === "http:" ? http : https;
    const httpRequest = requestClient.request(
      { ...req.endpoint, ...req, host: endpoint },
      (result) => {
        result.on("data", (data) => {
          resolve(JSON.parse(data.toString()));
        });
        result.on("errors", (err) => {
          reject({ feil: "det gikk galt", err });
        });
      }
    );
    httpRequest.write(req.body);
    httpRequest.end();
  });
  console.log(JSON.stringify(res));
};

request();
```
