### ISSUE TITLE
Adding AWS::Lambda::EventSourceMapping to Lambda

### ISSUE THREAD

**Issue by asmajlovicmars** [aws-amplify/amplify-cli#4759]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Tried to add AWS::Lambda::EventSourceMapping to a new Lambda function's CloudFormation template, in order to trigger it when the queue receives the data. At the same time I created a new policy, with needed permissions:
```json
              "Action": [
                "sqs:DeleteMessage",
                "sqs:ReceiveMessage",
                "sqs:GetQueueAttributes",
                "sqs:ChangeMessageVisibility"
              ],
```
If I try to push the code, I get the error, that Lambda doesn't have proper permissions, even though they're in the CF template: 
`
CREATE_FAILED               LambdaFunctionSQSUserAppEventSourceMapping                                           AWS::Lambda::EventSourceMapping Tue Jul 07 2020 12:07:45 GMT+0000 (Coordinated Universal Time) The provided execution role does not have permissions to call ReceiveMessage on SQS (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: b627dc3c-3c6e-4a48-bbe0-e830d95657eb)
`
If I remove the EventSourceMapping, push the permissions first, and then put back the EventSourceMapping code, and push again, everything works fine. Seems, like the order of applying the permissions is after trying to create a resource.

**Amplify CLI Version**
4.22.0

**To Reproduce**
Add the following code to functionLambda-cloudformation-template.json, and try to push it:
```json
    "LambdaFunctionSQSEventSourceMapping": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "Properties": {
        "BatchSize": "10",
        "Enabled": "true",
        "EventSourceArn": {
          "Ref": "MyQueueArn"
        },
        "FunctionName": {
          "Ref": "LambdaFunction"
        }
      }
    },
```
```json
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Action": "lambda:InvokeFunction",
              "Resource": "*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "sqs:DeleteMessage",
                "sqs:ReceiveMessage",
                "sqs:GetQueueAttributes",
                "sqs:ChangeMessageVisibility"
              ],
              "Resource": [
                {
                  "Ref": "MyQueueArn"
                }
              ]
            }
          ]
        }

```

**Expected behavior**
Should be working the same way, as it works if we do a 2-stage push, permissions first, and then EventSourceMapping. 

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Node Version. v14.2.0

**Comment by jhockett** [comment]
Hi @asmajlovicmars, you need to set the`dependsOn` field to make sure the resources are created in the correct sequence.

**Comment by asmajlovicmars** [comment]
Hi @jhockett, yes, basically, a "PolicyDocument" should be created before "LambdaFunctionSQSEventSourceMapping". Could you please show an example how would I set dependsOn between these two, and should it be in a backend-config.json or somewhere else?

**Comment by asmajlovicmars** [comment]
Thank you @jhockett
