### ISSUE TITLE
Add Support to AWS China in Beijing

### ISSUE THREAD

**Issue by MarchingVoxels** [aws-amplify/amplify-cli#4767]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
I'm trying to add support to a backend that can serve Chinese users. AWS China currently isn't within the regions list but it has ( I think ) all services that are wrapped by Amplify, for instance: Cognito, S3, AppSync etc. 

**Describe the solution you'd like**
A solution which allows developers to similarly configure AWS China with Amplify CLI. 

**Describe alternatives you've considered**
I'm currently trying to just use amplify in development. I think that it's possible to replicate all the Amplify steps in AWS China's console given that all of these features are supported. However, it will be a very painful experience and I don't know if this will work at all.  **_Any insight into how I can manually configure my code to support AWS China is also appreciated._** 
I think that it's possible to just edit aws-exports.js by changing the addresses to match AWS China. But the manual setup on the AWS side will be very tedious. 

**Additional context**
Hypothetical Steps to manually support AWS China: 
1. build the project as usual so that we can access #current-cloud-backend and backend folders
2. edit relevant files such as amplify-meta.json to point to AWS China
3. configure services in AWS China
4. deploy the app to AWS(**although I do not know which part specifically so any help is appreciated**)

**Comment by brene** [comment]
Hi @MarchingVoxels thanks for bringing this to our attention.

Given that most services (in fact 11 services, incl. Cognito User Pool) are actually not currently in the China regions, we currently cannot support the China regions for Amplify CLI. We will be revisiting this decision in the future as more services onboard to those regions.

**Comment by xxingjjing** [comment]
Hi @brene
Aws China has two regions, cn-north-1 and cn-northwest-1, Of whitch the region cn-north-1 has the following services: Cognito User Pool, AppSync, S3, API gateway, CouldFront, Lambda function, DynamoDB etc. By the way, cn-northwest-1 does not have the following services: Cognito User Pool and AppSync.

**Comment by zxkane** [comment]
Amplify-cli has module system, why not supporting `api`, `storage`, `function` modules in China regions?
