### ISSUE TITLE
amplify function update - doesn't remember previous function permissions

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#4768]
**Describe the bug**
In the new Amplify CLI version, a lambda function permissions is stored (in the `function-parameters.json`) under the `mutableParametersState.permissions` object, and it was previously under the global `permissions` object, and now - when trying to update a function through the CLI it doesn't remember the previous permissions and you need to add all of your permissions all over again.

**Amplify CLI Version**
`4.23.0`

**To Reproduce**
1. Create lambda function using `amplify function add`, add some permissions to it in creation (storage, analytics, whatever).
2. type `amplify function update`, choose your new function and try to update permissions for the function.
3. See that none of the permissions are selected, but if you go to the `function-parameters.json` file the permissions exist there

**Expected behavior**
The CLI is aware of the previous permissions of the function.

# Extra
Another feature that can be useful is that you check if the previous version global `permissions` object exists, and if it does then delete it in favor of the new `mutableParametersState.permissions` object, so there is no multiple data which can cause confusion (as it has for me).

**Comment by jhockett** [comment]
Hi @idanlo, #4823 fixes this issue. It will go out with the next release.
