### ISSUE TITLE
[API] GraphQL API as REST API through Lambda with AppSync or DynamoDB?

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#4769]
I have created a GraphQL Api for my mobile app using the CLI. 

Now some partners need data generated in the app. These are on the DynamoDB. 

Now the question is how do I do that? 
I have created a new function: 

```
Provide a friendly name for your resource to be used as a label for this category in the project: apigate
? Provide the AWS Lambda function name: apigate
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: Serverless ExpressJS function (Integration with API Gateway)
? Do you want to access other resources created in this project from your Lambda function? Yes
? Select the category api
Api category has a resource called ...
? Select the operations you want to permit for create, read, update, delete
```

**I used Serverless ExpressJS because the CRUD function of DynamoDB did not find my DynamoDB tables.** 

```Using service: Lambda, provided by: awscloudformation
? Provide a friendly name for your resource to be used as a label for this category in the project: apigate
? Provide the AWS Lambda function name: apigate
? Choose the function runtime that you want to use: NodeJS
? Choose the function template that you want to use: CRUD function for DynamoDB (Integration with API Gateway)
? Choose a DynamoDB data source option Use DynamoDB table configured in the current Amplify project
```

`There are no DynamoDB resources configured in your project currently`

Now I have the question, since the function does not have access to DynamoDB by default, should I simply extend it? Should I go internally then over GraphQL via AppSync? Performance will probably be better if I access it directly via DynamoDB?

my first test:

```
app.get('/answers', function (req, res) {
  var params = {
    ProjectionExpression: "id",
    TableName: `Answer-${process.env.API_AIVY_GRAPHQLAPIIDOUTPUT}-${process.env.ENV}`,
  };
  dynamodb.scan(params, function (err, data) {
    console.log(data)
    if (err){
      res.json({ error: err, url: req.url });
    }
    res.end({ success: data, url: req.url })
  });
});
```

**Comment by davidhgray** [comment]
@davidbiller  i'm seeing a similar issue #4817, but others have had success using the "Hello world" template #3693.  have you tried the "Hello world" template to see if the CLI can see your DB when choosing a Category?

**Comment by davidbiller** [comment]
I have tested this with access to storage. Makes sense that it's under storage, but also confusing when you first get a message that there are no tables.
