### ISSUE TITLE
CLI: 4.23.0 - TypeError: Cannot read property 'provider' of undefined at Object.updateConfigOnEnvInit

### ISSUE THREAD

**Issue by diondree** [aws-amplify/amplify-cli#4770]
**Describe the bug**
I'm currently trying to use the Amplify CLI headless in a custom CodeBuild setup. I'm not sure if I'm missing something here but I followed the steps I've seen and I'm getting the following the error in the log output. 

```bash
153 | init failed
154 | TypeError: Cannot read property 'provider' of undefined
155 | at Object.updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:222:84)
156 | at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:106:54
157 | at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
158 | at process._tickCallback (internal/process/next_tick.js:68:7)
159
```

**Amplify CLI Version**
 4.23.0 

**To Reproduce**
I'm running this bash script as part of the build process.
```bash
#!/bin/bash
set -e
IFS='|'

echo $AWS_ACCESS_KEY_ID

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":false,\
\"accessKeyId\":$AWS_ACCESS_KEY_ID,\
\"secretAccessKey\":$AWS_SECRET_ACCESS_KEY,\
\"region\":\"us-east-1\"\
}"

AMPLIFY="{\
\"projectName\":\"dpportal\",\
\"envName\":\"staging\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--codegen ${CODEGEN} \
--yes

amplify push
```

The $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY environment variables are added to the buildspec file which pulls those values from Secrets Manager.

**Expected behavior**
I expected the project to be initialized in order for me to deploy the stack and provision the resources. 

**Screenshots**

**Environment:**
Also using this image to build the project
`aws/codebuild/nodejs:10.14.1`

**Comment by codecadwallader** [comment]
I'm seeing the exact same and was just coming to report it.  v4.23 came out yesterday and that's when the issue showed up for us.  It doesn't seem to affect existing environments, only new environments in our CI/CD setup.  I've pinned our build settings back to v4.22 and the build seems to be succeeding again.

![image](https://user-images.githubusercontent.com/3823772/86925585-0fa6bb00-c0ff-11ea-9f27-ba439e3819a5.png)

**Comment by diondree** [comment]
Ah yes this worked for me as well. Guess the issue was introduced in this new version.

> I'm seeing the exact same and was just coming to report it. v4.23 came out yesterday and that's when the issue showed up for us. It doesn't seem to affect existing environments, only new environments in our CI/CD setup.
> 
> **Workaround**: I've pinned our build settings back to v4.22 and the build seems to be succeeding again.
> 
> ![image](https://user-images.githubusercontent.com/3823772/86925585-0fa6bb00-c0ff-11ea-9f27-ba439e3819a5.png)

**Comment by flywheelms** [comment]
Thanks for reporting this bug.  We will triage and provide an update.

**Comment by UnleashedMind** [comment]
@diondree 
What are the amplify categories you added to your project? 
What are the exact steps that leads to this issue?

**Comment by diondree** [comment]
@UnleashedMind I only have auth and a function added. This issue occurs when my CodeBuild process is triggered from Github.

This is the top part of my buildspec file where the issue occurs:
```yaml
version: 0.2

env:
    secrets-manager:
        AWS_ACCESS_KEY_ID: AmplifyUser:AMPLIFY_SECRET_KEY_ID
        AWS_SECRET_ACCESS_KEY: AmplifyUser:AMPLIFY_ACCESS_KEY

phases:
  install:
    commands:
       - npm install -g @angular/cli@6.2.9
       - npm install -g @aws-amplify/cli@4.22.0
       - npm install
  pre_build:
    commands:
       - ./scripts/amplify.sh
```
As I mentioned it pulls the access key id and access key from secrets manager and then uses them in the amplify script (amplify.sh). This script is what I added as part of the original issue.

**Comment by edwardfoyle** [comment]
@diondree @codecadwallader could you share the "function" block of your amplify-meta.json file? Or if it contains sensitive information you can email it to amplify-cli@amazon.com

**Comment by diondree** [comment]
@edwardfoyle I just sent the email with it

**Comment by codecadwallader** [comment]
@edwardfoyle Ditto, sent.

**Comment by jhockett** [comment]
Thanks for the great info @diondree @codecadwallader! We were able to reproduce and are working on a fix.

**Comment by diondree** [comment]
@jhockett That's awesome! You're very welcome

**Comment by jhockett** [comment]
@aws-amplify/cli version 4.23.1 has just been released. If you experience the same issue, please comment below.
