### ISSUE TITLE
amplify push error on HostedUICustomResourceInputs creation

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#4781]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created a new environment from one of my current environments (Making a test stage) and when I publish it is unable to create the required resources. The specific error is the following in cloudformation:

2020-07-08 19:35:22 UTC-0700 | HostedUICustomResourceInputs | CREATE_FAILED | Failed to create resource. See the details in CloudWatch Log Stream: 2020/07/09/[$LATEST]d23c75844f0e46a1a84bbb59eecee1bf
-- | -- | -- | --

which in the log resource is:

```
2020-07-09T01:50:35.027Z	8896a91d-c6a2-4897-bb14-82b0f57afee7	INFO	{ ResourceNotFoundException: User pool us-east-1_nLwgmrmTQ does not exist.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'User pool us-east-1_nLwgmrmTQ does not exist.',
  code: 'ResourceNotFoundException',
  time: 2020-07-09T01:50:35.026Z,
  requestId: '7fab3d74-e31b-4b09-a9f1-62c2315f565b',
  statusCode: 400,
  retryable: false,
  retryDelay: 83.33807292740994 }
```

For every single CLI version I tried the error was the exact same in the sense that it is saying the same user pool does not exist. The user pool ID was the same for every try

**Amplify CLI Version**
I tried on the following versions:
4.23.0 
4.22.0
4.21.0
4.20.0

**To Reproduce**
amplify env add
.. follow steps (name was test)
amplify push

**Expected behavior**
Resources to be created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC
 - Node Version. 12.12.0

**Additional context**

**Comment by gakinson** [comment]
I figured out the issue. It was due to the domain name in auth not being available. Since the default is auth and my env was test, it resulted in auth-test which is not very unique, so someone must already have it. 

I do recommend maybe adding the application name into this so that other people don't face the same issue

**Comment by SwaySway** [comment]
Hello @gakinson 
When you say domain name are you referring to the auth userpool id? I think the error might lie somewhere else since others using the CLI can may also have a test env.

**Comment by gakinson** [comment]
Inside of the Auth cloudformation stack within amplify that gets generated, there is the following section that got created:
```
HostedUICustomResourceInputs:
    Type: 'Custom::LambdaCallout'
    Properties:
      ServiceToken: !GetAtt HostedUICustomResource.Arn
      userPoolId: !Ref UserPool
      hostedUIDomainName: !If [ShouldNotCreateEnvResources, !Ref hostedUIDomainName, !Join ['-',[!Ref hostedUIDomainName, !Ref env]]]
    DependsOn: HostedUICustomResourceLogPolicy
```

The ref of hostedUIDomainName can be traced back to the parameters which is the following:
```
"hostedUIDomainName": "auth",
```

The resulting join of "auth" and env ("test"), will result in "auth-test" which would be a fairly commonly used name for the domain name.

Now it is possible that this was a question that was asked when I setup the auth a long time ago, but I do not remember. I just wanted to make sure that in the future either it is an option or that the default name that is used for the domainName is not "auth".

**Comment by lenarmazitov** [comment]
Have similar error.
I inited new amplify project, and just try to perform
amplify add auth
amplify push

And get error
```
The following resource(s) failed to create: [HostedUICustomResourceInputs]. 
```

**Comment by UnleashedMind** [comment]
@gakinson 

The error message says 'User pool us-east-1_nLwgmrmTQ does not exist.' 
Have you investigated on this? The name suggests that you userpool is in the us-east-1 region, are you setting up the new region in us-east-1?

**Comment by UnleashedMind** [comment]
@lenarmazitov 
How did you configure the auth category with the CLI? what federated identities did you add?
We need more information to investigate.
