### ISSUE TITLE
CLI v4.22.0: Error: "Profile configuration is missing for: default" in headless mode

### ISSUE THREAD

**Issue by diondree** [aws-amplify/amplify-cli#4782]
**Describe the bug**
I'm getting the following error when running amplify init from CodeBuild in headless mode despite the fact that I set the useProfile option to false:

```bash
--
169 | Error: Profile configuration is missing for: default
170 | at Object.getProfiledAwsConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/system-config-manager.js:82:11)
171 | at loadConfigurationForEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:518:45)
172 | at Object.loadConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:499:24)
173 | at Object.aws.configureWithCreds (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:18:45)
174 | at Object.getConfiguredAWSClient (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:60:13)
175 | at getS3Client (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:13:30)
176 | at uploadFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:19:28)
177 | at uploadAuthTriggerFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-auth-trigger-files.js:7:11)
178 | at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:74:11)
179 | at process._tickCallback (internal/process/next_tick.js:68:7)
180 | ✖ An error occurred when pushing the resources to the cloud
181 | ✖ There was an error initializing your environment.
182 | init failed
183 | Error: Unable to upload trigger files to S3
184 | at uploadFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:49:11)
185 | at process._tickCallback (internal/process/next_tick.js:68:7)
--
```

I noticed this issue was [reported previously](https://github.com/aws-amplify/amplify-cli/issues/3292#issuecomment-585108812) but I'm not sure if it was resolved. 

**Amplify CLI Version**
I'm using version 4.22.0

**To Reproduce**
When my build process is triggered, a step in my buildspec runs this bash script
```bash
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"useProfile\":false,\
\"accessKeyId\":$AWS_ACCESS_KEY_ID,\
\"secretAccessKey\":$AWS_SECRET_ACCESS_KEY,\
\"region\":\"us-east-1\"\
}"

AMPLIFY="{\
\"projectName\":\"dpportal\",\
\"envName\":\"staging\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes

amplify push
```

The weird thing is that the amplify init process begins to run and suddenly fails during unlike when the profile is missing where it fails at the start.

**Expected behavior**
I expected the amplify init command to configure the container environment to be able to deploy to the resources.

**Container Environment**
Current environment image: aws/codebuild/nodejs:10.14.1

**Comment by diondree** [comment]
I also just tried again using the latest released version and this issue still occurs.

**Comment by jpignata** [comment]
Hi @diondree! I suspect your JSON might not be correct. Are you expecting those to come from the environment? Please verify they are configured, and I believe you may need to wrap the strings in double quotes.

**Comment by diondree** [comment]
@jpignata The credentials seem fine since i believe if the credentials were not configured correctly the init process would not start. To add more context, a few resources are updated before it eventually fails and gives the above error. So the issue occurs during the process.

I'll test the changes to the JSON to confirm its as it should.

**Comment by jpignata** [comment]
Hmm. Can you humor me and wrap them in quotes? Perhaps I’m wrong, but it doesn’t seem like the above would output valid JSON.

**Comment by diondree** [comment]
Thats what I meant, I would test adding quotes but I know that they are present in the environment

**Comment by diondree** [comment]
@jpignata Ah yes that seemed to have did the trick. Thank you very much for the help.

**Comment by jpignata** [comment]
HOORAY! No worries.
