### ISSUE TITLE
headless mode --app option usage: How do I reference a GitHub repository URL  ?

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#4783]
I'm trying to pre-cofigure my backend in a headless script (app, auth, function) so that I can recreate an app by running a init script.

The documentation on this, found [here](https://docs.amplify.aws/cli/usage/headless#--app) states that:

> --app
Installs, initializes, and provisions resources for a sample amplify application from the provided GitHub repository 

But how to reference or provide the repository URL seems not to be documented. No examples exists either.

**Which Category is your question related to?**
api, auth, function

**Amplify CLI Version** 
4.23.0

**What AWS Services are you utilizing?**
Amplify CLI

**Provide additional details e.g. code snippets**
https://docs.amplify.aws/cli/usage/headless#--app

**Comment by jhockett** [comment]
The URL should follow the flag: `amplify init --app git@github.com:<github-username>/<repository-name>.git`

I'll look into adding this to our docs so it's clear what is expected.

**Comment by kjetilge** [comment]
Thanks!😃👍

**Comment by kjetilge** [comment]
It seems not to be working. I an error:
```
./init.sh 
Note: Amplify does not have knowledge of the url provided
Invalid remote github url
```

In my script I have:
```
amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes \
--app git@github.com:kjetilge/ffb5AppCreate.git
```

I tried to make the repo public, but that didn't help.
