### ISSUE TITLE
[request] `ls` command for functions and APIs

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4784]
**Is your feature request related to a problem? Please describe.**

it can be hard to find the functions and API paths already available - would be nicer to just list it in a CLI command

**Describe the solution you'd like**

- `amplify function ls`
- `amplify api ls`

**Describe alternatives you've considered**

have users dig thru json files to figure it out

**Comment by sw-yx** [comment]
tagging @dabit3

**Comment by brene** [comment]
@sw-yx this works today with `amplify status` is there a reason you prefer `ls`?

**Comment by dabit3** [comment]
@brene `status` does indeed list the functions, but I think the main ask here is surfacing the API endpoints and the paths associated with each endpoint.

**Comment by sw-yx** [comment]
what he said. basically if i need to use it in my code (eg `API.get` https://github.com/aws-amplify/docs/issues/1969 ) then i'd like to pull it up easily without digging thru a pile of json and nested folders

**Comment by shabab477** [comment]
Agree with @sw-yx . This command will be of good help. Usually I name API-s with `*Api` and Lambdas with `*Lambda` and do a grep with status command: `amplify status | grep "Lambda"`

**Comment by josefaidt** [comment]
Closing as this has since been released. To list statuses for functions or other categories, run `amplify status function` or `amplify status <category>`
