### ISSUE TITLE
Revert the pushed changes in amplify-cli.

### ISSUE THREAD

**Issue by SurajPandey186** [aws-amplify/amplify-cli#4792]
Well, the actual scenario is that in amplify->api->**"schema.graphql"** file in my client app was actually was outdated and there was a modification in the graphql schema at the server via AppSync service, now when I added a new category that is **analytics** and then pushed this change, the old schema was deployed over the cloud. So, I just wanted to revert the push in amplify cli. 

Amplify Cli Version:- 4.22.0
Os: Windows 10

**Comment by jhockett** [comment]
Hi @SurajPandey186, I want to make sure I'm understanding correctly. Was the change to the schema made in the AppSync console?

Also, do you have the schema changes that you want to preserve saved somewhere?

**Comment by SurajPandey186** [comment]
Yes @jhockett, the change was made directly in AppSync console. No, basically the developer who made the changes do not have that changed state of schema that he changed manually in AppSync

**Comment by SurajPandey186** [comment]
Hi @jhockett, I am waiting for your response.

**Comment by jhockett** [comment]
@SurajPandey186 unfortunately, there's nothing that can be done from the CLI to recover the changes made in the Console. In the future, I highly recommend committing schema changes to version control.

The CLI doesn't have knowledge of changes in the backend if you don't use `amplify pull` first. See: https://docs.amplify.aws/cli/start/workflows#amplify-pull

Also, you may find the docs regarding team workflows useful: https://docs.amplify.aws/cli/teams/overview

**Comment by otsnaval** [comment]
Thanks @jhockett  for the response.

**Comment by SurajPandey186** [comment]
Thanks, @jhockett, I have gone through docs earlier, but still, I thought there could anyway.

**Comment by jhockett** [comment]
Closing this issue, but feel free to comment below if you have further questions related to this issue.
