### ISSUE TITLE
Access Environment Variables in AppSync Resolver

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#4804]
**Which Category is your question related to?**
AppSync

**Amplify CLI Version** 
4.22.0

**Provide additional details e.g. code snippets**
Is there any way that I can get access to the apiId and the environment name in a velocity resolver? I'm trying to do a transactional request in VTL which requires me to specify the table name, and since I am using multiple environments, the table name is only known at run time. I suspect that these variables might be baked into $ctx, but I can't find any documentation supporting that idea. 

Any help is appreciated

Edit: It looks like others have run into the same issue (#1774 #2092). There is also a proposed workaround (#1946). And finally it seems like someone has tried to implement a solution (#2539). Can anyone on the Amplify team confirm that this issue has been resolved? Or is the proposed workaround the accepted solution?

**Comment by nathanqueija** [comment]
Hello, is there any update on when this will be released? Thanks

**Comment by SwaySway** [comment]
Closing this in favor of #1774 to provide visibility please follow that thread for updates.
