### ISSUE TITLE
Status of Hosting category is always 'Create' when using CI/CD.

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-cli#4805]
**Describe the bug**
Hosting category always have 'Create' status when using CI/CD configuration, no matter how many times you execute `amplify push`.

Additionally, `./amplify/backend/hosting` directory only contains an 'amplifyhosting' empty directory.

Weirdly, Amplify CLI uses that directory to determine if hosting has been configured from CLI (If you delete the 'hosting' directory and execute `amplify hosting update` it will tell you that hosting has not been configured from CLI but from the Amplify console).

**Amplify CLI Version**
4.24.0

**To Reproduce**
`amplify init`
`amplify hosting add`
`> Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment) `
`amplify push` (at least two times)

**Expected behavior**
Hosting category to have 'No Change' status on successive `amplify status` or `amplify push` executions.

**Screenshots**
<img width="567" alt="Screen Shot 2020-07-11 at 13 05 44" src="https://user-images.githubusercontent.com/34403992/87222824-98c82700-c377-11ea-840e-3590c7d187fb.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Node Version: 14.4.0

**Additional context**
None.

**Comment by ernestostifano** [comment]
Additional note: Executing `amplify pull` when there is no changes other than `Hosting` will make the process hang on `Fetching updates to backend environment: dev from the cloud.
`

<img width="568" alt="Screen Shot 2020-07-11 at 13 37 51" src="https://user-images.githubusercontent.com/34403992/87223299-ecd50a80-c37b-11ea-95f2-3679e8c5a2fa.png">

**Comment by ernestostifano** [comment]
This issue persists in v4.25. It disappeared for some time, after deleting and re-initializing my Amplify App, but now it has appeared again after adding a secondo backend environment from CLI. I also disconnected a branch and connected it again from the Amplify console, but I'am not sure of exactly when the issue appeared again.

**Comment by mbecker** [comment]
Hi,

same here. For me it appears all the time.

**Comment by cameronrr** [comment]
+1 same as above. After too much time trying to resolve this, it must be a bug. 
For now, will just treat 'create' on category hosting as meaning there is nothing to do.

**Comment by cameronrr** [comment]
Looks like the issue is that `lastPushTimeStamp` doesn't get set for category `"hosting"` with option `"Hosting with Amplify Console"` (i.e. in amplify/backend/amplify-meta.json). 

This is presumably because there is nothing to be pushed via the CLI as this hosting option is managed directly in the Amplify Console web interface. Since there is no `lastPushTimeStamp` it is always considered as having never been pushed, therefore needing to be 'created'.

Probably need some special handling surrounding resources which require no 'push' such as in this case. While the `lastPushTimeStamp` could simply be set, this is a bit misleading where no change has been pushed. Probably better to track the plugin has no configuration required and provide the status accordingly (i.e. 'Not Applicable' or simply 'No Change').

Interestingly though, amplify/#current-cloud-backend/amplify-meta.json does contain a `lastPushTimeStamp` for hosting, and so there is inconsistency between the local and cloud configuration due to this.

**Comment by martinbiard** [comment]
I'm also seeing this issue. The empty `amplify/backend/hosting/amplifyhosting` is particularly problematic because it doesn't get recreated on fresh git clones. My temporary fix is to make it a file, since the check is an `fs.exists`.

```sh
rm -rf amplify/backend/hosting/amplifyhosting
touch amplify/backend/hosting/amplifyhosting
```

**Comment by geoseong** [comment]
+1 same situation for me.

sometimes I resolved to do like
```
$ amplify pull --appId {appId} --envName {envName}

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use {awsprofile}
Amplify AppID found: {appId}. Amplify App name is:{AmplifyAppName}
Backend environment prod found in Amplify Console app: {AmplifyAppName}
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start

? Do you plan on modifying this backend? Yes  # <-- look at this carefully. choose "Yes"

Successfully pulled backend environment {envName} from the cloud.
Run 'amplify pull' to sync upstream changes.

$ amplify status

Current Environment: {envName}

| Category | Resource name                        | Operation | Provider plugin   |
| -------- | ------------------------------------ | --------- | ----------------- |
| Hosting  | amplifyhosting                       | Create    |                   |
| Auth     | kendrabuttonhosting___               | No Change | awscloudformation |
| Function | kendrabuttonhosting____PreSignup     | No Change | awscloudformation |
```
after doing this,
```
$ amplify pull

Pre-pull status:

Current Environment: prod

| Category | Resource name                        | Operation | Provider plugin   |
| -------- | ------------------------------------ | --------- | ----------------- |
| Hosting  | amplifyhosting                       | Create    |                   |
| Auth     | kendrabuttonhosting___               | No Change | awscloudformation |
| Function | kendrabuttonhosting____PreSignup     | No Change | awscloudformation |

Local changes detected.
Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✔ Successfully pulled backend environment prod from the cloud.


Post-pull status:

Current Environment: {envName}

| Category | Resource name                        | Operation | Provider plugin   |
| -------- | ------------------------------------ | --------- | ----------------- |
| Hosting  | amplifyhosting                       | No Change |                   |
| Auth     | kendrabuttonhosting___               | No Change | awscloudformation |
| Function | kendrabuttonhosting____PreSignup     | No Change | awscloudformation |
```

but sometimes no luck.

Which point can I check this is "Create" Operation state or not? I have no clue!

**Comment by UnleashedMind** [comment]
If you went through these steps: 
amplify add hosting -> Amplify Console -> Continuous deployment (Git-based deployments)
The CLI will open up the Amplify Console webpage, and you will connect to your Github project there, once that's done, come back to your  local dev terminal, and hit enter. 
I'm not able to reproduce the issue with the latest CLI version though. If you somehow get into this situation, you can run `amplify pull --restore` to get synchronized and consistent amplify status report in your local environment.
