### ISSUE TITLE
Can we add permissions to layer function like we do with regular functions (via CLI)

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-cli#4808]
When creating a function the CLI prompts if you want to provide the function access to other resources. This does not occur when creating a layer function. Is there any way to set permissions on a layer function?

 My goal is to create a layer with permissions to access app sync that handle all the queries / mutations to my API from one lambda. 

**Which Category is your question related to?**
functions

**Amplify CLI Version** 
4.23.1

**Comment by waltermvp** [comment]
do i just have to add the permissions to the non layer function using it?

**Comment by jhockett** [comment]
Hi @waltermvp Lambda layers do not have any flow for adding permissions, and it's outside the scope of their current design in the CLI. I also do not think it would help prevent a circular dependency, since the function depends on the Lambda layer.

**Comment by MontoyaAndres** [comment]
Hey, @waltermvp I could fix it in another way, by just creating a new lambda, adding the permissions I need to this one. Then I take the post-confirmation lambda and I give access to this one to execute the other lambda. You can do this by adding:

https://github.com/aws-amplify/amplify-cli/issues/663

**Comment by waltermvp** [comment]
Yep, that seems to be the best way forward, got it working ok. Thank you @MontoyaAndres  + @jhockett
