### ISSUE TITLE
How to have public query with cognito authentication

### ISSUE THREAD

**Issue by CaptainChemist** [aws-amplify/amplify-cli#4810]
**Which Category is your question related to?**

Appsync + Cognito

**Amplify CLI Version** 

4.12.0

**What AWS Services are you utilizing?**

Appsync, Cognito, DynamoDB, 3 lambda functions that have read/write permissions on my DynamoDB table using iam.

**Provide additional details e.g. code snippets**

I have a query `listproducts` that needs to be publically accessible (its a @function). I am seeing the behavior that the query loads perfectly when the user is logged in but I get a `UnauthorizedException- Valid authorization header not provided.` error when I'm not logged in. 

```gql
type Product {
  id: ID!
  name: String!
  // many other fields
}

type UserCourse
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Admin"] }
      { allow: owner, operations: [read] }
      { allow: private, provider: iam, operations: [create, read] }
    ]
  ) {
  id: ID!
  owner: String
  currency: String
  source: String
  amount: Int
  courseId: String
  invoice: String
}

type Query {
  listproducts: [Product] @function(name: "courseslistproducts-${env}")
}

type Mutation {
  enroll(courseId: String, priceId: String, source: String): UserCourse
    @function(name: "coursesenroll-${env}")
}
```

How can I best annotate my graphQL file and make edits to my amplify configuration to fix this problem? I'd ideally just like to put some sort of `@auth()` transform on the `listproducts` line but I think that might not bee supported. I've tried enabling 'allowUnauthenticatedIdentities' using the aws-cli but I can't actually tell if that is doing anything. It does create an unauthrole for me but when I manually give it permissions to the `listproducts` query that doesn't seem to help so I think I'm missing something.

I'm using this with `AWSAppSyncClient`, so I have seen others selectively either log in using an API key or cognito based on whether they are logged in (see code example below). I know I could do this using the API keys but I wasn't sure if there was an easier way with cognito since there is the `allowUnauthenticatedIdentities` setting and it seems like that setting isn't being used when I use API keys. Thanks so much! 

```

export default function App(props) {
  const [client, setClient] = useState(null)

  useEffect(() => {
    checkAuth()
  }, [])

  function checkAuth() {
    Auth.currentSession()
      .then(session => {
        const jwtToken = session.getAccessToken().getJwtToken()
        if (typeof jwtToken == 'string') {
          const client = new AWSAppSyncClient({
            url: awsConfig.aws_appsync_graphqlEndpoint,
            region: awsConfig.aws_appsync_region,
            auth: {
              type: awsConfig.aws_appsync_authenticationType,
              jwtToken: jwtToken ? jwtToken : null,
            },
            fetch,
            disableOffline: true,
          })
          setClient(client)
        } else {
          throw 'error'
        }
      })
      .catch(e => {
        console.log(e)
        const client = new AWSAppSyncClient({
          url: awsConfig.aws_appsync_graphqlEndpoint,
          region: awsConfig.aws_appsync_region,
          auth: {
            type: AUTH_TYPE.API_KEY,
            apiKey: awsConfig.aws_appsync_apiKey,
          },
          disableOffline: true,
          offlineConfig: {
            keyPrefix: 'public',
          },
          fetch,
        })
        setClient(client)
      })
  }

  if (!client) {
    return 'Loading...'
  }

  return <ApolloProvider client={client}>{props.children}</ApolloProvider>
}
```

**Comment by SwaySway** [comment]
> Appsync, Cognito, DynamoDB, 3 lambda functions that have read/write permissions on my DynamoDB table using iam. 

If you default mode of auth is IAM then to specify the query with `@function` you can either annotate it with `@auth(rules: [{ allow: public, provider: userPools }]` or `@aws_cognito_user_pools` to indicate that you can query that operation using userPool based auth
