### ISSUE TITLE
Why is 'COGNITO' in the app client's providerList hard-coded in OAuthCustomResource Lambda Function?

### ISSUE THREAD

**Issue by tmizuma** [aws-amplify/amplify-cli#4811]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Auth

**Amplify CLI Version** 

4.21.3

**What AWS Services are you utilizing?**

Cognito

**Provide additional details e.g. code snippets**

Looking at the code below, it looks like the app client provider will always be given a Cognito User Pool.
This code gets in the way if you want to allow authentication to external providers only.
I have removed this part of the code in the interim to address this.
I think the best thing to do is to remove the Cognito User Pool as a valid provider in the Amplify CLI options.

Is this idea correct?

https://github.com/aws-amplify/amplify-cli/blob/21de1affd89142598a1f8022c387b3c04994b1e0/packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs#L696

**Comment by UnleashedMind** [comment]
You are correct, Cognito is a default provider for the OAuth workflow. 
I'm not sure I agree with you that we should remove it though, this provides a convenient way for frontend developers to setup the OAuth in their project in a one-stop shop fashion, you don't have to pause the current work to setup Facebook or Google before continue the auth development. And when third party providers are setup, you can come back and update the OAuth providers in your project.
This does not in any way force your project to use Cognito as a provider (although it's setup), you can customize your UI to only link to the other providers in the sign in workflow.
