### ISSUE TITLE
amplify init --app <gitHubUrl> errors with: Amplify does not have knowledge of the url provided Invalid remote github url

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#4812]
It seems not to be working. I get an error:

./init.sh 
Note: Amplify does not have knowledge of the url provided
Invalid remote github url

In my script I have:

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes \
--app git@github.com:kjetilge/ffb5AppCreate.git

I tried to make the repo public, but that didn't help.

**Comment by ammarkarachi** [comment]
@kjetilge I tried running `amplify init --app git@github.com:kjetilge/ffb5AppCreate.git` and it was successful in cloning the repo but it failed running npm install because of the extra ',' in https://github.com/kjetilge/ffb5AppCreate/blob/2f36c9b357aece0050bbb3a8176215cc3f96608d/package.json#L9

**Comment by kjetilge** [comment]
I’ll beware of the commas from now on 🤓

**Comment by ammarkarachi** [comment]
Haha no problem. Don't hesitate to reopen if you run into more issues
