### ISSUE TITLE
Trying to add @auth to @function

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#4814]
I'm trying to add @auth to @function because I want to make this function with public access, so I tried to do it like this:

```
type Query {
  myCustomQuery(email: String!, title: String!, message: String!): String
    @auth(rules: [{ allow: public, provider: iam }])
    @function(name: "mycustomfunction-${env}")
}
```

But when I execute the command `amplify push` I get this error:

```
UPDATE_FAILED               authlogitoolwebapp0b2aa0ea        AWS::CloudFormation::Stack Mon Jul 06 2020 14:00:07 GMT-0500 (Colombia Standard Time) Parameters: [unauthRoleName, authRoleName] do not exist in the template
```

And I could [fix it](https://github.com/aws-amplify/amplify-cli/issues/2519#issuecomment-539402222) by going to the route `backend/api/MY_API/parameters.json` and adding:

```
"authRoleName": {
    "Ref": "AuthRoleName"
},
"unauthRoleName": {
    "Ref": "UnauthRoleName"
}
```

Is there another way to do this? I'd like to add a function and change the Authorization access, I found this [issue](https://github.com/aws-amplify/amplify-cli/issues/2701), but it's something that does not exist on the docs, I guess... Maybe is there an alternative to this? 

**Expected behavior**
Allow adding @auth to a @function without problems...

**Comment by SwaySway** [comment]
Closing as this issue is fixed in the latest version of the CLI. Should you experience this issue again please comment below.

**Comment by MontoyaAndres** [comment]
Yep, it's fixed 💯
