### ISSUE TITLE
Overwrite CLI Generated Cloudformation Stack

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#4815]
**Which Category is your question related to?**
AWS CloudFormation

**Amplify CLI Version** 
4.22.0

**Provide additional details e.g. code snippets**
Is there any way to overwrite one of the CloudFormation templates generated by the CLI for one of my graphql models? In amplify/api/myapi/build/stacks have a User.json CloudFormation template that I would like to edit. I figured I could just add changed to amplify/api/myapi/stacks and the changes would be picked up (as with overwriting a CLI generated resolver), but when I do so I get an error.

**Comment by UnleashedMind** [comment]
What's the error that you got?

**Comment by karrettgelley** [comment]
@UnleashedMind A very generic "stack is not in the state update complete"

**Comment by UnleashedMind** [comment]
Do you have multiple custom stacks and they there are dependency relationships between them? you might need to add the "DependsOn" attribute to make sure they are created/updated in the right sequence.

**Comment by karrettgelley** [comment]
@UnleashedMind Thanks. I figured it out. Closing
