### ISSUE TITLE
Filters not generated for owner field in model

### ISSUE THREAD

**Issue by mtltechtemp** [aws-amplify/amplify-cli#4818]
Everything is in the title.

I tried to add the owner field explicitly but then the onCreate and onUpdate subcriptions fails.

Is this normal?
```
    filter: {
          owner: { eq: this.stateUser.id }
        }
```
Error:
```
"The variables input contains a field name 'owner' that is not defined for input object type"
```

**Comment by UnleashedMind** [comment]
How did you define your schema? 
Please also provide the following information: 
CLI version
OS

**Comment by mtltechtemp** [comment]
> How did you define your schema?
> Please also provide the following information:
> 
> * CLI version
> * OS

CLI version:
```bash
➜  ~ amplify --version
4.24.0
```

OS:
```bash
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

Schema:
*I made a minimal example based on the doc that reproduces the error and uses the same authentication rules as in my schema.*
```gql
type Blog
  @model
  @auth(
    rules: [
      # Admin users can access any operation.
      { allow: groups, groups: ["Admin"] }
      # Authorize create, update, read.
      { allow: owner, operations: [create, update, read] }
      # Authorize access via API key.
      { allow: public, provider: apiKey }
    ]
  ) {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}

type Post
  @model
  @auth(
    rules: [
      # Admin users can access any operation.
      { allow: groups, groups: ["Admin"] }
      # Authorize create, update, read.
      { allow: owner, operations: [create, update, read] }
      # Authorize access via API key.
      { allow: public, provider: apiKey }
    ]
  ) {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}

type Comment
  @model
  @auth(
    rules: [
      # Admin users can access any operation.
      { allow: groups, groups: ["Admin"] }
      # Authorize create, update, read.
      { allow: owner, operations: [create, update, read] }
      # Authorize access via API key.
      { allow: public, provider: apiKey }
    ]
  ) {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
It really annoys me in my use case because I have a user group that has the admin group and that has access to everything and it screws up my queries as I can't filter by owner.
It's really something basic I didn't expect to have this problem at all.

It looks like it has something to do with #300 
I hope we can solve this problem quickly.

**Comment by mtltechtemp** [comment]
ping @UnleashedMind

**Comment by mtltechtemp** [comment]
@UnleashedMind ?

**Comment by UnleashedMind** [comment]
I tested with the latest version 4.29.x, and the issue seems to be resolved already. 
With the annotated schema that you provided, the owner field is added into to the compiled schema by the Amplify CLI. 
Please test and confirm.
