### ISSUE TITLE
Is amplify CLI support conditional BuildCommand?

### ISSUE THREAD

**Issue by juunone** [aws-amplify/amplify-cli#4829]
**Which Category is your question related to?**
amplify CLI BuildCommand

**Amplify CLI Version** 
`3.17.0`

**Provide additional details e.g. code snippets**
I want to deploy to CloudFront with amplify CLI
i have amplify/project-config.json in my project

```
{
  "projectName": "codelion-front",
  "javascript": {
    "framework": "react",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "build",
      "BuildCommand": "yarn build",
      "StartCommand": "yarn start"
    }
  },
  "providers": ["awscloudformation"],
  "frontend": "javascript",
  "version": "3.0"
}

```

i have deploy with github-actions in this package [amplify-cli-action](https://github.com/marketplace/actions/amplify-cli-action).
i need to conditional BuildCommand
e.g. `build:dev` `build:stg` like this.
how do i configure with conditional buildcommand in one project-config.json

**Comment by UnleashedMind** [comment]
You can save your custom build script to a file, and add the invocation logic into the `package.json` file, e.g.

```json
{
  
  "scripts": {
    
    "mybuild": "node ./path-to-the-script-file",
    
  }
}
```

The build command is then `"yarn mybuild"`

**Comment by juunone** [comment]
hi thanks to answer.
actually i want to conditional `project-config.json`
because i want to build another command in `project-config.json`

e.g.

```
"BuildCommand": "yarn build:dev",
or
"BuildCommand": "yarn build:stg",
```

**Comment by UnleashedMind** [comment]
The CLI does not provide that out of the box, it simplify invoked the build command before publish, you will have to write your own custom build command for that purposes.

**Comment by juunone** [comment]
ok thank you for answer!
