### ISSUE TITLE
No option to import existing Lex chatbot in CLI interactions 

### ISSUE THREAD

**Issue by mobilequickie** [aws-amplify/amplify-cli#483]
**Describe the bug**
Amplify CLI version 0.1.33

Issue: When adding a chatbot using the Amplify CLI via 'amplify add interactions' there's no option to import an existing chatbot even though, the wizard implies this option exists.

Reproduction:
> amplify add interactions
Using service: Lex, provided by: awscloudformation
Welcome to the Amazon Lex chatbot wizard
You will be asked a series of questions to help determine how to best construct your chatbot.

? Provide a friendly resource name that will be used to label this category in the project: **bot2**
? Would you like to start with a sample chatbot, import a chatbot, or start from scratch?

Result:
Only options are sample chatbot or start from scratch. Even though it asks, there's no prompt for "import a chatbot".

**Comment by kaustavghosh06** [comment]
@mobilequickie We're managing the resources by Cloudformation as a part of the Amplify CLI and Cloudformation service doesn't support managing resources created outside Cloudformation, so currently you won't be able to import an existing AWS resource for any of the categories and manage it via the CLI (using Cloudformation). This said we're planning to write another provider in the future which is Cloudformation independent and makes service API calls.

**Comment by arvidlarzzon** [comment]
Is it not possible to acheive this through some other way? I can't seem to find a guide describing how to connect my project to my existing lex chat bot.

**Comment by jihadrhamza** [comment]
is this feature available?

**Comment by jihadrhamza** [comment]
Can someone please update on this ? Am trying to use the existing bot in to mobile app using amplify cli. But cannot use other than default sample projects.

**Comment by saurabhpati** [comment]
I have the same feature request. I want to use the interactions module but I have an already existing bot on aws lex and there is no way for me to import that bot and its configurations.

**Comment by renebrandel** [comment]
Hi all, sorry for late reply on this thread. In order to use an existing Chatbot, you can follow the guidance here: https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js#manual-setup we don't support a CLI workflow to import a chatbot. The string was erroneous and will be modified in #4908
