### ISSUE TITLE
amplify init on WSL 2 Ubunutu gives error: uncaughtException: spawn cmd.exe ENOENT 

### ISSUE THREAD

**Issue by mikevanderveer** [aws-amplify/amplify-cli#4832]
**Which Category is your question related to?**
Amplify init, it seems to not be able to launch a brower pointing to the aws console. 

**Amplify CLI Version** 
4.24.1

**What AWS Services are you utilizing?**
Amplify

**Comment by UnleashedMind** [comment]
Seems like the CLI is trying to set up the local configuration for aws access. 
Can you run the Amplify CLI command directly on Windows cmd.exe or powershell?

**Comment by mikevanderveer** [comment]
@UnleashedMind well, while trying to install everything to run on powershell, I had to reboot. Then I tried again on the wsl 2 Ubuntu and it mosty worked. I didn't use sudo and it appeared to pump everything up to aws, creating a cloudformation stack etc, but it failed to write to my local drive. We shall see if I can get this thing running. 
Thanks for the help.

**Comment by UnleashedMind** [comment]
are you still blocked?

**Comment by mikevanderveer** [comment]
@UnleashedMind sorry, i should have posted earlier that the issues seemed to be caused by nodejs v 14...
I tried nodejs v12.18.2 LTS and things have been running smoothly ever since. 
Thanks for cheching up.

**Comment by UnleashedMind** [comment]
We'll investigate more on this
