### ISSUE TITLE
Amplify Publish - BadRequestException: Operation not supported. App is already connected a repository.

### ISSUE THREAD

**Issue by charleslouis** [aws-amplify/amplify-cli#4837]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

It is potentially linked to both CLI and Console in my opinion. 
See below.

**Describe the bug**

On the CLI : Publishing Manually `amplify publish` ends up with `Operation not supported. App is already connected a repository.` despite having run `amplify hosting remove` and `amplify hosting add` again with option "Manual"

**Amplify CLI Version**

4.24.1

**To Reproduce**
Here is the course of events:
- manually add CI/CD with Gitlab repo on console
- CI/CD fails for some reasons on the backend build due to `auth headless is missing the following inputParams facebookAppIdUserPool` (while `amplify push` goes fine) 
- Then tried to `amplify publish` (Backend works - I just need to deploy frontend) -> fails due to CI/CD setup from console 
- Tried to reconnect / disconnect repo from console with no avail
- ran `amplify hosting remove` then `amplify hosting add` to go back to manual 
- ran `amplify publish` ->  ends up with `Operation not supported. App is already connected a repository.`

On the console side, it says "Repository is already connected to another app".
But I see no other app (deleted all older apps).

It is not possible to select a branch (see screenshot) - even if I select another repo.

**Expected behavior**

on CLI being able to run `amplify publish` if in manual mode
OR on console being able to (re)implement CI/CD 
OR is there a way to disconnect repo ?
OR is there a way to reconnect repo AND branch (I can select the repo, put the branches dropdown is empty)
OR is there a good way to clone my repo and init a new amplify app just to deploy frontend ?

In any way, I just want to publish the frontend without having to start the whole stack from scratch (again). 
At least not at the moment. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2117081/87506127-3d49b200-c673-11ea-8b41-2ddb842850e9.png)

![image](https://user-images.githubusercontent.com/2117081/87506486-12139280-c674-11ea-817a-d632d98b9edb.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version v12.8.0

**Additional context**

In any way, I just want to publish my app without having to start the whole stack from scratch (again).

If you can recommend a way to duplicate my app so I can start again but without having to rebuild the backend, please share it and I'll go this way.

There are big frustrations as I face "stupid" issues while being very close to launching.
This is one. Last week I had to rebuild the whole stack upon deploy as well.
But still I really enjoy amplify and when it goes well it's great. 
It's really good to see all the progress made in a year! 
Thank you all for all the good work 🙏

**Comment by abhi7cr** [comment]
Hi @charleslouis,

When an amplify backend is configured with social credentials (client id and secrets), the credentials need to be supplied as environment variables in Amplify Console, in order for the CLI pull command to succeed. We released this fix last week in order for the builds to succeed consistently (previously it was only succeeding the first time) when social creds are enabled in the auth category. You can check this [comment](https://github.com/aws-amplify/amplify-cli/issues/4790#issuecomment-656422252) to see how to add the env variables, and this [comment](https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-657013051) to see what the fix entails.

Let me know if you have any questions.

**Comment by charleslouis** [comment]
Hi @abhi7cr,

Great that the fix has been released already and thanks for following promptly.
I can confirm this issue is gone 👌

On another note :
- I had to 'nvm use $VERSION_NODE_12' to my build settings to fix a memory leak upon build with yarn
It worked.

I now I face `ResourceNotReady: Resource is not in the state stackUpdateComplete`.

**Comment by charleslouis** [comment]
Update:

I proceeded to backup the tables and remove / add back GraphQL API.
The build passes now.
