### ISSUE TITLE
[usage question] `amplify storage update` - tell me more about whether i should overwrite cloudformation-template.json

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4839]
**Which Category is your question related to?**
storage

**Amplify CLI Version** 

4.24.0

**What AWS Services are you utilizing?**
dynamodb

**Provide additional details e.g. code snippets**

when i do `amplify storage update`, 

![image](https://user-images.githubusercontent.com/6764957/87550228-69038100-c6e1-11ea-9ce9-f6672e7adee6.png)

it asks me whether i want to overwrite `MYTABLE-cloudformation-template.json` - i have no idea, and it is not documented - please help me figure out if i want to do it? 

the default says no, but intuition says yes. which is it?

**Comment by dabit3** [comment]
Yeah, agree on this that it's confusing. This looks like it would be a good "First task" for someone looking to contribute if we can provide guidance here on what the information should be.

**Comment by UnleashedMind** [comment]
Agree that this is confusing. 
It meant to ask you if you want to update the CloudFormation template with the changes from the proceeding prompts.
I will mark this as an enhancement, our team will discuss on how to improve the UX.

**Comment by dabit3** [comment]
Thanks @UnleashedMind

**Comment by sw-yx** [comment]
for what its worth also, i could not find this in the docs anywhere. but CLI UX is first. its just that we should think about docs next after we fix the core exp

**Comment by sw-yx** [comment]
@UnleashedMind while you are at it, i would also recommend defaulting the "do you want to set up a GSI" question to no since that is the right answer most of the time

**Comment by josefaidt** [comment]
Closing as this issue has since been resolved, and the CLI no longer prompts for okay to overwrite.
