### ISSUE TITLE
Custom portions of an awsconfiguration.json file

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#484]
** Which Category is your question related to? **
Android / iOS

** What AWS Services are you utilizing? **
Kinesis Video, Polly, Kinesis

** Provide additional details e.g. code snippets **
If I needed to add custom portions to the awsconfiguration.json file for services that are not currently supported by the CLI, then these would be overwritten and lost when the CLI updates this file.

**Comment by undefobj** [comment]
This is being tracked already: https://github.com/aws-amplify/amplify-cli/issues/419
Closing duplicate.
