### ISSUE TITLE
Adding permission to a s3 bucket that's external to your app

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4859]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

I want to attach s3 permission for an s3 bucket that's external to your app. Currently, there seems to be no way of doing this other than to edit the cloud formation template directly and then add it there, but I think it may not be the best way because that template is also being updated/modified by Amplify, when I tried to add the s3 permission like so:

1. Add the following entry to `Parameters` on `func-cloudformation-template.json`.

```
"legacyS3Arn": {
  "Type": "String",
  "Default": "arn:aws:s3:::my-legacy-s3"
}
```

2. Add the following entry on the `AmplifyResourcePolicy` on the s3 policy

```
{
  "Effect": "Allow",
  "Action": [
    "s3:PutObject",
    "s3:GetObject",
    "s3:ListBucket",
    "s3:DeleteObject"
  ],
  "Resource": [
     // other resource added by amplify
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:s3:::",
          {
            "Ref": "legacyS3Arn"
          },
          "/*"
        ]
      ]
    }
  ]
}
```

Then I did `amplify update function` because I forgot to add permission to another s3 bucket, this time the s3 bucket is managed by Amplify so it can be added by doing `amplify update function`, but Amplify removed the entry that I entered in manually.

**Describe the solution you'd like**

hmmm... maybe a command or option to `amplify update function` that will ask devs `Do you want to attach permission to a resource not managed by Amplify?`.

**Describe alternatives you've considered**

N/A

**Additional context**

This might not just be for s3, it could also be for other resources external to your app.

**Comment by goatandsheep** [comment]
change the storage value in your `aws-exports.js`

**Comment by josefaidt** [comment]
Closing in favor of [`custom-policies.json`](https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function) to add additional permissions to functions within your Amplify project.
