### ISSUE TITLE
Attaching custom policies

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#486]
** Which Category is your question related to? **
Android / iOS

** What AWS Services are you utilizing? **
Kinesis Video, Polly, Kinesis, IoT

** Provide additional details e.g. code snippets **
If I use the Amplify CLI to configure my identity pool, then attach a custom policy to that identity pool, I risk losing the policy when updating something with the CLI.

**Comment by undefobj** [comment]
Related: https://github.com/aws-amplify/amplify-cli/issues/419

**Comment by kaustavghosh06** [comment]
@minbi We have a 3rdparty plugin for custom CFN templates which you can use (https://www.npmjs.com/package/amplify-category-template)
You can use the authRole and the unAuthRole as a `Ref` and then attach whatever policy you would like.
