### ISSUE TITLE
Provisioned Concurrency for Lambda Functions

### ISSUE THREAD

**Issue by jadenv** [aws-amplify/amplify-cli#4865]
**Which Category is your question related to?**
Functions

**Amplify CLI Version**
4.24.2

**What AWS Services are you utilizing?**
API + Functions

**Provide additional details e.g. code snippets**
Is there a way to configure Provisioned Concurrency for Lambda Functions within the amplify-cli as documented here?
https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/

The biggest issue seems to be that you can't allocate provisioned concurrency on an alias that points to the unpublished version ($LATEST), so not sure how that would work in the cloudformation template as I don't believe you can reference a published version, but maybe I'm wrong about that.

Either way, does anybody have an example of how to do this? Cheers 🍻

**Comment by grez72** [comment]
I have not tested this with provisioned concurrency, but if you are using the @function directive, you can specify a function name that includes an alias.

```
type Mutation {
  deleteComment(id: Int!): Comment @function(name:"lambdaResolver-${env}:<aliasName>")
}
```

e.g., for a "dev" alias
```
type Mutation {
  deleteComment(id: Int!): Comment @function(name:"lambdaResolver-${env}:dev")
}
```

It looks like lambda functions created with "amplify add function" automatically have the ${env} name suffixed to the function name, hence using the function name "lambdaResolver-${env}" before the alias. It would be nice if we could specify the environment name to be either a suffix or an alias (though perhaps there is a reason it must be used as a suffix).

You can also use the ${env} variable for the alias name with the @function directive.
```
type Mutation {
  deleteComment(id: Int!): Comment @function(name:"lambdaResolver-${env}:${env}")
}
```

So if your amplify env is "dev", the function being used would be: lambdaResolver-dev:dev

This wont automatically create the alias for you, you have to do that manually (e.g., in the lambda console), but you only have to do that once for a "dev" alias that points to $LATEST, and probably rarely for a "prod" alias that points to the most recently published version.

I can confirm that my "deleteComment" mutation is calling the alias when I set it up this way (I published a version, pointed the alias to the published version v1, modified $LATEST, and deleteComment called the v1 code pointed to by the alias. I then updated the alias to point to $LATEST and deleteComment was then pointing to the $LATEST updated code).

**Comment by UnleashedMind** [comment]
We don't provide this out of the box. 
I will mark this as en enhancement.

**Comment by dseeker** [comment]
Also looking for a solution using Amplify
@jadenv the serverless framework supports this by passing a single value in `provisionedConcurrency`, you may want to look how they do it.

**Comment by jadenv** [comment]
@dseeker thats exactly what I did :)

Until this is officially implemented in amplify-cli, I was able to modify my cloudformation template to include a version and alias that allows me to use provisioned concurrency like this:

```
{
  ...
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      ....
    },
    "LambdaVersion": {
      "Type": "AWS::Lambda::Version",
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "LambdaFunction"
        }
      }
    },
    "ProvisionedConcurrencyLambdaAlias": {
      "Type": "AWS::Lambda::Alias",
      "Properties": {
        "FunctionName": {
          "Ref": "LambdaFunction"
        },
        "FunctionVersion": {
          "Fn::GetAtt": [
            "LambdaVersion",
            "Version"
          ]
        },
        "Name": "provisioned",
        "ProvisionedConcurrencyConfig": {
          "ProvisionedConcurrentExecutions": 20
        }
      },
      "DependsOn": "LambdaFunction"
    }
  }
}
```

**Comment by tomhirschfeld** [comment]
@jadenv did you connect your lambda to API gateway at all? I'm having trouble here as API gateway doesn't integrate with the alias that has provisioned concurrency, it connects to "latest", not sure what changes i need to make here

**Comment by jadenv** [comment]
@tomhirschfeld yep, you will have to add `:provisioned` to the `uri` of the API CloudFormation template.

Ex:
```
{
  ...
  "uri": {
    "Fn::Join": [
      "",
      [
        "arn:aws:apigateway:",
        {
          "Ref": "AWS::Region"
        },
        ":lambda:path/2015-03-31/functions/",
        {
          "Ref": "functionlambdaArn"
        },
        ":",
        "provisioned",
        "/invocations"
      ]
    ]
  }
  ...
}
```

**Comment by poulter7** [comment]
@jadenv where in the standard amplify stack does this live? I see the cloudformation-template.json for api/graphql is auto-generated under the /build directory, I expect this gets overridden in each publish?

**Comment by poulter7** [comment]
Actually if one is looking to map into the alias from a graphql function I think you can simply pass the alias in the function name.
 This points to $Latest
`function(...): AWSJSON! @function(name: "function-${env}")`
This points to the provisioned alias you mentioned above.
`function(...): AWSJSON! @function(name: "function-${env}:provisioned")`

**Comment by arbermejo0417** [comment]
Hi @jadenv I tried a set up in cloudformation as you suggested for both the Function and API templates. The new resources were created correctly (alias, version and concurrency configurations). But API calls are not invoking the new version. Concurrency still doesn't work. Besides the edit in the API and Function CloudFormation templates you suggested is there anything else I should do?

**Comment by franklin113** [comment]
I am looking to add concurrency to my amplify app.  Has there been any updates on this? 
I have a REST API category lambda function that I want to have concurrency for.   I was able to manually assign a lambda version alias to the API Gateway's integration request.  Now I need publish a new version and assign the alias to it when I push to production.

**Comment by jadenv** [comment]
Seeing as this issue has been open for almost 4 years now, it seems this might be a bit too advanced of a use case for Amplify.

I would recommend using AWS CDK as an alternative to configure Lambda autoscaling:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html#autoscaling
