### ISSUE TITLE
Dynamo primary sort key

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#487]
**Is your feature request related to a problem? Please describe.**
`amplify init` and `amplify push` api commands don't allow for Dynamo tables to be created with a sort key.

**Describe the solution you'd like**
There was some discussion here of a possible solution but it doesn't seem to be implemented yet https://github.com/aws-amplify/amplify-cli/issues/56#issuecomment-416736520

Also discussed here https://github.com/aws-amplify/amplify-cli/pull/277#issuecomment-428690938

Something like this seems like it would work for my case of needing a sort key on a timestamp

```
type DeviceData @model {
  id: ID!
  timestamp: String! @sort
  value: String!
}
```

**Describe alternatives you've considered**
Not aware of any, would be open to anything since sort keys cannot be added to already created Dynamo tables.

**Comment by cityzen** [comment]
I would like to second this request

**Comment by mikeparisstuff** [comment]
Thank you for the note. This is a highly request feature and your feedback really helps us prioritize it. I will make sure this is included in discussions and will report back when I have more details.

**Comment by zjullion** [comment]
Would just like add that our organization would also love to see this feature.  As it currently stands, we're going to have to try manually modifying the cloudformation template that amplify creates in order to adjust the partition and sort keys.

**Comment by cityzen** [comment]
@zjullion I think you can link into an existing table or manually create a table and write your own custom resolvers. It may be easier to just form your own dynamo tables and write the custom resolvers than trying to fiddle with the auto-generated CloudFormation template.

**Comment by mart2967** [comment]
This is definitely our most needed feature at the moment. Would it be feasible to support specifying multiple sort fields? Example: sorting on createdAt or updatedAt. Clients would then specify what sort type to use in their graphql query variables.

**Comment by toddsampson** [comment]
+1 We also really need the feature.

**Comment by mikeparisstuff** [comment]
Wanted to ping this ticket again. We are working on an RFC for custom indexes on @model types and would love to hear your feedback when it is posted to GH.

**Comment by sakhmedbayev** [comment]
@mikeparisstuff would be great to have a way not only specify sort key but partition too.

**Comment by laura-sainz-mojix-com** [comment]
+1 We really need the feature also

**Comment by watanabethais** [comment]
+1 It would be great to have this feature.

**Comment by peterdyer7** [comment]
+1

**Comment by AlirezaAsadi** [comment]
+1

**Comment by marcschroeter** [comment]
+1

**Comment by yareyaredesuyo** [comment]
What is the best temporary way to achieve this ?

**Comment by et304383** [comment]
How is this still not resolved?  This seems like it should be trivial.  We need to define 1 to many relationships (user videos) and require a sort key.

**Comment by Crisp3333** [comment]
+1

**Comment by Crisp3333** [comment]
Currently for sorting, I am getting the query back from the response in call back then creating my own sorting algorithm. I think sorting is a fundamental operation for database/querying it might not be core, but it is used so much that it seems core. I rather not use this `@index` implementation to interfere with schemas that I am already satisfied with. To my benefit I am only returning at most 20 results. If it was 100's or 1000's of data to sort I would be in big problem. But sorting is needed. Would appreciate if some sorting mechanism would be provided out of the box for appsync\graphql

**Comment by kaustavghosh06** [comment]
We launched support for custom indexes today. You can find docs for the same out here - https://aws-amplify.github.io/docs/cli/graphql#key
Please let us know if you're still not able to solve your problem through this solution and we'll re-open this issue for you.

**Comment by AlirezaAsadi** [comment]
Awesome work! 👍

**Comment by Crisp3333** [comment]
Thanks a lot waking up with this news, I will try it out asap.

**Comment by Crisp3333** [comment]
@kaustavghosh06  I assume this will be in version `2.9.1`  for `android-sdk-appsync`.

**Comment by davidbiller** [comment]
https://stackoverflow.com/questions/56957835/use-key-to-get-only-your-own-data-shown-with-amplify
can someone help?
