### ISSUE TITLE
Can I create my custom policy for S3?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#4870]
Can I create my custom policy for S3?

I see that when adding S3 using amplify (amplify add storage), different access levels and. policies are added, (public, protected, private, S3AuthPublicPolicy, S3AuthProtectedPolicy…) to the s3-cloudformation-template.json file.

Can I my own custom policy? Something like S3CustomPolicy that does this:
Current user can upload files with prefix /profile-pictures/
No one can list files, remove or update them.
All files have public URLs, so, I can use them with emails and SDWebImage.

Apart from that, in one of the policies I see:
`/protected/${cognito-identity.amazonaws.com:sub}/*`
and in the sample code we have this:
`let key = "protected/\(AWSMobileClient.default().identityId!)/test.jpg`
that generates this URL:
`https://mybucket.s3-eu-west-1.amazonaws.com/protected/eu-west-1:9cc6e1be-29f8-xxxx-b2d2-ae7b82408739/my-image.jpg`

Is it possible to remove “eu-west-1” and the hyphens? Something like:
`https://mybucket.s3-eu-west-1.amazonaws.com/protected/9cc6e1be29f8xxxxb2d2ae7b82408739/my-image.jpg`
BTW, what is the purpose of the storage-params.json file? it is always empty.

Thanks a lot.

**Comment by ammarkarachi** [comment]
Hi @Ricardo1980,

You could either edit the cloudformation file or use the console. 

The URL that's generated is the path to the current signed in user as outlined here https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js and the string is a part of of the identity id.

The storage-params.json file is used when authorizing using user pool groups refer to 
https://aws.amazon.com/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/ under 'Adding User Pool Groups based authorization'

**Comment by Ricardo1980** [comment]
Thanks @ammarkarachi 

I modified my cloudformation file and now I can use the URs from a browser, email, or sdwebimage.
This is what I added:

		```
"S3BucketPolicy": {
			"DependsOn": [
				"S3Bucket"
			],
			"Type" : "AWS::S3::BucketPolicy",
			"Properties" : {
				"Bucket" : {"Ref" : "S3Bucket"},
				"PolicyDocument": {
					"Statement":[{
						"Sid": "PublidReadGetObject",
						"Effect": "Allow",
						"Action": "s3:GetObject",
						"Principal": "*",
						"Resource": [
							{
								"Fn::Join": [
									"",
									[
										"arn:aws:s3:::",
										{
											"Ref": "S3Bucket"
										},
										"/pictures/*"
									]
								]
							}
						]
					}]
				}
			}
		},

```
Is that OK?


I didn't know anything about 
https://aws.amazon.com/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/
I see a REST endpoint is created. Can I use GraphQL (AppSync) with that?

Thanks a lot.

**Comment by kaustavghosh06** [comment]
@Ricardo1980 are you unblocked with the issue above?

**Comment by Ricardo1980** [comment]
@kaustavghosh06 Yes, thanks a lot!
