### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by push10** [aws-amplify/amplify-cli#4872]
I have updated my graphql schema. 
Whenver I am trying to push it using amplify api push command I am getting some nasty error. 

× An error occurred when pushing the resources to the cloud

The specified bucket does not exist
There was an error pushing the API resource
NoSuchBucket: The specified bucket does not exist

#584

**Comment by UnleashedMind** [comment]
seems like the CLI can not find the deployment bucket. 
Please provide the following information so we can investigate: 
1. CLI verion
2. OS version
3. Amplify categories that you added to your project. 
4. Did you use Amplify Console to create your project? 
5. Have you pulled the project from github console and run `amplify init` on your local machine?
6. Have you manually changed anything in the `<project-root>/amplify/.config` folder?
7. Have you updated or deleted S3 bucket on the S3 console?

**Comment by nikhname** [comment]
Closing due lack of information/inactivity
