### ISSUE TITLE
An Error Occurred While Pushing Resources to the Cloud

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-cli#4873]
**Which Category is your question related to?**
Custom Stacks through amplify

**Amplify CLI Version** 
4.21.3

**Provide additional details e.g. code snippets**
I have added some [custom resources](https://docs.amplify.aws/cli/usage/customcf) in CustomResources.json. The details of the resources are not relevant, but an error occurs during their creation: _Resource is not in the state stackUpdateComplete_. This is a generic error, but in my case it refers to the creation of my custom resources which fail to be created simultaneously because they depend on one another. For instance, when I add a new environment `amplify env add` these custom resources should be created following an `amplify push`. However, since the custom resources that I added depend on one another, I am unable to push all the custom resources at the same time. Since I work in a feature branch git workflow with sandbox environments, this problem is very cumbersome. Does anybody know how to solve this problem? When I look at the auto-generated stacks (i.e. amplify/backend/api/myapi/build/SomeRandomStack.json) I notice that there are resources which depend on one another, yet the cli does not complain when you run `amplify push`. Any help would be appreciated

**Comment by UnleashedMind** [comment]
Have you tried to use the `DependsOn` attribute?
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html

**Comment by karrettgelley** [comment]
@UnleashedMind Thanks this solved my problem. Closing
