### ISSUE TITLE
many to many connection with auth directive (from docs)

### ISSUE THREAD

**Issue by a-ursino** [aws-amplify/amplify-cli#4874]
**Describe the bug**
I was trying to implement a "Many-to-many connections" following the docs at https://docs.amplify.aws/cli/graphql-transformer/directives#many-to-many-connections. If I copy the schema from the docs as it is, everything works fine. However, my API uses an API Key as default authorization mode and when I add an `@auth` directive like this to the schema

```graphql
type Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
  @model(queries: null)
  @auth(rules: [{ allow: owner }])
  @key(name: "byPost", fields: ["postID", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "postID"]) {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```

I get this error back

```json
{
  "data": {
    "getUser": {
      "id": "UU1",
      "username": "user1",
      "posts": {
        "items": null
      }
    }
  },
  "errors": [
    {
      "message": "Not Authorized to access items on type ModelPostEditorConnection",
      "errorType": "Unauthorized",
      "data": {},
      "errorInfo": {},
      "path": [
        "getUser",
        "posts",
        "items"
      ],
      "locations": [
        {
          "line": 33,
          "column": 7,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

when I execute this query:

```graphql
query GetUserWithPosts {
  getUser(id: "UU1") {
    id
    username
    posts{
      items{
        post{
          title
        }
      }
    }
  }
}
```

The same query works fine with a schema without the `@auth` directive.

**Amplify CLI Version**

v4.21.3

**To Reproduce**
Copy and paste the SDL above and run `amplify mock api`. The same behaviour happens when I deploy with `amplify push` 

**Expected behavior**
I should be able to access the items object

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 
 - Node Version. v14.4.0

**Additional context**

**Comment by a-ursino** [comment]
just to add few details that maybe can help in the debugging phase I did some tests

a) AppSync with Default authorization mode API key and no auth directive in the schema, works fine
b) AppSync with Default authorization mode Cognito pool and no auth directive in the schema, works fine
c) AppSync with Default authorization mode Cognito pool and auth directive in the schema returns an **error**

This is the schema for c

```graphql
type Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
  @model(queries: null)
  @auth(rules: [{ allow: owner }])
  @key(name: "byPost", fields: ["postID", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "postID"]) {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}

```

without all the auth directive (so point b) it works fine

any idea on how can fix it?

**Comment by a-ursino** [comment]
My workaround was to add explicitly this to my schema

```graphql
type ModelPostEditorConnection @aws_cognito_user_pools {
  items: [PostEditor]
  nextToken: String
}
```

the GraphQL transformer adds only this

type ModelPostEditorConnection {
  items: [PostEditor]
  nextToken: String
}

when an additional auth method is used on the many to many connection

**Comment by danbunnell** [comment]
I am also observing this behavior but using UserPools primary auth and IAM as secondary.  

As @a-ursino  reported, the type generated for the connection has default auth only.

```gql
type Post @model @auth(rules: [
    { allow: groups, provider: userPools, groups: ["Admins"] }
    { allow: public, provider: iam }
  ]) {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
  @model(queries: null)
  @auth(rules: [
    { allow: groups, provider: userPools, groups: ["Admins"] },
    { allow: public, provider: iam }
  ])
  @key(name: "byPost", fields: ["postID", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "postID"]) {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model @auth(rules: [
    { allow: groups, provider: userPools, groups: ["Admins"] },
    { allow: public, provider: iam }
  ]) {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```

Which results in this generated connection type:
```gql
type ModelPostEditorConnection {
  items: [PostEditor]
  nextToken: String
}
```

**Comment by sregg** [comment]
Same for me with Cognito by default and additional API key.
This solution worked for me too: https://github.com/aws-amplify/amplify-cli/issues/4874#issuecomment-662851439

**Comment by jackfrosch** [comment]
+1 for me, too. Auth setup is groups/cognito for CRUD and public/read/IAM for unauthenticated users. Solution from earlier was used. I declared the join connection type manually in schema.graphql and add the @aws_iam @aws_cognito_user_pools directives; i.e..

`type ModelPostEditorConnection @aws_iam @aws_cognito_user_pools {
  items: [PostEditor]
  nextToken: String
}`

**Comment by chrisjprior** [comment]
Auth directives are applied to the Model*Connection types as part of the process which adds them to the nested type's Query operations. What this means is that when there are no Query operations, the auth directives don't get applied to the Model*Connection type which leaves you with default authorization on that type.

The field level @connection directive will apply auth directives to the field but unfortunately it does not apply the directives to the field's return type i.e. the Model*Connection type. The PR I have linked ensures that the auth directive is also applied to the field's return type.

I have added a unit test for the example above to the PR and it passes. The only workaround I can see in advance of the fix is to rely on access via the default auth provider or to define an appropriate query operation on the nested type (in the case above that's the list operation on the PostEditor).

**Comment by chrisjprior** [comment]
@nikhname is there anything more I can do to help here?

**Comment by akshbhu** [comment]
Hi @a-ursino 

I tried to reproduce the error but its working for me. Can you try with the latest amplify version?

Here are my repro Steps:

I used below schema and followed documentation : https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections
```graphql
type Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(keyName: "byPost", fields: ["id"])
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor
  @model(queries: null)
  @auth(rules: [{ allow: owner }])
  @key(name: "byPost", fields: ["postID", "editorID"])
  @key(name: "byEditor", fields: ["editorID", "postID"]) {
  id: ID!
  postID: ID!
  editorID: ID!
  post: Post! @connection(fields: ["postID"])
  editor: User! @connection(fields: ["editorID"])
}

type User @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(keyName: "byEditor", fields: ["id"])
}
```
I used the default authorization as Cognitouserpools. Here is my default authorization
```json
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authissue4874a868a209"
            }
          },
```

After using the this Query 
```json
query GetUserWithPosts {
    getUser(id: "U1") {
        id
        username
        posts {
            items {
                post {
                    title
                }
            }
        }
    }
}
```
I am getting proper results with connections
```json
{
  "data": {
    "getUser": {
      "id": "U1",
      "username": "user1",
      "posts": {
        "items": [
          {
            "post": {
              "title": "Post 1"
            }
          },
          {
            "post": {
              "title": "Post 2"
            }
          }
        ]
      }
    }
  }
}
```

Let me know if I missed anything while recreating . Also Can you update to latest version and try again?

**Comment by a-ursino** [comment]
Hi @akshbhu 

I've updated amplify to v4.39, removed the custom code from my `amplify/backend/api/xyz/schema.graphql`

```
type ModelPostEditorConnection @aws_cognito_user_pools {
  items: [PostEditor]
  nextToken: String
}
```

and started to get the error again `Not Authorized to access items on type`.

The compiled schema at `amplify/backend/api/xyz/build/schema.graphql` contains now 

```
type ModelPostEditorConnection {
  items: [PostEditor]
  nextToken: String
}
```

instead of 

```
type ModelPostEditorConnection @aws_cognito_user_pools {
  items: [PostEditor]
  nextToken: String
}
```

so it works fine just with the default authorizer (the type generated for the connection has default auth only).

In my project, I have a default auth strategy with API KEY and an additional Cognito auth.

I hope this helps.

**Comment by anujmv** [comment]
@a-ursino - Same issue working with next js using both API and Cognito. Gives error when querying with cognito and works fine with API key.

Thought the problem was with my schema, weird bugs in amplify hope this fix.

**Comment by akshbhu** [comment]
Hi @a-ursino 

The @auth directive on model wont work if you have default authorizer as ```API KEY```.Can you try with default authentication as "CognitoUserPools" in your project? You can do that via ```amplify update api```.

@anujmv 

Can you check when you are making query with Cognito , Is  your default authentication for Auth is CognitoUserPools?
If not , can you try again by making Cognito as default authorizer.

You can check current auth config of your project inside amplify folder in this file ```backend-config.json```

**Comment by akshbhu** [comment]
Closing due to lack of response , If the problem still occurs , fell free to comment and I will reopen this issue again

**Comment by chrisjprior** [comment]
@akshbhu I raised a PR for this issue which included unit tests, did they not help you reproduce it?
