### ISSUE TITLE
Disable a Lambda in specific environment?

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-cli#4875]
I've created some utility Lambdas that I only need for a specific environment.

Is there a way to prevent that specific Lambda from being scanned upon in `amplify status` for a specific `amplify env` ?
I don't want it pushed in `prod` for example.

**Comment by UnleashedMind** [comment]
When you run `amplify env checkout` 
1. when you checkout into the particular env, the status for that particular function will be "Delete", run `amplify env pull --restore` to change it to "No Change"
2. when you checkout from the particular env to another env, the status for that particular function will be "Create", run `amplify env pull --restore` to change it to "No Change"

**Comment by SwaySway** [comment]
The Amplify CLI standard is to follow a git workflow. Docs here: https://docs.amplify.aws/cli/teams/overview
Should you have more questions on this please reach out in our discord community [here.](https://discord.gg/TrsguzP)
Should you have any issues related to this please comment below.
