### ISSUE TITLE
graphql has changes but no changes detected when amplify push command run. 

### ISSUE THREAD

**Issue by ajitgoel** [aws-amplify/amplify-cli#4883]
**Describe the bug**
I have made changes to my application's schema.graphql file and when i run the amplify push command, the system says "no changes detected". What could I be missing?

**Expected behavior**
When the schema.graphql file has changes and amplify push command is run, it should not show no changes detected message.

Running the amplify mock api command shows the schema changes but none of the queries.js, mutations.js, subscriptions.js files have the schema changes

**Update: 7/19/2020:**
so I think I know what is happening, if u look at the screenshot below, aws amplify detects that there are graphql changes and wants to push to aws, when I exit the process and rerun the amplify push again, it does not detect that the changes have not been updated in AWS. 

![image](https://user-images.githubusercontent.com/6394444/87885405-576cf280-c9db-11ea-8a8e-707625040630.png)

**Comment by UnleashedMind** [comment]
From the screen shot, I see you answered "yes" to the "Are you sure you want to continue" on the `amplify push`, which would mean the CLI started to push the local development updates to the cloud after the prompt about the codegen. 
At which point did you " exit the process" and how did you exit it? 

git file Changes does not necessarily mean your local developments haven't been pushed to the Cloud, it only means your github repo hasn't been updated. 

The CLI compares what's in the `amplicy/backend` and what's in the `amplify/#current-cloud-backend` to determine the status of each category.

If you want, you can make a dummy change, such  as adding a space at the end of one line in the schema, and then push again.

**Comment by ajitgoel** [comment]
We can close the issue. thank you @UnleashedMind for your input.
