### ISSUE TITLE
Custom naming schema during amplify initialization / environment setup

### ISSUE THREAD

**Issue by cremich** [aws-amplify/amplify-cli#4888]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify CLI initialization

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.24.2

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
Hello everyone,

is it possible to apply a custom naming schema in the resources referenced in the team-provider-info.json
We have some naming guidelines, how aws resources should be named across all our accounts. Amplify has it own ways for naming the resources created during initialization. 

Is there any support to define a custom naming schema?

**Comment by ammarkarachi** [comment]
Hi @cremich, We don't have anything that overrides the generated resource names but we are planning to include tag support #4607 for better governance of AWS resources.

**Comment by cremich** [comment]
Thanks @ammarkarachi .

Tagging is also relevant for us. In the meantime I found a solution how to update the tags for my amplify stacks. If you want, I can share it as a comment in #4607

**Comment by ammarkarachi** [comment]
> Thanks @ammarkarachi .
> 
> Tagging is also relevant for us. In the meantime I found a solution how to update the tags for my amplify stacks. If you want, I can share it as a comment in #4607

Definitely please go ahead!
