### ISSUE TITLE
Adding a layer resets function timeout

### ISSUE THREAD

**Issue by kennandavison** [aws-amplify/amplify-cli#4892]
Hi all - I'm noticing that my timeouts are all getting reset back to 25 seconds on my Lambdas after adding a layer. Learned the hard way today. :( Hope others can learn from this.

**Comment by houmark** [comment]
* It should be possible to configure timeout per function when creating/updating the function
* It should be possible to select the wanted Node version. It's currently defaulting to 10.x when 12.x is already available in Lambda
* It should be possible to configure RAM available to the function

**Comment by jhockett** [comment]
A fix was merged and deployed in Amplify CLI version 4.26.0.
