### ISSUE TITLE
How can I update Aurora Serveless from 1.17 to 2.07.1 (MySQL 5.6 to 5.7)

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#4904]
Hello,

I created my Amplify project time ago. I am using AppSync and RDS (Aurora) as a database.

I see that nowadays you support MySQL 5.7.

Using this command with the Query Editor and my database:
SHOW VARIABLES LIKE "%version%";
I see in my console:
aurora_version 1.17.98
version 5.6.10

How can I update from MySQL 5.6 to 5.7? (that is, from Aurora Serverless 1.17 to 2.07.1, the current one)

Update steps:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.html

If I try to follow those steps but in the console I don't see how to change my engine. See screenshots.

What do I do? How can I update my Aurora serverless instance? Am I missing something?

Thanks a lot.

<img width="1579" alt="Screenshot 2020-07-05 at 11 06 27" src="https://user-images.githubusercontent.com/738681/88152565-1b64a800-cbfc-11ea-903b-11595a9f3442.png">
<img width="865" alt="Screenshot 2020-07-05 at 11 05 26" src="https://user-images.githubusercontent.com/738681/88152573-1ef82f00-cbfc-11ea-891b-f9826b660acf.png">

**Comment by petervdbroek** [comment]
Did you manage to upgrade from aurora version 1.x to version 2.x?

**Comment by Ricardo1980** [comment]
@petervdbroek  Nope.

@nikhname Any news? I don't see any documentation about this issue. Thanks.

**Comment by CharanRoot** [comment]
@nikhname any update on this issue.

**Comment by Ricardo1980** [comment]
@nikhname 
Any news Nikhil?
I also asked this question in RDS forums 3 months ago but no reply.
https://forums.aws.amazon.com/thread.jspa?messageID=948408
What do we do?
Thanks a lot for your help.

**Comment by nikhname** [comment]
Hi @Ricardo1980, apologies for the late response. From the RDS [docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Patching.html#AuroraMySQL.Updates.Patching.ModifyEngineVersion), you should be able to modify the properties of your cluster by changing the Aurora MySQL engine version in the DB engine version box. From your screenshots it seems as though that window is not appearing so you could try upgrading the engine using the AWS CLI instead. Use the command ```aws rds modify-db-cluster --db-cluster-identifier <YOUR DB IDENTIFIER> --engine-version 5.7.mysql_aurora.2.07.1 --apply-immediately``` which will upgrade your specified database to the engine version 2.07.1 using MySQL version 5.7 and apply the changes immediately using the ```--apply-immediately``` flag. We do not currently support upgrading the cluster version using the Amplify CLI but we will look into doing so as an enhancement.

**Comment by Ricardo1980** [comment]
Thanks for reply @nikhil-dabhade 

But it seems it is not working.
I receive this:
`An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: You currently can't modify EngineVersion with Aurora Serverless.
`

**Comment by Ricardo1980** [comment]
@CharanRoot  @petervdbroek

I received a response from AWS support. 
I tried it and it is working. Not great, not terrible.

> Regretfully, it is currently not possible to upgrade an Aurora MySQL Serverless 5.6 DB cluster to Aurora MySQL Serverless 5.7 using the AWS CLI or directly from the RDS console. You can do so by restoring a snapshot from a currently supported Aurora MySQL release into Aurora MySQL Serverless 5.7 [1].
> 
> As a workaround I would recommend the following:
> 1)Take a snapshot of your current Aurora MySQL Serverless 5.6 DB cluster [2].
> 2)Restore the snapshot and select Aurora MySQL Serverless 5.7 on creation.
> 3)Update your application to point to the new Serverless DB cluster.
> 
> I understand you would like to avoid creating a new DB cluster and moving your data. The snapshot restore method is the easiest solution to your issue if your main concern is moving your data to another DB cluster. 
> 
> References
> ---------------
> [1] Aurora MySQL Serverless 5.7 engine updates 2020-06-18 (version 2.07.1) - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.serverless_2_07_01.html 
> 
> [2] Creating a DB cluster snapshot - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_CreateSnapshotCluster.html
