### ISSUE TITLE
How can I access my Aurora Serverless database from Lambda?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#4911]
I would like to create a lambda function that manipulates my data base (queries, updates…).
Somehow, I have to send info about how to connect to the database but it seems Amplify CLI does not support this.

If I run “amplify function add” then I can add a function and one of the questions is:

`? Do you want to access other resources in this project from your Lambda function? (Y/n) Y`

If I select YES I see this list:
```
? Select the category 
 ◯ api
 ◯ function
❯◯ auth
 ◯ storage
```

As you can see, RDS is not there. It appears the only way I have to access the database is through AppSync, but I don’t want, I don’t need that extra layer.

If I select those options, then Amplify creates special environment variables I can use in my lambda function.
This is what the console shows:

```
You can access the following resource attributes as environment variables from your Lambda function
	API_xxxxxxAPI_GRAPHQLAPIENDPOINTOUTPUT
	API_xxxxxxAPI_GRAPHQLAPIIDOUTPUT
	AUTH_xxxxxUSERPOOLID
	FUNCTION_SENDREPORT_NAME
	FUNCTION_SENDSUPPORTMESSAGE_NAME
	STORAGE_xxxxxx_BUCKETNAME
```

But what I want to send is exactly what I see in the file:
amplify/banckend/xxxapi/stacks/xxxxxapi-mydb-rds.json

These parameters:
```
"RelationalDatabaseConfig": {
          "RelationalDatabaseSourceType": "RDS_HTTP_ENDPOINT",
          "RdsHttpEndpointConfig": {
            "AwsRegion": {
              "Ref": "rdsRegion"
            },
            "DbClusterIdentifier": {
              "Ref": "rdsClusterIdentifier"
            },
            "DatabaseName": {
              "Ref": "rdsDatabaseName"
            },
            "Schema": "mysql",
            "AwsSecretStoreArn": {
              "Ref": "rdsSecretStoreArn"
            }
          }
        }
```

So, how can I send the values I need to access my RDS database to my lambda functions using environment variables? I mean, what file and cloud formation template do I have to modify?

Regarding accessing my database using GraphQL/AppSync, seems an unnecessary layer in my use cases, although I haven’t explored that.

Can you help me?
Thanks a lot.

**Comment by berenddeboer** [comment]
You can pass in outputs from other templates as input to your lambda template [by specifying the `dependsOn`](https://docs.amplify.aws/cli/usage/customcf) parameter in `backend-config.json`.

**Comment by nikhname** [comment]
@Ricardo1980 Yes as @berenddeboer said, outputs from other templates can be passed as input to lambda templates by using the `dependsOn` parameter in ```backend-config.json```. Feel free to comment if there are further questions.

**Comment by Ricardo1980** [comment]
@nikhname @berenddeboer 

OK, thanks a lot, I am going to try that.

Apart from that, last question:
Do you recommend me to do that (accessing aurora from lambda) or accessing my data using GraphQL from lambda? It appears that the command line wizard supports this scenario and prepares permissions and environment variables, so, it seems easier.

Thanks for suggestions.

**Comment by idanlo** [comment]
Hey @Ricardo1980 How did you end up doing that? My guess is I need to add to the lambda function in the dependsOn array this statement - 
```
{
    "category": "api",
    "resourceName": "XXXX",
    "attributes": [
        "GraphQLAPIIdOutput",
        "rdsRegion",
        "rdsClusterIdentifier",
        "rdsSecretStoreArn",
        "rdsDatabaseName"
    ]
}
```
Is that correct?

**Comment by Ricardo1980** [comment]
@idanlo let me know if you still need that info and I tell you several different things you have to do.
BTW, I don't remcommend you to use AWS RDS framework, it is a pain in the ass accessing the results when requesting some data. Use this:
https://github.com/jeremydaly/data-api-client
everything is much easier with that.

**Comment by idanlo** [comment]
@Ricardo1980 What I ended up doing is adding the attributes like I mentioned in my previous comment, but I had to export these in the GraphQL API cloudformation template, before every push to the API I need to run `amplify api gql-compile` then go to the cloudformation file, add these lines to the `Outputs` object -
```
  "RDSRegion": {
          "Value": {
            "Ref": "rdsRegion"
          }
        },
        "RDSClusterIdentifier": {
          "Value": {
            "Ref": "rdsClusterIdentifier"
          }
        },
        "RDSSecretStoreArn": {
          "Value": {
            "Ref": "rdsSecretStoreArn"
          }
        },
        "RDSDatabaseName": {
          "Value": {
            "Ref": "rdsDatabaseName"
          }
        }
```
And then run `amplify push -no-gql-override --y` so that it will not override the cloudformation template changes. 
I also had to add this to each lambda cloudformation json file - 
```
    "RDSDataAPIResourcesPolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "rds-data-api-lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "secretsmanager:GetSecretValue"
              ],
              "Resource": {
                "Ref": "apiNAMEOFAPIRDSSecretStoreArn"
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "rds-data:BatchExecuteStatement",
                "rds-data:BeginTransaction",
                "rds-data:CommitTransaction",
                "rds-data:ExecuteStatement",
                "rds-data:RollbackTransaction"
              ],
              "Resource": {
                "Ref": "apiNAMEOFAPIRDSClusterIdentifier"
              }
            }
          ]
        }
      }
    }
``` 
and also had to add the environment files in order to access the database from the code.
If there is anything I can do more efficiently I'm happy to hear suggestions.

And yes, the `data-api-client` library is awesome, a true life saver. I actually created types for it in DefinitelyTyped.
