### ISSUE TITLE
AppSync API Status does not reflect auth updates

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/amplify-cli#4914]
**Describe the bug**
Updating auth types of an AppSync API is not reflected in `amplify status` -- shows "No Change"

**Amplify CLI Version**
4.24.3

**To Reproduce**
```
amplify init
amplify add api // create AppSync API with API_KEY default auth
amplify push
amplify update api // select Update auth settings and choose IAM as the default auth type
amplify status // shows "No Change"
```

**Expected behavior**
`amplify status` shows "Update" when modifying the api auth

It looks like it's because updating the auth only modifies the generated cfn template which is in the build folder in the api resource and is ignored when hashing the folder to determine a diff here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/extensions/amplify-helpers/resource-status.js#L37

**Comment by rsousa** [comment]
Also, because of this the remote configuration doesn't change if one does a amplify push.
To overcome this we need to change the schema file push, change it back and push.

**Comment by jhockett** [comment]
Closing this issue since #8782 has been released.

**Comment by avenak** [comment]
This is still broken. I have removed API_KEY auth mode from my GraphQL model and add owner-based auth. I delete aws-exports.json and then `amplify pull`. A new aws-exports.json is generated and it still states that AppSync auth mode is API_KEY. This is either a bug or I am fundamentally not understanding how this is supposed to work.

**Comment by mosoriob** [comment]
Yes, this is still a problem
