### ISSUE TITLE
Amplify console command opens in the wrong region showing a cryptic message

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-cli#4920]
**Describe the bug**
When running the `amplify console` command the browser opens the url `us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2` but shows a top red band error `App with id APP_ID not found`. After some digging it seems the app was created in region `us-east-1`.

**Amplify CLI Version**
4.24.1

**To Reproduce**
Create an amplify AWS Profile in a REGION different from your default region for AWS Management Console. Run
```
amplify configure
amplify init
amplify console
```

**Expected behavior**
Change the message to provide some more context to the user. 

Eg: Your Amplify App has not been published in `us-east-2`. Change the region to match your Amplify project. You can find this information at `src/aws-exports.js`.

**Screenshots**
![Amplify-Framework_console (1)](https://user-images.githubusercontent.com/4660316/88310386-8353e500-cd07-11ea-90ad-15768bd84d08.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 14.5.0

**Additional context**
Issue reported during Amplify Days workshop

**Comment by MatthewJiao** [comment]
you helped me! thanks

**Comment by ZRamirez** [comment]
This same thing happens to me. aws-exports.js states the correct region. Thanks for the help.

**Comment by gitaalekhyapaul** [comment]
I think this issue does not exist anymore on version `4.45.2`, and can be safely closed.
