### ISSUE TITLE
Lambda function executing code from prior layer version on "test" in aws  lambda console

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-cli#4928]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I have a function that executes code from a layer. I have made changes to the layer that remove the lodash dependency from everywhere in the code, then I run "amplify push" and push the layer and update the version, next I configure my function to use the update layer version, and then run "amplify push" to update the function in the cloud in the dev env. Finally, I press the "test" button on the aws lambda console, and it  fails saying it cannot find lodash dependency. I have examined the zip file for the layer version and there is no reference to lodash. I have confirmed in the lambda console which layer version is configured for the function, and confirmed that the source code in the zip file from the console that it does not contain any reference to lodash. I don't know what to do now, it seems that there is some issue where and old version is pinned somewhere and it cannot access the new version's code.

![image](https://user-images.githubusercontent.com/3522001/88353882-fbc0a300-cd13-11ea-9f12-fbe6a83684c9.png)

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.25.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by pashka4281** [comment]
Dealing with the same exact thing. I figured out amplify doesn't follow AWS's layer versioning convention and instead uses its own one based on layer's description.
If you go here https://console.aws.amazon.com/lambda/home?region=us-east-1#/layers
and open up your layer you'll see that 

![layer](https://user-images.githubusercontent.com/91559/88566225-b9dd7880-d003-11ea-8e1b-b0b99867f9ee.jpg)

As you can see aws has 69 versions of this layer while amplify only has 11, at the same time I'm only able to see 9 from the CLI.
![wemux 2020-07-27 12-25-43](https://user-images.githubusercontent.com/91559/88566679-5c95f700-d004-11ea-9d21-7850b180e654.jpg)

I noticed that amplify doesn't always recognizes code update inside package (not sure what it depends on) but a new aws version seems to be created every time. In other words: I might have version 1, then change the code in it, amplify doesn't show any new versions in the CLI, then I do a push with other function updates and see a new version pop up on aws (:2 with description that says "Lambda layer version 1"). Something like this:
```
2 | arn:aws:lambda:us-east-1:99999999999:layer:CommonLayer:2 | Lambda layer version 1
1 | arn:aws:lambda:us-east-1:99999999999:layer:CommonLayer:1 | Lambda layer version 1
```

Then a few code changes & pushes later amplify CLI finally recognizes layer update and offers an update to V2, but the issue is that by then you have already deprecated V2 in favour of something like V5

**Comment by cc-bojan** [comment]
> Dealing with the same exact thing. I figured out amplify doesn't follow AWS's layer versioning convention and instead uses its own one based on layer's description.
> If you go here https://console.aws.amazon.com/lambda/home?region=us-east-1#/layers (choose your appropriate region)
> and open up your layer you'll see that
> 
> ![layer](https://user-images.githubusercontent.com/91559/88566225-b9dd7880-d003-11ea-8e1b-b0b99867f9ee.jpg)
> 
> As you can see aws has 68 versions of this layer while amplify only has 11, at the same time I'm only able to see 9 from the CLI.
> ![wemux 2020-07-27 12-25-43](https://user-images.githubusercontent.com/91559/88566679-5c95f700-d004-11ea-9d21-7850b180e654.jpg)
> 
> This results in different aws versions mapping to the same amplify version.
> 
> I noticed that amplify doesn't always recognizes code update inside package (not sure what it depends on) but a new aws version seems to be created every time. In other words: I might have version 1, then change the code in it, amplify doesn't show any new versions in the CLI, then I do a push with other function updates and see a new version pop up on aws (:2 with description that says "Lambda layer version 1"). Something like this:
> 
> ```
> 2 | arn:aws:lambda:us-east-1:99999999999:layer:CommonLayer:2 | Lambda layer version 1
> 1 | arn:aws:lambda:us-east-1:99999999999:layer:CommonLayer:1 | Lambda layer version 1
> ```
> 
> Then a few code changes & pushes later amplify CLI finally recognizes layer update and offers an update to V2, but the issue is that by then you have already deprecated V2 in favour of something like V5
> 
> P.S. I'm pushing 2 separate amplify environments (staging & dev) with the same layers so that only makes those versions multiply faster, but it's not the problem itself. It happens on a single env as well.
> 
> Still my use case is rather unconventional as we keep the layer in a separate repo (it has DB connectivity that is shared across multiple amplify apps) so the layer's code in my amplify app is ignored on the main project's gitignore (root of the project).
> So it's not part of the amplify's app repo, while at the same time we need that code in the build phase so we pull it from git as a separate step in the build script, that pulled code is probably recognized by amplify as a "change" so later on during build when it pushes backend, it also creates a new layer version each time we deploy anything.

Did you manage to solve this? I'm facing the exact same issue as you did:

<img width="1271" alt="1" src="https://user-images.githubusercontent.com/44865325/98831991-93b9d800-243c-11eb-9d08-a9f96a365c1f.png">

<img width="1117" alt="2" src="https://user-images.githubusercontent.com/44865325/98832028-9ddbd680-243c-11eb-9849-2e0fd4bd0fc1.png">

**Comment by a-bachelet** [comment]
@pashka4281 @cc-bojan 

Did any of you found a solution ?

I'm facing the same issue too and it's kind of frustrating because I can never use the last version of my layer as I intend to.

Thanks in advance !

**Comment by ammarkarachi** [comment]
This is something we are tracking in an overall rework for [Lambda Layer Improvement](https://github.com/aws-amplify/amplify-cli/projects/14 ) There is a similar issue targeting this problem tracking #5072

**Comment by pashka4281** [comment]
> @pashka4281 @cc-bojan
> 
> Did any of you found a solution ?
> 
> I'm facing the same issue too and it's kind of frustrating because I can never use the last version of my layer as I intend to.
> 
> Thanks in advance !

Yeah, we just started to modify templates manually inserting the proper version's ARN instead of using the cli
