### ISSUE TITLE
Data Model (Schema) design

### ISSUE THREAD

**Issue by mhzbg** [aws-amplify/amplify-cli#4933]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Schema Design

**Amplify CLI Version** 

4.25.0

**What AWS Services are you utilizing?**

GraphQL API

**Provide additional details e.g. code snippets**

Sorry if this is a new-be question but how would I go by designing the following schema. 

We have a trivial blog post that requires to have categories related to it, one or multiple.  
The categories cannot be an enum, need to be dynamic, so you can add new ones via a mutation. 

The trivial question is what would the relationship look like to have many blogposts relate to array of categories. 
Something like this (does not work)

```graphql
type Post 
  @model 
  id: ID!
  title: String!
  content: String
  image: Media @connection
  color: String
  status: Status
  categories: [Category] @connection
}

type Category
  @model
  id: ID!
  title: String!
}
```

The issue with this relation is that: 
We can only relate one category to a Post. 
Also how can we specify the category ID when creating the post, vs creating the category that relates to a secondary index created automatically (PostCategory) on the Category table. 

There must be a proper design pattern we're missing. 

Thanks for help.

**Comment by foxfl** [comment]
Hey,

What you are trying to archive is a many-to-many relationship between categories and posts 


For this, there is a pattern provided on the documentation: https://docs.amplify.aws/cli/graphql-transformer/directives#many-to-many-connections

Key here is to split up the many-to-many into two one-to-many relationships with a join model


```
type Post 
  @model {
  id: ID!
  title: String!
  content: String
  image: Media @connection
  color: String
  status: Status
  categories: [PostCategory ] @connection(keyName: "byPost", fields: ["id"])
}

type PostCategory
  @model(queries: null)
  @key(name: "byPost", fields: ["postID", "categoryID"])
  @key(name: "byCategory", fields: ["categoryID", "postID"]) {
  id: ID!
  postID: ID!
  categoryID: ID!
  post: Post! @connection(fields: ["postID"])
  category: Category! @connection(fields: ["categoryID"])
}

type Category
  @model {
  id: ID!
  title: String!
  posts: [PostCategory ] @connection(keyName: "byCategory", fields: ["id"])
}
```

Then, to add a category to a post, you would create a new PostCategory through a mutation

**Comment by ammarkarachi** [comment]
@mhzbg You would have to create a separate join model as pointed out by @foxfl. Let us know if that works for you

**Comment by mhzbg** [comment]
Yep, that worked @ Thank you for your help !
