### ISSUE TITLE
Mock Graphql API - NO SCHEMA AVAILABLE in local GraphQL console

### ISSUE THREAD

**Issue by thomasklein-winemaker** [aws-amplify/amplify-cli#4935]
**Describe the bug**
With my schema placed at `amplify/backend/api/backend/schema.graphql`, running `amplify mock api` doesn't seem to mock GraphQL. There's no change in `aws-exports.js` (e.g. pointing to local endpoints; adding `aws_appsync_dangerously_connect_to_http_endpoint_for_testing`as [described in the docs](https://docs.amplify.aws/cli/usage/mock))

From what I can see on the local GraphQL console running on http://localhost:20002/ it tries to fetch data from `/api-config` but the response is empty.

Even with my schema being the example one from the docs
```
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

**Output running `amplify mock api`:**

```
amplify mock api         
Scanning for plugins...
Plugin scan successful

The following types do not have '@auth' enabled. Consider using @auth with @model
         - Todo
Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth


GraphQL schema compiled successfully.

Edit your schema at /Users/thom/Projects/studio/amplify/backend/api/backend/schema.graphql or place .graphql files in a directory at /Users/thom/Projects/studio/amplify/backend/api/backend/schema
```
=> no more additional output like local table creation.

Worth noting that everything works as expected in the cloud.

**Versions**
- Amplify CLI 4.25.0 on MacOSX 10.15.5; 
- npm@6.14.7, node 14.1.0
- java openjdk version "12.0.2" 2019-07-16

**Comment by ammarkarachi** [comment]
@thomasklein-winemaker I am not able to reproduce the issue with aws-exports.js not updating. Also, what do you mean by 'NO SCHEMA AVAILABLE'?

**Comment by thomasklein-winemaker** [comment]
Hi @ammarkarachi !
This is what I'm seeing in the GraphQL Explorer:

<img width="886" alt="Screenshot 2020-07-27 at 19 19 11" src="https://user-images.githubusercontent.com/64782880/88571535-16f62000-d03e-11ea-88ba-2e475c549d14.png">

The amplify CLI also returns a warning (I think):

```
Mock does not handle CloudFormation resource of type AWS::IAM::ManagedPolicy. Skipping processing resource AuthRolePolicy01.
```
