### ISSUE TITLE
Has there been a change in the CORS handling of API functions?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-cli#4937]
I have 2 functions, each connected to a REST API.
Both use CORS `app.use(cors())`
One works fine but the other gives me a CORS error when calling from localhost.
The one that works was created by a slightly older version of Amplify, about 3 months ago,
The new one if from today.
I can't figure out why one would work and the other won't.

UPDATE:
This gets even weirder: I moved the `app.post` function from the API that gives the CORS error, to the one that works fine, and still the second function gives CORS error!
```
API.post('apiName', '/function1', ... // works fine
API.post('apiName', '/function2', ... // CORS error
```
I don't understand how is that even possible since they both are in the same API and in the same express app file...
```
app.use(cors())
...
app.post('/function1', function (req, res) { ...
app.post('/function2', function (req, res) { ...
```

**Comment by lkowalski-smartbusiness** [comment]
CORS errors show up in the code when the function has an uncaught errors and does not provide a valid response. Check your CloudWatch logs for indication of what's wrong with `/function2`

**Comment by ammarkarachi** [comment]
@ilyador as @lkowalski-smartbusiness mentioned the CORS error could possibly be as a result of errors in `/function2`

**Comment by ilyador** [comment]
@ammarkarachi @lkowalski-smartbusiness the functions worked fine when using a simple node server.
When defining new APIs with Amplify, do I need to register any path (like `/function1`) trough the CLI?

**Comment by ammarkarachi** [comment]
@ilyador If you have followed the steps here https://docs.amplify.aws/cli/restapi#rest-endpoint-that-triggers-new-lambda-functions there wouldn't be any additional steps to include a route
