### ISSUE TITLE
Amplify Push Timeout Error BUG/ISSUE

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-cli#4946]
This issue is evident with there are about 30 graphql schema. From Amplify CLI version 4.22 going forward, this issue has been consistent and causing issues. It hangs for a while on the cursor in command line and return a Amplify Push Timeout Error. This issue does not exist in 4.21.3. 

[schema.zip](https://github.com/aws-amplify/amplify-cli/files/4983327/schema.zip)

![image](https://user-images.githubusercontent.com/51476926/88570230-a0ecbb80-d033-11ea-9870-5dca50b264c5.png)

**Comment by KayIlory** [comment]
Attached is a list of 25 graphql schemas that might help replicate the issue using CLI version 4.22 and over.

**Comment by ammarkarachi** [comment]
Hi @KayIlory, The issue exists when a timeout is received when attempting to write to S3 we are working on a fix to retry after a timeout has been received

**Comment by KayIlory** [comment]
@ammarkarachi thanks for acknowledging the bug, any update on when we will get a fix for this.

**Comment by KayIlory** [comment]
> @ammarkarachi thanks for acknowledging the bug, any update on when we will get a fix for this.

and in what version the fix will be present so that I can test as well.

**Comment by ammarkarachi** [comment]
@KayIlory This should be fixed now in the latest version can you try it out?
