### ISSUE TITLE
Project Path Error claims Directory Path does not exist 

### ISSUE THREAD

**Issue by fuhreeus** [aws-amplify/amplify-cli#4950]
**Describe the bug**
Backend build  process is failing and the error references amplifi "featureFlags.js".  My project path exists and it is correct.  This issue started about 4 days ago.

**To Reproduce**
1) After updating the lambda function
2) Amplify push -y
3) Go to Amplify Console
4) See error in Build section.

**Expected behavior**
The build should work correctly as it did before and the process will deploy the next version of the code.

**Code Snippet**
This is the log from the Backend Build Process

# Starting phase: build
# Executing command: amplifyPush --simple
2020-07-27T19:38:17.079Z [INFO]: Project path: 'C:\Users\myusername\Documents\Projects\projectname' does not exist.
2020-07-27T19:38:17.080Z [INFO]: Error: Project path: 'C:\Users\myusername\Documents\Projects\projectname' does not exist.
                                 at Function.FeatureFlags.initialize (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:246:15)
2020-07-27T19:38:17.085Z [ERROR]: !!! Build failed
2020-07-27T19:38:17.085Z [ERROR]: !!! Non-Zero Exit Code detected
2020-07-27T19:38:17.085Z [INFO]: # Starting environment caching...
2020-07-27T19:38:17.086Z [INFO]: # Environment caching completed
Terminating logging...

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
 Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.5.0 => 9.5.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    aws-amplify: ^3.0.11 => 3.0.11
    aws-amplify-react: ^4.1.10 => 4.1.10
    bootstrap: ^4.5.0 => 4.5.0
    bootstrap-switch-button-react: ^1.2.0 => 1.2.0
    formik: ^2.1.4 => 2.1.4
    react: ^16.13.1 => 16.13.1
    react-bootstrap: ^1.0.1 => 1.0.1
    react-datepicker: ^2.16.0 => 2.16.0
    react-dom: ^16.13.1 => 16.13.1
    react-icons: ^3.10.0 => 3.10.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: 3.4.1 => 3.4.1
    react-select: ^3.1.0 => 3.1.0
    styled-components: ^5.1.1 => 5.1.1
    yup: ^0.29.1 => 0.29.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.25.0
</details>

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by kaustavghosh06** [comment]
@fuhreeus Have you connected your git repo to the Amplify Console? Amplify CLI adds a section in .gitignore which precluded addition of files which don't need to be checked in and committed. Looks like you've committed `amplify/.config/local-env-info.json` file which contains your local project path and that file shouldn't have been checked in.

**Comment by fuhreeus** [comment]
@kaustavghosh06 My repo is connected to the Amplify Console without issue (until recently).  This error started happening around build  #25. 

My issue happens when I do an amplify push.

I've disconnected and reconnected the repo (keys and webhooks as well) because if I do a git push on the frontend, I get this error: "There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again."

I see the local-env-info.json file but that hasn't caused any issues until just recently.

**Comment by CarlitosBeto** [comment]
@kaustavghosh06 I have the same issue with the new version "25", the process amplify push have the error  reported.
@fuhreeus I solved the issue in build process assigned a version 4.21.1 for build, maybe can help

**Comment by fuhreeus** [comment]
I just went back and checked the Amplify Console to see when my builds stopped working. 
On 24-July, I upgraded from '@aws-amplify/cli 4.24.3 to 4.25. 

The build stopped working from that point forward

**Comment by AravindTReddy** [comment]
Having the same issue from couple of days. Build failing with project directory does not exist when i push to Git or codecommit. 
@fuhreeus 
how did you do this ? ```After forcing build process to use @aws-amplify/cli 4.24.3, the build began to work again.```

Thanks a ton
Aravind

**Comment by fuhreeus** [comment]
@AravindTReddy In the Amplify Console "Build Settings" far left.

The Build Image settings at the bottom can be Edited to for a specific Amplify CLI build.  By default, it is set to "Latest", i changed it to 4.24.3

**Comment by AravindTReddy** [comment]
Thanks @fuhreeu. Build began to work again normal, But in my case 4.24.1 worked

**Comment by attilah** [comment]
@fuhreeus @AravindTReddy by default Amplify CLI generated `.gitignore` excludes the `local-env-info.json` file because it contains information about the locally initialized environment. Is there a particular reason why you have checked it into source control?

If you add the file back to `.gitignore` and remove it from source control, that could unblock you to use the latest version of the CLI, while we will work on a workaround.

**Comment by fuhreeus** [comment]
@attilah Thanks. My .gitignore file is woefully inadequate and I will be updating it for the reasons you listed.

I will try your workaround and report back.

**Comment by renebrandel** [comment]
@fuhreeus thank you! Let us know if this is still occurring, feel free to re-open the issue.
