### ISSUE TITLE
AppSync: Adding @key on a list field results in error when creating object: "Type mismatch for Index Key categories Expected: S Actual: L"

### ISSUE THREAD

**Issue by Jahans3** [aws-amplify/amplify-cli#4951]
I recently added a `@key` directive to a schema field so that I could search by that field, although I now get an error implying the previously correct data type is not what is expected. It says it expects a string but got a list, although the field is a list containing an enum.

Is it possible to query by a specific field without using `@key`? If not, how can I create records when the `@key` (seemingly) changes the expected type of a list to a string?

Below is my code, I added the `@key` to the `categories` list, but now when I try to create a new `Journey` I get the error shown below.

This is the schema:
```graphql
type Journey @model
  @auth(rules: [{ allow: owner, operations: [create, delete, update] }])
  @key(name: "getJourneysByCategories", fields: ["categories"], queryField: "getJourneysByCategories")
  @key(name: "getJourneysByName", fields: ["name"], queryField: "getJourneysByName") {
  id: ID!
  name: String!
  description: String
  coverImage: String
  isPrivate: Boolean!
  members: [JourneyUsersBridge] @connection(name: "JourneyUsers")
  moderators: [JourneyModeratorsBridge] @connection(name: "ModeratedBy")
  creator: User! @connection(name: "JourneyCreator")
  goals: [Goal] @connection(name: "JourneyGoals")
  posts: [Post] @connection(name: "JourneyPosts")
  categories: [JourneyCategory!]!
}
```

This is an example of the code used to create a `Journey`:
```typescript
type CreateJourneyInput = {
  name: string;
  description?: string | null;
  coverImage?: string | null;
  isPrivate: boolean;
  categories: Array<JourneyCategory | null>;
  journeyCreatorId: string;
};
const journey: CreateJourneyInput = {
    name: 'My GraphQL Journey',
    description: 'This Journey was made using GraphQL minus DataStore!',
    isPrivate: false,
    categories: [JourneyCategory.EXMAMPLE],
    journeyCreatorId: userId
};
const result = await API.graphql(
    graphqlOperation(mutations.createJourney, { input: journey })
);
```

This is the full error:
```
"One or more parameter values were invalid: Type mismatch for Index Key categories Expected: S Actual: L IndexName: getJourneysByCategories (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: U4EB7HPO1GU5LHVAOPMGAJJHANVV4KQNSO5AEMVJF66Q9ASUAAJG)"
```

**Amplify CLI Version** 
4.24.1

**What AWS Services are you utilizing?**
AppSync, DynamoDB

**Comment by Jahans3** [comment]
So I just removed the `getJourneysByCategories` key and the upload worked fine. What's happening here and why?

I just want to be able to query by `categories` - perhaps `@key` wasn't the right route to take? Does the key directive not work with lists?

**Comment by RossWilliams** [comment]
For DynamoDB, primary key attributes need to be of type string, number, or binary. you cannot use a list type.

You want to search by category, but each Journey can have multiple categories. The better way to handle this within the Amplify / DynamoDB framework is to have another model called JourneyJourneyType (or find a good name), where each item contains exactly 1 category.  JourneyJourneyType can contain a @connection to the Journey items.

something along these lines (untested):
```
type Journey @model
  @auth(rules: [{ allow: owner, operations: [create, delete, update] }])
  @key(name: "getJourneysByName", fields: ["name"], queryField: "getJourneysByName") {
  id: ID!
  categories: [JourneyCategory!]!
}

type JourneyJourneyCategory @model 
@key(name: "byCategoryOwnerDate", fields: ["category","owner","createdAt"]) {
  id: ID!
  journey: Journey! @connection
  category: JourneyCategory!
  owner: String! # you likely want to just get one owner's category
  createdAt: String! # you likely want to sort on createdAt from the main money
}
```

**Comment by Jahans3** [comment]
Thanks Ross, this solves my issue nicely. Seems obvious now 🙂
