### ISSUE TITLE
CLI 4.25 Breaks Authorization on Connected Models with Dynamic Auth

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#4954]
**Describe the bug**

Using the 4.25 CLI I push my schema to the cloud.

My schema.graphql has connected models something like this below.

```
type Scale @model
@auth ** some auth configuration
{
  id: ID
  uom: Uom @connection
}

type Uom @model
@auth **dynamic auth
{
  id: ID
  name: String
}
```

I have authorization for both of these models and I can run queries (ie. listUom, listScale) and get data directly like that. However, if I try to get to the Uom via the Scale query (ie. listScale(limit:10){items{id Uom{id}}}) it fails saying that I have no access to the Uom model.

This was working on CLI 4.23 - and if I downgrade from 4.25 to 4.23 the problem disappears and I again have the correct access.

**Amplify CLI Version**
4.23.1 is working - 4.25.0 is failing

**To Reproduce**
As described above

**Expected behavior**
Auth for 4.25 is the same as 4.23.1

**Comment by ammarkarachi** [comment]
@sacrampton Can you share your schema?

**Comment by sacrampton** [comment]
Hi @ammarkarachi - I can't share my entire schema (it is very large, spans multiple files, and is confidential). But I've cut out enough to demonstrate the issue. In so doing I think I might have incorrectly described the problem.

[schema1.zip](https://github.com/aws-amplify/amplify-cli/files/4991279/schema1.zip)

In any version of the Amplify CLI the following query works against the attached schema.

```
query getUser{
   getUser(id: "7d10d362-8902-40a0-b013-7022594097f5")
     {	id
        mobileActiveLocation{ 
          id
         classification{
           id
           fieldList{items{
             id
} } } } } }
```

However, as soon as I go one level below adding uom{id} or scale{id} or uom{scale{id}} under the fieldList part of the query it fails in Amplify 4.25 - but works in Amplify 4.23.1. I note that the @connection for uom and scale from the fieldList are not named connections, so maybe it has something to do with that.

```
query getUser{
   getUser(id: "7d10d362-8902-40a0-b013-7022594097f5")
     {	id
        mobileActiveLocation{ 
          id
         classification{
           id
           fieldList{items{
             id
             uom{id}
} } } } } }
```

Either way, it seems clear that my original description of the problem is incorrect.

**Comment by RossWilliams** [comment]
if you diff the generated resolvers between the versions, do you see any differences? Especially for /amplify/backend/api/$NAME/build/resolvers/fieldList.uom.res.vtl ?

**Comment by sacrampton** [comment]
There are differences between the two generated resolvers

The one generated by Amplify 4.23.1 has this as its last line

```
$util.toJson($context.result)
```

The one generated by Amplify 4.25 has this instead

```
#if( $ctx.error )
$util.error($ctx.error.message, $ctx.error.type)
#else
$util.toJson($ctx.result)
#end
```

**Comment by ammarkarachi** [comment]
@sacrampton with 4.23.1 does `uom{id}` return a `null`?

**Comment by sacrampton** [comment]
In 4.23.1 it returns null (I don't have anything in the Uom table linked here), but in 4.25 it returns an error saying I don't have permission to access Uom

**Comment by ammarkarachi** [comment]
That's expected in the change made after 4.23.1 we do return errors and the object.

**Comment by sacrampton** [comment]
@ammarkarachi - I'm struggling to recreated this in my test environment so I'll close this issue. I was getting this permission issue in my production environment and it disappeared when I rolled back to 4.23.1 - but I can't recreate in test.
