### ISSUE TITLE
Option `-y` for `amplify push`

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-cli#4955]
**Describe the solution you'd like**
I would like to do `amplify push -y` so I don't get asked some questions that I have to confirm after issuing the command.

**Describe alternatives you've considered**
Build a bash script that does `amplify push` and then inputs `Y` three times

**Additional context**
This is costing me time, because sometimes I do `amplify push`, do something else for 5 minutes and then come back expecting it to be done but see that I forgot to confirm

**Comment by ammarkarachi** [comment]
Hi @tobiasfeil, you can use `amplify push --yes`

**Comment by tobiasfeil** [comment]
Thank you!
