### ISSUE TITLE
Can I amplify pull a 'preview' environment?

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#4956]
Hi,

We are currently trying the preview feature of Amplify. Can users pull the environment set up by preview or do we have to set up another environment for just that branch? Saves some time if we could use the already set up environment in preview.

**Comment by ammarkarachi** [comment]
@Zanndorin Would you like to pull the (ephemeral) backend environment set up by the preview feature?

**Comment by Zanndorin** [comment]
@ammarkarachi  Sorry I don't understand what ephemeral means in this context.

I would like to pull the environment that is created when a preview backend is set up (we have chosen to setting up a new one for each PR).

**Comment by ammarkarachi** [comment]
I mean the pr-previews in Amplify https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html

**Comment by Zanndorin** [comment]
Yes exactly
