### ISSUE TITLE
Excluding model fields from @searchable

### ISSUE THREAD

**Issue by eripoll** [aws-amplify/amplify-cli#4957]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
I have just added @searchable to an existing @model that contains a lot of fields, some of which being AWSON containing a lot of entries.  Records with too long AWSJON are not streamed to ES because ES refuses them for size reasons.

However, I do not need all these fields to be added to the index.
There is no way for me to control what the py lambda is streaming to ES.

**Describe the solution you'd like**
@searchable could include a list of fields that either should be indexed or should not be indexed, depending which list is shorter.

**Describe alternatives you've considered**
Creating my own lambda but I honestly do no feel like dabbling in the whole CF stack to implement it.

**Additional context**

**Comment by ammarkarachi** [comment]
Hi @eripoll, You could modify the file under `amplify/backend/api/<Api Name>/build/functions/ElasticSearchStreamingLambdaFunction.zip` and replace the zip file to fit your needs

**Comment by eripoll** [comment]
@ammarkarachi I tried that but the next "amplify push" operation overwrote my zip with the one amplify generates...
Any way to avoid this?

**Comment by ammarkarachi** [comment]
@eripoll
The steps I performed to verify this was as follows 
I did created my own function and zipped using the same name `ElasticSearchStreamingLambdaFunction.zip` and checked S3 it was the file which I had altered. Is

**Comment by eripoll** [comment]
@ammarkarachi I created a function and zipped it using the `ElasticSearchStreamingLambdaFunction.zip` name and did 
`amplify push`
The resulting function in the console is NOT the one I just created unfortunately.
As I said, Amplify just replaces whatever I have in build with its own version...

Anyone can help on this?

**Comment by cto-leaps** [comment]
@ammarkarachi Hi again. I still have the issue. I just did a regular amplify push to my production environment and the custom function I had cerated got replaced by the one created by the cli!
It is putting my Elastic Search instances in danger. Could you help?

**Comment by cto-leaps** [comment]
I am still having issues with this. Guys please... 
At least make sure that whatever code I write for the Lambda is not overwritten.
