### ISSUE TITLE
amplify codegen remove invalid subcommand

### ISSUE THREAD

**Issue by ChrisWun** [aws-amplify/amplify-cli#496]
Either the output is wrong, or the command is missing.
![bildschirmfoto 2018-11-23 um 16 34 40](https://user-images.githubusercontent.com/7915105/48951154-cad80b80-ef3d-11e8-9ef4-4309abbcd973.png)

**Comment by kaustavghosh06** [comment]
The output is wrong. We'll fix it.

**Comment by yuth** [comment]
The feature has been released in `0.1.36`
