### ISSUE TITLE
amplify push shows as updating and completing then nothing is synced in the console

### ISSUE THREAD

**Issue by mikeRChambers610** [aws-amplify/amplify-cli#4962]
**Describe the bug**

I am using the command amplify push as I've done so many times before.  It runs the updates to the backend and completes successfully.

Then when I check the backend resources in the AppSync console, I do not see the updates. I also check the cloud formation stack and see that there is no nested stack created for the push.

**Amplify CLI Version**
4.25.0

**To Reproduce**
- Add new Int element to graphql schema (amplify/backend/api/nameofapi/schema.graphQL
- Run amplify status.
- Displays that API has an update.
- Run amplify push.
- CLI outputs successful updating of the back end resources.
- Go to AppSync endpoint in the console. No updates made.
- Go to cloud formation stack. No updates made in the stack.

**Expected behavior**
Amplify push should be updating the AppSync console and should be updating the stack in the cloud formation console.
Amplify push completes successfully when ran but not actually updating any of the resources.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 10.16.3

**Additional context**
I have been using Amplify push for over a year with no issues like this. I am using @searchable but I wouldn't think @searchable would be stopping the backend from being updated.

**Comment by mikeRChambers610** [comment]
Issue is resolve.

I realized that my amplify/.config/local-env-info.json page needed to be updated to point to the new folder name I had change my project to. 

Thanks to:
 https://github.com/aws-amplify/amplify-cli/issues/1442#issuecomment-589807701

**Comment by ammarkarachi** [comment]
@mikeRChambers610 Closing this issue seems to be resolved
