### ISSUE TITLE
[question] - Does now @model always create AmplifyDataStore tables?

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-cli#4965]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.25.0

**What AWS Services are you utilizing?**
Amplify
AppSync
DynamoDB
Lambda

**Provide additional details e.g. code snippets**
Does declaring a GraphQL type using @model directive now create AmplifyDataStore DynamoDB tables? I know they are used for "Delta Sync" feature of DataStore, but I'm not currently using DataStore and I don't remember seeing those tables before.

**Comment by eripoll** [comment]
You're right, I've just seen these tables appearing tonight ouf of nowhere while  I am ont using Datastore either!

**Comment by ammarkarachi** [comment]
Hi @ernestostifano and @eripoll, this is definitely a bug on the Amplify CLI side the workaround would be to edit the file  `amplify/backend/api/is4965/transform.conf.json`
```json 
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "ResolverConfig": {}
}
```
to
```json 
{
    "Version": 5,
    "ElasticsearchWarning": true
}
```

and invoke command `amplify push`

**Comment by edwardfoyle** [comment]
@ernestostifano This issue is fixed in the latest version of the CLI
