### ISSUE TITLE
Update API error

### ISSUE THREAD

**Issue by KevyVo** [aws-amplify/amplify-cli#4971]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
The bug happen when you do update a api pathing with a lamada function. It will delete the api domain section in the api cloud formation. Then when you push it will say there is a missing section called "apidomain" missing from the stack.

**Amplify CLI Version**
Version 4.24.1

**To Reproduce**
1) amplify update api
2)choose REST
3)choose your Api environment
4) Add another path
5) Add your path
6) Make or attach a existing Lambda
7) amplify push

**Expected behavior**
The api should successfully made itself and posted complete on the terminal.  

**Screenshots**
Error of the missing apidomain in the terminal
![Screen Shot 2020-07-22 at 1 36 48 PM](https://user-images.githubusercontent.com/53957494/88849912-6e5fd180-d19f-11ea-9661-7197ba29450b.png)
Before the api was updated
![Screen Shot 2020-07-29 at 1 28 11 PM](https://user-images.githubusercontent.com/53957494/88849862-5b4d0180-d19f-11ea-9e46-21dd12259d4b.png)
After the api was updated
![Screen Shot 2020-07-29 at 1 25 57 PM](https://user-images.githubusercontent.com/53957494/88849654-0c06d100-d19f-11ea-8138-9ed0c855f330.png)

**Desktop (please complete the following information):**
Mac OS
Node: v12.18.0

**Additional context**
I had a work around to the problem. I was first remake my environment and save my api-domain information in the api cloudformation template before I added my new api path. Then after I made my api update I would manually reinject that apidomain section back into the cloudformation template that was delete. Once that all done my api was push and successfully completed.

**Comment by ammarkarachi** [comment]
@KevyVo Can you let me know how you updated the API domain output in the CFN?

**Comment by KevyVo** [comment]
I used amplify to update it but I found a way around it. I save the lines that were missing before creation and then go back in adding them to the missing part of the cloudformation files before I push again.

**Comment by ammarkarachi** [comment]
@KevyVo we have released override for API and you can use the `override.ts` file generated after running `amplify override api` so that the your changes are preserved 

```js
import { AmplifyApiRestResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';
export function override(resources: AmplifyApiRestResourceStackTemplate) {
    resources.addCfnOutput(props, 'logicalId');
}

```
