### ISSUE TITLE
preserve comments on a graphql API for documentation in the API explorer?

### ISSUE THREAD

**Issue by olivoil** [aws-amplify/amplify-cli#4973]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.26.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
The AppSync API Explorer documentation states the following:

```
GraphQL Documentation

GraphQL APIs are fully self documenting. 
Use the documentation explorer on the right of the query editor to view your API definition. 
Add comments above the fields and types in the schema page to add your own documentation, which will be visible here.
```

But it seems Amplify CLI strips out all the comments from graphql schemas when pushing the API.
Is there a way to preserve the comments so that they show up in the API Explorer documentation?

**Comment by CurtisHumphrey** [comment]
Related to #1393

**Comment by SwaySway** [comment]
Closing in favor of #1393
