### ISSUE TITLE
Changing folder name of the project makes amplify command no longer work

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4974]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I renamed my project folder from `my-project` to `my-old-project`, when I tried to run `amplify env list` on it, amplify threw an error saying that `/my-project` folder does not exist when I ran the command inside of `my-old-project`. I'm not sure if there's anything local that needs to be updated when you change the folder name.

**Amplify CLI Version**

4.25.0

**To Reproduce**

- Rename folder of an existing project with amplify, `my-project` to `my-old-project` as an example.
- do `cd my-old-project` then `amplify env list`.

**Expected behavior**

Not sure.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.4.0

**Additional context**

**Comment by ammarkarachi** [comment]
@aprilmintacpineda you would need to update the project path specified under `amplify/.config/local-env-info.json`.
