### ISSUE TITLE
Version 4.26.0 doesn't propagate Graphql Api auth

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-cli#4986]
**Describe the bug**
Since Upgrade to 4.26.0 we have Authorization issues with nested items into Graphql Api after an Api update.
Here is the type ok error message we get : "Not Authorized to access directoryItem on type FilesContactsShared"
If we push with an older version, everything works well. 

**Amplify CLI Version**
4.26.0

**Comment by mlafo** [comment]
Some additional information : 
issues appears with the 4.24.3 version.

Schema exemple : 

```
type File
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownerId", identityClaim: "sub" }
      { allow: private, provider: iam }
    ]
  )
  @searchable {
  id: ID!
  ownerId: String
  name: String!
  size: Int
  type: String
  path: String
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  lastSharedAt: AWSDateTime
  SharedWith: [FilesContactsShared]
    @connection(
      name: "FilesContactsSharedWith"
      sortField: "sharedAt"
      limit: 50
    )
}

type FilesContactsShared
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownerId", identityClaim: "sub" }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  ownerId: String
  directoryItem: Directory @connection(name: "ContactsFilesSharedWith")
  file: File @connection(name: "FilesContactsSharedWith")
  sharedAt: AWSDateTime
}

type Directory
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "ownerId", identityClaim: "sub" }
      { allow: private, provider: iam }
    ]
  )
  @searchable {
  id: ID!
  ownerId: String
  userId: String
  email: String
  firstName: String
  familyName: String
  filesSharedWith: [FilesContactsShared]
    @connection(name: "ContactsFilesSharedWith")
}
```

**Comment by SwaySway** [comment]
@mlafo What type of entity made the request that gives you this error? Did you try a list query signing as the owner or as a private iam user?

**Comment by mlafo** [comment]
@SwaySway File Type entity made the issue throw a listFiles or a searchFiles request as the owner auth.

**Comment by davekiss** [comment]
@mlafo did you ever figure this out? Think I may be running into this issue as well

**Comment by mlafo** [comment]
@davekiss I dont really know, because we stayed under 4.24.3 version. We didn't upgade since  August, waiting for resolution. 
I'll try to check it out.

**Comment by lookitsatravis** [comment]
Also seeing this issue with CLI version 4.30.0.

**Comment by SwaySway** [comment]
@mlafo Are you still experiencing issues with this? I was not able to repro below is what I tried

Based on this error
```
Not Authorized to access directoryItem on type FilesContactsShared
```
It looks like it came from a list query on the `type FilesContactsShared`
I created a FilesContactShared (with a linked File and Directory) and I was able to get the result. 
Also This was all done with one user.


Could you possible provide more details such as:
- Was there more than one user?
 - If so could you provide a set of repro steps (ex. If directory record was made with userA and file was made with userB)
- What is the default mode of auth?

**Comment by SwaySway** [comment]
Closing this issue due to lack of information. Please comment below to re-open.
