### ISSUE TITLE
Could not find the AppSync API when pushing GraphQL API

### ISSUE THREAD

**Issue by shawnlauzon** [aws-amplify/amplify-cli#499]
**Describe the bug**
I added a GraphQL API. When asked to generate code, I said Y. When I tried to push, many AWS::AppSync::Resolver objects seem to be created, but when attempting to update the API resource, it fails with:

> Could not find the AppSync API. If you have removed the AppSync API in the console run amplify codegen remove

I had not removed anything manually. I also tried running `amplify codegen add` and then push again, but got the same error. Also, `amplify codegen remove` gives an error "invalid subcommand".

**To Reproduce**
1. `amplify auth`
2. Take defaults
3. `amplify push`
4. Take more defaults (code gen angular, probably doesn't matter)
5. See failure

**Expected behavior**
The push should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/48964822-c16e9380-ef7d-11e8-8eca-2c82750d0ae9.png)

![image](https://user-images.githubusercontent.com/611529/48964848-8751c180-ef7e-11e8-90d0-c8235fb90c35.png)

![image](https://user-images.githubusercontent.com/611529/48964837-435ebc80-ef7e-11e8-99ee-f67c7167d96d.png)

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

**Comment by yuth** [comment]
From the error message it looks like the Codegen config is has the wrong API id. We will add an option to remove codgen config is reported in #496 but in the mean time you could remove the configuration by deleting `.graphqlconfig.yml` from your project root and run `amplify codegen add`

**Comment by kaustavghosh06** [comment]
This issue is fixed and merged with this PR ->  #510
Please feel free to re-open this issue if the problem still persists.
