### ISSUE TITLE
Ability to download schema remotely

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#4994]
## Problem
I would like the ability to download the schema remotely.  Example: `GET myapp.com/graphql` and it return the graphql document.

## Why
The reason I want to do this is expose my schema for users to query and have documentation generators be able to pull this without having to run a cli command.

## Notes
After reviewing the code, it looks like there is quite a bit of black magic that the CLI uses to download this which is not friendly to other toolchains.

**Comment by SwaySway** [comment]
Hello @amcdnl 
The CLI uses the [Get Introspection Schema](https://docs.aws.amazon.com/appsync/latest/APIReference/API_GetIntrospectionSchema.html) from AppSync's API. Would that fit your use case? You can add that behind a REST/graphql API and have it make the sdk call in a lambda if needed (as a potential solution).

**Comment by amcdnl** [comment]
I think that will work. Thank you!

**Comment by amcdnl** [comment]
For others who are encountering this problem, here is my code result:

```ts
import { AppSync } from 'aws-sdk';
import { Request, Response } from 'express';
import ono from '@jsdevtools/ono';

const client = new AppSync();

const apiId = process.env.API_API_GRAPHQLAPIIDOUTPUT as string;
const apiKey = process.env.API_API_GRAPHQLAPIKEYOUTPUT as string;

export async function schemaHandler(req: Request, res: Response) {
  try {
    const req = client.getIntrospectionSchema({
      apiId,
      format: 'JSON',
      includeDirectives: true
    });

    req.on('build', () => {
      req.httpRequest.headers['x-api-key'] = apiKey;
    });

    const result = await req.promise();

    return res.type('application/json').send((result.schema as any).toString());
  } catch (error) {
    throw ono({ status: 500 }, `Failed to get schema`);
  }
}
```
