### ISSUE TITLE
Question about AWS Toolkit and Visual Studio Code

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#4996]
Hello,

Just wanted to know what IDE you use to modify your lambda functions. Do you use Sublime Text or something more advance?

Is there any advantage using Visual Studio Code and AWS Toolkit? 
I don't see any support for Amplify.
https://aws.amazon.com/visualstudio/
At least I see autocompletion working, inline help, and I can use a normal terminal to run "amplify push"

Any suggestions about your workflow when writing lambda?
Thanks a lot.

**Comment by undefobj** [comment]
Amplify team has no preferences on which IDE you use, however the VS Code Toolkit has some extensions that make building .NET applications easier and might make sense if those are the types of applications which you will be building. If you are using this you might want to take a look at the Amplify VSCode extension which has some nice code snippets as well: https://marketplace.visualstudio.com/items?itemName=aws-amplify.aws-amplify-vscode
