### ISSUE TITLE
How to connect a new amplify front end project to an existing back end 

### ISSUE THREAD

**Issue by SidKB** [aws-amplify/amplify-cli#4997]
Hi,

Can someone give me a heads up to connect a new frontend app to existing amplify project backend?

**Comment by akshbhu** [comment]
Try to follow these steps to first recover, and then add a new backend Env if you want to.

1. ```amplify pull --appId <your-project-appId> --envName <your-existing-backend-env>```
2.  ```amplify init``` and select the existing backend env if prompted
Now your amplify folder structure is fully setup, they you can add new backend env by```amplify env add```

You can also take a look at documentation here: https://docs.amplify.aws/cli/usage/headless#amplify-pull-parameters

**Comment by SidKB** [comment]
Thank you.
