### ISSUE TITLE
New user setup failed - you did NOT enter valid keys

### ISSUE THREAD

**Issue by kewp** [aws-amplify/amplify-cli#4998]
**Describe the bug**
Following the steps to setup a new user on the CLI but getting an error when entering keys:

```
Enter the access key of the newly created user:
? accessKeyId:
? secretAccessKey:

You did NOT enter valid keys.
New user setup failed.
Error: New user setup failed.
    at context.amplify.pressEnterToContinue.run.then.then.then.then.then.then (C:\Users\karlp\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\setup-new-user.js:108:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Amplify CLI Version**

```
c:\users\karl>amplify -v
4.26.0
```

**Desktop**
 - OS: Windows
 - Node Version. 8.12.0

**Comment by akshbhu** [comment]
Hi @kewp 

This issue seems to be related to the wrong accesskeysId or secret. You can check the documentation here using amplify configure to setup the user : https://docs.amplify.aws/cli/start/install#option-2-follow-the-instructions.

Let me know if this works for you?

**Comment by kewp** [comment]
Hi @akshbhu. The link you sent are the steps I followed.

**Comment by MatthewJiao** [comment]
getting problem issue as well

**Comment by akshbhu** [comment]
Hi @kewp 

I just tried it on windows and I was able to configure. Can you upgrade node version and try again?

**Comment by kewp** [comment]
Hey @akshbhu. I just tried again with node v12.16.2. Same thing.

**Comment by UnleashedMind** [comment]
I'm not able to reproduce either. 
Did you copy the keys from the AWS IAM console and paste the keys as command line input?

**Comment by kewp** [comment]
Click return at the prompt? Not sure where else I would copy the keys from?

**Comment by UnleashedMind** [comment]
could you try to enter any string at the prompt and see if the error is still there?

**Comment by kewp** [comment]
Any string? You think that a random string will somehow work? Come on...

**Comment by UnleashedMind** [comment]
my point is, you need to enter something at the prompt then click on the "return" button, otherwise you will get the error message. that was a very simple validation rule to prevent people from blindly click on the enter button.

**Comment by kewp** [comment]
Ok. Well... it does seem like when I type in junk it goes further.

When I ctrl-v (paste) it does change (the brackets `[hidden]` change) but it's blank - no dots like when you type.

So no pasting? The keys are so long!

**Comment by UnleashedMind** [comment]
That's because your short cut "ctrl-c" or "ctrl-v" is not working as expected, please check on them.

**Comment by kewp** [comment]
They are. I checked over and over that the paste was working (in a text editor). There is something wrong with the amplify console script.

**Comment by UnleashedMind** [comment]
Try this: 
1. Copy the keyid and key  to a plain text editor (not word), check they are correct.
2. select and copy again from the text editor, and then paste on the terminal console when the Amplify CLI prompt you.

**Comment by kewp** [comment]
Come on dude. This conversation is just going round and round. What you describe is what I did right at the start.

**Comment by renebrandel** [comment]
@kewp are you free to jump on a call real quick? I'm curious on how to reproduce this

**Comment by kewp** [comment]
@renebrandel yeah sure, how do you want to call?

**Comment by renebrandel** [comment]
DM me on twitter: twitter.com/renebrandel

**Comment by kewp** [comment]
Thanks for the call. So just for anyone who's interested - amplify uses node and for some reason on my machine (not sure if others too) you can't ctrl-v into node. However, right-click (to paste) works.

I've tested this on two machines: both Windows 10. Both from command prompt. One uses node v8. The other node 12.

**Comment by UnleashedMind** [comment]
Thanks @kewp for the detailed information.

**Comment by kewp** [comment]
No problem, @UnleashedMind . Thank you for the help

**Comment by MatthewJiao** [comment]
@kewp thanks for starting this thread! It turns out, I wasn't able to ctr-v into node either. Bless everyone for being such a supportive community :P

**Comment by kewp** [comment]
Hey @MatthewJiao my pleasure, so glad it helped you :)

**Comment by cricketplayer** [comment]
@kewp  helped me too. Thanks for persisting.
