### ISSUE TITLE
Auth Permissions implementation

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#5000]
When using amplify @auth directive connected to aws cognito, do you guys find any drawbacks implementing this kind of approach? 

![image](https://user-images.githubusercontent.com/3125784/89134649-2eab3800-d559-11ea-81a2-cd6838659c8e.png)

![image](https://user-images.githubusercontent.com/3125784/89134691-7fbb2c00-d559-11ea-8fe9-c3830eeb871e.png)

**Comment by akshbhu** [comment]
Hi @incr3m 

For quick suggestions you can post this on our discord page : https://discord.com/channels/705853757799399426/717109738101407866

**Comment by akshbhu** [comment]
Hi @incr3m 

we don't support regex in the group field.
for ex
```
["project.*"]
```
