### ISSUE TITLE
mock throws error on non-existent fields

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-cli#5003]
**Describe the bug**
Consider the following schema (taken from the [docs](https://docs.amplify.aws/cli/graphql-transformer/directives#field-level-authorization)):
```
type User @model {
  id: ID!
  username: String
  ssn: String @auth(rules: [{ allow: owner, ownerField: "username" }])
}
```

Now when creating a user (assuming we have a token with a username of `username`) like this:
```
mutation MyMutation {
  createUser(input: {id: "id", username: "username"}) {
    id
    ssn
  }
}
```
and then querying them like this:
```
query MyQuery {
  getUser(id: "id") {
    id
    ssn
  }
}
```
it throws an error:
```
{
  "data": {
    "getUser": {
      "id": "id",
      "ssn": null
    }
  },
  "errors": [
    {
      "message": "Unable to convert $util.toJson($context.source.ssn)\n to class com.amazonaws.deepdish.transform.model.lambda.LambdaVersionedConfig.",
      "errorType": "MappingTemplate",
      "data": null,
      "errorInfo": null,
      "path": [
        "getUser",
        "ssn"
      ],
      "locations": [
        {
          "line": 18,
          "column": 5,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```
Apparently, this is caused by the `ssn` being `null`.

Additionally, when updating the `ssn` and querying for the `ssn` field in this mutation:
```
mutation m {
  updateUser(input:{id:"id", ssn:"ssn"}) {
  	id
  	ssn
  }
}
```
it doesn't return the `ssn` properly but `null` instead:
```
{
  "data": {
    "updateUser": {
      "id": "id",
      "ssn": null
    }
  }
}
```
When querying for the `ssn` in a query afterwards, everything works as expected:
```
query MyQuery {
  getUser(id: "id") {
    id
    ssn
  }
}
```
Response:
```
{
  "data": {
    "getUser": {
      "id": "id",
      "ssn": "ssn"
    }
  }
}
```

**Amplify CLI Version**
4.24.3

**To Reproduce**
See above

**Expected behavior**
The queries and mutations to work properly

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Node version: 14.7.0

**Comment by SwaySway** [comment]
Hello @tobiasfeil 
The first case should return null the value was not set. Though returning null as an error seems specific to mock which is something we can investigate into looking why it throws that specific error.

The second case returns null on the mutation so it can protect the subscription response.
Read more on that here: https://docs.amplify.aws/cli/graphql-transformer/directives#authorizing-subscriptions

**Comment by tobiasfeil** [comment]
Thanks for the response! OK I'll just ignore the error for now then.

**Comment by tobiasfeil** [comment]
Found out I can't just ignore it because it actually throws an error. Therefore, for now, I have to fetch my data like this:

```
try {
      await API.graphql(
        graphqlOperation(listItems)
      )
    } catch (e) {
      this.data = e.data
    }
```
It would be nice to have this taken care of sooner rather than later.

**Comment by tobiasfeil** [comment]
Dangit, if I do it like this, the other limitation kicks in where field-level @auth protected fields return null in mutations... This is a bit tricky
