### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.when using Pinpoint with Cognito and User groups

### ISSUE THREAD

**Issue by eripoll** [aws-amplify/amplify-cli#5004]
**Describe the bug**
I have been using Cognito and user groups without any issue for a vue-based front-end project running on Amplify with a graphql backend.
I tried adding Pinpoint using the CLI, the push seems to be creating a pinpoint resources and to be updating my Userpool but I get a "No 'Access-Control-Allow-Origin' header is present on the requested resource." when trying to record an event. 

**To Reproduce**

1. Add auth to a basic project
2. create user groups
3. add a user to one of the groups
4. add pinpoint and try to record an event with an authenticated user

**Expected behavior**
The record should be sent to Pinpoint

**Code Snippet**
No specific code added

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:

in order of addition to the project
- Auth
- API
- Hosting
- Storage
- Function
- Analytics

**Comment by ammarkarachi** [comment]
I confirmed this closing in favor of #4772
