### ISSUE TITLE
`amplify env list --details` shows [Object object] for auth & functions

### ISSUE THREAD

**Issue by renebrandel** [aws-amplify/amplify-cli#5005]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Run `amplify env list --details` and get this output:
```
dev
--------------
Provider: awscloudformation
AuthRoleName: XYZ
UnauthRoleArn: XYZ
AuthRoleArn: XYZ
region: us-west-2
DeploymentBucketName: XYZ
UnauthRoleName: XYZ
StackName: XYZ
StackId: XYZ
AmplifyAppId: XXXXX
--------------

Provider: categories
auth: [object Object] #<--- see here?
function: [object Object] #<--- see here?
--------------
```
Check the "#<-- see here?" for the issue

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.25.0

**To Reproduce**
Add `auth` and `function` resources.
Run `amplify env list --details` 

See how it renders properly when I run `amplify env list --details --json`

**Expected behavior**
A list of auth & function resource names

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: Irrelevant.

**Additional context**

**Comment by akshbhu** [comment]
We can change this , We need to know the expected output.
