### ISSUE TITLE
Trying to connect to existing project backend (with code gen) on Android

### ISSUE THREAD

**Issue by Diederikjh** [aws-amplify/amplify-cli#5006]
**Which Category is your question related to?**
Getting schema files pulled from existing project on shared AWS account.

**Amplify CLI Version** 
4.25.0 running on Ubuntu

**What AWS Services are you utilizing?**
For DynamoDB, AppSync, cognito(?)

**Provide additional details e.g. code snippets**

I want to connect an existing AppSync project to my Android project. (Thought I'd log this here, as it seems more to do with the cli).  

I've run `amplify init` and `amplify add codegen --apiId <project ID>` this seems to work (as pointed out by the "Integrate with your app" section on the AppSync AWS console), and when I run `amplify status` it returns what I think looks right:
```
Current Environment: dev

| Category | Resource name   | Operation | Provider plugin |
| -------- | --------------- | --------- | --------------- |
| Api      | <appname>sync-dev | No Change |                 |

GraphQL endpoint: https://<more text>.appsync-api.<region>.amazonaws.com/graphql
```

When I run `amplify codegen`
It outputs:
```
✔ Downloaded the schema
✔ Generated GraphQL operations successfully and saved at <appname>/src/main/graphql/com/amazonaws/amplify/generated/graphql
```

When I run `amplify codegen model` (As I understand it: the command to run when you want the actual java files to be generated for use in your Android application) it doesn't seem to work: it just says 

> No AppSync API configured. Please add an API

Which I find unexpected, given the output of `amplify status`.

Am I missing something?

The project folder I'm working in did contain a previous local only api (where I manually added the graphql files), but I removed the amplify folder and `.graphqlconfig.yml` and `amplify.json` before running amplify init again.

I've tried running `amplify pull` but if I do, things start breaking even more: (status doesn't report anything being present after that).

I've been following the startup tutorial for [datastore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android) to some degree, but since we want to start from an existing project, it hasn't gone smoothly.

**Comment by Diederikjh** [comment]
I was looking at the AppSync console (which wants you to do an Init first, then a codegen add which doesn't look right?)  

Going to the **Amplify** console showed me the correct app ID that I should have used. Now when I run `amplify pull --appId <correct Amplify App id> --envName <env name>`  it pulls down the correct files.

Then running  `amplify codegen add` and  `amplify codegen model` seems to have sorted out my problem.

Now if you'll excuse me, I have to ceanup all the resources `amplify init` created.

**Comment by akshbhu** [comment]
Hi @Diederikjh 

Nice to know that it worked using amplify pull.  I will look into why the first approach failed.

**Comment by akshbhu** [comment]
Currently the CLI does not support this as amplify codegen models works based on an api that is created from the CLI. As codegen does not look at the introspection schema when generating the models.
If you are facing any other problems related to this , feel free to reply and I will reopen this issue again
