### ISSUE TITLE
Feature request: Indicative costs

### ISSUE THREAD

**Issue by struct78** [aws-amplify/amplify-cli#5016]
Recently I realised I had been stung for over $750 (my bad for not checking invoices for many months) after I added the @searchable directive to my GraphQL schema, but forgot about it as my focus shifted to other features that weren't search related.

It would be great if the CLI could give us indicative costs of services, or at least warnings or expensive services like Elastic Search when they are added, especially since the CLI abstracts a lot of the actual services away from the user, which makes using things like the AWS calculator difficult to use/costs hard to predict.

I am also not sure if this has been solved in newer versions of the CLI, but when I removed the @searchable directive, the Elastic Search service continued to run and had to be removed manually (this was after I discovered the high costs associated with it)

**Comment by abstractpoint** [comment]
One solution could be to set up a budget alerts (under billing) and use a "forecasted" figure, that one the moment you create a service you should get an alert if forecast exceeds your threshold.

I personally think that it's not worth bloating an already arguably bloated cli utility to add this.

**Comment by josefaidt** [comment]
Closing as a "wontfix" in favor of the built-in functionality in the AWS Console for billing.
