### ISSUE TITLE
No data source found

### ISSUE THREAD

**Issue by Somtozech** [aws-amplify/amplify-cli#5017]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

I have a custom resolver function that doesn't require a data source. All the resolver does is add the appsync API id and the env to $ctx.stash so other functions in the pipeline can access it. I made the DataSourceName NONE (since it doesn't require a data source).  But I keep getting this error (No data source found named NONE).
![image](https://user-images.githubusercontent.com/32250849/89388084-6b169980-d6fb-11ea-97da-f26d1f95c203.png)

My question is how do I create a custom resolver function without a data source 
This is my custom resolver function 
```
	"addEnvVariablesToStash": {
			"Type": "AWS::AppSync::FunctionConfiguration",
			"Properties": {
				"ApiId": {
					"Ref": "AppSyncApiId"
				},
				"DataSourceName": "NONE",
				"Description": "Sets $ctx.stash.env to the Amplify environment and $ctx.stash.apiId to the Amplify API ID",
				"FunctionVersion": "2018-05-29",
				"Name": "addEnvVariablesToStash",
				"RequestMappingTemplate": "{\n          \"version\": \"2017-02-28\",\n          \"payload\": {}\n        }",
				"ResponseMappingTemplate": {
					"Fn::Join": [
						"",
						[
							"$util.qr($context.stash.put(\"env\", \"",
							{ "Ref": "env" },
							"\"))\n$util.qr($context.stash.put(\"apiId\", \"",
							{ "Ref": "AppSyncApiId" },
							"\"))\n$util.toJson($ctx.prev.result)"
						]
					]
				}
			}
		},
```

**Comment by SwaySway** [comment]
When writing a resolver that is pointing to a `NONE` datasource you will need to create the datasource as well.
Docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-datasource.html#cfn-appsync-datasource-type
Resolver Docs:
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-none.html

Should you have further questions on writing your own custom resolvers we recommend our community discord: https://discord.gg/jWVbPfC
