### ISSUE TITLE
Verifiying email when using passwordless login.

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5019]
My app uses passwordless login (no emails in the process, just a text message), which is working fantastically.
This logic and lambda functions are explained here:
https://github.com/mobilequickie/amplify-passwordless-sms-auth

I would like to implement a feature that allows users to add their emails optionally (after they created an account, in the future), for notifications, and potentially recovering the account if they lost the phone number. 

I guess I can create a GraphQL mutation, that using a lambda function, connects to Cognito, and saves the email the user wants to set up.
My question is, in this case, can Cognito send an email so users can verify their emails? I don’t want to send emails to fake or unverified emails. 
Let me remark this is not to login, signup, MFA, or anything like that. 

If that is possible, how do I trigger that logic? I only see lambda triggers in Cognito setup.

Reading docs I don’t see this scenario.
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

Any idea? Thanks a lot.

EDIT: I realised that maybe there is another way. Let the iOS SDK (the client) do that.

If I call this, then the email is saved properly in the cognito user and verified_email attribute is false, which is OK.
```
AWSMobileClient.default().updateUserAttributes(attributeMap: ["email": "myemail@email.com"]) { userCodeDeliveryDetails, error in           
   print("")        
}
```

And in theory, if I call this, I should trigger the verification process.
```
AWSMobileClient.default().verifyUserAttribute(attributeName: "email") { userCodeDeliveryDetails, error in
   print("")
}
```

But when I call that, I receive an email that says:
"Your verification code is 924374"
which is what I receive in the passwordless login, through SMS.
Looks like the custom flow is triggered (my custom 4 lambda functions used by the passwordless login).
Evidently this does not make any sense to me. I should receive a link to verify the email.
What can I do?
Can I have 2 flows? default one for email (to verify it) and passwordless login (sms, to login or signup)

Thanks a lot for suggestions.

**Comment by akshbhu** [comment]
Hi @Ricardo1980 

For quick suggestions you can post this on our discord page : https://discord.com/channels/705853757799399426/717109738101407866

**Comment by kaustavghosh06** [comment]
@Ricardo1980 You can formulate your own email link and attach the one-time code to the URL and then form the client/website itself use custom-auth to authenticate the user utilizing the pre-auth trigger. 
Did you have that a shot?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.

**Comment by Ricardo1980** [comment]
@kaustavghosh06 
"You can formulate your own email link and attach the one-time code to the URL and then form the client/website itself use custom-auth to authenticate the user utilizing the pre-auth trigger."
The thing is, I don't want to use the email for login. Let me reformulate my question:

Is it possible to have passwordless login (using phone number, no email/password/username for login) and at the same time having OPTIONALLY the possibility to add an email that is not used in the login sequence that can be verified automatically sending an email with a code?

I solved this implementing my own logic with 2 lambda functions and API Gateway (my project uses AppSync), and saving codes and timestamps in my RDS database. 
I don't know if that is the proper way, but it is working. Seems to me this is overkill.

Can I have your opinion?

The use case is for example Discord, where the email is optional, you can add it whenever you want and verify it at any time. Or for example "Dil Mil", a dating app that you login using your phone number (no username, password, email) at optionally, at any time, you can add an email (and verify it). That is what I want.

Thanks a lot!
