### ISSUE TITLE
What is the proper way to get the current user email in a lambda function?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5020]
What is the proper way to get the current user email in a lambda function?

When executing a lambda function, the event object contains:

```
{
  "typeName": "Query",
  "fieldName": "...",
  "arguments": {
      ...
  },
  "identity": {
      "claims": {
          "sub": "3d5f858c-f29f-4a82-89dd-XXXXXXXX",
          "email_verified": false,
          "iss": "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_XXXX",
          "phone_number_verified": true,
          "cognito:username": "3d5f858c-f29f-4a82-89dd-XXXXXXXX",
          "aud": "43dja5g82nsid4pXXXXXXXXX",
          "event_id": "ac68618f-0b71-4fb1-87be-XXXXXXXX",
          "token_use": "id",
          "auth_time": 0000000,
          "name": "test name",
          "phone_number": "+4478499999999",
          "exp": 1596659999,
          "iat": 1596699999,
          "email": "dasds@dadasds.es"
      },
      "defaultAuthStrategy": "ALLOW",
      "groups": null,
      "issuer": "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_xxxxxxxxx",
      "sourceIp": [
          "147.12.249.111"
      ],
      "sub": "3d5f858c-f29f-4a82-89dd-xxxxxxx",
      "username": "3d5f858c-f29f-4a82-89dd-xxxxxxxx"
  },
  "source": null,
  "request": {
      ....
  },
  "prev": {
      "result": {}
  }
}
```

is it OK to extract the email using 
`event.identity.claims.email `
for the current cognito user?

I haven't found documentation about that.
I saw something in the appsync docs, but probably unrelated.
Here I see that claims means: "The claims that the user has.". But not sure about that.
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity

Thanks for suggestions.

**Comment by sw-yx** [comment]
i think you have it right, for generic functions! 👍 

note that [lambda triggers](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#lambda-triggers) also attach it onto `event.request.userAttributes.email`. example here: https://dev.to/aws/building-a-serverless-jamstack-ecommerce-store-with-gatsby-aws-303f#authentication

the claims thing is unrelated i think

**Comment by Ricardo1980** [comment]
Thanks!
