### ISSUE TITLE
Amplify CLI creates an `amplify.json` file in the project root directory

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-cli#5024]
**Describe the bug**

Even though we create a separate `amplify` directory, the CLI now creates an `amplify.json` file in the project root directory.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.26.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. `amplify init`
1. `ls`
1. See amplify.json; experience mild curiosity.

**Expected behavior**

I'd expect this file to reside in the `amplify` directory rather than adding footprint to our customers' project root directory.

**Screenshots**

Not applicable.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]: macOS 10.15.6
 - Node Version. You can use `node -v` to check the node version on your system: 14.2.0

**Additional context**

None.

**Comment by akshbhu** [comment]
Hi @jpignata 

The file is to support feature flags for existing and new projects created by amplify cli.You can find the details of feature flags and ```amplify.json```file here : https://docs.amplify.aws/cli/reference/feature-flags
