### ISSUE TITLE
Receiving a "Cannot GET /apipath" error when trying to list objects

### ISSUE THREAD

**Issue by pendraggon87** [aws-amplify/amplify-cli#5025]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I created a test project by adding dynamodb storage with just one column called "fqdn".  I created a REST API and a Lambda function using the CRUD template.

When I try to do a GET /domains (my api path), I get the following:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot GET /domains/</pre>
</body>

</html>
```

it looks like there is no way to get the list of all objects in the db?

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by pendraggon87** [comment]
At a minimum, maybe this can be a feature request to have a scan operation as the default?

**Comment by Blkc** [comment]
It is dynamodb which means scan operation is expensive. GET on dynamodb would always imply that you are passing in a primary key. Even on REST API terms you would also pass in an id.

**Comment by akshbhu** [comment]
Hi @pendraggon87 

Can you mail your amplify folder at amplify-cli@amazon.com with the issue no. as subject?

**Comment by ammarkarachi** [comment]
Closing this, don't hesitate to reopen if you are still facing this issue
