### ISSUE TITLE
How do I include an existing cloudformation stack into Amplify's backend

### ISSUE THREAD

**Issue by wsun66** [aws-amplify/amplify-cli#5029]
I already have an existing cloudformation stack that includes appsync, lambda, and dynamodb resource. I'd like to add it directly as a backend to my new application through Amplify. This way, I can use Amplify to manage the whole project. How do I do it?

**Comment by SwaySway** [comment]
We currently don't support importing resources into an Amplify project. Though we do have an open RFC for it here: https://github.com/aws-amplify/amplify-cli/issues/3977

Closing in favor of the RFC.
