### ISSUE TITLE
Cognito Adding To Group

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-cli#5030]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito, Amplify
** Provide additional details e.g. code snippets **
So i'm working on a project that uses 3 roles and for simplicity I will call them User, Editor, Admin.
When I setup auth I was able to order the groups and by default User is the group people are added to.

I have rewritten now a new signup menu because the default withAuth menu has limitations and isn't documented on how to add custom fields or a profile picture etc. So my new menu has all these fields and at the bottom a switch, if ON then add the user to editor, if not add user to group. I originally planned to use twilio to do verification for the groups but it seemed like a waste of time for now. 

What I can't seem to figure out is, how can I pass this switch state to say postConfirmation? What I would like to do is let users choose a role in the signup process but i'm unsure how to even pass data to the lambda function. I have no idea were it is called, as far as I understand postConfirmation exists and just works. It gets the group and user information in the add-to-group.js and runs. So how can I tell it to add a user based on the switch?

**Comment by sammartinez** [comment]
Transferring to Amplify CLI to see if they have any insights on their side for the lambda function configuration cc @renebrandel

**Comment by Rafcin** [comment]
I think we could possibly close this. I managed to solve the issue by using the metadata parameter and passing the selected group to the lambda function.

**Comment by sammartinez** [comment]
Understood, resolving. Thanks for responding back quickly to us @Rafcin !

**Comment by Rafcin** [comment]
Np, sorry I kept it open. I'll actually go look through older cases and close and upload solutions if I found any. 

For this issue if anyone is curious you can use ``clientMetadata.```, a parameter that exists for a few various actions listed at https://aws-amplify.github.io/amplify-js/api/classes/authclass.html

When you execute a confirmation or any other supported action you can pass any value to clientMetadata and in your lambda function read it as ```event.request.clientMetadata.{name}```. In my case it was ```event.request.clientMetadata.signup_group```
