### ISSUE TITLE
Does the GraphQL Transformer support Subscriptions with arguments?

### ISSUE THREAD

**Issue by azahran007** [aws-amplify/amplify-cli#504]
** Which Category is your question related to? **
GraphQL Transformer, VTL

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
Is there a way to create a subscription that accepts specific arguments in the annotated schema? Such as a subscription for comments on a particular Blog post:

```
type Subscription {

   onCreateComment(postId: ID!) @aws_subscribe(mutations: ["createComment"])

}
```

And if not yet supported, is there a way to add it as a "pass-thru" so it ends up in the final schema? Currently adding it and running Amplify push deletes it from the annotated schema, not sure if that is by design or is a defect.

**Comment by kaustavghosh06** [comment]
Closing this issue. Feel free to re-open if you've any questions related to this issue.

**Comment by timoteialbu** [comment]
> In the future, the goal would be to generated correctly parameterized subscriptions automatically based on your @auth and @connection directives in the model.

When can we expect that? I am trying to write a custom subscription using the owner as input, but I think it doesn't work because the owner is not explicitly defined in the table's schema.

**Comment by RidClick** [comment]
I need some help here.
The APIService generated by codegen has generated this function.

```
SubscribeToNewMessageListener: Observable<SubscribeToNewMessageSubscription> = API.graphql(
    graphqlOperation(
      `subscription SubscribeToNewMessage($conversationId: ID!) {
        subscribeToNewMessage(conversationId: $conversationId) {
          __typename
          author {
            __typename
            cognitoId
            id
            username
            registered
          }
          content
          conversationId
          createdAt
          id
          isSent
          recipient {
            __typename
            cognitoId
            id
            username
            registered
          }
          sender
        }
      }`
    )
  ) as Observable<SubscribeToNewMessageSubscription>;
```

I'm trying to call this listener from an angular page but I can not pass the parameter to the function
always get "Variable 'conversationId' has coerced Null value for NonNull type 'ID!'".
I have tried in all ways but I can not send it.

This is more or less my code.

```
constructor(
        private api: APIService
    ) {}

    ngOnInit() {
        this.api.SubscribeToNewMessageListener
        .map(msg => msg.conversationId = 'randomGUID')
        .subscribe({
            next: (x) => {console.log('Next',x)},
            error: (e) => {console.log('Error', e)},
            complete: () => {}
        })
    }
```


Another subscription without parameters, however, it works for me simply by subscribing to it.

Please need help.
Thanks you.

**Comment by Loghrenar** [comment]
Hey @RidClick,

I'm stuck at this point too, did you manage to get rid of this problem? Have you found a solution?
Thanks in advance.

**Comment by Loghrenar** [comment]
Hey @RidClick,

I'm stuck at this point too, did you manage to get rid of this problem? Have you found a solution?
Thanks in advance.

**Comment by rawadrifai** [comment]
@mikeparisstuff -- pleeeeeeeeeeeeez add parametrized subscriptions. It's such a big hole in the framework. Actually it renders it unusable for most real-time apps.

**Comment by Flos** [comment]
Im also a bit lost here. So codegen creates code which is not working when you need an argument as owner for a subscription or? Or how can I pass the owner as input to the subscription in Angular with the generated code?

amplify --version --> 3.0.0
