### ISSUE TITLE
Failed to start API Mock endpoint TypeErrorFailed to start API Mock endpoint TypeError

### ISSUE THREAD

**Issue by mike-neck** [aws-amplify/amplify-cli#5044]
**Describe the bug**

I'm new to aws amplify so than I was trying [an official tutorial](https://docs.amplify.aws/start/getting-started/installation/q/integration/react). When I ran a mock api as described in a section titled "Connect API and database to the app" in that document, it failed to start. Since a terminal shows only the error message, I cannot find the cause of this error.

**Amplify CLI Version**

- amplify version:  `4.27.0`

**To Reproduce**

Do the steps written in the tutorial document.

```
npx create-react-app example-tutorial --typescript
cd example-tutorial
yarn start
amplify init
yarn add aws-amplify @aws-amplify/ui-react
amplify add api # GraphQL / Single object with fields
amplify push
amplify mock api
```

**Expected behavior**

Mock server will start at locally.

**Screenshots**

![image](https://user-images.githubusercontent.com/640317/89771420-3eb7ae80-db3b-11ea-9755-2a5256699bc5.png)

**Desktop (please complete the following information):**

- Java version: 11 or 14 or 8 (installed via sdkman)
- macOS Catalina 10.15.1
- node version: v12.16.3

**Comment by edwardfoyle** [comment]
Hi @mike-neck I was unable to repro this issue following the steps you listed. Did you do anything else in the project that you didn't list above?

**Comment by mike-neck** [comment]
Here is all logs. I did nothing other than listed above.

https://gist.github.com/mike-neck/4bbe642a629273976b69149277988813

**Comment by mike-neck** [comment]
It seems this regular expression does not match openjdk-14(14.0.0). Is this related to this issue?

https://github.com/aws-amplify/amplify-cli/blob/06b822189c6c3f59788e496c7bc61fa1b4e21b3c/packages/amplify-util-mock/src/utils/index.ts#L30-L33

`java -version` outputs from openjdk 14.0.0

```
$ java --version
Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8
openjdk 14 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

**Comment by mike-neck** [comment]
The code, which verifies Java version, is trying to get value from `null` string when user configures `_JAVA_OPTIONS` environmental variable or is using openjdk 14.0.0(which does not return `"14.0.0"` but returns `"14"` as version string). I think the cause of this issue is here.

https://github.com/aws-amplify/amplify-cli/blob/06b822189c6c3f59788e496c7bc61fa1b4e21b3c/packages/amplify-util-mock/src/utils/index.ts#L35-L37

I think this condition should be like listed bellow.

```ts
  if (version == null && !semver.satisfies(version[0], minJavaVersion)) {
    context.print.warning(`Update java to 8+`);
  }
```

**Comment by mike-neck** [comment]
I Created PR #5120 .
