### ISSUE TITLE
Access Denied - This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by jaivinodha** [aws-amplify/amplify-cli#5047]
Issue:
Access Denied - This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Describe the bug**
**Im trying to Deploy the Reactjs serverless to Amplify console. If i do a manual deploy using amplify hosting add -> Hosting with Amplify Console -> Manual . It getting deployed successfully**. _**Its working properly**_ 

**But if if do amplify hosting add -> Hosting with Amplify Console ->Github-> connecting to Github -> successfully Deploying . But im getting Access Denied error.**

![image](https://user-images.githubusercontent.com/69211611/89837861-73515780-db87-11ea-87d8-dcf039136de6.png)
![image](https://user-images.githubusercontent.com/69211611/89838032-d5aa5800-db87-11ea-87b7-554011411644.png)

It tried adding SPA redirects 
![image](https://user-images.githubusercontent.com/69211611/89837787-4b61f400-db87-11ea-9c65-01e510bcbee6.png)

**To Reproduce**
amplify hosting add -> Hosting with Amplify Console ->Github-> connect to Github -> successfully Deploying . But im getting Access Denied error.

**Comment by jaivinodha** [comment]
Even i tried this way...but same access denied error
https://www.youtube.com/watch?v=DHLZAzdT44Y

**Comment by jaivinodha** [comment]
I have solved this issue by changing the base directory in the build configuration. 
For React,
![image](https://user-images.githubusercontent.com/69211611/89933683-0d1f1000-dc2d-11ea-9275-160e920f47ee.png)

By default , baseDirectory: / , i changed it to baseDirectory: /build
then makes some changes in your project , do a commit in github 
The Amplify console will generate the build automatically  and your project will run without any errors 
You do not need to add any Redirects and Rewrites for this .

**Comment by kingdopamine** [comment]
Thank you, you legend!

**Comment by AyazAI** [comment]
Not working for me!
I have `baseDirectory: build` and changed to `baseDirectory: /build`

**Comment by RonanOD** [comment]
I am getting this issue whenever you refresh any page other than the home page. Otherwise, everything works fine. The `baseDirectory: build` fix did not help.

**Comment by surajsharma** [comment]
> I am getting this issue whenever you refresh any page other than the home page. Otherwise, everything works fine. The `baseDirectory: build` fix did not help.

+1 would like to reopen

**Comment by Trevorh5** [comment]
> > I am getting this issue whenever you refresh any page other than the home page. Otherwise, everything works fine. The `baseDirectory: build` fix did not help.
> 
> +1 would like to reopen

+2

**Comment by LulyAI** [comment]
+3

**Comment by chasesagar** [comment]
> > > I am getting this issue whenever you refresh any page other than the home page. Otherwise, everything works fine. The `baseDirectory: build` fix did not help.
> > 
> > 
> > +1 would like to reopen
> 
> +2

+3

**Comment by chasesagar** [comment]
@Trevorh5 @surajsharma @RonanOD 
I have been facing the same error for days. The error is being caused by the amplify settings. The solution is simple, Edit your Rewrites and redirects by adding a new rule.

Original address: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>
Destination Address: /index.html
Redirect Type: 200(Rewrite)
Country Code: can be left blank

AWS documentation link https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

**Comment by RonanOD** [comment]
Works like a charm! I would never have figured that out. Thanks Sagar
