### ISSUE TITLE
Where are the EC2 instances of ElasticSearch?

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#5049]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I was trying to find the ec2 instance of my ElasticSearch but when I went to the console, I don't see it anywhere and on the dashboard, it says I have 0 instances running but on elastic search pricing page it says that there are charges for ec2 instances but I don't see them anywhere.

**Amplify CLI Version**

Latest

**To Reproduce**

1. Create a new amplify project with graphql api
2. Use `@searchable` directive to trigger create of elastic search.
3. Go to EC2 console

**Expected behavior**

It should display all my EC2 instances.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by RossWilliams** [comment]
There is a service called Amazon Elasticsearch Service, [here](https://eu-west-2.console.aws.amazon.com/es/home) is the console for it.

**Comment by aprilmintacpineda** [comment]
I should have been clearer. I want to hibernate my elastic search when I'm not using it.

**Comment by aprilmintacpineda** [comment]
Is there any reason why the EC2 instances of the ElasticSearch are not visible in the EC2 console?

I am trying to create a thread in the forum but I can't see where I can do that.

**Comment by SwaySway** [comment]
I believe you need to have an account setup for that.
If you have a support plan you can also contact AWS Support.
Since we have support for custom transformers, I suppose another alternative could be a directive which uses the same lambda but rather it points to another cluster. For that we do recommend discussing this in the community discord.

**Comment by aprilmintacpineda** [comment]
Hmmm.. what impact that it have if we switch from hot to ultrawarm and vise-versa?

**Comment by SwaySway** [comment]
You can view the docs on here on elasticsearch configuration changes: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-configuration-changes.html
