### ISSUE TITLE
Running amplify publish without hosting

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-cli#5053]
**Describe the bug**
When you run `amplify publish` without having run `amplify add hosting`. 

Message shown:
```
$ amplify publish

Please add hosting to your project before publishing your project
Command: amplify hosting add
```

In our documentation and trainings we predominantly use `amplify add <category>`. This alternative notation in the message seems a bit out of place here.

Besides the message it seems a better option to run `amplify add hosting` for the user the same way the CLI adds auth for storage if it's not currently added. 

Current approach seems to rely too much on the user when the CLI could already provide a solution.

**Amplify CLI Version**
4.27.1

**To Reproduce**
1) amplify init
2) amplify publish

**Expected behavior**
I would change the message to:
```
Please add hosting to your project before publishing your project
Command: amplify add hosting
```
But probably better to show a warning an run `amplify add hosting` for the user.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac
 - Node: v14.7.0

**Additional context**
NA

**Comment by esteban-uo** [comment]
hi @SwaySway @gsans. So how can we skip this warning from CLI? I have my own hosting solution.
Thanks

**Comment by teezeit** [comment]
same problem.

**Comment by josefaidt** [comment]
Closing as a "wontfix" due to the options available for hosting upon `amplify add hosting` including the managed solution with Amplify Hosting and the manual solution with S3 and CloudFront.
