### ISSUE TITLE
Amplify Mock API does not regenerate typescript types after schema.graphql modification

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#5055]
**Describe the bug**
Running the Mock API, when I modify schema.graphql, the Mock API does detect change and update, but it does not regenerate typescript types (in API.ts) correctly after modification. 

To fix this bug, I have to launch after every modification of my schema:
```
amplify api gql-compile && amplify codegen
```

My guess is that the Mock API execute the `amplify codegen` part, but not the `amplify api gql-compile`.

so when I modify `./amplify/api/MY_APP/schema.graphql`, 
it does not modify `./amplify/api/MY_APP/build/schema.graphql`.
but the Mock API will regenerate the types based on old `build/schema.graphql`

**Amplify CLI Version**
4.27.1

**To Reproduce**
- run: amplify mock api
- modify schema.graphql located in ./amplify/api/MY_APP/schema.graphql
- Mock API change, and it has regenerated typescript but it just regenerate old version of the schema.

**Expected behavior**
The types in API.ts should be up to date.

**Comment by SwaySway** [comment]
Confirmed this behavior -- marking this as a bug
