### ISSUE TITLE
init failed: Error: Invalid configuration settings

### ISSUE THREAD

**Issue by nypsystem** [aws-amplify/amplify-cli#5057]
Hello guys, im new to AWS services and when i enter " amplify init' , they prompt me whether to create an account or not, i pressed no and they prompt me for the accessKeyID and secretAccessKey and when i entered them , the error "invalid configuration settings" came out.
Just to be sure, i got my accessKeyID and secretAccess key from Workbench > Account Details

**Comment by nypsystem** [comment]
Hi @renebrandel , i've followed the documentation but i seem to have a problem with the newly created account
Attached is the error, i cannot proceed with the configuration without the access keys
![Untitled](https://user-images.githubusercontent.com/68338394/90138624-d91d2980-dda9-11ea-984a-322e7de2f441.png)

**Comment by renebrandel** [comment]
@nypsystem - it looks like your organization is prohibiting the creation of Administrator accounts. This doesn't seem like something that we can engage in. Please reopen this issue if can confirm that your organization allows your account to perform this action.
