### ISSUE TITLE
Adding notifications completely breaks amplify push (Auth error - Cannot turn MFA functionality ON, once the user pool has been created)

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#5063]
**Describe the bug**
Adding notifications breaks Auth

Running `amplify add notification` on an existing amplify project (with auth added previously and configured for MFA) causes the following error on push `Cannot turn MFA functionality ON, once the user pool has been created.`

See additional context for how to work around it

**Amplify CLI Version**
4.26.0

**To Reproduce**
1) get your project with auth already set up (MFA on)
2) run `amplify add notification`
3) add a new pinpoint project and setup fcm messaging (you will see a message about enabling auth)
4) amplify push

Project is now broken and won't deploy. It shows the error message `Cannot turn MFA functionality ON, once the user pool has been created.`

**Expected behavior**
To be able to publish project

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Node Version. v14.4.0

**Additional context**
Doing a diff on the project for before and after the only significant change I can see is in <project>-cloudformation-template.yml where the following line has changed:
```
RoleName: !If [ShouldNotCreateEnvResources, 'roarvib2307e0f_sns-role', !Join ['',[ 'sns', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
```

there is an `'undefined'` added to the line
```
RoleName: !If [ShouldNotCreateEnvResources, 'roarvib2307e0f_sns-role', !Join ['',[ 'sns', 'undefined', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
```
If I remove this, then it deploys correctly

**Comment by jcbdev** [comment]
Update - This happens with amplify add analytics too!

**Comment by jcbdev** [comment]
I figured out what causes this. Adding notifications changes "mfaConfiguration" from "OPTIONAL" to "ON" whether you have set it previously on purpose or not.  You have to change it back to make it work if you have a pre-deployed stack because you cannot make changes to cognito after the fact @akshbhu

**Comment by akshbhu** [comment]
Hi @jcbdev 

Thanks for reporting this. I am looking into this and soon will provide update regarding this

**Comment by akshbhu** [comment]
Hi @jcbdev 
I tried to reproduce this issue with latest amplify version (4.27.2)and I was not able to reproduce it. Amplify push was successful with any error.

I also have above line in the auth CFN file : 
```
      RoleName: !If [ShouldNotCreateEnvResources, 'issue54c516322_sns-role', !Join ['',[ 'sns', 'undefined', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
```
Here are my repro steps:

- amplify add auth with MFA turned ON and amplify push

- amplify add notifications with FCM

- Amplify push

Can you try with latest version and see the error is still there  and also if I have missed anything in my repro steps?

**Comment by marcvberg** [comment]
Hi @jcbdev

I tried reproducing this issue with the latest CLI 5.0.2 and was unable to do so - can you confirm that this is still an issue you're facing?

I did the following:

1. amplify add auth, MFA optional, push
2. amplify add analytics, pinpoint, push
3. amplify add notification, FCM, push
