### ISSUE TITLE
Inaccessible host: `dynamodb.us-east-1-fake.amazonaws.com'.

### ISSUE THREAD

**Issue by mujeex** [aws-amplify/amplify-cli#5067]
So I added a lambda function category using the amplify CLI, in order to query data from the GSI(Global secondary Index) I created using the @key directive in the graphql schema. Whenever I try mocking the function locally using the amplify mock function <functionName> the callback function of the query keeps on returning null. The function can be seen below

```
const AWS = require("aws-sdk");
const db = new AWS.DynamoDB.DocumentClient({
  region: process.env.REGION,
  apiVersion: "2012-08-10",
});
 
const params = {
  // ProjectionExpression: ["province", "gender", "updatedAt", "createdAt"],
  ExpressionAttributeValues: {
    ":provinceVal": "Sichuan",
  },
  IndexName: "RegistreesByProvince",
  KeyConditionExpression: "province = :provinceVal",
  TableName: process.env.API_PORTAL_SUBMISSIONSTABLE_NAME,
};
const calculateStatistics = async () => {
  try {
    const data = await db.query(params).promise();
    console.log(data);
  } catch (err) {
    console.log(err);
  }
};
 
const resolvers = {
  Query: {
    getStatistics: () => {
      return calculateStatistics();
    },
  },
};
exports.handler = async (event) => {
  // TODO implement
  const typeHandler = resolvers[event.typeName];
  if (typeHandler) {
    const resolver = typeHandler[event.fieldName];
    if (resolver) {
      var result = await resolver(event);
      return result;
    }
  }
}; // };
```
And below is the error I get whenever I execute that lambda function using a mock API
```

{ UnknownEndpoint: Inaccessible host: `dynamodb.us-east-1-fake.amazonaws.com'. This service may not be available in the `us-east-1-fake' region.
    at Request.ENOTFOUND_ERROR (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/event_listeners.js:501:46)
    at Request.callListeners (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/apple/Documents/work/web/portal/amplify/backend/function/calcStatistics/src/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
  message:
   'Inaccessible host: `dynamodb.us-east-1-fake.amazonaws.com\'. This service may not be available in the `us-east-1-fake\' region.',
  code: 'UnknownEndpoint',
  region: 'us-east-1-fake',
  hostname: 'dynamodb.us-east-1-fake.amazonaws.com',
  retryable: true,
  originalError:
   { Error: getaddrinfo ENOTFOUND dynamodb.us-east-1-fake.amazonaws.com dynamodb.us-east-1-fake.amazonaws.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     message:
      'getaddrinfo ENOTFOUND dynamodb.us-east-1-fake.amazonaws.com dynamodb.us-east-1-fake.amazonaws.com:443',
     errno: 'ENOTFOUND',
     code: 'NetworkingError',
     syscall: 'getaddrinfo',
     hostname: 'dynamodb.us-east-1-fake.amazonaws.com',
     host: 'dynamodb.us-east-1-fake.amazonaws.com',
     port: 443,
     region: 'us-east-1-fake',
     retryable: true,
     time: 2020-08-12T10:18:08.321Z },
  time: 2020-08-12T10:18:08.321Z }

```

Any help on this would be very much appreciated

PS: It is worth mentioning that I was able to successfully query for this data through the Appsync console, which led me to strongly believe the problem lies in the function itself.

**Comment by SwaySway** [comment]
When running mock on a function which has access to a dynamodb table generated by API. It will populate the env with fake values. If you would like to mock your lambda function against your deployed dynamodb table you can edit the values in the sdk client so it can make the call accurately. 

We also have a feature request open for customizing this env variables: https://github.com/aws-amplify/amplify-cli/issues/2227

**Comment by mujeex** [comment]
> When running mock on a function which has access to a dynamodb table generated by API. It will populate the env with fake values. If you would like to mock your lambda function against your deployed dynamodb table you can edit the values in the sdk client so it can make the call accurately.
> 
> We also have a feature request open for customizing this env variables: #2227

Thanks for getting back to me. I did as you suggested and it worked beautifully! It actually makes sense now that if you are running things locally, then you wouldn't have access to your backend resources which is where the env variables are created. Thanks again for shining a light on this.

**Comment by mujeex** [comment]
@SwaySway Now that I have your attention, please how do I project certain attributes to GSI created using the `@key` directive?

**Comment by SwaySway** [comment]
By certain attributes are you referring to using the same hash key in primary keySchema in a GSI?

**Comment by mujeex** [comment]
If I am understanding you correctly, you mean using the same primary key for the GSI as that of the parent table right? If so then no; I want to use a different hash and range key for the GSI table, but I don't want all the remaining attributes of the parent table to be projected to the GSI table.

**Comment by SwaySway** [comment]
A GSI is another index into a table to access records. For any given record it will show the attributes it has. 
Docs on Secondary Indexes: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html


Closing this issue as the main question is addressed. Should you have more questions on GSIs we recommend using our community discord for discussion https://discord.gg/jWVbPfC

**Comment by mujeex** [comment]
Alright thanks alot for your help!
