### ISSUE TITLE
"No AppSync API configured" when running "amplify codegen models"

### ISSUE THREAD

**Issue by RandomEngy** [aws-amplify/amplify-cli#5069]
**Describe the bug**
Model generation doesn't work. It claims that no API is configured, but all indications are that it does have an API.

**Amplify CLI Version**
4.27.1

**To Reproduce**
Added an Api from an existing API:
`amplify add codegen --apiId df4pcs54qfc7tjy4mzokjtco5y`

Ran:
`amplify codegen models`

Got `No AppSync API configured. Please add an API`

Ran `amplify status`:
```
C:\git\FocalistKotlin>amplify status

Current Environment: prod

| Category | Resource name          | Operation | Provider plugin   |
| -------- | ---------------------- | --------- | ----------------- |
| Api      | Focalist               | No Change |                   |
| Auth     | focalistkotlinxxxxxxxx | No Change | awscloudformation |
```

In amplifyconfiguration.json:
```
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "Focalist": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
```

I also see all properly populated .graphql files in `app\src\main\graphql\com\amazonaws\amplify\generated\graphql`

**Expected behavior**
The model generation works.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.16.3

**Comment by RandomEngy** [comment]
I'm digging into the code and I see that it is looking for resources with `providerPlugin === "awscloudformation"` . Mine does not have that provider plugin set. It looks like it was generated that way when I added the API.

**Comment by SwaySway** [comment]
When running `amplify add codegen --apiId ...` this is generating types for your appsync schema. The schema that is downloaded is an introspection schema which does not have `@model` directive attached. As using `amplify codegen models` is used with a DataStore enabled Amplify project.

**Comment by RandomEngy** [comment]
I had this working earlier. And the AppSync documentation says this can generate types:

![image](https://user-images.githubusercontent.com/9450861/90068328-54e17e00-dca5-11ea-803c-9dab22602cd3.png)

What command is supposed to generate types in this case?

**Comment by SwaySway** [comment]
If you built your AppSync API outside of Amplify there is portion of the docs here which go over this:
https://docs.amplify.aws/sdk/api/graphql/q/platform/android#configuration

**Comment by RandomEngy** [comment]
Ahh okay. I think I finally puzzled it out. The actual code generation in this case is done by the AWS Android AppSync SDK, with a Gradle plugin. I was missing that, so the code was not being generated. I was thrown off by all of the amplify cli "codegen" stuff.

**Comment by RandomEngy** [comment]
And figuring things out even more: There are two types of class generation happening!

1) Classes generated by the `com.amazonaws.appsync` gradle plugin. They work with the classic `aws-android-sdk-appsync` library with `AWSAppSyncClient.query()` and `AWSAppSyncClient.mutate()`. They can work from graphql that's downloaded from `amplify add codegen --apiId ...`
2) Classes generated by `amplify codegen models` . These work with `Amplify.API.mutate()` and `Amplify.API.query()` . They require `@model` type annotations and do not support an API added from `amplify add codegen --apiId ...` .

The weird part is that the AppSync console prompts you to add via `--apiId` then links you off to https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app.html . You then follow the Android Documentation link and it brings you to https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android . That talks about the "amplify" way of doing things, which doesn't work!

**Comment by Taha-Mohsin** [comment]
Hey, I'm facing the same issue.
Did you manage to solve this?

**Comment by RandomEngy** [comment]
Yes, as mentioned in my last update. If you add via API ID then you need to use the old AWSAppSyncClient and Gradle plugin. It does not work via the amplify API.
