### ISSUE TITLE
Lambda Layer custom module 

### ISSUE THREAD

**Issue by ryaneghrari** [aws-amplify/amplify-cli#5070]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Lambda Layers

**Amplify CLI Version** 
4.23.1

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Lambda Layers

**Provide additional details e.g. code snippets**
I am looking to include custom code in a layer: rmatchapi62c53619

![image](https://user-images.githubusercontent.com/13022330/90077972-76585f00-dcd1-11ea-9b92-7a83ca3ab9ee.png)

and then use it in the lambda function: 

![image](https://user-images.githubusercontent.com/13022330/90077994-8708d500-dcd1-11ea-9e41-c5c596977189.png)

However, I get the following error:
![image](https://user-images.githubusercontent.com/13022330/90078039-a56ed080-dcd1-11ea-93be-a941d82e65a4.png)

ps.
If I install a node module according to @dabit3 it works perfectly. I must be missing something simple. 

Thank you in advance. I will keep looking and post a video if I figure it out.

**Comment by jhockett** [comment]
Hi @ryaneghrari, please update to the latest CLI version. This import error was fixed in 4.25.0.

**Comment by ryaneghrari** [comment]
Thank you
