### ISSUE TITLE
command not found: amplify cli on mac

### ISSUE THREAD

**Issue by sgr0691** [aws-amplify/amplify-cli#5075]
I've run `npm install -g @aws-amplify/cli` and `sudo npm install -g @aws-amplify/cli --unsafe-perm=true ` and on my mac its not reading amplify as a command and continues to give me an error. I've uninstalled node and npm and reinstalled it but still the same result. I'm not sure if this is just a mac problem.

Currently I'm running node version v14.8.0 and npm version 6.14.7

**Comment by SwaySway** [comment]
I updated to the node and npm version. Are you using nvm? I was able to run  `amplify status` in a project. Are you able to use other npm-published CLI applications?

**Comment by sgr0691** [comment]
I'm currently not using nvm but I'm using npm & sudo npm. Should I use nvm instead? I was able to successfully use aws cli but just not amplify cli.

**Comment by edwardfoyle** [comment]
Hi @sgr0691 can you make sure that the global node modules bin folder is on your path? Usually this would be `usr/local/bin`. You can run `npm root -g` to see where npm is configured to install global modules. You'll get a path like `<some path>/lib/node_modules` and you'll need to make sure that `<some path>/bin` is on your path

**Comment by sgr0691** [comment]
Hi @edwardfoyle the path is /usr/local/lib/node_modules

**Comment by edwardfoyle** [comment]
@sgr0691 In that case you'll need to make sure that `/usr/local/bin` is on your path.

**Comment by sgr0691** [comment]
@edwardfoyle thank you for helping me with this. Amplify CLI is working on my computer

**Comment by danishuahmad** [comment]
@edwardfoyle Thank you. 😊

**Comment by Mitsutaka80** [comment]
This was helpful! Thank you edwardfoyle.

**Comment by OderoOtieno** [comment]
@edwardfoyle how do you make sure /usr/local/bin is on your path? I have exactly the same issue and npm root -g produces the path as follows: /usr/local/Cellar/node/16.1.0/lib/node_modules
