### ISSUE TITLE
amplify add codegen not generate API in AppSync

### ISSUE THREAD

**Issue by kaushal2406** [aws-amplify/amplify-cli#5077]
amplify add codegen  not asking API file name  it asking in ios API.swift but in android API not generated.
when try to configure **amplify codgen** command
Error  "No AppSync API configured. Please add an API"

Any one have solution please help .

Log after  amplify add codegen --apiId XXXXXX
 Getting API details
Successfully added API AppSyncDemo to your Amplify project
? Enter the file name pattern of graphql queries, mutations and subscriptions app/src/main/graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
✔ Downloaded the schema
✔ Generated GraphQL operations successfully and saved at app/src/main/graphql/com/amazonaws/amplify/generated/graphql

**Comment by SwaySway** [comment]
Are you looking at generating types from a API built on the AppSync console?
Below are some guides in android and iOS.
https://docs.amplify.aws/sdk/api/graphql/q/platform/android
https://docs.amplify.aws/sdk/api/graphql/q/platform/ios

**Comment by kaushal2406** [comment]
I have tried same steps ,
I can not pull from appsynch backend.

$ sudo amplify pull

Pre-pull status:

Current Environment: dev

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |
| Api      | AppSyncDemo   | No Change |                 |

✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
ENOENT: no such file or directory, open '/home/kaushal/AndroidStudioProjects/AppsyncDemo2/amplify/backend/backend-config.json'
Error: ENOENT: no such file or directory, open '/home/kaushal/AndroidStudioProjects/AppsyncDemo2/amplify/backend/backend-config.json'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at initEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/index.ts:61:33)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.js:43:52
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


I tried creating file also but still getting error.
after creating file it can not pull anything it showing nothing in pull data.just blank pull.

I also tried creating 3-4 new android project and try to create with **Integrate with your app** steps
if i create api with add command and push data to appsync it working but i want to use existing appsync data from server and generate api in android project that is not working.

**Comment by RandomEngy** [comment]
I have learned that while you use the amplify CLI to add the existing API, you *cannot* use the Amplify SDK or gradle plugins to handle it: https://github.com/aws-amplify/amplify-cli/issues/5069#issuecomment-673683606 . You need to use the classic `com.amazonaws.appsync` gradle plugin to generate the types on build and the classic `aws-android-sdk-appsync` library to make the AppSync calls.

**Comment by kaustavghosh06** [comment]
@RandomEngy thanks for jumpin in and answering. Closing this issue.
