### ISSUE TITLE
DynamoDB simulator incorrectly reports Java simulator errors as port error

### ISSUE THREAD

**Issue by cloudspeak** [aws-amplify/amplify-cli#5078]
In some situations, the [Amplify DynamoDB simulator](https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-dynamodb-simulator) incorrectly reports errors from the Java simulator as port errors.

The example I encountered was when using the `dbPath` parameter.  If you provide a non-absolute path, the Java simulator prints "Invalid directory for database creation." to stderr, however the JavaScript wrapper completely ignores this message.  There are two ways the error is reported:

* If no port was specified, the unhelpful error `Error: max retries hit for starting dynamodb emulator` is shown
* If an explicit port was specified, the completely incorrect error `Error: [port] is bound and unavailable` is shown

**Amplify CLI Version**
4.27.1

**To Reproduce**
* Install the simulator:
```
npm install amplify-dynamodb-simulator
```
* Create a file test.js with the following:
```javascript
const emulator = require('amplify-dynamodb-simulator');
emulator.launch({
    dbPath: "dynamoDir",
    port: 62224,
    inMemory: false
})
.then(port => { console.log(`Ok`) })
.catch(e => { console.error("Error: " + e) })
```
* Run this:
```
node ./test.js
```
* The output is `Error: 62224 is bound and unavailable` is incorrectly given.

**Expected behavior**

At the very least a more generic error should be given, but ideally, the content of the Java simulator's stderr should be shown:

```
Invalid directory for database creation
```

In addition, the fact that `dbPath` should be absolute should be explained on the README.

**Desktop (please complete the following information):**
 - Ubuntu 18.04.3 LTS running in VirtualBox in Windows 10
 - Node Version: 13.10.1

**Comment by cjihrig** [comment]
This should have been fixed by #6769, so I'll close the issue.
