### ISSUE TITLE
Broken amplify hosting serve with Amplify Console hosting

### ISSUE THREAD

**Issue by martinbiard** [aws-amplify/amplify-cli#5080]
**Describe the bug**
Running `amplify hosting serve` asks a blank question and does not open the site.

**Amplify CLI Version**
4.27.1

**To Reproduce**
Run on an app with amplify console hosting enabled:
```sh
amplify hosting serve
```
You get a prompt with a blank question:
```
$ amplify hosting serve
? question: Yes
```
If you answer Yes, it opens your browser to your Amplify Console app URL. Answering No does nothing.

**Expected behavior**
1. The question asked should be meaningful and not blank, or completely removed if unnecessary. 
2. The actual site URL should open in the browser, not the Amplify Console project.
3. If multiple domains are available for the current branch, ask for which one to open.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v12.18.3

**Comment by renebrandel** [comment]
@martinbiard did you use CI/CD or manual hosting?

**Comment by renebrandel** [comment]
@UnleashedMind The root cause is in `packages/amplify-console-hosting/modules/questions/question-generator.js` line 43. It seems like `constants.APP_MANUAL_SERVE_QUESTION` is undefined.

**Comment by martinbiard** [comment]
@renebrandel 
It was hosting setup as cicd, but seems like you figured it out. Thanks for fixing.
