### ISSUE TITLE
Composite primary key - Query without sortkey

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#5088]
**Is your feature request related to a problem? Please describe.**
When providing a Composite key as Primarykey it is not possible to query without the sortkey

```
type RentalItem
@key(fields: ["nodeId", "rentalItemId"])
@key(fields: ["rentalItemId", "nodeId"], name: "queryByRentalItemId", queryField: "getRentalItemByRentalItemId")
{
    nodeId: String!
    rentalItemId: String!
}
```

```
query MyQuery {
  getRentalItem(nodeId: "SE_STUFF") {
    name
  }
}
```
results in

```
{
  "errors": [
    {
      "message": "Field \"getRentalItem\" argument \"rentalItemId\" of type \"String!\" is required, but it was not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": null
}
```
while
```
 getRentalItemByRentalItemId(rentalItemId: "SE_1241") {
    items {
      country
    }
  }
```

works as expected. I get all items that have SE_1241 as primary key (in this index)

**Describe the solution you'd like**
I want the query to be passed to DynamoDB without the sortkey specified and it to work as it would when querying DynamoDB directly.

<img width="785" alt="Example" src="https://user-images.githubusercontent.com/9092858/90258054-4a131e80-de48-11ea-9acb-8ec20d7a2167.png">

---
I assume this is something inside the resolvers but I don't understand the language good enough to get it to work. 

I wanted to try something like this 

```
#if($ctx.args.rentalItemId) 
#set( $modelObjectKey = {
  "nodeId": $util.dynamodb.toDynamoDB($ctx.args.nodeId),
  "rentalItemId": $util.dynamodb.toDynamoDB($ctx.args.rentalItemId)
} ) 
#else {
#set ($modelObjectKey = {
       "nodeId": $util.dynamodb.toDynamoDB($ctx.args.nodeId)})
}
```

**Comment by RossWilliams** [comment]
getX operations are incensed to return a single item from the database. If you don’t specify the sort key, DynamoDB can’t get a single item, and it would be an invalid request

Use the listX query to get multiple items, and specify your partition key as a query argument

**Comment by Zanndorin** [comment]
But listX does a scan operation while 

``` 
getRentalItemByRentalItemId(rentalItemId: "SE_1241") {
    items {
      country
    }
  }
```

is a query operation?

I have used this a lot with the DocumentClient (and console).

**Comment by RossWilliams** [comment]
listX is either a scan or a query depending on the arguments provided.
In your api/$PROJECT_NAME/build/resolvers folder, look at Query.listRentalItems.req.vtl
you will see a line
```vtl
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
```

which is setting the dynamodb operation as a query rather than a scan.

**Comment by Zanndorin** [comment]
Good to know! 

I still think that this should work like described above, I know that AWS has documented the described behavior specifically for indexes but I can't find it right now.

I'll probably either add an autogenerated ID and keep this key as a second named index to get the behavior to work.

**Comment by RossWilliams** [comment]
It should not work as you describe. Get operations return a single item, that is why the type is singular and it doesn't return an "items" field with an array. Changing to your suggestion would screw up the types for users and add to more confusion.

The behaviour you want is provided by the list operation with no downsides.

**Comment by Zanndorin** [comment]
Oh yeah, I didn't even think about that the first generated get doesn't include "items". I also forgot that you are supposed to use the dynamodb.get() on the "main index"(?).

But In that case why does the "getRentalItemByRentalItemId" return an "items" field and work this way? That's out of the box. Seems a bit inconsistent in that case.


Just to clarify: When I change 

```
@key(fields: ["nodeId", "rentalItemId"])
```
to 
```
@key(fields: ["nodeId", "rentalItemId"], name: "someQueryName", queryField: "someQueryName")
```

everything works as intended (by me)

**Comment by RossWilliams** [comment]
When you give a @key a name a GSI is created. You can only query and scan a GSI, you cannot get single values. So the generated query is actually a scan/list template (similar to listX), and not a get item.
