### ISSUE TITLE
Steps for writing custom queries in Amplify Graphql ? 

### ISSUE THREAD

**Issue by Sourabh7749** [aws-amplify/amplify-cli#5089]
I am trying to Run a Simple Query to get Doctor details by userId. I checked for the documentation but was not able to find a way for defining a custom query.

query getDoctorsbyuserID($userId: String!) {
getDoctorsbyuserID(userId: $userId) {
id
firstName
lastName
userId
}
}

The queries which are auto generated are working fine but not able to find a way to make custom query work.

What are steps of writing custom queries in Amplify Graphql? Any document/blog ?

Frontend - Reactjs

P.S : I am new to Amplify.

**Comment by renebrandel** [comment]
Hi @Sourabh7749 - If you want to just use a different access pattern for your existing type use the `@key` directive.  https://docs.amplify.aws/cli/graphql-transformer/directives#key

You can also learn more here about different access pattern templates: https://docs.amplify.aws/cli/graphql-transformer/dataaccess

If you want to add custom business logic to retrieve that information, I think you're looking for the `@function` directive. You essentially create a Lambda function to handle the request. https://docs.amplify.aws/cli/graphql-transformer/directives#function

**Comment by renebrandel** [comment]
Feel free to reopen this if it's not what you're looking for.
