### ISSUE TITLE
Amplify env add misses hostedUIProviderCreds in the team-provider.info file

### ISSUE THREAD

**Issue by JohannesKonings** [aws-amplify/amplify-cli#5090]
**Describe the bug**
In my env main I have a empty hostedUIProviderCreds array in the team-provider.info file. This will not be copied if I create a new env.
This causes the error "Parameters: [hostedUIProviderCreds] must have values" after `amplify push`

`CREATE_FAILED      authfffbadminton63e2a49c          AWS::CloudFormation::Stack Fri Aug 14 2020 17:46:16 GMT+0200 (Mitteleuropäische Sommerzeit) Parameters: [hostedUIProviderCreds] must have values`

**Amplify CLI Version**
4.27.1

**To Reproduce**
- create a env with the categorie auth and configuration with Social Provider (Federation) 
- delete the configuration with Social Provider (Federation) (Than the field hostedUIProviderCreds has an empty arry)
- create a new env
- `amplify push` cause the error `Parameters: [hostedUIProviderCreds] must have values` 

**Expected behavior**
`amplify env add` will also copy hostedUIProviderCreds to the new env

**Screenshots**

![image](https://user-images.githubusercontent.com/14806640/90267831-60c07200-de56-11ea-929e-459c425f6a02.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v14.8.0

**Additional context**
Maybe i's related to https://github.com/aws-amplify/amplify-cli/issues/3642

The workaround is to copy the field hostedUIProviderCreds manually and before the first `amplify push`. Otherwise cloudformation is inconsistent.

**Comment by ammarkarachi** [comment]
@JohannesKonings as of the latest CLI version hostedUIProviderCreds are set to empty if not configured. This should be fixed in the latest version
