### ISSUE TITLE
Allow search queries with @searchable to retrieve more than 1000 items.

### ISSUE THREAD

**Issue by celobpm** [aws-amplify/amplify-cli#5099]
**Which Category is your question related to?**
GraphQL/ @searchable

**Amplify CLI Version** 
4.27.1

**What AWS Services are you utilizing?**
ElasticSearch Service, Amplify, Appsync

I would like to know if it is, in any way, possible to retrieve over 1000 elements per request from my ElasticSearch instance via the @searchable in amplify, using the query generated by Codegen.

If trying to increase the limit in the GraphQL query over 1000 I receive the error: 

"List size cannot exceed 1000"

I have found the following guide on how to do it with the scan request : [Here](https://janhesters.com/query-all-items-using-scans-in-aws-amplify/) but I couldn't Replicate with the Search query generated by codegen.

to reproduce: create a model with @searchable tag, insert over 1000 elements and try to  execute a query with a limit over 1000.

**Comment by edwardfoyle** [comment]
@celobpm you could do this with a lambda resolver: https://docs.amplify.aws/cli/graphql-transformer/directives#function
However, if you are trying to load that much data, I would recommend pagination which is supported out of the box using the nextToken parameter of the search query.

**Comment by celobpm** [comment]
@edwardfoyle , thanks! i wil try with the lambda resolver!  the nextToken is too slow for a few situations when i need many items returned.
