### ISSUE TITLE
amplify api add (REST)

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#51]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
adds api model files to the `ROOT/src/main/java`

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**
`amplify api add`

**What is the expected behavior?**
adds api model files to the `ROOT/app/src/main/java`

**Additional environment details**
env agnostic

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)** macOS Sierra
* **Output of ``amplify --version``**: 0.1.13
* **Did this work in previous versions?**: N

**Comment by kaustavghosh06** [comment]
Fixed this. Will close this once we publish to npm.

**Comment by kaustavghosh06** [comment]
Should be fixed with the latest npm publish.
