### ISSUE TITLE
The ARN of an IAM Role used to submit events to Mobile notifications' event ingestion service

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#5100]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
When trying to add the email channel to analytics in amplify cli the following cryptic message comes up:
`The ARN of an IAM Role used to submit events to Mobile notifications' event ingestion service`

which role does this refer to?  There is no documentation on this anywhere that I can find.

**Amplify CLI Version** 
4.27.0

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by akshbhu** [comment]
Hi @jcbdev 

Thanks for the feedback. Yes the line is somewhat confusing. That Is a userPrompt question asking you the ARN of the IAM role  that you want Amazon Pinpoint to use when it submits email-related event data for the channel.

**Comment by waltermvp** [comment]
@Ashish-Nanda does amplify create this role for you? or do you need to create it outside of amplify and just provide the arn here?

**Comment by evrardts** [comment]
@akshbhu can you please specific how to get this ARN? Or give an example? Thanks a lot!

**Comment by sarfarazengglb** [comment]
Why this issue is closed without answer??

**Comment by deividi86** [comment]
Can we get an answer to this issue? The notifications part of amplify documentation is broken and confusing.
