### ISSUE TITLE
Simple lambda takes 5seconds to run on Mock Api, but it's instant on the cloud

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#5103]
**Describe the bug**
For me, simple lambda takes 3 to 5 seconds to run on Mock Api, but instant on the cloud. Is it normal?

My CPU is not fast but not slow either (i7-8565U).

**Amplify CLI Version**
4.27.1

**To Reproduce**
- reproduce tutorial in the docs which create a "echo" or hello world function
https://docs.amplify.aws/cli/graphql-transformer/directives#function
- call it in your frontend code, compare cloud vs local with mock api.

P.S: thanks for the Mock API, it's really great.

**Comment by edwardfoyle** [comment]
@anisg yes unfortunately that sounds pretty normal. The main thing that slows down local execution is the CLI parses all of the CFN resources in order to populate any lambda environment variables that may derive their value from other resources. Marking this as an enhancement.

**Comment by edwardfoyle** [comment]
We have made several improvements to mock in the latest version of the CLI including some speed optimizations. You will likely still see slower startup times when mocking vs in the cloud but most of the latency now is a result of inefficient module loading across the CLI and not just a mock issue.
