### ISSUE TITLE
Auth fails with IAM public + user group when logged in

### ISSUE THREAD

**Issue by hanzhaodeng** [aws-amplify/amplify-cli#5105]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
A clear and concise description of what the bug is
`{ allow: public, provider: iam, operations: [read] }{ allow: groups, groups: ["Admin"] }` This works when user is not logged in and we use authMode AWS_IAM. But when a user logs in, using AWS_IAM fails with a status code of 401.

**Amplify CLI Version**
4.26.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Have a auth directive `{ allow: public, provider: iam, operations: [read] }{ allow: groups, groups: ["Admin"] }` Logs in and use authMode AWS_IAM to query.

**Expected behavior**
I think the read should still go through without user to toggle the auth to AMAZON_COGNITO_USER_POOLS.

**Comment by hanzhaodeng** [comment]
I am currently getting pass this by using Auth.currentAuthenticatedUser() to toggle the authMode

**Comment by edwardfoyle** [comment]
@hanzhaodeng what credentials are you sending in the AWS_IAM request after the user logs in? Is it the same credentials as before they logged in?

**Comment by kaustavghosh06** [comment]
You'd need to add `{ allow: private, provider: iam }` or `{ allow: private } //cognito-auth`  in addition for all logged in users to have access.
