### ISSUE TITLE
Sample Hello world lambda template when creating a REST api throws CORS error

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-cli#5111]
**Describe the bug**
When creating a new REST API using the Hello world lambda template throws CORS error.

**Amplify CLI Version**
4.27.2

**To Reproduce**
1) Run `amplify add api` with the options below

```
? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: helloApi
? Provide a path (e.g., /book/{isbn}): /hello
? Choose a Lambda source Create a new Lambda function
? Provide a friendly name for your resource to be used as a label for this category in the project: helloLambda
? Provide the AWS Lambda function name: helloLambda
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World
? Do you want to access other resources in this project from your Lambda function? No
? Do you want to invoke this function on a recurring schedule? No
? Do you want to configure Lambda layers for this function? No
? Do you want to edit the local lambda function now? Yes
? Restrict API access No
? Do you want to add another path? No
Successfully added resource helloApi locally
```

Current code
```
exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

When calling from the client
```
API.get('helloApi', '/hello')
```

Returns
```
No 'Access-Control-Allow-Origin' header is present on the requested resource'
```

**Expected behavior**
The default template should include the CORS header:
```
exports.handler = async (event) => {
  const response = {
    statusCode: 200,
    headers: {
      "Access-Control-Allow-Origin": "*"
    },
    body: JSON.stringify({ message: 'Hello from Lambda!' }),
  };
  return response;
};
```

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.7.0

**Additional context**
NA

**Comment by renebrandel** [comment]
Playing around with it some more, it seems like APIGW by configures the correct CORS settings with "OPTIONS" requests but doesn't using GET or POST. I think there might be a different APIGW level config that we should adjust here

**Comment by gsans** [comment]
That would be great but looking at the [API Gateway docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) it seems that for a Lambda proxy the setup used by Amplify you need to set the headers in your response as shown in the example.

**Comment by edwardfoyle** [comment]
@gsans You are correct that using lambda proxy integration does not allow API Gateway to intercept the response and add headers. However, the hello world template is meant to be a bare-bones template and there are plenty of contexts where it would not make sense to add such headers to the response (AppSync resolver, scheduled function, etc). When selecting a function template the "Serverless ExpressJS function (Integration with API Gateway)" option is pre-configured to include CORS headers

**Comment by gsans** [comment]
I wouldn't mind if it did work when you try to use it. The template just doesn't work when used together with `amplify add api` which defeats the purpose of providing such a template in the first place. This is not just a Lambda template but a Lambda template to be used in the context of a REST api.

**Comment by edwardfoyle** [comment]
@gsans marking this as an enhancement to implement "context-aware" template options.

**Comment by gsans** [comment]
Thanks. I think that a reasonable compromise while that is being built would be to include the CORS header but commented out so users don't find themselves troubleshooting CORS errors.

**Comment by renebrandel** [comment]
I agree with gsans suggestion here. We should just have the CORS header but commented out.
