### ISSUE TITLE
lastPushTimeStamp issue when adding API

### ISSUE THREAD

**Issue by cdellinger** [aws-amplify/amplify-cli#5114]
**Describe the bug**
Whenever I try adding a REST API to a brand new React project via the AWS-CLI I successfully walk through the questions to create the API but when I execute an "amplify push" I receive a message that says "Successfully pulled backend environment dev from the cloud." and then it gives an error of "An error occurred during the push operation: Cannot read property 'lastPushTimeStamp' of undefined".

After getting into this error state if I try to run "amplify status" I get the following error:
```
Current Environment: dev

Cannot read property 'lastPushTimeStamp' of undefined
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
    at getResourcesToBeCreated (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:122:76)
    at getResourceStatus (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:205:32)
    at AmplifyToolkit.showResourceTable [as _showResourceTable] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:232:102)
    at Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/status.js:5:27)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:166:29)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:34:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:94:9)
```

If try to remove the api via "amplify remove api", the cli walks me through the steps but throws the following error when I verify that I want to remove the specified api.
```
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
    at getResourcesToBeCreated (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:122:76)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:205:32)
    at deleteResourceFiles (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:114:56)
    at AmplifyToolkit.removeResource [as _removeResource] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/remove-resource.js:101:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/index.js:147:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:34:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:94:9)
There was an error removing the api resource
```

**Amplify CLI Version**
4.27.2

**To Reproduce**
Create REST API then run amplify push

**Expected behavior**
Be able to push the newly defined API to AWS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.18.3

**Additional context**

**Comment by cdellinger** [comment]
Trying to debug the code, it looks like when I execute an "amplify status" it fails when trying to process the API Gateway resource.   Looking in amplify-meta.json file in the /amplify/backend directory I see a property named lastPushTimeStamp for other resources that amplify has helped me create (auth, storage) but there is not a lastPushTimeStamp property for the entry for the "function" or "api" that got created in this file when I created the API.

**Comment by edwardfoyle** [comment]
Hi @cdellinger could you provide more details around how you initialized the project? Did you just run `amplify init` and follow the walkthrough? Also, did you have other resources configured in the project before that you then deleted?

**Comment by cdellinger** [comment]
The project was created with amplify init.  The first resource that was added was auth with cognito, I was able to do a push and run successfully.  I then added the api and failed as mentioned above.  I found a similar issue from back in April which recommended doing a "amplify pull dev --restore", it was the only thing I can do to back out the API problem.  After I did that I added storage (another issue here in this forum said that helped someone with a similar problem) in the form of a dynamodb table.  That action completed successfully and I was able to do a successful push.  I then tried adding the API again as described above with the same result.

**Comment by brooksidesw** [comment]
I'm having the same experience.  Same amplify version (4.27.2).

**Comment by akshbhu** [comment]
Hi @cdellinger and @brooksidesw 

From the error it seems , you have some resources which depends on another resource.
Did you selected a resource which depends on the lambda function in the workflow of adding REST api?

**Comment by brooksidesw** [comment]
I cannot say I am aware of selecting a resource that depends on the lambda.  Would the DynamoDB table created by the amplify script place a dependency on the lambda?

**Comment by akshbhu** [comment]
Hi @brooksidesw 

It will only create the dependency if you have selected the option in the workflow while adding REST API.
Can you elaborate more on the amplify script that you mentioned?

**Comment by cdellinger** [comment]
For me I see this error at times when I try creating resources with dependencies and also at times without dependencies, I can't seem to determine the pattern.

**Comment by cdellinger** [comment]
I just replicated it this morning here are two screen prints that show what I did.

![image](https://user-images.githubusercontent.com/357662/91636864-ff5dde80-e9d1-11ea-855e-04171a7b02d1.png)

![image](https://user-images.githubusercontent.com/357662/91636870-07b61980-e9d2-11ea-8fca-2d15fec1e877.png)

**Comment by akshbhu** [comment]
Hi @cdellinger , @brooksidesw 

Thanks for reporting this. I have made the fix in above PR.

**Comment by dwardu89** [comment]
It looks like this is still happening to me and i have version `4.29.0`

**Comment by mmendonca3** [comment]
It looks like this is still happening on version `4.29.1`

**Comment by akshbhu** [comment]
Hi @mmendonca3 and @dwardu89 

Can you post your ```amplify-meta.json``` file after redacting secret information from it?

**Comment by zachwaltz** [comment]
I'm also experiencing issues with having an API defined that is dependent on a Lambda function. By manually removing sections on my amplify-meta.json file, I've narrowed the issue down to the following section:

`{
	"function": {
		"widgets": {
			"build": true,
			"providerPlugin": "awscloudformation",
			"service": "Lambda",
			"dependsOn": []
		}
	},
	"api": {
		"widgets": {
			"service": "API Gateway",
			"providerPlugin": "awscloudformation",
			"dependsOn": [
				{
					"category": "function",
					"resourceName": "get-widgets",
					"attributes": [
						"Name",
						"Arn"
					]
				}
			]
		}
	}
}`

@akshbhu - please let me know what else I could provide to help with this issue.

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error.

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error.

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error.

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error.

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error. My amplify version is 4.27.0

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error. My amplify version is 4.27.0

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error. My amplify version is 4.27.0

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error. My amplify version is 4.27.0

Anyone got any workaround?

**Comment by yogimishra** [comment]
I am getting this error too, when trying to 'amplify push' after adding api locally. Just before that I deleted one api and a function and I have used some names for resources which were previously used. Not sure if it has anything to do with error. My amplify version is 4.27.0

Anyone got any workaround?

**Comment by akshbhu** [comment]
Hi @zachwaltz 

I think this might be because you added the api and function before fix was released. Your function resourceName(```widgets```) is different from function resourcename present in api depends on (```get-widgets```). Can you try this and check if it is working:
```json
{ 
    "function": { 
        "widgets": { 
            "build": true, 
            "providerPlugin": "awscloudformation", 
            "service": "Lambda", 
            "dependsOn": [] 
        }, 
        "api": { 
            "widgets": { 
                "service": "API Gateway", 
                "providerPlugin": "awscloudformation", 
                "dependsOn": [
                     { 
                         "category": "function", 
                         "resourceName": "get-widgets", 
                         "attributes": [ "Name", "Arn" ] 
                     } 
                ]
            } 
        } 
    } 
}
```
Let me know if this works?

@yogimishra 

Can you post your amplify-meta.json file after redacting secret information from it?

**Comment by yogimishra** [comment]
@akshbhu
Thanks a lot for the help. 

Yes, for me this was the issue. My function resourceName was different than the function resourceName in api. Once I made both same, it started working.

So for future, is that mean, I need to keep the function resource name and lambda function name same? Also, could you please let me know how to update my amplify cli without reinstalling everything.

**Comment by bernardnongpoh** [comment]
```
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react-native
? Source Directory Path:  src
? Distribution Directory Path: /
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
Cannot read property 'lastPushTimeStamp' of undefined
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
    at getResourcesToBeCreated (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:124:77)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/snapshot/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:263:32)
    at initEnv (/snapshot/node_modules/amplify-category-function/lib/index.js:112:110)
    at /snapshot/node_modules/@aws-amplify/cli/lib/initialize-env.js:38:64
    at /snapshot/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

I got this error when trying to pull from amplify
