### ISSUE TITLE
Predictions Convert AccessDeniedException Group role

### ISSUE THREAD

**Issue by DanielAlejandroMontesRodriguez** [aws-amplify/amplify-cli#5116]
**Describe the bug**
We are using Predictions to translate text, it is configured for auth and guest users for the auth and unauth role (IAM)

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "translate:TranslateText"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}`

This function well as expected, but not when you are logged in with Groups it shows the next **Error**:

> AccessDeniedException: User: arn:aws:sts::app-ID:assumed-role/us-east-1_nmlSwc6Ul-administratorGroupRole/CognitoIdentityCredentials is not authorized to perform: translate:TranslateText

**Amplify CLI Version**
4.24.2

> {
  "name": "tostayadmin",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@sentry/browser": "^5.12.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@uifabric/fluent-theme": "^7.1.90",
    "aws-amplify": "^3.0.18",
    "axios": "^0.19.2",
    "chart.js": "^2.9.3",
    "clabe-validator": "^1.3.6",
    "cra-append-sw": "^2.7.0",
    "crypto-js": "^4.0.0",
    "file-saver": "^2.0.2",
    "formik": "^2.0.10",
    "fuse.js": "^6.2.0",
    "geolib": "^3.2.1",
    "google-map-react": "^1.1.6",
    "html2canvas": "^1.0.0-rc.5",
    "libphonenumber-js": "^1.7.29",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "office-ui-fabric-react": "^7.117.3",
    "qrcode.react": "^1.0.0",
    "query-string": "^6.11.1",
    "react": "^16.12.0",
    "react-albus": "^2.0.0",
    "react-beautiful-dnd": "^13.0.0",
    "react-charts": "^2.0.2-next.6",
    "react-dom": "^16.12.0",
    "react-draggable": "^4.4.3",
    "react-dropzone": "^10.2.1",
    "react-event-timeline": "^1.6.3",
    "react-inlinesvg": "^1.2.0",
    "react-map-interaction": "^1.3.2",
    "react-player": "^1.15.3",
    "react-qr-reader2": "^1.1.0",
    "react-router-dom": "^5.1.2",
    "react-rte": "^0.16.1",
    "react-scripts": "3.4.0",
    "react-simple-keyboard": "^2.3.51",
    "react-sound": "^1.2.0",
    "react-stack-grid": "^0.7.1",
    "react-transition-group": "^4.3.0",
    "react-use": "^15.3.0",
    "react-world-flags": "^1.3.0",
    "remove-markdown": "^0.3.0",
    "yup": "^0.28.0"
  },
  "scripts": {
    "start": "react-scripts start && cra-append-sw --mode dev ./public/custom-sw.js",
    "build": "react-scripts --max_old_space_size=8192 build && cra-append-sw ./public/custom-sw.js",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "format": "prettier --write src/**/*.{js,jsx}",
    "amplify-modelgen": "node amplify/scripts/amplify-modelgen.js",
    "amplify-push": "node amplify/scripts/amplify-push.js"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "ini": "^1.3.5",
    "inquirer": "^6.5.1",
    "prettier": "^1.19.1"
  }
}

**Comment by UnleashedMind** [comment]
In your description: "but not when you are logged in with Groups". Did you use the Amplify CLI's auth category to create the user group in Cognito? Please use the group's Role ARN and go to the IAM's console to check the role's policy.

**Comment by DanielAlejandroMontesRodriguez** [comment]
> In regarding to this part of the description: "but not when you are logged in with Groups", did you use the Amplify CLI's auth category to create the user group in Cognito? Please use the group's Role ARN (the part after the / is the role name), and go to the IAM's console to check the role's policy, is there any suspicious policy specified for the group?

Yeah we use cli to create groups in cognito, the solution we implement right now is to add those policies in the prediction template.json.  When you add predictions it only asks for auth and guest users and it configures the correct policy for auth and oauth IAM roles

> ? What would you like to convert? (Use arrow keys)
❯ Convert text into a different language 
  Convert text to speech 
  Convert speech to text 
  Learn More 
? Who should have access? Auth and Guest users

i think its missing a part where you can configure access by groups

**Comment by giorgiocarniel** [comment]
> the solution we implement right now is to add those policies in the prediction template.json

@DanielAlejandroMontesRodriguez Can you share how you added these policies on the template.json?

**Comment by giorgiocarniel** [comment]
@DanielAlejandroMontesRodriguez I'm still facing the AccessDeniedException issue because I'm using Cognito groups too. Can you share the template.json you used to solve the problem, please?

**Comment by yuth** [comment]
This is an known issue where if there the user belongs to a custom cognito userpool group, the policy used for that user doesn't have all the permissions that are available for Auth user role. I have marked this as a bug

**Comment by yuth** [comment]
The workaround for this right now is to create an custom resource and add policy to support the custom roles created by the userPool groups. I have an sample [repo](https://github.com/yuth/custom-role-policy-for-translate), which adds the custom policy for `Admins` and `Moderators` group.

This follows the guideline we have for [custom resources](https://docs.amplify.aws/cli/usage/customcf#n1-configure-backend-configuration-with-custom-resource). 

If have added a custom resource called [policy](https://github.com/yuth/custom-role-policy-for-translate/tree/main/amplify/backend/customRoles/policy) and the part that you will have to change in order for this to work are
1. [`convertPolicyName`](https://github.com/yuth/custom-role-policy-for-translate/blob/main/amplify/backend/customRoles/policy/parameters.json#L2) in oaramters.json, This should match the policy name you have for your [translate resource](https://github.com/yuth/custom-role-policy-for-translate/blob/main/amplify/backend/predictions/translate/parameters.json#L3).
2. You need to update your `backed-config.json` to include the custom resource. Here the name of the `auth` should reflect the resource name of your userpool resource name
https://github.com/yuth/custom-role-policy-for-translate/blob/057a1615b4397490cc94dea1d3dcb0ca0b66aa14/amplify/backend/backend-config.json#L33-L47
3. You need to copy of this file in your content to your `<proj-root>/amplify/backedn/amplfy-meta.json`
4. Parameters in your custom resource [`template.json`](https://github.com/yuth/custom-role-policy-for-translate/blob/main/amplify/backend/customRoles/policy/template.json) should reflect the name of your auth resource and Cognito  Group names that you have in your project

**Comment by bregan** [comment]
Hi @yuth ,

Thanks for the post it was very useful.

I just went through your example repo and the custom resources documentation that you referenced in your post.

I followed the links everywhere and it all makes sense, except for item 3 above.

In the documentation here `https://docs.amplify.aws/cli/reference/files#core-amplify-files` it says not to manually edit the file.

I feel I am missing something on this.  Could you clarify what I should be doing for item 3?

Regards,

Brendan

**Comment by yuth** [comment]
@bregan the documentation says not to edit the file manually from `#current-cloud-backend` but you can edit contents of `backend` folder

![Screen Shot 2021-05-04 at 11 54 37 AM](https://user-images.githubusercontent.com/511386/117054986-8553c700-accf-11eb-885f-29e48c8f6546.png)
