### ISSUE TITLE
@searchable with @auth - query returns items.size() instead of total hits

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#5121]
**Describe the bug**
Note - this **only** happens for models with the @auth directive, the models without @auth works fine.

In the `Query.searchX.res.vtl` resolver that the CLI generates the end looks like this - 
```
#set( $es_response = {
  "items": $es_items
} )
#if( $es_items.size() > 0 )
  $util.qr($es_response.put("nextToken", $nextToken))
  $util.qr($es_response.put("total", $es_items.size()))
#end
$util.toJson($es_response)
```

but it should be this - 
```
#set( $es_response = {
  "items": $es_items
} )
#if( $es_items.size() > 0 )
  $util.qr($es_response.put("nextToken", $nextToken))
  $util.qr($es_response.put("total", $ctx.result.hits.total))
#end
$util.toJson($es_response)
```

because it now currently returns the length of the array of the items, which is incorrect.

**Amplify CLI Version**
4.27.2

**To Reproduce**
add @model,
add @searchable to model,
add @auth to model.
add some items to DB (for example 3 items), 
perform search query with limit set to 2, 
the total will be equal to 2 even though there are 3 total results

**Expected behavior**
the `total` field is equal to the total number of documents that fit the filter condition

**Comment by RossWilliams** [comment]
The PR which added this change has a comment for why it is done this way. The elasticsearch result is filtered by auth rules. You don't want to leak information about the total size of the response if a user is only supposed to see a partial list of the response.

If your use case is not concerned about this data leakage, you can customise the template to remove these lines. But Amplify should operate as secure-by-default

https://github.com/aws-amplify/amplify-cli/pull/2602#issuecomment-543844821

**Comment by renebrandel** [comment]
Hi this should now be addressed with Transformer v2. https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#aggregate-values-for-search-result-minimum-maximum-average-sum-terms We also added support for other aggregation queries. The auth rules are now applied at query-time instead of result-post-processing time.
