### ISSUE TITLE
Cannot add S3 event trigger to a lambda function when using Cognito groups

### ISSUE THREAD

**Issue by jingxizhang** [aws-amplify/amplify-cli#5124]
**Describe the bug**
I tried to add a S3 event triggered lambda function using amplify cli. But after the function is added, the amplify push failed. Note: the S3 is using individual groups for the restrict access.

**Amplify CLI Version**
4.27.0

**To Reproduce**
1. Create cognito user pool and user groups using amplify add auth.
2. Create using amplify add storage.
3. Update S3 storage template by running "amplify update storage"
3.a. Select "Individual Group" when it asks the "Restrict Access" for S3 bucket.
3.b Give the permissions for the groups to access S3 bucket.
4. Run "amplify push".
4.a. amplify push fails

**Expected behavior**
amplify push should be successful.

**Screenshots**
the push failed with the error:
UPDATE_FAILED               AdminGroupPolicy                                                       AWS::IAM::Policy           Wed Aug 12 2020 16:04:33 GMT-0700 (Pacific Daylight Time) The role with name authproceptgql5d4b5c6dUserPoolId-AdminGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: e868ccda-7e61-42bb-a00d-673012defc7e)
UPDATE_FAILED               EngineerGroupPolicy                                                    AWS::IAM::Policy           Wed Aug 12 2020 16:04:33 GMT-0700 (Pacific Daylight Time) Resource update cancelled                                                                                                                                                       
CREATE_FAILED               S3TriggerBucketPolicy                                                  AWS::IAM::Policy           Wed Aug 12 2020 16:04:33 GMT-0700 (Pacific Daylight Time) Resource creation cancelled                                                                                                                                                     
UPDATE_FAILED               AnalysisGroupPolicy                                                    AWS::IAM::Policy           Wed Aug 12 2020 16:04:33 GMT-0700 (Pacific Daylight Time) The role with name authproceptgql5d4b5c6dUserPoolId-AnalysisGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: a993fe8e-b441-407b-a129-d00e79816f22)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version:  v12.13.1

**Additional context**
It is a bug of Amplify CLI. It does not generate the reference to the user pool id in backend/awscloudformation/nested-cloudformation-stack.yml file. So when the S3 storage template reference to the user pool id  (the cognito user pool resource name is authproceptgql5d4b5c6d in my case) it just uses the default string "authproceptgql5d4b5c6dUserPoolId" and appends it with the group role. That id won't be found in the amplify stack.
It works if I manually add the user pool id reference in the S3 storage parameters.json file:
    "authproceptgql5d4b5c6dUserPoolId": {
        "Fn::GetAtt": [
            "authproceptgql5d4b5c6d",
            "Outputs.UserPoolId"
        ]
    },

**Comment by UnleashedMind** [comment]
Could you install the latest Amplify CLI and try again? 
I was not able to reproduce the error. 
the "authxxxxUserPoolId" is indeed generated in the backend/awscloudformation/nested-cloudformation-stack.yml file, and correctly referenced by the storage category's CloudFormation template.
