### ISSUE TITLE
Add new available regions for Aurora Serverless

### ISSUE THREAD

**Issue by danieljack2** [aws-amplify/amplify-cli#5128]
**Is your feature request related to a problem? Please describe.**
Aurora Serverless support in Amplify is currently only setup for a handful of regions. However the Data API for Aurora Serverless has now been rolled out to more regions.

Current supported regions: us-east-1, us-east-2, us-west-2, ap-northeast-1, eu-west-1

I believe the requirement is just the Data API availability and that should be available in more regions now, according to the [Aurora User Guide](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)

**Describe the solution you'd like**
Add new regions as supported for amplify api add-graphql-datasource. 
ap-southeast-1
ap-southeast-2 (This is the region i am actually interested in)
ap-northeast-1
ap-south-1
eu-central-1
eu-west-2
eu-west-3

**Comment by kristianmandrup** [comment]
Let's add these regions and make a PR ;)

**Comment by kristianmandrup** [comment]
See the file `supported-datasources.ts`

```ts
    alias: 'Aurora Serverless',
    defaultValuesFilename: 'appSync-rds-defaults.js',
    serviceWalkthroughFilename: 'appSync-rds-walkthrough.js',
    cfnFilename: 'appSync-rds-cloudformation-template-default.yml.ejs',
    provider: 'awscloudformation',
    availableRegions: ['us-east-1', 'us-east-2', 'us-west-2', 'ap-northeast-1', 'eu-west-1'],
```

Simply change to

```ts
    availableRegions: [ 
      'us-east-1', 'us-east-2', 'us-west-2', 'ap-northeast-1', 'eu-west-1',
      'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1', 'ap-south-1', 
      'eu-central-1', 'eu-west-2', 'eu-west-3'
    ],
```

**Comment by kristianmandrup** [comment]
Clone this repo

```sh
➜ git checkout -b add-aurora-regions
Switched to a new branch 'add-aurora-regions'

# Make the change above!!

➜  amplify-cli git:(add-aurora-regions) ✗ git commit -am "5128 add more aurora serverless regions"
[add-aurora-regions bc21295d0] 5128 add more aurora serverless regions
 1 file changed, 5 insertions(+), 1 deletion(-)
➜  git push
```

PROFIT :)

**Comment by cjihrig** [comment]
This was addressed by https://github.com/aws-amplify/amplify-cli/pull/8577. Closing.
