### ISSUE TITLE
Add analytics ignores configured region and deploys Amazon Pinpoint app to us-east-1

### ISSUE THREAD

**Issue by dennisAWS** [aws-amplify/amplify-cli#513]
Amplify version: 0.2.1-multienv.1
Platform: MacOS Mojave

Issue: Amazon Pinpoint application created in the wrong region. It deploys pinpoint app to us-east-1 regardless of my default amplify configured region of us-west-2. Amazon Pinpoint is now available in us-west-2.

Reproduction Steps:
Amplify default region: us-west-2 (Oregon)
> amplify add analytics
> amplify push
Actual Result: Amazon Pinpoint application is created in the us-east-1 region
Expected Result: Amazon Pinpoint application created in the us-west-2 region

**Comment by mihaiblaga89** [comment]
Right now, if Pinpoint is created in the Auth region if it's supported. However, apparently you can't select a Pinpoint instance from another region than 'us-east-1' in Cognito->Analytics. Can you add an option to actually select on which region to create the Pinpoint instance, just like Auth?

**Comment by UnleashedMind** [comment]
The CLI has been updated for both the @release and @multienv versions. 
There is a mapping to create the Pinpoint app in the nearest available region.

**Comment by hussaino3** [comment]
I don't know if you guys found a way to solve this, what I did was I went to the amplify folder in my project. Then I changed all the CloudFormation json objects that had an environment variable of region and made it literal us-east-1.
