### ISSUE TITLE
Add verbosity setting to improve CLI errors usability

### ISSUE THREAD

**Issue by peterv1988** [aws-amplify/amplify-cli#5130]
**Is your feature request related to a problem? Please describe.**
When running any Amplify CLI command, whenever a problem has occurred with one of the configuration files usually an error is shown. It can be almost impossible to figure out sometimes where the error is originated from.

To give an example of such a situation, I have initiated a new project, to mimic the problem I have on purpose made a typing error in a Amplify JSON file. But mostly this happens for example in case where the internet connection got interrupted halfway during a `push` procedure, leaving the Amplify project in incorrect drifted state. 

In the output you can see it is unclear in which part of the `push` procedure the error occurred, leaving it a big challenge to start recovering:
>Syntax Error: Expected Name, found }
>An error occurred during the push operation: Syntax Error: Expected Name, found }
```
$ amplify push -y
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Api      | test                    | Update    | awscloudformation |
✖ An error occurred when pushing the resources to the cloud

Syntax Error: Expected Name, found }
An error occurred during the push operation: Syntax Error: Expected Name, found }

# Perhaps if feature is added, add message like 'try to run command again with -vvv to get more information'
```

**Describe the solution you'd like**

Allowing the user to set verbosity (`amplify <command> -vvv` would make it easier for user to understand the error thrown by Amplify CLI.
> -v:  verbose (print errors/warnings while in event loop)
> -vv: very verbose (also print client commands/responses)
> -vvv: extremely verbose (also print internal state transitions)
Adding each step of internal state transitions would allow user to identity where to look for resolving issue:
```
$ amplify push -y -vvv
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name              | Operation | Provider plugin   |
| -------- | -------------------------- | --------- | ----------------- |
| Api      | test                    | Update    | awscloudformation |
[...]

[INFO] <detailed information about current state transition>
[...]
[ERROR] update.ts:2
api-artifact-handler.ts:5  
Syntax Error: Expected Name, found }
An error occurred during the push operation: Syntax Error: Expected Name, found }

✖ An error occurred when pushing the resources to the cloud
``` 

**Describe alternatives you've considered**
Currently I have to search through all (both automatically generated and normal) configuration files by hand

**Comment by r0zar** [comment]
@peterv1988 This error is caused when validating the `graphl.schema` file.

Short of adding verbosity levels for all logging- just adding a bit of text during the errors here explaining that the errors are coming from the schema file validation would really help. Just debugged this one for a few hours to track this down. :sleepy:

**Comment by r0zar** [comment]
Also specifically, it's probably because somewhere in your schema you have something that looks like this:

```

  listMyWorkflows(): [Workflow] @function(name: "AppSyncAuthorizer-${env}")
```

when it should look like this:

```

  listMyWorkflows: [Workflow] @function(name: "AppSyncAuthorizer-${env}")
```

Noting the lack of parenthesis.
