### ISSUE TITLE
Too long waiting for a response from lambda functions with nested fields in mock.

### ISSUE THREAD

**Issue by MariuszWitkowski** [aws-amplify/amplify-cli#5131]
**Describe the bug**

Response with the fields that are resolving in another lambda function is horrible long after version **4.13.0**. 

The average response of execution for the eleven lambdas takes 18sec (~1,5sec per lambda) when the handler invoking itself takes less than 100ms

- `4.27.3-alpha.5` - the latest tested version

- `4.13.0` - the latest one when it worked properly

- `4.13.1` - `4.17.2` - the range of versions where lambda function returns null on response

- `4.18.0` - first version which has a delay on response and returns the correct value

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

Define the query in the schema:

```graphql
type Query {
  get (
    parentId: ID
    id: ID!
  ) : IIdentifiedNode @function(name: "get-${env}")
  list (
    parentId: ID
    type: CriteriaTypeEnum
    criteria: Criteria
  ) : RootPagination @function(name: "list-${env}")
}
```

Define type with nested field with amplify function in the schema:

```graphql
type Element implements IIdentifiedNode {
  id: ID!
  name: String!
  createdBy: User @function(name: "get-${env}")
}
```

Create a query in explorer (or application):

```graphql
query MyQuery {
  list {
    elements {
      ... on Element {
        id
        name
        createdBy {
          name
        }
      }
    }
  }
}
```

That query will execute a list with ten elements. The next step is to create ten `get` lambda function instances for *createdBy* field. All lambda functions for this field will be executed synchronously (~100ms for each one and ~1,5sec delay between them)

**Expected behavior**

Execute lambda asynchronously when it is possible and reduce the delay between executions between functions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu/Fedora/Mac
 - Node Version. 14.5, 12.x

**Additional context**

The direct change in node_modules for an `amplify-util-mock` package (in `@amplify-cli`) to version `3.13.0`  gives us a positive result. However, this one is printing warning in the terminal with `@deprecated` directive

**Comment by edwardfoyle** [comment]
Hi @MariuszWitkowski this is a known issue we are tracking here #4319
Closing this as a duplicate
