### ISSUE TITLE
Running "amplify pull" o a newly cloned project causes an "invalid configuration settings" error

### ISSUE THREAD

**Issue by Zablas** [aws-amplify/amplify-cli#5133]
**Describe the bug**
There are 3 people on my team working on the project. Yesterday I gave one of them access with my accessKey and secretKey and they were able to access our backend perfectly. Today I tried giving another one access but every time he chooses the region after entering the keys he gets an error saying "Failed: invalid configuration settings"

**Amplify CLI Version**
4.27.2

**To Reproduce**
1) Pull the project from github
2) Run amplify pull
3) Enter the keys
4) Choose the region

**Expected behavior**
The backend should successfully be pulled.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.18.3

**Comment by UnleashedMind** [comment]
What command did the coworker run to set up his/her local development? 
Try to open the ~/.aws/credentials and ~/.aws/config files and put the aws_access_key_id, aws_secret_access_key and region into a profile, and select the profile when the init workflow prompts for it.

**Comment by Zablas** [comment]
@UnleashedMind I've talked to him about this. He seems to be missing the .aws folder. Should he create it manually then?

**Comment by UnleashedMind** [comment]
yes, you can create that folder manually

**Comment by Zablas** [comment]
@UnleashedMind after putting the keys manually into the files it seems to be working. Thanks for the help!
