### ISSUE TITLE
Duplicate URI created in amplifyConfiguration

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-cli#5134]
**Describe the bug**

From Discord conversation in ios-help channel.

Developer seeing the signIn and signOut uri duplicated and do not know what caused it.
The last step they tried is "Adding a pre sign-up function". 

```
"SignInRedirectURI": "myapp://,myapp://",
```

**Amplify CLI Version**
Unknown

**To Reproduce**
Unknown

**Expected behavior**
The URI should not contain duplicates.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by UnleashedMind** [comment]
Can you gather the following information from the customer?
 
Amplify CLI version, OS, node version and steps to reproduce.

**Comment by UnleashedMind** [comment]
Closing the issue due to inactivity, feel free to open another issue if the problem still exists.
