### ISSUE TITLE
Amplify-CLI not working (amplify add auth)

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-cli#5144]
**Describe the bug**
I installed the latest Version of ampliy-cli for flutter and i could run amplify-init and so on. But when i try to add auth "amplify add auth" and select something, the cli instantly exit. This also happens when i try to add storage and the cli asks then for auth.

**To Reproduce**
On Windows 10, install the Version 4.26.1-flutter-preview.0 and run "amplify add auth"

**Expected behavior**
adding Auth

**Screenshots**
$PS: xxx > amplify add auth
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? (Use arrow keys)
> Username
  Email
  Phone Number
  Email or Phone Number
  I want to learn more.
$PS: xxx >

The Real Problem is, that i just want to know how the Configuration should look like, because i hate using the cli and will use my already created Cognito User Pool.

Best Regards,
Ray

**Comment by flywheelms** [comment]
No customer response.
