### ISSUE TITLE
handling nullable connections

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#5152]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I get an error "_All fields provided to an @connection must be non-null scalar or enum fields_".

**Amplify CLI Version**

@aws-amplify/cli@4.21.3

**To Reproduce**

1. Create models like so:

```graphql
type ModelOne 
  @model {
  id: ID!
  testField: String
}

type ModelTwo
  @model {
  id: ID!
  testField2: String
  modelOneId: ID
  modelOne: @connection(fields: ["modelOneId"])
}
```

this will throw an error saying "_All fields provided to an @connection must be non-null scalar or enum fields_"

But when using the "old", and supposedly no longer recommended way of defining connections,

```graphql
type ModelOne 
  @model {
  id: ID!
  testField: String
}

type ModelTwo
  @model {
  id: ID!
  testField2: String
  modelOneId: String
  modelOne: @connection(keyField: "modelOneId")
}
```

it works as I expected?

**Expected behavior**

Provide an option for nullable connection or turn the old and unrecommended way of doing it to be that option (? not really sure), the docs did not talk about this option.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Node Version: N/A

**Additional context**

N/A

**Comment by UnleashedMind** [comment]
@aprilmintacpineda This is an known behavior, I will mark this as enhancement, our team will review it. 
@RossWilliams Thanks for your contribution, our team will review the PR.

**Comment by blazinaj** [comment]
👍

**Comment by mjza** [comment]
@UnleashedMind 
Is it still under reviewing?

**Comment by mjza** [comment]
@aprilmintacpineda I tested your solution but it does not work anymore.

**Comment by aprilmintacpineda** [comment]
> @aprilmintacpineda I tested your solution but it does not work anymore. I am using the latest amplify cli (V 4.40.1) .

Sorry to hear that, not sure why it doesn't work anymore though...

**Comment by mjza** [comment]
@aprilmintacpineda I found an alternative [here](https://github.com/aws-amplify/amplify-cli/issues/3275#issuecomment-663919926)

**Comment by blazinaj** [comment]
A dirty way around this is to just provide non-existing IDs for the required ID fields that are null.

```
createModelTwo {
  testField2: "Hello World"
  modelOneId: "thisIDneverExists"
}
```

This (surprisingly) does not cause an error. And when you query ModelTwo, the connection will return null.

**Comment by ahtokca** [comment]
Which behavior is guaranteed? Is there any way to have optional connections?

**Comment by edwardfoyle** [comment]
Nullable connections is now supported in the latest version of the CLI. Please upgrade to try it out
