### ISSUE TITLE
Returning only required fields from AWS Amplify GraphQL Query

### ISSUE THREAD

**Issue by benjeater** [aws-amplify/amplify-cli#5155]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
AWS Amplify API GraphQL 

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
AWS Amplify Auth
AWS Amplify API GraphQL 

**Provide additional details e.g. code snippets**

I am trying to implement graphQL API using the AWS Amplify framework in React. The schema is set up and data is being fetched from my database correctly; I would now like to choose which of the items will be returned when I make a request.

The code below is making a request to get the User data
```
import { API, graphqlOperation } from 'aws-amplify';
import * as Queries from '../../graphql/queries';

export default function(id) {

  const queryDetails = {
    id,
  }

  return API.graphql(graphqlOperation(Queries.getUser, queryDetails));
}
```
The documentation I have been reading (here and here) doesn't seem to cover how to define what items you want to be returned. I have the following Model defined for my User, but in some requests I only want the items with the arrow next to them returned:
```
type User @model {
  id: String!
  sk: String!
  firstName: String!  <---
  lastName: String!   <---
  avatar: String
  jobTitle: String
  company: String
  ...
}
```
Is there a way within the queryDetails object to define what items I would like returned?

**Comment by RossWilliams** [comment]
The files in the graphql folder are not meant to be used in your app directly. They are there merely as a guide to help you get started. You can copy/paste the queries you need into another folder/file and modify them to suit your needs

**Comment by benjeater** [comment]
Thanks @RossWilliams! I think I was getting mixed-up and thinking the codegen was only creating the resolvers and not the actual queries.

**Comment by benjeater** [comment]
> What we usually do in our project is that we define a custom query in a separate file and only list those fields in this query that we want to access. So in this particular case, we would've declared the following query in a separate file:
> 
> ```js
> export const getUserWithName = /* GraphQL */ `
>   query GetUser($id: ID!) {
>     getUser(id: $id) {
>       firstName
>       lastName
>     }
>   }
> `;
> ```
> 
> Not sure if you've already considered and dismissed such an approach, but pointing it out just in case.

Really, I was wondering if there was a way to generate queries in the schema.graphql file, but I realised after Ross' response that I was expecting to use the codegen function for all my queries. 

While you can define queries on the .GraphQL files and have them generated, this isn't documented well enough for me to learn it. Instead I just used the AppSync query writer on the AWS console to create what I needed, then copied the query into a file in created (custom-queries.js) in the generated `src/graphql` folder. 

I now have a few files in my `src/graphql` folder to define all my queries. I'm hoping in future that the documentation for using the `schema.graphql` file will be detailed enough to have everything generate itself 😀
