### ISSUE TITLE
Is there a way to assign a different lambda to the default resolvers?

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-cli#5166]
I want to override some of the default resolvers for queries and mutations because I need to add some particular behavior to the operations (for example I have some logical deletes so I wan't getTodo to return null when the item exists in DynamoDB but the status = DELETED).

I did tried the approach suggested here: https://docs.amplify.aws/cli/graphql-transformer/resolvers but it failed due: "Only one resolver is allowed per field".

Is there some alternative ?, might I be doing something wrong?
I can write `getTodoCustom`, `createTodoCustom`, etc. but it is not good from API perspective.
I can create the resources manually but it will be inconvenient (part of the model will be manual and part declared in the schema).

Specifically:
```
CREATE_FAILED               GetTodoResolver                                                                      AWS::AppSync::Resolver     Tue Aug 25 2020 00:57:30 GMT-0300 (Uruguay Standard Time) Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: b461ba5d-....; Proxy: null)
```

**Which Category is your question related to?**
- API / GraphQL

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
AppSync, Lambda

**Provide additional details e.g. code snippets**

Here was my change on CustomResources.json:
```
"Resources": {
    "ResolversLambdaDataSource": {
      "Type": "AWS::AppSync::DataSource",
      "Properties": {
        "ApiId": {
          "Ref": "AppSyncApiId"
        },
        "Name": "ResolversLambdaDataSource",
        "Type": "AWS_LAMBDA",
        "ServiceRoleArn": {
          "Fn::GetAtt": [
            "ResolversLambdaDataSourceRole",
            "Arn"
          ]
        },
        "LambdaConfig": {
          "LambdaFunctionArn": {
            "Fn::Sub": [
              "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:resolvers-${env}",
              { "env": { "Ref": "env" } }
            ]
          }
        }
      }
    },
    "ResolversLambdaDataSourceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "RoleName": {
          "Fn::Sub": [
            "ResolversLambdaDataSourceRole-${env}",
            { "env": { "Ref": "env" } }
          ]
        },
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "appsync.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "InvokeLambdaFunction",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:invokeFunction"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": [
                        "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:resolvers-${env}",
                        { "env": { "Ref": "env" } }
                      ]
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    "GetTodoResolver": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": {
          "Ref": "AppSyncApiId"
        },
        "DataSourceName": {
          "Fn::GetAtt": [
            "ResolversLambdaDataSource",
            "Name"
          ]
        },
        "TypeName": "Query",
        "FieldName": "getTodo",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.getTodo.req.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.getTodo.res.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        }
      }
    }
  },
```

**Comment by yuth** [comment]
@ignaciolarranaga if you just want to change the resolver, this could be achieved by creating the resolver template inside resolver folder of your api.

For instance if you want to change  query `getTodo` to return the return null when the status is set to DELETED then you need to create a new file called `<project-root>/amplify/backend/api/<api-name>/resolvers/Query.getTodo.res.vtl` with content.

```
#if( $ctx.error )
    $util.error($ctx.error.message, $ctx.error.type)
#else
    #if($ctx.result.status == "DELETED")
        $util.toJson(null)
    #else
        $util.toJson($ctx.result)
    #end
#end
```

One down side to overriding the resolvers is that effectively you're ejecting the transformation for that specific field and you would have to make sure you're updating the resolver if there is any changes to directives that could affect that field. We have an RFC https://github.com/aws-amplify/amplify-cli/issues/1055, which would allow adding custom logic using pipeline resolver without ejecting the field completely out. Please feel free to up vote and provide feedback there

**Comment by ignaciolarranaga** [comment]
Thanks @yuth , although the VTL can resolve some situations it is pretty limited, for example, in the creation I'm calculating the language using Comprehend, so it will not really have all the power that I need for all the scenarios.

I just checked proposal for pipeline resolvers and I think will address all that I need.

**Comment by yuth** [comment]
> I can write `getTodoCustom`, `createTodoCustom`, etc. but it is not good from API perspective.
> I can create the resources manually but it will be inconvenient (part of the model will be manual and part declared in the schema).

If you want to have custom lambda resolvers, with then you can ask transformer not to create the get query and create mutation

```graphql
type Todo @model(
  queries: { get: null, list: "listTodos" }
  mutations: { create: null, update: "updateTodo", delete: "deleteTodo" }
) {
   id: ID!
    title: String!
}

type Query {
   getTodo(id: ID!): Todo
}

type Mutation {
   createTodo(....): Todo
}
```

By doing this you could keep the API contract stable and create custom resolvers either using `@function` directive or creating a custom resolver. Once we have support for pipeline resolvers, you could remove these custom resolvers and use them

**Comment by ignaciolarranaga** [comment]
Thanks for the suggestion, yes I was also concerned about the duplication of methods but didn't had the time to get into that.

Just in case, is there a way to customize the Inputs of the transformer operations? (i.e. the createTodo for example).

Let me explain, one of the reason to have a createTodoCustom was because as I said some parameters were calculated and not received through parameters (e.g. the language/locale of the Todo) so actually the CreateTodoCustomInput was not having it.
