### ISSUE TITLE
Adding Cognito user pool groups using amplify auth update to an existing Cognito resource?

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5167]
**Which Category is your question related to?**

amplify push

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

Auth

**Provide additional details e.g. code snippets**

I already use Cognito in my Amplify CLI app. Can I safely add Cognito user pool groups using amplify update auth? Below is what I get when I run the update.

```
amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito 
resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? (Use arrow keys)
  Apply default configuration with Social Provider (Federation) 
  Walkthrough all the auth configurations 
❯ Create or update Cognito user pool groups 
  Create or update Admin queries API
```

**Comment by yuth** [comment]
@christodupreez adding just the user pool group to an existing cognito resource should not have any unintended consequences. This warning is specifically intended for cases changing authorization service from `User Sign-Up, Sign-In, connected with AWS IAM controls` to `User Sign-Up & Sign-In only (Best used with a cloud API only)` and vice versa.

**Comment by christodupreez** [comment]
@yuth thank you for the feedback. Will give it a try.
