### ISSUE TITLE
When UpdateRolesWithIDPFunction function created in nested-cloudformation-stack.yml

### ISSUE THREAD

**Issue by leehung-net** [aws-amplify/amplify-cli#5168]
I was update amplify CLI version to 4.27.2 and I have a issue below:
Before, I using `amplify push`, the file nested-cloudformation-stack.yml hava generate UpdateRolesWithIDPFunction 
```
"UpdateRolesWithIDPFunction": {
			"DependsOn": [
				"AuthRole",
				"UnauthRole"
			],
			"Type": "AWS::Lambda::Function",
			"Properties": {
				"Code": {
					"ZipFile": {
					}
				},
				"Handler": "index.handler",
				"Runtime": "nodejs10.x",
				"Timeout": "300",
				"Role": {
					"Fn::GetAtt": [
						"UpdateRolesWithIDPFunctionRole",
						"Arn"
					]
				}
			}
		}
```
alter upgrade: UpdateRolesWithIDPFunction not be generate to nested-cloudformation-stack.yml

anyone have me cleary why UpdateRolesWithIDPFunction not generate?

**Amplify CLI Version** 
4.27.2

**Comment by yuth** [comment]
@leehung-net did the upgrade cause any deployment issue or are you just wondering why that function is not getting generated after the upgrade? 

Amplify CLI generates this lambda function only if the auth category has identity pool enabled. If you have updated your auth category to use just the user pool by selecting `User Sign-Up & Sign-In only (Best used with a cloud API only)` in the auth service selection the identity pool will not be created and the lambda function will not be generated.

**Comment by leehung-net** [comment]
@yuth function is not getting generated when me upgrade to 4.27.2
When add auth, i using `User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)` and enable `unauthenticated`.
I using IAMInlinePolicies for set permission for unauthenticated for graphql.
With amplify version previous (i don't remember version), function UpdateRolesWithIDPFunctionRole generated and role `unauthRole` working correct.
But after upgrade, function UpdateRolesWithIDPFunctionRole not generated, so role `unauthRole` not be update 'AssumeRolePolicy'. So graphql api not working with unauthenticated, because identity pool not trust in `unauthRole`

**Comment by yuth** [comment]
Could you share the redacted version of your parameter.json file for auth category. The file is located in `amplify/backend/auth/<resource-name>/parameters.json`. I am interested to see if that file has `identityPoolName` in it

**Comment by leehung-net** [comment]
@yuth 
![image](https://user-images.githubusercontent.com/8251888/91377308-4cfb0f80-e849-11ea-8e54-feeeb05f8bf4.png)

**Comment by yuth** [comment]
Could you join [amplify discord channel](https://discord.gg/amplify) which might make it easier to debug this issue

**Comment by leehung-net** [comment]
I joined discord

**Comment by leehung-net** [comment]
@yuth any updated?

**Comment by kaustavghosh06** [comment]
@leehung-net Are you still suck on this?
 UpdateRolesWithIDPFunction  is generated when auth is enabled + identity-pool. Did your deployment fail in any case after upgrading?
