### ISSUE TITLE
npm install getting error

### ISSUE THREAD

**Issue by csarathm** [aws-amplify/amplify-cli#5169]
Hi,
When i am installing this package , getting following error :

Unexpected end of JSON input while parsing near '..."fs-extra":"^8.1.0","'
command : npm install -g @aws-amplify/cli
Node : v12.18.3
npm : 6.14.6

**Comment by jhockett** [comment]
Hi @csarathm, what OS are you using?

**Comment by flywheelms** [comment]
No customer response.
