### ISSUE TITLE
Delayed API response when performing internal GraphQL call from Lambda resolver

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-cli#5170]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.25.0

**What AWS Services are you utilizing?**
Amplify
AppSync
Cognito
DynamoDB

**Provide additional details e.g. code snippets**

Hi everyone!

I've defined some GraphQL operations by using @model directive.

When using them from the client-side, through `aws-amplify` library, I get a pretty decent performance. Response is received with little to non perceivable delay (max. 1 second).

Then I defined a custom query by using @function directive. The associated Lambda resolver calls the above API internally ([GraphQL from NodeJS](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js)). This is to enforce custom authentication rules. However, when using this query from the client-side, through `aws-amplify` library, response is received with a disturbing inconsistent delay (4-6 seconds).

The Lambda resolver does not perform expensive operations and does not perform any API call other than the one specified above.

I expected some additional overhead because now I have two API calls in series, but the second one should not have that much latency (being an "internal" call between AWS resources in the same region). Is it there a way to improve this situation? And, more importantly, is this delay the expected one?

Thank you very much.

**Comment by yuth** [comment]
@ernestostifano There should not be any significant delay added. You should be able to diagnose what is causing delay by enabling x-ray tracing on your AppSync API and looking at trace log for you lambda function. That should give you a rough indication of where that latency is getting added.

**Comment by ernestostifano** [comment]
Sorry for the huge delay in my response (this is a little awkward, looking at the title of this issue). It seemed to me that the delay I was talking about was caused by the Lambda initialization time (the two Lambdas actually). After the first call, performance improves.
