### ISSUE TITLE
encryption for deployment buckets

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#5172]
**Which Category is your question related to?**
DEPLOYMENT. all amplify deployments uses cloudformation. a bucket gets created for each environment.

**Amplify CLI Version** 
I created my environment with 4.25.0 but now I'm using 4.27.3.

**What AWS Services are you utilizing?**
lots of them

**Provide additional details e.g. code snippets**
How can I confidently create and deploy new amplify environments that satisfy enterprise requirements for encryption on all buckets?

**Comment by yuth** [comment]
Amplify CLI does not have support for encrypting the deployment bucket. I am marking this as an enhancement to get this prioritized

**Comment by xorxero** [comment]
Yes please, better yet give us access to the CF template for configuring this bucket.
Amplfiy should make things easier but leave the option open for us to configure further if necessary. There should be no limitations on how we can use these AWS services just because we are using Amplify...

**Comment by gruckionvit** [comment]
> Yes please, better yet give us access to the CF template for configuring this bucket.
> Amplfiy should make things easier but leave the option open for us to configure further if necessary. There should be no limitations on how we can use these AWS services just because we are using Amplify...

Agreed, found this quite odd when I was attempting to add the encryption to the deployment bucket. After running `amplify push` I found the encryption wasn't setup and Amplify had just removed it from the `YAML` file. Less than helpful.

**Comment by edwardfoyle** [comment]
The latest versions of the CLI enable S3 SSE by default now. Please upgrade to the latest version to pull in the fix.
