### ISSUE TITLE
How would you deploy an amplify app to a separate AWS account without using amplify env

### ISSUE THREAD

**Issue by steadweb** [aws-amplify/amplify-cli#5173]
**Which Category is your question related to?**
Deployment / Multi AWS Account

**Amplify CLI Version** 
4.27.0

**What AWS Services are you utilizing?**
Cognito, Lambda, AppSync, S3

**Provide additional details e.g. code snippets**
I have a requirement from a client that wants to package the amplify application up from one AWS account and deploy to another. I've tried various routes by removing files / folders from the amplify directory, but I can't see to get it right. The client will be in complete control of the source code, but when a new feature is added, ideally, they'd like to package this up, and deploy using amplify cli.

**Comment by yuth** [comment]
Amplify supports sharing the project externally using an version control system as documented [here](https://docs.amplify.aws/cli/teams/shared). When an amplify project is added to an git repository, it adds only the definition of resources to the repository and keeps provisioned environment specific info inside `team-provider-info.json`. The environment that are created in a single project can be in different AWS account, and one can change the environment only when they have the right credential to do this.

If you don't want to expose the details about the environment with the client, you could add `team-provider-info.json` into your git ignore.

**Comment by steadweb** [comment]
Thanks @yuth - I've used the CI/CD docs combined with the above, and I can deploy to a different env. I have found an issue with the hosting plugin which writes the bucket name to the parameter, but if the same env is deployed to a separate AWS account, the cloudformation script breaks because the same bucket name is created. That's a separate ticket though I believe.

**Comment by yuth** [comment]
Could you create a separate issue for this with additional details 

> I have found an issue with the hosting plugin which writes the bucket name to the parameter, but if the same env is deployed to a separate AWS account, the cloudformation script breaks because the same bucket name is created.

I am going to close this issue
