### ISSUE TITLE
amplify pull fetches previously deleted lambda function and layer

### ISSUE THREAD

**Issue by hugozap** [aws-amplify/amplify-cli#5174]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I pull environment changes with amplify-cli I get old folders from previously deleted functions and lambda layers.
If I check the contents of team-provider-info.json the old functions are not listed there.
If I try to remove them again with amplify remove function the old functions are not listed for deletion.

Not sure how to clean the env so amplify pull doesn't bring those old folders again?

**Amplify CLI Version**
4.27.0

**To Reproduce**

Not sure when things got out of sync:

- Delete function and lambda layer with amplify remove function
- push env changes
- checkout other environment and go back to original
- Run amplify pull
- The old folders (lambda, function) are created again.

**Expected behavior**
Previously deleted lambda layer/function should not be fetched.
A way to clean the out of sync cache should exist.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by jhockett** [comment]
Hi @hugozap, thanks for the bug report! I was able to reproduce this.

**Comment by jhockett** [comment]
Hi @hugozap, we released a fix for this in 4.29.0, however it's only fixed for [newly created Lambda layers](https://github.com/aws-amplify/amplify-cli/issues/4886#issuecomment-686798972).

Do you see the layer folders you want removed at `<project-root>/amplify/#current-cloud-backend/function/<layer-name>`?

**Comment by hugozap** [comment]
Hi John, yes I see them at that location.
