### ISSUE TITLE
Lambda function in Go with GraphQL

### ISSUE THREAD

**Issue by sky4git** [aws-amplify/amplify-cli#5177]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
functions
api

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.27.3

**What AWS Services are you utilizing?**
Lambda and AppSync

**Provide additional details e.g. code snippets**
I have created Lambda function with Go runtime. I have configured the GraphQL query to run this lambda function. 
All I want to know,  How lambda function written in Go, can read the payload when invoked from GraphQL query from frontend?

I cannot find any example anywhere?

Following are my code snippets to understand the scenario:
```gql
type Query {
  getCustData(name: String, region: String): String
    @function(name: "GetCustData-${env}")
}
```

In my Front-end tsx file.
```ts
const customer: any = await API.graphql(
          graphqlOperation(getCustData, {
            name: name,
            region: region,
          })
 );
```

my Go function excepts:
```go
type Request struct {
	Name     string `json:"name"`
	Region string `json:"region"`
}

// HandleRequest function
//func HandleRequest(ctx context.Context, request Request) (Response, error) {
}
```

I want to read the payload sent by GraphQL in the Request? But I don't know, How?

I am new to Go as well.

**Comment by yuth** [comment]
When using `@function` directive, the resolver wraps all the arguments inside an event object which is documented [here](https://docs.amplify.aws/cli/graphql-transformer/directives#usage-1). 

This code should provide you access to the arguments from the query `getCustData`
```go
// Arguments Graphql Arguments
type Arguments struct {
	Name      string `json:"name"`
	Region string `json:"region"`
}

// Event that is passed by the appsync
type Event struct {
	TypeName  string    `json:"typeName"`
	FieldName string    `json:"fieldName"`
	Arguments Arguments `json:"arguments"`
}

func handleRequest(ctx context.Context, ev Event) (string, error) {
	return fmt.Sprintf("Name:%s\nRegion:%s!", ev.Arguments.Name ev.Arguments.Region), nil
}
```

**Comment by sky4git** [comment]
I will give it a try.

**Comment by sky4git** [comment]
@yuth That worked 👍 . Exactly What I needed. 

However, I could not find it anywhere in the documentation. 

Thank you.

**Comment by yuth** [comment]
> However, I could not find it anywhere in the documentation.

We don't have anything language specific in the documentation, but the details about the event is listed [here](https://docs.amplify.aws/cli/graphql-transformer/directives#usage-1). The exact location is somewhere below as I can't hard link to it, I am attaching the scrrenshot

![Screen Shot 2020-08-26 at 5 43 51 PM](https://user-images.githubusercontent.com/511386/91370653-c6e8b580-e7c3-11ea-917a-d64d6585b559.png)
