### ISSUE TITLE
API Gateway setup for REST APIs has no CORS enabled for default 4xx and 5xx errors

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-cli#5183]
**Describe the bug**
Current setup throws CORS errors to the client instead of the underlying 4xx or 5xx making debugging much difficult. This should also fix these issues: #5013, #4937

**Amplify CLI Version**
4.27.3

**To Reproduce**
Run `amplify add api` to create a new REST API for `/todos` on the root of a new project and follow the steps below

- Please select from one of the below mentioned services: __REST__
- Provide a friendly name for your resource to be used as a label for this category in the project: __todosApi__
- Provide a path (e.g., /book/{isbn}): __/todos__
- Choose a Lambda source __Create a new Lambda function__
- Provide a friendly name for your resource to be used as a label for this category in the project: __todosLambda__
- Provide the AWS Lambda function name: __todosLambda__
- Choose the runtime that you want to use: __NodeJS__
- Choose the function template that you want to use: __Serverless ExpressJS function__
- Do you want to access other resources in this project from your Lambda function? __No__
- Do you want to invoke this function on a recurring schedule? __No__
- Do you want to configure Lambda layers for this function? __No__
- Do you want to edit the local lambda function now? __Yes__
- Restrict API access __Yes__
- Who should have access? __Authenticated and Guest users__
- What kind of access do you want for Authenticated users? __create, read, update, delete__
- What kind of access do you want for Guest users? __read__
- Do you want to add another path? __No__

When trying to access `/items` (a non-existing route) it throws a CORS error
<img width="1277" alt="Screenshot 2020-08-18 at 17 13 46" src="https://user-images.githubusercontent.com/4660316/91451050-ea1f6d80-e874-11ea-9c04-bf8b03617a70.png">

**Expected behavior**
After enabling CORS for default 4xx and 5xx errors I get a more detailed response when trying `/items` (a non-existing route)
<img width="1280" alt="Screenshot 2020-08-18 at 17 19 29" src="https://user-images.githubusercontent.com/4660316/91451122-00c5c480-e875-11ea-8a9e-93aacf120d7e.png">

Setting up CORS for 4xx and 5xx errors in API Gateway Console
<img width="949" alt="Screenshot 2020-08-18 at 17 17 44" src="https://user-images.githubusercontent.com/4660316/91451223-1d61fc80-e875-11ea-8551-1b5ee08d08cb.png">
<img width="1280" alt="Screenshot 2020-08-18 at 17 18 03" src="https://user-images.githubusercontent.com/4660316/91451233-1f2bc000-e875-11ea-9deb-de30082c0b23.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.7.0

**Additional context**
[Enable CORS with custom headers for an AWS Lambda function behind API Gateway](https://dev.to/leventov/enable-cors-with-custom-headers-for-an-aws-lambda-function-behind-api-gateway-in-serverless-framework-3702)

**Comment by yuth** [comment]
I am marking this as an enhancement and tagged for it to get prioritized

**Comment by pankaj-crypto** [comment]
When will this be available?

**Comment by tnorlund** [comment]
I found the error. The ARN was broken. It missed a star in the GET proxy:

*OLD*
```{
...
            "Resource": [
                "<ARN>staging/GET/*",
                "<ARN>/staging/GET//*",
            ]
...
}```

*NEW*
```{
...
            "Resource": [
                "<ARN>staging/GET/*",
                "<ARN>/staging/GET/*/*",
            ]
...
}```

**Comment by GeniaT** [comment]
Is there a possible workaround to allow CORS by still using the CLI ?

**Comment by jamesaucode** [comment]
I submitted a PR for to allow CORS for default 4xx and 5xx errors
