### ISSUE TITLE
Cognito and Pinpoint in different regions

### ISSUE THREAD

**Issue by srajsushmitha** [aws-amplify/amplify-cli#5190]
Is there any way that I can connect Cognito user pool in one region and pinpoint in another? I see that in aws console,
(manage cognito users->analytics) I can select pinpoint only from the region where cognito user pool is. 
Or could you please suggest if is there any alternative way that I can implement(without writing sign-up/sign-in code in front-end)?

**Comment by RossWilliams** [comment]
I think the documentation says if Pinpoint isn't available in the region where you have Cognito, you can connect to a Pinpoint app in US-EAST-1

**Comment by srajsushmitha** [comment]
We did.. but we are not able to connect cognito user pool to pinpoint.

**Comment by yuth** [comment]
@srajsushmitha could you provide more details about the region you have your userpool and pinpoint?

**Comment by srajsushmitha** [comment]
Cognito pool : eu-west-2 (London)
Pinpoint region: eu-west-1(Ireland)

**Comment by RossWilliams** [comment]
You cannot connect Cognito in eu west 2 to a pinpoint in eu west 1. You can only connect to pinpoint in us east 1, or you need to move Cognito to eu west 1.

**Comment by srajsushmitha** [comment]
Thanks

**Comment by yuth** [comment]
Closing the issue. Feel free to comment here if you need any further clarification.
