### ISSUE TITLE
amplify env checkout ->  Error: connect ETIMEDOUT 169.254.169.254:80

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#5192]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

![image](https://user-images.githubusercontent.com/21032419/91584053-aae04200-e984-11ea-818b-5366014f1d36.png)

**Amplify CLI Version**

4.27.3

**To Reproduce**

1. Created new environment via amplify console (connect branch).
2. After first deployment, there will be a message that allows you to copy-paste a command on the CLI, this command will add that new environment to your local -- Run that command to add that new env to your local.
3. Do amplify `env checkout <env>`
4. After you see the error, let it be, open a new terminal tab, do `amplify env list` and you'll see that you are in the target env on step 3.

**Expected behavior**

This should not happen.

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Node Version: v14.8.0

**Additional context**

N/A

**Comment by aprilmintacpineda** [comment]
Same with init

![image](https://user-images.githubusercontent.com/21032419/91585146-41f9c980-e986-11ea-8cee-d457abc4c4ae.png)

**Comment by yuth** [comment]
@aprilmintacpineda does comand hang after that with no additional ouptut? From the error it looks like the CLI could not connect to AWS servers. Is your computer behind a proxy server?

**Comment by aprilmintacpineda** [comment]
> does comand hang after that with no additional ouptut?

Yes it does as shown in the screenshot, after the error it still says _Initializing your environment: master_, when I press `ctrl + c` it does not cancel out.

> Is your computer behind a proxy server?

Nope, I am not behind a proxy server.

> From the error it looks like the CLI could not connect to AWS servers

Looks like so, BUT there are 3 environments in total, dev, uat, and master, I can checkout `dev` environment with no problems, but I can't checkout uat and master, both of which where created using the amplify console's connect branch button and was only added on my team provider using the command I mentioned.

**Comment by aprilmintacpineda** [comment]
I have just tried it now, it gives me the same error

![image](https://user-images.githubusercontent.com/21032419/91619097-bb151300-e9be-11ea-8770-177e5eb2206a.png)

but when I do `amplify env list`, it shows that I am now on master, but I'm not because the aws-exports actually hasn't changed, and how can I be when there was an error during checkout? `checkout dev` is successful with no problems

![image](https://user-images.githubusercontent.com/21032419/91619169-eb5cb180-e9be-11ea-94ed-5fafc74ff9fb.png)

**Comment by attilah** [comment]
@aprilmintacpineda Closing this issue as this seems to be a network related error on your machine at the time of the request. 169.* IP address indicates that your machine had an APIPA address, which means it did not get an IP address from your DHCP server.

**Comment by aprilmintacpineda** [comment]
Can't be sure about that as I am still encountering it now, but ONLY for this project, I have other projects and they seem to work pretty well.

![image](https://user-images.githubusercontent.com/21032419/91773294-0f1b3400-ec19-11ea-816c-c5fdf5974b47.png)
