### ISSUE TITLE
amplify rds over lambda resolvers 

### ISSUE THREAD

**Issue by rajababu3** [aws-amplify/amplify-cli#520]
**Which Category is your question related to?** 
Usage question
**What AWS Services are you utilizing?** 
AppSync with rds over lambda
**Provide additional details e.g. code snippets** 

My team is using cloudformation to create and connect with rds over lambda.
Some of the questions I have are: 

- Is there any way we can manage to pull all the resolvers and schema to local from appsync console.
-  Can we utilize amplify to write rds resolvers.
-  How we can utilize cloudformation to perform ci/cd for resolvers. 
    - Other ci/cd is managed with new multienv and working great as of now.

**Comment by rajababu3** [comment]
Thanks @kaustavghosh06 for this information. If you can let me know about timeline for the same, it will be of great help as my product is nearing production deployement. So that our team can plan accordingly.

**Comment by rayjanwilson** [comment]
excited for this feature

**Comment by rayjanwilson** [comment]
@kaustavghosh06 why did replying to this unassign you?

**Comment by blazestudios23** [comment]
I'm looking for a way to hook up an RDS from the amplify console. Please let me know when this will be possible.

**Comment by kaustavghosh06** [comment]
Hey guys, we do support custom resolvers and RDS as a part fo the GraphQL transformer as of today. Please checkout these links - https://aws-amplify.github.io/docs/cli/graphql#automatically-import-existing-datasources & https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model
