### ISSUE TITLE
2 auth modes problem

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#5200]
Hi,

It is a schema for a chat user. I want that the list of users is public (without private conversations).  Sorry to tell that but I think that multiple auth documentation is bad explained.

I do not understand why this does not work :
```graphql
schema {
   query: Query
}

type Query {
   listUsers(): [User]
   @aws_api_key
}

type User
@model(subscriptions: { level: public })
@key(name: "userByUsername", fields: ["username"], queryField: "userByUsername")
@aws_cognito_user_pools
@aws_api_key {
  id: ID!
  username: String!
  online: Boolean
  conversations: [Conversation]
  @connection(name: "UserConversations")
  @aws_cognito_user_pools
  createdAt: String
  updatedAt: String
}
```
This schema is rejected. And how to use that with Angular ?

**Comment by akshbhu** [comment]
Hi @rudyhadoux 

Can you tell what is the error you are getting when you said schema is rejected?

Also can you tell how did you setup your API so that I can reproduce this?

**Comment by rudyhadoux** [comment]
The schema failed after compilation.

I have an Api key and a Cognito user pool. And storage for other objects.

**Comment by akshbhu** [comment]
Hi @rudyhadoux 

You can change your Type Query to either remove arguments from the listUsers like below:

```graphql
type Query {
   listUsers: [User]
   @aws_api_key
}
```

or you can put some arguments in your query: 

```graphql
type Query {
   listUsers(id : ID!): [User]
   @aws_api_key
}
```

Let me know if this solve for issue.

**Comment by rudyhadoux** [comment]
I don't want to find a user(id) but only the public list of users.

I give you my whole schema and my Amplify configuration, so you can reproduce it and see bugs.

This schema below works and it is well compiled.

type User
@model(subscriptions: { level: public })
@key(name: "userByUsername", fields: ["username"], queryField: "userByUsername")
@aws_cognito_user_pools
@aws_api_key {
  id: ID!
  username: String!
  online: Boolean
  conversations: [Conversation]
  @connection(name: "UserConversations")
  @aws_cognito_user_pools
  createdAt: String
  updatedAt: String
}

type Conversation
@model(subscriptions: { level: public })
@auth(
  rules: [
    {
      allow: owner
      ownerField: "members"
      operations: [create, update, delete, read]
    }
  ]
) {
  id: ID!
  members: [String!]!
  user: User @connection(name: "UserConversations")
  messages: [Message] @connection(name: "ConversationMessages")
  createdAt: String
  updatedAt: String
}

type Message
@model(subscriptions: { level: public })
@auth(
  rules: [
    {
      allow: owner
      ownerField: "members"
      operations: [create, update, delete, read]
    }
  ]
) {
  id: ID
  members: [String!]!
  conversation: Conversation! @connection(name: "ConversationMessages")
  content: String
  bucket: String
  region: String
  key: String
  path: String
  vu: Boolean
  createdAt: String
  updatedAt: String
}

BUT if I add this, to set listUsers( ) public

type Query {
   listUsers(): [User]
   @aws_api_key
}

I have this error message. 
✖ An error occurred when pushing the resources to the cloud

Syntax Error: Expected Name, found )
An error occurred during the push operation: Syntax Error: Expected Name, found )
