### ISSUE TITLE
How can I connect pinpoint with cognito automatically?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5204]
Hello,

I am trying to create a lambda function that sends push notifications to a specific user id (rather than a campaign or anything like that). For doing that, I need the user id in the endpoint.

Here I see how to assign user ids to endpoints in 2 different ways:
https://docs.amplify.aws/sdk/analytics/endpoints/q/platform/ios#assigning-user-ids-to-endpoints
_“Manage user sign-up and sign-in with Amazon Cognito user pools.”
“Use the Amazon Pinpoint client to assign user IDs without using Amazon Cognito user pools.”_

I was successful with the second method, updating the endpoint manually with the user id at the end of the sign in or sign up sequence. But I don’t think this is the proper way if there is an automatic way.

Here Amazon says there is an automatic way, and looks like to me this is the proper way:
https://docs.aws.amazon.com/pinpoint/latest/developerguide/audience-define-user.html
_”If your application uses Amazon Cognito user pools to handle user authentication, Amazon Cognito can add user IDs and attributes to your endpoints automatically. For the endpoint user ID value, Amazon Cognito assigns the sub value that's assigned to the user in the user pool. To learn about adding users with Amazon Cognito, see Using amazon pinpoint analytics with amazon cognito user pools in the Amazon Cognito Developer Guide.”_

I am trying the first method, that also tracks sign in/up success/failure, which is good. But it is not working.

This is what I am doing:
I follow instructions here.
https://docs.amplify.aws/sdk/analytics/events/q/platform/ios#authentication-events
That is:
I update my awsconfiguration.json file, adding PinpointAppId  to the CognitoUserPool section. 
<img width="752" alt="Screenshot 2020-08-30 at 14 39 37" src="https://user-images.githubusercontent.com/738681/91660924-c22c4600-ead0-11ea-94b6-14d0a5a47eaf.png">

I also modify manually my congnito setup as explained here:
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html
to link cognito with pinpoint:
<img width="1912" alt="Screenshot 2020-08-30 at 13 26 14" src="https://user-images.githubusercontent.com/738681/91662128-459d6580-ead8-11ea-91d4-6b08fc92db8b.png">

but if I install the app again, login again, then it seems it is not working.
Pinpoint portal does not show sign up/in:
<img width="1914" alt="Screenshot 2020-08-30 at 13 28 41" src="https://user-images.githubusercontent.com/738681/91662134-4cc47380-ead8-11ea-9e82-a58bd9e94d0d.png">

And if I get the endpoint id in the client with:
`pinpoint.targetingClient.currentEndpointProfile().endpointId`
and I retrieve info of that endpoint id in a lambda function with:
`let data = await PINPOINT.getEndpoint(params).promise();`
this is what I see:
```
{
    "EndpointResponse": {
        "Address": "853fa4dec3a1dfb5fb2f66e25a8883f90a8d1501691xxxxxxxxxxxxxxxxxx",
        "ApplicationId": "3c2d2594890d4a358xxxxxxxxxxxx",
        "Attributes": {},
        "ChannelType": "APNS_SANDBOX",
        "CohortId": "43",
        "CreationDate": "2020-08-22T12:27:39.372Z",
        "Demographic": {
            "AppVersion": "1.0.0",
            "Locale": "en_GB",
            "Make": "apple",
            "Model": "iPhone",
            "Platform": "ios",
            "PlatformVersion": "13.5.1",
            "Timezone": "Europe/London"
        },
        "EffectiveDate": "2020-08-30T10:28:17.684Z",
        "EndpointStatus": "ACTIVE",
        "Id": "04896a60-1afc-4fd2-a274-xxxxxxxxxxx",
        "Location": {
            "Country": "GB"
        },
        "Metrics": {},
        "OptOut": "NONE",
        "RequestId": "7a7cb7e6-e360-433d-82db-xxxxxxxxxx"
    }
}
```
Nothing about User or user id, as you can see.

So, what is this not working? Do you see anything wrong? Any suggestion is welcome. Thanks.

Note: I am using passwordless login, I don’t know if that is related. I don’t think so.

EDIT: I realised that when I call "amplify push", this tool keeps removing the pinpoint value I added in the json configuration file. Perhaps this is related.

**Which Category is your question related to?**
Cognito and Pinpoint

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
Cognito and Pinpoint

**Provide additional details e.g. code snippets**
Above

**Comment by emiltorlen** [comment]
You can update the userId when you've logged in

eg

```javascript
import Amplify, { Analytics, Auth } from "aws-amplify";

Analytics.updateEndpoint({
        address: token,
        userId,
        channelType: Platform.OS === 'ios' ? 'APNS' : 'GCM',
        optOut: 'NONE'
})
```

**Comment by Ricardo1980** [comment]
@emiltorlen  Yes, I know that. In fact, I say in my question that I already tried that and it is working.
The problem with that solution is that you are not tracking sign up/sign in.
I want to do in using the proper way, using the way AWS documentation says, but, well, it is not working in my case.
I guess I am missing something.
Does anyone have any idea or suggestion?
Thanks a lot.

**Comment by emiltorlen** [comment]
Yes you're right, sorry about that. I see that you use APNS , IPhone requires the permissions in order to get a token at first. Not sure when you allow the permissions for notifications? 
Can you share some code of what you're doing at the moment?

Have you tried this on app launch?
```javascript
Amplify.configure({
  PushNotification: {
    requestIOSPermissions: false
  }
})
```

**Comment by Ricardo1980** [comment]
@emiltorlen Nope, it seems it is done automatically when you allow notifications.
My code is just this (after the login sequence):

```
            let user = AWSPinpointEndpointProfileUser()
            user.userId = loggedUser.userId.lowercased() // this is the user id from cognito

            let endpoint = self.pinpoint!.targetingClient.currentEndpointProfile()
            endpoint.user = user
            self.pinpoint!.targetingClient.update(endpoint)
```

**Comment by akshbhu** [comment]
Hi @Ricardo1980 

You can also post this on our discord community for quick responses : https://discord.com/channels/705853757799399426/717109738101407866

**Comment by Ricardo1980** [comment]
@akshbhu I did it a week ago, but no response. In fact, I am the only one asking questions in the analytics channel but no response.

**Comment by kaustavghosh06** [comment]
@Ricardo1980 Looks like you're manually creating these resources and not using the Amplify CLI. Which SDK/Library are you using on your client app?

**Comment by Ricardo1980** [comment]
@kaustavghosh06 No, I am using Amplify CLI to create analitycs (pinpoint) and auth (cognito).
The only manual thing I am doing is the 4 lambda functions for cognito because I activated (again, from amplify CLI) a custom auth flow. I don't know if that is related.
Do I try to reproduce the issue in a clean project?
What do you suggest?

**Comment by kaustavghosh06** [comment]
@Ricardo1980 were you able to figure out a solution for this?

**Comment by Ricardo1980** [comment]
@kaustavghosh06 I couldn't using the official way (integrating the 2 services properly).
What I do is that in the client, after the sign in process, manually I update the endpoint.
Not the best option but it is working.

I will try to this in a clean project and then open a bug.
