### ISSUE TITLE
Amplify Push error- Syntax Error: Invalid number, expected digit but got: "u".

### ISSUE THREAD

**Issue by kkbava** [aws-amplify/amplify-cli#5206]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
created vue application, "amplify init", "amplify add api" successful
edited generated default grahpsql schema in VSCode to this: (Did not edit any other part of the generated code)

type Todo @model {
  id: ID!
  long-url: AWSURL!
  short-url: String!
  created-at: AWSDateTime!
  used: Int!
}
amplify push gives this error:
Syntax Error: Invalid number, expected digit but got: "u".
See attached screenshot

**Amplify CLI Version**
4.27.3

**To Reproduce**
created vue application, "amplify init", "amplify add api" successful
edited generated default grahpsql schema in VSCode to this: (Did not edit any other part of the generated code)

type Todo @model {
  id: ID!
  long-url: AWSURL!
  short-url: String!
  created-at: AWSDateTime!
  used: Int!
}

**Expected behavior**
Not sure - was trying to mimic steps from the video at https://www.youtube.com/watch?v=SnqABG8e9Zk 

**Screenshots**

![Screenshot from 2020-08-31 12-03-59](https://user-images.githubusercontent.com/20571570/91689637-2824d600-eb82-11ea-8275-d673769a63e8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node Version: 14.9.0

**Additional context**
First experiment with amplify, vue, graphql, dynamodb - apologies if this is due to some mistake I did!
Tried to update API - that also gave an error
amplify update api gives same syntax error
![Screenshot from 2020-08-31 12-09-22](https://user-images.githubusercontent.com/20571570/91690045-e5afc900-eb82-11ea-95bb-25b6b98f0c6c.png)

**Comment by kkbava** [comment]
From the same laptop, tried the steps all over again.
1) vue create 2) amplify init 3) amplify add api 4) amplify push
everything worked fine. 
The difference - I did NOT edit the auto-generated graphql schema.
Guess the mistake was in the schema - will try to dig deeper

**Comment by kkbava** [comment]
guess I found out "my mistake" - "the culprit"
I get the error during amplify push, with a schema that read (notice hyphen in names)

> type kurl @model {
>   id: ID!
>   l-url: String!
>   s-url: String!
>   t-used: Integer!
> }

and the error disappears when I removed the hyphen

> type kurl @model {
>   id: ID!
>   lurl: String!
>   surl: String!
>   tused: Integer!
> }
> 

I'll wait for comments from others to know if this is a feature / limitation / defect - before I / you can close the issue.
I'll now go ahead and figure out how to use scalar types

**Comment by edwardfoyle** [comment]
The GraphQL spec does not allow hyphens (or any special characters besides underscore) in field names:
http://spec.graphql.org/June2018/#sec-Names

What failed during `amplify update api` with an Integer type in the schema?

**Comment by kkbava** [comment]
> The GraphQL spec does not allow hyphens (or any special characters besides underscore) in field names:
> http://spec.graphql.org/June2018/#sec-Names
Thanks for pointing out. 
Not to defend myself - but, a newbie doesnt start programming by reading specification. I didnt either - my bad.
I expect any error message to be actionable - it is in that area, I'd still complain - "syntax error: expected digit, but got "u" - didnt help. Cant still figure out where a "u" is. 
My learning with error messages has been that it should have 2 parts - tell the user what went wrong, and what he/she should do to correct it.
Hope we can improve the error message

> What failed during `amplify update api` with an Int type in the schema?
That was my mistake again - I typed "Integer!" 
Guess the amplify command exited on first error (hyphen) - never parsed this bit in 1st few runs.
I corrected it later to "Int!" and now, I'm friends with Amplify :)

once again, very happy to see an active community - I am a total newbie to the world of open source. 
And I promise I'll continue to make mistakes and ask for help :)

**Comment by edwardfoyle** [comment]
That error message comes from the graphql parsing library that we use so unfortunately there's not much we can do about it (I'm guessing the "u" it is referring to is the "u" after the dash in "l-url").

If you're new to GraphQL, I'd recommend going through this [getting started guide](https://graphql.org/learn/) to familiarize yourself with the syntax and functionality.

Also, you may be able to get better / faster help for general questions by joining our discord community: https://discord.gg/amplify

Welcome to the community!
