### ISSUE TITLE
Go function with amplify function build is wrong

### ISSUE THREAD

**Issue by sky4git** [aws-amplify/amplify-cli#5209]
**Which Category is your question related to?**
function

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
Lambda

**Provide additional details e.g. code snippets**
I have a two Lambda function in Go. I am developing on Windows PC.  When I use
`amplify function build` it create **main.exe** file in **/bin** folder of the Lambda function and **/dist** folder contains **latest-build.zip** with **main.exe** in it.

After this, when I use `amplify push --yes` command, it push my function to the cloud without any issue. 
But when I try to run the lambda function from the console, it always ends up with the following error.
`{
  "errorMessage": "fork/exec /var/task/main: no such file or directory",
  "errorType": "PathError"
}`

I assume when amplify function build command runs or amplify push happens, it should build the Go lambda function with GOOS=linux.  

Someone, please help to resolve this.
Thanks.

**Comment by akshbhu** [comment]
Thanks for reporting this. I am marking this as bug.

**Comment by sky4git** [comment]
FYI:
**amplify function build** is the issue. Local invoke is not an issue.  It is already creating windows .exe for when we build function.
 It should build with **GOOS=linux** on windows PC, so on lambda environment it can work with **amplify push --yes**.
