### ISSUE TITLE
Failing to rollback after "failed to satisfy constraint: Member must satisfy regular expression pattern"

### ISSUE THREAD

**Issue by aleksvidak** [aws-amplify/amplify-cli#5210]
**Describe the bug**
I have auth added to my Amplify project. I created a PostConfirmation function through amplify add function, then I assigned it through the Console to PostConfirmation trigger.

I wanted to adapt existing PostConfirmation function to add user to groups.

I have created user groups through amplify cli and made some manual changes to required templates according to what I saw is usually generated when **"add user to group"** through `amplify auth update`.

Doing amplify push resulted in the failure and from that point on I cannot make any change with amplify push. I have reverted local changes, but nothing helps. 

**Terminal logs**
UPDATE_FAILED UserPool AWS::Cognito::UserPool Mon Aug 31 2020 12:58:18 GMT+0200 (Central European Summer Time) 1 validation error detected: Value 'functionxxx395186PostConfirmationArn' at 'lambdaConfig.postConfirmation' **failed to satisfy constraint: Member must satisfy regular expression pattern**: arn:[\w+=/,.@-]+:[\w+=/,.@-]+:([\w+=/,.@-]*)?:[0-9]+:[\w+=/,.@-]+(:[\w+=/,.@-]+)?(:[\w+=/,.@-]+)? (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 2845964c-b320-4258-9d82-331c903daafe; Proxy: null)

UPDATE_FAILED AWS::CloudFormation::Stack Mon Aug 31 2020 12:58:29 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:us-east-1:358110627514:stack/amplify-xxx-dev-133524-authxxx395186-PWASSJLBA12B/7d118380-dc22-11ea-8d92-0a2f4587a347 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [UserPool].

**Amplify CLI Version**
4.27.3

**Expected behavior**
I would expect possibility to rollback.

**Desktop (please complete the following information):**
 - OS: Mac 10.15.6
 - Node Version: 12.16.2

**Comment by akshbhu** [comment]
Hi @aleksvidak 

It seems like a validation error in CFN in lambdafunctionARN. I think some manual changes you described might be the reason for this .One workaround you can try is ```amplify pull```. It will fetch the existing backend from the cloud which was previously pushed.You can also refer to the documentation : https://docs.amplify.aws/cli/teams/multi-frontend#workflow

Also can you tell me the steps of how you reached this error?

Let me know if workaround works for you?

**Comment by ttolvane** [comment]
For me pull didn't resolve the gridlock.
