### ISSUE TITLE
Nested query and mutation types in Graphql Transform not nesting correctly 

### ISSUE THREAD

**Issue by bmilesp** [aws-amplify/amplify-cli#5215]
**Describe the bug**

Used nested types for query and mutation in my schema.graphql file:
```
schema { 
  query: Query
  mutation: Mutation
}

type Query {
  asAdmin: AdminQuery
  @aws_auth(cognito_groups: ["Admin"])
  
  asTenant: TenantQuery
  @aws_auth(cognito_groups: ["Tenant"])

  asServiceArea: ServiceAreaQuery
  @aws_auth(cognito_groups: ["ServiceArea"])
}

type Mutation {
  asAdmin: AdminMutation
  @aws_auth(cognito_groups: ["Admin"])

  asTenant: TenantMutation
  @aws_auth(cognito_groups: ["Tenant"])

  asServiceArea: ServiceAreaMutation
  @aws_auth(cognito_groups: ["ServiceArea"])
}

type AdminQuery {
  getTenant(id: ID!): Tenant!
  getServiceArea(id: ID!): ServiceArea!
}

type TenantQuery {
  getMyProfile: Tenant!
  getMyServiceArea(id: ID!): ServiceArea!
}

type ServiceAreaQuery {
  getMyProfile: ServiceArea!
}

type AdminMutation {
  addTenant(name: String!): Tenant!
  addServiceArea(tenantId: ID!, name: String!): ServiceArea!
}

type TenantMutation {
  updateMyProfile(name: String!): Tenant!
  addServiceArea(name: String!): ServiceArea!
} 

type ServiceAreaMutation {
  updateMyProfile(name: String!): ServiceArea!
}

type Tenant @model {
  id: ID!
  name: String!
}

type ServiceArea @model {
  id: ID!
  name: String!
  tenantId: ID!
}
```

However, the nested query and mutation types under the asAdmin, asTenant, and asServiceArea definitions were additionally added to the Query and Mutation types, rendering the @aws_auth permissions useless as well as duplicated in error. The resolvers were also not attached to the nested types as expected, but rather attached to the erroneously duplicated query and mutation definitions.

**Amplify CLI Version**
4.28.0

**To Reproduce**

1. `amplify add api`
2. When prompted to edit the schema.graphql file, type 'Y' and paste the above schema code into the file and save it.
3. `amplify push`
 
**Expected behavior**
Properly attached resolvers to the nested query and mutation types (AdminQuery, TenantQuery, ServiceAreaQuery, AdminMutation,TenantMutation, and ServiceAreaMutation) as outlined in the schema above.

**Screenshots**
![image](https://user-images.githubusercontent.com/202549/91786192-0c96eb00-ebd5-11ea-811a-9845ca6703fe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version v12.16.1

**Additional context**
You can see in the Appsync console screenshot that the query and mutation types were "flattened" into the Query and Mutation types in error. However the correct schema was also added to their expected AdminQuery, TenantQuery, ServiceAreaQuery, AdminMutation,TenantMutation, and ServiceAreaMutation types but the resolvers were not attached, so it seems to have "almost" worked. You can see the AdminQuery and AdminMutation types were added to the schema correctly (and so were the other query and mutation types not illustrated) in this screenshot:

![image](https://user-images.githubusercontent.com/202549/91786444-a3fc3e00-ebd5-11ea-8ddb-7c15c7c380da.png)

**Comment by akshbhu** [comment]
Hi @bmilesp 

Amplify cli adds queries and mutation types for the input type having ```@model``` directive  and generates queries and mutation types based on other directives present in the model type i.e. ```@auth``` or ```@key```. 
In your schema it looks like you have added additional queries and mutations types to be protected.I think to support this case you need to add the custom resolvers for these types. Here is the example for this in our docs: https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

**Comment by bmilesp** [comment]
Hi akshbhu,

Thanks for clarifying. My greater goal was to have the @model directive to generate the query and mutation fields within different types other than the default Query and Mutation types. So for example would want the fields in createTenant, updateTenant, and deleteTenant within  the AdminMutation type.

After further thinking about this I realize it would most likely have to be granular functionality applied to the @model directive so I don't think that is currently possible?

Thanks again for your help.
-bp

**Comment by akshbhu** [comment]
Hi @bmilesp 

Yes. You can  always use custom resolvers for your case. I am closing this issue as it seems to have answered. If you face any more problems feel free to comment and I will reopen this issue again

**Comment by bmilesp** [comment]
Understandable.

Thanks again for your help, @akshbhu .
-bp
