### ISSUE TITLE
Error while running amplify pull in headless mode

### ISSUE THREAD

**Issue by fkoner** [aws-amplify/amplify-cli#5228]
**Describe the bug**
While executing the pull command using the headless configuration, the following error occurs:

```bash
2020-09-02T17:27:13.675Z [INFO]: TypeError: Cannot convert undefined or null to object
                                 at Function.assign (<anonymous>)
                                 at confirmFrameworkConfiguration (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/configuration-manager.js:102:12)
                                 at confirmConfiguration (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/configuration-manager.js:69:9)
```

**Amplify CLI Version**
**4.28.1**

**To Reproduce**
1. Export environment variables:
```shell
export REACTCONFIG={"SourceDir":"src","DistributionDir":"build","BuildCommand":"yarn run build","StartCommand":"yarn run start"}
export AWSCLOUDFORMATIONCONFIG={"configLevel":"project","useProfile":true,"profileName":"default"}
export AMPLIFY={"projectName":"headlessProjectName","appId":"xxxxxxxxxxxxxx","envName":"dev","defaultEditor":"code"}
export FRONTEND={"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"yarn run build","StartCommand":"yarn run start"}}
export PROVIDERS={"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}}
```
2. Run ampliy pull with exported variables:
```shell
amplify pull \
  --amplify $AMPLIFY \
  --frontend $FRONTEND \
  --providers $PROVIDERS \
  --yes
```

**Expected behavior**
Ensure that the amplify pull command is executed. For previous versions (e.g. version 4.28.0) it has worked correctly.

**Screenshots**
![amplify-issue](https://user-images.githubusercontent.com/2480544/92020035-25121d00-ed1d-11ea-83dd-290562cb8221.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu, MacOSX]
 - Node Version: 10.20.1 (local) 10.16.0 (amplify console)

**Additional context**
The script we are dealing with is very similar to this:
https://docs.amplify.aws/cli/usage/headless#sample-script-3

The bug appears both in our local environment and in the amplify console, it is related to the command line, and not a bug associated to the amplify console.

I don't know if something changed between version 4.28.0 and version 4.28.1, but with this patch we were presented with this error this morning.

If you require more detail I can share my headless script.

**Thanks in advance.**
***Paco***

**Comment by akshbhu** [comment]
Hi @fkoner 

Can you tell with which amplify version you are facing this error v4.28.0 or 4.28.1 or both?

**Comment by akshbhu** [comment]
Hi @fkoner 

I tried with the sample script and demo project and it is working fine for me. Can you elaborate more on following points:

- Is it working for you in version 4.28.0?
- Can you tell the details what resources you have added before so that I can repro this issue?

**Comment by cristhian-boc** [comment]
There is a bug on the CLI. We are getting the following error: `Unsupported javascript framework: react-native`. I can see that somebody changed the `framework-config-mapping.js` file. You are not returning the configs as in the past.

Before:
![image](https://user-images.githubusercontent.com/64980365/92033486-1f7afe00-ed42-11ea-9f12-b00b8c7a107a.png)

Current:
![image](https://user-images.githubusercontent.com/64980365/92033540-328dce00-ed42-11ea-91c2-398e6c422785.png)

And the `configuration-manager.js` file is trying to read the keys from that module.exports:
```
if (!Object.keys(frameworkConfigMapping).includes(inputParams.framework.toLowerCase())) {
      context.print.warning(`Unsupported javascript framework: ${inputParams.framework}`);
      inputParams.framework = 'none';
    }
```

So that is a breaking change, and maybe is the answer to solve this issue too.

We will use @4.26.0 in the meantime.

**Comment by fkoner** [comment]
@akshbhu 

I updated the issue, sorry, is not working in version **4.28.1**, in previous version **4.28.0** it works.

**Comment by akshbhu** [comment]
Yup , I have reproduced this . Thanks for your insights @cristhian-boc

**Comment by fkoner** [comment]
@akshbhu 
@cristhian-boc 
These commits

https://github.com/aws-amplify/amplify-cli/commit/5debb76bed86ab925becbcba85fd06347c0fa15a

https://github.com/aws-amplify/amplify-cli/commit/bb06162bdc9c9c567df4ae7f2a684bb6b586c6ab
