### ISSUE TITLE
amplify push overwrites awsmobile'saws-export.jst in SRC directory

### ISSUE THREAD

**Issue by askpatrickw** [aws-amplify/amplify-cli#523]
**Describe the bug**
If you add services with Amplify, it overwrites the aws-export.jst in your SRC directory.

**To Reproduce**
1. awsmobile init
2. awsmobile enable user-signin
TEST: type|cat aws-exports.jst
3. amplify init
4. amplify add storage
5. amplify push
TEST: type|cat aws-exports.jst
6. awsmobile pull will overwrite it again

**Expected behavior**
Your awsmobile config will still be in aws-exports.js

**Desktop (please complete the following information):**
 - OS: win10
 - Browser [e.g. chrome, safari]: N\A
    awsmobile 1.1.5 & 1.1.7 tested
    amplify 0.1.35

**Additional context**
1. The general guidance on all your documentation says to do this... Eek!
2. There is a backup of the awsmobile version in .\awsmobilejs\#current-backend-info but amplify only has the one in the SRC root.

**Comment by askpatrickw** [comment]
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/mobile-hub-aws-mobile-react-native.html

"The following content applies if you are already using the AWS Mobile CLI to configure your backend. If you are building a new mobile or web app, or you're adding cloud capabilities to your existing app, use the new AWS Amplify CLI instead. With the new Amplify CLI, you can use all of the features described in Announcing the AWS Amplify CLI toolchain, including AWS CloudFormation functionality that provides additional workflows."

Seems like this should say not to comingle and that Amplify should recognize you're using awsmobile and caution the developer they're about to make a mess. It would be easy enough to check for the presence of the awsmobile config folders.  Which to me (stomping on my config) is a horrible bug given the ease of the fix.

**Comment by UnleashedMind** [comment]
The Mobile Hub team has implemented the [The Mobile Hub Migrator](https://github.com/awslabs/amplify-mobilehub-migrator) that allows you to re-use your existing Mobile Hub resources with the Amplify CLI.

**Comment by askpatrickw** [comment]
I  just rebuilt using CLI. So I'm not going to have more input here and will close.
