### ISSUE TITLE
Tags on Existing projects

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#5230]
Is there a secret to creating tags on an existing project? I added the tags.json, and pushed - but nothing happened...I was expecting pretty much everything to be updated...

**Comment by ammarkarachi** [comment]
@GeorgeBellTMH You would need to add a file `amplify/backend/tags.json` in your existing project. For new projects the file should be auto generated. For more [info](https://docs.amplify.aws/cli/usage/tags)

**Comment by GeorgeBellTMH** [comment]
I followed the instructions, nothing happened...I would expect to see tags on the app-sync project, along with all the other resources...

**Comment by GeorgeBellTMH** [comment]
Wondering if this doesn't work if there are existing tags that were manually entered?
