### ISSUE TITLE
When sending a message using pinpoint, I don't see the returned object.

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5232]
When sending a message using pinpoint, I don't see the returned object.

I am writing a lambda that sends a message to an email. Like this:

```
try {
  let data = await PINPOINT.sendMessages(emailParams).promise();
  console.log('Success sending email: ' + data);
  //console.log("Email sent! Message ID: ", data['MessageResponse']['Result'][toAddress]['MessageId']);
} catch (error) {
  console.log('ERROR sending email: ' + error);
  throw error;
}
```

This is the documentation:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#sendMessages-property

If everything is setup properly, this is the log I see in cloud watch:
`2020-09-02T21:16:24.126Z	ff823a77-5fea-49a3-9a42-a7cxxxxxx	INFO	Success sending email: [object Object]
`

If I remove the proper permission in the cloud formation template (to force an error), then I see this, which seems OK to me:
`2020-09-02T21:09:42.678Z	c4cca3ad-1686-4277-a9d2-04ae37fa80bb	INFO	ERROR sending email: AccessDeniedException: User: arn:aws:sts::186370713xxxx:assumed-role/xxxxLambdaRole7c3ade49-dev/saveVisit-dev is not authorized to perform: mobiletargeting:SendMessages on resource: arn:aws:mobiletargeting:eu-west-1:186370xxxxxxx:apps/3c2d2594890d4a358d582eaxxxxxx/messages`

If I use a wrong sender email, then I see this, which is clearly wrong. I don't receive the email for that but an error is not triggered.
`2020-09-02T22:17:03.706Z	d6c16627-a51a-46ed-aa86-a91feae504a9	INFO	Success sending email: [object Object]
`

So, my questions are, why can't I see the result properly when there is a success (with something like DUPLICATE, PERMANENT_FAILURE, SUCCESSFUL... )?
My second question is, why I don't see an error when I use an invalid sender?

Thanks a lot.

**Which Category is your question related to?**
Pinpoint, Lambda and javascript

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
Pinpoint, Amplify CLI, Cloud Watch, Cloud Formation, Lambda

**Provide additional details e.g. code snippets**
Above

**Comment by akshbhu** [comment]
Hi @Ricardo1980 

This seems like a problem in pinpoint AWS SDK. You can try to post an issue on AWS forums for this or their GH page.

**Comment by Ricardo1980** [comment]
@akshbhu 
Done: https://forums.aws.amazon.com/thread.jspa?threadID=327333&tstart=0

BTW, can you help me with this?
When using asynchronous code in nodejs I see 3 ways:
callbacks
promises
async/await (and try/catch)

When using AWS I try to use the last one, for me it is easier to read the code.

However, in AWS documentation we only see info about callbacks,  for example:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#sendMessages-property
How is possible or what is the mechanism that allows me to use promises or async/await automatically when calling AWS  javascript API? I am curious. I haven't seen anything about that in AWS docs.

Last question, is there any workaround? What about if I wrap manually sendMessage callbacks inside a promise and then use async/await? (I am going to try that right now)

Thanks.

**Comment by Ricardo1980** [comment]
This is very strange. If I use callbacks instead of async/await, I get exactly the same result.
How is this possible?

Lambda:
```
  exports.handler =  function(event, context, callback) {

    // params setup here
  
    PINPOINT.sendMessages(emailParams, function(err, data) {
      // If something goes wrong, print an error message.
      if (err) {
        console.log('Error sending email' + err);
        callback(err);
  
      } else {
        console.log('Message sent 1: ' + data.MessageResponse.Result);
        console.log('Message sent 2: ' + data);
        callback(null, true);
      }
    });
  }
```

CloudWatch:

```
  2020-09-03T20:58:10.643Z	b35e143a-b675-4e6a-87e0-bc833746a5a3	INFO	Message sent 1: [object Object]
  2020-09-03T20:58:10.644Z	b35e143a-b675-4e6a-87e0-bc833746a5a3	INFO	Message sent 2: [object Object]
```

**Comment by akshbhu** [comment]
Hi @Ricardo1980 

> ```
> try {
>   let data = await PINPOINT.sendMessages(emailParams).promise();
>   console.log('Success sending email: ' + data);
>   //console.log("Email sent! Message ID: ", data['MessageResponse']['Result'][toAddress]['MessageId']);
> } catch (error) {
>   console.log('ERROR sending email: ' + error);
>   throw error;
> ```
I think your above code is also correct if you are calling inside an async function. 

Are these logs come up when you used wrong sender email just like earlier?

**Comment by Ricardo1980** [comment]
@akshbhu 
Nope, that's when everything works. In fact, I received an email.

If the sender is wrong, this is the log in cloudwatch. (I guess that in this case the error is in the response, not in the error, I don't know)

```
2020-09-03T21:46:53.154Z	af118b46-d285-45e6-8bf2-a4e0e7593dce	INFO	Message sent 1: [object Object]
2020-09-03T21:46:53.154Z	af118b46-d285-45e6-8bf2-a4e0e7593dce	INFO	Message sent 2: [object Object]
```

If I remove mobiletargeting:SendMessages permission, this is the log:

```
2020-09-03T21:53:38.137Z	0b596849-6d4a-4a3a-88ef-0ffde7d93d5b	INFO	Error sending emailAccessDeniedException: User: arn:aws:sts::1863707xxxxxx:assumed-role/bluishtestLambdaRole7c3ade49-dev/saveVisit-dev is not authorized to perform: mobiletargeting:SendMessages on resource: arn:aws:mobiletargeting:eu-west-1:186370713163:apps/3c2d2594890d4a358d582xxxxxxx/messages

{
    "errorType": "AccessDeniedException",
    "errorMessage": "User: arn:aws:sts::1863707xxxxxx:assumed-role/bluishtestLambdaRole7c3ade49-dev/saveVisit-dev is not authorized to perform: mobiletargeting:SendMessages on resource: arn:aws:mobiletargeting:eu-west-1:1863707xxxxxx:apps/3c2d2594890d4a358d582eaxxxxxxxx/messages",
    "code": "AccessDeniedException",
    "message": "User: arn:aws:sts::186370xxxxxx:assumed-role/bluishtestLambdaRole7c3ade49-dev/saveVisit-dev is not authorized to perform: mobiletargeting:SendMessages on resource: arn:aws:mobiletargeting:eu-west-1:18637xxxxxxx:apps/3c2d2594890d4a358d58xxxxxxxxx/messages",
    "time": "2020-09-03T21:53:38.136Z",
    "requestId": "516be112-8a54-479d-be42-01cb4d1f3664",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 36.1596889753107,
    "stack": [
        "AccessDeniedException: User: arn:aws:sts::186370xxxxx:assumed-role/bluishtestLambdaRole7c3ade49-dev/saveVisit-dev is not authorized to perform: mobiletargeting:SendMessages on resource: arn:aws:mobiletargeting:eu-west-1:1863707xxxxx:apps/3c2d2594890d4a358d58xxxxxxxxx/messages",
        "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}
```

And if I modify the function trying to access the response according AWS docs (and proper sender and permissions), this is the log:

```
  PINPOINT.sendMessages(emailParams, function(err, data) {
    // If something goes wrong, print an error message.
    if (err) {
      console.log('Error sending email' + err);
      callback(err);

    } else {
      //console.log('Message sent 1: ' + data.MessageResponse.Result);
      console.log('Message sent: ' + data);

      console.log("DeliveryStatus: " + data['MessageResponse']['Result'][toAddress]['DeliveryStatus']);

      callback(null, true);
    }
  });
```

```
2020-09-03T22:24:09.357Z	65ae45bd-ba80-45a7-a014-67b360c5f800	INFO	Message sent: [object Object]
2020-09-03T22:24:09.414Z	65ae45bd-ba80-45a7-a014-67b360c5f800	INFO	DeliveryStatus: SUCCESSFUL
```

which is "more or less" working.
Perhaps the problem is that the response is too big so cloudwatch cannot present it, only a specific field. 
Is that possible?

Thanks.

**Comment by Ricardo1980** [comment]
OK, I am an idiot, I should have used this:
console.log('Success sendMessages\n' + JSON.stringify(data, null, 2));
rather than 
console.log('Message sent: ' + data);

**Comment by akshbhu** [comment]
Hi @Ricardo1980 

Good to know that you resolved it. I am closing this issue for now. If you face any more problems, feel free to comment and I will reopen this again.

**Comment by personapp** [comment]
if there is an error on the callback I can console.log but not the successful response. Please help.
