### ISSUE TITLE
Access Lambda function via API Gateway

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5236]
**Which Category is your question related to?**

amplify update function

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

Function

**Provide additional details e.g. code snippets**

Is it possible to update an existing lambda function and add API Gateway? I need to access the function from another Vue app and from my understanding I'll need to add API Gateway to accomplish this.

**Comment by akshbhu** [comment]
Hi @christodupreez 

Did you create your existing lambda function using amplify cli?
If yes , then you can do is ```amplify add api``` and select your existing lambda function option to attach with API gateway.Here is the documentation for this : https://docs.amplify.aws/cli/restapi#rest-endpoint-that-triggers-existing-lambda-functions

Let me know if this answers your question.

**Comment by christodupreez** [comment]
Thank you @akshbhu

**Comment by christodupreez** [comment]
I have added the api using `amplify add api`, how would I enable CORS using Amplify CLI?

I get cors errors trying to access my new api:

`Access to XMLHttpRequest at 'https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/dev/status?id=1234567890' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.`

My code:

```
const apiName = "myapiname";
const path = "/status";
const myInit = {
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers":
      "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent"
  }, 
  response: true, 
  queryStringParameters: {
    id: "1234567890"
  }
};

API.get(apiName, path, myInit)
  .then(response => {
    Vue.$log.info(apiName, response);
  })
  .catch(error => {
    Vue.$log.error(apiName, error);
  });
```
