### ISSUE TITLE
How can I completely delete a function from my cloud resources?  

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5238]
**Which Category is your question related to?**

amplify remove function

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

Function

**Provide additional details e.g. code snippets**

Would the following delete the function from my cloud resources? 

amplify remove function
amplify push

**Comment by jhockett** [comment]
> Would the following delete the function from my cloud resources?
> 
> amplify remove function
> amplify push

That should do it.
