### ISSUE TITLE
amplify does not honor dependencies already setup with awsmobile

### ISSUE THREAD

**Issue by askpatrickw** [aws-amplify/amplify-cli#524]
**Describe the bug**
If you add a service using amplify which has dependencies it will add them, even if they have already been setup previously with awsmobile.

**To Reproduce**
1. awsmobile init
2. awsmobile enable user-signin
You now have a Cognito User Pool
3. amplify init
4. amplify add storage
You will be prompted to add Auth. No way to choose an existing Pool.
5. amplify push
You now have another User Pool and an overwritten aws-export.js see
#523 

**Expected behavior**
One User Pool

**Additional context**
The Amplify docs say to add new services with amplify to your existing mobile hub projects.

**Comment by UnleashedMind** [comment]
The amplify-cli and the awsmobile-cli  are not compatible with each other, and not designed to be used together. They do replace each other's contents in the aws-export.js file, which is used by the amplify library. 
For more information of the amplify cli, check [AWS Amplify CLI toolchain](https://aws.amazon.com/blogs/mobile/announcing-the-aws-amplify-cli-toolchain/)
I'm not sure where you find the instruction "to add new services with amplify to your existing mobile hub projects", could you please provide a link so we can check and make sure its contents are accurate.

**Comment by askpatrickw** [comment]
Same comment as here: https://github.com/aws-amplify/amplify-cli/issues/523#issuecomment-443381144

**Comment by kaustavghosh06** [comment]
@askpatrickw The Amplify CLI and awsmobile CLI are completely different products which have seperate underlying philiosopies. I wouldn't recommend using them on the same project. You should either use Amplify CLI or the Awsmobile CLI.

**Comment by kaustavghosh06** [comment]
Tracking this further in #523
