### ISSUE TITLE
Duplicate API auth provider after api update

### ISSUE THREAD

**Issue by 11csive** [aws-amplify/amplify-cli#5240]
**Describe the bug**
Changing an additional auth type to be the default auth type, causes it to be set as both default and additional, if selecting 'No" to 'Configure additional auth types?' when running api update.

**Amplify CLI Version**
4.28.2

**To Reproduce**
```
amplify add api
? Please select from one of the below mentioned services: **GraphQL**
? Provide API name: **amplifybugtest**
? Choose the default authorization type for the API **API key**
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): **7**
? Do you want to configure advanced settings for the GraphQL API **Yes, I want to make some additional changes.**
? Configure additional auth types? **Yes**
? Choose the additional authorization types you want to configure for the API **IAM**
? Configure conflict detection? **No**
? Do you have an annotated GraphQL schema? **No**
? Choose a schema template: **Single object with fields (e.g., “Todo” with ID, name, description)**

amplify update api
? Please select from one of the below mentioned services: **GraphQL**
? Select from the options below **Update auth settings**
? Choose the default authorization type for the API **IAM**
? Configure additional auth types? **No**
```

The authConfig in amplify-meta.json now look like this:
```
"authConfig": {
  "defaultAuthentication": {
    "authenticationType": "AWS_IAM"
  },
  "additionalAuthenticationProviders": [
    {
      "authenticationType": "AWS_IAM"
    }
  ]
}
```

And 'amplify push' results in:
`The following resource(s) failed to create: [GraphQLAPI]`
`Authentication type AWS_IAM for additional authentication provider 1 already specified on the API. It can only be specified once. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException;`

**Expected behavior**
AWS_IAM authentication type to be removed from additionalAuthenticationProviders 

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.9.0

**Comment by akshbhu** [comment]
Hi @11csive 

Thanks for reporting this. I have reproduced it.
