### ISSUE TITLE
No such resource AWS::Transfer::Server

### ISSUE THREAD

**Issue by flyck** [aws-amplify/amplify-cli#5243]
**Describe the bug**
It is not possible to create a CloudFormation Output for the resource `AWS::Transfer::Server`. Essentially the same as in https://github.com/aws-amplify/amplify-cli/issues/3339 but here with an `AWS::Transfer::Server` resource.

**Amplify CLI Version**
4.28.2

**To Reproduce**
* The same steps as in issue https://github.com/aws-amplify/amplify-cli/issues/3339 but with an AWS Transfer Server and an Output referencing it.
```
  "Outputs": {
    "ServerId": {
      "Value": { "Fn::GetAtt": ["TransferServer", "ServerId"]  },
    }
  }
```
* `amplify push`
```
Invalid CloudFormation template: .../template.json
✖ An error occurred when pushing the resources to the cloud

No such resource AWS::Transfer::Server
An error occurred during the push operation: No such resource AWS::Transfer::Server
```

**Expected behavior**
No failure at all but a successful push, since the CloudFormation is valid.

Desktop:
* Mac: 10.14.6
* Node Version: v14.1.0

**Comment by UnleashedMind** [comment]
Reproduced the issue.
The Amplify CLI uses "cfn-lint" to validate the Cloudformation template file.
In this particular case, there is an issue with its validation.

**Comment by kaustavghosh06** [comment]
"cfn-lint" is not a blocking error now and we've made this a warning. You should be able to deploy this with the latest version of the CLI.
Please let us know if you're still hitting this blocker.
