### ISSUE TITLE
Code generated models have no space between fields in toString

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-cli#5245]
Currently the code generated toString method for models used in DataStore/API has no space between fields so it looks like this:

`Post {id=d80cc4c7-70bd-4a8d-a843-664327c621dbtitle=Intro to DataStorerating=nullcontent=nullowner=null}`

Update the generated toString method to put a space between the different fields.

**Comment by akshbhu** [comment]
Hi @TrekSoft 

Thanks you for reporting this. Can you provide more context on this for ex. what amplify commands you used that generated this error?

**Comment by TrekSoft** [comment]
It's not an error. It's just that if you follow the [default getting started guide for Android Datastore](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/android), the models it generates have a toString method which is missing spaces between the fields.

Basically the `amplify codegen models` command in the CLI for the Android platform will always produce code generated Java classes with this toString method missing spaces.

**Comment by richardmcclellan** [comment]
@TrekSoft this sounds like a duplicate of https://github.com/aws-amplify/amplify-android/issues/555, which was fixed in https://github.com/aws-amplify/amplify-cli/pull/4463.  Are you using the latest version of the CLI?

**Comment by TrekSoft** [comment]
Thanks - I thought I was but I can double check that.

**Comment by TrekSoft** [comment]
Just confirmed that it did
