### ISSUE TITLE
Add Storage for multi env is creating different names

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#5247]
when adding storage and using multi envs it is creating different buckets but within the end a kind of random number. This is not helpful when you want to set the "arn:aws:s3:::bucket........160007-${env}/*", policy.
Now I have to add two buckets to the policy which grants dev access to prod and vice versa. 

bucket55217-master
bucket60007-develop

**Before is was just**

bucket-master
bucket-develop

then I was able to just add this policy:
"arn:aws:s3:::bucket-${env}/*"

I am using AWS Amplify CLI 4.28.2

**Comment by akshbhu** [comment]
Hi @rpostulart 

The random number  is added from the stack name to make the S3  buckets  name unique as these buckets are global. If the Id is removed , this might get ```bucket already exists``` error. I think for this you have to add the bucket names manually for the IAM policies.

**Comment by rpostulart** [comment]
Yeah of course! I have also noticed that this variable is available so I can set access:

"STORAGE_1234_BUCKETNAME": {
	"Ref": "storage1234BucketName"
}
