### ISSUE TITLE
Amplify Console does not correctly open the console

### ISSUE THREAD

**Issue by UnleashedMind** [aws-amplify/amplify-cli#5248]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Typing "amplify console" in the CLI only takes me to the right place in the AWS management console if I am in the exact region and logged in with the correct user. 

This can be confusing to new users of AWS if they changed the region they fill find that there are no projects inside the amplify service and that might take a lot of time to figure out what was the problem. 

It would be good that when someone types "amplify console" they are taken to the right place, if they are not sign in in the right user they can be requested the credentials and then taken to the right region  in their amplify console. 

**Amplify CLI Version**
4.29.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by akshbhu** [comment]
Thanks for reporting this!!.
