### ISSUE TITLE
I have added the api using `amplify add api`, how would I enable CORS using Amplify CLI?

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5252]
I have added the api using `amplify add api`, how would I enable CORS using Amplify CLI?

I get cors errors trying to access my new api:

`Access to XMLHttpRequest at 'https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/dev/status?id=1234567890' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.`

My code:

```
const apiName = "myapiname";
const path = "/status";
const myInit = {
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers":
      "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent"
  }, 
  response: true, 
  queryStringParameters: {
    id: "1234567890"
  }
};

API.get(apiName, path, myInit)
  .then(response => {
    Vue.$log.info(apiName, response);
  })
  .catch(error => {
    Vue.$log.error(apiName, error);
  });
```

I have read [https://github.com/aws-amplify/amplify-cli/issues/5183](https://github.com/aws-amplify/amplify-cli/issues/5183) and tried to enable cors manually as suggested, but I'm still getting the same error.

_Originally posted by @christodupreez in https://github.com/aws-amplify/amplify-cli/issues/5236#issuecomment-687057830_

**Comment by nikhname** [comment]
Enabling CORS using the CLI is an enhancement thats under review in #5183, closing this as a duplicate.
