### ISSUE TITLE
Case insensitive ModelStringFilterInput?

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#526]
**Is your feature request related to a problem? Please describe.**
Need to filter on strings but in a case insensitive-way. 

**Describe the solution you'd like**
ModelStringFilterInput should have a case insensitive comparison option. 

**Describe alternatives you've considered**
I understand this limitation is because Dynamo does not support case insensitive string comparison. It seems the solution is either to force all strings in the db to be lowercase, or to use elastic search through the @searchable operator. The problem with @searchable operator is it does not affect ModelStringFilterInput, it just provides one resolver (searchBla()), and defines its own SearchableFilterInputs and leaves ModelFilterInputs alone. If @searchable is enabled why not then switch out ModelFilterInputs with this SearchableFilterInput that does support case insensitivity through elastic search?  

One option which might be the simplest, is to build a custom @lowercase graphql transformer that can be applied to string field to force them to be stored in db as lowercase for easy string comparison. Then frontend can manipulate accordingly. 

**Additional context**
None.

**Comment by hisham** [comment]
https://medium.com/open-graphql/implementing-search-in-graphql-11d5f71f179 discusses search in AppSync and how to deal with case insensitivity. They have the graphql resolver create a lowercase searchField which is a concatenation of the attributes they want to search.

**Comment by hisham** [comment]
Yes I'm basically doing things on the client for now. However shouldn't we put that logic in the backend instead of client? It feels weird to rely on the client to store transformed properties. But I guess that's the easiest thing for now.

**Comment by hisham** [comment]
Also client solution does not deal with old data that do not have that search term. Need to backfill that data somehow. For now the data set is so small that I'm doing the filtering on the client side. So I'm good for now and will revisit this once my data set is larger.

**Comment by kaustavghosh06** [comment]
@hisham  Do you think we can close this issue and that you're unblocked?

**Comment by hisham** [comment]
Yeah there's enough workarounds for now. I just wished case insensitive comparison was handled out of the box without having to think about it. But yes I personally am unblocked for now.
