### ISSUE TITLE
 InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by kenbankspeng** [aws-amplify/amplify-cli#5267]
**Describe the bug**
Stretching things a bit to call this a bug, but this is where I'm at.

After I unwisely deleted the Iam User that was associated with Amplify credentials, my amplify commands stopped working. I was able to recover by running `amplify configure`, `amplify init` (existing environment: Yes), and `amplify pull`. Now my Amplify is associated with the new Iam User credentials, and things work as expected.

But if I go back to any previous backend configuration stored in git, my Amplify seems to get some re-association with the old credentials (although ~./aws still has the new credentials), such that any Amplify command, including `amplify init` and `amplify pull` fails with the following error:

UnhandledPromiseRejectionWarning: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at Request.extractError (/usr/local/nvm/versions/node/v14.9.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:837:35)...

**Amplify CLI Version**
4.29.0

**To Reproduce**
Described above.

**Expected behavior**
No error.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.9.0

**Additional context**

**Comment by mayckonx** [comment]
same problem here

**Comment by akshbhu** [comment]
Hi @mayckonx 

Can you check file ```local-aws-info.json``` present in .config folder under amplify folder and check if the profileName is same as the profile you newly created?
 If its different,  you can do is run ```amplify configure project``` and  select the correct ```aws-profile``` in the workflow.

Let me know if this works for you?

**Comment by mayckonx** [comment]
Hi @akshbhu, thanks for the tips. It worked for me!

**Comment by mikeRChambers610** [comment]
For me I just needed to run amplify configure again. Once I did that just generated a new access key and secret access key in IAM and was able to get the error resolved. Similar to the comment above.
