### ISSUE TITLE
DNS management (+ ACM) from CLI for static hosting

### ISSUE THREAD

**Issue by ncknuna** [aws-amplify/amplify-cli#527]
**Is your feature request related to a problem? Please describe.**
I'd love it if Amplify could fully manage the deployment of a new static site for me, but currently there are manual steps to set up the DNS routes via the console.

**Describe the solution you'd like**
Support for managing domains from the CLI, with automation around generating certs from ACM (or Let's Encrypt)

**Describe alternatives you've considered**
Could pull in an additional tool like Cloudformation or Terraform to do this, but would rather not :)

**Additional context**
Other tools like `apex up` or `zeit now` support this, so I know it's possible and something that other people have thought is a good idea :)

**Comment by kaustavghosh06** [comment]
@ncknuna Please take a look at the AWS Amplify Console documentation -> https://aws.amazon.com/amplify/console/ which got launched at re:Invent this year. 
This service should take care of your above-mentioned requests. Please feel free to re-open this issue if you've further questions.

**Comment by ncknuna** [comment]
@kaustavghosh06 , while the console is awesome, I would like to have a way to do this from the CLI (for ease of automated scripting), so I'd appreciate if this issue could be reopened. Thanks!

**Comment by kaustavghosh06** [comment]
@ncknuna Re-opened the issue.

**Comment by ykethan** [comment]
CLI currently supports this feature now.
