### ISSUE TITLE
how to manually delete corrupted environment

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-cli#5270]
hi, i have a few environments that i created, using different IAM users. i then deleted some of my users (i don't know which were used with which environment).

when i try and delete an environment, it indicates that is deleting backend but seems to be in a loop as it runs but nothing happens, so after about 15 minutes i stopped it.

i then deleted the associated cognito and identity pools as well as dynamodb table. then when i run amplify delete, i get this error message:

/ Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:dev
× Project delete failed
Cannot read property 'message' of null

how can i now delete the resources related to this environment?

thanks

**Comment by nikhname** [comment]
@kannieWeesNie did you try running ```amplify env remove dev```

**Comment by kannieWeesNie** [comment]
@nikhname thanks. tried to do that now but get:

"You cannot delete your current environment. Please switch to another environment to delete your current environment
If this is your only environment you can use the 'amplify delete' command to delete your project" 

- it is my only environment so have to run amplify delete  -  then get:

"Error in deleting env:dev
× Project delete failed
Cannot read property 'message' of null
TypeError: Cannot read property 'message' of null"

**Comment by berenddeboer** [comment]
The error message is probably related to some amplify update, try doing `amplify function update` or `amplify api update`, that probably adds some missing parameters to some json files.

But `amplify delete` is drastic, you can also try to simply create a new environment, switch to that, then delete the old.

**Comment by kaustavghosh06** [comment]
@kannieWeesNie Are you still stuck on this issue? Did you get a chance to visit your CloudFormation AWS Console and see what's going on with your stack?

**Comment by kannieWeesNie** [comment]
@kaustavghosh06 Thanks for the help. I gave up as I was spending too much time on the problem. When I have some spare time I will revisit the issue and see if I can determine what's happening.

**Comment by kaustavghosh06** [comment]
Okay, please let us know if you need further help. Closing this issue for now.
