### ISSUE TITLE
CLI says it's not avaiable in a region, but I can use it via console

### ISSUE THREAD

**Issue by Eduardogbg** [aws-amplify/amplify-cli#5271]
**Describe the bug**
If I `amplify init` a project with a sa-east-1 profile, it will work. I'll be able to add apis, authentication and etc. However, when I try to `amplify add hosting` it will yield a "Missing required key 'appId' in params" error. Then if I try to `amplify init --appId` with an Amplify app id that I already created via console in the region, it will say "Amplify service is not available in the region sa-east-1
init failed".

That doesn't make any sense, considering that I just created an app via the console, and all the features are available using it (for example, I can create a fullstack amplify app clicking the quick start examples).

**Amplify CLI Version**
4.29.0

**To Reproduce**
Try to `amplify init --appId` with an app id in sa-east-1

**Expected behavior**
To work, since I can do all the amplify cli things via the console, I expected them to work via cli.

**Comment by akshbhu** [comment]
Hi @Eduardogbg 

 As the appId you created via console is in region ```sa-east-1``` and amplify-cli doesn't support the region for amplify service ,thats why you are facing this issue.
I have mark this as enhancement and pending-review to get this prioritized.

**Comment by vargascookbook** [comment]
Hi ALL! Any news about this issue? We really need to use São Paulo through the CLI! Thank you!!

**Comment by nicolas-carlini** [comment]
Hi! Any news about this issue?

**Comment by mgrazianoc** [comment]
Kind of disapointing to know about that on CLI.

**Comment by j1nma** [comment]
It has been 2021 already...

**Comment by vargascookbook** [comment]
.. and the radio still silent here in São Paulo!

**Comment by thiagoalves** [comment]
@akshbhu @renebrandel Any news? Is there any way to circumvent this meanwhile?

**Comment by thiagoalves** [comment]
I manually edited `/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/aws-regions.js` and voilà... it worked!

**Comment by ZehCoque** [comment]
Let's not let this thread be forgotten!! We need the sa-east-1 to be as native as possible with amplify!
