### ISSUE TITLE
Push removing required keys from Lambda Layers in nested-cloudformation-stack.yml

### ISSUE THREAD

**Issue by naldertown** [aws-amplify/amplify-cli#5273]
**Describe the bug**
Having previously used lambda layers when released we upgraded to version 4.29.0 to take advantage of the multi-env support. We have recreated our existing layers and removed the old ones from the Amplify project 
The layers are allocated to Lambda functions within the project using the `amplify update function` command. 
All was working fine yesterday evening with the stack pushing as expected to the cloud. This morning I ran another `ampify push -y` following an `amplify init` and now the stack is not picking up the s3Key and deploymentBucketName from two of the three layers and is failing with the errors below:

`UPDATE_FAILED      functionRTRalphaClient                          AWS::CloudFormation::Stack Tue Sep 08 2020 09:49:21 GMT+0100 (British Summer Time) Parameters: [s3Key, deploymentBucketName] must have values`

`UPDATE_FAILED      functionRTRappsyncClient                        AWS::CloudFormation::Stack Tue Sep 08 2020 09:49:21 GMT+0100 (British Summer Time) Parameters: [s3Key, deploymentBucketName] must have values`

**Amplify CLI Version**
4.29.0

**To Reproduce**
Set up Lambda layers, allocate them to functions and then run `amplify push -y`.

**Expected behavior**
The stack should not lose these keys and should deploy the layers/functions as expected.

**Screenshots**
Two unhealthy layers in nested-cloudformation-stack.yml shown below:

![image](https://user-images.githubusercontent.com/14090898/92455682-e6b3ac80-f1b9-11ea-81a6-4ff7ea4604fb.png)

Healthy layer in same stack shown below:

![image](https://user-images.githubusercontent.com/14090898/92455792-05b23e80-f1ba-11ea-880e-0e3610ec04b6.png)

You can see from these screenshots that indeed the s3Key and deploymentBucketName are missing. Manually adding them in is of course overwritten by the push command.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.18.3

**Additional context**
We have some custom resources in the Amplify project (5 SQS queues).
backend-config.json seems to be intact.

**Comment by slatemates** [comment]
similar issue after multiple updates to layers , we same error occurs .

**Comment by naldertown** [comment]
Update on this. After looking through _team-provider-info.json_ I noticed that the keys relating to the layers had been removed from in there. Adding them back in resolved this issue. I still don't understand why amplify cli removed them, but at least we can continue development.

Still seems like a bug that needs to be resolved - but this is a manual workaround for now @slatemates .

**Comment by slatemates** [comment]
yes thanks @naldertown

**Comment by MontoyaAndres** [comment]
any updates?

**Comment by MontoyaAndres** [comment]
@naldertown thanks! Hope a fix soon of this :/

**Comment by MontoyaAndres** [comment]
Update: when you execute `amplify env checkout BRANCH` those params were deleted as well... The version I'm using is `4.29.3`

**Comment by jemucino** [comment]
I'm seeing the same issue on 4.29.5.

**Comment by jamesone** [comment]
I can confirm: https://github.com/aws-amplify/amplify-cli/issues/5273#issuecomment-689086581 - This worked for me.

**Comment by naldertown** [comment]
Any potential update on this from the Amplify CLI team? It's getting to be a real pain to have to discard or pick through changes to team-providers on each init/env checkout.

**Comment by ammarkarachi** [comment]
It looks like the issue was with the commit https://github.com/aws-amplify/amplify-cli/commit/239deaa8f2074046d671b2192d4bdc4f74b5d2d4. Comment if you are still facing this issue

**Comment by PeteDuncanson** [comment]
@ammarkarachi I've been hit with this one today but for a S3 trigger. Currently stopping me doing a push and I don't know what my ``team-provider-info.json`` file is meant to have in it to get it working again. 

Tried all the usual stuff (``amplify init`` and ``amplify pull --restore`` and the fuller version of the pull with environment ID that you can get from the Amplify console) and then I noticed that there was a new version out of the CLI. As a last ditched effort I installed that and did a fresh ``amplify pull`` and that fixed it! My ``team-provider-info.json`` file got updated and all was good again.

Hope that helps someone else for the hopefully brief window when this might cause issues.

**Comment by iuyt9003** [comment]
Look here, the team provider was updated with the S3Key and deploymentBucketName

amplify init -> amplify restore ( will update the team-provider-info.json) and the missing params (Must have values)
will be retrieved and it should do the work 
much thanks for the @PeteDuncanson Job!

![image](https://user-images.githubusercontent.com/23431551/107626827-04080d80-6c67-11eb-8f4e-4cea321269de.png)

![image](https://user-images.githubusercontent.com/23431551/107626593-b4c1dd00-6c66-11eb-9896-1b1b73de9b13.png)

**Comment by Creskendoll** [comment]
Following @PeteDuncanson's comment, I did a `amplify pull --restore` and that fixed it for me.

**Comment by jgroom33** [comment]
I did the following manually to align the project with what the new standard seems to be:
1. foo-cloudformation-template.json
```jsonc
{
//
  "Parameters": {
//
    "deploymentBucketName": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
//
  "Resources": { "LambdaFunction": { "Properties": { "Code": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
//
```

2. update team-provider-info.json
```jsonc
{
  "dev": { "categories": { "function": {
        "foo": {
          "deploymentBucketName": "amplify-bar-dev-xxxxx-deployment",  // where xxxxx can be obtained from S3 console
          "s3Key": "amplify-builds/foo-yyyyyy-build.zip" // where yyyyy seems to be arbitrary and also seems it can be the same across environments
        },
```

**Comment by gruckionvit** [comment]
A mixture of new init's `amplify pull --restore` and remembering that you need to init someone else's environment on your machine before you can use it because the `local-aws-info.json` which is hidden from git needs to update.
