### ISSUE TITLE
Setting up aliases and case sensitivity when using the Amplify CLI

### ISSUE THREAD

**Issue by yegow** [aws-amplify/amplify-cli#5274]
**Which Category is your question related to?**
Amplify Authentication

**Amplify CLI Version** 
4.27.0

**What AWS Services are you utilizing?**
Cognito, S3, Lambda

**Provide additional details e.g. code snippets**
I have been trying to figure out how I can configure aliases and username case sensitivity when setting up auth using `amplify add auth`. When using the manual configuration, I can edit these however I like but this limits me from using the CLI capabilities and therefore can use the `AdminQueries` API. On the other hand, if I use the CLI, I can't seem to find a place where it asks me about aliases or name case sensitivity (I would like my users to sign in with usernames and emails and also have case insensitivity on usernames). Any help on this would be highly appreciated.

**Comment by SwaySway** [comment]
We currently have a feature request open for this. For further updates on this please follow
https://github.com/aws-amplify/amplify-cli/issues/3494

**Comment by yegow** [comment]
I have had a look at the issue you referenced and there is still no mention
of aliases.
Regards,
Yego
