### ISSUE TITLE
Nodejs layer and amplify pull problem

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#5276]
**Describe the bug**
When amplify pull a layer with node_modules that generates symlink in node_modules/.bin with windows/macos developer setup, there is a problem with the files for symlink (/ \ problem).

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.29.0 (also with earlier version)

**To Reproduce**
1. Add a library that generated a .bin file inside the node_modules folder (handlebars for example). 
2. Amplify Push from windows setup
3. Amplify Pull from macos setup
4. Error with symlink

**Expected behavior**
As the other functions, I expect that amplify doesn't push the node_modules folder to the S3 zip file for layers so we can avoid the problem.

**Comment by blazinaj** [comment]
👍

**Comment by blazinaj** [comment]
Have you found any way to work around this? I can no longer checkout my environments due to this error. 

I keep getting this error in regards to the `.temp` folder that gets generated during a pull operation. 

```
✖ There was an error initializing your environment.
EEXIST: file already exists, symlink '../acorn/bin/acorn' -> '/home/ec2-user/environment/project-root/amplify/.temp/#current-cloud-backend/function/graphqlfunctions/lib/nodejs/node_modules/.bin/acorn'
```

I made the mistake of trying to use the Amplify CLI Layer functionality. Published a layer called `graphqlfunctions`, since we have multi-env setup it caused a bunch of issues, and now I can't delete the layer and get this error whenever I try to do anything in the CLI

**Comment by SebSchwartz** [comment]
Yes, we downloaded the .zip file from the s3 deployment bucket, removed the .bin folder il all node_modules (even in subfolder). Zip all the files again, upload to S3 then we were able to do stuffs with CLI.
Now, we are installing dependencies in this folder with `yarn --no-bin-links` to avoid this error again.

But as I said in the issue, they should be ignored as the other's normal functions.

**Comment by ammarkarachi** [comment]
@SebSchwartz I tried pushing(windows) and then pulling(Mac) using 4.29.7. I don't see that error can you confirm 4.29.7?

**Comment by ammarkarachi** [comment]
I can't see the issue occurring using push on windows and pull on mac but I do see the `.bin` folder marking it as a bug

**Comment by ammarkarachi** [comment]
@SebSchwartz @blazinaj We updated our zipping packages and this bug has been resolved, don't face to re-open if you still face this issue.
