### ISSUE TITLE
Layer name/version with multiple env in the same aws account

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#5277]
**Describe the bug**
We are on the same aws account with multiple amplify env and we are using layers (dev account). When we push a layer, it has the stack name and is incremented with a version value. There is no env reference on it.

**Amplify CLI Version**
4.27.3

**To Reproduce**
1. Create env dev1 and push layer -> version 1
2. Create env dev2 and push layer -> version 2 with the exact same name

**Expected behavior**
Layer name should also have the ENV variable.

**Comment by jhockett** [comment]
Hi @SebSchwartz, layers created prior to version 4.29.0 do not function properly with multiple environments. If you upgrade and remake the layers it should fix the issue. See this comment for more info: https://github.com/aws-amplify/amplify-cli/issues/5250#issuecomment-686998885
