### ISSUE TITLE
codegen Angular services return wrong subscription listener observable types at runtime

### ISSUE THREAD

**Issue by rob3c** [aws-amplify/amplify-cli#5284]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
`codegen` generates Angular services that return graphql subscription listener observables at runtime that don't match their declared typescript types.

**Amplify CLI Version**
4.29.0

**To Reproduce**
Create any graphql API and have amplfiy codegen all types including subscriptions.

For example, the Amplify Angular getting started walkthrough [here](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular#creating-the-api-with-database) creates a simple Restaurant API with a single `Restaurant` type.

In the generated Angular `APIService`, there's an `OnCreateRestaurantListener` property implemented like this (other generated subscription properties are similar):
```typescript
OnCreateRestaurantListener: Observable<
  OnCreateRestaurantSubscription
  > = API.graphql(
    graphqlOperation(
      `subscription OnCreateRestaurant {
        onCreateRestaurant {
          __typename
          id
          name
          description
          city
          createdAt
          updatedAt
        }
      }`
    )
  ) as Observable<OnCreateRestaurantSubscription>;
```

While that may look right at first glance, it's fundamentally broken. It compiles successfully, but it breaks at runtime. 

**Expected behavior**
I expect the declared return types of generated code to match the actual runtime types.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node v12.18.3
(these versions are irrelevant - the angular codegen code for subscriptions is broken)

**Additional context**

The problem in the generated code is (referencing the sample above), the `OnCreateRestaurantSubscription` instance (i.e. the newly-created `Restaurant` object) is not directly at the top level in the observable response returned by the `API.graphql` call. 

If the intention is to only provide an observable for the newly-created objects, then something like this with a `map` call to pick out the new value is needed instead (modeled after the generated code for queries and mutations): 
```typescript
  OnCreateRestaurantListener: Observable<
    OnCreateRestaurantSubscription
  > = (API.graphql(
      graphqlOperation(
        `subscription OnCreateRestaurant {
          onCreateRestaurant {
            __typename
            id
            name
            description
            city
            createdAt
            updatedAt
          }
        }`
      )
    ) as Observable<any>)
  .map(x => x.value.data.onCreateRestaurant as OnCreateRestaurantSubscription);
```
This only fixes the return type. Other issues like robust error handling and such when provided as a property on a shared service instance vs a function that returns new cold observables is another matter to be addressed separately.

**Comment by SwaySway** [comment]
@rob3c Based on the amplify-js library the response is `event.value.data` ([source](https://github.com/aws-amplify/amplify-js/blob/b0668ddb187ce756264cecf114768fac52f9af1b/packages/pubsub/src/PubSub.ts#L173)). We also have this piece in our docs which you've linked. I've opened a PR to add an interface so it's more clear on the type coming from a subscription.

**Comment by rob3c** [comment]
@SwaySway I appreciate your attempt at feedback for my issue, but based on the nature of your response, it appears that my writing was not as clear as I had hoped. I'm quite familiar with the runtime shapes that Amplify generates in the Angular services, the docs, the source code used for both generating the broken Angular service as well as passing the values to observable subscribers at runtime.

The problem is that the code generated by the `codegen` tool does not generate the correct typescript types for graphql subscriptions in Angular services, as I mentioned above. As also mentioned above, I provided the fix for the generated subscription _if the intention is to match the generated type_. Obviously, if the intention is to change the generated type to match what is actually being produced, then you'd address it by fixing the return type instead.

In any case, the result object needed to match the (broken) generated type for the restaurant getting started sample that I mentioned is not directly `event.value.data`, but is `event.value.data.onCreateRestaurant`, as indicated above. That's based on what it actually took to get a real project working with the (broken) generated code to match the generated return type.

This would've been easily caught before publishing the library if there were any tests that used a generated angular service with typescript, as either typescript would've caught it and given a compiler error that breaks the build, or the assertions would've broken when testing the runtime subscription values if it got that far.

Unfortunately, there are no Angular service subscription tests. There are only abstract CodeGenerator print statements using template literals, so none of the concrete object types or shapes that are actually generated get tested or are even obvious to readers of the source code (since I'm sure the code passed review by humans at some point and is still broken). There are some snapshot-based tests for queries and mutations - but not for subscriptions - and that may seem like a solution here. However, the saved snapshots would have to be correct, and that can be prone to error if you're not checking behavior of the generated code. (Snapshot tests are a religious war in itself lol).

The bottom line is, it seems very likely that nobody on the team has actually tried using the generated Angular service with subscriptions using typescript (the predominant Angular language), because they just don't work as generated (although they work fine after patching things up). I suspect this is due to the strong React bias the team seems to have (which is fine in itself - I like React too, and it's a nice framework with a solid ecosystem. However, this library is meant to support multiple platforms well.)

Unfortunately, obviously untested code like this really gives the impression that Angular is relegated to being a second class citizen in the Amplify world. None of the relatively fewer samples or walkthroughs are up-to-date to a modern Angular version or work exactly as described in the docs without alteration, including being outright broken like generated subscription typings are.

Another related issue is that Amplify uses `zen-observable` instead of `rxjs` for the subscription observables in a supposedly Angular service, which is more evidence the Amplify team doesn't seem too worried about providing a native Angular experience. And zen vs rxjs incompatibility issues aside, Amplify uses the outdated `zen-observable-ts` project for zen typings that don't even match the full zen observable interface completely! (For example, `concat` is available at runtime on a zen observable but is missing in the typescript typings for it.)

(There's also the matter I mentioned that we're only addressing the return type here rather than observable implementation details, but it's beyond the issue scope and this comment has turned out to be much longer than intended already lol - sorry about that.)

Amplify is certainly growing into a nice suite of tools that makes a lot of AWS interactions easier! I think it's important to understand the assumptions, biases and limitations of any tool to best leverage its capabilities. Please try to accept my comments here as the constructive feedback they were intended to be from someone working through those in a serious and detailed attempt to incorporate Amplify into multiple frontend and backend projects.

**Comment by kdubb** [comment]
@rob3c Is correct on both major points... 
1. **Generated code is incorrect** for listeners.
  This is a _nightmare_ when using strict Typescript.
1. Non RxJS `Observable`s
  In an Angular project seeing the type `Observable` and it not being RxJS is pretty jarring. At the very least the docs should highlight this inconsistency and at the most selecting your preferred implementation (ahem RxJS) should be allowed.
