### ISSUE TITLE
Unable to add analytics in ap-northeast-2

### ISSUE THREAD

**Issue by jakemraz** [aws-amplify/amplify-cli#5287]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
can't create Pinpoint service using amplify-cli in ap-northeast-2 region

I executed 'amplify init' and created Amplify app in ap-northeast-2 region. It did work. I could see there is Amplify app in ap-northeast-2.
afterward, I executed 'amplify add notifications' but Pinpoint service was created in us-west-2 even though Amplify App is in ap-northeast-2 and region value is set to ap-northeast-2 in ~/.aws/config
(I don't know why Pinpoint services is created in us-west-2 even though there is pinpoint launched at ap-northeast-2)

I tried to create Pinpoint using amplify-cli 5 times, but everytime I created, it always is created in us-west-2

**Amplify CLI Version**
4.29.1

**To Reproduce**
set your region to ap-northeast-2 at ~/.aws/config

$ amplify add analytics
? Select an Analytics provider Amazon Pinpoint
? Provide your pinpoint resource name: remove
Adding analytics would add the Auth category to the project if not already added.
? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analyt
ics events? (we recommend you allow this when getting started) Yes
Successfully added auth resource locally.
Successfully added resource remove locally

Some next steps:
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all your local backend and front-end resources (if you have hosting category added) and provisions them in the cloud

$ amplify console
https://ap-northeast-2.console.aws.amazon.com/amplify/home?region=ap-northeast-2#/dbobakoi9fape/YmFja2VuZA/dev

$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Auth      | cognito03492cea | Create    | awscloudformation |
| Analytics | remove          | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS DeploymentBucket          AWS::S3::Bucket            Thu Sep 10 2020 10:29:26 GMT+0900 (Korean Standard Time)
UPDATE_IN_PROGRESS AuthRole                  AWS::IAM::Role             Thu Sep 10 2020 10:29:26 GMT+0900 (Korean Standard Time)
UPDATE_IN_PROGRESS UnauthRole                AWS::IAM::Role             Thu Sep 10 2020 10:29:26 GMT+0900 (Korean Standard Time)
UPDATE_IN_PROGRESS amplify-remove-dev-102726 AWS::CloudFormation::Stack Thu Sep 10 2020 10:29:21 GMT+0900 (Korean Standard Time) User Initiated
⠧ Updating resources in the cloud. This may take a few minutes...
...
...
...
✔ All resources are updated in the cloud

Pinpoint URL to track events https://us-west-2.console.aws.amazon.com/pinpoint/home/?region=us-west-2#/apps/da6cb269cefb4b9398d99a2b99bc47b9/analytics/overview

**Expected behavior**
Pinpoint should be generated in ap-northeast-2

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 13.8.0

**Additional context**
Pinpoint has been launched in ap-northeast-2
Please support adding Pinpoint in ap-northeast-2 using amplify-cli

**Comment by akshbhu** [comment]
Hi @jakemraz 

Yes currently amplify-cli doesn't support for ap-northeast-2 region for pinpoint. I have mark this as enhancement and 👍 to get this prioritized.

**Comment by leonli** [comment]
and doesn't support ap-northeast-1 as well during my test.

**Comment by leonli** [comment]
a simple solution is to modify the cloudformation template after its generation

```
"ap-northeast-1": {
                "pinpointRegion": "ap-northeast-1"
 },
```
