### ISSUE TITLE
No field named xxxxxx found on type Query using custom Resolvers and Types annotated with @aws_iam @aws_cognito_user_pools and query field @auth directive

### ISSUE THREAD

**Issue by fkoner** [aws-amplify/amplify-cli#5289]
**Describe the bug**

I need to annotate my custom query method with @auth directive in order to allow both authorized and guess acces to my custom resolvers/methods/api using @aws_iam and @aws_cognito_user_pools Appsync Authorization Types

Like described at the following issues:

https://github.com/aws-amplify/amplify-cli/issues/4520
https://github.com/aws-amplify/amplify-cli/issues/2701
https://github.com/aws-amplify/amplify-cli/issues/2540
https://github.com/aws-amplify/amplify-cli/issues/2711

Similar to the following:

```
type Query {
  ninjaQuery(
    filter: AWSJSON
    sort: AWSJSON
    limit: Int
    nextToken: [String]
  ): NinjaConnection
   @auth(
     rules: [
       { allow: public, provider: iam }
       { allow: private, provider: userPools }
       { allow: private, provider: iam }
     ]
   )
}
```

**Amplify CLI Version**
4.29.1

**To Reproduce**
I have the following schema

```
type ClassProductOrService
  @aws_iam
  @aws_cognito_user_pools
  @model
  @searchable
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
      { allow: groups, groups: ["HERO"] }
    ]
  ) {
  id: ID!
  name: String!
  classID: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type Brand
  @aws_iam
  @aws_cognito_user_pools
  @searchable
  @model
  @auth(
    rules: [
      { allow: owner, operations: [read, create, update, delete] }
      { allow: private, provider: iam }
      {
        allow: groups
        groups: ["HERO"]
        operations: [read, create, update, delete]
      }
      {
        allow: groups
        groups: ["NINJA"]
        operations: [read, create, update]
      }
    ]
  ) {
  id: ID!
  brandName: String
  owner: String
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type CustomSearchableClassProductOrServiceConnection
  @aws_iam
  @aws_cognito_user_pools {
  items: [ClassProductOrService]
  nextToken: [String]
  total: Int
}

type CustomSearchableBrandConnection @aws_iam @aws_cognito_user_pools {
  items: [Brand]
  nextToken: [String]
  total: Int
}

### Custom Queries
type Query {
  searchClassProductOrServicesEnhanced(
    filter: AWSJSON
    sort: AWSJSON
    limit: Int
    nextToken: [String]
  ): CustomSearchableClassProductOrServiceConnection
   @auth(
     rules: [
       { allow: public, provider: iam }
       { allow: private, provider: userPools }
       { allow: private, provider: iam }
     ]
   )
  searchBrandsEnhanced(
    filter: AWSJSON
    sort: AWSJSON
    limit: Int
    nextToken: [String]
  ): CustomSearchableBrandConnection @aws_iam @aws_cognito_user_pools
   @auth(
     rules: [
       { allow: owner }
       { allow: private, provider: iam }
       { allow: groups, groups: ["HERO", "NINJA"] }
     ]
   )
}
```

I had configured custom resolvers at CustomResources.json file as described here: [Custom resolvers](https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable)

```
...
 "Resources": {
    "EmptyResource": {
      "Type": "Custom::EmptyResource",
      "Condition": "AlwaysFalse"
    },
    "QuerySearchClassProductOrServicesEnhanced": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": { "Ref": "AppSyncApiId" },
        "DataSourceName": "ElasticSearchDomain",
        "TypeName": "Query",
        "FieldName": "searchClassProductOrServicesEnhanced",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.searchClassProductOrServicesEnhanced.req.vtl",
            {
              "S3DeploymentBucket": { "Ref": "S3DeploymentBucket" },
              "S3DeploymentRootKey": { "Ref": "S3DeploymentRootKey" }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.searchClassProductOrServicesEnhanced.res.vtl",
            {
              "S3DeploymentBucket": { "Ref": "S3DeploymentBucket" },
              "S3DeploymentRootKey": { "Ref": "S3DeploymentRootKey" }
            }
          ]
        }
      }
    },
    "QuerySearchBrandsEnhanced": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": { "Ref": "AppSyncApiId" },
        "DataSourceName": "ElasticSearchDomain",
        "TypeName": "Query",
        "FieldName": "searchBrandsEnhanced",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.searchBrandsEnhanced.req.vtl",
            {
              "S3DeploymentBucket": { "Ref": "S3DeploymentBucket" },
              "S3DeploymentRootKey": { "Ref": "S3DeploymentRootKey" }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Query.searchBrandsEnhanced.res.vtl",
            {
              "S3DeploymentBucket": { "Ref": "S3DeploymentBucket" },
              "S3DeploymentRootKey": { "Ref": "S3DeploymentRootKey" }
            }
          ]
        }
      }
    }
...
```

When I run amplify push command, I got the following error:

```bash
CREATE_FAILED      QuerysearchBrandsEnhancedResolver                 AWS::AppSync::Resolver      Thu Sep 10 2020 00:35:54 GMT-0500 (Central Daylight Time) No field named searchBrandsEnhanced found on type Query (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 86823b13-a563-47df-bfe5-d5b9819d3b20; Proxy: null)

CREATE_FAILED QuerysearchClassProductOrServicesEnhancedResolver AWS::AppSync::Resolver  Thu Sep 10 2020 00:35:54 GMT-0500 (Central Daylight Time) No field named searchClassProductOrServicesEnhanced found on type Query (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 35ac621b-0fb2-44ed-9309-83a2d404a93e; Proxy: null)
UPDATE_FAILED AuthRolePolicy05                                  AWS::IAM::ManagedPolicy Thu Sep 10 2020 00:35:54 GMT-0500 (Central Daylight Time) Resource update cancelled                                                                                                                                                                                    
UPDATE_FAILED UnauthRolePolicy02                                AWS::IAM::ManagedPolicy Thu Sep 10 2020 00:35:54 GMT-0500 (Central Daylight Time) Resource update cancelled 

UPDATE_FAILED               GraphQLSchema                                                           AWS::AppSync::GraphQLSchema Thu Sep 10 2020 00:35:55 GMT-0500 (Central Daylight Time) Resource update cancelled

UPDATE_FAILED               apitrademarkplatform                 AWS::CloudFormation::Stack Thu Sep 10 2020 00:36:01 GMT-0500 (Central Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:551015711805:stack/amplify-trademarkplatform-dev-234040-apitrademarkplatform-1QOO6B75RZTWV/22193010-c8c5-11ea-b438-0eac0ccc6c9d was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [QuerysearchClassProductOrServicesEnhancedResolver, QuerysearchBrandsEnhancedResolver]. The following resource(s) failed to update: [UnauthRolePolicy02, AuthRolePolicy05, GraphQLSchema].
```

If I drop the @auth directive the amplify push command works like a charm. As I understand if I annotate my custom Query method with the @auth directive amplify cli will ensure to create the adecuate IAM policies in order to achieve both authenticated and guess acces using @aws_iam and @aws_cognito_user_pools Appsync Authorization Types.

**Expected behavior**
Allow to annotate multiple custom Query methods with @auth directive and ensure to create the adecuate IAM policies in order to achieve both authenticated and guess acces using @aws_iam and @aws_cognito_user_pools Appsync Authorization Types.

**Screenshots**
![amplify-@auth-issue-custom-resolver](https://user-images.githubusercontent.com/2480544/92691822-d0683680-f308-11ea-9505-bc4d5a720dfe.png)

**Desktop (please complete the following information):**
 - OS: Mac/Ubuntu
 - Node Version: 10.20.1

**Additional context**
If required I could share additional information in order to reproduce it.

**Thanks in advance**
**__Paco__** :rocket:

**Comment by mikedizon** [comment]
running into the same issue. were you able to resolve @fkoner ?

**Comment by danrivett** [comment]
Yep I am also running into this same issue when trying to allow access using `@auth` to a query provided by a custom lambda resolver:

```graphql
type Query {
  getByJobIds(jobIds: [ID!]!): [Job!]!
    @auth(
      rules: [
        { allow: private } # Allow Frontend access
        { allow: private, provider: iam } # Allow backend access
      ]
    )
}
```

I just get the following on `amplify push`:

```
No field named getByJobIds found on type Query (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: XXX; Proxy: null)
```

@attilah I'd be very grateful if you could take a look at this issue as seems to follow on to your initial fix in #2701 and you either may have an alternative suggestion or can get this triaged and hopefully fixed in the not too distant future? Thank you.

**Comment by danrivett** [comment]
I managed to solve this by removing the `@auth` Amplify-supplied annotation I use elsewhere and using AppSync's `@aws_iam` and `@aws_cognito_user_pools` annotations instead.

Based on my interpretation of @undefobj's [comment](https://github.com/aws-amplify/amplify-cli/issues/2701#issuecomment-555253252) I thought it wasn't the correct approach when using Amplify, but this is the only approach that is working for me after many hours of experimentation. Richard's comment is over a year old too, so maybe out of date. 

Either way, this approach is the only one I have working so far. Posting in case it helps anyone else.

**Comment by yuth** [comment]
@fkoner when an `@auth` directive is added to a field, the transformer automatically creates an resolver for that field.  There is no need to create an resolver in CustomResources.json. The usage of `@auth` directive is on an Query field is meant to be backed by an function, otherwise the resolver created by `@auth` directive will have `NONE` data source and won't be very useful.

If you want to use some custom data source, then I would recommend not using `@auth` directive. Like mentioned above `@auth` creates custom IAM policy when IAM provider is used, which you will have to do in custom resources if you're not using `@auth`

 @danrivett, this could be some related to some hashing issue how we generate the S3 path for resolvers. Could you try this again by updating the input schema and adding some additional spaces and see if that fixes it

**Comment by danrivett** [comment]
@yuth could you expand on what you mean by adding "additional spaces" I'm afraid I don't follow.

**Comment by yuth** [comment]
> @yuth could you expand on what you mean by adding "additional spaces" I'm afraid I don't follow.

Amplify CLI uses the hash of the schema file in to store resolvers and when output schema. If the path remains the same for any reason, the Cloudformation treats the change as no-op and could cause this issue. By addtion spaces I mean updating your input schema by adding empty spaces
