### ISSUE TITLE
How do you change the default region for amplify cli?

### ISSUE THREAD

**Issue by cityzen** [aws-amplify/amplify-cli#529]
** Which Category is your question related to? **
configuration

** What AWS Services are you utilizing? **
Amplify

** Provide additional details e.g. code snippets **
I am not sure how my default amplify region was set to eu-west-2 but that's not the region I want. Now whenever I create a new resources, it's always in eu-west-2 but I'm in the US. 

I tried doing amplify configure but that seems to just add a new profile to my .aws credentials. I also tried doing amplify storage add --profile profilename but that doesn't change anything.

Any ideas of how to change the amplify default region or do I need to uninstall/reinstall the cli? I don't even recall ever selecting eu-west-2 but could very well have been a misconfiguration on my part.

**Comment by cityzen** [comment]
@ajohnsen ahh, I tried `amplify configure` which seems to create a new aws profile. I'll look at `aws configure` and see if somehow I have my default region incorrect.

Thanks for the info!

**Comment by yuth** [comment]
You could run `amplify configure project` and use a new profile with the desired region
