### ISSUE TITLE
How to add Cognito postConfirmation Trigger to an existing Auth

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5291]
**Which Category is your question related to?**

amplify update auth

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

Auth

**Provide additional details e.g. code snippets**

Is it possible to add a Cognito postConfirmation trigger to an existing auth resource? If so, which steps should I follow?

**Comment by akshbhu** [comment]
Hi @christodupreez 

If you have added auth via amplify cli , then you can do ```amplify update auth``` and in the workflow select ```Walkthrough all the auth configurations```. In the end of workflow  it asks the question:```Do you want to configure Lambda Triggers for Cognito?``` , select yes and choose the type of trigger you want to select.

**Comment by christodupreez** [comment]
```
Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) (Use arrow keys)
❯ Yes 
  No
```

I'm not sure what I originally chose on this, how would I be able to see and would it break anything if I chose a different option than before?

**Comment by kaustavghosh06** [comment]
@christodupreez Are you still stuck on this? We automatically point to the default option which you'd originally selected in the update auth flow.
