### ISSUE TITLE
Amplify mock go resolver returns object with all values null

### ISSUE THREAD

**Issue by Jhorlin** [aws-amplify/amplify-cli#5293]
**Describe the bug**
When creating an AppSync function resolver written in go and the return is a struct "object". The [local invoke](https://github.com/Jhorlin/amplify-cli/blob/master/packages/amplify-go-function-runtime-provider/src/localinvoke.ts#L48) for amplify-go-function-runtime-provider return the result which is always a string, even if the resolver returns a struct "object" it is the string representation `"{\"my\":\"example\"}"`.

**Amplify CLI Version**
4.29.1

**To Reproduce**
1. Create an AppSync resolver in go
```go
package main

import (
	"context"

	"lib/events"
	"lib/log"

	"github.com/aws/aws-lambda-go/lambda"
)

// Args - Query arguments
type Args struct {
	Message string `json:"msg"`
}

type Echo struct {
	Message string `json:"Message"`
}

// HandleRequest - handle lambda request
func HandleRequest(ctx context.Context, event events.Resolver) (interface{}, error) {
	args := Args{}
	if err := event.UnmarshalArguments(&args); err != nil {
		log.Logger.Errorf("Error unmarshaling args: %v", err)
		return nil, err
	}
	return Echo{args.Message}, nil
}

func main() {
	lambda.Start(HandleRequest)
}
```
2. Create a graphql service with a query that returns an object and bind the object to the go function resolver.
```graphql
type Echo @aws_iam {
  Message: String
}

type Query {
  echo(msg: String): Echo @aws_iam @aws_oidc @function(name: "echo-${env}")
}
```

3. Execute your query.
```javascript
query MyQuery {
  echo(msg: "hello") {
    Message
  }
}
```
The result is 
```javascript
{
  "data": {
    "echo": {
      "Message": null
    }
  }
}
```
**Expected behavior**
```javascript
{
  "data": {
    "echo": {
      "Message": "hello"
    }
  }
}
```

**Desktop (please complete the following information):**
 - OS: PopOS based on Ubuntu
 - Node: v14.10.0

**Additional context**
The issue is the the go result is always a string. I think the solution is to parse the response in a try catch block and on cath return the original result.

**Comment by edwardfoyle** [comment]
The fix for this has been released in CLI v 4.32.0
