### ISSUE TITLE
Get type mismatch when using array of dynamic groups in @auth rules

### ISSUE THREAD

**Issue by hhemmati81** [aws-amplify/amplify-cli#5300]
I am trying to use an array of dynamic groups in the @auth rules and I get type mismatch error. It works in the mock just fine though. It also works if I use a single group instead of an array. Here are my schema and the error message that I am getting.

```
type ViralLoad
@model
@key(
  name: "ByDate"
  fields: ["groups", "createdAt"]
  queryField: "viralLoadByGroup"
)
@auth(
  rules: [
    { allow: owner }
    { allow: groups, groupsField: "groups", operations: [read] }
  ]
) {
  id: ID!
  location: String!
  createdAt: AWSDateTime
  time: [ViralLoadTime]
  reagentKitID: String
  machineID: String
  samples: [ViralSample]
  groups: [String]
}

type ViralLoadTime {
  start: AWSDateTime
  stop: AWSDateTime
  experimental: AWSDateTime
}

type ViralSample {
  load: Int
  control: Int
}
```

My sample mutation.
```
mutation MyMutation {
  createViralLoad(input: {location: "Location 1", createdAt: "2020-09-09T00:00:00Z", groups: ["Admin"]}) {
    location
    createdAt
  }
}
```

And the error message.
```
{
  "data": {
    "createViralLoad": null
  },
  "errors": [
    {
      "path": [
        "createViralLoad"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "One or more parameter values were invalid: Type mismatch for Index Key groups Expected: S Actual: L IndexName: ByDate (Service: DynamoDb, Status Code: 400, Request ID: QRGBTDVJ7EDIJV0JBK4JCJCDHRVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"
    }
  ]
}
```

**Comment by RossWilliams** [comment]
The "byDate" GSI uses groups as part of the key. Keys can only be string, number, or binary types. They cannot be lists.

**Comment by hhemmati81** [comment]
So the problem is in the key section not actually using an array for the auth. I wonder why this is working in the amplify mock.

**Comment by RossWilliams** [comment]
The problem is even earlier. There is a bug in the @key transformer code that validates the schema. It incorrectly tests for scalar types. It calls a method to get the field type, but that method looks inside lists and reports on the type of the list, so it never detects an invalid list type. See [here](https://github.com/aws-amplify/amplify-cli/blob/99885274488d2cb150d7858c95cb07e91221647a/packages/graphql-key-transformer/src/KeyTransformer.ts#L495)

**Comment by hhemmati81** [comment]
Thanks Ross, this was driving me crazy. At least I know what I have to do to get it working.
