### ISSUE TITLE
Throttled when building two amplify projects at the same time in Amplify/AWS Console

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#5309]
**Describe the bug**
I triggered the build of 2 environments at the same time and the second build fail because of throtteling in the amplify init  phase. (This is when building in the Amplify console triggered from a Git operation). If this can happen on just two environments can this happen in a single environment given that my Amplify project is big enough?

```
{ Throttling: Resource is not in the state stackUpdateComplete
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
 

 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 time: 2020-09-10T14:52:40.134Z,
                                 requestId: '8284f63b-fc4b-4652-b5be-c0a6661b554d',
                                 retryable: false,
                                 originalError:
                                 { message: 'Rate exceeded',
                                 code: 'Throttling',
                                 time: 2020-09-10T14:52:40.133Z,
                                 requestId: '8284f63b-fc4b-4652-b5be-c0a6661b554d' },
                                 statusCode: 400,
                                 retryDelay: 30000 }
```

I assume this is because it asks the Cloudformation stack too often if it is done. 

(My project isn't that big yet, we got 11 functions + the ones that the Auth and API generates.)

**Comment by ammarkarachi** [comment]
@Zanndorin Can you take a look at some online resources to debug more into the problem?
https://aws.amazon.com/premiumsupport/knowledge-center/cloudtrail-rate-exceeded/
