### ISSUE TITLE
Custom auth function

### ISSUE THREAD

**Issue by cgorrieri** [aws-amplify/amplify-cli#5324]
**Which Category is your question related to?**
Auth, API, Function

**Amplify CLI Version** 
4.29.1

**What AWS Services are you utilizing?**
Cognito, DynamoDB, AppSync

**Provide additional details e.g. code snippets**

Hello, I am currently looking at the model to use dynamic groups for authorization.

I have looked at other issues that mention using a PreToken lambda to insert the groups in the generated token, and have a subscription on the Permission table to notify the user to refresh the token.

This works well if the permissions keep being added. However, I am not sure it is secure if a permission is being removed as the user might not click on refreshing the token and will keep being part of a group as per the data in the token. If you have a solution for that I am interested.

I tried a different approach with a function returning the ids of the users allowed to perform the action (in my case there won't be more than 20), but probably the function is resolved after the auth in the resolvers.

That was my attempt:
```
type Model @model
  @auth(rules: [
    { allow: owner, ownerField: "ownerIds"}
  ]) {
  id: ID!
  ...
  ownerIds: [String] @function(name: "GetAllwedEditorIds-${env}")
}
```

Is there a plan in the roadmap for a way to add a custom function to a rule? something like:
```
type Model @model
  @auth(rules: [
    { allow: owner, function: "AuthUserForModel"}
  ]) {
  id: ID!
  ...
}
```

Thank you.

**Comment by RossWilliams** [comment]
To restate, you want to use dynamic groups, but you need to immediately revoke access when a user is no longer part of a group. A bearer then cannot be the mechanism to control auth for the model, but it can still be used as part of the graphQL query.

In AppSync this can be done with transactions where you have the main query and a second condition check get request. This isn't well supported in Amplify.

For Amplify, you may be able to use a mapping table that also controls the group membership. So you may have a User, Groups, and UserGroups table, and only allows queries for groups by going "through" the UserGroups table.

There are other methods as well, but this should give you an idea. My use of subscriptions is mainly to help the frontend know which queries can be run.

**Comment by cgorrieri** [comment]
That sounds interesting, I will have a try.
Thank you @RossWilliams

**Comment by UnleashedMind** [comment]
closing this issue for now, feel free to comment and open another issue if needed.
