### ISSUE TITLE
headless [amplify init] gets stuck with command prompt [Do you want to configure Lambda Triggers for Cognito? (Y/n)] for new build machines

### ISSUE THREAD

**Issue by alexdoan102** [aws-amplify/amplify-cli#5325]
**Describe the bug**
headless [amplify init] gets stuck with command prompt [Do you want to configure Lambda Triggers for Cognito? (Y/n)] for new build machines.  If you have a lambda cognito function, when you use a build machine for the first time, it prompts you with cognito message, and the headless [amplify init] is stuck waiting for that question to be answered.   NOTE: this happens only on the first time, if you get past this prompt, the next time you build, you are not going to get prompted again.
 ==> BTW, [--yes] option on headless [amplify init], will fix this problem, but the [--yes] option does BOTH a [init+push]   
            ==> see this issue here: https://github.com/aws-amplify/amplify-cli/issues/3721
                       ==> we cannot use [--yes] option, becuase we do not want it to automatically "push",since i have custom build/compile options i need to do for apsync (before i do the final [amplify push]

**Amplify CLI Version**
4.19.0 (and latest version too)

**To Reproduce**
either use the [amplify cli] or create a [ci/cd aws amplify console] profile, and call the ] headless [amplify init].
==> make sure you have a appsync project with custom lambda triggers.  (this is why it prompts you for [configure lambda trigger? command prompt] 
==> DO NOT USE the [--yes] option with [amplify init], because this forces a [init+push], which we do not want. 
    ==> related issue here:  Calling "amplify init" with "--yes" pushes on the cloud at the end of initialization
                                            https://github.com/aws-amplify/amplify-cli/issues/3721

**Expected behavior**
the headless [amplify init],  should have a way to bypass [lambda trigger for cognito] command prompt WITHOUT using the [--yes] input parameter.

**Screenshots**
![image](https://user-images.githubusercontent.com/73307/93104338-b5d0ed00-f67b-11ea-96c7-921c4729113c.png)

![image](https://user-images.githubusercontent.com/73307/93104395-c97c5380-f67b-11ea-8d2d-9e404a2efa25.png)

**Desktop (please complete the following information):**
 - OS:  windows amplify cli, * [aws amplify console]
 - Node Version. v12.16.1

**Additional context**

**Comment by UnleashedMind** [comment]
@alexdoan102 
What Amplify CLI version are you using? 
The init command shouldn't prompt that question if you are using the latest version of the CLI, it's been fixed by this [PR](https://github.com/aws-amplify/amplify-cli/pull/5039/files)
