### ISSUE TITLE
Is Amplify support private API function of APIGW?

### ISSUE THREAD

**Issue by denonade** [aws-amplify/amplify-cli#5326]
When we use "amplify api add" to create REST API in APIGW, the frontend use a public amplify domain to connect with APIGW.
1) Does it mean this traffic pass through internet to APIGW?
2) Can we setup a private API by leveraging VPN endpoint and resource policy with dedicated source VPC to serve our amplify frontend to have a REST API call with APIGW , which the traffic is routing within the AWS cloud?

Please advises, thanks.

**Comment by UnleashedMind** [comment]
1. yes
2. The Amplify CLI currently does not provide this capability. The Amazon API Gateway does allow you to set up private API that can only be accessed from your virtual private cloud in Amazon VPC by using an interface VPC endpoint
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html
