### ISSUE TITLE
#return directive within #if.....#else not working when using Amplify Mock

### ISSUE THREAD

**Issue by jliburd-nsi** [aws-amplify/amplify-cli#5328]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
The #return directive does not seem to work when used in an #if...#else block in the request mapping template.

DOES NOT WORK:

`#if( $util.isNullOrEmpty($ctx.source.team) )

  #return

#end

{
  "version": "2018-05-29",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.team, "___xamznone____"))
  }
}`

WORKS:

`#return

{
  "version": "2018-05-29",
  "operation": "GetItem",
  "key": {
      "id": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.team, "___xamznone____"))
  }
}`

Note: When testing, I verified that the if...else block is being entered by throwing an error in the block. Also, the code works when using it with the AppSync API.

**Amplify CLI Version**
4.29.1

**To Reproduce**
Try using similar code above in a request mapping template

**Expected behavior**
The `#return` directive would stop the execution of the mapping template when used in an if...else block

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows using WSL2
 - Node Version: 12.16.2

**Additional context**

**Comment by UnleashedMind** [comment]
I tried but I can't reproduce the issue. early return with #return is actually respected by the amplify mock.

**Comment by jliburd-nsi** [comment]
Did you try it with the `#return` in the if...else block? If you did and it worked, you can close the issue as it may have something to do with my setup. Thanks.

**Comment by UnleashedMind** [comment]
yes, the return is inside a #if #end block

**Comment by jliburd-nsi** [comment]
I already tested to ensure that the #if statement was passing and the code was entering the block, I tried again just now using a simple #if statement and it still didn't early return from the request mapping template. 

Closing this since the issue may be specific to me since it cannot be reproduced. Thanks for looking into it.
