### ISSUE TITLE
Mutation to save connected models (one-to-many) using parent model mutation

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5331]
**Which Category is your question related to?**

API

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

Is it possible to update the User (rather than the Retailer) once a Retailer is linked to a User model?

Currently, I'm updating the Retailer using the mutation below, but I am having to loop through an array of (linked Retailers) and calling the mutation to create the link. I would rather want to save the User model once with an array of Retailers.

```
      mutation($id: ID! $retailerUserId: ID!) {
          updateRetailer(input: {
              id: $id retailerUserId: $retailerUserId
          }) {
              id
            }
      } 
``` 

My schema:

```
type Retailer @model
{
  id: ID!
  name: String!
  description: String
  user: User @connection(name: "UserRetailers")
}

type User @model {
  id: ID!
  username: String!
  retailers: [Retailer] @connection(name: "UserRetailers")
}
```

**Comment by UnleashedMind** [comment]
you are actually updating a retailer record, you relink the retailer to another user, so you need to update the retailer not the user.

**Comment by christodupreez** [comment]
@UnleashedMind thank you for the feedback. I would prefer to do it using the User as this is the easiest approach from a UI perspective. The user is editing a User, linking one-to-many Retailers. (currently, I'm looping through the linked/unlinked Retailers and updating then one by one) Alternatively, is there a way to do a bulk update Retailers linking them to the User?

Thank you for the heads-up on the new connection definitions

**Comment by UnleashedMind** [comment]
I don't see how that can be done, if you are updating the retailer's userId, you are link the retailer to another user.
