### ISSUE TITLE
Amplify delete is taking too long, hours and it still not deleted!!!

### ISSUE THREAD

**Issue by rickirea** [aws-amplify/amplify-cli#5336]
**App Id**:
**Region**:
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by UnleashedMind** [comment]
@rickirea 
We need to gather some information about the project to further investigate the issue. 
- what is the Operating System? and it's version?
- What is the Amplify CLI version?
- What backend resource categories did you add to your project (AppSync API, function, storage, etc.)?

Please go to the Cloudformation, open the root stack template and see if you can get the errors in the CloudFormation delete operation.

**Comment by berenddeboer** [comment]
Probably not an amplify issue, but a CloudFormation issue.

**Comment by UnleashedMind** [comment]
Closing the issue for now, feel free to open another one if you are still blocked.
