### ISSUE TITLE
[request] Amplify codegen or Amplify push should ask if codegen should be in TypeScript

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#5338]
**Describe the bug**

when i run `amplify push` or `amplify codegen`, amplify cli generates javascript by default. there is no prompt to generate typescript, unless i run `amplify codegen configure` and then rerun `amplify codegen`. this makes typescript seem like a second class citizen.

**Amplify CLI Version**

4.27

**Comment by renebrandel** [comment]
@sw-yx upon the first time `amplify push` we actually ask whether you want to configure typescript or not. Are you suggesting to asking this on every amplify push?
![image](https://user-images.githubusercontent.com/4989523/93825265-c5bb7480-fc19-11ea-91f9-d17efff43434.png)

**Comment by sw-yx** [comment]
ah i think the problem here is that i have aliased my CLI to use `amplify push --y` by default. it makes sense that `-y` would also pick javascript as the default. sorry for false alarm
