### ISSUE TITLE
Give configuration flag to allow `amplify publish` to invalidate CDN if flag is set

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#534]
**Is your feature request related to a problem? Please describe.**
Right now it doesn't appear that `amplify publish` is invalidating the associated CloudFront distribution, which for this particular Amplify site should be entirely invalidated (`*` resource) on update (publish).

**Describe the solution you'd like**
A simple ability to configure `amplify publish` to invalidate resources in the associated CloudFront distribution if desired (probably off by default for websites using S3 versioning).

**Describe alternatives you've considered**
Manually invalidating the CloudFront distro every time I `amplify publish`, which is tedious.

**Comment by yuth** [comment]
You can invalidate the cache by passing `-c` flag to `publish` command. Its documented in [hosting workflow ](https://aws-amplify.github.io/docs/cli/hosting#workflow)

**Comment by jarrettj** [comment]
That link is no longer relevant? Where's the docs on the -c flag gone to?

**Comment by Yangeok** [comment]
> That link is no longer relevant? Where's the docs on the -c flag gone to?

[Here](https://docs.amplify.aws/cli/hosting#cache-invalidation)

**Comment by FOMSON** [comment]
Just FYI.

Documented [here](https://docs.amplify.aws/cli/hosting#stages) CLI command `amplify publish -c` doesn't seem to invalidate anything for me. However, `amplify publish --invalidateCloudFront` seems to do the trick...
