### ISSUE TITLE
stack is in "UPDATE_IN_PROGRESS state and can not be updated"

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#5343]
**Describe the bug**
Was updating a lambda via AWS Amplify build. Backend build just hang there, and I think AWS Amplify timed out. Any successive pushes now report:

```
Stack:arn:aws:cloudformation:us-east-1:...:stack/amplify-.../... is in UPDATE_IN_PROGRESS state and can not be updated.
An error occurred during the push operation: Stack:arn:aws:cloudformation:us-east-1:914282159778:stack/amplify-.../... is in UPDATE_IN_PROGRESS state and can not be updated.
```

**Amplify CLI Version**
I was deploying with the latest before 4.29.2. I updated now to 4.29.2

**Additional context**
How do I get my stack back in a normal state?

**Comment by hisham** [comment]
I'm cancelling the update via cloudformation UI, let's see if that works.

**Comment by hisham** [comment]
That worked and now I'm able to push again, but my push is taking long time with: 

`⠙ Updating resources in the cloud. This may take a few minutes...
`

**Comment by MontoyaAndres** [comment]
I have the exact same problem and I was about to do an issue about it, how did you cancel the update?

**Comment by hisham** [comment]
Go to https://console.aws.amazon.com/cloudformation/home

And there will be an "Action" button on top right, click that and you'll see option to cancel. 

My push eventually succeded btw, so I guess issue is resolved for now.

**Comment by MontoyaAndres** [comment]
![image](https://user-images.githubusercontent.com/15065852/93402024-3bee5e80-f849-11ea-877e-38f437fe31f2.png)
this is in my case

**Comment by hisham** [comment]
So your rollback is stuck? I guess your cloudformation is trying to rollback...

**Comment by MontoyaAndres** [comment]
What can I do to resolve it? I dont know what to do, I just wanted to update a lambda, and then happened this. Maybe I hit Ctrl + C to cancel the process and this broke this?

**Comment by MontoyaAndres** [comment]
![image](https://user-images.githubusercontent.com/15065852/93402415-4ceb9f80-f84a-11ea-94a7-e0b0317932cb.png)
these are what I have on cloudformation, the first that is creating is a branch I'm creating but is taking many time...

**Comment by ammarkarachi** [comment]
@hisham @MontoyaAndres IAM is experiencing an outage I would wait for the resolution before pushing again. You can find more information here https://status.aws.amazon.com/#

**Comment by MontoyaAndres** [comment]
I think I could fix it, I just deleted the stacks of this month 09, just there are two, and now I'm able to continue with Amplify

**Comment by MontoyaAndres** [comment]
![image](https://user-images.githubusercontent.com/15065852/93403415-106d7300-f84d-11ea-9df1-fb2e7f6bd813.png)
everything is green again :') thanks for the patience I guess jaja

**Comment by UnleashedMind** [comment]
closing the issue since you guys are not blocked anymore. 
Feel free to continue to comment here or open a new issue if needed.
