### ISSUE TITLE
How do I get the GraphQL Schema?

### ISSUE THREAD

**Issue by ryanto** [aws-amplify/amplify-cli#5346]
**Which Category is your question related to?**

API, AppSync, GraphQL

**Amplify CLI Version** 

4.18.1

**What AWS Services are you utilizing?**

Amplify

**Provide additional details e.g. code snippets**

Hello, I need to get the graphql schema that my amplify application is using.

I noticed a schema is written to `amplify/backend/api/$project/build/schema.graphql`, however when I try to load it I get runtime errors.

```js
import schema from "amplify/backend/api/$project/build/schema.graphql";
import { buildASTSchema } from "graphql";

let graphQLSchema = buildASTSchema(schema);
```

This results in the following errors:

```
Unknown directive "@aws_subscribe".
Unknown type "AWSTimestamp".
```

I'm wondering if there's anyway I can get the graphql schema from amplify.

**Comment by UnleashedMind** [comment]
What's giving the error? is it the graphql linter? 
`@aws_subscribe` is a AppSync directive, try to add a definition for it on top of the schema and see if the error goes away. 
```graphql
directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION
```
You don't need to add that if the schema is only used by Amplify CLI (AppSync recognizes its directives). 

In your App's codebase, you usually only directly use the queries, mutations and subscriptions generated by the Amplify CLI's codegen, which is located in the `sr/graphql/` folder for javascript projects.

**Comment by ryanto** [comment]
Thanks!

The error is coming from `buildASTSchema` which is part of the graphql library. It cannot read the schema that amplify generates because it is invalid due to this missing directive and type.

I can always manually add these, but amplify would overwrite the schema on every change, so I'd like to avoid that.

The project I'm working on needs to be able to share its graphql schema for testing purposes. It would be nice if amplify could generate a valid graphql schema, I feel it's very close to doing that, but a few items are missing.

Thank you!

Sidenote: I recently upgraded amplify-cli to 4.29.2 and the type changed to `AWSDateTime`, but the type definition is still missing from the schema.

**Comment by UnleashedMind** [comment]
The AppSync specific types and directives are not in the compiled schema because the CLI only uses them within the AppSync. I will mark this as an enhancement then.

**Comment by UnleashedMind** [comment]
Could you provide more information on the use case that this might be necessary?

**Comment by ryanto** [comment]
Sure!

1. I'd like to load the schema into our graphqli environment where I can explore the queries. I'm looking to do this without running amplify's mock command.

2. I want to use amplify with miragejs, which has the ability to take a schema and provide a number of helpers for mocking API responses. 

In both of those cases I need a valid graphql schema. Hope that helps, I can provide more info if needed.


Also, to be completely honest I was a little surprised that amplify does not provide a valid graphql schema. I feel a little cheated because I thought one of the selling points of amplify was that it's graphql, but I guess it's not really?

**Comment by josefaidt** [comment]
Hi @ryanto :wave: unfortunately we do not support integrations with miragejs, and currently recommend using `amplify mock api` as a way to test an API.

Closing this issue. If you experience issues testing with mock please consider filing a [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)
