### ISSUE TITLE
Amplify Cli: Auto-generated DDB trigger failed to deploy lambda resource

### ISSUE THREAD

**Issue by nikhil184** [aws-amplify/amplify-cli#5351]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I followed the steps described in the Amplify docs to create a Lambda trigger for a DDB table setup using @model : https://docs.amplify.aws/cli/usage/lambda-triggers#as-a-part-of-the-graphql-api-types-with-model-annotation

The Cloudformation generated for Lambda did not have Code section.The stack creation failed with Code attribute can't be empty/null.

Generated Cloud formation template for NodeJS Lambda DDB trigger:
```
"LambdaFunction": {
          "Type": "AWS::Lambda::Function",
          "Metadata": {
            "aws:asset:path": "./src",
            "aws:asset:property": "Code"
          },
          "Properties": {
            "Handler": "index.handler",
            "FunctionName": {
             .....
```
**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.29.1

**To Reproduce**
Steps: https://docs.amplify.aws/cli/usage/lambda-triggers#as-a-part-of-the-graphql-api-types-with-model-annotation
Lambda function runtime: `nodejs12.x`

**Expected behavior**
Stack deployment succeeds without any manual changes to CloudFormation template.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] - Mac
 - Node Version. You can use `node -v` to check the node version on your system. - v14.10.1

**Additional context**
Workaround: I manually modified the Cloudformation template to add code section,
```
            "Code": {
                "S3Bucket": {
                    "Ref": "s3bucket"
                },
                "S3Key": {
                    "Ref": "s3key"
                }
            },
```
It worked out for me.

**Comment by UnleashedMind** [comment]
I followed the steps in the document and I can not get the error. 
The Code section is not immediately added when you run `amplify function add`,  it's only added by the CLI right before the push. This is not just for the lambda trigger, but also for other types of functions. 
You don't have to manually add the "Code" section, just run `amplify push` and it will be successful.

**Comment by nikhil184** [comment]
@UnleashedMind  I am using it by referencing as a Cfn template in a CDK stack. We don't use `Amplify push` for deployment but use - "CDK deploy" AFAIK. What alternates we have apart from `Amplify push` adding it?

**Comment by UnleashedMind** [comment]
Currently you have to use `amplify push` to insert them. The logic is built into the `amplify push` workflow.
