### ISSUE TITLE
Composite sort key not created with @key directive

### ISSUE THREAD

**Issue by LpmRaven** [aws-amplify/amplify-cli#5352]
**Describe the bug**
Added a new `@key` to my schema.graphql

`@key(name: "bySupplier", queryField: "productsForSupplier", fields: ["region", "productType", "supplierSlug"])`

The new GSI is created in dynamoDB, but the composite SORT key is not. 

![Screen Shot 2020-09-16 at 3 50 38 pm](https://user-images.githubusercontent.com/6523593/93297418-8e715000-f834-11ea-8437-3e292ffecf11.png)

After a week, the new GSI remains empty of items.

**Expected behavior**
The composite sort key to be created and the dynamodb GSI to become populated.

**Comment by manueliglesias** [comment]
@renebrandel

**Comment by UnleashedMind** [comment]
When you open the "Indexes" tab for the table, it only shows the indexes, it doesn't show the items. 
In order to see the items, open the "Items" tab, and you will see the Items

**Comment by LpmRaven** [comment]
@UnleashedMind i'm aware that you can only see the items in the items tab. The screenshot was to show the 0 item count in the GSI. I was able to fix the issue by deleting the GSI and creating it again. The composite key was not created so I thought I should raise it, in case it's not an isolated issue.
