### ISSUE TITLE
Add text when building queries and mutations in the Appsync Console is slow and then misses chars

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#5356]
It is great that you can now easily construct queries and mutations via the console. 
When typing text on the left side then it misses chars when typing too fast.

<img width="1281" alt="Screenshot 2020-09-18 at 13 24 13" src="https://user-images.githubusercontent.com/21346629/93592560-ac64bf00-f9b2-11ea-8c54-c7aac38e8da5.png">

**Comment by UnleashedMind** [comment]
This issue is not for the Amplify CLI but for the AppSync Console, I've notified them about the issue.
