### ISSUE TITLE
modelgen bug with Has One @connection relation with an explicit field 

### ISSUE THREAD

**Issue by iartemiev** [aws-amplify/amplify-cli#5358]
**Describe the bug**
Related to this issue in JS: https://github.com/aws-amplify/amplify-js/issues/6560

`amplify codegen models` is incorrectly handling Has One relations. The `associatedWith` field is not being set to the field specified in the `fields` argument.

The following model:
```graphql
type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}
```

Gets modelgen'd to
```js
"Project": {
    "name": "Project",
    "fields": {
        "id": {
            "name": "id",
            "isArray": false,
            "type": "ID",
            "isRequired": true,
            "attributes": []
        },
        "name": {
            "name": "name",
            "isArray": false,
            "type": "String",
            "isRequired": false,
            "attributes": []
        },
        "teamID": {
            "name": "teamID",
            "isArray": false,
            "type": "ID",
            "isRequired": true,
            "attributes": []
        },
        "team": {
            "name": "team",
            "isArray": false,
            "type": {
                "model": "Team"
            },
            "isRequired": false,
            "attributes": [],
            "association": {
                "connectionType": "HAS_ONE",
                "associatedWith": "id"
            }
        }
    },
    "syncable": true,
    "pluralName": "Projects",
    "attributes": [
        {
            "type": "model",
            "properties": {}
        }
    ]
},
```

**Amplify CLI Version**
`4.29.2`

**To Reproduce**
Run `amplify codegen models` on the following schema:
```graphql
type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}

type Team @model {
  id: ID!
  name: String!
}
```

**Expected behavior**
I would expect that `team: Team @connection(fields: ["teamID"])` should result in:

```js
"team": {
    "name": "team",
    "isArray": false,
    "type": {
        "model": "Team"
    },
    "isRequired": false,
    "attributes": [],
    "association": {
        "connectionType": "HAS_ONE",
        "associatedWith": "teamID"
    }
}
```

**Comment by AaronZyLee** [comment]
I think the `associateWith` field is meant to annotate the name of connected field of the connected model. If we want to refer `teamID`, the convention of the current implementations is to use `targetName`. However, I notice this one only exists inside `BELONGS_TO` relation but not `HAS_ONE` and `HAS_MANY`. I think this should be clarified before fixing the bug.

**Comment by AaronZyLee** [comment]
I just find an interesting thing on the difference between `BELONGS_TO` and `HAS_ONE`. According to this [post](https://stackoverflow.com/questions/3808926/whats-the-difference-between-belongs-to-and-has-one), it says 

> To determine who "has" the other object, look at where the foreign key is. We can say that a `User` "has" a `Profile` because the profiles table has a `user_id` column.

After checking the [amplify docs](https://docs.amplify.aws/cli/graphql-transformer/directives#connection), this is the case for A `HAS_MANY` Bs and B `BELONGS_TO` A. In contrast, `BELONGS_TO` is not mentioned in `HAS_ONE` section. If we take the prerequisite above, we can find that Team actually `HAS_ONE` Project and Project `BELONGS_TO` Team, which is just the opposite to the current output.

Hence, I think the correct output should result in:
```
"team": {
    "name": "team",
    "isArray": false,
    "type": {
        "model": "Team"
    },
    "isRequired": false,
    "attributes": [],
    "association": {
        "connectionType": "BELONGS_TO",
        "targetName": "teamID"
    }
}
```

**Comment by iartemiev** [comment]
Thanks for giving this some thought, @AaronZyLee. I agree with the conclusion you reached. It seems consistent with how other relations are treated.

**Comment by iartemiev** [comment]
Bump

**Comment by lawmicha** [comment]
this is similiar on the iOS side https://github.com/aws-amplify/amplify-cli/pull/6031 where i've added targetName for this scenario
