### ISSUE TITLE
amplify publish -  fails to upload assets to s3

### ISSUE THREAD

**Issue by subratamazumder** [aws-amplify/amplify-cli#5363]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After adding hosting by `amplify add hosting` when `amplify publish` was run below error occurred saying 
```
Cannot find the distribution folder.
Error: Cannot find the distribution folder.
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

subratas-mbp  ~/workspace/react-amplified   master ●  amplify -v
4.29.2
 subratas-mbp  ~/workspace/react-amplified   master ● 

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Perform these [steps](https://docs.amplify.aws/start/getting-started/hosting/q/integration/react)
**Expected behavior**
S3 upload should happen without any issues.

**Screenshots**
See error details below
```
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
frontend build command exited with code 0
Publish started for S3AndCloudFront

Cannot find the distribution folder.
Distribution folder is currently set as:
  /Users/subratamazumder/workspace/react-amplified/build

Cannot find the distribution folder.
Error: Cannot find the distribution folder.
    at Object.scan (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-scanner.js:38:11)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Mac
 - Node Version. You can use `node -v` to check the node version on your system
 subratas-mbp  ~/workspace/react-amplified   master ●  node -v
v12.18.0
 subratas-mbp  ~/workspace/react-amplified   master ● 

**Additional context**
**Workaround**
As of now the workaround is to run `npm run build` to create this missing `build` directory.
And then run `amplify publish` to re-upload all `build\*` to configured s3 bucket.
**Probable Root Cause** : `amplify publish` is running `npm build` just before uploading s3 content, should have run `npm run build` instead.

**Comment by UnleashedMind** [comment]
The build command by default is "npm run-script build" and they are set during `amplify init`. 
You can still modify it after `amplify init` by running `amplify configure project`
