### ISSUE TITLE
amplify auth console cli command not working

### ISSUE THREAD

**Issue by donofriov** [aws-amplify/amplify-cli#5364]
**Describe the bug**
An error is thrown when running the `amplify auth console` command:
```
Error: File at path: '/Users/vdonofrio/.nvm/versions/node/v12.18.4/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/lib/provider-utils/supported-services.json' does not exist
```

I've verified that the JSON file does not exist but a JS file does

![image](https://user-images.githubusercontent.com/4457953/93707529-d5f72500-fb2f-11ea-9a55-c6c4ebf1fa96.png)

**Amplify CLI Version**
```
❯ amplify -v
4.29.2
```

**To Reproduce**
Note: The nvm steps are unnecessary, I reproduced a second time on a fresh node and amplify/cli install to verify the issue

1. nvm install 12.18.4
2. nvm alias default 12.18.4
3. npm i -g @aws-amplify/cli
4. amplify init 
5. amplify add auth
6. amplify push
7. amplify console auth

**Expected behavior**
Running `amplify console auth` should open the auth section of the amplify backend app in the AWS console

**Screenshots**
![image](https://user-images.githubusercontent.com/4457953/93707698-291da780-fb31-11ea-82ce-85f1b2300200.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version:
```
❯ node -v
v12.18.4
```

**Additional context**
The `amplify console` command is working and opening the AWS console from the terminal to the amplify app backend Overview tab

**Comment by aeflorezm** [comment]
I am having the exact same issue, it has been working fine and today I tried to open the auth console and got the same error.

**Comment by Fantaztig** [comment]
As a workaround you can JSON.stringify the object exported inside the supported-services.js and save the result in a supported-services.json
