### ISSUE TITLE
How to debug and invoke amplify lambda function efficiently?

### ISSUE THREAD

**Issue by betimer** [aws-amplify/amplify-cli#5365]
**Which Category is your question related to?**

amplify function

**Issue**

So far, every time I want to test the amplify function, I have to wait until `amplify push`, and if there is even a typo, I have to run the command again to check the result.

Is there any way I can invoke the function remotely immediately when developing? (Similar to lambda console, where I can test, but I found after `amplify push` the console complaint its size and does not allow me to edit online)

After `amplify push`, I cannot access the lambda function on console anymore due to the size issue below. (any way I can fix the size issue?)

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.29.2

**What AWS Services are you utilizing?**

API, function

**Provide additional details e.g. code snippets**
![image](https://user-images.githubusercontent.com/8111748/93709298-a4f31080-fb80-11ea-8ea2-a7b8df567b63.png)

**Comment by UnleashedMind** [comment]
You can test the function locally using amplify mock
https://docs.amplify.aws/cli/usage/mock#function-mocking-setup
