### ISSUE TITLE
"amplify push" : stop asking confirmation for generating types

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#5366]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I run "amplify push", wait 10 seconds for Amplify to confirm changes, then another 10-20seconds to have another confirmation if I want to generate types. Sometimes I forget this step and come back after a few minutes, thinking Amplify have sync my changes with the cloud, but no because I didn't confirm this step!

**Describe the solution you'd like**
Add a flag to automatically confirm steps.

**Describe alternatives you've considered**
remove the confirmation for generating types.

**Comment by jhockett** [comment]
Hi @anisg, you can use the yes flag! `amplify push -y`
