### ISSUE TITLE
Push Error - Internal Server Error

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#5368]
**Describe the bug**

When I'm pushing with a significant amount of change I find that the system will fail with an undefined internal error. In this case I'm using the Cloud9 (Linux) IDE to push and I've made a significant number of changes to my schema and resolvers (days of work involved in the changes). I perform the compile first and that is successful, and the push proceeds for a long time and the only error that comes back is this:
----------------------------------------------------------------------------
✖ An error occurred when pushing the resources to the cloud

Internal server error
An error occurred during the push operation: Internal server error 
----------------------------------------------------------------------------

So I'm somewhat stuck here.

**Amplify CLI Version**
4.29.2

**Expected behavior**
Clean push to cloud

**Comment by sacrampton** [comment]
I've continued to work this and have identified where it is breaking. I have a query that looks like this:

```
  searchDocumentsX(
    mustMatch: [SearchableDocumentsMatchFilterInput],
    mustMatchKeyword: [SearchableDocumentsMatchFilterInput],    
    mustExists: [SearchableDocumentSortableFields],
    mustQueryString: [SearchableDocumentsQueryStringFilterInput],
    mustNotMatch: [SearchableDocumentsMatchFilterInput],
    mustNotMatchKeyword: [SearchableDocumentsMatchFilterInput],
    mustNotExists: [SearchableDocumentSortableFields],
    mustNotQueryString: [SearchableDocumentsQueryStringFilterInput],
    rangeSingle: [SearchableDocumentsRangeSingleFilterInput],
    rangeDual:[SearchableDocumentsRangeDualFilterInput],
    searchAfter: [String],
    limit: Int,
    sort: [SearchableDocumentSortInput],
    from: Int ): SearchableDocumentConnection
```

And I modify it to look like this.

```
  searchDocumentsX(
    mustMatch: [SearchableDocumentsMatchFilterInput],
    mustMatchKeyword: [SearchableDocumentsMatchFilterInput],    
    mustExists: [SearchableDocumentSortableFields],
    mustQueryString: [SearchableDocumentsQueryStringFilterInput],
    mustNotMatch: [SearchableDocumentsMatchFilterInput],
    mustNotMatchKeyword: [SearchableDocumentsMatchFilterInput],
    mustNotExists: [SearchableDocumentSortableFields],
    mustNotQueryString: [SearchableDocumentsQueryStringFilterInput],
    rangeSingle: [SearchableDocumentsRangeSingleFilterInput],
    rangeDual:[SearchableDocumentsRangeDualFilterInput],
    orMustMatch: [SearchableDocumentsMatchFilterInput],
    orMustMatchKeyword: [SearchableDocumentsMatchFilterInput],
    orMustExists: [SearchableDocumentSortableFields],
    orMustQueryString: [SearchableDocumentsQueryStringFilterInput],
    orMustNotMatch: [SearchableDocumentsMatchFilterInput],
    orMustNotMatchKeyword: [SearchableDocumentsMatchFilterInput],
    orMustNotExists: [SearchableDocumentSortableFields],
    orMustNotQueryString: [SearchableDocumentsQueryStringFilterInput],
    orRangeSingle: [SearchableDocumentsRangeSingleFilterInput],
    orRangeDual:[SearchableDocumentsRangeDualFilterInput],       
    searchAfter: [String],
    limit: Int,
    sort: [SearchableDocumentSortInput],
    from: Int ): SearchableDocumentConnection  
```

I had 45 resolvers where I am making this change. I started doing these changes 1 by 1 and got about 10 successfully pushed - but now I can't push any more of them and get the Internal Server Error.

**Comment by ammarkarachi** [comment]
Hi @sacrampton, It looks like your credentials are expiring while the push is taking place. How are you managing your credentials?

**Comment by sacrampton** [comment]
Hi @ammarkarachi - I log into my AWS Cloud9 environment with my IAM user account. I believe Cloud9 caches credentials - I know if I do something "aws configure" it has no impact on the credentials in Cloud9.

By the way, I've been using Cloud9 to push for the last year and never had any issue with this.

**Comment by sacrampton** [comment]
Hi @ammarkarachi - I am sure the Internal Server Error is unrelated to credentials. I can log in with fresh credentials and execute the push and within 2 minutes of having the login and fresh credentials I get this Internal Server Error.

**Comment by sacrampton** [comment]
Hi @ammarkarachi - I tried another thing (create the query rather than update). So I removed the old query and pushed successfully, then added the new query back in but it fails on push. 

Is there any way I can find out more on what is causing this Internal Server Error?

**Comment by sacrampton** [comment]
Hi @ammarkarachi / @UnleashedMind - following on from previous comment, I reverted to the original query and it successfully pushed.

**Comment by ammarkarachi** [comment]
@sacrampton from the text file that was edited out I could see that when the cli tries query for stack updates and at that point it returns an error, any more context would be helpful

**Comment by sacrampton** [comment]
Hi @ammarkarachi - I removed that because it was distracting from the issue. That only happened after I edited the cloudformation-template.json to insert some DependsOn items. The core of the issue is that I'm getting this error when I do a push:

✖ An error occurred when pushing the resources to the cloud
Internal server error
An error occurred during the push operation: Internal server error


My process is to execute the following:

> amplify api gql-compile --minify
> Edit searchableStack.json to remove batch limitation (#4695)
> amplify push --no-gql-override --yes

As I showed above (https://github.com/aws-amplify/amplify-cli/issues/5368#issuecomment-696179104) I have now narrowed this down - if I make this change detailed in this comment then I get the Internal Server Error. I have 45 queries that I'm trying to modify - all generally identical - I started doing them 1 by 1 and that was working - but now I can't do any more.

**Comment by ammarkarachi** [comment]
The other thing I would generally do when pushing a stack is look at the Cloudformation events tab and see where the stack has encountered an error.

**Comment by sacrampton** [comment]
Hi @ammarkarachi  - the Events tab shows that everything seems to be completing without issue and that it fails right at the end of the process. I've included Events Tab and also screen shot of Cloud9 environment.

![cloudFormationEvents](https://user-images.githubusercontent.com/6362888/93831017-1af89400-fcb5-11ea-9801-78e4364aaed5.png)

![cloud9InternalServerError](https://user-images.githubusercontent.com/6362888/93831192-8e9aa100-fcb5-11ea-8d4d-2d0bfcb77008.png)

**Comment by sacrampton** [comment]
Hi @ammarkarachi / @UnleashedMind - I have got some more testing results. From the results I included here (https://github.com/aws-amplify/amplify-cli/issues/5368#issuecomment-696432670) it seems like the push is working completely in terms of updating the API. I also noted that after the failure there was no rollback happening on cloudformation. So I tested the results of the push - if I log into the AppSync Console I can see the filters available BEFORE I push - then AFTER the push all the additional filters are there indicating that the API is successfully getting updated.

So hopefully that isolates where in the process the crash is occurring - and maybe there is a workaround to manually put the files where they need to be given that the API itself is actually being updated successfully before the crash

![BeforePush](https://user-images.githubusercontent.com/6362888/93941084-0aa5ef00-fd71-11ea-8cff-ca1dc7e55435.jpg)

![AfterPush](https://user-images.githubusercontent.com/6362888/93941082-0974c200-fd71-11ea-85f6-b6081ace0563.jpg)

**Comment by sacrampton** [comment]
Hi @ammarkarachi @UnleashedMind - I have done some more testing here with checking the deployment bucket. When I do a push the following files are written to the deployment bucket before the crash.

- amplify-appsync-files/<folder>/resolvers/*
- amplify-appsync-files/<folder>/stacks/*
- amplify-appsync-files/<folder>/functions/*
- amplify-appsync-files/<folder>/schema.graphql
- amplify-appsync-files/<folder>/cloudformation-template.json
- amplify-appsync-files/<folder>/parameters.json
- nested-cloudformation-stack.yml
- amplify-cfn-templates/api/cloudformation-template.json

The #current-cloud-backend.zip file is not updated

**Comment by sacrampton** [comment]
Hi @ammarkarachi  @UnleashedMind - some more here. From last successful push, these files were created, but are not created in the deployment bucket when the push fails with this Internal Server Error issue.

- #current-cloud-backend.zip
- amplify-meta.json
- backend-config.json

My most recent successful push generates a very large #current-cloud-backend.zip - 5.3MB (5,300,214 bytes). Maybe we are running into some size limitation for generating this zip file because that appears to be where it is failing in the process.

**Comment by sacrampton** [comment]
Hi @ammarkarachi @UnleashedMind 

Are there any work arounds for this? It seems that the #current-cloud-backend folder in my project is being updated before anything crashes. Is there anything I can do to investigate this further? This is happening in my dev environment, but until I resolve this I can't push to TEST and then eventually to production.

Thanks

**Comment by sacrampton** [comment]
Hi @ammarkarachi  @UnleashedMind 

Is there any input that you might have on this? I'm looking for a work around to get this moving. The push seems to be updating the api correctly, but I can't move forward till I understand why this Internal Server Error is occurring and how we resolve it.

Thanks

**Comment by ammarkarachi** [comment]
@sacrampton Thanks for the updates this I believe this is failing before it gets a successful, I have tried uploading a rather large zip file > 10 MB too from my end but it doesn't look like it's failing there.

**Comment by ammarkarachi** [comment]
We are investigating right now to get you unblocked as soon as possible

**Comment by sacrampton** [comment]
Hi @ammarkarachi - is there anything I can be doing to provide further input / testing to help isolate the problem?

**Comment by ammarkarachi** [comment]
Hi @sacrampton Can you IM me on discord this way we can talk one on https://discord.gg/z8JFF9

**Comment by sacrampton** [comment]
Hi @ammarkarachi  / @UnleashedMind 

I am really confident that this Internal Server Error is occurring in the clean up process at the end of the successful push to CloudFormation. When I do the push all the updates are functioning exactly as specified in the API. I am primarily updating resolvers in this push and when I do that CloudTrail shows all of the resolvers are successfully pushed. I even set up a brand new Cloud9 environment and did the push from there with exactly the same result so its not happening on the client side.

I previously (https://github.com/aws-amplify/amplify-cli/issues/5368#issuecomment-698055503) identified which files were being updated in S3 as a result of the push and which were not.

So my question is what is happening in the clean up - how can I check - and how can I manually work around the clean up to get past this? I'm still dead in the water of being able to push my changes to Test & Prod environments until I can resolve this.

**Comment by sacrampton** [comment]
Hi @ammarkarachi @undefobj @UnleashedMind 

I went to a separate account to see if there was anything specific to the account that might have been causing a problem. 

It is still crashing at the final cleanup stage. Here is what I see

![testPush](https://user-images.githubusercontent.com/6362888/95144872-76527800-07c5-11eb-803e-9e42f500803b.png)

I've been dead in the water here for over 2 weeks and can't move forward and need to get changes to the schema through to my production environment. I've tried logging through AWS Support too, but they defer to you guys here. Am getting desperate to resolve this. Work arounds are fine - but at the moment I'm just dead in the water and haven't progressed at all in a week. Help!!!

**Comment by sacrampton** [comment]
Just updating this in case anyone else is having this problem.

When you use the codegen option amplify generates a hidden file called  .graphqlconfig.yml in the root of your project. This file is what is causing the issues identified here. Before you push make sure you delete this file and the push works successfully.

**Comment by yuth** [comment]
We have update the codegen to just print a warning message when codegen fails during push

https://github.com/aws-amplify/amplify-cli/blob/7cbd39632181a5bc323ac3ad3a835a358c74adf6/packages/amplify-codegen/src/callbacks/postPushCallback.js#L36-L41

Feel free to re-open/comment here if the issue still persists
