### ISSUE TITLE
Trigger Lambda function to process data in S3 and load in DynamoDB

### ISSUE THREAD

**Issue by robertosannazzaro** [aws-amplify/amplify-cli#5369]
As suggested on the discord server I am opening an issue here:

**Which Category is your question related to?**
Amplify Trigger function between S3 and DynamoDB

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
- Amplify
- S3
- Cognito
- DynamoDB

**Provide additional details e.g. code snippets**

I am trying to tackle this situation: I upload a .csv file to S3, then I want to trigger a Lambda function (possibly in python) that read this .csv file and put its content into DynamoDB. I created all the resources, however, when I try to give permissions to my trigger function to read dynamo I get this error from the CLI: Error: Cannot add S3Trigger4f853757 due to a cyclic dependency. 
At the same time, if I create a Lambda trigger, it seems that I am only allowed to use Node.js and not python, since the CLI is not asking about the language.

** Steps to reproduce: **
- Init an `npx create-react-app ` project along with `amplify init`

<img width="689" alt="Screenshot 2020-09-21 at 13 46 56" src="https://user-images.githubusercontent.com/32909143/93763001-ecc17880-fc10-11ea-926b-f20a41fb9d2d.png">

- `amplify add storage`

<img width="1257" alt="Screenshot 2020-09-21 at 14 12 16" src="https://user-images.githubusercontent.com/32909143/93765000-76bf1080-fc14-11ea-9d64-f6de8f6e484e.png">

- `amplify add storage`

<img width="1299" alt="Screenshot 2020-09-21 at 14 13 02" src="https://user-images.githubusercontent.com/32909143/93765062-90f8ee80-fc14-11ea-83bc-5c29870dc51e.png">

- `amplify configure function`

<img width="1309" alt="Screenshot 2020-09-21 at 14 13 51" src="https://user-images.githubusercontent.com/32909143/93765143-aec65380-fc14-11ea-9957-f85b9a334a4f.png">

**Comment by ammarkarachi** [comment]
@robertosannazzaro The S3 bucket depends on the Lambda function and the lambda function has access to these actions ```                                "s3:PutObject",
                                "s3:GetObject",
                                "s3:ListBucket",
                                "s3:DeleteObject"``` . My suggestion is to try adding the dynamo db access and pushing

**Comment by robertosannazzaro** [comment]
Hi, @ammarkarachi thanks for your answer and the time you spent 😀

I am not sure what do you mean: I added the dynamo DB access in the `amplify configure function`.

Could you please elaborate more?

**Comment by ammarkarachi** [comment]
@robertosannazzaro The trigger lambda should already have access to the S3 bucket through it's execution policy you would have to add only dynamo db permissions

**Comment by robertosannazzaro** [comment]
I understand, thanks @ammarkarachi. However, now another doubt emerges: if I create a trigger function, by default the function is in Node.js. It seems that the CLI does not give the possibility to choose in which language to have the function.

Is there a way to change this and switch to Python?

**Comment by robertosannazzaro** [comment]
Hi @ammarkarachi should I move this last question to another issue?

**Comment by ammarkarachi** [comment]
@robertosannazzaro yes that would be better I can close this issue and you can track updates on that issue.

**Comment by dhaval512** [comment]
hi , @robertosannazzaro  i am facing the same issue ?
is issue resolved for you ?
