### ISSUE TITLE
Shared environment overrides current environment   

### ISSUE THREAD

**Issue by Northshoot** [aws-amplify/amplify-cli#5371]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
New team member added or clone to new location:

Amplify it overrides `amplify/team-provider-info.json` but it should not

```
git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   amplify/team-provider-info.json
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.29.2

**To Reproduce**

- Create an amplify react-native app with backend. deploy, push to git and amplify.
- clone to new directory
- amplify init
- select to use existing environment 
- check git status

**Expected behavior**
Initiation in new location and working on shared environment 
amplify/team-provider-info.json is *not* modified

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
Tested on Mac and Windows

 - Node Version. You can use `node -v` to check the node version on your system
❯ node -v
v14.7.0

**Additional context**
Followed the guidelines on https://docs.amplify.aws/cli/teams/shared

Current workout around it to run

`git reset --hard `

before continuing operations. But the bug is dangerous as it can blow up whole infrastructure if not paying attention.

**Comment by ammarkarachi** [comment]
@Northshoot Can you provide us with diff between the two files redacting any sensitive information?

**Comment by Northshoot** [comment]
sure, interesting. It does only show difference in indentation

`diff --git a/amplify/team-provider-info.json b/amplify/team-provider-info.json
index d70a2e8..6ca56a0 100644
--- a/amplify/team-provider-info.json
+++ b/amplify/team-provider-info.json
@@ -1,21 +1,21 @@
 {
-    "dev": {
-        "awscloudformation": {
-            "AuthRoleName": "amplify-appname-dev-id-authRole",
-            "UnauthRoleArn": "arn:aws:iam::123456789010:role/amplify-appname-dev-id-unauthRole",
-            "AuthRoleArn": "arn:aws:iam::123456789010:role/amplify-appname-dev-id-authRole",
-            "Region": "region",
-            "DeploymentBucketName": "amplify-appname-dev-id-deployment",
-            "UnauthRoleName": "amplify-appname-dev-id-unauthRole",
-            "StackName": "amplify-appname-dev-id",
-            "StackId": "arn:aws:cloudformation:region:123456789010:stack/amplify-appname-dev-id/uuid",
-            "AmplifyAppId": "app_id"
-        },
-        "categories": {
-            "auth": {
-                "appname_id": {},
-                "userPoolGroups": {}
-            }
-        }
+  "dev": {
+    "awscloudformation": {
+      "AuthRoleName": "amplify-appname-dev-id-authRole",
+      "UnauthRoleArn": "arn:aws:iam::123456789010:role/amplify-appname-dev-id-unauthRole",
+      "AuthRoleArn": "arn:aws:iam::123456789010:role/amplify-appname-dev-id-authRole",
+      "Region": "region",
+      "DeploymentBucketName": "amplify-appname-dev-id-deployment",
+      "UnauthRoleName": "amplify-appname-dev-id-unauthRole",
+      "StackName": "amplify-appname-dev-id",
+      "StackId": "arn:aws:cloudformation:region:123456789010:stack/amplify-appname-dev-id/uuid",
+      "AmplifyAppId": "app_id"
+    },
+    "categories": {
+      "auth": {
+        "appname_id": {},
+        "userPoolGroups": {}
+      }
     }
+  }
 }` 

However, devs were getting this output after pulling, making it all confusing:

![init-failed](https://user-images.githubusercontent.com/7857361/93811751-9fe49e80-fc1e-11ea-89a3-8f87b2e160be.png)

The entries seem to be double both create and update. Would the spacing do that? 

Trying running it is could not find the env. 

![init-failed](https://user-images.githubusercontent.com/7857361/93811873-cd314c80-fc1e-11ea-9745-8ea8d7242952.png)

**Comment by ammarkarachi** [comment]
Are the credentials able to access the same stack on the account?

**Comment by Northshoot** [comment]
environment does not exist was resulted by aws profile having a different region. 
would region be part of ` amplify/team-provider-info.json` ?
However, the file change still occurs and requires git commit. Is that intentional change?

**Comment by ammarkarachi** [comment]
Does the code editor on the machines have different configurations for tabs vs spaces?

**Comment by Northshoot** [comment]
we tested that on three different machines, the file was never been edited by hand.

**Comment by ammarkarachi** [comment]
@Northshoot I will mark this as a bug and we will have a fix out soon

**Comment by Northshoot** [comment]
thank you!

**Comment by ammarkarachi** [comment]
@Northshoot would you know around what time did you initialize the project? I can see that we have our indentation for writing these files set to two spaces. It could be that accepting the indent would not change it further
