### ISSUE TITLE
AppSync mock oidc issuer check does not take ending forward slash into consideration.

### ISSUE THREAD

**Issue by Jhorlin** [aws-amplify/amplify-cli#5372]
**Describe the bug**
When creating an appsync authentication provider using amplify-cli it forces you to use a trailing "/" when entering the address of the issuer. When using mock and authenticating in your app, not GraphiQL, and calling out using oidc as the authentication type example:
```typescript
const params = queryString.parse(hash);
        const token = await parseJWT(params.id_token as string);
        cache.setItem(
          "federatedInfo",
          { token: params.id_token },
          { expires: token.exp * 1000 }
        );
        setToken(token);
        const response = await API.graphql({
          query: getStuff ,
          authMode: GRAPHQL_AUTH_MODE.OPENID_CONNECT,
          variables: { code: params.code },
        }) as GraphQLResult<getStuffQuery>
```
The issuer expected in appsync mock must end with a forward slash because it was enforced when creating the appsync authentication provider, but the issuer that is sent does not contain a forward slash causing this to fail. If you create a google oidc in your appsync project and configure https://accounts.google.com/ amplify will send https://accounts.google.com.
This will cause the check to fail [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/utils/auth-helpers/helpers.ts#L33) since it must be an exact match.

**Amplify CLI Version**
4.29.2

**To Reproduce**
1. Create a graphql API with an OICD, I have the same issue with google or microsoft.
2. Run `amplify mock`
3. Attempt to call the endpoint using OIDC as your authentication mode in a client app not GraphiQL

**Expected behavior**
I expect the oidc configured query to allow access to my application.

**Desktop (please complete the following information):**
 - OS: Ubuntu/Pop!_OS
 - Node Version. v14.11.0

**Additional context**
I think amplify-appsync-simulator should test for the issue and ignore the trailing forward slash or use a regex where it is optional.

**Comment by safonovklim** [comment]
@attilah this fix introduced bug for Auth0 clients.

Token Payload:

```
{
  iss: 'https://xxxxxx.auth0.com/',
  sub: 'auth0|xxxxxx',
  aud: 'xxxxxx',
  iat: xxxxxx,
  exp: xxxxxx,
  azp: 'xxxxx',
  scope: 'read write',
  gty: 'password'
}
```

oidcIssuers:

```
[
  "https://xxxxxx.auth0.com"
]
```

![image](https://user-images.githubusercontent.com/9365521/104242315-0f9dc400-5470-11eb-924b-7b818b487e4d.png)


As result,
`node_modules/amplify-appsync-simulator/lib/utils/auth-helpers/helpers.js` -> `isValidOIDCToken()` always return false for AUTH0 tokens

**Comment by safonovklim** [comment]
@yuth can you please review this PR?

Previous change to this file was: https://github.com/aws-amplify/amplify-cli/pull/5434
