### ISSUE TITLE
AccessDenied error appeared after deploy amplify project

### ISSUE THREAD

**Issue by Liguo-Ma** [aws-amplify/amplify-cli#5375]
I am using the lastest verison amplify
Also,I have uploaded my amplify project.
https://prod.d3kb4db9ojlfvl.amplifyapp.com/
This is my site.
It works file and redirect to signing page.
https://prod.d3kb4db9ojlfvl.amplifyapp.com/signin/
So this site works well.
But If I redirect this site so if I click F5 I get "AccessDenied" error.
What is the solution for this error?

**Comment by ammarkarachi** [comment]
@Liguo-Ma Can you elaborate on steps to reproduce this error? any more context will be helpful

**Comment by Liguo-Ma** [comment]
I have deployed amplify + ionic project with amplify publish
I used the manually method.
But the result is bad as above.
Signin page from main domain run fine.
But call signing page directly do not work 
![image](https://user-images.githubusercontent.com/59509767/93915886-e0cdd780-fd32-11ea-9136-9121c2a38681.png)
I get this error

**Comment by ammarkarachi** [comment]
@Liguo-Ma There is an identical issue in Amplify console if you would like to https://github.com/aws-amplify/amplify-console/issues/1058 receive updates from there

**Comment by Liguo-Ma** [comment]
@ammarkarachi  So what is the solution?

**Comment by Liguo-Ma** [comment]
use this rewrite and redirection
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]

**Comment by Liguo-Ma** [comment]
I think Amplify developers avoid this issue.
Why we should set this rule.
It could be more stress than firebase.
I want Amplify to be bigger and to be more flexible
