### ISSUE TITLE
Amplify CLI allows creation of duplicate REST API path

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#5379]
**Describe the bug**

Amplify CLI allows creation of duplicate REST API path

**Amplify CLI Version**

v4.28

**To Reproduce**

- `amplify add api` -> add a `/items` REST endpoint
- `amplify add api` -> add a `/items` REST endpoint again, observe there is no error

**Expected behavior**

should error the second time

**Screenshots**

this looks like its a risk of being a bad time...

![image](https://user-images.githubusercontent.com/6764957/93931713-bd665500-fd51-11ea-852a-3233c63f36db.png)

no error seen on amplify status either

![image](https://user-images.githubusercontent.com/6764957/93931468-66f91680-fd51-11ea-9a6e-6a8349719916.png)

**Comment by ammarkarachi** [comment]
@sw-yx We do have a warning for catch all paths for overlapping paths
` This path /items is overlapping with /items. /items is going to catch all requests from /items. Are you sure you want to continue? `

**Comment by edwardfoyle** [comment]
@sw-yx Are they duplicate paths on separate API Gateway APIs? If so, there shouldn't be any conflict as the hostname for each API is unique.

**Comment by sw-yx** [comment]
i understand how this is permissible under the current APIG model, but i'm also saying that this isnt a good developer experience for people who don't know any better. as a user i expect each path to be unique, and that when i make a mistake, the tool i use helps me do the right thing instead of creating a hard-to-debug situation like this nobody wants.

**Comment by edwardfoyle** [comment]
@sw-yx Do you think the appropriate fix would be to only allow one REST API resource in the project, similar to how the CLI only allows one GraphQL API?

**Comment by sw-yx** [comment]
@edwardfoyle  i think that is one way to do it, yes, but why did we not implement that in the first place? what are the tradeoffs? (i honestly cant think of any)

**Comment by renebrandel** [comment]
I think what's happening here is actually a DX issue. When you add a new API, it should provide you the option to add new paths to an existing REST API or add a new REST API. 

Something in the direction of this is probably better. A DX sample could be:
```bash
> amplify add api
GraphQL API
REST API
New path to an existing REST API --> shortcuts into amplify update api with the path question
```
