### ISSUE TITLE
Functions keeps layers ressource arn of other env

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-cli#5382]
**Describe the bug**
I have my dev env with a layer and 4 versions. My function "superFunction" is using layer v4 on dev.
When I switch to env test, I have no layer yet. My function "superFunction" keeps referencing layer v4 on dev. Problem is my test env is in another aws account so I don't have access to it. 

**Amplify CLI Version**
4.29.2

**To Reproduce**
1. Create layer and update it bunch of times to have multiple version
2. Switch to a new env on a different aws account.
3. Deploy and try to launch lambda

**Expected behavior**
In this example, I expect amplify to create a layer-test-v1 and change function's cloudformation to reference this layer version. Or let the choice to the user so we can choose to create layer on the other account and reference this one.

**Comment by ammarkarachi** [comment]
@SebSchwartz This enhancement is still in the works but after creating a lambda you would have to update the Arn manually for the new environment Lambda.

**Comment by SwaySway** [comment]
Closing this issue in favor of #5479. Please follow that issue for updates.
