### ISSUE TITLE
Subscribing to Batch Mutations (w/ BatchPutItem resolver)

### ISSUE THREAD

**Issue by jbertman** [aws-amplify/amplify-cli#5383]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
GQL Subscriptions

**Amplify CLI Version** 
4.29.2

**What AWS Services are you utilizing?**
Amplify, GQLT, Lambda, DDB

**Provide additional details e.g. code snippets**
I have a custom batch mutation that takes a list of inputs. It also receives an identifier, to be used by the accompanying subscription:

```
type Mutation {
    batchCreateThings(someId: ID!, things: [CreateThingInput!]!): [Thing] @aws_iam
}
```
The subscription looks like this:

```
type Subscription {
    onCreateThings: [Thing]
    @aws_cognito_user_pools
    @aws_subscribe(
        mutations: [
            "batchCreateThings"
        ]
    )
}
```

This works fine, I receive all batch changes. But when I try to add the subscription filter:

```
type Subscription {
    onCreateThings(someId: ID!): [Thing]
    @aws_cognito_user_pools
    @aws_subscribe(
        mutations: [
            "batchCreateThings"
        ]
    )
}
```
I can't get the subscription to fire. I retro-fitted the resolver with the `someId` input more recently than the resolver was created, do any changes need to be made to the resolvers? Or maybe return a connection-like model rather than a list of Things?

Mutation.batchCreateThings.req.vtl
```
#foreach($thing in ${ctx.args.things})
  ## [SNIP] Other Auth Rules
    ## [Start] Throw if unauthorized **
    #if( !($isStaticGroupAuthorized == true || $isDynamicGroupAuthorized == true || $isOwnerAuthorized == true) )
      $util.unauthorized()
    #end
    ## [End] Throw if unauthorized **
  #end
  ## [End] Check authMode and execute owner/group checks **
#end

#set($thingsData = [])
#foreach($thing in ${ctx.args.things})
  $util.qr($thing.put("createdAt", $util.time.nowISO8601()))
  $util.qr($thing.put("updatedAt", $util.time.nowISO8601()))
  $util.qr($thing.put("__typename", "Thing"))
  $util.qr($thing.put("id", $util.defaultIfNullOrBlank($thing.id, $util.autoId())))
  $util.qr($thingsData.add($util.dynamodb.toMapValues($thing)))
#end

{
  "version": "2018-05-29",
  "operation": "BatchPutItem",
  "tables": {
    "$ctx.stash.thingTableName": $utils.toJson($thingsData)
  }
}
```

Mutation.batchCreateThings.res.vtl
```
#if ($ctx.error)
    $util.appendError($ctx.error.message, $ctx.error.type, null, $ctx.result.data.unprocessedKeys)
#end

$util.toJson($ctx.result.data.get($ctx.stash.thingTableName))
```

**Comment by ammarkarachi** [comment]
@jbertman The payload of  the mutation is an array of `thing`s we can do a strict equality of such values but can't peek into the content of the payload. Filtering by id would not be possible

**Comment by jbertman** [comment]
Is there a solution where the return type can be a model like the generated connection models instead of `[Thing]`?

```
type ThingResponse {
  someId: ID!
  items: [Thing]
}
```
With a change in the mutation:
```
type Mutation {
    batchCreateThings(someId: ID!, things: [CreateThingInput!]!): ThingResponse @aws_iam
}
```

Sorry if this question doesn't make sense, I don't have much exposure to AppSync

**Comment by ammarkarachi** [comment]
@jbertman I am guessing you are trying to abstract the payload into another model but the question, the ID comparison is still out of scope.

**Comment by jbertman** [comment]
@ammarkarachi Hm.. any workarounds that come to mind? Really need this kind of functionality. Is there a performant way to break up the results and ship them off to a subscription? Or a different way I could do the batch put?

**Comment by silviuglv** [comment]
I'm trying to solve the exact same issue but after some digging online it looks like it might not be possible atm. 

It looks like the subscription does strict equality against the mutation resolved data, I guess, when using arguments, something like this:

```
type Subscription {
  onCreateThing(someId: ID!): Thing
}

// The way the subscription filters the resolved values it's kind of magic and I could not find any documentation on it, but it  looks like this 
if (Subscription.event.someId == Mutation.event.someId)
```
The only solution I can think atm is to batch the operation like this

```
mutation CreateThingsMutations {
  thing1: createThing(input: ...) {...thing}
  thing2: createThing(input: ...) {...thing}
}
```

With this, the above subscription should work.

**Comment by ammarkarachi** [comment]
Would it help to just filter `createThingInput` on the client?
