### ISSUE TITLE
Stop storing S3 bucket Lambda deployment information under Git

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-cli#5387]
**Is your feature request related to a problem? Please describe.**

When you work in a team on a project with multiple Amplify envs, you merge code from multiple developers in a main branch (at some point).
The problem is that the Git history and the code reviews are polluted by changes done when switching environment instead of real code changes.
To be more specific, all the CloudFormation scripts under amplify/backend/functions/XXX contains section like this:

```
"Code": {	
	"S3Bucket": "blabla-env-123456-deployment",
	"S3Key": "amplify-builds/blabla-1234567890123456-build.zip"	
},
```

Because the S3Key and S3Bucket is different for all env (and the S3Key even change between push) these value change all the time creating a lot of fuzz in the Git commits.

**Describe the solution you'd like**

I like to have the Amplify CLI dynamically injecting that information when pushing and removing the hardcoded values from the CloudFormation files.
Like having:

```
"Code": {	
	"S3Bucket": "DO-NOT-CHANGE-UPDATED-BY-AMPLIFY-CLI",
	"S3Key": "DO-NOT-CHANGE-UPDATED-BY-AMPLIFY-CLI"	
},
```
And if the Amplify CLI needs to store the information about those URLs please use team-provider-info.json for information that remains and a file that is under .gitignore for the information that changes at every push.

**Comment by ammarkarachi** [comment]
@xavierraffin Thanks for feature request this looks like there is some room for improvement I will mark this as an enhancement.

**Comment by ahtokca** [comment]
@xavierraffin was going to create exactly the same feature request! Thanks

**Comment by aaronbrighton** [comment]
Also, interested in this enhancement or bug fix.

Seems like similar environment specific pollution exists in the CF templates with Lambda layers (#5479).

**Comment by r0zar** [comment]
I agree this is an enhancement.

@ammarkarachi do you know who's working this at the moment? I wouldn't mind picking it up if it's looking for an owner.

I'd also be interested to chat on the ideal solution. Resolving the S3Bucket seems straightforward considering it already present in team-provider-info.json. The S3Key leaves a little to be improved on, considering it would be nice to generate only 1 hash for the entire build, and use that for all lambdas. Interested in your thoughts on this one. Thanks!

**Comment by cyrfer** [comment]
I'm excited this is being looked at. I am hoping the following basic use case for release management when promoting to higher environments is supported by any outcome.

For example, lets say:
1. all environments use lambda-a-01.zip.
2. Developer X implements a new feature, resulting in artifact lambda-a-02.zip, and successfully tests in DEV env, and promotes to QA env.
3. While QA team verifies the new behavior, Developer Y implements another feature, which results in artifact lambda-a-03.zip, and deploys to DEV env. Feature 03 has not been tested by the QA team yet.
4. Then the QA team promotes feature 02 to PROD env. Feature 02 should only go to PROD. Feature 03 SHOULD NOT be promoted.

I'm guessing the solution is to use a combination of branches and amplify environments, but I want to be sure that `git checkout QA && amplify push` only deploys the right thing. Please calm my paranoia.

**Comment by cyrfer** [comment]
@jhockett @renebrandel How do we start using this feature?

**Comment by jhockett** [comment]
Sorry for the confusion @cyrfer. The update has been merged, but it has not been released yet.

**Comment by ahtokca** [comment]
@jhockett,  any hints when it will be released?

**Comment by r0zar** [comment]
:man_dancing:

**Comment by Rifur13** [comment]
What are the current workarounds for this?
Do we need to inspect the cloudformation json files each we merge envs (e.g. merging dev env in a prod env) and make sure we don't overwrite the s3 bucket for each lambda?
