### ISSUE TITLE
AppSync Transformer Makes Both Owner Fields Required in Subscription

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-cli#5388]
Created on request of @yuth 

**Current broken behavior:** If you have a schema with multiple owner rules, where each restrict read operations such as this one...

```graphql
type Post @model
@auth(rules: [
    { allow: owner },
    { allow: owner, ownerField: "editors", operations: [read, update] }
]) {
  id: ID!
  title: String!
  content: String
  owner: String
  editors: [String]
}

```

... the Transformer makes the owner parameters in the subscribe functions all required, e.g. `onCreatePost(owner: String!, editors: String!)`

This means that, in this example, you could only subscribe to records where someone is both the owner and an editor. You would not be able to subscribe to records where they are just one or the other. 

**Expected behavior:** The owner parameters should be optional so you can choose to just send one.

**Comment by edwardfoyle** [comment]
closing as above PR is merged
