### ISSUE TITLE
"amplify push" causes a weird "Uploading files" prompt

### ISSUE THREAD

**Issue by renebrandel** [aws-amplify/amplify-cli#5393]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Run "amplify push" in a new project. Observe how the "Uploading files..." is weirdly formatted. Expected: A "spinner" with Uploading files... in-place instead of consecutively printed.
![image](https://user-images.githubusercontent.com/4989523/94105227-affea880-fded-11ea-895e-5b2099ee6532.png)

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.29.2

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by r0zar** [comment]
This has been happening to me for a few weeks and I was wondering if I was the only one seeing it :sweat_smile:
