### ISSUE TITLE
amplify-push cannot find profile init failed

### ISSUE THREAD

**Issue by nickguimond** [aws-amplify/amplify-cli#5394]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-app/src/scripts/amplify-push.js#L37 returns an object {profile: ''}  but system-config-manager.js expects it to be a string in places https://github.com/aws-amplify/amplify-cli/blob/3ec96f7616bff62b7a65e20a643b9a0f7c12b05a/packages/amplify-provider-awscloudformation/src/system-config-manager.js#L245-L258  which causes:
```
init failed
Error: Profile configuration is missing for: [object Object]
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.29.2

**Desktop (please complete the following information):**
 - OS: MAC
 - Node Version. You can use `node -v` to check the node version on your system
10.16.0

**Additional context**

**Comment by nikhname** [comment]
@nickguimond which command did you run that caused this error to show up? Was it` amplify configure`?

**Comment by nikhname** [comment]
I was able to reproduce this. As a workaround, you can provide the name of the profile you want to use in `amplify-build-config.json`

**Comment by nickguimond** [comment]
> I was able to reproduce this. As a workaround, you can provide the name of the profile you want to use in `amplify-build-config.json`

Cool, this was in sept, I ended up just modifying the source code to get around it at the time.
