### ISSUE TITLE
how does dependsOn work in backend-config.json

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#5395]
I'm struggling to get `dependsOn` in backend-config.json to do anything useful.

**Which Category is your question related to?**
deploying

**Amplify CLI Version** 
```bash
$ amplify -v
4.29.2
```

**What AWS Services are you utilizing?**
many - AppSync, Functions, and custom cloudformation.

**Provide additional details e.g. code snippets**

My backend-config.json includes:

```json
  "security": {
    "l12n": {
      "providerPlugin": "awscloudformation"
    }
  },
  "function": {
    "l12nAPI": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {"category": "security", "resourceName": "l12n", "attributes": ["SecurityGroupId"]}
      ]
    }
  },
```

where `security/l12n` is just a folder structure to hold a custom cloudformation template that simply creates a SecurityGroup for the function to run in a VPC.

From what I've seen in other posts, I think `dependsOn` can be used to force the deployment order. I have several stacks that need a specific order and in all of them I tried a scheme like I'm showing here. When I use this strategy, I get cloudformation errors that read like:

> UPDATE_FAILED               functionl12nAPI          AWS::CloudFormation::Stack Thu Sep 24 2020 08:21:28 GMT-0700 (Pacific Daylight Time) Parameters: [securityl12nSecurityGroupId] do not exist in the template

The function stack takes a parameter called `SecurityGroupId`, which is specified in the file `function/l12nAPI/parameters.json` as:
```json
{
  "SecurityGroupId": {
    "Fn::GetAtt": [
        "securityl12n",
        "Outputs.SecurityGroupId"
    ]
  }
}
```

The parameters.json is sufficient to get the stack to deploy. It seems that adding `dependsOn` corrupts the name of the parameter being passed to the CF template.

It would be great if you could describe how I'm supposed to use `dependsOn` or point me to the documentation.
Thank you!

**Comment by ammarkarachi** [comment]
Hi @cyrfer , It's looking for `securityl12nSecurityGroupId` whereas in the parameters.json it is specified as `SecurityGroupId`.   

The `dependsOn` here basically tells the cli where to look for the output variable to link the variable in the CFN.

**Comment by cyrfer** [comment]
@ammarkarachi it does not work.

**Comment by ammarkarachi** [comment]
It looks like the parameter is supposed to be created in the stack itself and that is not being created when the stack template is formed.

**Comment by cyrfer** [comment]
@ammarkarachi I do not follow what you're talking about.

Is `dependsOn` a tool to control the order the stacks are deployed?

**Comment by ammarkarachi** [comment]
@cyrfer The function cloudformation stack's template doesn't have the parameter declared when generating . I have created a sample project with a custom stack and a function below. To get the parameter passed on to the function you would need to declare the parameter as shown here https://github.com/ammarkarachi/customcfn/blob/1c0e8991802869bf1a6408177d7f01f09dd2d478/amplify/backend/function/customcfea0df03a/customcfea0df03a-cloudformation-template.json#L13

https://github.com/ammarkarachi/customcfn

>Is dependsOn a tool to control the order the stacks are deployed?

Yes for Cloudformation but in the CLI the `dependOn` is used to identify what parameters is the particular category depending on from an other resource.

**Comment by cyrfer** [comment]
@ammarkarachi Ok you're saying I need to change the parameter name when using `dependsOn`.

I'd like to make a feature request that `dependsOn` only control the order of the stack deployments, and it does NOT change the required parameter names as my parameters pass just fine without the use of `dependsOn`.

**Comment by cyrfer** [comment]
To me, the `dependsOn` feature is broken when it conflicts with another feature like the DSL available to `parameters.json` files. You might also consider this a BUG since there is a conflict, even though a workaround exists, which seems very fragile to me.

**Comment by cyrfer** [comment]
For compatibility, if developers uses OMIT the `attributes` section, could `dependsOn` only enforce the stack deployment ORDER, rather than also trying to pass a parameter? For example this,
```json
      "dependsOn": [
        {"category": "security", "resourceName": "l12n", "attributes": ["SecurityGroupId"]}
      ]
```
could change to this when only ORDER is desired:
```json
      "dependsOn": [
        {"category": "security", "resourceName": "l12n"}
      ]
```

**Comment by cyrfer** [comment]
We really need some documentation on this stuff.
https://github.com/aws-amplify/docs/issues/2437

**Comment by cyrfer** [comment]
@kaustavghosh06 can I get a bug label?

**Comment by josefaidt** [comment]
Closing per the [update on the docs issue](https://github.com/aws-amplify/docs/issues/2437#issuecomment-880162155) describing the plans to reduce the number of files Amplify generates and reducing dependencies on this file. @cyrfer if you feel this is in error or have additional comments please reply back to this thread and we can investigate further. 🙂

**Comment by jkgwm** [comment]
@josefaidt I just need to know what is allowed in `backend-config.json`. If you're removing that file in the next 10 days, then I'm happy to look at the future documentation instead.

I would like to know what are the priorities and roadmap of the Amplify tools. Where are "the plans" described?

**Comment by cyrfer** [comment]
@josefaidt I just need to know what is allowed in backend-config.json. If you're removing that file in the next 10 days, then I'm happy to look at the future documentation instead.

I would like to know what are the priorities and roadmap of the Amplify tools. Where are "the plans" described?

**Comment by josefaidt** [comment]
Hey @cyrfer thanks for the response! Unfortunately we do not currently have a public roadmap to reference. For the `backend-config.json` file are you looking for a clearer description of how `dependsOn` is used?

**Comment by cyrfer** [comment]
Yes, much clearer, actual documentation on the schema allowed.

**Comment by josefaidt** [comment]
Closing in favor of tracking #10043 for providing JSON schemas with descriptions of properties and their usage
