### ISSUE TITLE
[Feedback] amplify configure doesn't create a user in AWS IAM console.

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/amplify-cli#5398]
**Page**: [`/start/getting-started/setup/q/integration/android`](https://docs.amplify.aws/start/getting-started/setup/q/integration/android)

**Feedback**:

When I run _amplify configure_, provide region _us-west2_, and user _amplify-user_, it puts me at the AWS _Welcome to Identify and Access Management_ page instead of _Add User_

<img width="743" alt="amplify-rn-pic01" src="https://user-images.githubusercontent.com/6365898/94091586-774ed700-fdcd-11ea-824e-60da72c739a8.png">

**Comment by LeoSalemann** [comment]
My browser was MS Edge; my OS was Windows 10, running in a virtual box VM, hosted on a Mac running Catalina 10.15.16. I was performing the steps in **Install and configure the Amplify CLI** for React Native verbatim, except I picked us-west2 as my preferred region.

**Comment by LeoSalemann** [comment]
Here's another data point.  When I go to add a user in AWIS/IAM console, I get a list of groups instead of policies. I've had this AWS account since 2017-ish, so I might have something out of date on my side, re group vs. policy settings.
<img width="754" alt="add-user-issue" src="https://user-images.githubusercontent.com/6365898/94205544-5ee7c680-fe78-11ea-9474-c78e35228fd6.png">

**Comment by ammarkarachi** [comment]
Hi @LeoSalemann, The first step it prompts you to log into your AWS account after you have logged in you can continue on to setting up your user.

```
Follow these steps to set up access to your AWS account:

Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue

Specify the AWS Region
? region:  us-west-2
Specify the username of the new IAM user:
? user name:  ammar
Complete the user creation using the AWS console
https://console.aws.amazon.com/iam/home?region=us-west-2#/users$new?step=final&accessKey&userNames=ammar&permissionType=policies&policies=arn:aws:iam::aws:policy%2FAdministratorAccess
Press Enter to continue
```
