### ISSUE TITLE
Added tags via tags.json to an existing amplify project are inverting their default values

### ISSUE THREAD

**Issue by fkoner** [aws-amplify/amplify-cli#5399]
**Describe the bug**
Added tags via tags.json to an existing amplify project are inverting their default values

**Amplify CLI Version**
4.29.1

**To Reproduce**
Add tags as describe here [tags](https://docs.amplify.aws/cli/usage/tags)
Run amplify push. The value of **{project-env}** is switching by the value of **{project-name}**.

tags.json:
```
[
  {
    "Key": "user:Stack",
    "Value": "{project-env}"
  },
  {
    "Key": "user:Application",
    "Value": "{project-name}"
  }
]
```
Using the following project values:
**_project-env value: heroes
project-name value: aws-amplify-ninja_**

It results with the following tags:

**_user:Stack -> aws-amplify-ninja
user:Application -> heroes_**

**Expected behavior**
Assign the respect values for **{project-env}** and **{project-name}**
tags.json
```
[
  {
    "Key": "user:Stack",
    "Value": "{project-env}"
  },
  {
    "Key": "user:Application",
    "Value": "{project-name}"
  }
]
```

Resulting in the following tags:

**_user:Stack -> heroes
user:Application -> aws-amplify-ninja_**

**Screenshots**
![amplify-issue-inverting-values-for-tags](https://user-images.githubusercontent.com/2480544/94211476-2efbeb80-fe97-11ea-83a4-9187783d052f.png)

**Desktop (please complete the following information):**
 - OS: Mac/Ubuntu
 - Node Version. 10.20.1

**Additional context**

**_Thanks in advance 
paco :rocket:_**

**Comment by ammarkarachi** [comment]
@fkoner Thanks for bringing this to our attention it looks like it's an issue, we will have a fix by the next release
