### ISSUE TITLE
Stop asking for hostedUIProviderCreds at init

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-cli#5402]
**Is your feature request related to a problem? Please describe.**

We have an Amplify project that using Auth.federatedSignIn and who federates against Facebook, Google and Amazon.
We also offer an internal (Cognito login).

When we have a new developer (internal or external) cloning the repo he does `amplify init` to configure his dev env.

Then the Amplify CLI ask for the Social settings:
```
> amplify init
? Do you want to use an existing environment? No
? Enter a name for the environment <my-new-env>
...
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID.

 Enter your Facebook App ID for your OAuth flow:  <i-have-no-clue>
 Enter your Facebook App Secret for your OAuth flow:  <i-have-no-clue>

 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID.

 Enter your Google Web Client ID for your OAuth flow:  <i-have-no-clue>
 Enter your Google Web Client Secret for your OAuth flow:  <i-have-no-clue>

 You've opted to allow users to authenticate via Amazon.  If you haven't already, you'll need to create an Amazon App ID.

 Enter your Amazon App ID for your OAuth flow:  <i-have-no-clue>
 Enter your Amazon App Secret for your OAuth flow:  <i-have-no-clue>
```

At that point the developer have no idea what to input here. Many of them lost time trying to figure out or to remove the need for federation in their local env.
For 3rd party devs (project is open source) this is even worse.

And also most of the developer will never setup a Facebook, Google, Amazon federation on their dev environment. Most of the time they work on other part of the app and using the local Cognito login only is fine.

**Describe the solution you'd like**

Two ideas, I prefer Option 1 as it does not introduce a new command and therefore there is nothing new to learn for all devs in the Amplify community.

**Option1:**
Stop asking this settings at _init_ and instead ask:

```
Do you want to configure the Social login federation now (you can configure it manually in team-provider-info.json later if you don't)? y/n
```
Then (and I guess this is why you do it this way today), when the developer change the values in team-provider-info.json, detect that the auth needs to be updated. This specific need is explained here #5403 in a more general context.

**Option2:**
Stop asking this settings at _init_ and introduce a new Amplify command `amplify setup`:

```
> amplify setup
...
 Enter your Facebook App ID for your OAuth flow:  <i-am-ready-now>
 Enter your Facebook App Secret for your OAuth flow:  <i-am-ready-now>
...
```

With specific resource setup:

```
> amplify setup auth
...
 Enter your Facebook App ID for your OAuth flow:  <i-am-ready-now>
 Enter your Facebook App Secret for your OAuth flow:  <i-am-ready-now>
...
```

**Describe alternatives you've considered**

I considered creating a CLI for my project on top of the Amplify CLI to enter default value on behalf of my developer and say to developer: _Don't use `amplify init` use `./magic-amplify init`
But this is a pain, non Amplify standard and hard to maintain.

**Additional context**

This ticket will be easier to solve with #5403 done

**Comment by xavierraffin** [comment]
Please re-open

**Comment by xavierraffin** [comment]
Please keep open

**Comment by kaustavghosh06** [comment]
@xavierraffin did you try using the latest version of the CLI. AFAIK, we don't ask this question anymore on init or pull. cc @ammarkarachi
