### ISSUE TITLE
Amplify Backend Environments and CICD

### ISSUE THREAD

**Issue by jithinjava** [aws-amplify/amplify-cli#5404]
### Problem Description
I have different AWS accounts representing different environments dev, stage and prod.
I need to create same Amplify backend Environment in all the accounts(one per Account) with a GraphQL Api category.
I can use Amplify cli directly from my development workstation to initialize an app and create a new environment in dev Account. But for stage and prod I want this to be done by CICD.

### Here is the list of actions I tried:
for **DEV** Account, I used my development workstation(I have a react js application)

- installed amplify cli
- ran `amplify init`
- answered all the prompts as required
- at the end of init, it created an amplify app and auth/unauth roles as well in cloud
- Then, i ran `amplify api add`
- answered the prompts and created a GraphQl Api, compiled and pushed to cloud using `amplify push`

Everything looks ok. I have the environment with Api.

for **STAGE** Account, I tried 2 approaches:
1. Using Headless mode of Amplify CLI

- I have created a docker image with amplify cli support

As I read from the docs I need to run `amplify env add` to create a new environment.
**First problem** I faced `amplify env` is not available in headless mode.
So what I interpreted from the docs as a possible workaround for this was to checkout my react js application in my CICD pipeline and  run `amplify init` in headless mode from the root directory with a new environment name. and my expectation is that amplify cli will create a new environment with all graphql api category in test Account (Is this understanding correct?)

- I proceeded with code checkout, I have amplify folder and all files(everything else apart from files in .gitignore) generated by amplify cli

- ran amplify init in headless mode in my fresh checkout

**Second problem** I faced here was weird, CLI was ignoring "useProfile" flag and its checking for a named profile config, even though i set the value to false and provided correct ACCESS KEY ID and SECRET KEY. I am not sure this is a problem with my setup or order of execution of amplify commands.

2. Using Cloud formation templates generated by Amplify CLI in dev

- I tried to collect all the cfn templates generated by Amplify cli from S3 bucket to recreate the stack. But I found all relevant templates for my Api category except for the main stack which creates the Amplify app itself. With the templates i could create an AppSync api and all its dependencies but i couldnt find the template for root stack to create the amplify app itself and link my category.

Does this means that, Only possible ways to create a new amplify "Backend" environment is either CLI or Amplify console? Wont it generate a cfn template for the main stack? 

My intention is to replicate an amplify environment in my dev Account to my higher accounts with new environment names in my CICD. Could you please advice what are the steps to achieve this.

**Comment by ammarkarachi** [comment]
@jithinjava Can you share you headless invocation redacting any sensitive information?

**Comment by jithinjava** [comment]
Hi @ammarkarachi  Thanks for the response, Please find below log copied from pipeline execution

1.  Fresh checkout of the project
2. [Pipeline] sh
` amplify init --yes --amplify {"envName": "test"} --providers {"configLevel":"project","useProfile":false,"profileName":"default","accessKeyId":"DUMMYID","secretAccessKey":"DummySecretKey","region":"dummy-region"}`

Here my attempt was to create entirely new amplify app environment in my test account with name "test" using the amplify folder and files i already generated for my dev account. It failed looking for my AWS credentials file.

**Comment by jithinjava** [comment]
Hi, would be great to have an update on this issue , thanks 🙏

**Comment by ammarkarachi** [comment]
@jithinjava Can you try running the command with latest it should be working
>So what I interpreted from the docs as a possible workaround for this was to checkout my react js application in my CICD pipeline and run amplify init in headless mode from the root directory with a new environment name. and my expectation is that amplify cli will create a new environment with all graphql api category in test Account (Is this understanding correct?)

Yes it will create a new environment if not already created or initialize an existing one

>Does this means that, Only possible ways to create a new amplify "Backend" environment is either CLI or Amplify console? Wont it generate a cfn template for the main stack?

Yes it would generate new root stack templates for each of your environments, you would go dev -> stage -> prod
