### ISSUE TITLE
Not able to npm install -g @aws-amplify/cli. Giving npm Err - errno -4048 #461

### ISSUE THREAD

**Issue by Rudra815** [aws-amplify/amplify-cli#541]
**Describe the bug**
npm ERR! path C:\Users\hrudra\AppData\Roaming\npm\node_modules\@aws-amplify\cli\
node_modules\npm\node_modules\chownr\package.json.1630759970
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\hrudra\AppData\
Roaming\npm\node_modules\@aws-amplify\cli\node_modules\npm\node_modules\chownr\p
ackage.json.1630759970' -> 'C:\Users\hrudra\AppData\Roaming\npm\node_modules\@aw
s-amplify\cli\node_modules\npm\node_modules\chownr\package.json'
npm ERR!   parent: 'npm' }

**To Reproduce**
Run: npm install -g @aws-amplify/cli

**Expected behavior**
aws-amplify/cli successfully installed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 7 professional
![issueimg](https://user-images.githubusercontent.com/45593994/49439643-9f7bd900-f7e7-11e8-8e77-78ed55e64868.PNG)

**Additional context**

**Comment by yuth** [comment]
Amplify CLI is does not officially supported in Windows 7. We recommend you using Windows 10 with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). are actively working on support for cmd / ps but that it is not complete.

**Comment by kaustavghosh06** [comment]
You might want to first remove the @aws-amplify directory from the node-modules and then try re-installing it.

**Comment by kaustavghosh06** [comment]
@Rudra815 were you able to install it?

**Comment by Joao-Leite** [comment]
I'm having the same problem. I'm running Windows 10 Pro WSL feature activated.
When I go to node_modules folder, the @aws-amplify directory is not there (although its temporarily created when I'm running (npm install -g @aws-amplify/cli)

**Comment by Rudra815** [comment]
> 
> 
> @Rudra815 were you able to install it?

@kaustavghosh06 yes.. I have installed it successfully over NVM - Node Version Manager.
Thanks

**Comment by kaustavghosh06** [comment]
@Rudra815 Awesome!
@Joao-Leite Are you getting any errors when installing it?

**Comment by Rudra815** [comment]
@Joao-Leite no errors for me.. its working good for me. Below are steps I followed
1. Install NVM on WSL.
2. Install node and npm
3. Finally npm install -g @aws-amplify/cli. 
this way worked for me.. you also give a try
if you any any permission denied issue for any directory/file give them to that directory/file
sudo chmod 777 <dir/file name> then try with npm install -g @aws-amplify/cli again

Good Luck @Joao-Leite

**Comment by Joao-Leite** [comment]
I'm getting this error:
![error](https://user-images.githubusercontent.com/44463806/51029408-1f872280-158e-11e9-9576-5ddabc38d896.png)

But when I try to cd on the .staging folder, it says it doesnt exist, so I cant change permissions to it.
I think the folder is deleted when the installation doesn't run successfully .
I'm currently running node 11.6.0 and npm 6.5

**Comment by kaustavghosh06** [comment]
Looks like a permission issue. You might want to use ‘sudo’ to bypass this error.

**Comment by franciscofrr** [comment]
I'm also having this problem while trying to install the CLI. I'm running Win10 x64, with Nodejs v10.15.0 and npm 6.4.1. I've tried everything - running the command as admin, reinstalling Nodejs, but it always throws the same error.

**Comment by chengkiang** [comment]
On my Windows 10 Version 1803 (Build 171314.556), Node 8.1.4 and npm 6.8.0, I am also having the same issue when installing via the Windows command line. The \@aws-amplify folder does not exist in %appdata%\npm\node_modules, so I can't even check permissions or remove it.

**Comment by kaustavghosh06** [comment]
Hey guy, I was trying to reproduce this on a windows machine and wasn't able to. Did you'll run `npm install -g @aws-amplify/cli` and I was able to succesfully install the CLI. Please let me know if you're still seeing this issue.

**Comment by Chidan** [comment]
Hi There, I am also facing the exact same issue.
Below is the screen shot And log file attached, could you please help.
![image](https://user-images.githubusercontent.com/5826495/53374435-9880e480-3958-11e9-940d-f1df49d5ae5f.png)

[2019-02-25T22_52_02_809Z-debug.log](https://github.com/aws-amplify/amplify-cli/files/2902970/2019-02-25T22_52_02_809Z-debug.log)

**Comment by yuth** [comment]
@Chidan from the error log it looks like this issue is not specific to amplify cli, but rather NPM installation issue. Could you try running npm with admin permission and see if that solves the issue

**Comment by Chidan** [comment]
@yuth, I dont think there is anything wrong with NPM permission, as I am able to install all other modules without any issues, for example react.

**Comment by Chidan** [comment]
> @Chidan from the error log it looks like this issue is not specific to amplify cli, but rather NPM installation issue. Could you try running npm with admin permission and see if that solves the issue

@yuth, I dont think there is anything wrong with NPM permission, as I am able to install all other modules without any issues, for example react.

**Comment by Chidan** [comment]
> @Chidan from the error log it looks like this issue is not specific to amplify cli, but rather NPM installation issue. Could you try running npm with admin permission and see if that solves the issue

@yuth , BTW, Im running with admin permission in powershell on windows

**Comment by Chidan** [comment]
Finally I was able to install. I tried the same things I have been doing, but for once it got installed. I have no idea how it got install in this particular try!!! Not good!!

**Comment by prudhvirv** [comment]
I am still facing this issue. Struck with the same issue from last 2 days. 

![image](https://user-images.githubusercontent.com/3187332/61842871-56cc7980-aeb7-11e9-96a9-f4c0e29fcfd4.png)

**Comment by yuth** [comment]
@prudhvirv What version of NPM do you have installed. We have seen people having issues with older version of NPM. Could you upgrade your NPM to latest version and try again

**Comment by BilalAhmad7778** [comment]
@kaustavghosh06 
yeah it is working i was also facing the same problem but now it is solved 
Hey guy, I was trying to reproduce this on a windows machine and wasn't able to. Did you'll run npm install -g @aws-amplify/cli and I was able to succesfully install the CLI. Please let me know if you're still seeing this issue.
