### ISSUE TITLE
Can't amplify push due to "[googleClientId] do not exist in the template" error

### ISSUE THREAD

**Issue by dyson-yamashita** [aws-amplify/amplify-cli#5416]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
$ amplify -v
4.27.3

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I fixed PostConfirmation function of  Cognito in multiple env and with Google's federation set up.
After that, when amplify push, I can't complete the push due to the "[googleClientId] do not exist in the template" error.

```
$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name               | Operation | Provider plugin   |
| -------- | --------------------------- | --------- | ----------------- |
| Function | webf542827dPostConfirmation | Update    | awscloudformation |
| Auth     | webf542827d                 | No Change | awscloudformation |

UPDATE_IN_PROGRESS          webf542827d        AWS::CloudFormation::Stack Sat Sep 26 2020 12:06:20 GMT+0000 (Coordinated Universal Time)                                                                        
UPDATE_FAILED               webf542827d        AWS::CloudFormation::Stack Sat Sep 26 2020 12:06:20 GMT+0000 (Coordinated Universal Time)
Parameters: [googleClientId] do not exist in the template   
```

Also, the process of removing the federation with amplify update auth gives me the same error as above and I can't do the update.

And, googleClientId is written in team-provider-info.json
```
    "categories": {
        "auth": {
            "webf542827d": {
                "hostedUIProviderCreds": "[{\"ProviderName\":\"Google\",\"client_id\":\"100222998699-gps3kohgkpibbbb72dr5c0jc712khf51.apps.googleusercontent.com\",\"client_secret\":\"Y8szeeee9_mUJdddQPlffffuP\"}]",
                "googleClientId": "100222998699-gps3kohgkpibbbb72dr5c0jc712khf51.apps.googleusercontent.com"
            }
        }
```

Could you please let me know if there is a workaround?

**Comment by dyson-yamashita** [comment]
I resolved this problem.
Firstly, I remove Google specification from "Update OAuth social providers" and amplify push.
Secondly, I re-set Google specification by "Update OAuth social providers" and push.
Finally, modify funcation and push.

```
$ amplify update auth
  Walkthrough all the auth configurations 
  Add/Edit signin and signout redirect URIs 
❯ Update OAuth social providers 
  Create or update Cognito user pool groups 
  Create or update Admin queries API 
```

**Comment by Basovs** [comment]
> ❯ Update OAuth social providers

I dont have this option...

**Comment by Basovs** [comment]
> > ❯ Update OAuth social providers
> 
> I dont have this option...

Ohh... 

1.) I had to 'amplify update auth' and add oauth manually and provide access key and secret key for both Facebook and google. 

2.) And then i had to 'amplify update auth' AGAIN! And only then i saw this '❯ Update OAuth social providers' option. Click on it and u have to provide with Access key and Secret key for both Facebook and Google again! 

3.) Now 'amplify push' - Should work now! Be happy!

resume: u have to provde Facebooks and Googles access key and secret key TWICE.
