### ISSUE TITLE
When using RDS, how can I send a value that can be null?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5418]
Hello, 
I have a small issue.

When using RDS, how can I send a value that can be null?

This is my code:
  ```
const params = {
    secretArn: secretStoreARN,
    resourceArn: clusterIdentifierARN,
    database: databaseName,
    sql: `INSERT INTO UserReaction (senderUserId, receiverUserId, type) VALUES(UNHEX(:reactionSenderProfileUserId), UNHEX(:reactionReceiverProfileUserId), :reactionType) ON DUPLICATE KEY UPDATE updatedAt = NOW(3), type = :reactionType;`,
    parameters: [
      {
        name: 'reactionSenderProfileUserId',
        value: {
          "stringValue": reactionSenderProfileUserId
        }
      },
      {
        name: 'reactionReceiverProfileUserId',
        value: {
          "stringValue": reactionReceiverProfileUserId
        }
      },
      {
        name: 'reactionType',
        value: {
          "stringValue": reactionType
        }
      }
    ]
  }  
  try {
    let dbResponse = await RDS.executeStatement(params).promise();
    return true;
  } catch (error) {
    throw error;
  }
```

If reaction type is a string, then everything works fine.
But if reaction type is null (which is allowed in my data model), then I see this error from the lambda function:
`BadRequestException: Parameter "reactionType" has value with no field set`

So, reading this:
https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html
Perhaps I should use "isNull", not sure how.

I don't really know how to create a parameter for RDS.executeStatement that can be a string or null, I think that is the problem.

The solution I see right know is to create 2 params, but that is not scalable if I have more parameters that can be null.

What should I do?
Thanks a lot.

**Which Category is your question related to?**
RDS Data API

**Amplify CLI Version** 
4.29.0

**What AWS Services are you utilizing?**
AppSync, Lambda, and RDS (Aurora Serverless)

**Comment by ammarkarachi** [comment]
@Ricardo1980 This looks like something that is related to AWS SDK have you tried there?

**Comment by Ricardo1980** [comment]
@ammarkarachi 
Where exactly?
Here?
https://github.com/aws/aws-sdk-js
Thanks.

**Comment by ammarkarachi** [comment]
@Ricardo1980 That looks right

**Comment by Ricardo1980** [comment]
Ok. Let me try.
