### ISSUE TITLE
Must amplify pull retrieve function modification you made in aws console ?

### ISSUE THREAD

**Issue by Sam31000** [aws-amplify/amplify-cli#5424]
**Which Category is your question related to?**
Function

**Amplify CLI Version** 
4.29.3

**What AWS Services are you utilizing?**

- AppSynch

- RDS Aurora (instance)

- Lambda

**Usage question**
I'm using amplify cli as I use Git to pull/push modifications from aws cloud. When I'm trying to update my function code directly in aws console I'm not able to retrieve it locally. Here are the steps I'm doing : 

1.  Modification of a Function (Lambda Function in my amplify project) in aws console using online IDE.
2. Going locally in the folder where my amplify project is sync using my terminal. Trying to do `amplify pull`
3. Nothing is updated. All operation are "No Change"
4. When i'm trying to force it with `amplify env pull dev --restore`. I got the same result, nothing is updated.

My local project is correctly linked to the cloud. When I'm doing local modification I can `amplify push` them correctly.

Am I  doing something wrong ? Did amplify cli be used this way ? (Like git)

Thanks.

**Comment by ammarkarachi** [comment]
@Sam31000 The changes to the Lambda function will not be reflected back, but you can export the function and copy the changes manually
![image](https://user-images.githubusercontent.com/56042290/94869763-d7133680-03fa-11eb-9fde-99ddf03ba532.png)

**Comment by Sam31000** [comment]
Thank you @ammarkarachi for your answer.
It seems to be complicated to retrieve locally all modification done on aws online IDE this way.

I will looking  for an automatic way to do it.
