### ISSUE TITLE
Cognito lambda triggers time out on cold start

### ISSUE THREAD

**Issue by pagameba** [aws-amplify/amplify-cli#5425]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When using lambda triggers with Cognito (e.g. CreateAuthChallenge), the amplify-provided configuration cold start is over 5 seconds, causing Cognito to think the function has timed out (it has a hard limit of 5 seconds).  A second request is made, initiating a second cold start, which also times out.  The third (and last) attempt works because it hits the first lambda again, which is no longer cold.  In my case, the CreateAuthChallenge sends an email with a passwordless login code, so I would receive 3 emails on cold start.

Cold start:

`REPORT RequestId: f3cb4b4b-5947-4605-ad11-739a24a9afa5	Duration: 5819.94 ms	Billed Duration: 5900 ms	Memory Size: 128 MB	Max Memory Used: 89 MB	Init Duration: 182.38 ms`

Warm start:

`REPORT RequestId: 68c8fedc-9e38-4c19-98e5-00eae433a477	Duration: 365.82 ms	Billed Duration: 400 ms	Memory Size: 128 MB	Max Memory Used: 89 MB`

After instrumenting the code, I was able to identify that the difference is almost entirely consumed by the `index.js` plus module loading provided by Amplify as a framework.  When I moved my code into `index.js` and replaced the default module lookup/require pattern, the resulting cold start time is:

`REPORT RequestId: 11057896-81b5-4e29-820c-9fd2c3745b66	Duration: 1128.84 ms	Billed Duration: 1200 ms	Memory Size: 128 MB	Max Memory Used: 91 MB	Init Duration: 429.93 ms`

**Amplify CLI Version**
4.29.2

**To Reproduce**
Configure Cognito to use lambda triggers with Amplify CLI and deploy.

**Expected behavior**
The initial cold start time of the lambda should be much less.

**Screenshots**

none.

**Desktop (please complete the following information):**
 - OS: Amazon Lambda
 - Node Version. nodejs10.x

**Additional context**

none.

**Comment by kaustavghosh06** [comment]
@pagameba This issue would be fixed with this PR - https://github.com/aws-amplify/amplify-cli/pull/6863 and will be a part of our next release.
