### ISSUE TITLE
Strorage.put 403 error

### ISSUE THREAD

**Issue by donnrri** [aws-amplify/amplify-cli#5430]
I have done the following

Using the amplify CLI 
I am using aws-amplify version 3.1.1.
amplify add auth - to create a Cognito user pool
In the AWS console I have created a number user in this user pool and created groups for these
I have created an S3 bucket using amplify add storage
I have restricted  access for individual groups 
I can log into my application (a React app) and can Storage.get() a file from the public folder I have manually uploaded via the AWS console into the bucket created by amplify
Despite giving create/upload access to a user group,   I get the following errors when trying to upload a csv file using a user in that user group.

Request URL: https://cognito-identity.my-region.amazonaws.com/
Request Method: POST
Status Code: 400 
Remote Address: 54.213.20.204:443
Referrer Policy: no-referrer-when-downgrade

zn-errormessage: Unauthenticated access is not supported for this identity pool.

My request payload has a IdentityPoolId and I checked it is correct.
In my Identity Pool settings Identity Pool --> Authentication Providers -> Cognito my user pool id and client app id settings are correct.

After the 400 status error I get an 403 error for the actual PUT request :

Request URL: https://my-bucket.my-region.amazonaws.com/public/testfile?x-id=PutObject
Request Method: PUT
Status Code: 403 Forbidden
Remote Address: 52.218.252.113:443
Referrer Policy: no-referrer-when-downgrade

I see others have raised similar issues and requested the documentation be updated , but I cannot follow how to resolve this issue and the documentation  still says 
'_If you use aws-exports.js file, Storage is already configured when you call Amplify.configure(awsconfig)_'
Which is what I am doing.  If their are additional steps can you clearly explain them , like an example of what is required , where a file should be created and so on.

Thanks for any comments

**Comment by akshbhu** [comment]
Hi @donnrri 

When you login into your react app , Is the user part of a group(which you restricted access selected)?

One thing you can try is ```amplify update storage``` and  select ```Both ```option  in ```restrict access by``` question.
Here you can define individual access (user not part of a group) and Individual group access(user is part of a group)  permission on how to access objects in the bucket.

Let me know if this works for you?

**Comment by akshbhu** [comment]
Closing this issue as lack of response.
