### ISSUE TITLE
How to add SES permission to LambdaExecutionRole

### ISSUE THREAD

**Issue by pankaj-crypto** [aws-amplify/amplify-cli#5432]
I want to add SES permission to the LambdaExecutionRole so that I can send emails. I want to allow my Lambda Function to be able to use SES. 

I also think it would make sense to have a feature like `amplify [add|update|remove] ses`

**Comment by kaustavghosh06** [comment]
@pankaj-crypto Since we don't support SES out of the box in the Amplify CLI today, you'd have to manually go into `amplify/backend/functions/<function-name>` resource and update the LambdaExecution policy to add your desired SES policies.

**Comment by kaustavghosh06** [comment]
Closing this issue based on the recommendation above. Please let us know if you're still stuck on this and we can re-open this issue.

**Comment by nazartaran** [comment]
@kaustavghosh06 Hello! Recently I did just that - went into amplify/backend/functions/<function-name>, and modified it's cloudformation template with SES policies. It went fine, until I updated the Lambda function permissions to access other resources, after which my custom SES policies were removed. Did I did something wrong? Can you please help me to figure out the best way to implement SES policies for Lambda.
Thank you!

**Comment by bobbyhadz** [comment]
I am new to Amplify CLI so I apologize if I've got something wrong, but currently you can't add ses permissions using the CLI. 
So you have 2 options:

1. Edit the `cloudformation template` and add the permissions - which would be overwritten by any following updates to the function's permissions using the cli
2. Edit the `lambda's execution role in the IAM console` - which in my case did not get overwritten by updating the function's permissions using the cli

Both seem like a very brittle and bad idea, they work until they don't. Having your `cli function's permissions` and the `real function's permissions` out of sync can go wrong in many different ways.

Not being able to add these permissions (or any other permissions you may need for services not included in amplify) using the CLI seems like a huge limitation. Manually adding configuration surely can't be what the Amplify team proposes to solve this.

**Comment by nubpro** [comment]
> @pankaj-crypto Since we don't support SES out of the box in the Amplify CLI today, you'd have to manually go into `amplify/backend/functions/<function-name>` resource and update the LambdaExecution policy to add your desired SES policies.

Will the CLI override our manual changes to the CF template?

**Comment by kaustavghosh06** [comment]
I'm marking this as an enhancement for the CLI to provide a way to specify custom policies for a function so that it doesn't get overwritten on a next `amplify update function`.

**Comment by DPirate** [comment]
Any update regarding this issue?

**Comment by EricDitp** [comment]
+1 Same here

**Comment by Twentyone8** [comment]
Any further updates on this? Would be a useful feature to have

**Comment by kenbankspeng** [comment]
@jkervine I was delighted to see your post as I had been looking for a solution beyond editing the cloudformation templates. Sadly, I was not able to get the custom-policies.json to work, despite your comment making things very clear.

I did however see that amplify now supports `amplify add custom` although I am struggling on the semantics. Currently thinking that I need to add an 'ses' custom resource and reference the amplify lambda resource that needs permission.

https://docs.amplify.aws/cli/custom/cloudformation/

**Comment by kenbankspeng** [comment]
Very nice to see this custom-policies.json capability. file location is function/name/custom-policies.json (without the src).

**Comment by josefaidt** [comment]
Hey y'all apologies for the delay on this one, but as stated above this can be accomplished by leveraging the `custom-policies.json` file located in the function directory. Closing issue 🙂
