### ISSUE TITLE
Recommendation to make an AWS Amplify opensource project modular

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-cli#5435]
**Is your feature request related to a problem? Please describe.**

I am working on an opensource project based on AWS Amplify. This project contains 15+ resources.
This is a reference architecture that customers will fork to customize for their own needs.
The project resources has many _dependsOn_ on others (for example the API GW depends on functions which depends on auth, ...). The source code has also some dependency on the resources deployed (for example an optional security feature may require the frontend to make an additional API call to a Lambda through API Gateway).

Most of the customer won't need all the features (not all the resources) and they may want to remove some of them from the project.

The problem is today it is complex for a customer that start from our code base to remove features they don't need. It requires to edit backend-config.json plus some source code file of the SPA.

**Describe the solution you'd like**

I am looking for a recommendation on how to make the removal of features (and resources) easy for customers.
Because the dource code needs to be aware if a feature is available/required or not I feel the need for a global config file: a config file that is shared by backend and front end. And this file needs to persist accros environment, I cannot use aws-export from this.

**Describe alternatives you've considered**

For now I rely on documenting the commands and file editing that a feature removal will require.
I also created a config-overide.js file (I am using react-rewired) that read amplify backend files to extract information and customize front end. But this can break easily (if any file change, or some file are remove my regex may fail miserably).

Extract of my config-overide.js:

```
var amplifyMeta = {};
var amplifyTeams = {};
const fs = require("fs");
const path = require('path');
if ((!fs.existsSync("./amplify/backend/amplify-meta.json")) ||
    (!fs.existsSync("./amplify/team-provider-info.json")) ||
    (!fs.existsSync("./src/aws-exports.js"))
    ) {
    console.error("Amplify is not configured !!");
    console.log(" please run:");
    console.log(" > amplify init");
    console.log(" Select an existing environment (choose dev to start)");
    process.exit();
} else {
    amplifyMeta = require("./amplify/backend/amplify-meta.json");
    amplifyTeams = require("./amplify/team-provider-info.json");
}
const REGEX = /.*-(\w+)/;
const AMPLIFY_ENV = amplifyMeta.storage.amplifyIdentityBrokerCodesTable.output.Name.match(REGEX)[1];

console.log("Injecting config");
console.log("AMPLIFY_ENV is " + AMPLIFY_ENV);

var appHostingDomain = undefined;
if(amplifyTeams[AMPLIFY_ENV].categories.function.amplifyIdentityBrokerPostDeployment.hostingDomain) {
    appHostingDomain = amplifyTeams[AMPLIFY_ENV].categories.function.amplifyIdentityBrokerPostDeployment.hostingDomain;
} else if(amplifyMeta.hosting.S3AndCloudFront.output.CloudFrontDomainName) {
    appHostingDomain = "https://" + amplifyMeta.hosting.S3AndCloudFront.output.CloudFrontDomainName;
} else {
    console.log("WARNING : No hosting domain defined!!");
    process.exit();
}
...
```

But this does not solve the problem of easy removable components

**Other approach: plugin?**

Another approach I was thinking about was to use utils plugin and to embed them on my project to provide simpler command for my customers.
Like with preInit event I can prompt more configuration questions.
I am not sure it is a good approach and this is a bit of work.

Plus plugins will be installed for all Amplify projects my customer may use not only for mine which is not what they may like.

**Comment by josefaidt** [comment]
Closing in favor of [command hooks](https://docs.amplify.aws/cli/project/command-hooks/) which can allow you to further customize the behavior of Amplify before and after command execution. This can enable modifications to files such as `aws-exports.js` to surface properties from your backend that are not already available.
