### ISSUE TITLE
Using custom `ownerField:` with `@auth` should automatically generate schema with custom field

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/amplify-cli#5436]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When using `ownerField` in the `@auth`directive, the custom field should be present in the graphql schema

**Amplify CLI Version**
4.29.2

**To Reproduce**
Create a new iOS amplify project with the following graph ql schema
```gql
type Post @model @auth(rules: [{ allow: owner, ownerField: "dominus" }]) {
  id: ID!
  title: String!
}
```

Kick off model generation:
`amplify api gql-compile`

```gql
$ cat amplify/backend/api/scenarioatest4/build/schema.graphql|more
type Post {
  id: ID!
  title: String!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

**Expected behavior**
Expected output:
```gql
$ cat amplify/backend/api/scenarioatest4/build/schema.graphql|more
type Post {
  id: ID!
  title: String!
  dominus: String
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

Notice that `dominus: String` was automatically added because we are using `ownerField`

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Mac os
 - Node Version: v14.2.0

**Additional context**

**Comment by wooj2** [comment]
I believe this PR will address this issue:
https://github.com/aws-amplify/amplify-cli/pull/5455

**Comment by AaronZyLee** [comment]
> I believe this PR will address this issue:
> #5455

The PR addresses the output for modelgen but not the compiled graphql schema itself. I think this issue should go to the graphql tranformer package

**Comment by yuth** [comment]
@wooj do you also care about `groupsField` when its group auth?
