### ISSUE TITLE
How to use @before directive

### ISSUE THREAD

**Issue by Ko09** [aws-amplify/amplify-cli#5447]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
amplify API GraphQL 

**Amplify CLI Version** 
4.21.0

**What AWS Services are you utilizing?**
Appsync DynamoDB Amplify

**Provide additional details e.g. code snippets**
I tried to add pipeline resolver following #1055 proposal 2.
I created a schema like this.

```
type Report
@model(
  mutations: { create: "createReport" }
  queries: null
  subscriptions: null
)
@auth(rules: [{ allow: owner, ownerField: "id" }])
@before(mutation: create, function: "IsAlreadyReported", datasource: "ReportTable")
{
 id : ID!
 reporter : ID!
 reported : ID!
 enum : Detail!
}

```
After using amplify push I got this error. 
```
Unknown directive "before".
An error occured during the push operation: Unknown directive "before".
```

I guess I need to add this to somewhere. 

```
directive @before(mutation: ModelMutation!, function: String!, datasource: String!) ON OBJECT
directive @after(mutation: ModelMutation!, function: String!, datasource: String!) ON OBJECT
enum ModelMutation {
    create
    update
    delete
}
```
But Where ?

**Comment by nikhname** [comment]
Hi @Ko09 we don't support @before at the moment but we do have an RFC for it that you linked (https://github.com/aws-amplify/amplify-cli/issues/1055). I'll close this issue in favor of that but feel free to comment your use case or suggestions there.
