### ISSUE TITLE
Filter on null or "Not exists" for graphql fields

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#5456]
**Is your feature request related to a problem? Please describe.**

I can't filter on whether or not a field is null or "not exists"

**Describe the solution you'd like**

There are a couple ways of solving this, but the easiest solution I can think of is to allow this:

```
    const filter: ModelFooFilterInput = {
      field: { eq: null }
    };
    const results: ListFoosQuery = await this.apiService.ListStudyFoos(filter);
```

**Comment by SwaySway** [comment]
@malcomm I believe the filter you might be looking for in this scenario is if the attribute does not exist on the given record.
Given this schema
```gql
type Restaurant @model {
  id: ID!
  name: String!
  description: String!
  city: String!
}
```
If I wanted to filter by Restaurants that did not have a description then I would filter as follows:
```typescript
const service = new APIService();
const filter: ModelRestaurantFilterInput = {
    description: { attributeExists: false }
  };
const results: ListRestaurantsQuery = await service.ListRestaurants(filter);
```
If can also or them in the filter so it returns the field being null or the attribute not existing
```typescript
const filter: ModelRestaurantFilterInput = {
    or: [
      { description: { attributeExists: false } },
      { description: { eq: null } }
    ]
  }
```

**Comment by malcomm** [comment]
@SwaySway - that would be lovely; however, the filter input that amplfy-cli gives you is this:

```graphql
export type ModelStringFilterInput = {
  ne?: string | null;
  eq?: string | null;
  le?: string | null;
  lt?: string | null;
  ge?: string | null;
  gt?: string | null;
  contains?: string | null;
  notContains?: string | null;
  between?: Array<string | null> | null;
  beginsWith?: string | null;
};
```

`attributeExists` is not there and `eq: null` doesn't work.

**Comment by blazinaj** [comment]
@SwaySway Any follow up on this? We are trying to accomplish the same thing.

**Comment by blazinaj** [comment]
👀

**Comment by SwaySway** [comment]
Closing this issue as the current version of the transformer does generate the string filter input type which contains `attributeExists`. Please comment below if you don't see this input generated.

**Comment by wezside** [comment]
The error persist for me in 6.0.1. Simple List query from generated API.service with attributeExists filter. Running in Amplify Mock I can see the following error:

`ValidationException: Value provided in ExpressionAttributeValues unused in expressions: keys: {:date_requested_attributeExists}`

And then looking at the Dynamo output it's clear that the error here is that **expressionValues** is not actually needed. 

```
{
    "version": "2018-05-29",
    "limit": 100,
    "filter": {
        "expression": "attribute_not_exists(#date_requested)",
        "expressionNames": {
            "#date_requested": "date_requested"
        },
        "expressionValues": {
            ":date_requested_attributeExists": {
                "BOOL": false
            }
        }
    },
    "operation": "Scan"
}

```
