### ISSUE TITLE
Streaming DataStore to ElasticSearch should map _lastChangedAt as date type.

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#5470]
**Describe the bug**
Enable a DataStore's model with `@searchable` in `schema.graphql` to stream data to ElasticSearch.  By default, the `_lastChangedAt` field type is `float`. It should be `date` instead, otherwise it's impossible to query the correct records with that field.

**Amplify CLI Version**
4.29.3

**To Reproduce**
1. Schema.grapql.
2. Add @searchable to a model.
3. Add a record.
4. Open ElasticSearch and find out the indices.
5. Look at the mapping, the field type for `_lastChangedAt` is float by default.

**Expected behavior**
`_lastChangedAt` field type should be date.

**Screenshots**
![image](https://user-images.githubusercontent.com/762914/94907817-49efe080-04d3-11eb-8b82-582b332005b2.png)

**Comment by kaustavghosh06** [comment]
@nubpro __lastChangedAt is currently used for our datastore syncing protocol (https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html) and for accessing the last updated time for the record you could use the updatedAt field made available to you by default.
