### ISSUE TITLE
dev and prod environments no longer match

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5471]
**Which Category is your question related to?**

Amplify status

**Amplify CLI Version** 

4.29.3

**What AWS Services are you utilizing?**

`Current Environment: dev

| Category  | Resource name                   | Operation | Provider plugin   |
| --------- | ------------------------------- | --------- | ----------------- |
| Auth      | mbapp7945ad6e      | No Change | awscloudformation |
| Auth      | userPoolGroups                  | No Change | awscloudformation |
| Analytics | mbanalytics        | No Change | awscloudformation |
| Api       |mbappapi           | No Change | awscloudformation |
| Api       | mbappessubcheckapi | No Change | awscloudformation |
| Hosting   | S3AndCloudFront                 | No Change | awscloudformation || Storage   | mbapps3624b020f    | No Change | awscloudformation |
| Function  | mbappessubcheck    | No Change | awscloudformation |`

`Current Environment: prod

| Category | Resource name                | Operation | Provider plugin   |
| -------- | ---------------------------- | --------- | ----------------- |
| Auth     | mbapp7945ad6e   | No Change | awscloudformation |
| Api      | mbappapi        | No Change | awscloudformation |
| Hosting  | S3AndCloudFront              | No Change | awscloudformation |
| Storage  | mbapps3624b020f | No Change | awscloudformation |

`

I recently updated Amplify CLI before merging dev to prod. Somehow the two environments got out of sync.

After running: 

git checkout master
git merge develop
amplify status

I got this:

`Current Environment: prod

| Category  | Resource name                   | Operation | Provider plugin   |
| --------- | ------------------------------- | --------- | ----------------- |
| Api       | mbappapi           | Update    | awscloudformation |
| Storage   | mbapps3624b020f    | Update    | awscloudformation |
| Auth      | userPoolGroups                  | Delete    | awscloudformation |
| Analytics | mbanalytics        | Delete    | awscloudformation |
| Api       | mbappessubcheckapi | Delete    | awscloudformation |
| Function  | mbappessubcheck    | Delete    | awscloudformation |
| Auth      | mbapp7945ad6e      | No Change | awscloudformation |
| Hosting   | S3AndCloudFront                 | No Change | awscloudformation |
`

I then ran amplify push, now I'm left with

`Current Environment: prod

| Category | Resource name                | Operation | Provider plugin   |
| -------- | ---------------------------- | --------- | ----------------- |
| Auth     | mbapp7945ad6e   | No Change | awscloudformation |
| Api      | mbappapi        | No Change | awscloudformation |
| Hosting  | S3AndCloudFront              | No Change | awscloudformation |
| Storage  | mbapps3624b020f | No Change | awscloudformation |

`

How can I get prod updated as per my dev environment again?

**Comment by nikhname** [comment]
@christodupreez you could try running ```amplify env pull --restore``` to sync the prod env with dev.

**Comment by kaustavghosh06** [comment]
After running "git merge develop", you'd have to run "amplify env checkout <your-current-env-name>" as documented here - https://docs.amplify.aws/cli/teams/sandbox
Please let us know if you're still stuck.
