### ISSUE TITLE
Amplify Federated Sigin with Gmail needs Email as maindatory attribute 

### ISSUE THREAD

**Issue by nash567** [aws-amplify/amplify-cli#5472]
I started a new amplify project using amplify init. I added auth and used Username as Sig-in Method but i used Social providers with default Configuration and added Google and Facebook but in additional required attributes i removed Email and select none.Then i push the code it throws error about HostedUIProviders....

Then if i make email as required attribute it worked but with Facebook it causes error because not every Facebook user uses the email method some of them prefer mobile phones and other..

but before in amplify-cli version < @4.29.0 it does not throw any error.

**Comment by edwardfoyle** [comment]
It looks like this is the same issue reported in #5681 which has been fixed. Please follow up if you're still running into issues
