### ISSUE TITLE
Subscriptions on mutations with pipeline resolvers

### ISSUE THREAD

**Issue by pstance** [aws-amplify/amplify-cli#5473]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Subscriptions

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.29.2

**What AWS Services are you utilizing?**
AWS AppSync 

**Provide additional details e.g. code snippets**

I am attempting to subscribe to a mutation that has a pipeline resolver. When I attempt to do this, the subscription does not fire when the mutation is run. Is this use case supported?

**Comment by nikhname** [comment]
Hello @pstance, the CLI does not currently support pipeline resolvers but this is something we are working on.
Follow this RFC for those updates and some possible implementations: #1055
