### ISSUE TITLE
Multi environment lambda layer hard codes environment

### ISSUE THREAD

**Issue by davekiss** [aws-amplify/amplify-cli#5479]
**Describe the bug**
I have two environments and have created a new lambda layer. When I add the lambda layer to a function in the first environment, the CFN template for that function injects the current environment's layer value as a hard coded value from the env it was created in, rather than the environment that the build is/will be occurring in

https://github.com/aws-amplify/amplify-cli/blob/bffaded7351e3bfbcb67fede139b3dab7770eda4/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts#L154-L158

**Amplify CLI Version**
4.29.4

**To Reproduce**
1. Create two environments
2. Add a single lambda layer to both
3. Add the lambda layer to a function in environment A
4. Check the output of `Layers` in function-cloudformation-template.json – the value contains a hard-coded env

**Expected behavior**
The string value should contain a reference to `Ref:env` to pull the environment value from the current build environment rather than the environment where the layer was added to the function

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 10.15.3

**Additional context**

https://github.com/aws-amplify/amplify-cli/blob/bffaded7351e3bfbcb67fede139b3dab7770eda4/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/lambda-layer-cloudformation-template.ts#L154-L158

**Comment by ammarkarachi** [comment]
@davekiss #5072 is along the same lines, you can follow the updates there.

**Comment by jhockett** [comment]
Hi @davekiss, thanks for pointing this out. The `env` name is replaced with the current environment when you execute `amplify push`, however a using something like `Ref:env` would be better. I'm marking this as an enhancement.

**Comment by kenbankspeng** [comment]
Not sure if this is the same issue or not, but I have a multi env, and a lambda layer was created in env A. When I merged this into env B, although `amplify push` created a new lambda layer in env B, it linked the lambdas of env B to the layer of env A.

So, just my opinion, but I am struggling with the enhancement tag. To me, this means that amplify cli doesn't yet support layers in a multi env. If env B is production and env A is dev, sorry, but  I can't have production code dependent on a piece of dev code.

**Comment by davekiss** [comment]
@kenbankspeng @jhockett totally agree, it'd be one thing if the `amplify push` did replace the `env` value but that is not the case, `env` is only replaced when adding the layer to the lambda. This is a bug, not an enhancement.

**Comment by kenbankspeng** [comment]
I just performed a little test. I enhanced the lambda layer code in env B, did a push and as expected got a new version of the layer in env B, but was my jaw dropped after observing that the lambdas in env B still link to the now out-of-date code in layer A. Sorry, but a configuration management nightmare and not a feature that can be used for production. 

I do really appreciate the value that a lambda layer can add. I do hope this can be resolved quickly. Thank you.

**Comment by waynebrantley** [comment]
@davekiss Agree with you - this is a bug.   @jhockett - the env name is **not** replaced with the current environment when you execute `amplify push`

**Comment by jhockett** [comment]
Apologies, I misunderstood the issue and my previous comment didn't make sense (now edited to avoid confusion).

The reason I marked this as an enhancement, is because the layer referenced in the function can be updated with `amplify update function` to reference the new environment and correct version. This solution is tedious and we can definitely improve the developer experience here.

I think it's fair to expect the update to be automatic when performing `amplify env checkout`, so I'll change the label to a bug. Thanks for all the feedback!

**Comment by waynebrantley** [comment]
One thought would be:
- environment - have the ${env} in the name of the layer as suggested above.  This would mean the checkout code would not have to do anything when checking out different environments (as well as create environment not having to change).
- version - have a variable ${latestVersion} that always points to the latest version of the lambda for the given environment.  This would mean when checking out a new environment as long as the 'latest version' in that environment was set when creating/checking out.   If for some reason the 'layer' needed to be pinned - this would be a manual step - much like it is now.

Given these two ideas, seems like it would not be too bad of a fix?

**Comment by waynebrantley** [comment]
@jhockett Any update on this?

**Comment by aaronbrighton** [comment]
I've also ran into this issue attempting to use Lambda layers in a multi-environment team, would like to avoid having to run amplify update function each time someone pulls in code from others.

Any update?

**Comment by jhockett** [comment]
Hi all, we are actively looking into reworking how layer versions work in the CLI, so fixing this issue will likely either coincide or follow that update.

**Comment by gakinson** [comment]
Hey I noticed there was a fairly large amount of changes released in the latest version of Amplify. I was wondering if this was covered, it was not super clear if it was based on the changelog.

**Comment by jhockett** [comment]
> Hey I noticed there was a fairly large amount of changes released in the latest version of Amplify. I was wondering if this was covered, it was not super clear if it was based on the changelog.

Sorry for the confusion, but the layer versioning hasn't changed yet. I will update this issue as soon as there is more to share.

**Comment by akash87** [comment]
I was able to resolve it by replacing it with lambda layer arn in the cloudformation file. Layer ARN is available as an environment variable.

![image](https://user-images.githubusercontent.com/1129446/101285937-fc169200-380d-11eb-875e-8ba0287644b5.png)

**Comment by waynebrantley** [comment]
@akash87 That is a fantastic solution!  
@jhockett The layer thing needs some attention in a big way.
In fact, a great solution would be to let lambda's in an amplify project reference javascript files outside of their folder.  This is probably the 80% use case anyway - just some shared code among a few lambdas.  Don't necessarily need the whole shared layer concept.

In the meantime a change to the above would help anyone using lambda.  For now, a few manual edits and this is much better.

**Comment by tomhirschfeld** [comment]
@jhockett anything else to share here? Layers are really slowing our productivity down

**Comment by jhockett** [comment]
Apologies, not yet. We've had to prioritize work for the admin UI in the past few months, but I expect to return to working on layers shortly. I'll do my best to update any related issues once we have improvements ready. Thank you for your patience!

**Comment by Nxtra** [comment]
> I was able to resolve it by replacing it with lambda layer arn in the cloudformation file. Layer ARN is available as an environment variable.
> 
> ![image](https://user-images.githubusercontent.com/1129446/101285937-fc169200-380d-11eb-875e-8ba0287644b5.png)

Thanks for this workaround.

Is this consistent? 
- When I create a new layer version and update my function to use that version, will this be overwritten then?

**Comment by PavloNaumenko** [comment]
I'm going to use these rules on my project to get around the problem:
- use Lambda Layers only for packages storing
- don't use env in a lambda layer name

For it, we need to do:
- create a new layer with `amplify function add`
- change LayerName in the template of new function `myLayer-awscloudformation-template.json`
from:
```
{
...
  "Resources": {
    "LambdaLayer": {
      ...
        "LayerName": {
          "Fn::Sub": [
            "myLayer-${env}",
            {
              "env": {
                "Ref": "env"
              }
            }
          ]
        }
   }
...
}
```

to 


```
{
...
  "Resources": {
    "LambdaLayer": {
      ...
        "LayerName": {
         "Fn::Sub": "myLayer"
        }
   }
...
}
```

**Comment by danielvouch** [comment]
Any updates on this would be great ?

**Comment by StefanV85** [comment]
+1

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!

**Comment by jlecren** [comment]
> Hi all!
> 
> We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.
> 
> **DO NOT USE THIS IN PRODUCTION!**
> 
> To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

I tried to migrate my project on this version but I got an error in the generated CloudFormation file (I made the layer accessible from my whole organization):
```
Resource Name: LambdaLayerPermissionAwsOrgoxxxxx1857pLegacy1Legacy1 (AWS::Lambda::LayerVersionPermission)
Event Type: create
Reason: 1 validation error detected: Value 'o-xxxxx1857pLegacy1' at 'organizationId' failed to satisfy constraint: Member must satisfy regular expression pattern: o-[a-z0-9]{10,32} (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: 5017624e-da55-4687-83e1-d370bae99a21)
``` 

By the way, the environment and the version are still hard-coded in LayerVersionArn of the layer permission:
```json
"LambdaLayerPermissionPrivate144bc277": {
      "Type": "AWS::Lambda::LayerVersionPermission",
      "Properties": {
        "Action": "lambda:GetLayerVersion",
        "LayerVersionArn": "arn:aws:lambda:eu-west-1:XXXXXXXXXXXX:layer:BackendLayer-testb:4",
        "Principal": {
          "Ref": "AWS::AccountId"
        }
      }
    }
```

My guess is that the layer version used by the functions shall be placed in the file "team-provider-info.json" as it is environment-dependant. 
As for Layer version permissions, this is more tricky because the number of layer versions of each environment might differ so they can't just be listed in the cloudformation template.

**Comment by jhockett** [comment]
Thanks for the valuable feedback @jlecren! The first issue is definitely a bug, so thank you for the report.
 
> By the way, the environment and the version are still hard-coded in LayerVersionArn of the layer permission:
> 
> ```json
> "LambdaLayerPermissionPrivate144bc277": {
>       "Type": "AWS::Lambda::LayerVersionPermission",
>       "Properties": {
>         "Action": "lambda:GetLayerVersion",
>         "LayerVersionArn": "arn:aws:lambda:eu-west-1:XXXXXXXXXXXX:layer:BackendLayer-testb:4",
>         "Principal": {
>           "Ref": "AWS::AccountId"
>         }
>       }
>     }
> ```

When you push in a new environment, the CFN template will be updated accordingly. We don't use refs for the env name because layer versions are specific to each environment, and so are the associated layer version permissions.

> My guess is that the layer version used by the functions shall be placed in the file "team-provider-info.json" as it is environment-dependant.
> As for Layer version permissions, this is more tricky because the number of layer versions of each environment might differ so they can't just be listed in the cloudformation template.

It depends on if you use the new "Latest version" setting or if you pin a specific version. You can use `amplify update function` to try it out.
