### ISSUE TITLE
Custom Permissions to Functions created with Amplify

### ISSUE THREAD

**Issue by brahama** [aws-amplify/amplify-cli#5480]
**Amplify CLI Version** 

4.29.1

I've seen this question around but never answered really. 

How can we add IAM permissions to the function generated via Amplify so that it does not get overwritten on an update or following push.

Simple use case.
I have a function created that I want it to access iot:* via SDK but of course there is no option to add these kind of perms at list during the cli config.

We end up modifying the function-template.json adding the iam permissions by hand.

Which is the correct way to do this? is there a correct way? is there some feature coming for this?

Thanks!

**Comment by ammarkarachi** [comment]
You could create a policy and reference the policy using the custom cfn feature of the cli. https://docs.amplify.aws/cli/usage/customcf
