### ISSUE TITLE
Amplify push fails with error creating directory 

### ISSUE THREAD

**Issue by varmab** [aws-amplify/amplify-cli#5483]
**Describe the bug**
After adding api via amplify add api, then trying to push changes to cloud using amplify push, I receive following error at the time of adding resources to local folder

✖ An error occurred when pushing the resources to the cloud

EROFS: read-only file system, mkdir '/graphql'
An error occurred during the push operation: EROFS: read-only file system, mkdir '/graphql'

I am on Mac. My previous CLI version was worked perfectly fine. Latest version giving this problem.
I am doing this under fresh React Native CLI project. 

**Amplify CLI Version**
4.29.4

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.16.2

**Additional context**

**Comment by ammarkarachi** [comment]
can you `ls -l` from a glance it looks like the user does not have permissions to create the `/graphql` directory

**Comment by yarwest** [comment]
I am having the exact same issue, it seems to be an issue related to the root directory on mac being read-only, but the push is failing because the directory can't be created

**Comment by kaustavghosh06** [comment]
Seems like a folder permission issue locally and not directly tied to the amplify cli. Try using sudo with the amplify command if you're still facing this issue.

**Comment by testflyjets** [comment]
> Seems like a folder permission issue locally and not directly tied to the amplify cli. Try using sudo with the amplify command if you're still facing this issue.

You shouldn't need to run this with sudo. Why is the command trying to write to the root directory? Where is this specified? Seems to me like the CLI default of "/" is incorrect.

**Comment by kaustavghosh06** [comment]
Which command are you trying to run @testflyjets? The CLI doesn't alter any files in / but it does store the AWS tokens in your ~/.aws folder and generates artifacts from where you're trying to run the CLI command.

**Comment by testflyjets** [comment]
![Screen_Shot_2020-10-07_at_1_59_53_PM](https://user-images.githubusercontent.com/160552/95387497-a3765780-08a5-11eb-8234-e9b20da0c01a.png)

The `amplify init` call seems to use `/` as a path -- could this be the issue?

**Comment by kaustavghosh06** [comment]
@testflyjets This is the root or '/' path  relative to your project-path not the system root.

**Comment by testflyjets** [comment]
Okay, but this still doesn't explain why the tool is trying to write to `/graphql` -- are you saying that path is a relative local path to the project? If the previous version of the CLI didn't require sudo to complete this action then this would seem to be a reversion, and this issue shouldn't be closed.

**Comment by WillTinney** [comment]
I'm also having the same problem with amplify-cli 4.29.4. Sudo-ing amplify push doesn't solve the issue

**Comment by ammarkarachi** [comment]
What permission are set on your root folder it would help me debug the problem?

**Comment by WillTinney** [comment]
Permissions on the root folder are ```drwxr-xr-x```

**Comment by WillTinney** [comment]
May or may not be relevant, but I ```amplify init``` this project today after upgrading to the latest cli version

**Comment by ammarkarachi** [comment]
>May or may not be relevant, but I amplify init this project today after upgrading to the latest cli version

Version 4.29.4?

**Comment by WillTinney** [comment]
> > May or may not be relevant, but I amplify init this project today after upgrading to the latest cli version
> 
> Version 4.29.4?

Yep

**Comment by ammarkarachi** [comment]
@WillTinney I could reproduce it with npx react-native? @testflyjets are you using npx too?

**Comment by testflyjets** [comment]
Yes, I was using npx react-native.

**Comment by mgiorgi-github** [comment]
same issue

**Comment by mgiorgi-github** [comment]
I've set 777 permission on graphql folder... the script don't return error but the folder is empty

**Comment by RandyLarzabal** [comment]
I encountered the same issue, I think it came from the file .grzphqlconfig.yml . the path shown in the schemepath wasnt right, when I changed it the issue was fixed

**Comment by mgiorgi-github** [comment]
Hi', where is this file?

**Comment by ikmwt** [comment]
exactly same issue on amplify version 4.29.4

**Comment by testflyjets** [comment]
I retried the `amplify push` command and changed the two paths that default to `/` to `./` and the command completed successfully. I am on Mac OS 10.15.7, FWIW.

**Comment by ikmwt** [comment]
> I retried the `amplify push` command and changed the two paths that default to `/` to `./` and the command completed successfully. I am on Mac OS 10.15.7, FWIW.
This worked for me! Thanks!!!

**Comment by ikmwt** [comment]
@testflyjets  This worked for me! Thanks!!

**Comment by Injae-Lee** [comment]
Until version 4.29.3, `amplify-codegen` was hard coded to generate output in `src` directory.
In version 4.29.4, `amplify-codegen` generates output in `SourceDir`.

So you should change `javascript.config.SourceDir` to `"src"`(your source dir) in `amplify/.config/project-config.json`, remove `.graphqlconfig.yml`, and run `$amplify codegen add` `$amplify init`.

**Comment by LeSampsonConnor** [comment]
Following the comment from @Injae-Lee comment, I changed SourceDir inside of the project-config.json to "./" and ran amplify codegen which worked for me.

**Comment by varmab** [comment]
> I retried the `amplify push` command and changed the two paths that default to `/` to `./` and the command completed successfully. I am on Mac OS 10.15.7, FWIW.

Super.. this worked for me. I am using CLI 4.29.6

![image](https://user-images.githubusercontent.com/4167060/95699673-c2d50200-0c62-11eb-80c0-625b087a1999.png)

**Comment by ajnunez16** [comment]
same

**Comment by wei** [comment]
I can reproduce with CLI 4.30.0. The solutions above works great!

**Comment by Finneah** [comment]
Change to `./`didnt worked for me. 
`amplify codegen` also failed because of `EROFS: read-only file system, mkdir '/graphql'`

Funny but my solution was to mock first. 
1. `amplify mock api` 
2. `amplify push`

https://docs.amplify.aws/start/getting-started/data-model/q/integration/react-native#deploying-the-api

> (Optional) Test your API
To test this out locally, you can run the mock command.

>If you’d like to go ahead and deploy the API, you can jump to the next step.

**Comment by wei** [comment]
@Finneah 

1. Change `/` to `./` in `amplify/.config/project-config.json`
2. Remove `.graphqlconfig.yml`
3. Run `amplify codegen add`
4. Run `amplify push`
Alternatively, start fresh and use `./` as both directory paths

I think the file in step 2 is cached so you have to remove that too.

**Comment by Finneah** [comment]
> @Finneah
> 
> 1. Change `/` to `./` in `amplify/.config/project-config.json`
> 2. Remove `.graphqlconfig.yml`
> 3. Run `amplify codegen add`
> 4. Run `amplify push`
>    Alternatively, start fresh and use `./` as both directory paths
> 
> I think the file in step 2 is cached so you have to remove that too.

@wei 
I tried both. But without step 2. Change the dir and make a fresh start with changed dir didn’t worked. But with Step 2 it’s a good idea. I give it a try next time 👍

**Comment by angelinfante** [comment]
> I retried the `amplify push` command and changed the two paths that default to `/` to `./` and the command completed successfully. I am on Mac OS 10.15.7, FWIW.

Thank you very much @testflyjets !!!

**Comment by wei** [comment]
[Docs](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native#initialize-a-new-backend) updated in aws-amplify/amplify-cli#5483. 
CLI update is pending in #5654.

**Comment by ntmk** [comment]
In my case in the `.graphqlconfig.yml` the `schemaPath:` property was somehow set to `/../../../../../../schema.graphql` when it was auto generated. My fix was to update the path to `amplify/backend/api/<api name>/build/schema.graphql`

**Comment by dave-nicholas** [comment]
The following solved the issue for me.

`amplify mock api` to create `.graphqlconfig.yml`
Then edit the schema path from `../../../../graphql/schema.json` to `./amplify/backend/api/YUOR_PROJECT_NAME/build/schema.json`

**Comment by hafidzdaud** [comment]
Problem:
I was working on https://github.com/aws-samples/aws-amplify-react-native-events-app-workshop/ with same issue:

EACCES: permission denied, mkdir '/graphql'
An error occurred during the push operation: EACCES: permission denied, mkdir '/graphql'

To resolve:
1. rename /code/.graphqlconfig.yml to .bak and then delete (will be recreated with amplify push)
2. updated path "/" to "./" in amplify/.config/project-config.json

Verify:
amplify push (completed without errors)

**Comment by avinash273** [comment]
This worked for me as well:
Problem:
I was working on https://github.com/aws-samples/aws-amplify-react-native-events-app-workshop/ with same issue:

EACCES: permission denied, mkdir '/graphql'
An error occurred during the push operation: EACCES: permission denied, mkdir '/graphql'

To resolve:

rename /code/.graphqlconfig.yml to .bak and then delete (will be recreated with amplify push)
updated path "/" to "./" in amplify/.config/project-config.json
Verify:
amplify push (completed without errors)

**Comment by dylvaz** [comment]
> Problem:
> I was working on https://github.com/aws-samples/aws-amplify-react-native-events-app-workshop/ with same issue:
> 
> EACCES: permission denied, mkdir '/graphql'
> An error occurred during the push operation: EACCES: permission denied, mkdir '/graphql'
> 
> To resolve:
> 
> 1. rename /code/.graphqlconfig.yml to .bak and then delete (will be recreated with amplify push)
> 2. updated path "/" to "./" in amplify/.config/project-config.json
> 
> Verify:
> amplify push (completed without errors)

This worked for me!

**Comment by SpirosJohn** [comment]
> I retried the `amplify push` command and changed the two paths that default to `/` to `./` and the command completed successfully. I am on Mac OS 10.15.7, FWIW.

I tried the `amplify push`

✖ An error occurred when pushing the resources to the cloud

EROFS: read-only file system, mkdir '/graphql'
An error occurred during the push operation: EROFS: read-only file system, mkdir '/graphql'

Am using Expo and NPM

I saw yours did pass the amplify push can you help me and when you changed can you reference me the new path you puted?

**Comment by SpirosJohn** [comment]
Thanks it resolved

with

Problem:
I was working on https://github.com/aws-samples/aws-amplify-react-native-events-app-workshop/ with same issue:

EACCES: permission denied, mkdir '/graphql'
An error occurred during the push operation: EACCES: permission denied, mkdir '/graphql'

To resolve:

rename /code/.graphqlconfig.yml to .bak and then delete (will be recreated with amplify push)
updated path "/" to "./" in amplify/.config/project-config.json
Verify:
amplify push (completed without errors)

**Comment by bajuhaat** [comment]
> ![Screen_Shot_2020-10-07_at_1_59_53_PM](https://user-images.githubusercontent.com/160552/95387497-a3765780-08a5-11eb-8234-e9b20da0c01a.png)
> 
> The `amplify init` call seems to use `/` as a path -- could this be the issue?

I recreated app usingg ./ and amplify push worked!!

**Comment by schieble** [comment]
> I encountered the same issue, I think it came from the file .grzphqlconfig.yml . the path shown in the schemepath wasnt right, when I changed it the issue was fixed

There is an issue when this file is generated sometimes(never experienced before).   My schemaPath was something like ../../../../../../src ...     which when corrected to ./src/ ... everything was fine
