### ISSUE TITLE
How can I trigger an error from Lambda with an error code/type? (like VTL templates)

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5485]
Hello,

When using AppSync, we can use something like this when writing a VTL template:
`$util.error(String, String)`
where the first parameter is the error message and the second one is the error code/type.

Some times, instead of using VTL templates, I use lambda functions, which is very easy with something like this in my GraphQL schema:
`saveVisit(userId: ID!): Boolean! @function(name: "saveVisit-${env}")`

The thing is, I need to get a code or type in my app apart from a message, because my app does different things depending on the error code, and it is not very nice or safe to do that processing a message that is aimed for humans.

When writing a lambda function with NodeJS, we use 
`throw new Error('this is an error')`
But I don't know how to pass an error code/type to GraphQL.

How can I do that?
Thanks a lot.

**Comment by ammarkarachi** [comment]
@Ricardo1980 you can created a custom error in your Lambda
```js

class CustomError extends Error{ 
  constructor(message){
  super(message);
 }
} 
throw new CustomError("Custom Message")
```
Your graphql response will be then, you can use the `errorType` to handle you custom logic case.
```json
{
  "data": {
    "query": null
  },
  "errors": [
    {
      "path": [
        "query"
      ],
      "data": null,
      "errorType": "CustomError",
      "errorInfo": null,
      "locations": [
        {
          "line": 5,
          "column": 10,
          "sourceName": null
        }
      ],
      "message": "Custom Message"
    }
  ]
}
```

**Comment by Ricardo1980** [comment]
Thanks @ammarkarachi 
But that is not working.

Here my lambda:


```
exports.handler = async (event) => {
	class EmailIncorrectFormat extends Error{ 
		constructor(message) {
			super(message);
		}
	}
	const email = event.arguments.email;
	if (!checkValidEmail(email)) {
		// var error = new Error('Incorrect email format');
		// error.name = 'EMAIL_INCORRECT_FORMAT';
		// throw error
		throw new EmailIncorrectFormat("Incorrect email format");
	}
        .......
}
```

And this is what my iOS receives through AppSync/GraphQL.
```

{
  "data": null,
  "errors": [
    {
      "path": [
        "verifyEmail"
      ],
      "data": null,
      "errorType": "Lambda:Unhandled",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Incorrect email format"
    }
  ]
}
```

As you can see, errorType has Lambda:Unhandled
I also tried using error.name = 'MyCustomCode', but same result.
Any suggestion?
Thanks a lot!

**Comment by ammarkarachi** [comment]
@Ricardo1980 Sorry for the delay, you will have to add the following in your VTL template
```
#if( $context.result && $context.result.error_message )
    $util.error($context.result.error_message, $context.result.error_type, $context.result.error_data)
#else
    $util.toJson($context.result)
#end
```

**Comment by Ricardo1980** [comment]
@ammarkarachi The problem is, there is no template.

Including this:
saveVisit(userId: ID!): Boolean! @function(name: "saveVisit-${env}")
in my schema.graphql file, does not require VTL template. At least, in that specific case.

I saw a tweet saying it is not possible in this scenario.
https://twitter.com/bensie/status/1293981141645635593
Can you conform that?
If that is the case: what do you recommend me as a workaround (perhaps, using the message field).
Can you add this to your backlog?
Thanks a lot.

**Comment by Nxtra** [comment]
> @ammarkarachi The problem is, there is no template.
> 
> Including this:
> saveVisit(userId: ID!): Boolean! @function(name: "saveVisit-${env}")
> in my schema.graphql file, does not require VTL template. At least, in that specific case.
> 
> I saw a tweet saying it is not possible in this scenario.
> https://twitter.com/bensie/status/1293981141645635593
> Can you confirm that?
> If that is the case: what do you recommend me as a workaround (perhaps, using the message field).
> Can you add this to your backlog?
> Thanks a lot.

Isn't the function set up by Amplify as a pipeline resolver which still has mapping templates for the request or response?

**Comment by Ricardo1980** [comment]
@Nxtra 
Where are those mappings?
There are no mappings.
I think there is something autogenerated but if you modify that, amplify will overwrite it!

**Comment by Nxtra** [comment]
> @Nxtra
> Where are those mappings?
> There are no mappings.
> I think there is something autogenerated but if you modify that, amplify will overwrite it!

For example they can be in `amplify/backend/api/yourapiname/resolvers` and ``amplify/backend/ap/pipelineFunctions`. 
If you specify a template there yourself, amplify will not override it in the build directory.

**Comment by kaustavghosh06** [comment]
Closing based on @Nxtra's response. @Ricardo1980 please let us know if you need more help around this.

**Comment by Nxtra** [comment]
I worked out the following procedure. Let me know if this is what you are trying to accomplish.

Goal: Create a Lambda Resolver with a custom Request and Response Mapping Template

Steps:
1. `schema.graphql`
```
saveVisit(userId: ID!): Boolean! @function(name: "saveVisit-${env}")
```

2. Lambda function:
* `amplify add function`
* name of the function: `saveVisit`
* content of the function, here dummy content to show different behavior:
```
exports.handler = async (event) => {
  const { userId } = event.arguments;
  const randomNumber = Math.floor(Math.random() * 10 + 1);
  let response;

  if (randomNumber % 3 === 0) {
    response = userId;
  } else if (randomNumber % 3 === 1) {
    response = { errorMessage: `Something went wrong for ${userId}`, errorType: "ERROR" };
  } else {
    throw new Error("Serious unhandled problem occured");
  }
  return response;
};
```
Attention here: ```response = { errorMessage: `Something went wrong for ${userId}`, errorType: "ERROR" };``` -> is where we return an errorMessage and type without explicitly having to throw an error.

3. Request and Response mapping templates. You have to create the map `pipelineFunctions` in your backend/api directory.  
* In `amplify/backend/thenameofyourapi/pipelineFunctions` create file InvokeSaveVisitLambdaDataSource.req.vtl`:
```
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": "$ctx.stash.get("typeName")",
      "fieldName": "$ctx.stash.get("fieldName")",
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
```
* In `amplify/backend/thenameofyourapi/pipelineFunctions` create file InvokeSaveVisitLambdaDataSource.res.vtl`:
```
#if( $context.result && $context.result.errorMessage )
  $utils.error($context.result.errorMessage, $context.result.errorType)
#elseif( $ctx.error )
  $util.error($ctx.error.message, $ctx.error.type)
#else
  $utils.toJson($context.result)
#end
```
The first line allows you to capture intended errorMessages without having to explicitly throw an error in your function.

4. deploy
`amplify deploy --y`

5. AppSync console.  
Test it out a few times to see different errors come back.
1 in 3 will give you no error, 1 in 3 will return handled error, 1 in 3 will be unhandled error.
