### ISSUE TITLE
AdminQueries ApiGW fails with 500 in some environments / tries to call wrong Function ARN

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#5491]
Might be related to 
https://github.com/aws-amplify/amplify-cli/issues/5309

**Describe the bug**
I have two separate environments that are pretty much the same except some language settings (and seperate UserPool, DB etc). I deploy both at the same time leading to https://github.com/aws-amplify/amplify-cli/issues/5309 this issue. Normally A goes through (the Github trigger for A seems to be sent first so it starts building some milliseconds before B) and B times out making me hit the "re deploy" button on B.

Using the AdminQueries API in A works just fine. 
Using it in B returns a 500 `x-amzn-errortype	InternalServerErrorException`
no additional logs. The AdminQuery lambda does not trigger (has no logs). 
Trying to trigger this via the API GW console (proxy) makes the lambda trigger but the it fails because "claims" were undefined. 

I have no idea where to go from here.

All other functionality (i.e. Appsync etc) works fine in both apps. 

**Live update:**
Managed to find the "How to enable logs of API Gateway" article

Issue is now: 
`Execution failed due to configuration error: Invalid permissions on Lambda function`

It seems it is sending the request to an ARN that doesn't exist and is not mentioned anywhere else?

```
Sending request to https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-west-1:myAccountNumber:function:AdminQueriesa7beb8a4-prodse/invocations
```

vs

`arn:aws:lambda:eu-west-1:myAccountNumber:function:AdminQueries24db8511-prodse`

(Environment A for the record is `arn:aws:lambda:eu-west-1:myAccountNumber:function:AdminQueries24db8511-prodno`)

Which is the same everywhere in Cloudformation it seems like 
```
     "functionAdminQueries24db8511Arn": {
            "Type": "String",
            "Default": "functionAdminQueries24db8511Arn"
          },
``` 

even the API Gateway console points me towards 24db8511

prodno (Environment A) logging gives me 

```
(b03df27c-6286-4b85-885b-49569b737b6a) Sending request to https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-west-1:myAccountNumber:function:AdminQueries24db8511-prodno/invocations
```

**Comment by ammarkarachi** [comment]
What version of CLI are you using?

It looks like the function name isn't getting updated when a new environment is created

**Comment by Zanndorin** [comment]
These environments are actually fully done via the "Amplify pipeline"

For environment A and B (and also dev etc)
```
Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-10-05T12:07:12.171Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.29.4...
2020-10-05T12:08:00.835Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```

**Comment by Zanndorin** [comment]
Called AWS Support and they made it work magically. I suspect some weird Edge Cache
