### ISSUE TITLE
Programmatically rotating API keys without amplify publish - is it possible?

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#5494]
**Which Category is your question related to?**
Amplify API

**Amplify CLI Version** 
4.29.2

**What AWS Services are you utilizing?**
Amplify, AppSync, and CloudFront

**Provide additional details e.g. code snippets**
Hi, so currently my understanding is that if I want to rotate an API key for an AppSync GraphQL API deployed using Amplify, I would need to follow [these instructions](https://docs.amplify.aws/cli/graphql-transformer/config-params#createapikey), those being:

1. *Delete the existing API key by setting `CreateAPIKey` to 0 in the `amplify/backend/api/<apiName>/parameters.json` file and execute `amplify push`.*
1. *Create a new API key by setting `CreateAPIKey` to 1 in the `amplify/backend/api/<apiName>/parameters.json` file and execute `amplify push`.*

I followed these steps, but the GraphQL API still returns a "You are not authorized to make this call." error, the same as what happens when I remove the API key and don't create a new one. After discussing this issue with another dev on my team, we realized that we also need to publish our frontend app using `amplify publish` and invalidate our CloudFront caches for the frontend app in order for the GraphQL API to work again.

I am just wondering if these two extra steps are in fact required when rotating API keys for a frontend app that's deployed with CloudFront, or if there's another way of doing it that doesn't require full frontend publish? Thanks in advance.

**Comment by UnleashedMind** [comment]
API key rotation itself only requires the two steps you listed above.
However, the API key is used to configure your frontend Amplify Library, you can see it in the `scr/aws-export.js` file if you are using the default configuration, the API key is the `"aws_appsync_apiKey"`.
So, if you have already published your frontend, then yes, you need to publish again so your frontend will be configured to use the updated API Key to access the AppSync service.

**Comment by Coteh** [comment]
Yes, I noticed that field in `aws-exports.js` earlier. Makes sense that I would need to republish in order to have the frontend use the new key. Thanks, feel free to close.
