### ISSUE TITLE
amplify-appsync-simulator - Velocity render don't handle unknow error correctly.

### ISSUE THREAD

**Issue by chucre** [aws-amplify/amplify-cli#5502]
**Describe the bug**
I'm using [bboure/serverless-appsync-simulator](https://github.com/bboure/serverless-appsync-simulator) which is using `amplify-appsync-simulator`. When I use the DynamoDB operation `TransactWriteItems` (which isn't supported in the simulator yet) it stops the execution but doesn't show any useful information. 

**Amplify CLI Version**
The version of `amplify-appsync-simulator` we use is 1.23.3

**To Reproduce**
Map a function (unit or pipeline) that uses a data source of type DynamoDB and use the operation `TransactWriteItems`. 

```velocity
{
    "version" : "2018-05-29",
    "operation" : "TransactWriteItems",
    "transactItems": [
        {
            "table": "YOUR_TABLE_NAME",
            "operation" : "UpdateItem",
            "key" : $util.dynamodb.toMapValuesJson({
              "id": "someId"
            }),
            "update" : {
                "expression" : "SET started_at = :timestamp",
                "expressionValues" : {
                    ":timestamp" : { "N" : ${util.time.nowEpochSeconds()} }
                }
            },
            "condition" : {
                "expression" : "(attribute_not_exists(started_at))"
            }
        }
    ]
}
```

execute the mutation or query associated like: 
```graphql
mutation {
  sendTextMessage(patient_user_id: "local|my_local_id", text: "test") {
    text
    id
  }
}
```

you will get something like: 
```json
{
  "data": {
    "sendTextMessage": null
  },
  "errors": [
    {}
  ]
}
```

**Expected behavior**
After execute the query we should have a useful error, something like:

```json
{
  "data": {
    "sendTextMessage": null
  },
  "errors": [
    {
      "message": "Unknown operation name: TransactWriteItems",
      "errorType": "UnknowErrorType",
      "data": null,
      "errorInfo": null,
      "path": [
        "sendTextMessage"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": "GraphQL request"
        }
      ]
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Node Version: v12.16.1

**Comment by edwardfoyle** [comment]
The fix for this has been released in CLI v 4.32.0
