### ISSUE TITLE
Pandas import through amplify CLI layer not working

### ISSUE THREAD

**Issue by alstorm96** [aws-amplify/amplify-cli#5506]
When creating layer for pandas library in python runtime 3.8.5 using amplify cli. It throws this error.

[ERROR] Runtime.ImportModuleError: Unable to import module 'index': Unable to import required dependencies:

numpy:

 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

 

Importing the numpy C-extensions failed. This error can happen for

many reasons, often due to issues with your setup or how NumPy was

installed.

 

We have compiled some common reasons and troubleshooting tips at:

 

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

 

Please note and check the following:

 

  * The Python version is: Python3.8 from "/var/lang/bin/python3.8"

  * The NumPy version is: "1.19.2"

 

and make sure that they are the versions you expect.

Please carefully study the documentation linked above for further help.

 

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by ammarkarachi** [comment]
@alstorm96 If you could share steps you followed to create the lambda layer it would help debugging the issue.

**Comment by alstorm96** [comment]
I used two ways to import the pandas layer both didnt work.

Method 1- Using amplify CLI. Steps are as follows
In my existing amplify project i used these commands:-

>amplify add function
? Select which capability you want to add:
> Lambda layer (shared code & resource used across functions)
? Provide a name for your Lambda layer: layertd
? Select up to 2 compatible runtimes:
o NodeJS
o Python(Selected python)
? The current AWS account will always have access to this layer.
  Optionally, configure who else can access this layer. (Hit <Enter> to skip)
 ◯ Specific AWS accounts
 ◯ Specific AWS organization
 ◯ Public (everyone on AWS can use this layer)- I used public

>cd amplify/backend/function/layertd/lib/python/lib/python3.8/site-packages
>pip install pandas -t .

❯ amplify add function
? Select which capability you want to add:
> Lambda function (serverless function)
? Provide a friendly name for your resource to be used as a label for this category in the project:
> myfunction
? Provide the AWS Lambda function name:
> myfunction
? Choose the runtime that you want to use:
> Python
? Choose the function template that you want to use:
> Hello World
? Do you want to access other resources in this project from your Lambda function?
> No
? Do you want to invoke this function on a recurring schedule?
> No

? Do you want to configure Lambda layers for this function?
> Yes
? Provide existing layers or select layers in this project to access from this function (pick up to 5):
> layertd
? Select a version for layertd:
> 1

? Do you want to edit the local lambda function now?
> No

amplify push -y

**Comment by alstorm96** [comment]
Method 2 using aws cloud9.
Created a function and api gateway through amplify cli then manually created zip file for pandas through cloud9. Published it for my python 3.8 runtime. Added it. Still no success
