### ISSUE TITLE
Remove auth attribute from required but still it's create as required

### ISSUE THREAD

**Issue by lochawala** [aws-amplify/amplify-cli#5507]
**Describe the bug**
when i add auth in amplify and removing email from required attribute still it's create as required

**Amplify CLI Version**
4.29.3

**To Reproduce**

amplify add auth
Do you want to use the default authentication and security configuration?
❯ Default configuration
How do you want users to be able to sign in?
❯ Email or Phone Number
Do you want to configure advanced settings?
❯ Yes, I want to make some additional changes.
What attributes are required for signing up?
❯ unselect Email
Do you want to enable any of the following capabilities?
❯ hit enter
amplify push

**Expected behavior**
create userpoll as not required email attribute

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.1

**Comment by kaustavghosh06** [comment]
This issue is fixed as a part of this PR - https://github.com/aws-amplify/amplify-cli/pull/6445 and is part of the latest version of the CLI.
