### ISSUE TITLE
amptify init, Can't choose the type

### ISSUE THREAD

**Issue by YuK1Game** [aws-amplify/amplify-cli#5509]
**Describe the bug**
Can't choose the type

**Amplify CLI Version**
4.29.4

**To Reproduce**
command `$ amplify init` runned.

**Expected behavior**

**Screenshots**
![WS000000](https://user-images.githubusercontent.com/20548753/95298261-c2c9b080-08b6-11eb-952e-01d0686e0d70.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Node Version: v13.14.0

**Comment by YuK1Game** [comment]
push enter

```
? Choose the type of app that you're building 
 (node:4772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
```

**Comment by ammarkarachi** [comment]
@YuK1Game Which terminal are you using?

**Comment by MaxDesiatov** [comment]
This is reproducible for me on macOS 10.15.7 (19H2), I'm using the standard built-in terminal:

![maxdesiatov_2020-Oct-07](https://user-images.githubusercontent.com/112310/95382675-ece49800-08e1-11eb-9bd2-5d6e1df9567f.jpg)

**Comment by kaustavghosh06** [comment]
Amplify CLI does not have support for npx yet. You'll have to install the CLI globally to make it work using `npm install -g @aws-amplify/cli` command.

**Comment by MaxDesiatov** [comment]
Thanks. Shouldn't the error message explicitly specify that `npx` is not supported instead of throwing `UnhandledPromiseRejectionWarning`?

**Comment by kaustavghosh06** [comment]
Agreed. I'll mark this as a bug and we'll work on displaying a helpful message. Apologize for the confusion.

**Comment by renebrandel** [comment]
@YuK1Game / @MaxDesiatov can confirm that it works if you just use `amplify init` (globally installed) vs using npx?

**Comment by YuK1Game** [comment]
I added using `$ yarn global add @aws-amplify/cli`
and using Windows default terminal (Command Prompt)

`$ amplify init` works.
But not before.
I can't select an app type.

![WS000001](https://user-images.githubusercontent.com/20548753/95407246-6d91ab80-0957-11eb-8d9b-1781be442282.jpg)

thanks

**Comment by YuK1Game** [comment]
I use a global install.
`$ yarn global add @aws-amplify/cli`

```
$ where amplify
C:\Users\user_name\AppData\Local\Yarn\bin\amplify
C:\Users\user_name\AppData\Local\Yarn\bin\amplify.cmd
C:\Users\user_name\AppData\Local\Yarn\bin\amplify.cmd
```

Once you do, delete it and run it in npx.
`npx amplify init`

```
$ npx amplify init
npx: installed 1 in 1.407s
command not found: amplify
```

It's not available.

**Comment by MaxDesiatov** [comment]
@renebrandel The error described in the OP is no longer reproducible for me when I don't use `npx`, but `amplify init` still always fails with a different inexplicable error, which I reported separately in #5523.

**Comment by ammarkarachi** [comment]
Hi @YuK1Game, this looks like `amplify` is owned by another project https://github.com/chafnan/amplify. We are looking into how to address this.
