### ISSUE TITLE
Help accessing @connection via public lambda function, currently returns null

### ISSUE THREAD

**Issue by n1cklarosa** [aws-amplify/amplify-cli#5510]
I am having issues with a relational field when trying to access my data via a publically accessible lambda function through API gateway. In short, you can see on the Category type below, that I have a connection to Book allowing me to add a book to a category.  

From there, I am trying to build a public endpoint that will return all categories with thier related books in an array. I can access the Category object no problems using my endoiunt, but the 'books' field returns null. The lambda console shows the following error. 

```js
{
      path: [Array],
      data: null,
      errorType: 'Unauthorized',
      errorInfo: null,
      locations: [Array],
      message: 'Not Authorized to access items on type ModelBookCategoryConnection'
}
```

Using the query's section of AppSync allows me to grab this info when using Cognito for auth, but not api_key (I get null again). I am not sure if I am even in the right ball park, but I have been using this for testing.

As I am accessing the graphql API using an API key, I thought I might be able to add   @aws_api_key to the field or types, but it does not  fix the issue. If it is even an issue, am I perhaps trying to do something that is not possible? If so, is there a better way I could be handling this connection?

Thanks in advance

**Which Category is your question related to?**

Public API access

**Amplify CLI Version** 

4.27.3

**What AWS Services are you utilizing?**

Lambda, DynamoDB, AppSync, Amplify, API Gateway

**Provide additional details e.g. code snippets**

Here is my schema definition

```gql
type Book
  @model 
  @auth(
    rules: [
      {
        allow: groups
        groups: ["everyone"]
        operations: [create, delete, read, update]
      }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  author: String
  description: String
  url: String
  zipFile: S3Object
  image: S3Object
  thumbnailJpg: S3Object
  thumbnailWebp: S3Object
  status: String
  christmas: Boolean
  birthday: Boolean
  featured: Boolean
  password: String
  passwordProtected: Boolean
  categories: [BookCategory] 
    @connection(keyName: "byBook", fields: ["id"])
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type BookCategory
  @model(queries: null) 
  @auth(
    rules: [
      {
        allow: groups
        groups: ["everyone"]
        operations: [create, delete, read, update]
      }
      { allow: public, operations: [read] }
    ]
  )
  @key(name: "byBook", fields: ["bookID", "categoryID"])
  @key(name: "byCategory", fields: ["categoryID", "bookID"]) {
  id: ID!
  bookID: ID!
  categoryID: ID!
  book: Book  
    @connection(fields: ["bookID"])
  category: Category  
    @connection(fields: ["categoryID"])
}

type Category
  @model 
  @auth(
    rules: [
      {
        allow: groups
        groups: ["everyone"]
        operations: [create, delete, read, update]
      }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  books: [BookCategory]  
    @connection(keyName: "byCategory", fields: ["id"])
}
```

Here is the lambda endpoint and the graphql query I am using

```js
app.get("/public/categorys", async function (req, res) {
  try {
    const graphqlData = await axios({
      url: `${process.env.API_AMPLIFYBOOKSHELF_GRAPHQLAPIENDPOINTOUTPUT}`,
      method: "post",
      headers: {
        "x-api-key": process.env.API_AMPLIFYBOOKSHELF_GRAPHQLAPIKEYOUTPUT,
      },
      data: {
        query: print(listCategorys),
      },
    });
    console.log("results", graphqlData.data); 
    const body = {
      graphqlData: graphqlData.data.data.listCategorys,
    };
    res.json({ success: "get call succeed!", data: body });
  } catch (err) {
    console.log("error posting to appsync: ", err);
    res.json({ success: "failed", error: err });
  }
});

const listCategorys = gql`
  query listCategorys {
    listCategorys {
      items {
        books {
          items {
            id
            book {
              author
              christmas
              createdAt
              description
              featured
              id
              password
              image {
                bucket
                key
                region
              }
              passwordProtected
              status
              thumbnailJpg {
                bucket
                key
                region
              }
              thumbnailWebp {
                bucket
                key
                region
              }
              title
              url
              zipFile {
                bucket
                key
                region
              }
            }
          }
        }
        title
        id
        createdAt
      }
    }
  }
`;

```

**Comment by ammarkarachi** [comment]
@n1cklarosa What's your default authorization set as?

**Comment by n1cklarosa** [comment]
Thanks for getting back to me. Are you referring to the question asked when I added auth via the amplify command line?

as in, this part
 
`Do you want to use the default authentication and security configuration? Default configuration`

If so, I used default. Outside of that, I have given the function `read` access to the api when creating it via the command line. I am sorry if I am not answering in the right area.

**Comment by ammarkarachi** [comment]
No problem is the default configuration API key or Cognito User pool?

**Comment by n1cklarosa** [comment]
Thanks again, I am pretty sure it is Cgnito User pool. I am just trying to confirm it.

Here is my aws export, looking at this, i think I am  using AMAZON_COGNITO_USER_POOLS 

```
const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "xxx,
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "xxx",
    "aws_user_pools_web_client_id": "6jo5d5pg1o86jb5992crsget08",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "xxxx",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxx",
    "aws_cloud_logic_custom": [
        {
            "name": "publicApi",
            "endpoint": "xxx",
            "region": "ap-southeast-2"
        },
        {
            "name": "bookshelfZipApi",
            "endpoint": "xxx",
            "region": "ap-southeast-2"
        }
    ],
    "aws_user_files_s3_bucket": "amplify-bookshelf141758-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};
```

**Comment by n1cklarosa** [comment]
![image](https://user-images.githubusercontent.com/4338036/95394302-e8eb6100-0947-11eb-8d7d-cec1d4db831c.png)

I did find this in the GUI setup. If I try and change to API_KEY here it tells me I already have api key setup `API key is already specified as an additional authorization provider.`

**Comment by chrisjprior** [comment]
@ammarkarachi do you know if there is there anything further I can do here?

**Comment by n1cklarosa** [comment]
I believe it is safe to close this off as I have moved on with my manual work around in production and am no longer working on this job.. Thanks for your help.  If I do ever jump back in and try this again I will add an update.
