### ISSUE TITLE
HELP - create a new environment

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-cli#5511]
**Which Category is your question related to?**
Creating a new environment

**Amplify CLI Version** 
4.29.4

**What AWS Services are you utilizing?**
react serverless stack

**Provide additional details e.g. code snippets**

I am trying to create a new environment after encountering some problems when having two branches and creating two front ends - for some reason the second one failed to build because aws-exports.js does not get created.

So I figured perhaps you can really have one Amplify project in CodeCommit and then create multiple branches because any time you create a CI/CD front end and do a commit it will surely push updates to both the backend and the frontend.

If someone else is working on a different branch for backend changes then surely there are going to be problems because the backend will keep changing whenever the frontend commits are done ?  

So I figured perhaps it's better if I create a new backend and frontend for the separate branch.  I did this using the Amplify Console (web site) - when creating a new frontend from the new branch you get prompted to create a new backend - so I assumed this is essentially the same as using the "Amplify add".

That all appeared to work fine but then I was unclear on how to change my local development desktop environment to the newly created environment.  I assumed that "Amplify env import" command would do that, however it prompts for a --config <provider-configs> ?? No idea what these are or where you are supposed to find them.

So I gave up on that and tried to follow the suggest Team workflow by doing the following:

1.  Run 'git checkout demo' - to switch to the branch
2.  Run Amplify init and selected the previously created 'demo' environment
3.  The received the following:

```
XXXXXXXXXXXXXX@XXXXXXXXX-MacBook-Air rpm-app % Amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: demo
Using default provider  awscloudformation
⠋ Initializing your environment: demo(node:8499) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'DeploymentBucketName' of undefined
    at S3.getFile (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts:94:82)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/zip-util.js:7:8
    at new Promise (<anonymous>)
    at downloadZip (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/zip-util.js:6:10)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initialize-env.js:22:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ Initializing your environment: demo
```

And now it seems to be stuck running this command - perhaps its busy but it's running a long time now.

Any idea on what is going on here ?

How can I just delete and start again ?  Amplify remove throws and error as well - I'll post that as soon as the above finishes running.

So eventually I hit CTRL-C to terminate the process above since it seemed to be going nowhere.  

Subsequently I tried the following command, which also just exists with an error:

xxxxxxxxxxxxx@XXXXXXXX-MacBook-Air rpm-app % amplify pull --appId d2nsdwxw8qy7b --envName demo
Cannot destructure property 'AmplifyAppId' of 'teamProviderInfo[envName].awscloudformation' as it is undefined.
TypeError: Cannot destructure property 'AmplifyAppId' of 'teamProviderInfo[envName].awscloudformation' as it is undefined.
    at Object.exports.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js:16:17)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:167:29)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:82:9)

So no idea how to recover from this now...

Here is what I had to do:

1.  Create a new amplify/<project>. directory
2.  cd <project> 
3.  run 'amplify pull' and select the environment, in my case 'demo'
4.  Now copy the team-provider-info.json entry for the 'demo' environment from this new project folder to the old one
5.  run amplify pull in the old directory and the backend entries should be updated for the environment

And then it still seems to connect to the wrong backend !

All in all kind of fragile - if you do the wrong thing it ends up pretty broken.

**Comment by ammarkarachi** [comment]
@duncangroenewald Can you verify if the credentials being used have access to the same resources in the account?

**Comment by UnleashedMind** [comment]
It seems like the errors you see are because the `<project-root>/amplify/team-provider-info.json` file is corrupted in your project. 
- "amplify env import" is an internal command we use, it is not meant for what you are trying to do. 
- If you have everything set up on the Amplify Console, and you see both the frontend and backend build/deploy is successful, and you want to work on that project in a local development environment, after you git clone your project, you only need to run `amplify init`, make sure the `<project-root>/amplify/team-provider-info.json` is in place. 
- If you want to share the same backend environment, for multiple frontend, it's possible to do so, that's one of the functionalities of the `amplify pull` command, just run the `amplify pull` in the new frontend project and follow the prompts, and you will get the frontend configuration file , e.g. `src/aws-exports.js` for web apps, created for you. When prompted `Do you plan on modifying this backend?`, it's recommended that you select now so only one project is actively developing the backend, so there is not messy conflict to resolve.

**Comment by UnleashedMind** [comment]
Closing the issue now for lack of response.
Feel free to open a new issue if you still need help with your project.
