### ISSUE TITLE
'amplify pull' does not pull down aws-exports.js file

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-cli#5512]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
the command 'amplify pull' does not pull down aws-exports.js file

**Amplify CLI Version**
4.29.4

**To Reproduce**
Follow the steps outlined below from the docs
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/13807324/95326020-aeed7100-08ed-11eb-904c-abcf6f2325ae.png">

**Expected behavior**
I would have expected the aws-exports.js file to be updated with the selected environments backend parameters.  However this file is not updated or created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version. v12.18.1

**Additional context**
Managing environments docs needs some serious work as nothing works like the docs say it is supposed to.  Seriously frustrating trying to figure anything out.

**Comment by kaustavghosh06** [comment]
@duncangroenewald Could you show the list of commands and the selections you made with the pull command? Was there an error printed out?

**Comment by alstorm96** [comment]
Amplify pull doesnt even pulls python lambda function if changed on cloud on index.py

**Comment by kaustavghosh06** [comment]
@alstorm96 'amplify pull' does not pull in changes made in the Lambda AWS console directly. 
If you're working on a team and your team-member makes a change in the python index.py file and pushes using the Amplify CLI -  you can then pull it down using amplify pull.

**Comment by alstorm96** [comment]
What if someone directly changed the function in the console from my team. It doesnt pulls that one

**Comment by kaustavghosh06** [comment]
If your directly change the function in the Lambda AWS Console - amplify pull wouldn't pull the changes. Following  AWS best practices, I wouldn't recommend making changes directly in the AWS Console but rather maintain everything via code.
