### ISSUE TITLE
amplify configure does not list eu-north-1 region as an option

### ISSUE THREAD

**Issue by micsafi** [aws-amplify/amplify-cli#5513]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
`amplify configure ` command does not list eu-north-1 as an region to select even though Amplify is available in that region.

**Amplify CLI Version**
4.29.4

**To Reproduce**
Run `amplify configure` and see the list of available regions.

**Expected behavior**
I would expect the list to contain all regions where Amplify is available.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node v14.13.0

**Comment by ecerulm** [comment]
As far as I understand the `aws configure` is just guides you into: 
* Login to AWS Management Console
* Create a IAM user, for programmatic access with AdministratorAccess,
* Create a [local named profile] for aws cli

So the net result of `amplify configure` is just a new aws-cli's named profile, you can create the named profile yourself and skip the `amplify configure` entirely. 

I believe the workaround is to do this steps manually
* Create an IAM user called amplify-xxxxx  with attached policy `AdministratorAccess`
* Note the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` 
* Use `aws configure --profile amplify-xxxxx` to create a named profile (input the region, access key id, and secret access key)

Then rest of the tooling like `amplify init` will then rely on the named profile that you created. `amplify init` will ask you which named profile to use and you should just select `amplify-xxxx`.

**Comment by agordeev** [comment]
>Use aws configure --profile amplify-xxxxx to create a named profile (input the region, access key id, and secret access key)

Still, the region isn't listed when trying to input it (`me-south-1`)

**Comment by ecerulm** [comment]
@agordeev , What do you mean? `aws configure --profile amplify-xxxxx` will ask you to input the region (no list, you need to type the region name fully). `aws configure` replaces `amplify configure` you don't need to call `amplify configure` after.

**Comment by agordeev** [comment]
Sorry, my bad. Was using `amplify configure`
