### ISSUE TITLE
Querying a many-to-many relationship

### ISSUE THREAD

**Issue by DanNeish** [aws-amplify/amplify-cli#552]
** Which Category is your question related to? **
AWS Amplify GraphQL API

** What AWS Services are you utilizing? **
Amplify API GraphQL with dynamodb

I am working through the example in the Amplify docs [here](https://aws-amplify.github.io/docs/cli/graphql?sdk=js) on implementing a many-to-many relationship.
The example schema is:
```
type Post @model {
  id: ID!
  title: String!
  editors: [PostEditor] @connection(name: "PostEditors")
}

# Create a join model and disable queries as you don't need them
# and can query through Post.editors and User.posts
type PostEditor @model(queries: null) {
  id: ID!
  post: Post! @connection(name: "PostEditors")
  editor: User! @connection(name: "UserEditors")
}

type User @model {
  id: ID!
  username: String!
  posts: [PostEditor] @connection(name: "UserEditors")
}
```

How would you achieve a query such as:
List the title of all posts of which the user with id "XXXXXXX" is an editor.

Querying the User model for a particular user will provide a list of post IDs of posts that user is an editor of, however you can't then return the post title for each of those posts in the same query. 

Amplify Generated GetUser Query:
```
query GetUser($id: ID!) {
  getUser(id: $id) {
    id
    username
    posts {
      items {
        id
      }
      nextToken
    }
  }
}
```
I might be missing something simple here... (I'm new to Amplify and GraphQL in general)

UPDATE:
I was missing something simple, to achieve this the following query works. Left here for reference in case someone else is having the same problem.

```
query GetUser {
  getUser(id: "XXXXXXX") {
    id
    username
    posts {
      items {
        id
        post {
          title
        }
      }
      nextToken
    }
  }
}
```

**Comment by phaniteja1** [comment]
Is this filtering possible? Thanks!
