### ISSUE TITLE
`amplify init` always fails with `TypeError: Cannot read property 'Stacks' of null`

### ISSUE THREAD

**Issue by MaxDesiatov** [aws-amplify/amplify-cli#5523]
**Describe the bug**
When running `amplify init` it always throws `TypeError: Cannot read property 'Stacks' of null` with no clear way to proceed or fix it.

**Amplify CLI Version**
4.29.4

**To Reproduce**
1. Create an empty directory. 
2. Run `amplify init`
3. Select `ios` as the type of the app.

**Expected behavior**
`amplify init` succeeds.

**Screenshots**
<img width="1274" alt="Screenshot 2020-10-08 at 10 06 16" src="https://user-images.githubusercontent.com/112310/95438500-484c6f80-094e-11eb-9981-2ad5154d4041.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)
 - Node Version: v12.19.0

**Additional context**
This error was preceeded by https://github.com/aws-amplify/amplify-cli/issues/5509, but that one is no longer an issue for me as I don't attempt to start `amplify` with `npx` here.

**Comment by ammarkarachi** [comment]
@MaxDesiatov what's the usage policy for your user?

**Comment by UnleashedMind** [comment]
@MaxDesiatov 
[This document ](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n1-set-up-the-role-biz-corp) has the instruction on how to set up a role and the user to assume the role. 
As pointed out in [Step 2](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n2-set-up-the-user-to-assume-the-role-dev-corp) in the article the user must have the appropriate permission to assume the role.
```json
{
 "Version": "2012-10-17",
 "Statement": [
     {
         "Effect": "Allow",
         "Action": "sts:AssumeRole",
         "Resource": "<biz_corp_rol_arn>"
     }
 ]
}
```

**Comment by MaxDesiatov** [comment]
I'm not sure, what do you mean by "usage policy"? How do I check it?

**Comment by UnleashedMind** [comment]
Open the IAM console, go

**Comment by MaxDesiatov** [comment]
> [This document ](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n1-set-up-the-role-biz-corp) has the instruction on how to set up a role and the user to assume the role.
> As pointed out in [Step 2](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n2-set-up-the-user-to-assume-the-role-dev-corp) in the article the user must have the appropriate permission to assume the role:

The linked document says "You can optionally configure the Amplify CLI to assume an IAM role". So if this is optional, why is it needed then? 

> 
> From the error message, it does not seem to have the right permission.

Could you clarify which exact error message are you referring to? None of the error messages specify which permissions are required and on what user. The final error message `TypeError: Cannot read property 'Stacks' of null` doesn't refer to any permissions or users at all.

**Comment by MaxDesiatov** [comment]
I was following [the official Amplify documentation for iOS](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios#n1-create-a-new-project) and its "Prerequisites" list, it doesn't refer to users or permissions at all and specifies that running `amplify init` should work as the first step to set up the project. In my opinion, both documentation and error messages need to be updated to provide clear steps and requirements for new projects.

**Comment by UnleashedMind** [comment]
> > [This document ](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n1-set-up-the-role-biz-corp) has the instruction on how to set up a role and the user to assume the role.
> > As pointed out in [Step 2](https://docs.amplify.aws/cli/usage/iam-roles-mfa#n2-set-up-the-user-to-assume-the-role-dev-corp) in the article the user must have the appropriate permission to assume the role:
> 
> The linked document says "You can optionally configure the Amplify CLI to assume an IAM role". So if this is optional, why is it needed then?

You don't have to configure the Amplify CLI to assume a role, it can directly use a IAM user's credential. But you could configure it to assume a role. 

From the following error message, the profile that you've selected is from a role with `source_profile` set to a user that is NOT set up to assume a role. Open the `<home-dir>/.aws/config` file you can see the profiles. 

> 
> > From the error message, it does not seem to have the right permission.
> 
> Could you clarify which exact error message are you referring to? None of the error messages specify which permissions are required and on what user. The final error message `TypeError: Cannot read property 'Stacks' of null` doesn't refer to any permissions or users at all.


![95488834-e2aab400-094a-11eb-802e-df97699d8da2](https://user-images.githubusercontent.com/6025263/95492680-51d6d700-0950-11eb-9d49-7f4d6b7790d3.png)

**Comment by MaxDesiatov** [comment]
> You don't have to configure the Amplify CLI to assume a role, it can directly use a IAM user's credential. But you could configure it to assume a role.
> 
> From the following error message, the profile that you've selected is from a role with `source_profile` set to a user that is NOT set up to assume a role. Open the `<home-dir>/.aws/config` file you can see the profiles.

Is this mentioned in the Amplify "Getting started" documentation anywhere? I'm following the steps exactly as they are specified in the documentation, so my assumption is that either documentation is up to date and all the steps will succeed as described in it, or errors will be shown that will direct me and clearly state what's wrong and how to fix it.

> If you follow the instruction from the document, you will be able to set it up.

Shouldn't this document be directly linked from the "Getting started" and "Prerequisites" sections if following that document is required to get `amplify init` to work?

**Comment by UnleashedMind** [comment]
Assuming role is considered an advanced workflow.
You can follow our [Get started](https://docs.amplify.aws/cli/start/install) , the steps there will lead you to set up the configurations for the Amplify CLI to work.

**Comment by MaxDesiatov** [comment]
Thanks for the link. That "Get startred" page is exactly what I followed, which led to these issues.

What are your thoughts on the `TypeError: Cannot read property 'Stacks' of null` error message? How could it be improved to become more specific and helpful to other users who stumble upon these issues?

**Comment by UnleashedMind** [comment]
If you follow the instruction in the getting started doc, you will setup a new user using `amplify configure`, your profile won't have the role assumption signature, then you won't hit the error that the user does not have permission to assume a role. 
But I do agree with you that the final error message can be improved to provide more information. 
I will mark this as an enhancement.

**Comment by drochetti** [comment]
> I was following [the official Amplify documentation for iOS](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios#n1-create-a-new-project) and its "Prerequisites" list, it doesn't refer to users or permissions at all and specifies that running `amplify init` should work as the first step to set up the project. In my opinion, both documentation and error messages need to be updated to provide clear steps and requirements for new projects.

hey @MaxDesiatov, I'm part of the iOS team and will be happy to assist you. If there's an issue in the Getting Started docs I want to work with you and fix it asap.

You've mentioned that `amplify init` is in the "Prerequisites" but looking at the docs you linked, the prerequisites say that you need to run `amplify configure` (step 2 of the first page) whereas `amplify init` is not part of the prerequisites and happens later in the process (step 3 of the second page), when you're ready to provision the backend and it assumes the CLI has been already configured.

Are you able to confirm that `amplify configure` was executed before `amplify init` when you get the error?

**Comment by MaxDesiatov** [comment]
Yes, I can confirm it. I've followed the docs multiple times from the start in different environments on different machines with the same result.

**Comment by hector-gonzalez-epicor** [comment]
I am having the exact same issue as the original reporter. Has anyone found a workaround?

**Comment by josefaidt** [comment]
Hey @MaxDesiatov :wave: I wanted to follow-up on this issue and see if you were still experiencing this issue with `amplify init`?

**Comment by MaxDesiatov** [comment]
I haven't been using Amplify for long time due to a bunch of blocking bugs, including the one I reported here, so I can't really answer your question.

**Comment by josefaidt** [comment]
Hey @MaxDesiatov that's understandable. Given the age of this issue and lack of recent reports I will close this issue for now, however in the event you're using Amplify and run into this issue again please feel free to reply back to this thread and we can re-open to investigate further on the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v8.0.1)

**Comment by dpalme3160** [comment]
I'm having the same issue
