### ISSUE TITLE
How to change the directory for generated code?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5524]
If I run :
```
amplify push
...
...
Generated GraphQL operations successfully and saved at src/graphql
```

The "Generated GraphQL operations" are stored to `src/graphql`. Can I change the directory for this?

**Which Category is your question related to?**
GraphQL API

**Amplify CLI Version** 

4.29.2

**Comment by ammarkarachi** [comment]
@yaquawa you can change the `docsFilePath` in the `.graphqlconfig.yml` file and run `amplify codegen` to generate the new code files.
