### ISSUE TITLE
Undocumented breaking change in GraphQL @connection behaviour?

### ISSUE THREAD

**Issue by Zanndorin** [aws-amplify/amplify-cli#5526]
Hi, 

I had followed the documentation when we started building the project

https://docs.amplify.aws/cli/graphql-transformer/directives#connection

```
type Project @model {
  id: ID!
  name: String
  team: Team @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

in our case

```
type Customer @model
{
    id: String!
    name: String!
    supervisor: CustomerSupervisorGroup @connection
}


type CustomerSupervisorGroup @model
{
    id: String
    members: [String]
}
```

Which worked fine until some versions ago (I don't know when it stopped working, The feature isn't used that much 😊 )

Had to change to 

```
type Customer @model
{
    id: String!
    name: String!
    supervisor: CustomerSupervisorGroup @connection(fields:["id"])
}
```

Was this an intended change?

PS: Since I am building for production it builds on code change. So currently Amplify version is:

 2020-10-08T11:27:17.149Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.29.5...)

**Comment by ammarkarachi** [comment]
@Zanndorin as far as I know both cases should work? was your "id" setup as the primary index?

**Comment by Zanndorin** [comment]
@ammarkarachi It worked just fine until "recently".

I then mocked it locally and got the same results, maybe it is connected to me using String as id type? But I can reproduce this behaviour with

```
type Project @model {
  id: String!
  name: String
  team: Team @connection
}

type Team @model {
  id: String!
  name: String!
}
```

locally. (Will work when setting `@connection(fields:["id"])`


and yes it is the primary index on both.
