### ISSUE TITLE
S3 bucket storage permissions on a lambda function - incorrect policy statement for s3:ListBucket action

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#5528]
**Describe the bug**
When updating or creating a lambda function and choosing to access other resources, and then choosing storage, then your bucket (created also with amplify cli) it updates the cloudformation template for this function, adding this statement - 
```
{
  "Effect": "Allow",
  "Action": [
    "s3:PutObject",
    "s3:GetObject",
    "s3:ListBucket"
  ],
  "Resource": [
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:s3:::",
          {
            "Ref": "yourBucketName"
          },
          "/*"
        ]
      ]
    }
  ]
}
```
The problem here is that the ListBucket action needs a different resource - it needs to access the bucket and not a specific object, so in this case the resource for ListBucket should be 
```
      "Fn::Join": [
        "",
        [
          "arn:aws:s3:::",
          {
            "Ref": "yourBucketName"
          }
        ]
      ]
``` 
(you could format that to be cleaner I guess but it doesn't matter).
so Instead of the template that is created (the first code block above), this should be the created template - 
```
{
  "Effect": "Allow",
  "Action": [
    "s3:PutObject",
    "s3:GetObject"
  ],
  "Resource": [
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:s3:::",
          {
            "Ref": "yourBucketName"
          },
          "/*"
        ]
      ]
    }
  ]
},
{
  "Effect": "Allow",
  "Action": "s3:ListBucket",
  "Resource": [
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:s3:::",
          {
            "Ref": "yourBucketName"
          }
        ]
      ]
    }
  ]
}
```

**Amplify CLI Version**
4.29.4

**To Reproduce**
1. `amplify function add`
2. choose to access other resources
3. choose storage
4. select your s3 bucket from the list
5. choose read permission (you can add others)
6. see that the template created is incorrect and your function will not be able to list files in the bucket

**Expected behavior**
The template generated should be like the code block above (the last one)

**Comment by ammarkarachi** [comment]
@idanlo Yes, to list object at the root level that policy would not suffice thanks for bringing this up I will mark it as bug.

**Comment by idanlo** [comment]
@ammarkarachi not only on the root level, listing objects didn't work for me at all with that function

**Comment by ammarkarachi** [comment]
Let me try it out and get back to you

**Comment by jingxizhang** [comment]
Yes, I am also having the problem. It is not just the root level, the list object function returns deny access error whatever the prefix is.
The problem is that the resource: yourBucketName/* gives the permission for action INSIDE the bucket but not the permission for the action ON the bucket.
Adding another policy with resource: yourBucketName solves the problem.

**Comment by gabrielgrover** [comment]
> Yes, I am also having the problem. It is not just the root level, the list object function returns deny access error whatever the prefix is.
> The problem is that the resource: yourBucketName/* gives the permission for action INSIDE the bucket but not the permission for the action ON the bucket.
> Adding another policy with resource: yourBucketName solves the problem.

@jingxizhang could you paste your edits to cloudformation template?  I am having the same issue as you were.

**Comment by idanlo** [comment]
@ammarkarachi This issue still exists, and we still need to manually change the cloudformation template of functions in order to make s3:ListBucket operations work

**Comment by yonatanganot** [comment]
Hey @ammarkarachi,
Did you able to check this issue?
