### ISSUE TITLE
By switching between the amplify environments a wrong user pool is used

### ISSUE THREAD

**Issue by ivpdev** [aws-amplify/amplify-cli#5530]
**Describe the bug**
I have a project with an auth component. When I switch from one amplify environment to another, sometimes the app uses a wrong user pool (the one from the previous environment). 
The error occurs from time to time by multiple team members. Another switch between environments usually fixes the problem.

**Amplify CLI Version**
4.29.3

**To Reproduce**
Given:
-  there are amplify environments env1 and env2 both having "auth" component.
- env1 is active
When: 
- 'amplify env checkout env2' 
- './gradlew clean build'
- sign up a new user from the app
Then:
- the user is created in the user pool belonging to the environment env1

**Expected behavior**
the user is created in the user pool belonging to the environment checked out currently (env2)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.15.0

**Comment by UnleashedMind** [comment]
It seems like the frontend (The Android App?) is not properly picking up the switched backend configuration.
How are you testing your app? did you kill the previous testing app and then launch a new one after you checked out to the other backend env?

**Comment by a-melnyk** [comment]
hi all,

I just reproduced a similar issue with amplify 4.29.6. The problem occurs when a new environment is created, switching between environments works well for me and actually fixes broken config files.

@UnleashedMind, in my case amplifyconfiguration.json and awsconfiguration.json configuration files are not properly updated after `amplify push` execution

```
# currently on environment "oldenv" and about to create a new one
→ grep -rE 'PoolId|ApiUrl' app/src/main/res/raw
app/src/main/res/raw/amplifyconfiguration.json:                        "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/amplifyconfiguration.json:                        "ApiUrl: "oldUrl",
app/src/main/res/raw/awsconfiguration.json:            "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/awsconfiguration.json:            "ApiUrl: "oldUrl",

→ amplify env add # create a new environment „newenv“

# the values are not updated as no backend infrastructure is created yet
→ grep -rE 'PoolId|ApiUrl' app/src/main/res/raw
app/src/main/res/raw/amplifyconfiguration.json:                        "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/amplifyconfiguration.json:                        "ApiUrl: "oldUrl",
app/src/main/res/raw/awsconfiguration.json:            "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/awsconfiguration.json:            "ApiUrl: "oldUrl",

→ amplify push

# **PROBLEM**: the infrastructure was created but the configs files still contain old Cognito PoolId, AppSync ApiUrl is correct
→ grep -rE 'PoolId|ApiUrl' app/src/main/res/raw
app/src/main/res/raw/amplifyconfiguration.json:                        "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/amplifyconfiguration.json:                        "ApiUrl: "newUrl",
app/src/main/res/raw/awsconfiguration.json:            "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/awsconfiguration.json:            "ApiUrl: "newUrl",

→ amplify env checkout oldenv 

# correct values, as I'm back on the old environment
→ grep -rE 'PoolId|ApiUrl' app/src/main/res/raw
app/src/main/res/raw/amplifyconfiguration.json:                        "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/amplifyconfiguration.json:                        "ApiUrl: "oldUrl",
app/src/main/res/raw/awsconfiguration.json:            "PoolId": "eu-central-1_old_ID",
app/src/main/res/raw/awsconfiguration.json:            "ApiUrl: "oldUrl",

→ amplify env checkout newenv

# checkout back and forward fixed the issue, all values are correct
→ grep -rE 'PoolId|ApiUrl' app/src/main/res/raw
app/src/main/res/raw/amplifyconfiguration.json:                        "PoolId": "eu-central-1_new_ID",
app/src/main/res/raw/amplifyconfiguration.json:                        "ApiUrl: "newUrl",
app/src/main/res/raw/awsconfiguration.json:            "PoolId": "eu-central-1_new_ID",
app/src/main/res/raw/awsconfiguration.json:            "ApiUrl: "newUrl",
```

Workaround: checkout a different environment and then switch back to the newly created one

**Comment by ivpdev** [comment]
"How are you testing your app? did you kill the previous testing app and then launch a new one after you checked out to the other backend env?" 
- ./gradlew clean
- uninstall the from the emulator
- build and run with Android Studio
