### ISSUE TITLE
Cancelling amplify mock throws an error

### ISSUE THREAD

**Issue by owboateng** [aws-amplify/amplify-cli#5531]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I have upgraded my Amplify CLI from 4.28.2 to the latest 4.29.5 because the older version was not updating the generated queries and mutations when I changed the schema. The new version fixes the issue but when I try to close the CLI (control + C), I get this error:
```
error: uncaughtException: this.print.warn is not a function date=Thu Oct 08 2020 18:08:43 GMT+0200 (Central European Summer Time), pid=13493, uid=164619444, gid=1493692218, cwd=/Users/owusu/react-node-workspace/teachsomebody-nextjs, execPath=/usr/local/Cellar/node@12/12.18.2/bin/node, version=v12.18.2, argv=[/usr/local/Cellar/node@12/12.18.2/bin/node, /usr/local/bin/amplify, mock], rss=331444224, heapTotal=280821760, heapUsed=199832888, external=3517639, arrayBuffers=1491411, loadavg=[3.63525390625, 2.74072265625, 2.74365234375], uptime=708338, trace=[column=14, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts, function=Context.sigIntHandler, line=129, method=sigIntHandler, native=false, column=22, file=events.js, function=process.emit, line=327, method=emit, native=false, column=12, file=domain.js, function=process.EventEmitter.emit, line=482, method=emit, native=false], stack=[TypeError: this.print.warn is not a function,     at Context.sigIntHandler (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:129:14),     at process.emit (events.js:327:22),     at process.EventEmitter.emit (domain.js:482:12)]
```

Also the generated resolvers are not cleaned when I close the mock CLI.
**Amplify CLI Version**
4.29.5

**To Reproduce**
Just install the latest version on a MacOs (Mojave 10.14.6) and run amplify mock and try ctrl + C

**Expected behavior**
CLI gracefully terminates and cleans up the mock resolvers.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac (Mojave 10.14.6)
 - Node Version. v12.18.2

**Additional context**

**Comment by renegoretzka** [comment]
I have exactly the same issue on Windows 10.

**Comment by owboateng** [comment]
@ammarkarachi Please in which version of the CLI will this fix be?
