### ISSUE TITLE
Amplify push never completes 

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-cli#5532]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Following the basic instructions online for setting up an Amplify Android project and adding the Rest API. 

https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#next-steps

https://docs.amplify.aws/lib/restapi/getting-started/q/platform/android#configure-api

**Amplify CLI Version**
4.29.4 and 4.29.5

**To Reproduce**
Follow the instructions in the links provided above to setup your Amplify Android project with Rest API. 

ie. 

amplify init 
amplify add api 
amplify push 

**Expected behavior**
The CLI does not get stuck and generates a AmplifyConfiguration.json file.  

**Screenshots**

It gets stuck here forever: 

![image](https://user-images.githubusercontent.com/11478656/95497834-d1b46f80-0957-11eb-94fc-a3d683950cce.png)

On CloudFormation it says "CREATE_COMPLETE" for the rest api:

![image](https://user-images.githubusercontent.com/11478656/95498415-a2eac900-0958-11eb-937f-b887d86d3ace.png)

**Desktop (please complete the following information):**
MAC

**Comment by UnleashedMind** [comment]
I can not reproduce the issue. 
Maybe it's tied to a specific node version or aws region? 
please provide those information.
