### ISSUE TITLE
Support for WSL - Selected default editor not found

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#554]
**Describe the bug**
On Ubuntu for Windows 10 (WSL), after doing `amplify init`, I selected Sublime Text as the default editor, which is installed on my Windows filesystem. When trying to update the GraphQL schema through the console -- which I believe just launches your selected editor with the relevant file created and opened? -- I get the error "Selected default editor not found in your machine." 

I think this must have something to do with Amplify looking for an Ubuntu build of Sublime as opposed to the Windows version. 

**To Reproduce**
1. Install Ubuntu for Windows, Node, npm, Amplify, and Amplify CLI on Ubuntu distro. Install Sublime for Windows.
2. `amplify init` your app, select Sublime Text as your editor.
3. `amplify add api` and select Yes when asked to edit schema

**Expected behavior**
Editor launched with file opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/22964702/49597381-884d0080-f939-11e8-817e-d812f50b04ef.png)
![image](https://user-images.githubusercontent.com/22964702/49597522-d82bc780-f939-11e8-99ce-e1ed9c971dde.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu running on Windows Subsystems for Linux

**Additional Context**
The Amplify app is in the Windows filesystem, which can be navigated to via the /mnt/ Linux directory. Most Amplify functionality works with this setup.

**Comment by jkeys-ecg-nmsu** [comment]
Is it really an Amplify bug if the issue is caused by using an Ubuntu shell to access an Amplify app in a filesystem? Dunno, @yuth please reopen if you feel it warrants.

**Comment by imgntn** [comment]
Same issue -  `Press enter to continue Selected  editor vscode was not found in your machine.`

i think a lot of people run windows 10 with WSL 

is there some structural issue as to why amplify would be unable to open my default text editor? in the same terminal window where i'm running amplify, i can type "code" and open visual studio code

**Comment by jkeys-ecg-nmsu** [comment]
Agreed that WSL should be a supported platform.

**Comment by estyh** [comment]
I encounter the same problem using git bash inside vscode

**Comment by adampwright** [comment]
> I encounter the same problem using git bash inside vscode

Same issue. Not in WSL, standard Windows with Git Bash inside VS Code

**Comment by attilah** [comment]
Closing this issue as this is working as expected in the latest CLI, open successfully opens the browser in Windows, editors are opened as long as they WSL configured to share the path variables and access between WSL and Windows. the CLI uses `which` to locate the selected editor, so if `which code` returns an editor from the ubuntu shell then CLI will open it, if not then WSL is not configured properly.
