### ISSUE TITLE
*Edit* Graphql Update Appending Data to Arrays instead of overwriting

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-cli#5541]
I noticed a bug today, while I was working on an editor. When running the update mutation, my properties that use arrays are duplicated leaving me with the original array and the new array stored together. How the editor works is I get the data for x object, set the state and then with the same state if the user modified it and confirms it then it updates. I was under the impression it would override the values

**Comment by ammarkarachi** [comment]
@ondojo do you mean the items are concatenated even though they are the same? Also could you share your tranform.conf file?

**Comment by CarbnJacob** [comment]
I have this same problem too! With automerge the data objects concatenate every time rather than replace, which leads to huge issues.

**Comment by crolly** [comment]
> I have this same problem too! With automerge the data objects concatenate every time rather than replace, which leads to huge issues.

after some more digging into the docs of app sync, i have found this: https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html

the leads me to believe, that everything works as it is supposed to.

> Conflict on a list: GraphQL type and database type are lists. Concatenate the incoming list with the existing list in the server. The list values in the incoming mutation will be appended to the end of the list in the server. Duplicate values will be retained.

What we did, was to change the conflict resolution to `Optimistic Concurrency` and implementing our own conflict resolution.
@CarbnJacob you could e.g. use lodash's `isEqual` and then replace items in the list or the entire list. I guess it all depends on your data model.

**Comment by CarbnJacob** [comment]
> @CarbnJacob you could e.g. use lodash's `isEqual` and then replace items in the list or the entire list. I guess it all depends on your data model.

Thanks for getting back to me so fast @crolly!

I'm new to conflict resolution - would this conflict resolution need to be done in the callback from failed GraphQL mutations made by the client?

I'm doing most of the saves through Amplify DataStore so it's largely a black box to me :(

**Comment by crolly** [comment]
@CarbnJacob yes. take a look here: https://docs.amplify.aws/lib/datastore/conflict/q/platform/js#custom-configuration

you can specify your own conflictHandler with `DataStore.configure`.
