### ISSUE TITLE
Appsync custom lambda pipeline resolver

### ISSUE THREAD

**Issue by janfabian** [aws-amplify/amplify-cli#5547]
**Which Category is your question related to?**

**Amplify CLI Version** 
4.29.1

**What AWS Services are you utilizing?**
AppSync, Lambda

**Provide additional details e.g. code snippets**

I have my resolvers generated for me via the graphql directive `@model`

```
type MyType @model
```

I'd like to prepend custom lambda resolver before the VTL mapper to achieve following scenario

```
1. a graphql mutation is invoked mutation CreateMyType(
    $input: CreateMyTypeInput!
    $condition: ModelMyTypeConditionInput
  )

2. My custom lambda function which would return additional attributes

3. Amplify VTL mapper, where I could reference the previous lambda result as $ctx.prev.result

```

Background - to create a new model I need some attributes to be either fetched or calculated in my lambda. I also want to use the generated VTL resolver. 

Is it achievable in CLI to combine these functionalities?

**Comment by UnleashedMind** [comment]
@janfabian 
You can provide [custom resolvers](https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers) to override the CLI generated ones. 
But I don't think use you can use lambda function to dynamically add fields into the definition of a type annotated by @model.

**Comment by janfabian** [comment]
@UnleashedMind thanks for the response
