### ISSUE TITLE
Create a S3 trigger using AWS Amplify and then grant the trigger function access to APIs.

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-cli#5551]
**Describe the bug**
Create a S3 trigger using AWS Amplify and then grant the trigger function access to APIs.

API access policy seems to replace the S3 access policy and required manual replacement of the S3 access policy for the S3Trigger role

**Amplify CLI Version**
latest

**To Reproduce**
N/A

**Expected behavior**
I would expect different policies get created for API access and for S3 access and the S3Trigger role should have both assigned.

So in the CloudFormation templates both seems to use the same PolicyName - isn't that the reason one seems to be getting overridden?

At one point there seemed to be two different policies assigned to the S3Trigger role but I can't recall what the were called.

**Code Snippets **
storage/s3-cloudformation-template-json
```
"S3TriggerBucketPolicy": {
            "DependsOn": [
                "S3Bucket"
            ],
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "amplify-lambda-execution-policy",
                "Roles": [
                    {
                        "Ref": "functionS3Triggera54de6aaLambdaExecutionRole"
                    }
                ],
```

S3TriggerXXX/S3TriggerXXX-cloudformation-template.json
```
"AmplifyResourcesPolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "appsync:Create*",
                "appsync:StartSchemaCreation",
                "appsync:GraphQL",
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*",
                "appsync:Delete*"
              ],
```

**Comment by yuth** [comment]
With S3 Trigger, the S3 stack adds an inline policy to Lambda Execution role in S3 stack and when permission is granted to API category, we augment the same policy in the trigger function stack. Effectively the role gets permission to on both resources albeit in different stacks.

So to summarize trigger is added in S3, so policy inline policy gets added in Storage stack and when you add permission to function to access the API, that is maintained in function stack
