### ISSUE TITLE
How to speed up the API development cycle?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#5552]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

I'm loving Amplify initially but when trying to actually "get stuff done" for real I'm finding myself slowed down by the current development cycle. I wondered if I'm missing something to help streamline that, something that is skipped over in the "how to get started" docs that could make changes quicker?

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.29.4

**What AWS Services are you utilizing?**

API

**Provide additional details e.g. code snippets**

Making any change to my schema requires me to do a "amplify push" which requires waiting and saying "yes" to three questions (which I always answer yes too...so that seems a little defunct). This often takes 5-10 minutes to complete and I have to do this everything I need to make a change. As a result the development cycle is complete blown to bits with a lot of waiting going on.

Is there any way to speed this up? Is there a way it can only scan for changes or assume that my local setup is still the master so skip the checking it seems to do on live? Am I missing something?

If there is no way to speed it up currently then can I make the request that its looked into as currently its a killer for productivity.

**Comment by undefobj** [comment]
Have you looked at local mocking: https://docs.amplify.aws/cli/usage/mock#local-mocking

**Comment by PeteDuncanson** [comment]
I have, trouble is I was trying to do a data import at the time (via a function see #5553) so needed to have the schema in the cloud up to date as I found issues with it. A 7-10 minute push time is typical which means 6 changes an hour max :(

**Comment by kaustavghosh06** [comment]
@PeteDuncanson You can use "amplify push --yes" to avoid answering yes to all the questions in the CLI each time. As @undefobj mentioned using "amplify mock" is a great way to speed up the feedback loop for your API development. Could you explain in more detail why you weren't able to use mock?

**Comment by PeteDuncanson** [comment]
Running the mock and realising that it would re-compile the schema every time I made a change seemed helped a lot. It stopped me making silly errors/typos and catching them early. I was previously only seeing errors when I pushed and then the error messages where very vague which made debugging frustrating.

Some ideas for improvements on that could be:
* Pushing will fail if the schema is invalid but it doesn't fail fast, could the schema validation be done sooner?
* If the schema validation fails then maybe include a hint about "it can be easier to debug schema errors by running amplify mock api and visiting http://localhost:20002" to make that more discoverable?

The --yes or -y suggestion does wonders, thank you for that pointer 😃 

My main grumble though was at the slowness of a push in general. If I add one field to my API it can still take 5+ minutes for it to churn through to get it live and I wondered if that could be optimised any to make it faster? I'll explain my use case some more at the time of opening this so maybe you can understand my frustration. I fear that this will all just come down to me having to do a bit more thinking/planning before I go coding but here is what I was doing.

When I opened this issue I was trying to run a data import via a Lambda triggered by a S3 upload. While doing it though I was finding additional fields that I needed or could inject in, ones that needed more cleaning before import or was having ideas on the fly while working with the data so was sort of doing some quick on the fly refactoring. But as the code I wanted to run was in the cloud as a Lambda Function I needed it to talk to the GraphQL that was also in the cloud. If I needed to add a new field to my schema I needed to do a push and wait. So my cycle of editing the schema, pushing, re-running my import script was taking a long time which leads to all the usual problems of getting distracted or just burning time. I could have mocked the api and the function in theory but the debugging experience for mocked functions simply doesn't work as I've raised here #5553 so the only way to get feedback (even catching a simply typo) when developing currently is to do it in the cloud.

I know nothing of what that push is doing under the hood but I do see all the log info that scrolls up my page, some many things seem to be touched to add a String field to a existing entity. It seems a bit wasteful and brute force. I guess my query is, is there a better way that push could do its magic so that it goes quicker? Like I said above if it could fail fast that would be great, if it could just push up the change that would be great too and faster. I get that there might be issues if whats in the cloud has been touched by someone else and that is maybe why it has to do all the work is seems to do but what if I could have a setting that says "I'm the only want developing this, just deploy the diff" or something that could cut down on that push time if I've opted in and know what I'm doing?

Some of my feedback here might be better as separate issues but I wanted to give you some context in one place.

Hope that helps and if I can add anything more let me know.

**Comment by kaustavghosh06** [comment]
@PeteDuncanson Yeah, I get your pain. We introduced "mock" for the exact same reason and pain points that you've mentioned above. I'll ask the team to look at #5553 which looks like a bug in mocking functions - so that you don't have to push each of your changes to the cloud to test changes.

**Comment by PeteDuncanson** [comment]
Can I sanity check my App to see if I'm stretching Amplify too much or something, I'm still having push times take 5+ minutes sometimes 10+ which is just a dev flow killer.

Even Nader Dabit said it shouldn't be taking this long: https://twitter.com/dabit3/status/1336672727806205953

Which makes me thing am I doing something wrong or is there something else that could be done?

Its all Amplify out of the box stuff, I've got 15 models in my GraphQL schema, they have relations between then, searchable is enabled on three of them, auth via Google, storage and some Lambda's for importing data. Thats it really. Why would this take so long to push up?

Could it be a location thing? I'm signed up to eu-west-1 so I'm assuming all my stuff gets pushed up to there or does it go up to USA somewhere first or something? All the demo apps with 3 models for a blog work a treat and nice and speedy but is this a false promise, is this now just the way it is when you start putting something bigger in there?

related: https://github.com/aws-amplify/amplify-cli/issues/5964

**Comment by kaustavghosh06** [comment]
@PeteDuncanson The push times is dependent on the CloudFormation deploy times and it might take between 5-10 mins depending on the number of models and the number of resources being pushed.

**Comment by PeteDuncanson** [comment]
@kaustavghosh06 well I guess that just is the way it is then. Thanks for getting back so I can manage my expectations.

Also thanks for getting #5553 looked at (and fixed).

Any chance you can do the same with #5981 which is also hindering mocking? :)

Also as mentioned in #5964 is there anyway you can limit what gets pushed up to speed up a push? It seems that it almost seem to redeploy everything all over again every push rather than what has changed?

With that I'll close this one as now I know that it is what it is, anything you can do to speed it up would be great though as like I said its a developer flow killer as it stands!

**Comment by PeteDuncanson** [comment]
@kaustavghosh06 sorry to raise this here but I've noticed that since the last release of the CLI (v4.42) that pushing seems to be push quicker. Have you folks done any magic?
