### ISSUE TITLE
Best way to develop code to run for Lambda's, current setup is painfully slow and manual

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#5553]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

I'm after knowing if there is a better way to develop my code for running in a Function/Lambda. Currently (after initially creating the Function via Amplify) I'm manually editing the code in the browser editor for the Lambda itself. I then trigger the Lambda by uploading a file to S3 (its an import so this is how it will be run anyway). That loop though is slow going and totally kills any flow.

I've tried mocking the Function locally but if there are any errors or typos in my code it just hangs and won't give any details so the only way I've found to get anything sensible out is to edit it on live/dev directly.

Deploying a Lambda Layer for the shared/core code did wonders for making development easier, I wonder if there is something else I'm missing that might make this more sane and speedy?

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.29.4

**What AWS Services are you utilizing?**

Functions/Lambda

**Provide additional details e.g. code snippets**

**Comment by ammarkarachi** [comment]
It could be a possible issue with our mock functions feature. Does `Amplify mock function <functionNAme>`not return errors?

**Comment by PeteDuncanson** [comment]
No. It will just hangs. Apparently the mocking for functions spins up the function in another thread/process and the errors get swallowed. This makings doing any development locally impossible unless you like doing binary chop debugging while trying to find a typo...the only way I found to actually get some output/feedback was to deploy it to the cloud as at least then it will tell you what is wrong. That copy/paste/deploy/upload loop is a killer for productivity (there are only so many times you can resist temptations while you wait..."I'll just go check twitter...")

**Comment by berenddeboer** [comment]
See also #5159. Long standing issue.
