### ISSUE TITLE
How can I add a build script to load initial data?

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-cli#5555]
**Describe the solution you'd like**
I would like to load initial data to the database at the end of the backend build but prior to testing.  Is there any explanation/examples of how to do this, if not could someone add an example to documentation or provide a scripted option to do so e.g. 'amplify add data' to create the necessary entries and template files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ammarkarachi** [comment]
Hi @duncangroenewald, we do not support any data migration or data entry scripts in Amplify CLI. Your approach would defer on what type of data is it you are trying to load and from where you are try to load it and what's its destination
