### ISSUE TITLE
How to prevent a single field from being publicly available

### ISSUE THREAD

**Issue by bart** [aws-amplify/amplify-cli#5556]
Hey, it still looks like it's not possible to prevent a single field from being publicly available. I have a User model and want to allow all fields being publicly available except email. How would I do that? As @codepreneur stated in #4370 making one field public will result in all fields being public. Any solution?

```
type User @model @auth(
  rules: [
    { allow: groups, groups: ["Admin"], operations: [create, update, delete] }
    { allow: public, provider: iam, operations: [read] }
    { allow: private, operations: [read] }
  ]
) {
  id: ID!
  email: String @auth(rules: [{ allow: public, provider: iam, operations: [] }]) # ???
  name: String
  address: String
}
```

**Comment by bart** [comment]
All right, looks like I found a solution. Super weird and tricky but seems to work:

```
type User @model(subscriptions: null) @auth(
  rules: [
    { allow: groups, groups: ["Admin"], operations: [create, update, delete] }
  ]
) {
  id: ID! @auth(rules: [{ allow: public, provider: iam, operations: [read] } { allow: private, operations: [read] }]) @aws_cognito_user_pools
  email: String @aws_cognito_user_pools
  name: String @auth(rules: [{ allow: public, provider: iam, operations: [read] } { allow: private, operations: [read] }]) @aws_cognito_user_pools
  address: String @auth(rules: [{ allow: public, provider: iam, operations: [read] } { allow: private, operations: [read] }]) @aws_cognito_user_pools
}
```

This makes all fields public and private accessible except email field. Hope it helps!

**Comment by danrivett** [comment]
Nice work @bart but with us having to disable subscriptions to be able to have auth rules on required fields (like you've done), I assume this prevents this working with DataStore, since I believe it uses subscriptions to keep the datastore in sync?

I'm not clear about this, so could be wrong. If that's the case though that's a blocker for me unfortunately 😞

**Comment by bart** [comment]
Hey @danrivett first of all sorry for my late response. Was a bit busy last couple of days. Last but not least my answer to your question is short. When I got faced with that problem of permissions in Amplify I gave up in the end. One of the problems I had was the one I described above. But in general permission control is not fine grained enough in my opinion so that it is not possible to use in a production environment. Especially in my case that was the reason to fall back to good old NodeJS API gateway backed by Serverless Framework. Hopefully they will improve rules and permissions so that I can give Amplify a new chance with one of my upcoming projects.

**Comment by danrivett** [comment]
No problem @bart, thanks for getting back to me. Yeah I ran into quite a lot of pain trying to use field level permissions and ran away from it too.

I had a slightly different use case and I documented it in #6360 but it looks like that capability is very narrow in scope and not capable enough for what we needed.
