### ISSUE TITLE
How to do bi-directional one to one relationship? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#556]
** Which Category is your question related to? **
graphql-transformer

** What AWS Services are you utilizing? **
AppSync / Dynamo

** Provide additional details e.g. code snippets **

I'm currently running into a situation where initially I had a model like follows: 

```
type Post @model {
    id: ID!
    title: String!
}

type Response @model {
    id: ID!
    content: String!
    post: Post @connection
}
```

This correctly stores a 'responsePostId' for each row in the Response table. 

And then I decided I wanted access to 'response' from the Post model so I modified the schema to the following: 

```
type Post @model {
    id: ID!
    title: String!
    response: Response @connection(name: "PostResponse")
}

type Response @model {
    id: ID!
    content: String!
    post: Post @connection(name: "PostResponse")
}
```

What this does is create a "postResponseId" attribute for every new model in the Posts table and uses $context.source.postResponseId to get Post.response. However I don't need that index, because to get the response for a post (through the Post.response resolver) I should just use $context.source.id and as the value for "responsePostId' in the Response data source. 

Note if I change the Post schema to a one to many relationship:

```
type Post @model {
    id: ID!
    title: String!
    responses: [Response] @connection(name: "PostResponse")
}
```

The Post.responses resolver correctly queries using $context.source.id rather than a $context.source.postResponseId. 

I read https://aws-amplify.github.io/docs/cli/graphql?sdk=js and it talks about how to do bidirectional one-to-many relationship and a simple one-to-one relationship but there is no example in there for a bidirectional one-to-one. Am I missing something here. Maybe one-to-one bidirectional relationships are not supported because there is no way to enforce the strict 1:1ness in the database?

**Comment by hisham** [comment]
I'm looking at the code here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts#L132

And it looks like the case of `{} to {}` is not mentioned or handled. Why?

**Comment by watanabethais** [comment]
I'm new to AWS and I'm testing AppSync... I ended up with this same question.
Any answers?

**Comment by mikeparisstuff** [comment]
This can be implemented via a BatchWrite operation or via an AppSync pipeline resolver but is not yet implemented out of the box via the GraphQL transform. To build this yourself, you may use the @connection directive to configure the has one relationship on both @model types and then implement your own updatePost & updateResponse resolvers such that they use a pipeline resolver or BatchWrite operation to write the id of the other object into both records in both tables.

**Comment by janhesters** [comment]
@mikeparisstuff Do you have to do the same for create? Because I also tried this like this:

```graphql
type Coordinates
  @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  latitude: Float!
  longitude: Float!
  address: Address! @connection(name: "AddressCoordinates")
}

type Address @model(queries: { get: "getAddress", list: "listAddresses" }) {
  id: ID!
  country: String!
  city: String!
  zipCode: String
  streetName: String!
  streetNumber: String
  # notice the optional parameter below, because addresses exist first
  coordinates: Coordinates @connection(name: "AddressCoordinates")
}
```

But when I first create an `Address` entity and then create `Coordinates` using to the `Address`'s ID, it correctly points to the `Addreess` from `Coordinates` but not the other way around.

Would I also have to write a custom resolver for `createCoordinates` using `batchWrite` to write both the new `Coordinates` and populate the corresponding field for the coordinates id on the address' field?

**Comment by monaye** [comment]
@mikeparisstuff 
Any plan on this will be available out of the box?

**Comment by jarrodb** [comment]
Ping.  These are great questions.  I am new to Amplify and ran into the same issue trying to model a one-to-one through the connection.

**Comment by Jobel91** [comment]
This video may help you : https://www.youtube.com/watch?v=eUQvsuO6EnU

**Comment by galales** [comment]
> This video may help you : https://www.youtube.com/watch?v=eUQvsuO6EnU

The video is useful to have a very clear overview about relationships implementation, but it doesn't help with this specific topic

**Comment by Graig123git** [comment]
I am also facing the same issue where i am not able to do one to one bidirectional relationship.
In my case i am trying to achieve the following, A User can only make one Post at a time and a Post can only have one User as its owner. Any suggestion on how to solve this @mikeparisstuff

**Comment by gautamkshitij** [comment]
I am on the same topic too! any solutions to that? Unless we implement ourselves using GraphQL lambda resolvers?

**Comment by Graig123git** [comment]
There should be an easier way to achieve these functionlaities without writing custom resolvers.

**Comment by gautamkshitij** [comment]
Any ideas? 😅 or Do we wait for amplify maintainers??

**Comment by Graig123git** [comment]
@gautamkshitij i guess we have to wait, but for now i switch over to aurora serverless, it as serverless relational database which makes things more closer to our traditional databases.

**Comment by cheunjm** [comment]
bump!

**Comment by Werbelow** [comment]
I have also run into this issue, would love some guidance on the best way to handle this.

**Comment by dylan-westbury** [comment]
We run into also.

Our use case is.
Reward (can be redeemed)
Redeem  (a redemption of a reward)

Each redeem record has a a reward attached to it. For reward record it doesn't include the redeems.

**Comment by econtentmaps** [comment]
+1 into the months-long echoing silence!

**Comment by jgroom33** [comment]
the workaround I've implemented is to use 1:M relationships.  This allows the parent and child to auto populate the ID's.
imo, 1:1 is useless until this is fixed

**Comment by bcs-gbl** [comment]
+1

**Comment by gilvaju** [comment]
+1

**Comment by seanim0920** [comment]
+1

**Comment by ctjlewis** [comment]
This is a traditional example, where each `ProfilePicture` belongs to one `User` and each `User` has one `ProfilePicture`.

```graphql
type ProfilePicture @model {
  user: User! @connection
}

type User @model {
  profilePicture: ProfilePicture @connection
}
```

We want to use `CreateProfilePicture` and, supplying only the user ID and necessary data, and create *both* the `ProfilePicture { user: { ... } }` *and* update `User { profilePicture: { ... } }`. At present, only the former happens.

How can we establish an automatic bidirectional connection in AppSync?

**Comment by nonrevlb** [comment]
I am also having this problem.

**Comment by ykethan** [comment]
Hey y'all 👋 we really appreciate the feedback here! This is now supported via a new directive `@belongsTo` to be used in conjunction with `@hasOne` and the `@hasMany` to bidirectional relationships.

For additional information please refer to: https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship

 Closing issue 😃 . **If you are still experiencing this issue or feel the features do not quite cover your use case please reply back to this thread and we can re-open to investigate further**

**Comment by gxxcastillo** [comment]
Hi @ykethan, following up on this, I can see how the `@hasOne` relationship on type A results in a reference to a related model, B and how the `@belongsTo` sets up a relationship back to A.  

However, I don't see how to enforce the bi-directional relationship in the sense that creating type A, with a reference to a new type B doesn't seem to result in the relationship from B to A getting created.  As far as I can tell, I need to ensure I update the appropriate field in B to point back to A? If so, is this something I should be able to do with a `BatchPutItem` that creates both A and B at the same time, with references to each other?

**Comment by vincent38wargnier** [comment]
Hi,
the example is the doc is not working for me, i get those results after setting those tables : 
```
type Individual @model {
  id: ID!
  homeAddress: Address @hasOne
  shippingAddress: Address @hasOne
}

type Address @model {
  id: ID!
  homeIndividualID: ID
  shippingIndividualID: ID
  homeIndividual: Individual @belongsTo(fields: ["homeIndividualID"])
  shipIndividual: Individual @belongsTo(fields: ["shippingIndividualID"])
}
```

Requests : 
```
mutation MyMutation {
  createIndividual(input: {id: "i1"}) {
    id
  }
}

mutation MyMutation2 {
  createAddress(input: {homeIndividualID: "i1", id: "a1"}) {
    id
    homeIndividual {
      id
      homeAddress {
        id
      }
    }
  }
}

```

Résult : 
```
{
  "data": {
    "createAddress": {
      "id": "a1",
      "homeIndividual": {
        "id": "i1",
        "homeAddress": null
      }
    }
  }
}
```

So here the @hasOne and @belongsTo are not related to each other. I tried with the Amplify mock and AWS AppSync and I get the same issue.

HELP
