### ISSUE TITLE
Unable to install amplify cli on macOS BigSur Beta

### ISSUE THREAD

**Issue by hinddeep** [aws-amplify/amplify-cli#5561]
[error2.txt](https://github.com/aws-amplify/amplify-cli/files/5365607/error2.txt)
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm unable to install amplify cli on macOS BigSur Beta 9

**Amplify CLI Version**
NA

**To Reproduce**
Install amplify CLI using the following command:
```
sudo npm i -g @aws-amplify/cli
````

**Expected behavior**
Amplify CLI should be installed.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur beta 9
 - Node Version: v14.13.1

**Additional context**
Please check the attached error log for more details.

**Comment by yuth** [comment]
@hinddeep do you have NVM or some other node version managers installed on your computer?

**Comment by hinddeep** [comment]
No, I've not installed any node version manager on my system.

**Comment by yuth** [comment]
Thank you, I could not get this installation to fail beta version of BigSur. From the error log file it looks like npm cache issue. Could using temp cache using the following command and see if `npm install -g @aws-amplify/cli --cache /tmp/empty-cache` and see if the installation works

**Comment by hinddeep** [comment]
Oh wow! That worked like a charm! Thank you so much for providing the fix.
