### ISSUE TITLE
layers not working correctly with enviornments

### ISSUE THREAD

**Issue by waynebrantley** [aws-amplify/amplify-cli#5562]
**Describe the bug**
Let's say - you have a lambda layer in an environment - say 'dev' and it is on version 10.
You then create a new environment 'staging' and push to it.
The new environment will be on version 1.
The cloud formation templates for the lambdas that use layers will still be pointing to version 10 in dev environment!
```
 "Runtime": "nodejs12.x",
        "Layers": [
          {
            "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:testLayer-dev:10"
          }
        ],
```
**Amplify CLI Version**
4.29.6

**To Reproduce**
Create a new project with a "dev" environment that has  a layer and a lambda that uses that layer.  Push it.
Create a new environment and push it.  
Examine the cloudformation template for the lambda and you will see the layer still points to the "dev" environment.
You would not generally notice this as the layers are shared in the same account.  If you use two aws accounts for each environment you would get an error as the "dev" one would not exist in the new one.  Even without two accounts, the lambda in the new environment is using the wrong layer!

**Expected behavior**
Lambdas with layers should respect environments when referencing layers. 

**Additional context**
Not sure how you can fix this.   One thing that would help is to use env in the name of the layer like below.  However, this stil leaves the issue of what version for each environment.
```  
"Runtime": "nodejs12.x",
        "Layers": [
          {
            "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:testLayer-${env}:10"
          }
        ],
```
This brings up an additional pain point.  If you have 10 lambdas and they all use the same layer and version (usually the case), it is very painful to update them all to the latest version using the CLI.  I would be fine with every lambda in the current project always referring to the latest version of the layer - and that would help this situation too.
Just a thought...

**Comment by SwaySway** [comment]
Closing this issue in favor of #5479. Please follow that issue for updates.
