### ISSUE TITLE
amplify push doesn't update local graphql operation files in my react project.

### ISSUE THREAD

**Issue by simon-zhangmuye** [aws-amplify/amplify-cli#5567]
Need help. I add an Amplify api and make some changes to my schema.graphql file.
Then I use amplify push to generate graphql operations in my local env.
After that I make some changes in my schema again and use amplify push to upload.
This time my local graphql operations files don't upgrade.
Does anyone know how to solve this problem?

**Comment by simon-zhangmuye** [comment]
I add username, avatar, userid to my Post model in schema.graphql file. Then use amplify push, it updates the operations on the cloud but not the local files in my src/graphql.
![image](https://user-images.githubusercontent.com/10706610/95822567-e6d63780-0d77-11eb-925f-8c6866af81f9.png)
![image](https://user-images.githubusercontent.com/10706610/95822588-f05f9f80-0d77-11eb-9489-4f8f360d767c.png)
![image](https://user-images.githubusercontent.com/10706610/95822614-fc4b6180-0d77-11eb-83c7-29acc2d56182.png)

**Comment by lelocodelo** [comment]
I have the same problem right now. I updated my schema and used `amplify push`, usually my graphql/* files get updated, but not this time. Does anyone know how to resolve this or how to fetch the code from the cloud.
