### ISSUE TITLE
Layer deleted after switching environments

### ISSUE THREAD

**Issue by marziamura** [aws-amplify/amplify-cli#5568]
**Describe the bug**
I have a multienv project: dev and prod.  If I create a layer in dev, it does not appear on prod, and switching back to dev causes its deletion (or so it looks like from the cli)

**Amplify CLI Version**
4.29.2

**To Reproduce**
I have two environments prod and dev

* create lambda layer in dev
* amplify push (on dev)
* amplify env checkout prod
* amplify status
  * expected==> new layer should be visible (added to prod)
  * actual ==> layer was not there (bug nb. 1)
at this point I thought, also after reading some other comments online, that the layer was shared and didn't need to be added to prod. So...
* amplify update function 
* select one of the lambda functions to try to add the layer to it,
 * expected ==> The layer should be listed
 * actual ==> The layer was not there
mmhh so okay what about the dev env at this point?

* amplify env checkout dev
* amplify status
  * expected ==> no changes
  * actual ==> layer shows as to be deleted

**Expected behavior**
layer should be visible on all env and not getting deleted.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Node Version: 14.8.0

**Additional context**
multi env

**Comment by yuth** [comment]
@marziamura Could you try the following workflow and see if it works


1. create lambda layer in dev
2. amplify push (on dev)
3. git commit the changes
4. git checkout to prod
5. ampify checkout env prod
   i. You should get an prompt asking if you want to copy the layer or reference it
6. amplify status

**Comment by marziamura** [comment]
yes I'll try that as soon as I can. thanks for looking at this

**Comment by waynebrantley** [comment]
likely because the env needs manually changed in the cloud formation files.
https://github.com/aws-amplify/amplify-cli/issues/5479

**Comment by SwaySway** [comment]
@marziamura Were you able to try the suggested workflow?

**Comment by jhockett** [comment]
Closing due to lack of response. Please comment below if you still run into this issue.
