### ISSUE TITLE
When switching environment, lambda function code is reverted to old version 

### ISSUE THREAD

**Issue by marziamura** [aws-amplify/amplify-cli#5569]
**Describe the bug**
I have created two lambda functions on my amplify project.
Now whenever I switch environment the code of my functions get reverted to some older version, different from the one version I have deployed. 

**Amplify CLI Version**
4.29.2

**To Reproduce**
I am not too sure how this got currupted in the fist place. It might be that sometime I changed the code directly from the aws console.
Two env prod and dev 
* start on dev
* have a lambda function at version N
* modify it
* push to git
* push to amplify
* merge on git to prod
* git checkout  prod 
* amplify env checkout prod 
* amplify pull 
* amplify status ==> no changes
* git diff
   * expected ==>no changes
   * actual ==> function showing changes from version N -m ( not sure what m is at this point)
* git checkout dev
* amplify env checkout dev
* git diff
  * expected ==> no changes
  * actual ==> same as prod
* amplify status
   * expected ==> no changes
   * actual ==> functions are showing as changed (Update status)

As an additional note, I am checking the code on github and aws console, and nowhere I can see the old code amplify is reverting to as current version.

**Expected behavior**
Functions should not be reverted to an old (random?) version

**Screenshots**

**Desktop (please complete the following information):**
 - Windoes
 - Node Version. 14.8.0

**Additional context**
multienv

**Comment by yuth** [comment]
@marziamura  could you explain what do you mean by 

> merge on git to prod.

Does this mean you're currently in `dev` branch and then you're running
```shell
git merge prod # merging changes from prod back to dev
```

**Comment by marziamura** [comment]
I didn't run a git merge directly, I created a pull request on dev branch and merged it. I guess the results should be the same

**Comment by yuth** [comment]
Could you try checking out the branch first and then doing the `amplify env checkout <env-name>`. The environment checkout command should sync the functions and layers

**Comment by marziamura** [comment]
This seems to improve the behaviour but I still see changes that look random. I didn't try to understand what steps are leading to these, so I'll close this for now. Thanks for the help.
