### ISSUE TITLE
Mock does not clean resources when closing

### ISSUE THREAD

**Issue by TheAlot** [aws-amplify/amplify-cli#5579]
**Describe the bug**
If you run `amplify mock`, wait for it to finish and press ^C, the generated resolvers are not removed, and aws-exports.js is not reset to it's original form. 

**Amplify CLI Version**
4.29.7

**To Reproduce**
1. Create a new amplify project, with a sample schema.
2. Run `amplify mock`
3. Press ^C

**Expected behavior**
The generated appsync resolvers should be removed, and aws-exports.js should no longer contain test values.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Node Version. 14.13.0

**Additional context**
I tried to install previous versions of the amplify-cli, version 4.29.3 and above have this issue. I built the cli locally, and applied the latest fix to master (#5576), however this did not help the issue. The cli no longer crashes, but still exits before it has cleaned the project.

**Comment by edwardfoyle** [comment]
The fix for this has been released in CLI v 4.32.0
