### ISSUE TITLE
post confirmation lambda trigger

### ISSUE THREAD

**Issue by reinhal** [aws-amplify/amplify-cli#5584]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

really not sure: post confirmation lambda triggers

I am not sure where to ask this but I am looking to use a lambda post confirmation trigger with cognito to create a fresh copy of documents/table in dynamo db every time a new user is created.  My schema uses the @amodel, @auth,  and @connection directives. 

Can someone point me to some documentation/resources to help me build this out?

**Amplify CLI Version** 4.29.5

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

in process: AppSync (GraphQL), Lambda, Incognito, DynamboDb, possibily S3

**Provide additional details e.g. code snippets*

**Comment by yuth** [comment]
@reinhal what is the use case that you're trying to solve? Creating a new table for each confirmed user may not scale well as there is limitation on the number of tables an account can have. Also keep in mind the GraphQL transformer works at the deployment time and provisions tables and creates DataSources to be used by AppSync service and does not support  creation dynamic DynamodDB table/DataSources that might be needed to connect to these new tables that created in Post confirmation lambda trigger.

**Comment by reinhal** [comment]
@yuth Thank you for your patience as I try to explain what I am looking to accomplish.  There is a default set of data that each new user should have a copy of to create/update/delete for their account.  Maybe not a new table, but new copies of the default set of documents from each table. 

I was told I could create a post confirmation lambda trigger to accomplish this, but maybe you have another approach?

**Comment by yuth** [comment]
@reinhal Post confirmation trigger makes sense. You could give the post confirmation lambda trigger access to the AppSync API and then can trigger an mutation from your lambda trigger which adds a record in the required table. You can give permission to your lambda trigger function by running `amplify update function` and then choosing the trigger function.

In `Do you want to update the Lambda function permissions to access other resources in this project?` answer `Yes` and allow permission to `GraphQLAPI` to get the IAM policy updated to execution of mutation from the function.

**Comment by reinhal** [comment]
@yuth once I add that function and give it the appropriate access/permissions, are the next steps in the code for actually creating copies of the data items in each of the necessary tables? is their good documentation somewhere for that side of it?

**Comment by yuth** [comment]
Yes, You should have the API endpoint available to you as an env variable once the appropriate access is allowed. In your lambda you could fire an mutation request to add the data items and sing it using the IAM credentials.
