### ISSUE TITLE
Issue using "attributeExists" in list resolver

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#5589]
**Describe the bug**

I have a list query resolver that is the standard generated by Amplify. However, when I execute a query using the operator "attributeExists" as shown below it generates an error.

```
query search{
  listAssets(
  	filter:{assetStatus:{attributeExists: false}}
    limit:10
  )
  {items{id}}
}
```

The error that is generated from what should be a straight forward query looks like this

```
{
  "data": {
    "listAssets": null
  },
  "errors": [
    {
      "path": [
        "listAssets"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "ExpressionAttributeValues must not be empty (Service: DynamoDb, Status Code: 400, Request ID: CGT0NK9ADHR8LVODDPV68N3B37VV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"
    }
  ]
}
```

**Amplify CLI Version**

4.29.8

**To Reproduce**

Execute a simple query like that shown above

**Expected behavior**

Data matching the query is returned without error

**Comment by SwaySway** [comment]
Hello @sacrampton 
I was able to reproduce this and it seems that it's coming from the `toDynamoDBFilterExpression` utility in AppSync. I've noticed the team of this change, though I would also recommend their support forum for further visibility. https://forums.aws.amazon.com/forum.jspa?forumID=280

A potential workaround I can think of would be to remove it if there are no expression values.
```
#if( $context.args.filter )
  #set( $filter = $util.parseJson($util.transform.toDynamoDBFilterExpression($ctx.args.filter)))
  #if($filter.expressionValues.keySet().size() < 1)
  	$util.qr($filter.remove("expressionValues"))
  #end
  #set( $ListRequest.filter = $filter )
#end
```

**Comment by SwaySway** [comment]
Closing as this is a dependency is an issue. The AppSync team has been made aware of this issue.

**Comment by hisham** [comment]
7 months later and still an issue...
