### ISSUE TITLE
Can't update to the latest version (4.29.8)

### ISSUE THREAD

**Issue by TheDutchCoder** [aws-amplify/amplify-cli#5590]
**Describe the bug**
Global install results in "Unexpected end of JSON"

**Amplify CLI Version**
4.29.4

**To Reproduce**
Run `npm i -g @aws-amplify/cli`

**Expected behavior**
Amplify cli to update

**Screenshots**
![image](https://user-images.githubusercontent.com/1668207/96128530-7b997c00-0ec3-11eb-8278-7a05655b64b2.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6
 - Node Version. 10.14.2

**Comment by yuth** [comment]
@TheDutchCoder I could not get this installation to fail. From the error log file it looks like npm cache issue. Could using temporary cache using the following command and see if npm install -g @aws-amplify/cli --cache /tmp/empty-cache and see if the installation works

**Comment by TheDutchCoder** [comment]
Okay that seemed to have worked, thanks!
