### ISSUE TITLE
get and set of array values not working in amplify-velocity-template

### ISSUE THREAD

**Issue by MainAero** [aws-amplify/amplify-cli#5593]
The implementation of `set` and `get` methods of an array in velocity is not working like in the real environment.

[These lines](https://github.com/aws-amplify/amplify-cli/blob/41c99f8f956e46966779fbfa3a205a0fab39ea1f/packages/amplify-velocity-template/src/compile/references.js#L229-L248) should be replaced by an implimentation like:
```ts
if (id === 'get' && !baseRef[id]) {
    return baseRef[this.getLiteral(property.args[0])];
} else if (id === 'set' && !baseRef[id]) {
    return baseRef[this.getLiteral(property.args[0])] = this.getLiteral(property.args[1]);
} 
```

**Comment by MainAero** [comment]
May related: https://github.com/shepherdwind/velocity.js/pull/132

**Comment by yuth** [comment]
@MainAero Thank you for bringing this to our attention. We would appreciate an pull request as we are not merging the upstream to our implementation.

**Comment by renebrandel** [comment]
@MainAero - we're about to create a PR for this but wanted to make sure if you want to contribute to provide you an opportunity to do so. Happy to address this either way.

**Comment by MainAero** [comment]
@renebrandel thanks I created a [PR](https://github.com/aws-amplify/amplify-cli/pull/5741) for that.

As we are currently working on a typescript based test util for Appsync which enables you to write functional / integration test for your vtl resolvers I guess we might open a few PR's.

**Comment by renebrandel** [comment]
Cc @yuth
