### ISSUE TITLE
API Cloudformation Json Template ::: may not exceed 468992 bytes in size.

### ISSUE THREAD

**Issue by lr001dev** [aws-amplify/amplify-cli#5596]
Creating an issue here:
Running Amplify 4.29.8

Running into a problem when adding multiple paths using amplify update api command. When trying to push I receive the below error. I'm trying to add multiple paths to our REST API. Could use some guidance.

So, I updated my cli and I'm getting this error:

`AWS::CloudFormation::Stack Wed Oct 14 2020 00:02:12 GMT-0700 (Pacific Daylight Time) Template
 may not exceed 468992 bytes in size.`

My api-cloudformation.json is breaking the limit, so not sure how to fix this....

_Originally posted by @lr001dev in https://github.com/aws-amplify/amplify-cli/issue_comments/708222360_

**Comment by SwaySway** [comment]
@lr001dev 
The original issue # is missing in the link.

How many paths did you add? Could send over your Rest API CFN template to amplify-cli@amazon.com?

**Comment by lr001dev** [comment]
Sent @SwaySway

**Comment by yuth** [comment]
Amplify CLI creates single cloudformation file for a REST API and it looks like your REST API has exceeded the size supported by cloudformation. The generated JSON file has a lot spaces included, which makes the files easier to read but now it is hitting the cloudformation file size limit. I have marked this as a bug and we will try to split the this to multiple stacks so the file size issue can be resolved.

In the meantime, could you try minifying the file which reduces the file size significantly

**Comment by lr001dev** [comment]
Thank you for your response. I minified the file and successfully pushed, so that helped! I understand however, this is a bug and there will be an expected change addressing this issue, correct?

**Comment by kaustavghosh06** [comment]
@lr001dev CloudFormation just announced a limit increase of the template size to more than double. Here's the launch announcement - https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/ and if you're still running into template size limitations please let us know.

**Comment by lr001dev** [comment]
Sounds great.. and thanks for the quick support!
