### ISSUE TITLE
Refresh page, then Access Denied error

### ISSUE THREAD

**Issue by lochawala** [aws-amplify/amplify-cli#5599]
I have hosted my react app using amplify add host and amplify publish it's working fine, but when I refresh the page, then it's throw Access Denied error 
please check attach a screen shot of the error

![Screen Shot 2020-10-16 at 1 21 35 PM](https://user-images.githubusercontent.com/14148438/96228192-db228500-0fb2-11eb-8d97-b61b0279dbac.png)

**Comment by yuth** [comment]
@lochawala In your react app do you use routers? Does the URL change when the page loads?

**Comment by lochawala** [comment]
@yuth yes i am using routers in my react app & UEL change when the page loads

**Comment by kaustavghosh06** [comment]
@lochawala  Are you using Amplify console hosting or S3+Cloudfront hosting option from the CLI?

**Comment by lochawala** [comment]
Hi @kaustavghosh06 
I am using Amplify console hosting

**Comment by kaustavghosh06** [comment]
@swaminator @litwicki Have you'll seen this issue with Amplify Console Hosting before?

**Comment by litwicki** [comment]
@lochawala what is your "build" folder for your app, and the `baseDirectory` directory on your buildspec?

This can happen for a couple reasons. The most common is that the `baseDirectory` directory is set incorrectly in the buildspec file. 

```version: 0.1
frontend:
  artifacts:
    baseDirectory: build
    files:
      - '**/*'

**Comment by lochawala** [comment]
Hi Thanks all for your valuable time I have solved it 
please check screen shot for solution 

![Screen Shot 2020-10-26 at 10 24 04 AM](https://user-images.githubusercontent.com/14148438/97135111-6a7b2580-1775-11eb-83b1-8261df5c3af1.png)

**Comment by igorkosta** [comment]
@lochawala where have you added this `Rewrites and redirects`?

**Comment by lochawala** [comment]
@igorkosta you can find it in amplify app

Aws amplify 
Select your app
Left side you find rewrite rule menu

**Comment by igorkosta** [comment]
@lochawala thank you very much - already found it.

**Comment by KittPhi** [comment]
@lochawala Thank you for sharing your solution! Appreciated it!
