### ISSUE TITLE
Add README.md into amplify directory

### ISSUE THREAD

**Issue by watilde** [aws-amplify/amplify-cli#5600]
**Is your feature request related to a problem? Please describe.**
It was not easy to understand what each files and directories mean under amplify directory when running `amplify init` for the first time.

**Describe the solution you'd like**
Adding `README.md` under amplify directory describing clear high level description of each directories and files in the below at least:
+ .config
+ backend
+ team-provider-info.json

Additionally, having a version of `amplify-cli` in somewhere like `amplify/.config/project-config.json` would help us to maintain the description of them in `README.md` file.

**Describe alternatives you've considered**
Just having reference links would be a good starting point

**Additional context**
By having the description in the project, people do not need to often switch apps between their editors and the official website.

**Comment by renebrandel** [comment]
I love this idea!

**Comment by renebrandel** [comment]
We've recently compiled this page detailing all the different files & folders. https://docs.amplify.aws/cli/reference/files Is this the level of information you're looking for? 
I'm curious what other information could come in handy?

**Comment by watilde** [comment]
Great, that's exactly what I was looking for! In addition, I was thinking of something like `create-react-app`'s `README.md` that explains how to use `amplify-cli` + resources to learn as more useful to users.

+ Refs: https://github.com/facebook/create-react-app/blob/de27bcfcc079c6644a14db08ef01df1f102e7a95/packages/cra-template/template/README.md

The resource priorities that can be helpful to users is below IMO:

1. How to use `amplify-cli` which can be similar to `amplify -h`
2. Useful resource links
    1. What's amplify: [link](https://docs.amplify.aws/cli)
    2. Getting started: [link](https://docs.amplify.aws/cli/start/install)
    3. Files and Folders: [link](https://docs.amplify.aws/cli/reference/files)
    4. Community: [link](https://amplify.aws/community/)

**Comment by renebrandel** [comment]
Fantastic feedback @watilde - I'll look into this next week.
