### ISSUE TITLE
Force-sync cloud state to local state?

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#5601]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Syncing cloud and local state

**Amplify CLI Version** 
4.29.6

**What AWS Services are you utilizing?**
AppSync/GraphQL, DynamoDB, Lambda, Cognito

**Provide additional details e.g. code snippets**
I'm in the initial stages of development. For the time being I don't have any important data to keep hold of, and speed of iteration is my highest priority.

I'd like to be able to force-sync the cloud state to the local (git-tracked) amplify state (using the default auto-generated `.gitignore`).

For instance, say I want to modify the key of a certain `@model` object: I want amplify to simply tear down any existing cloud resources, and put them up from scratch using the new table layout.

Is there any way to achieve this?

(NOTE: I've seen some suggestions to achieve the particular effect of my example by removing the model object from my gql scheme  altogether, pushing to the cloud, adding it back, and pushing again. This doesn't work for me because other resources in my amplify stack depend on this model (e.g. a lambda function which has access to said table). And besides, I'm interested in the general solution more than in this one particular example.)

**Comment by yuth** [comment]
We have similar request which is being tracked in https://github.com/aws-amplify/amplify-cli/issues/2384. I am closing this in favor of that ticket so we can consolidate all the discussion in one ticket. 

I would appreciate if you could add your thoughts and what workflow you would like to see in #2384.
