### ISSUE TITLE
Amplify GraphQL API - Lambda function user-defined subfields

### ISSUE THREAD

**Issue by dominiksafaric** [aws-amplify/amplify-cli#5603]
**Which Category is your question related to?**
GraphQL Lambda function

**Amplify CLI Version** 
4.29.7

**What AWS Services are you utilizing?**
Amplify, AppSync GraphQL API, DynamoDB, Lambda, Cognito

**Provide additional details e.g. code snippets**
I have specified a custom GraphQL mutation called `updateCandidate` that forwards the request to a custom Lambda function with Python runtime. Please refer to the code snippet below for an example of the mutations invocation. My question refers to passing subfield information to the Lambda function. In the below example, I'd like the function to return only the `id` and `hasLiked` attributes. But, the list of these subfields is not forwarded within the Lambda event or context object.

```gql
mutation MyMutation {
  updateCandidate(input: {
    id: "7d50e944-ed8e-434b-8850-44357b80bb6a"
    userId: "c16df09d-2a67-4b6e-8799-abe62e2c47bd",
    candidateId: "3aa7d684-b5f2-4445-bc46-6e604befe295"
  }) {
    id,
    hasLiked
  }
}
```
The handler function receives an event such as the following:
```
{
	'typeName': 'Mutation',
	'fieldName': 'updateCandidate',
	'arguments': {
		'input': {
			'id': 'a256ee79-803e-4982-bccf-118897990aa1',
			'userId': 'c16df09d-2a67-4b6e-8799-abe62e2c47bd',
                         'candidateId': '3aa7d684-b5f2-4445-bc46-6e604befe295'
		}
	},
	'identity': None,
	'source': None,
	'request': {
		'headers': {
			
		}
	},
	'prev': {
		'result': {}
	}
}
```
But within it, there is no field describing the list of subfields that should be returned by its invocation. My question is, how can you pass this list of subfields to return from a query?

**Comment by yuth** [comment]
@dominiksafaric you can return all the subfields, and the appsync service will return only the fields that are requested in the API to the client. 

If you want to optimize and not send every subfield back from lambda to appsync, you can will have to update your lambda function invocation code to include [`context.info`](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-info) which includes selection set. 

```
## file: amplify/backend/api/upload/pipelineFunctions/Invoke<LambdaFunctionName>LambdaDataSource.req.vtl
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": "$ctx.stash.get("typeName")",
      "fieldName": "$ctx.stash.get("fieldName")",
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev),
      "info": $util.toJson($ctx.info) ## add this line
  }
}
```

**Comment by kaustavghosh06** [comment]
Closing based on the response above. If you're still stuck please let us know.
