### ISSUE TITLE
Primary sort key does not work

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#5605]
**Describe the bug**

I have the following schema:

```gql
type Lesson
  @model
  @key(fields: ["id", "lessonNumber"]) {
  id: ID!
  title: String!
  lessonNumber: Int!
  intro: AWSJSON!
}
```

which correctly generates a DynamoDB table with `id` as a primary partition key and `lessonNumber` as a primary sort key. 

Now, I am issuing the following auto-generated query:

```gql
 query ListLessons(
    $id: ID
    $lessonNumber: ModelIntKeyConditionInput
    $filter: ModelLessonFilterInput
    $limit: Int
    $nextToken: String
    $sortDirection: ModelSortDirection
  ) {
    listLessons(
      id: $id
      lessonNumber: $lessonNumber
      filter: $filter
      limit: $limit
      nextToken: $nextToken
      sortDirection: $sortDirection
    ) {
      items {
        id
        title
        lessonNumber
        intro
        createdAt
        updatedAt
      }
      nextToken
    }
  }
```

I expect this query to return a properly sorted list of lessons, however, I get the following result: 

```json
{
  "data": {
    "listLessons": {
      "items": [
        {
          "id": "6ee94aa8-fbe9-45f0-93e1-41c9045634f0",
          "title": "Second lesson",
          "lessonNumber": 2,
          "intro": "[{\"children\":[{\"text\":\"some text\"}],\"type\":\"paragraph\"}]",
          "createdAt": "2020-10-16T14:40:23.789Z",
          "updatedAt": "2020-10-16T14:40:23.789Z",
          "exercises": {
            "nextToken": null
          }
        },
        {
          "id": "06350758-6e19-4277-8e57-41ed5e6c66ef",
          "title": "Some Title",
          "lessonNumber": 1,
          "intro": "[{\"children\":[{\"text\":\"some text\"}],\"type\":\"paragraph\"}]",
          "createdAt": "2020-10-16T14:33:43.540Z",
          "updatedAt": "2020-10-16T14:33:43.540Z",
          "exercises": {
            "nextToken": null
          }
        },
        {
          "id": "fae9fb4e-e7b4-4e84-9d9e-2e41137ecf79",
          "title": "Twelve",
          "lessonNumber": 3,
          "intro": "[{\"children\":[{\"text\":\"some text\"}],\"type\":\"paragraph\"}]",
          "createdAt": "2020-10-16T14:40:55.745Z",
          "updatedAt": "2020-10-16T14:40:55.745Z",
          "exercises": {
            "nextToken": null
          }
        }
      ],
      "nextToken": null
    }
  }
}
```

notice `lessonNumber` field in the above result, the result does not come properly sorted. Is this expected behavior?

**Amplify CLI Version**
`4.29.2`

**Comment by yuth** [comment]
@sakhmedbayev What are the arguments that are passed to the list query? From the query results I suspect that you're not passing either `id` or `ModelIntKeyConditionInput`. 

DynamoDB sorting works with in the HASH, and will be sorted when you run a query. When no `id` is passed to `listLesson` the transformer does an DynamoDB scan and sorting is not supported in scan

**Comment by sakhmedbayev** [comment]
Thanks, @yuth, for the quick response. You are correct; I do not pass any arguments; however, I expect the default result will get properly sorted. 

Perhaps, another question, what are my options if I want to return all `Lessons` sorted by `lessonNumber` field???

**Comment by RossWilliams** [comment]
you need to get all lessons into the same partition key. One way to do this is to create an attribute that gets set to the same value for all items and use that as the partition key. type: 'Lesson', version: '1', audience: 'all', or similar.

**Comment by sakhmedbayev** [comment]
@RossWilliams thanks for the advice. It is what I am doing currently. I thought I am doing it incorrectly. Can you tell me please, what happens when I will have a million records of the type `Lesson`? How the data will be distributed among partitions?

**Comment by RossWilliams** [comment]
I don't know the answer to how data will be distributed once you have more than 10GB of lessons. But with adaptive capacity now being "instant", this is less likely of an issue.
