### ISSUE TITLE
Support DynamoDB Table On-Demand Capacity

### ISSUE THREAD

**Issue by StefanSmith** [aws-amplify/amplify-cli#561]
**Describe the solution you'd like**
Support DynamoDB Table `BillingMode` `PAY_PER_REQUEST` in cloudformation template generated by `amplify api gql-compile`

**Describe alternatives you've considered**
Editing cloudformation template after running `amplify api gql-compile`. This would need to be done every time.

**Additional context**
https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-BillingMode

**Comment by mikeparisstuff** [comment]
Thanks for the request. This is a relatively simple change and would be a great opportunity to contribute if you have the time. Otherwise, I will make sure this gets included for planning.

**Comment by haverchuck** [comment]
Marked [this issue ](https://github.com/aws-amplify/amplify-js/issues/2315)as a duplicate.

**Comment by doom777** [comment]
So DynamoDB capacity will now always be On Demand, or will there be a switch to enable either one? Like an interactive question, or maybe a --on-demand/--provisioned switch?

**Comment by haverchuck** [comment]
Noting that this enhancement was also requested in the Amplify Gitter lobby.

**Comment by mikeparisstuff** [comment]
This has been implemented as part of #581

**Comment by kaustavghosh06** [comment]
We've added support for this in our main CLI version.
Please install the latest CLI using `npm install -g @aws-amplify/cli`  and let me know (and re-opne the issue) if you're still facing this issue.

For documentation regarding this, please take a look at https://aws-amplify.github.io/docs/cli/graphql#dynamodbmodeltablereadiops for documentation regarding the same.

**Comment by AbhishekRaval** [comment]
I have been reading documentation and browsing through various Issues, but I am stuck. In my current project I want to use "PAY_PER_REQUEST" mode for dynamoDb database. I am using API Gateway along with serverless CRUD function. I didn't find a way to update dynamodbIOPS for Restful CRUD API created using amplify ?
