### ISSUE TITLE
Can you add to the CLI tool the possibility to rename lambda functions?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5616]
At the moment, when using the command "amplify function update", we can change several parameters, but not the function name or resource name.

Right now I am doing that manually and it is very annoying. 
Can you add this option?

Another nice improvement would be the possibility to duplicate a function with a different name.
Very often I have to copy sections of my cloud formation templates to new functions and this is also very time consuming.

Thanks a lot.

**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
Add a new step in "amplify function update"
Something like: 
Would you like to rename this function? 
What is the new name?

**Describe alternatives you've considered**
Right now I do that manually and takes time.

**Comment by kaustavghosh06** [comment]
@Ricardo1980 I don't believe Lambda allows renaming of it's Lambda function. If you change the name - it would essentially delete your function and then re-create a new one. If we allow for that from the CLI automatically - it might be dangerous for the customers doing this for their prod infra. Although, I like the clone/duplicate idea :)

**Comment by Ricardo1980** [comment]
@kaustavghosh06 
In that case, if you add "clone with a different name", that is OK to me.
When having cloud formation templates modified manually (permissions, parameters...), it is very time consuming having to copy/paste that manually.
Thanks!

**Comment by josefaidt** [comment]
Closing as a "wontfix" due to the underlying nature of changing resource names, and as Kaustav mentioned above this will require a teardown of the existing Lambda. Moving forward, please create a new function with the intended name and copy the relevant source
