### ISSUE TITLE
Amplify Publish directing API endpoints to localhost

### ISSUE THREAD

**Issue by dlamon1** [aws-amplify/amplify-cli#5617]
**Describe the bug**
'Mixed Content' error when loading hosted site after running 'amplify push' after working with 'amplify mock' and running locally with 'npm start'

<img width="613" alt="Screen Shot 2020-10-17 at 10 55 02 AM" src="https://user-images.githubusercontent.com/43188519/96347529-d4a21500-1067-11eb-8a26-67a7cdb07b61.png">

**Amplify CLI Version**
4.29.4

**To Reproduce**
run 'amplify mock';
run 'npm start';
run 'amplify publish';
load aws hosted URL;

**Expected behavior**
Expected behavior is to have endpoints directed to the aws hosted endpoints and not the localhost. 

**Screenshots**
See above and below

**Desktop (please complete the following information):**
 - OS: Mac 10.15.16
 - Node Version v12.18.4
- This is a React app
- Using vscode

**Additional context**
Additionally, I have previously posted this issue in the Amplify discord channel, the reply was to check aws-exports.js to confirm where the endpoint was assigned. On that occasion the endpoint was set to the local host, posting my hosted endpoint there solved the issue at that point. Though, I have just run through the steps again and the was-exports.js is directed to the hosted endpoint and I'm still getting the 'Mixed Content' error. 

Searching for project folder the localhost url returns the following instances: 

<img width="1400" alt="Screen Shot 2020-10-17 at 11 10 01 AM" src="https://user-images.githubusercontent.com/43188519/96347747-58103600-1069-11eb-8e53-1754733744cc.png">

My temporary fix has been
delete node_modules folder
run 'amplify init'
run 'amplify publish'

**Comment by UnleashedMind** [comment]
You need to quit the current local mock session before you run `amplify push`, `ctrl+C` will do.
When you start a mock session,[ the frontend config ](https://docs.amplify.aws/cli/usage/mock#config-files )files are changed by the CLI to point to the locally mocked resource, if you run `amplify push` while you are still in a mock session, the frontend config file will be uploaded to your hosting bucket, causing the error you see.

**Comment by UnleashedMind** [comment]
@dlamon1 since you put a thumb up I'm going to assume the question is answered. 
I'm closing the issue, feel free to open a new issue if you are still blocked.
