### ISSUE TITLE
Add default support for Ember.js to amplify-cli

### ISSUE THREAD

**Issue by officeguy** [aws-amplify/amplify-cli#562]
**Is your feature request related to a problem? Please describe.**
Ember.js framework is not as fully supported out of the box, compared to other frameworks such as react, angular etc.  

**Describe the solution you'd like**
I'd like the Ember.js framework to be included in the amplify-cli with first class support so that it can be selected in the same way other frameworks are, such as react, angular etc. Additionally I'd like higher level components for Ember to be included, such as UI components. ref https://aws-amplify.github.io/docs/js/ui
The ember cli is staying around for the long haul and has a strong 'sensible default' philosophy, which seems a good match for the goals of the amplify-cli. They'd be great to promote together within the Ember+AWS community.  

**Describe alternatives you've considered**
The alternative is to craft it oneself, based on great articles like this one from Michael. https://itnext.io/adding-aws-amplify-to-an-ember-js-application-72683167c476 .  This is viable but it would be faster and easier for devs to have support built in. 

**Additional context**
![image](https://user-images.githubusercontent.com/4327368/49666138-f3264500-fabb-11e8-9f38-aa96e08c5ac9.png)
refs
- awswishlist request : https://twitter.com/AWSSupport/status/1070974815299952640
- mention of roadmap item : https://twitter.com/mlabieniec/status/1071080380223021056

**Comment by yuth** [comment]
Thank you for making this feature request. We will add this to our backlog.
