### ISSUE TITLE
Should Lambda triggers created via the CLI be assigned to a CloudWatch logs group?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#5620]
**Describe the bug**

Generate two Lambda trigger functions via the CLI and neither is available in CloudWatch log viewer as other functions are. Shouldn't it create whatever links it needs so I can log what its doing?

**Amplify CLI Version**

4.30

**To Reproduce**

![image](https://user-images.githubusercontent.com/1674590/96376781-d8718c80-1178-11eb-883f-fae15ca6c3a6.png)

![image](https://user-images.githubusercontent.com/1674590/96376792-eb845c80-1178-11eb-8598-671c44e9e443.png)

**Expected behavior**

Other functions I've added have logging available so I would expect this to do the same. Only reason I can think it might not is that it might generate a lot of logs maybe compare to some of the other types of trigger?

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v12.18.4

**Additional context**

**Comment by PeteDuncanson** [comment]
Did some more digging around on this. Seems if I run a test on the Lambda (with the default test event generated via the Lambda UI) then my function will appear listed in the log group and I can click it, I assume that as it hadn't run there was nothing to log? Now I've run it and its got something to log it can show it. However when I click on it I still get the same error about the log group not existing?

![image](https://user-images.githubusercontent.com/1674590/96377789-d52dcf00-117f-11eb-9ec5-912fb37d3282.png)

Could be that its a Amplify Console issue rather than Amplify CLI but worth you folks having an look at it to be sure as I'm just guessing :)

**Comment by UnleashedMind** [comment]
It's exactly what you have found out, if the functions are not invoked yet, there is no log for them, so you won't be able to find any record in the CloudWatch.

**Comment by PeteDuncanson** [comment]
Well that is good to know. Thanks for the confirmation :)
