### ISSUE TITLE
Dearest amplify-cli

### ISSUE THREAD

**Issue by kenbankspeng** [aws-amplify/amplify-cli#5623]
Dearest amplify-cli,

With all due respects to the complexities you are dealing with, and also to the tremendous potential of amplify-cli, and having every desire for you to succeed, I can only describe the present state of @aws-amplify/cli (I'm currently using 4.30.0, but also true of earlier versions) as brittle and frustratingly difficult to use even in the basics.

My plea to your dev managers, backed by my 'too many' years of experience, is that you stop development of any new features and push hard to stabilize the core of your product. 

Here are just some of the daily things being dealt with lately:

- regularly pushing updates to the environments, even though there are really no effective updates, only because the cli is tracking environment builds in code that must be in configuration management.
- after merging in changes made in another branch, a push will hit one of a multitude of errors, but I return to the branch and then push, it sometimes work, after which I can return to the merge and successfully push.
- attempting to change the keys of a table, I need to remove the table and re-add it. But it errors on a dependency. Fair enough. I remove the dependencies using the cli only to find out that the corresponding 'dependsOn' weren't actually removed. Manually removing the dependencies from the 2 json files, only to have the error: Resource xxxxx must be in ARN format or "\*". I presently am unable to change the table.
- unable to add a new table because of the error: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename xxxxxxxx and update the stack again.
- errors on re-creating environments because I didn't manually remove the S3 buckets
- having to manually set CORS on the API Gateway for 4xx/5xx errors
- a lambda layer losses synchronization with the versioning
- a lambda layer in one environment links to code in another environment, a configuration management nightmare
...

Having also invested multiple years into environments managed by amplify-cli, I do sincerely desire your every success.

Sincerely, 
Ken Banks

**Comment by litwicki** [comment]
@kenbankspeng dev manager here. First off I want you to know we take this kind of feedback very seriously, and we want to always improve. Thank you for taking the time to share your experiences, and sorry to hear of your frustrations.

Second, I want you to know we are actively working on improvements concerning your third point. Regarding your other comments I would love to have a call/chat with you at your earliest convenience with my colleague @renebrandel. Feel free to ping us at amplify-cli@amazon.com and we'll make the time.

**Comment by kenbankspeng** [comment]
@litwicki Thanks Jake for the fast response, and that on a Sunday. Closing this item as it is really just a message. Very happy to chat.
