### ISSUE TITLE
Function command should prompt for extra-amplify permissions configuration.

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#5626]
**Is your feature request related to a problem? Please describe.**
While the amplify cli lets developers easily add permissions to other inter-amplify resources to the cloudformation template for a function, a lot of developers seem to struggle with adding extra-amplify resource permissions. A nice feature would be the ability to define these either at the command line or using a simplified JSON syntax to list the permissions and resources that leaves out extra cloudformation syntax, and has built in common substitutions. (e.g. API, ENV, etc.).

**Describe the solution you'd like**
I think a simple version would be to ask at the CLI and have the user type in the resource string and permission strings. A more advanced method would let us define a simplified json format that lives in the root and is marshalled into the cloudformation template at push time. The JSON should only manage the permissions specified, and should track differences to remove permissions when permissions are removed from the JSON.

**Describe alternatives you've considered**
Right now I manually add permissions in the cloudformation template. Which is fine, but I see a lot folks seem to struggle with it, for example setting up Secrets Manager.

**Additional context**
I think this would help make amplify more usable and it is likely the entire toolset to build this exists in the system already given the infrastructure for adding inter-amplify permissions.

Thank you!

**Comment by josefaidt** [comment]
Closing as this issue has since been resolved by the introduction of the `custom-policies.json` file for functions with the ability to use placeholder `${env}` values to reference different resources. https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function
