### ISSUE TITLE
TypeError: updateWalkthrough is not a function

### ISSUE THREAD

**Issue by bmvdeveloper** [aws-amplify/amplify-cli#5640]
**Describe the bug**
Running `amplify update analytics` and selecting `Amazon Pinpoint` results in:
```
TypeError: updateWalkthrough is not a function
    at Proxy.updateResource
/.config/yarn/global/node_modules/amplify-category-analytics/provider-utils/awscloudformation/index.js:25:10
```

**Expected behavior**
Be able to update analytics.

**Screenshots**
<img width="468" alt="Screen Shot 2020-10-20 at 1 05 50 AM" src="https://user-images.githubusercontent.com/53025018/96558412-7b590200-1270-11eb-8d7b-3c3368fc6e98.png">

**Amplify CLI Version**
v4.30.0

**To Reproduce**
run `amplify update analytics`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.9.0

**Comment by kaustavghosh06** [comment]
@bmvdeveloper With the latest version of the CLI, we don't throw this anymore and have updated the flow to the following:

```
kaustavg@3c22fb229ff6 testcreate % amplify update analytics
? Please select from one of the below mentioned services: Amazon Pinpoint
Update functionality not available for this service
```
