### ISSUE TITLE
amplify push does not preserve annotations/comments within schema.graphql

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#5645]
**Describe the bug**
I define my schema, I add supportive documentation, because a good GraphQL API includes type and field descriptions which can be viewed through GraphiQL for example.

**Amplify CLI Version**
4.29.3

**To Reproduce**
Create amplify project
Create GraphQL API
Use `Single object with fields (e.g., “Todo” with ID, name, description)`

Then, annotate the example schema.
```
# this is a comment
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

Finally, run `amplify push`

Visit the API through GraphiQL or AppSync console, navigate the "docs". Notice how the `Todo` type doesn't have the expected description

**Expected behavior**
I want the type and field definitions/documentation to persist when pushing the schema via amplify cli

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version. v12.16.3

**Comment by undefobj** [comment]
Hi @alexboulay this is actually a feature that the AppSync team has in their backlog as the storage of the schema once pushed to the service is outside the control of the Amplify CLI. Please open an issue in the AppSync Community Feedback if you would like to make this more visible to the service team: https://github.com/aws/aws-appsync-community
