### ISSUE TITLE
How to give full S3 Storage access to an "Admin" Cognito Group

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#5652]
** Which Category is your question related to? **
Storage, Auth
** What AWS Services are you utilizing? **
Amplify, Appsync, S3, Cognito
** Provide additional details e.g. code snippets **
I have Auth set up in my React Amplify app so that Cognito users in an "Admin" Cognito Group have full access, while all other users have limited access.

I need a way to allow all users to upload documents to S3 storage, and provide access controls based on Cognito Groups, particularly one "Admin" Cognito group having access to all files. Right now only the Logged In user that uploaded a file can successfully Storage.get() it from Storage. 

I've been playing around with Bucket policies and IAM roles, but haven't been able to figure it out. I am sure there is a simple solution! Any help would be appreciated.

**Comment by undefobj** [comment]
This should be possible by using the User Groups functionality in Amplify CLI and then granting permissions in the Storage category itself: https://docs.amplify.aws/cli/auth/groups#group-access-controls
The CLI workflow will allow you to leverage CRUD style permissions for your Admin group or alternatively you can override the IAM policy for that group directly with the `user-pool-group-precedence.json` file.

**Comment by lahdo** [comment]
Please reopen.

**Comment by rafaelsorto** [comment]
This is the same thing that I'm looking for, it seems with the current logic of public, protected, private, there is no way to have admins overriding the private access level of another user.
