### ISSUE TITLE
What is the difference between the AppSync @key and the $filter option in each query

### ISSUE THREAD

**Issue by jesuscovam** [aws-amplify/amplify-cli#5660]
What is the difference between these options, my intention is to choose the right one for each case, thanks for your time!

My context: I'm building a input to search products

**Which Category is your question related to?**
App-Sync

**Amplify CLI Version** 
4.30.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
![Screen Shot 2020-10-21 at 9 18 16 PM](https://user-images.githubusercontent.com/46403187/96816435-fe9a6500-13e2-11eb-9854-99cf089061f5.png)

**Comment by undefobj** [comment]
`@key` will create indexes in the backing database (DynamoDB) and perform queries over those indexes. This is an optimized pattern, but requires you to have a bit more understanding of your data model up front. 

Filters run over the returned data after executing a query (or a scan in list operations). They can help "filter down" your result set at the server before returning it to the client.

**Comment by jesuscovam** [comment]
@undefobj thank you!
