### ISSUE TITLE
Can't create a lambda function with python runtime

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#5662]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Trying to `amplify function add` a lambda with a python run time, and the moment I select the option for python, the following error is thrown:

```console
Error executing python3
You must have python >= 3.8 installed and available on your PATH as "python3". It can be installed from https://www.python.org/downloads
```
I've installed python 3.9 on the Windows 10 system and have updated the PATH to include both `...\Python39` and ...\Python39\Scripts`

The Python installer creates a `python.exe` executable, not `python3.exe`.

I'm using PowerShell, not WSL.

Entering `python3` on the PowerShell does start python correctly.

I've tried making a copy of `python.exe` and naming it `python3.exe`, but to no avail.

I've also tried to create some aliases, like the below, but none seem to help Amplify find python:
```console
Set-Alias python3.exe "D:\Users\Kim\AppData\Local\Programs\Python\Python39\python3.exe"
Set-Alias python3 "D:\Users\Kim\AppData\Local\Programs\Python\Python39\python3.exe"
```
I'm feeling like I'm doing something dumb here, but I don't know what.

**Amplify CLI Version**
4.30.0

**To Reproduce**
1.  run `amplify function add`
2.  select python as the runtime

**Expected behavior**
Should create a python function

**Screenshots**
![image](https://user-images.githubusercontent.com/26792769/96858769-e9791100-148a-11eb-9642-6ff286a00a39.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: v12.18.3

**Additional context**
Sorry if this is not a bug, and just me being stupid, but any input that sets me straight would be appreciated.

**Comment by renebrandel** [comment]
Looking at the code...
```
  try {
    pyVersionStr = await execAsStringPromise('python3 --version');
    const pyVersion = coerce(pyVersionStr);
    if (!pyVersion || lt(pyVersion, minPyVersion)) {
      hasDeps = false;
      errMsg = `python3 found but version ${pyVersionStr} is less than the minimum required version.\n${pythonErrMsg}`;
    }
  } catch (err) {
    hasDeps = false;
    errMsg = `Error executing python3\n${pythonErrMsg}`;
  }
```
Do you mind running `python3 --version` maybe with 3.9 they've changed the output format, so we can't just use `semver`.

**Comment by renebrandel** [comment]
cc @kimfucious

**Comment by kimfucious** [comment]
Hi @renebrandel ,

Thanks for the follow up.

Here's the output from `python3 --version`.

```console
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\kim> python3 --version
Python 3.9.0
PS C:\Users\kim>
```

**Comment by attilah** [comment]
@kimfucious since we check 2 things, `pipenv` is that possible that the pipenv check itself fails with this error message?

**Comment by kimfucious** [comment]
Hi @attilah, thanks for the follow up.

I actually don't need Python 3.9, so I'm going to revert to v3.8 and see if that fixes things.

Sorry to waste anyone's time on this, but perhaps it's something to get the CLI ready for folks moving to 3.9.

Give me a day or two, and I'll let you know how 3.8 goes.

**Comment by attilah** [comment]
@kimfucious sounds good, in the meantime since it can affect other customers as well, since we have no control over how python was installed, we'll probably implement a fallback mechanism for python binary selection by probing `python3` and `python` as well.

**Comment by kimfucious** [comment]
Hi @attilah,

Python v 3.8.6 installed from [here](https://www.python.org/downloads/windows/), also install as `python.exe`, not `python3.exe`.

Installing Python from the MS app store gets `python3` working from powershell and amplify can find it; however, running `pip3 install --user pipenv` does not get an amplify recognizeable install, as--to the best of my knowledge--Python 3 requires an `-m` parameter to run `pipenv`, like:
```shell
PS> python3 -m pipenv --version
pipenv, version 2020.8.13
```
Frankly, I'm not used to running Python on Windows, so I could be doing something dumb.  I'd use WSL, which would be easier and most likely resolve this issue, but I need this particular app to be built and running in PowerShell for reasons that aren't pertinent to this issue.

I have read all of [this](https://docs.python.org/3/using/windows.html), but nothing I've tried helps much toward getting amplify to allow me to create a Python function.

I can't be the only one doing this, so I'm hopeful that I'll find a solution soon.  If I do, I'll post it here.

Thanks for any further advice that you may have.

**Comment by attilah** [comment]
@kimfucious I think you have some local issue with your python setup for sure, I made the fix to make sure Amplify CLI can use `python` binary as a fallback, if `python3` was not found in the path. See #5744 PR for details.

**Comment by kimfucious** [comment]
@attilah At what version of the CLI should I try this.  

I've got an issue where I can't go to the newest version to to other issues.

Thanks.

**Comment by attilah** [comment]
It will be in included in the next release.
