### ISSUE TITLE
UnhandledPromiseRejectionWarning: NoSuchBucket: The specified bucket does not exist

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#5665]
**Describe the bug**

When I run `amplify init` on a cloned project, I should not see ugly unhandled promise rejections. I would also expect the command to run to completion or error, not hang.

**Amplify CLI Version**
v4.28

**To Reproduce**

1. git clone https://github.com/sw-yx/demo-amplify-storage-file-upload and npm install
	- note that this repo has the default `gitignore` given by amplify
2. amplify init

**Expected behavior**

a clean install experience

**Screenshots**

Note that this "Initializing your environment: dev" command has been hanging for > 15 minutes.

![image](https://user-images.githubusercontent.com/6764957/96892941-c10a0a80-14bc-11eb-8c31-61c33b6f0a6e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] mac
 - Node Version 12.18

**Comment by sw-yx** [comment]
related issue - since the "initializing your environment" hanging is bothering me - https://github.com/aws-amplify/amplify-cli/issues/5666

**Comment by kaustavghosh06** [comment]
@sw-yx Are you sure the S3 deployment bucket exists in your AWS account configured locally with your profile? You can find the bucket name in `<project-root>/amplify/backend/team-provider-info.json` file and then you can go to your AWS S3 Console to check if the bucket exists. 
On a side-node the Ctrl+C issue is weird and we should look into it and track in #5666 . cc @renebrandel @litwicki

**Comment by sw-yx** [comment]
@kaustavghosh06 no, i am sure that i have deleted that bucket. thats not the point i'm raising here, i am suggesting that even with the deleted bucket there should not be ugly unhandledpromiserejections in our code, for people who are cloning open source amplify projects this will be a very common experience

**Comment by kaustavghosh06** [comment]
Ah - got it! Yeah, we shouldn't be throwing the stack-trace and have a friendlier error message and catch it as you mentioned. I believe we had some ongoing work on it but I'll check with the team. @ammarkarachi can you please take a look at this as well when looking at #5666 ?

**Comment by sw-yx** [comment]
i saw this again, on CLI v4.32 (latest) https://github.com/aws-amplify/amplify-cli/issues/5770

**Comment by zanio** [comment]
I saw the error as well again

**Comment by irfanbabar15** [comment]
I have deleted the deployment file in S3, now i get this  UnhandledPromiseRejectionWarning: NoSuchBucket: The specified bucket does not exist. is there any solution ?
