### ISSUE TITLE
Respect Ctrl+C during `amplify init` or `amplify push`

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#5666]
**Is your feature request related to a problem? Please describe.**

When I run `amplify init` or `amplify push` and **realize it is hanging** or that i have made a mistake **while it is executing something in the cloud**, a standard CLI workflow is to `ctrl+C` to kill the process and restart. i would like this to actually work.

currently i have to kill the entire terminal process i am working on.

**Describe the solution you'd like**

i dont know what the cause is so i dont know the solution.

**Comment by ammarkarachi** [comment]
@sw-yx What version are you using? we do handle `SIGINT` and exit the process.

**Comment by ammarkarachi** [comment]
![image](https://user-images.githubusercontent.com/56042290/96898388-82386e00-1444-11eb-91fb-eea077e6a6e2.png)

**Comment by sw-yx** [comment]
4.28 - i should clarify that this is specifically during parts where there is a spinner, like "Initializing Environment"

![image](https://user-images.githubusercontent.com/6764957/96900326-8e641000-14c4-11eb-99aa-1292ff0c8747.png)

**Comment by ammarkarachi** [comment]
@sw-yx It's the spinner swallowing the CTRL+C, I will mark this as a bug and figure out a way for the spinner to not swallow the `SIGINT` event.

**Comment by ammarkarachi** [comment]
@sw-yx I tried it with 4.32.0 can you confirm?
![2020-11-03 09 54 01](https://user-images.githubusercontent.com/56042290/98022611-aee07400-1dba-11eb-8822-97d60eac0be3.gif)

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/98027782-214b6580-1e48-11eb-897d-91fe039d0f7c.png)
yes!! thank you!
