### ISSUE TITLE
Timestream as first class Database option

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-cli#5675]
**Is your feature request related to a problem? Please describe.**
Currently I am managing logging type events in DynamoDB. Given the recent TimeSream launch, it would be great if it is supported out of box. Instead of me building an implementation

**Describe the solution you'd like**
TimeStream should be supported as first class DB just like DynamoDB and Aurora

**Describe alternatives you've considered**
Alternative is to use DynamoDB. However for a part of my db where data shape is more like TimeSeries, it would be nice to use TimeStream

**Comment by nikhname** [comment]
@arkllc could you tell us a little bit about your use case for TimeStream logging?

**Comment by arkllc** [comment]
All of my application is built completely on AppSync transform with DynamoDB as backend DB. A part of my application has to monitor the progress of a job and store the progress back into a data store via AppSync data mutation. The subscribers to the mutation will automatically get notified. Before TimeStream I was thinking of storing the time series data of progress (timestamp and %of job complete) on a given job in DynamoDB.  However, Timestream has some great features of tiering and it will also reduce the burden of me doing this with extra coding with DynamoDB Streams. AppSync is a perfect fit here as it can provide low coupling due to a facade behind which I can abstract various purpose-built database types  - Dynamodb and TimeStream. Please let me know if you need further clarification.

**Comment by kaustavghosh06** [comment]
@arkllc This is an interesting use-case for the AppSync service to support. Would you mind opening up this issue in the AppSync community GitHub repo - https://github.com/aws/aws-appsync-community to gauge interest of the AppSync community and the AppSync team? Thank you! Closing the issue on this repo.
