### ISSUE TITLE
Sharing team provider json file

### ISSUE THREAD

**Issue by Junhano** [aws-amplify/amplify-cli#5679]
This is my first time using AWS Amplify
I am facing difficulties sharing backend environments with other developers. The doc says we need to share the same team provider JSON file. Which I did. But when I share the thing and he copy and paste the team provider json file, every time he run amplify console it says app with id not found. I tell him to run amplify push, but it says Unable to upload trigger files to S3, An error occurred during the push operation: Unable to upload trigger files to S3.

Now I am guessing the only problem left is he may not have the access to the backend environment since he doesn't have the accessKey and secret AccessKey as the doc says. But no matter where I look, there isn't a place to tell me how to set up the correct accessKey for the developer. I tried IAM and create a role to give him permission but it doesn't seem to work

Any help is appreciate

**Comment by litwicki** [comment]
Hi @Junhano the `AccessKey` and `SecretKey` are for the individual developer on their own workstation, **not** in the `team-provider` file. Here is a good guide for that: https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/

Also make certain that if you are sharing your team-provider file that your repository is **private**.

**Comment by Junhano** [comment]
thanks.
