### ISSUE TITLE
amplify add hosting not longer works

### ISSUE THREAD

**Issue by abstractalchemist** [aws-amplify/amplify-cli#568]
**Describe the bug**
After starting a new project, if I execute amplify add hosting with Prod, access to my application through CloudFront results in 403.

**To Reproduce**
1. create-react-app testing && cd testing
2. amplify init
3. amplify add hosting ( select Prod for deployment with CloudFront )
4. Right Click on console printed link to https

**Expected behavior**
Expect CloudFront URL to results in opening index.html

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser : chrome

**Comment by jkeys-ecg-nmsu** [comment]
Did you run `amplify publish`?

**Comment by UnleashedMind** [comment]
I was not able to reproduce the issue. 
Please check on the following: 
- run `amplify configure project` and make sure your build command and distribution directory are correctly configured. 
- run `amplify publish` to upload the contents in the distribution folder to the hosting bucket

**Comment by abstractalchemist** [comment]
Sorrty, this is a red herring.  It does in fact work, but I guess I wasn't waiting long enough for the components to essentially get settled.  What in fact happens is after the first ampliy add hosting/amplify publish, the initial call to the CloudFront domain returns a 403.  After some period of time ( anywhere between 15 minutes and half hour or longer ) it seems to settle and I see the application as expected.  It's rather confusing how that works and I thought it was a bug on the configuration side of amplify.

Sorry of the hassle.
