### ISSUE TITLE
Can't add same schema definition after removal and publish 

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#5680]
**Describe the bug**
For removing primary key and add with new primary key I removed mentioned schema 
```
type MasterTechSegment @model(timestamps:null) {
	techSegId: ID!
	techSegCode: String
	techSegDesc: String
}
```
and done amplify publish. After that I added the same schema with slight change to add new primary key as below

```
type MasterTechSegment @model(timestamps:null) @key(fields: ["techSegId"]) {
	techSegId: ID!
	techSegCode: String
	techSegDesc: String
}
```
and done amplify publish. But this time it ended up with following error

```
Resource Name: MasterTechSegment-e2owpdgtivelrlwbcw7hplm7jq (AWS::DynamoDB::Table)
Event Type: create
Reason: Resource creation cancelled


Resource Name: MasterTechSegmentIAMRole (AWS::IAM::Role)
Event Type: create
Reason: MasterTechSegmd853ef-role-e2owpdgtivelrlwbcw7hplm7jq-dev already exists in stack arn:aws:cloudformation:us-east-1:199522889564:stack/amplify-spad-dev-221813-apispad-B7FRPJ5LNHM7-MasterTechSegment-BKVYTVKC4J9/48ae4700-9f81-11ea-9171-0ed24b955b13
```

Please advise me a solution to move forward

**Amplify CLI Version**
4.29.2

**Comment by kaustavghosh06** [comment]
@meetrij Did you remove the @model from the schema -> do an amplify push -> and re-add the @model back and then get the error on amplify->push or did you remove the DDB table directly from the AWS Console?

**Comment by meetrij** [comment]
@kaustavghosh06 I didn't remove the DDB table directly from the AWS console, just removed below mentioned schema type and done amplify publish
```
type MasterTechSegment @model(timestamps:null) {
	techSegId: ID!
	techSegCode: String
	techSegDesc: String
}
```

**Comment by edwardfoyle** [comment]
@meetrij When you removed the @model was there a function or other resource in your project with a dependency on the DynamoDB table associated with the model? If so, there is a known issue where the child stack defining the table gets orphaned when removing the @model which could cause the behavior you're seeing if you add the model back later. See https://github.com/aws-amplify/amplify-cli/issues/5118#issuecomment-770120224 for more details

**Comment by kaustavghosh06** [comment]
Closing due to lack of further communication and response.
