### ISSUE TITLE
Email added as required in userpool even when not selected in amplify add auth prompt

### ISSUE THREAD

**Issue by kennandavison** [aws-amplify/amplify-cli#5681]
Hi, email shows as required even though I didn't select it during the amplify add auth flow. More context: no MFA/no required attributes.

**Comment by kaustavghosh06** [comment]
@kennandavison Which flow did you go through for `amplify add auth` - did you go with the default configurations from the CLI?

**Comment by kennandavison** [comment]
manual configuration

**Comment by kaustavghosh06** [comment]
What was your selection for this response? The email attribute in Cognito was set based on your response for this question in the manual configuration flow.

 What attributes are required for signing up? (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ Address (This attribute is not supported by Facebook, Google, Login With Amazon.)
 ◯ Birthdate (This attribute is not supported by Login With Amazon.)
 ◉ Email
 ◯ Family Name (This attribute is not supported by Login With Amazon.)
 ◯ Middle Name (This attribute is not supported by Google, Login With Amazon.)
 ◯ Gender (This attribute is not supported by Login With Amazon.)
 ◯ Locale (This attribute is not supported by Facebook, Google.)

**Comment by kennandavison** [comment]
Yeah, specifically unchecked that and tried a few times

**Comment by kaustavghosh06** [comment]
Got it. Yes, I was able to reproduce the issue. The following block always exists in the CloudFormation template by default which shouldn't be present if you unselect email in the sign-up attributes question. I'll take that back to me team. cc @edwardfoyle 

```
     Schema: 
        -
          Name: email
          Required: true
          Mutable: true
```

**Comment by Tristan10** [comment]
Any updates on this or suggestions for how to get around it?

**Comment by cheunjm** [comment]
Experiencing same issue here :(

**Comment by edwardfoyle** [comment]
The fix for this has been released. Please install the latest version of Amplify to get the fix.

**Comment by kervonryan** [comment]
@edwardfoyle  i'm still getting this issue. is there a temporary workaround?

**Comment by edwardfoyle** [comment]
@kervonryan Sorry, I didn't realize that the above PR was reverted before a release happened. So the fix for this has not been released. The workaround would be to remove the part of the CFN template that @kaustavghosh06 mentioned above.

I'll reopen this untile we can get the fix re-merged and released

**Comment by Maatrys** [comment]
Hello, I'm facing the same issue. Any idea when the fix will be released ?

**Comment by kaustavghosh06** [comment]
The fix for this is merged and this will be a part of our next release!
