### ISSUE TITLE
"Export is already exported by stack" when removing a GraphQL model a lambda is reliant on

### ISSUE THREAD

**Issue by rossbishop** [aws-amplify/amplify-cli#5686]
**Describe the bug**
Infrastructure is not correctly destroyed in the backend when removing a single model from a GraphQL schema if a lambda is reliant on said model. Commenting out a model in a GraphQL schema and pushing it to the backend with amplify should destroy all existing backend infrastructure associated with said model, but not all of the infrastructure is destroyed if lambda functions are present in the environment that have access to the DynamoDB table belonging to that model. 

When the updated model is then subsequently pushed to amplify, an error is returned in the format "Export with name xxx is already exported by stack yyy". If one looks at the DynamoDB tables in that environment, the table that should have been destroyed with the GraphQL model is still present.

From this point onwards the environment seems to be as good as bust as I can't push any changes to the cloud without running into this error. I have to then destroy the environment entirely and redeploy all of my infrastructure from scratch in a new environment. It's quite possible it's recoverable within configuration files or some other change, but as a new user I'm not yet at the point where I'm knowledgeable enough to recover the environment this way.

**Amplify CLI Version**
4.29.1

**To Reproduce**
1. Initialise and configure an amplify environment
2. Create a GraphQL API with amplify
3. Add a model to the GraphQL schema
4. Create a Lambda function with amplify (in my case I had both a Lambda Trigger and a standard Lambda Function) that has access to both the API and Storage associated with the GraphQL model
5. Push to the cloud
6. Comment out the created GraphQL model in the schema and push to cloud again
7. Observe whether the associated DynamoDB table has been destroyed
8. Make a subtle modification to the GraphQL model, uncomment it and push to the cloud
9. The aforementioned error should manifest informing the user that a resource already exists and is exported by another stack
10. At this point the issue seems to be impossible to rectify via the CLI - if you attempt to update the lambda, you cannot remove the reliance on the missing GraphQL model as it isn't in the list of available resources. Removing the lambda doesn't seem to fix the issue either.

**Expected behavior**
When removing a GraphQL model during an Amplify push to cloud, at the very least there should be a warning in place to tell the user they have other resources that are reliant on the resource they are about to destroy.

Perhaps the most user friendly thing to do, especially for new users like me, would be to remove the access to the resources from the lambda before they are destroyed.

I believe if I removed the Lambda function access to the model first and then removed the GraphQL model this may not be an issue. I haven't yet had an opportunity to test this as I now need to rebuild my infrastructure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 12.18.2

**Additional context**
I've had this issue twice, the first time I wasn't sure what caused it, the second time I decided to investigate it further - I'm not 100% sure if I've narrowed it right down to the exact cause but it seems to be to do at the very least with Lambda access to DynamoDB tables that are associated with GraphQL models. 

@undefobj suggested I create the issue and raise it to the attention of @renebrandel.

Many apologies if there is information I have missed - this is my first bug report on GitHub :)

Thanks

**Comment by kaustavghosh06** [comment]
@rossbishop Thanks for bringing this up. Yes, the dependency block is between the @model and the function resource and as you've mentioned if you remove a @model and the the table name is exported for another dependent Lambda function to use - you'll encounter this deletion issue. Are you currently stuck or were you able to run `amplify update function` -> remove access for the removed @model and able to re-deploy?

**Comment by rossbishop** [comment]
Hi @kaustavghosh06 - what I alluded to in my post is that I wasn't initially able to actually remove access for the removed @model via `amplify update function`. 

I've just uncommented the @model, run `amplify codegen` and then been able to remove it that way. I no longer see the references to the tables in the environment variables at the top of the lambda functions. 

However, upon trying to push the next time I then ran into an issue related to the auth resource which complained of `...PostConfirmationArn ...PostConfirmationName do not exist in the template`. Not quite sure where this was coming from, so I backed up my lambda trigger code and removed the trigger from the auth resource via `amplify update auth`.

I then tried pushing again and returned to the aforementioned "export" issue with the exact same resources.

I figured perhaps this was because I was trying to push the modified @model to the cloud when the original table and perhaps some other infrastructure still hadn't been removed remotely. 

I tried commenting out the @model again and pushing again with the lambda reliance on said @model removed but now I'm getting an S3 error `The bucket you are attempting to access must be addressed using the specified endpoint. Please 
send all future requests to this endpoint.` Certainly getting quite confused now. The running theme with the CLI output is that I get exceedingly vague errors that don't particularly describe what the actual issue is.

Clutching at straws I thought perhaps the attempted access of the environment var for the table that now doesn't exist was causing the issue, but I was pretty sure there was no verification of Lambda functionality in an `amplify push` and that would appear correct as commenting the contents of my remaining lambda out also did not address the issue.

Perhaps the S3 error is relating to the fact for some reason there isn't authorisation to destroy the table now? I could remove the table manually in the DynamoDB console but I hesitate to do anything like that as Amplify doesn't seem to be made aware of updates made to infrastructure in the AWS GUI.

A few lines below this initial error I have this error output: `UPDATE_FAILED               api                 AWS::CloudFormation::Stack Sat Oct 24 2020 20:58:13 GMT+0100 (British Summer Time) Embedded stack arn:aws:cloudformation:eu-west-2:xxxxxxxxxxxx:stack/amplify-project-dev-xxxxxx-api-xxxxxxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [RemovedModel]. The following resource(s) failed to update: [AuthRolePolicy01, UnauthRolePolicy01].`

Failed to create the model which already isn't supposed to exist in the pushed cloud infrastructure...?

I've searched my local files and can't seem to find any obvious reference to the removed @model.

I hope this provides a little more context on the weirdness of the issue!

Thanks again

**Comment by akshbhu** [comment]
Closing this in favour of  #6639
