### ISSUE TITLE
Attach datasource to existing Appsync

### ISSUE THREAD

**Issue by getmyrolemodels** [aws-amplify/amplify-cli#5687]
Datasource in Amplify is a really cool feature, separates the overhead of managing the operations. I have an existing AppSync and I want to use it in my new Amplify project.
Now, by following documentation I was able to add the Appsync endpoint to my project. But I can't leverage the datasource part of Amplify.

Any thoughts on how to achieve this ?

I followed the #574, but it seems support for this is yet to come.

**Comment by jhockett** [comment]
Hi @getmyrolemodels. Have you tried using the Lambda or HTTP data sources we provide? Is there something missing in these data source options?

For more information, checkout the docs on these directives:
https://docs.amplify.aws/cli/graphql-transformer/directives#function

https://docs.amplify.aws/cli/graphql-transformer/directives#http

**Comment by getmyrolemodels** [comment]
> Hi @getmyrolemodels. Have you tried using the Lambda or HTTP data sources we provide? Is there something missing in these data source options?
> 
> For more information, checkout the docs on these directives:
> https://docs.amplify.aws/cli/graphql-transformer/directives#function
> 
> https://docs.amplify.aws/cli/graphql-transformer/directives#http

Sorry not the resolvers, the Datastore. I was referring to the one used in the sync engine here --> https://github.com/mjzone/amplify-datastore-demo

**Comment by akshbhu** [comment]
Hi @getmyrolemodels 

Currently you can only connect datastore to the api projects initialized by Amplify CLI. We have a RFC to configure existing AWS Resources to amplify project.
Closing this issue in favor of #3977
