### ISSUE TITLE
Labels on PR's

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#5688]
Given there are >50 PR's open right now, the majority over 15 days old...it might be helpful to do some triaging/management with labels...which ones are critical? which ones are just complicated or waiting on other functionality? Which ones are new features, fixes, security?

**Comment by jhockett** [comment]
Thanks for your feedback @GeorgeBellTMH. We are actively looking into this. We've also prioritized catching up with a number of stale PRs this week.

**Comment by cjihrig** [comment]
I'm going to close this out, but this work is ongoing!
