### ISSUE TITLE
Provide support of other languages rather than VTL in the fields resolvers

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#569]
**Is your feature request related to a problem? Please describe.**
Many developers hesitate to use AWS AppSync because of the learning curve of VTL

**Describe the solution you'd like**
Provide a way for developers to use programing language they are acquainted with in the fields resolvers. In my case, it is Javascript.

**Comment by lennybr** [comment]
You may be able to accomplish this by using a [Lambda Resolver](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html) where you can use any language supported by Lambda (Java, Go, PowerShell, Node.js, C#, Python, and Ruby code out of the box).

FWIW I recently learned VTL and it was much quicker than expected, especially if you are already familiar with Javascript in your case.

**Comment by YikSanChan** [comment]
@mikeparisstuff May I get an update on ongoing progress for the alternative options?

**Comment by onhate** [comment]
IMHO latest amplify versions have abstracted so many basic things and yet it allows easy extension by lambdas which open worlds of possibilities, VTL is a very good option for the problem it solves, it is nice to know it and understand if eventually you need to extend it, and hope you don't need to.

**Comment by sakhmedbayev** [comment]
Yes, we can close it
