### ISSUE TITLE
read and write user attributes

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5692]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I'm reading the [Managing user attributes](https://docs.amplify.aws/guides/authentication/managing-user-attributes/q/platform/js) of the doc.

I'm wondering why one must specify **read attributes** and **write attributes** explicitly?
It's a hassle to run the update command every time once I want to add some additional **read attributes** and **write attributes**, the update command goes through ***ALL*** the steps about `auth` which take times.

I know nothing about the Cognito service, is this a restriction related to Cognito?

By the way, the doc says you can use the `update auth` command, but shouldn't it be `amplify auth update`?  is that a typo?

**Comment by jhockett** [comment]
Hi @yaquawa. Resource permissions within Amplify need to be explicitly granted. It's designed this way to encourage best practices. Any given user should have the minimum permissions necessary to ensure the best security posture.

> By the way, the doc says you can use the update auth command, but shouldn't it be amplify auth update? is that a typo?

You can use both `amplify update <category>` and `amplify <category> update`. This similarly works for `add`, `remove`, etc. The exception is env related commands. They must start with `amplify env <env-command>`.
