### ISSUE TITLE
How does the amplify pull command works?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5693]
> The `amplify pull` command operates similar to a git pull, fetching upstream backend environment definition changes from the cloud and updating the local environment to match that definition. The command is particularly helpful in team scenarios when multiple team members are editing the same backend, pulling a backend into a new project, or when connecting to multiple frontend projects that share the same Amplify backend environment.

The above is what I could find in the docs. 

Does that mean if I have edited some settings via browser or cli, then run `amplify pull`, all changes I made will be synced into my local config files in the `amplify` directory? How is it different from `git pull`?

**Amplify CLI Version** 

4.30.0

**Comment by UnleashedMind** [comment]
You will notice that Amplify CLI has created the `<project-root>/amplify/#current-cloud-backend` folder and the `<project-root>/amplify/backend` folder after you execute `amplify init` on your project.

If you are working in a team environment, let's say your teammate developed the GraphQL API for the project, and he ran `amplify push` to push his local development to the cloud. 

On your local development machine, you can run 
- `amplify pull` to get all of his latest pushed backend development into the `<project-root>/amplify/#current-cloud-backend` folder. But your local `<project-root>/amplify/backend` folder will not be changed. If you run `amplify status`, you will see what will be created/changed for the different categories in your backend if you run `amplify push`.
- `amplify pull --restore` to get all of his latest pushed backend development into the `<project-root>/amplify/#current-cloud-backend` folder and then overwrite the `<project-root>/amplify/backend` folder with the latest backend development, your local backend development will be lost. If you run `amplify status`, you will see all the categories are in "No Change" status.
