### ISSUE TITLE
amplify env checkout never completes (spins forever)

### ISSUE THREAD

**Issue by ahtokca** [aws-amplify/amplify-cli#5695]
**Describe the bug**
It looks like something happened to `env checkout` command. I can't checkout environment using any version after 4.28.2.
It just never completes and shows no errors. 

**Amplify CLI Version**
4.29.x, 4.30.x, 4.31.x,... 4.39.x

**To Reproduce**
when ever I run
```
amplify env checkout ${envName} --providers '{ "awscloudformation": {"configLevel": "project", "useProfile": true, "profileName": "${profileName}"} }'
```
it spins with "Initializing your environment: {...}" forever

**Expected behavior**
Environment get checked out

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.0.0

**Comment by jhockett** [comment]
Hi @ahtokca, what categories are you using?

**Comment by ahtokca** [comment]
> Hi @ahtokca, what categories are you using?

Thanks for quick reply. I'm using api, auth, function, storage

**Comment by jhockett** [comment]
I haven't been able to reproduce this yet @ahtokca.

Are you using Lambda layers? 

Have you modified the `team-provider-info.json` file at all? It can be found at `<your-project-root>/amplify/team-provider-info.json`.

**Comment by ahtokca** [comment]
> I haven't been able to reproduce this yet @ahtokca.
> 
> Are you using Lambda layers?
> 
> Have you modified the `team-provider-info.json` file at all? It can be found at `<your-project-root>/amplify/team-provider-info.json`.

What do I need to modify there?

the issue still present even with 4.32.1

**Comment by jhockett** [comment]
@ahtokca you don't need to modify `team-provider-info.json`. I was checking to make sure that the file was NOT edited.

**Comment by ahtokca** [comment]
> Are you using Lambda layers?
Nope. auth, storage, api, plain lambdas

Is there any way to enable tracing? I suspect there is a swallowed exception prevents the tool to complete and makes it waiting for ever

**Comment by jhockett** [comment]
> Is there any way to enable tracing? I suspect there is a swallowed exception prevents the tool to complete and makes it waiting for ever

There is not unfortunately.

**Comment by ahtokca** [comment]
4.39.x no luck. any way I can start from scratch ?

**Comment by edwardfoyle** [comment]
You can try creating a new env from one that you are able to check out.

Does going back to Amplify v 4.28.2 still allow you to checkout the "broken" environment?

**Comment by ahtokca** [comment]
> Does going back to Amplify v 4.28.2 still allow you to checkout the "broken" environment?

Yes. 4.28.2 still works ok. I have to rollback  team-provider-info.json though.

**Comment by kaustavghosh06** [comment]
@ahtokca Could you plese try again with the latest version of the CLI and see if the issue still exists?

**Comment by ahtokca** [comment]
With node 15.7 and amplify-cli 4.41.2 I managed to checkout & push
