### ISSUE TITLE
Lambda function: Adding permissions for SDK (AWS.DynamoDB) to read/update a Table

### ISSUE THREAD

**Issue by christodupreez** [aws-amplify/amplify-cli#5697]
**Which Category is your question related to?**

Function
Api

**Amplify CLI Version** 

4.29.3

**Provide additional details e.g. code snippets**

I have previously created a Function/REST. All good. Now I want to read/create/update a DynamoDB Table in my Lambda function using the AWS SDK (AWS.DynamoDB).

**Question:** How would I add permissions to the Lambda function using Amplify CLI and not having to add it manually?

```
const AWS = require('aws-sdk');
AWS.config.update({ region: 'eu-west-2' });
const ddb = new AWS.DynamoDB({ apiVersion: '2012-08-10' });
const cognitoTableName = 'User-jhcgzjhxc-dev';

const params = {
    TableName: cognitoTableName,
    Item: {
        'id': { S: userId },
        'es_profile': { S: JSON.stringify(profile.Clients[0]) }
    }
};

ddb.putItem(params, function (err, data) {
    if (err) {
        console.log("Error", err);
    }
    else {
        console.log("Success", data);
    }
});

```

The project already uses AppSync / GraphQL, not sure if this can help...

**Comment by jhockett** [comment]
Hi @christodupreez. Use `amplify update function` and after choosing the function you want to edit, answer `Yes` to `Do you want to update the Lambda function permissions to access other resources in this project? (Y/n)`.

For more information, see here: https://docs.amplify.aws/cli/function

Let me know if that helps!
