### ISSUE TITLE
Issue installing via NPM 

### ISSUE THREAD

**Issue by ludwigm** [aws-amplify/amplify-cli#57]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

```
npm install -g @aws-amplify/cli

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/generator'
npm ERR! notarget

```

**Steps to reproduce the issue:**

```
npm install -g @aws-amplify/cli
```

**What is the expected behavior?**

A installation without errors

**Additional environment details**

Node version: v10.9.0
NPM version: 6.2.0

**Comment by kaustavghosh06** [comment]
Hey. Are you by any chance pointing to a custom NPM server? 

I checked out NPM and @babel/types^7.000 is the latest version available - https://www.npmjs.com/package/@babel/types 

You might want to run the install command again and see if it errors out. I’ve seen sometimes NPM error out weirdly previously(but very rarely) even though the package exists in its repository, but then installs the package correctly when I run the install command the second time.

**Comment by ludwigm** [comment]
Hey,

you suspected right. I am using a Nexus NPM repo in front of it which should proxy remote dependencies. Usually that also works, why it does not work in this case is mysterious. Nevertheless when disabling the loading over the Nexus the installation succeeds. 

Many thanks
