### ISSUE TITLE
Session credentials from file not working

### ISSUE THREAD

**Issue by pethron** [aws-amplify/amplify-cli#5700]
**Describe the bug**
In .aws/config and .aws/credentials I have correctly set up a working default profile with access, secret and session token.
I tried to run `amplify init`:
 1 - in headless mode with configLevel as general
 2 - not in headless mode with profile set as default

The outcome for both commands resulted in a failing the cloudformation creation with:
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId

Credentials in my config file are generated with aws sts get-session-token and are working.
Permission is set to admin level.

**Amplify CLI Version**
4.30.0

**To Reproduce**
This is the script used for headless init (both useProfile and profileName are here to easily switch to configLevel project).
`#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"projectName\":\"headlessamplify\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--codegen $CODEGEN
--yes
`

**Expected behavior**
I expect amplify-cli to pick credentials using the default aws chaining method.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**
I used https://docs.amplify.aws/cli/usage/headless to set up the script file.

**Comment by UnleashedMind** [comment]
In the headless mode, you need to set the configLevel to "project" to make sure the default profile is used: 
`https://docs.amplify.aws/cli/usage/headless#--providers`

Could you share how the default profile is set up in your `.aws/config` and `.aws/credentials` files? You should mask out the actual values of `aws_access_key_id` and `aws_secret_access_key`.

**Comment by pethron** [comment]
Yeah, I know but I still tried all combinations to verify it wasn't working as expected. Here is my configuration:

.aws/config
 `[default]
region=eu-west-1
output=json`

.aws/credentials
 `[default]
aws_access_key_id=ASIA*******
aws_secret_access_key=***
aws_session_token=***`

I even tried all combinations on setting the default profile with [profile default]. That resulted in an error that couldn't resolve the aws metadata endpoint (as expected). I still didn't tried to mock the metadata endpoint (but I guess that this would work with amplify).

**Comment by UnleashedMind** [comment]
did you set up MFA for the user? 
What is the session token's expiration?

**Comment by pethron** [comment]
No MFA set up and token expiration is 1 hour.
Tried both instantly and after waiting 10-20 seconds (but it shouldn't be a problem for session tokens).

**Comment by UnleashedMind** [comment]
We are investigating the issue.
In the meanwhile, to unblock you, please run `amplify configure` to set up the credentials to work with Amplify CLI.

**Comment by kaustavghosh06** [comment]
@pethron Were you able to get around this issue while using MFA?

**Comment by pethron** [comment]
Didn't use MFA at that time, I can try to set up a new test

**Comment by kaustavghosh06** [comment]
@pethron were you able to get around this issue?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
