### ISSUE TITLE
What's the proper syntax for scheduling a lambda with Custom Schedule Expression?

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#5701]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Lambda Functions

**Amplify CLI Version** 
4.26.0

**What AWS Services are you utilizing?**
Functions

I'm trying to setup a schedule on a Lambda using `amplify function update`.

When I select `Custom AWS cron expression`, I'm not sure what to enter.

Should this be:
```console
cron(0 12 * * ? *)
```
or 
```console
"0 12 * * ? *"
```
or 
```console
0 12 * * ? *
```
or what?

It's not clear from the docs what the syntax is for entering this value.

Thanks! 🌮

**Comment by akshbhu** [comment]
Hi @kimfucious 

You can just enter the last expression you mentioned : ``` 0  12  *  *  ?  * ```. We will convert this input to ```"cron(0 12 * * ? *)"```.

**Comment by kimfucious** [comment]
Thanks @akshbhu for the clarification!
