### ISSUE TITLE
Race condition when resolving chained Lambdas in GQL schema

### ISSUE THREAD

**Issue by BracketJohn** [aws-amplify/amplify-cli#5702]
**Describe the bug**

Lambda functions as GQL `Query` resolvers randomly fail when chaining functions.

**Amplify CLI Version**

`4.30.0`

**To Reproduce**

Define a query inside the GQL schema like so:
```qgl
type Query {
  echo(msg: String): String @function(name: "processStringA-${env}") @function(name: "processStringB-${env}")
}
```

Define _both_ functions like this:
```js
exports.handler = async function (event, context) {
    return event.arguments.msg;
};
```

Now use `amplify mock` and the resulting playground to run `echo`:

```gql
query MyQuery {
  echo(msg: "Hello, World")
}
```

Now, frequently, `null` is returned, instead of `Hello, World`. Looking at the terminal we get the following output in these cases:

```
Lambda Data source failed with the following error
Command failed with exit code 1: ~/.nvm/versions/node/v12.11.1/bin/node ~/.nvm/versions/node/v12.11.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js

{"result":"Hello, World","error":null}
```

We see the output, and we see that `error: [{}]`, but we don't get any return in the playground:

```json
{
  "data": {
    "echo": null
  },
  "errors": [
    {}
  ]
}
```

**Expected behavior**

No console output/just logging and the following return:

```json
{
  "data": {
    "echo": "Hello, World"
  },
  "errors": [
    {}
  ]
}
```

**Desktop:**
 - OS: MacOS
 - Node Version: `v12.11.1`

**Additional context**

I suspect that the bug results from a race condition inside `execute.ts`. It occurs when the first lambda function `processStringA` returns and the output is then forwarded to `processStringB`. This is most likely due to the exit code then being `1`, even though amplify expects `0` to continue successfully.

If this is true, https://github.com/aws-amplify/amplify-cli/pull/5608 will already fix this issue.

**Comment by jhockett** [comment]
@BracketJohn looks like #5608 was merged and released. Are you still experiencing any issues in 4.32.0?

**Comment by chucre** [comment]
@jhockett Actually this happens even with #5608 merged. I think it's fixed with #5498. It's very similar. @BracketJohn can you test with the latest `master`?

**Comment by BracketJohn** [comment]
I think #5608 and #5498 are not yet part of the current release 4.32, right? How long til 4.33 releases? If that takes too long, I can try to get around to testing with the alpha releases.

**Comment by jhockett** [comment]
Sorry this issue fell off my radar. @BracketJohn @chucre both #5608 and #5498 have been merged and released. Are you still seeing this in the latest CLI?

**Comment by jgroom33** [comment]
this is possibly related to https://github.com/aws-amplify/amplify-cli/issues/6176
