### ISSUE TITLE
Running `amplify mock api` generates custom resolvers that are causing API changes on `amplify push`

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#5703]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.30.0

**What AWS Services are you utilizing?**
`amplify mock api`

When I create a graphql API, I add my schema and I run `amplify push` all the resolvers are created remotely and the `/backend/api/<myapi>/resolvers` directory stays  empty.

If I then run `amplify mock api`, all resolvers are generated in `/backend/api/<myapi/resolvers`. They stay there when I stop running the mock API. More so, this causes amplify to think that I did a change in the API. And Amplify will update the API when running `amplify push`.

* Why does `amplify mock api` cause an update of the API on running `amplify push`
* Will amplify now use all the resolvers specified in the `/backend/api/<myapi/resolvers` directory and is that dangerous?

**Comment by jhockett** [comment]
Closing this issue as a duplicate in favor of #5579.

For additional updates, see the linked PR: #5685.

**Comment by Nxtra** [comment]
Thanks, had not find that one.
