### ISSUE TITLE
Create S3 Storage with Default Server Side Encryption

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#5708]
**Is your feature request related to a problem? Please describe.**
When amplify cli creates storage category. The S3 bucket by default has no server side encryption and there is no option to default to server side encryption. 

**Describe the solution you'd like**
Offer option to enable server side encryption on s3 buckets or make it default. 

**Describe alternatives you've considered**
Modify cloudformation manually, specify it on individual file level on Storage.put (although instructions are vague and seems complex, see https://docs.amplify.aws/lib/storage/upload/q/platform/js#encrypted-uploads), or set it manually in S3 UI.

**Comment by hisham** [comment]
Doing it on individual file level was simple enough actually: 

```
Storage.put(newFile.name, newFile, {
      level: 'private',
      serverSideEncryption: 'AES256'});
```

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI

**Comment by cyrfer** [comment]
@edwardfoyle will this change the bucket used for cloudformation template DEPLOYMENT?
