### ISSUE TITLE
CORS for subscription 

### ISSUE THREAD

**Issue by getmyrolemodels** [aws-amplify/amplify-cli#5710]
I am working on an app using AWS AppSync. I have enabled the AuthN and AuthZ.

One part I am stuck is at adding CORS filter for Appsync subscriptions.

I have worked on websockets earlier and there too I had this problem. I solved it manually in websockets by filtering the CORS from header during the handshake.

Do we have a provision to invoke a lambda in Appsync when a client is attempting to connect for subscription ?

**Comment by edwardfoyle** [comment]
@getmyrolemodels AppSync doesn't supports this. There's nothing we can do on the CLI side as this is a service limitation. You can reach out to the service team on the AppSync forum: https://forums.aws.amazon.com/forum.jspa?forumID=280
