### ISSUE TITLE
Authorizing API Gateway Using Cognito User Pool Groups :: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by lr001dev** [aws-amplify/amplify-cli#5716]
**Describe the bug**
I'm not sure if this is a bug or a mis understanding on how it works, however, I have setup Api Rest Serverless Express via Amplify. I have added endpoints and restricted access for Authorized, Guests & User Groups. I'm currently trying to hit one of my endpoints using a Cognito Access JWT Token. When I don't provide an Authorization Header in the request the API category seems to create the Authorization Header with a Signature dynamically and I'm able to hit the endpoint which is using IAM Authorization it seems to me. When adding authorization header with Bearer token (cognito access jwt token) I get a 403 No Access Control. I'm not understanding the flow here. On initial setup of the lambda using Amplify CLI I set it up to access other categories in the app such graphql api... When I look at the API Gateway the authorizer is setup as IAM Authorization. Shouldn't my groups authorization automatically be configured when using the CLI? What is the proper workflow to allow cognito groups hit my rest endpoints?

CLI Version  4.38.8

**Comment by jhockett** [comment]
Hi @lr001dev. The JS library docs have a custom authorization code sample here that might be helpful:
https://docs.amplify.aws/lib/restapi/authz/q/platform/js#cognito-user-pools-authorization

For additional information on setup with the CLI:
https://docs.amplify.aws/cli/restapi

**Comment by lr001dev** [comment]
@jhockett Thank you for the reply. Just to verify, the documentation you pointed to me too at the first link I've seen before. Are you saying in order to get create this functionality I also need to create a "custom authorizer"? And if so, to further confirm, this is NOT an automated step that Amplify CLI will execute when setting up Authorization using Cognito Groups with REST API, correct or incorrect?

**Comment by lr001dev** [comment]
@jhockett Just getting an update on the above... Also can you let me know if using IAM Authorization on the API Gateway checks Cognito user groups if we are limiting certain methods based on those groups?

**Comment by kaustavghosh06** [comment]
@lr001dev Currently the Amplify CLI only supports API Gateway authorization with IAM and not Cognito User Pools directly. Having said that we do have Cognito Group support with API Gateway. In that setup we assing an IAM role a Cognito User pool group and associate the corresponding CRUD IAM policies for accessing the API (based on the selections you. made in the add/update api flow). We do not use JWT tokens at the moment for authorization of groups.
