### ISSUE TITLE
How to re-create the infrastructure?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5717]
I just noticed that the "Custom-Attributes" of Cognito can not be removed or changed once I added them. So I decided to store the user attributes in DynamoDB to improving the flexibility. I want to re-create the infrastructure from scratch so I can clear the Custom-Attributes I've added.

will the following command work for me?
```
amplify delete
amplify push
```

By the way, I just found that there is a command `amplify delete`, but can't find any information of this command on the docs... not sure what this command could do for me..

**Amplify CLI Version** 

4.31.1

**Comment by jhockett** [comment]
Hi @yaquawa. There's a small bit of text buried in the [docs](https://docs.amplify.aws/cli/usage/headless#amplify-delete-parameters), but there's definitely room for improvement:

"The amplify delete command deletes all of the resources tied to the current project in the cloud, and removes all of the local files created by the Amplify CLI from the filesystem."

`amplify delete` will delete the entire amplify project both in the cloud and locally, so there's no need to execute `amplify push` afterwards.


If you just want to remove your Cognito resource, you can do:
```
amplify remove auth
amplify push
```
In this case, you do in fact need to execute `amplify push` for the remove to happen in the cloud.

**Comment by yaquawa** [comment]
@jhockett I don't want config the `auth` ***again*** via `amplify add auth` from scratch. 
Will `amplify delete` delete all the "local files" including the config files which made by `amplify add auth` or `amplify auth  update` ?

What I want to achieve is that deleting all the resources on AWS, and re-created one exactly the same as before without running the `amplify add auth` again.

**Comment by kaustavghosh06** [comment]
@yaquawa Have you looked into our environments support? `amplify env add` would allow you to clone you existing infrastructure and then from the new environment you can run `amplify env remove <old-environment>` to get rid of your older environment.

**Comment by yaquawa** [comment]
@kaustavghosh06 Oh, thanks for the point out of `amplify env add`, I'll take a look at it!

**Comment by yaquawa** [comment]
@kaustavghosh06 Got it, thanks!

> Curious to know what the error is for the DELETE_FAILED operation though.

me too, is there any way to see the details of the error?

**Comment by kaustavghosh06** [comment]
@yaquawa In the CloudFormation console, you can go into the events tab for the nested stack and look for the failure event traces.

**Comment by yaquawa** [comment]
Thanks @kaustavghosh06 

it says this:
```
User pool cannot be deleted. It has a domain configured that should be deleted first. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: a74cdxbc-550b-4964-ba01-520a448e7d65; Proxy: null)
```

**Comment by yaquawa** [comment]
I set the "Amazon Cognito domain" under `App integration ---> Domain name` in the Cognito console earlier.
Is that the reason for this error? Curious to know should I run `amplify pull` after I made any changes in the console via browser ?
