### ISSUE TITLE
Throws an error when I am trying to publish my react app

### ISSUE THREAD

**Issue by jomosam** [aws-amplify/amplify-cli#5719]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
It throw an error when I tried to run **amplify publish command**. it returns the following error:- 

_Syntax Error: Unexpected @
An error occurred during the push operation: Syntax Error: Unexpected @_

**Amplify CLI Version**
4.30.0

**To Reproduce**
Run it in the following order 
**amplify push** -- it works fine without any issue.
**amplify publish** --

**Expected behavior**
It should publish my app

**Screenshots**
![image](https://user-images.githubusercontent.com/14156457/97431796-ed041080-1940-11eb-9d16-e64652d31bcb.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Node Version:  v14.13.0
 - NPM Version : 6.14.5

**Comment by UnleashedMind** [comment]
We need more input to investigate the issue.
- Could you show the full screenshot? what's below the red error message line?
- What categories of backend resources have you added into your project,  GraphQL API? hosting? storage? 
- Have you manually edited any of the Amplify CLI artifacts in the `<project-root>/amplify` folder?

**Comment by jomosam** [comment]
Could you show the full screenshot? what's below the red error message line?
![image](https://user-images.githubusercontent.com/14156457/97658764-2ba9e000-1a93-11eb-8c3b-02441fe1ad0d.png)

What categories of backend resources have you added to your project, GraphQL API? hosting? storage?
GraphQL,S3
Have you manually edited any of the Amplify CLI artifacts in the <project-root>/amplify folder?
No, I have not changed anything.

Could you open the <project-root>/amplify/.config/project-config.json file and check the javascript.config field?
what are the SourceDir, DistributionDir, BuildCommand, and StartCommand?
![image](https://user-images.githubusercontent.com/14156457/97659097-15e8ea80-1a94-11eb-9d5e-51dd33f2d950.png)

 can you run the BuildCommand on a terminal console at your project root folder without any problem?
Yes, I am able to run the build command and create an optimized version.
![image](https://user-images.githubusercontent.com/14156457/97659180-5b0d1c80-1a94-11eb-8726-7d6efd0d3f31.png)

**Comment by jomosam** [comment]
Could you show the full screenshot? what's below the red error message line?
![image](https://user-images.githubusercontent.com/14156457/97659407-f2726f80-1a94-11eb-90ed-1aad3a939b90.png)


What categories of backend resources have you added to your project, GraphQL API? hosting? storage?
**_GraphQL,S3_**
Have you manually edited any of the Amplify CLI artifacts in the <project-root>/amplify folder?
**_No, I have not changed anything._**

Could you open the <project-root>/amplify/.config/project-config.json file and check the javascript.config field?
what are the SourceDir, DistributionDir, BuildCommand, and StartCommand?
![image](https://user-images.githubusercontent.com/14156457/97659097-15e8ea80-1a94-11eb-9d5e-51dd33f2d950.png)

 can you run the BuildCommand on a terminal console at your project root folder without any problem?
**_Yes, I am able to run the build command and create an optimized version._**
![image](https://user-images.githubusercontent.com/14156457/97659180-5b0d1c80-1a94-11eb-8726-7d6efd0d3f31.png)

**Comment by jomosam** [comment]
Could you show the full screenshot? what's below the red error message line?

![image](https://user-images.githubusercontent.com/14156457/97659527-36657480-1a95-11eb-8906-80b4521d5624.png)



What categories of backend resources have you added to your project, GraphQL API? hosting? storage?
**_GraphQL,S3_**
Have you manually edited any of the Amplify CLI artifacts in the <project-root>/amplify folder?
**_No, I have not changed anything._**

Could you open the <project-root>/amplify/.config/project-config.json file and check the javascript.config field?
what are the SourceDir, DistributionDir, BuildCommand, and StartCommand?
![image](https://user-images.githubusercontent.com/14156457/97659097-15e8ea80-1a94-11eb-9d5e-51dd33f2d950.png)

 can you run the BuildCommand on a terminal console at your project root folder without any problem?
**_Yes, I am able to run the build command and create an optimized version._**
![image](https://user-images.githubusercontent.com/14156457/97659180-5b0d1c80-1a94-11eb-8726-7d6efd0d3f31.png)

**Comment by UnleashedMind** [comment]
Could you confirm that `amplify push` works at this point? and this error only occurs for `amplify publish`?

**Comment by jomosam** [comment]
Yes, amplify push works without any issue. The only problem is with the amplify publish .

**Comment by jhockett** [comment]
Hi @jomosam. It looks like the error message is cropped. If you don't want to share publicly, can you please email amplify-cli@amazon.com? If so, make the subject title "Github Issue 5719" and paste the error message in the email body.

**Comment by UnleashedMind** [comment]
If both the Build command and `amplify push` are successful, this might be due to a corrupt installation, could you try to remove the current installation and reinstall the Amplify CLI and then try again?

**Comment by jhockett** [comment]
Closing this issue due to lack of response. If you are still running into this issue @jomosam, please comment below and we will re-open.
