### ISSUE TITLE
auth with "Email Verification Link with Redirect" selected not working

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5720]
**Describe the bug**
I was able to sign up a user with the following code
```js
import { Auth } from 'aws-amplify'

Auth.signUp({
  username: email,
  password: password,
  attributes: {
    email: email,
  },
})
```

The email has been sent correctly but,
1. the email body is not the same as what I have configured.
2. the link is 404 not found

here is the email body(a dot + URL):

> . http://verificationbucket-develop.s3-website-ap-northeast-1.amazonaws.com/?data=eyJ1c2VyTmFtZSI6ImEyZTU1NWVhLTVkZTctNGRiOC04ODg3LTAxN2NlMWYzMGQyNiIsInJlZGlyZWN0VXJsIjoiLz91c2VybmFtZT1hMmU1NTVlYS01ZGU3LTRkYjgtODg4Ny0wMTdjZTFmMzBkMjYiLCJyZWdpb24iOiJhcC1ub3J0aGVhc3QtMSIsImNsaWVudElkIjoiN25tYXQ4bDZodWcyaWcyMGFtaWpjY20wNzQifQ==&code=407755

I couldn't find any information about the "Email Verification Link with Redirect". 
Have I missed something else?
What I want to achieve is that after user clicked on the link in the email, the user authenticated automatically and redirect to the "You are authenticated!" page on my site.

**Amplify CLI Version**
4.31.1

**To Reproduce**

```
amplify auth update
...
...
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 ◯ Add Google reCaptcha Challenge
❯ ● Email Verification Link with Redirect
 ◯ Add User to Group
 ◯ Email Domain Filtering (blacklist)
 ◯ Email Domain Filtering (whitelist)
 ◯ Custom Auth Challenge Flow (basic scaffolding - not for production)

amplify auth push
```

**Comment by UnleashedMind** [comment]
This is an known issue for Cognito, and people have figured out a bunch of workaround, for example:
https://medium.com/@jacobjoy/redirect-user-using-amazon-cognito-confirmation-url-d8ccb11bac75

Hope that helps.

**Comment by yaquawa** [comment]
@UnleashedMind Thanks for the links. 
But that's not what I want to know about. I understand I can do the same thing with out amplify, here I'm asking is the "amplify way" to to it. That is the ***"Email Verification Link with Redirect"*** option, which set the trigger by amplify. But I'm meeting the issue, that's why I opened this issue.

**Comment by yaquawa** [comment]
Hi Amplify team,
I want to know if it's possible to make "Email Verification Link with Redirect" option work. 
I have to make a decision for this. If this is a bug and won't be fixed soon, I'll do it manually.
Thanks.

**Comment by UnleashedMind** [comment]
@yaquawa 
This is a dependency issue on Cognito, we won't be able to fix it on the Amplify CLI side. You will need to use some of the workarounds that I listed in the above response.

**Comment by yaquawa** [comment]
@UnleashedMind 
The links you given me has nothing to do with the option "Email Verification Link with Redirect".
Even the docs doesn't has any information for this. Is this option a dead feature?

**Comment by yaquawa** [comment]
Any update on this?

**Comment by yaquawa** [comment]
I found the Environment variables for the lambda function was set to blank, how to fix this?
* EMAILMESSAGE
* EMAILSUBJECT
* REDIRECTURL
* RESOURCENAME

**Comment by yaquawa** [comment]
I tried editing this file:
`amplify/backend/function/myproject2713aa05CustomMessage/function-parameters.json`


The original content of this file was:
(notice that the `triggerEnvs` is a string but not an array.)

```
{
  "trigger": true,
  "modules": [
    "verification-link"
  ],
  "parentResource": "minaoshi2713aa05",
  "functionName": "minaoshi2713aa05CustomMessage",
  "resourceName": "minaoshi2713aa05CustomMessage",
  "parentStack": "auth",
  "triggerEnvs": "[\n  {\n    \"key\": \"RESOURCENAME\",\n    \"value\": \"resourceName\"\n  }\n]",
  "triggerDir": "/Users/wang/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage",
  "triggerTemplate": "CustomMessage.json.ejs",
  "roleName": "minaoshi2713aa05CustomMessage",
  "skipEdit": true,
  "REDIRECTURL": "https://3naoshi.com/",
  "EMAILSUBJECT": "account confirm",
  "EMAILMESSAGE": "click the follwoing links",
  "RESOURCENAME": "resourceName",
  "enableCors": false,
  "triggerEventPath": "CustomMessage.event.json"
}
```

I just changed the `triggerEnvs` to 
```
"triggerEnvs": [
        {
            "key": "RESOURCENAME",
            "value": "resourceName"
        }
    ],
```

the issue gone.

I noticed that if I run a `amplify update auth`, the `amplify/backend/function/myproject2713aa05CustomMessage/function-parameters.json` goes back to the stringified version again... This must be a bug.

**Comment by yaquawa** [comment]
Still hit the same issue... will this be fixed someday?
