### ISSUE TITLE
broken npm update reminder

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#5728]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
The versions don't appear in the npm update reminder.

**Amplify CLI Version**
4.30.0

**To Reproduce**
type `amplify publish` in your terminal.

**Expected behavior**
The versions will appear in the npm update reminder.

**Screenshots**

```bash
$ amplify publish

   ╭──────────────────────────────────────────────────────────╮
   │                                                          │
   │   Update available {currentVersion} → {latestVersion}    │
   │              Run {updateCommand} to update               │
   │                                                          │
   ╰──────────────────────────────────────────────────────────╯
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.16.2

**Comment by edwardfoyle** [comment]
@cyrfer I'm unable to repro that issue on v 4.30.0. We had to rollback v 4.31.0 to v 4.30.0 so it's possible that messed up the upgrade notifier.

**Comment by ericowhadi** [comment]
can you remind me what is the command to run to update amplify? the "updateCommand" broken string

**Comment by cyrfer** [comment]
@ericowhadi `npm i -g @aws-amplify/cli`
