### ISSUE TITLE
Error reporting is not clear

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#5729]
**Describe the bug**
Current error reporting method, after amplify publish, hardly displays exact reason

For example recently I was getting an error messages like

```
Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```
When I checked little up, found error something like some resources failed to update, create etc but can't find exact reason because I have 70+ tables and that much types in schema so after doing amplify publish will look at the end of the terminal and only for the output

Later in a glance found in between the process an error

```
CREATE_FAILED      VarietyPromLine        AWS::CloudFormation::Stack Thu Oct 29 2020 12:21:16 GMT+0530 (India Standard Time) Limit for stack has been exceeded
```

So this is the error and from the end portion I can't go all the way to starting section from VS Code terminal as they are not allowing it.

So it would be better to show error messages at the end

**Comment by jhockett** [comment]
Hi @meetrij. I agree, the CLI should either defer or repeat error messages at the end of the push/publish output. Marking this as an enhancement.

**Comment by josefaidt** [comment]
Closing as this has since been addressed by the release of Amplify 9.x. Today CloudFormation updates will print on a single line, and errors are surfaced at the end of the push attempt.
