### ISSUE TITLE
Error: An error occurred during the push operation: Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by ravishankar82** [aws-amplify/amplify-cli#5737]
After adding a new function using `amplify add function` I have added env variable directly to file `<function_name>-cloudformation-template.json`  file under Resources--> LambdaFunction--> Properties--> Environment. On `amplify push -y` I am getting error:

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

Don't what does exact meaning of **Resource is not in the state stackUpdateComplete**

**Comment by jhockett** [comment]
Hi @ravishankar82. It just means `amplify push` failed to create the resource. 

Can you share the cloudformation template edits you made? 

What version of the CLI are you using? `amplify -v`

**Comment by ravishankar82** [comment]
```
amplify -v
4.31.1
```

**Comment by ravishankar82** [comment]
Closing this issue
