### ISSUE TITLE
Composite sort key

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#5740]
**Which Category is your question related to?**
the key directive and key condition expressions

**Amplify CLI Version** 
4.31.1

**Question**
Given the schema and query from the example in the docs:
```gql
type Item @model
  @key(fields: ["orderId", "status", "createdAt"])
  @key(name: "ByStatus", fields: ["status", "createdAt"], queryField: "itemsByStatus") {
  orderId: ID!
  status: Status!
  createdAt: AWSDateTime!
  name: String!
}
enum Status {
  DELIVERED
  IN_TRANSIT
  PENDING
  UNKNOWN
}
```
and
```gql
query ListInTransitItemsForOrder {
  listItems(orderId:"order1", statusCreatedAt: { beginsWith: { status: IN_TRANSIT, createdAt: "2019" }}) {
    items {
      orderId
      status
      createdAt
      name
    }
  }
}
```
Is it possible to have more separation between the conditions applied to *status* and *createdAt*? Here, they both have the *beginsWith* condition, but could you have different types of conditions for each of the two sort keys? 

If not, then my next question would be: Let's say that *createdAt* is of the type *AWSTimestamp* (seconds since epoch). How would one query for the items with a certain value for *status* and a *createdAt* timestamp above a certain given timestamp?

A solution for this particular case would help me a lot. Right now, my workaround is to use a single sort key and to do a DynamoDB post filter operation on the second key (which is just a normal field, for clarity), but as you know, this is an expensive operation and unnecessarily forces me to use pagination and a lot of roundtrips.

**Comment by akshbhu** [comment]
Hi @avlonder 

When you have more than 2 arguments in the @key directive for e.g```(@key(fields:[a1,a2,a3]))``` , Amplify generates sort key as ```a2#a3``` as a single field and you can use operations on this key. So the separations between conditions isn't possible as it is a single key.
For your case you can create one more GSI with @key(status , createdAt) and you can perform operations as you mentioned above in the second point if you don't want to use filter.

**Comment by avlonder** [comment]
Thanks for the explanation and suggestion @akshbhu, but my particular case is somewhat different from the example in the docs: I'm already using a GSI, but for other reasons than the *status* + *createdAt* matter. So I guess, there's no better solution than filtering and pagination.
