### ISSUE TITLE
Is there a way to get the URL of the ElasticSearchDomain in a Lambda?

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-cli#5748]
**Which Category is your question related to?**
ElasticSearch

I want to access the API from one of the Lambdas and I was trying to see how can I inject the environment variable.

Thanks in advance.

**Comment by akshbhu** [comment]
Hi @ignaciolarranaga 

You can manually inject ESDomain as a variable in the function CFN file under Environment Object and define its value in parameters.json file or import it from api CFN file where ESDomain is defined .
```
            "Environment": {
                "Variables" : 
                    "ESDOMAIN": {
                        "Ref": "esDomain"
                    }
                }
```
After that you can access that variable in your lambda code as ```process.env.ESDOMAIN```.

Let me know if this solves your problem?
