### ISSUE TITLE
Delete removes only Stack, but not Bucket and Roles

### ISSUE THREAD

**Issue by ArmorDarks** [aws-amplify/amplify-cli#575]
**Describe the bug**
Delete command removes only Stack, but not Bucket and Roles

**To Reproduce**
Steps to reproduce the behaviour:

Go through

```
amplify init
```

Create cloud data by using a profile

Then lunch

```
amplify delete
```

**Expected behavior**

To remove everything

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: CLI
 - Version: 0.1.36

**Comment by UnleashedMind** [comment]
Because S3 bucket might have contents and the IAM roles might be used by other applications, so to be safe, the CLI does not delete them. 
I will mark this as a feature request, we will think about how to improve the UX for `amplify delete`.

**Comment by ArmorDarks** [comment]
It would be better if CLI will warn what exactly is going to delete. Then it won't be an issue. Right now you can only wonder what `delete` actually does (as turns out, almost nothing).

**Comment by asalvadore** [comment]
Hi all, any update on this ?

**Comment by kaustavghosh06** [comment]
Closing this in favor of duplicate #89
