### ISSUE TITLE
Function tutorial in documentation not working as intended.

### ISSUE THREAD

**Issue by 9710willy** [aws-amplify/amplify-cli#5752]
**Which Category is your question related to?**
Lambda Layer

**Amplify CLI Version** 
4.31.1

**What AWS Services are you utilizing?**
Lambda

**Provide additional details e.g. code snippets**
Hi all, thank you for your hard work. 
I was following the tutorial outlined in the documentation here: 
https://docs.amplify.aws/guides/functions/appsync-operations-to-lambda-layer/q/platform/js#set-up-your-layer

After running the script to generate graphql queries/mutations/subscriptions, no file is generated inside the graphql directory of the appsyncOperation. My guess is that babel has nothing to transpile because my codegen target is typescript. Do you guys have any additional info/way to fix this issue?

Thank you very much :D

**Comment by edwardfoyle** [comment]
Hi @9710willy I think you will need to add the typescript plugin to your babel config and add `--extensions ".ts"` to the babel command: https://babeljs.io/docs/en/babel-preset-typescript. You can also try out the `--copy-files` flag: https://babeljs.io/docs/en/babel-cli#copy-files
