### ISSUE TITLE
[request] remove wordmark in amplify cli

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#5756]
**Is your feature request related to a problem? Please describe.**

we had an internal discussion and it seems the broad consensus is to remove the amplify wordmark.

![image](https://user-images.githubusercontent.com/6764957/97902042-f72a7280-1d77-11eb-926b-5dd65e1d15bb.png)

cc @sammartinez

**Comment by renebrandel** [comment]
What about something simpler? :D 
```
                           _ _  __       
     /\                   | (_)/ _|      
    /  \   _ __ ___  _ __ | |_| |_ _   _ 
   / /\ \ | '_ ` _ \| '_ \| | |  _| | | |
  / ____ \| | | | | | |_) | | | | | |_| |
 /_/    \_\_| |_| |_| .__/|_|_|_|  \__, |
                    | |             __/ |
                    |_|            |___/ 
```

**Comment by sw-yx** [comment]
sure altho its hard to beat firebase haha
![image](https://user-images.githubusercontent.com/6764957/98039389-970bfd00-1e59-11eb-8462-c186f1999739.png)

**Comment by kaustavghosh06** [comment]
@sw-yx What monitor or terminal settings are you using? Is it the same config as what you took the firebase screenshot as? Checkout my screenshot below from normal terminal settings. Please involve me in the internal discussions :)
<img width="1280" alt="Screen Shot 2020-11-03 at 1 19 19 PM" src="https://user-images.githubusercontent.com/7247658/98041748-4a7fdd80-1dd7-11eb-8ea5-13d1f2f82a68.png">

**Comment by sw-yx** [comment]
i often use my terminal at half screen width, which is especially useful for live demos

**Comment by dabit3** [comment]
If I had to vote, I'd say to make it minimal / clean and remove it entirely.

If not, I do really like Rene's update above as it's much cleaner vs what we have now.

**Comment by ammarkarachi** [comment]
We can set the width in [figlet](https://www.npmjs.com/package/figlet) so that it fits in the terminal

**Comment by sw-yx** [comment]
yes. other options i keep track of:

- https://www.npmjs.com/package/term-size
- https://www.npmjs.com/package/boxen
