### ISSUE TITLE
origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Yishay** [aws-amplify/amplify-cli#5763]
Hi,

I've seen several posts about cors, but none of them answered my issue.
We have Lambda functions served through AWS GW and we're trying to access them using amplify API with a Cognito session:
![image](https://user-images.githubusercontent.com/10543568/97996771-d94d2400-1df0-11eb-8739-895ab3bce8e4.png)

The GW seems to be configured correctly:
![image](https://user-images.githubusercontent.com/10543568/97996418-6c398e80-1df0-11eb-96a8-d426c4e0a4de.png)
![image](https://user-images.githubusercontent.com/10543568/97996459-778cba00-1df0-11eb-9e77-ba6083107733.png)
The Lambda We're currently working with seems to be defined correctly:
![image](https://user-images.githubusercontent.com/10543568/97996543-912e0180-1df0-11eb-9260-0196af45deb7.png)

When using the API with a Cognito session it works correctly and the headers seem to be supporting cors:
![image](https://user-images.githubusercontent.com/10543568/97996994-26c99100-1df1-11eb-9a43-86d2eee4f731.png)
![image](https://user-images.githubusercontent.com/10543568/97997018-2f21cc00-1df1-11eb-8845-bdfaf6341397.png)

But when using it from the FE, we get the above error.
We'll appreciate your help on the subject.

Thanks,
Yishay

**Comment by Yishay** [comment]
[This post](https://stackoverflow.com/questions/64016850/amplify-with-rest-api-gateway-lambda-integration-cors-issues) may be related, but it didn't do the trick in our case.

**Comment by dwamianm** [comment]
@Yishay this probably has nothing to do with the API Gateway config so I would encourage you to avoid changing it manually... I have run into this in two scenarios in the past

1. The default header config that Amplify adds to the lambda function does not always work... so I usually replace their default with the following 

`// Enable CORS for all methods
app.use(function (request, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', '*');
  //intercept the OPTIONS call so we don't double up on calls to the integration
  if ('OPTIONS' === request.method) {
    res.send(200);
  } else {
    next();
  }
});`

2. If your lambda function is throwing an uncaught error, it may report a CORS issue when in fact it isn't best thing to do is check out Cloudfront logs. The logs will almost always give you an indication of what is going on

Hope this helps

**Comment by akshbhu** [comment]
Thanks @dwamianm  for the response. Can you explain when you said:

> The default header config that Amplify adds to the lambda function does not always work...

We would try to change this behavior in future.

@Yishay  Can you try @dwamianm  way to check if this works for you?

**Comment by dwamianm** [comment]
@akshbhu Certainly. 

When amplify generates the boilerplate CORS for a lambda that connect to an API gateway, it _rightfully_ restricts the method and headers to only a few types. The issue is that there are times when a amazon passes through the `amz-` headers usually attached to an authentication from the front-end and since the API gateway is not setup to expect them, it reject the connection and issues a CORS warning. 

This isn't something I think needs to be fixed but more so documented. I think the code snippet above should resolve this for more people.
