### ISSUE TITLE
Auth: cloudformation parameters do not exist in the template

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-cli#5764]
**Which Category is your question related to?**

auth

**Amplify CLI Version** 

4.32.0

I have an Android app with Amplify auth installed. I configured it to be able to sign in to google where I had to supply a web client ID and an Android client ID. The app worked and I was able to sign in with google.

I then tried updating auth to utilize the web ui. Now when I run amplify push, I get this error:

`UPDATE_FAILED      authmyAndApp               AWS::CloudFormation::Stack Tue Nov 03 2020 16:17:09 GMT+0200 (South Africa Standard Time) Parameters: [googleClientId, googleAndroid] do not exist in the template
Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
`
Any help to overcome this problem will be appreciated.

Thanks

**Comment by akshbhu** [comment]
Hi @kannieWeesNie 

From the error it seems ```GoogleCLientId``` and ```googleAndroid``` is missing . Can you check  in ```team-providerinfo``` file if these variables are present?
Also can you tell me categories you added and steps so that I can reproduce this error?

This issue seems related : https://github.com/aws-amplify/amplify-cli/issues/5416#issuecomment-699600478.
Let me know if this works for you?

**Comment by kannieWeesNie** [comment]
hi @akshbhu thanks for the help. Unfortunately I have removed the auth category and then added it again with web ui and it's working. I therefore can't check the _team-providerinfo_ file as it has been overwritten.

I initially set up the app following the Android get started steps and may have left the api and datastore dependencies in my build gradle file by mistake as I had no intention of using either. I then added auth and noticed that it ended up also adding an api. 

I then configured auth for guest sign in as well as google sign in. Everything worked but when I tried to update auth again to use web ui I got the error as mention above.

Unfortunately I cannot tell you the exact steps I followed other than as mentioned above.

**Comment by lexfaraday** [comment]
I have the same issue, here steps to reproduce:

1- amplify function add => create a function and add permissions to auth resource
2- amplify function update => unmark auth permissions
3- amplify push => error UPDATE_FAILED... Parameters: [authMainPoolResourceUserPoolId] do not exist in the template (and this parameters is created automatically by amplify-cli on step 1)

version @aws-amplify/cli@4.32.0

Thanks in advance!!

**Comment by akshbhu** [comment]
Hi @lexfaraday 

Thanks for reporting this bug. I have reproduced it.

**Comment by dylan-westbury** [comment]
Experiencing the same as mentioned by @lexfaraday
