### ISSUE TITLE
Amplify doesn't recognise pre-existing Vue.js project with Amplify

### ISSUE THREAD

**Issue by Murray2015** [aws-amplify/amplify-cli#5767]
**Which Category is your question related to?**
init

**Amplify CLI Version** 
4.32.0

**What AWS Services are you utilizing?**
Amplify / Cognito / S3

**Provide additional details e.g. code snippets**
I'm picking up development started by another team on a Vue.js app with AWS Amplify. They used Amplify Cli to add Auth to the app.

I've pulled the project down from GitHub. When I run the app, the Auth service is working fine.

I'm now trying to add Storage with amplify add storage, but am struggling to get the Amplify Cli (which I've had working fine on my own projects) to work with the new project.

I've tried:

- `amplify configure project`, which fails with the message 'You are not working inside a valid Amplify project. Use 'amplify init' in the root of your app directory to initialize your project, or 'amplify pull' to pull down an existing project.' (but I don't want to init a new project, this is an existing project that I've git pulled)
- `amplify pull --appId myAppIDFromTheAmplifyConsole --envName dev`, which fails with the message 'File at path: '/[thefullpath]/amplify/.config/local-env-info.json' does not exist' (and I can see that that file doesn't exist. The other team have confirmed that the file has never existed.)

My questions are:

1. Should I run `amplify init` as the first bullet point error message suggests? The auth service is working and I don't want to break the existing cognito user pools that Amplify created. Will amplify init push or rerun the cloudformation scripts and therefore change the backend?
2. If I shouldn't, what should I do?

Thanks!

**Comment by akshbhu** [comment]
Hi @Murray2015 

```amplify init``` will just initialize a new amplify project with IAM roles defined if the project hasn't been initialized before. For a new project it will setup the deployment bucket and IAM roles attached to it. Check documentation here :https://docs.amplify.aws/cli/start/workflows

For your case where the project has already been initialized, it will automatically detect the project has been initialized and ask ```Do you want to use an existing environment?``` or a new environment.
Here either you can work on existing environment (lets say ```dev```)or you can add a new environment to test your changes and later merge your new environment into dev.

It wont change the backend until you do amplify push.
We have a detailed documentation for your use-case : https://docs.amplify.aws/cli/teams/shared

Let me know if this resolves your problem.
