### ISSUE TITLE
Execute custom script before amplify push for all resources

### ISSUE THREAD

**Issue by amirhajimirsadeghi** [aws-amplify/amplify-cli#5774]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
The ability to run a custom script before `amplify push` for functions is very useful and empowering. It's frustrating that the same functionality is not supported for all resources. 

There are many ways that this could add utility to people's projects, my particular use case is uploading an S3 file before deploying CloudFormation for a AWS Step Function custom resource. The CloudFormation for that resource allows the state machine definition to be read from S3 which would allow me to define the state machine in an external file and upload it to S3 before amplify push.

**Describe the solution you'd like**
The solution I'd like to see is having the support for function pre push script to be supported for all resources.

**Describe alternatives you've considered**
Every particular example where this would be useful will probably have many alternatives for getting this done, but it comes with it's own headaches. For me, either I work with an escaped json string in CloudFormation or I manually make sure that the S3 file is up to date before I push my changes

**Additional context**
How functions support this:

My **package.json** for a project that has 3 functions (catalog, user, and order handler):

```
{
  "name": "client-webapp",
  "version": "0.1.0",
  "private": true,
   ...
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "build:qa": "REACT_APP_STAGE=qa react-scripts build",
    "build:prod": "REACT_APP_STAGE=prod react-scripts build",
    "amplify:catalog": "cd amplify/backend/function/catalog/src && npm i && node_modules/.bin/tsc && cd -",
    "amplify:user": "cd amplify/backend/function/user/src && npm i && node_modules/.bin/tsc && cd -",
    "amplify:orderhandler": "cd amplify/backend/function/orderhandler/src && npm i && node_modules/.bin/tsc && cd -",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
...
}

```

**Comment by kylekirkby** [comment]
This would be very useful 👍🏼

**Comment by lexfaraday** [comment]
+1 Post push also will be useful, for example to create dynamodb global tables such are not supported by a CloudFormation
yet, in order to keep all processes automated.

**Comment by Leandros** [comment]
Any progress on this?

**Comment by kylekirkby** [comment]
@Leandros there is this https://docs.amplify.aws/cli/project/command-hooks/#adding-a-command-hook

**Comment by josefaidt** [comment]
Hey folks :wave: as @kylekirkby noted (thank you for that!) this feature has since been released with [command hooks](https://docs.amplify.aws/cli/project/command-hooks/#adding-a-command-hook)! Closing issue 🙂
