### ISSUE TITLE
Option to auto-update functions that depend on a layer when layer version increments

### ISSUE THREAD

**Issue by j-yamamoto** [aws-amplify/amplify-cli#5779]
**Which Category is your question related to?**

Documentation "Update layer content"
https://docs.amplify.aws/cli/function/layers#update-layer-content

**Amplify CLI Version** 

4.32.0

**What AWS Services are you utilizing?**

AWS Lambda
AWS Lambda Layers

**Provide additional details e.g. code snippets**

In the lambda layer documentation, it says,

>  If there are changes available, the Amplify CLI will create a new layer version with the changes and **ask during amplify push if you’d like to update all dependent functions to use the latest version.**

while amplify cli does not ask anything about updating all dependent functions when I update and push changes in lambda layer.

Am I doing something wrong, or is this statement wrong?

Here is what cli prompts when I update lambda layer and run `amplify push`.
```
? Are you sure you want to continue? Yes
Content changes in Lambda layer [Lambda Layer Name] detected. Layer version increased to 4
Note: You need to run "amplify update function" to configure your functions with the latest layer version.
? What permissions do you want to grant to this new layer version? Previous version permissions
```

**Comment by akshbhu** [comment]
Hi @j-yamamoto 

> Content changes in Lambda layer [Lambda Layer Name] detected. Layer version increased to 4

The above quoted statement means , if you change anything in the lambda layer files locally in your project , amplify-cli automatically tracks your changes as you can see in the prompt you have mentioned above and will increase the layer version by 1 because lambda layer versions are immutable when deployed, any changes made to the layer after that will result in a new lambda layer version.

> Note: You need to run "amplify update function" to configure your functions with the latest layer version.

The next prompt is to update you on the functions as you might some functions dependent on previous layer versions but as you have updated the lambda layer version , you may need to point the function to the latest version of  lambda layer. CLI here  prompts to do an ```amplify update function ``` to point your function to this new layer when you have pushed the layer.

**Comment by akshbhu** [comment]
Hi @j-yamamoto 

Sorry for the confusion. I misunderstood the above quoted lambda layer documentation. I am marking this as bug for documentation. Thanks for reporting it.

**Comment by j-yamamoto** [comment]
@akshbhu Thank you for working on this issue. Although the statement below was wrong, do you guys have any plan on implementing this feature?

> If there are changes available, the Amplify CLI will create a new layer version with the changes and ask during amplify push if you’d like to update all dependent functions to use the latest version.

Since I use Amplify Console CI/CD feature, I would like amplify cli to update and push all functions depended on the lambda layer at the same time when the lambda layer gets updated and pushed. 

Otherwise, I need to deploy twice. First deploy for the lambda layer update and second deploy for all functions depended on the lambda layer.

**Comment by jgroom33** [comment]
a quicker way to do the update on the functions is find/replace on two files for each function:

* function/foo/function-parameters.json
* foo-cloudformation-template.json

a new "feature" just added to vscode excludes the *-parameters.json from the file view.  This breaks the find/replace in vscode for this file.

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!

**Comment by DeerajTheepshi** [comment]
> Hi all!
> 
> We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.
> 
> **DO NOT USE THIS IN PRODUCTION!**
> 
> To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`
> 
> Notable changes:
> 
> * Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
> * Option to automatically update dependent functions to the latest deployed Lambda layer version
> * Added ability to delete individual layer versions
> * Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
> * Support editing layer version descriptions
> * Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`
> 
> We'd love to hear any community feedback!

Are there any documentation to these newly introduced features ?

**Comment by jhockett** [comment]
Hi @DeerajTheepshi,

Docs on migrating your existing Lambda layers: https://docs.amplify.aws/cli/migration/lambda-layers-update

In order to have a Lambda function depend on the latest layer version, it needs to be updated with `amplify update function`. If you have multiple Lambda's depending on a layer, each one will need to be updated once.
