### ISSUE TITLE
Sorting with @searchable returns an empty array

### ISSUE THREAD

**Issue by andre-scheffer** [aws-amplify/amplify-cli#5786]
**Describe the bug**
I created a simple model with a createAt-field written explicitly:

`type Foo 
  @model
  @searchable
{
  id: ID!
  bar: String
  createdAt: String
}`

After deploying to Amplify, I created test entries in my Angular app:

```
await this.apiService.CreateFoo({bar: "test1"})
await this.apiService.CreateFoo({bar: "test2"})
await this.apiService.CreateFoo({bar: "test3"})
```

Finally, I wanted to get entries returned in descending order according to createdAt.

```
let sort = {
      field: SearchableFooSortableFields.createdAt,
      direction: SearchableSortDirection.desc
};
let testData = await this.apiService.SearchFoos(
      undefined,    // No filter needed
      sort,
      25
);
console.log(testData); // The item list of testData is empty
```

Error: The item list is empty

![image](https://user-images.githubusercontent.com/48789566/98234341-99a54a00-1f60-11eb-8bfa-05328b5643a4.png)

Cross check with the bar-field:

```
let sort = {
      field: SearchableFooSortableFields.bar,
      direction: SearchableSortDirection.desc
};
let testData = await this.apiService.SearchFoos(
      undefined,    // No filter needed
      sort,
      10
);
console.log(testData); // The item list of testData is not empty
```

Here the article list is not empty and correctly sorted

![image](https://user-images.githubusercontent.com/48789566/98234584-f56fd300-1f60-11eb-872c-b79e4f727c81.png)

**Amplify CLI Version**
4.32.0

**To Reproduce**
Pls see above under "Describe the bug"

**Expected behavior**
The list with sortings according to createdAt and (probably also updatedAt) should return a correctly sorted list.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v12.16.3

**Additional context**
The problem exists whether I set a filter or not.

Eventually related issues:
#2161
#2720

**Comment by akshbhu** [comment]
Hi @andre-scheffer 

Thanks for reporting it.

**Comment by andre-scheffer** [comment]
@akshbhu, did you have the chance to take a look at it?

**Comment by davorian** [comment]
I can see this error too.

**Comment by davorian** [comment]
@akshbhu any updates?

**Comment by PatrykMilewski** [comment]
We noticed the same problem in our application

**Comment by akshbhu** [comment]
Hi @andre-scheffer 

Is there a specific reason to use createdAt type as ```String``` instead of ```AWSDatetime```. We are still discussing on enhancement to pass types from appsync to elasticsearch.
For the workaround you use type ```AWSDateTime``` instead of String.

Let me if this works for you?

**Comment by andre-scheffer** [comment]
Hi @akshbhu,

if you create a model in your schema.graphql the createdAt- and updatedAt-Fields are created by Amplify. So IMHO it is a bug.

For now I paused my efforts on @searchable because of the pricing. So I can't validate your workaround. I think I'll come back to it late in my project.

Cheers,
André

**Comment by PatrykMilewski** [comment]
Since we are facing the same issue, I will try this solution tomorrow.

**Comment by akshbhu** [comment]
Hi @andre-scheffer 

> if you create a model in your schema.graphql the createdAt- and updatedAt-Fields are created by `Amplify.`

That's true. But the type will be ```AWSDateTime``` for the both createdAt and updatedAt unless createdAt is present as a field in your schema.

@PatrykMilewski 

Let me know if that works for you?

**Comment by lzygmanski** [comment]
Hello @akshbhu!

After we changed to `AWSDateTime` createdAt and updatedAt works fine. Thanks for help!

cc @PatrykMilewski

**Comment by Risord** [comment]
This issue hit us when using custom field which happen to contain timestamp and was a string.
Consider reopening and fixing properly. It does not make sense that certain sorting rule (with certain data?) will cause query result silently break and returning zero.
