### ISSUE TITLE
How to access the current environment?

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#5790]
I have an angular app and I'm using `@aws-amplify/ui-angular` and `aws-amplify`.

How do I access the current environment that I'm hooked up to? Just to be sure, I have two environments `amplify env list`:

```
| Environments |
| ------------ |
| dev.         |
| *prod        |
```

I see: `amplify/.config/local-env-info.json` and it has:

```
  "envName": "prod"
```

So how to do I get that `envName` at runtime?

**Comment by akshbhu** [comment]
Closing in favour of #4364 

As a workaround , you can check for ```aws-exports.js``` file , some variables might contain envName attached to some resource variables. For example : 

You can do some easy regex to filter that out. This comment might help: https://github.com/aws-amplify/amplify-cli/issues/4364#issuecomment-635768030
