### ISSUE TITLE
Sorting+Limit with AppSync + Elastic Search

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-cli#5795]
With AppSync <-> Elastic Search, according to the docs, it advises you to use `filter` when searching for a specific term.
https://docs.amplify.aws/cli/graphql-transformer/searchable

If I have a 100 posts and post #1, #2, #100 have my type === 'blog', I **expect** to get **3 results** back if I search by type === 'blog' and limit at 5 with Elastic Search using the following query. But I get back **actually** **1 result**.

If I remove the`sort: {direction: desc, field: time}` I get back all 3 results.

```
query MyQuery {
  searchList(sort: {direction: desc, field: time}, limit: 5, filter: {
    type: {
      matchPhrase: "blog"
    }
  }) {
    items {
      id
      type
    }
  }
}
```

I think the issue is with `filter` because it searches then filters.

With AppSync <-> DynamoDB, in the schema.graphql you can add the `keys` attribute to create a GSI, so when you query, you don't need to use the `filter` key, but in the root of the query specify the attribute you added as a key. This fixes the LIMIT issue in the AppSync <-> DynamoDB scenario.

How do I fix this issue with the AppSync <-> ElasticSearch scenario?

**Comment by akshbhu** [comment]
Hi @chantlong 

It seems like there is no value with just ```blog``` keyword present in your inverted index in ES. Values like ```blog1``` or ```blog2``` wont be fetched using just ```matchphrase``` as it will look for ```blog``` keyword in your index.

Can you try with ```matchPhraseprefix```?

Let me know if this works for you?

**Comment by chantlong** [comment]
@akshbhu "blog" is just a text example, it can be anything. type has "blog", "business", "finance"...etc.

Anyways it seemed like there was a problem with the resolvers generated by Amplify in that it causes the search, to search the entire Table with the matched text and then filtered by user Id in the resolver. Managed to be fixed with a custom resolver so that it queries results only belong to that user id without filtering needed.
