### ISSUE TITLE
@auth not propagating to nested type (without @model) for provider IAM

### ISSUE THREAD

**Issue by vthukral94** [aws-amplify/amplify-cli#5799]
This is the duplicate of this [issue](https://github.com/aws-amplify/amplify-cli/issues/3064) which was closed in January. But, still seems to be present as confirmed by other users in comments as well.

**Comment by vthukral94** [comment]
@attilah is this something you can look into?
Thanks

**Comment by akshbhu** [comment]
Hi @vthukral94 

Are you using the latest amplify version?

Have you tried this workaround mentioned in this comment : https://github.com/aws-amplify/amplify-cli/issues/3064#issuecomment-575704940

**Comment by pdsorensen** [comment]
I can confirm that after using the @aws_iam on my many-to-many relationship it was possible to access it through my iam credentials in appsync.

**Comment by vthukral94** [comment]
@pdsorensen 
I am using v4.32.0 of `@aws-amplify/cli` & 
```
"@aws-amplify/api": "^3.2.10",
"@aws-amplify/auth": "^3.4.10",
"@aws-amplify/core": "^3.8.2",
```

**Comment by pdsorensen** [comment]
Hi @vthukral94, here is my schema that at least made it possible for me. I just tried to slim some of the auth directives down by removing ` { allow: private, provider: iam }` but that lead to a `Unauthorized`, so i readded them again.

My libraries is a bit outdated, cli version is 4.29.0, my frontend app libraries are:  
```    
"aws-amplify": "^3.0.8",
"aws-sdk": "^2.209.0",
```
(and then i'm calling appsync through a v4 signed IAM request in a lambda)

```
type Poll
  @model
  @aws_iam
  @auth(rules: [{ allow: private, provider: iam }, { allow: private }]) {
  id: ID!
  title: String!
  fromDate: AWSDateTime!
  toDate: AWSDateTime!
  deadline: AWSDateTime
  selections: [Selection] @connection(name: "PollSelections")
  requiredUsers: [PollUserJoinTable]
    @connection(keyName: "byPoll", fields: ["id"])
  locked: Boolean!
}

type PollUserJoinTable
  @model
  @aws_iam
  @key(name: "byUser", fields: ["userID", "pollID"])
  @key(name: "byPoll", fields: ["pollID", "userID"])
  @auth(rules: [{ allow: private, provider: iam }, { allow: private }]) {
  id: ID!
  userID: ID!
  pollID: ID!
  user: User! @connection(fields: ["userID"])
  poll: Poll! @connection(fields: ["pollID"])
}

type User
  @model
  @aws_iam
  @auth(rules: [{ allow: private, provider: iam }, { allow: private }]) {
  id: ID!
  email: String
  phone: String
  displayName: String
  slackId: String
  polls: [PollUserJoinTable] @connection(keyName: "byUser", fields: ["id"])
}
```

**Comment by kaustavghosh06** [comment]
Closing based on @pdsorensen's response. Thanks @pdsorensen for the assistance.
