### ISSUE TITLE
Support Sign In with GitHub

### ISSUE THREAD

**Issue by safaiyeh** [aws-amplify/amplify-cli#5807]
**Is your feature request related to a problem? Please describe.**
I've been frustrated setting up GitHub Login with Cognito & Amplify.

This might be more of a feature request for Cognito itself than amplify-cli.

**Describe the solution you'd like**
Support GitHub Login as you do with Facebook, Google, Amazon, and Apple.

**Describe alternatives you've considered**
One way to setup GitHub is use a custom OIDC provider to handle logging in with GitHub. There is an open source repo here: https://github.com/TimothyJones/github-cognito-openid-wrapper that provides this integration.

I've bumped into different issues with it. Refresh tokens and accessing fields I would like.

Currently, the easiest solution is to use Firebase for Auth and Amplify for other services.

**Comment by safaiyeh** [comment]
cc @undefobj

**Comment by sw-yx** [comment]
related federated login provider requests:

- GitHub: https://github.com/aws-amplify/amplify-cli/issues/2529
- Twitter: https://github.com/aws-amplify/amplify-cli/issues/995
- Apple: 
	- https://github.com/aws-amplify/amplify-cli/issues/3434
	- https://github.com/aws-amplify/amplify-cli/issues/3929

**Comment by jamesonwilliams** [comment]
Closed in favor of #2529.
