### ISSUE TITLE
Removing @searchable causes unintended impacts on unrelated Elasticsearch endpoints

### ISSUE THREAD

**Issue by scowie** [aws-amplify/amplify-cli#5809]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I had 2 projects using amplify-cli (Project1 and Project2), both using the @searchable keyword on a schema object and so both having an Elasticsearch domain.  I removed the @searchable tag from the schema on Project1 and pushed the change.  Subsequently, not only was the Elasticsearch domain for Project1 deleted, but also the Elasticsearch domain for Project2 was impacted with loss of all data and loss of a customized index mapping.

**Amplify CLI Version**
4.10.0

**Expected behavior**
Expected no impact on the Elasticsearch domain for Project2

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.7
 - Node Version. 12.19.0

**Comment by kaustavghosh06** [comment]
@scowie This seems concerning. How was the other ES domain configured? 
When you remove the @searchable directive, only the ElasticSearch domain configured using the CloudFormation stack by the CLI should be removed and impacted.

**Comment by scowie** [comment]
@kaustavghosh06 The ES domain was configured to allow searching for activities by location (map bounding box) as follows:  1) Created a new mapping type property to have "type": "geo-point", 2) Deleted the index "activity" which had been created by the amplify cli for the searchable graphql type "Activity", 3) Re-created the "activity" index on the elasticsearch domain to include use of the new "geo-point" property.
I will also note that the elasticsearch domain that was deleted from Project1 was configured the same way with a "activity" index having been created from a searchable graphql "Activity" type.  Both projects were working and had activities in elasticsearch domains.  Then I removed the searchable from Project1 because it was no longer needed.  The next time I loaded Project2 I noticed all of the activities were gone and I had to repeat the 3 steps that I mentioned above to get it working again.

**Comment by attilah** [comment]
re-adding pending triage until repro steps are provided.

**Comment by josefaidt** [comment]
Hey @scowie :wave: unforunately I'm unable to reproduce this using the following steps on the latest version of the CLI, 4.50.2:

1. in two separate directories, `project1/` and `project2/`:
  1. initialize Amplify project with `amplify init -y`
  2. add a GraphQL API with `amplify add api` and accepting defaults
  3. modify the Todo schema with
    ```graphql
    type Todo @model @key(fields: ["name"]) @searchable {
      name: String!
      description: String
    }
    ```
  4. run `amplify push` and follow the prompts
2. Using the GraphQL API, add a few sample data items
3. Confirm searchable queries are functional
4. Remove `@searchable` from schema in `project1`
5. run `amplify push` and follow the prompts
6. confirm searchable queries are not valid in `project1`
7. confirm searchable queries still function in `project2`

Please let me know if there are any differences between what you experienced and the procedure noted above (with the updated CLI), and if applicable provide a sample of the GraphQL schema used when this issue occurred.
