### ISSUE TITLE
CLI returns to prompt slowly under proxy environment

### ISSUE THREAD

**Issue by Meganezaru** [aws-amplify/amplify-cli#5813]
**Describe the bug**
Currently I'm trying to learn Amplify CLI commands.

When I execute some command, it finishes so slowly.
For example, when I execute 'amplify status', it consumes about 1min 20s.

My Internet environment is under the corporate proxy server.
I set HTTP_PROXY env variable to the corporate proxy address.

It looks there are some accesses going out via 443 port directly (handshake SYN).
It occurs many retransmission because the outgoing port isn't opened in our environment.

I guess it has a possibility of the reason for this issue.

Why don't they though the proxy server?
What are these requests via 443 directly?

**Amplify CLI Version**
The version is 4.32.0

**To Reproduce**
Executing a command in the environment that is under proxy servers.

**Expected behavior**
All traffics are sent through the proxy server and Amplify commands finish soon after its process.

**Screenshots**
![image](https://user-images.githubusercontent.com/3725684/98518189-66d9b980-22b2-11eb-835c-0f6f04083ca9.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Node Version. v15.0.1

**Comment by josefaidt** [comment]
Hey @Meganezaru :wave: are you still experiencing this issue with the [most recent version of Amplify CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v10.6.0)?

**Comment by josefaidt** [comment]
Hey @Meganezaru :wave: just wanted to follow up on this issue to see if you're still experiencing this using the latest version of Amplify CLI?

**Comment by Meganezaru** [comment]
I've already left the company, so I cannot check it.
Sorry.

**Comment by josefaidt** [comment]
Closing as this is no longer applicable
