### ISSUE TITLE
Amplify | Adding a different DynamoDb resource to an existing AppSync Resolver

### ISSUE THREAD

**Issue by apurvamistry** [aws-amplify/amplify-cli#5815]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Amplify AppSync Custom Resolvers

**Amplify CLI Version** 
4.31.1

**What AWS Services are you utilizing?**
AWS Amplify, AppSync, DataStore, Auth

**Provide additional details e.g. code snippets**
I started working on Amplify a few weeks ago. Having set up my basic structure, I now am at a point where I need some customization to be added to my AppSync resolvers. To explain it better, here's my schema (this is indicative, of course, but it serves to explain the relationship model):

```typescript
type Post
  @model
{
  id: ID!
  text: String
  comments: [Comment!] @connection(keyName: "byPost", fields: ["id"])
}

type Comment
  @model
  @key(name: "byPost", fields: ["postID"])
{
  id: ID!
  text: String
  postID: ID!
  post: Post @connection(fields: ["postID"])
}

```

As expected, doing an `amplify push` generates all the relevant resolver VTL files for me.
What I would like to do is, within the request resolver for listing the comments, i.e. `Query.listComments.req.vtl` (or the response resolver), I want to access the entire `Post` object. What I do get is just the `postID` at the `Comment` level, but I would instead want to use the entire `Post` object, to carry out some processing that is necessary for my business use case.

Here's the auto-generated VTL file for request resolver for listing comments:
```
#set( $limit = $util.defaultIfNull($context.args.limit, 100) )
#set( $ListRequest = {
  "version": "2018-05-29",
  "limit": $limit
} )
#if( $context.args.nextToken )
  #set( $ListRequest.nextToken = $context.args.nextToken )
#end
#if( $context.args.filter )
  #set( $ListRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") )
#end
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
  #if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
$util.toJson($ListRequest)
```

What would be ideal is for me to get access to the `Post` object here, and then pass it via args to the response resolver for listing comments.

Theoretically, I do know that there is a way to add a resource to the `CustomResources` stack file. What I am unclear about is, how do I add the `Post` DynamoDb table as a resource and access it within the request resolver for `Comment`?

Any guidance here is much appreciated.

**Comment by Meganezaru** [comment]
I think you should attach new resolver to the 'post' field of Comment type.
Probably it will be like getPost resolver.

**Comment by kaustavghosh06** [comment]
@Meganezaru You're right - you'd need a custom resolver for this. You can read more about it out here @apurvamistry - https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model
