### ISSUE TITLE
Avoid deletion of production storage

### ISSUE THREAD

**Issue by rush86999** [aws-amplify/amplify-cli#5816]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
 cli shows deletion of current s3 and creation of a new one for my current production environment. I have active users in production environment. Is there a way to manually avoid this conflict?

**Amplify CLI Version**
4.31.0

**To Reproduce**
I created a new devel environment and deleted an S3 trigger. In order to delete the s3 trigger I needed to delete the storage and added it again. When I went to prod environment, it showed to delete current storage and add a new one. The current storage has files that cannot be deleted or replaced. How do I avoid this conflict while still working on development of the app.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
macos 
 - Node Version. You can use `node -v` to check the node version on your system
v12.13.1

**Additional context**
I am working on the development environment. Eventually I want to merge my changes but I am afraid to do so at this point. I also had a screen showing 
<img width="481" alt="Screen Shot 2020-11-09 at 1 10 21 PM" src="https://user-images.githubusercontent.com/16848240/98579777-0c7a3200-228d-11eb-84bf-9052255a383b.png">

**Comment by rush86999** [comment]
just to add to the issue, my production app is based on the old graphql schema setup. The new code I m writing is in the development environment that I will push into production later

**Comment by kaustavghosh06** [comment]
@rush86999 To remove the S3 trigger - you could've just run `amplify update storage` -> remove trigger instead of removing the storage resource completely. When you checkout from say 'dev' env to 'prod' env - the changes from dev - carry-froward to prod. To avoid that you can use the `--restore` flag when checking out prod - `amplify env checkout prod --restore` or after checking out prod, you can also run `amplify env pull --restore`.
