### ISSUE TITLE
Missing Credentials in Config

### ISSUE THREAD

**Issue by James-Perrin** [aws-amplify/amplify-cli#5817]
"ERROR Error: Uncaught (in promise): CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"

Within my angular project I have Auth, Storage, and API. When I added tables to the schema for the api I got the message above at run time. I have tried configLevel  "project" and "general" with the respective information. I have tried amplify configure project and aws configure. I can still interact with the amplify cli, pushing/pulling updates, but I get that error during run time. Nothing has worked, I have exhausted my number of options so any direction is appreciated. 

Amplify CLI Version: 4.32.0

I was unable to reproduce this same error, however, it occurred once I added new API tables to the schema.

A clear and concise description of what you expected to happen; to use the credentials within local-aws-info.json.

OS:  Ubuntu 20.04.1 LTS
Node: v10.19.0

**Comment by James-Perrin** [comment]
**Package.json**

{
  "name": "quotetool"
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "~9.1.12",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.1.12",
    "@aws-amplify/ui-angular": "0.0.2-ui-preview.5368",
    "@babel/compat-data": "7.8.0",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "@types/jquery": "^3.5.1",
    "angular": "^1.8.0",
    "aws-amplify": "^2.3.0",
    "aws-amplify-angular": "^4.1.9",
    "aws-sdk": "^2.759.0",
    "cropperjs": "^1.5.9",
    "dompurify": "^2.1.0",
    "html2canvas": "^1.0.0-rc.7",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.5.13",
    "rxjs": "~6.6.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "^9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@angular/language-service": "~9.1.12",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jspdf": "^1.3.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.8.3"
  }
}

**Comment by nikhname** [comment]
@James-Perrin just to be clear, you did not see the error again until you added additional tables to your API?

**Comment by James-Perrin** [comment]
@nikhname  Yes that is correct.
