### ISSUE TITLE
IAM auth missing appsync policy and returning 401 response

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#5822]
**Which Category is your question related to?**
API and Auth4

**Amplify CLI Version** 

4.32.1

**What AWS Services are you utilizing?**
AppSync, Cognito

**Provide additional details e.g. code snippets**
I am seeing an issue with auth and API where making a query like this gives a 401 response.

```
        API.graphql({
          query: listPosts,
          authMode: 'AWS_IAM',
        }),
```

This is a similar issue noted here https://github.com/aws-amplify/amplify-cli/issues/3485

The way around this for me was to add the AWSAppSyncAdministrator policy to the `unauthRole` and `auth` roles added to the identity pool. I am wondering if this is the intended workflow or if something went wrong. Ideally this can be documented if it's not already.

Below you can see my backend-config
```
"api": {
    "myapi": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "mypool"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
      }
    }
```

I couldn't find any reference to the above auth and unauth roles in the generated cloud formation templates so I am wondering if maybe this could be a bug. 

I would also like to note that I added my auth services during the amplify cli api workflow so maybe something went wrong there and it would be better to do those in separate steps. First adding the api and then the auth.

**Comment by r0zar** [comment]
Did you test this as an authenticated or unauthenticated user? I'm curious because there is a step in the `Auth` config for adding unauthenticated logins.

**Comment by oste** [comment]
@r0zar I tested this as both authenticated and unauthenticated user. I had to add the appsync policy to both of these cognito roles for each to work.

**Comment by kaustavghosh06** [comment]
@oste There are a few things you'd need to do for IAM policies to be attached to the auth and unauth roles.
First you'd need to add IAM as an additional auth type to  your API using the `amplify add/update api` flow. Then for the models you want to grant IAM access, you'd need to add - @auth(rules: [{ allow: public, provider: iam }]). Once you push this change, the CLI will auto-add the necessary IAM policies to the auth and unauth roles.
