### ISSUE TITLE
Deploying with aws amplify via GitHub

### ISSUE THREAD

**Issue by ergunpp** [aws-amplify/amplify-cli#5830]
Hi,
I am building a dynamic app using gatsbyjs, and cognito authentication.
I have added the aws cli and initialized a project with the cli and setup user pools.
I am pushing the project to GitHub, from where it is pulled to aws amplify app and deployed.
Build runs ok on amplify, but whenever I am trying to login to app, get the following error:

`AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run amplify push after adding auth via amplify add auth?`

Amplify push returns 

`No changes detected`

As the aws-export file is not in the GitHub repository, it is also not included during build. Thinking adding it to backend in amplify console would help me solve the problem, I tried to edit backend settings, but there is only one option that tells me: to run the following command in the root of my project folder:

` amplify pull --appId d3f1ka39vnvynv --envName dev`

When I run the above command I get:

`Amplify appId mismatch.
You are currently working in the amplify project with Id d1bbo3dicck94q`

I am completely stuck and overwhelmed.

Appreciate help.
Thanks

**Comment by kaustavghosh06** [comment]
@ergunpp Were you able to get through this issue? Did you use the aws cli or amplify cli to setup the user-pools?
