### ISSUE TITLE
[amplify-appsync-simulator] VTL rendering failures crash silently causing difficult debugging

### ISSUE THREAD

**Issue by iamdavidmartin** [aws-amplify/amplify-cli#5831]
Hello,

I'm using the serverless-appsync-simulator (https://github.com/bboure/serverless-appsync-simulator) which wraps the amplify-appsync-simulator for local development.

When rendering a VTL fails, for whatever reason, there is no error written to the console. This causes silent failures and lots of time spent tracking down what happened.

The line below is where the crash silently happens. Perhaps that call should be wrapped in a try/catch block and the error printed the error to the console? 

https://github.com/aws-amplify/amplify-cli/blob/def49064f952663749689e829e5d37e28fdd17a3/packages/amplify-appsync-simulator/src/velocity/index.ts#L56

**Comment by nikhname** [comment]
@iamdavidmartin could you share the VTL code that failed without showing an error in the console?

**Comment by iamdavidmartin** [comment]
Sure, will do that soon. I've gone through my VTLs and fixed the problems. Most of the failures I had were just trailing commas at the end of a line in JSON. That line would be the final property in a list, for example, and the comma wouldn't be appropriate because there isn't another item following. Note that this doesn't fail on appsync online, but does locally.

I'm planning on making a pull request soon. There are more areas where there are silent failure beyond this one. I've added exception handling and logging to those areas along with an environment variable that, when set, will print debug info to the console. That's helpful because CloudWatch logs online can show, if you choose, all queries - successful and failing ones. But locally you can't get logging which is pretty darn helpful when debugging.

**Comment by attilah** [comment]
This seems to be fixed in the latest CLI as for this "listTodo" response resolver I saw the compile error for the VTL in the console:

```vtl
#if( $ctx.error )
$util.error($ctx.error.message, $ctx.error.type)
#else
$util.toJson({
    "$ctx.result"
    })
#end
```

Error was:
```
Reloading failed with error
Error: Error:Parse error on resolvers/Query.listTodos.res.vtl:4:4 
Parse error on line 5:
...{    "$ctx.result}")#end
----------------------^
Expecting 'MAP_SPLIT', got 'CLOSE_PARENTHESIS'
Mapping template change detected. Reloading...
Reloading failed with error
Error: Error:Parse error on resolvers/Query.listTodos.res.vtl:5:4 
Parse error on line 5:
...  "$ctx.result"    })#end
----------------------^
Expecting 'MAP_SPLIT', got 'MAP_END'
```
