### ISSUE TITLE
Support eu-west-3 region

### ISSUE THREAD

**Issue by mimccio** [aws-amplify/amplify-cli#5832]
Please add support for eu-west-3 (Paris) region.

**Comment by sammartinez** [comment]
Hello @mimccio, Amplify JS interacts with the Amplify CLI. Are you calling out for support within the CLI? Please let us know. cc @renebrandel for awareness.

**Comment by mimccio** [comment]
Hi @sammartinez,
Yes when we initiate a new amplify project in the CLI there is no choice for eu-west-3.
Thanks :)

**Comment by jeromeheissler** [comment]
I have setup a project with a profile in eu-west-3. All the project has been created in the correct region. But when i tried to deploy it with the Amplify Console the build failed with message : "Amplify service is not available in the region eu-west-3"

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-22T14:44:56.572Z [INFO]: 
2020-12-22T14:44:56.574Z [INFO]: [0mFor more information on AWS Profiles, see:[0m
                                 [0mhttps://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html[0m
                                 [31mAmplify service is not available in the region eu-west-3[39m
2020-12-22T14:44:56.575Z [INFO]: [31mFailed to pull the backend.[39m
2020-12-22T14:44:56.577Z [INFO]: [31mAmplify service is not available in the region eu-west-3[39m
2020-12-22T14:44:56.579Z [INFO]: [0mError: Amplify service is not available in the region eu-west-3[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:63:11)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:37:3)[0m
                                 [0m    at Object.queryProvider (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a10-queryProvider.ts:12:3)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:20:5)[0m
                                 [0m    at Object.exports.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:57:5)[0m
                                 [0m    at Object.executeAmplifyCommand (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/index.ts:256:5)[0m
                                 [0m    at executePluginModuleCommand (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:181:3)[0m
                                 [0m    at Object.executeCommand (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/index.ts:105:5)[0m
2020-12-22T14:44:56.596Z [ERROR]: !!! Build failed
2020-12-22T14:44:56.597Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-22T14:44:56.597Z [INFO]: # Starting environment caching...
2020-12-22T14:44:56.597Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by Yaskomega** [comment]
Thank you @mimccio , I was about to create a issue for this ! 
![image](https://user-images.githubusercontent.com/25390006/104506774-20704600-55e6-11eb-81a9-dba018bbc419.png)
As you can see, we don't have eu-west-3 among the possible choices.
Is it possible to deploy in eu-west-3 ? 
Can you please add the eu-west-3 choice if so ? 
@jeromeheissler what command are you using please ?

**Comment by lePaulo** [comment]
@Yaskomega: as a workaround, you can define an aws profile with the aws cli, and avoid the command `amplify configure`.  
@jeromeheissler: as a workaround in Amplify Console, you can edit build settings and apply the following template (replace `dev` by your environment name):  
```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplify init --amplify "{\"envName\":\"dev\"}" --yes
        - amplify push --yes
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by rubab** [comment]
@lePaulo I tried with aws cli but app didn't deploy on Paris region. Could you please guide me?

**Comment by mitmol** [comment]
Hello,

In the amplify app dashboard, I have the "frontend environment tab, but not the backend tab. The amplify support is not total in region eu-west-3 ?

**Comment by mwiekens** [comment]
I have the same problem. Can't deploy to eu-west-3. Same message.
With Amplify cli 5.0.2

**Comment by lambda0xff** [comment]
When trying to `amplify pull` I get "Amplify service is not available in the region eu-west-3. Failed to pull the backend. Amplify service is not available in the region eu-west-3"

Shouldn't this issue be reopened ? And also, maybe the docs should make it clear that the CLI is not available for all regions ?  Could have saved me some time ...

**Comment by drekorig** [comment]
Same problem with Amplify cli 5.1.2

**Comment by Emmanuel-D-coface** [comment]
We need to configure a cloudfront hosting to an Amplify project hosted in zone eu-west-3.

This Amplify project was created via the console interface since the Amplify CLI does not support eu-west-3 as a region (even the latest version ) which is a strange inconsistency , if it's alloawed with the console it should be added to the CLI too especially is some actions ARE NOT POSSIBLE through the console...

But the hosting is not configurable via the console , only the CLI , could you allow the CLI to support eu-west-3 ?
Thanks for the support

**Comment by laisnegautier** [comment]
I created a SSR project (with NuxtJS) with amplify configured in eu-west-3 by not using "amplify configure", but just "amplify init" with a eu-west-3 configured profile. With this, it's possible to add api and auth in the region etc... But there are issues in the console (for the hosting part) which doesn't build my backend because amplify cli doesn't support eu-west-3.

Sticking to static generation and workaround for now then.

**Comment by alexduros** [comment]
Same here ! Not able to deploy a SSR project un eu-west-3 as amplify CLI is not available there. 
Not completely clear for me on what is missing on AWS part to open it (as the service is already available in static mode) . 
Please add eu-west-3 🙏

**Comment by sebsto** [comment]
Another customer asking for AWS Amplify support in eu-west-3 https://github.com/aws-amplify/amplify-cli/issues/7794

**Comment by rudyhadoux** [comment]
I confirm.

**Comment by rudyhadoux** [comment]
Does it take ten years to add a region ?

**Comment by rudyhadoux** [comment]
Why is it closed ?????

**Comment by jhockett** [comment]
Hi @rudyhadoux, the issue was closed automatically because a linked PR was merged. It will be included in the next release!

**Comment by rudyhadoux** [comment]
Good news.
