### ISSUE TITLE
Feature: Require to specify API Gateway's endpoint and actual api endpoint  separately in Cognito(with AWS_IAM) in CloudFront + API Gateway(not edge optimized) situation

### ISSUE THREAD

**Issue by lhideki** [aws-amplify/amplify-cli#5838]
In case of authenticating by Cognito(with AWS_IAM) in CloudFront + API Gateway(not edge optimized),  by the signature that created by Amplify cannot authenticate.
Because of the signature that created by Amplify made from Host and URL that were specified in endpoint.

In order to authenticate in  CloudFront + API Gateway(not edge optimized), I must specifed the API Gateway's endpoint Host and URL for (Amplify's) signing parameter.
Examples of parameters are below.

* API Endpoint Host: api.example.com
* API Endpoint URL: /auth/api
* API Gateway's endpoint Host: [random chars].execute-api.[region].amazonaws.com
* API Gateway's endpoint Url: /Stage/auth/api
* Amplifiy's endpoint: https://[API Endpoint Host]/[API Endpoint URL] <- https://api.example.com/auth/api
* Host as signing parameter: [API Gateway's endpoint Host] <- [random chars].execute-api.[region].amazonaws.com
* URL as signing parameter: [API Gateway's endpoint Url] <- /Stage/auth/api

Current version Amplify cannot specify API Endpoint and API Gateway's endpoint separately. So Authentication will be failed with following message.

```
message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
```

**Comment by ykethan** [comment]
Hey, just following up on this. is this a feature that you would like to see implemented?

**Comment by josefaidt** [comment]
Closing due to age and inactivity
