### ISSUE TITLE
undefined Storage cause error on push

### ISSUE THREAD

**Issue by Breci** [aws-amplify/amplify-cli#5840]
**Describe the bug**

**To Reproduce**

- Create a first storage, using S3 and push it
- Then create a second storage with `amplify add storage` and select S3
```
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
Amazon S3 storage was already added to your project.
```

- Then if you want to push your project again you will get this error
```
× An error occurred when pushing the resources to the cloud

File at path: 'C:\your\path\react-amplified\amplify\backend\storage\undefined\parameters.json' does not exist
An error occurred during the push operation: File at path: 'C:\your\path\react-amplified\amplify\backend\storage\undefined\parameters.json' does not exist
```

**Expected behavior**

I expect to not have an error, and not have the undefined storage

**Screenshots**

**What is Configured?**

On the amplify-meta.json file, I can find this at the end
   ```
   "undefined": {
      "service": "S3",
      "providerPlugin": "awscloudformation"
    }
   ```

**Additional context**
I got this problem after trying to add a second bucket to my project, based on the getting starting page

**Comment by ryanhollander** [comment]
BTW you can remove the "undefined" storage configuration using "amplify storage remove" and then you'll be able to push, albeit w/o the second storage config.

**Comment by KIWI-JP** [comment]
Having the same issue here since I updated to the latest CLI version yesterday (4.32.1)

**Comment by oookoook** [comment]
Hello, I've updated to the 4.34.0 version today and the error is still happening. Is there any roadmap regarding fixing this issue or any kind of workaround? It seems to me that this is not happening to every user of amplify - guessing from the quite low activity on this issue. I also tried to downgrade to a different version (4.27.3) and the error occurred again. So maybe something is wrong with my config which can be fixed...

**Comment by mocha384** [comment]
Hi, I have faced the same issue, however, my intention is to add additional s3 storage with a different policy. Is there any plan to add multiple s3 storage options in amplify-cli or is there any workaround to achieve the same need?

**Comment by ammarkarachi** [comment]
> BTW you can remove the "undefined" storage configuration using "amplify storage remove" and then you'll be able to push, albeit w/o the second storage config.


This is a bug on our end but you would have to remove the following json from `amplify/backend/backend-config.json` to push again
```json
    "undefined": {
      "service": "S3",
      "providerPlugin": "awscloudformation"
    }
```

**Comment by ammarkarachi** [comment]
This should be fixed in the latest release, don't hesitate to reopen if you are still facing this issue
