### ISSUE TITLE
How to refresh the AppSync API key automatically?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#5843]
Assume you have the following schema
```graphql
type Todos @model
  @auth(rules: [
    { allow: public, operations: [read], provider: apiKey }
    ])
{
  id: ID!
  text: String!
}
```

To query it, you'll need a AppSync API key.
But how to refresh an API key?
For a Cognito user pools type of auth, `Auth.currentSession()`  do the job for you.
But can I refresh a public AppSync API key when using `allow: public`?

**Comment by kaustavghosh06** [comment]
@yaquawa If you'd want to update/refresh/rotate the API-Key, you'd need to go through these steps with the Amplify CLI - https://docs.amplify.aws/cli/graphql-transformer/config-params#createapikey

**Comment by yaquawa** [comment]
You mean I have to rotate them manually?!

**Comment by gruckionvit** [comment]
Why is this closed?
