### ISSUE TITLE
'amplify function update' fails to remove API dependency for post confirmation lambda triggers

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-cli#5845]
**Describe the bug**
I first created `auth` with a post confirmation lambda and then I created a graphql `api`.

When I do `amplify function update`, I want to give my post confirmation lambda access to my graphql `api`. I run into circular dependency error and learn that it is a common problem remained unfix, see (#1874).

However, the main problem I encounter is that, when I re-run `amplify function update` and deselect `api` access. The circular dependency error continues to persist. I did a bit of investigation. It seems that the bug is that deselecting `api` access on `amplify function update` doesn't really update `backend-config.json` and `amplify-meta.json`. I have to manually remove the lambda dependency on both files for the circular dependency error to disappear. 

**Amplify CLI Version**
4.32.0

**Expected behavior**
Deselecting API removes API dependency access on lambda function.

**Comment by akshbhu** [comment]
We have a PR that will fix this issue soon #6040
