### ISSUE TITLE
Will ES dedicated master nodes get removed on amplify push?

### ISSUE THREAD

**Issue by blbigelow** [aws-amplify/amplify-cli#5846]
**Which Category is your question related to?**
API(GraphQL) @serachable

**Amplify CLI Version** 
N/A

**What AWS Services are you utilizing?**
ElasticSearch Service

**Provide additional details e.g. code snippets**
I am looking at getting my ES domain up to recommended best practice standards by having dedicated master nodes running along with data nodes. If I do the work to update the domain outside of Amplify configuration am I going to be fighting the loosing battle of Amplify push calls reverting my work?

**Comment by kaustavghosh06** [comment]
@blbigelow If you're defining the ES domain completely outside of the Amplify project, then an `amplify push` shouldn't affect any of that configuration. 
Having said that, are you modifying the ES configurations generated by the Amplify CLI as a part of the @searchable directive?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response and further communication.
