### ISSUE TITLE
Amplify add notifications applies changes without amplify push

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#5847]
I have been using amplify for some time now. I have decided to use 3 separate AWS accounts for sandbox, staging, and a prod environment. When I am happy with a change in a lower environment i would promote it to the higher environment. This has been working well until I tried to add email notifications to my project.

I ran `amplify add notifications` and selected "Email" from the list of options. I expected the CLI to modify the cloudformation templates (just like other services in amplify do). The CLI made a modification to the templates but it also applied the changes to the Pinpoint project in the cloud **without** me running `amplify push`

In the process of adding notifications, the user is asked to provide **The ARN of an identity verified with SES** and **The ARN of an IAM Role used to submit events to Mobile notifications' event ingestion service**. Those appear to be used to make changes in the cloud on the spot. Because of that, the process is not repeatable in a higher environment. I cannot just take my templates and apply them as the ARNs in those environments would be different and I don't even seem to have a way to configure them.

**Comment by UnleashedMind** [comment]
You are right, the notifications category does not use the CloudFormation as the provider, it instead directly calls the Pinpoint APIs to setup and manage the updates/removals of the notification channels. The reason behind this special handling is that we are dealing with client secrets in setting up channels such as the APNS (in the .p12 file), and there is a security risk if the notifications category uses the same mechanism as for other categories, i.e. first store the client secrets in the `<project-root>/amplify/backend/notifications` folder, and then set it up in the cloud in the execution of the `amplify push` command.
As a result, if you need to set it up in another environment, you will have to provide the parameters again.
