### ISSUE TITLE
After upgrading to 4.32.1 "Unknown type "AWSEmail". Did you mean "AWSDate"?"

### ISSUE THREAD

**Issue by dwamianm** [aws-amplify/amplify-cli#5854]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
- After upgrading to v4.32.1,  GQL Api calls where schema attributes have an `AWSEmail` (AWS utility scalar type) type throws the error "Unknown type "AWSEmail". Did you mean "AWSDate"?"
- Attempting to go to 4.32.0 throws the same error. 
- Going to 4.31.0 DOES NOT throw the error. 

The offending type in the schema is:

<pre>
type Member
  @versioned
  @model(subscriptions: null)
  @key(name: "byActiveStatusByCreatedAt", fields: ["activeStatus", "createdAt"], queryField: "listMembersByActiveStatusByCreatedAt")
  @key(name: "byEmail", fields: ["email"], queryField: "listMembersByEmail")
  @auth(rules: [{ allow: private }, { allow: private, provider: iam }, { allow: public, operations: [create, read] }]) {
  id: ID!
  email: AWSEmail!
  phone: AWSPhone!
  lastName: String!
  firstName: String!
  roleType: RoleTypeEnum
  avatar: String
  isBot: BoolEnum
  dob: AWSDate
  lat: String
  lon: String
  locale: String
  tz: String
  tzLabel: String
  tzOffset: Int
  activeStatus: ActiveStatusEnum!
  lastSeenTimeStamp: Int
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime
  federatedLogin: [ID]
  notifications: [Notification!]
  orgs: [Org] @connection(keyName: "byMember", fields: ["id"])
  orgMemberships: [OrgMember] @connection(keyName: "byMember", fields: ["id"])
}
</pre>

**Amplify CLI Version**
4.32.1

**To Reproduce**
- Create a @model Type and add `AWSEmail` to any attribute in that type
- Run `amplify mock`
- Go to GraphiQL and add an item to to the previously created type
- Execute the auto generated list<Type> query

**Expected behavior**
- Query should succeed and Amazon custom scalar types should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.18.2

**Additional context**
This project has been on many previous versions of the CLI

**Comment by nikhname** [comment]
@dwamianm  Is this only an issue on mock?

**Comment by dwamianm** [comment]
@nikhname ...so far it's the only one I have had.

**Comment by dwamianm** [comment]
Any updates @nikhname

**Comment by kaustavghosh06** [comment]
@dwamianm Could you please try using the latest CLI v 4.40.1 and see if you're still seeing this issue with mock?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.

**Comment by igorkosta** [comment]
I know the issue is closed but the error still persists on 4.41.2
