### ISSUE TITLE
amplify 4.32.1 throwing error using amplify post option

### ISSUE THREAD

**Issue by karthik2872** [aws-amplify/amplify-cli#5858]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After doing amplify init and adding storage and api locally,  get error when executing amplify push command

**FeatureFlags is not initialized
An error occurred during the push operation: FeatureFlags is not initialized**

I have the cli.json created through the init process. What is missing here to be initialized

**Amplify CLI Version**
4.32.1

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by kaustavghosh06** [comment]
@karthik2872 This error should be fixed with the Latest version of the CLI - v 4.40.1. Could you please let us know if you're still stuck?
