### ISSUE TITLE
Use the Amplify CLI to generate Appsync API that uses Delta Sync

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/amplify-cli#586]
Coped from: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/318

> Hi.
> 
> I've read the docs on DeltaSync. However, the implementation is something I don't know how to proceed. I've read this doc which provides a cloudformation stack to implement a sample Appsync API that supports Delta Sync query, but I assume it a problem for me. I already have a stack generated and run by the Amplify CLI. I've thought about adding those columns manually to my table and trying to follow the docs to create queries and DynamoDb with TTL and maybe resolvers to make this work. But that would be a long manual process which might not work.
> 
> How do I use Amplify CLI to generate API that allows for Delta SYnc queries?

**Comment by pmbanugo** [comment]
@UnleashedMind is there a way to merge the sample cloudformation config from the sample doc, with what Amplify uses, so I can make this work?

**Comment by kaustavghosh06** [comment]
@pmbanugo Currently we don't have the ability to do so. But we have it in our roadmap to have this feature.

**Comment by GeorgeBellTMH** [comment]
This would be really useful, currently you have to generate the queries by hand, which can become a nightmare...

**Comment by renebrandel** [comment]
`amplify update api` allows you to toggle "Conflict Resolution" now and auto-generates models for clients to use in their app. Closing this as done.
