### ISSUE TITLE
input folder for graphql schema

### ISSUE THREAD

**Issue by NicoAs** [aws-amplify/amplify-cli#5863]
When using a default graphql schema under 
*<my_project_folder>* \amplify\backend\api\ *<my_app_name>* \ **schema.graphql** the graphql compilation is working fine

````
GraphQL schema compiled successfully.

Edit your schema at <my_project_folder>\amplify\backend\api\<my_app_name>\schema.graphql or place .graphql files in a directory at <my_project_folder>\amplify\backend\api\<my_app_name>\schema

````

I tried to move the schema in the *\schema*  folder as described in the output above in order to have more maintenable schemas, splitted in differents files. The schema will not be interpreted

````
By updating the API, the graphql will not be found.

Syntax Error: Unexpected <EOF>
GraphQLError: Syntax Error: Unexpected <EOF>
````

Any idea ? 
Thank you

**Comment by uncodable** [comment]
Hi,

Can you share your file structure tree so we can see, thanks.

**Comment by NicoAs** [comment]
I doubled check, start 
````
amplify update api 
````
.. it works now 👍  No idea what was wrong ,,,
