### ISSUE TITLE
GraphQL. Field type not present list seems mandatory with @keys

### ISSUE THREAD

**Issue by batical** [aws-amplify/amplify-cli#5868]
**Describe the bug**
Assuming a type XXX 
The field input type 'ModelXXXFilterInput' is not present when resolving type 'Query' [@965:1].
```
type XXX
  @model(
    queries: { get: "getXXX", list: null }
    mutations: { create: null, update: "updateFollows" }
    subscriptions: null
  )
  @key(
    name: "xxxGSI"
    fields: ["is2", "status"]
    queryField: "xxxing"
  )

```
I was trying to remove lots of unused resolver like list for example. But an error appear that The filed input type "ModelXXXFilterInput" is not present

I tried another combination after (still not working
```
type XXX
  @model(
    queries: { get: "getXXX"}
    mutations: { create: null, update: "updateXXX" }
    subscriptions: null
  )
```
I  had to revert back to the default setting I had
```
type XXX
  @model(
    mutations: { create: "createXXX", update: "updateFollows" }
    subscriptions: null
  )
```

I tried on multiple type in one push. the mutations value have no impact (IMO)
Just that query is required  for adding a type if I have @ keys

**Amplify CLI Version**
amplify version 4.32.1

**To Reproduce**

**Expected behavior**
Just be able to publish without all those unused resolver

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GitHub action
```
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201108.1
 - Node Version. 12

Happening on my Mac OS also


**Additional context**
Add any other context about the problem here.

**Comment by josefaidt** [comment]
Hey @batical :wave: thanks for raising this! Unfortunately I have not been able to recreate this issue with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v4.51.3). If possible, could you try again using the latest version of the CLI? Also, were you receiving this error when you push or when you attempt to query?

**Comment by akshbhu** [comment]
Closing this , if the issye still presists feel free to comment and we will reopen the issue again
