### ISSUE TITLE
GO function print doesn't appear in console when performing amplify mock function

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#5869]
**Describe the bug**
I'm trying to print a string with `fmt.Println` and `log.Println` on the Terminal when running `amplify mock function`. It doesn't seem to appear on the console.

**Amplify CLI Version**
4.32.1

**To Reproduce**
GO lambda function:
```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-lambda-go/lambda"
)

type MyEvent struct {
	Name string `json:"name"`
}

func HandleRequest(ctx context.Context, name MyEvent) (string, error) {
	fmt.Println("Where did it go?")
	log.Println("I'm lost too...")

	return fmt.Sprintf("Hello %s!", name.Name), nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

**Expected behavior**
The logs should appear on the console.

**Screenshots**
See, it doesn't appear here:
![image](https://user-images.githubusercontent.com/762914/99230244-115d5980-282a-11eb-9e74-abf30f8729bf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Windows
 - Node Version. You can use `node -v` to check the node version on your system v12.16.3

**Comment by tom-on-the-internet** [comment]
I'm having the same issue. I would like to be able to log values.

**Comment by pablo-tlnd** [comment]
same here, any news on your side ?

**Comment by nubpro** [comment]
@tom-on-the-internet @pablo-tlnd Please give the main post a 👍, so they can prioritize on this issue.

Mocking is too slow and cumbersome, I decided to test on aws console instead (which may not be ideal).

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.
