### ISSUE TITLE
Amplify Console -> App -> Provisioning using unsupported NodeJS as default version

### ISSUE THREAD

**Issue by PawanMude** [aws-amplify/amplify-cli#5871]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify Console -> App -> Provisioning using unsupported NodeJS as default version

**Amplify CLI Version**
4.32.1

**To Reproduce**
Kindly refer : https://stackoverflow.com/questions/64859295/how-to-update-aws-amplify-consoles-cicd-dockerfile-w-r-t-framework-versions 

2020-11-16T16:04:19.093Z [WARNING]: Error updating cloudformation stack
2020-11-16T16:04:24.101Z [INFO]: Following resources failed
                                 Resource Name: UpdateRolesWithIDPFunction (AWS::Lambda::Function)
                                 Event Type: create
                                 Reason: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1a755105-752a-4d83-a3a7-846bea5944cd; Proxy: null)
2020-11-16T16:04:24.103Z [INFO]: init failed

**Expected behavior**
Resource successfully completed. 

**Screenshots**
Kindly refer : https://stackoverflow.com/questions/64859295/how-to-update-aws-amplify-consoles-cicd-dockerfile-w-r-t-framework-versions

**Desktop (please complete the following information):**
 - OS: Amazon Linux 
 - Node Version : 15.2.0 

**Additional context**
None.

**Comment by BrianFanning** [comment]
Same issue here, looks like the version of Amplify on the container is pretty old, before this commit was made to change the UpdateRolesWithIDPFunction CFN template to use node10: https://github.com/aws-amplify/amplify-cli/commit/a4eb66ca1a89ce79e83f551e328c1dc04ba62f7e

**Comment by markspeich** [comment]
I ran into this problem, and then my rollback failed. The same codebase deployed successfully to a lower environment two days prior.

**Comment by PawanMude** [comment]
It's working fine with latest version of cli. 
aws-amplify/cli@4.41.0
aws-amplify/ui-react@0.2.33
aws-amplify@3.3.13
