### ISSUE TITLE
Guidance with backend user association with Auth.federatedSignIn on custom OIDC flows (not hosted)

### ISSUE THREAD

**Issue by bneigher** [aws-amplify/amplify-cli#5883]
I have a question about usage.  According to the docs on getting aws credentials using my own token exchange / refresh provider:

```
You can alternatively use Auth.federatedSignIn() to get AWS credentials
directly from Cognito Federated Identities and not use User Pool federation

...

Note that this isn’t from a Cognito User Pool so the user you get after
calling this method is not a Cognito User.
```

This is what I have in my react-native app and it works okay (though there are a lot of issues with react-native and my tokens being invalid when first opening up the app after several hours). 

My question is regarding doing lookups on my users in a backend process (completely decoupled from the aws-amplify app).  I want to make the association between the usernames I boot into this **federatedSignIn** and the cognito user id:
`(IdentityId: "us-west-2:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")`
that the app uses for all its amplify resourcing, for example private storage path key, pinpoint analytics user association, ect.

Is there any way to do this? My user pool is empty (which makes sense as it doesn't use it per the docs).  Do I need to store the association myself?

** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **

**Comment by kaustavghosh06** [comment]
@bneigher That's a great question. You can look up the identity id's and associated logins in the cognito identity pool console  out here:

<img width="1280" alt="Screen Shot 2020-12-24 at 11 06 03 AM" src="https://user-images.githubusercontent.com/7247658/103103745-215e1b00-45d8-11eb-8aab-6078f45f9b8e.png">

**Comment by bneigher** [comment]
@kaustavghosh06 all I see here is the Cognito ID (us-west-2:xxxxxx).  And when paging into one of them with a "Linked login" it's essentially an empty page.  It's useless.
<img width="1414" alt="Screen Shot 2020-12-24 at 9 43 39 PM" src="https://user-images.githubusercontent.com/4627728/103121532-6c584c80-4631-11eb-8218-e358c7a882c3.png">

I'm hoping to be able to lookup the federator's auth id (auth0) here.

**Comment by bneigher** [comment]
or rather, am expecting..
