### ISSUE TITLE
Update banner present after installing latest

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-cli#5889]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I installed the CLI via: `npm install -g @aws-amplify/cli`. I was then told an update was available, and I should move from 4.32.1 to 4.31.1. This confuses me.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.32.1

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

$ npm install -g @aws-amplify/cli
$ amplify init
See the banner saying an update is available.

**Expected behavior**

No banner. I just updated.

**Screenshots**

![CleanShot 2020-11-16 at 19 54 35](https://user-images.githubusercontent.com/19775/99326082-943fdd80-2845-11eb-8d76-ea0e84a91570.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

macOS 10.15.7
Node.js v14.2.0

**Additional context**

Rene told me to open this. Blame Rene.

**Comment by renebrandel** [comment]
cc @edwardfoyle

**Comment by litwicki** [comment]
I just tested on a 4.32.1 install and ran an upgrade to latest (now 4.36.2) to verify this has been fixed. Please reopen if there is a regression.
