### ISSUE TITLE
Amplify Codegen Fails At Generating Statements

### ISSUE THREAD

**Issue by BodiTrak** [aws-amplify/amplify-cli#589]
I am in the processing of moving my amplify project into a new machine (both OSX).
Everything still works perfectly on old machine running @aws-amplify/cli@0.1.24

When I attempt to run `amplify codegen` on new machine I get the following error:
Error Message: "**GraphQL schema file should contain a valid GraphQL introspection query result**"
Error Thrown At: amplify-graphql-docs-generator/lib/generator/generate.js

At first I thought my Schema file was bad, however, I am still able to run `amplify codegen` on the original machine.

I did some digging and I've found that the mention error message was catch error message. the actual error is actually **Maximum call stack size exceeded**
This error happens when the generator starts to generate the operations, I've also tested with reordering the codes to see if its specific to my queries, mutations, or subscriptions but they came back the same. Given that its working on my old machine, I believe I can assume that my schema is in fact valid.

**Steps to reproduce the behavior**
1. git clone project into new machine that has amplify files included.
2. yarn add @aws-amplify/cli (tested with v0.1.24 & up to date version)
3. amplify configure project (updates paths)
4. amplify codegen

**Expected behavior**
1. Download Introspection Schema from AppSync
2. Generate all-operation statements
3. Generate types for iOS - API.swift

**Full Error Output**
`2018-12-16T18:44:51.541Z - error: uncaughtException: Maximum call stack size exceeded date=Sun Dec 16 2018 13:44:51 GMT-0500 (Eastern Standard Time), pid=23996, uid=501, gid=20, cwd=/Users/kurois/GitHub/ALTO-AppSync, execPath=/usr/local/Cellar/node/11.4.0/bin/node, version=v11.4.0, argv=[/usr/local/Cellar/node/11.4.0/bin/node, /usr/local/bin/amplify, codegen], rss=121077760, heapTotal=89968640, heapUsed=65731112, external=2364960, loadavg=[4.32666015625, 3.28759765625, 2.98095703125], uptime=89408, trace=[column=18, file=/Users/kurois/.config/yarn/global/node_modules/graphql/index.js, function=Object.get [as GraphQLInterfaceType], line=45, method=get [as GraphQLInterfaceType], native=false, column=26, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=getFields, line=26, method=null, native=false, column=14, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=Object.keys.map, line=38, method=map, native=false, column=null, file=null, function=Array.map, line=null, method=map, native=false, column=6, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=getFields, line=34, method=null, native=false, column=14, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=Object.keys.map, line=38, method=map, native=false, column=null, file=null, function=Array.map, line=null, method=map, native=false, column=6, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=getFields, line=34, method=null, native=false, column=14, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts, function=Object.keys.map, line=38, method=map, native=false, column=null, file=null, function=Array.map, line=null, method=map, native=false], stack=[RangeError: Maximum call stack size exceeded,     at Object.get [as GraphQLInterfaceType] (/Users/kurois/.config/yarn/global/node_modules/graphql/index.js:45:18),     at getFields (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:26:26),     at Object.keys.map (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:38:14),     at Array.map (<anonymous>),     at getFields (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:34:6),     at Object.keys.map (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:38:14),     at Array.map (<anonymous>),     at getFields (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:34:6),     at Object.keys.map (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/generator/getFields.ts:38:14),     at Array.map (<anonymous>)]`

**Desktop (please complete the following information):**
- OS: 10.14.1
- Node: 11.4.0
- Yarn: 1.12.3

**Comment by BodiTrak** [comment]
Additional Tests:
I've made a new side environment where I do a branch new `amplify init` but it came back the same error. 

I'm not really good with node / js but after looking around for **Maximum call stack size exceeded**, I've seen others talked about different computers might have an effect on how much memory node is allow to use, and that the error might come from a recurring problem while looping thought the possible operations. 

Which makes me think if my schema is too complex, but with that said, my old machine is still running properly.

**Comment by kaustavghosh06** [comment]
@BodiTrak Yeah, I assume its tied to the memory of your system. I believe there's a recursive call being made during code generation but due to lack of memory in your system, the process is not able to allocate additional stacks for further recursive calls and thus erroring out.

**Comment by BodiTrak** [comment]
@kaustavghosh06 

Thanks, 

That was what I thought when I researched into the error message. 

With that said, the current working machine is a 2 year old MacBook Pro 13" Basic Model
As for the problem machine, its a branch new 2 months old MacBook Pro 15" w/ upgraded 32GB Ram

I guess the only thing I can do now is look into a way where I can configure the memory available to node. 

If you know of any specific memory configuration that might help with this, please do let me know. Thanks

**Comment by BodiTrak** [comment]
For others who might encounter this error during the generation process.

make sure to install the `graphql` package. 

If the `@aws-amplify/cli` was installed with `npm`, it will show that it requires `graphql` however, it doesn't if you are using `yarn`.

**Comment by codinronan** [comment]
For anyone who arrived here due to that error during `amplify init`, increase the amount of memory to your node process. 2 GB (the default) is not enough, you need at least 4 (which still may not be enough, I give my system 6 GB which always works). It's compiling some typescript and some versions of typescript are known to have this issue.
