### ISSUE TITLE
API not deployed after custom changes to template

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#5894]
**Describe the bug**
If I modify an API template, amplify correctly recognizes it as updated upon "amplify push". However, the CLI does not deploy the new version of the API. I need to go in and manually redeploy.

**Amplify CLI Version**
4.32.1

**To Reproduce**
Add anything custom to your API_NAME-cloudformation-template.json. E.g. try adding a AWS::ApiGateway::GatewayResponse section or add a new header to the Access-Control-Allow-Headers. You would see the section reflected in the AWS console but the API is not redeployed (go to Stages>Deployment History).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Node: v12.18.2

**Comment by UnleashedMind** [comment]
Did you answer "yes" on "Are you sure you want to continue?" and allow the `amplify push` to run to completion? is there any error? 
Please elaborate on the steps how you manually redeployed the update.

**Comment by krikork** [comment]
Hey @UnleashedMind, yes, I answered yes and amplify completed the deployment without any errors.
To manually redeploy the API I would go into the AWS Console, then into the API Gateway service, then select the API I was making changes to. That will load the "resources" section of the API. Then I would click on the "Actions" dropdown and select deploy API. Only after that i would see my changes working.

**Comment by UnleashedMind** [comment]
This is a known behavior of the CloudFormation, you have to create another deployment in your template to get the update deployed. The Amplify CLI does it by renaming the AWS::Apigateway::Deployment resource on each update. 
If you update the template manually, then you also need to rename the deployment resource so that the update will be deployed.

**Comment by krikork** [comment]
Thanks for the explanation.
