### ISSUE TITLE
Please support NodeJS version 14 (currently LTS and recommended for most users)

### ISSUE THREAD

**Issue by hogarthww-labs** [aws-amplify/amplify-cli#5901]
**Is your feature request related to a problem? Please describe.**

Support the latest NodeJS LTS (14.x) for AWS Lambdas

**Describe the solution you'd like**

Support the latest NodeJS LTS (14.x)

**Describe alternatives you've considered**

None

**Comment by UnleashedMind** [comment]
Thanks for bringing it up, our team will look into this.

**Comment by oookoook** [comment]
Node 14 runtime is available in AWS Lambda since yesterday: https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/

**Comment by kaustavghosh06** [comment]
We're actively looking into this. cc @attilah

**Comment by yaquawa** [comment]
I need this too!
I want to use `import` syntax in my lambda function.
