### ISSUE TITLE
Unrecognized Client Exception: API Gateway

### ISSUE THREAD

**Issue by subtlegiant** [aws-amplify/amplify-cli#5902]
**Describe the bug**
After updating CLI, a POST to my REST API results in an UnrecognizedClientException. The endpoint was working before the update. Unfortunately I don't remember which version of the client I upgraded from.  Endpoint was set up via amplify CLI in the standard way: amplify add api

Here's the code snippet:
```
import { API } from 'aws-amplify';

const actions = {
  async awsPostToEndpoint(store, userAttrs) {
    const payload = {
      email: userAttrs.email
    }
    try {
      const result = await API.post("my-endpoint", "/my-path", payload)
      return result
    } catch (err) {
      console.log(err)
    } 
  }
}
```

In addition if you look at the request header there is an undefined path as part of the credential.
authorization: AWS4-HMAC-SHA256 Credential=undefined/20201118/us-west-2/execute-api/aws4_request, 

**Amplify CLI Version**
4.32.1

**Expected behavior**
Successful POST to API

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.7
 - Node Version. 10.16.3

**Comment by UnleashedMind** [comment]
We need more information to investigate. 

1. Did you configure your Amplify library in your frontend code? 

```
import { API } from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```

2. After you update the CLI, did you modify the REST API and run `amplify push`?

In the `aws-exports.js` file do you find this section: 
"aws_cloud_logic_custom": [
        {
            "name": "api-resource-name",
            "endpoint": "https://xxxx.xxxx.<region>.amazonaws.com/<env>",
            "region": "<awsregion>"
        }
    ]

**Comment by subtlegiant** [comment]
1. Yes, this is a Vue app and I have the imports in my main.js file as follows:
```
import Vue from 'vue'
import App from './App.vue'

import '@aws-amplify/ui-vue'
import Amplify from 'aws-amplify'
import awsconfig from './aws-exports'
import vuetify from './plugins/vuetify'
import router from  '@/router/router'

import store from '@/store/store'

Amplify.configure(awsconfig)

Vue.config.productionTip = false

new Vue({
  vuetify,
  store,
  router,
  render: h => h(App)
}).$mount('#app')
```

2. No, but I have since tried replacing the API with another from scratch and still get the same error. The resources were definitely pushed with amplify push.

3. This is a snippet from my aws-export.js with the name and secrets obfuscated:
```
"aws_cloud_logic_custom": [
        {
            "name": "my-endpoint",
            "endpoint": "https://xxxxxxxxx.execute-api.us-west-2.amazonaws.com/<env>",
            "region": "us-west-2"
        }
]
```

**Comment by UnleashedMind** [comment]
on point 2, that means the frontend configuration file content hasn't changed for the `aws_cloud_logic_custom`, and you know the same endpoint used to work? 
`Unfortunately I don't remember which version of the client I upgraded from`: do you mean you are using a new version of the Amplify library?

**Comment by subtlegiant** [comment]
> on point 2, that means the frontend configuration file content hasn't changed for the aws_cloud_logic_custom, and you know the same endpoint used to work?

Yes, that is correct.

> do you mean you are using a new version of the Amplify library?

I upgraded the Amplify CLI version to 4.32.1, which is when the behavior began. The version of the aws-amplify library in my package.json is ^3.0.9, which has not changed.

**Comment by UnleashedMind** [comment]
After you update the Amplify CLI version, what amplify commands have you run to cause the frontend project to fail? 

Other than the aws-exports.js file, the Amplify CLI does not interact with your frontend's Rest API. So, if your frontend project is working, it should continuously to work if you update the Amplify CLI version, because it does not change anything in your frontend project if you do not run any commands to update either the frontend config file or the backend resources. 

Since you mentioned you have: 
```
authorization: AWS4-HMAC-SHA256 Credential=undefined/20201118/us-west-2/execute-api/aws4_request,
```
It might be related to how your auth is setup, and there are similar issues on the JS library: 
https://github.com/aws-amplify/amplify-js/issues/3816
https://github.com/aws-amplify/amplify-js/issues/2626

Please browse through them check your project's auth setup, see if you can find other possible causes.

**Comment by subtlegiant** [comment]
I suspect your assertion that updating the CLI version does not affect the frontend project is not correct because all I did was update the CLI, nothing else changed, and my API stopped working.  That being said, I did resolve the issue by updating the aws-amplify library from 3.0.9 to 3.3.8. I do appreciate your help. Hopefully if anyone else runs into this it will save some time.
