### ISSUE TITLE
Error deploying stack when using verify email with Cognito userpool

### ISSUE THREAD

**Issue by debugguru** [aws-amplify/amplify-cli#5907]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Error with email verification template for Cognito user pools

**Amplify CLI Version**
4.32.1

**To Reproduce**

1.  update the CF template for Cognito to use Email link verification instead of code
2. Update the text for email template to include the link e.g. verify you email {####}
3. amplify deploy
4. stack fails to deploy/update with following error
`Reason: The message is invalid. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 7fafa82f-1c40-4d40-b09c-02dca4a093d0; Proxy: null)`
5. If you change the email text to 'verify you email {##verify email##} {####}' the stacks deploys successfully. 

**Expected behavior**
1. Userpool should be updated with the template text. 
2. Using AWS Console, you can use template text like
verify you email {####}
or
verify you email {##Verify email##} //this is preferred 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Catalina 10.15.7]
 - Node Version. 12.19.0

**Additional context**

**Comment by debugguru** [comment]
Here is the CF template
`UserPool:

    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !If [ShouldNotCreateEnvResources, !Ref userPoolName, !Join ['',[!Ref userPoolName, '-', !Ref env]]]
      
      Schema: 
        
        -
          Name: email
          Required: true
          Mutable: true
        
        -
          Name: name
          Required: true
          Mutable: true
        
      
      
      
      AutoVerifiedAttributes: !Ref autoVerifiedAttributes
      AccountRecoverySetting: 
        RecoveryMechanisms: 
          - 
            Name: verified_email
            Priority: 1
      
      
      EmailVerificationMessage: !Ref emailVerificationMessage
      EmailVerificationSubject: !Ref emailVerificationSubject
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: !Ref emailVerificationFromEmail 
        SourceArn: !Ref sesSourceARN
      VerificationMessageTemplate:
        DefaultEmailOption:   CONFIRM_WITH_LINK
        EmailSubjectByLink: !Ref emailVerificationSubject
        EmailMessageByLink: !Ref emailVerificationMessage
          
      Policies:
        PasswordPolicy:
          MinimumLength: !Ref passwordPolicyMinLength
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      
      UsernameAttributes: !Ref usernameAttributes
      UsernameConfiguration: 
        CaseSensitive: false     
      MfaConfiguration: !Ref mfaConfiguration
      SmsVerificationMessage: !Ref smsVerificationMessage
      SmsConfiguration: 
        SnsCallerArn: !GetAtt SNSRole.Arn`

**Comment by UnleashedMind** [comment]
Do you mean that you updated the `parameters.json` file of the auth category and changed
`"emailVerificationMessage": "Your verification code is {####}",`
to
`"emailVerificationMessage": "verify you email {####}",`

**Comment by debugguru** [comment]
Yes that's correct. Plus I updated the template to send link instead of code for verification

**Comment by UnleashedMind** [comment]
The error message is from Cognito, if you configure  CONFIRM_WITH_LINK as the DefaultEmailOption, the email message has to contain `{##verify email##}`. As you have probably verified on the Cognito console.
The CLI won't be able to change this behavior.
