### ISSUE TITLE
amplify update function doesn't show full scope of permissions when using existing DDB tables

### ISSUE THREAD

**Issue by renebrandel** [aws-amplify/amplify-cli#5915]
**To Reproduce**
1. amplify add api -> REST
2. Create a new function and select CRUD + DDB template
3. Select an existing DDB

Actual: When I run amplify update function, I don't see DDB being listed as an accessible resource

**Expected behavior**
when I run amplify update function, I see the DDB being an accessible resource

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Mac
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by davidbiller** [comment]
Its under storage

**Comment by akshbhu** [comment]
@renebrandel 

Did you selected the resource permissions for the function after selecting the CRUD DDB template?

**Comment by akshbhu** [comment]
Closing this issue as it seems to be solved
