### ISSUE TITLE
Amplify add then push doesn't generate aws-exports.js for "android" -- not a doc issue

### ISSUE THREAD

**Issue by kevinsullivan** [aws-amplify/amplify-cli#592]
It is clear that amplify add _ followed by amplify push and/or amplify publish does *not* generate an aws_exports.js file when one has selected android as the application type; consequently App.js won't compile, and the whole chain breaks. 

I've read the three or four previous issues on this topic, several closed, one still open. The problem keeps being explained as a documentation problem. It's not. It is clearly the case that the promised file is *not* being generated even when the recommended set of actions is taken (amplify add component followed by amplify push). 

This problem occurs for me using Windows and a completely fresh install of all the software. It appears, and another post seems to confirm, that there is a problem generating this file when android is selected as the app type.

**Comment by UnleashedMind** [comment]
aws-exports.js file is only generated for Javascript projects. 
are you working on a react-native projects? if so, you should configure the project and set the project type to be Javascript and then select reac-native as the framework.

**Comment by kaustavghosh06** [comment]
@kevinsullivan For an android project, an `awsconfiguration.json` file should be generated by the CLI in the app directory. Are you still blocked on this?

**Comment by kaustavghosh06** [comment]
Closing this issue for now. Please feel free to re-open this if you have further questions.
