### ISSUE TITLE
AWS CloudWatch loggroup retention

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#5921]
**Which Category is your question related to?**

It seems amplify or CloudFormation create an implicit log group. How can I set the retention? I don't need to store logs forever.

**Amplify CLI Version** 

4.32.1

**What AWS Services are you utilizing?**

AWS Lambda.

**Comment by UnleashedMind** [comment]
The Log groups are auto created by the Lambda resource, the Amplify CLI does not directly create or set its configurations. I'm not aware of any straightforward way to set its retention policy. 
However,  there is a hack as outlined in this medium article, if you are interested in giving it a try:
https://medium.com/allermedia-techblog/cloudformation-example-log-retention-for-lambda-and-codebuild-a11e74516bb6

**Comment by berenddeboer** [comment]
That no longer works I'm sure, I already tried to do something like that, it says the name is already in use.

**Comment by UnleashedMind** [comment]
Have you tried to put a [DependsOn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html) on the Lambda resource, so the LogGroup is created **before** the Lambda resource?

**Comment by berenddeboer** [comment]
Yeah, that may work. But it's an existing log group, wanted to update it.

**Comment by kaustavghosh06** [comment]
@berenddeboer We create the log group as a part of the lambda function CloudFormation defintion.
You can probably add the "RetentionInDays" parameter to the log-group created as a part of the CloudFormation deinition.
Docs - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
