### ISSUE TITLE
Getting Started - Javascript - fails, bad S3 protections and content

### ISSUE THREAD

**Issue by kevinsullivan** [aws-amplify/amplify-cli#593]
**Describe the bug**
I ran the getting started tutorial here: https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs. Having pushed, access to the AWS web site fails, access denied. In the course of investigating, it became clear as well that the contents of the local dist directory were not uploaded to AWS, as the S3 bucket is empty.

**To Reproduce**
Just go through the tutorial.

**Expected behavior**
I expected a working website hosted at AWS.

**Screenshots**

**Desktop (please complete the following information):**
 OSX

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UnleashedMind** [comment]
Did you only run `amplify push` ? 
`amplify push` will create the hosting bucket for you, configured for static web hosting. 
In order to have your application hosted in the hosting bucket, you need to run `amplify publish`, as stated in the document.

**Comment by kevinsullivan** [comment]
I did publish. Nothing was pushed up toAWS and the permission on the S3 bucket remained with no public access.

**Comment by UnleashedMind** [comment]
We have not been able to reproduce the issue. 
What region did you run the tutorial? 
When you run `amplify hosting add`, did you select "DEV" (S3 only) or "PROD" (S3 and CloudFront)? 
You checked and the `dist` does have contents, right?

**Comment by liam-movember** [comment]
I also got this issue when working through the tutorial and haven't been able to resolve it.
Using Ubuntu desktop.  Amplify version: 0.1.38, AWS CLI version: 0.2.5

I selected DEV (S3 only) when creating the project.  The dist folder is populated when publishing.  The bucket is created fine.  If I upload the dist files into the bucket manually (via console, using admin account) then everything works as expected.  Hope this helps.

**Comment by josephecombs** [comment]
I'm also having this issue. Unfortunately I ran amplify push before amplify publish so maybe that's the cause. A push should NOT mess up subsequent publish es. 

Contents are not being uploaded to the appropriate S3 Bucket on publish - i.e. there is no index.html file in the bucket that the CloudFront CDN points to.

**Comment by UnleashedMind** [comment]
@josephecombs 
what's your javascript framework? is it Angular?

**Comment by josephecombs** [comment]
React

**Comment by kaustavghosh06** [comment]
@josephecombs Were you able to figure out the issue with the latest version of the CLI? Seems like @UnleashedMind fixed it in #697. Please feel free to re-open the issue if you're still experiencing it.
