### ISSUE TITLE
amplify push throw error after remove auth

### ISSUE THREAD

**Issue by khalid283** [aws-amplify/amplify-cli#5933]
**Describe the bug**
`amplify remove auth`
`amplify push`
the following error will be thrown
`Template error: instance of Fn::GetAtt references undefined resource auth*******
An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource auth****`

**Amplify CLI Version**
4.34.0

**To Reproduce**
`amplify remove auth`
`amplify push`

**Expected behavior**
push the changes to the cloud

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Node Version - 10.15.3

**Comment by Nxtra** [comment]
Hi @khalid283 ,

I tried to reproduce and did the following:
* `amplify init`
* `amplify add auth`
* `amplify push`
* `amplify remove auth`
* `amplify push`
-> Succeeded:  All resources are updated in the cloud

I did not encounter your issue.

Can you double check and if necessary add more info to reproduce the problem?

**Comment by ammarkarachi** [comment]
@khalid283 Did you have any other resources that were using Auth?

**Comment by khalid283** [comment]
@ammarkarachi I am using two services a GraphQL and Auth.

I have solved the problem another way. but removing auth does not push yet.

**Comment by Nxtra** [comment]
Can you provide the info @ammarkarachi asked for or close the issue if no longer relevant?
