### ISSUE TITLE
Cannot remove resource access permissions from function 

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#5934]
**Describe the bug**
I added permissions to my function in order to be able to access api resources.
Adding the permissions succeeded.  

I then updated the function and removed the permissions.
I tried pushing the changes.

This failed with the message:
"Parameters: [apiamplifyissueGraphQLAPIEndpointOutput, apiamplifyissueGraphQLAPIIdOutput, apiamplifyissueGraphQLAPIKeyOutput] do not exist in the template"

I think this originates from leftover configuration in `backend-config.json` that should have been removed. (more info below)

**Amplify CLI Version**
4.34.0

**To Reproduce**
```
amplify init
amplify add api (basic example)
amplify add function (hello world)
amplify push
amplify update function (update Resource access permissions -> api, crud)
amplify push
amplify update function (Resource access permissions -> unselect api)
amplify push
```

**Expected behavior**
Successfully deploy the new version of the stack where the lambda function no longer has access to the api resources.

**Screenshots**
Error message:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/36597466/99982004-580efe80-2daa-11eb-9903-01a9d635a47f.png">

**Additional context**
I found that all configuration regarding permissions had been removed from the cloudformation files except for in `backend-config.json`. 

`backend-config.json`:
```
{
  "api": ...,
  "function": {
    "testFunction": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "amplifyissue",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput",
            "GraphQLAPIKeyOutput"
          ]
        }
      ]
    }
  }     
}
```

From the above I learned that `"GraphQLAPIIdOutput"`, `"GraphQLAPIEndpointOutput"`, `"GraphQLAPIKeyOutput"` are still expected. However the function's cloudformation template, `testFunction-cloudformation-template.json`, no longer specifies this variables.  Which is indeed logical since I just asked them to be removed.

However the cli fails because they are still expected from `backend-config.json`.

**Proposed solution**
Remove the dependency on the removed parameters in `backend-config.json`

**Comment by sharmaaditya570191** [comment]
I was trying to reproduce this bug but the latest Amplify CLI version (4.45.2) does not allow me to unselect a category in the flow `amplify update function`. We can add some functionality to remove resource access permissions.

![image](https://user-images.githubusercontent.com/42587159/112020408-52f26e00-8b56-11eb-9165-8dd4780633e2.png)

**Comment by sharmaaditya570191** [comment]
https://github.com/aws-amplify/amplify-cli/pull/6766 fixes this issue.
