### ISSUE TITLE
Headless amplify init ignoring --frontend params. 

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-cli#5944]
**Describe the bug**
headless amplify init is ignoring frontend params, which is an issue when trying to init a project where the aws-exports.js needs to generate in a particular SourceDir. (e.g. /src for react-native multi-env project).

if provide --yes, aws-exports.js generates in root. 

**Amplify CLI Version**
4.34.0

**To Reproduce**
```
#!/usr/bin/env bash

npm install -g @aws-amplify/cli

REACTNATIVECONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"yarn build\",\
\"StartCommand\":\"yarn start\"\
}"

AWSCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"XXXXXXXXXXXXXX\",\
\"secretAccessKey\":\"/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\
\"region\":\"xx-xxxx-x\"\
}"

AMPLIFY="{\
\"projectName\":\"xxxxxxxxxxx\"\
\"envName\":\"xxxxxx\"\
\"defaultEditor\":\"none\"\
}"

PROVIDERS="{\
\"awscloudformation\":${AWSCONFIG}\
}"

CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react-native\",\
\"config\":${REACTNATIVECONFIG}\
}"

amplify init --frontend ${FRONTEND} --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN}
```

**Expected behavior**
Frontend params should register for amplify init

**Screenshots**
<img width="565" alt="Screen Shot 2020-11-24 at 1 28 58 pm" src="https://user-images.githubusercontent.com/16129043/100039304-0d988b00-2e59-11eb-87fb-1749603cbd57.png">
**After running script, frontend prompt shows**

<img width="457" alt="Screen Shot 2020-11-24 at 1 24 54 pm" src="https://user-images.githubusercontent.com/16129043/100039603-aa5b2880-2e59-11eb-9c9c-b3e571bb5872.png">
**From documentation**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version v12.16.3

**Comment by kaustavghosh06** [comment]
@dylan-westbury Could you try this out with the latest version of the CLI? I was able to get this to working with the latest version of the CLI:
I used the sample script below for reference:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/sample-headless-scripts/headless_init_new_project.sh

**Comment by dylan-westbury** [comment]
Hi @kaustavghosh06 

For the project (additional frontend that does not have amplify directory in repo). I can't get past this stage in ci/cd automatically using same script as above (using access key / secret).  

<img width="538" alt="Screen Shot 2021-03-25 at 6 42 35 pm" src="https://user-images.githubusercontent.com/16129043/112436602-0008f880-8d9a-11eb-80de-7e28ca145c2b.png">

Shouldn't it skip if I am specifying useProfile as false (as above)?

**Comment by cjihrig** [comment]
@dylan-westbury I think you need `--yes` in your `amplify init` command.
