### ISSUE TITLE
Failed to create LambdaExecutionRole using `amplify init --app`

### ISSUE THREAD

**Issue by imikemiller** [aws-amplify/amplify-cli#5946]
**Describe the bug**
When using an existing app containing a Lambda function to initialise a new Amplify project in the same AWS account I receive an error that the Lambda execution role already exists. This relates to the fact that the amplify project ID is not used when creating the name for this resources and the fact that the init method of the CLI hardcodes the environment name as `sampledev` and we therefore get a clash of resource names between the Amplify project CFN stacks.

The Lambda execution role name, for a function provisioned with `amplify add function`, is built with the following `Fn::Join`

```
{
  "Fn::Join": [
	"",
	[
		"projectNameLambdaRole7440fR85",
		"-",
			{
			    "Ref": "env"
			}
	]
    ]
}
```
This role name will not be unique across stacks as the name string is hardcoded into the template and only the `env` variable is available to ensure uniqueness. This env is always set to `sampledev` when initialising from an existing app.

This presents issues when using an existing app as a starting point for new projects where you may need to initialise many projects from the same app into the same AWS account.

**Amplify CLI Version**
4.21.0

**To Reproduce**

Using the steps outlined [here](https://aws.amazon.com/blogs/mobile/amplify-cli-adds-scaffolding-support-for-amplify-apps-and-authoring-plugins/) attempt to initialise a project from an app that includes a Lambda function more than once into the same AWS account.

**Expected behavior**
That each attempt to initialise a project from an existing app succeeds.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 12.14.1

**Comment by josefaidt** [comment]
Closing in favor of tracking broader issue to consolidate `amplify init --app` workflow to be similar to the general `amplify init` workflow (including `--envName` flag) https://github.com/aws-amplify/amplify-cli/issues/8611

As a workaround, either remove `team-provider-info.json` to your project before committing to git or clone the repository manually, then run `amplify init` to specify the environment name
