### ISSUE TITLE
Upgrading from 4.32.1 → 4.34.0 removed all Cognito User Pool GROUPS 

### ISSUE THREAD

**Issue by d3clan** [aws-amplify/amplify-cli#5947]
**Describe the bug**
Upgraded from 4.32.1 → 4.34.0.

The push was successful, but resulted in:
1. User Groups being removed from the Cognito User Pool (non-recoverable)
2. All Cognito triggers being removed
3. Custom verification messages being reset (previously changed manually)
4. Option for sending verifications using SES reset to in-built Cognito (previously changed manually)

**Amplify CLI Version**
4.34.0

**To Reproduce**
Ran
```
amplify status
```
Amplify reported an `update` to `Auth`, as well as the `Trigger` as I was editing (related to an auth trigger), so this was not completely unexpected

Ran
```
amplify push
```
Received the message
```
 amplify status
? Amplify has been upgraded to handle secrets more securely by migrating some values in team-provider-info.json to deployment-secrets.json
You can create a back up of the team-provider-info.json file before proceeding. (y/N)
```
Chose `y` and then `Y` to continue with the push

**Expected behavior**
To update the trigger, leaving everything else in Cognito untouched

**Additional context**
Fortunately, this was against our dev environment, but worried that this could be a blocker on any future upgrades, as we've always been keen to keep up-to-date with new features.

**Comment by ammarkarachi** [comment]
@d3clan I see the CFN being overwritten but I couldn't reproduce the user pool groups and triggers being removed
```
            - ' if(hostedUIProviderCreds.length === 0) {'
            - '  response.send(event, context, response.SUCCESS, {});'
            - ' }'
```
I see these lines being introduced part of the change in team-provider

**Comment by ammarkarachi** [comment]
Can you also share the output of `amplify status`?
