### ISSUE TITLE
Please add support for video recognition (identifying labels)

### ISSUE THREAD

**Issue by kristianmandrup** [aws-amplify/amplify-cli#5948]
**Is your feature request related to a problem? Please describe.**

> Amazon Rekognition makes it easy to add image and video analysis to your applications using proven, highly scalable, deep learning technology that requires no machine learning expertise to use. With Amazon Recognition, you can identify objects, people, text, scenes, and activities in images and videos

According to the Amplify docs however, only static image recognition is currently supported. 
We are building a Digital Asset Management platform where the main assets are videos and this feature is essential.

**Describe the solution you'd like**

Add support for videos label recognition in the same way that images are currently supported

**Describe alternatives you've considered**

Writing our own custom Cloud Formation Templates and figuring out how to hook them up

**Comment by hogarthww-labs** [comment]
For anyone interested in this feature, I've started an implementation [here](https://github.com/hogarthww-labs/amplify-cli/commit/0cd2fa89fddb53b1e1eb06bfbc60dd57ff08fde3)

**Comment by ammarkarachi** [comment]
@kristianmandrup Hey thanks for the request.

@hogarthww-labs Thanks for actively contributing, I would also take a loot at our [plugin architecture](https://docs.amplify.aws/cli/plugins#plugin-installation) to see if you could leverage that feature

**Comment by kristianmandrup** [comment]
@ammarkarachi Thanks. I've recently released 2 such plugins, for SMS and for Lambdas triggered by SMS. Still lots to learn. 
Is there a strict naming convention such as `amplify-category-<name>` for it to work?

I will aim to release the video recognition as a plugin when it is working to satisfaction.

**Comment by hogarthww-labs** [comment]
I started the plugin[ here](https://github.com/hogarthww-labs/amplify-category-video-predictions). 

Trying to get my head around all the inner working of the current mechanics and how I can best leverage it. Cheers!

Here my other recent attempts at writing plugins

- [amplify-sqs-lambda-template](https://github.com/hogarthww-labs/amplify-sqs-lambda-template)
- [amplify-sqs-template](https://github.com/hogarthww-labs/amplify-sqs-template)

I guess I should stick with the naming convention however `amplify-category-<plugin-name>`
