### ISSUE TITLE
AWS Amplify installation fails

### ISSUE THREAD

**Issue by chikason** [aws-amplify/amplify-cli#5951]
0 info it worked if it ends with ok
1 verbose cli [
... edited out
746 error Unexpected end of JSON input while parsing near '...LoAUg0E2U3IXCTAQA==",'
747 verbose exit [ 1, true ]

**Comment by ammarkarachi** [comment]
@chikason Can you fill out the following and give us more information?

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**
Add any other context about the problem here.

**Comment by chikason** [comment]
**Amplify CLI Version**
i do not have any version on my system. i uninstalled and installed my node

**To Reproduce**
i tried  bellow
npm install -g @aws-amplify/cli
npm install -g @aws-amplify/cli@4.32.0

but none of them worked

**Desktop (please complete the following information):**

OS: Windows 10
Node Version: v14.15.1

**Additional context**
npm ERR! Unexpected end of JSON input while parsing near '...LoAUg0E2U3IXCTAQA=="

708 http fetch GET 304 https://registry.npmjs.org/@graphql-codegen%2fcore 1579ms (from cache)
709 silly fetchPackageMetaData error for @graphql-codegen/core@1.8.3 Unexpected end of JSON input while parsing near '...LoAUg0E2U3IXCTAQA==",'
710 timing stage:rollbackFailedOptional Completed in 3ms
711 timing stage:runTopLevelLifecycles Completed in 97772ms
712 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...LoAUg0E2U3IXCTAQA==",'
712 verbose stack     at JSON.parse (<anonymous>)

**Comment by ammarkarachi** [comment]
Can you run `npm cache clean --force` ? and retry installing

**Comment by femster890** [comment]
Have a similar problem but I get the error :

Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:default.ssl.fastly.net, DNS:fastly.com, DNS:*.a.ssl.fastly.net, DNS:*.hosts.fastly.net, DNS:*.global.ssl.fastly.net, DNS:*.fastly.com, DNS:a.ssl.fastly.net, DNS:purge.fastly.net, DNS:mirrors.fastly.net, DNS:control.fastly.net, DNS:tools.fastly.net

any ideas

**Comment by ammarkarachi** [comment]
@femster890 
This does not look like an issue with Amplify CLI but after some cursory googling I found this 
https://stackoverflow.com/questions/52128817/hostname-ip-doesnt-match-certificates-altnames-host-registry-npmjs-org-is
Let me know if you have any question regarding Amplify CLI

**Comment by femster890** [comment]
Think i did see this but not sure if this helps me??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
