### ISSUE TITLE
Default value for schema type

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#5959]
Is there a way to specify a default value for graphQL schema types in Amplify?

ex.
myFlag: Boolean = true

This does not compile using amplify api gql-compile

We have a flag which should default to true and would like to initialize it this way when a type is created.

**Comment by renebrandel** [comment]
Hi folks - i'm transferring this issue to the CLI repo and we'll be tracking this as a feature request.

**Comment by cameronbourke** [comment]
It would be awesome to see @azurelogic's great work on [graphql-default-value-transformer](https://github.com/trek10inc/graphql-default-value-transformer) merged into the `amplify` core!

**Comment by renebrandel** [comment]
@cameronbourke this is super interesting. @azurelogic - are you still maintaining that repository?

**Comment by yaquawa** [comment]
up up up

**Comment by azurelogic** [comment]
Sorry for the delayed reply. Holidays have had me busy.

Thanks @cameronbourke for connecting me to this issue!

@renebrandel, I haven't needed to do any active work on that repo since I built it this summer. That said, I'm interested in getting that merged into `amplify` core. What do you need from me to move forward with that? Thanks!

**Comment by renebrandel** [comment]
Cool. As a first step, are you okay for us to recommend this as a third party plugin? 

We'll do some testing on our end but would love for the folks on this thread to try it out as well.

**Comment by azurelogic** [comment]
@renebrandel Sorry, I've been swamped. I'm more than happy to have you guys recommend it as a 3rd party plugin to solve this problem.

As far as testing goes, the biggest thing that you'll want to double check is data type handling. I don't think I got a chance to put BigInt and a few others through their paces. If you find any problems, feel free to open an issue. If you have a chance to work up the solution, I'd be happy to take a PR there too. Either way, just keep me posted on next steps.

Thanks!

**Comment by bahroze-alphaSquad** [comment]
+1. Really appreciate it team

**Comment by PatrykMilewski** [comment]
👍 Waiting for this feature

**Comment by renebrandel** [comment]
Hi folks - we've introduced this now as mainline feature in the new GraphQL transformer. Try the PREVIEW (do not use this in production) here: https://github.com/aws-amplify/amplify-cli/issues/6217#issuecomment-929677992

**Comment by dobeerman** [comment]
I have installed the latest version of cli that allows to support the `@default` directive. Also, the [documentation](https://docs.amplify.aws/cli/graphql/data-modeling/#assign-default-values-for-fields) stands that we can use the `@default` directive to specify a default value for optional [scalar type fields](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) such as Int, String, and more.

I use `Boolean`, but `@default` directive does not apply for such scalar type.

```text
$ amplify api gql-compile     
🛑 Schema Errors:

Expected type String!, found true.

GraphQL request:148:36
147 |
148 |   enabled: Boolean @default(value: true)
    |                                    ^
149 | }
SchemaValidationError: Schema Errors:

Expected type String!, found true.
```

Same for `Int`

```text
$ amplify api gql-compile
🛑 Schema Errors:

Expected type String!, found 0.

GraphQL request:148:33
147 |
148 |   disabled: Int @default(value: 0)
    |                                 ^
149 | }
SchemaValidationError: Schema Errors:

Expected type String!, found 0.
```

@renebrandel could you please clarify this issue? Thanks in advance.

**Comment by cjihrig** [comment]
The `value` argument must be a string. The `@default` directive will convert to the proper type for you.
