### ISSUE TITLE
Unable to remove Lambda layer

### ISSUE THREAD

**Issue by frankclaassen** [aws-amplify/amplify-cli#5961]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Added a Lambda layer to my project, added a lambda function and configured it to use the layer.  Updated function to remove lamba layer config and then tried to remove the layer, get error: Resource cannot be removed because it has a dependency on another resource

**Amplify CLI Version**
4.34.0

**To Reproduce**
add lambda layer
add function and configure to use layer
push
update function to not use layer
push
try remove layer and error appears

**Expected behavior**
expect layer to be removed

**Comment by frankclaassen** [comment]
workaround for this bug:
- edit backend-config.json and remove the layer as dependency from the function
- amplify env checkout <env>
- amplify remove function & delete the layer
-amplify push will then delete the layer

if you do amplify update function and unselect the layer from the function configuration, amplify does NOT remove the dependency for the function layer

**Comment by ammarkarachi** [comment]
@frankclaassen Did you try to push after the you removed it from the function?

**Comment by frankclaassen** [comment]
@ammarkarachi yes, when I do the push is when I get the error

**Comment by half2me** [comment]
Just a bit of extra info. In my case I got it to work without having to remove the function.
If you edit these files, removing references to the layer in your function's dependencies, the layer can be properly deleted.
- backend-config.json
- amplify-meta.json
- function-cloudformation-template

**Comment by katryo** [comment]
I ran into exactly the same problem and could not solve it. I manually removed `dependsOn` items in `backend-config.json`  but it did not work. It would be great if this problem is not forgotten...

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI
