### ISSUE TITLE
Field level @auth doesn't grant additional write privileges

### ISSUE THREAD

**Issue by PatrykMilewski** [aws-amplify/amplify-cli#5968]
**Describe the bug**
My use case is, that I want to limit access to Episode type:
 - Editors should have full read/write access
 - RatingsEditors should have only read access, but they should be able to edit rating field

The problem is, that I cannot apply the second requirement to my schema. When I'm trying to update the Episode, it always returns "Not Authorized to access updateEpisode on type Episode".

I was trying to achieve this using documentation:
https://docs.amplify.aws/cli/graphql-transformer/auth#field-level-authorization
But it doesn't covert exactly my use case.

**Amplify CLI Version**
4.32.0

**To Reproduce**
1. Create GraphQL API using following schema:
```gql
type Episode
@model
@auth(
  rules: [
    { allow: groups, groups: ["Editors"], operations: [create, read, update, delete] }
    { allow: groups, groups: ["RatingsEditors"], operations: [read] }
  ]
) {
  id: ID!
  description: String
  rating: String @auth(
    rules: [
      { allow: groups, groups: ["Editors", "RatingsEditors"], operations: [create, read, update, delete] }
    ]
  )
}
```
2. And following groups definitions:
```
[
    {
        "groupName": "Administrators",
        "precedence": 1
    },
    {
        "groupName": "Editors",
        "precedence": 2
    },
    {
        "groupName": "RatingsEditors",
        "precedence": 3
    }
]
```
3. Create user and add to RatingsEditors group.
4. Try to update any Episode using following query and RatingsEditors user:
```
mutation MyMutation {
  updateEpisode(input: {id: "1", rating: "test"}) {
    rating
    id
  }
}
```
5. It returns "Not Authorized to access updateEpisode on type Episode".
6. Add user to Editors group and try the same query. Now user is able to call updateEpisode.
7. Same problem occurs when trying to set rating field value to null (delete operation on field level).

**Expected behavior**
RatingsEditors group have only read access on Episodes, but they can edit rating field using updateEpisode mutation.

Field @auth directive should take precedence over type @auth directive and let RatingsEditors user update the field.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.19.1

Raw error output:

```js
{
  "data": {
    "updateEpisode": null
  },
  "errors": [
    {
      "path": [
        "updateEpisode"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 20,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access updateEpisode on type Episode"
    }
  ]
}
```

**Comment by waltermvp** [comment]
cognito is down in us east 1 https://status.aws.amazon.com/ 

if its a recent issue this might be it

**Comment by PatrykMilewski** [comment]
> cognito is down in us east 1 https://status.aws.amazon.com/
> 
> if its a recent issue this might be it

It's not affected by this, I'm working on eu-west-1.

**Comment by ammarkarachi** [comment]
@PatrykMilewski I am looking at it, trying to discern whether ` { allow: groups, groups: ["RatingsEditors"], operations: [read] }` is conflicting with your field level auth

**Comment by PatrykMilewski** [comment]
@ammarkarachi Thank you!

**Comment by PatrykMilewski** [comment]
Hey @ammarkarachi any updates on that?

**Comment by SwaySway** [comment]
Hello @PatrykMilewski 
This is related to how field auth rules currently operate.

> In addition an owner can perform an update operation on the Todo object, only when the content field is present as a part of the input. Any other user - who isn’t an owner of an object isn’t authorized to update that object.

Docs: https://docs.amplify.aws/cli/graphql-transformer/auth#field-level-authorization

In short since `RatingsEditors` is only allowed access to read the object, the field rule will pass but since they can't update the object as a whole the operation will fail. We are looking at enhancing `@auth` in the future as we are currently working on some graphql transformer improvements.

`@auth` RFC: https://github.com/aws-amplify/amplify-cli/issues/1043

**Comment by PatrykMilewski** [comment]
Hey @SwaySway

Understood, however I don't see any proposals for this use case in #1043, or I'm missing something?

I would love to have different access rights for fields level, like in this case. Also not having a model directive on that field would be also useful, since it doesn't really always make sense to have separate model for field, which is not actually a real entity.

**Comment by SwaySway** [comment]
@PatrykMilewski The proposal which would capture this scenario would be deny-by-default. By having this we can enforce access to specific fields while denying access to other fields. Given your schema `RatingsEditors` would be given CRUD access on the field `rating` but only having read access on other fields.

**Comment by SwaySway** [comment]
To keep track of these use cases closing in favor of the RFC.

**Comment by PatrykMilewski** [comment]
Sounds good, thanks!
