### ISSUE TITLE
Is it possible to disable opening browser when amplify publish completes?

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#5973]
**Which Category is your question related to?**
Amplify Hosting

**Amplify CLI Version** 
4.29.2

**What AWS Services are you utilizing?**
AppSync, S3

**Provide additional details e.g. code snippets**
Maybe this can be refiled under Feature Request if it doesn't exist, but I was just wondering if there's a CI/CD option for `amplify publish` to not open up web browser with deployed app once it completes. I checked [CI/CD page](https://docs.amplify.aws/cli/usage/headless#amplify-pushpublish-parameters) and [Amplify Hosting page](https://docs.amplify.aws/cli/hosting#amazon-s3-and-amazon-cloudfront) of the CLI documentation and I don't see anything for such a thing.

A little bit of background, we use Jenkins for CI/CD and our build agent is a macOS box that happens to have GUI installed. Whenever the Jenkins agent runs pipeline to deploy our web app using Amplify, there's a web browser that ends up being opened on that page. The other dev I'm working on this project with thinks that this could be fixed by not specifying a default browser, but I wonder if there's any options in Amplify CLI that can prevent browser window from being opened in the first place. 

I assume most CI/CD machines are truly headless (ie. no GUI) so we're probably a special case, but I think it would still be nice to have an option that completely prevents CLI from opening a window. And if there is actually something in the docs I missed, please let me know. Thanks.

**Comment by ammarkarachi** [comment]
@Coteh it looks like by default it is set to open the browser, I will mark this as an enhancement to be worked by the team

**Comment by FabioNevesAbreu1** [comment]
Hi, i thing that i have the same issue but when ```amplify pull``` in a headless mode, can you verify for me?
anyone have the same issue than me?
