### ISSUE TITLE
Getting error "Amplify service is not available in the region us-west-1 init failed"

### ISSUE THREAD

**Issue by rafee** [aws-amplify/amplify-cli#5978]
**Describe the bug**
First, I was having the problem described in #4918. After that I connected the app from console itself and was trying to connect the app using command `amplify init --appId <ID>`. That's when I encountered above error.
**Amplify CLI Version**
4.36.0

**To Reproduce**
Steps: 
1. `amplify init` from console. The app is not created in console. 
2. `amplify add hosting`>`Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)`. Get issue #4918.
3. Create app from console by linking from github
4. Try `amplify init --appId <ID>`. 
Get the following error at terminal:
`Amplify service is not available in the region us-west-1
init failed
Error: Amplify service is not available in the region us-west-1
    at Object.run (/home/rafee/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/amplify-service-migrate.js:44:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/home/rafee/.nvm/versions/node/v14.15.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:96:5)`

**Expected behavior**
Console app and terminal app gets connected
**Screenshots**
![Screenshot 2020-11-25 223730](https://user-images.githubusercontent.com/3380056/100382718-24fe8200-2fd9-11eb-83db-410e678c6c9a.png)

**Desktop (please complete the following information):**
 - OS: `ubuntu 20.04-wsl`
 - Node Version.: `v14.15.1`

**Additional context**

**Comment by litwicki** [comment]
Amplify Console currently does not support backend environments powered by Amplify CLI in `us-west-1`  We are hoping to have support for this before the end of the year.

**Comment by djamcon** [comment]
@litwicki It looks like there's still not support for us-west-1. Any update here?

**Comment by litwicki** [comment]
@djamcon we obviously missed that original target and apologize for that. We are working on getting an updated timeline given the new requirements for Amplify Admin UI as well, and will share as soon as we have an update.

**Comment by djamcon** [comment]
Thanks @litwicki. What do you mean new requirements?

Also, in that case, what is the shortest path forward to getting the Amplify Admin UI if we're currently working in us_west_1?

**Comment by litwicki** [comment]
@djamcon just updating you that @kaustavghosh06 and I are reviewing our plans this week and will have an update on a timeline for `us-west-1` before EOW.

**Comment by jovincroninwilesmith** [comment]
Any update on this timeline for supporting `us-west-1`?

**Comment by mikehedman** [comment]
I had a successful build yesterday, but today I am getting this error:
"Amplify service is not available in the region us-west-1"

Is Amplify available in us-west-1?  Or is this some temporary outage?

**Comment by paalvibe** [comment]
Will eu-north-1 be supported? I am getting the same error:

```
amplify init --appId foo
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: sandbox
Using default provider  awscloudformation
Amplify service is not available in the region eu-north-1
Error: Amplify service is not available in the region eu-north-1
```
