### ISSUE TITLE
graphql composite key with no value in part of key throws error

### ISSUE THREAD

**Issue by frankclaassen** [aws-amplify/amplify-cli#5979]
**Describe the bug**
I have the following schema:
```gql
type Student
  @model(subscriptions: null)
  @key(
    name: "byStudentName"
    fields: ["firstName", "middleName", "lastName", "birthDate"]
    queryField: "getStudentByName"
  )
  {
  id: ID!
  firstName: String!
  middleName: String
  lastName: String!
  gender: Gender!
  birthDate: AWSDate!
 }
```
When I try to run query getStudentByName with input 
{
  firstName: 'Emily',
  middleNameLastNameBirthDate: {
    eq: { middleName: "", lastName: 'Jacobs', birthDate: '2008-09-20' }
  }
}

```
graphql throws error: 
 errorType: 'InvalidArgumentsError',
 errorInfo: null,
 locations: [Array],
 message: "When providing argument 'middleNameLastNameBirthDate.$operation.lastName' you must also provide 
 middleNameLastNameBirthDate.$operation.middleName'."
```
**Amplify CLI Version**
4.34.0

**To Reproduce**
- use provided schema
- try and run query 

**Expected behavior**
Expect no error to be thrown as having a middleName field with no value is valid data.  DynamodDB creates the data with no middleName value but graphql transform is having an issue with generating the query

**Comment by ammarkarachi** [comment]
Hi @frankclaassen as of now we don't support partial composite keys. Please refer to this issue for updates https://github.com/aws-amplify/amplify-cli/issues/5468

**Comment by frankclaassen** [comment]
@ammarkarachi I see this as a critical design flaw in the amplify / appsync implementation as the current implementation does not cater for real world data.  There are millions of people in the world with no middle name and for a system to enforce a value for something that does not exist is ridiculous and utterly poorly thought out. This seems like a very simple fix, if the supplied value is empty, then it will not cause any errors when constructing the composite key value. I can do this with my own code without issues, can't see why this cannot be fixed in appsync / amplify????????
