### ISSUE TITLE
Create app failed The repository provider's oauth token should be alphanumeric.

### ISSUE THREAD

**Issue by mokeseven7** [aws-amplify/amplify-cli#598]
Hi There - 

Im using the aws cli with the following amplify dependencies:
    "aws-amplify": "^1.1.17",
    "aws-amplify-vue": "^0.2.4",

I followed the vue setup instructions, added hosting, and all goes well.

However, when i try to add and deploy the app via the aws amplify console, i get the following error:

**Create app failed
The repository provider's oauth token should be alphanumeric.**

I am using bit bucket, and have given the app permission. I have had successful deploys with different apps with earlier versions of the two dependencies listed above.

please let me know if there is anymore info i can provide, as any assistance here would be greatly appreciated.

**Comment by UnleashedMind** [comment]
In order to use amplify console, you need to use the @multienv version of the amplify cli.

**Comment by DanGreen100** [comment]
Hi mokeseven7, thank you for reporting this error. The AWS Amplify Console team is actively investigating the issue.

**Comment by mokeseven7** [comment]
Thanks @UnleashedMind - Is this a recent change? I have a fully functioning amplify console app here:

https://mcgrathweb.com/

That used the standard aws cli. This was built about a week ago.

I can provide more details if needed.

**Comment by mokeseven7** [comment]
Thanks @DanGreen100  - Is this a recent update? I have a fully functioning aws console app here:

https://mcgrathweb.com/

That did not use the multi

That used that exact same setup:

**Comment by mokeseven7** [comment]
Ive added some addition info here:

https://pastebin.com/z5whe0kb

Again, this was built using the standard CLI, and have had around 12 successful deployments via pushing to master branch of 0auth integrated bitbucket repo

**Comment by mokeseven7** [comment]
@DanGreen100 @UnleashedMind - Just to provide an update, i followed the exact same steps as my successful "add apps" and "deploy", except this time with a gitlab repo, and everything deployed fine. This seems like it might be having to do with bitbucket oauth flow only

**Comment by DanGreen100** [comment]
@mokeseven7 
We've pushed a change to resolve "the oauth token should be alphanumeric" error when connecting some BitBucket repositories in the AWS Amplify Console. Please let me know if you continue to experience this issue!
