### ISSUE TITLE
 There was an error initializing your environment. Cannot read property 'xxxPreSignup' of undefined

### ISSUE THREAD

**Issue by dhoulker** [aws-amplify/amplify-cli#5983]
**Describe the bug**
When trying to set up a new amplify environment i repeatedly see this error, when trying to deploy in the console, or checking out the new environment locally

**Amplify CLI Version**
4.36.0

**To Reproduce**
- Create a new environment using the CLI, then try to deploy. Environment if fine initially locally, then fails in both the console and locally when checking out the environment, or running amplify init.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] - Mac but happens in the console as well.
 - Node Version. 12.11.1

**Additional context**
The environment uses federated auth, with Google and a Cognito trigger for domain whitelisting.

**Comment by dhoulker** [comment]
Incase anyone else runs into this, I reverted back to 4.34.0 and all seems to be working again. 

Looks like an issue with v4.36.0 specifically.

**Comment by giangph-2248** [comment]
> Incase anyone else runs into this, I reverted back to 4.34.0 and all seems to be working again.
> 
> Looks like an issue with v4.36.0 specifically.

thank you so much, it works for me

**Comment by ammarkarachi** [comment]
@dhoulker we are working on a fix for release. Will keep you updated once we have it out

**Comment by ammarkarachi** [comment]
This should be fixed in 4.36.1
