### ISSUE TITLE
[Auth] Cannot remove lambda trigger

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-cli#5986]
**Describe the bug**
After adding a lambda trigger, I cannot remove it. It was the only trigger, and I am able to deselect that trigger and enable another, but I cannot deselect/remove when there's only a single remaining trigger. There are no errors and the CLI returns "Successfully updated resource <Auth Name> locally". Trigger is not removed, auth update shows it still selected, `amplify status` is not altered.

**Amplify CLI Version**
4.36.0

**To Reproduce**
1. Add "Post Confirmation" trigger.
2. Push and use.
3. Call `amplify auth update`, step through, and deselect above trigger.
4. Trigger is not removed, auth update shows it still selected, `amplify status` is not altered.
(Can, however, deselect and enable another, it will delete the previous and enable the new one, but still cannot delete last remaining trigger).

**Expected behavior**
Deselecting a trigger should remove it. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 14.12.0

**Additional context**
N/A

**Comment by akshbhu** [comment]
Closing this issue as it is solved with this PR #6403. It will be available in the next version.
