### ISSUE TITLE
Missing description for Api and Auth stacks

### ISSUE THREAD

**Issue by tainguyenbui** [aws-amplify/amplify-cli#599]
**Describe the bug**

**To Reproduce**
1. Add an API with User Pool through Amplify CLI and wait for it to be created
2. Go to 'CloudFormation Stacks' in AWS Console
3. See missing description

**Expected behavior**
A description for the stack is expected in the same way that is created for hosting, functions, storage or analytics

**Screenshots**
![screenshot 2018-12-18 at 13 49 40](https://user-images.githubusercontent.com/4402762/50158354-cf3cdd80-02cb-11e9-940c-0ababf8936ed.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 70.0.3538.110

**Additional context**

**Comment by UnleashedMind** [comment]
CloudFormation stack description is optional, it is not a hard requirement, so this is not considered a bug. 
I will note this item for our future releases, thanks for bring it to our attention.
