### ISSUE TITLE
Amplify remove env fails - cannot delete authRole and unauthRole

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#6003]
**Describe the bug**
The `amplify remove env XX` fails to delete authRole and unauthRole, to solve that, you would need to go to these IAM roles directly through the console and de-attach their policies manually. 

**Amplify CLI Version**
4.36.2

**To Reproduce**
1. Create environment
2. Create `notifications` category
3. push that environment
4. run `amplify remove env XX`, see problem

**Expected behavior**
The CLI should automatically de-attach the Pinpoint policies and should be able to delete those roles

**Comment by josefaidt** [comment]
I am no longer able to reproduce this issue after adding notifications to an environment and attempt to delete the environment. Closing issue 🙂 if you are still experiencing this please reply back to this thread or open a [new issue](https://github.com/aws-amplify/amplify-cli/issues/new/choose) and we can investigate further
