### ISSUE TITLE
Resource is not in the state stackUpdateComplete In Conflict

### ISSUE THREAD

**Issue by oras** [aws-amplify/amplify-cli#6012]
In case of conflict between backend and local the following error will appear :

"**_Resource is not in the state stackUpdateComplete_**"

The only option for now is to back up the local schema and initating the amplify pulling command.

In most of case updates in the following file must be set manually:
 app/src/main/res/raw/amplifyconfiguration.json

**Comment by oras** [comment]
Sometimes when I am trying to push updated GraphQl schema to the server, I am getting a weardo error:
"Resource is not in the state stackUpdateComplete"

In most of the times I noticed that it can happen when I am updating the API in the backend ( No through the Amplify CLI)
It's look like a conflict problem.

When I pull the upated API from the backend to the client ( Amplify side ) It delted the local schema.
I used a backup copy to create it a gain and pushed.
The original information is still saved in the "amplifyconfiguration.json"

So if I changed the schema api name it can create a conflict.

So I must delete the old API enter point from that file.

**Comment by ammarkarachi** [comment]
@oras The error is mainly caused when there is an ongoing update on your stack and it has not finished updating. I would either wait for the stack to return to `UPDATE_COMPLETE` state and retry pushing your resources.

**Comment by oras** [comment]
It didn't work on my case

**Comment by ammarkarachi** [comment]
@oras Unfortunately the console changes won't be reflected in your Amplify CLI project you would have to update the Project using `amplify update api` to update your api. Also changing names is not possible without replacement
