### ISSUE TITLE
add directive for computed properties to graphql schema

### ISSUE THREAD

**Issue by wisammechano** [aws-amplify/amplify-cli#6014]
**Is your feature request related to a problem? Please describe.**
It is very hard to expose a model field that is to be computed on the fly. It can be very tiny that doesn't need to be computed using lambda functions. A simple example is computing `fullname` based on db fields `firstname` and `lastname`. What I am currently doing is modifying the resolver response templates to do what I need.

**Describe the solution you'd like**
in the schema, I can simply say `fullname: String @computed('$firstname $lastname')` for example. It should also be ignored when mutating the object, and preferably the feature can resolve fields from connections as well, simple inline resolver. 

**Describe alternatives you've considered**
Modifying the resolver template, I compute that field using the result object and the model. While it isn't complicated, it is too much boilerplate, having to copy the resolver from the build folder then edit it.

**Comment by ammarkarachi** [comment]
@wisammechano 
Interesting scenario but this `fullname: String @computed('$firstname $lastname')` could be easily handled on the client side. Do you have some advanced use case for this scenario?

**Comment by wisammechano** [comment]
@ammarkarachi , yes, for example having an array of data while needing only the length of it, instead of querying the whole array, we can say `sessionsCount: Int @computed('$sessions.length')`. 

While this example is fairly easy to do on the client as well, all computed properties can be handled on the client. But sometimes, one doesn't wish to expose the original data to compute it, or simply lowering the data being transferred. It would be great if one can access connections as well and their properties.

**Comment by kaustavghosh06** [comment]
@wisammechano This is a great use-case for a custom transformer/plugin.
You can take a look at some of the community plugins/transformers which solve similar issues:
https://github.com/flogy/graphql-ttl-transformer
https://github.com/hirochachacha/graphql-auto-transformer
