### ISSUE TITLE
Adding Cognito triggers and admin queries to an existing Amplify project / Cognito user pool

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#6015]
We have an existing Amplify project utilizing Cognito. It has been in production for almost a year.

We would like to add Cognito triggers and admin queries to the project using amplify auth update. 
When we do this, we are informed that our existing identity pool will be deleted (!).
'Warning! Your existing IdentityPool: [pool name] will be deleted on the next "amplify push" '
Obviously not an option for an existing application.

How can we add Cognito triggers and admin queries to an existing Amplify project without impacting our existing Cognito user pool?

**Comment by mrgrue** [comment]
+1

**Comment by RossWilliams** [comment]
Create a new lambda. Modify the CloudFormation template to use the lambda as a custom resource. Inside the lambda use the npm package safe-cfn-custom-resource and call the right Cognito API calls. To make it better, pass in the Cognito user pool,  Client ID, and lambda trigger ARNs as properties. Modify backend-config.json for your lambda  so that it depends on the lambda trigger functions and the user pool, and so these properties can be passed into your stack as parameters. If you modify backend-config.json by hand, run amplify envy checkout to have the changes applied before pushing.

**Comment by ammarkarachi** [comment]
@blairtaylor Which version of the CLI are you using?

**Comment by blairtaylor** [comment]
We are currently using v4.36.1. We set up the project in the summer of 2019, don't know what version of Amplify we were using at the time.

**Comment by RuarriS** [comment]
Is there anyway to connect the Lambda function as a "Pre Sign-up" trigger from the auth's parameters.json? 

I noticed by doing a new `amplify init` and `amplify add auth` with Cognito triggers, that it creates triggers for some other types like 'DefineAuthChallenge'. I am unable to replicate this though for a "Pre Sign-up" trigger.

**Comment by ammarkarachi** [comment]
@RuarriS what is your use case of lambda also can you share your parameter values?

**Comment by RuarriS** [comment]
@ammarkarachi I believe at the time I was trying to manually integrate a Lambda function with an existing Auth resource, without blowing away my IdentityPool (i.e. not running `amplify auth update`

**Comment by kaustavghosh06** [comment]
@blairtaylor When you went through the `amplify auth update` flow - and if you choose the option of "Cloud API only" - that can potentially see the error message above. If you chose the the second option (Cloud API + IAM controls), then you won't get that warning message. It would be critical for us know more about your selections to help you further.

@RuarriS There currently isn't a way to attach an existing Lambda function as a trigger to your Amplify managed cognito user pool. We allow you to create one though for all the trigger use-cases which Cognito supports. You can open up a feature request for attachment of an existing lambda function in our repo.
