### ISSUE TITLE
Can I deploy multiple apps adding customization to each app with one main github branch?

### ISSUE THREAD

**Issue by hyungjunk** [aws-amplify/amplify-cli#6017]
I have multiple amplify apps connected to one github branch and all apps get deployed once the main branch is updated.

Each lambda function in amplify app has to configure its database connection differently.

I can't find a way to do it because environment variables that are set in amplify are not accessible in lambda nor I can use lambda's environment variable (os.environ['ENV']) to differentiate because all apps are looking at the same backend.

What would be the way to solve this?

**Comment by SwaySway** [comment]
Hello @hyungjunk 
Do you have different amplify apps as in different amplify environments? Or are there different amplify apps that are connected to the same backend? (like different frontends example: https://docs.amplify.aws/cli/teams/multi-frontend)
How is the lambda function configured?
Is the lambda function different for each app?

**Comment by hyungjunk** [comment]
@SwaySway 

It is more like using the same backend but mostly not entirely.

Say I have 3 companies to provide service with the same logic.
But each service has to connect to different DB and the db config in lambda is like
```
# db_config.py
DB_NAME = 'MY_DB'

# index.py
from db_config import DB_NAME 
def index():

    ....
    db = connect(DB_NAME)
```

As you can see, the logic is same but db configuration or something like this is the only different part.
Frontend should be entirely the same.

Lambda configuration remains the same as it is made by amplify.

**Comment by SwaySway** [comment]
How the lambda function being called? Is it possible to pass an identifier into the event when calling the lambda? Via API Gateway or AppSync?

**Comment by hyungjunk** [comment]
It is called via API Gateway. AFAIK, I could pass an identifier into event if I modify my Http Request.
But It doesn't seem good to me since user could modify http request and access to another DB.
Encrypting could be a way but it seems just making a problem to solve a problem.
Or any other you can think of?

**Comment by kaustavghosh06** [comment]
@hyungjunk How are you configuring the DB? Is it through the Amplify CLI?
