### ISSUE TITLE
"amplify env add" doesn't copy lambda env variables

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-cli#6019]
**Describe the bug**
I have a `dev` env that sets up `auth` and a `preSignUp lambda` that contains the `DOMAINBLACKLIST` env variables. 

When I called `amplify env add` to create a new env `test`. The `DOMAINBLACKLIST` variables is not copied over in the `team-provider-info.json`. Instead, it shows an empty object.

```json
// team-provider-info.json
{
   "dev": {
      "categories": {
         "function": {
            "myAuthResourcePreSignup": {
               "DOMAINBLACKLIST": "xxx.com"
             }
         }
   },
  "test": {
      "categories": {
         "function": {
            "myAuthResourcePreSignup": {
             }
         }
   }
}
```

**Amplify CLI Version**
4.36.2

**To Reproduce**
1. amplify auth add (with preSignUp trigger and set some env variables)
2. amplify env add (create a new env)
3. Observe `team-provider-info.json` for missing env variables

**Expected behavior**
Lambda env variables copy to new env.

**Comment by josefaidt** [comment]
Closing as this is no longer applicable. With later versions of the CLI (I tested with 10.7.x), the CLI will prompt for action regarding the function's env vars during `amplify env add`:

```
➜  amplify env add
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment asdf
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment asdf to AWS Amplify app: dv4lfw455k9wi

Deployment completed.
Deploying root stack a11144 [ ---------------------------------------- ] 0/4
	amplify-a11144-asdf-114819     AWS::CloudFormation::Stack     CREATE_IN_PROGRES
	UnauthRole                     AWS::IAM::Role                 CREATE_IN_PROGRES
	AuthRole                       AWS::IAM::Role                 CREATE_IN_PROGRES
	DeploymentBucket               AWS::S3::Bucket                CREATE_IN_PROGRES

Deployment state saved successfully.
✔ Initialized provider successfully.
? You have configured environment variables for functions. How do you want to proceed? (Us
e arrow keys)
❯ Carry over existing environment variables to this new environment 
  Update environment variables now 
```

**Comment by f00f** [comment]
Happened to me just now, with amplify cli version 12.3.0

**Comment by lnguyen-lc** [comment]
happened to me too
after struggling for a while, I found that somehow the env vars is not recognized by amplify, 
maybe because someone who added the env vars forgot to commit the related code
the solution is to remove all definitions related to those env vars manually (searching through the yml)
then try properly adding them using `amplify function update`
