### ISSUE TITLE
Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by chefncode** [aws-amplify/amplify-cli#6021]
**Describe the bug**
UPDATE_FAILED      authiosgettingstartedb2d588a7 AWS::CloudFormation::Stack Tue Dec 01 2020 13:20:27 GMT+0300 (Arabian Standard Time) Parameters: [hostedUIProviderCreds] must have values

**Amplify CLI Version**
4.37.0

**To Reproduce**
Following Getting Started module: Build an iOS Application with AWS
https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-four/?e=gs2020&p=build-a-react-app-three

Create a GraphQL API Service and Database
Generate Client Side Code
Deploy the API Service and Database > amplify push

**Expected behavior**
✔ All resources are updated in the cloud
GraphQL endpoint: https://yourid.appsync-api.eu-central-1.amazonaws.com/graphql

**Screenshots**
<img width="1280" alt="Screen Shot 2020-12-01 at 13 44 03" src="https://user-images.githubusercontent.com/68824513/100730652-6200b500-33db-11eb-9306-26c5e27c32e7.png">

**Desktop**
 - Mac OS 10.15.7
 - Node Version v14.15.0

**Comment by AshkanHovold** [comment]
I am getting the same error

**Comment by nubpro** [comment]
I regularly get this error.

I think what I usually do is to do `amplify pull` to make sure your local backend is synced with the one on the cloud.
Afterwards, make your changes and push again.

**Comment by jgroom33** [comment]
probably duplicate https://github.com/aws-amplify/amplify-cli/issues/5942

**Comment by AshkanHovold** [comment]
> I regularly get this error.
> 
> I think what I usually do is to do `amplify pull` to make sure your local backend is synced with the one on the cloud.
> Afterwards, make your changes and push again.

In this case I did "amplify env add" and created a brand new environment. so there is nothing to pull. I am creating the backend resources for the first time.

**Comment by chefncode** [comment]
> I regularly get this error.
> 
> I think what I usually do is to do `amplify pull` to make sure your local backend is synced with the one on the cloud.
> Afterwards, make your changes and push again.

Thank you very much. Its work! I thought it is one of the way we manipulate the cloud system, even we have nothing yet on the cloud, but very helpful.

**Comment by chefncode** [comment]
@AshkanHovold feel free to pull and push your project 👍🏼
