### ISSUE TITLE
CloudFormation template has wrong value for "Effect" for AuthRole and UnauthRole

### ISSUE THREAD

**Issue by paddlefish** [aws-amplify/amplify-cli#6022]
**Describe the bug**
In an amplify project, if you use the CloudFormation drift detection it will find two differences: in the UnauthRole and AuthRole.  The created roles will have `"Effect": "Allow",` but the template will have `"Effect": "Deny",`.

The cloud formation template should accurately describe the desired state of the deployed system.  In this case, the roles that were created are correct ("Effect": "Allow",) but for some reason the cloud formation template has the wrong value ("Effect": "Deny",).  This might lead a developer to think they need to "fix" their Auth and Unauth roles; however, if they do so, they'll break their cloud stack. Furthermore, it complicates repairing a broken environment, as you cannot simply make an environment match the cloud formation template to make it correct.

**Amplify CLI Version**
amplify --version 
4.36.2

**To Reproduce**
Create a new amplify project and push an environment.
Open the CloudFormation console and select the template corresponding to your environment.
Select "detect drift" and then view the drift results.

**Expected behavior**
The newly created stack would not have any drift.

**Screenshots**
![Screen Shot 2020-12-01 at 9 52 09 AM](https://user-images.githubusercontent.com/535096/100764421-ee02e480-33bb-11eb-8006-9b0ed52d634b.png)

![Screen Shot 2020-12-01 at 9 51 57 AM](https://user-images.githubusercontent.com/535096/100764440-f2c79880-33bb-11eb-98d6-d9c7bc6abbbf.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 (19H15)
 - Node Version. v14.9.0

**Comment by ammarkarachi** [comment]
@paddlefish This something I haven't experienced before can you check your cloudtrail and see how these roles have been modified?

**Comment by paddlefish** [comment]
> @paddlefish This something I haven't experienced before can you check your cloudtrail and see how these roles have been modified?

@ammarkarachi I didn't know about cloudtrail but i'm learning new things all the time.  Here appears to be the event that creates one of the two roles:

<img width="1776" alt="Screen Shot 2020-12-01 at 11 11 34 PM" src="https://user-images.githubusercontent.com/535096/100832032-a2d4ea00-342c-11eb-8bb2-f07a9305a537.png">

And here is an update that happened a little while later that changed the Effect from Deny to Allow.

<img width="1792" alt="Screen Shot 2020-12-01 at 11 14 25 PM" src="https://user-images.githubusercontent.com/535096/100832043-acf6e880-342c-11eb-8709-ff5d01c3e0a1.png">

**Comment by ammarkarachi** [comment]
@paddlefish To clarify do you init a new environment in an existing project and what categories exist in the project before you init/push?

**Comment by paddlefish** [comment]
@ammarkarachi : after amplify init, but before push, the auth and unauth resources are created and also the cloud formation template. At this point they agree: DENY

![Screen Shot 2020-12-08 at 8 53 55 AM](https://user-images.githubusercontent.com/535096/101516693-667e1e00-3945-11eb-9c0b-cdca6f3527a3.png)

![Screen Shot 2020-12-08 at 8 54 55 AM](https://user-images.githubusercontent.com/535096/101516714-6d0c9580-3945-11eb-9946-d35577e20366.png)

Then amplify add auth

Then amplify push

Now the roles have changed to ALLOW, but the cloud formation template still says DENY.

![Screen Shot 2020-12-08 at 8 59 25 AM](https://user-images.githubusercontent.com/535096/101516978-c674c480-3945-11eb-9342-202649396819.png)

![Screen Shot 2020-12-08 at 8 58 52 AM](https://user-images.githubusercontent.com/535096/101516994-cb397880-3945-11eb-9c38-890e37ed96c9.png)

**Comment by kaustavghosh06** [comment]
@paddlefish You're seeing this since we use a custom lambda resource to update the auth and unuath role and change the effect to "Allow" when you have auth enabled in your Amplify project. Is there a functionality issue that you're seeing with this in your app?

**Comment by paddlefish** [comment]
@kaustavghosh06 : The reason it is important is because Amplify isn't perfect.  Sometimes an `amplify push` will fail, for example if two GIS's are modified at once.  Or if a circular dependency is inserted, causing cloud formation deployment to fail. And, sadly, sometimes CloudFormation fails when trying to rollback a failed deployment. Thus you're left with an environment that's partially pushed, and partially rolled back. I understand that you might argue that failures like these are bugs, and so handling the resulting corrupted environment isn't important. But I look at it as: How can I know that my production environment can be maintained? There should be a way recover from a disastrous `amplify push`.

In such a situation the only recovery I've found to work is to manually update AWS services using the console so they are "good".  But figuring out what is "good" is very hard if you can't trust the CloudFormation template.

If you must use a lambda, what would it hurt to *also* update the cloudformation template so that it matches the change made by the lambda? This way if you find yourself with a malfunctioning environment, you can use the CF Drift Detect capability to guide repairing the environment.

As an aside... why are you using a lambda to update roles instead of doing it via CloudFormation?
