### ISSUE TITLE
Error creating UserPoolClientLambda during amplify push

### ISSUE THREAD

**Issue by AshkanHovold** [aws-amplify/amplify-cli#6025]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Following resources failed

Resource Name: UserPoolClientLambda (AWS::Lambda::Function)
Event Type: create
Reason: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 3017a11d-3929-4c64-82d1-bd74e4e1d595; Proxy: null)

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

**Amplify CLI Version**
4.36.2

**To Reproduce**

1. I run "amplify env add"
2. Do you want to use an existing environment? No
3. Enter a name for the environment: newdev
4. Do you want to use an AWS profile? Yes
succesfully installs everything so far. 
5. I run "amplify status"
It displays:
Current Environment: newenv

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Auth     | omitted   | Create    | awscloudformation |
| Hosting  | S3AndCloudFront | Create    | awscloudformation |
| Api      | [omitted]dynamoapi    | Create    | awscloudformation |

6. I run "amplify push"

Push fails and error above is displayed

**Expected behavior**
amplify push to succeed

**Screenshots**
![image](https://user-images.githubusercontent.com/32637977/100787235-9c864400-3413-11eb-8741-947c3065787b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v10.19.0

**Comment by ammarkarachi** [comment]
Hi @AshkanHovold, I think we started using a newer runtime for the lambdas, with what amplify CLI version did you create the lambda triggers?

**Comment by AshkanHovold** [comment]
4.36.2 is what I used yesterday when I tried to create a new environment

But if you are asking what I originally used first time, I dont know. This was first created more then a year ago. What should I do to update to newer runtime for the lambdas?

**Comment by AshkanHovold** [comment]
Just updated to 4.37.1 and still the same error. If I understand correctly, the lambda it is trying to create is something aws appsync is using, I have no control over this lambda being created, or do I? Can I change the version it uses somehow?

**Comment by AshkanHovold** [comment]
Ah here I found something: -cloudformation-template.yml

at the top it says:
AWSTemplateFormatVersion: 2010-09-09
in this file it says
Runtime: nodejs8.10

Should this be updated to higher version of node? (nodejs12.x?)

**Comment by ammarkarachi** [comment]
Hi @AshkanHovold, Sorry for the delay in getting back to you. We have a guide to help you through migrating to the latest version here: https://docs.amplify.aws/cli/migration/lambda-node-version-update.

**Comment by AshkanHovold** [comment]
Hello, thank you! I have tried this and I was able to create a new environment now. You can mark this as solved!

**Comment by AshkanHovold** [comment]
By doing as @ammarkarachi suggested in the link my problem was solved.
