### ISSUE TITLE
GraphQL Subscription parameters are ignored when mocking

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6026]
**Describe the bug**
When subscribing to a Subscription with parameters, specified parameters are ignored, and events are pushed out to all clients regardless of what was specified in the parameters. This is when using `amplify mock` to test locally. 

**Amplify CLI Version**
4.37.0

**To Reproduce**
Here is an example GraphQL schema:

```graphql
type FooList {
  optID: String!
  foos: [Foo!]!
}

type Mutation {
  triggerFooChanged(optID: String!): FooList
}

type Subscription {
  onFooChanged(optID: String!): FooList @aws_subscribe(mutations: ["triggerFooChanged"])
}
```

After subscribing to `onFooChanged` using `optID = 'something'` I'm getting all the events coming through, not just the ones where `optID = 'something'`.
For example, calling the mutation `triggerFooChanged(optID: 123)` returns `{optID: 123, foos: []}`. However, someone subscribed to `onFooChanged(optID: 333)` also gets this data.

**Expected behavior**
Clients subscribed to a specific `optID` should only get events with that `optID`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.20.0

**Comment by half2me** [comment]
Also, the [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) isn't very clear on how the subscription parameters filter mutations. Is it filtering on the returned data? Is it filtering based on the mutation argument? Both could be true looking at the given example.

**Comment by dabit3** [comment]
re: Issue -> I've had a few customers reach out about this, only happens when running `amplify mock` like @half2me suggested cc @renebrandel @manueliglesias @elorzafe 

re: docs cc @awsed for filtered subscriptions, maybe we can improve some messaging here going over importance of return values from mutations.

**Comment by half2me** [comment]
Closing, as duplicate of #4725
