### ISSUE TITLE
Can't push if I have any editor or files open

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6028]
**Describe the bug**

When trying to push I get an error about how amplify can't change a file or folder as I have it open in VSCode. 

Trouble is often I don't have the mentioned file open in VSCode yet the only way I've found to make it happy and allow a push is to close VSCode. This is far from ideal and I'm at a lose as to why it would be doing it! I could understand if I was half way through a edit of a config file or something but I'm not and I can't see why VSCode would keep a lock/handle to the files mentioned?

**Amplify CLI Version**

v4.32

**To Reproduce**

Tricky...for me currently I've got 10 files open in VSCode. One of which is my schema.graphql file (this is a new one for me for it to complain about, normally its one of a number of other files). Then in a console window I do a `amplify push --yes` and thats when it blows up half way through with the attached error.

I've got "yarn start" running too at the time, not sure if that could be part of it? The error goes away if I close VSCode though, I don't need to close my `yarn start` to clear it so don't think its an issue.

**Expected behavior**

Having the schema file (or any of my custom code files) open shouldn't stop amplify doing a push, it should only be copying those and not renaming or deleting them.

This seems to be a newish behaviour (noticed it the last few weeks) and I'm not sure how to really fix it. It could be an extension, or VSCode itself? 

**Screenshots**

![image](https://user-images.githubusercontent.com/1674590/100797511-29cc9700-341a-11eb-8e85-caec0b0f218b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v12.18.4

**Additional context**

**Comment by ammarkarachi** [comment]
@PeteDuncanson Is VSCode running in Administrator mode by any chance?

**Comment by PeteDuncanson** [comment]
I don't think so. Should it be?

**Comment by PeteDuncanson** [comment]
I'll run it in admin mode today and see how I go and report back

**Comment by PeteDuncanson** [comment]
Nope, running it in admin or normal mode is making no difference :(

**Comment by PeteDuncanson** [comment]
More on this, managed to capture a screenshot of it complaining about being unable to create a folder. I've not got anything open in VSCode that is in that folder or even near it. Yet if I close VSCode then this error goes away. Very weird.

![image](https://user-images.githubusercontent.com/1674590/101000276-926c5e80-3555-11eb-8624-21f4d483caf8.png)

**Comment by PeteDuncanson** [comment]
Today I've narrowed down the issue to be when I have my schema.graphql file open while doing a push that has API changes in it. If I close then file but leave VSCode open I can then push.

**Comment by PeteDuncanson** [comment]
Oh another update. Seems closing schema doesn't work the first time, but does on a repeat go.

So this is current steps:

* edit the schema
* close the schema
* run `amplify push --yes`
* get the EPROM error about schema.graphql
* run `ampligy push --yes` again and this time it will work

Not sure if there is a lag between it closing and being released? Will test some more and see if I spot a pattern.

**Comment by PeteDuncanson** [comment]
So its happening when it tries to compile the GraphQL schema, that is when it complains that it can't write to my schema file. Annoyingly this only pops up a minute or two into the deploy yet it fails every time on the first go. So I'm losing 1-2 minutes every time I make a change. This is an absolute motivation killer and destroying any attempts to get into a developer flow.

![image](https://user-images.githubusercontent.com/1674590/101364574-a20fde00-389a-11eb-8d10-0e2457d8c84c.png)

**Comment by attilah** [comment]
@PeteDuncanson it seems to be a local issue specific to your environment. Amplify is running in the same security context as your terminal window and we are using standard NodeJS file system APIs to access the files. As some troubleshooting tips could you please try the following in the same terminal window where the CLI commands are failing:
- Try `mkdir` the very same directory that the CLI tries to make
- `type schema.graphql` and see if you succeed

- Are you doing local or remote development with VS Code?
- Is WSL2 involved anyhow in your workflow?

In our team we are using Windows and Mac machines as well and VS Code is our most common editor and never saw any file locking issues until now.

**Comment by PeteDuncanson** [comment]
This just hit me again tonight. Closing the schema file makes it go away and I can push. Oddly I only had the file open to look at (I'd not edited it at all) and that was enough. Had a few computer restarts since the last time so no idea what that is.

**Comment by PeteDuncanson** [comment]
@attilah I tried making a directory, no problem, type schema no problem. I'm developing locally, still got yarn start running (its a create-react-app) when I push if thats of note. I've no idea what WSL1 or 2 is :(

**Comment by PeteDuncanson** [comment]
I think this one is fixed as I've not seen it for a while. Doing some thinking about why and all we can come up with is I cleared out node_modules to fix https://github.com/aws-amplify/amplify-cli/issues/6369#issuecomment-759058814 and think that cleared this error too. 

As a result I think its now working and if anyone else has the same trouble they have a fix they can try. Thanks.

**Comment by PeteDuncanson** [comment]
This just happened again, if I close schema.json file in VSCode I can push. Weird.

**Comment by PeteDuncanson** [comment]
This just hit me again today. I'm on a totally new laptop, fresh installs and checkouts of everything.

If it helps I'm using Window Terminal to do all my CLI stuff.
