### ISSUE TITLE
amplify-app needs to verify @aws-amplify/cli version

### ISSUE THREAD

**Issue by ktmdan** [aws-amplify/amplify-cli#6039]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Error running npx amplify-app@latest, this command will use the global version of @aws-amplify/cli which has breaking changes bypassing the questions when running init.

**Amplify CLI Version**
Issue with prior to amplify-cli 4.37

**To Reproduce**
Install prior version of cli into global cache then run npx amplify-app@latest this will fail asking the question to type in environment name

**Expected behavior**
This should check the minimum version of the cli installed an print an error if its unsupported.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. v14.7.0

**Comment by ammarkarachi** [comment]
@ktmdan We released a fix for this in Amplify CLI version 4.38.0
