### ISSUE TITLE
Patterns for managing multiple clients that use the same backend

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#604]
** Which Category is your question related to? **
Core

** What AWS Services are you utilizing? **
API (appsync), Auth, Storage, Cloudfront (outside the Amplify ecosystem)

** Provide additional details e.g. code snippets **
I have multiple clients (typescript admin webapp, typescript customer webapp, possibly android app...?) and I'm finding it difficult to keep Amplify configuration in sync across multiple git repos. Is it reasonable to use the Amplify CLI in its own repo and export packages as sdks?

As far as I can tell, there is no magic happening that requires Amplify to exist at the root of the client source code, is that correct? I think the only feature that might be affected by this pattern is `amplify publish` but that's acceptable.

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks, this is a duplicate request as #582. It's in our backlog.

**Comment by ajhool** [comment]
Thanks for the response, I believe that #582 partially addresses this issue, but this issue concerns a broader code management concept than just multiple frontend framework/languages support. I can create a separate issue that hones in on the external versioning pattern if that would be helpful.

I'm curious about this code pattern even for a single-frontend use-case but it becomes more critical when there are multiple frontends (even if all of those frontends are, say, typescript).

**Comment by UnleashedMind** [comment]
The amplify cli combined the amplify libraries try to enable the developers to develop the frontend and the backend in the same codebase. 
The cli has frontend handlers that generate the appropriate configuration files for different types of project. For example, for javascript projects,  it the `aws-exports.js` file, to be used by the amplify js library; and for android, it's the `awsconfiguration.json` file, to be used by the native library. These configuration files contain information of the backend resources. 
This setup is to speed up the backend resource development and testing, and the 'hook up' between the frontend and the backend of the project.

**Comment by kaustavghosh06** [comment]
@ajhool The CLI does some codegen for your frontend code which you might not be able to leverage  if you maintain or use the amplify cli in it's own repo.

**Comment by ajhool** [comment]
Is the codegen output simply `aws-exports.js` and `API.ts`? My plan was to export those two items from the amplify cli repo or module. I believe there is also some amplify meta codegen (like altering .gitignore), but that would belong in the aws amplify repo.

**Comment by kaustavghosh06** [comment]
@ajhool Yes, you're correct about the codegen behavior above.
