### ISSUE TITLE
Push of fresh checkout will break lambda layers

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#6043]
**Describe the bug**
If you pull the repository (say in a CI process) and then try an `amplify push` after you have configured the env (amplify init/env checkout), then node_modules folder will be empty in any lambda layers as the folder is ignored by .gitignore.

Note: this does not happen on functions so the push must be running an npm install on the functions folder but is skipping the `lib/nodejs` folder in the lambda layer

you will get an error like the following in the cloudwatch logs
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'graphql-tag'\nRequire stack:\n- /opt/graphql-request.js\n- /opt/graphql/getSection.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'graphql-tag'",
        "Require stack:",
        "- /opt/graphql-request.js",
        "- /opt/graphql/getSection.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Amplify CLI Version**
4.35.0

**To Reproduce**
Pull any repo with node_modules in .gitignore and a lambda layer configured on a lambda function

try to run a function which relies on code in this node_modules folder within the lambda layer

**Expected behavior**
npm install to have been run to install packages and function to work correctly instead of blowing up with missing node packages 

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.4.0

**Additional context**
Workaround is obviously add a step to CI to cover this npm install from the folder but the same can happen if an unexpecting developer pushes from a fresh machine too which can cause breaking changes to an environment

**Comment by SwaySway** [comment]
@jcbdev 
Lambda layers are expected to contain static content when deploying. 
Docs: https://docs.amplify.aws/cli/function/layers

Marking this as a potential enhancement to review with team.

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!
