### ISSUE TITLE
Unusuable arrow key functionality for selecting GraphQL or REST when issuing amplify add api

### ISSUE THREAD

**Issue by Fish-In-A-Suit** [aws-amplify/amplify-cli#6048]
**Introductory data**

- Amplify CLI version: 4.37.1
- I have already successfully issues `amplify init`

**Problem description**
I am following [this](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react) tutorial, which covers connecting API and the database to the app.  When issuing the command `amplify add api` in the console windows, I am first greeted by an option to select between GraphQL and REST. It says that I should use arrow keys, but doing so doesn't change the arrow key pointing to GraphQL. Then, when I press enter, I get an error: `"There was an error adding the API resource"`

This is the image before pressing enter.
![image](https://user-images.githubusercontent.com/37004357/101015024-0cf1aa00-3567-11eb-8f41-e4bc3f429c08.png)
And this is after pressing enter.
![image](https://user-images.githubusercontent.com/37004357/101015055-17ac3f00-3567-11eb-8d98-df35a6c351bc.png)

Please, let me know what I am doing wrong and sincerely thank you for the time taken!

Best regards.

**Comment by SwaySway** [comment]
@Fish-In-A-Suit Are you using the default git bash? If so does not support an interactive terminal.
Source: https://github.com/vuejs/vue-cli/issues/2117
Closing this issue as it's not related to the CLI.
