### ISSUE TITLE
Project appears to be in a bad state. How to purge all Amplify generated files to escape bad state.

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-cli#605]
** Current behavior: **
```
amplify init
// edit backend/api/myapi/schema.graphql
amplify status --> API (Update), Auth (No Change), Storage (No Change)
amplify push --> Everything updates correctly, no errors.
amplify status --> API (Update), Auth (No Change), Storage (No Change)

```
expected behavior - everything the same as above except the final step should be:

```
amplify status --> API (No Change), Auth (No Change), Storage (No Change)
```

** What I've tried **
1. Removing the following files
```
amplify/\#current-cloud-backend
amplify/backend/amplify-meta.json
src/aws-exports.js
aws-exports.js
awsconfiguration.json
```
2. amplify init
3. amplify status // (API status is: Update)
3. amplify push // (succeeds)
4. amplify status // (API status is: Update)

** Feature Request **
This appears to be a bug in Amplify, but I'm not sure how to reproduce it. I would like to reset Amplify to an initial state (without losing my API, Auth, or Storage configuration), which files do I need to remove to do so?

A command like `amplify clean` would be useful for when things go wrong.

**Comment by UnleashedMind** [comment]
Thanks we are investigating the issue.

**Comment by UnleashedMind** [comment]
I was not able to reproduce your issue with the latest version of the multienv version
0.2.1-multienv.14

Could you get the latest and see if the issue is still there?

**Comment by kaustavghosh06** [comment]
@ajhool  Could you try using `amplify env pull --restore`? This would basically restore your local backend with whatever is there in the cloud. (i.e in your current-cloud-backend folder).

**Comment by ajhool** [comment]
`amplify env pull --restore` has corrected the `amplify status` response (Operation = No Change for each service) and does not appear to have introduced any unexpected file changes, I will update if I find surprises. Thanks!

**Comment by joemsak** [comment]
My ampify status is still showing an expired / deleted GraphQL API Key after doing the env pull --restore command - I can't do a push because it keeps putting the old API key into the #current-cloud-backend amplify-meta file. Any help?

**Comment by bcs-gbl** [comment]
> 
> 
> My ampify status is still showing an expired / deleted GraphQL API Key after doing the env pull --restore command - I can't do a push because it keeps putting the old API key into the #current-cloud-backend amplify-meta file. Any help?

Search your api key on Console and paste there. Maybe it helps
