### ISSUE TITLE
When adding an additional key to a model the order that key matters

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6050]
**Describe the bug**

Given a deployed model that already has keys on it, if I add a new key to the schema for that model it has to be after the existing ones. If I add it before the last one then it fails with this error:

"Attempting to mutate more than 1 global secondary index at the same time on the AddressTable table in the Address stack.
An error occurred during the push operation: Attempting to mutate more than 1 global secondary index at the same time on the AddressTable table in the Address stack."

**Amplify CLI Version**

v4.37.1

**To Reproduce**

Given this schema:

```
type TestModel @model
 @key(name: "byField1", fields: ["field1"], queryField: "modelByField1")
 @key(name: "byField2", fields: ["field2"], queryField: "modelByField2")
 {
  id: ID!
  field1: string!
  field2: string!
  field3: string!
}
```

Deploy it via `amplify push`.

Then add a new key in the middle of the existing two:

```
type TestModel @model
 @key(name: "byField1", fields: ["field1"], queryField: "modelByField1")
 @key(name: "byField3", fields: ["field3"], queryField: "modelByField3")
 @key(name: "byField2", fields: ["field2"], queryField: "modelByField2")
 {
  id: ID!
  field1: string!
  field2: string!
  field3: string!
}
```

Try to `amplify push` again and you will get an error about trying to do multiple GIS changes to the TestModel model. 

Change the order of the new key to be after the exisiting ones:

```
type TestModel @model
 @key(name: "byField1", fields: ["field1"], queryField: "modelByField1")
 @key(name: "byField2", fields: ["field2"], queryField: "modelByField2")
 @key(name: "byField3", fields: ["field3"], queryField: "modelByField3")
 {
  id: ID!
  field1: string!
  field2: string!
  field3: string!
}
```

Try to push again and this time it will go up just find, your new key will have been added.

**Expected behavior**

I'd expect the order to not matter. As it is the current error message causes much confusion

"I'm only adding one key, why is it saying I'm added multiple?"

I suspect its just working its way through an array and trying to remove the key that is now in index 1 as its not the key its expecting. Instead I think it should sort that array or check if it already has a key elsewhere in the array?

**Screenshots**

![image](https://user-images.githubusercontent.com/1674590/101025697-d8352100-356d-11eb-9f02-a033571bd50d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.18

**Additional context**

**Comment by SwaySway** [comment]
I'm not able to repro this with version `4.37.1`. The diff check that is happening here is looking to see if more than GSI is added on the same table on an update. If the order is changed it would be considered an edit which is not caught by the diff check.

The provided in error is similar to that of #6013, closing this issue to move the discussion there. Perhaps there is something that is different in the provided schema which is causing this error. If so you can email it to us amplify-cli@amazon.com if the information is sensitive.

Closing in favor of this duplicate: https://github.com/aws-amplify/amplify-cli/issues/6013

**Comment by PeteDuncanson** [comment]
@SwaySway sent the schema over in an email, thanks.
