### ISSUE TITLE
Add sa-east-1 to Specify the AWS Region in amplify configure

### ISSUE THREAD

**Issue by nicolas-carlini** [aws-amplify/amplify-cli#6051]
I need to build a front with vue in amplify in the sa-east-1 region but the configuration is not there

I need the region of sa-east-1 to be added in the configuration

**Comment by kaustavghosh06** [comment]
@nicolas-carlini A lot of the resources which Amplify provisions in the categories aren't available in sa-east-1 region yet - hence it's not an available option yet. We'll be adding more regions as and when all the dependencies are available in that region. Here's a list of regions we support in the CLI today:

  ```
'us-east-1': 'US East (N. Virginia)',
  'us-east-2': 'US East (Ohio)',
  'us-west-2': 'US West (Oregon)',
  'eu-west-1': 'EU (Ireland)',
  'eu-west-2': 'EU (London)',
  'eu-central-1': 'EU (Frankfurt)',
  'ap-northeast-1': 'Asia Pacific (Tokyo)',
  'ap-northeast-2': 'Asia Pacific (Seoul)',
  'ap-southeast-1': 'Asia Pacific (Singapore)',
  'ap-southeast-2': 'Asia Pacific (Sydney)',
  'ap-south-1': 'Asia Pacific (Mumbai)',
  'ca-central-1': 'Canada (Central)',

```

**Comment by 0xrfsd** [comment]
:( =?> [...]

**Comment by JohnnyHandy** [comment]
Well got disappointed today... I currently have an entire structure on sa-east 1 (lambdas, dynamodb, s3) and when I was about to add auth to my gatsby application, I find that there is no sa-east -1 :(

**Comment by ZandreeTresvalles** [comment]
> Well got disappointed today... I currently have an entire structure on sa-east 1 (lambdas, dynamodb, s3) and when I was about to add auth to my gatsby application, I find that there is no sa-east -1 :(

Same here... My structure is at ap-east-1

**Comment by ZandreeTresvalles** [comment]
@kaustavghosh06 Hi, should we just migrate to a different region? is there a quick way to migrate? thank you in advance.
