### ISSUE TITLE
Amplify doesn't generate Swift models

### ISSUE THREAD

**Issue by KatsuShooter** [aws-amplify/amplify-cli#6052]
**Describe the bug**
Following the guide, I added script in build phase:
`"${PODS_ROOT}/AmplifyTools/amplify-tools.sh"`
But after building it doesn't create AmplifyConfig and AmplifyModels group
**Amplify CLI Version**
4.32.0

**Expected behavior**
It should create AmplifyModels and AmplfiyConfig groups

**Aditional information**
Build logs:
Found amplify-cli version: (4.32.0), Required: >= (4.22.0)
Found amplify-app version: (2.20.0), Required: >= (2.17.1)
  Using: npx amplify-app@latest
modelgen is set to true, generating Swift models from schema.graphql...

GraphQL schema compiled successfully.

```
modelgen is set to true, generating Swift models from schema.graphql...
GraphQL schema compiled successfully.



Edit your schema at /Users/katsushooter/Library/Mobile Documents/com~apple~CloudDocs/Documents/Projects/DentistCalendar/amplify/backend/api/dentistcalendar/schema.graphql or place .graphql files in a directory at /Users/katsushooter/Library/Mobile Documents/com~apple~CloudDocs/Documents/Projects/DentistCalendar/amplify/backend/api/dentistcalendar/schema
Successfully generated models. Generated models can be found /Users/katsushooter/Library/Mobile Documents/com~apple~CloudDocs/Documents/Projects/DentistCalendar/app/src/main/java
npx: installed 128 in 11.839s
✅ Found Amplify CLI version 4.32.0
🎸 Creating base Amplify project
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? (Y/n) [52D[52C
✅ Successfully created base Amplify Project
```
**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.18.4

**Comment by kaustavghosh06** [comment]
@KatsuShooter Can you check if you see any files out here - /Users/katsushooter/Library/Mobile Documents/com~apple~CloudDocs/Documents/Projects/DentistCalendar/app/src/main/java ?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
