### ISSUE TITLE
 feature branch team workflow with multiple environments  /Using multiple dev machines / gitignore

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-cli#6062]
I'm using devcontainers and vscode on a nextjs and amplify project started on my mac laptop.

Trying to develop on my windows desktop, I'm running into  ` /.config/local-env-info.json' does not exist.` Same error when running `amplify configure` or `amplify configure project`. It's because I have it in my .gitgnore .

What are the amplify files or directories that should be in gitignore? Does my workflow on multiple machines demand me take ` /.config/local-env-info.json' out of .gitignore? 

What is the best way to handle a workflow for a developer to use multiple machines, as well as working with additional developers?

**Comment by ammarkarachi** [comment]
@amlcodes It looks this is a bug on our end, can you pull/init an env and try it out?

**Comment by amlcodes** [comment]
ahhh, yeah just had to pull again on my machine. That makes sense, I guess I expected to configure to setup for some reason. Makes sense that I would pull. Doesn't seem like a bug IMO, user error.

On teams - I guess you would have an Organization with AWS accounts/users in Org Units with the permissions needed? And then each person would just amplify pull... right?

**Comment by ammarkarachi** [comment]
>On teams - I guess you would have an Organization with AWS accounts/users in Org Units with the permissions needed? And then each person would just amplify pull... right?

That would be right

>On .gitignore - is there an official source of truth on this? I'm seeing conflicting ideas on amplify/team-provider-info.json ?

Before version 4.32.1 the CLI used to write hostedUIProviderCreds to team-provider-info, in the latest version those values are managed from `~/.aws/amplify/deployment-secrets.json`. There would be no harm exposing your team-provider-info.json in a source repository anymore
