### ISSUE TITLE
$util.validate does not return a message

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6068]
**Describe the bug**
When using `$util.validate()` in a VTL resolver, a message is never returned.
According to the docs: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html
```vtl
$util.validate(boolean, String) : void
```
"_If the condition is false, throw a CustomTemplateException with the specified message._"

But in my case, the `String` argument is ignored.

**Amplify CLI Version**
4.37.1

**To Reproduce**
Run `amplify mock`
Use `$util.validate(false, "foo")` in a VTL resolver, it will throw an error with an empty message .
I also tried: `$util.validate(false, "foo", "bar")`
Which returns `bar` correctly for the type, but doesn't include `foo` as the message.

**Expected behavior**
The 2nd argument should be used as the error message.

**Screenshots**
Example output for `$util.validate(false, "foo", "bar")`
<img width="173" alt="Screenshot 2020-12-04 at 22 44 52" src="https://user-images.githubusercontent.com/6759894/101217926-74504c80-3682-11eb-8e02-8f0f09e210f5.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.20.0

**Comment by attilah** [comment]
AppSync returns this error info:
```json
{
  "data": {
    "getFoo": null
  },
  "errors": [
    {
      "path": [
        "getFoo"
      ],
      "data": null,
      "errorType": "b",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "a"
    }
  ]
}
```

Velocity template engine [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-velocity-template/src/compile/references.js#L292) is catching the thrown error and overwriting the message property, this needs some refactor to preserve the incoming message.
