### ISSUE TITLE
Simplify lambda environment variables

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#6073]
I'm wondering why we are adding individual variables for endpoints etc. to each lambda. We get apiendpoints and adminendpoints and s3endpoints. It all seems a bit excessive and frustrating to use. 

I'm wondering why we don't just have an amplifyconfig variable that is essentially the awsconfig.js file in json format...this way we can just pass it to Amplify.config and everything is ready to go...

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.
