### ISSUE TITLE
Proper Support for SES Category

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#6076]
**Is your feature request related to a problem? Please describe.**
We have a need to deploy SES email templates as part of our app. The solution described at https://github.com/aws-amplify/amplify-cli/issues/80#issuecomment-492428916 works for simple email cases but not larger html emails. 

The problem is cloudformation has a limit of 4096 bytes (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html). A simple html email can be about 44kb in size so we can't inline it in the cloudformation template. So we then have to deploy that html email to s3 and refer to that in cloudformation which is not supported in amplify cli without a plugin. 

**Describe the solution you'd like**
SES category in amplify cli that lets us deploy emails templates without having me to think about how to do it. 

**Describe alternatives you've considered**
For now we created our own script via aws cli to deploy SES email templates.

**Comment by attilah** [comment]
@hisham by defining your own custom CloudFormation stack and referencing the HTML template from S3 is fully supported, take a look at our docs on how to do it: https://docs.amplify.aws/cli/usage/customcf

I cc our PM: @renebrandel to be aware of this requirement but closing the issues as the question was answered. If you run into problems defining your custom stack feel free to open a new issue regarding that.

**Comment by hisham** [comment]
yes but how would I upload the html templates to s3? Seems like with the current setup I would have to do this manually / out of band from amplify cli. It wouldn't be uploaded by amplify cli itself.
