### ISSUE TITLE
Resource name is non alphanumeric when pushing functions with dashes

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#6077]
Similar issue: #3163 (but thats for analytics)

**Describe the bug**
CLI permits users to add dashes to their resouce name with `amplify function add`. However upon pushing, it fails.

**Amplify CLI Version**
4.37.0

**To Reproduce**
1. `amplify function add`
2. resource name: `add-dash-function`
3. `amplify push`

**Expected behavior**
CLI should block user from adding dashes as their resource name during the creation of a function.

Error:
```
Template format error: Resource name functiongetDataFrom-SIRIM is non alphanumeric.
An error occurred during the push operation: Template format error: Resource name functiongetDataFrom-SIRIM is non alphanumeric.
```
ps: On error line 1, can we please have a space added between the function name and the word 'function'?

**Comment by nubpro** [comment]
duplicate of #6064

**Comment by ammarkarachi** [comment]
> duplicate of #6064

Closing of in favor ^
