### ISSUE TITLE
Cloudfront response codes template

### ISSUE THREAD

**Issue by timoteialbu** [aws-amplify/amplify-cli#608]
**Describe the bug**
If you take a look at this file [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-hosting/lib/S3AndCloudFront/template.json#L142), you'll notice that the template defines there error pages with `Response Code`s of 200. I believe that is wrong. One reason for that is from an SEO [perspective](https://moz.com/learn/seo/http-status-codes). If a 404 returns a 200 code, it will end up being crawled and indexed by web crawlers, and subsequently end up in search results. There are also other instances where you build an API and you would want to return the proper error code when something is not working and not a 200 code.

**To Reproduce**
Go here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-hosting/lib/S3AndCloudFront/template.json#L142

I ran into this issue when I was adding a WAF (Web Application Firewall) to my cloudfront distribution. I tried blocking my IP, but when I was hitting the site I kept getting HTTP 200s back.

**Expected behavior**
I expect error pages should come back with the proper error code.

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS is irrelevant, but I did run tests on Chrome 70 and Firefox 64.

**Smartphone (please complete the following information):**
IPhone X - Safari

**Additional context**
Open PR 
 - master: https://github.com/aws-amplify/amplify-cli/pull/609
 - multienv: https://github.com/aws-amplify/amplify-cli/pull/610

**Comment by UnleashedMind** [comment]
That's just the default configuration, we don't expect it to be suitable for all different scenarios, the cli has a command `amplify hosting configure`, which can be used to add/remove/update the CustomErrorResponses.
