### ISSUE TITLE
amplify configure is a mysterious command

### ISSUE THREAD

**Issue by r0zar** [aws-amplify/amplify-cli#6081]
**Describe the bug**
Running `amplify configure` with various arguments exits silently.
Additionally, there are certain hidden commands, like `amplify configure project`.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
`4.37.1`

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Run a few commands:
```
❯ amplify configure help
❯ amplify configure projecasda
❯ amplify configure project
```

**Expected behavior**
Output a clear explanation of what amplify configure does, all the commands it has, all the arguments they support, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/4655474/101266452-a01c1280-3714-11eb-9c7b-2a27b81653f2.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu`
 - Node Version. You can use `node -v` to check the node version on your system
`v12.18.3`

**Additional context**
IMO, the whole CLI should provide basic help and definitions when invalid commands are detected.
I'd suggest looking at a holistic solution for this. I'm sure a 3rd party package could help.

-rozar

**Comment by kaustavghosh06** [comment]
@r0zar Currently we don't support sub-command level help commands, but if you're stuck at what `amplify configure` is, I would highly recommend looking up our docs - https://docs.amplify.aws/start/getting-started/installation/q/integration/js#option-1-watch-the-video-guide. `amplify configure` is literally the firs thing we talk about.
Also, checkout `amplify help` command to know more about configure. If you think the description doesn't make a lot of sense, we can work on the wordings.
