### ISSUE TITLE
Cant remove API after removing all dependencies

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#6089]
**Describe the bug**
I want to remove my existing api with `amplify remove api`. It's true that some of functions are using the API (Appsync and as a DDB storage). Therefore, I removed all related resources to the API from my functions.
After doing that, I tried the remove the api again.
I get the same error:
`Resource cannot be removed because it has a dependency on another resource`

**Amplify CLI Version**
4.37.0

**To Reproduce**
1. amplify add api.
2. configure schema.
3. amplify add function > configure resources > enable api and storage > choose the model you've created.
4. amplify push
5. amplify update function > configure resources > unselect api and storage
6. amplify remove api
7. Error: `Resource cannot be removed because it has a dependency on another resource`

**Expected behavior**
After removing the depencies, `ampify remove api` should just work!

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Is there a way to force delete the API perhaps with `-force` irregardless of dependencies?
The purpose is so that I can drop the entire table and recreate them in order to truncate my tables.

**Comment by ammarkarachi** [comment]
@nubpro Can you push after updating the function and then try removing the API?

**Comment by nubpro** [comment]
> @nubpro Can you push after updating the function and then try removing the API?

I remember trying that, and it still didnt work out. So are you saying you actually need to push first?

**Comment by OsenLiu** [comment]
I have the same issue.  My amplify version is 4.39 & 4.34.
1. add the storage access to the function
2. remove storage access to the function
3. remove storage with amplify storage remove
The cli always say "Resource cannot be removed because it has a dependency on another resource"

**Comment by OsenLiu** [comment]
> I have the same issue. My amplify version is 4.39 & 4.34.
> 
> 1. add the storage access to the function
> 2. remove storage access to the function
> 3. remove storage with amplify storage remove
>    The cli always say "Resource cannot be removed because it has a dependency on another resource"

I have to manually remove the storage in amplify-meta file and then can remove the storage.

**Comment by nubpro** [comment]
@ammarkarachi dont close this

**Comment by ammarkarachi** [comment]
@nubpro Sorry on the delay will get back to you on this

**Comment by ammarkarachi** [comment]
@nubpro can you confirm this with latest version. I tried it out and I wasn't able to reproduce it.

**Comment by nubpro** [comment]
I switched my pc and tried to repro a new project, running on version 4.41.0, I cant reproduce it on my end anymore. Unfortunately I don't have my previous project with me.

@OsenLiu
Can you try with latest Amplify?
