### ISSUE TITLE
Unclear how to use GraphQL transformer

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-cli#61]
https://github.com/aws-amplify/amplify-cli/tree/master/packages/graphql-transformer-core

I feel this page could use some clarification. How do we get our project to recognize the GraphQL SDL file? What do we name it and where do we put it? What series of commands in the CLI is necessary to get this pushed to the project in order to create DynamoDB tables?

**Comment by kaustavghosh06** [comment]
@ffxsam. Thanks for the feedback. We’re working towards improving our docs and the feedback is extremely useful. Did you get a chance to look at https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/Readme.md?

Also, there’a an awesome blog post about it which just got published sometime back which you might find useful - https://medium.com/open-graphql/create-a-multiuser-graphql-crud-l-app-in-10-minutes-with-the-new-aws-amplify-cli-and-in-a-few-73aef3d49545

**Comment by ffxsam** [comment]
The first link didn't help, but the second one did. `amplify add api` was the missing key. I think if that's added to your readme, that will clarify things.
