### ISSUE TITLE
Add File name to Error: 'jsonString' argument missing or empty

### ISSUE THREAD

**Issue by matansagee** [aws-amplify/amplify-cli#6102]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

I encounter this error when running `amplify api gql-compile` but I don't know which file is problematic. 
Can you please add an indication of which file is not serializing?

amplify version - 4.38.0 

**Is your feature request related to a problem? Please describe.**

**Comment by atlesp** [comment]
I get the same now on my project when running `amplify push` '
![image](https://user-images.githubusercontent.com/1275067/101453891-5871d280-3930-11eb-90ef-e6f943533780.png)

I did a `amplify pull` in the hope to resolve the issue, but it still occurs.

amplify cli version 4.38.0

**Comment by ywroh** [comment]
![스크린샷 2020-12-08 오후 6 32 56](https://user-images.githubusercontent.com/39849622/101467758-170c1200-3986-11eb-8fb6-3dae63632584.png)
I checked the same error and tried amplify pull, but the error comes out as follows.
![스크린샷 2020-12-08 오후 6 34 50](https://user-images.githubusercontent.com/39849622/101467784-20957a00-3986-11eb-92d6-48892d50b0b0.png)
amplify cli version 4.38.0

**Comment by atlesp** [comment]
My issue was that a deployment crashed and corrupted something. I fixed it by restoring the environment from the cloud

`amplify env pull -restore`
and 
`amplify pull -restore`

**Comment by attilah** [comment]
Seems to be related to #6097, closing in favor of that.

**Comment by attilah** [comment]
Reopening to gather more information on the logging error.

@ywroh That logging related error looks interesting to me, did you cleanup logging data in-between the operations or do you have any pointers on how that could have happened

**Comment by ywroh** [comment]
@attilah Thanks for your interest in my logging information.

Unfortunately, I didn't clean up the logging data between tasks, and I'll tell you as far as I can remember why it happened.

I did amplify init in the dev branch of my hb-platform project and then moved to the test branch to create the test backend and amplify env add, but the test backend was not properly created by selecting use existing environment.

Then, when I came back to the dev branch and entered the above command, an error occurred.

Please understand that my memory may be inaccurate.

**Comment by attilah** [comment]
@ammarkarachi  ^^^

Closing and will track as part of the other similar issue.

**Comment by lebull** [comment]
@ammarkarachi Could you link the similar issue please?

**Comment by lebull** [comment]
Still seeing this using cli version 4.39 and also in the admin ui.  Looks like the related issue was closed out.  Am I missing some steps here?

![image](https://user-images.githubusercontent.com/3135984/102017619-96eeff00-3d2d-11eb-847e-aa63d3a66fc8.png)

**Comment by dacarva** [comment]
I'm getting the same issue here. CLI version 4.39.
I created the project using the admin UI but it is not working in my environment

**Comment by dacarva** [comment]
> Still seeing this using cli version 4.39 and also in the admin ui. Looks like the related issue was closed out. Am I missing some steps here?
> 
> ![image](https://user-images.githubusercontent.com/3135984/102017619-96eeff00-3d2d-11eb-847e-aa63d3a66fc8.png)

I'm getting the same issue here. CLI version 4.39.
I created the project using the admin UI but it is not working in my environment

**Comment by atlesp** [comment]
@dacarva it does not seem like this is released yet when looking at the [changelog](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/CHANGELOG.md)

**Comment by lebull** [comment]
Good morning,

I was working on this exercise last night and I believe the s3 bucket
does not have CORS enabled for that endpoint, so I am unable to fetch the
data from my app.

https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

Would someone over there be able to double check this real quick, or would
you rather me replicate that from my side?

**Comment by ammarkarachi** [comment]
Thanks @atlesp , Yes the fix hasn't been released yet. It should be out soon
