### ISSUE TITLE
amplify pull may occurs file delete ?

### ISSUE THREAD

**Issue by misogihagi** [aws-amplify/amplify-cli#6105]
**Describe the bug**
when I had typed 
```bash
amplify push
git add .
git commit -am "commit"
amplify pull
git diff

```
then 

- amplify/backend/api/{apiname}/schema.graphql
- amplify/backend/api/{apiname}/stacks/CustomResources.json
- amplify/backend/api/{apiname}/transform.conf.json

were deleted.
I wonder why no change made file delete.
<details>
<summary>diff log</summary>
<pre>
<code>
diff --git a/amplify/backend/api/amplifygit/parameters.json b/amplify/backend/api/amplifygit/parameters.json
deleted file mode 100644
index 34f3c30..0000000
--- a/amplify/backend/api/amplifygit/parameters.json
+++ /dev/null
@@ -1,11 +0,0 @@
-{
-    "AppSyncApiName": "amplifygit",
-    "DynamoDBBillingMode": "PAY_PER_REQUEST",
-    "DynamoDBEnableServerSideEncryption": false,
-    "AuthCognitoUserPoolId": {
-        "Fn::GetAtt": [
-            "authamplifygit633662b6",
-            "Outputs.UserPoolId"
-        ]
-    }
-}
\ No newline at end of file
diff --git a/amplify/backend/api/amplifygit/schema.graphql b/amplify/backend/api/amplifygit/schema.graphql
deleted file mode 100644
index f4c7d6e..0000000
--- a/amplify/backend/api/amplifygit/schema.graphql
-        ]
-    }
-}
\ No newline at end of file
diff --git a/amplify/backend/api/amplifygit/schema.graphql b/amplify/backend/api/amplifygit/schema.graphql
deleted file mode 100644
index f4c7d6e..0000000
--- a/amplify/backend/api/amplifygit/schema.graphql
+++ /dev/null
@@ -1,108 +0,0 @@
-input CreateMyModelTypeInput {
-       title: String
-}
-
-input DeleteMyModelTypeInput {
-       id: ID!
-}
-
-type Mutation {
-       createMyModelType(input: CreateMyModelTypeInput!): MyModelType
-       updateMyModelType(input: UpdateMyModelTypeInput!): MyModelType
-       deleteMyModelType(input: DeleteMyModelTypeInput!): MyModelType
-}
-
-type MyModelType {
-       id: ID!
-       title: String
-}
-
-type MyModelTypeConnection {
-       items: [MyModelType]
-       nextToken: String
-}
-
-
-type Query {
-       getMyModelType(id: ID!): MyModelType
-       listMyModelTypes(filter: TableMyModelTypeFilterInput, limit: Int, nextToken: String): MyModelTypeConnection
-}
-
-type Subscription {
-       onCreateMyModelType(id: ID, title: String): MyModelType
-               @aws_subscribe(mutations: ["createMyModelType"])
-       onUpdateMyModelType(id: ID, title: String): MyModelType
-               @aws_subscribe(mutations: ["updateMyModelType"])
-       onDeleteMyModelType(id: ID, title: String): MyModelType
-               @aws_subscribe(mutations: ["deleteMyModelType"])
-}
-
-input TableBooleanFilterInput {
-       ne: Boolean
-       eq: Boolean
-}
-
-input TableFloatFilterInput {
-       ne: Float
-       eq: Float
-       le: Float
-       lt: Float
-       ge: Float
-       gt: Float
-       contains: Float
-       notContains: Float
-       between: [Float]
-}
-
-input TableIDFilterInput {
-       ne: ID
-       eq: ID
-       le: ID
-       lt: ID
-       ge: ID
-       gt: ID
-       contains: ID
-       notContains: ID
-       between: [ID]
-       beginsWith: ID
-}
-
-input TableIntFilterInput {
-       ne: Int
-       eq: Int
-       le: Int
-       lt: Int
-       ge: Int
-       gt: Int
-       contains: Int
-       notContains: Int
-       between: [Int]
-}
-
-input TableMyModelTypeFilterInput {
-       id: TableIDFilterInput
-       title: TableStringFilterInput
-}
-
-input TableStringFilterInput {
-       ne: String
-       eq: String
-       le: String
-       lt: String
-       ge: String
-       gt: String
-       contains: String
-       notContains: String
-       between: [String]
-       beginsWith: String
-}
-
-input UpdateMyModelTypeInput {
-       id: ID!
-       title: String
-}
\ No newline at end of file
diff --git a/amplify/backend/api/amplifygit/stacks/CustomResources.json b/amplify/backend/api/amplifygit/stacks/CustomResources.json
deleted file mode 100644
index f95feea..0000000
--- a/amplify/backend/api/amplifygit/stacks/CustomResources.json
+++ /dev/null
@@ -1,58 +0,0 @@
-{
-  "AWSTemplateFormatVersion": "2010-09-09",
-  "Description": "An auto-generated nested stack.",
-  "Metadata": {},
-  "Parameters": {
-    "AppSyncApiId": {
-      "Type": "String",
-      "Description": "The id of the AppSync API associated with this project."
-    },
-    "AppSyncApiName": {
-      "Type": "String",
-      "Description": "The name of the AppSync API",
-      "Default": "AppSyncSimpleTransform"
-    },
-    "env": {
-      "Type": "String",
-      "Description": "The environment name. e.g. Dev, Test, or Production",
-      "Default": "NONE"
-    },
-    "S3DeploymentBucket": {
-      "Type": "String",
-      "Description": "The S3 bucket containing all deployment assets for the project."
-    },
-    "S3DeploymentRootKey": {
-      "Type": "String",
-      "Description": "An S3 key relative to the S3DeploymentBucket that points to the root\nof the deployment directory."
-    }
-  },
-  "Resources": {
-    "EmptyResource": {
-      "Type": "Custom::EmptyResource",
-      "Condition": "AlwaysFalse"
-    }
-  },
-  "Conditions": {
-    "HasEnvironmentParameter": {
-      "Fn::Not": [
-        {
-          "Fn::Equals": [
-            {
-              "Ref": "env"
-            },
-            "NONE"
-          ]
-        }
-      ]
-    },
-    "AlwaysFalse": {
-      "Fn::Equals": ["true", "false"]
-    }
-  },
-  "Outputs": {
-    "EmptyOutput": {
-      "Description": "An empty output. You may delete this if you have at least one resource above.",
-      "Value": ""
-    }
-  }
-}
diff --git a/amplify/backend/api/amplifygit/transform.conf.json b/amplify/backend/api/amplifygit/transform.conf.json
deleted file mode 100644
index 98e1e19..0000000
--- a/amplify/backend/api/amplifygit/transform.conf.json
+++ /dev/null
@@ -1,4 +0,0 @@
-{
-    "Version": 5,
-    "ElasticsearchWarning": true
-}
\ No newline at end of file
</code>
</pre>
</details>

**Amplify CLI Version**
4.32.1

**To Reproduce**
```bash
amplify push
git add .
git commit -am "commit"
amplify pull
git diff

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. v12.19.0

**Comment by attilah** [comment]
I was not able to reproduce it by following your exact commands, here is the output:

![image](https://user-images.githubusercontent.com/230432/101810691-ef27c600-3acd-11eb-83ff-1c4becb8eca1.png)

**Comment by misogihagi** [comment]
sorry, I couldn't reproduce also.
I'll back to collect more information.
