### ISSUE TITLE
Support custom claims for auth directive in amplify mock api

### ISSUE THREAD

**Issue by estyh** [aws-amplify/amplify-cli#6106]
**Is your feature request related to a problem? Please describe.**
I'm trying to add auth directives to my models using custom attributes. This is supported with the "groupClaim" field. The problem is, I can't test it locally, because the mock graphql server only supports adding cognito groups, and not custom attributes. Development time would be a lot faster for me if I could test it locally, and not just in the appsync console.

**Describe the solution you'd like**
It would be nice to have another option in the local graphiql explorer, in the Update Auth dialog, to specify custom attributes for the token.

**Additional context**
Here is a sample of my schema and my resolver (it's working great now in appsync console)

```
type DemoThing
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["adminReporting"], groupClaim: "custom:rights" }
    ]
  ) {
  id: ID!
  stats: String!
}
```

The resolver checks the custom attribute, which is a comma-delimited string, to see if it contains the required right ("group").
Here are the relevant lines:

```
  ## Authorization rule: { allow: groups, groups: ["adminReporting"], groupClaim: "custom:rights" } **
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("custom:rights"), []) )

  #if( $util.isString($userGroups) )
    #set( $userGroups = $userGroups.split(",") )
  #end
  #set( $allowedGroups = ["adminReporting"] )
  #foreach( $userGroup in $userGroups )
    #if( $allowedGroups.contains($userGroup) )
      #set( $isStaticGroupAuthorized = true )
      #break
    #end
  #end
```

**Comment by attilah** [comment]
@estyh thanks for raising this, I add it to out bug-bash project to being tracked by the team.

**Comment by siegerts** [comment]
👋 Hi, this issue was referenced in the v4.50.2 release!

Check out the release notes here https://github.com/aws-amplify/amplify-cli/releases/tag/v4.50.2.
