### ISSUE TITLE
Can amplify support HTTP Api

### ISSUE THREAD

**Issue by lijingshanxi** [aws-amplify/amplify-cli#6107]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

        I want to use HTTP api in amplify;
        Is there any way to use HTTP api, such as manually modifying the template file;

**Describe alternatives you've considered**

**Additional context**

**Comment by SwaySway** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-cli/issues/6024
