### ISSUE TITLE
'amplify import auth' blocking incomprehensible step

### ISSUE THREAD

**Issue by intersides** [aws-amplify/amplify-cli#6111]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
amplify import auth

**Amplify CLI Version** 
4.38.0
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Auth, Cognito, Android SDK

**Provide additional details e.g. code snippets**
I am trying to use an existing User Pool set and defined by an external contractor. It is meant for a web-application dashboard using Cognito authentication and now I need to create a Native Android Mobile app that uses the same Cognito base.  
During the 'amplify import auth' step, I got stuck at he "Select the User Pool you want to import", the Web app client has been found and I have 3 choice for Native app clients, and none of them works, they all report the error: "The following OAuth properties are not matching".
then:

Configured Identity Providers:

| dashboard-custom-login | dashboard |
| ---------------------- | --------- |
|                        | COGNITO   |

OAuth Flow Enabled for app client:

| dashboard-custom-login | dashboard |
| ---------------------- | --------- |
| false                  | true      |

Callback URLs:

| dashboard-custom-login | dashboard                                  |
| ---------------------- | ------------------------------------------ |
|                        | http://localhost:3200/oauth2-redirect.html |

Logout URLs:

| dashboard-custom-login | dashboard                                  |
| ---------------------- | ------------------------------------------ |
|                        | http://localhost:3200/oauth2-redirect.html |

Allowed OAuth Flows:

| dashboard-custom-login | dashboard |
| ---------------------- | --------- |
|                        | code      |

Allowed OAuth Scopes:

| dashboard-custom-login | dashboard |
| ---------------------- | --------- |
|                        | openid    |
|                        | profile   |

How to progress... I found this message feedback totally cryptic.  Thanks in advance.

**Comment by renebrandel** [comment]
Hi @intersides can you go to the Cognito User Pool configuration and confirm that the OAuth properties under the app clients (dashboard-custom-login and dashboard) are the same? 

You can find this setting under App Integration -> App client settings
![image](https://user-images.githubusercontent.com/4989523/101705888-d02d2380-3a3c-11eb-9fa8-f92792baeb6e.png)

**Comment by intersides** [comment]
One of the app client had no OAuth set. 
I could move ahead by creating a new app client for the mobile app. So I guess that this issue can be closed.
