### ISSUE TITLE
Amplify generating duplicate files

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-cli#6118]
** Please describe which feature you have a question about? **
AWS Amplify

** Provide additional details**
Why does `amplify pull` generate multiple versions of the same file?

![4CE8A313-A583-47C8-ACA4-565A369BC683_4_5005_c](https://user-images.githubusercontent.com/3934326/100166634-02058e00-2e72-11eb-8cec-e3663ee45869.jpeg)

**Comment by attilah** [comment]
@jknapp25 what version of the CLI are you using and what commands are you exactly executing that causes this? Is file duplication happening if VS Code is closed and executing the command from the shell? What OS are you using.

**Comment by jknapp25** [comment]
@attilah I moved my project files out of a location that is syncing with the cloud, as advised by this article... https://technology.siprep.org/icloud-sync-creating-duplicate-files-when-saving/
