### ISSUE TITLE
Add functionality to correctly resolve AWS:NoValue when using Amplify mock

### ISSUE THREAD

**Issue by cbude** [aws-amplify/amplify-cli#6122]
**Is your feature request related to a problem? Please describe.**
I see that a lot of people have problems with environment variables for lambda functions when using amplify mock api.
Since mock doesn't support using for example **resolve:ssm** it translates it into the to the litteral value which works incorrectly when working locally. I tried using the **AWS:NoValue** instead to remove all env variables from the cloudformation template when using mock but that also translates in to en env variable with the value "AWS::NoValue"

**Describe the solution you'd like**
I would like mock to be able to handle the pseudo parameter **AWS:NoValue** to correctly remove a property instead of translating it to a string value. This would enable me to declare my environment variables locally which is something I use when developing other applications and lambda functions.

**Describe alternatives you've considered**
My current solution is to read what ENV is running and use that to select "ENV_VAR_LOCAL" instead of "ENV_VAR" for all variables that are required to run the function locally. Solutions proposed in other issues either involve a separate env file or hardcoding values during development and reverting before pushing. Neither of those solutions work for me since they involve risking to committing sensitive information when pushing to GIT.

**Additional context**
[AWS - Pseudo parameter reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html)

**Comment by attilah** [comment]
@cbude thanks for raising it, I marked it as an enhancement

**Comment by Bentheburrito** [comment]
Hi all, I'd like to take this issue up :slightly_smiling_face:
