### ISSUE TITLE
graphql-transformer-core requires amplify-cli-core but is not a dependency

### ISSUE THREAD

**Issue by kcwinner** [aws-amplify/amplify-cli#6123]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
[graphql-transformer-core/src/util/sanity-check.ts](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/src/util/sanity-check.ts#L5) requires `amplify-cli-core` but `amplify-cli-core` is not listed as a dependency in [package.json](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/package.json) as of version `6.24.0` (6.23.1 was last working version for me).

I received the following error when attempting to upgrade from 6.23.1 to 6.25.0:
```
cdk-appsync-transformer % yarn test
yarn run v1.22.10
$ rm -fr lib/ && jest --passWithNoTests --updateSnapshot
 FAIL  test/index.test.ts
  ● Test suite failed to run

    Cannot find module 'amplify-cli-core' from 'node_modules/graphql-function-transformer/node_modules/graphql-transformer-core/lib/util/sanity-check.js'
```

**Amplify CLI Version**
N/A - using amplify graphql-transformer libraries outside of amplify-cli

**To Reproduce**
```
git clone -b repro/graphql-transformer-dependencies https://github.com/kcwinner/cdk-appsync-transformer.git
npx projen
yarn test
```

**Expected behavior**
graphql-transformer libraries working without the global context of amplify-cli

**Screenshots**
<img width="717" alt="Screen Shot 2020-12-09 at 9 39 50 AM" src="https://user-images.githubusercontent.com/2728868/101643808-7dcf1100-3a02-11eb-9d85-b08219f514d6.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.17.0

**Additional context**
I use the graphql-transformer libraries in a [cdk construct](https://github.com/kcwinner/cdk-appsync-transformer#functions) to allow directive based schema usage.

**Comment by attilah** [comment]
@kcwinner thanks for the heads up I created the PR after double checking for other packages.
