### ISSUE TITLE
Unable to pull a backend env created by the amplify console (EPERM: operation not permitted)

### ISSUE THREAD

**Issue by lebull** [aws-amplify/amplify-cli#6138]
This is happening on Windows.

>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Pulling env created by the amplify console results in a permissions error

```
+ @aws-amplify/cli@4.38.2
added 45 packages from 20 contributors, updated 51 packages and moved 2 packages in 26.651s
PS C:\Users\me\Projects\proj> amplify pull --appId <app_id>--envName dev
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
EPERM: operation not permitted, rename 'C:\Users\me\Projects\proj\amplify' -> 'C:\Users\me\Projects\proj\amplify-backup'

```
**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

+ @aws-amplify/cli@4.38.2

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

* Create a backend env using the amplify console
* Use the pull command provided to pull the backend env

**Additional context**

I originally had this pointed to another amplify project in another branch, so maybe something wanky happened with the cli's config?  But I'm reproducing this after creating a fresh clone on a different machine where there was never a reference to the other project.

**Comment by attilah** [comment]
@lebull thanks for reporting the issue we're aware of this and it will be fixed in the next release.

**Comment by lebull** [comment]
4.39 seemed to resolve this issue.

**Comment by ammarkarachi** [comment]
@lebull Thanks for checking

**Comment by berbaroovez** [comment]
Im getting this issue on 4.39
