### ISSUE TITLE
Folders for deleted lambdas returning

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#6140]
**Describe the bug**
On one project I have deleted a lambda (it used to be a dynamodb trigger lambda).  I did this quite a while ago and plenty of push/pull have occurred since then.  But I find I have to keep deleting the lambda folder from the functions folder in the backend.

At first I though it could be git but I have ignored the folder and deleted it and checked all branches etc. and it definitely is not coming back via git.  If I delete the amplify folder though and do a fresh pull then it definitely reappears!  How do I tell amplify to remove it permanently?

**Amplify CLI Version**
4.38.0

**To Reproduce**
Remove & Delete a lambda and push.  Do a fresh pull by deleting the amplify folder.  Folder for lambda reappears.

**Expected behavior**
Lambda to have been removed from the current backend on the "push" command

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.4.0

**Comment by SwaySway** [comment]
@jcbdev Is the folder empty? Or are there CFN templates in the folder?

**Comment by jcbdev** [comment]
@SwaySway the templates are in the folder along with the lambda code.

I don't really understand how it is happening.  When I check the s3 deployment bucket there are no references in any of the build folders etc EXCEPT for #current-cloud-backend.zip where the function still exists.  It's like it never get removed from this zip so persists forever even though all references elsewhere are removed.

**Comment by kaustavghosh06** [comment]
did you run `amplify remove <function>` and then run `amplify push`?

**Comment by jcbdev** [comment]
> did you run `amplify remove function` and then run `amplify push` thereafter to remove the function from the cloud?

Yeah it comes back.  I have figured out that `amplify remove function` does not delete the folder from `#current-cloud-backend` folder. Thus it gets pushed with the next amplify push and ends up in the package zip on S3... This of course means that even on a fresh checkout if you do an `amplify pull` it downloads the folder again and restores it.

The "workaround" is to manually delete the folder in #current-cloud-backend before pushing.  It then stops coming back.  Would be good if it deleted that folder anyway when the function is removed.

**Comment by jcbdev** [comment]
@kaustavghosh06  @SwaySway turns out my workaround was still not enough.  It is insipid and still kept coming back.

I think I have finally fixed it by downloading #current-cloud-backend.zip, unzipping it, removing the function folder and then uploading it manually to s3.

I am assuming the push/pull process always downloads the latest #current-cloud-backend.zip (even if you have that folder already locally), so the folder gets restored consistently.  Then push process then just applies the changes to this folder and re-zips and pushes it (thus resurrecting the folder for the deleted lambda each time)

I have no idea why `amplify function remove` left the folder when it was deleted as other lambdas (and a layer) have been deleted since with no issue but for some reason in this instance it left the folder but deleted all references to it and then it was pushed to the bucket.  From that point on it was restored consistently whether or not you delete the folder or delete it in '#current-cloud-backend' folder (because of the behaviour of re-pulling the zip on every action).

Although I have solved my issue for now it does strike me that this could cause any number of assets to be consistently propagated if they are not specifically mentioned in the amplify-meta.json/backend-config.json.  Maybe a warning and or prompt to delete unreferenced folders on amplify push command could prevent similar issues.

The main reason it was disruptive in my scenario was the function was old code that did not fulfil the eslinting rules that were enforced after its deleting on the monorepo.  Thus anyone working on the backend would then start having issues pushing their code.

**Comment by SwaySway** [comment]
We are looking into some function enhancements this is something we can keep in mind as a part of that. Closing this issue for now as it seems it's resolved should you run into this again please comment below. You can also check the logging file with the following format `~/.amplify/logs/amplify-cli-<issue-date>.log`.
