### ISSUE TITLE
Can not require/import custom function from lambda layer. 

### ISSUE THREAD

**Issue by Usama-Tahir** [aws-amplify/amplify-cli#6142]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am using the lambda layer for node modules. Recently I decided to share a piece of code across multiple lambdas so I decided to put that piece of code in the lambda layer `/opt` directory. For example, I created a file named `toast.js` inside `/opt/` directory so the full path is like this: `/opt/toastjs`

toast.js:
```
const getValue = async () => {
  console.log('Toast');
};
module.exports = getValue;

```

In my Lambda function that uses that layer, I import that `toast.js` file like this.
```
const getValue = require('/opt/toast');

```

However, when I run my lambda function, I get this error.

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '/opt/toast'\nRequire stack:\n- /var/task/app.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '/opt/toast'",
        "Require stack:",
        "- /var/task/app.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
I can successfully use node_modules from the lambda layer inside my lambda functions though.
**Amplify CLI Version**
4.37.1

**Expected behavior**
I should be able to use custom code from inside the lambda layer in my lambda function.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS (Focal Fossa)
 - Node Version. v12.14.1

**Comment by attilah** [comment]
@Usama-Tahir you do not have to refeerence /opt folder from your Lambda code as whatever you put into `/opt` in your layer will be `.` in your Lambda, please try this: `const getValue = require('./toast');` and it should work.

Try out something similar by using node modules in a layer by following this guide: https://aws.amazon.com/blogs/mobile/how-to-use-lambda-layers-with-the-amplify-cli/

I'm closing the question as it was answered if something new comes up feel tree to re-open it or open a new one.
