### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ryan-mars** [aws-amplify/amplify-cli#615]
In order to facilitate collaboration with the community and align the efforts of potential contributors with that of project leadership, this repo needs a published roadmap.

**Comment by cmckni3** [comment]
Does the Amplify team have a public roadmap? The Containers and CloudFormation teams have projects on GitHub for tracking. See below

https://github.com/aws/containers-roadmap/projects
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/projects
