### ISSUE TITLE
[QUESTION] can I update the CLI without making changes to the project?

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-cli#6154]
** Please describe which feature you have a question about? **
This is probably a dumb question, but I just want to update the CLI so I can use Lambda Layers and dont want to cause issues in my current project. Thx

**Comment by SwaySway** [comment]
Hello @contractorwolf 
Generally the CLI handles migrations when upgrading between versions. For any migrations which require external manual intervention please review our docs here: https://docs.amplify.aws/cli/migration/lambda-node-version-update
