### ISSUE TITLE
Governance and contol improvement

### ISSUE THREAD

**Issue by Vittoriusly** [aws-amplify/amplify-cli#616]
**Is your feature request related to a problem? Please describe.**  
I'm a bit worried to let high-privileged IAM accounts usage under the discretion of 3rdy part developers, but on the other side I cannot slow down CI/CD cycles, hence I need a trade-off between deployment needs and company needs.   

**Describe the solution you'd like**  
The idea I have in mind is to split the CloudFormation script into 3 scripts inside a StackSet.  

1. the first one is the script that create IAM resources (iam users, roles, policies and so on). This script can be easly checked and won't change very often.
2. the second one is an optional script that declare "pet resources" such as databases, tables and so on. In my opinion this will allow developers to deploy with more confidence because data will be untouched.
3. the third one is the "cattle resources" part.

**Describe alternatives you've considered**
I don't have other ideas.

**Additional context**
Nothing to add.

**Comment by kaustavghosh06** [comment]
@Vittoriusly Have you checked out the new multi-environment feature of the Amplify CLI? -> https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Maybe the 3rd party developers shouldn't have access to the prod environment and work off their own sandbox environments?

**Comment by Vittoriusly** [comment]
@kaustavghosh06 That is another "dimension". May goal is lowering risks on deploy phase: I do not want to be forced to allow developers to handle sensitive IAM resources such as users, policies and roles.  I don't know how these can interact with Shared VPCs.

**Comment by kaustavghosh06** [comment]
We released support for Assuming IAM roles and MFA which would potentially solve your issue - https://aws-amplify.github.io/docs/cli/init#assuming-an-iam-role
Please feel free to re-open or comment on this thread if you need more information around this.
