### ISSUE TITLE
Amplify push: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-cli#6164]
After updating my GraphQL API configuration, every time I try `amplify push`, I get the error, `Unexpected token u in JSON at position 0`. I imagine it means a JSON object somewhere is undefined, but I have no idea how to fix that.

UPDATE: That error also shows after I finish configuring conflict detection using the CLI.
UPDATE: That error also shows after I do `Disable DataStore for entire API`.

**Comment by ucanlendit** [comment]
We have the same error, happy to jump on a quick call to help debug...

**Comment by jknapp25** [comment]
@ucanlendit I know it's not the best workaround, but I did not see this issue after removing, then re-creating my API, **without enabling** the DataStore.

**Comment by villeheikkinentt** [comment]
I'm having the same issue. Creating a new environment works and you can successfully use amplify push, but updating the environment again causes the same issue.

**Comment by akshbhu** [comment]
Hi @jknapp25

Sorry for the late response. 
Can you tell me the categories you added  so that I can repro this error on my end?

**Comment by akshbhu** [comment]
This issue is fixed in amplify latest version v4.40.1. 
Feel free to comment if the issue  still present.

**Comment by isbkch** [comment]
Issue still present, I'm running 4.41.2 
I'm getting the same error when I run `amplify api gql-compile`
Is there anyway to make the error message more clear ?
