### ISSUE TITLE
No credentials found for appId - Backend hosted in AWS RDS

### ISSUE THREAD

**Issue by dattnguyen** [aws-amplify/amplify-cli#6167]
I tried running 

```
amplify configure --appId *************
```

but it did not work. I kept getting No credentials found for appId: ************* error. My backend is created and stored in AWS RDS (Oracle engine) so I'm not sure if that might cause an issue. I wonder how I can connect the backend environment of Amplify to AWS RDS. 

When I went to the AWS Amplify website, I could see that a backend environment was created but it's not connected to anything and it does not have continuous deploys set up.

**Comment by akshbhu** [comment]
Hi @dattnguyen 

From the error it seems it not able to find credentials for the appId?
Can you tell me the steps you followed and categories added before you got this error?

**Comment by jhockett** [comment]
Hi @dattnguyen, We need more information to understand what's going on.

What steps led you to this state? 

What version of the cli are you running? You can use `amplify -v` to check the amplify cli version on your system

**Comment by dattnguyen** [comment]
Hi @jhockett and @akshbhu, thanks for your reply. I am following these steps from a youtube video (https://www.youtube.com/watch?v=QkjkdkkQZwE&t)

- Upload to Github all the front-end files, cd to that directory, run `npm i aws-amplify-vue`. The current version of cli I am running is 4.39.0
- Run `amplify configure`, create new user with the KeyID and secret access key. 
- Run `amplify init`, `amplify add hosting`
- After running `amplify pull --appId ************* --envName staging`, I can see that the backend environment is now created.

Current Environment: staging

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |

So, how do I connect this backend to AWS RDS? I have a connection string `connectString: "**********.us-east-1.rds.amazonaws.com/jeopardy"` and a password that are stored in a db-config.js file when I run the app locally. I would assume I have to use them to connect to AWS RDS using Amplify but I am not sure how to.

Please let me know if you need further information.

**Comment by dattnguyen** [comment]
I guess my problem comes down to how can I connect the Amplify backend environment to AWS RDS. After googling around, it looks like I need to create a serverless using Amazon Aurora as the engine option. However, the database has already been uploaded and stored using Oracle as the engine.

**Comment by jhockett** [comment]
@dattnguyen We have [docs](https://docs.amplify.aws/cli/graphql-transformer/relational) on setting up a relational DB with a GraphQL API that you might find useful. Unfortunately, Oracle is not supported.

**Comment by dattnguyen** [comment]
That's unfortunate. Thanks for letting me know!
