### ISSUE TITLE
Cannot pull an existing backend since the latest version

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-cli#6168]
**Describe the bug**
On an existing project, I want to pull an existing Amplify backend
I run `amplify pull --appId d26xxxxxx --envName dev`

**Expected:**
A new amplify/ directory is created with the backend informations

**Actual**
The CLI opens a Chrome browser and redirects me to the Admin UI (https://eu-west-1.admin.amplifyapp.com/admin/d26xxxxxx/dev/verify/).
I don't use Admin UI, it is not enabled - so I am completely blocked.

**Workaround**
Downgrading amplify-cli to 4.29.8 fixed the issue.

**Amplify CLI Version**
4.39.0

**Desktop (please complete the following information):**
Mac OS

**Comment by abenzick** [comment]
I am experiencing this exact same issue.

**Comment by jhockett** [comment]
Hi @maximelebastard @abenzick, was AdminUI enabled previously for this project? If not, can you double check it's not currently enabled?

I haven't been able to reproduce this yet.

**Comment by abenzick** [comment]
Yes, it was enabled previously.

**Comment by maximelebastard** [comment]
I may have enabled it a few minutes for a quick test.
For what I remember, I did not pull the project during that interval.

**Comment by jhockett** [comment]
Try running `amplify logout --appId <AmplifyAppId>`. What's the output you see?

If the credentials exist, you will be asked if you want to logout from all sessions. Answer `y`. Then try pulling your app.

**Comment by jhockett** [comment]
A fix has been merged and will be available in the next release. Thanks for the bug reports @maximelebastard @abenzick!
