### ISSUE TITLE
Can't pull out data via DataStore for types with a @connection relation?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6169]
**Which Category is your question related to?**

DataStore use within Amplify. I've added DataStore in retrospectively to an existing GraphQL api via `amplify update api`

I can pull back data for models that don't have any relations (@connections to other models) however when I try to pull back data for models with relations they always come back as empty (ie no results found). That seems to be the only pattern I can find.

When I added the data I back filled all the `_version` fields with a value of 1.

I've tried creating a new item too, again this only works for models without relations and when it works the new item only shows up in my local environment and not in my DynamoDB tables.

Calling `Amplify.DataStore.clear();` in my apps main index.js file doesn't clear that new item out of my local data.

Feels like I'm missing a magic setting somewhere to say "no really, you can sync to the database now...!" but can't find it. Although the fact I can pull back some data but not others sort of rules that out, the connection clearly works its just not working for some models.

I've set the logging level to debug using `Amplify.Logger.LOG_LEVEL = "DEBUG";` which logs an error about subscriptions not being able to find a field called id on a model that doesn't have an id field, but this is logged way after my data access code which is coming back empty.

How best to debug this or look into it more?

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

v.4.39

**What AWS Services are you utilizing?**

API

**Comment by nubpro** [comment]
Don't think this problem is relevant anymore, @PeteDuncanson. It's sorted out already.

For any future readers:
It has nothing to do with the use of `@connection`.

Here's how you can debug why DataStore is having trouble syncing down the data to the client:
1. Developer tools
2. Network tab
3. Go through each `graphql` request and check the response. There will be errors if any.

**Comment by PeteDuncanson** [comment]
Yep, I got this sorted over the weekend with the help of some fine folks in the Discord channel. 

As you state the info I needed was in the network tab as GraphQL errors. Fixing those made DataStore work as it should.
