### ISSUE TITLE
amplify/backend/api/myproject/schema.graphql - single source of truth?

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#617]
** Which Category is your question related to? **
AppSync

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
In amplify/backend/api/myproject/schema.graphql, I define such a type with GraphQL transformer:
```graphql
type Item @model {
  id: ID!
  createdAt: AWSDateTime
  content: String!
}
```
In this way, I am able to access `createdAt` attribute of the item, as it will be filled by server end as suggested in https://github.com/aws-amplify/amplify-cli/issues/401.

However, I want to remove `createdAt` from `CreateItemInput` and `UpdateItemInput`, that are auto-generated according to [codegen - flow 2](https://aws-amplify.github.io/docs/cli/codegen#workflows-).

```graphql
input CreateItemInput {
  id: ID
  createdAt: AWSDateTime
  content: String
}

input UpdateItemInput {
  id: ID!
  createdAt: AWSDateTime
  content: String
}
```

My questions:
1. Can I do it on appsync console Schema and somehow "pull" it? 
1. Can I do it with myproject/build/schema.graphql and somehow "push" it? 
1. Or myproject/schema.graphql is the single source of truth and there is no way to manually tune the transformed schema AND generated resolvers?

**Comment by YikSanChan** [comment]
For question 3, currently, there is no way to sync generated resolver code (e.g., amplify/backend/api/myproject/build/resolvers/Mutation.createItem.request) with resolver in AppSync console. Edit resolver on AppSync console directly. #30

**Comment by kaustavghosh06** [comment]
@YikSanChan 
1. Currently, there's not a clean way to pull your changes from the console, but yes you can follow the methodology mentioned in the twitter thread mentioned above in which case you would no longer be able to manage your API through the CLI (using the annotated schema) and you would have to rely on the console to make all your changes.

2. I'll let @mikeparisstuff answer that, but i beleive you can do so

3. You can use the ` amplify push —no-gql-override` command to manually modify your generated resolvers and then push it. Note: this command basically would not automatically compile the annotated graphql schema and override the resolvers.

**Comment by gitzhouxinyu1** [comment]
But isn't that meaning that everytime you update the api, you can't let the cli do the transform for you (since it will modify your previous choices), or let the cli do the transform and edit back the previous changes?
