### ISSUE TITLE
Not Authorized to access createUser on type User

### ISSUE THREAD

**Issue by Ko09** [aws-amplify/amplify-cli#6170]
I init an existing project that I made 6 month ago using `amplify init --app <github url>`. I pulled that project using `amplify pull`.
Then I executed GraphQL mutation that creates User after authenticated from Cognito user pool.
I received an Error says `{"data": null, "errorInfo": null, "errorType": "Unauthorized", "locations": [Array], "message": "Not Authorized to access createUser on type User", "path": [Array]}.
`
I attached a policy that allows every actions on every resources on DynamoDB to Cognito authRole, and I also attached AWSAppSyncInvokeFullAccess policy, but still getting this message. I can't figure it out why I am getting this Error.This thing worked 6month ago without configuring policies on authRole when I use `amplify add api` and `amplify add auth`. 

**Which Category is your question related to?**
Amplify cli
Cognito
API

**Amplify CLI Version** 
4.39.0
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
AppSync 
Cognito

**Provide additional details e.g. code snippets**
```
type User
  @model
  @auth(rules: [{ allow: owner, ownerField: "id", queries: null }]) {
  id: ID!
  sex: String
  avatar: S3Object
  username : String
  conversations: [ConvoLink] @connection(name: "UserLinks")
  messages: [Message] @connection(name: "UserMessages")
}
```
This is the function that I call to execute the mutation.

```
async createUser() {
    try {
      await API.graphql(graphqlOperation(createUser, { username: "Guest" }))
    } catch (err) {
      console.log('Error creating user! :', err)
    }
  }
}
```

**Comment by Ko09** [comment]
I read this https://github.com/aws-amplify/amplify-cli/issues/3064

and added   @aws_cognito_user_pools in my schema. 
still get same Error.

**Comment by Ko09** [comment]
Changing `@auth(rules: [{ allow: owner, ownerField: "id", queries: null }])` to `@auth(rules: [{ allow: owner, queries: null }])` worked for me.

**Comment by saurabhghadi0401** [comment]
Hi, can you please help me out with same..? I want to store cognito user to type User also. How did you call the mutation function? did you call it in lambda function or  just in your app(JS file.. maybe) ?
