### ISSUE TITLE
Amplify push - Cannot read property 'join' of null

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#6172]
**Describe the bug**
I currently cannot push using the Amplify CLI, this is the error - 
```
Cannot read property 'join' of null
An error occurred during the push operation: Cannot read property 'join' of null
```

**Amplify CLI Version**
4.37.1 (downgraded because new versions have a lot of bugs)

**To Reproduce**
`amplify push`

**Expected behavior**
Amplify push works.

**Additional context**
I am currently blocked and cannot work on my backend because of this

**Comment by gabrielperales** [comment]
@idanlo I'm having the same issue, how did you fix it?

**Comment by idanlo** [comment]
@gabrielperales i actually have no idea. Sometimes the environment gets messed up on its own, probably by amplify pull or something. I deleted the amplify folder, pulled from git, ran amplify init and it worked. Weird.
