### ISSUE TITLE
Amplify pull - pushing with a custom profileName - incorrect AWS Account ID

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-cli#6184]
**Describe the bug**
We have a CI/CD script before building the app that pulls the Amplify code (aws-exports, queries, mutations etc), we use a custom profile name for each environment, this is the pull script - 
```
REACTNATIVECONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"/\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"$PROJECT_NAME-$ENV\",\
\"region\":\"$REGION\"\
}"
AMPLIFY="{\
\"projectName\":\"$PROJECT_NAME\",\
\"appId\":\"$APP_ID\",\
\"envName\":\"$ENV\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react-native\",\
\"config\":$REACTNATIVECONFIG}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG}"

echo -e "no\n" | amplify pull \
  --amplify $AMPLIFY \
  --frontend $FRONTEND \
  --providers $PROVIDERS
```
The pull fails with this error - 
```
User: USER_ARN is not authorized to perform: amplify:GetApp on resource: arn:aws:amplify:REGION:INCORRECT_ACCOUNT_ID:apps/APP_ID
```
Version 4.37.1 and below works, I have tried 4.38.0 and 4.39.0 both do not work

**Amplify CLI Version**
Anything 4.38.0 and above

**To Reproduce**
Create a script like the one I pasted above, have correct credentials for a custom AWS profile, you will not be able to pull your app from that profile.

**Expected behavior**
Custom profiles should work

**Comment by jhockett** [comment]
Hi @idanlo, I wasn't able to reproduce this. The pull script you provided worked for me on 4.39.0. Are you still seeing this issue on version 4.40.1?

**Comment by jhockett** [comment]
Closing due to lack of response.
