### ISSUE TITLE
variable (and configurable) account number instead of hardcoded everywhere

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#6187]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

Currently, I looked at the template files, there are hardcoded account numbers related to the account where I deployed the app, shouldn't this be a variable that we can change?

**Describe the solution you'd like**

Allow us to add `accountNumber` on a configuration file.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by yuth** [comment]
@aprilmintacpineda which category did you see the account number hardcoded?

**Comment by akshbhu** [comment]
Closing due to lack of response. Feel free to comment to clarify this

**Comment by aprilmintacpineda** [comment]
@yuth @akshbhu I think in the latest version this is no longer the case. Thanks for the response. I'll open this again if I found out more about the latest version.
