### ISSUE TITLE
Add `amplify env ls` as an alias for `amplfiy env list`

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#6188]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I type `amplify env ls` expecting list of Amplify environments when the command is actually `amplify env list`.

**Describe the solution you'd like**
I'd like `amplify env ls` to be an alias for `amplify env list`.

**Describe alternatives you've considered**
I can just make it a shell alias. 😛 

**Additional context**
If you guys are interested in having this built-in alias implemented, I would like to contribute by submitting a PR for it.

**Comment by yuth** [comment]
@Coteh yes, we would appreciate an PR
