### ISSUE TITLE
An error occurred during the publish operation

### ISSUE THREAD

**Issue by gwasserman4856** [aws-amplify/amplify-cli#6190]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Using headless amplify publish, I am getting "An error occurred during the publish operation".  It appears to have completed cloudformation updates and built the deployment package.  The last line before the error is "Find out more about deployment here: bit.ly/CRA-deploy."  

I am working in a dev environment where I do have console access.  In my production environment I do not have console access so need to deploy everything via Jenkins.  This process was working about a month ago.  When run via Jenkins, the same role is used that is used when I run locally.

I also see a random error "An error occurred during the push operation: The AWS Access Key Id you provided does not exist in our records."  This error stops well before the above mentioned problem.  If I kick off the job again, it will normally not throw that error and continue with the rest of the process.  

I was on with support for over 3 hours today and a full recording was made of the process I am following.

While ideally I would like to get this fixed.  Please let me know if there is an alternative that I can follow given that the build directory is being created.  Can I manually zip the build directory and upload and then use a cli command to kick off the deployment (note that I can not upload directly in amplify console due to read only permissions in our production environment).  I have a project that needs to get to production as soon as possible, so looking for a quick workaround.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.32.1
I tried the latest release but that causes other issues and researching the bug reports it was recommended to downgrade to 4.32.1 which is also the last version that was working for me.

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Probably not easy to reproduce.  The error is likely a combination of amplify, jenkins jobs, and policies on our account.  However, it did work previously and I am using the same role whether locally or via jenkins so expect it should still work.  It would be nice to see a more informative error message to figure out what is going on.  

I have put in a lot of print statements in the amplify cli code.  It appears to fail at const config = await configurationManager.loadConfiguration(context, aws); in the file aws.js.  

**Expected behavior**
Publish should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
Local: Mac
Jenkins: Dockerfile based on python:3-7-alpine image

**Additional context**

**Comment by gwasserman4856** [comment]
I spent a lot of time debugging the amplify cli and was finally able to get the deploy to work.  At the end of the day there is a lot going on and just having error messages propagated to the log would help tremendously. 

First issue was that I was getting an exception for having a corrupt local-aws-info.json file.  That file was in the auto generated .gitignore.  I removed from the .gitignore so that the process could pick up my local file.  This did not resolve the problem, but allowed the program to move forward.

After digging deeper, I found that I was having an error due to not having the project profile name in the .aws credentials file.  I had the useProfile option set to false and was setting credentials directly in the headless amplify init call.  I was also setting environment variables for the credentials and created a .aws/credentials file for default profile.  The process I am using was working when I last worked on the project over a month ago.  As in the first issue, an exception was getting thrown and the message was not getting written to the console.  Once I printed the exception, it was pretty easy to figure out that the program was looking for a section in the credentials file for the project profileName.  Once I did that then the program was able to deploy.   

Please let me know if it sounds like I have taken the correct steps to resolve the problem so it does not break when moving to new versions.  Also, let me know if there is a way to get more verbose output from the application to assist with debugging.

**Comment by yuth** [comment]
> I spent a lot of time debugging the amplify cli and was finally able to get the deploy to work. At the end of the day there is a lot going on and just having error messages propagated to the log would help tremendously.

We are adding more verbose logging to the CLI to diagnose the issues. These log statements would be added organically and in more places slowly.

> After digging deeper, I found that I was having an error due to not having the project profile name in the .aws credentials file. I had the useProfile option set to false and was setting credentials directly in the headless amplify init call. I was also setting environment variables for the credentials and created a .aws/credentials file for default profile.

Which headless command were you using when you set `useProfile` to false? It should be possible to do a `push`/`publish` without creating a local profile in headless mode. 

You could get details about headless mode in our docs [here](https://docs.amplify.aws/cli/usage/headless)

**Comment by the-zimmermann** [comment]
I'm in the same boat. This is my third project I'm coming back after a while and amplify all of the sudden stops working.
This is so frustrating. I will probably never publish a frontend with the cli again.  

Can you please output the errors instead of just telling us that there is an error? 
![image](https://user-images.githubusercontent.com/75070374/102490353-00914500-406f-11eb-86e8-6ee325055758.png)

**Comment by the-zimmermann** [comment]
> I'm in the same boat. This is my third project I'm coming back after a while and amplify all of the sudden stops working.
> This is so frustrating. I will probably never publish a frontend with the cli again.
> 
> Can you please output the errors instead of just telling us that there is an error?
> ![image](https://user-images.githubusercontent.com/75070374/102490353-00914500-406f-11eb-86e8-6ee325055758.png)

Not sure why, but if you kill all the files:

```git clean -dfx```

and reinitiate (did that before without cleaning) it works again.

You may forgot something in the process or added something up, what you did not migrate in older projects?

**Comment by gwasserman4856** [comment]
@Yuth - In order for me to deploy to production, I essentially need to recreate the entire amplify environment via a docker image run from Jenkins.  The first step runs amplify init and that is where I set the access key and secret access key in the providers section.  The amplify init ran with no issue.  Next, the process runs an amplify publish.  There is no argument for credentials, but I assumed it picked up settings based on the amplify init.  The publish ran and was able to execute cloudformation scripts.  It only failed at the very end after creating everything for the build.  The deploy is what was failing due to not having the profile in the credentials file.   Please note that I am on an older version of amplify due to issues with the latest release that others have posted issues about.

In terms of error logging, the places that would have helped me are where errors are thrown and those messages are never sent to the console.  For example, in system-config-manager.js - throw new Error(`Profile configuration is missing for: ${profileName}`); was the message that would have been most useful to see and could have saved many hours of debugging.   There was another place where an error was being thrown complaining about a corrupt local-aws-info.json file.  That file is in the standard .gitignore.  I just added it back to the project and then the process was able to continue.

**Comment by yuth** [comment]
> In terms of error logging, the places that would have helped me are where errors are thrown and those messages are never sent to the console. For example, in system-config-manager.js - throw new Error(`Profile configuration is missing for: ${profileName}`); was the message that would have been most useful to see and could have saved many hours of debugging. There was another place where an error was being thrown complaining about a corrupt local-aws-info.json file. That file is in the standard .gitignore. I just added it back to the project and then the process was able to continue.

Thank you for the feedback about logging.

Could you share arguments used in `amplify init` in your CI

**Comment by gwasserman4856** [comment]
The relevant parts of my python setup program are:

Init:

    AMPLIFY = {
        "projectName": PROJECT_NAME,
        "envName": envName,
        "defaultEditor": "code"
    }

    FRONTEND = {
        "frontend":"javascript",
        "framework":"react",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "build",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm run-script start"
        }
    }

    PROVIDERS = {
        "awscloudformation": {
            "configLevel": "project",
            "useProfile": False,
            # "profileName": "default",
            "accessKeyId": env['AWS_ACCESS_KEY_ID'],
            "secretAccessKey": env['AWS_SECRET_ACCESS_KEY'],
            "region": env['AWS_DEFAULT_REGION']
        }
    }

    AUTH = {
        "auth": {
            "userPoolId": userPoolId, 
            "webClientId": webClientId, 
            "nativeClientId": nativeClientId, 
            "identityPoolId": identityPoolId
        }
    }

    subprocess.run([
        'amplify', 'init',
        '--amplify', json.dumps(AMPLIFY), 
        '--frontend', json.dumps(FRONTEND), 
        '--providers', json.dumps(PROVIDERS), 
        '--categories', json.dumps(AUTH),
        '--yes'
        ],
        env=env)

Publish:

    CODEGEN = {
        "generateCode": True,
        "codeLanguage": "javascript",
        "fileNamePattern": "src/graphql/**/*.js",
        "generatedFileName": "API",
        "generatedDocs": "True"
    }

    subprocess.run([
        'amplify', 'publish', 
        '--codegen', json.dumps(CODEGEN), 
        '--yes'
        ],
        env=env)

**Comment by nikhname** [comment]
@gwasserman4856 did you face this again with CLI version 4.41.2? We will work on providing better error logging related to profile configuration and publish.

**Comment by Nxtra** [comment]
If you are publishing in your CI pipeline chances are that warnings are treated as errors.
Thereby any warnings from your Frontend code will break the pipeline when doing a publish.

Either fix all warnings or set the env var `CI=false` in your pipeline.
