### ISSUE TITLE
Schema change error in a new environment

### ISSUE THREAD

**Issue by ayeganyan** [aws-amplify/amplify-cli#6192]
**Describe the bug**
Getting schema change error in the new environment

**Amplify CLI Version**
4.40.0

**To Reproduce**
1. Change key schema in schema.graphql
2. Add new environment
```
Do you want to use an existing environment? No
? Enter a name for the environment testa
Using default provider  awscloudformation
```
3. Push environment
```
amplify push --y
```
An error is reported:
```
Attempting to edit the key schema of the InvitationTable table in the Invitation stack. 
An error occurred during the push operation: Attempting to edit the key schema of the InvitationTable table in the Invitation stack. 
```
**Expected behavior**
User should be able to push any schema in new environment

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. v10.19.0

**Additional context**

**Comment by ayeganyan** [comment]
Error exists even if I did not change anything 
In 4.29.8 as well

**Comment by yuth** [comment]
@ayeganyan do you have an env with name `testa` already in the project? If there is an existing environment with the same name in `<project-root>/amplify/team-provider-info.json`, the CLI does not create an new environment. If you want to recreate the environment please run `amplify env remove <env-name>` and then add it back

**Comment by ayeganyan** [comment]
That was completely new environment...
I tried with new environments several environment, and finally reverted all my changes I have made after last successful deployment, and removed auto-generated "#current-cloud-backend", amplify-meta.json, awscloudformation folders, so it seems issue occurred  because of environment info did not cleaned up from previous environment.

**Comment by ayeganyan** [comment]
I am facing issue again, as you can see graphqlapi is in Create state:
```
amplify push --y
✔ Successfully pulled backend environment develop from the cloud.

Current Environment: develop

| Category | Resource name                  | Operation | Provider plugin   |
| -------- | ------------------------------ | --------- | ----------------- |
| Auth     | authentication                 | Create    | awscloudformation |
| Auth     | userPoolGroups                 | Create    |                   |
| Api      | graphqlapi                     | Create    | awscloudformation |
....
| Function | invitationQueueTrigger         | Create    | awscloudformation |
| Storage  | storage                        | Create    | awscloudformation |
| Queue    | postConfirmationQueue          | Create    | awscloudformation |
| Queue    | invitationQueue                | Create    | awscloudformation |

The following types do not have '@auth' enabled. Consider using @auth with @model
         - Policy
Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth

✖ An error occurred when pushing the resources to the cloud

Attempting to edit the key schema of the TenantTable table in the Tenant stack. 
An error occurred during the push operation: Attempting to edit the key schema of the TenantTable table in the Tenant stack. 
```

**Comment by ayeganyan** [comment]
It worked fine after I remove #current-cloud-backend folder

**Comment by yuth** [comment]
Sanity check needs to be run only if the resource is being updated, irrespective of the content that is in the #current-cloud-backend. I am marking this as bug
