### ISSUE TITLE
Access denied when creating SQS as custom resource

### ISSUE THREAD

**Issue by ayeganyan** [aws-amplify/amplify-cli#6194]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Access denied when creating SQS as custom resource when pushing the environment

**Amplify CLI Version**
4.40.0

**To Reproduce**
I have added custom SQS resource which worked fine as of 12 December.
However now I am getting the following error when pushing the environment:
```
CREATE_FAILED queuepostConfirmationQueue AWS::CloudFormation::Stack Wed Dec 16 2020 10:02:43 GMT+0400 (Armenia Standard Time) Embedded stack arn:aws:cloudformation:us-west-2:822798142733:stack/amplify-xxxxxx-testa-94446-queuepostConfirmationQueue-15LXOIQ3ZPFBM/492f7ae0-3f64-11eb-b8f9-06519b4450d1 was not successfully created: The following resource(s) failed to create: [SQS]. 
```
Note: The SQS deploys fine with the following command:
```
aws cloudformation deploy --template-file amplify/backend/queue/postConfirmationQueue/postConfirmationQueue-cloudformation-template.json --stack-name testSQS --parameter-overrides "env=test"
```

**Expected behavior**
User should be able to push custom resource

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version: v10.19.0

**Additional context**

**Comment by ayeganyan** [comment]
Downgrading to aws-amplify/cli@4.29.8 fixed this issue.

**Comment by yuth** [comment]
@ayeganyan could you include the CFN errors from the nested SQS stack to help us narrow down the issue

**Comment by ayeganyan** [comment]
Sorry for attaching wrong message on the ticket description, 
I don't have the issue anymore as I downgraded it, however, the message contained the below line (and that was the only error):
```
Access to the resource https://sqs.us-west-2.amazonaws.com/ is denied.
```

**Comment by kaustavghosh06** [comment]
@ayeganyan Were you able to root-cause this or still stuck with CLI v 4.28?

**Comment by Raees678** [comment]
Were you ever able to figure this out? Just a few weeks ago I was successfully able to create an SQS queue. However I tried to switch to create a new environment and am now unable to do so with Amplify. It fails with the same error.
