### ISSUE TITLE
Storage bucket is not clean up after failed push

### ISSUE THREAD

**Issue by ayeganyan** [aws-amplify/amplify-cli#6195]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Storage bucket is not clean up after failed push

**Amplify CLI Version**
4.29.8

**To Reproduce**
1. Create new environment 
2. Add s3 storage resource 
3. Add graphql resource which will fail on push 
4. push the environment
After failing command, push one more time and will have the following error:
```
CREATE_FAILED   storagestorage                  AWS::CloudFormation::Stack Wed Dec 16 2020 10:55:44 GMT+0400 (Armenia Standard Time) Embedded stack arn:aws:cloudformation:us-west-2:XXXXXXXXX:stack/amplify-XXXXX-testa-94446-storagestorage-IO4NVU4IWOBA/b175a5a0-3f6b-11eb-97d4-02400ead0b83 was not successfully created: The following resource(s) failed to create: [S3Bucket].
```

This is due to bucket is already created in the last push and did not deleted when it fail.

**Expected behavior**
Storage category bucket created in push should be removed if category status remains "created"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version v10.19.0

**Additional context**

**Comment by yuth** [comment]
Amplify CLI adds bucket with the DeletionPolicy `Retain` for S3 buckets so that the content of the bucket does not get deleted as the bucket may contain important data. 

But the bucket should be deleted when the push itself fails when adding a new storage bucket. I am marking this as an bug and add to our backlog

**Comment by josefaidt** [comment]
Closing in favor of tracking documented bug https://github.com/aws-amplify/amplify-cli/issues/10018
