### ISSUE TITLE
plugin type details url is 404

### ISSUE THREAD

**Issue by watilde** [aws-amplify/amplify-cli#6196]
**Describe the bug**
When I run `amplify plugin init` and select `Learn more`, cli suggested to see https://docs.amplify.aws/cli/usage/plugin and it is **404** page. I think it should show https://docs.amplify.aws/cli/plugins/architecture#plugin-types isntead and made PR: https://github.com/aws-amplify/amplify-cli/pull/6120.

**Amplify CLI Version**
v4.40.0

**To Reproduce**
1. Run `amplify plugin ini`
2. Select `Learn more`
3. See the URL

**Expected behavior**
It should show valid page.

**Screenshots**
<img width="825" alt="Screen Shot 2020-12-16 at 17 51 41" src="https://user-images.githubusercontent.com/1716463/102326148-60341580-3fc7-11eb-98d3-29ac5a8f591c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version: v14.13.0

**Comment by ammarkarachi** [comment]
@watilde Good catch!, I will merge the PR. Thanks for your contribution.
