### ISSUE TITLE
Unable to export the ARN value of a cloudformation resource using a custom cloudformation template using Amplify CLI

### ISSUE THREAD

**Issue by hirenumradia** [aws-amplify/amplify-cli#6197]
**Describe the bug**
I am trying to create custom templates within my Amplify application. However, while trying to push the sample template from the CLI I am observing the following error “An error occurred during the push operation: No such resource AWS::EFS::AccessPoint”.

**Amplify CLI Version**
4.38.2

**To Reproduce**
Please see the sample template:
[https://www.dropbox.com/s/1u40ze8w6jkl5jl/template.json.zip?dl=1](Sample Template)

When I try to do an amplify push from the CLI it fails and gives the error "No such resource AWS::EFS::AccessPoint". The issue happens when I add an Outputs sections and try to get the Arn of the "AWS::EFS::AccessPoint" in the template.

**Expected behaviour**
The stack should deploy correctly and

**Screenshots**
![image](https://user-images.githubusercontent.com/2716293/102337699-b9ca1f00-3f8a-11eb-8423-e071a56091ce.png)

**Desktop (please complete the following information):**
 - OS: Mac OSx 10.15.7
 - Node Version. v12.18.3

**Additional context**
There was another similar issue but it didn't seem to have a resolution:
https://github.com/aws-amplify/amplify-cli/issues/4453

**Comment by ammarkarachi** [comment]
@hirenumradia This is an issue with `cfn-lint` in CLI package we are using we will have to incorporate a different way to lint cfn files before push.
