### ISSUE TITLE
amplify push returns error: The "path" argument must be of type string

### ISSUE THREAD

**Issue by dcp3450** [aws-amplify/amplify-cli#6198]
**Describe the bug**
Any command to talk outside of local returns the error: `An error occurred during the push operation: The "path" argument must be of type string. Received an instance of Error`. Including `amplify env pull --restore` and `amplify push`.

I've updated CLI to the latest version to be sure

**Amplify CLI Version**
4.40.0

**Expected behavior**
commands would run without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 12.16.1

**Comment by yuth** [comment]
@dcp3450 would you mind sharing the content of `<project-root>/amplify/.config/local-env-info.json`. Please make sure you redact any sensitive information before sharing it here. 

What categories do you have in your project.

**Comment by eioo** [comment]
I'm experiencing this issue when running `amplify init`

**Comment by yuth** [comment]
> I'm experiencing this issue when running `amplify init`

@eioo is this a new project? What version of Amplify CLI do you have installed?

**Comment by eioo** [comment]
I trie

> > I'm experiencing this issue when running `amplify init`
> 
> @eioo is this a new project? What version of Amplify CLI do you have installed? And what is the OS that you're using to run Amplify CLI

New project, yes. I tried first with latest version from NPM, which is 4.40.0, gave the same error as OP had. I installed 4.29.0 and the init command ran smoothly.

**Comment by Olusamimaths** [comment]
I had this same issue and it was because my internet was down.

**Comment by danigb** [comment]
In my case, I've solved by removing the "dev" environment from `amplify/team-provider-info.json` file 🤷‍♀️ May help others...

**Comment by yuth** [comment]
I think this error shows up when there is an network error when downloading current-cloud backend. https://github.com/aws-amplify/amplify-cli/pull/6216 should fix this

**Comment by yuth** [comment]
> > > I'm experiencing this issue when running `amplify init`
> > 
> > 
> > @eioo is this a new project? What version of Amplify CLI do you have installed? And what is the OS that you're using to run Amplify CLI
> 
> New project, yes. I tried first with latest version from NPM, which is 4.40.0, gave the same error as OP had. I installed 4.29.0 and the init command ran smoothly.
> 
> I'm running MacOS 10.15.6.

@ eioo  Do you remember the error message. Did it contain `Received an instance of Error` in it?

**Comment by yuth** [comment]
The fix should be included in the next release (after Amplify CLI 4.40.0)
