### ISSUE TITLE
Could not initialize 'dev': The "path" argument must be of type string. Received an instance of Error

### ISSUE THREAD

**Issue by stleon** [aws-amplify/amplify-cli#6200]
**Describe the bug**

$amplify env pull --restore (or amplify env checkout dev)
Fetching updates to backend environment: dev from the cloud.Could not initialize 'dev': The "path" argument must be of type string. Received an instance of Error

**Amplify CLI Version**
4.40.0

**To Reproduce**
I just copy cloudformation-template.json from one project to another.

**Expected behavior**
Moves mine environment to the environment specified in the command (checkout)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v15.3.0

**Additional context**
Deleting of project and creating it from scratch helped me for the first time with this bug.

**Comment by dwamianm** [comment]
@stleon When I had this error in the past I remove the `#current-cloud-backend` and then do an `amplify env checkout <env>` and it fixed it. 

based on your reproduction steps it's also possible you may need to run `amplify configure` again... have not tested to reproduce

I also have a little utility bash script I wrote that cleans everything...see below. 

<pre>
#!/bin/bash

rm -Rf amplify/backend/api/<gql-resource-name>/build
rm -Rf "amplify/#current-cloud-backend"
rm -Rf amplify/mock-data/dynamodb/*
rm -Rf amplify/mock-data/S3/*

echo 
read -p "What is the name of the environment you want to checkout: " env
ENV=$env

# now make sure we have checked out to rebuild the #curren-cloud-backend folder
amplify env checkout ${ENV}

# And now remove all the cognito users
./tools/delete_cognito_users.sh
</pre>

hope it helps you.

**Comment by yuth** [comment]
This looks similar to issue https://github.com/aws-amplify/amplify-cli/issues/6198. Marking this as duplicate.

**Comment by cmcgruder** [comment]
I'm following an [aws tutorial](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/) and when prompted to deploy to the live environment (AWS), I run 'git push origin master'. I'm receiving the same path error as initially described and have attached a screen capture. Please re-open this incident, as the others you've pointed to don't seem to be duplicates. If they are, please provide the solution.
<img width="880" alt="Screen Shot 2020-12-18 at 3 52 28 PM" src="https://user-images.githubusercontent.com/4771458/102668772-03149d00-414a-11eb-915f-e3516fffafe0.png">
