### ISSUE TITLE
Lambda resolver getting access to the whole result?

### ISSUE THREAD

**Issue by tgjorgoski** [aws-amplify/amplify-cli#6208]
I am experimenting with lambda resolvers in the schema.
I have something like this:
```gql
type Document @model
{
    id: ID!
    title: String!
    page1: Page
    page2: Page
    summary: String @function(name="summary-service") 
}

type Page @model {
   id: ID!
   caption: String!
   text: String!
}
```

The idea is that when a user sends a query, in addition to the info about the document and the pages, the lambda function (summary-service) will analyse the results too, and in the summary field return a dynamically generated summary.
But when I added a **summary-service** lambda which had something like this:
```js
export const generateSummary = async (event, _context) => {
    console.log(event.source);
```
and when I sent query like:
```gql
query {
 getDocument(id: "..") {
    title
    page1 {
       caption
       text
    }
    page 2 {
       caption
       text
    }
   summary
 }
}
```
I got proper results for all fields, but summary lambda didn't work as expected. When I looked in summary-service lambda log, it turns out **event.source** contains data just on the level of the Document type (same level on which the function is attached in the schema) - in this case just "title", **and doesn't** contain data for page1 and page2.

What is the reason for this? What is the order by which the fields in one type are resolved?
Is there something I can do to ensure that when the lambda is called that event.source contains all the other fields resolved? 
Maybe it can e be done by writing custom resolvers?

**Comment by yuth** [comment]
The source is available only to the nested object and not at the top level as it is a map that contains the resolution of the parent field. Since summary is at the root level, source will not have any data set in it

**Comment by tgjorgoski** [comment]
@yuth , there is a parent resolver for the getDocument I think, and the summary lambda resolver is its child resolver, so that's why I was getting "title" in the event.source. From your answer, I'm understanding that there is no way/setting in which the lambda function can take the rest of the info.

How about this, what if I create additionaly something like:
```
type DocumentWithSummary {
   document: Document  
}
query {
   getDocumentWithSummary(id: ID!) : DocumentWithSummary
}
```

Is it possible that I specify pipeline resolver for the getDocumentWithSummary, in which the first function will be just the regular getDocument resolver, and the second function will be lambda. Will that lambda then as input get the fully "resolved" document data, in which I can additionally update summary field?

**Comment by yuth** [comment]
@tgjorgoski 

> Is it possible that I specify pipeline resolver for the getDocumentWithSummary, in which the first function will be just the regular getDocument resolver, and the second function will be lambda. Will that lambda then as input get the fully "resolved" document data, in which I can additionally update summary field?

Yes. With pipelines, you can set the value in `$$ctx.stash` or you can use `$ctx.prev.result` to get the values from the previous AppSync function that was executed
