### ISSUE TITLE
"amplify update storage" drops the s3 path from the cloudformation template

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#6211]
**Describe the bug**
I had a storage resource already configured in my project and wanted to allow users of a certain group to be able to upload filed to S3 so i did the following:
```
amplify update storage
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Restrict access by? Both
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? read
? Select groups: administrators, instructors, orgAdmin, orgManager, orgManagerLimited, orgMember
? What kind of access do you want for administrators users? create/update, read, delete
? What kind of access do you want for instructors users? create/update, read
? What kind of access do you want for orgAdmin users? read
? What kind of access do you want for orgManager users? read
? What kind of access do you want for orgManagerLimited users? read
? What kind of access do you want for orgMember users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? No
```

Here's a portion of the generated diff:

![Screen Shot 2020-12-17 at 10 03 47 PM](https://user-images.githubusercontent.com/11936077/102572558-74a50a80-40ba-11eb-9a41-e058789435c9.png)

As you can see the path was dropped from the resource name which is a security issue.

My current version is 4.39.0. The original template was generated in mid 2020, not sure about the exact version.

**Comment by yuth** [comment]
@krikork which policy is this? Is this for auth/unauth user or is it for a cognito user pool group? From the screenshot its hard to make out the name of the policy

**Comment by krikork** [comment]
Hi @yuth, this is for cognitive user pool group.

**Comment by akshbhu** [comment]
Hi @krikork 

Can you specify which user group is this policy belongs to as it is been cropped in image?

> As you can see the path was dropped from the resource name which is a security issue.

This isnt a security isssue as the Resource element in the IAM policy  specifies  ```arn:aws:s3:::Ref{S3Bucket}/ *```  for the GetObject, PutObject, and DeleteObject actions so that applications can read, write, and delete any objects in the test bucket.

You can get more information here: https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/

**Comment by akshbhu** [comment]
Closing due to lack of response. Feel free to comment and I will reopen this issue
