### ISSUE TITLE
Cannot read property 'join' of null An error occurred during the push operation: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by ayeganyan** [aws-amplify/amplify-cli#6213]
I am having this message on "amplify pull" command.
```
Cannot read property 'join' of null
An error occurred during the push operation: Cannot read property 'join' of null
```
Note:
When I do "amplify pull --force"
I am getting "adminQueriesxxx" function, the one that I deleted manually, but its not appears in backend-config.jon, and is not present in lambda console.

Before this I wanted remove admin queries and userpoolgroups via CLI which was not work, so I removed everything related to them from my local files.
To make sure the reason is not in inconsistency between my local changes and env I added fresh env and tried to push again, and get the same error.

Is there a way/workaround to fix the environment just to make it work (some repair), even if it affect your code locally? 
I wonder what I'll do if something like this will happen in production... ¯\_(ツ)_/¯

**Comment by ayeganyan** [comment]
I assume the reason is amplify project do some resource caching.
Is it possible clean it up, or create new app with existing local changes?

**Comment by yuth** [comment]
@ayeganyan this looks similar to issue #6198. I havent been able to reproduce this, but if you could provide stack trace it would make it easier for me to figure out which part of the code is causing this.

> Before this I wanted remove admin queries and userpoolgroups via CLI which was not work, so I removed everything related to them from my local files.
> To make sure the reason is not in inconsistency between my local changes and env I added fresh env and tried to push again, and get the same error.

Which files did you delete to remove admin queries? If you changed it in the AWS console, then these resources will be recreated with the next push as CLI treats `amplify/backend` folder as source of truth

**Comment by kaustavghosh06** [comment]
@ayeganyan I recently ran into this issue. This happened since I didn't have `npm` installed on my machine and the CLI was trying to run `npm install` on my NodeJS Lambda functions before pushing. Do you have npm installed and what OS are you using?
