### ISSUE TITLE
CloudWatch logs don't show identity in context

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#622]
** Which Category is your question related to? **
AppSync, CloudWatch

** What AWS Services are you utilizing? **
AppSync, CloudWatch

** Provide additional details e.g. code snippets **
I enable CloudWatch logs, run live queries from AppSync console, click "VIEW IN CLOUDWATCH" from the right bottom and access the cloudwatch stream.

As I am planning to add some authentication, I care about `$context.identity`. However, from the log, there is no such `identity`get printed. The `$context` looks like:
```
    "context": {
        "arguments": {
            "id": "c35f1f04-8d24-4977-98de-58dc3b0a2378"
        },
        "result": {
            "owner": "evan",
            "createdAt": "2018-12-01T16:43:46.528Z",
            "inventoryType": "apparels",
            "itemName": "No image 843",
            "__typename": "Item",
            "id": "c35f1f04-8d24-4977-98de-58dc3b0a2378",
            "updatedAt": "2018-12-01T16:43:46.528Z"
        },
        "stash": {},
        "outErrors": []
    },
```
which doesn't align with what described in [doc](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#accessing-the-context):
```
{
   "arguments" : { ... },
   "source" : { ... },
   "result" : { ... },
   "identity" : { ... },
   "request" : { ... }
}
```
But if I modify my resolver, it turns out that the `$context.identity` works as expected. So I guess context.identity still exists, it is simply not logged. Why? And how to log context.identity in CloudWatch?

**Comment by UnleashedMind** [comment]
Hi @YikSanChan 
You question is for the AWS AppSync service, please log it in the aws forum:
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)
