### ISSUE TITLE
No such file or directory on aws mock

### ISSUE THREAD

**Issue by wispyco** [aws-amplify/amplify-cli#6222]
**Describe the bug**
My app was working fine locally, and then I ran amplify push and I got the following response

```
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/anders/amplify/kin-recipes/amplify/#current-cloud-backend/api/kinrecipes'
```
I then ran amplify mock again and got this response

```
(node:35367) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/anders/amplify/kin-recipes/amplify/#current-cloud-backend/api/kinrecipes'
(node:35367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not sure what changed to cause this, because it was running just fine before I tried to push it

**Amplify CLI Version**
4.40.0

Running Ubuntu 20 with node version 12.18.0

I had been following this tutorial and things were working up until the final push

https://www.youtube.com/watch?v=HZUlQ7Z2xHQ

**Comment by wispyco** [comment]
Ok so I just ran 

amplify delete

and reran through the steps and this time it pushed up so not sure what went wrong

**Comment by akshbhu** [comment]
Hi @wispyco 

Glad to know it worked for you. I am closing this as it seems to be solved.  If this issue occurs, feel free to comment, and ill reopen this again.
