### ISSUE TITLE
DataStore - Validation error of type MissingFieldArgument: Missing field argument owner for Subscription and Sync

### ISSUE THREAD

**Issue by getglad** [aws-amplify/amplify-cli#6230]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When using the below schema
```
type Recipe
  @model
  @auth(rules: [
    { allow: owner, provider: oidc, identityClaim: "sub" }
  ]) {
  id: ID!
  name: String
  description: String
  ingredients: [Ingredient] @connection(keyName: "byRecipe", fields: ["id"])
  sourceType: String
  source: Source @connection
}
```

I get the below error:

```
DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateRecipe'"}]}
DataStore - Sync error Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateRecipe'"}]}
```

The record is created locally, but does not push. Because it cannot push, also cannot get 

**Amplify CLI Version**
`4.40.1`

**To Reproduce**
1. Create an API with an OIDC auth + `AUTOMERGE` conflict resolution
2. Run `node amplify/scripts/amplify-modelgen.js` + `amplify push`
3. Launch the application and obverse the console

**Expected behavior**
No error in console, the records push and pull correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: `v14.15.3`

**Additional context**
Cognito authentication looks correct (no auth errors messages) and JWT token can authenticate through the AppSync console, so my best guess is that this is something to do with the schema. Happy to provide any other insights.

**Comment by akshbhu** [comment]
Hi @getglad 

AFAIK your schema looks fine. There is one catch when using subscriptions with @auth.You can check the documentation here: https://docs.amplify.aws/cli/graphql-transformer/auth#authorizing-subscriptions

> The record is created locally but does not push. Because it cannot push, also cannot get

 I have the following questions for the above quote

1. Can you check if your data is present in dynamo DB? 

2. Have you tried running these queries/mutations on Appsync Console?

**Comment by getglad** [comment]
Hey @akshbhu - got some traction on this with the `js` team and it looks like it is actually a JS library problem, not anything generated by the CLI, so closing this - thanks! 

For reference - https://github.com/aws-amplify/amplify-js/issues/7435#issuecomment-751514968
