### ISSUE TITLE
@auth on non-@model fields fails on first push

### ISSUE THREAD

**Issue by Risord** [aws-amplify/amplify-cli#6231]
**Describe the bug**
Amplify push fail in non-deterministic way when inserting new type with field with auth rule.

**Amplify CLI Version**
4.40.1

**To Reproduce**
Add next declaration to schema.graphql:

```
type TestType {
  testField: String! @auth(rules: [{ allow: public }])
}
```

`amplify push`

Will fail with error message:
```
Resource Name: TestTypetestFieldResolver (AWS::AppSync::Resolver)
Event Type: create
Reason: Type TestType not found (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: <Request-ID>; Proxy: null)
```

Try again without auth rule:
```
type TestType {
  testField: String!
}
```

`amplify push`

This works and now we can use original schema with auth rule:
```
type TestType {
  testField: String! @auth(rules: [{ allow: public }])
}
```

`amplify push`

And exactly same schema works now.

**Expected behavior**
It should work on first run and applying schema should be deterministic.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 14.15.0

**Comment by kaustavghosh06** [comment]
@Risord That might be because you're missing @model on your type? Is that intentional?

**Comment by Risord** [comment]
> @Risord That might be because you're missing @model on your type? Is that intentional?

@kaustavghosh06 it is intentional. I think @model maps to db table but you might want have other types too in your schema for example with lambda resolvers.

**Comment by Risord** [comment]
@edwardfoyle @auth rules on non-@model fields are already allowed, in certain cases those are required and already working fine.
Only issue is that you have to apply such schema in two phases.
Therefore current classification as "enchanment" or current title does not make much sense.

**Comment by edwardfoyle** [comment]
Yep you're right. I mis-read the description. Marking as a bug

**Comment by studiobrain** [comment]
So to understand correctly, as I have seen similar errors and cant seem to find a definitive answer, an Amplify created api and GraphQL schema:

`amplify add api`

...can have types with no @model directive and still utilize the @auth directive - and we should see no errors on push?

for example:
```
type Post @auth(rules: [{ allow: private, provider: iam }]) {
  id: ID!
  title: String!
}
```

**Comment by Risord** [comment]
@studiobrain yes but as issue says you have to push your type once without auth rules. Also if I remember correctly type level auth rules did not work at all but field level rules worked so you need to use those.

So first push:
```
type Post {
  id: ID!
  title: String!
}
```

And then:
```
type Post {
  id: ID! @auth(rules: [{ allow: private, provider: iam }])
  title: String! @auth(rules: [{ allow: private, provider: iam }])
}
```
 
Be aware from caveats caused by this bug:
If you add new fields later you need to again push those too first without auth rules. Aaand my "favourite part" is that push fails same way for every environment regardless are you pushing manually or with CI/CD. Therefore be prepared to push cripled partial schemas manually to production or by "decoy commits" so that CI/CD does not fail.

**Comment by studiobrain** [comment]
So in summation, yes and no, but mostly no...  Also, no.

**Comment by cjihrig** [comment]
This appears to be resolved with v2 of the GraphQL Transformer.

**Comment by THPubs** [comment]
@cjihrig Any ETA for the fix to be released?
