### ISSUE TITLE
Access s3 file from signed URL from China

### ISSUE THREAD

**Issue by giorgiocarniel** [aws-amplify/amplify-cli#6232]
Not sure if this is the correct repo to ask but please tell me if there are more suitable channels to ask this question.

I have an Amplify application with a storage resource. 
I also have a Lambda that when called, creates a signed URL to download an s3 file. 

When downloading the file from the generated URL for me It works correctly, but my vendors located in China tell me they get "Request timed out".
Is it a common problem when accessing s3 from China?

I'm on eu-central-1 (Frankfurt).

**Comment by ammarkarachi** [comment]
@giorgiocarniel Someone from the aws forums would be better suited to help you: https://forums.aws.amazon.com/index.jspa

**Comment by giorgiocarniel** [comment]
Btw, they solved it by changing DNS address
