### ISSUE TITLE
amplify-cli no prompt for MFA token

### ISSUE THREAD

**Issue by jdw88** [aws-amplify/amplify-cli#6233]
**Describe the bug**
I'm using an AWS profile to assume a role as per the following configuration...

```
[profile amplify-staging]
mfa_serial=<arn>
source_profile=jamie-amplify
role_arn=<arn>
region=us-east-1
```
When running `amplify push` I am not prompted for an MFA token. 

**Amplify CLI Version**
```
$ amplify -v
4.40.1
```

**To Reproduce**
Running `amplify push` 
```
 $  amplify push
⠋ Fetching updates to backend environment: staging from the cloud.Profile amplify-staging is configured to assume role
  <role_arn>
It requires MFA authentication. The MFA device is
  <mfa_serial>
```
There is no prompt for an MFA token, however, I eventually noticed that the prompt is just not visible, i.e. is still waiting for input. However, it can take several attempts for the cli to register the input...

```
 $  amplify push
⠋ Fetching updates to backend environment: staging from the cloud.Profile amplify-staging is configured to assume role
 <role_arn>
It requires MFA authentication. The MFA device is
  <mfa_serial>
? Enter the MFA token code: 752983
⠏ Fetching updates to backend environment: staging from the cloud.Profile amplify-staging is configured to assume role
  <role_arn>
It requires MFA authentication. The MFA device is
  <mfa_serial>
? Enter the MFA token code: 879594
✔ Successfully pulled backend environment staging from the cloud.

Current Environment: staging
```

**Expected behavior**
Prompt for MFA token and proceed with deployment. 

**Desktop (please complete the following information):**
 - OS: Mac (MacOS Catalina 10.15.7)
 - Node Version:
``` 
$ node -v
v12.19.0
```

**Comment by jdw88** [comment]
*Update*

If there are pending changes in your environment, you're prompted to select whether or not you want to continue with the deployment. It seems you need to provide another auth token after this...
```
? Are you sure you want to continue? Yes
⠸ Updating resources in the cloud. This may take a few minutes...Profile amplify-staging is configured to assume role
  <role_arn>
It requires MFA authentication. The MFA device is
  <mfa_serial>
? Enter the MFA token code: <token>
⠙ Updating resources in the cloud. This may take a few minutes
```

Not sure if the credentials are being cached correctly? after a successful auth the cache file appears like so...

```
{
    "<role_arn>": {}
}
```

**Comment by Jupdi** [comment]
Got the same issue. Added Storage to a new project and im not able to push it. Need to go around the long way and deploy it via the console.

**Comment by Jupdi** [comment]
Still got the same issue, using Version 4.41.1 

```
amplify push
⠋ Fetching updates to backend environment: dev from the cloud.Profile test is configured to assume role
  arn:aws:iam:xxxxxxxx:role/xxxxxxx-role
It requires MFA authentication. The MFA device is
  arn:aws:iam::xxxxxxx:mfa/xxxxxxx
```
⠦ Fetching updates to backend environment: dev from the cloud.

**Comment by zvaraondrej** [comment]
I can confirm the same issue. It took us quite some time to figure it out... It would be awesome if this could get fixed! Many thanks!

```
node -v
v14.15.1

amplify version
4.41.2

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
```
