### ISSUE TITLE
Can't remove a postConfirmation trigger

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6238]
**Describe the bug**
I generated a cognito postconfirmation trigger lambda. I want to remove it. I go through the options, and de-select my trigger.
<img width="369" alt="Screenshot 2020-12-23 at 01 20 07" src="https://user-images.githubusercontent.com/6759894/102945145-385c1a80-44bd-11eb-90bc-d5d8e2b059f4.png">
<img width="374" alt="Screenshot 2020-12-23 at 01 20 13" src="https://user-images.githubusercontent.com/6759894/102945148-3b570b00-44bd-11eb-9d3e-c72fcb9a2e7b.png">
Nothing changes, the function is still there, and I'm unable to delete it.
```
amplify remove function
```
<img width="1038" alt="Screenshot 2020-12-23 at 01 21 07" src="https://user-images.githubusercontent.com/6759894/102945196-5f1a5100-44bd-11eb-84b7-a8586c76ffc9.png">

**Amplify CLI Version**
4.40.1

**To Reproduce**
Add a custom postConfirmation trigger.
Try to remove it.

**Expected behavior**
The function should be removed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 12.20.0

**Comment by MontoyaAndres** [comment]
You can check the backend-config.json file to remove from the "Auth" the trigger from the array "dependsOn" . I don't recommend to do this, it's better with the cli, but if is necessary you can do it...

**Comment by akshbhu** [comment]
Hi @half2me 

Closing this issue as it seems to be fixed with this PR #6403
