### ISSUE TITLE
Codegen auto generate from schema is missing few fields

### ISSUE THREAD

**Issue by Pranav-Dakshina** [aws-amplify/amplify-cli#6241]
**Describe the bug**
When I download the `schema.graphql` file from `AWS AppSync`, and run `amplify codegen`; generated queries, and types doesn't match the schema

**Amplify CLI Version**
4.40.1

**To Reproduce**
`schema.graphql`
```
input GetAllItemsInput {
	limit: Int
	after: String
}

type GetAllItemsOutput {
	success: Boolean
	message: String
	code: String
	data: ItemConnection
}

type Item {
	id: ID
	created_at: AWSDateTime
	updated_at: AWSDateTime
}

type ItemConnection {
	items: [Item]
	after: String
	hasMore: Boolean
}

type Query {
	getAllItems(input: GetAllItemsInput): GetAllItemsOutput
}

```
and run `amplify codegen`

`API.ts`

```
export type GetAllItemsQuery = {
  getAllItems: {
    __typename: 'GetAllItemsOutput';
    code: string | null;
    data: {
      __typename: 'ItemConnection';
      after: string | null;
      hasMore: boolean | null;
    } | null;
    message: string | null;
    success: boolean | null;
  } | null;
};
```
`items` is missing in `ItemConnection`

**Expected behavior**
The generated `API.ts`

```
export type GetAllItemsQuery = {
  getAllItems: {
    __typename: 'GetAllItemsOutput';
    code: string | null;
    data: {
      __typename: 'ItemConnection';
      after: string | null;
      hasMore: boolean | null;
      items: Array<{
        __typename: 'Item';
        id: string | null;
	created_at: string | null;
	updated_at: string | null;
      } | null> | null;
    } | null;
    message: string | null;
    success: boolean | null;
  } | null;
};
```

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Node Version. v14.15.0

**Comment by akshbhu** [comment]
Hi @Pranav-Dakshina 

When you configured codegen , you are promped with this question : 
```Enter maximum statement depth [increase from default if your schema is deeply nested]```

You can statement depth > 2 so that it can generate nexted items.  This is skipped in your case as nested depth is set as 2.

What you can do is : 
1. run ```amplify configure codegen```
2. Configure above question for a depth > 2
3. run ```amplify codegen ``` again to generate code.

let me know if this works for you?

**Comment by Pranav-Dakshina** [comment]
Hi @akshbhu 

Thanks that made sense. It works 🎉 
I will close this issue
