### ISSUE TITLE
Cancelling a push or getting timeout seems to leave the app in an unknown state

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6242]
**Describe the bug**

When ```amplify push``` is interrupted it seems to cause issues with the known state of the application both locally and up in the cloud. 

Interruptions might be through a user killing the process or through a network timeout.

Does the process recover well to get both local and cloud instances in a known state so that the next push is valid.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**

Running an ```amplify push``` seems to take an age for me, average 7-10 minutes, which is a total dev flow killer. I've learnt through habit to always add on the ```--yes``` flag to pre-answer the prompts that pop up so I can at least get on with something else while its doing its thing.

Sometimes however through muscle memory I run this too soon and so have to cancel it with a Ctrl-C as soon as I realise. 

Why would I cancel it? Well often its when I know I've got an issue in my schema such as me having commented out the @searchable directives so I could mock my api locally and then wanting to push it up but I forgot to uncomment the directives, this would be bad. See https://github.com/aws-amplify/amplify-cli/issues/5981 for details of that gotcha. Another reason might be I see that my team mate has pushed and I need to pull first or I'll over-write their changes.

Secondly I work from two different locations currently, one of those has a flakey internet connection, some times it will drop out or just have a go slow mid push. When it does this it either hangs (so I kill it) or timesout (where it kills itself). When this happens I don't know what state it is left in.

I know I'm sometimes in an unknown state due to the amount of "that shouldnt' be happening" issues I seem to be running into.

https://github.com/aws-amplify/amplify-js/issues/7438
https://github.com/aws-amplify/amplify-cli/issues/6028
https://github.com/aws-amplify/amplify-cli/issues/6047

**Expected behavior**

Killing the push shouldn't leave the app in an unknown state. On the next attempt it should try again a fresh if its not flagged as having completed a good push.

A timeout shouldn't leave the app in an unknown state.

Now it could be its doing all the above wonderfully and I'm just unlucky but the only thing I can think of that could keep getting my app in a messed up state is a failed push so wanted to make sure its doing as it could/should if possible.

Additionally:

Ideally a push shouldn't take 7-10+ minutes (https://github.com/aws-amplify/amplify-cli/issues/5552 and https://github.com/aws-amplify/amplify-cli/issues/5964) it leads to me learning muscle memory that gets me in trouble, I know its my responsibility at the end of the day but they way it currently is setup its just waiting to catch me out.

@searchable should be mockable or ignored when mocking to stop me doing that (https://github.com/aws-amplify/amplify-cli/issues/5981), that would reduce my "oh no, STOP!" moments :)

A push should warn if there is newer stuff up on the cloud than local, I'd rather it failed (sort of like a git push) and told me to pull first than let me happily blitz what is up there deleting my teammates work (sometimes manual stuff like Auth keys and such) - this would also stop those "oh damn, STOP!" moments.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Additional context**

**Comment by ammarkarachi** [comment]
@PeteDuncanson with the stack you should be able to re-push if the stack has completed it's update/rollback. I am not entirely sure about the GSI update issues but I will get back to you on that.

Thanks for bringing this to our attention we are looking into ways to improve the push feature in the CLI

**Comment by PeteDuncanson** [comment]
@ammarkarachi what state is this issue now in? Its flagged as pending-response but is also closed?
