### ISSUE TITLE
auto-compile lambda in typescript during `amplify mock api`

### ISSUE THREAD

**Issue by jacobdubail** [aws-amplify/amplify-cli#6245]
**Which Category is your question related to?**
Function and API

**Amplify CLI Version**
4.40.1 

**What AWS Services are you utilizing?**
AppSync, Lambda

**Provide additional details e.g. code snippets**
I've converted a lambda to Typescript. I have a package script `"amplify:framePricingGet": "cd amplify/backend/function/framePricingGet && tsc -p ./tsconfig.json && cd -"` that works fine. What I'm hoping to do is have my typescript auto-compile during `amplify mock api` for testing. It's quite cumbersome to pause the `mock api` command, then run `tsc`, then restart `mock api`. 
Is there a way to hijack the events in `mock api` to run a custom script?

Thank you!

**Comment by akshbhu** [comment]
Hi @jacobdubail 

AFAIK there are no hacks to push this script as it will require some rework in mock category.
Can you not include this script and ```amplify mock api ``` in  some npm scripts?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further communication.
