### ISSUE TITLE
amplify pull error: Cannot read property 'defaultProject' of undefined

### ISSUE THREAD

**Issue by 9037568** [aws-amplify/amplify-cli#6246]
**Describe the bug**
When attempting to pull a newly created project via `amplify pull`, the command fails.

>amplify pull --appId redacted --envName staging
Opening link: https://us-east-1.admin.redacted.com/admin/redacted/staging/verify/
√ Successfully received Amplify Admin tokens.
Amplify AppID found: redacted. Amplify App name is: redacted
Backend environment staging found in Amplify Console app: redacted
Failed to pull the backend.
Cannot read property 'defaultProject' of undefined
TypeError: Cannot read property 'defaultProject' of undefined
    at getAngularConfig (C:\snapshot\node_modules\amplify-frontend-javascript\lib\framework-config-mapping.js:61:39)

**Amplify CLI Version**
4.40.1

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 14.15.3

**Comment by jhockett** [comment]
Hi @9037568, thanks for the bug report! I was able to reproduce it.

**Comment by jhockett** [comment]
To get unblocked, you can run the following:
```
npx -p @angular/cli ng new <root-of-project>
cd <root-of-project>
amplify pull --appId redacted --envName staging
```

See the [docs](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular) for more information.

**Comment by 9037568** [comment]
Thanks for the unblocking instructions. Very helpful.
