### ISSUE TITLE
Push timesout...and I've no idea why.

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6248]
**Describe the bug**

This is related to #6242 

I work in two places, one has no problem pushing. The other will often timeout when pushing. To the point that I often switch using my phone as a hot spot to get around it. This works but its killing my data plan!

Oddly at this place I have plenty of internet speed, its not metered and works good enough to run everything else I need. Ok so sometimes zoom will have a complaint every now and then about the connection but it copes. Amplify on the other hang often hangs and the times out. I don't understand why. At the time it hanged I did a speed test and had an upload speed of 18+Mbps.

It tries to upload the files and then 2 minutes later will error like so:

![image](https://user-images.githubusercontent.com/1674590/103042396-5d11ca00-4571-11eb-8697-38d868a3a8f5.png)

Switch to my phone and no issues. What could it be?

The logical answer is "this is a issue with your setup" but what on earth could that be? Is there anything in the code that might explain this happening? If it zips everything up I don't see how it could timeout, it can't be that big! Plus it works sometimes but not others so its not like there is a firewall here blocking something. Totally puzzled.

**Amplify CLI Version**

v4.40.1

**To Reproduce**

Fly to my girl friends house and try to push...

**Expected behavior**

It works like it does at home...

**Desktop (please complete the following information):**
 - OS: the dreaded Windows

**Additional context**

**Comment by jamesonwilliams** [comment]
@aws-amplify/amplify-cli mentioned that this may be related to https://github.com/aws-amplify/amplify-cli/issues/4113.

**Comment by kaustavghosh06** [comment]
@PeteDuncanson We've seen this issue before and this it's highly probably that this is caused due to Network issues like high latency, packet loss, and congestion as mentioned out here - https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/

As @jamesonwilliams suggested, could you please give the above mentioned network tools a try?

**Comment by PeteDuncanson** [comment]
The dodgy connection (which seems to be behaving itself at the mo):
![image](https://user-images.githubusercontent.com/1674590/103044645-40799000-4579-11eb-890a-bda2a2e5307b.png)

Mobile:

![image](https://user-images.githubusercontent.com/1674590/103044707-7454b580-4579-11eb-9641-85e26d5d7469.png)

 My home one will have to wait until tomorrow :)

**Comment by kaustavghosh06** [comment]
@PeteDuncanson Were you able to push with the network having no packet loss at the moment right now?

**Comment by PeteDuncanson** [comment]
@kaustavghosh06 yep, pushing again now to test again. If it happens again I'll run the same report, is that best way to narrow this down? I know its a tricky one to get to the bottom of an likely its at my end...but network stuff really isn't a strong point for me :)

**Comment by kaustavghosh06** [comment]
Yeah, we tried solving for this problem a few months back - https://github.com/aws-amplify/amplify-cli/pull/5158 by chunking down the files to be uploaded to S3 to avoid seeing this issue. 
But I think we need to come up with a better retry strategy as mentioned by @yuth out here - https://github.com/aws-amplify/amplify-cli/issues/4183#issuecomment-624835043 for this problem.

**Comment by kaustavghosh06** [comment]
@PeteDuncanson Closing this issue - please let us know if you're still seeing this often with a reliable network connection.
We're tracking the retry work I mentioned above as a part of this issue - #4183

**Comment by PeteDuncanson** [comment]
Little update on this one, I've had the internet line at home upgraded and got a new router. I've had no repeats of this issue since. Cause is very much a duff connection it seems. Thanks.

**Comment by PeteDuncanson** [comment]
Take it back, just happened again :(

Not sure what can be done about it. I tend to just tether to my phone and upload it via 4G!

**Comment by amcdnl** [comment]
I'm getting this too on wired fiber connection ...
