### ISSUE TITLE
amplify push stuck in PinpointFunctionOutputs step

### ISSUE THREAD

**Issue by mbahar** [aws-amplify/amplify-cli#625]
**Describe the bug**
amplify push stuck in PinpointFunctionOutputs step

**To Reproduce**
1. amplify init (ionic app)
2. amplify add analytics
3. amplify push

**Expected behavior**
Backend should be deployed

**Screenshots**
UPDATE_IN_PROGRESS fancytodos-20181224115035 AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:16 GMT-0800 (PST) User Initiated             
CREATE_IN_PROGRESS authcognito4d3984a8       AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:20 GMT-0800 (PST)                            
CREATE_IN_PROGRESS authcognito4d3984a8       AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:21 GMT-0800 (PST) Resource creation Initiated
CREATE_IN_PROGRESS analyticsfancytodos       AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:21 GMT-0800 (PST)                            
CREATE_IN_PROGRESS analyticsfancytodos       AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:21 GMT-0800 (PST) Resource creation Initiated
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS fancytodos-20181224115035-authcognito4d3984a8-RC4M26WXR9TN  AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:20 GMT-0800 (PST) User Initiated             
CREATE_IN_PROGRESS fancytodos-20181224115035-analyticsfancytodos-10AUCXB1OHUH3 AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:21 GMT-0800 (PST) User Initiated             
CREATE_IN_PROGRESS LambdaExecutionRole                                         AWS::IAM::Role             Mon Dec 24 2018 11:52:25 GMT-0800 (PST)                            
CREATE_IN_PROGRESS IdentityPool                                                AWS::Cognito::IdentityPool Mon Dec 24 2018 11:52:25 GMT-0800 (PST)                            
CREATE_IN_PROGRESS LambdaExecutionRole                                         AWS::IAM::Role             Mon Dec 24 2018 11:52:26 GMT-0800 (PST) Resource creation Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS IdentityPool                                               AWS::Cognito::IdentityPool               Mon Dec 24 2018 11:52:27 GMT-0800 (PST) Resource creation Initiated
CREATE_COMPLETE    IdentityPool                                               AWS::Cognito::IdentityPool               Mon Dec 24 2018 11:52:29 GMT-0800 (PST)                            
CREATE_IN_PROGRESS IdentityPoolRoleMap                                        AWS::Cognito::IdentityPoolRoleAttachment Mon Dec 24 2018 11:52:31 GMT-0800 (PST)                            
CREATE_IN_PROGRESS IdentityPoolRoleMap                                        AWS::Cognito::IdentityPoolRoleAttachment Mon Dec 24 2018 11:52:33 GMT-0800 (PST) Resource creation Initiated
CREATE_COMPLETE    IdentityPoolRoleMap                                        AWS::Cognito::IdentityPoolRoleAttachment Mon Dec 24 2018 11:52:34 GMT-0800 (PST)                            
CREATE_COMPLETE    fancytodos-20181224115035-authcognito4d3984a8-RC4M26WXR9TN AWS::CloudFormation::Stack               Mon Dec 24 2018 11:52:36 GMT-0800 (PST)                            
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    LambdaExecutionRole AWS::IAM::Role             Mon Dec 24 2018 11:52:41 GMT-0800 (PST)                            
CREATE_COMPLETE    authcognito4d3984a8 AWS::CloudFormation::Stack Mon Dec 24 2018 11:52:42 GMT-0800 (PST)                            
CREATE_IN_PROGRESS PinpointFunction    AWS::Lambda::Function      Mon Dec 24 2018 11:52:43 GMT-0800 (PST)                            
CREATE_IN_PROGRESS PinpointFunction    AWS::Lambda::Function      Mon Dec 24 2018 11:52:44 GMT-0800 (PST) Resource creation Initiated
CREATE_COMPLETE    PinpointFunction    AWS::Lambda::Function      Mon Dec 24 2018 11:52:44 GMT-0800 (PST)                            
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS PinpointFunctionOutputs Custom::LambdaCallout Mon Dec 24 2018 11:52:50 GMT-0800 (PST) 
⠹
**Desktop (please complete the following information):**
 - OS: iOS

**Comment by UnleashedMind** [comment]
What version of the cli are you using? 
There was a bug like this, but that bug has already been fixed.
