### ISSUE TITLE
[Bug] Amplify deploy fails and hangs with no resolution possible

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#6251]
**Describe the bug**
Amplify deploy fails with this error message:

```bash
UPDATE_COMPLETE functionrsc AWS::CloudFormation::Stack Thu Dec 24 2020 11:06:23 GMT+0800 (Singapore Standard Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      functionamplifyrscdemo1a862661 AWS::CloudFormation::Stack Thu Dec 24 2020 11:06:26 GMT+0800 (Singapore Standard Time) Resource creation cancelled                                
UPDATE_FAILED      apirsc                         AWS::CloudFormation::Stack Thu Dec 24 2020 11:06:26 GMT+0800 (Singapore Standard Time) Parameters: [authRoleName, unauthRoleName] must have values
UPDATE_IN_PROGRESS apirsc                         AWS::CloudFormation::Stack Thu Dec 24 2020 11:06:25 GMT+0800 (Singapore Standard Time)                                                            
⠦ Updating resources in the cloud. This may take a few minutes...
```

and then the CLI completely hangs with a very confusing message and doesnt terminate

![image](https://user-images.githubusercontent.com/6764957/103057439-713de180-45da-11eb-8b57-5efed5e48bd2.png)

**Amplify CLI Version**
4.39

**To Reproduce**
https://github.com/sw-yx/amplify-react-serverless-components/

**Expected behavior**
failures should be clear and resolution steps recommended.

**Screenshots**
as above. i also livestreamed my entire experience using the CLI for development. https://youtu.be/VA3TFymZlW4 error comes at the end. i cut the livestream short when i realized this error was not going to be resolvable.

**Comment by ammarkarachi** [comment]
@sw-yx Can you try the latest CLI version? it should be working in 4.40.0 and onwards.

**Comment by AlbertoSinigaglia** [comment]
I'm having the same problem in `V4.44.0`

**Comment by ryanbagwell** [comment]
same problem on 4.51.0
