### ISSUE TITLE
@aws_api_key Not applying to generated List queries or mutations

### ISSUE THREAD

**Issue by rewardle-jason** [aws-amplify/amplify-cli#6254]
**Describe the bug**
When API Key is set as an additional auth method to a graphql type, it's auto generated queries and mutations associated with the type fail with an access denied error when called with an access key.

**Amplify CLI Version**
amplify version is 4.39.0 on macos

**To Reproduce**
Create a demo amplify project following these instructions:
https://docs.amplify.aws/start/getting-started/setup/q/integration/js

When you get to the amplify add api step, pick the following options:
amplify add api 
? Please select from one of the below mentioned services: GraphQL
? Provide API name: **amplifyjsapp**
? Choose the default authorization type for the API **IAM**
? Do you want to configure advanced settings for the GraphQL API **Yes, I want to make some additional changes.**
? Configure additional auth types? **Yes**
? Choose the additional authorization types you want to configure for the API **API key**
API key configuration
? Enter a description for the API key: **backendaccess**
? After how many days from now the API key should expire (1-365): **7**
? Configure conflict detection? **No**
? Do you have an annotated GraphQL schema? **No**
? Choose a schema template: **Single object with fields (e.g., “Todo” with ID, name, description)**

The Change the graphql schema file to the following:
```
type Todo @model @aws_api_key {
  id: ID!
  name: String!
  description: String
}
```

Now do an amplify push.  Once done go to the console:
amplify console api

select authorisation provider as api key and try to run the following query:
```
query MyQuery {
  listTodos {
    items {
      id
      name
    }
  }
}
```

This results in an unexpected error:
Not Authorized to access listTodos on type Query

**Expected behavior**
I expect to be able to run the listTodos query without error

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.15.1

**Comment by kaustavghosh06** [comment]
@rewardle-jason You'd need to use the @auth directive - `@auth(rules: [{ allow: public }])` in the schema for your model for all the associated  queries, and mutations  tied to your model.
