### ISSUE TITLE
How to remove all deleteXXX mutation from graphql api?

### ISSUE THREAD

**Issue by ahtokca** [aws-amplify/amplify-cli#6255]
**Which Category is your question related to?**
GraphQL API

**Amplify CLI Version** 
4.28.2

**Provide additional details e.g. code snippets**
I have @auth notation like below.
```
@auth(
    rules: [
      {allow: owner, operations: [read, create, update]}
      {allow: private, provider: userPools, operations: [read, update, create]}
      {
        allow: private
        provider: iam
        operations: [read, update, create]
      }
    ]
  )
```
However it still **allows deletion**. Is there any way to remove delete mutation completely? Am I doing anything wrong?
Does it make sense to tweak api/../build/clouformation-template.json?

**Comment by kaustavghosh06** [comment]
@ahtokca How did you verify that it still sllows deletion. If you haven't explicitly mentioned `delete` the corresponding auth directives shouldn't be applied to the operations - are you not seeing that behavior?

**Comment by ahtokca** [comment]
@kaustavghosh06, Thanks for reply. Well, despite the fact that I explicitly removed 'delete' from allowed operations it still generates at api/my-api/build/schema.graphql with `deleteXXXX` mutations. If I execute the 'deleteXXXX' from react-native client than it perfectly deletes the item from table. Could it be linked to the multiple auth rules?

**Comment by kaustavghosh06** [comment]
Yeah, that's possible. Let us look into it.

**Comment by ahtokca** [comment]
it allows to create/delete even with the combination below.
```
@auth(
    rules: [
      {allow: owner, operations: [read]}
      {allow: private, operations: [read]}
    ]
  )
```
:(

**Comment by ahtokca** [comment]
here is the answer I get from aws support, I think the issue can be closed

> As per the documentation[1], when specifying operations as a part of the @auth rule, the operations not included in the list are not protected by default. Hence, removing an operation from the auth rules does not forbid it. Instead, that operation is no longer protected by the auth rule. For example, consider the following rule:
{allow: owner, operations: [read, create, update]}

> Here the owner is allowed to read, create and update objects. However, since 'delete' is not in the operations list, any authenticated user can delete the object. If we add delete to the above rule, only the owner of the object will be able to delete it. I have tested this at my end as well.

> Moving forward, as per my testing it seems that we cannot completely remove access to delete operation using @auth directive as the owner will always be allowed to perform all operations. Hence, in order to disable delete operation, we can remove the corresponding mutation from the schema. By default, when we use the @model directive, CRUDL queries and mutations are configured automatically. Up to 8 resolvers (create, update, delete, get, list, onCreate, onUpdate, onDelete) are generated. However, this is configurable via the queries, mutations, and subscriptions arguments on the @model directive. For example, the following schema would create and configure a single query field post(id: ID!): Post and mutations for update and create operations:
```
type Post @model(queries: { get: "post" }, mutations: {create: "createPost", update:"updatePost"}) {
    id: ID!
    title: String!
    tags: [String!]!
}
```
> I would suggest that you could modify your schema in a similar manner to generate the required queries, mutations etc without generating delete mutation. Please see [2] for more details on @model directive.

> References:
[1] https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization
[2] https://docs.amplify.aws/cli/graphql-transformer/model
```
