### ISSUE TITLE
Disable DataStore for entire API not working from Amplify CLI

### ISSUE THREAD

**Issue by dacarva** [aws-amplify/amplify-cli#6256]
**Description**
I am having some issues with Datastore and conflict detection. I am developing a web app where Datastore is not needed and it's causing some issues so I decided to remove it using the Amplify CLI. 

When I run the command amplify update api to disable Datastore for the entire API I get this error from IAM:

`UPDATE_FAILED               AuthRolePolicy01                                                            AWS::IAM::ManagedPolicy     Thu Dec 24 2020 07:58:38 GMT-0500 (Colombia Standard Time) API: iam:ListPolicyVersions User: arn:aws:sts::106906875273:assumed-role/us-east-2_sklHaVKuw_Full-access/amplifyadmin is not authorized to perform: iam:ListPolicyVersions on resource: policy arn:aws:iam::106906875273:policy/amplify-cannvestinvestorapp-dev-203535-apiCannvestInvestorApp-1H7CEUADMM4YB-AuthRolePolicy01-14T23PJMIKF22
`
What can I do?

**Amplify CLI Version**
4.40.1

**To Reproduce**
Run the following commands in the terminal:

amplify update api
**Please select from one of the below mentioned services**: GraphQL
**Select from the options below** Disable DataStore for entire API
amplify push

**Expected behavior**
A successful operation

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Node Version. 13.14.0

**Comment by kaustavghosh06** [comment]
@dacarva Looks like there's a IAM policy missing in an IAM role in your account. Could you please go tour AWS Account's IAM Console and add "iam:ListPolicyVersions" policy to the "us-east-2_sklHaVKuw_Full-access" IAM Role. That would let you push successfully.
