### ISSUE TITLE
Rollback of schema on deployment

### ISSUE THREAD

**Issue by iuyt9003** [aws-amplify/amplify-cli#6259]
A huge bug! When changing a schema field name ( which has a @connection directive) back and again to the same name, Causing AppSync to crush!

**Describe the bug**
I am using amplify with Api that uses graphql. I have in the table ( @model ) a field that has an @connection on it,
I have updated the field name to something (ABC for example...) then I have returned to the same name it was before 
(not ABC for example DAB...) what happens caused my app sync to break! 

the Appsync for the 30 first minutes worked good, all requests were handled the right way, tables were good.
but after that, it started to break!!!! when I moved to the app sync  (in the AWS website) I suddenly saw something terrifying.
the table had the previous connection name when I built the query.  So I moved back to the code. I was hitting Amplify pull 
I was thinking maybe I didn't change that, but no changes were received. 
I did amplify status, still, no changes detected. 
Finally, I have decided to use amplify push ( it showed me that the API changed, but when I was in the file it seems it hasn't
been changed ). so I push the changes. then it worked again. 

I will shorthand this,
amplify pull - NO changes detected ... 1 second after Amplify push ... changes detected in the API.

so far no clue. I am hoping you able to figure out what happens.

**Amplify CLI Version**
4.36.2

**To Reproduce**
1. In the schema change a field with @connection on it then change again it to the same name before.

**Expected behavior**
Appsync not to crush...

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12

**Additional context**
Contact me if need to show it.

**Comment by kaustavghosh06** [comment]
@iuyt9003 When you changed the field-name, I'm assumign you ran `amplify push`- did the push succeed in your terminal?

**Comment by iuyt9003** [comment]
It did succeed. and I was on the UI AppSync and saw the build worked. the field on the UI of the AppSync changed.
But then after 30 minutes I was on the AppSync again and saw the old format!!! with the old name. 
Then my API suddenly broke. and after that, I was doing 
1) amplify pull - no changes, 
2) amplify status - no changes,
3) amplify push - API changed??? But my local API file hasn't changed. and nothing had been pulled off, 
and status was no changes and pull. so that's was pretty wierd.

**Comment by iuyt9003** [comment]
Again!!! 
1) Amplify status - No changes.
2) Amplify push - API changed : OOO 

Whats going on, my env broken again.

![image](https://user-images.githubusercontent.com/23431551/103170475-3099ce80-484d-11eb-97af-5e8fa4e4fa3b.png)

**Comment by iuyt9003** [comment]
I am starting to thinking maybe it is related to preview on Amplify, Because my other teammate. haven't pulled from staging but he opened up a pull request and we have a preview on it that targets staging env. but it should take the latest version.

so I am not sure.

**Comment by edwardfoyle** [comment]
Can you try pulling the project in a new folder and then run `amplify status` and `amplify push`? It seems like your #current-cloud-backend folder may be out of sync with what's deployed in the cloud.

**Comment by iuyt9003** [comment]
yes, it's seems that it happen because of the preview section. in the UI.
my teammate hasn't pulled the latest change I did on the schema. so the Appsync has changed. and broken.

But he didn't amplify push, he had a preview that was running seems like somehow it was changing the Appsync. 

The preview is set to work with one of our env ( instead of creating a new env every time).

**Comment by kaustavghosh06** [comment]
@iuyt9003 Are you still seeing this? We weren't able to reproduce this behavior on our side. Please let us know.
