### ISSUE TITLE
Backend configuration lost after frontend deploy

### ISSUE THREAD

**Issue by 9037568** [aws-amplify/amplify-cli#6262]
NOTE: I can't tell whether this is a CLI or console problem, so I'm starting it here.

**Describe the bug**

I had configured the auth piece of my backend:

````
>amplify status
Current Environment: staging

| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Auth     | redacted       | No Change | awscloudformation |
````

But after I deployed a frontend via the web admin UI, that backend configuration was apparently lost:

````
>amplify status
Current Environment: staging

| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |

>
````

**Amplify CLI Version**
4.40.1

**To Reproduce**
Unconfirmed:
-- Configure backend with auth
-- Deploy frontend

**Expected behavior**
Backend configuration should not be lost when deploying frontend.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 14.15.3

**Comment by jhockett** [comment]
Hi @9037568, can you try running `amplify pull` and see what the result is?

**Comment by 9037568** [comment]
I tried that several times. The result was the same as shown above:

````
| Category | Resource name | Operation | Provider plugin |
| -------- | ------------- | --------- | --------------- |
````

**Comment by jhockett** [comment]
> But after I deployed a frontend via the web admin UI, that backend configuration was apparently lost

Can you provide more detail on what you did at this step? I think you mean Amplify console in this case. As far as I know, the admin UI doesn't have a frontend deploy feature.

**Comment by 9037568** [comment]
Too many things with the same name.
When I say "web admin UI", I'm referring to this:

![image](https://user-images.githubusercontent.com/9916473/103391711-d3ba4480-4ae8-11eb-9d9c-ee1de2dd87cf.png)

**Comment by jhockett** [comment]
My mistake then, that is in fact the admin UI. Can you explain what you did in the admin UI?

**Comment by 9037568** [comment]
I clicked the "frontend environments" tab, and deployed the frontend.

![image](https://user-images.githubusercontent.com/9916473/103392242-e2096000-4aea-11eb-8cdb-4d05aabff142.png)

**Comment by jhockett** [comment]
@9037568 sorry, I got confused. The page you are on is the Amplify console. The orange button that says "Open admin UI" brings you to the admin UI.

**Comment by jhockett** [comment]
So far I haven't been able to reproduce. Can you go into detail on the steps you took to configure `auth`?

**Comment by 9037568** [comment]
I don't know if I can recall it all in the right order.

I believe what I did was:

* Run `amplify add auth` from the CLI
* Push via `amplify push`
* Configure auth via the Admin UI
* Pull via `amplify pull` from the CLI
* Push application changes to CodeCommit
* Use the "Frontend environments" tab above to connect to CodeCommit and deploy the frontend

**Comment by kaustavghosh06** [comment]
@9037568 Are you still stuck on this issue?

**Comment by 9037568** [comment]
I "fixed" it by rebuilding from scratch, so I'm not stuck. But I'd still call this a big problem.

**Comment by kaustavghosh06** [comment]
@9037568 Glad you're not seeing this. Our team wasn't able to reproduce this issue unfortunately. 
If anyone else reports this or comments out here with the same issue, we can re-open and dig deeper.
