### ISSUE TITLE
Add Support for customizing GraphQL Input types when overwriting VTL resolver

### ISSUE THREAD

**Issue by danrivett** [aws-amplify/amplify-cli#6265]
**Is your feature request related to a problem? Please describe.**
I have created a custom resolver to overwrite a VTL request template for a mutation, in order to autogenerate a nested type's (not top-level) `id` to ensure it includes the top-level id in order to be able to query for the top-level type given a nested-level id, and then the nested type can be filtered. See the example GraphQL schema below for more details:

```graphql
type Project @model {
  id: ID!
  ...
  jobs: [Job!]!
}

# This type is inlined inside the Project table
type Job {
  id: ID! # the field should be non-nullable in the schema, it's in the input type that it should be nullable
  ...
}
```

Overwriting the VTL resolver is fine, however now that I'm auto generating the nested type's `id`, I don't want the corresponding generated GraphQL Input type for the mutation to specify that the id is required to be passed by the client since it's being auto-generated in the VTL template.

However it is not possible to overwrite GraphQL `input` types like it is for the resolver.

**Describe the solution you'd like**
I would like the ability to be able to overwrite an automatically generated `input` GraphQL type so I can make a field optional instead of required.

**Describe alternatives you've considered**
For now I have kept it as required (I don't think I have a choice) and using the convention of the client passing in an empty string or `auto` value which will indicate that the VTL resolver should auto-generate one (as opposed to on updates when it should use the one passed in). From a client perspective this isn't ideal and is error-prone.

**Additional context**
Here is the auto-generated `input` type I want to be able to customize:

```graphql
input CreateProjectInput {
  id: ID # This is auto-generated already, and already is non-nullable, so don't be confused by this, I'm not referring to this input field
  ...
  jobs: [JobInput!]
}

input JobInput {
  id: ID! # It this input field I want to change to be nullable
  ...
}
```

In the sample GraphQL schema above, the `Job.id` field is being auto-generated in a custom VTL resolver in the format `projectId#uniqueJobSuffix` so that when given just a job id, the id can be split on the `#` and the parent project can be looked up, and then the whole job id is used to filter the project's `jobs` array.

**Comment by MontoyaAndres** [comment]
Same, I'd like to do the same as @danrivett explains

**Comment by SwaySway** [comment]
Hello @danrivett 
If you have a custom resolver which is auto populating the field you can also override the nested input type as well. This would make the id optional on Mutation Operations.

```gql
# override input
input JobInput {
  id: ID
  name: String
}

type Project @model {
  id: ID!
  jobs: [Job!]!
}

type Job {
  id: ID!
  name: String
}
```

**Comment by danrivett** [comment]
@SwaySway thanks for the response. I apologise that my example was over simplified and while your suggestion may work in this simple case above, I previously tried your suggestion with a more nested structure and it doens't work; I'll explain below.

Here is the example above but expanded slightly to show the problem:

```graphql
input CreateProjectInput {
  id: ID input field
  ...
  jobs: [JobInput!]
}

input JobInput {
  id: ID! # It this input field I want to change to be nullable
  nestedStructure: NestedStructureInput!
  ...
}

input NestedStructureInput {
  foo: String!
}
```

In the above example if you attempt to override `JobInput` and define your own like before to make `id` optional, it errors because it says it cannot find `NestedStructureInput` since `NestedStructureInput` is auto-generated and not part of the `schema.graphql` being edited.

So you would end up having to define all the inputs that it references in order to override just the single one - `JobInput`.

This may sound fine, but we use a fairly nested structure as we try and inline as much as possible rather than generate lots of separate tables because of the AppSync subscription limit of 100 means we can get close to that by not inlining types. It's also more efficient for us to inline types where possible.

What I'm hoping based on what you recommended, is that the generator may be able to be smarter so that it generates all the input types other than the ones specified and then attempts to 'compile'/parse it rather than doing that early and complaining it cannot find other input types as they haven't yet been generated.

I hope that makes sense, let me know if not.

**Comment by SwaySway** [comment]
@danrivett Ah yup this makes sense. I can see your use case here. There is another issue where this has been mentioned. We are currently working on redesigning the transformer this is something we can keep in mind. 

RFC: https://github.com/aws-amplify/amplify-cli/issues/6217

As another workaround you could also make the job field nullable and add the validation in a custom resolver. In this scenario you can also control when the field should be nonnnullable.

**Comment by SwaySway** [comment]
Closing this issue in favor of the RFC: #6217.
