### ISSUE TITLE
Template error: resource BookingTable does not support attribute type StreamArn in Fn::GetAtt

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-cli#6266]
**Describe the bug**
When running amplify push api I get this error which is utterly un useful. On production version, i always get this error but will then run again and it always works, but on our dev version it fails with this every-time.

**Amplify CLI Version**
4.40.1

**To Reproduce**
Run - amplify push ap

**Expected behavior**
It should update the amplify API

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Node Version: v14.0.0

My Model:
```gql
type BookingTable @model(subscriptions: null)
    @key(name: "entityBookingTables", fields: ["entityId"])
    @key(name: "entityBookingTablesByMaxPeople", fields: ["entityId", "maxPeople"], queryField: "listEntityBookingTablesByMaxPeople")
    @key(name: "entityBookingTablesByCapacity", fields: ["entityId", "minPeople"], queryField: "listEntityBookingTablesByCapacity")
    @auth(rules: [
    { allow: owner },
    { allow: groups, groups: ["admin"] },
    { allow: groups, groups: ["users"] },
    { allow: public, provider: iam, operations: [read] }
]) {
    id: ID!
    tableNumber: Int
    capacity: Int
    area: String
    entityId: ID!
    ttl: Float
    maxPeople: Int
    minPeople: Int
    bookings: [Booking] @connection(keyName: "bookingTableKey", fields: ["id"])
    availability: [TableAvailability]
    createdAt: Float
    updatedAt: Float
}

```

**Comment by josefaidt** [comment]
Hey @oliverandersencox :wave: thanks for raising this! For more context, what is the error you are experiencing?

**Comment by josefaidt** [comment]
Hey @oliverandersencox I'm unable to recreate this issue with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v4.51.3). Was this issue appearing before the auth resource was fully created and pushed? If possible, are you still experiencing this issue, and may you try with the latest version of the CLI?

**Comment by akshbhu** [comment]
Closing this , Is the issue still presists , Feel free to comment and we will reopen this again

**Comment by danfreid** [comment]
I had the same problem.  In my full schema, it had both type @model definitions for RateSheet and RateSheetTable.  When I changed the second table to RatesSheetTable2, it worked.  Maybe there is some code gen happening that creates RateSheetTable from the first RateSheet type?
