### ISSUE TITLE
Authorized error on a query with a parent list with a nested object which has @auth

### ISSUE THREAD

**Issue by benjamin79** [aws-amplify/amplify-cli#6267]
Not sure if it is a bug, but it feels like one. With the following code i get: Not Authorized to access ad on type Person

The query itself works, but with the above error. A person can have one ad and an ad can have multiple persons.

When i query the ads alone it works and i only get the back ads where the ads.editor array field contains the username. For Example ["myUsername","anotherOne"]

**Amplify CLI Version**
4.40.1
Node: v14.15.3

**To Reproduce**
```gql
type Person
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "customerID"
        identityClaim: "custom:customerID"
      }
    ]
  )
  @key(
    name: "byCustomerID"
    fields: ["customerID"]
    queryField: "personByCustomerID"
  ) 
  @model {
  id: ID!
customerID: ID!
  firstname: String
  lastname: String!
  ad: Ad @connection(fields: ["adID"])
  adID: ID!
}

type Ad
  @model
  @key(
    name: "byCustomerID"
    fields: ["customerID"]
    queryField: "adByCustomerID"
  )
  @auth(
    rules: [
       { allow: owner, ownerField: "editors" }
    ]
  ) {
  id: ID!
customerID: ID!
  name: String
  editors: [String]
}
```
Query:
```
API.graphql(
      graphqlOperation(queries.personList)
    );
```
**Expected behavior**
When i query the Person table, the persons where the username isn´t in the ads.editors array field are ignored.

**Comment by yuth** [comment]
@benjamin79 Could you share the query used here in both `Person` and `Ad`. You could try runing these queries in  appsync  console  and easily switch users.

One other thing I would be interested in knowing is is for the Person type that you get from the query, is the corresponding `Ad` in `Person.ad`, does it have the current users username as `editor`?

**Comment by benjamin79** [comment]
> @benjamin79 Could you share the query used here in both `Person` and `Ad`. You could try runing these queries in appsync console and easily switch users.
> 
> One other thing I would be interested in knowing is is for the Person type that you get from the query, is the corresponding `Ad` in `Person.ad`, does it have the current users username as `editor`?

@yuth 
thanks for helping

```
query PersonByCustomerId(
  $customerID: ID
  $sortDirection: ModelSortDirection
  $filter: ModelPersonFilterInput
  $limit: Int
  $nextToken: String
) {
  personByCustomerID(
    customerID: $customerID
    sortDirection: $sortDirection
    filter: $filter
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      firstname
      lastname
      customerID
      ad {
        id
        customerID
        editor
        name
        editors
        createdAt
        updatedAt
      }
      adID
      adIDName
      createdAt
      updatedAt
    }
    nextToken
  }
}
```

```
query MyQuery {
  adByCustomerID(customerID: "1") {
    nextToken
    items {
      id
      editor
      editors
      name
    }
  }
}
```
I get the same error in the appsync console with the first query

Regarding our last question:
No, not ever ad should be visible to all users. So no, the current user is not alway in the editors field.
For example:

I have 2 ads in the db:
One editors field  might look like:
```
  "id: 1",
  "editors": {
    "L": [
      {
        "S": "user1"
      },
      {
        "S": "user3"
      }
    ]
  },
```
Another ad editors field:

```
 "id: 2",
  "editors": {
    "L": [
      {
        "S": "user2"
      }
    ]
  },
```
So if user2 for example is the current logged in user id only like to get back persons where the editors field in the connected ad lists the user2 in the array. At the moment i get back all persons and also the above error.

So for example if there are 2 persons in the db table and person 1 has the ad Id 1 and the next one ad id 2. I would expect only to get back one person when the current user is user2.

**Comment by yuth** [comment]
@benjamin79 I see you have updated the schema to include `@auth` directive for `Person` type with `identityClaim` to be present in `custom:customerID`.  What error do you get when you run the first query? Do you manage to get any of the `Person` listed with that query.

Since you are using a custom identity claim, I am assuming you already have configured [Cognito Lambda trigger to update the JWT token](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) with `custom:customerID` field and you're using [Id JWT token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) instead of Access JWT Token as custom claims won't be present in Access Token

**Comment by benjamin79** [comment]
> @benjamin79 I see you have updated the schema to include `@auth` directive for `Person` type with `identityClaim` to be present in `custom:customerID`. What error do you get when you run the first query? Do you manage to get any of the `Person` listed with that query.
> 
> Since you are using a custom identity claim, I am assuming you already have configured [Cognito Lambda trigger to update the JWT token](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) with `custom:customerID` field and you're using [Id JWT token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) instead of Access JWT Token as custom claims won't be present in Access Token

@yuth 
It doesn´t matter if the claim is in it or not. The error is the same. I made sure by creating two new tables with a different name without the claim and did a new push.

**Comment by yuth** [comment]
I can't think of any reason for getting `Not Authorized to access ad on type Person`. I used the your schema except for the `identityClaim` and managed to get the results for `personByCustomerID`. Could you share the your complete schema and also share the default `auth` mode used for API. Also wondering if you have overridden any of the resolvers

**Comment by benjamin79** [comment]
@yuth To make sure nothing else got in the way i made a complete new project with amplify init. Mostly with default values. -> 

1. https://gist.github.com/benjamin79/178a6666e8c44d8ec21dc74e5ba0ba50

2. It then put in the following schema:
```
type Person
  @model
 {
  id: ID!
  firstname: String
  lastname: String
  ad: Ad @connection(fields: ["adID"])
  adID: ID!
  adIDName: String
}

type Ad
  @model
    @auth(
    rules: [
       { allow: owner, ownerField: "editors" }
    ]
  ) 
  {
  id: ID!
  editor: String
  name: String
  editors: [String]
}
```

3. In the tables i put:
Person:
```
{
  "id": {
    "S": "e623e897-f246-4b97-a37a-c20c468fb449"
  },
  "firstname": {
    "S": "John"
  },
  "__typename": {
    "S": "Person"
  },
  "lastname": {
    "S": "Doe"
  },
  "adID": {
    "S": "c0b29e30-93db-4fce-8bda-2a17f0a7f98c"
  }
}
```
```
{
  "id": {
    "S": "b829d7c9-9159-4d73-ac21-960090f42c6e"
  },
  "firstname": {
    "S": "foo"
  },
  "__typename": {
    "S": "Person"
  },
  "lastname": {
    "S": "faa"
  },
  "adID": {
    "S": "9644a286-a5db-4932-af63-aba4f1373629"
  }
}
```
 Ad:
```
 {
  "id": {
    "S": "c0b29e30-93db-4fce-8bda-2a17f0a7f98c"
  },
  "__typename": {
    "S": "Ad"
  },
  "editors": {
    "L": [
      {
        "S": "travis"
      },
      {
        "S": "gravis"
      }
    ]
  },
  "editor": {
    "S": "travis"
  },
  "name": {
    "S": "MyAd1.pdf"
  }
}
```

```
{
  "id": {
    "S": "9644a286-a5db-4932-af63-aba4f1373629"
  },
  "__typename": {
    "S": "Ad"
  },
  "editors": {
    "L": [
      {
        "S": "fravis"
      }
    ]
  },
  "editor": {
    "S": "fravis"
  },
  "name": {
    "S": "MyAd2.pdf"
  }
}
```

4. Created user fravis in cognito user pools and added custom attribute **customerID**  (not necessary). Set password.

5.  Authenticated in the appsnc console and run following query:

```
query MyQuery {
  listPersons {
    items {
      adID
      firstname
      lastname
      adIDName
      ad {
        name
      }
    }
  }
}
```

Got following result with same error:

```
{
  "data": {
    "listPersons": {
      "items": [
        {
          "adID": "c0b29e30-93db-4fce-8bda-2a17f0a7f98c",
          "firstname": "John",
          "lastname": "Doe",
          "adIDName": null,
          "ad": null
        },
        {
          "adID": "9644a286-a5db-4932-af63-aba4f1373629",
          "firstname": "foo",
          "lastname": "faa",
          "adIDName": null,
          "ad": {
            "name": "MyAd2.pdf"
          }
        }
      ]
    }
  },
  "errors": [
    {
      "path": [
        "listPersons",
        "items",
        0,
        "ad"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 8,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access ad on type Person"
    }
  ]
}
```

Expected result should be:
```
...
 "items": [
        {
          "adID": "9644a286-a5db-4932-af63-aba4f1373629",
          "firstname": "foo",
          "lastname": "faa",
          "adIDName": null,
          "ad": {
            "name": "MyAd2.pdf"
          }
        }
      ]
...
```
Cause user fravis is only listed in the ad MyAd2.pdf in he editors array list.

When i query only the ads:

```
query MyQuery {
  listAds {
    items {
      editor
      editors
      id
      name
    }
  }
}
```
I correctly returns only the one ad where the current user fravis is listed.

Hope this helps. 
thanks

**Comment by SwaySway** [comment]
@benjamin79 Following up on this, are you still running into this issue?

I based on the last schema you provided I was able to create an ad and then create a person with said ad. I also had no issues getting access to `listPersons`. 

Could you provide the auth mode which you have setup for your project? I tried it with the following authConfig
You can find this config in `amplify/backend/backend-config.json`

```json
"api": {
    "fern": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authfernaXXXXXX"
            }
          },
          "additionalAuthenticationProviders": []
        }
      }
    }
  }
```

**Comment by benjamin79** [comment]
@SwaySway thanks for looking into it. Yes same error. The authConfig is the same. 

You need to put in a second item in the Ad table where the current user is not listet. So when the current user is: fravis and you list only travis and gravis in the editors field the error will come up. If you change for example travis to fravis the error is gone.

```
 {
  "id": {
    "S": "c0b29e30-93db-4fce-8bda-2a17f0a7f98c"
  },
  "__typename": {
    "S": "Ad"
  },
  "editors": {
    "L": [
      {
        "S": "travis"
      },
      {
        "S": "gravis"
      }
    ]
  },
  "editor": {
    "S": "travis"
  },
  "name": {
    "S": "MyAd1.pdf"
  }
}
```

**Comment by SwaySway** [comment]
@benjamin79 
Yea the flow here is an entity such as `fravis` is logged on and they can create a person with a linked ad as there are no auth rules on person. Same thing would apply if running a query such as `listPersons`. Though since there are auth rules added on Ad a person such as fravis should not be able to read ads where they are not the editor or in editors. If you are looking at only protecting create/update/delete and not read you can specify that in the auth rule for Ad this way anyone can read Ads. Where fravis would be able to read records. Read more on auth rules here: https://docs.amplify.aws/cli/graphql-transformer/auth

**Comment by benjamin79** [comment]
@SwaySway 
I´m not sure how this can be done.
I´ve added public / private  to the ad type. But this doesn´t solve it. Now i still get back 2 persons. Just without the error message. But it should return only 1 Person. Cause the fravis is not listed in the editors array of "MyAd1.pdf" 

How do i do that?

```
type Ad
  @model
    @auth(
    rules: [
       { allow: owner, ownerField: "editors" },
       { allow: public, operations: [read] }
    ]
  ) 
  {
  id: ID!
  editor: String
  name: String
  editors: [String]
}

```

**Comment by SwaySway** [comment]
It sounds like you are looking for authorization logic on the person type perhaps you can keep it consistent by adding owner auth on the person model type as well?

**Comment by benjamin79** [comment]
@SwaySway 
No, that is not possible cause of the dynamic nature. For example if i have 10.000 persons which have the assigend the same ad. Now if the ad gets added or removed a user, i would have to update 10.000 persons. That seems like a costly operation if it happens multiple times. 

Any idea how to solve this?

**Comment by SwaySway** [comment]
@benjamin79 

One thing you can do is create an auth rule to limit access to how many persons a user can see. The second thing could be to create an auth rule that only allows users to read into Ad. This way any person can read the ad that is assigned to them. Additionally if that user runs listPersons. They should only see records related to them via some auth rule.

This is more a discussion based question. For this I recommend our discord server: https://discord.com/invite/jWVbPfC
Here you can speak with other members on how to potentially address this further. 

Closing this issue as there are no actionable items to take in the CLI.

**Comment by benjamin79** [comment]
@SwaySway Please allow me once more:

Something like this:
```
type User @model {
  id: ID!
  something: 
    @connection(name: "UserSomethings")
    @auth(rules: [{ allow: owner, ownerField: "usernames" }])
}

type Something @model(queries: null) {usernames: [String] }
```

Is not possible? So i can´t do auth on a field in a connection?
