### ISSUE TITLE
error on amplify push: malformed policy, related to graphql schema

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#6270]
**Describe the bug**
I am seeing a cloudformation error when deploying with `amplify push`.
> Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 49ea155d-a1f8-4d43-82e0-20ff2d109e17; Proxy: null)

The resource this error is related to is nowhere to be found when globally searching my VS Code project.

I had a successful deploy very recently, but some things changed:
1. I added a new query field in my graphql schema
2. I added some code in my existing lambda function to handle the new query field
3. I updated the amplify cli.

Interestingly enough, **when I remove my changes to the graphql schema file** but keep my changes elsewhere, `amplify push` succeeds to deploy, but I'm lacking the new feature I need.

**Amplify CLI Version**
4.40.1

**To Reproduce**
1. Have an existing project deployed.
2. Update the amplify cli.
3. Update a graphql schema & lambda.
4. run `amplify push`

**Expected behavior**
Info about which policy is malformed. I don't believe I changed:
> [omitted]EnvLambdaDataSourceRole

**Desktop (please complete the following information):**
 - OS: Ubuntu via WSL
 - Node Version. v12.18.0

**Comment by cyrfer** [comment]
I don't understand what changed, but the deploy WORKED TODAY. I simply I re-added the field and the return type in my schema file and ran `amplify push`, just like I did yesterday.

I highly doubt yesterday's error came from a typo. I tried to reproduce the error with a typo and I see a very different error upon deploy. The only other causes I can think of are:
1. The amplify cli might have dependencies that changed their behavior overnight. I'd like to know what these could be.
2. My computer behavior changed. I am suspicious of my machine because I never could find the role in the Cloudformation error message on my local computer.

**Comment by jhockett** [comment]
Hi @cyrfer, glad to hear you got it working.

>     1. The amplify cli might have dependencies that changed their behavior overnight. I'd like to know what these could be.

I'm not aware of any changes that could have caused this issue, but it's hard to rule out entirely.

Closing this issue. Let us know if you see this again and we can reopen.
