### ISSUE TITLE
Make 'amplify import auth' headless

### ISSUE THREAD

**Issue by hirenumradia** [aws-amplify/amplify-cli#6271]
**Is your feature request related to a problem? Please describe.**
I am using AWS CDK to deploy a new Amplify app and Cognito Resources. I am exporting the required Cognito outputs from AWS CDK and have initialised a new amplify backend environment using a headless amplify init script.

This environment has no resources. I want to use 'amplify import auth' to import the CDK provisioned Cognito auth into the amplify project.

**Describe the solution you'd like**
I would love "amplify import auth" to be able to be run in headless mode so that I can automate the import

**Describe alternatives you've considered**
I have to manually configure the auth for the amplify app in all environments. I'm worried about doing this manually in production.

**Comment by jhockett** [comment]
Hi @hirenumradia, can you please offer some insight into your use case?

**Comment by hirenumradia** [comment]
Hi @jhockett sure. So the use case is that I want to have a completely automated deployment of an amplify app and associated AWS resources. This allows me to make sure all of our environments are in separate AWS accounts and are nearly indentical in their config.

I have automated a fresh amplify app but am stuck with automating "amplify add auth". 

I need to ideally automate this to import the Cognito resource that I have created in CDK.

Right now I have to do the step manually the first time I build the amplify app. Then I have modified amplifyPush.sh to make it specifies the auth config on each push.

As I am maintaining a modified version of the amplifyPush.sh script, I have to update the script with any changes if that's are any. Which isn't ideal.

Hopefully that's enough info! If not, feel free to ask.

**Comment by ChrisSargent** [comment]
Is there any chance of this being implemented or perhaps more guidance how to achieve something like this in CI/CD.

Essentially, our Cognito setup is being handled by AWS CDK so we'd like to connect to that user pool in CI/CD.

**Comment by jhockett** [comment]
Hi @ChrisSargent, actually this now supported in the latest version of Amplify CLI. 

Headless support for `import auth` was added by this [PR](https://github.com/aws-amplify/amplify-cli/pull/7266), but looks like we're missing documentation on it.

**Comment by ChrisSargent** [comment]
Hi, yeah, I was literally just reading that PR :-) but then I also some other issues which suggested you can use `amplifyPush` with env vars instead.

I was trying to use the headless import in a node script like so:

```ts
const authConfig = {
  userPoolId: 'myUserPoolId',
  webClientId: 'myWebAppClientId',
  nativeClientId: 'myNativeAppClientId',
};

const authCmd = `amplify import auth`;
execSync(authCmd, {
    input: JSON.stringify(auth),
    stdio: 'inherit',
});
```

but I got an error that no stdin was provided (it could well be that my usage of `execSync` is incorrect).

**Comment by ChrisSargent** [comment]
Okay, I actually got this working with:

```ts
const authConfig = {
  version: 1,
  userPoolId: 'myUserPoolId',
  webClientId: 'myWebAppClientId',
  nativeClientId: 'myNativeAppClientId',
};

const authCmd = `amplify import auth`;
execSync(authCmd, {
    input: JSON.stringify(authConfig),
    stdio: ['pipe', 'inherit', 'inherit'],
});
```

**Comment by ykethan** [comment]
The `amplify import auth` example has been added to the docs. Closing the GitHub issue.
