### ISSUE TITLE
How to re-create the infrastructure from a DB change?

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-cli#6273]
**Which Category is your question related to?**
infrastructure

**Amplify CLI Version** 
4.39.0

**What AWS Services are you utilizing?**
Graphql, DynamoDB

**Provide additional details**
I'm currently creating the models for my DB, but I'm facing some issues when I modifying the tables since I created the tables and now I added some secondary indexes so Amplify CLI says "Local secondary indexes must be created when the table is created" so that now I need to clean up the infrastructure in AWS but I want to keep my local changes in order to re-create the infrastructure again with the new indexes.

Any suggestion or Idea? Thanks for advance

**Comment by edwardfoyle** [comment]
Do you have any production data in your tables at this point? If not, I'd recommend removing the @models from your schema, pushing and then adding them back with the new @key directives that you want. We also have a new "iterative updates" feature in 4.40 that should handle pipelining dynamodb changes that can't be done all at once which may help you in this case.

**Comment by djom202** [comment]
So far, I just to have some list like cities, countries, places to fill the dropdowns. I left the the schema in blank and I tried to push it but I got this error: ```
Syntax Error: Unexpected <EOF>
An error occurred during the push operation: Syntax Error: Unexpected <EOF>
```, so I rollback the changes, and this time I just remove the @model tag but also forces me to remove the @connection, @auth, @searchable tags.

**Comment by SwaySway** [comment]
Could you provide the schema which resulted in this error? As far as discussions related to changes on `@key` the directive currently only creates an LSI when referring the secondary index references a hash/sort key from the primary key.

Related PR: https://github.com/aws-amplify/amplify-cli/pull/5648
