### ISSUE TITLE
How to write a transformer?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6274]
I am looking for a tutorial that explain how can we start building a custom transformer for amplify graphql. Is there any document available that explain how can we generate it and how to integrate it to a test project?

I found the following link, but it is very incomprehensible.

https://docs.amplify.aws/cli/plugins/authoring#authoring-custom-graphql-transformers--directives

**Comment by edwardfoyle** [comment]
You can check out this project for an example of a custom transformer: https://github.com/hirochachacha/graphql-auto-transformer

Also can you open an issue (or even better a PR!) in the docs repo describing the pain points of the existing documentation?

**Comment by mjza** [comment]
@edwardfoyle OK. Thanks. I will write on docs repo.

**Comment by mjza** [comment]
One small question regarding custom transformer, how can I get the current user information in a custom transformer?

**Comment by mjza** [comment]
I checked [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-auth-transformer/src/ModelAuthTransformer.ts) and it seems I can use `$ctx.identity`. Am I write?

**Comment by edwardfoyle** [comment]
Yes, here are the AppSync docs describing what's in ctx.identity: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html
