### ISSUE TITLE
How to list items in GraphQL based on deep ancestor (e.g. parent of parent)?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6275]
Assume I have defined the following grandparent (i.e. Country), parent (i.e. State), child (i.e. City) models. 

```
type Country
@model 
{
  id: ID!
  name: String!
  states: [State] @connection(keyName: "byCountry", fields: ["id"])
}

type State
@model 
@key(name: "byCountry", fields: ["countryId", "name"], queryField: "listStatesByCountry")
{
  id: ID!
  name: String!
  countryId: ID!
  country: Country @connection(fields: ["countryId"])
  cities: [City] @connection(keyName: "byState", fields: ["id"])
}

type City
@model 
@key(name: "byState", fields: ["stateId", "name"], queryField: "listCitysByState")
{
  id: ID!
  name: String!
  stateId: ID!
  state: State @connection(fields: ["stateId"])
}
```

Based on above definition, I can list child elements based on their parents! For example, I have `listStatesByCountry` that makes it possible to list all states based on a passed country id. The same way we can list cities based on a selected state by using `listCitysByState` query. 

My question is: **How can I get list of cities of a selected country? While there is no direct relationship between `City` and `Country` models, as `State` model sits between them!**

I need to define something like following on `City` model, but I don't know how as `countryId` does not exist in the `City` model and it must be retrieved from `state` property!

```
@key(name: "byCountry", fields: ["countryId", "name"], queryField: "listCitysByCountry")
```

**Comment by edwardfoyle** [comment]
There are a few ways to handle this:

1. If you're okay making several calls from the client, you can call "listStatesByCountry" and then iterate through all the states returned and call "listCitysByState" for each one and concatenate all of the cities into one list to effectively get "all cities in the country"
2. Add the countryId to the City model and add an @key as you described above to the model as well. Depending on how often countryId changes (probably not often unless the city-state relationship is just for the sake of example) duplicating this id into every city may be acceptable.
3. Create a "listCitiesByCountry" query with a custom resolver that can perform the steps of option 1 on the server side. This will save round-trips between the client and server but will still require multiple trips to the database

The most "non-relational" approach would be option 2 as typically expensive writes and duplicating data is sacrificed to make reads efficient, but really it depends on your exact use case and how often data is going to be read vs updated.

**Comment by mjza** [comment]
1. I want exactly prevent several calls!
2. If I repeat the `countryId` in the `City` model also, how can I guaranty that the `countryId` in the linked `state` is similar to this new `countryId` property in the `City`. I mean is there any mechanism to check this automatically, and prevent wrong creation or wrong update? Maybe you refer me to use custom transformer, but I am looking for something in the definition of the models. 
3. It seems it is the easiest way in my use case.

**Comment by edwardfoyle** [comment]
For 2, there isn't any "automatic" mechanism for this. You would need to write a custom resolver for the create city operation that looks up the corresponding state and duplicates the countryId into the city record. If you have a use case where a state might move to a different country (seems unlikely) you would also need to have custom logic to handle updating the country id of all the cities in that state

**Comment by mjza** [comment]
I don't have a use case that state and city have different country! 
I meant I need a mechanism to control it and prevent pushing wrong information in the DB. In case user push wrong countryId for a City I would like to have an exception.

**Comment by edwardfoyle** [comment]
You'll need to write a custom lambda resolver to handle this: https://docs.amplify.aws/cli/graphql-transformer/function
The lambda resolver can look up the country id based on the state id when a city is created and add that into the city record.
