### ISSUE TITLE
How to implement i18n in GraphQL?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6276]
I want to have translation for one property in my model. For example if I have:

```
type Country
@model 
{
  id: ID!
  name: String!
}
```

I want to store name of countries in `name` property. But I want to store the name for different locales. for example I want to store `Germany` for `en` locale and `Deutschland` for `de` locale. And I want to get the suitable name for this specific country based on the current user locale. For example, when I list the countries and the user's language is German then I expect to see `Deutschland` for this specific entry. Is it supported by Amplify or is there any solution for it?

**Comment by edwardfoyle** [comment]
Without knowing the full context of your application, it's difficult to know what the best approach would be, but I think a schema like the following is heading in the right direction:

```graphql
type LocalizedCountry
@model
@key(name: "byLocale", fields: ["locale"], queryField: "listCountrysByLocale")
{
  id: ID!
  locale: String!
  localizedName: String!
}
```

if you don't want multiple "LocalizedCountry" entries for a single country, you'll need a connection to another table.

```graphql
type Country
@model
{
  id: ID!
  localizedNames: [LocalizedCountryName!]! @connection(keyName: "byCountry")
}

type LocalizedCountryName
@model
@key(name: "byCountry", fields: ["countryId"])
{
  id: ID!
  countryId: ID!
  locale: String!
  localizedCountryName: String!
}
```
And then you can filter the localizedCountryName on the client.

If you want to be able to get the locale-specific name of an arbitrary country with no additional client-side logic I think you will need to write a custom resolver for a "getCountryByLocale" query that takes in a country id and a locale and looks it up in a table like the "LocalizedCountryName" table above

**Comment by mjza** [comment]
The first approach `LocalizedCountry`, is not acceptable as we cannot later do filtering for a specific item, because one country has several ids. The second approach is a classical solution for i18n. However, there are some obstacles. 

1. When use case is showing list of items (in this sample, list of countries) in a drop down, such an approach is good. 
2. when user can create items in his or her locale, then we need 2 create requests. First we must create the localized name, and then use that id for creating the item for the first time. And in case we want to add a new locale for an existing item, it is clear that we have to create the localized name first and then update the `localizedNames ` array. 
Now the question is, when we want to create an item for the first time, can we create the `Country` with its first translation or a bunch of translations in once? 
Do I need necessarily create a custom transformer or resolver?
3. Normally in the classical REST APIs, we define a locale as the default locale. In case that on item does not have the translation for the requested locale, then the translation for the default locale would return back. 
On the other hand, always we have maximum one string not an array of translations. 
However, in this approach as far as I see, we must return back all the locales, and then front-end makes decision to use which one. Now assume we have 100 translations for an item. And we requested 20 items. A huge amount of data would be transferred to the front-end to just extracts one translation per item.

**Comment by edwardfoyle** [comment]
If you only want the server to return a country entity with the name based on the client's locale, I think you will need to go with the custom resolver approach. You can create queries such as "listLocalizedCountries" and "getLocalizedCountry" that can look up the country in the countries table and the localized name in the other table and merge it into one object before returning to the client. You can read about custom lambda resolvers here: https://docs.amplify.aws/guides/api-graphql/lambda-resolvers/q/platform/js
