### ISSUE TITLE
How can I add email link verification rather than pin, through the CLI?

### ISSUE THREAD

**Issue by kvoth3** [aws-amplify/amplify-cli#628]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Auth
** Provide additional details e.g. code snippets **
I did not see an option for this while going through the `amplify add auth` cli flow.

I was able to implement it through the web console, manually adding the user pool and identity pools, then choosing email link rather than having a pin verification. The problem is I eventually had to  edit `aws-exports.js` with my pool values and if I want other services in the future, this will get overwritten with an updated config.

Looking at the backend folder config, i didn't see any attributes to edit that would change from email pin to email link verification. How do I implement this in a way that persists?

**Comment by kaustavghosh06** [comment]
@kvoth3 Right now the Cognito Cloudformation doesn't support this, but we'll be engaging with the cognito team to add this as a part of their Cloudformation support.

**Comment by kaustavghosh06** [comment]
@kvoth3 The changes in your aws_exports.js  file won't overwrite if you're using the latest version of the CLI. We added this functionality a few months back.

Also, we added support for email-link verification in the CLI. Check it out here - https://aws.amazon.com/blogs/mobile/amplify-framework-adds-supports-for-aws-lambda-triggers-in-auth-and-storage-categories/
