### ISSUE TITLE
Adding a second bucket leads to `undefined` in the `backend-config`

### ISSUE THREAD

**Issue by BracketJohn** [aws-amplify/amplify-cli#6283]
**Describe the bug**

Adding S3 storage to a project that already has an bucket, adds an `undefined` bucket.

**Amplify CLI Version**
`4.40.1`

**To Reproduce**
Run `amplify add storage` twice, select S3 twice

**Expected behavior**
No further changes to the `backend-config.json`.

**Screenshots**

What happens is the following:
```
--- a/amplify/backend/backend-config.json
+++ b/amplify/backend/backend-config.json
@@ -11,6 +11,10 @@
     "somePriorBucket": {
       "service": "S3",
       "providerPlugin": "awscloudformation"
+    },
+    "undefined": {
+      "service": "S3",
+      "providerPlugin": "awscloudformation"
     }
   },
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.11.1

**Comment by jhockett** [comment]
Hi @BracketJohn, thanks for the bug report! I was able to reproduce on `4.40.1`.

To get unblocked, you can just run `amplify remove storage` => choose undefined

**Comment by BracketJohn** [comment]
Thanks for the help, and thanks for fixing it
