### ISSUE TITLE
[MOCK] createObject returns the object created, but sometimes nothing is saved in the database (random)

### ISSUE THREAD

**Issue by vincent38wargnier** [aws-amplify/amplify-cli#6287]
Hi, I had an issue using the mock. I was thinking the problem was coming from my code, but after some research I realized it came from the mock itself. What confirmed it to me was that the bug was happening even in the Amplify GraphiQL Explorer.

I had the 2 following queries :
```gql
query MyQuery {
  listProductOffers(filter: {deleted: {ne: true}}) {
    items {
      id
    }
  }
}

mutation MyMutation {
  createProductOffer(input: {productOfferShopId: "b26f77db-636e-4cf5-ba34-45f837f5cbf5"}) {
    id
  }
}
```
When i created my "productOffer", the mock was returning me the product created, meaning that everything worked, but then when i checked the content of the database with the query, i realized that there were nothing saved. Don't take attention to the filter I put to the query, by default when I create a productOffer, the deleted attribute equals null.

Here is the video of the bug :

https://user-images.githubusercontent.com/33725800/103386911-391a2f80-4b01-11eb-8b0e-2141d1895fbd.mp4

I tried the same code with the normal dynamoDB, after amplify push, everything is working perfectly. 

EDIT : I'm using amplify version 4.40.0 on Mac os

**Comment by jhockett** [comment]
Hi @vincent38wargnier, thanks for the report. Please fill out the issue template so we can better debug what's happening:

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system

**Comment by edwardfoyle** [comment]
Just to be 100% sure, does the issue still repro if you remove the filter on the query?

**Comment by vincent38wargnier** [comment]
Unfortunately I didn't try without the filter, and now I removed the mock directory to work on a clean one so I can't test it anymore.

**Comment by SwaySway** [comment]
Closing this issue as there is no further action. Should you run into this again please comment below.
