### ISSUE TITLE
In Auth cognito user pool, what is the difference between the app_client and app_clientWeb clients?

### ISSUE THREAD

**Issue by danludwig** [aws-amplify/amplify-cli#629]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito User Pool

** Provide additional details e.g. code snippets **
amplify add auth (or amplify update auth) deploys a user pool that by default has 2 app clients, one denoted as "_app_client" and the other as "_app_clientWeb". What is the difference between these, are both necessary, and if so why?

**Comment by kaustavghosh06** [comment]
@danludwig `app_client` is used if you want to re-use the amplify generated backend for a native mobile app. For javascript projects just the app_clientWeb is required.

**Comment by kaustavghosh06** [comment]
Closing this issue. Please feel free to reopen this issue if you still have further questions regarding this
