### ISSUE TITLE
Fresh clone of project followed by `amplify init && amplify status` marks existing Lambda Layers as `Create`

### ISSUE THREAD

**Issue by kevcam4891** [aws-amplify/amplify-cli#6290]
**Describe the bug**
When we `git clone` an existing amplify project, then run `amplify init` all of the normal functions get their cloud metadata attached including the very necessary `lastPushTimeStamp`, so the system knows not to create it. Example:

Normal Function after `amplify init` 👍
![image](https://user-images.githubusercontent.com/4650870/103410746-b746f800-4b3a-11eb-963a-2dd03576a83c.png)

For Layers 👎
![image](https://user-images.githubusercontent.com/4650870/103410772-d3e33000-4b3a-11eb-8556-b68363b6e0a1.png)

When running `amplify status` everything else comes back `No Change` with the exception of the layer:
![image](https://user-images.githubusercontent.com/4650870/103410813-0a20af80-4b3b-11eb-8f1f-f48acb694777.png)

**Amplify CLI Version**
4.40.1

**To Reproduce**

1. Ensure project has been pushed to amplify and pushed to Git.
2. Clone project into new folder, run all normal `yarn`, etc to rehydrate it.
3. `amplify init --amplify '{"envName":"develop","appId":"xxx","defaultEditor":"vscode"}' --providers '{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"xxx","AmplifyAppId":"xxx"}}' --codegen '{"generateCode":false,"generateDocs":false}'`
4. `amplify status` shows `Create` next to Lambda Layers.

In some instances, if it thinks the layer has changed you'll get an even more confusing `Create` row AND `Update` row??
![image](https://user-images.githubusercontent.com/4650870/103410892-7a2f3580-4b3b-11eb-9c79-ff621ffdf3e4.png)

**Expected behavior**
I expect to get `No Change` to all resources, since nothing has changed or is being created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 14.15.3

**Additional context**
I have a hard time believing Layer functionality in Amplify is ready for prime time. In this particular case, I've tracked some code down that seems to strip the metadata (including lastPushTimeStamp):

`./packages/amplify-category-function/src/index.ts`

![image](https://user-images.githubusercontent.com/4650870/103411035-02add600-4b3c-11eb-9d6b-0c1835f5e191.png)

Prior to this code running, the state of the amplifyMeta contains the timestamp, and following this, setMeta edits the file to remove the metadata.

Im not sure of the logic behind this, and the author of this code seemed to know what they're doing since there's commenting around this particular logic. Should it be stripped for some reason? I'm happy to work on this and submit a PR to restore the metadata back to the Layer in amplify-meta.json, but want to be sure I'm on the right track.

**Comment by SebSchwartz** [comment]
Same issue here too. It then fail the CI/CD thanks to wrongly versioned layer...

**Comment by jhockett** [comment]
Hi @kevcam4891, @chris7716, and @SebSchwartz.

We fixed this issue in version 5 of the CLI. Please update to the latest version to migrate your Lambda layers to be able to use the latest features and bug fixes.

For reference, here's the documentation on the Lambda layer migration: https://docs.amplify.aws/cli/migration/lambda-layers-update

Closing this issue. If you see this again, please comment below and we can reopen and investigate.
