### ISSUE TITLE
How to delete project from the cloud while keeping the local source files intact?

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#6295]
I would like to remove all the deployed infra from AWS cloud while preserving my source codes for my lambda and schema etc.
How can I do that?

Running `amplify delete` would destroy basically everything from the cloud and the local files.

**Which Category is your question related to?**
Cloudformation and environment

**Amplify CLI Version** 
4.40.1

**Comment by jhockett** [comment]
Hi @nubpro, you can delete the app from the Amplify console. That will only affect the cloud. 

Alternatively, you can backup the project files and then run `amplify delete`.

**Comment by lkolodziejek** [comment]
Hi John,

Can you please kindly elaborate how this can help? 

After both actions my local amplify stops working and I'm not able to re-create cloud environment.

In case of first solution, local amplify still believes 'No changes' to the environment and will not allow to push.

For the second, no S3 bucket in AWS and cannot recreate environment as well.

Option allowing to delete resources in Cloud only without need to recreate local configuration would be very useful.

Best Regards,
Lukasz

**Comment by nubpro** [comment]
> Hi @nubpro, you can delete the app from the Amplify console. That will only affect the cloud.
> 
> Alternatively, you can backup the project files and then run `amplify delete`.

A proper solution would be much appreciated.
I have the same dilemma as @lkolodziejek has described.

**Comment by jhockett** [comment]
I don't follow @nubpro @lkolodziejek. The original question was just about keeping src files intact and deleting the app in the cloud.

If you want your project to keep functioning, why are you deleting the project in the cloud? Please elaborate on your use cases.

**Comment by nubpro** [comment]
> I don't follow @nubpro @lkolodziejek. The original question was just about keeping src files intact and deleting the app in the cloud.
> 
> If you want your project to keep functioning, why are you deleting the project in the cloud? Please elaborate on your use cases.

For my usecase, I will like to shut off my project as it is using a ton of cloud resources, and charging me. That said, I anticipate I will put back the project back online in a couple of months. Or perhaps I can refer back the codes on my new project (without needing to manually back it up on  another folder).

**Comment by lkolodziejek** [comment]
I would like to share code with the client and let them recreate app from their own AWS account.

Besides, shouldn't Cloud resources be decoupled from Infrastructure as a Code? 

Removing CloudFormation stack from AWS doesn't purge it's definition,  removing Lambda from AWS doesn't purge GitHub code, I'm not sure why Amplify does so :)

**Comment by jhockett** [comment]
Thanks for the clarification @nubpro @lkolodziejek. I recommend leveraging git to help out with this:

Add the `team-provider-info.json` file to `.gitignore`
Add project to a git repository, make sure amplify folder and all source code is committed and pushed
Run `amplify delete` to remove the project locally and in the cloud (there's no going back)

When you want to init the project, use the `--app` flag as described in the docs: https://docs.amplify.aws/cli/usage/headless#--app

**Comment by lkolodziejek** [comment]
John,

Thank you for the tip.

I've tried this approach, unfortunately provided commend doesn't work for me.

Does it has to be public git repository, or can be private?

I'm able to pull my repository using git over ssh (git clone git@github.com:lkolodziejek/<project>.git), however unfortunately Amplify throws error:

amplify init --app git@github.com:lkolodziejek/<project>.git
Note: Amplify does not have knowledge of the url provided
Invalid remote github url

Yet, I was able to restore project from github via AWS Console and pull changes from there, so the methods works.

Best Regards,
Lukasz

**Comment by kaustavghosh06** [comment]
@lkolodziejek It doens't have to be a public repo. You can just leverage a pvt git repo - push the files as a storage mechanism to pull down the files when required. After you create a backup (a git provider in this case), you can run amplify delete. You do not need to store the `amplify/team-provider-info.json` in the git repo.
After project deletion, you can `git clone` in your workspace and just run `amplify init` on it.  Please let us know if run into issues with running `amplify init` on a cloned amplify workspace.
