### ISSUE TITLE
Amplify CLI not using the profile listed in the local-aws-info.json

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6297]
I have set up two different environments using two different profiles. Applies to 4.36.2. I cannot use 4.40.1 at this time because of a different bug about a missing Id token that is supposed to be related to the  Admin UI setting. 

```
{
    "dopry": {
        "configLevel": "project",
        "useProfile": true,
        "profileName": "default"
    },
    "dev": {
        "configLevel": "project",
        "useProfile": true,
        "profileName": "Dev.AWSAdministratorAccess"
    }
}
```

.aws/credentials
```
[default]
aws_access_key_id=xxxx
aws_secret_access_key=xxxx
```

.aws/config
```
[default]
region=us-east-1

[profile Dev.AWSAdministratorAccess]
sso_start_url = https://company.awsapps.com/start
sso_region = us-east-1
sso_account_name = Dev
sso_account_id = XXXXXXX
sso_role_name = AWSAdministratorAccess
region = us-east-1
credential_process = aws-sso-util credential-process --profile Dev.AWSAdministratorAccess
sso_auto_populated = true
```

Given I have my personal environment checked out 
   AND the AWS_PROFILE environment variable is unset
When I run `amplify env checkout dev`   
Then I see 

```
$ amplify env checkout dev
- Initializing your environment: devEnvironment 'dev' not found.
Try running "amplify env add" to add a new environment.
If this backend already exists, try restoring it's definition in your team-provider-info.json file.
```

Given I have my personal environment checked out 
   AND the AWS_PROFILE environment variable is set to Dev.AWSAdministratorAccess
When I run `amplify env checkout dev`   
Then I see 
```
$ amplify env checkout dev
✔ Initialized provider successfully.
Initialized your environment successfully.
```

This Demonstrates the Amplify CLI isn't using the profile listed in the local-aws-info.json. 

I would expect
1. Amplify to use the profile stored in local-aws-info.json
2. Better Error Messaging
   1. > Initializing your environment: devEnvironment 'dev' not found.
      1. It should be specific that the environment was not found in the cloud since it is in my local repo
      2. It should clarify the Account Id and Account Name in which the environment was not found for better troubleshooting in multiple account scenarios.
      3. It should clarify the appId and app Name in which the environment was not found for better troubleshooting in multiple app/account scenarios.
    2. > Try running "amplify env add" to add a new environment. 
        1. The environment is in my team-provider-info.json, it was just not found online.  Shouldn't this advise me to push my environment and maybe ask me to verify I'm working in the correct account?
    3. > If this backend already exists, try restoring it's definition in your team-provider-info.json file.  
          1. There should be instructions for restoring a definition. There currently isn't a clear cut process for getting the information to import an existing app/environment from the cloud to a local team-provider-info.json.  Online there is an instruction that says to amplify pull --appId, but this will always error our if the environment in team-provider-info.json doesn't match the appId.  I go caught by this when I was setting up our dev account for CI/CD. I created the 'app' and 'environment' online when setting up CI, then couldn't get it into a local environment. I want to be able to pull dev/uat/prod for debugging and production support. I'd assume a lot of people are going to set this up online since most of the documentation about build recommends using the console over writing an amplify.yml

**Comment by ammarkarachi** [comment]
@dopry What's the access you have provided to the dopry profile?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response. Please let us know if you're still stuck on this issue.
