### ISSUE TITLE
team-provider-info.json shouldn't be treated as a canonical source of environment information.

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6298]
It seems like the team-provider-info.json is the store for environment details. It would be nice if it only stored a  reference to an AWS account, appId, and environment id, the rest of the environment details such as AuthRoleName, UnauthRoleArn, AuthRoleArn, Region, DeploymentBucketName, UnauthRoleName, StackName, StackId, AmplifyAppId, etc were stored in the cloud. 

That way the cli could use the current credentials to list the environments in the cloud you could easily select the ones to keep in your team provider. the developer experiencer of amplify env add/remove/import could be modified to just work on cloud resources. team-provider-info.json could continue to support the user experience by aggregating the environments in multiple accounts to give developers a good experience when using multiple account setups.

**Comment by ykethan** [comment]
Hey @dopry, thank you for the feedback.Amplify team are looking into improving the developer experience. 
Closing the issue due to age.
