### ISSUE TITLE
CLI installer inappropriately updates my bash_profile

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-cli#6300]
I've run the `amplify` installer script a few times. Now, in my `~/.bash_profile` I see:
```console
jhwill@9801a7a9c383:~$ cat ~/.bash_profile 
. ~/.bashrc


# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"
```

It should either not update my dot files, or it should ensure only one entry is present.

**Comment by akshbhu** [comment]
Thanks for reporting this 👍

**Comment by renebrandel** [comment]
cc @edwardfoyle

**Comment by edwardfoyle** [comment]
@jamesonwilliams Once you have installed the packaged CLI once, you should use `amplify upgrade` to install newer versions. This command will not add duplicates to your bash_profile. However, we can add some logic to prevent the duplicates

**Comment by kaustavghosh06** [comment]
@jamesonwilliams The fix for this is merged now.
