### ISSUE TITLE
CLI does not provide a usable help dialog

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-cli#6303]
I'm trying to reference the documentation for how the `pull` subcommand works.

None of the following commands show help for the pull subcommand.

```
amplify pull --help
```
```
amplify pull -h
```
```
amplify pull help
```
```
amplify help pull
```

Some of these commands will ask me:
> ? Do you want to use an AWS profile? (Y/n)

I would not expect to need an AWS profile, to view the help text.

**Comment by akshbhu** [comment]
Thanks for reporting it 👍 . 
We are actively working to improve the help section for such commands.

**Comment by jamesonwilliams** [comment]
Oh man lol this one is great I forgot about it
