### ISSUE TITLE
Error when Amplify push

### ISSUE THREAD

**Issue by Celinala** [aws-amplify/amplify-cli#6305]
I keep running into this problem when trying to push to my AWS console. It only happens when I try to push for Lambda functions, been stuck on it even after running "pip3 install --user pipenv", really not sure what to do, any help would be appreciated.

Pasted from terminal after "amplify push":

```✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name            | Operation | Provider plugin   |
| -------- | ------------------------ | --------- | ----------------- |
| Function | ModifiedSchedulesAmplify | Create    | awscloudformation |
| Storage  | NimbusAmplify            | No Change | awscloudformation |
| Hosting  | amplifyhosting           | No Change | awscloudformation |
? Are you sure you want to continue? Yes
You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".
✖ An error occurred when pushing the resources to the cloud

Missing required dependencies to package ModifiedSchedulesAmplify
An error occurred during the push operation: Missing required dependencies to package ModifiedSchedulesAmplify

**Comment by akshbhu** [comment]
Hi @Celinala 

May I know which amplify version are you using? You try with our latest version (4.41.0).
Also which OS are you using for this?

**Comment by Celinala** [comment]
> Hi @Celinala
> 
> May I know which amplify version are you using? You try with our latest version (4.41.0).
> Also which OS are you using for this?

@akshbhu I currently have up-to-date 4.41.0 Amplify and my OS is macOs Catalina Version 10.15.7 and I still get error.

**Comment by ale753** [comment]
I have the same problem here. I'm trying to push a python function but I keep getting this error : 
Could not find "python3" or "python" executable in the PATH.
You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".

I'm running amplify 4.41.0 on Windows 10 Education 10.0.19042. I have both Python3 and pipenv installed. 

I read of some workarounds at https://github.com/aws-amplify/amplify-console/issues/595 , but they refer to the AWS console

**Comment by ale753** [comment]
I got this to work in some way. Probably not all the modifications are needed, but I will show you them all. OS Windows 10 Education.
I did the steps described here :  https://github.com/aws-amplify/amplify-cli/issues/6159
In particular : 
1 - Install pipenv using pip install --user pipenv.This does a user installation to prevent breaking any system-wide packages.
2 - Run python -m site --user-base to get your user base binary directory, append bin to the path and add this path to your $PATH variable. You can echo $PATH if its added or not.

Open the Environment Variables window. Open the "Path" variable and add these lines both in User variables and System variables (probably one of them is not needed) :

  ` "C:\Users\YOUR_USER_NAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\bin"`

`"C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python38\Scripts\"`

`"C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python38"`

Check your installation paths with : 
`where python`
`where python3`
`where pipenv`

And then restart Windows 10. I'm able now to push my python lambda to the backend without errors.

**Comment by akshbhu** [comment]
@Celinala 

Can you try these steps : https://github.com/aws-amplify/amplify-cli/issues/6159#issuecomment-745584938

Let me know if this works for you?

**Comment by Celinala** [comment]
@akshbhu 
These were my steps:
My commands were:

1. Install pipenv using pip install --user pipenv

2. python -m site --user-base 
3. echo $path
4. export PATH=$PATH:/Users/celinalazaro/Library/Pyth/on/2.7



Im not sure what to do after, particularly:

```
After this, open the Environment Variables window. Open the "Path" variable and add these lines both in User variables and System variables (probably one of them is not needed) :

"C:\Users\YOUR_USER_NAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\bin"

"C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python38\Scripts\"

"C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python38",
```


 because I thought I did that in step 4? Also. I am using mac OS cmd with Python version 2.7. I am not sure if I am suppose to use Python 3 for it to Amplify push successfully.

**Comment by ale753** [comment]
I'm not experienced with mac OS unfortunately, my solution works with Windows 10, but it's likely something similar in your case. 
Check if your folder /2.7 contains a folder named Scripts and then add it with export PATH. 

export PATH=$PATH:/Users/celinalazaro/Library/Pyth/on/2.7/Scripts 

Or something similar, the files could be different. Be sure to add the path that contains the python3.exe and pip exe

You should be able to check your path on linux/mac with : 

`which python`
`which python3`
`which pipenv`

**Comment by akshbhu** [comment]
@Celinala 

you need to use python3 for for a successful ```amplify push```. you can check the spec here: https://docs.amplify.aws/cli/function#supported-lambda-runtimes.

**Comment by Celinala** [comment]
@akshbhu 

I updated to Python 3 and updated the latest version of amplify. 
I also ran these commands:

Install pipenv using pip install --user pipenv

python -m site --user-base

and added the paths:

`which python
which python3
which pipenv
`
and added their paths to my .bash_profile,
which looks like this:
`
PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}:/usr/local/opt/python/libexec/bin/python:/Library/Frameworks/Python.framework/Versions/3.9/bin/python3:/Library/Frameworks/Python.framework/Versions/3.9/bin/pipenv"
export PATH`

I am still getting the current error:

`
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name            | Operation | Provider plugin   |
| -------- | ------------------------ | --------- | ----------------- |
| Function | ModifiedSchedulesAmplify | Create    | awscloudformation |
| Storage  | NimbusAmplify            | No Change | awscloudformation |
| Hosting  | amplifyhosting           | No Change | awscloudformation |
? Are you sure you want to continue? Yes
You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".
✖ An error occurred when pushing the resources to the cloud

Missing required dependencies to package ModifiedSchedulesAmplify
An error occurred during the push operation: Missing required dependencies to package ModifiedSchedulesAmplify
`

Is this due to python missing dependencies?

**Comment by Celinala** [comment]
Solved error by running vitual env (I wasn't aware we had to use one) :
`pipenv run amplify push`

then noticed my Python path was '/Users/celinala/.local/share/virtualenvs/ModifiedSchedulesAmplify-pC9yLFox/lib/python3.9/' so I renamed to python3.8.
