### ISSUE TITLE
Invalid S3 key when using pipelineFunction resolvers

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6306]
**Describe the bug**

I wrote a transformer to create a pipeline resolver via a GraphQL directive. I recently made a change to use the default amplify behaviour of storing pipeline function resolvers inside the `pipelineFunctions` directory, exactly like the `@function` directive does. This works fine when pushing from my dev machine with `amplify push`. However, the automatic deployment I have setup on Amplify Console fails to deploy with the following error:
`Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;...`

Since all my other resolvers work fine, and only the pipeline function resolvers inside of the `pipelineFunctions` directory seem to be causing issues, I'm assuming it has something to do with the location of the vtl files. However, since pushing manually works fine, I can't see any other explanation than it being something particular to Amplify Console's CI/CD.

Here is the code which is making the request mapping template for the pipeline function:
https://github.com/half2me/amplify-transformers/blob/bb064f26266dc397862c430373669111d015210b/src/DynamoDBTransformer.ts#L126
This is then automatically being moved into the `pipelineFunctions` directory by amplify.

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
This used to work when I had manually specified the template location in S3 instead of letting amplify automatically generate the template files from the inline templates, and I had them stored with the other resolver templates, inside the `resolver` directory.

** To Reproduce **
1) Use this example schema:
```graphql
type Foo @model(mutations: null, subscriptions: null, timestamps: null, queries: null) {
  id: ID!
  name: String!
}

type Query {
  getFoo(id: String!): Foo @pipeline @dynamodb(table: "Foo", name: "A") @dynamodb(table: "Foo", name: "B")
}
```
2) Install the pipeline transformer
```
npm install @halftome/amplify-transformers@2.0.5
```
3) Add the transformers to `amplify/backend/api/<YOUR_API>/transform.conf.json`
```json
"transformers": [
    "@halftome/amplify-transformers/dist/PipelineTransformer",
    "@halftome/amplify-transformers/dist/DynamoDBTransformer"
]
```

4) `amplify push` should work just fine
4) Amplify Console should fail to deploy

**Comment by kaustavghosh06** [comment]
@half2me Are you still stuck on this?
