### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by parikh20** [aws-amplify/amplify-cli#6307]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Setting up Amplify via amplify init

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.41.0

**What AWS Services are you utilizing?**
None atm

**Provide additional details e.g. code snippets**
Amplify init errors out with 'Missing credentials in config". I have my credentials in ~/.aws/credentials and I have my config in ~/.aws/config. I'm attempting to setup this for an existing repository that uses amplify.

**Comment by akshbhu** [comment]
Hi @parikh20 

Can you check the ```local-aws-info.json``` in the ```.config``` folder inside ampify folder if it contains your profile used when go went through amplify init flow?

Also are you using windows or Mac for your project?

**Comment by parikh20** [comment]
Theres no .config folder since amplify init errors out. I'm currently on Linux.

**Comment by akshbhu** [comment]
I guess you are using vscode. You can check in the ```.vscode``` folder , there must a file ```settings.json``` , you can uncomments/ remove the files mentioned in ```settings.json```. After this you can see the .config folder.

**Comment by parikh20** [comment]
This is my local-aws-info.json

`{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}`

**Comment by akshbhu** [comment]
@parikh20 

Apologies. I misread the above information in which you mentioned that you are doing ```ampify init``` on an existing amplify project.
If the project is already setup with amplify , you can try ```amplify pull``` to fetch the existing project from the cloud.

Let me know if I am missing something

**Comment by parikh20** [comment]
That worked thanks!
