### ISSUE TITLE
Lambda Resolver - Top Level Errors not being logged in amplify mock

### ISSUE THREAD

**Issue by bacon1097** [aws-amplify/amplify-cli#6311]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When requiring an invalid package, the function will simply timeout with no indication of what the error is.

**Amplify CLI Version**
4.41.0

**To Reproduce**
1. In your lambda resolver, provide an invalid `require` statement before the handler is defined.
2. Run `amplify mock`
3. Execute the graphql query/mutation that uses said lambda resolver

**Expected behavior**
Print the error in the console and fail. Not timeout.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v12.16.1

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.
