### ISSUE TITLE
CLI binary for macOS arm64

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-cli#6312]
**Describe the bug**
When running the following curl command to install amplify-cli on M1 macbook, I get this error.
```
chai@Vics-MacBook-Air ~ % curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

 Installing the AWS Amplify CLI...

\033[31m Sorry, there's no Amplify CLI binary installer available for arm64 architecture.

Error: Amplify CLI failed to install. Check your internet connection and try again.
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**Expected behavior**
It should just work!

**Screenshots**
![image](https://user-images.githubusercontent.com/762914/103649554-a3b3eb00-4f99-11eb-9277-9865e33483d2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu] Macbook (M1)
 - Node Version. You can use `node -v` to check the node version on your system

**Comment by edwardfoyle** [comment]
Hi @nubpro Unfortunately [pkg](https://github.com/vercel/pkg) (which we use for building the native binaries) does not support macos arm64 yet. I created [this issue](https://github.com/vercel/pkg/issues/1023) in that repo asking for the feature which you could 👍 .

In the meantime, you can install the CLI using npm. Or if you really don't want to use node/npm, you may be able to run the x86 binary on your M1 mac using Rosetta 2. You'll just need to bypass the install script architecture check. To do that, download the install script [here](https://aws-amplify.github.io/amplify-cli/install), remove the `# Detect architecture` if statement and then run the script

**Comment by nubpro** [comment]
> Hi @nubpro Unfortunately [pkg](https://github.com/vercel/pkg) (which we use for building the native binaries) does not support macos arm64 yet. I created [this issue](https://github.com/vercel/pkg/issues/1023) in that repo asking for the feature which you could 👍 .
> 
> In the meantime, you can install the CLI using npm. Or if you really don't want to use node/npm, you may be able to run the x86 binary on your M1 mac using Rosetta 2. You'll just need to bypass the install script architecture check. To do that, download the install script [here](https://aws-amplify.github.io/amplify-cli/install), remove the `# Detect architecture` if statement and then run the script

Yap, I managed to install amplify with npm.
Thanks!

**Comment by renebrandel** [comment]
Packaged version of Amplify CLI now supports M1 MacBooks.
