### ISSUE TITLE
DataStore: Throws "UpdateItem on versioned data source requires the _version to be provided." when sending a mutation

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6315]
**Describe the bug**

When trying to update an existing model via DataStore GraphQL throws the following error in the console and in the network tab:

"UpdateItem on versioned data source requires the _version to be provided."

Yet the code is good and the _version field is provided. Seems that this was caused by my resolver (added via Amplify not manually) for the update mutation wasn't DataStore aware (ie none of the required fields for DataStore where added to the resolver. 

This was discussed last weekend in the Discord channel chat here https://discordapp.com/channels/705853757799399426/735987596462653461/789553458625249280

**To Reproduce**

Not sure how it got into this state. Sometimes I kill the ```amplify push``` (using Ctrl-C but only before it starts actually uploading stuff, if its got that far I leave it run) command if I've forgotten something. Or sometimes my connection times out (its pretty flakey at the minute) after 2 minutes and then I'm not sure what state it has left everything in, could it be caused by that?

At the point of this being "broken" running ```amplify status``` would say everything is up to date and as it should be yet my resolver was not setup as it should be. I've never edited a resolver manually until I found the issue and tried to fix it (which seems to have worked).

See attached two files, one called Sector which works (as it has all the DataStore stuff in it) and then the broken Staff model which doesn't mention the DataStore fields (I've renamed them as .txt files as I can't upload .vtl files).

[staff-resolver.txt](https://github.com/aws-amplify/amplify-js/files/5735591/staff-resolver.txt)
[sector-resolver.txt](https://github.com/aws-amplify/amplify-js/files/5735592/sector-resolver.txt)

Winmerge screenshot showing some of the missing fields:

![image](https://user-images.githubusercontent.com/1674590/103003432-b570a980-4528-11eb-82cd-91d3188ac511.png)

Now annoyingly I had fixed this last week but its just reoccurred today which is puzzling me. Team mate says they haven't pushed. I'm going to re-do it and see if I made any mistakes and keep an eye on it.

**Expected behavior**

The resolver if DataStore is enabled so inject in all the right template code to wire up mutations via DataStore. Ideally it should be able to recover from an unknown state (cancelled push or timeout) if it doesn't already.

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:

```amplify update api```

* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://xxxxx.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxxxxxxxxxxxxxxxxxxxx",
    "aws_cloud_logic_custom": [
        {
            "name": "webFormHandlerAPi",
            "endpoint": "https://xxxxxxxxxxxxx.eu-west-1.amazonaws.com/live",
            "region": "eu-west-1"
        },
        {
            "name": "customerCsvExport",
            "endpoint": "https://xxxxxxxxxxxxxx.eu-west-1.amazonaws.com/live",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:xxxxxxxxxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1xxxxxxxxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxxxxxxxxx.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxxxxxxxxx-live",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};   
```

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by PeteDuncanson** [comment]
So yesterday I managed to do a push and get the resolvers up in the cloud again. Result! 

I cleared out all the resolvers I found in ``/amplify/backend/api/<MyApp>/resolvers`` as I don't think they are the "real" ones and talking to another dev we think that folder is used for over-writing generated resolvers should you need to (would love some confirmation on that).

Then I did a push and it worked and I had an afternoon of work that could be done. 

Logging in today I'm back to the same error, the resolvers have all reverted in the cloud somehow, no one else has done a push. What gives?

I've got a theory but not sure if its based on fact or anything.

It worked yesterday when we pushed it up and while I was using it. Then we slept and today its broken again. Could it be that over-night AWS cleared out the App due to lack of interaction, sort of put it to sleep, then when we hit it again in the morning it hydrates it from somewhere? Could it be that where it hydrates it from has the broken resolves in it? If so how to fix that or check it? Would it be a zip up in S3 somewhere I can check or delete?

A push today has fixed it again...but then I fear that tomorrow it will have reverted again. How best to just clear out this glitch?

**Comment by PeteDuncanson** [comment]
Think I've found the issue here. Our CI was redeploying from git but the fix of removing the custom resolvers mentioned above hadn't been pushed up to github yet. My team mate did a git push with other code in it that triggered the CI and over-wrote my fix that I'd manually deployed via ``amplify push`` yesterday. 

I've since pushed up my fixes to git and the CI has rebuilt again and the resolvers are now all working again. Result!

I'll await tomorrow to double check but if its all still working I'll close this one.

For those following along the cause was having copies of the resolvers in this folder ``/amplify/backend/api/<MyApp>/resolvers``` which were out of date and seem to over-write the generated resolvers from Amplify.

**Comment by akshbhu** [comment]
@PeteDuncanson Good to know that it is working today for you 👍 

> I cleared out all the resolvers I found in /amplify/backend/api/<MyApp>/resolvers as I don't think they are the "real" ones and talking to another dev we think that folder is used for over-writing generated resolvers should you need to (would love some confirmation on that).

Thats true , If you have any resolvers present in the ``` /amplify/backend/api/<MyApp>/resolvers``` , those resolvers wont be touched  and direclty copied to cloud as these resolvers contains manual changes and amplify doesnt overwrite on them.
This way customers can have custom resolvers or their own implemented resolvers. 

I guess this is the case  for you, it keeps on overiding for you as a stale resolver file might be present in ```/amplify/backend/api/<MyApp>/resolvers``` and keep getting pushed when you are doing ```amplify push```.

Let me know if this answer your question.

**Comment by PeteDuncanson** [comment]
@akshbhu I've been working on it all day today and pushing git and no problems to report. I think we have found our culprit!

Thanks for everyone's help on this on especially Chai from the Discord channel who really dug deep to help me out.

Consider this one closed.
