### ISSUE TITLE
Adding/Re-adding DataStore via the CLI doesn't re-generate the resolvers

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6323]
Some how my Mutation resolvers are only half setup to work with DataStore (over half of them don't mention ```_version```).

In an effort to fix this I disabled DataStore and re-enabled it in the hope they would regenerate but they are still broken.

**To Reproduce**

1. Somehow end up with resolvers that are not DataStore aware! Not sure how that happened to me but if you want to test it yourself you can see the changes needed in the files I uploaded to this related issue https://github.com/aws-amplify/amplify-js/issues/7438 if you've broken it correctly then trying to run a mutation on that resolver will throw the error mentioned in the above issue, well done, you have a DataStore unaware resolver...lets try to fix that.
2. Run ``amplify update api``
3. Select ``disable DataStore``
4. Push up to Amplify via ``amplify push``
5. Run ``amplify update api``
6. Select ``enable DataStore``
7. Push up to Amplify via ``amplify push``

This should have over-written the resolvers and made it all "work" as it should. However when you run your mutation from step 1 again you will see its still broken and throwing the same error.

**Expected behavior**

Seems that the old classic of "switch it off and switch it back on again" doesn't seem to work here for DataStore, it stays broken and I'm not sure why. I would expect it to regenerate all the resolvers and hopefully put right whatever got broken before thus clearing my issue.

Related issues:
https://github.com/aws-amplify/amplify-js/issues/7438
https://github.com/aws-amplify/amplify-cli/issues/6242

**Comment by edwardfoyle** [comment]
@PeteDuncanson Reading through the related issues you linked it looks like the root cause of this was the lack of documentation about how the resolvers overwrite the build/resolvers? Is there another issue here that you're still facing?

**Comment by PeteDuncanson** [comment]
For the record, yes this was an issue with my having copies of old resolvers in my resolvers folder that were causing me issues. No action required. Thanks :)
