### ISSUE TITLE
Add README to VTL resolvers directory

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6325]
This is hopefully a simple DX idea.

I didn't know you could over-write generated resolvers as described here: https://docs.amplify.aws/cli/graphql-transformer/resolvers

I thought the ``/amplify/backend/api/<MyApp>/resolvers`` folder was just where all resolvers lived. I didn't know that they actually all get generated into ``/amplify/backend/api/<MyApp>/build/resolvers`` and any that appear in ``/amplify/backend/api/<MyApp>/resolvers`` are over-rides or custom resolvers that will replace the generated one. 

This is actually really clever but the convention was hard for me to find, I had to have my build broken for 3 weeks to learn this bit (See https://github.com/aws-amplify/amplify-cli/issues/6315 to follow along at home).

Might I suggest that folders with this over-rides could be renamed as ``customResolvers`` rather than ``resolvers`` or something similar? I know that on the face of it this is a minor change but it will have knock on effects and it could be the genie is out of the bottle and its too late to change it. But that to me would have helped with my mental model of what that folder actually is for.

If we went a step forward could it be worth dropping a readme into these folders explaining what they are, when you might use them and links to the online docs? I only found this gem of a page today (https://docs.amplify.aws/cli/reference/files) and if nothing else it would be nice to add something in there about where to put custom code that over-rides the generated stuff.

**Comment by edwardfoyle** [comment]
@PeteDuncanson thanks for the suggestion. I fear that renaming that folder would be a big headache, but I think adding a readme to the folder describing the override process would be a good improvement.

**Comment by rajrajhans** [comment]
Hi @edwardfoyle, I'm trying to make a PR which closes this issue. Could you please clarify whether the generated README file should be added to .gitignore? 

Thanks.
