### ISSUE TITLE
Is it possible to have a one to many relationship on the same model in graphql

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-cli#6326]
**Which Category is your question related to?**
Graphql Api

**What AWS Services are you utilizing?**
Appsync 
Datastore

**Provide additional details e.g. code snippets**
I have a model Projects that can have multiple children projects of the same type which themselves could have multiple children projects.
Imagine a folder system. Currently we are achieving it with mongodb by having a `parentProjectId` field within each project document. So the root project has  an empty `parentProjectId` field and each subsequent child project has their parent's id. 

![image](https://user-images.githubusercontent.com/25743418/103821236-c88c8900-5093-11eb-9248-74b5469d2a46.png)

Is this something I can achieve with amplify?

**Comment by edwardfoyle** [comment]
@DevTGhosh Yes you can define a self-referential model. If projects only need a reference to their parent project you can accomplish that with a schema like:
```graphql
type Project @model {
  id: ID!
  parentID: ID!
  parent: Project @connection(fields: ["parentID"])
}
```
In general, graphql does not impose any limitations on recursive models. Depending on your access patterns you may need to add additional @key directives or custom resolvers but this use case can be achieved.

**Comment by DevTGhosh** [comment]
So if I want to list all the child projects of a parent project I would guess it looks like this ??
```js
type Projects
  @key(name: 'byParentProjectId', fields: ['parentProjectId])
  @model {
  id: ID!
  parentProjectId: ID!
  childProjects: [Projects] @connection(keyName: "byParentProjectId", fields: ["id"])
}
```
