### ISSUE TITLE
All lambda functions have IAM policy for logging

### ISSUE THREAD

**Issue by wderezin** [aws-amplify/amplify-cli#6328]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

When creating a Lambda function with only API access no IAM policy is attached.  This prevents the lambda from be able to log to cloudwatch.    For example, if you add AUTH access to a lambda it does create an IAM role with the `lambda-execution-policy` policy attached

**Describe the solution you'd like**

For any function added with `amplify add function` create an IAM role with the `lambda-execution-policy` attached as the following:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:us-east-1:667713841636:log-group:/aws/lambda/LAMBDA_NAME-ENVIRONMENT:log-stream:*",
            "Effect": "Allow"
        }
    ]
}
```

**Describe alternatives you've considered**

When adding a lambda I always add AUTH read access.

**Additional context**

**Comment by ykethan** [comment]
Hey @wderezin, wanted to follow up on this issue. Are you still experiencing the behaviour?

**Comment by josefaidt** [comment]
Closing as this issue has since been resolved. After adding a Lambda function with access to an API we see there is a Lambda execution IAM policy in the function's CloudFormation template.

```json
"lambdaexecutionpolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": {
                "Fn::Sub": [
                  "arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
                  {
                    "region": {
                      "Ref": "AWS::Region"
                    },
                    "account": {
                      "Ref": "AWS::AccountId"
                    },
                    "lambda": {
                      "Ref": "LambdaFunction"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    },
```
