### ISSUE TITLE
graphql client api mutations[codegen] help...

### ISSUE THREAD

**Issue by sgoveia** [aws-amplify/amplify-cli#633]
**Which Category is your question related to?** 
API Graphql
 **What AWS Services are you utilizing?** 
Auth, API, Storage
 **Provide additional details e.g. code snippets** 

Hello @mikeparisstuff and @kaustavghosh06 I am loving Amplify CLI but I am wondering what I am doing wrong with respect to calling the codegen created mutations, the queries seem to work ok. Below are details:
#### I have created a Vue.js project please see package.json below:
<img width="324" alt="screen shot 2018-12-27 at 11 00 57 am" src="https://user-images.githubusercontent.com/3951459/50491124-bd032380-09de-11e9-92b6-5e2ee0ef11b3.png">

#### Here is my schema:
<img width="519" alt="screen shot 2018-12-27 at 10 55 33 am" src="https://user-images.githubusercontent.com/3951459/50491307-a9a48800-09df-11e9-86b9-9e05c352b9f8.png">

#### Here is the "codgen" generated mutation:
<img width="720" alt="screen shot 2018-12-27 at 10 55 53 am" src="https://user-images.githubusercontent.com/3951459/50491329-bfb24880-09df-11e9-9fc2-e819f34e1810.png">

#### Here is the import:
<img width="502" alt="screen shot 2018-12-27 at 10 57 19 am" src="https://user-images.githubusercontent.com/3951459/50491342-d2c51880-09df-11e9-8614-a3bd4cc9669e.png">

#### Here is the call within the Vue.js "method" section:
<img width="626" alt="screen shot 2018-12-27 at 2 18 58 pm" src="https://user-images.githubusercontent.com/3951459/50491858-77e0f080-09e2-11e9-9494-b193fa084370.png">

#### Here is the error I continue to get.. :
<img width="1010" alt="screen shot 2018-12-27 at 2 02 35 pm" src="https://user-images.githubusercontent.com/3951459/50491396-1cadfe80-09e0-11e9-9f3f-1e4f91346483.png">

Please help... I have tried many variations but can't see why it is failing.. I basically just tried to follow the examples from [here](https://aws-amplify.github.io/docs/js/api#amplify-graphql-client) 

Any suggestions or help would be very appreciated.. Thanks in advance for your time..

**Comment by jkeys-ecg-nmsu** [comment]
Have you tried `await uuidv4()`?

**Comment by sgoveia** [comment]
@jkeys-ecg-nmsu  Thanks I just did try ` await uuidv4()` and still no go.. same error. I have even tried hard coding a string i.e. `{input: {recording_id:"this-is-a-uuid"}}` and still getting "Variable input has coerced Null..."
Thanks for the idea though.

**Comment by tobiv** [comment]
I had to set `owner` as nullable, otherwise the API expects it in the input. It should be set automatically either way.

**Comment by elorzafe** [comment]
@sgoveia I had another approach, I updated my schema on AppSync console, and removed the required (!) for owner attribute like this
```graphql
input CreateRecordingsInput {
	id: ID
	recording_id: String!
	owner: String
}
```

and saved the schema and tried with this code
```javascript
async callApi() {
    const new_recording = {
      recording_id: uuid(),
    }
    const response = await API.graphql(graphqlOperation(mutations.createRecordings, { input: new_recording }));
    console.log({response});
  }
```

**Comment by sgoveia** [comment]
Ah.. @elorzafe  yes thank you! looks and works great!

@UnleashedMind , @kaustavghosh06 this issue can be closed! Thanks to all who have helped..!!
