### ISSUE TITLE
Unable to locate custom transformer during gql compile

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6330]
I have read this article https://docs.amplify.aws/cli/plugins/authoring#authoring-custom-graphql-transformers--directives
but no mention on how to use a custom transformer.

I have tried [graphql-default-value-transformer](https://github.com/trek10inc/graphql-default-value-transformer), with the following setting in my `amplify/backend/api/xx/transform.conf.json`

```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "transformers": [
        "graphql-default-value-transformer"
    ]
}
```

But I got this error when I run `amplify push`

```
Cannot find module 'xxxxx/~/.npm-global/lib/node_modules/graphql-default-value-transformer'
```

(I have installed the package both locally and globally.)

## How to fix the issue
I found this is an issue of the upstream lib `global-dirs`.
So I created an issue at here.
https://github.com/sindresorhus/global-dirs/issues/21
Amplify team should upgrade the `global-dirs` once the issue has been fixed.

**Comment by edwardfoyle** [comment]
@yaquawa did you change the npm global path between when you installed the CLI and when you installed this transformer? Can you check if the package is actually installed at the path that the CLI is looking for it?

**Comment by yaquawa** [comment]
@edwardfoyle here is the global path of mine. 
```
npm config get prefix
/Users/username/.npm-global
```

I could find graphql-default-value-transformer in `/Users/wang/.npm-global/lib/node_modules/graphql-default-value-transformer/`.

**Comment by yaquawa** [comment]
@edwardfoyle 

Here is the full error message:

```
Unable to import custom transformer module(graphql-default-value-transformer).
You may fix this error by editing transformers at /Users/xxx/Documents/htdocs/myproject/amplify/backend/api/testprojectapi/transform.conf.json
✖ An error occurred when pushing the resources to the cloud

Cannot find module '/Users/xxx/Documents/htdocs/myproject/~/.npm-global/lib/node_modules/graphql-default-value-transformer'
Require stack:
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/lib/commands/push.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
An error occurred during the push operation: Cannot find module '/Users/xxx/Documents/htdocs/myproject/~/.npm-global/lib/node_modules/graphql-default-value-transformer'
Require stack:
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/import-global/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/lib/commands/push.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/lib/index.js
- /Users/xxx/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
```

**Comment by edwardfoyle** [comment]
@yaquawa I was able to successfully compile a schema using that transformer plugin and the latest version of the CLI.

Are you using a local installation of the CLI? The CLI only supports global installation

**Comment by yaquawa** [comment]
@edwardfoyle can you tell me what's your `npm config get prefix` ?
I was not able to compile it in both local and global installation.

> I could find graphql-default-value-transformer in /Users/username/.npm-global/lib/node_modules/graphql-default-value-transformer/.

**Comment by edwardfoyle** [comment]
my `npm config get prefix` is `/usr/local`. What does `which amplify` return for you? It should be equivalent to `$(npm config get prefix)/bin/amplify`

**Comment by yaquawa** [comment]
@edwardfoyle here is mine, looks fine?

```
npm config get prefix
/Users/xx/.npm-global

which amplify
/Users/xx/.npm-global/bin/amplify
```

**Comment by yaquawa** [comment]
@edwardfoyle can you tell me your amplify's version?

**Comment by yaquawa** [comment]
@edwardfoyle I found this is an issue of the upstream lib global-dirs.
So I created an issue at here.
sindresorhus/global-dirs#21
Amplify team should upgrade the global-dirs if the issue fixed.

**Comment by edwardfoyle** [comment]
Thanks for digging into that! Marking this as a dependency issue
