### ISSUE TITLE
How to provide private iam permissions to query created with `@key` directive

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-cli#6332]
I am trying to query a @key custom query from a lambda, however, the `{ allow: private, provider: iam }` are not applied to the query  and I am not able to call the @key query
(FYI I have added API permissions to the Lamba via the CLI)
```graphql
type Metric
  @model
  @key(
    name: "byType"
    fields: ["type"]
    queryField: "metricByType"
  )
 @auth(
   rules: [
     { allow: public, operations: [create] }
     { allow: private, provider: iam, operations: [read] }
   ]
 )
 @auth(rules: [{ allow: public, operations: [create] }, { allow: private, provider: iam }]) {
  id: ID!
  type: String!
  source: String
  createdAt: AWSDateTime!
  expirationUnixTime: AWSTimestamp! @ttl
}
```

How can I apply the authorization rules to the custom query (@key)?

**Comment by waltermvp** [comment]
https://github.com/aws-amplify/amplify-cli/issues/4995

**Comment by edwardfoyle** [comment]
Hi @waltermvp the process for this is admittedly a bit clunky but it's documented here: https://docs.amplify.aws/cli/function#signing-a-request-from-lambda

**Comment by waltermvp** [comment]
Thank you for the link, I had followed all the steps. 

Changing the order of the with rules resolved this issue for me.
