### ISSUE TITLE
Could not initialize 'staging': socket hang up

### ISSUE THREAD

**Issue by patstahl** [aws-amplify/amplify-cli#6334]
`amplify pull --appId [REDACTED] --envName staging` fails with error: 

> Could not initialize 'staging': socket hang up

Just updated the data model with the Admin UI and intended to pull the changes.

**Comment by renebrandel** [comment]
Transferring this to the Amplify CLI repo. cc @jhockett @kaustavghosh06

**Comment by jhockett** [comment]
Hi @patstahl, we don't create any socket connections when running `amplify pull` as far as I know. Could you please fill out the following information?

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 - Node Version. You can use `node -v` to check the node version on your system
 - Default browser

**Comment by edwardfoyle** [comment]
@patstahl Also, if you are on Windows, are you using WSL?

**Comment by patstahl** [comment]
Amplify CLI Version
4.41.0

Desktop (please complete the following information):
OS: MacOS 11.1
Node Version: v12.18.3
Default browser: Chrome

Cloned a new env (dev) and pulled this successfully. However, still not able to pull the 'staging' env.

**Comment by edwardfoyle** [comment]
@patstahl After running the failed pull command, can you post the last few lines from `~/.amplify/logs/<latest file>` here?
Also could you include any error messages in the browser console log when trying to authenticate?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
