### ISSUE TITLE
Inserting new users in the User table 

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6335]
I have followed [this tutorial](https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js) for inserting new created user in a USER table. 

But unfortunately it does not inject any row in my table.

**Comment by edwardfoyle** [comment]
@mjza Can you provide more details on what is not working? Is the lambda trigger invoked? Did it throw an error?

In the future, please fill out [one of our issue templates](https://github.com/aws-amplify/amplify-cli/issues/new/choose) when creating an issue.

**Comment by mjza** [comment]
@edwardfoyle The reason that I didn't shared any code was that, the code is exactly same as the documents. 

Yes, I checked the console output and here is the error output:

> 2021-01-08T08:47:30.869Z	3fdca048-883f-4542-8c58-bd7d1b92424c	INFO	Error ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
>     at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
>     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
>     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
>     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
>     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
>   code: 'ValidationException',
>   time: 2021-01-08T08:47:30.772Z,
>   requestId: '8KG68SPNVE922311NSSR404N63VV4KQNSO5AEMVJF66Q9ASUAAJG',
>   statusCode: 400,
>   retryable: false,
>   retryDelay: 39.05797380224338
> }

It seems the line 27 in the code made that error output.

**Comment by mjza** [comment]
I also made an output for the item that I try to write, and here is the result:

```json
2021-01-08T10:04:37.055Z	57075ee8-f855-4a18-82b8-2c499dbf53e0	INFO	{
  Item: {
    id: { S: '40748424-ee75-4380-9114-6e5ff830fb8e' },
    __typename: { S: 'User' },
    name: { S: undefined },
    email: { S: 'x.y@cimt-ag.de' },
    createdAt: { S: '2021-01-08T10:04:37.024Z' },
    updatedAt: { S: '2021-01-08T10:04:37.024Z' }
  },
  TableName: 'User-xyz-staging'
}
```

**Comment by mjza** [comment]
It seems name has problem!

**Comment by mjza** [comment]
I solved it like follow:

```
            var id = event.request.userAttributes.sub,
            name = event.request.userAttributes.name,
            email = event.request.userAttributes.email;

        let params = {
            Item: {
                'id': {S: id ? id : ""},
                '__typename': {S: 'User'},
                'name': {S: name ? name : ""},
                'email': {S: email ? email : ""},
                'createdAt': {S: date.toISOString()},
                'updatedAt': {S: date.toISOString()},
            },
            TableName: process.env.API_CIMPLYCITYWEBAPP_USERTABLE_NAME
        };
```
