### ISSUE TITLE
Where to check log of published app?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6336]
If I have a lambda function that I use in an amplify project. Assume I connected this function to one event, for example "Post confirmation" trigger. 

Now the question is if I have `console.log` function inside of my lambda function, where can I find its log in the run time?

I mean after I push and publish my app, I want to check the lambda log.

**Comment by nubpro** [comment]
CloudWatch.

1. Open your lambda function in AWS console.
2. Click Monitoring tab.
3. View logs in Cloudwatch.

![image](https://user-images.githubusercontent.com/762914/103940629-9b5dda80-5168-11eb-9b48-3c5fdbc01655.png)

Hope it helps!

**Comment by mjza** [comment]
Thanks. Now I can see my output!
