### ISSUE TITLE
`amplify import auth` role issue to call rest apis

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-cli#6342]
**Describe the bug**
I have imported a cognito and identity pool in my amplify project.
When I am connected, I have the defined role in the identity pool, but this role is not the one used by my apis 

**Amplify CLI Version**
4.41.0

**To Reproduce**
- `amplify import auth`
- login 
- fetch an api

**Expected behavior**
The created apis must have a policy that includes the authRole and unauthRole defined in identity pool

**Screenshots**
```json

{
 "dev": {
    "awscloudformation": {
      "AuthRoleName": "amplify-connect-dev-191322-authRole",
      "UnauthRoleArn": "arn:aws:iam::<AWSAccountID>:role/amplify-connect-dev-191322-unauthRole",
      "AuthRoleArn": "arn:aws:iam::<AWSAccountID>:role/amplify-connect-dev-191322-authRole", // <- role expected by my apis
      "Region": "eu-west-1",
      "DeploymentBucketName": "amplify-connect-dev-191322-deployment",
      "UnauthRoleName": "amplify-connect-dev-191322-unauthRole",
      "StackName": "amplify-connect-dev-191322",
      "StackId": "arn:aws:cloudformation:eu-west-1:<AWSAccountID>:stack/amplify-connect-dev-191322/388c62e0-43b8-11eb-91ef-0688c03830a1",
      "AmplifyAppId": "d1hs2h53wjzqap"
    },
      "auth": {
        "connect813df658": {
          "userPoolId": "eu-west-1_YFiTKQPSg",
          "userPoolName": "ssoconnect95362d60_userpool_95362d60-dev",
          "webClientId": "<webClientID>",
          "nativeClientId": "<nativeClientID>",
          "identityPoolId": "eu-west-1:1edf629d-8393-41fa-b6c6-8c5a26c5c131",
          "identityPoolName": "ssoconnect95362d60_identitypool_95362d60__dev",
          "allowUnauthenticatedIdentities": true,
          "authRoleArn": "arn:aws:iam::<AWSAccountID>:role/amplify-ssoconnect-dev-110152-authRole",
          "authRoleName": "amplify-ssoconnect-dev-110152-authRole", // <- role defined in my identity pool
          "unauthRoleArn": "arn:aws:iam::<AWSAccountID>:role/amplify-ssoconnect-dev-110152-unauthRole",
          "unauthRoleName": "amplify-ssoconnect-dev-110152-unauthRole"
        }
      }
    }
```

**Desktop (please complete the following information):**
 - OS: [e.g. Mac/Windows/Ubuntu]
 Mac 
 - Node Version. You can use `node -v` to check the node version on your system
14.5

**Comment by mlecoq** [comment]
According to the documentation `Amplify CLI will update the policies attached to the roles to ensure Amplify categories function correctly. ` but policies are not updated to take into account the roles of the  imported identity pools

**Comment by mlecoq** [comment]
I didn't see this sentence `- This resource will be available for GraphQL APIs ('amplify add api')` 😥 - so there is no way to do it with rest apis ?

**Comment by SwaySway** [comment]
@mlecoq We currently have a feature request to support cognito user pools in rest apis. 
Closing in favor of that FR https://github.com/aws-amplify/amplify-cli/issues/3390

**Comment by mlecoq** [comment]
@SwaySway great - I have some apis that are public (so using unauth role) - does the FR cover this case ?
