### ISSUE TITLE
Datastore is not able to create createdAt timestamps automatically and failing silently (DataStore - failed to execute errorHandler Error: Field createdOn is required)

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-cli#6353]
**Describe the bug**
I  am using the timestamp feature for the graphql models and using the fields `createdOn` to access it from datastore as mentioned here #6310. I have 2 models that are using this feature and for one of the model, creation of a new item happens successfully in the local db but then throws an error after 1-2 sec it throws a console warning `Error: Field createdOn is required` and doesn't save in dynamodb.

This is a huge problem because for users it seems everything has worked and the item was saved when it wasn't.

Creating the item for the model through appsync console works perfectly. 

**Amplify CLI Version**
4.41.1

**To Reproduce**
Have multiple connected models and create a new item 

**Expected behavior**
New item should be created and saved in dynamodb

**Screenshots**
My schema 
```graphql
type Clients
  @model(timestamps: { createdAt: "createdOn", updatedAt: "updatedOn" })
{
  id: ID!
  name: String!
  email: String
  tenantId: ID!
  activeFlag: Boolean!
  projects: [Projects] @connection(keyName: "byClientId", fields: ["id"])
  createdOn: AWSDateTime!
  updatedOn: AWSDateTime!
}
type Projects
  @key(name: "byClientId", fields: ["parentClientId"])
  @key(name: "projectsByParentProjectId", fields: ["parentProjectId"])
  @model(timestamps: { createdAt: "createdOn", updatedAt: "updatedOn" })
 {
  id: ID!
  name: String!
  tenantId: ID!
  freelancers: [ID]
  parentProjectId: ID
  parentClientId: ID
  activeFlag: Boolean!
  childProjects: [Projects] @connection(keyName: "projectsByParentProjectId", fields: ["id"])
  quotes: [Quote] @connection(keyName: "quotesByParentProjectId", fields: ["id"])
  createdOn: AWSDateTime!
  updatedOn: AWSDateTime!
}
```

My datastore save code
```js
    await DataStore.save(
      new Clients({
        id: nanoid(),
        name: clientName,
        tenantId: tenantId,
        activeFlag: true,
      })
    )

      await DataStore.save(
        new Projects({
          id: nanoid(),
          name: projectName,
          tenantId: tenantId,
          activeFlag: true,
          parentClientId,
        })
      )
```

For `Clients` model the datastore save work but for `Projects` it fails 

Error
```
[WARN] 53:41.399 DataStore - failed to execute errorHandler Error: Field createdOn is required
    at datastore.ts:253
    at datastore.ts:330
    at Array.forEach (<anonymous>)
    at initializeInstance (datastore.ts:329)
    at datastore.ts:343
    at e.i.produce (immerClass.ts:97)
    at new Projects (datastore.ts:340)
    at MutationProcessor.modelInstanceCreator (datastore.ts:231)
    at MutationProcessor.<anonymous> (mutation.ts:300)
    at step (outbox.ts:133)
    at Object.throw (outbox.ts:133)
    at rejected (outbox.ts:133)
```

**Desktop (please complete the following information):**
 - OS: WSL 2 Ubuntu
 - Node Version. 12.18.4

**Comment by attilah** [comment]
@DevTGhosh since you like to depend on the auto assignment of the values for the timestamp field, you should make them optional in your schema, when Amplify CLI transforms your schema it will make these fields optional in the input type, but the model generator works from the input schema - as the output schema does not have all the information like connection and key definitions - and detects this field as mandatory. But in general even without transformation these fields should be optional when you depend on "server side" assignment of values.

Give it a try and get back with the results please.

**Comment by DevTGhosh** [comment]
The project item started saving automatically without me changing anything with the code or graphql schema. I can't replicate the bug anymore but the fact it was failing in dynamodb save while successfully saving in local db has me worried. For now I will update the schema to remove the required from the timestamp fields and use Appsync to create the items as a work around.  Maybe the team can replicate the issue and provide better error handling for edge cases like this.

**Comment by attilah** [comment]
Thanks for the update!

Closing the issue as it is a non-issue based on your answers.
