### ISSUE TITLE
improve CLI speed

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#6355]
**Is your feature request related to a problem? Please describe.**
every time I execute a command (e.g: `amplify update api`), it takes at least 6seconds of startup time before the command executes, same thing happens when you call amplify-cli via nodejs.

**Describe the solution you'd like**
Improve its CLI speed to be below 1 or 2s, I'm not an expert in the field but a few ideas would be to remove dependencies or create a single js file executable using ncc. or even better create binaries. I know it is a lot of work though but could be cool to have that!

**Comment by dabit3** [comment]
Are you using the npm global installation?

If so, have you tried installing using the new smaller packaged available via curl? It's at least 3x faster from my experience.

https://docs.amplify.aws/cli/start/install

That being said, it would also be nice to have better performance in general.

**Comment by anisg** [comment]
Nice, I reinstalled via Curl, and indeed now it's faster! (takes 2 to 3 seconds to start) thanks 👍

**Comment by attilah** [comment]
@anisg thanks for reporting this issue, as @dabit3 pointed out we have a package CLI version which already has some performance gains, but as we going forward these pain points are considered and continuously improved, so closing it as a 'non-issue' for now.
