### ISSUE TITLE
Amplify containers hosting only deploys with node version.

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-cli#6357]
When I was using the `curl` installed version of the Amplify CLI, I got this warning when running `amplify push` after adding container hosting using `amplify add hosting`:

```
Method generateHostingResources does not exist or not a function in category plugin: hosting.
An error occurred during the push operation: Method generateHostingResources does not exist or not a function in category plugin: hosting.
```

When I uninstalled the curl version of the CLI and installed the node version, deploying then worked.

The version I was on is `4.41.1`

**Comment by navaid7890** [comment]
@dabit3 I tried above solution but still the issue is not resolved, 
I am using the amplify version 4.41.2

![Screenshot from 2021-02-03 13-42-27](https://user-images.githubusercontent.com/26667775/106720879-cf240700-6625-11eb-8a05-865aa4c013ce.png)
