### ISSUE TITLE
Cannot perform headless init: returns "Environment name missing"

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#6362]
**Which Category is your question related to?**
CI / Headless

**Amplify CLI Version** 
4.41.1

**What AWS Services are you utilizing?**
Amplify auth, hosting, api, functions

**Provide additional details e.g. code snippets**

I want to do a headless init of an existing environment.
When running this init I get the error message `Environment name missing`.

This is the flow I followed:
* I have an amplify environment for this project running. The name of the environment is `dev`.
* install the amplify cli globally : `npm install -g @aws-amplify/cli@4.41.1 --unsafe-perm=true`
* create a script for headless init (source for the script: [https://docs.amplify.aws/cli/usage/headless#sample-script](https://docs.amplify.aws/cli/usage/headless#sample-script)), `init.sh`:
```
#!/bin/bash
set -e

IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"eu-west-1\"\
}"

AMPLIFY="{\
\"projectName\":\"MyAppName\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
—-amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```
* This is my `backend-config.file`:
```
{
  "auth": {
    "myappname1c7b3413": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [],
      "customAuth": false
    }
  },
  "api": {
    "myappname": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authmyappname1c7b3413"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
      }
    }
  },
  "storage": {
    "images": {
      "service": "S3",
      "providerPlugin": "awscloudformation"
    }
  },
  "function": {
    "emailReminder": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "myappname1c7b3413",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "api",
          "resourceName": "myappname",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    }
  },
  "hosting": {
    "amplifyhosting": {
      "service": "amplifyhosting",
      "providerPlugin": "awscloudformation",
      "type": "manual"
    }
  }
}
```

* I then run `./init.sh` providing the correct credentials which returns "Environment name missing"
* I checked that the credentials are valid by temporarily adding another aws command in the script `AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws lambda list-functions` which returned the expected result.

Can you help me figure out what is wrong: why can't I do a headless init of the environment and does it return the error message "Environment name missing"?

**Comment by attilah** [comment]
@Nxtra everything is correct with your script, the problem is "unicode". The first `-` character in front of --amplify is not a `-`. Replace it and it will work. I checked the docs site and it is correct there. We had some of these issues before, but they are all cleared up now.

Here is the selection of the `-` character in VS Code and notice that the first one is not selected:

![image](https://user-images.githubusercontent.com/230432/104254048-d68f3080-542a-11eb-9b0d-3ce277e3dd2b.png)

**Comment by Nxtra** [comment]
> @Nxtra everything is correct with your script, the problem is "unicode". The first `-` character in front of --amplify is not a `-` that is a "mdash" character. Replace it and it will work. I checked the docs site and it is correct there. We had some of these issues before, but they are all cleared up now.
> 
> Here is the selection of the `-` character in VS Code and notice that the first one is not selected:
> 
> ![image](https://user-images.githubusercontent.com/230432/104254048-d68f3080-542a-11eb-9b0d-3ce277e3dd2b.png)
> 
> For reference: https://en.wikipedia.org/wiki/Dash#Similar_characters_and_their_Unicode_code-points

Nice, thanks for figuring that out!
