### ISSUE TITLE
`*PolicyVersions` rights are missing for `amplify push` from Amplify UI "Full Access" User

### ISSUE THREAD

**Issue by BracketJohn** [aws-amplify/amplify-cli#6363]
**Describe the bug**

`PolicyVersion` rights are missing from Amplify UI "Full Access" users.

**To Reproduce**

Make a change to a graphql based API that requires `AuthRolePolicy` changes (I'm unsure what triggers this, for us it was likely the addition of scoial sign on). Afterwards, run `amplify push`. We received the following error on our first attempt, when using an Amplify UI user to authenticate: 

```sh
UPDATE_FAILED      AuthRolePolicy01 AWS::IAM::ManagedPolicy     Mon Jan 11 2021 12:40:34 GMT+0100 (Central European Standard Time) API: iam:ListPolicyVersions User: arn:aws:sts::XXX:assumed-role/eu-central-XXX_Full-access/XXX is not authorized to perform: iam:ListPolicyVersions on resource: policy arn:aws:iam::XXX:policy/amplify-XXX-YYY-ZZZ-apigraphqlAPI-XXX-AuthRolePolicy01-XXX
```

After creating a Policy that allows `iam:ListPolicyVersions` for the specific resource, we received an error that `iam:DeletePolicyVersions` was missing. Afterwards adding `DeletePolicyVersions` rights, we received an error for `CreatePolicyVersions`, now also the Rollback failed and the full stack entered the `UPDATE_ROLLBACK_FAILED` state. A "continue rollback" and then "amplify push" afterwords worked out and the `push` was successful.

**Expected behavior**

Successful push, even it `*PolicyVersions` rights are needed.

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which resources do you have configured?
  * Auth
  * Storage
  * Api (graphql)
  * Some lambda Functions 

Environment:
- OS: MacOS 10.15.7
- amplify CLI version: `4.41.1`
- admin UI enabled

**Comment by attilah** [comment]
@BracketJohn thanks for raising the issue in fact the `iam:CreatePolicyVersion` and `iam:DeletePolicyVersion` is missing from our [documentation](https://docs.amplify.aws/cli/usage/iam). Admin UI policies will also be fixed.

**Comment by attilah** [comment]
Fixed in: https://github.com/aws-amplify/docs/pull/2845

**Comment by BracketJohn** [comment]
Thanks for quickly addressing this - what PR/repo will Admin UI policies be fixed? Just so that I can track the fix status.

**Comment by anisg** [comment]
I got the same issue, a quick fix is to go to the IAM AWS console and search for this "full access" role, then edit its policies by adding CreatePolicyVersion and DeletePolicyVersion.

**Comment by kylekirkby** [comment]
I've just got the same issue whilst pushing an update to my API. Is it not possible for the Amplify CLI to update this users permissions? This `amplifyadmin` user was created when initializing this project.


```bash
Reason: API: iam:CreatePolicyVersion User: arn:aws:sts::xxxxxxxx:assumed-role/us-east-1_Llgylt720_Full-access/amplifyadmin is not authorized to perform: iam:CreatePolicyVersion on resource: policy arn:aws:iam::xxxxxxxxx:policy/amplify-xxxxxxx-develop-164858-xxxxxxx-GJXUTPLAQHP1-UnauthRolePolicy01-1NJ7KKBCS5KTR
```

**Comment by regischow** [comment]
@attilah as this has been fixed in the documentation, but will the managed policy, arn:aws:iam::aws:policy/AdministratorAccess-Amplify, be fixed as well?
