### ISSUE TITLE
amplify-appsync-simulator - 401 for token.iss ending with forward slash

### ISSUE THREAD

**Issue by safonovklim** [aws-amplify/amplify-cli#6368]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

**Given** I using `amplify-appsync-simulator`

and I use `OPENID_CONNECT` auth type

and I use OIDC Issuer:
- `https://xxxxxx.auth0.com` OR
- `https://xxxxxx.auth0.com/`

**When** I make request with JWT token 

And token.iss (issuer) is `https://xxxxxx.auth0.com/`

**Simulator throw 401 Unauthorized**

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

- `amplify-appsync-simulator`: 1.24.3

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**

Expected 200 OK

**Screenshots**

Line 33 (see screenshot) will always throw `false` if `token.iss` ends with forward slash

token - `function isValidOIDCToken(token...)`:

```
{
  iss: 'https://xxxxxx.auth0.com/',
  sub: 'auth0|xxxxxx',
  aud: 'xxxxxx',
  iat: xxxxxx,
  exp: xxxxxx,
  azp: 'xxxxx',
  scope: 'read write',
  gty: 'password'
}
```

oidcIssuers (line 26):

```
[
  "https://xxxxxx.auth0.com"
]
```

![image](https://user-images.githubusercontent.com/9365521/104328743-2dfdd100-54fd-11eb-905f-23110d768fa5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version: v12.18.3

**Additional context**

This bug was introduced by:

- https://github.com/aws-amplify/amplify-cli/issues/5372
- https://github.com/aws-amplify/amplify-cli/pull/5434/files

Function `isValidOIDCToken` removes forward slash from AuthType.Issuer only, but should remove from `token.iss` too!

**Comment by safonovklim** [comment]
PR Fix: https://github.com/aws-amplify/amplify-cli/pull/6364

**Comment by attilah** [comment]
@safonovklim thanks for the reporting and fix!
