### ISSUE TITLE
Codegen out of sync with current schema

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#637]
**Describe the bug**
I have made updates to my schema, and it has apparently completed successfully (I have verified that the schema is correct by manually checking the AppSync console).  However, running `amplify status` notes that the GraphQL API still is in "Update" status and I believe as a result, the codegen is now generating using an outdated version of the schema.  When finished, it warns me that the schema needs to be pushed.  **I believe the root issue to be that the local environment is no longer aware that it is synced with the remote, or something to that effect, after running `amplify push`.**

**To Reproduce**
1. Running codegen results in the above mentioned situation.

**Expected behavior**
Codegen should grab the most recent schema and use it for codegen.

**Screenshots**
Result of `amplify codegen`
![image](https://user-images.githubusercontent.com/686823/50520397-b7144d80-0a85-11e9-933c-f2caccb86b0e.png)

I continue to get the above result after running `amplify push`.  I have also tried deleting the build folder to regenerate everything and this didn't appear to affect anything.

$ amplify -v
0.2.1-multienv.17

**Comment by UnleashedMind** [comment]
I am not able to reproduce the issue you described. 
But I'm using a very simple schema. 
Can you share your schema, or a similar schema that can reproduce the issue without leaking sensitive information? I will give it another try with your schema.

**Comment by UnleashedMind** [comment]
Please send it over to zhoweimi@amazon.com

**Comment by mwarger** [comment]
I created a new local environment by running init, and I'm not seeing this problem anymore.  Something must have just gotten out of sync between the remote and local versions of the templates...

**Comment by UnleashedMind** [comment]
great!
I'm glad things worked out.
