### ISSUE TITLE
Auth section missing from amplifyconfiguration.json with CLI version 4.41.1

### ISSUE THREAD

**Issue by peter-trevan-bluefruit** [aws-amplify/amplify-cli#6377]
**Describe the bug**
I've just upgraded from version 4.41.0 to 4.41.1.

When I run `amplify pull` or `amplify init` from my Android app's repo the resulting "amplifyconfiguration.json" is missing entire contents of `"auth":{"plugins": {}}`. When I downgrade to amplify version 4.41.0 this is not the case.

**Amplify CLI Version**
4.41.1

**To Reproduce**

1. Setup android amplify project
2. Add Congito auth as described here https://docs.amplify.aws/lib/auth/signin/q/platform/android
3. Open app\src\main\res\raw\amplifyconfiguration.json and observe the "auth > plugins" section is empty.

**Expected behavior**

With amplify 4.41.0 I get the following"

```
"auth": {
    "plugins": {
        "awsCognitoAuthPlugin": {
            "UserAgent": "aws-amplify-cli/0.1.0",
            "Version": "0.1.0",
            "IdentityManager": {
                "Default": {}
            },
            "CredentialsProvider": {
                <CredentialsProvider>
            },
            "CognitoUserPool": {
                <CognitoUserPool>
            },
            "Auth": {
                <Auth>
            }
        }
    }
}
```

But with 4.41.1:

```
"auth": {
    "plugins": {}
}
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v14.15.1

**Comment by attilah** [comment]
It was a known regression in 4.41.1, that we addressed in 4.41.2 which was just release, update the CLI, sorry for the inconvenience.
