### ISSUE TITLE
Fine grained access control for environments

### ISSUE THREAD

**Issue by Jupdi** [aws-amplify/amplify-cli#6379]
**Is your feature request related to a problem? Please describe.**
All developers on our project are able to access all environments, so everyone can access customer/production data and possibly accidentally delete it. 

**Describe the solution you'd like**
A possibillity to control the access of the cli features and if best the access of the resources itself. The most important feature would be to allow users just to access certain environments.

**Describe alternatives you've considered**
I tried doing that via IAM and the resource restriction is possible, but i cant control the access per environment. Also its very exhausting to keep up with all resource changes.

**Comment by attilah** [comment]
@Jupdi thanks for the suggestion, but the CLI itself has no authorization model builtin and the security aspects you are looking for must be done at AWS level. In the team workflow [docs page](https://docs.amplify.aws/cli/teams/overview) we provide some possibilities on how teams could work, individual account per team member give the best isolation so everyone can be admin and as no sensitive data like credentials or anything saved by Amplify into the source files, Prod, Staging, etc environments should be secured by the AWS provided ways as well, accessed by only CI/CD servers and such. That kind of fine grained auth is out of scope for the CLI.
