### ISSUE TITLE
Hosted UI has Invalid Resource URLs

### ISSUE THREAD

**Issue by chancyk** [aws-amplify/amplify-cli#6380]
**Describe the bug**
Clicking on the Hosted UI endpoint brings up a page that displays nothing, seemingly because the embedded URLs are broken, such as:
```html
<script src="null/null/js/jquery-3.4.1.min.js"></script>
```

**To Reproduce**
1. Setup auth with `amplify add auth`
2. Open the provided Hosted UI endpoint from `amplify status`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by attilah** [comment]
@chancyk the `Hosted UI Endpoint` link in itself does not have to render a working login page, the CLI prints out the `Test Your Hosted UI Endpoint`, which is the same url but with correctly parameterized for testing. If you check it, it will show the login form for your user pool.

```
Hosted UI Endpoint: https://<your name here>-dev.auth.us-west-2.amazoncognito.com/
Test Your Hosted UI Endpoint: https://<your name here>-dev.auth.us-west-2.amazoncognito.com/login?response_type=code&client_id=<your app client id>&redirect_uri=<your redirect url>
```
