### ISSUE TITLE
Identity Pool Authentication Provider App ID Blank After Adding Facebook Auth

### ISSUE THREAD

**Issue by pnewhook** [aws-amplify/amplify-cli#6383]
**Describe the bug**
After setting up Facebook login for my Amplify app, I couldn't login until I updated the Facebook App ID in the AWS console.
![2021-01-13 10_27_40-Editing amplifytest02313e3b_identitypool_02313e3b__dev - Amazon Cognito - Amazon](https://user-images.githubusercontent.com/92876/104516689-c5792780-55c2-11eb-810b-0a2375e6bba6.png)

**Amplify CLI Version**
4.41.1

**To Reproduce**
1. amplify add auth
2. go through the steps and provide a facebook app id and secrect when asked
3. amplify publish
4. Try to login you'll get the error "Token is not from a supported provider of this identity pool."

**Expected behavior**
This should be setup after completing the cli/push workflow. Facebook was setup as an external identity provider uner my user pools, but not within the identity pool settings

**Screenshots**
![2021-01-13 10_28_21-React App](https://user-images.githubusercontent.com/92876/104517655-6ddbbb80-55c4-11eb-8f85-d02330eca7bc.png)

**Desktop (please complete the following information):**
Windows
v14.15.3

**Comment by kaustavghosh06** [comment]
@pnewhook When you add auth with the CLI and go through the default social login flow we configure the cognito user pool hosted UI flows. You can view and find your Facebook access id/secret in the cognito user pool - third party provider section instead.

**Comment by pnewhook** [comment]
@kaustavghosh06 I can find my app Id/secret in multiple places, the problem is it isn't configure in the place it NEEDS to be set, which I've included in the screenshot

**Comment by kaustavghosh06** [comment]
@pnewhook We do not setup social federation with identity pools which you've included in the screenshot. We set it with the cognito user pool and you can find it in the cognito user pool console. I'm attaching the screenshot of where you can find it. From. your screenshot it looks like the cognito identity pool console.

<img width="1792" alt="Screen Shot 2021-03-19 at 12 17 14 PM" src="https://user-images.githubusercontent.com/7247658/111831833-2831bc80-88ad-11eb-9a2a-72ceb5895b89.png">
