### ISSUE TITLE
amplify push - An error occurred when pushing the resources to the cloud

### ISSUE THREAD

**Issue by sundarcodes** [aws-amplify/amplify-cli#6385]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
On doing `amplify push`, getting the following error - 

```
An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```
When I use amplify cli version 4.36.0, I do not get error for the same changes to the backend. Its one of later version of cli after 4.36.0 that is causing this issue.

**Amplify CLI Version**
4.41.2

**To Reproduce**
* Change in amplify backend
* Run `amplify push`

**Expected behavior**
All resources should be updated successfully in the cloud.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.16.3

**Additional context**
After I tried with v4.41.2 and got this error, I did a roll back to 4.36.0 and it worked like a charm. So it the newer version thats causing this. Any help on this would be highly appreciated.

**Comment by attilah** [comment]
@sundarcodes you have a project state which is successfully pushed with 4.36.0 but if you update to 4.41.2 then push fails? What `amplify status` shows, which type of resources are updated? If you go to the CloudFormation console, you have to see some error about what fails during the stack deploy or either in the terminal where you execute the push.

It looks like when you do the push the stack is still updating or in some other states, that could be checked in the CF console to see the exact problem.

**Comment by sundarcodes** [comment]
> @sundarcodes you have a project state which is successfully pushed with 4.36.0 but if you update to 4.41.2 then push fails? 

Yes, the same project state when pushed using 4.36.0 works good. But when using 4.41.2, it fails.

> What `amplify status` shows, which type of resources are updated? If you go to the CloudFormation console, you have to see some error about what fails during the stack deploy or either in the terminal where you execute the push.

Actually the type of resources doesn't seem to matter. Just did a small change to the api resource and tried.

Steps:
1. Changed in schema.graphql
2. `amplify status` said changes to API
3. `amplify push` - Failed with *Resource is not in the state stackUpdateComplete* message. The CF console shows this.
![Screenshot 2021-01-15 at 5 30 20 AM](https://user-images.githubusercontent.com/10928793/104663385-e6d93100-56f2-11eb-9716-9f95b1e0a150.png)

4. Rolled back to 4.36.0
5. `amplify status` still said changes to API
6. 'amplify push` pushed all changes to cloud without any errors/rollback.

> It looks like when you do the push the stack is still updating or in some other states, that could be checked in the CF console to see the exact problem.
Seems to happen only in the latest version.


Please let me know if any other info is required. Thanks for your prompt response.

**Comment by attilah** [comment]
That Lambda seems to be generated for triggers configured and CF cannot find it, hence the error.

Is the result the same if you `amplify push --forcePush --yes` with the latest CLI also fails?

**Comment by sundarcodes** [comment]
@attilah `amplify push --forcePush --yes` didn't work as well. All the devs in our team have rolled back aws cli to 4.36.0 and working to not have an impact in our development sprints. Just curious and for our understanding - was there any code changes done in the recent versions of the cli to do a strict check and do a rollback to `amplify push` when some function does not exist and when the cli cannot find it.

**Comment by kaustavghosh06** [comment]
@sundarcodes Does everything work fine with v 4.36.0 and your deployments succeed?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further communication.
