### ISSUE TITLE
New enableIterativeGsiUpdates feature fails with Rate exceeded Error

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#6388]
**Describe the bug**

I have set enableIterativeGsiUpdates to true because I need to make about 300 GSI modifications spread across 48 models.

I do it in 2 parts - first step to compile and it does so successfully. Long story about why I have to do it in 2 parts.

$ amplify api gql-compile --minify

Next step is the push

$ amplify push --no-gql-override --yes

Unfortunately it fails with the following error

✖ An error occurred when pushing the resources to the cloud

Rate exceeded
An error occurred during the push operation: Rate exceeded

=======================================

Appreciate any suggestions on how I can do this throttling.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Steps defined above

**Expected behavior**
Successful push

**Comment by attilah** [comment]
@sacrampton that is a lot of updates ;-) even with support for iterative updates I would suggest to reach out to customer support and try to increase the rate limits if possible. Throttling is not something we control as I assume - please confirm - that this Rate limitation comes from CF itself from the underlying DynamoDB update? or CF itself?

As a workaround you could phase your modifications of the schema to get a successful push.

If you can give some background on how you ended up with 300 updates that could help to understand more if we can do something around it. Is is happening during your regular dev flow of a project or a major refactoring or something else?

**Comment by sacrampton** [comment]
Hi @attilah - I'll reach out to support to see if CloudFormation can change throttling. I'll try a few work arounds.

The reason for this is that I'm trying to get DataStore to work with an existing application. This has been an off again / on again process for at least a year - every time we get into it we run into a major road block. We've been working through them and the latest one is how the GSI's are defined. 

Our app has been developed over time and connections are declared like this. 
```
assetVisit: [AssetVisit] @connection (name: "AssetAssetVisit", sortField: "lastPhotoTaken" )  
```

However, if you do that then DataStore doesn't work. You have to use the @key directive to create all GSI's and then declare the connection like this.
```
assetVisit: [AssetVisit] @connection(keyName: "byAssetVisitAssetId", fields: ["id"])
```

Which on the back end means the original GSI has to be deleted and a new GSI created - so with about 150 connections then that means 300 updates.

**Comment by attilah** [comment]
@sacrampton did you see any throttling value in CloudWatch or CloudTrail(?) which shows how long are you throttled? One uber-advanced thing came to my mind, that if we would maximize resources within update steps AND add a delay (how long?) between steps...perhaps that could help with throttling...but it depends on the length of the throttling...

**Comment by sacrampton** [comment]
Hi @attilah - sadly the only options for CloudFormation service limit increase are:

- Cloudformation Stack Limit
- Module Limit per Account
- Version Limit per Module

There is no option to request any service limit increase for CloudTrail

There is no mention of any throttling value on CloudFormation - I'm assuming that is what is happening given that the amplify push error says "An error occurred during the push operation: Rate exceeded" and various searches said this was a throttling issue.

Some online suggestions were to add DependsOn statements. So I also edited cloudformation-template.json to add DependsOn after every model such that it waited for the previous model. I've done that before when amplify push crashes when creating lots of DynamoDB resources simultaneously - but that made no difference this time.

**Comment by sacrampton** [comment]
Hi @attilah  - I just halved the number of updates and got exactly the same error. Rather than continuous trial and error it would be good to understand the threshold that is causing this to choke. I can't see anything in CloudFormation that impacts this.

Obviously enableIterativeGsiUpdates is a long sought after addition, but if all that does is cause CloudFormation to choke then its not really helping. But I'm also now sure how to progress this, or precisely where the choke point it.

Appreciate anything you can do to progress this as it is a really important feature to move beyond experimental status.

**Comment by GeorgeBellTMH** [comment]
The non-ideal solution is to sleep(x) between iterations...

**Comment by sacrampton** [comment]
Hi @GeorgeBellTMH - just want to check with you - is this something that I can configure, or is it a modification that needs to happen within the amplify framework

**Comment by attilah** [comment]
I'm marking it as an enhancement to make sure we are tracking it.

**Comment by jcbdev** [comment]
I've just gotten this with one index update, almost instantly as well.  It doesn't even start running the cloudformation.

Comment out the index and it works 🤷‍♂️ 

Interestingly I could not get feature working on my demo branch at all (constantly complaining about multiple GSI updates) but when I switch to a fresh environment I get this just making one index change (new environment *since* adding the flag instead of the demo one which existed before enabling)

**Comment by renebrandel** [comment]
We've got a new logic to wait for the index to be created. Please create a new issue if this still happens.
