### ISSUE TITLE
authorisation control based on data in the tables!

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6389]
**Which Category is your question related to?**
Usage

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
Cognito + Dynamodb

I am developing a B2B app. It means I have some customers (users) that are Admins and also some customers of the customer (normal users) and some employee of my customers. 

Now assume I have the following models:

```graphql
type User
@model 
@key(name: "byEmail", fields: ["email"], queryField: "listUsersByEmail")
@auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[create, delete, read]},
              {allow: owner, ownerField: "id", operations: [update, read]}
             ])
{
  id: ID!
  email: String!
  name: String
  status: String  
  createdAt: String
  updatedAt: String
}


type Institute
@model 
@key(name: "sortByName", fields: ["self", "name"], queryField: "listInstitutesSortByName")
@auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow: private, provider: userPools, operations: [read]}
            ]) 
{
  id: ID!
  self: Int! @default(value: "1") @auto
  name: String!  
  address: String
  tell: String
}


type Employee
@model 
@key(name: "byInstitute", fields: ["instituteId"], queryField: "listEmployeesByInstitute")
@auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[create, update, delete, read]},
              {allow: owner, ownerField: "userId", operations: [read]}              
             ]) 
{
  id: ID!
  instituteId: ID @assert(condition: ".length() > 1") @auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[create, update, delete, read]},
              {allow: owner, ownerField: "userId", operations: [read]}
             ])
  institute: Institute @connection(keyField: "instituteId")
  userId: ID @assert(condition: ".length() > 1") @auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[create, update, delete, read]},
              {allow: owner, ownerField: "userId", operations: [read]}
             ])
  user: User @connection(keyField: "userId")
  suspended: Int @default(value: "0") @auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[create, update, delete, read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[create, update, delete, read]},
              {allow: owner, ownerField: "userId", operations: [read]}
             ])
  accepted: Int @default(value: "0") @auth(rules: [{allow:groups, groups:["Supers"], provider: userPools, operations:[read]}, 
              {allow:groups, groups:["Admins"], provider: userPools, operations:[read]},
              {allow: owner, ownerField: "userId", operations: [update,read]}              
             ])
}
```

I have a list of users and institutes. Each users can belong to 1 or more institutes via Employee model. 

Now the question is:

**I limited creation of employees to Admins. How can I allow admins of a specific institutes to modify all employees of that institutes?**

On the other hand, all users (including admins) have at least an entry in my employee table. 
While the users have different groups: Admins and Employees.
Now a user belong to an institute + he or she is an Admin -> then I want he or she could only manipulate those employees entries that are belong to the same institute. 

**Or how can I say, allow admins to manipulate a row in the employees table, if and only if, they have an entry in the employees table with the same `InstituteId`**

**Comment by attilah** [comment]
@mjza you have multiple options here, depending on number of institutes you can have 1 group per institute and validate it with dynamic `group` but you can run into group count limitations if you have a lot of them. A more scalable way would be to have a Cognito pre-token generation trigger that adds the list of institutes to a custom claim that will be present in the JWT token issued by Cognito. Then in a custom resolver you can check if the passed in `instituteId` in the request can be found in the the custom claim.
Another solution could be to use a pipeline resolver and instead of having a claim in one of the steps in the pipeline resolver do the same check against DynamoDB there and then allow the execution to the next step in the pipeline resolver or fail with authorization error.

I'm closing the issue as answered your question, if something new comes up feel free to comment or open a new issue.

**Comment by mjza** [comment]
@attilah Could you provide any documentation or link to a tutorial for the last 2 suggestions?
