### ISSUE TITLE
`amplify auth update` break the config file of "Email Verification Link with Redirect" option

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6397]
**Describe the bug**
The command `amplify auth update` break the config file of "Email Verification Link with Redirect" option.

**Amplify CLI Version**
4.41.2

# To Reproduce
## 1
```shell
amplify add auth # make sure you have selected the "Email Verification Link with Redirect" option
amplify push
```

## 2
check the following files
* amplify/backend/function/xxxCustomMessage/function-parameters.json
* amplify/backend/function/xxxCustomMessage/parameters.json

```shell
amplify auth update # make sure you have changed some parameters of "Email Verification Link with Redirect" option
```
## 3
check the following files again to see the changes
* amplify/backend/function/xxxCustomMessage/function-parameters.json (`triggerEnvs` key is not an array anymore)
* amplify/backend/function/xxxCustomMessage/parameters.json (`resourceName` key is removed)

related issue https://github.com/aws-amplify/amplify-cli/issues/5720

**Comment by attilah** [comment]
@yaquawa thanks for the detailed repro, I was able to find the issue, push was not needed, just add auth and update auth to reproduce it in the end.

**Comment by yaquawa** [comment]
@attilah Thanks for fixing this issue!

I have a question, can you tell me what is the following file for?
`amplify/backend/function/xxx/parameters.json`
Is this the parameters for the cloudformation template?
I can't find any information for this file.
Thanks.
