### ISSUE TITLE
TS2307 error when importing dependencies to TypeScript files

### ISSUE THREAD

**Issue by flogy** [aws-amplify/amplify-cli#6398]
**Which Category is your question related to?**
Using TypeScript for Amplify functions (for a REST API).

**Amplify CLI Version** 

4.23.1

**What AWS Services are you utilizing?**

Only one REST API with one lambda function.

**Provide additional details e.g. code snippets**

I am trying to migrate my existing Amplify REST API to TypeScript. Following the https://docs.amplify.aws/cli/function/build-options guide, I restructured my code directory and added a script to transpile my code prior pushing it to AWS. However, when executing the script (or using `amplify push`), I get `TS2307` errors like the following one:

```
ts/app.ts:3:44 - error TS2307: Cannot find module 'aws-serverless-express' or its corresponding type declarations.
3 import awsServerlessExpressMiddleware from 'aws-serverless-express'
```

It seems like my external dependencies, which are installed in the function's `package.json` can not be resolved when using TypeScript.

**Here is how me directory structure looks like:**

```
amplify/backend/function/test
|- src
   |- node_modules
   |- event.json
   |- package-lock.json
   |- package.json <-- here the imported dependencies are installed
|- lib
   |- app.ts <-- here I'm trying to access the dependencies
   |- index.ts
|- tsconfig.json
```

I guess it is because the `lib` directory is outside the `src` directory where the `package.json` lives? That would mean [Amplify's build options manual](https://docs.amplify.aws/cli/function/build-options) does not work when using any dependencies.

How can this be resolved?

**Interesting side note:**
It seems like only some of the dependencies can't be resolved: There are no issues with importing `express` and `body-parser`.

Thanks in advance.

**Comment by attilah** [comment]
@flogy yes, that's the root cause I think you are right. We'll check the above guide with external dependencies if there are some errors.

As a workaround I can share in one project here is how I used TS with external and shared dependencies:

- in root package.json I had this entry:
```
"amplify:<functionName>": "cd amplify/backend/function/<functionName>/src && yarn && yarn build",
```
- in the function's package.json I handled the local build of the package:
```
"build": "yarn clean && touch package.json && tsc && cp ./lib/* . && rimraf lib tsconfig.tsbuildinfo",
"clean": "rimraf tsconfig.tsbuildinfo lib ./index.d* ./index.js*"
```

here is my function structure:
```
.
├── function-parameters.json
├── <functionName>-cloudformation-template.json
└── src
    ├── node_modules
    ├── package.json
    ├── src
    │   └── index.ts
    ├── tsconfig.json
    └── yarn.lock
```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES6",
    "rootDir": "src",
    "outDir": "lib",
  },
  "references": [
  ],
  "exclude": [
    "**/lib/**/*"
  ]
}
```

Let me know if this helps to resolve your problem.

**Comment by flogy** [comment]
Hi @attilah 

Thank you very much for your workaround. I was not able to get it to run though, but it inspired me to build another workaround:

```
<functionName>
├── function-parameters.json
├── .gitignore <-- to ignore the generated contents of the `src` directory
├── src <-- empty, but needs to exist to make `amplify push` work
└── ts
        ├── node_modules
        ├── src <-- containing my `index.ts` and other TypeScript source files
        ├── event.json
        ├── package-lock.json
        ├── package.json
        └──  tsconfig.json
```

.gitignore

```
/src/*
```

tsconfig.json

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "module": "CommonJS",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "outDir": "../src",
    "baseUrl": "./",
    "rootDir": "./src",
    "paths": {
      "src": ["./src"]
    }
  }
}
```

function package.json

```json
"scripts": {
    "build": "npm run clean && tsc && copyfiles -e '**/*.ts' -e 'tsconfig.json' '**/**' ../src",
    "clean": "rimraf ../src/*"
  },
```

project package.json

```json
"scripts": {
    "amplify:<functionName>": "cd amplify/backend/function/<functionName>/ts && npm install && npm run build && cd -"
  },
```

This resolved my problem.

It would still be awesome though if an easier solution for external dependencies could be documented in the Amplify CLI docs.

Thanks for your nice support!
