### ISSUE TITLE
Mocking functions and dynamodb when using cognito user pools don't authenticate

### ISSUE THREAD

**Issue by CSTDev** [aws-amplify/amplify-cli#6399]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Mocking

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.37.1

**What AWS Services are you utilizing?**
Amplify, Dynamodb, Cognito

**Provide additional details e.g. code snippets**
I'm trying to develop a function locally using the aws-go-sdk, the function should talk to my dynamodb table and the used as a resolver for a graphql function. It's using cognito auth. 

I've been able to use the following config to connect to the mocked dynamodb from a function:
```
sess := session.Must(session.NewSession(&aws.Config{
		Region:      aws.String("us-fake-1"),
		Endpoint:    aws.String("http://localhost:62224"),
		Credentials: credentials.NewStaticCredentials("fake", "fake", "fake"),
	}))
```
Is there a way not to have to hardcode this?

Does amplify mock cognito in any way? I know I can select a userpool in the OneGraph Graphql console, but does that get passed through with the graphql query to the function, and does the local dynamodb respect that authentication?

What user does the function use when mocked?

**Comment by attilah** [comment]
@CSTDev currently Today there is no better way to do it, but I mark it as an enhancement so we can track this.

**Comment by edwardfoyle** [comment]
We have made several improvements to mock in the latest version of the CLI and have documented how to handle this use case here: https://docs.amplify.aws/cli/usage/mock#connecting-to-a-mock-model-table

You can install the latest version of the CLI to try it out.
