### ISSUE TITLE
Updating schema SDL not detected by Amplify

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-cli#64]
**Do you want to request a feature or report a bug?**
Bug?

**What is the current behavior?**
I update my schema and save it, run `amplify push`, and it makes no changes to the AppSync API.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**

1. Modify schema
2. Run `amplify push` (or `amplify api push`)

**What is the expected behavior?**
Changes should be detected and the AppSync schema & resolvers should be updated

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
macOS 10.13.6

* **Output of ``amplify --version``**:
0.1.14

* **Did this work in previous versions?**: Y/N
N/A

**Comment by kaustavghosh06** [comment]
Did you update the schema file in the amplify/backend/<resource-name>/schema.qraphl file which has the annotated schema in it?

**Comment by ffxsam** [comment]
Ahh, I wasn't aware it was just copying my schema file somewhere else. I thought it would just keep a pointer to mine, and use that as the source of truth. Thanks.

**Comment by elmarti** [comment]
For anyone else having problems with this, whilst working fast, I was editing the schema as it was being pushed, which seemed to upset the file watcher. By the time I came run `amplify push`, it was not aware that the file had been updated and I had to force it by adding a dummy type.
