### ISSUE TITLE
UserPoolClientRole has gone missing

### ISSUE THREAD

**Issue by t-lm** [aws-amplify/amplify-cli#6400]
**Describe the bug**
Amplify deployment fails because one of the ressources (UserPoolClientRol) in one of the cloud formation stacks (auth service) has gone missing from IAM (no entity found). 

**Amplify CLI Version**
4.18.0

**To Reproduce**
...

**Expected behavior**
I do not understand how the IAM role has been removed from IAM. It should be there.

**Screenshots**
<img width="1680" alt="Capture d’écran 2021-01-16 à 10 14 31" src="https://user-images.githubusercontent.com/48994853/104808028-bcb36c00-57e3-11eb-91f8-84d5a8f58294.png">

**Desktop (please complete the following information):**
- OS: Mac
- Node Version: v12.13.1

**Log output**
**Additional context**
No action from my end. Ressource has gone missing.

**Comment by attilah** [comment]
@t-lm please use the issue template to provide all the information we require to be able to help you better.

**Comment by kaustavghosh06** [comment]
Closing due to lack of further response.
