### ISSUE TITLE
Error on 'amplify push --force' after upgrade to @aws-amplify/cli 4.40.0

### ISSUE THREAD

**Issue by sonisourabh** [aws-amplify/amplify-cli#6406]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I have upgrade `@aws-amplify/cli` to version  `4.40.0`. Next when I do `amplify push --force`, getting the following error 
`Reason: CustomResource attribute error: Vendor response doesn't contain Id key in object`

**Amplify CLI Version**
4.40.0

**To Reproduce**
 `amplify push --force`

**Expected behavior**
All resources should be updated successfully in the cloud.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Node Version: v14.8.0

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**
When I rolled back the  `@aws-amplify/cli` to version  `4.39.0`, the `amplify push --force` works successfully.

**Comment by ammarkarachi** [comment]
@sonisourabh which categories are you using? more info would help us resolving this issue fasgter

**Comment by sonisourabh** [comment]
> 
> 
> @sonisourabh which categories are you using? more info would help us resolving this issue fasgter

I am using following categories
- `auth`
- `storage`
- `api`
- `analytics`

**Comment by ammarkarachi** [comment]
@sonisourabh If you are able to can you send us your amplify folder to amplify-cli@amazon.com look into this further. Be sure to include the issue number in the subject

**Comment by sonisourabh** [comment]
@ammarkarachi I have just sent the amplify folder to the mentioned email id. Please have a look.

**Comment by sonisourabh** [comment]
@ammarkarachi Have you got a chance to look at zip folder I shared over email

**Comment by ammarkarachi** [comment]
@sonisourabh I am afraid I cannot find the email can you please send it again?

**Comment by sonisourabh** [comment]
> 
> 
> @sonisourabh I am afraid I cannot find the email can you please send it again?
@ammarkarachi  I have sent the email again. Please have a look. Thanks

**Comment by sonisourabh** [comment]
@ammarkarachi Have you got a chance to look at zip folder I shared over email

**Comment by ammarkarachi** [comment]
@sonisourabh Got it looking at it now

**Comment by ammarkarachi** [comment]
@sonisourabh Just to confirm have you changed your Auth from API Key to Cognito?

**Comment by sonisourabh** [comment]
Yes. I use AMAZON_COGNITO_USER_POOLS or AWS_IAM based on the user context. For federated user AWS_IAM otherwise AMAZON_COGNITO_USER_POOLS

**Comment by ammarkarachi** [comment]
@sonisourabh I still see the CFN outputs graphql api key if you could update your api to use cognito and try pushing.

**Comment by ammarkarachi** [comment]
@sonisourabh I am closing this issue let me know if that works
