### ISSUE TITLE
API Mock Server: Go Function connected to a GraphQL resolver has an already done context

### ISSUE THREAD

**Issue by borgstrom** [aws-amplify/amplify-cli#6407]
**Describe the bug**

Golang Lambda functions get access to a context object: https://docs.aws.amazon.com/lambda/latest/dg/golang-context.html

This can be used to ensure async work is cleaned up when the function execution is cancelled or times out.

In the API mock server, this context is already done as soon as the function start.

**Amplify CLI Version**

```
#509 ❯❯❯ amplify -v
4.41.2
```

**To Reproduce**

Add a Go function, with all the defaults:

```
#502 ❯❯❯ amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: playground81901fc0
? Choose the runtime that you want to use: Go
Only one template found - using Hello World by default.

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource playground81901fc0 locally.
```

Change the `HandleRequest` function from the default scaffolding to be:

```go
func HandleRequest(ctx context.Context, name MyEvent) (string, error) {
	select {
	case <-ctx.Done():
		return "", fmt.Errorf("context is done")

	default:
		return fmt.Sprintf("Hello %s!", name.Name), nil
	}
}
```

Connect this to a GraphQL resolver:

```gql
type Query {
    goFunc(): String! @function(name: "playground81901fc0-${env}")
}
```

Run the query and you'll get back:

```json
{"Response":"","Error":":context is done"}
```

For now, I work around this by checking if `REGION` is `us-east-1-fake` and then manually creating a context with my own timeout.

**Expected behavior**

Context is not done.

**Comment by nikhname** [comment]
@borgstrom was the context object already done only when you were using the mock server?

**Comment by borgstrom** [comment]
@nikhname - That is correct. The context is only already done using the mock server.

**Comment by cjihrig** [comment]
A fix for this landed in https://github.com/aws-amplify/amplify-cli/commit/d67af7689efecdd9282eba8cfd678223f729cf64, and it should be available in the next release.
