### ISSUE TITLE
Notifications preserve status 'create'

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#6408]
**Describe the bug**
I already have Notifications set up (both FCM and APNS) in the cloud using the Amplify CLI on one device.
I install the Amplify CLI on a second device and run *Amplify pull*.
I don't specify the APNS certificate and FCM API key, because these keys are already set in the cloud.
Everything is fine except for *Notifications*  which remain in status *Create*, even after *Amplify push --force*.

**Amplify CLI Version**
4.41.2

**Desktop**
second device: macOS Big Sur

**Comment by nikhname** [comment]
@avlonder is the status of notifications in the create state when you run ```amplify push``` as well as ```amplify status```?

**Comment by avlonder** [comment]
@nikhname, yes it was. I deleted the full cloudformation stack and started from scratch again. But I hope similar things won't happen anymore once the app is in production

**Comment by nikhname** [comment]
I was not able to reproduce this. Closing but comment or re-open the issue if it reappears.
