### ISSUE TITLE
Amplify env add is broken

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#6411]
**Describe the bug**
Trying to add a new environment on an existing amplify project fails with the following error.  This is a recent issues as this never used to occur but has started occurring in my CI builds and on developer machines recently
```
TypeError: Cannot read property 'lastPushTimeStamp' of undefined
```

From what I can tell I have multiple lambda functions which rely on the api (in backend-config.json) but there is no dedicated section in backend-config.json for the api in the api: {} structure
```
"dependsOn": [
                {
                    "category": "api",
                    "resourceName": "roarapp",
                    "attributes": [
                        "GraphQLAPIIdOutput",
                        "GraphQLAPIEndpointOutput"
                    ]
                }
            ]
```

The api section exists in amplify-meta.json for existing enviroments and I have not had an issue previously but now there seems to be an issue.  I am assuming on createing a new environment the cli it is copying backend-config.json to create a new amplify-meta.json and then following line fails in `@aws-amplify/cli/lib/extenstions/amplify-helpers/resource-status.js` because the api isn't specifically mentioned in backend-config.json

```
lines 118-132: (crash on line 124)

for (let i = 0; i < resources.length; ++i) {
        if (resources[i].dependsOn && resources[i].dependsOn.length > 0) {
            for (let j = 0; j < resources[i].dependsOn.length; ++j) {
                const dependsOnCategory = resources[i].dependsOn[j].category;
                const dependsOnResourcename = resources[i].dependsOn[j].resourceName;
                if (amplifyMeta[dependsOnCategory] &&
                    (!amplifyMeta[dependsOnCategory][dependsOnResourcename].lastPushTimeStamp ||
                        !currentAmplifyMeta[dependsOnCategory] ||
                        !currentAmplifyMeta[dependsOnCategory][dependsOnResourcename]) &&
                    amplifyMeta[dependsOnCategory][dependsOnResourcename].serviceType !== 'imported') {
                    resources.push(amplifyMeta[dependsOnCategory][dependsOnResourcename]);
                }
            }
        }
    }
```

These references are not new and I have created plenty of environments before so I assume this is a change of behaviour recently.  I could potentially try adding a section to backend-config.json to see if it works but should I have to?  What happened recently to cause this?

**Amplify CLI Version**
4.41.2

**To Reproduce**
See above. 

**Expected behavior**
A new environment to be created without issues instead of crashing after creating the authroles and deployment buckets.

**Desktop (please complete the following information):**

- OS: Mac Catalina
- Node Version. v14.4.0

**Additional context**
This is an +1yr old project.  Is this because a feature has changed along the road and the backend-config.json not correctly migrated?

**Comment by jcbdev** [comment]
Seems I can fix this by adding the following to the backend-config.json.  I think this is meant to be there and somehow over the various upgrades of the cli this section must have been removed at some point

```
"myapp": {
            "service": "AppSync",
            "providerPlugin": "awscloudformation",
            "output": {
              "authConfig": {
                "additionalAuthenticationProviders": [
                  {
                    "authenticationType": "AWS_IAM"
                  }
                ],
                "defaultAuthentication": {
                  "authenticationType": "AMAZON_COGNITO_USER_POOLS",
                  "userPoolConfig": {
                    "userPoolId": "authmyapp"
                  }
                }
              }
            }
          },
```

Will close as I managed to resolve on my own

**Comment by jroeland1993** [comment]
Facing the same issue - can you reopen?
