### ISSUE TITLE
Cannot suppress "Do you want to update code for your updated GraphQL API" on amplify push

### ISSUE THREAD

**Issue by jcbdev** [aws-amplify/amplify-cli#6412]
**Describe the bug**
I have tried all the following combinations but I am always asked the question `Do you want to update code for your updated GraphQL API?` at the end of a push.

```
amplify push --yes
```

```
CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"typescript\",\
\"fileNamePattern\":\"packages/core/graphql/**/*.ts\",\
\"generatedFileName\":\"packages/core/API.ts\",\
\"generateDocs\":true\
}"

amplify push --codegen $CODEGEN --yes
```

```
amplify push --no-gql-override --yes
```

Any idea why i cannot get the push to occur without this prompt?

**Amplify CLI Version**
4.41.2

**To Reproduce**
Any type of push

**Expected behavior**
amplify push to complete with no walkthrough questions asked

**Desktop (please complete the following information):**

- OS: Mac catalina
- Node Version. 14.4.0

**Comment by nikhname** [comment]
@jcbdev is this a blocking issue for a headless workflow you are working on?

**Comment by jcbdev** [comment]
I am having it both in a CI headless push but we also get it locally if devs try to skip the prompts @nikhname

**Comment by cjihrig** [comment]
@jcbdev I am unable to reproduce this issue with the latest version of the CLI. Can you try upgrading to a newer version of the CLI and see if that fixes your issue. If upgrading does not resolve your issue, can you please provide more detailed steps to reproduce.
