### ISSUE TITLE
Access GraphQL API from Cognito Triggers

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6413]
We need to reference users (list them, edit them, etc) from our application. We are using a cognito post confirmation trigger to populate our Users table. If we attempt by granting our Trigger Function access to the API it creates a circular dependency. There doesn't appear to be a way to construct the DynamoDB Table Name since there seems to be a salt string added. 

What is the recommended approach for accessing tables generated by a GraphQL API from a Cognito Trigger? 

It would be nice if 
1. the cli prevented you from adding circular dependencies
2. the graphql api generated dynamodb table names that could be recreated with just the REGION and ENV, sans salt. So you could produce the script in your code without creating a cloudstack circular depedency.
3. the nosql storage generated by the graphQL api was an independent stack so you could take a dependency on it without creating a circular dependency.

**Comment by akshbhu** [comment]
Hi @dopry 

We are currently investigating for a solution to handle circular depedencies in a better way. Here is the similar issue where we are tracking circular dependencies. https://github.com/aws-amplify/amplify-cli/issues/4568

For the workaround Either you can try to push resources one at a time to break circular dependency among auth-> function->api or you can unblock yourself by using a custom resource in Cloudformation to unblock - #1874

Closing this issue in favour of #4568
