### ISSUE TITLE
Merge Query from multiple files when splitting up schema. 

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6415]
It would be nice to design schemas by Functionality. In my current app,  I  have calendars, users, blog schemas.   I'd like to put each in its own GraphQL file along with any related Mutations or Queries.  Currently, that causes the error 

```
There can be only one type named "Query".
There was an error pushing the API resource
Error: There can be only one type named "Query".
```

It would be nice if the cli merged all my queries and mutations and warned me or errored if there were duplicates so that all the graphql relative to a single domain is in one file for easy editing. 

This seems to work for mutations.

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.
