### ISSUE TITLE
Amplify CLI Fails to Create Lambda Trigger for DynamoDB Stream - Stream Not Found

### ISSUE THREAD

**Issue by chriskinzel** [aws-amplify/amplify-cli#6417]
**Describe the bug**
When running `amplify push` after creating a lambda trigger for a DynamoDB stream on a table in dynamo using the cli, I am getting the following error:

> CREATE_FAILED   LambdaEventSourceMappingFormSubmission
>
> Invalid request provided: Stream not found: arn:aws:dynamodb:us-east-1:<account-id>:table/FormSubmission-zq2mm2xzvnb5rezdfu2ealjmw4-dev/stream/2020-11-14T21:26:11.505 (Service: Lambda, Status Code: 400, Request ID: 67d3ec1d-1e36-4dc6-abcd-eb0c0603e2c1, Extended Request ID: null)

The stream ARN is incorrect, it is pointing to an old no longer existing stream. The correct ARN should be arn:aws:dynamodb:us-east-1:<account-id>:table/FormSubmission-zq2mm2xzvnb5rezdfu2ealjmw4-dev/stream/2021-01-18T02:14:09.870. If I manually set this stream ARN in the CloudFormation template for the lambda, it works, but this obviously won't work across different environments.

This issue popped up after I deleted a lambda trigger created with the cli in the AWS console manually. I then deleted the lambda using the amplify cli, reverted the codebase, and re-created a new lambda trigger on the same dynamo table. No matter what I do, `amplify push` always gives this error if I try to push a new DynamoDB trigger.

How can I fix the incorrect stream ARN amplify is referencing and update it to the correct one?

**Amplify CLI Version**
4.41.2

**Expected behavior**
Expect the Lambda to be created successfully after `amplify push` connected to DynamoDB stream.

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: v14.8.0

**Comment by ammarkarachi** [comment]
What has happened is that the LambdaEventSourceMapping is out of sync. You can delete the LambdaEventSourceMapping in the searchable stack and `amplify push --force` and then reintroduce it to associate the mapping again and force push again.
