### ISSUE TITLE
GraphQl @function generated request resolver invalid. 

### ISSUE THREAD

**Issue by btweedy2879** [aws-amplify/amplify-cli#6419]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

When using the GraphQL @function directive, the resolver code being generated is invalid and throws the following error on query: 
Unexpected character ('t' (code 116)): was expecting comma to separate Object entries

This is the request vtl code being generated: 
```
## [Start] Invoke AWS Lambda data source: KsiGetLegacyCustomerLambdaDataSource. **
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": "$ctx.stash.get("typeName")",
      "fieldName": "$ctx.stash.get("fieldName")",
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
## [End] Invoke AWS Lambda data source: KsiGetLegacyCustomerLambdaDataSource. **
```
The issue seems to be related to `"$ctx.stash.get("typeName")"`.  Manually changing the double quotes around typeName and fieldName to single quotes resolves the issue. 

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.41.2

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
Use the @function directive on any defined query.   

**Expected behavior**
A valid request mapping template is generated when using the @function directive.  Subsequent use of respective query succeeds without error. 

**Screenshots**

**Desktop (please complete the following information):**
macOs
- OS: [e.g. Mac/Windows/Ubuntu]
- Node Version. You can use `node -v` to check the node version on your system
12.16.1
**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`
```
{
  "data": {
    "getLegacyChildCustomers": null
  },
  "errors": [
    {
      "path": [
        "getLegacyChildCustomers"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unexpected character ('t' (code 116)): was expecting comma to separate Object entries\n at [Source: (String)\"{\n  \"version\": \"2018-05-29\",\n  \"operation\": \"Invoke\",\n  \"payload\": {\n      \"typeName\": \"$ctx.stash.get(\"typeName\")\",\n      \"fieldName\": \"$ctx.stash.get(\"fieldName\")\",\n      \"arguments\": {\"custid\":\"SCHTR\"},\n      \"identity\": {\"claims\":{\"sub\":\"0f0deaea-b240-4ae4-8368-b58b185a0c04\",\"cognito:groups\":[\"Customer\"],\"email_verified\":true,\"cognito:preferred_role\":\"arn:aws:iam::934875256114:role/us-east-1_SSyZoFrEK-CustomerGroupRole\",\"iss\":\"https://cognito-idp.us-east-1.amazonaws.com/us-east-1_SSyZoFrEK\",\"[truncated 3071 chars]; line: 5, column: 37]"
    }
  ]
}
```
**Additional context**

**Comment by nikhname** [comment]
@btweedy2879 could you provide your schema so that we can try reproducing this?

**Comment by etaylor23** [comment]
I also experience this issue. Here's extra detail on @btweedy2879  initial report

### Amplify CLI Version
You can use amplify -v to check the amplify cli version on your system
4.41.2

To Reproduce
Use the @function directive on any defined query.
Schema Chunk:
```
...
type Mutation {
...
  createSalarySet(
    input: CreateSalarySetInput!
    condition: ModelSalarySetConditionInput
  ): SalarySet @function(name: "storageTransformerRangeToMonthStaffCosts-${env}")
...
}
...
```

### Expected behaviour
- Amplify deploys correctly escaped template


### Further details

**Error:**
> Unexpected character ('t' (code 116)): was expecting comma to separate Object entries↵ at [Source: (String)"{↵  "ver

Amplify Generates the following:
```
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": "$ctx.stash.get("typeName")", <---- Error begins here
      "fieldName": "$ctx.stash.get("fieldName")",
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
```
Switching to
```
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload": {
      "typeName": $util.toJson($ctx.info.typeName),
      "fieldName": $util.toJson($ctx.info.fieldName),
      "arguments": $util.toJson($ctx.arguments),
      "identity": $util.toJson($ctx.identity),
      "source": $util.toJson($ctx.source),
      "request": $util.toJson($ctx.request),
      "prev": $util.toJson($ctx.prev)
  }
}
```
Fixes the issue, however - I'm now going to write deployment code to sub in this fix which is not ideal.

**Comment by btweedy2879** [comment]
@nikname here are the schema items related to this issue: 

`
type LegacyCustomer {
  custid: String!
  lastname: String
  firstname: String
  address1: String
  address2: String
  city: String
  state: String
  zip: String
  billrates1: String
  billrates2: String
  billrates3: String
  billrates4: String
  billrates5: String
  billratesC: String
  billratesS: String
  billratesB: String
  billratesZ: String
  billratesF: String
  billratesM: String
  billratesP: String
  billratesSS: String
  billratesDISC: String
  corngoal: String
  beangoal: String
  wheatgoal: String
  pulling: Boolean
  computermaps: Boolean
  gps: Boolean
  recs: Boolean
  grid: String
  phonenum: String
  faxnum: String
  teststorun1: String
  teststorun2: String
  teststorun3: String
  teststorun4: String
  teststorun5: String
  teststorun6: String
  teststorun7: String
  teststorun8: String
  teststorun9: String
  teststorun10: String
  modemfiles1: String
  modemfiles2: String
  modemfiles3: String
  email: String
  WebFiles: Boolean
  EmailFromWeb: Boolean
  EmailFromKSI: Boolean
  Contact: String
  Notes: String
  Password: String
  Delivery: String
  PPM: Boolean
  ExpWebSite: String
  UseCustPhbCalc: Boolean
  WebMaps: Boolean
  CSVHeaderYN: Boolean
  PaperLess: Boolean
  EmailStatus: Boolean
  LocID: String
}
type Query @aws_iam @aws_api_key @aws_cognito_user_pools { 
     getLegacyChildCustomers(custid: String!):[LegacyCustomer] @function(name: "ksiGetLegacyChildCustomers-${env}")
  }
`
Let me know if you need more than that.

**Comment by nikname** [comment]
Wrong "nikname" 😬 😂

**Comment by btweedy2879** [comment]
> Wrong "nikname" 😬 😂

@nikname my apologies.   @nikhname, please see my comment above with schema.

**Comment by josefaidt** [comment]
Hey @btweedy2879 @etaylor23 :wave: are yall still experiencing this issue? I am seeing the following lines get created, however they are not reproducing this issue when querying. 

```
"typeName": "$ctx.stash.get("typeName")",
"fieldName": "$ctx.stash.get("fieldName")",
```

Much like you have already noted the following replacements will also work:

```
"typeName": "$ctx.stash.get('typeName')",  ## single quoted field
"typeName": $util.toJson($ctx.stash.get("typeName")),  ## using toJson to get the value
```

It appears to parse the values fine now, but we were able to force a similar error message (shown below) by intentionally adding a backslash to the get method's argument `"$ctx.stash.get("\typeName")"`.

```
Unexpected character ('\\' (code 92)): was expecting comma to separate Object entries\n at [Source: (String)\"{\n  \"version\": \"2018-05-29\",\n  \"operation\": \"Invoke\",\n  \"payload\": {\n  \t  \"typeName\": \"$ctx.stash.get(\"\\typeName\")\",
...
```
