### ISSUE TITLE
aws-exports.js appears to be awsmobile format

### ISSUE THREAD

**Issue by eoliphan** [aws-amplify/amplify-cli#642]
I'm not sure if this is a bug or not.  In short, just created a new project with the 0.1.38 version of the CLI, and added auth support, but when I do any auth related stuff, after having called configure, (via the React UI components, or the JS API), i get an error about User Pools not being found.  In looking at the `aws-exports.js` I noticed that the format doesn't appear to match what you see in the docs for manual config where there's a per feature block: `{ Auth: {...} }` instead mine looks like this:

```
const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-xxx",
    "aws_user_pools_web_client_id": "xxx"
};


export default awsmobile;
```

not sure if this is my problem or there's something else going on.

**Comment by jkeys-ecg-nmsu** [comment]
Don't think this is a problem. This is probably an attempt to future-proof the CLI so that it can be integrated with AWS Mobile. FWIW, I took the aws-exports.js JSON, converted it to an object, and this works:

```

const awsmobile =  {
    aws_project_region: "us-east-1",
    aws_cognito_identity_pool_id: "us-east-1:ed9asdfasdf",
    aws_cognito_region: "us-east-1",
    aws_user_pools_id: "us-east-1_aASDFASDF",
    aws_user_pools_web_client_id: "aSDFASDFa12312awsdf",
    aws_content_delivery_bucket: "asdf",
    aws_content_delivery_bucket_region: "us-east-1",
    aws_content_delivery_url: "https://asdf.cloudfront.net",
    aws_appsync_graphqlEndpoint: "asdf",
    aws_appsync_region: "us-east-1",
    aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
    // aws_mobile_analytics_app_id: "13e3d2101basdf",
    // aws_mobile_analytics_app_region: "us-east-1"
};

[...]

  Amplify.configure({
      ...awsmobile,
      XR:{
        SumerianProvider: { // Sumerian specific configuration
          region: 'us-east-1', // Sumerian region 
          scenes: scenes
        }      
       }//end XR
   }); //end Amplify.configure()
```

**Comment by eoliphan** [comment]
ugh it was actually a problem on my end.  I'm using CLJS and pulled it in as an alias as opposed to a default

**Comment by eoliphan** [comment]
ugh it was actually a problem on my end.  I'm using CLJS and pulled it in as an alias as opposed to a default
