### ISSUE TITLE
Unhelpful Error Message: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6420]
$ amplify push
✔ Successfully pulled backend environment dopry from the cloud.
Current Environment: dopry
| Category | Resource name                     | Operation | Provider plugin   |
| -------- | --------------------------------- | --------- | ----------------- |
.....
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

Cannot read property 'length' of undefined
An error occurred during the push operation: Cannot read property 'length' of undefined

What does this error mean?  After trying all the sub-commands amplify push function shows me 
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\push-resources.ts:802:57
    at Array.forEach (<anonymous>)
    at C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\push-resources.ts:786:15
    at Array.forEach (<anonymous>)
    at formNestedStack (C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\push-resources.ts:783:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\push-resources.ts:216:29)
    at async Promise.all (index 0)
    at providersPush (C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\push-resources.ts:90:3)
    at AmplifyToolkit.pushResources [as _pushResources] (C:\Users\dopry\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\push-resources.ts:66:7)
```

What length of what exactly? Which function resource has a problem? This error message is not helpful. 

Processing each template and component should be wrapped in a try/catch and you should let developers know what is failing.

**Comment by ammarkarachi** [comment]
@dopry which version, os and node version are you using?

**Comment by dopry** [comment]
not like it makes a difference since you can go straight to https://github.com/aws-amplify/amplify-cli/blob/b5f917a81524feb64ec7e674c6213cb47fd7794c/packages/amplify-provider-awscloudformation/src/push-resources.ts#L800 and see the code accessing .length on the potentially empty attributes array.  lazy

but node 14/LTS and amplify 4.41.2

**Comment by edwardfoyle** [comment]
@dopry Did you manually edit any of the dependency attributes in your `amplify-meta.json` file? We can add a check for an undefined attributes list but the CLI should never produce a dependency with undefined attributes in the `amplify-meta.json` file. If there was a CLI flow that resulted in the corrupt `amplify-meta.json` file please follow up with repro steps. If you manually edited the file, you'll likely need to make sure that you specified the attributes correctly.

**Comment by kaustavghosh06** [comment]
Closing this issue as the fix was released for this.

**Comment by Niretech** [comment]
I've just installed @aws-amplify/cli@4.50.0 and i'm getting this issue now. I haven't changed the API since my last push so I know it was working - now when I push after the install it tells me there's a change in the API and throws the above error.

**Comment by cjihrig** [comment]
@Niretech the issue you're seeing is being worked on in https://github.com/aws-amplify/amplify-cli/issues/7190.
