### ISSUE TITLE
Amplify Publish deleted my dev DynamoDB and misconfigured mi localhost

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-cli#6425]
**Describe the bug**
Amplify publish delete my dev env and instead of create the "production" env on DynamoDB with the format `tableName-${hash}-develop` .

**Amplify CLI Version**
4.41.0

**To Reproduce**
I create my infrastructure with the CLI (auth, storage, api graphql) and mock the API meanwhile I finishing the models after that I push my changes to develop env, so I tested and it's working fine but when I publish my changes so the command basically delete my tables created and re-create new ones in order to use into production env. As you know the tables has a hash with a format `tableName-${hash}-${env}` well that hash was modified to be used in production and my local still has the old one (config) and when I try to run in localhost that Env or config is not found. Now I don't know how I can restore or recovery my env to continue working on that without delete my production env.

**Expected behavior**
I'll hope that command should deploy the new one env and keep the dev tables.

**Desktop (please complete the following information):**
- OS: Mac Catalina v10.15.7
- Node Version. v14.15.1
- Vue: 2.6.11

**Comment by kaustavghosh06** [comment]
@djom202 Sorry to hear that the models were deleted. Did you run ampliy env checkout -> publish? Curious to know the exact steps to reproduce this.

**Comment by djom202** [comment]
@kaustavghosh06 Yes I did `publish` command, but I never used `env checkout`.

**Comment by kaustavghosh06** [comment]
@djom202 We're not able to reproduce this issue. Did you by any chance rename your model names? That usually results in deletion of your old model (with a different name) in DDB.

**Comment by djom202** [comment]
@kaustavghosh06 I don't change the table names because I had finalized all the changes I needed to make, I just tried to publish my changes to production, even in production I have the tables with the same names but just develop env was deleted.

**Comment by kaustavghosh06** [comment]
@djom202 We unfortunately couldn' replicate this issue and neither had any other customers report this. Were you able to reproduce this issue?

**Comment by GeorgeBellTMH** [comment]
#5972 would have been helpful...
