### ISSUE TITLE
Running amplify init to create a new environment doesn't update your local environment settings

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6432]
**Describe the bug**

Using an existing app I created a new environment using ``amplify init`` as described in https://docs.amplify.aws/cli/teams/overview

However although this created a new environment and I pushed it. When running my App locally my API's are still pointing at the old environment. To reset it I then had to do a ``amplify pull`` which changed the files to use the correct environment rather than the previous one.

**Amplify CLI Version**

v4.41.2

**To Reproduce**

Assuming an existing app that is already in the cloud:

* run ``amplify init`` and within the steps for that:
** Don't base it on an existing environment
** Give it a name
** Select the existing environment as the source to copy from
* run ``amplify push``
* Run your app in the browser
* Check the contents of awsexports.js and note that all the endpoints for your API's are still pointing to the old one.

**Expected behavior**

After creating a new environment and pushing it I would expect it to update my current environment to match it.

I guess this is like git's "create a new branch" command which annoyingly then never actually checks out that new branch?

This might be by design but it lost me about 50 minutes of head scratching today, could cost someone else coming be hind us a lot more, lets make it simpler.

- OS: Windows

**Comment by rajrajhans** [comment]
> I guess this is like git's "create a new branch" command which annoyingly then never actually checks out that new branch?. This might be by design 

Once you create a new environment and run `amplify env list` it will show you that current environment is actually the new one you just created, so it's definitely a bug wherein the `aws-exports.js` file is not getting updated with the new environment's endpoints and keys.

**Comment by giulioambrogi** [comment]
Hello is there any temporary workaround while we wait for the fix?

**Comment by DylanBruzenak** [comment]
This is still occurring in 2022.

**Comment by raffclar** [comment]
Confirmed still happening

**Comment by edwardfoyle** [comment]
Are you observing this behavior if you run `amplify env add` instead of `amplify init`? `amplify init` should only be used when a project has not been initialized locally. After that, `amplify env add` should be used to create new environments. That being said, we can add some additional safeguards around this flow

**Comment by brandonfonseca** [comment]
This is happening to me as well, however, running an `amplify env checkout {new_env_name}` as suggested above, still does not fix the issue. The `aws-exports.js` is still not being updated.

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: this now appears to be fixed with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.6.20). Closing issue 🙂

**Comment by aaronjwhipple87** [comment]
This is still occurring 
cli version: 9.1.0

**Comment by GauthierWillemse** [comment]
Sill having the same issue. Someone found a fix?
