### ISSUE TITLE
"Failed to fetch Amplify Admin credentials init failed" on new project

### ISSUE THREAD

**Issue by mikelhamer** [aws-amplify/amplify-cli#6437]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Running amplify init on a new local Ionic project that does not exist in the Amplify console results in the error "Failed to fetch Amplify Admin credentials init failed"

**Amplify CLI Version**
4.41.2

**To Reproduce**
```
npm install -g @aws-amplify/cli@latest
amplify configure (with correct access key and us-east-2)
cd path/to/new/project
amplify init
```

**Expected behavior**
The command completes with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/10012080/105127432-e2c06100-5aae-11eb-94db-85d80d63f76e.png)

**Desktop (please complete the following information):**

- OS: Windows

- Node Version: v14.15.3

**Log output**

> 2021-01-20T04:01:36.191Z|info : amplify configure core  
> 2021-01-20T04:02:21.700Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.credetialsFilePathExists(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:02:21.702Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:02:21.703Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.credetialsFilePathExists(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:02:21.704Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["C:\\Users\\username\\.aws\\config"])
> 2021-01-20T04:02:21.704Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.writecredetialsFilePath(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:02:33.583Z|info : amplify version core  {"version":true,"yes":false}
> 2021-01-20T04:02:41.462Z|info : amplify init core  
> 2021-01-20T04:05:23.406Z|info : amplify configure core  
> 2021-01-20T04:06:26.668Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.credetialsFilePathExists(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:06:26.669Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:06:26.670Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.credetialsFilePathExists(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:06:26.670Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["C:\\Users\\username\\.aws\\config"])
> 2021-01-20T04:06:26.671Z|info : amplify-provider-awscloudformation.system-config-manager.setProfile.writecredetialsFilePath(["C:\\Users\\username\\.aws\\credentials"])
> 2021-01-20T04:06:33.492Z|info : amplify init core  
> 2021-01-20T04:09:34.827Z|info : amplify console core  
> 2021-01-20T04:12:30.902Z|info : amplify help core  
> 2021-01-20T04:12:37.405Z|info : amplify env core  
> 2021-01-20T04:13:09.423Z|info : amplify help core  
> 2021-01-20T04:13:24.380Z|info : amplify delete core  
> 2021-01-20T04:17:36.440Z|info : amplify help core  
> 2021-01-20T04:18:16.917Z|info : amplify configure core  
> 2021-01-20T04:19:31.799Z|info : amplify init core  
> 2021-01-20T04:20:48.286Z|info : amplify version core  {"version":true,"yes":false}

**Additional context**

**Comment by nikhname** [comment]
May be fixed by https://github.com/aws-amplify/amplify-cli/pull/6433

**Comment by jhockett** [comment]
@mikelhamer are you using an existing `team-provider-info.json` file?

**Comment by mikelhamer** [comment]
@jhockett No I don't believe so (this was a brand new project that didn't have any aws info). I completely uninstalled node, aws and amplify cli, deleted cached node modules and aws cli and amplify cli config from my machine, and started from scratch. This fixed the issue for me.

**Comment by jhockett** [comment]
Glad to hear you were able to fix it @mikelhamer! If it comes up again, please comment below and we will investigate. 

Closing this issue.

**Comment by rocketmaniac** [comment]
I also ran into this issue on a new project using:

Amplify CLI Version
4.41.2

Desktop (please complete the following information):

OS: macOS Mojave 10.14.6
Node Version: v12.9.0

Unfortunately, I did not have the luxury of reinstalling everything as I did not want to break existing apps.  Per a suggestion by AWS support, I pulled the code into a fresh Cloud9 instance and 'amplify'ed' it there.  I then pulled the new amplify'ed version to my local and amplify seems happy now, and it didn't affect my existing apps as I didn't have to reinstall everything.

Hopefully, the linked PR will resolve this issue moving forward.
