### ISSUE TITLE
Amplify status gets stuck in invalid state after unsuccessful codegen

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#644]
**Describe and reproduction**
- Have a schema with codegen enabled.  
- `amplify status` shows "No Change" for your graphql API category.
- Have some custom queries or mutations that you've written, that are also in the `graphql` folder and available to have types generated for them.  
- Change your schema so some of the queries would result in a type generation error once they have codegen ran against them.
- Run `amplify push` to push the schema changes and generate the types.  
- The type generation will fail once all the cloudformation changes have been completed.
- Run `amplify status` and see that the API still is set at "Update" - presumably this is because the `amplify push` command never actually finished (even though all the remote cloudformation changes were completed successfully - the error during type generation short-circuited this)
- **From this point forward** any changes made to the schema or anything else won't affect this status - it appears to be "stuck" in "Update" status.

**Expected behavior**
After a successful `push` the status should be set back to "No Change"

$ amplify -v
0.2.1-multienv.19

**Comment by kaustavghosh06** [comment]
@mwarger We provided a fix for this as a part of the latest version of the main CLI. Please let me know if you're still seeing the issue.
