### ISSUE TITLE
Bug with Field Level Authorisation on Amplify API

### ISSUE THREAD

**Issue by chrisyeung1121** [aws-amplify/amplify-cli#6441]
**Describe the bug**
Amplify does not produce correct behaviour on field level authorisation, after finding help on discord, I found out that the behaviour of `amplify add api` is not deterministic and is affected by the order of adding **congito user pool** and **API Key**. 

**Amplify CLI Version**
4.41.1

**To Reproduce**
1. `amplify add api` -> choose`cognito user pool` as default auth type -> choose `API key` as additional auth type.
2. In `graphql.schema`, add the following SDL

``` graphql
type Todo
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"] }
    ]
  ) {
  id: ID!
  name: String!
  description: String
  secret: String @auth(rules: [{ allow: groups, groups: ["admin"] }])
}
```

3. Run `amplify api gql-compile`, and inspect the graphql.schema in `build` folder

```
type Todo @aws_api_key @aws_cognito_user_pools {
  id: ID!
  name: String!
  description: String
  secret: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

**Expected behavior**
I expect the following SDL in `type Todo`, which I obtained correctly if I switch of order of default auth type to API key

```graphql
type Todo @aws_cognito_user_pools @aws_api_key {
  id: ID!
  name: String!
  description: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  secret: String @aws_cognito_user_pools
}
```

- OS: Mac
- Node Version: 12.18.3

**Comment by SwaySway** [comment]
Hello @chrisyeung1121 the behavior you are looking for here is deny-by-default this is something we are tracking as a part of the `@auth` Enhancement RFC here: https://github.com/aws-amplify/amplify-cli/issues/1043

We are looking at adding these enhancements in the next version of the transformer here: https://github.com/aws-amplify/amplify-cli/issues/6217

Closing this issue in favor the of the `@auth` and GQL Transformer vNext RFC.
