### ISSUE TITLE
Tags not applied to API  Gateway REST resource

### ISSUE THREAD

**Issue by FredrikMeyer** [aws-amplify/amplify-cli#6449]
**Describe the bug**

Editing the `tags.json` does not apply tags tags to API Gateway. Discovered by drift detection in AWS Cloudformation.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Edit the tags.json file, and create a REST API.

**Expected behavior**
I expect all resources to get tagged.

**Screenshots**
Diff in drift detection:
![image](https://user-images.githubusercontent.com/1738405/105325067-7a67a180-5bcc-11eb-9c58-fa7d1fc4aca2.png)

**Desktop (please complete the following information):**

- OS: Mac
- Node Version. v14.8.0

**Additional context**

This happen also during the build when I push to my Github branch.

**Comment by josefaidt** [comment]
Hey @FredrikMeyer this now appears to be fixed and tags persist across pushes 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/5033303/169555664-d115e5d3-6a1e-4e3c-b554-a8ab4a11f7a5.png">

Closing issue 🙂 if you are still experiencing this please reply back to this thread and we can re-open to investigate further 🙂
