### ISSUE TITLE
How to generate many-to-many queries and interfaces?

### ISSUE THREAD

**Issue by boxcee** [aws-amplify/amplify-cli#6451]
**Which Category is your question related to?**
Amplify GraphQL API Documentation & Usage

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
GraphQL API

**Provide additional details e.g. code snippets**
Two things:
1. The generated queries do not support many-to-many querying. I believe the documentation is not clear enough what needs to be done to fill that 'gap' of the missing generated code.
2. If a developer proceeds to adjust the query and is working with TypeScript, it seems to create some problems with mixing the generated code with the adjustment due to the lack of some interfaces.

Documentation in question: https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections

Model:
```
type Context @model {
  id: ID!
  name: String!
  enterprise: Enterprise @connection(name: "Contexts")
  resultItems: [ContextResultItem] @connection(keyName: "byContext", fields: ["id"])
  users: [ContextUser] @connection(keyName: "byContext", fields: ["id"])
}

type ContextUser
@model(queries: null)
@key(name: "byContext", fields: ["contextID", "userID"])
@key(name: "byUser", fields: ["userID", "contextID"]) {
  id: ID!
  contextID: ID!
  userID: ID!
  context: Context! @connection(fields: ["contextID"])
  user: User! @connection(fields: ["userID"])
}

type User @model {
  id: ID!
  username: String!
  contexts: [ContextUser] @connection(keyName: "byUser", fields: ["id"])
  tokens: [Token] @connection(name: "Tokens")
}
```
Generated query to list `User`:
```
export const listUsers = /* GraphQL */ `
  query ListUsers(
    $filter: ModelUserFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listUsers(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        username
        contexts {
          nextToken
        }
        tokens {
          nextToken
        }
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
```
The query above should also include:
```
contexts {
  items {
    context {
      id
      name
    }
  }
  nextToken
}
```
Now, after making changes to the query but using the generated interface, it shows the property `items` as non existent, since it is also missing in the generation it seems.

**Comment by akshbhu** [comment]
Hi @boxcee 

When you configured codegen , you are promped with this question :
Enter maximum statement depth [increase from default if your schema is deeply nested]

You can statement depth > 2 so that it can generate nexted items. This is skipped in your case as nested depth is set as 2.

What you can do is :

run amplify configure codegen
Configure above question for a depth > 2
run amplify codegen again to generate code.
let me know if this works for you?

**Comment by boxcee** [comment]
It does. Really my bad, sorry.
