### ISSUE TITLE
Using an existing AppSync GraphQL API is a problem in the CD process

### ISSUE THREAD

**Issue by landworth** [aws-amplify/amplify-cli#6457]
When I try to push an existing API to an Amplify backend, it does not integrate properly in the CD process.

**Amplify CLI Version**
4.41.2

**To Reproduce**
When I first add the existing AppSync to the Amplify backend environment (with the command `amplify add codegen --apiId <app-id>`) it all seems ok and after a push, I see all 3 categories appearing within the Amplify Console.
![image](https://user-images.githubusercontent.com/32584900/105447797-cf5af480-5c6c-11eb-9efa-a26501e68470.png)

Then I push a new branch to github, connect the branch in Frontend environments and it starts to build. All is fine and it deploys and loads correctly, however the app doesn't even attempt to load the AWS GQL endpoint so no data is displayed.

When I now go back to the Amplify Console "API" is no longer listed against the backend categories for my environment.
![image](https://user-images.githubusercontent.com/32584900/105447908-1a750780-5c6d-11eb-94fb-5cc2b6934790.png)

**Expected behavior**
When Amplify builds a branch linked to a backend with a custom AppSync API, it should pull in the appropriate aws_appsync parameters (endpoint/keys/etc) to ensure the build works correctly.

**Additional context**
Adding the aws-exports.js file to the repo mitigates the problem when using only one GraphQL endpoint, but multiple dev/staging/prod API endpoints becomes tricky. It would be far better if the Amplify backend would hold onto the imported AppSync details and share them as needed in the CD process.

**Setup**
- I have a React/Amplify project which controls auth and analytics categories.
- I connect this to an existing AppSync backend using the command "amplify add codegen --apiId xxxxxxxxxxx".
- Works fine when running it locally (probably since aws-exports.js is present)

**Comment by yuth** [comment]
@landworth 
> When I first add the existing AppSync to the Amplify env it all seems ok and after a push

What do you mean by this. Do you add the AppSync API using `amplify add codegen --apiId <app-id>`?

**Comment by landworth** [comment]
> @landworth
> 
> > When I first add the existing AppSync to the Amplify env it all seems ok and after a push
> 
> What do you mean by this. Do you add the AppSync API using `amplify add codegen --apiId <app-id>`?

Hi @yuth thanks for your reply.

Yes, exactly I add the AppSync API to Amplify with the command `amplify add codegen --apiId <app-id>` - I will update my question with that to clarify.

**Comment by ammarkarachi** [comment]
@landworth from the documentation https://docs.amplify.aws/cli/graphql-transformer/codegen#statement-depth, 


>If you use the –apiId flag to add an externally created AppSync API, such as one created in the AWS console, you will not be able to manage this API from the Amplify CLI with commands such as amplify api update when performing schema updates. You cannot add an external AppSync API when outside of an initialized project.


You would have run the `amplify add codegen --apiId <app-id>` on every new environment created.

**Comment by kaustavghosh06** [comment]
Closing as the question seems to be answered. Please let us know if you've further questions.
