### ISSUE TITLE
[push] - as admin user but get 403

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#6458]
Resource Name: aivy-rn-elasti-glz29xwkqdo4 (AWS::Elasticsearch::Domain)
Event Type: update
Reason: User: arn:aws:sts::327300291***:assumed-role/eu-central-1_bKDi3JIN3_Full-access/amplifyadmin is not authorized to perform: es:AddTags on resource: arn:aws:es:eu-central-1:327300291***:domain/aivy-rn-elasti-glz29xwkqdo4 (Service: AWSElasticsearch; Status Code: 403; Error Code: AccessDeniedException; Request ID: 3f3e192c-3dcc-4641-95ce-fc97397eddd3; Proxy: null)

**Comment by davidbiller** [comment]
any news here?

**Comment by ammarkarachi** [comment]
@davidbiller  Were there any changes in the Searchable Lambda before pushing?

**Comment by davidbiller** [comment]
No, no changes since on year @ammarkarachi

**Comment by davidbiller** [comment]
I tried now to update a model in api too, just for testing: 
it seems that my role is completly broken?!

![Bildschirmfoto 2021-01-26 um 10 48 19](https://user-images.githubusercontent.com/7137361/105828994-183fdf80-5fc4-11eb-97c8-f4cdd17f48f5.png)

**Comment by davidbiller** [comment]
Okay I added the rights now, and it works. 
eu-central-1_bKDi3JIN3_Full-access was not updated from the cli with the correct rights.

**Comment by ammarkarachi** [comment]
Thanks for getting back to me on this, let me know if you experience any other issues
