### ISSUE TITLE
Amplify mock function does not print console.error to terminal

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#6461]
**Describe the bug**
When I use console.error in node function in amplify it doesn't write console.error to the terminal (fish).

**Amplify CLI Version**
4.41.0

**To Reproduce**
- run amplify add function, follow a regular flow
- add a console.error('this is an error') to the new function just created
- run `amplify mock function funcName`

**Expected behavior**
- see console errors

**Desktop (please complete the following information):**

- OS: Mac
- Node: v12.13.0

**Additional context**
We'd like to sort on errors in cloud watch so not using console.error is an issue

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version to try it out.
