### ISSUE TITLE
amplify-appsync-simulator giving error in OpenIdConfig Issuer trailing '/'

### ISSUE THREAD

**Issue by sarfraaz-talat** [aws-amplify/amplify-cli#6463]
Getting the error when trying to connect through OpenIdConfig when my Issuer has trailing '/'

`{"errors":[{"errorType":"UnauthorizedException","message":"UnauthorizedException: Invalid JWT token"}]}`

Digging into the code,just found out isValidOIDCToken function inside helpers is stripping the trailing '/' from the issuer & then matching it against token.iss

Same config with trailing '/' works just fine with my production AppSync deployment on aws

**Comment by yuth** [comment]
@sarfraaz-talat Thanks for reporting this. This issue has been fixed in https://github.com/aws-amplify/amplify-cli/pull/6364. The change should be included in a release after 4.41.2.
