### ISSUE TITLE
Please make it easy to sort a list query

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-cli#6465]
It seems that to sort a list query I'd have to use ElasticSearch, and create custom resolvers.
This seems convoluted and time consuming when all I'd like to do is to run the default "list" query on a `@model` but tell it to sort the result according to a given field of the `@model`.

I'm aware also of the solution of using `@key` but I don't want to have to pass something to filter out by; I'd just like to get all the items sorted according to a field of my `@model`

I think that making this easier would greatly improve productivity for many people!

**Comment by ammarkarachi** [comment]
@cosimtaiuz we are tracking this as an enhancement in issue #4714.
