### ISSUE TITLE
How to manage multiple amplify projects with multiple company accounts on the same machine

### ISSUE THREAD

**Issue by BlakeWu** [aws-amplify/amplify-cli#6466]
**Which Category is your question related to?**
Hosting

**Amplify CLI Version** 
4.41.1

**What AWS Services are you utilizing?**
S3, cloudfront, route 53, and etc

**Provide additional details e.g. code snippets**
I saw the use case, "host an Amplify app in multiple AWS accounts" in https://github.com/aws-amplify/amplify-cli/issues/2127.  
But those multiple AWS accounts are under the same company. My question is different from that. 
How can I manage multiple amplify projects with multiple "different" company accounts on the same machine? 
Thanks.

**Comment by ammarkarachi** [comment]
@BlakeWu The CLI uses the profile to setup/modify an environment if you have the profiles setup per environment the CLI it should work out of the box.

**Comment by BlakeWu** [comment]
> @BlakeWu The CLI uses the profile to setup/modify an environment if you have the profiles setup per environment the CLI it should work out of the box.

Yeah. I know that. Just like #2127. Just not sure if it can work for different corporation accounts. If you say so, I will try it. Thanks!

**Comment by jhockett** [comment]
Closing this issue. If you have any more questions, let us know and we can re-open
