### ISSUE TITLE
AWS Amplify GraphQL Query Filter data based on relational model field

### ISSUE THREAD

**Issue by rigalpatel001** [aws-amplify/amplify-cli#6467]
**AWS Amplify GraphQL Query Filter data based on relational model field**

I create Post and rating model and I want to list all posts but exclude posts for which login user already give ratings.

I created below models
```gql
type Post @model @key(name: "postsByUserId", fields: ["authorId"]) {
  id: ID!
  authorId: ID!
  content: String!
  postImage: String
  author: User @connection(fields: ["authorId"])
  rating: [Rating] @connection(keyName: "ratingByUserId", fields: ["authorId"])
}

type Rating
@model
@key(name: "ratingByPostId", fields: ["postId"])
@key(name: "ratingByUserId", fields: ["userId"]) {
  id: ID!
  postId: ID!
  userId: ID!
  rating: String!
  user: User @connection(fields: ["userId"])
  post: Post @connection(fields: ["postId"])
}
```
I tried the above query but it's not working
```gql
query MyQuery {
  listPosts(filter: {not: {userId: {ne: "2234566666"}}}) {
    items {
      content
      rating {
        items {
          userId
        }
      }
    }
  }
}
```

I appreciate it if someone can help me with this.

**Comment by davidbiller** [comment]
A side question: 
When we use filter like this, than its possible to get some empty arrays as result with a nextToken right? 
So if its a bad day, it could be that we have to scan the complete table to get the data.

**Comment by ammarkarachi** [comment]
@rigalpatel001 wouldn't the query be 
```gql
query MyQuery {
  listPosts(filter: {authorId: {ne: "2234566666"}}) {
    items {
      content
      rating {
        items {
          userId
        }
      }
    }
  }
}
```

Since you are filtering on Post

**Comment by ammarkarachi** [comment]
@davidbiller I am not sure let me find out

**Comment by ammarkarachi** [comment]
@davidbiller A single `Scan` reads the max items set by the limit parameter or 1 MB data and then applies the filtering to formulate result. So yes it would do subsequent scans.

**Comment by rigalpatel001** [comment]
Hello @ammarkarachi 

all posts have author Id and multiple users can add ratings. I want to filter posts but based on rating users. there are two different user users can create a post and another level of users can add ratings to the posts.

IE ABC user login and he can view only pending rating post (exclude post which user already add ratings.)

query MyQuery {
  listPosts(filter: {authorId: {ne: "2234566666"}}) {
    items {
      content
      rating {
        items {
          userId
        }
      }
    }
  }
}

This is wrong because it filters post based on author id

Thanks

**Comment by ammarkarachi** [comment]
> all posts have author Id and multiple users can add ratings. I want to filter posts but based on rating users. there are two different user users can create a post and another level of users can add ratings to the posts.

IE ABC user login and he can view only pending rating post (exclude post which user already add ratings.)

from what I understand you want posts only when there are not rating by the user, is that correct?

**Comment by rigalpatel001** [comment]
@ammarkarachi 

 when there are not rating by the **login user**, is that correct?
 Yes, correct.
 
 
 So there are two types of user 
 1. end-user (who create new posts )
 2. teacher (who adds ratings to post )
 
 When the teacher login he can view all posts and add ratings but exclude posts in which the teacher already added a rating.

**Comment by ammarkarachi** [comment]
@rigalpatel001 There are two approaches to doing this

1. Write a [customer resolver](https://docs.amplify.aws/cli/graphql-transformer/resolvers#custom-resolvers)
2. You could also write a simple lambda function that invokes the query and filters based on the criteria you want

Let me know if this helps
