### ISSUE TITLE
How do I debug the project in Visual Studio Code?

### ISSUE THREAD

**Issue by chrisl777** [aws-amplify/amplify-cli#647]
I'd like to be able to contribute to the project. In order to do that efficiently, I'd like to run the Amplify CLI in Visual Studio Code and debug the code by setting breakpoints. How does one do that? 

At first, I just forked/cloned to build the project and do a basic run of the project from source. I tried to start with the suggested steps to build the project from the [Contributing ](https://github.com/aws-amplify/amplify-cli#contributing) section of the README. However, these steps fail (see attached errors): 
```
$ npm run setup-dev
yarn config set workspaces-experimental true
``` 
[Amplify CLI npm run setup-dev errors.txt](https://github.com/aws-amplify/amplify-cli/files/2719530/Amplify.CLI.npm.run.setup-dev.errors.txt)

I noticed that there is this note in the [GraphQL transformer docs](https://github.com/aws-amplify/amplify-cli/blob/63e682c7a5bb4a03298d1c5852beb78af0473b9c/packages/graphql-transformer-core/Readme.md): "there are some debug configurations defined in .vscode/launch.json you can use Visual Studio code to add debug breakpoints to debug the code." However, there is no launch.json file as noted. 

At a bare minimum, it would be good to be able to build and run the project from source. And ideally, if there were a launch.json file to run in Visual Studio Code, that would be even better. How does the Amplify team debug the project? (It would be tough to imagine one could not debug the code and set breakpoints.)

**Comment by kaustavghosh06** [comment]
@chrisl777 Can you please pull in the latest code form master/multienv branch (whichever one you're working on) and you won't see the above errors during the build step.

**Comment by kstro21** [comment]
Hi @chrisl777, were you able to debug the project? I would like to contribute too and I have the same question.

**Comment by haverchuck** [comment]
@chrisl777 @kstro21 

If you want to debug in vs code, you can add the following configuration to your launch.json:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "type": "node",
      "request": "launch",
      "name": "types gen simple type",
      "program": "${workspaceFolder}/packages/amplify-cli/bin/amplify", // path to your instance of the CLI, after you've run the npm run setup-dev command
      "cwd": "/absolute/path/to/amplify/project",
      "args": [
        // the cli commands that you will be testing, below is an example for 'amplify auth add;
        "auth",
        "add"
      ],
      "console": "integratedTerminal", 
    },
  ]
}
```

**Comment by kstro21** [comment]
@haverchuck it works, thanks!
