### ISSUE TITLE
keyName / Resolver conflict

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#6472]
**Describe the bug**

In order to get DataStore to sync I had to change all of my connections from "@connection (name" to "@connection (keyName", but when compiling (amplify api gql-compile --minify) it throws an error if you do not have id as a mandatory field. So in the following connection statement, if I have "id:ID" it throws an error, but if I have "id:ID!" it does not.
```
  M2MConnection: [M2MConnection] @connection (keyName: "byM2MConnectionDocumentId", fields: ["id"])
```

Now here is where a problem arises. When creating a record we never provide an ID, we rely on the resolver to generate the ID as per the statement from the resolver below.
```
$util.qr($context.args.input.put("id", $util.defaultIfNull($ctx.args.input.id, $util.autoId())))
```

So what this means is that if you use a mutation and you don't provide an ID then the mutation fails.

There is a work around to this - get into the "input CreateModelInput" and remove the ! from the ID there - but this is a painful process when you have a lot of models.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Defined above

**Expected behavior**
The gql-compile does not throw an error if the value is nullable - maybe a warning, but not an error

**Comment by ammarkarachi** [comment]
@sacrampton We have merged a PR addressing the issue. Please take a look and let me know if this fits your use case.https://github.com/aws-amplify/amplify-cli/pull/5153

**Comment by sacrampton** [comment]
@ammarkarachi - I believe the core of my issue was allowing nullable fields so this should address it

**Comment by ammarkarachi** [comment]
Cool! I will close this issue. The change should be available in the next release.
