### ISSUE TITLE
Subscription returns null for deep elements. (And with mock it works perfectly) amplify graphql

### ISSUE THREAD

**Issue by vincent38wargnier** [aws-amplify/amplify-cli#6478]
Hi everyone, 
I'm currently using subscriptions to update the state of my "manager" in order to spread the update through useContext.

The problem I encountered is that when I enter in the subscription, I update my manager data with the subscription response. But I had issues because the response was incomplete. Some attributes were returned as null even if they existed.

I don't have the issue when I use the mock. That's why i'm suruprised. I thought maybe it's due to aync stuff, but I don't get how the subscription can return data if it didn't retrieve all the data I asked for.

Anyway, here is some of my code :
My graphql schema table :
```gql
type Manager @model 
  @auth(rules: [
    {allow: owner}, 
    {allow: groups, groups: ["Admin"]}
    {allow: public, operations: [read], provider: apiKey}
    ])
{
  id: ID!
  email: String!
  name: String!
  surname: String!
  phone: String!
  shops: [Shop] @connection(keyName: "byManager", fields: ["id"])
}
```

You can see each manager can have many shops. Here is the subscription code that is supposed to retrieve me some data 
```gql
export const onDeleteShop = /* GraphQL */ `
  subscription OnDeleteShop {
    onDeleteShop {
      id
      manager {
        id
        email
        name
        surname
        phone
        createdAt
        updatedAt
        owner
        shops {
          items {
            id
            category
            city
          }
        }
      }  
    }
  }
`;
```

And here is the code of my subcription : 
```js
return API.graphql(graphqlOperation(onDeleteShop, { owner: user.attributes.sub })).subscribe({
        next: async (data) => {
          console.log("on rentre dans la onDeleteShop souscription")
          console.log(data.value.data.onDeleteShop)
          setManager(data.value.data.onDeleteShop.manager)
        }
      })
```

I'm very surprised that it' working perfectly when I use the mock, and when I'm in normal mode it returns me null for shops :
```
{id: "xxx-xxx-xxx-xxx", manager: {…}}
id: "xxx-xxx-xxx-xxx"
manager:
createdAt: "2021-01-15T12:13:53.288Z"
email: ""
id: "xxx-xxx-xxx-xxx"
name: "V"
owner: "xxx-xxx-xxx-xxx"
phone: ""
shops: null
surname: "W"
updatedAt: "2021-01-15T12:13:53.288Z"
__proto__: Object
__proto__: Object
```

If instead of updating my manager state with the subscription returned data like this
`setManager(await data.value.data.onCreateShop.manager)`
I call the getManager Query, everything works. But I don't get why my subscription data is not fully loaded.
To solve my issue i called inside the subscription a query to get all my manager data :
`setManager(API.graphql(graphqlOperation(listManagers))`

I hope you understand me.

I use amplify 4.41.2 on MacOS

**Comment by ammarkarachi** [comment]
@vincent38wargnier Can you check what's the max depth you have set? I am assuming you are using codegen.

https://docs.amplify.aws/cli/graphql-transformer/codegen#statement-depth

**Comment by vincent38wargnier** [comment]
Hi @ammarkarachi 
My codengen depth is set up to 2, but I'm not using the auto generated code, I use my own mutation as I showed to you in my post.
Thank you.

**Comment by vincent38wargnier** [comment]
I just found this other issue, which might be related to mine #5542, apparently the mutation must excpect the same elements as response than the subscription, which is pretty weird. I didn't try enough to be sure about what I'm saying.

**Comment by jhockett** [comment]
Hi @vincent38wargnier. We're aware of this issue and are working with the service team to investigate it.

**Comment by kylekirkby** [comment]
This is also possibly the cause of an issue that I'm facing. I'm using the IAM authMode and I'm failing to retrieve any data in the subscription payload.

```gql

type Resource
	@model
	@auth(
		rules: [
			{ allow: public, operations: [read], provider: iam }
			{ allow: groups, groups: ["basic", "editors", "admin"], operations: [read] }
			{ allow: groups, groupsField: "editorGroups", operations: [read, update, create] }
			{
				allow: owner
				ownerField: "editors"
				operations: [read, update, create]
				identityClaim: "email"
			}
		]
	) {
	id: ID!
	title: String!
	description: String!
	videoUrl: String
	presentationUrl: String
	speakers: [ResourceSpeaker] @connection(keyName: "byResource", fields: ["id"])
	editorGroups: [String]
	editors: [String]
}

type ResourceSpeaker
	@model(queries: null)
	@auth(
		rules: [
			{ allow: public, operations: [read], provider: iam, queries: null }
			{ allow: groups, groups: ["admin", "basic", "editors"], operations: [read], queries: null }
			{
				allow: groups
				groups: ["admin", "editors"]
				operations: [create, read, update, delete]
				queries: null
			}
		]
	)
	@key(name: "byResource", fields: ["resourceId", "speakerId"])
	@key(name: "bySpeaker", fields: ["speakerId", "resourceId"]) {
	id: ID!
	resourceId: ID!
	speakerId: ID!
	resource: Resource! @connection(fields: ["resourceId"])
	speaker: Speaker! @connection(fields: ["speakerId"])
}
```
A subscription for the Resource type is returning:

```json
{
"value": {
    "data": { "onCreateResource" : "null" }
  }
}
```
On a separate note, since I'm using two `authMode`'s I've using:
```js
const sub = API.graphql({ query: subscriptions.onCreateResource, authMode: authMethod });
```
Where `authMethod` is either `AMAZON_COGNITO_USER_POOLS` or `AWS_IAM`, depending on whether the user is logged in or not. 

I couldn't find much documentation on a custom `authMode` with subscriptions. Maybe we should update the docs with examples on using `authMode` with subscriptions?

**Comment by vincent38wargnier** [comment]
Hi @kylekirkby , for me the way subscriptions work is pretty clear now :

The subscription returns the data you specified, if this data is included in the response of the query/mutation that triggered the subscription.

It means that if you want a subscription fires, first you need to have in your query/mutation's response the items that the subscription is listening to, and you also need to ask in your query/mutation all the items needed for your subscription.

I'm also using different auth modes : Cognito for logggedIn users, IAM for public and API_KEY for Lambda, and my subscriptions fire perfectly anytime, whatever auth method I use. The important thing is that anytime you do a request, be sure to ask the data needed by the subscription to fire.

**Comment by yuth** [comment]
@vincent38wargnier The subscription works by using the data that `mutation` result provides and has  no capability to query the data source for missing fields as it documented [here](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html)

> If you use the pure WebSockets client, selection set filtering is done per client, as each client can define its own selection set. In this case, the subscription selection set must be a subset of the mutation selection set. For example, a subscription addedPost{author title} linked to the mutation addPost(...){id author title url version} receives only the author and title of the post. It does not receive the other fields. However, if the mutation lacked the author in its selection set, the subscriber would get a null value for the author field (or an error in case the author field is defined as required/not-null in the schema).

**Comment by vincent38wargnier** [comment]
Yes that's what I understood. But this behaviour is not very instinctive, neither convenient.

**Comment by Morrious** [comment]
@vincent38wargnier It's not clear to me if you found a solution to your issue or a workaround? I have the same issue, am using the auto-generated subscriptions with depth 3, but I still get null for the connection elements just like your original question.

**Comment by vincent38wargnier** [comment]
Make sure the mutation that fires the subscription retrieves the data you expect from the subscription. 
Subscriptions are only filtering the data retrieved by the mutation, it's not getting any data from the database.

**Comment by Morrious** [comment]
Thanks! I was just editing my reply after I figured it out. Yes, not intuitive, you have the basically double up on the parameters that you want to return from the subscription.

**Comment by vincent38wargnier** [comment]
Yeah, and the worst is when you will do an update to your table attributes, you will need to edit all the mutations that fire your subscription. It's very easy to forget one mutation call somewhere in the code.

**Comment by Morrious** [comment]
> Yeah, and the worst is when you will do an update to your table attributes, you will need to edit all the mutations that fire your subscription. It's very easy to forget one mutation somewhere in the code, if many different mutations fire the same subscription.

The way I'm handling this is by using the Amplify CLI for all of my graphql generation and creating different depths for different use-cases with `amplify codegen configure && amplify codegen`. I end up with a folder structure: graphql/depth3, graphql/depth4, etc. It's a bit of a pain and I worry I will need to make custom queries in the future if these deeper queries are still returning too much data, but we'll see.

**Comment by vincent38wargnier** [comment]
Ah yeah if you use the auto generated code then you might not have this issue, but I personally write my own requests in order to not fetch data that I don't need.
