### ISSUE TITLE
No export named api###GraphQLAPIIdOutput:GetAtt:####Table:Name found

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#6484]
**Describe the bug**
After updating a Lambda function, pushing yields the error *No export named api###GraphQLAPIIdOutput:GetAtt:####Table:Name found*.

**Amplify CLI Version**
 4.41.2

**To Reproduce**
```
amplify init
amplify add auth
amplify add analytics
amplify push
amplify add notifications
amplify add api
amplify add function
  trigger
  additional resources: analytics, api
amplify push
amplify update function
  additional resources: analytics, storage
amplify push
```

**Expected behavior**
I expect that environment variables and permissions are set for the DynamoDB tables instead of the AppSync api.

**Comment by ammarkarachi** [comment]
@avlonder this is a know bug it basically doesn't clear up the resource after it assigns it to them

**Comment by avlonder** [comment]
@ammarkarachi, what workaround do you propose? Does removing the function in the Lambda console, and then updating and pushing with the CLI do the job?

**Comment by ammarkarachi** [comment]
If you have the code swapping it out with a new function would be easier than messing with CFN files

**Comment by avlonder** [comment]
> If you have the code swapping it out with a new function would be easier than messing with CFN files

Uhu, I see. However, for some reason,  doing
```
amplify remove function
amplify push
amplify add function
amplify push
```
sometimes doesn't work either and returns the same error mentioned in the title. I have 15 functions and it happens to one of them. If I look in the console, the function doesn't exist, so I don't understand what's going on here. I will try renaming the function, but I hope this won't happen a lot, because this causes a chain of renamings in my stack.

**Comment by avlonder** [comment]
> If you have the code swapping it out with a new function would be easier than messing with CFN files

Uhu, I see. I don't know if this is related, but if I run
```
amplify remove function
amplify push function
amplify add function
amplify push function
```
for some functions, I get the error *the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs*.

The particular function that yields this error has permissions for analytics and storage, and apparently, the storage category is giving this error.  Also, this function is invoked in a resolver (and not triggered by DynamoDB streams as mentioned in my original report).

**Comment by avlonder** [comment]
So, I have been experimenting with this for a day (!!), and I came to the conclusion that the combination of permissions for analytics and storage breaks it, if you have not set a DynamoDB streams trigger. Does this make any sense?

**Comment by avlonder** [comment]
> EDIT: this is a dependency issue that occurs when you set permissions for both analytics and storage resources, without DynamoDB streams trigger. It can be fixed by adding the _GraphQLAPIIdOutput_ to _dependsOn_ in _amplify-meta.json_ and to _parameters_ in the function's _cloudformation-template.json_

I opened a new bug issue for this: #6607

**Comment by akshbhu** [comment]
Closing this in favour of  #6639
