### ISSUE TITLE
Cognito redirect URI restriction

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-cli#6488]
When working with Cognito OAuth, the Amplify CLI forces you to use a trailing slash in the redirect URI.

For example, if I try to use:

__http://localhost:3000/profile__

The CLI gives me this error message:

```
The value must be a valid URI with a trailing forward slash. HTTPS must be used
instead of HTTP unless you are using localhost.
```

It forces you to use a URI that looks something like this: __http://localhost:3000/profile/__ (notice the trailing slash)

The problem is that, when using the trailing slash, the client does not authenticate the user upon redirect.

The only way to fix this is to wait for the deployment to complete, then manually update the local configuration in __aws-exports.js__ and also manually update the redirect uri in the cognito dashboard.

I've recorded a video of the issue and uploaded it [here](https://www.youtube.com/watch?v=qVxwNkkSo-o)

__Notes__:

1. The root domain __does__ work, i.e. if I set it to be just __http://localhost:3000/__ it works fine, only when adding a path does it fail.
2. The code I'm using to sign the user in is this: `Auth.federatedSignIn({ provider: "Google" })`

__Mitigation suggestion:__ Disable the CLI check that tries to ensure there is a trailing slash. If this was disabled, there would be no issue for me. It would be nice if the Cognito service would parse the URL properly though (or maybe this is something to do with the Amplify Client libraries?)  but for now this would be a good way to mitigate.

**Comment by kaustavghosh06** [comment]
Discussed with @undefobj offline. We need to brainstorm and come with a better DX in the CLI to come up with a warning or a workaround. 
Just FYI, Cognito service has a limitation around the usage of "trailing slashes" for URL's and hence the CLI enforces it.

**Comment by dabit3** [comment]
Update here: It looks like since I was using Next.js, there is a way to configure the trailing slash to make this work. There is a good blog post here that I will post:

https://creativedesignsguru.com/next-js-aws-amplify-cognito-oauth/

Using this configuration, everything works properly. I will go ahead and close this issue since I opened it and it seems like there is a simple workaround built into the framework. This works fine on other frameworks out of the box from what I can tell.

Thanks for everyone's guidance here.
