### ISSUE TITLE
Chained function mutation timeout

### ISSUE THREAD

**Issue by jgroom33** [aws-amplify/amplify-cli#6490]
Function chaining [defined here](https://docs.amplify.aws/cli/graphql-transformer/function#chaining-functions) is a nice feature

Mutation timeouts limit the capability though.

Assumption:

```
type Mutation {
  somethingcomplex(input: String): String
    @function(name: "step1-${env}")   # consumes 5 seconds of lambda runtime
    @function(name: "step2-${env}")   # consumes 10 seconds of lambda runtime
    @function(name: "step3-${env}")   # consumes 10 seconds of lambda runtime
    @function(name: "step4-${env}")   # consumes 10 seconds of lambda runtime
    @function(name: "step5-${env}")   # consumes 10 seconds of lambda runtime
```

The above mutation will never reach step 5. There is a 30 second hard limitation for appsync mutation responses.

Potential workarounds:

* Don't use Appsync as the entrypoint
* Use REST or direct lambda call

Potential Solutions:

* Add Step Functions to Amplify

**Comment by ammarkarachi** [comment]
@jgroom33 Thanks for the suggestion, I will mark this as an enhancement for the team to review

**Comment by kaustavghosh06** [comment]
@jgroom33 Unfortunately AppSync service has a hard limit on the execution timeout - which is 30 seconds as you mentioned. You can open up a request with your use-case in the AppSync Service GitHub repo out here - https://github.com/aws/aws-appsync-community to convey this directly to the AppSync service team.

As per as Step functions goes, Amplify doesn't support it out of the box, but you can definitely use custom resources within Amplify to acheive this use-case. You can take a look at this community created blog post to learn more about integrating step functions with the Amplify CLI - https://cevo.com.au/post/2020-10-14-extend-aws-amplify-with-custom-resources/

Custom AWS resource integration docs - https://docs.amplify.aws/cli/usage/customcf

**Comment by jgroom33** [comment]
@kaustavghosh06  thank you for the pointers!
