### ISSUE TITLE
Subscription by ID - get event source mutation name

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#6491]
I tried https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js 

My question now is, do I somehow get the mutation that is responsible for the event? 

Background: I don't want to write an extra handler for each event. 
onCreateByID
onUpdateByID
onDeleteByID

so would be cool if I could write: 

```
onCareerEventsByPartner(partner_id: ID!): Career
    @aws_subscribe(mutations: ["createCareer", "deleteCareer", "updateCareer"])
```

and than in js: 

```
data.value.data.onCareerEventsByPartner

If(data.value.data.onCareerEventsByPartner.createCareer){}
If(data.value.data.onCareerEventsByPartner.updateCareer){}

or
if(data.sourceMutation === "createCareer"){}
```

**Comment by jhockett** [comment]
I'm investigating this issue @davidbiller. Can you please tell us about your use case?

**Comment by davidbiller** [comment]
I know from google firebase that I can use any field/attribute as param, without to create a custom subscription in my schema. 

I have several tables, since I am building a dashboard I would like to monitor for specific parameters for each table. 

I have careers. Partners, Users. 

Now I would like to monitor each table: 
When a user starts a new career.
When he deletes it, updates it, etc. 

The same goes for partners. 

So I would have to create onCreate, onUpdate, onDelete as customSub, because I want to watch for one ID each. 

With a customSub I can pass an array of mutations. 

It would be good if I also get the event previously entered in the array emptied when an event is fired. 

Currently I get the subscription event delivered. But I don't see if it is a create, update or delete event.

Translated with www.DeepL.com/Translator (free version)

**Comment by kaustavghosh06** [comment]
@davidbiller Are you still looking for a solution for this?

**Comment by davidbiller** [comment]
> @davidbiller Are you still looking for a solution for this?

If there is one :) sure. 

Is it clear what I need?

**Comment by yuth** [comment]
@davidbiller yes, this is supported in AppSync as its documented [here](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html)

> You can make these fields real time by adding an `@aws_subscribe(mutations: ["mutation_field_1", "mutation_field_2"])` directive for each of the subscriptions you want to receive notifications for



> so would be cool if I could write:
> 
> ```
> onCareerEventsByPartner(partner_id: ID!): Career
>     @aws_subscribe(mutations: ["createCareer", "deleteCareer", "updateCareer"])
> ```

This will work exactly the way you want
