### ISSUE TITLE
Error on Push: Could not initialize 'dev': Stack with id amplify-PROJECTNAME-dev-131445 does not exist

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-cli#6498]
My project was working but somehow the build was failing because a previous build was stuck and could not complete.  I had this happen previously and got around it by deleting the build.  This time I couldn't find that in the menu but ended up deleting the CF stack instead (dumb, I know).  I seem to be able to still find all of the resources (S3 storage is still there, cognito, api all there) but I can't seem to push anymore and it gives me the error in the title when I "amplify push".  

I can even see the S3 folder with the amplify project, but I don't know what my next steps should be.  Should I try and recreate the cloudformation stack from the deleted one? is that even possible?  Do I just need to give up and recreate the whole project? what are my options after accidently deleting the cloudformation stack?

**Amplify CLI Version** 
4.41.2

**Comment by ammarkarachi** [comment]
@contractorwolf 

1. Do you have other environments setup on the project? 
2. Is this the production environment stack that ended up getting deleted?

**Comment by contractorwolf** [comment]
@ammarkarachi this is the only environment I have for this project right now, currently: dev

**Comment by ammarkarachi** [comment]
@contractorwolf I tried out your scenario and

1. created a project x with a deleted stack but with just auth.
2. new project y with no categories and freshly initialized. 
3. Copied x is backend directory 
4. Replace everything in y's amplify-meta.json with x's content except all under
```
{
  "providers": {
    "awscloudformation": {
    ...
    }
}
```
5. Same with team-provider.json leaving that object intact
```
{
  "dev": {
    "awscloudformation": {
  ...
 }
}
```
and `amplify push`

This was possible with just auth but I would try it out to save your project
