### ISSUE TITLE
Ability to query by relationship

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-cli#65]
**Do you want to request a feature or report a bug?**
Feature

**What is the expected behavior?**
It would be nice to have a GraphQL query created to handle querying by a relationship. For instance, if I have this schema:

```graphql
type User @model {
  id: ID!
  name: String!
}

type Post @model {
  id: ID!
  name: String!
  owner: User @connection
}
```

There should be a way to list all posts by a specific owner (by specifying owner ID).

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
macOS 10.13.6

* **Output of ``amplify --version``**:
0.1.14

* **Did this work in previous versions?**: Y/N
N

**Comment by adrianhall** [comment]
This is pretty much supported already:

```
type User @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "UserPosts")
}

type Post @model {
  id: ID!
 title: String!
 owner: User @connection(name: "UserPosts")
}
```

You can then do something like:

```
query GetUserPosts($id: ID!) {
  getUser(id: $id) {
    id name posts { id title }
  }
}
```

Would that work for you?

**Comment by ffxsam** [comment]
Ahh, looks familiar! Reminds me a bit of Prisma. That would probably work out. And of course, we can apply limit/token filters to `posts` in that query to paginate through posts, I imagine.

**Comment by mikeparisstuff** [comment]
@ffxsam Yes, you have full pagination and filter arguments on all @connection fields. Note: Only 1-M, M-1, and 1-1 connections are implemented as of now.

**Comment by ffxsam** [comment]
Thanks! Side note: are there plans to make Amplify auto-create DynamoDB tables based on the schema?

**Comment by mikeparisstuff** [comment]
I think this can be closed.
