### ISSUE TITLE
Running npm install on lambda deployments causing problems with sharp

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#6505]
I am trying to deploy my lambda with a dependency on sharp...

Sharp requires downloading linux dependencies instead of darwin...

When I download and setup the sharp dependency with linux, then do a deploy the linux dependencies are overwritten when npm install is run...

This is making it impossible to deploy linux sharp to lambda...

I would like a feature to turn off the npm install functionality on individual functions, or alternately run a post npm install script...

**Comment by kaustavghosh06** [comment]
@GeorgeBellTMH In your package.json file you can have postinstall hook which runs after npm install. You can learn more out here - https://docs.npmjs.com/cli/v6/using-npm/scripts

**Comment by GeorgeBellTMH** [comment]
Sounds good. Thanks
