### ISSUE TITLE
Add TypeScript functions as templates in functions flow

### ISSUE THREAD

**Issue by cmaycumber** [aws-amplify/amplify-cli#6507]
**Which Category is your question related to?**
function

**Amplify CLI Version** 
4.41.1

Is it possible to add a hook that would fire a local cli command when a function is added through the amplify-cli? I'm trying to convert functions to typescript immediately for a better developer experience and wasn't sure if this was possible with a custom plugin or by other means.

**Comment by kaustavghosh06** [comment]
@cmaycumber Did you get a chance to check this out - https://docs.amplify.aws/cli/function/build-options to add hooks to the functions for tsc compilation?

**Comment by cmaycumber** [comment]
> @cmaycumber Did you get a chance to check this out - https://docs.amplify.aws/cli/function/build-options to add hooks to the functions for tsc compilation?

I did see that. The build isn't really necessarily my problem it's initializing the different files like the index.ts, pakage.json, etc. once a function is added.

**Comment by kaustavghosh06** [comment]
@cmaycumber Got it. So what you're looking for is TS based template to get started with for Lambda functions?

**Comment by cmaycumber** [comment]
> @cmaycumber Got it. So what you're looking for is TS based template to get started with for Lambda functions?

Yes, basically. It'd be nice to have the option built into amplify to add functions with a typescript configuration out of the box, but I understand that might be asking for a lot. I was simply trying to streamline the process of adding functions to avoid having to copy and paste the necessary files/re-setup the files every time.

It's not a huge priority, just an area where I thought the developer experience could be improved slightly.

**Comment by xo28122000** [comment]
Hi @cmaycumber
I am currently working on implementing runtime hooks for the cli, which would run before or after execution of amplify commands like add, push etc. The scripts for these hooks would be provided by customers. So for this case, you would hook a post add script to delete the amplify generated js files and add ts files. Once you hook the script it will always run after amplify add. 

would this solve your usecase? If we were to pass parameters (like amplify command or plugin ran), which ones do you think would be most beneficial to have access to in the scripts?

**Comment by cmaycumber** [comment]
> Hi @cmaycumber
> I am currently working on implementing runtime hooks for the cli, which would run before or after execution of amplify commands like add, push etc. The scripts for these hooks would be provided by customers. So for this case, you would hook a post add script to delete the amplify generated js files and add ts files. Once you hook the script it will always run after amplify add.
> 
> would this solve your usecase? If we were to pass parameters (like amplify command or plugin ran), which ones do you think would be most beneficial to have access to in the scripts?

I think this definitely would! It sounds like I could easily replicate the function creation every time across different dev machines which would be great.

**Comment by xo28122000** [comment]
> > Hi @cmaycumber
> > I am currently working on implementing runtime hooks for the cli, which would run before or after execution of amplify commands like add, push etc. The scripts for these hooks would be provided by customers. So for this case, you would hook a post add script to delete the amplify generated js files and add ts files. Once you hook the script it will always run after amplify add.
> > would this solve your usecase? If we were to pass parameters (like amplify command or plugin ran), which ones do you think would be most beneficial to have access to in the scripts?
> 
> I think this definitely would! It sounds like I could easily replicate the function creation every time across different dev machines which would be great.

Thanks for your response! I will be sure to include this use case.

**Comment by xo28122000** [comment]
Hi @cmaycumber
I just released the RFC for runtime hooks: #7614 
 It would be really helpful if you can leave some feedback!

**Comment by lazpavel** [comment]
closing this ticket in favor of [runtime hooks](https://docs.amplify.aws/cli/usage/command-hooks/)
