### ISSUE TITLE
CLI - amplify pull - File project: data should NOT have additional properties: 'frontend-ios'

### ISSUE THREAD

**Issue by kchaturanga** [aws-amplify/amplify-cli#6508]
E:\NodeJS\****ookings\***-api>amplify pull --appId d****** --envName staging
Amplify AppID found: *******19. Amplify App name is: ***-web-app
Backend environment staging found in Amplify Console app: **-web-app
Failed to pull the backend.
File project: data should NOT have additional properties: 'frontend-ios'
JSONValidationError: File project: data should NOT have additional properties: 'frontend-ios'

-----------------------
amplify -v
4.39.0

Im getting above issue when I tried to connect  app to this backend environment using the Amplify CLI

**Comment by akshbhu** [comment]
Hi @kchaturanga 

This seems to be a problem with feature flags. Can you update to latest version of amplify (4.41.2) and try again?

Let us know if this works for you?

**Comment by kchaturanga** [comment]
@akshbhu  It worked with the latest version, Sorry for the late update, And thank you for the rompt reply ..
