### ISSUE TITLE
await response for: What permissions do you want to grant to this new layer version?

### ISSUE THREAD

**Issue by jgroom33** [aws-amplify/amplify-cli#6519]
Scenario:

* executing `amplify push`
* updates to layer function exists
* updates to other functions exist

The CLI does not wait for a response to the question "What permissions do you want to grant to this new layer version?"

**Amplify CLI Version**
4.41.2

**To Reproduce**

1. make changes to layer
2. make changes to function
3. `amplify push`
4. wait
5. notice the push does not continue

**Expected behavior**

CLI should wait for user to respond to the question instead of exiting.

**Desktop**

- OS: Windows 10 WSL 2
- Node Version. v12.18.3

**Comment by jhockett** [comment]
Hi @jgroom33, I wasn't able to reproduce this on mac. It might be WSL specific, but do you see any similar issues when using Amplify CLI? The code that waits on this response isn't fundamentally different from other question answer flows.

**Comment by jgroom33** [comment]
@jhockett I have not noticed any other similar issues.

The workaround is pretty simple: `amplify push` layers on their own.  This is probably good practice anyway, so I don't think this is worth any extra effort.

**Comment by mgarabedian** [comment]
I am having the same problem on my mac. I get "What permissions do you want to grant to this new layer version", and the amplify push exits. on version 4.41.2

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!
