### ISSUE TITLE
Referencing the Region in the Graphql Schema

### ISSUE THREAD

**Issue by amirmishani** [aws-amplify/amplify-cli#6520]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.39.0

**What AWS Services are you utilizing?**
API, Auth, Function

**Provide additional details e.g. code snippets**
I'm trying to configure an HTTP resolver to call a step function. The url needs the correct aws region. I know you can pass the environment like so `${env}` but I couldn't find anything in the docs stating how to pass the aws region. Is this possible right now or does it need to be feature request?

Something like this: `@http(method: POST, url: "https://states.${region}.amazonaws.com/")`

**Comment by jhockett** [comment]
Hi @amirmishani, we don't currently have support for passing in values to the http directive. Marking this as a feature request.

**Comment by meehawk** [comment]
Hi @jhockett I'd like to work on this issue. However, I am new to the `amplify-cli` ecosystem. Any directions would be awesome

**Comment by jhockett** [comment]
Glad to hear it @meehawk! I recommend taking a look at our contributing [document](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md).

For tackling this issue, I would look to the various graphql packages, mainly `graphql-http-transformer`. Good luck!

**Comment by meehawk** [comment]
@jhockett thank you so much. I have already started to work on this issue
