### ISSUE TITLE
How to reference AmplifyAppId inside CF-template for API Gateway

### ISSUE THREAD

**Issue by schorfi** [aws-amplify/amplify-cli#6523]
Hello,
I am trying to reference ("Ref") the amplify application id related to of the current pulled backend environment inside the cloudformation template of an API-Gateway.
Is there a way to access this value? If yes, how?

For the bigger picture - I am trying to create an CORS allow origin header which will allow the amplify app deployment url; so that the app works together with its API GW.

Please let me know if you can help me further.
I am not 100% sure, this perfectly fits here as it is also an CF template topic.

Looking forward for your response

**Comment by jhockett** [comment]
Hi @schorfi, to pass a Parameter to the cloudformation template, it needs the Parameter type listed in the template:

```json
...
Parameters: {
  "myParamName": { "Type": "String" }
},
...
```

To pass in the appId to the template, add it to `team-provider-info.json`.

It would be at ${envName}.categories.${categoryName}.${resourceName}.${paramName}: ${myValue}

Something like:
```json
{
  "dev": {
    "awscloudformation": {
      ...
    },
    "categories": {
      "api": {
        "myApiResourceName": {
          "myAppId": <AmplifyAppId>
        }
      }
    }
  }
}
```

Here's the official docs on refs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

**Comment by schorfi** [comment]
thank you, for the quick response
adding this does indeed works and I have seen the docs to Ref already; now I understood where this input is coming from

now, the AmplifyAppId is already inside of the envname.awscloudformation you showed above...
Is there a way to access this (maybe via Fn::Sub?) or reference it in the categories (to make it an input to the template)?
