### ISSUE TITLE
Amplify Mock Can't list storage buckets or upload objects

### ISSUE THREAD

**Issue by CSTDev** [aws-amplify/amplify-cli#6524]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Trying to use the mock feature to run the application locally and upload a file to an S3 bucket.

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.41.2

**What AWS Services are you utilizing?**
Amplify Mock, storage

**Provide additional details e.g. code snippets**
I'm using the Go SDK to create a lambda which creates a file then uploads it to a bucket.
I've started the services uses `amplify mock`
The following is the code I'm using to connect and upload to the bucket:

```
storageSess = session.Must(session.NewSession(&aws.Config{
			Region:      aws.String("us-fake-1"),
			Endpoint:    aws.String("http://localhost:20005"),
			Credentials: credentials.NewStaticCredentials("fake", "fake", "fake"),

uploader := s3manager.NewUploader(storageSess)

	_, err := uploader.Upload(&s3manager.UploadInput{
		Bucket: aws.String(s.BucketName),
		Key:    aws.String(name),
		Body:   file,
	})
```

On running it it attempts to contact `http://<BucketName>.localhost:20005/<key>` and returns the error `dial tcp: lookup <bucketname>.localhost: no such host`

Should the session config be something else to connect?

I've also tried just listing buckets and receive a `no such key` error. I've tried using different regions, and a default session:

```
storageSess = session.Must(session.NewSessionWithOptions(session.Options{
			SharedConfigState: session.SharedConfigEnable,
		}))
```

I can list contents of my bucket by doing a get request (outside of Go e.g. with the browser) to `http://localhost:20005/<bucketname>-dev`

Thanks

**Comment by akshbhu** [comment]
Hi @CSTDev 

We currently don't support go SDK for amplify mock storage. we only support (Javascript, android, ios).

One thing you can try in addition to the code you shared above is setting ```S3ForcePathStyle``` to true in the config. This will force S3 to use PathStyleURL like this ```http://localhost:20005/<bucketname>-dev```.
You can find more documentation here: https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config

**Comment by CSTDev** [comment]
Thanks @akshbhu That did in fact work. Much appreciated.
