### ISSUE TITLE
Cannot get resource: myFunctionName from 'function' category.

### ISSUE THREAD

**Issue by alexhouse** [aws-amplify/amplify-cli#6531]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Lambda functions (layers)

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

* 4.41.2

**What AWS Services are you utilizing?**

* API Gateway
* GraphQL API
* REST API
* Functions
* Hosting
* Cognito Auth

**Provide additional details e.g. code snippets**

I've got two envs that I predominantly use, `prod` and `staging`. I dev and check understanding in `staging` before checking out `prod` and pushing the final setup.

I can normally work around most conflicts, but lately I've been getting this error a lot which I can't seem to get around:

```
Cannot get resource: myFunctionName from 'function' category.
An error occurred during the push operation: Cannot get resource: myFunctionName from 'function' category.
```

In this scenario:
* I created a function (a layer) in `staging`
* I pushed it to `prod`
* I ended up deleting it from `staging`
* Checked out `prod` and went to push changes (including the deletion) but hit error.

Is this something specific to CLI or more likely to be CloudFormation related?

**Comment by jhockett** [comment]
Hi @alexhouse, what steps did you take during this step "I ended up deleting it from staging"?

**Comment by alexhouse** [comment]
@jhockett removed any dependencies using `amplify function update` (manually had to remove the layer from any `dependsOn` blocks in `amplify-meta.json` as they weren't affected), and then `amplify function remove`

**Comment by alexhouse** [comment]
The only way I found to workaround this particular issue was to checkout my secondary environment, `amplify pull`, recreate any new functions I'd previously created & copy the code over from my other git branch, then repeat the steps I'd taken before - remove dependencies, manually edit `amplify-meta.json` and then `amplify function remove` again

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!

**Comment by renebrandel** [comment]
Hi @alexhouse - we're closing this because of our new lambda layer changes has been released. Check out the details here:
- https://docs.amplify.aws/cli/migration/lambda-layers-update 
- https://docs.amplify.aws/cli/function/layers

**Comment by alexhouse** [comment]
Perfect, thanks! So far new layer stuff is working well 👍  Appreciate the update
