### ISSUE TITLE
Mocking a function with Fn::Select on env variables

### ISSUE THREAD

**Issue by DavidAlvarado23** [aws-amplify/amplify-cli#6533]
**Describe the bug**
When mocking a function to run it locally and it has set a env variable in the CloudFormation template with a Select statement like this:
```json
{
   "S3_IMAGES_BUCKET": {
      "Fn::Join": [
         "",
         [
            "arn:aws:s3:::my_bucket",
            {
               "Fn::Select": [
                  3,
                  {
                     "Fn::Split": [
                        "-", 
                        {
                           "Ref": "AWS::StackName"
                        }
                     ]
                  }
               ]
            },
            "-",
            {
               "Ref": "env"
            }
         ]
      ]
   }
}
```
Gives the following error:
**FN::Select expects list item to be an array instead got [3,{"Fn::Split":["-",{"Ref":"AWS::StackName"}]}]**

**Amplify CLI Version**
4.41.0

**To Reproduce**
Create a Lambda function with the Amplify CLI and add a env variable in the CloudFormation template as the one indicated above.

**Expected behavior**
The env variable should be created with the correct parameters to mock the function. When deploying the function the env variable is created correctly.

**Desktop:**
- OS: Ubuntu 18.04.5
- Node Version: v14.15.3

**Comment by edwardfoyle** [comment]
@DavidAlvarado23 this is a bug. Looks like in mock we don't currently have logic to handle parsing the second value in select if it's not already an array: https://github.com/aws-amplify/amplify-cli/blob/9acdc7e5b8aebc1fcbcd43e25c0fcdd5842f2427/packages/amplify-util-mock/src/CFNParser/intrinsic-functions.ts#L126

**Comment by edwardfoyle** [comment]
The fix for this has been released. Please upgrade to the latest version of the CLI
