### ISSUE TITLE
"amplify env add" asks "Do you want to use an existing environment?"

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#6535]
When I enter `amplify env add` or `amplify env add <env name>` it first asks "Do you want to use an existing environment?" If I say yes, and select an environment, it will just use that environment and not create a new environment. I personally believe this is counter-intuitive. It should immediately just ask you for the name of the new environment. If I wanted to use an existing environment, I would run `amplify env checkout`.

Also, if you provide an environment name to `amplify env add` (e.g. `amplify env add stg`) it should be able to immediately add that environment and skip the environment name prompt.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Simply create an Amplify project and enter `amplify env add` to add a new environment.

**Expected behavior**
It asks "Enter a name for the environment" and rest of the steps proceeds as expected for adding new environment. (selecting AWS profile, etc.)

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version: v12.18.4

**Comment by gitaalekhyapaul** [comment]
I would like to work on this issue.
