### ISSUE TITLE
I can no longer pull my amplify env -  Failed to communicate with the Amplify CLI

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6536]
**Describe the bug**
It appears that something has changed with the way `amplify pull` work as I can no longer pull an env. 

**Amplify CLI Version**
4.41.2

**To Reproduce**

Create an empty directory.  Run `amplify pull --appId YOUR_API_ID --envName develop`
Whatever has been changed recently with the Admin UI has broken the ability to pull down our environments... We are now greeted with this:

`amplify pull --appId d10hksl83hnlja --envName develop`

![amplify-pull-errro](https://user-images.githubusercontent.com/4564433/106744270-72215480-6617-11eb-9979-b47219714fec.PNG)

**Expected behavior**
The ability to be able to pull an env! 

**Screenshots**
![image](https://user-images.githubusercontent.com/4564433/106744311-7fd6da00-6617-11eb-8c4d-e80ec192184b.png)

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
 - Node - v14.10.1
 - OS - Windows 10 / WSL (Ubuntu 20.04)
 - 
**Log output**

**Additional context**
This used to work fine. I've got a feeling that the Amplify Admin UI has broken things :(

**Comment by pcolmer** [comment]
This seems related to https://github.com/aws-amplify/amplify-adminui/issues/84 but that issue has been closed. Clearly there is still an issue ...

**Comment by jhockett** [comment]
Hi @kylekirkby, this is due to a bug in WSL that prevents the browser from sending a request to localhost running in Ubuntu from Windows. See this [issue](https://github.com/aws-amplify/amplify-adminui/issues/35) for more context.

**Comment by kaustavghosh06** [comment]
@kylekirkby  The workaround right now for WSL is what you've mentioned in https://github.com/aws-amplify/amplify-adminui/issues/84#issuecomment-772466619

We're tracking this as a part of this issue https://github.com/aws-amplify/amplify-adminui/issues/35 @pcolmer 

Also, the next release of the CLI will provide options to select from AWS profile/access-keys/Admin UI if you don't wish to authenticate via the Admin UI for your environment. PR for the same: https://github.com/aws-amplify/amplify-cli/pull/6433
