### ISSUE TITLE
Are union types supported in schema.graphql and amplify mock? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#6537]
**Which Category is your question related to?**
graphql api

**Amplify CLI Version** 
4.41.2

If I specify this type of Union in schema.graphq: 

`union Media =  Video | Image | Link`

And I run amplify mock, I get the following warning: 

`Type "Media" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.`

What does this warning mean? Are union types supported in the schema.graphql / amplify mock?

**Comment by jhockett** [comment]
@hisham sorry for the delayed reply. Unions are not supported in the GQL transformer. For more context, see this [issue](https://github.com/aws-amplify/amplify-cli/issues/736).

**Comment by jhockett** [comment]
Closing this issue. @hisham for further updates on union support, see the GraphQL Transformer [RFC](https://github.com/aws-amplify/amplify-cli/issues/6217). Feedback is welcome!
