### ISSUE TITLE
Give option to push without first pulling the `#current-cloud-backend` as well as to disable overwriting changes in `backend` when push fails.

### ISSUE THREAD

**Issue by iurquiza** [aws-amplify/amplify-cli#6538]
**Is your feature request related to a problem? Please describe.**
I am always frustrated to have my CloudFormation changes overwritten or reverted whenever a push fails.

**Describe the solution you'd like**
Please give the option to push without first pulling the `#current-cloud-backend` directory from S3 by passing a flag or parameter with the `push` command. Keep the current behavior as default, but give the option to change it.
Please also give the ability to disable overwriting local CloudFormation changes in `backend` directory whenever a push fails. This is relate to the above as the content of `backend` get synchronized with `#current-cloud-backend`.

**Comment by jhockett** [comment]
Hi @iurquiza, can you elaborate on why you are looking for these changes and what your use case is?

**Comment by iurquiza** [comment]
Sure! Most of the time the CloudFormation template generated by the Amplify CLI is adequate to provision your resources as desired, but there are times when you want to customize the CloudFormation template itself and not just update the parameter. As you can imagine editing CloudFormation templates is not error proof, so when deploying your customized template there can be issues that cause the `amplify push` to fail which automatically triggers a pull from the cloud. I understand that making the default behavior restoring the template to the last successfully provisioned version is optimal, but having your custom changes overwritten every time an `amplify push` fails can be frustrating, especially when the changes made are significant. I understand there are ways to restore your changes and continue working/experimenting after a failed `amplify push`, but adding steps and time to a process that can already be time consuming gets frustrating after a while. Adding a flag or parameter to prevent the automatic pull would address this issue while allowing the default behavior to continue being the same; is should not break any backwards compatibility. Let me know if you would like further clarification or details. Thanks!

**Comment by kaustavghosh06** [comment]
@iurquiza The pull command should only touch your #current-cloud-backend directory and the changes you make to your `amplify/backend` directory would remain intact. Are you modifying the  #current-cloud-backend directory or the amplify/backend directory?

**Comment by iurquiza** [comment]
@kaustavghosh06 Let me try to reproduce the issue and update the steps here. Thank you.

**Comment by iurquiza** [comment]
I am going to have to investigate this further, but there is definitely something strange going on.
Here are some of my observations:
- The issue does not happen consistently.
- When the issue does happen, the backed CloudFormation template's contents don't match what is in the repository's remote branch, so we can most likely dismiss a `git pull`, `git checkout`, or `git reset` being the culprit.
- The file contents also do not match what I originally thought, the contents of `#current-cloud-backend`.
- I've downloaded and extracted the `#current-cloud-backend.zip` from S3 and the backed CloudFormation template's contents do not match what is in there either.
- The file contents actually match what is in the `amplify-cfn-templates` directory in the S3 bucket.
- The `parameters.json` file associated with the CloudFormation template in question is also some times modified where properties that had previously been removed get reinstated. I have the GitLens extension installed in VS Code and can see that the files get modified around the `amplify push` fails.
- The `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` also contains the same attribute mentioned above, and the timestamp of the file also changes to around the time that the other file gets modified, but off by a couple of minutes.
I will post an update here if I can narrow down the cause.
Thanks!

**Comment by chakch** [comment]
any update about the feature ?

**Comment by josefaidt** [comment]
Closing in favor of [overrides](https://aws.amazon.com/blogs/mobile/override-amplify-generated-backend-resources-using-cdk/)
