### ISSUE TITLE
`amplify push` not to override specific resolvers

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#654]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
For example, I added manually a global secondary index to a dynamoDB table and set a resolver to scan against it. Now, whenever I update my schema locally and issue `amplify push` the resolver is overwritten and loses all manually set instructions.

Is there any way to preserve the manually changed resolvers?

**Comment by kaustavghosh06** [comment]
Yes, you can do this using the `‘amplify push —no-gql-override` command.

**Comment by sakhmedbayev** [comment]
Thank you @kaustavghosh06 for the help. I have tried to use `amplify push —no-gql-override` but it still overrode all resolvers.

**Comment by wizawuza** [comment]
@sakhmedbayev what version of amplify cli are you running? You can check it by running:
amplify -v

**Comment by sakhmedbayev** [comment]
@wizawuza my version is `0.2.1-multienv.22`

**Comment by kaustavghosh06** [comment]
@sakhmedbayev There are two dashes — and not one just - in the flag.
