### ISSUE TITLE
Expected scalar and got S3Object - S3Object resolves to scalar types?

### ISSUE THREAD

**Issue by BrianMagus** [aws-amplify/amplify-cli#6540]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

GraphQL

**Amplify CLI Version** 

4.41.2

**What AWS Services are you utilizing?**

API

**Provide additional details e.g. code snippets**
So, i've got this type for storing and referencing files in s3:
```gql
type S3Object @auth(rules: [{ allow: owner }]) {
  bucket: String!
  region: String!
  key: String!
}
```
each field resolves to a scalar type String, and my understanding is that an object must ultimately resolve to acceptable scalar types. 
 
However, when pushing the schema, I get the error:
```
Expected scalar and got S3Object
An error occurred during the push operation: Expected scalar and got S3Object
```

What am I not understanding about scalar types and how objects resolve? I thought maybe S3Object was somehow reserved as a keyword, but it doesn't matter what I call the object:

```gql
type PenName @model @auth(rules: [{ allow: owner }]) {
  penId: ID!
  penFull: String!
  penFirst: String!
  penMiddle: String
  penLast: String
  penBio: String
  penPhotoId: ID!
  penLogoId: ID!
  penPhoto: S3Object*** 
  penLogo: S3Object***
  penFBProfile: String
  penFBGroup: String
  penFBPage: String
  penTwitter: String
  penInstagram: String
  penAmazon: String
  penWebsite: String
  penNewsletter: String
  penGoodreads: String
  penStoryworldId: ID!
  storyWorlds: [StoryWorld] @connection(keyName: "byPen", fields: ["penId"])
}
```

**Comment by BrianMagus** [comment]
Playing with the schema a bit at a time to see when this happens, it appears that as soon as I start adding connections with keys, I get this error. For example, in the above referenced code, if my 'PenName' object looks like this:
```
type PenName @model @auth(rules: [{ allow: owner }]) {
  penId: ID!
  penFull: String!
  penFirst: String!
  penMiddle: String
  penLast: String
  penBio: String
  penPhotoId: ID!
  penLogoId: ID!
  penPhoto: S3Object*** 
  penLogo: S3Object***
  penFBProfile: String
  penFBGroup: String
  penFBPage: String
  penTwitter: String
  penInstagram: String
  penAmazon: String
  penWebsite: String
  penNewsletter: String
  penGoodreads: String
  penStoryworldId: ID!
  storyWorlds: [StoryWorld]
}
```
and the referenced StoryWorld looks like this:
```
type StoryWorld @model @auth(rules: [{ allow: owner }]) {
  worldId: ID!
  penId: ID!
  title: String!
  description: String
  logo: FileObject @connection
  series: [Series] 
  books: [Book] 
  elements: [Element]
}
```
everything is fine. 

If, however, I add an appropriate connection between PenName and StoryWorld:
```
type PenName @model @auth(rules: [{ allow: owner }]) {
  penId: ID!
  penFull: String!
  penFirst: String!
  penMiddle: String
  penLast: String
  penBio: String
  penPhoto: FileObject @connection
  penLogo: FileObject @connection
  penFBProfile: String
  penFBGroup: String
  penFBPage: String
  penTwitter: String
  penInstagram: String
  penAmazon: String
  penWebsite: String
  penNewsletter: String
  penGoodreads: String
  storyWorlds: [StoryWorld] @connection(keyName: "byPen", fields: ["penId"])
}

type StoryWorld @model @auth(rules: [{ allow: owner }]) 
@key(name: "byPen", fields:["worldId", "title", "description", "logo", "series", "books"]){
  worldId: ID!
  penId: ID!
  title: String!
  description: String
  logo: FileObject @connection
  series: [Series] 
  books: [Book] 
  elements: [Element] 
}
```
I get the above error. Does this have to do with query depth? If PenName is queried, it pulls the storyworlds (when/if called for), then hits the FileObject (this is me adjusting the name to see if that for some reason made any difference, it didn't) type and doesn't dig any deeper to resolve scalar types?

**Comment by jhockett** [comment]
Hi @BrianMagus,

> So, i've got this type for storing and referencing files in s3:
> 
> ```graphql
> type S3Object @auth(rules: [{ allow: owner }]) {
>   bucket: String!
>   region: String!
>   key: String!
> }
> ```

You can't use `@auth` on a type without `@model`.
