### ISSUE TITLE
Amplify storage add prefix for lambda trigger

### ISSUE THREAD

**Issue by AzherAleem** [aws-amplify/amplify-cli#6547]
**Is your feature request related to a problem? Please describe.**
I have an s3 bucket created via Amplify Storage command and I've added a lambda trigger on the put operation. I am uploading content(video & Images) in the s3 bucket with level as 'protected' as per the amplify documentation: 

[](https://docs.amplify.aws/lib/storage/download/q/platform/js#file-access-levels)

As per the documentation in protected and private level the content is saved in a hierarchy level as protected/{user_identity_id}/ for the protected level.
I am storing images as protected/{user_identity_id}/images and videos in protected/{user_identity_id}/videos subfolder respectively. Since Amplify does not allow creating more than one buckets and I want lambda to trigger only when a video is uploaded protected/{user_identity_id}/videos folder. So, I am trying to add a prefix for the lambda trigger notification but I do not know how to specify 'user_identity_id' as it will be unique for each user. I have tried specifying 'videos/' but it did not trigger.

**Describe the solution you'd like**
I'd like to either just have videos/ specified and have the trigger even when a subfolder name is specified or have a way to specify the complete path as a prefix 'protected/{user_identity_id}/videos' but 'user_identity_id' value can be replaced with a known placeholder.

**Describe alternatives you've considered**
I have tried to add suffix instead like '.mp4' however, I found out that I cannot add multiple suffixes for one notification and will have to create multiple event notifications for each suffix like separate for .mp4, .mkv, etc which I would not prefer.

**Comment by rajrajhans** [comment]
According to [this](https://aws.amazon.com/premiumsupport/knowledge-center/s3-event-notification-filter-wildcard/) and [this](https://stackoverflow.com/questions/33107809/using-a-wildcard-on-s3-event-notification-prefix), wildcards are not supported in prefix/suffix rules, since asterisk character (*) is a valid character that can be used in object key names, Amazon S3 literally interprets the asterisk as a prefix or suffix filter.

Also, something like `'/protected/${cognito-identity.amazonaws.com:sub}/videos/'` in the `Value` of `FilterRule` is also interpreted literally, instead of `${cognito-identity.amazonaws.com:sub}` resolving to the respective Cognito Identity ID. 

>  I want lambda to trigger only when a video is uploaded to protected/{user_identity_id}/videos folder

One workaround using which I was able to achieve this is by removing the filter from my s3 cloudformation template and having a kind of a filter <i>within</i> the lambda function by checking the object key -

```js
exports.handler = function (event, context) {
  const key = event.Records[0].s3.object.key;

  if (key.includes("/videos/")) {
    // do things with the uploaded video here
  } 
};
```

It isn't ideal, but it gets the job done. Alternative to this would be, as you mentioned, to add multiple event notifications for each suffix.

**Comment by AzherAleem** [comment]
@rajrajhans I have these two workarounds as well. I guess the wild card isn't supported yet. 
But thanks for your help.

**Comment by anishagg17** [comment]
Isn't `prefix` still added to amplify storage trigger?

**Comment by AzherAleem** [comment]
> Isn't `prefix` still added to amplify storage trigger?

It was already there from the start but if you look at the issue statement again, I was trying have the prefix trigger on {user_identity_id} which is dynamically created for protected level in s3 for amplify.

**Comment by anishagg17** [comment]
Thanks a lot of clarification @AzherAleem, I could not find how to trigger with prefix in docs. Could you please share any link so that I can observe?

**Comment by AzherAleem** [comment]
> Thanks a lot of clarification @AzherAleem, I could not find how to trigger with prefix in docs. Could you please share any link so that I can observe?

For a documentation reference you can explore:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html

And this is how it might look like in your cfn script(Example of how I implemented this):

```

"NotificationConfiguration": {
                    "LambdaConfigurations": [
                        {
                            "Event": "s3:ObjectCreated:*",
                            "Filter": {
                                "S3Key": {
                                    "Rules": [
                                        {
                                            "Name": "prefix",
                                            "Value": "FOLDER_NAME_GOES_HERE"
                                        }
                                    ]
                                }
                            },
                            "Function": {
                                "Ref": "FUNCTION_NAME_GOES_HERE"
                            }
                        },
                        {
                            "Event": "s3:ObjectCreated:Put",
                            "Filter": {
                                "S3Key": {
                                    "Rules": [
                                        {
                                            "Name": "prefix",
                                            "Value": "FOLDER_NAME_GOES_HERE"
                                        }
                                    ]
                                }
                            },
                            "Function": "YOUR_LAMDA_ARN_GOES_HERE"
                        }

                    ]
                }
            }
```

**Comment by anishagg17** [comment]
@AzherAleem thanks, but this is AWS cloudformation script. Where to add this to an amplify project?

**Comment by AzherAleem** [comment]
> @AzherAleem thanks, but this is AWS cloudformation script. Where to add this to an amplify project?

If you have an amplify project already set up then you can go to amplify->backend->storage->YOURS3RESOURCENAME->s3-cloudformation-template.json

This is where you will find your cfn script for you added amplify s3 storage.

**Comment by anishagg17** [comment]
> If you have an amplify project already set up then you can go to amplify->backend->storage->YOURS3RESOURCENAME->s3-cloudformation-template.json
> 
> This is where you will find your cfn script for you added amplify s3 storage.

Thanks for letting me know 🤗

**Comment by AzherAleem** [comment]
> > If you have an amplify project already set up then you can go to amplify->backend->storage->YOURS3RESOURCENAME->s3-cloudformation-template.json
> > This is where you will find your cfn script for you added amplify s3 storage.
> 
> Thanks for letting me know 🤗

No worries. Do leave a thumbs up if it helped. :)
