### ISSUE TITLE
How to return user specific subfield on the list query?

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#655]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync, User Pools

** Provide additional details e.g. code snippets **

I have set the following GraphQL schema:
```
type BookEntity @model @searchable {
  id: ID!
  content: String!
  bookmarks: [BookEntityBookmark] @connection(name: "BookEntityBookmarks")
}

type BookEntityBookmark
  @model(queries: null)
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "owner"
        mutations: [create, update, delete]
        queries: [get, list]
      }
    ]
  ) {
  id: ID!
  bookEntity: BookEntity! @connection(name: "BookEntityBookmarks")
  bookmark: Bookmark! @connection(name: "BookmarkBookEntityBookmarks")
  owner: String
}

type Bookmark @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  bookEntitys: [BookEntityBookmark!]!
    @connection(name: "BookmarkBookEntityBookmarks")
  owner: String
}
```

Now, when I query `BookEntity` as `query listBookEntitys`, I want `listBookEntitys.bookmarks` to return only currently logged in user's bookmarks. At the moment, however, I see bookmarks of all users.

What am I doing wrong?

**Comment by nikhname** [comment]
@sakhmedbayev can you expand on what you mean by logged in users? It is not clear from your schema.

**Comment by nikhname** [comment]
@sakhmedbayev could you update to the latest version of the CLI (3.17.0) and see if you are still unable see the logged in users?

**Comment by sakhmedbayev** [comment]
Thanks! No longer relevant.
