### ISSUE TITLE
import auth when Unauthenticated role is not assigned

### ISSUE THREAD

**Issue by imers** [aws-amplify/amplify-cli#6552]
**Describe the bug**
Unauthenticated role in identity pool could be empty. However when it's empty, "import auth" would pop up error: 
_Cannot parse arn: 'undefined'.
Error: Cannot parse arn: 'undefined'._

**Amplify CLI Version**
4.41.2

**To Reproduce**
amplify import auth

**Expected behavior**
Explain why it cannot process or ignore the Unauthenticated role when it's empty.

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: v14.15.4

**Comment by kaustavghosh06** [comment]
@imers For the CLI to work correctly with other categories in the CLI when importing auth - we need an unauth role defined tied to the imported cognito identity pool. That's a requirement for now.
