### ISSUE TITLE
Sorting on createdAt and updatedAt in search query results in 0 results returned when records are expected

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#6553]
**Describe the bug**
Sorting a search query from `@searchable` on the type with a sort field of updatedAt or createdAt results in 0 results when fields are populated with data. 

**Amplify CLI Version**
4.41.2

**To Reproduce**
1. create a type with `@searchable` 
2. push
3. run query from front end or appsync with no sort and see results
4. add sort for updatedAt or createdAt and see no results (other fields work)

**Expected behavior**
Get search results sorted 

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: v12.13.0

**Additional context**
this works in the appsync console as expected: 

```gql
query {
  searchAccounts(sort: {direction: desc, field: id}, limit: 20) {
    items {
      id
      createdAt
      updatedAt
    }
  }
}
```

this does not return any results (createdAt or updatedAt):
```gql
query {
  searchAccounts(sort: {direction: desc, field: createdAt}, limit: 20) {
    items {
      id
      createdAt
      updatedAt
    }
  }
}
```

createdAt and updateAt are not marked required in the schema but i can see the fields are populated.

**Comment by jhockett** [comment]
Hi @kldeb, can you share your schema so we can try reproducing this?

**Comment by kldeb** [comment]
@jhockett sure, can I share it with you privately somehow?

**Comment by jhockett** [comment]
Certainly, you can send it to amplify-cli@amazon.com. Please include the issue number in the subject.

**Comment by kldeb** [comment]
@jhockett sent, thanks

**Comment by jhockett** [comment]
@kldeb I was able to reproduce the issue. Thank you for the bug report and for providing your schema!

**Comment by jhockett** [comment]
When I changed the type of `createdAt` and `updatedAt` to `AWSDateTime` it worked as expected.

**Comment by kldeb** [comment]
@jhockett Thanks! That works.
