### ISSUE TITLE
Example of mocking function with post method

### ISSUE THREAD

**Issue by unclejustin** [aws-amplify/amplify-cli#6556]
**Which Category is your question related to?**

Mocking functions

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.41.2

**What AWS Services are you utilizing?**

Functions

**Provide additional details e.g. code snippets**

This site: https://docs.amplify.aws/cli/restapi/testing#test-the-api-with-amplify-mock has an example json for GET requests but nothing for POST.

Need the correct syntax for testing POST data.

Examples:

This throws a 500 error

```
{
  "httpMethod": "POST",
  "path": "/test",
  "body": {
    "test": "true"
  }
}
```

This returns and empty `req.body`

```
{
  "httpMethod": "POST",
  "path": "/test",
  "body": "{ \"test\": \"test\" }"
}
```

**Comment by edwardfoyle** [comment]
@unclejustin The second payload you have is correct, you just need to set the content type to "application/json":
```
{
    "httpMethod": "POST",
    "path": "/test",
    "headers": {
        "content-type": "application/json"
     },
    "body": "{ \"test\": \"test\" }",
}
```
Details on the API Gateway event can be found here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
