### ISSUE TITLE
Amplify push not updating cloud resources with GraphQL API auth changes

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-cli#6557]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Some auth settings on my GraphQL schema are not generated correctly in the AppSync schema after a push. We have 2 AWS accounts (dev and prod), which both had just a recent deploy from the AWS Amplify console (set to track the `master` branch on our repo).

The autogenerated schemas that are displayed in the AppSync console are different. Some types are missing the @aws_iam tag, which is messing up the database access.

The only reason I can think of is that the master deploy was done from a different starting point on both accounts. Funny enough, both of them (prod and dev) are missing the tag in different places,  which makes me think that depending on the starting point, they skipped some changes.

The missing changes are:

- prod account: `type S3Object`,that is not a model, is not inheriting the `@aws_iam` tag when added as a field on a model that has it
- dev account: a model with auth rule `{ allow: owner, operations: [create, delete, update] }` use to also have `{ allow: private, operations: [read], provider: iam }`. The last was removed but the update is not showing up, which makes the `others` read operation invalid

I tried to add some changes on both environments and perform an `amplify push`, with no luck. Also redeployed `master` through the console. Something is making the auth changes to not be reflected in the schema. I even tried to add and revert the `{ allow: private, provider: iam }` lines, no luck.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Add the a schema type `{ allow: private, provider: iam }` to the auth rules (which already are `@auth(rules: [{ allow: owner }])` and deploy the changes.

**Expected behavior**
AppSync should reflect the schema changes after an amplify push

**Desktop (please complete the following information):**

- OS: `macOS Catalina 10.15.7`
- Node Version: `v15.7.0`

**Comment by kaustavghosh06** [comment]
@wvidana For the issue with your dev account - if you choose IAM as your default auth type - and if that's the only auth type is use then the generated AppSync schema doesn't need to have the @aws_iam directly set to it - the types are auto-protected by the default auth type which would be IAM in your case.

For the type S3Object, I don't believe we inherit the auth tag from the parent model. If you'd like - you can explicitly specify @aws_iam on that type and the CLI/GraphQL transformer will passthrough that directive to the generated output AppSync schema.

**Comment by wvidana** [comment]
Hi @kaustavghosh06, thanks for getting back so quickly!

Our default auth type is Cognito. We configured IAM as the secondary because we need to run DB operations from Lambda functions. We created both schemas from the same code, just pushed through `amplify push` at different times.

I believe this PR added the auth handle propagation for nested types https://github.com/aws-amplify/amplify-cli/pull/3223 , so it **should** be supported.

Furthermore, we realized that the order we declare the types in the schema affects this. For example, if we place `S3Object` after the model that uses it, it will correctly inherit the `@aws_iam` handle, but it doesn't if it is declared before it. This gets a bit more difficult to control when using several files in a `schema` folder.

**Comment by kaustavghosh06** [comment]
@wvidana We merged #3223 but I don't believe it's a part of our latest NPM release. We're working on a release to NPM as we speak. Once we have the release out, you'd be able to propagate auth for nested types.

We'll investigate on the ordering issue.

**Comment by wvidana** [comment]
@kaustavghosh06 that PR was merged more than a year ago, I do believe it is part of the NPM release.

### Issue on auth tags for nested types
The issue is that the order of the models in the schema affects how the code is generated in the cloud.

For example, having default auth as Cognito and secondary is IAM, with the following code
```graphql
type Button @model @auth(rules: [{allow: owner}]) {
  image: S3Object
}

type User @model @auth(rules: [{allow: owner}, {allow: private, provider: iam}]) {
  profile_pic: S3Object
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```

The generated `S3Object` schema won't have IAM permissions, but if we change the order and place `User` before `Button`, it will correctly inherit the permissions and be generated with the auth tags like `@aws_cognito_user_pools @aws_iam`


### Issue on auth tags for model types
The other issue is that some models will wrongly get the `@aws_cognito_user_pools @aws_iam` tag when they shouldn't. It seems to be also related with the type order (like if the first models have IAM permissions then everyone gets the `@aws_iam` tag.

This seems to be happening on Amplify 4.41.2, but reverting to 4.36.2 fixes it

**Comment by SwaySway** [comment]
@wvidana We had a PR to address recursive types. Looks like it's just taking the first auth mode when evaluating `S3Object` for the first time. Labeling this is a bug.
