### ISSUE TITLE
optimal setup for mobile CI/CD pipeline

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-cli#6559]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Continuous Deployment 

**Amplify CLI Version** 

4.41.2

**What AWS Services are you utilizing?**
DataStore, AppSync, DynamoDB, Cognito, 

**Provide additional details e.g. code snippets**
I am about to setup a CI/CD pipeline for our React Native mobile app. My question is what is the optimal way of doing this? We have our build pipe setup my understanding is that I will have to do `amplify pull --appId {appId} --envName prod` as a step before running my tests. My question is:

1) Is this the right approach?
2) Is there a way to update the backend as part of the release? Should I grab the updated code from staging, run amplify pull and amplify push?

Best,

Robert

**Comment by kaustavghosh06** [comment]
@rraczae Your understanding is correct. We provide support for various headless options for CI/CD.
Here are few samples which you can reference:
https://github.com/marketplace
