### ISSUE TITLE
Model connection doesn't respect @auth when model queries are set to null

### ISSUE THREAD

**Issue by adam-nygate** [aws-amplify/amplify-cli#6561]
**Describe the bug**
If you disable query generation on a type (i.e @model(queries: null)), then GQL queries will fail when you try to query for this model via a connection because the generated Model*Connection fails to have the proper auth directives applied.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Example schema:
```gql
type Post 
@model(timestamps:null) 
@auth(rules: [{ allow: public}, { allow: private }]) {
    id: ID!
    title: String!
    comments: [Comment] @connection(keyName: "byPost", fields: ["id"]) @auth(rules: [{ allow: public}, { allow: private }])
}

type Comment 
@model(queries: null, mutations: null, subscriptions: null) 
@key(name: "byPost", fields: ["post_id"])
@auth(rules: [{ allow: public}, { allow: private }]) {
    id: ID!
    post_id: ID!
    body: String!
}
```

run `amplify api gql-compile` in order to see the generated schema.graphql in ./build/

See that ModelCommentConnection does not have the `@aws_api_key @aws_cognito_user_pools` (if Cognito User Pools was set up as an alternative auth method)

**Expected behavior**
I'd like for people to only access Comment via Post.comments, and so disabling Comment queries should allow me to do so without impeding my ability to access Comment via Post.comments.

**Desktop (please complete the following information):**
- OS: Mac
- Node Version: v14.11.0

**Comment by SwaySway** [comment]
Closing as PR #5655 fixes this issue. This fix will be included in the next release.
