### ISSUE TITLE
Will `@connection` cause the "n+1" problem?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6562]
I'm wondering if the `@connection` will have the "n+1" problem.

Similar concern is that if it will cause the "n+1" problem when using `@function` ? for example:
```gql
type Query {
    posts: [Post] @function(name: "GraphQLResolverFunction")
}
type Post {
    id: ID!
    title: String!
    comments: [Comment] @function(name: "GraphQLResolverFunction")
}
type Comment {
    postId: ID!
    content: String
}
```

**Comment by SwaySway** [comment]
Hello @yaquawa 
This is a problem which you can run into in general with GraphQL, `@connection` included.
There are a few ways to leverage this problem in AppSync. Should you use `@function` in this scenario you can use BatchInvoke: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html#advanced-use-case-batching

Additionally you can also cache the response: https://docs.aws.amazon.com/appsync/latest/devguide/enabling-caching.html

**Comment by yaquawa** [comment]
@SwaySway Thanks for the doc link, it helps. 
I posted a feature request on this topic
https://github.com/aws-amplify/amplify-cli/issues/6649
