### ISSUE TITLE
env checkout xxx removes secrets from deployment-secrets.json

### ISSUE THREAD

**Issue by ahtokca** [aws-amplify/amplify-cli#6563]
**Describe the bug**

**Amplify CLI Version**
I had 2 environment tst and dev with version 2.28.2. After migration to 2.41.2 auth secrets were migrated to deployment-secrets.json. However up on switching with `amplify env checkout xxx` between environment the secrets disappeared from deployment-secrets.json

**To Reproduce**
1. the secrets for both envs are in deployment-secrets.json
2. amplify checkout env tst => secrets of dev is removed from deployment-secrets.json

**Expected behavior**
never ever remove stuff from deployment-secrets.json

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: 15.7.0 / 14.15.5

**Log output**
[amplify-cli-2021-02-06.log](https://github.com/aws-amplify/amplify-cli/files/5937210/amplify-cli-2021-02-06.log)

**Comment by ahtokca** [comment]
any feedback? It happened again. it screws my deployment secrets pretty much on every checkout.  now with 4.44.0 too

**Comment by PawanKolhe** [comment]
@ahtokca `deployment-secrets.json` is a generated file. So if you added anything to it manually, it will get overridden when changing environments. Could you confirm if you edited `deployment-secrets.json` manually or through the CLI?

To modify deployment secrets through Amplify CLI you could use `amplify auth update`.

**Comment by ahtokca** [comment]
@PawanKolhe,

I do `amplify env checkout xxx` when I see that auth secret got removed. After secrets are removed it is not possible to do `amplify push` anymore. Since the requried params are not passed to auth. The whole deployment is broken. 

Mind the case when a person may have several amplify projects under the same user / same computer.

Personally removing secrets sounds really bad even if you put them manually. I'd expect this file is used to keep sensitive data same way as ~/.aws/credentials. I never seen aws removes anything from ~/.aws/credentials. I'd really appreciate if amplify will follow the same pattern and ~/.aws/amplify/deployment-secrets.json will be used in 'append-only' mode

**Comment by PawanKolhe** [comment]
@ahtokca I wanted to ask, what process do you follow to add the deployment secrets to deployment-secrets.json at the moment? Do you use the CLI's `amplify auth update` command or manually edit the file?

**Comment by ahtokca** [comment]
@PawanKolhe, no  I don't change it manually, besides I have to restore it when secrets are removed

**Comment by PawanKolhe** [comment]
@ahtokca Ah okay. So you actually don't need to restore deployment secrets in `deployment-secrets.json` once they have been initially pushed with `amplify push` or `amplify publish`. Amplify clears the deployment secrets from `deployment-secrets.json` because they are not needed on consecutive pushes and could be a security risk if they remain there. 

If you ever need to change the deployment secrets in the cloud, you'll need to use the Amplify CLI and run `amplify auth update` and walk through the prompts as shown below, which would add the deployment secrets to the `deployment-secrets.json` file and will be preserved even on checking out to different environments. But once you run `amplify push` they will be updated in the cloud and cleared from `deployment-secrets.json` forever:

![Capture](https://user-images.githubusercontent.com/8324407/109194378-5b59c200-77bf-11eb-96cf-02fa5ba24904.PNG)

**Comment by ahtokca** [comment]
@PawanKolhe Well. That sounds good. However `amplify push` fails with auth update if I don't have deployment secrets for env I'm pushing against.

**Comment by PawanKolhe** [comment]
@ahtokca Interesting. Could you provide the error message if possible for when `amplify push` fails with auth update. That would be helpful for debugging.

**Comment by ahtokca** [comment]
@PawanKolhe  Here is the fresh failure

```
UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                                   Custom::LambdaCallout      Thu Mar 04 2021 20:47:52 GMT+0100 (Central European Standard Time) Failed to update resource. See the details in CloudWatch Log Stream: 2021/03/04/[$LATEST]a746b6b3a91c45efbc55ad174f4db67b
```

**Comment by ngocketit** [comment]
> @PawanKolhe Here is the fresh failure
> 
> ```
> UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                                   Custom::LambdaCallout      Thu Mar 04 2021 20:47:52 GMT+0100 (Central European Standard Time) Failed to update resource. See the details in CloudWatch Log Stream: 2021/03/04/[$LATEST]a746b6b3a91c45efbc55ad174f4db67b
> ```

Got the same issue and Cloudwatch logs shows:
```
2021-03-08T16:01:05.596Z	d72bbecd-bf0e-4f47-9308-98b77f32bac9	INFO	TypeError: Cannot read property 'client_id' of undefined
    at getRequestParams (/var/task/index.js:1:1053)
    at updateIdentityProvider (/var/task/index.js:1:1635)
    at hostedUIProviderMeta.forEach (/var/task/index.js:1:2373)
    at Array.forEach (<anonymous>)
    at identity.listIdentityProviders.promise.then (/var/task/index.js:1:2249)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
then I emptied `appSecrets` in `~/.aws/amplify/deployment-secrets.json`, put the secrets in the `team-provider-info.json` again, ran `amplify push`, chose `yes` to migrate to `deployment-secrets.json` and it worked.

**Comment by ianmartorell** [comment]
Exact same issue and resolution as @ngocketit, I wish I had found this thread an hour earlier 😅

**Comment by dallinwright** [comment]
For me when I do this, the file is never created even though it says:

`? Amplify has been upgraded to handle secrets more securely by migrating some values in team-provider-info.json to deployment-secrets.json
You can create a back up of the team-provider-info.json file before proceeding. Yes
Successfully updated auth resource locally.`

The provider json had the values removed, but migration never took place. on `amplify --version
4.45.2`

**Comment by ammarkarachi** [comment]
@dallinwright The issue seemed to stem from credentials not being updated on new env can you try with the latest version and see if you are still facing this issue?
