### ISSUE TITLE
Select Elastic Search Version

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#6564]
To encourage upgrading to newer versions of elastic search we should be able to set which version our codebase uses. We should default to newest version in new code-bases.

transform.conf.json should have a "ElasticSearchVersion":"xx"

There should also be an upgrade path from older versions to newer versions.

#5229 for details on upgrading.

I would also think moving elastic search config from CustomResources.json to an ElasticSearch.json file would help with discoverability...

**Comment by SwaySway** [comment]
Thanks for the enhancement request @GeorgeBellTMH 
I do think we can also looking into adding a version parameter for the directive itself as this is something different than a cloud instance change such as [AWS Elasticsearch Configureable Parameters](https://docs.amplify.aws/cli/graphql-transformer/config-params#elasticsearchstreamingfunctionname)

Closing in favor of #5229 so we can track this enhancement in one issue.
