### ISSUE TITLE
Project delete failed - Access Denied when running amplify delete

### ISSUE THREAD

**Issue by nathanagez** [aws-amplify/amplify-cli#6566]
**Describe the bug**
When I try to delete the resources by using `amplify delete` or `amplify delete --force` the following message appears:

![amplify delete screenshot](https://user-images.githubusercontent.com/7148684/107236586-219a6480-6a26-11eb-93c0-72508644b5d6.png)

It looks like that this is related to the S3 policies (https://docs.amplify.aws/cli/usage/iam#n3-set-up-the-local-development-environment-dev-corp). Also, I can see on the AWS Console that the S3 bucket is not deleted.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Create a new user on the AWS console and attach the [IAM policies](https://docs.amplify.aws/cli/usage/iam#n3-set-up-the-local-development-environment-dev-corp) taken from the documentation and run:

`amplify init`
then select the user you created with the IAM policies mentioned above.
`amplify delete`

**Expected behavior**
Delete the resources deployed in the cloud (S3 Bucket).

**Desktop (please complete the following information):**

- OS: macOS 11.1 (20C69)
- Node Version: v12.16.3

**Additional context**
It looks like that the issue is related to the S3 policies, when I replace all S3 policies by `s3:*` it works as expected, but I don't know which policy is missing.

Also, when I use the AWS CLI to delete the S3 bucket `aws s3 rb s3://bucket-name --force` the bucket is successfully deleted (using the same profile used for amplify-cli).

**Comment by SwaySway** [comment]
@nathanagez Is the amplify cli using the same profile as the aws cli?

**Comment by kaustavghosh06** [comment]
@nathanagez There is one additional S3 IAM policy which was missing in our docs - which we just added as a part of this PR-https://github.com/aws-amplify/docs/pull/2924/files I'm suspecting that was the S3 IAM policy missing.
Closing this issue (please let us know if you see this issue again in the future with the additional S3 policy) and thanks for bringing this up.

**Comment by nathanagez** [comment]
> @nathanagez There is one additional S3 IAM policy which was missing in our docs - which we just added as a part of this PR-https://github.com/aws-amplify/docs/pull/2924/files I'm suspecting that was the S3 IAM policy missing.
> Closing this issue (please let us know if you see this issue again in the future with the additional S3 policy) and thanks for bringing this up.

@kaustavghosh06 thank you for your reply, I added the missing policy but now I have another error:

![The bucket you tried to delete is not empty](https://user-images.githubusercontent.com/7148684/107341670-8fdf3580-6abf-11eb-82c7-f62f427509b7.png)

**Comment by nathanagez** [comment]
@SwaySway  @kaustavghosh06
