### ISSUE TITLE
Having issues creating a layer and assigning it to a function

### ISSUE THREAD

**Issue by patrickliechty** [aws-amplify/amplify-cli#6575]
In version 4.41.2 on Windows 10, I create a layer.  I switch to the opt folder and run npm install for each of the libs I want.  They do not get installed. I see them getting installed in my project package.json.  I don't see any package.json in the opt folder.

As well when I go to add a new function, the layer I just added is not available to select in the amplify function add.

I tried downgrading to 4.40.1 following the instructions of AWS support.  I created a new project and tried all of it again and it didn't help.

I also tried an amplify push in my original project above and I was not able to push the function or layer.  Here are the errors from the push:

C:\Users\Patrick Liechty\sandbox\clarifyPhaseTwo>amplify push
√ Successfully pulled backend environment test from the cloud.

Current Environment: test

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Function | manylibs2       | Create    | awscloudformation |
| Function | addCCFaf43234   | Create    | awscloudformation |
| Auth     | clarify694880c2 | No Change | awscloudformation |

Tag Changes Detected
? Are you sure you want to continue? Yes
Content changes in Lambda layer manylibs2 detected. Layer version increased to 2
Note: You need to run "amplify update function" to configure your functions with the latest layer version.
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS functionaddCCFaf43234       AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Resource creation Initiated
UPDATE_FAILED      authXXXXXXX         AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, allowUnauthenticatedIdentities, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, sharedId, useDefault, userpoolClientGenerateSecret, mfaConfiguration, identityPoolName, userPoolGroupList, authSelections, resourceNameTruncated, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, resourceName, serviceName, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, requiredAttributes, passwordPolicyCharacters, userpoolClientLambdaRole, defaultPasswordPolicy] must have values
UPDATE_IN_PROGRESS authXXXXXXX         AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:23 GMT-0700 (Mountain Standard Time)
CREATE_IN_PROGRESS functionaddCCFaf43234       AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:23 GMT-0700 (Mountain Standard Time)
CREATE_IN_PROGRESS functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:23 GMT-0700 (Mountain Standard Time)
UPDATE_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:19 GMT-0700 (Mountain Standard Time) User Initiated
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-clarify-test-165214-functionaddCCFaf43234-1NY9KOZTE8Z3A AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) User Initiated
\ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-clarify-test-165214-functionmanylibs2-D2FQL7O7NE23 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) User Initiated
/ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED functionaddCCFaf43234 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Resource creation cancelled
CREATE_FAILED functionmanylibs2     AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Resource creation cancelled
\ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:25 GMT-0700 (Mountain Standard Time) The following resource(s) failed to create: [functionaddCCFaf43234, functionmanylibs2]. The following resource(s) failed to update: [authXXXXXXX].
/ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Tue Feb 09 2021 10:25:29 GMT-0700 (Mountain Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Tue Feb 09 2021 10:25:28 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      LambdaLayerPermissionprivate1 AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 10:25:29 GMT-0700 (Mountain Standard Time) Layer version arn:aws:lambda:us-west-2:501560897171:layer:manylibs2-test:1 does not exist. (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: e7c97893-66ce-481d-b8e6-06e731123a5b)
CREATE_IN_PROGRESS LambdaLayer                   AWS::Lambda::LayerVersion           Tue Feb 09 2021 10:25:28 GMT-0700 (Mountain Standard Time)                                              
CREATE_IN_PROGRESS LambdaLayerPermissionprivate1 AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 10:25:28 GMT-0700 (Mountain Standard Time)                                              
- Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS                           functionaddCCFaf43234       AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time)
DELETE_IN_PROGRESS                           functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:32 GMT-0700 (Mountain Standard Time)
UPDATE_COMPLETE                              authXXXXXXX        AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:31 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS amplify-clarify-test-165214-functionaddCCFaf43234-1NY9KOZTE8Z3A AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time) User Initiated

DELETE_IN_PROGRESS amplify-clarify-test-165214-functionmanylibs2-D2FQL7O7NE23 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time) User Initiated           
CREATE_FAILED      amplify-clarify-test-165214-functionmanylibs2-D2FQL7O7NE23 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:33 GMT-0700 (Mountain Standard Time) The following resource(s) failed to create: [LambdaLayer, LambdaLayerPermissionprivate1].
CREATE_FAILED      LambdaLayer                                                AWS::Lambda::LayerVersion  Tue Feb 09 2021 10:25:33 GMT-0700 (Mountain Standard Time) Resource creation cancelled
- Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE authclarify694880c2 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED LambdaExecutionRole AWS::IAM::Role Tue Feb 09 2021 10:25:34 GMT-0700 (Mountain Standard Time) Resource creation cancelled
| Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-clarify-test-165214-functionmanylibs2-D2FQL7O7NE23 AWS::CloudFormation::Stack          Tue Feb 09 2021 10:25:37 GMT-0700 (Mountain Standard Time)
DELETE_COMPLETE LambdaLayerPermissionprivate1                              AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 10:25:36 GMT-0700 (Mountain Standard Time)
DELETE_SKIPPED  LambdaLayer                                                AWS::Lambda::LayerVersion           Tue Feb 09 2021 10:25:36 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE functionmanylibs2 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:45 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Tue Feb 09 2021 10:25:48 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-clarify-test-165214-functionaddCCFaf43234-1NY9KOZTE8Z3A AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:51 GMT-0700 (Mountain Standard Time)
DELETE_COMPLETE LambdaExecutionRole                                             AWS::IAM::Role             Tue Feb 09 2021 10:25:50 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:56 GMT-0700 (Mountain Standard Time)
DELETE_COMPLETE          functionaddCCFaf43234       AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:56 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
- Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: LambdaLayerPermissionprivate1 (AWS::Lambda::LayerVersionPermission)
Event Type: create
Reason: Layer version arn:aws:lambda:us-west-2:501560897171:layer:manylibs2-test:1 does not exist. (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: e7c97893-66ce-481d-b8e6-06e731123a5b)

Resource Name: arn:aws:lambda:us-west-2:501560897171:layer:manylibs2:1 (AWS::Lambda::LayerVersion)
Event Type: create
Reason: Resource creation cancelled

Resource Name: clarifyLambdaRolef226cace (AWS::IAM::Role)
Event Type: create
Reason: Resource creation cancelled

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

**Comment by jhockett** [comment]
Hi @patrickliechty. The /opt folder is intended for static assets. For the node runtime, navigate to `amplify/backend/function/<layer-name>/lib/nodejs/` and then install your modules.

This looks unrelated to the failed push though:

>UPDATE_FAILED authXXXXXXX AWS::CloudFormation::Stack Tue Feb 09 2021 10:25:24 GMT-0700 (Mountain Standard Time) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, allowUnauthenticatedIdentities, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, sharedId, useDefault, userpoolClientGenerateSecret, mfaConfiguration, identityPoolName, userPoolGroupList, authSelections, resourceNameTruncated, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, resourceName, serviceName, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, requiredAttributes, passwordPolicyCharacters, userpoolClientLambdaRole, defaultPasswordPolicy] must have values

**Comment by patrickliechty** [comment]
Ok, I was looking for that folder. The documentation said it would be there, but that folder you mention /lib/nodejs did not created.

**Comment by jhockett** [comment]
@patrickliechty when you created the layer, did you make sure NodeJS was a selected option? You have you press the space bar to select a choice.

**Comment by patrickliechty** [comment]
Ok I did not select NodeJS as you said.  A few of the issues have gone away since I selected it in the layer.  I was able to create the layer. The lib\nodejs folder is there now.  I am using version 4.40.1 when I tested.  I was able to see the layer when creating a new function.  But I still get an error when I do an amplify push.  Here is the error:


C:\Users\Patrick Liechty\sandbox\clarifyPhaseTwo>amplify push
√ Successfully pulled backend environment test from the cloud.

Current Environment: test

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Function | manylibs2       | Create    | awscloudformation |
| Function | addCCFEnv       | Create    | awscloudformation |
| Auth     | XXXXXXXX| No Change | awscloudformation |
? Are you sure you want to continue? Yes
| Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Resource creation cancelled                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
UPDATE_FAILED      UnauthRole                  AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Resource update cancelled                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
UPDATE_FAILED      AuthRole                    AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Resource update cancelled                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
UPDATE_FAILED      DeploymentBucket            AWS::S3::Bucket            Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Resource update cancelled                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
UPDATE_FAILED      XXXXXXXX         AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Parameters: [authRoleArn, usernameAttributes, autoVerifiedAttributes, allowUnauthenticatedIdentities, smsVerificationMessage, userpoolClientReadAttributes, mfaTypes, emailVerificationSubject, sharedId, useDefault, userpoolClientGenerateSecret, mfaConfiguration, identityPoolName, userPoolGroupList, authSelections, resourceNameTruncated, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, resourceName, serviceName, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, unauthRoleArn, requiredAttributes, passwordPolicyCharacters, userpoolClientLambdaRole, defaultPasswordPolicy] must have values
CREATE_IN_PROGRESS functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Resource creation Initiated                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CREATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Did not have IAM permissions to process tags on AWS::IAM::Role resource.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
CREATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) Did not have IAM permissions to process tags on AWS::IAM::Role resource.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
UPDATE_IN_PROGRESS DeploymentBucket            AWS::S3::Bucket            Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UPDATE_IN_PROGRESS XXXXXXXX         AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UPDATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UPDATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
CREATE_IN_PROGRESS functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:56 GMT-0700 (Mountain Standard Time)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UPDATE_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:52 GMT-0700 (Mountain Standard Time) User Initiated                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-clarify-test-165214-functionmanylibs2-1VIWFT2ZRW5OZ AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:57 GMT-0700 (Mountain Standard Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 22:09:58 GMT-0700 (Mountain Standard Time) The following resource(s) failed to create: [functionmanylibs2]. The following resource(s) failed to update: [authclarify694880c2, AuthRole, DeploymentBucket, UnauthRole].
/ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaLayer AWS::Lambda::LayerVersion Tue Feb 09 2021 22:10:02 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaLayer AWS::Lambda::LayerVersion Tue Feb 09 2021 22:10:10 GMT-0700 (Mountain Standard Time) Resource creation Initiated
| Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:12 GMT-0700 (Mountain Standard Time)
UPDATE_COMPLETE                              XXXXXXXX         AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:11 GMT-0700 (Mountain Standard Time)
UPDATE_COMPLETE                              AuthRole                    AWS::IAM::Role             Tue Feb 09 2021 22:10:10 GMT-0700 (Mountain Standard Time)
UPDATE_COMPLETE                              UnauthRole                  AWS::IAM::Role             Tue Feb 09 2021 22:10:10 GMT-0700 (Mountain Standard Time)
UPDATE_COMPLETE                              DeploymentBucket            AWS::S3::Bucket            Tue Feb 09 2021 22:10:10 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS LambdaLayerPermissionprivate1 AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 22:10:12 GMT-0700 (Mountain Standard Time)
CREATE_COMPLETE    LambdaLayer                   AWS::Lambda::LayerVersion           Tue Feb 09 2021 22:10:10 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    XXXXXXXX AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:13 GMT-0700 (Mountain Standard Time)
DELETE_IN_PROGRESS functionmanylibs2   AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:13 GMT-0700 (Mountain Standard Time)
/ Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS amplify-clarify-test-165214-functionmanylibs2-1VIWFT2ZRW5OZ AWS::CloudFormation::Stack          Tue Feb 09 2021 22:10:14 GMT-0700 (Mountain Standard Time) User Initiated 
CREATE_COMPLETE    LambdaLayerPermissionprivate1                               AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 22:10:13 GMT-0700 (Mountain Standard Time)                
CREATE_IN_PROGRESS LambdaLayerPermissionprivate1                               AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 22:10:13 GMT-0700 (Mountain Standard Time) Resource creation Initiated
| Updating resources in the cloud. This may take a few minutes...

DELETE_IN_PROGRESS LambdaLayerPermissionprivate1 AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 22:10:38 GMT-0700 (Mountain Standard Time)
| Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE amplify-clarify-test-165214-functionmanylibs2-1VIWFT2ZRW5OZ AWS::CloudFormation::Stack          Tue Feb 09 2021 22:10:40 GMT-0700 (Mountain Standard Time)
DELETE_SKIPPED  LambdaLayer                                                 AWS::Lambda::LayerVersion           Tue Feb 09 2021 22:10:40 GMT-0700 (Mountain Standard Time)
DELETE_COMPLETE LambdaLayerPermissionprivate1                               AWS::Lambda::LayerVersionPermission Tue Feb 09 2021 22:10:39 GMT-0700 (Mountain Standard Time)
- Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-clarify-test-165214 AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:48 GMT-0700 (Mountain Standard Time)
DELETE_COMPLETE          functionmanylibs2           AWS::CloudFormation::Stack Tue Feb 09 2021 22:10:48 GMT-0700 (Mountain Standard Time)
\ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack


Following resources failed

Resource Name: amplify-clarify-165214-unauthRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A501560897171%3Astack%2Famplify-clarify-test-165214%2F6087d750-4608-11eb-aa8f-06945ba32212/events


Resource Name: amplify-clarify-165214-authRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A501560897171%3Astack%2Famplify-clarify-test-165214%2F6087d750-4608-11eb-aa8f-06945ba32212/events


Resource Name: amplify-clarify-165214-deployment (AWS::S3::Bucket)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A501560897171%3Astack%2Famplify-clarify-test-165214%2F6087d750-4608-11eb-aa8f-06945ba32212/events


× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

**Comment by patrickliechty** [comment]
I was able to get passed the issue by renaming my amplify folder. I then did an amplify pull to get synced up.  I added my function and layer again and did a push.  It worked this time.
