### ISSUE TITLE
enable "amplify storage add" to use existing s3 bucket

### ISSUE THREAD

**Issue by komushi** [aws-amplify/amplify-cli#658]
**Is your feature request related to a problem? Please describe.**
There are multiple amplify apps to share the same s3 bucket contents. It will be nice to have an option of not creating but using an existing bucket.

**Describe the solution you'd like**
It would be very nice to have a feature of using existing s3 bucket.

**Describe alternatives you've considered**
Manually updating s3-cloudformation-template.json now.

**Additional context**

**Comment by dattajoshi** [comment]
Is there any update on this? 
@komushi As an alternate, how did you edit the  s3-cloudformation-template.json? was it through amplify or in the AWS console itself? Can you share the details please

**Comment by komushi** [comment]
@dattajoshi 

I edit the following file.

amplify/backend/storage/<storage-name>/s3-cloudformation-template.json
#### 4-2-1.
Replace every
```
"Ref": "S3Bucket"
```
With
```
"Ref": "bucketName"
```

#### 4-2-2.
Remove every
```
            "DependsOn": [
                "S3Bucket"
            ],

```

#### 4-2-3.
Add
```
        "CreateBucket": {
            "Fn::Equals": [
                "false",
                "true"
            ]
        }
```
Under
```
    "Conditions": {
```

#### 4-2-4.
Add
```
            "Condition": "CreateBucket",
```
Under
```
        "S3Bucket": {
```

**Comment by komushi** [comment]
@kaustavghosh06 

Thanks for setting it as a feature request. What is the situation?
I have met several other cases that needs this feature.

Thanks

**Comment by Adalsteinn95** [comment]
What is the status of this feature? This would be very nice for many cases. 
Especially for projects moving to AWS amplify.

**Comment by WassimErriha** [comment]
This is possibly tracked by #3977 .

**Comment by renebrandel** [comment]
Hi - I'm closing this issue in favor of our RFC: #3977 
In addition, we've already started making progress in this issue with the ability to import existing Cognito resources. Check out our launch announcement here: https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/
