### ISSUE TITLE
DynamoDB Lambda Triggers luck policies for AWS SDK

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6581]
I've followed the doc to created a "DynamoDB Lambda Triggers".
https://docs.amplify.aws/cli/usage/lambda-triggers#dynamodb-lambda-triggers

But the policy lucks actions for using AWS SDK for DynamoDB like these:

```
"dynamodb:GetItem",
"dynamodb:Query",
"dynamodb:Scan",
"dynamodb:PutItem",
"dynamodb:UpdateItem",
"dynamodb:DeleteItem"
```

I don't want to use AppSync to update or delete my DynamoDB items from the Lambda function, I'd rather like to use the SDK directly, because of the `@auth` directive just doesn't allow you do so such actions.

**Comment by SwaySway** [comment]
@yaquawa Adding a Lambda function trigger on a DynamoDB table will run the lambda on an action taken on the dynamodb. This question flow does not grant access to the table. You can add the dynamodb table as a resource to access when running `amplify function update`. 

Could you explain your usecase a bit here? Are you looking at using a lambda function as opposed to a VTL Resolver in AppSync? If so you could look into the `@function` directive to do something like this.

**Comment by yaquawa** [comment]
@SwaySway My usecase is do aggregation calculations. for example,

```gql
type Post {
    id: ID!
    commentsCount: Int
}

type Comment {
    id: ID!
    postID: ID!
}
```

so whenever a new `Comment` was inserted/removed, increment/decrement the corresponding psot's `commentsCount` field.

**Comment by SwaySway** [comment]
The missing step here would be to additionally allow access to the api so it can submit the query operation as well.

Example
```
➜  bookstore git:(rev) ✗ a add function 
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: bookstoreXXX
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Lambda trigger
? What event source do you want to associate with Lambda trigger? Amazon DynamoDB Stream
? Choose a DynamoDB event source option Use API category graphql @model backed DynamoDB table(s) in the current Amplify project
Selected resource bookstore
? Choose the graphql @model(s) Entity

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. api
? Select the operations you want to permit on bookstore Mutation
```

Additionally using this similar thread https://github.com/aws-amplify/amplify-cli/issues/3681 you can also increment the count on a field on the Comment model itself and query that field, using a field resolver in Post.

Closing this issue as it's more of a discussion for that we do recommend our discord server: https://discord.gg/jWVbPfC

Should you have any issues related to function permissions please comment below.
