### ISSUE TITLE
Amplify project with additional API (combining authorized DataStore with public api)

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-cli#6584]
**Which Category is your question related to?**

Hey everyone,

I have an amplify project that uses DataStore for offline scenario. Once users are logged in they can create their own records and sync them across devices so the authentication is set to Cognito User Pools. 

Everything is great, but the app also has a "guest mode". As a guest, I can see some content and information. The problem is, since the authorization is set to Cognito pool and I am using DataStore, I cannot add API_KEY authorized endpoints to my GraphQL api. See related thread here: [DataStore Authorization - combining owner and api_key based methods breaks sync](https://github.com/aws-amplify/amplify-js/issues/7709)

Question: What I ended up doing is creating a separate GraphQL app with AppSync, however now I am having trouble with CI/CD as I cannot just checkout & push. Does this sound right? Any hints/workarounds until support for combining multiple auth types with DataStore becomes available?

Cheers,
Rob

**Amplify CLI Version** 
4.42.0

**What AWS Services are you utilizing?**
DataStore, Auth, AppSync

**Provide additional details e.g. code snippets**
none

**Comment by SwaySway** [comment]
As of now Datastore only works with one GraphQL API which has conflict resolution enabled. 
For potential workarounds you can also discuss this on our discord server: https://discord.com/invite/jWVbPfC
