### ISSUE TITLE
Post confirmation trigger lambda function getting 403 errors when calling API Gateway API

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#6589]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

In brief: post confirmation lambda is not allowed to access a REST API on API Gateway.

[ Use case: We need this because only the REST API gets credentials that contain identityID, which our post confirmation lambda needs to create a new user in DynamoDB... ]. Here's how it shows up:

Created a post-confirmation trigger lambda function via `amplify auth update`, after first having created a REST Api linked to a lambda function. The API is set up to require authentication for both guest and authenticated users and either is allowed only read access to the API.

After the cli sets up the post confirmation lambda, I run an `amplify function update` and give the post confirmation lambda read access to the API in the section where it asks if we want to enable other resources from the project.

The cli sets up an IAM role for the post confirmation lambda.  The Amplify cli also attaches the (seemingly) correct policy for the post confirmation lambda to access the REST API.

Now the test: sign-up a new user. This test fails. The post confirmation lambda gets an error returned from its request from the API. A 403 error

I tried two ways to have the post confirmation lambda call the API: 
1) axios
2) using the AWS sdk's `Service()` call

both failed with a 403 error. The second method gave a bit more info, saying 

              "Missing authentication token"

In the post confirmation lambda logs, I see an error code and message for this, both named "UserLambdaValidationException". There were no logs for the API call, even though that was set-up and tested to work via the console, which tells me the request was rejected before reaching the API.

I thought the Amplify CLI took care of setting up the authentication token for us automatically, even in the case of lambdas accessing cli-generated APIs (I may be wrong on this).

NOTE: when I test the same API from the test link in API-gateway console, it works: it returns a 200 response with the expected payload.

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.42.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

* Add a lambda function that will be doing the work behind a RES API
```
dtal@thing5: amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: getUser
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Serverless ExpressJS function (Integration with API Gateway)

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? Yes
Please edit the file in your editor: /home/dtal/repos/wg9r5td5e.dd.org/amplify/backend/function/getUser/src/app.js
? Press enter to continue 
```
* Here's the code of that lambda (note: this is a temporary lambda we're using to test this issue now):
```javascript
var express = require('express')
var bodyParser = require('body-parser')
var awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')

// declare a new express app
var app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

// Enable CORS for all methods
app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept"
    );
    next();
});

// Remember: these are available to you:
// req.apiGateway.event
// req.apiGateway.context
// req.body - not available on 'get' but avail on 'put', 'post'

app.get("/get-user", function (req, res) {
    if (req.query.postconf) {
        if (req.query.postconf === "15923220-9750-4075-a096-efeedc1dec82") {
            if (req.query.id) {
                console.log("/get-user got id: " + req.query.id);
                var resJson = {
                    statusCode: 200,
                    url: req.url,
                    test: JSON.stringify(req.apiGateway.event)
                };
                res.json(resJson);
            } else {
                res.json({
                    statusCode: 400,
                    url: req.url,
                    error: "err1"
                });
            }
        } else {
            res.json({
                statusCode: 400,
                url: req.url,
                error: "err2"
            });
        }
    } else {
        res.json({
            statusCode: 400,
            url: req.url,
            error: "err3"
        });
    }
});

app.listen(3000, function () {
    console.log("App started");
});

// Export the app object. When executing the application local this
// does nothing. However, to port it to AWS Lambda we will create a
// wrapper around that will load the app from this file
module.exports = app;
```
*  After editing the code, add a REST api for the function
```
Successfully added resource getUser locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/getUser/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud

dtal@thing5: amplify add api
? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: getUser
? Provide a path (e.g., /book/{isbn}): /get-user
? Choose a Lambda source Use a Lambda function already added in the current Amplify project
? Choose the Lambda function to invoke by this path getUser
? Restrict API access Yes
? Who should have access? Authenticated and Guest users
? What kind of access do you want for Authenticated users? read
? What kind of access do you want for Guest users? read
Auth configuration is required to allow unauthenticated users, but it is not configured properly.
Successfully updated auth resource locally.
? Do you want to add another path? No
Successfully added resource getUser locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

dtal@thing5: 
```
* Create a post confirmation lambda
```
dtal@thing5: amplify auth update
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)


 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Create your own module
Successfully added resource ddcff88827PostConfirmation locally.

Next steps:
Check out sample function code generated in <project-dir>/amplify/backend/function/ddcff88827PostConfirmation/src
"amplify function build" builds all of your functions currently in the project
"amplify mock function <functionName>" runs your function locally
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
Successfully added the Lambda function locally
? Do you want to edit your custom function now? Yes
Please edit the file in your editor: /home/dtal/repos/wg9r5td5e.dd.org/amplify/backend/function/ddcff88827PostConfirmation/src/custom.js
? Press enter to continue 
```
* Edit function to use this code
```javascript
const aws = require('aws-sdk');
const axios = require('axios');

aws.config.update({region: process.env.REGION});

const getUserEndpointBaseUrl =
      'https://' + process.env.API_GETUSER_APIID + '.execute-api.' +
      process.env.REGION + '.amazonaws.com/' + process.env.ENV;
const postconf = '15923220-9750-4075-a096-efeedc1dec82';

exports.handler = (event, context, callback) => {
    // axios way of making the API call
    const url = getUserEndpointBaseUrl + '/get-user?id=' +
          event.request.userAttributes.sub + '&postconf=' + postconf;
    axios.get(url).then((response) => {
        const identityId = response.identityId;
        console.log('got identityId: ' + identityId);
        if (identityId) {
            callback(null, event);
        } else {
            callback('no identityId', null);
        }
    }).catch((error) => {
        callback(error, null)
    });
};
```
* Update the post confirmation trigger lambda function to give it access to the API created above
```
dtal@thing5: amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update ddcff88827PostConfirmation
General information
| Name: ddcff88827PostConfirmation
| Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
| Not configured

Lambda layers
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. api
? Api has 3 resources in this project. Select the one you would like your Lambda to access getUser
? Select the operations you want to permit on getUser read

You can access the following resource attributes as environment variables from your Lambda function
        API_GETUSER_APIID
        API_GETUSER_APINAME
? Do you want to edit the local lambda function now? No

dtal@thing5: 
```
* Final `amplify push`
* In the browser, in the IAM console, I noticed that two policies were created and attached to the IAM role for the post confirmation lambda: one is named `amplify-lambda-execution-policy` - here's that policy:
  ```json
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Action": [
                  "apigateway:GET",
                  "apigateway:HEAD",
                  "apigateway:OPTIONS"
              ],
              "Resource": [
                  "arn:aws:apigateway:us-east-1::/restapis/getUser/*"
              ],
              "Effect": "Allow"
          }
      ]
  }
  ```
  The second policy that gets attached by this deploy process to the post confirmation lambda role is named `lambda-execution-policy` - for the Cloudwatch logs access.
* The test: just invoke this lambda right after you enter the confirmation code for your user at the end of the authentication flow. The post confirmation then returns with an error `UserLambdaValidationException` caused by it getting a 403 when it tried to make the API call.
* When I changed the code of the API call to not use axios but use the aws-sdk `Service()` call instead, I also got a 403 error but in this case, got a bit more info about what caused the error, it said: **`"PostConfirmation failed with error Missing Authentication Token."`**.
 
**Expected behavior**

I expected the request from post confirmation lambda to the API to not get back a "missing authentication token" 403 error.

I expected the request's authentication token to have been there, with credentials of those of the user being post-confirmed.

I noticed that both the Auth and Unauth roles have policies to invoke the API. Had the correct authentication token been there, it would have worked.

**Desktop (please complete the following information):**

- OS: recent Debian linux
- Node Version. 12.0.0
- Amplify cli version: 4.42.0

**Comment by SwaySway** [comment]
@dorontal Thanks for your detailed report. I was able to reproduce this with the given axios snippet, though I saw that this wasn't signed with aws creds. 
A few questions here:
- Is the aws versioned signed with the credentials provided to the lambda?
- Could you provide the way you called api gateway with the AWS SDK?

**Comment by dorontal** [comment]
@SwaySway thank you for quick response. Reagarding the first question, I believe you mean whether the aws version that I used in the code that used the `aws.Service()` command, right?  If so, the answer is that it was not signed at all. Neither axios version or the aws version of the code did any signging. Regarding the second question, sure, here is the exact code I used to have the post confirmation lambda access the API Gateway REST endpoint:
```javascript
const aws = require('aws-sdk');
const axios = require('axios');

aws.config.update({region: process.env.REGION});

const getUserEndpointBaseUrl =
      'https://' + process.env.API_GETUSER_APIID + '.execute-api.' +
      process.env.REGION + '.amazonaws.com/' + process.env.ENV;
const postconf = '15923220-9750-4075-a096-efeedc1dec82';

//
// axios way of making the API call
//
exports.handler = (event, context, callback) => {
    const url = getUserEndpointBaseUrl + '/get-user?id=' +
          event.request.userAttributes.sub + '&postconf=' + postconf;
    axios.get(url).then((response) => {
        const identityId = response.identityId;
        console.log('got identityId: ' + identityId);
        if (identityId) {
            callback(null, event);
        } else {
            callback('no identityId', null);
        }
    }).catch((error) => {
        callback(error, null)
    });
};
```

**Comment by dorontal** [comment]
I believe that this is what's going on and will propose a direction to fix it (though I may be wrong):
* The post-confirmation lambda gets called and is authenticated at that time with Cognito User Pool
Here's what needs to happen
* With the user token, get temporary IAM credentials from the Identity Pool
* Use these IAM credentials to sign the API request with Signature Version 4
as desribed [here](https://serverless-stack.com/chapters/connect-to-api-gateway-with-iam-auth.html), for example.

**Comment by SethThomas** [comment]
Hi @dorontal.  I stumbled across this issue because I'm trying to solve the same problem you are.  I believe the behavior you are experiencing is expected.  

When you enable IAM authorization on your REST API, API Gateway requires that you authenticate every request you send by [signing the request](https://docs.aws.amazon.com/apigateway/api-reference/signing-requests/).  In your code snippets, it appears that you are not signing the request, so a 403 "Missing Authentication Token" makes sense.

> NOTE: when I test the same API from the test link in API-gateway console, it works: it returns a 200 response with the expected payload.

This is also expected behavior.  When you make a test call via the API Gateway Console, API Gateway skips authorization and directly invokes your method.

**Comment by dorontal** [comment]
@SethThomas - thank you for your reply - I think I understand it, but luckily we no longer need to have the post-confirmation trigger lambda function make an API call - the original reason for doing this was that we needed the identityId of the user, but in post-conf lambda that identityId doesn't exist, so it has to make an API Gateway call to an API Gateway API to ask for this identityId. But we have found a workaround for the original problem which caused this very special use case.

**Comment by SethThomas** [comment]
@dorontal Ah yes, the Cognito identityID problem.  It's a real struggle, I've been down that road myself.  It sounds like we've settled on similar solutions.  Glad you were able to solve your problem!

**Comment by ahlrenzarqueza** [comment]
> @dorontal But we have found a workaround for the original problem which caused us to first try the use case described in this issue.
This is really frustrating that getting identity Id still requires a workaround. 

I understand the purpose of identity Id being it available only after authentication of the particular user, but maybe AWS should consider if this is really the ID needed as principal to be used on other AWS services (such as AWS IoT). It is very ugly to self-manage IoT policies to check on every user login (in my opinion).
