### ISSUE TITLE
updating auth redirect urls does not seem to work

### ISSUE THREAD

**Issue by rmargolinross** [aws-amplify/amplify-cli#6591]
**Describe the bug**
When I run amplify update auth and attempt to update one of my redirect url's the url is never updated even though the process seems to succeed. I was forced to manually update my parameters.json file.

**Amplify CLI Version**
4.42.0

**To Reproduce**
`amplify update auth`
choose `Add/Edit signin and signout redirect URIs`
Follow the process to edit one url for signin and one for signout (For some reason it asks for signin twice)
`amplify push`

**Expected behavior**
I expect the url I updated to change but it did not

**Desktop (please complete the following information):**
- OS: Mac
- Node Version: 15.8.0

**Comment by sharmaaditya570191** [comment]
Can I take this up @ammarkarachi ?

**Comment by edwardfoyle** [comment]
Hi @rmargolinross I'm not able to repro this using the latest version of the CLI. I was able to edit existing URIs and add new ones. Can you provide more details around how you created and updated the auth resource? Also could you paste the contents of the "oAuthMetadata" field from the `parameters.json` file in the auth resource directory before and after running `amplify update auth`?

**Comment by sharmaaditya570191** [comment]
I am not able to reproduce this issue on the following configuration:-

- Amplify CLI version 4.43.0
- Node version: 10.23.0
- OS: Ubuntu 18.04

My `oAuthMetadata` field in `parameters.json` is getting updated successfully on running `amplify update auth` with the federated option.

**Comment by rmargolinross** [comment]
Actually I think I was using the cli wrong and answering the, do you wish to add any question incorrectly. That seemed to be causing my issue.
