### ISSUE TITLE
Admin UI authentication throws an error and prevents other authentication methods from being used 

### ISSUE THREAD

**Issue by JackPenney** [aws-amplify/amplify-cli#6593]
**Describe the bug**
When I run ``amplify init``, select an existing environment  and choose Amplify Admin UI as my authentication method it will throw the following errors (``Failed to refresh tokens: Missing required parameter auth parameters.
Failed to get credentials: Missing required parameter auth parameters``) 

After encountering this error ``ampliy init`` will no longer allow me to select a different authentication method, meaning i'm stuck in a broken state and can't attempt to authenticate my environment another way (Access key works fine for me but now I can't switch to use that).

I'm not sure what's causing this, i'm sure i'm missing a setting somewhere but have had no luck getting to the bottom of this yet, I have had Admin UI authentication work for me in the past. 
I've also tried re-running ``amplify configure`` and going through that process again but ``ampliy init`` still gives the same error
This also happens with ``amplify env checkout live``

**Amplify CLI Version**
4.42.0

**To Reproduce**
Run ``amplify init`` 
Select an existing environment
Select Amplify Admin UI as the authentication method
If you get the same error you should then be unable to change authentication methods for your environment 

**Expected behavior**
I'd expect Admin UI to work as an authentication method, not sure what i'm doing wrong to get it into this state
Also ``amplify init`` should allow me to select a a different authentication method if one has failed, instead of locking me into my first selection

**Screenshots**
![image](https://user-images.githubusercontent.com/17148318/107641744-e5584580-6c6b-11eb-8047-ceb081e96f3e.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: v12.18.4

**Comment by JackPenney** [comment]
I've managed to sort of work around this by setting up a fresh clone of my repo and then re-running ``amplify configure`` and then ``amplify init`` where i could authenticate by access key.  Not an ideal fix but it gets things unblocked for now

**Comment by jhockett** [comment]
@JackPenney if you run into this again, you can run `amplify logout --appId <yourAppId>` and then you'll be able to choose a different authentication method as expected when you run commands.

**Comment by EdwardFinegan** [comment]
> @JackPenney if you run into this again, you can run `amplify logout --appId <yourAppId>` and then you'll be able to choose a different authentication method as expected when you run commands.

I just ran into a similar issue and `amplify logout --appId <yourAppId>` worked for me. Is there any detailed document for these commands and when to use them?

**Comment by jhockett** [comment]
> > @JackPenney if you run into this again, you can run `amplify logout --appId <yourAppId>` and then you'll be able to choose a different authentication method as expected when you run commands.
> 
> I just ran into a similar issue and `amplify logout --appId <yourAppId>` worked for me. Is there any detailed document for these commands and when to use them?

`amplify help` is an easy way to get a list of commands and some context. 

However, this is a workaround so you won't find documentation for this scenario currently.

**Comment by hanna-becker** [comment]
I had the same issue after upgrading to amplify-cli 4.42.0 and then again to 4.43.0, although I do not recall ever selecting the admin ui as my default authentication method.

**Comment by jhockett** [comment]
> I had the same issue after upgrading to amplify-cli 4.42.0 and then again to 4.43.0, although I do not recall ever selecting the admin ui as my default authentication method.

Did running `amplify logout --appId <yourAppId>` fix the issue for you?

**Comment by edwardfoyle** [comment]
The fix for this has been released in version 4.44.1 of the CLI. Please upgrade to the latest version to try it out.

**Comment by Robbie-Cook** [comment]
I deleted everything in my `amplify` folder (except what was not gitignored) and re-ran `amplify init`. Worked for me
