### ISSUE TITLE
amplify pull causes template.json for userPoolGroups to be invalid

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#6594]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Given I have an Amplify app with Cognito Auth with userPoolGroups
And I run Amplify Pull
The amplify/backend/auth/userPoolGroups/template.json file is replaced with erroneous JSON (see the attached screenshot)

**Amplify CLI Version**
4.42.0

**To Reproduce**
Create an Amplify app with Cognito and userPoolGroups.
Push everything.
Once built, run amplify pull
Observe amplify/backend/auth/userPoolGroups/template.json for errors.

**Expected behavior**
I expect amplify/backend/auth/userPoolGroups/template.json to not contain errors

**Screenshots**
![image](https://user-images.githubusercontent.com/632749/107647799-8c77b580-6c49-11eb-97ac-c5c3a3a84418.png)

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
Mac 10.15.7
- Node Version. You can use `node -v` to check the node version on your system
node 12.14.1

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**

**Comment by sharmaaditya570191** [comment]
I am not able to reproduce the issue on the following environment:-

- OS: Ubuntu 18.04
- Node Version: 10.23.0
- Amplify CLI version: 4.44

I tried adding authentication with Cognito and UserPoolGroups but did not get any errors in the `template.json` under UserPoolGroups after pulling. Did you update anything related to UserPoolGroups via the Cognito UI after running `amplify push` before running `amplify pull`?

![image](https://user-images.githubusercontent.com/42587159/108437343-26a3b300-7273-11eb-91de-87339a976442.png)

**Comment by alexkates** [comment]
I don't see errors in the output of amplify-pull. I see errors when I open the template.json file in an VSCode. Specifically, there are extra commas generated, causing the JSON to show as invalid in the editor e.g., red squiggly lines. Please refer to my original screen shot for the editor errors.

**Comment by sharmaaditya570191** [comment]
Yes I have checked the path you mentioned - `amplify/backend/auth/userPoolGroups/template.json`. The `template.json` does not have any errors on my side. Is it because of some locally enabled extension for JSON files on your side?

**Comment by alexkates** [comment]
Yea I'm sure there is some extension that is highlighting the issue. That being said, the extra commas are still invalid JSON, right? Do you see the trailing commas, regardless of if the IDE is highlighting them?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#trailing_commas_in_json

**Comment by sharmaaditya570191** [comment]
Yes I agree but after `amplify pull` I do not have any trailing commas in `template.json`. I have tried adding multiple userGroups too. Did you complete the CLI process of creating UserPoolGroups or could you check if the Groups you created are visible on Cognito UI?

**Comment by alexkates** [comment]
I have completed the CLI process (we use amplifyPush --simple via the console CI/CD). The userGroups are also there in Cognito, and the app has been running in production for a few months. I'm confident everything is working correctly.

**Comment by sharmaaditya570191** [comment]
I was going through the changelog here - https://github.com/aws-amplify/amplify-cli/compare/v4.42.0...v4.44.0. There are some recent changes to lint rules and linters in the latest updates to the Amplify CLI (v4.44).

**Comment by jamesonwilliams** [comment]
@alexkates Do you see the trailing commas in `template.json` when using 4.44.0? If not, is this issue good to close?
