### ISSUE TITLE
regression on appsync permission assignment from functions

### ISSUE THREAD

**Issue by thibaultdalban** [aws-amplify/amplify-cli#6595]
**Describe the bug**
Since PR #5342 requesting a graphQL API inside a lambda using IAM auth returns a `Permission denied`.
`errors: [{ errorType: 'UnauthorizedException', message: 'Permission denied' }]`
Manually reverting the appsync policy in the lambda cloudformation template to the one generated before PR #5342 fix the issue.

**Amplify CLI Version**
4.42.0

<details>
<summary>Permissions generated in the cloudformation template</summary>

```json
 {
              "Effect": "Allow",
              "Action": [
                "appsync:GraphQL"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/types/create/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/types/read/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/types/update/*"
                    ]
                  ]
                },
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/types/delete/*"
                    ]
                  ]
                }
              ]
            }
```
</details>

<details>
<summary>Permissions manually updated in the cloudformation template</summary>

```json
           {
              "Effect": "Allow",
              "Action": [
                "appsync:Create*",
                "appsync:StartSchemaCreation",
                "appsync:GraphQL",
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/*"
                    ]
                  ]
                }
              ]
            }
```

</details>

This is how the request is signed in the lambda function:
```js
  let signer = new AWS.Signers.V4(req, "appsync", true)
  signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate())
```

**Comment by thibaultdalban** [comment]
@r0zar thanks for the great job done on these permissions assignment :+1: 
Do you have any clues on why I have permission denied?

**Comment by r0zar** [comment]
Looks like the type mappings are wrong.

`"/types/create/*"` / `"/types/read/*"` / `"/types/update/*"` / `"/types/delete/*"`

For a workaround try setting your CF template to this: 

```
{
              "Effect": "Allow",
              "Action": [
                "appsync:GraphQL"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apixxxGraphQLAPIIdOutput"
                      },
                      "/*"
                    ]
                  ]
                }
}
```

**Comment by thibaultdalban** [comment]
Thanks for your quick reply, I will give it a try and let you know.

**Comment by r0zar** [comment]
Thoughts on this issue...

Amplify allows for limiting create/read/write/update access to AppSync through a CLI based question-answer workflow.
(The PR updates it to use query/subscription/mutation language) 

To implement that, the cloudformation policy is split into separate resource inputs which each are responsible for different resolver ARNs.

You can get a better idea of the structure of the resolver ARNs by looking at your `amplify/backend/api/<api-name>/build/cloudformation-template.json` file an see how they are referenced by the generated AppSync code. 

My assumption is that resolver ARNs are being matched against using the implicit pattern that AppSync uses when it generates the resolvers. (Could be improved by exporting resolvers from the API category cloudformation and importing it elsewhere)

I'm not sure why the resources in your example are using the old create/read/update/delete language. The goal of the PR was to remove the CRUD verbs with the introduction of graphql-style language (query/mutation/subscription) for graphql-based APIs. (Looking into this). This simplified the mapping of actions to relevant resolver ARN paths.

 Todos
 - Find out why CRUD verbs are being used for a AppSync API
 - Look into possibility of exporting resolvers to use their ARNs by import/reference
 - TBD

**Comment by thibaultdalban** [comment]
If it can help, the API has been created a few months ago, so not with the CLI V4.42.

**Comment by thibaultdalban** [comment]
I confirm it works

> Looks like the type mappings are wrong.
> 
> `"/types/create/*"` / `"/types/read/*"` / `"/types/update/*"` / `"/types/delete/*"`
> 
> For a workaround try setting your CF template to this:
> 
> ```json
> {
>   "Effect": "Allow",
>   "Action": [
>     "appsync:GraphQL"
>   ],
>   "Resource": [
>     {
>       "Fn::Join": [
>         "",
>         [
>           "arn:aws:appsync:",
>           {
>             "Ref": "AWS::Region"
>           },
>           ":",
>           {
>             "Ref": "AWS::AccountId"
>           },
>           ":apis/",
>           {
>             "Ref": "apixxxGraphQLAPIIdOutput"
>           },
>           "/*"
>         ]
>       ]
>     }
>   ]
> }
> ```

**Comment by SwaySway** [comment]
Hello @thibaultdalban 
This new feature has a feature flag for it did you have that enabled when running update?
```json
"appSync": {
  "generateGraphQLPermissions": true
}
```

**Comment by thibaultdalban** [comment]
@SwaySway I will check that tomorrow morning, in which file this flag is supposed to be defined?
I was reading the PR and discovered the check on this feature flag [here](https://github.com/aws-amplify/amplify-cli/pull/5342/files#diff-102364c7436737e11d4a0d58e8a633eb9d687e74b61837c8281cc9d7390e5e19R108) so it's probably my issue. I will let you know.

**Comment by SwaySway** [comment]
Yup this feature flag can be assigned in the `cli.json` file which is located in your `amplify` dir.
More docs on FF here: https://docs.amplify.aws/cli/reference/feature-flags

**Comment by sevenseat** [comment]
After upgrading to 4.43.0, I had this issue as well.  I did not originally have the `generateGraphQLPermissions` flag set, but I set it after reading the thread.  The issue didn't disapper.  To get things back to working, I followed @r0zar 's instructions above, setting the permissions to `/*`

**Comment by ataibarkai** [comment]
I'm also experiencing the same issue.

For anyone on the lambda team looking into this, this comment on another github issue sums up the problem perfectly: 
https://github.com/aws-amplify/amplify-cli/issues/6675#issuecomment-782106122

Seems it should be very easy to fix

**Comment by SwaySway** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-cli/issues/6675
