### ISSUE TITLE
Mobilehub -> Amplify migration. Import existing API GATEWAY instance.

### ISSUE THREAD

**Issue by AdriannaJedrzejczak** [aws-amplify/amplify-cli#6606]
Im migrating environment from MobileHub to Amplify. I want to continue using all of the existing resources (Cognito, APi gateway and hosting of the app).

**What I have done:**
1. Initialize the project with `amplify init` command
2. Import existing Cognito using the `amplify import auth` command 
3. Add hosting feature for the project using `amplify add hosting`

**What is left:**
1. Import Api Gateway to the freshly created environment, which is impossible for now as I know? 

**Is your feature request related to a problem? Please describe.**
Mobilehub will be discontinued in October 30 2021, I need to migrate existing environments to the Amplify service and, in the future, be able to create new environments with Amplify. 

**Describe the solution you'd like**
Easy way to link amplify project.

**Describe alternatives you've considered**
I tried manual adding the api gateway resource in the aws-export.js file, it does work locally, but when I deploy the application using `amplify publish` command, this file is overridden, oauth configuration is being added and I get following error 
<img width="792" alt="Screenshot 2021-02-10 at 16 40 28" src="https://user-images.githubusercontent.com/33098816/107776106-777e4d80-6d41-11eb-968b-39c4e85d13af.png">

My aws-exports.js file (without manually added api address):
<img width="558" alt="Screenshot 2021-02-12 at 14 53 21" src="https://user-images.githubusercontent.com/33098816/107776661-23c03400-6d42-11eb-8149-0600fd7713bb.png">

**Comment by SwaySway** [comment]
Hello @AdriannaJedrzejczak 

We do not recommend using import auth to move your auth resource from mobilehub to amplify cli. 
We do have a migrator tool which can help with this usecase
Repo: https://github.com/awslabs/amplify-mobilehub-migrator

**Comment by AdriannaJedrzejczak** [comment]
Thanks for your response, @SwaySway.

I tried using the migration tool however, I found the following issues: 
1. Hosting feature is not migrated properly. I cannot either successfully run `amplify publish`, because its causing the following error: ```An error occurred during the publish operation: No Amazon CloudFront and S3 hosting service is enabled.```

nor run `amplify add hosting` or `amplify remove hosting`.
Running `amplify add hosting` gives me `S3AndCloudFront is present in amplify-meta.json` 
Running `amplify remove hosting` gives me `You have not added any resources in the hosting category.` 
It looks like its halfway configured.
2. API is migrated with hardcoded `/Development` (upper case) URL -> I managed to update it manually and make it work.

Additionally, I need to make sure that in the future, there exists a possibility to create a new environment from scratch, which is not when I only base on the migration tool

**Comment by kaustavghosh06** [comment]
@AdriannaJedrzejczak 
Sorry for the confusion, would you mind opening up an issue in the MobileHub migrator GitHub repo -  https://github.com/awslabs/amplify-mobilehub-migrator and we'd be happy to help migrate your MobileHub project to Amplify. Thank you.
