### ISSUE TITLE
Missing GraphQLAPIIdOutput dependency in lambda function with analytics and storage resources

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#6607]
**Describe the bug**
When using the *amplify add function* command, a dependency issue occurs when you set permissions for both analytics and storage resources, without DynamoDB streams trigger. It can be fixed by adding the GraphQLAPIIdOutput to dependsOn in amplify-meta.json and to parameters in the function's cloudformation-template.json

**Amplify CLI Version**
4.41.2

**To Reproduce**
```
amplify init
amplify add auth
amplify add analytics
amplify push
amplify add notifications
amplify add api
amplify add function
  serverless lambda (no trigger)
  additional resources: analytics, storage
amplify push
```

**Comment by rajrajhans** [comment]
> **To Reproduce**
> 
> ```
> amplify init
> amplify add auth
> amplify add analytics
> amplify push
> amplify add notifications
> amplify add api
> amplify add function
>   serverless lambda (no trigger)
>   additional resources: analytics, storage
> amplify push
> ```

I am getting the following error while after following the steps mentioned:

```Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs```

> It can be fixed by adding the GraphQLAPIIdOutput to dependsOn in amplify-meta.json and to parameters in the function's cloudformation-template.json

@avlonder can you specify what exactly should be added to those files to fix the error? Thanks

**Comment by akshbhu** [comment]
Hi @avlonder 

This is happening due to this :https://github.com/aws-amplify/amplify-cli/blob/45e0246306136e513c735899b030f94bb004a330/packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts#L229

Since we are adding dependsOn only on basis for resourceName and in your case ```analytics``` and ```api``` have same resourceNames which skips the dependsOn for ```api```.

I have included this change in PR.

For the workaround , you need to add the dependsOn section in your function:
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "translatedev",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }

**Comment by grant-d** [comment]
Any news on this being merged. We have the same bug, preventing deployment.
Our repro is simpler, we simply removed a function, added it back and now it fails with the same error. In our case the dependency is a `DynamoDb` table (ie this issue is not restricted to `storage`/`analytics`)

This dependency fails. 
```
"API_JIGX_FOOTABLE_NAME": {
              "Fn::ImportValue": {
                "Fn::Sub": "${apiabcGraphQLAPIIdOutput}:GetAtt:FooTable:Name"
              }
            }
```

**Comment by mgarabedian** [comment]
Also having this issue...I just upgraded to the latest cli, and after 'amplify update function' to access 'storage', I get this error. What is the fix?

**Comment by mgarabedian** [comment]
Thank you for your workaround @akshbhu . In my case, I was only using 'storage', so this worked using just 'GraphQLAPIIdOutput'. I was able to successfully deploy at least.

```
 "MyLambdaFn": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "FooBar",
          "attributes": [
            "GraphQLAPIIdOutput"
          ]
        }
      ],
  ...
}
```

**Comment by avlonder** [comment]
Amplify guys, please stop adding breaking changes to the CLI: suddenly my whole way of creating Lambdas with storage and analtyics permissions is broken. And I can't go back to an earlier version of the CLI without a lot of other trouble. This kind of stuff is really driving me nuts (sorry, getting moody, probably due to covid)

**Comment by avlonder** [comment]
Ow sorry, my mistake: had two resources with the same name. So, there was no breaking change. At least not this time.

**Comment by akshbhu** [comment]
Closing this in favour of  #6639
