### ISSUE TITLE
optionally provision DynamoDB tables created via `amplify add api (GraphQL)` using On-Demand capacity

### ISSUE THREAD

**Issue by troygoode** [aws-amplify/amplify-cli#661]
**Is your feature request related to a problem? Please describe.**

Currently DynamoDB tables created via `amplify add api (GraphQL)` are configured to use Provisioned capacity (with 5 units of R/W capacity per month). This seems like a sane default given that Provisioned capacity is eligible for AWS' Free Tier. On the other hand, users are more likely to stumble upon runtime operation errors when you exceed the (very low) initial capacity. AWS recently launched DynamoDB On-Demand capacity, which solves this challenge but (a) comes at a premium and (b) does not have a Free Tier.

**Describe the solution you'd like**
Prompt the user to input a Read/Write capacity for use when creating the table; if the users doesn't specify (or says zero?) select On-Demand capacity for them instead of Provisioned capacity.

**Describe alternatives you've considered**
Update the [documentation](https://aws-amplify.github.io/docs/js/api) (and potentially the text output of `amplify add api (GraphQL)` to note that the user should be careful to adjust the default 5 units of RW capacity to something that will fit their use case.

**Comment by mikeparisstuff** [comment]
@troygoode Thanks for the feature request. This feature has been completed as part of #581 and will be merged into the multienv branch as soon as the PR is completed and merged.

**Comment by kaustavghosh06** [comment]
We've added support for this in our main CLI version.
Please install the latest CLI using `npm install -g @aws-amplify/cli` and let me know (and re-opne the issue) if you're still facing this issue.

For documentation regarding this, please take a look at https://aws-amplify.github.io/docs/cli/graphql#dynamodbmodeltablereadiops for documentation regarding the same.
