### ISSUE TITLE
Unable to do an Amplify push

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#6611]
We are unable to do an Amplify push as of this morning. 

We have done hundreds of pushes for this project over the last year.

We receive the error "<resource> must have values" multiple times and have not come across this before:

Here is the stack trace:

? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes
| Updating resources in the cloud. This may take a few minutes...
UPDATE_FAILED      storagexxxxxxxxxxpics AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:47 GMT-0500 (Eastern Standard Time) Resource update cancelled
UPDATE_FAILED      functionxxxxxxxxxx            AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:47 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_FAILED      hostingS3AndCloudFront       AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Resource update cancelled
UPDATE_FAILED      UnauthRole                   AWS::IAM::Role             Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Resource update cancelled
UPDATE_FAILED      DeploymentBucket             AWS::S3::Bucket            Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Resource update cancelled
UPDATE_FAILED      AuthRole                     AWS::IAM::Role             Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Resource update cancelled
UPDATE_FAILED      functionxxxxxxxxxx      AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_IN_PROGRESS functionxxxxxxxxxx            AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time)
UPDATE_FAILED      functionxxxxxxxxxx           AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_FAILED      functionsxxxxxxxxxx     AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_FAILED      functionxxxxxxxxxx       AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_FAILED      functionxxxxxxxxxx         AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values
UPDATE_FAILED      functionxxxxxxxxxx         AWS::CloudFormation::Stack Fri Feb 12 2021 15:32:46 GMT-0500 (Eastern Standard Time) Parameters: [s3Key, deploymentBucketName] must have values

**Comment by pepso** [comment]
I have the same issue, but against a newly added lambda only (plain express JS boilerplate function).

My Amplify CD pipeline does not show an error in the logs and only information about the failure is available through cloud formation: "CREATE_FAILED | Parameters: [s3Key, deploymentBucketName] must have values"

Steps to reproduce:
- Add new lambda function (select Express template)
- Push changes to git -> triggers CD pipeline push
- Build fails

Amplify-cli in use "latest" = 4.43

I tested changing version to 4.42, and 4.41.2. For both versions, the build succeeds, but the function does not get created.

**Comment by blairtaylor** [comment]
Updating the Amplify CLI to the latest version resolved the issue for us.

**Comment by pepso** [comment]
My fix was to manually remove the parameters of s3Key and deploymentBucketName from the newly created Lambda function's cloud formation template. I'm going to raise this as a separate issue so it will be tracked...

**Comment by yuth** [comment]
@blairtaylor did you have the Amplify CLI version pinned

**Comment by miguelaeh** [comment]
Hi guys,
Just in case it helps someone I spent some hours with a similar issue. After adding a lambda function using the CLI version `4.44.1` my fronted CI was unable to push due to `Parameters: [s3Key, deploymentBucketName] must have values`.
It seems the version used in the CI by default `4.29.4`, so, to use the same version as I am using in local I configured the `Live Packages Updates` using the console to override that version and use the same as locally. Now everything works fine.

**Comment by kaustavghosh06** [comment]
Looks like pinning the version in CI/CD to latest version of Amplify CLI fixes the issue. 
@blairtaylor Please let us know if you're still stuck on this and we'll re-open the issue.

**Comment by blairtaylor** [comment]
Thanks @kaustavghosh06 . As per my comment on Feb 13, upgrading to the latest version resolved the issue for us. This was an amplify push command from the CLI not a CI build. 

Within the CI build, our build setting is:        

backend:
  phases:
    build:
      commands:
        - amplifyPush --simple

Does this not use the latest version of Amplify to build?
