### ISSUE TITLE
Support VTL resolver

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6616]
I found that amplify provides a `@function` directive to add any custom resolver via Lambda.
But in most cases, a simple VTL resolver is enough and efficiency.
Please consider to implement a directive for VTL resolver.

Thanks.

**Comment by yuth** [comment]
What is the use-case you have in mind, which would help to have custom VTL Resolvers?

**Comment by yaquawa** [comment]
Hi @yuth 
That could be any edge cases that the framework not provides.
For example complicated auth rules or validation rules depending on the domain logic, or the missing `BatchGetItem`, `BatchWriteItem` operation which the framework not provides, there are so many edge cases you can tell.

It's easy enough to attach VTL resolver via the AppSync console, but this way you have to write the tedious CloudFormation templates yourself, which should be the work of the framework to do.

**Comment by yuth** [comment]
It makes sense. Like you said,  transformer vNext would make it easier to write a custom transformer to address this usecase. We are also exploring how we can expose pipeline in the vNext transformer

**Comment by yaquawa** [comment]
we already have the `@function` but why not give a `@vtl` also ? 
I think this is the simplest way to implement a custom resolver.

**Comment by cjihrig** [comment]
I'm going to close this as custom VTL resolvers are supported - https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver
