### ISSUE TITLE
Confusing messaging leads to duplicate projects: "You are not working in a valid Amplify project"

### ISSUE THREAD

**Issue by omenking** [aws-amplify/amplify-cli#6617]
In AWS Amplify, you can build a web application without having to ever pull the backend because you are using the Admin UI.

It is very easy to run into the error "You are not working in a valid Amplify project" and then be prompted to run `amplify init` 

Then you will run `amplify init` and not realizing that it has now just created a second application.

<img width="736" alt="Screen Shot 2021-02-13 at 7 31 56 AM" src="https://user-images.githubusercontent.com/7776/107850065-a7733280-6dcd-11eb-988f-814e262477d8.png">

A more clear message would be along the lines of:

```
We detected no local backed files suggesting there is no provisioned backend. 
This command requires a backend environment deployed to AWS and the presence of these backend files.
If you already have a backend environment within the AWS console you need to pull these files
If you have yet to create a backend environment you can run ampify init to initialize a new project that will provision a blackened environment to AWS
```

**Comment by renebrandel** [comment]
Hi @omenking good feedback. What do you think of this prompt:

```
No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
- "amplify init" to initialize a new Amplify project
- "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
```

**Comment by gitaalekhyapaul** [comment]
@yuth @renebrandel would an error like this work?
![Screenshot from 2021-04-04 17-42-44](https://user-images.githubusercontent.com/54375111/113508364-3a7a4e80-956d-11eb-9b80-056785d2421b.png)
**If yes, I would like to be assigned to this issue**
