### ISSUE TITLE
Incompatibility with previous project using latest 4.43 fails Lambda deployments

### ISSUE THREAD

**Issue by pepso** [aws-amplify/amplify-cli#6619]
I have created my original amplify project around when the cli version ~4.21.3 was out.

The last ~8 months of amplify-cli releases and incompatibility with AWS Amplify service is causing issues to our project. The latest update is no different. 

Background and contexts:
- I updated my local development environment to amplify-cli to 4.43 (so I get support for lambda layers <- totally worth raising another issue but I leave it out, for now, to keep scope contained in this issue)
- I created a box standard Lambda with "amplify function add" and pushed to git
- AWS Amplify pipeline using "latest" = 4.43 fails to deploy without any indication in the logs as to why 
- Only information about the failure is available through AWS console's cloud formation: "CREATE_FAILED | Parameters: [s3Key, deploymentBucketName] must have values"

Steps to reproduce:
- Have a prior project (probably 4.41.2 is enough based on changelog)
- Add new lambda function using 4.43 (select Express template)
- Push changes to git -> which triggers AWS amplify pipeline
- Build fails for no logs (except in CloudFormation stack info as copy+pasted above)

I tried to rerun the build with 4.43, 4.42, and 4.41.2. For 2 latter ones, the build succeeds, but the function did not get created.

My eventual fix for the issue was to edit the function's cloud formation template manually and remove references to s3Key and deploymebtBucketName. This created the new lambda function using CD pipeline in the cloud finally.

In the end, my issue boils down to the following bullet points:
- What is the missing configuration from my project that causes this issue (missing s3key/bucket name), and how these are communicated to users like me so I know how to fix these without spending hours browsing this repo for PRs and code changes? I didn't see any indication of breaking changes in the changelog for this one until I found this: https://github.com/aws-amplify/amplify-cli/pull/6358
- What is the current test process for the amplify-cli team to ensure AWS amplify users can use the amplify-cli without breaking their builds ~every third release (this is subjective based on my project experience)?
- Is there an understanding that some users of amplify-cli never use commands like push, pull, in their development environment, but rely on CD pipeline to manage their cloud environments? More than happy to share why this is the case in follow up conversations (security/env-variables/version-controlled configuration etc.). Maybe I'm using amplify "wrongly" or maybe it is something you should look into as a valid use case of the tool.

I think there is no urgency to deal with the current technical fix (as I have a manual fix in place for now), but I am keen to understand how this project can ensure also existing users continue to enjoy the fruits of this framework with less frustration.

_Originally posted by @pepso in https://github.com/aws-amplify/amplify-cli/issues/6611#issuecomment-778655599_

**Comment by tryheirloom-alex** [comment]
Hi @pepso, I found this issue while facing similar symptoms:
 - My local Amplify CLI (4.43.0) changed the `*-cloud-formation-template.json` files to take the parameters `deploymentBucketName` and `s3Key`.
 - The `amplify push` command works locally. I can see these parameters and their values in `team-provider-info.json`
 - The build fails when it is triggered from the CD pipeline with the following error:
 ```
 CREATE_FAILED      function*               AWS::CloudFormation::Stack Sun Feb 14 2021 19:53:23 GMT+0000 (Coordinated Universal Time) Parameters: [s3Key, deploymentBucketName] must have values
 ```

## Solution
I resolved that issue by going into the "Build image settings" in the amplify console and making sure the "Amplify CLI" package's version is set to "latest". I could verify that the setting worked by triggering a new build and looking at the logs under "Build" > "Cloning Repository". There was now a message that looked like this:
```
2021-02-14T23:23:33.015Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-02-14T23:23:37.957Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.43.0...
```
The build proceeded to complete successfully at that point.

It seems that you tried different versions of the CLI so your issue may be unrelated. I'm leaving a comment hoping to help other people who are brought here searching for these errors (it must be fairly common given that the build image was using Amplify cli 4.29.4 by default).

**Comment by yuth** [comment]
@pepso Thank you for your feedback. Did you have the Amplify CLI version pinned in Amplify console?

**Comment by pepso** [comment]
Hi @yuth, and more than happy to share my findings if these help us all going forward.

_Did you have the Amplify CLI version pinned in Amplify console?_
I used the "latest", which might have not been latest (4.43) based on answer by @tryheirloom-alex, and then I pinned the versions 4.42, and 4.41.2 into build settings to test these versions out.

_Also do you have the team-provider-info.json file in .gitignore file?_
Short answer: no. 
Long answer: We use team-provider-info.json to set the auth's hostedUIProviderCreds to SSO authentication during the build time so it's a mix of things instead of straight yes/no in our case.

**Comment by pepso** [comment]
Just a quick note after I added yet another function and encountered the same problem:
Pinning AWS Amplify's build setting for Amplify-cli to 4.44 did solve the technical deployment issue of missing S3key/deploymentBucketName. 

This probably closes "technical fix" part of the original question, but not the bullet points regarding "how cli team communicates these changes to the user", and "valid use cases regarding CD pipeline deployments" which are still pending answers.

**Comment by yuth** [comment]
> Just a quick note after I added yet another function and encountered the same problem:

Did you use the same version of Amplify CLI in both console and on your computer when adding the function

**Comment by pepso** [comment]
> Did you use the same version of Amplify CLI in both console and on your computer when adding the function

It was local: 4.43, and CD: 4.44

**Comment by jhockett** [comment]
@pepso do you see references to s3key/deploymentBucketName in your `team-provider-info.json` file?

`<environment name>.categories.function.<function name>.s3key`
`<environment name>.categories.function.<function name>.deploymentBucketName`

**Comment by pepso** [comment]
team-provider-info.json has no variables defined for our functions on "production" nor "dev" cloud environments, with an exception that "dev" has 1 lambda layer with those variables present for some reason.

**Comment by kaustavghosh06** [comment]
@pepso Were you able to figure out the solution tied to this issue?
