### ISSUE TITLE
Invoking a lambda from another Lambda

### ISSUE THREAD

**Issue by ReidWeb** [aws-amplify/amplify-cli#663]
** Which Category is your question related to? **
Functions
** What AWS Services are you utilizing? **
Lambda (and others - but not relevant to this question)
** Provide additional details e.g. code snippets **
I'm using AWS Amplify CLI Multienv 20, I'd like to be able to invoke another (Amplify managed) lambda function from my Amplify managed lambda function - I need to grant the invoking lambda the role that permits it to invoke my second lambda - however I cannot find any way to manage this with amplify?

If I edited the CFT, it could get over-written and it would be different between environments? Any advice, or is this not a feature available?

**Comment by kaustavghosh06** [comment]
@ReidWeb I beleive the CFT template won't get modified for the Lambda function. You can go ahead and modify it in the amplify/backend directory.

**Comment by ReidWeb** [comment]
Ah that's good to know! Managed to add a segment to the lambda policy that'll allow me to invoke the secondary lambda

```json
{  
   "Effect":"Allow",
   "Action":"lambda:InvokeFunction",
   "Resource":{  
      "Fn::Sub":[  
         "arn:aws:lambda:${region}:${account}:function:funcName-${env}",
         {  
            "region":{  
               "Ref":"AWS::Region"
            },
            "account":{  
               "Ref":"AWS::AccountId"
            },
            "lambda":{  
               "Ref":"LambdaFunction"
            },
            "env":{  
               "Ref":"env"
            }
         }
      ]
   }
}
```

so 🤞it should work across environments - I'll reopen this if I face issues when promoting

**Comment by MontoyaAndres** [comment]
Thanks @ReidWeb , That little code worked for me! In my case, I'm trying to execute another lambda through the post-confirmation lambda, because I have this issue: https://stackoverflow.com/questions/62503523/trying-to-use-model-within-post-confirmation-function :(

**Comment by mjza** [comment]
@MontoyaAndres How did you used this code to invoke your second function?

**Comment by mjza** [comment]
@MontoyaAndres Could you please help me to call my second function via postConfirmation? Could you please list the steps and codes?

**Comment by MontoyaAndres** [comment]
@mjza it's not necessary, you can try this https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js instead of adding the trigger with the cli

**Comment by mjza** [comment]
@MontoyaAndres I saw that link already. But assume I want to add group to user when confirmed and then also add him to my custom user table. In this case, I need to implement the add user group first, and then add user to custom table by calling the custom `add user to table` function in the  `add user to group` function.

**Comment by mjza** [comment]
@MontoyaAndres What I really need to know is if I exactly have a custom function how can I invoke it inside of my Post confirmation event function.

**Comment by mjza** [comment]
I found the solution! :D

**Comment by MontoyaAndres** [comment]
@mjza what did you do and was the solution for you? :)

**Comment by mjza** [comment]
@MontoyaAndres please check your stackoverflow question. I left the answer there.

**Comment by mjza** [comment]
Basically I needed to add user to a group and also record it in a user table. I think you wanted to do the same. Isn't it?

**Comment by MontoyaAndres** [comment]
Yep, that was I think 😅. Thanks for sharing!
