### ISSUE TITLE
Error: Cannot find module 'amplify-cli-logger' or new node version v14.9.0

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/amplify-cli#6633]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

Updated working system (Ubuntu 20.10) to node 14.9, updated amplify to latest.  Used Amplify code about 12 month snow.  When I try to check Amplify version, I get the error stated above and a reference to folders in node version 12.18.3 as such --> " '/home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/bin/amplify'"

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

@aws-amplify/cli@4.43.0 (this was from the install script results as checking version after renders the error)

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

amplify --version

**Expected behavior**

Amplify should recognize system node version

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
Ubuntu 20.10

- Node Version. You can use `node -v` to check the node version on your system
- 
Node 14.9.0

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

/home/vfulco/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/exitOnNextTick.js:1
Error: Cannot find module 'amplify-cli-logger'
Require stack:
- /home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/exitOnNextTick.js
- /home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/index.js
- /home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/lib/index.js
- /home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/home/vfulco/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/exitOnNextTick.js:4:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/exitOnNextTick.js',
    '/home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/index.js',
    '/home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/lib/index.js',
    '/home/foo/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/bin/amplify'
  ]
}

**Additional context**

**Comment by yuth** [comment]
@weisisheng 
1. How did you update the Amplify CLI after installing Node 14.9
2.  Did you get any error when installing the CLI? 
3. Do you have custom `PATH` variable set in the shell to ensure Amplify CLI is added to the PATH

**Comment by weisisheng** [comment]
Hello-

1. Used this-->sudo npm install -g @aws-amplify/cli --unsafe-perm=true
2. No error, finished per the usual.
3. This was it.  Path was still showing the old version of node even after I switched in NVM.  Fixed now.
Thank you.
