### ISSUE TITLE
Support import statement in graphql files

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6636]
After I saw https://github.com/aws-amplify/amplify-cli/issues/962

I realized that the order of auto merging relied on filename implicitly.

For example:
```
s2.graphql
s1.graphql
s3.graphql
```
would be merged in order of:
```
s1.graphql
s2.graphql
s3.graphql
```

which may not be the correct order to be merged.

to solve this issue, you may use [graphql-tools](https://www.graphql-tools.com/docs/schema-loading/#using-import-expression) to implement this feature.

so  you can just do import explicitly:

```graphql
# s1.graphql (the entry point)

# import * from 's2.graphql'
# import * from 's3.graphql'

extend type Query {
  queryField2: String
}
```

**Comment by yuth** [comment]
@yaquawa  have you faced any problems with the merging order? The way graphql transformer works is it merges the set of documents inside the `schema` folder to a signle file first and then starts processing the merged document. Here the order of declaration does not matter as there are no scopes or namespaces.

**Comment by yaquawa** [comment]
@yuth You can read #962 for more details, but the point is that I don't think this will work

```graphql
extend type XXX {
  queryField2: String
}

type XXX {
  queryField1: String
}
```

because I think you have to define `XXX` first before you can extend it, I'm I wrong?

**Comment by yuth** [comment]
Given the following documents

```gql
# schema/one.graphql
type One @model {
  baseField: String
}

extend type Two {
  extendedField: Int
}
```

and 

```gql
# schema/two.graphql
extend type One {
  extendedField: String
}

type Two @model{
  baseField: String
}
```

The transformer merges the files and generates this

```gql
# Pasting only relevant snippet
type One {
  id: ID!
  baseField: String
  extendedField: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Two {
  id: ID!
  baseField: String
  extendedField: Int
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

```

This is possible because the schema is type declaration and there is no namespaces or scoping needed. So the order is not matter when declaring the types.

Feel free to comment/reopen if extension does not work
