### ISSUE TITLE
Can not choose partition and sort key as key for GSI.

### ISSUE THREAD

**Issue by patrykkrz** [aws-amplify/amplify-cli#6637]
I have an existing DynamoDB table created by amplify
The table has only two columns:
- PK (as Partition Key)
- SK (as Sort Key)

The remaining columns will be added by the application later as needed (never mind at this case).

I need add GSI to reverse Partition Key <-> Sort Key. I tried to add GSI, when partition key for GSI was "SK" column from my table, and sort key for GSI was "PK" column, but can't do this by amplify (info from amplfy cli: **You do not have any other attributes remaining to configure**). I can do it by AWS Console.

When I added any column by amplify-cli, I have the option to select it as PK for GSI.

**Amplify CLI Version**
4.43.0

**To Reproduce**
Create table with only two columns and try update storage:

**_amplify storage update_**
? Please select from one of the below mentioned services: NoSQL Database
? Specify the resource that you would want to update ********
? Would you like to add another column? No
? Do you want to add global secondary indexes to your table? Yes
**You do not have any other attributes remaining to configure**
? Do you want to add a Lambda Trigger for your Table? No
? overwrite ******\SevMainTable-cloudformation-template.json No
Successfully updated resource

**Expected behavior**
Add partition key column name and sort key column nam to chooser: "Please choose partition key for the GSI"

**Comment by edwardfoyle** [comment]
@patrykkrz I was able to repro this and it seems like a bug to me. You should be able to select the primary index partition key as a key in a GSI when going through the flow.

**Comment by kaustavghosh06** [comment]
Fix for this issue was merged and released in the latest version of the CLI.

**Comment by patrykkrz** [comment]
@edwardfoyle This fix is not working for me. amplify-cli version 4.46.1

**Comment by attilah** [comment]
Reopened because of #7249

**Comment by edwardfoyle** [comment]
@patrykkrz Looks like this was a miss from the original fix. The CLI allows you to select all keys as GSI during the add workflow but didn't add support for the update workflow
