### ISSUE TITLE
Appsync Mock: Util.error or #return continues execution of pipeline and resolvers.

### ISSUE THREAD

**Issue by mgarabedian** [aws-amplify/amplify-cli#6640]
**Describe the bug**
As of version 4.42.0 and above, appsync simulator is not aborting on #return or $util.error.  My pipeline functions continue to execute after an error is thrown, all the way until the resolver template. If I downgrade to 4.41.2, the problem is gone.

**Amplify CLI Version**
Affecting 4.42.0 and 4.43.0

**To Reproduce**
Throw an exception in a vtl template. $util.error("ERROR").  It will continue to execute future pipeline and resolvers.

**Expected behavior**
Prevents subsequent functions from being executed.

**Desktop (please complete the following information):**

- OS: Mac
- Node Version. v14.2.0

**Comment by kaustavghosh06** [comment]
Fix for this issue was merged and released in the latest version of the CLI.
