### ISSUE TITLE
Unknown type \"AWSEmail\"

### ISSUE THREAD

**Issue by igorkosta** [aws-amplify/amplify-cli#6643]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
`AWSEmail` scalar type is not recognized when used locally with  `amplify mock api`

**Amplify CLI Version**
4.43.0

**To Reproduce**
Use `AWSEmail` scalar type in your graphql schema. 
Whenever you try to query the data with 

```js
    const {
      data,
      errors,
    } = await API.graphql(graphqlOperation(getUser, { email }));
```

The call to graphql api results in following error:

```
{"errors":[{"message":"Unknown type \"AWSEmail\". Did you mean \"AWSDate\"?","locations":[{"line":1,"column":23}]}],"data":null}
```

**Expected behavior**
`AWSEmail` scalar type works as expected.

- OS: Mac OS Mojave - 10.14.6
- Node Version: v15.2.0

**Comment by gitaalekhyapaul** [comment]
PR #6680 fixes the above issue.

**Comment by cjihrig** [comment]
Thanks @gitaalekhyapaul. I'll close this out as #6680 has been released.
