### ISSUE TITLE
Amplify push, status and env Cannot read property 'forEach' of undefined TypeError: Cannot read property 'forEach' of undefined 

### ISSUE THREAD

**Issue by sanjaykataria10** [aws-amplify/amplify-cli#6645]
**Describe the bug**
amplify status -> Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at AmplifyToolkit.showHelpfulProviderLinks show-helpful-provider-links.js:12:15

amplify env checkout <name>
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined checkout.js:28:45

amplify pull --restore
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
initialize-env.js:49:49

all amplify commands seem to fail when reading providers.forEach. For backend, our project has auth, storage and api

**Amplify CLI Version**
amplify -v -> 4.43.0

**To Reproduce**
any env related amplify command

**Desktop (please complete the following information):**

- OS: Windows
- Node Version. v10.15.3

**Comment by yuth** [comment]
@sanjaykataria10 Could you answer the following
1. Is Amplify CLI installed gloablly (using `npm install -g @aws-amplify/cli`)
2. Is this project created in a different machine
3. Could you share the content of `<proj-root>/amplify/.config/project-config.json`.

**Comment by sanjaykataria10** [comment]
@yuth 

1. Amplify CLI installed globally
2. project was created in my m/c but I have other developers working on it
3. here is the project config on my local. 
{
  "version": "3.0"
}
when reviewing on github looks like this file was deleted by a dev. (prev contents below)
{
    "providers": [
        "awscloudformation"
    ],
    "projectName": "amplify-jobs-app",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "react",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "build",
            "BuildCommand": "npm.cmd run-script build",
            "StartCommand": "npm.cmd run-script start"
        }
    }
}

Thanks.

**Comment by sanjaykataria10** [comment]
I have restored the project-config and am able to run amplify env commands. Thanks !
