### ISSUE TITLE
Support graphql "Conditional Put" with primary key condition

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6647]
I noticed that there is a "condition" parameter on the "createXXX" mutation fields.
But seems like it only gives the "non-primary-key"  fields?

According to the doc, you can put an item conditionally by checking if it already exists.
> You can perform a conditional put operation (add a new item if one with the specified primary key doesn't exist)

from https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-ConditionExpression

I don't know if this is a bug or something by designed. But I want the option to check if the item already exists, if so do not insert.

**Comment by yuth** [comment]
The `createXXX` mutation always checks for the key condition and will fail if there is a record with the same key. Its a pre-requiste for create mutation. If you look at the generated resolver you will see an statement like this below to enforce that

```
#set( $condition = {
  "expression": "attribute_not_exists(#id)",
  "expressionNames": {
      "#id": "id"
  }
} )
```

**Comment by yaquawa** [comment]
Sorry that's my bad... Thanks for the detailed info!
