### ISSUE TITLE
Add an option to add CRUD policies to DynamoDB Stream function

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6648]
copied from : https://github.com/aws-amplify/amplify-cli/issues/6581
Because I think this should be a feature request but not an issue report.

I've followed the doc to created a "DynamoDB Lambda Triggers".
https://docs.amplify.aws/cli/usage/lambda-triggers#dynamodb-lambda-triggers

But the policy lucks actions for using AWS SDK for DynamoDB like these:

```
"dynamodb:GetItem",
"dynamodb:Query",
"dynamodb:Scan",
"dynamodb:PutItem",
"dynamodb:UpdateItem",
"dynamodb:DeleteItem"
```

I don't want to use AppSync from the Lambda function, I'd rather like to use the AWS-SDK directly to perform some complex operations which it's not possible to accomplished with the graphql .

**Comment by SwaySway** [comment]
@yaquawa If you are looking to give your lambda function access to the dynamodb table then you can do so by adding selecting storage as a resource. From there you can select the model being used.

```bash
➜  bookstore git:(rev) ✗ a function add
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: getddbtable
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. storage
? Storage has 2 resources in this project. Select the one you would like your Lambda to access Entity:@model(appsync)
? Select the operations you want to permit on Entity:@model(appsync) (Press <space> to select, <a> to toggle all, <i> to invert selection)
 ◉ create
❯◉ read
 ◉ update
 ◉ delete
 ```

**Comment by yaquawa** [comment]
@SwaySway But that's just a regular function right?
I mean the ["DynamoDB Lambda Triggers"](https://docs.amplify.aws/cli/usage/lambda-triggers#dynamodb-lambda-triggers) lucks polices for using the aws sdk.

**Comment by SwaySway** [comment]
Since it's still a lambda function you are able to specify which resources it has access to.

**Comment by kaustavghosh06** [comment]
@yaquawa Please let us know if you're still stuck after @SwaySway's last response.
Closing this issue.
