### ISSUE TITLE
Wrong path separator on windows when pushing pre-existing schema.

### ISSUE THREAD

**Issue by nagyv** [aws-amplify/amplify-cli#665]
**Describe the bug**
I've tried to move from my own AppSync setup to Amplify, thus I was using my existing schema file when I added the `api` plugin. When I tried to push the changes, an erroneous `/` appeared in the path, despite being on windows.

**To Reproduce**
1. Use windows
2. Run amplify api add
3. Please select from one of the below mentioned services: GraphQL
4. Provide API name: whatever
5. Choose an authorization type for the API: Amazon Cognito User Pool
6. Do you have an annotated GraphQL schema? Yes
7. Provide your schema file path: tmp\schema.gql
8. run `amplify push`

**Expected behavior**
The Appsync API is created in the AWS console.

**Screenshots**
This is the error message:
```
GraphQL schema compiled successfully. Edit your schema at C:\Users\Viktor\Projects\BalanceWebApp\amplify\backend\api\balancewebapp/schema.graphql
× An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, scandir 'C:\Users\Viktor\Projects\BalanceWebApp\amplify\backend\api\balancewebapp\build\resolvers'
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The auth plugin was already configured and pushed before.

**Comment by kaustavghosh06** [comment]
@nagyv Which version of the CLI are you using? You can check using the `amplify -v` command.

**Comment by nagyv** [comment]
I'm using 0.1.38



Kaustav Ghosh <notifications@github.com> ezt írta (időpont: 2019. jan. 7.,
H, 19:14):

**Comment by kaustavghosh06** [comment]
@nagey Can you upgrade to the latest version of the CLI and try this out? I beleive we fixed this issue in the lates version. Feel free to re-open this if you're still seeing the issue.

**Comment by nagey** [comment]
I think you mean @nagyv

**Comment by nagyv** [comment]
Thanks. It works.
