### ISSUE TITLE
Failed to start API Mock endpoint Error: Duplicate schema type name EmailAddress

### ISSUE THREAD

**Issue by CurtisHumphrey** [aws-amplify/amplify-cli#6656]
**Describe the bug**
I've upgraded from v 4.21.3 to 4.43.0 and now my scheme will not compile in mock mode.  The error is
`Failed to start API Mock endpoint Error: Duplicate schema type name EmailAddress`

The type is defined as:
```
type EmailAddress
  @model(queries: null, subscriptions: null)
  @auth(
    rules: [
      { allow: groups, groupsField: "company_id", operations: [read] }
      { allow: groups, groups: ["admin"] }
      { allow: groups, groups: ["reader"], operations: [read] }
    ]
  )
  @key(name: "by_personnel", fields: ["personnel_id", "type"]) {
  company_id: ID!
  id: ID!
  personnel_id: ID!
  type: String!
  email: AWSEmail!
}
```

If I change the name to EmailAddress2 it works and runs in mock mode but it breaks our code because the autogenerated names change.  In Amplify Console, it builds just fine so this is just a mock mode issue.

**Amplify CLI Version**
4.43.0

- OS: [e.g. Mac/Windows/Ubuntu]
MacOs: 10.15.7
Node: 14.1.0

**Comment by yuth** [comment]
This is caused because we are using [`graphql-scalar`](https://github.com/aws-amplify/amplify-cli/blob/edd8e68e36600834ef9eaab6911e4a1111e90238/packages/amplify-appsync-simulator/src/schema/appsync-scalars/index.ts#L177) which creates a scalar with the same name
