### ISSUE TITLE
Headless Amplify CLI prompts for profile / access keys despite being defined in bash script

### ISSUE THREAD

**Issue by JonathanMSifleet** [aws-amplify/amplify-cli#6657]
**Describe the bug**
When attempting to setup Amplify using a [headless configuration](https://docs.amplify.aws/cli/usage/headless), and setting the useProfile key to false and using my access keys I am still prompted to select whether I wish to use a profile or access keys.

[image](https://user-images.githubusercontent.com/41328055/108231961-323f8e80-713a-11eb-8e1c-602ae3e0bc2c.png)

The script works fine on MacOS but I do not have access to a Mac.

**Amplify CLI Version**
4.44.0

**To Reproduce**
After setting up WSL and Ubuntu the script I attempted to use is as follows:

```
#!/bin/bash
REACTCONFIG="{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm build\",\"StartCommand\":\"npm start\"\}"
AWSCLOUDFORMATIONCONFIG="{\"configLevel\":\"project\",\"useProfile\":false,\"accessKeyId\":\"[my access key]\",\"secretAccessKey\":\"[my secret access key]\",\"region\":\"eu-west-1\"\}"
AMPLIFY="{\"projectName\":\"automatedAmplifyTest\",\"envName\":\"jonathan\",\"defaultEditor\":\"code\"}"
FRONTEND="{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":${REACTCONFIG}\}"
PROVIDERS="{\"awscloudformation\":${AWSCLOUDFORMATIONCONFIG}\}"
amplify init --amplify "$AMPLIFY" --frontend "$FRONTEND" --providers "$PROVIDERS" --yes
amplify status
amplify push
```

**Expected behavior**
The expected output should read something like this:
```
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
Note: It is recommended to run this command from the root of your app directory
Using default provider  awscloudformation
✔ Initialized provider successfully.
Initialized your environment successfully.
Your project has been successfully initialized and connected to the cloud!
```

OS: Windows 10 1909. 
WSL: Ubuntu 20.04.1 LTS, branch 19h1_release
Node Version. v14.15.5

**Comment by PawanKolhe** [comment]
Was able to reproduce the issue. On Git Bash it's working fine, but WSL2 with Ubuntu is prompting all the questions.

Reproduced issue on:
- Host OS: Windows 10 20H2 (OS Build 19042.804)
- WSL2 OS: Ubuntu 20.04.1 LTS (Focal Fossa)
- Node version: v15.9.0

![image](https://user-images.githubusercontent.com/8324407/108370750-ffbd9080-7222-11eb-9343-bb0b69f44557.png)

**Comment by JonathanMSifleet** [comment]
@PawanKolhe May I ask how you were able to get it to run using Git Bash? I get this error:
`C:\Users\jonathans\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found`

**Comment by PawanKolhe** [comment]
> @PawanKolhe May I ask how you were able to get it to run using Git Bash? I get this error:
> `C:\Users\jonathans\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found`

So I saved the script as `amp.sh` and ran `bash amp.sh` from Git Bash and it worked. Maybe you have [this issue](https://github.com/nodejs/node/issues/29287#issuecomment-524859390), not sure.

![image](https://user-images.githubusercontent.com/8324407/108390143-5e403a00-7236-11eb-8641-445bc8d2c162.png)

**Comment by yuth** [comment]
@JonathanMSifleet the headless parameter is malformatted and not a valid JSON. If you update your script as below the script should work as expected
```sh
#!/bin/bash
REACTCONFIG="{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm build\",\"StartCommand\":\"npm start\"}"
AWSCLOUDFORMATIONCONFIG="{\"configLevel\":\"project\",\"useProfile\":false,\"accessKeyId\":\"AKIA***\",\"secretAccessKey\":\"****\",\"region\":\"eu-west-1\"}"
AMPLIFY="{\"projectName\":\"automatedAmplifyTest\",\"envName\":\"jonathan\",\"defaultEditor\":\"code\"}"
FRONTEND="{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":${REACTCONFIG}}"
PROVIDERS="{\"awscloudformation\":${AWSCLOUDFORMATIONCONFIG}}"
amplify init --amplify "$AMPLIFY" --frontend "$FRONTEND" --providers "$PROVIDERS" --yes
amplify status
amplify push
```

Feel free to comment/re-open if this does not work

**Comment by JonathanMSifleet** [comment]
That worked! Thank you so much I can't explain how grateful I am
