### ISSUE TITLE
EACCES error after creating a new function

### ISSUE THREAD

**Issue by theAndrewCline** [aws-amplify/amplify-cli#6658]
**Describe the bug**
After creating a function and pushing. The function produces this EACCES error for the function file.

` Lambda execution failed with status 200 due to customer function error: EACCES: permission denied, open '/var/task/index.js'`

by changing all of the source file permissions I can work around this issue. `chmod -R 755 src`

**Amplify CLI Version**
4.43.0

**To Reproduce**
create a new function and push

**Expected behavior**
The function should just work out of the box.

- OS: MacOS
- Node Version 14.15.2

**Comment by edwardfoyle** [comment]
Hi @theAndrewCline does this error happen when running `amplify mock function` or when executing in the cloud? It seems like a local file permissions issue as I am unable to reproduce on my machine. Can you try creating a new function and see if the issue persists there as well?

**Comment by theAndrewCline** [comment]
It happens when executing in the cloud. Not when running `amplify mock function`

**Comment by theAndrewCline** [comment]
@edwardfoyle I also change my global prefix for npm and yarn to be ~/.local so all my packages are installed in ~/.local/.bin

I was wondering if that might be the issue.

**Comment by edwardfoyle** [comment]
@theAndrewCline it's possible that's related but that should only affect globally installed packages, not local ones. Does this happen if you add a new function, select one of the template, push without editing the function and then test it in the lambda console?

**Comment by theAndrewCline** [comment]
@edwardfoyle yes it does.

**Comment by edwardfoyle** [comment]
@theAndrewCline does the user that you are using in your shell have limited file system permissions? The .zip file that is uploaded to lambda will have the same permissions as the files on the local machine

**Comment by theAndrewCline** [comment]
@edwardfoyle to my knowledge the shell permissions have not been modified so they should be the default. I will verify with my companies it team and let you know if they have been.

**Comment by theAndrewCline** [comment]
@edwardfoyle I confirmed I just have a default MacOS admin account.

**Comment by edwardfoyle** [comment]
@theAndrewCline When you create a new function, what are the permissions on the `index.js` file?

**Comment by theAndrewCline** [comment]
Here the permissions are `-rw-------` for index.js

**Comment by theAndrewCline** [comment]
@edwardfoyle I think we can close this as it seems to be more related to my computer settings and not a cli issue. 

My umask settings for the system are not the default for some reason.

Thanks so much for your help!

**Comment by edwardfoyle** [comment]
Just for reference, the permissions on the `index.js` file when I create a function are `-rw-r--r--` which matches the permissions documented by lambda. More information on the issue can be found here: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-deployment-package-errors/

I think if you set the default unmask to 644 on your machine it should work:
https://support.apple.com/en-us/HT201684
