### ISSUE TITLE
UpdateMutations always requires id as one of the parameters even it's not the primary partition key

### ISSUE THREAD

**Issue by jncheung** [aws-amplify/amplify-cli#6662]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

`UpdateMutations` always requires `id` as one of the parameters even it's not the primary partition key

Sample schema : 

```GRAPHQL
type UsersEntity
@key (fields:["userID", "sortKey"])
@key(fields: ["isDeleted", "DeletedAt"], name: "deletedUsers", queryField: "listDeletedUsers")

@auth (rules:[
  { allow: private , operations: [create, read, update]},
  { allow: private , provider: iam, operations:[create, read] }
])
@model 
{
  id: ID 
  userID: ID!
  sortKey: ID!
  phoneNumber: String!
  firstName: String
  lastName: String
} 
```

```GRAPHQL
export const updateUsersEntity = /* GraphQL */ `
  mutation UpdateUsersEntity(
    $input: UpdateUsersEntityInput!
    $condition: ModelUsersEntityConditionInput
  ) {
    updateUsersEntity(input: $input, condition: $condition) {
      id
      userID
      sortKey
      itemType
      phoneNumber
      firstName
      lastName
      _version
      _deleted
      _lastChangedAt
    }
  }
`;

```

```typescript
export type UpdateUsersEntityInput = {
  id: string,
  userID: string,
  sortKey: string,
  itemType?: enum_UserItemType | null,
  phoneNumber?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  _version?: number | null,
};
```
**Expected behavior**
Since I have defined `userID` and `sortKey` as my primary key, I am expecting to use only `userID` and `sortKey` to update the data via Graphql

**Amplify CLI Version**
`4.43.0`

**Desktop (please complete the following information):**

- OS: Mac
- Node Version : `12.19.0`

**Additional context**

I have also enabled the conflict resolution for the DataStore

**Comment by leaky** [comment]
+1, I'm also seeing this. Is this expected behaviour?

**Comment by jncheung** [comment]
@leaky, this issue has been resolved in recent version. i think it was around `4.48.0`.

and yes, this is an expected behaviour if you are using DataStore in your application.

I have this issue because of I am not using DataStore and was trying to integrate single table design with amplify API GraphQL
