### ISSUE TITLE
Installation broken because of package "package" (that's literally the name)

### ISSUE THREAD

**Issue by snaiperskaya96** [aws-amplify/amplify-cli#667]
**Describe the bug**
Running `sudo npm install -g @aws-amplify/cli@multienv --verbose` returns 
```
npm http fetch GET 200 http://registry.npmjs.org/package 26ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 21410ms
npm verb type range
npm verb stack package: No valid versions available for package
```
And breaks the installation. It can be worked around using yarn but you'd run into an issue where you cannot select any service when doing init or configure (the solution was in fact to use npm instead of yarn)

**To Reproduce**
1. `sudo npm install -g @aws-amplify/cli@multienv --verbose` (It happens even without `@multienv` btw)

**Expected behavior**
Installation should be successful 
**Screenshots**
![image](https://user-images.githubusercontent.com/5279281/50790577-32140a00-12b7-11e9-9966-f8dd16a56e31.png)

**Desktop (please complete the following information):**
 - OS: "KDE neon" (Ubuntu 18.04)

**Comment by snaiperskaya96** [comment]
The reason the installation breaks is because this package has been retired/deleted/whatever and is not available anymore http://registry.npmjs.org/package 
Thanks npm

**Comment by kaustavghosh06** [comment]
Oh wow. Trying to figure out which dependency is using this.

**Comment by timgivois** [comment]
It seems that package is no longer supported [url](https://github.com/vesln/package).

**Comment by kaustavghosh06** [comment]
Hey guys, looks like npm put back the package "package" and I was able to install the CLI successfully again after not able to install it for the last hour. 
Guess, it was a momentary npm glitch.
