### ISSUE TITLE
me-south-1 not supported

### ISSUE THREAD

**Issue by enleet** [aws-amplify/amplify-cli#6671]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Region  me-south1 (Bahrain) is not listed in Amplify CLI

**Amplify CLI Version** 
4.41.2

**What AWS Services are you utilizing?**
AppSync, DynamoDB

**Provide additional details e.g. code snippets**
Im using Amplify CLI to link an AppSync to my app using :
amplify add codegen --apiId , I'm getting the note that : (AppSync API was not found in region..etc), so I chose to select from the list however, the region I have my AppSync and DynamoDB configured on is not even within the list : me-south1 (Bahrain)

How do I link the AppSync API in this case ?

**Comment by enleet** [comment]
> Hi @enleet. Can you confirm that Appsync service is available in me-south-1?

No I still don't see it , have you changed anything  ?

**Comment by enleet** [comment]
> > Hi @enleet. Can you confirm that Appsync service is available in me-south-1?
> 
> No I still don't see it , have you changed anything ?

So I'm still waiting for a response here ...its more than a month now since I raised this .. still don't know what exactly is happening here

**Comment by enlife6** [comment]
here is another thing also related 

when run "amplify api add-graphql-datasource" you don't get region  me-south-1 in list .. 

The strange thing on the console you can create RDS and AppSync in that region separately but you can't link them also ..because when you try to create new data source for the AppSync you also can't see that region 

is that a bug ? or something you guys are working on ? when need some clarifications to know which direction we should move

**Comment by enleet** [comment]
Hi guys ?

any update on the me-south-1 support ?

**Comment by enleet** [comment]
Hey Guys ... its taking weeks and week without getting any response .. what can a one do to get a reply ?

**Comment by a777med** [comment]
The issue is still there. I need to use Amplify in this region specifically.

**Comment by a777med** [comment]
How come the same region exists in the Amplify endpoints in this page [https://docs.amazonaws.cn/en_us/general/latest/gr/amplify.html](url) ?
amplify.me-south-1.amazonaws.com
