### ISSUE TITLE
Error on checking out backend environment

### ISSUE THREAD

**Issue by kadiyala9999** [aws-amplify/amplify-cli#6672]
Amplify version : 4.44.0
```bash
amplify env checkout staging
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at getCognitoConfig (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:257:48)
    at Object.keys.forEach.service (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:115:37)
    at Array.forEach (<anonymous>)
    at getAWSExportsObject (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:112:39)
    at createAWSExports (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:79:25)
    at Object.createFrontendConfigs (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:32:16)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:20:33)
    at Object.initializeEnv (/home/ec2-user/.nvm/versions/node/v10.20.1/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:100:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by SwaySway** [comment]
@kadiyala9999

Could you provide a few more details that lead up to this event?
 - Including the resources you have created in your project
If possible can you include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Comment by kadiyala9999** [comment]
I modified the oAuthMetadata in parameters.json under auth category which was pointing the logout and redirect URLS to master when I was on test environment and did "amplify push". From there I am getting an error while checking out the environment. I was able to do "amplify push" locally and "amplify status" shows correct environment even after the error. But when we try to build on amplify console, it fails with the error below.
 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-02-22T17:39:30.008Z [INFO]: [0mAmplify AppID found: d25ut3u9pcq9sv. Amplify App name is: vcms-clips[0m
2021-02-22T17:39:30.066Z [INFO]: [0mBackend environment staging found in Amplify Console app: vcms-clips[0m
2021-02-22T17:39:31.673Z [INFO]: [31mFailed to pull the backend.[39m
2021-02-22T17:39:31.675Z [INFO]: [31mCannot read property 'join' of undefined[39m
2021-02-22T17:39:31.677Z [INFO]: [0mTypeError: Cannot read property 'join' of undefined[0m
                                 [0m    at getCognitoConfig (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:257:48)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:115:37[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at getAWSExportsObject (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:112:39)[0m
                                 [0m    at createAWSExports (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/frontend-config-creator.js:79:25)[0m
                                 [0m    at Object.createFrontendConfigs (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:32:16)[0m
                                 [0m    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:20:33)[0m
                                 [0m    at Object.generateFiles (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a40-generateFiles.ts:44:25)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:30:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:57:5)[0m
2021-02-22T17:39:31.694Z [ERROR]: !!! Build failed
2021-02-22T17:39:31.694Z [ERROR]: !!! Non-Zero Exit Code detected
2021-02-22T17:39:31.694Z [INFO]: # Starting environment caching...
2021-02-22T17:39:31.695Z [INFO]: # Uploading environment cache artifact...
2021-02-22T17:39:31.790Z [INFO]: # Environment caching completed
Terminating logging...

{
    "identityPoolName": "vcmsclips",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "vcmsclxxxx",
    "userPoolName": "vcmsclips",
    "autoVerifiedAttributes": [
        "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
        "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
        "email"
    ],
    "userpoolClientReadAttributes": [
        "email"
    ],
    "userpoolClientLambdaRole": "vcmsclxxxxxx_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "useDefault": "manual",
    "authSelections": "identityPoolAndUserPool",
    "resourceName": "vcmsclips",
    "thirdPartyAuth": false,
    "usernameAttributes": [
        "email"
    ],
    "userPoolGroups": false,
    "adminQueries": false,
    "triggers": "{}",
    "hostedUI": true,
    "userPoolGroupList": [],
    "authRoleArn": {
        "Fn::GetAtt": [
            "AuthRole",
            "Arn"
        ]
    },
    "unauthRoleArn": {
        "Fn::GetAtt": [
            "UnauthRole",
            "Arn"
        ]
    },
    "parentStack": {
        "Ref": "AWS::StackId"
    },
    "permissions": [],
    "dependsOn": [],
    "hostedUIDomainName": "clips-xxxx",
    "authProvidersUserPool": [],
    "hostedUIProviderMeta": "[]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"https://clips.xxxxx.com/\"],\"LogoutURLs\":[\"https://auth.clips.xxxxx.com/login?response_type=code&client_id=xxxxxxxxxxxxxxxxx&redirect_uri=https://clips.xxxxxxx.com/\"]}"
}

**Comment by edwardfoyle** [comment]
It looks like your `amplify-meta.json` file has gotten out of sync with the changes you made. Make sure that the following is present in that file as well (note that the key in this file is "OAuthMetadata" whereas the key in the `parameters.json` file is "oAuthMetadata"
```json
{
  "auth": {
    "<auth resource name>": {
      "output": {
        "OAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"https://clips.xxxxx.com/\"],\"LogoutURLs\":[\"https://auth.clips.xxxxx.com/login?response_type=code&client_id=xxxxxxxxxxxxxxxxx&redirect_uri=https://clips.xxxxxxx.com/\"]}"
      }
    }
  }
}
```
Did you manually modify the files or was there a CLI flow that led to the files being in this state?

**Comment by kadiyala9999** [comment]
@edwardfoyle Yes. It looks like the file was out of sync. I was on "test" environment and the parameters.json and amplify-meta.json has oAuthMetaData pointing to production logout and redirect URL's. I am not sure how it went to this state but when I observed it's pointing to wrong URL's, I did change to correct one and from there I am seeing this issue.

**Comment by edwardfoyle** [comment]
@kadiyala9999 Just to confirm, you are still seeing this issue after updating both the `amplify-meta.json` file and `parameters.json` file in the auth category?

**Comment by kadiyala9999** [comment]
@edwardfoyle Yes. I am still seeing the same error.

**Comment by edwardfoyle** [comment]
@kadiyala9999 In that case it seems like it's probably an issue when the `amplify-meta.json` file in your `#current-cloud-backend` folder. After running `amplify env checkout staging` can you send a zip file of the following files to amplify-cli@amazon.com:
```
#current-cloud-backend
  amplify-meta.json
  auth
    <auth resource name>
      parameters.json
backend
  amplify-meta.json
  auth
    <auth resource name>
      parameters.json

```

**Comment by kadiyala9999** [comment]
@edwardfoyle Sent.

**Comment by kadiyala9999** [comment]
@edwardfoyle Any update on this.

**Comment by edwardfoyle** [comment]
Hi @kadiyala9999 sorry for the delay. I took a look at the files you sent and it looks like the issue is you do not have any "LogoutURLs" defined in the OAuthMetadata. You can add them by running `amplify update auth`, select `Walkthrough all the auth configuration` then when you get to `Do you want to use an OAuth flow` select `Yes` and you can enter sign-in and sign-out redirect URLs

**Comment by kadiyala9999** [comment]
@edwardfoyle It's working now. Appreciate your help!
