### ISSUE TITLE
Creating subscriptions for custom mutations doesn't seem to work

### ISSUE THREAD

**Issue by seanim0920** [aws-amplify/amplify-cli#6677]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

GraphQL Schemas

**Amplify CLI Version** 

4.44.0

**Provide additional details e.g. code snippets**

I've tested creating subscriptions for regular mutations (creation, update, deletion) by adding code like this to the schema:

```
type Subscription {
  didUpdate: Type @aws_subscribe(mutations: ["updateType"])
}
```

Like how is done here: https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js

That works. Now I want to create a subscription for a custom update mutation I've made by following this guide (https://docs.amplify.aws/cli/graphql-transformer/resolvers), but putting the mutation name in that "mutations" array doesn't work. Has anyone done this before? I also tried making new resolvers for this new subscription but that didn't seem to help.

**Comment by yuth** [comment]
@seanim0920 could you share an minimal schema and share what you're customizing in your resolvers

**Comment by seanim0920** [comment]
Here:

`type Thing @model
{
  id: ID!
  counter: Int
}

input UpdateThingInput {
  id: ID!
  counter: Int
}

type Mutation {
  incrementCounter(input: UpdateThingInput!): Thing
}

type Subscription {
  didUpdate: Thing @aws_subscribe(mutations: ["updateThing"])
  didIncrementCounter: Thing @aws_subscribe(mutations: ["incrementCounter"])
}`

didUpdate will fire the subscription event when the normally generated updateThing operation occurs. didIncrementCounter will not, even if the resolver for incrementCounter is just a copy of the updateThing resolver.

**Comment by yuth** [comment]
@seanim0920 do you have resolvers attached to `incrementCounter` mutation using the custom stack as [documented](https://docs.amplify.aws/cli/graphql-transformer/resolvers#custom-resolvers)?

**Comment by seanim0920** [comment]
Yes the mutation works on its own, it's just the subscription to the mutation I can't get.

**Comment by yuth** [comment]
@seanim0920  I was able to get the custom subscription working with the [following project](https://github.com/yuth/custom-subscription-example). I am subscribing using the following query
```gql
subscription DidIncrement {
  didIncrementCounter {
    counter
    createdAt
    id
    updatedAt
  }
}

```

and when I do the following mutation, the subscription gets fired
```gql
mutation incrementCounter {
    incrementCounter(id: "1") {
    counter
    createdAt
    id
    updatedAt
  }
}
```

Could you clarify 
1. Your mutation has a selection set
2. Your subscription resolver is returning an object with `Thing` shape


You can see the the resolver that I have for increment [here](https://github.com/yuth/custom-subscription-example/blob/main/amplify/backend/api/testinit/resolvers/Mutation.incrementCounter.req.vtl), which updates the object in table and the [response template](https://github.com/yuth/custom-subscription-example/blob/main/amplify/backend/api/testinit/resolvers/Mutation.incrementCounter.res.vtl) returns the full object back
