### ISSUE TITLE
Amplify DataStore and DocumentDB ?

### ISSUE THREAD

**Issue by ppave** [aws-amplify/amplify-cli#6678]
I need to fetch data from my backend and cache locally. And we have DocumentDB already set up.
Is it possible to use: DataStore > AppSync > Lamdas >  DocumentDB?
If that not supported by CLI, is it supported by using AWS interface at all?

**Comment by yuth** [comment]
Amplify CLI does not support Document DB out of the box. AppSync needs DynamoDB table to support DeltaSync.

DataStore is an [uses GraphQL](https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js) to as wire protocol and if you can implement DeltaSync and conflict resolution with your custom lambda and write appropriate resolver then this could be supported.

**Comment by ppave** [comment]
thank you, closing
