### ISSUE TITLE
Clarification required: Datastore and full offline work

### ISSUE THREAD

**Issue by marianolc** [aws-amplify/amplify-cli#6685]
**Which Category is your question related to?**

DataStore and AppSync

**Amplify CLI Version** 

4.44.0

**What AWS Services are you utilizing?**

DynamoDB

**Provide additional details e.g. code snippets**

Right now, the DataStore section in the documentation says the following:

>The CLI will prompt you to configure your API. Select GraphQL as the API type and reply to the questions as shown below. When prompted to configure advanced settings, respond Yes, I want to make some additional changes, and ensure that conflict detection is enabled. **Conflict detection is required when using the DataStore to sync data with the cloud**.

>Troubleshooting: **Cloud sync will fail without the conflict detection configuration.** To enable it for an existing project, run amplify update api and choose Enable DataStore for entire API.

This is not explicitly stated but does this mean that if I don't configure conflict detection DataStore will work completely offline? Or is it still going to constantly try to synchronize only that in those cases it will just fail?

Trying to add the api **without** Conflict detection I do the following:

```
#amplify add api
? Please select from one of the below mentioned services: **GraphQL**
? Provide API name: **xApi**
? Choose the default authorization type for the API **API key**
? Enter a description for the API key: **xKey**
? After how many days from now the API key should expire (1-365): **365**
? Do you want to configure advanced settings for the GraphQL API **Yes, I want to make some additional changes.**
? Configure additional auth types? **No**
? Configure conflict detection? **No**
? Do you have an annotated GraphQL schema? **No**
? Choose a schema template: **Single object with fields (e.g., “Todo” with ID, name, description)**
```

The process still ask for API Keys. It's ok I guess but If I try to do a push:

```
√ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Api      | xApi           | Create    | awscloudformation |

```

Why is trying to add the dynamoDB backend when appSync is supposedly not active?

**To add more information:**

Using and testing the android API there is a clear step that makes the AppSync to work or not:

`
Amplify.addPlugin(new AWSApiPlugin());
`

But using javascript I don't see such extra step to explicitly activate this feature.

**Comment by yuth** [comment]
@marianolc If you want to have local only data store based project you should follow the [Option 1: Platform integration](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#option-1-platform-integration) in our docs. Here you will be using `npx amplify-app` script which does not create an amplify project till you're ready to start syncing the DataStore to cloud.

**Comment by marianolc** [comment]
Hi @yuth  ! I've tried Option 1 but is not persistent. When I restart the app (using node + express ) the data is missing.

**Comment by kaustavghosh06** [comment]
@marcoreni From the flow above it looks like you've answered "No" to this question - `Configure conflict detection? **No**`
If you answer Yes, the data would be persisted locally for conflict detection.

**Comment by marcoreni** [comment]
@kaustavghosh06 For some reason I was tagged here, I assume the correct recipient was @marianolc  :D
