### ISSUE TITLE
Pipeline resolvers - reference to automatically generated resources

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#6692]
I want to convert the default resolver to pipeline resolver, but my schema.graphql doesn't contain any mutation - they are included in build/schema.graphql file. More precisely I would like to convert create resolver to be able to intercept it and include some validation functions that will run before the actual mutation is executed.
Currently the automatically generated mutation contains some condition which in turn contains model definition for each table field.
If I want to keep the condition of this mutation do I have to copy its whole definition from automatically generated schema? If so, how to be sure that in the future I keep all conditions of automatically generated mutations?
This all starts to be pretty complicated from this point.

If mutation is automatically generated in build/schema.graphql, do I have to overwrite its definition in my schema.grapql?
Can I just overwrite the automatically resolver in CustomResource.json? If so, then the original one contains references to multiple resources like the table, data source, IAM role...
How to reuse all of these resources without copying it and modify only the one resolver to change it's kind to pipeline and inject custom functions? Can I have references in my resolver (in CustomREsources.json) to resources that are defined (automatically generated) in
build/stacks/.json?

**Comment by akshbhu** [comment]
Hi @jk171505 

Seems like you want to overwrite current ```createResolver```. AFAIk you can create overwrite current resolvers in the ```<projectfolder>/api/resolvers/``` directory and when you call ```amplify api gql-compile``` amplify will directly copy the resolver in to build directly without overwriting it.
Here is the documentation that can help you : https://docs.amplify.aws/cli/graphql-transformer/resolvers.

Let me know if this answers your question?

**Comment by akshbhu** [comment]
Closing due to lack of response. Feel free to comment if you are stuck and I will reopen this again
