### ISSUE TITLE
DynamoDB and AWS Amplify does not sync for unknown reasons.

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#6697]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I'm trying to edit dynamodb directly but when I do a search query, I can see that the results does not update.

![image](https://user-images.githubusercontent.com/21032419/108645877-316a7c00-74ef-11eb-8126-895949a04a40.png)

**Amplify CLI Version**

N/A

**To Reproduce**

Unsure as well, looking for feedbacks on where to look, I've been googling for about 2 hours now and I can't find a definite solution.

**Expected behavior**

DynamoDB and Elastic Search should be in sync.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- OS: N/A
- Node Version: N/A

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**

This is a project that was initiated originally with an older version of amplify, so it's quite an old project, but I've upgraded this project the best I could, it's been dormant for months and now I'm just coming back to it.

**Comment by edwardfoyle** [comment]
@aprilmintacpineda The @searchable directive attaches a streaming function that is triggered off of DynamoDB changes and streams the change to the ES cluster. You can search CloudWatch for errors in that function which may explain why the ES cluster is out of sync. The lambda should be named `ddb_to_es`

**Comment by aprilmintacpineda** [comment]
@edwardfoyle I created a new environment and so far has not experienced this in that new environment, If we experience it again, I will post an update with the logs from `ddb_to_es` lambda as per your instructions.

**Comment by akshbhu** [comment]
Hi @aprilmintacpineda 

Good to know it worked for you. Closing this issue for now , if it occurs again feel free to comment and reopen this issue again.
Also you can check cloudwatch logs for erros in ```ddb_to_es```  lambda fn as @edwardfoyle mentioned.
