### ISSUE TITLE
Subscription on model with @auth(rules: [{ allow: owner }]) does not work

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#6699]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.43.0

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
I will use the Todo example provided by Amplify to demonstrate the issue.

* Define your type and add owner authorization to it
```
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
}
```

* Create a user pool and a user with password. Let's say the username is "TestUser"
* Open two browser windows with the AppSync console and login with the TestUser
* In the first window open a subscription
```
subscription MySubscription {
  onCreateTodo(owner: "TestUser") {
    id
    name
  }
}
```
* In the second window make a createTodo mutation
```
mutation MyMutation {
  createTodo(input: {name: "Do the dishes"}) {
    id
    name
  }
}
```

**Expected behavior**
I expect to see the data of the creation event in running my subscription.

**Current behavior**
No data is is shown. The subscription isn't triggered.

**Related issues**
I found a couple possibly related issues:
* [https://github.com/aws-amplify/amplify-cli/issues/3148](https://github.com/aws-amplify/amplify-cli/issues/3148)
* [https://github.com/aws-amplify/amplify-android/issues/186](https://github.com/aws-amplify/amplify-android/issues/186)

How can I trigger the subscription when using @owner auth?
Am I doing something wrong in my setup?

**Comment by edwardfoyle** [comment]
Hi @Nxtra you need to add the "owner" field to the selection set of the mutation and the subscription in order for the subscription to be triggered

**Comment by Nxtra** [comment]
> Hi @Nxtra you need to add the "owner" field to the selection set of the mutation and the subscription in order for the subscription to be triggered

Thanks, that did the trick!
