### ISSUE TITLE
Updating auth resource results in custom modules in PostConfirmation parameters.json being removed

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6701]
**Describe the bug**
I've got a post-confirmation lambda trigger where I've added a separate module of `create-new-user`(.js). This gets removed whenever I update auth. 

**Amplify CLI Version**
4.44.0

**To Reproduce**
Add a post-confirmation trigger. Create a new module i.e `create-new-user.js` in the lambda src directory. Add this new module to the comma-separated modules param in the functions `parameters.json` file. 
```
{
	"modules": "add-to-group,create-new-user",
	"resourceName": "yourProjectPostConfirmation"
}
```
Update auth lambda triggers and see that this new module is removed by Amplify.

**Expected behavior**
Custom modules can be added without worrying about whether they will be inadvertently removed.

Maybe have the option to add multiple "modules" with the CLI.

**Comment by edwardfoyle** [comment]
@kylekirkby Marking this an an enhancement because auth in general does not support updates very well (there are lots of cases where modified configuration will be overwritten) and we need to address this holistically. For now you'll have to make sure to add your custom module back to the parameters.json file if you go through the `amplify update auth` flow after making manual changes

**Comment by akshbhu** [comment]
Hi @kylekirkby 

You can also add one custom module with ```amplify update auth```
```
? What functionality do you want to use for Post Confirmation (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ Learn More
 ──────────────
 ◉ Add User To Group
 ◉ Create your own module
```
This will maintain your custom module while you do ```amplify update auth```

@edwardfoyle  is correct , if you want to add more modules , then after updating you need to add those in ```parameters.json``` file after update auth command.

**Comment by kylekirkby** [comment]
Hi @edwardfoyle / @akshbhu ,

Thanks for the update! I did see this option but for some reason, I thought it was one or the other 🤷🏼‍♂️.

Cheers!
