### ISSUE TITLE
Mock in Container - Error

### ISSUE THREAD

**Issue by aexei** [aws-amplify/amplify-cli#6703]
When I try to start the API for testing in docker container, I get the following error: 

`Failed to start API Mock endpoint UnknownEndpoint: Inaccessible host: localhost. This service may not be available in the us-fake-1' region.`

**Comment by edwardfoyle** [comment]
Hi @aexei what do you mean when you say "testing in docker container"? The CLI does not use docker for mock. Can you provide more details around what resources you have in your project and detailed repro steps that led to this error?

**Comment by aexei** [comment]
Hi @edwardfoyle,

For our CI/CD process, we use Gitlab Pipelines and have implemented various tests (e2e, intergration, ...). For this I want to mock the API within a Gitlab CI/CD job and then run the tests against the API. Gitlab uses one Docker container per job. Initializing Amplify and getting it ready works without problem, but when I run amplify mock I get the error. 
I know that in Gitlab localhost is blocked, so I created a custom Docker container. This is then executed inside the job. Unfortunately, nothing changes.  If I run the container on my Mac, everything runs without a problem.

Gitlab Job:

```
integration:
  stage: test
  services:
    - docker:19.03-dind
  image: docker:latest
  script:
    - docker run 
        --rm 
        -v ${PWD}:/data 
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        --env AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        notionug/docker-aws-amplify
        sh /data/.scripts/ci/runTestIntegration.sh
```

[Dockerfile.txt](https://github.com/aws-amplify/amplify-cli/files/6027113/Dockerfile.txt)
[init_project_ci.txt](https://github.com/aws-amplify/amplify-cli/files/6027123/init_project_ci.txt)
[runTestIntegration.txt](https://github.com/aws-amplify/amplify-cli/files/6027121/runTestIntegration.txt)

**Comment by aexei** [comment]
@edwardfoyle 

I have found a solution. Apparently one part (I suspect DynamoDB) does not work on Alpine Linux. I have adjusted my DOCKERFILE to amazon linux 2 and everything works
