### ISSUE TITLE
Unable to push any new changes

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-cli#6704]
**Describe the bug**
Unable to push any new changes in amplify . It show's an error of `Existing schema attributes cannot be modified or deleted.`

**Amplify CLI Version**
4.44.0

**To Reproduce**
Try to update auth and add a new user pool group
For detailed steps
https://youtu.be/IhXZ-Ekex1Y

Error messages 
```
UPDATE_FAILED      UserPool AWS::Cognito::UserPool Tue Feb 23 2021 00:55:49 GMT+0530 (India Standard Time) Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)

UPDATE_FAILED authchedarAuthTest AWS::CloudFormation::Stack Tue Feb 23 2021 00:55:52 GMT+0530 (India Standard Time) Embedded stack arn:aws:cloudformation:eu-west-2:251651594881:stack/amplify-chedarv2-staging-232034-authchedarAuthTest-14GAGGNY7CAL5/ed59d3a0-49fe-11eb-bd5a-023389416292 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [UserPool]. 

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25743418/108760477-b8613800-7573-11eb-86da-9d636dc9d1a1.png)
![image](https://user-images.githubusercontent.com/25743418/108760526-c747ea80-7573-11eb-94cf-3b899e662a7e.png)
![image](https://user-images.githubusercontent.com/25743418/108760576-d75fca00-7573-11eb-961d-c4027e043876.png)
![image](https://user-images.githubusercontent.com/25743418/108760605-e21a5f00-7573-11eb-8f53-89ecaf548185.png)

**Desktop**

- OS: Ubuntu in WSL2 
- Node Version - 12.18.4

**Comment by DevTGhosh** [comment]
Earlier it seemed to be an issue with user pool groups but I can't seem to push any new changes through the error is remaining the same on any change being pushed. 

On amplify pull I am seeing that this following files have been changed compared to my git 
 amplify > team-provider-info.json
 ```json
 "function": {
        "chedarAuthTestPostConfirmation": {
          "GROUP": "companyAdmin",
          "deploymentBucketName": "amplify-chedarv2-staging-232034-deployment",
          "s3Key": "amplify-builds/chedarAuthTestPostConfirmation-66664a7632346a4e494b-build.zip"
        }
      }
 ```
 
![image](https://user-images.githubusercontent.com/25743418/108764284-67077780-7578-11eb-9870-53794fcfda26.png)

2nd file amplify > function > chedarAuthTestPostConfirmation> src > chedarAuthTestPostConfirmation-cloudformation-template.json

```json
    "deploymentBucketName": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    }
 ```
 
![image](https://user-images.githubusercontent.com/25743418/108764487-ad5cd680-7578-11eb-8796-948cead9b6b1.png)

3rd file amplify > function > chedarAuthTestPostConfirmation> src > package-lock.json

old json 
```
    "follow-redirects": {
      "version": "1.13.1",
      "resolved": "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.13.1.tgz",
      "integrity": "sha512-SSG5xmZh1mkPGyKzjZP8zLjltIfpW32Y5QpdNJyjcfGxK3qo3NDDkZOZSFiGn1A6SclQxY9GzEwAHQ3dmYRWpg=="
    }
 ```

new json 
```
    "follow-redirects": {
      "version": "1.13.2",
      "resolved": "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.13.2.tgz",
      "integrity": "sha512-6mPTgLxYm3r6Bkkg0vNM0HTjfGrOEtsfbhagQvbxDEsEkpNhw582upBaoRZylzen6krEmxXJgt9Ju6HiI4O7BA=="
    }
```

![image](https://user-images.githubusercontent.com/25743418/108764687-ef861800-7578-11eb-9056-4ff791640f5f.png)

If I remove the changes amplify status shows that the function needs to be updated & the error from above repeats.

I had just upldated cli to version 4.44.0 before making the changes not sure if they caused the issue.

The issue seems similar too #4980. I had also updated the custom attribute to cognito user pool but that was a few months back.

**Comment by sharmaaditya570191** [comment]
I also faced the `Resource is not in the state stackUpdateComplete` while doing `amplify push` in a sample project where I followed the steps you mentioned but I was able to fix this by creating a new project and running `amplify configure` and `amplify init` again. Here is a reference of a similar issue - https://github.com/aws-amplify/amplify-cli/issues/82. Could you try after running `amplify configure` again?

**Comment by DevTGhosh** [comment]
@sharmaaditya570191 Thanks for the help but didn't work tried creating a new profile. New clone of of the project same error every time.

**Comment by sharmaaditya570191** [comment]
A possible issue I see is that custom attributes cannot be removed or changed once added to the user pool - https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes. I suggest you pull the latest successful deployment and give it a try.

**Comment by DevTGhosh** [comment]
@sharmaaditya570191 tried that but that's where the difference between the git tracked files and amplify files are coming in as mentioned here https://github.com/aws-amplify/amplify-cli/issues/6704#issuecomment-783649393

**Comment by sharmaaditya570191** [comment]
> I had also updated the custom attribute to cognito user pool but that was a few months back.

Did you try to reset it to the point just before you updated the custom attribute? 1 more option is to remove auth and then try to push.

**Comment by DevTGhosh** [comment]
I am hesitant to do that because that definitely will not be possible once the site goes in production which is quite soon. I will lose my job if I say I have to remove & reset auth for all users for the site to function further. A lot of my sites functionality is tied to a users custom attributes & it definitely isn't possible for me to remove or rollback auth & test. 

I would like to know what went wrong if a solution is possible or if a solution is not possible what can be done to make sure that it isn't a problem in the future. 

@ammarkarachi  please look into this as all my work is kind of stuck until a solution is suggested.

**Comment by sharmaaditya570191** [comment]
I was trying to find better solutions and just came across [this](https://github.com/aws-amplify/amplify-cli/issues/2753#issuecomment-599156217) where a user updated the `amplify-cfn-templates/auth` with the correct `auth-cloudformation-template.yml` file via S3 user interface and then he could run `amplify push` properly.

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

you mentioned you have added custom attributes before. Have you added these via AWS console or by manually making changes in Auth CFN?
Also can you take a diff  of ```auth-cloudformation-template.yml``` present in your deployment bucket in S3 as per mentioned by @sharmaaditya570191  and your local auth CFN file and see if anything is changed?

**Comment by DevTGhosh** [comment]
@akshbhu  For custom attributes I made the following changes in Amplify > backend > auth > multitenant > paramenters.json & cloudformation-template.yml

Changes made were 
parameters.json
```json
 "userpoolClientWriteAttributes": [
        "email",
        "name",
        "custom:tenantid"
    ],
 "userpoolClientReadAttributes": [
        "email",
        "name",
        "custom:tenantid"
    ],
 ```
    
 .....cloudformation-template.yml

```yml
Schema: 

        -
          Name: email
          Required: true
          Mutable: true

        -
          Name: name
          Required: true
          Mutable: true

        - 
          Name: tenantid
          Mutable: true
          AttributeDataType: String
```
On checking with s3 bucket there is no difference in stuff that I have already committed to git and s3 cloudformation-template.yml for auth. 

However there are these changes that have happened for function chedarAuthTestPostConfirmation-cloudformation-template.json

![image](https://user-images.githubusercontent.com/25743418/108907543-38f16880-7648-11eb-99bc-d6282925db5d.png)


![image](https://user-images.githubusercontent.com/25743418/108907600-4d356580-7648-11eb-9892-d6265463470d.png)


Amplify status while I am on a clean branch is showing that function chedarAuthTestPostConfirmation needs to be updated
![image](https://user-images.githubusercontent.com/25743418/108907785-8b328980-7648-11eb-96b1-57f372f81dc9.png)

when I try to amplify pull it gets all the stuff mentioned here https://github.com/aws-amplify/amplify-cli/issues/6704#issuecomment-783649393

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

The changes are due to this PR : https://github.com/aws-amplify/amplify-cli/pull/6358/files which we introduced to save s3key and bucketName in teamProvider file.

I dont think this change is causing above cognito error.This only updates functions CFN template to use Ref values.

I tried the same steps creating userpool with custom attributes and adding a userpool again but I am able to deploy successfully.

Can you also attach the log file of the failed deploy. it might be present ~/.amplify/logs/amplify-cli-<issue-date>.log and mail your amplify folder to amplify-cli@amazon.com redacting any secret information?

**Comment by akshbhu** [comment]
Can you also check what custom attributes are present on AWS console?

**Comment by DevTGhosh** [comment]
@akshbhu The attribute is showing up in cognito 
![image](https://user-images.githubusercontent.com/25743418/109090891-c6f94c00-7739-11eb-840c-76521b2b8c65.png)

My amplify logs of last 3 days when the problem started happening

[amplify-cli-2021-02-24.log](https://github.com/aws-amplify/amplify-cli/files/6040036/amplify-cli-2021-02-24.log)
[amplify-cli-2021-02-22.log](https://github.com/aws-amplify/amplify-cli/files/6040037/amplify-cli-2021-02-22.log)
[amplify-cli-2021-02-23.log](https://github.com/aws-amplify/amplify-cli/files/6040038/amplify-cli-2021-02-23.log)


I have also mailed you the amplify folder it will be from email id dev@chedar.fr

**Comment by DevTGhosh** [comment]
@akshbhu  any updates on the matter? Did you get the mail?

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

I think its some error in cognito , as I tried with same repro steps but it succeeds for me. Can you send me a RequestID  for the failed deployment (you can find this in Cloudwatch Logs). I can check with Cognito service what happened with this case.

**Comment by DevTGhosh** [comment]
@akshbhu  I don't have any failed deployment log from the last week but 3 months back in the same amplify env So sending request id's for that

**Staging** is the env in which the problems are occurring

- Log group `/aws/lambda/chedarAuthTestPostConfirmation-staging` - 2020-12-31 16:39:29 - Request id `4ce01d33-ca60-4561-8b61-4ef810064c90`
- Log group `/aws/lambda/amplify-chedarv2-staging-UpdateRolesWithIDPFuncti-10DFPSM938AL6` - 2020-12-29 23:27:04 - Request id `680a1065-5a16-4936-90f7-d062eb6ab5f6`
- Log group `/aws/lambda/amplify-chedarv2-staging-232034-authched-MFALambda-6JXFEAID4YGI` - 2020-12-29 23:25:55 - Request id `b7022742-1273-4a58-b74a-f7101891f820`
- Log group `/aws/lambda/amplify-chedarv2-staging-232034-au-RoleMapFunction-1A8AMEIBJGW1M` - 2020-12-29 23:27:29 - Request id `614d78b7-2b44-4eac-8668-1762787c9f8d`
- Log group `/aws/lambda/amplify-chedarv2-staging-2320-UserPoolClientLambda-1A88F8TQ2UYN8` - 2020-12-29 23:26:24 - Request id `fcc6b690-2937-448b-876b-387da62cd9fa`

**Comment by DevTGhosh** [comment]
@akshbhu please let me know if you find anything.

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

Apologies for the delay. I have asked the cognito service to look into requestId and see what went wrong. I will get back with updates on this.

**Comment by DevTGhosh** [comment]
@akshbhu thanks please do check and get back to me.

**Comment by DevTGhosh** [comment]
@akshbhu any updates on the matter?

**Comment by DevTGhosh** [comment]
@akshbhu @ammarkarachi  it's been a almost a month since I have asked for this issue at least let me know where the problem is arising from so I can work around it & make sure it doesn't happen again. Right now I am stuck, if I create a new amplify project and go into production I have no idea if the issue will reoccur and put our whole business at stake.

**Comment by akshbhu** [comment]
HI @DevTGhosh 

Thanks you for the patience. We are working with cognito team to resolve error.

The video above  showing error is different from the code you sent as it doesnt contains the updated userPool Group which lead to the error on Push.(video also has one more userPool group ```chedarAdmin```)
```
[
  {
    "groupName": "companyAdmin",
    "precedence": 1
  },
  {
    "groupName": "freelancer",
    "precedence": 2
  }
]
```

Is there anything there that might attempt to update the user pool and in the process delete an attribute from a User Pool?
From the video it looks like you just added a userPool group which leads to CFN error on push. Is there anyway you have updated customSchema attributes or any attribute in the userPool?

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

From the Code you sent, Custom Schema attributes in Auth are : 
```
      Schema:
        - Name: email
          Required: true
          Mutable: true

        - Name: tenantid
          Mutable: true
          AttributeDataType: String
``` 

As you mentioned in this comment : 

> @akshbhu For custom attributes I made the following changes in Amplify > backend > auth > multitenant > paramenters.json & cloudformation-template.yml
> 
> Changes made were
> parameters.json
> 
> ```json
>  "userpoolClientWriteAttributes": [
>         "email",
>         "name",
>         "custom:tenantid"
>     ],
>  "userpoolClientReadAttributes": [
>         "email",
>         "name",
>         "custom:tenantid"
>     ],
> ```
> 
> .....cloudformation-template.yml
> 
> ```yaml
> Schema: 
> 
>         -
>           Name: email
>           Required: true
>           Mutable: true
> 
>         -
>           Name: name
>           Required: true
>           Mutable: true
> 
>         - 
>           Name: tenantid
>           Mutable: true
>           AttributeDataType: String
> ```

Looks like the name attribute is missing , this why CFN is giving error ```Existing schema attributes cannot be modified or deleted.``` as you are modyfying the custom Attributes.

Can you include the name field i the custom Schema and try this again?
Let me know if this solves your problem?

**Comment by DevTGhosh** [comment]
Ok so I have been testing with the new cli version `4.46.0` and after a amplify pull and making changes it seems the issues have gone. It seems the issue was being caused by the `4.44.0` version which I was using at the time. I had just updated to that version before I started having this problems. I hadn't changed anything in the backend related to amplify in this time period so nothing has changed from my end except the amplify cli version. 

 I checked my code and I never had the name attribute in  `auth`  the example code I provided was a bit outdated. 
 
 I will do further testing tomorrow but it seems like it is working for now. Thanks a lot for your help. It is greatly appreciated @akshbhu.
 
 One last question are there breaking changes in amplify cli updates for minor updates like from `4.44.0` to `4.46.0` ? I will stick to a particular version if that's the case.

**Comment by akshbhu** [comment]
Hi @DevTGhosh 

Good to know that its working for you now. AFAIK there aren't any breaking changes in those version.
Closing this issue for now as it seems to be working. If it gets stuck feel free to comment and Ill open the issue again.

**Comment by ejferg** [comment]
We are having the exact same issue. We updated our custom attributes and groups. We deployed and it failed in the exact same way as @DevTGhosh same messages on all fronts.

**Comment by DevTGhosh** [comment]
@ejferg trying going back a couple of minor cli versions if you are on the latest version and use `amplify pull` and see if it works then. I wasn't able to pinpoint my issue but maybe this would work.
