### ISSUE TITLE
No options to choose when configure

### ISSUE THREAD

**Issue by alexbruno** [aws-amplify/amplify-cli#6709]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I'm running into a bug when using `amplify configure` to setup my project, there is no options to choose a backend provider.

**Amplify CLI Version**
`4.44.0`

**To Reproduce**
Just running `amplify configure`.

**Expected behavior**
Command should list options to configure a backend provider.

**Screenshots**
![image](https://user-images.githubusercontent.com/2638399/108800827-f27e0a00-7572-11eb-8981-d20472ca4589.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS (running into WSL2 on Windows 10)
- Node Version: 14.15.5 (latest LTS)

**Log output**
No relevant log output.

**Additional context**
...

**Comment by kaustavghosh06** [comment]
How did you install the CLI? Did you run `npm install -g @aws-amplify/cli`?

**Comment by alexbruno** [comment]
Yup, I did this way.

**Comment by PawanKolhe** [comment]
I wasn't able to reproduce this issue. I'm on Ubuntu 20.04.2 LTS (WSL2), Node v15.9.0.

**Comment by akshbhu** [comment]
Hi @alexbruno 

This shouldnt ask for backend provider as currently there is only ```awscloudformation``` as only supported provider.
This seems like a problem with your installation. 
Could you share the plugin.json file which should be located in <home-dir>/.amplify/plugins.json

**Comment by alexbruno** [comment]
Thanks guys!
It is exactly what I have here @akshbhu, no plugins.
I am noob using `amplify`, just started from docs tutorials and there is no mentions about plugins.
How can I solve this?

```
$ amplify plugin scan
Scanning for plugins...
The following official plugins are missing or inactive:
    awscloudformation: provider | amplify-provider-awscloudformation@4.39.0
    analytics: category | amplify-category-analytics@2.20.1
    api: category | amplify-category-api@2.29.1
    auth: category | amplify-category-auth@2.28.1
    function: category | amplify-category-function@2.30.0
    hosting: category | amplify-category-hosting@undefined
    hosting: category | amplify-console-hosting@undefined
    hosting: category | amplify-container-hosting@undefined
    interactions: category | amplify-category-interactions@2.6.1
    notifications: category | amplify-category-notifications@2.18.0
    predictions: category | amplify-category-predictions@2.7.1
    storage: category | amplify-category-storage@2.10.12
    xr: category | amplify-category-xr@2.7.1
    codegen: util | amplify-codegen@2.21.2
    flutter: frontend | amplify-frontend-flutter@0.3.0
    android: frontend | amplify-frontend-android@2.14.5
    ios: frontend | amplify-frontend-ios@2.18.7
    javascript: frontend | amplify-frontend-javascript@2.20.7
    mock: util | amplify-util-mock@3.28.0
Plugin scan successful
```

```
$ cat ~/.amplify/plugins.json
{
  "pluginDirectories": [
    "cli-local-node-modules",
    "cli-parent-directory",
    "global-node-modules"
  ],
  "pluginPrefixes": [
    "amplify-"
  ],
  "userAddedLocations": [],
  "lastScanTime": "2021-02-23T21:50:50.434Z",
  "maxScanIntervalInSeconds": 86400,
  "plugins": {
    "core": [
      {
        "packageName": "@aws-amplify/cli",
        "packageVersion": "4.44.0",
        "packageLocation": "/home/.../@aws-amplify/cli@4.44.0/node_modules/@aws-amplify/cli/",
        "manifest": {
          "name": "core",
          "type": "core",
          "commands": [
            "categories",
            "configure",
            "console",
            "delete",
            "env",
            "help",
            "init",
            "logout",
            "migrate",
            "plugin",
            "publish",
            "push",
            "pull",
            "run",
            "status",
            "uninstall",
            "upgrade",
            "version"
          ],
          "commandAliases": {
            "h": "help",
            "serve": "run",
            "ls": "status"
          }
        }
      }
    ]
  },
  "excluded": {}
}
```

**Comment by akshbhu** [comment]
Hi @alexbruno 

Can you try a golbal fresh install of ampify-cli using this command  : npm install -g @aws-amplify/cli?
Also after installing use ```which amplify``` to check if the cli is globally installed.

Let me know if this solves your problem?

**Comment by alexbruno** [comment]
Thank you!
I uninstalled `@aws-amplify/cli` and manually `rm` related bin files, so I did a fresh install and it worked.
