### ISSUE TITLE
How to replace a Cognito Userpool (to update settings)?

### ISSUE THREAD

**Issue by Stvad** [aws-amplify/amplify-cli#6710]
I'd like to create a new userpool and migrate the Amplify application to use it (because I need to enable case insensitivity for UserPool and frustratingly you can't change it on the live userpool. #4185 is related)

I'd like to userpool as a new way of driving auth for existing APIs/etc. But it does not seem to be possible to create a second userpool though Amplify CLI 

I'm basically re-opening #4387 as it didn't receive an answer

**Which Category is your question related to?**
Auth

**Amplify CLI Version**: 4.44.0

**What AWS Services are you utilizing?**
The ones relevant here: 
- Cognito
- API Gateway/Lambda
- S3

**Comment by Stvad** [comment]
Best approach I was able to thing of so far:
- create a new branch/environment changing the Cognito params before the first push
- set up the migration lambda in new env pointing to the old one
- when ready flip the dns name to point to the new environment

**Comment by ammarkarachi** [comment]
@Stvad You can use the feature flag to enable case insensitivity for a user pool. There is more info here https://docs.amplify.aws/cli/reference/feature-flags#enableCaseInsensitivity

**Comment by Stvad** [comment]
sure, that's not what this question is about. the issue is that cognito won't allow you to update existing userpools for whatever reason. so you must create a new one and do migration to it. the questions is how to do this with Amplify, while still keeping the userpool under Amplify management/switching APIs/etc access to be controlled by new userpool

**Comment by akshbhu** [comment]
Hi @Stvad 

Amplify doesnt support this out of the box .Cognito Migration handler is the AWS supported way for this. The CLI can only support adding the new user pool.(I guess you already know about this: https://aws.amazon.com/blogs/mobile/migrating-users-to-amazon-cognito-user-pools/)

The steps you mentioned should work.
Closing this issue as this is not amplify supported. Feel free to comment if you are stuck and Ill reopen this issue

**Comment by Stvad** [comment]
I see :( So creating a new env is the best available way?

Are there already feature requests to support creating second userpool in the same cognito app/change resource to switch to new userpool/etc?

**Comment by Stvad** [comment]
Going the new environment path now. It seems CLI does not allow you to create the migration trigger :( ?

![image](https://user-images.githubusercontent.com/81347/108953823-ae494300-7620-11eb-930f-1883a0fb52b9.png)
![image](https://user-images.githubusercontent.com/81347/108953827-b0130680-7620-11eb-8ea3-d567b2c12a75.png)
