### ISSUE TITLE
Backend amplify operations lead to repeated requests for "Select the authentication method you want to use:"

### ISSUE THREAD

**Issue by adam-nygate** [aws-amplify/amplify-cli#6713]
**Describe the bug**
Whenever executing an authorised amplify operation (amplify pull/push etc), the terminal prompts repeatedly for "Select the authentication method you want to use:"

**Amplify CLI Version**
4.44.0

**To Reproduce**
I used to receive an error about a token being expired/unavailable when the CLI was previously authenticated via Amplify Admin UI. I followed instructions in an issue to use `amplify logout` and to replace the default authentication method with AWS Profile/Access Key. After doing this, when utilising an amplify operation that requires authentication, I get repeated prompts to "Select the authentication method you want to use:". Selecting a choice (except Amplify Admin UI) leads to the prompt again (approx 2 or 3 times). Selecting Amplify Admin UI causes it to error out with the token being unavailable.

**Expected behavior**
The CLI should save my choice (or AWS Profile) and not re prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/4394852/108825821-66440500-75bb-11eb-9131-fea398e9cb90.png)

**Desktop (please complete the following information):**

- OS: Mac
- Node Version: v14.11.0

**Comment by akshbhu** [comment]
Hi @adam-nygate 

I tried amplify pull command and its working fine for me.I have following questions:
1. Can you provide me the steps you took or amplify commands you used before you hit this issue so that I can reproduce this on my end?
2. Are the multiple prompts showing up in amplify push/ pull commands in your case?

**Comment by adam-nygate** [comment]
> Hi @adam-nygate
> 
> I tried amplify pull command and its working fine for me.I have following questions:
> 
> 1. Can you provide me the steps you took or amplify commands you used before you hit this issue so that I can reproduce this on my end?
I believe the issue was introduced by:

1. [Received this error when using amplify CLI and followed the instructions](https://github.com/aws-amplify/amplify-cli/issues/6593) to`amplify logout`
2. After `logout`, used `amplify pull`
3. Was presented with repeated prompts for authentication methods (as shown in the screenshot).

> 2. Are the multiple prompts showing up in amplify push/ pull commands in your case?
Yes, multiple prompts (as shown in the screenshot)

Do you know where I can find the configuration of credentials used by amplify CLI so I can see if the file is malformed?

**Comment by jhockett** [comment]
> Do you know where I can find the configuration of credentials used by amplify CLI so I can see if the file is malformed?

Do you see `<project root>/.config/local-aws-info.json`? If you chose to use a profile, it should look like the following:

```json
{
  "<environment name>": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "<your profile name>"
  }
}
```

**Comment by adam-nygate** [comment]
`<project root>/amplify/.config/local-aws-info.json` reads:
```
{
  "main": {
    "configLevel": "amplifyAdmin"
  }
}
```

**Comment by adam-nygate** [comment]
> > Do you know where I can find the configuration of credentials used by amplify CLI so I can see if the file is malformed?
> 
> @adam-nygate Do you see `<project root>/.config/local-aws-info.json`? If you chose to use a profile, it should look like the following:
> 
> ```json
> {
>   "<environment name>": {
>     "configLevel": "project",
>     "useProfile": true,
>     "profileName": "<your profile name>"
>   }
> }
> ```

Updating `<project root>/amplify/.config/local-aws-info.json` to follow your template seems to resolve the issue

**Comment by jhockett** [comment]
@adam-nygate Glad to hear it's working! Which authentication method do you want to use ideally?

In the future, you can run `amplify configure project` to switch authentication methods instead of needing to manually edit the file.

**Comment by adam-nygate** [comment]
> @adam-nygate Glad to hear it's working! Which authentication method do you want to use ideally?
> 
> In the future, you can run `amplify configure project` to switch authentication methods instead of needing to manually edit the file.

AWS Profile. I would have presumed that the prompts to select an authentication method would have saved the preference to the json.
