### ISSUE TITLE
Cannot remove access to another resource from lambda function

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6719]
**Describe the bug**
I'm trying to remove Storage access from my pre-token cognito trigger function.

But when running `amplify update function`, I'm not able to deselect the API resource category:

```bash
 ⚙  god  ~/Git/resources.linaro.org   develop ±✚  aws2-wrap --profile ResourcesHubUser
--exec "amplify update function"
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update resourceshub5749acdaPreTokenGeneration
General information
| Name: resourceshub5749acdaPreTokenGeneration
| Runtime: nodejs

Resource access permission
- resourceStorage (read)

Scheduled recurring invocation
| Not configured

Lambda layers

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to.
 ◯ function
 ◯ ssm
 ◯ perms
 ◯ auth
 ◯ api
❯◯ storage
>> You must select at least one category
```

**Amplify CLI Version**
4.44.0

**To Reproduce**
Add a pre-token lambda trigger function. Add access to another resource category. Then try to remove this access. Instead you get a validation error stating that at least one must be selected?

**Expected behavior**
To be able to remove access to a resource.

**Comment by akshbhu** [comment]
Thanks for reporting it.
