### ISSUE TITLE
Most times I run amplify push - I'm now having to sign in to the Admin UI, which needs a workaround!

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6720]
**Describe the bug**
Prior to updatin amplify cli to 4.44.0, I could run `amplify push` without a care in the world. Now 99% of the time I'm having to sign in to the Admin UI??? Currently I've got delve into the network requests for the page that is opened in my browser, copy the JWT token and then run a curl command.  Why have pushing resources suddenly become a chore?

**Amplify CLI Version**
4.44.0

**To Reproduce**
Use amplify cli 4.44.0. Try and push resources and more often than not, you'll have to sign in to the Admin UI..!

**Expected behavior**
Push resources without needing to sign in to Admin UI

- OS: Windows/ WSL2 Ubuntu
- 
**Log output**
```
amplify push
⠦ Fetching updates to backend environment: develop from the cloud.Opening link: https://us-east-1.admin.amplifyapp.com/admin/xxxxxxxx/develop/verify/
⠙ Continue in browser to log in…
⠇ Fetching updates to backend environment: develop from the cloud.
```
**Additional context**
This never used to be this much effort!

**Comment by edwardfoyle** [comment]
The fix for this has been released in the latest version of the CLI. Please upgrade to the latest version.
