### ISSUE TITLE
amplify update storage -- add s3 trigger -- results to error when deploying

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#6726]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

I need to modify s3 storage, so I did: `amplify add function` then `amplify update storage` and added s3 trigger then chose the function I just created, it succeeds but when I push it, it results to an error:t

```
Following resources failed
                                 Resource Name: wrgds3bucket (AWS::S3::Bucket)
                                 Event Type: update
                                 Reason: Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: <hidden>; S3 Extended Request ID: <hidden>; Proxy: null)
                                 URL: <hidden>
```

**Amplify CLI Version**

Latest, this is happening on the amplify ci/cd

**To Reproduce**

1. Add S3 bucket.
2. Publish
3. Create lambda function
4. Publish
5. Update s3, attach lambda to trigger
6. Publish

**Expected behavior**

Should successfully update the s3 bucket.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: N/A
- Node Version: N/A

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**

**Comment by akshbhu** [comment]
Hi @aprilmintacpineda 

I tried with your steps mentioned above but it works fine for me.

Can you also put the logout mentioned in the template?

Also can you share amplifyMeta file redact any secret information present?

**Comment by aprilmintacpineda** [comment]
I will check.

**Comment by rajrajhans** [comment]
Hey @aprilmintacpineda, even I tried to reproduce and it worked fine on my end as well. I did the following steps: 

- `amplify add storage` (selected "No" for lambda trigger)
- `amplify push`
- `amplify add function` (selected NodeJS lambda function)
- `amplify push`
- `amplify update storage` (attached lambda function created previously as trigger)
- `amplify push`

And it deployed correctly. Have you done anything different than the above steps?

**Comment by aprilmintacpineda** [comment]
Hmmm, nothing really, that's all I did on my end, although, this project was initialized with an older version and I simply tried to upgrade it to the latest version, not sure if that could be a factor...

**Comment by rajrajhans** [comment]
> 
> 
> Hmmm, nothing really, that's all I did on my end, although, this project was initialized with an older version and I simply tried to upgrade it to the latest version, not sure if that could be a factor...

Are you still facing the issue?

**Comment by aprilmintacpineda** [comment]
I haven't tried it out yet, this can be closed, for now, I'll open it up again if it comes up....
