### ISSUE TITLE
`sort` argument of `@searchable` should be an array

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6729]
**Describe the bug**
According to https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after
the `sort` argument should be array type. If only give a single sort value, the "load more" feature could potentially skip items that have the same `sort` value.

For example

```gql
type Post @searchable {
  id: ID!
  viewCount: Int
  title: String
}

```

```gql
query MyQuery {
  searchPosts(
    limit: 1
    sort: {direction: desc, field: viewCount}
    nextToken: "3.0"
  ) {
    items {
      title
      viewCount
    }
    nextToken
  }
}
```

Think the `limit` as the value of the number of posts per page, because the limit is set to 1, even if there are billions of posts has `viewCount` equals to 3, you only get 1, because they have the same `viewCount` value.

To get the correct response, we should give the unique id as part of the sort argument:
```gql
query MyQuery {
  searchPosts(
    limit: 1
    sort: [
        {direction: desc, field: viewCount}
        {direction: desc, field: id}
    ]
    nextToken: ["3.0", "id_of_the_last_post_of_current_page"]
  ) {
    items {
      title
      viewCount
    }
    nextToken
  }
}
```

**Comment by akshbhu** [comment]
Hi @yaquawa 

Yes you are correct , this is definately an enhancement on our side. We are currently working on next phase of our transformers VNext which will include these enhancements :https://github.com/aws-amplify/amplify-cli/issues/6217.

For the workaround you can define the ```SearchablePostSortInput``` in your schema.grapql to be an array and make changes in the resolver to pass the unique id as you have shown above to get all the posts with same view count.

**Comment by yaquawa** [comment]
@akshbhu I've tried your method, but with no luck, I was thinking that "is this the limitation of AppSync itself" ?!  Amplify has no reason to implement it using just a single element array of the `sort` parameter..

**Comment by renebrandel** [comment]
Hi folks - we're planning on addressing this as part of our new GraphQL transformer. The approach is captured here in our RFC: https://github.com/aws-amplify/amplify-cli/issues/7546 love to hear your feedback!

**Comment by renebrandel** [comment]
This is now supported! https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#sort-search-result-over-multiple-fields
