### ISSUE TITLE
GSIs will be updated even if the api push operation fails

### ISSUE THREAD

**Issue by jncheung** [aws-amplify/amplify-cli#6735]
**Describe the bug**
I tried to update multiple GSIs in a single `amplify api push -y` and the cli returns errors
I then decided to push the GSIs one by one and this error comes up

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
`4.43.0`
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
```typescript
type My
 @key(fields: ["fieldsA", "id"], name: "byfieldsA")  -> update GSI @key(fields: ["fieldsA", "id"], name: "searchFieldsA")
 @key(fields: ["fieldsB"], name: "fieldsBByFieldsA")  -> update GSI  @key(fields: ["fieldsB", "id"], name: "searchFieldsB")
@model 
{
  fieldsA: ID!
  fieldsB: ID!

} 


```
```
amplify push -y
```
```
Attempting to add and remove a global secondary index at the same time on the OrganisationsTable table in the Organisations stack. 
An error occurred during the push operation: Attempting to add and remove a global secondary index at the same time on the OrganisationsTable table in the Organisations stack.
```

```typescript

type My
@model 
{
  fieldsA: ID!
  fieldsB: ID!

} 

```

```
amplify api push -y
```

```
UPDATE_FAILED      MyTable          AWS::DynamoDB::Table   Thu Feb 25 2021 10:34:43 GMT+0800 (Hong Kong Standard Time) Cannot perform more than one GSI creation or deletion in a single update
```

```typescript

type My
@key(fields: ["fieldsA", "id"], name: "searchFieldsA")

@model 
{
  fieldsA: ID!
  fieldsB: ID!

} 

```

```
amplify push -y
```

```
UPDATE_FAILED      MyTable                              AWS::DynamoDB::Table   Thu Feb 25 2021 09:15:37 GMT+0800 (Hong Kong Standard Time) Attempting to create an index which already exists (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: BGPMM05RHF8R4RCLJARUHC52K7VV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null
```

**Expected behavior**

Rollback to previous state prior to the push

**Desktop (please complete the following information):**

- OS: Mac `10.15.7 (19H510)`
- Node Version.`v12.19.0`
**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**
I went to the dynamodb console and the GSIs were already updated

**Comment by akshbhu** [comment]
Hi @jncheung 

There is a Feature flag that you need to switch to enable Multiple GSIs feature in AmplifyCli. Here: https://docs.amplify.aws/cli/reference/feature-flags#enableIterativeGsiUpdates
Can you check if you have enabled this in ```cli.json``` file present inside your project folder.

**Comment by jncheung** [comment]
@akshbhu i will give that a try. thanks.

**Comment by renebrandel** [comment]
https://github.com/aws-amplify/amplify-cli/issues/1406#issuecomment-748354434

I'm closing this issue as a duplicate. Please use the thread linked above as main thread for multiple GSI update discussion.
