### ISSUE TITLE
CI deployment fails - "Current environment cannot be determined"

### ISSUE THREAD

**Issue by Coteh** [aws-amplify/amplify-cli#6743]
**Describe the bug**
I have a frontend web app deployed using Amplify via Jenkins CI agent. It has three environments, but two of them are unable to be deployed via Jenkins. Upon running `amplify configure project`, I receive the error "Current environment cannot be determined".

**Amplify CLI Version**
4.44.1

**To Reproduce**
Setup an Amplify project and run the following command: (configure args based on your project)

```
amplify configure project --amplify '{"projectName":"myproject","envName":"prod","defaultEditor":"code"}' --providers '{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"myprofile"}}' --yes
```

**Expected behavior**
Amplify project should be configured and be ready for the `amplify init` command I run next in my CI pipeline.

**Actual behavior**
```
Current environment cannot be determined

Use 'amplify init' in the root of your app directory to initialize your project with Amplify

script returned exit code 1
```

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Node Version: 12.16.1

**Additional context**
My understanding is that I must run `amplify configure project` before `amplify init` to ensure everything's setup correctly before I run `amplify publish`. This error message appears contradictory to my understanding. This appears to be a bug as one of the environments works perfectly (configure project, init, and publish all run successfully) but the other two environments fail.

**Comment by akshbhu** [comment]
Hi @Coteh 

The error is actually correct. To set up an amplify project, first, you have to do an ```amplify init```. This command will initialize an amplify project with IAM roles, deployment bucket names, and frontend. Then you can do ```amplify configure project``` to change the setting for the previously initialized amplify project if needed.

```amplify configure``` helps you to setup aws profile to init an amplify project. This has to be done once if you want to use single aws profile.

Here is the documentation you might find useful:
for amplify configure; https://docs.amplify.aws/cli/start/install#configure-the-amplify-cli
amplify init: https://docs.amplify.aws/cli/start/workflows#initialize-new-project

**Comment by Coteh** [comment]
Thank you, will review the documentation.

I am able to deploy my project locally, is it possible that I need to run `amplify init` again?

**Comment by Coteh** [comment]
Swapped the two commands in my Jenkins pipeline and it seems to work now. It appears to use the same S3 hosting bucket rather than create a new one. I guess there must have been some thing in the backend that wasn't initialized properly.

Weird that having `amplify init` before `amplify configure project` is contradictory to other posts I've seen on this repo but it works now so I'll just leave it at that. Will open a new issue if something else happens, thanks.
