### ISSUE TITLE
Disable graphql queries and mutation generation without disabling ability to write custom queries / mutations (and subscriptions of course)

### ISSUE THREAD

**Issue by gruckion** [aws-amplify/amplify-cli#6747]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

API

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.44.0

**What AWS Services are you utilizing?**

AppSync, GraphQL, DynamoDB, CodeGen

**Provide additional details e.g. code snippets**

We have created an `API` and it is working fine and generating the graphQL queries for us. However the nature of our schema leads to the build in queries not be suitable and are noise in our project. I am aware that if I say I don't want my schema to support mutations then CodeGen will not produce the mutations. But it also blocks us from writing our own mutations against that schema.

> How can I disable the generation of these queries without disabling the possibility to carry out our own custom mutations, queries and subscriptions.

**Comment by akshbhu** [comment]
Hi @gruckion 

You can define your own input , mutation and queries in the ```schema.graphql``` and while doing ```amplify api gql-compile``` amplify wont touch any custom queries or mutation defined in schema and these custom queries/mutations will be present in build/schema.graphql along with autogenerated queries and mutation.

If you want to disble autogenerated queries /mutation, you can mark those as null in @model parameters.
```
type Post @model(queries: null, mutations: null, subscriptions: null) {
  id: ID!
  title: String!
  tags: [String!]!
}
```

This schema will stop autogenerated queries, mutations and subscriptions. For more information you can check here:https://docs.amplify.aws/cli/graphql-transformer/model#usage 

Furthermore if you want to change/ overwrite custom resolvers for the queries/ mutations you can see the documentation here.https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers

Let me know if this resolves your question?

**Comment by akshbhu** [comment]
Closing this as it seems to be answered. Feel free to comment if you are stuck and I will reopen this issue again.

**Comment by gruckion** [comment]
Will get back to you if we have any issue with this. But makes sense, thank you for the detail.
