### ISSUE TITLE
Anyway we can speed up the version check? :)

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#6751]
**Is your feature request related to a problem? Please describe.**

All the issues on here ask for which version of Amplify you are using yet on my machine it takes an age to spin up and report it. Would be nice if that was a bit speedier.

I know this isn't exactly mission critical but it just kills my flow when I'm mid reporting an issue and have to wait a minute for it to report v4.42

I assume its spinning up everything regardless as if its about to do some heavy lifting but ultimately its echo'ing out a constant or config file value, seems a bit over kill.

**Describe the solution you'd like**

Make a version check a special case where to skips booting everything up as normal and instead just gets the version and report is nice and quick.

**Describe alternatives you've considered**

Me just being more patient. But you know...DX matters! :)

**Additional context**

Amplify is really coming on nicely, keep it up folks.

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.

FWIW - if you're using cURL to install the Amplify CLI, in general the performance is significantly better.
