### ISSUE TITLE
EC2 Backed Functions

### ISSUE THREAD

**Issue by amirhajimirsadeghi** [aws-amplify/amplify-cli#6752]
**Is your feature request related to a problem? Please describe.**
- Cold start times on lambdas could reach > 1 second with large functions and Secrets Manager utilized to initializing the lambda. 
- Lambda Warmers help but aren't a perfect solution because it's not guaranteed that a new request will use a warmed lambda even if one exists.

**Describe the solution you'd like**
- Being able to deploy EC2 backed functions will allow for much faster functions since initialization will only happen on deployments and scaling with new instances

**Describe alternatives you've considered**
- No other viable solutions for managing secrets with a lambda other than secrets manager
- Lambda warmers don't guarantee faster API calls, just reduce the probability of cold start

**Additional context**
This is a suggestion to help with slow API calls when using API Gateway + Lambda Function to support my react app

**Comment by akshbhu** [comment]
Hi @amirhajimirsadeghi 

Thanks for the feature request.
You can also check our serverless container based deployments for your use case:
https://docs.amplify.aws/cli/usage/containers

**Comment by nubpro** [comment]
> Hi @amirhajimirsadeghi
> 
> Thanks for the feature request.
> You can also check our nonserverless container based deployments for your use case:
> https://docs.amplify.aws/cli/usage/containers

hold on a sec...
you meant to say serverless right?

**Comment by amirhajimirsadeghi** [comment]
@nubpro I'm not sure why the documents call it serverless containers. It looks like it uses AWS Fargate under the hood which just manages the deployment and scaling of EC2 instances on your behalf if I'm not mistaken. It'll operate differently from lambdas in that it'll initialize an instance for you once and will continue to use that until you need to scale.

Is this correct? @akshbhu

**Comment by edwardfoyle** [comment]
@amirhajimirsadeghi Yes it uses Fargate under the hood. Like all "serverless" things, it is only serverless in the sense that you don't directly manage the servers.

**Comment by renebrandel** [comment]
@amirhajimirsadeghi - any particular use case that our containers support can't achieve. From what it reads like, this could solve your concerns.

**Comment by amirhajimirsadeghi** [comment]
@renebrandel yes you're right! This takes care of my problem. I can close out the issue, thanks!

**Comment by amirhajimirsadeghi** [comment]
Hi all, how does one go about giving the container permission to access externally managed AWS resources? There doesn't seem to be any cloud formation generated when I use this functionality.

**Comment by amirhajimirsadeghi** [comment]
ignore my last comment, didn't realize you have to `amplify push` to generate the cloudformation
