### ISSUE TITLE
Can't run "amplify hosting add" correctly

### ISSUE THREAD

**Issue by lis186** [aws-amplify/amplify-cli#6757]
**Describe the bug**
Running `amplify hosting add` fails.  It show's an error of `Cannot read property 'config' of undefined`.

**Amplify CLI Version**
4.44.2

**To Reproduce**

run `amplify hosting add` in a amplify project

**Expected behavior**
Run correctly

**Screenshots**
<img width="2000" alt="Untitled" src="https://user-images.githubusercontent.com/635405/109390515-0ba90100-794d-11eb-96ab-212b386ce624.png">

**Desktop:**

- OS: macOS Big Sur 11.2.2
- Node Version: v15.10.0

**Comment by lis186** [comment]
It works on 4.38.2

**Comment by edwardfoyle** [comment]
This has been released in the latest version of the CLI
