### ISSUE TITLE
DataStore does not rebuild nested objects beyond a single level of depth

### ISSUE THREAD

**Issue by KyleBrost** [aws-amplify/amplify-cli#6759]
**Describe the bug**
I have graphql with "has-one" relationships with the following relationship

Event->ServiceRequest->Site

When the DataStore fires the ready event and I query ServiceRequest, I get all the ServiceRequests with the Site object populated.  If I query the Event, I get all the ServiceRequests populated without the Site populated.

**Amplify CLI Version** 4.44.2

**To Reproduce**

```
type Event
@model()
{
   id: ID!
   eventName: String
   serviceRequest: ServiceRequest! @connection
}

type ServiceRequest
@model()
{
  id: ID!
  serviceRequestName: String
  site: Site! @connection
}

type Site
@model()
{
  id: ID!
  siteAddress: String
}
```
Load some temporary data
```
let testEvent = await DataStore.query(Event);
console.dir(theEvent);
let testSr = await DataStore.query(ServiceRequest);
console.dir(testSr);
```

Notice testEvent.serviceRequest is populated but testEvent.serviceRequest.site is not defined.  But, testSr.site is defined.

**Expected behavior**
I should be able to access testEvent.serviceRequest.site.siteAddress when I query testEvent.

**Desktop (please complete the following information):**
- OS: Windows 10
- Node Version: v12.16.1

**Comment by edwardfoyle** [comment]
Hi @KyleBrost you may need to increase depth in your codegen configuration. You can run `amplify configure codegen` and enter a new number in response to:
```
Enter maximum statement depth [increase from default if your schema is deeply nested]
```
By default, this value is 2, but in your case I think 4 would be appropriate.

**Comment by KyleBrost** [comment]
> Hi @KyleBrost you may need to increase depth in your codegen configuration. You can run `amplify configure codegen` and enter a new number in response to:
> 
> ```
> Enter maximum statement depth [increase from default if your schema is deeply nested]
> ```
> 
> By default, this value is 2, but in your case I think 4 would be appropriate.

Hi Edward, this does not fix the issue. My understanding is that depth function is used to determine the depth when it launches the actual graphql queries.  If it designed to handle the nesting depth in DataStore it does not work. Mine is set to 10 levels and has no change in behaviour relative to my issue.

**Comment by edwardfoyle** [comment]
@KyleBrost Sorry, I was mistaken before, this is expected behavior when querying using DataStore. See: https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations

**Comment by KyleBrost** [comment]
@edwardfoyle it is not expected behaviour for 1to1 or has one relationships. The documentation is referring to 1 to many. 

The documentation says nothing about nested relationships. That is multiple 1 to 1 nest more than 1 level deep. 

This should be reopened.

**Comment by KyleBrost** [comment]
@edwardfoyle Can you reply to my previous comment as your reason for closing is countered by what the documentation says?
