### ISSUE TITLE
Change Amplify Pull Defaults

### ISSUE THREAD

**Issue by raffibag** [aws-amplify/amplify-cli#6760]
**Is your feature request related to a problem? Please describe.**
Seems that most folks are using `amplify pull` to incorporate an existing back-end environment into one or many new front-end clients. When using the command, however, the default answer to the question: `Do you plan on making changes to the backend environment` is `Y/n`. Considering answering "Y" when you meant "n" can really mess up your project (vs. the other way around), perhaps it'd be better to default the answer to that question to `y/N`.

**Describe the solution you'd like**
Default answer to the question `Do you plan on making changes to the backend environment` when using the `amplify pull` command should be `y/N` (i.e., "No").

**Comment by edwardfoyle** [comment]
Hi @raffibag thanks for the suggestion! We will consider the use cases here and decide if this change makes sense.

**Comment by renebrandel** [comment]
Thank you for your suggestion. Given that this enhancement hasn't gotten more traction, we're going to be closing this issue for now. If more people are running into this in the future, I'm more than happy to re-open this issue.
