### ISSUE TITLE
Remove confusing option when doing "amplify add storage" for iOS/Android

### ISSUE THREAD

**Issue by ruiguoamz** [aws-amplify/amplify-cli#6765]
**Is your feature request related to a problem? Please describe.**
According to this [issue](https://github.com/aws-amplify/amplify-ios/issues/1079)

When user executes command: `amplify add storage`, `Amplify CLI` is not able to detect the platform user chose, thus, the second option `NoSQL Database` showing confuses customer since native platform do not have apis in `StoragePlugin` that interact with NoSQL Database

**Describe the solution you'd like**
`Amplify CLI` is able to detect the platform user previously chose, if the platform is `iOS/Android`, then should only display one option: `Content (Images, audio, video, etc.)`,

**Additional context**
<img width="528" alt="Screen Shot 2021-03-01 at 17 27 29" src="https://user-images.githubusercontent.com/48600426/109582678-6bb9b780-7ab3-11eb-9b38-1ea24621898d.png">

**Comment by renebrandel** [comment]
Hi @ruiguoamz thank you for your feedback. A couple points:
- While you can't access the NoSQL (DynamoDB table) directly through the Amplify Android storage category, we do provide mechanisms for you to configure your backend with a DynamoDB table that you can attach to functions, or REST APIs. Similar to how Amplify CLI helps you provision Lambda functions (which aren't directly exposed to the libraries), it is a crucial component for introducing more advanced business logic for your app backend.
- Amplify-provisioned backends can be shared across multiple frontends, so we're limiting the platform-specific flows to only client-side operations like code generation etc. This ensure if there are multiple developers on your team, you'll get a consistent experience throughout all of their dev environments.

I'll keep this issue in mind if this feedback comes up more broadly. Currently, we don't have any plans to update this flow given the points above.
