### ISSUE TITLE
Cannot finish amplify configure with Admin UI on Windows

### ISSUE THREAD

**Issue by watilde** [aws-amplify/amplify-cli#6779]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.13.0

### Amplify CLI Version

4.41.2

### What operating system are you using?

Windows, macOS

### Amplify Categories

auth

### Amplify Commands

pull

### Describe the bug

When I pull a backend setup by Admin UI, that shows a login page and makes an error when proceed. The error message was “Failed to communicate with the Amplify CLI”.

### Expected behavior

Should success login.

### Reproduction steps

1. Finish tutorial on https://sandbox.amplifyapp.com/start#datastore
2. Login AWS management console
3. Move to Admin UI
4. Enable Auth from Admin UI
5. Run displayed amplify pull
6. Open browser and login via Admin UI
6. See the error

### Log output

Let me put screenshot instead since the error is captured in browser.
![Error](https://user-images.githubusercontent.com/1716463/109735755-9a947280-7c06-11eb-8348-103b30ada878.JPG)

This issue is related to https://github.com/aws-amplify/amplify-adminui/issues/134. I debug the issue and turned out we do use `express` server in `amplify-provider-awscloudformation` to listen POST request from Admin UI login page. The default of hostname is `localhost`, `0.0.0.0` and `127.0.0.1` on macOS, but Ubuntu on WSL2 on Windows allows only `localhost` by default. Since `127.0.0.1` seems to be coded in Admin UI console, we can specify the hostname in CLI.

Refs: reported by a developer - https://ginpen.com/2021/03/02/failed-to-communicate-with-the-amplify-cli/

**Comment by attilah** [comment]
@watilde Thanks for reporting the issue and also providing the PR, we look into it and it gets into the next release!
