### ISSUE TITLE
Filtering a list of data based off of multiple different attributes that a user may or may not apply

### ISSUE THREAD

**Issue by ShehryarKh** [aws-amplify/amplify-cli#6783]
How can I filter data by multiple attributes before its returned?
For example:
```
type Shirt @model
  id: ID!
  color: String!
  size: String
  brand: String
}
```

How would I be able to apply query that would filter by color and or size and or brand with respects to limit. 
I've run into issues where listShirts query would return only 5 items when I've set limit to 50. So I understand that its scanning 50 items and then adding the filters, the solution seems to be add a secondary index to fields and then run a query? Is there an example with adding multiple indexes ?
So if I were to add multiple indexes, how could I achieve this functionally with those indexes? what would it look like?

**Comment by edwardfoyle** [comment]
@ShehryarKh I'd encourage you to read our docs on @key https://docs.amplify.aws/cli/graphql-transformer/key if you haven't already. You can also read through the DynamoDB docs on GSIs to get familiar with some of the limitations of queries in non-relational databases: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html

If you want to filter on any combination of color size and brand you will probably have to do a scan (listShirts) with a filter. However, if you only need to query 2 fields at a time, you can create a GSI using @key to support those queries.

**Comment by ShehryarKh** [comment]
@edwardfoyle Thank you for the response, I am looking into it right now.

**Comment by ShehryarKh** [comment]
in my research, it seems to me that I should be using `@searchable` 

I should offload complex querying to Elasticsearch.  DynamoDB should continue to handle CRUD operations.

**Comment by edwardfoyle** [comment]
@ShehryarKh yes that is another option and would be appropriate if you need to handle complex query patterns
