### ISSUE TITLE
Possible to use different build commands for different target environments?

### ISSUE THREAD

**Issue by CharlieDigital** [aws-amplify/amplify-cli#6784]
**Which Category is your question related to?**

- Build and deploy
- Development environment configuration

**Amplify CLI Version** 

- 4.44.0

**What AWS Services are you utilizing?**

- AppSync
- S3
- DynamoDB
- Lambda

**Provide additional details e.g. code snippets**

Consider a scenario where I have multiple environments:

1. Dev/Sandbox
2. Demo/Integration
3. Staging/QA
4. Production

And I set the build command for the CLI as `npm run dev` for development, how can I configure this so that when I switch to demo using `amplify env checkout int`, it will run `npm run int` instead?  (Namely, the objective is to inject different configurations (URLs) for `process.env`; in this case, I am using a library for my front-end to inject the variables: https://github.com/quasarframework/app-extension-qenv/tree/dev/app-extension but it's not clear to me how this should mesh with the Amplify CLI build command configuration)

I'm aware that this is possible via Amplify Console using a .yml file, but not sure how this can be accomplished via the CLI.

**Comment by edwardfoyle** [comment]
Hi @CharlieDigital we currently don't support a way to configure per-environment build commands. However, the current environment name is stored in `<project root>/amplify/.config/local-env-info.json` so you could potentially write a build script that reads this value and branches based on that.
