### ISSUE TITLE
Can't create a new env, problem with the team-provider-info.json

### ISSUE THREAD

**Issue by iuyt9003** [aws-amplify/amplify-cli#6786]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

4.39.0

### What operating system are you using?

windows

### Amplify Categories

Not applicable

### Amplify Commands

configure, init, push

### Describe the bug

it's seems the team-provider-json doesn't fetch the s3Key and deploymentBucketName of the functions and then they can't be created. 

### Expected behavior

That the functions will have the s3Key and the deploymentBucketName.
they can't be created when I am trying to create a new version.

### Reproduction steps

1. Amplify init for a new env/ amplify env add
2. Amplify push -> Amplify push failed. 

### Log output

CREATE_FAILED               functionplatformauthCustomMessage AWS::CloudFormation::Stack Wed Mar 03 2021 21:14:37 GMT+0200 (Israel Standard Time) Parameters: [deploymentBucketName, s3Key] must have values        

The team-provider-info.json does not have them.

esource Name: XXXX203226-authRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled

Resource Name: XXX-203226-unauthRole (AWS::IAM::Role)
Event Type: update
Reason: Resource update cancelled

Resource Name: S3Bucket (AWS::S3::Bucket)
Event Type: create
Reason: XXXXX203226-develop already exists

Please Fix it, I can't create any new envs. and it's blocking me from working.

**Comment by iuyt9003** [comment]
![image](https://user-images.githubusercontent.com/23431551/109859722-f8a47280-7c65-11eb-8be8-a3824f4aa657.png)
Working Env,

![image](https://user-images.githubusercontent.com/23431551/109859774-06f28e80-7c66-11eb-8af6-e8d7679875c0.png)
Not Working Env

**Comment by jhockett** [comment]
@iuyt9003 did you downgrade the CLI to v4.39.0 after previously upgrading? 

Please upgrade your CLI to the latest version (4.44.2 as of writing) and see if you can create a new environment.

**Comment by iuyt9003** [comment]
yes yes, I did upgrated to 4.44.2 still the same, sorry before open the ticket was on different version. but i did update it before publishing this ticket.

**Comment by iuyt9003** [comment]
Unable to upload trigger files to S3
An error occurred during the push operation: Unable to upload trigger files to S3

CREATE_FAILED      functionplatformauthCustomMessage AWS::CloudFormation::Stack Thu Mar 04 2021 13:35:48 GMT+0200 (Israel Standard Time) Parameters: [deploymentBucketName, s3Key] must have values 
-- On other envs they are exists just here not.
I can't make any new envs this is a big issue for us now. blocked.

**Comment by edwardfoyle** [comment]
@iuyt9003 I was only able to repro this issue when downgrading to a previous version of the CLI after creating a new environment with the latest version. My steps were:
install v 4.39.0 => init project, add auth with triggers => push => install v 4.44.2 => create new environment => revert back to v 4.39.0 => push new environment => observe failure.

Can you ensure that you used the latest version of the CLI to create the new environment and push it?
I was able to resolve the issue by installing the latest version of the CLI again and pushing again

In general, once you start using a newer version of the CLI you should not go back to a previous version as the older version may not be able to interpret the changes that the new version made.

**Comment by iuyt9003** [comment]
Hey You right, I did it.
Admin UI blocked me. I had to reconfigure the project
with : Amplify configure project. 
And check the Authentication with the AWS profile. which working the best.
