### ISSUE TITLE
init fails with self-signed certificate error

### ISSUE THREAD

**Issue by Jsunny271** [aws-amplify/amplify-cli#6791]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.4

### Amplify CLI Version

4.44.2

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug
```
init failed
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'amplify.us-east-1.amazonaws.com',
  retryable: true,
  time: 2021-03-04T05:19:53.148Z
}
```

I am behind a company proxy . please suggest working solution.

### Expected behavior

Creation of user and IAM in backend after using amplify init command.

### Reproduction steps

using amplify init cmd

### Log output

```
# Put your logs below this line

```

Please provide the solution ASAP.

**Comment by edwardfoyle** [comment]
You'll likely need to supply a custom certificate to the Node process. See https://github.com/aws-amplify/amplify-cli/issues/2739#issuecomment-751908597

**Comment by Jsunny271** [comment]
@edwardfoyle  Which custom cert you are talking about? Localhost or amazon one?

Please describe briefly.

**Comment by edwardfoyle** [comment]
@Jsunny271 Your company proxy is likely presenting an SSL certificate that is signed by a certificate authority (CA) that Node is not aware of. You need to add the CA cert of whatever CA your company proxy is using so that Node can validate the certificate.

**Comment by Jsunny271** [comment]
Issue not resolved. Any other solution which can work?

**Comment by edwardfoyle** [comment]
There's not much we can do as this is an issue with you local Node configuration not recognizing the certificates presented by your proxy. Are you able to init a project when not connected to the proxy?

**Comment by Jsunny271** [comment]
It works fine without proxy.

**Comment by edwardfoyle** [comment]
Closing this as there isn't anything we can do. Please see https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs and if you are able to figure it out, consider following up here to help others who may also run into the issue when using a proxy.
