### ISSUE TITLE
Headless deploy does not generate statements

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#6794]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.44.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

publish

### Describe the bug

When I run `amplify publish` with CODEGEN configuration to generate the statements in src/graphql, then it does not generate these statements.

### Expected behavior

`mutations.js`, `queries.js` and `subscriptions.js` should be generated in `src/graphql`

### Reproduction steps

**init.sh**
```
#!/usr/bin/env sh
set -e
IFS='|'


REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"eu-west-1\"\
}"


AMPLIFY="{\
\"projectName\":\"fixer\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"


# AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
# AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY amplify plugin scan

amplify init --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --y
```

**publish.sh**
```


#!/bin/bash
set -e
IFS='|'

CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"javascript\",\
\"fileNamePattern\":\"src/graphql/**/*.js\",\
\"generatedFileName\":\"API\",\
\"generateDocs\":true\
}"

amplify push \
--codegen $CODEGEN \
--yes
```

`init.sh && publish.sh`

### Log output

```
Cannot find file '../../graphql/mutations' in ...
```

**Comment by siegerts** [comment]
Hi @Nxtra - thanks for taking the time to submit this!

A few thoughts - 

- Did you add a graphQL API to the project and enable `codegen`?  The above scripts do not enable `codegen` by default - you may need to use `amplify codegen add`.  

- If successful, the `codegen` output will be located in `src/graphql/**/*.js` of your project by default, unless this setting was configured differently when running `amplify codegen add` (above).

**Comment by Nxtra** [comment]
> Hi @Nxtra - thanks for taking the time to submit this!
> 
> A few thoughts - 
> 
> - Did you add a graphQL API to the project and enable `codegen`?  The above scripts do not enable `codegen` by default - you may need to use `amplify codegen add`.  
> 
> - If successful, the `codegen` output will be located in `src/graphql/**/*.js` of your project by default, unless this setting was configured differently when running `amplify codegen add` (above).

Hi @siegerts ,

Yep, I added the API category to the project. When I do a publish via `amplify publish --y` then the statements are generated. 
They then appear in src/graphql .

I have the issue of the missing statements explicitely for headless deploy.

**Comment by siegerts** [comment]
Hi @Nxtra, thanks for the update - labeling this as an `enhancement`.

Right now, there isn't an equivalent argument for `codegen add` in the headless CLI.  In the meantime, one workaround is to script the current CLI command (and selections) for `amplify codegen add` in your bash script after executing `amplify init
--amplify $AMPLIFY ...` .

Hope that this helps - thanks again for raising.

**Comment by Nxtra** [comment]
> Hi @Nxtra, thanks for the update - labeling this as an `enhancement`.
> 
> Right now, there isn't an equivalent argument for `codegen add` in the headless CLI. In the meantime, one workaround is to script the current CLI command (and selections) for `amplify codegen add` in your bash script after executing `amplify init --amplify $AMPLIFY ...` .
> 
> Hope that this helps - thanks again for raising.

What does `amplify codegen add` do? I thought I needed `amplify codegen statements` for which there is an equivalent in the headless workflow.

**Comment by siegerts** [comment]
`amplify codegen add` enables the functionality within the project that will allow statements to be generated.  

You can test this by running `amplify codegen statements` (CLI) after initializing an amplify project - you should see:

```
> amplify codegen statements                                                                                  
code generation is not configured. Configure it by running
$amplify codegen add

```

Some reference on the [`.graphqlconfig.yml`](https://docs.amplify.aws/cli/graphql-transformer/codegen)
