### ISSUE TITLE
add-graphql-datasource - aurora serverless - request template missing quotes for DELETE and UPDATE

### ISSUE THREAD

**Issue by gbrackman** [aws-amplify/amplify-cli#6798]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

13.13.0

### Amplify CLI Version

4.18.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

"amplify api add-graphql-datasource" fails to add required single quotes in request template DELETE and UPDATE statements when a string is used as the key.

### Expected behavior

Request templates should use correct SQL syntax for DELETE and UPDATE statements in the generated req.vtl files when a string is used as the key.

Example below. Single quotes are generated for the SELECT statement, but not the DELETE statement.

{
  "version": "2018-05-29",
  "statements":   ["SELECT * FROM Event WHERE event_id='$ctx.args.event_id'", "DELETE FROM Event WHERE event_id=$ctx.args.event_id"]
}

### Reproduction steps

Given an existing project with an api and a serverless database with a table:
amplify api add-graphql-datasource

### Log output

```
# Put your logs below this line

```

This was fixed for SELECT statements in issue #2133. The same logic should be applied for DELETE and UPDATE statements.

**Comment by edwardfoyle** [comment]
@gbrackman Thanks for reporting this! Marking as a bug. The line that needs to be updated is: https://github.com/aws-amplify/amplify-cli/blob/e1e07b245db0963c4655e646c53e7615febe2930/packages/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts#L279

**Comment by kaustavghosh06** [comment]
The fix for this is released and is a part of CLI version 4.47.1.
