### ISSUE TITLE
Add MFA authentication capabilities to amplify cli

### ISSUE THREAD

**Issue by chizou** [aws-amplify/amplify-cli#680]
**Is your feature request related to a problem? Please describe.**
The credentials to access the AWS account are not secured by another factors and they have are provisioned with admin capabilities. This makes our account extremely vulnerable if those credentials are somehow compromised.

**Describe the solution you'd like**
Update the CLI so that it can handle MFA tokens much like aws cli can

**Describe alternatives you've considered**
I don't know of any

**Additional context**
None

**Comment by hakanson** [comment]
How are you using MFA? 

Do you use the technique from https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/ ? where you run `aws sts get-session-token --serial-number arn-of-the-mfa-device --token-code code-from-token` and then update a named profile (e.g. [mfa]) in your `~/.aws/credentials`?  This might work after #709 is fixed and the `aws_session_token` is honored.

Or do you have a profile configured in `~/.aws/config` with `role_arn`, `source_profile` and `mfa_serial`?  This might require an update to `getRoleCredentials` in `amplify-provider-awscloudformation/lib/system-config-manager.js` to retrieve the serial number and pass along to `sts.assumeRole()` along with a token prompt.

**Comment by chizou** [comment]
I'm doing the latter.

**Comment by kaustavghosh06** [comment]
We launched support for MFA earlier this year which would solve this issue. Please take a look at our docs - https://aws-amplify.github.io/docs/cli/init#assuming-an-iam-role for more information.

**Comment by ericclemmons** [comment]
@kaustavghosh06 Is there updated documentation on how to enable MFA for all new users?

```console
❯ amplify add auth
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Do you want to enable any of the following capabilities?
Successfully added resource authmfa90ad2317 locally
```

It seems that I have to enable this through the Cognito admin?

**Comment by kaustavghosh06** [comment]
@ericclemmons This issue is tied to using AWS MFA as an authentication options for using of AWS user of the CLI :)
For your question, regarding Cognito, you have the walk through the "Manual configurations" or go through the `amplify update auth` flow and walkthrough all the configurations to explicitly enable MFA. We don't enable it by default for Cognito user pools.

**Comment by ericclemmons** [comment]
Ahhh, thanks @kaustavghosh06!  I originally went through "Defaults" with additional options, but this looks closer to what I wanted (excuse the <kbd>Ctrl-C</kbd>, CLIs don't let me go "back"):

> ![mfa](https://user-images.githubusercontent.com/15182/77798591-6eed2d80-7030-11ea-8fb9-ceb7b9cbc036.gif)
