### ISSUE TITLE
✖ There was an error initializing your environment.

### ISSUE THREAD

**Issue by andrewJermaine-ios** [aws-amplify/amplify-cli#6804]
Hi I'm trying to initialize amplify on a blank project as a test but I am getting an error. 
Everything seems to go as planned until the last line 
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
⠋ Initializing your environment: dev(node:66730) ExperimentalWarning: The fs.promises API is experimental
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/queue-microtask/index.js:1
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/queue-microtask/index.js:5:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)

I am using Xcode 12.4 
Amplify 4.44.2

**Comment by edwardfoyle** [comment]
@andrewJermaine-ios what version of Node are you using? Can you provide more details around the other options you selected during the init workflow?

**Comment by andrewJermaine-ios** [comment]
Thanks for getting back to me. 
Node --version = 11.4.0
My selections during the init workflow:
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifySetupTest
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Using default provider  awscloudformation
AWS access credentials can not be found.
? Setup new user (Y/n) (node:71484) ExperimentalWarning: The fs.promises API is experimental
? Setup new user Yes
Follow these steps to set up access to your AWS account:
Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue
Specify the AWS Region
? region:  us-west-2

Created a new user with no problem and set that user as default profile. Literally all goes well until that last line.
The workflow also makes the amplifyconfiguration.json and the awsconfiguration.json files right before this line fails. 
I tried this on amplify cli version 4.37.1 and got the same result.

**Comment by andrewJermaine-ios** [comment]
Dawg I updated my node to 15.11.0 and it worked. Thank you for the suggestion. Your team rocks.
