### ISSUE TITLE
AWS App-sync configuration for Complex Object Credentials

### ISSUE THREAD

**Issue by Chandher05** [aws-amplify/amplify-cli#681]
Right now my configuration aws-amplify
`Amplify.configure({ Auth: { userPoolId: 'ap-south-xxxx', region: 'ap-xxxxx-x', identityPoolId: 'xx-xxxx-x', userPoolWebClientId: 'xxxxxxxxxxxx', }, API: { 'aws_appsync_graphqlEndpoint': 'some url', 'aws_appsync_region': 'ap-xxxxx-5', 'aws_appsync_authenticationType': 'AWS_IAM', } });`

This above configuration takes care of AppSync calls for me, so I do not manually initialize a appsync client.
How do I configure Complex Object Credentials, So I can upload to S3 using AppSync with the above configuration.

**Comment by manueliglesias** [comment]
See awslabs/aws-mobile-appsync-sdk-js#336
