### ISSUE TITLE
Change environment variable of a lambda function

### ISSUE THREAD

**Issue by bhavinkamani-gt** [aws-amplify/amplify-cli#6816]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

What is the way to update environment variable. I tried directly changing value in function-parameters.json but on `amplify push` it did not propagate these changes to my lambda function. I then tried changing other files such as `team-provider-info.json`, `nested-cloudformation-stack.yml` without any luck. Finally I had to change the environment variable value through lambda console to make it work.

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.44.2

**What AWS Services are you utilizing?**
Lambda function, auth

**Provide additional details e.g. code snippets**

**Comment by attilah** [comment]
@bhavinkamani-gt currently you have to add your custom environment variable to the CFN template of the function in `amplify/backend/function/<function name>/<function name>-cloudformation-template.json` file like this:

![image](https://user-images.githubusercontent.com/230432/110530917-cf556d80-80cf-11eb-82ec-2905f10719b3.png)

And what you add there will be deployed with your function.

**Comment by nikhname** [comment]
This section in the docs will be useful here https://docs.amplify.aws/guides/functions/configuring-lambda/q/platform/js
Please comment or reopen if you have further questions
