### ISSUE TITLE
@aws_iam tag applied on types that are not configured to use IAM permissions

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-cli#6826]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.45.0

### What operating system are you using?

macOS Catalina

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

GrahpQL types that do not have `iam`auth rules, for example like `@auth(rules: [{ allow: owner }])` end up getting the `@aws_iam` tag in the generated schema. This seems to happen because they wrongly inherit it from a previous type.

If I revert to Amplify version 4.36.2 this does not happen.

This affects, at least, versions ` 4.41.2`, `4.44.2` and `4.45.0`

This bug was also reported on https://github.com/aws-amplify/amplify-cli/issues/6557 , the changes in https://github.com/aws-amplify/amplify-cli/commit/deb53bd36a0994d951f6e120c0b8f0b1ee0dfdc8 did not fix the issue with Auth permissions

### Expected behavior

The models with `@auth(rules: [{ allow: owner }])` should not get the `@aws_iam` tag in the generated schema after `amplify push`

### Reproduction steps

1. Create a schema with 2 models: one with iam permissions and the other without them. Put the one with `iam` in the top, I think order matters, like this:
```graphql
type User @model @auth(rules: [{allow: owner}, {allow: private, provider: iam}]) {
  profile_pic: S3Object
}

type Button @model @auth(rules: [{allow: owner}]) {
  image: S3Object
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```
2. `amplify push`
3. download the generated Schema from the appsync panel
4. the `Button` model wrongly has the `@aws_iam`

### Log output

```
# Put your logs below this line

```

**Comment by SwaySway** [comment]
@wvidana What is your default mode of authentication?
I tried to repro with the following auth mode
```json
"authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authfunkXXX"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
```

The build schema came out as follows for button
```gql
type User @aws_iam @aws_cognito_user_pools {
  id: ID!
  profile_pic: S3Object
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Button {
  id: ID!
  image: S3Object
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type S3Object @aws_iam @aws_cognito_user_pools {
  bucket: String!
  region: String!
  key: String!
}
```

**Comment by SwaySway** [comment]
@wvidana 
Ah ok - a few more questions here regarding the config of the project
- Are you using any custom resolvers?
- Custom Stacks?
- Does the schema use any appsync auth directives? (ex. `@aws_iam` `@aws_cognito_user_pools`)
- If possible can you provide your `transform.confg.json`? (located within api dir)

**Comment by wvidana** [comment]
@SwaySway 
 
>     * Are you using any custom resolvers?
Yes, a Lambda resolver acting as an API Endpoint
```graphql
type Query {
    api_name(body: CustomBody!, somefield: String): String @function(name: "myfunction-${env}")
}
```

>     * Custom Stacks?
Yes, but not on `api`, we have added some custom lines in:
  * `auth`: to solve circular dependency with lambda triggers https://github.com/aws-amplify/amplify-cli/issues/4568
  * `function`: same as `auth`, we needed some extra code to be able to create a PreSignUp trigger with access to the DynamoDB created by `api`
  * `storage`: only an output, to reference from other stacks
  * `custom`: we created a custom stack from scratch since we needed an SQS queue. We are currently moving that to another repository since the amplify project will not need access to it

>     * Does the schema use any appsync auth directives? (ex. `@aws_iam` `@aws_cognito_user_pools`)
No, at least not anything like `@aws_`. 
We are using:`@model`, `@auth`, `@key`, `@function` (the custom resolver) and `@connection`

>     * If possible can you provide your `transform.confg.json`? (located within api dir)
```json
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    },
    "StackMapping": {
        "QueryfoobarByUserResolver": "Foobar",
        "QueryfoobarByUserAcccessResolver": "Foobar",
        "QueryfoobarByStatusResolver": "Foobar"
    }
}
```

**Comment by nikhname** [comment]
@wvidana did you enable adminUI in your previous project?

**Comment by nikhname** [comment]
If admin UI is enabled, we auto-add the @aws_iam directive for the models to be accessible from the data manage section of Admin UI.

**Comment by wvidana** [comment]
@nikhname yes we did! That might explain it :)

Anyways, since I couldn't replicate the issue in a fresh new project, we ended up re-creating the whole project with the newest amplify, and things seems to be working fine.

**Comment by SwaySway** [comment]
Closing this issue - should you have run into more issues with this please comment below.
