### ISSUE TITLE
env sync prints help

### ISSUE THREAD

**Issue by kftsehk** [aws-amplify/amplify-cli#683]
**Describe the bug**
`amplify env sync` prints the help

**To Reproduce**
1. amplify init any project
2. `amplify env sync`

**Expected behavior**
According to the help, should do
> Syncs your environment with the current cloud environment.
Use the restore flag to overwrite your local backend configs with that of the cloud.

**Screenshots**
![image](https://user-images.githubusercontent.com/20808792/50895279-99a99100-1440-11e9-85eb-c504389f8207.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Amplify cli version: 0.2.1-multienv.22

**Comment by kaustavghosh06** [comment]
@kftsehk You can use `amplify env pull` instead of `sync`. We'll change the print statement in the CLI. Marking this as a bug.

**Comment by kaustavghosh06** [comment]
This issue is fixed in the latest version of the CLI.

**Comment by monaye** [comment]
@kaustavghosh06 
Looks like `sync` is no more available. Is there any way to push the added env to the cloud so the developers don't have to push manually but using Amplify Deploy to push the newly created env?
