### ISSUE TITLE
Ascii art collapsed

### ISSUE THREAD

**Issue by ginpei** [aws-amplify/amplify-cli#6833]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.1

### Amplify CLI Version

4.45.0

### What operating system are you using?

Ubuntu 20.04 (WSL2 on Windows10)

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

The ascii art shown when you run just `amplify` is collapsed (see attached image)

### Expected behavior

The ascii art should look beautiful

### Reproduction steps

Run `amplify` without args in CLI.

It occurred on VS Code Terminal in default window size with hidden side bar. In my Windows, full-width fonts are used (Japanese)

### Log output

```
# Put your logs below this line

```bash
$ amplify


| Category      |
| ------------- |
| notifications |
| analytics     |
| api           |
| auth          |
| function      |
| hosting       |
| interactions  |
| predictions   |
| storage       |
| xr            |
                                                                                                  
 █████╗ ███╗   ███╗██████╗ ██╗     ██╗███████╗██╗   ██╗    ███████╗██████╗  █████╗ ███╗   ███╗████
███╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗                                                           
██╔══██╗████╗ ████║██╔══██╗██║     ██║██╔════╝╚██╗ ██╔╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔═
═══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝                                                           
███████║██╔████╔██║██████╔╝██║     ██║█████╗   ╚████╔╝     █████╗  ██████╔╝███████║██╔████╔██║████
█╗  ██║ █╗ ██║██║   ██║██████╔╝█████╔╝                                                            
██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██║██╔══╝    ╚██╔╝      ██╔══╝  ██╔══██╗██╔══██║██║╚██╔╝██║██╔═
═╝  ██║███╗██║██║   ██║██╔══██╗██╔═██╗                                                            
██║  ██║██║ ╚═╝ ██║██║     ███████╗██║██║        ██║       ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║████
███╗╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗
╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚═╝╚═╝        ╚═╝       ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═══
═══╝ ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

…
```

Collapsed
![image](https://user-images.githubusercontent.com/355808/110404379-9b2c6f00-8033-11eb-933a-07d02cce93ae.png)

Looks good in wider screen
![image](https://user-images.githubusercontent.com/355808/110403555-20af1f80-8032-11eb-99a8-77d212128b48.png)

**Comment by watilde** [comment]
Full width font is often used in Japanese OS and might be in the other multibyte languages as well. We might want to consider to stop using ASCII or having `unicode-off` option as same as npm.

Refs:
+ https://docs.npmjs.com/cli/v7/using-npm/config#unicode
+ https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by attilah** [comment]
@ginpei thanks for the issue, I marked it as an enhancement.

**Comment by ginpei** [comment]
By the way, just curious though, I'm wondering how it's supposed to be. Would anyone please share how it look in the western environment?

**Comment by cjihrig** [comment]
It's supposed to say "AMPLIFY FRAMEWORK" like in https://user-images.githubusercontent.com/355808/110403555-20af1f80-8032-11eb-99a8-77d212128b48.png.

**Comment by ginpei** [comment]
So it just expects wider screen regardless font thing. Thank you so much!

**Comment by kaustavghosh06** [comment]
PR #6497 has been merged to remove the ASCII art and will be part of the next release.
