### ISSUE TITLE
Configure opens wrong URL to create IAM from tmux

### ISSUE THREAD

**Issue by ginpei** [aws-amplify/amplify-cli#6836]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm -g

### If applicable, what version of Node.js are you using?

v14.15.1

### Amplify CLI Version

4.45.0

### What operating system are you using?

Ubuntu 20.04 (WSL2 on Windows10)

### Amplify Categories

Not applicable

### Amplify Commands

configure project

### Describe the bug

`amplify configure` asks a new IAM user name, then open the URL for that. The URL in browser is wrong while the URL printed in console is correct.

e.g.

- `https://console.aws.amazon.com/iam/home?region=us-west-2#/users=final&accessKey&userNames=xxxxxxxx&permissionType=policies&policies=arn:aws:iam::aws:policy%2FAdministratorAccess` (wrong, in browser, shows IAM home instead)
- `https://console.aws.amazon.com/iam/home?region=us-west-2#/users$new?step=final&accessKey&userNames=xxxxxxxx&permissionType=policies&policies=arn:aws:iam::aws:policy%2FAdministratorAccess` (correct, in console)

For short, `#/users=final` vs `#/users$new?step=final`.

### Expected behavior

Open the correct URL so that user can create it quickly

### Reproduction steps

1. Move to the project directory in tmux
1. Run `amplify configure`
2. Proceed to "Specify the username of the new IAM user"
3. Input any username, and hit enter

### Log output

```
# Put your logs below this line

```

- The browser I use is Edge
- If ran `amplify configure` directly on WSL console, it does not open at all. **This happens only with tmux**
- tmux: https://github.com/tmux/tmux

**Comment by attilah** [comment]
@ginpei what is happening here is that the shell open detects the `$new?step` parts of the URL we are opening as an environment variable and tries to expand it, but as it is expands to nothing it just replaces it with nothing, hence that part of the URL is gone. At this point I don't know if it is a tmux thing or not.
