### ISSUE TITLE
How to enable CORS programatically on AWS RESTAPI?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6840]
I have a a REST API like this:

```js
const awsServerlessExpress = require('aws-serverless-express');
const app = require('./app');

const server = awsServerlessExpress.createServer(app);

exports.handler = (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};
```

Based on [this documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) if I want to activate the CORS I have to apply this changes:

```js
exports.handler = async (event) => {
    const response = {
        statusCode: 200,
        headers: {
            "Access-Control-Allow-Headers" : "Content-Type",
            "Access-Control-Allow-Origin": "https://www.example.com",
            "Access-Control-Allow-Methods": "OPTIONS,POST,GET"
        },
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

However, in the newest version of `AWS cli` it generates the `expirts.handler` like the first snippet of code; and it places the following code in `app.js`:

```js
// Enable CORS for all methods
server.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "*");
  res.header("Access-Control-Allow-Methods", "OPTIONS,POST,GET");
  res.header("Access-Control-Allow-Credentials", true);
  next();
});
```

However, this code does not activate the CORS on my API.

**The first question is, how can I add headers to `aws-serverless-express`?**

If you look at the bottom of the reference that I mentioned earlier, there is another link as [Enable CORS on a resource using the API Gateway console](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors-console.html).

If I follow that link, I can activate the CORS on my `AWS::ApiGateway::RestApi`. But this method is the last thing that I want to do. Why? Because by generating a new staging environment, I have to do those steps by hand again and document it somewhere and so on. 

My cloud formation template files are json and not yaml. I saw some documentations, that say it is possible to activate CORS via template files, like [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-api-cors.html#cfn-apigatewayv2-api-cors-allowheaders).

**Does anyone, know how can I activate CORS on my lambda function or api programatically in Node.js file or in a declarative way in `*-cloudformation-template.json` files?**

**Comment by attilah** [comment]
I think the first part of the question is related to `aws-serverless-express` package, please open the issue in their repository.

To get more familiar with the differences between JSON and YAML you can use the http://www.json2yaml.com/ tool.

Regarding API Gateway and CORS there are several 3rd party articles can be found.

If you have a CLI specific issue related to this, feel free to open a new issue with the exact problem.

**Comment by mjza** [comment]
Thanks for closing the ticket in advanced. The API has been made by cli. And the skeleton code and template files also made by cli. Let me ask my question in another way. How can I add CORS to REST API when I used `amplify add api` for generating an API?

**Comment by mjza** [comment]
@attilah Please reopen the ticket, I have not yet get my answer.

**Comment by mjza** [comment]
Here is the response header:

```
content-length: 261
content-type: application/json
date: Wed, 10 Mar 2021 09:01:02 GMT
via: 1.1 e1e056e45a0f8d6bc22b223900511170.cloudfront.net (CloudFront)
x-amz-apigw-id: b9qgNHX2IAMFfug=
x-amz-cf-id: bpAL_wZ0eAulxRJHcpXGdw0wLayg1SGzVSvrk0g9u-H3B2LbvEkLmQ==
x-amz-cf-pop: FRA2-C2
x-amzn-errortype: AccessDeniedException
x-amzn-requestid: 4aa5b176-5081-498a-9062-15c1e018cd30
x-cache: Error from cloudfront
```

**Comment by mjza** [comment]
No need to reopen the issue, but if you like create a ticket that it shows suitable error code. JS tells it is cors while it is not.
