### ISSUE TITLE
Cannot exceed quota for PoliciesPerRole error

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-cli#6846]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

4.45.0

### What operating system are you using?

linux (amplify console build)

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

 adding `{ allow: private, provider: iam }` @auth option on each 50+ graphql models causes the backend to fail with error `Cannot exceed quota for PoliciesPerRole: 10`

![image](https://user-images.githubusercontent.com/3125784/110556710-097b4980-817a-11eb-9c95-369ed6f7d07a.png)

### Expected behavior

This usually works for graphql with 4 models

### Reproduction steps

1. Have a graphql schema with 50+ models.
2. Append `{ allow: private, provider: iam }` @auth to each.
3. Do amplify push

### Log output

```
UPDATE_FAILED      GraphQLSchema    AWS::AppSync::GraphQLSchema Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource update cancelled
CREATE_FAILED      AuthRolePolicy06 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy08 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy14 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy09 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy02 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy04 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy07 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy03 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy01 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy11 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:22 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
CREATE_FAILED      AuthRolePolicy12 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:21 GMT+0000 (Coordinated Universal Time) Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: 586cc950-458a-4521-9099-da26719a5e0a; Proxy: null)
CREATE_FAILED      AuthRolePolicy10 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:21 GMT+0000 (Coordinated Universal Time) Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: f4804e41-b7b5-4ba6-8dab-8ec81ae1eca9; Proxy: null)
CREATE_FAILED      AuthRolePolicy05 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:21 GMT+0000 (Coordinated Universal Time) Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: 8f788ff0-0ccd-411a-9231-a365822669ca; Proxy: null)
UPDATE_COMPLETE    GraphQLAPIKey    AWS::AppSync::ApiKey        Wed Mar 10 2021 00:14:21 GMT+0000 (Coordinated Universal Time)
CREATE_FAILED      AuthRolePolicy13 AWS::IAM::ManagedPolicy     Wed Mar 10 2021 00:14:21 GMT+0000 (Coordinated Universal Time) Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: ddd71f1b-b488-420e-8526-8628b3a9419c; Proxy: null)
```

Upon checking api build director. Amplify generates 14 AuthRolePolicies under api stack:
![image](https://user-images.githubusercontent.com/3125784/110556643-e781c700-8179-11eb-9f34-3dd03cb69ec2.png)

**Comment by attilah** [comment]
@incr3m could you send your schema only to amplify-cli@amazon.com. We are looking into beside the quota increase how could we provide a different/other solution and a schema that causes this problem would be beneficial, if you cannot share it with us, no problem.

As you are hitting a default max quota limit, I marked it as an enhancement.

**Comment by pussyslain** [comment]
@attilah I have sent you the files.

**Comment by incr3m** [comment]
@attilah I have sent you the files

**Comment by kaustavghosh06** [comment]
@incr3m Please let us know if you were able to request a limit increase in your quota. This would enable you see to push 2x the amount of models you currently are trying to push.
