### ISSUE TITLE
I removed AdminQuery API and its function but it is still there. 

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6849]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

4.45.0

### What operating system are you using?

mac

### Amplify Categories

auth

### Amplify Commands

pull

### Describe the bug

I am using amplify v4.45.0. 

I removed the AdminQueries API with `amplify remove api`, and then I removed its function with `amplify remove function`, and finally pushed the changes. 
However, whenever I use `amplify pull` it will download a folder as `AdminQueries269127e5` inside my function folder. 

It is interesting that if I use `amplify remove api` or `amplify remove function` it does not show AdminQueries as an option anymore. How can I get rid of that function in the back-end completely?  

### Expected behavior

No AdminQueries remain anymore. 

### Reproduction steps

1. Generate a AdminQuery API with `amplify update auth`.
2. `amplify push`
3. Remove the admin query with `amplify update auth`.
4. It will remain there.

### Log output

```
# Put your logs below this line

```

**Comment by attilah** [comment]
@mjza I did executed these steps and I don't have any functions left in my project, works as expected. After the push with admin queries:
- update auth, manual configuration and say No to AdminQueries
- remove api
- remove function
- push

After this you only have empty `api` and `function` directories, but no function or anything in the project.

Retry the steps above and AdminQueries should be gone.

Closing the issue as it is working as expected and not reproducible
