### ISSUE TITLE
Amplify push failed on not authorized to perform cloudformations:DescribeStacks

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6851]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.10.1

### Amplify CLI Version

4.45.0

### What operating system are you using?

Windows/Ubuntu (WLS2)

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I've just tried to push my stack with the latest version and... what has happened?!?

Firstly, I needed to update some functions to a newer version of the NodeJS runtime, which is fine. I'm also now getting ApiID not in Outputs for a new resource that I was planning to push. I then tried to push again but I got the following error:

```
 god  ~/Git/resources.linaro.org   develop ±  aws2-wrap --profile ResourcesHubUser --exec "amplify push"
✖ There was an error pulling the backend environment develop.
An error occurred during the push operation: User: arn:aws:sts::xxxxxx:assumed-role/us-east-1_Llgylt720_Full-access/amplifyadmin is not authorized to perform: cloudformation:DescribeStacks
 ✘  god  ~/Git/resources.linaro.org   develop ±  aws2-wrap --profile ResourcesHubUser --exec "amplify push"
✔ Successfully pulled backend environment develop from the cloud.

Current Environment: develop

| Category | Resource name                          | Operation | Provider plugin   |
```

My question is, how can it fail once and then, on a second execution straight after, work? It might be worth looking into this...

### Expected behavior

No inconsistent behavior.

### Reproduction steps

This is going to be difficult since it worked straight after...?

### Log output

```

**Comment by attilah** [comment]
@kylekirkby I assume that you are running with a IAM user/profile which is using our predefined set of policies defined [here](https://docs.amplify.aws/cli/usage/iam). As we are adding new functionality to the CLI it is possible that requires additional policies to be added to that user, we always update this docs page with the latest ones.

The latest version has `DescribeStacks` defined, verify that your user's policy also has it.

**Comment by kylekirkby** [comment]
@attilah the funny thing is, though, I have the permission in my `amplifyadmin` role. It worked on a subsequent execution of `amplfiy push` which is very strange.

**Comment by attilah** [comment]
That is really strange indeed, as the problem solved I am closing the issue if something comes up, feel free to comment or open a new one.
