### ISSUE TITLE
Default Values in GraphQL Schema

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#6852]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

4.44

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

Add support for default values in GraphQL schemas.

## Example
In the following schema, I would like to have `dataScrubbing` enabled by default.

```graphql
type Flow @model  {
  dataScrubbing: Boolean
}
```

the following is spec'ed for input params but does not seem to work:

```graphql
type Flow @model  {
  dataScrubbing: Boolean = true
}
```

it throws the following:

```
Syntax Error: Expected Name, found =

GraphQL request:895:26
894 |   # Enable server-side data scrubbing
895 |   dataScrubbing: Boolean = true
    |                          ^
896 |
```

## Related Materials
- https://discuss.dgraph.io/t/schema-migration-default-values-for-fields/11178/6
- https://stackoverflow.com/questions/51563960/how-to-add-default-values-to-input-arguments-in-graphql

### Expected behavior

Ability to add default values for a schema definition.

### Reproduction steps

NA

### Log output

```
# Put your logs below this line

```

**Comment by attilah** [comment]
@amcdnl As @cjihrig said it is only supported for `input` members and currently not supported by the CLI, but with a custom directive you can achieve the expected behavior that suit your needs. I mark it as an enhancement.

**Comment by amcdnl** [comment]
Ya - I think that would be good.

**Comment by cjihrig** [comment]
GraphQL Transformer v2 was released recently with a new `@default` directive for this use case. I'm going to close this as resolved.
