### ISSUE TITLE
Restore table from both on demand and point in time

### ISSUE THREAD

**Issue by gruckionvit** [aws-amplify/amplify-cli#6855]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

API

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.44.2

**What AWS Services are you utilizing?**

AppSync, DynamoDB

**Provide additional details e.g. code snippets**

Once I restore all my tables using either `on demand backups` or `point in time recovery` how do I then get that data into the table with the original name.

1. Do I delete the table resource and then restore the table with the original name?
2. Do I empty the table then copy all the data from `restored` table into `original` table?

Can you please document this workflow DynamoDB has left it up-to the developer it seems but it would save us developers a bunch of time if you provided a least a proposed workflow. What flow can I follow in order to restore my tables data into the table with the same name.

**Comment by attilah** [comment]
It seems that this issue is strictly related to DynamoDB operations and not CLI related, I would suggest to post in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131) to get help from folks who are subject matter experts in this area.
