### ISSUE TITLE
how to achieve dynamic @auth?

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-cli#6861]
**Amplify CLI Version** 
4.45.0

**What AWS Services are you utilizing?**
DataStore

Assuming I have the following schema: 

```graphql
type Space
  @model {
  id: ID!
  name: String
  about: String
}

type Post @model  @auth(rules: [{ allow: groups , groups: ['editors'], operations: [update]}]) {
  id: ID!
  spaceId: ID!
  title: String!
  content: String
}
```

How can I define different @auth rules for different spaceIds? In fact, I want the "editors" group to be able to update posts only if the posts belong to SpaceID = x. And have different auth rules for SpaceId = y ... . In other words I want to scope auth to spaceIds. 

Is this achievable with the current implementation?

thank you

**Comment by attilah** [comment]
@mdegrees it depends on your scenario, that kind of authorization could be done if you can add the `spaceId` to the claims of the users during Cognito token generation and then with a custom resolver verify the Claim and either allow or deny the given operation. Similar to your case other customers documented a possible [solution](https://github.com/aws-amplify/docs/issues/2317) that you could adopt.

**Comment by mdegrees** [comment]
@attilah does the token refresh in "real time"? If the user hops from a space to another, joins and leaves spaces quite often, would writing the user membership state to the token still be a viable option?

**Comment by attilah** [comment]
No it would not be good for that scenario as Access Tokens usually valid for days.

But for these kind of dynamic authorization you can leverage perhaps what we support already to use `groups` as allow, but don't specify a static groups list in the `@auth` directive. That way we'll generate an input where you can pass in the `spaceId` in the queries and with the custom resolver you can validate it yourself if you allow that or not.

**Comment by mdegrees** [comment]
This sounds like an interesting track. Can you please point me to an example where `groups` is escaped and the model fields are passed? I did't get the 'passing spaceId' part. Where do I pass it? Do you mean in the query? as follows
`DataStore.save(new Post({spaceId: 'xyz', title: 'random title', content: 'random content'}))`

**Comment by attilah** [comment]
@mdegrees check the docs [here](https://docs.amplify.aws/cli/graphql-transformer/auth#dynamic-group-authorization) for a sample and documentation.

**Comment by mdegrees** [comment]
@attilah thank you
