### ISSUE TITLE
Notifications not detaching the IAM Managed Policies upon delete

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#6866]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

4.45.1

### What operating system are you using?

MacOS

### Amplify Categories

notifications

### Amplify Commands

delete

### Describe the bug

When a notification resource was created with an enabled channel then upon `amplify delete`, the delete finished successfully, but upon checking in CFN console the Stack is still there because the Managed Roles were not detached before Pinpoint app deletion, and  this caused a role delete failure, hence the Stack stayed there as well.

### Expected behavior

Delete the CFN Stack in a clean way.

### Reproduction steps

1. amplify init
2. amplify add notification
3. amplify update notification -> enable a channel
4. amplify delete

### Log output

```
# Put your logs below this line

```

**Comment by kaustavghosh06** [comment]
PR with the fix for this is merged and will be part of our next release.
