### ISSUE TITLE
AWSTimestamp on input becomes Int on the condition

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/amplify-cli#6869]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.0

### Amplify CLI Version

4.45.0

### What operating system are you using?

MacOs

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

I have a model
```
type Player @aws_iam
@aws_cognito_user_pools {
	lastinteraction: AWSTimestamp
        ...
}
```
and the `codegen` commands generates
```
input ModelPlayerConditionInput {
	lastinteraction: ModelIntInput
        ...
}
```
where `ModelIntInput` is:
```
input ModelIntInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: [Int]
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
}
```
However `Int` is not enough for a timestamp, since from the [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) `Int` can hold at most 2^32, but the timestamp is something like 2^40

### Expected behavior

Sincerely i don't know, maybe a`Float` can be used, but it's obviously not the best choice since maybe a `Long` might be what we want

### Reproduction steps

Implement that model and then generate all the default mutations

**Comment by AlbertoSinigaglia** [comment]
UPDATE:  
I've found this issue https://github.com/aws/aws-appsync-community/issues/21 that explains how to use `Long` in the Schema, maybe this could be a fix?

**Comment by attilah** [comment]
@AlbertoSinigaglia I mark it as a bug to make sure someone looks into it from the team, perhaps we can get around it by NOT mapping the `AWSTimestamp` scalar to `Int`, perhaps we could generate its own `ModelAWSTimestampInput` type but we have to check what conditions would be supported or does this change breaks any Codegen packages, etc.

On the other hand 32 bit signed integer can take you up to `Tuesday, January 19, 2038 3:14:07` so I don't see any actual risks with the `Int` assumption.

**Comment by AlbertoSinigaglia** [comment]
@attilah yup sorry, I was used to think to timestamp as Java does (milliseconds), and so there was a problem using int, but `AWSTimestamp` manages seconds

**Comment by cjihrig** [comment]
Hi @AlbertoSinigaglia. We have discussed this internally, and would prefer not to make this change at this time. With the understanding that `AWSTimestamp` units are seconds and not milliseconds, are you unblocked?

**Comment by AlbertoSinigaglia** [comment]
> Hi @AlbertoSinigaglia. We have discussed this internally, and would prefer not to make this change at this time. With the understanding that `AWSTimestamp` units are seconds and not milliseconds, are you unblocked?

yes yes sure, I've just divided the millis by 1000 and casted  to Int, and job done, thank you
