### ISSUE TITLE
Custom resolvers are removed when the mock server is stopped

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-cli#6878]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.45.2

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

I've created a custom resolvers to overwrite a standard resolver and placed it in 

```
<rootDir>mplify/backend/api/rcv/resolvers
```

Then I started the local backend server with 

```
amplify mock
```

The server added its own resolver templates into this directory, and when I stopped it, all the templates were gone, including my custom template.

### Expected behavior

See the description

### Reproduction steps

1. Add a custom template to the resolvers dir
2. Start the mock server
3. Stop the mock server
4. Observe that all templates are gone.

### Log output

```
# Put your logs below this line

```

**Comment by siegerts** [comment]
Hi @volkanunsal , thanks for taking the time to submit. I was able to reproduce on my end following your steps above.

1. Add a custom override template to the resolvers dir
2. Start the mock server
3. Stop the mock server
4. templates are removed

Labeling as a bug.

https://user-images.githubusercontent.com/634958/111163690-b2a7b280-8573-11eb-8b79-086812ec89ef.mov

**Comment by gitaalekhyapaul** [comment]
The issue seems to generate from the `resolver-overrides.ts` file.
**I would like to work on this issue.**

**Comment by SwaySway** [comment]
@volkanunsal Could you provide info on the custom resolvers? Can you provide a sample which is reproducible?

 @siegerts was able to repro this with an empty file. However I tested this on version `4.45.2` and it did not delete non-empty files.

**Comment by volkanunsal** [comment]
I can definitely say the files weren't empty when I encountered the issue.

**Comment by volkanunsal** [comment]
Try this. Copy a default resolver and use the same file name and content to create a new one when the server is not running. Then start the server. And stop it again. All files are gone.

Is the server checking the md5 hash of the file to decide whether to remove it? Because that might explain it. I'd copied over the default file but may not have changed its contents yet.

**Comment by kaustavghosh06** [comment]
@volkanunsal Either empty or the same file as the default one. If the file is the same without a single change or customization, then it results in getting rid of it. As you mentioned above it does a string comparison and deletes based on it.
