### ISSUE TITLE
client_id, client_secret and authorize_scopes are all required idp details

### ISSUE THREAD

**Issue by pnewhook** [aws-amplify/amplify-cli#6880]
### Before opening, please confirm:

- [x] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.4

### Amplify CLI Version

4.45.2

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

publish

### Describe the bug

I received an error while publishing to my test environment. Publishing to production was successful. The issue appears to be related to OAuth setup which is the same in both environments. 

This error was in the console 
```
UPDATE_FAILED               authtracktitanwebe5df7ee5         AWS::CloudFormation::Stack Mon Mar 15 2021 08:59:07 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:972180027784
:stack/amplify-tracktitanweb-test-121019-authtracktitanwebe5df7ee5-1PNV7APLUO244/011d8c00-739f-11eb-93b8-124ddee56cf7 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The f
ollowing resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
```

The following error is from my cloudwatch logs. 
```
2021-03-15T11:58:36.589Z	22ca071d-07be-4594-acd2-e8c476b2627e	INFO	Response body:
 
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/03/15/[$LATEST]cdad37b3875e47a9af4a278c2e8e2537",
    "PhysicalResourceId": "2021/03/15/[$LATEST]cdad37b3875e47a9af4a278c2e8e2537",
    "StackId": "arn:aws:cloudformation:us-east-1:972180027784:stack/amplify-tracktitanweb-test-121019-authtracktitanwebe5df7ee5-1PNV7APLUO244/011d8c00-739f-11eb-93b8-124ddee56cf7",
    "RequestId": "b6a7302b-a060-47a7-a952-00890cfe5f6e",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "client_id, client_secret and authorize_scopes are all required idp details.",
            "code": "InvalidParameterException",
            "time": "2021-03-15T11:58:36.554Z",
            "requestId": "c01089f3-06ce-4dae-87cb-3ffdcd2a100f",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 82.31004771926726
        }
    }
}
```

### Expected behavior

Publish should work without issue

### Reproduction steps

1. Have project with social login successfully publishing
2. `amplify publish`

### Log output

```
# Put your logs below this line

```

**Comment by pnewhook** [comment]
After swapping between prod and test a few times, my publish eventually worked, it's not clear what actually changed.

**Comment by roman-burdakov** [comment]
I'm facing a similar issue for one of the environments during `amplify push`:

```
UPDATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Mon Apr 05 2021 15:13:53 GMT-0400 (Eastern Daylight Time) Requested update required the provider to create a new physical resource
UPDATE_FAILED      HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Mon Apr 05 2021 15:13:54 GMT-0400 (Eastern Daylight Time) Failed to update resource. See the details in CloudWatch Log Stream: 2021/04/05/[$LATEST]6ce5bfb6cc2143a58323a4061ebd41e2
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-dvcclient-qa-211341-authdvccliente6700c86-NRLBOIMJHQQ9 AWS::CloudFormation::Stack Mon Apr 05 2021 15:13:55 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               authdvccliente6700c86       AWS::CloudFormation::Stack Mon Apr 05 2021 15:14:03 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:<MASKED>:stack/amplify-dvcclient-qa-211341-authdvccliente6700c86-NRLBOIMJHQQ9/f79e5ae0-5078-11eb-8361-0a90e6def441 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
UPDATE_FAILED               functionsavesearch          AWS::CloudFormation::Stack Mon Apr 05 2021 15:14:03 GMT-0400 (Eastern Daylight Time) Resource update cancelled
```

with log message:
```
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/04/05/[$LATEST]6ce5bfb6cc2143a58323a4061ebd41e2",
    "PhysicalResourceId": "2021/04/05/[$LATEST]6ce5bfb6cc2143a58323a4061ebd41e2",
    "StackId": "arn:aws:cloudformation:us-east-1:<MASKED>:stack/amplify-dvcclient-qa-211341-authdvccliente6700c86-NRLBOIMJHQQ9/f79e5ae0-5078-11eb-8361-0a90e6def441",
    "RequestId": "0481612e-c6c7-4fa1-beed-96acb83bd961",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "client_id, client_secret and authorize_scopes are all required idp details.",
            "code": "InvalidParameterException",
            "time": "2021-04-05T19:13:52.767Z",
            "requestId": "960f29c8-790a-443a-a17c-a8b9652b771c",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 67.56379915504516
        }
    }
}
```

Amplify Version:
4.46.1

In the corresponding auth-related parameters.json I do have a proper configuration for `hostedUIProviderMeta` and `oAuthMetadata`. I compared it with the other two environments and they matched.
I spent a fair amount of time troubleshooting (i.e. comparing cf templates between envs) and searching for similar issues. 

Since there is no clear resolution to this problem, I would like to reopen it here if possible to get some help. Thanks.

**Comment by arturocanalda** [comment]
Facing the same issue here after upgrading the cli.

Amplify Version:
4.46.1

**Comment by arturocanalda** [comment]
@roman-burdakov 
Have you checked your `team-provider-info.json`?

In my case, `hostedUIProviderCreds` was missing `client_id, client_secret and authorize_scopes` for the dev environment (actually the one failing).

After adding those missing attributes to `hostedUIProviderCreds` for the `dev` environment, I run `amplify push` and it worked fine.

Just notice when pushing it will move all the secrets of the updated environment to `~/.aws/amplify/deployment-secrets.json`.

Hope this helps you.

**Comment by roman-burdakov** [comment]
@arturocanalda I have compared sections for dev and prod which work and qa. Nothing stood out there to me. In particular `auth` section looks the same for all three envs:

```
  "qa": {
    "awscloudformation": {..},
    "categories": {
      "auth": {
        "dvccliente6700c86": {}
      },
    ...
```
Also, I believe we should not have `hostedUIProviderCreds` in `team-provider-info.json`. I have them in `~/.aws/amplify/deployment-secrets.json` 

thanks for your response. I will keep looking into how those are handled. Strange that it only doesn't work for one environment while others are fine.
