### ISSUE TITLE
@connect - one to many - nextToken usage

### ISSUE THREAD

**Issue by codeinaire** [aws-amplify/amplify-cli#6886]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
API GraphQL

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.45

**What AWS Services are you utilizing?**
Lambda, AppSync, Cloudfront, DynamoDB.

**Provide additional details e.g. code snippets**

I set up a one-to-many relationship between a couple of model. It works fine. I'm able to query for the one model record and from that get the many model records. However, I set a limit of 10 for the many model records but it's not obvious to me how to use the `nextToken` value to retrieve the other many model records.

I've tried using the list query for the many model and the list query for the one model but I get the invalid start key error. How can I use the `nextToken` value to get the other many model records?

**Comment by renebrandel** [comment]
hi @codeinaire - I'm having trouble fully understanding the issue. Can you share more of your query itself? A sample schema & query would add sufficient context.

Here's just some additional info on pagination: https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js#paginating-queries

**Comment by codeinaire** [comment]
This is the relevant part of the schema.

```
type PageForms
  @model
  @auth(
    rules: [
      { allow: private, operations: [update, read] }
      { allow: private, provider: iam, operations: [create, read, update] }
    ]
  ) {
  id: ID!
  pageId: String
  mappingDatas: [MappingData]
    @connection(keyName: "byPageForms", fields: ["id"], limit: 10)
}

type MappingData
  @model
  @auth(
    rules: [
      { allow: private, operations: [update, read] }
      { allow: private, provider: iam, operations: [create, read, update] }
    ]
  )
  @key(
    fields: ["archived", "formCreatedTime"]
    name: "ByArchived"
    queryField: "listMappingDataByArchived"
  )
  @key(
    name: "ByFormIdAndArchive"
    fields: ["formId", "archived", "formCreatedTime"]
    queryField: "listFormsByPageIdAndArchive"
  )
  @key(name: "byPageForms", fields: ["pageFormsID", "formId"]) {
  id: ID!
  formName: String
  formId: String
  pageId: String
  mappingInfo: MappingInfo
  rawLeadFields: [RawLeadField]
  status: Status
  formCreatedTime: String
  deliveryStatus: Int
  errors: Int
  campaignName: String
  campaignId: String
  archived: ArchivedStatus
  pageFormsID: ID
  leads: [Lead] @connection(keyName: "byMappingData", fields: ["id"])
}
```

This is the relevant queries.
```
let mappingDatas: any
      const pageForms: any = await API.graphql(
        graphqlOperation(listPageFormss, {
          filter: {
            pageId: {
              eq: pageId
            }
          }
        })
      )
      const pageForm: any = await API.graphql(
        graphqlOperation(getPageForms, {
          id: pageForms.data.listPageFormss.items[0].id
        })
      )
```

This is the relevant result of pageForm
```
{
      ...
      pageId: 10
      mappingDatas: {
            items: Array(10) [ {…}, {…}, {…}, … ],
            nextToken: "<a token>"
      }
}
```

I want to be able to get more of the mappingDatas by using `nextToken`, but it's not clear how to do that. I understand how to use `nextToken` to get more records in a regular list query, but this `nextToken` is nested in a record from a get query, so how do I use it to get more of the mappingDatas records?

I hope that clears it up.
​​​​

**Comment by codeinaire** [comment]
BTW @renebrandel the _only_ reason I'm doing this is because of [this issue](https://github.com/aws-amplify/amplify-cli/issues/5820). But if I can't do pagination with the `nextToken` from in the nested record and I can't use a composite key, what options do I have left!? TBH it's kind of frustrating.

p.s. I posted the issue I linked using my work github account. I should've posted this issue using the same account but forgot I was logged in on my personal account.

**Comment by renebrandel** [comment]
Hi - can you share the `listPageFormss` GraphQL query here? If you can give us the query, it'll be easier to explain it. Basically nested nextToken can be passed into that query as an input.

**Comment by codeinaire** [comment]
Great! Here's the query:

```
export const listPageFormss = /* GraphQL */ `
  query ListPageFormss(
    $filter: ModelPageFormsFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listPageFormss(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        pageId
        createdAt
        updatedAt
        mappingDatas {
          nextToken
        }
      }
      nextToken
    }
  }
`;
```

And, just in case, here's how it's used:
```
const pageForms: any = await API.graphql(
        graphqlOperation(listPageFormss, {
          filter: {
            pageId: {
              eq: pageId
            }
          }
        })
      )
```

**Comment by yuth** [comment]
@codeinaire the `mappingDatas` field can take an argument called `nextToken` and when you pass that it would use that value to paginate the mapping data.  So the updated query would look somewhat like this
```js
export const listPageFormss = /* GraphQL */ `
  query ListPageFormss(
    $filter: ModelPageFormsFilterInput
    $limit: Int
    $nextToken: String
    $mappingDataNextToken: String
  ) {
    listPageFormss(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        pageId
        createdAt
        updatedAt
        mappingDatas (nextToken: $mappingDataNextToken){
          items {
            id
            formName
            formId
            pageId
            # Other fields that you're interested in
          }
          nextToken
        }
      }
      nextToken
    }
  }
```

When trying to get the next page of `mappingData` pass the  you will need to pass the `nextToken` from `mappingDatas` of each `listPageFormss` to `mappingDataNextToken`

**Comment by codeinaire** [comment]
@yuth it appears to be working. Thanks for your help!

BTW, is this anywhere in the docs? I couldn't find anything like this and not sure if it's not there or I just didn't look in the right places.
