### ISSUE TITLE
amplify remove env cannot delete deployment bucket

### ISSUE THREAD

**Issue by ericwolf08-wp** [aws-amplify/amplify-cli#6887]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

env

### Describe the bug

Changing the local-aws-info.json to remove an environment in a separate account (workaround) with amplify remove env results in delete the backend successfully but fails deleting the deployment bucket in the specified account "× remove env failed: The bucket you tried to delete is not empty". Also the team-provider-info.json still maintains the deleted environment.

### Expected behavior

The deployment bucket should be deleted when there is no other backend or frontend in the specified account. Also the environment should be deleted from the team-provider-info.json file.

### Reproduction steps

1. amplify env add
2. amplify push
3. amplify env checkout (e.g. dev)
4. amplify remove env (e.g. sandbox)

### Log output

```
# Put your logs below this line
? Are you sure you want to continue? This CANNOT be undone. (This will delete 'testenv' environment of the project from the cloud) Yes
- Deleting resources from the cloud. This may take a few minutes...
Deleting env:testenv
| Deleting resources from the cloud. This may take a few minutes...
Error in deleting env:testenv
The bucket you tried to delete is not empty
× remove env failed: The bucket you tried to delete is not empty
The bucket you tried to delete is not empty
BucketNotEmpty: The bucket you tried to delete is not empty
    at Request.extractError (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\services\s3.js:712:35)
    at Request.callListeners (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\Eric.Wolf\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18)

```

**Comment by siegerts** [comment]
Hi @ericwolf08-wp , thanks for taking the time to submit this.

If I understand correctly, you are trying to remove an environment that is associated with another AWS account/profile?

If thats the case, and you have both profiles/credential, can you: 

1. Use `amplify configure project` which will give you the option to select a different profile for the CLI
2. Swap to, and then from, the profile with permissions to `amplify env remove`, etc.?

Also, can you confirm that the problem still exists with the most recent version of the CLI?

---
Just to confirm - I ran through a typical flow (single profile) below and that behaves as expected.  

1. `amplify init`
2. `amplify push`
3. `amplify env add testenv`
4. `amplify status` -> testenv 
5. `amplify env checkout dev`
6. `amplify status` -> dev
7. `amplify env remove testenv`
8. 
```
✔ Successfully removed environment from the cloud
 Successfully removed environment from your project locally
```

**Comment by ericwolf08-wp** [comment]
Hey there,
i can confirm that reconfiguring the whole project to work in a separate account with `amplify configure project` works (yet more annoying than just changing the json to use a different profile) can remove the cloudformation stack.
But the problem remains, that the deployment bucket cannot be deleted. Also the team-provider-info.json does not delete the information about the deleted environment (perhaps because it was not successful).
I tried the same steps you proposed, yet without success resulting again in 
`× remove env failed: The bucket you tried to delete is not empty`
Is further information needed here?

**Comment by ericwolf08-wp** [comment]
Hello there,
i can confirm that reconfiguring the Amplify Project works, yet changing the local-aws-info.json to use a different account is far easier.
I updated to the newest version 4.45.2 but the problem remains. The Cloudformation Stack is deleted successfully but the deployment bucket remains, since its not empty:
`× remove env failed: The bucket you tried to delete is not empty`

Also, the application is still visible in the Amplify Management Console (yet empty) and the team-provider-info.json also still has the information about the test environment.
Is there any further information needed?

**Comment by siegerts** [comment]
Hi! Thanks for the follow up: 

Can you try editing `amplify/.config/local-aws-info.json` and temporarily change the value `profileName` of the current env to the one you need to use for deletion.

Then retry `amplify env remove ...`

**Comment by ericwolf08-wp** [comment]
I already tried that without success :(

**Comment by siegerts** [comment]
Was/is there any additional configuration done for this project, or are these the first things that were done when initializing the project?

**Comment by ericwolf08** [comment]
its a fully working application with frontend and backend (api, lambda, cognit, s3). The additional environments are for features and testing.

**Comment by siegerts** [comment]
Is there anything left in the account profile's S3 buckets (deployment or storage) that the test `env` is associated with?

**Comment by ericwolf08-wp** [comment]
the labels are correct. the storage bucket gets delete through cloudformation. the -deployment bucket still contains 
#current-cloud-backend.zip, amplify-meta.json and backend-config.json. amplify-meta.json for example still has the provider information for roles etc.

**Comment by ammarkarachi** [comment]
@ericwolf08 Can you check if there is versioning on the objects in the s3 bucket?

**Comment by ericwolf08-wp** [comment]
the versioning is disabled in the s3 bucket

**Comment by kaustavghosh06** [comment]
@ericwolf08-wp We were able to root-cause the issue. It might be due to a missing policy - `s3:DeleteObjectVersion` which was missing in our docs. Did you use Admin UI or a custom IAM role/user based on our docs to setup your project?

**Comment by ericwolf08-wp** [comment]
I am using the AdministratorAccess-Amplify AWS managed Policy in my Role for the Amplify CLI. And yes, `s3:DeleteObjectVersion` is actually missing. I will try this again.
