### ISSUE TITLE
Compatibility with Angular monorepo workspace

### ISSUE THREAD

**Issue by cbranca** [aws-amplify/amplify-cli#6888]
**Amplify CLI Version** 
4.32.0

**What AWS Services are you utilizing?**
AppSync

** Additional details **
I have an angular workspace with multiple applications (monorepo pattern). amplify init needs to be called where the angular.json file is located, and it is located in the root of the workspace. In this case I can set up only one application as an amplify app.

I would like to setup as an amplify project every application inside the workspace. But the angular workspace with multiple projects has only one angular.json located in the root. Calling amplify init in the folder of a specific project will fail when choosing angular as javascript framework because it can't find the angular.json in the application folder.

Is there a way to achieve that?

**Comment by kaustavghosh06** [comment]
This is the recommended flow for monrepo project structures - https://docs.amplify.aws/cli/usage/monorepo#step-2-set-up-the-amplify-backend 
Please let us know if this answers your query.
