### ISSUE TITLE
An error occurred during the push operation: Stack with id does not exist

### ISSUE THREAD

**Issue by seyaobey** [aws-amplify/amplify-cli#6889]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.8.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

Mac Big Sur

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I'm trying to add amplify to my flutter app. I have followed the official tutorial (https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter). After having initialised amplify in my app and ran `amplify configure`, I want to push my changes with `amplify push`. Then I get the above error:
```
An error occurred during the push operation: Stack with id amplify-xxx-dev-xxx does not exist
```
I've tried a number of solutions suggesting there is a mismatch of regions between my amplify project and my cloudformation project (or something like that). They are on the same region.
I'm ready to share any extra information needed to look at this issue

### Expected behavior

command `amplify push` should push changes to the remote project.

### Reproduction steps

1. add amplify in your flutter project with `amplify `
2. `amplify configure`
2. `amplify push`

**Comment by seyaobey** [comment]
@nikhname thanks for your answer. Yes the stack existed in the AWS console. At the end, I just restarted a new project from scratch. I have to note that this time, I first added a service (`amplify add auth`) and I have not called `amplify configure`.
I don't know if that plays a role. But this time, so far, every think is working.

**Comment by nikhname** [comment]
Ok. I am going to close this issue but please comment or re-open if it shows up again.
