### ISSUE TITLE
DataStore error after update - Cannot return null for non-nullable type: 'String' within parent 'xyz'

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-cli#6891]
I have a working DataStore and edited one of my models' schema to include a required String field. I then ran **codegen models** and on completion **push**.

Once the push completed I tried to run my app but keep getting  _Cannot return null for non-nullable type: 'String' within parent 'xyz'_  when a **DataStore.query** is called on the updated model. I believe that this is because the existing objects in the datastore do not have the new required field. So I deleted all the items in the database table using **AppSync console** by running a delete mutation on all the items except one, which I updated to include the required field and a value. It still did not work, throwing the same error.

Next, I updated the models schema to make the new field no longer required. I then ran codegen and then push. On complettion, the app now works and the datastore query returns the requestd item containing the new (but not required) field.

So what's happening? What do I need to do to be able to update the model to include a required field (note that there are existing items in the store) ?

Thanks, appreciate any help with this

By the way, after the first push, I ran amplify console and used the generated link to open the console. From within the console, I clicked on View in AppSync and get an error stating that the GraphQl API does not exist, by chance I noticed that the region was set to Sao Paulo! while my store is in Ireland!

**Comment by nikhname** [comment]
@kannieWeesNie which platform are you using? Could you also provide your schema before and after? A common reason for this is having a field that is optional in the before schema and not after. You could mitigate this by editing your DynamoDB tables manually in the console to ensure that no required fields have no values.

**Comment by kannieWeesNie** [comment]
thanks @nikhname I'm using windows 10. I know what is causing the problem. It is when I add a new **required** field to the schema. If a add the same field but make it **not required** then there is no problem.

What concerns me is, if later, after using DataStore in a published app and there are thousand of items in the database, I then add a new required field to the schema, the app will then stop working! Surely the only solution cannot be to then edit the DynamoDb tables? What if the app was Twitter with millions of items? 

Does this mean that one cannot add new required fields to the schema after publication of the app without breaking the app?

**Comment by kaustavghosh06** [comment]
Closing based on last response and no further communication on this. Please let us know if you're still stuck on this issue.
