### ISSUE TITLE
List query doesn't return all items in table

### ISSUE THREAD

**Issue by bishonbopanna** [aws-amplify/amplify-cli#6895]
**Which Category is your question related to?** : **Appsync query filtering**

**Amplify CLI Version** :  **4.31.1**

**What AWS Services are you utilizing?** **Appsync, DynamoDB**

Also posted here : https://forums.aws.amazon.com/thread.jspa?messageID=977778&#977778

**Question in brief : How to get all the items from a query (with partition token and sort key and filter) without the next token**

Here is the schema : 

```gql
type BusinessCode
@model 
@key(
  name: "byCountryByBusinessCode",
  fields: ["country", "BusinessCode"],
  queryField: "listBusinessCodesByCountryByBusinessCode"
)
@key(
  name: "byCountryByState",
  fields: ["country", "state"],
  queryField: "listBusinessCodesByCountryByState"
)

{
  id: ID! 

  BusinessCode : ID! 

  state: String!

  country: String! 
}
```

10 K records inserted. 

Now use listBusinessCodesByCountryByState to get records with value for partition key, in this case country and sort by state and filter by BusinessCode, notice that you get empty list with next token only.

Why - From reading : https://forums.aws.amazon.com/thread.jspa?messageID=977778&#977778

A DynamoDB filter expression is applied AFTER the query runs (and you get a page of results)

So If I have say 10K records and if my filter condition (not part of the partition key) did not give any result in the first page then i end up getting and empty list with the nextToken. What if the record I am trying to filter is the 9999th record, how many times will we need to keep requesting for the next page with nextTokens ? the number of requests to get to the record which could be the last record will be huge and inefficient.

I understand that the filter is applied AFTER the results are returned but how do we solve for the above use case? 

seems to me the logical way is to be able to apply the filter (for no partition key) BEFORE, which might be against the principal for using partition keys - Please advise on how to solve for this use case. 

Also to add, can we have more that one value for the partition key so that the filter conditions are made part of the partition keys ?

**Comment by siegerts** [comment]
Hi @bishonbopanna, thanks for raising this!  To get a bit more context, do you mind porting this to one of formatted templates listed here:

- [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) or [usage question](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=question&template=3.usage-question.md&title=)

This will help the team determine the best approach to take.

**Comment by bishonbopanna** [comment]
@siegerts - updated as per usage question. thanks.

**Comment by SwaySway** [comment]
@bishonbopanna It looks like you are looking at using a more search specific query. Would the `@searchable` directive fit your usecase here? 
https://docs.amplify.aws/cli/graphql-transformer/searchable

**Comment by bishonbopanna** [comment]
@SwaySway, @kaustavghosh06 - Yes it probably does (I ll try it and update). However question is what is the recommendation from Amplify/AWS - should tables/entites (which is almost all for reasonable size app) to have be made "Searchable" - isnt that expensive (literally - adding to your bill ?) 

Also relational databases seem to solve this problem "Searching BEFORE the data is returned" and there is this link - https://docs.amplify.aws/cli/graphql-transformer/relational which says only available from US-EAST-1 - is there any roadmap/feature request that the team is working to making it available in all regions and directly as an option from Amplify CLI ?

@dabit3  - any comments ?
