### ISSUE TITLE
Unable to specify s3 bucket with dot such as domain

### ISSUE THREAD

**Issue by komushi** [aws-amplify/amplify-cli#690]
**Is your feature request related to a problem? Please describe.**
Unable to specify domain type bucket name like 'example.com'

**Describe the solution you'd like**
Change the existing validation.

**Describe alternatives you've considered**
No work-round yet.

**Additional context**
S3 bucket allows dot so it will be nice to enable this feature

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks @komushi

**Comment by kaustavghosh06** [comment]
@komushi This issue is fixed.

**Comment by komushi** [comment]
@kaustavghosh06 

Thanks.

From which amplify-cli release I can use it?
