### ISSUE TITLE
Failed to pull the backend.

### ISSUE THREAD

**Issue by MachariaK** [aws-amplify/amplify-cli#6900]
I created an app using Admin UI then created a fresh Vue JS application. 

When I run `amplify pull --appId d2v01y74i7xjqk --envName staging` on the CLI, I am getting the following error:

Invalid feature flag configuration

These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:
  - graphqltransformer.skipoverridemutationinputtypes

This issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.

I have upgraded amplify to the latest 4.45.0 version.

**Comment by cjihrig** [comment]
@MachariaK did upgrading the CLI version fix the problem for you? If so, can this be closed out?

**Comment by MachariaK** [comment]
No. I am still experiencing the problem.

**Comment by cjihrig** [comment]
> I have upgraded amplify to the latest 4.45.0 version.

Can you please try with v4.45.2, which should include `skipOverrideMutationInput`.

**Comment by MachariaK** [comment]
> 
> 
> > I have upgraded amplify to the latest 4.45.0 version.
> 
> Can you please try with v4.45.2, which should include `skipOverrideMutationInput`.

I have upgraded but I am still getting the same error:

```
+ @aws-amplify/cli@4.45.2
updated 20 packages in 221.88s

D:\Developer\Vue_Applications\rba>amplify pull --appId d2v01y74i7xjqk --envName staging
Failed to pull the backend.
request to https://e7auv6no3g.execute-api.us-east-1.amazonaws.com/wave3Prod/AppState/?appId=d2v01y74i7xjqk failed, reason: getaddrinfo ENOTFOUND e7auv6no3g.execute-api.us-east-1.amazonaws.com
FetchError: request to https://e7auv6no3g.execute-api.us-east-1.amazonaws.com/wave3Prod/AppState/?appId=d2v01y74i7xjqk failed, reason: getaddrinfo ENOTFOUND e7auv6no3g.execute-api.us-east-1.amazonaws.com
    at ClientRequest.<anonymous> (C:\snapshot\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

D:\Developer\Vue_Applications\rba>amplify pull --appId d2v01y74i7xjqk --envName staging
Opening link: https://us-west-2.admin.amplifyapp.com/admin/d2v01y74i7xjqk/staging/verify/
√ Successfully received Amplify Admin tokens.
Amplify AppID found: d2v01y74i7xjqk. Amplify App name is: rba
Backend environment staging found in Amplify Console app: rba
Failed to pull the backend.
Invalid feature flag configuration

These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:
  - graphqltransformer.skipoverridemutationinputtypes

This issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.

Learn more about feature flags: https://docs.amplify.aws/cli/reference/feature-flags
```

**Comment by cjihrig** [comment]
I haven't been able to reproduce this on v4.45.2. This might be a silly question, but how did you update the CLI version and generate this part of your snippet?

```
+ @aws-amplify/cli@4.45.2
updated 20 packages in 221.88s
```

Did you perform this install globally?

**Comment by MachariaK** [comment]
Yes I did : npm i -g @aws-amplify/cli@4.45.2

**Comment by MachariaK** [comment]
This is what I ran on the CMD Prompt `npm i -g @aws-amplify/cli@4.45.2` but when I check the version it's still `4.45.0`.

**Comment by cjihrig** [comment]
It sounds like you have a local path issue. Can you verify where v4.45.0 is installed and where v4.45.2 was installed to. If you're using a Node version manager, that can also impact the installation location.

**Comment by MachariaK** [comment]
I have managed by simply running `amplify upgrade` and it's working fine now.
