### ISSUE TITLE
How to restore amplify environment when the stack was manually deleted from cloudformation

### ISSUE THREAD

**Issue by happystrawberry** [aws-amplify/amplify-cli#6903]
** Please describe which feature you have a question about? **
due to the amp push failures and the stacks were also partially removed from the cloudformation console, we can't restore the prod env, such as using amplify init, push, pull and consistently see the error::
Using default provider  awscloudformation
⠋ Initializing your environment: prodCould not initialize 'prod': The specified bucket does not exist

the attempts we did,
1. init env using existing prod, but failed with the above err
2. since the app is removed completely, we lost two envs and unable to clone it back
3. the app id has been hard coded in the app files for deployment, it is nearly impossible to be changed. each push has to be pushed under same appID in the amp.
4. we did try to create a new app for prod by using same name, but the entire creating process is hang without seeing any progress in amp console or amp cli.

It is quite urgent. please help.

** Provide additional details**

**Comment by kaustavghosh06** [comment]
@happystrawberry Unfortunately there's easy way to restore a deleted CloudFormation stack form the AWS console, but you can easily clone your infrastructure  by running `amplify env add` -> `amplify push`.
