### ISSUE TITLE
REST API with no restriction on API access gives error: "No Parameters: [authRoleName, unauthRoleName] must have values"

### ISSUE THREAD

**Issue by glynjackson** [aws-amplify/amplify-cli#6905]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.13.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Amplify **push** fails after adding a new REST API if using imported auth. Error: **Parameters: [authRoleName, unauthRoleName] must have values.**

### Expected behavior

Adding a REST API with **no auth** shouldn’t create the following values in the cloud creation script:

```
        "authRoleName": {
            "Type":  "String"
        },
        "unauthRoleName": {
            "Type":  "String"
        },
```

### Reproduction steps

> amplify add api

? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: PartnerAPI
? Provide a path (e.g., /book/{isbn}): /partner/list
? Choose a Lambda source Use a Lambda function already added in the current Amplify project
? Choose the Lambda function to invoke by this path Partner
? Restrict API access No
? Do you want to add another path? No

> amplify push

### Log output

```

Current Environment: sandbox

| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Api      | PartnerAPI            | Create    | awscloudformation |
| Auth     | creditconsole89e81d50 | No Change | awscloudformation |
| Api      | OpenBanking           | No Change | awscloudformation |
| Function | Partner               | No Change | awscloudformation |
? Are you sure you want to continue? Yes
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS functionPartner                      AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:29 GMT+0000 (Greenwich Mean Time)               
UPDATE_IN_PROGRESS apiOpenBanking                       AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:29 GMT+0000 (Greenwich Mean Time)               
UPDATE_IN_PROGRESS amplify-creditconsole-sandbox-120457 AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:24 GMT+0000 (Greenwich Mean Time) User Initiated
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-creditconsole-sandbox-120457-apiOpenBanking-16IWDKNG3ZOUE AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:29 GMT+0000 (Greenwich Mean Time) User Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE functionPartner AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:30 GMT+0000 (Greenwich Mean Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      apiPartnerAPI AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:32 GMT+0000 (Greenwich Mean Time) Parameters: [authRoleName, unauthRoleName] must have values
CREATE_IN_PROGRESS apiPartnerAPI AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:32 GMT+0000 (Greenwich Mean Time)                                                            
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-creditconsole-sandbox-120457-apiOpenBanking-16IWDKNG3ZOUE AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:33 GMT+0000 (Greenwich Mean Time) Initiated by parent stack
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-creditconsole-sandbox-120457 AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:44 GMT+0000 (Greenwich Mean Time) The following resource(s) failed to create: [apiPartnerAPI]. The following resource(s) failed to update: [apiOpenBanking]. 
UPDATE_FAILED               apiOpenBanking                       AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:43 GMT+0000 (Greenwich Mean Time) Resource update cancelled                                                                                                  
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    functionPartner AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:54 GMT+0000 (Greenwich Mean Time) 
UPDATE_IN_PROGRESS apiOpenBanking  AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:54 GMT+0000 (Greenwich Mean Time) 
UPDATE_IN_PROGRESS functionPartner AWS::CloudFormation::Stack Thu Mar 18 2021 15:34:54 GMT+0000 (Greenwich Mean Time) 
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-creditconsole-sandbox-120457-apiOpenBanking-16IWDKNG3ZOUE AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:05 GMT+0000 (Greenwich Mean Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-creditconsole-sandbox-120457 AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:18 GMT+0000 (Greenwich Mean Time) 
UPDATE_COMPLETE                              apiOpenBanking                       AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:17 GMT+0000 (Greenwich Mean Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE apiPartnerAPI AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:19 GMT+0000 (Greenwich Mean Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE functionPartner AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:20 GMT+0000 (Greenwich Mean Time) 
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE amplify-creditconsole-sandbox-120457 AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:30 GMT+0000 (Greenwich Mean Time) 
UPDATE_COMPLETE          apiOpenBanking                       AWS::CloudFormation::Stack Thu Mar 18 2021 15:35:30 GMT+0000 (Greenwich Mean Time) 
⠸ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠸ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete


```

Auth parameters
```

{
  "authSelections": "userPoolOnly",
  "resourceName": "creditconsole89e81d50",
  "serviceType": "imported",
  "region": "eu-west-1"
}
```

API parameters

```
{
    "authRoleName": {
        "Ref": "AuthRoleName"
    },
    "unauthRoleName": {
        "Ref": "UnauthRoleName"
    }
}
```

**Comment by jhockett** [comment]
@glynjackson I haven't been able to reproduce this. I'm able to push an api with or without adding auth, with the same parameters present. Did you edit the cloudformation template directly at any point?

**Comment by glynjackson** [comment]
No, not before this error. I did however remove the follow after as a workaround it and appear to work. 

cloudformation for api removed...

```
{
    "authRoleName": {
        "Ref": "AuthRoleName"
    },
    "unauthRoleName": {
        "Ref": "UnauthRoleName"
    }
```
}

**Comment by glynjackson** [comment]
Question, did amplify add authRoleName and unauthRoleName as above to the cloudformation for you when you select Restrict API access **No**? This results in the error "No Parameters: [authRoleName, unauthRoleName] must have values"

**Comment by jhockett** [comment]
> Question, did Amplify add authRoleName and unauthRoleName as above to the Cloudformation script for you when you selected: Restrict API access **No**?
> 
> This results in the error "No Parameters: [authRoleName, unauthRoleName] must have values" on push for me

Yes it did. My API's generated `parameters.json` is identical to the one you posted. 

@glynjackson do you see `AuthRoleName` and `UnauthRoleName` in your `amplify-meta.json`?

**Comment by kaustavghosh06** [comment]
@glynjackson I think the issue out here is with your auth resource. Did you by any change run `amplify update auth` and choose only Cloud API option in the. manual configuration? You'd be needing an identity pool as well to work with your REST API.

**Comment by glynjackson** [comment]
@jhockett I see AuthRoleName and UnauthRoleName in awscloudformation in amplify-meta.json. What is the significance of this? thank you in advance.

**Comment by glynjackson** [comment]
@kaustavghosh06 I have not run, `amplify update auth` as it's not supported using an imported auth.

**Comment by kaustavghosh06** [comment]
@glynjackson When you imported auth - did you choose to import identity pool? 
Even if you do not Restricted Access - we still need an identity-pool provisioned for configuring Guest Access.

**Comment by glynjackson** [comment]
@glynjackson Not that I remember. I'm using Amazon Cognito Identity for my AppSync API and an identity pool is not required. I do not have guest access enabled. All auth for AppSync API is Cognito pool. For my rest API I don't need guest access.

**Comment by kaustavghosh06** [comment]
@glynjackson Sorry for the confusion. AppSync API works directly with Cogntio user-pool which you've correctly imported. For REST API configured via the Amplify CLI - No-access = Guest access to all the resources for which it requires you to configure identity pool and the import that too.

**Comment by glynjackson** [comment]
@kaustavghosh06 Thank you for the fast reply. So have I missed a step? How does one go about configuring guess access when my auth is imported? (I cannot run update auth CLI command). 

I've removed '"Ref": "AuthRoleName" ' from the cloudformation to get this to work, what is the impact of me doing this?

I don't think this is made clear in the documentation or what you must do if using imported auth (a common usecase). 

The original error "No Parameters: [authRoleName, unauthRoleName] must have values"... are you saying...

1. To use "No auth" you MUST setup guess access regardless?
2. Guest access can not be configured after setup (imported auth)?

**Comment by glynjackson** [comment]
@jhockett @kaustavghosh06 

This looks like the same error message, (but CLI does not hang). https://github.com/aws-amplify/amplify-cli/issues/6251

I have tested on a fresh project a few times which still reproduces the same error, No Parameters: [authRoleName, unauthRoleName] must have values".

**How I tested:**

> amplify init (selecting vue)
> amplify **import** auth (selecting pool only)
> amplify add function (selecting python)
> amplify add api (selecting rest and no auth)
> amplify push

```
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED      apiTestMe AWS::CloudFormation::Stack Thu Mar 25 2021 09:22:52 GMT+0000 (Greenwich Mean Time) Parameters: [authRoleName, unauthRoleName] must have values
```

**Comment by glynjackson** [comment]
@kaustavghosh06 This is still a problem for me. I do have a workaround, but I would like to understand if this is a bug or something I have misconfigured. Any additional information would be greatly appreciated. Thank you.

**Comment by glynjackson** [comment]
Of track but worth noting... I have also found another bug in the python hello template used by Amplify in latest CLI.  Amplify generates ``` 'body': "Hello from your new Amplify Python lambda!" ``` which will fails to parse on AWS Gateway, maybe use ``` 'body': json.dumps("Hello from your new Amplify Python lambda!")```.

**Comment by glynjackson** [comment]
After some trial and error, I found the root of the OP problem. In 'team-provider-info.json' I was missing the following...

```
 "allowUnauthenticatedIdentities": false,
          "authRoleArn": "xxxx",
          "authRoleName": "xxx",
          "unauthRoleArn": "xxx",
          "unauthRoleName": "xxx"
```

The CLI never generated these for me and I never modify this file.
