### ISSUE TITLE
Lambda function for Telegram bot

### ISSUE THREAD

**Issue by gHashTag** [aws-amplify/amplify-cli#6910]
I am creating a bot for telegram from this [lesson](https://dev.to/nqcm/-building-a-telegram-bot-with-aws-api-gateway-and-aws-lambda-27fg).
After adding the Lambda service

```bash
amplify add function
```

I add the following code:

```javascript
const { Telegraf } = require('telegraf')
const telegrafAws = require('telegraf-aws')

const config = require('config')

const bot = new Telegraf(config.get('token'), {
  webhookReply: true
})

// Create webhook handler
const updateHandler = telegrafAws(bot, {
  timeout: 2000 // Optional parameter, after timeout, empty response will be sent to AWS and function execution will be stopped
})

// Optional - set webhook url on start
bot.telegram.setWebhook('https://nezgbk462d.execute-api.us-east-1.amazonaws.com/JSBot')

bot.start(ctx => ctx.reply('Welcome'))
bot.help(ctx => ctx.reply('Send me a sticker'))
bot.on('sticker', ctx => ctx.reply('👍'))
bot.hears('hi', ctx => ctx.reply('Hey there'))
bot.launch()

exports.handler = updateHandler
```

Locally everything works, but when I upload the code to the cloud

```bash
amplify push
```

The bot stops working.

Environment
<img width="716" alt="Снимок экрана 2021-03-16 в 18 43 04" src="https://user-images.githubusercontent.com/6774813/111319250-9b59e980-8687-11eb-9a66-a029f5cc665d.png">

The test shows this error.

<img width="1214" alt="Снимок экрана 2021-03-16 в 17 55 43" src="https://user-images.githubusercontent.com/6774813/111312242-eae8e700-8680-11eb-8fd0-df1fbb966874.png">

I tried to increase the memory to 1000MB, but it did not help.

What could be the problem?

**Comment by richardfan1126** [comment]
This is not related to Amplify or Lambda
This is related to Telegraf plugin and it isn’t even an issue

Telegraf stated that when calling launch(), it will run as a request listener and will run until termination.

This long running listener approach is not suitable in Lambda, and it will definitely end with timeout

**Comment by kaustavghosh06** [comment]
@gHashTag Looks like the task is taking more than 25 seconds and timing out. You can increase the timeout of the Lambda function by directly going into the `amplify/backend/function/<resource-name>/<cloudfromation.tempalte.json>` file and changing the default 15 seconds timeout to a max of 15 mins. You can find more about this resource configuration here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout
