### ISSUE TITLE
GraphQL called from NodeJS throws "Not Authorized to access <queryName> on type Query"

### ISSUE THREAD

**Issue by evanmcd** [aws-amplify/amplify-cli#6912]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.1

### Amplify CLI Version

4.45.2

### What operating system are you using?

Mac

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

When calling the graphql API from a Lambda (as per the example here: https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js), out of the box list queries work, but the same query called from the Lambda returns "Not Authorized to access <queryName> on type Query" whenever accessed by a user using User Pool auth.

### Expected behavior

The query should be permitted to run for users that can run the query directly from the graphql explorer, either when mocking or in the cloud via the AppSync Console

### Reproduction steps

1. Start from a new project created with `amplify init`
2. Add api, then configure auth to allow User Pools
3. Create a User Group called "Admin" and create a Cognito User (using Amplify Admin UI) and assign the user to that group.
4. Add a function that calls the listTodos query (see schema below)
5. Run `amplify mock`
6. Update Auth to sign in as the user created in step 3
7. Run the function backed query
8. Observe the error "Not Authorized to access <queryName> on type Query"

### GraphQL schema(s)

<details>

```graphql
type Todo @model 
  @auth(rules: [
    { allow: owner },
    { allow: public, provider: apiKey, operations: [read, create, update, delete] },
    { allow: groups, groups: ["Admin"], operations: [read, create, update, delete]}
  ])
  {
  id: ID!
  name: String!
  description: String
}

type Query {
  testing: [Todo] @function(name: "listToDosFunc-${env}")
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
2021-03-19T00:15:30.593Z|info : amplify mock mock  
2021-03-19T00:15:35.903Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["amplify-iam-test"])
2021-03-19T00:15:35.904Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/myusername/.aws/config"])
2021-03-19T00:15:35.904Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-03-19T00:15:35.904Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["amplify-iam-test"])
2021-03-19T00:15:35.904Z|info : amplify-provider-awscloudformation.system-config-manager.makeFileOwnerReadWrite(["/Users/myusername/.aws/credentials"])


```

</details>

Knowing there are a lot of steps to get to the point of mocking, and a lot of options that can be chosen along the way, I've captured (and sped up) a video of the process here: https://dsc.cloud/a4f6b1/Auth-issue-2x.mp4

Here is the function:

```javascript
/* Amplify Params - DO NOT EDIT
	API_MYAPP_GRAPHQLAPIENDPOINTOUTPUT
	API_MYAPP_GRAPHQLAPIIDOUTPUT
	AUTH_MYAPPCCA27F22_USERPOOLID
	ENV
	REGION
Amplify Params - DO NOT EDIT */

const axios = require('axios');
const gql = require('graphql-tag');
const graphql = require('graphql');
const { print } = graphql;
const listTodosQuery = gql`
    query listTodos {
        listTodos {
            items {
                name
                id
            }
        }
    }
`;

exports.handler = async (event) => {
    const url = process.env.API_MYAPP_GRAPHQLAPIENDPOINTOUTPUT;
    const key = process.env.API_MYAPP_GRAPHQLAPIKEYOUTPUT;
    try {
        const graphqlData = await axios({
            url: url,
            method: 'post',
            headers: {
                'x-api-key': key
            },
            data: {
                query: print(listTodosQuery)
            }
        });

        return graphqlData.data.data.listTodos.items;
        
    } catch(err) {
        console.error('error processing listTodosFunc lambda', err);
    }
};

```

**Comment by kaustavghosh06** [comment]
@evanmcd Looks like you're using an API Key from your lambda to access the API but you've configured your API with cognito user pool groups?

**Comment by evanmcd** [comment]
@kaustavghosh06 thanks for the reply. The end goal is to be able to query the API via user pool groups, but I am new to the AWS world and so not entirely clear how the different auth mechanisms are expected to play together. 

Is it required that we use IAM (per the example [here](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda)) to access user pool based auth from lambda? If not, is there an example in the docs somewhere that illustrates how to do that?

I guess my expectation was that the API key is playing some role in validating that the lambda has access to the graphql service at all, but that the auth token would be used to identify which user is making the request, and therefore what access is allowed for the objects being accessed by the graphql.

Thanks for your help with this.

**Comment by ammarkarachi** [comment]
@evanmcd Check out this document on how to use Cognito User Pools to authenticate using AWS Appsync SDK
https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js#cognito-user-pools
