### ISSUE TITLE
Dynamic Group Auth - For every Partner Company a Group? Max 10k are allowed. Good Idea?

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#6916]
https://docs.amplify.aws/cli/graphql-transformer/auth#dynamic-group-authorization

I have a dashboard where partners can log in. Here they can see users who have signed up through their link on the platform.

So that not only one user can see this, but several users of the partner, I wanted to use the groups @auth option.

So I would create a separate group in Cognito for each partner. Then, when the partner invites their employees, I would assign the accounts to the group.

Now I have seen that there is a maximum of 10k groups. It will be a long time before we get to that amount of partners, but is that the way to go?

**Comment by kaustavghosh06** [comment]
Yeah, there are two ways to go about it - either have a separate app with a separate userpool tied to each partner or have a single app with different cognito user-pool groups  for each partner as you're thinking but then be mindful of the 10k userpool groups limitation.
