### ISSUE TITLE
How to give serverless container access to non-amplify-managed resources

### ISSUE THREAD

**Issue by amirhajimirsadeghi** [aws-amplify/amplify-cli#6918]
**Which Category is your question related to?**
Serverless Containers

**Amplify CLI Version** 
4.45.2

**What AWS Services are you utilizing?**
- DynamoDB
- Cognito
- API Gateway
- Secrets Manager

**Provide additional details e.g. code snippets**
I have two issues
1. I want to give my container the ability to know which env it is in and when I try to add the env to the environments attribute of the task definition the cloudformation gets overwritten when I run amplify push
2. I want to give my container permission to access non-amplify managed resources but my cloudformation gets overwritten everytime I run amplify push

How can I modify my cloudformaiton without it being overwritten for this resource? Or is there another approach I need to be taking that I'm unaware of

**Comment by mattfysh** [comment]
As a workaround, can you create an amplify lambda function and invoke it from inside your container, to act as somewhat of a proxy between your container and other non-amplify resources?

**Comment by amirhajimirsadeghi** [comment]
@mattfysh any prospect of adding this capability. I want to move away from lambdas to containers to avoid cold start times for my website, and the workaround doesn't solve that problem for me.

**Comment by mattfysh** [comment]
@amirhajimirsadeghi I don't work on this project sorry, just an idea I had for a workaround.

To solve the cold start times, you could create the lambda function then edit the CF template file to set a "provisioned concurrency", if I've understood these docs correctly: https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html

**Comment by mattfysh** [comment]
Another cheap workaround is to create a storage (dynamodb) resource, call it TestEnv.

Then give your container permission, once running you can inspect `process.env.STORAGE_TESTENV_NAME` ... it will contain the environment name in it, e.g. `"TestEnv-dev"`

**Comment by renebrandel** [comment]
Just to follow-up on this thread. We've just published an RFC on this. Would love to get your feedback: https://github.com/aws-amplify/amplify-cli/issues/7792

**Comment by ykethan** [comment]
Hey, we can now add polices to a Lambda function using custom-polices.json file. Closing the issue. Please refer to https://github.com/aws-amplify/amplify-cli/issues/7792 for additional information.
