### ISSUE TITLE
TypeError: require(...).internalModuleStat is not a function

### ISSUE THREAD

**Issue by rmtuckerphx** [aws-amplify/amplify-cli#6924]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.13.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

I get an error executing: amplify version

### Expected behavior

The command executes and returns the version

### Reproduction steps

1. I installed amplify cli: 
npm install -g @aws-amplify/cli

2. When I try to run amplify cli to get the version:
amplify version

I get the error.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
C:\dev\amplify>amplify version
internal/modules/cjs/loader.js:59
const internalModuleStat = function (f) { return require('fs').internalModuleStat(f); };
                                                               ^

TypeError: require(...).internalModuleStat is not a function
    at internalModuleStat (internal/modules/cjs/loader.js:59:64)
    at stat (internal/modules/cjs/loader.js:143:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:645:16)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:951:27)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1276:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
    at internal/bootstrap/pkg.js:7:1


```

</details>

**Comment by rajrajhans** [comment]
Hi @rmtuckerphx, according to [this](https://forums.aws.amazon.com/thread.jspa?threadID=336048) and [this](https://github.com/vercel/pkg/issues/954#issuecomment-697928214) this looks like it's related to vscode terminal. Can you confirm if it works for you in a normal terminal (outside of vscode)?

**Comment by rmtuckerphx** [comment]
Now it works in normal Windows Command Line and also inside VSCode.
