### ISSUE TITLE
when to use `amplify pull` ?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6926]
I've read the docs, but didn't get what this is. Why not just `git pull` instead?
For example, if I edited the `schema.graphql` then run the `amplify push`, does that mean in another computer with the same repo, if I run the `amplify pull` the latest version of `schema.graphql` will replace my local old one..?

**Comment by rajrajhans** [comment]
Hey @yaquawa, the `amplify pull` command is similar to `git pull`. Using `amplify pull`, you can fetch any definition changes to your amplify  backend environment in the cloud. If there were any changes made to the backend by someone else, `amplify pull` will update any backend configuration files that might not be in git repo. It also facilitates other interesting usecases like [multi frontends](https://docs.amplify.aws/cli/teams/multi-frontend), wherein you can use the `amplify pull` command to share the same Amplify backend across multiple frontends, (example a React and Android app). I hope this answers your question.

**Comment by yaquawa** [comment]
@rajrajhans Thanks for the details, does that means `schema.graphql` will be replaced with the new one if it is stale?

**Comment by rajrajhans** [comment]
> 
> 
> @rajrajhans Thanks for the details, does that means `schema.graphql` will be replaced with the new one if it is stale?

As per my understanding, yes. If there are any new changes in the backend, `amplify pull` will update your local backend to match with the new changes pulled from the cloud.

**Comment by kaustavghosh06** [comment]
@rajrajhans Explained it really well. @yaquawa let us know if you have more questions around this. Closing this issue.

**Comment by yaquawa** [comment]
@rajrajhans Thanks! Will this including the manual changes as well?

**Comment by rajrajhans** [comment]
> 
> 
> @rajrajhans Thanks! Will this including the manual changes as well?

Hi, could you clarify what exactly you mean by "manual changes"?
