### ISSUE TITLE
Add additional info when updating user pool group order

### ISSUE THREAD

**Issue by ktmdan** [aws-amplify/amplify-cli#6928]
When setting the preference of the cognito user groups.  Display a message that the preference is in reverse order meaning the entries on the top take preference. Wasn't entirely obvious and caused a lot of wasted time.

**Comment by renebrandel** [comment]
Hi @ktmdan - thanks for raising this issue. This is currently working as expected as the "top most preference" is on the "top". This is inline with many common UX. The intent is to order by preference i.e. primary preference, secondary preference, and and so on.
