### ISSUE TITLE
Appsync API is unauthorized when creating new Python lambda function resolver

### ISSUE THREAD

**Issue by Raees678** [aws-amplify/amplify-cli#6933]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.11.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

Mac

### Amplify Categories

function, api

### Amplify Commands

add

### Describe the bug

Creating a Python lambda resolver and giving API access does not allow it to call the Appsync API with any queries or mutations that are explicitly marked as allowing `{ allow: private, provider: iam }` auth. Instead it gives me Unathorized every time. I am using the `requests-aws4auth` python package to make graphql queries to the Appsync API.

### Expected behavior

The lambda should be able to make queries and mutations.

### Reproduction steps

1. Created a Python lambda with `amplify add function`.
2. Gave it create, read, update and delete access to the Appsync API while creating it. Used the `requests-aws4auth` package to make another auery to the appsync endpoint.
3. Tied the lambda to a query/mutation.
4. Went to the Appsync console, and called the query/mutation with the lambda resolver attatched. The lambda does run but while performing the mutation it shows Unauthorized.

#### Temporary workaround I found
I was able to look into this and check the IAM permissions attatched to the policy given to the lambda role. I compared the policies generated in Amplify v4.41.1 to the latest version v4.45.2.

It seems like some permissions which used to be given to lambdas like:

    "Action": [
                    "appsync:Create*",
                    "appsync:StartSchemaCreation",
                    "appsync:Get*",
                    "appsync:List*",
                    "appsync:Update*",
                    "appsync:Delete*"
    ]

and in resources this was replaced:

    {
      "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/*"
        ]
      ]
    }

to this:

    "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/types/create/*"
        ]
      ]
    },
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/types/read/*"
        ]
      ]
    },
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/types/update/*"
        ]
      ]
    },
    {
      "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/types/delete/*"
        ]
      ]
    }

When I added that old statement back into the policy the lambda was allowed to make queries and mutations again.

**Comment by beingayush** [comment]
Facing the same issue! 
The above solution fixed it

**Comment by kaustavghosh06** [comment]
@Raees678 Did you give access to the Lambda to access the GraphQL API by going through the `amplify add/update function` flow and granting CRUD operation permissions for the API?

**Comment by Raees678** [comment]
@kaustavghosh06 Yes I did do this during the `amplify add function`.

**Comment by kaustavghosh06** [comment]
@Raees678 Did you select Create/Read/Update and Delete as options or just a subset? Selecting all would result in adding the "appsync:Graphql" policy to the list which will allow you to access all the queries from the Lambda function.

**Comment by Raees678** [comment]
I selected all 4 options when I added the api. It does add appsync:Graphql to the policy. However despite that being there, it still shows me unauthorized when I try to call a graphql api secured using private IAM auth. The only way for me to fix it was to change the cloudformation template manually and add back:

    {
      "Fn::Join": [
        "",
        [
          "arn:aws:appsync:",
          {
            "Ref": "AWS::Region"
          },
          ":",
          {
            "Ref": "AWS::AccountId"
          },
          ":apis/",
          {
            "Ref": "XXXXXXXGraphQLAPIIdOutput"
          },
          "/*"
        ]
      ]
    }

In the end I ended up downgrading to amplify version 4.44.2 which automatically adds these resources for the Graphql policy. And that seems to work when using requests-aws4auth to make calls.

**Comment by SwaySway** [comment]
@Raees678
We did have a bug related to this which was addressed in https://github.com/aws-amplify/amplify-cli/pull/6723.
This is merged and was released in v4.42.0.
If you have the following feature flag enabled the CLI will create the proper policies on a function update.

```json
"appsync": {
  "generateGraphQLPermissions": false
}
```
