### ISSUE TITLE
Does AppSync do batch-get, batch-update, and batch-write?

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#6934]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Storage.

**Amplify CLI Version** 

Latest.

**What AWS Services are you utilizing?**

AppSync.

**Provide additional details e.g. code snippets**

I'm quite confused with the number of request limits per second.

Does AppSync do Batch operations when I send multiple queries/mutations in one statement?

Example multiple list queries:

```graphql
query {
  q1: listUsers {
    items {
      id
    }
  },
  q2: listTags {
    items {
      id
    }
  }
}
```

Example multiple get queries

```graphql
query {
  q1: getUser(id: 1) {
    id
  },
  q2: getUser(id: 2) {
    id
  }
}
```

Example multiple mutations

```graphql
mutation {
  m1:createUser (
    input: {
      id: 1,
      fullname: "test 1"
    }
  ) {
    id
  }
  m2:createUser (
    input: {
      id: 1,
      fullname: "test 2"
    }
  ) {
    id
  }
  m3:createUser (
    input: {
      id: 1,
      fullname: "test 3"
    }
  ) {
    id
  }
}
```

How many multiple mutations/queries can I do in one request?

**Comment by kaustavghosh06** [comment]
@aprilmintacpineda This is a great question which you could directly ask to the AppSync Service team and community members out here for a more in-depth answer around implementation details of the service - https://github.com/aws/aws-appsync-community 
Would be great if you could open up an issue in that repo. Thank you.
