### ISSUE TITLE
Amplify created user role is not kept up to date with requirements

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#6937]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

4.45.0

### What operating system are you using?

Windows/Ubuntu (WLS2)

### Amplify Categories

auth, storage, function, api, analytics, hosting, notifications, interactions, predictions, xr

### Amplify Commands

push

### Describe the bug

We're using the amplify create IAM user, amplifyadmin, to manage permissions when pushing changes. On multiple occasions, we've had to change the permissions for this role by hand since Amplify doesn't actively keep it up to date. This should be managed and updated by Amplify CLI. https://docs.amplify.aws/cli/usage/iam lists some of the permissions needed but I've just updated the user pool groups for Cognito and I'm getting -`Full-access/amplifyadmin is not authorized to perform: cognito-idp:UpdateGroup` 

This causes our team trouble. We've got to keep updating the `amplifyadmin` role... 

It also appears that the permission above isn't even listed in the policy example linked to above.

### Expected behavior

Amplify CLI should update the Amplify CLI generated `amplifyadmin` role.

### Reproduction steps

1. Add an Auth instance.
2. Push and then add a new group. 
3. See the permission error when using the suggested IAM permissions.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@kylekirkby We are aware of this situation and we're trying our best to update the missing IAM roles and policies both in our docs and policy list generated by Amplify Admin. At the same time, we're planning on introducing a Managed Policy for this and is definitely on our radar currently.

**Comment by kaustavghosh06** [comment]
Doc PR - https://github.com/aws-amplify/docs/pull/3077/files
