### ISSUE TITLE
nextToken is not null when it reach the end of the pagination 

### ISSUE THREAD

**Issue by taoatmars** [aws-amplify/amplify-cli#6940]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

4.45.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When doing a GraphQL Query on `list`, if the limit matches with the number of records, nextToken will not return null, instead, it will return a token

### Expected behavior

nextToken should be null when there are no additional records.

### Reproduction steps
```
query abc {
  listToDos(limit: 10) {
    nextToken
    items {
      id
      todo
    }
  }
}
```
NOTE: we have exactly 10 records, and we still get non-null nextToken returned.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type ToDo @model {
  id: ID!
  todo: String
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

Example: If we have 6 records and the GraphQL list query limit is set to 3, the second page returns nextToken that is not null. 
```
query abc {
  listToDos(limit: 3) {
    nextToken
    items {
      id
      todo
    }
  }
}
```
result: 
```
query abc {
  listToDos(limit: 3, nextToken: "thisIsAToken") {
    nextToken
    items {
      id
      todo
    }
  }
}
```
nextToken is not null when it reaches the last page.

**Comment by akshbhu** [comment]
Hi @taoatmars 

I tried the same steps and saw that next token is not null , if you try query with non null token again , it will return a empty list of items with next token as ```null```.

Since it doesnt know if all the items have been queried , one more query is needed to check if all the items has been queried. 
You can see as an example set the next token as 11 for 10 items. this will return all 10 items with next token as null.

**Comment by kaustavghosh06** [comment]
Closing as the question seems to be answered by @akshbhu
