### ISSUE TITLE
Support cross-drive linking for amplify-dev on windows

### ISSUE THREAD

**Issue by PawanKolhe** [aws-amplify/amplify-cli#6950]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

15.12.0

### Amplify CLI Version

4.46.0

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When setting up the dev environment on Windows, during `setup-dev-win` script, specifically when it runs the `link-win` script, if your Yarn installation is in a separate drive than the amplify-cli project, it will create an incorrect link for the `amplify-dev` command.

In my case, my Yarn directory is `C:\Users\Pawan\AppData\Local\Yarn\bin\` and the amplify-cli project is at somewhere in the D drive: `D:\...\amplify-cli\packages\amplify-cli\bin\amplify`

This issue seems to be caused by [this issue](https://github.com/npm/cmd-shim/issues/21) in the `npm/cmd-shim` package which `amplify-cli/scripts/link-bin.js` is using for setting up the linking for amplify-dev command on Windows.

### Expected behavior

`amplify-dev` should correctly run.

### Reproduction steps

1. Place amplify-cli project in a different drive
2. Run `yarn run setup-dev-win` from the amplify-cli project root
3. Run `amplify-dev` in a sample project

**Screenshot**
![unknown](https://user-images.githubusercontent.com/8324407/112116730-94c7f680-8be0-11eb-9863-dd525eee8d47.png)

**Comment by kaustavghosh06** [comment]
@PawanKolhe Thanks for submitting a fix for this!
