### ISSUE TITLE
`@key` directive keep adding LSI instead of GSI

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#6952]
### Amplify CLI Version

4.45.2

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

How to tell Amplify to add a GSI instead of LSI ?

this got me an LSI, where I want it to be a GSI.
```
@key(name: "byStatus", fields: ["owner", "status", "createdAt"], queryField: "listReviewsByStatus")
```

### Expected behavior

Let user choose wether it'll add a GSI or LSI.

**Comment by SwaySway** [comment]
A LSI is created when the fields of the primary key are used in the secondary key. Though we did change this behavior and by default it now creates a GSI.

FeatureFlag here: https://docs.amplify.aws/cli/reference/feature-flags#secondaryKeyAsGSI

**Comment by yaquawa** [comment]
@SwaySway I'm using the latest version, still not works. Should I create the `cli.json` to make the "default" behavior happens?

**Comment by siegerts** [comment]
@yaquawa Thanks for following up.

Yes, you can create if you don't currently have a `cli.json` in your `/amplify` directory. You can follow these instructions to get more info - https://docs.amplify.aws/cli/reference/feature-flags#configuration.

If you don't currently have that file,  verify that adding other flags _will not alter your desired behavior_.

After creating a new project with `amplify init` for **Amplify CLI v4.46.1**, the default contents is: 

```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": false,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    }
  }
}

```

Hope that this helps!
