### ISSUE TITLE
multiple-authorization-rules not auto populating model field correctly 

### ISSUE THREAD

**Issue by liorix** [aws-amplify/amplify-cli#6953]
I followed the documentation from this article:
https://docs.amplify.aws/cli/graphql-transformer/auth#multiple-authorization-rules

I created the following schema:
```gql
type Draft @model
  @auth(rules: [
    # Defaults to use the "owner" field.
    { allow: owner },

    # Authorize the update mutation and both queries.
    { allow: owner, ownerField: "editors", operations: [update, read] }
  ]) {
  id: ID!
  title: String!
  content: String
  owner: String
  editors: [String]
}
```

Then I went to the graphql explorer on my local machine (using amplify mock) and run:
```gql
mutation CreateDraft {
  createDraft(input: { title: "A new draft" }) {
    id
    title
    owner
    editors
  }
}

```

The expected result was according to the documentation:

```json
{
    "data": {
        "createDraft": {
            "id": "...",
            "title": "A new draft",
            "owner": "someuser@my-domain.com",
            "editors": ["someuser@my-domain.com"]
        }
    }
}

``` 

Actual Result: 
```json
{
  "data": {
    "createDraft": {
      "id": "d786c540-2c1c-4663-a9cb-79b081b0bdce",
      "title": "A new draft",
      "owner": "liorix",
      "editors": null
    }
  }
}
```

As you can see, the owner field is auto-populated with the correct username, but editors field is null. I'm not sure what I'm missing here.

I'm using Amplify version: 4.30.0

Thanks so much for your help.
Lior

**Comment by sammartinez** [comment]
This seems to be related to CLI. cc @renebrandel for visibility

**Comment by josefaidt** [comment]
Hey @liorix thanks for raising this! I've noticed the example provided by the docs does not match the corresponding output examples, and have made a PR to the docs to adjust. In this instance, it is redundant to also include the owner in the `editors` list as the owner has the ability to update and delete from the first auth rule.

**Comment by josefaidt** [comment]
Closing due to documentation update 🙂
