### ISSUE TITLE
amplify init without team-provider-info.json fails

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-cli#6954]
We have a CI/CD pipeline and it's working great. We can checkout the new branch, init the amplify project and push the backend changes together with our release. Up until now we had `team-provider-info.json` in git, but now we have to share the code with devs setting up their own envs which is under a different organization than production, hence we excluded it.

Our pipe looked something like this before: 

```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"us-east-2\"\
}"

AMPLIFY="{\
\"projectName\":\"$AWS_PROJECT_NAME\",\
\"envName\":\"$AWS_ENV_NAME\",\
\"defaultEditor\":\"code\"\
}"

...

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes

...

amplify push \
--codegen $CODEGEN \
--yes

```

Now we added app id here since it isn't part of the team config anymore:

```
AMPLIFY="{\
\"appId\":\"$AWS_APP_ID\",\
\"projectName\":\"$AWS_PROJECT_NAME\",\
\"envName\":\"$AWS_ENV_NAME\",\
\"defaultEditor\":\"code\"\
}"
```

But then we are getting the following error:

```
Amplify AppID found: XXXXXXX. Amplify App name is: XXXXXX
⠙ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
AlreadyExistsException: Stack [amplify-xxx-sandbox-94443] already exists
```

Then we tried to change init to pull:

```
amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--categories $CATEGORIES \
--yes
```

This works, however it overwrites our "local" backend changes with whatever is latest in the cloud. An ugly workaround is `git checkout .` but I would really not want to do that. 

Any ideas how we could make this work?

**Which Category is your question related to?**
Headless CI/CD, working with multiple environments. 

**Amplify CLI Version** 
4.46.0

**What AWS Services are you utilizing?**
cognito, graphql, datastore, restapi

**Provide additional details e.g. code snippets**

**Comment by kaustavghosh06** [comment]
@rraczae Trying to understand your use-case better. With this script do you want to initialize an existing environment or are you trying to create a new environment each time?

**Comment by rraczae** [comment]
hey @kaustavghosh06 Initialize an existing environment and push changes to the backend. Essentially we have four environments in one amplify app: dev, qa, staging, prod. First we make changes to dev, then when we push to qa it triggers the build, which runs amplify init with the qa environment, then pushes the backend changes. Only difference now is we gitignored `team-provider-info.json`, and added `appId` to init, but the environments still exist.

**Comment by rraczae** [comment]
@kaustavghosh06 any ideas how to get around this?

**Comment by kaustavghosh06** [comment]
@rraczae You'd need to store the team-provider-info.json for initializing an existing environment at this point. One way could be to maybe store it in S3/GitHub and fetch it dynamically and insert it as a part of your CI/CD process?

**Comment by rraczae** [comment]
@kaustavghosh06 thank you that makes sense. Actually what might be even better is to put it in an environment variable base64 encoded and just inject it post-clone. I did something similar with firebase before.
