### ISSUE TITLE
Failed to create models in the cloud: Modelgen job creation failed

### ISSUE THREAD

**Issue by emmafass** [aws-amplify/amplify-cli#6959]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.16.1

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

push

### Describe the bug

I made two small changes (one to one model and one to another model). I ran `npm run amplify-modelgen`. When I run `amplify push` everything looks like it works except that I see the output:

```
⠙ Updating resources in the cloud. This may take a few minutes...Successfully generated models. Generated models can be found in /Users/emmafass/ringside-pro/src
✔ Code generated successfully and saved in file src/API.ts
Failed to create models in the cloud: Modelgen job creation failed
✔ All resources are updated in the cloud
```

I first saw this error after I tried an `amplify push` and it asked me if I want to upgrade my node version in some of the template files of the functions I created. It suggested doing this in a dev environment as it may cause some issues. I went forward with it in dev and then saw the `Failed to create models in the cloud: Modelgen job creation failed` error. 

To confirm that the models were not correctly updated in the cloud, I want to AppSync and checked my schema. The changed models were still in their old forms.

I tried making a minor change to my schema. Then I ran `amplify push` again. Same output with the same error.

### Expected behavior

Expect the changes I made to be pushed to the cloud.

### Reproduction steps

1. Make a change to a model in schema.graphql
2. Run `npm run amplify-modelgen`
3. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional details
App Id: d2wxezabb7wfg6
Env: dev

**Comment by kaustavghosh06** [comment]
@emmafass Which region are you in?

**Comment by emmafass** [comment]
us-east-1

**Comment by kaustavghosh06** [comment]
@emmafass Do you have your schema split up into multiple different files or is it present in `amplify/backend/api/<resource-name>/schema.gql` file ?

**Comment by emmafass** [comment]
@kaustavghosh06 it's split into multiple files.

The structure is like `amplify/backend/api/my_api_name/schema/` then all of my schema files.

**Comment by kaustavghosh06** [comment]
Ah! Got it. The error message isn't a blocker for your deployment and it just means the Admin UI CMS wouldn't be able to use the latest models. We've diagnosed the root-cause and will be looking into this.

**Comment by emmafass** [comment]
Oh awesome!! Ok thank you so much for looking into it :) Glad it only refers to the Admin UI

**Comment by stelldogg** [comment]
I am experiencing this issue too.  My schema is in only one file [`amplify/backend/api/<resource-name>/schemal.gql`].

Region is `us-east-2`.  I'm not seeing any significant issues with functionality, but the AdminUI is failing to load as well.

Issue was not present on 3/26/2021 - but began on 3/29/2021 with no changes made from my end.

**Comment by jingo64** [comment]
I'm also seeing this issue - it'd help to have this issue re-opened until the problem is actually solved

**Comment by kaustavghosh06** [comment]
@stelldogg What's your appId?
@jingo64  What's your appId and region?

**Comment by stelldogg** [comment]
@kaustavghosh06 I've been able to resolve this issue by doing some force syncing between local and cloud backends.  However, it usually means some manual steps to ensure no code is lost.

**Comment by kaustavghosh06** [comment]
Got it. If you could provide your appId, we could see what went wrong and precent it from happening the next time round. Are your models getting created and synced to be used with the Admin UI CMS now?

**Comment by jingo64** [comment]
@kaustavghosh06 thanks for getting back to me! My app ID is d1pwgea1m2idtd in the us-east-1 region

**Comment by DregondRahl** [comment]
Having same issue--

APP ID: do360ckrbw0ee 
REGION: ap-southeast-2

**Comment by kaustavghosh06** [comment]
@jingo64 Are you using RDS/Aurora with your schema?

**Comment by DregondRahl** [comment]
> @DregondRahl Are you using RDS/Aurora with your schema?

Yes, RDS Aurora Serverless MySQL. Only two tables for test data.

**Comment by kaustavghosh06** [comment]
We currently don't support Admin UI CMS or Datastore with RDS hence the failure. This wouldn't affect any of your other app functionalities as mentioned here - https://github.com/aws-amplify/amplify-cli/issues/6959#issuecomment-806223042

**Comment by DregondRahl** [comment]
Okay, thanks for that, I was following this guide (https://docs.amplify.aws/cli/graphql-transformer/relational)  and thought I could work something out. But I guess its not an option

**Comment by itsmarkodonnell** [comment]
@kaustavghosh06 is there plans to support multiple .graphql files to work with the admin ui? I'm having the same issue, using only dynamo tables with datastore.

**Comment by mynameisguy** [comment]
Having the same issue - using only one schema file and dynamoDB

**Comment by itsmarkodonnell** [comment]
Just to follow up I moved my schema into one .graphl file and continued to get this error. The only thing I can think is that I have a few lambda resolvers set up, does anyone know if maybe they're not supported also (like RDS)? 

> @kaustavghosh06 is there plans to support multiple .graphql files to work with the admin ui? I'm having the same issue, using only dynamo tables with datastore.
