### ISSUE TITLE
Data Modeling  one to many relation failed to deploy

### ISSUE THREAD

**Issue by ahmabboud** [aws-amplify/amplify-cli#6960]
I am trying to create a one to many relations between my tables in AWS Amplify >App> Admin UI>Data Modeling
after creating the one to many relations between any two tables and click on save and deploy it will fail to deploy with a massage that says "failed to deploy".

See original issue :
[https://github.com/aws-amplify/amplify-cli/issues/6958#issuecomment-806047223](url)

**Comment by siegerts** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-adminui/issues/151
