### ISSUE TITLE
Safari can't authenticate admin app with CLI on amplify pull

### ISSUE THREAD

**Issue by letsbelopez** [aws-amplify/amplify-cli#6965]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

4.46.0

### What operating system are you using?

Amazon Linux 2

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

Can't authenticate amplify admin app locally with Safari.

When authenticating an admin app in Safari the request fails because Safari blocks the POST request to http://127.0.0.1:4242/amplifyadmin/ in the AdminLoginServer. Authentication happens after a `amplify pull.`

### Expected behavior

The POST request should return from this endpoint: http://127.0.0.1:4242/amplifyadmin/ like it does in Chrome.

### Reproduction steps

1. Set Safari as default browser 
2. Create amplify admin app
3. Run `amplify pull --appId {app_id} --envName staging ` in a new local app
4. Safari opens to authenticate.
5. Follow steps to authenticate
6. Look at console and see the error: `Fetch API cannot load http://127.0.0.1:4242/amplifyadmin/ due to access control checks.`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

Safari Version 14.0.3


```

</details>

<img width="664" alt="Screen Shot 2021-03-23 at 1 19 56 PM" src="https://user-images.githubusercontent.com/16825996/112393299-163e8800-8cb8-11eb-8bb3-fa9928adef82.png">

I think the Admin Login Server may need a proxy to enable https...?

**Comment by RyanMorash** [comment]
I am also experiencing the same issue with CLI 4.46.1 on Node.js 12.18.2 and Safari version 14.1 on macOS Big Sur 11.3

**Comment by cjihrig** [comment]
This warning appears to be related, and prevents Safari from even communicating with the CLI (it would be nice if this showed up as an error rather than a warning).

<img width="868" alt="Screen Shot 2021-03-25 at 6 17 16 PM" src="https://user-images.githubusercontent.com/2512748/112550886-7146ac80-8d96-11eb-847f-b150db8f1c3e.png">
