### ISSUE TITLE
Unable to add hosting after removing manual deployment hosting.

### ISSUE THREAD

**Issue by little-bamboo** [aws-amplify/amplify-cli#6972]
```
amplify add hosting // I incorrectly selected manual instead of continuous
amplify publish
amplify remove hosting
amplify add hosting // then I get below message
```

I'm also dealing with this same error.  After adding manual hosting through the CLI, I wanted to switch to a CI/CD workflow.  After removing hosting, I'm getting the same error:

```
on macbook-pro client on 🌱 master [🗑📝] via ⬢ v12.18.3 on 🅰 (us-west-2) took 46s 
➜  amplify add hosting
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.
```

_Originally posted by @little-bamboo in https://github.com/aws-amplify/amplify-cli/issues/4086#issuecomment-807479091_

**Comment by kaustavghosh06** [comment]
@little-bamboo Unfortunately due to Amplify Hosting service limitation, it won't be possible to switch between between Manual <> CI/CD types of hosting. The best way forward is to delete the Amplify Console App and create a new one.

**Comment by little-bamboo** [comment]
Then you should update the documentation!!
