### ISSUE TITLE
More dynamic tags based on environment

### ISSUE THREAD

**Issue by dsypniewski** [aws-amplify/amplify-cli#6974]
**Is your feature request related to a problem? Please describe.**
Wanting to add tags for billing purposes we find ourselves that the tags allow mostly static values except two placeholders.
Client wanting tags for example for prod/dev we'd like to map tags based on the environment to some other values.

**Describe the solution you'd like**
Allow more advanced expressions for tags like mapping based on environment.

If it's feasible it could use CloudFormation intrinsic functions to achieve the most flexibility but after some consideration it seems that for tags a simple map from environment would suffice for most use cases.
Since current implementation of tags only allows strings this could be achieved by using object as a map, and then handle this inside HydrateTags function.
```
[
  {
    "Key": "user:EnvType",
    "Value": {
      "prod": "production",
      "otherprod": "production",
      "dev": "development",
      "jdoe": "development",
    }
  }
]

```
With the simpler approach we could consider somehow handling a default value if the mapping doesn't match anything, it could be as "" (empty string) or something like "__default".

If this gets accepted I should be able to submit a pull request for this.

**Comment by renebrandel** [comment]
Hi @dsypniewski this is currently a supported feature. Just use the string {project-env} within your "Value" field. Amplify CLI will auto replace that string with the current Amplify env. See more here: https://docs.amplify.aws/cli/usage/tags#using-predefined-variables

**Comment by dsypniewski** [comment]
I know about this and this feature request is supposed to built upon that to be more flexible.
