### ISSUE TITLE
Coud not initialize dev

### ISSUE THREAD

**Issue by MachariaK** [aws-amplify/amplify-cli#6975]
**Which Category is your question related to?**
Amplify CLI

**Amplify CLI Version** 
4.46.1

**What AWS Services are you utilizing?**
AWS Amplify - JS

**Provide additional details e.g. code snippets**
I upgraded cli to version 4.46.1. I have created models using the Admin UI and when I pull, 
`amplify pull --appId d4kj5li5xk9a1 --envName dev`, I am getting the following error:
Could not initialize 'dev': ENOENT: no such file or directory, realpath 'D:\Developer\Vue_Applications\shortfall\amplify\.temp\#current-cloud-backend\a
pi\shortfall\build\states\initial-stack\states\initial-stack\states\initial-stack\states\initial-stack\states\initial-stack\states\initial-stack\states\initial-stack\states\initial-stack'

**Comment by akshbhu** [comment]
Hi @MachariaK 

Can you tell me the exact repro steps so that I can reproduce this error? 
Also, which OS platform are you using?

**Comment by MachariaK** [comment]
I can't replicate this but I am still facing the same problem. I have a lot of suggestions but none is working.

**Comment by MachariaK** [comment]
I changed a model in the backend and this must have caused the error. I have however migrated the project and it's working fine now.

**Comment by marenero1974** [comment]
@MachariaK how did you managed to copy data from one model of an environment to a model of another enverionment? did you do this?
