### ISSUE TITLE
Unable amplify push: "AccessDenied. User doesn't have permission to call es:DescribeElasticsearchDomain"

### ISSUE THREAD

**Issue by alekseyFilonenko** [aws-amplify/amplify-cli#6976]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.1

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

I added one `ID!` Field to an existing type. These are all changes, but when I push, I get the following error:
```
UPDATE_FAILED ElasticSearchStreamingLambdaFunction AWS::Lambda::Function Sat Mar 27 2021 11:49:22 GMT+0300 (Moscow Standard Time) AccessDenied. User doesn't have permission to call es:DescribeElasticsearchDomain
```
There is one type in the schema with @searchable, I think it has something to do with it. But the changes have nothing to do with this type.
The IAM account from which the push occurs has AdministratorAccess.

### Expected behavior

`amplify push` should succeed

### Reproduction steps

1. amplify push

**Comment by alekseyFilonenko** [comment]
@akshbhu Hello.

No, we never added `es:DescribeElasticsearchDomain` manually.
Before the error occurred, we also added: an @model with two @connections. And then `ID!` field to an another existing @model.

And more recently, amplify cli asked to update nodejs from 10 to 12 for handlers, and transferred some keys from team-provider-info to deployment-secrets.

**Comment by Raees678** [comment]
@alekseyFilonenko alekseyFilonenko I had a similar issue but on Amplify v4.44.2. The thing that fixed it for me was to go into the hidden folder: `amplify/.config/local-aws-info.json`, and find the environment name I wanted to push to in that JSON file. 

The old JSON object looked like this for me:

    "YOUR_ENV_NAME": {
        "configLevel": "amplifyAdmin"
    }

and I ended up manually changing it to:

    "YOUR_ENV_NAME": {
        "configLevel": "project",
        "useProfile": true,
        "profileName": "default"
    }

When I changed that and pushed, the push worked without any errors.

**Comment by alekseyFilonenko** [comment]
@Raees678 It really helped. Thanks a lot.
@akshbhu Unfortunately, I'm not sure if this would help with the problem I described initially. Since those changes were successfully pushed by another developer from their machine.

But today I had another push error.

```
UPDATE_FAILED UnauthRolePolicy03 AWS :: IAM :: ManagedPolicy Tue Mar 30 2021 12:18:41 GMT + 0300 (Moscow Standard Time) API: iam: CreatePolicyVersion User: arn: aws: sts :: .... Full-access / amplifyadmin is not authorized to perform: iam: CreatePolicyVersion on resource: policy arn: aws: iam ::  ....
```

And the advice of @Raees678 helped to fix this. Thanks again.

**Comment by akshbhu** [comment]
Hi @Raees678  @alekseyFilonenko 

Have you created the project with  AdminUI ? I wanted to know how ```local-aws-info.json``` chnaged to amplifyAdmin

**Comment by Raees678** [comment]
@akshbhu I think what happened for me was that a teammate actually created a project and I pulled it. But it made me sign in to the admin UI to authenticate me before letting me pull.
