### ISSUE TITLE
Graphql not honoring the auth rules for custom queries

### ISSUE THREAD

**Issue by bishonbopanna** [aws-amplify/amplify-cli#6977]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v15.12.0

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

publish

### Describe the bug

Graphql is not honoring the auth rules for custom queries like it does for generated queries where the fields for authorization scopes specified and when querying as IAM Unauthenticated user.

### Expected behavior

Custom queries should have same behavior as generated queries wrt autherization.

### Reproduction steps

Graphql not honoring the auth rules for custom queries

Here is the schema

```graphql
type todo
@model (subscriptions: { level: off })
@versioned
@auth(
  rules: [
    { allow: owner, ownerField: "owner", operations: [read, create, update, delete], provider: userPools}
  ])
@aws_cognito_user_pools
@key(
  name: "byItemByDescription",
  fields: ["item", "description"],
  queryField: "listByItemByDescription"
)
@key(
  name: "byOwnerByStatus",
  fields: ["owner", "status"],
  queryField: "listByOwnerByStatus"
)
{
  id: ID! @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])

  owner: String @aws_cognito_user_pools

  status : String @aws_cognito_user_pools

  item: String!  @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])

  description: String @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])
}
```

Auth rules are configured to allow owner field to carry out CRUDL, and owner and status fields are configured to accessed only by users from user pool. This api is configured for additional auth type - IAM.

id, item and status are configured to be able to be read by any IAM user - not authenticated too.

Now this generated query works - RUNNING AS IAM UNAUTHENTICATED USER :

Query # 1 -

```graphql
query MyQuery {
  listTodos {
    items {
      id
      item
      description
      owner
    }
  }
}
```
Output # 1:

```json
{
  "data": {
    "listTodos": {
      "items": [
        {
          "id": "b598ad29-e700-4ed7-bd08-a37dd8c99df1",
          "item": "Pick Biscuit",
          "description": "Test 2"
        },
        {
          "id": "06c9fe59-2c86-47a8-aae5-a5612adfa244",
          "item": "Wash Car",
          "description": "Test 3"
        },
        {
          "id": "111",
          "item": "Pick Milk",
          "description": "Test 1"
        }
      ]
    }
  }
}
```
Below query does not return value of owner field as it is meant only for user from user pool - so this too works as expected :

Query # 2 :
```graphql

query MyQuery {
  listTodos {
    items {
      id
      item
      owner
    }
  }
}

```
Output # 2 

```json
{
  "data": {
    "listTodos": {
      "items": [
        {
          "id": "b598ad29-e700-4ed7-bd08-a37dd8c99df1",
          "item": "Pick Biscuit",
          "owner": null
        },
        {
          "id": "06c9fe59-2c86-47a8-aae5-a5612adfa244",
          "item": "Wash Car",
          "owner": null
        },
        {
          "id": "111",
          "item": "Pick Milk",
          "owner": null
        }
      ]
    }
  },
  "errors": [
    {
      "path": [
        "listTodos",
        "items",
        0,
        "owner"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access owner on type todo"
    },
    {
      "path": [
        "listTodos",
        "items",
        1,
        "owner"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access owner on type todo"
    },
    {
      "path": [
        "listTodos",
        "items",
        2,
        "owner"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access owner on type todo"
    }
  ]
}

```

However below Custom query which has Item as partition key and Description as sort key does not work - this is the issue. Requirement is to have similar behavior as the generated query. Is there any additional config needed ? Could not find any info on this here : https://docs.amplify.aws/cli/graphql-transformer/key

Query # 3

```graphql
query MyQuery {
  listByItemByDescription(item: "Pick Milk") {
    nextToken
    items {
      item
      id
      description
    }
  }
}
```

Output # 3

```json
{
  "data": {
    "listByItemByDescription": null
  },
  "errors": [
    {
      "path": [
        "listByItemByDescription"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access listByItemByDescription on type Query"
    }
  ]
}  
```

### GraphQL schema(s)

<details>

```graphql
type todo
@model (subscriptions: { level: off })
@versioned
@auth(
  rules: [
    { allow: owner, ownerField: "owner", operations: [read, create, update, delete], provider: userPools}
  ])
@aws_cognito_user_pools
@key(
  name: "byItemByDescription",
  fields: ["item", "description"],
  queryField: "listByItemByDescription"
)
@key(
  name: "byOwnerByStatus",
  fields: ["owner", "status"],
  queryField: "listByOwnerByStatus"
)
{
  id: ID! @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])

  owner: String @aws_cognito_user_pools

  status : String @aws_cognito_user_pools

  item: String!  @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])

  description: String @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @bishonbopanna 

Can you tell me what authentication method you selected while adding api?

**Comment by bishonbopanna** [comment]
@akshbhu - Userpool is the authentication method with IAM being additional authentication.

**Comment by bishonbopanna** [comment]
@akshbhu / @edwardfoyle  - Any update ? + @kaustavghosh06

**Comment by kaustavghosh06** [comment]
@bishonbopanna Can you check the auth rules applied to the "listByItemByDescription" query in the the de-compiled schema located in `amplify/backend/api/build` directory? 
Also, which auth type are you using when running Query 3?

**Comment by kaustavghosh06** [comment]
@bishonbopanna I did a little bit of deep-diving and you can model your data in the following way to get the correct auth rules set for your custom query:

```graphql
type todo
@model (subscriptions: { level: off })
@versioned
@auth(
  rules: [
    { allow: owner, ownerField: "owner", operations: [read, create, update, delete], provider: userPools},
    { allow: public, operations: [read], provider: iam }
  ])
@aws_cognito_user_pools
@key(
  name: "byItemByDescription",
  fields: ["item", "description"],
  queryField: "listByItemByDescription"
)
@key(
  name: "byOwnerByStatus",
  fields: ["owner", "status"],
  queryField: "listByOwnerByStatus"
)
{
  id: ID! @aws_cognito_user_pools

  owner: String @aws_cognito_user_pools 

  status : String @aws_cognito_user_pools

  item: String!  @aws_cognito_user_pools 

  description: String @aws_cognito_user_pools 
}


```

**Comment by bishonbopanna** [comment]
Thanks @kaustavghosh06 - that worked! Question - shouldnt this behave the same like for generated APIs, why the need for explicit auth rule ?

**Comment by davidbiller** [comment]
Why you are mixing the 
@aws_cognito_user_pools
and the @auth directives? 

So If I understand it right, the @aws_cognito_user_pools ist the Same like auth private?!
