### ISSUE TITLE
Amplify push does noting ( no update in cloud )

### ISSUE THREAD

**Issue by BrianAndersen78** [aws-amplify/amplify-cli#698]
**Describe the bug**
Same bug as in #243 still exists. Amplify push does nothing... amplify api gql-compile not working eather.  

**To Reproduce**
Completely new install. <- everything works as expected.
Changing shema in backend/api/~apiname~/schema.graphql
Do "amplify push" 
Terminal tels me that it need to update Api, but after typing "y", terminal writes "All resources are updated in the cloud" - but nothing got updated.

**Expected behavior**
The shema in appsync to get updated

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 

**Additional context**

**Comment by UnleashedMind** [comment]
@BrianAndersen78 
could you tell us the version of the cli that you are using? 
run `amplify -v` to find out the version.

**Comment by BrianAndersen78** [comment]
OFC :)
Version 0.1.38

Thx for fast reply...

**Comment by UnleashedMind** [comment]
That bug has already been fixed, I've tested, and the latest version 0.1.41 does not have this issue. 
Please update the cli to the latest version and verify.

**Comment by BrianAndersen78** [comment]
Sorry, i still can't make it work... Here are some screenshots, just to verify im doing the right thing. ( it's my first time with amplify )
![skaermbillede fra 2019-01-11 23-02-44](https://user-images.githubusercontent.com/30560831/51062008-9277b400-15f5-11e9-8a59-e50ad09a4d4a.png)
![skaermbillede fra 2019-01-11 23-03-16](https://user-images.githubusercontent.com/30560831/51062015-99062b80-15f5-11e9-98d8-f448acc0ac7c.png)
![skaermbillede fra 2019-01-11 23-04-09](https://user-images.githubusercontent.com/30560831/51062024-9c99b280-15f5-11e9-8317-bdf505723ecd.png)

**Comment by kaustavghosh06** [comment]
Refer #565

**Comment by BrianAndersen78** [comment]
I recreated the project from start with the new version 0.1.41, and now it seems to work. Thanks for your help :)

**Comment by claytonbwell** [comment]
@UnleashedMind What's the command to update Amplify cli with npm? I'm stuck at 0.1.34 and I can't figure out how to update it to most recent version.

**Comment by wizawuza** [comment]
I'd try `npm install -g @aws-amplify/cli`
or, if you're running multienv `npm install -g @aws-amplify/cli@multienv`

that should update it to the latest.
