### ISSUE TITLE
How can I delete the current Cognito user from a Lamba function?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#6982]
**Description**
Hello,

My app uses AppSync/GraphQL. It has a mutation called "removeAccount".
This triggers a lambda function that does several things:
-Removes all data related with the current user in my aurora serverless db.
-Removes the Cognito user.
-Sends a last email to the user.

Reading Cognito docs, I see there are 2 functions to remove a user:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html

`adminDeleteUser`, that requires UserPoolId and Username.

`deleteUser`, that requires AccessToken.

So, I have some questions.
Because I want to delete the current user (not another one), I guess I should use deleteUser, but I don't know what that access token is in the lambda context.
Any help?

Regarding the other one, I think I can remove any user, but that is not required.
Moreover, another question: My app uses passwordless login, so I guess the username in my case is the phone number correct?
In fact, in my lambda function I see that event.identity.username contains the phone number. Should I pass that to adminDeleteUser and problem solved?

BTW, once I remove a user, do I have to remove something about the Identity Pools?

Any recommendation is welcome. Thanks a lot!

**Which Category is your question related to?**
Lambda and Cognito

**Amplify CLI Version** 
4.46.1

**What AWS Services are you utilizing?**
AppSync, Cognito, Lambda

**Provide additional details e.g. code snippets**
NA

**Comment by edwardfoyle** [comment]
Hi @Ricardo1980 check out this comment: https://github.com/aws-amplify/amplify-cli/issues/2569#issuecomment-541277467. I think that should get you headed in the right direction.

**Comment by Ricardo1980** [comment]
Thanks @edwardfoyle 
Seems to me that is useful.

However, I don't understand the step about getting and validating the access token to avoid a security issue.

Do I have to do that if my requests are authentificated?
Can I get the access token from the "event" object the lambda function receives (looks like it is here: event.request.headers.authorization)?
Shouldn't be enough if I extract the username from the "event" object? I mean, can a hacker send a different username there?

From iOS, do I have to get the access token with?:
```
        AWSMobileClient.sharedInstance().getTokens { tokens, error in
            print("\(tokens?.accessToken)")
        }
```

It seems similar to wha t I get in my lambda function in event.request.headers.authorization, but the value is not exactly the same.

Thanks a lot for suggestions!

**Comment by kaustavghosh06** [comment]
@Ricardo1980 Is your use-case for adding access for all authenticated users to delete themselves from the user pool using a API or is it an Admin action that you want to enable where only users from a certain group can delete users?
