### ISSUE TITLE
"amplify push" - Connection timed out after 120000ms

### ISSUE THREAD

**Issue by wellmmer** [aws-amplify/amplify-cli#6991]
Hi @kaustavghosh06 and @kimfucious 

I'm facing the same issue right now... I did a bash script to build my Node.js lambda, once they were coded using Typescript I needed to do it. But when I run **"amplify push -y"** I'm always getting the error below:

```
Connection timed out after 120000ms
An error occurred during the push operation: Connection timed out after 120000ms
```

![image](https://user-images.githubusercontent.com/37679777/113061012-c5cb9c80-9187-11eb-92f0-15610e939662.png)

But the weird thing is that if I just update one resource like my API Gateway, so then I don't get any error, and it works fine!

Amplify CLI Version
![Screen Shot 2021-03-30 at 18 44 51](https://user-images.githubusercontent.com/37679777/113061144-05928400-9188-11eb-8446-6cd72be9da04.png)

Any help guys ?

_Originally posted by @wellmmer in https://github.com/aws-amplify/amplify-cli/issues/5663#issuecomment-810598503_

**Comment by wellmmer** [comment]
Sometimes the error is this one below...

![image](https://user-images.githubusercontent.com/37679777/113061883-260f0e00-9189-11eb-99c2-e266945f1c43.png)

**Comment by kaustavghosh06** [comment]
@wellmmer This is an intermittent issue due to DNS/Network issue from mainly AWS S3 service but I agree we should catch these network issue in the CLI. We're tracking the work for this out here - #6930. Closing this as a dup.
