### ISSUE TITLE
Is "items" key avoidable when using @connection?

### ISSUE THREAD

**Issue by dutzi** [aws-amplify/amplify-cli#6994]
After setting up a 1 to many `@connection` like so:

```gql
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model
  @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  content: String!
}
```

 we get something like the following:

```gql
query getPost {
  getPost(id: "a-post-id") {
    id
    title
    comments {
      items {
        id
        content
      }
    }
  }
}
```

Is there a way to get rid of "items" when querying `getPost`? I mean something like:

```gql
query getPost {
  getPost(id: "a-post-id") {
    id
    title
    comments {
      id
      content
    }
  }
}

```

**Comment by edwardfoyle** [comment]
@dutzi No this is not possible. It has to do with how we generate the connection model to support pagination. You'll notice that within the "comments" schema there is also a "nextToken" field which is why the list of comments cannot be directly under "comments" in the schema
