### ISSUE TITLE
Setting parameters for custom cloudformation resources

### ISSUE THREAD

**Issue by CSTDev** [aws-amplify/amplify-cli#6995]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
CloudFormation

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.45.0

**What AWS Services are you utilizing?**
Cloudformation, cloudwatch, aws chatbot

**Provide additional details e.g. code snippets**

I've added a custom cloudformation to create some cloudwatch alerts and aws chatbot slack channel. I have an amplify dev environment in one AWS account and usually push to that during development, I therefore have it as my environment in the amplify CLI, and have values for it in team-provider-info.json, here I put the Id of the slack channel that I need to use in the cloudformation and it works well.

I then have another deployment in a different AWS account that runs off my `main` branch. I'm not sure how to go about adding the slack channel ID so that it would be used when amplify deploys to that environment? 
I don't have any values for it in my team-provider-info.json, would putting values in there and then pusing them to the `main` branch solve this?
 I've tried to check out that environment but after using `amplify configure` and adding access keys for an IAM user, I get `The security token included in the request is invalid.` I think this is because  the account doesn't have a root login it's only ever an assumed role to access it.

**Comment by kaustavghosh06** [comment]
@CSTDev Yes, you could use team-provider-info.json to set environment specific parameters.

**Comment by CSTDev** [comment]
OK, thanks. Will work on checking out that environment.
