### ISSUE TITLE
Why elastic search does not find any result?

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6997]
I have defined a model in my AWS Amplify like this:

```graphql
type Report 
@model 
@searchable
{
  id: ID!
  title: String!
  location: String!
} 
```

While I can create items and also list them, however, I cannot get the items using search query:

[![enter image description here][1]][1]

Look at above figure, `searchReports` returns nothing, while I have many reports with title `T` as it can be seen in the result of `listReports`.

  [1]: https://i.stack.imgur.com/vwsAO.png

**Comment by kaustavghosh06** [comment]
@mjza Can you use "matchPhrase" instead of "eq" in the query above and see if that returns any results?

**Comment by mjza** [comment]
First of all it works with `eq` if I enter a new entry in the table. It does not work for old entries. 
I deleted my data and reenter them then it was working. 
However, later when I had multiple items with same values, `eq` was not working anymore and I needed to use `matchPhrase`.
If you have no more comments regarding this recent problem you can close the ticket.

**Comment by edwardfoyle** [comment]
When you say old entries do you mean entries created before the @searchable directive was added to the schema? If so, this is expected behavior as adding @searchable does not backfill already existing data into the ES cluster.
