### ISSUE TITLE
Occasionally, amplify push fails due to TypeError: undefined is not interable.

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#7004]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

4.46.1

### What operating system are you using?

Windows/Ubuntu (WLS2)

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

push

### Describe the bug

Occasionally, when pushing updates using `amplify push -y`, the deployment will fail mid-way through with:

```
UPDATE_COMPLETE    functioncreateNewResource        AWS::CloudFormation::Stack Thu Apr 01 2021 15:19:47 GMT+0100 (British Summer Time)
⠼ Updating resources in the cloud. This may take a few minutes...TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getUniqueStacksEvents (/home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:494:24)
    at /home/god/.nvm/versions/node/v14.10.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:134:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-01T14:19:58.519Z - error: uncaughtException: Inaccessible host: `cloudformation.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region. date=Thu Apr 01 2021 15:19:58 GMT+0100 (British Summer Time), 

```

### Expected behavior

I'm suspecting this could be something to do with my internet connection dropping out for a split second...? I do live in a rural area (🤞 Starlink can help me eventually). 

Is there a way that this exception can be caught and dealt with in such a way that the deployment will wait for the connection to be re-instated? I may be completely wrong and it could be some other issue at play here..

Thoughts all?

### Reproduction steps

1. `amplify push -y`
2. Kill internet connection whilst creating a resource

**Comment by ammarkarachi** [comment]
@kylekirkby I believe this error is from the call get-stack-updates and if the stack has errored out it doesn't return data and we still attempt to iterate over. I will mark this as a bug

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI
