### ISSUE TITLE
amplify api does not create the correct resolvers when using relation database

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/amplify-cli#7011]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### Amplify CLI Version

latest

### What operating system are you using?

windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When calling ampliy push after creating schema for RDS database following:
https://docs.amplify.aws/cli/graphql-transformer/relational

the push complains about "only one resolver can be specified per field"

### Expected behavior

should not complain

### Reproduction steps

1. follow https://docs.amplify.aws/cli/graphql-transformer/relational
2. call ampliy push
3. fails to push

### GraphQL schema(s)

mock:

type addresses @model @auth(rules: [{ allow: owner }]){
  id: ID!
  country_code: Int!
  state: String!
  province: String!
  city: String!
  street: String!
  zipcode: String!
}

### Log output

<details>

```
# Put your logs below this line


```

</details>

for address, it created two resolvers files.
One in address.json one in ***-rds.json

eg. one named CreateAddressResolver
one named addressCreateResolver

both pointing to field createAddresses

this then creates error when calling amplify push

it's expected for amplify to detect two resolvers are specified, and use the rds override

**Comment by GMerakis** [comment]
so amplify push creates a bunch of table specific resolvers that conflicts with rds ones.
is it possitble to suppress the resolver creation??

**Comment by edwardfoyle** [comment]
@GMerakis It sounds like you had a model in your schema that had the same name as a model imported from the RDS table. If you remove the @model annotation from the model it will not generate any resolvers, but you probably want to make sure there are no naming conflicts in the first place.

**Comment by GMerakis** [comment]
thank @edwardfoyle!

I got confused while following the amplify datastore codelab...
I thought you need to generate schema when importing RDS models...

The reason is that when running amplify codegen models
it fails to generate the models to start playing around.
(We are using flutter)

Per my understanding, when using the RDS models
(eg. amplify api add-graphql-datasource)
https://docs.amplify.aws/cli/graphql-transformer/relational

We need to create lambda functions to hook up the RDS and AppSync?

**Comment by kaustavghosh06** [comment]
@GMerakis  are you still stuck on this?
