### ISSUE TITLE
Switch case for tags based on environment

### ISSUE THREAD

**Issue by dsypniewski** [aws-amplify/amplify-cli#7019]
**Is your feature request related to a problem? Please describe.**
Currently tags implementation allows only two placeholders which are not flexible enough for our needs.

**Describe the solution you'd like**
Having a switch case like statement for tags, eg.
```
[
  {
    "Key": "user:EnvType",
    "Value": {
      "prod": "production",
      "prod-other": "production",
      "stage": "staging",
      "dev1": "development",
      "dev2": "development",
      "dev3": "development",
      "jdoe": "development"
    }
  }
]
```
The expected behaviour of this syntax in this example is that `user:EnvType` tag would get the following value based on the environment name:
* `prod` and `prod-other` = `production`
* `stage` = `staging`
* `dev1`, `dev2`, `dev3`, `jdoe` = `development`

If the mapping does not find a match there are a few ways to handle this:
* have a default value with a `_default` key or something similar (default key needs to avoid colliding with actual environment names)
* emit empty string
* emit environment name
* exit with an error and require a mapping for all the values

Also even if the option with the default value would be allowed one more fallback needs to be chosen from the rest of the possibilities.

**Describe alternatives you've considered**
Allowing full CloudFormation template usage of intrinsic functions but it seems tags are not directly passed to stack template so it would be harder to implement.

**Additional context**
Previously opened this issue https://github.com/aws-amplify/amplify-cli/issues/6974 but it seems I might not have explained properly that the current feature which I know of an actually use is not enough in this case. The previous issue was closed without allowing me the possibility to explain that the requested feature actually doesn't exist hence I'm opening a new one.

**Comment by ammarkarachi** [comment]
I am not sure if it's viable to achieve that much granularity with tags if there is community traction we would definitely consider. As a workaround you could swap out the tags.json file on a push for a given environment

**Comment by dsypniewski** [comment]
If there would be some way to hook before push that could live in the repository then it would be feasible.
Currently the only way I know of doing something like this would be using a amplify plugin but each developer has to install and update them manually on each machine instead off all of the project configuration being contained within the repository which is just not practical.

The proposed changes are quite simple to implement and I would be available to make a PR for that if it get's accepted.
