### ISSUE TITLE
The cli should do what it's asked not ask so many questions.

### ISSUE THREAD

**Issue by brian-young-** [aws-amplify/amplify-cli#702]
**Is your feature request related to a problem? Please describe.**

Amplify cli is difficult to script and work with because it asks to many questions. 

Case in point is the 'amplify init' command.  I use it frequently after changing git branches and it's annoying to keep specifying the same thing over and over. 

**Describe the solution you'd like**

As a cli the tool should take all required information as params then just complete task. 

Alternately a -y or -q command param would be swell.

When designing command line tools, I frequently use the git cli as the model.  It's correct.

**Describe alternatives you've considered**

This works but it's extra work...
```echo y | amplify function build```

**Comment by kaustavghosh06** [comment]
@brian-young- We introduced headless support for the CLI which could be used for scripting. Please take a look at our documentation for the same - https://aws-amplify.github.io/docs/cli/init#headless-usage-of-the-cli
