### ISSUE TITLE
Can not deploy. could not initialize env -- Access Denied--

### ISSUE THREAD

**Issue by carlosortizpacheco** [aws-amplify/amplify-cli#7020]
**Issue/question**
Hi, I can not deploy my app. 

**Error message**
```
2021-01-24T18:49:37.421Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-01-24T18:49:42.773Z [WARNING]: - Initializing your environment: dev
2021-01-24T18:49:42.839Z [INFO]: [31mCould not initialize 'dev': Access Denied[39m
2021-01-24T18:49:42.854Z [ERROR]: !!! Build failed
2021-01-24T18:49:42.855Z [ERROR]: !!! Non-Zero Exit Code detected
2021-01-24T18:49:42.855Z [INFO]: # Starting environment caching...
2021-01-24T18:49:42.855Z [INFO]: # Environment caching completed
```

**Additional information**
This is the first time I have this message. My amplify version is 4.41.2 and I´m working in a macbook pro M1.  I have already seen that I actually have dev enviroment with amplify status and also in team-provider-info.json. I have also execute in my terminal the amplify pull environment ....... command....

This is my team-provider-info.json file
```json
{
  "dev": {
    "awscloudformation": {
      "AuthRoleName": "amplifyXXXXX",
      "UnauthRoleArn": "arn:aws:iamXxXXXXX",
      "AuthRoleArn": "arn:aws:iamXXXXXx",
      "Region": "XXXXX",
      "DeploymentBucketName": "amplifyXXXXXX",
      "UnauthRoleName": "amplifyXXXXX",
      "StackName": "amplifyXXXXX",
      "StackId": "arn:aws:cloudformationXXXXXX",
      "AmplifyAppId": "XXXXXX"
    },
    "categories": {
      "auth": {
        "XXX": {XXXX}
      }
    }
  }
}
```

**Comment by davidlevy** [comment]
Hi

I have the same error
⠼ Initializing your environment: dev
Could not initialize 'dev': Access Denied

I didn't try to push on this project for months. Meanwhile I have pushed on other amplify projects on other AWS accounts/profiles.
I have tried to force the profile with init/configure commands ... but still same error
Is there a way to get more verbose logs ?

**Comment by vs-slavchev** [comment]
What fixed it for me: the role that Amplify was using did not have AdministratorAccess.

You can make a new Role in IAM with AdministratorAccess. Then you go to Amplify and your app. In App Settings > General you can see the Service role. You can click Edit and then for Service role choose the one you just created.
