### ISSUE TITLE
Public AWS_IAM Subscription Will Result 'Unauthorized' with @model(subscriptions: { level: public }) set

### ISSUE THREAD

**Issue by yutaoyan** [aws-amplify/amplify-cli#7033]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Schema:
```
type SubTest2
  @model(subscriptions: { level: public })
  @auth(
    rules: [
      {
        allow: public
        provider: iam
        operations: [read, create, update, delete]
      }
    ]
  ) {
  id: ID!
  name: String
}
```
When `(subscriptions: { level: public })` is set, subscription with AWS_IAM as authMode will failed with the following message:
```
Error: {
    "errors": [
        {
            "message": "Connection failed: {\"errors\":[{\"errorType\":\"Unauthorized\",\"message\":\"Not Authorized to access onUpdateInterviewSlot on type Subscription\"}]}"
        }
    ]
}
```

### Expected behavior

Allow subscription for authMode: 'AWS_IAM' when `@model(subscriptions: { level: public })` is set.

### Reproduction steps

Schema:
```
type SubTest
  @model(subscriptions: { level: public })
  @auth(
    rules: [
      {
        allow: public
        provider: iam
        operations: [read, create, update, delete]
      }
    ]
  ) {
  id: ID!
  name: String
}
```
Subscription GQL Query:
```
updateSubTestListener = API.graphql({
        query: onUpdateSubTest,
        authMode: 'AWS_IAM',
      }).subscribe({
        next: (eventData) => {
          console.log({ eventData });
        },
        error: (error) => console.error(error),
        close: () => console.log('Done updateEventListener'),
      });
```
OR:
In AppSync console (with auth provider set to IAM):
```
subscription abc {
  onUpdateSubTest {
    id
    name
    createdAt
    updatedAt
  }
}
```

### GraphQL schema(s)

<details>

```
type SubTest
  @model(subscriptions: { level: public })
  @auth(
    rules: [
      {
        allow: public
        provider: iam
        operations: [read, create, update, delete]
      }
    ]
  ) {
  id: ID!
  name: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

When `(subscriptions: { level: public })` is removed, public IAM subscription will works.

There are two ways we can make this non-issue, either we clear about this behavior in the documentation or we actually fix the problem, which is put the correct permission for unauthRole.
I tried to manually put the following into the policy under unauthRole, which doesn't help, there seems to be some magic happening behind the scene.
`"arn:aws:appsync:us-east-1:[Account-Id]:apis/[AppSync-Id]/types/Subscription/fields/onCreateSubTest"`

I tried the solution here: https://github.com/aws-amplify/amplify-cli/issues/2715#issuecomment-553550734
also doesn't help in my use case (Public Subscription)

Also, I found that there is no subscription resolver is generated for this table if no Cognito auth rules are present, this seems to be expected behavior, but please confirm this.

**Comment by SwaySway** [comment]
Hello @yutaoyan 
Using `(subscriptions: { level: public })` is used a middle ground of having no auth enabled on subscriptions though having them still being generated. If you are looking at adding public authorization access on your `@model`s by having public under the iam provider will give you public access.

```gql
type SubTest
  @model
  @auth( rules: [
  # will give public access to crud (including subscriptions) on SubTest
  { allow: public, provider: iam }
]) {
  id: ID!
  name: String
}
```

**Comment by yutaoyan** [comment]
Hey @SwaySway,

Thank you for your answer, the real issue that these two permissions cannot coexist, `(subscriptions: { level: public })` and `{ allow: public, provider: iam }` on subscription. If I declare both in the same table, Amplify will not implement either of these rules and the subscription with public IAM will result in not authorized. 

So I think the best is that we are clear about the behavior that you cannot have both rules at the same time in the documentation, or we just put a warning during the `amplify api gql-compile` and ban the user from doing so. which latter is the real fix but it takes more time and effort.
