### ISSUE TITLE
amplify push returns `Parameters: [authProviders] must have values` after running amplify update auth

### ISSUE THREAD

**Issue by octaneC8H18** [aws-amplify/amplify-cli#7036]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

12.18.4

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

1. I ran `amplify update auth` selected `Walkthrough all the auth configurations`.
2. Then i changed the value of `Specify the app's refresh token expiration period`. 
3. I Did not change anything else. And then I ran amplify push and it resulted `Parameters: [authProviders] must have values`

Specify the app's refresh token expiration period

### Expected behavior

It should update the refresh token expiration period

### Reproduction steps

1. Run `amplify update auth` selected `Walkthrough all the auth configurations`.
2.Then  change the value of `Specify the app's refresh token expiration period`. 
3. Dont change anything else
4. run `amplify push update`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@octaneC8H18 What features have you enabled on your auth? it will help us reproduce this problem on our end.

**Comment by octaneC8H18** [comment]
@ammarkarachi Thank you for your time :). I found the solution. I had add a custom attribute manually in the CF template.. And running CLI had deleted it from CF. After adding it again manually fixed the error. Anyways the error "Parameters: [authProviders] must have values" is misleading
