### ISSUE TITLE
--frontend flag not honored in headless amplify init command

### ISSUE THREAD

**Issue by kaustavghosh06** [aws-amplify/amplify-cli#7046]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

latest

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

`--frontend` flag in amplify init not honored when running in headless mode. Following script always defaults to javascript/none framework even though there's an explicit mention of the framework and frontend config i'd like to use. 
The usual flow using `amplify init` works fine and is just an issue with the headless flag.

```bash

#!/bin/bash
set -e
IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"projectName\":\"headlessProjectName\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes



```

### Expected behavior

Frontend configs in the headless script should be honored.

### Reproduction steps

Run the script mentioned above.

### GraphQL schema(s)

NA

### Log output

NA

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI
