### ISSUE TITLE
Mock S3 trigger functions fails to execute

### ISSUE THREAD

**Issue by sayjava** [aws-amplify/amplify-cli#7052]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

12+

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When using `amplify mock storage` if a trigger function is attached to S3 to be triggered on file upload and  a file is uploaded, the mock server crashes when it tries to invoke the trigger function. 

### Expected behavior

The attached function should be triggered locally when a file is uploaded to the storage 

### Reproduction steps

- Setup an amplify project
- Add storage with `amplify add storage` and create/attach a simple trigger function to S3
- Start the server with `amplify mock storage`
- Upload a file to the S3 mock storage 

The storage mock server will crash

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
mock, storage], rss=360427520, heapTotal=300437504, heapUsed=288633992, external=12350793, arrayBuffers=10327490, loadavg=[1.5, 1.85205078125, 1.94482421875], uptime=705328, trace=[column=11, file=internal/validators.js, function=validateString, line=120, method=null, native=false, column=7, file=path.js, function=Object.join, line=1039, method=join, native=false, column=29, file=/Users/user/.nvm/versions/node/v12.18.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/utils/lambda/load-lambda-config.ts, function=Object.loadLambdaConfig, line=27, method=loadLambdaConfig, native=false, column=5, file=internal/process/task_queues.js, function=processTicksAndRejections, line=97, method=null, native=false, column=20, file=/Users/user/.nvm/versions/node/v12.18.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/storage/storage.ts, function=null, line=112, method=null, native=false], stack=[TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object,     at validateString (internal/validators.js:120:11),     at Object.join (path.js:1039:7),     at Object.loadLambdaConfig
```

</details>

### Additional information

The bug is related to how the mock storage tries to load the lambda configuration.

L111 src/storage/storage.ts 
```javascript
const config = await loadLambdaConfig(triggerName, context.print);
```

L21  src/utils/lambda/load-lambda-config.ts 
but the function signature is 
```javascript
export const loadLambdaConfig = async (context: $TSContext, resourceName: string, overrideApiToLocal: boolean = false,
): Promise< ProcessedLambdaFunction>
``` 

See 
https://github.com/aws-amplify/amplify-cli/blob/ebdaa5981004b86e2f84b94d25fc84b25325ee18/packages/amplify-util-mock/src/storage/storage.ts#L111

See src/utils/lambda/load-lambda-config.ts 
https://github.com/aws-amplify/amplify-cli/blob/ebdaa5981004b86e2f84b94d25fc84b25325ee18/packages/amplify-util-mock/src/utils/lambda/load-lambda-config.ts#L21

**Comment by edwardfoyle** [comment]
This has been addressed in the latest version of the CLI
