### ISSUE TITLE
To remove .ts files while latest-build.zip is created on amplify push

### ISSUE THREAD

**Issue by ravishankar82** [aws-amplify/amplify-cli#7061]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Describe the solution you'd like**
Can you please add a provision to remove .ts files from the latest-build.zip before running "amplify push".

**Comment by jhockett** [comment]
@ravishankar82 how are you compiling your TypeScript code? Can you share your `tsconfig.json`?

We recommend keeping the TypeScript files in a separate folder in our [docs](https://docs.amplify.aws/cli/function/build-options) which will prevent them from being included in `latest-build.zip`.

We are tracking more extensive TypeScript support in the following issues:
https://github.com/aws-amplify/amplify-cli/issues/659
https://github.com/aws-amplify/amplify-cli/issues/6507

**Comment by ravishankar82** [comment]
Yes, we can do if we place our source in another dir and pointing to build dir to src.
but I was expecting something to happen by amplify push under the hood

**Comment by jhockett** [comment]
@ravishankar82 can you elaborate on why you'd like to see this change?

**Comment by ravishankar82** [comment]
Because its unconventional in development point of view. If Amplify team suggesting use another folder its ok but there should be some option while creating amplify project using CLI command. At the time of amplify init there should be an option to select TypeScript and if developer select that one then this should ask about ts-src and js-src dir.

As Amplify does most of configuration things(creating folder dir and others) automatically at the time of initialization, in the same line of configuration we can give an option.

**Comment by jhockett** [comment]
Thanks for elaborating on your use-case @ravishankar82. I'm going to close this issue in favor of the following issues #659
#6507.
