### ISSUE TITLE
Error performing amplify push

### ISSUE THREAD

**Issue by doobrie** [aws-amplify/amplify-cli#7073]
**Describe the bug**
I am doing my development within a DropBox synced folder.  Whenever I try to perform `amplify push`, I get an error:

```
An error occurred during the push operation: EBUSY: resource busy or locked, rmdir 
'C:\Users\David\Dropbox\Code\my-app\amplify\.temp\#current-cloud-backend'
```

**To Reproduce**
1. Create a react application within a synced DropBox folder.
2. Add amplify to it and add an api.
3. Attempt to push the project with `amplify push`.

**Expected behavior**
The project should be pushed to the AWS backend.

**Desktop (please complete the following information):**
 - OS: Windows 10 / Powershell

**Additional context**
If I disable DropBox syncing on the `amplify` folder within my project, everything works as expected.

**Comment by jhockett** [comment]
Hi @doobrie, developing in a synced folder, be it dropbox or other, is not something we support. Git is a much better option for syncing your project across devices and will not conflict with CLI operations.

**Comment by doobrie** [comment]
I agree, and use Git for saving my projects.

If you happen to create a project in a DropBox folder however, the Amplify CLI fails.  My question is whether there should be something in the docs telling users not to do this ?
