### ISSUE TITLE
GraphQL update fails for AWSJON attribute with enabled conflict resolution

### ISSUE THREAD

**Issue by LaurentEscalier** [aws-amplify/amplify-cli#7076]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.47.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When updating my model using the cli-generated update mutation over the GraphQL API, AppSync returns an error of type `InternalFailure`.

This happens with a model that is configured with `data source versioning` and `conflict detection and resolution (AUTOMERGE)`, when the client attempts to update an AWSJSON attribute on the model while also sending a `_version` of the model that is not the latest.

### Expected behavior

The `conflict detection and resolution` algorithm should be able to process and merge the data.

### Reproduction steps

1. Create GraphQL API with `amplify add api`
<img width="779" alt="Screen Shot 2021-04-13 at 10 56 15" src="https://user-images.githubusercontent.com/62994416/114525990-e1827880-9c46-11eb-8ecd-1b8945f85978.png">
2. Setup your GraphQL Schema

```typescript
type Todo @model {
  id: ID!
  data: AWSJSON!
}
```
3. Push the API with `amplify push`
4. Send the following GraphQL create mutation, for example using AppSync's query tool in the AWS console:

```graphql
mutation MyMutation {
  createTodo(input: {data: "{\"key\":[]}"}) {
    data
    id
    _version
  }
}
```

5. Note the id returned for the created `Todo`
6. Send the following GraphQL update mutation, for example using AppSync's query tool in the AWS console:

```graphql
mutation MyMutation {
  updateTodo(input: {data: "{\"key\":[]}", id: "<<YOUR_TODO_ID>>", _version: 1}) {
    id
    data
    _version
  }
}
```

7. Observe that the `Todo` was updated to `_version` 2
8. Send the previous GraphQL update mutation again, for example using AppSync's query tool in the AWS console:

```graphql
mutation MyMutation {
  updateTodo(input: {data: "{\"key\":[]}", id: "<<YOUR_TODO_ID>>", _version: 1}) {
    id
    data
    _version
  }
}
```

9. Observe that the API responds with an error:

```json
{
  "data": {
    "updateTodo": null
  },
  "errors": [
    {
      "path": [
        "updateTodo"
      ],
      "data": null,
      "errorType": "InternalFailure",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "An internal error occurred."
    }
  ]
}
```

### GraphQL schema(s)

<details>

```graphql
input CreateTodoInput {
	id: ID
	data: AWSJSON!
	_version: Int
}

input DeleteTodoInput {
	id: ID
	_version: Int
}

enum ModelAttributeTypes {
	binary
	binarySet
	bool
	list
	map
	number
	numberSet
	string
	stringSet
	_null
}

input ModelBooleanInput {
	ne: Boolean
	eq: Boolean
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
}

input ModelFloatInput {
	ne: Float
	eq: Float
	le: Float
	lt: Float
	ge: Float
	gt: Float
	between: [Float]
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
}

input ModelIDInput {
	ne: ID
	eq: ID
	le: ID
	lt: ID
	ge: ID
	gt: ID
	contains: ID
	notContains: ID
	between: [ID]
	beginsWith: ID
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
	size: ModelSizeInput
}

input ModelIntInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: [Int]
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
}

input ModelSizeInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: [Int]
}

enum ModelSortDirection {
	ASC
	DESC
}

input ModelStringInput {
	ne: String
	eq: String
	le: String
	lt: String
	ge: String
	gt: String
	contains: String
	notContains: String
	between: [String]
	beginsWith: String
	attributeExists: Boolean
	attributeType: ModelAttributeTypes
	size: ModelSizeInput
}

input ModelTodoConditionInput {
	data: ModelStringInput
	and: [ModelTodoConditionInput]
	or: [ModelTodoConditionInput]
	not: ModelTodoConditionInput
}

type ModelTodoConnection {
	items: [Todo]
	nextToken: String
	startedAt: AWSTimestamp
}

input ModelTodoFilterInput {
	id: ModelIDInput
	data: ModelStringInput
	and: [ModelTodoFilterInput]
	or: [ModelTodoFilterInput]
	not: ModelTodoFilterInput
}

type Mutation {
	createTodo(input: CreateTodoInput!, condition: ModelTodoConditionInput): Todo
	updateTodo(input: UpdateTodoInput!, condition: ModelTodoConditionInput): Todo
	deleteTodo(input: DeleteTodoInput!, condition: ModelTodoConditionInput): Todo
}

type Query {
	syncTodos(
		filter: ModelTodoFilterInput,
		limit: Int,
		nextToken: String,
		lastSync: AWSTimestamp
	): ModelTodoConnection
	getTodo(id: ID!): Todo
	listTodos(filter: ModelTodoFilterInput, limit: Int, nextToken: String): ModelTodoConnection
}

type Subscription {
	onCreateTodo: Todo
		@aws_subscribe(mutations: ["createTodo"])
	onUpdateTodo: Todo
		@aws_subscribe(mutations: ["updateTodo"])
	onDeleteTodo: Todo
		@aws_subscribe(mutations: ["deleteTodo"])
}

type Todo {
	id: ID!
	data: AWSJSON!
	_version: Int!
	_deleted: Boolean
	_lastChangedAt: AWSTimestamp!
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime!
}

input UpdateTodoInput {
	id: ID!
	data: AWSJSON
	_version: Int
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

While opening this issue I have highly simplified the original `data` object that I intend to use to demonstrate the problem. Doing so I was able to isolate the empty array as a possible cause. This might relate to https://github.com/aws-amplify/amplify-cli/issues/4708

**Comment by jhockett** [comment]
Hi @LaurentEscalier, thank you for the detailed issue and simplified reproduction steps! I'll raise this issue with the dependent service team.

**Comment by jhockett** [comment]
@LaurentEscalier can you share any `requestId`'s you have from when you ran into the `InternalFailure`?

**Comment by LaurentEscalier** [comment]
@jhockett Here's one: `e75d66ee-5b4b-4332-a08e-e6904f329a30`.

**Comment by jhockett** [comment]
@LaurentEscalier this issue has been fixed by the AppSync team. Thanks again for reporting it with such detailed reproducible steps! Closing this issue, please comment below if you run into this again.
