### ISSUE TITLE
Private GitHub repository to the amplify project

### ISSUE THREAD

**Issue by hugoebarboza** [aws-amplify/amplify-cli#7079]
Hello,

I would like to configure your private GitHub repository to the amplify project, how can I do this ?

Thanks in advance.
Hugo Barboza

>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by siegerts** [comment]
Hi @hugoebarboza, thanks for raising!

To get started, check out the documentation on linking up a Git repo.  During this process, a private repo can be selected.

https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html

Hope that this helps!
