### ISSUE TITLE
Generated schema is not corrected (scalars like AWSDateTime not defined )

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [aws-amplify/amplify-cli#7080]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 3.04 GB / 7.96 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @aws-amplify/ui-react: ^1.0.6 => 1.0.6
    @gqless/cli: ^2.0.14 => 2.0.14
    @types/react: ^17.0.3 => 17.0.3
    aws-amplify: ^3.3.26 => 3.3.26
    gqless: ^2.0.11 => 2.0.11
    graphql: ^15.5.0 => 15.5.0
    next: 10.1.3 => 10.1.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.2.3 => 4.2.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.46.1
    aws-cdk: 1.96.0
    ngrok: 3.4.0
    node-gyp: 7.1.2
    npm: 7.6.3
    pnpm: 5.18.8
    windows-build-tools: 5.2.2
    yarn: 1.22.10

```

</details>

### Describe the bug

Generated schema is not corrected (scalars like AWSDateTime not defined).

after `amplify mock api` a get new file in `amplify/backend/api/demo/build/schema.graphql`
but this file not corrected:

1) this file use directive "@aws_subscribe" but it not defined on this file
2) use AWSDateTime scalar but it not defined on this file

I am using a custom typescript generator that generates react hooks based on the schema.graphql file. And it gives errors, because the scheme is really not valid and not correct, since it uses scalars, but does not define them, since it uses directives, but does not define them.

### Expected behavior

Generated file `amplify/backend/api/demo/build/schema.graphql` should contain used directives and scalars at the top of the file:

```graphql
scalar AWSDateTime
directive @aws_subscribe(mutations: [String]) on FIELD_DEFINITION

...other code...
```

### Reproduction steps

1) amplify init
2) amplify add api
3) amplify mock
4) check generated file. you not see used scalars and directives `amplify/backend/api/demo/build/schema.graphql`

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1"
};

export default awsmobile;
```

![image](https://user-images.githubusercontent.com/69426460/114004536-6c3e2e80-9867-11eb-91e5-a42395010352.png)

![image](https://user-images.githubusercontent.com/69426460/114003713-a6f39700-9866-11eb-896a-545dad2620af.png)

![image](https://user-images.githubusercontent.com/69426460/114003725-ab1fb480-9866-11eb-9617-2cc3083b10be.png)

**Comment by damassi** [comment]
@MaxmaxmaximusAWS 

> Do you understand what I mean?) Scalars MUST be declared if used in the scheme. YOU WILL NOT FIND ANYONE IN THE UNIVERSE gql utility that would not give you an error about the analysis of such a scheme)

This conversation would be much friendlier if you chilled out on the all caps. It really comes across as overly aggressive. Thanks.

**Comment by MaxmaxmaximusAWS** [comment]
@damassi capital letters are not a cry, words have stressed vowels, but there may also be stressed words in a sentence, which are emphasized) I'm sorry if this was perceived as a scream

**Comment by cjihrig** [comment]
It seems like it is possible to include the custom scalars in the output schema. I'm not sure if there is a historical reason or use case for omitting them.

Unfortunately, it doesn't seem like including the directives (`aws_subscribe`, etc.) would work because AppSync does not support directive definitions in schemas.

**Comment by cjihrig** [comment]
I'm closing this as a can't / won't fix due to the AppSync limitations described above.
