### ISSUE TITLE
Being repeatedly asked for which Auth method I want to use for each push

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#7090]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

4.48

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I was logged in using AdminUI but I had a permissions issue. So I had to logout and insteead authenticate with Amplify using IAM keys. Now when every I When I do a push I get asked which Authentication method I want to use. This is a bit of a drag.

### Expected behavior

Just use the last setting from the last push?

### Reproduction steps

Authenticate with AdminUI 
`amplify logout` and select the nukeclear option of "log me out of everything"
`amplify init`
follow the walk through to use `AWS Access Keys`
`amplify push`
Get the menu asking which auth method you want to use, this appears everytime.

**Comment by jhockett** [comment]
Hi @PeteDuncanson, can you share your `<project-root>/amplify/.config/local-aws-info.json`?

**Comment by PeteDuncanson** [comment]
`{
  "localdev": {
    "configLevel": "amplifyAdmin"
  }
}`

Not much is it... :)

**Comment by PeteDuncanson** [comment]
@jhockett seems its showing me that menu for most commands (update, add, etc) not just push if that helps.

**Comment by PeteDuncanson** [comment]
Had a dig around with a team mate comparing configs and seems I'm missing a few lines. Added this in there instead:

{
  "localdev": {
    "configLevel": "project",
    "useProfile": false,
    "awsConfigFilePath": "C:\\Users\\pete\\.amplify\\awscloudformation\\6wH9YnAEwC"
  }
}

And now I no longer get asked for auth choices which is great. However...the question still remains...how did it get in that state in the first place? :)

**Comment by kaustavghosh06** [comment]
@PeteDuncanson We've fixed the issue with the latest version of the CLI - v4.49.0. Please let us know if you're still seeing this with the latest version of the CLI. 
Relevant fixes: 
https://github.com/aws-amplify/amplify-cli/pull/7094
https://github.com/aws-amplify/amplify-cli/pull/7092
