### ISSUE TITLE
4.48.0 - amplify api gql-compile now requires credentials

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-cli#7091]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.15

### Amplify CLI Version

4.48.0-

### What operating system are you using?

Ubuntu

### Amplify Categories

auth, storage, function, api

### Amplify Commands

Not applicable

### Describe the bug

Previous to 4.48, the `amplify api gql-compile` did not require credentials. Now it does. This eliminates using it easily from a CI/CD CodePipeline/CodeBuild step to produce CloudFormation and VTL template.

### Expected behavior

Don't require credentials for a command that doesn't require them.

### Reproduction steps

git clone https://some-repo.git

From a shell script:
```bash
# ------------------------------------------------------------------------------
#  Create files needed for CI/CD so that the amplify CLI thinks there is a
#  configured project. Don't overwrite them if they exist when run locally.
if [ ! -f amplify/team-provider-info.json ]
then
    echo "{}" > amplify/team-provider-info.json
fi

# Not sure if the envName below affects anything. Setting it to something weird
# so generated code can be searched for it.
if [ ! -f amplify/.config/local-env-info.json ]
then
    echo "{ \"projectPath\": \"$(pwd)\", \"envName\": \"maynotmatter\"}" > amplify/.config/local-env-info.json
fi

amplify api gql-compile
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
amplify api gql-compile --yes
? Select the authentication method you want to use: (Use arrow keys)
❯ AWS profile
  AWS access keys
```
</details>

**Comment by jhockett** [comment]
Hi @kjones, thanks for filing the issue! I was able to reproduce when credentials are not automatically resolved.

**Comment by jhockett** [comment]
@kjones can you share the contents of <project-root>/amplify/.config/local-aws-info.json?

**Comment by kjones** [comment]
In this CI/CD case there is none. I can create a fake one if that gets `gql-compile` to continue on.

**Comment by jhockett** [comment]
@kjones for now the easiest workaround would be to pin the previous version of the CLI `4.47.1` in CI/CD until we release a fix.
