### ISSUE TITLE
Error during push now has a link to logs in cloudwatch but it 404's

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#7099]
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.48

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

Yesterday I was getting an error during a push and the CLI now gives me a url to the log in cloudwatch which was a nice touch. However when I click the link it says there is no event that matches it in cloudwatch. Seems something isn't right with the url but I can't work out what.

Error I was having yesterday was this one #6430 which is what caused the error/log link to show up, I suspect any will do it thoguh.

### Expected behavior

Clicking the link takes me to the actual link log

### Reproduction steps

Create a condition where a push will fail...
Get an error, it should include a link/url to the log
Go to the url and see that cloudwatch can't find the log

**Comment by jhockett** [comment]
@PeteDuncanson, thanks for filing this issue. The cloudwatch link comes from cloudformation, not the CLI. Can you provide the broken link?
