### ISSUE TITLE
How can I set up a local environment? 

### ISSUE THREAD

**Issue by rodrigowpl** [aws-amplify/amplify-cli#7107]
>**Note**: If your question is regarding the AWS Amplify Console service, please log in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Run amplify functions and API locally

**Amplify CLI Version** 
4.48.0

**What AWS Services are you utilizing?**
Dynamo DB, RDS, Cloudwatch, Lambda functions, API Gateway

**Provide additional details e.g. code snippets**
I'm basically trying to run my applications locally. I have functions and an API. I'm struggling to figure how to set up my environment to run locally.

Here is my boilerplate:
![image](https://user-images.githubusercontent.com/18172307/114949223-eaca3b80-9e26-11eb-8933-206aaebbd485.png)

There you are seeing my APIs and my functions. I'm trying to explore https://docs.amplify.aws/cli/usage/mock. But what happens is when I run `amplify mock` my API is mocked but the functions keep calling from the cloud. How could I mock or run them locally properly?

**Comment by PatrykMilewski** [comment]
Just don't. Simply deploy backend to the AWS and then start your frontend locally and let it connect to it.

There are a lot of emulation/mocking/localstack like solutions, to emulate cloud locally, but what is the point, when you can simply deploy it to the cloud for free and test it with real services? Setting up local emulation environment cost money (time).

**Comment by rodrigowpl** [comment]
@PatrykMilewski What do you mean? 
"when you can simply deploy.."
"Setting up local emulation environment cost money (time)". 

Really man?
This is not the point. How do you do to debug? Do you make a new deployment for every new console.log to track some bug? 

This is not sustainable

**Comment by Karmavil** [comment]
@rodrigowpl 
* [ ] React ?
* [ ] Vue ?
* [ ] JS ?
* [ ] iOS ?
* [ ] Android ?
* [ ]  Flutter ?

**Comment by jhockett** [comment]
Hi @rodrigowpl, as mentioned by @Karmavil, REST APIs are not yet supported by mock:
https://docs.amplify.aws/cli/usage/mock#api-mocking-setup

You can mock functions by themselves: https://docs.amplify.aws/cli/usage/mock#function-mocking-setup

We are tracking REST API mocking in this issue: https://github.com/aws-amplify/amplify-cli/issues/3399
