### ISSUE TITLE
Template error: instance of Fn::GetAtt references undefined resource when attempting to push auth delete

### ISSUE THREAD

**Issue by SaiCharan21** [aws-amplify/amplify-cli#7109]
I have created a Cognito resource using `amplify add auth`, but am now attempting to remove it. I have run `amplify auth remove` to do so, but when trying to push the changes I get the above "template error".

**Error:** 
```
Template error: instance of Fn::GetAtt references undefined resource authtechycommerce9b204560
An error occurred during the push operation: Template error: an instance of Fn::GetAtt references undefined resource authtechycommerce9b204560
```

![image](https://user-images.githubusercontent.com/51977495/114957583-f158b300-9e26-11eb-9a40-9d643cd50b18.png)

**Comment by jhockett** [comment]
@SaiCharan21 it looks like one of your resources depended on the auth resource.

Can you see which resource(s) has a reference to `authtechycommerce9b204560` in it's respective cloudformation template?

**Comment by DeniferSantiago** [comment]
I have the same problem, is it necessary to remove the @auth directives from my schema if I want to remove auth?
I just want to change my userpool to change the required attributes

**Comment by SwaySway** [comment]
Should the OP have issues removing the resources please comment below to re-open.
