### ISSUE TITLE
amplify.yml not loaded

### ISSUE THREAD

**Issue by ctjlewis** [aws-amplify/amplify-cli#7110]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn global add

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.48.0

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

publish

### Describe the bug

The `amplify.yml` build settings are not loaded by the CLI.

### Expected behavior

The build settings should be loaded as described below:

https://docs.aws.amazon.com/ja_jp/amplify/latest/userguide/build-settings.html

Furthermore, "Build Settings" is nowhere on the App Settings page in the Amplify Console.

### Reproduction steps

1. Add an `amplify.yml` to your root directory.
2. Run `amplify publish` and see the `preBuild` and `build` stages are not loaded.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@ctjlewis Are you using CI/CD and managing your frontend deployments via Git with Amplify Console hosting? 
Where did you add the amplify.yml file?
What were the steps followed when running `amplify add hosting`?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further response.

**Comment by ctjlewis** [comment]
Thank you, sorry, just noticed I hadn't responded--this issue disappeared on its own.
