### ISSUE TITLE
[4.45<] generates wrong AppSync mutation resolvers

### ISSUE THREAD

**Issue by kopkunka55** [aws-amplify/amplify-cli#7123]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.14.0

### Amplify CLI Version

4.48.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen, push, Not applicable

### Describe the bug

Amplify CLI generates wrong mutation resolver for delete and update operation, when using a DynamoDB sort key like following

```graphql
type FollowRelationship
	@model(timestamps:{createdAt: "timestamp"})
	@auth(rules: [
		{allow: owner, ownerField:"followerId", provider: userPools, operations:[read, create]},
		{allow: private, provider: userPools, operations:[read]}
	])
	@key(fields: ["followeeId", "followerId"])
{
	followeeId: ID!
	followerId: ID!
	timestamp: AWSDateTime!
}
```

but when initializing with Amplify CLI > 4.45, the generated resolver will be like

![スクリーンショット 2021-04-18 20 08 53](https://user-images.githubusercontent.com/63289889/115143384-eea5ca00-a081-11eb-9010-8629fde918e9.png)

the above code should have two input values (followeeId and followerId), but the generated resolver has only `id`, which isn't even defined in schema.

### Expected behavior

the resolver should generate delete operation like

![スクリーンショット 2021-04-18 20 00 08](https://user-images.githubusercontent.com/63289889/115143174-b18d0800-a080-11eb-936e-74dc4c63d380.png)

this is generated with Amplify project initialized by v4.45

### Reproduction steps

1. `amplify init` (> v4.45)
2. `amplify add auth`
3. `amplify add api`
4. `amplify mock api` or `amplify push`

### GraphQL schema(s)

<details>

```graphql
type FollowRelationship
	@model(timestamps:{createdAt: "timestamp"})
	@auth(rules: [
		{allow: owner, ownerField:"followerId", provider: userPools, operations:[read, create]},
		{allow: private, provider: userPools, operations:[read]}
	])
	@key(fields: ["followeeId", "followerId"])
{
	followeeId: ID!
	followerId: ID!
	timestamp: AWSDateTime!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
Does this appear in the latest version for you as well? I was not able to repro this on v4.48.

Looking at the delete input object in the schema is as follows
```gql
input DeleteFollowRelationshipInput {
  followeeId: ID!
  followerId: ID!
}
```

**Comment by kopkunka55** [comment]
@SwaySway Yes, still have same problem with v4.49

**Comment by SwaySway** [comment]
I'm not able to repro with the provided schema. Is there anything else that might change the build? (ex. schema, resolvers, etc)
