### ISSUE TITLE
amplify init fails with type error log is not a function

### ISSUE THREAD

**Issue by najeeb2113** [aws-amplify/amplify-cli#7131]

**Comment by cjihrig** [comment]
Can you please provide the information requested in the issue template.

**Comment by kaustavghosh06** [comment]
@najeeb2113 Please open an issue with this format - https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title= for giving the team all the information required to repro.
