### ISSUE TITLE
Error when amplify push with custome category (AWS CodeBuild) 

### ISSUE THREAD

**Issue by descaloni-thinkwhy** [aws-amplify/amplify-cli#7132]
Following up on 
https://github.com/aws-amplify/amplify-cli/issues/5683
I am having this issue and no fixes appears to be documented

**Comment by SwaySway** [comment]
@descaloni-thinkwhy 

Can you provide information on the custom category that is failing for you? (as well as the amplify version you are on)
If possible can you also include steps on how to reproduce this oush error.

**Comment by descaloni-thinkwhy** [comment]
@SwaySway Failing on Codebuild>Trigger
V 4.45.0

**Comment by SwaySway** [comment]
@descaloni-thinkwhy 

Some questions here to better understand this

- Is this happening because of a custom category?
- What exactly is failing? Can you provide some logs or error messages?
- What version of the Amplify CLI are you using?

**Comment by descaloni-thinkwhy** [comment]
The issue is when my codebuild has a Trigger attached:        
FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/develop$

When I run amplify push:
Invalid CloudFormation template: /home/ec2-user/environment/amplify-nextjs-ssr/amplify/backend/codebuild/amplifycodebuild/template.json
✖ An error occurred when pushing the resources to the cloud

Cannot read property '0' of undefined

The push still happens and sets everything correctly but it starts with that error 
The moment I remove the trigger section the error is not present
amplifycli 4.45.0

The user tmizuma from https://github.com/aws-amplify/amplify-cli/issues/5683 with the same issue

**Comment by josefaidt** [comment]
Hey @descaloni-thinkwhy :wave: can you post your codebuild template? It appears to include yml in the json template file based on the snippet and stack trace. The CloudFormation Designer could be helpful and could be used to validate the template as well https://console.aws.amazon.com/cloudformation/designer/home?region=us-east-1

**Comment by descaloni-thinkwhy** [comment]
[codebuild-template.json.zip](https://github.com/aws-amplify/amplify-cli/files/6672599/codebuild-template.json.zip)
@josefaidt Attached is the formation. It is valid and checked. Amplify still deploys it with the trigger, but throws errors. 
If this is deployed without amplify, no error 
If the trigger on ln 98 is removed then no error is thrown.

**Comment by josefaidt** [comment]
Thank you for the response with the file I'm taking a look at it now

**Comment by josefaidt** [comment]
Hey @descaloni-thinkwhy upon further inspection it appears [cfn-lint](https://www.npmjs.com/package/cfn-lint) is the culprit here and is failing to validate due to `SourceVersion` as well as the `FilterGroups`. Marking this as a dependency issue bug, and I've requested that the official cfn-lint distribute their package via npm. https://github.com/aws-cloudformation/cfn-lint/issues/2053

**Comment by Straubulous** [comment]
@descaloni-thinkwhy - are you still blocked as of CLI 5.1.1 ? 
We've made cfn-lint a warning instead of an error, so it shouldn't prevent actual deployment now.

**Comment by descaloni-thinkwhy** [comment]
Resolved. Thank you!
