### ISSUE TITLE
Custom Resource Outputs unavailable to Function Mock

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#7137]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.14.0

### Amplify CLI Version

v4.49.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

codegen, Not applicable

### Describe the bug

When running `amplify mock function`, environment variables that pull attributes from Custom Resources are not correctly populated. In my case, I have a custom SQS and SNS resources, and their URLs/ARNs appear fine when pushed to the cloud, however when run locally the environment variable is `'[object Object]'`

### Expected behavior

The environment variables should be populated correctly with the Outputs of the custom resources. Other environment variables such as those from the API, Storage and Auth categories **are** successfully populated.

### Reproduction steps

1. Define a custom resource containing an SQS queue or SNS topic, or both. In your resource definition, have Output parameters such as:

```
"Outputs": {
    "QueueUrl": {
      "Value": {
        "Ref": "Queue"
      }
    },
```

2. Create a new function and follow the custom resources guide to allow the function access to custom resource outputs: https://docs.amplify.aws/cli/usage/customcf#n3-optional-reference-existing-parameters

3. Push to the cloud, to create your custom resources. Visit the lambda function to verify that it has an environment variable/s correctly populated by custom resource attributes.

4. Run `amplify mock function` on your new function, and `console.log(process.env)` where you will see the custom resource outputs show up as the string `'[object Object]`

**Comment by mattfysh** [comment]
Note, `typeof process.env.OUTPUT_VAR` is a string NOT an object. It looks like the mocking harness has baked in a stringified an object and stored in process.env _before_ running the function

**Comment by SwaySway** [comment]
Looks like at the moment mock does first level parsing on intrinsic functions, we could look into traversing these values to see if we can grab the actual value cfn parameter.

Snippet on where this happens
https://github.com/aws-amplify/amplify-cli/blob/c8069bd1a69dd7bf4d31dd94743c0e4c7c140d85/packages/amplify-util-mock/src/CFNParser/field-parser.ts#L36-L47
