### ISSUE TITLE
Amplify Function CloudFormation templates unusable by AWS cfn_tools

### ISSUE THREAD

**Issue by paolo573** [aws-amplify/amplify-cli#7138]
I am trying to add CloudWatch alarms to my Amplify Functions so that I get paged when certain events happen.

I was able to find the appropriate CloudFormation config, and applied it manually to the yaml (to test; this approach would get overwritten by the CLI, so is not a permanent solution) and the alarms and topics created successfully, so i began work to script this.

I am already using AWS cfn_tools to modify the Amplify Auth CF template, and cfn_tools is able to load and dump the Auth package CF template without any issues.

When I took the same approach with the Amplify Function CF templates (there is one for each Function) I ran into the complaint from cfn_tools.

Steps to reproduce:
1) `cfn_tools.load_yaml` the Function CF template
2) Try to dump that loaded yaml as below:
```python
dumper = cfn_flip.yaml_dumper.get_dumper(clean_up=True, long_form=False)
raw_markup = yaml.dump(
        markup,
        Dumper=dumper,
        default_flow_style=False,
        allow_unicode=True
)
```

The array for `ShouldNotCreateEnvResources` condition seems to be the offender.

System details:
- Amplify 4.44.2
- Python Lambda Resolvers

**Comment by SwaySway** [comment]
@paolo573 
Are you using this tool?
https://github.com/awslabs/aws-cfn-template-flip

If so it looks it might a conversion issue, did you open an issue with them?

**Comment by paolo573** [comment]
@SwaySway yes, via `pip install cfn_flip` + a python script. I didn't open an issue with them - had noticed another user's comment in the linked issue in this repo, and this spawned off a conversation there. Want me to start an `awslabs/aws-cfn-template-flip` issue?

**Comment by SwaySway** [comment]
Yes as this issue seems related to this rather than the CLI.
Closing this issue for now, should you find there to be an issue with CFN Function template (in JSON) that is generated by the CLI please comment below to re-open.
