### ISSUE TITLE
How to enable my Lambda function to send mail with AWS-SDk.

### ISSUE THREAD

**Issue by tanaydpatel** [aws-amplify/amplify-cli#7141]
Hello,
I'm using AWS-SDK (JS) to send email. In EC2 I was able to access the AWS credentials from `aws configure` default profile. But when i migrated my code to serverless I'm wondering how I can set up my AWS credentials for AWS-SDK. 
Or 
How can I assign role/policy to lambda to send mail from SES.
Please tell where should I edit in <function-name>-cloudformation-template.json,
I'm confused between `AssumeRolePolicyDocument` & `lambdaexecutionpolicy` and what should be added?

ps: I'm new to AWS.

**Which Category is your question related to?**
SES

**Amplify CLI Version** 
4.49.0

**What AWS Services are you utilizing?**
Lambda, API gateway

**Provide additional details e.g. code snippets**
For sending mail I'm using code from the following documentation.
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html#ses-examples-sendbulktemplatedemail

**Comment by edwardfoyle** [comment]
Hi @tanaydpatel you'll need to edit the `lambdaexecutionpolicy` to include SES permissions. Some example permission configurations can be found here: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/control-user-access.html

In the future, you'll also need to be careful if updating lambda permissions using `amplify update function` as the execution policy may be overwritten at that time

**Comment by tanaydpatel** [comment]
Thanks for the answer.
