### ISSUE TITLE
Amplify push after remove auth don't work

### ISSUE THREAD

**Issue by DeniferSantiago** [aws-amplify/amplify-cli#7143]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.1.0`

### Amplify CLI Version

4.49.0

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, api

### Amplify Commands

push

### Describe the bug

I use amplify with the auth, api and storage features. I want to remove auth because I need to remove a required attribute. I can run `amplify remove auth` but then running `amplify push` I get an error. I think it is because api or storage use auth. I've tried commenting out all the `@auth` directives from my schema but it didn't work either.

### Expected behavior

be able to remove auth and re-add it without any error

### Reproduction steps

amplify add auth
amplify add api //with cognito auth
amplify add storage //with users and guest
amplify push
amplify remove auth
amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
| Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
× An error occurred when pushing the resources to the cloud

Template error: instance of Fn::GetAtt references undefined resource anyname5ccc6678
An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource anyname5ccc6678

```

</details>

**Comment by SwaySway** [comment]
@DeniferSantiago Are you looking at re-adding auth? API can be independent of Auth since you can use an API key for auth, though you'll need auth for storage to specify access levels. Are you looking at removing auth and then adding it back? If so you can remove and re-add just run through `amplify update` on API (if using cognito/iam) and storage to verify the newly added auth resource.

**Comment by DeniferSantiago** [comment]
Thanks for your answer @SwaySway , I will try. So would it be to run amplify remove auth, amplify add auth, amplify update api, amplify update storage and amplify push?

**Comment by SwaySway** [comment]
Yes when doing this update flows it will update the resource stacks with correct references to the new auth resource you've created.

**Comment by DeniferSantiago** [comment]
Thank you very much, the solution worked @SwaySway
