### ISSUE TITLE
Ability to resolve SSM value while testing lambda locally

### ISSUE THREAD

**Issue by jncheung** [aws-amplify/amplify-cli#7147]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Is your feature request related to a problem? Please describe.**

I am using SSM to store some third-party API endpoints and credential strings. I use `{{resolve:ssm:/path/to/my/ssm:version}}` syntax in lambdas cloudformation template. 

It works fine on the cloud, lambdas can get the values from the SSM but sadly i was unable to test the lambda using `amplify mock function` 

**Describe the solution you'd like**

I can do the mocking on my local machine instead of pushing new version to the cloud and test.

**Describe alternatives you've considered**

fallback the environment variable values if undefined

**Additional context**
```bash
me@mbp src % amplify mock function
? Select the function to mock createMember
? Provide the path to the event JSON object relative to /-/amplify/backend/function/CreateMember src/event.json
Ensuring latest function changes are built...
Starting execution...
CreateMember failed with the following error:
{
  stack: 'Error: Could not load lambda handler function due to TypeError [ERR_INVALID_URL]: Invalid URL: {{resolve:ssm:/path/dev/cat/endpoint:1}}\n' +
    '    at loadHandler (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/lib/utils/execute.js:106:15)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  message: 'Could not load lambda handler function due to TypeError [ERR_INVALID_URL]: Invalid URL: {{resolve:ssm:/path/dev/cat/endpoint:1}}'
}
Finished execution.
```
```javascript
// cloudformation.json
{
    "Environment": {
      "Variables": {
        "SDB_API_URL": {
          "Fn::Sub": [
            "{{resolve:ssm:/path/${env}/cat/endpoint:1}}",
            {
              "env": {
                "Ref": "env"
              }
            }
          ]
        },
      }
    }
    ...
}

**Comment by edwardfoyle** [comment]
Hi @jncheung we don't currently support this but we do support overriding mock lambda environment variables using a `.env` file in the function directory: https://docs.amplify.aws/cli/usage/mock#function-mock-environment-variables
You could use this as a way to override the value of that environment variable in the mock runtime

**Comment by jncheung** [comment]
@edwardfoyle thanks for your answer, putting the `.env` in the function directory works perfectly while doing mocking agaist the `api` and `function`. 

but however, amplify does not support symlink in the lambdas. So **DO NOT** try to put symlinks for shared environment variables across functions. 

otherwise the whole project will explode. :(
