### ISSUE TITLE
Amplify pull not pulling lambda function in cloud!

### ISSUE THREAD

**Issue by AyazAI** [aws-amplify/amplify-cli#7149]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

v14.16.1

### What operating system are you using?

Lubuntu

### Amplify Categories

auth, storage, function, api

### Amplify Commands

pull

### Describe the bug

Amplify pull is not fetching the updates from the cloud.
I have made changes to one of my functions in the cloud.
When I try `amplify pull` it doesn't show the changes in the terminal

### Expected behavior

It should fetch updates from the cloud!

### Reproduction steps

1: create lambda function
2: make changes in the function in the cloud
3: use `amplify pull`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
@AyazAI 
The CLI does not pull changes made in the Function Console. `amplify pull` pulls down the deployed changes that where already made in your Amplify Project.

https://docs.amplify.aws/cli/start/workflows#amplify-pull

**Comment by AyazAI** [comment]
@SwaySway 
In the lambda console, there is an option `Deploy` which means deployed the updates in the cloud.
So if it's deployed in the cloud! Shouldn't the `amplify pull` pull that change if it's part of Amplify project.
Note: Lambda function is part of my Amplify project.

**Comment by SwaySway** [comment]
Running a deploy will change the instance of the lambda that get's executed. This change does not downstream to your deployment resources, which is what the CLI references as amplify project changes that have been deployed to the cloud. 

Generally we don't advise making console changes into the resources deployed by the CLI as they can potentially cause drift in the cloudformation templates.

**Comment by AyazAI** [comment]
Can you tell specifically what cloudformation drifts may it cause!
When amplify pulling, it should check the function definition and search for changes. If it's there, the cloudformation template should be updated accordingly!

**Comment by SwaySway** [comment]
Docs on drift: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#what-is-drift

For changes on lambda function development the CLI offers the following commands:
- `amplify mock <functionName>` test your amplify function changes locally before deployment
- `amplify function push` to deploy function changes

Do you have a use case here where you need to make changes on the console as opposed to the CLI?

**Comment by AyazAI** [comment]
Thanks for the mocking command, I will definitely try that!

Amplify push takes a lot of time to push changes to the cloud, that's why I use lambda console to deploy my changes quickly. When pulling from the cloud, it says no changes detected. So, sometimes I lost the changes that I made.
I am not sure how much time would `amplify function push` take but I will give it a try!

**Comment by AyazAI** [comment]
I have implemented OTP authentication by using custom auth flow in amplify. I have 4 functions that are part of Auth. Can we mock lambda functions in this case? If yes, what could be the event object file!
Thanks

**Comment by renebrandel** [comment]
Hi @AyazAI. Amplify is built on top of AWS CloudFormation, an Infrastructure-as-Code solution. We use CloudFormation "templates" to describe, version, manage, and deploy your backend. While going through the Lambda Console and updating the function, will deploy the function, it won't actually change the information we rely on within the CloudFormation template. There is opportunity here though to showcase if there was "a drift" to warn customers that they might be overwriting externally configured changes. We might look into that as an enhancement to the `amplify push` experience.

**Comment by AyazAI** [comment]
Hi @renebrandel, that would be amazing if it can notify of externally configured changes. When using `amplify push`, how about prompting the user to pull changes from the cloud and pushing it, In this way, it will update the cloud formation template.

**Comment by SwaySway** [comment]
We don't support mocking of auth triggers though you can mock the function with your own event input. If you wanted to mock what the payload will look like you can follow Cognito's docs on what the payload will look like when invoking the function locally.

Docs: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-pools-lambda-trigger-syntax-shared

**Comment by AyazAI** [comment]
Ok thanks
I will definitely try that!
