### ISSUE TITLE
Python Lambda Layer doesn't create skeleton folder structure

### ISSUE THREAD

**Issue by glynjackson** [aws-amplify/amplify-cli#7155]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.49.0

### What operating system are you using?

MacOS

### Amplify Categories

function

### Amplify Commands

add

### Describe the bug

When creating a Python Layer documentation states 

:A python folder is auto-generated for you. In there you’ll find a skeleton folder structure to add your Python packages to. Add your packages to lib/python3.8/site-packages folder and then you can use it from within your Python function same as any other import." https://docs.amplify.aws/cli/function/layers#add-shared-code

### Expected behavior

amplify add function should follow documentation and create a skeleton folder structure /lib/python3.8/site-packages

### Reproduction steps

amplify add function            
? Select which capability you want to add: Lambda layer (shared code & resource used across functions)
? Provide a name for your Lambda layer: ExampleLayer
? Select up to 2 compatible runtimes: Python
? The current AWS account will always have access to this layer.
Optionally, configure who else can access this layer. (Hit <Enter> to skip) 

### Additional information

In additional to above the suggested folder structure if working is not correct  and should be opt/python i.e. https://stackoverflow.com/questions/65191450/aws-amplify-and-importing-lambda-layers-in-python-gives-module-not-found-error

**Comment by akshbhu** [comment]
Hi @glynjackson 

you can put layer code in both folder ```/opt/python``` or  ```python/lib/python3.8/site-packages```. you can copy your ```.py``` file to any of these and import that in functions lambda.

here is the documentation: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html.

We also follow the same in our e2e tests 
here the is the path where we put layer code : https://github.com/aws-amplify/amplify-cli/blob/ec1a5a754bc1232f6f9808025d58413c0143bfd3/packages/amplify-e2e-core/src/utils/index.ts#L71
This is the file which is copied : https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-tests/layerdata/python/testfunc.py

Can you copy the error you are facing?

**Comment by glynjackson** [comment]
Hi @akshbhu ,

Thank you for the reply. 

I'm not facing an error. Only the documentation suggests that a skeleton folder structure is created for Lambda Layers (Python). However, for me at least, this is not the case. If I follow the steps to add a new layer the function is created and a folder /opt/.

I was expecting the same behaviour as adding a normal function and the documentation suggests that  `python/lib/python3.8/site-packages` will be created and I don't have any Hello from Lambda! example. 

Glyn

**Comment by glynjackson** [comment]
Has anyone reproduced this?
