### ISSUE TITLE
Lambda layer install python packages from a listto the deployment

### ISSUE THREAD

**Issue by schorfi** [aws-amplify/amplify-cli#7158]
**Which Category is your question related to?**
Amplify function - lambda layer for python

**Amplify CLI Version** 
4.49.0

**What AWS Services are you utilizing?**
dynamodb, lambdas (python+js), API GW

**Provide additional details e.g. code snippets**
I was trying out the lambda layer as we wanted and have shared code/definitions between various lambda functions.
This was working as expected - it concerned our own modules. 
Now, we have several python lambda functions which have non-zero entries in their Pipfile for section packages. 
These were required to have the CICD pipeline create a working deployment. At one point in history, suddenly we required more packages to be listed in the pip file, because the automatically deployed version was lacking those resulting in non working functions.
For example, we required to have certifi and requests in the pip file.

Now, I wanted to have this in our shared lambda layer. But I dont know how to make amplify building it to be included into the deployment (zip file). As a comparision, I was hoping to put a Pipfile there as a dependency definition.
That doesnt work and I cannot find documentation how this is intended to do for python.

https://docs.amplify.aws/cli/function/layers#create-a-lambda-layer indicates this for nodejs...but not python

Please let me know where to look and how to do that.

Thank you

**Comment by akshbhu** [comment]
Hi @schorfi 

Currently layers doesnt  build the dependencies.  It just package the folder ``` amplify/backend/function/<layer-name>/lib/python/lib/python3.8/site-packages``` into zip. we are remodelling the layers work again to add buildstep and incorporating multienv changes.
https://github.com/aws-amplify/amplify-cli/projects/14
https://github.com/aws-amplify/amplify-cli/pull/7085

For the workaround you have to manually build the dependencies and copy them in path mentioned above. Amplify push will pick this folder and creates a deployment(zip) file which will then get deployed.

Let me know if this answers your question.

**Comment by jhockett** [comment]
Hi @schorfi,

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

For a list of new features, see the PR https://github.com/aws-amplify/amplify-cli/pull/7375

We'd love to hear any community feedback!

**Comment by renebrandel** [comment]
Hi @schorfi - we're closing this because of our new lambda layer changes has been released. Check out the details here:
- https://docs.amplify.aws/cli/function/layers#add-shared-code
- https://docs.amplify.aws/cli/migration/lambda-layers-update
