### ISSUE TITLE
Is it possible to change the username?

### ISSUE THREAD

**Issue by DeniferSantiago** [aws-amplify/amplify-cli#7159]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.49.0
**What AWS Services are you utilizing?**
Auth, API, Storage

**Issue**
I don't think it is possible to change username when creating amplify userpool by choosing to login with username.
![image](https://user-images.githubusercontent.com/41799285/115755183-12f7f400-a36b-11eb-8604-4e0fa92101fb.png)

As seen in the image the option "Also allow sign in with preferred username (a username that your users can change)" is disabled and there is no way to activate any of these options from amplify cli, it is not clear how I can use the class Auth to change username so maybe it's a problem for amplify-cli and amplify-js.

Another issue is that I see that when a user uses an external provider, a username of type is created: provider_uuid
Ex: Google_000000000000000000000

My application is type social network so the username is used for mentions and it will look ugly that there is something like @ Google_000000000000000000000 I have thought of implementing a solution with the database, that is, allowing to add a custom username for the accounts that use an external provider since the others will be limited with that the username will not change in cognito since amplify-cli does not allow me to create a userpool that allows it.

I will create this as a discussion in amplify-js and as a issue in amplify-cli

**Comment by SwaySway** [comment]
Changing the alias someone uses can't be changed once the userpool is created. Cognito Docs: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings

One option here might be that you can append an alias using a Post-Authentication trigger, and use that key/value pair to reference as the username (https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers) in your application.

**Comment by DeniferSantiago** [comment]
so there is no way to set these options from amplify-cli while using amplify add auth?
![image](https://user-images.githubusercontent.com/41799285/115778760-21eba000-a385-11eb-9d44-124e17ed6c10.png)

**Comment by SwaySway** [comment]
One thing you can do is remove the auth resource and add a new one again with the correct settings (granted this does delete info on your cognito userpool)

We don't expose this flow in the CLI because fo the aforementioned limitation with Cognito.

**Comment by DeniferSantiago** [comment]
I became agnostic of the username in cognito, now my users cannot change the username used to log in but the one visible in the application.

I'm still not happy, I ran into problems using `amplify import auth` I thought I could continue working normally with amplify

**Comment by kaustavghosh06** [comment]
@DeniferSantiago Unfortunately the settings you're referring to are immutable in the Cognito service. We're working with the Cognito team on this to see if we can make these attributes mutable.

**Comment by josefaidt** [comment]
Per the last comment these attributes are immutable and cannot be changed from the Amplify CLI. Closing as a dependency issue. You may want to provide feedback directly to the [Cognito](https://aws.amazon.com/cognito/) team for visibility.
