### ISSUE TITLE
Aws amplify Increment number from DynamoDB (using GraphQL)

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-cli#7163]
Hello everyone, 

I am using **AWS Amplify** and **graphQL**
I want to increment a variable in  **DynamoDB** in table called **song**

### In my case
I want to increment variable called **lastNumber**.

### My question 
How can many users increment by 1 field (**lastNumber**) with value of integer at DynamoDB table then each one get a different **response** ? (using the operation called increment an Atomic Counter)

Thank you in advance

**Comment by edwardfoyle** [comment]
Hi @MedNabilEssefaihi we don't currently have a graphql transformer that can generate a resolver for this. However, you can modify the resolver that is autogenerated to apply something similar to the atomic counter logic documented here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters

Documentation on custom resolvers can be found here: https://docs.amplify.aws/cli/graphql-transformer/resolvers

**Comment by MedNabilEssefaihi** [comment]
Dear Mr @edwardfoyle,

Thank you so much for your help, your answer was absolutely **fruitful** 😄
