### ISSUE TITLE
Delete Mutations created with wrong primary key

### ISSUE THREAD

**Issue by ingwinlu** [aws-amplify/amplify-cli#7168]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

4.49.0

### What operating system are you using?

Ubuntu

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Tried to extract the minimum, the model I am using is a bit more complex, however I notice the error on ALL my models that do not use an ID primary field as key.

When creating a model that is not using the default primary key like:
```

type Customer
  @model
  @key(fields: ["name"])
 {
  name: String!
  displayName: String
}
```

I notice that all my delete mutations (all models that use a custom primary key) are created wrongly (both in appsync and in codegen):
```
mutation MyMutation {
  deleteCustomer(input: {id: "TestCustomer"}) {
    displayName
  }
}
```

Executing this results in:
```
{
  "data": {
    "deleteCustomer": null
  },
  "errors": [
    {
      "path": [
        "deleteCustomer"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "The provided key element does not match the schema (Service: DynamoDb, Status Code: 400, Request ID: 4FPU3ONDN7OTFTCHI78QHF0JLNVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"
    }
  ]
}
```

Update Mutations and Queries are generated correctly (using name instead of id).

### Expected behavior

api is generated correctly

### Reproduction steps

filled in in "describe the bug" already

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

looks similar to https://github.com/aws-amplify/amplify-cli/issues/7123

I also pushed a new fresh environment, resulting in the same schema beeing generated:
![image](https://user-images.githubusercontent.com/4435962/115878692-1d88bb00-a449-11eb-953b-0d3b2b699c80.png)

**Comment by ingwinlu** [comment]
The graphql output that is build during amplify push is also building the wrong Input:
```
input CreateCustomerInput {
  id: ID
  name: String!
  displayName: String
}

input UpdateCustomerInput {
  name: String
  displayName: String
}

input DeleteCustomerInput {
  id: ID
}
```

probalby some issue around here:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-model-transformer/src/graphql-types/mutation.ts#L66

**Comment by josefaidt** [comment]
Hi @ingwinlu thanks for raising this issue and providing details! It looks like this bug is a regression from https://github.com/aws-amplify/amplify-cli/pull/6059, and has been raised internally. As a workaround, downgrade the CLI to v4.45.0 and re-run `amplify api gql-compile` to get the proper input types.

/cc @akshbhu

**Comment by siegerts** [comment]
👋 Hi, this issue was referenced in the v4.50.2 release!

Check out the release notes here https://github.com/aws-amplify/amplify-cli/releases/tag/v4.50.2.
