### ISSUE TITLE
Amplify Auth Error

### ISSUE THREAD

**Issue by SaiCharan21** [aws-amplify/amplify-cli#7171]
How do I fix the Amplify Auth Error, it all correctly pushed to amplify console but don't know what the problem is.

[ERROR] 32:55.893 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?

**Comment by kaustavghosh06** [comment]
@SaiCharan21 Do you have your aws_exports.js file checked into the src/ directory? Please check your .gitignore file.
Do you have backend builds enabled in the Amplify Console?
