### ISSUE TITLE
AWS Amplify Using Subscription Method with DynamoDB (An error occurred when pushing the resources to the cloud)

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-cli#7177]
Hi there!

I am working on project with **react native** ans **AWS Amplify**, I am using **graphQL API** with **DynamoDB**
I am getting a **subscribe** return from any changes happen in Table **Post**, I need to subscribe only when the **post identify by user** is change, so I am trying to create a filter to Subscription method using that code below and got an error:

**the code I use** 
```
type Subscription {
  onUpdatePost(userId: ID!,  deleted: Boolean!): Post
    @aws_subscribe(mutations: ["updatePost"])
}
```
**the error I get**

```
✖ An error occurred when pushing the resources to the cloud

Object type extension 'Subscription' cannot redeclare field onUpdatePost
An error occurred during the push operation: Object type extension 'Subscription' cannot redeclare field onUpdatePost
```

**Comment by edwardfoyle** [comment]
@MedNabilEssefaihi this is probably because the @model directive is generating a conflicting onUpdatePost operation. You can turn this off by adding `@model(subscriptions: null)` to the directive. Note that this will also remove automatic generation of update and delete subscriptions as well.
