### ISSUE TITLE
Amplify JWT from Auth not validating in API

### ISSUE THREAD

**Issue by BryanZWu** [aws-amplify/amplify-cli#7178]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
CLI Auth and API

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.49.0

**What AWS Services are you utilizing?**
DynamoDB, S3, cloudofrmation, Cognito Auth

**Provide additional details e.g. code snippets**
I mistakenly deleted the cloudformation stacks which were on my dev environment and am creating a new dev environemnt. I used the following commands:

```
amplify env checkout [now-broken-dev-branch]
amplify env pull
amplify env checkout [new-dev-branch]
amplify push
amplify env pull
```
to recreate an environment and am running into an issue where I am unable to access any of the restricted APIs as a signed-in client via Auth (returns 403s). I am able to successfully access the endpoint using postman and my aws credentials, but it appears that for some reason or another, using the JWT generated by `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` in the API header does not seem to work anymore, and returns 403s. The [CLI auth documentation](https://docs.amplify.aws/cli/auth/overview#unlink-an-existing-cognito-user-pool-or-identity-pool) doesn't really explain why it might be erroring out. 

How can I troubleshoot this?

**Comment by edwardfoyle** [comment]
Hi @BryanZWu a couple things you can check:
1. Does your aws-exports.js file have the cognito user pool id and other cognito values populated?
2. Do you have an old session cookie that may still be pointing to a user in the old environment?

**Comment by BryanZWu** [comment]
Hi @edwardfoyle, thanks for the response--
`aws-exports.js` does have the correct cognito user pools id and the other fields are populated. I don't recognize the `aws_cognito_identity_pool_id` anywhere in my user pool console, but the `aws_user_pools_id` matches the user pool I'm interested in. I think the `aws_user_pools_web_client_id` is likely correct, as it refers to the `clientWeb` app Id, but I am not certain. 

Regarding the second point, I've cleared the cookies and am getting the same 403, so I don't think that's it?

**Comment by BryanZWu** [comment]
Hi! Any updates on this? This is blocking quite a few engineers on our team and we'd love to get this back ASAP.

**Comment by edwardfoyle** [comment]
@BryanZWu you can check the identity pool values at https://console.aws.amazon.com/cognito/federated/?region=us-east-1 (substitute the region if different than us-east-1). That console page will list all of your identity pool and you can make sure that the appropriate one is in the aws-exports.js file.

**Comment by kaustavghosh06** [comment]
Closing due to lack of further requested information.
