### ISSUE TITLE
Amplify appsync mutation direct lamda resolver is not syncing with amplify datastore

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-cli#7185]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.4

### Amplify CLI Version

4.49.0

### What operating system are you using?

Ubuntu 20.04 in WSL

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

On configuring a direct lambda resolver for appsync mutation to batchWrite to a @model Dynamodb table. The resulting changes are not getting synced with datastore normally. Only after a proper `await Datastore,stop()` & `await Datastore.start()` are the changes to the dynamodb tables showing up in datstore.  I am adding the following fields to dynamodb table extra to make it work with datastore `__typename`, `_lastChangedAt`, `_version`, `owner`, `createdAt` & `updatedAt`. 

### Expected behavior

On successful batchWrites with the lambda resolvers to the dynamodb table the data should sync with the datastore using subscription. 

### Reproduction steps

1. Create two @model tables (Quote, QuoteInfo)
2. Crate a new mutation with  custom lambda resolver to create multiple Quote & QuoteInfo
```graphql
type Mutation {
 createQuoteAndQuoteInfos(quoteName: String!): CreateQuoteAndQuoteInfosResponse
    @function(name: "createQuoteAndQuoteInfos-${env}")
}

type CreateQuoteAndQuoteInfosResponse {
  id: ID
  name: String
}
```
3. Create the lamda function with the necessary fields for datastore
```js

async function createQuoteAndQuoteInfos(event) {
  const addQuoteInfoRes = await addQuoteInfoOfQuote(event.arguments.quoteName)
  return { id: addQuoteInfoRes }
}

async function addQuoteInfoOfQuote(quoteName) {
  const currentTime = new Date()
  const updateTime = currentTime.toISOString()
  const lastChangeTime = currentTime.getTime()
  let costlinesArray = createQuoteTemplate({ quoteName})
  costlinesArray = JSON.parse(JSON.stringify(costlinesArray))
  const seedData = costlinesArray.map((item) => {
    return {
      PutRequest: {
        Item: {
          ...item,
          id: nanoid(),
          __typename: 'QuoteInfo',
          _lastChangedAt: lastChangeTime,
          _version: 1,
          owner: '4d58f556-1272-48b4-863a-da8a0e73f',  //owner id 
          createdAt: updateTime,
          updatedAt: updateTime,
        },
      },
    }
  })
  const chunks = await sliceInChunks(seedData)

  const createdQuoteInfo = await createQuoteInfo(chunks)

  return createdQuoteInfo
}

async function sliceInChunks(arr) {
  let i
  let j
  const CHUNK_SIZE = 25 // DynamoDB BatchWriteItem limit
  const chunks = []

  for (i = 0, j = arr.length; i < j; i += CHUNK_SIZE) {
    chunks.push(arr.slice(i, i + CHUNK_SIZE))
  }

  return chunks
}

async function createQuoteInfo(chunks) {
  const promises = chunks.map(async function (chunk) {
    const params = { RequestItems: { [QUOTEINFOTABLE]: chunk } }
    const res = await docClient.batchWrite(params).promise()
    return res
  })

  return await Promise.all(promises)
}
```

4. Fire the mutation and check the datastore doesn't sync the data.
5. Restart datastore and see the new data has been synced. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Quote @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  quoteInfo: [QuoteInfo] @connection(keyName: "byQuote", fields: ["id"])
}

type QuoteInfo @model @key(name: "byQuote", fields: ["quoteId"]) @auth(rules: [{ allow: owner }]) {
  id: ID!
  quoteId: ID!
  quantity: Float
  rate: Float
  unit: String
  smg: Float
}

type overtimeDetail {
  multiplier: Float
  overtimeHours: Float
}

type Mutation {
  deleteQuoteAndQuoteInfo(quoteId: ID!): DeleteQuoteAndQuoteInfosResponse
    @function(name: "editQuoteAndQuoteInfos-${env}")
  createQuoteAndQuoteInfos(quoteName: String!): CreateQuoteAndQuoteInfosResponse
    @function(name: "createQuoteAndQuoteInfos-${env}")
}

type DeleteQuoteAndQuoteInfosResponse {
  id: ID!
}

type CreateQuoteAndQuoteInfosResponse {
  id: ID
  name: String
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nubpro** [comment]
For subscriptions to work properly, you need to call Appsync GraphQL at the end instead of writint directly to DynamoDB. If Im not wrong you can write a batchWrite function for appsync gql

**Comment by DevTGhosh** [comment]
@nubpro Any idea on how to do that or manually force a sync of the changed data? Currently even on a refresh of the page  `syncQuoteInfos` graphql query don't get the changed data.

**Comment by nubpro** [comment]
> @nubpro Any idea on how to do that or manually force a sync of the changed data? Currently even on a refresh of the page `syncQuoteInfos` graphql query don't get the changed data.

The right way is to call appsync not write directly into ddb

**Comment by greendinosaur** [comment]
@nubpro Incidentally, I've recently added DataStore to an existing graphql that had a batch resolver to batch insert items into a Dynamo DB table. The resolver now doesn't work. Are you sure that DataStore supports BatchPutItem?

The error I get from the resolver is: 

> Unsupported operation 'BatchPutItem'. Datasource Versioning only supports the following operations (TransactGetItems,PutItem,BatchGetItem,Scan,Query,GetItem,DeleteItem,UpdateItem,Sync)

The resolver code is:
```
#set($transectSitesData = [])
#foreach($item in ${ctx.args.transectSites})
    $util.qr($item.put("createdAt", $util.time.nowISO8601()))
    $util.qr($item.put("updatedAt", $util.time.nowISO8601()))
    $util.qr($item.put("_lastChangedAt", $util.time.nowISO8601()))
    $util.qr($item.put("__typename", "MyTable"))
    $util.qr($item.put("_version", 1))
    $util.qr($item.put("id", $util.defaultIfNullOrBlank($item.id, $util.autoId())))
    $util.qr($transectSitesData.add($util.dynamodb.toMapValues($item)))
#end
{
  "version": "2018-05-29",
  "operation": "BatchPutItem",
  "tables": {
      "MyTable-API-mydev": $utils.toJson($transectSitesData)
  }
}
```

The only changes I've made in an attempt to resolve the error is to add the _version and _lastChangedAt fields into this template.

**Comment by DevTGhosh** [comment]
@nubpro  I have to create 10,000+ rows how would suggest to do it in a fast manner with appsync that is not just 10,000 graphql calls. 

@greendinosaur datastore doesn't support BatchPutItem that is there for dynamodb, datastore is built on top of IndexedDB for web and SQLite for mobile.

**Comment by nubpro** [comment]
I supposed you could create a Dynamodb resolver for Appsync, apparently Im both right and wrong

This is only possible if you didnt had versioning enabled but this is mandatory for DataStore to function properly.

https://github.com/aws-amplify/amplify-cli/issues/3889#issuecomment-611105420

I dont think think you can run away from triggering 10k requests....?

**Comment by edwardfoyle** [comment]
Hi @DevTGhosh the issue here is that the DeltaSync table is not populated with the changes that your lambda resolver is making to the table. When mutating data through AppSync this happens automatically but not when using a lambda resolver as there is no way for AppSync to know what is being mutated. You may be able to get this to work by updating the DeltaSync table within your lambda resolver. Some docs on implementation details can be found here: https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js#sync-data-to-cloud
Note however that the DeltaSync table is meant to be an internal implementation detail of DataStore and in general we do not recommend customers depend directly on it.
