### ISSUE TITLE
Prepend Function/API names with amplify app names in lambda

### ISSUE THREAD

**Issue by ashleyoldershaw** [aws-amplify/amplify-cli#7189]
**Is your feature request related to a problem? Please describe.**
When I make lambda functions in AWS Amplify and name them we get the actual lambda function created with the friendly name we give it, with the env name at then end. However, if I have 2 projects with 2 functions that could reasonably be called something like `getDataFunction` there would be a clash. This also happens with API gateway instances.

**Describe the solution you'd like**
Prepend the function name in a similar way that cloudformation stacks are made so that duplicate function names don't clash.

e.g. if your amplify app was called "my-amplify-app" we could call the function "my-amplify-app-getDataFunction"

**Describe alternatives you've considered**
We could just name the functions long and complex names to avoid clashes but it seems a bit unwieldy to do so.

**Additional context**
Almost duplicated function names here - if we had another project with the same function name there would be a clash.
![image](https://user-images.githubusercontent.com/15020968/116254048-ed069100-a768-11eb-840d-80fb6dec4957.png)

**Comment by LoganArnett** [comment]
@edwardfoyle  I would like to take this one, just need to confirm if appending the amplify app name is the expected prefix

**Comment by ykethan** [comment]
Hey @ashleyoldershaw, we can leverage tags to identify a function. Please refer to https://docs.amplify.aws/cli/project/tags/ for additional information.
