### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by ReidWeb** [aws-amplify/amplify-cli#719]
**Describe the bug**
Receiving following invoking any operation
```
The AWS Access Key Id you provided does not exist in our records
```

**To Reproduce**
1. Using access key generated using STS - very definitely valid - was working previously via a named profile - correctly specified in config.
2. Run any command e.g. `amplify init` or `amplify env pull` 

**Expected behavior**
Should successfully authenticate and run expected operations.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/3649078/51219309-3039ee80-1928-11e9-86ec-20fedfbbeb17.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version 0.2.1-multienv.26, also tried revert and run with 0.2.1-multienv.21

**Comment by ReidWeb** [comment]
Possibly related to #709 - I applied kevin's fix and not hitting the issue.

**Comment by UnleashedMind** [comment]
Please also check my response to #709 
Temp credentials you got directly from STS would not directly work in the normal cli profile setup. 
Because as you guys have found out, the cli does not read session_token from the config file, and for temp credentials, the api call will fail without the session_token.

**Comment by ReidWeb** [comment]
It's an interesting decision not to support this? In a lot of large enterprises (including some major customers), I'm aware that STS sign in is the only option available for such operations as in these situations devs can't get any other programmatic access to AWS via any other mechanism?

Personally I'm of the opinion that the auth mechanisms supported by other AWS tools (Node SDK) should be supported here... It was working fine for me up to recently?

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks, we are currently working to improve this part of the UX. By the way, the aws javascript sdk itself does not support temp credentials out of the box like that, the aws cli does.

**Comment by UnleashedMind** [comment]
@undefobj 
This issue has been addressed in our last merge. 
MFA support is implemented and in the PR, pending review. 
#718 
#734

**Comment by UnleashedMind** [comment]
The fix by @hakanson is released in the @latest and the @multienv versions.
