### ISSUE TITLE
CLI dont generate the "/*" part of the PolicyDocument Resource URL Template

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#7197]
### Before opening, please confirm:

- [x] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v15.5.0

### Amplify CLI Version

4.49.0

### What operating system are you using?

MacOS

### Amplify Categories

function, api

### Amplify Commands

codegen

### Describe the bug

I added a lambda function to call GraphQL from Nodejs in Lambda. When I try to call the GraphQL API, I get an error "permission denied". 
So I checked the Auth directives before, and all seems to be ok. 
```
@auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: groups, groupsField: "partner_id" }
      { allow: public, provider: iam }
    ]
  ) {
```

I checked the role permissions to. All was ok: 

```
 {
              "Effect": "Allow",
              "Action": [
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*"
              ],
....
```

than I checked the ResourvePolicy. 
Here I found the fix. I have to add by myself the last part of the URL Template. ->   **"/*"** 
Than all is working. 

```
"AmplifyResourcesPolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "appsync:GraphQL",
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      {
                        "Ref": "AWS::Region"
                      },
                      ":",
                      {
                        "Ref": "AWS::AccountId"
                      },
                      ":apis/",
                      {
                        "Ref": "apiaivyGraphQLAPIIdOutput"
                      },
                      "/*"
                    ]
                  ]
                }
              ]
            }
          ]
        }
      }
    }
```

### Expected behavior

Like before, the cli generates the   "/*" too in the CloudFormation files. 

### Reproduction steps

add a function, give it access to api. 

### GraphQL schema(s)

<details>

```graphql
type Space
  @model
  @key(name: "BySecureHash", fields: ["secure_hash"], queryField: "spacesBySecureHash")
  @key(
    name: "ByPartnerIdByDate"
    fields: ["partner_id", "createdAt"]
    queryField: "spacesByPartnerIdByCreatedAt"
  )
  @key(name: "ByOwner", fields: ["owner"], queryField: "spacesByOwner")
  @key(name: "ByCareerId", fields: ["career_id"], queryField: "spacesByCareerId")
  @key(
    name: "ByPartnerUserIDByPartnerID"
    fields: ["partner_user_id", "partner_id"]
    queryField: "spacesByPartnerUserIDByPartner"
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: groups, groupsField: "partner_id" }
      { allow: public, provider: iam }
    ]
  ) {
  id: ID!
  owner: ID!
  newsletter: Boolean
  progress: Int
  partner_id: ID!
  career_id: ID
  #users ID from Partner
  partner_user_id: String!
  secure_hash: String
  language: String
  ref_link: String
  matching_score_to_space_career: Float
  related_spaces: AWSJSON
  createdAt: String
  updatedAt: String
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
Hi @davidbiller this has been fixed but it is behind a feature flag to maintain backwards compatibility with existing projects. You can enable the [generateGraphQLPermissions](https://docs.amplify.aws/cli/reference/feature-flags#generateGraphQLPermissions) feature flag in your `cli.json` file to take advantage of the new policy generation

**Comment by davidbiller** [comment]
@edwardfoyle Okay. I see.

So I started my project long time ago, so If I understand it right, I have to add now the cli.json and add some entries. 
I added this: 

` ` `{
  "features": {
    "appSync": {
      "generateGraphQLPermissions": true
    },
    "graphQLTransformer": {
      "addMissingOwnerFields": true,
      "validateTypeNameReservedWords": true,
      "useExperimentalPipelinedTransformer": false,
      "enableIterativeGSIUpdates": false
    },
    "codegen": {
      "useAppSyncModelgenPlugin": true,
      "useDocsGeneratorPlugin": true
    }
  }
}
` ` ` 

and now after the creation of a lambda function and add permission to api, I got this: 


```{
                  "Fn::Join": [
                    "",
                    [
                      "arn:aws:appsync:",
                      { "Ref": "AWS::Region" },
                      ":",
                      { "Ref": "AWS::AccountId" },
                      ":apis/",
                      { "Ref": "apiaivyGraphQLAPIIdOutput" },
                      "/types/Mutation/*"
                    ]
                  ]
                }```
                
                
                is this good? Deprecated at May 2021. So I only can use this style right?

**Comment by davidbiller** [comment]
Do i have to upadte all Lambda functions now?
