### ISSUE TITLE
Support non-scalar fields in mutations

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#72]
**Do you want to request a feature or report a bug?**

Feature request
 
**What is the current behavior?**

Currently the DyanmoDBModelTransformer skips non scalar fields when creating inputs for mutations. 

Can this functionality be added? since input object types can also refer to other input objects it should be possible to infer an input for each non scalar object. The non scalar could be saved as inline or map attribute in DynamoDB.

another possibility would be to add a specific directive for certain use cases. for example would it make sense to have a `@s3object` directive to have special handling of complex object that gets stored in S3 by appsync? (there's no real special handling except that the S3ObjectInput requires more fields than the actual S3Object in order to get properly handle by AppSync SDK)

**Comment by mikeparisstuff** [comment]
I propose that when a @model type has a field with a type that is a **NON** @model object type, we walk that **NON** @model object type creating an input object types for every **NON** @model type in the sub tree. We then include that top level **NON** @model type's input in the @model create input.

For example

```graphql
type Post @model {
  id: ID!
  title: String
  metadata: PostMetadata
}
type PostMetadata {
  tags: Tags
}
type Tags {
  published: Boolean
}
```

Would create the following:

```graphql
type Post {
  id: ID!
  title: String
  metadata: PostMetadata
}
type PostMetadata {
  tags: Tags
}
type Tags {
  published: Boolean
}

# update @model inputs
type CreatePostInput {
  title: String
  metadata: PostMetadataInput
}
type UpdatePostInput {
  id: ID!
  title: String
  metadata: PostMetadataInput
}
type DeletePostInput {
  id: ID!
}

# non @model inputs. These are stored inline within other top level @model types.
type PostMetadataInput {
  tags: TagsInput
}
type TagsInput {
  published: Boolean
}
```

**Comment by mwarger** [comment]
I want to point out what could possibly be a simpler case of a non-scalar type, and that is `enums`.  Enums are not being translated into the input types after schema generation even though they are essentially strings, AFAIK.

**Comment by kaustavghosh06** [comment]
We've merged a fix for this. We'll publish a new version for the CLI on Monday which would have this fix.
