### ISSUE TITLE
APIGatewayAuthStack error after upgrading to v4.50.0

### ISSUE THREAD

**Issue by chriswaterbury** [aws-amplify/amplify-cli#7201]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.20.0

### Amplify CLI Version

4.50.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

After updating to v4.50.0 from v4.49.0 amplify push fails.

First happened with a continuous deployment with @latest amplify cli, but I get the same error locally

`CREATE_FAILED      APIGatewayAuthStack AWS::CloudFormation::Stack Tue Apr 27 2021 18:08:34 GMT+0000 (Coordinated Universal Time) Output 'ApiId' not found in stack`

APIGatewayAuthStack.json appeared in the amplify/backend/api folder

Added ApiId to admin-queries-cloudformation-template.json Outputs and get a similar error but for both Rest APIs in my stack

`CREATE_FAILED APIGatewayAuthStack AWS::CloudFormation::Stack Wed Apr 28 2021 12:26:18 GMT-0400 (Eastern Daylight Time) Parameters: [CustomRestAPI, AdminQueries] do not exist in the template`

Amplify push succeeds after downgrading to v4.49.0. Both REST APIs use Cognito user pool auth

### Expected behavior

Expected upgrading to v4.50.0 from v4.49.0 to succeed when pushing previously working backend

### Reproduction steps

1. Have AdminQueries REST API
2. Upgrade from v4.49.0 to v4.50.0
3. Attempt to amplify push

**Comment by cjihrig** [comment]
Thanks for reporting this @chriswaterbury. There is a fix for this underway at https://github.com/aws-amplify/amplify-cli/pull/7192. Please stick with v4.49.0 for the time being.

**Comment by siegerts** [comment]
👋 Hi, this issue was referenced in the v4.50.2 release!

Check out the release notes here https://github.com/aws-amplify/amplify-cli/releases/tag/v4.50.2.
