### ISSUE TITLE
Use GraphQL code-gen types and endpoints in Functions

### ISSUE THREAD

**Issue by chriszirkel** [aws-amplify/amplify-cli#7210]
**Which Category is your question related to?**
API (GraphQL), Function

**Amplify CLI Version** 
4.47.1

**What AWS Services are you utilizing?**
AppSync, Lambda

**Provide additional details e.g. code snippets**
I have an Amplify backend project with an GraphQL API and a Resolver Function. The folder structure is the following:
```
/amplify/backend/api/graphql
  - schema.graphql
/amplify/backend/function/resolver/src
  - handler.ts
/amplify/src
  - /graphql/queries.ts
  - API.ts
  - aws-exports.js
  ```

The resolver function must access the GraphQL api and needs the endpoint information (appsync url, api key, etc) and query statements and types. I was following the official guide (https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#query) on how to access it from Node.js, but the example uses the env variables API_URL and API_KEY and defines the grapqhl query inline? 
How can I access the code-generated files (e.g. API.ts, queries.ts, mutations.ts...) from the function, so that I don't have to write the queries again and can rely on generated type declarations? Furthermore, how can I access the API url and key?

I was trying to import it like `import * as queries from "../../../../../src/graphql/queries"`, but that results in long relative paths and the function deployment build does not include these files and the function fails with an import error at runtime.

I guess there must be an recommended way to  get the API information into the functions?

**Comment by edwardfoyle** [comment]
Hi @chriszirkel we have this feature request for placing the generated files into a function: https://github.com/aws-amplify/amplify-cli/issues/5879

As for accessing the API from the lambda, the environment variables that are automatically populated are `API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT` and `API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT`

**Comment by chriszirkel** [comment]
> Hi @chriszirkel we have this feature request for placing the generated files into a function: #5879
> 
> As for accessing the API from the lambda, the environment variables that are automatically populated are `API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT` and `API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT`

Hi @edwardfoyle thank you for your reply. It seems like the GraphQL API does not get populated into the environment variables of my function. Here a console.log of process.env while executing:

```
2021-04-29T14:30:24.650Z	5e3f5cb3-45db-4dd9-8ff8-e130193459bf	INFO	env {
  AWS_LAMBDA_FUNCTION_VERSION: '$LATEST',
  AWS_SESSION_TOKEN: '',
  AWS_LAMBDA_LOG_GROUP_NAME: '/aws/lambda/resolver-dev',
  LD_LIBRARY_PATH: '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib',
  LAMBDA_TASK_ROOT: '/var/task',
  AWS_LAMBDA_LOG_STREAM_NAME: '2021/04/29/[$LATEST]cd20e9c2cb134fef95dd88286dbaba77',
  AWS_LAMBDA_RUNTIME_API: '127.0.0.1:9001',
  ENV: 'dev',
  AWS_EXECUTION_ENV: 'AWS_Lambda_nodejs14.x',
  AWS_XRAY_DAEMON_ADDRESS: '169.254.79.2:2000',
  AWS_LAMBDA_FUNCTION_NAME: 'resolver-dev',
  PATH: '/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin',
  AWS_DEFAULT_REGION: 'eu-west-1',
  PWD: '/var/task',
  AWS_SECRET_ACCESS_KEY: '',
  LAMBDA_RUNTIME_DIR: '/var/runtime',
  LANG: 'en_US.UTF-8',
  AWS_LAMBDA_INITIALIZATION_TYPE: 'on-demand',
  NODE_PATH: '/opt/nodejs/node14/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task',
  AWS_REGION: 'eu-west-1',
  TZ: ':UTC',
  AWS_ACCESS_KEY_ID: '',
  REGION: 'eu-west-1',
  SHLVL: '0',
  _AWS_XRAY_DAEMON_ADDRESS: '169.254.79.2',
  _AWS_XRAY_DAEMON_PORT: '2000',
  AWS_XRAY_CONTEXT_MISSING: 'LOG_ERROR',
  _HANDLER: 'index.handler',
  AWS_LAMBDA_FUNCTION_MEMORY_SIZE: '128',
  _X_AMZN_TRACE_ID: 'Root=1-608ac2ff-51c6b02f63e7707f44da5b99;Parent=00954e1032c78147;Sampled=0'
}
```

Am I missing something?
