### ISSUE TITLE
CircleCI returns failed because of they can't get package `openjdk-8-jdk-headless`

### ISSUE THREAD

**Issue by tacck** [aws-amplify/amplify-cli#7235]
I added PR #7234 , and I got failed from CircleCI's check.

I checked results, I can see this message..

```
Err:61 http://security.debian.org/debian-security stretch/updates/main amd64 openjdk-8-jdk-headless amd64 8u275-b01-1~deb9u1
  404  Not Found
```

All messages are here.

* https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/449/workflows/8821c50d-a12d-41de-8ea5-a3a27d1a71ad/jobs/4550
* https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli/449/workflows/8821c50d-a12d-41de-8ea5-a3a27d1a71ad/jobs/4551

**Comment by attilah** [comment]
@tacck Added a reply to your PR thanks for the contribution. Closing this issue as the pipeline is already fixed.
