### ISSUE TITLE
Deletion failed NotFound (from AWS Amplify Console)

### ISSUE THREAD

**Issue by renegoretzka** [aws-amplify/amplify-cli#7238]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.19.0

### Amplify CLI Version

4.50.0

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

add, env

### Describe the bug

After checking out an amplify project from another AWS account with AdministratorAccess-Amplify IAM Policy, pull an existing Amplify Environment and trying to add a new environment, I ran into this CloudFormation Error:

`CREATE_FAILED        DeploymentBucket                      AWS::S3::Bucket            Mon May 03 2021 13:52:20 GMT+0200 (GMT+02:00) API: s3:SetBucketEncryption Access Denied`

I didn't had access to the S3 bucket, which was quite obvious afterwards. After I got access to the S3 bucket, I wasn't able to to create the environment once again, since it said that the Stack already exists:
```
\ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
× Root stack creation failed
AlreadyExistsException: Stack [amplify-sunstreetadmin-renedev-135214] already exists
```
So I tried to list the environments using `amplify env list`, where I did not find the new environment to remove it. I also tried to just remove it by `amplify env remove ENVNAME`, but it said no environment found.

I checked the Amplify Console in the browser and I have seen the environment, but were not able to delete it thru the Console as it said the following: `Deletion failed NotFound - An error occurred while processing your request: NotFound: null`

So I am not able to delete the wrongly created environment in any way.

### Expected behavior

1. If the creation of the bucket fails, because I am lack of S3 permissions, the rollback should also delete the whole environment.
2. If that is not possible, at least show it in the list of environments by `amplify env list` and be able to delete it by `amplify env remove ENVNAME`
3. If that is not possible, I should be able to delete the environment in the AWS Amplify Console.

### Reproduction steps

1. Create Amplify application
2. Share with another IAM user with Amplify access, but no S3 access policies.
3. Pull the Amplify application by the newly created IAM user. `amplify pull ...`
4. Try to create a new environment by using `amplify env add`, which fails due to lack of permissions.
5. Check the environments and remove it either by `amplify env remove ENVNAME` or by the AWS Amplify Console.

### GraphQL schema(s)

Not needed

### Additional information

Couldn't find an work-around to delete the environment.

**Comment by attilah** [comment]
@renegoretzka sorry that you got stuck in between and thanks for the input about the enhancements about the failure case and it makes sense, I will mark the issue as an enhancement to the existing flow.

To get you unstuck would you try to delete the stack that was create for the new environment from the CFN console and then try two things:
- remove the env from amplify console after the CFN stack was deleted
- if the above would failed for some reason try to add the env from CLI and get back to us with the results
