### ISSUE TITLE
How to backfill data for compound sort key

### ISSUE THREAD

**Issue by danielvouch** [aws-amplify/amplify-cli#7240]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Storage (DynamoDB)

**Amplify CLI Version** 
4.49.0

**What AWS Services are you utilizing?**
DynamoDB

**Provide additional details e.g. code snippets**
We have created a new GSI that has a compound sort key status#createdAt, the Amplify documentation states that if you create a GSI that has a compound sort key that you will have to backfill the data in the index, what is the best way to go about backfilling the data?

`@key(name: "TestStatus_byEntity", fields: ["entityId", "status", "createdAt"])`

**Comment by siegerts** [comment]
Hi @danielvouch :wave: - thanks for raising this!  To get a bit more context, do you mind porting this to the formatted template below:

- [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=)

This will help the team determine the best approach to take will all of the required information.
