### ISSUE TITLE
Amplify local mock question

### ISSUE THREAD

**Issue by marco-staizen** [aws-amplify/amplify-cli#7259]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify function
Amplify mock api

**Amplify CLI Version** 
4.49.0

**What AWS Services are you utilizing?**
 AppSync

**Provide additional details e.g. code snippets**
I attached a non amplify generated lambda function but it throws this error when I run amplify mock api
<img width="455" alt="image" src="https://user-images.githubusercontent.com/79079991/117103278-9fafa280-adac-11eb-8710-e14a1a7777b1.png">
Note: This function exists in the cloud
Code Snippet usage:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/79079991/117103300-aa6a3780-adac-11eb-9c31-bf0de01ca087.png">

**Comment by attilah** [comment]
@marco-staizen it looks more like an issue, than a question, please open a new issue form to provide all the required details to be able to help you with your problem.
