### ISSUE TITLE
codegen causes "Cannot convert undefined or null to object" error

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#726]
**Describe the bug**
When trying to generate code for a demo simple schema, amplify CLI gives the error 
`Cannot convert undefined or null to object`
Project is a SPA web app, with pure JS, no framework involved.

**To Reproduce**

0. Initialize your project with the usual `amplify init`

1. Create an API with Schema

```
type Match {
	face: String!
	match: String!
	confidence: Float!
}
type Query {
	matches: [Match]
}
schema {
	query: Query
}
```

2. In a terminal, type 
`amplify codegen add --appId <your API ID>`

3. Result 
`Cannot read property 'inputParams' of undefined`

**Expected behavior**
codegen should complete and generate the client side code to call the API

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2
 - Amplify
```bash
$ node --version && amplify --version
v11.6.0
0.1.42
```
**Smartphone (please complete the following information):**
 n/a

**Additional context**
n/a

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by yuth** [comment]
When you add the API what language target did you use?

**Comment by sebsto** [comment]
Two things : 
1. The above error was my mistake : I typed `--appId` instead of `--apiId` 
Suggestion : the error message can be more informative in that case.

2. When correctly using `--apiId` I still have an undefined error.

```
$ amplify add codegen  --apiId fad...ncm
✖ Getting API details
The "id" argument must be of type string. Received type undefined
```
The error happens before the CL will ask for a language.

**Comment by sebsto** [comment]
None.

**Comment by kaoskeya** [comment]
I get this issue only while using the multienv cli. It works fine with the same AppSync App while using the non-multicli amplify-cli.

**Comment by yuth** [comment]
@kaoskeya thank you for the clarification. 

The fix is in `0.2.1-multienv.36`

**Comment by sebsto** [comment]
Confirmed this is working for me using `0.2.1-multienv.36`

**Comment by davidfarinha** [comment]
I had a similar issue ("cannot read 'inputParams' of undefined") that is fixed for me using 0.2.1-multienv.36. Thanks!

**Comment by vientang** [comment]
I'm getting the same error message when I run amplify push. "Cannot convert undefined or null to object". This happens right after the prompt "Are you sure you want to continue?". 

I'm using @aws-amplify/cli version 0.1.45 - not multienv.
API is AppSync (GraphQL)
Auth is cognito
Hosting is S3andCloudfront
Provider plugin - awscloudformation

The app works. It's just that I get this message when running amplify push. Any suggestions on what to do?

**Comment by yuth** [comment]
@vientang this is not related to the above issue. Could you raise a separate issue for the same, so that we can track it

**Comment by vientang** [comment]
@yuth Here's the issue I've created - https://github.com/aws-amplify/amplify-cli/issues/850
