### ISSUE TITLE
add auth field to connection directive

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#7260]
### Is this related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

To protect the grapqhQL API against nesting attacks, the connection resolvers should have the option to specify an identity check.

A basic example of a nesting attack is: a user is allowed to query his friends. If the friendship joint table is not protected by some identity check, this user is also able to query friends of friends and so on.

### Describe the solution you'd like

For example:

```
type User {
  id: ID!
  name: String
 friends: [Friendship] @connection(fields: ["id"])
}

type Friendship @key(fields: ["userId", "friendId"]) {
  userId: ID!
  friendId: ID!
  user: User @connection(fields: ["userId"], authFields: ["userId, friendId"])
  friend: User @connection(fields: ["friendId"], authFields: ["userId, friendId"])
}
```
And in the result resolver template
```
#set($authorized = false)
#foreach($entry in $authFields)
  #if($ctx.result[$entry] == $ctx.identity.username)
    #set($authorized = true)
  #end
#end
#if(!$authorized)
  $util.unauthorized()
#end
```

### Describe alternatives you've considered

Set a maximum depth on the nesting of objects

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by attilah** [comment]
@avlonder thanks for the feature request, `@connection` do support authorization on related data if queries are disabled on the related type (`Friendship`). As this is a very special use case to unblock you I'd suggest to implement this functionality with custom resolvers.

**Comment by avlonder** [comment]
@attilah, even if queries are disabled on the friendship type, a user can access data from friends of friends of friends of ... (you see where I'm going), because there's nothing validating the identity in the resolvers created by the connection directive.

**Comment by avlonder** [comment]
Indeed, I could write custom resolvers to exactly do this identity check, but then what's the point in offering a CLI with graphql-transformer. Also, I think this is a very common use case and many AppSync practitioners are unaware of the security leak.

**Comment by avlonder** [comment]
Ow, now I see the confusion... I had a misunderstanding about *$ctx.source* (I thought it was the object one level higher, but it is the very root object), so indeed, the solution I propose is not better than just not creating queries like you suggested. However, this still doesn't solve the issue of nesting attacks.
