### ISSUE TITLE
Generated create mutation template doesn't use modelObjectKey for conditions

### ISSUE THREAD

**Issue by pagameba** [aws-amplify/amplify-cli#7261]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.0.0

### Amplify CLI Version

4.50.2

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

A schema with a model containing two fields in the primary index not using `id` does not generate a create mutation with a condition that returns an  error when creating an item with duplicate values in the primary index.  You can run the create mutation multiple times with the same primary index values and it reports success.

### Expected behavior

Attempting to create a new record when the primary key values collide with an existing record should fail.

### Reproduction steps

A model below allows you to invite the same user to the same organization multiple times without error.  Duplicate database entries are not actually created.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type UserInvite
@model
@key( fields[ 'organizationId', 'email' ] )
{
  organizationId: ID!
  email: String!
  note: String!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

The generated resolver template for `Mutation.createUserInvite.req.vtl` contains this logic:

```
## [Start] Prepare DynamoDB PutItem Request. **
$util.qr($context.args.input.put("__typename", "UserInvite"))
#set( $condition = {
  "expression": "attribute_not_exists(#id)",
  "expressionNames": {
      "#id": "id"
  }
} )
```

Using AppSync's query interface, you can run the `createUserInvite` mutation with the same organizationId and email and it returns successfully.  Note that it does not actually create multiple items in the database.  If you subscribe to `onCreateUserInvite` it will trigger the subscription as if it *had* created a new UserInvite.  What actually appears to happen, if you pass an alternate value for other fields, is it actually *updates* the existing record in the database.

By contrast, if you attempt to use `updateUserInvite` with the same model and pass non-existent values for the primary keys, it will fail the conditional check.  Looking at the `Mutation.updateUserInvite.req.vtl`, we see it generates the correct conditions if `modelObjectKey` is set.

```
  #if( $modelObjectKey )
    #foreach( $entry in $modelObjectKey.entrySet() )
      $util.qr($condition.put("expression", "$condition.expression AND attribute_exists(#keyCondition$velocityCount)"))
      $util.qr($condition.expressionNames.put("#keyCondition$velocityCount", "$entry.key"))
    #end
  #else
    $util.qr($condition.put("expression", "$condition.expression AND attribute_exists(#id)"))
    $util.qr($condition.expressionNames.put("#id", "id"))
  #end
```

I believe the fix is to use branching logic to generate the condition for the create template in the same way it works with update.

**Comment by attilah** [comment]
@pagameba thanks for reporting the issue and it is an existing bug between `@model` and `@key`. One correction to your observation:

This mutation will not create duplicate items as the same `PutItem` request with same PK and SK will end up updating the same item:
```graphql
mutation C1 {
  createUserInvite(input: {
    organizationId: "O1"
    email:"E1"
    note: "N1"
  }) {
    organizationId
    email
    note
    createdAt
    updatedAt
  }
}
```

Executing the mutation times and then the following query will only return 1 item:
```graphql
query Q1 {
  listUserInvites {
    items {
      organizationId
      email
      note
      createdAt
      updatedAt
    }
  }
}
```

If we'd generate this expression, it would work as you expect:
```vtl
#set( $condition = {
  "expression": "attribute_not_exists(organizationId) and attribute_not_exists(email)"
} )
```

**Comment by pagameba** [comment]
Yes I noted that it does not actually create additional records, however it does update existing records at least that is what I observed. It also triggers an onCreate subscription event even though no new record is actually created

**Comment by attilah** [comment]
The `onCreate` fires because the create mutation - regardless of its functionality - was successfully invoked, if you have a NOOP type resolver the subscription can still fire, that is one of the use cases I utilized `None` data source before.

**Comment by pagameba** [comment]
Ok I get it. I also realized what the create mutation does under the hood is use `PutItem` which, and I did not realize this before, is this:


> The PutItem operation overwrites an item with the same key (if it exists). If you want to avoid this, use a condition expression. This allows the write to proceed only if the item in question does not already have the same key.

So it makes total sense if the generated condition is on a field that doesn't exist, it would update an existing record.

**Comment by attilah** [comment]
@pagameba I got back to this issue Today and when rebased my branch noticed some changes in the code, verified and this issue is already fixed, connected to a different bug report in PR: https://github.com/aws-amplify/amplify-cli/pull/7419 since 4.51.2 so if you try the latest CLI it will be fixed.

**Comment by pagameba** [comment]
Awesome, thanks for the update.  Can confirm that this does solve our problem, great work :)
