### ISSUE TITLE
How does the @connection work under the hood?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7272]
Hi, I'm having an error when referring a specific relationship field, so I decide take a look at the generated vtl resolvers.
But I can't understand how it works with the `@connection`..

For example:
```gql
type Project @model {
  id: ID!
  name: String
  teamID: ID!
  team: Team @connection(fields: ["teamID"])
}

type Team @model {
  id: ID!
  name: String!
}
```

it gets something like this:
```gql
type Query {
	getProject(id: String!): Project
}
```

the source of the `Project` is a DynamoDB table, but it doesn't contain a `team` attribute, so how could the vtl resolver return such an object with the `team` field set? I can't see any related code in the vtl template for `getProject`. anyone tell me why? and how does it work?

**Comment by attilah** [comment]
It works as any other GraphQL implementation with it comes to related data, your example is the '[Has one](https://docs.amplify.aws/cli/graphql-transformer/connection#has-one)' scenario from the docs.

I suggest to take a look at the `build` folder of your API where you can see the generated resolvers, also the AppSync console is a great help to better understand what is being generated/deployed for you.

The `Project.team` resolver is responsible to return the team data for a given project (as you query it through the `Project` type). In the AppSync console you can see the attached resolver to the `team` field.

I hope this answers your question, if you are just getting started with GraphQL and Amplify I would suggest to go through the various QuickStarts we have on the [docs site](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js).

**Comment by yaquawa** [comment]
Hi @attilah , thanks for the information!
Do you mean the resolver of `getProject` don't have to return a `Project` object? It is allowed to return only **partial** fields of the `Project`, and the lucked fields (`team` in this example) could be resolved from another resolver(`Project.team` in this example)?
