### ISSUE TITLE
Subscription won't return items with SortDirection for connected models

### ISSUE THREAD

**Issue by OukhouyaAyoub** [aws-amplify/amplify-cli#7274]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.49.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

Hello, I'm facing a bug where for the subscription the sort direction is not taken into account. The list and get queries are working fine, and we can specify sort direction for them.
Schema and subscription query to be found at the end.
The sortDirection added after imagesByDate is simply not taken into account.
> - Schema : 
type Camera @model
  {
  id: ID!
  cameraName: String!
  project: Project @connection(name: "ProjectCameras")
  imagesByDate: [Image] @connection(keyName: "byCameraByDate", fields: ["id"])
}

> - Subscription : 
subscription MySubscription {
  onUpdateCamera {
    id
    imagesByDate(sortDirection: DESC) {
      items {
        id
        datetime
      }
    }
  }
}
- Example of image id : cam001_2020-09-29T20:01:36.549835Z

### Expected behavior

The sort direction should have an effect on the sorting of the results.

### Reproduction steps

1- Have a one-to-many connection between two tables
2- subscription from the first table won't retrieve items from the second respecting the sort direction you specified

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Camera @model
  {
  id: ID!
  cameraName: String!
  project: Project @connection(name: "ProjectCameras")
  imagesByDate: [Image] @connection(keyName: "byCameraByDate", fields: ["id"])
}
type Image @model
  @key(name: "byCameraByDate", fields: ["cameraID", "datetime"])
{
  id: ID!
  cameraID: ID!
  datetime: AWSDateTime!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment]
@OukhouyaAyoub this is by design as you only see the parameters for the subscription because of the type reuse in the `GraphQL` schema, so on the client side you also can do type reuse.

Subscriptions are not doing an actual query, your update mutation's selection set is doing the query, subscriptions receive the same data that was returned as a result of the update mutation.

creating data with this mutation:
```graphql
mutation C {
  C1: createCamera(input: {
    id: "C1"
    cameraName: "Camera1"
  }) {
    id
  }
  
  I1: createImage(input:{
    id: "I1"
    cameraID: "C1"
    datetime: "2020-01-01T00:00:00.000Z"
  }) {
    id
  }
  
  I2: createImage(input:{
    id: "I2"
    cameraID: "C1"
    datetime: "2021-03-10T00:00:00.000Z"
  }) {
    id
  }
  
  I3: createImage(input:{
    id: "I3"
    cameraID: "C1"
    datetime: "2019-12-01T00:00:00.000Z"
  }) {
    id
  }
}
```

and then creating this subscription in another AppSync console window:
```graphql
subscription MySubscription {
  onUpdateCamera {
    cameraName
    id
    imagesByDate {
      items {
        cameraID
        datetime
      }
    }
  }
}
```

and executing this update mutation:
```graphql
mutation U {
  updateCamera(input: {
    id: "C1"
    cameraName: "Updated C1"
  }) {
    id
    cameraName
    imagesByDate(sortDirection: DESC) {
      items {
        cameraID
        datetime
      }
    }
  }
}
```

will get you the desired result and the same applies to filtering as well.

I hope this helped to shed some light on how it works behind the scenes.
