### ISSUE TITLE
An error occurred during the push operation - getaddrinfo EBUSY

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#7279]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v10.23.1

### Amplify CLI Version

4.50.2

### What operating system are you using?

AWS Linux (Cloud9)

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I have a valid schema - compiles fine and can also generate codegen models fine. The change I made was to add a lot of connections that didn't require creation of GSI ( like this -  brand: Brand @connection (fields: ["equipmentReferenceBrandId"]) ). It failed to upload to deployment bucket. I had statements like this in about 40 models (was moving to use @key rather than @connection).

Eventually I realized that if I made the change model by model and pushed model by model it worked fine - just meant I had to do 40 pushes to get my updates which was beyond mind numbing!!

Eventually I got it all pushed through - with exactly the same code deployed that originally failed when I tried to push all at once.

Now I try to add a new GSI as follows, and the same error happens - and this one I can't get around. Without this line the push succeeds - with this line it gets the error below...
  @key(name: "byDocumentURL", fields: ["documentURL"], queryField: "DocumentByURL") 

Error is shown below....
---------------------------------------------------------------------------------------------------------------------
Uploading files...✖ An error occurred when pushing the resources to the cloud

getaddrinfo EBUSY amplify-****-deployment.s3.amazonaws.com amplify-****.s3.amazonaws.com:443
An error occurred during the push operation: getaddrinfo EBUSY amplify-****-deployment.s3.amazonaws.com amplify-****-deployment.s3.amazonaws.com:443

### Expected behavior

Push succeeds

### Reproduction steps

As described above

### GraphQL schema(s)

<details>

```graphql
type Document
  @model
  @key(name: "byDocumentURL", fields: ["documentURL"], queryField: "DocumentByURL") 
  @searchable 
  @auth(rules: [ -- deleted for simplicity -- ])
{
  id: ID!
  description: String
  documentNumber: String
  documentDate: AWSDate
  documentURL: AWSURL
  M2MConnection: [M2MConnection] @connection (keyName: "byM2MConnectionDocumentId", fields: ["id"])
}  
```

</details>

### Additional information

I am migrating my database to DataStore so this new schema is moving from @connection to @key and has auto merge conflict resolution

**Comment by cjihrig** [comment]
I did a bit of testing.

- I created a GraphQL API with 45 models and pushed it successfully.
- Next, I drastically lowered the number of allowed file descriptors, modified the schema, and pushed again. With a very low ulimit, I got an EMFILE error while trying to process the project. This is expected behavior.
- Next, I tried with a larger ulimit. This time, I got an error during push (Uploading files...✖ An error occurred when pushing the resources to the cloud) like the OP. The specific error code was Inaccessible host, which is different from EBUSY reported by the OP. However, I'm using macOS, not Cloud9, so there is a good chance that this is the same error, just reported differently on different platforms.

I think there is a good chance that the issue is related to available file descriptors. If possible, you can try bumping the ulimit on your host (not sure if it is possible on Cloud9 or not). I think @attilah is correct when he said:

> which can be caused by our uploading code as we start too many promises/network requests

Relevant Node.js help issue: https://github.com/nodejs/help/issues/2390

**Comment by sacrampton** [comment]
Thanks @cjihrig @attilah 

I looked at the Node.js notes you provided and ran "ulimit -n" and it showed my Cloud9 instance had 4096.

I tried running "ulimit -n 8192" to double the number and ran into all manner of permission issues. I have no idea where I can change this. I logged a support ticket with AWS Support. Any ideas that anyone else has would be much appreciated.

**Comment by cjihrig** [comment]
> Any ideas that anyone else has would be much appreciated.

Are you able to try pushing the project from a different environment? It would be good to see if that unblocks you, and if the error you're hitting is a limitation in Cloud9 due to the size of your project.

**Comment by sacrampton** [comment]
@cjihrig @attilah - have a couple of things to report...

Tried creating a new Cloud9 environment and got identical results

Next set up a new environment on my Windows 10 PC and also got essentially the same result ("**Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. An error occurred during the push operation: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.**")

However, in setting up the new environment (amplify init) I got this error "**Could not initialize 'dev': Inaccessible host: `amplify-xxxx-deployment.s3.amazonaws.com'. This service may not be available in the `us-east-1' region.**". I tried amplify pull after this and it worked fine. Then I tried amplify push and got the above error.

Using the AWS CLI I could list the bucket (ie. aws s3 ls s3://amplify-xxxx-deployment).

**Comment by sacrampton** [comment]
@cjihrig @attilah - further info. My schema previously used connections like this
```
  operatingUnit: OperatingUnit @connection (name: "OperatingUnitAsset", sortField: "name")
```

But as I understand it, that way is deprecated in favour of @key - so I've changed all my GSI's to be like this

```
  @key(name: "byAssetOperatingUnitId", fields: ["assetOperatingUnitId"], queryField: "AssetOperatingUnit") 
```

And on the operatingUnit type I put the following statement and everything works fine
```
  asset: [Asset] @connection (keyName: "byAssetOperatingUnitId", fields: ["id"])
```
And then I can use amplify codegen models to create models for DataStore and everything works fine.

But where it starts to fall off the rails is when I do a connection from the child to the parent - like this on the asset model

```
  assetOperatingUnitId: ID!
  operatingUnit: OperatingUnit @connection (fields: ["assetOperatingUnitId"])
```
To get it to push I have to do these connections model by model and it works fine - if I try to push more than 1 model at a time it gives the getaddrinfo EBUSY error. I did 40+ individual pushes and eventually got the model pushed to the cloud.

However, when I generate the DataStore models with amplify codegen models I get this error.

(https://github.com/aws-amplify/amplify-js/issues/4695#issuecomment-834159472)
Models are not topologically sortable. Please verify your schema.


Whilst I'm sorting out that issue, I commented out 165 of these @connection (fields: [* lines in my schema and the push went through without any issue.

**Comment by sacrampton** [comment]
Hi @cjihrig @attilah 

Just following up the experience from trying this in Windows 10 and getting essentially the same result.
https://github.com/aws-amplify/amplify-cli/issues/7279#issuecomment-835918017

Any thoughts on this?

Thanks

Stephen
