### ISSUE TITLE
official docker image for amplify

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#7292]
### Is this related to another service?

local development

### Describe the feature you'd like to request

I would like to use an official Docker image with the Amplify CLI and related tooling installed.

Use Case:
I am using native modules in my lambda functions as my GraphQL API. I can run `amplify mock` locally, but this achieves a test using the native build with OSX architecture. I want to test builds locally that use the same architecture as the cloud uses, locally.

I made a Docker image from the [AWS Lambda base image for Nodejs](https://gallery.ecr.aws/lambda/nodejs). This allowed me to install dependencies and build my backend functions in the same Linux environment. Now I would like to use `amplify mock` from within the container, exporting the appropriate ports.

I see I need some version of Java to run `amplify mock` in my Docker container. Is there any advice on which distro?

What ports should I export when running my container so I can use `amplify mock` running in the container and interact with the web interface for GraphIQL as well as the graphql API  with a client running on my host?

### Describe the solution you'd like

I would like to use an official Docker image with the Amplify CLI and related tooling installed.

### Describe alternatives you've considered

Building a Docker image myself. See questions above.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by attilah** [comment]
Thanks for the feature request I had a similar thought during the week, my intention was the VS Code dev container support, which would also be a nice addition. /cc @renebrandel

**Comment by cyrfer** [comment]
Some progress notes.

I see this in the terminal when in the container:
```bash
$ amplify mock
Unable to find Java version >=1.8 <= 2.0 ||  >=8.0 on the path. Download link: https://amzn.to/2UUljp9
Failed to start API Mock endpoint Error: Command failed with ENOENT: java -version
spawnSync java ENOENT
```

The error message provides a [download link](https://amzn.to/2UUljp9) and informs me about a distro. I used [these instructions](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html#rpm-linux-install-instruct) to install Java in my Docker image.

For my build, I'm ignoring some files, not sure if that's ideal.
```
.git
**/dist
**/node_modules
**/package-lock.json
**/.DS_Store
**/.nyc_output
**/#current-cloud-backend
```

I run like this currently for experimentation
```bash
$ docker build -t amplify-builder .
# volume allows aws profiles from host
$ docker run --rm -v $HOME:/root -it amplify-builder bash
```

Here is some encouraging output:
```bash
$ amplify init
...
$ amplify mock
...
AppSync Mock endpoint is running at http://172.17.0.2:20002
```

So now I know which port to use, `20002`, updating my `run`:
```bash
$ docker run --rm -v $HOME:/root -p 20002:20002 -it amplify-builder bash
...
$ amplify init
...
$ amplify mock
...
AppSync Mock endpoint is running at http://172.17.0.2:20002
```

**Comment by cyrfer** [comment]
My `Dockerfile` is working for running `amplify mock` within a container, allowing me to locally test builds.

It would be nice if something like this was available to developers without any research.

```Dockerfile
FROM public.ecr.aws/lambda/nodejs:latest

# critical to prevent inherited behavior
ENTRYPOINT []

# needed for amplify mock
RUN rpm --import https://yum.corretto.aws/corretto.key
RUN curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo
RUN yum install -y java-11-amazon-corretto-devel
# RUN java -version


ARG AMPLIFY_CLI_VERSION=latest
RUN npm i -g @aws-amplify/cli@$AMPLIFY_CLI_VERSION


...COPY & RUN commands for my code
```
