### ISSUE TITLE
 amplify push - Resource is not in the state stackUpdateComplete

### ISSUE THREAD

**Issue by elankeeran** [aws-amplify/amplify-cli#7296]
Im trying to push the changes Im getting below error 

`CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Sun May 09 2021 12:25:32 GMT+0100 (British Summer Time)
CREATE_FAILED      LambdaExecutionRole AWS::IAM::Role Sun May 09 2021 12:25:33 GMT+0100 (British Summer Time) laundryappLambdaRole4bb80017-dev already exists in stack arn:aws:cloudformation:eu-west-2:344656295049:stack/amplify-laundry-app-dev-11402-functionuserSignUp-AM0YFHPH58MV/51277990-b017-11eb-8f8f-0648095267c8
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED amplify-laundry-app-dev-11402-functionuserSignUp-95DT48R1H4AR AWS::CloudFormation::Stack Sun May 09 2021 12:25:33 GMT+0100 (British Summer Time) The following resource(s) failed to create: [LambdaExecutionRole].
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS GraphQLSchema AWS::AppSync::GraphQLSchema Sun May 09 2021 12:25:38 GMT+0100 (British Summer Time)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED functionuserSignUp AWS::CloudFormation::Stack Sun May 09 2021 12:25:38 GMT+0100 (British Summer Time) Embedded stack arn:aws:cloudformation:eu-west-2:344656295049:stack/amplify-laundry-app-dev-11402-functionuserSignUp-95DT48R1H4AR/417bc1c0-b0b9-11eb-9a90-02ed3930dbce was not successfully created: The following resource(s) failed to create: [LambdaExecutionRole].
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS amplify-laundry-app-dev-11402-apilaundryapp-Z747P1967ZKV AWS::CloudFormation::Stack  Sun May 09 2021 12:25:39 GMT+0100 (British Summer Time) Initiated by parent stack
UPDATE_FAILED               GraphQLSchema                                            AWS::AppSync::GraphQLSchema Sun May 09 2021 12:25:39 GMT+0100 (British Summer Time) Resource update cancelled
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               apilaundryapp                 AWS::CloudFormation::Stack Sun May 09 2021 12:25:49 GMT+0100 (British Summer Time) Resource update cancelled`

Following resources failed

Resource Name: LambdaExecutionRole (AWS::IAM::Role)
Event Type: create
Reason: laundryappLambdaRole4bb80017-dev already exists in stack arn:aws:cloudformation:eu-west-2:344656295049:stack/amplify-laundry-app-dev-11402-functionuserSignUp-AM0YFHPH58MV/51277990-b017-11eb-8f8f-0648095267c8

Resource Name: crkl4qqbsbcfhb7aalisdasnmeGraphQLSchema (AWS::AppSync::GraphQLSchema)
Event Type: update
Reason: Resource update cancelled

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

**Comment by siegerts** [comment]
Hi :wave: - thanks for raising this!  To get a bit more context, do you mind porting this to the formatted [bug report]([bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) 

This will help the team determine the best approach to take. Thanks.
