### ISSUE TITLE
Transformer order

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7297]
### Is this related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

I'm creating a custom transformer which should be applied before `@auth`.
Currently, there is no way to specify "***before***" or "***after***" one or more transformers.
I wish we had a mechanism to solve such a problem.

**Comment by siegerts** [comment]
Hi @yaquawa :wave: !  - Can you please reopen with the [feature request form](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml), leaving the required fields.  

Answering these questions helps other community members and users who may come across this add additional use cases, upvote (with [GitHub reactions feature](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)), or provide additional context that can help guide prioritization and development.
