### ISSUE TITLE
Add function support in amplify-headless-interface

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-cli#7307]
### Is this related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

Now its not possible to execute `amplify add function --headless` function interface is missing:
https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-headless-interface/src/interface

### Describe the solution you'd like

add function interface and headless function and layers add/update

### Describe alternatives you've considered
`amplify add function --headless`
sytolk$ `amplify add function --headless`
Headless mode is not implemented for amplify-category-function

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Closing in favor of tracking existing item #4294
