### ISSUE TITLE
update, remove function DX enhancements

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#7308]
### Is this related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

Enhance the `update function` and `remove function` walkthrough with some additional checks and auto-selection of options.

### Describe the solution you'd like

When running `update function`, CLI shows a prompt to select a service: Function or Layers.

CLI could check project resources to see if there are Functions and/or Layers exists or not.

1. if both exists keep the existing functionality
2. if only one of them exists, auto select that service and skip to the resources selection directly
3. if none of them exist, then show the standard "No function resources to update. Use "amplify add function" to create a function or layer."

The same treatment could be applied to `remove function` as well.

Some E2E tests will probably require updates as well where `add function`, `update function` or `remove function`.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jhockett** [comment]
This issue was addressed in the latest release, 5.2.0.
