### ISSUE TITLE
Push fails after upgrade from 4.49.0 to 4.50.2

### ISSUE THREAD

**Issue by hbj** [aws-amplify/amplify-cli#7310]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.18.4

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

After upgrading the CLI from 4.49.0 to 4.50.2, if I update a resource and push, the push fails with the following error message:

```
CREATE_FAILED APIGatewayAuthStack AWS::CloudFormation::Stack Tue May 11 2021 12:21:55 GMT+0100 (Central European Standard Time) Template format error: At least one Resources member must be defined.
```

I noticed that a new file `amplify/backend/api/APIGatewayAuthStack.json` with the following content has been created:

```json
{
  "Description": "API Gateway policy stack created using Amplify CLI",
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "authRoleName": {
      "Type": "String"
    },
    "unauthRoleName": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    },
    "standupSlackBot": {
      "Type": "String"
    }
  },
  "Conditions": {
    "ShouldNotCreateEnvResources": {
      "Fn::Equals": [
        {
          "Ref": "env"
        },
        "NONE"
      ]
    }
  }
}
```

If I go back to 4.49.0 and delete that file, then the push works fine.

### Expected behavior

Push works.

### Reproduction steps

Reproduction might depend on the services you have in your stack. In my case I have a REST API, a GraphQL API, a user pool auth, a couple of functions, 2 DB storages a custom event bus and a custom event bridge.

1. upgrade the Amplify CLI for a version < 4.50 to 4.50.2
2. run `amplify push --force` as described in the documentation (this should work)
3. update a resource, e.g. a function
4. run `amplify push` (this should fail)

**Comment by cjihrig** [comment]
Thank you for reporting this. Can you please share your REST API's `api-params.json` file via email at amplify-cli@amazon.com.

**Comment by rinosamakanata** [comment]
I'm experiencing the same problem with this bug.

**Comment by halilduygulu** [comment]
I have S3 timeout errors since this morning 

```
connect ETIMEDOUT 52.218.85.64:443
An error occurred during the push operation: connect ETIMEDOUT 52.218.85.64:443
```

**Comment by hbj** [comment]
> Thank you for reporting this. Can you please share your REST API's `api-params.json` file via email at [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com).

Done.
