### ISSUE TITLE
Appsync cache settings being overwritten

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-cli#7314]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Appsync caching

**Amplify CLI Version** 
4.32.1

**What AWS Services are you utilizing?**
Amplify, appsync

**Provide additional details e.g. code snippets**
I set some cache configs on CustomResources.json, it works. The problem is when I need to set caching config to default queries, I do that using the aws console on appsync but every time I deploy a new version the cache configuration are overwritten on default queries. How can I set cache config for default queries?

**Comment by ammarkarachi** [comment]
Hi! Can you give us more information on how you are overriding the caching values? on every invocation of `amplify push` the CLI does overwrite the resolvers and templates

**Comment by zzBrunoBrito** [comment]
When I set cache configs on custom queries I do this using the "CustomResources.json" file, It works fine.
Example: 

```
....
"CachingConfig": {
          "Ttl": 60,
          "CachingKeys": [
            "$context.arguments.searchTerm"
          ]
}
...
```

But when I need to set cache config on default queries I use the appsync console and do like this:

![image](https://user-images.githubusercontent.com/17935753/118025994-b7e86a00-b336-11eb-9e50-d20561af989b.png)

The problem is whenever I do a new `amplify push`, the cache is disabled on these auto generated queries. How can I enable cache for the default(auto generated) queries without lose these configs every time I do a new `amplify push`? I'm using the per-resolver caching option because I only need caching on specific queries.

**Comment by zzBrunoBrito** [comment]
My question is basically this: Is possible to set caching configs on default queries using amplify?

**Comment by ammarkarachi** [comment]
Currently we don't have an easy way to override default configurations that CLI provides but we are looking into making this possible. I will mark this as an enhancement for our team include into our use cases.

**Comment by zzBrunoBrito** [comment]
Ok understood, but is possible to do this(even if its not easy) using the CustomResources.json file? I would love to find some examples on how to do this. Its kinda frustrating that on every new push I have to set the cache configs again.

**Comment by ammarkarachi** [comment]
The CustomResources.json file is basically a way to provide resources to your existing stack. In your CICD you could run a script that updates the Resolvers after deploy to set the Cache Settings.

**Comment by SwaySway** [comment]
Closing this issue in favor of https://github.com/aws-amplify/amplify-cli/issues/2803.
