### ISSUE TITLE
UPDATE_FAILED error: api [unauthRoleName, authRoleName] do not exist in the template

### ISSUE THREAD

**Issue by sina-developer** [aws-amplify/amplify-cli#7318]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

 npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.16.0

### Amplify CLI Version

4.50.2

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

we had a project which was build on Amplify Version 4.49.0 and that was working just fine
after releasing Amplify version 4.50.2 our project gives us an error on "Amplify push" Command and also when ever we wants to deploy project using Admin UI, same error prevents deployment
The Error Is :

UPDATE_FAILED error: api [unauthRoleName, authRoleName] do not exist in the template

i had mentioned this error on a older issue which was created at 2017, i think.

and if you want to preproduce this error

follow these steps:

1. install amplify v4.49.0
2. add graphQL api with some roles and groups
3. add storage (s3 bucket)
4. open admin UI
5. try to enable Data Model Editor - Deploy using Admin UI
6. it will not deploy this way!

OK!
i know you will tell me to update Amplify cli
but when ever i try to push using v4.49.0 it works!
otherwise whenever i try to push using v4.50.2 it will give me the error 
also i'm not able to deploy by admin ui itself
i only can push using v4.49.0

i will provide an image of error log from v4.50.2 

![image_2021_05_12T12_14_10_588Z](https://user-images.githubusercontent.com/26477180/118017852-517e3e80-b36c-11eb-8182-d2de956ba71d.png)

it is the same error on admin UI too

### Expected behavior

admin UI deployment should work!
amplify push should work on version 4.50.2

### Reproduction steps

1. install amplify v4.49.0
2. add graphQL api with some roles and groups
3. add storage (s3 bucket)
4. open admin UI
5. try to enable Data Model Editor - Deploy using Admin UI
6. it will not deploy this way!

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

thank you guys
I know you are doing your best

**Comment by cjihrig** [comment]
Thanks for reporting this @sina-developer. I have a few questions:

1. Do you have any REST APIs in your project, or only a GraphQL API?
2. Based on the screenshot you've shared, it appears that you're running into a different error. The issue title mentions "[unauthRoleName, authRoleName] do not exist in the template" but the screenshot states "[unauthRoleName, authRoleName] must have values". The first implies setting parameters that do not exist, while the second implies that the parameters exist but do not have values.
3. Would you mind zipping up your project and sharing it via email to amplify-cli@amazon.com. I'd be happy to take a look at it for you instead of going back and forth on GitHub.

**Comment by sina-developer** [comment]
> Thanks for reporting this @sina-developer. I have a few questions:
> 
> 1. Do you have any REST APIs in your project, or only a GraphQL API?
> 2. Based on the screenshot you've shared, it appears that you're running into a different error. The issue title mentions "[unauthRoleName, authRoleName] do not exist in the template" but the screenshot states "[unauthRoleName, authRoleName] must have values". The first implies setting parameters that do not exist, while the second implies that the parameters exist but do not have values.
> 3. Would you mind zipping up your project and sharing it via email to [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com). I'd be happy to take a look at it for you instead of going back and forth on GitHub.

hello

1.yes, i have a REST API endpoint which is connected to an lambda function
2.error which mentioned on title of this issue is grabbed from Admin UI report, i tried using amplify push command on v 4.50.2 and it fails, when i took a look for cli logs, i just see this error (error on image)
3.I need to talk with project owner about this, if it is ok, i'll send the source code

this error occurs after amplify cli v4.50.2
i think it is related to new version
btw,it may not!

**Comment by cjihrig** [comment]
With v4.50.2 of the CLI, you can update your REST API:

1. The `parameters.json` file no longer needs to reference `authRole` or `unauthRole`. Unless you've made any customizations by hand, this file will likely become just an empty object (`{}`).
2. Similarly, in the CloudFormation template, you should not need the `authRole` or `unauthRole` parameters. There shouldn't be any IAM policies in the file anymore either. All of those resources should now be handled in the `APIGatewayAuthStack.json` template.

**Comment by sina-developer** [comment]
> With v4.50.2 of the CLI, you can update your REST API:
> 
> 1. The `parameters.json` file no longer needs to reference `authRole` or `unauthRole`. Unless you've made any customizations by hand, this file will likely become just an empty object (`{}`).
> 2. Similarly, in the CloudFormation template, you should not need the `authRole` or `unauthRole` parameters. There shouldn't be any IAM policies in the file anymore either. All of those resources should now be handled in the `APIGatewayAuthStack.json` template.

about REST API
first i created one with authorized and unauthorized access level
and after that on API Gateway i set Auth to NONE
is it the problem?

**Comment by cjihrig** [comment]
I don't think that is the problem. I think the problem is related to the files I referenced above, but I can't be 100% certain without seeing the project.

**Comment by sina-developer** [comment]
hi
sorry for delay on response

i just notice there is a empty object on backend-conf.json
which is  exact same as one of my deleted functions 
i used "amplify remove function"
and it seems when i pull my project on a new directory, it includes this empty function object
so i removed that and now it works perfectly

function was attached to auth postConfirmation trigger before

thanks for your helps <3
