### ISSUE TITLE
Support separate client ids for android/ iOS in Auth - Cognito UserPools

### ISSUE THREAD

**Issue by rohandubal** [aws-amplify/amplify-cli#732]
**Is your feature request related to a problem? Please describe.**
Currently Android/ iOS platforms share same clientId which means the users of both apps are considered to have similar environments. There can be cases where different auth providers are supported for different platforms. This currently won't be possible if clientIds are shared.

**Describe the solution you'd like**
Separate clientIds for android / iOS to allow distinct features for both platforms.

**Describe alternatives you've considered**
n/a

**Comment by kaustavghosh06** [comment]
Closing due to lack of further response and activity.
