### ISSUE TITLE
Amplify Push fails - Limit for stack has been exceeded

### ISSUE THREAD

**Issue by treystudio3a** [aws-amplify/amplify-cli#7321]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.1

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I have not added any new schemas to my project, but now when I try to push changes I get 

AWS::CloudFormation::Stack Wed May 12 2021 15:52:39 GMT-0500 (Central Daylight Time) Limit for stack has been exceeded

It appears if I get over about 15 schemas I get this error.  I can not find any particular hard stop, as I remove and add schemas sometimes I can get to 19, but seems to consistently fail over 20.  I used to have many more (25+) without any issues, but now it's consistently giving me this error.  I end up with all kinds of other areas, but this "Limit for stack has been exceeded" always to be the first error that occurs in the push.

### Expected behavior

Used to deploy successfully.

### Reproduction steps

1. add 15-20+ schemas
2. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
Have you hit the limit on the number of CloudFormation stacks you can have in your account (200 I believe)? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

**Comment by treystudio3a** [comment]
That's what I'm wondering but I don't have any control over that right?  If this limit is occurring its due to the Amplify Push script correct?  Or is there a way to upgrade my AWS plan to increase limits?

**Comment by treystudio3a** [comment]
What I don't understand is this used to work, and now it's not, so I'm trying to figure out what has changed?

**Comment by cjihrig** [comment]
You can check in the CloudFormation web console to see all of your stacks. Based on your description of your Amplify project's size, I wouldn't expect it to exhaust the entire limit, but perhaps you have other stacks as well.

**Comment by treystudio3a** [comment]
Thank you very much I see now where the stacks are left over from older amplify test projects.  deleting those now I will report back here if that works

**Comment by treystudio3a** [comment]
That was the problem.  Thank you very much @cjihrig !
