### ISSUE TITLE
Mock server not overriding endpoint under "api/plugins/awsAPIPlugin"

### ISSUE THREAD

**Issue by difelice** [aws-amplify/amplify-cli#7330]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.2.1

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

util-mock

### Amplify Commands

mock [api]

### Describe the bug

When running `amplify mock`, the Flutter app is fetching data from the cloud API instead of the local mocked API.

### Expected behavior

I expect app fetching data from the mocked API server and not the Cloud instance.

### Reproduction steps

1. Start mocked API server with command `amplify mock`
2. Run Flutter app fetching data from server.
3. The data is the one stored in Cloud and not in mocked server.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I noticed that when server runs, the configuration file `myapp/lib/amplifyconfiguration.dart` is overriding endpoint URL and API Key under `auth/plugins/awsCognitoAuthPlugin/AppSync/Default` but same attributes under `api/plugins/awsAPIPlugin/myapp/` are unchanging and they are still the cloud ones.

This is the comparison diff when mock server runs:

```diff
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "REDACTED",
                    "region": "us-east-1"
                },
                "pinpointTargeting": {
                    "region": "us-east-1"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:REDACTED",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-2_UP4gigTZE",
                        "AppClientId": "REDACTED",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "REDACTED",
                        "Region": "us-east-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-east-1"
                    }
                },
                "AppSync": {
                    "Default": {
-                       "ApiUrl": "https://REDACTED.appsync-api.us-east-2.amazonaws.com/graphql",
+                       "ApiUrl": "http://192.168.1.156:20002/graphql",
                        "Region": "us-east-2",
                        "AuthMode": "API_KEY",
-                       "ApiKey": "REDACTED",
+                       "ApiKey": "da2-fakeApiId123456",
                        "ClientDatabasePrefix": "myapp_API_KEY",
+                       "DangerouslyConnectToHTTPEndpointForTesting": true
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "myapp": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://REDACTED.appsync-api.us-east-2.amazonaws.com/graphql",
                    "region": "us-east-2",
                    "authorizationType": "API_KEY",
                    "apiKey": "REDACTED"
                }
            }
        }
    }
}
}''';

**Comment by adifelice-godaddy** [comment]
After digging in I realize my cocoa pods we outdated, after upgrading this issue disappeared. I think we can close this for now. Thank you all!
