### ISSUE TITLE
Can you use the output of a nested GraphQL API stack as a parameter to a custom resource?

### ISSUE THREAD

**Issue by kylevoyto** [aws-amplify/amplify-cli#7331]
**Which Category is your question related to?**

`Api` (GraphQL)

**Amplify CLI Version** 

`4.50.2`

**What AWS Services are you utilizing?**

`DynamoDB`, `AppSync`, `CloudFormation`

**Provide additional details e.g. code snippets**

I created a custom resource in an Amplify project following the [Advanced workflows - Add a custom AWS resource](https://docs.amplify.aws/cli/usage/customcf) guide.

I want to reference the name of a DynamoDB table created through the Amplify GraphQL API backend in my custom resource.

I tracked down the name of the CloudFormation output for the DynamoDB table name in `./amplify/backend/api/myapi/build/stacks/My.json`.

```json
"Outputs": {
  "GetAttMyTableName": {
    "Description": "Your DynamoDB table name.",
    "Value": {
      "Ref": "MyTable"
    },
    "Export": {
      "Name": {
        "Fn::Join": [
          ":",
          [
            {
              "Ref": "AppSyncApiId"
            },
            "GetAtt",
            "UserSettingsTable",
            "Name"
          ]
        ]
      }
    }
  }
}
```

Using the instructions for [referencing existing parameters](https://docs.amplify.aws/cli/usage/customcf#n3-optional-reference-existing-parameters), I modified `backend-config.json` so that the custom resource depends on the GraphQL API.

```json
  "custom-resources": {
    "my-custom-resource": {
      "service": "my-backend-resource",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "myapi",
          "attributes": [
            "GetAttMyTableName"
          ]
        }
      ]
    }
  },
```

I know I'm missing the `"Ref": "AppSyncApiId"` prefix to the `GetAttMyTableName`, but I do not know how to add the prefix. I think this is problem number 1 of 2, so I will continue with my attempt below.

I added an input parameter for the table name in my custom resource template

```json
  // The format out here is `<category><resource-name><attribute-name>`
  // we have defined all of these in the `backend-config.json` file above
  "Parameters": {
    "apimyapiGetAttUserMyTableName": {
      "Type": "String"
    }
  },
```

and modified the `parameters.json` to include the parameter.

```json
{
  "apimyapiGetAttMyTableName": {
    "Fn::GetAtt": [
      "apimyapi",
      "Outputs.GetAttMyTableName"
    ]
  }
}
```

But I get the following error when I try to `amplify push`.

```json
CREATE_FAILED  <resource>  AWS::CloudFormation::Stack Thu May 13 2021 20:20:15 GMT-0400 (Eastern Daylight Time) Output 'GetAttMyTableName' not found in stack 'arn:aws:cloudformation:<region>:<account>:stack/amplify-<project>-dev-<id>-apimyapi-<id>/<id>'
```

I think the problem is that the DynamoDB table name is output by a nested stack under the API stack. I do not know how to configure the custom resource to reference an output from a nested stack.

```
(stack)    amplify-<project>-dev-<id>-apimyapi-<id>
(nested)      |-amplify-<project>-dev-<id>-apimyapi-<id>-My-<id>
```

Is it possible to reference an output from a nested GraphQL API stack in Amplify?

**Comment by akshbhu** [comment]
Hi @kylevoyto 

you are almost on right path. Instead of adding  ```GetAttMyTableName``` , You can replace backend Config to get ```AppsyncApiId``` . Then you can use ```ImportValue``` to access the table in the CFN.

You can add this section where you want to import this exported value from My.json
```
    {
      "Fn::ImportValue": {
        "Fn::Sub": "${AppSyncApiId}:GetAtt:TodoTable:Name"
      }
    }
```

Also Add a parameter in the stack ```AppsyncApiId``` where you are importing this table Name

Let me know if this works for you?

**Comment by kylevoyto** [comment]
@akshbhu thank you for the help.

I hit the following error when I tried to import the value with a substitution including the API Id:

```
Template error: the attribute in Fn::ImportValue must not depend on any resources, imported values, or Fn::GetAZs
```

I can provide extra information if you think the error may be a mistake in my configuration. I am curious about the solution.

However, I think I can achieve my goals with access to the GraphQL API instead of connecting directly to the DynamoDB table. (I can successfully to import the location of the API.)

**Comment by akshbhu** [comment]
Hi @kylevoyto 

Glad to know it worked. For importing tableName , Can you share the snippet of how are you importing tableName in custom resource?

**Comment by kylevoyto** [comment]
@akshbhu I did not successfully import the tableName. I am using the GraphQL API endpoint instead, so I could directly follow the [Advanced workflows docs](https://docs.amplify.aws/cli/usage/customcf).

backend-config.json

```json
  "custom-resources": {
    "my-custom-resource": {
      "service": "my-backend-resource",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "myapi",
          "attributes": [
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    }
  },
```

parameters.json

```json
{
  "apimyapiGetAttMyTableName": {
    "Fn::GetAtt": [
      "apimyapi",
      "Outputs.GraphQLAPIEndpointOutput"
    ]
  }
}
```

template.json

```json
  "Parameters": {
    "apimyapiGraphQLAPIEndpointOutput": {
      "Type": "String"
    }
  },
```
