### ISSUE TITLE
wrong template for Cognito pre-signup triggers

### ISSUE THREAD

**Issue by DeniferSantiago** [aws-amplify/amplify-cli#7339]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.1.0

### Amplify CLI Version

4.51.0

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

I created a lambda function that runs in cognito triggers (pre-signup) then I ran `amplify push` and everything worked fine.

Then I created another function that has nothing to do with the previous scenario and when running amplify push I got an error that has to do with the auth module: 
```
UPDATE_FAILED               authanynameauth              AWS::CloudFormation::Stack Fri May
(hora estándar del Atlántico) Parameters: [functionanynameauthPreSignupName, functionanyname ist in the template
```

### Expected behavior

run `amplify push` and save the new function without getting any errors

### Reproduction steps

`amplify update auth`
select: `Walkthrough all the auth configurations`
add a trigger in pre-signup
edit the code of the function created
upload changes with: `amplify push`
add a new function with the Hello Word template: `amplify add function`
edit the code of the function created
upload changes with: `amplify push` Error!

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
UPDATE_FAILED               authanynameauth              AWS::CloudFormation::Stack Fri May
(hora estándar del Atlántico) Parameters: [functionanynameauthPreSignupName, functionanyname ist in the template


```

</details>

**Comment by DeniferSantiago** [comment]
I also see that the error seems in the end is not correct but I could understand it.

I went to the .yml template of the auth module and found:
```
UserPoolPreSignupLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: UserPool
    Properties:
      Action: "lambda:invokeFunction"
      Principal: "cognito-idp.amazonaws.com"
      FunctionName: !Ref functionanynameauthPreSignupName
      SourceArn: !GetAtt UserPool.Arn
```
so I deduced that the error was referring to not finding the value in `!Ref functionanynameauthPreSignupName`
so I went to the parameters.json file of the auth module and added a new property with the name of the function to be executed in the pre-signup:
```json
{
  "functionanynameauthPreSignupName": "anynameauthPreSignup"
}
```
Then I ran `amplify push` and it worked, I'm not sure of the quality of this solution and if amplify really needed to add that information in the parameters, that's why I'll leave the problem open

**Comment by ammarkarachi** [comment]
@DeniferSantiago Was the amplify project created with an earlier version?

**Comment by DeniferSantiago** [comment]
Yes, but I don't know which one exactly

**Comment by DeniferSantiago** [comment]
as I no longer used cognito-triggers I removed all reference to them in the .yml and .json file

**Comment by ammarkarachi** [comment]
Can you try it with the latest version?

**Comment by DeniferSantiago** [comment]
@ammarkarachi  The project was created in a previous version but is currently updated to the latest version of amplify

**Comment by ammarkarachi** [comment]
@DeniferSantiago Can you send us your amplify folder to amplify-cli@amazon.com? Also specify the issue number in the subject.

**Comment by DeniferSantiago** [comment]
I am no longer using lambda triggers due to: https://github.com/aws-amplify/amplify-js/issues/5522
