### ISSUE TITLE
some problems about GraphQL And DataStore CRUD operations 

### ISSUE THREAD

**Issue by sina-developer** [aws-amplify/amplify-cli#7342]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

GraphQL Api

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.50.2

**What AWS Services are you utilizing?**

Auth,Api,Function,Storage

**Question :**

I have a question about graphql queries on react js app

when i was using AppSync to test some data, i just noticed there is a column called _version which is related to Conflict Resolution
on the react side i'm using API.graphQL funciton to CRUD operations
but that _version column makes things harder
so :
1- can i turn off this Conflict Resolution?
2- how should handle this versioning stuff?
3- should i only use AppSync for Managing Data ?
4- when i remove data using API.graphQL it is still there! what should i do?
also 
i tried DataStore too
and that is offline first library but in my application i need to be fully online
i dont want to save data temporarily on client-side and then upload when it gets online
also there is no way to log the result to detect that a record has been saved locally or online!

so Datastore questions:
1- how should i get the result log of an operation?
2- how to turn off offline-first ability?

**Comment by SwaySway** [comment]
Hello @sina-developer 
Conflict Resolution is a AppSync Feature which is used as a part of DataStore. For info on what the fields (such as `_version`) mean refer to the AppSync dos below.
You can check if you have this enabled if there is a `ResolverConfig` in your `transform.conf.json`. If you have this enabled it is best to use the DataStore library as the deleting a field will leave it with a timestamp when the said record will expire. (mentioned in the appsync docs). If you would not like to use datastore you can disable it when running `amplify update api`.

If you have any issues/questions using DataStore from the library. I'd recommend opening a question/discussion thread with the amplify library you are using. 


AppSync Conflict Resolution Docs: https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html

**Comment by sina-developer** [comment]
thank you for your response

amplify update api worked!
