### ISSUE TITLE
Unable to Push - Get Message: UPDATE_FAILED ... Parameters: [authProviders] must have values

### ISSUE THREAD

**Issue by tim-weisbrod** [aws-amplify/amplify-cli#7343]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d30fzi40a51bhx

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I made a few minor changes to a GraphQL schema we have pushed many times in the past, and ran amplify push.  That resulted in the failure shown below, followed by a cloud formation rollback.

UPDATE_FAILED               authvepwebae8b813dae8b813d AWS::CloudFormation::Stack Sat May 15 2021 14:02:43 GMT-0400 (Eastern Daylight Time) Parameters: [authProviders] must have values

Not sure if this is related, but I had just upgraded the amplify CLI to version 4.51.0 before I saw this error the first time.

Also, in case it's related somehow - One of my colleagues said he attempted to push an auth only change in the last several days as well, but it failed.  I don't have the exact error message, but he said he didn't check in anything related to that.

Full console output is included in additional details.  Thanks for your help!

### Expected behavior

Push to complete, updating the GraphQL resources in App Sync

### Reproduction steps

1. run npm i -g @aws-amplify/cli to get version 4.51.0 (not sure if this is related), but it is a step I took
2. run amplify push
3. confirm push, and say yes to all prompts to re-generare and over-write

### Build Settings

```yaml
amplify\backend\api\vepapi\build\parameters.json

{
    "CreateAPIKey": 1,
    "AppSyncApiName": "vepapi",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": false,
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Outputs.UserPoolId"
        ]
    },
    "S3DeploymentBucket": "amplify-xxxxxxxxxxxxxxxxxxxxxx",
    "S3DeploymentRootKey": "amplify-appsync-files/xxxxxxxxxxxxxxxxxxxxx"
}
```

### Additional information

Console Output

> amplify push
√ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name          | Operation | Provider plugin   |
| -------- | ---------------------- | --------- | ----------------- |
| Api      | vepapi                 | Update    | awscloudformation |
| Auth     | userPoolGroups         | No Change | awscloudformation |
| Auth     | vepwebae8b813dae8b813d | No Change | awscloudformation |
? Are you sure you want to continue? Yes

GraphQL schema compiled successfully.

```
Edit your schema at C:\...\schema.graphql or place .graphql files in a directory at C:\...\schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes
\ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-vepweb-dev-195208 AWS::CloudFormation::Stack Sat May 15 2021 14:02:37 GMT-0400 (Eastern Daylight Time) User Initiated
| Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          authuserPoolGroups         AWS::CloudFormation::Stack Sat May 15 2021 14:02:43 GMT-0400 (Eastern Daylight Time)

UPDATE_IN_PROGRESS          authvepwebae8b813dae8b813d AWS::CloudFormation::Stack Sat May 15 2021 14:02:43 GMT-0400 (Eastern Daylight Time)

UPDATE_COMPLETE             authuserPoolGroups         AWS::CloudFormation::Stack Sat May 15 2021 14:02:43 GMT-0400 (Eastern Daylight Time)

UPDATE_FAILED               authvepwebae8b813dae8b813d AWS::CloudFormation::Stack Sat May 15 2021 14:02:43 GMT-0400 (Eastern Daylight Time) Parameters: [authProviders] must have values

UPDATE_ROLLBACK_IN_PROGRESS amplify-vepweb-dev-195208  AWS::CloudFormation::Stack Sat May 15 2021 14:02:44 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to update: [authvepwebae8b813dae8b813d].
\ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE authvepwebae8b813dae8b813d AWS::CloudFormation::Stack Sat May 15 2021 14:03:02 GMT-0400 (Eastern Daylight Time)
/ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack


UPDATE_IN_PROGRESS                           authuserPoolGroups         AWS::CloudFormation::Stack Sat May 15 2021 14:03:03 GMT-0400 (Eastern Daylight Time) 
UPDATE_COMPLETE                              authuserPoolGroups         AWS::CloudFormation::Stack Sat May 15 2021 14:03:03 GMT-0400 (Eastern Daylight Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-vepweb-dev-195208  AWS::CloudFormation::Stack Sat May 15 2021 14:03:04 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE                              authvepwebae8b813dae8b813d AWS::CloudFormation::Stack Sat May 15 2021 14:03:06 GMT-0400 (Eastern Daylight Time)
UPDATE_COMPLETE                              authuserPoolGroups         AWS::CloudFormation::Stack Sat May 15 2021 14:03:06 GMT-0400 (Eastern Daylight Time)
UPDATE_ROLLBACK_COMPLETE                     amplify-vepweb-dev-195208  AWS::CloudFormation::Stack Sat May 15 2021 14:03:06 GMT-0400 (Eastern Daylight Time)


Following resources failed

× An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

**Comment by myfairshare** [comment]
I also had issues, just updated to 4.51.0 and its resolved in my case.

**Comment by ammarkarachi** [comment]
@tim-weisbrod Do you mind sharing the schema?

**Comment by tim-weisbrod** [comment]
Sorry for my delayed response.

Yes, am happy to share my schema privately if you want to reach out to me.

Thanks,

Tim
