### ISSUE TITLE
Can't deploy a react web app in AWS Amplify (Dynamic web app)

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-cli#7347]
Dear AWS support team,

I have a problem to deploy a REACT web application connected with  with **Backend environments** using DynamoDB, GraphQL API, Cognito, Lambda Function.

**Problems I got**
1. Deployment steps from AWS Amplify,
1.1  It blocked in **Build** step : after a search I found that I need to change **Amplify CLI** version from **lastest** to **3.3.27**, from Build settings>  Build image settings> Version
1.2.  It's block in **Deploy**:  I get this message
```
2021-05-17T22:06:42 [INFO]: Starting Deployment
2021-05-17T22:06:42 [ERROR]: Failed to deploy
```

2. Deployment with amplify console
in this step I made these cmd
amplify add hosting > 
Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)  >
amplify publish > 
I got this error
```

 Zipping artifacts completed.
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: Branch dev not found.
```

### My question 
what should I do ? Especially, there is no message based on it

Thank you in advance

**Comment by ammarkarachi** [comment]
@MedNabilEssefaihi is the version you are using 3.3.27?

**Comment by MedNabilEssefaihi** [comment]
Hello Mr @ammarkarachi 

this is my json file 

> 
> {
>   "name": "design",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@aws-amplify/ui-react": "^1.0.7",
>     "@material-ui/core": "^4.11.3",
>     "@material-ui/icons": "^4.11.2",
>     "@material-ui/lab": "*",
>     "@testing-library/jest-dom": "^5.11.4",
>     "@testing-library/react": "^11.1.0",
>     "@testing-library/user-event": "^12.1.10",
>     "aws-amplify": "^3.4.3",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "react-router-dom": "^5.2.0",
>     "react-scripts": "4.0.3",
>     "validation-latitude-longitude": "^1.1.3",
>     "validator": "^13.6.0",
>     "web-vitals": "^1.0.1"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "react-app/jest"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> }
>

**Comment by ammarkarachi** [comment]
Is there a reason why you are unable to use the latest version?

**Comment by MedNabilEssefaihi** [comment]
Do you mean  "aws-amplify": "^3.4.3", ? if yes. I tried to updated using npm i aws-amplify but it did't work, also i try npm i aws-amplify@latest didn't work too

**Comment by ammarkarachi** [comment]
@MedNabilEssefaihi The library you are referring to is the amplify js client library [npm link.](https://www.npmjs.com/package/aws-amplify)  You are likely looking for the Amplify CLI library which can be install using `npm i -g @aws-amplify/cli@latest`. The CLI library is the framework that helps you add the categories and deploy the resources

**Comment by MedNabilEssefaihi** [comment]
I updated the CLI and aws-amplify 
but it still the same problem

**Comment by ammarkarachi** [comment]
The console is looking for the dev branch and it looks like it does not exist

**Comment by ammarkarachi** [comment]
Closing this issue let me know if you need anything else

**Comment by MedNabilEssefaihi** [comment]
@ammarkarachi Thank you
I made it, the solution is I needed to update my npm version
