### ISSUE TITLE
Custom Resource Gets Deleted From DependsOn for Other Resources

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#7349]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.20.1

### Amplify CLI Version

4.51.1

### What operating system are you using?

Mac

### Amplify Categories

function, Not applicable

### Amplify Commands

env, update

### Describe the bug

We have some custom CF resources within amplify (SNS/SQS) which have folder structures as follows:
```
amplify/backend/sns/<topic>
          - <topic>-awscloudformation-template.json
          - parameters.json
```
We then have lambda functions that depend on these resources by adding them into the dependsOn section of the lambda function

```
"lambdaFunction": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "sns",
          "resourceName": "<topic>",
          "attributes": [
            "Arn"
          ]
        }
    }
```

When we set this up, it works totally fine after we do amplify env checkout <env-name>. 

The bug is when we use the amplify cli to update the lambda function resource dependencies, it will always delete the custom resources. 

Can you add some sort of check so that it wont delete any resources that are part of a category which are not under your supported/predefined list.

### Expected behavior

When you update the category resource's dependencies, do not delete custom resources that are within the dependency list.

### Reproduction steps

Environment setup as above

1. amplify update function
2. select function
3. select to update resources dependant on
4. make some sort of update
5. look at backend config file and see custom resources are no longer in the list within dependsOn

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@gakinson Thanks for the issue currently the parameters.json file is being overwritten on every update. I will mark this as an enhancement and factor in your use case going forward

**Comment by tomhirschfeld** [comment]
any updates here?

**Comment by fkunecke** [comment]
Can confirm this is still an issue on `5.1.2`. I don't have any issues for resources manually added to `backend-config`, like queues or topics, but I have a function that `dependsOn` a queue that gets overwritten if I add a dependency through the CLI. @ammarkarachi if you can help point me in the right direction I can put together some code and submit a PR. This is a pretty big issue on my side.
