### ISSUE TITLE
Error: 'jsonString' argument missing or empty

### ISSUE THREAD

**Issue by TraxBox** [aws-amplify/amplify-cli#7350]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.1.0

### Amplify CLI Version

I get the following error when running 'amplify version': 'jsonString' argument missing or empty Error: 'jsonString' argument missing or empty     at Function.JSONUtilities.parse (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)     at Function.JSONUtilities.readJson (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)     at Object.readPluginsJsonFile (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-helpers/access-plugins-file.js:29:45)     at Object.getPluginPlatform (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:40:48)     at Object.run (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/index.js:65:53)     at Object.<anonymous> (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/bin/amplify:8:25)     at Module._compile (node:internal/modules/cjs/loader:1109:14)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)     at Module.load (node:internal/modules/cjs/loader:989:32)     at Function.Module._load (node:internal/modules/cjs/loader:829:14)     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)     at node:internal/main/run_main_module:17:47

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, interactions

### Amplify Commands

add, configure, configure project, delete, env, init, publish, pull, push, status, update

### Describe the bug

Can't seem to run any amplify commands without getting this error:
'jsonString' argument missing or empty
Error: 'jsonString' argument missing or empty
    at Function.JSONUtilities.parse (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.JSONUtilities.readJson (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at Object.readPluginsJsonFile (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-helpers/access-plugins-file.js:29:45)
    at Object.getPluginPlatform (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:40:48)
    at Object.run (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/index.js:65:53)
    at Object.<anonymous> (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/bin/amplify:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

### Expected behavior

I just want it to configure amplify

### Reproduction steps

1. I just try to run 'amplify init' 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
'jsonString' argument missing or empty
Error: 'jsonString' argument missing or empty
    at Function.JSONUtilities.parse (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:79:15)
    at Function.JSONUtilities.readJson (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at Object.readPluginsJsonFile (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-helpers/access-plugins-file.js:29:45)
    at Object.getPluginPlatform (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:40:48)
    at Object.run (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/lib/index.js:65:53)
    at Object.<anonymous> (/Users/sevenhorns/.nvm/versions/node/v16.1.0/lib/node_modules/@aws-amplify/cli/bin/amplify:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47


```

</details>

**Comment by TraxBox** [comment]
Also, I'm running this on the M1 Mac Big Sur 11.3.1. 
Not sure If that helps any.

**Comment by ammarkarachi** [comment]
@TraxBox it looks like the file `~/.amplify/plugins.json` has been corrupted somehow. Can you remove the file and try again?

**Comment by TraxBox** [comment]
Thx. Sorry for my ignorance, but I can't find a path to that file. Where might it be?

**Comment by ammarkarachi** [comment]
Do you see an output when you run `cat ~/.amplify/plugins.json`?

**Comment by TraxBox** [comment]
It seems I didn't get anything. ➜  ~ cat ~/.amplify/plugins.json
➜  ~

**Comment by ammarkarachi** [comment]
It's an empty file for some reason. Can you run `rm ~/.amplify/plugins.json`? and then invoke amplify

**Comment by TraxBox** [comment]
Got this: ➜  ~ rm ~/.amplify/plugins.json
➜  ~ amplify
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful

amplify <command> <subcommand>

  init                Initializes a new project, sets up deployment resources in the cloud, and makes your project ready for Amplify.                              
  configure           Configures the attributes of your project for amplify-cli, such as switching front-end framework and adding/removing cloud-provider plugins. 
  push                Provisions cloud resources with the latest local developments.                                                                               
  pull                Fetch upstream backend environment definition changes from the cloud and updates the local environment to match that definition.             
  publish             Executes amplify push, and then builds and publishes client-side application for hosting.                                                    
  serve               Executes amplify push, and then executes the project's start command to test run the client-side application locally.                        
  status              Shows the state of local resources not yet pushed to the cloud (Create/Update/Delete).                                                       
  delete              Deletes all of the resources tied to the project from the cloud.                                                                             
  <category> add      Adds a resource for an Amplify category in your local backend                                                                                
  <category> update   Update resource for an Amplify category in your local backend.                                                                               
  <category> push     Provisions all cloud resources in a category with the latest local developments.                                                             
  <category> remove   Removes a resource for an Amplify category in your local backend.                                                                            
  <category>          Displays subcommands of the specified Amplify category.                                                                                      
  mock                Run mock server for testing categories locally.                                                                                              
  codegen             Generates GraphQL statements(queries, mutations and eventHandlers) and type annotations.                                                     
  env                 Displays and manages environment related information for your Amplify project.                                                               
  console             Opens the web console for the selected cloud resource.                                                                                       
  logout              If using temporary cloud provider credentials, this logs out of the account.                                                                 

where <category> is one of: notifications, analytics, api, auth, function, hosting, interactions, predictions, storage, xr

➜  ~

**Comment by ammarkarachi** [comment]
The plugin file is written now if you execute the cat again it should have the data for the cli to execute

**Comment by TraxBox** [comment]
Also, should 'Amplify init' be ran from the directory where I place my Xcode file?

**Comment by TraxBox** [comment]
It all seems to be working correctly now. Can explain what the problem was?

**Comment by ammarkarachi** [comment]
>Also, should 'Amplify init' be ran from the directory where I place my Xcode file?

You should run in the root of your project, so if the file is under `src/` then a level above

>It all seems to be working correctly now. Can explain what the problem was?

Was this the case when you first invoked the CLI or it crept up later?

**Comment by ammarkarachi** [comment]
@TraxBox Closing this issue let me know if you have any other problems
