### ISSUE TITLE
Is there any way I can implement Phone number OTP authentication?

### ISSUE THREAD

**Issue by synaptic-universal** [aws-amplify/amplify-cli#7353]
I have been trying to use the feature of signin and signup using  Phone number OTP without email or username. But unfortunately there is no function folder in backend folder of amplify but many tutorials has that folder. So can I get some help over here. I am developing it in react.

**Comment by josefaidt** [comment]
Hey @synaptic-universal :wave: this would be a great question to ask in our [community Discord](https://discord.gg/amplify)! It isn't possible out-of-the-box with Amplify right now, however Amplify _can_ help connect your front-end to AWS resources. Additionally, here are a couple of community blog posts that have helped me personally get this customized workflow set up:

- https://hnp.dev/otp-based-phone-auth-amazon-cognito-amplify/
- https://techinscribed.com/passwordless-phone-number-authentication-using-aws-amplify-cognito/
- https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples-publishing-messages.html

If this is a feature you would like to see included in Amplify, consider [submitting a feature request](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml)
