### ISSUE TITLE
Updates to model with @key directive with 3 or more fields

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#7357]
I'm so confused about how to use the @key directive with 3 or more fields.

Do you have to provide the joined keys with *every* update?

Given the following ``@key(fields: ["email", "status", "date"])``,  I know you have to provide all three fields IF you are updating any of them. Meaning, in an update, if you update the object's "email" field, you have to provide the "status" and "date" as well.

But let's say you have a "subject" field and you just want to update that.

````
appsync.mutate({
                mutation: Message.mutations.update,
                variables: {
                  input: {
                    id: event.arguments.input.id,
                    subject: "Hi James!"
                  }
                }
              })
````

Do you have to provide the "status" and "date" fields?

I would assume not, but when I run this update, I get the field status#date with this value in Dynamo:

``${ctx.args.input.status}#${ctx.args.input.date}``

That seems like it can't be right, which is why i'm submitting this as a bug.

**Comment by sammartinez** [comment]
This seems to be Amplify CLI related. This issue is now transferred and cc @renebrandel on this.

**Comment by kaustavghosh06** [comment]
Closing this as the potential fix has been released as mentioned by @edwardfoyle 
Please let us know if you're still stuck on this,
