### ISSUE TITLE
Unions in GraphQL Transformer

### ISSUE THREAD

**Issue by colmartofus** [aws-amplify/amplify-cli#736]
** Which Category is your question related to? **
GraphQL Transform

** What AWS Services are you utilizing? **
AWS AppSync GraphQL Transform

** Provide additional details e.g. code snippets **
I'm new to GraphQL and AppSync. I'm interested in the modelling of unions. I have a text adventure game something like this (note the union):

```
enum Stage {
  GETTING_PLAYERS,
  VOTING
}

enum RoleName {
  ROGUE,
  WARRIOR,
  MAGE
}

# ONE IMPORTANT PART
union Role = Rogue | Warrior | Mage

type Game @model {
  id: ID!
  currentPlayers: [Player] @connection(name: "GamePlayers")
  stage: Stage!
}

type Player @model {
  id: ID!
  game: Game @connection(name: "GamePlayers")
  ingame: Boolean!
  ids: PlayerIdentifiers! @connection(name: "PlayerIds")
  gameState: PlayerGameState! @connection(name: "PlayerState")
}

type PlayerGameState @model {
  id: ID!
  player: Player! @connection(name: "PlayerState")
  role: Role # ANOTHER IMPORTANT PART
  votesReceived: [String]
}

type PlayerIdentifiers @model {
  id: ID!
  ingameName: String!
  player: Player @connection(name: "PlayerIds")
}

type Rogue @model {
  id: ID!
  name: RoleName!
  cloak: String
  dagger: String
}

type Warrior @model {
  id: ID!
  name: RoleName!
  sword: String
  strength: int
}

type Mage @model {
  id: ID!
  name: RoleName!
  spell: String
}
```

After I run `amplify update api` and `amplify push`, my `CreatePlayerGameState` and `UpdatePlayerGameState` types don't have an associated role though the `PlayerGameState` type has a `Role`. I've tried adding `@connection` but get `Could not find an object type named Role.`. How can I have my union modelled so that I can use it in my mutations or am I going about this all wrong and there's an easier way to do this?

**Comment by colmartofus** [comment]
Thanks for your reply. Is there a tutorial for writing a custom resolver using graphql-transformer?

Is there also a tutorial on writing a custom query using graphql-transformer?

**Comment by kaustavghosh06** [comment]
@colmartofus We're releasing support for custom resolvers along with comprehensive documentation for the same. I'll update this thread once we release the feature. For more details, you can take a look at https://github.com/aws-amplify/amplify-cli/pull/581

**Comment by kaustavghosh06** [comment]
Hey guys,
We've added functionality for custom resolvers. Please use `npm install -g @aws-amplify/cli` to install the latest version of the CLI. For documentation regarding it, please refer to https://aws-amplify.github.io/docs/cli/graphql#overwrite-a-resolver-generated-by-the-graphql-transform

Here's the launch announcement for the same - https://aws.amazon.com/blogs/mobile/amplify-adds-support-for-multiple-environments-custom-resolvers-larger-data-models-and-iam-roles-including-mfa/

**Comment by colmartofus** [comment]
Thanks for the update.

**Comment by Macheine** [comment]
> 
> 
> Hey guys,
> We've added functionality for custom resolvers. Please use `npm install -g @aws-amplify/cli` to install the latest version of the CLI. For documentation regarding it, please refer to https://aws-amplify.github.io/docs/cli/graphql#overwrite-a-resolver-generated-by-the-graphql-transform
> 
> Here's the launch announcement for the same - https://aws.amazon.com/blogs/mobile/amplify-adds-support-for-multiple-environments-custom-resolvers-larger-data-models-and-iam-roles-including-mfa/

That link is dead, is there any place to still find the documentation on this?

**Comment by arealmaas** [comment]
> Hey @colmartofus, unfortunately the transformer does not currently support union types in the manner you are proposing. You are welcome to use union types and then write your own resolver that implements the behavior but as of writing this will not be auto-generated.

@mikeparisstuff  Just to let others know that I followed this example, but having issues generating typescript-models when doing this. https://github.com/aws-amplify/amplify-codegen/issues/143

Is there an other solution to this to get the models generated even though I use interface/union types?
