### ISSUE TITLE
Deprecated library warnings upon inaugural install

### ISSUE THREAD

**Issue by awhitford** [aws-amplify/amplify-cli#737]
**Describe the bug**
My inaugural installation produced a few deprecated library warnings:
* deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
* deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax.
* deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**To Reproduce**
It was my first time installing:  `npm install -g @aws-amplify/cli`

**Expected behavior**
Consistent with OWASP Top 10 A9, I would expect dependencies to be kept up to date to minimize security flaws, and ensure maintainability.  It is also surprising to see an actively maintained project emit package deprecation warnings.

**Screenshots**
```
$ npm install -g @aws-amplify/cli
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
...
+ @aws-amplify/cli@0.1.42
added 1950 packages from 1311 contributors in 56.741s
```

**Desktop**
 - OS: Mac OSX 10.14.2
 - NodeJS 10.15.0
 - NPM 6.4.1

**Comment by kaustavghosh06** [comment]
@awhitford It's not a direct dependency of the CLI but a dependency of a dependency.

**Comment by awhitford** [comment]
Good answer.  Sorry that I didn't think to check that.  I was just sharing my alarm.
