### ISSUE TITLE
amplify pull always asking for credentials

### ISSUE THREAD

**Issue by connected-mdeluco** [aws-amplify/amplify-cli#7370]
**Which Category is your question related to?**
api (I think)

**Amplify CLI Version** 
v4.50.2

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
For my team I'm trying to follow the directions on the [Team Environments](https://docs.amplify.aws/cli/teams/multi-frontend) document, where my mobile team does *not* plan on modifying the backend.

However, I assume the mobile team will find it necessary to checkout feature environments as they develop the frontend mobile features that take advantage of updates in the backend.

Every time I run `amplify pull` in the mobile codebase, I have to go through the whole process of providing access keys, selecting a region, editor, etc.

Shouldn't that information be saved, so from the mobile code base I can easily switch between amplify environments?

**Comment by ammarkarachi** [comment]
@connected-mdeluco Are you executing a pull on an existing project?

**Comment by connected-mdeluco** [comment]
@ammarkarachi - yes, it's an existing project, the option to choose the project comes up as one of the questions after executing `amplify pull`. It automatically detects the `dev` environment, which is the only one we have at the moment, and continues with the remaining questions.

The process finishes with the message:
```
Added backend environment config object to your project.
Run 'amplify pull' to sync upstream changes.
```

If I run `amplify pull` again, I have to go through all the questions again.

I'd like our mobile devs to be able to easily and quickly switch between environments.

**Comment by connected-mdeluco** [comment]
After going through all the questions, entering my credentials, etc. `amplify env checkout dev` results in the following:
```
      No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
```

The only Amplify-related file seems to be `src/aws-exports.js`.

I assume this is all related to answering `? Do you plan on modifying this backend? No` - but it's incredibly inconvenient to have to go through 13 inputs every time we change environments.

**Comment by ammarkarachi** [comment]
You could try using pull with [headless](https://docs.amplify.aws/cli/usage/headless#amplify-pull-parameters)  and save the script new projects that your pull your amplify app into

**Comment by connected-mdeluco** [comment]
@ammarkarachi - so that doesn't really solve the problem, it just answers all the questions using command parameters?

My concern is how my mobile team will easily switch environments, which I guess is not possible, and not expected as part of the documented workflow?

With the workflow as it stands, how then are mobile teams supposed to complete frontend development related to a backend feature? They'll have to wait for the backend environment to be merged to the main environment? But even then, every time they pull the main environment they have to go through the questionnaire.

Is this really the intended functionality?

**Comment by kaustavghosh06** [comment]
@connected-mdeluco Are you still stuck on this issue? We don't recommend storing AWS AccessKeys and SecretKeys as a part of your project code or repository - hence it is stored outside of the project in either ~/.aws or ~/.amplify.
Each time a new machine is used or a new team-member wants to pull down a project, they'd need to authenticate and fetch credentials for their development.
