### ISSUE TITLE
Using multiple AWS accounts in the same Ubuntu box

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/amplify-cli#7373]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

amplify configure 

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

4.49.0

**What AWS Services are you utilizing?**

Amplify and all its related services

**Provide additional details e.g. code snippets**

Hi, I want to set two amplify projects over two different AWS accounts. I was wondering if it is possible to add two different configurations (two different AWS accounts) to amplify via amplify configure in my Ubuntu computer? If yes, how can this be managed? If not, is it possible to run amplify configure each time I want to work with a different AWS account?

**Comment by ammarkarachi** [comment]
@leonardocfor Yes it is possible to manage two different projects with different project when you execute `amplify init` the CLI prompts you to select the user-profile/keys. You can use the desired profile key from the corresponding account and initialize the project.

**Comment by leonardocfor** [comment]
@ammarkarachi thanks man, that worked
