### ISSUE TITLE
Problem with Pinpoint and Cloud fFormation

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#7376]
Hello,

My project uses pinpoint to send emails and push notifications.
I modified this file:
/amplify/backend/analytics/pinpointResource/pinpoint-cloudformation-template.json

To add my email and push templates there (so, they are saved in my repository)
One template works:
```
  "Resources": {
    "EmailTemplate1": {
      "Type": "AWS::Pinpoint::EmailTemplate",
      "Properties": {
        "HtmlPart": "xxxxxxxx",
        "TextPart": "xxxxxx",
        "Tags": {},
        "TemplateDescription": "xxxxxx",
        "DefaultSubstitutions": "xxxxx",
        "TemplateName": "verification_email_template",
        "Subject": "xxxxxxx"
      }
    }
    .....

```
But if I try to add 2 or more templates, only one of them is deployed (that is, I only see one in the pinpoint console).
```
  "Resources": {
    "EmailTemplate1": {
      "Type": "AWS::Pinpoint::EmailTemplate",
      "Properties": {
        "HtmlPart": "xxxxxxxx",
        "TextPart": "xxxxxx",
        "Tags": {},
        "TemplateDescription": "xxxxxx",
        "DefaultSubstitutions": "xxxxx",
        "TemplateName": "verification_email_template",
        "Subject": "xxxxxxx"
      }
    },
    "EmailTemplate2": {
      "Type": "AWS::Pinpoint::EmailTemplate",
      "Properties": {
        "HtmlPart": "xxxxxxxx",
        "TextPart": "xxxxxx",
        "Tags": {},
        "TemplateDescription": "xxxxxx",
        "DefaultSubstitutions": "xxxxx",
        "TemplateName": "visit_email_template",
        "Subject": "xxxxxxx"
      }
    },
    ....

```

So, what's wrong? probably I am missing something related cloud formation syntax.
Do you see the mistake?
Thanks a lot.

**Which Category is your question related to?**
CLI, pinpoint and cloud formation

**Amplify CLI Version** 
4.50.2

**What AWS Services are you utilizing?**
CLI, pinpoint and cloud formation

**Provide additional details e.g. code snippets**
Above

**Comment by ammarkarachi** [comment]
I added the templates you have to my cfn and it looks like they got added. Have you checked if they are added in the same region?
![image](https://user-images.githubusercontent.com/56042290/119172319-a845e100-ba1a-11eb-8e55-105c68a7142e.png)

**Comment by Ricardo1980** [comment]
@ammarkarachi
you are right, it is also working in my computer. I don't know yesterday it didn't work.
Anyway, thanks a lot for testing this. I close the ticket.
