### ISSUE TITLE
storage add in amplify-headless-interface is implemented but not work

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-cli#7378]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### If applicable, what version of Node.js are you using?

v12.13.0

### Amplify CLI Version

4.51.1

### What operating system are you using?

macOS

### Amplify Categories

storage

### Amplify Commands

add

### Describe the bug

I have this JSON
```json
{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "S3",
    "permissions": {
      "auth": ["CREATE","READ","UPDATE","DELETE"]
    },
    "bucketName": "tsBucket",
    "lambdaTrigger": {
      "mode": "existing",
      "name": "tsTriggerFunction"
    }
  }
}
```
And execute in console 

`cat tsHeadlessStorage.addstorage.json | jq -c | amplify add storage --headless`

Headless mode is not implemented for amplify-category-storage

### Expected behavior

I'm using this: https://docs.amplify.aws/cli/usage/headless

The error is: Headless mode is not implemented for amplify-category-storage

but I see here that storage add is implemented: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-headless-interface/src/interface/storage/add.ts

### Reproduction steps

create headless JSON for storage and execute in console: `cat tsHeadlessStorage.addstorage.json | jq -c | amplify add storage --headless`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@sytolk I will mark this as an enhancement we do have the code but we are still working on some implementation details

**Comment by sytolk** [comment]
Its implemented now thanks https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-headless-interface/src/interface/storage
