### ISSUE TITLE
Object Properties Missing in Autogenerated Mutation Input for AppSync 

### ISSUE THREAD

**Issue by ph0ph0** [aws-amplify/amplify-cli#7383]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17

### Amplify CLI Version

4.51.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I have a custom GraphQL schema for a blogging application. The main model type is Post.

Post contains a number of properties that have a custom type eg `Gallery: [MediaObject]`. The majority of these properties with custom types are missing from the automatically generated `CreatePostInput`. This means that I cannot create a Post object that has these properties with custom type.

The lack of these custom type properties is evident in the AppSync console, under Queries. In the Explorer, go to Mutations, click on CreatePost mutation, and you will see that 6 of the 21 properties for Post are missing. The missing properties are tags, attributes, seo, featuredImage, gallery and createdBy.

They are also missing in the autogenerated graphql schema in api > build > schema.graphql in the react app.

I have made multiple clean projects from scratch, and the problem is reproducible. I have changed the `maxDepth` via `amplify codegen configure` to 3, and also updated the amplify cli to 4.51.2 and still no luck. 

### Expected behavior

I expect all of the properties to be there in the CreatePost Input.

### Reproduction steps

1) Create a new react/amplify app in the usual manner
2) Use my custom schema
3) Check the autogenerated schema and the AppSync > Queries tab.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


type Post @model {
    id: ID
    createdBy: User
    createdAt: AWSDateTime
    updatedAt:AWSDateTime
    type: PostType!
    title: String!
    status: Status
    content: String!
    excerpt: String
    slug: AWSURL
    wordpressId: Int
    wordpressImageURLs: [AWSURL]
    author: String
    likes: Int
    tags: [Tag]
    attributes: Attribute
    seo: Seo
    featuredImage: MediaObject
    gallery: [MediaObject]
    comments: [Comment]
    numberOfComments: Int

}

type User @model {
    id: ID
    username: String!
    firstName: String
    lastName: String
    email: AWSEmail!
    avatar: MediaObject
    location: String
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    Posts: [Post]
}

type Tag @model {
    id: ID
    postIds: [ID]
    name: String!
}

type Attribute @model {
    id: ID
    postId: ID
    link: String
    imgUrl: AWSURL
    ogImage: AWSURL
    ogDescription: String
    canonicalLink: AWSURL
}

type Seo @model {
    id: ID
    postId: ID
    metaRobotsNoIndex: String
    metaRobotsNoFollow: String
    canonical: AWSURL
    metaDesc: String
    opengraphDescription: String
    opengraphModifiedTime: AWSDateTime
    opengraphPublishedTime: AWSDateTime
    opengraphTitle: String
    opengraphUrl: AWSURL
    opengraphImage: AWSURL
    twitterDescription: String
    twitterImage: String
    twitterTitle: String
    schemaSeo: String
}

type Comment
   {
  id: ID
  postId: ID!
  createdBy: ID
  author: String
  createdAt: AWSDateTime
  text: String!
  likes: Int
}

type MediaObject @model {
    id: ID
    linkedId: ID
    createdBy: ID
    mediaItemUrl: AWSURL
    srcSet: String
    medium: AWSURL
    thumb: AWSURL
    sourceURL: AWSURL
    description: String
    bucket: String
    region: String
    key: String
    type: MediaObjectType
}

type Like @model {
    id: ID!
    objectVotedOnID: ID!
    createdBy: ID
    createdAt: AWSDateTime
    likeOn: LikeOnType

}

enum PostType {
    TOOLS
    BLOGS
    INSPIRATIONS
    NEWS
    POSTS
    NEWSLETTERS
}

enum LikeOnType {
    POST
    COMMENT
}

enum Status {
    PUBLISH
    DRAFT
}

enum MediaObjectType {
    IMAGE
    VIDEO
    AUDIO
}


// This is the resultant autogenerated CreatePostInput, which is missing 6 fields:

input CreatePostInput {
  id: ID
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  type: PostType!
  title: String!
  status: Status
  content: String!
  excerpt: String
  slug: AWSURL
  wordpressId: Int
  wordpressImageURLs: [AWSURL]
  author: String
  likes: Int
  comments: [CommentInput]
  numberOfComments: Int
}

</details>


### Log output

<details>

```
# Put your logs below this line

```

</details>


### Additional information

If there are any issues with my schema, please let me know. Thanks very much!

**Comment by ammarkarachi** [comment]
@ph0ph0 If you would like to connect model types you can use the `@connection` directive to establish relationships between your data model [here](https://docs.amplify.aws/cli/graphql-transformer/connection)

**Comment by ph0ph0** [comment]
Ok thanks for the pointer @ammarkarachi, I was confused as to why the comments array/type was included in the CreatePostInput, and not the other fields that I referred to?

**Comment by ph0ph0** [comment]
To anyone else that comes across this issue, I have found the reason why CommentInput is included in the CreatePostInput, but the other custom types are not. `Comment` was the only one that was not annotated with a `@model` directive. I assume that this means that AppSync then views this type on the `comments` field as a set of nested fields, rather than an object with its own DynamoDB table. Perhaps @ammarkarachi could shed more light on this?
