### ISSUE TITLE
npm i @aws-amplify/cli installs older version 4.51.0 not the latest 4.51.1

### ISSUE THREAD

**Issue by wbrijesh** [aws-amplify/amplify-cli#7389]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.51.1

### If applicable, what version of Node.js are you using?

v14.16.1

### What operating system are you using?

Mac

### Browser type?

Firefox developer edition

### Describe the bug

running amplify pull.... gives this error 

```
Opening link: https://ap-south-1.admin.amplifyapp.com/admin/d3d3gypvzk1ai2/staging/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: d3d3gypvzk1ai2. Amplify App name is: next-blog
Backend environment staging found in Amplify Console app: next-blog
Failed to pull the backend.
Invalid feature flag configuration

These feature flags are defined in the "amplify/cli.json" configuration file and are unknown to the currently running Amplify CLI:
  - codegen.handlelistnullabilitytransparently

This issue likely happens when the project has been pushed with a newer version of Amplify CLI, try updating to a newer version.

Learn more about feature flags: https://docs.amplify.aws/cli/reference/feature-flags
```

### Expected behavior

`npm i @aws-amplify/cli`
 doesn't installs older version 4.51.0 not the latest one

### Reproduction steps

amplify pull --appId xxxxxxxxxxxxxx --envName staging

### Additional information

although adding @latest or running amplify upgrade will solve the problem it would be nice to have the latest version installed by default, especially because admin ui requires the latest version

**Comment by ammarkarachi** [comment]
@wbrijesh you would need to install Amplify CLI globally by invoking `npm i -g @aws-amplify/cli@latest`. We do not support local installs yet.

**Comment by wbrijesh** [comment]
I did try
