### ISSUE TITLE
[multienv] Unable to migrate existing amplifyjs project

### ISSUE THREAD

**Issue by benbayard** [aws-amplify/amplify-cli#739]
**Describe the bug**
With an existing project I am trying to migrate to multienv

**To Reproduce**
1. Install multienv
2. Run: `amplify env`
3. Get error needing to migrate configs
4. ![image](https://user-images.githubusercontent.com/1026035/51447336-e9564b00-1cd1-11e9-8d03-3e82b8708b5c.png)
5. I figured out the error was with the structure of my `amplify-meta.json`, so I change it to: 
```
{
    "providers": {
        "awscloudformation": {
            "AuthRoleName": "XXX",
            "UnauthRoleArn": "YYY,
            "AuthRoleArn": "ZZZ",
            "Region": "us-west-2",
            "DeploymentBucketName": "XXX",
            "UnauthRoleName": "XXX,
            "StackName": "XXX,
            "StackId": "XXX",
            "api": {
                "Kylo": {
                    "service": "AppSync",
                    "output": {
                        "securityType": "API_KEY",
                        "GraphQLAPIIdOutput": "AAA",
                        "GraphQLAPIEndpointOutput": "BBB",
                        "GraphQLAPIKeyOutput": "CCC"
                    },
                    "lastPushTimeStamp": "2018-11-04T01:13:40.460Z"
                }
            },
            "auth": {...},
            "hosting": {...}
        }
    }
}
```
6. That got the migration to work! Yay! Listing my amplify showed all the correct information
7. Run: `amplify env add`
8. Get new error: ```SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Command.run (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/src/commands/env/add.js:9:25)
    at Runtime.<anonymous> (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:90:58)
    at step (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:32:23)
    at Object.next (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:13:53)
    at /Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:3:12)
    at Runtime.run (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:51:12)
    at Object.run (/Users/ben/.nvm/versions/node/v10.13.0/lib/node_modules/@aws-amplify/cli/src/cli.js:26:29)```

**Expected behavior**
I would expect to not have to do the original migration without needing to change up my file. 
I would also expect add to work correctly.

Is there a way I can back up my config, and re-init? How can I make sure I get the _exact same config_ if I delete my existing config and re-try? 

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser  Chrome (but this is all in the CLI)
 - Version [e.g. 22] latest

**Added information**

Ideally what I am trying to do is this (maybe I am using the incorrect tools:
1. Check out my feature branch (e.g. `ben-implements-new-be-feature`)
2. Have an environment that has a separate AppSync project
3. When I push to github and it merges to some branch (ideally master
4. When my changes are merged to master the changes that I had made to the appsync project are merged in to the production app. 

My biggest problem is that I cannot edit my appsync back end because it's pointing to production. So I have no real way to test backend changes or updates. I'm open to any way to make changes locally and migrate them to production easily.

**Comment by kaustavghosh06** [comment]
@benbayard `amplify init` with the multienv CLI won't make your stack disappear. It would prompt you if you want to initialize a new env and then you can switch between your envs using `amplify env checkout <env-name>' command.

**Comment by kaustavghosh06** [comment]
@benbayard Were you able to get this running? Please re-open this issue if you're still stuck
