### ISSUE TITLE
Add secret: TypeError: Cannot read property 'length' of undefined (Policies cannot be added for secret)

### ISSUE THREAD

**Issue by hphirke** [aws-amplify/amplify-cli#7398]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

4.51.2

### What operating system are you using?

Ubuntu

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

I have added Custom resource as per docs:
https://docs.amplify.aws/cli/usage/customcf#n3-optional-reference-existing-parameters

When I add the API using amplify api add, I am adding a lambda fucntion which needs to add custom resource (secret from Secret Manager)

But while adding custom resource  I get error as:

```
**Policies cannot be added for secret**
_TypeError: Cannot read property 'length' of undefined
    at AmplifyToolkit.getCategoryPluginInfo [as _getCategoryPluginInfo] (/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-category-pluginInfo.js:7:32)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/invoke-plugin-method.js:24:40)
    at getResourcesForCfn (/home/hp/.config/yarn/global/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:181:78)
    at Object.askExecRolePermissionsQuestions (/home/hp/.config/yarn/global/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:109:72)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.createWalkthrough (/home/hp/.config/yarn/global/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:44:78)
    at async addFunctionResource (/home/hp/.config/yarn/global/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:58:9)
    at async newLambdaFunction (/home/hp/.config/yarn/global/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:522:26)
    at async askPaths (/home/hp/.config/yarn/global/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:409:22)
    at async pathFlow (/home/hp/.config/yarn/global/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:152:25)
    at async Object.legacyAddResource (/home/hp/.config/yarn/global/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/legacy-add-resource.js:16:20)
    at async Object.executeAmplifyCommand (/home/hp/.config/yarn/global/node_modules/amplify-category-api/lib/index.js:166:5)
    at async executePluginModuleCommand (/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/lib/index.js:114:9)

You can access the following resource attributes as environment variables from your Lambda function
	AUTH_TALENTOTODAY6A1A6D08_USERPOOLID
	ENV
	REGION_
```

### Expected behavior

It should add Correct policy for resources (Lambda here)

### Reproduction steps

```
amplify add api
? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: myFunction
? Provide a path (e.g., /book/{isbn}): /
? Choose a Lambda source Create a new Lambda function
? Provide an AWS Lambda function name: myFunctionHandler
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. auth, secret
? Auth has 2 resources in this project. Select the one you would like your Lambda to access <My pool>
? Select the operations you want to permit on My pool read
? Secret has 2 resources in this project. Select the one you would like your Lambda to access secretName
? Select the operations you want to permit on secretName read
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```

# Put your logs below this line
amplify add api
? Please select from one of the below mentioned services: REST
? Provide a friendly name for your resource to be used as a label for this category in the project: myFunction
? Provide a path (e.g., /book/{isbn}): /
? Choose a Lambda source Create a new Lambda function
? Provide an AWS Lambda function name: myFunctionHandler
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration

? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. auth, secret
? Auth has 2 resources in this project. Select the one you would like your Lambda to access <My pool>
? Select the operations you want to permit on My pool read
? Secret has 2 resources in this project. Select the one you would like your Lambda to access secretName
? Select the operations you want to permit on secretName read

```

</details>

**Comment by himanshuphirke** [comment]
I tried adding few logs and here is what I found:
{ category: 'secret' }
and 
data structure: context.pluginPlatform.plugins
in getCategoryPluginInfo has values:


{
  core: [
    {
      packageName: '@aws-amplify/cli',
      packageVersion: '4.51.2',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/@aws-amplify/cli/',
      manifest: [Object]
    }
  ],
  analytics: [
    {
      packageName: 'amplify-category-analytics',
      packageVersion: '2.21.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-analytics',
      manifest: [Object]
    }
  ],
  api: [
    {
      packageName: 'amplify-category-api',
      packageVersion: '2.31.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-api',
      manifest: [Object]
    }
  ],
  auth: [
    {
      packageName: 'amplify-category-auth',
      packageVersion: '2.32.0',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-auth',
      manifest: [Object]
    }
  ],
  function: [
    {
      packageName: 'amplify-category-function',
      packageVersion: '2.31.9',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-function',
      manifest: [Object]
    }
  ],
  hosting: [
    {
      packageName: 'amplify-category-hosting',
      packageVersion: '2.7.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-hosting',
      manifest: [Object]
    },
    {
      packageName: 'amplify-console-hosting',
      packageVersion: '1.8.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-console-hosting',
      manifest: [Object]
    },
    {
      packageName: 'amplify-container-hosting',
      packageVersion: '1.3.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-container-hosting',
      manifest: [Object]
    }
  ],
  interactions: [
    {
      packageName: 'amplify-category-interactions',
      packageVersion: '2.6.2',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-interactions',
      manifest: [Object]
    }
  ],
  notifications: [
    {
      packageName: 'amplify-category-notifications',
      packageVersion: '2.19.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-notifications',
      manifest: [Object]
    }
  ],
  predictions: [
    {
      packageName: 'amplify-category-predictions',
      packageVersion: '2.8.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-predictions',
      manifest: [Object]
    }
  ],
  storage: [
    {
      packageName: 'amplify-category-storage',
      packageVersion: '2.11.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-storage',
      manifest: [Object]
    }
  ],
  xr: [
    {
      packageName: 'amplify-category-xr',
      packageVersion: '2.8.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-category-xr',
      manifest: [Object]
    }
  ],
  codegen: [
    {
      packageName: 'amplify-codegen',
      packageVersion: '2.24.2',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-codegen',
      manifest: [Object]
    }
  ],
  functionRuntime: [
    {
      packageName: 'amplify-dotnet-function-runtime-provider',
      packageVersion: '1.5.4',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-dotnet-function-runtime-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-go-function-runtime-provider',
      packageVersion: '1.8.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-go-function-runtime-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-java-function-runtime-provider',
      packageVersion: '1.8.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-java-function-runtime-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-nodejs-function-runtime-provider',
      packageVersion: '1.5.5',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-nodejs-function-runtime-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-python-function-runtime-provider',
      packageVersion: '1.8.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-python-function-runtime-provider',
      manifest: [Object]
    }
  ],
  functionTemplate: [
    {
      packageName: 'amplify-dotnet-function-template-provider',
      packageVersion: '1.5.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-dotnet-function-template-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-go-function-template-provider',
      packageVersion: '1.3.7',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-go-function-template-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-java-function-template-provider',
      packageVersion: '1.5.5',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-java-function-template-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-nodejs-function-template-provider',
      packageVersion: '1.6.8',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-nodejs-function-template-provider',
      manifest: [Object]
    },
    {
      packageName: 'amplify-python-function-template-provider',
      packageVersion: '1.3.9',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-python-function-template-provider',
      manifest: [Object]
    }
  ],
  android: [
    {
      packageName: 'amplify-frontend-android',
      packageVersion: '2.15.3',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-frontend-android',
      manifest: [Object]
    }
  ],
  flutter: [
    {
      packageName: 'amplify-frontend-flutter',
      packageVersion: '0.4.3',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-frontend-flutter',
      manifest: [Object]
    }
  ],
  ios: [
    {
      packageName: 'amplify-frontend-ios',
      packageVersion: '2.20.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-frontend-ios',
      manifest: [Object]
    }
  ],
  javascript: [
    {
      packageName: 'amplify-frontend-javascript',
      packageVersion: '2.22.1',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-frontend-javascript',
      manifest: [Object]
    }
  ],
  awscloudformation: [
    {
      packageName: 'amplify-provider-awscloudformation',
      packageVersion: '4.50.0',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-provider-awscloudformation',
      manifest: [Object]
    }
  ],
  mock: [
    {
      packageName: 'amplify-util-mock',
      packageVersion: '3.31.2',
      packageLocation: '/home/hp/.config/yarn/global/node_modules/amplify-util-mock',
      manifest: [Object]
    }
  ]
}

**Comment by SwaySway** [comment]
Hello @himanshuphirke 

Functions does not support the resource access question workflow for custom resources. Marking this as a bug as the CLI should warn that this option is not supported.

**Comment by josefaidt** [comment]
Hey @hphirke :wave: per the comment above a message has since been added to warn when attempting to grant access to a custom category:

```
? Select the operations you want to permit on customResource91c37637 read
custom category does not support resource policies yet.
```

To grant access to resources in a function, we can leverage the [`custom-policies.json` file](https://docs.amplify.aws/cli/function/#access-existing-aws-resource-from-lambda-function) to specify which additional actions we want to allow such as getting parameters from SSM:

```json
[
  {
    "Action": ["ssm:GetParameters"],
    "Resource": [
      "arn:aws:ssm:us-east-1:*:parameter/amplify/myamplifyapp/${env}/*"
    ]
  }
]
```

Closing issue 🙂
