### ISSUE TITLE
S3 buckets should require ssl requests by default

### ISSUE THREAD

**Issue by nsluss** [aws-amplify/amplify-cli#7405]
### Is this related to a new or existing Amplify category?

storage, hosting

### Is this related to another service?

S3

### Describe the feature you'd like to request

In keeping with AWS Foundational Security Best Practices, Amplify created S3 buckets should default to requiring requests to use HTTPS and reject HTTP.

### Describe the solution you'd like

Generated CloudFormation templates for S3 buckets should come with a bucket policy that rejects HTTP requests. Short of being a default, a documented flag in a config file or cli option would work too.

### Describe alternatives you've considered

Remediation instructions for the config rule `s3-bucket-ssl-requests-only` are pretty straight forward: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#s3-5-remediation

It's also possible to change the templates manually to include the correct policy

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by edwardfoyle** [comment]
This has been addressed by https://github.com/aws-amplify/amplify-cli/pull/10533/files
