### ISSUE TITLE
VTL resolver files not correctly regenerating when changing auth rules on existing type

### ISSUE THREAD

**Issue by jingo64** [aws-amplify/amplify-cli#7406]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.0.0

### Amplify CLI Version

4.51.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I have an existing graphql type, which looks something like this:

```gql
type Account @model @auth(rules: [{ allow: owner }]) 
  @key(name: "ByOwner", fields: ["owner"], queryField: "accountsByOwner"){
  id: ID! # this should come from Yodlee
  name: String! # account name - currently being used as the "unique" id for our MVP as 
}
```

It has a corresponding resolver type added into the folder "resolvers", which looks like this:

```
#if( $authMode == "userPools" )
  ## No Static Group Authorization Rules **


  ## [Start] If not static group authorized, filter items **
  #if( !$isStaticGroupAuthorized )
    #set( $items = [] )
    #foreach( $item in $ctx.result.items )
      ## No Dynamic Group Authorization Rules **
    ...
```

I want to add a new auth type based on groups, so changes my original spec to something like:

```gql
type Account @model @auth(rules: [{ allow: owner }, { allow: groups, groups: ["Admin"]}]) 
  @key(name: "ByOwner", fields: ["owner"], queryField: "accountsByOwner"){
  id: ID! # this should come from Yodlee
  name: String! # account name - currently being used as the "unique" id for our MVP as 
}
```

I run `amplify push`, however my admin role users do not have access.

The issue appears to be, the files in these folders are not updated after they are first created, I'm guessing this is by design so people can override the content with their own VTL scripts where needed.

The issue is, there is nothing in the documentation that explains this behaviour.

### Expected behavior

After a new `amplify push` on the API change, the VTL file to be regenerated and access to work as expected.

### Reproduction steps

1. Create a type, with some access policy
2. Push that type using amplify push
3. Add a new permission policy onto this, without changing the VTL file
4. Re-run amplify push
5. Check the VTL file, it hasn't changed (or at least my local one hasn't). Check your deployed version, that new access policy is not applied.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I appear to be able to work around the problem by just deleting the "resolvers" folder entirely that exists in my API structure. This seems to cause them to be regenerated from scratch each time and therefore the problem goes away. If this is the desired behaviour, it'd be good to advise people to not persist these files unless you need to override the VTL entries.

**Comment by yuth** [comment]
@jingo64 The resolver should get updated to accommodate the Static group authorization rule that you added. All your resolvers inside `<proj-root>/amplify/api/<api-name>/build/resolvers/` should get updated with the following code

```
  ## [Start] Static Group Authorization Checks **
  #set($isStaticGroupAuthorized = $util.defaultIfNull(
            $isStaticGroupAuthorized, false))
  ## Authorization rule: { allow: groups, groups: ["Admin"], groupClaim: "cognito:groups" } **
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("cognito:groups"), []) )
  #set( $allowedGroups = ["Admin"] )
  #foreach( $userGroup in $userGroups )
    #if( $allowedGroups.contains($userGroup) )
      #set( $isStaticGroupAuthorized = true )
      #break
    #end
  #end
  ## [End] Static Group Authorization Checks **
```

Could you clarify 
1. Do you have the resolvers overridden by having a copy of them in `<proj-root>/amplify/api/<api-name>/resolvers/`
2. What command did you use to push the changes? Did you use `amplify push --no-gql-override`

**Comment by SwaySway** [comment]
Closing issue due to lack of response. If you are still experiencing this issue please comment below to re-open.
