### ISSUE TITLE
Iterative GSI Updates Ignores Backend Limits

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#7425]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v10.24.1

### Amplify CLI Version

4.51.3

### What operating system are you using?

AWS Linux (Cloud9)

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

The new "enableiterativegsiupdates" was a welcome step forward, unfortunately it doesn't appear to consider the back end limitations when generating its stacks. My application has ~50 models and ~200 GSI's. If I try to create this it aborts immediately with a cryptic message saying "Rate exceeded".

So if I comment out all the GSI's to just create the models it won't fail on "Rate exceeded", but it will fail part way through because trying to create tables concurrently chokes the back end. So then I have to manually insert DependsOn statements to tell it to wait for each previous Model to create.

So now I have my models created and want to create GSI's - so if I uncomment the ~200 GSI's and try to run that it will eventually choke when it tries to update more than 25 tables with GSI's concurrently. But because it was an iterative update trying to roll this back to a point I can start again seems to be more than a little fraught / fragile.

Ultimately, at the moment, given the CLI seems to have no awareness of backend limitations and tries to push stuff that is not going to work due to those limitations, its probably safer to proceed without "enableiterativegsiupdates" until such time that the CLI understands the back end limitations.

### Expected behavior

The CLI understands the back end limitations and does not create a stack that is going to fail on push.

### Reproduction steps

Described in the bug description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
Hi @sacrampton 

> So if I comment out all the GSI's to just create the models it won't fail on "Rate exceeded", but it will fail part way through because trying to create tables concurrently chokes the back end. So then I have to manually insert DependsOn statements to tell it to wait for each previous Model to create.

The feature `enabledIterativeUpdates` currently supports changing GSIs on your already existing tables. For creation of multiple tables we are looking at using the same iterative deployment logic for creation of tables as well. Follow this issue for updates https://github.com/aws-amplify/amplify-cli/issues/2584

> So now I have my models created and want to create GSI's - so if I uncomment the ~200 GSI's and try to run that it will eventually choke when it tries to update more than 25 tables with GSI's concurrently.

To understand this better, can you explain this a little further?
- How are the 200 GSIs spaced out between 50 tables?
- What sort of change is happening during the update between these 200 GSIs? Do you change the name of the index? sort fields?

**Comment by sacrampton** [comment]
Hi @SwaySway - in the documents it says "Enable multiple GSI updates through iterative incremental deployments." (https://docs.amplify.aws/cli/reference/feature-flags#enableIterativeGsiUpdates).  I guess I didn't read that to be it is ONLY for updates and not create GSI operations. My case I was changing from @connections to @keys which required deleting the existing GSI's created by the connection and creating them via key. So my updates were deletes and creates. From what you are saying the creation is not supported (if I'm understanding it).

**Comment by SwaySway** [comment]
Hi @sacrampton 
The ff `enableiterativegsiupdates` is scoped to the creation, update, and removal of GSIs on an existing table.

> My case I was changing from `@connection` to `@key` which required deleting the existing GSI's created by the connection and creating them via key. So my updates were deletes and creates.

Given the initial limit of having 20 GSIs per table: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes

- For some of these changes did some tables have near 20 GSIs as opposed to some other tables?
- What sort of error did you get from doing a push on this? We recently added some retry logic when it comes to checking if an iterative deployment is ready for the next deployment (https://github.com/aws-amplify/amplify-cli/pull/7278)

**Comment by sacrampton** [comment]
Hi @SwaySway - I have 1 table with 14 GSI's and most others are substantially lower than that.

In terms of errors, I try to create this it aborts immediately with a cryptic message saying "Rate exceeded".

**Comment by watilde** [comment]
@SwaySway I heard the same issue with this thread and could reproduce the issue with the current master. Let me share its log that describes how to reproduce: https://gist.github.com/watilde/5fdc6cb3452fcec2ec94f67262035dd5

**Comment by SwaySway** [comment]
Hi @watilde 
Is this repo for the creation of multiple tables? We could add another resource check to ensure that we can split the creation of tables in an iterative deployment or using the resource manager to create a dependsOn connection. Adding this issue as the feature-request to follow for that work https://github.com/aws-amplify/amplify-cli/issues/2584

Hi @sacrampton 
Aside from multiple create tables, are you experiencing issues with multiple GSI updates? I tried to repro the scenario you mentioned with 14 gsis in one table and I was able to get the deployment working (this table as had records as well).

**Comment by SwaySway** [comment]
Tracking the work for creation of multiple tables in #2584. 
Closing this issue as the CLI has exponential backoff implemented during iterative deployments.
Should you experience any issues related to iterative deployments on an update please comment below.
