### ISSUE TITLE
amplify init gives AccessDenied error - When trying to clone a repo from another creator 

### ISSUE THREAD

**Issue by Kevinberg** [aws-amplify/amplify-cli#7428]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

-

### Amplify CLI Version

-

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

I am trying to init an existing project  where I used ""     amplify init --app  https://github.com/Savinvadim1312/NetflixClone.git   ""     in an empty folder.

Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
**⠦ Initializing your environment: devCould not initialize 'dev': Access Denied**

As this is not working; it does not create an aws export file and I can't run npm start with expo

Any help is highly appreciated!  

### Expected behavior

It creates the files but it does not connect to my aws amplify account and does not create aws export files.

### Reproduction steps

1. Empty Folder
2. install all packages
2. amplify init --app  https://github.com/Savinvadim1312/NetflixClone.git 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by yuth** [comment]
It looks like the https://github.com/Savinvadim1312/NetflixClone.git repo has [`teamproviderinfo.json`](https://github.com/Savinvadim1312/NetflixClone/blob/main/amplify/team-provider-info.json) checked into the repo.  So when you try to init the project with environment name `dev` it is trying to reuse the existing resources. Could you try using a different name for the environment instead of `dev` and see if that works.

**Comment by Kevinberg** [comment]
Hi @yuth , Thanks for your response! tried this in this issue: 

https://github.com/aws-amplify/amplify-cli/issues/7441

Still the same problem but I will close this issue as the other one is the extended version of the issue
