### ISSUE TITLE
Found whitespace in your key name (use quotes to include)

### ISSUE THREAD

**Issue by AyazAI** [aws-amplify/amplify-cli#7429]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

4.44.1

### What operating system are you using?

Lubuntu

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

When trying to run `amplify push --y`, i got the following error

` at line 4,8 >>><<<<<<< HEAD   "defa ... An error occurred during the push operation: Found whitespace in your key name (use quotes to include) at line 4,8 >>><<<<<<< HEAD   "defa ...`

### Expected behavior

It should push the changes

### Reproduction steps

1: Create 2 branches, 2 env's
2: Make changes in 1 branch and 1 env, and push works fine
3: Merge 1st branch in 2nd branch produces error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @AyazAI :wave: could this be caused by a potential merge conflict leftover in one of the files? Do you have the full error with the stack trace you could post?

**Comment by AyazAI** [comment]
Yes, i think this is the result of merge conflict left over.
I will post the full error

**Comment by AyazAI** [comment]
Hi, i noticed that i only get this error while using `amplify push`

`
✖ An error occurred when pushing the resources to the cloud
Found whitespace in your key name (use quotes to include) at line 4,8 >>><<<<<<< HEAD
  "defa ...
An error occurred during the push operation: Found whitespace in your key name (use quotes to include) at line 4,8 >>><<<<<<< HEAD
  "defa ...
`

**Comment by AyazAI** [comment]
Can you tell me which file may include these lines
OR
There is an issue in the cloud?

**Comment by josefaidt** [comment]
@AyazAI thank you for sending the error message. Can you post your schema?

**Comment by yuth** [comment]
The file where the merge conflict is probably in `<project-root>/amplify/backend/api/<api-name>/schema.graphql`. Resolving the merge conflict should resolve this issue

**Comment by AyazAI** [comment]
@yuth I don't think schema would include the conflict!

Schema:

`type User @model {
  id: ID!
  companyuser: CompanyUser @connection
  spuser: SpUser @connection
  finderuser: FinderUser @connection
  adminuser: AdminUser @connection
}

type CompanyUser @model {
  id: ID!
  company: Company @connection
  payment_methods: [PaymentMethod]
    @connection(keyName: "byCompanyUser", fields: ["id"])
  first_name: String
  last_name: String
  phone_number: String
  email: String
  cnic_front: String
  cnic_back: String
  image: String
  location: String
}

type Company @model {
  id: ID!
  sps: [SpUser] @connection(keyName: "byCompany", fields: ["id"])
  subscribed_services: [SubscribedService]
    @connection(keyName: "byCompany", fields: ["id"])
  name: String
  registration_number: String
  date_of_establish: String
  country: String
  city: String
  office_address: String
  secp: String
  fbr: String
  image: String
}
type SpUser
  @model
  @key(name: "byCompany", fields: ["companyID"])
  @key(name: "bySpID", fields: ["id"]) {
  id: ID!
  companyID: ID
  first_name: String
  last_name: String
  phone_number: String
  email: String
  password: String
  gender: String
  date_of_birth: String
  address: String
  profile_picture: String
  aboutyou: String
  video: String
  hours: BussinessHours @connection
  services: [SpAssignedService] @connection(keyName: "bySpUser", fields: ["id"])
  virtualloc: String
  jobs: String

  online: String
  status: String
  approved: Boolean

  rating: String
  earning: String
  lat: String
  lng: String
  convince_type: String
  convinc_number_plate: String
  identity: Identity @connection
  documents: [Document] @connection(keyName: "bySpUser", fields: ["id"])
  category: Category @connection
  sub_category: SubCategory @connection
  sp_category: String
  sp_sub_category: String
}

type Identity @model {
  id: ID!
  cnic: String
  cnic_front: String
  cnic_back: String
  cnic_with_face: String
  police_verification: String
}

type Document @model @key(name: "bySpUser", fields: ["spID", "certificate"]) {
  id: ID!
  spID: ID
  certificate: String
  certificate_date_of_completion: String
  certificate_institute: String
  certificate_image: String
}

type FinderUser @model {
  id: ID!
  first_name: String
  last_name: String
  phone_number: String
  email: String
  password: String
  gender: String
  date_of_birth: String
  address: String
  cnic_front: String
  cnic_back: String
  location: String
  profile_picture: String
  saved_locations: [SavedLocation]
    @connection(keyName: "byFinderUser", fields: ["id"])
}

type SavedLocation
  @model
  @key(name: "byFinderUser", fields: ["finder_user_id"]) {
  id: ID!
  finder_user_id: ID
  name: String
  lat: String
  lng: String
}

type AdminUser @model {
  id: ID!
  first_name: String
  last_name: String
  phone_number: String
  email: String
  password: String
  gender: String
  date_of_birth: String
  address: String
  cnic_front: String
  cnic_back: String
  profile_picture: String
}
type SubscribedService @model @key(name: "byCompany", fields: ["companyID"]) {
  id: ID!
  companyID: ID
  category: String
  sub_category: String
  service: String
  location: String
  type: String
  duration: String
  price: String
  description: String
}

type SpAssignedService @model @key(name: "bySpUser", fields: ["sID"]) {
  id: ID!
  sID: ID
  service_id: ID
  service: Service @connection(fields: ["service_id"])
  category_value: String
  sub_category_value: String
  price: String
  category: String
  sub_category: String`
  location: String
  type: String
  duration: String
  description: String

  sp: SpUser @connection(fields: ["sID"])
}

type SMS @model {
  status: String
}
type BussinessHours @model {
  id: ID
  spID: ID
  monday: [String]
  tuesday: [String]
  wednesday: [String]
  thursday: [String]
  friday: [String]
  saturday: [String]
  sunday: [String]
}

type Category @model {
  id: ID!
  category: String
  sub_category: [SubCategory] @connection(keyName: "byCategory", fields: ["id"])
  color_code: String
  image: String
  status: String
}

type SubCategory
  @model
  @key(name: "byCategory", fields: ["categoryID", "name"]) {
  id: ID!
  categoryID: ID!
  category: Category @connection(fields: ["categoryID"])
  name: String
  services: [Service] @connection(keyName: "bySubCategory", fields: ["id"])
  status: String
}

type Service
  @model
  @key(name: "bySubCategory", fields: ["subCategoryID", "name"]) {
  id: ID!
  subCategoryID: ID!
  subcategory: SubCategory @connection(fields: ["subCategoryID"])
  name: String
  type: [String]
  basis: [String]
  duration: [String]
  max_price: String
  min_price: String
  description: String
  status: String
}

type PaymentMethod
  @model
  @key(name: "byCompanyUser", fields: ["company_user_ID", "type"]) {
  id: ID!
  company_user_ID: ID
  name: String
  email: String
  number: String
  valid_thru: String
  cvc: String
  type: String
  primary: String
}

type Query {
  search(text: String): String @function(name: "search-${env}")
  filter(
    text: String
    location: String
    priceStart: String
    priceEnd: String
    gender: String
    rating: String
  ): String @function(name: "filter-${env}")

  # get unique services to be assigned to sp
  listToBeAssignedServices(spID: String): String
    @function(name: "listToBeAssignedServices-${env}")
}`

**Comment by AyazAI** [comment]
I would have to remove the schema if you have checked the schema!

**Comment by AyazAI** [comment]
I have tried Vs Code Find in Folder feature to find `>>><<<<<<<,` but nothing found in the project

**Comment by AyazAI** [comment]
I am constantly merging from dev(working) into test(not working) branch, but it's giving me this error. Eventually, I have to checkout to dev and push to test env.

**Comment by johnpc** [comment]
Could it be related to https://github.com/aws-amplify/amplify-cli/issues/7397?

**Comment by AyazAI** [comment]
@johnpc Yeah probably

**Comment by AyazAI** [comment]
Well, I have assumed you have seen the schema and there is no issue with schema.graphql. If you need that at any point, do let me know!

**Comment by josefaidt** [comment]
Hey @AyazAI yes thank you for posting your schema I was able to take a look at it. What kind of changes were made in the other branch? Here is the procedure I've followed:

1. create project, environment prod, create git
2. add GraphQL api with auth, push to amplify and git
3. create and checkout new git branch `next`, create new amplify environment `dev`
4. modify schema and push changes to amplify and git
5. checkout main branch
6. checkout prod amplify env
7. merge `next` into `main`
8. push changes to amplify prod environment

If you search for `<<<<<<< HEAD` does anything show up? I believe the first few `>>>` characters are from the error message

**Comment by AyazAI** [comment]
Hey @josefaidt,

I have 3 branches (dev, test, master) and 3 amplify env's (dev, test, prod)
The flow I usually follow is to make changes in **dev**, test them in **test**, and make them live in **master**.
While following the normal flow I had to merge changes from **dev** into **test**. While all of sudden the error came in the **test** branch and I can't push anything from the test branch. There is some error or conflict error in that branch.
1: I have tried to search in the folder to find `>>>`, nothing found
2: I can even create new categories in that branch but can't push them in the cloud

**Comment by josefaidt** [comment]
Thanks for the information @AyazAI were you able to find anything searching for `<<<<<<< HEAD`?

**Comment by AyazAI** [comment]
I haven't found anything while searching for `<<<<<<< HEAD` !

**Comment by josefaidt** [comment]
This is only affecting the `test` branch? In your `test` branch could you try restoring the Amplify environment with `amplify env checkout test --restore` or `amplify env pull test --restore` (assuming `test` is also the name of the environment in Amplify, then re-attempt the merge from `dev`?

**Comment by josefaidt** [comment]
Sure! `checkout` will switch envs and overwrite local changes, where `pull` will pull that env onto the env you currently have checked out.

**Comment by AyazAI** [comment]
Thank you soo much @josefaidt, the problem has been resolved by `amplify env pull test --restore`
