### ISSUE TITLE
Cannot amplify push with error: 'Resource xxxxxx must be in ARN format or "*".' on dynamodb stream.

### ISSUE THREAD

**Issue by taskooh** [aws-amplify/amplify-cli#7430]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

4.51.4

### What operating system are you using?

Mac

### Amplify Categories

storage, function

### Amplify Commands

update

### Describe the bug

`StreamArn` dependencies in amplify-meta.json is removed in `amplify function update`

Then, the error happens while `amplify push`

```
Resource storageTransactionArn must be in ARN format or "*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: xxxx; Proxy: null)
```

### Expected behavior

Able to `amplify push` without any errors.

### Reproduction steps

1. run`amplify update storage` and add new trigger function

![image](https://user-images.githubusercontent.com/20131692/120148077-a18d4a00-c222-11eb-9fbc-2addf717ad3d.png)

after running, in amplify-meta.json:
```
"TransactionTrigger573ac743": {
      "service": "Lambda",
      "providerPlugin": "awscloudformation",
      "build": true,
      "dependsOn": [
        {
          "category": "storage",
          "resourceName": "Transaction",
          "attributes": [
            "Name",
            "Arn",
            "StreamArn"
          ]
        }
      ],
      "lastPushTimeStamp": "2021-05-31T06:11:22.537Z"
    }
```

2. run`amplify update function` and update resource permission of table
![image](https://user-images.githubusercontent.com/20131692/120148618-79eab180-c223-11eb-8782-f9430688ba83.png)

after running, in amplify-meta.json:
```
    "TransactionTrigger573ac743": {
      "service": "Lambda",
      "providerPlugin": "awscloudformation",
      "build": true,
      "dependsOn": [
        {
          "category": "storage",
          "resourceName": "Transaction",
          "attributes": [
            "Name",
            "Arn"
          ]
        }
      ],
      "lastPushTimeStamp": "2021-05-31T06:17:55.787Z"
    }
```

and  "StreamArn" is removed.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by taskooh** [comment]
Related to closed issue https://github.com/aws-amplify/amplify-cli/issues/5333, But still not fixed in latest version.

**Comment by realityworks** [comment]
Same here... had to revert and add the resources manually with the full ARN reference.

**Comment by realityworks** [comment]
@luhanamz we need an urgent fix on this. :/

**Comment by realityworks** [comment]
Update to 5.1.0, still have the same issue.

**Comment by realityworks** [comment]
The problem ended up being the following format in the **lambdaExecutionPolicy** of the cloud formation policy >

```
"Parameters": {
    ...
    "storagefeedName": {
      "Type": "String",
      "Default": "storagefeedName"
    },
    "storagefeedArn": {
      "Type": "String",
      "Default": "storagefeedArn"
    }
    ...
    ...
   "lambdaexecutionpolicy": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "lambda-execution-policy",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "dynamodb:DescribeTable",
                "dynamodb:GetItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:PutItem",
                "dynamodb:UpdateItem",
                "dynamodb:DeleteItem"
              ],
              "Resource": [
                {
                  "Ref": "storagefeedArn"
                },
                {
                  "Fn::Join": [
                    "/",
                    [
                      {
                        "Ref": "storagefeedArn"
                      },
                      "index/*"
                    ]
                  ]
                }
              ]
   ...
```

**Comment by edwardfoyle** [comment]
The latest version of the CLI (5.1.0) has a fix for `StreamArn` being removed from the `dependsOn` block when updating the function permissions.

@realityworks I'm unable to reproduce the issue you're seeing with 5.1.0. What does the function block within the `backend-config.json` file in your project look like?
