### ISSUE TITLE
How to recreate Elasticsearch instance created by the `@searchable` ?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7438]
**Which Category is your question related to?**
API

**Amplify CLI Version** 

4.52.0

**Provide additional details e.g. code snippets**
Suddenly, one of my searchXXX API stop working, but the search API for other models was fine, I don't know what's the problem, I've checked the Elasticsearch console, and found that some of my schema in graphql doesn't match with the one on the Elasticsearch.

I've tried to delete the `@seachable` directive, but the corresponding index on the Elasticsearch didn't get deleted.
So how could I recreate the Elasticsearch instance without creating a new amplify env?

**Comment by yuth** [comment]
`@searchable` directive creates one Elastic Search cluster per API. Removing `@searchable` directive from one of the `@model` will not remove the index. You would have to run custom script to create an new index as shown in this [gist](https://gist.github.com/SwaySway/41548b31f48b00dc18080c08d1583601)

**Comment by renebrandel** [comment]
Closing this for now as it didn't get much traction.
