### ISSUE TITLE
Missing file/directory upon initial installation of Amplify cLi

### ISSUE THREAD

**Issue by acnowland** [aws-amplify/amplify-cli#7454]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

Unable to complete - npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

15.7.0

### Amplify CLI Version

...

### What operating system are you using?

Mac Big Sur 11.2

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Upon installation with command `npm install -g @aws-amplify/cli` I get the following errors: 

`npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/adamnowland/.nvm/versions/node/v15.7.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-cdk/bin/cdk
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/adamnowland/.nvm/versions/node/v15.7.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-cdk/bin/cdk'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adamnowland/.npm/_logs/2021-06-03T22_03_10_118Z-debug.log`

### Expected behavior

Complete installation

### Reproduction steps

1. utilizing npm install -g @aws-amplify/cli`
2. utilizing sudo npm install -g @aws-amplify/cli`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by yuth** [comment]
@acnowland Does the installation fail use a different version of Node in NVM? Also could you try updating NPM to latest version and see if the issue still persists?
