### ISSUE TITLE
Unable to modify backend auth resources

### ISSUE THREAD

**Issue by jmarshall9120** [aws-amplify/amplify-cli#7458]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d10f4nc5uip2ry

### Region

us-west-1

### Amplify Console feature

Backend builds

### Describe the bug

Cannot edit Auth whatsoever.

Any attempt to edit or remove my auth ends with this error after `amplify push`:

```
Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

I've seen many other issues suggesting to pull the repo, but this is not a sync issue in my case.  I've pulled, pushed, it doesn't matter, the issue cannot be fixed that way. 

### Expected behavior

```
amplify auth update
....change some setting...
amplify push y
```
should successfully update

```
amplify auth remove y
amplify push y
```
The above commands should remove my Auth.

I'm afraid that all I can do is delete my project completely and start over.  The fact that this is possible makes it maybe a little to risky to use Amplify in the first place.  Hopefully this can be resolved without that. 

### Reproduction steps

No Idea

**Comment by jmarshall9120** [comment]
Hi @siegerts , 

1. `amplify -v` = 4.52.0
2. The project was created using the CLI, however certain aspects were edited in the Cognito user pool UI.
3. You caught me, I put the wrong command in the question.  I've edited it.  In my testing I used the correct command
   `amplify auth remove`

**Comment by jmarshall9120** [comment]
Based on the issue I'm seeing in cloud formation I've tried several methods now to update my GraphQL Api, which I did find was expired.
    1. I've added the line
         `"APIKeyExpirationEpoch": "-1"`
        to my amplify > api > myApi > parameters.json
    2. I've edited my API key in AppSync > myApi > settings to no longer be expired.

Still no change.

**Comment by jmarshall9120** [comment]
logged in to mess with this to see this today:

![image](https://user-images.githubusercontent.com/30184747/120909970-97f35000-c62f-11eb-9abe-c82cd68ef8a5.png)

Not sure I'm making progress here...

**Comment by yuth** [comment]
If you want to delete the API Key created by amplify CLI you would have to set `CreateAPIKey` to `0`. The parameters GraphQL transformer accepts are documented [here](https://docs.amplify.aws/cli/graphql-transformer/config-params#createapikey). 

You could also try to extend the API Key expiration time by running `amplify update api` and updating auth settings for the API.

When the API Key extension done using the AppSync console does it using control plane and does not sync with Amplify CLI as it uses Cloudfomration for managing resources.

**Comment by jmarshall9120** [comment]
@yuth - I can't run amplify auth update.  That's the whole problem here.  My updates won't go through

**Comment by jmarshall9120** [comment]
Hey all, I closed this.  Though I'm quite worried about the fact this kind of lock up is possible, I've deleted the amplify project and started over.  I have to make the decision to move forward.  Thanks all for your time.
