### ISSUE TITLE
How to create data source and attach resolver in appSync with amplify-cli

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#746]
** Which Category is your question related to? **

appSync

** Provide additional details e.g. code snippets **

Hi :) I would like to create data source for appSync and attach it as a resolver.
Is it possible? If so how do I do it??
If not, should I use AppSync console for now??

**Comment by kaustavghosh06** [comment]
@bokuweb  We don't have support for custom resolvers and custom data sources yet but we're actively working on it. Take a look at #574

**Comment by bokuweb** [comment]
thanks!

**Comment by morgler** [comment]
Since there is support for customer resolvers now: when will custom data sources (i.e. REST APIs) be supported?
