### ISSUE TITLE
Ability to add connection on non model types

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#7462]
### Is this related to a new or existing Amplify category?

api

### Is this related to another service?

AppSync

### Describe the feature you'd like to request

We would like to be able to use `@connection` directive on type's that don't have an `@model` directive defined directly on the. This type is an intemediary type that exists on a parent type that does have `@model`. 

### Describe the solution you'd like

Be able to do this:

```gql

type Customer @model {
  id: ID!
  orderItemSet: OrderItemSet
}

type OrderItemSet {
  items: [Item] @connection
  otherCollection: [Other]
}
```

### Describe alternatives you've considered

Handwritten function instead

### Additional context

InvalidDirectiveError: @connection must be on an @model object type field.

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by yuth** [comment]
@kldeb when a type is not a `@model` the values are stored inline in the table where this field is used. So in this above case, `orderItemSte` is stored in `Customer`, since the values are stored in customer object, we can't use `@connection`
