### ISSUE TITLE
Unable to remove model/table

### ISSUE THREAD

**Issue by tkang** [aws-amplify/amplify-cli#7465]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.11.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I removed a model from schema.graphql file and ran ‘amplify push —y’ to apply changes

I’m getting the following error.
```
Cannot convert undefined or null to object
An error occurred during the push operation: Cannot convert undefined or null to object
```

### Expected behavior

`amplify push --y` command should run with no issues.
model/table should be removed

### Reproduction steps

1. Add a model in schema.graphql (e.g. 'Company')
2. Run `amplify push --y` to apply change. Make sure a DynamoDB table is created (e.g. CompanyTable)
3. Remove the model we added in step 1 from schema.graphql
4. Run `amplify push --y` => This is where we get errors.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I also have a lambda function.
I removed it with `amplify remove function` and `amplify push --y`and then things work as expected (I removed the model from my schema.graphql and ran `amplify push --y` and it works)

**Comment by MontoyaAndres** [comment]
I have the exact same problem, also I did an issue about it: https://github.com/aws-amplify/amplify-cli/issues/7466

**Comment by jhockett** [comment]
Closing this as a duplicate in favor of https://github.com/aws-amplify/amplify-cli/issues/7466.
