### ISSUE TITLE
Cannot delete a table with the CLI: `Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by MontoyaAndres** [aws-amplify/amplify-cli#7466]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Ubuntu

### Amplify Categories

api

### Amplify Commands

codegen, push

### Describe the bug

I want to delete a table with CLI just removing the Type @model, but I can't.

I have defined the table like this:

```
type Feedback @model(subscriptions: null) {
  id: ID!
  stars: Int
  comment: String
  fromId: ID!
  toId: ID!
}
```

Then, I just wanted to remove it by deleting that @model from the `Schema.graphql`. But I got this error:

![image](https://user-images.githubusercontent.com/15065852/120932263-b3f00380-c6ba-11eb-8f55-561d6c6ad46a.png)

### Expected behavior

Delete table and resolvers.

### Reproduction steps

I have created the @model like any other.

Just added the @model in the Schema.graphql:

```
type Feedback @model(subscriptions: null) {
  id: ID!
  stars: Int
  comment: String
  fromId: ID!
  toId: ID!
  hola: String!
}
```

Then I did `amplify push --y` and works great, then I deleted from the Schema.graphql and I got the previous error.

**Comment by o-gi** [comment]
I have same problem
It's happening suddenly

**Comment by jhockett** [comment]
Hi @MontoyaAndres @o-gi @tkang, so far I haven't been able to reproduce. Can you each please tell me more about your graphql api's? Are you using auth? If so, any auth triggers?

I tried to reproduce with a GraphQL API with default options, but I was able to delete two different tables by removing the types from my schema and running `amplify push`

```
amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: ddbtest
? Choose the default authorization type for the API API key
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): 7
? Do you want to configure advanced settings for the GraphQL API No, I am done.
```

**Comment by MontoyaAndres** [comment]
@jhockett I can share you the Amplify folder in any email if you'd like. To check the cloud formation templates.

**Comment by jhockett** [comment]
That would be great @MontoyaAndres. Please send it to amplify-cli@amazon.com after redacting any sensitive information.

**Comment by MontoyaAndres** [comment]
@jhockett sent. Let me know if you received it.

**Comment by MontoyaAndres** [comment]
The title of the email is `Issue #7466 Amplify folder - Andrés Montoya`

**Comment by jhockett** [comment]
Got it, thank you @MontoyaAndres!

**Comment by tkang** [comment]
My situation when I had this issue was when I had (1) auth (2) function (3) api enabled.
After I removed function, I was able to remove a table/model.

**Comment by MontoyaAndres** [comment]
@tkang I don't have any function related to this table :/. Maybe if you explain better what you did to fix it can help us 👍🏻 .

**Comment by MontoyaAndres** [comment]
Hey, @jhockett the amplify folder I sent you worked for you :)? We still have this problem :(

**Comment by josefaidt** [comment]
Hey @MontoyaAndres would you mind restoring it to your drive or send the amplify folder again?

**Comment by MontoyaAndres** [comment]
@josefaidt you can find the email with the title "Issue #7466 Amplify folder - Andrés Montoya"

**Comment by josefaidt** [comment]
Thank you @MontoyaAndres I received it!

**Comment by dylan-westbury** [comment]
I have this issue also. I have removed any functions, connections and also access to resources for a table before I delete, but this error shows.

**Comment by dylan-westbury** [comment]
I just created a new environment as a workaround for now. We don't have anything in production yet.

**Comment by josefaidt** [comment]
Hey @dylan-westbury and @MontoyaAndres we have identified the bug and will be submitting a PR to fix this!
