### ISSUE TITLE
nodjs update to 12 for Lambda UpdateRolesWithIDPFuncti...

### ISSUE THREAD

**Issue by al3x88** [aws-amplify/amplify-cli#7469]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
amplify lambda 

**Amplify CLI Version** 
4.22.0

**What AWS Services are you utilizing?**
I am using S3 with iOS Amplify.
The 2 Lambda functions called:
- UpdateRolesWithIDPFuncti..
- UserPoolClientLambda

that have been created automatically with the installation process, must be update to Nodejs 12 or higher ( aws end of service policy).
Is there a safe way to do it? 

**Provide additional details e.g. code snippets**

**Comment by jhockett** [comment]
Hi @al3x88, can you update to the latest version of Amplify CLI? The newer version will upgrade your functions automatically for you.

**Comment by al3x88** [comment]
Hi @jhockett ! Updating Amplify cli will require to update cocoa pod Amplify as well ?
I am just worried to break up my uploading controller on iOS....

**Comment by akshbhu** [comment]
Hi @al3x88 

You can update to amplify cli latest version 4.52.0 and lambda runtime migration for these will be done automatically. updating to latest version also wont affect your project.

**Comment by mrducky4** [comment]
I am also trying to get these lambda functions updated from runtime nodejs10.x. What is the workflow to get these lambda functions updated after I update my amplify cli version? I tried `amplify pull` then `amplify push` but it just says there are no changes detected and it doesn't do anything.

**Comment by jhockett** [comment]
@mrducky4 the Lambda functions will automatically update the node version when pushed with an update. You can add a comment or add a newline to your source code to trigger change detection. You can also bump the version listed in your Lambda function's `package.json` to achieve the same result.

**Comment by akshbhu** [comment]
Can you check whats your project version in ```amplify/.config.project-config.json? 
amplify migration happens when you a push if project version is less than 3.1.

Also can you tell me what files in your project are currently on old nodejs runtime?

**Comment by mrducky4** [comment]
@jhockett what source code? These lambda functions are created by amplify and I have no idea what they do. The two function names are:

- amplify-<project name>-UserPoolClientLambda-<some code>
- amplify-<project name>-UpdateRolesWithIDPFuncti-<some code>

These functions seem to be associated with my Auth resource that uses a Cognito user pool. From cloudwatch logs, it seems like these functions were invoked exactly once when I deployed the project long ago, so I'm not sure if they are even relevant after initial deployment.

I can't find any `package.json` for these functions, so I don't know how to follow your instructions. Please help.

**Comment by mrducky4** [comment]
@akshbhu my project-config.json has version 3.1. amplify-cli updated this, as the version that is committed in my repo is 3.0.

I don't know about "what files in my project are on the old runtime".  All I know is the lambda function names, see my previous comment, which are also the same as the functions in the original post that started this issue.

Thank you for helping.

**Comment by mrducky4** [comment]
Can anybody tell me if these lambda functions that amplify creates have any use after initial deployment? Is it even worth it to try to upgrade the nodejs runtime? Is it safe to just update the runtime version in the AWS Lambda Console?

- `amplify-<project name>-UserPoolClientLambda-<some code>`
- `amplify-<project name>-UpdateRolesWithIDPFuncti-<some code>`

Thanks for any additional guidance you can provide.

**Comment by kaustavghosh06** [comment]
@al3x88 are you still blocked on this issue?
@mrducky4 These Lambda resources are Custom AWS Lambda resources used to configure/update resources for which there isn't any native CloudFormation support. This would be used when you decide to update/delete your AWS resources which is managed by these Lambda custom resources.

**Comment by kaustavghosh06** [comment]
Closing this issue as the migration for the latest node version is covered as a part of the latest version of the CLI. Please let me know if you're still stuck on this or have more questions.
