### ISSUE TITLE
Amplify Push - An error occurred during the push operation: EACCES: permission denied

### ISSUE THREAD

**Issue by venkatabhilashchavala** [aws-amplify/amplify-cli#7470]
Hello,

I am using amplify CLI version - 4.52.0

When I run the command amplify push, it is through the below error message. 

`✖ There was an error pulling the backend environment staging.
An error occurred during the push operation: EACCES: permission denied, unlink '..../amplify/#current-cloud-backend/amplify-meta.json'`

tried clearing the npm cache still no luck.

Looking forward to the suggestions on how to fix the error.

Thank you

**Comment by jhockett** [comment]
Hi @venkatabhilashchavala, please provide some additional information so we can better help debug the issue.

How did you install the Amplify CLI? (npm or curl)
-If npm, did you install it globally? Did you use `sudo`?

What OS are you using?

If you navigate to the `#current-cloud-backend` folder and run `ls -al`, what's the output you see?

**Comment by venkatabhilashchavala** [comment]
macOS, npm install for amplify CLI.  did it globally without sudo

**Comment by akshbhu** [comment]
Hi @venkatabhilashchavala 

This seems like a permission issue. Can you also check permissions of `#current-cloud-backend` folder?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further correspondence. 
Issue can be narrowed down to customer filesystem permission issue.
