### ISSUE TITLE
Graphql API connection between models

### ISSUE THREAD

**Issue by dreamhigh915** [aws-amplify/amplify-cli#7472]
Hi everyone.

Now, I'm trying to get such json object from Graphql API.
`{
  user: {
    id: ID,
    name: String,
    friends: {
      user: {
        id: ID,
        name: String
      },
      user: {
        id: ID,
        name: String
      },
      user: {
        id: ID,
        name: String
      },
    }
  }
}`

For this, how do I need to draw my schema?

I'll appreciate it if anyone could give me a solution for this.

Thanks for your attention.

**Comment by jhockett** [comment]
Hi @dreamhigh915, check out the documentation for GraphQL: https://docs.amplify.aws/cli/graphql-transformer/overview

If you're still stuck, questions like these are better suited for our [community discord server](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#community).

**Comment by dreamhigh915** [comment]
OK
