### ISSUE TITLE
IOS simulator cannot connect to development server.

### ISSUE THREAD

**Issue by jinchenxiangdan** [aws-amplify/amplify-cli#7473]
**Which Specific Feature is your question related to?**

I tried to pull the frontend code from Github and `amplify pull` the deployment from the admin UI, but after I ran `yarn start`, it shows the cannot connect to the development server, the screenshot is shown below:

![image](https://user-images.githubusercontent.com/18094294/111553261-395dba80-8741-11eb-8b06-84ee82879f54.png)
And at the same time, the terminal returns this error:

```
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/user/Projects/TKC/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/user/Projects/TKC/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 7)

```

The only change I made is the `amplify/.config/local-env-info.json`. I changed `projectPath` to my local one, if I don’t make this change, amplify pull would cause the error: 
```
✖ There was an error initializing your environment.
File at path: '../amplify/team-provider-info.json' does not exist
```

But this doesn’t affect the error that I am having, the only thing that causes this error is after running `amplify pull —appid —envName dev`

and the interesting thing is it works perfectly through `run in web browser`.

**Provide additional details e.g. code snippets**

1. This is a react-native project.
2. Project's folder name on Github is different from the project name that initialized by using `amplify init`

**Comment by josefaidt** [comment]
Hey @jinchenxiangdan :wave: thanks for raising this and apologies for the delay! Are you still experiencing this issue when running `amplify pull` from the root of your project without specifying the appId and envName, and can you confirm the new `projectPath` is a valid, absolute path to your local project files?
