### ISSUE TITLE
amplify push "Packaging lambda failed function failed."

### ISSUE THREAD

**Issue by yiweixia** [aws-amplify/amplify-cli#7474]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Amplify Categories

storage, function, api

### Amplify Commands

push

### Describe the bug

After running `amplify push`, after confirming the changes I want to push, I get the following error 
`Packaging lambda failed function failed. Could not find npm executable in the PATH.`

The npm executable is definitely on my path, so I'm not sure why it fails. However, the issue goes away after an `amplify env checkout`.

### Expected behavior

`amplify push` succeeds.

### Reproduction steps

1. `git pull`ed our amplify package from master.
2. Make changes to schema.graphql (add two non-required fields to existing table)
2. `amplify push`
3. `y` when asked to confirm that I want to push changes.
4. get the error, "Packaging lambda failed function failed. Could not find npm executable in the PATH."

### GraphQL schema(s)

<details>
Added two new fields to existing table, (names have been changed)

```graphql

    newFieldA: AWSDateTime @auth(rules: [
        {allow: groups, groups: ["admin"],  operations: [create, update, read]},
        {allow: private, provider: iam, operations: [create, read, update, delete]}
    ])
    newFieldB: AWSDateTime @auth(rules: [
        {allow: groups, groups: ["admin"],  operations: [create, update, read]},
        {allow: private, provider: iam, operations: [create, read, update, delete]}
    ])

```

</details>

**Comment by jhockett** [comment]
Hi @yiweixia, do you use a node version manager like nvm? What version of npm is installed?

> However, the issue goes away after an `amplify env checkout`.

After running checkout, are you able to push changes to your schema?

**Comment by yiweixia** [comment]
Nope, don't have nvm installed. Using npm version 6.14.13.

>After running checkout, are you able to push changes to your schema?

Yeah, push succeeds and everything is working fine after `amplify env checkout`, so I'm not being blocked. It's just a weird issue that popped up.

**Comment by akshbhu** [comment]
Closing this issue as it seems to be working , if it fails with same error , comment on it and we will open this again
