### ISSUE TITLE
amplify push should run pre-build scripts before deteching changes

### ISSUE THREAD

**Issue by connor4312** [aws-amplify/amplify-cli#7478]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.3.0

### Amplify CLI Version

4.51.4

### What operating system are you using?

Windows

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

1. Have a repo set up where functions are compiled by build scripts in the root package.json
2. Have a function that imports things outside its working directory as part of its build step
3. Change one of these things
4. Run `amplify push`
5. Amplify does not detect any changes 🐛 

### Expected behavior

If a build script is configured, it should be executed before detecting changes.

### Reproduction steps

See above

**Comment by xo28122000** [comment]
Hi @connor4312,
Can you please describe your use-case more.

**Comment by connor4312** [comment]
Sure, I build functions using a bundler (esbuild) and have common code that's shared between them--outside of their folders. These are built by having a script `amplify:<function name>` in the root package.json. Changing this shared code will caused the compiled version to be changed, but because `amplify push` doesn't build before trying to detect changes, I need to manually do so in order for a push to work.

**Comment by xo28122000** [comment]
> Sure, I build functions using a bundler (esbuild) and have common code that's shared between them--outside of their folders. These are built by having a script `amplify:<function name>` in the root package.json. Changing this shared code will caused the compiled version to be changed, but because `amplify push` doesn't build before trying to detect changes, I need to manually do so in order for a push to work.

So would having access to runtime hooks, that can always execute right before `amplify push`, be useful in this case? For this hook you can provide a script that builds resources and Amplify would run this script before every push. Would this potentially solve your issue?

**Comment by connor4312** [comment]
Yep

**Comment by xo28122000** [comment]
Hi @connor4312 
I just released an RFC for runtime hooks: #7614 
It would be really helpful if you can leave some comments!

**Comment by connor4312** [comment]
Looks good overall, I think that works for me. Feel free to close this issue if there's nothing outstanding you'd like to do otherwise.

**Comment by lazpavel** [comment]
closing this ticket in favor of [runtime hooks](https://docs.amplify.aws/cli/usage/command-hooks/)
