### ISSUE TITLE
amplify import storage for DynamoDB: "not authorized to perform: dynamodb:ListTables on resource"

### ISSUE THREAD

**Issue by 9037568** [aws-amplify/amplify-cli#7485]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.52.0

### What operating system are you using?

Windows

### Amplify Categories

storage

### Amplify Commands

add

### Describe the bug

When executing `amplify import storage`, I select "DynamoDB table" and the operation fails with this error.

I see a couple of things in this error that seem weird to me:
-    "assumed-role" : why is a role being assumed?
-    The role apparently assumed seems to not have the access it claims to have: `Full-access`

### Expected behavior

The `import storage` command should succeed.

### Reproduction steps

Run `amplify import storage`
Select DynamoDB Table

### Log output

<details>

```
User: arn:aws:sts::[redacted]:assumed-role/us-east-1_AiDvjECeo_Full-access/amplifyadmin is not authorized to perform: dynamodb:ListTables on resource: arn:aws:dynamodb:us-east-1:[redacted]:table/*
AccessDeniedException: User: arn:aws:sts::[redacted]:assumed-role/us-east-1_AiDvjECeo_Full-access/amplifyadmin is not authorized to perform: dynamodb:ListTables on resource: arn:aws:dynamodb:us-east-1:[redacted]:table/*
    at Request.extractError (C:\snapshot\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\snapshot\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\snapshot\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\snapshot\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\snapshot\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\snapshot\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\snapshot\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (C:\snapshot\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (C:\snapshot\node_modules\aws-sdk\lib\event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

</details>

**Comment by akshbhu** [comment]
Hi @9037568 

Can you add this policy ```dynamodb:ListTables``` to your  IAM user configured with CLI ?

let me know if this works?

**Comment by 9037568** [comment]
@akshbhu:
>Can you add this policy dynamodb:ListTables to your IAM user configured with CLI ?

Won't help, because that user already has that permission:

![image](https://user-images.githubusercontent.com/9916473/121980625-4303b800-cd5a-11eb-9cfe-a837906c88a7.png)
![image](https://user-images.githubusercontent.com/9916473/121980697-6af31b80-cd5a-11eb-9abd-e61439e3e0ea.png)

**Comment by kaustavghosh06** [comment]
@9037568 Did you authenticate using the Admin UI? In your IAM console, can you check if this IAM role - "us-east-1_AiDvjECeo_Full-access" has the "dynamodb:ListTables" IAM policy listed? If you'd want to use a local AWS profile tied to your IAM user described above instead, you can run `amplify configure project` and use this IAM user/Profile.

**Comment by 9037568** [comment]
"us-east-1_AiDvjECeo_Full-access" does not have that permission.

The question remains: why is a role being assumed when none should be assumed?

You also said:

```
If you'd want to use a local AWS profile tied to your IAM user described above instead, you can run amplify configure project and use this IAM user/Profile.
```

But my project is already configured that way, and the configuration is being ignored.

**Comment by kaustavghosh06** [comment]
@9037568 There are multiple ways to authenticate your Amplify Project. The two in question are:
1. Amplify Admin - which uses short-term Cognito credentials. The Cognito resources and IAM roles are generated in your AWS account as a part of the Admin UI setup. This allows for developers on team to authenticate via Admin UI directly who don't necessarily have access to an AWS account. More information out here -  https://docs.amplify.aws/console/adminui/extend-cli
At some point, you must've run amplify pull and authenticated via the Admin UI and hence it's assuming the  IAM role generated as a part of the setup process. 

2. IAM user used as a part of the AWS Profile: This is the user that you were referring above.
If you'd like to see, which authentication method your project is using, you can go into <project-root>/amplify/.config/local-aws-info.json file. 

If it is set to :
```json
{
    "configLevel": "amplifyAdmin"
}
```

and if you want to use your AWS Profile/IAM user - you can change it to:
```json
{
    "configLevel": "project",
    "useProfile": true,
    "profileName": <your-profile-name>
  }
```

**Comment by 9037568** [comment]
If I change the json file like that, I get this error:

Failed to get profile: Profile configuration is missing for: amplify-admin

**Comment by 9037568** [comment]
And now, thanks to this change, the project is broken again. 

After changing back to the original contents, the `amplify status` command is failing with this output:

```
? Select the authentication method you want to use: (Use arrow keys)
> Amplify Admin UI
  AWS profile
  AWS access keys
```

**Comment by kaustavghosh06** [comment]
What does your `~/amplify/.config/local-aws-info.json` look like now?

The profile name you entered - is that valid and present in your ~/.aws/.credentials and ~/.aws/.config folder?

**Comment by 9037568** [comment]
The file has been restored to what it was originally, so theoretically everything should be working the same as before.

```
{
    "configLevel": "amplifyAdmin"
}
```

But now I get that "Select the authentication method" dialog on every request

**Comment by 9037568** [comment]
This comment exists to tell the "stale bot" what to go do with itself.

**Comment by josefaidt** [comment]
Hey @9037568 :wave: apologies for the delay! I've confirmed I was also able to reproduce this when using `amplifyAdmin` to authenticate. Marking this as a bug to add `dynamodb:ListTables` to the Amplify Admin user.

As a workaround we can run `amplify configure project` and make selections to the prompts as follows:

```
? Which setting do you want to configure? AWS Profile setting
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

For the awscloudformation provider.
? Do you want to set the project level configuration Yes
? Select the authentication method you want to use: AWS profile
```

This will allow us to choose an AWS profile to authenticate with rather than the Amplify Admin user.

**Comment by edwardfoyle** [comment]
We are in the process of adding `dynamodb:ListTables` to the `AdministratorAccess-Amplify` managed policy (this is the policy that is attached to the Admin UI Role).

**Comment by sachscode** [comment]
dynamodb:ListTables is added to AdministratorAccess-Amplify , hence this issue can be closed.
