### ISSUE TITLE
Lambda layer change not detected (only package.json)

### ISSUE THREAD

**Issue by frank-unovica** [aws-amplify/amplify-cli#7489]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.52.0-alpha.0

### What operating system are you using?

ubuntu

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Lambda layer change is not detected for node.js, only the hash of package.json is considered.

### Expected behavior

I'm sharing code among lambda functions; it should update when I make a change.

### Reproduction steps

1. Write lambda layer
2. put a .js file in the layer
3. amplify push; the first time it will create the layer and correctly include the files, which can be imported by lambda functions through /opt/nodejs/
4. change the .js file and push again; it won't detect a change.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

See hashLayerVersionContents function (amplify-cli/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts/)

**Comment by jhockett** [comment]
Hi @frank-unovica, this is intentional. If we hash all js files in your Lambda layer it can become very slow when a layer has more than a few small dependencies. As an alternative, you can put your custom modules in the `/opt` folder, and in your Lambda function import from `/opt/<path-to-your-file>`.

**Comment by frank-unovica** [comment]
Thanks, I'll do that, but it would be sufficient to just exclude node_modules and include other files. The opt directory seems to be undocumented.

**Comment by jhockett** [comment]
The `/opt` folder is mentioned during the `add function` flow by the CLI, but I agree we should have better documentation around it. Thanks for pointing this out @frank-unovica!
