### ISSUE TITLE
Failed to create models in the cloud: Modelgen job creation failed AWS Amplify Push

### ISSUE THREAD

**Issue by ChadBradThad** [aws-amplify/amplify-cli#7491]
**Which Category is your question related to?**
amplify push, Amplify CLI

**Amplify CLI Version** 
4.51.2

**What AWS Services are you utilizing?**
AWS Amplify

**Provide additional details e.g. code snippets**
I have been trying to perform an `amplify push`. Previously I was getting an error message regarding `cannot have 1:1 optional connections between models`, which I fixed and believed it would fix the failed message I was getting, but was not the case.

I am seeing the following message every time I perform an `amplify push`:

```
⠇ Updating resources in the cloud. This may take a few minutes...Successfully generated models. Generated models can be found in /Users/name/Documents/Project/ProjectAbbreviation/
**Failed to create models in the cloud: Modelgen job creation failed**
✔ All resources are updated in the cloud
```

My questions are:
1. How big of an issue is getting the message `Failed to create models in the cloud: Modelgen job creation failed`?
2. What exactly does it mean?
3. Any tips for resolving it?

**Comment by jhockett** [comment]
Hi @ChadBradThad, can you share your GraphQL schema?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further requested information.
