### ISSUE TITLE
Make the first field in @key directive mandatory in a query for GraphQL

### ISSUE THREAD

**Issue by AndyW22** [aws-amplify/amplify-cli#7499]
### Is this related to a new or existing Amplify category?

api

### Is this related to another service?

Appsync

### Describe the feature you'd like to request

When specifying a key: ``` @key(name: "getGameDataByTitle", fields: ["title"], queryField: "getGameDataByTitle")``` in a GraphQL type, an input for "title" should be in the query since without it the query will return a dynamoDB error. This is the same reason that for the premade queries with @model, the "id" field is required.

Currently, the "title" field is not required when making a query: 
![image](https://user-images.githubusercontent.com/76787794/121514494-fcbdfa00-c9e3-11eb-9d4f-fcba8223135f.png)

I dont think theres any reason it shouldn't be required since the query will always return an error if you don't provide an argument for "title".

This is also misleading for someone using the graphiql explorer as it would appear there is a bug when in fact they just needed to provide the field.

### Describe the solution you'd like

the first item in `fields` for the @key directive requires an input when making a query.

### Describe alternatives you've considered

No alternative for this.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by sundersc** [comment]
@AndyW22 I can confirm that I can reproduce the issue on my end. We will look into this.
