### ISSUE TITLE
Unable to deploy lambda function to new environment in different region.

### ISSUE THREAD

**Issue by greendinosaur** [aws-amplify/amplify-cli#7501]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.6.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I have created a new environment with a different name in a different AWS region from my current environment.  

I am unable to push changes through to this new environment. Specifically, the lambda functions are failing to be deployed successfully. 

When I execute `amplify push` to the new environment, I get the following error in my console:

`Reason: Resource handler returned message: "Layer version arn:aws:lambda:ap-southeast-1:XXXXXXX:layer:imagery-mydev:1 does not exist. (Service: Lambda, Status Code: 400, Request ID: XXXXXX, Extended Request ID: null)" (RequestToken: YYYYY HandlerErrorCode: InvalidRequest)`

I have a lambda function that is dependent on a lambda layer. I notice that the environment name is hardcoded into the `function-cloudformation-template.json` file as

` "Layers": [{"Fn::Sub":"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:imagery-mydev:1"}],`

where `imagery` is the name of the later and `mydev` is the name of the existing environment and not the new one I am trying to push changes to.

I suspect the hardcoding in the cloudformation template is to blame. Any ideas on alternatives so it picks up the environment automatically rather than hardcoding? I'm a newbie when it comes to cloudformation so not sure what could be used?

I have also noticed that if I checkout my original environment and then choose to add a new function via the CLI with access to the layer, this new function also has a hardcoded environment when referencing the layer.

One option I have considered as a workaround is to change the name of the new environment in the new region to the same as the other environment. It appears the lambda layers are being deployed successfully into the new environment prior to the attempt to create the dependent lambda functions.

### Expected behavior

It should successfully push the lamda functions to the new environment in the different region.

### Reproduction steps

1. amplify env add `new_env`
2. amplify checkout `new_env`
3. amplify push

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by greendinosaur** [comment]
As an update, I manually edited the cloudformation json file to

`"Layers": [{"Fn::Sub":"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:imagery-${env}:1"}]`

and `amplify push` succeeded. 

I guess the question now is, why do I need to manually edit the file? Shouldn't the CLI ensure the file uses the environment variable?

**Comment by jhockett** [comment]
Hi @greendinosaur, we have merged a feature that will allow you to have your Lambda functions depend on the latest deployed layer version. It should be included in the next release.

The hardcoding of the env name in the layer ARN is currently necessary because Lambda layer versions are immutable, and your new environment may not have the same version number deployed.

**Comment by greendinosaur** [comment]
Will the new feature default to use ${env} in the cloudformation json file and some kinf of variable to indicate use the latest version of the layer? 

I can see this being useful when you want to deploy to a new environment. The deployment can create the new lambda layer with a version number of 1 and then use this in the new lambda function.

Otherwise, the problem I had today will persist and people will have to manually edit the cloudformation file in order to deploy a lambda function requiring a lambda layer to a new environment.

**Comment by jhockett** [comment]
> Will the new feature default to use ${env} in the cloudformation json file and some kinf of variable to indicate use the latest version of the layer?

Essentially although the mechanism is different, see https://github.com/aws-amplify/amplify-cli/pull/7375 for more information on the upcoming release.

I recommend using `amplify update function` for the time being to point your Lambda function to the layer version in your new environment, instead of manually updating the cloudformation.

**Comment by greendinosaur** [comment]
the issue with using amplify update function is I can only do this once I've deployed the function to the new environment as the cloudformation template has the environment layer hardcoded. Once I've deployed, I can use `amplify update function` to manage it

**Comment by jhockett** [comment]
Hi @greendinosaur, if you update to the latest version of Amplify CLI and migrate your Lambda layers, you can run `amplify update function` to point your function to depend on the latest deployed layer version in the relevant environment.

For reference, here is the documentation on the v5 layer migration: https://docs.amplify.aws/cli/migration/lambda-layers-update

Closing this issue. If you run into any issues, please comment below and we can re-open and investigate further.
