### ISSUE TITLE
Skipping ‘Restrict API Access’ step when modifying an API

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [aws-amplify/amplify-cli#7510]
Hello. I've been using amplify for a while and my organization has a rather unique setup for authentication to each of our REST API routes. When we add, update, or remove a route via the Amplify CLI, is there a way to completely omit the 'Restrict API Access' step? The thing is that I want to be able to make changes to the routes while leaving the authentication details completely intact. Ever since the beginning we've been selecting the 'no' option and then just manually rebuilding the authentication setup in the AWS console. Does anyone have any ideas of what we can do?

**Comment by akshbhu** [comment]
Hi @ChapterSevenSeeds 

 Do you mean a headless call to add/modify REST API in amplify?

**Comment by ChapterSevenSeeds** [comment]
@akshbhu,

that's not quite what I'm looking for. Let me expound a bit more.

When I run the command 'amplify update api', asks me a series of questions.

1. Please select from one of the below mentioned services: REST
2. Please select the REST API you would want to update: FooBarAPI
3. What would you like to do: Add another path
4. Provide a path (e.g., /book/{isbn}): /foobarpath
5. Choose the Lambda function to invoke by this path: mylambda
6. Restrict API access (Y/n)

Step 6 in the above is what I'm looking to completely omit. If I select 'n', then Amplify CLI removes all the authentication settings from every route attached to the FooBarAPI. If I select 'Y', it forces me to specify a set of authentication rules which it will apply to every route attached to the FooBarAPI. Simply enough, I want to add a new route to the FooBarAPI and leave the authentication settings for the other routes untouched. Is this possible?

**Comment by akshbhu** [comment]
Hi @ChapterSevenSeeds 

AFAIK if you select (Y/N) to this question, this will only affect the specific path for the API. For your info , you can also check ```api-params.json``` to check the auth settings per path.

In your case if you add a path to rest API ```/foobarpath``` , you can just select 'Y' to this select privacy settings , it doesn't affect your other paths.

**Comment by ChapterSevenSeeds** [comment]
@akshbhu,

I apologize. I never realized that what we were experiencing was a result of the api-params.json not having any sort of auth configured. Running amplify push would just wipe them out. Thanks for pointing that out to me! I'll take it from here.
