### ISSUE TITLE
Symbolic links

### ISSUE THREAD

**Issue by glidaa** [aws-amplify/amplify-cli#7511]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

15.5

### Amplify CLI Version

4.52

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I get this when i build
       # Executing command: amplifyPush --simple

2021-06-09T22:36:07.348Z [INFO]: [31mFailed to pull the backend.[39m
2021-06-09T22:36:07.349Z [INFO]: [31mELOOP: too many symbolic links encountered, stat '/codebuild/output/src745308297/src/glidaa.com/PaxHeader'[39m
2021-06-09T22:36:07.373Z [INFO]: [0mError: ELOOP: too many symbolic links encountered, stat '/codebuild/output/src745308297/src/glidaa.com/PaxHeader'[0m
                                 [0m    at Object.statSync (fs.js:1016:3)[0m
                                 [0m    at Object.statSync (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:312:16)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/project-scanner.js:10:12)[0m
                                 [0m    at scanProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/index.js:14:25)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a30-initFrontend.ts:21:24[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at Object.initFrontend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a30-initFrontend.ts:19:34)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.21.0/lib/node_modu

### Expected behavior

it should work

### Reproduction steps

amplify push on my backend

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi

From the error : ELOOP: too many symbolic links encountered, stat '/codebuild/output/src341512534/src/glidaa.com/PaxHeader , it seems in src folder PaxHeader might contain symlinks to a folder which is creating a loop and node (fs.Statsync()) is complaining.

This is the line which fails:
https://github.com/aws-amplify/amplify-cli/blob/08f7a3c45b2e98535ef325eb0a97c5bc4d3008c6/packages/amplify-frontend-ios/lib/project-scanner.js#L10

If its present , try removing them from App and try again?

**Comment by glidaa** [comment]
ok this         - rm PaxHeader seems to do something.

**Comment by glidaa** [comment]
so we added this

version: 1
env:
  variables:
      key: value
backend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - rm PaxHeader
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**Comment by glidaa** [comment]
as the amplify.yml

**Comment by glidaa** [comment]
why am i - rm PaxHeader? you have an issue in your code.

**Comment by behrooziAWS** [comment]
I have searched our build logs in the last 2 weeks for other occurrences of this too many symlink error and it is limited to your app and one other which doesn't have the same fingerprint.  I would recommend you diff this commit where it started: `efff5a87f9da2b962039bbd61c72bff7a71331fe` against the previous `072dff49cabdb872eff47ef526841f3d1f2afabf` where it didn't happen.  If you have not added PaxHeader or added any packages that may have created that folder let us know.
