### ISSUE TITLE
Cannot update to amplify 5.0.0

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#7521]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.1.0

### Amplify CLI Version

4.51.3

### What operating system are you using?

macOS 10.15.7

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When trying to update to 5.0.0 using any of these commands:
`npm install -g @aws-amplify/cli`
OR
`sudo npm install -g @aws-amplify/cli --unsafe-perm=true`
I receive this error:
`6089 verbose stack Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-cdk/bin/cdk'`

<img width="1502" alt="Screenshot 2021-06-16 at 11 21 48" src="https://user-images.githubusercontent.com/738681/122205399-1ce43200-ce98-11eb-9e7b-3910af8a7336.png">
<img width="1502" alt="Screenshot 2021-06-16 at 11 23 18" src="https://user-images.githubusercontent.com/738681/122205414-21104f80-ce98-11eb-8638-fffd9da59c29.png">
<img width="1502" alt="Screenshot 2021-06-16 at 11 23 14" src="https://user-images.githubusercontent.com/738681/122205418-21a8e600-ce98-11eb-95c7-b2b152173134.png">
<img width="1502" alt="Screenshot 2021-06-16 at 11 21 59" src="https://user-images.githubusercontent.com/738681/122205422-22417c80-ce98-11eb-9d11-91f4bf12e82a.png">

### Expected behavior

Installation goes OK.

### Reproduction steps

Just try to update from 4.51.3 to 5.0.0 using my computer or my configuration.

### GraphQL schema(s)

NA

### Log output

NA

**Comment by josefaidt** [comment]
Hey @Ricardo1980 thanks for raising this! Can you try clearing npm cache with `npm cache clean` and re-attempt the upgrade?

**Comment by ArshAulakh59** [comment]
I'm facing the same issue. Have tried 'npm -g cache clean --force' and then installing again but didn't work.

**Comment by josefaidt** [comment]
I was able to reproduce this issue with Node v15.7 and npm v7.4.3, and was able to resolve it by upgrading npm with `npm i -g npm` to update to v7.18.1 and re-attempt upgrade of Amplify CLI. 

Can you try upgrading npm to the latest version and re-attempt the upgrade?

**Comment by Ricardo1980** [comment]
After removing manually node and npm, and then installing again with brew, it worked.
