### ISSUE TITLE
Is it possible to link a resources created in appsync to Amplify graphql api

### ISSUE THREAD

**Issue by mlafo** [aws-amplify/amplify-cli#7524]
**Which Category is your question related to?**
Amplify graphql Api

**Amplify CLI Version** 
4.52.0

Considering that it may be necessary to restore a DynamoDB table.  
Is it possible after adding the table as a data source on appsync to automatically down the schema to Amplify API through schema.graphql

**Comment by akshbhu** [comment]
Hi @mlafo 

Do you mean to use an external Appsync Api created through Console in your amplify App?

If yes, This documentation can help you with this: https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js#re-use-existing-appsync-graphql-api

**Comment by mlafo** [comment]
Sorry it's not my user case. 

I'am seeking a way to link an existing dynamoDb Table to Amplify graphql API. 
Into Appsync I can add my table as a data source. It builds resolvers for GraphQL and the appsync schema works. 
But i would like to have this schema up to date in my local schema.graphql file. After an "Amplify env --restor" cmd that won't work, If i write the input 
Obviously it has something to do with the CloudFormation process behind the Amplify CLI.

**Comment by mlafo** [comment]
OK, I have found a solution. 

In my exemple the table i wanted to link is named 'myTable'
I create a new @model Type in my local schema.graphql named with 'myDefinitiveTypeName' with goods attributes.
I push the api : amplify api push
Then Apsync is updated and create a new dynamoDb table 'myDefinitiveTypeName' with env informations in the name if needed. 
I remove 'myDefinitiveTypeName'
I backup  'myTable'
I restore 'myTable' under 'myDefinitiveTypeName'
And it works !

**Comment by akshbhu** [comment]
Hi @mlafo 

Currently Amplify doesnt support this usecase. 

Glad to know this workaround works , but I am not sure if you will be able to make any updates to this via CLI as you have made changes through appsync console which can cause drift in CFN.

**Comment by mlafo** [comment]
Hi @akshbhu 
It seems that updates, like adding attributes, in the @model Type in the schema.graphql work fine. 
No error appear during an amplify api push. No problem either with GraphQl requests. 
Pretty good for now.
