### ISSUE TITLE
Graphql not sorting like guide

### ISSUE THREAD

**Issue by IgorDePaula** [aws-amplify/amplify-cli#7525]
**Which Category is your question related to?**
Graphql sorting like guide

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

Aplify CLI 4.52.0

**What AWS Services are you utilizing?**

I using mock api with graphql

**Provide additional details e.g. code snippets**
My model:

```
type Ambit @model  @key(name: "ambitsByDate", fields: ["type","createdAt"], queryField: "ambitsByDate") {
  id: ID!
  name: String!
  createdAt: String!
  type: String!
}
```

My query:
```
query MyQuery {
  ambitsByDate(type: "ambit", sortDirection: ASC) {
    items {
      id
      name
      createdAt
    }
  }
}
```

Error:
![Captura de tela de 2021-06-16 12-36-25](https://user-images.githubusercontent.com/2833993/122249800-861b7380-ce9f-11eb-9277-bf38d3bd0d1e.png)

The guide:
[https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js#implementation](https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js#implementation)
![Captura de tela de 2021-06-16 12-37-44](https://user-images.githubusercontent.com/2833993/122250220-dc88b200-ce9f-11eb-8fb1-807ba558397f.png)
![Captura de tela de 2021-06-16 12-37-54](https://user-images.githubusercontent.com/2833993/122250233-df83a280-ce9f-11eb-87e1-45574f460f50.png)

**Comment by akshbhu** [comment]
Hi @IgorDePaula 

I tried with same schema you provided and it is working for me .
this is the query:
```
query MyQuery {
  ambitsByDate(type: "ambit", sortDirection: ASC) {
    items {
      name
      createdAt
      type
    }
  }
}
```
Here are the results: 
```
{
  "data": {
    "ambitsByDate": {
      "items": [
        {
          "name": "1",
          "createdAt": "2021-06-16T18:55:34.591Z",
          "type": "ambit"
        },
        {
          "name": "2",
          "createdAt": "2021-06-16T18:55:39.441Z",
          "type": "ambit"
        },
        {
          "name": "3",
          "createdAt": "2021-06-16T18:55:43.164Z",
          "type": "ambit"
        },
        {
          "name": "4",
          "createdAt": "2021-06-16T18:55:49.021Z",
          "type": "ambit"
        }
      ]
    }
  }
}

```

From the error it seems you're trying to run a Query using a condition that does not include the partition/hash key

Can you try other queries like List/get to see if that's working?

**Comment by IgorDePaula** [comment]
@akshbhu 

Yes, anothers queries works fine.

Sorry, something happens in my machine, after install some libs, the mock of api sorting the data, but not in my app, that send the http variables...

**Comment by IgorDePaula** [comment]
Sorry, my app not sorting because I executes the wrong query. Sorry.

Thank you for your attention.

**Comment by IgorDePaula** [comment]
Question, sorting only by date, or Can I sorting by another field?

**Comment by akshbhu** [comment]
yes , you can sort by field too instead of date

**Comment by IgorDePaula** [comment]
Cool!!! I'ii try.

**Comment by IgorDePaula** [comment]
@akshbhu , please a doubt, the graphql api and rest api, each one has your won way or not, my workds not make sense? Example, graphql is only mobile and rest is for only web...or not, they has same way?
