### ISSUE TITLE
CLI 5.x fails to locate AWS credentials provided by an EC2 instance profile

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-cli#7528]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.10.0

### Amplify CLI Version

5.0.0

### What operating system are you using?

macOS 11.4

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

I am working on an amplify demo where amplify CLI is used from an Amazon EC2 instances. 
All permissions to use AWS services are passed through an Amazon EC2 instance profile + an IAM role.
To build my project, I use `amplify pull` to fetch the config file.
Here is the command I use

```
REGION=eu-central-1
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
AMPLIFY="{\
\"projectName\":\"$AMPLIFY_PROJECT_NAME\",\
\"appId\":\"$AMPLIFY_APPID\",\
\"envName\":\"$AMPLIFY_ENV\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"ios\"
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

PATH=$PATH:/usr/local/bin/ # require to find node
/usr/local/bin/amplify pull \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes --region $REGION
```

My `~/.aws` directory looks like

```
ec2-user@ip-172-31-20-171 ~ % cat .aws/config 
[default]
region=eu-central-1

ec2-user@ip-172-31-20-171 ~ % cat .aws/credentials 
[default]

```

Using amplify version <5 it was working like a charm.
Now that I upgraded to Amplify CLI v5, I receive the following error message.
Looks like the CLI is not able to understand the credentials are provided through the IAM role.

```
Pre-pull status:
Current Environment: dev
| Category | Resource name             | Operation | Provider plugin   |
| -------- | ------------------------- | --------- | ----------------- |
| Auth     | iosgettingstarted57ec6fa5 | Create    | awscloudformation |
| Api      | iosgettingstarted         | Create    | awscloudformation |
| Storage  | images                    | Create    | awscloudformation |
Local changes detected.
Pulling changes from the cloud will override your local changes.
⠋ Fetching updates to backend environment: dev from the cloud.
Failed to get profile: Profile configuration for 'default' is invalid: missing aws_access_key_id, aws_secret_access_key
```

I tried to remove the profile from AWS CLI config, or to remove `~/.aws` altogether - no changes.

After talking to @marcvberg it appears this might be related to https://github.com/aws-amplify/amplify-cli/issues/7311 

### Expected behavior

Amplify CLI should be able to pull out AWS credentials from the EC2 instance profile. Either by itself, either by relying on the underlying SDK.

### Reproduction steps

1. create an amplify project on your laptop.
2. deploy the project 
3. launch an EC2 instance with an Instance Profile pointing to a role having [this minimum set of permissions](https://github.com/sebsto/amplify-ios-getting-started/blob/main/code/cli-build/iam_permissions_for_ec2.json).
4. Connect to the EC2 instance
5. Issue an `amplify pull` command similar to the one above (be sure to assign correct values to all environment variables)

command fails

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment]
Probably will be fixed by: #7401

**Comment by sebsto** [comment]
Two workarounds that worked for me :

1. hard code an access key and secret access key in `~.aws/credentials`

2. Modify the script I amusing to explicitly fetch access key and secret access key from instance meta-data

```
ACCESS_KEY=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/macOS_CICD_Amplify/ | jq -r .AccessKeyId)
SECRET_KEY=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/macOS_CICD_Amplify/ | jq -r .SecretAccessKey)

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"general\",\
\"useProfile\":false,\
\"accessKeyId\":\"$ACCESS_KEY\",\
\"secretAccessKey\":\"$SECRET_KEY\",\
\"region\":\"$REGION\"\
}"
```

**Comment by cjihrig** [comment]
@sebsto is this working for you now with v5.0.2 and newer of the CLI?

**Comment by sebsto** [comment]
I'll need to spin a new EC2 instance to test this - thanks for the heads. I will try to allocate time during the week-end
