### ISSUE TITLE
How to mimic device tracking with custom auth flow and dynamdb?

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-cli#7530]
**Which Category is your question related to?**
Cognito (authentication)

**Amplify CLI Version**
 4.51.0

**Provide additional details e.g. code snippets**
If you're using the custom authentication flow, is there a way to get some verified device identifier (for example, one assigned by the amplify client to the app itself) which can then be stored in a dynamodb table as to mimic Cognito's device tracking?
Use case:
  1. no need for a challenge if the device is recognized
  2. implement some kind of exponential backoff routine

**Comment by akshbhu** [comment]
Hi @avlonder 

Can you check this link if this can help you : https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/ ?
