### ISSUE TITLE
CLI 5.x  cause circular dependency error

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7541]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.0.0

### What operating system are you using?

MacOS

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

After updated to v5.0.0, when run `amplify push`, I got this error:
```
Circular dependency between resources ...
```

Revert back to v4 everything have been pushed normally.

### Reproduction steps

upgrade to v5, run `amplify push`

### Additional information
I'm using the following categories.
```
| Category | Resource name                           | Operation | Provider plugin   |
| -------- | --------------------------------------- | --------- | ----------------- |
| Function | testdf914c57df914c57PostConfirmation    | Update    | awscloudformation |
| Function | DynamoStream                            | Update    | awscloudformation |
| Function | testdf914c57df914c57CustomMessage       | No Change | awscloudformation |
| Function | AdminQueries96463a40                    | No Change | awscloudformation |
| Function | dbStreamLibs                            | No Change | awscloudformation |
| Auth     | userPoolGroups                          | No Change | awscloudformation |
| Auth     | testdf914c57df914c57                    | No Change | awscloudformation |
| Api      | AdminQueries                            | No Change | awscloudformation |
| Api      | test                                    | No Change | awscloudformation |
| Storage  | testfiles                               | No Change | awscloudformation |
```

in `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` I got some miss formatted items (the config for  `auth` category), but not sure if this is the root cause, because even this looks like a bug, but it won't error on previous version of amplify-cli.

<img width="1253" alt="Screen Shot 2021-06-18 at 5 40 53" src="https://user-images.githubusercontent.com/13927101/122469523-03f29280-cff8-11eb-866c-681c7409fbed.png">

**Comment by akshbhu** [comment]
Hi @yaquawa 

This is a known bug and we have a PR [here](https://github.com/aws-amplify/amplify-cli/pull/7392) that will address this .
Closing this in favour of #7372
