### ISSUE TITLE
Issue still present, I'm running 4.41.2

### ISSUE THREAD

**Issue by stephenjen** [aws-amplify/amplify-cli#7542]
Issue still present, I'm running 5.0 
I'm getting the same error when I run `amplify push`
Is there anyway to make the error message more clear ?

_Originally posted by @isbkch in https://github.com/aws-amplify/amplify-cli/issues/6164#issuecomment-773677253_

**Comment by nubpro** [comment]
Try reseting your schema.graphql, create a blank schema

**Comment by josefaidt** [comment]
Hey @stephenjen :wave: thanks for raising this. To gather more context would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help the team better determine the cause of the issue.

**Comment by stephenjen** [comment]
> Can you show your schema.graphql?
> Perhaps there's some syntax error somewhere

I simplified it down to the most basic table and still received the same error

`type Tag @model {
    id: ID!
}`

**Comment by stephenjen** [comment]
I ended up deleting the ./amplify directory and then running amplify init and going through the entire setup process again.  This solved the issue.
