### ISSUE TITLE
CLI 5.0: Migrating lambda layer failed

### ISSUE THREAD

**Issue by div5yesh** [aws-amplify/amplify-cli#7555]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.13.0

### Amplify CLI Version

5.0.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Amplify push fails with pre existing lambda layers after CLI version upgrade.

```
? Are you sure you want to continue? Yes

⚠️  Amplify updated the way Lambda layers work to better support team workflows and additional features.
This change requires a migration. Amplify will create a new Lambda layer version even if no layer content changes are made.

? Continue? Yes
Unable to find layer permissions for myLambdaLayer, falling back to default.
✖ An error occurred when pushing the resources to the cloud

Cannot destructure property 'value' of 'layerConfig.runtimes[0]' as it is undefined.
An error occurred during the push operation: Cannot destructure property 'value' of 'layerConfig.runtimes[0]' as it is undefined.
```

### Expected behavior

Auto migration of lambda layers as per https://docs.amplify.aws/cli/migration/lambda-layers-update

### Reproduction steps

Run amplify push after upgrading CLI to 5.0.

`amplify push --force`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
Discussed with @div5yesh  offline and observed the `amplify/backend/function/numpypandasLayer/layer-runtimes.json` in empty `[]` in the pre-migration step. Changing it to the following would potentially resolve the issue.
```json

[
  {
    "value": "python",
    "name": "Python",
    "layerExecutablePath": "python/lib/python3.8/site-packages",
    "cloudTemplateValue": "python3.8"
  }
]


```

**Comment by attilah** [comment]
This issue comes from the fact that runtime selection was optional in CLI versions before 5.0.0 and this is not handled in any way.
