### ISSUE TITLE
Permission denied when adding DynamoDB auto scaling

### ISSUE THREAD

**Issue by rupe120** [aws-amplify/amplify-cli#7562]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.3.0

### Amplify CLI Version

5.0.1

### What operating system are you using?

Windows

### Amplify Categories

storage

### Amplify Commands

push

### Describe the bug

I added a ScalingPolicy and ScalableTarget for read and write on a DynamoDB table. When `amplify push` is run I get the following error

    CREATE_FAILED               ReadCapacityScalableTarget                                                     AWS::ApplicationAutoScaling::ScalableTarget Mon Jun 21 2021 09:46:00 GMT-0400 (Eastern Daylight Time) User: arn:aws:sts::267565328097:assumed-role/us-east-1_XMD8bEI0J_Full-access/amplifyadmin is not authorized to perform: application-autoscaling:DescribeScalableTargets (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: AccessDeniedException; Request ID: 88fffdb2-d700-40b7-96da-755de956dc58; Proxy: null)

### Expected behavior

DynamoDB auto scaling enabled

### Reproduction steps

1. Add AWS::ApplicationAutoScaling::ScalableTarget and AWS::ApplicationAutoScaling::ScalingPolicy to a DynamoDB table
2. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
There was an error creating your Issue: body is too long (maximum is 65536 characters). See Gist https://gist.github.com/rupe120/a40f9b199389d5ba5fc9ab0e72165120

```

</details>

**Comment by attilah** [comment]
@rupe120 as you are adding custom functionality to your stack that the CLI has generated, if those customizations require new permissions those have to be added manually to the Policy you configured to execute the `amplify` commands with.

**Comment by rupe120** [comment]
It has admin permission

**Comment by rupe120** [comment]
Are you looking for anything more from me?

**Comment by rupe120** [comment]
@attilah is there something I'm not understanding correctly?

**Comment by kaustavghosh06** [comment]
@rupe120 I believe you're using Amplify Admin to authenticate your requests. When authenticating via Amplify Admin, your IAM policies are scoped down and are listen in here - `us-east-1_XMD8bEI0J_Full-access` in your AWS account. You can go ahead and look at this IAM role and update/add policies for your custom stack. Please let me know if you're still stuck after adding the appropriate policies to the IAM role mentioned above.
