### ISSUE TITLE
@key directive with three fields

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-cli#7565]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify, graphql

**Amplify CLI Version** 

4.32.1

**What AWS Services are you utilizing?**
Appsync. DynamoDB

Is it possible to create a @key directive with three fields? Suppose I have a type like this:
```
 type CommunityMember
  @model
  @key(name: "test", fields: ["communityID", "fullName", "status"], queryField: "testQuery")
   {
  id: ID!
  communityID: ID!
  memberID: ID!
  createdAt: String
  community: Community @connection(fields: ["communityID"])
  member: User @connection(fields: ["memberID"])
  fullName: String
  role: String
  status: String
}
```

I would like to use the "testQuery" to filter records based on the community ID, and do ordering based on the "fullName" and "status" fields. But the query always returns empty results, I can see that the index on dynamodb table is empty. If I remove one of the fields like "status", the query works just fine, which leads me to think that it only works with two fields. Can someone tell me if its possible to create an global secondary index using three fields? The way I'm doing its no working.

**Comment by attilah** [comment]
@zzBrunoBrito I guess you added the `@key` directive after you had data in the table, right? If that's the case, CLI does not do data backfill, you have to do that yourself as of Today.

`@key` supports more than 2 fields as you can see it [here](https://docs.amplify.aws/cli/graphql-transformer/dataaccess): 

```graphql
@key(name: "byCustomerByStatusByDate", fields: ["customerID", "status", "date"])
```

That page has a lot of data patterns that could help you to understand what is possible.

**Comment by zzBrunoBrito** [comment]
@attilah You're right, I have to do data backfill. Thanks!

**Comment by attilah** [comment]
@zzBrunoBrito awesome, closing the issue as the question was answered.
