### ISSUE TITLE
amplify push overwrites manual changes to userPoolGroups/template.js

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#7573]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I need to make some changes to my user pool groups template. More specifically I am adding another action to the AssumeRolePolicyDocument section under the section that defines one of my user pool groups.

```
   "orgAdminGroupRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "RoleName":{
                    "Fn::Join": [
                        "",
                        [
                          {
                            "Ref": "authcognitoUserPoolId"
                          },
                          "-orgAdminGroupRole"
                        ]
                    ]
                },
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "",
                            "Effect": "Allow",
                            "Principal": {
                                "Federated": "cognito-identity.amazonaws.com"
                            },
                            "Action": [
                                "sts:AssumeRoleWithWebIdentity",
                                "sts:TagSession"
                            ],
                            "Condition": {
                              "StringEquals": {"cognito-identity.amazonaws.com:aud": {"Ref":"authcognitoIdentityPoolId"}},
                              "ForAnyValue:StringLike": {"cognito-identity.amazonaws.com:amr": "authenticated"}
                            }
                        }
                    ]
                }
            }
        },

```

After amplify push, the Action section gets overwritten to 

`"Action": "sts:AssumeRoleWithWebIdentity"`

### Expected behavior

Amplify push should not override the file but should just deployed.

### Reproduction steps

Make changes to the template
Run amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@krikork Please take a look at how to add custom policies to your group IAM roles out here with the "user-pool-group-precedence.json" file  in the last section  - https://docs.amplify.aws/cli/auth/groups#group-access-controls

**Comment by krikork** [comment]
Hey @kaustavghosh06, I am trying to add sts:TagSession in the IAM group role’s trust policy as shown here: https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/using-attributes-for-access-control-policy-example.html

Do you have any example of how to do that in the "user-pool-group-precedence.json" file?

Also, can you clarify why amplify overwrites the local changes on `amplify push`? The behavior seems inconsistent with other resources, it also makes it far harder to achieve what the documentation link above achieves with 1 line.

**Comment by kaustavghosh06** [comment]
@krikork Right now we do not support modifying or adding the sts:TagSession to the IAM roles, but we're currently working on a feature to make this sort of customizability possible in a generic way. cc @akshbhu

**Comment by setterlee** [comment]
Similar issue here but with the user-pool-group-precedence.json file, i'm trying to add some custom policies to give access to geolocations resources to my default users group but the amplify push command overrides the file...

**Comment by josefaidt** [comment]
Closing in favor of customizing via [overrides](https://docs.amplify.aws/cli/auth/override/) (mentioned in https://github.com/aws-amplify/amplify-cli/issues/7573#issuecomment-894435621)
