### ISSUE TITLE
If I try to add function access permission to a function from another function I get "No resources found for function"

### ISSUE THREAD

**Issue by fgiopp** [aws-amplify/amplify-cli#7587]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.4

### Amplify CLI Version

5.0.1

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

So far, whenever I have needed to add access permissions to one lambda function (function Y) from another (function X), I have done is following steps from the amplify CLI:

- amplify function update
- >Lambda function (serverless function) 
- select function X
- >Resource access permissions 
- select the function category (using the space bar)
- select the target function in which I'm interested from the list of my function

Some day ago, I upgraded to 5.0.1; today, I have tried to add the access permission to function Y from the function X, so:

- amplify function update
- >Lambda function (serverless function) 
- select function X
- >Resource access permissions 
- select the function category (using the space bar)
- PROBLEM: now I don't get the list of functions to give accesso to but I get "No resources found for function."

### Expected behaviour

- amplify function update
- >Lambda function (serverless function) 
- select function X
- >Resource access permissions 
- select the function category (using the space bar)
- select the target function in which I'm interested from the list of my function

**Comment by attilah** [comment]
@fgiopp thanks for reporting the issue, I was able to reproduce it.

**Comment by fgiopp** [comment]
I have upgraded to amplify 5.0.2, but the problem is still there.

**Comment by fgiopp** [comment]
I have upgraded to amplify 5.0.2, but the problem is not fixed.

**Comment by attilah** [comment]
It is not included in 5.0.2, will be in the next release.
