### ISSUE TITLE
Add a way to use human-readable names for resources

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-cli#759]
**Is your feature request related to a problem? Please describe.**
It's challenging when the amplify cli creates resources named like "cognito1eb8d495_userpool_1eb8d495". At a glance, it's impossible to tell which app it belongs to, whether it's staging or production, etc.

**Describe the solution you'd like**
The CLI should have a way to set a prefix, e.g. `amplify add auth --name-prefix my-app-dev-` or something similar to this.

**Comment by kaustavghosh06** [comment]
Thanks for your feedback @ffxsam. We'll work on getting these names friendly.

**Comment by webberwang** [comment]
Having the ability to choose your own resource name like `amplify add api` would be a welcomed addition

**Comment by kaustavghosh06** [comment]
@ffxsam We've fixed both the issues that you'd mentioned. We use the project-name as the prefix for your Cognito userpools now and also use the env-name as a part of your cloudformation stacks. Please use the latest version of the CLI and let us know what you think about it.
