### ISSUE TITLE
`amplifyconfiguration.dart` is being added to `.gitignore` automatically

### ISSUE THREAD

**Issue by MohammedNoureldin** [aws-amplify/amplify-cli#7591]
Is it ok that `amplifyconfiguration.dart` is being added to the `.gitignore` file automatically? I have just tried initializing my project, and this file was added to gitignore.

In my case I am using already existing resources, so that requires editing this file manually (if I am doing that correctly). If this file should be really excluded, how should I add my already existing resources?

My `flutter --version` output:

```
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision adc687823a (6 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

**Comment by josefaidt** [comment]
Hey @MohammedNoureldin :wave: as @ragingsquirrel3 noted this is the default behavior for the CLI as checking this file into source control can cause unexpected behavior when using multiple environments and branches as it is specific to the currently-initialized app. You can choose to opt-in to checking this file into source control, however please be aware of the pitfalls such as the CLI making changes to this file and the gitignore as actions are performed.

**Comment by attilah** [comment]
Closing as the question has been answered.
