### ISSUE TITLE
Amplify does not support mock lambda function in golang 1.16.* runtime

### ISSUE THREAD

**Issue by M-Arthur** [aws-amplify/amplify-cli#7599]
### Golang version
1.16.5

### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

5.0.1

### What operating system are you using?

Ubuntu

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Amplify does not allow me either mock the lambda function or push the function to AWS when I use golang 1.16.*

### Expected behavior

Eveything should go through with no error.

### Reproduction steps

1. Run cmd `amplify function`
2. Configure the function as you like expect choose `go` as the runtime
3. Run cmd `amplify mock function [function name created in step 2]` and choose the default JSON object.

### GraphQL schema(s)

<details>

```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}

type Customer @model @key(fields: ["email"]) {
  email: String!
  username: String
}
```

</details>

### Log output

<details>
Below is what I get.

```
Ensuring latest function changes are built...
Starting execution...
Local invoker binary was not found, building it...
go: github.com/aws/aws-lambda-go@v1.15.0: missing go.sum entry; to add it:
        go mod download github.com/aws/aws-lambda-go
appsyncConnection failed with the following error:
Error: Command failed with exit code 1: go build main.go
    at makeError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/execa/index.js:188:17)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/runtime.ts:31:24)
    at buildLocalInvoker (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:29:5)
    at Object.localInvoke (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:67:30)
    at Object.invoke (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-go-function-runtime-provider/src/index.ts:26:24)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:183:20
    at Object.start (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:48:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5) {
  shortMessage: 'Command failed with exit code 1: go build main.go',
  command: 'go build main.go',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.

```

</details>

### Additional information

N/A

**Comment by attilah** [comment]
@M-Arthur I can't see if it is a CLI failure or not at this point as the error I see is seems to be an error coming back from the go compiler. Could you try and build the go function manually by going to the function's directory and see if that succeeds?

**Comment by M-Arthur** [comment]
> @M-Arthur I can't see if it is a CLI failure or not at this point as the error I see is seems to be an error coming back from the go compiler. Could you try and build the go function manually by going to the function's directory and see if that succeeds?

Build from local is totally fine. I only see this error message when I tried to build with Amplify.

BTW, I downgraded golang to 1.15.* and it works fine now. But it does not work once I upgrade golang to 1.16.*

**Comment by josefaidt** [comment]
Hey @M-Arthur :wave: I ran into an issue with go@1.16 and the default go Lambda template, and as you said once you downgrade to 1.15 and try mocking (which runs `go build`) it will build and mock as intended. And even so, if you then upgrade to 1.16 and try to mock that same lambda, it will work.

Below is the error I received with the base template:

```console
go: github.com/aws/aws-lambda-go@v1.24.0: missing go.sum entry; to add it:
        go mod download github.com/aws/aws-lambda-go
``` 

It appears this is due to a [change with module loading in go@1.16](https://blog.golang.org/go116-module-changes#TOC_3.) where the `go` command no longer tries to fix and resolve missing dependencies, and requires us to run `go get ...` or `go mod tidy` to generate the sum file. Once either of these commands are ran and dependencies are available locally, we can then successfully mock the lambda function.

**Comment by M-Arthur** [comment]
> Hey @M-Arthur 👋 I ran into an issue with go@1.16 and the default go Lambda template, and as you said once you downgrade to 1.15 and try mocking (which runs `go build`) it will build and mock as intended. And even so, if you then upgrade to 1.16 and try to mock that same lambda, it will work.
> 
> Below is the error I received with the base template:
> 
> ```
> go: github.com/aws/aws-lambda-go@v1.24.0: missing go.sum entry; to add it:
>         go mod download github.com/aws/aws-lambda-go
> ```
> 
> It appears this is due to a [change with module loading in go@1.16](https://blog.golang.org/go116-module-changes#TOC_3.) where the `go` command no longer tries to fix and resolve missing dependencies, and requires us to run `go get ...` or `go mod tidy` to generate the sum file. Once either of these commands are ran and dependencies are available locally, we can then successfully mock the lambda function.

Thanks a lot. It fixes the issue and clear my doubts.

**Comment by josefaidt** [comment]
🙏 glad to hear that works! We have an open PR to address this as well, which will install dependencies on mock.
