### ISSUE TITLE
Can't create API, despite following name rules

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-cli#760]
**Describe the bug**
When creating a new API, it's impossible to name it according to the acceptable naming rules.

**To Reproduce**
1. `amplify api add`
2. Answer `GraphQL`
3. Name the API using a hyphen

**Expected behavior**
I would expect it to work. Instead, the error "You can use the following characters" shows up.

**Screenshots**
```
? Please select from one of the below mentioned services GraphQL
? Provide API name: amplify-vue
>> You can use the following characters: a-z A-Z 0-9
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.14.3
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@ffxsam As th error message says that currently we support "a-z" which is a to z chars then "A-Z" charecters which is all A to Z chars and then "0-9" which 0 to 9 numbers. We don't support "-" char yet and you're trying to use that in your API name.

**Comment by ffxsam** [comment]
Woops, I somehow misread that. That's what I get for working on code for too long without a break. 😉
