### ISSUE TITLE
Amplify AppSync: custom sorting and filtering with pagination

### ISSUE THREAD

**Issue by matteocarpi** [aws-amplify/amplify-cli#7610]
Hi all, I'm trying to write a schema so that I can query models filtered by multiple keys, sorted by a custom key and paginated.

an example of my model: 

```
type Article {
  id: ID!
  category: String!
  area: String!
  publishOn: AWSDate!
}
```

And an example of the query I would like to do is: retrieve all the `Articles` which are part of both a given `category` AND `area`, returned in descending order by `publishOn` in chunks of 10 items each (to implement pagination server-side, and have a lightweight UI).
The response should include also the `nextToken` attribute that can be used to load the "next" page of the filtered articles list.

I have multiple problems with what I can do with the automatically generated schema and can't find a way to implement manually a solution that works for all what I want to do. I try and make a list of what goes wrong:

1. Filtering

Let's say I want to query 10 articles that belong to the category "Holiday":

```
listArticles(filter: {category: {eq: "Holiday} }, limit: 10)
```

I won't get the first 10 articles that match that category, but instead, it seems that AppSync selects the first 10 items in the table, and then it filters these 10 items by the filter criteria. 
In other words, it seems that the sequence in which filtering and sorting are applied is the opposite of what expected. Expected: firstly filter the table by the filter critaria, then return the first 10 items of the filtered result sets. 

2. Sorting

I couldn't find a way to add sorting with AppSync, so I added searchable:

```
type Article (
  @searchable
) {
  id: ID!
  category: String!
  area: String!
  publishOn: AWSDate!
}
```

Now if I sort by date, that key will be used as nextToken and brake the pagination. This is a known issue: https://github.com/aws-amplify/amplify-cli/issues/4434

Do you have any good tip on how to find a workaround to these bugs? I dag into the documentation and in couple of issue, but didn't come up with a solution that works well...

Thanks in advance, 

Matteo

**Comment by attilah** [comment]
@matteocarpi you can look at the `amplify/team-provider-info.json` and you will find a top level key that is your environment name, you can safely remove that.

In the cloud when you delete the CFN template the only remaining resource is your S3 deployment bucket and you can find its name with the same file for the given environment, you can remove that by hand in the AWS Console as well, if you don't need the content.

I'm closing the issue as the question has been answered.

**Comment by matteocarpi** [comment]
Ehmm... I don't see how that answers my question was there a mistake?

However, I got my issue solved on this stackoverflow post: https://stackoverflow.com/questions/68129867/amplify-appsync-custom-sorting-and-filtering-with-pagination/68131083#68131083
