### ISSUE TITLE
How to delete env manually?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7612]
**Amplify CLI Version** 
4.52.0

------

I have deleted the cloudformation nested stack via the web console because the amplify-cli can't delete them correctly.
After then, I tried `amplify env remove dev` to delete it from the config, but this won't work as I've deleted the whole stack myself already. So what's the proper way to remove it from `amplify env list` ? It's harmless but it's so confusing to having a non-existing env there.

**Comment by attilah** [comment]
If you removed the stack from CFN, there are 2 things left behind, your deployment bucket in S3 that you can safely delete, it will have a name like: `amplify-<projectname>-<envname>-<some id>-deployment`.

Locally you can find a top level key in `amplify/team-provider-info.json` file with the name of the environment that you can safely remove from there as well.

Closing the issue as it answers the question, if something new comes up feel free to comment on the issue or open a new one.
