### ISSUE TITLE
`Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7613]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

4.45.2

### What operating system are you using?

MacOS

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

when `amplify push` this shown up:

```
Cannot convert undefined or null to object
An error occurred during the push operation: Cannot convert undefined or null to object
```

Is there any way to show the stack traces? The info above can't give me any useful hints to what happened there.
or if there is a way to push only one category at a time? so I can narrow down what's the category causes the error..

### Expected behavior

x

### Reproduction steps

x

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by yaquawa** [comment]
Hi @akshbhu @jhockett , I was able to narrow down the issue to here

https://github.com/aws-amplify/amplify-cli/blob/856fdf7d226c8a6dc47a8e2278b13dd793fee22a/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/getDependentFunction.ts#L27

where `permissions` is `undefined` in my environment, because the content of my `function-parameters.json` is like this
```json
{}
```

I don't know if this is a bug or something.. could you guide me how to fix this?

**Comment by josefaidt** [comment]
Hey @yaquawa thanks for raising this and including the details! This is an issue we are actively tracking and have a PR open to fix!

I'll close this issue as a duplicate in favor of tracking https://github.com/aws-amplify/amplify-cli/issues/7466, and PR https://github.com/aws-amplify/amplify-cli/pull/7594
