### ISSUE TITLE
 RFC: Runtime Hooks

### ISSUE THREAD

**Issue by xo28122000** [aws-amplify/amplify-cli#7614]
This is a Request For Comments (RFC). RFCs are intended to elicit feedback regarding a proposed change to the Amplify Framework. Please feel free to post comments or questions here.

# Summary

There is a need to perform automations or tasks during lifecycle events of Amplify CLI commands. Runtime hooks help customers run custom scripts during Amplify CLI’s lifecycle events. Customers can hook into a lifecycle event by adding their script files to the hooks directory. Amplify CLI detects and executes the corresponding script during the lifecycle event.

# Common Runtime Hooks Use Cases

### Security checks

Customers can write scripts to scan for sensitive information before push or publish events. If there is a detected vulnerability, customer scripts can stop the execution of Amplify CLI command by exiting with a non zero code. Example of running credential scanner before push:

```bash
if keychecker --path $projectRoot; then
    # no vulneribility found
    exit 0
else
    echo "found security vulneribility"
    exit 1
fi
```

### Running local tests

Customers can write hook scripts to run preexisting test suits. Following is an example of bash script running `npm test`:

```bash
# running npm tests in pre-push script
npm test
testPassed=$?
if [ $testPassed -eq 0 ]; then
    echo "npm tests passed"
    exit 0
else
    echo "npm tests failed"
    exit 1
fi
```

To maintain execution consistency, especially within cross-teams, customers can use runtime hooks to test for Amplify CLI version and halt Amplify CLI commands execution if inconsistent version is present.

```js
const process = require("process");
const data = JSON.parse(process.argv[2]);
const teamAmplifyVersion = "4.52.0";
if (teamAmplifyVersion != data.amplify.version) {
  process.exit(1);
}
```

Hook scripts can also run linters and code formatters to ensure that codebase follows lint and format rules.

### Logging and notifications for Amplify CLI events 

Using hooks, customers can send email or slack messages or store logs. Customers will be able to utilize runtime parameters in their scripts to create detailed logs.

```js
const axios = require("axios");
const process = require("process");
axios
  .post(
    "https://slack.com/api/chat.postMessage",
    {
      channel: "Amplify",
      text:
        "Amplify push was successfully executed!",
    },
    { headers: { authorization: `Bearer ${"SLACK_API_TOKEN"}` } }
  )
  .then((res) => {})
  .catch((err) => {});

```

# Customer Workflow

* Amplify CLI generates a hooks directory in amplify/backend with sample hook scripts on `amplify init`. For existing projects, this folder and sample scripts will be created on `amplify upgrade`.
* Customers will add scripts in hooks directory following the naming convention to hook into a specific lifecycle event. 
* Amplify CLI will execute the hook scripts synchronously during the corresponding event and log scripts' errors and messages to the shell. 

All the scripts in the hooks directory will be git committed by default which is different from [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). To support cross platform compatibility, Amplify hook scripts are not executable files.

### New Amplify CLI generated directory structure after `amplify init`:
```bash
 -amplify
   -backend
      -hooks // all hooks scripts go within this directory
        -pre-push.js.sample
        -post-push.sh.sample
```

### Naming convention:

Files in the hooks directory should follow the format `pre|post-<command>[-<sub-commmand>].extension`. 
`sub-commmand` is optional and can be used to increase hook specificity. Example: `pre-add-auth` and `pre-mock-api`.
If there are `pre-add.js`, `pre-add-auth.js`, `post-add.js` and `post-add-auth.js` scripts present, Amplify CLI will execute in the following order:
`pre-add.js` **>** `pre-add-auth.js` **>** `amplify add auth` **>** `post-add-auth.js` **>** `post-add.js`

### Scripting Languages and Supported Lifecycle events:

Amplify CLI will support bash(.sh) and node(.js) scripts. All scripts are auto-detected based on the extension. If there are files present with same filename and different extensions, extension with naming precedence will be executed. 
For customers or teams using cross platform operating system, it is recommend to use javascript over bash. 

Amplify CLI will support pre and post lifecycle events for the following amplify commands and sub-commands:
* add
* update
* remove
* push
* status
* delete
* pull
* publish
* mock
* env
* codegen
* gql-compile

### Parameters passed to Hook Scripts

When a lifecycle event is called, Amplify CLI passes runtime parameters into hook scripts as command line arguments. There are two JSON strings that will be passed as parameters to hook scripts: **data** and **error**. The sample scripts generated by `amplify init` will have boilerplate template to showcase parsing and using these parameters. Following describes the structure of the two parameters:

**data**: JSON string with the following structure:

```js
{
     projectPath: String,
     amplify: { 
          version: String,
          environment: String,
          command: String,
          subCommands: [ String ],
          options: { String: Boolean|String }
     }
}
```

- projectPath - path to root directory of customer’s amplify project
- amplify -
  - version - current Amplify version
  - environment - current Amplify environment
  - command - Amplify CLI command executed. Example: push
  - subCommands - list of Amplify CLI subcommands or plugins executed. Example auth, storage 
  - options - JSON object containing command line option passed as key and either a boolean or a string as value. Example: For amplify push --yes, the options object would be { yes: true }.

**error**: JSON string in case Amplify CLI emits an error, null otherwise. It has the following structure:

```js
{
     "message": String,
     "stack": String
}
```

- message: the error message emitted by Amplify CLI
- stack: the error stack emitted by Amplify CLI

### Exit status

To stop the execution of Amplify CLI, the hook script can exit with a non-zero status and Amplify CLI will generate necessary logs and gracefully exit.

### Third party packages and Amplify Console support

Customers can use third party packages in hook scripts given those packages are imported correctly and are accessible during execution. For instance, if a pre-push script uses jest to run tests, customers should run `npm i -g jest` or `npm i jest` once before Amplify CLI executes the pre-push script.

Amplify Console is automatically supported and hook scripts will be executed by the console similar to the execution on local machine. 

Customers can use third party dependency and Amplify Console simultaneously by modifying `amplify.yml` file to install dependency packages (backend preBuild). More information about running preBuild commands in console can be found in the [Amplify docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#yml-specification-syntax).
Example `amplify.yml` file snippet to install jest:

```yaml
version: 1
env:
  variables:
      key: value
backend:
  phases:
    preBuild:
      commands:
        -npm install jest -g
    build:
      commands:
        -amplifyPush --simple
```

# Appendix

### Sample generated scripts

**pre-add.js.sample** and **post-add.sh.sample** are sample scripts created on `amplify init` in the hooks directory. 

**pre-add.js.sample**

```js
// This is a sample script created by Amplify CLI.
// To start using this script please change the filename:
// pre-add.js.sample  ->  pre-add.js
//
// parameters available:
// process.argv[0] - path to node executable (default)
// process.argv[1] - path to the running script file (default)
// process.argv[2] - data - String JSON argument (passed by Amplify)
// process.argv[3] - error - String JSON argument or null (passed by Amplify)
//
// exiting with a non zero status - process.exit(1)
// will result in Amplify CLI process to exit.

const process = require("process");

const error = JSON.parse(process.argv[3]);
if (error !== null) {
  console.log("Amplify CLI emitted an error:", error.message);
  process.exit(1);
}

const data = JSON.parse(process.argv[2]);
console.log("project root path:", data.projectPath);
console.log("Amplify CLI command:", data.amplify.command);
console.log("Amplify CLI sub-commands:", data.amplify.subCommands);

process.exit(0);
```

**post-add.sh.sample**

```bash
# This is a sample script created by Amplify CLI.
# To start using this script please change the filename:
# post-add.sh.sample  ->  post-add.sh
#
# parameters available:
# $0 - path to the running script file (default)
# $1 - data - String JSON argument (passed by Amplify)
# $2 - error - String JSON argument or null (passed by Amplify)
#
# exiting with a non zero status - exit 1
# will result in Amplify CLI process to exit.

if [ -z "$(which jq)" ]; then
    echo "Please install jq to run the sample script."
    exit 1
fi

if ! [ -z "$2" ]; then
    echo "Amplify CLI emitted an error:" $(echo $2 | jq -r '.message')
    exit 1
fi

projectPath=$(echo $1 | jq -r '.projectPath')
amplifyCommand=$(echo $1 | jq -r '.amplify | .command')
amplifySubCommands=$(echo $1 | jq -r '.amplify | .subCommands | .[]')
echo "project root path:" $projectPath
echo "Amplify CLI command:" $amplifyCommand
echo "Amplify CLI sub-commands:" $amplifySubCommands

exit 0
```

# Questions for the community

* How and which particular use case(s) would be helpful to you? Are there any use cases that are missing here that Amplify team should consider?
* Which lifecycle event(s) would be most useful for you (Ex.: pre-push, post-push, pre-add-auth, etc)?
* Which values would be useful to be passed as parameters to the hook scripts?
* Which language would you prefer to use for writing hook scripts?

**Comment by cmaycumber** [comment]
This is awesome. 

> How and which particular use case(s) would be helpful to you? Are there any use cases that are missing here that Amplify team should consider?
> 
> Which lifecycle event(s) would be most useful for you (Ex.: pre-push, post-push, pre-add-auth, etc)?

I would instantly use the following lifecycles off the top of my head: 
- pre-push (Compile a custom typescript function into js inside of the function/src folder using esbuild)
- post-add-function (Create a custom function that uses typescript)
- pre-add-auth (Make sure that my custom user pool, deployed through AWS CDK, is up and running for that particular stage)

> Which values would be useful to be passed as parameters to the hook scripts?

Maybe certain configurations for functions? e.i For my use case outlined above, a `function-type` param, for example `--trigger-type=cognito-trigger` creates a typescript function that already has the types for UserPoolTriggers.

> Which language would you prefer to use for writing hook scripts?
 
Bash and Node.js

Another reason I think this RFC is so great is that I think it adds a large amount of flexibility to Amplify which I've found in the past to be limiting.

**Comment by xo28122000** [comment]
Hi @cmaycumber 
Thank you for your feedback! 
The list of use cases is super helpful to define how to structure this feature and implementation!.

> Maybe certain configurations for functions? e.i For my use case outlined above, a `function-type` param, for example `--trigger-type=cognito-trigger` creates a typescript function that already has the types for UserPoolTriggers.

The parameter would be tricky since it would be specific to the life cycle event that's executed. I'll be sure to rework the implementation to support sending hook specific parameters.

**Comment by wizage** [comment]
Are these hooks going to be available also to CLI plugins?

I.E. Exposed through the amplify-plugin.json

What I sort of discussed with @edwardfoyle

**Comment by connor4312** [comment]
> Amplify CLI will support bash(.sh) and node(.js) scripts. All scripts are auto-detected based on the extension. If there are files present with same filename and different extensions, extension with naming precedence will be executed. For customers or teams using cross platform operating system, it is recommend to use javascript over bash.

Bash may not be present for Windows users. I suggest, for a given `<hook-name>` the following:

- On posix, look for the file `amplify/backend/hooks/<hook-name>`. Given it's executable, executable directly.
   -  For convenience you may also look for `amplify/backend/hooks/<hook-name>.sh`, though using a shebang is pretty common.
- On windows, look for any file `amplify/backend/hooks/<hook-name>.<ext>`, where `ext` is any of the extensions in `process.env.PATHEXT`. If that exists, execute it directly.
- Otherwise, look for `amplify/backend/hooks/<hook-name>.js`

**Comment by armenr** [comment]
First, let me say that as an avid (daily) Amplify user/builder, I love this proposal and RFC. I tried to hack my way around exposing some kind of "entry point" that I can hook into before/after certain CLI commands (most common needs have been around pre-push, post-push, pre-pull, and post-pull).

> How and which particular use case(s) would be helpful to you? Are there any use cases that are missing here that Amplify team should consider? Which lifecycle event(s) would be most useful for you (Ex.: pre-push, post-push, pre-add-auth, etc)?

- Local tests
- Security inspection
- Actions to take pre-push (compile some typescript, build/bundle a function, render some kind of template/config file dynamically at push time, CHECK that an existing resource or endpoint exists/is responding/is up before commencing push/deploy)
- Actions to take post-pull (parse JSON, templates, or values/outputs returned from the successful push and trigger a follow-up script for doing things like smoke testing, or for grabbing some values and rendering them into a config/environment variables file, etc)

> Which values would be useful to be passed as parameters to the hook scripts? Which language would you prefer to use for writing hook scripts?

- For now, just having an "entry point" where I can specify a shell command, a shell script, or a javascript file to run before/after certain actions would be enough...can't think of parameters I'd want to pass, but it would be really nice if we could create some kind of basic YAML file to specify our scripts, and then we can make the scripts accept arguments/params we'd want to pass

### Suggestion 

IMHO, it would be really nice to expose an interface that's already conventional to Amplify (like in the amplify.yml file), and allow customers/users/builders to either include a "cli-hooks" top-level key in the `amplify.yml` file itself, or in an accompanying `amplify-cli-hooks.yml` file you can just keep in the root of the repo...

Example:

```
env:
  variables:
    SOME_ENV_VAR: some value
    SOME_OTHER_VAR: false

cli-hooks:
  phases:
    # Begin Pre-Push
    pre-push:
      commands:
        - echo "[!] I am running BEFORE pushing your backend!"
        - export STACK_NAME=$(jq -r '.providers.awscloudformation.StackName' ./amplify/#current-cloud-backend/amplify-meta.json)
        - bash my-awesome-pre-push-script.sh
        - aws ssm put-parameter --name "stackID" --type "String" --value "$${STACK_NAME}" --overwrite
        - cdk synth --profile sso-deploy-us-west-2
        - cdk deploy SomePipelineName --profile some-profile-name --region us-west-2
    # Begin Post-Push
    post-push:
      commands:
        - echo "[!] I am running AFTER pushing your backend!"
        - export SOME_ENDPOINT=$(jq -r '.some.key.with.endpoint.address' ./amplify/#current-cloud-backend/amplify-meta.json)
        - curl -s -X GET $SOME_ENDPOINT
        - bash run-basic-endpoint.sh
    # Begin Post-Pull
    post-pull:
      commands:
        - echo "[!] Execute Amplify post-push helpers"
        - cp aws-exports.js ../some-other/path/aws-exports.ts
        - cfn-lint
        - echo "[!] Rendering JSON templates into friendly YAML"
        - cfn-flip amplify/backend/api/apiv1/customResources.json amplify/backend/api/apiv1/customResources.yaml
```

**Comment by renebrandel** [comment]
Hi folks - just wanted to drop a message here that we've taken the input here and released the first version of our "Command Hooks" capabilities.

We've gone with a git-hooks-like DX for a more familiar interface but provided escape hatches for you to pull in external dependencies and also allow you to support any custom runtime like python etc. Out of the box, we support bash and Node.js.

Launch Tweet here: https://twitter.com/renebrandel/status/1436056535034056723
What's New post: https://aws.amazon.com/about-aws/whats-new/2021/09/aws-amplify-command-hooks-custom-scripts-cli/
Documentation: https://docs.amplify.aws/cli/usage/command-hooks/

Looking forward to you trying it out and provide further feedback!

**Comment by mattfysh** [comment]
Hi, hooks don't seem to survive checking out a new environment. e.g. I have `dev` checked out... create my hooks, run a push and verify they work, commit my hooks to the `dev` branch

Then I checkout prod according to the docs

```
git checkout prod
amplify env checkout prod
```

But the hooks are no longer there

**Comment by kaustavghosh06** [comment]
If you're using the git based flow, you'd also have to git merge from your dev branch to prod.
