### ISSUE TITLE
Trunk based development with multienvironment

### ISSUE THREAD

**Issue by aterreno** [aws-amplify/amplify-cli#762]
Hi there, 
I am trying to move our 'handcrafted' combination of Terraform infrastructure (S3+cloudfront distro) and single page apps (React.js built with Weback) to amplify.  

We have just two environments, dev and prod, everything works using dot env, so we have one dot env file per environment: 

```
NODE_ENV=dev
SERVICE_URL=
API_URL=
COGNITO_USER_POOL=
COGNITO_APP_ID=
```

That way the SPA gets built with those variables injected, then pushed to the right bucket/cf distro

What are the best practices to handle this sort of configuration with amplify?

**Comment by jkeys-ecg-nmsu** [comment]
I believe the new Amplify Console will let you set environment attributes that are applied at build time.

**Comment by kaustavghosh06** [comment]
@aterreno Did you get a chance to test out the Amplify console?
