### ISSUE TITLE
Amplify equivalent of gitignore?

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#7623]
Does the amplify CLI have a way to specify files/directories that should be ignored by the CLI, analogously to `.gitignore` with Git?

This seems like a generally-useful feature, but to specify my particular context:
I would like each python lambda function to include a `.venv` folder within it. 

This works fine locally, but when pushing, amplify throws an error:
`An error occurred during the push operation: ENOENT: no such file or directory, stat '/pathOfPythonLambdaFunction/venv/bin/python'`

**Comment by edwardfoyle** [comment]
Hi @ataibarkai, the CLI does not currently have a mechanism like `.gitignore`. I think the issue in this case is that the `.venv` directory contains symlinks which causes an error when the CLI tries to package the lambda for deployment. Is your `.venv` directory within the `src` folder in the function? Anything outside of the `src` folder should not be included when packaging the lambda function
