### ISSUE TITLE
Sort not working on createdAt timestamp with @key directive

### ISSUE THREAD

**Issue by bacon1097** [aws-amplify/amplify-cli#7624]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.1

### Amplify CLI Version

5.0.2

### What operating system are you using?

Windows 10

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I cannot sort by createdAt using the @key directive. The query works however the result produced is not ordered at all. When I switch between ASC and DESC, the result flips as expected but the order is not related to the createdAt field which is expected.

I have tried manually setting the createdAt field to:
- new Date().valueOf().toString() = 1624880470163
- new Date().toString() = Mon Jun 28 2021 12:41:31 GMT+0100 (British Summer Time)

To no avail... I have also tried leaving it blank in which case amplify populates the field with something looking like "2021-06-28T11:42:16.880Z" with no luck.

This issue was found when mocking the environment (using Local DynamoDb)

### Expected behavior

The result produced is an ordered list by the createdAt timestamp.

### Reproduction steps

1. Create the message entry n amount of times
```graphql
mutation CreateMessage {
  createMessage(
    input: {status: SENT, value: "Message 1", receiver: "user's_sub_attribute"}
  ) {
    id
  }
}

```

2. List the messages
```graphql
query MyQuery {
  messagesByDate(
    receiver: "user's_sub_attribute"
    sortDirection: ASC
  ) {
    items {
      value
      id
      createdAt
      receiver
    }
  }
}

```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Message
  @model
  @auth(
    rules: [
      # Owner has full access
      { allow: owner }
      # The reciever can read and update
      { allow: owner, ownerField: "receiver", operations: [read, update] }
    ]
  )
  @key(
    name: "messagesByDate"
    fields: ["receiver", "createdAt"]
    queryField: "messagesByDate"
  ) {
  id: ID!
  receiver: ID!
  deleted: Boolean
  status: MessageStatus!
  value: String!
  createdAt: String!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @bacon1097 :wave: if you change `createdAt`'s type to `AWSDateTime` will it sort as expected? I noticed in one of our examples on the docs site it originally shows `String` and then switches to `AWSDateTime` in a later example.

https://docs.amplify.aws/cli/graphql-transformer/key#example-get-orders-by-customer-email-by-createdat

**Comment by bacon1097** [comment]
Hi @josefaidt, I have indeed tried that also with no luck. Forgot to mention that in the initial issue.

**Comment by edwardfoyle** [comment]
@bacon1097 So far I have not been able to reproduce this. I used the schema and query that you specified above and observed results coming back sorted by createdAt. Can you paste a sample of what the createdAt values look like in your records?

**Comment by bacon1097** [comment]
```graphql
query MyQuery {
  messagesByDate(
    receiver: "06c690af-3bf1-4007-a951-22c34eb7a3f8"
    sortDirection: ASC
  ) {
    items {
      createdAt
      value
      receiver
    }
  }
}

```

Produces:

```graphql
{
  "data": {
    "messagesByDate": {
      "items": [
        {
          "createdAt": "2021-06-29T15:47:24.753Z",
          "value": "Message 5",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:46:18.374Z",
          "value": "Message 3",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:47:22.216Z",
          "value": "Message 4",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:47:47.919Z",
          "value": "Message 6",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:46:14.325Z",
          "value": "Message 2",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-28T11:42:16.880Z",
          "value": "Message 1",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        }
      ]
    }
  }
}

```

**Comment by bacon1097** [comment]
```graphql
query MyQuery {
  messagesByDate(
    receiver: "06c690af-3bf1-4007-a951-22c34eb7a3f8"
    sortDirection: DESC
  ) {
    items {
      createdAt
      value
      receiver
    }
  }
}

```

Produces:
```graphql
{
  "data": {
    "messagesByDate": {
      "items": [
        {
          "createdAt": "2021-06-28T11:42:16.880Z",
          "value": "Message 1",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:46:14.325Z",
          "value": "Message 2",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:47:47.919Z",
          "value": "Message 6",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:47:22.216Z",
          "value": "Message 4",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:46:18.374Z",
          "value": "Message 3",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        },
        {
          "createdAt": "2021-06-29T15:47:24.753Z",
          "value": "Message 5",
          "receiver": "06c690af-3bf1-4007-a951-22c34eb7a3f8"
        }
      ]
    }
  }
}

```

**Comment by josefaidt** [comment]
Hey @bacon1097 are you also seeing this issue if you run the query in the AppSync Console or is it only when mocking locally?

**Comment by bacon1097** [comment]
Hi @josefaidt, I am only seeing it when locally mocking so far. Just tested the AppSync Console and it seems fine there.

createdAt timestamp in the AppSync console is the same format as local versions e.g. 2021-06-30T20:20:07.920Z

**Comment by josefaidt** [comment]
Hey @bacon1097 I re-tested this in Windows 10 with changing `createdAt` types in between creating records to no avail. Are you still seeing this issue after removing the `amplify/mock-data` directory and recreating the records? Is this sorting issue affecting other models as well?

**Comment by bacon1097** [comment]
Hi @josefaidt, looks like deleting the mock directory and recreating the records worked. Sorting works as expected now.

**Comment by bacon1097** [comment]
Potentially a warning or defect still available here? To alert people that recreating the mock records is required when adding a sort key to a model.

**Comment by josefaidt** [comment]
Hey @bacon1097 glad this is working for you! I will keep an eye out for future reports of sort-related issues in mock.
