### ISSUE TITLE
Backfilling can't imports all items

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7626]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

4.45.2

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I've tried the [backfill script in the doc](https://docs.amplify.aws/cli/graphql-transformer/searchable#backfill-your-elasticsearch-index-from-your-dynamodb-table), yes it will backfill, but not all of the items in my table. 

I have only 2000+ items in my table only partial of them could be backfilled, and the number of backfilled items changes every time you run the script(I have deleted the corresponding index in ES before I run the script).

### Expected behavior

x

### Reproduction steps

x

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
Hi @yaquawa do you see any failures in the CloudWatch logs when running the backfill script?
