### ISSUE TITLE
How to upgrade Elasticsearch version?

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-cli#7628]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
API

**Amplify CLI Version** 

4.52.0

**What AWS Services are you utilizing?**
Elasticsearch

**Provide additional details e.g. code snippets**
I'm using `@searchable` to generate the Elasticsearch instance, but currently it using version 6 of Elasticsearch, how can I upgrade it to version 7?

**Comment by edwardfoyle** [comment]
Hi @yaquawa currently the only way to do this is to modify the cloudformation template that the CLI generates. You can copy the `SearchableStack.json` from `<project root>/amplify/backend/api/<api name>/build/stacks/SearchableStack.json` to `<project root>/amplify/backend/api/<api name>/stacks/SearchableStack.json` (copy it out of the build directory). Then you can update the ElasticsearchVersion property in that stack.

You'll need to be careful when making updates to your API that the override template stays in sync.

We have an RFC for several @searchable improvements, which includes upgrading to version 7: https://github.com/aws-amplify/amplify-cli/issues/7546
