### ISSUE TITLE
@searchable transforms and connections

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/amplify-cli#763]
Is there a way to get the @searchable to also work with @connection. Say I have these models.

```
type Post @model @searchable {
    id: ID!
    text: String
    votes: [Vote] @connection(name: "PostVotes")
}

type Vote @model @searchable {
    id: ID!
    vote: Int!
    post: Post! @connection(name: "PostVotes")
}
```

The generated searchVotes query would then only be able to filter on id and vote. But say I want to get all the votes for a certain postId. 

Likewise the ListVotes query doesn't either provide a filter on the post connection.

So how would I in this case go about to get all the Votes on a certain post?

**Comment by mikeparisstuff** [comment]
Hey @helloniklas thanks for the question. This is a great idea but is not yet supported, but we would love to support use cases like this in the future. I think the best way to get movement on this would be to propose a design so that we can start getting feedback from the community. We will be investing more in enhancing auth support across the transform so any design should consider what authorization would look like.

**Comment by jonmifsud** [comment]
@mikeparisstuff this is a critical part for what we'd need.

@helloniklas's scenario is fairly simple in that you can query posts and then get the votes through the standard GQL connection. 

However we are thinking of scenarios where we would need to search across joint datasets. We know in elastic there are different storage models, including structuring flat file nested properties or linking properties (meaning they'd live on the same shard - possible performance causes) - is there anywhere that could point to how we could create custom resolvers to get these to open up in a flat file? 

Using the above scenario meaning that the @searchable for Vote would contain both the Vote information + the post information.

**Comment by malcomm** [comment]
Any movement on this? I've run into this a couple of times and I have to just stop and try to go around it a different way. It seems like supporting `@searchable` and `@connection` on the basic `ID` level would be a big win and solve 80% of the issues.

**Comment by MilesDowe** [comment]
This gets a +1 from me. Maybe it's been addressed, but I've had difficulty finding documentation online.

Given:

```graphql
type ObjectA @model @searchable {
  id: ID!
  objectB: ObjectB! @connection(name: "ObjectBToA")
}

type ObjectB @model @searchable {
  id: ID!
  objectAs: [ObjectA] @connection(name: "ObjectBToA")
}
```

It would be handy to search for `ObjectA` by the `id` value of `ObjectB`.

I've so far been injecting Elasticsearch queries directly by manually modifying the `Searchable.*Filter` objects over the AppSync UI to have an `override` string attribute. I then updated their associated Resolvers to use only the `override` if it's present.

This is unsustainable, though. While I can define the Resolver as a VTL file under `./amplify/backend/api/resolvers`, there isn't a way to ensure my `override` attribute hack gets created when running `amplify push`, thus breaking code with schema updates.

**Comment by beautypassgroup** [comment]
Any movement on this please?

**Comment by Blkc** [comment]
+1 I ran into this issue today and sadly the current solution is to copy the data over to one of the @model so you can query and update without breaking.

**Comment by supercodes1223** [comment]
+1 this is a big issue for us.

**Comment by supercodes1223** [comment]
Feedback we got from Amplify team is that they prioritize these issues by their engagement on Github so please upvote this issue and add your comments so this becomes a priority to them. For us not making @connection available to @searchable is a big limitation.

**Comment by ericowhadi** [comment]
+1 stumble on the same limitation, big deal.

**Comment by jfhidakatsu** [comment]
This would be a great feature, as it would save development time for us.

**Comment by alexboulay** [comment]
Our team needs this!

**Comment by KIWI-JP** [comment]
I have also been needing this for a while on a project, so any progress towards it would be appreciated.

In the meantime, is there any way to do this with a custom resolver? @alexboulay did you find a way around it?

**Comment by alexboulay** [comment]
@KIWI-JP I ended up putting all the search terms in a list within the objects that I wanted to search. Its not the cleanest solution but it does work!

**Comment by yannikw23** [comment]
Are there any updates on this? Any help would be appreciated!

**Comment by josefaidt** [comment]
Hey y'all :wave: I wanted to follow-up on this one and show how this is now possible with GraphQL Transformer v2 and the new relational directives! Using the following schema we will be able to create a Post, create a Vote linked to the Post, then run a search query by post ID.

```graphql
type Post @model @searchable {
  id: ID!
  text: String
  votes: [Vote] @hasMany
}

type Vote @model @searchable {
  id: ID!
  vote: Int!
  post: Post!
}
```

Then we can execute the following in order to ultimately search Votes by Post ID

```graphql
mutation CREATE_POST {
  createPost(input: {text: "my first post"}) {
    id
  }
}

mutation CREATE_VOTE {
  createVote(input: {vote: 10, postVotesId: "a7173361-d420-44fd-abb9-88b26f7a506b"}) {
    id
  }
}

query SEARCH_BY_ID {
  searchVotes(filter: {postVotesId: {eq: "a7173361-d420-44fd-abb9-88b26f7a506b"}}) {
    items {
      id
      postVotesId
      vote
    }
  }
}
```

Where the search query will return:

```json
{
  "data": {
    "searchVotes": {
      "items": [
        {
          "id": "34caeece-2530-452c-8965-0f3d097b545c",
          "postVotesId": "a7173361-d420-44fd-abb9-88b26f7a506b",
          "vote": 10
        }
      ]
    }
  }
}
```

Closing issue 🙂 if you feel this does not quite cover your use case please reply back to this thread and we can re-open to investigate further!

**Comment by Hoxni** [comment]
How to search votes by text in related posts? For example how to get votes, where related post contains word "test" in field `text`?

**Comment by majirosstefan** [comment]
I am using GraphQL Transformer v2. 

If you need to **search votes by text in related posts** in the schema above, you should re-evaluate your access patterns.  
_This is typically you taking a look on how the data is accessed in your app, and then you would model relationships based on that in (the schema.graphqhl)._
 
To get search votes by text in related posts,  you can search posts by text first and then just tell AppSync to append corresponding posts:

```
query SEARCH_POSTS {
  searchPostsThatEndsWithPost: searchPosts(filter: {text: {wildcard: "*post"}}) { **// search posts**
    items {
      id
      votes {  **// sub-select votes**
        items {
          id
          vote
        }
        nextToken
      }
    }
  }
}
```

That query above would give you something like this: 

<img width="1135" alt="Screenshot 2023-08-21 at 7 32 03 PM" src="https://github.com/aws-amplify/amplify-cli/assets/44647381/e7ae5bf8-51b5-4a6a-8822-49737ffaec21">

If response is containing non-null **nextToken** somewhere, usually it means there are more results to be fetched.

Here you can see how to pass nextToken to the outer search results (`data.searchPostsThatEndsWithPost.items`): 
https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#paginate-over-search-results

<img width="833" alt="Screenshot 2023-08-21 at 7 39 21 PM" src="https://github.com/aws-amplify/amplify-cli/assets/44647381/124b0dfc-7ac3-4d8c-a6b6-0c612e68c84c">

But if those search results looks like this (indicating that not the all of nested votes have not been fetched): 

<img width="1142" alt="Screenshot 2023-08-21 at 7 50 12 PM" src="https://github.com/aws-amplify/amplify-cli/assets/44647381/48dc9524-8ca2-48ed-87b7-ccb81c96a8f0">

You would need to pass nextToken to inner _data.searchPostsThatEndsWithPost.items[x].votes.nextToken like this:  

```

query SEARCH_POSTS {
  searchPostsThatEndsWithPost: searchPosts(filter: {text: {wildcard: "*post"}}) {
    items {
      id
      votes (nextToken:"ey....fQ==") {
        items {
          id
          vote
        }
        nextToken
      }
    }
    nextToken
  }
}
```

The problem with that is that **nextToken** is applied to every subselection and you would get also this error: 

`The provided starting key is outside query boundaries based on provided conditions (Service: DynamoDb, Status Code: 400, Request ID: 3NPOT84B4B09GRITQGLGH2E32BVV4KQNSO5AEMVJF66Q9ASUAAJG)`

<img width="1279" alt="Screenshot 2023-08-21 at 8 08 25 PM" src="https://github.com/aws-amplify/amplify-cli/assets/44647381/158733a8-b421-46ba-9bf5-5982dc08e57f">

so in that case (fetching nested items) you would need to narrow down the search query to get only one post and the query would look like: 

```
query SEARCH_POSTS {
  searchPostsThatEndsWithPost: searchPosts(filter: {text: {wildcard: "*post", and: {id: {eq:"3666e229-6134-4d6e-95ed-06906ce70d85"}}}}) {
    items {
      id
      votes (limit:1, nextToken:"ey==") {
        items {
          id
          vote
        }
        nextToken
      }
    }
    nextToken
  }
}

```

It's not intuitive to use this approach, but it seems to be possible.

Another approach (that I would prefer) would be

-  to retrieve initial searched posts + nested votes using searchQuery (using default limits of Appsync)
-  and then if you need to load more votes, you can use **listVotes** query (with some filtering such as _and_ & _ne_ conditions - e.g you would pass array of the items that you do not want to fetch anymore) or you would add new _"@index"_  for that field (previously named _"@key"_) to support that access pattern

**Comment by johndebord** [comment]
I have two types:
```graphql
type Post
  @model
  @searchable {
  hash: String! @primaryKey
  user: User! @hasOne
}
```
```graphql
type User
  @model
  @searchable {
  sub: String! @primaryKey
  username: String!
}
```
I would like to search for `Post`s by the `user`'s `username` like so:
```javascript
let apiGraphQLSearchPiecePostsResult = await API.graphql({
  authMode: GRAPHQL_AUTH_MODE.AWS_IAM,
  query: searchPosts,
  variables: {
    filter: {
      user: {
        username: {
          matchPhrasePrefix "asdf",
        },
      },
    },
  },
});
```
However, this is impossible. Or is it? Is there a way to achieve something like this?

**Comment by johndebord** [comment]
Is this still not possible?
