### ISSUE TITLE
Multiple filters

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-cli#7634]
HELP! Does someone have experience where you can filter an appsync query and combine different filters.

For example:

type Product
@model
{
name
color
price
theme
category
size
....
}

I want to filter on these fields and also on all possible  combinations. With secondary indexes I have reached the limit of 20 indexes, so that is not the solution :disappointed:

It need goes over 6000 product items

**Comment by edwardfoyle** [comment]
For complex query patterns, take a look at the @searchable directive: https://docs.amplify.aws/cli/graphql-transformer/searchable

**Comment by rpostulart** [comment]
Ok so it is only possible with an additional service?
