### ISSUE TITLE
Error: Parameters: [s3Key, deploymentBucketName] must have values

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-cli#7637]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify cli

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
5.0.2

**What AWS Services are you utilizing?**
Amplify, lambda, dynamoDB

Suddenly when I try to amplify push, I'm getting this error " Parameters: [s3Key, deploymentBucketName] must have values" for each custom lambda function I have. I tried to do amplify pull --restore, amplify init or even rolling back some versions on git. But this error keeps hapenning every time  I try to do a new deploy.

**Comment by edwardfoyle** [comment]
Hi @zzBrunoBrito do you see values for those parameters in your `team-provider-info.json` file, within the respective function blocks?

**Comment by zzBrunoBrito** [comment]
Hey @edwardfoyle, I could fix it now but indeed I could not see values for those parameters on the team-provider-info.json file. The weird thing about it is that I saw on my git history that those parameters were never there and yet I could do amplify push normally, it seems that it suddenly became required. More weird than that was my fix: I notice that if I updated a function, amplify create these values on team-provider-info.json, so I updated all my functions(44) with empty spaces and amplify created the values on the team-provider-info.json and now its working.

**Comment by edwardfoyle** [comment]
@zzBrunoBrito Glad you were able to get this fixed, but sorry it was such a tedious process! Did you recently upgrade your Amplify CLI version? We made a change related to those parameters a few months ago. It should have automatically populated those values but if you ran `amplify push --force` that may have caused Amplify to try to push functions that didn't have changes which could cause this issue

**Comment by zzBrunoBrito** [comment]
Yes I did upgrade it recently. I was using a very old version and upgraded to the latest version. Thanks for the clarification!
