### ISSUE TITLE
Crash when try to push

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#7639]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

5.0.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

When I try to use `amplify push` after answering the question yes I will see **sometimes** the following error: 

> ⠸ Uploading files...✖ An error occurred when pushing the resources to the cloud
> 
> Inaccessible host: `amplify-cimplycitywebapp-staging-62032-deployment.s3.amazonaws.com'. This service may not be available in the `us-east-1' region.
> An error occurred during the push operation: Inaccessible host: `amplify-cimplycitywebapp-staging-62032-deployment.s3.amazonaws.com'. This service may not be available in the `us-east-1' region.
> ⠸ Uploading files...^Aborted!

Then it will leave `deployment-state.json` file in my S3 bucket and the bucket is there.

Also, it would cause crash other apps like Microsoft Teams and Chrome and would disconnect the internet. 

I really don't think it is a bug in those apps or my mac. I tested my machine and my internet connection. If I don't run `amplify push --y` it won't crash or close any of those programs. 

### Expected behavior

Error handling. 

### Reproduction steps

Maybe not possible in your side. But I use the latest mac mini with new macOS big Sue 11.4 on new CPUs. 

### Additional information

appId: dl91s1m9oit3p
region: us-east-1

**Comment by mjza** [comment]
I tested with my windows machine too, it is almost 30 minutes that it shows `Uploading files...` but nothing happen afterwards.

**Comment by mjza** [comment]
After several failed tries, I could finally push via my Windows machine.

**Comment by edwardfoyle** [comment]
@mjza, how large is the zip of your #current-cloud-backend directory? And do you have any large lambda functions? (You can check the size of the `latest-build.zip` file in the function `dist` directory).

**Comment by mjza** [comment]
Where can I find that `dist` folder?

**Comment by mjza** [comment]
@edwardfoyle Anyway just for your information: I updated the amplify and now on the mac also when I try to push it does not disconnect the Internet.

**Comment by cjihrig** [comment]
@mjza are you saying that the problem is resolved now? Is it possible you had a bad Internet connection when you were experiencing problems?

**Comment by mjza** [comment]
@cjihrig I am sure it was not internet connection, I even disconnected my Wifi and used LAN. I used the same provider on two machines and I am sure the internet was there. Just when I ran the `amplify push` it disconnect my internet on my mac. 

Yes the problem resolved by installing the version 5.1.0.
