### ISSUE TITLE
when checkout env: ERROR: No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json

### ISSUE THREAD

**Issue by fgiopp** [aws-amplify/amplify-cli#7640]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.4

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I have created a new lambda layer on SVIL env and pushed it correctly.

When I try to checkout on TEST with: 
`$amplify env checkout test`

I get the following error:

```
No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json
Error: No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json
    at Object.readCFNTemplate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/cfnUtilities.ts:9:11)
    at Object.updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:408:57)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:131:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Expected behavior

`amplify env checkout test`
then 
`Initialized your environment successfully.`

### Reproduction steps

```
1) amplify env checkout svil
2) create a new lambda layer
3) amplify push --yes
4)  amplify env checkout test
   ---> ERROR
```

**Comment by edwardfoyle** [comment]
Hi @fgiopp, on the last step, can you try passing in the `--restore` flag and see if that allows you to check out the other environment successfully? ie `amplify env checkout test --restore`

**Comment by fgiopp** [comment]
I have noticed that despite the Error, the checkout to the environment (TEST) was like almost complete. So, I was able to push TEST. After that I checkout back to SVIL and then finally again to TEST, this time without the Error.
