### ISSUE TITLE
amplify env remove does not remove lambda layer

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#7641]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

5.1.0

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

env

### Describe the bug

`amplify env remove` does not delete lambda layers associated to the env being removed.

### Expected behavior

When removing an environment, all cloud resources associated to that env should be deleted upon successful completion of the `amplify env remove` command.

### Reproduction steps

Using the amplify cli:
- start from an env "envone" with a lambda layer and a function using that layer
- add new env "envtwo" and push
- checkout "envone" 
- execute `amplify env remove envtwo` 
- open layers page of console.aws.amazon.com/lambda/ and verify that layer created for "envtwo" was not deleted

**Comment by edwardfoyle** [comment]
Hi @cfbo, do you know what version of the CLI you used to create the Lambda layer? If it was created with CLI version >= 5.0.0, the layer should be removed automatically. If it was created with an earlier version of the CLI, for now you'll have to manually remove the deleted layer version from the cloud.

**Comment by cfbo** [comment]
Hi @edwardfoyle, thanks for your answer. It is pretty likely that it was created with a version older than 5.0.0 because it was created few weeks ago and I suppose 5.0.0 was released later than that. 
So, does this mean that in our case, when creating new envs and then removing them, it will keep not to delete layers? If that's the case, do you suggest to re-create the layer from scratch so that this issue will go away?

**Comment by cfbo** [comment]
I am closing the issue because it seems that with version >5.0.0 the lambda layer is working fine now
