### ISSUE TITLE
Connect a Cognito user with an AppSync type

### ISSUE THREAD

**Issue by thathurtabit** [aws-amplify/amplify-cli#7645]
This is a continuation of https://github.com/aws-amplify/amplify-cli/issues/1313 which was closed and locked without guidance on how to complete this task with Amplify.

I'd preface this with acknowledging I'm new to Amplify (and general stitching together of AWS services), so I'm sure I'm missing something simple somewhere in docs.

To reiterate the question - after using something like `Amplify UI (react)` to create a new user (stored as a `Cognito User`?), how then do you connect this user to a Data Model? I.e. one `Cognito User` could be the owner of many `Posts` - but the `Cognito User` is not available and seemingly unknown with regards to the Data Model? I.e. Un-queryable by `GraphQL`?

I'd imagine there would be a way to sync a `Cognito User` with a `User` data model, as this would almost always need to be done but can't find anything in the documentation. The original issue: https://github.com/aws-amplify/amplify-cli/issues/1313 mentions updating the docs, but doesn't a provide a link to that document?

Really hoping I can find some help on this, cheers.

**Amplify CLI Version** 
5.0.1

**What AWS Services are you utilizing?**
Amplify, Amplify Admin UI, Amplify UI (react)

**Comment by edwardfoyle** [comment]
Hi @thathurtabit, it sounds like what you're looking for is [owner based auth rules](https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization). Using the @auth directive in your GraphQL model will generate additional resolver logic and add an "owner" field to the model. We don't have a directive like @user to directly link a Cognito user and a schema type together

**Comment by thathurtabit** [comment]
Ah thanks @edwardfoyle ! That sounds promising 👍 I'll give that a go and close this shortly.
