### ISSUE TITLE
Syntactically incorrect schema gets pushed to amplify and irreversibly corrupts entire project

### ISSUE THREAD

**Issue by ayhoung** [aws-amplify/amplify-cli#7648]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g amplify-cli

### Amplify CLI Version

4.52.0

### What operating system are you using?

Mac OS X Big Sur

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Amplify pushes syntactically incorrect graphql schema to the cloud, which irreversibly corrupts the entire project, forcing a project recreate.

```
type Billing @model {
  @key(name: "byUser", fields: ["user_id"]){
  id: ID!
  user_id: ID
  type: String
  credit_card_no: String
  credit_card_expiry: String
  credit_card_holder_name: String
  address_one: String
  address_two: String
  city: String
  country: String
  zipcode: Int
}
```

the above was the syntactically incorrect schema, note the `{` before the `@key`

### Expected behavior

amplify push --yes should reject this incorrect schema, but in this instance, the push was accepted and corrupted the entire project

### Reproduction steps

1. Use the above incorrect code to push to schema

### GraphQL schema(s)

<details>

```graphql
type Billing @model {
  @key(name: "byUser", fields: ["user_id"]){
  id: ID!
  user_id: ID
  type: String
  credit_card_no: String
  credit_card_expiry: String
  credit_card_holder_name: String
  address_one: String
  address_two: String
  city: String
  country: String
  zipcode: Int
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
No matter how I chance the schema.graphql file, it will still give me the same error as:
GraphQL request:54:3
53 | type Billing @model {
54 |   @key(name: "byUser", fields: ["user_id"]){
     |   ^
55 |   id: ID!

```

</details>

### Additional information

I've had a back and forth between AWS support on this issue, their response is that is a rare occurrence but the entire environment would have to be recreated.

**Comment by edwardfoyle** [comment]
Hi @ayhoung can you check the contents of your GraphQL schema in your deployment bucket:
1. In your local project, navigate to `<project root>/amplify/backend/api/<api name>/build/parameters.json` and find the `S3DeploymentRootKey` value (you'll need this in a later step)
2. Navigate to the S3 console [here](https://s3.console.aws.amazon.com/s3/home)
3. Search for the deployment bucket for your project and environment
4. Within that bucket, open up `amplify-appsync-files`, then the folder corresponding to the value from step 1
5. Download the `schema.graphql` file in that folder and check if it has the syntax error. If so fix the syntax error and replace the schema in s3 with the corrected one

If the schema in the s3 bucket does NOT have the syntax error, then we'll need to do some additional debugging.

**Comment by ayhoung** [comment]
@edwardfoyle unfortunately I've already deleted the environment. i'll see if I can recreate it when I have time

**Comment by GeorgeBellTMH** [comment]
#5972 may have helped...
