### ISSUE TITLE
privacy.authRoleName and privacy.unAuthRoleName in api-params.json (REST api) are environment specific

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#7649]
Hi @ksokol 

We are using multiple environments and each time we create a new one, I find myself manually updating privacy.authRoleName and privacy.unAuthRoleName in api-params.json in order to match the new env.

If I run `amplify api update`
![image](https://user-images.githubusercontent.com/7568421/124266939-e8c76d00-db37-11eb-8052-bcf805ba232a.png)

I get the following changes:
![image](https://user-images.githubusercontent.com/7568421/124267019-05fc3b80-db38-11eb-8b9d-0c10cc256d94.png)

I was reading your answer there: https://github.com/aws-amplify/amplify-cli/issues/4984#issuecomment-673688143 and it was very helpful. However I am still not sure whether what are saying there is that I shouldn't need to update as I am doing above.

What I know for sure is that when switching to a new env, that value isn't automatically updated to match the new env. Everything else in amplify seems to work in a way where when switching to an env, everything relates to that env and is parametric on the env. It seems odd that env X has reference to something from env Y. So far this is the only instance that I have seen in amplify working in this way.

Your feedback on this would be very helpful, i.e. helping me understand if I should keep manually making the changes on each branch associated to an env or just keep it as it is, even if it reference another env.

#4984

**Comment by edwardfoyle** [comment]
Hi @cfbo those values are not used by the CLI anymore and can safely be removed. The auth and unauth role names are injected into the CloudFormation templates at push time based on the current environment.

**Comment by cfbo** [comment]
Hi @edwardfoyle,

Thanks for your reply. Based on that, I have proceed with the removal on such values:
![image](https://user-images.githubusercontent.com/7568421/124441535-0edd4f00-dd7c-11eb-8342-777c07cde063.png)

If I got it wrong, please let me know. Otherwise thanks again for your kind help.
