### ISSUE TITLE
Serverless container secret is created but not injected

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#7661]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

16.4.1

### Amplify CLI Version

5.1.0

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

The `docker-compose.yml::secrets` field is not working, as documented here: https://docs.amplify.aws/cli/usage/containers#environment-variables-and-secrets

I understand I need to run `amplify push` _without_ `-yes` so that I can engage with the following prompt:

```
? Secret configuration detected. Do you wish to store new values in the cloud? Yes
```

I observe that:

1. A new secret is created in Secrets Manager
2. The new secret contains the correct value
3. `process.env.DB_PASSWORD` is undefined at container runtime

### Expected behavior

`process.env.DB_PASSWORD` should be populated with the contents of the secret that was created when `amplify push` was run

### Reproduction steps

1. Use the documentation at the linked URL to attempt to get secrets working in serverless containers
2. Observe that `process.env.DB_PASSWORD` is not populated inside the container

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mattfysh** [comment]
I'm attempting a workaround by hard-coding the secret name, and using the SecretsManager API to retrieve the secret... but I'm not sure this will work either as the container role policy may not have enough permissions to retrieve the secret

**Comment by mattfysh** [comment]
Yep that failed...

```
User: arn:aws:sts::<snip>:assumed-role/<snip> is not authorized to perform: secretsmanager:GetSecretValue on resource: amplify-<snip>
```

Guess I will just hard code my secrets into the code repo for now, need to keep moving. I will say though - if you're going to add secret management functionality to Amplify, don't half-ass it. Developers are going to be understandably anxious about how the framework handles secrets and will want to have trust that if secrets-related functionality is being included and documented, that it works reliably and safely.

**Comment by mattfysh** [comment]
I took a look through the codebase to see if I could fix, couldn't figure out what the fix is but thought I'd cc a few folk who contributed to `packages/amplify-category-api/src/provider-utils/awscloudformation/containers-handler.ts`

cc @edwardfoyle @elorzafe @undefobj @manueliglesias

**Comment by attilah** [comment]
@mattfysh try to reference the secret in the container part of your compose file to get it populated into the CFN template and that should solve your problem, for example: 

```yaml
version: "3.8"
services:
  express:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - public
      - private
    environment:
      - MY_ENV=Foo
    secrets:
      - SECRET_1
secrets:
  SECRET_1:
    file: ../secrets/.secret-secret1.txt
networks:
  public:
  private:
 ```

This is the part that needs to be added:
```yaml
    secrets:
      - SECRET_1
```

Let me know if this works for you as it is not in the documentation, let's ask @elorzafe answer if this is the expected way or not?

Get back to us and tell if this solved your problem or not.

**Comment by mattfysh** [comment]
This works 🎆  thank you!! 🙇  just seems like the docs need a small update.

Shameless plug 💡  I've also created a new issue around getting an X-Ray sidecar working: https://github.com/aws-amplify/amplify-cli/issues/7713
