### ISSUE TITLE
obsolete auth instance not removed from remote env

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#7669]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.1.0

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

In our project we had added auth, then we have removed it to create a new one with a different configuration.
The obsolete auth is not referenced in any file anymore, but when I do an `amplify pull --restore` I keep getting the files 
![image](https://user-images.githubusercontent.com/7568421/124626868-57c9fc00-de7f-11eb-9660-5d54fec8e59d.png)
This seems to occur only in one of the env. If I create a new env from scratch, it just won't add the obsolete stack and the issue doesn't occur.
I haven't found a way to get rid of that obsolete auth: it's not in Cognito, it's not in any cloudformation file.. I don't how to get rid of it.

### Expected behavior

When running `amplify auth remove xx` I expect that stack to be removed locally and remotely. If I then push the changes into git, when merging into a different branch associated to another env, I would expect that env to be updated to point to the new auth (which works), but also to remove all files related to the that obsolete auth (which is the issue).

### Reproduction steps

- on branch 1, add auth-x to env-a, push to branch-1
- checkout branch 2, merge branch-1 into branch-2 where CI/CD is configured (automatic build) with env-b 
- == env-b should have auth-x
- remove auth-x to env-a, add auth-y to env-a, push
- checkout  branch 2, merge branch-1 into branch-2 (this will update CFN for env-b removing all references to auth-x), git push to branch 2 == env-b should have auth-y and env-x should be removed  (automatic build on amplify) 
- checkout branch-2, checkout env-b, do an `amplify pull --restore` >> if the pull brings back files related to auth-x, that's the issue

**Comment by cjihrig** [comment]
> I haven't found a way to get rid of that obsolete auth: it's not in Cognito, it's not in any cloudformation file.. I don't how to get rid of it.

When you say that the auth is not in any CFN file, do you mean local files only? Can you also confirm whether or not it exists in your deployed version.

In your last step, you're running `amplify pull --restore`. That should overwrite any local changes with what is in the cloud. If the auth still exists in the cloud, that may explain what's happening. Have you pushed the changes to env-b in the cloud?

**Comment by cfbo** [comment]
Thanks coming back to this. I have to admit it's not easy to remember the exact steps, which I am aware it's not great to attempt reproducing the issue.
The main point is env-b is configured to build automatically in amplify upon new commits to branch-2.
While for env-a I did an explicit amplify auth remove and amplify push, for env-b I shouldn't need to that because CFN is updated with a new auth (auth-y). The pipeline build correctly introduced auth-y in env-b, the problem is that it didn't remove files and folder of auth-x (remotely), even if not referenced in CFN anymore. So when I do a pull - - restore they come back to life locally. I don't have a way to remove them remotely. If I execute amplify auth remove auth-x it gives me an error (because not in config), cut) but the folder is there.

Anyways, it's not a big deal, I think it's an edge case and not that easy to reproduce. I myself don't currently have the time to try a full reproduction of the issue.
I am fine with closing the ticket if need be.

**Comment by cjihrig** [comment]
Thanks @cfbo. If you're able to reproduce it consistently, feel free to come back to this issue.
