### ISSUE TITLE
What exaclty `--no-gql-override` flag do?

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#767]
** Which Category is your question related to? **
cli flags

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **

I have a hard time to understand what does exactly `--no-gql-override` flag on `amplify push` do?

Does it prevent overriding resolvers? If so, should it then be called `--no-VTL-override`?

A side question. Is this flag available on `multienv` version of the cli? I am using this version and my VTL resolvers are overriding despite the flag.

**Comment by kaustavghosh06** [comment]
@sakhmedbayev It doesn't override the resolvers and the schema and the CFN templates when you have the flag. I tried to replicate your issue and wasn't able to. Could you install the latest version of the CLI and test to see if your resolvers gets overwritten or not when you use it with amplify push?

**Comment by sakhmedbayev** [comment]
@kaustavghosh06 my current version of cli is multienv.33. Can you please test it? Try to add a new field to an existing Graphql type with @model decorator.

**Comment by kaustavghosh06** [comment]
@sakhmedbayev This is not the behavior with the latest version of the CLI. You can update it using `npm install -g @aws-amplify/cli@multienv` and re-open the issue if you're still stuck.
