### ISSUE TITLE
Can't use @auth directive : " client_id, client_secret and authorize_scopes are all required idp details " 

### ISSUE THREAD

**Issue by DeerajTheepshi** [aws-amplify/amplify-cli#7679]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

5.0.1

### What operating system are you using?

Arch Linux

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

After adding @auth directives to my schema.graphql file (To support cognito user pool based Authorization), I tried to push the api using ``` amplify push api -y ``` , however the cloudformation stack update failed with the following error on the resource ``` HostedUIProvidersCustomResourceInputs ```:

``` UPDATE_FAILED      HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Wed Jul 07 2021 15:53:19 GMT+0530 (India Standard Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/07/[$LATEST]f7d49c85b58e436b92165600a9d0f615 (RequestId: 0fa33873-17b7-48aa-82ef-aca0e1b1447b) ```

On further inspection of the logs from cloud watch:
``` {
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/07/07/[$LATEST]c4620f97c4e14af3bb513363934b59e3",
    "PhysicalResourceId": "2021/07/07/[$LATEST]c4620f97c4e14af3bb513363934b59e3",
    "StackId": "arn:aws:cloudformation:ap-south-1:203285624879:stack/amplify-amplifybackend-dev-165627-authamplifybackend2556f592-1CGKQZ7OY9OR1/56f50a70-d558-11eb-9c6e-06141c4adade",
    "RequestId": "81973275-589e-4603-ac10-24af8612903c",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "client_id, client_secret and authorize_scopes are all required idp details.",
            "code": "InvalidParameterException",
            "time": "2021-07-07T09:54:18.340Z",
            "requestId": "33f86c30-84ac-47c8-8dfc-cfc1064c74ff",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 81.41210741461092
        }
    }
}
```
NOTE: We are not using any OIDC Authentication. But Google and Facebook app logins are configured.

### Expected behavior

Amplify push is expected to add resolvers for the @auth directive as mentioned in the schema file and deploy it perfectly.

### Reproduction steps

1. Add @auth Directives to a few types in schema.graphql
2. Update API authentication to Cognito User Pool.
3. Run ``` amplify push api -y ```
4. I think you also need to ensure that the Authentication used is enabled for google and FB authentiation

### GraphQL schema(s)

Providing a small example:

```type User
  @model
  @auth(rules: [{ allow: owner, ownerField: "userID", identityClaim: "sub" }])
  @searchable {
  id: ID! # id is same as firebaseId
  firstName: String!
  middleName: String
}
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@DeerajTheepshi can you run `amplify push` and see if you are still facing this error?

**Comment by DeerajTheepshi** [comment]
Sorry for not updating. 
amplify push instead of amplify push api worked, but then occasionally I encountered the error some other times too.

I guess this can be closed.
