### ISSUE TITLE
Template may not exceed 1000000 bytes in size.

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#7680]
My org has been using Amplify CLI to create our Graphql API. We have recently hit a limit apparently related to the size of CF Templates exceeding 1MB.

We have a relatively large API but never expected to hit this limit. 

What could be the course of action from here?

What I have tried:

- Disabling subscriptions since we do not currently use them ( not good long term since the plan was to use them )
- Removing objects that aren't used ( not good long term since we will always feel squeezed by this limit )

I'm really scratching my head on this one...Is it possible we are doing something completely wrong or Amplify CLI was only meant for very small projects?

Any insights is appreciated.

**Comment by cjihrig** [comment]
@alexboulay what version of the CLI are you using? Also, would you be willing to share your GraphQL API with us at amplify-cli@amazon.com?

**Comment by cjihrig** [comment]
Can you please share which stack is failing as well.

**Comment by alexboulay** [comment]
Yes. I will absolutely send that your way with the issue id referenced in the subject line.
I just want to make sure I know everything about the env when it is falling because this occurred with another member of my team on his sandboxed environment.
This week, I will reproduce this error in our dev environment with the latest CLI version.
Thank you very much.

**Comment by AlessandroAnnini** [comment]
I have the same problem, any news about this?

**Comment by kaustavghosh06** [comment]
@alexboulay are you still stuck on this issue?

**Comment by kaustavghosh06** [comment]
Closing due to lack of further communication and response.
