### ISSUE TITLE
amplify push generate wrong Query field on AppSync

### ISSUE THREAD

**Issue by wjnpeter** [aws-amplify/amplify-cli#7692]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

amplify push generate wrong Query field on AppSync

### Expected behavior

Expect generate a Query field with listXXXs

### Reproduction steps

1. Given I have this schema:
type AnimalData @model {
    id: ID!
    name: String!
}

2. Run amplify push
3. Head to AppSync -> Schema
4. Found the generated schema for Query:
type Query {
	getAnimalData(id: ID!): AnimalData
	listAnimalData(filter: ModelAnimalDataFilterInput, limit: Int, nextToken: String): ModelAnimalDataConnection
}
5. See the listAnimalData without "s" at the end(Wrong)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
"Data" is plural, so I think this is working as intended.
