### ISSUE TITLE
Functions are including devDependencies on upload

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#7696]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

latest

### What operating system are you using?

MacOS

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

devDependencies are included in the zip file uploaded to lambda.

### Expected behavior

no dev dependencies should make it to aws...

### Reproduction steps

add some dev dependencies to a function, and push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
It sounds like we need to add `--production` when invoking npm.
