### ISSUE TITLE
Add a CLI prompt asking the customer if they are using Amplify or the SDK 

### ISSUE THREAD

**Issue by poojamat** [aws-amplify/amplify-cli#7707]
### Is this related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

Add a CLI prompt asking the customer if they are using Amplify or the SDK (default to Amplify), and only generate files if they are using the SDK. Otherwise it causes compilation errors and is confusing for user.

### Describe the solution you'd like

Add a CLI prompt asking the customer if they are using Amplify or the SDK (default to Amplify), and only generate files if they are using the SDK. Otherwise it causes compilation errors and is confusing for user.

### Describe alternatives you've considered

The alternative is we ask user to delete the folder if there are compile time failures.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by ammarkarachi** [comment]
@poojamat Can you let us know of your use case and what you are trying to achieve?
