### ISSUE TITLE
Getting "Uploaded file must be a non-empty zip" error when deploying

### ISSUE THREAD

**Issue by mrsln** [aws-amplify/amplify-cli#7714]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

5.1.1

### What operating system are you using?

Mac

### Amplify Categories

storage, function

### Amplify Commands

push

### Describe the bug

I haven't touched our Amplify Project for some time. Today I needed to debug one of the functions but I'm getting the following error when I'm trying to deploy (`amplify push -y --force`)

```
CREATE_FAILED               LambdaLayerVersion0bd85cbe                                                          AWS::Lambda::LayerVersion  Mon Jul 12 2021 20:15:34 GMT+0500 (Yekaterinburg Standard Time) Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: bb67a787-871c-4efb-acae-63699c032f46; Proxy: null)
```

I can see that other functions have non-empty zip files in the `dist/` directory, except for the Layer function. 

### Expected behavior

successful deployment

### Reproduction steps

1. `amplify push -y --force`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I have tried using the LTS node and the latest node and removing the file from s3.

**Comment by ammarkarachi** [comment]
@mrsln I see you have made no changes to the Lambda Layer itself. Can you make sure of the following things?

- The Lambda Layer has a `lib` and or `opt` folder under the folder
- The layer configuration has a runtime specified
-

**Comment by mrsln** [comment]
Thank you for the reply @ammarkarachi! 
What changes should I make to the Lambda layer and how do I go about it?

- yes, the Lambda layer has the `lib` and `opt` folders
- it does not have runtime specified, according to the AWS Lambda Layers dashboard
![image](https://user-images.githubusercontent.com/96596/125586195-621bcde0-b20a-42db-b172-be69ce60ca71.png)

- there are no files in the `opt` folder

I'm new to AWS. As I understand, the corrupted zip file with layer files is built on my machine when I run `amplify push`. How is it connected with the layer's runtime?

**Comment by mrsln** [comment]
It started working after I've put a random file in the `opt` folder. My function does not use that version of the layer so I'm not sure if the layer is working but this is good enough for me right now. So the issue is solved for me. Thank you!

**Comment by jhockett** [comment]
Glad to hear you're unblocked @mrsln! A layer with no runtime specified and no files in the `/opt` folder will produce an empty zip file which is why the push failed. Closing this issue.
