### ISSUE TITLE
UPDATE_FAILED Parameters: [authRoleName, unauthRoleName] do not exist in the template

### ISSUE THREAD

**Issue by karldanninger** [aws-amplify/amplify-cli#7716]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

5.1.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

update

### Describe the bug

Running `amplify update api` to update a REST api, specifically a individual route, results in the following diff:

```
...

diff --git a/amplify/backend/api/someApi/someApi-cloudformation-template.json b/amplify/backend/api/someApi/someApi-cloudformation-template.json
index bc5a766..976020a 100644
--- a/amplify/backend/api/someApi/someApi-cloudformation-template.json
+++ b/amplify/backend/api/someApi/someApi-cloudformation-template.json
@@ -3,12 +3,6 @@
     "Description": "API Gateway resource stack creation using Amplify CLI",
     
     "Parameters": {
-        "authRoleName": {
-            "Type":  "String"
-        },
-        "unauthRoleName": {
-            "Type":  "String"
-        },
         "env": {
             "Type": "String"
         },
@@ -18,13 +12,13 @@
             "Type": "String",
             "Default": "functionsubscriptionName"
           },
-        
+
           
           "functionsubscriptionArn": {
             "Type": "String",
             "Default": "functionsubscriptionArn"
           }
-        
+

...
```

Running this command seems to remove a required definition used to deploy...

### Expected behavior

Don't remove required attributes.

### Reproduction steps

1. amplify update api
   - choose REST
   - choose API to update
   - chose route to update
   - follow the steps
1. amplify push

### Log output

UPDATE_FAILED      apisomeApi  AWS::CloudFormation::Stack Tue Jul 13 2021 14:50:13 GMT-0400 (Eastern Daylight Time) Parameters: [authRoleName, unauthRoleName] do not exist in the template
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_IN_PROGRESS project-master-20190528103403-apiproject-119PZXB62MQ7B AWS::CloudFormation::Stack Tue Jul 13 2021 14:50:13 GMT-0400 (Eastern Daylight Time) Initiated by parent stack
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               apiproject                    AWS::CloudFormation::Stack Tue Jul 13 2021 14:50:24 GMT-0400 (Eastern Daylight Time) Resource update cancelled

**Comment by karldanninger** [comment]
Referencing this closed Issue https://github.com/aws-amplify/amplify-cli/issues/2519 although not solved.

**Comment by cjihrig** [comment]
Can you check `amplify/backend/api/someApi/parameters.json` for those parameters? If they exist, you can remove them and try pushing again.

**Comment by karldanninger** [comment]
Hey @cjihrig, that was it, thank you.

Any info you can share with me on why this is?

**Comment by cjihrig** [comment]
Those parameters are supposed to be automatically removed. I'll look into why that did not happen.

**Comment by karldanninger** [comment]
Cool, well I'm unblocked, so thank you.
Looking forward to any insights you might share on this topic.

**Comment by warrenmcquinn** [comment]
Just chiming in to say that I also encountered this issue, and these exact parameters were listed in `amplify/backend/api/someApi/parameters.json`. Thanks for the workaround for now!

**Comment by josefaidt** [comment]
Hey y'all :wave: I've confirmed the CLI will update the `parameters.json` file automatically.

1. Create an API with Amplify CLI version 4.29.2
2. run `amplify push`
3. Upgrade to Amplify CLI version 5.4.0 (latest version at the time of writing, also confirmed with 5.1.1)
4. Add/update a route on the API
5. run `amplify push`
6. observe parameters are removed

```
git diff main:amplify/backend/api/api7716/parameters.json amplify/backend/api/api7716/parameters.json 
diff --git a/amplify/backend/api/api7716/parameters.json b/amplify/backend/api/api7716/parameters.json
index f88dfa2..9e26dfe 100644
--- a/amplify/backend/api/api7716/parameters.json
+++ b/amplify/backend/api/api7716/parameters.json
@@ -1,8 +1 @@
-{
-    "authRoleName": {
-        "Ref": "AuthRoleName"
-    },
-    "unauthRoleName": {
-        "Ref": "UnauthRoleName"
-    }
-}
\ No newline at end of file
+{}
\ No newline at end of file
```

If you are still experiencing this issue please reply back to this thread with the CLI version you are attempting to upgrade to or refer to the workaround noted above to manually remove these parameters.

**Comment by kaustavghosh06** [comment]
Closing based on last response and no further communication or related issues tied to this. Please let us know if you're still stuck on this issue.
