### ISSUE TITLE
Storage env vars not added to lambda function

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/amplify-cli#7718]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

node 14

### Amplify CLI Version

5.1.1

### What operating system are you using?

mac

### Amplify Categories

storage, function

### Amplify Commands

add

### Describe the bug

1. When adding a lambda trigger that accesses a table and no resources, the environment variables for ENV, REGION, and TABLE_NAME show up in both the CLI and get printed for reference in the lambda itself.

When doing the same thing, but additionally selecting storage as a resource one would like access to, those environment variables are not added to the generated lambda function.

### Expected behavior

I would expect the STORAGE_BUCKETNAME_BUCKET env var to be printed along with all the other env vars.

### Reproduction steps

In this blog post: https://dev.to/mtliendo/create-a-resume-uploader-using-aws-amplify-2e17

*Add auth
* add an api
* add storage
* add a function

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Candidate 
  @model 
  @auth(rules: [{ allow: owner, operations: [create, update] }]) {
    id: ID!
    name: String!
    email: String!
    resumeFile: String!
    userIdentity: String!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@mtliendo It looks like it does it when I don't assign it Custom variables.

**Comment by mtliendo** [comment]
Ah thanks for the insight! I see you added this to the bug bash, thanks for the quick followup!
