### ISSUE TITLE
Issues with REST APIs and multienv

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-cli#772]
**Describe the bug**
When using `amplify-cli multienv` and adding a REST API (GraphQL works fine), all of the different amplify environments will create an API Gateway with the same name, and will therefore overwrite each other.

**To Reproduce**
1. Using multienv, `amplify init` a new environment (env1)
2. In env1, `amplify api add` a REST API
3. Use `amplify push` to create the API Gateway in the cloud (jt will have a stage named env1)
4. `amplify init` to create env2
5. Again call `amplify push` and see that there is still only one API Gateway, and it only has a single stage, env2 (env1 will be gone)

**Expected behavior**
Each amplify env should have its own API Gateway with a unique name (appending the name of the env to the API Gateway name, as is done for other resources, would be sufficient).

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: All
 - Version @aws-amplify/cli@0.2.1-multienv.14

**Comment by kaustavghosh06** [comment]
@zjullion I was trying to reproduce the problem, but wasn't. Are you sure you did an `amplify push` in both your environments? 
Below is my screenshot of both the API's which I created (REST API) which each have a stage corresponding to their env name.

![image](https://user-images.githubusercontent.com/7247658/51779097-1a5fc280-20ba-11e9-95ab-00534eedc359.png)


API Gateway doesn't overwrite the API's with same names.

**Comment by zjullion** [comment]
@kaustavghosh06 - there may be an issue on my end.  Looking at the cloudformation template I can see:

```
"DeploymentAPIGWpaymentApi": {
        "Type": "AWS::ApiGateway::Deployment",
        "Properties": {
          "Description": "The Development stage deployment of your API.",
          "StageName": {
            "Fn::If": [
              "ShouldNotCreateEnvResources",
              "Prod", 
              {
                "Ref": "env"
              } 
            ]
          },
          "RestApiId": {
            "Ref": "paymentApi"
          }
        }
      }
```

I'll investigate this further on Monday.  I apologize in advance if this is a false alarm.

**Comment by zjullion** [comment]
I've tried today to deploy the same stack in a second env, and a second API was created with its own stage.  This is a false alarm - my apologies.  Need to test more thoroughly next time!
