### ISSUE TITLE
Function not in new environment

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#7720]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

env, push

### Describe the bug

My new function which I developed in my environment `dev` is not available in my environment `staging`.

I added a new function `graphqlResolver`, pushed it on dev -> Everything is working
Then I switched to my staging environment and the function is not present in my team-provider or in the cli output.

### Expected behavior

I expect that I add a function in one environment and when switching to the other environment it'll be created as well. 
Like described (imo) here: https://docs.amplify.aws/cli/teams/overview

### Reproduction steps

1. `amplify env checkout dev`
2. `amplify add function`
3. Add function ...
4. `amplify push`
5. `amplify env checkout staging`
6. `amplify push`

Function is not there

### Additional information

The function is in the team-provider.json present for the development env but not for the staging env. 
Can I somehow import it?

**Comment by kaustavghosh06** [comment]
@AlessandroVol23  What's the output of `amplify status` command in your staging environment?

**Comment by AlessandroVol23** [comment]
The output doesn't show any new `graphqlResolver` (which is the new function) 

![image](https://user-images.githubusercontent.com/19362086/125584948-a0cfffb5-e0f8-403c-ba64-0856e476faee.png)

**Comment by ammarkarachi** [comment]
@AlessandroVol23 Can you share your file `amplify/team-provider-info.json` file removing any sensitive data?

**Comment by josefaidt** [comment]
Hey @AlessandroVol23 :wave: I was able to reproduce this when I connected my project to Git with the following steps:

1. init amplify project, init git repo
2. `amplify add auth`
3. `amplify push`
4. git add, commit, push to `main`
5. `git checkout -b next`
6. `amplify env add` with name `next`
7. `amplify update auth`, add post-confirmation trigger
8. `amplify push`
9. git add, commit, push to `next`
10. `git checkout main`
11. `amplify env checkout main`
12. `git merge next -X theirs`
13. `amplify push`
14. observe auth is showing "update" while function does not exist

Although I was not able to recreate this issue without connecting to git, this process follows our [documented procedure for working with multiple environments](https://docs.amplify.aws/cli/teams/sandbox). Marking this as a bug
\cc @ammarkarachi

**Comment by AlessandroVol23** [comment]
Actually I could get it running by going back to develop and doing the workflow again, so it is not reproducible anymore for me. If it is not a proper bug you can close it if you want.

Thanks anyway for your help!

**Comment by josefaidt** [comment]
@AlessandroVol23 glad to hear you are no longer blocked 🙏 we'll keep this issue opened to track the bug. I was also able to work around the issue using the same process

**Comment by josefaidt** [comment]
Hey @AlessandroVol23 those reproduction steps I posted were for a different bug related to auth triggers, not just functions 🙈 I'll remove the bug label and close this issue.
