### ISSUE TITLE
Adding new env sometimes fails with Ressource is not the in the state stackUpdateComplete

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#7723]
**Amplify CLI Version** 
5.0.2

I have a strange problem that seems to be intermittent while creating environments.

I am trying to create dev environments for a few developers. I have successfully created one by starting from our current `dev` environment which is in a good and working state.

What I do in terms of CLI commands:

- `amplify env checkout dev`
- `amplify env add`
- Select `No` to the question `Do you want to use an existing environment?`
- Follow the rest of the prompts to create the env
- `amplify push`

When I first tried that I got the following output after a few minutes of running:

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/70296188/125672661-f40a7022-f405-45ef-8dfa-eee554fc42bd.png">

However, everything went well and the stack was successful when I look at CloudFormation.

This seems to cause sort of a desync between CF and the amplify env. If I go to Amplify console, it says the env has No enabled categories...

I deleted the stack and then tried to create a new env and everything went well: the CLI continued to show output from the stack creation and it gracefully finished as with any successful push.

This morning, I tried to create a second new environment for another developer and got the same failing behaviour...Amplify CLI failed but stack was successful. 

Any insights is appreciated.

**Comment by alexboulay** [comment]
I've noticed the ES domain takes forever to be created. I'm currently attempting a second push and it's been over 40mins, still in creation. Though everything is fine and the CLI push hasn't failed on me (yet)

**Comment by ammarkarachi** [comment]
>I've noticed the ES domain takes forever to be created. I'm currently attempting a second push and it's been over 40mins, still in creation. Though everything is fine and the CLI push hasn't failed on me (yet)

Hi @alexboulay, it looks like the ES domain creation is timing out the push. I will consult the ES team if any mitigations is possible.

**Comment by alexboulay** [comment]
it failed cli side but CF all good.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/70296188/125710102-6e6e08e2-3da3-4e50-ac94-d4d2d747767d.png">
ES domain took a while

**Comment by kaustavghosh06** [comment]
@AlessandroVol23 are you still seeing these issues? We had a recent service issue tied to ACM domain creations and that might've caused this issue. Please let me know if you're still seeing this on new env creations regularly.

**Comment by AlessandroVol23** [comment]
Hi @kaustavghosh06 not sure if you meant me but I didn't hat this issue :-)
