### ISSUE TITLE
Amplify cli deleting functions from file system without warning

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#7733]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v12.13.0

### Amplify CLI Version

5.1.1

### What operating system are you using?

mac

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

env

### Describe the bug

Amplify is deleting functions in the project without warning. There are two scenarios that are unexpected:

1. `amplify add function`, work on the function and test locally using mock but don't commit to repo and don't amplify push, then run `amplify env checkout [some-other-env]` and function files disappear but the folder remains. 

2. The CLI is constantly changing the formatting of internal files it's using. As a team we try to stay in sync with versions but it seems like the changes still happen. So we don't always catch important changes because amplify file changes are noisy. Today, 3 developers (1 submitted PR, 2 other's reviewed) missed a bad team-provider-info merge that deleted two new functions from our dev branch. 

### Expected behavior

1. Amplify should warn when there are changes that haven't been pushed before doing a checkout or a pull or any action other than `amplify function remove` that will remove the function from the project. 

2. I don't know what to tell you here. The team provider info file is getting too big and it probably needs to be broken up into smaller files so we can easily detect changes. Or something. I can't tell you how many times I've looked at the changes in this file and they're just things getting re-arranged or some minor change that doesn't affect dev.
 
Don't delete user generated files without warning.  

### Reproduction steps

1. amplify function add
2. add code to function
3. don't push the function or commit
4. amplify env checkout (possibly other commands as well)
5. see function disappear 
6. remove a function from team provider info and watch it disappear

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@kldeb The function would be carried over after you push, since the function becomes available only through the current cloud backend.

Can you provide us a diff of the changes?

**Comment by kldeb** [comment]
Update: I learned that it was also an issue in one case with a bad merge on the backend-config.json file that dropped lambdas. I also learned that we occasionally experience issues with the amplify.meta.json file and it needs to be manually changed to clear our push errors. There's a lot going on here and I'm not sure what is the root problem.

**Comment by ammarkarachi** [comment]
@kldeb I agree that some bad merges would cause undesirable. I asked for diffs to figure out if there was something we could do to mitigate it when generating the file (a sort by resource names) to keep the change to those file predictable.

**Comment by kldeb** [comment]
@ammarkarachi can I send you the diff of the file privately?

**Comment by ammarkarachi** [comment]
@kldeb yes amplify-cli@amazon.com

**Comment by ammarkarachi** [comment]
~~The function would be carried over after you push, since the function becomes available only through the current cloud backend~~
