### ISSUE TITLE
MFALambdaInputs failing on amplify push

### ISSUE THREAD

**Issue by regischow** [aws-amplify/amplify-cli#7739]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

When I upgraded my amplify cli from 4.45.2 to 5.1.0 and running `amplify push` after initializing a new env, I encountered the following error.

> CREATE_FAILED      MFALambdaInputs                       Custom::LambdaCallout Fri Jul 16 2021 16:52:53 GMT-0400 (Eastern Daylight Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/16/[$LATEST]...

Cloudwatch logs had the following error,

> "Data": {
>         "err": {
>             "message": "User: arn:aws:sts::[account id]:assumed-role/portalves927ag_totp_lambda_role-rchow/amplify-clientportal-rchow-160848-authcl-MFALambda-AebKAebqN5Zp is not authorized to perform: iam:PassRole on resource: arn:aws:iam::[account id]:role/snsves927ag160848-rchow",
>             "code": "AccessDeniedException",
>             "time": "2021-07-16T20:52:52.832Z",
>             "requestId": "75b57781-d51a-4cb8-8b7c-5a9e7ba906e8",
>             "statusCode": 400,
>             "retryable": false,
>             "retryDelay": 30.68807466081629
>         }
>     }

I am not sure why the MFALambda needs iam:PassRole for the SNSRole? SNSRole is used to action on sns:Publish, MFALambda is use to configure MFA.

In the Cloudformation for Auth, MFALambdaRole has policy to action on iam:PassRole for the portalves927ag_totp_lambda_role Resource.

Here is the Cloudformation in question,
```
# BEGIN MFA LAMBDA RESOURCES
  MFALambdaRole:
  # Created to execute Lambda which sets MFA config values
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !If [ShouldNotCreateEnvResources, 'portalves927ag_totp_lambda_role', !Join ['',['portalves927ag_totp_lambda_role', '-', !Ref env]]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: portalves927ag_totp_pass_role_policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource: !If [ShouldNotCreateEnvResources, 'arn:aws:iam:::role/portalves927ag_totp_lambda_role', !Join ['',['arn:aws:iam:::role/portalves927ag_totp_lambda_role', '-', !Ref env]]]
```

### Expected behavior

Expectation is amplify push would complete successful with no errors.

### Reproduction steps

1. npm install -g @aws-amplify/cli@5.1.0
2. npm init <- new env
3. amplify push -y

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
CREATE_FAILED      amplify-clientportal-rchow-160848-authclientportalAuth-NNCBAMJF5PN3 AWS::CloudFormation::Stack Fri Jul 16 2021 16:54:12 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [MFALambdaInputs]. 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               authclientportalAuth              AWS::CloudFormation::Stack Fri Jul 16 2021 16:54:15 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:ca-central-1:[account id]:stack/amplify-clientportal-rchow-160848-authclientportalAuth-NNCBAMJF5PN3/9ce433f0-e677-11eb-8b49-020c75308b9a was not successfully created: The following resource(s) failed to create: [MFALambdaInputs]. 
UPDATE_ROLLBACK_IN_PROGRESS amplify-clientportal-rchow-160848 AWS::CloudFormation::Stack Fri Jul 16 2021 16:54:16 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [authclientportalAuth].       
```

</details>

### Additional information

Workaround:

- Adding policy statement to MFALambdaRole to allow iam:PassRole to SNSRole

```
# adding statement to MFALambdaRole policy
- Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource: !If [ShouldNotCreateEnvResources, !Sub 'arn:aws:iam::${AWS::AccountId}:role/portalves927ag_sns-role', !Join ['',[ !Sub 'arn:aws:iam::${AWS::AccountId}:role/', 'sns', 'ves927ag', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]
```

**Comment by ammarkarachi** [comment]
@regischow if you upgrade to the latest version [5.1.2](https://www.npmjs.com/package/@aws-amplify/cli/v/5.1.2) it is fixed.

**Comment by ammarkarachi** [comment]
Can you let me know the region you are trying to push to?

**Comment by regischow** [comment]
> Can you let me know the region you are trying to push to?

ca-central-1

**Comment by fgiopp** [comment]
Same problem here.
When running `amplify push` after initializing a new env, I encountered the same error reported by @regischow .

`amplify update auth` haven't fixed the problem.

on cloud watch, I can see the following error:
```
 "err": {
            "message": "User: arn:aws:sts::5xxxxxxxxx7:assumed-role/yyyyyyyy_totp_lambda_role-prod/amplify-filewhey-prod-181256-authkkkkkk-MFALambda-hzOC2hlKZblP is not authorized to perform: iam:PassRole on resource: arn:aws:iam::5xxxxxxxxx7:role/snszzzzzzzzz-prod",
            "code": "AccessDeniedException",
            "time": "2021-07-16T16:48:21.360Z",
            "requestId": "71e6f45f-1b49-4006-abbb-c0bc658c4c4e",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 51.27577122389842
        }

```

**Comment by ammarkarachi** [comment]
@fgiopp what's the walkthrough followed when running `amplify update auth`

**Comment by connected-mdeluco** [comment]
I want to create a new environment based off one I've already configured. `amplify update auth` seems to require reconfiguring auth options from scratch. As @fgiopp commented, "not what I need."

**Comment by fgiopp** [comment]
Eventually, I used `amplify update auth` and applied the default configuration, then again `amplify update auth`, but this time with my custom configuration. This solved the problem in my case.

NB: I don't think this is necessary, but in my case, between the first `amplify update auth` and the second, I also pushed the change to the cloud.

**Comment by regischow** [comment]
@fgiopp, are you able to confirm the resulting iam:PassRole resource used to execute MFALambda?

**Comment by connected-mdeluco** [comment]
@ammarkarachi I'm on 5.1.2 and getting the issue consistently when trying to push new environments. Region us-east-2.

**Comment by connected-mdeluco** [comment]
Here's a sequence of events that I just encountered:

1. `amplify env add` - env name `mdteste`
2.  `amplify push`
```
...
CREATE_IN_PROGRESS MFALambdaInputs Custom::LambdaCallout Tue Jul 20 2021 09:42:08 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED MFALambdaInputs Custom::LambdaCallout Tue Jul 20 2021 09:42:09 GMT-0400 (Eastern Daylight Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/20/[$LATEST]713c0bf7db2c4ba393cbbf4cf0513a02 (RequestId: 95b8f6ef-96e9-4e05-b0fb-7ca4b6b7d887)
...
CREATE_FAILED               authSaffronAuth               AWS::CloudFormation::Stack Tue Jul 20 2021 09:42:40 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:us-east-2:821663879482:stack/amplify-saffron-mdteste-93653-authSaffronAuth-141231UK8B4HF/1638de50-e960-11eb-bd2d-06251c9d69f8 was not successfully created: The following resource(s) failed to create: [MFALambdaInputs]. 
UPDATE_ROLLBACK_IN_PROGRESS amplify-saffron-mdteste-93653 AWS::CloudFormation::Stack Tue Jul 20 2021 09:42:40 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [authSaffronAuth].                                                                                                                                                                                                   
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED amplify-saffron-mdteste-93653-authSaffronAuth-141231UK8B4HF AWS::CloudFormation::Stack Tue Jul 20 2021 09:42:39 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [MFALambdaInputs]. 
⠋ Updating resources in the cloud. This may take a few minutes...
...
```
3. `amplify update auth`
4. `What do you want to do? Apply default configuration without Social Provider (Federation)`
5. `amplify push`
```
...
CREATE_FAILED      CustomMessageConfirmationBucket AWS::S3::Bucket Tue Jul 20 2021 10:06:54 GMT-0400 (Eastern Daylight Time) saffronauthverificationbucket-mdteste already exists
...
CREATE_FAILED      amplify-saffron-mdteste-93653-authSaffronAuth-1NVM4BVP3XNAX AWS::CloudFormation::Stack               Tue Jul 20 2021 10:08:38 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [CustomMessageConfirmationBucket]. 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               authSaffronAuth               AWS::CloudFormation::Stack Tue Jul 20 2021 10:08:42 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:us-east-2:821663879482:stack/amplify-saffron-mdteste-93653-authSaffronAuth-1NVM4BVP3XNAX/b9213f10-e963-11eb-af0e-06ebf7928cfe was not successfully created: The following resource(s) failed to create: [CustomMessageConfirmationBucket]. 
UPDATE_ROLLBACK_IN_PROGRESS amplify-saffron-mdteste-93653 AWS::CloudFormation::Stack Tue Jul 20 2021 10:08:42 GMT-0400 (Eastern Daylight Time) The following resource(s) failed to create: [authSaffronAuth].
...
```

I can't remember, but I may have tried customizing the messages for the "Forgot password" config in Authentication settings in the console, which led me to file amplify-console [#2069](https://github.com/aws-amplify/amplify-console/issues/2069).

**Comment by jk171505** [comment]
Hi, I had exactly the same issue while trying to push the env. New policy statement suggested in workaround solved the problem for me. I'm on amplify 5.5.0.

**Comment by Straubulous** [comment]
This has been fixed it was related to the an issue we had a couple of months ago. For the MFA to pass a role to it, it didn't require passrole permissions in the past, but Cognito changed the permissions requirements so that passrole is required.  CLI has been updated accordingly. Closing.
