### ISSUE TITLE
Using fragments to get nicer types on various queries

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/amplify-cli#774]
Not sure I'm missing something. But if my schema has various queries that gives back say a User object. Like, GetUserQuery and ListUsersQuery. When using the API.swift these comes out as different types. I.e GetUserQuery.Data.GetUser and ListUsersQuery.Data.ListUser, both which are a User object.

Now, I know you can get around this by using fragments in the queries, but since amplify builds all this for you, is there way to make this nicer, or to get amplify to set up fragments?

**Comment by kaustavghosh06** [comment]
@helloniklas We fixed this issue as a part of https://github.com/aws-amplify/amplify-cli/pull/796 and is a part of our latest CLI version.
