### ISSUE TITLE
Unable to upload trigger files to S3

### ISSUE THREAD

**Issue by vgmartinez** [aws-amplify/amplify-cli#7742]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.0

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Hi guys,
I create a new env and when I try to deploy then I have this error at the end of the process, all the cloudformation is ok.

```
00 (Central European Summer Time) 
UPDATE_COMPLETE amplify-global-dev-112114           AWS::CloudFormation::Stack Mon Jul 19 2021 12:14:27 GMT+0200 (Central European Summer Time) 
✔ Generated GraphQL operations successfully and saved at src/graphql
⠸ Uploading files...e NoSuchBucket: The specified bucket does not exist
    at Request.extractError (/Users/victor/.nvm/versions/node/v14.15.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:714:35)
    at Request.callListeners (/Users/victor/.nvm/versions/node/v14.15.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```

```
✖ An error occurred when pushing the resources to the cloud

Unable to upload trigger files to S3
An error occurred during the push operation: Unable to upload trigger files to S3
```

### Expected behavior

I expect that `amplify push` works ok

### Reproduction steps

`amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
Hi @vgmartinez 
A few questions here
- Were you able to create new env's and push in a prior version?
- Before running creating the env and running push is it located in the same account as the previous env?

**Comment by vgmartinez** [comment]
@SwaySway,
- Yes, in the previous version I did't.
- Is located in different account, but now even in the same account the master env is not working for the same reason.
let me know if you need more info, I was looking for bad bucket reference but I don't see anythings wrong.

**Comment by SwaySway** [comment]
When creating the new env in a different account did the CLI prompt which profile to use?
This should setup the deployment bucket to handle the resources.

> Is located in different account, but now even in the same account the master env is not working for the same reason.

Is there a different error happening in the master env?

**Comment by josefaidt** [comment]
Hey @vgmartinez :wave: are you still experiencing this issue? If so are you receiving a different error in the "master" env?

**Comment by vgmartinez** [comment]
hi @josefaidt @SwaySway sorry for the delay. 
I keep getting the same error and it is very frustrating ;(. I don't know why if I create a new environment from the UI (Amplify) I keep getting this same error. I don't know where the reference to s3 is, all cloudformation stacks end ok. I don't know where to look.

Thanks for try to help.

**Comment by josefaidt** [comment]
Hey @vgmartinez in the account where you're experiencing this issue are the S3 settings set to block all public access?
![image](https://user-images.githubusercontent.com/5033303/128210579-21549ea9-17e7-4e56-97e3-b8b29a41ec39.png)

**Comment by kaustavghosh06** [comment]
@vgmartinez Yes, we've seen this issue due to the bucket policies set on your AWS account globally as @josefaidt mentioned. Please let us know if your'e still facing the issue after making the changes suggested by @josefaidt.
