### ISSUE TITLE
How do you make sure /usr/local/bin is on your path?

### ISSUE THREAD

**Issue by yash-5575** [aws-amplify/amplify-cli#7749]
How do you make sure /usr/local/bin is on your path? 

I have exactly the same issue and npm root -g produces the path as follows: /usr/local/Cellar/node/16.1.0/lib/node_modules

_Originally posted by @OderoOtieno in https://github.com/aws-amplify/amplify-cli/issues/5075#issuecomment-843725896_

**Comment by josefaidt** [comment]
Hey @yash-5575 :wave: to check the PATH variable we can execute `echo $PATH | grep $(npm bin -g)`. If the path is not available in the variable we can add it with `export PATH=$PATH:$(npm bin -g)`, which can be added to your `~/.bashrc` file to persist.

**Comment by josefaidt** [comment]
Closing issue, @yash-5575 if you are still experiencing this issue and are in need of further assistance please reply back to this thread and we can reopen to investigate further 🙂
