### ISSUE TITLE
Modifying queries.graphql and rerun codgen to get deeper data in API.swift

### ISSUE THREAD

**Issue by helloniklas** [aws-amplify/amplify-cli#775]
So the generated queries from the annotated schema through transforms doesn't seem to go deep enough through the connections. This works in the console. So I thought I could manually add what I need to queries.graphql and run 'amplify codegen types' to get a new API.swift. But this doesn't seem to work. Do I have to install Apollo to create the Codegen manually?

The examples I'm looking at is a User model that has Votes and each vote has a post. But by default generated query I can't get to the post.id inside Vote. In the console I could do it.
```
query GetUser($id: ID!) {
  getUser(id: $id) {
    id
    name
    votes {
      items {
        id
        vote
        post {
          id
        }
      }
      nextToken
    }
...
```

The annotated schema looks like this:
```
type User @model @searchable {
    id: ID!
    name: String!
    votes: [Vote] @connection(name: "UserVote")
}

type Vote @model @searchable {
    id: ID!
    user: User! @connection(name: "UserVote")
    vote: Int!
    post: Post! @connection(name: "PostVotes")
}

type Post @model @searchable {
    id: ID!
    text: String
    votes: [Vote] @connection(name: "PostVotes")
}
```

**Comment by yuth** [comment]
> Ok, so I got this working by doing:
> 
> ```
> amplify remove api
> amplify add Codegen --apiId xxxxxxxxx
> amplify Codegen types
> ```
> 
> It then regenerate the API.swift with my added queries.

@helloniklas, You don't have to remove the API first. You could just run `amplify codegen types` after editing your queries. If you just run `amplify codgen` after editing queries, make sure that you say no to generating statements.

We plan to add an additional command line parameter that can be used to specify the depth  for generation of GraphQL statement

**Comment by helloniklas** [comment]
Ok thanks. For some reason it didn't work unless I first removed API and added it from the cloud with the id. I guess because I first added it with amplify from a local schema file.

Adding more granularity seems like a good idea.

**Comment by kaustavghosh06** [comment]
@helloniklas We added support for --max-depth flag for the amplify codegen command as a part of #820. Please feel free to check out the latest version of the CLI and re-open this issue if you're still stuck on this.
