### ISSUE TITLE
configure project with --yes option does not suppress "Which setting do you want to configure?" question

### ISSUE THREAD

**Issue by Bullace** [aws-amplify/amplify-cli#7750]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

5.1.2

### What operating system are you using?

Ubuntu

### Amplify Categories

hosting

### Amplify Commands

configure project

### Describe the bug

When running the project configure command with the --yes param I keep getting prompted with the "Which setting do you want to configure?" question. Because of this I can't automate deployment.

### Expected behavior

When using the --yes param I expect the question to not be prompted and the default option "Project information" to be chosen.

### Reproduction steps

Running the project configure example script (with valid config) from [https://docs.amplify.aws/cli/usage/headless#sample-script-1](https://docs.amplify.aws/cli/usage/headless#sample-script-1) should trigger the question prompt.

**Comment by SwaySway** [comment]
It looks like this is coming from headless containers flow, since headless flow for containers is not currently supported.
Marking this is an enhancement. Will review with the team if we can provide an option to go through just project configuration without container hosting setup.
