### ISSUE TITLE
Querying for connection with @key field consisting of multiple fields

### ISSUE THREAD

**Issue by KristineTrona** [aws-amplify/amplify-cli#7752]
**Which Category is your question related to?**
AWS AppSync, AWS GraphQL

**Amplify CLI Version** 
v5.1.1.

**What AWS Services are you utilizing?**
AWS AppSync, AWS GraphQL

**Provide additional details e.g. code snippets**

Hello, I am working on an app, which will need to support multi-tenancy in the backend. This creates a challenge as normal record ids will no longer be unique across the table, but only unique within the tenant. I have created the following schema:

```gql
type Tenant
  @model {
  id: ID!
  events: [Event] @connection(name: "EventTenant", keyField: "tenantId")
  locations: [Location] @connection(name: "LocationTenant", keyField: "tenantId")
}

type Event
  @model
  @key(fields:["id", "tenantId"]) {
  id: ID!
  tenant: Tenant @connection(name: "EventTenant", keyField: "tenantId")
  tenantId: ID!
  location: Location @connection(name: "EventLocation", keyField: "locationId", sortField: "tenantId")
  locationId: ID
}

type Location
  @model
  @key(fields:["id", "tenantId"]) {
  id: ID!
  tenant: Tenant @connection(name: "LocationTenant", keyField: "tenantId")
  tenantId: ID!
  events: [Event] @connection(name: "EventLocation", keyField: "locationId", sortField: "tenantId")
}
```

This way I am now able to have multiple records in `Location` and `Event` tables with the same value for `id` as long as their `tenantId` is different, which is the desired behaviour.

The problem I have now is with the connection `Event.location`, because even though the `locationId` in `Event` matches a record in `Location` table, the `location` field returns `null`. I am not able to specify the `tenantId` when trying to query the `location` field from `getEvent` query. However, when I try to get events from within a location `Location.events` - then I am able to specify the `tenantId` as sort key and get the correct connected records. 

Does anybody know how I could retrieve `location` from `Event` with the given indexes or is that something that is simply not possible when using sortKey in such a manner on a single object connection? Any help is much appreciated! Thank you!

**Comment by SwaySway** [comment]
Hello @KristineTrona 
It could be returning null as the primary key schema for Location uses two fields. This is supported in the updated `@connection` definition. You can reference both new id fields so it can run the get operation on the location field.
```graphql
type Tenant
  @model {
  id: ID!
  eventId: ID
  locationId: ID
  events: [Event] @connection(fields: ["eventId", "id"])
  locations: [Location] @connection(fields: ["locationId", "id"])
}

type Event
  @model
  @key(fields:["id", "tenantId"]) {
  id: ID!
  tenant: Tenant @connection(fields: ["tenantId"])
  tenantId: ID!
  location: Location @connection(fields: ["locationId", "tenantId"])
  locationId: ID
}

type Location
  @model
  @key(fields:["id", "tenantId"]) {
  id: ID!
  tenant: Tenant @connection(fields: ["tenantId"])
  tenantId: ID!
  events: [Event] @connection(fields: ["id", "tenantId"])
}
```

**Comment by KristineTrona** [comment]
@SwaySway Thank you for the response, I've tested the above example and can confirm that it indeed works. :)

**Comment by SwaySway** [comment]
Closing issue as the op question has been answered.
