### ISSUE TITLE
How to have indices query in appsync? 

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#7754]
**Which Category is your question related to?**

Appsync, graphql, pipeline resolver

**Amplify CLI Version** 
5.1.2

I have a full stack app defined in amplify by graphql and react.js. 

I need to do extra authorisation in my queries based on what I asked [here](https://github.com/aws-amplify/amplify-cli/issues/6389), therefore, I tried to find out how can I define a pipeline resolver.

I pursued this [tutorial](https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html) as a warm up for creating pipeline resolvers. As a step for defining a pipeline resolver, I have to find the mutation or query in the schema section of appsync console:

![https://i.stack.imgur.com/GKlGm.png](https://i.stack.imgur.com/GKlGm.png) 

However, the problem is some of the queries that I defined with indices are not listed in the right hand side panel. 

For example, I have defined the following index:

```
@key(name: "byCountry", fields: ["countryId", "updatedAt"], queryField: "listReportsByCountry")
```

but I cannot find `listReportsByCountry` in the `Resolvers` list. How can I find the resolvers of these kind of queries and define some sort of custom actions in between.

**Comment by SwaySway** [comment]
Hi @mjza 

You can find the query for `listReportsByCountry` under queries.
The CLI does not currently support pipeline resolvers.
Though we are aware of it and are tracking that as a part of the new transformer. RFC: #6217 

The transformer does accept overrides, so a potential solution would be to overwrite the generated CFN templates and resolver to create a pipeline resolver for `listReportsByCountry`.
Docs: https://docs.amplify.aws/cli/graphql-transformer/resolvers

**Comment by SwaySway** [comment]
@mjza 
As long as you have a top level object defined (ex. Mutation, Query, Subscription) there is no need for a schema definition. 
GraphQL Docs: https://spec.graphql.org/June2018/#sec-Root-Operation-Types

If you are adding in your own query you can add that in your schema. Such as `getUser` and it that type will get carried over into the build schema. From there you can create it's own resolvers and CFN templates as mentioned in the overwrite resolver docs.

**Comment by mjza** [comment]
Thanks.
