### ISSUE TITLE
Support for multiple subscriptions - iOS

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/amplify-cli#777]
** Which Category is your question related to? **
Usage Guidance
** What AWS Services are you utilizing? **
AppSync, Cognito
** Provide additional details e.g. code snippets **
I have a basic model of Post with Comments and I am subscribing to onCreatePost and onCreateComment mutation in iOS in sequential order. Strangely, the subscription which is called last works while the first one does not. I read other posts mentioning that multiple subscriptions works with Cognito but in my case it is not working.

I am using the guidance provided at https://aws-amplify.github.io for creating subscription. Any suggestion?

**Comment by mikeparisstuff** [comment]
Can you please provide more information on how you are inititing subscriptions? When you initiate a subscription via a subscription query, AppSync will return a list of authenticated topics that correspond to different subscription queries and the client is responsible for organizing and managing those connections. It sounds like you may just be subscribing to the latest of those topics, but I can not be certain without more information. What client/sdk/libraries and version are you using to subscribe? Any code snippets you could share would help me debug your issue.

**Comment by rohit3d2003** [comment]
I have a main method where I am calling multiple subscribe methods which are subscribing to individual topics. Here is the code snippet:

<img width="749" alt="screen shot 2019-01-28 at 12 59 11 pm" src="https://user-images.githubusercontent.com/16943885/51865939-85004080-22fc-11e9-801f-88d65323159f.png">

Also, I couldn't figure out a way to filter the topic while subscribing. In my current code, once I receive a notification, I am putting a code to check if I care to act on it. Is there a to filter the topic itself to avoid receiving so many events.

I am using Amplify v 0.1.44 with iOS (Swift) and latest AWS Sdk's

**Comment by undefobj** [comment]
@rohit3d2003 since your question is specific to iOS SDK calls could you please post your question and code to the AppSync iOS SDK: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues

We have several iOS Engineers who will be better suited to troubleshoot with you. Feel free to reopen if there is a CLI or GraphQL Transformer issue.
