### ISSUE TITLE
Cannot Enable DataStore to edit your data model visually

### ISSUE THREAD

**Issue by alonsnir** [aws-amplify/amplify-cli#7771]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d9dwprxsmtbx8

### Region

us-east-2

### Environment name

qa

### Amplify CLI Version

5.1.1

### What operating system are you using?

Ubuntu

### Browser type?

Chrome

### Describe the bug

I have an an amplify app created and deployed with the amplify cli.
It has GraphQL API with data model tables in DynamoDB
When I try to update content via the Content page in the Admin UI it says "An additional deployment is needed to enable content management capabilities for your API. Navigate to "Data" and hit "Save and deploy"
Following the above, on the Data page, clicking on "Enable DataStore and deploy" does nothing. 
Content remains unmanageable from the Admin UI. 

### Expected behavior

I need to able to manipulate content in the Admin UI.

### Reproduction steps

1. Create an app with the amplify cli
2. add api grapgql and generate models in DynamoDB
3. deploy the app
4. check all is up and running, db tables exist
5. add some data using the qraphql console
6. open Admin UI and try to manage content

**Comment by SwaySway** [comment]
@alonsnir 
If you have the project pulled down in a local machine you can enable datastore by running `amplify update api`. After running `amplify push` the data models should be available in the admin ui.

**Comment by josefaidt** [comment]
Hey @alonsnir :wave: just wanted to follow-up and see if you were able to successfully enable DataStore, push, and manage content from AdminUI?

**Comment by alonsnir** [comment]
Hello @josefaidt @SwaySway, 

I'm sorry, but from the reproduction steps it's already done. I have stated in steps I use cli, and have deployed the app, which is - amplify update api and amplify push. 
I have also mentioned it on the support issue I have opened for this and tried a several time during the support call.

Anyway, I have done as suggested:

1. pulled the app again
2. "updated" api by `amplify update api`
3. pushed it with `amplify push` here is the output:
✔ Successfully pulled backend environment dev from the cloud.
Current Environment: dev
| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Auth     | userPoolGroups | No Change | awscloudformation |
| Auth     | aruggaauth     | No Change | awscloudformation |
| Api      | arugga         | No Change | awscloudformation |
| Function | pullRobotData  | No Change | awscloudformation |
| Function | pushRobotData  | No Change | awscloudformation |
No changes detected
4. went to the Amplify Admin console, tried to enable data modeling with same result.

I'm still not able to manage content from the Amplify Admin :(

**Comment by josefaidt** [comment]
Hey @alonsnir thank you for the information! In the Amplify AdminUI are you seeing any errors in the browser's console? What does the AdminUI show when you navigate to the content screen?

**Comment by alonsnir** [comment]
Hi @josefaidt there is no error shown in the console.
When I navigate to the content screen it says: `An additional deployment is needed to enable content management capabilities for your API. Navigate to "Data" and hit "Save and deploy"`. I then follow the link and go to the Data Modeling page. On that page there is a button 'Enable DataStore and deploy', clicking on it does nothing, no error displayed, but if I try to navigate out of that page it says "You have unsaved changes, are you sure you want to leave?"

If I look at the network pane, there I see only one error, it's 404 for the following request:
https://sd7m8ny5u0.execute-api.us-east-2.amazonaws.com/prod/backend/d9dwprxsmtbx8/api/dev/getModels

**Comment by alonsnir** [comment]
Hi @josefaidt 
``` 
$ amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Enable DataStore for entire API

GraphQL schema compiled successfully.

$ amplify codegen
✔ Generated GraphQL operations successfully and saved at src/graphql
```

**Comment by josefaidt** [comment]
Thanks @alonsnir, do you run into issues when running `amplify codegen models`?

**Comment by alonsnir** [comment]
@josefaidt oh, that one, I assumed typo in what you asked for, sorry. 
here it is:

```
$ amplify codegen models

GraphQL schema compiled successfully.

Edit your schema at /home/alon/amplify/amplify/backend/api/arugga/schema.graphql or place .graphql files in a directory at /home/alon/amplify/amplify/backend/api/arugga/schema
Unknown type "Query". Did you mean "ModelQuery"?
Error: Unknown type "Query". Did you mean "ModelQuery"?
    at assertValidSDL (/snapshot/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/snapshot/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.codegen (/snapshot/node_modules/@graphql-codegen/core/dist/commonjs/codegen.js:33:39)
    at /snapshot/node_modules/amplify-codegen/src/commands/models.js:109:23
    at Array.map (<anonymous>)
    at Object.generateModels (/snapshot/node_modules/amplify-codegen/src/commands/models.js:108:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.run (/snapshot/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/snapshot/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at Object.executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:116:9)

```

**Comment by alonsnir** [comment]
@josefaidt sent to amplify-cli@amazon.com

**Comment by josefaidt** [comment]
Hey @alonsnir thanks for sending it over! I noticed you have defined types for Mutation and Subscription, but not Query. Can you try removing the `query` line from your `schema` declaration and re-run `amplify codegen models`? I've noticed a similar error when running `amplify api gql-compile` as well.

```diff
schema {
- query: Query
  mutation: Mutation
  subscription: Subscription
}

```

**Comment by alonsnir** [comment]
Hi @josefaidt 

```
$ amplify codegen models
Error: Query root type must be provided.
Successfully generated models. Generated models can be found in ./amplify/src
```

**Comment by josefaidt** [comment]
Hey @alonsnir was the `schema` block added for a particular reason? I was able to enable DataStore from the CLI, generate models, and deploy, though I did run into a different issue when trying to access the content pane. Can you try removing the `schema` block all together and push?

**Comment by josefaidt** [comment]
Hey @alonsnir were you able to successfully push after removing the `schema` block from your schema file?
