### ISSUE TITLE
Cannot Remove Environment Variable from Lambda

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#7777]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

update

### Describe the bug

I added an environment variable via amplify function update, now I try to remove it via amplify function update. On push I get following error: 

UPDATE_FAILED               functionMyrFn     AWS::CloudFormation::Stack Wed Jul 21 2021 23:01:50 GMT-0600 (Mountain Daylight Time) Parameters: [myEnvVar] must have values                                            

### Expected behavior

Should remove env var succesfully

### Reproduction steps

1. Add env var to function via amplify function update
2. amplify push
3. Remove env var via amplify function update
4. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hisham** [comment]
To get it to work I had to manually remove the following from the MyFn-cloudformation-template.json parameters list: 

,
    "myEnvVar": {
      "Type": "String"
    }

**Comment by hisham** [comment]
But when I switched to another env, amplify push on that env failed. Turned out I had to remove another instance from myEnvVar from my team-provider-info.json and then things worked. 

So from my perspective removing env vars from lambdas via amplify cli is completely broken.

**Comment by SwaySway** [comment]
@hisham 
Did you add the env variable with a prior version and remove it with version 5.1.2?
I was not able to repro using 5.1.2 I was able to add and remove a env variable.

**Comment by hisham** [comment]
yeah I added it with 5.1.1 and removed with 5.1.2.

**Comment by josefaidt** [comment]
Hey @hisham :wave: thanks for raising this! I've been able to reproduce in 5.1.2 and the latest version 5.2.0 as well. This appears to specifically affect environment variables and not secrets. After running `amplify pull --restore` the function does not show environment variables configured, but shows the env var and asks us for the value on a subsequent push. Marking this as a bug

Reproduction steps:

1. `amplify add function`, add sample env var
3. `amplify push`
4. `amplify update function`, remove sample env var
5. `amplify push`
6. Observe error shown in this issue
7. `amplify pull --restore`
8. Make some update (example: add a secret to existing function)
9. `amplify push`
10. Observe the following prior to CLI pulling backend env from cloud
   ```
    > amplify push -y

    Some Lambda function environment variables are defined but missing values.

    ? Enter the missing environment variable value of my_sample_var in 7777removinglambdaenb40fa2f1: mysamplevalue
   ```

**Comment by mariusbutuc** [comment]
Removing λ-function environment variables is still buggy in `@aws-amplify/cli@5.3.0`.

It will likely be fixed when `*5.3.1` is out, as it contains #7917.

**Comment by conorw** [comment]
I can confirm this issue still exists in v5.6.0

**Comment by conorw** [comment]
Correction. This may have been something weird in my project.
I was able to resolve by editing the nested-cloudformation-stack.yml file in the backend/awscloudformation/build folder
