### ISSUE TITLE
amplify update auth failed

### ISSUE THREAD

**Issue by wongzigii** [aws-amplify/amplify-cli#7778]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

> TypeError: Cannot read property 'substring' of undefined

```
amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Update OAuth social providers
 Select the identity providers you want to configure for your user pool:
TypeError: Cannot read property 'substring' of undefined
    at userPoolDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/assets/cognito-defaults.js:24:47)
    at Object.identityAndUserPoolDefaults [as identityPoolAndUserPool] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/assets/cognito-defaults.js:66:6)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/utils/auth-defaults-appliers.ts:46:54
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts:45:31
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:379:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)
There was an error adding the auth resource
```

### Expected behavior

Command execute success without error 

### Reproduction steps

1.Run `amplify update auth`
2.Update OAuth social providers
3.Select `Google`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
@wongzigii 
Did you try to remove google as a social provider?
I did not run into that error, here's what I did to repro on v5.1.2
- add google and facebook
- run `amplify push`
- run `amplify update auth`
- remove google as a social provider
- run `amplify push`

**Comment by wongzigii** [comment]
I've renamed the project directory name, maybe that's the issue.

**Comment by SwaySway** [comment]
@wongzigii 
You can run `amplify configure project` so the project also reflects the project directory name change.

**Comment by wongzigii** [comment]
OK Good to know Thanks @SwaySway Closing
