### ISSUE TITLE
npm install -g @aws-amplify/cli  give error

### ISSUE THREAD

**Issue by cmrlabs** [aws-amplify/amplify-cli#778]
**Check the below command response**

Command used : **`npm install -g @aws-amplify/cli`**

Response : 
```
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ npm install -g @aws-amplify/cli
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/chandramoulireddyporeddy/.npm-global/bin/amplify -> /Users/chandramoulireddyporeddy/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

+ @aws-amplify/cli@0.1.44
updated 3 packages in 96.79s

Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ amplify configure
-bash: amplify: command not found
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ 
```

I hope you understand the above issue.

**Comment by kaustavghosh06** [comment]
@cmrlabs Looks like the CLI was installed but with warnings (which are currently expected due to our dependencies). I tried to install the CLI and use the amplify command and wasn't able to reproduce it. Let me investigate on this.

**Comment by slaat** [comment]
try `npm list -g --depth=0`, does @aws-amplify/cli appear in that list? If not, your path is not configured correctly.

**Comment by cmrlabs** [comment]
I tried, path configured correctly
```
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ npm list -g --depth=0
/Users/chandramoulireddyporeddy/.npm-global/lib
├── @aws-amplify/cli@0.1.44
├── firebase-tools@6.3.0
├── graphql@0.13.0
├── jshint@2.9.7
└── npm@6.7.0

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ 


```

**Comment by shazzner** [comment]
Same issue, this is running from a docker container of image `node:10.15.0`.

**Comment by haggenmacher** [comment]
```
Haggenmacher-MBP:~ swan$ npm list -g --depth=0
/Users/swan/.nvm/versions/node/v11.9.0/lib
├── @aws-amplify/cli@0.1.45
└── npm@6.5.0

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5
Haggenmacher-MBP:~ swan$ 
```
Same issue. Are we able to manually install these peer dependencies? If so, what are the steps? If not, can the warning be ignored?

**Comment by jahnagoldman** [comment]
I have this issue, as well.

```
MacBook-Pro:~ jahnaariellegoldman$ npm list -g --depth=0
/Users/jahnaariellegoldman/.npm-global/lib
├── @aws-amplify/cli@0.1.45
├── expo-cli@2.7.1
└── react-native-cli@2.0.1

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5

```

**Comment by vishal2332** [comment]
Same issue on my mac as well.

Vishals-MacBook-Pro:Angular vishalshinde$ npm list -g --depth=0
/usr/local/lib
+-- @angular/cli@7.3.0
+-- @aws-amplify/cli@0.1.45
+-- awsmobile-cli@1.1.7
`-- npm@6.4.1

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5

**Comment by sirshannon** [comment]
Same issue here.

`Gabadon:Developer sirshannon$ npm list -g --depth=0
/Users/sirshannon/npm-global/lib
├── @aws-amplify/cli@0.1.45
├── webpack@4.29.0
└── webpack-cli@3.2.1

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5`

**Comment by jahnagoldman** [comment]
I found that uninstalling node completely for me and using nvm to reinstall helped. I think it had something to do with having different versions of node installed, but am not 100% sure.

**Comment by kaustavghosh06** [comment]
Hey guys, please take a look at @jahnagoldman solution and if you're still facing the issue, please let me know and we can re-open this issue.

**Comment by sirshannon** [comment]
That's not a solution. A solution would be "uninstall node completely and use nvm to install node version [a specific node version here]".

**Comment by sirshannon** [comment]
not sure if this helps but here is the extremely simplified dependency graph showing the issue(s?):
```
├─┬ @aws-amplify/cli@1.1.4
│ ├─┬ amplify-codegen@1.0.9
│ │ ├─┬ amplify-graphql-docs-generator@1.0.7
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ amplify-graphql-types-generator@1.0.7
│ │ │ ├── graphql@14.1.1 deduped
│ │ │ 
│ │ ├─┬ aws-appsync-codegen@0.17.5
│ │ │ ├─┬ graphql@0.11.7
│ │ │ │ 
│ │ │ ├─┬ graphql-config@1.2.1
│ │ │ │ ├─┬ UNMET PEER DEPENDENCY graphql@0.12.3
│ │ │ │ ├─┬ graphql-import@0.4.5
│ │ │ 
│ │ ├─┬ graphql@14.1.1
│ │ │ 
│ │ ├─┬ graphql-config@2.2.1
│ │ │ ├─┬ graphql-import@0.7.1
│ │ 
│ ├─┬ amplify-provider-awscloudformation@1.0.10
│ │ ├── amplify-codegen@1.0.9 deduped
│ │ │ 
│ │ ├─┬ graphql-auth-transformer@3.0.7
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ graphql-connection-transformer@3.0.7
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ graphql-elasticsearch-transformer@3.0.7
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ graphql-transformer-common@3.0.5
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ graphql-transformer-core@3.0.7
│ │ │ ├─┬ graphql@0.13.2
│ │ │ 
│ │ ├─┬ graphql-versioned-transformer@3.0.7
│ │ │ ├─┬ graphql@0.13.2
```

**Comment by sirshannon** [comment]
Mentions of this issue as far back as November: #434

**Comment by kaustavghosh06** [comment]
@sirshannon Can you run `echo $PATH` and see if your bin directory where the amplify CLI is installed is included in it?

**Comment by shannon-hager-skookum** [comment]
It is. Amplify is found and usable for the few things I have tried in spite of the error.

**Comment by sirshannon** [comment]
It is. `/usr/local/bin` is the first item in my PATH and `which amplify` reports `/usr/local/bin/amplify`

Amplify is found and usable on one of my machines in spite of the error. I have not attempted to use it on all of my machines but did get that error on each of them.

See also #434 for someone having the error but being able to use amplify as expected.

**Comment by kaustavghosh06** [comment]
@sirshannon, in #434, @bearc0025 refers to the npm warnings when installing the CLI, are you referring to the following as errors?
```
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
```
The original issue if you look at the top refers to this:

```
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ amplify configure
-bash: amplify: command not found

```

In this case, the user is not able to execute the amplify commands after installing. Are you referring to the same issue?

**Comment by sirshannon** [comment]
@kaustavghosh06
Yes, that is a warning but if they were to list their npm modules after getting that warning, they would get the same error that everyone in this thread has posted.
```
npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5
```
I think it's been posted enough times by enough people to make it clear what we're talking about here.

**Comment by kaustavghosh06** [comment]
@sirshannon  I'm just trying to help out here and trying to ask clarifying questions since the peer dep issue is not at all related to the original issue by @cmrlabs 
If your issue is tied to the warnings/errors on installation we're tracking it as a part of #783

**Comment by sirshannon** [comment]
@kaustavghosh06
You closed this issue 5 days ago with no mention of #783

**Comment by aldokhayel** [comment]
same issue

**Comment by bestwade22** [comment]
any solution?

**Comment by jpbourgeon** [comment]
For what it's worth I have the exact same issue on Windows 10. However I have been using the CLI successfully since january without any major issue.

```shell
 # npm -v
6.7.0
 # node -v
v11.10.1
# npm ls --depth=0 -g
C:\Users\jpbourgeon\AppData\Roaming\npm
+-- @aws-amplify/cli@1.1.7
+-- npm-check@5.9.0
`-- serve@10.1.2

npm ERR! peer dep missing: graphql@^0.11.0 || ^0.12.0 || ^0.13.0, required by graphql-import@0.4.5
```

**Comment by rfdc** [comment]
same here!! Any solution?!

**Comment by joshmello** [comment]
Same

**Comment by aaronbesson** [comment]
Same

**Comment by aldokhayel** [comment]
Kindly share me your $PATH, print from terminal: "echo $PATH"

**Comment by aaronbesson** [comment]
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

i uninstalled node several times, reinstalled. like others i am getting the exact errors on install.

> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/aaronbesson/.npm-global/bin/amplify -> /Users/aaronbesson/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

>

**Comment by aldokhayel** [comment]
try to write this in terminal, but change "YOURNAME"
`export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/YOURNAME/npm/bin"`
@aaronbesson

**Comment by joshmello** [comment]
This may sound dumb but restart your computer after you install amplify. I
tested the restart on 3 machines with this issues and it fixed it for us.
Mac node via brew

**Comment by aaronbesson** [comment]
I ran
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/YOURNAME/npm/bin"

no difference

i also restarted :)
but that didnt change anything.. cant seems to find what's going on here.
this error is on my McBook Pro only, on my iMac, it works fine.. strange..

**Comment by aaronbesson** [comment]
OK, I narrowed down my issue to being either permissions related and/or improper paths.
I followed these instructions to uninstall npm/node (and I also uninstalled yarn) using brew
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

I also manually removed @aws-amplify from the usr/lib/node_modules dir.

I then fixed all the permissions, and reinstalled npm via brew and was able to install cli successfully. thanks to all who took time to respond and help out

**Comment by DanielCarns** [comment]
I had the same issue and it was caused by a few factors. The above solutions won't work unless you follow step #1 here.

1.) Amplify documentation doesn't tell you to first install the AWS CLI, it assumes you already have. Go here to follow those instructions: [(https://docs.aws.amazon.com/cli/latest/userguide/install-linux-al2017.html)]
2.) Make sure your version of node is updated (common sense I know) I got a syntax error upon installing it again because I was somehow running 5. instead of 12.

Hope this helps!!

**Comment by Mehdi-android** [comment]
I restarted, uninstalled & installed node again but no luck.

user@user-Lenovo-ideapad-300:~$ npm ls --depth=0 -g
/home/user/npm/lib
`-- @aws-amplify/cli@3.7.0

npm ERR! peer dep missing: leveldown@~1.4.3, required by @conduitvc/mosca@2.8.3
npm ERR! peer dep missing: ioredis@^1.15.1, required by @conduitvc/mosca@2.8.3
npm ERR! peer dep missing: mongodb@~2.1.4, required by @conduitvc/mosca@2.8.3
user@user-Lenovo-ideapad-300:~$

**Comment by sunilale0** [comment]
I installed aws cli first and then installed aws-amplify again. That worked for me.
