### ISSUE TITLE
Social sign in with apple scope, mapping and environment variables

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-cli#7793]
Recently sign in with apple option is added to the supported options in CLI (5.1.2). The hostedUIProviderMeta parameter is generated as follows:

```
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Facebook\",\"authorize_scopes\":\"email,public_profile\",\"AttributeMapping\":{\"email\":\"email\",\"family_name\":\"last_name\",\"given_name\":\"first_name\",\"username\":\"id\"}},{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"family_name\":\"family_name\",\"given_name\":\"given_name\",\"username\":\"sub\"}},{\"ProviderName\":\"SignInWithApple\",\"authorize_scopes\":\"email,name\",\"AttributeMapping\":{\"email\":\"email\",\"family_name\":\"lastName\",\"given_name\":\"firstName\"}}]",
```
This authorisation scope for sign in with apple is comma separated and attribute mapping is missing name to name and sub to username maps, this results in a weird configuration of the federation identity provider and mapping (a record with email,name is added on the top) in console and when redirected to Apple throws an error of "Invalid client scope"
If the checkboxes of the authorisation scope is unticked and ticked and saved in the console,  the issue goes away.

The console environment variables page does not specify the default variables for sign in with apple either. Please update it. 

[https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html)

![image](https://user-images.githubusercontent.com/24868344/126858801-e30e81ea-3107-41b1-99ef-bd4c89c59f70.png)
![image](https://user-images.githubusercontent.com/24868344/126858814-356555e9-d022-44b6-a4a5-0062a8b49be6.png)

**Comment by johnpc** [comment]
Is this a bug report for the CLI? If so can you provide steps to reproduce, and describe what you expected vs what you got?

As for your comment about the doc site, I believe that page is owned by amplify console, you can open up a ticket with them [here](https://github.com/aws-amplify/amplify-console/issues)

**Comment by pedramp20** [comment]
Yes it is a bug report. The steps to reproduce it:

```
amplify update auth
```

Then select:

```
Update OAuth social providers
```

Then tick 

```
Sign in with Apple
```
Then provide the requested information and finally
```
amplify push
```

The result is what I attached in the previous post and what is expected is this screen shot:
![image](https://user-images.githubusercontent.com/24868344/127729973-9a85b529-3361-4ef2-b8d6-8bfbc3f5b72e.png)

**Comment by letsbelopez** [comment]
If you'd like, you can test a fix we've been working on. https://www.npmjs.com/package/@aws-amplify/cli/v/5.3.0-siwa-update.3
