### ISSUE TITLE
Missing Authentication token 

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-cli#7795]
Dear Support Team,

I am building react app with **Cognito** for **auth** and **unauth** user, **DynamoDB** with **GraphQL API** to connect with my app
In my case I am trying to get data from DynamoDB by Graphql API the request works very well in some devices but in some other devices it doesn't work and returns the error: **Missing Authentication token.** even that I give permission in **I AM rules**

### the steps that I did
I gave permissions to auth and unauth user to use getUser request by GraphQL.
Note: it works very well in my devices like (PC widnow 10, smartphone android 9.1) but in some other devices like Asus, Windows 10 pro it doesn't work.

Does AWS have a problem of giving permission ? 
I guess it's **I AM rules** problem 

### Error I got
![124311221-4de58780-db65-11eb-86b5-03976a3e7500](https://user-images.githubusercontent.com/74948380/126865163-9a75c25b-5987-46bc-bb38-59f974adf726.jpg)

### My package.json
```
{
  "name": "myApp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    ...
    "@aws-amplify/ui-react": "^1.0.7",
    "aws-amplify": "^3.4.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
     ....
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
**What should I do ?**

**Comment by johnpc** [comment]
it could be that the authentication token is not being included in your request or that that the authentication token for your api has expired. Are you using amplify-generated code to initiate the request? Can you reproduce the error in a REST client or curl request?

**Comment by MedNabilEssefaihi** [comment]
Dear @johnpc
Thank you for your answer

The error message is **Missing Authentification token **

![IMG_20210730_185533.jpg](https://user-images.githubusercontent.com/74948380/127693127-9d6d5470-4c51-4a04-94eb-e7d55a977f2a.jpg)

**Comment by johnpc** [comment]
Can you share your graphql schema?

**Comment by MedNabilEssefaihi** [comment]
```
type User @model {
  id: ID!
  email: String!
  administrationId: ID!
  userType: String!
  administration: Administration @connection(fields: ["administrationId"])
}

```

**Comment by johnpc** [comment]
When using AWS_IAM for public API access, unauthenticated logins must be enabled. To enable unauthenticated logins, run amplify update auth from the command line and choose Walkthrough all the auth configurations.

Could that be the issue?

**Comment by johnpc** [comment]
Adding this annotation to your graphql schema will add the proper permissions: `@auth(rules: [{ allow: public, provider: iam }])`

**Comment by MedNabilEssefaihi** [comment]
Dear Mr @johnpc 

First of all, thank you so much for your time and your effort in my issue,

I made some the changes like:
### 1. Add I AM roles for unauth user  
![permission](https://user-images.githubusercontent.com/74948380/127903234-5ec18391-d451-48a7-87cf-87714ee191ba.png)

Example roles of code: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "appsync:GraphQL",
            "Resource": [
                "arn:aws:appsync:<regoin>:<account-id>:apis/<api_key>/types/Query/fields/listAdministrations",
            ]
        }
    ]
}
```

**Note I customized the GraphQL requests depend of my project need**

I recognized that we used different solutions, Do I need to change it and use the some steps as yours ?

**Comment by MedNabilEssefaihi** [comment]
I got a new error when I used another GraphQL request


![229159100_801865383782893_348203007518475524_n](https://user-images.githubusercontent.com/74948380/127905401-8b5315d8-03aa-4e99-ac1d-f15ab90f535a.jpg)

![225229005_1203668200151643_8332576835805729524_n](https://user-images.githubusercontent.com/74948380/127905405-00d39e00-b931-4406-a01a-36b2946ddbb4.jpg)

Any suggestion ? Thank you.

**Comment by johnpc** [comment]
I can't be sure about everything specifically going on in the code you have. But I have created a simple amplify app that demonstrates successful iam authenticated requests. You can see [here](http://mednabilessefaihi-20210802160947-hostingbucket-dev.s3-website-us-east-1.amazonaws.com) that the request succeeds and the payload is written to the screen.

The source code for this app [uses your graphql schema](https://github.com/johnpc/med-nabil-essefaihi/blob/master/amplify/backend/api/mednabilessefaihi/schema.graphql) shared in this ticket and simply [renders the result of the api request](https://github.com/johnpc/med-nabil-essefaihi/blob/master/src/App.js#L15) using `AWS_IAM` auth.

**Comment by MedNabilEssefaihi** [comment]
Dear @johnpc 

Well received, Thank you very much for the app ✅

**Comment by kaustavghosh06** [comment]
@MedNabilEssefaihi  Closing this issue based on @johnpc's response. Please feel free to let us know if you're still stuck.
