### ISSUE TITLE
How to do a complex database query in AWS Amplify

### ISSUE THREAD

**Issue by kgoyal98** [aws-amplify/amplify-cli#7798]
With Amplify API I am trying to implement something like a social network website. In the website, users can follow people and add posts. In the timeline, users can see the posts of people they follow. 

Schema is something like this:

```

type User @model {
  id: ID!
  name: String!
  following: [User] @connection(name: "UserFollowing")
  followers: [User] @connection(name: "UserFollowers")
}

type Post @model {
  id: ID!
  content: String
  user: User @connection
}

type UserFollow @model {
  id: ID!
  user: User @connection(name: "UserFollowing")
  followee: User @connection(name: "UserFollowers")
}

```

While implementing the timeline feature, I got stuck. How can I query user's timeline posts?
If I use RDS it might be easier by using a complex SQL query. However it doesn't look like Amplify supports SQL queries for RDS.

Can somebody please help me with this?

**Comment by johnpc** [comment]
So this should be possible to accomplish without using a complex sql query.

Just call `listPosts` with appropriate filters and update your schema file to this:

```

type User @model {
  id: ID!
  name: String!
  following: [UserFollow] @connection(name: "UserFollowing")
  followers: [UserFollow] @connection(name: "UserFollowers")
  posts: [Post] @connection(name:"UserPosts")
}

type Post @model {
  id: ID!
  content: String
  user: User @connection(name:"UserPosts")
}

type UserFollow @model {
  id: ID!
  user: User @connection(name: "UserFollowing")
  followee: User @connection(name: "UserFollowers")
}
```

Please reopen if you have any further questions

**Comment by kgoyal98** [comment]
@johnpc
I am unable to create the filter after reading the documentations. Can you please tell specifically what would be the filter?
