### ISSUE TITLE
amplify add notifications

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#78]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
does not add identity pool / IAM access when notifications is added to the project

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal amplify add notifications

**What is the expected behavior?**
add identity pool / IAM access when notifications is added to the project

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)** macOS Sierra
* **Output of ``amplify --version``**: 0.1.15
* **Did this work in previous versions?**: N

**Comment by rohandubal** [comment]
@haverchuck tagging as requested. Cannot assign as I do not have permissions.

**Comment by muellerfr** [comment]
What's the status of this issue?

**Comment by UnleashedMind** [comment]
The update has already been implemented and sent out in the PR #123 
Once it's approved, it'll be merged and published in our next release.

**Comment by muellerfr** [comment]
@UnleashedMind Thanks for the update.

**Comment by kaustavghosh06** [comment]
We just published to npm with a fix for this. Please use the version -> 0.1.19.
Closing the issue, feel free to re-open if the issue persists.
