### ISSUE TITLE
Unable to get latest version of cli (or uninstall current one)

### ISSUE THREAD

**Issue by jess010** [aws-amplify/amplify-cli#7818]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

6.14.13

### Amplify CLI Version

4.43 in use as current version / 5.2.0 installed

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

When creating a react app with AWS amplify using tutorial (https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-two/), I discovered I was unable to update older version of the amplify CLI installed through npm as part of a 3rd party tutorial in March 2021.

I tried both npm i -g @aws-amplify/cli and then npm i -g @aws-amplify/cli@latest. The install process showed as successful for v5.2.0, but when querying local version, this is still showing as v4.4.3. I also tried npm uninstall -g @aws-amplify/cli to reset, but this did not work to remove my current instance (i.e. 'amplify -v' shows 4.4.3, and amplify configure' executes even after supposed uninstall). 

Appreciate guidance on reset and update of current CLI version.

### Expected behavior

amplify -v shows current version (v5.x) after current version has been installed via npm i -g @aws-amplify/cli@latest 
npm uninstall -g @aws-amplify/cli results in amplify no longer being installed on desktop

### Reproduction steps

1a. npm i -g @aws-amplify/cli@latest
1b. amplify -v
2a. npm uninstall -g @aws-amplify/cli
2b. amplify -v

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

----------------------------------------
Successfully installed the Amplify CLI
----------------------------------------
....
Learn more - https://docs.amplify.aws/cli/reference/usage-data
+ @aws-amplify/cli@5.2.0
updated 18 packages in 35.63s

amplify -v
4.43.0

**Comment by johnpc** [comment]
Interesting - this always works for me.

What is the result of running `which amplify` and `npm root -g`?

**Comment by jess010** [comment]
which amplify
/usr/local/bin/amplify

npm root -g
/Users/<user>/.nvm/versions/node/v12.22.3/lib/node_modules

**Comment by johnpc** [comment]
That would be why. When you reinstall amplify via npm, it's installing the and updating binary in your `npm root -g` directory. Unless `/usr/local/bin/amplify` is a properly configured symlink, your npm commands will have no effect. 

You could try removing `/usr/local/bin/amplify` and making sure your npm root is in your $PATH

**Comment by jess010** [comment]
Got it, I am set with latest version now. Thanks @johnpc, this was extremely helpful!
