### ISSUE TITLE
Simplify `amplify push` confirmation prompts

### ISSUE THREAD

**Issue by flybayer** [aws-amplify/amplify-cli#782]
**Is your feature request related to a problem? Please describe.**
`amplify push` is currently a bit annoying and could be simplified. Each time you run the command it prompts you three times for various confirmations. It's annoying because 99% of the time you hit `yes` for all three.

<img width="947" alt="screen shot 2019-01-28 at 16 14 31" src="https://user-images.githubusercontent.com/8813276/51867086-96efdc80-2318-11e9-8426-35587ae300db.png">

**Describe the solution you'd like**
I propose leaving the initial push confirmation as is, but after the initial push save the preferences for code generation in `amplify/.config/project-config.json`

**Describe alternatives you've considered**
Support a `-y` flag so `amplify push -y` would run without any prompts.

**Comment by kaustavghosh06** [comment]
@flybayer Are you using the multienv version of the CLI?

**Comment by flybayer** [comment]
I'm not sure. How do I know?

It's version 0.1.44

**Comment by kaustavghosh06** [comment]
@flybayer We have headless support in the @multienv version of the CLI which is currently in beta. We'll have updated docs on this once we merge it to master. For now you can take a look at some headless scripts, like the push headless command - https://github.com/aws-amplify/amplify-cli/blob/multienv/packages/amplify-cli/sample-headless-scripts/headless_push.sh
