### ISSUE TITLE
Constant unexpected changes when pushing

### ISSUE THREAD

**Issue by connected-mdeluco** [aws-amplify/amplify-cli#7829]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.1.2

### What operating system are you using?

Mac

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

I created a new environment yesterday starting from my `develop` environment. I made a small change to our model defined in `schema.graphql`, pushed them to my new environment, and committed the changes to a feature branch.

This morning I merged the feature branch into the dev branch, checked out and updated the dev branch, checked out the develop environment, and pushed the changes to the develop environment.

I ended up with the first attached change in my repo. What is it? Why did it happen?

I had something similar happen yesterday, second diff attached below.

How do I stay ahead of these kinds of things? It's a real hassle when working with protected branches - I've got to create a new branch for these changes and have someone on my team review the pull request.

```
diff --git a/src/graphql/schema.json b/src/graphql/schema.json
index 230f093..3029f64 100644
--- a/src/graphql/schema.json
+++ b/src/graphql/schema.json
@@ -5083,6 +5083,23 @@
         "onOperation" : false,
         "onFragment" : false,
         "onField" : false
+      }, {
+        "name" : "deprecated",
+        "description" : null,
+        "locations" : [ "FIELD_DEFINITION", "ENUM_VALUE" ],
+        "args" : [ {
+          "name" : "reason",
+          "description" : null,
+          "type" : {
+            "kind" : "SCALAR",
+            "name" : "String",
+            "ofType" : null
+          },
+          "defaultValue" : "\"No longer supported\""
+        } ],
+        "onOperation" : false,
+        "onFragment" : false,
+        "onField" : false
       }, {
         "name" : "aws_subscribe",
         "description" : "Tells the service which mutation triggers this subscription.",
@@ -5133,23 +5150,6 @@
         "onOperation" : false,
         "onFragment" : false,
         "onField" : false
-      }, {
-        "name" : "deprecated",
-        "description" : null,
-        "locations" : [ "FIELD_DEFINITION", "ENUM_VALUE" ],
-        "args" : [ {
-          "name" : "reason",
-          "description" : null,
-          "type" : {
-            "kind" : "SCALAR",
-            "name" : "String",
-            "ofType" : null
-          },
-          "defaultValue" : "\"No longer supported\""
-        } ],
-        "onOperation" : false,
-        "onFragment" : false,
-        "onField" : false
       }, {
         "name" : "aws_lambda",
         "description" : "Tells the service this field/object has access authorized by a Lambda Authorizer.",
@@ -5166,23 +5166,6 @@
         "onOperation" : false,
         "onFragment" : false,
         "onField" : false
-      }, {
-        "name" : "deprecated",
-        "description" : null,
-        "locations" : [ "FIELD_DEFINITION", "ENUM_VALUE" ],
-        "args" : [ {
-          "name" : "reason",
-          "description" : null,
-          "type" : {
-            "kind" : "SCALAR",
-            "name" : "String",
-            "ofType" : null
-          },
-          "defaultValue" : "\"No longer supported\""
-        } ],
-        "onOperation" : false,
-        "onFragment" : false,
-        "onField" : false
       }, {
         "name" : "aws_publish",
         "description" : "Tells the service which subscriptions will be published to when this mutation is called. This directive is deprecated use @aws_susbscribe directive instead.",
```

Another synchronization issue:
```
diff --git a/amplify/backend/auth/userPoolGroups/template.json b/amplify/backend/auth/userPoolGroups/template.json
index 7ab361f..05fcfe7 100644
--- a/amplify/backend/auth/userPoolGroups/template.json
+++ b/amplify/backend/auth/userPoolGroups/template.json
@@ -183,10 +183,7 @@
                                     "Action": [
                                         "iam:PassRole"
                                     ],
-                                    "Resource": [
-                                        { "Ref": "AuthRoleArn" },
-                                        { "Ref": "UnauthRoleArn" }
-                                    ]
+                                    "Resource": "*"
                                 }
                             ]
                         }
@@ -236,6 +233,7 @@
                                 "    cognitoidentity.setIdentityPoolRoles(params).promise();",
                                 "    response.send(event, context, response.SUCCESS, {message: 'Successfully updated identity pool.'})",
                                 "    } catch(err) {",
+
                                 "        response.send(event, context, response.FAILED, {message: 'Error updating identity pool'});",
                                 "    }",
                                 "   };",
```

### Expected behavior

I expect anything auto generated to not constantly change, when there doesn't seem to be reason for change, requiring additional work to keep up.

### Reproduction steps

I don't know why this is happening.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by connected-mdeluco** [comment]
Here's another, after checking out an environment. `myAppService` doesn't exist in the environment I switched to, so presumably it should be removed entirely from `team-provider-info.json` rather than set to an empty object.

The parent object of `myAppService` is `categories`.

```
diff --git a/amplify/team-provider-info.json b/amplify/team-provider-info.json
index 62bc8f2..4c763a8 100644
--- a/amplify/team-provider-info.json
+++ b/amplify/team-provider-info.json
@@ -118,7 +118,8 @@
         "AdminQueriesfd14adb5": {
           "deploymentBucketName": "amplify-myapp-sfththth-100810-deployment",
           "s3Key": "amplify-builds/AdminQueriesfd14adb5-6152633649656e65566e-build.zip"
-        }
+        },
+        "myAppService": {}
       }
     }
   }
```

**Comment by johnpc** [comment]
When you update schema.graphql, I do expect some changes to auto generated files.

Is it possible that different versions of the CLI were used at any point in what they were doing? The userPoolGroups change especially looks like there was a version change involved.

**Comment by kaustavghosh06** [comment]
Closing this issue due to lack of further response. Please let us know if you're still stuck on this.

**Comment by connected-mdeluco** [comment]
@johnpc - so these constant minor differences are just something we have to live with in VCS?

If there's no functional difference, maybe there's no reason for them to happen between versions of the CLI. i.e. keep autogen output consistent for the sake of your customers.
