### ISSUE TITLE
Deprecated usage of cfn-lint

### ISSUE THREAD

**Issue by alex-unikorny** [aws-amplify/amplify-cli#7831]
https://github.com/aws-amplify/amplify-cli/blob/b1b6291ac79b18b55723f9463aa93005ab75be88/packages/amplify-provider-awscloudformation/src/push-resources.ts#L539

The library https://www.npmjs.com/package/cfn-lint is deprecated, and I get some confusing errors, for example in my case I have this error pushing resources -- No such resource AWS::CodeArtifact::Domain, but if I validate the template with aws cli all is right.

I think is much better use aws cli to validate the cloudformation template instead of the usage of this deprecated library or create a new one to avoid this outdating problems.

**Comment by johnpc** [comment]
any chance you could share your configuration that fails this deprecated validation, but passes using aws cli validation?

**Comment by alex-unikorny** [comment]
Here is an example, thanks!

[codeartifact-cloudformation-template.yml.zip](https://github.com/aws-amplify/amplify-cli/files/6901826/codeartifact-cloudformation-template.yml.zip)

**Comment by johnpc** [comment]
Recently, another customer was experiencing these errors (https://github.com/aws-amplify/amplify-cli/issues/7132) so we changed cfn-lint from an error to a warning and resolved the issue.

Since aws cli only provides linting source code in python, we can't easily share the linting logic with aws-cli.

If you're still experiencing issues with errors, you may just need to upgrade your version of the cli.

**Comment by alex-unikorny** [comment]
Makes sense, but current master branch has the log level as error, I'm seeing context.print.error instead of context.print.warning, I checking a wrong branch maybe?

**Comment by johnpc** [comment]
is the only issue the logging? Or does this actually prevent you from being able to deploy the resources?

**Comment by alex-unikorny** [comment]
Just logging issue, I think is confusing.

**Comment by johnpc** [comment]
Agreed, it should be changed from `context.print.error` to `context.print.warning`

**Comment by edwardfoyle** [comment]
closing as above PR has been merged
