### ISSUE TITLE
Auth Sign Up Custom Flow -- username cannot be of email format anymore in `Auth.signUp()`

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#7833]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.1.0 - 5.6.0

### What operating system are you using?

Debian 10

### Amplify Categories

auth

### Amplify Commands

Not applicable - problem is in the client code (Javascript)

### Describe the bug

The 

    Amplify.Auth().signUp()

method  no longer lets you send the email address as the `username` when it is an email-only sign-up.

Our method of sign-up used to always work but it just broke in Amplify CLI version 5.2.0. 

(NOTE: we don't use Authenticator, we call the API instead the usual way via code that has worked for many months already)

When you set up for email-only verification and sign-up, you were previously able to supply the email address as the username because the email address **is** the username in that case.

But that use case no longer works.  Here's the code that used to work and no longer works:
```typescript
        return Auth.signUp({
            username: email,
            password,
            attributes: { email }
        });
```

This used to always work. The way in which today it no longer works is this: as soon as you call this function, it returns an error (in the promise) that says:

```
    Username cannot be of email format, since user pool is configured for email alias.
```

### Expected behavior

Expected the method `Auth.signUp()` not to return an error saying that the email format cannot be used for username "since user pool is configured for email alias". I had never asked for anything like "email alias" and am not sure what "email alias" means. I believe the CLI erroneously assumes we are asking for this "email alias" here.

### Reproduction steps

Create an auth flow via software where you call
```typescript
        return Auth.signUp({
            username: email,
            password,
            attributes: { email }
        });
```

where `email` is a string variable containing a user's valid email address 

and `password` is the user's password 

And you'll get the same error message.

### GraphQL schema(s)

Not Applicable

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dorontal** [comment]
This is very likely related to #7666 and that's why it is mentioned there (the problem in issue #7666 is the same problem but this is a different way in which the same problem shows up).

**Comment by dorontal** [comment]
I can't tell for sure but do believe that it's quite likely the fix of #7671 will resolve this issue too. Thanks for mentioning it.

**Comment by iyz91** [comment]
This happens even without adding any triggers after upgrading CLI to 5.2.0. Very frustrating seeing as it's a pretty front line thing to regress and can't change it once the user pool is created.

**Comment by iyz91** [comment]
Downgrading cli to 5.1.2 solves the problem and creates the pool correctly.

**Comment by vincent38wargnier** [comment]
I have the same issue, i select email :
![image](https://user-images.githubusercontent.com/33725800/128257694-1217f8f6-3221-446e-9daf-b1f063bd607a.png)
But at the end I have the following configuration :
![image](https://user-images.githubusercontent.com/33725800/128257783-86a4e419-bfbb-4456-b1ce-234f125510b8.png)
So when I call the Cognito API to create a user it throws me this back :
![image](https://user-images.githubusercontent.com/33725800/128257878-5820ed3c-f018-4fbb-8928-a6766f0f463c.png)

**Comment by dorontal** [comment]
Just tried this again with the new version (5.3.0) and the bug is still there.

This issue is very debilitating any development of any app that needs a signed-up user to develop. I cannot create even one signed-up user right now. I would very much appreciate a fix. It does not seem like a difficult fix and there are already pull requests for this. Thank you.

Adding a screenshot that shows in more detail the error that we get that says:

   "Username cannot be of email format, since user pool is configured for email alias.":

![Screenshot from 2021-08-06 10-48-10](https://user-images.githubusercontent.com/5935957/128529497-7a8a7acc-2bab-4000-a63d-32ff30ffbeaf.png)

**Comment by dorontal** [comment]
Just tried this again with the new version (5.3.0) and the bug is still there.

This issue is very debilitating -- any development of any app that needs a signed-up user to develop is now impossible.

The error that gets returned when we try to sign up a user with an email address, right now, is:

    "Username cannot be of email format, since user pool is configured for email alias."

**Comment by c0h1b4** [comment]
Any updates or estimate when this issue will be solved? We have a project that is stalled because of this. Will move to other platform if this is not solvable.

**Comment by dmost714** [comment]
I've also encountered this issue on a new project.
Brought it up in Discord and was pointed here.

Here are a few details:

I used `amplify add auth`, selected 'email' and 'no' for advanced.
I believe this setup also leaves you in a state where the verification email will not be sent.
I deleted auth and tried again using 'manual' config via the cli tool. That also didn't work.
**I deleted auth and configured it via the Amplify Admin UI. That worked. Yay.**

Here's the react code snippet I was using:
```
function App() {
  return (
    <AmplifyAuthContainer>
      <AmplifyAuthenticator usernameAlias="email">
        <AmplifySignUp
          slot="sign-up"
          usernameAlias="email"
          formFields={[
            { type: "email" },
            { type: "password" }
          ]}
        />
      </AmplifyAuthenticator>
    </AmplifyAuthContainer>
  )
}
```

Hope this helps someone!

**Comment by dorontal** [comment]
@dmost714 I went to the Amplify Admin UI [here](https://console.aws.amazon.com/amplify/home) but it just brought me back to the Cognito User Pool Console dialog shown above -- and that did not allow me to create the user with the error `... user pool is configured for email alias ...` - how did the Amplify UI help you?  I must have used it in the wrong way because every time I try, it just brings me to the Cognito Console UI. Thanks for any pointers!

**Comment by dmost714** [comment]
> I went to the Amplify Admin UI [here](https://console.aws.amazon.com/amplify/home) but it just brought me back to the Cognito User Pool Console dialog

Don't click "Authentication" under the "categories added" label.
You have to go to the "Admin UI". You get there by clicking the "Open admin UI" button.
You may need to enable the UI with a switch. If you made changes with it, it will update your cloud formation, so you then need to 'amplify pull' in the terminal to sync local environments with the cloud (same as if another team member mades changes I suppose). Once in the "Admin UI" page, head to the find "Configure login and signup" under the person icon and click the button. At the bottom of that section you may see a "Reset all authentication settings and users" button which you can use to wipe the slate clean and try again. (Or 'amplify remove auth' from the terminal.

<img width="617" alt="Screen Shot 2021-08-12 at 7 14 03 PM" src="https://user-images.githubusercontent.com/224830/129281914-d7c13bdf-d7f6-4037-aa48-1f01eb33b5a6.png">

**Comment by dorontal** [comment]
Thanks very much, @dmost714!  After tinkering with the new Admin UI for a while it did not work for me for seemingly obscure reasons, which I could detail if somebody really needs to know, but I think I'll just wait until the Amplify team fixes this simple issue - saw that there's a PR for it already.

**Comment by dorontal** [comment]
UPDATE @dmost714!  I was able to use the Admin UI to create a functional user pool with email-only verification!

I had to start a new app altogether for that, though. I could not do this with my existing app, because some wrong config settings were getting during user-pool creation in a way that could not be changed later.

In the new app, I followed your procedure. It was Angular for me but your procedure still worked. I had to do
```
amplify init
amplify add auth
amplify push
```
then reset the auth from the Admin UI.
then the AdminUI gave free reign to create a new user pool with email-only verification.

Now I can try to morph this blank app into my existing app and perhaps continue to develop seamlessly that way :)

Thanks!

**Comment by dmost714** [comment]
> That's because when you add a trigger

We're on a similar journey, I'm also waiting on the auth trigger PR. You don't need to `amplify add auth` in the CLI, then delete it in the Admin UI. You can just create it using the Admin UI.

For my 2 triggers, what I did was create the triggers using `amplify update auth`, and `amplify push` to push them to the cloud. Then `amplify remove auth` & push to delete auth (since it gets clobbered). The lambda auth triggers won't be deleted (bug?). Now head over to Admin UI and create Auth. Then head over to Cognito (in AWS console), go into your user pool's 'triggers' section and manually add the triggers using the dropdown boxes. (Or dig up the CLI actions to do the same...). 

Doing the above, your triggers won't be defined in your cloud formation, so it's just a temporary workaround.

**Comment by dorontal** [comment]
This pull request seems to suggest that it is an Amplify CLI fix, and an easy one. I believe this pull request below may be the fix, right? 
https://github.com/aws-amplify/amplify-cli/pull/7671

**Comment by dorontal** [comment]
This bug seems solved / fixed as of today - thank you so much, Amplify team!

I just tried the new Amplify CLI version (6.0.0) and this bug no longer happens: it is now possible to create an email format username with email-only verification.

**Comment by dorontal** [comment]
This bug seems solved / fixed as of today - thank you so much, Amplify team!

I just tried the new Amplify CLI version (6.0.0) and this bug no longer happens: it is now possible to create an email format username with email-only verification.
