### ISSUE TITLE
Can't Run any Amplify Commands. Found '}' where a key name was expected

### ISSUE THREAD

**Issue by julien-tamade** [aws-amplify/amplify-cli#7837]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.16.1

### Amplify CLI Version

can't run

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

add, env, push, status

### Describe the bug

I had made two changes before pushing. One was updating auth permissions in a graphql model
from: 
@auth(
  rules: [
    {allow: private, operations: [read]}
    { allow: public, provider: apiKey, operations: [read] }
  ]
)

to:
@auth(
  rules: [
    {allow: private, operations: [read]}
    { allow: public, provider: apiKey, operations: [read] }
    { allow: public, provider: iam, operations: [read] }
  ]
)

And also made some changes to a lambda function

When I pushed it made it quite a way through the push and then I got the error: 
Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 6,9 >>>        }
      ],
  ...

I am now unable to run any amplify commands because I get the same error.
I've searched for ">>>" and found nothing
I can't even run 'amplify version'

### Expected behavior

I would appreciate if it told me which file the error was in so I could go find it

### Reproduction steps

I'm not sure what may have cause it.
I had made two changes before pushing. One was updating auth permissions in a graphql model
from: 
@auth(
  rules: [
    {allow: private, operations: [read]}
    { allow: public, provider: apiKey, operations: [read] }
  ]
)

to:
@auth(
  rules: [
    {allow: private, operations: [read]}
    { allow: public, provider: apiKey, operations: [read] }
    { allow: public, provider: iam, operations: [read] }
  ]
)

And also made some changes to a lambda function

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Resource
@model (subscriptions: null, mutations: null)
@auth(
  rules: [
    {allow: private, operations: [read]}
    { allow: public, provider: apiKey, operations: [read] }
    { allow: public, provider: iam, operations: [read] }
  ]
){
  id: ID!
  title: String
  description: String
  link: String
  destination: ResourceDestination
  thumbnailLink: String
  category: ResourceCategory
}

```

</details>

### Log output

<details>

```
error: uncaughtException: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 6,9 >>>        }
      ],
  ... date=Thu Jul 29 2021 20:24:26 GMT-0700 (Pacific Daylight Time), pid=53896, uid=501, gid=20, cwd=/Users/Julien/Documents/Flowly-Backend, execPath=/usr/local/bin/node, version=v12.16.1, argv=[/usr/local/bin/node, /usr/local/bin/amplify, push], rss=386326528, heapTotal=306163712, heapUsed=293316112, external=37396978, loadavg=[3.48193359375, 4.24951171875, 4.08447265625], uptime=645609, trace=[column=11, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js, function=error, line=41, method=null, native=false, column=9, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js, function=keyname, line=163, method=null, native=false, column=15, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js, function=object, line=353, method=null, native=false, column=28, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js, function=legacyRootValue, line=434, method=null, native=false, column=23, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js, function=Object.module.exports, line=454, method=exports, native=false, column=20, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts, function=Function.JSONUtilities.parse, line=109, method=parse, native=false, column=32, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts, function=Function.JSONUtilities.readJson, line=33, method=readJson, native=false, column=37, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts, function=updateAwsMetaFile, line=19, method=null, native=false, column=23, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts, function=AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate], line=143, method=updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate], native=false, column=56, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, function=null, line=357, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=46, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, function=null, line=350, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=10, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js, function=CloudFormation.updateamplifyMetaFileWithStackOutputs, line=349, method=updateamplifyMetaFileWithStackOutputs, native=false, column=null, file=null, function=runMicrotasks, line=null, method=null, native=false, column=5, file=internal/process/task_queues.js, function=processTicksAndRejections, line=97, method=null, native=false], stack=[Error: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 6,9 >>>        },       ],,   ...,     at error (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11),     at keyname (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:163:9),     at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15),     at legacyRootValue (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:434:28),     at Object.module.exports (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23),     at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:109:20),     at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:33:32),     at updateAwsMetaFile (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts:19:37),     at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/update-amplify-meta.ts:143:23),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:357:56,     at Array.forEach (<anonymous>),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:350:46,     at Array.forEach (<anonymous>),     at CloudFormation.updateamplifyMetaFileWithStackOutputs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:349:10),     at runMicrotasks (<anonymous>),     at processTicksAndRejections (internal/process/task_queues.js:97:5)]


Julien@Juliens-MBP-4 flowly-backend % amplify push
Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 6,9 >>>        }
      ],
  ...
Error: Found '}' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 6,9 >>>        }
      ],
  ...
    at error (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:41:11)
    at keyname (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:163:9)
    at object (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:353:15)
    at legacyRootValue (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:434:28)
    at Object.module.exports (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/hjson/lib/hjson-parse.js:454:23)
    at Function.JSONUtilities.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:91:22)
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/jsonUtilities.js:47:32)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:262:56)
    at StateManager.getMeta (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/state-manager/stateManager.js:41:31)
    at checkIfMobileHubProject (/usr/local/lib/node_modules/@aws-amplify/cli/lib/utils/mobilehub-support.js:19:50)
    at Object.ensureMobileHubCommandCompatibility (/usr/local/lib/node_modules/@aws-amplify/cli/lib/utils/mobilehub-support.js:7:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:112:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

</details>

### Additional information

none

**Comment by josefaidt** [comment]
Hey @julien-tamade :wave: thanks for raising this! I was unable to reproduce this with similar small changes to a GraphQL API. A few follow-up questions to better understand the context:

- do you experience this issue with only the changes made to your schema (not also the function)?
- do you notice any stray curly braces in your project's `amplify-meta.json`
- what kind of changes were made to the function (code changes, `amplify update function`)?

**Comment by julien-tamade** [comment]
@josefaidt  thank you for the reply.

So i checked out amplify-meta.json and noticed there's a ton of unknown characters at the top:
���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������tributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput",
            "GraphQLAPIKeyOutput"
          ]
        }
      ],

**Comment by julien-tamade** [comment]
If I delete this file, will it regenerate when running amplify push? What should I do?

**Comment by johnpc** [comment]
I think if you remove the file and call `amplify pull` amplify-meta.json will regenerate.

**Comment by julien-tamade** [comment]
@johnpc unfortunately that didn't work. after removing amplify-meta.json I can't run push or pull

**Comment by josefaidt** [comment]
@julien-tamade can you run and step through the prompts for `amplify init`? This should regenerate the amplify-meta.json file

**Comment by josefaidt** [comment]
Hey @julien-tamade were you able to successfully regenerate the amplify-meta.json file by stepping through `amplify init`?

**Comment by julien-tamade** [comment]
@josefaidt yes, that solved it. Thank you!

**Comment by josefaidt** [comment]
🙏 awesome! Glad to hear it! Closing issue based on response above.
