### ISSUE TITLE
How to reuse a CloudFormation template on same category?

### ISSUE THREAD

**Issue by ghost** [aws-amplify/amplify-cli#7849]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
How to reuse a Cloudformation template

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

5.2.1

**What AWS Services are you utilizing?**

CodeBuild

**Provide additional details e.g. code snippets**

I have a Cloudformation template that creates a CodeBuild project receiving as parameters all the variable data, the problem is that I don't know how to reuse it without copy paste the template on other resource folder (using amplify, because using stacks without amplify is not possible for my project)

Here is an example of my current backend folder structure:
- backend
   - codebuild
      - build-project-repo1
         - create-build-proyect-template.yml
         - parameters.json
      - build-project-repo2
         - create-build-proyect-template.yml
         - parameters.json

It's possible to reuse the template in a folder structure like this?
- backend
   - codebuild
      - create-build-proyect-template.yml
      - build-project-repo1 (reusing template)
         - parameters.json
      - build-project-repo2 (reusing template)
         - parameters.json

Thanks in advance.

**Comment by johnpc** [comment]
I don't think that specifically is possible.

However, have you tried using [amplify environments](https://docs.amplify.aws/cli/teams/overview)? Environments can be used to pass different parameters to a code build resource.

You could also try using a symlink in order to reuse the file but I can't guarantee that'll work either.

**Comment by alex-unikorny** [comment]
Has sense to request this as an improvement? I tried with the symlink and works well, thank! 
But I think that Amplify could be more flexible to manage resources on AWS for example if backend-config.json file improves adding the references of base templates for each categories and improve the readability with an yml file and dependencies declaration like this:

<img width="480" alt="Screenshot 2021-08-03 at 18 43 49" src="https://user-images.githubusercontent.com/87278251/128054024-d6f92a1f-4d61-4f37-ab80-b902bcdd466c.png">

Regards!!

**Comment by johnpc** [comment]
Glad the symlink solution got you unblocked in the meantime.

And sure! That would be cool! I'll mark this as a feature request.

**Comment by johnpc** [comment]
Glad the symlink solution got you unblocked in the meantime.

And sure! That would be cool! I'll mark this as a feature request.

**Comment by josefaidt** [comment]
Closing issue as the Amplify CLI has moved away from git-tracked CloudFormation templates and now builds these templates in the ephemeral `build/` directory within the corresponding resource
