### ISSUE TITLE
Issue with opening of browsers on windows 

### ISSUE THREAD

**Issue by Aeolun** [aws-amplify/amplify-cli#785]
**Describe the bug**
I install amplify, literally every command fails somewhere.

**To Reproduce**
1. Install amplify `npm i -D @aws-amplify/cli`
2. See it introduce around 140 security vulnerabilities 💯 .
3. 
```
$ ./node_modules/.bin/amplify configure
? Select the backend providers.
```
4. Nothing beyond `? Select the backend providers.` is displayed on the command line. Enter exits the program.
5. 
```
$ ./node_modules/.bin/amplify init
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: Vim (via Terminal, Mac OS only)
? Choose the type of app that you're building

/mnt/c/Users/bart.riepe/Projects/chat-ui/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot read property 'value' of undefined
```
6. Again nothing is displayed after I want to choose my app type, pressing enter explodes again.

This is running in WSL on Ubuntu.

**Expected behavior**
I expect to execute commands, and have them function. I also kind of expect amplify to work without having to directly link to a specific account/region/profile, but I haven't actually got that far yet.

**Additional context**
```
$ npm --version
6.4.1
$ node --version
v8.15.0
$ ./node_modules/.bin/amplify --version
0.1.44
```

**Comment by kaustavghosh06** [comment]
@Aeolun. We can surely look into this. Can you see if you can temporarily unblock yourself my globally installing the CLI using ‘npm install -g @aws-amplify/cli’?

**Comment by jkeys-ecg-nmsu** [comment]
@Aeolun almost everything the CLI offers, besides `amplify configure`, works in WSL. I still use Ubuntu on Windows for my daily Amplify development tasks.

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 globally installing Amp CLI does not resolve `amplify configure` issue. Based on the error it looks like Amplify sees that it's running on a Windows environment so it tries to spawn cmd.exe instead of another ubuntu shell to do the work. That'd be my guess as to the error at any rate.

**Comment by UnleashedMind** [comment]
@Aeolun 
I've tested recent versions of the Amplify-CLI  (such as 1.7.5), and it's working as expected on Windows 10 on both powershell and cmd.exe, you can just run the Amplify-CLI commands directly on them.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu @Aeolun
