### ISSUE TITLE
Amplify Geo

### ISSUE THREAD

**Issue by IsaacTrevino** [aws-amplify/amplify-cli#7850]
### Is this related to another service?

Amplify Geo

### Describe the feature you'd like to request

Needed Features in Geo CLI `amplify add geo`
- Auth Cognito Groups privilege's with regards to Maps.
- Missing Esri Satellite (Imagery) Map Style

### Describe the solution you'd like

Adding groups auth, since incurring auth error when using groups to access maps.

Satellite Imagery Map not in CLI

### Describe alternatives you've considered

Adding Custom LocationService Policy to Auth groups manually in Auth Groups via IAM.

Modify ampliy cloudfomation resource to add Satellite map  

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Closing as `geo` category has since been added to the CLI, https://docs.amplify.aws/cli/geo/maps/
