### ISSUE TITLE
Cloudformation uses default value instead of using actual bucket name of environment after `amplify push`

### ISSUE THREAD

**Issue by wahmd** [aws-amplify/amplify-cli#7851]
**Which Category is your question related to?**
Cloudformation, S3 bucket 

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
5.2.0

**What AWS Services are you utilizing?**
cloudformation, S3 bucket, lambda, 

**Provide additional details e.g. code snippets**

**I am writing to s3 inside lambda function but it picks the default value from the cloudformation stack while it should be picking current environment bucket value.** 

Steps used to add bucket in my lambda function:
![image](https://user-images.githubusercontent.com/74547936/127822331-f8b567fd-1e0b-41c0-9f08-896e1e57b7cc.png)

key changes in cloudformation 
![image](https://user-images.githubusercontent.com/74547936/127822717-c0f09872-f82d-4d7d-9256-44253773b721.png)
then in env vars
![image](https://user-images.githubusercontent.com/74547936/127823318-7a05ec0d-5c4e-4e8c-9d19-ba3b634f8001.png)

after `amplify push` , when env vars pick the default value instead of the actual bucket that exists in that environment 
![image](https://user-images.githubusercontent.com/74547936/127823081-97cc74d3-0963-4ad2-b48c-b763a9270cd9.png)

**Comment by johnpc** [comment]
when are you passing in the `storageXxxStorageBucketName` parameter to your cloudformation? The cloudformation json looks correct - that environment variable should be set to whatever you pass in for that parameter.

I would like to see your `parameter.json` file used for storage.

**Comment by wahmd** [comment]
parameters.json for this lambda is just empty object. {}.
However, the function-parameters.json looks like: 
![image](https://user-images.githubusercontent.com/74547936/127900884-888455bf-3f5f-4fea-b303-c02f37c4b7dc.png)

**Comment by johnpc** [comment]
I don't see a parameter there called `storageXxxStorageBucketName`. Maybe the env var should just come from the `bucketName` parameter instead?

**Comment by kaustavghosh06** [comment]
@wahmd Did you push the storage resources to the cloud?

**Comment by wahmd** [comment]
> I don't see a parameter there called `storageXxxStorageBucketName`. Maybe the env var should just come from the `bucketName` parameter instead?

Yes, this is what I think it should automatically pick with this name format storagexxxStorageBucketName. After pushing again, I'm getting bucket name correctly without changing any code. This is getting highly unpredictable & unreliable as code breaks or works after pushing to cloud without any code change. Just to be on safe side, I also added in `parameters.json`
```
{
  "storagexxxStorageBucketName": {
    "Fn::GetAtt": ["storagexxxStorage", "Outputs.BucketName"]
  }
}
```

Until I figure out why its not always picking env bucketname variable, I am constructing bucketName manually concatenated with current env inside my lambda function. so in case it breaks, I do have the correct bucket name.

**Comment by wahmd** [comment]
> @wahmd Did you push the storage resources to the cloud?

Yes, the resources are pushed to cloud with `amplify push` command

**Comment by fkunecke** [comment]
There's 4 things needed to fill in this value. Check that you've got them all.

for this example I'm going to assume that you added a `storage` resource and named it `data`.  This is important for your cloudformation templates.

The value must be in `Outputs` on the cloudformation template for the resouce you're trying to access:
```
"Outputs": {
    "BucketName": {
        "Value": {
            "Ref": "S3Bucket"
        },
        "Description": "Bucket name for the S3 bucket"
    },
}
```

The resource needs to be in the `dependsOn` array in the `backend-config` for the service you're trying to access it from:
```
"function": {
  "name-of-your-function": {
    "service": "Lambda",
    "providerPlugin": "awscloudformation",
    "build": true,
    "dependsOn": [
      {
        "category": "storage",
        "resourceName": "data",
        "attributes": [
          "BucketName"
        ]
      }
    ]
  }
}
```

Note that it's essential that the name matches exactly between `attributes` and `Outputs` in the above 2 files.


Then, you need two parts in the cloudformation template of the service trying to access the resource from. In your case this would be the CF template for the function. Assuming the resource name is `data` this would be:

```
"Parameters": {
  "storagedataBucketName": {
    "Type": "String",
    "Default": "storagedataBucketName"
  }
}
```

And then you can access this parameter through your environment variables:

```
"Environment": {
  "Variables": {
    "STORAGE_DATA_BUCKETNAME": {
      "Ref": "storagedataBucketName"
    }
  }
}
```

If these aren't set correctly then something went wrong generating the files. You should also be able to follow this as a guide for adding custom resources to your amplify project (just remember to do an `amplify env checkout envname` if you ever manually change your `backend-config`).

Hope this helps!
