### ISSUE TITLE
Cannot push any changes -  An error occurred while fetching the app backend: Network Failure

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#7852]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.7.0

### Amplify CLI Version

5.2.1

### What operating system are you using?

Windows 10 / Ubuntu 20.04 WSL

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

Running `amplify push -y` no longer works. The admin UI login page is opened in the browser and displays the following error message:

```
 An error occurred while fetching the app backend: Network Failure
```

There have been constant issues with authentication ever since the admin UI has been developed, integrated, and released.

Any ideas what's going on this time? 

### Expected behavior

The CI command `amplify push -y` should not require login via a browser.

### Reproduction steps

1. Install amplify CLI 5.2.1
2. Run `amplify push -y` and see that issues occur when trying to login.

**Comment by kylekirkby** [comment]
Looks like it could be a CORS issue?

![cors-aws-amplify](https://user-images.githubusercontent.com/4564433/127861932-3cbeeee2-cee0-482c-9fa4-7d4e1a856d08.PNG)

**Comment by kylekirkby** [comment]
The solution, for me at least, was to remove the Amplify Admin UI. 

1. Disable Amplify Admin UI in the AWS management console.
2. Run `amplify configure project` 
3. Selected `Wrapped` profile name. 

`~/.aws/config`
```
[profile ResourcesHubUser]
sso_start_url=https://xxxxxxxx.awsapps.com/start
sso_region=us-east-1
sso_account_id=xxxxxxxxxxxx
sso_role_name=PowerUserAccess
region=us-east-1
output=json

[profile Wrapped]
credential_process = aws2-wrap --process --profile ResourcesHubUser
region = us-east-1
```

We are using AWS SSO so I need to use a little python script `aws2-wrap` to get SSO auth working.

https://github.com/linaro-its/aws2-wrap

4. Run `aws sso login --profile ResourcesHubUser`
5. Run `amplify push -y`

**Comment by johnpc** [comment]
I am glad that you've found a workaround! I am unable to reproduce any cors or network issue associated with the admin ui credential handshake. 

If you can provide more detailed repeatable steps so that I can reproduce I'd be happy to look into it further

**Comment by jhockett** [comment]
Hi @kylekirkby, closing this issue due to lack of response. Please comment below if you run into this again.
