### ISSUE TITLE
Support for Lex v2

### ISSUE THREAD

**Issue by gino8080** [aws-amplify/amplify-cli#7862]
### Is this related to a new or existing Amplify category?

interactions

### Is this related to another service?

Lex

### Describe the feature you'd like to request

Support for the Lex v2 api
to make usable  components like ChatBot

related issue
https://github.com/aws-amplify/amplify-js/issues/7662

### Describe the solution you'd like

I would like that this simply  works :)

```javascript
import { ChatBot, AmplifyTheme } from 'aws-amplify-react'

   <ChatBot
          title="My Bot lex2"
          botName="MyLexV2Bot"
        />
```

### Describe alternatives you've considered

nothing

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jhockett** [comment]
Closing this issue as a duplicate. This feature request is more appropriately tracked by aws-amplify/amplify-js#7662.
