### ISSUE TITLE
getting API: s3:SetBucketEncryption Access Denied after upgrading

### ISSUE THREAD

**Issue by ShehryarKh** [aws-amplify/amplify-cli#7869]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.8.0

### Amplify CLI Version

5.2.1

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

push

### Describe the bug

I've upgrade from v4 to v5.2.1 and I am unable to push new changes. 

```
Resource Name: amplify-website-*** (AWS::S3::Bucket)
Event Type: update
Reason: API: s3:SetBucketEncryption Access Denied
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%***
```

### Expected behavior

for it to made the schema changes and push

### Reproduction steps

amplify push --yes

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
Hi @ShehryarKh, can you make sure `s3:PutEncryptionConfiguration` is added to your IAM role's policy and then try `amplify push --yes`?

**Comment by ShehryarKh** [comment]
@jhockett the IAM role i use to run `amplify push` has S3: full access.

**Comment by ShehryarKh** [comment]
I found out that the role `us-east-1_xxxxxx_Full-access` which I believe was auto generated and is used to make the cloudformation changes was missing.

- s3:GetEncryptionConfiguration
- s3:PutEncryptionConfiguration

Should have been auto updated.
