### ISSUE TITLE
Multi-env: Share the same resource between environments

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-cli#787]
The CLI multienv feature currently has a missing usecase: the ability to use the same resource between environments. The usecase is that I have two frontends: `alpha.myawesomeapp.com` and `beta.myawesomeapp.com`. I want the same user directory but different schemas for my data in alpha and beta.

**Comment by yschoueri** [comment]
Is this something that will be worked on? I have 2 environments but I have dynamodb tables that do not contain environment dependent data and so i find it redundant to create them twice especially since it increases my cost

**Comment by renebrandel** [comment]
Closing this as this is now addressed with the `amplify import auth` / `amplify import storage` workflows.
