### ISSUE TITLE
How to set up or retrieve the mock api graphql endpoint?

### ISSUE THREAD

**Issue by kalote** [aws-amplify/amplify-cli#7880]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Mock [api]

**Amplify CLI Version** 
5.2.1
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**
I've setup amplify in my local machine as follow:
```
amplify init
amplify add api #graphql api
amplify mock api
```
now, i would like to either set (with an env var like mock_api_endpoint=http://0.0.0.0:20001) or retrieve the graphql mocked endpoint so that i can use it in my test suite.

How should i do that?

Note: I haven't `push` or provisionned and created associated resources on AWS yet.

**Comment by cjihrig** [comment]
If your test suite is running `amplify mock api`, you can parse the output for the endpoint:

```
AppSync Mock endpoint is running at http://10.0.0.48:20002
```

If you are running `amplify mock api` externally from your test suite, you'll need to make sure that the correct port is being used on your own. If you're testing functions with mock, the environment variables should be populated with that information in the mocked function already.

**Comment by kalote** [comment]
Thanks for your answer. I'm not using mock function, just the mock api with graphql.
I'm running it externally for my react app, and i don't see any environment variable. 

Is there a way to just run the `mock api`, and retrieve the endpoint information without manually parsing the text output? or even better, being able to set the mock_api_endpoint env vars from a config file to instruct amplify what should be the URL to use?

The architecture of my usage is as follow:

```
react app -> (local) graphql mock -> [mocked db]
react app -> (dev) appSync -> dynamoDB
```

I would like to use the mock api as my local graphql & db environment, for running the test, and for developing. Maybe it's a feature-request if it's not already available?

**Comment by cjihrig** [comment]
There is an existing feature request in https://github.com/aws-amplify/amplify-cli/issues/2235.

**Comment by kaustavghosh06** [comment]
Closing this issue as the question seems to be answered and a corresponding feature request for it is already opened up as a part of #2235.
