### ISSUE TITLE
Hosting with Multiple Frontends - is it possible?

### ISSUE THREAD

**Issue by ChrisSargent** [aws-amplify/amplify-cli#7899]
**Which Category is your question related to?**

Hosting & multiple front ends

**Amplify CLI Version** 

5.2.1

**What AWS Services are you utilizing?**
Hosting, API, Auth (imported from an existing CDK Cognito)

We have a monorepo with one folder for the backend and one folder for the frontend. I have successfully set up all of the backend functionality in the correct folder.

Then, following the instructions to run `amplify pull` from the frontend folder, all seems well. Except, if I run `amplify add hosting` I get the `No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.` error.

FYI, likewise running `amplify status` results in the same error.

Am I doing something wrong, or is hosting for multiple front-ends (as described here: https://docs.amplify.aws/cli/teams/multi-frontend#workflow) not possible?

**Comment by josefaidt** [comment]
Hey @ChrisSargent :wave: when stepping through the prompts for `amplify pull` we have to select "Yes" for "Do you plan on modifying this backend?" in order to add more resources like `hosting`. Are your intentions to host multiple web apps with the same backend resources, all from the same monorepo?

**Comment by ChrisSargent** [comment]
@josefaidt exactly that, yes. Ideally one backend package that has the API and schema etc and one or more front ends using the same api.

**Comment by josefaidt** [comment]
Hey @ChrisSargent thanks for clarifying! Unfortunately this is not currently supported, and there is [an existing feature request with a slightly different workflow](https://github.com/aws-amplify/amplify-cli/issues/2022). I'll mark this as a feature-request and raise it with the team!

**Comment by ChrisSargent** [comment]
Okay. I think we'll probably manage all our front ends with CDK then and just use Amplify for the graphql api.

Rather than this feature request, Id love to see the annotated Schema to resource generation to be available in CDK

**Comment by jhockett** [comment]
Hi @ChrisSargent, we have a recommended monorepo structure that should be helpful for dealing with multiple frontends: https://docs.amplify.aws/cli/usage/monorepo
