### ISSUE TITLE
Creating a blank 'aws-exports.js' with 'amplify init'

### ISSUE THREAD

**Issue by mbahar** [aws-amplify/amplify-cli#79]
**Do you want to request a feature or report a bug?**

Feature

**What is the current behavior?**

`aws-exports.js` file is not available until I run `amplify push` for the first time. So, it is confusing not to find a configuration file after a successful initialization.

**What is the expected behavior?**

With `amplify init`, create an `aws-exports.js` file without any configuration in it.

**Comment by akleiber** [comment]
I was searching around for an `aws-exports.js` file after `amplify init` because it is mentioned in the docs.

> When you run amplify init command you are asked for the details of your project. A configuration file for your app is put in your configured source directory called aws-exports.js.
https://aws-amplify.github.io/amplify-js/media/quick_start#step-4-set-up-your-backend

So either change the docs or change the behaviour like requested here.

**Comment by VetBoard** [comment]
I dont get it, the expected behavior is to get a aws-exports.js EMPTY file after amplify init? I dont even get the file after amplify init event when it creates the roles and bucket

**Comment by kaustavghosh06** [comment]
@VetBoard  The expected behavior is to get an aws_exports.js file after you add a resource and push it.

**Comment by VetBoard** [comment]
Ah ok @kaustavghosh06 perfect. thank you

**Comment by kaustavghosh06** [comment]
Hey guys, witht he latest version of the CLI we generate an aws_exports file on an amplify init.
