### ISSUE TITLE
Default Lamda Execution Policy Can't Use Global Secondary Indexes

### ISSUE THREAD

**Issue by johnford2002** [aws-amplify/amplify-cli#791]
**Describe the bug**
Using the amplify-cli to create a REST API backed by DynamoDB, complete with a global secondary index, results in a Lamda IAM role & policy that can't query the GSI.

**To Reproduce**
1. `amplify init`
2. `amplify add api`
2a. Select REST, select CRUD backed by Dynamo, create new table, specify enough columns for a primary key, sort key, and GSI.
3. `amplify push`
4. Attempt to query GSI either through code or direct API endpoint

**Expected behavior**
The Lamda CloudFormation template should add the Dynamo index(es) to the allowed resource section under the lamda-execution-policy.

**Desktop (please complete the following information):**
 - OS: Mac OS X Sierra
 - Browser: Chrome

**Comment by kaustavghosh06** [comment]
@johnford2002  You're right. If you can submit a quick PR for the same, I could review it and we could ship this in our next release. Thanks!

**Comment by dz0l038** [comment]
Hi @kaustavghosh06, is there a manual workaround to query on a secondary index? I am struggling for a while on this

**Comment by ryross** [comment]
I'm also blocked on this. Any updates?

**Comment by kaustavghosh06** [comment]
We've merged a fix for this. This would be a part of our next npm release.

**Comment by jarrettj** [comment]
Cool @kaustavghosh06. Patiently waiting this side. Any idea of ETA? Thanks.
