### ISSUE TITLE
Lambda layers are deleted with every env checkout

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#7916]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.4.0

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

env

### Describe the bug

With every `amplify env checkout ...` all lambda layers will be deleted. 

For example I switch from dev to staging and I can see the git difference in the `function-parameters.json` the following changes:
**Old**
```json
{
  "permissions": {
    "storage": {
      "Holding:@model(appsync)": ["read"],
      "Transaction:@model(appsync)": ["create", "read", "update", "delete"],
      "Investment:@model(appsync)": ["create", "read", "update", "delete"],
      "Portfolio:@model(appsync)": ["create", "read", "update", "delete"]
    }
  },
  "lambdaLayers": [
    {
      "type": "ExternalLayer",
      "arn": "LAYER_ARN"
    },
    {
      "type": "ExternalLayer",
      "arn": "LAYER_ARN"
    }
  ]
}
```

**New**

```json
{
  "permissions": {
    "storage": {
      "Holding:@model(appsync)": [
        "read"
      ],
      "Transaction:@model(appsync)": [
        "create",
        "read",
        "update",
        "delete"
      ],
      "Investment:@model(appsync)": [
        "create",
        "read",
        "update",
        "delete"
      ],
      "Portfolio:@model(appsync)": [
        "create",
        "read",
        "update",
        "delete"
      ]
    }
  },
  "lambdaLayers": []
}
```

### Expected behavior

No layers are getting changed when switching environments

### Reproduction steps

1. In amplify dev environment
2. Switch to another environment `amplify env checkout staging`
3. Files changed

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @AlessandroVol23 :wave: thanks for raising this! Since this external Lambda Layer ARN is supplied as a static value in `function-parameters.json` this value will be added after a `git merge`. Using the following steps from the docs page for [sandbox environments](https://docs.amplify.aws/cli/teams/sandbox):

```
$ git checkout main
$ amplify env checkout main
$ git merge dev
$ amplify push
$ git push -u origin main
```

The external Lambda Layer ARN value should then be added to your other environment and ready to push!

**Comment by akshbhu** [comment]
Closing due to no response. If the issue is still present , comment on this and ill reopen it again
