### ISSUE TITLE
Creating a sample bot for lex multiple times in an account creates the same bot

### ISSUE THREAD

**Issue by minbi** [aws-amplify/amplify-cli#792]
**Describe the bug**
Creating a sample bot for lex multiple times in an account overrides the same bot. An option is not given during setup to rename the bot.

**To Reproduce**
```
amplify init
amplify add interactions
amplify push
```

**Expected behavior**
The cli should create two bots.

**Comment by renebrandel** [comment]
Hi minbi - Thanks for creating this issue. For now, I'll be closing this issue given that it hasn't gotten much traction. Happy to re-open this issue if more people are passionate about it.
