### ISSUE TITLE
Function Packager: files or folders beginning with a dot(.) do not add to latest-build.zip

### ISSUE THREAD

**Issue by mgarabedian** [aws-amplify/amplify-cli#7926]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.3

### Amplify CLI Version

5.3

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

push

### Describe the bug

When running amplify push, I see that any file or folder that begins with a dot (.) does not get copied to the functions dist/latest-build.zip.  My project utilizes dot folders, and a node module I use also contains a .config file that doesn't get added to the zip, resulting in Lambda Erroring when called.

### Expected behavior

Any file in the src directory gets added to the latest-build.zip

### Reproduction steps

- Add a .test file to a function
- Do amplify push
- Open function's dist/latest-build.zip
- See that the file is not there

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dismantl** [comment]
I also just started seeing this issue, which wasn't happening last week. I am running Amplify CLI version 5.2.1, node.js 16.6.1, on a Mac.

**Comment by josefaidt** [comment]
Hey @mgarabedian and @dismantl :wave: thanks for raising this! I was able to reproduce this on the latest version of the CLI and confirmed if I downgraded the CLI to an older version (pre 5.0.0, I used 4.52.0 in my reproduction) it was zipping the dotfiles. Marking this as a bug

**Comment by mgarabedian** [comment]
No problem. Any idea when this will be fixed? I cannot deploy certain Lambda functions now, and am stuck here. Thanks
