### ISSUE TITLE
«Template error: instance of Fn::GetAtt references undefined resource» when attempting to push auth plugin

### ISSUE THREAD

**Issue by StanMiletskiy** [aws-amplify/amplify-cli#7939]
Hello guys. I need to set up and use Amplify for one of iOS projects I've been handed, I have been trying to apply different approaches setting up Amplify, using different AWS guides, but all the paths lead to the exact same issue I am facing - when I try to push Auth plugin, using `amplify push` I get the error:

Template error: instance of Fn::GetAtt references undefined resource authalphacoachbot

I think that the solution is quite simple, but I'm stuck, so you help is much appreciated.

I'm using amplify init --app https://github.com/ssaid-df/alpha-ios-upwork-stan.git and I don't have any direct access to AWS implementation, just a source code of the app which uses it.

**Amplify version 5.3.0**

**Comment by josefaidt** [comment]
Hey @StanMiletskiy :wave: would you mind porting this over to our [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)? This will help gather additional context about the issue. Also, may you confirm you have permissions to access the repo?

**Comment by StanMiletskiy** [comment]
@josefaidt hey! done: https://github.com/aws-amplify/amplify-cli/issues/7941
yes, I do have permissions to access the repo.

**Comment by josefaidt** [comment]
Thank you @StanMiletskiy ! I'll close this issue in favor of tracking the mentioned issue 😄
