### ISSUE TITLE
Removing `@searchable` transform directive fails to update stack

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#794]
**Describe the bug**
Removing `@searchable` transform directive fails to update stack

**To Reproduce**
1. while locally, create a schema:
```
type MyTestType @model @searchable {
    id: ID!
    content: String!
}
```
2. run `amplify push`
3. remove @searchable directive:
```
type MyTestType @model @searchable {
    id: ID!
    content: String!
}
```
4. run again `amplify push`
5. See error
```
UPDATE_FAILED               myApiName              AWS::CloudFormation::Stack Wed Jan 30 2019 21:22:15  Parameters: [ElasticSearchStreamingLambdaCodeS3Bucket, ElasticSearchStreamingLambdaCodeS3Key] do not exist in the template
```

```
✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
```
**Expected behavior**
The Elasticsearch cluster as well as the trigger to be removed

**Desktop (please complete the following information):**
 - macOS
 - cli version: `0.2.1-multienv.39`

**Comment by kaustavghosh06** [comment]
@sakhmedbayev For the time being you can remove the Elasticsearch parameters from the amplify/bakend/api<resource>/parameters.json file as a workaround while we fix this bug.

**Comment by wbroek** [comment]
Got the same problem with latest aws-amplify/cli@0.2.1-multienv.42.
Removed the `ElasticSearchStreamingLambdaCodeS3Key` and `ElasticSearchStreamingLambdaCodeS3Bucket` from the parameters.json BUT they got re-added again of you do a push so removed them when the cli asks to generate the graphql code.

**Comment by YikSanChan** [comment]
amplify version 1.1.3. I believe the issue has already been solved based on what I just tried.

**Comment by kaustavghosh06** [comment]
Just checked again and this issue seems to be reoslved with the latest CLI version. Plese feel free to re-open this issue if you're still facing the problem.
