### ISSUE TITLE
amplify push error

### ISSUE THREAD

**Issue by AjayBains** [aws-amplify/amplify-cli#7940]
when trying

amplify push
i am getting the error 

 There was an error pulling the backend environment dev.
An error occurred during the push operation: Stack with id amplify-amplifyreactappnew-dev-141312 does not exist

i dont understand what is happening,can someone help?

**Comment by josefaidt** [comment]
Hey @AjayBains :wave: would you mind porting this over to our [bug report template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) in order to gather additional context about the environment?

**Comment by akshbhu** [comment]
Closing this issue as no information provided. Please fill the issue template
