### ISSUE TITLE
Add AWS_LAMBDA authorization mode support for AppSync

### ISSUE THREAD

**Issue by michaelbrewer** [aws-amplify/amplify-cli#7963]
### Is this related to a new or existing Amplify category?

api

### Is this related to another service?

AppSync

### Describe the feature you'd like to request

Allow for setting up your lambda authorizer via the Amplify CLI.

### Describe the solution you'd like

Amplify CLI should setup Appsync (which does have CFN support for setting up the lambda authorizer)

### Describe alternatives you've considered

Manually updating the AppSync authorization manually. 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by SwaySway** [comment]
Hi @michaelbrewer 
We are currently planning on including this in the next version of the transformer, can't specify a date yet. Marking this issue as tracking in v2, our team will provide an update on this thread regarding this feature.

RFC: https://github.com/aws-amplify/amplify-cli/issues/6217

**Comment by MontoyaAndres** [comment]
Any news about this? It's very important for Saas applications...

**Comment by mkaya95** [comment]
I hope it will be solved soon.
Best Regards,

**Comment by renebrandel** [comment]
https://docs.amplify.aws/cli/graphql/authorization-rules/#custom-authorization-rule just launched! @-mention me here if there's anything else to this. Otherwise I'll close the issue for now.
