### ISSUE TITLE
Creating Function with access to another services

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-cli#7970]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.15.1

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

storage, function, api

### Amplify Commands

add

### Describe the bug

I'm trying to create a new function with access to another services as Storage, API or Another functions, so when I tried to give the access through the console I got the error.
![image](https://user-images.githubusercontent.com/1834808/129626320-d9f074a2-2833-46d0-a51e-f1590b2812b3.png)

### Expected behavior

I expected that function must have access to the another services.

### Reproduction steps

![image](https://user-images.githubusercontent.com/1834808/129626375-7bf93712-095b-4f2c-b08d-13d8fcbfcd92.png)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @djom202 :wave: thanks for filing this! Are you also seeing this issue with other services as well? I was able to reproduce when trying to grant access to another function, but not with Storage or API.

**Comment by djom202** [comment]
@josefaidt I tried with function, storage and api in the same tried, but not individually.

**Comment by djom202** [comment]
I just to tried and looks like the issue is related to the another functions
