### ISSUE TITLE
Query Limit takes effect before filter

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-cli#7975]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

5.3.0

### What operating system are you using?

mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Following graphql query

```graphql
{
 l0: listPremiums {
      items {
        id
        inviteCode
      }
    }
  l1: listPremiums(filter: { inviteCode: { eq: "m5e349vu" } }) {
      items {
        id
        inviteCode
      }
    }
  
  l2: listPremiums(limit: 1, filter: { inviteCode: { eq: "m5e349vu" } }) {
      items {
        id
        inviteCode
      }
    }
   }
```

result
```json
{
  "data": {
    "l0": {
      "items": [
        {
          "id": "e8f368da-75fe-48b1-b268-25cfcb4098a0",
          "inviteCode": "zi1bau02"
        },
        {
          "id": "4b7e3d2f-a48d-45bc-b9f7-16460f6e15cc",
          "inviteCode": "m5e349vu"
        },
        {
          "id": "5665d2d1-3da7-44d7-8b09-38f8d31315cf",
          "inviteCode": "b25nztdi"
        }
      ]
    },
    "l1": {
      "items": [
        {
          "id": "4b7e3d2f-a48d-45bc-b9f7-16460f6e15cc",
          "inviteCode": "m5e349vu"
        }
      ]
    },
    "l2": {
      "items": []
    }
  }
}
```

### Expected behavior

l2 to have 1 item

```json
{
  "data": {
    "l0": {
      "items": [
        {
          "id": "e8f368da-75fe-48b1-b268-25cfcb4098a0",
          "inviteCode": "zi1bau02"
        },
        {
          "id": "4b7e3d2f-a48d-45bc-b9f7-16460f6e15cc",
          "inviteCode": "m5e349vu"
        },
        {
          "id": "5665d2d1-3da7-44d7-8b09-38f8d31315cf",
          "inviteCode": "b25nztdi"
        }
      ]
    },
    "l1": {
      "items": [
        {
          "id": "4b7e3d2f-a48d-45bc-b9f7-16460f6e15cc",
          "inviteCode": "m5e349vu"
        }
      ]
    },
    "l2": {
      "items": [
        {
          "id": "4b7e3d2f-a48d-45bc-b9f7-16460f6e15cc",
          "inviteCode": "m5e349vu"
        }
      ]
    }
  }
}
```

### Reproduction steps

1. create 3 item
2. send query with filter of 2nd or 3rd item with limit 1
2. check result

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
Hi @matart15 this is expected behavior. It comes from the fact that in a DynamoDB query, DynamoDB will process a max of "limit" number of items. This limit is counted toward before the filter expression is evaluated. https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-Limit

**Comment by matart15** [comment]
@edwardfoyle thank you. i will look into dynamodb details. 

just to confirm my understanding, there is no way to implement pagination with search using dynamodb?

**Comment by edwardfoyle** [comment]
@matart15 DynamoDB pagination is more of an "infinite scroll" pagination thane an "n results at a time" pagination. However, you could implement this with the query you have above and continue requesting data either until the nextToken comes back null, or you have populated a full page of results. Then to load the next page, start the query with the last received nextToken. The only thing this solution is lacking is jumping to a specific page of results without loading the intermediate pages. To support a use case like that, checkout out the [@searchable directive](https://docs.amplify.aws/cli/graphql-transformer/searchable/) which is backed by [AWS CloudSearch](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/paginating-results.html)

**Comment by matart15** [comment]
@edwardfoyle  thank you. 
Closing the issue
