### ISSUE TITLE
How toe edit `amplify/.config/project-config.json` file 

### ISSUE THREAD

**Issue by Kizi061** [aws-amplify/amplify-cli#7985]
The amplify/.config/project-config.json should me like below

```json
{
  "providers": [
    "awscloudformation"
  ],
  "projectName": "testproject",
  "version": "3.1",
  "frontend": "javascript",
  "javascript": {
    "framework": "react",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "dist",
      "BuildCommand": "npm.cmd run-script build",
      "StartCommand": "npm.cmd run-script start"
    }
  }
}
```

I am having   "DistributionDir": "build",

How can I change it?

**Comment by josefaidt** [comment]
Hey @Kizi061 :wave: this information can be updated when running `amplify configure project` and selecting "Project information" when asked which setting you want to configure. For more information about this command and how it's used please refer to this [documentation page](https://docs.amplify.aws/cli/start/workflows/#amplify-configure-project).
