### ISSUE TITLE
allow cognito authenticated users to publicly access s3 objects without x-amz-security token

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#7994]
**Which Category is your question related to?**
This question is related to the s3 bucket and allowing authenticated users to access the bucket files without needing any token or `x-Amz-Signature` without expiry.
So I have a specific use case, in which I want cognito pool users (authenticated from google) to access bucket objects publicly and they should not need any token to use or render the files in the app.

Here is more explanation which I posted on the Discord AWS Amplify channel.

```
1. I have an s3 bucket and it's private now, which means all public access is blocked. 
2. I have created an identity pool for my Cognito user pool, and allowed it to read, write and list all the bucket objects.
3. now every time, if I try to access an image from the s3 bucket, I need x-amz-security or signature token and the URL is only valid for 7 days. 
4. In my case I want authenticated users to access s3 bucket objects without any x-amz-signature or security token, because if my users are uploading 100 images daily in s3 then I need a lambda function to have an eye in the table to update the URL with a valid token.
more on this from #cli-help :
actually, when I am uploading the image to the s3 bucket file name results in a key, which usually we need to fetch the URL with a token, which contains the x-Amz-Signature or security token. Now the issue is, I am maintaining these links in the dynamodb table. Now
1. If we store the image with a token, it expires after a period of time [for 7 days].
2. If we only store the image key, then at the front-end we need to make another call to get the security token, then only we can render the image.
3. I don't want to fetch x-Amz-signature or security token, because it costs a get request, in my case if the user is authenticated with google (users will be in cognito user pool) then we should not need these tokens anymore, it should allow authenticated users to access the image directly (basically with the URL(https://<bucketName>/path/key) only)
```

**What AWS Services are you utilizing?**
Cognito user pool
S3 Bucket
Amplify 

**Provide additional details e.g. code snippets**
This is the policy I have written but it is not working for my use case if all public access is turned off.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": {
                "Federated": "accounts.google.com"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::<bucketname>-staging"
        },
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::<bucketname>-staging/*"
        }
    ]
}
```
I have also tried this policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::<bucketName>"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::<bucketName>/*"
        }
    ]
}
```
but these policies are restricting authenticated users from accessing the objects from s3.

And if I turn off all block public access checks then I can access the files from anywhere (unauthenticated). 
Please help me to solve this specific use case.

**Comment by fkunecke** [comment]
I am not sure if this will help you, but this is my solution related to this.

Instead of getting the url on the client side, I get the signed URL from a lambda. This allows me to control who accesses some files, which may be of use to you in the future. Here's a basic working example:

```
const signedUrlExpireSeconds = 60 * 5;

async function asyncGetSignedUrl(params) {
  return new Promise((resolve, reject) => {
    try {
      const result = s3.getSignedUrl('getObject', params);
      resolve(result);
    } catch (e) {
      reject(e);
    }
  })
}

app.get('/fetch-item', async (req, res) => {
  const { key } = req.query;

  const url = await asyncGetSignedUrl({
    Bucket: process.env.STORAGE_PUBLIC_BUCKETNAME,
    Key: `${key}`,
    Expires: signedUrlExpireSeconds,
  });
  // redirect to the signed asset url
  return res.redirect(url);
});

```

When using it on the frontend, I can call it straight from an `img` tag:

```
import awsconfig from '../../aws-exports';

const restApiUrl = (apiName) => awsconfig.aws_cloud_logic_custom.find((i) => i.name === apiName);

export const getSignedUrlFromS3Object = file => {
  return `${restApiUrl('API_NAME').endpoint}/fetch-item?key=${encodeURIComponent(file.key)}`;
}

...

<img className='profile-pic' src={getSignedUrlFromS3Object(profile.photo)} />
```

```
type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type Profile @model {
  photo: S3Object
}
```

**Comment by josefaidt** [comment]
Hey @hackrx apologies for the delay! And I appreciate the detailed steps! Could a potential solution be adding a policy to [restrict s3 access by the `referer` header](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html#example-bucket-policies-use-case-4) or by [enabling CORS on the bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html#how-do-i-enable-cors)?

**Comment by josefaidt** [comment]
Hey @hackrx just wanted to follow-up to my previous message. Were you able to find a suitable solution using the links provided above?

**Comment by hackrx** [comment]
Yes @josefaidt, I found that calling getURL is the good solution for me, amd thanks to Dillion ehi helped me find that it is a local call to a function which just appends the token to the key. Although referer header and enabling the CORS was not the solution for me, because as I was calling api as Amplify.{func}.
Thanks for the follow-up.
