### ISSUE TITLE
Amplify won't delete bot in AWS but locally

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#7996]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.4.0

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

interactions

### Amplify Commands

delete

### Describe the bug

If I remove an interaction bot locally it won't be removed in AWS.

### Expected behavior

It should be removed locally and in AWS.

### Reproduction steps

1. `amplify add interaction`
2. Add bot
3. `amplify push --yes`
4. `amplify remove interaction`
5. `amplify push --yes`

Expected: Bot gone
Reality: Bot available

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @AlessandroVol23 :wave: thanks for filing this! I was able to reproduce with the steps provided, marking this as a bug 🙂

**Comment by attilah** [comment]
Upon further investigation it seems that the Delete handler is missing in the Lambda Callout we are provisioning for the resource.

**Comment by josefaidt** [comment]
Closing as issue is now fixed. Confirmed working with current latest version of the CLI - 7.6.23
