### ISSUE TITLE
Authenticator Email Only Signup fails

### ISSUE THREAD

**Issue by awhig** [aws-amplify/amplify-cli#7998]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.3.0

### What operating system are you using?

mac

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

When I try and create a new account, using my email address, I get the following message.

**Username cannot be of email format, since user pool is configured for email alias**

I did notice that the new pool has "Username" selected under the user pool attributes. I believe it should be "Email address or phone number".

I believe there are related bugs filed #7833, but they were using a custom flow and not the hosted/built in widget. Most likely the same root issue, so I thought I'd file a separate bug. Please mark duplicate if they are in fact the same issue. 

### Expected behavior

Allow email address to be used as the login instead of a username.

### Reproduction steps

I deleted my old auth setup/userpools which was set up for username login.

I added a new auth setup which uses email login. I followed the steps found here:

https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/#ui-components

I use the built in authenticator widget in my app.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @awhig :wave: thanks for raising this! The change to use username alias attributes was recent, and the issue you are experiencing does appear to be related to the mentioned issue. Labelling this as a duplicate auth bug and closing in favor of tracking #7833. Please subscribe to the mentioned issue for updates 🙂 and we will work with the folks maintaining the components to find a suitable solution.
