### ISSUE TITLE
Build Failing Randomly Due to Package Locking (Works on Rebuild)

### ISSUE THREAD

**Issue by eric-zhu-uw** [aws-amplify/amplify-cli#8003]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

4.50.0

### What operating system are you using?

Windows

### Amplify Categories

hosting

### Amplify Commands

push, Not applicable

### Describe the bug

Occasionally when I push my code, the build will start and it will run smoothly and deploy. However, on occassion the build will run and time out/fail when it's trying to lock all the packages for my Amplify Functions.

I have included the logs I get on an example failed build:
[logs_for_amplify_issue.txt](https://github.com/aws-amplify/amplify-cli/files/7026619/logs_for_amplify_issue.txt)

I believe this is an issue because I will rebuild without changing any code and it will lock properly and pass. Therefore I believe there is some non-determinsitic process in the build that may be causing it to fail sometimes.

### Expected behavior

I expected the build to pass on the first try and not require a couple of rebuilds for it to successfully build.

### Reproduction steps

The bug is hard to reproduce since it fails non-deterministically. I can provide logs for failed builds but I can't reproduce it in a consistent manner.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment]
This seems to be a local issue either to your Python installation or Windows antivirus configuration as the CLI is only invoking `pip install`. Try to run the same command but exclude that given folder in your antivirus/Windows defender configuration.

also manually create the virualenv and do a pip install in the function's folder to see if that would succeed.

**Comment by eric-zhu-uw** [comment]
This issue only occurs when I deploy to amplify. Whenever I build locally to mock the function or run pip install, there are no issues. Not sure if you have access to my AWS logs and view the build results in more detail...

**Comment by kaustavghosh06** [comment]
Closing based on last response and no further communication or related issues tied to this. Please let us know if you're still stuck on this issue.
