### ISSUE TITLE
Amplify pull: Failed to get profile: Profile configuration is missing for: undefined

### ISSUE THREAD

**Issue by davejab** [aws-amplify/amplify-cli#8006]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.7.0

### Amplify CLI Version

5.3.0

### What operating system are you using?

Arch Linux

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

When pulling back-end from and Amplify project with Admin UI enabled an attempt to set up profile is made despite having successfully received Amplify Admin tokens. This results in an error retrieving the profile. This only happens when specifying `--appId` & `--envName` flags.

### Expected behavior

When pulling back-end, either Amplify Admin tokens should suffice for authentication or user can successfully configure profile.

### Reproduction steps

1. Initialize Amplify back-end & push to AWS
2. Enable Admin UI via AWS Console
3. Add, commit and push Amplify project to Git repository
3. Delete project from local storage
4. Checkout Git repository
5. run: amplify pull --appId xxxxxxxxxxxxx --envName yyy
```
Opening link: https://REGION.admin.amplifyapp.com/admin/xxxxxxxxxxxxx/yyy/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: xxxxxxxxxxxxx. Amplify App name is: projectname
Backend environment yyy found in Amplify Console app: projectname
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? Yes
⠼ Fetching updates to backend environment: dev from the cloud.? Select the authentication method you want to use: (Use arrow ke? Select the authentication method you want to use: AWS profile
Failed to get profile: Profile configuration is missing for: undefined
⠹ Fetching updates to backend environment: dev from the cloud.%
```

### Log output

<details>

```
# Put your logs below this line
2021-08-22T11:40:27.413Z|info : amplify pull core  {"appId":"[***]xxxxxx","envName":"[***]yy","yes":false}
2021-08-22T11:40:27.446Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
2021-08-22T11:40:37.942Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2021-08-22T11:40:38.155Z|info : amplify-provider-awscloudformation.attach-backend.getAmplifyApp.amplifyClient.getApp([{"appId":"[***]xxxxxx"}])
2021-08-22T11:40:38.303Z|info : amplify-provider-awscloudformation.attach-backend.getBackendEnv.amplifyClient.getBackendEnvironment([{"appId":"[***]xxxxxx","environmentName":"[***]yy"}])
2021-08-22T11:40:38.447Z|info : amplify-provider-awscloudformation.attach-backend.downloadBackend.s3.getObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]xxxxxxx-[***]yy-[***]30-[***]ment"}])
2021-08-22T11:40:49.166Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig([null])
2021-08-22T11:40:49.168Z|error : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig([null])
Error: Profile configuration is missing for: undefined
```

</details>

### Additional information

This can be worked around by not specifying `--appId` & `--envName` flags when pulling.

**Comment by josefaidt** [comment]
Hey @davejab :wave: thanks for raising this! To clarify, are you executing the `amplify pull...` command in the directory where we have freshly cloned the existing Amplify project from a git repository? If so, can you try running `amplify init` rather than the pull? This should prompt whether you want to use an existing environment and also allow you to choose the preferred authentication method.

**Comment by davejab** [comment]
Hi @josefaidt thanks for your response. Yes I am running `amplify pull...` in the root of the project directory that has been freshly cloned. I have attempted the same steps with `amplify init...` however this results in a mismatch of appId. My intention here is to onboard additional developers to work on the same deployment.

```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything
```

```
$ amplify pull --appId dl20tjmxxxxxx --envName dev
Amplify appId mismatch.
You are currently working in the amplify project with Id d9h116uxxxxxx
```

**Comment by josefaidt** [comment]
Hey @davejab thanks for the info! Are you running `amplify init` and choosing a profile that is different from the original creation? What does the `local-aws-info.json` file look like? 

```
> cat amplify/.config/local-aws-info.json
{
  "dev": {
    "configLevel": "amplifyAdmin"
  }
}
```

When you run `amplify init` and step through the prompts are you able to select `Amplify Admin UI` to authenticate and not create a different app?

**Comment by davejab** [comment]
@josefaidt the profile I am selecting is the same as the one I set up Amplify originally with (although I have renamed it locally)

```local-aws-info.json``` after running ```amplify init```:
```
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}
```

When running ```amplify init``` i do not get the option to select ```Amplify Admin UI```

Interestingly, I can still pull successfully without specifying ```--appId``` & ```--envName``` despite the app id being different:
```
$ amplify pull --appId xxxxxxxxxxxxx --envName dev
Amplify appId mismatch.
You are currently working in the amplify project with Id yyyyyyyyyyyyy

$ grep -r yyyyyyyyyyyyy                                    
amplify/team-provider-info.json:      "AmplifyAppId": "yyyyyyyyyyyyy"
amplify/backend/amplify-meta.json:      "AmplifyAppId": "yyyyyyyyyyyyy"
amplify/#current-cloud-backend/amplify-meta.json:      "AmplifyAppId": "yyyyyyyyyyyyy"

$ amplify pull                                    

Pre-pull status:

Current Environment: dev

| Category | Resource name                       | Operation | Provider plugin   |
| -------- | ----------------------------------- | --------- | ----------------- |
| Auth     | userPoolGroups                      | No Change | awscloudformation |
| Auth     | sheriffofnottinghamaba9b612aba9b612 | No Change | awscloudformation |
| Function | AdminQueries3e965cf1                | No Change | awscloudformation |
| Api      | AdminQueries                        | No Change | awscloudformation |

✔ Successfully pulled backend environment dev from the cloud.

Post-pull status:

Current Environment: dev

| Category | Resource name                       | Operation | Provider plugin   |
| -------- | ----------------------------------- | --------- | ----------------- |
| Auth     | userPoolGroups                      | No Change | awscloudformation |
| Auth     | sheriffofnottinghamaba9b612aba9b612 | No Change | awscloudformation |
| Function | AdminQueries3e965cf1                | No Change | awscloudformation |
| Api      | AdminQueries                        | No Change | awscloudformation |


$ grep -r yyyyyyyyyyyyy
amplify/team-provider-info.json:      "AmplifyAppId": "yyyyyyyyyyyyy"
amplify/backend/amplify-meta.json:      "AmplifyAppId": "yyyyyyyyyyyyy"
amplify/#current-cloud-backend/amplify-meta.json:      "AmplifyAppId": "yyyyyyyyyyyyy"

```

**Comment by josefaidt** [comment]
Hey @davejab just wanted to follow-up 🙂 are you able to reproduce by repeating the same steps in a new project?

**Comment by kaustavghosh06** [comment]
Closing based on last response and no further communication or related issues tied to this. Please let us know if you're still stuck on this issue.
