### ISSUE TITLE
Resolvers for Update-Mutation don't work for RDS Source

### ISSUE THREAD

**Issue by Smorgaz** [aws-amplify/amplify-cli#8008]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

5.3.0

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

Auto generated resolvers for Update Mutation on serverless rds contain a superflous `}` in "statements". This prevents any Update mutations.

### Expected behavior

Auto-Generated resolvers that allow running Update-Mutations.

### Reproduction steps

1. Add Relational Database according to the tutorial https://docs.amplify.aws/cli/graphql-transformer/relational/
2. Find erronous statement in/amplify/backend/api/APIName/resolvers

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @Smorgaz :wave: thanks for raising this! I was able to reproduce by following the tutorial from our docs site, and noticed the mutations were generated as follows:

```
## Mutation.updateCustomers.req.vtl
#set( $updateList = {} )
#foreach( $entry in $ctx.args.updateCustomersInput.keySet() )
  #set( $discard = $updateList.put($entry, "'$ctx.args.updateCustomersInput[$entry]'") )
#end
#set( $update = $updateList.toString().replace("{","").replace("}","") )
{
  "version": "2018-05-29",
  "statements":   ["UPDATE Customers SET $update WHERE id=$ctx.args.updateCustomersInput.id}", "SELECT * FROM Customers WHERE id=$ctx.args.updateCustomersInput.id"]
}
```

After removing the extra curly brace after the ID `WHERE id=$ctx.args.updateCustomersInput.id}`, I was able to update existing customer resources.

**Comment by Smorgaz** [comment]
I also got additional `s`. I assumed the generated Code expects the table names to be singular like it does with the `@model` types for DynamoDB. An other issue that popped up was table names in all lowercase. In the resolvers those names are sometimes Capitalized and sometimes not. If in your example above, you named the table `customers`, the mutation would look something like this:

    {
      "version": "2018-05-29",
      "statements":   ["UPDATE customers SET $update WHERE id=$ctx.args.updateCustomersInput.id}", "SELECT * FROM Customers WHERE id=$ctx.args.updateCustomersInput.id"]
    }
