### ISSUE TITLE
Support for Kinesis Firehose and his destinations

### ISSUE THREAD

**Issue by nathanagez** [aws-amplify/amplify-cli#8018]
### Is this related to a new or existing Amplify category?

analytics

### Is this related to another service?

Athena, S3, AWS Glue, Redshift, Kinesis Data Analytics

### Describe the feature you'd like to request

Currently, the amplify-cli analytics category plugin only supports Pinpoint and Kinesis data streams, then requiring the end user to manually connect the destination services once configured. In my opinion, this configuration limits the use we can have of analytics.

Support for Kinesis (Firehose) delivery streams could significantly improve the user experience of the analytics category plugin and allow users to easily create "custom" analytics through the CLI. 

I think this is a considerable option since there are analytics-based AWS workshops:
- https://streamingvideoanalytics.workshop.aws/
- https://amplify-analytics.workshop.aws/

User request:
- https://github.com/aws-amplify/amplify-cli/issues/2949

### Describe the solution you'd like

As a solution/implementation, we would like to have the ability to add Kinesis (Firehose) delivery streams using `amplify add analytics` and the ability to connect different related services to it.

In order to facilitate the development of this feature, we have produced a diagram summarizing the different permutations possible using Kinesis Firehose (in outline). The idea is to develop something flexible so that end users are not restricted to a single use.
![permutations](https://user-images.githubusercontent.com/7148684/130583748-0bf56545-4a4c-42c0-9338-c1aebc8710d8.jpg)

### Describe alternatives you've considered

We started implementing the functionality, we have something that works but we wanted to share it with the amplify-cli team so we can make sure we are building something right from the beginning respecting your actual code base and best practices.

<img width="453" alt="cli-1" src="https://user-images.githubusercontent.com/7148684/130584365-3e772345-9e3f-402a-b649-fff70adfa4ab.png">
<img width="598" alt="cli-2" src="https://user-images.githubusercontent.com/7148684/130584368-46a6e24f-57b0-4e3c-8095-b1837b5908ae.png">
<img width="688" alt="status" src="https://user-images.githubusercontent.com/7148684/130585867-2835f359-0378-4b57-8a47-10322654c662.png">

![console](https://user-images.githubusercontent.com/7148684/130585474-2119374f-fec8-4d93-8ef6-7b4f5de14d67.png)

### Additional context
This feature will also help us in the development of a JavaScript client library (analytics part) for amplify-video category plugin.
https://docs.google.com/document/d/16TJYom-VNTGnMOq-9ebaIYbL-QFandrC2SlpQ1kmOe4/edit?usp=sharing

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by attilah** [comment]
@nathanagez thanks for letting us know, it looks useful at first sight, assigning our PM @renebrandel to make him aware!

**Comment by nathanagez** [comment]
Since we can now create resources using the AWS CDK I can close this issue.
