### ISSUE TITLE
@Zanndorin @xavierraffin Are you still facing this problem?

### ISSUE THREAD

**Issue by flutteresbolivia** [aws-amplify/amplify-cli#8023]
@Zanndorin @xavierraffin Are you still facing this problem?

_Originally posted by @ammarkarachi in https://github.com/aws-amplify/amplify-cli/issues/4952#issuecomment-803171617_

i have this problem!

**Comment by attilah** [comment]
@flutteresbolivia closing the issue as the referenced issue is already fixed since, if it still persist with latest CLI open a bug report with the new issue template to be able to help you.
