### ISSUE TITLE
Support for Lex V2: Chatbots are not available in new console 

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#8024]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.4.0

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

interactions

### Amplify Commands

add

### Describe the bug

Chatbots I have created with amplify are available in the lex console but they are not available in the new lex V2 console.

### Expected behavior

Chatbot in lex v1:
![image](https://user-images.githubusercontent.com/19362086/130655030-03bae9c7-f1af-45c7-a962-9494d6fe747c.png)

Lex v2 (clicked on start building):

![image](https://user-images.githubusercontent.com/19362086/130655088-38a6f010-9404-4d39-8311-83d6807a8634.png)

Not sure if it is hidden somewhere. 

### Reproduction steps

1. `amplify add interactions`
2. Add sample chatbot
3. Go to lex

**Comment by attilah** [comment]
Based on the announcement this is by design by Lex: https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-lex-announces-tooling-to-migrate-bots-from-lex-v1-console-to-lex-v2-console/

Amplify CLI does not support Lex V2 which is a full set of new APIs not just a new Console it seems.

I mark it as a feature request.

**Comment by AlessandroVol23** [comment]
Ah, sorry I thought it is just a new console. Thank you!

**Comment by ykethan** [comment]
Support for Lex v2 has been implemented in the interactions category. Please refer to https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js/#lex-v2-bot for additional information.
