### ISSUE TITLE
Clarify timezone for Lambda recurring schedule

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#8027]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
function

**Amplify CLI Version** 
5.3.0 

**What AWS Services are you utilizing?**
Lambda

**Provide additional details e.g. code snippets**

When I setup a lambda on recurring schedule, the default time amplify cli suggest is current time on my local machine. So I assume then I am setting the lambda's schedule based on my timezone and amplify cli will convert to UTC. For example I set my lambda to run 7:11am MST each day. But then checking the deployed lambda I see the time is not converted to UTC: cron(11 7 * * ? *). 

Amplify CLI should be super clear what timezone I'm inputting the time in. It seems to imply it's my timezone because it picked the current time, but turns out it's current time in UTC which is not my current local time.

**Comment by attilah** [comment]
@hisham thanks for the heads up I mark it as a bug because it is an easy DX change in the prompts, the time given is in UTC as you also figured since that's how Lambda works: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents-expressions.html
