### ISSUE TITLE
Headless push without compiling schema

### ISSUE THREAD

**Issue by sceptyk** [aws-amplify/amplify-cli#806]
** Which Category is your question related to? **
api

** What AWS Services are you utilizing? **
appsync

** Provide additional details e.g. code snippets **
Background: I have set up auth/guest api with amplify and so appsync is configured to AWS_IAM and therefore I cannot use @auth directly.  To solve that I forked the amplify-cli and updated transformer to use $ctx.identity.username instead of claims. I can run it in dev mode locally all right and compile the resolvers. I have also continuous integration and deployment set up with circle ci so I run headless script to publish to staging/prod environment. 
Problem: I install @aws-amplify/cli@multienv when running in circleci so my changes are obviously not there and when I init amplify environment after checkout it recompiles the resolvers. I was wondering if there is a flag or setting I could pass to avoid this? Or maybe a better way of handling this scenario?

My deploy script:
```
#!/bin/bash
set -e
IFS='|'

AMPLIFY="{\
\"envName\":\"$1\"\
}"

AWSCLOUDFORMATION="{\
\"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
\"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
\"region\":\"eu-central-1\"\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATION\
}"

amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes

amplify publish \
--yes
```

I would appreciate any suggestions.

**Comment by yuth** [comment]
@sceptyk Amplify has `--no-gql-override` option which will prevent overwritting the resolvers. Could you try running publish with `--no-gql-override` option. Your publish command should look like this:
```bash
amplify publish \
--yes --no-gql-override
```

Please re-open the issue if this doesn't solve the issue

**Comment by sceptyk** [comment]
@yuth Hey, thanks for the answer. I ended up running my amplify-cli version in integration process as well.

I tried the flag before (sorry to not include this information in the question). As I understand --no-gql-override would not override resolvers on the server side not during generation. The idea of changing resolvers manually on aws side seems not feasible when there are few environments to update each time.

**Comment by yuth** [comment]
`--no-gql-override` forces CLI not to update the resolves in `amplify/backend/api/<api-name>/build` folder. So if you're using a version control system, and you have the api build folder committed to the branch, it should update the revolvers.

**Comment by sceptyk** [comment]
@yuth So I tried that again to see if I didn't mess up something before. It appears like the overriding is done after init is called and therefore the flag in publish does not matter anymore because the resolvers are already changed. Is this expected behavior?

**Comment by yuth** [comment]
@sceptyk It looks like we the CFN gets rerun for some reason. I am going to digg a bit deeper.

We are actively testing custom resolvers for graphql transform (https://github.com/aws-amplify/amplify-cli/pull/581). Once its merged you won't have to do go and update the resolvers in AWS console
