### ISSUE TITLE
Every response in AdminQueries api requests are 500 (Error)

### ISSUE THREAD

**Issue by hrqmonteiro** [aws-amplify/amplify-cli#8066]
**Which Category is your question related to?**

Authentication, AdminQueries

**Amplify CLI Version** 

5.3.0

**What AWS Services are you utilizing?**

Amplify, Cognito, Lambda

**Provide additional details e.g. code snippets**

I am trying to follow what i saw [here](https://aws.amazon.com/pt/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/), [here](https://docs.amplify.aws/cli/auth/admin/#example) and [here](https://dev.classmethod.jp/articles/amplify-admin-queries-api-custom/), just for the sake of examples. 

That is, i have a Cognito user pool, and an AdminQueries API all set-up.
And i want to have React components that reads this groups and update it (with GET and POST).

But, i follow these tutorials and every response i get is 500 (Error).

One example:

I have a cognito user pool with a group called `Admin`, and as i try to read it like this:

```
import Amplify, { Auth, API } from 'aws-amplify';

let nextToken;

async function listAdmins(limit){
  let apiName = 'AdminQueries';
  let path = '/listUsersInGroup';
  let myInit = { 
      queryStringParameters: {
        "groupname": "Admin",
        "limit": limit,
        "token": nextToken
      },
      headers: {
        'Content-Type' : 'application/json',
        Authorization: `${(await Auth.currentSession()).getAccessToken().getJwtToken()}`
      }
  }
  const { NextToken, ...rest } =  await API.get(apiName, path, myInit);
  nextToken = NextToken;
  return rest;
}

export default function App() {
  return (
    <div className="App">
      <button onClick={() => listEditors(10)}>List Editors</button>
    </div>
  );
}

```

I get a 500 Error.

Same thing if i try with `listUsers`, `addUserToGroup` or any other one. It just won't work.

**Comment by RoniqueRicketts** [comment]
Try removing the Authorization header and see if it works.

**Comment by hrqmonteiro** [comment]
> Try removing the Authorization header and see if it works.

It doesn't.

Since in the API Gateway configuration, the API Key Origin is set to Headers.

![tehhs](https://user-images.githubusercontent.com/17055027/131552146-d1652770-4db3-4973-a1fd-24e5c255e4ec.png)
(I couldn't set this to english, actually i'm trying to do so in months, but anyway, i think you can understand it)

**Comment by hrqmonteiro** [comment]
UPDATE: here in english:

![tehhs](https://user-images.githubusercontent.com/17055027/131552576-79933d32-5f36-4366-a15c-d95008da4d7d.png)

**Comment by cjihrig** [comment]
@hrqmonteiro are you able to identify any additional information about the error beyond the 500 status code?

**Comment by josefaidt** [comment]
Hey @hrqmonteiro just wanted to follow-up on this and see if you were able to identify any additional information. Based on the screenshot it appears it is looking for the `x-api-key` header
