### ISSUE TITLE
How to filter an array property when making graphl query

### ISSUE THREAD

**Issue by irakli-g** [aws-amplify/amplify-cli#8076]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
GraphQL queries

**Amplify CLI Version** 
5.3.0
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
S3, DynamoDB, Cognito, AppSync, Amplify

**Provide additional details e.g. code snippets**
This is a post entity from my graphql schema
<img width="746" alt="Screenshot 2021-09-01 at 12 44 29" src="https://user-images.githubusercontent.com/70649220/131640981-0a3745da-c597-44bd-a977-56d890ff616d.png">

Post contains property "favorited" which will be an array of user ids (id when you get upon registration);

Upon creation of a post "favorited" is an empty array but if someone marks a post as his/her favorite, post's "favorited" array will be updated and user's ID will be added on top of the existing list of IDs (if any);

Let's say app has 100 posts from different users and I added to my favorites only 5 posts.

If I want to only see posts that I marked as my favorite, how will I be able to query them? Can I list posts where "favorited" array contains my ID?

Is something like this possible?
let filter = {
    favorited: {
       contains: "my ID"
    }
};

await API.graphql({ query: listPosts, variables: { filter: filter}}));

**Comment by danielleadams** [comment]
Hi @irakli-g, it's not possible to use `contains` on an array list, but have you looked at using the `@searchable` directive? This may solve the use case you are trying to address. (Docs: https://docs.amplify.aws/cli/graphql-transformer/searchable/#usage)

**Comment by irakli-g** [comment]
Hi @danielleadams, thanks for suggestion.

I've checked it. It's a fancy feature but I am not sure how useful it can be for my case. I assume creating many to many relationship in my schema would do the trick.

It's mentioned in this tutorial starting from 20:00. I will test this case.
[https://www.youtube.com/watch?v=eUQvsuO6EnU&list=WL&index=4&ab_channel=EnlearAcademy](url)

**Comment by danielleadams** [comment]
I think creating a many-to-many relationship would help too. I talked more with team members, and it looks like using `contains` actually does work when querying a GraphQL endpoint too.

**Comment by irakli-g** [comment]
I confirm that using many to many relationship does help to solve this problem.
