### ISSUE TITLE
creating a new trigger for amplify storage when one exists will make push fail

### ISSUE THREAD

**Issue by danielleadams** [aws-amplify/amplify-cli#8087]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.3

### Amplify CLI Version

5.3.1

### What operating system are you using?

Mac

### Amplify Categories

storage, function

### Amplify Commands

add, update

### Describe the bug

When a user attempts to update a trigger with a new Function for a storage resource and then push up changes, the push fails with Resource is not in the state stackUpdateComplete.

If the user tries to remove either function (`amplify function remove`), the user will see `An error occurred when removing the resources from the local directory`.

Therefore, the user cannot push up any changes and is not able to delete either function without deleting the storage resource first.

### Expected behavior

The user should be able to push up resources when storage is updated without issues.

### Reproduction steps

1. `amplify storage add` -> Create trigger (y) -> Create new function
2. `amplify storage update` -> Update trigger -> Create new function
3. `amplify push`

### Log output

<details>

```
➜  ampapp git:(master) ✗ amplify push
...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete

➜  ampapp git:(master) ✗ amplify function remove
? Choose the resource you would want to remove S3Triggerxxx (function)

? Are you sure you want to delete the resource? This action deletes all files related to this resourc
e from the backend directory. Yes
Resource cannot be removed because it has a dependency on another resource
Dependency: S3 - xxx
An error occurred when removing the resources from the local directory
```

</details>

**Comment by sachscode** [comment]
Validated with amplify cli 7.6.x ,  this issue is fixed, cannot repro. Closing the issue.
