### ISSUE TITLE
Amplify Publish fails for manually deployed branch

### ISSUE THREAD

**Issue by dsueltenfuss** [aws-amplify/amplify-cli#8092]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.5

### Amplify CLI Version

5.4.0

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

publish

### Describe the bug

When attempting to publish an amplify environment, the deployment fails with the following message
`You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches.`
The branch in question has always been manually deployed, and was able to be deployed with v5.3.1

### Expected behavior

The branch should deploy successfully

### Reproduction steps

Install amplify-cli 5.4.0
amplify publish

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cespin** [comment]
I'm having exactly the same issue.

In my case I was doing it in the frontend build phase in the pipeline but I can reproduce the issue locally as well.

Since the command wasn't creating the _build_ folder for me the pipeline was breaking, I tried doing a _yarn build_ before the _amplify publish_ but it still doesn't put anything in S3

**Comment by VictorGaiva** [comment]
I'm having the same problem. Was able to isolate the issue to [this function](https://github.com/aws-amplify/amplify-cli/blob/d1b8aa615402e449bac257d6229dd4094a7c731a/packages/amplify-cli/src/utils/check-hosting.ts#L3), which seems to be returning true when it's not supposed to

**Comment by otkrickey** [comment]
I'm having the same issue.
This bug occurred after updating `amplify-cli` to `v5.4.0` via `npm` this morning.
Probably the cause is the difference between `v5.3.1` and `v5.4.0`.

**Comment by otkrickey** [comment]
I found the difference between v5.3.1 and v5.4.0
Maybe this code is related to the error.

https://github.com/aws-amplify/amplify-cli/compare/v5.3.1...v5.4.0#diff-032e045e16fdd4ab054cd0b810d1e7ce2f95a0ef6a58ecae08e50fc44a6c843aL9-R19

**Comment by callumbrieske** [comment]
This bug has affected me too. Rolling back to 5.3.1 resolved the issue for me.

**Comment by otkrickey** [comment]
Yeah, This file is causing error.
https://github.com/aws-amplify/amplify-cli/blob/4f03859c3a7c092c025c3047e1c5fa581a62a05a/packages/amplify-cli/src/utils/check-hosting.ts

**Comment by cjihrig** [comment]
Opend https://github.com/aws-amplify/amplify-cli/pull/8106 with a revert of the changes causing this issue.

**Comment by otkrickey** [comment]
@cjihrig 
Thank you for your great work.

**Comment by chowlett** [comment]
I am still getting "You have already connected branches ..." with "amplify add hosting" after upgrading amplify cli to 5.5.0. That is after removing hosting under 5.4.0 in an attempt to work around the 5.4.0 bug.
