### ISSUE TITLE
Amplify Delete does not remove resources from awsconfiguration

### ISSUE THREAD

**Issue by dmennis** [aws-amplify/amplify-cli#81]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
$ Amplify delete
Actual Result: All the resources deleted in the cloud
Expected Result: All the resources deleted in the cloud and any references to those resources in the awsconfiguration file be removed.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**
1. Init iOS project
2. Enable any feature and push
2. Amplify delete and confirm
After all the resources have been deleted. Open up the awsconfiguration file to see links pointing to resources that have been deleted. If Amplify CLI is updating this file, it should delete those entries when resources are deleted by the Amplify CLI.

**What is the expected behavior?**
For the Amplify CLI to remove any resources linked in the awsconfiguration file pointing to deleted cloud resources.

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)** MacOS 10.13.6
* **Output of ``amplify --version``**: 0.1.15
* **Did this work in previous versions?**: Not sure

**Comment by oxydev** [comment]
Its working perfectly fine.

**Comment by blomm** [comment]
yes, currently amplify delete will delete everything 
even when i run an 'amplify add api' but then choose to discard all my changes, next time i do a 'amplify push' it still wants to create the resource that I discarded (ie didn't save)

**Comment by kaustavghosh06** [comment]
@dmennis The latest version of the CLI removes the awsconfiguration.json and aws_exports.js files. cc @SwaySway @ammarkarachi
