### ISSUE TITLE
Zipping artefacts take more than 12 hours

### ISSUE THREAD

**Issue by AnlyDcouth** [aws-amplify/amplify-cli#8107]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
AWS Amplify publish

**Amplify CLI Version** 
2.6
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

AWS Amplify

**Provide additional details e.g. code snippets**
after 'amplify publish' the system is taking too long(more than 12 hours) to create artefacts. SO far the generated file size is 750GB and its still stating 'zipping artefacts'

**Comment by lazpavel** [comment]
Can you please upgrade to the latest CLI version and try to run the command again. 
If the issue persists with with the newest version, please send us the  logs from `~/.amplify/amplify-logs` at amplify-cli@amazon.com
