### ISSUE TITLE
Elasticsearch with 20Gb is not free tier ...

### ISSUE THREAD

**Issue by canivel** [aws-amplify/amplify-cli#811]
Hi, i suggest to change the default volume size to 10Gb when adding the default ElasticSearch setup from the schema.graphql (@searchable), so it fit on the free tier.

Thank you

**Comment by mikeparisstuff** [comment]
I have included a change that drops the default to 10GB as part of #581

**Comment by kaustavghosh06** [comment]
We've fixed this issue in the latest version of the main CLI. Please install the latest CLI using `npm install -g @aws-amplify/cli`  and let me know (and re-opne the issue) if you're still facing this issue

**Comment by gustavosooeiro** [comment]
I've used the last version by September/2019 and I've ended up paying the 20Gb instance of Elasticsearch. I felt confortable creating the instance because of this post. Is the default Elasticsearch creation set to 20Gb or 10Bg.  How can I create an Elasticsearch instance that fits in the free tier?
