### ISSUE TITLE
Amplify push prompts for all missing environment variables but only considers last one entered

### ISSUE THREAD

**Issue by jennapederson** [aws-amplify/amplify-cli#8111]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn global add @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.18.3

### Amplify CLI Version

5.4.0

### What operating system are you using?

mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I added four environment variables via `amplify function update` in a branch. After testing and merging this branch, I ran into the build issues described in these docs - https://docs.amplify.aws/cli/function/env-vars/#configuring-environment-variables. I followed the steps at the bottom to resolve. In step 2, `amplify push`, it prompts for the four missing environment variable values, however the push fails and the team-provider-info.json file only reflects the last env var value entered. In order to resolve this, I had to run `amplify push` four times to get the values all set properly for the main branch.

### Expected behavior

I expect that when running `amplify push` and the CLI tells me "Some Lambda function environment variables are defined but missing values." and asks for all of the values, that they will be reflected in the team-provider-info.json (and any other required file) and the command will succeed.

### Reproduction steps

1. `amplify init`
2. initialize git repo and push to github
3. connect amplify to github branch main
5. create new branch
6. `amplify add function` (defaults, Node, hello world)
7.  commit, push to github
8. enable PR previews OR connect a branch directly
9. `amplify pull ...` the new backend environment
10. `amplify update function` and add 4 new env vars/values to the function
11. push to github
12. wait for successful backend build for branch
13. merge branch to main
14. note failed backend build and follow steps here to resolve: https://docs.amplify.aws/cli/function/env-vars/#configuring-environment-variables
    `Parameters: [var4, var3, var2, var1] must have values`
15. check out main branch
16. switch to original amplify environment - `amplify env checkout dev`
17. `amplify push`

The last env var is reflected in the team-provider-info.json but not the first three added and the push fails. See partial log output below.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

Partial log output after running `amplify push`

<details>

```
# Put your logs below this line
 ~/tmp/MultiEnvVarsBug   main ±  amplify push

Some Lambda function environment variables are defined but missing values.

? Enter the missing environment variable value of VAR1 in multienvvarsbug1c7b1d9f: var1-value
? Enter the missing environment variable value of VAR2 in multienvvarsbug1c7b1d9f: var2-value
? Enter the missing environment variable value of VAR3 in multienvvarsbug1c7b1d9f: var3-value
? Enter the missing environment variable value of VAR4 in multienvvarsbug1c7b1d9f: var4-value
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev

┌──────────┬─────────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name           │ Operation │ Provider plugin   │
├──────────┼─────────────────────────┼───────────┼───────────────────┤
│ Function │ multienvvarsbug1c7b1d9f │ Create    │ awscloudformation │
└──────────┴─────────────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? Yes
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-multienvvarsbug-dev-204227 AWS::CloudFormation::Stack Mon Sep 06 2021 21:28:02 GMT-0500 (Central Daylight Time) User Initiated
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS functionmultienvvarsbug1c7b1d9f AWS::CloudFormation::Stack Mon Sep 06 2021 21:28:08 GMT-0500 (Central Daylight Time)
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_FAILED               functionmultienvvarsbug1c7b1d9f    AWS::CloudFormation::Stack Mon Sep 06 2021 21:28:09 GMT-0500 (Central Daylight Time) Parameters: [var3, var2, var1] must have values
UPDATE_ROLLBACK_IN_PROGRESS amplify-multienvvarsbug-dev-204227 AWS::CloudFormation::Stack Mon Sep 06 2021 21:28:09 GMT-0500 (Central Daylight Time) The following resource(s) failed to create: [functionmultienvvarsbug1c7b1d9f].
⠦ Updating resources in the cloud. This may take a few minutes...

```

</details>

### Additional information

In order to resolve this, I had to run `amplify push` four times to get the values all set properly for the main branch.

**Comment by josefaidt** [comment]
Note for the team: it does appear these values are captured and populated in the function's `function-parameters.json` file

```json
{
  "lambdaLayers": [],
  "environmentVariableList": [
    {
      "cloudFormationParameterName": "one",
      "environmentVariableName": "one"
    },
    {
      "cloudFormationParameterName": "two",
      "environmentVariableName": "two"
    },
    {
      "cloudFormationParameterName": "three",
      "environmentVariableName": "three"
    }
  ]
}
```

**Comment by jameslporter** [comment]
Any idea of a timeline? Our team is learning amplify fast but this really cripples our flow! Thanks!

**Comment by pnedelko** [comment]
Waiting for the fix 🤞
