### ISSUE TITLE
Whitespace differences (no actual code diff) causes amplify status to show need to update

### ISSUE THREAD

**Issue by IcedNet** [aws-amplify/amplify-cli#8129]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.20.2

### Amplify CLI Version

5.5.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, analytics, notifications

### Amplify Commands

pull, status

### Describe the bug

When `amplify status`is run after initial clone and amplify setup for local dev on a new machine, shows:

    Current Environment: production
    

│ Category      │ Resource name     │ Operation │ Provider plugin   │
│ Auth          │ userPoolGroups    │ Update    │ awscloudformation │
│ Api           │ dev               │ Update    │ awscloudformation │
│ Function      │ notifications     │ Update    │ awscloudformation │
│ Function      │ postConfirmHook   │ Update    │ awscloudformation │
│ Function      │ preSignUpHook     │ Update    │ awscloudformation │
│ Auth          │ app│ No Change │ awscloudformation │
│ Analytics     │ app         │ No Change │ awscloudformation │
│ Notifications │ app         │ No Change │                   │
│ Storage       │ ValidEmails       │ No Change │ awscloudformation │
`

Execute `git status`

`Your branch is up to date with 'origin/production'.`

Execute `amplify pull` then `git status`

Your branch is up to date with 'origin/production'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   amplify/backend/api/dev/parameters.json
	modified:   amplify/backend/auth/userPoolGroups/template.json
	modified:   amplify/backend/function/notifications/notifications-cloudformation-template.json
	modified:   amplify/backend/function/postConfirmHook/postConfirmHook-cloudformation-template.json
	modified:   amplify/backend/function/preSignUpHook/preSignUpHook-cloudformation-template.json
	modified:   amplify/team-provider-info.json`

Diff shows only whitespace differences - namely tabs become 4 sp instead of 2...

### Expected behavior

Ignore whitespace differences - json spec is human readable, no spacing spec'd, yes?

### Reproduction steps

Already outlined

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Closing in favor of tracking existing feature request https://github.com/aws-amplify/amplify-cli/issues/7635
