### ISSUE TITLE
amplify configure fails to fetch environment in upgrade from 5.4.0 to 5.5.0

### ISSUE THREAD

**Issue by nealdeters** [aws-amplify/amplify-cli#8133]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

5.5.0

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

configure

### Describe the bug

We have our PR process setup to run tests via github actions. In this process we install amplify-cli and configure the environment to run our tests. 

In running tests this morning we are hit an error when configuring our environment:
`
amplify version 5.5.0
found existing environment stage
- Fetching updates to backend environment: stage from the cloud.
Could not initialize 'stage': Access Denied
`

I manually updated to use amplify version 5.4.0 today and the configure command works. It seems like there are permissions issues in the recent 5.5.0 release.

### Expected behavior

amplify configure command successfully configures and pulls back the environment from the cloud.

### Reproduction steps

1. Install node version 14
2. Install amplify-cli version 5.5.0
3. Run amplify configure

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hello @nealdeters,

Thank you for your feedback. I am trying to reproduce the issue following the reproduction steps without success.
Can you reproduce this issue in an empty folder, if there are any additional steps can you please provide them here?

**Comment by nealdeters** [comment]
I apologize @lazpavel, I forgot to mention that this is part of our testing process via github actions. We're building our amplify environment in a docker container. I tested again this morning on the latest version 5.6.0 and am still failing. I'm trying to think of the best way to reproduce this in a smaller scale.

For better understanding of our docker image, I've listed out our general setup below.

`
FROM node:lts

RUN apt update
RUN apt install -y software-properties-common
RUN wget -O- https://apt.corretto.aws/corretto.key | apt-key add - 
RUN add-apt-repository 'deb https://apt.corretto.aws stable main'
RUN apt-get update; apt-get install -y java-1.8.0-amazon-corretto-jdk

RUN npm install --global --unsafe-perm @aws-amplify/cli@latest
`

**Comment by josefaidt** [comment]
Hey @nealdeters :wave: are you still experiencing this issue with the [latest version of the Amplify CLI (v6.0.1)](https://github.com/aws-amplify/amplify-cli/releases/tag/v6.0.1)?

**Comment by nealdeters** [comment]
@josefaidt ran a test this morning using the latest version 6.0.1 and still hitting the same error.

**Comment by josefaidt** [comment]
Thanks for the information @nealdeters! How are you authenticating with the CLI in the newer versions? And are you able to capture the logs? These should be located at `~/.amplify/logs`.

Do you also experience this issue locally with the same credential set?

**Comment by nealdeters** [comment]
@josefaidt still working on a way to replicate this locally. Haven't had time yet this week to do so, but it's on my list.

**Comment by josefaidt** [comment]
Hey @nealdeters no worries! Thanks for getting back, I'll leave this open

**Comment by josefaidt** [comment]
Hey @nealdeters :wave: just wanted to follow-up and see if you had a chance to replicate this locally?

**Comment by nealdeters** [comment]
@josefaidt still haven't had a chance to test this locally yet. Currently we have it set to a specific version as a workaround.

**Comment by nealdeters** [comment]
@josefaidt I've tested locally and can replicate the issue with our docker container. We've updated to amplify 7.6.2 and attempt to run `amplify env pull --yes --categories {"auth":{"userPoolId":"user_pool","webClientId":"client_id","nativeClientId":"native_client_id"}}` to pull down our stage environment. 

Regarding the logs, it doesn't really give me much information. I'm able to find the existing stage environment, but the only information that is thrown is "Could not initialize 'stage': Access Denied". I've tested changing permissions for our Github user (even gave full admin access), but still continue to receive the same error.

**Comment by nealdeters** [comment]
I've solve the issue. It was due to our permissions on our IAM user that was standing up the Amplify environment. The update from 5.4 to 5.5 introduced some new method calls on env pull that were not there before. The methods s3.listObjectVersions and cfn.listStackResources were missing from our permissions. Adding them fixed the problem.
