### ISSUE TITLE
amplify console command does not use vim navigation key bindings

### ISSUE THREAD

**Issue by dpilch** [aws-amplify/amplify-cli#8134]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.7.0

### Amplify CLI Version

5.5.0

### What operating system are you using?

Amazon Linux 2

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

When running `amplify console` the user is prompted to choose to open the admin UI or Amplify console. vi navigation keys (`j` - move down, `k` - move up) do not work. All other user prompts the require selecting from a list allow for use of the vi navigation keys `j` and `k`.

```
$ amplify console 
? Which site do you want to open? … 
▸ Amplify admin UI
  Amplify console
```

### Expected behavior

* Pressing `j` should move the selection down one line.
* Pressing `k` should move the selection up one line.

Example:
1. `amplify configure`
2. User prompted to `Sign in to your AWS administrator account`.
3. Press `Enter`
3. User prompted to `Specify the AWS Region`.
4. Pressing `j` or `k` will cause the region selection to move down or up respectively

### Reproduction steps

1. `mkdir console-bug`
2. `cd console-bug`
3. `amplify init` (accept all defaults)
2. `amplify console`
  ```
  $ amplify console 
  ? Which site do you want to open? … 
  ▸ Amplify admin UI
    Amplify console
  ```
3. Press `j`.
4. The selection does not change.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hello @dpilch, thank you for your feedback.
I was able to reproduce this and marked it as a bug for the team to pick up.

**Comment by josefaidt** [comment]
Closing as the prompter library is built to filter lists on user input, which prohibits j/k from being mapped.
