### ISSUE TITLE
Impossible to force email uniqueness with Amplify CLI

### ISSUE THREAD

**Issue by ZebGirouard** [aws-amplify/amplify-cli#814]
**Is your feature request related to a problem? Please describe.**
In the [Amplify Auth Documentation](url), it states that

```
To enforce Cognito User Pool signups with a unique email, you need to change your User Pool’s Attributes setting in Amazon Cognito console as the following:
```

...but this is impossible.  Once a user pool is created, using the CLI, we cannot change the attribute configuration.  In fact, AWS's own documentation says so.

**Describe the solution you'd like**
Currently it does not seem possible to create the configuration pictured here using the CLI:

![](https://aws-amplify.github.io/amplify-js/media/images/cognito_user_pool_settings.png)

And it seems that the new Amplify CLI does not allow Mobile Hub configurations through the UI, which is how I set this configuration in the past.

I need a way to create the configuration pictured above using the new Amplify CLI, because I want to take advantage of the newer features, and it seems the effort of the Amazon team is on feature additions and bug fixes for this newer tool.

**Describe alternatives you've considered**
I have considered pointing to an existing user pool, but I cannot seem to do this through the CLI either.

If either setting the configuration pictured above or linking `amplify add auth` to an existing user pool is possible, please add this to the documentation.  And please remove the part that asks users to change configuration in a user pool after it's been created automatically.

**Comment by bradennapier** [comment]
Yeah they even show that you can do it in the docs which is not true at all https://aws-amplify.github.io/docs/js/authentication#using-components-in-react

**Comment by kaustavghosh06** [comment]
With our new version of the CLI we've introduced the ability for users to select how they want users (including an option for email uniqueness) to sign in upfront as a part of the default flow instead of setting the username attribute as a default in the default flow (which is immutable unfortunately after the creation of the userpool since that is a restriction from the Cognito service). Please feel free to check it out and re-open/comment on this issue if you see a problem with it.

**Comment by Soek22** [comment]
Hi @kaustavghosh06, thanks for adding it, very appreciated. 
I'm using the CLI console 1.6.1 to setup user sign-up with email/phone, and I've encountered an issue ( #1247 ).
Off-topic, cognito related: where could I open an issue/feature request for adding sign-in aliases to users that have signed-up with phone/email?

**Comment by 24jr** [comment]
@kaustavghosh06 Hey its me again. you seem to have the answers for every amplify thing I go to! But yeah now that I updated that method doesn't work anymore and I can't figure out how to get it so I can use usernames but also allow for email. Using the manual or the default auth it does the username way without email checkbox below or if I do the method above then it just creates a new Cognito pool with email as username and adds the check below for email. No I want the check below for email on the custom username one like worked before...

**Comment by asmajlovicmars** [comment]
Hi @kaustavghosh06, I'm using 4.13.4 version of CLI, and even though I included suggested change by @St3Ko, and pushed the auth without getting any errors, couldn't get **Enable case insensitivity for username input** checked off. Could you please advise how to ensure uniqueness of emails, which we use as username? Thanks.

**Comment by lorentzca** [comment]
Hi @asmajlovicmars,

> Not sure if this is the right way, but following the same instructions above, added at the same spot to the Properties code below and it works. (Recommended) Enable case insensitivity for username input is checked
> 
> UsernameConfiguration: CaseSensitive: false

It looks right. 👀

- https://github.com/aws-amplify/amplify-cli/issues/3494#issuecomment-590016486
