### ISSUE TITLE
Unable to create LSI using GraphQL Schema in Amplify

### ISSUE THREAD

**Issue by CodeMaxer** [aws-amplify/amplify-cli#8141]
We tried to implement a graphQL schema with an LSI and GSI for DynamoDB inside Amplify and keep running into issues. Is there anything wrong with our syntax below?
Note: LSI as 'ByOrderDate' and GSI as 'ByItemByStore'.

type OrdDtl @model
  @key(fields: ["StoreOrderID", "OrderLineID"])
  @key(name: "byOrderdate", fields: ["StoreOrderID", "LastDate"], queryField: "StoreOrderID")
  @key(name: "byItemByStore", fields: ["ItemID", "StoreOrderID"])
  @auth(rules: [{allow: public}]) {
  id:ID!
  StoreOrderID: String!
  OrderLineID: Int!
  ItemID: String!
  LastDate: AWSTimestamp
}

---------------------------------------------------------------------------------------------------
The current key functionality does generate LSIs as well. To generate an LSI, you can create a secondary @key directive with multiple fields, where the first field is the same as the hash key in the primary @key directive.

using the @key directive, the first @key directive: @key(fields:["HASH", "RANGE"]) will change the table hash and range keys to "HASH" and "RANGE". A second @key directive like: @key(name:"X", fields:["HASH", "RANGE_2"], queryField: "fieldToReferenceForLSI"] will generate the LSI because the hash is the same as the primary hash key. If instead your second key directive had its first field as "HASH_2", a GSI will be created.

_Originally posted by @RossWilliams in https://github.com/aws-amplify/amplify-cli/issues/1725#issuecomment-505862542_

**Comment by RossWilliams** [comment]
can you post details of the issue you are running into ?

**Comment by CodeMaxer** [comment]
The final outcome of running this schema is as below.
Both the indexes get created as GSI in dynamoDB where as we need LSI to be efficient. 

Note: We have many  LSI needs. This example is the simplest of all.

**Comment by RossWilliams** [comment]
can you confirm that this is a new table being created, and not an update to an existing table ? LSIs can only be created at the time a table is created.

**Comment by CodeMaxer** [comment]
yes, this is a brand new table...  I understand LSI and GSI conceptually and was successful if I did the same in DynamoDB directly. 
Since I need graphQL schema to create the Amplify app project, I am trying using the schema given above but it doesnt create LSI but always ends up with GSIs.

**Comment by RossWilliams** [comment]
sorry, I now see you have a "name" property in the LSI, don't specify a name for the LSI.

This is my best guess and I'm not 100% sure this fixes it, I haven't worked in Amplify for a year.

**Comment by RossWilliams** [comment]
I think I have your answer, there is a feature flag in the project to turn off LSIs. The feature flag is on by default for new projects (meaning no LSI gets created), and off for existing projects.

https://github.com/aws-amplify/amplify-cli/blob/fa172c4caf6f15de56925bd1ff4f8ee743788b52/packages/amplify-cli-core/src/feature-flags/featureFlags.ts#L543

**Comment by CodeMaxer** [comment]
Thank you very much! that was the answer 👍
