### ISSUE TITLE
AppSync Console Schema update is not reflected with amplify pull

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#8151]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.5.0

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

pull

### Describe the bug

I did some changes to appSync schema which is linked with my amplify app. I wrote some mutations and subscriptions in it and attached custom resolvers to them, and on `amplify pull` my local graphQL schema didn't not reflected with the changes which I did  in schema.

### Expected behavior

It should reflect the changes made in AppSync console. It should update the local graphql schema with the updated schema.

### Reproduction steps

1. Create an amplify project using console.
2. pull it and add graphql api
3. push it
4. Now make some changes in your schema using appsync console, and attach the resolver to it.
5. pull the code using appId and environment.
6. You will see no changes reflected in your local schema, which you can find under `amplify/backend/api/...
7

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hello @hackrx, 

Thank you for raising this issue. Currently we don't support a pull from AppSync Console. Amplify fully relies on CloudFormation to version and manage the infrastructure. Pull is intended for team workflows where one developers pushes the GraphQL transform schema and the other developer pulls that. 

Let us know if there is anything we can assist with.

**Comment by hackrx** [comment]
Hi @lazpavel, thanks for the follow-up. If amplify doesn't support the pull from appsync, then can you please tell me how can I write `type mutation` ? because in my `schema.graphql` file under `amplify/backend/api/<projectname>/`, I can't find it.
I know if we want to write custom resolvers, then we should place it under `amplify/backend/api/project/resolvers/` but how can I write/connect the resolver in `type mutation` and `type subscription` because mutation, subscription, and query type are not written in generated (from amplify pull) `schema.graphql` file.

I can find `type Mutation`, `type Query` and `type Subscription` under `amplify/backend/api/project/build/schema.grahpql`, but this is generated from schema.graphql right? so if I will make any changes in this build folder, then it will be discarded with `amplify push` right? 
Also, is there any way to download/export the custom resolvers which I have written in Appsync console?
Please correct me if I am missing something.
Thanks.

**Comment by hackrx** [comment]
I found the tutorial [here](https://docs.amplify.aws/cli/graphql-transformer/resolvers/), and it is working fine. 
Thanks.
