### ISSUE TITLE
How to clone project with amplify? With Appsync?

### ISSUE THREAD

**Issue by rygo6** [aws-amplify/amplify-cli#816]
This seems very undocumented and I am a bit confused. I am trying to get another developer going on this project. This is what I have done so far:

1. I push code to git relying on default generated .gitignore
2. Other developer pulls git repo.
3. Other developer runs awsmobile init mobilehubid

That completes rather successfully except that.

1. It does NOT configure Appsync. The aws-exports.js generated is devoid of appsync settings. The appsync-info.json is also devoid of information it just says:
```
{
    "freshLocalEnableDisableFlag": "enable"
}
```

2. It generates an extra folder I don't understand. In my project I have just "awsmobilejs". But when running awsmobile init mobilebudid on the freshly cloned project it generates a folder called "~awsmobilejs-2018-08-07-14-12-57" What is the purpose of this extra folder? Is that correct?

What is the proper method to clone a repo to a new machine and have awsmobile cli set up? How do I get appsync set up in that project as well? What is the extra folder with ~ and the date for?

Thank you.

**Comment by yuth** [comment]
@rygo6 are you using `amplify cli` or  `awsmobile`? Could you also mention the version

**Comment by kaustavghosh06** [comment]
Hey guys, we released a version of the Ampify CLI to support multiple environments (cloning of infrastructure) and sharing  your infrastructure between and outside teams. Please take a look at the documentation for the same - https://aws-amplify.github.io/docs/cli/multienv?sdk=js as it solves the above mentioned use-case and feel free to re-open this issue if you think this problem still exists.
