### ISSUE TITLE
Need To Choose AWS Region

### ISSUE THREAD

**Issue by svstartuplab** [aws-amplify/amplify-cli#817]
This is my first time with Amplify and first time setting up Cognito.  I have Cognito setup but wanted to add Amplify to my Angular app.  I went through the setup process but CloudFormation was created in the wrong region and I couldn't find a way to change this.

Do you want to request a feature or report a bug?

Bug?

What is the current behavior?

Setup in the docs for Getting Started and Angular assumed that my setup is in us-west-2 but I'm using us-west-1.  Cognito is in us-west-2 because it is not available yet in Norcal but will be moved there when possible.  The setup process created a mess.  Not sure aws-amplify is usable without the CloudFormation setup.  If there is a way to pass up using CloudFormation that isn't obvious in the setup.

What is the expected behavior?

Let users choose their region and it may not be the same for Cognito and S3.  Let us choose existing buckets.  Or modify the docs and setup process to make CF optional.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?  

I know nothing of previous versions.  Installed 1.0.6 plus angular 1.0.3.  Browser / OS doesn't matter.

**Comment by kaustavghosh06** [comment]
@svstartuplab Are you using the Amplify CLI to deploy your infrastructure/resources?

**Comment by svstartuplab** [comment]
@kaustavghosh06  Sorry, it has been so long since I worked with Amplify and I don't recall and can't find a reference to this issue in my notes on Amplify.  If the CLI uses CloudFormation I'm probably not using it.  I hate CF.  I have a billing problem now that was caused by using CF in an AWS workshop a month ago.  The cleanup script was supposed to end SageMaker but with a current bill of $90+ and growing daily something is messed up.  Please never use CF for anything.
