### ISSUE TITLE
SSM (Secret values) generated comments duplicated on each env

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#8177]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.5.0

### What operating system are you using?

Windows

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I am creating a separate bug report as suggested there https://github.com/aws-amplify/amplify-cli/issues/8090#issuecomment-919214043

Each time I am requested to do that:
![image](https://user-images.githubusercontent.com/7568421/133298833-d341ad7c-a860-4259-a255-bd7ed1ae485b.png)

a new comment is generated in the lambda
![image](https://user-images.githubusercontent.com/7568421/133298459-fb75b26d-60c5-4729-8e31-466471c17fa7.png)

Notes:
- I am using multiple env and git branches.
- I have introduced secrets in one of the branches (e.g. dev). When propagating changes to other branches/envs, the secrets have to be populated each time. When doing that, the reported issue occurs.
**- the same identical issue occurs with all generated comments, like in that case:**
![image](https://user-images.githubusercontent.com/7568421/133299550-938ca003-c449-4941-83bf-f151ebaa4b6e.png)

### Expected behavior

Avoid keeping adding that comment if an identical one exists.

Question: is that comment actually required? 

I can this feature may become tricky if that comment is not entirely identical.
Maybe a way forward is to start handling simpler cases (like: "if an identical comment is found, then do not add another one"), and then move on to more complex cases (e.g. the comment is not identical because a variable was removed/added).

**Comment by josefaidt** [comment]
Hey @cfbo :wave: thanks for taking the time to file this separately! What file do you see the Params comment block get added to? And may you share your reproduction steps?

**Comment by cfbo** [comment]
The key point is the following:
> I have introduced secrets in one of the branches (e.g. dev). When propagating changes to other branches/envs, the secrets have to be populated each time. When doing that, the reported issue occurs.
It's very easy to reproduce.

The file where this happen is any file where that comments are initially applied to (e.g. index.js for a Node hello world lambda).
Just create a new env and on push, when the CLI asks values for these parameters, you'll end up with additionally generated comments (duplicated).

**Comment by josefaidt** [comment]
Hey @cfbo :wave: I'm unable to reproduce the issue where comments are duplicated. I did notice that if we use the commented block or remove it, it will be re-added on update or env checkout, though if I left the comment alone I was not seeing it be duplicated. Would you mind sharing a full screenshot of the function where the comments are duplicated and if there were any additional steps taken to reproduce successfully?

**Comment by cfbo** [comment]
I have just created a new env (with amplify init). Here is what I get: 
![image](https://user-images.githubusercontent.com/7568421/135271510-bd49f5bd-75ce-412b-966d-cbd31d0c890e.png)

**Comment by josefaidt** [comment]
Hey @cfbo is this using WSL on Windows or Windows itself? I did notice we're using `\n` in the templated code which may be causing some issue, however I am still unable to reproduce when using Windows, Ubuntu on WSL, and macOS. Does this happen only with new envs or also with existing envs that do not yet have the secrets defined?

**Comment by cfbo** [comment]
I am on windows 10, using powershell (I have WSL but not using this for this).
It happens after creating a new env using amplify init. When doing that it asks if I want to carry over secrets: Yes.
Once the creation of the env is completed, I can see that comment being added.

**Comment by josefaidt** [comment]
Hey @cfbo just wanted to follow-up and see if you are still experiencing this issue with the [latest version of the CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.5.4)?

**Comment by cfbo** [comment]
This issue is still occurring to me all the times (I have noticed it again few days ago). However unfortunately I don't have time to reproduce it. Looks like no one else is upvoting it so I am absolutely fine with closing it. 
The workaround for me is to remove the generated comments each time (to avoid duplication). Of course I keep the latest generated version.
