### ISSUE TITLE
amplify environmentcchange and resource issue

### ISSUE THREAD

**Issue by NihalKA** [aws-amplify/amplify-cli#8184]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

5.6.0

### What operating system are you using?

Mac,Ubuntu

### Amplify Categories

auth, storage, api

### Amplify Commands

env, pull, push, status

### Describe the bug

amplify app was created and there were storage,api,auth, notification. At first time when i do amplify pull it says it will created some unwanted resources(like delete my existing api and creating new) based on my local changes. what is do is amplify pull again(or amplify pull --restore)where everything comes back to normal. at that moment amplify push says no changes detected. at this moment there were all my required resources.
Now I created new env using amplify env add envname, here again those unwanted new resources(that i told Iam having before amplify pull) appears again.I removed that and try amplify push. Iam not able to push the exact correct changes.
the issue is resolved when a new app is created. still the old app is receiving issue. how can we solve this

### Expected behavior

amplify env checkout and pushing should should exactly push and create new resources in new env based on cloning env

### Reproduction steps

amplify env- dev:
amplif add api. - api1
adplify add auth -auth1
amplify add storage- storage1
 this is pushed and all set

some how in my backend-config.json I can see an api2 which i dont require. so to a new folder when i try to pull from amplify this api2 comes first. i'll do a amplify pull --restore, my correct api1 will come

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@NihalKA Did you push after creating the new resources in your first env?

**Comment by josefaidt** [comment]
Hey @NihalKA :wave: are you still experiencing this issue?
