### ISSUE TITLE
Remove the lines between the amplify status report

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-cli#8185]
### Describe the feature you'd like to request

The lines are just noise and actually make this harder to read. When there are more than a few resources it scrolls them off the top of the console screen. Example screenshot (only a few lines shown):
<img width="516" alt="Screen Shot 2021-09-15 at 5 16 37 AM" src="https://user-images.githubusercontent.com/1952793/133424316-a8a7ce2e-04c1-4eec-92c9-2047dfb99aa1.png">

### Describe the solution you'd like

Remove the lines between the useful information.

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by zlintz** [comment]
So much better without the lines, hopefully others agree

**Comment by cjihrig** [comment]
The linked PR was closed as a won't fix, so I'm going to close this out as well. Thank you for the feature request though.
