### ISSUE TITLE
Update dependencies in Lambda

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-cli#8189]
So I found a High severity vulnerability (which I reported already to aws-security@amazon.com) but I was wondering If I can manually update to the suggested version in the meantime?
How can I update my lambda function dependencies that uses node.js?

**Comment by ammarkarachi** [comment]
@afern247 Is it a third party dependency?

**Comment by afern247** [comment]
> @afern247 Is it a third party dependency?

Yes it is. The dependency is not mine if that's what you are thinking. It's from Amplify.

**Comment by ammarkarachi** [comment]
>Yes it is. The dependency is not mine if that's what you are thinking. It's from Amplify.

I meant the Lambda function dependency?

**Comment by afern247** [comment]
what do you mean lambda function dependency? My lambda is a super simple function post-sign up confirmation to create some data on DynamoDB. It has nothing modified by me such as installed dependencies...

This is what comes with Amplify when you create the lambda

**Comment by afern247** [comment]
The team of the vuln. just pushed an update and I got it merged. Closing this.
