### ISSUE TITLE
Restricting access of REST API with non alphanumeric URL fails on push when group access is selected

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#8193]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.5.0

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Restricting access of REST API with non alphanumeric URL fails on push when group access is selected.

### Expected behavior

The push should not fail.
Given that api paths with dashes or other character are allowed, I suppose they should also be allowed when the group restricition policy is added.

### Reproduction steps

Create REST API 
Add endpoint `list-items`
Restrict access to **Both** authenticated users and groups
Run `amplify push`

![image](https://user-images.githubusercontent.com/7568421/133622904-4915b9e6-f1b1-4a5d-bf59-860c642010db.png)

Error:
![image](https://user-images.githubusercontent.com/7568421/133623118-5f1a613d-43fe-44ea-96ca-84fa273022f4.png)

**Comment by josefaidt** [comment]
Hey @cfbo :wave: thanks for taking the time to file this! I've confirmed the behavior when we restrict access to user groups on an endpoint with a dash included such as `hello-world`.

![image](https://user-images.githubusercontent.com/5033303/133626521-c918eec8-b632-4615-91ff-e0c03596a584.png)

As a temporary workaround we can remove the dash from this resource name (`usersGrouphelloworldPolicy`) and push successfully. Marking this as a bug 🙂

**Comment by jhockett** [comment]
Closing as this is no longer an issue on the latest version of the CLI.
