### ISSUE TITLE
Querying eq operator not working when using GSI composite SK.

### ISSUE THREAD

**Issue by glynjackson** [aws-amplify/amplify-cli#8204]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

amplify schema, cli and AppSync

**Amplify CLI Version** 

5.6.0

**Issue** 

I have been trying to resolve an issue for the last few days and cannot work out why the "eq" operator on my query is refusing to yield results. I have a transaction schema with a composite SORT KEY. I have results and all other operators i.e. beginsWith, le, gt etc all work and return the correct results, however, "eq" returns nothing. Why?

It is understanding that with a composite SK I can query on one or more of the fields that make up that key. However, this does not seem to be the case. It seems like eq operator has to match the whole string i.e `value#value`. 

My key:

```
# byAccountCategory: GSI with composite SORT using a combination categoryCode & sortIndex (sort direction) i.e 1021#00000691.
@key(name: "byAccountCategory", fields: ["accountOBConnectID", "categoryCode", "sortIndex"], queryField: "transactionByCategory")
```

**Works** beginsWith:

```
query MyQuery {
  transactionByCategory(accountOBConnectID: "da086ebb-46d7-42d7-b4c9-d6b96e6b551f", categoryCodeSortIndex: {beginsWith: {categoryCode: 100}}) {
    items {
      amount
      categoryName
      categoryCode
      sortIndex
      typeName
      typeCode
    }
  }
}
```

**Returns**

```
{
  "data": {
    "transactionByCategory": {
      "items": [
        {
          "amount": "1801.24",
          "categoryName": "Salary",
          "categoryCode": 100,
          "sortIndex": "0000000134",
          "typeName": "Income",
          "typeCode": 1
        },
        {
          "amount": "1801.44",
          "categoryName": "Salary",
          "categoryCode": 100,
          "sortIndex": "0000000296",
          "typeName": "Income",
          "typeCode": 1
        }, etc....
```

Operator ge **works**...

```
query MyQuery {
  transactionByCategory(accountOBConnectID: "da086ebb-46d7-42d7-b4c9-d6b96e6b551f", categoryCodeSortIndex: {ge: {categoryCode: 100}}) {
    items {
      amount
      categoryName
      categoryCode
      sortIndex
      typeName
      typeCode
    }
  }
}

```

However, when I try to use the operator 'eq' I get **no** results where I should have over **10**.

**Not working...**

```
query MyQuery {
  transactionByCategory(accountOBConnectID: "da086ebb-46d7-42d7-b4c9-d6b96e6b551f", categoryCodeSortIndex: {eq: {categoryCode: 100}}) {
    items {
      amount
      categoryName
      categoryCode
      sortIndex
      typeName
      typeCode
    }
  }
}
```

**Results:**

```
{
  "data": {
    "transactionByCategory": {
      "items": []
    }
  }
}
```

What I'm I doing wrong?

What I have tried.

- I have data and it is valid. 
- I have run the queries in the Appsync console to make sure this is not code related.
- Permissions are correct. In fact, if I get data for the other operators there is no reason why eq should not work
- Filters with the eq operator work but just not a query using a GSI SK 

**Schema**

```
type Transaction
@model
@aws_cognito_user_pools
@auth(rules: [
      # Cognito users in Admin Group operations.
      { allow: groups, groups: ["Admin"], operations: [read]},
      # Dynamic group authorisation on the record.
      { allow: groups, groupsField: "groupsCanAccess", operations: [read]}
      ])

# byAccountCategory: GSI with composite SORT using a combination categoryCode & sortIndex (sort direction) i.e 1021#00000691.
@key(name: "byAccountCategory", fields: ["accountOBConnectID", "categoryCode", "sortIndex"], queryField: "transactionByCategory")
{
    # Core Transaction Fields.
    id: ID! # Unique identifier for the transaction within an servicing institution.
    accountID: ID! # A unique and immutable identifier used to identify the account resource. 
    accountOBConnectID: ID! # Used to identify the account resource
    applicantID: ID! # Unique identifier for the Applicant.
    groupsCanAccess: [String]! # Which Cognito user group(s) can access this record.
    sortIndex: String! # A string assigned to the transaction to ensure a stable sort. A smaller index value corresponds to a more recent Transaction.
    amount: String! # A number of monetary units specified in an active currency.
    # Classification Fields.
    typeName: String # Name of the classification type.
    typeCode: Int # Classification type code 
    categoryName: String # Name of the category.
    categoryCode: Int 
}




```

![Screenshot 2021-09-17 at 11 48 21](https://user-images.githubusercontent.com/426906/133770733-b0f7e4f0-91f0-4815-ad1b-4e0d8f773bb7.png)

Logs:

```
{
    "logType": "RequestMapping",
    "path": [
        "transactionByCategory"
    ],
    "fieldName": "transactionByCategory",
    "resolverArn": "arn:aws:appsync:eu-west-1:956388132785:apis/ja4l5riza5bglc6iym7jreyu4i/types/Query/resolvers/transactionByCategory",
    "requestId": "80d018fe-a193-4a0b-a67a-59857bff5595",
    "context": {
        "arguments": {
            "accountOBConnectID": "da086ebb-46d7-42d7-b4c9-d6b96e6b551f",
            "categoryCodeSortIndex": {
                "eq": {
                    "categoryCode": 100
                }
            }
        },
        "stash": {},
        "outErrors": []
    },
    "fieldInError": false,
    "errors": [],
    "parentType": "Query",
    "graphQLAPIId": "ja4l5riza5bglc6iym7jreyu4i",
    "transformedTemplate": "                       \n  \n\n\n{\"version\":\"2018-05-29\",\"operation\":\"Query\",\"limit\":100,\"query\":{\"expression\":\"#accountOBConnectID = :accountOBConnectID AND #sortKey = :sortKey\",\"expressionNames\":{\"#accountOBConnectID\":\"accountOBConnectID\",\"#sortKey\":\"categoryCode#sortIndex\"},\"expressionValues\":{\":accountOBConnectID\":{\"S\":\"da086ebb-46d7-42d7-b4c9-d6b96e6b551f\"},\":sortKey\":{\"S\":\"100\"}}},\"index\":\"byAccountCategory\",\"scanIndexForward\":true}"
}
```

**Comment by sundersc** [comment]
Hey @glynjackson, we will look into this. Meanwhile, could you try to include the field `sortIndex` too in the query(`eq` condition) and see whether it is returning the results.

```graphql
query MyQuery {
  transactionByCategory(accountOBConnectID: "da086ebb-46d7-42d7-b4c9-d6b96e6b551f", categoryCodeSortIndex: {eq: {categoryCode: 100, sortIndex: "0000000134"}}) {
    items {
      amount
      categoryName
      categoryCode
      sortIndex
      typeName
      typeCode
    }
  }
}
```

**Comment by sundersc** [comment]
When using composite sort key, dynamoDB stores the data in the format `FieldA#FieldB#FieldC`, so all the key condition expressions work around that format. In your example, it is actually looking for `categoryCode#sortIndex` equal to `100`.
[Best Practices for Using Sort Keys to Organize Data](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html
)

Here are the options I could think that would solve your problem.

**Option 1:**
Use beginsWith as shown below, this will return all records with `categoryCode = 100`.

``` graphql
query MyQuery {
  transactionByCategory(accountOBConnectID: "da086ebb-46d7-42d7-b4c9-d6b96e6b551f", categoryCodeSortIndex: {beginsWith: {categoryCode: 100, sortIndex: ""}}) {
    items {
      amount
      categoryName
      categoryCode
      sortIndex
      typeName
      typeCode
    }
  }
}
```

**Option 2:**
Create an another index with only `categoryCode` as sort key and use `eq` key condition expression.

**Option 3:**
Use `@searchable` directive. This provides more options for searching using OpenSearch.
https://docs.amplify.aws/cli/graphql-transformer/searchable/

**Comment by glynjackson** [comment]
Thank you for such a detailed response. @sundersc This really helped me to understand. Using your advice I decided to look at my access patterns and came up with a solution that allows this to work with a correct sort direction. again thank you

**Comment by loganpowell** [comment]
Hi friends 👋 

Sorry to ping a closed issue, but mine is related.

I am having a similar issue using three-field composite keys and anything other than the `beginsWith` operator. I can't find any docs on how one might go about using the other operators (`lt` / `le` / `gt` / `ge`) with a composite key that includes an `enum` with a date field (`createdAt`).

It seems to me that the only operator that works in this case is `beginsWith`, is that right? If so, shouldn't this be [documented](https://docs.amplify.aws/cli/graphql-transformer/key/#designing-data-models-using-key)?
