### ISSUE TITLE
What all policies can be added to replace for AdministratorAccess?

### ISSUE THREAD

**Issue by dongnguyen01** [aws-amplify/amplify-cli#8205]
Hi everyone,
Because I am not allowed to add IAM user with AdministratorAccess.
Therefore, could you please guide me how to use "amplify init" without AdministratorAccess?
What all specific policies must I add to my IAM user to be able to use from CLI?
Thanks a lot.

**Comment by josefaidt** [comment]
Hey @dongnguyen01 :wave: please refer to our [documentation page for the necessary IAM policies](https://docs.amplify.aws/cli/usage/iam/#3-set-up-the-local-development-environment-dev-corp). You can also use `AdministratorAccess-Amplify` rather than the global `AdministratorAccess` policy

**Comment by dongnguyen01** [comment]
> Hey @dongnguyen01 👋 please refer to our [documentation page for the necessary IAM policies](https://docs.amplify.aws/cli/usage/iam/#3-set-up-the-local-development-environment-dev-corp). You can also use `AdministratorAccess-Amplify` rather than the global `AdministratorAccess` policy

I also added "AdministratorAccess-Amplify" to my IAM user, but I got a list of errors in console
![error2](https://user-images.githubusercontent.com/80385228/133797375-c9d5bfbc-59e3-4964-b49b-f48048bf10ff.png)

![error1](https://user-images.githubusercontent.com/80385228/133797365-7249788c-b231-4b4f-96f5-2f520e387186.png)

In CLI command line, I got the error: 
`AccessDeniedException: User: arn:aws:iam::***:user/myAcount is not authorized to perform: amplify:CreateApp on resource: arn:aws:amplify:ap-northeast-1:***:apps/* with an explicit deny
 code: 'AccessDeniedException',
  time: 2021-09-17T11:07:18.997Z,
  requestId: '71fc6db3-ab61-4216-b8cb-28441976d0e5',
  statusCode: 403,
  retryable: false,
  retryDelay: 0.15392640388640633
`

I didn't pay attention to the page you send before.
I will follow you link.
Thank you for your help.

**Comment by josefaidt** [comment]
Hey @dongnguyen01 :wave: were you able to update the permissions and create resources using the CLI successfully?

**Comment by dongnguyen01** [comment]
> Hey @dongnguyen01 👋 were you able to update the permissions and create resources using the CLI successfully?

Yes, when I create new IAM user with Programmatic Access and AdministratorAccess-Amplify, I could use CLI.
However, with old IAM user (I am provided, with MFA option), I do not know if it is selected Programmatic Access (when creating) because in account credential setting, no access key is existing. Therefore, I created new access key. And, although I also provided AdministratorAccess for it, I cannot still use CLI.

**Comment by josefaidt** [comment]
@dongnguyen01 thank you for the information! Can you confirm whether the IAM user you are provided has Programmatic Access? Perhaps this [documentation page for IAM & MFA](https://docs.amplify.aws/cli/usage/iam-roles-mfa/#3-set-up-the-local-development-environment-dev-corp) could provide more insight as to how users with MFA can be configured for use locally

**Comment by dongnguyen01** [comment]
> @dongnguyen01 thank you for the information! Can you confirm whether the IAM user you are provided has Programmatic Access? Perhaps this [documentation page for IAM & MFA](https://docs.amplify.aws/cli/usage/iam-roles-mfa/#3-set-up-the-local-development-environment-dev-corp) could provide more insight as to how users with MFA can be configured for use locally

Where could I check whether the IAM user you are provided has Programmatic Access?
As I read somewhere, if I create access key, I will have Programmatic Access.
Therefore, I think I will only need to follow your link to work with IAM & MFA. I hope it work.
But I will test this later because now I could work by creating new IAM user with Programmatic Access and AdministratorAccess-Amplify.

Thank you for your help!!!
