### ISSUE TITLE
How should I handle configuration files created by amplify cli that contain account specific information ?

### ISSUE THREAD

**Issue by gvlachos** [aws-amplify/amplify-cli#821]
Recently I have been trying out Amplify. I use Ubuntu 18.04.1, node 10.13.0 and the latest version of the Amplify cli (0.1.44  from running 'amplify --version'). I have one github repository with the following structure:

```
root
 +
 |
 +---+ mobile
 |       +
 |       |
 |       +-----+ expo
 |
 +----+server
         +
         |
         +-----+ rest
```

There is one .gitignore file that I created in the root. I then created an React Native project in the expo directory and ran amplify init, amplify auth and amplify add api for GraphQL. In this case there were no updates to either the root or the expo .gitignore files.

In the rest directory, which was initially empty, I ran amplify init and amplify add api for REST (Lambda). In the case the root .gitignore file was not updated and there was no .gitignore file created in the rest directory.

I noticed that there are a number of files that contain specific information to my AWS account (such as configuration, specific endpoints and API keys) such as 

- expo/.amplifyrc
- expo/aws-exports.js
- expo/amplify/#current-cloud-backend/amplify-meta.json and
- expo/amplify/backend/amplify-meta.json

and similar in the directories under rest.

The information in this file seems very specific to my AWS account and especially the aws_appsync_apiKey in aws-exports.js seems to me that is not a good idea to store them in a repository as a simple file.

So I would like to ask:

1) am I right that these are the only places that have account information or have I missed some other file ?

2) would you have some suggestion of how to save them in a repository such as github (maybe somehow encrypted) ?

3) if I do not put them in the repository, could you suggest a development process I could use with Ampllfy cli ?

**Comment by yuth** [comment]
@gvlachos a multienv version of Amplify CLI is being tested and soon will be merged with master. We do add a [`.gitignore`](https://github.com/aws-amplify/amplify-cli/blob/multienv/packages/amplify-cli/src/extensions/amplify-helpers/get-git-ignore-blob.js) file in multienv branch to mask account specific information. You could either start using `@multienv` tag of Amplify CLI or use the linked `.gitignore` as the starting point

**Comment by gvlachos** [comment]
@yuth ok I see the new version of the Amplify CLI now with the updated .`gitignore` file that excludes the following:

```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
aws-exports.js
awsconfiguration.json
```

It would be great if you could also let me know what steps I need to take on a project just pulled from github in order to re-create these files (the third part of my question above). 

Note that the project is initialized with auth (`amplify add auth`) and GraphQL (`amplify add api`).

**Comment by kaustavghosh06** [comment]
@gvlachos You can simply git clone and then ‘amplify init’ on that project.

**Comment by gvlachos** [comment]
@kaustavghosh06 I did that (`git clone` and then ran `amplify init`) however `amplify status` shows that there is a difference in my GraphQL api

```
Current Environment: demo

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | expotabsdemov2  | Update    | awscloudformation |
| Auth     | cognitoa1b085a0 | No Change | awscloudformation |

```

Also:

1.  `aws-exports.js` in the root of my project was not generated

2. the file `./amplify/backend/amplify-meta.json` in the clone is different from the original,  it contains the following entry in the providers section:

```
        "categories": {
            "auth": {
                "cognitoa1b085a0": {}
            }
        }
```

3. in the cloned project there is no file 'amplify/backend/awscloudformation/nested-cloudformation-stack.yml' while there is in the original

4. in the cloned project there is no directory './amplify/backend/api/expotabsdemov2/build' while there is in the original with directories of functions, resolvers, stacks and files schema.graphql, parameters.json, cloudformation-template.json

from the above I certainly need 1 but I am not sure when I may need 2, 3, 4, (I am quite new with all this)
