### ISSUE TITLE
AdminQueries function includes aws-sdk in dependencies

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#8213]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

latest

### Amplify CLI Version

latest

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

add

### Describe the bug

aws-sdk is included in the dependencies for the adminqueries lambda...my understanding is that it is automatically included in lambda's, and so should be unnecessary to include in the zip file...might be better if it was a devDependency?

### Expected behavior

Don't include aws-sdk in adminqueries zip file

### Reproduction steps

Create an admin interface and push the zip file

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
The `aws-sdk` is now a devDependency. This was addressed by https://github.com/aws-amplify/amplify-cli/pull/9669, closing this issue. Thanks for the suggestion @GeorgeBellTMH!
