### ISSUE TITLE
Resource is not in the state stackUpdateComplete An error occurred during the push operation: Resource is not in the state  stackUpdateComplete

### ISSUE THREAD

**Issue by babaralishah** [aws-amplify/amplify-cli#8218]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by siegerts** [comment]
Hi :wave: - thanks for raising this!  To get a bit more context, do you mind porting this to the issue template here:

- [bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=) 

A more detailed reproduction will help the team determine the best approach to take. Thanks!
