### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by NobbuMajankwe** [aws-amplify/amplify-cli#8219]
I'm using a REST API that triggers Lambda functions but I keep getting a CORS policy error: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Even when I have specified 'Access-Control-Allow-Origin' and I'm calling the API from the Origin I defined on 'Access-Control-Allow-Origin' (i.e. http://localhost:3000)
how do I fix this error?

region: eu-west-2
app Id: d6ozmsl14fg99

AWS Amplify, API(REST),  Lambda

```js
// Enable CORS for all methods
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "http://localhost:3000")
  res.header("Access-Control-Allow-Headers", "Authorization")
  next()
});

//Calling the API 
const testAPI = (event) => {
  event.preventDefault();
      const apiName = "TestAPI";
      const path = "/item/testingApi";
      const myInit = {
        body: {
          emails: ["applications@motech.dev"] /* REQUIRED */,
          subject: "The Subject" /* REQUIRED */,
          body: "The Body \n The Body Also" /* REQUIRED */,
          replyTo: ["support@motech.dev"] /* OPTIONAL */,
        },
      };
      API.post(apiName, path, myInit)
        .then( async (response) => {
          console.log("success", response);
          alert("success: "+ response);
        })
        .catch((error) => {
          console.log("error", error);
        });
}
```

**Comment by josefaidt** [comment]
Hey @NobbuMajankwe :wave: just wanted to follow-up on @siegerts comment regarding CORS headers' values and restructuring the reproduction steps. Please note there is an [active feature request for adding CORS headers to failed responses](https://github.com/aws-amplify/amplify-cli/issues/5183), which could be causing confusion when, for instance, the Lambda fails to respond.

**Comment by NobbuMajankwe** [comment]
Have managed to sort the error out, seemingly when the lambda function throws any error, the API Gateway throws a CORS error even though the problem is not related to the CORS / CORS headers. of which that could be an error worth investigating....

**Comment by josefaidt** [comment]
Ahh glad to hear you're back up and running! It sounds like you've run into the issue where CORS headers are not attached to the error responses we'd get from API Gateway, which is documented in the linked feature request. I'll see what we can do to get that prioritized 🙂 

Closing as issue has been resolved
