### ISSUE TITLE
Disabling cloud-api does not delete/remove the stack

### ISSUE THREAD

**Issue by jbarwick** [aws-amplify/amplify-cli#823]
Do you want to request a feature or report a bug?

BUG in version 1.1.4

What is the current behavior?

Deleting the cloud-api simply performs an UPDATE_STACK

What is the expected behavior?

Delete the stack.

With the comand:

? please confirm to disable: cloud-api Yes

Expected to delete all files, clean up everything...and run DELETE_STACK 

The result was:

disabled: cloud-api
backend awsmobile project enabled features:
database, hosting, user-signin

MacBook-Pro-4:gorilla-tip-mobile-web jbarwick$ awsmobile push

checking the backend contents
   generating backend project content
   done
backend build artifacts are saved at:
/Users/jbarwick/Development/Gorilla Pit/gorilla-tip-mobile-web/awsmobilejs/.awsmobile/backend-build

preparing for backend project update: gorilla-tip-web
done

updating backend project: gorilla-tip-web
awsmobile api call successful
waiting for the cloud formation to complete
cloud-api update finished with status code: UPDATE_COMPLETE

Successfully updated the backend awsmobile project: gorilla-tip-web

The backend was NOT deleted.

**Comment by UnleashedMind** [comment]
@jbarwick 
What you found is correct, it's the mobile hub service behavior. 
Since the mobile hub project has been deprecated, there's no active development on it at this moment.

**Comment by UnleashedMind** [comment]
close the issue for now, feel free to reopen if needed.
