### ISSUE TITLE
Share Cognito UserPool (backend) between an alpha and beta websites (two more distinct apps) 

### ISSUE THREAD

**Issue by yahavb** [aws-amplify/amplify-cli#824]
**Is your feature request related to a problem? Please describe.**
I wish to deploy more than one amplify apps that use the same backend. Specifically, CognitoUserPool 

**Describe the solution you'd like**
Share Cognito UserPool (backend) between an alpha and beta websites (two more distinct apps) 

**Describe alternatives you've considered**
Create one backend dev with the Amplify CLI 2. Connect both the 'alpha' and 'beta' branches to the Amplify Console using the 'dev' backend.

**Additional context**

**Comment by Jefftopia** [comment]
I'm trying to do this as well using `amplify env`, but `import` has no documentation so I'm not sure what I'm supposed to pass to the `--config` param or the `--awsInfo` param. 

I tried giving them path to files in the `/amplify` directory of my other project but an error is thrown saying "must use object notation".

**Comment by kaustavghosh06** [comment]
@Jefftopia I've provided a sample for you in #828

**Comment by yuth** [comment]
Amplify CLI does not support sharing the resources between different apps directly as this could have unintended consequences of each app changing the same resource. 

You could try creating a separate amplify project to for the shared resources and then using the values from the export file in your application.
