### ISSUE TITLE
Amplify failing to find GroupRole Policies causing Pushes to fail

### ISSUE THREAD

**Issue by theraggedflygon** [aws-amplify/amplify-cli#8258]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.18.3

### Amplify CLI Version

6.0.1

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

After running `amplify update auth` I am now being greeted by the error message indicating that two of my cognito usergroup roles cannot be found. The error text is as follows:
```CREATE_FAILED               adminGroupPolicy                                                   AWS::IAM::Policy           Thu Sep 23 2021 09:41:23 GMT-0500 (Central Daylight Time) The role with name authsensordbui9f42de86UserPoolId-adminGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 309aead7-6f9b-43c6-af52-4bee11e316de; Proxy: null) ```

### Expected behavior

As I did not touch the groups when running `amplify update auth`, I would expect the push to be successful and that I could continue working on my application.

### Reproduction steps

This began by trying to use a model within a post-confirmation Cognito trigger which itself was unsuccessful as has been documented in #4568. As documented in the issue, I was unable to push my changes and thus had to revert them using `amplify pull env --restore` since you cannot remove access to all of Auth, Storage, API, etc using `amplify update function`.

When I next made a change and attempted to push I was given an error reading `AWS::CloudFormation::Stack Thu Sep 23 2021 09:07:27 GMT-0500 (Central Daylight Time) Parameters: [authProviders, breakCircularDependency, thirdPartyAuth, aliasAttributes] must have values` which I was able to fix by running `amplify update auth` and proceeding through the menus. The full logs of my auth update can be found here: 

```
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Do you want to add User Pool Groups? Yes
? Select any user pool groups you want to delete:  
? Do you want to add another User Pool Group No
√ Sort the user pool groups in order of preference · admin, dev, other
 Do you want to add an admin queries API? No
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? Add User to Group
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Confirmation
? What functionality do you want to use for Post Confirmation Add User To Group
? Enter the name of the group to which users will be added. 
```

Even though this fixed the previous issue, a new issue arose where it says that the IAM Group Policies do not exist. The error text is as follows:
```
CREATE_FAILED               adminGroupPolicy                                                   AWS::IAM::Policy           Thu Sep 23 2021 09:41:23 GMT-0500 (Central Daylight Time) The role with name authsensordbui9f42de86UserPoolId-adminGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 309aead7-6f9b-43c6-af52-4bee11e316de; Proxy: null) 
CREATE_FAILED               devGroupPolicy                                                  AWS::IAM::Policy           Thu Sep 23 2021 09:41:23 GMT-0500 (Central Daylight Time) The role with name authsensordbui9f42de86UserPoolId-devGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 5cd31573-5669-4c81-8f9f-34e43b5f06b6; Proxy: null)
```

I have not been able to fix this error and thus have been unable to push since this started.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

CREATE_FAILED               adminGroupPolicy                                                   AWS::IAM::Policy           Thu Sep 23 2021 09:41:23 GMT-0500 (Central Daylight Time) The role with name authsensordbui9f42de86UserPoolId-adminGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 309aead7-6f9b-43c6-af52-4bee11e316de; Proxy: null) 
CREATE_FAILED               devGroupPolicy                                                  AWS::IAM::Policy           Thu Sep 23 2021 09:41:23 GMT-0500 (Central Daylight Time) The role with name authsensordbui9f42de86UserPoolId-devGroupRole cannot be found. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 5cd31573-5669-4c81-8f9f-34e43b5f06b6; Proxy: null)

**Comment by josefaidt** [comment]
Hey @theraggedflygon :wave: thank you for taking the time to file this! Would you mind posting the diff of the auth resource's CloudFormation template? Or can you confirm whether a block like the following exists in the template?:

```json
"membersGroupRole": {
  "Type": "AWS::IAM::Role",
  "Properties": {
      "RoleName":{
          "Fn::Join": [
              "",
              [
                {
                  "Ref": "authamplifyauthUserPoolId"
                },
                "-membersGroupRole"
              ]
          ]
      },
      "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "",
                  "Effect": "Allow",
                  "Principal": {
                      "Federated": "cognito-identity.amazonaws.com"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {"cognito-identity.amazonaws.com:aud": {"Ref":"authamplifyauthIdentityPoolId"}},
                    "ForAnyValue:StringLike": {"cognito-identity.amazonaws.com:amr": "authenticated"}
                  }
              }
          ]
      }
  }
},
```

**Comment by theraggedflygon** [comment]
Yes I see a block like that in `auth/userPoolGroups/template.json`. Both of the roles have blocks that look like that.

**Comment by josefaidt** [comment]
Thanks for clarifying @theraggedflygon ! I have a couple follow-up questions:

- Did these groups exist before attempting to update the auth resource?
- Do you see an error in the CloudFormation console that perhaps provides more details as to why this role creation failed? 
- Were you able to capture the git diff of these template files to determine what changed after running `amplify update auth`?
- Does running `amplify push --force` with the changes locally alleviate the issue?

For what it's worth we should be able to see this IAM role in the console:
![image](https://user-images.githubusercontent.com/5033303/134983970-746df143-6d16-4c8f-9f82-f7e7212ccbde.png)

**Comment by theraggedflygon** [comment]
Per your request, I've just run `amplify push --force` and that succeeded. I am now able to push changes to the cloud and it appears like the Cognito Groups are unaffected. I'll be sure to update this thread if I find that the forced push causes any further issues, but for right now everything seems to be good! Thanks for the help.

**Comment by josefaidt** [comment]
Ahh glad to hear you're back up and running @theraggedflygon! Given the issue has been resolved I will go ahead and close this issue 🙂 , however if anything surfaces please reply back to this thread and we can re-open to investigate further.
