### ISSUE TITLE
Lambda package-lock.json sporadically flips lockfileVersion

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#8271]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

5.6.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Every now and then when I run `amplify push` through the CLI I would get a different package-lock.json file for one or more functions. It appears that the _lockVersion_ property in the file flip-flops between 1 and 2 and that the _packages_ section from the json either appears or is removed. (Looks like that section is present when the lockVersion is 2 and the "packages" section is gone when the lockVersion is 1) E.g.
![Screen Shot 2021-09-24 at 4 43 38 PM](https://user-images.githubusercontent.com/11936077/134737564-41c814a0-326b-4c43-a321-e654e31c7acf.png)

### Expected behavior

I would expect this behavior to be consistent unless I change the version of the amplify CLI.

### Reproduction steps

I am unable to reproduce consistently. The issue happens occasionally when I push an updated function to the backend

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jhockett** [comment]
@krikork is this only happening in the storage trigger? Or are you experiencing this with other functions also?

**Comment by krikork** [comment]
@jhockett this is happening across the board.

Curious if you can answer what is the lockFileVersion value is supposed be and why? When i created the project everything was set to 1 then everything got flipped to 2 then the CLI has started flipping things back to 1 as I edit function resources.

**Comment by jhockett** [comment]
Ah, this is controlled by npm: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

Closing this issue as this is not something Amplify CLI interacts with.

**Comment by krikork** [comment]
Thanks @jhockett!
