### ISSUE TITLE
multienv unintuitive, errors

### ISSUE THREAD

**Issue by Jefftopia** [aws-amplify/amplify-cli#828]
**Describe the bug**
I'm using the amplify cli with multienv.

1. `import` has no documentation for usage. But AFAIK, `import` is the appropriate way to share an auth backend between disparate projects (as opposed to one projects on multiple branches).
2. `import` requires a `--config`, but I'm not exactly sure what config should be. 
3. When I pass `team_provider_info.json` to `--config`, amplify cli errors. When I pass `./.config/*` to `--config`, amplify cli errors. When I pass any file within the `./.config` directory, the cli errors.

**To Reproduce**
1. Clone amplify project A
2. Clone project B. B will have the same backend as A.
3. `$ amplify env import --name <NAME> --config <PATH-TO-JSON-FILES-IN_A>`.
4. See error below

>You must pass in the configs of the environment in an object format using the --config flag

**Expected behavior**
Ideally, no error! ;-)

How `import` is supposed to work? What _is_ `--config`? Is `import` broken? If not, what do I need to pass it? _How_ should I pass what needs passing?

**Desktop (please complete the following information):**
 - macOS High Sierra
 - Node 9.5.0
 - Amplify CLI 0.2.1-multienv.42 (from `amplify --version`

**Additional context**
Project A's amplify stack has been setup with `init`, and it has been pushed with `amplify push`.

**Edit/Update** 
I made some progress by passing the actual flattened JSON string to `--config`. Still figuring out what next...

**Comment by kaustavghosh06** [comment]
@Jefftopia You could take a look at https://github.com/aws-amplify/amplify-cli/blob/multienv/packages/amplify-cli/sample-headless-scripts/headless_add_external_env.sh for an example of the import command. We're working on the documentation for these commands. Sorry for the confusion.

**Comment by Jefftopia** [comment]
@kaustavghosh06 Perfect, thanks for that example.
