### ISSUE TITLE
Is aws amplify stable enough for production?

### ISSUE THREAD

**Issue by FemkeBuijs** [aws-amplify/amplify-cli#829]
I have read many github issues and stackoverflow question about amplify and the feature requests/bugs related to it, and most answers included 'we are still working on it' (clear many to many relationships, unique graphql fields etc). Some workarounds given were not usable for production environments (e.g. delete Stack when "Error: Only one resolver is allowed per field")

I am wondering, is AWS Amplify with GraphQL stable enough to use it in production of an app that will reach thousands of users, and heavily relies on a relational database (many-to-many relations)?

**Comment by kaustavghosh06** [comment]
Yes, Amplify is stable, however it’s an Open Source Project and we operate in the open with the open-source community, who help us fix issues and also contribute on major features. We highly encourage you to submit bug fixes and PR’s for features when and where you encounter it.
