### ISSUE TITLE
Ability to hide some fields in the model from the get/search queries

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#8311]
### Is this related to another service?

AWS APPSYNC

### Describe the feature you'd like to request

Can we have a way to do something like:

```gql
type MyModel
  @model
  @searchable
  @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: groups, groups: ["headOffice"], operations: [create, update] }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  someField: String @hidden
}
```

Notice the `@hidden` directive, it indicates that this field SHOULD NOT be included in the `get/search` queries but should still be included in `update/create` mutations.

### Describe the solution you'd like

See above

### Describe alternatives you've considered

Can't find any alternatives.

### Additional context

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by marcvberg** [comment]
Hi @aprilmintacpineda,

Could you describe your use case for us? One option to prevent unwanted reading of a given field would be to set up field auth rules for that if you want to restrict it. Here's a link to our documentation https://docs.amplify.aws/cli/graphql-transformer/auth/#field-level-authorization

**Comment by aprilmintacpineda** [comment]
Nice, the field level authorization will do the job. Thanks!
