### ISSUE TITLE
Graviton2 Lambda Functions

### ISSUE THREAD

**Issue by ahansson89** [aws-amplify/amplify-cli#8315]
What's the Cloudformation flag for using Graviton2 Lambda functions?

There is no reference in the announcement, nor could I find it in the AWS docs.

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by marcvberg** [comment]
Hi @ahansson89 looks like they probably just haven't updated their docs yet, but the [boto3 docs here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.create_function) say "Architectures" of type list, and when I tested that as an input for a CFN stack it worked with

`Architectures: ["arm64"]`
