### ISSUE TITLE
How to init an app with PowerUserAccess role?

### ISSUE THREAD

**Issue by memochou1993** [aws-amplify/amplify-cli#8318]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

How to init an app with PowerUserAccess role? Or init an app without creating IAM roles?

Does anyone have any idea? Thanks!

**Which Category is your question related to?**

Authorization

**Amplify CLI Version** 

6.1.0

**What AWS Services are you utilizing?**

amplify

**Provide additional details e.g. code snippets**

![image](https://user-images.githubusercontent.com/38420282/135429936-7facac1b-00dc-4892-9ad5-68810b61f811.png)

**Comment by marcvberg** [comment]
Hi @memochou1993, you need to have a certain level of permissions on the profile you use with the Amplify CLI, as shown here: https://docs.amplify.aws/cli/usage/iam/

I would suggest you use the Amplify Administrator Policy `AdministratorAccess-Amplify` or attach some policies to your role matching the required ones in the link above.

If you want to initialize an app without an IAM role you'll need to use static credentials for an IAM user, which will still need appropriate policies attached to give it access to perform necessary actions. You can make your own custom policy if there are some actions you know you won't need to use, but `iam:GetRole` isn't one you'll get out of
