### ISSUE TITLE
Adding Lambda Layer creates CORS issue

### ISSUE THREAD

**Issue by Mrfoofums** [aws-amplify/amplify-cli#8320]
**Please describe which feature you have a question about?**
When running `amplify update function` and adding this ARN arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-ver-0-25-0:1 following this guide here https://aws-otel.github.io/docs/getting-started/lambda#manual-steps-for-private-lambda-layers I get CORS problems.

All my endpoints are configured with CORS enabled and I've triple checked that everything works when removing the error
**Provide additional details**

**What AWS Services are you utilizing?**
Amplify, Lambda
**Provide additional details e.g. code snippets**

**Comment by Mrfoofums** [comment]
Was using 5.4.0 just upgrade to latest.

NPM

If applicable, what version of Node.js are you using?
16.4.2

Amplify CLI Version
6.1.0

What operating system are you using?
Mac latest OS

Amplify Categories
What Amplify categories are being used?

Details
Ran `amplify function update` to add the Open Telemetry Nodejs Layer extension to my test project

Describe the bug
I have 3 API's which all work fine that fetch data from dummy endpoints over the internet like placeholder json. When adding the layer I suddenly get CORS issues on every outbound request.

Expected behavior
Adding the layer doesn't stop my lambdas from executing, at a minimum

Reproduction steps
1) Create an amplify project with a nodejs lambda
2) Add this layer extension which should generate telemetry. arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-ver-0-25-0:1

Details here https://aws-otel.github.io/docs/getting-started/lambda#manual-steps-for-private-lambda-layers

Will running the exact steps below in an empty directory create an Amplify project that demonstrates the bug behavior?
Yes




Log output
```Access to XMLHttpRequest at 'https://z4u9t1adte.execute-api.us-east-1.amazonaws.com/dev/people' from origin 'https://main.ddasnp6c9k57f.amplifyapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

Include any relevant log output under:

~/.amplify/logs/amplify-cli-<issue-date>.log
Be sure to remove any sensitive data.

<details>

```
# Put your logs below this line


```

</details>

That's it

**Comment by josefaidt** [comment]
Hey @Mrfoofums :wave: thanks for including those details! Are you seeing any errors in the Lambda's logs? Or do you see a response body attached to the errored response? There is currently an [open feature request to enable CORS for errored responses](https://github.com/aws-amplify/amplify-cli/issues/5183), which may be causing confusion here.

**Comment by Mrfoofums** [comment]
Ah, good call.  It looks like the environment variable I set for a custom collector config isn't working correctly.

Here is the log:
```
021-09-30T17:33:04.787-04:00 | goroutine 1 [running]:
-- | --
  | 2021-09-30T17:33:04.787-04:00Copymain.NewCollector({0xc00020e2d0, 0x0, 0xc00020e450, 0x0}) | main.NewCollector({0xc00020e2d0, 0x0, 0xc00020e450, 0x0})
  | 2021-09-30T17:33:04.787-04:00Copy	github.com/open-telemetry/opentelemetry-lambda/collector/collector.go:60 +0x1ca | github.com/open-telemetry/opentelemetry-lambda/collector/collector.go:60 +0x1ca
  | 2021-09-30T17:33:04.787-04:00Copymain.main() | main.main()
  | 2021-09-30T17:33:04.787-04:00Copy	github.com/open-telemetry/opentelemetry-lambda/collector/main.go:38 +0x132 | github.com/open-telemetry/opentelemetry-lambda/collector/main.go:38 +0x132
  | 2021-09-30T17:33:04.788-04:00CopyEXTENSION	Name: collector	State: Started	Events: [] | EXTENSION Name: collector State: Started Events: []
  | 2021-09-30T17:33:04.910-04:00CopySTART RequestId: 209d7e98-e6ec-4a24-94cf-68954e21a6bb Version: $LATEST | START RequestId: 209d7e98-e6ec-4a24-94cf-68954e21a6bb Version: $LATEST
  | 2021-09-30T17:33:07.469-04:00Copy2021/09/30 21:33:07 [collector] Launching OpenTelemetry Lambda extension, version:  v0.1.0 | 2021/09/30 21:33:07 [collector] Launching OpenTelemetry Lambda extension, version: v0.1.0
  | 2021-09-30T17:33:07.469-04:00Copy2021/09/30 21:33:07 Reading AOT config from file: /opt/config.yaml failed. | 2021/09/30 21:33:07 Reading AOT config from file: /opt/config.yaml failed.
  | 2021-09-30T17:33:07.489-04:00Copypanic: Cannot load Collector config. | panic: Cannot load Collector config.
```

So my question is, where would I put the collector config so that it is findable by the layer? I Currently have the environemtn vairable `OPENTELEMETRY_COLLECTOR_CONFIG_FILE=\opt\config.yaml`

But apparently that is not the correct folder. My project structure looks like so:

<img width="246" alt="Screen Shot 2021-10-01 at 1 21 08 PM" src="https://user-images.githubusercontent.com/5214037/135661676-2640520a-9647-4dad-9a2d-9dcc20d01879.png">

**Comment by josefaidt** [comment]
> So my question is, where would I put the collector config so that it is findable by the layer? I Currently have the environemtn vairable OPENTELEMETRY_COLLECTOR_CONFIG_FILE=\opt\config.yaml

`/opt` will work for the layer itself, but not for the function. All files in `src/` will be zipped up in `dist/`, therefore we should be able to add that config file to `src/`, but it will only be accessible in that Lambda itself. I would also suggest updating the path to use forward slashes `./config.yaml`.

Do you own the layer, and is it possible to include the config file in with the layer itself?

**Comment by josefaidt** [comment]
> but it will only be accessible in that Lambda itself.

I may have spoke too soon and it may be able to be read by the Lambda. I'm walking through this use case now

**Comment by Mrfoofums** [comment]
I don't own the layer, this is actually an extension provided by AWS. 

I'm looking at this here :

`To customize the collector configuration, add a configuration yaml file to your function code. Once the file has been deployed with a Lambda function, create an environment variable on your Lambda function OPENTELEMETRY_COLLECTOR_CONFIG_FILE and set it to /var/task/*<path/<to>/<filename>*. This will tell the extension where to find the collector configuration.`

**Comment by josefaidt** [comment]
Ahh okay I was mistaken. We can add `config.yaml` to our function's `src/` directory, then run `amplify update function` to add the env var, `OPENTELEMETRY_COLLECTOR_CONFIG_FILE` to point to `/var/task/config.yaml` 
![image](https://user-images.githubusercontent.com/5033303/135666962-06e6df2a-bde1-478e-91f1-f6514444e986.png)

And if we test the execution we can see the layer is successfully reading the config file, despite the errors in the config (I copied the first example from that link)
![image](https://user-images.githubusercontent.com/5033303/135667157-0102729d-3e9e-4271-9b6a-f48de682610d.png)

**Comment by Mrfoofums** [comment]
That did the trick. So I'll just need to deploy this config with every function it seems then unfortunately but thanks for solving my problem!

**Comment by josefaidt** [comment]
@Mrfoofums just ran through another scenario, we can actually add another Lambda Layer to host the config.yaml file and just be sure to set the env var on each of the functions with the proper route: `/opt/config.yaml`. This way you won't have to manage the same file in several different directories 🙂 
![image](https://user-images.githubusercontent.com/5033303/135679146-d9dbd535-251f-41e6-baee-75c3016dbf80.png)

**Comment by Mrfoofums** [comment]
This is exceptionally helpful, thanks!
