### ISSUE TITLE
Amplify CLI not syncing hosting

### ISSUE THREAD

**Issue by nrmilstein** [aws-amplify/amplify-cli#8322]
Hi, I'm having continuing problems with my amplify configuration (continued from [#2275](https://github.com/aws-amplify/amplify-console/issues/2275)). My App ID is d51x1p5vho0k and my region is us-east-2.

I have two environments: dev and prod. According to the console, both have frontend hosting.

When I `amplify env checkout prod` and run `amplify status`, it wants to create hosting (even though it already exists on the console).  If I `amplify push`, it fails, saying "Invalid request provided: Failed to create branch. The branch prod already exists for the app d51x1p5vho0k".

If I `amplify pull` instead, it removes hosting and states I do not have it on `amplify status`. If I then `amplify env checkout dev` and `amplify status`, it says I've deleted hosting and wants to push that. If I then `amplify pull`, it reverts to saying I have hosting.

How can this be resolved? It appears my CLI cannot recognize the hosting on the prod branch. I created this hosting via the console last week, but I was under the impression it would then appear in the CLI.

I have backend auth on the prod branch that I cannot lose; otherwise I would just recreate the environment. I cannot find a way on the console to delete just the `prod` hosting, in which case I would try recreating it via CLI.

**Comment by nrmilstein** [comment]
Thanks. I'm on 6.1.0.

**Comment by josefaidt** [comment]
Hey @nrmilstein :wave: thanks for raising this and apologies for the delay! Can you walk me through how you set up hosting via the console? Was this done from the Amplify Console > your app > "Frontend Environments" > connect to source control?

**Comment by nrmilstein** [comment]
Hi, we originally setup everything via the CLI: `amplify init`, `amplify add hosting`, and eventually `amplify env add prod`.

Then, 3 weeks ago, I was suddenly unable to `amplify publish` in the prod environment: "Deployment file has not been uploaded, please make sure you uploaded the deployment file prior to invoke this api"

The next day, I tried to resolve this error by `amplify remove hosting` on the prod branch, and then (after pushing) re-adding it via `amplify add hosting`. This would give me "You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches."

Needing to bring our production hosting back online, I clicked Amplify console > your app> "Frontend Environments" > "Add environment" to re-create a prod frontend environment via the console (our app has never been connected to source control, we always manually deploy via `amplify push/publish`).

This somewhat worked, and we can now deploy on prod and dev via zip upload. However, the CLI acts as though it knows nothing about the frontend prod hosting (as explained above).

I assume that you cannot mix adding hosting via the CLI and via the console, which is what we did in the face of the errors. So I would assume the solution is to remove the frontend hosting via the console, then re-add it via the CLI `amplify remove hosting`. I was going to try this at some point, but I expect the same error as before: "You have already connected branches to your Amplify Console app. Please visit the Amplify Console to manage your branches."

**Comment by josefaidt** [comment]
Hey @nrmilstein thanks for clarifying. Looking at the files it did appear that env would work, though I also saw the prod env lacked the information the dev env has for hosting. I was initially trying to see if we could surgically link the existing hosting that you've set up manually with the local project files, however the process is very involved and error prone. Despite the circumstances I believe the proper course of action would be to remove the hosting set up manually for prod, then add from the CLI. Though before attempting the change, please ensure the CLI is correctly showing no hosting resources in the prod env locally. When the prod env is checked out, we can also verify the contents of files in `#current-cloud-backend` do not show hosting details (this is most likely what was previously stopping us from re-adding hosting originally)

**Comment by nrmilstein** [comment]
I don't believe so, we hadn't deployed for a couple weeks at that point.

**Comment by josefaidt** [comment]
Hey @nrmilstein thanks for clarifying. I am glad to hear you're back up and running, and given the issue has now been resolved I'll close this issue. Though if you come across this again during a later push please reply back to this thread or create a new issue and we can investigate further.

**Comment by nrmilstein** [comment]
Great, thanks for all your help!
