### ISSUE TITLE
Toggle off hidden input for Secret Add / Update at CLI.

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#8324]
### Is this related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

I'd like to be able to see what I put into the Secret value when configuring at the command line. It would be nice if I could toggle this at runtime so I can see to confirm what I put in is the correct string when I configure it or keep it hidden if choose.

### Describe the solution you'd like

At runtime, in the function add or update, when choosing add or update secret, ask if you'd like to show the secret when entered and default to N. This keeps the current default behavior and lets me toggle it when I want but not when I don't. Also no surprises if you set it at the project level and forget.

### Describe alternatives you've considered

A project level toggle, could cause problems if you forget or share with a team. Another option is to add a validation and not ever accept empty values. This might be the lesser evil from a security perspective. I'd accept either solution.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by marcvberg** [comment]
Hi @ryanhollander,

We can't show what text is in the response in the terminal due to security concerns, but we will add this as a feature request with validation to check for cases such as empty input.

**Comment by renebrandel** [comment]
Hi @ryanhollander - thanks for suggesting this feedback! Unfortunately, we will not be able to enable this feature after reviewing with our Application Security team, therefore I'm closing this issue for now. Unless there's significant interest for this, we'll leave this issue as closed. Feel free to @-mention me anytime to discuss further.
