### ISSUE TITLE
Why does Amplify put -blog next to hosting bucket name

### ISSUE THREAD

**Issue by ChristianChiarulli** [aws-amplify/amplify-cli#833]
** Which Category is your question related to? **

hosting bucket name

** What AWS Services are you utilizing? **

AWS Amplify
S3 Bucket
Route53

** Provide additional details e.g. code snippets **

I am using this to publish a gatsby blog

I can't connect the s3 bucket to route53 because the need to be the same name but I can't make the "-blog" go away.

You can follow this tutorial to reproduce 

https://www.gatsbyjs.org/blog/2018-08-24-gatsby-aws-hosting/

**Comment by yuth** [comment]
@ChristianChiarulli Are you using @multienv version of amplify-cli? If so did you name the environment `blog`?

**Comment by ChristianChiarulli** [comment]
Yes I am using multienv, so that explains the blog. Is there anyway to make sure “-environment” doesn’t appear?

**Comment by yuth** [comment]
It is recommended to use s3 with cloud front for hosting.

> Is there anyway to make sure “-environment” doesn’t appear?

If you set the environment name to `NONE` it should stop appending the env name to the S3 Bucket

**Comment by ChristianChiarulli** [comment]
I can’t use Capital letters for the environment name and lowercase “none” was still appended

**Comment by yuth** [comment]
Oh.. we recently had to limit the env name to only have small case letters to support all the services that we support in CLI. 

Like I mentioned earlier, you should be using `cloudfront` for hosting for production traffic. With the cloudfront, you should be able to connect your domain without any problem.

We will investigate if we could drop the prefix name for bucket for hosting.

**Comment by ChristianChiarulli** [comment]
Thanks anyway I was able to get it up through cloudfront. Sorry for the general ignorance I'm new to web development and AWS.

**Comment by yuth** [comment]
No problem. We probably could improve our documentations. We are open for contribution to our [documentation](https://github.com/aws-amplify/docs/) repo

**Comment by codepreneur** [comment]
@yuth this is a big issue for me, since in order for all my non-www requests to be redirected to root domain (or vice versa) I need to create two buckets `example.com` and `www.example.com` then put two cloudfront web distributions in front of them and (A) Alias them on route53 and this `example.com-dev` is ruining DNS for me big time, since for all of my other sites, I create  these buckets manually and can set their name exactly as domain names.

**Comment by codepreneur** [comment]
@yuth @UnleashedMind the way I solve this problem right now is not ideal:

```
amplify add hosting
```

and then go and modify `template.json`  -> `Fn::Join` to not append environment to bucket name and only then 
```
amplify push
amplify publish
```
and then all the redirects work perfectly (like I described in previous comment)

so it would be nice to be able to do
```
amplify add hosting -bucketName example.com
```

but manually editing `template.json` works too I guess

**Comment by lakshmi-kannan** [comment]
I ran into this issue today. There is no way to setup the bucket name to a domain name I want and just use Route53 + S3 bucket. I am in early phases of app development and I don't need cloudfront at all. I am now forced to use cloudfront just to get a dev site with a nice CNAME. 

It would be nice for the CLI to allow users to setup a cloudfront distribution and a custom cname if that's the recommended approach. 

Interestingly, amplify push & publish did not register the app in the AWS console. When I select Amplify there, I do not see the app I pushed from CLI. I verified I used the right profile etc. I wasted an hour reading docs, figuring out the domain name restriction on S3 bucket and finally got hold of this issue. Not a good UX I'd say :).

**Comment by pairmix** [comment]
what about this issue ?

**Comment by deviant32** [comment]
I am having the same issue...

**Comment by pairmix** [comment]
i finally have to give up amplify. i'm unable to let it work properly because of this issue.
Google Firebase works like a charm.
