### ISSUE TITLE
appsync apikey expired, can't create new one

### ISSUE THREAD

**Issue by kenmckaba** [aws-amplify/amplify-cli#8341]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
N/A

**Amplify CLI Version** 
amplify 6.1.0

**What AWS Services are you utilizing?**
appsync lambda api-gateway rekognition

**Provide additional details e.g. code snippets**
I have an appsync api using apikey- 'rlafeature'. My lambda, 'rlaapi', depends on that appsync api and makes calls to it.

The appsync apikey expired. I created a new one in appsync console. Now pull creates files with the old apikey.

Amplify push has this error:
UPDATE_FAILED               functionXXXXX         AWS::CloudFormation::Stack Fri Oct 01 2021 12:06:49 GMT-0700 (Pacific Daylight Time) Output 'GraphQLAPIKeyOutput' not found in stack 'arn:aws:cloudformation:us-east-1:XXXXXX:stack/amplify-XXXXX'

**Comment by josefaidt** [comment]
Hey @kenmckaba :wave: thanks for raising this! To create a new API key please reference this [documentation page](https://docs.amplify.aws/cli/graphql-transformer/config-params/#createapikey)

> CreateAPIKey takes value of either 1 or 0.
>
> It gives you the mechanism to rotate the API Key, in scenarios such as to handle API Key expiration.
>
> Follow these two steps when you need to rotate an API Key
>
> - Delete the existing API key by setting `CreateAPIKey` to 0 in the `amplify/backend/api/<apiName>/parameters.json` file and execute amplify push.
> - Create a new API key by setting `CreateAPIKey` to 1 in the `amplify/backend/api/<apiName>/parameters.json` file and execute amplify push.

**Comment by kenmckaba** [comment]
We have worked around the problem and switched to userpools instead of apikeys, so we won't try to completely understand the apikey problem or a solution.

Thanks for your generous support!

**Comment by josefaidt** [comment]
Hey no worries @kenmckaba ! Glad to hear you've found a suitable solution and are back up and running 🙂 . Closing issue
