### ISSUE TITLE
Default editor is shown as `undefined` after project initialization

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#8356]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

v6.1.1

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

Default editor choice is shown as `undefined` and developers are prompted to choose an editor upon choosing to edit a newly-created resource. In the example shown below, project files are created as expected though without the editor-specific settings file (in this case, `.vscode/settings.json`). This does not have an impact other than requiring the developer to choose an editor upon choosing to edit a newly-created resource.

**NOTE:** after creating a resource (function), choosing to edit, and selecting the editor the editor-specific settings file is created

```shell
> amplify init -y
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
Note: It is recommended to run this command from the root of your app directory
The following configuration will be applied:

Project information
| Name: test
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

Using default provider  awscloudformation
```

If we then run `amplify configure project` we see `undefined` for the default editor:

```shell
> amplify configure project
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.

Project information
| Name: test
| Environment: dev
| Default editor: undefined
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

AWS Profile setting
| Selected profile: default

Advanced: Container-based deployments
| Leverage container-based deployments: No
```

Example prompt showcasing the additional prompt for selecting an editor when creating new resources:

```shell
> amplify add function
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: teste2662eb6
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? Yes
? Choose your default editor: Visual Studio Code
Edit the file in your editor: /Users/josef/Documents/projects/aws-amplify/reproductions/test/amplify/backend/function/teste2662eb6/src/index.js
? Press enter to continue 
Successfully added resource teste2662eb6 locally.
```

### Expected behavior

- CLI creates editor-specific settings files on init
- CLI retains editor selections and does not subsequently prompt for editor upon resource creation and choice to edit

### Reproduction steps

1. `amplify init -y`
2. `amplify configure project`
3. Observe missing editor-specific settings file and `undefined` for default editor

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment]
Can you still reproduce this? I cannot

**Comment by josefaidt** [comment]
Hey @johnpc yes I can still reproduce. After init it shows undefined but if we run through `amplify configure project` again and set the editor it persists. It will also persist if adding a resource and selecting the editor, which I'm assuming is prompting us for the editor because it is initially undefined. The `defaultEditor` is not set in `amplify/.config/local-env-info.json` after initialization

**Comment by flozender** [comment]
Hi, can I work on this? Thanks!
