### ISSUE TITLE
Amplify CLI for amplify add auth does not support App Client Secret

### ISSUE THREAD

**Issue by ajayvohra2005** [aws-amplify/amplify-cli#8369]
### Is this related to a new or existing Amplify category?

auth

### Describe the feature you'd like to request

Currently, there is no mechanism to use Amplify CLI ```amplify add auth``` command and input an option to create Cognito User Pool App Clients with an App Secret. 

### Describe the solution you'd like

Amplify CLI input for ```amplify add auth``` should ask the user if Cognito User Pool App Client should be created with an App Client Secret.

### Describe alternatives you've considered

To my knowledge, there are no current alternatives available.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @ajayvohra2005 :wave: this is now possible with the use of [resource overrides](https://docs.amplify.aws/cli/auth/override/)! Using the following auth override we will be able to generate client secrets for the native and web clients

```ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPoolClient.generateSecret = true
  resources.userPoolClientWeb.generateSecret = true
}
```

<img width="413" alt="image" src="https://user-images.githubusercontent.com/5033303/183509488-c2964455-bd7c-46f9-bb8c-a91de70fb950.png">

Closing 🙂
