### ISSUE TITLE
lambda needs update state is buggy in `amplify ls`

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-cli#838]
**Describe the bug**

I am finding that my lambda functions never show as up-to-date with the amplify CLI (using amplify 0.2.1-multienv.35)

**To Reproduce**

1. run `amplify push`
2. after it completes run `amplify ls`
3. the functions are shown as needing updating

I, unfortunately, do not have a canned example of this, it’s in my private repo.

**Expected behavior**

After running `amplify push`, if you run `amplify ls` it should show everything as up-to-date.

**Screenshots**

![screen shot 2019-02-07 at 6 09 56 pm](https://user-images.githubusercontent.com/136651/52449064-f366af00-2b03-11e9-88e0-3823d21bb892.png)

![screen shot 2019-02-07 at 6 10 26 pm](https://user-images.githubusercontent.com/136651/52449068-f5c90900-2b03-11e9-9431-009abf24749c.png)

video https://www.dropbox.com/s/lbt1zx66tv06vkn/amplify-push-still-says-update.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.6
 - Version: amplify 0.2.1-multienv.35

**Comment by kaustavghosh06** [comment]
@mrcoles We released a fix for this. Let me know if you're still seeing this. Thanks!
