### ISSUE TITLE
CLI attempting to update container secrets for non-initial deploy

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#8384]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

6.1.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-api/src/provider-utils/awscloudformation/utils/containers-artifacts.ts#L204-L209

This code results in CLI setting `isInitialDeploy` to true, even when it is **not** the initial deploy

The Array `newContainersName` contains all of the named containers in docker-compose.yaml

However, the Set `currentContainersSet` only contains the name of containers which have a build spec, not the names of containers that are using existing images,

e.g. this service will be missing from `currentContainersSet`

```yml
xray:
    image: amazon/aws-xray-daemon
    ports:
      - "2000:2000/udp"
```

This causes CLI to attempt to update secrets, which does not work in an environment where the secrets do not exist on disk (e.g. CI/CD), causing this error when pushing:

```
Error(s) in secret file(s):
Secret file "../secrets/.secret-x" can't be read.
Secret file "../secrets/.secret-y" can't be read.
Secret file "../secrets/.secret-z" can't be read.
```

### Expected behavior

The bug is not present in CLI code

### Reproduction steps

1. Execute the code block linked to above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mattfysh** [comment]
Still having this issue. At the moment, there are a number of bugs related to Container Secrets, and I have to do all deploys manually, from my local machine. It would be great if these could be fixed soon so I can go back to using GitHub Actions to deploy

**Comment by mattfysh** [comment]
Ok, I think I'm done with Amplify... I've even pointed out the exact lines of code that are causing this bug... and here we are, 4 months later, and still no movement.

The Amplify team should drop Serverless Containers from your offering immediately -- you clearly do not have the capacity or embedded knowledge to maintain it.

**Comment by sundersc** [comment]
@mattfysh - Apologies for the delay in getting back to you. I completely understand your frustration. This issue definitely deserved a much higher priority.	

We are trying to address this issue as soon as possible. PR https://github.com/aws-amplify/amplify-cli/pull/9556 should fix this behavior once merged and released.
