### ISSUE TITLE
I can't do an amplify push

### ISSUE THREAD

**Issue by DarkestMisery** [aws-amplify/amplify-cli#8394]
Hi!, I have a little issue, I did an 'amplify add codegen --appId XXXXXXXXXXXXXXXXXX', then I tried to do an 'amplify push' but it didn't update my amplify publish domain and I haven't credentials in the publish domain. I just want to push my api to the amplify settings in the domain.

**Provide additional details**
I always do an amplify status to look what is the actual status of my app:

    Current Environment: dev
    
 Category | Resource name | Operation | Provider plugin 
------------- | --------------------- | ------------- | ------------------- 
 Api | api_resource_name | Create | 
 Auth | auth_resource_name | No Change | awscloudformation 

Then, I do an amplify push:

✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
Category | Resource name | Operation | Provider plugin 
------------- | --------------------- | ------------- | ------------------- 
 Api | api_resource_name | Create | 
 Auth | auth_resource_name | No Change | awscloudformation 

? Are you sure you want to continue? Yes
✔ All resources are updated in the cloud

Then, I do again the amplify status and it didn't change.

Thanks for your attention. :)

**Comment by yuth** [comment]
@DarkestMisery When you do `amplify add codegen --appId XXXXXXXXXXXXXXXXXX`, amplify CLI uses this information to download the GraphQL Schema from the AppSync API to generate code. What do you mean by 
>  just want to push my api to the amplify settings in the domain.

If the issue is the status showing `Create` for the API, then it should change when there is an actual change that needs deployment. When its a codegen external API, and no other changes, Amplify CLI see any changes that needs deployment and then does not update the `#current-cloud-backend` folder

**Comment by DarkestMisery** [comment]
Hi!, thanks for answer.

Yes, when I do `amplify add codegen --appId XXXXXXXXXXXXXXXXXX` it generates the GraphQL from the API and the status set on `Create` but when I do `amplify push`, It doesn't update correctly, as you say.

My localhost works fine, all the backend config is doing great but the publish domain doesn't works, it responses a 404 Error `No grapql endpoint provided` and the problem is caused because the bad update.

**Comment by yuth** [comment]
could you try removing the `codegen` and adding it again. When an API is added with `amplify codegen add --apiId XXXXXXXXXX`, it should not show it as create status. You can remove the api by running `amplify api remove` and choosing the API.
