### ISSUE TITLE
Prevent Public users from "list" a database table in GraphQL

### ISSUE THREAD

**Issue by dbeck121** [aws-amplify/amplify-cli#8395]
**Which Category is your question related to?**
GraphQl API Authorisations

**Amplify CLI Version** 
6.2.1

**What AWS Services are you utilizing?**
GraphQL with App Sync

**Provide additional details e.g. code snippets**

Hi,
I created my database with amplify and it works pretty good. Unfortunately I can not find out how to solve one problem that I have. I searched everywhere but I did not found a solution.

Let this be the database description

`type Customer @model 
@auth(rules: [
   {allow: public, , operations: [read,create,update]},
   {allow: groups, groups: ["admin","partner"] }])  
{

   id: ID!

   firstName: String

   lastName: String

   email: String

   phone: String

}`

I want that public can access Customer elements for which they know the ID. That works fine like this. Unfortunately they can also list the Customer table what I do not want. Is there a way to forbid "list" for certain users? 

It would be great if someone could help here.

BR

**Comment by dbeck121** [comment]
Hi @yuth,

that  helps a lot. I found now the following in the docu:
https://docs.amplify.aws/cli/graphql-transformer/auth/#definition

`# The following objects are deprecated. It is encouraged to use ModelOperations.
enum ModelQuery { get list }
enum ModelMutation { create update delete }`

Is there any information how long they are safe to use or is ther a replacement? The ModelOperations lack the "list" feature.

BR and thank you again. That solved a lot.

**Comment by yuth** [comment]
When there is no auth added to a field, we fall back to auth rules of the type as to prevent any accidental information leak.

**Comment by dbeck121** [comment]
Hi,

seems with the new version this is not possible anymore?

`enum ModelQuery { get list }
enum ModelMutation { create update delete }`

does not exist in the docs.

https://docs.amplify.aws/cli/graphql/authorization-rules/

Is there a new version to prevent users from doing list queries? I use it in my project and  the use case that users might read specific elements but not list all available sounds pretty common to me.

BR and thanks in advance
