### ISSUE TITLE
Setting property to nil via generated Swift api is ignored

### ISSUE THREAD

**Issue by peterfennema** [aws-amplify/amplify-cli#840]
**Describe the bug**
I use Amplify iOS with GraphQL Transform and Codegen to generate a Swift api for AppSync.
In the generated code I set a property to nil. After applying a mutation nothing happens, the previous value is not erased in DynamoDB.

**To Reproduce**

1. Given the following schema

```
type User @model   
{
  id: ID!
  name: String
   ...
}

```
2. Given the current value for `name` in DynamoDB is `Peter`

3. Given the following Swift code for a UserMutation

```
let input = UpdateUserInput(
    id: "someId",
    name: nil, 
    ...
)
let updateUserMutation = UpdateUserMutation(input: input)
...
```

4. After executing the mutation the existing value for `name` in DynamoDB still is `Peter`

**Expected behavior**
I would expect the value in DynamoDB to be `null`, or the `name` property to be removed.

**Comment by palpatim** [comment]
This seems to be a problem with the AppSync SDK, rather than CodeGen--it looks like the SDK isn't transmitting fields with `nil` values as part of the mutation payload. I'm investigating from the SDK side.

**Comment by palpatim** [comment]
I'm tracking this on https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/180. @yuth, please feel free to close this bug in favor of the AppSync iOS issue.
