### ISSUE TITLE
Release Provisioned Resources

### ISSUE THREAD

**Issue by OrangeDrangon** [aws-amplify/amplify-cli#841]
** Which Category is your question related to? **
CLI General Usage

** What AWS Services are you utilizing? **
Auth

** Provide additional details e.g. code snippets **
Is there a command to release all resources that were provisioned by the CLI automatically for this project.

**Comment by yuth** [comment]
Amplify supports `remove` command on all the resources. So you could run
```
$ amplify auth remove 
$ amplify push
```

You can run delete command to delete all the resources provisioned by the CLI. Only thing that remains is the deployment bucket which you will have to delete manually 
```
$ amplify delete
```

**Comment by OrangeDrangon** [comment]
Thanks
