### ISSUE TITLE
Unable to restrict API access to REST route with imported auth

### ISSUE THREAD

**Issue by acusti** [aws-amplify/amplify-cli#8414]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

6.3.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

add, update

### Describe the bug

when i try to create or update a REST API path and i choose to “Restrict API access” to “Authenticated users only”, then amplify push, if i try to hit that route with the `Authorization` header from the current session’s id token as [described here](https://docs.amplify.aws/lib/restapi/authz/q/platform/js/#cognito-user-pools-authorization), i get a 403 response with the error type `IncompleteSignatureException`:

```
content-length: 3096
content-type: application/json
date: Sun, 10 Oct 2021 17:15:19 GMT
via: 1.1 ea7c4b0407882327307bae4ed233d142.cloudfront.net (CloudFront)
x-amz-apigw-id: HAHiNGb8IAMF-Yw=
x-amz-cf-id: Y7NgC6ymAQWAPs_oX1UHp8E1cY185EonYRy5WjhQLzAOQ1O0W4pDjg==
x-amz-cf-pop: SFO5-C3
x-amzn-errortype: IncompleteSignatureException
x-amzn-requestid: d6957f4c-6084-4fad-92c6-c0f40427c961
x-cache: Error from cloudfront
```

the code triggering the request:
```js
                const headers = {
                    Authorization: `Bearer ${(await Auth.currentSession())
                        .getIdToken()
                        .getJwtToken()}`,
                };
                const options = { headers };
                const result = await API.get(apiName, '/the-api-path', options);
```

the API route is a GET route only so i selected `read` when prompted “What kind of access do you want for Authenticated users?” if i choose to restrict API access to “Authenticated and Guest users” and enable “read” for both, the CLI gives me an error:

```
? Restrict API access Yes
? Who should have access? Authenticated and Guest users
? What kind of access do you want for Authenticated users? read
? What kind of access do you want for Guest users? read
Auth configuration is required to allow unauthenticated users, but it is not configured properly.
Error: Auth configuration is required to allow unauthenticated users, but it is not configured properly.
    at ensureAuth (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:329:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async askPrivacy (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:276:17)
    at async askPaths (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:426:25)
    at async pathFlow (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/service-walkthroughs/apigw-walkthrough.js:156:25)
    at async Object.legacyUpdateResource (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/provider-utils/awscloudformation/legacy-update-resource.js:16:20)
    at async Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/lib/index.js:166:5)
```

this makes me suspect that the issue is related to having imported `auth` into the project. for auth, i have a cognito user pool with a couple of user groups and an identity pool that has unauthenticated and authenticated roles configured.

### Expected behavior

i expected the GET request using the cognito id token JWT `Authorization` header to succeed and not cause a 403 `IncompleteSignatureException` response.

### Reproduction steps

1. set up passwordless auth with cognito using these steps: https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/
2. use `amplify import auth` to add the existing cognito user pool
3. `amplify add api`, choose REST, create a path, choose to restrict API access to authenticated users, choose “read”, test the created API passing a valid cognito id JWT as the `Authorization` header

### Additional information

i was hoping that some of the info in #8019 would help me, especially once i read https://github.com/aws-amplify/amplify-cli/issues/8019#issuecomment-907940339, because i am also using cognito user groups. however, i confirmed that my user group role has the amplify policy attached to it (named `amplify-xxxxxx-prod-000000-APIGatewayAuthStack-0AAA000AA0A0-PolicyAPIGWA…` [i modified the ids before pasting]), so that doesn’t seem to be the issue. i tried also adding another amplify policy to the user group role in IAM and still the same response.

last note: i looked up the specific `x-amzn-ErrorType` in the [troubleshooting 403 errors from API Gateway docs](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-troubleshoot-403-forbidden/) and found that the explanation is “A request with an "Authorization" header is sent to an API resource path that doesn't exist.” it’s hard for me to imagine how that applies here, however, because the API resource path exists; it shows up in the API Gateway console and the route + lambda work fine when i choose to not “restrict API access” in the amplify CLI.

**Comment by acusti** [comment]
quick update: i added a new REST API route this morning via amplify and made sure to set “Restrict API access” to `no`, and after i ran `amplify push`, i went to add the cognito authorizer to the new route, but discovered that the cognito authorizer i had manually added was gone. i created a new one and added it to all the same protected routes again, but it feels like this might be something that needs to live in my infrastucture-as-code (CloudFormation templates or whatever) so it’s no longer a security liability.

**Comment by josefaidt** [comment]
Hey @acusti :wave: apologies for the delay here! Are you still experiencing this issue?

**Comment by acusti** [comment]
hi @josefaidt, thanks for checking in! i am still experiencing this issue, but it actually doesn't have anything to do with imported auth. i rebuilt my amplify app using the built-in amplify auth and i still am unable to restrict API access to REST routes using the CLI. instead, i’ve been using the workaround specified in [this comment](https://github.com/aws-amplify/amplify-cli/issues/3390#issuecomment-1060252876) and detailed in [this gist](https://gist.github.com/evankirkiles/9de81f026a2e2c961a2b6a3d80d35519).

i am happy to have a solution that seems fairly reliable, but i am also puzzled that the CLI restrict API access functionality doesn’t work. i don’t think there’s anything unusual about my setup (built-in cognito for auth, user groups but i’ve tried specifying restrict API access rules both for authorized/guest users and for user groups and i always get the same result (403 responses). and i only want some of my REST routes to be restricted while others should be public, so i have to maintain a `Set` of `RESTRICTED_PATHS` in my override.ts that i must remember to keep up-to-date as i add and remove restricted routes to my REST API.

**Comment by sky-aqm** [comment]
+1 amplify auth does seem to be cursed
