### ISSUE TITLE
Git workflow using tags instead of branches

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#8426]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Auth, Api (GraphQL, REST and Fargate), Function, Storage (DDB)

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

v6.3.0

**What AWS Services are you utilizing?**

AppSync, ApiGateway, Fargate/ECS, Cognito, Lambda, DynamoDB

**Provide additional details e.g. code snippets**

Question about the git workflow. I release using tags not branches... if I want to push to prod using a tag that was already deployed to a pre-prod environment, is this what I need?

```
git checkout v1.0.0
amplify env checkout prod
git restore amplify
amplify push
```

So instead of using (for example) `git merge staging` I'm using `git restore amplify`

That should work, right? And do I need to commit after `amplify push`?

**Comment by josefaidt** [comment]
Hey @mattfysh :wave: when the CLI did not prompt for the secret's value, was this a new function that we merged in? After merging and running `amplify env checkout <current-env-name>` to init the new resources I just merged in, then run `amplify push` I received the following prompt:

```
> amplify push
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
? mysupersecret in 8426c0f09b53 does not have a value in this environment. Specify one now: [input is hidden] 
```

Can you describe the workflow in which it did not prompt for the missing secret value? Also if you wouldn't mind could you file a [new bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml) for the function secret issue so we can document the occurrence separately?

**Comment by mattfysh** [comment]
Hi @josefaidt - I reran the scenario with the latest version of CLI and everything worked! Thanks for a great job on this one 🪄
