### ISSUE TITLE
AppSync with Amplify

### ISSUE THREAD

**Issue by sufyanghazali** [aws-amplify/amplify-cli#8433]
**Which Specific Feature is your question related to?**

Adding API to Amplify app

**Provide additional details e.g. code snippets**
Hi, I've been trying to connect an existing appsync api to an amplify app. Everything works locally but when I run "
amplify push" to update it in the cloud, the api doesn't get pushed along with it.

**Comment by josefaidt** [comment]
Closing due to age and inactivity. @sufyanghazali if you are still experiencing this issue please file a [new issue](https://github.com/aws-amplify/amplify-cli/issues/new/choose)
