### ISSUE TITLE
Failed to get profile: Profile configuration is missing for: undefined

### ISSUE THREAD

**Issue by marlonmarcello** [aws-amplify/amplify-cli#8438]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

6.3.1

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

When trying to run `amplify init` on a project that was previously working I get the following message: `Failed to get profile: Profile configuration is missing for: undefined`.

### Expected behavior

Amplify should initialize the project.

### Reproduction steps

1. Clone repo
2. Run `amplify init`
3. Get errpr

### Log output

Output from CLI:
```
➜  amplify pull

Pre-pull status:

    Current Environment: master

┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting    │ No Change │                   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Auth     │ loschompsa3785611 │ No Change │ awscloudformation │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ loschomps         │ No Change │ awscloudformation │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Storage  │ loschompss3       │ No Change │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘

? Select the authentication method you want to use: AWS profile
Failed to get profile: Profile configuration is missing for: undefined
⠦ Fetching updates to backend environment: master from the cloud.%
```

**Comment by edwardfoyle** [comment]
@marlonmarcello can you check the contents of `<project root>/.config/local-aws-info.json`? You should see something like:
```json
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "<AWS profile name>"
  }
}
```

**Comment by edwardfoyle** [comment]
@marlonmarcello If you run `amplify pull --appId <your app id> --envName <amplify env name>` in an empty directory does it give you the option to select a profile?
