### ISSUE TITLE
GraphQL schema corrupt and can't override

### ISSUE THREAD

**Issue by harveyappleton** [aws-amplify/amplify-cli#8439]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Amplify DataStore

**Amplify CLI Version** 

6.2.0

**What AWS Services are you utilizing?**

Amplify API, DataStore, Auth

**Provide additional details e.g. code snippets**

I accidentally made a mistake in my `schema.graphql` file (added a semicolon) - but now whenever I run `amplify codegen models` then try `amplify push` I get this error. Can't seem to find anywhere in the Amplify console that I can manually fix this. Any ideas? Thanks
![image](https://user-images.githubusercontent.com/56404035/137276932-fa82e37d-6c46-484a-a664-7bbbfb2e65e3.png)

**Comment by edwardfoyle** [comment]
@harveyappleton This probably means that the syntax error somehow made it into your `#current-cloud-backend` directory. The CLI should prevent you from pushing a schema with a syntax error so if you have any repro steps for how you got into this state, we could look into implementing some extra guardrails to prevent this situation.

It can be a bit tedious to get out of this situation. Here are the steps:
1. Navigate to the S3 console in the AWS account where your project is deployed.
2. Find the deployment bucket for your project and environment. It will be named `amplify-<project name>-<amplify env>-<random number>-deployment`
3. Open up the bucket and download the `current-cloud-backend.zip` file
4. Unzip the file and fix the syntax error in `api/<api name>/schema.graphql`
5. Re-zip the directory and replace the `current-cloud-backend.zip` file in S3 with the new one
6. Run `amplify push`. Amplify will now pull down the fixed schema file when computing the pre-push status

**Comment by edwardfoyle** [comment]
@harveyappleton Can you make sure that the zip file didn't accidentally get nested inside an additional directory? This sometimes happens when right-clicking a directory and zipping it.
