### ISSUE TITLE
Pushing `auth` change resets my "App client settings"

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-cli#844]
**Describe the bug**

My app client settings (for the hosted UI) all got reset just now after doing an `amplify push` when I had changed the "userpoolClientRefreshTokenValidity" parameter in my "auth" settings.

**To Reproduce**

1. Deploy an `auth` backend
2. Configure "App client settings" in AWS Console > Cognito > User Pool > App integration > App client settings
3. Edit `./amplify/backend/auth/<authname>/parameters.json` and change "userpoolClientRefreshTokenValidity" to a different number
4. Push the changes `amplify push`
5. Go back to your "App client settings" and they’re all gone

**Expected behavior**

These values should persist or I should be able to incorporate them into my project. Is there a way to incorporate this into my cloudformation-template and also handle different environments correctly?

**Desktop (please complete the following information):**
 - Version: amplify 0.2.2-multienv.1

**Comment by kaustavghosh06** [comment]
@mrcoles Cloudformation doesn't support Hosted UI support inherently but you can use custom lambda resources to make that possible. That being said, we're actively working on hosted UI support as a part of the CLI and I'll update this thread once we have the support.

**Comment by mrcoles** [comment]
@kaustavghosh06 ok thanks! An initial MVP (at least for me) would be if it didn’t wipe existing settings (but IDK the implications of what is required to do that).

**Comment by kaustavghosh06** [comment]
With our new version of the CLI (>1.4.0), we've introduced Hosted-UI/Outh flow as a part of the CLI flow. Please feel free to check it out and re-open/comment on this issue if you see a problem with it.

Also, we've introduced the capability of not wiping custom settings in the aws_exports or awsconfiguration files.

**Comment by mrcoles** [comment]
Hey @kaustavghosh06 any recommendations on migrating from a manual setup of the hosted ui to the new one?

**Comment by kaustavghosh06** [comment]
@mrcoles You can go through the `amplify update auth` flow and fill in your exisiting domain-name which you have configured on your Cognito console.

**Comment by mrcoles** [comment]
OK, thanks, so I just have to reconfigure it then.

Also, I just put my previous setup steps in a gist in order to share what my setup process was like: https://gist.github.com/mrcoles/bce4ef171872bf80a013f0db3e7c534b  I found it to require a ton of trial and error and in the end some parts are still a little funky.

**Comment by mrcoles** [comment]
@kaustavghosh06 is `npm install -g @aws-amplify/cli@multienv` no longer the current way to have the multi-env cli?

**Comment by kaustavghosh06** [comment]
@mrcoles On Feb 11th, 2019, we merged the multienv functionalities to the master version of the CLI and discontinued the @multienv version. You can use `npm install -g @aws-amplify/cli` to install the latest version of the CLI which now has multienv capabilities.
