### ISSUE TITLE
Support specifying KMS options for DynamoDB

### ISSUE THREAD

**Issue by srgustafson8** [aws-amplify/amplify-cli#8441]
### Is this related to a new or existing Amplify category?

storage

### Is this related to another service?

DynamoDB

### Describe the feature you'd like to request

We are using Amplify for an application and have added storage in the form of Dynamo. Currently, there doesn't seem to be a way to specify the encyption settings, which default to encryption-at-rest using the [AWS owned key](https://docs.aws.amazon.com/kms/latest/developerguide/services-dynamodb.html#dynamodb-encrypt). 

This provides some issues in our setup, especially if we want to store PII or restricted data in this table. By default, our squad members assume a limited role into their accounts, which provides read-only access and a deny on `kms:Decrypt*`, preventing them from reading encrypted data without going through our privilege escalation process. Unfortunately, using the AWS owned key doesn't seem to need a KMS Decrypt operation to access the data in the table, meaning our default limited roles are able to read the data.

It would be great to be able to specify which sort of encryption you'd like to use when creating Dynamo tables from Amplify.

### Describe the solution you'd like

When adding storage via the CLI, I would like a further option that allows you to specify whether you want to use the AWS Owned key, AWS Managed key or provide an ARN for your own CMK.

### Describe alternatives you've considered

Creating the DynamoDB Table separately with the correct encryption, then importing it to Amplify would work, but then you have to manage this outside of Amplify and lose some of the DevEx around creating and managing tables in the same place as the code.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @srgustafson8 :wave: this can now be accomplished through the use of [overrides](https://docs.amplify.aws/cli/graphql/override/)! Using the following API override snippet we can override the underlying storage encryption settings:

```ts
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyApiGraphQlResourceStackTemplate) {
  resources.models['Todo'].modelDDBTable.sseSpecification = {
    sseEnabled: true,
    sseType: 'KMS',
    kmsMasterKeyId: 'ee604e14-0f56-42f9-a25c-1622b05c9c02',
  }
}
```

We can also apply this to the `storage` category:

```ts
import { AmplifyDDBResourceTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyDDBResourceTemplate) {
  resources.dynamoDBTable!.sseSpecification = {
    sseEnabled: true,
    sseType: 'KMS',
    kmsMasterKeyId: 'ee604e14-0f56-42f9-a25c-1622b05c9c02',
  }
}
```

Closing in favor of overrides approach
