### ISSUE TITLE
Create storage fails with Parameters: [KMSMasterKeyID] must have values

### ISSUE THREAD

**Issue by danielhstahl** [aws-amplify/amplify-cli#8442]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v15.14.0

### Amplify CLI Version

6.3.1

### What operating system are you using?

Ubuntu

### Amplify Categories

storage

### Amplify Commands

push

### Describe the bug

Bug exists when both pushing locally and when using an app connected to Github.  Error when creating storage: `Parameters: [KMSMasterKeyID] must have values`

![Screenshot Capture - 2021-10-14 - 10-36-32](https://user-images.githubusercontent.com/6961410/137350533-71c4ed56-511a-4606-9088-33fcc070ea9f.png)

This bug occurred on a brand new app, using an existing codebase.  

### Expected behavior

Error not to exist or a better error that explains what I need to add.

### Reproduction steps

Can't provide exact reproduction since this is a private codebase.  

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
@danielhstahl Can you provide the walkthrough options that you selected when creating the resource? Were you configuring an S3 bucket or a DynamoDB table?
