### ISSUE TITLE
Not able to push api

### ISSUE THREAD

**Issue by akash-gupt** [aws-amplify/amplify-cli#8473]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

6.1.1

### What operating system are you using?

mac

### Amplify Categories

<img width="1105" alt="Screenshot 2021-10-18 at 1 44 50 PM" src="https://user-images.githubusercontent.com/11151000/137694195-98c5f486-c09e-45d4-b74a-3d7fc3a2c829.png">
api

### Amplify Commands

push, update

### Describe the bug

i am trying to push or update api but it's not working.
<img width="1105" alt="Screenshot 2021-10-18 at 1 44 50 PM" src="https://user-images.githubusercontent.com/11151000/137694195-98c5f486-c09e-45d4-b74a-3d7fc3a2c829.png">

### Expected behavior

i should be able to push the api

### Reproduction steps

i am not sure 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

<img width="876" alt="Screenshot 2021-10-18 at 2 25 09 PM" src="https://user-images.githubusercontent.com/11151000/137700143-880053cc-d171-492c-876d-6d87bbb2f5e4.png">
</details>

**Comment by marcvberg** [comment]
Hi @akash-gupt,

There might be a JSON config file that's in a bad state - have you edited any JSON files since changing the API? In the amplify directory

**Comment by josefaidt** [comment]
Hey @akash-gupt :wave: just wanted to follow up to @marcvberg 's message and see if you were able to identify a JSON file that might have been manually edited?

**Comment by akash-gupt** [comment]
Yes i found it by making some changes on amplify cli.

**Comment by josefaidt** [comment]
Thanks for clarifying @akash-gupt! Were you able to successfully push your API after identifying the affected JSON file?

**Comment by akash-gupt** [comment]
Yes, I did.

**Comment by josefaidt** [comment]
Awesome! Glad to hear you're back up and running 🙂 

Closing issue

**Comment by akash-gupt** [comment]
Thank you.
