### ISSUE TITLE
preSignUp trigger is failing with default code

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#8506]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.5.1

### Amplify CLI Version

6.3.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

I added a lambda trigger for preSignUp through `amplify update auth`. All the boiler plate was generated correctly, I wen't ahead and did a `amplify push` and all changes wen't through as expected, however when I try to add a user I get an invocation error:

`PreSignUp failed with error callback is not a function. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: cce25d95-1cce-4541-b674-5ab08e6b0f5f; Proxy: null)`

### Expected behavior

That the trigger would work out-of-the-box.

### Reproduction steps

- Add auth
- Add lambda trigger for preSignUp through wizard
- Push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2021-10-20T18:11:39.063Z	b0145221-ba5d-4d31-b631-331e7447621c	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "callback is not a function",
    "stack": [
        "TypeError: callback is not a function",
        "    at Object.exports.handler (/var/task/custom.js:5:3)",
        "    at /var/task/index.js:37:50",
        "    at Array.map (<anonymous>)",
        "    at Runtime.exports.handler (/var/task/index.js:37:29)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}


```

</details>

**Comment by maziarzamani** [comment]
I was able to narrow it down the module code which was generated automatically in `index.js`. If I replace the source in `index.js` with the source from `custom.js` the problem is solved.

**Comment by codybreene** [comment]
@josefaidt I'm sorry, it's not clear to me how the issue was documented or resolved in the linked bug report. What is ultimately the fix here? I'm running into precisely the same issue.
