### ISSUE TITLE
Amplify codegen in headless environment

### ISSUE THREAD

**Issue by struct78** [aws-amplify/amplify-cli#852]
** Which Category is your question related to? **
amplify codegen

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
I am using the @multienv CLI to checkout different amplify environments based on the current branch. I have added .graphqlconfig.yml to my .gitignore, as it contains environment specific information about the API.

What I want to do is simply have the API ID in an environment variable that is configured per branch, and run `amplify codegen add --apiId xxxxxxxxx`.

Currently we can provide credentials via the `--providers` switch when running amplify init in a headless environment, e.g.

```AWSCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"accessKeyId\":\"${AWS_ACCESS_KEY_ID}\",\
\"secretAccessKey\":\"${AWS_SECRET_ACCESS_KEY}\",\
\"region\":\"${AWS_REGION}\"\
}"
PROVIDERS="{\
\"awscloudformation\":${AWSCONFIG}\
}"

amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --yes
```
Which is great - but is there a way we can do it for codegen?
e.g.

```
CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"typescript\",\
\"fileNamePattern\":\"src/graphql/**/*.ts\",\
\"generatedFileName\":\"src/services/api.ts\",\
\"generateDocs\":false\
}"

amplify codegen add --apiId xxxxxx --configure ${CODEGEN}
```
or
```
amplify codegen add --apiId xxxxxx ${CODEGEN}
```

**Comment by kaustavghosh06** [comment]
@struct78 We have introduced headless support for running our CLI which includes running codegen in headless as well. Please checkout - https://aws-amplify.github.io/docs/cli/init#amplify-pushpublish-parameters Let me know if you've suggestions for the same. Closing this issue and feel free to re-open if needed.
