### ISSUE TITLE
Deployments are failing (only recently) due to legacy lambda layers

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#8525]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

6.3.1

### What operating system are you using?

Windows 10 / Ubuntu 20.04 WSL

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Up until recently, lambda layers have worked great. Not sure what breaking change was introduced but in a very indeterminate fashion, deployments are failing due to legacy layer versions.

```
CREATE_FAILED      LambdaLayerPermissionAwsAccountsxxxxxxxxxxxxxxLegacy47 AWS::Lambda::LayerVersionPermission Fri Oct 22 2021 13:28:31 GMT+0100 (British Summer Time) 1 validation error detected: Value 'xxxxxxxx6178e7aa22b6' at 'principal' failed to satisfy constraint: Member must satisfy regular expression pattern: \d{12}|\*|arn:(aws[a-zA-Z-]*):iam::\d{12}:root (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: be5f0413-4557-4f40-b3c4-xxxxxxxxx; Proxy: null)

```
The only way I've managed to fix this is by deleting the problematic layers by hand in the AWS console.

### Expected behavior

Complaints about legacy layers should not prevent amplify deployments from completing. 

### Reproduction steps

1. Have around 50 layer versions and wait for amplify cli to start complaining about legacy versions. 🤦‍♂️

**Comment by antonio-vevivo** [comment]
Happened also to me, and can confirm that deleting the old layer versions from AWS console resolves this error. @kylekirkby thanks :)

**Comment by josefaidt** [comment]
Hey @kylekirkby and @antonio-vevivo thanks for raising this and apologies for the delay! I have a few follow-up questions:

- When you run into this issue is the layer mentioned several versions behind or does it occur when we're upgrading from an affected layer? 
- Are you able to capture the diff of the layer's CloudFormation template for when it occurred?

As an example, here is a snippet from a layer's CFN template for when we're only allowing a certain account:

```json
"LambdaLayerPermissionAwsAccounts229156689808be6ab91b": {
  "Type": "AWS::Lambda::LayerVersionPermission",
  "Properties": {
    "Action": "lambda:GetLayerVersion",
    "LayerVersionArn": {
      "Ref": "LambdaLayerVersionbe6ab91b"
    },
    "Principal": "229156689808"
  }
},
```

**Comment by kylekirkby** [comment]
> * When you run into this issue is the layer mentioned several versions behind or does it occur when we're upgrading from an affected layer?

Hi @josefaidt ,

The affected layer is usually several versions ahead of the breaking layer version, from what I've seen. I'm sorry but I can't provide a diff. If this happens again, I'll capture it. I've got one lambda layer with about 50 + versions, sometimes the deployment will fail on an old version that doesn't match the correct naming convention that is required...

**Comment by josefaidt** [comment]
Hey @kylekirkby thanks for clarifying! In the mean time how do you have the restrictions set (if any) for the affected Lambda Layer? 
![image](https://user-images.githubusercontent.com/5033303/142021361-a8723339-d8db-44b8-9e08-aa84facd0030.png)

**Comment by kylekirkby** [comment]
@josefaidt - Specific AWS account:

```
    "LambdaLayerPermissionAwsAccountsxxxxxxxxxxxxx50e8b5b": {
      "Type": "AWS::Lambda::LayerVersionPermission",
      "Properties": {
        "Action": "lambda:GetLayerVersion",
        "LayerVersionArn": {
          "Ref": "LambdaLayerVersion750e8b5b"
        },
        "Principal": "xxxxxxxxxxx"
      }
    },
    "LambdaLayerPermissionPrivate750e8b5b": {
      "Type": "AWS::Lambda::LayerVersionPermission",
      "Properties": {
        "Action": "lambda:GetLayerVersion",
        "LayerVersionArn": {
          "Ref": "LambdaLayerVersion750e8b5b"
        },
        "Principal": {
          "Ref": "AWS::AccountId"
        }
      }
    }

```

**Comment by josefaidt** [comment]
Hey @kylekirkby thanks for clarifying! After speaking with the team we believe this issue should be fixed in later versions of the CLI (currently at [7.4.0](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.4.0)) as the underlying logic has been modified to avoid naming issues for the `principal`'s value. Please continue with the [latest version of the Amplify CLI](https://github.com/aws-amplify/amplify-cli/releases/tag/v7.4.0) and let us know if this issue surfaces again, however in the mean time this should be mitigated.

**Comment by josefaidt** [comment]
Closing issue. @kylekirkby if you run into this issue again in the near future please reply back to this thread and we can investigate further 🙂
