### ISSUE TITLE
Amplify new environment stuck on "Updating resources in the cloud..."

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-cli#8526]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.5

### Amplify CLI Version

6.3.1

### What operating system are you using?

Windows 10 / Ubuntu 20.04 WSL

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

env, init, pull

### Describe the bug

So after checking out a new env, and battling with `amplify-video` issues regarding different env's. I've managed to get the new production env - `main` - deployed. However, the CLI never stops and returns once all the stacks have been created. Checking cloud formation, I can see that the updates have all been completed. 

UPDATE_COMPLETE                     amplify-xxxxx-main-xxxxxxAWS::CloudFormation::Stack Fri Oct 22 2021 18:25:50 GMT+0100 (British Summer Time)
⠙ Updating resources in the cloud. This may take a few minutes...

This has been stuck in this state for around 30 mins.. What do I do? Exit the process? or wait... if "wait" is the answer -  a "few" minutes seems a bit too lenient. 

### Expected behavior

Amplify CLI to return and exit the process after deploying all stacks and not get stuck on `⠙ Updating resources in the cloud. This may take a few minutes...` 

### Reproduction steps

1.  Deploy a new environment off of an existing one. See that the process never completes.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment]
I cannot reproduce this. Is this happening to you across multiple attempts on multiple different wifi networks? I wonder if this was some kind of temporary network environment or dns issue.

**Comment by josefaidt** [comment]
Hey @kylekirkby :wave: are you still experiencing this issue?

**Comment by kylekirkby** [comment]
@josefaidt - I'm no longer experiencing this. Potentially a network problem?
