### ISSUE TITLE
Invalid one to many resolver when primary partion key field is not a string

### ISSUE THREAD

**Issue by ptejada** [aws-amplify/amplify-cli#8534]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.1

### Amplify CLI Version

6.3.1

### What operating system are you using?

Windows (WSL)

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

If I create a model where the primary key is not of type `String` any one-to-many relationships will be broken because the generated resolver assumes the primary partition key is a `String.`

For example, the relation resolver will include something like this
```
  "expression": "#partitionKey = :partitionKey",
  "expressionNames": {
      "#partitionKey": "accountId"
  },
  "expressionValues": {
      ":partitionKey": {
          "S": "$context.source.number"
    }
  }
```

Trying to query the relationship will result in a DynamoDB error "One or more parameter values were invalid: Condition parameter type does not match schema type" because the partition key is supposed to be of type `N` instead of `S`

### Expected behavior

The generated resolver should reference the correct field type 
```
  "expression": "#partitionKey = :partitionKey",
  "expressionNames": {
      "#partitionKey": "accountId"
  },
  "expressionValues": {
      ":partitionKey": {
          "N": "$context.source.number"
    }
  }
```

`Note:` Manually making this edit in the resolver template fixes the error.

### Reproduction steps

1. Create the models using the GraphQL schema.
2. Create a new `Account` record
3. Try query to the `Account.jobs` relation. Ex: 
```graphql
query MyQuery {
  listAccounts {
    items {
      name
      number      
      jobs {
        items {
          id
          name
        }
      }
    }
  }
}
```

### GraphQL schema(s)

<details>

```graphql
type Account @model(subscriptions: null) @key(fields: ["number"]) {
  number: Int!
  name: String!
  group: String!
  jobs: [Job] @connection(keyName: "byAccount", fields: ["number"])
}

type Job @model
@key(name: "byAccount" fields: ["accountId", "status", "name"]) {
  id: ID!
  name: String
  status: String
  accountId: Int!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
@ptejada if you get a chance, please try out v2 of the GraphQL Transformer to see if it addresses this issue for you.
