### ISSUE TITLE
Upgrading from ElasticSearch 6.2 to OpenSearch 1.0

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#8535]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Upgrading from ElasticSearch 6.2 to OpenSearch 1.0

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

6.3.1

**What AWS Services are you utilizing?**

AppSync / DynamoDB / ElasticSearch

**Provide additional details e.g. code snippets**

I am using the Amplify CLI to create all back end resources. By default is creates the ElasticSearch instance at version 6.2. What is the recommended approach to upgrade this to OpenSearch 1.0. Should I do it in the Console, or is there a setting in the parameters where we can specify a version?

**Comment by cjihrig** [comment]
@sacrampton I've marked this as a feature request, but it's not likely to be supported in the near future. To answer your question, yes, I think you will likely need to do this outside of Amplify for time being.

**Comment by sacrampton** [comment]
Thanks @cjihrig - so are you saying that it should be fine if we perform the upgrade outside Amplify and that future pushes will be compatible?

**Comment by cjihrig** [comment]
We can't make any guarantees about compatibility if you need to do something outside of our normal workflows. The reason we don't support this out of the box is because it's possible that an OpenSearch breaking change could slip through that we cannot account for.

**Comment by sacrampton** [comment]
So your advice at this time is not to move to OpenSearch and stay with ElasticSearch 6.2?

**Comment by cjihrig** [comment]
@sacrampton sorry for the delayed response. I wanted to share [this](https://docs.amplify.aws/cli/migration/transformer-migration/#what-are-the-breaking-changes-and-how-do-i-migrate) with you. That section of the docs for the new GraphQL Transformer include instructions for upgrading to version 7.10.

**Comment by sacrampton** [comment]
Thanks for this @cjihrig - is the existing transformer (specifically the lambda from Ddb to Es) compatible with OpenSearch? Or do you have to do this in conjunction with a migration to the new transformer?

**Comment by cjihrig** [comment]
v1 of the transformer has not been updated in any way. Due to breaking changes between the older ElasticSearch versions, I'm not comfortable recommending you to update if you're staying on v1.

**Comment by sacrampton** [comment]
Thanks for this @cjihrig.

I note that the latest version of OpenSearch is 1.2.0 - what is the difference between this and 7.10? Given AWS is moving everything to OpenSearch, shouldn't we be moving to from ElasticSearch 6.2 to OpenSearch 1.2.0? Or is ElasticSearch 7.10 the same thing as OpenSearch 1.2.0?

**Comment by cjihrig** [comment]
Check out https://opensearch.org/faq/. A few relevant quotes from that page:

> OpenSearch is a fork of open source Elasticsearch 7.10. As such, it provides backwards REST APIs for ingest, search, and management. The query syntax and responses are also the same. In addition, OpenSearch can use indices from Elasticsearch versions 6.0 up to 7.10. We also aim to support the existing Elasticsearch clients that work with Elasticsearch 7.10.

> All future OpenSearch 1.x releases will be backwards compatible with Elasticsearch 7.10, although some APIs will be deprecated. If functionality requires a breaking change, we will introduce a new major version of OpenSearch and provide tooling to make migrating to the new major version simple.

Regarding the new GraphQL Transformer - that was [released earlier this week](https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/).
