### ISSUE TITLE
[Geo] `amplify add geo` doesn't set region of Amazon Location Service in `aws-exports.js` using cli v.6.3.1

### ISSUE THREAD

**Issue by DominicBortmes** [aws-amplify/amplify-cli#8538]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify

### If applicable, what version of Node.js are you using?

v16.11.1

### Amplify CLI Version

6.3.1

### What operating system are you using?

Amazon Linux 2 (Cloud9)

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

`amplify add geo` created an `aws-exports.js` that does not include the project region into the geo settings of the amplify project. This breaks the rendering of any map (unless the map is explictly instantianted with the region parameter set) since API requests are sent against an in-existing region `https://maps.geo.undefined.amazonaws.com/maps/v0/maps/`.

```js
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "<redacted>",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "<redacted>",
    "aws_user_pools_web_client_id": "<redacted>",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "AmazonLocationService": {
            "maps": {
                "items": {
                    "geo-test": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "geo-test"
            },
            "region": "eu-west-1"
        }
    }
};


export default awsmobile;
```

The `geo` section lacks the [documented](https://docs.amplify.aws/lib/geo/existing-resources/q/platform/js/#in-your-application) region to be used of Amazon Location Services. Note that the region is setup correctly, since other configuration sections like auth take over the region correctly.

Note that there seem to be related bugs open that interfere with this issue. [Issue-8405 of the amplify cli](https://github.com/aws-amplify/amplify-cli/issues/8405) reports that the JSON keys of the `geo` settings section seem to be inconsistent across different versions, increasing the risk of unsuccessful config parsing.
[Issue-57 of maplibre-gl-js-amplify](https://github.com/aws-amplify/maplibre-gl-js-amplify/issues/57) points out that a missing default region for Amazon Location Service (in `aws-exports.js`'s geo section) can break rendering of Maps. (When aws-exports.js does export a default _AND_ devs don't set the region expliclty for every map initialized in JS.)

### Expected behavior

`amplify add geo` should create a config that contains the project region and looks below. I verfied with an older version of amplify cli (6.2.1) that the region used to be passed through successfully.

```js
{
    // ...
    "geo": {
        "AmazonLocationService": {
            maps: {...}, 
            search_indices: {...},
            region: REGION_OF_AMPLIFY_PROJECT
        }
    }
}

### Reproduction steps

### Reproduce issue with npm aws-amplify@6.3.1
1. install most recent amplify cli version (npm install -g @aws-amplify)
2. init an amplify project with `amplify init`
3. Add geo feature with defaults by executing `amplify add geo`
4. Generate `aws-exports.js` by pushing to cloud `amplify push`
5. Find that the generated `aws-exports.js` __does not set the the `region` key__ under .geo.AmazonLocationService.

### Proof that older version (aws-amplify@6.2.1) behaved as expected
This works with older amplify version v. 6.2.1 executing the same steps, i.e.
1a. npm rm -g @aws-amplify (clean up previously used version)
1b. install amplify cli  `npm install -g @aws-amplify/cli@6.2.1 `        
2. init an amplify project with `amplify init`
3. Add geo feature with defaults by executing `amplify add geo`
4. Generate `aws-exports.js` by pushing to cloud `amplify push`
5. Find that the generated `aws-exports.js`  __does set the the `region` key__ under .geo.AmazonLocationService as expected

### GraphQL schema(s)

-

### Log output

-

### Additional information

_No response_

**Comment by phani-srikar** [comment]
This has been fixed with amplify CLI `v6.4.0`. Please run `amplify push --force` after upgrading the Amplify CLI.
