### ISSUE TITLE
Read-only cli tool for AppSync clients

### ISSUE THREAD

**Issue by zigfreid5** [aws-amplify/amplify-cli#855]
**Background**
I work on a mobile app that uses AppSync with IAM and Cognito User Pools. Our backend team (on the other side of the globe) manages three different environments, Dev, Staging, and Production.

To use `amplify codegen` I have to run `amplify init`. This adds amplify to my project and creates a bunch of resources for me in AWS that I don't need (or want, or should even have access to create).

I will never need to `amplify push` anything and will only ever want to `amplify codegen types`.

**Request**
How about a tool, command, or version of `amplify configure` that simply lets me use the codegen without assuming that I'm starting a new project from scratch?

**Comment by kaustavghosh06** [comment]
@zigfreid5 We provide these options now: Please take a look at the following docs:
Please take a look at Flow 5 in this section - https://docs.amplify.aws/cli/graphql-transformer/codegen#workflows
