### ISSUE TITLE
Restrict access to certain environment

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-cli#8579]
### Describe the feature you'd like to request

It would be handy to be able to restrict access of a certain developer. If I'm not mistaken, right now when initializing amplify it always uses full AdministratorAccess. For example when onboarding a new junior developer, it is not necessary for him to be able to push to master or create new environments. It would be nice to  be able to restrict access to e.g. only development environment. 

### Describe the solution you'd like

Maybe on amplify init there could be a option for restricting access? 

### Describe alternatives you've considered

As far as I know there are no ways of achieving this. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cjihrig** [comment]
@parvusville you could try a couple different approaches. You could limit who can assume the IAM role used by the CLI when pushing a project. You could also try limiting access via tags, as outlined [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html#access_iam-tags_control-tag-keys). Another approach would be to have a separate account for your production environment. We could definitely improve our documentation around this though.

**Comment by cemo** [comment]
@cjihrig is there any documentation about it?
