### ISSUE TITLE
@model directive doesn't work as expected 

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-cli#861]
**Describe the bug**
@model directive doesn't work as expected / as described in the documentation [here](https://aws-amplify.github.io/docs/cli/graphql#model)  : 
> You may also override the names of any generated queries and mutations, or remove operations entirely.

Removing all mutations seems broken

**To Reproduce**
1. Create a amplify project and add `api` to it. 
2. Update the `amplify/api/app_name/schema.graphql` as described in the docs : 
```
type Post @model(queries: { get: "post" }, mutations: null) {
    id: ID!
    title: String!
    tags: [String!]!
}
```
3. run `amplify push api` to deploy the graphql schema to appsync. Answer `Y` to all questions
4. Go to the aws console to inspect the generated graphql, or inspect `amplify/api/app_name/build/schema.graphql` and see that mutations by default are still present

**Expected behavior**
`mutations:null` should have caused all mutations to be removed from the generated schema

**Version used**
Forgot to mention that I use the multienv version of the CLI

**Additional context**
I'm pretty new around here, can anyone guide me to a great document showing how to create a  `schema.graphql` file for a **real** app (meaning with multiple .graphql files for better reading, security implemented, mutations and susbscriptions only where needed, mutations that invoke lambdas etc...) Thanks a lot !!!

**Comment by vparpoil** [comment]
Updated the CLI to the last release (following the closing of #74 which will apparently help answering my interrogations). I started from scratch with `amplify remove api` and `amplify add api`. The bug is still present

**Comment by yuth** [comment]
What version of CLI did you use.  I could not reproduce this in `1.1.7` 

 Feel free to to re-open if you can still reproduce this.

**Comment by vparpoil** [comment]
Thanks for checking and sorry for the issue. 
I couldn't reproduce either with version 1.1.7
