### ISSUE TITLE
Bug After initial pull - error Could not attach the backend to the project. Ensure that there are no applications locking the `amplify` folder and try again

### ISSUE THREAD

**Issue by krrby** [aws-amplify/amplify-cli#8629]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dqb3qupymvbim

### Region

ap-southeast2

### Environment name

MaoriMatchBackend

### Amplify CLI Version

6.3.1

### If applicable, what version of Node.js are you using?

v16.11.1

### What operating system are you using?

Windows

### Browser type?

Chrome

### Describe the bug

Hi there, I've just done the initial pull for the backend of my project  (amplify pull --appId dqb3qupymvbim --envName staging) , I then used amplify pull and this error has come up :

![image](https://user-images.githubusercontent.com/34120827/139575803-4bb5be0e-f728-4365-bdbb-e4e78a67b6b2.png)

I have removed and installed amplify, deleted the staging environment, and started again but this bug keeps coming up after the initial pull 

### Expected behavior

That it will sync with the back end and say that everything is up to date

### Reproduction steps

-I install Amplify CLI and libraries for react-native
-I create my data models and authentication
-Save and Deploy
-I then use amplify pull --appId dqb3qupymvbim --envName staging, everything completes 
- I then use amplify pull again and I get error

**Comment by ammarkarachi** [comment]
@krrby Do you have the amplify project open in an IDE before you executed the pull?

**Comment by krrby** [comment]
Yes, I have it running on Visual Code Studios, I found a workaround this
morning. if I do amplify init and then open the console, create the data
models and then pull the project it works,
it just won't work if I create the data models first and try and pull an
already created backend

**Comment by siguy85** [comment]
I had this happen to me, I was logged into aws console as a different user to the aws cli... when I tried to pull, I got that error. I logged out of aws console via my browser and tried the pull again using aws cli. I was then directed to my browser and logged in as the aws cli user instead.
