### ISSUE TITLE
So far as I can tell, the `exists` field of the `SearchableStringInput` is non-functional

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-cli#863]
**Which Category is your question related to?**
Usage of a search functionality on a model that is `searchable`

**What AWS Services are you utilizing?**
Amplify, DynamoDB, ElasticSearch.

**Provide additional details e.g. code snippets**
When trying to run a search for `exists: false` on a field, I get a persistent error of type `Elasticsearch:UserIllegalArgumentException` with an error message of `"Elasticsearch responded with an error: Bad Request"`

In order, to get this, I execute a query on a "search" type query, with an `input` object that looks like this:
`{ filter: { email: { exists: true } } }`

If I try it with any field (whose input is searchablestringfilterinput), I get the same error. If I try it with an `eq` operator, or a `wildcard` operator, it seems to work just fine.

e.g., `{ filter: { email: { eq: emailaddress } } }` works fine and `{ filter: { email: { wildcard: "usernamepartofemail*" } } }` works fine

Is there something that I'm missing, or is this perhaps something that has changed inside the elasticsearch api since the searchablestringfilterinput resolver was first written?

**Comment by jernejcic** [comment]
I cannot get past this. I am getting `Elasticsearch:UserIllegalArgumentException` on all my search queries. Any ideas on the cause and how to get around it?

**Comment by mikeparisstuff** [comment]
Hello thanks for raising the issue. This appears to be a bug and is being investigated. We will work on providing a speedy mitigation and in the meantime you should be able to use custom resolvers to by pass the problem (see https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable for an example). Thank you for the patience.

**Comment by kaustavghosh06** [comment]
The issue seems to be resolved from the service side. Please feel to re-open/comment on this issue if you're still stuck on this or still seeing this issue.
