### ISSUE TITLE
Running amplify push after updating to updated CLI causes error;

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#865]
**Describe the bug**
Running `amplify push` after updating to updated CLI causes error; 

**To Reproduce**
1. Run amplify push
2. Accept migration instructions
3. See error:

```
Migrating your API. This may take a few minutes.
× An error occured when migrating the API project.
× An error occurred when pushing the resources to the cloud

Cannot read property 's3TemplateURL' of undefined
```

**Expected behavior**
It works.

Would appreciate any ideas on how to solve this or get logs for your use.  Thank you!

**Comment by kaustavghosh06** [comment]
@mwarger Which version of the CLI did you initialze the project you're trying to migrate?
Can you tell me what your `amplify status` outputs?

**Comment by mwarger** [comment]
many versions ago - it was one of the original multi-env betas.  I've kept it up to date since then.

amplify status looks normal - no different than it has in the past.

>amplify status

Current Environment: local

| Category  | Resource name   | Operation | Provider plugin   |
| --------- | --------------- | --------- | ----------------- |
| Function  | mylambda       | Create    | awscloudformation |
| Api       | myapi          | Update    | awscloudformation |
| Auth      | cognito51fac114 | No Change | awscloudformation |
| Storage   | s305dbbf8f      | No Change | awscloudformation |
| Analytics | redactedapp       | No Change | awscloudformation |

Pinpoint URL to track events https://console.aws.amazon.com/blah
GraphQL endpoint: https://blahblah.appsync-api.us-east-1.amazonaws.com/graphql

**Comment by kaustavghosh06** [comment]
Interesting. So you have a standalone function which is not previously deployed.
Just to root cause, can you remove that (make sure to back up the function code) and then run an `amplify push` and see if the migration works?

**Comment by mwarger** [comment]
Update - I reverted the change I had made to the lambda and ran amplify push again - I accepted the migration and it appears to be working now.  Will update once I see a status.

**Comment by mwarger** [comment]
It went along doing stuff for quite a while, then I got this.  Please advise @kaustavghosh06 

× An error occured when migrating the API project.
Reverting API migration.
× An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, mkdir 'C:\dev\redacted\amplify\backend\api\mygql\template\Resources\GraphQLSchema\Properties\ApiId\Fn::GetAtt'

**Comment by chris-merapar** [comment]
I have the same error but the scenario is slightly different.

1. Project has api and auth, no functions
2. Start with fresh clone of the repo, so amplify-meta.json is not present (it's in the amplify gitignore)
3. Run amplify init and choose the env I want to deploy
4. Run amplify push and get the s3TemplateURL error

I put some debugging in amplify-provider-awscloudformation/lib/push-resources.js and found that the error is caused because the new entries in amplify-meta.json (created by the amplify init) do not contain the providerMetadata object.

**Comment by chris-merapar** [comment]
I just tried something else:

1. amplify env pull --restore
2. amplify push
3. amplify push (see below)
4. Say yes to migration

Some strange things happened:

- After the restore, folders under amplify/backend were created for functions and an api that I deleted from the project a long time ago. They were not referenced in the backend-config.json so I guess they are doing no harm
- The first time I ran amplify push it it not ask me to migrate, said nothing needed updating, and succeeded with very little console output. I then ran it again and it said the api needed updating, then asked me for confirmation to migrate. 

The migration did work though using this method.

**Comment by mwarger** [comment]
@chris-merapar I will give this a try.  Thanks for the suggestion.

**Comment by mwarger** [comment]
I tried syncing my environment like you described (by doing a `env pull --restore`) - This put my environment in a 'no change' status.  I made a change to the schema so that it would need to update.

I tried to push and I got the same error:

× An error occured when migrating the API project.
Reverting API migration.
× An error occurred when pushing the resources to the cloud

ENOENT: no such file or directory, mkdir 'C:\dev\redacted\amplify\backend\api\mygql\template\Resources\GraphQLSchema\Properties\ApiId\Fn::GetAtt'

Please advise on how I could successfully complete this migration.  I'm happy to send any logs or even screen share with a member of your team.  Thanks!

**Comment by chris-merapar** [comment]
> ENOENT: no such file or directory, mkdir 'C:\dev\redacted\amplify\backend\api\mygql\template\Resources\GraphQLSchema\Properties\ApiId\Fn::GetAtt'
> 

This is a different error to the one I got. You could add some debug logging to whichever CLI JS file generated that error (for me it was /usr/local/lib/node_modules/\@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js).

In general, I don't think these workarounds are a workable solution, as I can't do this every time in the CI pipeline, where the amplify init must properly create the amplify-meta.json (which is in the standard amplify gitignore, so never present in the CI environment).

**Comment by mwarger** [comment]
@chris-merapar I agree.  The last time there was a substantial update, I had to re-create my projects from scratch.  I hope I don't have to do that this time to get this to work.  

@kaustavghosh06 @UnleashedMind Any thoughts?

**Comment by kaustavghosh06** [comment]
@mwarger Can you show me what your `amplify status` looks like?
Also, could you please show the whole stack-trace if possible (for the migration), that would help us a lot.

**Comment by kaustavghosh06** [comment]
Also, would it be possible to share you schema if you can?

**Comment by mwarger** [comment]
Can you provide an email address and I can send you all that information.  Thanks!

**Comment by kaustavghosh06** [comment]
@mwarger kaustavg@amazon.com

**Comment by kaustavghosh06** [comment]
@mwarger Sure! Let's get this fixed :)

**Comment by kaustavghosh06** [comment]
@mwarger Didn't get your email today. Quick question. Are you using Native windows or WSL to run the CLI?

**Comment by mwarger** [comment]
@kaustavghosh06 @UnleashedMind @mikeparisstuff I believe I have figured out a temporary work-around for this issue.  I believe the root cause might have something to do with this PR: https://github.com/aws-amplify/amplify-cli/pull/757

I had an enum type that was apparently causing an issue with generating the graphql schema - I temporarily changed this enum type to a string and it appears to migrate successfully.

**Comment by kaustavghosh06** [comment]
@mwarger Thanks for looking into this, yes you're correct. We've rootcause the issue and is tied to the enum field changes in #757. We're currently working on fixing this. I'll update this thread once we push a new version with a fix to npm.
