### ISSUE TITLE
AppSync RDS support

### ISSUE THREAD

**Issue by mobiledevelopersprojects** [aws-amplify/amplify-cli#866]
**Describe the solution you'd like**
When I design schema with model and relationship, I would want the relational database at the backend instead of creating multiple DynamoDB at the backend, defeating the purpose of NoSQL data store. 

**Describe alternatives you've considered**
I have gone with DynamoDB but it amplify doesnt follow the best practices of DDB. So I had to do a lot of customization there. In fact, I went away from amplify as a result and done everything from scratch. 

**Additional context**
Complicated schema modeling that still needs consistent performance via NoSQL (DynamoDB)

**Comment by kaustavghosh06** [comment]
@mobiledevelopersprojects  We have an RFC for the same out here - https://github.com/aws-amplify/amplify-cli/issues/660 for the same and we're working to get a solution out for Aurora serverless soon. Please feel free to add your feedback to the the RFC.

**Comment by kaustavghosh06** [comment]
We've launched support for RDS as a part of the GraphQL transformer. Please take a look at https://aws-amplify.github.io/docs/cli/graphql#automatically-import-existing-datasources for more information around it.
