### ISSUE TITLE
Amplify mock UnknownEndpoint: Inaccessible host: `localhost' at port `62224'. This service may not be available in the `us-fake-1' region. | Failed to start API Mock endpoint Error: start has timed out!

### ISSUE THREAD

**Issue by akinwol** [aws-amplify/amplify-cli#8669]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.0.1

### Amplify CLI Version

6.3.1

### What operating system are you using?

Mac 11.4 Big Sur

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When i run amplify mock I am able to run queries/mutations from the explorer locally. However as soon as a I run my next js app `yarn dev`. Amplify mock stops working. I get the following error in the console. 

```
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "limit": 100,
    "operation": "Scan"
}
UnknownEndpoint: Inaccessible host: `localhost' at port `62224'. This service may not be available in the `us-fake-1' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:529:46)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:361:22)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'UnknownEndpoint',
  region: 'us-fake-1',
  hostname: 'localhost',
  retryable: true,
  originalError: Error: connect ECONNREFUSED ::1:62224
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -61,
    code: 'NetworkingError',
    syscall: 'connect',
    address: '::1',
    port: 62224,
    region: 'us-fake-1',
    hostname: 'localhost',
    retryable: true,
    time: 2021-11-04T13:21:47.981Z
  },
  time: 2021-11-04T13:21:47.981Z
}

```

Then I kill the process and try run `amplify mock` again but this time I get the following error 
`Failed to start API Mock endpoint Error: start has timed out!`

I have reinstalled all packages and still running into the same issue. I even tried creating a new project just to test it out but ran into the same issue. This also seems to only happen with my next js projects. Seems like as soon as the app gets compiled, amplify mocking stops working.

### Expected behavior

This behavior is completely unexpected, I am not sure what happened as everything was working fine just a week ago. I have no idea what's going on. Any help would be greatly appreciated. Running a next js app shouldn't break the cli mocking capabilities. I am still learning this stuff and not even sure how to pinpoint to the root cause. 

### Reproduction steps

1. Run `amplify mock`
2. Run `yarn dev` on next js app 
3. Run query

### GraphQL schema(s)

<details>

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
}

type Post @model @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  post: Post @connection(fields: ["postID"])
  content: String!
}



```

</details>

**Comment by ammarkarachi** [comment]
@akinwol can you check if the port 62224 is in use by running `lsof -i -P`?

**Comment by akinwol** [comment]
I ended up resolving this

To solve I did the following 
- Ran `sudo nano /etc/hosts `

Doing that you get something like this 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/37726406/140933537-d65fdf76-82ef-4c37-8bcd-1c4f71f5d3bf.png">

- Deleted the ip6 ` ::1 localhost `
- Then ran `sudo killall -HUP mDNSResponde ` to flush dns cache

I was trying different things but that seemed to do the trick

**Comment by nealdeters** [comment]
I've been hitting this error lately as well. I tried the above command and that get's it running, but everything runs extremely slow.
