### ISSUE TITLE
`Invalid lambda function output : Invalid JSON` error in my PreSignup Lambda

### ISSUE THREAD

**Issue by codybreene** [aws-amplify/amplify-cli#8682]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

6.3.1

### What operating system are you using?

Mac

### Amplify Categories

auth, function

### Amplify Commands

push

### Describe the bug

I add a PreSignup lambda function so that I can autoConfirm my user on signUp. However, I've noticed that if I remove the `async` from my handler, the function throws a `Invalid lambda function output : Invalid JSON` error. But, I am not awaiting anything in the handler itself, so I should not have to use `async`. 

Moreover, I am not clear why both an `index.js` and `custom.js` file were generated - ultimately, where should the logic of my lambda live? It doesn't appear as though the `custom.js` file is being read.  

Here is the code in the `index.js` file: 

```
exports.handler = async (event) => {
  // Confirm the user
  event.response.autoConfirmUser = true;

  // Set the email as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty("email")) {
    event.response.autoVerifyEmail = true;
  }

  // Set the phone number as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty("phone_number")) {
    event.response.autoVerifyPhone = true;
  }

  // Return to Amazon Cognito
  return event;
};
```

As you can see, there's nothing async about the function

### Expected behavior

The code in my PreSignup lambda is executed without an issue, aka the user is autoConfirmed. 

### Reproduction steps

1. amplify add auth
2. configure auth with presignup lambda
3. customize presignup lambda function
4. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@codybreene If you would remove async you would have to use the callback signature as cognito is expecting a promise.

**Comment by ammarkarachi** [comment]
Also to understand the issue better why would you like to remove async?

**Comment by codybreene** [comment]
How can I tell the Lambda is expecting a promise? Also, is the lambda reading from `index.js` or `custom.js`? Why are there two files?

**Comment by yuth** [comment]
The lambda gets a `MODULES` env variable injected which should have `custom` included in it. You can see it in the `amplify/backend/function/<resource-name>PreSignup/parameters.json`. `index.json` is what gets executed and expect a promise to be returned.
