### ISSUE TITLE
Support for Serverless Aurora

### ISSUE THREAD

**Issue by patoncrispy** [aws-amplify/amplify-cli#87]
**Do you want to request a feature or report a bug?**
Feature

Hey team! First off, this tool is amazing! Really enjoying the experience so far. 

I know Serverless Aurora (SA) is only just out and probably doesn't even have CloudFormation support yet, but are there plans to add SA support, especially for GraphQL APIs? This would be very cool!

**Comment by YikSanChan** [comment]
Seems there are some ongoing progress? See https://aws.amazon.com/blogs/mobile/aws-appsync-releases-pipeline-resolvers-aurora-serverless-support-delta-sync/

> With the release of the Data API for Aurora Serverless, you now have a first-class data source for executing GraphQL operations against a relational database in AWS AppSync.
