### ISSUE TITLE
Amplify CLI mangles name of project

### ISSUE THREAD

**Issue by tetreault** [aws-amplify/amplify-cli#870]
**Which Category is your question related to?** 
Creating a new project

**What AWS Services are you utilizing?**
Amplify CLI

**Provide additional details e.g. code snippets**
When I initialized my new react app with the Amplify CLI I noticed in `amplify/.config/#current-cloud-backend/amplify-meta.json` file it mangled the name I gave it. 

I entered `amplifyreactapp` as the name, and to my surprise when I looked at my S3 bucket it generated I see the name `mplifyeactpp`. 

Is there some unexpected thing going wrong here? Aside from the name getting mangled, the rest of the CLI is working fine so its not some roadblock I just don't like the name it created.

**Comment by UnleashedMind** [comment]
is it the deployment bucket name of the hosting bucket name?

**Comment by tetreault** [comment]
Hi @UnleashedMind its the deployment bucket. I just was confused why the name wouldnt literally be what I entered.

**Comment by UnleashedMind** [comment]
The deployment bucket is only internally used by the cli, as you've found out, it does not block any functionalities. 
I will check if it can be made more human readable and consistent.

**Comment by tetreault** [comment]
Thanks for the feedback @UnleashedMind ! Yeah i mean, if I choose a valid name (between 8-20 alphanumeric characters) I don't really understand why the amplify CLI would mangle the name at all? Why not just straight up use the exact same name the user entered?

**Comment by UnleashedMind** [comment]
what version of the CLI are you using? (execute `amplify -v` to find out). 
The latest version (1.1.0) already changed this behavior. the names are appended with time stamp and env name. But the beginning part is the original project name.

**Comment by tetreault** [comment]
Weird, I couldve sworn when I installed the amplify cli I followed the command in the README on this repo (`npm install -g @aws-amplify/cli`) but i do indeed see `amplify -v` prints out 0.1.45. I wonder how that happened...

**Comment by UnleashedMind** [comment]
try `npm install -g @aws-amplify/cli@latest`

**Comment by tetreault** [comment]
Thx @UnleashedMind i'm migrating to this latest version now!
