### ISSUE TITLE
How to upgrade cli to @multienv

### ISSUE THREAD

**Issue by hagiosofori** [aws-amplify/amplify-cli#872]
** Which Category is your question related to? **
Multienv

** Provide additional details e.g. code snippets **
I've globally installed the multienv version of amplify-cli. however, creating a git branch, and then running amplify add env produces no result. It runs as though it's not the multienv version.

I checked the globally installed packages, and it shows that the multienv version is installed. 

However, checking the amplify version shows 0.1.41, which isn't the multienv version. Is there something I'm missing?

```yarn global list
yarn global v1.13.0
warning ..\package.json: No license field
info "@aws-amplify/cli@0.2.2-multienv.1" has binaries:
   - amplify
info "create-react-app@2.1.5" has binaries:
   - create-react-app
info "expo-cli@2.10.0" has binaries:
   - expo
   - expo-cli
Done in 2.87s.```


``amplify version
0.1.41``

**Comment by kaustavghosh06** [comment]
Hey, can you run `npm install -g @aws-amplify/cli` to install the latest version of the CLI (which has multienv support now).

**Comment by kaustavghosh06** [comment]
@hagiosofori Closing this issue. Please let me know if you're still having issues installing.
