### ISSUE TITLE
jest-haste-map: Haste module naming collision: <functionName>

### ISSUE THREAD

**Issue by phanendraguptha** [aws-amplify/amplify-cli#8728]
I am getting the jest-haste-map issue after doing following steps:
1. Added new function (amplify add function)
2. Pushed the amplify function (amplify push)
3. While I run expo, the below mentioned error is getting generated (expo start)
I've seen the solution as mentioned in this link https://github.com/aws-amplify/amplify-cli/issues/3295#issuecomment-833640678 still it's not working. As i dig little deeper, in the metro config resolver options I didn't see any option related to blacklistRE.  Please help me resolving this issue.
```
jest-haste-map: Haste module naming collision: <functionName>
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/amplify/#current-cloud-backend/function/<functionName>/src/package.json
    * <rootDir>/amplify/backend/function/<functionName>/src/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/phanendraguptha/Desktop/<projectName>/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/phanendraguptha/Desktop/<projectName>/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 76) {
  mockPath1: 'amplify/#current-cloud-backend/function/<functionName>/src/package.json',
  mockPath2: 'amplify/backend/function/<functionName>/src/package.json'
}
```

**Comment by yuth** [comment]
I think the option name now is changed to `blockList`.  [metro docs](https://facebook.github.io/metro/docs/configuration/#blocklist)

**Comment by phanendraguptha** [comment]
I tried using blockList with the regex pattern and the exclusionList still getting the same error message.
```
const exclusionList = require("metro-config/src/defaults/exclusionList");
module.exports = {
  resolver: {
    blockList: exclusionList([/amplify\/#current-cloud-backend\/.*/]),
    // blockList: /#current-cloud-backend\/.*/,
  },
};
```

**Comment by josefaidt** [comment]
Hey @phanendraguptha :wave: are you still experiencing this issue? The regex pattern in the uncommented line looks correct.

```js
{
  blockList: /amplify\/#current-cloud-backend\/.*/
}
```

**Comment by phanendraguptha** [comment]
Tried that thing also. Still it's not working

**Comment by josefaidt** [comment]
Hey @phanendraguptha as @kaustavghosh06 has [mentioned on a related issue](https://github.com/aws-amplify/amplify-cli/issues/9026#issuecomment-975872068), we'd recommend opening an issue in the expo repository or similar to see if they could provide a workaround or better solution
