### ISSUE TITLE
How to rebuild back end resources like S3 buckets used by amplify?

### ISSUE THREAD

**Issue by poppybank** [aws-amplify/amplify-cli#874]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
S3, API GraphQL

** Provide additional details e.g. code snippets **
Amplify version 0.1.44

In a fit of bucket cleanup from some earlier experiments, I seem to have deleted the buckets used by amplify to store data needed for amplify push to work.  Now when I try to push a change to a resolver, I get this error: 

✖ An error occurred when pushing the resources to the cloud
The specified bucket does not exist

Is there a way for me to rebuild the whole backend from scratch based on my current state?  I am going to need to move this project to another account eventually so I'd like to understand how this will work.

**Comment by kaustavghosh06** [comment]
@poppybank You should checkout our latest v1 release for the Amplify CLI which supports multiple environments. You can basically clone your infrastructure accross multiple environments (could be in the same or different account). Here's the announcement - https://aws.amazon.com/about-aws/whats-new/2019/02/amplify-framework-adds-support-for-multiple-environments-custom-resolvers-larger-data-models-and-iam-roles-including-mfa/

**Comment by poppybank** [comment]
I just installed it so I'll try it out but when I try to migrate the project to the new version it fails because of the same issue 

⠙ Migrating your project
Migrating your API. This may take a few minutes.
✖ There was an error migrating your project.
migration operations are rolledback.
2019-02-14T19:58:59.154Z - error: uncaughtException: The specified bucket does not exist date

**Comment by kaustavghosh06** [comment]
@poppybank I see..did you delete your deployment bucket?

**Comment by poppybank** [comment]
Yes.

**Comment by kaustavghosh06** [comment]
@poppybank One workaround I could suggest is to remove your GraphQLAPI (after backing up or copying your annotated schema) by using the older version of the CLI-> migrate your project using the latest version of the CLI -> amplify env add (this would create a new deployment bucket for your env)-> add  your API back -> push

**Comment by poppybank** [comment]
OK, so do this: 

- make a copy of the amplify directory
- revert to @aws-amplify/cli@0.1.44
- amplify api remove
- install  @aws-amplify/cli@1.1.0
- amplify api add
- restore backend/api from the old directory
- amplify push
correct?

**Comment by poppybank** [comment]
Where should the amplify env add be in there?

**Comment by kaustavghosh06** [comment]
* revert to @aws-amplify/cli@0.1.44
* Make a copy of the amplify dir as backup
* amplify api remove ideally but I think this won't work since you won't be able to push subsequently due to the missing deployment bucket. 
Try this instead, manually delete the `amplify/backend/api<graphqlapiname>/` and `amplify/#current-cloud-backend/api<graphqlapiname>/` directories and remove the api reference from the `amplify/backend/amplify-meta.json` file as well.
* install  @aws-amplify/cli@1.1.0
* run `amplify` command to migrate your other resources and project configs (that would work without a deployment bucket)
* amplify env add
* amplify api add (Use the same annotated schema as your previous API - you can get that from amplify/backend/api/<graphql-api-name>/schema.graphql)
**Note: This would create a new GraphQL API and corresponding data-sources**
* amplify push

**Comment by poppybank** [comment]
@kaustavghosh06 that worked!!  Thank you.

Are there docs somewhere about how to point the native apps to different environments?

**Comment by kaustavghosh06** [comment]
@poppybank So we follow git-based flows, so each time you do something like `amplify env checkout <env-name>` we regenerate your `awsconfiguration.json` file, which has a list of all your backend resources based on your environment you're checking out. This file could be directly fed to the client libraries.

**Comment by kaustavghosh06** [comment]
For more details, please checkout https://aws-amplify.github.io/docs/cli/multienv?sdk=android

**Comment by poppybank** [comment]
Will do, thank you for your help.

**Comment by mburgjr** [comment]
Is there any way to simply make a new deployment bucket and keep only one environment on the amplify project?

Or to combine the environments after in some way?
