### ISSUE TITLE
amplify-appsync-simulator - #break statement does not exit loop immediatly

### ISSUE THREAD

**Issue by DavidCaya** [aws-amplify/amplify-cli#8779]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn add amplify-appsync-simulator

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

amplify-appsync-simulator@1.27.7

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

From Velocity's documentation:

> If you want to stop looping in a foreach from within your template, you can now use the #break directive to stop looping at any time:
> ## list first 5 customers only
> #foreach( $customer in $customerList )
>     #if( $velocityCount > 5 )
>         #break
>     #end
>     $customer.Name
> #end

$velocityCount is 1 based, so this implies that once $velocityCount is over 5, the line `$customer.Name` will not be called. This is in line with the behavior in AppSync.

In `amplify-appsync-simulator` however, that same line will be executed, and then the loop will exit.

### Expected behavior

Hitting a `#break` statement during a loop should exit it immediately.

### Reproduction steps

[sim-break.zip](https://github.com/aws-amplify/amplify-cli/files/7514978/sim-break.zip)
1. Unzip to empty folder
2. Go to sim-break folder
3. yarn
4. yarn test

The .vtl code in this snippet should break from the foreach loop when `$velocityCount` is equal to 2, but the following statement still gets called and a $velocityCount of 2 is added to the result.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by yuth** [comment]
@DavidCaya thank you for the bug report. This is an issue with our velocity implementation. I have marked this as a bug

**Comment by DavidCaya** [comment]
@yuth Thank you. I have tried to take a look at the issues I've added for the simulator, but I'm having a little difficulty navigating Velocity implementation's code.
