### ISSUE TITLE
amplify push command fails after some amount of success pushes with error "Could not access the Amazon S3 object"

### ISSUE THREAD

**Issue by vkurniavka** [aws-amplify/amplify-cli#8781]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:185187150882:apps/d3j5y35vsu5okt

### Region

us-east-2

### Amplify Console feature

Access control

### Describe the bug

I have create backend api for my amplify app using container-based deployments, with my custom docker file and update on every amplify push. For access I'm use AWS access keys because with AdminUI it not allows me to push, hoveever after some amount of successefuly pushes I got Deployment Failed with error in console: 
_"UPDATE_FAILED   DeploymentAwaiter                                                    AWS::CloudFormation::CustomResource Wed Nov 10 2021 15:34:26 GMT+0200 Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed  Logs: /aws/lambda/amplify-offshoredev-deva--AwaiterCustomCompleteHa
n-bsgpeVaQp7He      at Runtime.exports.handler (/var/task/index.js:102:13)     at processTicksAndRejections (internal/process/task_queues.js:97:5) (RequestId: 9f1b936d-5c44-47eb-a5f6-6
030670a999b)"_

hen I go to AWS CodePipeline select only one existing amplify pipeline I see error in source step "Amazone S3 failed" with error
**"Could not access the Amazon S3 object: "amplify-...181234-deployment/amplify-builds/...-3549362f50334e674778-build.zip". Make sure that the names of the bucket and object are both correct, and that the action IAM role has sufficient permissions to access this bucket."**
this build.zip exists and account I use can access it.

### Expected behavior

amplify push command should succesefuly push source to the s3

### Reproduction steps

1. amplify pull --appId ....
2. amplify configure project
   a) AWS Profile setting -> AWS access keys
3. amplify configure project
   a) Advanced -> container-based deployments -> yes
4. amplify add api
   a) REST
   b) API Gateway + AWS Fargate (Container-based)
   c) Custom (bring your own Dockerfile or docker-compose.yml)
   d)On every "amplify push" (Fully managed container source)
5. copy source
6. amplify push --yes
7. after some time execute again: amplify push --yes
8. After some amount of  success pushes like 6-8 every next push will failed

**Comment by yuth** [comment]
@vkurniavka, how are you getting the access and secret keys? Does the ones you get have session token?

**Comment by v-kurniavka** [comment]
@yuth, I create access key for my account in aws console then download it for use. No they doesn't, or I don't now how to find it

**Comment by mpashkovskiy** [comment]
Experience the same problem. To me it looked like it started to fail after Build step in the CodePipeline failed once. Build step failed because of a mistake in the REST API service code.

**Comment by mpashkovskiy** [comment]
Adding full access to bucket with zips (Dockerfile + source code of the service) to `ApiPipelinePipelineSourceCodePipelineActionRole*` in `amplify/backend/api/[SERVICE_NAME]/[SERVICE_NAME]-cloudformation-template.json` helped to fix the issue.

**Comment by owboateng** [comment]
> Adding full access to bucket with zips (Dockerfile + source code of the service) to `ApiPipelinePipelineSourceCodePipelineActionRole*` in `amplify/backend/api/[SERVICE_NAME]/[SERVICE_NAME]-cloudformation-template.json` helped to fix the issue.

Hi, could you please explain the steps. I am experiencing the same problem but I do not understand how you fixed the issue. Thank you.

**Comment by sachscode** [comment]
Based on the solution, looks like ApiPipelinePipelineSourceCodePipelineActionRole requires access to the deployment bucket but for some reason was created without it. marking this as a bug.

**Comment by edwardfoyle** [comment]
@vkurniavka Are you still experiencing issues here?

**Comment by Straubulous** [comment]
No response - closing

**Comment by jseun** [comment]
I am still experimenting the issue.  As soon as one build of my image fails, the next `amplify push` will not be able to complete and will output
```
🛑 The following resources failed to deploy:
Resource Name: DeploymentAwaiter (AWS::CloudFormation::CustomResource)
Event Type: update
Reason: Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed

Logs: /aws/lambda/amplify-nextcontainer-dev-AwaiterCustomCompleteHan-bNp0g7O4YByC

    at exports.handler (/var/task/index.js:103:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (RequestId: a511a985-e5af-4f9b-ae63-74f74dce5dce)
URL: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-west-2%3A858653473156%3Astack%2Famplify-nextcontainer-dev-f48ed-apinextcontainerapi-W4PN44FT0K45%2F7383f210-4179-11ef-a6fd-0ad26c1ddc3b/events


🛑 Resource is not in the state stackUpdateComplete
Name: DeploymentAwaiter (AWS::CloudFormation::CustomResource), Event Type: update, Reason: Received response status [FAILED] from custom resource. Message returned: The execution didn't succeed

Logs: /aws/lambda/amplify-nextcontainer-dev-AwaiterCustomCompleteHan-bNp0g7O4YByC

    at exports.handler (/var/task/index.js:103:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (RequestId: a511a985-e5af-4f9b-ae63-74f74dce5dce), IsCustomResource: false
```

And this will show up in Pipeline

![Screenshot 2024-07-15 at 11 00 36 AM](https://github.com/user-attachments/assets/098ad323-e4e8-4e31-9800-6af22bdc1112)
