### ISSUE TITLE
Api.swift file not generated

### ISSUE THREAD

**Issue by kvasukib** [aws-amplify/amplify-cli#879]
**Describe the bug**
Api.swift file is not created after Amplify Push.

**To Reproduce**
([following the AWS Amplify iOS Tutorial](https://aws-amplify.github.io/docs/ios/start))
Amplify Init
Amplify Push
Amplify  add api
Amplify Push

**Which AWS service(s) are affected?**
AMPLIFY

**Expected behavior**
After following the AWS Amplify 'Getting Started' tutorial, the 'api.swift' file is not  generated. I saw this was an issue in November and updated my NPM and Amplify to the latest versions, but it's still not working.

**Screenshots**
![screen shot 2019-02-14 at 4 11 55 pm](https://user-images.githubusercontent.com/17263996/52821040-4a740300-3073-11e9-81d4-47e1a1566c15.png)

<img width="1006" alt="screen shot 2019-02-14 at 4 08 30 pm" src="https://user-images.githubusercontent.com/17263996/52820886-d9cce680-3072-11e9-891e-21d45228d58e.png">

**Environment(please complete the following information):**
Xcode 10.1
Cocoapods
 Swift 4.2

**Device Information (please complete the following information):**
 - Device: iPhone Xs
 - iOS Version: 12.1.4

**Additional context**

Raising on behalf of @andrewdr

**Comment by yuth** [comment]
@andrewdr could you paste the configuration you have for codegen. Its stored in `.graphqlconfig.yml` file which is in the root of your project. 

Please obfuscate `graphQLApiId` and ` endpoints` when you paste the content

**Comment by yuth** [comment]
Closing this in favor of https://github.com/aws-amplify/aws-sdk-ios/issues/1236 as all the conversation is happening in that issue
