### ISSUE TITLE
All AppSync files backed up?

### ISSUE THREAD

**Issue by rygo6** [aws-amplify/amplify-cli#88]
I am just trying to better understand something here. I noticed in this path on my S3 bucket:
myapp-20180830150843-deployment/amplify-appsync-files

There are many many duplicates with names like this `Blog.posts.request.1535664903`

It looks like they are AppSync resolvers, and also it is making a new file here everytime I do amplify push. Is that correct? 

Why is amplify uploading all of my Appsync resolvers to S3?
Why is it uploading a duplicate of the same resolver everytime I push?

Is this some sort of automatic backup system? Is there anyway I can utilize this through the CLI?

**Comment by kaustavghosh06** [comment]
@rygo6 We are using Cloudformation to deploy the AppSync API and the corresponding data sources and your revolvers. Cloudformation has a limitation of total file size which limits the use of in-line resolvers within the Cloudformation template. 
The workaround for that would be to store the resolvers in S3 in your deployment bucket and then reference that in the Cloudformation templates deployed.

**Comment by kaustavghosh06** [comment]
Closing this issue for now. Feel free to re-open this if you still have further questions tied to this.
