### ISSUE TITLE
Sample Lambda with IAM permissions calling AppSync

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#8800]
Can someone please share a sample Lambda function (authorized with IAM permissions, this part is important!) that calls a mutation on AppSync.

It seems like such a trivial and often used code in Amplify, and it should be easy to find. But it's not anywhere. All sample code I can find is outdated and gives many errors, for example this Amplify blog entry:

https://aws.amazon.com/blogs/mobile/supporting-backend-and-internal-processes-with-aws-appsync-multiple-authorization-types/

**Comment by yuth** [comment]
Amplify has it documented [here](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#signing-a-request-from-lambda)

**Comment by skryshi** [comment]
Thank you, it's working.
