### ISSUE TITLE
Amplify pull/push fail 

### ISSUE THREAD

**Issue by krikork** [aws-amplify/amplify-cli#8826]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

6.4

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

env, pull, push

### Describe the bug

I have been deploying changes to the same amplify project (and backend environment) for a while. Earlier today I made some changes to one of my lambda functions and tried to run amplify push. The operation failed with the following mesage:

```
MacBook-Pro-2 core % amplify push
✖ There was an error pulling the backend environment sandboxb.
An error occurred during the push operation: invalid relative path: function/coreIntegrationsLayer/lib/nodejs/node_modules/.bin/../uuid/bin/uuid
```

Attempting to pull from the backend environment will produce the same error.

I tried to create a new folder and pull the amplify project there in order to start from scratch but resulted in the same issue. Here is the log output:

```
% amplify pull --appId XXXXXXX --envName YYYYY
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Amplify AppID found: XXXXXXX. Amplify App name is: YYYYY
Backend environment sandbox found in Amplify Console app: YYYYY
Failed to pull the backend.
invalid relative path: function/coreIntegrationsLayer/lib/nodejs/node_modules/.bin/../uuid/bin/uuid
Error: invalid relative path: function/coreIntegrationsLayer/lib/nodejs/node_modules/.bin/../uuid/bin/uuid
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/yauzl/index.js:426:70
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/yauzl/index.js:631:5
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:561:5)
```

### Expected behavior

Making simple cold changes. I was able to deploy the same love the function using the same method just a few hours earlier.

### Reproduction steps

See above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by yuth** [comment]
@krikork  From the error message it looks like there was some installation issue in the library Amplify CLI uses. Could you uninstall and reinstall Amplify CLI using the latest version of NPM

**Comment by krikork** [comment]
It is not an installation issue. It appears to be something with the state saved on s3. My teammates started getting the issue after I did. None of us had changed the cli version for a while.

**Comment by yuth** [comment]
@krikork could you see if this happens with different projects as the stack trace seems to indicate to have issues with importing packages.

If this is because of something in the S3, was there was some modification to the bucket and its contents?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response and further communication.
