### ISSUE TITLE
Amplify push throwing an error when creating a new API

### ISSUE THREAD

**Issue by chrisbrine** [aws-amplify/amplify-cli#883]
**Describe the bug**
When AWS Amplify is running amplify push it is not completing and creating an error. I previously was receiving a different error that is already in the bug report, but since I want to continue working I deleted the API and tried to start again from scratch with the API. But now I'm getting an entirely new error.

**To Reproduce**
1. Run 'amplify push'

**Expected behavior**
To successfully push the GraphQL API to AWS.

**Screenshots**

**GraphQL schema**
type Users @model(
	queries: { get: "getUser", list: "getUsers" },
	mutations: { create: "addUser", update: "editUser", delete: "deleteUser" },
	subscriptions: { onCreate: "onAddUser", onUpdate: "onEditUser", onDelete: "onDeleteUser" }
) @auth(
	rules: [
		{allow: owner},
		{allow: groups, groups: ["Admin"]}
	]
) {
	id: ID!
	owner: String
	createdAt: String
	updatedAt: String
	email: String
	emailVerified: Boolean
	phone_number: String
	phone_numberVerified: Boolean
	data: AWSJSON
}

**Amplify PUSH**
Alpha:bento4me chrisbrine$ amplify push

Current Environment: master

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | bento4megraphql | Create    | awscloudformation |
| Auth     | bento4me        | No Change | awscloudformation |
? Are you sure you want to continue? Yes

GraphQL schema compiled successfully.
Edit your schema at /Users/chrisbrine/Library/Mobile Documents/com~apple~CloudDocs/projects/bento4me/amplify/backend/api/bento4megraphql/schema.graphql or place .graphql files in a directory at /Users/chrisbrine/Library/Mobile Documents/com~apple~CloudDocs/projects/bento4me/amplify/backend/api/bento4megraphql/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Choose the code generation language target javascript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.js
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter the maximum depth of statements to be generated 2
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    authbento4me            AWS::CloudFormation::Stack Fri Feb 15 2019 17:05:46 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS authbento4me            AWS::CloudFormation::Stack Fri Feb 15 2019 17:05:46 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS bento4me-20190212090627 AWS::CloudFormation::Stack Fri Feb 15 2019 17:05:41 GMT-0800 (Pacific Standard Time) User Initiated
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS apibento4megraphql AWS::CloudFormation::Stack Fri Feb 15 2019 17:05:50 GMT-0800 (Pacific Standard Time)
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    GraphQLSchema                                           AWS::AppSync::GraphQLSchema Fri Feb 15 2019 17:06:02 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE    GraphQLAPIKey                                           AWS::AppSync::ApiKey        Fri Feb 15 2019 17:06:00 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS GraphQLAPIKey                                           AWS::AppSync::ApiKey        Fri Feb 15 2019 17:05:58 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS GraphQLSchema                                           AWS::AppSync::GraphQLSchema Fri Feb 15 2019 17:05:58 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS bento4me-20190212090627-apibento4megraphql-HRZR54E1Y26O AWS::CloudFormation::Stack  Fri Feb 15 2019 17:05:51 GMT-0800 (Pacific Standard Time) User Initiated
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS Users AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:06 GMT-0800 (Pacific Standard Time)
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE Users AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:29 GMT-0800 (Pacific Standard Time)
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS                  apibento4megraphql                                      AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:43 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS bento4me-20190212090627                                 AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:42 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE                     apibento4megraphql                                      AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:39 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS bento4me-20190212090627-apibento4megraphql-HRZR54E1Y26O AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:37 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE                     CustomResourcesjson                                     AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:34 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS                  CustomResourcesjson                                     AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:33 GMT-0800 (Pacific Standard Time)
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    bento4me-20190212090627-apibento4megraphql-HRZR54E1Y26O AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:57 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE    Users                                                   AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:57 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS Users                                                   AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:46 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE    CustomResourcesjson                                     AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:45 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS CustomResourcesjson                                     AWS::CloudFormation::Stack Fri Feb 15 2019 17:06:45 GMT-0800 (Pacific Standard Time)
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE apibento4megraphql AWS::CloudFormation::Stack Fri Feb 15 2019 17:07:05 GMT-0800 (Pacific Standard Time)
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    bento4me-20190212090627 AWS::CloudFormation::Stack Fri Feb 15 2019 17:07:07 GMT-0800 (Pacific Standard Time)
UPDATE_COMPLETE    authbento4me            AWS::CloudFormation::Stack Fri Feb 15 2019 17:07:07 GMT-0800 (Pacific Standard Time)
UPDATE_IN_PROGRESS authbento4me            AWS::CloudFormation::Stack Fri Feb 15 2019 17:07:06 GMT-0800 (Pacific Standard Time)
⠴ Updating resources in the cloud. This may take a few minutes...⠋ Generating GraphQL operations2019-02-16T01:07:15.953Z - error: uncaughtException: `e` has already been exported. Exported identifiers must be unique. (116:16)
  114 | }
  115 | `;
> 116 |   export const e =  `subscription E {
      |                ^
  117 |   E {
  118 |     id
  119 |     owner date=Fri Feb 15 2019 17:07:15 GMT-0800 (Pacific Standard Time), pid=65158, uid=501, gid=20, cwd=/Users/chrisbrine/Library/Mobile Documents/com~apple~CloudDocs/projects/bento4me, execPath=/usr/local/bin/node, version=v11.2.0, argv=[/usr/local/bin/node, /usr/local/bin/amplify, push], rss=113934336, heapTotal=80031744, heapUsed=57355072, external=1027663, loadavg=[1.2265625, 1.35400390625, 1.43310546875], uptime=357469, trace=[column=264, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-babylon.js, function=t, line=1, method=null, native=false, column=208428, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-babylon.js, function=Object.parse, line=1, method=parse, native=false, column=19, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.parse$2 [as parse], line=10639, method=parse$2 [as parse], native=false, column=23, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=coreFormat, line=13856, method=null, native=false, column=73, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=format, line=14115, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=formatWithCursor, line=14131, method=null, native=false, column=15, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=null, line=42399, method=null, native=false, column=12, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js, function=Object.format, line=42418, method=format, native=false, column=19, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=format, line=131, method=null, native=false, column=10, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=render, line=98, method=null, native=false], stack=[SyntaxError: `e` has already been exported. Exported identifiers must be unique. (116:16),   114 | },   115 | `;, > 116 |   export const e =  `subscription E {,       |                ^,   117 |   E {,   118 |     id,   119 |     owner,     at t (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-babylon.js:1:264),     at Object.parse (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/parser-babylon.js:1:208428),     at Object.parse$2 [as parse] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:10639:19),     at coreFormat (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:13856:23),     at format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:14115:73),     at formatWithCursor (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:14131:12),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:42399:15,     at Object.format (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/prettier/index.js:42418:12),     at format (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:131:19),     at render (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:98:10)]
Alpha:bento4me chrisbrine$

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: most recent

**Additional context**
It doesn't appear to be working at all at the moment. Is there any workaround at least so that I can continue working? Thank you.

**Comment by kaustavghosh06** [comment]
@chrisbrine Could you please share your annotated GraphQL schema?

**Comment by chrisbrine** [comment]
I only have one model so far as I'm slowly building up the site. It is:

type Users @model(
	queries: { get: "getUser", list: "getUsers" },
	mutations: { create: "addUser", update: "editUser", delete: "deleteUser" },
	subscriptions: { onCreate: "onAddUser", onUpdate: "onEditUser", onDelete: "onDeleteUser" }
) @auth(
	rules: [
		{allow: owner},
		{allow: groups, groups: ["Admin"]}
	]
) {
	id: ID!
	owner: String
	createdAt: String
	updatedAt: String
	email: String
	emailVerified: Boolean
	phone_number: String
	phone_numberVerified: Boolean
	data: AWSJSON
}

I see that it outputted, in the build, as:

type Users {
  id: ID!
  owner: String
  createdAt: String
  updatedAt: String
  email: String
  emailVerified: Boolean
  phone_number: String
  phone_numberVerified: Boolean
  data: AWSJSON
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelUsersConnection {
  items: [Users]
  nextToken: String
}

input ModelStringFilterInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
}

input ModelIDFilterInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
}

input ModelIntFilterInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  contains: Int
  notContains: Int
  between: [Int]
}

input ModelFloatFilterInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  contains: Float
  notContains: Float
  between: [Float]
}

input ModelBooleanFilterInput {
  ne: Boolean
  eq: Boolean
}

input ModelUsersFilterInput {
  id: ModelIDFilterInput
  owner: ModelStringFilterInput
  createdAt: ModelStringFilterInput
  updatedAt: ModelStringFilterInput
  email: ModelStringFilterInput
  emailVerified: ModelBooleanFilterInput
  phone_number: ModelStringFilterInput
  phone_numberVerified: ModelBooleanFilterInput
  data: ModelStringFilterInput
  and: [ModelUsersFilterInput]
  or: [ModelUsersFilterInput]
  not: ModelUsersFilterInput
}

type Query {
  getUser(id: ID!): Users
  getUsers(filter: ModelUsersFilterInput, limit: Int, nextToken: String): ModelUsersConnection
}

input CreateUsersInput {
  id: ID
  owner: String
  createdAt: String
  updatedAt: String
  email: String
  emailVerified: Boolean
  phone_number: String
  phone_numberVerified: Boolean
  data: AWSJSON
}

input UpdateUsersInput {
  id: ID!
  owner: String
  createdAt: String
  updatedAt: String
  email: String
  emailVerified: Boolean
  phone_number: String
  phone_numberVerified: Boolean
  data: AWSJSON
}

input DeleteUsersInput {
  id: ID
}

type Mutation {
  addUser(input: CreateUsersInput!): Users
  editUser(input: UpdateUsersInput!): Users
  deleteUser(input: DeleteUsersInput!): Users
}

type Subscription {
  o: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  n: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  A: Users @aws_subscribe(mutations: ["addUser"])
  d: Users @aws_subscribe(mutations: ["addUser", "editUser"])
  U: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  s: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  e: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  r: Users @aws_subscribe(mutations: ["addUser", "editUser", "deleteUser"])
  E: Users @aws_subscribe(mutations: ["editUser"])
  i: Users @aws_subscribe(mutations: ["editUser"])
  t: Users @aws_subscribe(mutations: ["editUser", "deleteUser"])
  D: Users @aws_subscribe(mutations: ["deleteUser"])
  l: Users @aws_subscribe(mutations: ["deleteUser"])
}

**Comment by chrisbrine** [comment]
What it looks to me is it is messing up on the Subscription portion. It is breaking apart the string into multiple characters instead of taking the full string for some reason. Unless there is a different formatting method for subscriptions than for mutations and queries? There's nothing I saw in the documentation that indicates this unless I missed something.

**Comment by chrisbrine** [comment]
Ok it is definitely that that is the problem.  I see that when listing subscription functions it is expected to be in an array in brackets so I can see that it is just a matter of different formatting. So it does work but looks differently. I might recommend making sure this is added to the @models section of the documentation on the site. :) But at least now I get what the issue was.

**Comment by chrisbrine** [comment]
Meaning when I changed the subscriptions line in the @model to:
subscriptions: { onCreate: ["onAddUser"], onUpdate: ["onEditUser"], onDelete: ["onDeleteUser"] }
It then worked.

**Comment by kaustavghosh06** [comment]
@chrisbrine  Thanks for letting us know. We'll add this to our documentation. Please let us know if you're still stuck on something.
