### ISSUE TITLE
@connection codegen missing connection id

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#884]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync, Amplify

** Provide additional details e.g. code snippets **
I have a 1-N relation: 1 inventory can have N items. Define `amplify/backend/api/<app-name>/schema.graphql`:
```graphql
type Item @model {
  id: ID!
  name: String!
}

type Inventory @model {
  id: ID!
  name: String!
  items: [Item] @connection
}
```
Generated code in `amplify/backend/api/<app-name>/build/schema.graphql`:
```graphql
type Item {
  id: ID!
  name: String!
}

type Inventory {
  id: ID!
  name: String!
  items(filter: ModelItemFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelItemConnection
}

input CreateItemInput {
  id: ID
  name: String!
  inventoryItemsId: ID
}

input UpdateItemInput {
  id: ID!
  name: String
  inventoryItemsId: ID
}
```
`inventoryItemsId` is in generated type `CreateItemInput`, `UpdateItemInput`, and also in DynamoDB table `Item`, but not in generated type `Item`. I do find having `inventoryItemsId` in `type Item` extremely useful.

Questions:
1. Is there a specific reason not including `inventoryItemsId` with `type Item`? 
1. What is the walkaround to include `inventoryItemsId` in `type Item`?

**Comment by YikSanChan** [comment]
Updates: I tried below annotated graphql schema
```graphql
type Item @model {
  id: ID!
  name: String!
  inventory: Inventory @connection(name: "InventoryItems")
}

type Inventory @model {
  id: ID!
  name: String!
  items: [Item] @connection(name: "InventoryItems")
}
```
and `amplify api gql-compile` generates below schema:
```graphql
type Item {
  id: ID!
  name: String!
  inventory: Inventory
}

type Inventory {
  id: ID!
  name: String!
  items(filter: ModelItemFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelItemConnection
}

input CreateItemInput {
  id: ID
  name: String!
  itemInventoryId: ID
}

input UpdateItemInput {
  id: ID!
  name: String
  itemInventoryId: ID
}
```
Haven't tried `amplify push` yet. Will update once I get the chance to push

**Comment by mikeparisstuff** [comment]
Hey @YikSanChan. Your update is exactly what I would suggest with one addition. Due to a limitation in DynamoDB, you will need to make this change in two steps. Whenever you are making a change to an existing @connection field you should first push the project without the @connection.

```graphql
type Item @model {
  id: ID!
  name: String!
}

type Inventory @model {
  id: ID!
  name: String!
}
```

and push via `amplify push`. After you have removed the @connection, you can then re-add the @connection.

```graphql
type Item @model {
  id: ID!
  name: String!
  inventory: Inventory @connection(name: "InventoryItems")
}

type Inventory @model {
  id: ID!
  name: String!
  items: [Item] @connection(name: "InventoryItems")
}
```

and push via `amplify push`.

PS. You can always add the `itemInventoryId` field directly to the Item type itself as well.

```
type Item @model {
  id: ID!
  name: String!
  itemInventoryId: ID!
}
```

**Comment by YikSanChan** [comment]
@mikeparisstuff Thank you.
