### ISSUE TITLE
Transform full graphql schema from schema.graphql with directives

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#885]
**Is your feature request related to a problem? Please describe.**
When initializing Amplify Graphql API, need to edit the `schema.graphql`, e.g.,
```graphql
type Item @model {
  id: ID!
  name: String!
}

type Inventory @model {
  id: ID!
  name: String!
  items: [Item] @connection
}
```
Then the SDL will be converted into a **full** graphql schema like below. It takes time, and many jobs running on the cloud.
```graphql
type Item {
  id: ID!
  name: String!
}

type Inventory {
  id: ID!
  name: String!
  items(filter: ModelItemFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelItemConnection
}

input CreateItemInput {
  id: ID
  name: String!
  inventoryItemsId: ID
}

input UpdateItemInput {
  id: ID!
  name: String
  inventoryItemsId: ID
}

...
```

**Describe the solution you'd like**
Would be great if the full schema graphql can be generated and return without going through the backend cloud services setup process. I believe 1:1 relation between the 2 schemas exist and can be determined statically.

**Comment by lennybr** [comment]
@YikSanChan if you are just looking to **only** compile the SDL, you can do that quickly by running the `amplify api gql-compile` command.

**More details from the [docs](https://aws-amplify.github.io/docs/cli/graphql?sdk=js):**

If you want to update your API, open your project’s `backend/api/~apiname~/schema.graphql` file (NOT the one in the `backend/api/~apiname~/build` folder) and edit it in your favorite code editor. You can compile the `backend/api/~apiname~/schema.graphql` by running:

```
amplify api gql-compile
```

and view the compiled schema output in ``backend/api/~apiname~/build/schema.graphql``.
