### ISSUE TITLE
Migration failed, reverted but AppSync API stop working

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#888]
**Describe the bug**
As title. Please help me figure out:
- How to restore the app.
- How to successfully migrate.

**To Reproduce**
1. `amplify env`
2. Migration. See [the full log](https://gist.github.com/YikSanChan/968f00c6a8a2485aaf8c33d6d9b33bac)
3. Automatic rollback due to migration failure. (`git status` shows no local change, all DynamoDB tables remain the same)
4. AppSync API broken. Previously working API doesn't work now (return null).

**Expected behavior**
AppSync API should work as it did.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
This breaks my working app. @mikeparisstuff Not sure if it is related but after migration:

## Lose all resolvers
![image](https://user-images.githubusercontent.com/17229109/52978406-068c4100-3386-11e9-8501-42557ab5abbf.png)

## There exists only 1 data sources (I don't remember how many did I have before migration):
![image](https://user-images.githubusercontent.com/17229109/52978448-31769500-3386-11e9-8bf7-0bc3694aaff4.png)

**Comment by mikeparisstuff** [comment]
Can you please provide more details on the migration including any error messages or CloudFromation stack details?

**Comment by YikSanChan** [comment]
You can find all the details in [the full log](https://gist.github.com/YikSanChan/968f00c6a8a2485aaf8c33d6d9b33bac). Let me know if you need anything else. Thanks!

**Comment by YikSanChan** [comment]
@mikeparisstuff Not sure if it is related but after migration:

## Lose all resolvers

![image](https://user-images.githubusercontent.com/17229109/52978406-068c4100-3386-11e9-8501-42557ab5abbf.png)

There exists only 1 data sources (I don't remember how many did I have before migration):

![image](https://user-images.githubusercontent.com/17229109/52978448-31769500-3386-11e9-8bf7-0bc3694aaff4.png)

**Comment by mikeparisstuff** [comment]
Thanks for the information. It appears that the migration failed because of an AppSync function that references a data source that was being moved during the migration. The migration takes place in two steps and first removes resolvers & data sources before recreating them under a new project structure.

You should be able to unblock yourself by removing the functions that reference the data source, removing the data source, and then re-running push. Before you do that however, can you share what your current project structure looks like? Do you see a transform.conf.json in your project directory? Thanks.

**Comment by YikSanChan** [comment]
Thanks for the fast response, @mikeparisstuff 

I don't have `transform.conf.json` in my project directory. As I mentioned above, `git status` shows no change after migration rollback. This is the full project structure in my app folder: https://gist.github.com/YikSanChan/dda8e56778dd809223563b0da49b0aed

**Comment by mikeparisstuff** [comment]
From that gist, it appears that you no longer have a schema.graphql in your api directory? Is that true?

**Comment by YikSanChan** [comment]
@mikeparisstuff My apology, I don't print files. Now we will be able to see schema.grapqhl

**Comment by kaustavghosh06** [comment]
@YikSanChan I think this issue is similar to this - https://github.com/aws-amplify/amplify-cli/issues/881

**Comment by YikSanChan** [comment]
@kaustavghosh06 It sounds correct. Anyway, I will do what @mikeparisstuff told me: remove the function, remove the data source, re-push and see if it works (I am not worried about this because the function is no longer in use). If it works, I will re-migrate and see the results.

**Comment by mikeparisstuff** [comment]
Great! Glad this is working now. I have reproduced the issue and will work on a fix for the revert so no one else runs into the strange intermediate state.

**Comment by YikSanChan** [comment]
Thank you @mikeparisstuff ! Feel free to close the issue :)
