### ISSUE TITLE
Cannot perform more than one GSI creation or deletion in a single update - with enableIterativeGSIUpdates set to true

### ISSUE THREAD

**Issue by vineethbhargavan** [aws-amplify/amplify-cli#8883]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2wbvui32pghee

### Region

ap-southeast-2

### Amplify Console feature

Backend builds

### Describe the bug

According to this blog :
https://aws.amazon.com/about-aws/whats-new/2021/04/aws-amplify-orchestrates-multiple-amazon-dynamodb-gsi-updates-single-deployment/

I was hoping the multiple GSI update issue is resolved! ..but it still keeps coming.
![image](https://user-images.githubusercontent.com/12675696/141735585-a56cfc50-7f4a-4662-81a2-16b0e22ce807.png)

From the above diagram:
Changing the GSI name from : byTypeAndMode to byClassTypeAndModeType , leads to the following error, upon amplify push.
`
Resource Name: PlanType-XXX
(AWS::DynamoDB::Table)
Event Type: update
Reason: Cannot perform more than one GSI creation or deletion in a single update

`

cli.json (not sure if we need any more attributes?)
`
{
    "features": {
      "graphQLTransformer": {
        "enableIterativeGSIUpdates": true
      }
    }
  }
`
If this is not a bug, appreciate if we can have this feature in amplify.
Thanks
Vineeth.

### Expected behavior

https://aws.amazon.com/about-aws/whats-new/2021/04/aws-amplify-orchestrates-multiple-amazon-dynamodb-gsi-updates-single-deployment/

### Reproduction steps

1. Create a GSI
2. Amplify push
3. Rename the GSI
4. amplify push

**Comment by edwardfoyle** [comment]
Hi @vineethbhargavan setting that Feature Flag should be all that's required to get this working. Are you pushing in a CI/CD environment? And if so, is your `cli.json` file checked into your repo / present in the CI/CD environment?

**Comment by vineethbhargavan** [comment]
Yes @edwardfoyle - Cli.json is checked in. The changes are pushed to Aws Code Commit - which in turn is being pulled by Amplify - this is the CI CD we have.

**Comment by vineethbhargavan** [comment]
The other thing  is , when this error happens...Amplify does a rollback - And while it does rollback most of the resources - any GSI created during the amplify push doesn't get rolled back!!! FYI - this behaviour happens all the time!!(probably i should create a separate bug for this) - if amplify detects a GSI update and the amplify push fails for whatever reason - the rollback fails to remove the GSI. One has to manually remove it!  Else subsequent amplify push will fail citing the reason - GSI already exists.

**Comment by Straubulous** [comment]
vineethbhargavan - please create a separate issue for your last comment. Closing this one
