### ISSUE TITLE
Support CDK override for API (REST)

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-cli#8884]
Version 7 of the CLI introduced support for CDK override of some categories like Auth & Storage. With this issue I'd like to propose to support API (REST) next. This would unlock things like [data transformations in VTL](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html) (already supported for GraphQL), [request validation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html) settings, [OpenAPI support](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), and all kinds of [integration types](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-integration-settings.html).

**Comment by jhockett** [comment]
Hi @dreamorosi, we just launched override support for the api category in version `7.5.0`. Feedback is appreciated!

[REST override docs](https://docs.amplify.aws/cli/restapi/override/)
