### ISSUE TITLE
7.3.1 - amplify push auth failed - triggers

### ISSUE THREAD

**Issue by daniellorenzin** [aws-amplify/amplify-cli#8885]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.3.1

### What operating system are you using?

Mac

### Amplify Categories

auth, function

### Amplify Commands

push

### Describe the bug

When a custom message or post confirmation trigger is added there is a bad reference in the generated CloudFormation.

`UPDATE_FAILED      auth<project> AWS::CloudFormation::Stack Tue Nov 16 2021 11:37:19 GMT+1100 (Australian Eastern Daylight Time) Template error: instance of Fn::GetAtt references undefined resource Userpool`

Generated template:
 `"UserPoolCustomMessageLambdaInvokePermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "FunctionName": {
          "Ref": "<project>CustomMessage"
        },
        "Principal": "cognito-idp.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "Userpool",
            "Arn"
          ]
        }
      }
    },
    "UserPoolPostConfirmationLambdaInvokePermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "FunctionName": {
          "Ref": "<project>PostConfirmation"
        },
        "Principal": "cognito-idp.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "Userpool",
            "Arn"
          ]
        }
      }
    },`

### Expected behavior

It builds the reference as `Userpool` but it should be `UserPool`

### Reproduction steps

Add custom trigger to auth module.

run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@daniellorenzin Yes, we're aware of this issue and in the process of rolling out a fix. 
Here's the fix which we just merged - https://github.com/aws-amplify/amplify-cli/pull/8879 
Closing as a dup of https://github.com/aws-amplify/amplify-cli/issues/8870

**Comment by daniellorenzin** [comment]
Great thanks
