### ISSUE TITLE
Expose Custom Resources Outputs into aws-exports.js

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-cli#8886]
### Describe the feature you'd like to request

With Amplify CLI Customers can define custom resources via CloudFormation & AWS CDK and these resources can reference the ones created by Amplify. At the moment though, interacting with these resources from the application requires Customers to pass the name/identifier of that resource somewhat manually. 
Similarly to what already happens for resources created via Amplify, the CLI could add to the `was-exports.js` file all the outputs of the custom resources stacks, so that the application can be aware of them.

### Describe the solution you'd like

Given a custom category `myAwesomeCategory` defined in the `amplify` folder, all the outputs for that stack would be injected in the `was-exports.js` generated by Amplify CLI after pushing.

```
"Outputs" : {
  "XXXXXXXXXXX" : {
    "Description" : "Information about the value",
    "Value" : "value1",
    "Export" : {
      "Name" : "outputA"
    }
  },
  "YYYYYYYYYY" : {
    "Description" : "Information about the value",
    "Value" : "value2",
    "Export" : {
      "Name" : "outputB"
    }
  }
}
```
Would result in something like this:
```
{
   ... /* Amplify Categories */
  "myAwesomeCategory": {
     "outputA": "value1",
    "outputB": "value2"
  }
}
```

Ideally these values would then be available within the Amplify Libraries, but even just having them in the `was-exports.js` file would be super helpful.

### Describe alternatives you've considered

Using specific naming conventions, hardcoding names in the application, injecting the values at build/deploy time, all of which are cumbersome in their own way given that Amplify CLI clearly knows these values and is already generating the config file.

### Additional context

This could help in cases in which Customers are interacting directly with an AWS resource through the SDK, for example in the case of secrets, feature flags, of for instance missing features for existing Amplify categories (i.e. Amazon Location Service's Route Calculator or Geofences that are not yet available in Geo).

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by kaustavghosh06** [comment]
You can use post-push command hooks to fetch the CloudFormation outputs from any stack and put it in any client file you'd like.  You can read more about lifecycle hooks here - https://docs.amplify.aws/cli/project/command-hooks/

**Comment by kaustavghosh06** [comment]
@dreamorosi  Please let us know if you above would not work for your use-case and we will re-open this issue. Thank you!
