### ISSUE TITLE
Migration 6.4.0->7.3.2 - Amplify Init existing environment issue

### ISSUE THREAD

**Issue by batical** [aws-amplify/amplify-cli#8892]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.11.1

### Amplify CLI Version

7.3.2

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

init

### Describe the bug

Update the new CLI (same issue was reproductible with 7.3.1 version)

amplify init-> Select Env

#3746 was not helpfull

### Expected behavior

Init the env

### Reproduction steps

update CLI
amplify init

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../../amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/CustomMessage.map.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at AmplifyToolkit.getTriggerMetadata [as _getTriggerMetadata] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:404:85)
    at AmplifyToolkit.getTriggerEnvInputs [as _getTriggerEnvInputs] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:489:36)
    at initTriggerEnvs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:434:43)
    at Object.updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:380:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:132:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

</details>

### Additional information
When the CI start the push action, it also failed on this
```
UPDATE_FAILED               storage***mediastorage           AWS::CloudFormation::Stack Mon Nov 15 2021 14:31:37 GMT+0000 (Coordinated Universal Time) Parameters: [triggerFunction] must have values    
```
_No response_

**Comment by kaustavghosh06** [comment]
@batical What are the contents of your files in the `amplify/backend/storage` folder?

**Comment by javiermartingonzalez** [comment]
@batical For the push action, try in `amplify/backend/storage`, next enter the folder that giving that error and from `parameters.json` remove the following:

`    "triggerFunction": "NONE"`

**Comment by batical** [comment]
I wil give a try today. Thanks.

**Comment by batical** [comment]
as @javiermartingonzalez  suggested I remove in parameters the line 
`"triggerFunction": "NONE"`

But I also add to remove in `s3-cloudformation-template`

```
"triggerFunction": {
	"Type": "String"
}
```

then 
`amplify push` on my computer -> OK
`amplify env pull` --restore -> ok

and finnaly 
`Push using GitHub action ` -> ok

thanks for your help. Closing it
