### ISSUE TITLE
Migration 6.4.0->7.3.2 S3 storage bucket name changed. Critical!!!

### ISSUE THREAD

**Issue by ray415** [aws-amplify/amplify-cli#8893]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.3.2

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

push

### Describe the bug

After deploying the front-end updates today using the `latest` version (7.3.2) the links to S3 files are broken. We fetch the link to the file using the code below:
`Storage.get('<directory_name>/logos/${logo_filename}', {level: "public"})`

It turned out that Amplify created a new bucket and is now referencing this new bucket. Looking at this new bucket name it seems more like a bug than a planned update:

Environment name: `staging`
Old bucket name: `<bucketName>-staging`
New bucket name: `<bucketName>staging-staging`

No changes are being made in `amplify/backend/storage/..../parameters.json` and the `"bucketName"` value is still the initial one.

This is a **major** blocker currently because we can't use the older version of Amplify as it throws some incompatibility errors.

How can we use the Amplify service in our production environments if these kinds of bugs are getting to the production version of an AWS service?

### Expected behavior

Amplify CLI should use the initial bucket name for the S3 storage service in a format `"bucketName-${env}"`

### Reproduction steps

Do `amplify push` using old version (6.4.0) and then using a new version (7.3.2)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ray415** [comment]
In the meantime Amplify v. 7.3.3 came out. Using the `latest` tag in the build settings we are getting this buildtime error now:
```
Following resources failed
    Resource Name: <bucketName>staging (AWS::S3::Bucket)
    Event Type: update 
    Reason: <bucketName>-staging already exists
```

**Comment by ray415** [comment]
@kaustavghosh06, @sachscode  thank you for looking into this and applying a bugfix!

But...
did you test it also before deploying a bugfix? I mean exactly my case where we already have a bucket? After upgrading to 7.3.4 we get the following errors:

```
UPDATE_IN_PROGRESS          S3Bucket AWS::S3::Bucket            
Wed Nov 17 2021 08:57:32 GMT+0000 (Coordinated Universal Time) Requested update requires the creation of a new 
physical resource; hence creating one.

UPDATE_FAILED   S3Bucket    AWS::S3::Bucket            Wed Nov 17 2021 08:57:32
GMT+0000 (Coordinated Universal Time) <bucketName>-staging already exists

UPDATE_ROLLBACK_IN_PROGRESS amplify-<apiName>-staging-173138-storages3ff95c5ff-A2VLVJAJRE2P 
AWS::CloudFormation::Stack Wed Nov 17 2021 08:57:33 GMT+0000 (Coordinated Universal Time) The following 
resource(s) failed to update: [S3Bucket].

2021-11-17T08:57:45.161Z [INFO]: 
2021-11-17T08:57:45.162Z [INFO]: UPDATE_FAILED               storages3ff95c5ff                  AWS::CloudFormation::Stack 
Wed Nov 17 2021 08:57:42 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:us-east-
2:625262942667:stack/amplify-<apiName>-staging-173138-storages3ff95c5ff-A2VLVJAJRE2P/2a7bda00-5bff-11eb-
942e-0230bd8e0e32 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The
 following resource(s) failed to update: [S3Bucket].

UPDATE_ROLLBACK_IN_PROGRESS amplify-<apiName>-staging-173138 AWS::CloudFormation::Stack Wed Nov 17 2021
 08:57:42 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [storages3ff95c5ff].
```

The same error appears with 7.3.5 and 7.3.6. Why is it trying to create a new resource if it's already created before? Does that mean that everyone who's trying to do `amplify push` with "legacy" Amplify apps are having this issue?

**Comment by ray415** [comment]
@kaustavghosh06, @sachscode do you have any ideas for a quick fix? Our development cycle is currently affected by this issue because we can't deploy any updates to this environment.

**Comment by kaustavghosh06** [comment]
@ray415 Sorry for the trouble. Yes, we can help you getting unblocked. Which version of the CLI are you using right now? Given the current situation, would recommend doing the following list of steps. We have a few options out here

**Use the new bucket created with the convention <bucketName>staging-staging for this current environment**

1.  Move to the latest version of the Amplify CLI (7.5.0+)
2. amplify env pull --restore
3. Confirm that you see amplify/backend/storage/cli-inputs.json file (if not - then run `amplify update storage` and confirm your settings and see if this file gets generated).
4. amplify push --force to confirm that your deployment is successful
5. Install AWS CLI and copy contents from the older bucket to the newer bucket using this command `aws s3 sync s3://FROM_BUCKET s3://TO_BUCKET`

For any other environment moving forward, we have taken care of the bucket-names with the fix mentioned above.

**Use the older bucket - <bucketName>-staging**
1.  Move to the latest version of the Amplify CLI (7.5.0+)
2. amplify env pull --restore
3. amplify storage remove (removes storage locally)
4. amplify import storage (https://docs.amplify.aws/cli/storage/import/) and select the older bucket
5. amplify push 

With the second approach you would be loosing out on updating the storage resource via the CLI once it is imported, hence would recommend the first option. But if you absolutely want the same naming convention as before, then would second option. Unfortunately there is no way in CloudFormation (which is the deployment service we use under the hood) to associate an existing bucket once it disassociates with itself.

**Comment by ray415** [comment]
@kaustavghosh06, thank you for the feedback! For the other environments, we are using CLI v. 6.4.0 as it is the latest stable one without any issues. For this environment, we used the "latest" tag in the build settings, so it was updated from 6.4.0 to 7.3.2. Later we also tried with 7.3.5 and 7.3.6.

Before trying out the options you described I would like to specify some details:
> With the second approach you would be loosing out on updating the storage resource

What do you mean exactly by that? Does it mean that if we want to do `amplify storage update` it's not possible with the second approach?

What if we back up the files from the initial bucket, delete the bucket, and let it be recreated by the CloudFormation service like it's trying to do currently? Would that work?

**Comment by kaustavghosh06** [comment]
Yes, that approach should also work. But please make sure to backup the files correctly with that approach.

**Comment by kaustavghosh06** [comment]
@ray415 Were you able to get back on track?

**Comment by ray415** [comment]
@kaustavghosh06, thank you! Deleting the bucket worked.
