### ISSUE TITLE
Override S3 Auth Public Policy

### ISSUE THREAD

**Issue by javiermartingonzalez** [aws-amplify/amplify-cli#8894]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

S3 Storage

**Amplify CLI Version** 

7.3.3

**What AWS Services are you utilizing?**

S3 Bucket

**Provide additional details e.g. code snippets**

Hello, I want to put "s3:putObjectAcl" permission to IAM rule "public_policy". Before last Amplify changes, it was possible on parameters.json file -> `s3PermissionsAuthenticatedPublic": "s3:PutObject,s3:PutObjectAcl,s3:GetObject"`

But after new Amplify version, that file no longer exists. Looking for a solution, I found override posibility (https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-s3-resources) but I'm not able to find the correct value for my task.

Tested without success:

`resources.s3AuthPublicPolicy.s3PermissionsAuthenticatedPublic = "s3:PutObject,s3:PutObjectAcl,s3:GetObject"
`
`resources.s3AuthPublicPolicy = "s3:PutObject,s3:PutObjectAcl,s3:GetObject"
`
```
resources.s3AuthPublicPolicy.s3PermissionsAuthenticatedPublic = [
        "s3:PutObject",
        "s3:PutObjectAcl",
        "s3:GetObject"
    ]
```

What is the right way to add that permission via Amplify and not using AWS Console? Thank you

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez For a change o this high-level, you can go into the `amplify/backend/storage/cli-inputs.json` file and make the change and then run `amplify push`. Let me know if that worked!

**Comment by javiermartingonzalez** [comment]
What is the key and the value for add it? Before migration, parameters.json was cleared with default values and you add easily. Now I don't have a sample or default values to add new values.

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez So now with overrides.ts file, you can do the same by defining the login in there. I tried doing what you mentioned above and the overrides.ts file in that case would look like this:

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez So now with overrides.ts file, you can do the same by defining the login in there. I tried doing what you mentioned above and the overrides.ts file in that case would look like this:

``` js


import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyS3ResourceTemplate) {

    resources.s3AuthPublicPolicy.policyDocument = Object.assign(
        resources.s3AuthPublicPolicy.policyDocument, 
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
        }
    );
}




```

**Comment by javiermartingonzalez** [comment]
@kaustavghosh06  Thank you for the answer, but with the code provided, I'm getting the following error when pushing:

`UPDATE_FAILED               S3AuthPublicPolicy                                                       AWS::IAM::Policy           Wed Nov 17 2021 01:16:26 GMT+0100 (GMT+01:00) Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: dab73ce4-40bf-46e9-8c5e-0849126255a5; Proxy: null)`

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez Really sorry, missed a key in there. It should be this:

``` js
import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyS3ResourceTemplate) {

    resources.s3AuthPublicPolicy.policyDocument = Object.assign(
        resources.s3AuthPublicPolicy.policyDocument, 
        {
            Statement: {
                Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
            }
        }
    );
}
```

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez Sorry, missed a key in there. The overrides.ts file should look like this
``` js
import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyS3ResourceTemplate) {

    resources.s3AuthPublicPolicy.policyDocument.Statement = Object.assign(
        resources.s3AuthPublicPolicy.policyDocument.Statement, 
        {
            Action: [ "s3:PutObject","s3:PutObjectAcl","s3:GetObject"]
            
        }
    );
}
```

**Comment by javiermartingonzalez** [comment]
@kaustavghosh06 Thank you! I understand now. I think I had to override the whole policyDocument (and I was developing some code before your Object.assign to keep in mind Statement from the top), but being able to only overriding Statement part directly is very easy.

Now solved, your last code is working as expected, thank you for your time!
