### ISSUE TITLE
Running Amplify CLI inside Docker Container - Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId

### ISSUE THREAD

**Issue by ZukkyBaig** [aws-amplify/amplify-cli#8896]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.3.3

### What operating system are you using?

Windows 11, running command in Docker

### Amplify Categories

auth

### Amplify Commands

init

### Describe the bug

I am trying to build my React application that utilises Amplify for auth'ing to AWS Cognito. The app that is being built is inside a docker container, so that I can build and output the "build" directory to promote to different environments in my TeamCity CI/CD.

I am calling a shell script once npm install has ran, that invokes `amplify init`:

```
#!/usr/bin/env bash

# ======== SCRIPT CONFIGURATION ========

set -e

IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"${AWS_ACCESS_KEY_ID}\",\
\"secretAccessKey\":\"${AWS_SECRET_ACCESS_KEY}\",\
\"region\":\"${AWS_DEFAULT_REGION}\"\
}"

AMPLIFY="{\
\"projectName\":\"projectName\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"code\"\
}"

FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

AUTHCONFIG="{\
\"userPoolId\":\"${AMPLIFY_USERPOOL_ID}\",\
\"webClientId\":\"${AMPLIFY_WEBCLIENT_ID}\",\
\"nativeClientId\":\"${AMPLIFY_NATIVECLIENT_ID}\"\
}"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"

amplify init \
--amplify "${AMPLIFY}" \
--frontend "${FRONTEND}" \
--providers "${PROVIDERS}" \
--categories "${CATEGORIES}" \
--yes
```

When this runs inside the Docker container, I receive this error
![amplifyerror](https://user-images.githubusercontent.com/20065329/142031087-8ed9511a-1332-4187-8a6a-01b0a43b3ba8.png)
:

Essentially, the error states:
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId

I have read around, and can't seem to find a solution which works. Maybe I am doing something wrong, but the help would be appreciated.

### Expected behavior

For the `auth` to be successfully imported into the React app, so I can build successfully.

### Reproduction steps

1. Create a React App
2. Utilise Amplify auth inside index.js
2. Create a Dockerfile:

```
FROM node:16.13.0 as build-env
WORKDIR /app

# AWS access keys for Amplify
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ARG AMPLIFY_USERPOOL_ID
ARG AMPLIFY_WEBCLIENT_ID
ARG AMPLIFY_NATIVECLIENT_ID

# Install dependencies
RUN apt-get update \
    && apt-get install -y \
    unzip \
    gettext-base \
    && apt-get clean

# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \ 
    && unzip -qq awscliv2.zip \
    && ./aws/install

# Set execution permissions for aws-cli
RUN chmod +x /usr/local/bin/aws

# Install AWS Amplify CLI
RUN npm install -g @aws-amplify/cli

# Ensure node_modules are inside PATH.
ENV PATH="/app/node_modules/.bin:${PATH}"

# Run React in CI mode to enable stricter standards and test run behaviour.
# ENV CI=true

# Copy dependencies.
COPY package.json ./
COPY package-lock.json ./

# Pull and build dependencies.
RUN npm install

# Copy everything else
COPY . ./

# Run AWS Amplify init script
RUN bash -c "./initAwsAmplify.sh"

# Build app
RUN npm run build-ci

```
4. Run `docker build -t app .`
5. The error that I am facing should be shown.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ZukkyBaig** [comment]
Ok, I had an extra "double quote" here:
```
CATEGORIES="{\
\"auth\":$AUTHCONFIG**\"** \
}"
```
I removed that, and now I am seeing this error:
![amplifyerror2](https://user-images.githubusercontent.com/20065329/142036770-fc2c316a-d862-42df-8598-2d3627960e43.png)

"TypeError: The "path" argument must be of type string. Received undefined"

Thank you

**Comment by kaustavghosh06** [comment]
@ZukkyBaig Could you please provide screenshot for the entire stack trace?

**Comment by ZukkyBaig** [comment]
![stacktrace](https://user-images.githubusercontent.com/20065329/142037380-81796c49-3d17-4a03-be66-043d09d50d47.png)

**Comment by kaustavghosh06** [comment]
@ZukkyBaig Does your project already have an auth resource? Does the script work without the --categories "${CATEGORIES}" \ params?

**Comment by ZukkyBaig** [comment]
It does have an auth resource, but this will be used in our CI/CD, a fresh pull from the repo? Are we meant to store the auth resource in git?

**Comment by ZukkyBaig** [comment]
Update: I have tried without "--categories "${CATEGORIES}" \" parameter, and it fails with:

```
#16 3.648 Note: It is recommended to run this command from the root of your app directory
#16 7.347 - Initializing your environment: dev
#16 9.382 - Building resource auth/newplatformweb0af654ca
#16 9.423 ✔ Initialized provider successfully.
#16 9.432 ✖ There was an error initializing your environment.
#16 9.441 Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
#16 9.441     at ensureHeadlessParameters (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1312:11)
#16 9.441     at Object.headlessImport (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1169:40)
#16 9.441     at importedAuthEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:946:18)
#16 9.441     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#16 9.441     at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/index.js:52:72)
#16 9.441     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:349:22
------
executor failed running [/bin/sh -c bash ./build.sh configureAwsAmplify]: exit code: 1

```

**Comment by ZukkyBaig** [comment]
Ok, I got it to work by setting in `.dockerignore` to ignore the "amplify" folder that is created, so that on the "init" it creates a fresh "amplify" folder in the root directory when it is being built in the Docker Container. Once I did this, it successfully worked. Can you confirm that if this is the right approach?

**Comment by kaustavghosh06** [comment]
Yes, that would pull in all the latest config values from the cloud. @ZukkyBaig please let us know if you're still stuck on this issue.
