### ISSUE TITLE
Unauth and Auth roles are not deleted when deleting the CF template

### ISSUE THREAD

**Issue by adrianhall** [aws-amplify/amplify-cli#89]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

Go to the CloudFormation console and delete the root stack.  The deletion fails because the Unauth Role and Auth role still exist.

**Steps to reproduce the issue:**

1. amplify init
2. amplify analytics add
3. amplify push
4. Go to CloudFormation console
5. select the root CF stack
6. Delete the stack

**What is the expected behavior?**

All resources are deleted, including the IAM roles.

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)** Mac
* **Output of ``amplify --version``**: 0.13.3
* **Did this work in previous versions?**: N

**Comment by attilah** [comment]
Already fixed.
