### ISSUE TITLE
amplify push fail - related to babel and prettier?

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#890]
**Describe the bug**
I change my annotated graphql schema:
```graphql
type Item @model @searchable {
  id: ID!
  subcategory: String!
  // other fields
}
```
to
```graphql
type Item @model @searchable {
  id: ID!
  subcategory: String
  // other fields
}
```
Amplify status:
```sh
Current Environment: NONE

| Category | Resource name      | Operation | Provider plugin   |
| -------- | ------------------ | --------- | ----------------- |
| Api      | inventoryappmobile | Update    | awscloudformation |
| Auth     | cognitoc7f37f50    | No Change | awscloudformation |
| Storage  | s307ab5088         | No Change | awscloudformation |
```
Amplify push fails: see full log at https://gist.github.com/YikSanChan/9b2a508b782e7bbaf19262bb0ceca725. It seems everything looks good other than the last place - How does it relate to prettier???
```
⠹ Updating resources in the cloud. This may take a few minutes...⠋ Generating GraphQL operations2019-02-18T23:36:50.776Z - error: uncaughtException: Couldn't resolve parser "babel" date=Mon Feb 18 2019 15:36:50 GMT-0800 (Pacific Standard Time), pid=75827, uid=501, gid=20, cwd=/Users/evan/source/inventoryapp-mobile, execPath=/usr/local/Cellar/node/11.7.0/bin/node, version=v11.7.0, argv=[/usr/local/Cellar/node/11.7.0/bin/node, /usr/local/bin/amplify, push], rss=97263616, heapTotal=64802816, heapUsed=54493448, external=5491097, loadavg=[3.6259765625, 3.2001953125, 3.15234375], uptime=977210, trace=[column=13, file=/Users/evan/.config/yarn/global/node_modules/prettier/index.js, function=resolveParser$1, line=10572, method=null, native=false, column=19, file=/Users/evan/.config/yarn/global/node_modules/prettier/index.js, function=normalize, line=10664, method=null, native=false, column=12, file=/Users/evan/.config/yarn/global/node_modules/prettier/index.js, function=formatWithCursor, line=13950, method=null, native=false, column=15, file=/Users/evan/.config/yarn/global/node_modules/prettier/index.js, function=null, line=41967, method=null, native=false, column=12, file=/Users/evan/.config/yarn/global/node_modules/prettier/index.js, function=Object.format, line=41986, method=format, native=false, column=19, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=format, line=131, method=null, native=false, column=10, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=render, line=98, method=null, native=false, column=21, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=forEach, line=56, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=47, file=/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts, function=generate, line=53, method=null, native=false], stack=[Error: Couldn't resolve parser "babel",     at resolveParser$1 (/Users/evan/.config/yarn/global/node_modules/prettier/index.js:10572:13),     at normalize (/Users/evan/.config/yarn/global/node_modules/prettier/index.js:10664:19),     at formatWithCursor (/Users/evan/.config/yarn/global/node_modules/prettier/index.js:13950:12),     at /Users/evan/.config/yarn/global/node_modules/prettier/index.js:41967:15,     at Object.format (/Users/evan/.config/yarn/global/node_modules/prettier/index.js:41986:12),     at format (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:131:19),     at render (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:98:10),     at forEach (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:56:21),     at Array.forEach (<anonymous>),     at generate (/home/circleci/repo/packages/amplify-graphql-docs-generator/src/index.ts:53:47)]
```

**To Reproduce**
1. Change amplify/backend/api/<app-name>/schema.graphql, modify a field from required to optional
2. amplify push

**Expected behavior**
Amplify push should succeed

**Desktop (please complete the following information):**
 - Mac OS

**Additional context**
amplify version 1.1.2

**Comment by kaustavghosh06** [comment]
@YikSanChan I wasn't able to reproduce this issue locally with "npm" or "yarn". This issue seems strange. Maybe you would want to install babel globally or locally to your project so that it's available to the CLI (as a wrokaround)?

**Comment by YikSanChan** [comment]
@kaustavghosh06 Hmm, does `amplify push` calls any local libs (like babel and prettier) under the hood? I don't understand the issue at all :(

**Comment by kaustavghosh06** [comment]
Yes, we do that https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-docs-generator/package.json
I think there's an issue with the latest version of prettier. Let me lock down the version in the above package and update this thread after we release the change.

**Comment by YikSanChan** [comment]
@kaustavghosh06 According to https://github.com/jonlabelle/SublimeJsPrettier/issues/157, it seems a prettier version issue. As suggested by most answers there, I upgrade prettier version to 1.16.4 by `yarn global upgrade pretter@1.16.4`. However, the error changes to https://gist.github.com/YikSanChan/b7f0b08ed1b009cbf393af3293eb490b.

The difference: in [this link](https://gist.github.com/YikSanChan/9b2a508b782e7bbaf19262bb0ceca725), it complains about `/Users/evan/.config/yarn/global/node_modules/prettier/index.js`, while in the later one, it complains about `/Users/evan/.config/yarn/global/node_modules/amplify-graphql-docs-generator/node_modules/prettier/index.js`. Unfortunately I don't think I should upgrade prettier in amplify-graphql-docs-generator/node_modules :(

**Comment by kaustavghosh06** [comment]
Try installing prettier version 1.14.2

**Comment by kaustavghosh06** [comment]
@YikSanChan What's your answer ` Choose the code generation language target ?` question as part of the push command for codegen.

**Comment by YikSanChan** [comment]
@kaustavghosh06 No luck with `yarn global upgrade pretter@1.14.2`. I get the same error as https://gist.github.com/YikSanChan/b7f0b08ed1b009cbf393af3293eb490b. Seems the problem being `.config/yarn/global/node_modules/amplify-graphql-docs-generator/node_modules/prettier/index.js` shows it is version 1.15.3, and amplify-graphql-docs-generator is out of my control :(

Hmm when I run `amplify push` I don't get this question. If I was, I choose Javascript.

**Comment by kaustavghosh06** [comment]
@YikSanChan I was able to reproduce the issue. Updating prettier to 1.16.4 in the docs-generator package fixed the issue. Checkout #901

**Comment by YikSanChan** [comment]
@kaustavghosh06 I do think so! When do you expect this get merged and I am able to use it?

**Comment by kaustavghosh06** [comment]
@YikSanChan We published a new version of the CLI. Please install it and let me know if that fixed the issue. I would recommend uninstalling the previous version of the CLI - `npm uninstall -g @aws-amplify/cli' and then installing it again using `npm install -g @aws-amplify/cli`

**Comment by YikSanChan** [comment]
@kaustavghosh06 Thank you! It fixes the problem.
