### ISSUE TITLE
`add custom` does not fail on uninitialized projects

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#8920]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

7.x

### What operating system are you using?

macos

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

In an empty folder `amplify add custom` does not fail early.

![image](https://user-images.githubusercontent.com/230432/142262325-bfb1866a-8dad-46b9-b8a4-590e0025d4e3.png)

### Expected behavior

fail with project the error before asking any prompts.

### Reproduction steps

1. mkdir foo
2. cd foo
3. amplify add custom

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
Yes, it's a requirement to do "amplify init" for adding any Amplify resources. Is the ask here to show the message at the start rather than showing after two questions?

**Comment by SebasRod23** [comment]
May I work on this please? Thanks
