### ISSUE TITLE
Auth Template is incorrectly generated - CICD and Local

### ISSUE THREAD

**Issue by daniellorenzin** [aws-amplify/amplify-cli#8926]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.3.6

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

init, push

### Describe the bug

In the 7.3.6 version the auth template is incorrectly generating the defaults for ```hostedUIProviderCreds``` parameter.

for example:

``` "hostedUIProviderCreds": {
      "Type": "String",
      "Default": []
    }
```

### Expected behavior

Pervious version was deploying correctly with:

```
"hostedUIProviderCreds": {
      "Type": "String"
    },
```

### Reproduction steps

Upgrade to 7.3.6 and push to ci/cd which is setup for a new environment build.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@daniellorenzin What's the error you're getting in build logs and local?

**Comment by kaustavghosh06** [comment]
Also, he stopped storing the "hostedUIProviderCreds" locally in the amplify folder for security reasons only requiring it only during add/update auth operations making it ephemeral.  Getting an idea of the workflow you're executing and the build logs would help us unblock you.

**Comment by daniellorenzin** [comment]
The backend auth folder only has the cli-inputs.json. We are passing in the creds to the pipeline via the ENV AMPLIFY_GOOGLE_CLIENT_ID and AMPLIFY_GOOGLE_CLIENT_SECRET, as per the [documented way. ](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html)

Error in build log is: 
```
CREATE_FAILED               authmovecmdamplify1a858268           AWS::CloudFormation::Stack Wed Nov 17 2021 20:07:07 GMT+0000 (Coordinated Universal Time) Template format error: Every Default member must be a string.
```
