### ISSUE TITLE
Amplify AWS Admin actions amplify update auth error

### ISSUE THREAD

**Issue by frankdevsx** [aws-amplify/amplify-cli#8937]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

Amplify AWS Admin actions amplify update auth

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
6.1.1

**What AWS Services are you utilizing?**

Amplify

**Provide additional details e.g. code snippets**

I want to have access to the (AdminCreateUser) https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html I am following this tuutorial here https://docs.amplify.aws/cli/auth/admin/, The problem with this, is that it generates some default functions, without including the function I want which is AdminCreateUser

module.exports = {
  addUserToGroup,
  removeUserFromGroup,
  confirmUserSignUp,
  disableUser,
  enableUser,
  getUser,
  listUsers,
  listGroups,
  listGroupsForUser,
  listUsersInGroup,
  signUserOut,
};

When I change the CognitoActions.js file to include the AdminCreateUser, then I run

amplify update auth 
What do you want to do? Create or update Admin queries API
Do you want to restrict access to the admin queries API to a specific Group: No

amplify push

I get this error

Following resources failed
× An error occurred when pushing the resources to the cloud
Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdate

**Comment by marcvberg** [comment]
Hi @frankdevsx,

You mentioned you changed `CognitoActions.js` to inclde AdminCreateUser, can you share what changes you made to support that?

**Comment by marcvberg** [comment]
I'll add this: `cognitoActions.js` is not the only file you'll need to edit, there are routing statements in `app.js` that will need to be updated so you can then map the request to the function it sounds like you added to `cognitoActions.js`

Afterward you do not need to `amplify update auth`, you just need to `amplify push` and it will update the lambda function backing the AdminQueries

**Comment by marcvberg** [comment]
Closing, the issue appears to be some misconfiguration. Feel free to reopen issue if necessary
