### ISSUE TITLE
Provided private key cannot be used for Sign in with Apple

### ISSUE THREAD

**Issue by kfernandes29** [aws-amplify/amplify-cli#8939]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

15.3

### Amplify CLI Version

7.4.0

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I have run `amplify update auth` in my PROD environment and enabled Facebook, Google and Apple Sign In. However I get an error stating:

`InvalidParameterException: Provided private key cannot be used for Sign in with Apple.`

This same key worked in my STAGING environment so I am unsure what the issue is. Here is the Sign In With Apple portion of my deployment-secrets.json:

{\"ProviderName\":\"SignInWithApple\",\"client_id\":\"xxxxxxx\",\"team_id\":\"xxxxxx\",\"key_id\":\"xxxxxx\",\"private_key\":\"/Users/kfernandes29/Downloads/AuthKey_XXXXXXX.p8\"}

### Expected behavior

Amplify pushes the updates auth configuration and the auth gets updated.

### Reproduction steps

1. Run `amplify update auth`
2. Update Social Providers
3. Enter details for Sign In With Apple
4. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kfernandes29** [comment]
Looks like I had to copy and paste the text in the .p8 key. Weird how it worked the other way for my Staging environtment.

**Comment by kfernandes29** [comment]
Looks like I had to copy and paste the text in the .p8 key. Weird how it worked the other way for my Staging environtment.

**Comment by karlmarxlopez** [comment]
@kfernandes29 I'm also experiencing this issue #9478. 

I tried the following
1. Using path to p8 file
2. Copying and pasting the p8 contents into the CLI prompt
3. Copy and pasting only the contents between BEGIN and END

None of them works, how did you exactly resolve this?

**Comment by AlvSovereign** [comment]
I had this same issue and got it to work, realising tha the p8 file contents contain line-breaks in them.

Be careful when pasting into the CLI, better to copy out the private key in your IDE and remove the line breaks so you have one long string of characters, then copy that long string and paste into the CLI where needed.

Hope that helps.

**Comment by jedwardblack** [comment]
@AlvSovereign That worked. Thanks!
