### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined

### ISSUE THREAD

**Issue by EduardoTayupanta** [aws-amplify/amplify-cli#8942]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn global add @aws-amplify/cli

### If applicable, what version of Node.js are you using?

17.1.0

### Amplify CLI Version

7.4.0

### What operating system are you using?

Windows 11

### Amplify Categories

Not applicable

### Amplify Commands

configure

### Describe the bug

The 'request' argument must be string. Received type undefined

### Expected behavior

None

### Reproduction steps

no amplify command is executed

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kaustavghosh06** [comment]
@EduardoTayupanta We need more information on this. 
Does this happen during CLI installation? Could you please try using npm - `npm install -g @aws-amplify/cli`

**Comment by EduardoTayupanta** [comment]
There is no error in the installation, it installs normally, but when executing a command referring to amplify the following error occurs:

C:\Users\eduar>amplify configure
The 'request' argument must be string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:224803
    at Object.<anonymous> (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:251922)
    at Object.t (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:279775)
    at n (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:279589)
    at AmplifyToolkit.executeProviderUtils [as _executeProviderUtils] (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\execute-provider-utils.js:7:26)
    at Object.attachUsageData (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\context-manager.js:27:45)
    at Object.run (C:\Users\eduar\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\index.js:147:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kaustavghosh06** [comment]
@EduardoTayupanta Could you please use `npm install -g @aws-amplify/cli` instead of yarn and let us know if you're still seeing this.

**Comment by EduardoTayupanta** [comment]
It was solved when using npm, but what is the drawback of the installation with yarn?

**Comment by kaustavghosh06** [comment]
@EduardoTayupanta Currently we support only npm installations for the global installation of the CLI. We have a few open issues already for investigating yarn installs for the CLI. Closing issue as a dup.

**Comment by EduardoTayupanta** [comment]
thank you very much for your help!
