### ISSUE TITLE
How to restore team-provider-info.json in new machine? 

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#8979]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
amplify cli setup

**Amplify CLI Version** 
7.4.3

**What AWS Services are you utilizing?**
function,api,analytics

**Provide additional details e.g. code snippets**

I cloned my git environment and was setting up my dev environment on a new (cloud9) machine. I imported my amplify backend via ```amplify pull <my_app_id>``` command. I went through the steps and it correctly listed all my backend environments, where it asked me to choose one which I did. 

Everything worked fine and I was able to push and pull to my chosen backend env. When I wanted to switch to another env though via 'amplify env checkout', amplify could not find my other envs, and amplify env list only showed one env. 

It wasn't clear how to pull the other existing envs. 

So what I ended up doing was grab the team-provider-info.json from another machine where I had everything setup, and that fixed things. 

team-provider-info.json is also checked into git, but when I setup the new machine, amplify completely overwrote it with just one env. 

So going forward, what is the proper way to pull the entire team-provider-info.json with all env information?

**Comment by lazpavel** [comment]
Hi @hisham, thank you for your question, I am trying to reproduce the steps you described and will get back to you asap.

**Comment by lazpavel** [comment]
Hi @hisham, when you pull in a fresh dir you pull in one env at a time. 
You can execute the commands as:
- `amplify pull --appId ${appId} --envName ${devEnvName}`
- `amplify pull --appId ${appId} --envName ${prodEnvName}`

after that `amplify env list` should display both env and `amplify env checkout ${envName}` should properly change the env and keep the `team-provider-info.json` in the correct state

[0] - https://docs.amplify.aws/cli/teams/overview/
[1] - https://docs.amplify.aws/cli/usage/headless/#amplify-pull-parameters

**Comment by lazpavel** [comment]
Please reopen if the above solution doesn't work. Thank you
