### ISSUE TITLE
FR: Export existing environment as a config file to be re-imported in new environment

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#898]
**Is your feature request related to a problem? Please describe.**
Pretty much all my Amplify applications involve the hosting and auth categories, and a good subset of those also use API, and most of them share configuration (e.g. disable user-signup, use optional TOTP email, require email, production hosting environment).

**Describe the solution you'd like**
I would like to be able to export the configuration for an existing environment's categories, and then re-import these templates in new environments with a prompt for changes where necessary (e.g. resource name changes). This would enable a workflow where a developer creates a template React-based Amplify app in a repository, and other developers can clone this repo, import the necessary backend configuration to setup identical resources with minimal name changes, and push. 

The specific use case for us is that we want to have the ability to host public Sumerian scenes **privately** on Amplify "mini-container" SPAs sitting in an Amplify app. (No Authenticator necessary; this is for the benefit of prettifying our application domains.) 

This is a one-category application -- hosting. Since the only config change that needs to be made between these mini-SPAs is swapping out the Sumerian private scene config export, I'd like to setup a workflow where someone could clone my repo, run `amplify init --import` or something to that effect, swap the config file, and run `amplify publish` in ~5 minutes. 

This would also give us the flexibility of hosting all of our Sumerian scenes in Amplify container sites with the minimal change of removing `withAuthenticator` from those which need to be public.

**Describe alternatives you've considered**
`amplify init` for every project.

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 I think what I'm really asking for is a bifurcation between the concept of "template/concept environments" (what currently does not exist) and "concrete environments" (what currently exists). 

Concrete environments would be the only environments that can actually contain (AWS) resources, while the template environments would be defined environments that can be implemented with concrete instantations. This workflow would make Amplify multienvs a natural corrollary of traditional OOP inheritance and speed adoption.

Let me define template environments for my coworkers to instantiate (with their own, **actual** environment names, or perhaps appended to the template name, like `appresource-conceptName-devName`) and provision real resources against a template.

Such a scheme would also make it simple to backup template environments (which don't contain references to actual resources) to the account, while leaving concrete instantiation references on developer instances/machines. That would solve my original FR by giving fellow developers the option of checking out a hypothetical template environment, instantiating it into a concrete environment with all related resources, and go with miniminal configuration.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu That's a great feature request. Let's track this and see if there are others in the community who would like a similar feature-set.

**Comment by jkeys-ecg-nmsu** [comment]
Thank you!

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 can you modify the title to something more descriptive of what my follow-up comment describes rather than the OP? Might receive a bit more attention that way.

**Comment by ykethan** [comment]
This is currently supported by pulling your existing application from your git repository and run an `amplify init` without the `aws-exports` and `teams-provider-info` file. Please refer to https://docs.amplify.aws/cli/start/workflows/#clone-sample-amplify-project for additional information.
