### ISSUE TITLE
SearchableStringFilterInput regexp returns bad request

### ISSUE THREAD

**Issue by alexlhanson** [aws-amplify/amplify-cli#899]
# SearchableStringFilterInput regexp returns bad request
## Categories
graphQL/ AppSync, elasticsearch
## Services
DynamoDB, Elasticsearch, Amplify, AppSync
## Summary
When attempting to query the db in the AWS console using the filter by regexp, I get this response message: 
```"message": "Elasticsearch responded with an error: Bad Request"```
I am trying to query by date so that I can enter a regexp for certain dates to get returned.  My query in the console has been something like the following:
```
query SearchEvents {
  searchEvents(
    filter: { date: { regexp: "2019" } }
    sort: {
	field: date
	direction: asc
    }
  ) {
    items {
      id
      date
    }
    nextToken
  }
}
```
I think based on the schema that it is supposed to accept a string.  I have also tried: 
``` regexp: "/2019/g"```
``` regexp: "/2019/"```
``` regexp: "2019.*"```
``` regexp: "2019.+"```
...probably some others as well.  The documentation doesn't show this particular one, and for most of the options it takes you to www.elastic.co documentation, which appears to have a different input pattern in general.  The only options that do work for that filter as far as I can tell are eq, nq, and match.  

this is the model in the schema:
``` 
type Event
	@model
	@searchable
	{
	id: ID!
	presentation: Presentation @connection
	orders: [Order] @connection(name:"EventOrders")
	date: AWSDate!
	restaurant: Restaurant @connection(name:"EventRestaurant")
}
 ```

this is the search query provided:
```
export const searchEvents = `query SearchEvents(
  $filter: SearchableEventFilterInput
  $sort: SearchableEventSortInput
  $limit: Int
  $nextToken: Int
) {
  searchEvents(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      presentation {
        id
        topic
        name
      }
      orders {
        nextToken
      }
      date
      restaurant {
        id
        name
        website
        currentRestaurant
      }
    }
    nextToken
  }
}
`;
```
this is the searchableEventFilterInput:
```
input SearchableEventFilterInput {
  id: SearchableIDFilterInput
  date: SearchableStringFilterInput
  and: [SearchableEventFilterInput]
  or: [SearchableEventFilterInput]
  not: SearchableEventFilterInput
}
```

this is the SearchableStringFilterInput:
```
input SearchableStringFilterInput {
  ne: String
  eq: String
  match: String
  matchPhrase: String
  matchPhrasePrefix: String
  multiMatch: String
  exists: Boolean
  wildcard: String
  regexp: String
}
```

Thanks ahead for any help!

**Comment by hakimio** [comment]
I can confirm that wildcard and regexp filtering doesn't work.
@mikeparisstuff

**Comment by hakimio** [comment]
Update: the query string has to be lowercase to be able to use wildcard query. Let's say there is a field "FirstName" with value "Emma". Searching for "Emm*" gives no results, but "emm*" finds the correct record. Any way to make "Emm*" work as well? Something with [lowercase_expanded_terms](https://github.com/elastic/elasticsearch/issues/9973)?

**Comment by AaronHarris** [comment]
By default the tokenizer in Elasticsearch lowercases all strings when building the reverse index. The straigforward approach here looks to be to lowercase all query_strings that get sent to Elastic search in the resolver, or else modify your ES cluster to use a different (ie. case sensitive) tokenizer if letter case matters.

**Comment by arhoy** [comment]
This library has the worst documentation I ever seen
