### ISSUE TITLE
Struggling with @auth directive

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#8993]
Hi. I struggle with setting up model authorization for anything other than trivial examples. Please help, struggling with this for a long time.

I want a model with the following properties:
- IAM lambda has full access
- userPool owner has **update & read** access to nickname field
- userPool owner has **read** access to birthday fields
- userPool owner has no access to spamRating field

### Approach 1 - using @auth directive on fields:

```
type User
    @model
    @auth(rules: [
                    { provider: iam, allow: private }
     ])
{
    id: ID!
                        @auth(rules: [{ provider: userPools, allow: owner, operations: [read] }])
    owner: String!
                        @auth(rules: [{ provider: userPools, allow: owner, operations: [read] }])
    nickname: String!
                        @auth(rules: [{ provider: userPools, allow: owner, operations: [read, update] }])
    birthday: AWSDate!
                        @auth(rules: [{ provider: userPools, allow: owner, operations: [read] }])
    spamRating: String!
}

```

This doesn't work. Gives the following error:

> InvalidDirectiveError: 
> Per-field auth on the required field id is not supported with subscriptions.
> Either make the field optional, set auth on the object and not the field, or disable subscriptions for the object (setting level to off or public)
> 

I don't want to disable subscriptions. And I cannot make "id" field optional.

So stuck here.

### Approach 2 - using multiple models:

Create multiple models, each a different view onto the data.

```
type UserPrivate
    @model
    @auth(rules: [
                    { provider: iam, allow: private }
     ])
{
    id: ID!
    owner: String!
    nickname: String!
    birthday: AWSDate!
    spamRating: String!
}


type UserReadUpdate
    @model
    @auth(rules: [
                    { provider: userPools, allow: owner, operations: [read, update] }
     ])
{
    id: ID!
    owner: String!
    nickname: String!
}


type UserRead
    @model
    @auth(rules: [
                    { provider: userPools, allow: owner, operations: [read] }
     ])
{
    id: ID!
    owner: String!
    nickname: String!
    birthday: AWSDate!
}
```

This doesn't work. It creates 3 tables. I want 1 table with different models pulling data from it. There is no option to specify table name in @model directive.

### Conclusion

How do I do this? Is there another option I am missing here? Please help.

**Comment by lazpavel** [comment]
Hi @skryshi, I am looking into it, just to make sure I properly understood your request. Is this what you're trying to achieve?

IAM lambda has full access
userPool owner **only** has **update & read** access to nickname field
userPool owner **only** has **read** access to birthday fields
userPool owner has **no** access to spamRating field

**Comment by lazpavel** [comment]
Let me know if the below configuration works for you:

```
type User
  @model
  @auth(
    rules: [
      { allow: private, provider: iam }
      { allow: owner, provider: userPools, operations: [read] }
    ]
  ) {
  id: ID!
  owner: String!
  nickname: String
    @auth(
      rules: [
        { allow: private, provider: iam }
        { allow: owner, provider: userPools, operations: [read, update] }
      ]
    )
  birthday: AWSDate!
  spamRating: String @auth(rules: [{ allow: private, provider: iam }])
}
```

**Comment by lazpavel** [comment]
Please reopen if the above solution doesn't work. Thank you

**Comment by skryshi** [comment]
@lazpavel This looks like it should work, but it doesn't in several ways:

1. userPool owner can update (but not read) spamRating.
2. nickname is always returned as null on Mutations.

For example, here is the resolver generated for `User.nickname.res.vtl`:

```
## [Start] Checking for allowed operations which can return this field **
#set( $operation = $util.defaultIfNull($context.source.operation, "null") )
#if( $operation == "Mutation" )
$util.toJson(null)
#else
  $util.toJson($context.source.nickname)
#end
## [End] Checking for allowed operations which can return this field **
```

It for some reason sets the output of nickname to null on Mutations. Why? This isn't what User type definition says.

**Comment by skryshi** [comment]
@lazpavel I don't have the permissions to re-open this issue.

**Comment by lazpavel** [comment]
Hi @skryshi can you confirm for me the transformerVersion? please paste the content from `amplify/cli.json`
