### ISSUE TITLE
@auth without 'read' permission still allows reads

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#8995]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.6.1

### Amplify CLI Version

7.4.4

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

**After removing read permission from @auth users can still read the model data.**

More specifically, changing from this:

```
type Test
  @model
  @auth(rules: [
    { provider: userPools, allow: private, operations: [read, create, update, delete] }
  ])
{
  id: ID!
  writeable: String
  readOnly: String
}
```

to this:

```
type Test
  @model
  @auth(rules: [
    { provider: userPools, allow: private, operations: [create, update, delete] }
  ])
{
  id: ID!
  writeable: String
  readOnly: String
}
```

still allows users to read the model data.

### Expected behavior

After removing read permission from @auth, users will not be able to read model data.

### Reproduction steps

I have created a bare bones Amplify project where I can reproduce this bug:

1. `amplify init`
2. `amplify add auth` 
3. `amplify add api`
    (select User Pool as primary, and IAM as secondary auth)
4. use the graphQL schema for Test model from above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

From what I can tell, changing @auth does not change generated Query, it stays the same:

```
type Query {
  syncTests(filter: ModelTestFilterInput, limit: Int, nextToken: String, lastSync: AWSTimestamp): ModelTestConnection
  getTest(id: ID!): Test
  listTests(filter: ModelTestFilterInput, limit: Int, nextToken: String): ModelTestConnection
}

```

**Comment by sachscode** [comment]
@skryshi 
1. Could you please confirm the options selected when you configured "Auth" . It would be great if you could share 
   amplify/backend/auth/<resourceName>/cli-inputs.json and amplify/backend/auth/
2. Did "amplify push" complete successfully

**Comment by sachscode** [comment]
Hi @skryshi 
The current GraphQL implementation , the operations which are are in the operations array are protected . since Read has been removed , this is not protected. You would need to create a rule which denies private from read. Similar to how we document denying access on a field.
https://docs.amplify.aws/cli/graphql-transformer/auth/#field-level-authorization
Please let use know if you have any other queries.

**Comment by sachscode** [comment]
We are in the process of updating this behavior to "default protected" , per  RFC https://github.com/aws-amplify/amplify-cli/issues/6217

**Comment by skryshi** [comment]
@sachscode I looked up the links you gave, but I still don't understand how to deny read permission to the whole model. Like this?

```
type Test
  @model
  @auth(rules: [
    { provider: userPools, allow: private, operations: [] },
    { provider: userPools, allow: private, operations: [create, update, delete] }
  ])
{
  id: ID!
  writeable: String
  readOnly: String
}
```

If this is not correct, could you give an example please?

**Comment by SwaySway** [comment]
@skryshi To deny read access you'd need a forbidden group which has access to read similar to the field example @sachscode referenced above.

```graphql
type Test
  @model
  @auth(rules: [
    { provider: userPools, allow: groups, groups: ["ForbiddenGroup"], operations: [read] },
    { provider: userPools, allow: private, operations: [create, update, delete] }
  ])
{
  id: ID!
  writeable: String
  readOnly: String
}
```

**Comment by lazpavel** [comment]
Closing per above comment

**Comment by skryshi** [comment]
@SwaySway Thank you!
