### ISSUE TITLE
Lambda Triggers auto detached after updates to Cognito

### ISSUE THREAD

**Issue by gorbinphilip1** [aws-amplify/amplify-cli#8997]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.4

### Amplify CLI Version

7.4.4

### What operating system are you using?

MacOS 10

### Amplify Categories

auth

### Amplify Commands

push, update

### Describe the bug

Cognito lambda triggers getting automatically detached while pushing any updates to Cognito configuration. 
Note: Not regarding updates to lambda function itself but to Cognito configurations like change of password policy etc.

It's clear that the approach for attaching triggers to Cognito is through an authTriggerFn function. From logs I cannot see an invocation after update here in this new version but old version used to get a delete which was causing similar trouble. But in all cases triggers gets detached automatically after any updates to Cognito cloudformation.

This is consistent across amplify versions 5, 6 & 7 at least.

I have reproduced this in a minimal code base here: https://github.com/gorbinphilip1/amplify-cognito-trigger-sample

### Expected behavior

After update  Cognito should retain previously attached lambda triggers.

### Reproduction steps

Simply put steps to reproduce is to
1. Deploy an amplify app with auth category (Cognito) that has lambda trigger setup
2. Deploy an update to the same stack with `amplify push` after altering auth category using `amplify auth update`

Please find the steps below that I used to reproduce this myself in a minimal code base
```
# install amplify, current latest is 7.4.4
npm install -g @aws-amplify/cli
# init project with default setting
amplify init
# configure auth with cognito at least one trigger
amplify add auth
# deploy -- equivalent to commit a3ed91fb86479f3e26871ba95af05e0372fe9dab
amplify push

# all good at this point, triggers are attached.

# update cognito password policy
amplify auth update
# deploy -- equivalent to commit 12bcb24389ac4cb5f36854e61fa0338163c6c0e8
amplify push

# password policy gets updated and existing triggers are now detached from cognito :(
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by marcvberg** [comment]
I was able to reproduce this bug following the steps provided above

**Comment by sarahsga** [comment]
Prior to v7.x.x, when I ran amplify push, the auth triggers were successfully attached to the userpool. But when I updated the amplify-cli to the latest v7.4.5, the auth triggers are no longer attached.

**Amplify push using v7.4.5**
<img width="1082" alt="Screenshot 2021-11-19 at 12 38 14 PM" src="https://user-images.githubusercontent.com/10798986/143059593-b7621e2c-c51e-4172-8f5d-4acaaeb689a9.png">

**Amplify push using v6.4.0**
<img width="1095" alt="Screenshot 2021-11-19 at 12 53 14 PM" src="https://user-images.githubusercontent.com/10798986/143059489-bcc40b18-8a2b-4303-8fe1-bd67cbc1e043.png">

**Comment by wbroek** [comment]
Got the same thing after upgrade to CLI. 7.5.x (updated to latest 7.5.4 for latest test) when pushing the latest changes all triggers where wiped out.
When we ran `amplify update auth` we get the comment we need to migrate: `A migration is needed to support latest updates on auth resources`
After we said yes to the migration and confirmed all the current settings (we did not add or remove settings) and pushed again all triggers where back.
Question is if this migration is mandatory?? (got more Amplify projects so would be nice if we know)

**Comment by attilah** [comment]
@wbroek yes the migration is mandatory because the underlying implementation changed to use the CDK from the previous static EJS templates and also some state files in certain categories are refactored to use the new `cli-inputs.json` as a singular parameter source.

**Comment by cespin** [comment]
@akshbhu , I just build with v7.6.5 and the Cognito triggers are still being removed. In order to fix it I had to add this code in the _override.ts_:

```javascript
    // START - Lambda Triggers
    // This is being done because the generated stack is missing Cognito triggers - Don't know why
    const newLambdaConfig = {
        ...resources.userPool.lambdaConfig,
    };

    if (!newLambdaConfig["preSignUp"]) {
        newLambdaConfig["preSignUp"] = {
            "Ref": "functionmyprojectauthPreSignupArn"
        };
    }

    resources.userPool.lambdaConfig = newLambdaConfig
    // END - Lambda Triggers
```

What I find strange is that the CloudFormation parameter _functionmyprojectauthPreSignupArn_ is available but not set.

I also have a post confirmation trigger and that one is being correctly set. No need to do anything in the _override.ts_ for that one.

**Comment by paulnolan7** [comment]
I think there is an issue with the case difference between SignUp and signup. See this issue #9351
