### ISSUE TITLE
Running api function locally

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#9]
Hi,

Good day.

Do you want to request a feature or report a bug?
feature

What is the current behavior?
You have to push push api changes to test them.

What is the expected behavior?
Would be cool if you could generate the required SAM template files to run an api function locally.

Regards.
JJ

**Comment by kaustavghosh06** [comment]
@jarrettj. We already have the feature to test your function backing your API gateway prox(similar to SAM). Checkout ‘amplify function help’ and look for ‘amplify function invoke <resourcename>’. You can get the resourcename of your function by looking it up in the table after running the ‘amplify status’ command. You can also pass custom events to test out your Lambda functions. The event.json is present in the same directory as the source code of the lambda function -> amplify/backend/function/<resourcename>/src/

**Comment by jarrettj** [comment]
Hi,

Good day.

I found that, and logged another bug #10. Can't get it to invoke.

Regards

**Comment by kaustavghosh06** [comment]
Okay,  I’ll close this issue and track bug #10.
