### ISSUE TITLE
Unauth login lost after adding storage feature for auth users

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-cli#90]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**

i enable auth with unauth login. then enable storage with Auth user access only. => unauth logins no longer work

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**

1. amplify add auth

> ? Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes

2. amplify add storage

> ? Who should have access: Auth users only

At this point, unauth access is no longer available.

**What is the expected behavior?**

shouldnt lose unauth login just because i add stoge feature for auth users

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)** mac
* **Output of ``amplify --version``**: 0.1.15

* **Did this work in previous versions?**: Y/N dunno

**Comment by kaustavghosh06** [comment]
This issue is fixed in the latest version of the CLI. Please feel free to comment on this thread if you're still facing this issue.
