### ISSUE TITLE
Amplify Export - CDK fails to find CloudFormation templates

### ISSUE THREAD

**Issue by daniellorenzin** [aws-amplify/amplify-cli#9009]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.4.5

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

`amplify export` fails to find function cloudformation templates. On mac its concatenating the path twice to the generated CF.

 ```No CloudFormation template found at /Users/daniel/Developer/Project/amplify/backend/function/projectamplify1a858268PostConfirmation/Users/daniel/Developer/Project/amplify/backend/function/amplify/backend/function/projectamplify1a858268PostConfirmation/projectamplify1a858268PostConfirmation-cloudformation-template.json```

### Expected behavior

Should be finding the template at: `Users/daniel/Developer/Project/amplify/backend/function/amplify/backend/function/projectamplify1a858268PostConfirmation/projectamplify1a858268PostConfirmation-cloudformation-template.json`

### Reproduction steps

`amplify export --cdk --out ./infra/cdk-amplify/lib`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@daniellorenzin what's your `path` in the exported backend construct?

**Comment by daniellorenzin** [comment]
I never get an export, this occurs when running it as above.

`amplify export --cdk --out ./infra/cdk-amplify/lib`

**Comment by daniellorenzin** [comment]
In the terminal it displays this:
```
$ amplify export --cdk --out ./infra/cdk-amplify/lib

    Current Environment: test
    
┌─────────────┬────────────────────────────────────────┬───────────┬───────────────────┐
│ Category    │ Resource name                          │ Operation │ Provider plugin   │
├─────────────┼────────────────────────────────────────┼───────────┼───────────────────┤
TABLE OF RESOURCES
└─────────────┴────────────────────────────────────────┴───────────┴───────────────────┘
✔ Existing files at /Users/daniellorenzin/Developer/project/infra/cdk-amplify/lib/amplify-export-projectamplify will be deleted and new files will be generated, continue? (Y/n) · yes
✖ Writing Cloudformation
No CloudFormation template found at /Users/daniellorenzin/Developer/project/amplify/backend/function/projectamplify1a858268PostConfirmation/Users/daniellorenzin/Developer/project/amplify/backend/function/projectamplify1a858268PostConfirmation/projectamplify1a858268PostConfirmation-cloudformation-template.json
Error: No CloudFormation template found at /Users/daniellorenzin/Developer/project/amplify/backend/function/projectamplify1a858268PostConfirmation/Users/daniellorenzin/Developer/project/amplify/backend/function/projectamplify1a858268PostConfirmation/projectamplify1a858268PostConfirmation-cloudformation-template.json
    at Object.readCFNTemplate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/cfnUtilities.ts:22:11)
    at Object.writeCustomPoliciesToCFNTemplate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/pre-push-cfn-processor/cfn-pre-processor.ts:35:43)
    at ResourceExport.postGenerateCategoryCloudFormation (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts:310:15)
    at ResourceExport.generateAndTransformCfnResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/resource-package/resource-export.ts:81:37)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/export-resources.ts:46:55)
    at exportBackend (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/export.ts:74:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/export.ts:62:5)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)```

**Comment by ammarkarachi** [comment]
@daniellorenzin can you send me your amplify backend to amplify-cli@amazon.com?

**Comment by daniellorenzin** [comment]
> @daniellorenzin can you send me your amplify backend to [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)?

Did you want the whole backend folder, or just the backend-config.json file?

**Comment by ammarkarachi** [comment]
@daniellorenzin The whole backend folder would be good so I can run export myself if you are not comfortable sharing that, you can let me know what categories you have provider and any steps to reproduce this.

**Comment by ammarkarachi** [comment]
@daniellorenzin thanks for the folder I could reproduce it and have a fix out for the next release

**Comment by daniellorenzin** [comment]
@ammarkarachi  Thanks, this exports now but the cloudformation template for the api for appsync is blank, compared to the build folder where a complete template is.

It then fails to run cause the stacks seem to be missing a parameter.

**Comment by ammarkarachi** [comment]
@daniellorenzin Sorry didn't get back to you earlier, can you try it with the latest release?
