### ISSUE TITLE
amplify update Auth amplify push throws error UPDATE_ROLLBACK_FAILED state and can not be updated

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-cli#9018]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, api

### Amplify Commands

push

### Describe the bug

This project I'm working on already has Facebook sign in added , I wanted to add Google Sign in so I did Amplify update Auth' and tried to push the modifications, however I didn't have permissions to do that. After I got the permissions, I tried to amplify push but I get this error:

 Stack:arn:aws:cloudformation:us-east-1:432853258441:stack/amplify-huruproject-local-190356/117b7360-c94d-11eb-a4cc-0e8a861a6983 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
An error occurred during the push operation: Stack:arn:aws:cloudformation:us-east-1:432853258441:stack/amplify-huruproject-local-190356/117b7360-c94d-11eb-a4cc-0e8a861a6983 is in UPDATE_ROLLBACK_FAILED state and can not be updated 

Thing is I can't find this specific stack in my stacks console. I searched in the Failed, Active and In Progress categories, I am in the right region. 

### Expected behavior

amplify update auth 
add google signin
amplify push
new social signin added and successfully deployed

### Reproduction steps

amplify update auth
Update OAuth social providers
 Select the identity providers you want to configure for your user pool: Google
enter web client ID and secret 
amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
Stack:arn:aws:cloudformation:us-east-1:432853258441:stack/amplify-huruproject-local-190356/117b7360-c94d-11eb-a4cc-0e8a861a6983 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
An error occurred during the push operation: Stack:arn:aws:cloudformation:us-east-1:432853258441:stack/amplify-huruproject-local-190356/117b7360-c94d-11eb-a4cc-0e8a861a6983 is in UPDATE_ROLLBACK_FAILED state and can not be updated.



```

</details>

**Comment by lazpavel** [comment]
Hi @taouichaimaa,

Thank you for raising this issue. Are you able to update to the latest [CLI](https://www.npmjs.com/package/@aws-amplify/cli) and check if the issue still happens? If you still encounter the issue please send us the console logs at amplify-cli@amazon.com

**Comment by lazpavel** [comment]
Closing. Please don't hesitate to reopen if you still need help.
