### ISSUE TITLE
"socket hang up" or "write EPIPE" during amplify push

### ISSUE THREAD

**Issue by rollcabbage** [aws-amplify/amplify-cli#9019]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

node/17.1.0

### Amplify CLI Version

7.4.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I have an Amplify project with a dev environment which has been created in an AWS account, and now I am planning to add staging environment but deploy to another AWS account. The file size of this Amplify project was almost 102M.

After `amplify init` to add staging environment, when I run `amplify push` to deploy the project, errors below occurred.

>? Are you sure you want to continue? Yes 
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: socket hang up

>? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: write EPIPE

I run the same command in two different location, so two type of errors was shown.
My co-worker can successfully `amplify push` the same project to AWS.

The same error also occurred when I run `cdk deploy` in a project build by aws cdk (which size was about 14M). Maybe network condition would be considered as a reason for failing to run the command, but a network speed test shows, my download and upload speed was always between 80Mbps and 95 Mbps.

And I have changed  `net.inet.tcp.always_keepalive` to 1.

### Expected behavior

Successfully to run `amplify push` command.

### Reproduction steps

1. Create a Amplify project that have a file size above 100M.
2. Run `amplify init` command to add a new enviroment.
3. Run `amplify push` to deploy the project. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@rollcabbage Can you try pushing with node 14?

**Comment by rollcabbage** [comment]
Thank you for reply. The same error displayed with node 14. @ammarkarachi 
I add more logs and hidden the sensitive information.

```
$ node -v
v14.18.1
```

```
$ amplify push

Some Lambda function environment variables are defined but missing values.

? Enter the missing environment variable value of ADMIN_EMAIL in sendmail: xxxxxxxx.com
✔ Successfully pulled backend environment stg from the cloud.

    Current Environment: stg

┌──────────┬────────────────────┬───────────┬───────────────────┐
│ Category │ Resource name      │ Operation │ Provider plugin   │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ dynamoxxxxxxxxx    │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Storage  │ xxxxxxxxxx         │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ xxxxxxxxxxxxxxxxxx │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ xxxxxxxxxx         │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Function │ xxxxxxxxxxxx       │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Api      │ xxxxxxxxxxxxx      │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Api      │ xxxxxxxx           │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Api      │ xxxxxxxxxxxx       │ Create    │ awscloudformation │
├──────────┼────────────────────┼───────────┼───────────────────┤
│ Auth     │ xxxxxxxxxxxxxxxxxx │ Import    │ awscloudformation │
└──────────┴────────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: write EPIPE
```

**Comment by mozadeh** [comment]
I have the same problem 
`✖ There was an error pulling the backend environment prod.
🛑 An error occurred during the push operation: socket hang up`

**Comment by ammarkarachi** [comment]
@rollcabbage What are dependencies of your lambda? I have been trying to reproduce it but was unable to do so.

**Comment by rollcabbage** [comment]
Paste as below. @ammarkarachi 

```
{
  "name": "xxxxxxxxxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "aws-sdk": "^2.845.0",
    "aws-serverless-express": "^3.3.5",
    "body-parser": "^1.17.1",
    "express": "^4.15.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by danshev** [comment]
Seeing the same.

- _An error occurred during the push operation: write EPIPE_ error -or-  
- _An error occurred during the push operation: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed._

I don't have the greatest uplink connection, but I hope AWS's philosophy isn't, "Well, too bad"...

**Comment by rollcabbage** [comment]
I solved this issue after uninstall antivirus software in my PC...
