### ISSUE TITLE
amplifyPush not working in 7.4.5 in Amplify Console CI/CD

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#9025]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.16.1

### Amplify CLI Version

7.4.5

### What operating system are you using?

Linux2

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

Deployment in our app has stop working, last week everything was fine. I have updated the auth and storage service,  new files where generated, and locally push operations works fine.

the amplifyPush --simple script throws is failing

### Expected behavior

To continue to work as it did before version update.

### Reproduction steps

1. update cli
2. update storage and auth 
3. commit changes
4. new deployment failed!

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
                                 # Starting phase: build
2021-11-22T18:40:57.894Z [INFO]: [0mAmplify AppID found: dcb45hbpdk6m3. Amplify App name is: trialpal2web[0m
2021-11-22T18:40:58.021Z [INFO]: [0mBackend environment desarrollo found in Amplify Console app: trialpal2web[0m
2021-11-22T18:41:00.510Z [INFO]: [31mFailed to pull the backend.[39m
2021-11-22T18:41:00.512Z [INFO]: [31mCannot read property 'serviceType' of undefined[39m
2021-11-22T18:41:00.556Z [INFO]: [0mTypeError: Cannot read property 'serviceType' of undefined[0m
                                 [0m    at getResourcesToBeCreated (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)[0m
                                 [0m    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)[0m
                                 [0m    at generateModels (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:58:49)[0m
                                 [0m    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/invoke-plugin-method.ts:29:10)[0m
                                 [0m    at Object.postPullCodegen (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/amplify-service-helper.ts:38:5)[0m
                                 [0m    at onSuccess (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:59:3)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:31:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)[0m
                                 [0m    at Object.executeAmplifyCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)[0m
                                 [0m    at executePluginModuleCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)[0m
                                 [0m    at Object.executeCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)[0m
2021-11-22T18:41:00.580Z [ERROR]: !!! Build failed
2021-11-22T18:41:00.580Z [ERROR]: !!! Non-Zero Exit Code detected
2021-11-22T18:41:00.580Z [INFO]: # Starting environment caching...
2021-11-22T18:41:00.581Z [INFO]: # Uploading environment cache artifact...
2021-11-22T18:41:00.698Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

### Additional information

Please help!!!

**Comment by kaustavghosh06** [comment]
@sergiorodriguez82 Have you pinned your Amplify CLI version in the build settings to latest in Amplify Console? What is it set to?

Also, could you please share contents of your `amplify/backend/backend-config.json`? This would help us investigate further.

**Comment by sergiorodriguez82** [comment]
Thanks @kaustavghosh06 !

Hello
here my config
`{
  "api": {
    "tp2Api": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authtp2Auth"
            }
          },
          "additionalAuthenticationProviders": []
        }
      }
    },
    "tp2IntegrationAPI": {
      "service": "API Gateway",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "tp2UserDisabled",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserEnabled",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserDelete",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserEdit",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2SubjectCompleteVisit",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2SubjectEnroll",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2CreateEDiaryCardPDF",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2AlertTrigger",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2SubjectChangeState",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2SubjectChangeGroup",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2CreateReportCardPDF",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2Ping",
          "attributes": [
            "Name",
            "Arn"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserCreate",
          "attributes": [
            "Name",
            "Arn"
          ]
        }
      ]
    }
  },
  "function": {
    "tp2UserCreate": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2UserDisabled": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    },
    "tp2UserEnabled": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        }
      ]
    },
    "tp2UserDelete": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2UserEdit": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2SubjectCompleteVisit": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2ReportInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2EDiaryInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2SubjectEnroll": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2ReportInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2EDiaryInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2CreateEDiaryCardPDF": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "storage",
          "resourceName": "tp2Storage",
          "attributes": [
            "BucketName"
          ]
        }
      ]
    },
    "tp2SendNotification": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2ForceChangePassword": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2ReportInstancesTrigger": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2EDiaryInstancesTrigger": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2SubjectChangeState": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserDisabled",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2UserEnabled",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2ReportInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2EDiaryInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2SubjectChangeGroup": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2ReportInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "function",
          "resourceName": "tp2EDiaryInstancesTrigger",
          "attributes": [
            "Name"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2CreateReportCardPDF": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "storage",
          "resourceName": "tp2Storage",
          "attributes": [
            "BucketName"
          ]
        }
      ]
    },
    "tp2SubjectDelete": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        }
      ]
    },
    "tp2AuditTrace": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "api",
          "resourceName": "tp2Api",
          "attributes": [
            "GraphQLAPIIdOutput"
          ]
        }
      ]
    },
    "tp2Ping": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda"
    }
  },
  "auth": {
    "userPoolGroups": {
      "service": "Cognito-UserPool-Groups",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId",
            "AppClientIDWeb",
            "AppClientID",
            "IdentityPoolId"
          ]
        }
      ]
    },
    "tp2Auth": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [],
      "customAuth": false
    }
  },
  "storage": {
    "tp2Storage": {
      "service": "S3",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "auth",
          "resourceName": "tp2Auth",
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": [
            "AdminGroupRole"
          ]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": [
            "CoordinatorGroupRole"
          ]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": [
            "InvestigatorGroupRole"
          ]
        },
        {
          "category": "auth",
          "resourceName": "userPoolGroups",
          "attributes": [
            "SubjectGroupRole"
          ]
        }
      ]
    }
  }
}`
I'm using the lastest version, I also try with 7.4.2 with no luck.

![image](https://user-images.githubusercontent.com/38695777/142931779-93c6b0fa-483b-4ad5-89cb-9c6223ed0436.png)

I do not have imported resources. all my auth actions are in cognito, no 3erd parties involved.
BR
Sergio

**Comment by kaustavghosh06** [comment]
@sergiorodriguez82 Got a chance to review the `backend-config.json`. Looks like the following resource is missing from your project but your API is still depending on this resource, causing the issue:

``` json
        {
          "category": "function",
          "resourceName": "tp2AlertTrigger",
          "attributes": [
            "Name",
            "Arn"
          ]
        }
```

**Comment by sergiorodriguez82** [comment]
I have also replicate the problem when I add a new environment.
Getting the same error
![image](https://user-images.githubusercontent.com/38695777/142939841-7da01f06-c46e-4117-ba83-e0499acd6fbd.png)

**Comment by kaustavghosh06** [comment]
Yes, it’s exactly because of the reason I’ve mentioned above.
