### ISSUE TITLE
What are the known issues with installing amplify-cli using yarn

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#903]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
None

** What AWS Services are you utilizing? **
None

** Provide additional details e.g. code snippets **
From https://github.com/aws-amplify/amplify-cli/blob/69cfb43a71404129f3de1cc627c7d36021f11af3/Readme.md#install-the-cli:
> Warning: Please don't use yarn for installing the CLI. It has known issues. Use npm instead as advised above.

What are the known issues?

**Comment by kaustavghosh06** [comment]
@YikSanChan We previousl had issues with yarn wrt plugins but we fixed those issues and users should be able to install the CLI using yarn. We'll update our documentation.

**Comment by YikSanChan** [comment]
@kaustavghosh06 Submitted a PR to update in https://github.com/aws-amplify/amplify-cli/pull/907
