### ISSUE TITLE
Storage outputs from cfn not getting generated 

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#9037]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

7.4.5

### What operating system are you using?

Mac

### Amplify Categories

auth, storage

### Amplify Commands

push

### Describe the bug

Entire environment is broken after trying to upgrade to amplify v7.4.5.

Issue started with our cypress tests failing with our front-end getting an error on Storage.put indicating that the region is missing. This led me down to realized that the s3/storage information is not getting populated into the aws-exports.json file.

I then noticed on every push it is saying that our storage needs to be created (s3), even though it definitely exists.

I then went through the process of doing the overrides migration https://docs.amplify.aws/cli/migration/override/ in the attempt to fix this. I started with storage and did a push which then failed. I then tried doing Auth which resulted in more failures.

So now I have reverted everything and went back to version 6.4.0 which is working.

The following was the latest push failure which means that during your migration process, something is not referencing the new outputs/inputs from auth.

I replaced our resource name with XXXXXX for privacy purposes.
```
UPDATE_FAILED storageXXXXXX   AWS::CloudFormation::Stack Mon Nov 22 2021 15:13:04 GMT-0800 (Pacific Standard Time) Parameters: [authXXXXXXXXXXXXXUserPoolId, authuserPoolGroupsadminGroupRole] do not exist in the template
UPDATE_FAILED apiXXXXXX AWS::CloudFormation::Stack Mon Nov 22 2021 15:13:05 GMT-0800 (Pacific Standard Time) Resource update cancelled   
```

### Expected behavior

amplify push works and amplify-exports.json is generated correctly

### Reproduction steps

See above description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by heyheman11** [comment]
I am also having issues whenever I ran `amplify init` using `amplify-cli@7.4.5` this is the output of my logs
```sh
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/PostConfirmation.map.json' does not exist
    at Function.JSONUtilities.readJson (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at AmplifyToolkit.getTriggerMetadata [as _getTriggerMetadata] (/usr/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:404:85)
    at AmplifyToolkit.getTriggerEnvInputs [as _getTriggerEnvInputs] (/usr/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:489:36)
    at initTriggerEnvs (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:438:43)
    at Object.updateConfigOnEnvInit (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:384:25)
    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:132:28
    at /usr/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

To fix this I had to create a symbolic link between `/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth` and `/usr/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth`

**Comment by kaustavghosh06** [comment]
@gakinson Would it be possible for you to send over a sharable link to download your backend amplify folder (before migration) to amplify-cli@amazon.com for us to investigate further?

**Comment by gakinson** [comment]
> [amplify-cli@amazon.com](mailto:amplify-cli@amazon.com)

Sent

**Comment by tomhirschfeld** [comment]
@kaustavghosh06 ^^ would appreciate your help here quickly, this is block all of our production deployments and merges to master right now

**Comment by kaustavghosh06** [comment]
@tomhirschfeld We're looking into the files which were just sent. @gakinson mentioned - "So now I have reverted everything and went back to version 6.4.0 which is working." You can still continue deployments and pin the version to 6.4.0 if you're using Amplify Console for CI/CD.

**Comment by tomhirschfeld** [comment]
hi @kaustavghosh06 geoff spoke too soon. reverting to 6.4.0 did not work, so pinning the deployments isn't a way out of this for us for now

**Comment by gakinson** [comment]
We tried creating a brand new environment using version 6.4.0 and the new environment is still experiencing the issue where there is no storage (s3) params being generated in the aws-exports.js file. Also, on the admin ui view, it is showing this:

![Screen Shot 2021-11-23 at 1 15 41 PM](https://user-images.githubusercontent.com/3464973/143130321-5808f098-6e22-4e0a-a92a-0d7c0342e9ea.png)
s

**Comment by kaustavghosh06** [comment]
@gakinson How did you create the new environment? CLI or Admin UI? After running a push using 6.4.0 - does the push succeed? What are the contents for the generated `amplify/backend/amplify-meta.json`  file?

**Comment by gakinson** [comment]
I used the CLI. The push succeeds, but no s3 configuration.

Should I send the amplify-meta.json to the same email mentioned above?

**Comment by kaustavghosh06** [comment]
@gakinson From that file it looks like the storage resource hasn't been deployed with 6.4.0. What's the result of `amplify status` for this new environment ?

**Comment by gakinson** [comment]
It may not be the 6.4.0 anymore because I have been trying to roll forward to get it working, but still no luck.

I can create another environment.

Any ideas why it may not be picking up the storage information?

**Comment by gakinson** [comment]
I managed to get the environment to deploy using 7.4.5, but still no s3 configurations getting generated

**Comment by gakinson** [comment]
Migrated storage and auth to overrides, still same issue

**Comment by kaustavghosh06** [comment]
@gakinson The issue is that the "Outputs" from the CloudFormation file need to be populated in the amplify-meta.json file after a successful deployment but the  storage (S3 resource) in the amplify-meta.json file doesn't have the "output" section with the bucket-name like any other resource in that file.

**Comment by gakinson** [comment]
Okay, that makes sense, is there anything I can do locally to test for you guys?

**Comment by kaustavghosh06** [comment]
@gakinson The CLI has generic logic to just put in outputs from cloudformation outputs into that file and that hasn't changed in a while and we aren't able to reproduce locally. Can you try running `amplify push --force` and see if the "output" section for the S3 resource gets populated?

**Comment by gakinson** [comment]
Doing the force push now.

I tested the following:
1. Remove s3 storage resource
2. amplify push
3. Add s3 storage resource
4. amplify push

Still no output getting generated and configs are not generated

**Comment by gakinson** [comment]
Force pushed complete still with no outputs generated

**Comment by kaustavghosh06** [comment]
@gakinson Just sent you an email requesting for a screen-share for us to debug this together. Having no luck reproducing it on our end locally.

**Comment by gakinson** [comment]
@kaustavghosh06 and I have figured out the issue. Amplify is working on a fix right now.  Turns out it was due to a service call that would only return 100 resources and our project has more than 100 resources.
