### ISSUE TITLE
Amplify Headless mode [Documentation is wrong]

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-cli#9049]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

7.4.5

### What operating system are you using?

AWS Cloud9 Linux - CentOS

### Amplify Categories

auth, storage, api

### Amplify Commands

add

### Describe the bug

If I folow headless documentation here: 
https://docs.amplify.aws/cli/usage/headless/#headless-category-payloads
Its need to use `jq` like that:
```
$ cat tool/amplify_storage/tsHeadlessStorage.addstorage.json | jq -c | amplify add storage --headless
jq - commandline JSON processor [version 1.5]
Usage: jq [options] <jq filter> [file...]
No input received on stdin
Error: No input received on stdin
    at Interface.<anonymous> (/home/ec2-user/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/utils/headless-input-utils.ts:28:33)
```
Its appears that JSON is not received from `amplify` 

### Expected behavior

Skip this error and import headless JSON in amplify project 

### Reproduction steps

Follow docs: https://docs.amplify.aws/cli/usage/headless/#headless-category-payloads
try to amplify import in headless mode some JSON file.

# Additional information - How to fix this!

My `jq` version: `jq-1.5` Maybe with the latest jq version this issue will not exist but this fix issue for me:

`jq -c . < tool/amplify_auth_cognito/tsHeadlessAuth.addauth.json | amplify add auth --headless`

**Comment by jhockett** [comment]
Hi @sytolk, what's the output of just running `cat tool/amplify_storage/tsHeadlessStorage.addstorage.json`?

**Comment by sytolk** [comment]
The issue is not with cat. The issue is with `jq`. @jhockett look at the Additional information
```
ec2-user:~/environment/tse-dev (with-tsLambdaLayer) $ cat tool/amplify_storage/tsHeadlessStorage.addstorage.json
{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "S3",
    "permissions": {
      "auth": ["CREATE_AND_UPDATE","READ","DELETE"]
    },
    "bucketName": "tsbucket",
    "lambdaTrigger": {
      "mode": "existing",
      "name": "tsTriggerFunction"
    }
  }
}
```

**Comment by jhockett** [comment]
I'm able to get your JSON payload working on mac with jq version 1.6: `cat addstorage.json | jq -c | amplify add storage --headless`

Can you try updating to jq 1.6 and see if that fixes it for you @sytolk?

**Comment by sytolk** [comment]
```
ec2-user:~/environment/tse-dev (with-tsLambdaLayer) $ sudo yum install jq
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                                                                                                                                                                                                                                              | 3.7 kB  00:00:00     
234 packages excluded due to repository priority protections
Package jq-1.5-1.amzn2.0.2.x86_64 already installed and latest version
```

**Comment by jhockett** [comment]
@sytolk thanks for reporting this issue! We'll update the documentation to account for version 1.5.

**Comment by sytolk** [comment]
Yes can confirm that this works with jq v.1.6 but it's not in the Linux repos now.. can you try if my fix works for you?

```
ec2-user:~/environment/tse-dev (with-tsLambdaLayer) $ cat tool/amplify_storage/tsHeadlessStorage.addstorage.json | jq -c | amplify add storage --headless                                                                                                                                                                                                                      
Amazon S3 storage was already added to your project.
```

**Comment by sytolk** [comment]
@jhockett Why not simple replace `cat | jq` from documentation with script like this:
```javascript
const amplify_storage = require('./tool/amplify_storage/tsHeadlessStorage.addstorage.json');

import('execa').then((module) => {
  module
    .execa('amplify', ['add', 'storage', '--headless'], {
      input: JSON.stringify(amplify_storage),
    })
    .then((returnValue) => {
      console.log('Success: ' + JSON.stringify(returnValue));
    });
});
```

source: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-core/src/utils/headless.ts#L89

**Comment by jhockett** [comment]
Hey @sytolk, apologies on the late response. That's a great alternative, thanks for opening the docs PR!
