### ISSUE TITLE
@aws_subscribe and other declarative declared as unknown , schema graphs giving 'trying to redefine type' error

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-cli#9050]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### Amplify CLI Version

5.3.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, api

### Amplify Commands

codegen

### Describe the bug

the schema.graphql files generated by the amplify pull and amplify codegen give directive errors ( @model @aws_cognito_user_pools @auth..) , keywords such as `(rules: [{allow: private}]) ` give unknown argument error and my schema type are giving 'trying to redefine type' error. 
I have 3 schema.graphql in my amplify directory like this :
├── amplify
│   ├──-#current-cloud-backend
│   │  ├── api
│   │.    │
│   │      └── schema.graphql
├── │
│   ├── backend
          ├── api
          │──────-├
                  ├──build
                  │    └── schema.graphql
                  └── schema.graphql
they all have my datastore schema except for the second that has query and mutation declaration. I don't know how to fix this.

### Expected behavior

run codegen
get generated java classes for my data manipulations
schema files with no errors

### Reproduction steps

amplify pull
amplify codegen

### GraphQL schema(s)

<details>

```graphql
type tabledb @aws_cognito_user_pools @aws_iam {
  id: ID!
  tabname: String
  itabdescription: String
  duration: Int
  _lastChangedAt: AWSTimestamp!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
type Subscription {
  onCreateQuestionsDB: QuestionsDB @aws_subscribe(mutations: ["createQuestionsDB"]) @aws_iam @aws_cognito_user_pools
  onUpdateQuestionsDB: InterviewQuestionsDB @aws_subscribe(mutations: ["updateQuestionsDB"]) @aws_iam @aws_cognito_user_pools
  onDeleteQuestionsDB: InterviewQuestionsDB @aws_subscribe(mutations: ["deleteQuestionsDB"]) @aws_iam @aws_cognito_user_pools
  onCreateUserSettings: UserSettings @aws_subscribe(mutations: ["UserSettings"]) @aws_iam @aws_cognito_user_pools
}
type Mutation {
  createQuestionsDB(input: CreateQuestionsDBInput!, condition: ModelQuestionsDBConditionInput): QuestionsDB @aws_iam @aws_cognito_user_pools
  updateQuestionsDB(input: UpdateQuestionsDBInput!, condition: ModelQuestionsDBConditionInput): QuestionsDB @aws_iam @aws_cognito_user_pools
  deleteQuestionsDB(input: DeleteQuestionsDBInput!, condition: ModeQuestionsDBConditionInput): QuestionsDB @aws_iam @aws_cognito_user_pools
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hi @taouichaimaa, thank you for reporting the issue. Working on trying to reproduce the issue. In the meantime can you update to the latest amplify-cli and check if the issue still happens?

**Comment by lazpavel** [comment]
Hi @taouichaimaa, is it possible for you to share the entire schema? You can send it at amplify-cli@amazon.com

**Comment by taouichaimaa** [comment]
Hello, I sent the files , the subject is the title of this issues. Thank you.

**Comment by taouichaimaa** [comment]
Hi @lazpavel  , any update on the issue? it's been 3 days since I last got an update

**Comment by lazpavel** [comment]
Hi @taouichaimaa, sorry for late response. Can you please share the contents of the `amplify/cli.json` file?

**Comment by lazpavel** [comment]
Replied to your email with an updated schema. Closing the ticket as there seemed to be an issue with the `graphql.schema` content. Please reopen if you still have issues.
