### ISSUE TITLE
Custom auth attributes created pre-v7.4 (as per #1204) are ignored in latest Amplify CLI

### ISSUE THREAD

**Issue by bensewell** [aws-amplify/amplify-cli#9051]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd

### If applicable, what version of Node.js are you using?

14.17.4

### Amplify CLI Version

7.4.5

### What operating system are you using?

Windows

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

amplify push auth ignores existing custom attributes in the CloudFormation template, and attempts to overwrite them with new ones, resulting in failure, as CloudFormation does not allow the changing of a schema,

Having modified my auth cloudformation template as per #1204 to add a custom attribute, I had been happily using it until the latest Amplify CLI.

The error that appears is:
`2021-11-23T10:01:05.011Z [INFO]: UPDATE_FAILED               UserPool                                             AWS::Cognito::UserPool     Tue Nov 23 2021 10:01:01 GMT+0000 (Coordinated Universal Time) Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)
                                 UPDATE_ROLLBACK_IN_PROGRESS amplify-revuclient-dev-145127-authrevu-1BEVIHOZX6WP9 AWS::CloudFormation::Stack Tue Nov 23 2021 10:01:02 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [UserPool].`

### Expected behavior

When pushing new versions of the backend, the auth should push seamlessly. 

### Reproduction steps

I have not tried these as I'm not sure how to get hold of an old version of the CLI (I guess I could build it myself?)

1. Start with a v6 of the amplify CLI
2. `amplify init`
3. `amplify add auth`
4. Add custom attributes to the schema in "amplify/backend/auth/xxx/xxx-cloudformation-template.yml"
5. `amplify push`
6. Upgrade to latest amplify CLI
7. Make some change that requires the auth to be pushed (perhaps `amplify add storage`?)

### Log output

<details>

```
# Put your logs below this line
2021-11-23T10:01:05.011Z [INFO]: UPDATE_FAILED               UserPool                                             AWS::Cognito::UserPool     Tue Nov 23 2021 10:01:01 GMT+0000 (Coordinated Universal Time) Existing schema attributes cannot be modified or deleted. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)
                                 UPDATE_ROLLBACK_IN_PROGRESS amplify-revuclient-dev-145127-authrevu-1BEVIHOZX6WP9 AWS::CloudFormation::Stack Tue Nov 23 2021 10:01:02 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [UserPool].

```

</details>

### Additional information

I have created a fix on a fork (sorry not branched yet) that checks the previous CloudFormation template for a schema and uses that in favour of creating a new one:

https://github.com/bensewell/amplify-cli

If you're amenable to this kind of fix, I could tidy up & test.

**Comment by lazpavel** [comment]
Hi @bensewell, thank you for raising this issue. I am working on trying to reproduce following the steps. In the meantime can you try to downgrade to the previous version that worked? `npm install -g @aws-amplify/cli@6.4.0`

**Comment by akshbhu** [comment]
Hi @bensewell 

Since the templates regenerates on each push with our new version , your custom attributes will get removed.
We have a nicer way to provide this custom attributes in the CFN template through overrides.

you can try ```amplify override auth```, this will generate an ```overrides.ts``` file inside the auth resource folder.

After than you try to customizer userPool with the previous custom attributes and these values will be written in the generated CFN.

Example of an override.ts file is here : https://docs.amplify.aws/cli/auth/override/

Let me know if this works for you ?

**Comment by chris-mds** [comment]
Hi,

you can add custom attributes with the new auth override function @akshbhu mentioned here like the following:

```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const customAttribute = {
    "attributeDataType" : 'String',
    "developerOnlyAttribute" : false,
    "mutable" : true,
    "name" : 'mycustomattribute',
    "required" : false
  };
  resources.userPool.schema = [customAttribute];
}
```

**Comment by bensewell** [comment]
Thanks @akshbhu and @chris-mds - that really helps. All working now.

**Comment by bensewell** [comment]
Just as some constructive feedback, it would have been great if in here: https://docs.amplify.aws/cli/migration/override/  there had been a link to https://docs.amplify.aws/cli/auth/override/ and other related items to help me work this out for myself. 

I love the new method of overriding, much preferable to the old one.
