### ISSUE TITLE
Unable to get storage S3 bucket name in CDK via resource dependency

### ISSUE THREAD

**Issue by shishkin** [aws-amplify/amplify-cli#9052]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

7.4.5

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

publish

### Describe the bug

I'm trying to resolve S3 bucket in custom CDK category using amplify storage resource dependency as described in https://docs.amplify.aws/cli/custom/cdk/#reference-amplify-environment-name.

Resolved bucket name appears hardcoded `storagefilesBucketName`.

### Expected behavior

Bucket name would be resolved correctly.

### Reproduction steps

```TypeScript
    const amplifyResources: AmplifyDependentResourcesAttributes =
      AmplifyHelpers.addResourceDependency(
        this,
        amplifyResourceProps.category,
        amplifyResourceProps.resourceName,
        [{ category: "storage", resourceName: "files" }]
      );
    const bucketName = amplifyResources.storage.files.BucketName;
    const s3Bucket = s3.Bucket.fromBucketName(
      this,
      "Amplify S3 Uploads",
      bucketName
    );
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

amplify build custom
⠙ Building custom resources🛑 There was an error building the custom resources
🛑 Error: Invalid S3 bucket name (value: storagefilesBucketName)
Bucket name must only contain lowercase characters and the symbols, period (.) and dash (-) (offset: 12)
    at Function.validateBucketName (/Users/serega/work/maklerbot/amplify/backend/custom/cdk/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:721:13)

```

</details>

**Comment by kaustavghosh06** [comment]
@shishkin As mentioned in our docs, you'd get the bucket-name as a ref as described here - https://docs.amplify.aws/cli/custom/cdk/#reference-amplify-environment-name

Similar to something like this.

```
const myBuckeetName = cdk.Fn.ref(dependencies.storage.<resource-name>.Name)
```

**Comment by shishkin** [comment]
Thanks @kaustavghosh06! That works. I must have missed the ref.
