### ISSUE TITLE
Amplify init parameters for headless mode dont support json from file (or its not documented)

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-cli#9053]
### Is this feature request related to a new or existing Amplify category?

New category

### Describe the feature you'd like to request

Now its used `jq` to load JSON from file: https://docs.amplify.aws/cli/usage/headless/#headless-category-payloads

But for init parameters its have Unix scripts only:
https://docs.amplify.aws/cli/usage/headless/#amplify-init-parameters

Example script for ` amplify init ` is platform dependent /bin/bash (cannot work on Windows)

### Describe the solution you'd like

I have try to run from command line:
` amplify init --amplify {"projectName":"tsAWSlayer","envName":"dev","defaultEditor":"code"} --frontend {  "frontend": "javascript",  "framework": "react",  "config": {    "SourceDir": "src",    "DistributionDir": "build",    "BuildCommand": "npm run-script build",    "StartCommand": "npm run-script start"  }} --providers {  "awscloudformation": {    "configLevel": "project",    "useProfile": true,    "profileName": "default"  }}`

and this is the error:
```
Cannot create property 'providers' on string '{projectName:tsAWSlayer,envName:dev,defaultEditor:code}'
TypeError: Cannot create property 'providers' on string '{projectName:tsAWSlayer,envName:dev,defaultEditor:code}'
    at transform (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\input-params-manager.ts:45:32)
    at Object.normalizeInputParams (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\input-params-manager.ts:10:3)
    at Object.constructInputParams (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\amplify-service-helper.ts:8:34)
    at constructExeInfo (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\commands\init.ts:15:18)
    at Object.run (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\commands\init.ts:26:3)
    at Object.executeAmplifyCommand (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\index.ts:373:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at executePluginModuleCommand (C:\Users\smari\AppData\Roaming\nvm\v16.6.0\node_modules\@aws-amplify\cli\src\execution-manager.ts:204:3)
```

### Describe alternatives you've considered

I'd like to be possible json file relative path to be provided
`amplify init --amplify scripts/amplify_init.json`

this will work on any platform that amplify-cli can be installed (including Windows)

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by lazpavel** [comment]
Hi @sytolk, what you have should work just remove all the extra spaces as in the below example: 
```
amplify init --amplify {"projectName":"tsAWSlayer","envName":"dev","defaultEditor":"code"} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}} --yes
```

**Comment by lazpavel** [comment]
Closing with above comment, please reopen if you still have issues

**Comment by sytolk** [comment]
Hi @lazpavel the problem in command line is that JSON can't be formatted and it's hard to be changed. This is the reason `cat` and `jq` to be used and JSON to be loaded from file. But this is platform specific Unix only. It's much better amplify cli to take JSON from the file. Don't you think? If you think so pease reopen the issue

**Comment by sytolk** [comment]
@jhockett I think its better to review this issue first: rethink skip usage of `cat` && `jq` to compress JSON before to change documentation in this: https://github.com/aws-amplify/amplify-cli/issues/9049
