### ISSUE TITLE
Figure out the environment inside any override.ts file

### ISSUE THREAD

**Issue by cespin** [aws-amplify/amplify-cli#9063]
### Is this feature request related to a new or existing Amplify category?

auth, storage, api

### Describe the feature you'd like to request

There is no context available in the _override.ts_ files.

I was recently trying to reference a function name and in order to do that properly I needed to know to environment name. I wasn't able to neither figure it out nor to reference the stack parameters.

It would be useful if these files are given a context that contains the stack and project parameters.

### Describe the solution you'd like

I would like to have a context parameter available during inside the _override.ts_ file

### Describe alternatives you've considered

I considered introspecting values already set inside the one object that's being passed to the _override.ts_, for example, in the case of _Auth_ a parameter of type _AmplifyAuthCognitoStackTemplate_ is available and there are attributes set in it which names contain the environment name like the cognito trigger function names. I wasn't able to do this because the values (of type String) that are already set in that object are some sort of internal reference.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chris-mds** [comment]
Got the same issue here.
I want to set a trigger function to my s3 bucket with the following override function (maybe someone can use this, when migrating his s3 setup)

```
import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyS3ResourceTemplate) {
  resources.s3Bucket.notificationConfiguration = {
    lambdaConfigurations : [
      {
        event: 's3:ObjectCreated:*', 
        function:'Here I need access for my env specific lambda function', 
        filter: {
          s3Key: {
            rules: [
              {
                name: 'prefix',
                value: 'exchange'
              },
              {
                name: 'suffix',
                value: 'xml'
              }
            ]
          }
        }
      },
      {
        event: 's3:ObjectRemoved:*', 
        function:'functionDriversAppFileInterfaceHandlerArn', 
        filter: {
          s3Key: {
            rules: [
              {
                name: 'prefix',
                value: 'exchange'
              },
              {
                name: 'suffix',
                value: 'xml'
              }
            ]
          }
        }
      }
    ]
  }
}

```

Of course I can hardcode it, but I guess this doesn't make sense in long term and isn't the idea behind this new override pattern,

**Comment by kaustavghosh06** [comment]
@cespin @chris-mds Thanks for explaining your use cases. What all information would be helpful for you’ll to be present in this context apart from env name?

**Comment by chris-mds** [comment]
@kaustavghosh06 for me it would be very helpful to access my configured external resources just like we know it from a lambda function:

`/* Amplify Params - DO NOT EDIT
	API_APPGRAPHQLAPI_GRAPHQLAPIENDPOINTOUTPUT
	API_APPGRAPHQLAPI_GRAPHQLAPIIDOUTPUT
	ENV
	REGION
	STORAGE_APPSTORAGE_BUCKETNAME
Amplify Params - DO NOT EDIT */`

So e.g.

```amplify update storage```

```Do you need to access other resources from this project? (Y/n)```

```
Chose the resources you need to access
- Auth ( )
- Function (x)
- Storage ( )
- ...
```

```
Chose which function you need to access
- MySuperCoolLambdaFunction (x)
```

and this will give you all the necessary informations you need to implement in your override function. Without this kind of functionality I don't have a clue, how I can access my functions for the trigger

**Comment by cespin** [comment]
In short: access to the same info that the we have available when editing the stack's CloudFormation file manually. Mainly the (nested) stack's parameters. The environment is just one of these parameters. Like this we can keep on adding parameters and secrets through the Amplify CLI and reuse them here.

**Comment by gakinson** [comment]
If you need just the environment name and app id, you can access it via

```
import {
   getProjectInfo,
} from '@aws-amplify/cli-extensibility-helper';

export function override(resources: ...) {
  const projectInfo = getProjectInfo();

}
```

**Comment by chris-mds** [comment]
Thanks @gakinson,
Is this somewhere documented?

I updated my code with the new variable and it works for different env like expected. Maybe someone can use this as a reference. Function overrides trigger for an s3 bucket with prefix 'exchange' and suffix 'xml' in this example. Trigger lambda function gets called for every create and put event when the filter matches. And of course you have to replace the 'xxxx' in the arn with your account id as well as your region and function name.

```
import { AmplifyS3ResourceTemplate, getProjectInfo } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyS3ResourceTemplate) {
  const projectInfo = getProjectInfo()
  resources.s3Bucket.notificationConfiguration = {
    lambdaConfigurations : [
      {
        event: 's3:ObjectCreated:*', 
        function:`arn:aws:lambda:YourRegion:xxxxxxx:function:YourSuperCoolTriggerFunctionName-${projectInfo.envName}`, 
        filter: {
          s3Key: {
            rules: [
              {
                name: 'prefix',
                value: 'exchange'
              },
              {
                name: 'suffix',
                value: 'xml'
              }
            ]
          }
        }
      },
      {
        event: 's3:ObjectRemoved:*', 
        function:`arn:aws:lambda:YourRegion:xxxxxxx:function:YourSuperCoolTriggerFunctionName-${projectInfo.envName}`, 
        filter: {
          s3Key: {
            rules: [
              {
                name: 'prefix',
                value: 'exchange'
              },
              {
                name: 'suffix',
                value: 'xml'
              }
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by chris-mds** [comment]
I get a new error I didn't recognized before when using the getProjectInfo.

`⠇ Building resource storage/MyStorage🛑 Error: Skipping override due to VMError: Access denied to require 'os'`

So I guess this helper function tries to get the env through the os, which is denied by my system. How can I fix this?

**Comment by cespin** [comment]
I had already tried this @chris-mds, the only difference on my side is that I was overriding the Auth. I got the same error.

I also tried to access the nested stack's parameter using CDK primitives, all the info we need is the params. I got a similar error that said that I didn't have permissions to access 'fs'.

@kaustavghosh06, why can't we import CDK constructs in the override.js files and use them? I was trying to set a Ref this way and I got the error I mentioned above. Similarly, if we need to use the SSM/secret manager resolve feature we cannot because imports and CDK primitives are restricted.

@chris-mds , it's documented [here](https://docs.amplify.aws/cli/project/override/)

**Comment by gakinson** [comment]
I am also experiencing the same error when I add the getProjectInfo function to my overrides.ts file in auth. I tried doing a bunch of debugging last night, but didn't get anywhere. Hopefully the Amplify team can help with this one soon.

**Comment by chris-mds** [comment]
Hi @akshbhu,

Do you have an ETA for this fix? Without it, we cant migrate amplify to the new versions >= 7.x.x properly

**Comment by christianguevara** [comment]
Any ETA? Overrides are not fully useful if the env can't we obtained.

**Comment by arledesma** [comment]
I have not seen a pr for the [proposed solution](https://github.com/aws-amplify/amplify-cli/issues/9081#issuecomment-979407163) from @akshbhu 

> Currently fs/ env access is blocked in override files except for custom resources which we use at build time, so getProjectInfo wont work in overrides.ts files.  
> 
> We are working as an enhancement to provide project/env info in the overrides function.

I have opened pr #9241 to provide project/env into overrides via `global.amplify`. 🤷

**Comment by ahiratan** [comment]
I could get backend setting using `require` command in `override.ts` like this:

```
// This file is used to override the REST API resources configuration
import { AmplifyApiRestResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiRestResourceStackTemplate) {
  // access to `<project_dir>/amplify/backend/amplify-meta.json`
  const amplifyMetaJson = require('../../../amplify-meta.json');
}
```

Could this be a work around solution?

**Comment by cespin** [comment]
Nice work around @ahiratan !

Did you test it? Don't you get any of those errors about not having access to 'fs' or 'os' ?

In amplify-meta.json there are ways to figure out the env name, for example, chopping the stackName in pieces should do the trick. It's still a work around but better than being completely blocked.

**Comment by cespin** [comment]
Ok, @ahiratan 's work around does the trick. Just tested it.

I could get the environment like this:

```javascript
    const amplifyMetaJson = require('../../../amplify-meta.json');
    console.log(amplifyMetaJson.providers.awscloudformation.StackName.split("-").slice(-2, -1).pop());
```

It's obviously a hack but better than nothing.

**Comment by ahiratan** [comment]
Good. 
As you say this not a good solution and I expect that at least `getProjectInfo()` will work properly because this function is now exposed to users.
https://github.com/aws-amplify/amplify-cli/blob/v7.6.3/packages/amplify-cli-extensibility-helper/src/index.ts#L2

And also I think it's better that we can use with "Export Amplify project to CDK".
https://docs.amplify.aws/cli/usage/export-to-cdk/

**Comment by nickwilldoit** [comment]
@cespin and @ahiratan thanks for this. I'm using this hack, but it's pretty scary. I'm also using it to get the outputs from other stacks so I can refer to them in my Auth overrides.ts (in this case, I need to reference an EmailConfiguration).

It's wacky to me that such a hack is needed, and I'm still on the fence about just reverting to an older version of the amplify cli. If this hack suddenly stops working I'm in trouble...

**Comment by IvanCaceres** [comment]
Also attempting to migrate my auth resource to v7, it had some custom stuff in cloudformation but now in the override.ts there's isn't any way to access !Ref parameters from other resources in the amplify project.

How can we reference a Lambda function name and function arn? Functions which were added through the amplify CLI.

**Comment by vifox001** [comment]
I'm also getting the error `Failed to override [category] due to: VMError: Access denied to require 'os'.` when calling the `AmplifyHelpers.getProjectInfo()` inside the override.ts.

@cespin workaround works👍🏼, but better to sort it out in the amplify cli.

**Comment by aqarcoSys** [comment]
I need to change elasticsearch instances based on env, I cannot detect which env name ,I get always `Access denied to require 'os'` and somehow the prev workaround does not work anymore ?

**Comment by jhockett** [comment]
As a temporary workaround, you can use a CloudFormation intrinsic function or reference in many cases. The type system might complain, so you may need to use a less strict type instead of the provided type. 

For example, let's say I want to include the environment for my rest API in the description:
```ts
export function override(resources: any) {
  resources.restApi.description = { 'Fn::Sub': 'REST API for environment ${env}' };
}
```

**Comment by chris-mds** [comment]
Hi @jhockett,

Do you have an example, how to get your approach working on the s3 override inside a more nested property? I have posted my code a bit above.

**Comment by IvanCaceres** [comment]
It seems the workaround to require the amplify-meta.json has stopped working. I was using that to get the environmental info: ARNs, function names etc for use when setting the user pool triggers (in the override method it's the resources.userPool.lambdaConfig property).

This workaround in the auth override.ts file which was previously working correctly is now throwing a syntax error on amplify push about an unexpected token:

I'm not sure why this require statement is the problem now after previously working during several amplify push's.
**Line of code causing error** (it works when I comment out this require statement):
`const amplifyMetaJson = require('../../../amplify-meta.json')`

**Error message** (occurs during amplify push):
`Error: Skipping override due to SyntaxError: Unexpected token (2:13)`


To get around this I have hardcoded the ARN values and function names inside of my override.ts file. I have different values in the file on git branches for prod/staging.

**Comment by himesh-sv** [comment]
Hello everyone,
I also needed some environment information in my auth override.

First I tried @ahiratan and @cespin 's workaround. which was to get `amplify-meta.json` and retrieve properties via some string operations. Which worked locally but when it goes through CI/CD Code pipeline it cause the error mentioned by @aqarcoSys  which was saying `Error: Skipping override due to SyntaxError: Unexpected token (2:13)` This was caused due to a node version error in the runtime env (in CI/CD).

**My Solution**
To overcome the above problem I used Amplify Command Hooks, specifically the `pre-push` hook.
You can read the `amplify-meta.json`  at that time since the project is already initiated. So read the `amplify-meta.json`  and retrieve and assign all properties you need to a string variable and create a new file from that for you to use inside your override.ts

**Inside `pre-push.js`**
```
const hookHandler = async (data, error) => {
  const fs = require("fs");
  let amplifyMeta = JSON.parse(
    fs.readFileSync("amplify/backend/amplify-meta.json")
  );
  let resourceName = Object.keys(amplifyMeta.auth)[0];
  let accountId = amplifyMeta.providers.awscloudformation.AuthRoleArn.split(":")[4];
  let region = amplifyMeta.providers.awscloudformation.Region;

  const content = `
  export const authConfig = {
    "amplify_env": "${data.amplify.environment.envName}",
    "resource_name":"${resourceName}",
    "account_id":"${accountId}",
    "region":"${region}"
} 
  `;
  try {
    fs.writeFileSync(`amplify/backend/auth/${resourceName}/config.ts`, content);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};
```
In my case, I can read those properties by importing config.ts to override.ts. By this workaround, it is possible to get any values from the amplify-meta.json.

Refer,
[Command Hooks Doc](https://docs.amplify.aws/cli/project/command-hooks/)

**Comment by cespin** [comment]
Marvellous suggestion to use hooks @nickwilldoit / @himesh-sv .

I had to modify @himesh-sv 's solution a bit to make it work with my project. Here's a detailed step-by-step of what I did:

1.  Create the file _amplify/hooks/pre-push.js_ and include this:

```javascript
const fs = require("fs");
const parameters = JSON.parse(fs.readFileSync(0, { encoding: 'utf8' }));
let amplifyMeta = JSON.parse(
    fs.readFileSync("amplify/backend/amplify-meta.json")
);
let resourceName = "YOUR_USERPOOL_RESOURCE_NAME";
let accountId = amplifyMeta.providers.awscloudformation.AuthRoleArn.split(":")[4];
let region = amplifyMeta.providers.awscloudformation.Region;

const content = `export const AuthContext = {
    "environment": "${parameters.data.amplify.environment.envName}",
    "resource_name":"${resourceName}",
    "account_id":"${accountId}",
    "region":"${region}"
}`;
try {
    fs.writeFileSync(`amplify/backend/auth/${resourceName}/config-auth-override.ts`, content);
    process.exit(0);
} catch (err) {
    console.error(err);
    process.exit(1);
}
```

Remember to change "YOUR_USERPOOL_RESOURCE_NAME" for the value that makes sense for your Amplify project. I did it like this and not like @himesh-sv because in my case I have two items in the array.

2. Use the new module in your Auth _override.ts_ file: 

```javascript
import {AuthContext} from "./config-auth-override";
...
console.log(AuthContext["environment"]);
```

3. Exclude the generated file _config-auth-override.ts_ from version control. I added this to my _.gitignore_ file:

```
config-*-override.ts
```

Still a hack, it's just a cleaner hack =D Ideally the final context would be provided as an invocation param.

**Comment by chakch** [comment]
any update for this issue ?

**Comment by gakinson** [comment]
Hello,

Was there something special to get the suggested hack mentioned from @cespin to work in the CI/CD? I have the pre-push.js file in the amplify/hooks directory and the amplify console CI/CD is not executing the hook. Works locally, but not in console.

Thank you!

**Comment by anurag128** [comment]
Hello @gakinson,

To make it work in Amplify Console can you try doing "amplify push" locally, as mentioned here https://docs.amplify.aws/cli/project/command-hooks/#using-command-hooks-in-amplifys-cicd-pipeline , we need to do "amplify push" locally to upload the hooks. Hope it helps :)

**Comment by cespin** [comment]
@gakinson , it literally took me ~5 hours to make the pipeline execute the hooks. In my case, I tried different flavours of what @anurag128 is suggesting but it wasn't working out.

I tried different things (and commits and `amplify push` commands) so I'm not 100% sure what made the pipeline finally execute the hooks but when it finally did it once it never stopped working.

Assuming that you're following the recipe that I described above, try this: 

- Go to the folder /amplify/backend/auth/YOUR_USERPOOL_RESOURCE_NAME
- In there, create the file _config-auth-override.ts_
- Put this inside the file: 

```javascript
export const AuthContext = {
    "environment": "XXX",
    "resource_name":"YOUR_USERPOOL_RESOURCE_NAME",
    "account_id":"000000000000",
    "region":"us-east-1"
}
```
- Commit and push to let the pipeline run

Let me know if it works, I'm curious :)

**Comment by himesh-sv** [comment]
Hi @gakinson ,
For some reason, Amplify Hook (pre-push.js) is getting overwritten with a default file at the time of running `amplify push` in the CI/CD pipeline. You can programmatically copy the file and insert it before running `amplify push`  in your deployment script. First copy your current pre-push.js to your root (better to check in the file) and add the following to your deployment script before amplify push command.

`cp pre-push.js amplify/hooks/`

**Comment by gakinson** [comment]
Thanks for all the help!

I will test some stuff out today, but I did find that if I ran an amplify push locally for an environment, the contents in the s3 bucket for deployment get updated. I may just try copying the content directly into the S3 deployment bucket to see if that works.

**Comment by gakinson** [comment]
One thing I ended up doing was deploy just the hook change first so that it gets uploaded to the cloud on the end of the deployment. Then I did the change for the auth resource and pushed after.

**Comment by cespin** [comment]
For anyone still fighting with this:

- I had to disable the `--simple` flag in my `amplify.yml` file. Otherwise my pre-push hook wouldn't run.
- Within the pipeline execution I couldn't get a hold of the _amplify-meta.json_ file so I had to grab the values from env vars. The end result is this:

```javascript
const fs = require("fs");
const parameters = JSON.parse(fs.readFileSync(0, {encoding: 'utf8'}));
let accountId, region, environment;

try {
    const amplifyMeta = JSON.parse(fs.readFileSync("amplify/backend/amplify-meta.json"));
    accountId = amplifyMeta.providers.awscloudformation.AuthRoleArn.split(":")[4];
    region = amplifyMeta.providers.awscloudformation.Region;
    environment = parameters.data.amplify.environment.envName;
} catch (e) {
    console.warn("No amplify-meta.json found, falling back to environment variables");
    accountId = process.env.CUSTOMER_ACCOUNTID;
    region = process.env.AWS_REGION;
    environment = process.env.AWS_BACKEND_ENVIRONMENT_ARN.split("/").pop();
}
if (!accountId || !region || !environment) {
    throw new Error("Couldn't find accountId, region or environment");
}
const content = `export const BuildContext = {
    "environment": "${environment}",
    "account_id":"${accountId}",
    "region":"${region}"
}`;
console.info("config-override content:", content);
try {
    fs.writeFileSync(`amplify/backend/auth/MY-AUTH-RESOURCE/config-override.ts`, content);
    fs.writeFileSync(`amplify/backend/api/MY-API-RESOURCE/config-override.ts`, content);
    process.exit(0);
} catch (err) {
    console.error(err);
    process.exit(1);
}
```

The first case with the _amplify-meta.json_ file works in my local environment and the second one with the env vars works for the pipeline.

With that I can do this in the _override.ts_ files:

```javascript
import {BuildContext} from "./config-override";
...
console.info(BuildContext["environment"]);
console.info(BuildContext["account_id"]);
console.info(BuildContext["region"]);
```

**Comment by yaquawa** [comment]
Any update to this? if we can't get the ARN of amplify generated resource the override feature is useless...🥲

**Comment by yaquawa** [comment]
Even importing file from current directory won't work .
For example `import X from './XXX.ts'` won't work.

Please considering include the directory path of the `override.ts`, by setting the `require.root` option in the upstream lib [vm2](https://github.com/patriksimek/vm2).

**Comment by josefaidt** [comment]
Hey folks in the thread :wave: this is now possible with resource overrides for all categories except for API (for now). You can upgrade to the latest CLI (11.0.3 at the time of writing) and upgrade the Extensibility helper - with CDK v2.

Once upgraded, you can add the second argument to the override function `amplifyProjectInfo` to get the project name and environment name! 🎉 

```ts
import {
  AmplifyAuthCognitoStackTemplate,
  AmplifyProjectInfo,
} from '@aws-amplify/cli-extensibility-helper'

export function override(
  resources: AmplifyAuthCognitoStackTemplate,
  amplifyProjectInfo: AmplifyProjectInfo
) {
  console.log(amplifyProjectInfo.projectName, amplifyProjectInfo.envName)
}

```

**Comment by josefaidt** [comment]
Closing as this issue is now resolved 🙂

**Comment by wvidana** [comment]
In case anyone is looking into this and don't want to upgrade just yet, take a look at this comment on the use of `addPropertyOverride` to write plain cfn code into override.ts (using `Fn:Sub` or `Ref` with access to the cfn properties like `env` and so on)

https://github.com/aws-amplify/amplify-cli/issues/12582#issuecomment-1535038019

**Comment by macamhi** [comment]
> Hey folks in the thread 👋 this is now possible with resource overrides for all categories except for API (for now). You can upgrade to the latest CLI (11.0.3 at the time of writing) and upgrade the Extensibility helper - with CDK v2.
> 
> Once upgraded, you can add the second argument to the override function `amplifyProjectInfo` to get the project name and environment name! 🎉
> 
> ```ts
> import {
>   AmplifyAuthCognitoStackTemplate,
>   AmplifyProjectInfo,
> } from '@aws-amplify/cli-extensibility-helper'
> 
> export function override(
>   resources: AmplifyAuthCognitoStackTemplate,
>   amplifyProjectInfo: AmplifyProjectInfo
> ) {
>   console.log(amplifyProjectInfo.projectName, amplifyProjectInfo.envName)
> }
> ```

Hi, this is not working for me when deploying the branch to Amplify Hosting, the back-end build fails with an error message :
Cannot read property 'envName' of undefined
Indeed, amplifyProjectInfo is undefined when the override function is called at that time.
What's really strange is that it works fine when building and pushing locally!
I tried both with amplify CLI 11.0.5 and latest (12.1.1).
Any idea of what's wrong?

**Comment by redjonzaci** [comment]
Hey, I have the same problem with @macamhi.

**Comment by redjonzaci** [comment]
I paid a little more attention to this comment and I saw that I was trying to use `amplifyProjectInfo` in an API's `override.ts`. 
Is there any workaround for the API category? Because I can't merge my changes otherwise.

> Hey folks in the thread 👋 this is now possible with resource overrides for all categories except for API (for now). You can upgrade to the latest CLI (11.0.3 at the time of writing) and upgrade the Extensibility helper - with CDK v2.
> 
> Once upgraded, you can add the second argument to the override function `amplifyProjectInfo` to get the project name and environment name! 🎉
> 
> ```ts
> import {
>   AmplifyAuthCognitoStackTemplate,
>   AmplifyProjectInfo,
> } from '@aws-amplify/cli-extensibility-helper'
> 
> export function override(
>   resources: AmplifyAuthCognitoStackTemplate,
>   amplifyProjectInfo: AmplifyProjectInfo
> ) {
>   console.log(amplifyProjectInfo.projectName, amplifyProjectInfo.envName)
> }
> ```
