### ISSUE TITLE
amplify cli headless mode init don't take framework parameter

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-cli#9065]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.6.0

### Amplify CLI Version

7.4.5

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

I'm using amlify headless init from command line:
https://docs.amplify.aws/cli/usage/headless/#--frontend

It's have in compressed JSON: `"framework":"react"`
```
 amplify init --amplify{"projectName":"tsAWSlayer","envName":"dev","defaultEditor":"code"} --frontend{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-scri
pt build","StartCommand":"npm run-script start"}} --providers{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}}
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project tagspacesaws
The following configuration will be applied:

Project information
| Name: tagspacesaws
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm.cmd run-script build
| Start Command: npm.cmd run-script start

? Initialize the project with the above configuration? (Y/n)
```
but in the results there is no react configured: `Javascript framework: none`

### Expected behavior

headless init confuguration to be set

### Reproduction steps

run in console this:

```
 amplify init --amplify{"projectName":"tsAWSlayer","envName":"dev","defaultEditor":"code"} --frontend{"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-scri
pt build","StartCommand":"npm run-script start"}} --providers{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default"}}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sytolk** [comment]
This one is different from configuration too
```
| Build Command: npm.cmd run-script build
| Start Command: npm.cmd run-script start
```

I have different in JSON without `.cmd`: `"BuildCommand":"npm run-script build","StartCommand":"npm run-script start"`

**Comment by lazpavel** [comment]
Hi @sytolk, thank you for raising this issue, I was able to reproduce and marked as a bug for the team to pickup.

**Comment by lazpavel** [comment]
Hi @sytolk, it looks there is an issue with the invocation command, here is the updated command with correct escaping that works:

`amplify init --amplify "{\"projectName\":\"tsAWSlayer\",\"envName\":\"dev\",\"defaultEditor\":\"code\"}" --frontend "{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm run-script build\",\"StartCommand\":\"npm run-script start\"}}" --providers "{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":true,\"profileName\":\"default\"}}"
`

The recommended way would be to use a script file as documented here: https://docs.amplify.aws/cli/usage/headless/#sample-script

**Comment by lazpavel** [comment]
Closing per above comments, please reopen if you still have issues

**Comment by sytolk** [comment]
Thanks @lazpavel 
But using recommended script https://docs.amplify.aws/cli/usage/headless/#sample-script is platform dependent. 
You can't run this script on Windows -> #!/bin/bash
Maybe this feature request can fix this issue too: https://github.com/aws-amplify/amplify-cli/issues/9053

**Comment by cjihrig** [comment]
The linked bash script can be ported to run on Windows.

**Comment by sytolk** [comment]
@cjihrig I know :) The main issue is: this: https://github.com/aws-amplify/amplify-cli/issues/9053
Look at this: https://docs.amplify.aws/cli/usage/headless/#headless-category-payloads
Maybe you can port `cat` and `jq` to Windows too ?
`cat myAddApiRequest.json | jq -c | amplify add api --headless`
The problem is in amplify cli it not take json from file

**Comment by sytolk** [comment]
Why not simple create node script:

```javascript
const shell = require('shelljs');
const amplify = require('./amplify.json');
const frontend = require('./frontend.json');
const providers = require('./providers.json');

const cmd =
  'amplify init --amplify "' +
  JSON.stringify(amplify).replaceAll('"', '\\"') +
  '" --frontend "' +
  JSON.stringify(frontend).replaceAll('"', '\\"') +
  '" --providers "' +
  JSON.stringify(providers).replaceAll('"', '\\"') +
  '" --yes';
if (shell.exec(cmd).code !== 0) {
  shell.echo('Error amplify init');
  shell.exit(1);
}

```
