### ISSUE TITLE
Override configuration for Storage/S3 not working on Amplify Console CI/CD builds

### ISSUE THREAD

**Issue by javiermartingonzalez** [aws-amplify/amplify-cli#9067]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.5.1

### What operating system are you using?

AWS Builds

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

I have an override.ts file for storage on my Amplify. Using my local computer, with `amplify push`, it is updated to cloud without any problem.

But for AWS Amplify builds (it is using `amplifyPush --simple`), when machine automatically create the build, all included on override.ts is reverted to base status. I need to make `amplify push` from my local computer to apply again the overrides. It is working but when someone upload to git and then AWS Amplify generate the build, agian is reverted.

### Expected behavior

When building bakend on AWS with `amplifyPush --simple` command, take care of override.ts modifications

### Reproduction steps

1. Create override storage
2. Add some CDK changes
3. Apply it from local computer (ok)
4. Upload something to git and then AWS Amplify starts building
5. When building backed, all on override.ts is reverted to base and that build is not considering override.ts configurations

### Additional information

applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush --simple

**Comment by kaustavghosh06** [comment]
@javiermartingonzalez Di you have the overrides.ts file checked into git which is used for building the backend in CI/CD?

**Comment by javiermartingonzalez** [comment]
Yes, it’s on the git repository

**Comment by kaustavghosh06** [comment]
Got it. Can you also ensure that the following flag is enabled in `amplify/cli.json` file

```
    "project": {
      "overrides": true
    }
```

**Comment by javiermartingonzalez** [comment]
Yes, flag is enabled and that file is on Git, too.

**Comment by josefaidt** [comment]
Hey @javiermartingonzalez :wave: thanks for filing this! I was able to reproduce after adding a simple override to enable versioning on my s3 resource. After pushing to git, and subsequently allowing the console to build my backend versioning was suspended.

```ts
// amplify/backend/storage/<my-resource-name>/override.ts
import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyS3ResourceTemplate) {
  resources.s3Bucket.versioningConfiguration = {
    status: 'Enabled',
  }
}
```

![image](https://user-images.githubusercontent.com/5033303/143303225-ffeb9e77-a307-48ac-b375-81bbb1c5229c.png)

Marking as a bug 🙂 

cc @akshbhu this may also be relevant https://github.com/josefaidt/amplify-storage-overrides/commit/51f947c6649942a293c12e4dde432fcd33406d42
