### ISSUE TITLE
Public app without authentication

### ISSUE THREAD

**Issue by cmnstmntmn** [aws-amplify/amplify-cli#9069]
# Problem

I have an Amplify app, and i'm storing data in Amplify backend.
I can't use keys since they are going to expire.
In the same time, i don't have users ..

# Question

How to i authenticate my app backend to consume data from Amplify backend (using a permanent key)?

**Comment by renebrandel** [comment]
Hi @cmnstmntmn , I assume you're looking to use GraphQL? You can use the `{allow: public, provider: iam}` authorization rule to tackle this. It'll use your auth category's "unauthenticated" IAM role to access https://docs.amplify.aws/cli/graphql/authorization-rules/#public-data-access

**Comment by cmnstmntmn** [comment]
@renebrandel but i don't see how i can change from `API_KEY` 
to `IAM`, since this file is automatically generated.

```js
// aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "url/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY", // <------------------ set this to IAM
    "aws_appsync_apiKey": "da2-irfn5lbxkzdxlmsbghlgj5db4e"
};
```

**Comment by juniarz** [comment]
> @renebrandel but i don't see how i can change from `API_KEY` to `IAM`, since this file is automatically generated.
> 
> ```js
> // aws-exports.js
> 
> const awsmobile = {
>     "aws_project_region": "us-east-2",
>     "aws_appsync_graphqlEndpoint": "url/graphql",
>     "aws_appsync_region": "us-east-2",
>     "aws_appsync_authenticationType": "API_KEY", // <------------------ set this to IAM
>     "aws_appsync_apiKey": "da2-irfn5lbxkzdxlmsbghlgj5db4e"
> };
> ```

Hi, to change that, you have to update your api. You will be able to set the default auth provider and the secondary auth providers.

The aws_exports.js file will use the default auth provider as the authenticationType.

Another way I am doing this is to switch the authtype mode during the API call.

Check out: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js/#using-amplify-graphql-client

**Comment by renebrandel** [comment]
Correct. @cmnstmntmn run `amplify update api` to choose "Authorization modes" -> "IAM"
