### ISSUE TITLE
Override in Auth not Executing

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-cli#9081]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I  added some code to the generated override.ts file in auth category and when I do an amplify push, those changes are not being reflected.

The following is what my overrides look like:

```
import {
  AmplifyAuthCognitoStackTemplate,
  getProjectInfo,
} from '@aws-amplify/cli-extensibility-helper';

const NON_DEVELOPER_ENVS = ['production', 'master'];

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const projectInfo = getProjectInfo();

  if (NON_DEVELOPER_ENVS.includes(projectInfo.envName)) {
    resources.userPool.emailConfiguration = {
      emailSendingAccount: 'DEVELOPER',
      from: 'XXXXX@XXXX.com',
      sourceArn: 'XXXXXXX',
    };
  } else {
    resources.userPool.emailConfiguration = {
      emailSendingAccount: 'COGNITO_DEFAULT',
    };
  }
}
```

The resulting cloudformation file has no reference to emailConfiguration

### Expected behavior

modified values should appear in the built cloudformation file.

### Reproduction steps

See above description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by gakinson** [comment]
I have isolated the issue to being the import of getProjectInfo. How do we get the environment name in the stack?

**Comment by gakinson** [comment]
Followed instructions in https://docs.amplify.aws/cli/custom/cdk/#reference-amplify-environment-name  to reference the env, but now I get this error on build:

```
🛑 Error: Skipping override due to VMError: Access denied to require 'os'

2021-11-25T06:39:48.599Z - error: uncaughtException: Skipping override due to VMError: Access denied to require 'os'
 date=Wed Nov 24 2021 22:39:48 GMT-0800 (Pacific Standard Time), pid=15181, uid=501, gid=20, cwd=/Users/geoffreykinson/IdeaProjects/wesponsored-web, execPath=/Users/geoffreykinson/.nvm/versions/node/v12.22.1/bin/node, version=v12.22.1, argv=[/Users/geoffreykinson/.nvm/versions/node/v12.22.1/bin/node, /Users/geoffreykinson/.nvm/versions/node/v12.22.1/bin/amplify, build], rss=526921728, heapTotal=461672448, heapUsed=439455928, external=7277069, arrayBuffers=2533573, loadavg=[4.77783203125, 4.04931640625, 4.318359375], uptime=36668, trace=[], stack=undefined

```

**Comment by akshbhu** [comment]
Hi @gakinson 

Currently fs/ env  access is blocked in override files except for custom resources which we  use at build time, so getProjectInfo wont work in overrides.ts files.

We are working as an enhancement to provide project/env info in the overrides function.

**Comment by akshbhu** [comment]
closing as a dpulicate of https://github.com/aws-amplify/amplify-cli/issues/9063

**Comment by gakinson** [comment]
> Hi @gakinson 
> 
> Currently fs/ env  access is blocked in override files except for custom resources which we  use at build time, so getProjectInfo wont work in overrides.ts files.
> 
> We are working as an enhancement to provide project/env info in the overrides function.

Do you have an ETA on this feature?

**Comment by houmark** [comment]
Any ETA on this @akshbhu? We are also stuck not being able to override custom triggers due to not being able to pull the ENV which prevents us from setting the correct triggers in all environments.
