### ISSUE TITLE
On Amplify push: Failed to create models in the cloud: Modelgen job creation failed

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9084]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.5.2

### What operating system are you using?

Window 10

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

When doing a push I seem to always get this error right at the end. It doesn't seem to effect anything but its big and red and not giving me the "everything is good" vibes.

### Expected behavior

It does the thing its complaining it can't do. Also...if it can't do it but still runs is it a false negative?

### Reproduction steps

I'm aware that as ever this might be a issue with my setup (tm) however this is what I'm doing:

I've DataStore install and runnning, so have the additional models.

`amplify push -y`

Wait. Right at the end if all goes well it will render the error as shown below. Build and push still deploy though...

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/1674590/143435976-0f29c2a6-fef6-4c68-b23f-e01fc5992507.png)

**Comment by cjihrig** [comment]
This is being tracked in https://github.com/aws-amplify/amplify-cli/issues/9070. Would you mind following along there.

**Comment by maremoto** [comment]
The same is happening to us

**Comment by PeteDuncanson** [comment]
Closing as this is a duplicate of #9070 (sorry don't know how I missed the other one).
