### ISSUE TITLE
Is it possible to use amplify mock api without java

### ISSUE THREAD

**Issue by ravi-palakodeti** [aws-amplify/amplify-cli#9086]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g 

### If applicable, what version of Node.js are you using?

14.x.x

### Amplify CLI Version

7.5.2

### What operating system are you using?

OSX

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Is java needed to run amplify mock api. Based on this [#4456](https://github.com/aws-amplify/amplify-cli/issues/4456), it states that java is needed to run the in memory dynamodb server. I have a container image of that db and am interested in using that instead of installing java on the OS. Is this possible or potentially a feature that can be included in the future

### Expected behavior

I would like to use amplify mock api without installing java on the OS

### Reproduction steps

npx create-react-app xxx
amplify init
amplify add api
amplify mock api

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
Failed to start API Mock endpoint Error: Command failed with exit code 1: java -version
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

```

</details>

**Comment by akshbhu** [comment]
Hi @ravi-palakodeti 

Its currently not possible because to maci api we use dynamoDB local which requires java as dependency.
you can check more info here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

**Comment by ravi-palakodeti** [comment]
The link you shared has a reference to a docker-compose script that will do it for me. All I would then need is a way for amplify CLI to know where my docker db is running (essentially a way to inject host URL for dynamodb). Alternately, I tried to run amplify CLI on a docker container that has java and ran into an issue where it expects to host the mock server on localhost. Being able to change this url via configuration would also help
