### ISSUE TITLE
DEPLOY FAILING! Error: Cannot find module 'provider-utils/awscloudformation/index' after update to Amplify 7.5.2

### ISSUE THREAD

**Issue by georgeleeventures** [aws-amplify/amplify-cli#9097]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v10.23.2

### Amplify CLI Version

7.5.2

### What operating system are you using?

Amazon Linux, Cloud9

### Amplify Categories

Not applicable

### Amplify Commands

pull, push

### Describe the bug

I am unable to do any deployments via a push or a pull after upgrading my amplify to the latest 7.5.2.

When I run amplify pull on my Amazon Linux Cloud9, I get the following error:
```
Error: Cannot find module 'provider-utils/awscloudformation/index'
Require stack:
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/lib/initialize-env.js
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/lib/pull-backend.js
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/lib/commands/pull.js
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/lib/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Promise.resolve.then (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js:128:80)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
When I try to deploy to AWS Amplify console, this is the error I get:

```
2021-11-26T03:23:41.247Z [WARNING]: ✖ There was an error initializing your environment.
2021-11-26T03:23:44.384Z [INFO]: [31mFailed to pull the backend.[39m
2021-11-26T03:23:44.389Z [INFO]: [31mCannot find module 'provider-utils/awscloudformation/index'[39m
                                 [31mRequire stack:[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting/lib/ElasticContainer/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/domain/amplify-toolkit.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/domain/context.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/context-manager.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/index.js[39m
                                 [31m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/bin/amplify[39m
2021-11-26T03:23:44.390Z [INFO]: [0m/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js:1[0m
                                 [0mError: Cannot find module 'provider-utils/awscloudformation/index'[0m
                                 [0mRequire stack:[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting/lib/ElasticContainer/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/on-category-outputs-change.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/domain/amplify-toolkit.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/domain/context.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/context-manager.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/index.js[0m
                                 [0m- /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/bin/amplify[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:128:30[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at initEnv (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:128:30)[0m
2021-11-26T03:23:44.444Z [ERROR]: !!! Build failed
2021-11-26T03:23:44.444Z [ERROR]: !!! Non-Zero Exit Code detected

```

All of this is happening after upgrading amplify CLI to the latest 7.5.2.

Can you please advise?

### Expected behavior

The expected result should be a successful pull from the backend to my local machine.

### Reproduction steps

1. Amplify pull
2. Or deploy changes out to Git and have Amplify Console pull the changes. 
3. The same error applies on the latest 7.5.2 version of the amplify CLI.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by PeteDuncanson** [comment]
I was getting this or something similar last week. Fixed it by running a Amplify pull using the command listed in Amplify UI under my environment. Then checking in what changes and git pushing that. Give that a whirl.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/1674590/143572473-cb26861c-6093-4570-a9bb-36279709203e.png">

**Comment by kishan2110** [comment]
@PeteDuncanson I tried this one also but getting same error
<img width="1134" alt="Screenshot 2021-11-26 at 5 51 49 PM" src="https://user-images.githubusercontent.com/35519654/143581003-6a3a1b76-832c-4dd0-bad9-c03896fc0239.png">

**Comment by josefaidt** [comment]
Hey @georgeleeventures :wave: thanks for raising this! A few follow-up questions:

- what CLI version was used before upgrading?
- do you also experience this issue with more recent versions of Node.js? (14 or 16)
- are there any customizations applied to your app's buildspec? (`amplify.yml`)

**Comment by georgeleeventures** [comment]
@josefaidt 
what CLI version was used before upgrading?
> I think it was 7.4.4? I don't remember unfortunately. I update the CLI frequently.
do you also experience this issue with more recent versions of Node.js? (14 or 16)
> I just swapped to node.js v16.13 and still get the same error
are there any customizations applied to your app's buildspec? (amplify.yml)
> No, i don't believe so. I have never edited that.

**Comment by cjihrig** [comment]
@kishan2110 are you using the packaged version of the CLI (typically installed via curl)?

I ask because the message accompanying your stack trace implies that the import path is not handled during the packaging process. Looking at `amplify-category-api/src/index.ts`, there are a few dynamic imports like [this](https://github.com/aws-amplify/amplify-cli/blob/acfa82c9b275df0a7347ae0700a919dd8c03a4de/packages/amplify-category-api/src/index.ts#L56-L58) which access the problematic path.

**Comment by kishan2110** [comment]
@cjihrig  yes i am using the packaged version of the CLI

**Comment by georgeleeventures** [comment]
Could someone please help? I can't do any deployments or work on this at all when it is entirely broken and I have no visibility as to why - only because the AWS CLI was updated.

**Comment by aazhou1** [comment]
I am having this same issue. The amplify build after a gift push fails due to failure to pull due to this new amplify cli verison.

**Comment by kishan2110** [comment]
@cjihrig  thank you.
I clone the project amplify-cli and setup dev with the changes you mention  its working now

**Comment by cjihrig** [comment]
Thanks for verifying @kishan2110. I'll link the PR to this issue so that it auto closes when the PR is merged.

**Comment by georgeleeventures** [comment]
@cjihrig For me to get this working again, I need to setup the amplify cli directly from git? How can i get this working again?

**Comment by cjihrig** [comment]
@georgeleeventures just until the next release of the CLI is available. There are instructions for building the CLI locally [here](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md). Alternatively, you can downgrade to an older version of the CLI until the next release is available.

**Comment by aazhou1** [comment]
The issue for me is that the error is occurring when amplify is building the frontend client from Github after a code merge. Will building the CLI locally from git help to resolve that issue?

**Comment by georgeleeventures** [comment]
@aazhou1 I think what @cjihrig is saying is, for now, we can build from github repo to run it locally if we have to keep building. But we will have to wait until the new release of the CLI in order for builds to work triggered on the Amplify console. Correct me if I am wrong @cjihrig ?

**Comment by aazhou1** [comment]
well when will that new release be out? Is there a sev2 for that?
