### ISSUE TITLE
amplify cli tool takes 30 sec to startup on every command

### ISSUE THREAD

**Issue by massi-ang** [aws-amplify/amplify-cli#9099]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

17.1.0

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac OS Big Sur

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

The `amplify` command takes about 30 sec from pressing enter to displaying some text in the terminal, even with `amplify help` or `amplify version`.

### Expected behavior

Help and version should be instantaneous (< 1sec)

Other commands might vary, but would not expect anything >5 sec

### Reproduction steps

run `amplify help` or `amplify version`
after ~30 sec the help / version are printed on screen

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2021-11-26T10:48:10.016Z|info : amplify help core  
2021-11-26T10:55:47.974Z|info : amplify version core  
```

</details>

**Comment by PeteDuncanson** [comment]
I've had a similar grumbles of late. Bug bear for me is why does a simple version check take an age to do? https://github.com/aws-amplify/amplify-cli/issues/6751

**Comment by TeemuViikeri** [comment]
> I've had a similar grumbles of late. Bug bear for me is why does a simple version check take an age to do? #6751

Same here also. It's pretty frustrating to wait for these simple commands for so long.

**Comment by juniarz** [comment]
+ 1

**Comment by litwicki** [comment]
Hey folks, we're having trouble reproducing this. Can you provide some additional information about your workstations if possible? OS, chipset (M1, M1 Max/Pro, Intel, etc) and such helps us isolate the issue much quicker. Thanks!

**Comment by juniarz** [comment]
> Hey folks, we're having trouble reproducing this. Can you provide some additional information about your workstations if possible? OS, chipset (M1, M1 Max/Pro, Intel, etc) and such helps us isolate the issue much quicker. Thanks!

Hi, I am using a AWS EC2 t2.large instance with enough storage space

**Comment by massi-ang** [comment]
I am running the CLI on a Mac Book Pro 16" 2.6 Ghz 6-Cores i7 16GB ram 512 GB SSD
Running `amplify version` in an empty folder
Node and NPM installed via Volta.

Is there any way to have tracing/debug logs to see where the code is spending time?

**Comment by ammarkarachi** [comment]
We have released a new version with some improvements. Can you let us know if you are experiencing slowness after the latest?

**Comment by massi-ang** [comment]
This is better, getting ~5sec for `amplify help` or `amplify version`, but this is still feels slow for a simple version print or help dump. 

When installing amplify-cli I get these warnings. Could be this the reason for the slowness?

```
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by stam** [comment]
I have the same issue:
```
➜  ~ time amplify version
7.6.3
amplify version  6.70s user 1.59s system 88% cpu 9.342 total
```
```
➜  ~ time amplify version
7.6.3
amplify version  6.40s user 1.91s system 74% cpu 11.196 total
➜  ~
```

Specs: Node v12.22, and the same macbook as @massi-ang 
<img width="494" alt="Screenshot 2021-12-10 at 13 23 50" src="https://user-images.githubusercontent.com/12035356/145573658-185846b9-8519-4a18-8805-8330ef5a5da5.png">

**Comment by Straubulous** [comment]
The original issue of 30 seconds is addressed. Please open a new issue for additional perf improvements.
