### ISSUE TITLE
'Unauthorized on [_version]' exception on Mutations

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#9101]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.6.1

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I am getting `Unauthorized on [_version]` exceptions on update Mutations.

I created a fresh project to test out the new Amplify release 7.5.2. Used this graphQL model:

```
type Test
  @model
  @auth(rules: [
    { provider: iam, allow: private },
    { provider: userPools, allow: private, operations: [read, update] }
  ])
{
  id: ID!

  writeable: String

  readOnly: String
    @auth(rules: [
      { provider: iam, allow: private },
      { provider: userPools, allow: private, operations: [read] }
    ])

  hidden: String
    @auth(rules: [
      { provider: iam, allow: private },
    ])
}
```

Using AWS AppSync console, run this query::

```
mutation MyMutation {
  updateTest(input: {id: "1", writeable: "2", _version: 1}) {
    id
    writeable
  }
}
```

When I run this query as UserPool user, I get this exception:

```
{
  "data": {
    "updateTest": null
  },
  "errors": [
    {
      "path": [
        "updateTest"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Unauthorized on [_version]"
    }
  ]
}
```

If I omit _version from MyMutation inputs, then I get a different exception:

> Value for field '$[_version]' must be a number.

As a sanity check, I have verified that UserPool should have update access:

<img width="371" alt="Screen Shot 2021-11-26 at 9 18 40 PM" src="https://user-images.githubusercontent.com/2320090/143587118-1aced44c-aaae-4f4f-8dde-29d1524f2254.png">

### Expected behavior

Update mutation succeeds.

### Reproduction steps

1. `amplify init`
2. `amplify add auth`
3. `amplify add api`
    1. Set UserPool as primary auth and IAM as secondary auth.
5. use graphQL Test model as above
6. `amplify push`
7. create a test UserPool user in Cognito
8. add a sample entry into DynamoDB Test table (with id = 1)
9. open AWS AppSync console and run MyMutation as above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hi @skryshi, thank you for reporting this issue, I was able to reproduce it and we're looking into it.

**Comment by cjihrig** [comment]
Fixed in https://github.com/aws-amplify/amplify-cli/pull/9135
