### ISSUE TITLE
Command hooks warning shown locally with most `amplify` commands

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9103]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

pnpm add -g @aws-amplifuy/cli

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

v7.6.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

add, configure project, env, init, pull, push, status, update

### Describe the bug

Command hooks warning is shown on most amplify commands with the exception of `amplify version`
![image](https://user-images.githubusercontent.com/5033303/143604347-de6ac05c-cda6-40a2-baef-6cc00ee60833.png)
![image](https://user-images.githubusercontent.com/5033303/143604368-20e7f73b-7a56-4cd3-86fe-1cef5cb9f545.png)

for what it's worth I have some content in the `/opt/amazon` directory
```
> tree /opt/amazon
/opt/amazon
└── redshift
    ├── Amazon\ Redshift\ ODBC\ Driver\ License\ Agreement.pdf
    ├── Amazon\ Redshift\ ODBC\ Driver\ License\ Agreement.txt
    ├── ErrorMessages
    │   └── en-US
    │       ├── DSIamMessages.xml
    │       ├── DSMessages.xml
    │       ├── ODBCMessages.xml
    │       ├── PGOMessages.xml
    │       └── SQLEngineMessages.xml
    ├── Setup
    │   ├── odbc.ini
    │   └── odbcinst.ini
    ├── Tools
    │   └── DriverInstaller
    └── lib
        ├── AmazonRedshiftODBC.did
        ├── amazon.redshiftodbc.ini
        ├── libamazonredshiftodbc.dylib
        └── root.crt

6 directories, 14 files
```

### Expected behavior

Command hooks warning is only shown under the context of AdminUI

### Reproduction steps

run some Amplify command

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by edwardfoyle** [comment]
Command hooks uses the of `/opt/amazon` to enable/disable command hooks. This behavior has been appsec approved an will not be changed. To work around the issue you can move the contents of `/opt/amazon` to a different location.
