### ISSUE TITLE
No clear usage of @belongsTo

### ISSUE THREAD

**Issue by Lazarus404** [aws-amplify/amplify-cli#9109]
**Which Category is your question related to?**

GraphQL decorators

**Amplify CLI Version** 

7.4.5

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

When creating a relationship with `@hasMany`, a field is generated in the related model.  For instance, anding a `@hasMany` in `MyModel` to a field of type `[YourModel]` will add a `myModelYourModelsID` field in the `MyModel` schema.

The question is, if I already have a `myModelID` in `YourModel`, how do I link that?  Do I use `@belongsTo`?  Is there a different way to map it?

**Comment by cjihrig** [comment]
Yes, `@belongsTo` is the preferred way to make a relation bidirectional. You could also use a "has one" relation to create a bidirectional link, but `@belongsTo` includes some extra validation and is designed with this specific use case in mind, while `@hasOne` is not.

**Comment by Lazarus404** [comment]
I'm just not sure how to use it.  There's no direct reference that shows how.  I did see that if you have an `@connection`, then you can swap the `fields` value to point to the model you want to reference and change `connection` to `belongsTo`, so it looks like:

```
directoryID: ID! @belongsTo({fields: [Directory]})
```

but that fails to compile

**Comment by Lazarus404** [comment]
I see what I'm doing wrong.  It should be

```
directory: Directory @belongsTo
```
