### ISSUE TITLE
There was an error initializing your environment, file at path "<.......>/PostConfirmation.map.json" does not exist

### ISSUE THREAD

**Issue by BmjEarhart** [aws-amplify/amplify-cli#9112]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2220awwhxp5no

### Region

us-east-2

### Amplify Console feature

Not applicable

### Describe the bug

Prior to seeing this bug, I had run `amplify update auth` to configure a postConfirmation lambda trigger for our userPool. When doing so I was prompted: 

```
% amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

? A migration is needed to support latest updates on auth resources.
Recommended to try in a non-production environment first. Run "amplify env add" to create or clone an environment.
Learn more about this migration: https://docs.amplify.aws/cli/migration/override
Do you want to migrate auth resource "appname1234"? (Y/n) › 
```
Based on https://docs.amplify.aws/cli/migration/override/, I'm guessing this is because I updated amplify CLI above version 7 at some point since initially creating these environments. This seems relevant to the below error logs.

After this, when running `amplify init` and choosing an existing environment, I see the following error:

```
 % amplify init

Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: development
Using default provider  awscloudformation
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/PostConfirmation.map.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at AmplifyToolkit.getTriggerMetadata [as _getTriggerMetadata] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:404:85)
    at AmplifyToolkit.getTriggerEnvInputs [as _getTriggerEnvInputs] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/trigger-flow.ts:489:36)
    at initTriggerEnvs (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:438:43)
    at updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:384:25)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:132:49
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The result of this is that `amplify status` does successfully realize that I tried to init the new environment, and will compare the local resources/functions to 'development' environment, but the locally running front end is still pointing to the same env from before running `init`.

note, running `amplify pull` at this point seems to resolve the immediate issue, until next time you run `amplify init`. 

### Expected behavior

Expected result of this command is

```amplify init    
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: development
Using default provider  awscloudformation
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything
```

After which the local environment is pointing to the 'development' backend

### Reproduction steps

Prereq - a development and prod environment. Possibly relevant that they have a postConfirmation auth lambda trigger configured, and are initially created with CLI version < 7 (https://docs.amplify.aws/cli/migration/override/)

1) On development, with amplify CLI version ≥ 7, run `amplify auth update`
2) When prompted with `Do you want to migrate auth resource "appname1234"? (Y/n) ›`, press y to accept.
3) Once complete, finish navigating through `amplify auth update` -> `Walkthrough all the auth configurations`. (No changes were intentionally made to any of these configurations, not sure this is strictly necessary)
4) run `amplify init prod`. This should result in the above error message.

### Additional information

amplify cli version:  7.5.2

**Comment by fhnstephen** [comment]
Similar here. We have a project created in amplify-cli@6, and after upgraded to v7, we can't run `amplify init` anymore, showing a similar error, but for another auth trigger.
Wondering if there is any documentation talking about this breaking changes.

**Comment by theakashanand** [comment]
Any updates on this? It's so annoying when amplify keeps pushing updates every other week, with each update having more bugs than the last. We aren't able to create new environments for our application anymore with amplify v7.5.3. Running `amplify init` throws the error:

> File at path: '.../PostConfirmation/PostConfirmation.map.json' does not exist

**Comment by dylan-westbury** [comment]
1. `amplify init`
2. enter new name for env e.g. (prod)

There was an error initializing your environment.
Error: File at path: '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/../../../../amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/PostConfirmation.map.json' does not exist

**Comment by dylan-westbury** [comment]
Confirming this is resolved with latest cli version
