### ISSUE TITLE
Can't get TypeScript for Lambdas working in new environment

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9113]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.5.2

### What operating system are you using?

Windows

### Amplify Categories

function

### Amplify Commands

configure project, env, push

### Describe the bug

Trying to spin up a new environment from an existing setup (we already have dev and live, I'm creating a staging) and now getting some new errors with our Lambdas and I'm not sure why as these haven't appeared on the other two environments.

We are using TypeScript for our Lambdas and build that into JS by having a command in our package.json for each Lambda.

I've gone through what its complaining about and tried installing TypeScript globally in the pre-build step, then install the missing types its complaining about but still it can't find what its wanting and now I'm at a loss. Any pointers what I've doing wrong?

I'd follow the instructions on how to do this but as I've already got an issue open explaining they are incorrect (https://github.com/aws-amplify/amplify-cli/issues/8668) I feel I'm kind of on my own here :|

 

### Expected behavior

I can't see why this would have worked on the dev/live environments if it is failing on this new one. Confused as to why its an issue now?

With Typescript install globally via the build settings and a local tsconfig file to the Lambda I can't see why it wouldn't work?

### Reproduction steps

Tricky as ever as this is all part of a huge project, you might be able to trim these steps down some.

Have an existing environment with a Lambda called "peteTest" in it with the files included below.

Add a line to your scripts section of you project root package.json:

"amplify:peteTest": "cd amplify/backend/function/peteTest && tsc -p ./tsconfig.json"

In your build settings add this pre-build script so that TypeScript is install globally: 

backend:
  phases:
    build:
      commands:
        - npm i -g typescript

Create a new branch. Connect your branch in the CI. Trigger the CI to build your branch. It should fail claiming to not find types.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

package.json in the /src folder of your Lambda (/amplify/backend/functions/peteTest/src):
```
{
  "name": "peteTest",
  "version": "2.0.0",
  "description": "Lambda function generated by Amplify",
  "main": "index.js",
  "license": "Apache-2.0",
  "dependencies": {
    "axios": "^0.21.1",
    "graphql": "^15.5.0",
    "graphql-tag": "^2.11.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.72",
    "@types/aws-sdk": "^2.7.0",
    "@types/node": "^16.11.10",
    "typescript": "^4.1.5"
  }
}
```

tsconfig.json in the /src folder of our Lambda (/amplify/backend/functions/peteTest/src
)

```
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "outDir": "./src",
    "baseUrl": "./",
    "rootDir": "./src",
    "paths": {
      "src": ["./src"]
    },
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": false,
    "declaration": false,
    "removeComments": true,
    "noImplicitReturns": true,
    "noUnusedLocals": false,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["./src"],
  "exclude": ["src/node_modules", "src/**/*.spec.ts"]
}
```

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1674590/143691118-bc98cea9-d22d-4cbf-9d17-9f8db0afd8be.png">

**Comment by sachscode** [comment]
Hi @PeteDuncanson 
I am following the steps to reproduce this issue and root cause the problem.Could you please share the version of typescript in your environment ? Was this recently updated too ?

**Comment by PeteDuncanson** [comment]
Hey @sachscode, thanks for taking a look. This one has been a head scratcher!

Its says in my package.json in the root of my app that I'm running `"typescript": "^4.2.3"`

I see that 4.5 is available now, I wonder if that is the version the new environment is installing. But don't the environments load up fresh each deploy? If so why would this one fail but the dev/live ones work (assuming that they do and its not just a quirk thats literally happened since our last deploy to dev/live and me starting up staging?

In the meantime I'll update locally too and see if that causes the same issues.

**Comment by sachscode** [comment]
Hi @PeteDuncanson , 
I am thinking probably something in the way the types are resolved from tsconfig.json might have changed causing this problem. Could you please confirm if you have a "types" section in your tsconfig.json.

**Comment by PeteDuncanson** [comment]
I don't now. I tried adding `types:["node"]` and `"types:["node","node_modules/@types]` to the config (thank you Stackover flow) but to no effect. Any pointers?

**Comment by sachscode** [comment]
one way to check is, in your local environment, in the src/dist folder you should see the Zip file which is being uploaded to lambda. Could you please check if the files with types are being included.

**Comment by sachscode** [comment]
@PeteDuncanson 
Could you please share the snippet of code, where you are importing aws-sdk  ? 
Do you use:
import * as AWS from 'aws-sdk';

**Comment by PeteDuncanson** [comment]
@sachscode 

We are using:

`import AWS, { CognitoIdentityServiceProvider } from "aws-sdk";`

I've yarn add'ed the aws-sdk and pushed up via git to see what the CI thinks of it, will report back

I'm not sure where you mean I should look for the src/dist folder, no such folder exists in the root or in the lambda folder that I can see? I can't `amplify push` at the minute as staging doesn't really exist to push to from amplify locally

**Comment by sachscode** [comment]
@PeteDuncanson  
1. To fix the aws-sdk types error, could you please try changing the import statement to 
import * as AWS from "aws-sdk"
let cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();

2. The Dist folder is created locally after the amplify push operation.  
amplify/#current-cloud-backend/function/peteTest/dist
amplify/backend/function/peteTest/dist

**Comment by PeteDuncanson** [comment]
Changed the import and git pushed, its building now.

There is no `dist` folder in either of the locations you mention in my local #current-cloud-backend build?

**Comment by sachscode** [comment]
>>>Changed the import and git pushed, its building now.
Does this mean the error is no longer seen ? or are we still in the process of validating it?

>>>There is no dist folder in either of the locations you mention in my local #current-cloud-backend build?
Yes, this is in the local environment.

**Comment by PeteDuncanson** [comment]
Seeing this again on a new environment, now using CLI version 7.6.11

Help me @sachscode you are my only hope...

**Comment by sachscode** [comment]
Hi @PeteDuncanson 
looking into this.

**Comment by PeteDuncanson** [comment]
@sachscode yes this error in in the CI. I've done a full pull into a fresh folder, what now? Make a change and do a push?

**Comment by sachscode** [comment]
Yes @PeteDuncanson , can we try doing that , this will allow us to eliminate any Amplify state related problems.

**Comment by PeteDuncanson** [comment]
@sachscode that seems to have unstuck whatever it is! 

So to sum up if it happens again (hello future me!):

* Create new folder locally
* Git checkout your solution into there so its clean
* Pulled the target environment from Amplify using the command listed under the "hosting environment" in the Amplify console.
* Git commit anything its pulled down
* Git push
* Await the CI to complete a build (again check the Amplify console for this)

Now I have green lights :)
