### ISSUE TITLE
Error when pushing with amplify

### ISSUE THREAD

**Issue by zandvakiliramin** [aws-amplify/amplify-cli#9114]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

sudo npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.5.3

### What operating system are you using?

Mac

### Amplify Categories

function, api

### Amplify Commands

add, push

### Describe the bug

I am developing an expo app, with Amazon AWS as the backend.
I have 2 separate issues:

 1. I have changed my schema, and now when I try  ```amplify push``` I get this error:
🛑 An error occurred during the push operation: Unknown directive "key".

Unknown directive "key".

Unknown directive "connection".

2. I have added a function (the default hello-world lambda function), and now when I try to do ```npm start``` I get the following error:

jest-haste-map: Haste module naming collision: testHelloWorld
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/amplify/#current-cloud-backend/function/testHelloWorld/src/package.json
    * <rootDir>/amplify/backend/function/testHelloWorld/src/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/ramin/Code/Playground/ta-bot-mvp/node_modules/jest-haste-map/build/index.js:543:17)
    at workerReply (/Users/ramin/Code/Playground/ta-bot-mvp/node_modules/jest-haste-map/build/index.js:614:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 36)
    at /Users/ramin/Code/Playground/ta-bot-mvp/node_modules/jest-haste-map/build/index.js:426:22 {
  mockPath1: 'amplify/#current-cloud-backend/function/testHelloWorld/src/package.json',
  mockPath2: 'amplify/backend/function/testHelloWorld/src/package.json'

### Expected behavior

I expect it to change the schema on the cloud and add the functions

### Reproduction steps

1. npx create-react-app <app-name>
2. cd <app-name>
2. npm add -g @aws-amplify/cli
3. amplify configure
4. amplify init
5. install the local Amplify dependencies.
```
npm install aws-amplify aws-amplify-react-native @react-native-community/netinfo @react-native-async-storage/async-storage
```
6. amplify function add
7. amplify push
8. amplify api add
9. I change the default schema 
10. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Message @model @auth(rules: [{allow: public}]) @key(name: "byUser", fields: ["userID"]) @key(name: "byChatRoom", fields: ["chatroomID"]) {
  id: ID!
  content: String!
  userID: ID
  chatroomID: ID
}

type ChatRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  newMessages: Int
  LastMessage: Message @connection
  Messages: [Message] @connection(keyName: "byChatRoom", fields: ["id"])
  ChatRoomUsers: [ChatRoomUser] @connection(keyName: "byChatRoom", fields: ["id"])
}

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  imageUri: String
  status: String
  condition: String!
  Messages: [Message] @connection(keyName: "byUser", fields: ["id"])
  chatrooms: [ChatRoomUser] @connection(keyName: "byUser", fields: ["id"])
}

type ChatRoomUser @model(queries: null) @key(name: "byChatRoom", fields: ["chatroomID", "userID"]) @key(name: "byUser", fields: ["userID", "chatroomID"]) @auth(rules: [{allow: public}, {allow: public}]) {
  id: ID!
  chatroomID: ID!
  userID: ID!
  chatroom: ChatRoom! @connection(fields: ["chatroomID"])
  user: User! @connection(fields: ["userID"])
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
type Message
  @model
  @auth(rules: [{ allow: public }])
  @key(name: "byUser", fields: ["userID"])
  @key(name: "byChatRoom", fields: ["chatroomID"]) {
  id: ID!
  content: String!
  userID: ID
  chatroomID: ID
}

type ChatRoom @model @auth(rules: [{ allow: public }]) {
  id: ID!
  newMessages: Int
  LastMessage: Message @connection
  Messages: [Message] @connection(keyName: "byChatRoom", fields: ["id"])
  ChatRoomUsers: [ChatRoomUser]
    @connection(keyName: "byChatRoom", fields: ["id"])
}

type User @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String!
  imageUri: String
  status: String
  Messages: [Message] @connection(keyName: "byUser", fields: ["id"])
  chatrooms: [ChatRoomUser] @connection(keyName: "byUser", fields: ["id"])
}

type ChatRoomUser
  @model(queries: null)
  @key(name: "byChatRoom", fields: ["chatroomID", "userID"])
  @key(name: "byUser", fields: ["userID", "chatroomID"])
  @auth(rules: [{ allow: public }, { allow: public }]) {
  id: ID!
  chatroomID: ID!
  userID: ID!
  chatroom: ChatRoom! @connection(fields: ["chatroomID"])
  user: User! @connection(fields: ["userID"])
}

```

</details>

### Additional information

I have already looked into the previous issues, the solutions that I found don't work for me:
1. Someone had recommended changing features.graphqltransformer.transforversion to 1 in cli.json. But it automatically changes back to 2 when I do ```amplify push```.

2. For the functions the solution that worked was to add the following code to the metro.config.js file at the root. This works, However, I don't know if it is ok to do this or not, since I am manually adding something. 

```javascript
module.exports = {
  resolver: {
    blacklistRE: /#current-cloud-backend\/.*/
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by cjihrig** [comment]
> Someone had recommended changing features.graphqltransformer.transforversion to 1 in cli.json. But it automatically changes back to 2 when I do amplify push.

If you want to push a v1 compatible schema, please make sure that `transformerversion` is set to `1` **and**  the `useexperimentalpipelinedtransformer` feature flag is set to `false`. This should prevent the automatic change that you're observing.
