### ISSUE TITLE
getting DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified when deleting item in datastore

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-cli#9115]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.16.1

### Amplify CLI Version

7.5.3

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

Im not sure if this
https://github.com/aws-amplify/amplify-js/issues/9285
is a library or a cli bug
We are using the "old" gql transform. we are evaluating the migration

### Expected behavior

Item should be deleted with no issue.

### Reproduction steps

1. create an amplify app
2. add datastore
3. create item
4. query item
5. delete item

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
I think this is more likely to be a library issue. I'm going to close this since you've opened https://github.com/aws-amplify/amplify-js/issues/9285. If it is determined to be a CLI issue, that issue can be transferred here.
