### ISSUE TITLE
Where the heck is simply the full detailed list of CLI commands?

### ISSUE THREAD

**Issue by smhk** [aws-amplify/amplify-cli#9119]
https://github.com/aws-amplify/amplify-cli#commands-summary

There's a short list there of major commands.

However the "init" command for example has many, many critical subcommands.

Where the heck is simply the documentation of all the CLI commands?

Note that "% amplify init help" and "%amplify help init" do nothing.

Thanks - anyone who knows!

**Comment by edwardfoyle** [comment]
The docs here describe most of the command and flags that the CLI accepts: https://docs.amplify.aws/cli/usage/headless/
