### ISSUE TITLE
v2 transformer doesn't respect "StackMapping" in transformer.conf.json

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-cli#9123]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.5.3

### What operating system are you using?

linux

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

I'm trying to migrate my existing environment to the v2 transformer. First thing I did was to perform the migration and that successfully executed.

```
amplify migrate api
```

Then I tried to see if the newly migrated schema would compile

```
amplify api gql-compile
```
But this came back with the following error
```
🛑 Removing a model from the GraphQL schema will also remove the underlying DynamoDB table.
This update will remove table(s) [ConnectionStack2]
ALL EXISTING DATA IN THESE TABLES WILL BE LOST!
If this is intended, rerun the command with '--allow-destructive-graphql-schema-updates'.
```

The issue here is that **_I do not have a model/table called "ConnectionStack2 in my database_**. To get around the limitation of 500 resources in a single stack I had StackMapping etnreis in the transform.conf.json file similar to this.

```
    "StackMapping": {
        "AssetequipmentReferenceResolver": "ConnectionStack2",
        "AssetcrowdResultsResolver": "ConnectionStack2"
   }
```

I removed this StackMapping from the transform.conf.json file and compiled with --allow-destructive-graphql-schema-updates to see if I could get it to compile but got the following error. There were 1,209 resources generated in the ConnectionStack.json file. I tried to 450 resources in transform.conf.json in ConnectionStack2 and 450 resources in transform.conf.json in ConnectionStack3 - but still got the error below.

```
InvalidMigrationError: The ConnectionStack.json stack defines more than 500 resources.
```

### Expected behavior

Successful compilation

### Reproduction steps

Described above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sacrampton** [comment]
@edwardfoyle - is there any work around for this? Or do I have to just wait for a fix before I can move to v2?

**Comment by edwardfoyle** [comment]
@sacrampton Unfortunately I don't think there's any simple workaround. The above PR should fix this once released.

**Comment by sacrampton** [comment]
Hi @edwardfoyle - I'm struggling to see when this fix will be available - seems there is a lot of activity, but I can't see where it has been released

**Comment by sacrampton** [comment]
Hi @edwardfoyle - I need to update my api for a separate issue, but it is saying that amplify update api requires the schema to be migrated. But I can't migrate the schema because of the stack mapping bug. So I thought I'd downgrade amplify to 6.3.1 so I used the "npm i @aws-amplify/cli@6.3.1" command in aws linux (Cloud 9) - it appeared to install successfully, but when I run "amplify -v" it return 7.6.7

How do I successfully downgrade to 6.3.1 whilst waiting for fixes to the 7.x

**Comment by garciajg** [comment]
@sacrampton  You'd want to add the `-g` flag right? So do `npm i -g @aws-amplify/cli@6.3.1`
