### ISSUE TITLE
Cannot build graphql v2 on amplify CI/CD

### ISSUE THREAD

**Issue by wattanakorn495** [aws-amplify/amplify-cli#9125]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

latest and 7.5.4

### What operating system are you using?

amazon linux 2 image

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I cannot build graphql v2 on amplify CI/CD
I have tried both lasted and v7.5.4

`
[0mError: Unknown directive "hasMany".[0m
                                 [0mUnknown directive "manyToMany".[0m
                                 [0mUnknown directive "index".[0m
                                 [0mUnknown directive "manyToMany".[0m
`

![image](https://user-images.githubusercontent.com/41609635/143803989-7fd23c4a-e73d-43f7-8ad9-b994e783b2a2.png)

### Expected behavior

it should work as same as local cli

### Reproduction steps

1. create graphql api
2. create schema with v2 directive
3. configure amplify ci/cd
4. push your code 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Straubulous** [comment]
@wattanakorn495, the symptoms indicate CLI is running the v1 transformer. Have you tried `amplify migrate api`? to inform CLI to now use v2. 

Are you working with a project which existed prior to CLI 7.5? By default, CLI uses GQL trans v1 on existing projects and v2 on new projects.

**Comment by cjihrig** [comment]
@wattanakorn495 in your project's `cli.json` file, please make sure that the `useexperimentalpipelinedtransformer` feature flag is set to `true`, and the `transformerversion` feature flag is set to `2`.

**Comment by wattanakorn495** [comment]
I tried again and it works.

> @wattanakorn495 in your project's `cli.json` file, please make sure that the `useexperimentalpipelinedtransformer` feature flag is set to `true`, and the `transformerversion` feature flag is set to `2`.

This is my cli.json
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "project": {
      "overrides": true
    }
  }
}
```
