### ISSUE TITLE
'amplify status' continues to show 'update' even after a successful 'amplify publish'

### ISSUE THREAD

**Issue by leantide** [aws-amplify/amplify-cli#913]
**Describe the bug**
'amplify status' continues to show 'update' even after a successful 'amplify push' or a successful 'amplify publish'

**To Reproduce**
1. run 'amplify publish'
2. run 'amplify status'

**Expected behavior**
All categories have an operation value of 'No Change' 

**Observed behavior**
2 of my 24 categories (which are both Lambda functions) have an operation value of 'Update'

$ amplify status
Current Environment: dev

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Function | settings        | Update    | awscloudformation |
| Function | nodes           | Update    | awscloudformation |
| Auth     | cognito6e1470c4 | No Change | awscloudformation |
| Hosting  | S3AndCloudFront | No Change | awscloudformation |
| Storage  | authorization   | No Change | awscloudformation |
| Storage  | users           | No Change | awscloudformation |
| Storage  | settings        | No Change | awscloudformation |
| Storage  | membership      | No Change | awscloudformation |
| Storage  | details         | No Change | awscloudformation |
| Storage  | counters        | No Change | awscloudformation |
| Storage  | products        | No Change | awscloudformation |
| Storage  | releases        | No Change | awscloudformation |
| Storage  | features        | No Change | awscloudformation |
| Storage  | items           | No Change | awscloudformation |
| Function | membership      | No Change | awscloudformation |
| Function | details         | No Change | awscloudformation |
| Function | counters        | No Change | awscloudformation |
| Function | products        | No Change | awscloudformation |
| Api      | settings        | No Change | awscloudformation |
| Api      | membership      | No Change | awscloudformation |
| Api      | details         | No Change | awscloudformation |
| Api      | counters        | No Change | awscloudformation |
| Api      | products        | No Change | awscloudformation |
| Api      | nodes           | No Change | awscloudformation |

**Additional context**
Using multi-env amplify-cli: @aws-amplify/cli@0.2.1

**Comment by kaustavghosh06** [comment]
@leantide We've fixed this behavior in the latest version of the CLI. Also, please note that we have moved the multienv features in the main CLI, so you could use the main CLI and install it using `npm install -g @aws-amplify/cli`

**Comment by leantide** [comment]
Wow, fast response. Thank you.
