### ISSUE TITLE
Unable to migrate to new GraphQL Transformer

### ISSUE THREAD

**Issue by localsecurity-emily** [aws-amplify/amplify-cli#9130]
**Describe the bug**
I am trying to migrate my GraphQL Transformer from v1 to v2 using the guide [here](GraphQL Transformer v1 to v2 migration).

**To Reproduce**
- Upgraded from `@aws-amplify/cli` v7.3.6 to v7.5.2
- Ran `amplify migrate api`
- Got message: `You are using the deprecated parameterization of @connection which cannot be automatically migrated.`
- I changed all of my `@connection` to `@hasOne` or `@hasMany` (the only relationships relevant to my schema) and got a series of 
```
Unknown directive "hasOne".

Unknown directive "hasMany".

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "hasMany".
```

**Comment by cjihrig** [comment]
@localsecurity-emily in your project's `cli.json` file, please make sure that the `useexperimentalpipelinedtransformer` feature flag is set to `true`, and the `transformerversion` feature flag is set to `2`.

**Comment by localsecurity-emily** [comment]
@cjihrig I can confirm that I have both of those flags set correctly

**Comment by josefaidt** [comment]
Hey @localsecurity-emily :wave: are you seeing those errors on push or on another attempt of `amplify migrate api`? Once the schema has been manually migrated and the feature flags are set as described in @cjihrig 's comment you should be good to push the changes
