### ISSUE TITLE
@model(subscriptions: null) broken. Error in graphql-auth-transformer: Cannot read property 'level' of null

### ISSUE THREAD

**Issue by BeaveArony** [aws-amplify/amplify-cli#9132]
Having a schema

```graphql
type Todo @model(subscriptions: null) {
  id: ID!
}
```

and running `amplify api gql-transform` will give 

```
Cannot read property 'level' of null
```

in `@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts`.

The code expects there to be an object with a level property.

Using amplify v7.5.4

**Comment by renebrandel** [comment]
hi @BeaveArony - just confirming, did you mean to type `amplify api gql-compile`?

**Comment by renebrandel** [comment]
I couldn't reproduce this issue on my end.

**Comment by BeaveArony** [comment]
> I couldn't reproduce this issue on my end. Is that the full schema?

This is not the full schema, as this would be too long, but I guess it's the `@auth` directive as the error comes from `graphql-auth-transformer.js`. Here is one type:

```graphql
type Profile
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner, ownerField: "id", operations: [create, update] }
      { allow: groups, groups: ["SuperAdmin"] }
      { allow: groups, groups: ["Admin"], operations: [create, update, read] }
      { allow: private, operations: [read] }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  email: String!
  phone: String
  firstname: String
  lastname: String
  roleDescription: String
  joinedAt: AWSDateTime
  lastInvitedAt: AWSDateTime
  lastAuthenticatedAt: AWSDateTime
  cognitoUserStatus: CognitoUserStatus
  lastSelectedTenantId: String
  photoUrl: String
  tenants: [TenantMembership!] @connection(keyName: "byProfile", fields: ["id"])
}
```

When I change `@model(subscriptions: null)` to `@model(subscriptions: { level: off }) I can compile using the transformer v2.

Note: A fix for me was opening `graphql-auth-transformer.js` and changing two places from this:
```js
subscriptions.level
``` 
to this:
```js
subscriptions?.level
```

**Comment by parvusville** [comment]
Getting this as well when running amplify api override, after migrating the API.
