### ISSUE TITLE
V2 GraphQL tranforms doesn't allow @auth with @function for a Mutation field.

### ISSUE THREAD

**Issue by wizage** [aws-amplify/amplify-cli#9133]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.5.4

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

add, push

### Describe the bug

Amplify @auth directive doesn't add anything inside the pipeline resolver:

The entire Schema is below. This is for the Mutation `CreateStreamKey`

```
## [Start] Field Authorization Steps. **
#set( $isAuthorized = false )
#if( $util.authType() == "User Pool Authorization" )

#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Field Authorization Steps. **
```

### Expected behavior

Schema would generate a resolver that would contain a proper Auth solution for Mutations. This worked on Legacy.

### Reproduction steps

1. `amplify init`
2. `amplify add api`
3. Change your schema to below
4. `amplify push`
5. Go to the console and observe that the Resolver is empty (also can see it in the build folder)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Channel @model @auth(rules: [{allow: owner}, {allow: private, operations: [read]}]) {
  id: ID! @primaryKey
  title: String!
  description: String!
  streamKey: String @auth(rules: [{allow: owner}])
  channelArn: String @auth(rules: [{allow: owner}]) @index(name: "channelsByArn", queryField: "channelByArn")
  streamURL: String
  streamKeyArn: String @auth(rules: [{allow: owner}])
  ingestEndpoint: String @auth(rules: [{allow: owner}])
}

type Mutation {
  createStreamKey(id: ID): Channel @auth(rules: [{allow: owner}]) @function(name: "channelManager-${env}") 
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SwaySway** [comment]
`@auth` on a `@function` only supports static groups, iam, and apiKey. Owner and dynamic groups are currently mapped to the model generated operations since those dynamic fields are handled directly in the resolvers.

A potential alternative here is to create a lambda function which handles the owner auth as well
Allow a private user to enter the mutation but delegate the auth logic to the function ex. 
   ```graphql
   type Mutation {
     createStreamKey(id: ID): Channel
     @auth(rules: [{ allow: private }]) 
     @function(name: "myOwnerAuth-${env}")
     @function(name: "channelManager-${env}")
   }
   ```

**Comment by wizage** [comment]
Hey @SwaySway 

Thanks for the answer but that is not a really a solid answer. So you are saying that there is right now no correct way to do `@auth` for fields on anything that isn't in a `@model`. IMO worst case I would rather at least have a directive to query for the Channel and then check the owner rather then have another Lambda. Also if this is the case, why does GraphQL compile allow this pattern then? Shouldn't the compile fail, if this is not a valid solution?

Further more, why would you separate the functions for Auth and the other datasource? That would double my cost as a user due to invokes would be doubled in the worst case scenario.

**Comment by marcvberg** [comment]
Hi @wizage,

We have limited support for customers once they get into the space of custom resolvers, we don't want to deny the functionality as an invalid solution because there are still valid use cases for it. One option you could take is this:

```
type Channel @model @auth(rules: [{allow: owner}, {allow: private, operations: [read]}]) {
  id: ID! @primaryKey
  title: String!
  description: String!
  streamKey: String @auth(rules: [{allow: owner}]) @function(name: "channelManager-${env}")
  channelArn: String @auth(rules: [{allow: owner}]) @index(name: "channelsByArn", queryField: "channelByArn")
  streamURL: String
  streamKeyArn: String @auth(rules: [{allow: owner}])
  ingestEndpoint: String @auth(rules: [{allow: owner}])
}
```

If you put a lambda resolver on the `streamKey` field you can take advantage of the field level auth, and you can write the lambda resolver to only take action on a create request, allowing other requests to pass through untouched.

**Comment by marcvberg** [comment]
I will close this question as answered since it's been some time, feel free to reopen if necessary
