### ISSUE TITLE
Deploy custom authorization with AWS-Cognito using amplify-cli

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9134]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Deploying custom authorization to API-GATEWAY using Cognito-user pool.

**Amplify CLI Version** 
7.5.4
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
API GATEWAY, APP SYNC.

**Provide additional details e.g. code snippets**
I just want to know, is there any way to deploy custom authorization using amplify cli? Right now, I can't see any cli steps to add custom authorization to an API endpoint, by default it is AWS_IAM.
For eg: 
```
 amplify update api                                                   ✔ 
? Select from one of the below mentioned services: REST
Only one option for [Select the REST API you want to update:]. Selecting [restapi].
✔ What would you like to do? · Update path
? Select the path to edit /checkblog
✔ Provide a path (e.g., /book/{isbn}): · /checkblog
✔ Choose a Lambda source · Use a Lambda function already added in the current Amplify project
✔ Choose the Lambda function to invoke by this path · restapiCheckBlog
✔ Restrict API access? (Y/n) · yes
✔ Who should have access? · Authenticated users only
✔ What permissions do you want to grant to Authenticated users? · create, read, update, delete
✅ Successfully updated resource
```
I can create custom authorization from the API GATEWAY console, but the issue is, if I am pushing something from local, then it is deleting that custom authorizer and updates each API auth as AWS_IAM.

Also, there should be a way to assign authorization type to each API endpoint. 

BTW thanks, for such a great community.   I hope,  I am not missing something.

**Comment by SwaySway** [comment]
Hello @hackrx 
There is a feature request to support cognito in rest api, the comments in the linked feature request below also discuss some alternatives into how to add it manually as well. Closing this issue in favor of the duplicate
https://github.com/aws-amplify/amplify-cli/issues/3390

Should the linked issue not address your concern please comment below and we can re-open this issue.

**Comment by hackrx** [comment]
Hey @SwaySway, yes it refers to my issue, and I tried the proposed solution but I can't find cloud-formation-template.json file under my api folder. The steps to find the variables is unclear to me. Can you please provide any guide here? 
Thanks for the follow up.
