### ISSUE TITLE
After upgrading amplify-cli an amplify push with no changes breaks REST API permissions

### ISSUE THREAD

**Issue by dhardiker** [aws-amplify/amplify-cli#9137]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.5.4

### What operating system are you using?

Mac M1

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I've just upgraded to the latest version of amplify-cli and I noticed this on an amplify push:

```
DELETE_COMPLETE amplify-myweaver-amplify-sandbox-XXXXX-APIGatewayAuthStack-XXXXXXXXXXXX AWS::CloudFormation::Stack Mon Nov 29 2021 17:25:25 GMT+0000 (Greenwich Mean Time)
```

Ever since that happened my API calls to Lambda's behind the API Gateway have stopped working. I have had logging on for sometime. Before this happened when I called my Lambda it looked like this:

```
(4647e8f2-6d88-4519-a401-6be1180fd566) Extended Request Id: XXXXXXXXX
(4647e8f2-6d88-4519-a401-6be1180fd566) Verifying Usage Plan for request: 4647e8f2-6d88-4519-a401-6be1180fd566. API Key:  API Stage: XXXXXXXXX/sandbox
(4647e8f2-6d88-4519-a401-6be1180fd566) API Key  authorized because method 'OPTIONS /files/{proxy+}' does not require API Key. Request will not contribute to throttle or quota limits
(4647e8f2-6d88-4519-a401-6be1180fd566) Usage Plan check succeeded for API Key  and API Stage XXXXXXXXX/sandbox
(4647e8f2-6d88-4519-a401-6be1180fd566) Starting execution for request: 4647e8f2-6d88-4519-a401-6be1180fd566
(4647e8f2-6d88-4519-a401-6be1180fd566) HTTP Method: OPTIONS, Resource Path: /files/XXXXXXXXX-6a5b-4bf6-b621-XXXXXXXXX
(4647e8f2-6d88-4519-a401-6be1180fd566) Successfully completed execution
(4647e8f2-6d88-4519-a401-6be1180fd566) Method completed with status: 200
```

Since the update, it does this now:
```
(e60cbf60-4f6f-40d9-95b8-e462caa0eca3) Extended Request Id: XXXXXXXXX
(e60cbf60-4f6f-40d9-95b8-e462caa0eca3) The client is not authorized to perform this operation.
```

I brought this to the `#cli-help` channel on Discord (see [this message chain with Josef](https://discordapp.com/channels/705853757799399426/708077731711156284/914934239881998348)) where it was determined that the REST API had not been migrated to a newer form. These REST APIs are well over a year old and when I ran `amplify update api` to add a dummy `/temp` path it triggered a migration:

![](https://media.discordapp.net/attachments/708077731711156284/914971536912429066/Screenshot_2021-11-29_at_20.10.04.png)

After an `amplify push` everything now worked as expected.

### Expected behavior

A REST API migration was clearly needed, this should have been detected and happened automatically, or don't touch it. Simply upgrading the amplify-cli shouldn't have broken my existing legacy REST APIs.

### Reproduction steps

I'm not sure how to create the legacy structure as no changes to files in source control were needed, just an upgrade of the amplify-cli. I'm not sure what version of the cli I had before, because there's no tracking/auditing of that that I know of. It's probably about a month since I last upgraded the cli.

### Additional information

This issue has a user confirmed workaround, but could do with a better fix!

Keywords that might help others find this report and possible solution:
* REST API Gateway Lambda REST API Key 302 CORS permission denied
* CloudFormation APIGatewayAuthStack DELETE_COMPLETED
* amplify-cli upgrade auth api

Thanks!

**Comment by josefaidt** [comment]
Hey @dhardiker thanks for taking the time to file this and I'm glad we were able to connect on Discord, ultimately to recover the env, migrate the resource, and get you back up and running! Marking as a bug and linking the related PR 🙂
