### ISSUE TITLE
npm install -g awsmobile-cli throws following error. Can someone help me resolve this issue please

### ISSUE THREAD

**Issue by jk62** [aws-amplify/amplify-cli#9141]
(base) jaikishansharma@Jaikishans-MacBook-Air lpr-aws % npm install -g awsmobile-cli
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/awsmobile-cli
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/awsmobile-cli'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/awsmobile-cli'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/awsmobile-cli'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jaikishansharma/.npm/_logs/2021-11-30T02_14_58_471Z-debug.log
(base) jaikishansharma@Jaikishans-MacBook-Air lpr-aws %

**Comment by ammarkarachi** [comment]
@jk62 are you building a new backend? you can install the latest Amplify CLI using `npm i -g @aws-amplify/cli@latest`

**Comment by jk62** [comment]
Same error still persists. 


base) jaikishansharma@Jaikishans-MacBook-Air lpr-aws % npm i -g @aws-amplify/cli@latest
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/@aws-amplify
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@aws-amplify'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@aws-amplify'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/@aws-amplify'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jaikishansharma/.npm/_logs/2021-11-30T16_28_24_633Z-debug.log
(base) jaikishansharma@Jaikishans-MacBook-Air lpr-aws %

**Comment by josefaidt** [comment]
Hey @jk62 :wave: please refer to this [npm documentation page](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more information on how to resolve this EACCESS error when installing packages globally

**Comment by jk62** [comment]
Thanks for your advice bro but it got resolved with following command:
sudo npm install -g @aws-amplify/cli --unsafe-perm=true;
