### ISSUE TITLE
Known limitation: Real-time subscriptions are not supported when owner authorization is configured with a list of owners.

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#9143]
From the docs:

> **Known limitation:** Real-time subscriptions are not supported when owner authorization is configured with a list of owners.

What is the suggested work around this limitation?

#### My use case:

A Message type in a chat app. Two users have access to a message - sender and receiver. I am using iOS DataStore, so I want changes to the message to be pushed to both users. But because of the limitation, they will not be.

```
type Message
  @model
  @auth(rules: [
    { provider: userPools, allow: owner, ownerField: "owners", operations: [read, update] }
  ])
{
  owners: [String]
  text: String
}
```

**Comment by jk171505** [comment]
@skryshi looks like this is known limitation:
https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access

"Known limitation: Real-time subscriptions are not supported when owner authorization is configured with a list of owners."

**Comment by skryshi** [comment]
Whoever runs into this, this is an AppSync limitation. Subscriptions with parameters do a simple match, they cannot handle contains in an array functionality.

The suggested workaround is here:

https://stackoverflow.com/questions/64411293/is-it-possible-to-map-a-subscription-parameter-to-an-array-at-the-mutation-outpu
