### ISSUE TITLE
Invalid @belongsTo

### ISSUE THREAD

**Issue by irakli-g** [aws-amplify/amplify-cli#9145]
**Which Category is your question related to?**
I've been trying to debug this for several hours now but I can't compile my graphql schema and I get this error.

<img width="1325" alt="Screenshot 2021-11-30 at 14 09 14" src="https://user-images.githubusercontent.com/70649220/144028074-d2c6bba7-4145-463f-97a3-3b373aea9d50.png">

This is how favorite post and post schema looks like >>>
<img width="1094" alt="Screenshot 2021-11-30 at 14 16 31" src="https://user-images.githubusercontent.com/70649220/144028708-1cde635c-5e48-4451-8e6b-c161429cc73e.png">

Am I doing something wrong here or is it just a bug?

**Amplify CLI Version**
7.5.4

**What AWS Services are you utilizing?**
S3, DynamoDB, Amplify, Appsync, Cognito

**Provide additional details e.g. code snippets**

**Comment by sundersc** [comment]
Hey @irakli-g Since you have a partition key and sort key on type `Post`, I believe you must specify 2 fields on `@belongsTo` directive so that dynamoDB knows how to do the join.

**Comment by sundersc** [comment]
Hey @irakli-g Since you have a primary key (with partition key and sort key), I believe `@belongsTo` must specify 2 fields to perform the join. However I see this validation happens only when I have an auth rule on the model. We are looking into this.

**Comment by sundersc** [comment]
@irakli-g Did you get this working by matching the primary key fields on `belongsTo` relational directive?

**Comment by irakli-g** [comment]
@sundersc sorry I did not have a chance to test it. Could you please write a small schema example of how it should be handled properly and I'll give it a try right away? Thanks.

**Comment by sundersc** [comment]
@irakli-g - We can do something like this. `StudentCourse`'s primary key is `id` (PK) + `studentId` (SK). So belongsTo must specify two fields to establish a successful relationship `studentCourseId` and `studentId`.

```graphql
type StudentScore @model {
  id: ID!
  studentCourseId: ID!
  studentId: ID!
  studentCourse: StudentCourse @belongsTo(fields: ["studentCourseId", "studentId"])
  # other fields
}

type StudentCourse @model {
  id: ID! @primaryKey(sortKeyFields: ["studentId"])
  studentId: ID!
  courseId: ID!
  scores: [StudentScore] @hasMany
  # other fields
}
```

**Comment by irakli-g** [comment]
@sundersc Works like a charm!

I've tried this too and it successfully compiled.
```
type StudentScore @model {
  id: ID!
  studentCourseId: ID!
  studentId: ID! @index(name:"studentScoreByDate",queryField:"studentScoreByDate", sortKeyFields:["createdAt"])
  studentCourse: StudentCourse @belongsTo(fields: ["studentCourseId", "studentId"])
  createdAt: AWSDateTime!
}

type StudentCourse @model {
  id: ID! @primaryKey(sortKeyFields: ["studentId"])
  studentId: ID!
  courseId: ID!
  scores: [StudentScore] @hasMany
}
```
