### ISSUE TITLE
Amplify mock not pulling response format from schema

### ISSUE THREAD

**Issue by Lazarus404** [aws-amplify/amplify-cli#9147]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

mock api

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

7.5.4

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

Pipeline defined in `CustomResources.json`:
```
"getDirectoriesResolver": {
  "Type": "AWS::AppSync::Resolver",
  "Properties": {
    "ApiId": {
      "Ref": "AppSyncApiId"
    },
    "TypeName": "Query",
    "Kind": "PIPELINE",
    "PipelineConfig": {
      "Functions": [{
        "Fn::GetAtt": [
          "FunctionGetSite",
          "FunctionId"
        ]
      }, {
        "Fn::GetAtt": [
          "FunctionGetUser",
          "FunctionId"
        ]
      }, {
        "Fn::GetAtt": [
          "FunctionGetUserDirectories",
          "FunctionId"
        ]
      }, {
        "Fn::GetAtt": [
          "FunctionGetDirectories",
          "FunctionId"
        ]
      }]
    },
    "FieldName": "listDirectoriesFunction",
    "RequestMappingTemplate": "{}",
    "ResponseMappingTemplate": "$util.toJson($ctx.result)"
  },
  "DependsOn": ["FunctionGetSite", "FunctionGetUser", "FunctionGetUserDirectories", "FunctionGetDirectories"]
}
```
and schema defined in `schema.graphql`:
```
type Query {
  listDirectoriesFunction(host: String!): [Directory]
}
```
However, the GraphQL explorer does not suggest a list of items will be returned.  I would expect the schema shown in GraphQL explorer to show the child elements `items`, `nextToken` and `startedAt`, but instead I see the immediate model fields.  Is there something missing to tell the generator to determine this as a `list` based query?

**Comment by sundersc** [comment]
If it is a custom query, you will need to wrap it around another type to get the same result. You can take a look at the `amplify/api/<api-name>/build/schema.graphql` to see how it works on types with model directive.

For example:
```graphql
type ModelTodoConnection {
  items: [Todo!]!
  nextToken: String
}
```

**Comment by Lazarus404** [comment]
That worked great!  Thank you.
