### ISSUE TITLE
Unknown directive "primaryKey"

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#9149]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Environment information

ok

### Describe the bug

All the new directives are unknown.

### Expected behavior

An error occurred during the push operation: Unknown directive "primaryKey" 
after amplify push.

### Reproduction steps

ok

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "manyToMany".

Unknown directive "hasMany".

Unknown directive "hasOne".

Unknown directive "hasOne".

Unknown directive "hasMany".

Unknown directive "hasMany".

Unknown directive "hasMany".

Unknown directive "primaryKey".

Unknown directive "belongsTo".

Unknown directive "primaryKey".

Unknown directive "hasMany".

Unknown directive "primaryKey".

Unknown directive "hasMany".

Unknown directive "belongsTo".

Unknown directive "hasMany".

Unknown directive "belongsTo".

**Comment by sundersc** [comment]
Hey @rudyhadoux, can you make sure the below feature flags are set correctly on the `cli.json` file? It should look like the below.

```
"useexperimentalpipelinedtransformer": true,
"transformerversion": 2,
```

**Comment by rudyhadoux** [comment]
Thanks.
With this parameters it works but old directives are unknown like 
@key
@version

**Comment by sundersc** [comment]
To use the new directives, you need to migrate your api from v1 to v2 first. There are 2 options,
1. Revert your feature flags and run `amplify migrate api`, this should convert the schema from v1 to v2. There may be some manual corrections required based on your schema.
2. Convert the schema manually as documented here and set the feature flags to v2.
https://docs.amplify.aws/cli/migration/transformer-migration/

**Comment by rudyhadoux** [comment]
It seems that @key becomes @index.
But @versioned ?

**Comment by rudyhadoux** [comment]
I don't understand because I have Amplify CLI 7.5.4. My project is two days old.
And I think it is a very bad idea to delete @versioned because it was very useful.

**Comment by cjihrig** [comment]
@rudyhadoux the `@key` directive has been replaced with `@primaryKey` and `@index` depending on which functionality you're looking for.

`@versioned` was not carried forward because the functionality is now supported in AppSync and DataStore, so it was deemed no longer necessary.

**Comment by sundersc** [comment]
Looking at the docs, it looks `@versioned` was depreciated in favor of conflict detection.
https://docs.amplify.aws/lib/datastore/conflict/q/platform/js/

**Comment by rudyhadoux** [comment]
OK thanks.
