### ISSUE TITLE
PostAuth trigger doesn't  exists in cloudwatch

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9150]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.5.4

### What operating system are you using?

Mac

### Amplify Categories

auth, function

### Amplify Commands

update

### Describe the bug

I added the post Auth trigger to Cognito user pool of my current project. After pushing it to the cloud, I can see the post-authentication trigger in cognito pool, but when I am trying to navigate to cloudwatch through "post-authentication trigger" function, it says this log group doesn't. exists. But today morning I can see it is created, but the thing is, it is only triggered once after deployment, when I logged in using google, after that, it didn't work. 
So for a quick test, I created another env. (testAuth), deployed. same auth configuration with google as a service provider.
But now, the same thing is happening, log group doesn't. exists.
![Uploading image.png…]()

### Expected behavior

It should deploy the log group, and one more thing. with the older one, it is not getting triggered after authentication. 
I can see the new users' entry in the Cognito user pool.

### Reproduction steps

 amplify update auth                                          ✔  3m 27s 
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Sto
rage features for images or other content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Google
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and cr
eate an App ID. 
 
 Enter your Google Web Client ID for your identity pool:  xxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use?  backende66ab65d-e66ab65d
 Which redirect signin URIs do you want to edit? 
 Do you want to add redirect signin URIs? No
 Which redirect signout URIs do you want to edit? 
 Do you want to add redirect signout URIs? No
 Select the OAuth flows enabled for this project. Authorization code grant
 Select the OAuth scopes enabled for this project. Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the identity providers you want to configure for your user pool: Google
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and cr
eate an App ID. 
 
 Enter your Google Web Client ID for your OAuth flow:  xxxxxxxxxxxxx.apps.googleusercontent.com
 Enter your Google Web Client Secret for your OAuth flow:  xxxxxxxxxxxxxxxxxxxf
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Post Authentication
? What functionality do you want to use for Post Authentication Create your own module
Successfully updated the Cognito trigger locally
✅ Successfully updated auth resource   backende66ab65d locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

✅ Successfully updated resource update locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hackrx** [comment]
Today I added, post-confirmation trigger, and it doesn't get reflected in the Cognito, though in `cli-inputs.json`, I can see the entries of customAuth lambda trigger for post-confirmation and post-authentication.
Now, both of these triggers are not visible in the Cognito console, earlier post-authentication trigger was there in the console, but its cloudwatch did not exist.

## backend/api/auth/blogbackende22eg67t/cli-inputs.json 
```
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "blogbackende22eg67t_identitypool_e22eg67t",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "blogte22eg67t",
    "userPoolName": "blogbackende22eg67t_userpool_e22eg67t",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "username",
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": "30",
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "blogte22eg67t_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "sharedId": "e22eg67t",
    "resourceName": "blogbackende22eg67t",
    "authSelections": "identityPoolAndUserPool",
    "useDefault": "manual",
    "hostedUI": true,
    "triggers": {
      "PostAuthentication": [
        "custom"
      ],
      "PostConfirmation": [
        "custom"
      ]
    },
    "hostedUIDomainName": "blogbackende22eg67t-e22eg67t",
    "authProvidersUserPool": [
      "Google"
    ],
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid profile email\",\"AttributeMapping\":{\"username\":\"sub\",\"email\":\"email\"}}]",
    "userPoolGroupList": [],
    "serviceName": "Cognito",
    "usernameCaseSensitive": false,
    "useEnabledMfas": false,
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": true,
    "dependsOn": [
      {
        "category": "function",
        "resourceName": "blogbackende22eg67tPostAuthentication",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      },
      {
        "category": "function",
        "resourceName": "blogbackende22eg67tPostConfirmation",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      }
    ],
    "userPoolGroups": false,
    "adminQueries": false,
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "authTriggerConnections": "[\n  {\n    \"triggerType\": \"PostAuthentication\",\n    \"lambdaFunctionName\": \"blogbackende22eg67tPostAuthentication\"\n  },\n  {\n    \"triggerType\": \"PostConfirmation\",\n    \"lambdaFunctionName\": \"blogbackende22eg67tPostConfirmation\"\n  }\n]",
    "permissions": [],
    "authProviders": [
      "accounts.google.com"
    ],
    "thirdPartyAuth": true,
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"testblogs://\"],\"LogoutURLs\":[\"testblogs://\"]}"
  }
}
```

**Comment by hackrx** [comment]
Amplify pull is working fine, but when I am trying to push it. It is giving this error: 

```
? Are you sure you want to continue? Yes
GraphQL schema compiled successfully.

Edit your schema at /Volumes/RajatSSD/FlutterProject/Blog-Backend/Application-Backend/habsyJSBackend/amplify/backend/api/Blogbackend/schema.graphql or place .graphql files in a directory at /Volumes/RajatSSD/FlutterProject/Blog-Backend/Application-Backend/habsyJSBackend/amplify/backend/api/Blogbackend/schema
⠸ Building resource api/BlogbackendGraphQL schema compiled successfully.

Edit your schema at /Volumes/RajatSSD/FlutterProject/Blog-Backend/Application-Backend/habsyJSBackend/amplify/backend/api/Blogbackend/schema.graphql or place .graphql files in a directory at /Volumes/RajatSSD/FlutterProject/Blog-Backend/Application-Backend/habsyJSBackend/amplify/backend/api/Blogbackend/schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscriptio
n) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Ye
s
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-Blogbackend-rtestapis-200457          AWS::CloudFormation::Stack Fri Dec 03 2021 14:56:54 GMT+0530 (India Standard Time) User Initiated
UPDATE_IN_PROGRESS functionBlogbackende66ab65dPostAuthentication AWS::CloudFormation::Stack Fri Dec 03 2021 14:56:59 GMT+0530 (India Standard Time)
UPDATE_IN_PROGRESS storageBlogbackends3                          AWS::CloudFormation::Stack Fri Dec 03 2021 14:56:59 GMT+0530 (India Standard Time)
UPDATE_IN_PROGRESS authBlogbackende66ab65d                       AWS::CloudFormation::Stack Fri Dec 03 2021 14:56:59 GMT+0530 (India Standard Time)
UPDATE_COMPLETE    functionBlogbackende66ab65dPostAuthentication AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:00 GMT+0530 (India Standard Time)
UPDATE_COMPLETE    storageBlogbackends3                          AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:00 GMT+0530 (India Standard Time)
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS amplify-Blogbackend-rtestapis-200457-authBlogbackende66ab65d-56NEPR8CXZZK AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:00 GMT+0530 (India Standard Time) User Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Fri Dec 03 2021 14:57:08 GMT+0530 (India Standard Time)
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          HostedUIProvidersCustomResourceInputs                                               Custom::LambdaCallout      Fri Dec 03 2021 14:57:12 GMT+0530 (India Standard Time) Requested update required the provider to create a new physical resource
UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                                               Custom::LambdaCallout      Fri Dec 03 2021 14:57:12 GMT+0530 (India Standard Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/12/03/[$LATEST]b1ae2b894c6c43b185d8c6fc0ff8bc80 (RequestId: 2c571992-a2e2-494f-b5f5-cdf412b93842)
UPDATE_ROLLBACK_IN_PROGRESS amplify-Blogbackend-rtestapis-200457-authBlogbackende66ab65d-56NEPR8CXZZK AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:13 GMT+0530 (India Standard Time) The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               authBlogbackende66ab65d              AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:22 GMT+0530 (India Standard Time) Embedded stack arn:aws:cloudformation:us-east-2:661481011465:stack/amplify-Blogbackend-rtestapis-200457-authBlogbackende66ab65d-56NEPR8CXZZK/0a1dadb0-51f4-11ec-9709-06aa052d8626 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
UPDATE_ROLLBACK_IN_PROGRESS amplify-Blogbackend-rtestapis-200457 AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:23 GMT+0530 (India Standard Time) The following resource(s) failed to update: [authBlogbackende66ab65d].
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS authBlogbackende66ab65d                       AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:51 GMT+0530 (India Standard Time)
UPDATE_IN_PROGRESS functionBlogbackende66ab65dPostAuthentication AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:51 GMT+0530 (India Standard Time)
UPDATE_IN_PROGRESS storageBlogbackends3                          AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:51 GMT+0530 (India Standard Time)
UPDATE_COMPLETE    functionBlogbackende66ab65dPostAuthentication AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:51 GMT+0530 (India Standard Time)
UPDATE_COMPLETE    storageBlogbackends3                          AWS::CloudFormation::Stack Fri Dec 03 2021 14:57:51 GMT+0530 (India Standard Time)
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Fri Dec 03 2021 14:58:21 GMT+0530 (India Standard Time)
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-Blogbackend-rtestapis-200457-authBlogbackende66ab65d-56NEPR8CXZZK AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:22 GMT+0530 (India Standard Time)
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE authBlogbackende66ab65d AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:25 GMT+0530 (India Standard Time)
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-Blogbackend-rtestapis-200457 AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:28 GMT+0530 (India Standard Time)
UPDATE_COMPLETE                              storageBlogbackends3                 AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:30 GMT+0530 (India Standard Time)
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE functionBlogbackende66ab65dPostAuthentication AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:30 GMT+0530 (India Standard Time)
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE          authBlogbackende66ab65d              AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:40 GMT+0530 (India Standard Time)
UPDATE_ROLLBACK_COMPLETE amplify-Blogbackend-rtestapis-200457 AWS::CloudFormation::Stack Fri Dec 03 2021 14:58:40 GMT+0530 (India Standard Time)
⠹ Updating resources in the cloud. This may take a few minutes...

Following resources failed

Resource Name: 2021/12/03/[$LATEST]b1ae2b894c6xxxxxxxxxc0ff8bc80 (Custom::LambdaCallout)
Event Type: update
Reason: Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/12/03/[$LATEST]b1ae2b894c6c43b185d8c6fc0ff8bc80 (RequestId: 2c571992-a2e2-494f-b5f5-cdf412b93842)
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-2%3A661481011465%3Astack%2Famplify-Blogbackend-rtestapis-200457-authBlogba/events


✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```
And when I am trying to remove this trigger from amplify auth using `amplify update auth` then apply custom authorization with social provider, and then trying to removing this lambda function using `amplify remove function` but it says: 
```
amplify remove function    ✔  28s
? Choose the resource you would want to remove Blogbackende66ab65dPostAuthentication (function)

? Are you sure you want to delete the resource? This action deletes all files related to this resource from the
 backend directory. Yes
🛑 Resource cannot be removed because it has a dependency on another resource
🛑 Dependency: Cognito - Blogbackende66ab65d
🛑 An error occurred when removing the resources from the local directory
```
Please suggest some fix for this issue. 
Thanks.

**Comment by josefaidt** [comment]
Hey @hackrx :wave: thanks for raising this! Unfortunately I was not able to reproduce this issue using the provided reproduction steps. Although it does take a few minutes for the CloudWatch log group to show up in the Console after deploy and logging in, I was able to see the `console.log()` statements I added to the function

```js
// custom.js
exports.handler = async event => {
  console.log('LOGGING FROM THE POST AUTH TRIGGER')
}
```

![image](https://user-images.githubusercontent.com/5033303/144646642-4d7621b8-ab3f-4917-942f-75ddb5903f97.png)

To remove the trigger, we can walk through `amplify update auth` and remove the Post Authentication trigger. By doing so the CLI will remove the function from our project.

**Comment by hackrx** [comment]
Okay, so I updated my auth using `amplify update auth` then it removed the trigger. Again I added post auth trigger and this time it worked 🍾  . Now I can  see the logs in the cloud-watch. Thanks  @josefaidt.
I have one doubt, the code in `custom.js` file have `callback()` function: 
```
callback(null, event);
```
And I can see an error in cloud-watch that `callback is not a function`. I know if I will comment it, then the function will not throw an error, but why it is added in boilerplate code? what is the significance of the `callback()` function?
```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "callback is not a function",
    "stack": [
        "TypeError: callback is not a function",
        "    at Object.exports.handler (/var/task/custom.js:7:3)",
        "    at /var/task/index.js:37:50",
        "    at Array.map (<anonymous>)",
        "    at Runtime.exports.handler (/var/task/index.js:37:29)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```
@josefaidt can you put some light on this, please?
