### ISSUE TITLE
geo cli auth warning

### ISSUE THREAD

**Issue by raphkim** [aws-amplify/amplify-cli#9154]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.4.2

### Amplify CLI Version

7.5.4

### What operating system are you using?

Mac

### Amplify Categories

auth, Not applicable

### Amplify Commands

add

### Describe the bug

```console
raphk@88665a1eb0f6 geotest2 % amplify add geo
? Select which capability you want to add: Map (visualize the geospatial data)
✔ geo category resources require auth (Amazon Cognito). Do you want to add auth now? (Y/n) · yes

Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Defau
lt configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
✅ Successfully added auth resource geotest2f9f9186c locally

✅ Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

✔ Provide a name for the Map: · map6bed22b1
✔ Who can access this Map? · Authorized and Guest users
The following choices determine the pricing plan for Geo resources. Learn more at https://aws.amazon.com/location/pricing/
✔ Are you tracking commercial assets for your business in your app? · No, I do not track devices or I only need to track consumers' personal devices
Successfully set RequestBasedUsage pricing plan for your Geo resources.
Available advanced settings:
- Map style & Map data provider (default: Streets provided by Esri)

✔ Do you want to configure advanced settings? (y/N) · no
⚠️ Auth configuration is required to allow unauthenticated users, but it is not configured properly.
⚠️ Adding Map to your project requires the Auth category for managing authentication rules.
✅ Successfully updated auth resource locally.
✅ Successfully added resource map6bed22b1 locally.
```

Even after adding auth category (as part of adding geo category), the following warnings pop up:
- "⚠️ Auth configuration is required to allow unauthenticated users, but it is not configured properly."
- "⚠️ Adding Map to your project requires the Auth category for managing authentication rules."

### Expected behavior

The CLI should detect that Auth resources have been added to the project and not display these warnings.

### Reproduction steps

1. ```amplify add geo```
2. Add auth when prompted

### GraphQL schema(s)

N/A

### Log output

N/A

### Additional information

N/A

**Comment by phani-srikar** [comment]
This has been fixed with CLI `v7.6.2`
