### ISSUE TITLE
amplify push issue

### ISSUE THREAD

**Issue by RatMan64** [aws-amplify/amplify-cli#9156]
this question is related to pushing items from a new amplify project.

**Amplify CLI Version** 
7.5.4

**What AWS Services are you utilizing?**
amplify

**Provide additional details e.g. code snippets**

First I have been working off a default react app with the Cognito authentication already integrated. the issue I'm having is when I try to push a new amplify API with lambda API gateway and dynamodb. this push fails with 
× An error occurred when pushing the resources to the cloud
```
🛑 An error occurred during the push operation: Inaccessible host: `amplify-cs453final-dev-143606-deployment.s3.us-west-2.amazonaws.com' at port `undefined'. This service may not be available in the `us-west-2' region.
```
does anyone know what could be causing this? I tried from a fresh amplify app and got the same issue.

**Comment by sundersc** [comment]
Hi @RatMan64, I'm unable to reproduce the issue. Is your machine behind a VPN (or firewall) which could block uploading files to a S3 bucket?

**Comment by RatMan64** [comment]
I am at my univsersity. ill have to see if this is the case when i get home.

**Comment by RatMan64** [comment]
@sundersc yes that was the issue my school wifi blocks the creation of aws items but doesn't block the updating of resources thanks.

**Comment by RatMan64** [comment]
ok this issue has now recurred after i updated the cli and some of the items that I created also disappeared at my home
