### ISSUE TITLE
Amplify CLI too slow

### ISSUE THREAD

**Issue by dobeerman** [aws-amplify/amplify-cli#9163]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

7.5.5

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

The amplify cli works too slow and has the following timing:
```bash
$ time amplify --version
7.5.5
amplify --version  18,99s user 1,25s system 124% cpu 16,227 total
``` 

### Expected behavior

Immediate response

### Reproduction steps

```bash
$ yarn global add @aws-amplify/cli
$ amplify --version
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

2021-12-01T08:23:56.296Z|info : amplify version core  {"version":true,"yes":false}
2021-12-01T08:24:22.355Z|info : amplify help core  
2021-12-01T08:25:21.675Z|info : amplify version core  {"version":true,"yes":false}
2021-12-01T09:14:46.007Z|info : amplify version core  {"version":true,"yes":false}


```

</details>

**Comment by cjihrig** [comment]
We recently merged https://github.com/aws-amplify/amplify-cli/pull/9155, which will hopefully address this. Please give the next release a try once it is available.

**Comment by dobeerman** [comment]
Good job, guys! Thanks a lot.
I might confirm that the #9155 fixed the issue partly. The current timing is the following:

```sh
$ time amplify --version
7.6.0
amplify --version  8,00s user 0,62s system 134% cpu 6,401 total
```

**Comment by cjihrig** [comment]
Thank you for verifying. I'll close this out.
