### ISSUE TITLE
Cannot add any amplify module

### ISSUE THREAD

**Issue by BogdanCodreanu** [aws-amplify/amplify-cli#9165]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn global add @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.9.1

### Amplify CLI Version

7.5.4

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api

### Amplify Commands

add

### Describe the bug

When i try to add any amplify module using `amplify add X` i am getting the error:

```
Section 'overrides' is not registered in feature provider
Error: Section 'overrides' is not registered in feature provider
    at FeatureFlags.getValue (C:\Users\bogda\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\node_modules\amplify-cli-core\src\feature-flags\featureFlags.ts:231:13)
    at Function.FeatureFlags.getBoolean (C:\Users\bogda\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\node_modules\amplify-cli-core\src\feature-flags\featureFlags.ts:122:34)
    at selectPluginForExecution (C:\Users\bogda\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\src\execution-manager.ts:52:22)
    at executeCommand (C:\Users\bogda\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\src\execution-manager.ts:32:38)
    at Object.run (C:\Users\bogda\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\src\index.ts:205:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I have reinstalled the amplify cli, tried it with a new empty project and the same error is achieved everytime. It's like something is broken on my machine.

### Expected behavior

Add api module using `amplify add api`

**Comment by lazpavel** [comment]
Hi @BogdanCodreanu, can you please share the contents of `amplify/cli.json`?

**Comment by BogdanCodreanu** [comment]
Yes, thank you, right here:
`{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  }
}`

**Comment by lazpavel** [comment]
Can you try to run `amplify --version` and make sure you're on the latest version. Try uninstalling amplify and run `amplify --version` again to confirm there isn't any installation left. Then install it again.

Can you add the minimal reproduction steps in an empty directory?

**Comment by BogdanCodreanu** [comment]
I did the following steps:

1. `amplify --version` gave the output of `7.5.4`.
2. removed all global node_modules (from npm and from yarn)
3. `amplify --version` gave the output of `The system cannot find the path specified.`
4. `yarn cache clean`
5. `yarn global add @aws-amplify/cli`
6. `amplify --version` gave the output of `7.5.5`.
7. `amplify add api` results in the same error (Section 'overrides' is not registered in feature provider) with the same stack trace

**Comment by lazpavel** [comment]
I am unable to reproduce the issue, can you send a copy of your project at amplify-cli@amazon.com? Thank you!

**Comment by BogdanCodreanu** [comment]
Well it happens with any empty project that's just initialized with `npm init` / `yarn init`.
I think it's something that's happening from my machine. It started happening after a `amplify delete` command threw an exception and failed (although the amplify on the console web and cloudfromation stack were deleted). Unfortunately I don't have the exception that was thrown on amplify delete. It happened last night and then i wen to sleep when i saw that the add api is not working anymore.

**Comment by lazpavel** [comment]
can you run the following commands in an empty directory:
- `amplify init`
- `amplify add api` 
and let me know if you have the same issue

**Comment by BogdanCodreanu** [comment]
It's the same error

**Comment by BogdanCodreanu** [comment]
I tried it with a different aws account and it still is the same error

**Comment by cjihrig** [comment]
@BogdanCodreanu we are looking into this on our side. It appears to be a bug related to feature flags.

**Comment by edwardfoyle** [comment]
Can you try installing the CLI globally using npm instead of yarn? Currently we do not support yarn installs.

**Comment by BogdanCodreanu** [comment]
Same behavior unfortunately... (on empty directory after `amplify init`)
```
PS G:\Repos\test> amplify add api
Section 'overrides' is not registered in feature provider
Error: Section 'overrides' is not registered in feature provider
    at FeatureFlags.getValue (C:\Users\bogda\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-cli-core\lib\feature-flags\featureFlags.js:58:23)
    at Function.FeatureFlags.getBoolean (C:\Users\bogda\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-cli-core\lib\feature-flags\featureFlags.js:534:34)
    at selectPluginForExecution (C:\Users\bogda\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:56:45)
    at executeCommand (C:\Users\bogda\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:38:42)
    at Object.run (C:\Users\bogda\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:162:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by edwardfoyle** [comment]
Looks like a bug here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/execution-manager.ts#L52 @akshbhu I think this needs to be updated with the new overrides FF logic?

**Comment by BogdanCodreanu** [comment]
I confirm that it's working on version 7.6.5!
