### ISSUE TITLE
Custom Plugins/Directives migration guide for GraphQL Transformer v2

### ISSUE THREAD

**Issue by jaxyeh** [aws-amplify/amplify-cli#9180]
**Which Category is your question related to?**
GraphQL Transformer v2

**Amplify CLI Version:** 
7.5.4

**Problem:** 

Hi, I am working on migrating our from API GraphQL Transformer v1 to v2 for my company.

I tried to run the migration script (`amplify migrate api`) but it crashed with all different schema errors which I thought it would migrate the code automatically. Regardless, I went ahead run through changes manually one by one. Then I tried to run the `amplify migrate api` again at the end of the manual changes to see any issues. Still, I've encountered many error messages related to those several "Unknown directive" associated to the "@ttl" directive and several of our custom-developed directives.

Our team has developed our own custom GraphQL Transformer Plugins (aka GraphQL directives) along with the third-party transformer called `graphql-TTL-transformer`. After some digging, I found this migration guide written by one of your team member: https://gist.github.com/renebrandel/0b9537e2016e3dd9ed6d794b30b2e3f4. I was surprised that it wasn't published through the official documentation guide.

I am aware that the `@ttl` directive package hasn't been upgraded to support v2 yet. This was mentioned here: https://github.com/flogy/graphql-ttl-transformer/issues/12.

For now, I would like your guidance to focus on fixing our current custom developed transformers. At this point, the `amplify-graphql` pkg is not found in public npm domain. I am unable to see some of those packages found in the `amplify-cli` monorepos, but they don't seem to be published. At bottom of that guide, it mentioned that we could use `@aws-amplify/graphql-transformer-interfaces` package but that is not clear to me.

Code example would be helpful. When trying to look through a couple of official transformers found in the `amplify-cli` monorepos, they do not use the `amplify-graphql` and `amplify-graphql-transformer-core` packages directly. They did not inherit the `TransformerPluginBase` class as suggested in that guide, and maybe we were not supposed to upgrade either? Maybe it was an compatiblity issue with the migrate script, but will not be an issue pushing into amplify services? Or perhaps I am confused?

Any additional code examples or guidance will be appreciated!

**Comment by jaxyeh** [comment]
1) For reference to the error messages (`...` truncated many of those same "Unknown directive"):

```bash
➜  ash git:(jax/transformerV2) ✗ amplify migrate api
⚠️ Your instance type for OpenSearch is t2.small.elasticsearch, you may experience performance issues or data loss. Consider reconfiguring with the instructions here https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments
🛑 Unknown directive "customAudited".
...
Unknown directive "customTenanted".
...
Unknown directive "ttl".
...
    at assertValidSDL (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/validation/validate.js:108:11)
    at buildASTSchema (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at validateModelSchema (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/validation.ts:145:32)
    at GraphQLTransform.transform (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:172:39)
    at _buildProject (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:564:37)
    at buildAPIProject (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:521:24)
    at transformGraphQLSchema (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:394:29)
    at Object.run (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/commands/api/migrate.ts:32:5)
    at Object.executeAmplifyCommand (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:222:5)
    at executePluginModuleCommand (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/jax/.nvm/versions/node/v16.8.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

2) I've added `"suppressSchemaMigrationPrompt": true` flag to the `cli.json`, and the cli error above remains the same.

3) I've tried to refactor the custom transformer code as follow, but the `amplify migrate api` error issue remains:

<img width="634" alt="Screen Shot 2021-12-02 at 3 08 04 PM" src="https://user-images.githubusercontent.com/202622/144495185-c912b1f9-f271-46fe-8aef-f3917aa045dd.png">

**Comment by sundersc** [comment]
Hi @jaxyeh Can you please try the approach as documented here.
https://docs.amplify.aws/cli/plugins/authoring/#authoring-custom-graphql-transformers--directives

**Comment by jaxyeh** [comment]
Hi @sundersc, thank you for getting back to me. I've tried to rewrite the custom transformer accordingly to the guide, but I still can't load the custom transformers. I had to inject some debug logs against the `amplify-cli` runtime, and apparently, it did not load the custom transformers? See the screenshot of the VSCode Debug stack. Is there a reason why the custom transformers are not loaded in the `transformers` stack? 

<img width="1433" alt="Screen Shot 2021-12-07 at 12 45 08 PM" src="https://user-images.githubusercontent.com/202622/145111932-2d758bdf-3779-424f-a0cd-311804079a87.png">

_By the way,  you can see the custom transformers are listed within the `.transformConfig` stack!_

----

###  For the reference, here below is a basic example of custom transformer code:

**transform.config.json:**

```json
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "transformers": [
        "graphql-transformer-audited",
        "graphql-transformer-tenanted",
        "graphql-ttl-transformer",
        "graphql-default-owner-transformer"
    ],
    "StackMapping": {
        "QuerylistEventsBySeriesResolver": "EventWatcher",
        "FacilitycontactsResolver": "ConnectionStack",
        "TierIIFacilityProductproductResolver": "ConnectionStack",
        "QuerygetEventDocumentsResolver": "EventDocument",
        "QuerylistEventWatchersBySeriesResolver": "EventWatcher"
    }
}
```

**graphql-transformer-audited.ts:**

```typescript
import { InvalidDirectiveError, TransformerPluginBase } from "@aws-amplify/graphql-transformer-core";
import {  TransformerContextProvider, TransformerSchemaVisitStepContextProvider } from "@aws-amplify/graphql-transformer-interfaces";
import { DirectiveNode, FieldDefinitionNode, ObjectTypeDefinitionNode } from "graphql";

type DefaultValueDirectiveConfiguration = {
  object: ObjectTypeDefinitionNode;
  field: FieldDefinitionNode;
  directive: DirectiveNode;
  modelDirective: DirectiveNode;
  value: string;
};

const directiveName = "customAudited";

const directiveDefinition = /* GraphQL */ `
  directive @${directiveName} on OBJECT
`;

/**
 * Basic Custom Transformers with log outputs for testing purpose
 */
export class AuditedModelTransformer extends TransformerPluginBase {
  constructor() {
    super("graphql-transformer-audited", directiveDefinition);
    console.log("AuditedModelTransformer init!");
  }

  object = ( definition: ObjectTypeDefinitionNode, directive: DirectiveNode,  ctx: TransformerSchemaVisitStepContextProvider ): void => {
    validateModelDirective(definition);
    console.log(`Detect Object for ${directiveName}`);
  };

  generateResolvers = (ctx: TransformerContextProvider): void => {
    console.log(`Generate Resolver for ${directiveName}`);
  };
}

function validate( ctx: TransformerSchemaVisitStepContextProvider, config: DefaultValueDirectiveConfiguration ): void {
  validateModelDirective(config.object);
}

function validateModelDirective(object: ObjectTypeDefinitionNode): void {
  const modelDirective = object.directives!.find(
    (dir) => dir.name.value === "model"
  );
  if (!modelDirective) {
    throw new InvalidDirectiveError(
      `Types annotated with @${directiveName} must also be annotated with @model.`
    );
  }
}
```

I've tried to load the custom transformers written by a third party (https://github.com/sirvan3tr/amplify-graphql-default-owner-transformer). Unfortunately, I am still unable to load them in our code.

I've considered doing fresh vanilla amplify setup to prove my point, but AWS is experiencing a network-wide outage at the moment. Please confirm you can load the custom transformers into the Amplify code?

**Comment by cjihrig** [comment]
I can confirm this is a bug. I'm working on a fix.
