### ISSUE TITLE
Build fails with Cannot read property 'envName' of undefined

### ISSUE THREAD

**Issue by nunesky** [aws-amplify/amplify-cli#9184]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.11.0

### Amplify CLI Version

6.1.1

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

This is a follow up to the bug #9170

My build was failing on 1 Dec with the message `Parameters: [s3Key, deploymentBucketName] must have values`. That specific bug seems to have been fixed, but now my build fails with:

```
2021-12-02T11:23:38.869Z [INFO]: �[0mTypeError: Cannot read property 'envName' of undefined�[0m
                                 �[0m    at getCurrentEnvName (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/envResourceParams.ts:15:47)�[0m
                                 �[0m    at AmplifyToolkit.removeDeploymentSecrets [as _removeDeploymentSecrets] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/envResourceParams.ts:156:22)�[0m
                                 �[0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:421:60�[0m
                                 �[0m    at Array.map (<anonymous>)�[0m
                                 �[0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:421:8)�[0m
                                 �[0m    at runMicrotasks (<anonymous>)�[0m
                                 �[0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)�[0m
2021-12-02T11:23:38.908Z [ERROR]: !!! Build failed
```

### Expected behavior

Successful build

### Reproduction steps

Trigger a build in the CI/CD system through the amplify console or by a push trigger.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by christophersutton** [comment]
I've received the same error, and in the same situation where yesterday builds were failing for "Parameters: [s3Key, deploymentBucketName] must have values", now failing with envName error. 

`[0mTypeError: Cannot read property 'envName' of undefined[0m`

**Comment by josefaidt** [comment]
Hey @christophersutton and @nunesky I was able to reproduce using the following steps:

- `npm i -g @aws-amplify/cli@6.1.1`
- create a new project with `amplify init -y`
- add add, accept defaults
- add a REST API, add a route `/hello`, restrict access to auth users
- create a git repo and push
- `amplify add hosting` to enable CI

![image](https://user-images.githubusercontent.com/5033303/144457096-3c2ad8da-ad9a-4732-b298-8dcd72da4c46.png)

Marking this as a bug 🙂

As a workaround we can pin the Amplify CLI version in the Console to what we are using locally either via the console or via the buildspec (`amplify.yml`)
```yml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm install --global @aws-amplify/cli@6.1.1
    build:
      commands:
        - amplifyPush --simple
```
![image](https://user-images.githubusercontent.com/5033303/144457365-0be7ec0f-adc6-41d6-ae6f-d7325e4a2072.png)

**Comment by nunesky** [comment]
> Hey @nunesky and @christophersutton 👋 thanks for raising this! I've just triggered a build on an existing project of mine to reproduce. To clarify, were there any backend changes that were made prior to experiencing this error? At what step in the backend build did you notice this?
> 
> ```
> # Importing Amplify environment: next (amplify env import)
> 2021-12-02T15:16:54.693Z [INFO]: �[32mSuccessfully added environment from your project�[39m
> 2021-12-02T15:16:54.783Z [INFO]: # Initializing existing Amplify environment: next (amplify init)
> 2021-12-02T15:16:59.816Z [INFO]: �[33mNote: It is recommended to run this command from the root of your app directory�[39m
> 2021-12-02T15:17:06.166Z [WARNING]: - Initializing your environment: next
> ```

My case is the same as @christophersutton. No changes to backend, yesterday builds failed with `Parameters: [s3Key, deploymentBucketName] must have values`, now failing with `envName` error. The stage in which the build fails is the same as shown in the log in your most recent comment. 
Thanks for looking into this!
