### ISSUE TITLE
Amplify push don't work

### ISSUE THREAD

**Issue by nazarcybulskij** [aws-amplify/amplify-cli#9189]
Describe the bug

Amplify-CLI can not  add   modules (analytics, function and etc.)   
We get an error message   --  🛑 An error occurred during the push operation: Resource is not in the state stackUpdateComplete after "amplify push" 

To Reproduce
Steps to reproduce the behaviour:

1) Create project   -- "amplify init"
2) Add Auth module  --  "amplify add auth" 
3) add login mechanism Google from AdminUI  
4) turn on  Enable access to unauthenticated identities 
5) add a new  Date model from  admin UI

We think.

maybe, we have a conflict between different authorization modes  (Api key mode and Cognito user pool mode)

![Screenshot 2021-12-02 at 14 52 36](https://user-images.githubusercontent.com/5183069/144425651-c0f2015c-d48f-493a-adbc-3e45af37f653.png)

Expected behaviour
Command "amplify push" should work or maybe we made mistake in setup for  aws project
We need help

**Comment by fjnoyp** [comment]
Hi @nazarcybulskij thanks for sharing your issue.  As this is related to Amplify CLI let's move this issue to that repo.

**Comment by josefaidt** [comment]
Marking as a duplicate and closing in favor of tracking #9183
