### ISSUE TITLE
amplify mock not setting owner field on a GraphQL API create

### ISSUE THREAD

**Issue by michaelhutton** [aws-amplify/amplify-cli#9196]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.5.0

### Amplify CLI Version

7.6.1

### What operating system are you using?

Mac

### Amplify Categories

auth, api

### Amplify Commands

mock

### Describe the bug

Running `amplify mock` on a completely fresh project with `owner` auth rules does not set the owner field when creating a resource. The auth type being tested is `AMAZON_COGNITO_USER_POOLS`, via a GraphQL API.

The owner field gets set correctly when testing in the online AppSync environment, just not in the mocked environment.

### Expected behavior

The `owner` field gets set correctly in the locally mocked environment, as is does in the AppSync environment and in older versions of the CLI.

### Reproduction steps

1. Run `amplify init` on a new directory
2. Run `amplify add api`, choosing GraphQL, the simple "Todo" schema and choosing `AMAZON_COGNITO_USER_POOLS` as your auth strategy
3. Modify your schema to add owner auth rules via `@auth(rules: [{allow: owner}])`
4. Run `amplify mock` and the owner field does not get set correctly on a `createTodo` request
5. Doing an `amplify push` and testing exact same `createTodo` request on the AppSync environment sets the owner field correctly

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Todo @model @auth(rules: [{allow: owner}]) 
{
  id: ID!
  name: String!
  description: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by danielleadams** [comment]
Hi @michaelhutton, I believe this was fixed in https://github.com/aws-amplify/amplify-cli/pull/9192. Can you try updating to 7.6.2 and trying again?

**Comment by michaelhutton** [comment]
Just tested and you are correct, it's now working!
Thanks for the update 👍
