### ISSUE TITLE
Cannot read property 'deploymentBucketName' of undefined

### ISSUE THREAD

**Issue by johnf** [aws-amplify/amplify-cli#9197]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.18.0

### Amplify CLI Version

7.6.1

### What operating system are you using?

Ubuntu

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

When doing a push I am getting the following error

 An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot read property 'deploymentBucketName' of undefined

### Expected behavior

Push succeeds

### Reproduction steps

Can add more data later if needed. Not sure if my amplify-meta is in a broken state somehow or if this is related to the change

### Log output

<details>

```
TypeError: Cannot read property 'deploymentBucketName' of undefined
```

</details>

### Additional information

I think this is related to #9144, the error is occurring at https://github.com/aws-amplify/amplify-cli/blob/v7.6.1/packages/amplify-provider-awscloudformation/src/push-resources.ts#L1103

This is for a cognito auth lambda function.

amplify-meta.json doesn't have an s3Bucket section for this function but it does for my others

I manually added an s3Bucket section as a workaround

**Comment by akshbhu** [comment]
Hi @johnf 

can you try with latest cli version 7.6.2  and let us know if this issue still persists??

**Comment by johnf** [comment]
@akshbhu Seems to be working for me now thanks

**Comment by c0deWookiee** [comment]
I have CLI version 7.6.2 and the problem persists, can anyone advise?

**Comment by humarkx** [comment]
With the latest Amplify version 7.6.2, I still have this problem.

**Comment by johnf** [comment]
Reopening as now that I'm back in the office and testing with anger I still have this issue

**Comment by shackcrack007** [comment]
i have this issue to with the latest version

**Comment by mdarche** [comment]
Experiencing the same issue. Also experiencing this with 7.6.2 and using a Cognito Post Confirmation lambda function

**Comment by RichWK** [comment]
For anyone else hitting this error, I was able to work around it by downgrading Amplify CLI to 7.3.4. 👍🏼

**Comment by kylekirkby** [comment]
For anyone hitting these issues, I was able to get past the CLI error message by updating my numerous lambda functions that were not passing in the `deploymentBucketName` and `s3Key` parameters. The `Code` property of the lambda function will also need to be updated to reference the newly added params. 

So for a lambda function in `amplify/backend/function` check the "Parameters" section for the above keys. If they don't exist, add them and also update `Resources->LambdaFunction->Properties->Code` property to remove the hardcoded values. 

```json
 "Parameters": {
....
    "env": {
      "Type": "String"
    },
    "deploymentBucketName": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
```

and 

```json
 "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        ...
        "Code": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
        }
        ....
      }
    },
```

**Comment by 0xR** [comment]
I had the same issue with 7.6.2. Downgrading to 7.3.4 didn't work. I also tried the latest 6.x, 5.x and 4.x still the same issue.

It took a while to realise that although I ran `npm i -g @aws-amplify/cli` to update I was still using an older amplify version since amplify now lives in `~/.amplify`. To update I should have ran `amplify upgrade`.

7.6.3 solves the issue indeed.

**Comment by cjihrig** [comment]
I'm going to close this, as v7.6.3 should resolve the issue.
