### ISSUE TITLE
Renaming subscriptions in @model directive is completely broken

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-cli#9199]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.6.1

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When renaming subscriptions in graphQL `@model` directive, there are two bugs (I am using `amplify api gql-compile` command):
1. It generates garbage `type Subscription`
2. It does not generate Subscriptions vtl files.

Sample graphQL schema:

```
type Message
  @model(mutations: { create: "iCreateMessage", update: "iUpdateMessage", delete: "iDeleteMessage" }, subscriptions: { onCreate: "onICreateMessage" })
  @auth(rules: [
    { provider: iam, allow: private },
    { provider: userPools, allow: owner, ownerField: "owners", operations: [read] }
  ])
  {
    id: ID!
    createdAt: AWSDateTime!
    owners: [String]!
    chatId: ID! @index(name: "byChat", sortKeyFields: ["createdAt"])
    senderId: ID!
    text: String!
    status: MessageStatus!
    spamRating: Float
      @auth(rules: [
        { provider: iam, allow: private }
      ])
}

enum MessageStatus {
    new
    sent
    delivered
    read
}

input CreateMessageInput {
  id: ID
  createdAt: AWSDateTime
  owner: String!
  chatId: ID!
  senderId: ID!
  text: String!
  status: MessageStatus!
  spamRating: Float
  _version: Int
}

type Mutation {
  createMessage(args: CreateMessageInput!): Message
    @function(name: "createMessage-${env}")
    @aws_iam @aws_cognito_user_pools
}

type Subscription {
  onCreateMessage(owner: String): Message @aws_subscribe(mutations: ["createMessage"]) @aws_iam @aws_cognito_user_pools
}
```

A snippet of the generated graphQL schema with garbage type Subscription (it looks like it's generating one subscription for each letter of the new subscription name):

```
type Subscription {
  onCreateMessage(owner: String): Message @aws_subscribe(mutations: ["createMessage"]) @aws_iam @aws_cognito_user_pools
  o: Message @aws_subscribe(mutations: ["iCreateMessage"])
  n: Message @aws_subscribe(mutations: ["iCreateMessage"])
  I: Message @aws_subscribe(mutations: ["iCreateMessage"])
  C: Message @aws_subscribe(mutations: ["iCreateMessage"])
  r: Message @aws_subscribe(mutations: ["iCreateMessage"])
  e: Message @aws_subscribe(mutations: ["iCreateMessage", "iCreateMessage", "iCreateMessage", "iCreateMessage"])
  a: Message @aws_subscribe(mutations: ["iCreateMessage", "iCreateMessage"])
  t: Message @aws_subscribe(mutations: ["iCreateMessage"])
  M: Message @aws_subscribe(mutations: ["iCreateMessage"])
  s: Message @aws_subscribe(mutations: ["iCreateMessage", "iCreateMessage"])
  g: Message @aws_subscribe(mutations: ["iCreateMessage"])
}
```

All subscription vtl files are missing.

### Expected behavior

1. Subscriptions are renamed
2. Subscriptions vtl files are generated

### Reproduction steps

1. Create a basic Amplify project with api.
2. Use graphql schema above
3. Run `amplify api gql-compile`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
Thank you for reporting this. There are a few things going on here.

First, the value passed to `onCreate` should be an array, not a string. The validation in the CLI should be updated to catch this (unfortunately, the GraphQL spec allows this).

Second, the subscription VTL files are not generated. It looks like this issue existed in v1 of the transformer, so I'll need to look into that.

Here is the reduced schema I used for testing:

```graphql
type Message @model(subscriptions: { onCreate: "onICreateMessage" }) {
  id: ID!
}
```

**Comment by cjihrig** [comment]
PR for the array validation: https://github.com/aws-amplify/amplify-cli/issues/9199

**Comment by cjihrig** [comment]
@skryshi the VTL files not being generated are expected. You need to specify `level: on` when overwriting the default subscriptions.

**Comment by skryshi** [comment]
@cjihrig Ok, thanks that worked:

`@model(subscriptions: { onCreate: ["onCreateMessage1"], level: on })`

You ought to put this in the docs. How are we supposed to guess at the command syntax. Here:

https://docs.amplify.aws/cli/graphql/data-modeling/#rename-generated-queries-mutations-and-subscriptions

BTW, I don't get what the purpose of having an array is? It just generates identical subscriptions with different names.
