### ISSUE TITLE
[blogUserPoolId] do not exist in the template

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9203]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

The pull is working fine, but when I am doing some changes (even any comment in the code) and pushing, then it is failing.

```                         
UPDATE_FAILED               functionBlogbackendBlogTable                   AWS::CloudFormation::Stack Fri Dec 03 2021 21:34:59 GMT+0530 (India Standard Time) Parameters: [authBlogbackendUserPoolId] do not exist in the template                                                                                                   
UPDATE_FAILED               functionBlogbackendUserTable                   AWS::CloudFormation::Stack Fri Dec 03 2021 21:34:59 GMT+0530 (India Standard Time) Parameters: [authBlogbackendUserPoolId] do not exist in the template       
```

### Expected behavior

It should push the local changes to backend.

### Reproduction steps

1. I upgraded amplify cli to 7.6.2 earlier I think it was 7.5.2.
2. amplify pull
3. amplify push
4. ERROR

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @hackrx :wave: thanks for raising this! To clarify, are these functions custom resolvers for a GraphQL API, which have access to the auth resource?

**Comment by hackrx** [comment]
These functions are not custom resolvers, these are Dynamodb CRUD trigger functions, which have auth access.

**Comment by hackrx** [comment]
Thanks @josefaidt  for the hint, first I removed auth access from both of these functions, then I tried  `amplify push` and it worked.
