### ISSUE TITLE
Subscriptions are not sending data

### ISSUE THREAD

**Issue by irakli-g** [aws-amplify/amplify-cli#9218]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

nom

### If applicable, what version of Node.js are you using?

14.17.0

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, api

### Amplify Commands

push

### Describe the bug

I am using Amplify for my react native project. I am holding two of my phones next to each other logged in with two different accounts. I've opened a screen where users can post comments/replies. I am using subscriptions so that everyone can see real-time updates. Subscriptions are not working I can't see data on user X when I post comment with user Y.

Please note that I do receive data on user X when I make a comment as user X but user Y does not see it unless I reload.

For example onCreateGroupComment does work and it sends data back (I update redux state upon receiving updates from subscriptions) but others don't see the updates immediately they need to reload the screen...

My subscriptions
<img width="671" alt="Screenshot 2021-12-05 at 01 38 46" src="https://user-images.githubusercontent.com/70649220/144725361-55005837-aa28-4246-9d58-fce8af85b0b4.png">
<img width="548" alt="Screenshot 2021-12-05 at 01 39 28" src="https://user-images.githubusercontent.com/70649220/144725384-9e166e3a-fb5c-4964-89c3-b8d6e2d92a70.png">

### Expected behavior

Users should see real-time updates when someone pots a comment/reply.

### Reproduction steps

1. Amplify init
2. add api, auth (with unauthenticated logins), storage
3. add graphql schema
4. amplify push
5. remove excess properties in subscriptions.ts. e.g, onCreateGroupComment also had a group object attached to it which I don't use
6. Subscribe to real-time updates showing in code example images

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Group
    @model(subscriptions: null)
    @auth(
        rules: [ 
            { allow: owner},
            { allow: private, operations: [read, update] }
         ]
    ) {
    id: ID!
    owner: String!
    members: [String]!
    title: String!
    description: String!
    files: [File]!
    comments: [GroupComment] @hasMany
    tasks: [GroupTask] @hasMany
    meetingLink: String
    createdAt: AWSDateTime!
    updatedAt: AWSDateTime
}

type GroupComment
    @model
    @auth(
        rules: [
            { allow: owner },
            { allow: private, operations: [read, update] }
        ]
    ) {
    id: ID!
    owner: String!
    content: String!
    groupId: String! @index(name:"groupCommentsByDate",queryField:"groupCommentsByDate", sortKeyFields:["createdAt"])
    group: Group @belongsTo
    replies: [GroupReply] @hasMany
    likes: [Like]!
    createdAt: AWSDateTime!
    updatedAt: AWSDateTime
}

type GroupReply
    @model
    @auth(
        rules: [
            { allow: owner },
            { allow: private, operations: [read, update] }
        ]
    ) {
    id: ID!
    owner: String!
    content: String!
    commentId: String! @index(name:"groupRepliesByDate",queryField:"groupRepliesByDate", sortKeyFields:["createdAt"])
    comment: GroupComment @belongsTo
    likes: [Like]!
    createdAt: AWSDateTime!
    updatedAt: AWSDateTime
}

type GroupTask  @model @auth(rules: [{ allow: owner }, { allow: private }]) {
    id: ID!
    owner: String!
    task: String!
    assignees: [String]!
    steps: [Step]!
    type: String!
    files: [File]!
    dueDate: String!
    reminder: Int!
    status: String!
    groupId: String!
    group: Group @belongsTo
    notificationId: String
    createdAt: AWSDateTime!
    updatedAt: AWSDateTime
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by irakli-g** [comment]
Hi, @yuth  the owner filed is the username of the currently logged-in user. This field did not exist in subscriptions before the update to transformer V2 and everything was just fine... everyone was receiving real-time data.

Why would I need custom resolvers now? I thought it was supposed to be pretty straightforward as it was in transformer V1 where everything worked great regarding subscriptions.

**Comment by irakli-g** [comment]
This is the error I get if I remove the owner field from a subscription.

<img width="1363" alt="Screenshot 2021-12-08 at 10 07 04" src="https://user-images.githubusercontent.com/70649220/145157100-9af40720-6b14-4f0c-8b44-e4dca380c047.png">

**Comment by irakli-g** [comment]
I see now. This is what I tested.
<img width="486" alt="Screenshot 2021-12-08 at 19 43 15" src="https://user-images.githubusercontent.com/70649220/145238100-93642fca-85df-4b79-8663-17da09e7ca0e.png">

<img width="772" alt="Screenshot 2021-12-08 at 19 43 30" src="https://user-images.githubusercontent.com/70649220/145238107-755d7d61-e6af-4c24-88b1-f15a043b1a0b.png">

Now users who are currently viewing that particular group do receive updates on comment creation. I assume I can do the same on comment edit/delete but in this case, instead of groupId it would be better to provide commented and add subscription on a comment level for edit/delete not on a group level because you might delete/edit a comment which user looking at that particular group has not loaded yet.

**Comment by yuth** [comment]
> This field did not exist in subscriptions before the update to transformer V2 and everything was just fine... everyone was receiving real-time data.

Could you share the schema before the v2 migration. Before/after schema would be helpful to figure out why the subscription stopped working

**Comment by irakli-g** [comment]
This is how the generated subscriptions.ts looked like before v2. There was no requirement for providing owner parameter.

<img width="741" alt="Screenshot 2021-12-10 at 22 41 10" src="https://user-images.githubusercontent.com/70649220/145625202-f54f3854-6bf0-4618-aa41-1a60b98afec3.png">

**Comment by yuth** [comment]
Schema would be more helpful as it contains auth rules

**Comment by irakli-g** [comment]
```
type Group
	@model(subscriptions: null)
	@auth(
		rules: [
			{ allow: owner }
			{ allow: groups, groups: ["Admin"] }
			{ allow: private, operations: [update, read] }
		]
	) {
	id: ID!
	owner: String!
	ownerPicture: String!
	ownerFirstName: String!
	ownerLastName: String!
	members: [String]
	title: String!
	description: String!
	files: [File]!
	comments: [GroupComment]! @connection(name: "GroupComments")
	tasks: [GroupTask]! @connection(name:"GroupTasks")
	meetingLink: String
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime
}

type GroupComment
	@model
	@key(name: "groupCommentsByDate", fields: ["groupCommentGroupId", "createdAt"], queryField: "groupCommentsByDate")
	@auth(
		rules: [
			{ allow: owner }
			{ allow: groups, groups: ["Admin"] }
			{ allow: private, operations: [read, update] }
		]
	) {
	id: ID!
	owner: String!
	ownerPicture: String!
	ownerFirstName: String!
	ownerLastName: String!
	ownerUniversity: String!
	content: String!
	groupCommentGroupId: String!
	group: Group @connection(name: "GroupComments")
	replies: [GroupReply]! @connection(name: "GroupCommentReplies")
	audio: String
	likes: [Like]!
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime
}

type GroupReply
	@model
	@key(name: "groupRepliesByDate", fields: ["groupReplyCommentId", "createdAt"], queryField: "groupRepliesByDate")
	@auth(
		rules: [
			{ allow: owner }
			{ allow: groups, groups: ["Admin"] }
			{ allow: private, operations: [read, update] }
		]
	) {
	id: ID!
	owner: String!
	ownerPicture: String!
	ownerFirstName: String!
	ownerLastName: String!
	ownerUniversity: String!
	content: String!
	receiver: String!
	groupReplyCommentId: String!
	groupComment: GroupComment @connection(name: "GroupCommentReplies")
	audio: String
	likes: [Like]!
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime
}

type GroupTask 	@model @auth(rules: [{ allow: owner }, { allow: groups, groups: ["Admin"] }, { allow: private, operations: [read, update] }]) {
	id: ID!
	owner: String!
	task: String!
	assignees: [String]!
	steps: [Step]!
	type: String!
	files: [File]!
	dueDate: String!
	reminder: Int!
	status: String!
	groupTaskGroupId: String!
	group: Group @connection(name:"GroupTasks")
	notificationId: String
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime
}
```
