### ISSUE TITLE
Dynamic Group Authorization with single Group not working

### ISSUE THREAD

**Issue by n0rb** [aws-amplify/amplify-cli#9220]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.9.1

### Amplify CLI Version

7.6.2

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Dynamic Group Authorization with single Group (groupsField -> group: String) does not work as described here
https://docs.amplify.aws/cli-legacy/graphql-transformer/auth/#dynamic-group-authorization

The query response is empty, although the User has the correct group memberships to list items.

### Expected behavior

The API should respond with a list of items where the appropriate groupsField value is set to a group of the user context

### Reproduction steps

1. amplify add api
2. define schema like described below
3. test api with amplify mock api, open appsync mock endpoint in browser
4. in mock endpoint, click update auth , add "Admin" to groups
5. fill mockup data with a few requests `mutation MyMutation {
  createPost(input: {title: "asdf", group: "TESTGROUP"}) {
    id
  }
}`
6. update auth again, remove "Admin" from groups, add "TESTGROUP" to groups
7. do a query `query MyQuery2 {
  listPosts {
    items {
      id
      title
    }
  }
}`
8. the response will be empty `{
  "data": {
    "listPosts": null
  }
}`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Post @model 
@auth(rules: [
{ allow: groups, groups: ["Admin"] }
{ allow: groups, groupsField: "group" }
])
 {
  id: ID!
  title: String
  group: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

the functionality is fine when the group field is an array `group: [String]` ie multiple group implementation.

the issue is probably the resolver when using a single String groupsField, as it is using a authFiler with in: ["AAA", "BBB"] `$util.qr($authFilter.add({ "group": { "in": $role0 } }))`

**Comment by sundersc** [comment]
Hi @n0rb I'm unable to reproduce this issue. Based on the docs link, I assume you are using v1 version of the graphql transformer. Can you confirm what does the below feature flags look like in `cli.json` file?
```json
"useexperimentalpipelinedtransformer"
"transformerversion"
```

**Comment by cjihrig** [comment]
@n0rb did the previous comment

**Comment by n0rb** [comment]
> ```json
> useexperimentalpipelinedtransformer
> ```

sorry @sundersc I kind of missed your response, sorry for the late reply.
here is the requested info from amplify/cli.json

```
"useexperimentalpipelinedtransformer": true,
"transformerversion": 2,
```

**Comment by sundersc** [comment]
@n0rb - I've tested v2 transformer through AppSync console, it seems to be working as expected. I'm going to try in mock api. Are you sure that the consecutive calls are not using the same user session?

**Comment by n0rb** [comment]
@sundersc I refreshed the mock page if thats what you mean and changed the User Token via the "Update Auth" Button and "Generate Token". I didn't test further in the cloud/AppSync because of the issue. So it could be a mock problem if it works for you on AppSync

**Comment by sundersc** [comment]
Thanks for reporting this issue. I can confirm that this is a bug with the mock api functionality. We will look into this.
