### ISSUE TITLE
Parameters are empty after amplify build for RestApi

### ISSUE THREAD

**Issue by csilvacaio** [aws-amplify/amplify-cli#9221]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
API Gateway

**Amplify CLI Version** 
You can use `amplify -v` to check the amplify cli version on your system
Version: 7.6.2

**What AWS Services are you utilizing?**
Cognito
RestApi

**Provide additional details e.g. code snippets**
I'm trying to override an API Rest defined through Amplify. I need to define Cognito as the auth method for this API.
I have the following code inside my `override.ts` file that defines the parameter that I will need.
```
resources.addCfnParameter(
    {
      type: 'String',
      description:
        'The id of an existing User Pool to connect. If this is changed, a user pool will not be created for you.',
      default: 'None',
    },
    'AuthCognitoUserPoolId'
  )
```

My parameters.json file is like this:
```
{
  "AuthCognitoUserPoolId": {
    "Fn::GetAtt": ["authMyAuth", "Outputs.UserPoolId"]
  }
}
```

The problem that I'm facing is that after executing the `amplify build` the `parameters.json` file in the same level of `override.ts` is erased, and the `parameters.json` inside the build folder is also empty. In the end, the expected value for the parameter is not defined. What am I missing?

**Comment by jhockett** [comment]
Hi @csilvacaio, I have a fix in progress, but I don't know when it will be released. 

As a workaround, you can assign the intrinsic function to default:
```ts
resources.addCfnParameter(
    {
      type: 'String',
      description:
        'The id of an existing User Pool to connect. If this is changed, a user pool will not be created for you.',
      default: {
        "Fn::GetAtt": ["authMyAuth", "Outputs.UserPoolId"]
      },
    },
    'AuthCognitoUserPoolId'
  )


```

**Comment by csilvacaio** [comment]
Thanks for the workaround @jhockett .
I remember that I tried something similar to that but it didn't work. I will try again now based in your example.

**Comment by jhockett** [comment]
@csilvacaio my mistake, that doesn't actually work. You cannot set the default value to an intrinsic function.

**Comment by csilvacaio** [comment]
Hey @jhockett, I saw that your PR got the approvals. Does that mean a release soon? :sweat_smile:

**Comment by jhockett** [comment]
Hi @csilvacaio apologies for the wait, but the PR has been released!

After you upgrading to the latest version of @aws-amplify/cli-extensibility-helper in your package.json (`^2.3.9` at time of writing) you can do something like:

```ts
export function override(resources: AmplifyApiRestResourceStackTemplate) {
  resources.addCfnParameter(
    {
      type: 'String',
      description: 'Test parameter'
    },
    'DESCRIPTION',
    'Description has been overridden',
  );
  
  resources.restApi.description = { 'Ref': 'DESCRIPTION' };
}
```

Closing this issue, comment below if you have feedback and we can re-open if needed. Thank you for your patience!
