### ISSUE TITLE
Invalid KeyConditionExpression

### ISSUE THREAD

**Issue by franklin113** [aws-amplify/amplify-cli#9222]
**Which Category is your question related to?**
API

**Amplify CLI Version** 
7.6.2, Transformer v2

**What AWS Services are you utilizing?**
Amplify Mock, Dynamo DB

**Provide additional details e.g. code snippets**
I am attempting to mock my graphql api and am receiving errors related to Dynamo DB on all my queries.  

Here's my model that I'm running amplify generated queries on:
```

type User
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["admin"] }
      { allow: owner, ownerField: "id", operations: [read] }
    ]
  ) {
  id: ID!
  first_name: String
  last_name: String
  email: String!
  isAdmin: Boolean
}

```

```
Error while executing Local DynamoDB
{
    "version": "2018-05-29",
    "limit": 100,
    "operation": "Query",
    "query": {
        "expression": "${modelQueryExpression.expression} AND #id = :asdfasdf3jpo323 AND #id = :asdfasdf3jpo323"
    },
    "scanIndexForward": true
}
ValidationException: Invalid KeyConditionExpression: Syntax error; token: "$", near: "${"
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
```

Has anyone seen this error, and how did they get around it?

**Comment by franklin113** [comment]
I reverted back to version 1 of the transformer and it appears to be working now.  I'm not sure if this is a bug in v2 or if I need to update something else to get it to work.

cli.json
```
"transformerversion": 1,
"useexperimentalpipelinedtransformer": false,
```

**Comment by lazpavel** [comment]
PR reverted due to new issue: https://github.com/aws-amplify/amplify-cli/issues/9560
