### ISSUE TITLE
Cannot read property 'deploymentBucketName' of undefined

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#9223]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I updated to 7.6.2 from 7.5.5 and am getting the following error on push: 

An error occurred during the push operation: Cannot read property 'deploymentBucketName' of undefined

It seems duplicate of https://github.com/aws-amplify/amplify-cli/issues/9197 except it's happening with 7.6.2

### Expected behavior

amplify push should work 

### Reproduction steps

Upgrade to 7.6.2 and push - not sure what triggers the issue in my stack. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hisham** [comment]
I reverted to 7.5.5 and amplify push works again.

**Comment by lacek** [comment]
Got the same issue with 7.6.2 when pushing specific resource (e.g. `amplify api push`, `amplify function push <function_name>`). Reverted to 7.5.5 and no more error.

**Comment by humarkx** [comment]
Amplify 7.6.2 same problem with deploymentBucketName

**Comment by ryanhollander** [comment]
same

**Comment by Straubulous** [comment]
Fixed in7.6.3
