### ISSUE TITLE
Cannot deploy from "set up > data" in Amplify Studio

### ISSUE THREAD

**Issue by isaacrowntree** [aws-amplify/amplify-cli#9224]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

14.18.2

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

I have a bunch of functions which I've deployed, along with an API:

![Screen Shot 2021-12-06 at 10 22 13 pm](https://user-images.githubusercontent.com/11435437/144837608-b00873e6-58f8-43af-b902-7d2ce1534664.png)

In amplify studio I get this error when I try to run `Save and Deploy` from the Amplify Studio UI (appid d26seotyr25w3q):

`Command failed with exit code 1: /root/.amplify/bin/amplify push --yes --allow-destructive-graphql-schema-updates ⚠️ Amplify command hooks are disabled in the current execution environment. ⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information. [31mAn error occurred pushing an env "dev" due to missing environment variable values[39m. `

### Expected behavior

All I want to do is get the Content editor running. Any ideas? 

### Reproduction steps

1. Create a heap of functions and an api with auth
2. Cognito user pool set as default auth method
3. Conflict resolution recommended mode

### GraphQL schema(s)

I've got a big graphql schema but I don't want to put it here.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @isaacrowntree 

we currently dont support functions with environment variables inn amplify studio.
this link might be able to help you better : https://github.com/aws-amplify/amplify-adminui/issues/332#issuecomment-964380483
