### ISSUE TITLE
amplify push fails after upgrading to cli 7.6.2

### ISSUE THREAD

**Issue by vikaskgahlawat** [aws-amplify/amplify-cli#9225]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.2

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

>amplify push
? Are you sure you want to continue? Yes
√ A migration is needed to support latest updates on api resources.
Recommended to try in a non-production environment first. Run "amplify env add" to create or clone an environment.
Learn more about this migration: https://docs.amplify.aws/cli/migration/override
Do you want to migrate api resource "resources"? (Y/n) · yes

× An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot read properties of undefined (reading 'forEach')

Before saying "yes" to the migration step, there were api-params.json and parameters.json files under the existing resources.
After running this command all the api-params.json and parameters.json files are deleted and the command itself fails with the above message.
It even deletes the cloud formation templates which were customized as per requirements.

After this I uninstalled amplify cli and installed version 6.4.0 and took a fresh git clone.
Everything worked fine with 6.4.0 version of amplify cli.
![DeletedItems](https://user-images.githubusercontent.com/64056565/144838662-5a77a034-52d0-42d1-8bc4-c1b86b750e1c.JPG)

### Expected behavior

Amplify push should create the resources in the cloud without any error.

### Reproduction steps

Create amplify project with amplify version < 7.
Add API to the project.
Customize the API's cloud formation template to add a custom authorizer or to covert it to a web socket API.
Run Amplify push. It runs successfully.
Upgrade amplify to the latest version.
Make any change in the API. For eg., change a description in the cloud formation template.
Again run Amplify Push.
It gives the error mentioned above.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment]
@vikaskgahlawat could you include the snippet you used to customized the template?

**Comment by vikaskgahlawat** [comment]
Sure @attilah Please find attached two cloud formation templates. I am still trying to understand how can amplify push delete the api-params.json and parameters.json files.
[authProviderRestAPI-cloudformation-template.txt](https://github.com/aws-amplify/amplify-cli/files/7665370/authProviderRestAPI-cloudformation-template.txt)
[dataProviderWebSocket-cloudformation-template.txt](https://github.com/aws-amplify/amplify-cli/files/7665372/dataProviderWebSocket-cloudformation-template.txt)

**Comment by attilah** [comment]
@vikaskgahlawat we silently migrate to `cli-inputs.json` from those two files, that's why those are getting deleted. Thanks for the templates I'm looking into it.

**Comment by attilah** [comment]
@vikaskgahlawat could you check if ANY of your `api-params.json` is only an empty object?
Is the total number of APIs you have is 6 in the project?

**Comment by vikaskgahlawat** [comment]
@attilah There are a total of 9 APIs including the AdminQueries which doesn't have an api-params.json file. I just noticed that out of the remaining 8, 2 still have api-params.json and parameters.json file. So it deleted for only 6 APIs.
Also, none of the api-params.json is only an empty object but two of the parameters.json files were empty objects.

**Comment by attilah** [comment]
it is "good news", as it means that the migration is failing and it is an existing issue. Let me ping @jhockett to see he can provide a workaround!

**Comment by tomhirschfeld** [comment]
we have the same issue

+1

**Comment by jhockett** [comment]
Hi @vikaskgahlawat, the `parameters.json` being empty is fine. Did the remaining `api-params.json` files have a paths array defined with at least one entry?

The migration flow doesn't take custom CloudFormation changes into account. I will update the migration message to make that more clear and make the migration logic more robust. 

After migration, REST APIs have new overrides functionality for customizing the CloudFormation template using types from the CDK: https://docs.amplify.aws/cli/restapi/override/

**Comment by jhockett** [comment]
@tomhirschfeld do you have any REST APIs (excluding Admin Queries) with an `api-params.json` that do not define paths for the API?

**Comment by vikaskgahlawat** [comment]
@jhockett Not all. The one that I customized to be a websocket API does not have a path array defined in the api-params.json

**Comment by jhockett** [comment]
@vikaskgahlawat that's why the migration failed. It doesn't handle custom changes to `api-params.json`. The workarounds available are either continue to use the older version or you can implement the same custom changes with the new overrides workflow.

I have a PR to address some of the sharp corners, but it doesn't solve everything: https://github.com/aws-amplify/amplify-cli/pull/9267

**Comment by vikaskgahlawat** [comment]
Thanks, @jhockett. Although I have a lot of customizations that I will have to incorporate in the new override workflow my concern now is: Is there any other feature in progress/plan that can again bring such breaking changes. So if I use this new override workflow and customize my APIs as per my needs, can a new version stop supporting this override workflow or does not provide the backward compatibility of this override workflow.

**Comment by jhockett** [comment]
Apologies for the inconvenience @vikaskgahlawat. We don't plan on making any breaking changes to the override workflow. I'm also working on a fix to prevent the migration on push from being needed to avoid breaking anyone with custom changes.

**Comment by vikaskgahlawat** [comment]
One more question @jhockett If I continue to use the old version of amplify cli and develop the application with those standards, won't it break when AWS Amplify pull the latest code from the codecommit repo and try to setup the backend environment.

**Comment by jhockett** [comment]
@vikaskgahlawat if you're using CI/CD through Amplify Console, you can pin the CLI version to match what you are using locally in the settings.

**Comment by vikaskgahlawat** [comment]
@jhockett Any idea why amplify push is deleting the api-params.json files? There are two strange behaviors.
1. For the existing APIs there were api-params.json files. With the latest version of amplify, when I do amplify push, it deletes the api-params.json files and then give error that the api-params.json does not exist.
2. In the same code, I added a new api with the latest version of amplify. It created a directory for the api but did not create an api-params.json file. Assuming this is the way new APIs should be created, I ran amplify push. Along with the old APIs, it gave error for the new API as well that the api-params.json.

I am not sure if it makes sense, but here is the version of aws cli that I use.
aws-cli/2.0.50 Python/3.7.7 Windows/10 exe/AMD64

and the version of amplify cli is: 7.6.7

Unfortunately, everything was working fine on my colleage's machine and he happened to create new APIs using the new version of amplify. So now I can't even proceed further using the old version of amplify because that won't support the APIs created with the new version. Because the folder structure is different in version 6 and 7 of amplify.

**Comment by Artur112** [comment]
How is this new overrides feature in any way better than what amplify v6 had? For example, as amplify only creates the ANY method for APIs having the ability to manually edit the API cloudformation template made it easy to get the exact methods I want. I tried updating and migrating to v7 but seeing that this removes the cloudformation template I reverted back.
