### ISSUE TITLE
amplify v7.5.5 push fails with: "Parameters: [analyticsEssPinpointId, analyticsEssPinpointRegion] do not exist in the template" after override migration

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#9232]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

7.5.5 - I'm unable to install latest due to https://github.com/aws-amplify/amplify-cli/issues/9223

### What operating system are you using?

Mac

### Amplify Categories

analytics

### Amplify Commands

push

### Describe the bug

I'm trying to do amplify push, and the thing prompts me to do the override migration, which I select yes for. The push then fails with:

UPDATE_FAILED      functionEssDynamoStreamFn       AWS::CloudFormation::Stack Mon Dec 06 2021 11:29:17 GMT-0700 (Mountain Standard Time) Parameters: [analyticsEssPinpointId, analyticsEssPinpointRegion] do not exist in the template

### Expected behavior

amplify push should work

### Reproduction steps

Is it a pinpoint specific issue? I don't know. And I'm unable to see if latest cli fixes this due to https://github.com/aws-amplify/amplify-cli/issues/9223 where push also fails there. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @hisham 

Apologies for the incovenience. We have a PR which will fix the deployment bucket issue : https://github.com/aws-amplify/amplify-cli/pull/9215

For the other issue , I am investigating it.

If possible can you send your amplify folder after redacting any secret info from it.

**Comment by hisham** [comment]
Sure I just sent it to amplify-cli@amazon.com thanks!

**Comment by akshbhu** [comment]
Hi @hisham 

It seems like a problem with ```EssDynamoStreamFn```. According to ```amplify-meta.json``` , this function dependsOn analytics but if you check ```function parameters.json``` for this , this function itself doesn't know  it depends on analytics.

**function-parameters.json**
```
  "permissions": {
    "api": {
      "randomAPI": [
        "create",
        "read",
        "update",
        "delete"
      ]
    },
    "auth": {
      "randomauth": [
        "read"
      ]
    },
    "storage": {
      "randomstorage": [
        "create",
        "read",
        "update"
      ]
    }
  },
```
As you can see analytics is missing and its present in ```amplify-meta.json```.
```
    "RandomFn": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "api",
          "resourceName": "randomAPI",
          "attributes": [
            "GraphQLAPIIdOutput",
            "GraphQLAPIEndpointOutput"
          ]
        },
        {
          "category": "auth",
          "resourceName": "randomauth,
          "attributes": [
            "UserPoolId"
          ]
        },
        {
          "category": "storage",
          "resourceName": "randostorage",
          "attributes": [
            "BucketName"
          ]
        },
        {
          "category": "analytics",
          "resourceName": "randomanalytics",
          "attributes": [
            "Id",
            "Region"
          ]
        },
        {
          "category": "function",
          "resourceName": "randomlayer",
          "attributes": [
            "Arn"
          ]
        }
 
```

For the workaround , Can you go to ```amplify update function``` and try giving this function access to analytics . 

If it was working before , can you also check if this function was depending on analytics (check in ```function-parameters.json```) before in  #current-cloud-backend.

Ill also try to reproduce this from an older version with its a regression?

**Comment by akshbhu** [comment]
yes , Just try removing the section from ```backendConfig.json``` and ```amplifyMeta.json``` and try push again?

**Comment by hisham** [comment]
yes I ended up removing the analytics dependsOn for EssDynamoStreamFn from amplify-meta.json, and the push now worked.

**Comment by akshbhu** [comment]
Good to know it worked.
Closing this issue , if you get stuck on it again , feel free to ping and ill reopen this again
