### ISSUE TITLE
Generated GraphQL declarations not written to project config source directory

### ISSUE THREAD

**Issue by sohara** [aws-amplify/amplify-cli#924]
**Describe the bug**
It appears that the generated GraphQL declarations are always written to a directory called `src` instead of respecting the `sourceDir` config attribute that appears in `amplify/project-config.json`. This is a nested config attribute under `javascript.config`.

Steps to reproduce the behaviour:
1. Create a new amplify js project
2. Choose e.g. the Ember framework option (which defaults to `app` for `sourceDir`) or manually enter `app` at the prompt.
3. Add the `api` category and create a GraphQL schema (default one should be fine)
4. See that the generated queries, mutations, subscriptions and schema files are written to `src/graphql` instead of `app/graphql`

**Expected behaviour**
Since we've declared that source files live in `app` we would expect the graphql files to also live there.

**Comment by kaustavghosh06** [comment]
This is a duplicate issue and we're tracking it as a part of #916.
