### ISSUE TITLE
Failed to create models in the cloud: Modelgen job creation failed

### ISSUE THREAD

**Issue by NiklasReinhold** [aws-amplify/amplify-cli#9243]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

v7.6.2

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Hello, 

I get the error message "Failed to create models in the cloud: Modelgen job creation failed" when I do "amplify push". 

Therefore I have a problem with building the Datastore Models for the cloud. 
It does not work with amplify push or on AmplifyStudio/Datastore/Save&Deploy. 

Behaviour: 
Now the AppSync does not sync anymore and I can't watch the AmplifyStudio/Content. 

### Expected behavior

Usually on amplify push (on api changes) the models in the cloud should be created. 
No errormessage should be shown. 

### Reproduction steps

To recreate: everytime I do "amplify push" or AmplifyStudio/Data/Save&Deploy

![2](https://user-images.githubusercontent.com/29887205/145042982-4df6228e-e01c-4913-a8ad-a2671eb5a542.png)
![1](https://user-images.githubusercontent.com/29887205/145042990-f08d613c-60c4-48b8-b5fd-e0da9d64bc88.png)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Invoice @model @auth(rules: [{allow: owner}, {allow: public}, {allow: groups, groups: ["admin"], operations: [read, create, update, delete]}]) {
  id: ID!
  totalGrossAmount: Float!
  totalRemononAmount: Float!
  totalRefund: Float!
  totalNetAmount: Float!
  monthOfUse: Int!
  yearOfUse: Int!
  nf1ID: String!
  createdAt: AWSDateTime
  owner: String!
  totalRemononFee: Float!
  fileKey: String
}

enum Status {
  ACCEPTED
  INREVIEW
  REJECTED
}

type ReceiptLineItem @model @auth(rules: [{allow: owner}, {allow: public}, {allow: groups, groups: ["admin"], operations: [read, create, update, delete]}]) {
  id: ID!
  passedCheck: Boolean
  ocr_ProductCode: String
  ocr_Quantity: Float
  ocr_VatPercentage: Float
  ocr_NetLineTotal: Float
  ocr_GrossLineTotal: Float
  ocr_ProductName: String
  remononFee: Float
  owner: String!
  receiptID: String!
}

type Receipt @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["admin"], operations: [read, create, update, delete]}, {allow: public, operations: [create, read, update]}]) {
  id: ID!
  uploadDate: AWSDateTime!
  fileKey: String!
  status: Status!
  passedCheck: Boolean
  ocr_NetAmount: Float
  ocr_VatNumber: String
  ocr_TaxNumber: String
  ocr_Date: AWSDate
  ocr_MerchantStreet: String
  ocr_MerchantCity: String
  ocr_MerchantPostcode: Int
  ocr_PaymentMethod: String
  ocr_TotalAmount: Float
  ocr_MerchantName: String
  ocr_DocumentID: String
  ocr_ErrorMessage: String
  remononFee: Float
  nf1ID: String
}

type NF1 @model @auth(rules: [{allow: owner}, {allow: public, operations: [create, read, update]}, {allow: groups, groups: ["admin"], operations: [read, create, update, delete]}]) {
  id: ID!
  fileKey: String!
  monthOfUse: Int!
  yearOfUse: Int!
  imageStatus: Status
  orderformStatus: Status
  ocr_ValidUntil: AWSDate
  ocr_IsOfficialPurchasingAgent: Boolean
  ocr_DesignatedAgent: String
  ocr_AuthorizedFamilyMember: String
  ocr_OfficiersName: String
  ocr_OrderNr: String
  ocr_ValidFrom: AWSDate
  ocr_procurementAgency: String
  usGarrison: UsGarrison
  rejectedReason: String
  receivingAgency: String
  uploadedImages: Int
}

type UserProfile @model @auth(rules: [{allow: owner}, {allow: public, operations: [create, read, update]}, {allow: groups, groups: ["admin"], operations: [read, create, update, delete]}]) {
  id: ID!
  firstName: String
  middleName: String
  lastName: String
  birthdate: AWSDate
  zipCode: String
  city: String
  bankAccountType: BankAccountType
  iban: String
  bic: String
  bankName: String
  bankOwner: String
  cognitoUserID: String!
  fullStreetAddress: String
  createdAt: AWSDateTime
  cognitoFileID: String
  adminVerified: Status!
  wantsVerification: Boolean
  militaryRank: String
  boxAddress: String
  postOfficeAddress: String
  rejectedReason: String
  bankUserFullName: String
  bankUserAddress: String
  accountNumber: Int
  typename: String @index(name: "byAccountNumber", queryField: "itemsByAccountNumber", sortKeyFields: ["accountNumber"])
  onboarded: Boolean
}

enum UsGarrison {
  Grafenwoehr
  Stuttgart
}

enum BankAccountType {
  US
  EU
}


```

</details>

### Log output

<details>

```
# Output of the Cli on updating: (everything fine, update complete until:)
... 
UPDATE_COMPLETE amplify-remononapp-staging-162830 AWS::CloudFormation::Stack Tue Dec 07 2021 14:38:27 GMT+0100 (Mitteleuropäische Normalzeit)
Failed to create models in the cloud: Modelgen job creation failed
√ All resources are updated in the cloud

GraphQL endpoint: https://jqf4xeviejgolgz6tqc7iaz5fi.appsync-api.eu-central-1.amazonaws.com/graphql
GraphQL API KEY: da2-ulkpte43nzhtfovl3uulmn7fby

```

</details>

### Additional information

Thanks!

**Comment by akshbhu** [comment]
hi @NiklasReinhold 

I think the main issue here is hydrating env variables during deploy stage  as you can see the error above in the image.

Do you have function env variables in your project? . if yes , then can you try deploying locally with cli using ```amplify push```. This command will prompt the env variables filling during push .

We are tracking similar error here: https://github.com/aws-amplify/amplify-cli/issues/8111

if you want more info to workaround this , you can check this: https://github.com/aws-amplify/amplify-adminui/issues/332#issuecomment-964380483

Regarding this error: Failed to create models in the cloud: Modelgen job creation failed

This doesn't stop the deploy and creates the model if you run it locally and we are also tracking this issue to resolv this quickly.

**Comment by NiklasReinhold** [comment]
Hi @akshbhu 

You were right, the main issure was one env variable in one lambda function. 
When I removed the env variable it worked!

Ps: amplify push did not work with env variable, only without too. 

Thank you very much!

**Comment by NiklasReinhold** [comment]
@akshbhu 
Overview: The save&deploy in the AmplifyStudio works & I can see the Content. 

It remains that "amplify push" drops this error: 
![image](https://user-images.githubusercontent.com/29887205/145214157-3b2f22d8-31de-4132-91f8-9a76a8d82a2a.png)

The unexpected behaviour I have is the remaining "Outbox Mutation Failed Event" for the sync of one class of our schema. 
![image](https://user-images.githubusercontent.com/29887205/145214385-a89ece96-6e24-4973-80ca-849ec7fa1f23.png)

Any Idea?

**Comment by NiklasReinhold** [comment]
I've found this: 
![image](https://user-images.githubusercontent.com/29887205/145257454-ab546eee-7294-49dd-89b5-8170714b85fa.png)

**Comment by lazpavel** [comment]
Hi @NiklasReinhold, can you provide the output for `amplify status`

**Comment by NiklasReinhold** [comment]
@lazpavel This is the output for amplify status. The same as usual: 
![image](https://user-images.githubusercontent.com/29887205/145359994-6f57312c-a05b-4b7d-8420-8ca19b3e770a.png)

**Comment by lazpavel** [comment]
Hi @NiklasReinhold 

The error `The security token included in the request is invalid` seems to be a common error when the AWS credential does not has the required permission. Do any of your functions require access to other resources? Can you check that the permissions are valid?

**Comment by NiklasReinhold** [comment]
Hi @lazpavel Yes indeed, somehow my logged my Account (Aws Admin) had not enough rights. Or I missed something. 
I used amplify configure to recreate a new account and now the push works with the cloud-build of models. 

I would love to close the issue and use the app in productive. 
Sadly I'm not yet ready

This Bug without an error-Description brings me trouble: 
![MicrosoftTeams-image2](https://user-images.githubusercontent.com/29887205/145813214-02e87860-ec15-4344-933f-a105fc849b23.png)

Do you have any idea on how to find the error-source or how to fix this?

**Comment by lazpavel** [comment]
Hi @NiklasReinhold, I don't see a `test` field in the `UserProfile` can you re-run `amplify codegen models`
