### ISSUE TITLE
Ability to define Time To Live for a dynamo DB table 

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-cli#926]
**Is your feature request related to a problem? Please describe.**
Using amplify-cli, we should minimize the manual setup needed in the Aws console when deploying a schema. It's a pain to go to each model where TTL is needed to set it up manually.

**Describe the solution you'd like**
It would be great to define this in the graphQL schema : 
```
type StreamDataThatHasATTL @model {
    id: ID!
    data: String
    ttl: Int! @ttl
}
```

**Comment by timoteialbu** [comment]
This would be useful for us too, as that would get rid of some logic we have in our app to remove rows that are older than X time

**Comment by mikeparisstuff** [comment]
This would be a great use case for a custom transformer. See #1396.

**Comment by zjullion** [comment]
@mikeparisstuff Would a custom transformer do the trick here? My understanding is that custom transformers allow you to write custom response + request VTL templates, whereas enabling TTL is strictly about modifying the Dynamo table itself (ideally via cloudformation).

**Comment by zjullion** [comment]
@kaustavghosh06 Can you provide any update on this?

**Comment by zjullion** [comment]
@UnleashedMind ? @yuth ?

**Comment by zjullion** [comment]
@brene ?

**Comment by amuresia** [comment]
+1

**Comment by dialnco** [comment]
Hi! Any sign of update on this?

**Comment by realityfilter** [comment]
This would really be great. Is there a possibility to configure this in other places in the source code?

**Comment by DennisWanjiru** [comment]
This would minimize the amount of logic that one writes to handle the same.

**Comment by avlonder** [comment]
Was somebody able to write a custom @ttl transformer?

**Comment by CharanRoot** [comment]
any update ??

**Comment by techdragon** [comment]
@avlonder I looked into this but I didn’t find enough documentation on how to go about building the required transformer when I was looking.

**Comment by StriderHND** [comment]
Any information about this?

**Comment by zetsnotdead** [comment]
We are also interested in this.

**Comment by flogy** [comment]
> @mikeparisstuff Would a custom transformer do the trick here? My understanding is that custom transformers allow you to write custom response + request VTL templates, whereas enabling TTL is strictly about modifying the Dynamo table itself (ideally via cloudformation).

@zjullion Thought the same thing at first, but it seems that AWS Amplify actually offers a way to implement such a `@ttl` directive by ourselves. They call them transformers as well. See this paragraph in the documentation: https://docs.amplify.aws/cli/plugins/authoring#custom-graphql-transformers

**Comment by flogy** [comment]
I'll try to build this: https://github.com/flogy/graphql-ttl-transformer

Make sure to leave a ⭐️ to motivate me a bit 😉 Thanks!

**Comment by kaustavghosh06** [comment]
@flogy Please open up an issue on GitHub if you encounter any blockers when working on the custom directive plugin. Left you a star on the repo :D

**Comment by flogy** [comment]
The [graphql-ttl-transformer](https://github.com/flogy/graphql-ttl-transformer) library is finished, tested and [published to NPM](https://www.npmjs.com/package/graphql-ttl-transformer) 🚀

It is used exactly the way @vparpoil suggested in the initial post of this issue.

Enjoy and please consider starring the [repo](https://github.com/flogy/graphql-ttl-transformer) if it has helped you saving time and money 😊🙏 Thanks!

**Comment by renebrandel** [comment]
@flogy any concerns if I feature the plugin on our docs?

**Comment by flogy** [comment]
> @flogy any concerns if I feature the plugin on our docs?

@renebrandel No, that would be awesome!

**Comment by renebrandel** [comment]
@flogy - https://github.com/aws-amplify/docs/pull/2593 

I'll close this issue for now given that we've got a documented solution and an amazing 3rd party contribution for this feature. If there is additional interest to have this be built-in, please create a new issue.

**Comment by renebrandel** [comment]
![image](https://user-images.githubusercontent.com/4989523/97338191-7848ad80-183e-11eb-98fb-7a1d9b4942c9.png)
