### ISSUE TITLE
All the VTL resolvers cannot be updated by modifying `schema.graphql` after Mocking.

### ISSUE THREAD

**Issue by jaga810** [aws-amplify/amplify-cli#9268]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When running `$ amplify mock api`,  Amplify CLI exports compiled resolvers to `amplify/backend/api/{API NAME}/resolvers/`.
Even after I exit `$ amplify mock api`using Ctrl+C, `amplify/backend/api/{API NAME}/resolvers/` files which are not custom VTL but generated automatically by Amplify CLI remain.
This causes overwriting all the resolvers and fixing VTLs as I run `$ amplify mock api` at first time.

### Expected behavior

When running `$ amplify mock api`,  Amplify CLI exports compiled resolvers to `amplify/backend/api/{API NAME}/build/resolvers/`.

### Reproduction steps

1. `$ amplify init`
1. `$ amplify add api` specifying IAM and API Key for auth method.
1. edit `schema.graphql` as below

```graphql
type Todo @model 
  @auth(rules: [
      { allow: public, provider: iam }
    ]) 
{
  id: ID! 
  name: String!
  description: String!
}
```

4. `$ amplify mock api`
5. check `amplify/backend/api/{API NAME}/build/resolvers/Mutation.createTodo.auth.1.req.vtl`. Only IAM Authorization is allowed and API Key Authorizations is not allowed.

```vtl
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
#set( $isAuthorized = false )
#set( $allowedFields = [] )
#if( $util.authType() == "API Key Authorization" )
$util.unauthorized()
#end
#if( $util.authType() == "IAM Authorization" )
  #if( $ctx.identity.userArn == $ctx.stash.unauthRole )
    #set( $isAuthorized = true )
  #end
#end
#if( !$isAuthorized && $allowedFields.isEmpty() )
$util.unauthorized()
#end
#if( !$isAuthorized )
  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )
  #if( $deniedFields.size() > 0 )
    $util.error("Unauthorized on ${deniedFields}", "Unauthorized")
  #end
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

6. then edit `schema.graphql` as below during running `$ amplify mock api`

```graphql
type Todo @model 
  @auth(rules: [
      { allow: public, provider: iam }
      { allow: public, provider: apiKey }
    ]) 
{
  id: ID! 
  name: String!
  description: String!
}
```
7. Exit `$ amplify mock api` using Ctrl+C.
7. Check `amplify/backend/api/{API NAME}/build/resolvers/Mutation.createTodo.auth.1.req.vtl` content is not changed. I expect the filed changed as below. API Key Authorizations should be added.

```vtl
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $inputFields = $util.parseJson($util.toJson($ctx.args.input.keySet())) )
#set( $isAuthorized = false )
#set( $allowedFields = [] )
#if( $util.authType() == "API Key Authorization" )
  #set( $isAuthorized = true )
#end
#if( $util.authType() == "IAM Authorization" )
  #if( $ctx.identity.userArn == $ctx.stash.unauthRole )
    #set( $isAuthorized = true )
  #end
#end
#if( !$isAuthorized && $allowedFields.isEmpty() )
$util.unauthorized()
#end
#if( !$isAuthorized )
  #set( $deniedFields = $util.list.copyAndRemoveAll($inputFields, $allowedFields) )
  #if( $deniedFields.size() > 0 )
    $util.error("Unauthorized on ${deniedFields}", "Unauthorized")
  #end
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Once after `$ amplify mock api`, `amplify/backend/api/{API NAME}/resolvers` directory is created and `$ amplify api gql-compile` starts to not work well.

**Comment by lazpavel** [comment]
Hi @jaga810, `amplify api gql-compile` is designed to update the resolvers in the `amplify/backend/api/{API NAME}/build/resolvers/` while `amplify/backend/api/{API NAME}/resolvers/` is used for custom resolvers and resolvers temporarily generated by `amplify mock api`, these will be removed one `amplify mock api` exists.

Can you provide more details in regard to `amplify api gql-compile` starts to not work well after running the `amplify mock api`.

Can you confirm if you still have issues to update the contents of `amplify/backend/api/{API NAME}/build/resolvers/Mutation.createTodo.auth.1.req.vtl` by executing `amplify api gql-compile`?

**Comment by jaga810** [comment]
Thank you for your reaction @lazpavel !

> amplify api gql-compile is designed to update the resolvers in the amplify/backend/api/{API NAME}/build/resolvers/ while amplify/backend/api/{API NAME}/resolvers/ is used for custom resolvers 

Yes. So it's odd Amplify CLI exports compiled resolvers to `amplify/backend/api/{API NAME}/resolvers/` when running `$ amplify mock api`.
Even after I exit `$ amplify mock api` using Ctrl+C, `amplify/backend/api/{API NAME}/resolvers/` files which are not custom VTL but generated automatically by Amplify CLI remain.
This causes overwriting all the resolvers and fixing VTLs as I run `$ amplify mock api` at first time.

I noticed this problem scope is larger than `*.auth.1.req.vtl`; all the resolvers affected.
I'll update the name of issue.

**Comment by lazpavel** [comment]
Hi @jaga810, can you try to manually remove the resolvers from `amplify/backend/api/{API NAME}/resolvers/` and let me know if this solves the main issue. 

In order to exclude some permissions issues, can you confirm that after a manual removal if follow up runs of `amplify mock api` still fail to remove the resolvers from `amplify/backend/api/{API NAME}/resolvers/`

**Comment by jaga810** [comment]
@lazpavel 
Yes that work around worked for me.
However, 

1. it seems painful to manually remove `amplify/backend/api/{API NAME}/resolvers/`
2. What if I create custom VTL file in `amplify/backend/api/{API NAME}/resolvers/` ?

For those don't use custom VTL, [Command Hooks](https://docs.amplify.aws/cli/project/command-hooks/) is a good workaround in terms of 1.

Could you reproduce this bug in your environment?
If not, I'll investigate more on how to reproduce it.

**Comment by lazpavel** [comment]
So far I wasn't able to reproduce, exiting the `amplify mock api` removed the resolvers from `amplify/backend/api/{API NAME}/resolvers/`

**Comment by jaga810** [comment]
@lazpavel 
I found another reproduction step.
If you modify `schema.graphql` during `$ amplify mock api`, resolvers in `amplify/backend/api/{API NAME}/resolvers/` remain after exiting `$ amplify mock api`.

And I wonder if it is expected behavior that `$ amplify mock api` export resolvers in `amplify/backend/api/{API NAME}/resolvers/` not in `amplify/backend/api/{API NAME}/build/resolvers/`.

**Comment by lazpavel** [comment]
Hi @jaga810, thank you for providing reproduction steps. Currently when mock api exits it only removes the templates that are the same as the ones in the `build` directory in order to keep the custom ones. I believe there is room for a better DX here. Marking it as a `feature-request`.

**Comment by mdarche** [comment]
This has been messing me up big time for the last 24 hours. 

I was actively updating my `@auth` directives in `schema.graphql` while running `amplify mock` and the .vtl template files were not reflecting my changes. Workaround is to delete the contents of the resolvers directory before running `amplify mock` as suggested by @lazpavel.
