### ISSUE TITLE
Cannot read properties of null (reading 'level')

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9269]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I was trying to push custom resolver, which I wrote, but it was giving me `only one resolver allowed per field`. I tried multple times, but it  failed. Then I thougt, may be I should go with v2 version, and migrate exisiting structure. Here the steps which I taken to migrate: 
1. amplify migrate api
2. I applied auth rule to each model, to allow authenticated users.
3. Then I renamed overwrite resolvers, according to mention [here](https://docs.amplify.aws/cli/migration/transformer-migration/)
4. This is sample ss: 
![image](https://user-images.githubusercontent.com/54453778/145415786-cbd122fc-071e-4098-815b-95f7eeb5be2f.png)
I followed each step, which is mentioned in the amplify migration doc. 
But when I am doing push, I am facing this error: 
```
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot read properties of null (reading 'level')
```

### Expected behavior

Push should work.

### Reproduction steps

1. amplify migrate api
2. I applied auth rule to each model, to allow authenticated users.
3. Then I renamed overwrite resolvers, according to mention [here](https://docs.amplify.aws/cli/migration/transformer-migration/)
4. amplify push
5. Error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
@hackrx you haven't shared your schema. Does it look like the issue you're encountering is a duplicate of https://github.com/aws-amplify/amplify-cli/issues/9132?

**Comment by hackrx** [comment]
Thanks @cjihrig for referring #9132, I fixed it by following the suggested fix. 
`@model (subscriptions:{level:off})`
