### ISSUE TITLE
Facing CORS Policy issue with API REST on Dynamodb with API Gateway Cognito authorization

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-cli#9270]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

with npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

windows

### Amplify Categories

storage, function, api

### Amplify Commands

add

### Describe the bug

When we try to get items from an imported dynamoDb table with an API REST using a cognito Authorization in API gateway, we got these issues: 

`...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

or

`...has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.`

or

`...has been blocked by CORS policy: Request header field access-control-allow-methods is not allowed by Access-Control-Allow-Headers in preflight response.
`

### Expected behavior

Need to get the items list of an imported dynamoDb table

### Reproduction steps

1) We imported an existing DynamoDb Table using `amplify import storage`
2) We created a Rest API connected to this imported table and we used the CRUD dynamodb template for our lambda function
3) Our lambda function look like : 

```
const AWS = require('aws-sdk')
var awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')
var bodyParser = require('body-parser')
var express = require('express')
var cors = require('cors');

AWS.config.update({ region: process.env.TABLE_REGION });

const dynamodb = new AWS.DynamoDB.DocumentClient();
let tableName = "My table name";
if(process.env.ENV && process.env.ENV !== "NONE") {
  tableName = tableName + '-' + process.env.ENV;
}

var app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

//Enable CORS for all methods
app.use(cors());
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Methods", "GET")
  res.header("Access-Control-Allow-Headers", "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Access-Control-Allow-Methods")
  res.header("Access-Control-Allow-Credentials", true);
  next()
});

//GEST ITEMS LIST
app.get("/items", function(request, response) {
  let params = {
    TableName: tableName,
    limit: 1000
  }
  dynamodb.scan(params, (error, result) => {
    if(error){
      response.json({statusCode: 500, error: error.message});
    }else{
      response.json({statusCode:200, url: request.url, body: JSON.stringify(result.Items)});
    }
  });
});
```
4) Our calling function is : 

```
const getItems = async () =>{

        //INIT
        let myInit = { 
            headers: {
                'Content-Type' : 'application/json',
                Authorization: `${(await Auth.currentSession()).getAccessToken().getJwtToken()}`,
                'Access-Control-Allow-Origin' : '*',
                'Access-Control-Allow-Methods': 'GET',
                'Access-Control-Allow-Headers' : 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Methods',
                'Access-Control-Allow-Credentials' : true
            }
        }

        //GET ITEMSLIST
        API.get("MyAPIName", "/items", myInit).then((result) => {
            console.log(JSON.parse(result.body));
        }).catch(err => {
            console.log(err);
        });
    }
```

6) We added a cognito group authorization to our Methode request in API Gateway
7) When we test it inside api gateway, we are getting the attended results
9) but when trying inside the app we got the error message : **... has been blocked by CORS policy: Request header field access-control-allow-methods is not allowed by Access-Control-Allow-Headers in preflight response.**

10) when we use only the IAM role generated by amplify with no cognito authorization it's works.

_No response_

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso :wave: thanks for raising this! These CORS errors may be a bit misleading due to the lack of CORS headers of failed responses out of API Gateway (reference: https://github.com/aws-amplify/amplify-cli/issues/5183). In your sample snippet, are you seeing an error or the results outputted to the console?

```js
//GET ITEMSLIST
        API.get("MyAPIName", "/items", myInit).then((result) => {
            console.log(JSON.parse(result.body));
        }).catch(err => {
            console.log(err);
        });
```

**Comment by julienlaurent-migso** [comment]
Hi Josef, 
Thank you for your answer,
We have improved our code and our api gateway settings following your reference.
Now all our {proxy+} routes are working very well (we are really happy with that).

But we cannot get the data with the direct path of our API :

we have this console error at the API Call :

![consoleerr](https://user-images.githubusercontent.com/79509459/145572925-a07f8c19-7215-4181-bfe3-dc9a4d8c5083.PNG)

Juste bellow our lambda function (with the direct path and the proxy route):

```
//Enable CORS for all methods
app.use(cors());
app.use(function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next()
});

//API DIRECT PATH => NOT WORKING
app.get("/organizations", function(request, response) {
  let params = {
    TableName: tableName,
    limit: 1000
  }
  dynamodb.scan(params, (error, result) => {
    if(error){
      response.json({statusCode: 500, error: error.message});
    }else{
      response.json({statusCode:200, url: request.url, body: JSON.stringify(result.Items)});
    }
  });
});

//API WITH PROXY ROUTE => WORKING
app.get("/organizations/list", function(request, response) {
  let params = {
    TableName: tableName,
    limit: 1000
  }
  dynamodb.scan(params, (error, result) => {
    if(error){
      response.json({statusCode: 500, error: error.message});
    }else{
      response.json({statusCode:200, url: request.url, body: JSON.stringify(result.Items)});
    }
  });
});
```

here our updated api calling function :

```
//GET ITEMS LIST
    const getOrganizations = async () =>{

        //INIT
        let myInit = { 
            headers: {
                'Content-Type' : 'application/json',
                Authorization: `${(await Auth.currentSession()).getAccessToken().getJwtToken()}`,
            }
        }

        //GET ORGANIZATIONS LIST
        API.get("CoreOrganizationAPI", "/organizations", myInit).then((result) => {
            console.log(JSON.parse(result.body));
        }).catch(err => {
            console.log(err);
        });
    }
```

Our API Gateway direct route :

![01](https://user-images.githubusercontent.com/79509459/145573251-1049755b-5e14-4567-8898-2f24b700bec8.png)

When we test it inside API Gateway, we got the attended results : 

![02](https://user-images.githubusercontent.com/79509459/145573394-5ab392c3-3f78-4366-bc0d-3681c7778e5c.png)

For the preflight OPTIONS we defined the exactly same settings than the {proxy+} route : 

![03](https://user-images.githubusercontent.com/79509459/145573611-13d1db32-85f6-43db-8007-13317174c8f9.png)
![04](https://user-images.githubusercontent.com/79509459/145573617-03a63171-3b53-4869-b58e-716fb29cfba7.png)

Do we miss some thing for a direct path calling ? 
thank you very much for your help.

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso thank you for the detailed clarification! Taking a further look into this.

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso are you using a Cognito Authorizer for your REST API or did you restrict access to users of a group via the CLI? I noticed this line which notes restricting to groups

> We added a cognito group authorization to our Methode request in API Gateway

Was this added in the API Gateway Console manually? May you share the setup of your Cognito Authorizer if in use?

**Comment by julienlaurent-migso** [comment]
Hello @josefaidt,
I am using Cognito User pool Authentification into my amplify application.

When i am calling my API, I pass into the headers the Authorization like : 
```
import {Auth} from '@aws-amplify/auth'
...
headers: {
            'Content-Type' : 'application/json',
            Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}`,
        }
```

In API Gateaway, i defined a Cognito Authorizer using the same Cognito User Pool (and i added to my Method Request): 
![image](https://user-images.githubusercontent.com/79509459/147054803-cf673009-5859-46d8-8a9a-4358a1f66a5b.png)

All my proxy routes "/xxxx/{proxy+} "work very well but not my direct path "/xxxx".

For my application i decided to use only proxy route, so this point is not bloking my development at all.

Thank you very much.

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso apologies for the delay! I'm glad to hear you are unblocked, but to the issue around the direct path can you confirm there is an active route in the Express application with the route without a trailing slash? And also whether the Cognito Authorizer is applied to the direct route vs the proxy route?
![image](https://user-images.githubusercontent.com/5033303/148077809-f5b3d50b-e5b1-4abc-97fa-4c400a1a2998.png)

**Comment by julienlaurent-migso** [comment]
Hey @josefaidt, thank you for your reply. 
Yes in my express app there is an active route for my direct path : 
(if i replace my route /core to /core/items it's working)
![image](https://user-images.githubusercontent.com/79509459/149287006-0ce9360b-ea58-4bca-8e73-174f3232de1a.png)

And yes, you can see that the cognito authorizer is applied to the direct route and the proxy : 
![image](https://user-images.githubusercontent.com/79509459/149287215-da845ee1-4a6f-4ca4-991b-ce034b59b97f.png)
![image](https://user-images.githubusercontent.com/79509459/149287249-19c48fb0-4b89-48bd-a5a8-d71cc4eccf0a.png)

Here my api gateway trigger in lambda:
![image](https://user-images.githubusercontent.com/79509459/149287767-f279272a-97c5-46af-8075-79a092f2424f.png)

I don't know what can i show you more .. 
thank you, 
regards,
Julien

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso :wave: unfortunately I have not been able to successfully reproduce this issue. Can you confirm your Lambda is functioning without error for the `/core` route? 

![image](https://user-images.githubusercontent.com/5033303/150014875-3d61eb58-35c4-4555-8434-dd2517fdfd9b.png)
![image](https://user-images.githubusercontent.com/5033303/150014925-2a1cb302-1602-41b8-8f94-9231748b834c.png)

**Comment by julienlaurent-migso** [comment]
Hi @josefaidt, i spent a lot of time to align and check all my settings between my direct and proxy route in API Gateway and now **everything is working** .. 
I can't explain what was the issue. Maybe the new release of the amplify cli has fixed my issue. 
Thank you a lot for your help ! I close the issue.
