### ISSUE TITLE
Error on amplify push: AmplifyResourcesPolicy - The policy failed legacy parsing

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#9274]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

7.6.3

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I'm pushing updates which include pointing a dynamdb stream to a lambda. amplify push fails with: 

UPDATE_FAILED      AmplifyResourcesPolicy AWS::IAM::Policy      Thu Dec 09 2021 12:33:24 GMT-0700 (Mountain Standard Time) The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 7dff3800-26e1-4b1b-a16c-fe581d7e39cc; Proxy: null)

Resource Name: ampli-Ampl-<redact> (AWS::IAM::Policy)
Event Type: update
Reason: The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 7dff3800-26e1-4b1b-a16c-fe581d7e39cc; Proxy: null)
URL: <redact>

Resource Name: LambdaTriggerPolicyRx (AWS::IAM::Policy)
Event Type: create
Reason: Resource creation cancelled

Resource Name: EssDynamoStreamFn (AWS::Lambda::Function)
Event Type: update
Reason: Resource update cancelled
URL: <redact>

### Expected behavior

amplify push should work with no issues

### Reproduction steps

Not sure. Just happens in my env. I tried to revert to 7.5.5 and the error is still there. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @hisham 

Can you tell me the steps you did when you have this error before ```amplify push```.
Also can you paste the Cfn template policy which is giving errors?

**Comment by hisham** [comment]
I think the steps were: 

1) I added a lambda trigger from a ```@model``` dynamodb stream, I did this by editing the cloudformation of the lambda method (since https://github.com/aws-amplify/amplify-cli/issues/6883 is not implemented yet)
2) I did amplify push, everything worked as expected
3) I switched branches where this trigger was not setup, I did amplify push, the push went through fine, did other dev work, including doing override migrations as required by 7.5.5
4) I went back to the branch where the lambda trigger was setup, and did amplify push, and got this error. 

This seems to be the policy that is failing to parse for some reason: 

```
    "LambdaTriggerPolicyRx": {
      "DependsOn": [
        "LambdaExecutionRole"
      ],
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "amplify-lambda-execution-policy-Rx",
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:ListStreams"
              ],
              "Resource": {
                "Fn::ImportValue": {
                  "Fn::Sub": "${apiEssGraphQLAPIGraphQLAPIIdOutput}:GetAtt:RxTable:StreamArn"
                }
              }
            }
          ]
        }
      }
    },
```

**Comment by hisham** [comment]
Hey somehow, the issue resolved itself! I did amplify function update, and though I didn't make any changes, amplify push now works again, so you're free to close.

**Comment by akshbhu** [comment]
Closing as its working
