### ISSUE TITLE
Amplify push fails after upgrading to GraphQL transformer v2 and moving from 7.6.2 to 7.6.3

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#9278]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.3

### What operating system are you using?

Debian 10

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When I upgraded last week to Amplify v 7.6.2 - it wanted me to upgrade the GraphQL schema to v2 of the GraphQL transformer. I did. I made my new schema work. The migration tool worked fine. It compiled the new schema and I was able to use it in my code with Amplify version 7.6.2.

Today, however, upon upgrading to Amplify 7.6.3 - using the exact same schema: the newly migrated v2 of GraphQL Transformer schema - I got the following error when trying to push:

```
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Your GraphQL Schema is using "@primaryKey", "@index", "@belongsTo", "@hasMany" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.
```

I cannot understand this complaint / error report by the CLI: what is it saying?  That I have the new directives in my v2 schema?  I know that already, so what?  Why does it ask me to look up the website that describes the v2 schema migration if this schema has already been migrated, and if it was successfully migrated as version 7.6.2 proved?  What is the actual problem causing the CLI to barf here? I did not understand that from the reported error message, nor why there was an error message at all.

### Expected behavior

I expected the Amplify CLI to not complain, to not crash, and to compile the newly migrated (v2) schema without any errors, just like version 7.6.2 of the CLI did - no errors - all fine and works with the rest of the code.

### Reproduction steps

See the newly migrated GraphQL schema, in subsection below.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# amplify push
...
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Your GraphQL Schema is using "@primaryKey", "@index", "@belongsTo", "@hasMany" directives from the newer version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.
```
</details>

**Comment by cjihrig** [comment]
In your project's `cli.json` file, can you confirm that the `useexperimentalpipelinedtransformer` feature flag is set to `true`, and the `transformerversion` is set to `2`.

**Comment by dorontal** [comment]
@cjihrig Thank you very much. These flags were not set. The `useexperimentalpipelinedtransformer` was set to `false` and `transformversion` was set to 1 - please accept my apologies for not knowing about these settings.

I am now trying to figure out why those settings have changed from having the correct version (2) in the previous deploy (the one with v7.6.2) and why they are back at version 1 now -- I re-scaffold / recreate the entire amplify project each time so it's possible that `amplify add api` went to v2 before and now it doesn't - if I find anything useful, I will report here.

Closing my mistaken bug report as it is not a bug. Sorry about that and thank you so much for (a) an amazing product, (b) such a quick reply!

**Comment by dorontal** [comment]
I did notice that at the time of running the CLI command `amplify push` the file `amplify/cli.json` does not exist yet.

It is the call to `amplify push` that creates this file in my case.

This call creates the file with the settings for version 1 of the GraphQL transform.

I need to call `amplify push` twice, therefore: once to create the file `amplify/cli.json` and fail with it because the settings in it are for version 1 of the GraphQL transform but my schema is version 2, and a second time, after modifying the newly created `cli.json` to reflect usage of v2 - and that second push works fine.

Right now, this seems to be one way to get a v2 schema and the `cli.json` changes to be pushed together: a failed push, followed by editing `cli.json`, followed by a successful push.
