### ISSUE TITLE
I am getting error after creating "rn-cli.config.js"

### ISSUE THREAD

**Issue by rahulsrivastava1** [aws-amplify/amplify-cli#9296]
const blacklist = require("metro-config/src/defaults/blacklist");
module.exports = {
  resolver: {
    blacklistRE: blacklist([/#current-cloud-backend\/.*/]),
  },
![Screenshot 2021-12-11 115436](https://user-images.githubusercontent.com/54400720/145666718-eef7c7d6-59ca-4b2b-ad91-52e74ecd55c4.png)

};

I updated in the root of the folder but the problem is still troubling? I am using expo... please someone help!

**Comment by akshbhu** [comment]
Hi @rahulsrivastava1 

Its difficult to tell the root cause with this info. 
Can you update this with  issue template?
