### ISSUE TITLE
Cognito auth trigger detached with env checkout

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9297]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I have two envs: rtestapis and testapis.
I created two auth trigger on rtestapis env and both are working fine, but when I tried switching the env, pulled the changes from rtestapis and pushed it to testapis, lambda trigger are not attached to cognito user pool.
But locally, I can see trigger configuration, and everthing is fine, but it is not attaching the triggers to cognito console.
Here is the 
## cli-inputs.json
```
{
  "version": "1",
  "cognitoConfig": {
    "identityPoolName": "blogbackend8xxxxxxx9_identitypool_8xxxxxxx9",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "blogt8xxxxxxx9",
    "userPoolName": "blogbackend8xxxxxxx9_userpool_8xxxxxxx9",
    "autoVerifiedAttributes": [
      "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
      "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
      "email"
    ],
    "aliasAttributes": [],
    "userpoolClientGenerateSecret": false,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email"
    ],
    "userpoolClientLambdaRole": "blogt8xxxxxxx9_userpoolclient_lambda_role",
    "userpoolClientSetAttributes": false,
    "sharedId": "8xxxxxxx9",
    "resourceName": "blogbackend8xxxxxxx9",
    "authSelections": "identityPoolAndUserPool",
    "useDefault": "manual",
    "hostedUI": true,
    "triggers": {
      "PostConfirmation": [
        "custom"
      ],
      "PreSignup": [
        "custom"
      ]
    },
    "userPoolGroupList": [],
    "serviceName": "Cognito",
    "usernameCaseSensitive": false,
    "useEnabledMfas": false,
    "authRoleArn": {
      "Fn::GetAtt": [
        "AuthRole",
        "Arn"
      ]
    },
    "unauthRoleArn": {
      "Fn::GetAtt": [
        "UnauthRole",
        "Arn"
      ]
    },
    "breakCircularDependency": true,
    "dependsOn": [
      {
        "category": "function",
        "resourceName": "blogbackend8xxxxxxx9PostConfirmation",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      },
      {
        "category": "function",
        "resourceName": "blogbackend8xxxxxxx9PreSignup",
        "triggerProvider": "Cognito",
        "attributes": [
          "Arn",
          "Name"
        ]
      }
    ],
    "userPoolGroups": false,
    "adminQueries": false,
    "parentStack": {
      "Ref": "AWS::StackId"
    },
    "authTriggerConnections": "[\n  {\n    \"triggerType\": \"PostConfirmation\",\n    \"lambdaFunctionName\": \"blogbackend8xxxxxxx9PostConfirmation\"\n  },\n  {\n    \"triggerType\": \"PreSignUp\",\n    \"lambdaFunctionName\": \"blogbackend8xxxxxxx9PreSignup\"\n  }\n]",
    "permissions": [],
    "authProviders": [
      "accounts.google.com"
    ],
    "thirdPartyAuth": true,
    "hostedUIDomainName": "blogbackendauth",
    "authProvidersUserPool": [
      "Google"
    ],
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}}]",
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"blog://\"],\"LogoutURLs\":[\"blog://\"]}"
  }
}
```
I also tried creating `override.ts` but it also didn't worked.
## override.ts 
```

import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  let newLambdaConfig = {
    ...resources.userPool.lambdaConfig,
};

if (!newLambdaConfig["PreSignUp"]) {
    newLambdaConfig["PreSignUp"] = {
        "Ref": "arn:aws:lambda:us-east-2:661481011465:function:blog8xxxxxxx9PreSignup-testapis"
    };
  }
  if(!newLambdaConfig["PostConfirmation"]){
    newLambdaConfig["PostConfirmation"] = {
      "Ref": "arn:aws:lambda:us-east-2:661481011465:function:blog8xxxxxxx9PostConfirmation-testapis"
    };
}

resources.userPool.lambdaConfig = newLambdaConfig;
}

```
Push is also resulting in success, not sure what is happening.

### Expected behavior

It should attach the auth trigger. 

### Reproduction steps

1. Create two envs.
2. deploy 2 or more auth triggers to a env
3. then checkout to env b, merge the changes by pulling, then push it to b env.
4. You will can check the triggers in cognito console.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by reedshea** [comment]
I am seeing the same or a similar issue trying to spin up a new environment (new branch, new full-stack Amplify deployment). The `cli-inputs.json` contains a reference in `dependsOn` and `authTriggerConnections` to the correct post-confirmation Lambda function that should be triggered after user signup/confirmation. The relevant CloudFormation stack shows those parameters. In the Cognito console, though, under `User pool properties / Lambda triggers`, nothing is attached. 

The function appears to be correctly created. It shows up in the Lambda console. But when trying to manually attach the trigger in the Cognito console, I receive the following error:

```
[404 Not Found] Allowing Cognito to invoke lambda function cannot be completed.
code: ResourceNotFoundException
message: The resource you requested does not exist.
```

If I instead try to attach the corresponding function from my `dev` environment rather than my `new` branch / environment, that appears to work (but isn't the right outcome, just a point of reference).

**Comment by mgarabedian** [comment]
Upgrading to the latest CLI and migrating Auth, all my lambda triggers configurations in Cognito are deleted upon deployment.... :(  

I do see them all in cli-inputs.json

**Comment by mgarabedian** [comment]
Very worth noting, if i checkout another env and push ( without amplify update auth ), the triggers are gone again

**Comment by gearoidgit** [comment]
> The function appears to be correctly created. It shows up in the Lambda console. But when trying to manually attach the trigger in the Cognito console, I receive the following error:
> 
> ```
> [404 Not Found] Allowing Cognito to invoke lambda function cannot be completed.
> code: ResourceNotFoundException
> message: The resource you requested does not exist.
> ```
> 
As  @reedshea does, I get the same error when using the new version of the AWS Cognito Console.  When I use the current (not the new) version of the AWS Cognito Console I can successfully add the trigger.

**Comment by saltonmassally** [comment]
I am experiencing a similar problem; postConfirmation triggers are not being attached

**Comment by josefaidt** [comment]
Hey @hackrx :wave: apologies for the delay! Are you still experiencing this issue? This appears to now be fixed as I am unable to reproduce the issue
