### ISSUE TITLE
Add option of enforcing "admin create only" for users in Cognito user pool 

### ISSUE THREAD

**Issue by matwerber1** [aws-amplify/amplify-cli#9299]
### Is this feature request related to a new or existing Amplify category?

auth

### Is this related to another service?

cognito

### Describe the feature you'd like to request

When I'm first developing an app with Amplify that uses Cognito auth, I typically want to control user signup and prevent public signups. Similarly, if I'm making an internal / private tool, I do not want signup to be public. I would like the ability to toggle "Admin only" user creation on/off from the Amplify CLI and Amplify Studio.

### Describe the solution you'd like

This request is to add an option to the Auth CLI, something like `Administrators must create users? [yes, no]` and if `yes` is selected, the resulting Cognito User Pool CloudFormation template would have `AllowAdminCreateUserOnly: true`, as shown below: 

```yaml
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
```

Would be great to see the same checkbox in the Amplify Console/Studio, too. 

### Describe alternatives you've considered

In the past, I used to manually edit `xxx-cloudformation-template.yml` in `amplify/backend/auth/xxx/`, but oddly enough I no longer see that file. I **do** see the template in a  new `build` directory (i.e. `amplify/backend/auth/xxx/build/`) but it seems this file is generated based on the user's CLI input each time you run `amplify push`...

It's been quite awhile since I used Amplify... maybe directly modifying a CF template generated by the CLI (or in my case, Amplify Studio) is no longer supported? If so, would make sense... it was always frustrating when I'd run `amplify update xyz` but forgot that I had modified the modified the template earlier, as re-running `amplify update` would overwrite my changes. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by akshbhu** [comment]
Hi @matwerber1 

Can you try our override feature : https://docs.amplify.aws/cli/auth/override/

you can try something like this:
```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {
    resources.userPool.adminCreateUserConfig = {
        allowAdminCreateUserOnly: true
    }
}
```
This command will modify cfn template like this: 
```
  "Resources": {
    "UserPool": {
      "Type": "AWS::Cognito::UserPool",
      "Properties": {
        "AdminCreateUserConfig": {
          "AllowAdminCreateUserOnly": true
        },
```

**Comment by matwerber1** [comment]
Hi @akshbhu,

Sorry, I missed that in the docs. The typescript method is definitely new since the last time I looked at Amplify. 

I haven't tested, but its clear that's exactly what I'm looking for (and much nicer than the old way of editing the CloudFormation JSON).

Thanks for sharing, will close.
