### ISSUE TITLE
Capitalized Env Names break Cloudformation S3 Hosting

### ISSUE THREAD

**Issue by sollipse** [aws-amplify/amplify-cli#930]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
If you create an environment with a capital letter, Cloudformation will try to create a hosting bucket with capitalized letters in the name. 
**To Reproduce**
The following guide is in japanese, but chrome auto-translate does a good enough job of converting to english. 
https://qiita.com/YoshinoriSatoh/items/f185729693243da77c58

**Expected behavior**
Capitalized env names don't break amplify push

**Additional context**

**Comment by kaustavghosh06** [comment]
@sollipse Which version of the CLI are you using? We do not allow env names with capital letters with CLI versions >= 1.0.0

**Comment by sollipse** [comment]
Verified that this error no longer occurs on 1.1.4
