### ISSUE TITLE
PostConfirmation Trigger unable to add user to group, missing `cognito-idp:GetGroup` permission on attached auth resource

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9305]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

Unable to successfully execute `add-to-group` PostConfirmation trigger upon creating a new user in UserPool due to missing permission. Trigger template also tries to create the group if it fails to get the group, which also fails due to a missing permission.

- `cognito-idp:GetGroup`
- `cognito-idp:CreateGroup`

<details>
	<summary>add-to-group trigger code</summary>

```js
/* eslint-disable-line */ const aws = require('aws-sdk')

const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider({
  apiVersion: '2016-04-18',
})

exports.handler = async event => {
  const groupParams = {
    GroupName: process.env.GROUP,
    UserPoolId: event.userPoolId,
  }
  const addUserParams = {
    GroupName: process.env.GROUP,
    UserPoolId: event.userPoolId,
    Username: event.userName,
  }
  /**
   * Check if the group exists; if it doesn't, create it.
   */
  try {
    await cognitoidentityserviceprovider.getGroup(groupParams).promise()
  } catch (e) {
    console.log('error is', e)
    await cognitoidentityserviceprovider.createGroup(groupParams).promise()
  }
  /**
   * Then, add the user to the group.
   */
  await cognitoidentityserviceprovider
    .adminAddUserToGroup(addUserParams)
    .promise()

  return event
}

```

</details>

Sample repo: https://github.com/josefaidt/amplify-postconf-auth-trigger-issue

![image](https://user-images.githubusercontent.com/5033303/145906961-6aae6034-febd-43f4-a0df-01b21815af1d.png)

After adding a `console.log(e)` to the try/catch block of the postconfirmation trigger (to understand why it is attempting to create the group) we see the following error in the Lambda's CloudWatch logs
![image](https://user-images.githubusercontent.com/5033303/145907113-b0b6d1c6-9335-4079-b402-ea06b96f2e6c.png)
  

```
AccessDeniedException: User: arn:aws:sts::814763596509:assumed-role/authtriggersf7a8d23ePostConfirmation-dev/authtriggersf7a8d23ePostConfirmation-dev is not authorized to perform: cognito-idp:GetGroup on resource: arn:aws:cognito-idp:us-east-1:814763596509:userpool/us-east-1_UzWz3I2rt because no identity-based policy allows the cognito-idp:GetGroup action
```

### Expected behavior

default add-to-group template should add new users to group without error

### Reproduction steps

1. `amplify init -y`
2. `amplify add auth`
	1. create group `users`
	2. add `add-to-group` functionality
	3. add PostConfirmation trigger, accept template
3. `amplify push -y`
4. Create sample frontend, attempt to create a new user
5. Observe error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
fix #7673

**Comment by hackrx** [comment]
I also faced this issue, but I fixed it, by manually adding an inline policy to the post-confirmation role.

**Comment by josefaidt** [comment]
Closing as a duplicate of https://github.com/aws-amplify/amplify-cli/issues/7582
