### ISSUE TITLE
ownerField is not working as expected for auth directive, need to update userID instead of username as default 

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9308]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.2

### What operating system are you using?

mac

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

I updated my `schema.graphql` file, for the `@auth` directives, but nothing is working, not sure why. 
According to this guide, we can add `allow: owner` to only allow owners of the document to edit the doc, and we can also specify the `ownerField`, but it's not working, by default appsync adds `owner` attribute to the doc, and the value as username(cognito-username), which is a bad practice to have, because the user is allowed to update the username, also if I am specifying `ownerField`  equals to `userID` which I am assigning from custom-vtl (extracting it using `$ctx.identity.sub`), but it is not allowing a signed in user to even create a doc using `create-$modelName` mutation.
Here is the example schema, mutation and error:  

### ownerField: userID, not authorised error: 
```
Not Authorized to access createPost on type Post
```

### owner (default sets to username), in this case, mutation & queries are working fine.
![image](https://user-images.githubusercontent.com/54453778/145926706-de18d875-0f10-4ac3-9b78-38af764750a1.png)

If I remove `ownerField` from `@auth` rule, then it works, but again it stores userName, which a user can change later, I know a user can't update his/her username after signup, he/she can only update preferred_username, but this is also not working, I have created an [issue](https://github.com/aws-amplify/amplify-cli/issues/9307) here.

### Expected behavior

`ownerField` should work, and instead of userName from cognito, owner field should contain user's sub value by default (from cognito), which is unique, and I am using sub as userID.

### Reproduction steps

1. Add `@auth` rule with `allow: owner, ownerField: userID`
2. amplify push
3. try to execute any mutation or query.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
input CreatePostInput {
  id: ID
  content: String
  userID: ID!
}

type Post
  @model
  @auth(
    rules: [
      {
        allow: owner
        provider: userPools
     ownerField: "userID" 
        operations: [create, update, delete, read]
      }
      { allow: private, provider: userPools, operations: [read] }
      { allow: private, provider: iam }
    ]
  ) {
  id: ID!
  content: String
  userID: ID!
    @index(
      name: "byUser"
      queryField: "getPostSorted"
      sortKeyFields: ["createdAt"]
    )
  User: User! @belongsTo
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by danielleadams** [comment]
@hackrx just so I'm clear on the question - are you trying to replace the `owner` field with the User's ID (that is not the username)? If so, I think what you are looking for is `identityClaim` field for the auth rule. You can add `allow: owner, identityClaim: "sub"` as a rule. Identity claim will be the user field that is grabbed from the JWT token, and "sub" is the unique uuid that a User Pool user gets.

Here are some relevant docs: https://docs.amplify.aws/cli/graphql/authorization-rules/#configure-custom-identity-and-group-claims. Just keep in mind that `user_id` would be for a non-User Pool auth provider - a user ID from User Pool is `"sub"`.

**Comment by hackrx** [comment]
Thanks @danielleadams, it worked 😃 . 
```
  @auth(
    rules: [
      {
        allow: owner
        provider: userPools
        identityClaim: "sub"
        ownerField: "userID"
      }
    ]
  )
```
This [reference](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) is really helpful.
