### ISSUE TITLE
Change sign-in options for existing project

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9316]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
auth

**Amplify CLI Version** 
You can use `amplify -v` to check the amplify cli version on your system
7.6.3

**What AWS Services are you utilizing?**
Cognito, S3, SES, SNS

**Provide additional details e.g. code snippets**
I have an existing project and would like to add an alternative sign-in option - an e-mail.
When I try to remove current auth category, there is too much references to remove along with it, so I'm looking for a way to update the current sign-in method.

How this can be accomplished?

**Comment by lazpavel** [comment]
Hi @jk171505, you should be able to use `amplify update auth`. There are some configurations that cannot be updated after the auth resource is created like signup attributes. Let us know if this solves your use case.

**Comment by jk171505** [comment]
It doesn't. I can live with current sign-up attributes, but I would like to change sign-in options- by adding additional one, I.e. email.
Looks like none of available auth types gives the ability to update the sign-in options unless I'm missing something...

**Comment by lazpavel** [comment]
Thank you for the update, re-checked and currently updating the sign-in options is not supported.
![image](https://user-images.githubusercontent.com/85319655/146414274-c4e8d076-f78e-4715-997f-6643145a0fec.png)
Marking the ticket as a feature request

**Comment by lazpavel** [comment]
This is a console limitation and not a CLI one, closing as Won't Fix.
![image](https://user-images.githubusercontent.com/85319655/146428419-92d3ad8f-7272-4d4b-96ab-399137887e08.png)
