### ISSUE TITLE
Cannot delete an environment, throwing errors about v2 scheme transformers but I'm running v1?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9317]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.6.3

### What operating system are you using?

Windows

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

I'm trying to clean up my environments by deleting an older one we no longer use. Triggering a delete is erroring with an odd error where it is complaining about my schema and lots of references to V2 transformer directives but I'm using V1.

![image](https://user-images.githubusercontent.com/1674590/146195799-aa1b9369-97c1-44bf-9177-0721205bbe2d.png)

Not all that sure how to proceed as the environment is now stuck and I'm worried we are going to be getting billed for a environment I can't clean up.

These environments are left overs from https://github.com/aws-amplify/amplify-cli/issues/9129

They are garbage so happy to just bin them off but can't.

### Expected behavior

Environment just deletes itself, regardless of what state my schema is in, be gone with you! 

### Reproduction steps

Admittedly I'm using the Console for this but the output from that is the same as the CLI so I suspect its using the CLI under the hood or similar.

I'm not sure if the environment is in an unknown state which is why it can't be deleted as a result not sure how best to suggest how to recreate it. Once again happy to jump on a call if needed so you can see it in action.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by PeteDuncanson** [comment]
Can't clone an environment either now 
![image](https://user-images.githubusercontent.com/1674590/146210462-542c5756-b783-4861-9d65-46f90a2ac234.png)

**Comment by josefaidt** [comment]
Hey @PeteDuncanson :wave: thanks for raising this! Taking a look at this

**Comment by josefaidt** [comment]
Hey @PeteDuncanson thank you again for hopping on a quick call with us, and I'm glad we were able to unblock y'all from deleting those environments. I will follow-up with the Console team to uncover what the "clone" functionality is attempting to do and see if we are able to identify what is awry, however thankfully we are able to successfully initialize a new environment and push locally.

With that I'll be closing out this issue. Please keep us posted on how the push performs after we successfully initialized the new environment, and I'll be in touch regarding the Console issue. 🙂
