### ISSUE TITLE
How to add a user to access a model via the email

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#9332]
Hi everyone.

In my code snippet I have a `Post` model where I need to add some `editors`. The way I am planning to invite `editors` is with their e-mail address, however I need their userSub as an entry in `editors`. Is there a way to fetch the userSub with the email address and then update the editors array with that information?

Users create and login with their email-addresses through Cognito.

Thanks.

**Which Category is your question related to?**
Amplify auth

**Amplify CLI Version** 
7.4.2

**What AWS Services are you utilizing?**
- AppSync
- Cognito
- DynamoDB

**Provide additional details e.g. code snippets**

```GraphQL
type Post 
  @model 
  @auth(rules: [
    {allow: owner, ownerField: "owner"},
    {allow: owner, ownerField: "editors", operations: [update, read]}
    {allow: private, operations: [create]}
  ]) {
  id: ID!
  owner: String
  editors: [String]
  name: String!
}
```

**Comment by danielleadams** [comment]
Hi @maziarzamani - you can certainly do this. I think the behavior you are looking for will be a combination of setting up your GraphQL schema with the CLI, and then your application code using the [amplify-js ](https://github.com/aws-amplify/amplify-js) library. Have you taken a look at the Authentication docs for Amplify? (https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/)

**Comment by maziarzamani** [comment]
> Hi @maziarzamani - you can certainly do this. I think the behavior you are looking for will be a combination of setting up your GraphQL schema with the CLI, and then your application code using the [amplify-js ](https://github.com/aws-amplify/amplify-js) library. Have you taken a look at the Authentication docs for Amplify? (https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/)

Hi @danielleadams! Thanks for getting back to me. I do have experience with amplify-js and the API endpoints in general. However I was wondering how I do this magic from a GraphQL perspective. Is there a trick with resolver functions on the attributes directly that I can utilize to make this happen or what would you recommend?

**Comment by maziarzamani** [comment]
As i understand I should be able to add a function to `editors`? 

```GraphQL
type Post 
  @model 
  @auth(rules: [
    {allow: owner, ownerField: "owner"},
    {allow: owner, ownerField: "editors", operations: [update, read]}
    {allow: private, operations: [create]}
  ]) {
  id: ID!
  owner: String
  editors: [String] @function(name: "HandleUserPermission-${env}")
  name: String!
}
```

However an example of how `HandleUserPermission` would work with DynamoDB in play would be a great help, I was not able to find any proper examples anywhere.

**Comment by josefaidt** [comment]
Hey @maziarzamani :wave: after spending some time working with this I've found a suitable solution for using user's emails as the claim

```graphql
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
# input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Post
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "owner", identityClaim: "email" }
      {
        allow: owner
        ownerField: "editors"
        identityClaim: "email"
        operations: [update, read]
      }
      { allow: groups, groups: ["ADMIN"], operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  editors: [String]
  name: String!
}
```

And since the API calls will be using the access token by default, we'll want to be sure we're using the ID token which includes the user's email

```js
async function createPost(input) {
  const result = await API.graphql({
    query: mutations.createPost,
    variables: { input },
    // authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
    authToken: (await Auth.currentSession()).getIdToken().getJwtToken(),
  })
  return result.data.createPost.id
}
```

Now the ownership is tied to the logged-in user's email address they signed up with, and we can manually input `editors` email addresses which will grant `read` and `update` permissions.

Sample app repo: https://github.com/josefaidt/9332/blob/main/src/pages/index.js

**Comment by maziarzamani** [comment]
Thanks @josefaidt!
