### ISSUE TITLE
amplify mock not reverting aws-exports.js on termination

### ISSUE THREAD

**Issue by zalanfarkas** [aws-amplify/amplify-cli#9338]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

7.6.4

### What operating system are you using?

Mac (Apple Silicon)

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

`amplify mock` is not reverting aws-exports.js on termination, therefore, it still contains the mock values. 

### Expected behavior

According to the docs: [Once you stop the mock server the config files are updated with the correct cloud endpoints for your project and DangerouslyConnectToHTTPEndpointForTesting is removed from the config file.](https://docs.amplify.aws/cli/usage/mock/#config-files)

### Reproduction steps

1. Run `amplify mock`
2. Terminate `amplify mock`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Workaround: after running `amplify push` or `amplify pull`, the endpoint values will be correct again. However, we still need to remove "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true from aws-exports.js manually.

**Comment by mdarche** [comment]
Experiencing this issue as well in the latest 7.6.5

**Comment by sundersc** [comment]
Hi @zalanfarkas - what are the authorization modes configured for the api? This can be found in `backend-config.json` file (`api > [apiname] > output > authConfig`).

**Comment by sundersc** [comment]
I can confirm that this issue can be reproduced, we will look into this.
