### ISSUE TITLE
"Template error: instance of Fn::GetAtt references undefined resource" when using AdminUI/Studio for changes on Auth.

### ISSUE THREAD

**Issue by Parth220** [aws-amplify/amplify-cli#9341]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d34ljddyp2gbsz

### Region

us-east-1

### Environment name

Staging

### Amplify CLI Version

7.6.3

### If applicable, what version of Node.js are you using?

v17.0.1

### What operating system are you using?

Ubuntu through Windows Linux Subsystem 

### Browser type?

Google Chrome

### Describe the bug

I deployed a very very rudimentary Authentication setup using the AdminUI/Studio. Later I wanted to update the authentication signup flow, so I clicked "Reset all authentication settings and users", with the hopes of updating the sign up flow after.

When the Admin Studio tries to run the deploy to delete the existing auth settings and users, it results in a deployment failure.

These are the logs: 
`Command failed with exit code 1: amplify push --yes --allow-destructive-graphql-schema-updates - Fetching updates to backend environment: staging from the cloud. - Building resource api/Backend ✔ Successfully pulled backend environment staging from the cloud. - Building resource api/Backend - Updating resources in the cloud. This may take a few minutes... ✖ An error occurred when pushing the resources to the cloud ⚠️ Amplify command hooks are disabled in the current execution environment. ⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information. [32mGraphQL schema compiled successfully.[39m [32mEdit your schema at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema[39m [0m[0m [0m Current Environment: staging[0m [0m [0m [90m┌──────────[39m[90m┬───────────────[39m[90m┬───────────[39m[90m┬───────────────────┐[39m [90m│[39m Category [90m│[39m Resource name [90m│[39m Operation [90m│[39m Provider plugin [90m│[39m [90m├──────────[39m[90m┼───────────────[39m[90m┼───────────[39m[90m┼───────────────────┤[39m [90m│[39m Auth [90m│[39m Backend [90m│[39m Delete [90m│[39m awscloudformation [90m│[39m [90m├──────────[39m[90m┼───────────────[39m[90m┼───────────[39m[90m┼───────────────────┤[39m [90m│[39m Api [90m│[39m Backend [90m│[39m No Change [90m│[39m awscloudformation [90m│[39m [90m└──────────[39m[90m┴───────────────[39m[90m┴───────────[39m[90m┴───────────────────┘[39m [32mGraphQL schema compiled successfully.[39m [32mEdit your schema at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema[39m 🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authBackend.`

When I try to do this operation using `amplify remove auth` and then `amplify push`, 

I get the same final error: 

> Building resource api/BackendGraphQL schema compiled successfully.
> Edit your schema at /mnt/c/Users/Parth/Documents/project/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /mnt/c/Users/Parth/Documents/project/amplify/backend/api/Backend/schema
> ✖ An error occurred when pushing the resources to the cloud
> 🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authBackend

### Expected behavior

The deployment would complete properly and Amplify AdminUI would delete all users and previous settings, allowing me to revamp my auth flow.

### Reproduction steps

1. Go to Amplify AdminUI/Studio
2. Click Authentication 
3. Scroll to the bottom and click "Reset all authentication settings and users"
4. Click confirm.

**Comment by yppartyk** [comment]
@Parth220 

To unblock yourself, please do the following with the CLI:
- `amplify remove auth` 
- `amplify update api`
- Select `GraphQL`
- `Select a setting to edit`:  **Authorization modes**
- `Choose the default authorization type for the API`: choose either **API key** or **IAM** depending on your GraphQL schema
- When you get to `Configure additional auth types?`, enter `yes` (that you want to edit these)
- When given the choice of additional auth types, _unselect_ **Amazon Cognito User Pool** and press enter

You should now be able to push your updates and remove the Auth resource. However, do this only if your GraphQL schema does not actually depend on the Cognito User Pool auth type (i.e. if none of the auth directives in your schema contain `{allow: private}`)
