### ISSUE TITLE
gitignore `node_modules` for custom resources

### ISSUE THREAD

**Issue by hkford** [aws-amplify/amplify-cli#9342]
### Describe the feature you'd like to request

When you add custom resources using CDK, [Amplify CLI generates `amplify/backend/custom/<resource-name>` directory](https://docs.amplify.aws/cli/custom/cdk/) which includes `node_modules` after build step.

It would be helpful if Git ignores `amplify/backend/custom/<resource-name>/node_modules` and `amplify/backend/custom/<resource-name>/build` directory.

### Describe the solution you'd like

Currently [ignoreList](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts#L50) does not have such directories. Adding `amplify/backend/custom/*/node_modules` is the first choice.

### Describe alternatives you've considered

When Amplify CLI generates skeleton directory for CDK custom resource, [the `generateSkeletonDir` function](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-custom/src/walkthroughs/cdk-walkthrough.ts#L37) does not create `.gitignore`. Generating `.gitignore` for the custom resources is the second choice.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @hkford :wave: these two directories should be covered by the `build/` and `node_modules/` lines in the generated gitignore. Are you seeing an issue where these directories are checked into git?

```
#amplify-do-not-edit-begin
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
**.sample
#amplify-do-not-edit-end
```

**Comment by hkford** [comment]
I found the generated gitignore worked well (Git ignored node_modules of custom resources). Close this issue. 

![スクリーンショット 2022-02-09 18 48 18](https://user-images.githubusercontent.com/82389275/153171418-e8964388-840e-42d7-85c3-5fb516057ee2.png)
