### ISSUE TITLE
Incorrect environment name parameter in hooks script

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify/amplify-cli#9346]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.18.2

### Amplify CLI Version

7.6.4

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

[In documentation](https://docs.amplify.aws/cli/project/command-hooks/#access-parameters-in-hook-scripts), parameter structure in hooks scripts is following:
```json
{
  "amplify": { 
    "version": String,
    "environment": String,
    "command": String,
    "subCommand": String,
    "argv": [ String ]
  }
}
```
But, actually `amplify.envionment` is `Object` not `String`, and `amplify.envionment.envName` is actually the environment name.

### Expected behavior

To access `amplify.environment` as String.

### Reproduction steps

1. Create `amplify/hooks/pre-status.js` with the following contents.
   ```js
   const fs = require('fs');
   const parameters = JSON.parse(fs.readFileSync(0, { encoding: 'utf8' }));
   console.log(parameters.data, parameters.error)
   ```
2. Run `amplify status`
3. The following content is output to the terminal
   ```
   ----- 🪝 pre-status execution start -----
      {
        amplify: {
          environment: {
            projectPath: '/workspaces',
            defaultEditor: 'vscode',
            envName: 'dev'
          },
          command: 'status',
          argv: [
            '/usr/local/bin/node',
            '/usr/local/share/npm-global/bin/amplify',
            'status'
          ],
          version: '7.6.4'
        }
      } undefined
   ----- 🪝 pre-status execution end -----
   ```

**Comment by cjihrig** [comment]
It looks like this was fixed by https://github.com/aws-amplify/amplify-cli/pull/9347, so I'll close this out.

**Comment by cjihrig** [comment]
Oops. #9347 was closed without merging, so I'll reopen this.
