### ISSUE TITLE
Custom Transformer v2 - Resolvers in TransformerContext are empty/undefined

### ISSUE THREAD

**Issue by mrsimply** [aws-amplify/amplify-cli#9349]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v17.0.1

### Amplify CLI Version

7.6.4

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

With Custom Transformes v1 I implemented a custom directive `@tenant`, which I am trying to rebuild with **Transformer v2**.

When trying to use the `ctx.resolvers.getResolver(typeName, fieldName)`, the result is `undefined`.
When trying to grab all resolvers with `ctx.resolvers.collectResolvers()`, I receive an empty object `{}`.

Here is my minmum code for reproduction:
```ts
import {
  InvalidDirectiveError,
  TransformerPluginBase,
} from '@aws-amplify/graphql-transformer-core';
import {
  TransformerContextProvider,
  TransformerSchemaVisitStepContextProvider,
} from '@aws-amplify/graphql-transformer-interfaces';
import { DirectiveNode, ObjectTypeDefinitionNode } from 'graphql';

const directiveName = 'tenant';
const directiveDefinition = `
  directive @${directiveName} on OBJECT
`;

export class TenantTransformer extends TransformerPluginBase {
  private typesWithModelDirective: Set<string> = new Set();

  constructor() {
    super('tenant-transformer', directiveDefinition);
  }

  object = (
    definition: ObjectTypeDefinitionNode,
    directive: DirectiveNode,
    ctx: TransformerSchemaVisitStepContextProvider,
  ): void => {
    const typeName = definition.name.value;
    this.typesWithModelDirective.add(typeName);
  };

  generateResolvers = (ctx: TransformerContextProvider): void => {
    const resolvers = ctx.resolvers.collectResolvers();
    const keys = Object.keys(resolvers);

    if (keys.length === 0) {
      throw new InvalidDirectiveError('I cannot find any resolvers at all :-(');
    }
  };
}

```

This is my API schema:
```graphql
type Todo @model @tenant @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  description: String
}
```

### Expected behavior

I expect the context to provide the resolvers available from `@model`and `@auth`, with the possibility to add custom snippets with `resolver.addToSlot()` - wich I can't, because resolver is **undefined**:

### Reproduction steps

1. Init amplify
2. Create GraphQL API with Basic Cognito Auth and the Demo "Todo" GraphQL Schema
3. Create a Custom Transformer (code above), configure `transform.conf.json`, add @tenant directive to GraphQL Schema
3. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mrsimply** [comment]
PS: I was also waiting for #9180 to get fixed with #9252 done by @cjihrig - Maybe the topics are related? in #9180 custom transformers were not considered at all - now they are considered, but they are not populated with any resolvers...

**Comment by cjihrig** [comment]
@mrsimply I can reproduce your error message, but I believe it's because you are calling `Object.keys()` on the `Map` object that is returned by `ctx.resolvers.collectResolvers()`. The `Map` does contain resolvers though.

**Comment by mrsimply** [comment]
> @mrsimply I can reproduce your error message, but I believe it's because you are calling `Object.keys()` on the `Map` object that is returned by `ctx.resolvers.collectResolvers()`. The `Map` does contain resolvers though.

Thx for checking, the Keys was just to demonstrate the object is empty. At least in my case it is empty!

My resolvers just return `{}`

I have no clue why. Any ideas?

**Comment by cjihrig** [comment]
Can you try `resolvers.keys()` instead of `Object.keys(resolvers)`. `resolvers` is a `Map`, not a plain JavaScript object.

**Comment by mrsimply** [comment]
> `resolvers` is a `Map`, not a plain JavaScript object.

@cjihrig true 🤦‍♂️ Thanks for pointing this out 😅 I still can't finish my transformer as the contents of `resolver.addToSlot(slotName, requestMappingTemplate)` won't show up in the TransformerResolver, but that is another story... Thanks again!

**Comment by mrsimply** [comment]
@cjihrig I'm still struggling, as the Transformer v2 is very sparsely documented - As you seem to have a stake in the amplify-cli package, would you mind taking a look into #9362 as well? Thank you very much in advance 🥺
