### ISSUE TITLE
Amplify pull deletes local resources

### ISSUE THREAD

**Issue by Spidey507** [aws-amplify/amplify-cli#9357]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.2.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

Ubuntu

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

I try to pull the info from my cloud backend and it brings nothing to my local

### Expected behavior

when I run amplify pull I want to get all the info I have on my cloud backend to my local 

### Reproduction steps

1. amplify status
2. amplify pull

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by marcvberg** [comment]
Hello, we'll need some additional information here
1. We need some logs of the output you're seeing
2. Are you adding resources with the CLI and then attempting to pull before pushing?

**Comment by cjihrig** [comment]
Closing due to a lack of follow up. If you're still having problems, please open a new issue.
