### ISSUE TITLE
Destination of API.ts|js

### ISSUE THREAD

**Issue by struct78** [aws-amplify/amplify-cli#936]
**Is your feature request related to a problem? Please describe.**

Destination of generated API.ts|js does not always go to common/logical folder.

**Describe the solution you'd like**

amplify codegen should see if folders such as `api/` or `services/` (and any other folders developers commonly use for API logic) exist in the `src/` folder before suggesting writing itself to the root of `src/`

For example, if my folder structure contains `src/services`, when I run `amplify push` on a new environment, or run `amplify codegen`, the CLI should present me with something like this:

`Enter the file name for the generated code (src/services/API.ts)`

**Comment by kaustavghosh06** [comment]
This is a duplicate issue and we're tracking it as a part of #916.
