### ISSUE TITLE
Minimum version required of Amplify CLI is not installed

### ISSUE THREAD

**Issue by iwishApp** [aws-amplify/amplify-cli#9364]
The project has been developed during the beginning of 2020.  Now I want to continue developing. I pulled  dev env from AWS server to a brand new Mac OS, where I have installed npm and amplify cli just before that.
npm install -g @aws-amplify/cli amplify-app

Node -v  is 16.13.1
npm -v is 8.1.2

when I try to build my project in Xcode I get this:

error: Minimum version required of Amplify CLI is not installed.
  Min required version: (4.22.0)
  Found Version: (7.6.4)

To install the latest version, please run the following command:
  npm install -g @aws-amplify/cli@latest

Command above does not help, because I already have the latest version of CLI.  What can be done here?

**Comment by marcvberg** [comment]
Hello, do you have a package.json that references a version of the cli? I'm wondering if you've got something like "^4.22.0" where the major version must still be 4

**Comment by iwishApp** [comment]
Solved. Uninstall and install of cocaopods. Then
pod init
(input necessary pods into it)
pod install --repo-update

and it was fixed
