### ISSUE TITLE
How to add custom attributes in cognito from cli?

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-cli#9373]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.5

### What operating system are you using?

mac

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

I want to know if there is any way to create custom attributes in cognito userpool using CLI.
Right now, I have custom attributes in my Cognito which I created from cognito console, but if I checkout to a new amplify env and push it, I don't get all the custom attributes, so it is really tedious process, to reflect the same attributes to different envs.

### Expected behavior

There should be way to add custom attributes may be in any cf file or somewhere, so that a new amplify env with auth have same attributes in cognito console.

### Reproduction steps

1. Add auth 
2. Add custom attributes from cognito console
3. amplify env add newenv
4. Check cognito console for custom attributes.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by chris-mds** [comment]
Hi @hackrx,

This is possible with the new auth override function. Look at [this](https://github.com/aws-amplify/amplify-cli/issues/9051#issuecomment-977857262).

**Comment by hackrx** [comment]
Thanks @chris-mds, it worked!
Here is what I did: 
1. `amplify override auth`
2. Edit the generated `override.ts` with this code:  
```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  //customAttributeName Member must have length less than or equal to 20 
  const customAttribute = {
    "attributeDataType" : 'String',
    "developerOnlyAttribute" : false,
    "mutable" : true,
    "name" : 'mycustomattribute',
    "required" : false
  };
 
  resources.userPool.schema = [customAttribute];
}

```
3. amplify push
