### ISSUE TITLE
Nested Stack Updates get Overwritten any time environment is built/deployed

### ISSUE THREAD

**Issue by jnastaskin** [aws-amplify/amplify-cli#9376]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

7.6.3

### What operating system are you using?

Mac

### Amplify Categories

storage, hosting

### Amplify Commands

pull, push

### Describe the bug

 I'm looking to update a nested stack but am seeing the updates get overwritten any time I build/deploy the environment.  This is what i followed when updating the stack
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html

I updated a nested stack template regarding a storage resource by following this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html.  After deploying the environment the changes made to that stack get overwritten with the automatically created cloudformation template.  All I'm trying to do for that template is substiitute ${cognito-identity.amazonaws.com:sub} with ${aws:PrincipalTag/cognitoId} per steps listed here https://github.com/aws-amplify/amplify-js/issues/54#issuecomment-876455852

### Expected behavior

Updates made to nested stack persist after deploying/build.

### Reproduction steps

1. update a nested stack following the steps listed here:
 (using the console and by directly uploading a local template file to the nested stack, not the root stack) 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html

2.  Build/deploy environment that the updated stack was in
3.  Check that nested stack's template that was updated --> changes are overwritten

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

If there is a better way to make that change to the stack (i.e. substiitute ${cognito-identity.amazonaws.com:sub} with ${aws:PrincipalTag/cognitoId} ) I'm all ears.  Updating the template directly via the docs guide listed above seemed the most straightforward.
 
I'm not sure if the issue might be because I'm updating the nested stack instead of the root stack, but the reason for that is I'm not sure how to make that update to the nested stack through the root stack, if that makes sense.

Thank you in advance to any help offered! :)

**Comment by ammarkarachi** [comment]
@jnastaskin we have released storage overrides to you can use the override function to make modifications to the storage policy after running `amplify override storage` https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-s3-resources

**Comment by jnastaskin** [comment]
Hi @ammarkarachi , thanks for getting back to me on this.  That seems like it should do the trick ,however, I'm running into an issue of how exactly to implement the override I'm trying to make in the template, which is to simply update this string in the template:
![image](https://user-images.githubusercontent.com/31951390/147610678-e5c2cf1c-ee8e-468c-80c0-9c6641df1947.png)

I see with the automatically generated override.ts file  we can access "resources.s3AuthProtectedPolicy.policyDocument"

I tried using the following in my override.ts document: 
`
import { AmplifyS3ResourceTemplate } from '@aws-amplify/cli-extensibility-helper';
const policyDocument = {
  PolicyDocument: {
    Version: '2012-10-17',
    Statement: {
      Effect: 'Allow',
      Action: {
        'Fn::Split': [
          ',',
          {
            Ref: 's3PermissionsAuthenticatedProtected',
          },
        ],
      },
      Resource: [
        {
          'Fn::Join': [
            '',
            [
              'arn:aws:s3:::',
              {
                Ref: 'S3Bucket',
              },
              '/protected/${aws:PrincipalTag/cognitoId}/*',
            ],
          ],
        },
      ],
    },
  },
};

export function override(resources: AmplifyS3ResourceTemplate) {
  resources.s3AuthProtectedPolicy.policyDocument = policyDocument;
}
`

this gave me an error after doing an amplify push:
"UPDATE_FAILED      S3AuthProtectedPolicy AWS::IAM::Policy Tue Dec 28 2021 14:32:28 GMT-0800 (Pacific Standard Time) Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 26d92de7-0f16-4b09-a1b4-e1a69065945a; Proxy: null)"


any ideas on how to do this? The documentation here https://docs.amplify.aws/cli/storage/override/#customize-amplify-generated-s3-resources gives little to no examples of more involved uses cases of an override :/

Thank you in advance!

**Comment by jnastaskin** [comment]
when trying the same thing but:
`resources.s3AuthProtectedPolicy.policyDocument = JSON.stringify(policyDocument);
`
I get the same error

**Comment by jnastaskin** [comment]
UPDATE:

I realized the issue with my override file was i had an extra " PolicyDocument: " in the object **and** I needed to use double quotes instead of single quotes for the object to properly get converted as json.

Issue has now been resolved, the cloud formation stack is persisting through builds :)

Note: with this new override feature, there really should be some added documentation to notify the user that updates they make directly to the cloudformation templates in the console will get overwritten after a build....aside from testing a new feature prior to a build, I don't see the utility in updating a  cloudformation template directly in the console since it will get overwritten anyways...
