### ISSUE TITLE
Lambda function in GraphQL endpoint is not returning proper errorType but instead "Lambda:Unhandled"

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-cli#9378]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.3

### What operating system are you using?

macOS

### Amplify Categories

function, api

### Amplify Commands

add, pull, push

### Describe the bug

When applying a lambda to a custom query or mutation the lambda function is not returning proper errorType when an exception is raised, however it is always returning `Lambda:Unhandled`.

### Expected behavior

Expecting that the right errorType is shown in the errors variable of the endpoint, and not `Lambda:Unhandled`

### Reproduction steps

- Create a "hello world" lambda function named "myTestFunction" and replace with "minimal lambda code" as shown below
- Add the query to the schema as shown int he "GraphQL schemas" section
- Push

**Minimal lambda code (myTestFunction):**

```JavaScript
class CustomException extends Error {
    constructor(message) {
        super(message);
    }
}

exports.handler = async(event, context, callback) => {
    throw new CustomException("Failed retrieving test query")
}
```

### GraphQL schema(s)

```GraphQL
type Query {
  testQuery(email: String!): String @function(name: "myTestFunction-${env}") @auth(rules: [{allow: private}])
}
```

### Log output

```
{
  "data": {
    "testQuery": null
  },
  "errors": [
    {
      "path": [
        "testQuery"
      ],
      "data": null,
      "errorType": "Lambda:Unhandled",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Failed retrieving test query"
    }
  ]
}

```

**Comment by sundersc** [comment]
Hi @maziarzamani - This is by AppSync design. You can read more about this [here](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html). 

However the behavior you are expecting can be achieved by overriding the response resolver.
https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers

Below is an example.

**Schema:**
```graphql
type Example @model {
  id: ID!
  ... other fields
  echo: String @function(name: "echoFunction-${env}")
}
```

**Lambda function:**
```typescript
exports.handler = (event, context, callback) => {
    const result = {
        data: 'test response',
        errorMessage: 'Error Message goes here',
        errorType: 'CustomErrorType'
    };
    callback(null, result);
};
```

**Custom resolver:** (Example.echo.res.vtl)
```
#if( $ctx.prev.result && $ctx.prev.result.errorMessage )
    $utils.error($ctx.prev.result.errorMessage, $ctx.prev.result.errorType, $ctx.prev.result)
#else
    $utils.toJson($ctx.prev.result.data)
#end
```

**AppSync error response:**
```json
"errors": [
    {
      "path": [
        "listBlogs",
        "items",
        0,
        "test"
      ],
      "data": null,
      "errorType": "CustomErrorType",
      "errorInfo": null,
      "locations": [
        {
          "line": 6,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Error Message goes here"
    }
  ]
```

**Comment by maziarzamani** [comment]
@sundersc, so here is the golden question, I have multiple resolvers for this lambda function in the build folder:

**Query.testQuery.res.vtl**
`        
$util.toJson($ctx.prev.result)
`

**InvokeTestQueryLambdaDataSource.res.vtl**
```vtl
## [Start] Handle error or return result. **
#if( $ctx.error )
  $util.error($ctx.error.message, $ctx.error.type)
#end
$util.toJson($ctx.result)
## [End] Handle error or return result. **

```

I tried to update the **InvokeTestQueryLambdaDataSource.res.vtl** with your sample code:
```
#if( $ctx.prev.result && $ctx.prev.result.errorMessage )
    $utils.error($ctx.prev.result.errorMessage, $ctx.prev.result.errorType, $ctx.prev.result)
#else
    $utils.toJson($ctx.prev.result.data)
#end

```

However AppSync is returning this now

```json
{
  "data": {
    "testQuery": null
  }
}
```

**Comment by maziarzamani** [comment]
I added your Custom resolver to `Mutation.testQuery.res.vtl` and it did the trick a long with the lambda sample code!! Cheers.
