### ISSUE TITLE
On Windows, plugins development does not work.

### ISSUE THREAD

**Issue by zeodtr** [aws-amplify/amplify-cli#938]
**Describe the bug**
On Windows, plugins development (https://aws-amplify.github.io/docs/cli/plugins?sdk=js) does not work. 

**To Reproduce**
Follow the steps in https://aws-amplify.github.io/docs/cli/plugins?sdk=js
It does not work on Windows. Amplify CLI does not recognize the newly installed plugin.

**Expected behavior**
If you follow the steps in https://aws-amplify.github.io/docs/cli/plugins?sdk=js
You should see the intended output on the console of Windows.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: not relevant
 - Version: 10

**Additional context**

**Solution**
Actually, I've found the solution. It is a bug on
amplify-cli/packages/amplify-cli/src/lib/global-prefix.js

Current function:
```javascript
function getGlobalNodeModuleDirPath() {
  const yarnPrefix = getYarnPrefix();
  if (__dirname.includes(yarnPrefix)) {
    return path.join(yarnPrefix, 'node_modules');
  }
  return path.join(getNpmPrefix(), 'lib', 'node_modules');
}
```
 Should be modified as follows:
```javascript
function getGlobalNodeModuleDirPath() {
  const yarnPrefix = getYarnPrefix();
  if (__dirname.includes(yarnPrefix)) {
    return path.join(yarnPrefix, 'node_modules');
  }
  if (process.platform === 'win32')
    return path.join(getNpmPrefix(), 'node_modules');
  return path.join(getNpmPrefix(), 'lib', 'node_modules');
}
```

Please refer the npm document: https://docs.npmjs.com/files/folders.html
(Search for 'that is, no lib folder')

**Comment by wizage** [comment]
This has been fixed in #941
