### ISSUE TITLE
AUTH: Set lamba triggers via cloud formation

### ISSUE THREAD

**Issue by henobi** [aws-amplify/amplify-cli#9382]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

Hi guys,

we experienced some problems with the lambda triggers in cognito. Sometimes when we run amplify push we figured out that as a side effect the lambda triggers were not set anymore. Every time we are deploying on production we are getting very nervous because of that.

We then took a look into the cloudformation file and analysed that amplify-cli does not configure the cognito triggers via native CloudFormation [1] but via a inline-lambda and we think that is causing the problems.

Why is amplify not using the `AWS::Cognito::UserPool LambdaConfig` to configure cognito lambda triggers?
Could this be implemented in the future?

Thank you.

Kind regards,

Hendrik

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html

### Expected behavior

Triggers should stay as configured.

### Reproduction steps

-

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@henobi thanks for the issue I will mark it as feature request for the team

**Comment by akshbhu** [comment]
Hi @henobi 

You can to turn off this flag ```breakcirculardependency``` to false to achieve cognito triggers creation through CFN. 

This flag is introduced to break circular dependency between API , Auth , Cognito triggers.

You can check ore here : https://docs.amplify.aws/cli/reference/feature-flags/#breakCircularDependency

**Comment by henobi** [comment]
Hi @akshbhu 

Looks exactly what we were looking for.  Thank you very much. We will try it out.

In the documentation it says the flag is deprecated.
So what will be the default in the future? Triggers via Custom Lambdas or CFN?

Best regards
Hendrik

**Comment by akshbhu** [comment]
Nice to know that it solves your problem. For the procedure, you have to update auth with FF as false to make CFN changes.

Currently we dont have any plan to deprecate this flag since this flag solves a case of circular dependency on API , auth and cognito triggers.

Closing this request as already implemented.
