### ISSUE TITLE
Failed to start API Mock endpoint TypeError: Cannot read property 'level' of null

### ISSUE THREAD

**Issue by nealdeters** [aws-amplify/amplify-cli#9389]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

amplify mock api

### Describe the bug

When attempting to mock my newly migrated api schema I'm hitting the below error:

Failed to start API Mock endpoint TypeError: Cannot read property 'level' of null

### Expected behavior

Expect for the newly migrated schema to build successfully.

### Reproduction steps

1. Update env to Amplify CLI 7.6.5
2. Migrate older schema to newer directives by running 'amplify migrate api'
3. Run 'amplify mock api' to build local schema

### GraphQL schema(s)

<details>

```graphql
# Can email this if needed


```

</details>

### Log output

<details>

```
# 


```

</details>

**Comment by akshbhu** [comment]
Hi @nealdeters 

Can you share the graphql schema so that I can reproduce it  on my end ?

**Comment by nealdeters** [comment]
@akshbhu could I email you my schema? It's a couple of files.

**Comment by akshbhu** [comment]
Hi @nealdeters 

You can mail us at amplify-cli@amazon.com

**Comment by nealdeters** [comment]
Thanks, I've emailed the schema.

**Comment by lazpavel** [comment]
Hi @nealdeters, can you resend the schema, it looks that there is no attachment to the previous email. Thank you!

**Comment by nealdeters** [comment]
Hi @lazpavel, sorry about that. I've sent the attachment.
