### ISSUE TITLE
inputs generated in graphql schema even if model has queries and/or mutations null, however these are not accessible in the schema

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#939]
**Describe the bug**
If I create a graphql schema with @model, inputs are created for the queries and mutations even if they are marked null. (I don't think they should be) Then, if you try to refer to these in your graphql schema, the compile step reports them as non-existent. If you try to include same named inputs in your graphql schema it complains that the inputs already exist.

I've worked around it by changing namespaces (using "New..." in place of "Create..." etc.).

**To Reproduce**
Create a schema like so:

type Something @model(queries:null, mutations:null) { id: ID!, name: String! }
type Mutation { mutateSomething(input: CreateSomethingInput): Something }

-or the other case-

type Something @model { id: ID!, name: String! }
input CreateSomethingInput { id: ID!, name: String! }

and run amplify push

**Expected behavior**
I think it would be better if it worked such that if I include a like named object in my schema, it should overwrite the "default" generated schema. e.g. if I add "input CreateSomethingInput" and it's part of the auto-generated schema already, my version replaces the auto-generated version in the final compiled schema. And if the queries or mutations are null and the inputs unused they should not be included by default in the auto-generated schema.

Thanks.

**Comment by mikeparisstuff** [comment]
Hey @ryanhollander. This is fixed by #950.

**Comment by ryanhollander** [comment]
@mikeparisstuff Thanks!

**Comment by ryanhollander** [comment]
just wanted to let you know I upgraded to 1.1.7 today and this fix is in that release. I was able to compile my graphql schema and the "ghostly" inputs are indeed no longer included. Thank you.

**Comment by yuth** [comment]
@rayjanwilson thank you for confirming the fix
