### ISSUE TITLE
@primaryKey directive on API type definition does not apply to generated queries

### ISSUE THREAD

**Issue by samjett247** [aws-amplify/amplify-cli#9392]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.17.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

storage, api

### Amplify Commands

add, codegen, push

### Describe the bug

According to the documentation here: https://docs.amplify.aws/cli/graphql/data-modeling/
using the @primaryKey directive will allow the user to define the primarykey used for the table. However, this @primaryKey directive does **not** change the autogenerated get{typename} queries, which use the `id` field by default. This is a departure from the behavior prior to this release, where annotating a field as a key would also allow you to `get{typename` via amplify query.

**Current Behavior**
In the output src/queries.graphql, I see the following query: 

```export const getTesttype = /* GraphQL */ `
  query GetTesttype($id: ID!) {
    getTesttype(id: $id) {
      myidname
      fieldnameone
      fielnametwo
      createdAt
      updatedAt
    }
  }
`;```

When I look at the Dynamodb table, I see that `myidname` is successfully created as the primaryKey of the table.

HOWEVER, if I try to use this query in the Appsync console, I am not able to query on `myidname`  and have to query on an `id` field. When querying, I get the following error: 

```
{
  "data": {
    "getTesttype": null
  },
  "errors": [
    {
      "path": [
        "getTesttype"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Query condition missed key schema element: myidname (Service: DynamoDb, Status Code: 400, Request ID: 6M6BFMT7AJT1TPICEHCLT6TRAJVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"
    }
  ]
}
```

### Expected behavior

**Expected Behavior**

I had assumed that, by defining the field `myidname` as @primaryKey, Appsync would know that I need the "get" query to query on the `myidname` field, not on this `id` field that is Appsync-generated and doesn't actually exist in the dynamo tables. In fact, by using the @primaryKey directive, I am now unable to "get" query the type. I believe this is a bug and oversight in the behavior of the @primaryKey directive. 

Please help urgently, as our project is going to need to either work out a fix for this issue or revert to the previous version of amplify that allowed the "get" queries on the primary key of the table.

### Reproduction steps

Create a new amplify project
amplify add api 
    - accept all defaults
edit the schema.graphql and add the following type: 
```
type testtype
  @model
  @auth(
      rules: [
        { allow: all, operations: ["read", "create", "update"]},
      ]
  )
  {
      myidname: ID! @primaryKey
      fieldnameone: String
      fielnametwo: String
  }
```

### GraphQL schema(s)

Authorization doesnt really matter - do auth however is easiest

```graphql
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type testtype
  @model
  {
      myidname: ID! @primaryKey
      fieldnameone: String
      fielnametwo: String
  }

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

You should confirm that you see the following output in `src/queries.graphql`:

```export const getTesttype = /* GraphQL */ `
  query GetTesttype($id: ID!) {
    getTesttype(id: $id) {
      myidname
      fieldnameone
      fielnametwo
      createdAt
      updatedAt
    }
  }
`;```

**Comment by samjett247** [comment]
@renebrandel am I doing something incorrectly here? Would appreciate any insight you can provide :)

**Comment by samjett247** [comment]
With graphql transformer V1, when appsync generates a "get" graphql query on a type, it looks like the following (assuming the field name was `primarykeyfield`):

```vtl
## [Start] Set the primary @key. **
#set( $modelObjectKey = {
  "email": $util.dynamodb.toDynamoDB($ctx.args.email)
} )
## [End] Set the primary @key. **
{
  "version": "2018-05-29",
  "operation": "GetItem",
  "key": #if( $modelObjectKey ) $util.toJson($modelObjectKey) #else {
  "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
} #end
}
```

Three things to notice: (i) It is using a "getitem" operation on the table, (ii) It sets the modelObjectKey at the beginning of the resolver, (iii) If modelObjectKey is not defined, it will default to using the `id` field.

Using Graphql transformer V2, it generates the following for a "get" operation:

```vtl
## [Start] Get Request template. **
#set( $GetRequest = {
  "version": "2018-05-29",
  "operation": "Query"
} )
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $expression = "" )
  #set( $expressionNames = {} )
  #set( $expressionValues = {} )
  #foreach( $item in $ctx.stash.metadata.modelObjectKey.entrySet() )
    #set( $expression = "$expression#keyCount$velocityCount = :valueCount$velocityCount AND " )
    $util.qr($expressionNames.put("#keyCount$velocityCount", $item.key))
    $util.qr($expressionValues.put(":valueCount$velocityCount", $item.value))
  #end
  #set( $expression = $expression.replaceAll("AND $", "") )
  #set( $query = {
  "expression": $expression,
  "expressionNames": $expressionNames,
  "expressionValues": $expressionValues
} )
#else
  #set( $query = {
  "expression": "id = :id",
  "expressionValues": {
      ":id":     $util.parseJson($util.dynamodb.toDynamoDBJson($ctx.args.id))
  }
} )
#end
$util.qr($GetRequest.put("query", $query))
#if( !$util.isNullOrEmpty($ctx.stash.authFilter) )
  $util.qr($GetRequest.put("filter", $util.parseJson($util.transform.toDynamoDBFilterExpression($ctx.stash.authFilter))))
#end
$util.toJson($GetRequest)
## [End] Get Request template. **
```

In this case, nothing is set into the metadata.modelObjectKey, so the fallback id is used. Also, the underlying behavior changed from a getitem to a query, which is strange and unexpected.

**Comment by samjett247** [comment]
Looks like there is a preAuth step where the modelObjectKey is *supposed* to be inserted into the resolver pipeline. However, it was/is not getting inserted. I think it was my addition of a custom resolver for the `init` phase that made this preAuth resolver get generated. See preAuth resolver below - this was the missing piece:

```
## [Start] Set the primary key. **
$util.qr($ctx.stash.metadata.put("modelObjectKey", {
  "taskid": $util.dynamodb.toDynamoDB($ctx.args.taskid)
}))
## [End] Set the primary key. **
{}
```

**Comment by samjett247** [comment]
Confirmed that, unless you specify the names for each query to be implemented, the queries will be generated with an "id" to identify them with instead of the specified @primaryKey field. in the example above, if you specify below in the schema.graphql, you will get an incorrect `get` query that tries to use `id` to query the item:

```
type testtype
  @model
  {
      myidname: ID! @primaryKey
      fieldnameone: String
      fielnametwo: String
  }
```

Instead, if you use the following, you will get the correct `get` queries:

```
type testtype
  @model(queries: {get: "getTesttype", list: "listTestTypes"})
  {
      myidname: ID! @primaryKey
      fieldnameone: String
      fielnametwo: String
  }
```

I assume this applies to update mutations as well, as these are not working by default.

**Comment by cjihrig** [comment]
Thanks for reporting this. I believe the issue should be fixed by https://github.com/aws-amplify/amplify-cli/pull/9409. Until that is released, you should be able to work around the issue by renaming your model from `testtype` to `Testtype`.
