### ISSUE TITLE
A Typo "filterEpression" exists in generated resolver 

### ISSUE THREAD

**Issue by lizepeng** [aws-amplify/amplify-cli#9393]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When I read the vtl code generated by amplify, I found there is a type `filterEpression` in it.

```velocity
#if( !$util.isNullOrEmpty($filter) )
  #set( $filterExpression = $util.parseJson($util.transform.toDynamoDBFilterExpression($filter)) )
  #if( !$util.isNullOrBlank($filterExpression.expression) )
    #if( $filterEpression.expressionValues.size() == 0 )
      $util.qr($filterEpression.remove("expressionValues"))
    #end
    #set( $ListRequest.filter = $filterExpression )
  #end
#end
```

### Expected behavior

`filterEpression` should be fixed to `filterExpression`

### Reproduction steps

1. generate resolvers by using cmd `amplify api gql-compile`
2. check the file `Query.listCustomers.req.vtl`

### GraphQL schema(s)

<details>

```graphql
type Customer @model {
  customer_id: ID!
  customer_name: String
  logo: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by akshbhu** [comment]
Hi @lizepeng 

I have reproduced the bug. thanks for reporting it
