### ISSUE TITLE
There are no DynamoDB resources configured in your project currently

### ISSUE THREAD

**Issue by flgatormike** [aws-amplify/amplify-cli#9397]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.5

### What operating system are you using?

Windows

### Amplify Categories

function

### Amplify Commands

add, pull

### Describe the bug

Using Amplify Studio I created a model, then "saved and deployed" successfully. Then I ran "amplify pull", but when I try to create a function "amplify function add" I get the error "There are no DynamoDB resources configured in your project currently"

Maybe I am missing something, but when I deploy and then pull, shouldn't I have the updated ddb model in my project?

### Expected behavior

I expect DynamoDB resources configured in my project.

### Reproduction steps

1. Create model in Amplify Studio
2. amplify pull
3. amplify function add
4. get error "There are no DynamoDB resources configured in your project currently"

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
@flgatormike Did you answer 'yes'  `Do you plan on modifying this backend?`?

**Comment by cjihrig** [comment]
Closing due to a lack of followup, but we can revisit this issue if needed.
