### ISSUE TITLE
`@hasOne` field causes push operations to fail, when the referenced type has a`@primaryKey` containing 2 (or more) sort key fields.

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#9401]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.2.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

macOS 12.0.1

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I am working on migrating my app to the v2 amplify GraphQL transformer. My setup was working fine with the v1 transformer.
When the `@hasOne` field described in this bug is commented out, the project "compiles" and pushes correctly.

One of my types has a primary key, with 2 sort key fields; see attached partial schema.

When running
`amplify api push --yes` or `amplify push --yes`, I get the following error:
```
✖ An error occurred when pushing the resources to the cloud
🛑 Invalid @hasOne on Post:associatedTawk. Provided fields do not match the size of primary key(s) for TawkCandidate
InvalidDirectiveError: Invalid @hasOne on Post:associatedTawk. Provided fields do not match the size of primary key(s) for TawkCandidate
    at getRelationalPrimaryMap (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/src/utils/schema.ts:129:13)
    at AuthTransformer.protectRelationalResolver (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts:526:59)
    at AuthTransformer.generateResolvers (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts:348:16)
    at GraphQLTransform.transform (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:252:21)
    at _buildProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:563:37)
    at buildAPIProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:520:24)
    at transformGraphQLSchema (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:393:29)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:166:5)
    at async Promise.all (index 0)
    at providersPush (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:139:3)
    at AmplifyToolkit.pushResources [as _pushResources] (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:96:9)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

After some digging around with a local clone of `amplify-cli`, it looks like in the vicinity of
`@aws-amplify/graphql-auth-transformer/src/utils/schema.ts:129:13` (the first line in the stack trace above), 
the variable `const relatedPrimaryFields` (defined on line 125) contains the following payload:
`ownerSub,localId#tawkVersion`

I.e., `TawkCandidate`'s 2 sort keys (`localId` and `tawkVersion`) occupy a **single** element in the array joined with a `"#"` character -- throwing off the argument length comparison and triggering an error.

### Expected behavior

The app should "compile" and push successfully...

### Reproduction steps

Run `amplify api push --yes` or `amplify push --yes`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type TawkCandidate
  @model(subscriptions: {level: off})
  @auth(
     rules: [
       {allow: owner, ownerField: "ownerSub", identityClaim: "sub", operations: [read]},
       {allow: public, operations: [read]},
       {allow: private, provider: iam, operations: [create, read, update, delete]}
     ]
) {
  ownerSub: String!
    @primaryKey(sortKeyFields: ["localId", "tawkVersion"])
    @index(name: "byAuthor", sortKeyFields: ["createdAt"])
  localId: String!
  tawkVersion: String!
  # ...
}

# ...

type Post
  @model(subscriptions: {level: off})
  @searchable
  @auth(
     rules: [
      {allow: owner, ownerField: "ownerSub", identityClaim: "sub", operations: [read, update, delete]},
      {allow: public, operations: [read]},
      {allow: private, provider: iam, operations: [create, read, update, delete]}
    ]
) {
  id: ID!
  ownerSub: String! @index(name: "byAuthor", sortKeyFields: ["createdAt"])

  associatedTawk_localId: String
  associatedTawk_tawkVersion: String
  associatedTawk: TawkCandidate @hasOne(fields: ["ownerSub", "associatedTawk_localId", "associatedTawk_tawkVersion"])
  # ...
}


```

</details>

### Log output

<details>

```
# Put your logs below this line

If this would be of assistance, please advise which kinds of "sensitive data" may appear in the logs...
At a glance I don't see any but I don't want to accidentally miss some.
```

</details>

### Additional information

As noted above:

After some digging around with a local clone of `amplify-cli`, it looks like in the vicinity of
`@aws-amplify/graphql-auth-transformer/src/utils/schema.ts:129:13` (the first line in the stack trace above), 
the variable `const relatedPrimaryFields` (defined on line 125) contains the following payload:
`ownerSub,localId#tawkVersion`

I.e., `TawkCandidate`'s 2 sort keys (`localId` and `tawkVersion`) occupy a **single** element in the array joined with a `"#"` character -- throwing off the argument length comparison and triggering an error.

**Comment by Dennis-Dekker** [comment]
Have the same issue, but with the @manyToMany directive. CLI does allow to change the primary key, but not to add sort keys.

**Comment by sundersc** [comment]
Thanks for reporting this issue. I'm working on it.

**Comment by Dennis-Dekker** [comment]
@sundersc I just pulled the newest version of the CLI, but this have this issue. I'm using the @manyToMany directive, but get the same error: 
`An error occurred during the push operation: Invalid @hasOne on ItemLocation:item. Provided fields do not match the size of primary key(s) for Item`
This is my schema:
```
type Item @model
    @auth(rules: [{ allow: private }])
{
    id: ID! @primaryKey(sortKeyFields:["itemID"]) # This is the client ID
    itemID: ID! # This is the item ID (sortkey)
    parentIDs: [ID!] @index(name:"ByParent", queryField:"ItemByParent")
    parents: [Item!] @hasMany(fields:["parentIDs"])
    childIDs: [ID!] @index(name:"ByChild", queryField:"ItemByChild")
    children: [Item!] @hasMany(fields:["childIDs"])
    data: AWSJSON
    type: String!
    locations: [Location!] @manyToMany(relationName: "ItemLocation")
}

type Location @model
    @auth(rules: [{ allow: private }])
{
    id: ID! @primaryKey(sortKeyFields:["locationID"]) # This is the client ID
    locationID: ID! # This is the location ID (sortkey)
    parentIDs: [ID!] @index(name:"ByParent", queryField:"LocationByParent")
    parents: [Item!] @hasMany(fields:["parentIDs"])
    childIDs: [ID!] @index(name:"ByChild", queryField:"LocationByChild")
    children: [Item!] @hasMany(fields:["childIDs"])
    data: AWSJSON
    type: String!
    items: [Item!] @manyToMany(relationName: "ItemLocation")
}
```
The schema works fine, until I add `(sortKeyFields:["itemID"])` and/or `(sortKeyFields:["locationID"])` to the schema. I don't use the @hasOne directive in this schema, but it still shows up in the error. I'm I doing something wrong here?

**Comment by brighterfrog** [comment]
Mine was an error introduced from the @auth definition. If you remove it, run it through it's fine. Add @auth in and that error pops.

**Comment by Dennis-Dekker** [comment]
Thanks, I just checked and it seems to work without the @auth directive. I still need it tho, but for development it's nice to have this at hand. I will forward this finding to the dev working on this, maybe it will help with solving the issue.

**Comment by ataibarkai** [comment]
I just submitted a new bug report (https://github.com/aws-amplify/amplify-cli/issues/9573) which manifests with a `hasMany` field. The offending line is the one preceding the line fixed in this issue. cc @sundersc
