### ISSUE TITLE
@primaryKey transformer does not override id field in appsync

### ISSUE THREAD

**Issue by pencilshinchan** [aws-amplify/amplify-cli#9402]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

NPM

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

https://docs.amplify.aws/cli/graphql/data-modeling/#setup-database-tables

The Amplify docs state that any table created with the @model transformer will have an id field defined as the partition key unless overridden by using the @primaryKey transformer. Optionally a sort key can also be specified.

I have created the simple GraphQL schema below.
<detail>
```
 type prodord @model @auth(rules: [{ allow: private }]) {
  pord_pk: String! @primaryKey(sortKeyFields: ["pord_sk"])
  pord_sk: String!
    @index(
      name: "listOrderItemsIndex"
      queryField: "itemsInOrder"
      sortKeyFields: ["pord_pk"]
    )
  type: String!
    @index(
      name: "typeIndex"
      queryField: "listItemsByType"
      sortKeyFields: ["type_sk"]
    )
  userOrProduct: String
    @index(name: "productOrUserIndex", queryField: "userOrProduct")
  type_sk: String!
  fname: String
  lname: String
  email: String
  avatar: String
  company: String
  name: String
  unitPrice: Int
  quantity: Int
} 

```
</detail>

When performing an Amplify push everything is created successfully. 

When looking at Dynamodb the pk and sk are defined as specified in the schema, and all of the indexes have been created correctly.

However when looking at the API in AppSync the query for getProdord does not allow the use of the PK and SK for queries only the id field which has an asterixis beside it - which I assume indicates that it is required when querying. In order to allow queries off of a PK/SK combination (or just the PK) an additional GSI with a sort key would have to be defined off of the PK and SK.

### Expected behavior

When using the @primaryKey transformer the default behavior of using the id field to get and list rows either by using the AppSync UI or via an API call should be overridden. 

Should be able to query either off of the PK only, or a combination of the PK and SK. The option does not exist in the AppSync queries UI.

### Reproduction steps

1. Create a new graphQL API using the CLI
2. Edit the schema using the schema supplied in the description
3. Perform an Amplify push - select 'y' for all options

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type prodord @model @auth(rules: [{ allow: private }]) {
  pord_pk: String! @primaryKey(sortKeyFields: ["pord_sk"])
  pord_sk: String!
    @index(
      name: "listOrderItemsIndex"
      queryField: "itemsInOrder"
      sortKeyFields: ["pord_pk"]
    )
  type: String!
    @index(
      name: "typeIndex"
      queryField: "listItemsByType"
      sortKeyFields: ["type_sk"]
    )
  userOrProduct: String
    @index(name: "productOrUserIndex", queryField: "userOrProduct")
  type_sk: String!
  fname: String
  lname: String
  email: String
  avatar: String
  company: String
  name: String
  unitPrice: Int
  quantity: Int
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

The current workaround is to create an additional GSI off of the PK and SK to allow queries off of those fields.

**Comment by cjihrig** [comment]
Thanks for reporting this. I can reproduce the issue and am working on a fix. Until then, please try changing the model name from `prodord` to `Prodord`.

**Comment by rwdueck** [comment]
Just capitalizing the model name and pushing to the cloud resulted in a few failures with the resolvers. I ended up removing the graphql API and pushing it up again with the model name capitalized. 

Tested queries and mutations in Appsync. Everything seems to be working as expected. Thanks.
