### ISSUE TITLE
GraphQl Auth directive not working correctly with imported auth (cognito user pool)

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-cli#9408]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

with npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

windows

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

I am using Graphql Api for my Amplify App.
The amplify app auth is imported from an existing cognito user pool (amplify import auth).
I can create and read my TlgDataTemplate **but not update it.**

See my two connected model with their directive :

```gql
type TlgDataTemplate @model 
@auth(rules: [
  {allow: owner}, 
  {allow: owner, ownerField: "itemViewers", operations: [read]},
  {allow: owner, ownerField: "itemEditors", operations: [update, read]},
  {allow: groups, groups: ["MegaUsers"]},
  {allow: groups, groupsField: "organizationMegaUsersGroup"},
  {allow: groups, groupsField: "projectMegaUsersGroup"}
  {allow: groups, groupsField: "projectUsersGroup", operations:[read]},
])
{

  id: ID! @primaryKey
  name: String

  name: String! 
  description: String

  itemEditors: [String] 
  itemViewers: [String] 
  organizationMegaUsersGroup: String!
  projectMegaUsersGroup: String!
  projectUsersGroup: String

  createdBy: String
  updatedBy: String

  tlgDataRoadmap: [TlgDataRoadmap] @hasMany
}

type TlgDataRoadmap @model
  @auth(rules: [
    {allow: owner},
    {allow: groups, groups: ["MegaUsers"]},
    {allow: groups, groupsField: "organizationMegaUsersGroup"},
    {allow: groups, groupsField: "projectMegaUsersGroup"}
    {allow: groups, groupsField: "projectUsersGroup"},
  ])
  {

  id: ID! @primaryKey
  name: String

  tlgDataTemplateTlgDataRoadmapId: ID!
  tlgDataTemplate: TlgDataTemplate @belongsTo

  organizationMegaUsersGroup: String!
  projectMegaUsersGroup: String!
  projectUsersGroup: String

  createdBy: String
  updatedBy: String
}
```

When i try to update TlgDataTemplate as normal user i got this issue : 

![image](https://user-images.githubusercontent.com/79509459/147947415-b6f1d45b-0b6f-4565-8b40-0dab0bafbb29.png)

The automatic Mutation.updateTlgDataTemplate.req.vtl : 

```vtl
## [Start] Mutation Update resolver. **
## Set the default values to put request **
#set( $mergedValues = $util.defaultIfNull($ctx.stash.defaultValues, {}) )
## copy the values from input **
$util.qr($mergedValues.putAll($util.defaultIfNull($ctx.args.input, {})))
## set the typename **
## Initialize the vars for creating ddb expression **
#set( $expNames = {} )
#set( $expValues = {} )
#set( $expSet = {} )
#set( $expAdd = {} )
#set( $expRemove = [] )
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $Key = $ctx.stash.metadata.modelObjectKey )
#else
  #set( $Key = {
  "id":   $util.dynamodb.toDynamoDB($ctx.args.input.id)
} )
#end
## Model key **
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $keyFields = [] )
  #foreach( $entry in $ctx.stash.metadata.modelObjectKey.entrySet() )
    $util.qr($keyFields.add("$entry.key"))
  #end
#else
  #set( $keyFields = ["id"] )
#end
#foreach( $entry in $util.map.copyAndRemoveAllKeys($mergedValues, $keyFields).entrySet() )
  #if( !$util.isNull($ctx.stash.metadata.dynamodbNameOverrideMap) && $ctx.stash.metadata.dynamodbNameOverrideMap.containsKey("$entry.key") )
    #set( $entryKeyAttributeName = $ctx.stash.metadata.dynamodbNameOverrideMap.get("$entry.key") )
  #else
    #set( $entryKeyAttributeName = $entry.key )
  #end
  #if( $util.isNull($entry.value) )
    #set( $discard = $expRemove.add("#$entryKeyAttributeName") )
    $util.qr($expNames.put("#$entryKeyAttributeName", "$entry.key"))
  #else
    $util.qr($expSet.put("#$entryKeyAttributeName", ":$entryKeyAttributeName"))
    $util.qr($expNames.put("#$entryKeyAttributeName", "$entry.key"))
    $util.qr($expValues.put(":$entryKeyAttributeName", $util.dynamodb.toDynamoDB($entry.value)))
  #end
#end
#set( $expression = "" )
#if( !$expSet.isEmpty() )
  #set( $expression = "SET" )
  #foreach( $entry in $expSet.entrySet() )
    #set( $expression = "$expression $entry.key = $entry.value" )
    #if( $foreach.hasNext() )
      #set( $expression = "$expression," )
    #end
  #end
#end
#if( !$expAdd.isEmpty() )
  #set( $expression = "$expression ADD" )
  #foreach( $entry in $expAdd.entrySet() )
    #set( $expression = "$expression $entry.key $entry.value" )
    #if( $foreach.hasNext() )
      #set( $expression = "$expression," )
    #end
  #end
#end
#if( !$expRemove.isEmpty() )
  #set( $expression = "$expression REMOVE" )
  #foreach( $entry in $expRemove )
    #set( $expression = "$expression $entry" )
    #if( $foreach.hasNext() )
      #set( $expression = "$expression," )
    #end
  #end
#end
#set( $update = {} )
$util.qr($update.put("expression", "$expression"))
#if( !$expNames.isEmpty() )
  $util.qr($update.put("expressionNames", $expNames))
#end
#if( !$expValues.isEmpty() )
  $util.qr($update.put("expressionValues", $expValues))
#end
## Begin - key condition **
#if( $ctx.stash.metadata.modelObjectKey )
  #set( $keyConditionExpr = {} )
  #set( $keyConditionExprNames = {} )
  #foreach( $entry in $ctx.stash.metadata.modelObjectKey.entrySet() )
    $util.qr($keyConditionExpr.put("keyCondition$velocityCount", {
  "attributeExists": true
}))
    $util.qr($keyConditionExprNames.put("#keyCondition$velocityCount", "$entry.key"))
  #end
  $util.qr($ctx.stash.conditions.add($keyConditionExpr))
#else
  $util.qr($ctx.stash.conditions.add({
  "id": {
      "attributeExists": true
  }
}))
#end
## End - key condition **
#if( $context.args.condition )
  $util.qr($ctx.stash.conditions.add($context.args.condition))
#end
## Start condition block **
#if( $ctx.stash.conditions && $ctx.stash.conditions.size() != 0 )
  #set( $mergedConditions = {
  "and": $ctx.stash.conditions
} )
  #set( $Conditions = $util.parseJson($util.transform.toDynamoDBConditionExpression($mergedConditions)) )
  #if( $Conditions.expressionValues && $Conditions.expressionValues.size() == 0 )
    #set( $Conditions = {
  "expression": $Conditions.expression,
  "expressionNames": $Conditions.expressionNames
} )
  #end
  ## End condition block **
#end
#set( $UpdateItem = {
  "version": "2018-05-29",
  "operation": "UpdateItem",
  "key": $Key,
  "update": $update
} )
#if( $Conditions )
  #if( $keyConditionExprNames )
    $util.qr($Conditions.expressionNames.putAll($keyConditionExprNames))
  #end
  $util.qr($UpdateItem.put("condition", $Conditions))
#end
$util.toJson($UpdateItem)
## [End] Mutation Update resolver. **
```

### Expected behavior

Need to Create / Read / Update / delete my dynamodb elements using graphql api correctly and following specific auth directives

### Reproduction steps

1. Create amplify project (react)
2. import Auth (existing cognito user pool)
3. create GraphQl api 
4. add auth directive like above

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by julienlaurent-migso** [comment]
Hello, 
I found a working solution for me.

1. I have updated my @auth rules like : 
```
@auth(rules: [
  {allow: owner, ownerField: "createdBy", provider: userPools}, 
  {allow: owner, ownerField: "itemViewers", operations: [read], provider: userPools},
  {allow: owner, ownerField: "itemEditors", operations: [update, read], provider: userPools},
  {allow: groups, groupsField: "groupEditors", provider: userPools},
  {allow: groups, groupsField: "groupViewers", operations:[read], provider: userPools}
])

itemEditors: [String] 
  itemViewers: [String] 
  groupEditors: [String]
  groupViewers: [String]

```
2. Delete all .vtl files in the resolvers api folder
3. Delete all .vtl files in the build/resolvers api folder
4. Amplify mock || push 

I think in certain circumstance that i do not know the graphql transformer v2 is not editing correctly the vtl files...

If you have some advices related to this issue ? Thank you a lot

**Comment by edwardfoyle** [comment]
@julienlaurent-migso when you say you tried to "update TlgDataTemplate as normal user", was that user listed in the `owner` or `itemEditor` fields? If not, it would not have permission to edit the entity. In your updated schema, it shouldn't be necessary to specify `provider: userPools` as that is the default.

`amplify mock` will place resolver files in the `resolvers` directory but they will be removed after the mock server is terminated. Unless you are specifically overwriting some VTL resolvers, the `resolvers` directory in your project should be empty. The `build/resolvers` directory will be populated every time `amplify api gql-compile` or `amplify push` is run and contains the resolvers that will be included in the push

**Comment by julienlaurent-migso** [comment]
Hello @edwardfoyle, 
I have checked the authentification acces with the command `amplify status api -acm <model>` and everything is correct.
Everything works correctly when my resolver's folder is empty.
But when it is not empty some transformer issues happen (the mock is not working, and if i push my backend and my frontend, the graphql requests are not working correctly). 

**Is there a specific commande to terminate the mock server ?** 

See in my case, before launch `amplify mock`, my resolver folder is empty : 
![image](https://user-images.githubusercontent.com/79509459/149289104-38c833a8-2744-43d8-90db-8907997eead4.png)

After the mock, all the resolver's files are correctly created :
![image](https://user-images.githubusercontent.com/79509459/149289411-2131d7b7-1b04-45c5-8eef-0dac48518382.png)

So, if i kill the terminal :
![image](https://user-images.githubusercontent.com/79509459/149289569-da41dc76-2e75-442a-b408-0bf4f3435b4d.png)

All the resolver's files are still in the folder:
![image](https://user-images.githubusercontent.com/79509459/149289632-59e6865c-4b72-4752-9d70-d1dde7c0d767.png)

And at this moment, if i launch again a mock server my issues come..

You can see below, i launched again a mock server and in this case, it deleted all the resolver's files .. :
![image](https://user-images.githubusercontent.com/79509459/149290039-8371ab3a-a14f-4ab2-b167-b41a074e58cd.png)

**Comment by josefaidt** [comment]
Hey @julienlaurent-migso are you still experiencing this issue? If you close the mock server with ctrl+c does it remove the resolvers as expected, or after killing the VSCode integrated terminal can you see if the process is still running (`lsof -i :20002`)?

**Comment by julienlaurent-migso** [comment]
Hi @josefaidt, Yes "ctrl+c" remove the resolvers, perfect ! 
Thank you very much for the trick ! It was annoying to do this action manually.
I have still lot of thing to learn. I close this issue
