### ISSUE TITLE
'amplify pull' does not pull down aws-exports.js file

### ISSUE THREAD

**Issue by goldwareJapan** [aws-amplify/amplify-cli#9416]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.5

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

'amplify pull' does not pull down aws-exports.js file.

I deleted and created cognito ( auth ). I need to update aws-exports  file on other frontend project

### Expected behavior

aws-exports.js file to be updated. 

### Reproduction steps

1 web frontend  + amplify project
1 ios frontend project ( which already did amplify pull )

at backend project delete auth. create auth. which changes cognito id.
at ios `amplify pull`. aws-exports file not changed. even if you delete aws-exports file, `amplify pull` won't create it.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

There was a same issue. But it closed automatically. https://github.com/aws-amplify/amplify-cli/issues/5512

workaround: 
Delete `amplify` folder on ios project. but you have to go through all questions

**Comment by krikork** [comment]
Hard to tell but this might be related to an issue I started seeing 12 hours ago. We have an automated amplify build triggered on every code change. With the last build we started seeing the following error on the front end:

`Error: Region is missing`

The error seems to happen when we make any requests to s3. 

Comparing the latest build to an older one I can see that the amplify-meta.js file is missing the output block from the "s3Media" section. That's where the region had been usually configured.

**Comment by josefaidt** [comment]
Hey @goldwareJapan :wave: thanks for raising this! In your iOS app did you originally select to _not_ modify the backend?

```
> amplify pull --appId d1vfckhhiu71it --envName staging
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Amplify AppID found: d1vfckhhiu71it. Amplify App name is: amplifyapp
Backend environment staging found in Amplify Console app: amplifyapp
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using none
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? No
```

If so, we will need to run the full `amplify pull` command with the `appId` and `envName` as shown in the sample above to update the exports file.

**Comment by goldwareJapan** [comment]
> did you originally select to not modify the backend?

Yes. We did select not

>  run the full amplify pull command with the appId and envName 

Tried with full argument. still same result. `aws-exports.js` file not being created. 

```
❯❯❯ ls apps/back/src/aws-exports.js 
apps/back/src/aws-exports.js
❯❯❯ mv apps/back/src/aws-exports.js apps/back/src/aws-exports1.js
❯❯❯ ls apps/back/src/aws-exports.js 
ls: apps/back/src/aws-exports.js: No such file or directory
❯❯❯ amplify pull --appId $appId --envName dev
Opening link: https://ap-northeast-1.admin.amplifyapp.com/admin/*******/dev/verify/
✔ Successfully received Amplify Studio tokens.
Amplify AppID found: *******. Amplify App name is: ******
Backend environment dev found in Amplify Console app: ******

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.

❯❯❯ ls apps/back/src/aws-exports.js 
ls: apps/back/src/aws-exports.js: No such file or directory
```

Is it because I selected 
Source Directory Path:   apps/back/src

**Comment by goldwareJapan** [comment]
> Is it because I selected
> Source Directory Path: src

tried with `src`. still same.

**Comment by goldwareJapan** [comment]
as experiment I created new folder and tried pulling as javascript with no frame work.
```
❯❯❯ amplify pull --appId ****** --envName dev                                                                                      cognito ✭ ✖
Opening link: https://ap-northeast-1.admin.amplifyapp.com/admin/******/dev/verify/
✔ Successfully received Amplify Studio tokens.
Amplify AppID found: ******. Amplify App name is: ******
Backend environment dev found in Amplify Console app: ******
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using none
? Source Directory Path:  apps/back/src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? No

Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.
```

and tried deleting `aws-exports.js` and pulled with full command. it is not creating file again.
https://github.com/aws-amplify/amplify-cli/issues/9416#issuecomment-1005286276

**Comment by goldwareJapan** [comment]
on a main react project with `Do you plan on modifying this backend? Yes`

 tried deleting aws-exports.js and amplify pull. It creates `aws-exports.js` file again.

**Comment by goldwareJapan** [comment]
OK. Now I have a more serious problem.

When I checkout to another env and push. it created 2 Cognito pools. but `aws-exports.js` file does not change.

I have no idea where to get newly created env's `cognito_user_pool_id`. ( I can copy it from Cognito admin console. Don't want it to be hardcoded. I want it to be changed with amplify commands )

Because I want my production users to be on 1 user pool and dev users on another user pool.

**Comment by josefaidt** [comment]
Hey @goldwareJapan thank you for those details!  I was able to successfully reproduce two issues:

- `cognito_user_pool_id` value is not updated in `aws-exports.js` when pulling environments in a project where we selected to _not_ modify the backend
- `cognito_user_pool_id` value is not updated in `aws-exports.js` after pushing a new environment, requiring us to run `amplify env checkout <newly-created-environment>` to update the value

**Reproduction Steps:**

1. create new project `amplify init -y`
2. add auth with defaults `amplify add auth`
3. push `amplify push -y`
4. observe `aws_user_pools_id` reflects newly created userpool
5. add another environment `amplify env add next`
6. push `amplify push -y`
7. observe `cognito_user_pool_id` is not updated, run `amplify env checkout next` to update the value in `aws-exports.js`
8. in a separate directory, pull the existing app with `amplify pull --appId <existing-amplify-app-id> --envName dev`, choose _not_ to modify backend
9. observe `aws-exports.js` is created and the `cognito_user_pool_id` is populated correctly
10. pull the `next` environment with `amplify pull --envName next`
11. observe `cognito_user_pool_id` is not updated
	1. **note**: we are unable to run `amplify env checkout next` to update the exports file as we did not choose modify the backend when we pulled the app
	2. we are unable to remove the `aws-exports.js` file and recreate with `amplify pull --envName next`

As a workaround, we can remove the second project's `amplify/` directory as well as the `aws-exports.js` file and re-pull the new environment to generate the `aws-exports.js` with the new User Pool: `amplify pull --appId <existing-amplify-app-id> --envName dev`

**Comment by josefaidt** [comment]
@yuth this appears to be also affecting the GraphQL API's URL

**Comment by yuth** [comment]
> @yuth this appears to be also affecting the GraphQL API's URL

It is because the CLI is treating all the values from the prev env as custom config and retaining the value. I am working on a fix for that
