### ISSUE TITLE
Is it possible to use a circular reference in a model?

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-cli#9417]
I am trying to create a circular reference in a schema.
I tried to follow the instructions on https://docs.amplify.aws/cli-legacy/graphql-transformer/connection/#has-one.
But when I try to push, I get the following...

An error occurred during the push operation: Schema validation failed.
Directive "connection" may not be used on OBJECT.

**Which Category is your question related to?**
??

**Amplify CLI Version** 
7.6.5

**What AWS Services are you utilizing?**
Amplify, AppSync, S3, Dynamo

**Provide additional details e.g. code snippets**
```
type Item 
    @model
	@key(name: "byParent", fields: ["id"]) {
    id: ID!
    subItems: [Item] @connection(keyName: "byParent", fields: ["id"])
    name: String
}
```

**Comment by lazpavel** [comment]
Hi @LeoReubelt, you should be able to use circular reference in a model.

Can you please provide the contents from `amplify/cli.json`?

**Comment by LeoReubelt** [comment]
Hi @lazpavel.  Thanks for responding. cli.json is pasted below. I


```
{
    "features": {
        "graphqltransformer": {
            "addmissingownerfields": true,
            "validatetypenamereservedwords": true,
            "useexperimentalpipelinedtransformer": false,
            "enableiterativegsiupdates": true,
            "secondarykeyasgsi": true,
            "skipoverridemutationinputtypes": true
        },
        "frontend-ios": {
            "enablexcodeintegration": true
        },
        "auth": {
            "enablecaseinsensitivity": true,
            "useinclusiveterminology": true
        },
        "codegen": {
            "useappsyncmodelgenplugin": true,
            "usedocsgeneratorplugin": true,
            "usetypesgeneratorplugin": true,
            "cleangeneratedmodelsdirectory": true,
            "retaincasestyle": true
        },
        "appsync": {
            "generategraphqlpermissions": true
        },
        "project": {
            "overrides": true
        }
    }
}
```

**Comment by lazpavel** [comment]
can you add to the `"graphqltransformer"` section `"transformerversion": 1,`. Let me know if you still have the issue

**Comment by josefaidt** [comment]
Hey @LeoReubelt are you still experiencing this issue?

**Comment by LeoReubelt** [comment]
@josefaidt i am actually working on a different project right now. i was still having problems when i switched, but i will close this issue for now. And if i can't figure it out when i resume, i will reopen it.
