### ISSUE TITLE
Error when installing AWS Amplify

### ISSUE THREAD

**Issue by saidaantonyan** [aws-amplify/amplify-cli#942]
I'm following instructions to install AWS Amplify described here https://aws-amplify.github.io/docs/.

**In terminal I do:**
npm install -g @aws-amplify/cli
**And get the following error:**

npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davit/.npm/_logs/2019-02-25T20_20_56_846Z-debug.log

 **- OS: macOS Mojave
 - NodeJS version is 11.10.0
 - Ruby version is ruby 2.3.7p456**

**Comment by kaustavghosh06** [comment]
@saidaantonyan Looks like a user permission issue.
Please use `sudo npm install -g @aws-amplify/cli`

**Comment by yuth** [comment]
Feel free to re-open if the proposed solution doesn't work

**Comment by bdaz** [comment]
FYI, this does still seem to be an issue, and `sudo` only works if you also include the `--unsafe-perm` flag (per https://github.com/nodejs/node-gyp/issues/454).
