### ISSUE TITLE
My new enviroinment treated as new app

### ISSUE THREAD

**Issue by goldwareJapan** [aws-amplify/amplify-cli#9423]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 
7.6.5

**What AWS Services are you utilizing?**
amplify

**Provide additional details e.g. code snippets**

When I `amplify env add` and `amplify push`
[this](https://docs.aws.amazon.com/amplify/latest/userguide/team-workflows-with-amplify-cli-backend-environments.html) 
docs says I will have 2 env in backend envidoinments. But I ended up with 2 same application.  Is it intended?

| Expected | Current|
| ------------- | ------------- |
| ![Screen Shot 2022-01-05 at 12 28 10](https://user-images.githubusercontent.com/35557320/148156241-36b5e243-cf36-483a-a00f-53424bdb0be5.png) | ![Screen Shot 2022-01-05 at 12 28 49](https://user-images.githubusercontent.com/35557320/148156358-ac191eee-8fb8-49b1-a3ce-1285df6866c0.png) |

Maybe because of that I can't select env to deploy

**Comment by edwardfoyle** [comment]
@goldwareJapan as long as you are using the same AWS account for both environments, they should both be added to a single Amplify App. Are you using the same AWS profile / credentials as the original amplify environment when creating the new amplify environment?

**Comment by goldwareJapan** [comment]
I don't think that is possible. 

I have 2 was profiles set. but they are completely different accounts.

So if I select a different profile it creates env on the whole other account. ( i tried and confirmed it. image attached )

![Screen Shot 2022-01-07 at 16 28 47](https://user-images.githubusercontent.com/35557320/148508130-3aa46eb1-8b55-4936-a4a3-51628e7b38da.png)

**Comment by cjihrig** [comment]
@goldwareJapan when you run `amplify env add`, you need to select the same profile. It looks like you picked a different profile here.

**Comment by goldwareJapan** [comment]
As mentioned [here](https://github.com/aws-amplify/amplify-cli/issues/9423#issuecomment-1007198307) if i select different profile it is created on whole different account. 

for now i created env with web console. So we can close it. but still ...
