### ISSUE TITLE
id field is not of type string for model with circular reference

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-cli#9428]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, storage, api

### Amplify Commands

codegen, push

### Describe the bug

I am working on an ios app. I have the following model on my local schema.

```
type InnerItems 
@model 
@auth(rules: [{allow: private, operations: [read, create, update]}])
@key(name: "byInnerItems", fields: ["name", "status", "type"]) {
  id: ID!
  items: [InnerItems] @connection(keyName: "byInnerItems", fields: ["id"])
  name: String
}
```

when I execute amplify push, it results in the following error.

✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: id field is not of type String

If I change the model to...

```
type InnerItems 
@model 
@auth(rules: [{allow: private, operations: [read, create, update]}])
@key(name: "byInnerItems", fields: ["name"]) {
  id: String!
  items: [InnerItems] @connection(keyName: "byInnerItems", fields: ["id"])
  name: String
}
```

and run amplify push, I get the following error.

Code generation failed with the following error 
id field on InnerItems should be of type ID.
Failed to create models in the cloud: Modelgen job creation failed
✔ All resources are updated in the cloud

And when I run amplify codegen models I get the following errors.

id field on InnerItems should be of type ID
Error: id field on InnerItems should be of type ID

### Expected behavior

I would expect codegen to work with an id of type ID!.

### Reproduction steps

See description of bug.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type InnerItems 
@model 
@auth(rules: [{allow: private, operations: [read, create, update]}])
@key(name: "byInnerItems", fields: ["name", "status", "type"]) {
  id: ID!
  items: [InnerItems] @connection(keyName: "byInnerItems", fields: ["id"])
  name: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line
InvalidDirectiveError: id field is not of type String
2022-01-05T16:14:15.325Z|info : amplify version core  {"version":true,"yes":false}

```

</details>

**Comment by lazpavel** [comment]
Hi @LeoReubelt, the issue you're experiencing is because the types in the @key directive fields list do not match the types of the @connection directive fields. 

You should be able to use it by changing the `name` field type as in
```
type InnerItems 
     @model 
     @auth(rules: [{allow: private, operations: [read, create, update]}])
     @key(name: "byInnerItems", fields: ["name"]) {
  id: ID!
  items: [InnerItems] @connection(keyName: "byInnerItems", fields: ["id"])
  name: ID
}
```

Please reopen if you still have issues
