### ISSUE TITLE
Make DynamoDB tables an output from cf templates

### ISSUE THREAD

**Issue by benoj** [aws-amplify/amplify-cli#943]
Is is possible to set the dynamodb table name/streamarn as an output from the amplify cli. I need access to the tables from another CF based deployment.

**Comment by elorzafe** [comment]
@benoj currently the table name and region is exported on `aws-exports.js` file on the `aws_dynamodb_table_schemas` attribute.

**Comment by benoj** [comment]
Thanks @elorzafe - I'm trying to write a lambda function which listens to the dynamodb stream using the serverless framework.  This unfortunately requires that I reference the cf output or ARN - which is a timestamp value and therefore likely to continuously change. By adding the tablename, and stream arn to the outputs in the CF template will allow me to reference the stream arn by referencing the cf-stack in aws.

I won't be able to use the aws-exports.js from my serverless.yml

**Comment by yuth** [comment]
I am marking this as an enhancement. We do store the ARN in  `<project-root>/amplify/backend/amplify-meta.json` which you could use in the mean time

**Comment by ChristopheBougere** [comment]
+1 for the feature request.
Also, I don't see the `aws_dynamodb_table_schemas` in `aws-exports.json` neither that in `<project-root>/amplify/backend/amplify-meta.json`.
My tables are AppSync resolvers.
I actually don't see the table names anywhere in my project folder.

**Comment by hisham** [comment]
+1. Also currently need lambda created within amplify to read from the dynamodb table created by the graphql transformer.

**Comment by kaustavghosh06** [comment]
We released this feature as a part of our latest CLI version release - 4.16.1.
You can checkout the documentation out here for more information - https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation
