### ISSUE TITLE
@manyToMany relation throws a warning DataStore - subscriptionError, Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'chatroom' in type 'ChatRoomUser' is undefined @ 'onDeleteChatRoomUser/chatroom'"}]} with a model name 'ChatRoom' but works well with 'Chatroom' WHY?

### ISSUE THREAD

**Issue by rosmu** [aws-amplify/amplify-cli#9441]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

MacOS Catalina v10.15.7

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

I have the below schema which is throwing a warning `[WARN] 42:42.781 DataStore - subscriptionError, Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'chatroom' in type 'ChatRoomUser' is undefined @ 'onDeleteChatRoomUser/chatroom'"}]}.` when Datastore is initialised. However, when the type `ChatRoom` is renamed to `Chatroom` the warning goes away and works as expected. Is there anything special about the model name `ChatRoom` which can cause this issue?

```
type ChatRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  users: [User] @manyToMany(relationName: "ChatRoomUser")
}

type User @model @auth(rules: [{allow: public}])  {
  id: ID!
  chats: [ChatRoom] @manyToMany(relationName: "ChatRoomUser")
}
```

### Expected behavior

The schema should generate the valid client code regardless the type name case sensitivity.

### Reproduction steps

1. Use the schema below to create the API

```
type ChatRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  users: [User] @manyToMany(relationName: "ChatRoomUser")
}

type User @model @auth(rules: [{allow: public}])  {
  id: ID!
  chats: [ChatRoom] @manyToMany(relationName: "ChatRoomUser")
}
```

2. Initialize the datastore as documented here[](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/)
3. Observe the warning on the developer console:
    ``[WARN] 42:42.781 DataStore - subscriptionError, Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'chatroom' in type 'ChatRoomUser' is undefined @ 'onDeleteChatRoomUser/chatroom'"}]}.`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type ChatRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  users: [User] @manyToMany(relationName: "ChatRoomUser")
}

type User @model @auth(rules: [{allow: public}])  {
  id: ID!
  chats: [ChatRoom] @manyToMany(relationName: "ChatRoomUser")
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
I think what's happening here is that the CLI is generating the following `ChatRoomUser` type:

```gql
type ChatRoomUser {
  id: ID!
  chatRoomID: ID!
  userID: ID!
  chatRoom: ChatRoom!
  user: User!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
}
```

Notice the casing of the `chatRoom` field. It looks like the front end code is trying to access `chatroom` with different casing. Does regenerating the front end code make any difference?
