### ISSUE TITLE
amplify import auth headless

### ISSUE THREAD

**Issue by kellycastrof** [aws-amplify/amplify-cli#9458]
**Please describe which feature you have a question about?**
I want to know how to use amplify import auth with a sh script
**Provide additional details**
I follow the instructions of the documentation, however it doesn't mention how to use it. I use parameter --categories, but it still asks me for config in the terminal.
**What AWS Services are you utilizing?**
I'm using amplify auth
**Provide additional details e.g. code snippets**
I have a sh script with a config like this (same as the documentation)

**amplify.sh**
```
AUTHCONFIG="{\
\"userPoolId\": \"myproject-userpool-id\",\
\"webClientId\": \"appid-web\",\
\"nativeClientId\": \"appid-native\",\
\"identityPoolId\": \"myproject-idp-poolid\"\
}"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"

amplify import auth --categories $CATEGORIES
```

**Comment by johnpc** [comment]
I am able to reproduce this issue and there are some recent changes to `amplify import auth` that may be the cause. Adding this to our bug board for prioritization.

**Comment by edwardfoyle** [comment]
Hi @kellycastrof can you try using the `amplify import auth --headless` feature? I just realized we don't have documentation for it (working on that now), but it follows the same pattern as the headless commands [here](https://docs.amplify.aws/cli/usage/headless/#headless-category-payloads) and the payload shape is defined [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-headless-interface/src/interface/auth/import.ts)

**Comment by kellycastrof** [comment]
@edwardfoyle  it works, thanks!
