### ISSUE TITLE
Best Practice to have multiple apps share common amplify backend

### ISSUE THREAD

**Issue by abhishek0207** [aws-amplify/amplify-cli#946]
My application has a web project and a react native project. Both of them uses a common amplify backend. 
What are the best practices or patterns that can be used in order to maintain the sync between the amplify files of the two projects?
Both web and mobile are separate project with their own git repositories.

Thanks in Advance

**Comment by yuth** [comment]
We have it documented in [amplify-configure-project](https://aws-amplify.github.io/docs/cli/init#amplify-configure-project) section of the docs

Please feel free to re-open if this doesn't help

**Comment by mayteio** [comment]
[Updated link](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#amplify-configure-project) for those coming from Google.

**Comment by Bulletninja** [comment]
> We have it documented in [amplify-configure-project](https://aws-amplify.github.io/docs/cli/init#amplify-configure-project) section of the docs
> 
> Please feel free to re-open if this doesn't help

Is it possible to have multiple apps under the same domain(Possibly (ideally, not limited to) via subdomains)?

**Comment by borisdayma** [comment]
> Is it possible to have multiple apps under the same domain(Possibly (ideally, not limited to) via subdomains)?

I was thinking of doing it by having:
* "www" and root point to "master"
* app.mydomain.com point to "app" branch, which could be completely independent from master

However I don't think it's very clean and can make development maintenance difficult…
Were you able to have multiple repositories associated to the same domain?

**Comment by Bulletninja** [comment]
Yes, turns out it can be done pretty easily from the amplify console, you just need to type the subdomain directly where it asks for your domain.
Also there is an article from aws that proposes a mono repo approach. That'd probably be a better development experience.
