### ISSUE TITLE
Unable to Push Changes to Lambda Layer

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-cli#9460]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

14.17.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

MacOS 11.6

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

Make a small change to one of the .js files in my lambda layer. Then call amplify push. The change will get reverted and "No changes detected" is reported. 

Also tried amplify function push. Which does go about talking to the cloud. However it eventually reverts the changes too. It also doesn't ask about the layer version config as it used to.

### Expected behavior

A question about the lambda layer config and then push the layer to the cloud successfully. Without reverting the local changes.

### Reproduction steps

1. make a change to a .js file in the lambda layer
2. amplify push
3. check the change in the .js file and you will see it has reverted back.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Was talking on Discord and tried removing some old layer versions. Current version is 49. I removed versions 1, 2, and 3 and confirmed those versions were removed as per the web console. This did not help at all unfortunately.

**Comment by josefaidt** [comment]
Hey @Etep15 :wave: thanks for taking the time to file this! As mentioned in Discord please send the link to your amplify.zip to amplify-cli@amazon.com

Possibly related?:

- https://github.com/aws-amplify/amplify-cli/issues/8525 (had ~50 layer versions, experienced CFN errors on legacy layer version creation, removing latest/problematic layer resolved issue)
- https://github.com/aws-amplify/amplify-cli/issues/7476 (layer was being restored to previous version, similar to this issue where layer is "restored" to the previous version on push -- new changes are removed)

**Comment by Etep15** [comment]
Thanks for the links @josefaidt. Unfortunately I wasn't able to find anything would work.

I've since made a change to one of my lambda files (not layer) and have the same problem. I tried an **amplify pull** and then **push**. Same problem.

After I make the change if I do an **amplify status** it shows that there is indeed changes that need to be pushed. But again, push is reverting them. Here's a snippet...

amplify status

    Current Environment: dev
    
    ┌──────────┬───────────────────────┬───────────┬───────────────────┐
    │ Category │ Resource name         │ Operation │ Provider plugin   │
    ├──────────┼───────────────────────┼───────────┼───────────────────┤
    │ Function │ participant           │ Update    │ awscloudformation │

So currently I can't upload any changes at all. Any suggestions? No idea how it got to this state. This particular function was last updated yesterday. So sometime yesterday, things got out of whack. 

Recommendations?

**Comment by Etep15** [comment]
I figured out the issue. I'm an idiot. Hope I didn't waste too many people's time. My editor was in the wrong folder. Apologies. 

Tip for any others who are wondering what kind of voodoo is going on if this happens. Make sure you are are in the "backend" folder, not the "#current-cloud-backend". Visual Studio Code wasn't making it very apparent, which again, may be how I setup the project.
