### ISSUE TITLE
How to make OpenSearch less rigid? e.g wildcards / fuzziness

### ISSUE THREAD

**Issue by mattfysh** [aws-amplify/amplify-cli#9464]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

API (Graphql)

**Amplify CLI Version** 

v7.6.5

**What AWS Services are you utilizing?**

AppSync + OpenSearch

**Provide additional details e.g. code snippets**

What is the best way to get more results from OpenSearch?

This is the best I can do so far without digging into the VTL templates:

```js
{
  or: searchterm
    .trim()
    .split(/\s+/)
    .map(word => ({
      name: {
        wildcard: `*${word}*`,
      },
    })),
}
```

I understand there are additional settings related to fuzziness that can be sent with an OpenSearch query, but it looks as is if the current AppSync utility does not support it 

`$util.transform.toElasticsearchQueryDSL`
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html#transformation-helpers-in-utils-transform

What would be the best way to approach this and tailor the search experience so it is more forgiving and returns more populated result sets?

**Comment by johnpc** [comment]
You can look into configuring your opensearch to index ngrams of the fields that you want to be fuzzy. I'm not sure exactly how to do that from the cli though
