### ISSUE TITLE
Allow multiple S3 buckets

### ISSUE THREAD

**Issue by dmost714** [aws-amplify/amplify-cli#9467]
### Is this feature request related to a new or existing Amplify category?

storage

### Describe the feature you'd like to request

I would like the ability to create multiple S3 buckets in the same project.

Why? The existing S3 bucket and associated lambda trigger operates on objects put into the bucket, transforming them into new objects. It is a best practice to put new objects into different bucket (to avoid recursive triggers).

```
➜  MyCoolProject git:(dev) amplify add storage
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
⚠️ Amazon S3 storage was already added to your project.
```

### Describe the solution you'd like

I would like the amplify-cli to allow me to create more than one S3 bucket (and associated trigger), and would like the ability to give S3 triggers meaningful names.

Feature parity in Amplify Studio is nice to have.

### Describe alternatives you've considered

I'll try to work around this limitation by adding the 2nd bucket and trigger via `amplify add custom`.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by johnpc** [comment]
Thank you for providing this feedback!

**Comment by nadetastic** [comment]
Related to https://github.com/aws-amplify/amplify-cli/issues/5836

**Comment by 0618** [comment]
Thanks for the feature request. Multi-Bucket feature is available in Amplify Gen2, Please check out for more details here https://aws.amazon.com/blogs/mobile/add-multiple-storage-buckets-amplify/

Amplify Gen1 is being deprecated, we are not adding new features to it.
