### ISSUE TITLE
Parameters.json location in new public project

### ISSUE THREAD

**Issue by HieronymusLex** [aws-amplify/amplify-cli#9475]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
7.6.5
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I've provisioned a fresh create-react-app project (`npx create-react-app app`) Amplify project and added auth. I want to publish this project on GitHub therefore I've added the team-provider-info.json, cli.json and hooks directories in the amplify directory to my .gitignore. Amplify updates the .gitignore file so with `build/` therefore the `amplify/backend/auth/foo/build/parameters.json` is excluded from version control, but when I check the project out and run `amplify init`, the CLI throws an error saying  `amplify/backend/auth/foo/build/parameters.json` does not exist. 

What is solution to this? The error seems to be resolved if I copy the `parameters.json` of the build directory up a level to `project/amplify/backend/auth/foo/`. Is this the right thing to do?

**Comment by josefaidt** [comment]
Hey @HieronymusLex :wave: to clarify, are you cloning the project into a new directory and running `amplify init`?

**Comment by HieronymusLex** [comment]
Yes cloning to a new directory and running amplify init from there.

**Comment by josefaidt** [comment]
Hey @HieronymusLex thank you for clarifying. This appears to be a bug and I have documented it here https://github.com/aws-amplify/amplify-cli/issues/9508, as a workaround can you try running `amplify build` and then re-run `amplify init`?

**Comment by HieronymusLex** [comment]
@josefaidt that works for me as a workaround! I'll close this issue in favour of #9508
