### ISSUE TITLE
Code generation failed with the following error

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#9476]
Amplify CLI Version 7.6.7.
AWS Services : auth api storage.

Hi, what is this error ?
**✔ Generated GraphQL operations successfully and saved at src/graphql
Code generation failed with the following error 
ENOENT: no such file or directory, lstat '/Users/rudy/Desktop/site/amplify/#current-cloud-backend/auth/site9aa3eb1e'.
✔ All resources are updated in the cloud**

**Comment by johnpc** [comment]
If that file is missing you may need to re-pull. Did you select "no" when responding to the prompt "do you intend to modify the backend"?

**Comment by rudyhadoux** [comment]
With a new deploy, the problem is over. Thanks.
