### ISSUE TITLE
amplify codegaen models - after migration to V2

### ISSUE THREAD

**Issue by bergmorten** [aws-amplify/amplify-cli#9503]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue, Not applicable

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
amplify --v
7.6.5

```

</details>

## After migrating GraphQL Transformer v1 to v2, amplify models codegen models gives warnings

```
amplify codegen models
GraphQL schema compiled successfully.

Edit your schema at C:\tmp\test\amplify\backend\api\modelgentest\schema.graphql or place .graphql files in a directory at C:\tmp\test\amplify\backend\api\modelgentest\schema
warning: Model Blog has field posts of type Post but its not connected. Add a @connection directive if want to connect them.
warning: Model Post has field blog of type Blog but its not connected. Add a @connection directive if want to connect them.
warning: Model Post has field comments of type Comment but its not connected. Add a @connection directive if want to connect them.
warning: Model Comment has field post of type Post but its not connected. Add a @connection directive if want to connect them.
Successfully generated models. Generated models can be found in C:\tmp\test\src

```

### Expected behavior

`amplify codegen models ` should return correct models after migration to V2 graphQL transformers

### Reproduction steps

1. `amplify init` (select default)
2. `amplify add api `(select blog example with relationships)
3. `amplify push`
4. `amplify migrate api`
5. `amplify codegen`  (select typescript and level 2 depth)
6. `amplify codegen models` <--- This returns warnings

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @bergmorten :wave: can you post the contents of your `amplify/cli.json` file? I'm curious if the `useappsyncmodelgenplugin` feature flag is set to false.

As a follow up, can you confirm whether `amplify push` was ran after migrating the API? I believe the feature flags are updated after a migration and successful push of the migration.

**Comment by bergmorten** [comment]
The 'useappsyncmodelgenplugin' is set to false. Should I try to enable it?

I did a push right after the migration.

**Comment by aspearman** [comment]
I'm having this same issue. Though my `cli.json` is lacking the `userappsyncmodelgenplugin` flag altogether:

```
{
    "features": {
        "graphqltransformer": {
            "addmissingownerfields": true,
            "validatetypenamereservedwords": true,
            "useexperimentalpipelinedtransformer": true,
            "enableiterativegsiupdates": true,
            "transformerversion": 2,
            "suppressschemamigrationprompt": true,
            "improvePluralization": true
        },
        "project": {
            "overrides": true
        }
    }
}
```

I don't remember what CLI version I used when I migrated it; I migrated when I only had one model a few weeks ago.

**Comment by josefaidt** [comment]
Hey @bergmorten please try setting that flag to true. 
@aspearman this feature flag should be located under `codegen`, are you using a CI/CD pipeline to deploy your project by chance? ![image](https://user-images.githubusercontent.com/5033303/150153330-7652ce85-ddb8-4cf8-9282-8ad40449f57d.png)

**Comment by josefaidt** [comment]
1. install Amplify CLI 4.39.0
2. `amplify init`
3. `amplify add api` > GraphQL > Select One-to-Many example schema
4. `amplify push -y`
5. install latest Amplify CLI 7.6.9
6. `amplify migrate api`
7. `amplify push -y`
8. `amplify codegen models`
9. observe connection warning and `cli.json` is missing `codegen` feature flags
	```json
    {
      "features": {
        "graphqltransformer": {
          "addmissingownerfields": true,
          "validatetypenamereservedwords": true,
          "useexperimentalpipelinedtransformer": true,
          "enableiterativegsiupdates": false,
          "transformerversion": 2,
          "suppressschemamigrationprompt": true
        },
        "project": {
          "overrides": true
        }
      }
    }
	```

As a workaround, manually adding the feature flag `useappsyncmodelgenplugin` to `amplify/cli.json` and setting its value to `true` mitigates the warnings when running `amplify codegen models`

```json
"codegen": {
      "useappsyncmodelgenplugin": true
    }
```

Marking as a bug 🙂

**Comment by bergmorten** [comment]
Changing the settings in cli.json did the trick. Models are now generated without warnings and with relationships.

**Comment by aspearman** [comment]
Same here, fixed. Thanks @josefaidt!
