### ISSUE TITLE
Multiple @function usages throws: The FunctionDirectiveStack.json stack defines more than 500 resources.

### ISSUE THREAD

**Issue by deagudelo** [aws-amplify/amplify-cli#9511]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

sudo npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.18.1

### Amplify CLI Version

7.6.8

### What operating system are you using?

Tried on Ubuntu 20.04 and Mac (Big Sur & Monterey)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

My lambda functions in a separate project using Serverless Framework by company policy. I have to use the @function graphql-transformer to access them from my graphql schema operations. 
I'm currently over 125 resolvers and I cannot add any more because of a limit in the number of resources in the generated FunctionDirectiveStack.json, thrown by CloudFormation. The `amplify push` operation is unsuccesssful. This means I can't deploy new code using it from graphql.

### Expected behavior

After the limit of resources and size given by CloudFormation, another stack should be created so that all the functions defined with @function are well handled and the `amplify push` operation is successful.

### Reproduction steps

1. Define certain number (more than 125 in my case) of resolvers using @function 
2. amplify push

### Log output

<details>
```
# Put your logs below this line
The FunctionDirectiveStack.json stack defines more than 500 resources.
```
</details>

### Additional information

The schema is really big itself so I'm already minifying using minify-json, and this is not helping given the error has to do with number of resources rather than size.

This is already mentioned in other [issue](https://github.com/aws-amplify/amplify-cli/issues/3265) but with lower limits and was addressed with an increase of the limits in CloudFormation, which is not sustainable and will not work in this case.

**Comment by johnpc** [comment]
You should be able to exercise some control over your stack by using stack mappings, which documentation is being added soon. You can find details in this PR where the docs are being added: https://github.com/aws-amplify/docs/pull/3848/files

**Comment by josefaidt** [comment]
Closing as docs PR has been merged 🙂

**Comment by akhilv77** [comment]
I am Facing the same error while amplify push, is there any workaround for this issue ?
