### ISSUE TITLE
ElasticSearch index contains duplicates, how to clear it out?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9520]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.8

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I daren't touch anything manually after losing a weeks dev time after trying to delete a key last year!

So, no.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When searching our api for a @searchable model we are finding that we are getting returned some old data. Seems its not been cleared from the index.

We've been making changes to the schema and I'm not sure if the index over the last year has got "stuck". My plan was to clear out the index and get it to rebuild but I have no idea how to do that or if it is safe to do so. I've seen references in the docs to send commands to ES via http but which commands and which are safe?

Last time I tried being smart like this I locked us out of doing a deployments for 2 weeks.

### Expected behavior

Deleted data shouldn't appear in the index?

Or give me an easy and safe way to reindex. Yes I'm aware that reindexing might be costly but with the amount of data we've got its not an issue but it is an issue having it broken.

I'd have loved to see a button in the back end of the new Admin Studio (or whatever its called this quarter) that would do this for us, sadly can't see it.

### Reproduction steps

Project is 18 months in so we've been adding and removing data, changing schemas and all sorts. Some how we've ended up with some duff data and in honestly I'm not sure how.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by johnpc** [comment]
We spoke about this offline, but for the purposes of recording the results of the conversation for future readers:

1. Log in to your AWS console
2. Visit the Amazon OpenSearch Service console
3. Find your domain and click it's name to access its details
4. Click the "Access Dashboard" url at the top right
5. If there are permissions issues accessing it, update the configuration to include a stanza with your public IP address
6. Use the Kibana interface there to manage the data inside your elastic search indexes. This may require background information on how to use kibana and how to write raw elastic search queries.
