### ISSUE TITLE
How to know which ES/OpenSearch instance is used by which Environment?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-cli#9521]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.8

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Nope.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I've been trying to see what state our ES instance indexes are in but I see we have 4 listed, 2 for ES and 2 for opensearch. The ES ones seem empty and the opensearch ones have differing amounts of data. Which are still used? I'm guessing the ES ones are no longer used, are they safe to delete? I'm loathed to manually delete anything after getting drift on a deployment last year that cost us mightly.

Say I want to reindex one of hte other opensearch instances, how do I know which is used by which environment?

To add to the confusion I've got 4 environments and a total of 4 ES/OS instances, are some of those environments using ES and others OS? How to know? And again how to know which to delete if any?

### Expected behavior

Its easier to find which instance is used by which environment.

Allow a rename or label to be added for easier identification.

How to know which instances are actually used and where?

![image](https://user-images.githubusercontent.com/1674590/149326962-fef69619-425d-46ba-b59c-db7bf54aa796.png)

### Reproduction steps

Got to OpenSearch in the console and try to work out which instance belongs to which environment. Can't see anywhere that gives you any pointers.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by l-hendriks** [comment]
you can try to match the ids (h5..., fw... etc) in the cloudformation definition. In the cloudformation console select the stack (you might need to search for the child stack where the ES is defined in) and then outputs/properties properties tab

**Comment by sundersc** [comment]
@PeteDuncanson To find it through AWS console, find the application's searchable stack in CloudFormation. Select the stack on the list and go to `Resources` tab and search for type `AWS::Elasticsearch::Domain`.

**Comment by PeteDuncanson** [comment]
Lovely, thank you @sundersc :)

**Comment by R-Art-project** [comment]
Hi @PeteDuncanson!! If I understand well, what you are looking for can find it in the OpenSearch Dashboard in the Tab Tag.

I leave you a reference below:
<img width="902" alt="Screenshot 2023-02-24 at 3 37 32 AM" src="https://user-images.githubusercontent.com/66227758/221146226-87436f0c-b5c3-4bcb-a8eb-8a473590c086.png">

**Comment by majirosstefan** [comment]
I would ask to reopen this and use similar naming that Amplify is using with DynamoDB tables (they ends with environment suffix). (as Enhancement)
