### ISSUE TITLE
@manyToMany directive with sortkey fails to push, provided fields do not match the size of the primary keys

### ISSUE THREAD

**Issue by Dennis-Dekker** [aws-amplify/amplify-cli#9526]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

7.6.9

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When I try to push my schema, I get an error stating:

```
× An error occurred when pushing the resources to the cloud
� An error occurred during the push operation: Invalid @hasOne on ItemLocation:item. Provided fields do not match the size of primary key(s) for Item
```
Pushing the schema without the sortkey in the @primaryKey of both models succeeds without problems, however adding the sortkeys results in the error.

A similar issue (#9401) has been fixed in a previous PR (#9459) and has been released in version 7.6.9, but this didn't fix the problem for me.

### Expected behavior

The push should deploy two model tables with sortkeys.

### Reproduction steps

1. `amplify init`
2. `amplify add auth`
2. `amplify add api` --> blank schema
3. Add schema from graphQL schema (see below)
4. `amplify push --y` (or `amplify push --allow-destructive-graphql-schema-updates --y` if starting with schema with sortkeys commented out) 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
#input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Item @model
    @auth(rules: [{ allow: private }])
{
    id: ID! @primaryKey(sortKeyFields:["itemID"]) # This is the client ID
    itemID: ID! # This is the item ID (sortkey)
    parentIDs: [ID!] @index(name:"ByParent", queryField:"ItemByParent")
    parents: [Item!] @hasMany(fields:["parentIDs"])
    childIDs: [ID!] @index(name:"ByChild", queryField:"ItemByChild")
    children: [Item!] @hasMany(fields:["childIDs"])
    data: AWSJSON
    type: String!
    locations: [Location!] @manyToMany(relationName: "ItemLocation")
}

type Location @model
    @auth(rules: [{ allow: private }])
{
    id: ID! @primaryKey(sortKeyFields:["locationID"]) # This is the client ID
    locationID: ID! # This is the location ID (sortkey)
    parentIDs: [ID!] @index(name:"ByParent", queryField:"LocationByParent")
    parents: [Item!] @hasMany(fields:["parentIDs"])
    childIDs: [ID!] @index(name:"ByChild", queryField:"LocationByChild")
    children: [Item!] @hasMany(fields:["childIDs"])
    data: AWSJSON
    type: String!
    items: [Item!] @manyToMany(relationName: "ItemLocation")
}
```

</details>

### Log output

<details>

```
# Put your logs below this line

```

</details>

**Comment by johnpc** [comment]
I was able to reproduce this. I had to run `amplify add auth` as well in your repro instructions

**Comment by Dennis-Dekker** [comment]
Thanks, I will update the instructions

**Comment by Dennis-Dekker** [comment]
Someone else found (see comment in #9459) that removing the @auth directive results in amplify deploying the schema without errors, so maybe this has to do something with that.

**Comment by sundersc** [comment]
@Dennis-Dekker - That would still not produce the expected behavior. I see that including sortKey on the primaryKey is not playing well with `@manyToMany` directive. We are looking into this.

Another approach: would it be possible to remove the sort keys and create an index for the fields `itemID` and `locationID` in your case.

**Comment by Dennis-Dekker** [comment]
Thanks for your reply! We will implement the indexes for now to develop our product, but the sorkeys would be really nice to have. I will keep an eye out for any updates.

**Comment by ivadenis** [comment]
Same issue. Really hope to see this resolved.

**Comment by sundersc** [comment]
Sorry about the delay. The linked PR also needs some changes on the codegen side. We are working with codegen team to get this implemented.
