### ISSUE TITLE
amplify codegen generates incorrect types in API.ts file

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws-amplify/amplify-cli#953]
**Describe the bug**
For example I have graphql schema in AppSync:

```graphql
type AudioAlbum {
  id: ID!
  title: String
  tracks: [Track]
}

type Track {
  id: ID!
  title: String
}

type Query {
  getAudioAlbum(audioAlbumId: ID!): AudioAlbum
  getTrack(trackId: ID!): Track
}
```

Then I execute `amplify add codegen --apiId={appsync id}`
Then in autogenerated file API.ts I see the following types:
```typescript
export type GetAudioAlbumQuery = {
  __typename: string;
  id: string;
  title: string | null;
  tracks: Array<{
    __typename: "Track";
    id: string;
    title: string | null;
  } | null> | null;
};
export type GetTrackQuery = {
  __typename: string;
  id: string;
  title: string | null;
};
```
It is incorrect, because type 
```typescript
{
  __typename: "Track";
  id: string;
  title: string | null;
}
```
is not equal to type:
```typescript
{
  __typename: string;
  id: string;
  title: string | null;
}
```
There are different __typename properties.

**Expected behavior**
__typename must be the same. Or just remove __typename property from autogenerated types. And it will be great if there will be GetTrackQuery in GetAudioAlbumQuery like in AppSync schema:
```typescript
export type GetAudioAlbumQuery = {
  __typename: string;
  id: string;
  title: string | null;
  tracks: Array<GetTrackQuery | null> | null;
};
export type GetTrackQuery = {
  __typename: string;
  id: string;
  title: string | null;
};
```

**Comment by yuth** [comment]
@ildar-icoosoft whats the version of amplify cli do you have installed?

I manage to get the right `__typename` for the all the types. The expected `__typenames` are `AudioAlbum` and `Tracks` for `getAudioAlbum` and `getAudioAlbum` respectively
```typescript
export type GetAudioAlbumQuery = {
  getAudioAlbum:  {
    __typename: "AudioAlbum",
    id: string,
    title: string | null,
    tracks:  Array< {
      __typename: "Track",
      id: string,
      title: string | null,
    } | null > | null,
  } | null,
};

export type GetTrackQuery = {
  getTrack:  {
    __typename: "Track",
    id: string,
    title: string | null,
  } | null,
};
```

**Comment by ildar-icoosoft** [comment]
@yuth I have @aws-amplify/cli@1.1.6

Also here is my GetAudioAlbum function in API.service.ts:

```
async GetAudioAlbum(audioAlbumId: string): Promise<GetAudioAlbumQuery> {
    const statement = `query GetAudioAlbum($audioAlbumId: ID!) {
        getAudioAlbum(audioAlbumId: $audioAlbumId) {
          __typename
          id
          title
          tracks {
            __typename
            id
            title
          }
        }
      }`;
    const gqlAPIServiceArguments: any = {
      audioAlbumId
    };
    const response = (await API.graphql(
      graphqlOperation(statement, gqlAPIServiceArguments)
    )) as any;
    return <GetAudioAlbumQuery>response.data.getAudioAlbum;
  }
```

**Comment by yuth** [comment]
Oh I see what you are saying. Typescript does support using string literals in types. So it should not be a problem if the type says `__typename` is `Track` or `AudioAlbum`

**Comment by ildar-icoosoft** [comment]
@yuth The problem is that __typename: "Track"; is not equal to __typename: string;
I use this interfaces in application. For example, I'm getting album:
const album: GetAudioAlbumQuery = async GetAudioAlbum();
I expect that album.tracks will be GetTrackQuery[] type (like in graphql schema). But album.tracks IS NOT EQUAL to GetTrackQuery[]

Please reopen this issue
