### ISSUE TITLE
Angular monorepo structure question

### ISSUE THREAD

**Issue by arledesma** [aws-amplify/amplify-cli#9531]
**Which Category is your question related to?**

`N/A`

**Amplify CLI Version** 

`7.6.9`

**What AWS Services are you utilizing?**

`N/A`

**Provide additional details e.g. code snippets**

I want to start with a couple of points

1. Amplify Console supports a [monorepo build spec](https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html) that provides for multiple amplify projects within a single repository.
2. Amplify CLI project-level configurations for [monorepo](https://docs.amplify.aws/cli/project/monorepo/) directs users to use a single amplify backend per angular workspace.
3. Angular workspaces support [multiple discrete projects](https://angular.io/guide/file-structure#multiple-projects), not requiring a single backend and never directing users to use a single backend.
4. A single backend can turn a monorepo into a monolith.

With those points in mind, I am wondering how users of amplify should use the Amplify Console monorepo build spec with angular workspaces. The amplify-cli currently requires that `angular.json` [exist within the project directory](https://github.com/aws-amplify/amplify-cli/blob/4cc2b2c9bb7fa04d5722f758cdad7e7b8c3cafc7/packages/amplify-frontend-javascript/lib/framework-config-mapping.js#L56-L80) (oddly enough, this is only to provide a naïve hint for `DistributionDir` using the `outputPath` for the `defaultProject` which is not required in angular.json). This logic only exists for angular, for some reason, which greatly limits the use of amplify within an actual monorepo of discrete projects. Simply creating an empty `angular.json` in the angular project root avoids the error produced by amplify, but that is hacky and can cause additional issues with angular cli commands.  This leads to confusing workflow for developers attempting to perform an angular command or an amplify command.

Questions:

1. Why is angular the only framework that [throws an error](https://github.com/aws-amplify/amplify-cli/blob/4cc2b2c9bb7fa04d5722f758cdad7e7b8c3cafc7/packages/amplify-frontend-javascript/lib/framework-config-mapping.js#L63-L69) if it can not find the framework configuration file in the amplify project root?
2. With the inconsistency between Amplify Console monorepo build spec supporting multiple amplify applications and Amplify CLI monorepo 'recommended' flow only supporting a single application how should an angular only monorepo setup their repository to deploy multiple backend applications that each have their own web frontend?
3. Are we supposed to revert to using a single angular workspace per amplify application in a **monorepo**?
    - If we are supposed to use a single angular workspace per amplify application then what is the recommended method to share libraries between each of the angular workspaces?
    - How do repositories utilizing [nx](https://nx.dev/) work with this structure?

---
Related issue: #6888
This issue was answered with a link to https://docs.amplify.aws/cli/usage/monorepo#step-2-set-up-the-amplify-backend which is a recommendation, not a requirement. The framework-config-mapping requires that angular.json exist in the project root, which does not line up with it only being a recommendation.

**Comment by josefaidt** [comment]
Hey @arledesma :wave: apologies for the delay here!! Are you still experiencing this issue? From the [linked documentation](https://docs.amplify.aws/cli/project/monorepo/), it is recommended to set up a backend at the root of one of the frontend projects (e.g. `/apps/app1`), then in the second app (e.g. `/apps/app2`) run `amplify pull` to associate the backend created in app1

> For a monorepo setup, it is recommended to have the Amplify CLI initialize a new backend at the root of one of your frontend projects. In a different frontend directory, you can run amplify pull and select the Amplify app you want to associate your frontend with.

**Comment by arledesma** [comment]
@josefaidt The amplify console supports multiple backend projects in a monorepo.

How do we accomplish that, using the amplify cli, with what you are suggesting?
