### ISSUE TITLE
cannot deploy another env

### ISSUE THREAD

**Issue by yt-aidma** [aws-amplify/amplify-cli#9533]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.3

### Amplify CLI Version

7.6.9

### What operating system are you using?

Windows + WSL2 Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

OpenSearchStreamingLambdaFunction arn now arn:aws:lambda:{region}:{accountId}:function:OpenSearchStreamingLambdaFunction

so after change env with `amplify env checkout {env}`, `amplify push` stop with error `OpenSearchStreamingLambdaFunction already exists in stack arn:aws:cloudformation:~`

### Expected behavior

arn:aws:lambda:{region}:{AWS Account ID}:function:amplify-{Amplify app name}-{Amplify environment}-{Random string}-OpenSearchStreamingLambd-{Random string}

https://docs.amplify.aws/cli/graphql/troubleshooting/#backfill-opensearch-index-from-dynamodb-table

### Reproduction steps

1. write schema.graphql with @searchable
2. amplify push
3. amplify env add
4. amplify env checkout {new-env}
5. amplify push

### GraphQL schema(s)

type Post
  @model
  @searchable
  @auth(rules: [{ allow: private }]) {
  id: ID!
  title: String!
  sell: String!
  buy: String!
  description: String!
  timestamp: AWSTimestamp!
  deletedAt: String
  isCompetition: Boolean
  isPublished: Boolean
}

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I found error in cloudformation stack `SearchableStack`
amplify cli version 7.6.5 works

**Comment by cjihrig** [comment]
Thanks @aleksey-shmatov. I'll close this as a duplicate.
