### ISSUE TITLE
'amplify add storage' allows uppercase characters, then fails when pushing to cloud

### ISSUE THREAD

**Issue by johnrusch** [aws-amplify/amplify-cli#9542]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

`amplify version` => 7.6.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

storage

### Amplify Commands

add, push

### Describe the bug

When adding an S3 bucket, amplify cli allowed me to enter an uppercase character for the bucket name. When I eventually tried to push my changes to the cloud it failed because buckets can't have uppercase characters. Also cli didn't allow me to use a '-' even though I'm pretty sure you can use hyphens when naming buckets.

Just making an issue of this because it is annoying, spent a bit of time configuring storage and pushing and have to do it over again.

### Expected behavior

Stop me from naming a bucket with an uppercase character before it tries to create it.

### Reproduction steps

amplify add storage                                              
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✔ Provide a friendly name for your resource that will be used to label this category in the project: · resourcename
✔ Provide bucket name: · WishItStoppedMeIfITriedToDoSomethingLikeThis

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
<img width="937" alt="Screen Shot 2022-01-15 at 1 01 30 PM" src="https://user-images.githubusercontent.com/35750236/149637769-0c442cf0-4baa-4cb4-9471-110f7efee024.png">

**Comment by lazpavel** [comment]
Hi @johnrusch, thank you for reporting this issue.
The linked [PR](https://github.com/aws-amplify/amplify-cli/pull/9555) should fix this.
