### ISSUE TITLE
Upgrade of amplify-cli dependency error

### ISSUE THREAD

**Issue by jobypthomas** [aws-amplify/amplify-cli#9544]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

7.13.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

add, codegen, configure, configure project, env, init, pull, push, status, update

### Describe the bug

Not able to upgrade using the command "npm i -g @aws-amplify/cli". Current version is 7.6.5, latest version is 7.6.9. Current node version is 16.2.0, npm version 7.13.0. I tried on two different Macs (M1 and Intel).

### Expected behavior

Upgrade the amplify cli to 7.6.9

### Reproduction steps

npm i -g @aws-amplify/cli

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/@aws-amplify/cli/node_modules/graphql
npm ERR!   graphql@"^14.5.8" from @aws-amplify/amplify-category-api@1.2.0
npm ERR!   node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api
npm ERR!     @aws-amplify/amplify-category-api@"1.2.0" from @aws-amplify/cli@7.6.9
npm ERR!     node_modules/@aws-amplify/cli
npm ERR!       @aws-amplify/cli@"*" from the root project
npm ERR!     @aws-amplify/amplify-category-api@"1.2.0" from amplify-container-hosting@2.4.11
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-container-hosting
npm ERR!       amplify-container-hosting@"2.4.11" from @aws-amplify/cli@7.6.9
npm ERR!       node_modules/@aws-amplify/cli
npm ERR!         @aws-amplify/cli@"*" from the root project
npm ERR!   graphql@"^14.5.8" from @aws-amplify/graphql-auth-transformer@0.5.8
npm ERR!   node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer
npm ERR!     @aws-amplify/graphql-auth-transformer@"0.5.8" from @aws-amplify/cli@7.6.9
npm ERR!     node_modules/@aws-amplify/cli
npm ERR!       @aws-amplify/cli@"*" from the root project
npm ERR!     @aws-amplify/graphql-auth-transformer@"0.5.8" from amplify-provider-awscloudformation@5.8.8
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation
npm ERR!       amplify-provider-awscloudformation@"5.8.8" from @aws-amplify/cli@7.6.9
npm ERR!       node_modules/@aws-amplify/cli
npm ERR!         @aws-amplify/cli@"*" from the root project
npm ERR!       3 more (@aws-amplify/amplify-category-api, ...)
npm ERR!     1 more (@aws-amplify/graphql-relational-transformer)
npm ERR!   65 more (amplify-app, amplify-codegen, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm ERR! node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common/node_modules/relay-compiler
npm ERR!   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.1
npm ERR!   node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common/node_modules/@graphql-tools/relay-operation-optimizer
npm ERR!     @graphql-tools/relay-operation-optimizer@"^6.3.7" from @graphql-codegen/visitor-plugin-common@2.5.2
npm ERR!     node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/node_modules/@graphql-codegen/visitor-plugin-common
npm ERR!       @graphql-codegen/visitor-plugin-common@"^2.5.1" from amplify-codegen-appsync-model-plugin@1.24.4
npm ERR!       node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jobythomas/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jobythomas/.npm/_logs/2022-01-16T23_18_40_309Z-debug.log

```

</details>

**Comment by IvanCaceres** [comment]
I'm also running into this exact issue my amplify version is 7.6.3 and I'm trying to install @latest or 7.6.10

**Comment by josefaidt** [comment]
Hey @jobypthomas and @IvanCaceres :wave: thanks for raising this! I was able to downgrade npm to 7.13.0 and reproduce the issue where we are unable to install the CLI. Can you try upgrading npm to the latest v7 release? `npm i -g npm@7`

**Comment by IvanCaceres** [comment]
@josefaidt I can confirm it has solved my issue. Upgrading my npm v7 from 7.18.1 to npm@7 (latest/7.24.2) and installing aws-amplify/cli@latest has fixed the dependencies error.

**Comment by josefaidt** [comment]
Thanks for confirming @IvanCaceres 🙂 glad to hear you're back up and running!

**Comment by jobypthomas** [comment]
@josefaidt I confirm that your suggestion solved my issue as well. Thank you!
