### ISSUE TITLE
Cannot specify "-"(hyphen) in bucket name

### ISSUE THREAD

**Issue by kobakeiara** [aws-amplify/amplify-cli#9550]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.9

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

storage

### Amplify Commands

add

### Describe the bug

Cannot specify "-"(hyphen) in bucket name, When adding S3 with the "add storage" command.

----------------------
% amplify add storage
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✔ Provide a friendly name for your resource that will be used to label this category in the project: · s34a64d876
? Provide bucket name: › test-logs-20220118  

❯ Bucket name can only use the following characters: a-z 0-9 - and should have minimum 3 character and max of 47 character

### Expected behavior

Specify "-"(hyphen) in bucket name.

### Reproduction steps

% amplify add storage

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by danielleadams** [comment]
Hi @kobakeiara, thanks for opening this. I know hyphens are valid characters for S3 buckets, but Amplify only allows alphanumeric values for S3 bucket names because Amplify CLI uses `-` as a delimiter to name Amplify CLI-created buckets. Are you able to work around this or do your S3 buckets require hyphens in their names?

**Comment by danielleadams** [comment]
Marking this as a bug because we should have a clearer error message that Amplify-created S3 bucket names should be alphanumeric.

**Comment by sachscode** [comment]
The Error is here:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts#L95 
should create a custom validator with the regex 
'^[a-z0-9-]+$'
