### ISSUE TITLE
StreamARN to resource is not cleaned up after type was removed from schema

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#9553]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12

### Amplify CLI Version

7.6.5

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

function, api

### Amplify Commands

push

### Describe the bug

After removing a `@model` type from the schema that was referenced by a `function` resource `StreamARN` will be kept around and push is failing, dependency is not cleaned up.

export/getatt references are not removed from Lambda function and the tableA delete will go in "Update_rollback_complete"

### Expected behavior

During GQL compile a warning is printed about the reference and properly remove related CRUD resources dependencies and push should succeed

### Reproduction steps

1. Create Amplify App 
2. Add  GraphQL API with two models(tableA , tableB)
3 Add Lambda function with trigger template and add the trigger to one of the model(tableA) of the API
4 remove the tableA from the schema.graphql file

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by anurag128** [comment]
Hi Team, this behaviour still persists in the latest amplify CLI version 10.7.1
