### ISSUE TITLE
function custom policy error message points to old documentation URL

### ISSUE THREAD

**Issue by tjmcewan** [aws-amplify/amplify-cli#9558]
**Page**: [`https://docs.amplify.aws/function/custom-policies/`](https://docs.amplify.aws/function/custom-policies/)

**Feedback**: 

I've obviously got my custom-policies file wrong but the output error message directs me to the above non-existent page.

> An error occurred during the push operation: Invalid custom IAM policies in the [...] function.
> [...]
> Learn more about custom IAM policies for function: https://docs.amplify.aws/function/custom-policies

**Comment by flozender** [comment]
May I please work on this? Thanks!
