### ISSUE TITLE
How is the partition key selected when no `ID` Scalar type is included in a model?

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#956]
We have use cases where we'd like a non-ID type to be the partition key for a given table. For instance, for a Users table, we might want to have a String type with a custom name be the partition key. (Also, with Aurora Serverless support, the same question applies for forcing a field to be the primary key on mutation.) 

In the absence of a directive like `@primary` that Amplify and/or AppSync can use to determine partition / primary key, how are these keys selected? First field in the model, a field named "id"? 

It seems weird to me that you can effectively specify foreign-key relations with the `@connection` directive, but you can't specify the primary key of a table with a similar directive. I'm guessing the lack of such a directive is because GraphQL is designed to be agnostic to the backend implementation, but in the specific use cases of DynamoDB and Aurora Serverless, special directives to choose partition/primary keys would be helpful.

** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
Amplify (+CLI), AppSync, AWSAppSyncClient

**Comment by mikeparisstuff** [comment]
All @model types currently require a single hash key named "id". We are working on an RFC that will introduce new functionality and allow you to define and query custom indexes. The RFC should be available on GitHub in the near future and hopefully should answer your question in more detail.

**Comment by jkeys-ecg-nmsu** [comment]
Thank you.
