### ISSUE TITLE
Generated index.js for Cognito triggers is missing context & callback params

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-cli#9563]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.9

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

Adding the `auth` category with a Cognito Pre-signup or Post confirmation trigger generates an `index.js` that passes only the `event` param to each trigger (not `context` & `callback`):

```javascript
exports.handler = async event => {
  await Promise.all(modules.map(module => module.handler(event)));
  return event;
}
```

Thus, the user's trigger code in `custom.js` cannot invoke the `callback`.

### Expected behavior

The generated `index.js` that calls the trigger(s) should pass `context` & `callback` (in addition to `event`):

```javascript
exports.handler = async (event, context, callback) => {
  await Promise.all(modules.map(module => module.handler(event, context, callback)));
  return event;
}
```

### Reproduction steps

1. `add auth`
2.  Choose `Y` for Lambda triggers question
3. Select `Pre-signup` or `Post Confirmation`
4. For "functionality" choose `Create Your Own`
5. Finish, then look at `amplify/backend/function/<MyName>/src/index.js`
6. Notice it only passes the `event` param (not `context` & `callback`)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
The `callback` should not be needed. Please see the [Async handlers section of this page](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html). It probably makes sense to make `context` available though.

**Comment by cjihrig** [comment]
The Lambdas should work fine with synchronous code. Ultimately, callbacks, Promises, and `async/await` are just different ways of doing the same thing in JavaScript.

I've changed this from a feature request to a bug based on your most recent comment. The custom trigger should be updated to use an async function instead of the callback, and the `context` argument should be available.
