### ISSUE TITLE
Amplify @model + @index directive, limit not working

### ISSUE THREAD

**Issue by timfulmer** [aws-amplify/amplify-cli#9564]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

```
% amplify -v
7.6.5
```

**What AWS Services are you utilizing?**

Amplify + DynamoDB + AppSync

**Provide additional details e.g. code snippets**

So, I have an Amplify model setup, with a global secondary index on a field called `window` using the `@index` Amplify directive. As I am putting items into the DynamoDb table using the v3 JS AWS SDK, I bucket the items in 30 day window chunks. In DynamoDB console, I can run a query on the `byWindow` index, for `30days` partition key, and I get 51 results in DynamoDB.

![Screen Shot 2022-01-19 at 1 39 59 PM](https://user-images.githubusercontent.com/6497107/150218182-ac77e9fe-0acb-48ad-a55a-87c053c2d88a.png)

Now, when I run this GraphQL query, using the AppSync setup provided by the Amplify `@model` directive, I get 16 results:

```
query MyQuery {
  list(filter: {window: {eq: "30days"}}, limit: 100000) {
    items {
      id
      window
    }
  }
}
```

Even though I have set an arbitrarily large limit.

Now, I understand there is a 1MB size limit when talking to DynamoDB, and spot checking some of the 51 items, I am seeing item sizes ranging from 4-9kB. So, 16 of these should be about 144kB max. If we are we saying we only get 16 items from DynamoDB in a 1MB chunk, then something doesn't seem to be adding up correctly.

Feels like this is a common use case, and it is strange to me to require pagination on the front end to load 51 items with a total size of less than half a MB.

Am I missing something obvious?

**Comment by timfulmer** [comment]
Also, here is the RCU usage for the initial page of 50 in DynamoDb console. So, 16RCU for the initial 50, .5RCU for the last one, giving us:

```
16.5RCU * 8kB / RCU = 132kB <<< 1MB
```

![Screen Shot 2022-01-19 at 2 26 24 PM](https://user-images.githubusercontent.com/6497107/150226922-019b05cb-25b8-4db0-ab11-2120443f9254.png)

**Comment by josefaidt** [comment]
Hey @timfulmer :wave: apologies for the delay here!! Would you mind sharing a sample of your schema with the `@index` directive? Using this doc as a reference, we can run a query using this secondary index which will return the expected results rather than the `list*` queries https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-secondary-index

**Comment by josefaidt** [comment]
Hey @timfulmer :wave: are you still experiencing this issue?

**Comment by timfulmer** [comment]
Hi @josefaidt  thanks for the reply! Unfortunately I am on another project right now, and cannot say whether this behavior is still actual with latest amplify or not. It was a great stack to work on, and hopefully I’ll have an opportunity to do so again!

**Comment by josefaidt** [comment]
Thank you @timfulmer for the clarification and for the kind words! 😄 due to the circumstance I will close this issue for now, however if you run into this issue again please do not hesitate to reply back to this thread
