### ISSUE TITLE
Dynamic Groups authorization check not applied on Subscription Resolvers GraphQL Transformer V2

### ISSUE THREAD

**Issue by mrsimply** [aws-amplify/amplify-cli#9568]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

curl

### If applicable, what version of Node.js are you using?

v17.4.0

### Amplify CLI Version

7.6.10

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

push, Not applicable

### Describe the bug

When using Dynamic Groups for authorization check, those rules are not applied on Subscription Resolvers with the GraphQL Transformer V2. The CLI generated VTL code blocks containing the Auth checks for `onCreate`, `onUpdate` and `onDelete` are empty in the auth slot (in my schema example e.g. in file `Subscription.onCreateTodo.auth.1.req.vtl`, also see reproduction steps)

As a result Client throws: `[WARN] 12:11.281 DataStore - subscriptionError Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onCreateTodo on type Todo"}]}`

This bug might be related to #9466, maybe you have an idea @alex-vladut?
Queries and Mutations are working now, but the fix was not applied for Subscriptions?

### Expected behavior

Apply Dynamic Groups authorization check correctly for Subscriptions with GraphQL Transformer V2, therefore the VTL Resolver should be generated correctly.

### Reproduction steps

- Init a new Amplify project
- Create GraphQL API with Cognito User Pool Auth
- Use my simplified Schema as provided below
- Push API (and Auth)

The file `Subscription.onCreateTodo.auth.1.req.vtl` looks as follows (have a look at the empty if block in the middle, the Dynamic Groups authorization check should happen here):
```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#if( $util.authType() == "User Pool Authorization" )

#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

If you replace the Auth rule with `{ allow: owner }` for testing purpose, the file content will change like this, the block is filled correctly:

```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#if( $util.authType() == "User Pool Authorization" )
  #if( !$isAuthorized )
    #set( $ownerEntity0 = $util.defaultIfNull($ctx.args.owner, null) )
    #set( $ownerClaim0 = $util.defaultIfNull($ctx.identity.claims.get("username"), $util.defaultIfNull($ctx.identity.claims.get("cognito:username"), "___xamznone____")) )
    #if( $ownerEntity0 == $ownerClaim0 )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( !$isAuthorized )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

### GraphQL schema(s)

```graphql
# For testing purpose only

type Todo
  @model
  @auth(
    rules: [
      {
        allow: groups
        groupClaim: "cognito:username"
        groupsField: "owner"
        operations: [create, read]
      }
    ]
  ) {
  id: ID!
  owner: ID
  name: ID!
  description: String
}

```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mrsimply** [comment]
Thanks for your reply @alex-vladut. I'm looking forward to an official reply from AWS. The fact that  Real-time subscriptions are not supported for dynamic group authorization is really scary and jeopardizes our complete Data Model & Business Concept. It used to work in Transformers V1.

Am official  statement from AWS is very much appreciated!

**Comment by Dennis-Dekker** [comment]
@mrsimply Nice that you opened an issue on this topic, I have also been looking for a solution. First of all, are you sure that it worked in v1? I haven't used v1 personally, but the legacy documentation states that dynamic group auth has no impact on the subscriptions. Maybe they didn't update the documentation after changing this, or maybe I'm mistaken. You can check the v1 auth legacy documentation on this subject here: https://docs.amplify.aws/cli-legacy/graphql-transformer/auth/#authorizing-subscriptions. I have been looking for updates or comments on this subject in this Github repo and on the discord channel, but to me, it seems they never implemented dynamic group auth to the full extent.

**Comment by undefobj** [comment]
Dynamic Group Auth on Subscriptions is not supported in v1 or v2 as authorization checks are done in AppSync at connection time and not at Runtime. This feature will be worked on after the upcoming AppSync Runtime Filtering feature is launched which you can track here: https://github.com/aws/aws-appsync-community/issues/186

**Comment by mrsimply** [comment]
Thank you for clarification  @undefobj - Interesting, as the client error did not show with V1. I assume V1 did not return unauthorized. 

Looking forward to the overall solution!

**Comment by josefaidt** [comment]
Hey @mrsimply per the updates above I'll be closing this issue in favor of tracking the RFC mentioned and the existing feature request in this repo https://github.com/aws-amplify/amplify-cli/issues/2189. Please subscribe to the feature request for further updates 🙂

**Comment by SebSchwartz** [comment]
@undefobj It was working in the V1 :/
I was receiving all updates in real time and it a user was not in the same group, he didn't received it...

Here is our @auth that was making it work:
```
@auth(
    rules: [
      { allow: groups, groupsField: "clientId" }
      { allow: private, provider: iam, operations: [read, create, update] }
    ]
  )

# Field:
clientId: ID! 
```

**Comment by mrsimply** [comment]
> @undefobj It was working in the V1 :/ I was receiving all updates in real time and it a user was not in the same group, he didn't received it...
> Groups were set in a PreToken lambda. So the token sent to appsync have the groups filled in.

That is exactly how we implemented it. Still gives me a headache! 🤯

**Comment by undefobj** [comment]
To clarify - the bug in #9466 is still being looked into. That will be addressed. However subscriptions with dynamic auth has never been possible. We are working on a feature that will release soon in AppSync to address that so that it will be possible.
