### ISSUE TITLE
Closing the mock api Server removes custom auth resolvers

### ISSUE THREAD

**Issue by n0rb** [aws-amplify/amplify-cli#9571]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.9.1

### Amplify CLI Version

7.6.9

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

A. When creating a custom auth resolver (eg Mutation.createTodo.auth.1.req.vtl) in `<root>/amplify/backend/api/<APINAME>/resolvers` and then starting `amplify mock api` the script will copy all resolvers from `<root>/amplify/backend/api/<APINAME>/build/resolvers` to <`root>/amplify/backend/api/<APINAME>/resolvers` but also delete your custom auth resolver.

B. When you start `amplify mock api` without a custom auth resolver, but then edit a script-copied auth resolver in `<root>/amplify/backend/api/<APINAME>/resolvers`, the mock server will notice the change and do a reload (ie: "Mapping template change detected. Reloading...")

Your edited auth resolver file will actually stay in `<root>/amplify/backend/api/<APINAME>/resolvers` and the change is functional.

However if you now stop the mock server via ctrl+c and then start `amplify mock api` again (maybe on the next work day ...) the script will delete your auth resolver file from `<root>/amplify/backend/api/<APINAME>/resolvers` (see A)

and now the auth resolver gone for good.

This does NOT happen for all other resolvers (eg Mutation.createTodo.req.vtl will not get deleted by the same behavior)

Might be similiar to #6878 but is definitely still existing for auth resolvers

### Expected behavior

I expect all custom resolvers to always stay in `<root>/amplify/backend/api/<APINAME>/resolvers` and not get removed in any circumstances.

### Reproduction steps

this will reproduce part B of the described bug

1. new project
2. amplify init
2. amplify add auth (Cognito Auth)
3. amplify add api (Cognito Auth)
4. Edit schema to what is provided in this issue
5. amplify mock api
6. open `<root>/amplify/backend/api/<APINAME>/resolvers/Mutation.createTodo.auth.1.req.vtl`  in an editor an add `#set( $foo = "bar" ) at line 1
7. save file, mock server will register the change 
8. stop mock server with ctrl+c
9. start mock server again: amplify mock api
10. `<root>/amplify/backend/api/<APINAME>/resolvers/Mutation.createTodo.auth.1.req.vtl` is gone

### GraphQL schema(s)

<details>

```graphql

type Todo
  @model
  @auth(
    rules: [
      {
        allow: groups
        groups: ["Admin"]
        operations: [create, update, delete, read]
      }
    ]
  ) {
  id: ID!
  name: String!
  description: String
}



```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

this is a very annoying issue and was hard to even get my finger on as all other resolvers don't follow this behavior.
if possible, please tell me a workaround or fix as soon as possible as it really halts development if I have to always copy around the auth resolvers from backup folders.

**Comment by josefaidt** [comment]
Hey @n0rb :wave: thanks for raising this and including detailed reproduction steps! I was able to successfully reproduce using the provided steps. Marking as a bug 🙂

**Comment by n0rb** [comment]
any update about this? this destroys information after all so it should get some priority at least
