### ISSUE TITLE
`hasMany` field causes `amplify push` failures -- apparently due to`@auth` transformer interaction with GSI

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#9573]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.2.0

### Amplify CLI Version

7.6.11

### What operating system are you using?

macOS 12.0.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

I am working on migrating my app to the v2 amplify GraphQL transformer. My setup was working fine with the v1 transformer.
When the `@hasMany` field described in this bug is commented out, the project "compiles" and pushes correctly.

One of my types (`UserFollow`) has a field with both a `@primaryKey` and `@index` defined on it.
Another type (`User`) has a `hasMany` field referencing the aforementioned field of `UserFollow`.
See attached partial schema.
(I am also seeing the exact same bug with 2 other types manifesting the above relationship.)

---

When running
amplify api push --yes or amplify push --yes, I get the following error:
```
TypeError: Cannot read properties of undefined (reading 'keySchema')
    at getRelationalPrimaryMap (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/lib/utils/schema.js:72:21)
    at AuthTransformer.protectRelationalResolver (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts:526:59)
    at AuthTransformer.generateResolvers (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts:348:16)
    at GraphQLTransform.transform (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:252:21)
    at _buildProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:562:37)
    at buildAPIProject (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:519:24)
    at transformGraphQLSchema (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/graphql-transformer/transform-graphql-schema.ts:392:29)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:166:5)
    at async Promise.all (index 0)
    at providersPush (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:139:3)
    at AmplifyToolkit.pushResources [as _pushResources] (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/push-resources.ts:96:9)
    at Object.executeAmplifyCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-api/src/index.ts:223:5)
    at executePluginModuleCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/opt/homebrew/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

Note that the offending line is 1 line preceding the line fixed in https://github.com/aws-amplify/amplify-cli/pull/9459/

### Expected behavior

push should succeed...

### Reproduction steps

Run `amplify api push --yes` or `amplify push --yes`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type User @model(subscriptions: {level: off})
@searchable
@auth(rules: [
  {allow: owner, ownerField: "sub", identityClaim: "sub", operations: [read, update]},
  {allow: public, operations: [read]},
  {allow: private, provider: iam, operations: [create, read, update, delete]}
]) {
  sub: String! @primaryKey

  # ...

  # this one causes a failure when not commented out
  following: [UserFollow]! @hasMany(indexName: "byFollower", fields: ["sub"])

  # this one works fine
  followers: [UserFollow]! @hasMany(indexName: "byFollowed", fields: ["sub"])
}


type UserFollow
  @model(subscriptions: {level: off})
  @searchable
  @auth(rules: [
    {allow: owner, ownerField: "ownerSub", identityClaim: "sub", operations: [create, read, delete]},
    {allow: public, operations: [read]},
    {allow: private, provider: iam, operations: [create, read, update, delete]}
  ]) {
  ownerSub: String!
    @primaryKey(sortKeyFields: ["followed_sub"])
    @index(name: "byFollower", sortKeyFields: ["createdAt"])

  followed_sub: String! @index(name: "byFollowed", sortKeyFields: ["createdAt"])

  # ...
  createdAt: AWSDateTime!
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

The offending line is located 1 line above the line that contained the fix to my previously reported bug concerning a `hasOne` connection. See the (already merged) fix PR: https://github.com/aws-amplify/amplify-cli/pull/9459

**Comment by lazpavel** [comment]
Hi @ataibarkai, thank you for reporting this issue, to help narrow the reproduction steps can you please email us the contents of `amplify/api/<api_name>/cli-inputs.json` at amplify-cli@amazon.com.

You also mentioned you're trying to migrate to V2, can you attach the V1 schema as well, what were the steps you made? Was just running `amplify migrate api` or there were required any manual changes to the schema?

Can you still reproduce this issue if you start a new project configured with the V2 transformer to begin with?

**Comment by ataibarkai** [comment]
Hi @lazpavel , thanks for your attention on this.

If you'd like I can email the contents of the `cli-inputs.json` file as well, but I don't see anything sensitive there(*) so I don't mind attaching it here as well:
[*except _perhaps_(?) the `cognitoUserPoolId`, so I am redacting it]:
```
{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "AppSync",
    "defaultAuthType": {
      "mode": "AMAZON_COGNITO_USER_POOLS",
      "cognitoUserPoolId": "authredactedauth"
    },
    "additionalAuthTypes": [
      {
        "mode": "API_KEY",
        "expirationTime": 365,
        "keyDescription": ""
      },
      {
        "mode": "AWS_IAM"
      }
    ],
    "conflictResolution": {},
    "apiName": "voke02",
    "gqlSchemaPath": "/Users/ataibarkai/LocalGit/tawkit/backend/amplify/backend/api/voke02/schema.graphql"
  }
}
```

> You also mentioned you're trying to migrate to V2, can you attach the V1 schema as well, what were the steps you made? Was just running amplify migrate api or there were required any manual changes to the schema?

I had to make a bunch of manual changes to the schema, but the end result is not drastically different from the original and generally makes sense.
I've been making the changes in parts, where at every stage the entire schema compiles except for a single offending unit.
This bug describes the last offending unit in my migration.

> Can you still reproduce this issue if you start a new project configured with the V2 transformer to begin with?

I haven't tried a new project, but I have tried a brand new environment, and the error persists.

Did you try and fail to reproduce this error?

From what I can tell, this error seems very robust; both from glaring at the code in `@aws-amplify/graphql-auth-transformer/src/graphql-auth-transformer.ts:526:59`, and from the fact that I see this error across multiple types with the same conditions (`@hasMany` referencing an `@index` defined on a field that also has a `@primaryIndex` with a `sortKeyFields`).

**Comment by ataibarkai** [comment]
I also just edited the gql schema to reflect the following field on the `User` type:
`followers: [UserFollow]! @hasMany(indexName: "byFollowed", fields: ["sub"])`.

This field works just fine. Unlike the offending field:
`following: [UserFollow]! @hasMany(indexName: "byFollower", fields: ["sub"])`

(note the difference: `indexName` "byFollowed" in the former, and "byFollower" in the latter).

the working `byFollowed` index is defined on a field with no other directives, whereas the non-working "byFollower" index is defined on a field which also has a `@primaryKey(sortKeyFields: ["followed_sub"])` directive on it.

**Comment by ataibarkai** [comment]
>Thank you for the update, I wasn't able to reproduce the exact error yet, I ran however into a different one, so I wanted to make sure I am reproducing the same configuration

@lazpavel interesting. Another potentially relevant detail I noticed in my schema: the `sortKeyFields` references another field which has its own index defined on it. I vaguely remember this may have something to do with GSI dynamics?

**Comment by ataibarkai** [comment]
@lazpavel any updates on this?

**Comment by lazpavel** [comment]
> Thank you for the update, I wasn't able to reproduce the exact error yet, I ran however into a different one, so I wanted to make sure I am reproducing the same configuration

with the latest amplify I no longer experience the previous error, the push succeeds

**Comment by ataibarkai** [comment]
> with the latest amplify I no longer experience the previous error, the push succeeds

Hi @lazpavel , thanks for that second update.
I am still seeing the same error even with the latest amplify, so I dug deeper.

I confirmed that on a fresh amplify project the schema I provided works properly. Looking for differences between my main project and the fresh project, I noticed the `secondaryKeyAsGSI` flag which is set to `true` on a fresh project but was absent from my main project.

This reminded me of another issue from a year ago, which I had also commented on but forgot about since:
https://github.com/aws-amplify/amplify-cli/issues/6650
This issue is about migrating a LSI-based amplify project to a GSI-based amplify project.

I confirmed that the relevant index described here ("byFollower") is in fact backed by a LSI rather than a GSI in my tables. I strongly suspect this is the source of the issue I am encountering here.

So going back to https://github.com/aws-amplify/amplify-cli/issues/6650:
Is there a supported way to migrate a LSI-backed table to a GSI-backed table without losing all the data?

**Comment by ataibarkai** [comment]
@lazpavel or alternatively -- can the `auth` transformer be fixed to support LSI indices?
You should be able to reproduce the issue I described by creating a new project and setting the `secondaryKeyAsGSI` to `false` prior to the initial push.

**Comment by ataibarkai** [comment]
High @lazpavel, any updates?
Seems there is a PR out with a fix but it hasn't been merged yet.

I appreciate your effort on this, hoping to finally merge our v2 transformer migration.

**Comment by 8maxxam8** [comment]
@lazpavel @sundersc 

Hi guys,
I am currently experiencing a similar issue with @belongsTo in connection with @auth and more than one sortKey inside of the parent element. 

The following error comes up when I try to amplify push the schema:
🛑 Invalid @belongsTo on Comments:todo. Provided fields do not match the size of primary key(s) for Todos

Below schema should reproduce the error:

`type Todos @model @auth(rules: [{ allow: private }] {
  id: ID!
  createdAt: String
  number: Int
  title: String
  description: String
  comments: Comments @hasMany(indexName: "byComments", fields: ["id"])
  baseType: String 
  @index(name: "byNumber" queryField: "todosByNumber" sortKeyFields: ["number"]) 
  @index(name: "byTitle" queryField: "todosByTitle" sortKeyFields: ["title"]) 
  @index(name: "byDescription", queryField: "todosByDescription" sortKeyFields: ["description"])
}

type Comments @model @auth(rules: [{allow: private}] {
  id: ID!
  createdAt: String
  firstName: String
  lastName: String
  todosID: ID @index(name: "byComments")
  todo: Todos @belongsTo(fields: ["todosID"])
}`


Actually it is the same issue which was mentioned here and has already been closed: https://github.com/aws-amplify/amplify-cli/issues/9401

Is this still a bug? Or does anyone have a solution on how to set it up correctly? Looking forward to your help!

**Comment by sundersc** [comment]
Hey @8maxxam8 - I couldn't reproduce the issue with the provided schema. Could you check the schema?

There were few issues in the above schema. (1) `)` missing on the auth rules. (2) field with `hasMany` relation should be a list. Below is the schema I used to reproduce.

```graphql
type Todos @model @auth(rules: [{ allow: private }]) {
  id: ID!
  createdAt: String
  number: Int
  title: String
  description: String
  comments: [Comments] @hasMany(indexName: "byComments", fields: ["id"])
  baseType: String 
  @index(name: "byNumber" queryField: "todosByNumber" sortKeyFields: ["number"]) 
  @index(name: "byTitle" queryField: "todosByTitle" sortKeyFields: ["title"]) 
  @index(name: "byDescription", queryField: "todosByDescription" sortKeyFields: ["description"])
}

type Comments @model @auth(rules: [{allow: private}]) {
  id: ID!
  createdAt: String
  firstName: String
  lastName: String
  todosID: ID @index(name: "byComments")
  todo: Todos @belongsTo(fields: ["todosID"])
}
```

**Comment by 8maxxam8** [comment]
Hey @sundersc , thanks for the reply! My bad, I forgot the `)` and the `[ ]`! I just checked the schema again and forgot an important part. I think it has something to do with having two @belongsTo inside of the Comments Table...

The following schema should now reproduce the error:

```
type Todos @model @auth(rules: [{ allow: public }]) {
  id: ID!
  createdAt: String
  number: Int
  title: String
  description: String
  comments: [Comments] @hasMany(indexName: "byComments", fields: ["id"])
  baseType: String
    @index(
      name: "byNumber"
      queryField: "todosByNumber"
      sortKeyFields: ["number"]
    )
    @index(
      name: "byTitle"
      queryField: "todosByTitle"
      sortKeyFields: ["title"]
    )
    @index(
      name: "byDescription"
      queryField: "todosByDescription"
      sortKeyFields: ["description"]
    )
}

type Comments @model @auth(rules: [{ allow: public }]) {
  id: ID!
  todosID: ID! @index(name: "byComments")
  todo: Todos @belongsTo(fields: ["todosID"])
  createdAt: String
  firstName: String
  lastName: String
  messageID: ID @index(name: "commentsByMessages")
  message: Messages @belongsTo(fields: "messageID")
}

type Messages @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String
  content: String
  comments: [Comments] @hasMany(indexName: "byComments", fields: ["id"])
}
```

**Comment by 8maxxam8** [comment]
@sundersc Do you have any update on this? I am really stuck at this one!
