### ISSUE TITLE
Amplify API does not incorporate permission boundaries of user in CF stacks

### ISSUE THREAD

**Issue by k1410003** [aws-amplify/amplify-cli#9583]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

When I add API via Amplify, Amplify did not set up IAM permission boundaries on IAM roll. There was no problem when I added auth.
Is  this a bug? Or, did I make wrong how to set up? I refered to here. https://docs.amplify.aws/cli/project/permissions-boundary/.

I need to set up IAM permission boundaries on all of the IAM roles I made at my project to prevent privilege escalation.

I can't write English well. I used a translator on Google. Sorry for my poor English.

**Which Category is your question related to?**
api? or awscloudformation? or etc...

**Amplify CLI Version** 
```
❯ amplify -v
7.6.11
```

**What AWS Services are you utilizing?**
AWS AppSync GraphQL

**Provide additional details e.g. code snippets**

**Comment by edwardfoyle** [comment]
Hi @k1410003 I was able to repro this when using @function or @searchable in the GraphQL schema. Marking as bug, but just want to confirm that you aren't seeing this behavior in some other configuration as well?

**Comment by k1410003** [comment]
@edwardfoyle Thank you.
I am not sure if the problem will be caused in another configuration because I only tried API or Auth.

Then, the GraphQL schema which the problem causes is under the below.
```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Note @model {
  id: ID!
  name: String!
  description: String
}
```
