### ISSUE TITLE
Resolver is missing slot preDataLoad

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9584]
**Which Category is your question related to?**
GraphQL

**Amplify CLI Version** 
7.6.11

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
I'm trying to intercept the record creation process and add a custom logic that would verify if this record can be created by checking the status of corresponding record in another table.
I added **preDataLoad** slot to **/resolvers** folder naming it following the recommended naming convention:
`Mutation.createXXX.preDataLoad.1.req.vtl`

-- but I get the following error  when I try to push or compile locally:
```
Resolver is missing slot preDataLoad
```

I'm not sure why, but slots like: **preAuth**, **preDataLoad**, **postDataLoad**, **finish** are not generated at all...

**Comment by edwardfoyle** [comment]
for mutation resolvers, you need to use the pre/postUpdate slot instead of preDataLoad. pre/postDataLoad only exist for query resolvers.

**Comment by jk171505** [comment]
Thanks. Is there a place in documentation where this is explained?

**Comment by jk171505** [comment]
@edwardfoyle  can you point me to some documentation that explains the usage of pre/postUpdate slots? Not a word about its existence in amplify documentation:
https://docs.amplify.aws/cli/graphql/custom-business-logic/#create-a-custom-query-or-mutation
https://docs.amplify.aws/cli/migration/transformer-migration/#what-are-the-breaking-changes-and-how-do-i-migrate

**Comment by kylekirkby** [comment]
@josefaidt @marcvberg @renebrandel 

Can we please get some documentation on custom VTL resolvers?
