### ISSUE TITLE
amplify env pull vs checkout and --restore

### ISSUE THREAD

**Issue by brianhilst** [aws-amplify/amplify-cli#960]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify env checkout and pull
** What AWS Services are you utilizing? **
Amplify CLI and Console
** Provide additional details e.g. code snippets **
Would you please provide some additional documentation on the differences between the amplify env checkout and env pull commands as well as when to use and what the --restore flag does?  We are unsure of which to use and when.

**Comment by yuth** [comment]
`amplify env checkout <envname>` is analogues `git checkout <branchname>`.  This changes the current env to `envname`. When you do an amplify push after this command, you will be pushing to `envname`. 

`amplify env pull` is analogues to `git pull`. Your `current-cloud-backend` will be synced with what is deployed in the env. This command is useful when some changes were pushed from a different workspace, and you want to get those changes locally to your workspace and see the diff between whats in the cloud and what you have in your workspace

The `--restore` flag will discard any changes in your `backend`. Your `backend` will be in sync with the `envname` in case of `checkout` and with the current env in case of `pull`. This is similar to `get reset --hard HEAD`
