### ISSUE TITLE
Extending @searchable resolver slots file naming inconsistency

### ISSUE THREAD

**Issue by pmulka** [aws-amplify/amplify-cli#9612]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.2

### Amplify CLI Version

7.6.12

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made to the cloud.

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

Extending a @searchable query's slots, such as `Query.searchTodos.init.1.req.vtl` does not get picked up. After running `amplify api gqp-compile` produces a SearchableStack.json that does not include this in the pipeline: [SearchableStack-Query.searchTodos.txt](https://github.com/aws-amplify/amplify-cli/files/7943532/SearchableStack-Query.searchTodos.txt)
 
Instead, I found that using `Search.Todo.init.1.req.vtl` will be picked up and added to the pipeline: [SearchableStack-Search.Todo.txt](https://github.com/aws-amplify/amplify-cli/files/7943556/SearchableStack-Search.Todo.txt)
 
This is inconsistent with the the file naming following the GraphQL `{typeName}.{fieldName}`.

### Expected behavior

After setting up a project with a the GraphQL schema detailed below and running `amplify api gql-compile`, the following are automatically created in build/resolvers:

- Query.searchTodos.auth.1.req.vtl
- Query.searchTodos.postAuth.1.res.vtl
- Query.searchTodos.req.vtl
- Query.searchTodos.res.vtl

I would expect, then, to be able to use the slot extensions in the same way with Query.searchTodos.init.1.req.vtl, etc.

### Reproduction steps

1. amplify init
2. amplify add api
  - Include Cognito User Pool auth. 
3. Update the schema to the one below.
4. Add a custom resolver for Query.searchTodos.init.1.req.vtl
5. amplify api gql-compile
6. Inspect the SearchableStack in build/stacks and the init function will be missing.

### GraphQL schema(s)

<details>

```graphql
type Todo
  @model
  @searchable
  @auth(rules: [{allow: owner}])
{
  id: ID!
  name: String!
  description: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @pmulka :wave: thanks for raising this! I'm seeing the resolver is picked up on my end, as well as in the posted SearchableStack. Can you confirm whether you're seeing the init function populated in the searchTodos pipeline? 
![image](https://user-images.githubusercontent.com/5033303/152887417-69734ff0-20b6-48d1-9d4f-f3984dad6811.png)

**Comment by pmulka** [comment]
Hi @josefaidt. Using Amplify 7.6.15, the init slot files starting with the name Query.search are now added to my pipelines as I would expect. Thank you! 👍

**Comment by josefaidt** [comment]
Awesome, glad to hear it @pmulka 🙌  

Closing issue 🙂
