### ISSUE TITLE
Authorization rules documentation request

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-cli#9613]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
api / auth

Hello,

I'm a little confused by the existing authorization rules documentation (https://docs.amplify.aws/cli/graphql/authorization-rules/).

The existing documentation is oriented around recommended use-cases for common access patterns, which is very helpful. But I think it would be significantly augmented by a simple table which documents the functionality of the `auth` directive in the simplest way possible:

**What does each strategy _do_?, what arguments does it support? What are the default values these arguments take when left unspecified?**

To motivate this request, consider the simplest possible use-case, of wanting to make an object (or a field) public. Here's the current documentation on the subject:

--- 

> **Public data access**
> To grant everyone access, use the public authorization strategy. Behind the scenes, the API will be protected with an API Key.
```
type Todo @model @auth(rules: [{ allow: public }]) {
  content: String
}
```
---
 
Now, I found that this provides access to the object for access with the API Key -- but _denies_ access to a signed in user.

If you squint at the documentation above, you can kind of figure out that the `public` strategy populates `apiKey` as the default `provider` argument when one is not already specified, which means that all other auth mechanisms will fail. But it is far from clear from the documentation alone (and to be honest, a part of me is still wondering if I simply encountered a bug).

The `Signed-in user data access` headline provides the solution:
To support public access by any signed in user, add `{allow: private}` as a rule.
This works, and by the fact that it works I can infer that the `private` strategy populates `userPools ` as the default `provider` argument when one is not already specified, which covers this use-case. But this is not stated anywhere explicitly.

Could I have used `{allow: public, provider: userPools}` instead of `{allow: private}`?

And anyways, what's the difference between
`{allow: public, provider: userPools}` and
`{allow: private, provider: userPools}` ?

etc...

**Comment by johnpc** [comment]
No, you could not have used `{allow: public, provider: userPools}` because it is an invalid combination. You can see the table in the docs under Authorization Strategies (https://docs.amplify.aws/cli/graphql/authorization-rules/#authorization-strategies) does not contain a row for `public` and `userPools`.  `private` requires that user is signed in.

**Comment by josefaidt** [comment]
Closing per the authorization strategy table in the documentation
