### ISSUE TITLE
In 'split schema' graphql, schemas without @model do not merge queries or mutations

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-cli#962]
If I split my schema into multiple files and I have a schema file that does not have a type annotated with @model, yet includes Query or Mutation types, the Query and Mutation types are not merged into the build schema file. 

CLI version is 1.1.6
Windows 10 / Powershell

To reproduce Create two schema files:

schema1.graphql contains:

type ModelType @model { id: ID!, name: String! }

schema2.graphql contains:

type NoModel {id: ID!, name: String! }
type Query { getNoModel(id: ID!):NoModel }
type Mutation { putNoModel(id: ID!, name: String!):NoModel }

Now run 'amplify api gql-compile' (or 'amplify push')
the resulting schema.graphql file in build/ will not contain the "getNoModel query or putNoModel mutation"

To workaround this I've combined those schema items with another part of my schema where the file does have @model

Thank you.

**Comment by yuth** [comment]
We do support splitting the schema into multiple files. Its documented in[API Category Project structure](https://aws-amplify.github.io/docs/cli/graphql#api-category-project-structure) section.

You will need to create a directory named `<project-root>/amplify/backend/api/<api-name>/schema/` and put the split schema inside it.

**Comment by ryanhollander** [comment]
Hello: I think you may misunderstand. I am using a split schema, that works fine. What I'm saying is if one of them does not have at least one type defined with @model then the Query and Mutation types that may be included in that file are not merged by amplify api gql-compile into the combined schema in build/ and therefore not included in AppSync.

**Comment by ryanhollander** [comment]
I was going to open a new issue for this but I think this issue is directly related. Let me know if you think a new issue is warranted and I'll happily open another ticket. Here is the new issue I found: in a split schema, if the second or subsequent merged schema has a @model with queries and mutations null, type Query and type Mutation are not merged into the compiled schema.

So in one case the second file has no @model and in this case there is an @model but the annotation has a directive (queries: null, mutations: null). In both cases there are at least one of type "Mutation" and "Query" defined with functions listed and in both cases these entries are not merged into the final compiled graphql.schema.

**Comment by mikeparisstuff** [comment]
@ryanhollander Thanks for raising the issue. I am having trouble reproducing the issue. Can you advise.

I have this schema as you mentioned above:

```graphql
# schema/schema1.graphql
type ModelType @model { 
  id: ID!, 
  name: String! 
}

# schema/schema2.graphql
type NoModel { id: ID!, name: String! }
type Query { getNoModel(id: ID!): NoModel }
type Mutation { putNoModel(id: ID!, name: String!): NoModel }
```

After running `amplify api gql-compile`, I see:

```graphql
type ModelType {
  id: ID!
  name: String!
}

type NoModel {
  id: ID!
  name: String!
}

type Query {
  # The NoModel query
  getNoModel(id: ID!): NoModel

  # The generated queries
  getModelType(id: ID!): ModelType
  listModelTypes(filter: ModelModelTypeFilterInput, limit: Int, nextToken: String): ModelModelTypeConnection
}

type Mutation {
  # The NoModel mutation
  putNoModel(id: ID!, name: String!): NoModel

  # auto-generated mutations
  createModelType(input: CreateModelTypeInput!): ModelType
  updateModelType(input: UpdateModelTypeInput!): ModelType
  deleteModelType(input: DeleteModelTypeInput!): ModelType
}

# ... the rest
```

I also tried changing `schema/schema1.graphql` to 

```graphql
type ModelType @model(queries: null, mutations: null) { id: ID!, name: String! }
```

And I still see

```graphql
type Query {
  getNoModel(id: ID!): NoModel
}

type Mutation {
  putNoModel(id: ID!, name: String!): NoModel
}
```

Am I doing something wrong to reproduce the issue?

**Comment by ryanhollander** [comment]
@mikeparisstuff  Thanks for taking the time to review this.

>>Am I doing something wrong to reproduce the issue?

maybe, but it's probably my fault for not being specific enough. Let me review my findings and I'll respond here in a day or so with a better example.

**Comment by ryanhollander** [comment]
Ok, I started a clean API project and did some testing. It seems like if the first schema file has a type Query defined it won't merge anything defined in type Query in subsequent files (I only tested 2 files). Likewise for Mutations. However, if the second file has @model the generated model queries and mutations are merged in. @connection doesn't seem to impact this. Here is an example you can start with and see the merge not working. I'm realizing now I've been seeing the same bug over and over in different contexts and misidentified the root cause.

Please try this (the file naming is influencing load order, if you reverse the file names you get the opposite Query/Mutation types.

file 1 is named s1.graphql and contains:

type MyType1  {
	id: ID!
	title: String!
	content: String!
	price: Int
	rating: Float
	xx: xx
}
type xx {
	id: ID!
	mytype: MyType1
}
type Query {
	getxx(id: ID!):xx
}
type Mutation {
	putxx(id: ID!):xx
}

file 2 is named s2.graphql and contains:

type MyType2 {
	id: ID!
	title: String!
	content: String!
	price: Int
	rating: Float
}
type Query {
	getMine(id: ID!):MyType2
}
type Mutation {
	putMine(id: ID!):MyType2
}

running amplify api gql-compile (version 1.1.7 now) gives me schema.graphql:

type MyType1 {
  id: ID!
  title: String!
  content: String!
  price: Int
  rating: Float
  xx: xx
}

type xx {
  id: ID!
  mytype: MyType1
}

type Query {
  getxx(id: ID!): xx
}

type Mutation {
  putxx(id: ID!): xx
}

type MyType2 {
  id: ID!
  title: String!
  content: String!
  price: Int
  rating: Float
}

Hope this helps! Thanks.

**Comment by mikeparisstuff** [comment]
@ryanhollander Gotcha. Can you try using a type extension in the second schema? E.G.

```graphql
# schema1.graphql
type Query {
  queryField1: String
}
```

then

```graphql
extend type Query {
  queryField2: String
}
```

If this does not work, I will look into what we can do to fix this.

**Comment by ryanhollander** [comment]
@mikeparisstuff well that is handy, adding extend to the second file works. Thanks! Maybe instead of a bug this can be turned into a documentation request? A note somewhere in the Amplify docs would be helpful for future developers looking to split schemas. :-)

**Comment by babus** [comment]
@yuth The link is broken. Couldn't find anything easily in the doc too.

**Comment by andrew-aernos** [comment]
I'm running into something weird similar related to multiple extensions across different split schema. For example, both the following `Post `and `Comment ` are **not** marked `@model`

```
// in Post.graphql
type Query {
  echo(msg: String): String @function(name: "myfunc-${env}"
}

type Mutation {
  createPost(input: CreatePostInput!): Post @function(name:"postFunc-${env}")
}

// in Comment.graphql
extend type Mutation {
  createComment(comment: String): Comment @function(name:"commentFunc-${env}")
}
```

When I use `extend ` on `Post`'s Mutation fields: 
- gql-compile generates `build/schema.graphql` includes the Mutation fields
- gql-compile **doesn't** generate the resolvers in the `build/resolvers` '
- gql-compile **doesn't** generate appsync::resolver cfn resources in build/stacks/FunctionDirectiveStack.json

When I don't use `extend` on `Post`'s Mutation fields
- gql-compile generates `build/schema.graphql` `doesn't` include the Mutation fields
- gql-compile does generate the resolvers in the `build/resolvers` '
- gql-compile does generate appsync::resolver cfn resources in build/stacks/FunctionDirectiveStack.json

**Comment by Woodz** [comment]
> API Category Project structure

For reference, the URL has now moved to https://docs.amplify.aws/cli/graphql-transformer/overview#api-category-project-structure
