### ISSUE TITLE
What's the recommended way of creating pipeline functions after migration to V2 graphQL transformer?

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9622]
**Which Category is your question related to?**
api

**Amplify CLI Version** 

7.6.8

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
I tried to replace resolver for create mutation but I get the error saying:
```
CREATE_FAILED               CreateXXXResolver                                                   AWS::AppSync::Resolver     Wed Jan 26 2022 21:19:45 GMT+0100 (Central European Standard Time) Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 94399f42-735f-4071-a2c6-7be4254ed5d0; Proxy: null)
```

So it looks like I'm not able to overwrite the existing resolver in order to add some custom functions and different data sources for them. It was possible in the previous version. How this can be accomplished now?

**Comment by lazpavel** [comment]
Hi @jk171505, here is the documentation for [extending amplify generated resolvers](https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers).

Let us know if you still have issues.

**Comment by jk171505** [comment]
@lazpavel thanks, although I'm looking for a way to change the data source for one of the resolvers generated in new slots as it seems like all of them have data source set to NONE_DS.
I basically need to query different table in order to verify if the mutation that I want to modify can proceed or should throw an error.

**Comment by lazpavel** [comment]
Check the comment here: https://github.com/aws-amplify/amplify-cli/issues/9623#issuecomment-1023528618

**Comment by jk171505** [comment]
Thanks!
