### ISSUE TITLE
Change data source for resolver that extends Amplify-generated one

### ISSUE THREAD

**Issue by jk171505** [aws-amplify/amplify-cli#9623]
**Which Category is your question related to?**
api

**Amplify CLI Version** 
7.6.8

**Provide additional details e.g. code snippets**
Is this possible to change data source for new resolver that extends Amplify-generated one in new version of graphQL transformer (V2)?

**Comment by lazpavel** [comment]
Hi @jk171505, you should be able to achieve what you need by using CDK to define custom VTL resolvers as described here: https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver.

Please let us know if you still have any issues

**Comment by jk171505** [comment]
@lazpavel where do I define the exact slot for which I want to change the data source?

**Comment by jk171505** [comment]
Can I accomplish the same by defining the data source for specific slot in `CustomResources.json`?

**Comment by lazpavel** [comment]
I see, the link above will allow you to create and configure a custom resolver and not to update a different data source for a slot on an extended resolver.

For that you could use the documented way to [extend a resolver](https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers) (e.g: `Mutation.createModelB.postAuth.2.req.vtl`) and then use `amplify override api` and update the datastore for the specific appsyncFunction as below: 

```
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate) { 
resources.models["**ModelB**"].appsyncFunctions["Mutationcreate**ModelB**postAuth1FunctionMutationcreate**ModelB**postAuth1Function.AppSyncFunction"].dataSourceName = "**ModelATable**";
}
```

**Comment by jk171505** [comment]
Thanks! That's exactly what I needed.

**Comment by Dennis-Dekker** [comment]
@lazpavel  Is there a difference between the replacement of \*\*ModelB** and \*\*ModelATable** in your example? I'm confused by this, so if model A is named "Item" should \*\*ModelATable** be "Item" or "ItemTable"?

**Comment by jk171505** [comment]
@Dennis-Dekker you are basically changing the dataSource for ModelB to ModelA. You should also add the suffix 'Table', so it should be:
```
resources.models["Item"].appsyncFunctions["MutationcreateItempostAuth1FunctionMutationcreateItempostAuth1Function.AppSyncFunction"].dataSourceName = "SomeOtherItemTable";

**Comment by alexboulay** [comment]
@jk171505 Do you know if I can reference a Lambda DataSource in this case? If yes, that would be awesome.

**Comment by ggorge-etiqa** [comment]
This is my `override.ts`:
```
import { AmplifyApiGraphQlResourceStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
    const model = resources.models["User"];
    model.appsyncFunctions["MutationcreateUserpreUpdate0Function.AppSyncFunction"].dataSourceName = "UniqueUsernameCheckLambdaDataSource";
}
```
On `amplify push` I' m getting this error:

`Cannot set properties of undefined (setting 'dataSourceName')`

Amplify version is `12.3.0`.

Is what explained in this issue still valid?

**Comment by BradVidler** [comment]
@ggorge-etiqa Did you ever solve this? I'm facing the same issue.

**Comment by rob-lucky** [comment]
> This is my `override.ts`:
> 
> ```
> import { AmplifyApiGraphQlResourceStackTemplate, AmplifyProjectInfo } from '@aws-amplify/cli-extensibility-helper';
> 
> export function override(resources: AmplifyApiGraphQlResourceStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
>     const model = resources.models["User"];
>     model.appsyncFunctions["MutationcreateUserpreUpdate0Function.AppSyncFunction"].dataSourceName = "UniqueUsernameCheckLambdaDataSource";
> }
> ```
> 
> On `amplify push` I' m getting this error:
> 
> `Cannot set properties of undefined (setting 'dataSourceName')`
> 
> Amplify version is `12.3.0`.
> 
> Is what explained in this issue still valid?

Yes, this is still valid solution with amplify cli v 12.11.1

For the function name you can also take a look into your build folder, where you can also find the generated resolvers. Here you can also find the CloudFormation stacks. Find the stack for your origin model. Find your function. The function should have this syntax: `FunctionNameAppSyncFunctionRandomString`.

You need the FunctionName part und use it in override.ts:
`model.appsyncFunctions["FunctionName.AppSyncFunction"].dataSourceName = "SomeOtherItemTable";`
