### ISSUE TITLE
Can't access custom CDK resource outputs from Lambda function

### ISSUE THREAD

**Issue by nathanagez** [aws-amplify/amplify-cli#9630]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

7.6.13

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

custom, function

### Amplify Commands

push

### Describe the bug

We don't have the ability to access output variables from custom CDK code in Lambda function.

<img width="709" alt="Screenshot 2022-01-27 at 23 25 46" src="https://user-images.githubusercontent.com/7148684/151456966-d21289a8-4ac6-4d89-bd8f-242d9e0aa06f.png">

### Expected behavior

We should be able to access output variables from custom resources using the `dependsOn` statement in the `backend-config.json` file.

### Reproduction steps

Add custom resource:
`amplify add custom` select CDK and name it "video"

Add an CfnOutput value for this stack:

```ts
new cdk.CfnOutput(this, "outputKey", {
  value: "TEST_FROM_CDK"
});
```

Add Lambda function:
`amplify add function`

Update `backend-config.json` `depnedsOn` entry:
```json
"yourLambda": {
      "build": true,
      "providerPlugin": "awscloudformation",
      "service": "Lambda",
      "dependsOn": [
        {
          "category": "custom",
          "resourceName": "video",
          "attributes": [
            "outputKey"
          ]
        }
      ]
    }
```

Update the Lambda CloudFormation stack:
```json
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "{\"createdOn\":\"Mac\",\"createdBy\":\"Amplify\",\"createdWith\":\"7.6.3\",\"stackType\":\"function-Lambda\",\"metadata\":{}}",
  "Parameters": {
    "CloudWatchRule": {
      "Type": "String",
      "Default": "NONE",
      "Description": " Schedule Expression"
    },
    "deploymentBucketName": {
      "Type": "String"
    },
    "env": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
    "customvideooutputKey": {
      "Type": "String"
    }
  }
```

Populate parameter values:
`amplify env checkout <your-env>`

Deploy:
`amplify push`

<img width="709" alt="Screenshot 2022-01-27 at 23 25 46" src="https://user-images.githubusercontent.com/7148684/151457656-33386641-b637-4f1b-a3ec-55099a457d3b.png">

### Note:
If someone can give me explanations on how the outputs are shared between the stacks and hints on how to implement this feature I might be able to do it!

**Comment by josefaidt** [comment]
Hey @nathanagez :wave: thanks for raising this! Unfortunately this is not currently supported, however I've updated the title and labels on https://github.com/aws-amplify/amplify-cli/issues/9087 to better reflect the request. I'll mark this as a duplicate feature request, and for further updates please subscribe to #9087 🙂
