### ISSUE TITLE
OpenSearch & conflict resolution/versions break GraphQL search queries

### ISSUE THREAD

**Issue by alexhouse** [aws-amplify/amplify-cli#9632]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.1

### Amplify CLI Version

7.6.13

### What operating system are you using?

OSX

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, function, api

### Amplify Commands

Not applicable

### Describe the bug

OpenSearch transforms don't appear to work with `_version` on fetching. Although the `OpenSearchStreamingLambd` lambda function strips `_version` and `_ttl` from the payload, setting the `version` and `version_type` on the created OS record, any `searchModel` queries don't appear to translate them back causing search responses to return an error for every record to the tune of: `Cannot return null for non-nullable type: 'Int' within parent 'Model' (/searchModels/items[0]/_version)`

### Expected behavior

`_version` (and `_ttl`) are restored to their correct values when GraphQL search queries return results

### Reproduction steps

1. Create a new `@searchable` model
2. Version it
3. Enable conflict resolution
4. `amplify push`
5. Create an entity
6. Search for entity
7. Witness failures in response

### GraphQL schema(s)

<details>

```graphql
type SearchableModel @model @searchable @auth(rules: [{allow: public, provider: apiKey}]) {
  id: ID!
  value: String!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

My knowledge of the resolvers is nowhere near good enough, but I imagine this should be solvable with a tweak to the search response resolvers to extract document version data (if `version_type` is external) into the model(s) to be returned?

**Comment by sundersc** [comment]
@alexhouse - Could you confirm the transformer version being used? `amplify status` prints this info.

**Comment by alexhouse** [comment]
@sundersc of course, using version 2. OpenSearch 1.1
