### ISSUE TITLE
Is there any way to configure the `publish` command?

### ISSUE THREAD

**Issue by fernandesGabriel** [aws-amplify/amplify-cli#9634]
**Which Category is your question related to?**
Publish

**Provide additional details e.g. code snippets**
I would like to customize the `publish` command while deploying my application manually, as it is possible to configure the build process if I use the CI version of it. The issue that I face currently in using the CI is that I can't give full read access of my organization to the desired AWS account.

**Comment by johnpc** [comment]
I don't think this is something we support, although you might look into command hooks.

I'm not sure I fully understand your access control issue though. 

Does that answer the question?

**Comment by fernandesGabriel** [comment]
@johnpc, I think what I need is exactly the command hooks, so I can use `pre-publish.js/sh` to add a custom logic as you can do on `preBuild` while using Amplify Hosting CI/CD pipelines. My issue regarding the current access control is due to the Amplify Console integration only having the possibility to integrate with my organization, and not with a specific project only. In this way, the owners of the AWS account could also list on Amplify Console all the connected repositories to my Github organization, which for our case can be some sort of information leak as we don't own the AWS accounts we deploy some of the Amplify apps. I don't really understand the reason the Github and Amplify Console integration requires such high privilege, as many other integrations we do have, during the setup process, we can select with the repository that the app would use.

**Comment by josefaidt** [comment]
Hey @fernandesGabriel :wave: apologies for the delay here! Are you referring to allowing access to specific GitHub repositories within the GitHub organization? In GitHub you can specify which repositories the app has access to, therefore the app from Amplify Hosting can _only_ access the specified repositories.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/5033303/178807801-70400443-10f0-41f1-a74a-f5da5822c4a4.png">

**Comment by fernandesGabriel** [comment]
Hi @josefaidt . Thank you for your reply. I haven't seen such access control before with an Amplify-Github app. Maybe it is something newer, or I just haven't gone through the whole process properly. I haven't had time to try the `pre-publish.js/sh` before, but also that seems to help with what I need. In any way, when I am back to this project, I will experiment with both.
