### ISSUE TITLE
Question Regarding 1-Many relationships with Named Connections using Amplify/Appsync

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-cli#964]
**Which Category is your question related to?**
Appsync API
**What AWS Services are you utilizing?**
Amplify, Appsync, Cognito, S3, SES
**Provide additional details e.g. code snippets**

Question regarding Using Amplify/Appsync/Graphql/React, and the `@connection` directive. I have a 1-Many relationship schema that is similar to 
```
type SingleResource @model {
  id: ID!
  name: String!
  multipleLinks: [Link] @connection(name: "MultipleLinksToSingleResource")
}

type Link @model{
  id: ID!
  name: String!
  singleResource: SingleResource @connection(name: "MultipleLinksToSingleResource")
}
```
The `Link`s will usually be created before the `SingleResource`, and upon creation of the `SingleResource`, I will do a Select-Multiple to connect the array of `Link`s to that `SingleResource`. 

I am using the `aws-appsync-react` **graphqlMutation** helper, using AppSync's auto-generated Schema that looks like this (does not create an input field for the links): 
```
input CreateSingleResourceInput {
  id: ID
  name: String!
  // no input field is made for the Links
}

input CreateLinkInput{
   id: ID
   name: String!
   linkSingleResourceId: ID //Works fine if I'm connecting from this direction
}
```

What is the best way to be able to perform a mutation similar to the following? : 
```
    this.props.createSingleResource({
      input: {
        name: this.state.name,
        singleResourceMultipleLinksIds: this.state.linkIDs,
      }
    });
```
I can imagine a few workarounds, like multiple mutations, or updates, to achieve my desired result, but I am curious if I'm just missing some obvious best practice using the existing tooling with Amplify and Appsync. Thanks!

**Comment by elorzafe** [comment]
@mikeparisstuff what do you think?

**Comment by mikeparisstuff** [comment]
You have a few options. The quickest and easiest way to do it without having to make any changes to your API will be to do as @elorzafe mentions and first create the SingleResource before updating each of the associated MultipleLinks.

If you would like to have a single mutation that allows you to do as you mentioned:

```
this.props.createSingleResource({
      input: {
        name: this.state.name,
        singleResourceMultipleLinksIds: this.state.linkIDs,
      }
    });
```

Then you can use Pipeline resolvers to implement the "createSingleResource" resolver. The resolver would have two functions:

1. Create the SingleResource
2. Use a BatchWrite operation to update all the associated MultipleLinks.

You can do this today using nested stacks but you will need to write the resolver logic yourself. We are looking at designs that would allow you to compose custom logic like this on top of auto-generated resolvers but there is not set release date for this feature. More details will be released in an RFC when they are ready.

**Comment by kaustavghosh06** [comment]
Please feel free to re-open this issue if you still think your problem is unresolved.
