### ISSUE TITLE
Custom Lambda authorizer for AppSync does not seem to work

### ISSUE THREAD

**Issue by dragosiordachioaia** [aws-amplify/amplify-cli#9645]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

7.6.13

### What operating system are you using?

MacOS 121.1 (Monterey) on M1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have not any manual changes to the cloud resources managed by Amplify

### Amplify Categories

auth, storage, function, api

### Amplify Commands

Not applicable

### Describe the bug

When I add a custom Lambda authorizer for a GraphQL API, any request made to the API gets an "Unauthorized" error despite the Lambda authorizer returning `{"isAuthorized": true}` for every request. 

**This is the CLI input for the GraphQL API:**
<details>

```json
{
  "version": 1,
  "serviceConfiguration": {
    "apiName": "inspectionstool",
    "serviceName": "AppSync",
    "gqlSchemaPath": "/Users/dragosreams/repos/inspections-tool/amplify/backend/api/inspectionstool/schema.graphql",
    "defaultAuthType": {
      "mode": "AWS_LAMBDA",
      "lambdaFunction": "graphQlLambdaAuthorizera8a08789",
      "ttlSeconds": "0"
    },
    "additionalAuthTypes": [
      {
        "mode": "AWS_IAM"
      }
    ],
    "conflictResolution": {
      "defaultResolutionStrategy": {
        "type": "OPTIMISTIC_CONCURRENCY"
      }
    }
  }
}
```
</details>

**This is the GraphQL schema for the model in question:**
```graphql
type Asset @model @auth(rules: [{ allow: custom }]) {
    id: ID!
    name: String
}
```

**And this is the code for my Lambda (this is only the index.js file, the CLI generated a few other things):**
```javascript
exports.handler = async (event) => {
  console.log(`event =`, JSON.stringify(event, null, 2));
  return { isAuthorized: true };
};
```

### Expected behavior

Given that the Lambda authorizer always returns `isAuthorized: true`, I would expect all queries, mutations and subscription initialisation requests to succeed. Instead, they all fail.

### Reproduction steps

1. Add GraphQL API with the following schema:
```graphql
type Asset @model @auth(rules: [{ allow: custom }]) {
    id: ID!
    name: String
}
```
2. Set the default authorization mode on the API as "AWS_LAMBDA"
3. Create a new Lambda function as directed by the CLI
4. Make the Lambda always return `{isAuthorized: true}`
5. Make requests to the API, either from the AppSync console or from a client app (e.g. a React app)
6. Any request will return Unauthorized.

### GraphQL schema(s)

<details>

```graphql
type Asset @model @auth(rules: [{ allow: custom }]) {
    id: ID!
    name: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
Hi @dragosiordachioaia, can you try updating your lambda function as below and let us know if you're still having issues 

```
exports.handler = async (event) => {
  console.log(`event =`, JSON.stringify(event, null, 2));
  return { isAuthorized: true, resolverContext: {} };
};
```
