### ISSUE TITLE
Unexpected token in JSON at position 0 during amplify pull/push

### ISSUE THREAD

**Issue by suneelmatham** [aws-amplify/amplify-cli#9654]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

7.6.13

### What operating system are you using?

Mac OS 12.1

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Updated #current-cloud-backend.zip after duplicate files were created due to icloud sync. Followed the steps outlined in https://github.com/aws-amplify/amplify-cli/issues/3576#issuecomment-596732233 to remove duplicate files and uploading a new #current-cloud-backend.zip file

After updating the zip file, i am getting an 'unexpected token at position 0' error during amplify pull/push.

### Amplify Categories

api

### Amplify Commands

pull, push

### Describe the bug

Getting an 'unexpected token at position 0' error during amplify pull/push.

### Expected behavior

Do amplify pull/push smoothly

### Reproduction steps

Didn't make any changes besides updating current-cloud-backend zip file in s3 deployment folder. I noticed a lot of empty '@' lines in logs.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

SyntaxError: Unexpected token ^@ in JSON at position 0
```

</details>

### Additional information

<img width="931" alt="Screenshot 2022-01-30 at 10 18 53 PM" src="https://user-images.githubusercontent.com/54971275/151708961-081c02fc-83e7-4d9a-93c3-776825ac87ee.png">
<img width="903" alt="Screenshot 2022-01-30 at 10 19 33 PM" src="https://user-images.githubusercontent.com/54971275/151708971-bad067e9-b693-4cf4-addf-b3e4f906ae88.png">
<img width="903" alt="Screenshot 2022-01-30 at 10 20 56 PM" src="https://user-images.githubusercontent.com/54971275/151709088-48b4a09b-7d50-4574-bf2f-c5437e8bdaed.png">

**Comment by edwardfoyle** [comment]
Hi @suneelmatham it seems like there is still some file in your deployment bucket that is expected to be JSON but has invalid contents. Some files to check would be the `amplify-meta.json`, `backend-config.json` and `cli.json` files but it could be other files as well.

Let us know if you're still having issues here and we can take a look at your deployment bucket to try to figure out what's going on.

**Comment by suneelmatham** [comment]
Hi @edwardfoyle , I fixed this by doing an `amplify push --force`. It's working fine now, thanks
