### ISSUE TITLE
A deployment is in progress.

### ISSUE THREAD

**Issue by Dayton-IX** [aws-amplify/amplify-cli#9665]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v15.5.1

### Amplify CLI Version

7.6.14

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

When trying to push updates to the cloud, I am now getting this error:
`A deployment is in progress.
If the prior rollback was aborted, run:
"amplify push --iterative-rollback" to rollback the prior deployment
"amplify push --force" to re-deploy`
Even though there is no deployment running, the last time a deployment was ran was on 1/27/2022, which completed successfully. 

### Expected behavior

A successful `amplify push`

### Reproduction steps

Unknown, amplify push was working properly last week, stopped working this Monday morning. :/
I have discussed this with the members of my team, and none of them seem to have done anything out of the ordinary either.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

- I have run `amplify pull` to make sure I have the latest changes from the cloud.
- Running `amplify push --force` throws: `An error occurred during the push operation: ["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]`
- Running `amplify push --iterative-rollback` also throws: `An error occurred during the push operation: ["Index: 1 State: {\"preRollback\":\"previousDeploymentReadyCheck\"} Message: Resource is not in the state stackUpdateComplete"]`

I have tried the suggestion [here](https://github.com/aws-amplify/amplify-cli/issues/7237#issuecomment-832117481) but this does not seem to apply to the latest version of amplify, as the .json files mentioned don't seem to exist on my build.

**Comment by harshmsomani** [comment]
Facing the same issue, running 'amplify rebuild api' also throws an error

**Comment by Ilya93** [comment]
I have the same problem after upgrading amplify to latest version

**Comment by Dayton-IX** [comment]
> Hey @Dayton-IX 👋 thanks for raising this and apologies for the delay! Are you seeing any CloudFormation errors in the console when pushing? Does this error occur before the push operations begin?

The error is occurring before the push operation begins. It doesn't look like there are any errors in CloudFormation, in fact it indicates that everything was completed successfully on the last push we were able to make.

**Comment by sachscode** [comment]
Hi @Dayton-IX 
1.  Could you please share the error messages seen on the screen for the `amplify push` process. 
2. Could you please confirm the contents of the deployment bucket of your project? 
    Amplify uses a file called [deployment-state.json](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-state-manager.ts#L15) to maintain deployment state. Do you see this file in the deployment bucket ?

Hi @harshmsomani 
Could you please provide the details of the error that you see when you run "amplify rebuild api" .

**Comment by Dayton-IX** [comment]
<img width="1404" alt="Screen Shot 2022-02-14 at 1 11 22 PM" src="https://user-images.githubusercontent.com/40467528/153939402-80919aca-a94c-41ea-95cc-6cf8d020a8dc.png">

I don't see a deployment-state.json in my amplify folder, where can I find it?

**Comment by reptiliano37** [comment]
I have the same problem. Any solution? I don't found deplyment-state.json either ...

**Comment by reptiliano37** [comment]
@Dayton-IX Hello! Finally, I found deployment-state.json in Amazon S3/Buckets , from aws console! Sorry, my aws console is in Spanish.

![imagen](https://user-images.githubusercontent.com/37412545/154442377-55fb7df4-f6f9-4090-abaa-ccfe5d51e7bc.png)

**Comment by sarv-fuse** [comment]
@sachscode 
> 2. Could you please confirm the contents of the deployment bucket of your project?
>    Amplify uses a file called [deployment-state.json](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/iterative-deployment/deployment-state-manager.ts#L15) to maintain deployment state. Do you see this file in the deployment bucket ?

{
  "version": "1",
  "startedAt": "2022-02-18T07:16:51.118Z",
  "status": "ROLLING_BACK",
  "currentStepIndex": 0,
  "steps": [
    {
      "status": "ROLLING_BACK",
      "previousMetaKey": "amplify-appsync-files/62b1222fb09eda4fb1e6ec134e8cecea195dd340/states/initial-stack/deployment-meta.json"
    },
    {
      "status": "ROLLED_BACK"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    },
    {
      "status": "WAITING_FOR_DEPLOYMENT"
    }
  ]
}

**Comment by harshmsomani** [comment]
@sachscode 
error: uncaughtException: Error occurred while monitoring stack:The security token included in the request is expired date=Wed Feb 23 2022 19:48:38 GMT+0530 (India Standard Time), pid=19867, uid=501, gid=20, cwd=/Users/hsomani/Hoora/production/hoora, execPath=/Users/hsomani/.amplify/bin/amplify, version=v12.22.7, argv=[/Users/hsomani/.amplify/bin/amplify, /snapshot/node_modules/@aws-amplify/cli/bin/amplify, push, --force], rss=194797568, heapTotal=236077056, heapUsed=217374264, external=108229369, arrayBuffers=106650157, loadavg=[2.45263671875, 2.5439453125, 2.58251953125], uptime=795020, trace=[column=29, file=/snapshot/node_modules/aws-sdk/lib/protocol/query.js, function=Request.extractError, line=50, method=extractError, native=false, column=20, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=106, method=callListeners, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=686, method=emit, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/snapshot/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=null, line=688, method=null, native=false, column=18, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.emit, line=78, method=emit, native=false, column=14, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=Request.emit, line=686, method=emit, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=Request.transition, line=22, method=transition, native=false, column=12, file=/snapshot/node_modules/aws-sdk/lib/state_machine.js, function=AcceptorStateMachine.runTo, line=14, method=runTo, native=false, column=10, file=/snapshot/node_modules/aws-sdk/lib/state_machine.js, function=null, line=26, method=null, native=false, column=9, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=null, line=38, method=null, native=false, column=12, file=/snapshot/node_modules/aws-sdk/lib/request.js, function=null, line=688, method=null, native=false, column=18, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=Request.callListeners, line=116, method=callListeners, native=false, column=12, file=/snapshot/node_modules/aws-sdk/lib/sequential_executor.js, function=callNextListener, line=96, method=null, native=false, column=13, file=/snapshot/node_modules/aws-sdk/lib/event_listeners.js, function=IncomingMessage.onEnd, line=335, method=onEnd, native=false, column=22, file=events.js, function=IncomingMessage.emit, line=326, method=emit, native=false, column=12, file=domain.js, function=IncomingMessage.EventEmitter.emit, line=483, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1241, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=84, method=null, native=false], stack=[ExpiredToken: Error occurred while monitoring stack:The security token included in the request is expired,     at Request.extractError (/snapshot/node_modules/aws-sdk/lib/protocol/query.js:50:29),     at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:106:20),     at Request.emit (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/snapshot/node_modules/aws-sdk/lib/request.js:686:14),     at Request.transition (/snapshot/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/snapshot/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /snapshot/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:688:12),     at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:116:18),     at Request.emit (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:78:10),     at Request.emit (/snapshot/node_modules/aws-sdk/lib/request.js:686:14),     at Request.transition (/snapshot/node_modules/aws-sdk/lib/request.js:22:10),     at AcceptorStateMachine.runTo (/snapshot/node_modules/aws-sdk/lib/state_machine.js:14:12),     at /snapshot/node_modules/aws-sdk/lib/state_machine.js:26:10,     at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:38:9),     at Request.<anonymous> (/snapshot/node_modules/aws-sdk/lib/request.js:688:12),     at Request.callListeners (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:116:18),     at callNextListener (/snapshot/node_modules/aws-sdk/lib/sequential_executor.js:96:12),     at IncomingMessage.onEnd (/snapshot/node_modules/aws-sdk/lib/event_listeners.js:335:13),     at IncomingMessage.emit (events.js:326:22),     at IncomingMessage.EventEmitter.emit (domain.js:483:12),     at endReadableNT (_stream_readable.js:1241:12),     at processTicksAndRejections (internal/process/task_queues.js:84:21)]

**Comment by sachscode** [comment]
@harshmsomani  looks like the error you are facing is different in that it appears to be an expired IAM session is being used to push resources. `"The security token included in the request is expired date=Wed Feb 23 2022 19:48:38 GMT+0530 (India Standard Time)"` .
1. Could you please confirm if you are using the correct IAM profile.
2. Could you please check if you are using "sts role" in your ~/.aws/credentials . Please refresh this token. 
Please retry and let us know if it works for you

**Comment by sachscode** [comment]
@reptiliano37  After deleting the deployment-state.json, is the amplify-push still failing ?  If its failing , could you please log into your AWS console and check the cloudformation logs for the stacks that have failed during deployment.

@sarv-fuse Could you please try deleting the deployment-state.json and please retry `amplify push` ?

**Comment by Dayton-IX** [comment]
@reptiliano37 @sachscode  Thanks! I found deployment-state.json, deleted it, and was able to push new updates to that env again!

**Comment by jnastaskin** [comment]
@sachscode  I'm also having this issue  and after deleting  the deployment-state.json file, I've tried running amplify push, amplify push --force, and  amplify push --iterative-rollback   and they all fail. Here is the error

![image](https://user-images.githubusercontent.com/31951390/157912377-5b520c6c-f5f5-4810-a4e3-82de1ac06d5e.png)

Are there any files that I should be looking at to debug this? The error really doesn't give much insight.

**Comment by TitusEfferian** [comment]
i always can reproduce this error on my current on going project.

here is my step to reproduce

### 1. create new data models from amplify studio, and the schema will look likes this
```
type Carts @model @auth(rules: [{allow: public}]) {
  id: ID!
  cartID: ID!
}
```

click deploy from amplify studio

### 2. pull to the local machine with simple amplify pull
`amplify pull` and everything still success

### 3. change the graphql schema from local machine
```
type Carts @model @auth(rules: [{allow: public}]) {
  id: ID!
  cartID: ID! @primaryKey
}
```

### 4. deploy  using `amplify push --allow-destructive-graphql-schema-updates`

and i got an error from the CLI
```
\ Rolling back (2 of 1)🛑 An error occurred during the push operation: /
["Index: 0 State: {\"deploy\":\"waitingForDeployment\"} Message: Resource is not in the state stackUpdateComplete"]
```

the `deployment-state.json` will shown up on s3. 
And i always got and same error like the author of this issue `A deployment is in progress. If the prior rollback was aborted, run: "amplify push --iterative-rollback" to rollback the prior deployment "amplify push --force" to re-deploy`

and i can fix it by delete the `deploment-state.json` on s3

any insight why is this happening? thank you

### My Amplify CLI Version
10.0.0

**Comment by Etx17** [comment]
After deleting the json file mentionned, i get :
Uploading files.🛑 Your:'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed'
