### ISSUE TITLE
Cognito mail invitation message template is not supported from cli-inputs.json ??

### ISSUE THREAD

**Issue by togro** [aws-amplify/amplify-cli#9668]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

On file cli-inputs.json I have 

emailVerificationSubject
emailVerificationMessage

But cognito has another template **"Invitation message"** , can configure that message like Verification message on cli-inputs.json ?

O the only way is add template on cognito web console ?

![image](https://user-images.githubusercontent.com/7252575/151905831-9a563efb-2e3d-4629-ad2b-f93e67f06bb3.png)

### Expected behavior

I expected on the cli-inputs.json file the same config for Verification Message, some like  :
```
{
  "version": "1",
  "cognitoConfig": {
          .... 
         "emailInvitationSubject": "Your temporary password",
         "emailInvitationMessage": "Your username is {username} and temporary password is {####}."
          ....
   }
 }
```

### Reproduction steps

I expected that amplify-client create fields for email verification messages

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @togro :wave: we can use overrides to set this property! Using [this doc for reference](https://docs.amplify.aws/cli/auth/override/) we can run `amplify override auth` and use the following to customize the invitation message template:

```ts
import * as cognito from '@aws-cdk/aws-cognito'
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  const inviteMessageTemplate: cognito.CfnUserPool.InviteMessageTemplateProperty =
    {
      emailMessage:
        'Hello {username}, you have been invited to join our awesome app! Your temporary password is {####}',
      emailSubject: "You're Invited!",
    }

  resources.userPool.adminCreateUserConfig = {
    inviteMessageTemplate,
  }
}

```

By doing so, this allows us to control the invitation message template from within the `overrides.ts` file. If we wish to keep the messaging together in `cli-inputs.json` we can also create new inputs that will be used as parameters to our CloudFormation template:

**cli-inputs.json**

```diff
{
  // ...
  "smsAuthenticationMessage": "Your authentication code is {####}",
  "smsVerificationMessage": "Your verification code is {####}",
  "emailVerificationSubject": "Your verification code",
  "emailVerificationMessage": "Your verification code is {####}",
+ "invitationEmailMessage": "Hello {username}, your temporary password is {####}",
+ "invitationEmailSubject": "You're invited -- from the cli-inputs.json!",
  // ...
}
```

And modify our `overrides.ts` to simply reference the new parameters:

```ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPool.addPropertyOverride('AdminCreateUserConfig', {
    InviteMessageTemplate: {
      EmailMessage: {
        Ref: 'invitationEmailMessage',
      },
      EmailSubject: {
        Ref: 'invitationEmailSubject',
      },
    },
  })
}
```

Now after we push our resources with `amplify push` we can see the changes are reflected in the console 🙂 
![image](https://user-images.githubusercontent.com/5033303/152055243-5daae0cb-630e-4f50-96f9-614980f79aa2.png)

**Comment by josefaidt** [comment]
I'll mark this as a feature request to automatically generate those parameters and CFN references for auth resources 🙂

**Comment by togro** [comment]
Thanks !
 works fine !
👍
