### ISSUE TITLE
Cannot use IAM auth after migrating to v2

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-cli#9673]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.11

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

Hello

I've migrated my graphql api to GraphQL transformer v2.

I had specified { allow: public, provider: iam } as an auth rule in v1 and thus I was able to do all operations when logged in as an IAM user when having necessary permissions.

But after migrating to v2 and using the same auth directive, being { allow: public, provider: iam }, I am getting Unauthorized access.

what could be the cause for this ?

```
type Customer
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: public, provider: iam }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  customer_last_name: String! 
  customer_mailing_address: String
```

This is the access control matrix for above type

iam:public
  ┌──────────────────────────┬────────┬──────┬────────┬────────┐
  │         (index)          │ create │ read │ update │ delete │
  ├──────────────────────────┼────────┼──────┼────────┼────────┤
  │            id            │  true  │ true │  true  │  true  │
  │          owner           │  true  │ true │  true  │  true  │
  │    customer_last_name    │  true  │ true │  true  │  true  │
  │ customer_mailing_address │  true  │ true │  true  │  true  │
  └──────────────────────────┴────────┴──────┴────────┴────────┘

### Expected behavior

The { allow: public, provider: iam } needs to allow all operations for an IAM user with access to the API.

### Reproduction steps

1. Create Customer table using v1.
2. Specify public IAM auth
3. Create Customer table using v2
4. Specify a similar public IAM auth
5. Test accessing data in both.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Customer
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: public, provider: iam }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  customer_last_name: String! 
  customer_mailing_address: String


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
@rezab777 could you clarify what you mean by "Test accessing data in both." Are you using the AppSync console or something else? If you're using the AppSync console, please check out these instructions: https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console
