### ISSUE TITLE
amplify pull failed to pull backend if it is imported

### ISSUE THREAD

**Issue by hf-qin** [aws-amplify/amplify-cli#9674]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

6.14.12

### Amplify CLI Version

7.6.14

### What operating system are you using?

windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

pull

### Describe the bug

When run amplify pull, got the error message:
```
Failed to pull the backend.    
File at path: '<projectfolder>\amplify\backend\auth\<app name>\parameters.json' does not exist
```

### Expected behavior

The error message shouldn't appear

### Reproduction steps

1. init a new amplify project
2. use `amplify import auth` to add an existing backend
3. `amplify push` commit the amplify app change
4. push the change to the git repository
5. clone the repository
6. run `amplify pull` to pull the backend

### Additional information

I checked the code, line 179 in [index.js](https://github.com/aws-amplify/amplify-cli/blame/master/packages/amplify-category-auth/src/index.js) was revised in https://github.com/aws-amplify/amplify-cli/commit/b6008614b5b1cd739d2966ed644edf810290a798

'build' was inserted as part of the path to 'parameters.json', as shown below:
```
@ -165,10 +165,10 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
         delete cliInputs[paramName];
       }
     });
-    context.amplify.saveEnvResourceParameters(context, category, existingAuthResource, envSpecificParams);
-    const resourceDirPath = path.join(amplify.pathManager.getBackendDirPath(), 'auth', authProps.resourceName, 'parameters.json');
+    context.amplify.saveEnvResourceParameters(context, category, authExists, envSpecificParams);
+    const resourceDirPath = path.join(amplify.pathManager.getBackendDirPath(), 'auth', authProps.resourceName, 'build', 'parameters.json');
     const authParameters = await amplify.readJsonFile(resourceDirPath);
-    if (!existingAuthResource) {
+    if (!authExists) {
       const options = {
         service: 'Cognito',
         serviceType: 'managed',
```

As a workaround, when reaching the 'Please tell us about your project' stage, if manually copies the 'parameters.json' from the 'build' folder to the app folder, the amplify pull will complete successfully.

**Comment by josefaidt** [comment]
Hey @hf-qin :wave: thanks for raising this! It sounds like you're experiencing a bug similar to what is described in this issue https://github.com/aws-amplify/amplify-cli/issues/9508, can you confirm this is what you're running into?

**Comment by hf-qin** [comment]
> Hey @hf-qin 👋 thanks for raising this! It sounds like you're experiencing a bug similar to what is described in this issue #9508, can you confirm this is what you're running into?

Hey @josefaidt. I think the root cause of the one and #9508 is the same.

**Comment by josefaidt** [comment]
Hey thanks for confirming! I'll mark this as a duplicate and close in favor of tracking #9508. Please subscribe to that issue for further updates 🙂
