### ISSUE TITLE
Multienv CloudFormation-template Git Merge Conflicts

### ISSUE THREAD

**Issue by richardzyx** [aws-amplify/amplify-cli#968]
**Describe the bug**
When following the recommended workflow for teams https://aws-amplify.github.io/docs/cli/multienv?sdk=js and merging sandboxes, git conflicts on cloudformation-template files for lambda functions occur and force each sandbox to do a new commit.

**To Reproduce**
Simply follow all the step on the recommended team workflow.

**Expected behavior**
Test just need to do git merge dev and no git conflicts should occur since test was build from a past commit in dev.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 1.1.5

I see that according to #819 it's safe to ignore awscloudformation/ folder which was also causing git conflicts, but I don't believe it's auto generated from the CLI when initing new envs?

**Comment by kaustavghosh06** [comment]
@richardzyx It is safe to include that in the gitignore. it will get automatically created when you're doing an `amplify push`.

**Comment by richardzyx** [comment]
@kaustavghosh06 thanks for the clarification, but I'm wondering if that should be in the default .gitignore or behavior for CLI? It was difficult to track down these unexpected behavior so if the CLI can take care of that out-of-the-box that would be very helpful. 

Thanks!

**Comment by kaustavghosh06** [comment]
@richardzyx If you initialize a new project using the CLI now, we do add all these files in your .gitignore files so that you don't have to think about it.

**Comment by dopry** [comment]
@kaustavghosh06 amplify/backend/function/*/*-cloudformation-template.json is not ignored by default and still causes these errors.
