### ISSUE TITLE
Auth override.ts lambdaConfigPermissions

### ISSUE THREAD

**Issue by IvanCaceres** [aws-amplify/amplify-cli#9680]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.4.2

### Amplify CLI Version

7.6.14

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Made customizations to cloudformation template such as setting lambda triggers not provided by the CLI.
Cloudformation template is deleted in the latest amplify version and replaced with override.ts pending a prompt to migrate.

### Amplify Categories

auth

### Amplify Commands

override

### Describe the bug

After running auth override.ts I am attempting to configure Lambda triggers and their Lambda invoke AWS::Lambda::Permission's via the resources.lambdaConfigPermissions property. I see that lambdaConfigPermissions is typed to only hold values of type lambda.CfnPermission. However the override.ts sandbox does not allow access to the @aws-cdk primitives so I can't instantiate a version of this class. I have tried setting the property values via a plain object as the example code shows below, however this is not creating the invoke permissions and I'm not seeing them on the AWS Lambda console site under Lambda => configuration => Permissions.

I would greatly appreciate any help on how to use lambdaConfigPermissions properly or lambdaTriggerPermissions.

Thanks!

```
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyAuthCognitoStackTemplate) {
    // https://github.com/aws-amplify/amplify-cli/issues/9063#issuecomment-996200713
    // hacky workaround to get the amplify meta data with a require statement
    // the amplify override.ts is not provided the stack parameters we need like functioncognitoCustomEmailSenderPostmarkArn
    const amplifyMetaJson = require('../../../amplify-meta.json')
    const cdkLambda = require('@aws-cdk/aws-lambda')
    let amplifyEnv = amplifyMetaJson.providers.awscloudformation.StackName.split(
        '-'
    )
        .slice(-2, -1)
        .pop()
    let kmsKeyId =
        amplifyMetaJson.function.cognitoCustomEmailSenderPostmark.output[
            'KMSKeyArn'
        ]

    resources.userPool.lambdaConfig = {
        kmsKeyId,
        customEmailSender: {
            lambdaArn:
                amplifyMetaJson.function.cognitoCustomEmailSenderPostmark
                    .output['Arn'],
            lambdaVersion: 'V1_0',
        },
        preSignUp: amplifyMetaJson.function.authPreSignup.output['Arn'],
        postConfirmation:
            amplifyMetaJson.function.lgndUserPostConfirmation.output['Arn'],
    }
    resources.lambdaTriggerPermissions
    resources.lambdaConfigPermissions = {
        UserPoolCustomEmailSenderLambdaInvokePermission: {
            action: 'lambda:invokeFunction',
            principal: 'cognito-idp.amazonaws.com',
            functionName:
                amplifyMetaJson.function.cognitoCustomEmailSenderPostmark
                    .output['Name'],
            sourceArn: amplifyMetaJson.auth.lgndAuth.output['UserPoolArn'],
        } as any,
        UserPoolauthPreSignupLambdaInvokePermission: {
            action: 'lambda:invokeFunction',
            principal: 'cognito-idp.amazonaws.com',
            functionName: amplifyMetaJson.function.authPreSignup.output['Name'],
            sourceArn: amplifyMetaJson.auth.lgndAuth.output['UserPoolArn'],
        } as any,
    }
}
```

### Expected behavior

I expect to see the lambda invoke permissions created according to the properties set on the AmplifyAuthCognitoStackTemplate.lambdaConfigPermissions. These are not appearing on the AWS Lambda console => configuration => Permissions. Going through the normal app auth flow results in an access denied error because the invoke permission does not exist.

### Reproduction steps

1. amplify auth override
2. customize the auth override.ts with lambdaConfigPermissions as depicted in my example code.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

Amplify push completes successfully but the lambdaConfigPermissions are not created.

**Comment by fernandesGabriel** [comment]
I am experiencing the same issue, exactly with the `resources.lambdaConfigPermissions` override. I am using CLI 7.6.21

**Comment by fernandesGabriel** [comment]
@sachscode here is more detailed information:

1. I ran `amplify auth override`
2. Got the `overrides.ts` compiled just fine
3. Added rules as changing `resources.userPool.schema` and pushed it just fine
4. Outputed cloudformation contains properly the change on on `resources.userPool.schema`
5. Try to add `resources.lambdaConfigPermissions`
6. Try to push the new changes, no errors are thrown, but this new rule isn't included on the outputted cloudformation template like the one before the override

**Comment by akshbhu** [comment]
I think you are adding functions via ```amplify add function``` , this is why the lambdaConfigPermissions Object is empty.
Since userPool Object is already created , you are able to override its properties as present in above code.
lambdaConfigPermissions is of type ```CfnPermissions``` and since its not created while adding auth , you aren't able to override it and we have not allowed ```fs``` operations in ```override.ts``` file for security reasons.
For this purpose , we have ```amplify add custom``` command , that generated ```cdk-stack.ts``` file where you can add these custom resources of any type and access resources generated by amplify through APIs.

To add ```UserPoolCustomEmailSenderLambdaInvokePermission``` , you can try this:
```typescript
import * as cdk from '@aws-cdk/core';
import * as AmplifyHelpers from '@aws-amplify/cli-extensibility-helper';
import { AmplifyDependentResourcesAttributes } from '../../types/amplify-dependent-resources-ref';
import * as lambda from '@aws-cdk/aws-lambda';
export class cdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps, amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, 'env', {
      type: 'String',
      description: 'Current Amplify CLI env name',
    });
    // Access other Amplify Resources
    const retValFunction:AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(this,
      amplifyResourceProps.category,
      amplifyResourceProps.resourceName,
      [
        {category: 'function', resourceName: 'i9680475e25f4475e25f4PreSignup'},
      ]);
    const retValAuth:AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(this,
      amplifyResourceProps.category,
      amplifyResourceProps.resourceName,
      [
        {category: 'auth', resourceName: 'i9680475e25f4475e25f4'},
      ]);
      const key = 'preSignup';
      const resourceKey = `UserPool${key}LambdaInvokePermission`;
      new lambda.CfnPermission(this, `${resourceKey}`, {
          action: 'lambda:invokeFunction',
          principal: '[cognito-idp.amazonaws.com](http://cognito-idp.amazonaws.com/)',
          functionName: cdk.Fn.ref(retValFunction.function.i9680475e25f4475e25f4PreSignup.Name),
          sourceArn: cdk.Fn.ref(retValAuth.auth.i9680475e25f4475e25f4.UserPoolArn),
      });
    }
}
```

Let me know if this works for you?

**Comment by akshbhu** [comment]
Thanks for clarifying. I  have identified a bug with preSignup naming thats why its not able to set the LambdaConfig and permissions properly.
I have put a pull request to address this bug

**Comment by kennyd-reacthealth** [comment]
> I think you are adding functions via `amplify add function` , this is why the lambdaConfigPermissions Object is empty. Since userPool Object is already created , you are able to override its properties as present in above code. lambdaConfigPermissions is of type `CfnPermissions` and since its not created while adding auth , you aren't able to override it and we have not allowed `fs` operations in `override.ts` file for security reasons. For this purpose , we have `amplify add custom` command , that generated `cdk-stack.ts` file where you can add these custom resources of any type and access resources generated by amplify through APIs.
> 
> To add `UserPoolCustomEmailSenderLambdaInvokePermission` , you can try this:
> 
> ```ts
> import * as cdk from '@aws-cdk/core';
> import * as AmplifyHelpers from '@aws-amplify/cli-extensibility-helper';
> import { AmplifyDependentResourcesAttributes } from '../../types/amplify-dependent-resources-ref';
> import * as lambda from '@aws-cdk/aws-lambda';
> export class cdkStack extends cdk.Stack {
>   constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps, amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps) {
>     super(scope, id, props);
>     /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
>     new cdk.CfnParameter(this, 'env', {
>       type: 'String',
>       description: 'Current Amplify CLI env name',
>     });
>     // Access other Amplify Resources
>     const retValFunction:AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(this,
>       amplifyResourceProps.category,
>       amplifyResourceProps.resourceName,
>       [
>         {category: 'function', resourceName: 'i9680475e25f4475e25f4PreSignup'},
>       ]);
>     const retValAuth:AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(this,
>       amplifyResourceProps.category,
>       amplifyResourceProps.resourceName,
>       [
>         {category: 'auth', resourceName: 'i9680475e25f4475e25f4'},
>       ]);
>       const key = 'preSignup';
>       const resourceKey = `UserPool${key}LambdaInvokePermission`;
>       new lambda.CfnPermission(this, `${resourceKey}`, {
>           action: 'lambda:invokeFunction',
>           principal: '[cognito-idp.amazonaws.com](http://cognito-idp.amazonaws.com/)',
>           functionName: cdk.Fn.ref(retValFunction.function.i9680475e25f4475e25f4PreSignup.Name),
>           sourceArn: cdk.Fn.ref(retValAuth.auth.i9680475e25f4475e25f4.UserPoolArn),
>       });
>     }
> }
> ```
> 
> Let me know if this works for you?

This does work, with one small change.  The principal line should be updated to simply `cognito-idp.amazonaws.com`. In my case, I used to not for the preSignUp trigger but for the Custom Email Sender and Custom SMS Sender triggers.
