### ISSUE TITLE
Multi Auth Modes on a single type @model and single api call with IAM and Cognito

### ISSUE THREAD

**Issue by jcolvard** [aws-amplify/amplify-cli#9683]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Auth, API(GraphQL)

**Amplify CLI Version** 
7.6.14

**What AWS Services are you utilizing?**
Auth & Api from Amplify CLI
AppSync
Cognito
IAM

**Provide additional details e.g. code snippets**
I'm trying to allow unauthenticated guest visitors to read(listTodos) from a DynamoDB table. And I want authenticated users to be able to read(listTodos) and update(updateTodo) from within DynamoDB.

I've spent many hours getting to know the services and methods of approach for this pattern, but I have yet to find the bulletproof, best practice for accomplishing this common use case. Any advice, feedback, or info you can share, would be tremendously appreciated. Thank you very much in advance!

Note, my example here actually just deals with the read function(listTodos), to make things simpler, I'm leaving the operation specifics out of it.

**Relavent App Configuration(If there's something additional I need to config, that I've overlooked, please let me know 🙌 )**
```
create-react-app
amplify init
amplify add auth
  - Allow Unauthenticated Users: YES
  - Email based sign in
amplify add api
  - Default auth mode: Cognito User Pools
  - Additional auth mode: IAM
Confirmed within the AppSync Console > Settings both auth modes are in place
I have custom sign up/sign in flows, nothing at all fancy, all in place and working fine
```
So, dare I say, I did, almost, kind of-ish get this working using this graphqlSchema:

```
type Todo
  @model
  @aws_cognito_user_pools
  @aws_iam
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: private, provider: userPools, operations: [read, update] }
    ]
  ) {
  id: String!
  name: String!
}
```
So with that schema ☝️ `amplify push`ed, using this code on the front-end React:
```
{ user } = useUser() //This is an imported user hook, tied into my Amplify Auth, It works
[todoArray, setTodoArray] = useState([])

useEffect(() => {
  const fetchTodos = async () => {
    try {
      const todoData = await API.graphql({
        query: listTodos,
        authMode: !user ? 'AWS_IAM' : 'AMAZON_COGNITO_USER_POOLS'
      })
      const allTodoItems = todoData.data.listTodos.items
      setTodoArray(allTodoItems)
    } catch (error) {
      console.log('Not Workin:', error)
    }
  }
  fetchTodos()
}, [user])

console.log(todoArray)
```
I have it 98% working, save a React useEffect hiccup, which I need to iron out. What happens with an _authenticated user_ is that, the page loads, rendering the app, causing the useEffect hook to fire fetchTodos(). This function starts running _before_ my `user` object is returned from Cognito, and so the graphQL request is sent using `authMode: AWS_IAM`. This kicks me a **401 Unauthorized** in the console because I am Authorized/signed-in, therefore my auth rule is `allow: private, provider: userPools`, but again the front end call thinks I want to request using IAM. A fraction of a second later, the `user` object/ useEffect dependency gets updated, re-triggering useEffect, with `user` and the proper Congito mode, and successfully returns my `todoArray`. So, I get what I'm hoping for, plus a 401(if you feel like sharing easiest way to fix that, would greatly appreciate it). As for the _unauthenticated user_, there never is any user to wrangle, the page loads and stays loaded with no `user` info, the api call gets triggered on page load, with IAM and the appropriate `public` guest identity, todos come back, rock n roll 🎉 

So, my first question for you all is, does that ☝️ all seem like a good practice/approach(assuming the 401 gets fixed 😆 )? Would love to hear your thoughts, or if anyone has a better, simpler solution.

-----

My second question is regarding my other approach at the private/public api access. I was stumped on that useEffect thing for a bit, so I decided to try and do away with Cognito completely and go with IAM for private and public access. So I updated my schema to this:
```
type Todo
  @model
  @aws_iam
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: private, provider: iam, operations: [read, update] }
    ]
  ) {
  id: String!
  name: String!
}

```
I `amplify push`ed that ☝️ Then I `amplify update api`d to change my default authentication mode to `IAM` with no secondary autth mode(I actually tried it with Cognito as a secondary, and with no secondary). I confirmed in the AppSync console that these settings were in place.

Then I updated my front end, getting rid of the `user` and the ternary check inside of the authMode

```
[todoArray, setTodoArray] = useState([])
useEffect(() => {
  const fetchTodos = async () => {
    try {
      const todoData = await API.graphql({
        query: listTodos,
        authMode: 'AWS_IAM'
      })
      const allTodoItems = todoData.data.listTodos.items
      setTodoArray(allTodoItems)
    } catch (error) {
      console.log('Not Workin:', error)
    }
  }
  fetchTodos()
}, [])

console.log(todoArray)
```
The result is that, the call succeeds on my _public rule_ with an _unauthenticated guest usser_, but I get the 401 unauthorized error when the same call runs with an _authenticated user_. I've tried every which permutation of rules, removed the public rule entirely, set IAM as my only auth mode and deleted the `provider: iam` option, everything I could think of. Can't get it. By adding the `provider: iam` flag on the rule in my schema, and then `amplify push`ing the back end I can verify that the resources are being generated. I can see that the resources are being added onto the correct policy, which is attached to the AuthRole that is associated with my Federated Identity Pool. However, I cannot call a successful api request from an authenticated user with {allow: private, provider: iam} 🤷‍♂️ 

My second question, has anyone else experienced this? Is there anything that jumps out as to what I might be doing wrong? If there's something in the Docs that I've overlooked, my apologies. It seem like I'm following the rules based on the content here: https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access

Thank you very much for any help you might be able to offer!

**Comment by utopianf** [comment]
I have just encountered this problem and post it on [re:Post](https://repost.aws/questions/QUoW1YoL9ETMGD2hv2jRJimg/app-sync-query-can-not-be-authorized-by-iam ).

The IAM cannot authenticate my query even on AppSync.

**Comment by sundersc** [comment]
@jcolvard - Was the authenticated user mapped to any user pool groups? This can be verified in Cognito console.

**Comment by jcolvard** [comment]
@sundersc, thanks for getting back, and thanks for chiming in on the last issue I participated on.

My main user was added to an admin group in Cognito. My other user that I test with was not part of a cognito group, and I’m almost sure that I had the same failed private iam attempt with that user. I will verify and update here tomorrow.

Question though, if a user is part of a cognito user group, will that cause an inability for that user to make a private iam api call?

Will update tomorrow.

**Comment by sundersc** [comment]
There is a known issue with the IAM:private rule when the authenticated user belongs to a user group. If your are running into this, it can be solved as stated [here](https://github.com/aws-amplify/amplify-cli/issues/9502#issuecomment-1028316931).
