### ISSUE TITLE
Amplify generated "list" query does not return proper result

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-cli#969]
**Describe the bug**
Amplify generated "list" query does not return proper result. I am not sure if it is the issue with amplify, appsync or dynamodb. Any help and insights would help.

**To Reproduce**
1. I have the following graphql schema: 

```
type BookEntity @model @searchable {
  id: ID!
  bookSection: String
  bookOrder: String
  bookCode: String!
  bookCodeTitleRu: String
  bookElementOrder: String
  type: String
  chapterNumber: String
  verseNumber: String
  cleanedContent: String
  content: AWSJSON
  verseContent: AWSJSON
  elements: AWSJSON
}
```
Amplify generates for me `listBookEntitys` beside others out of this schema.

2. I have imported "manually" [this file](https://github.com/sakhmedbayev/myPublicRepo/blob/master/carsProject/019PSA-result.json) into the "BookEntityTable".

3. Made a global secondary index with "bookCode" as a partition key and an "index" (a field in my data) filed as a sort key. I called that global secondary index as "gsi-bookCode-sortIndex"

4. I also modified amplified generated request template for the for `Query.listBookEntitys.req.vtl` in the following way:

```
#set($myFilters = {})
#set($myFilters.chapterNumber = $ctx.args.filter.chapterNumber)
#set($myFilters.type = $ctx.args.filter.type)

{
    "version" : "2017-02-28",
    "operation" : "Query",
    "index" : "gsi-bookCode-sortIndex",
     "query" : {
        "expression": "#bookCode = :bookCode",
        "expressionNames" : {
        "#bookCode" : "bookCode"
    },
        "expressionValues" : {
            ":bookCode" : $util.dynamodb.toDynamoDBJson($ctx.args.filter.bookCode.eq)
        }
    },
    "filter": #if( $myFilters.chapterNumber ||  $myFilters.type)
		$util.transform.toDynamoDBFilterExpression($myFilters)
 	#else
		null
 	#end
}
```

4. Putting that all together gave me a way to query my data successfully using this query type and variables:

```
query ListBookEntitys($filter: ModelBookEntityFilterInput, $limit: Int, $nextToken: String) {
  listBookEntitys(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      ...BookEntityItem
      __typename
    }
    nextToken
    __typename
  }
}

fragment BookEntityItem on BookEntity {
  id
  bookCode
  bookSection
  bookOrder
  bookCodeTitleRu
  bookElementOrder
  type
  chapterNumber
  verseNumber
  cleanedContent
  content
  verseContent
  elements
  __typename
}
```

variables: 

```
{
  "filter": {
    "bookCode": {
      "eq": "PSA"
    },
    "chapterNumber": {
      "eq": "95"
    }
  }
}
```

4. The issue lays in that problem that I can query data only up to `chapterNumber: 96`. If, however, I try to query `chapterNumber": { "eq": "97"}`, I receive an empty `items` array:

```
{
  "data": {
    "listBookEntitys": {
      "items": [],
      "nextToken": "eyJ2ZXJzaW9uIjoxLCJ0...
```

**Expected behavior**
To get a proper response regardless of the `chapterNumber` value.

**Desktop (please complete the following information):**
 -  iOS
 - amplify cli version: 1.1.6

**Additional context**
The data for all chapters is in the DynamoDb table, "BookEntityTable", and can query it using dynamoDB console tools.

**Comment by mikeparisstuff** [comment]
If you have more items in your table than the limit of items being returned by that query for the particular hash key then you might not see the results you are expecting in the first page. The reason for this is that DyanmoDB filter expressions are run on records after they have been read from their individual partition. To guarantee that you get a record back where the chapterNumber == 96 then you should make "chapterNumber" the sort key of your index. You can then do a query where the bookCode == "PSA" and the chapterNumber == 96. In the current implementation DynamoDB will go to the partition where bookCode == "PSA", read "limit" number of rows from the partition, and then after reading the records filter them using the filter expression. If you provide a limit of 10 in the request and the record that you want is the 11th in the index then you will not get that value in the first page.

**Comment by sakhmedbayev** [comment]
Sorry, I forgot to report, the issue was resolved. My problem was that I had a bad partition key strategy in DynamoDB.
