### ISSUE TITLE
@function annotation in splitted schema file is not working (resolver is not created)

### ISSUE THREAD

**Issue by taskooh** [aws-amplify/amplify-cli#9698]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.15

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I want to split graphql schema files.
When splitting, the @function annotation in `extend type Query` is not working, and resolver is not created.

### Expected behavior

resolver should be created for the function `extend type Query`
```graphql
extend type Query {
  func2: Boolean @function(name: "apiResolver-{env}")
}
```

### Reproduction steps

1. `amplify add api` (Graphql)
2. amplify add function
3. create /schema folder under {apiName}, put schema.graphql, xxxx.graphql. (Schema is written down)
4. `amplify push`
5. look at appsync console, or /build/stacks/FunctionDirectiveStack.json, and confirm that resolver is not created for func2 (in `extend type Query`)

![image](https://user-images.githubusercontent.com/20131692/152473881-3166c04b-13bc-48d3-a9ef-0cfad0e38dd3.png)

### GraphQL schema(s)

<details>

[amplify/backend/api/ampschemabugtest/schema/schema.graphql]
```graphql
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type Todo @model {
  id: ID!
  name: String!
  description: String
}

type Query {
  func1: boolean @function(name: "apiResolver-{env}")
}
```

[amplify/backend/api/ampschemabugtest/schema/xxxx.graphql]
```graphql
extend type Query {
  func2: Boolean @function(name: "apiResolver-{env}")
}

```
</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @taskooh, Thank you for reaching out. Apologies on the delay in a response. On replicating this in my Amplify application I was able to experience a similar behavior. I was able to find a similar issue outlining this behaviour in https://github.com/aws-amplify/amplify-cli/issues/7846.

Marking this as feature request.
