### ISSUE TITLE
Yarn test on master fails in amplify-appsync-simulator

### ISSUE THREAD

**Issue by gpoul** [aws-amplify/amplify-cli#9703]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

git clone the source

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

master

### What operating system are you using?

Amazon Linux 2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

`yarn test` fails with "AWSURL parse Should reject an invalid URL 1" in the tests within amplify-appsync-simulator:

![image](https://user-images.githubusercontent.com/161626/152517982-a4dd7df6-cbdc-4031-93da-173c364f40a4.png)

### Expected behavior

yarn test should complete successfully

### Reproduction steps

1. Perform local env setup as described in https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#local-environment-setup
2. Run `yarn setup-dev`
3. Run `yarn test`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by cjihrig** [comment]
I am able to reproduce this with Node 16. The tests do not fail on Node 14, which explains how the change made it past our CI. Marking as a bug.
