### ISSUE TITLE
Regarding Amplify Hosting, "Amazon CloudFront and S3"

### ISSUE THREAD

**Issue by dayjournal** [aws-amplify/amplify-cli#9710]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify Hosting

**Amplify CLI Version**
v7.4.4
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Amazon CloudFront, Amazon S3

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I have three questions about hosting with "Amazon CloudFront and S3" selected in Amplify Hosting.

1 . about inaccessibility during deployment
Immediately after deployment using this function, it seems that the deployed application cannot be accessed as described in the link below.

![samole_00](https://user-images.githubusercontent.com/7871642/152683660-43bc1a0f-a17a-4f26-9b63-f02886c91934.png)

> This is because CloudFront forwards requests to the default S3 endpoint (s3.amazonaws.com), which is in the us-east-1 region, and it can take up to 24 hours for the new hosting bucket name to propagate globally.
https://docs.amplify.aws/cli/hosting/hosting/#amazon-s3-and-amazon-cloudfront

I was able to access the application by reconfiguring the CloudFront origin domain and adding the region to the address. Is there any way to reflect this when deploying without manually modifying the settings in this way?

![sample_01](https://user-images.githubusercontent.com/7871642/152683669-96d6e0c8-9d5b-4e42-8a92-c62a65a82239.png)
![sample_02](https://user-images.githubusercontent.com/7871642/152683674-bc80b03a-0a1b-4b8f-9942-6c44d703edc9.png)

2 . about S3 settings
In the S3 settings after deployment, the block public access is set to off, and the website hosting setting is enabled.
Although direct access is not allowed, I think there should be no problem if the blocked public access is turned on and the website hosting setting is disabled, and only CloudFront is configured.

![sample_03](https://user-images.githubusercontent.com/7871642/152683722-de8680eb-a76e-4727-97ec-2d2842803171.png)
![sample_04](https://user-images.githubusercontent.com/7871642/152683725-f0ddcafb-4b26-4290-b2b8-a19e1880d154.png)

3 . about automatic removal of S3
When I run "amplify remove hosting", CloudFront is automatically removed, but S3 does not seem to be automatically removed. Do I need to delete it manually? Or is there a way to remove it automatically?

**Comment by josefaidt** [comment]
Hey @dayjournal :wave: thanks for raising this and apologies for the delay! To share some insight on your questions:

1. based on the question for 2, this appears to be working as expected.
2. What stage was used to deploy? It appears we may want the `PROD` stage, https://docs.amplify.aws/cli/hosting/hosting/#stages
3. did you push after `amplify remove hosting`?

**Comment by dayjournal** [comment]
Hi, @josefaidt 
Thank you for your answer!

There is also a blog where I have tested it here.
Trying Out Various Settings for AWS Amplify Publishing
https://dev.to/aws-builders/trying-out-various-settings-for-aws-amplify-publishing-39i4

> based on the question for 2, this appears to be working as expected.

It seems that some regions may not be reflected until 24 hours as shown in this document. I was able to improve this manually, but is there any way to improve this automatically?
https://docs.amplify.aws/cli/hosting/hosting/#amazon-s3-and-amazon-cloudfront

> What stage was used to deploy? It appears we may want the PROD stage,

I used "PROD". The current configuration is fine, but for a more accurate configuration, it needs to reflect what you asked. It may be that the S3 settings are internally mixed with the "DEV" version. 

> did you push after amplify remove hosting?

I tried several times and CloudFront disappears automatically, but S3 remains.

**Comment by ykethan** [comment]
Hey @dayjournal , apologies for the delay in a response. on replicating hosting with cloudfront and s3 I observed the S3 bucket persisting. I created a github issue: https://github.com/aws-amplify/amplify-cli/issues/10478. Please feel free in adding your comments to the issue.

Closing this in favor of the issue.

**Comment by dayjournal** [comment]
Hi, @ykethan
Thank you for your response!
