### ISSUE TITLE
Unable to pull existing environments

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/amplify-cli#9711]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.14

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth, storage, function, api, analytics, hosting, interactions

### Amplify Commands

env

### Describe the bug

I recently pulled an existing Amplify project onto a new machine. I've run into multiple issues because it seems my local project is not properly synced with the cloud (I'm unable to delete or update an existing API, for instance, and receiving the error mentioned in https://github.com/aws-amplify/amplify-cli/issues/82). 

I currently have 3 env (dev, beta, prod). However, locally, I'm only seeing beta on `amplify env list`. `amplify pull` does not fix the issue. `amplify checkout env dev` gives me `Please pass in a valid environment name. Run amplify env list to get a list of valid environments`, and if I attempt `amplify add env dev`, I get the following error:
```
An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
AlreadyExistsException: Stack [amplify-amplifydemo-dev-151837] already exists
```

The only working solution is to create a new env. However, this workaround isn't a viable solution - if this were a production app, I would be completely unable to checkout / update existing environments.

### Expected behavior

Checking out an existing project locally would show me all existing environments, and allow me to delete / update existing resources. 

### Reproduction steps

1. Clone existing Amplify app
2. Attempt to checkout existing deployed environments
3. Attempt to delete or update an existing api

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String!
}

type Appointment @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  time: String!
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by romeubertho** [comment]
Hello,

I guess your `team-provider-info.json` does not have your dev environment there. `amplify env list` will list all envs based on the `team-provider-info.json` file

Try going to Amplify in your AWS console, find backend environments, click in edit backend and run the command there, something like: `amplify pull --appId YOUR_APP_ID --envName dev`.

I hope this can help you a bit xD
