### ISSUE TITLE
Lambda Authorizer being ignored when passing an OIDC token

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#9714]
**Which Category is your question related to?**
@auth directive and Lambda Authorizer. Not sure if this is actually an issue with AppSync or a misunderstanding of the Lambda Authorizer.

**Amplify CLI Version**

`7.6.14`

My API uses mostly OIDC as an auth provider. However, I have certain use cases where it is not sufficient. Therefore, I am trying to leverage Lambda Authorizers. 

I have annotated my model with an @auth directive as follow `@auth(rules: [{ allow: custom }])` .

It seems like if I put any random string (not an OIDC token), my Lambda Authorizer is executed ( as I see the execution through CloudWatch logs).

However, if I pass in an OIDC token, it seems like the Authorizer is not called and it is rather treated as if I made the request with another auth provider. I guess AppSync has no way of knowing, because I looked at the headers sent, OIDC vs Lambda and they are identical, ie theres no field that says OIDC or Lambda, it just infers it through the token?

Is there something i'm missing? I want to pass my users OIDC token to my lambda authorizer to make some checks, however, it seems like I can't do that. Only workaround would be to append or suffix a character to my token so that Lambda Authorizer is actually called.

Thank you.

**Comment by cjihrig** [comment]
@alexboulay how are you making requests to your GraphQL API?

**Comment by alexboulay** [comment]
@cjihrig for now, in the AppSync console.

**Comment by sundersc** [comment]
@alexboulay - I think that is due to validation on AppSync side. Does your token have `Bearer` as prefix (like `"Bearer <Token>"`).

**Comment by alexboulay** [comment]
@sundersc I am passing my token as is. If put Bearer as a prefix, it works, just as if I had added a random character to my token, I initially tried `_<token>` before posting this issue as a test/trying to figure out how to trigger the authorizer.

So my understanding is that it's all at the AppSync level and to instruct it to use the AWS_LAMBDA as an auth provider, I cannot give it an OIDC token as is?

**Comment by sundersc** [comment]
@alexboulay - That's my understanding too. Still I don't see a valid reason why AppSync would reject a valid OIDC token. I'm checking with AppSync engineers, I will post an update.

**Comment by alexboulay** [comment]
@sundersc To clarify, AppSync doesn't reject the token, it accepts it but since my @auth rules are configured to reject OIDC auth provider, I get a permission denied ( which is 100% expected ).

**Comment by sundersc** [comment]
Your interpretation is correct. Appsync tries to infer the auth type being used, and for most auth types, it knows what the credentials should look like. For example, for API keys, they come in one header, for IAM, it's a signature of a certain format, and for Cognito/OIDC, it's a specific type of token. For Lambda, however, it's inherently very open ended, so it's simply treated as the fallback answer. If you're providing a token that's exactly valid for another auth type, it'll always assume that auth is to be used, not Lambda, which is likely the case you're running into. To put that more succinctly - it's not that the Lambda isn't being invoked, it's that the service thinks you're trying to do OIDC auth, not Lambda. 

AppSync team is working on a docs update on this, but to fix, there's a few possibilities:
1) if you have to use oidc via lambda sometimes and via your oidc provider sometimes, tinker with the token as you already mentioned. Add a prefix/suffix before passing it in, then in the lambda itself, remove it.
2) always do your oidc auth via oidc
3) always do your oidc auth via lambda, removing oidc as a provider
