### ISSUE TITLE
Amplify publish/push no longer working with an imported AppSync API after updating to v7.6.15.

### ISSUE THREAD

**Issue by coe720** [aws-amplify/amplify-cli#9718]
I just updated the Amplify CLI to version 7.6.15 and am no longer to run `amplify push` or `amplify publish` due to the following error: An error occurred during the push operation: Could not find a schema at ~/project/amplify/backend/api/api-name/schema.graphql

I'm using an import AppSync API using `amplify codegen` and never had an API directory at all under the backend folder.

I tried deleting the imported API using `amplify api remove` and re-importing it using codegen to see if the new CLI brought in that directory but still having the same issue.

**Comment by sundersc** [comment]
@coe - Could you open a new issue using the issue template?

**Comment by charlesdarkwind** [comment]
https://github.com/aws-amplify/amplify-cli/issues/9721
