### ISSUE TITLE
Can't init project with Amplify

### ISSUE THREAD

**Issue by edward-hong** [aws-amplify/amplify-cli#972]
Hi I'm trying to initialize a project by running the command `amplify init` but after I make the selections, it comes back with an error:

```
⠧ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
{ OptInRequired: The AWS Access Key Id needs a subscription for the service
    at Request.extractError (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/edward/.config/yarn/global/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The AWS Access Key Id needs a subscription for the service',
  code: 'OptInRequired',
  time: 2019-03-03T21:14:34.638Z,
  requestId: '581c6e4a-3df9-11e9-8269-59b4c2d8d7d2',
  statusCode: 403,
  retryable: false,
  retryDelay: 21.790819558046604 }
```

How do I opt in? I was wondering how do I fix this issue?

**Comment by kaustavghosh06** [comment]
@edward-hong Did you configure your AWS profile using the `amplify configure` command and then use that profile in your init process?

**Comment by UnleashedMind** [comment]
This is usually because your aws account has not been completely verified, or you have not granted proper permission for the IAM user (that the aws access credentials are associated with). 
Set up an user with admin permission and use its credentials with the Amplify CLI, see if it works, you can then use more granular permission control.

**Comment by edward-hong** [comment]
Hi @UnleashedMind thank you for the reply. I have an IAM user with admin access and under the 'Access Advisor' tab, it says I have admin access for AWS Amplify.

Also, I did configure my AWS profile using the `amplify configure` command and used that profile to init. 

I'm currently checking whether my AWS account has been verified. There's no indication when I log in that it hasn't been verified. I've opened up a ticket with AWS support regarding this issue.

**Comment by kaustavghosh06** [comment]
@edward-hong  Please take a look at this - https://github.com/aws-amplify/amplify-cli/issues/191#issuecomment-469682712 to resolve your issue. As @Purvik mentioned, you would need to Call and Verify your account and then try again.

**Comment by edward-hong** [comment]
Yea I've verified my account and have successfully initialised a project. Thank you for the help!

**Comment by codingforsuckers** [comment]
Hi, how does one perform the call is there a number if so which. I'm facing the same issue but don't know how to verify my account. Thanks for any help.

**Comment by arjunkalburgi** [comment]
I'm having this issue, @edward-hong how did you solve it? How do I verify my account?

**Comment by edward-hong** [comment]
@arjunkalburgi I had to contact Amazon support and they were able to verify me through a call instead.

**Comment by guptapuja7** [comment]
while doing amplify init i get this error C02ZM0TFLVCG:researchdata C300738$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project researchdata
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using vue
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script serve
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use amplifynewuser
init failed
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  message: 'read ECONNRESET',
  errno: 'ECONNRESET',
  code: 'NetworkingError',
  syscall: 'read',
  region: 'us-east-1',
  hostname: 'amplify.us-east-1.amazonaws.com',
  retryable: true,
  time: 2020-04-16T21:33:49.517Z
