### ISSUE TITLE
Getting: Missing AmplifyAppId in amplify-meta.json error when trying to "amplify console api"

### ISSUE THREAD

**Issue by spharsh** [aws-amplify/amplify-cli#9723]
I created a new react-app
Modified its schema (its a simple blog app)
did amplify add api followed by amplify push

Now when I am trying to open this api using amplify console api, I am getting this error " Missing AmplifyAppId in amplify-meta.json".

Also, in my account I had created another api(s) and dynamodb table(s) in past, but there is literally nothing in my account! Why did this happened and how can I rectify this situation and the error?

Please provide your suggestions.

Thanks,

**Comment by josefaidt** [comment]
Hey @spharsh :wave: can you share the steps you took to set up the Amplify project?

**Comment by ammarkarachi** [comment]
@spharsh Can you check if you have >= 25 app created on the Amplify Console in your AWS account?

**Comment by spharsh** [comment]
Hi,
so I started with npx create-react-app app-name
amplify init
amplify add api (changed my graphql schema and it compiled successfully)
amplify push

Now when I am doing this amplify console api, I am getting this error.

**Comment by spharsh** [comment]
@ammarkarachi so this is weird too. I am pretty sure I had, if not 25, atleast 20 apps (I am in learning phase) but now there is not a single app!!!
Where did they go?
![image](https://user-images.githubusercontent.com/18090572/153076771-8e468363-d919-45fd-bd01-c0c476a68f70.png)

**Comment by spharsh** [comment]
@ammarkarachi okay my bad, I was in a different region and yes there are exactly 25 apps. Should I just delete useless ones?

**Comment by ammarkarachi** [comment]
Yes, there is an app limit on Amplify Console and it's always good practice to clean up test app so as not to incur any charges.

**Comment by spharsh** [comment]
Okay, I am doing this now, and hopefully, after this, I won't be getting that error.

Thank you so much!

**Comment by ammarkarachi** [comment]
I will close this issue for now let me know if you need any additional help
