### ISSUE TITLE
API CustomResources.json 500 resources per template limit - question about splitting it up using nested stacks

### ISSUE THREAD

**Issue by HKJChen** [aws-amplify/amplify-cli#9729]
**Which Category is your question related to?**
API

**Amplify CLI Version**
7.6.7

**What AWS Services are you utilizing?**
AppSync/GraphQL

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
We have a big GraphQL schema and most of our resolvers are custom/defined in the api/api name/stacks/CustomResource.json template.  We have run up against the 500 resources per cloudformation template limit and so we wanted to split out some of the resources from the CustomResource.json template in separate/smaller templates using Nested stacks.  

Most of our resolvers are pipeline resolvers, and so we define the common pipeline functions in CustomResources.json and pass their function id's to the nested templates as parameters.

We got the nested stack to work, but it seems a little bit kludgy.  We split out some of the functions into a separate stack template in the api/<api name>/stacks folder.  So now, where we used to have 1 stack template (CustomResources.json), we now have 2 stack templates (CustomResources.json and NestedCustomResources.json).  We configured CustomResources to create the NestedCustomResources stack as a nested stack after all of its own resources have been created.  While this seems to work, in addition to creating the NestedCustomResources stack as a nested stack, Amplify attempts to create the NestedCustomResources stack as an independent stack.  We worked around this by adding a condition in the NestedCustomResources stack so that it only creates resources when a flag is set, and that flag is passed as a parameter from CustomResources when it is created as a nested stack.  So even though the NestedCustomResource stack runs twice, it only creates/updates resources when it runs as a nested stack.  When we browse the stacks for our project/environment, we find 2 instances of the NestedCustomResources stack, one with 0 resources and one with all of the expected resources.  

Is this an acceptable implementation?  Or might we run into issues with this?  
Is there a way to put the nested cloudformation template (NestedCustomeResources.json) into another folder under our amplify project folder structure so that it will be uploaded to the S3 deployment bucket by amplify, but it won't be invoked/run/installed as an independent stack?

Note that we aren't able/willing(?) to divide up the api into smaller micro services at this point in our project.

**Comment by josefaidt** [comment]
Hey @HKJChen :wave: apologies for the delay here but thank you for raising this! This has [since been solved](https://github.com/aws-amplify/amplify-cli/issues/9762#issuecomment-1116445920) as of Amplify CLI v8.1.0. Please upgrade the CLI and push an update to the API
