### ISSUE TITLE
amplify configure missing ca-central-1

### ISSUE THREAD

**Issue by shlfung** [aws-amplify/amplify-cli#9740]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14

### Amplify CLI Version

1.8.5

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

configure

### Describe the bug

Missing ca-central-1 option when selecting "Specify the AWS Region"

### Expected behavior

ca-central-1 should be an option

### Reproduction steps

aws configure
after logging into aws console
press enter to continue

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ammarkarachi** [comment]
Hi, it looks like I see the options on running `amplify configure`

![image](https://user-images.githubusercontent.com/56042290/153508591-8bff4420-b4a3-4bf7-82bc-2bf2dbe0797f.png)

**Comment by cjihrig** [comment]
If you're running version 1.8.5 of the CLI, that could be why. Can you try upgrading to a newer version. Today, the latest version is 7.6.19, which is significantly different from 1.8.5.
