### ISSUE TITLE
Stack update failed after adding IAM as additional authorization type

### ISSUE THREAD

**Issue by nikname** [aws-amplify/amplify-cli#9746]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

7.6.19

### What operating system are you using?

Windows 10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

push, update

### Describe the bug

I have created a new Amplify project with `amplify init`, imported an existing Cognito User Pool with `amplify import auth` and created a GraphQL API with `amplify add api`. After doing this steps I have run `amplify push` and the stack creation completed as espected.
I would have an additional IAM authorization mode so I have run amplify update api and selected the previous Cognito User Pool as the primary mode and then IAM as an additional mode. When I run amplify push the update fail with the following error

> Parameters: [unauthRoleName] must have values 

After ispecting _#current-cloud-backend/awscloudformation/build/root-cloudformation-stack.json_ I have notice that only `authRoleName` is passed as a param to the API nested stack while `unauthRoleName` is missing

### Expected behavior

The param `unauthRoleName` is passed to the API nested stack

### Reproduction steps

1. `amplify init`
2. `amplify import auth`
3. Select existing Cognito User Pool
4. `amplify add api`
5. `amplify push`
6. `amplify update auth`
7. Select IAM as additional authorization mode
8. `amplify push`

### GraphQL schema(s)

<details>

```graphql
type Message @model(mutations: null) @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  fromId: String!
  userId: String @index(name: "byUser")
  message: String
}
```

</details>

### Log output

<details>

```
UPDATE_IN_PROGRESS          chatapi                 AWS::CloudFormation::Stack Fri Feb 11 2022 12:03:59 GMT+0100 (Central European Standard Time)

UPDATE_FAILED               chatapi                 AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:00 GMT+0100 (Central European Standard Time) Parameters: [unauthRoleName] must have values   

UPDATE_ROLLBACK_IN_PROGRESS amplify-chatapi-dev     AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:01 GMT+0100 (Central European Standard Time) The following resource(s) failed to update: [chatapi].
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                              chatapi                 AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:12 GMT+0100 (Central European Standard Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-chatapi-dev AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:13 GMT+0100 (Central European Standard Time)
UPDATE_COMPLETE                              chatapi                 AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:14 GMT+0100 (Central European Standard Time)
UPDATE_ROLLBACK_COMPLETE                     amplify-chatapi-dev AWS::CloudFormation::Stack Fri Feb 11 2022 12:04:14 GMT+0100 (Central European Standard Time)
⠙ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Resource is not in the state stackUpdateComplete

```

</details>

**Comment by josefaidt** [comment]
Hey @nikname :wave: I was able to reproduce this when importing auth and selecting the user pool only. Can you try reimporting and selecting "Cognito User Pool and Identity Pool" to mitigate this issue? https://docs.amplify.aws/cli/auth/import/#import-an-existing-identity-pool

**Comment by nikname** [comment]
I confirm by selecting "Cognito User Pool and Identity Pool" it works!

**Comment by nikname** [comment]
Hi @ammarkarachi, please note that my issue is resolved now but for me this remains a bug (missing parameter in the generated CloudFormation template)
