### ISSUE TITLE
Prevent `$ amplify push` without updating API, Auth, Storage category resources in v6 to v7 migration 

### ISSUE THREAD

**Issue by jaga810** [aws-amplify/amplify-cli#9750]
### Is this feature request related to a new or existing Amplify category?

auth

### Is this related to another service?

storage, api

### Describe the feature you'd like to request

Prevent `$ amplify push` without updating API, Auth, Storage category resources in v6 to v7 migration.

Your settings with parameters.json can be destroyed, if you `$ amplify push` without `$ amplify update ${category}` in v6 to v7 migration.
parameters.json file is deprecated and has been replaced by cli-inputs.json after Amplify CLI v7.
Amplify CLI v7 seems to try `$ amplify push` ignoring parameters.json file in the amplify project created by v6 or prior.

### Describe the solution you'd like

Both or one of below.
- Show migration prompt for the resources override feature enabled (GraphQL API, storage, auth) like `A  migration is needed to support latest updates on auth resources.` when users try  `$ amplify push` or `$ amplify status`
- Deploy  referencing parameters.json instead of cli-inputs.json if `amplify update ${category}` has not run.

### Describe alternatives you've considered

N/A

### Additional context

Reproduction steps of the problem.

1. `npm i -g @aws-amplify/cli@6.4.0`
2. `amplify init -y` with default settings
3. `amplify add auth` with adding some lambda triggers
4. `amplify push -y`
5. `amplify auth console` and choose `Userpools`. Then confirm that lambda triggers are __associated__ to the userpool.
6. `npm i  -g @aws-amplify/cli@7.6.19`
7. `amplify status` shows no change here.
8. `amplify add api` with default settings. CLI shows no warnings about auth resource.
9. `amplify push -y` and confirm `amplify/backend/auth/` files remain nothing different before updating Amplify CLI v7.
10. `amplify auth console` and choose `Userpools`. Then confirm that lambda triggers are __not associated__ to the userpool.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by enishenish** [comment]
This notification feature is really important for older version users!
I experienced the loss of the production environment's auth trigger settings in this context.
This feature is very good to prevent such trouble.

**Comment by ykethan** [comment]
Tested the provided reproduction steps in Amplify CLI V10.0.0 when migrating from CLI v6.4.0, `amplify push` removes Cognito auth triggers.

**Comment by josefaidt** [comment]
Note for fix: block `amplify push` after migrating from CLI <7 to CLI >7, prompt for resource migration
