### ISSUE TITLE
After running the 'npm install -g @aws-amplify/cli' command, I get back a message stating the number of vulnerabilities instead of an execution. I have npm, git and node.js all updated and can not resolve this issue. Any suggestions?

### ISSUE THREAD

**Issue by clevelanda1** [aws-amplify/amplify-cli#9753]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

16.14.0

### Amplify CLI Version

Not running

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

Not applicable

### Amplify Commands

configure project

### Describe the bug

Already stated.

### Expected behavior

Na

### Reproduction steps

Na

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

N/a

**Comment by yuth** [comment]
@clevelanda1 these are coming from transitive dependencies of Amplify CLI. We are actively working on updating our dependencies when we see serious vulnerabilities in our direct dependencies. Also keep in mind, Amplify CLI is a build tool which is only during deployment. So most of these vulnerabilities might be false positives.

**Comment by josefaidt** [comment]
Closed as this is now obsolete
