### ISSUE TITLE
Modify default authorization from IAM to Cognito User Pool authorizer when creating API from Amplify CLI.

### ISSUE THREAD

**Issue by Revanth97** [aws-amplify/amplify-cli#9754]
**Which Category is your question related to?**
API

**Amplify CLI Version**
```
amplify -v
6.3.1
```

**What AWS Services are you utilizing?**
AWS API Gateway

**Provide additional details**

`amplify add api` creates a new API with specified properties, but the **default authorization is set to IAM** which is fine. I have a cognito user pool in AWS and I want my API to be setup with this **cognito user pool authorization** by default. Is it possible?

Right now, whenever an API gateway is created, I go to that API gateway, create a **new authorizer** and select the **cognito pool authorizer** and then specify the **Token Source as Authorization**. Finally, I go to **Resources** in the API selected and update the Authorization to the newly created Cognito User Pool Authorizer.

Is there any way to specify this with Amplify CLI ? I've checked the documentation, and the best I was able to find is that I can only import a cognito user pool auth. Not sure how I can specify this as my API Gateway default authorizer. Could someone please guide me through any documentation that would help in this usecase?

Thank you!!

**Comment by josefaidt** [comment]
Hey @Revanth97 :wave: thanks for raising this! Unfortunately this is not currently supported and is documented as a feature request in #2679 and https://github.com/aws-amplify/amplify-cli/issues/3390. Please subscribe or add feedback to one of the feature requests linked. I'll close this issue in favor of tracking the existing feature requests
