### ISSUE TITLE
CLI Deployment error message with link to troubleshooting guide should be improved

### ISSUE THREAD

**Issue by Straubulous** [aws-amplify/amplify-cli#9766]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

7.6.19

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

A new error message (for push failure) was implemented in CLI Version 7.6.19 that provides a link to the new troubleshooting guide.  The text in that message has grammar issues and could be more clear:

An error occurred when pushing the resource to the cloud
🛑 An error occurred during the push operation: Resource is not in the state stackUpdateComplete
⚠️ Please refer Amplify CLI troubleshooting guide at: https://docs.amplify.aws/cli/project/troubleshooting/

### Expected behavior

The error message should read:

🛑 An error occurred during the deployment. The following resources failed:
Resource Name: GraphQLAPI (AWS::AppSync::GraphQLApi)
Event Type: create
Reason: The service limit for number of GraphQL APIs has been reached. (Service: AWSAppSync; Status Code: 400; Error Code: ApiLimitExceededException; Request ID: 180acaf7-63c4-401d-be02-4b32ca821e98; Proxy: null)

⚠️ Review the Amplify CLI troubleshooting guide for potential next steps: https://docs.amplify.aws/cli/project/troubleshooting/

### Reproduction steps

do any action which causes the push to fail

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ENT108** [comment]
Same there... error output if lacking debug data!

**Comment by johnpc** [comment]
Closing this ticket as the associated PR has been released
