### ISSUE TITLE
Possible to make `id` field required so that it's not automatically generated on create operations (and the operation fails)?

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-cli#977]
**Is your feature request related to a problem? Please describe.**
I want to ensure we do not create "duplicate" records that differ only by the id hash key. I know that the Amplify team will be releasing a RFC sometime soon about (a) new directive(s) to enforce partition key selection, but in the meantime, is it possible to make the hash key required on create operations without overriding resolvers?

**Comment by kaustavghosh06** [comment]
We released the @key directive for this use-case. Please take a look at the docs out here - https://aws-amplify.github.io/docs/cli-toolchain/graphql#key
