### ISSUE TITLE
'ElasticSearchInstanceType' must be one of AllowedValues

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-cli#9775]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.20

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When trying to push API changes, I get the following error:

`UPDATE_FAILED apipropswap AWS::CloudFormation::Stack Tue Feb 15 2022 20:24:26 GMT-0500 (Eastern Standard Time) Parameter 'ElasticSearchInstanceType' must be one of AllowedValues`

We are setting the instance type in team-provider-info.json and haven't changed the value in over a month (t3.medium.search)

In fact, we even purchased a reserved instance for the t3.medium.search

![Screen Shot 2022-02-15 at 8 37 17 PM](https://user-images.githubusercontent.com/292923/154179658-07057de9-990e-4c96-816e-c3aece6142cc.png)
 
To be clear, the changes we are trying to push have NOTHING to do with the search instance. We just added a field to a data model.

### Expected behavior

Amplify allows me to deploy

### Reproduction steps

1. try to push amplify
2. See error

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by CodySwannGT** [comment]
Thanks for your quick attention on this. I should mention we are unable to deploy our production app until we get resolution on this!

**Comment by CodySwannGT** [comment]
Anything on this? We're completely blocked on a production app.

**Comment by sundersc** [comment]
@CodySwannGT - Can you please provide the below details?
- What is the GraphQL transformer version? (`amplify status` prints out this information)
- Which AWS region the app is deployed?

**Comment by CodySwannGT** [comment]
Thanks @sundersc 

1. GraphQL transformer version: 1
2. us-east-1

**Comment by sundersc** [comment]
@CodySwannGT Below are the allowed values I see in the CFN template for v1 searchable. Could you try this in Dev or new test environment? I'm trying to understand how `t3.medium.search` was accepted in the previous push.

```
't2.small.elasticsearch',
't2.medium.elasticsearch',
'c4.large.elasticsearch',
'c4.xlarge.elasticsearch',
'c4.2xlarge.elasticsearch',
'c4.4xlarge.elasticsearch',
'c4.8xlarge.elasticsearch',
'm3.medium.elasticsearch',
'm3.large.elasticsearch',
'm3.xlarge.elasticsearch',
'm3.2xlarge.elasticsearch',
'm4.large.elasticsearch',
'm4.xlarge.elasticsearch',
'm4.2xlarge.elasticsearch',
'm4.4xlarge.elasticsearch',
'm4.10xlarge.elasticsearch',
'r3.large.elasticsearch',
'r3.xlarge.elasticsearch',
'r3.2xlarge.elasticsearch',
'r3.4xlarge.elasticsearch',
'r3.8xlarge.elasticsearch',
'r4.large.elasticsearch',
'r4.xlarge.elasticsearch',
'r4.2xlarge.elasticsearch',
'r4.4xlarge.elasticsearch',
'r4.8xlarge.elasticsearch',
'r4.16xlarge.elasticsearch',
'i2.xlarge.elasticsearch',
'i2.2xlarge.elasticsearch',
'i3.large.elasticsearch',
'i3.xlarge.elasticsearch',
'i3.2xlarge.elasticsearch',
'i3.4xlarge.elasticsearch',
'i3.8xlarge.elasticsearch',
'i3.16xlarge.elasticsearch',
'r6gd.12xlarge.elasticsearch',
'ultrawarm1.xlarge.elasticsearch',
'm5.4xlarge.elasticsearch',
't3.xlarge.elasticsearch',
'm6g.xlarge.elasticsearch',
'm6g.12xlarge.elasticsearch',
't2.micro.elasticsearch',
'r6gd.16xlarge.elasticsearch',
'd2.2xlarge.elasticsearch',
't3.micro.elasticsearch',
'm5.large.elasticsearch',
'd2.4xlarge.elasticsearch',
't3.small.elasticsearch',
'c5.2xlarge.elasticsearch',
'c6g.2xlarge.elasticsearch',
'd2.8xlarge.elasticsearch',
'c5.4xlarge.elasticsearch',
't4g.medium.elasticsearch',
'c6g.4xlarge.elasticsearch',
'c6g.xlarge.elasticsearch',
'c6g.12xlarge.elasticsearch'
```

**Comment by CodySwannGT** [comment]
@CodySwannGT - yes. Those values all work in the other environments where we have never before modified the default search instance.

However, I don't believe they will work in production where we have been migrated to OpenSearch and I am weary of trying it out on production for fear of getting stuck in a bad state.

**Comment by sundersc** [comment]
@CodySwannGT - How did you migrate your v1 searchable instance to OpenSearch? If it was done outside the CLI, then it will be replaced on the next push when CLI detects a change to API.

You can set the instance type to t3.medium.search equivalent and take a snapshot of data and restore after the push completes. Also, consider migrating to transformer v2 as this uses opensearch by default.

https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html

**Comment by CodySwannGT** [comment]
@sundersc thanks for the reply - To be honest, it was a while ago we migrated the search instance to opensearch and we didn't do anything special. If I recall correctly, we went to purchase a reserved elastic search medium instance and were told it had to be opensearch, so we changed the config in amplify, deployed and then purchased the reserved instance.

Is transformer v2 production ready? I've been trying to follow along and can't tell for sure.

**Comment by sundersc** [comment]
> Are there any possible unwanted scenarios here?

This shouldn't affect the `amplify push`. I would recommend to try this out in a non-prod environment.

> Is transformer v2 production ready?

Yes, it is. Please refer to this doc for more information on migration.
https://docs.amplify.aws/cli/migration/transformer-migration/

Regarding the instance types, we will include the new instance types to the allowed list.

**Comment by CodySwannGT** [comment]
@sundersc I think that's the problem. How can I get a non-prod environment in the same state that our production environment is in?

**Comment by CodySwannGT** [comment]
@sundersc thanks for opening this pull request! Any ETA i can pass along to the team on our end?

**Comment by CodySwannGT** [comment]
@sundersc is this in the latest version or is it pending a release?

**Comment by sundersc** [comment]
Hi @CodySwannGT - This is not released yet. It should be available in the next release.

**Comment by CodySwannGT** [comment]
Well..... the wrong instance types were added. We're now getting this:

````
UPDATE_FAILED               ElasticSearchDomain                                                                AWS::Elasticsearch::Domain Wed Mar 09 2022 20:53:20 GMT-0500 (Eastern Standard Time) 1 validation error detected: Value 't3.medium.search' at 'elasticsearchClusterConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [r6gd.12xlarge.elasticsearch, i3.2xlarge.elasticsearch, ultrawarm1.xlarge.elasticsearch, m5.4xlarge.elasticsearch, t3.xlarge.elasticsearch, m6g.xlarge.elasticsearch, i3.4xlarge.elasticsearch, m3.large.elasticsearch, m6g.12xlarge.elasticsearch, r4.16xlarge.elasticsearch, t2.micro.elasticsearch, m4.large.elasticsearch, r6gd.16xlarge.elasticsearch, d2.2xlarge.elasticsearch, t3.micro.elasticsearch, m5.large.elasticsearch, i3.8xlarge.elasticsearch, i3.large.elasticsearch, d2.4xlarge.elasticsearch, t2.small.elasticsearch, c4.2xlarge.elasticsearch, t3.small.elasticsearch, c5.2xlarge.elasticsearch, c4.4xlarge.elasticsearch, c6g.2xlarge.elasticsearch, d2.8xlarge.elasticsearch, c5.4xlarge.elasticsearch, t4g.medium.elasticsearch, c6g.4xlarge.elasticsearch, c6g.xlarge.elasticsearch, m3.medium.elasticsearch, c6g.12xlarge.elasticsearch, c4.8xlarge.elasticsearch, c4.large.elasticsearch, c5.xlarge.elasticsearch, c5.large.elasticsearch, t4g.small.elasticsearch, c4.xlarge.elasticsearch, c5.9xlarge.elasticsearch, c6g.8xlarge.elasticsearch, c6g.large.elasticsearch, d2.xlarge.elasticsearch, ultrawarm1.medium.elasticsearch, t3.nano.elasticsearch, t3.medium.elasticsearch, m6g.2xlarge.elasticsearch, t2.medium.elasticsearch, t3.2xlarge.elasticsearch, c5.18xlarge.elasticsearch, m6g.4xlarge.elasticsearch, i3.xlarge.elasticsearch, r6gd.2xlarge.elasticsearch, i2.xlarge.elasticsearch, r3.2xlarge.elasticsearch, r4.2xlarge.elasticsearch, m5.xlarge.elasticsearch, m4.10xlarge.elasticsearch, r6gd.4xlarge.elasticsearch, r6g.2xlarge.elasticsearch, r3.4xlarge.elasticsearch, r5.2xlarge.elasticsearch, m5.12xlarge.elasticsearch, m4.xlarge.elasticsearch, m6g.8xlarge.elasticsearch, m6g.large.elasticsearch, r4.4xlarge.elasticsearch, m5.24xlarge.elasticsearch, m3.xlarge.elasticsearch, r6g.4xlarge.elasticsearch, i3.16xlarge.elasticsearch, t3.large.elasticsearch, r5.4xlarge.elasticsearch, ultrawarm1.large.elasticsearch, m3.2xlarge.elasticsearch, r6gd.8xlarge.elasticsearch, r6gd.large.elasticsearch, r6g.xlarge.elasticsearch, r3.8xlarge.elasticsearch, r3.large.elasticsearch, r5.xlarge.elasticsearch, m4.2xlarge.elasticsearch, r6g.12xlarge.elasticsearch, r4.8xlarge.elasticsearch, r4.xlarge.elasticsearch, r4.large.elasticsearch, r5.12xlarge.elasticsearch, m5.2xlarge.elasticsearch, r6gd.xlarge.elasticsearch, r6g.8xlarge.elasticsearch, r6g.large.elasticsearch, i2.2xlarge.elasticsearch, r3.xlarge.elasticsearch, r5.24xlarge.elasticsearch, r5.large.elasticsearch, m4.4xlarge.elasticsearch] (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 5100b43a-0a12-4fc7-b4fc-c06d982da58a; Proxy: null)````
