### ISSUE TITLE
Cannot remove environment when checked out in another one not in the same region

### ISSUE THREAD

**Issue by cptflammin** [aws-amplify/amplify-cli#978]
Hi there !
   When checked out in an environment by example in region eu-central-1, I cannot remove another one in another region. I get an error like this:

Stack with id xxxyyyyzzz-5132437 does not exist

In same region removing one from another one is ok

**Comment by UnleashedMind** [comment]
Hi, @cptflammin 
No, you can not remove stack from another region.

**Comment by cptflammin** [comment]
@UnleashedMind @kaustavghosh06 When creating a new environment, we should be able to specifically set a region (top of my mind, that's possible or I miss something). Typically we will be in two weeks' time in the building aside yours in Seattle, I will set an environment that's based in us-west rather than eu-central currently

**Comment by kaustavghosh06** [comment]
@cptflammin This is a bug and @yuth is working on a fix for the same. I'll update this thread once we have the release out.

**Comment by johnford2002** [comment]
I believe this fix breaks config functionality when configLevel is set to 'general' instead of 'project'.

https://github.com/aws-amplify/amplify-cli/blame/master/packages/amplify-provider-awscloudformation/lib/configuration-manager.js#L506

There is no config return in the event configLevel is set to something other than 'project'.

**Comment by yuth** [comment]
@johnford2002 https://github.com/aws-amplify/amplify-cli/commit/426acbf121e1d6ba5e62f15dc1c295c6b7c79fa9 should fix the general config level. This change was released in @aws-amplify/cli@1.7.1. Please comment if the issue still persists.
