### ISSUE TITLE
Cannot pull backend environment from the cloud

### ISSUE THREAD

**Issue by khacminh** [aws-amplify/amplify-cli#9789]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.6.20

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

I cannot pull the backend environment from the cloud. 

I ran the command:

```sh
amplify pull --appId myappid --envName an-existed-env
```

and the following error occurs

```log
✔ Successfully pulled backend environment alpha from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
Cannot read properties of undefined (reading 'Id')
TypeError: Cannot read properties of undefined (reading 'Id')
at constructPinpointNotificationsMeta (/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications/lib/multi-env-manager.js:42:39
```

I can pull other environments but got error with this environment

### Expected behavior

The backend environment can be pulled from the cloud

### Reproduction steps

```sh
amplify pull --appId myappid --envName an-existed-env
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @khacminh :wave: how was this environment initially created?

**Comment by khacminh** [comment]
Hi @josefaidt 

The amplify app was created about 1 year ago from the AWS console. Then, the environment was created by amplify cli

**Comment by josefaidt** [comment]
Hey @khacminh thank you for clarifying! Based on the error above it appears notifications are added to this project. Is this an existing project you have initialized locally and you're wanting to pull down env's from the cloud that are not already available locally?

**Comment by khacminh** [comment]
hi @josefaidt 

The environments was created locally. But I cannot checkout to that env. So I have to pull it again from the cloud

**Comment by josefaidt** [comment]
Hey @khacminh :wave: apologies for the delay here! Are you still experiencing this issue? How was the notification resource added to the project?

**Comment by khacminh** [comment]
Hi @josefaidt 

The notification resource was added by using CLI `amplify notification add`

**Comment by josefaidt** [comment]
Hey @khacminh thanks for clarifying. I have a few follow-up questions:

- what notification type are we using? (FCM, SMS, Email, etc)
- are we attempting to pull the project into a fresh directory?
- can you clarify whether your notification resource has an associated `Id` property in your `amplify/backend/backend-config.json` file?

```json
"notifications": {
        "Pinpoint": {
          "Name": "mynotification-dev",
          "Id": "7541b10f34d3473aa39c82f586520a1c",
          "Region": "us-east-1"
        }
      }
```

**Comment by josefaidt** [comment]
Hey @khacminh :wave: are you still experiencing this issue?

**Comment by khacminh** [comment]
Hi @josefaidt 

The problem is still there. The notification is enabled with:

- FCM and APNS
- I pulled to the new directory & the old one
- In the `backend-config.json`, the notification resource has **no** associated Id property

**Comment by josefaidt** [comment]
Hey @khacminh thank you for clarifying! It appears perhaps there was some issue during the creation of this resource where the `Id` property was not populated in our `backend-config.json`. As a workaround, can you try to copy the pinpoint project ID from the console and manually populate this field, then push? By doing so this should update the contents of this configuration and enable us to then pull the project into a new directory.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/5033303/166608599-39cb3fdc-006d-4430-95c4-aeb7dcaaaa8c.png">

**Comment by khacminh** [comment]
Hi @josefaidt 

I see that this configuration is in `team-provider-info.json` not in `backend-config.json`.

**Comment by khacminh** [comment]
@josefaidt 

After a lot of pain, I think it was the problem with pinpoint region configuration in `pinpoint-cloudformation-template.json`

![image](https://user-images.githubusercontent.com/13713865/166884275-3ec8e512-b7e3-4685-bd6d-f148f7a1d973.png)

**Comment by josefaidt** [comment]
Hey @khacminh ah that's interesting, is the pinpoint application deployed in a different region?

**Comment by khacminh** [comment]
@josefaidt 

The pinpoint app was deployed in `eu-west-2`. So I have to update the file `pinpoint-cloudformation-template.json` manually, then publish to amplify

**Comment by josefaidt** [comment]
Hey @khacminh thank you for the clarification. Is that region the same as the Amplify app itself? And to clarify further it appears you are unblocked after manually updating that template file?

**Comment by khacminh** [comment]
@josefaidt 

- The amplify app was deployed in `eu-west-2`, the same as the pinpoint application
- I had to update the configuration file manually and it fixed the problem

**Comment by josefaidt** [comment]
Hey @khacminh thank you for clarifying! And I'm glad to hear you're back up and running. While we have not received other, similar reports of this issue I'm curious what the value is for the [pinpoint region support feature flag](https://docs.amplify.aws/cli/reference/feature-flags/#pinpoint), found in your `amplify/cli.json` file

**Comment by khacminh** [comment]
@josefaidt

Here is my `cli.json` file, there is no pinpoint region in it

```json
{
  "features": {
    "graphqltransformer": {
      "enableiterativegsiupdates": true,
      "securityEnhancementNotification": false,
      "showfieldauthnotification": false
    },
    "project": {
      "overrides": true
    }
  }
}
```

**Comment by josefaidt** [comment]
Hey @khacminh to clarify, is this the entire file contents of this file? If so, can you confirm whether the `cli.json` file in your deployment bucket's `#current-cloud-backend.zip` has this information?

**Comment by khacminh** [comment]
Hi @josefaidt 

This is the entire file contents. Checking the `cli.json` file from `#current-cloud-backend.zip`, it has the same content.

**Comment by josefaidt** [comment]
Hey @khacminh apologies for the delay here! Given the age of the project most of the newer feature flags are likely disabled, however we have a [reference doc](https://docs.amplify.aws/cli/reference/feature-flags/) that can be used to opt-in to the newer features like the Pinpoint region support flag noted above.

> The project was created about 2 years ago. I think there is an incompatible problem with old applications. Now I cannot clone a new environment with amplify cli. I also tried with aws-cli:

What issue are you running into when creating the new environment from the CLI? e.g. `amplify env add mynewenv`

**Comment by josefaidt** [comment]
Hey @khacminh just wanted to follow-up on this issue. Please file the environment creation issue as a [separate bug report](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml), however in the mean time I will close this issue as "not reproducible". If you experience this issue again please reply back to this thread and we can re-open to investigate further

**Comment by khacminh** [comment]
hi @josefaidt 

I had to fix the issue myself by updating my resources and configuration from local and push it back to amplify.
