### ISSUE TITLE
DataStore-Update/Mutation

### ISSUE THREAD

**Issue by webappjeff** [aws-amplify/amplify-cli#9794]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)
Hey guys, Please Keep in mind this is my first time doing this, so please take it easy on me. I am just looking for some help here. I have a streaming app for which I need to store analytics/streaming data. I would like to update the streams and likes count directly in the data to show it on the front end. I am sure this can be done however, I am just not sure how to go about it.

I am using react-native.
To start, I have been using Amplify Analytics Pinpoint but I just found out the data is basically lost after 90 days. A big problem for me, because I would like to keep the data permanently. 

Here's an example of what I would like to do below:
Say I have Artist John who has 10 Songs and 5 Videos on my platform. Anytime a user plays any of John's content (songs, videos) I want to update John's stream count by the number of plays. Also, I want to upload the data (Plays and Likes) for the video and likes. 

So I simply need to update the data via the schema each time there is an interaction on the front end. Below I list Examples of my Schemas and what I need to update:
```gql
type Artist @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  imageUri: String!
  Bio: String!
  Follow: Int!
  _**Streams: Int!**_ (need to update)
  albums: [Album] @connection(keyName: "byArtist", fields: ["id"])
}

type Song @model @key(name: "byAlbum", fields: ["albumID"]) @auth(rules: [{allow: private}]) {
  id: ID!
  songName: String!
  songArtist: String!
  songAlbum: String!
  albumSequence: Int
  imageUri: String!
  mp3Uri: String!
  category: String
  genre: String
  year: Int
  era: String
  **_streams: Int_** (need to update)
  duration: String
  **_likes: Int_**  (need to update)
  AgeVersion: String!
  rights: String
  priority: Int
  albumID: ID
  album: Album @connection(fields: ["albumID"])
}

type Videos @model @auth(rules: [{allow: private}]) {
  id: ID!
  videoName: String!
  videoArtist: String!
  videoAlbum: String
  description: String
  imageUri: String!
  mp4Uri: String!
  category: String
  genre: String
  year: Int
  era: String
  **_views: Int_** (need to update)
  duration: String
  **_likes: Int_** (need to update)
  AgeVersion: String!
  priority: Int
  Comments: [Comment] @connection(keyName: "byVideos", fields: ["id"])
}

```

I have been learning about mutations but I can't grasp the idea still. Can you guys please point me in the right direction? My app is growing and I need to have this working properly ASAP.

**Which Category is your question related to?**
Amplify DataStore Mutation

**Amplify CLI Version**
7.6.20

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
Amplify Auth, Analytics, DataStore, GraphQL

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

**Comment by josefaidt** [comment]
Hey @webappjeff :wave: it appears the appropriate solution for this simple mutation is to create a custom resolver. Can you see if the comment here https://github.com/aws-amplify/amplify-cli/issues/3681#issuecomment-629233301 sheds some insight?

**Comment by josefaidt** [comment]
Hey @webappjeff apologies for the delay here. While there is a `updatedAt` field we can query, this would be a great question to ask in our [community Discord server](https://discord.gg/invite/amplify) for assistance with custom resolvers.
