### ISSUE TITLE
Wrong bucket name passed to lambda env variable on mock server (NoSuchBucket)

### ISSUE THREAD

**Issue by rafaelfaria** [aws-amplify/amplify-cli#9814]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.0

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

storage, api

### Amplify Commands

Not applicable

### Describe the bug

After creating a function, and adding `Resource access permissions to access the storage i have, I would expect the bucket to be accessible through the `STORAGE_{STORAGE}_BUCKETNAME` variable in `process.env`.

However, I get mixed results. If my variable is STORAGE_RAFAELBUCKET_BUCKETNAME for instance, on some occasions I would get "storageRafaelbucketBucketname" or i would get the bucket name without the "identification" that suffix it.

Ex: bucket name = myapp_media, then i am getting `myapp_media-dev` instead `myapp_media1234-dev` as it is the name of my bucket in the cloud.

So when I run my lambda function, I am getting `NoSuchBucket: The specified bucket does not exist`

### Expected behavior

Even though I know the mock only simulates it, I would expect that whatever value comes from the environment variable, would match the bucket mock is using.

### Reproduction steps

I am not sure how exactly I can reproduce that since it never really worked. but here the steps I took.

1. Add storage, create an s3 bucket
2. Add a lambda function 
3. add resources to it, and add access to the bucket we created in the storage
4. create a function inside the lambda to either save or read a file from the bucket.
5. Always get the message `NoSuchBucket: The specified bucket does not exist`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>
Nothing comes in the log.
</details>

**Comment by ykethan** [comment]
Hello @rafaelfaria, apologies for the delay in a response. I utilized the following steps in my replication.

1. add storage.
2. add function, under advanced settings allow storage access permissions.
3. add S3 putObject code to function with `process.env.STORAGE_<config name>_BUCKETNAME` to access s3 bucket name.

on performing a `amplify mock function` I was able to upload the file to the s3 bucket and print the `process.env.STORAGE_<config name>_BUCKETNAME`, but did not experience the change in a bucket name.

could you please check the `backend-config.json` attributes for function to see if the `BucketName` has been added.

**Comment by ykethan** [comment]
hello @rafaelfaria , just wanted to follow up on this and see if you are experiencing any continued issues.

**Comment by ykethan** [comment]
closing the issue due to inactivity
