### ISSUE TITLE
API (GraphQL with DynamoDB): Query use GSI with 3 attributes is not working 

### ISSUE THREAD

**Issue by sondt1610** [aws-amplify/amplify-cli#9822]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

14.19.0

### Amplify CLI Version

7.6.8

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Add GSI using AWS CLI

### Amplify Categories

api

### Amplify Commands

codegen, push

### Describe the bug

- Query with gsi (3 attributes is wrong). Can not query field  "is_premium_string" is equal to "true" and field "video_time" is less than 10.
- Only can query field "is_premium_string" is less than "true" and "video_time" is less than 10 
![image](https://user-images.githubusercontent.com/33110100/155058170-27379cc4-ad81-4f44-a4ad-1a4e338ccf6f.png)

### Expected behavior

I want to query Dynamo DB with field  "is_premium_string" is equal to "true" and field "video_time" is less than 10  when use GSI with 3 attributes

### Reproduction steps

1. I create gsi with 3 attributes
  @key(name: "ByVideoByPremium", fields: ["video_id", "is_premium_string", "video_time"], queryField: "getMessByVideoByPremium")
2.  I want to query Dynamo DB with field  "is_premium_string" is equal to "true" and field "video_time" is less than 10 but query getMessByVideoByPremium only use field "is_premium_string" is less than "true" and "video_time" is less than 10 
![image](https://user-images.githubusercontent.com/33110100/155057041-aa6251c1-e189-4a68-888c-5e589d0f1272.png)
3. Due to composite keys "is_premium_string" and "video_time" => create new field: "is_premium_string#video_time" => can not query 1 field equal and 1 field is less than => query wrong
![image](https://user-images.githubusercontent.com/33110100/155057587-23f95dcd-da68-4eac-b46a-32be1b49b633.png)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Message
  @model
  @key(name: "ByVideoByPremium", fields: ["video_id", "is_premium_string", "video_time"], queryField: "getMessByVideoByPremium") {
  id: ID!
  text: String!
  video_id: String!
  video_time: Int!
  is_premium: Boolean
  is_premium_string: Boolean
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sundersc** [comment]
This looks very similar to the scenario here https://github.com/aws-amplify/amplify-cli/issues/8204#issuecomment-923531983.

@sondt1610 - `@searchable` directive is a better option to run queries like these.
https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/

**Comment by sondt1610** [comment]
thank @sundersc, i used @searchable and successfully
