### ISSUE TITLE
graphql-auth-transformer opensearch - Auth only works on dynamic group list when keyword is appended

### ISSUE THREAD

**Issue by Gphill93** [aws-amplify/amplify-cli#9823]
I'm working on an app that added dynamic auth groups to the schema that is also using `@Searchable`.  It was noticed that the dynamic grouping was not working, as search queries were not returning records that belonged to dynamic groups as expected.  After looking into the generated search auth resolver I noticed that `keyword` was not appended for list dynamic auth fields.  After adding `keyword` to the list auth fields the search worked as expected.

To me, this seems like a bug with the resolver generation but I want to first confirm with you all if that's the case.  Is there something different we should be doing for dynamic group-based auth for search?

Here is the code that excludes `.keyword`.  Happy to submit a PR if this should be added.
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-auth-transformer/src/resolvers/search.ts#L164

**Comment by sundersc** [comment]
`.keyword` is not applicable on all the fields. This issue needs to be analyzed in much more detail.

Would you mind opening a new issue using the template? Please include the GraphQL schema.

**Comment by Gphill93** [comment]
Ok will do, thanks
