### ISSUE TITLE
`S3 Error Code: NoSuchKey` when creating a custom Transformer with a `lambda.Function`

### ISSUE THREAD

**Issue by multimeric** [aws-amplify/amplify-cli#9826]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

7.6.21

### What operating system are you using?

Ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When you write a custom transformer, and that transformer creates a lambda function using `lambda.Function()`, it fails with the above error.

### Expected behavior

The lambda function should be added to the API stack.

### Reproduction steps

1. Create a TS file with this content: 
```typescript
export default class CountTransformer extends TransformerPluginBase implements TransformerPluginProvider {
    constructor() {
        super("foo", "directive @foo on OBJECT");
    }

    transformSchema = (ctx: TransformerTransformSchemaStepContextProvider) => {
     generateResolvers = (ctx: TransformerContextProvider) => {
        const stack: TransformerNestedStack = ctx.stackManager.createStack("countResolverStack") as TransformerNestedStack;
        stack.setParameter(ResourceConstants.PARAMETERS.S3DeploymentBucket, Fn.ref(ResourceConstants.PARAMETERS.S3DeploymentBucket));
        stack.setParameter(ResourceConstants.PARAMETERS.S3DeploymentRootKey, Fn.ref(ResourceConstants.PARAMETERS.S3DeploymentRootKey));

        const func = new lambda_node.NodejsFunction(stack, "countResolverFunction", {
            projectRoot: __dirname,
            entry: path.join(__dirname, "resolver.ts"),
            handler: "handler",
            bundling: {
                forceDockerBundling: true
            }
        });
    };
}
```
2. Add this transformer by adding the path to `./amplify/backend/api/amplify/transform.conf.json`
3. Add `@foo` to your schema
4. Run `amplify push`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

```graphql
type Todo @foo {
  id: ID!
  name: String!
  description: String
}
```

### Additional information

Full error message:
```
CREATE_FAILED      countResolverFunction7AFC8206                                                           AWS::Lambda::Function      Tue Feb 22 2022 22:28:15 GMT+1100 (Australian Eastern Daylight Time) Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: Lambda, Status Code: 400, Request ID: 3de18d23-9099-48e2-af22-85ef678ff11c, Extended Request ID: null)" (RequestToken: ce29afe4-58ea-acbd-42b1-b2073e07ec93, HandlerErrorCode: InvalidRequest)
CREATE_FAILED      amplify-amplify-somedev-210332-apiamplify-REXGKFCZYMOU-countResolverStack-1JJTAEVS17RUX AWS::CloudFormation::Stack Tue Feb 22 2022 22:28:16 GMT+1100 (Australian Eastern Daylight Time) The following resource(s) failed to create: [countResolverFunction7AFC8206, QuerycountTodoResolver].  
```

**Comment by ykethan** [comment]
hey @multimeric, thank you for reaching out. apologies for the delay in a response. wanted to check and see if you are still experiencing issues. If so, could you please provide us the full example for your transformer.

**Comment by multimeric** [comment]
Unfortunately I couldn't work out how to reproduce this issue, so I'm happy to close. Not sure if it's actually fixed, though.
