### ISSUE TITLE
Amplify failing to find GroupRole Policies causing Push to fail

### ISSUE THREAD

**Issue by RadomirPerisic** [aws-amplify/amplify-cli#9827]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

After running `amplify update auth` I get an error message about one of existing cognito user groups:

```
UPDATE_FAILED   storages33a9cbeb7  AWS::CloudFormation::Stack Tue Feb 22 2022 14:50:01 GMT+0100 (Central European Standard Time) Output 'adminsGroupRole' not found in stack 'arn:aws:cloudformation:us-east-2:284023404211:stack/amplify-appname-dev-162424-authuserPoolGroups-1CY2XSVA3MEA2/863ab0e0-186c-11eb-a769-068a5b117f6e'
```

I've seen a similar issue: https://github.com/aws-amplify/amplify-cli/issues/8258 but doing `amplify push --force` doesn't help, error appers again.

I've been using amplify in my project for over a year, I noticed after upgrading `amplify-cli` a lot of files in `amplify/backend/auth` have changed. I don't know which version I had when I created `auth`

I didn't change groups, I wanted to change user attributes.

### Expected behavior

`amplify push` should update stack after `amplify-cli` npm package upgrade

### Reproduction steps

Any change in `amplify auth` and doing a push later after upgrading npm package

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line
UPDATE_FAILED   storages33a9cbeb7  AWS::CloudFormation::Stack Tue Feb 22 2022 14:50:01 GMT+0100 (Central European Standard Time) Output 'adminsGroupRole' not found in stack 'arn:aws:cloudformation:us-east-2:284023404211:stack/amplify-appname-dev-162424-authuserPoolGroups-1CY2XSVA3MEA2/863ab0e0-186c-11eb-a769-068a5b117f6e'
```

</details>

**Comment by RadomirPerisic** [comment]
Additional note: after reseting changes in git, and I try to `amplify push --force` I get the same error

**Comment by RadomirPerisic** [comment]
If you are talking about `amplify/backend/auth/userPoolGroups/build/userPoolGroups-cloudformation-template.json` file, I don't see `adminsGroupRole` or `usersGroupRole` values in `Outputs`.

**Comment by RadomirPerisic** [comment]
I did a search in project, I found it in `amplify/backend/awscloudformation/build/auth/userPoolGroups/template.json`:

**Comment by josefaidt** [comment]
Hey @RadomirPerisic thank you for clarifying! When running `amplify status` does it show the user pool groups is in the "UPDATE" state? And are the groups available in the precedence JSON file? I'm curious if whether these were unintentionally removed and perhaps whether we're able to capture a diff of those changes to better understand when this unintentional change occurred

**Comment by RadomirPerisic** [comment]
After running `amplify status` it shows `userPoolGroups` in `UPDATE` state.
Groups are available in precedence JSON file.
Looking back when I created this project, package version was 4.x if that helps.

`git status` shows this diff:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    amplify/backend/auth/xxxxxx/auth-trigger-cloudformation-template.json
	deleted:    amplify/backend/auth/xxxxxx/xxxxxx-cloudformation-template.yml
	deleted:    amplify/backend/auth/xxxxxx/parameters.json
	deleted:    amplify/backend/auth/userPoolGroups/parameters.json
	deleted:    amplify/backend/auth/userPoolGroups/template.json
	modified:   amplify/backend/auth/userPoolGroups/user-pool-group-precedence.json
	modified:   amplify/backend/backend-config.json
	modified:   amplify/backend/types/amplify-dependent-resources-ref.d.ts
	modified:   amplify/team-provider-info.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	amplify/backend/auth/xxxxxx/cli-inputs.json
```

**Comment by josefaidt** [comment]
> Looking back when I created this project, package version was 4.x if that helps.

Are you referring to the `aws-amplify` package here or the CLI version?

**Comment by sachscode** [comment]
Hi @RadomirPerisic 
Could you please share the contents of your amplify folder through an email to amplify-cli@amazon.com. This will allow us to inspect and validate if all auth resources have been correctly migrated. Also , could you pl confirm which storage resource are you adding the authentication to ? is it S3 or DDB.

**Comment by RadomirPerisic** [comment]
@josefaidt `amplify-cli` version
@sachscode I'll send the folder

**Comment by RadomirPerisic** [comment]
I'm not adding authentication to any storage (or at least not trying to), this was already set up

**Comment by sachscode** [comment]
@RadomirPerisic  
Per the cli-inputs.json , the identity-pool seems to be missing. This is required for the userPoolGroupRoles to be created. 
We follow the method presented in https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_cognito-bucket.html . 

Could you please share the CLI flow used to update auth?
```
amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: (Use arrow keys)
❯ **User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)**
  User Sign-Up & Sign-In only (Best used with a cloud API only)
  I want to learn more.
 
```
please select the first option in "Select the authentication/authorization services that you want to use" option.

**Comment by RadomirPerisic** [comment]
I selected `User Sign-Up, Sign-In, connected with AWS IAM controls` on first option. I was able to push without any problems.
I don't remember selecting this option when previously setting up auth, but I might be wrong.
Thanks for help
