### ISSUE TITLE
stray `undefined` message printed when exiting `amplify update storage`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9829]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.21

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

storage

### Amplify Commands

update

### Describe the bug

When running `amplify update storage`, if we exit (ctrl+c) the workflow we notice a stray `undefined` message

```text
> amplify update storage
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✖ Restrict access by? · Auth/Guest Users
undefined
🛑 An error occurred when updating the storage resource
```

### Expected behavior

should not print `undefined`

### Reproduction steps

1. `amplify init -y`
2. `amplify add storage`
3. `amplify update storage`
4. ctrl+c
5. observe stray `undefined`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by flozender** [comment]
Hi, can I work on this, please? Thanks!
