### ISSUE TITLE
AWS Lambda appsync client 

### ISSUE THREAD

**Issue by austinamorusocfc** [aws-amplify/amplify-cli#983]
I built an a super simple client to allow composing of appsync calls when using cognito

https://www.npmjs.com/package/executequery

Got the idea from the following article but didn't like having to turn off cognito 
https://read.acloud.guru/backend-graphql-how-to-trigger-an-aws-appsync-mutation-from-aws-lambda-eda13ebc96c3

Was hoping there would be a better / faster way to do this.

**Comment by UnleashedMind** [comment]
Thanks @austinamorusocfc for the feedbacks. 
Do you have any specific suggestions?

**Comment by kaustavghosh06** [comment]
Closing this due to lack of requester response. If you're still interested in tracking this ans give us more information, let us know and we'll re-open this.
