### ISSUE TITLE
`amplify/hooks/` directory is pulled when choosing not to modify the backend during `amplify pull`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9835]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.21

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

Upon pulling an existing Amplify app into a new directory and choosing _not_ to modify the backend, observe the `amplify/hooks/` directory is also pulled. This may cause issues when hooks are used to modify backend files that are not pulled when choosing not to modify the backend.

https://docs.amplify.aws/cli/teams/multi-frontend/

### Expected behavior

`amplify/hooks/` is not pulled when choosing not to modify the backend

### Reproduction steps

1. create a new project with `amplify init -y`
2. modify the pre-push hook
3. push with `amplify push -y`
4. in a separate directory, run `amplify pull` and choose the newly pushed app
5. choose "no" to "Do you plan on modifying this backend?"
6. observe hooks directory is pulled

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by lazpavel** [comment]
tested with v.10.5.0. no longer an issue
