### ISSUE TITLE
Lambda authorization for AppSync defaults to User Pool authorization when a Cognito ID token is used

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-cli#9836]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.20

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

auth, custom, function, api

### Amplify Commands

Not applicable

### Describe the bug

Hello

When using custom Lambda authorization for AppSync, the Authorization type defaults to User Pool Authentication when a Congito JWT token is used.

### Expected behavior

When using Lambda Auth, one should be able to use AWS Congito JWT token as the Auth Token. AppSync should not interpret this as User Pool Authorization.

### Reproduction steps

1. create amplify environment. run `add function`. create a [python function](https://gist.github.com/rezab777/1fcbf933802a408fa264ca522bec2bba). you will need to add the python package `jose` as a layer.
2.  run `amplify import auth` and import a cognito user pool.
3. run `amplify add api`.  pick user pool authentication and the function created earlier as the api authentication methods. use below schema for the api.
4. deploy.
5. after deployment, create a few sample entries with different `owner` values from the appsync console.
6. now modify the `QueryGetAnimalDataResolverFn` resolver's request mapping template. disable `$util.toJson($ctx.result.items[0])`  and instead replace it with `Auth type is $util.authType()`.
7. now choose AWS Lambda as auth provider in the appsync console.
8.provide your JWT id token generated by Cognito in the Authorization token field and run a getAnimal query . this would return the authorization mode in the console. As you will be able to see, it will be `User Pool Authorization` instead of `Lambda Authorization`.

Why is this happening ? 
Why can you not pass a cognito jwt token as the token ? and why does it interpret it as user pool authorization. 
I observed the same behaviour when using a Lambda authorizer in node.js. i.e. when the token was something other than a cognito jwt token e.g. `custom-authorized`, the auth type was correctly interpreted as Lambda authorization. But when a cognito jwt token was supplied, it interpreted the auth to be a user pool auth.

### GraphQL schema(s)

```
type Customer
  @model
  @auth(
    rules: [
      { allow: custom }
      { allow: owner }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  customer_last_name: String
}

type Animal
  @model
  @auth(
    rules: [
      { allow: custom }
      { allow: owner }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  animal_type: String
  animal_color: String
}
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sundersc** [comment]
Hi @rezab777 - This seems to be an issue with the AppSync service, there is a similar issue noticed with OIDC authentication as well https://github.com/aws-amplify/amplify-cli/issues/9714.

A quick workaround would be to append some prefix like `Token<space>` + `JWT` and remove the prefix in the lambda and process the JWT.

**Comment by rezab777** [comment]
@sundersc Thanks for your recommendation. As you suggested , I added a prefix such as `Bearer` and it seems to solve the issue.
