### ISSUE TITLE
support CDK version 2 

### ISSUE THREAD

**Issue by chakch** [aws-amplify/amplify-cli#9845]
### Is this feature request related to a new or existing Amplify category?

New category

### Describe the feature you'd like to request

The aws-amplify/cli-extensibility-helper support only the CDK version 1.
add the support of CDK version 2 for aws-amplify/cli-extensibility-helper

### Describe the solution you'd like

I think it will be better to create new package aws-amplify/cli-extensibility-helper-cdkv2 to have the ability to import resource in an custom cdk stack using v2  

### Describe alternatives you've considered

Nothing 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [x] ⚠️ This feature might incur a breaking change

**Comment by joshwand** [comment]
The problem extends beyond just cli-extensibility-helper -- indeed you cannot build any custom resources using v2 as the amplify cli uses v1 and complains if it's not there.

**Comment by chakch** [comment]
> The problem extends beyond just cli-extensibility-helper -- indeed you cannot build any custom resources using v2 as the amplify cli uses v1 and complains if it's not there.

I can build an custom stack using cdk v2 by changing all the dependencies and it's work fine. But When I try to import created resources using the helper, I couldn't, because the helper use the v1 version

**Comment by dreamorosi** [comment]
CDK v1 will enter maintenance mode on June 1, 2022: https://github.com/aws/aws-cdk/issues/19836

> AWS CDK v1 will enter Maintenance Mode after June 1, 2022. After this date, we will continue to publish releases to v1 only for critical security updates and critical bug fixes. We will not publish new features or minor bug fixes to v1. See the [AWS SDKs and Tools maintenance policy](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html) for more detail on what this means.

**Comment by menendezjaume** [comment]
Same. Even more considering what @dreamorosi said. I can't see how this is a P3 when v1 is entering maintenance mode in less than a month…

**Comment by siegerts** [comment]
linking https://github.com/aws-amplify/amplify-cli-export-construct/pull/39

**Comment by dreamorosi** [comment]
Thank you @siegerts for linking that PR.

Has the team considered using L1 constructs that are available in CDK v2 instead of holding off the migration/support?

**Comment by swaminator** [comment]
@dreamorosi @joshwand  @chakch @alex-vladut, @ryanhuff, @tacck, @MattJColes, @sopel, @dreamorosi, @pbv0, @agcty, @iShavgula-TacTill: We are currently working to upgrade to CDK v2. Couple of questions for ya'll:
1. What commands are you using? (e.g. `export`, `custom`, `overrides`)
2. If you're using `export`, do you have any automated CI workflows that depend on this?

**Comment by dreamorosi** [comment]
@swaminator from my side `custom` 90% of the time & `overrides` 10% of the time.

**Comment by PhilipWhiteside** [comment]
Yes, `override`. However, as not all properties are supported by overrides, I've been preferring to just go with CDK directly. Some of these are required by app sec teams for projects. My use of Amplify is being trimmed down to client side. It would be great to have seen Amplify create a self contained CDK construct that can be imported into a CDK stack deployed with CDK pipelines. Again, this is not perfect, as it depends on whether a method exists on the resource as CDK doesn't create them, so not all properties are supported then either.

No `custom`. Instead running a post publish/push/status script to grab ARNs from the Amplify stack and pump them into CDK v2 stack as parameters. 

No `export`. The output doesn't work without the helper from what I tried. I'd expected a functional cfn stack but some of the stacks were not referencing each other (IIRC dynamodb table stack wasn't referenced by api, or something nested like that, this was a short while ago).

**Comment by mtliendo** [comment]
CDK V2 for Amplify is in public preview :) : https://aws.amazon.com/blogs/mobile/use-aws-cdk-v2-with-the-aws-amplify-cli-extensibility-features-beta/

**Comment by sobolk** [comment]
We just shipped `@aws-amplify/cli@11.0.0` together with `@aws-amplify/cli-extensibility-helper@3.0.0` which are on CDKv2.
