### ISSUE TITLE
@auth issue when used with relational directives and partial access rights

### ISSUE THREAD

**Issue by lazpavel** [aws-amplify/amplify-cli#9846]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

v7.6.21

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When using gql model types with partial create rights (eg: not allowed to create some fields) and relational directives the create mutation will fail.

### Expected behavior

Create mutation should succeed

### Reproduction steps

1. `amplify init`
2. `amplify add api`
3. `amplify push`
4. in console execute the create mutation and observe the error

example:
```
mutation MyMutation {
  createChild(input: {id: "001", name: "test"}) {
    id
    name
  }
  createParent(input: {parentChildId: "001", name: "test"}) {
    updatedAt
    parentChildId
    owner
    name
    id
    description
    createdAt
  }
}
```

`createParent will fail "message": "Unauthorized on [parentChildId]"`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Parent @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String
  description: String @auth(rules: [{ allow: owner, operations: [read] }])
  child: Child @hasOne
}

type Child @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String
}

```

</details>

### Additional information

Second example:
```
type Post @model @auth(rules: [{ allow: owner, operations: [create, read] }]) {
  id: ID @auth(rules: [{ allow: owner, operations: [create, read, update, delete] }])
  name: String @auth(rules: [{ allow: owner, operations: [create, read, delete] }])
  owner: String
}
```

is not allowing nullifying the name when it should
```
mutation MyMutation {
  createPost(input: {id: "0002", name: "test"}) {
    id
    name
    owner
    updatedAt
    createdAt
  }
  updatePost(input: {id: "0002", name: null}) {
    id
    name
    owner
    updatedAt
    createdAt
  }
}
```

`"message": "Unauthorized on [name]"`

**Comment by afnar** [comment]
Hi @lazpavel,
I was looking at this PR and that's awesome!
I just have a question about this new feature that I'm unsure I understood correctly. I have the following schema:
```
type MyModel
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      # Owner
      {
        allow: owner
        ownerField: "senderUserId"
        operations: [read, update, delete]
      }
      { allow: owner, ownerField: "recipientUserId", operations: [read] }
      # Private
      { allow: private, provider: iam, operations: [read] }
      # Groups
      { allow: groups, groups: ["Worker"], operations: [create] }
    ]
  ) {
  id: ID!
  senderUserId: String!
  recipientUserId: String!
  status: MyModelStatus
    @default(value: "PENDING")
    @auth(
      rules: [
        # Owner
        { allow: owner, ownerField: "senderUserId", operations: [read] }
        {
          allow: owner
          ownerField: "recipientUserId"
          operations: [read, update]
        }
        # Private
        { allow: private, provider: iam, operations: [update] }
      ]
    )
  }
```

As you can see, I have `2 owners`:
- one (`senderUserId`) that can `[read, update, delete]` but on `status` he can just `[read]`;
- one (`recipientUserId`) that can `[read]` but on `status` he can also `[read, update]`;

I also have the **group** `['Worker']` that can `[create]` but on `status` he cannot.

When trying to execute the mutation `CreateMyModel` with all the inputs **except** `status`, I get a error `Unauthorized on [status]`.

Shouldn't it work with your PR? or I misunderstood it?

Thanks!

**Comment by lazpavel** [comment]
Hi @afnar, you have @default directive on the status field so it still tries to se the default, can you retry without the @default directive?

**Comment by afnar** [comment]
I did not tried yet, but the `@default` directive should stay because it's important.
The real use case I wanted is that when the user uses `createMyModel`, no `status` will be passed in the `$input` but it will fallback on the default. This `status` can then only be `created` using the default value or also updated for example using a Lambda.
What should be the best solution to my use case? I didn't wanted to create a Lambda resolver just to do this `default` behavior.
