### ISSUE TITLE
The user having authRole can't access the data because a resolver generated by Amplify CLI doesn't allow authRole to access the data

### ISSUE THREAD

**Issue by sasssssssa** [aws-amplify/amplify-cli#9854]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I found the like a bug about a resolver generated by Amplify CLI.

I want to create schema any user is allowed to read all data.
I checked this [document](https://docs.amplify.aws/cli/graphql/authorization-rules/#configure-multiple-authorization-rules), I tried below the schema.graphql. But, I couldn't authenticated user is allowed to read all Todo.

schema.graphql
```graphql
type Todo @model 
  @auth(rules: [{ allow: public, operations: [read], provider: iam }]){
  id: ID!
  name: String!
  description: String
}


```

method
```javascript
async function list_query() {
  const listTodo = await API.graphql({
    query: listTodos,
    variables: {},
    authMode: 'AWS_IAM'
  });
  console.log(listTodo)
}
```

error response
```
{"data":{"listTodos":null},"errors":[{"path":["listTodos"],"data":null,"errorType":"Unauthorized","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Not Authorized to access listTodos on type ModelTodoConnection"}]}
```

---

I checked the resolver named 'Query.listTodos.auth.1.req.vtl'.
Why this resolver is allowed only unauthorized user? What if I want to show the data to everyone?

'Query.listTodos.auth.1.req.vtl
```
## [Start] Authorization Steps. **
$util.qr($ctx.stash.put("hasAuth", true))
#set( $isAuthorized = false )
#set( $primaryFieldMap = {} )
#if( $util.authType() == "IAM Authorization" )
  #if( !$isAuthorized )
    #if( $ctx.identity.userArn == $ctx.stash.unauthRole )
      #set( $isAuthorized = true )
    #end
  #end
#end
#if( $util.authType() == "User Pool Authorization" )

#end
#if( !$isAuthorized && $util.isNull($ctx.stash.authFilter) )
$util.unauthorized()
#end
$util.toJson({"version":"2018-05-29","payload":{}})
## [End] Authorization Steps. **
```

Now, I'm thinking of replacing to the resolver like allowing authRole can access to the data.
```
    #if( $ctx.identity.userArn == $ctx.stash.unauthRole ||  $ctx.identity.userArn == $ctx.stash.authRole)
```

### Expected behavior

Authenticated user can access all data.

### Reproduction steps

N/A

### GraphQL schema(s)

<details>

```graphql
type Todo @model 
  @auth(rules: [{ allow: public, operations: [read], provider: iam }]){
  id: ID!
  name: String!
  description: String
}


```

</details>

### Log output

<details>

```
{"data":{"listTodos":null},"errors":[{"path":["listTodos"],"data":null,"errorType":"Unauthorized","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Not Authorized to access listTodos on type ModelTodoConnection"}]}


```

</details>

**Comment by josefaidt** [comment]
Hey @sasssssssa :wave: thanks for raising this! Can you confirm whether your auth resource allows unauthenticated logins? This is required to be used with public IAM rules in GraphQL

```
Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
```

This can be changed with `amplify update auth` > Walkthrough all the auth configurations

**Comment by sasssssssa** [comment]
Hi, @josefaidt. Thank you  for your response
I had changed it before raise issue. But, I enabled unauthenticated logins does not solve this problem

```
$ amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

...
 Allow unauthenticated logins? (Provides scoped down permissions that you can
 control via AWS IAM) Yes
```

**Comment by rafaelfaria** [comment]
I am not sure if you are having this issue locally when you mock, I certainly do. I have exactly the same issue, the issue doesn't happen when I deploy it to staging. This makes developing REALLY tricky because with every change I want to test, i actually need to push to my staging.

For reference, this used to work on v 1. 
I'm surprised more people are not complaining about it.

**Comment by josefaidt** [comment]
Hey @sasssssssa :wave: apologies for the delay here! Are you still experiencing this issue? From the provided schema, frontend code example, and VTL template this appears to be set up correctly. I have a few follow-up questions:

- do you experience this issue when mocking?
- might be a silly question, but did you run `amplify push` after setting unauthenticated logins?

And to clarify, the unauth role will be used for public IAM auth, where the authRole is used to private IAM auth (accessible by any logged-in user)

**Comment by alharris-at** [comment]
Hi @sasssssssa, I have reproduced this issue, and will mark this as a bug. Thank you for filing.

**Comment by alharris-at** [comment]
Hi @sasssssssa, it turns out I was also a bit confused based on the existing documentation, and after confirming with the team, it looks like this is working as intended today. We are working on an update to the docs to clarify the issue a bit further, and hopefully make it easier to get this right the first time around. As suggested, adding the `private iam` auth rule should allow you to do what you're trying to do here. Please reach out if you have any more questions.
