### ISSUE TITLE
Adding owner read-only field-level Auth rule causes 'not authorized to access' field errors even though reader is the owner

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#9855]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

7.6.22

### What operating system are you using?

Debian 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When using the schema below for a User model, the owner gets denied authorization to access a model when the GraphQL query to access the model includes the following rule `@auth(rules: [{ allow: owner, operations: [read] }])` -- i.e. making any field read-only to the owner causes authentication errors when the owner tries to read that field.

### Expected behavior

I expected the owner to be authorized to read the User model they own, even after adding the field level Auth rule that allows owner read-only access, but after adding that rule owner became unauthorized.

### Reproduction steps

1. Have a schema and a model defined in it with some fields
2. Put the same model-level `@auth` rules on this model that are on the schema below
3. Now put a field-level `@auth` on some field like this: 
    ```graphql
       @auth(rules: [{ allow: owner, operations: [read] }])
    ```
4. Apply a GraphQL query, as owner logged in to your Cognito User Pool to read the model and include the field that has the field-level Auth rule in your query - you'll see the authorization denied error

### GraphQL schema(s)

<details>

```graphql
type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  bio: String!
  bytesQuota: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  bytesUsed: Int!
}
```

</details>

### Log output

<details>

This is reported in browser's DEV console:

```
ERROR Error: Uncaught (in promise): Object: {"data":{"getUser":null},"errors":[{"path":["getUser","bytesQuota"],"data":null,"errorType":"Unauthorized","errorInfo":null,"locations":[{"line":15,"column":5,"sourceName":null}],"message":"Not Authorized to access bytesQuota on type Int"}]}

```

</details>

### Additional information

This is a successful query with the schema above, because it does not include the field with the field-level Auth rule:
![successful_query](https://user-images.githubusercontent.com/5935957/155630607-67edf413-9051-441b-9b22-a1cb596c344b.png)

But here's a query that does include the field with the field-level Auth rule:
![error_query](https://user-images.githubusercontent.com/5935957/155630610-57bc4097-d435-4421-b3d9-08e7e457d6ec.png)

**Comment by dorontal** [comment]
This issue spawned off from: https://github.com/aws-amplify/amplify-cli/issues/6343

**Comment by dorontal** [comment]
Actually closing this issue in favor of the original issue -- there was no reason to close the original issue

**Comment by josefaidt** [comment]
Hey @dorontal :wave: let's carry the conversation here as the previous issue was labeled as a feature request for deny-by-default behavior for Transformer v1 where this issue appears to be a bug or unintentional behavior with transformer v2 and the updated deny-by-default behavior.

**Comment by josefaidt** [comment]
From the previous issue we can use the following schema and create a few users to add a few Todo items with user-specific `notes`

```graphql
type Todo
  @model
  @auth(rules: [{ allow: owner }, { allow: public, operations: [read] }]) {
  id: ID!
  name: String!
  notes: String @auth(rules: [{ allow: owner }])
}
```

After creating a few records we can modify our schema to be read-only:

```graphql
type Todo
  @model
  @auth(
    rules: [
      { allow: owner, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
  notes: String
    @auth(rules: [{ allow: owner, operations: [read] }])
}
```

this will allow us to retrieve the data depending on the currently authenticated user:

![fetch todos as user](https://user-images.githubusercontent.com/5033303/155623804-b49aebe8-0eae-44ed-9fa3-61ed289ce80f.png)
![fetch todos as josef](https://user-images.githubusercontent.com/5033303/155624116-aede47cb-c463-45da-b25b-5ca932ce2591.png)

**Comment by dorontal** [comment]
Thanks very much @josefaidt -- I understand, continuing her.

**Comment by dorontal** [comment]
@josefaidt first thanks a lot for trying this. My schema -- the one that did not work -- is different from the one you tried, only slightly. The schema I reported above is repeated here:

```graphql
type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  bio: String!
  bytesQuota: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  bytesUsed: Int!
}
```

Your schema has different Auth rules at the model level -- perhaps it's that difference that causes my schema to fail as described above and yours to succeed (- in retrieving queries that had the field with the field level Auth).

**Comment by dorontal** [comment]
@josefaidt just to answer your question:  I did check that the current authenticated user was the owner - via when logging in in the Appsync queries console, I logged in with the user who is the owner of that record.

**Comment by josefaidt** [comment]
Hey @dorontal thank you for the clarifications! I updated my schema to be similar to yours except I chose API Key for public auth instead of IAM, however that should not cause an issue since we are authorizing with Cognito User Pools. After commenting out the `owner` auth rule at the model-level I'm still seeing the intended results.

```graphql
type Todo
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      # { allow: owner, operations: [read] }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID! @primaryKey
  name: String!
  notes: String @auth(rules: [{ allow: owner, operations: [read] }])
}
```

I have a few follow-up questions:

- Can you send a screenshot of the returned results with the `owner` field and current logged in user for clarification?
- Can you try setting up another project with the same sample schema are you also experiencing the issue there? Keep in mind when setting up a test project we will want to grant owner write permissions to create a few items first

**Comment by dorontal** [comment]
Hi @josefaidt I don't think that using an API key is the same at all. It's not difficult to replicate my issue, you only need to have a single user added to your app, then sign that user in, then do a query with that user as the currently signed in "owner".

I cannot show the owner field easily because the Appsync console does not have that hidden field as an optional field to show. I know the user was the owner because it was the only one user in the DB currently.

If I have time and this is not solved over the next couple of weeks, I'll definitely write a small test app.

**Comment by josefaidt** [comment]
Hey @dorontal :wave: I believe without the `owner` authorization rule on the model level the owner is not stored, which explains why we're not seeing the owner field in the AppSync Console. Referencing this doc https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access

> To restrict a record's access to a specific user, use the owner authorization strategy. When owner authorization is configured, only the record's owner is allowed the specified operations.
Behind the scenes, Amplify will automatically add a `owner: String` field to each record which contains the record owner's identity information upon record creation.

If you look at the built schema do you see an `owner` field?

```graphql

type Todo @aws_api_key @aws_iam @aws_cognito_user_pools {
  id: ID!
  name: String!
  notes: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
  owner: String
}
```

**Comment by dorontal** [comment]
Got it. Thanks @josefaidt !  WIll try.

**Comment by dorontal** [comment]
Could this be a case of the VTL template not populating `owner` properly - is that why it's null?

**Comment by dorontal** [comment]
I think I understand now. Thank you for pointing out the existence of this hidden `owner` field @josefaidt!

In my app, user records in the DB are created only one way - inside a post-confirmation lambda trigger - when the DB record is created, owner is not set to anything. When I try to add one line that sets the owner to the same value as id in the post-confirmation lambda trigger, then the field level authorization rule works again! This issue has just gotten solved for me. Thanks so much! (I'll let you close it whenever you see fit).

**Comment by josefaidt** [comment]
Hey @dorontal :wave: glad to hear you're back up and running! Closing issue 🙂

**Comment by B33fb0n3** [comment]
Hey @josefaidt, 
I have about the same problem, just haven't been able to solve it with this thread yet. 
I created the following schema:
`type Team @model @auth(rules: [{ allow: private, operations: [read] },{ allow: groups, groups: ["Chef"]}]) {
  id: ID! # fil_51100
  weekId: ID
  currentWeek: Week @hasOne(fields: ["weekId"])
  weeks: [Week] @hasMany(indexName: "byTeam", fields: ["id"])
  user: [User] @hasMany(indexName: "byTeam", fields: ["id"])
}

type User @model @auth(rules: [{ allow: private, operations: [read] },{ allow: owner, operations: [create, read, update], ownerField: "owner" }]) {
  id: ID!
  owner: ID! # userSub
  displayname: String!
  teamId: ID! @index(name: "byTeam", sortKeyFields: ["displayname"])
  team: Team! @belongsTo(fields: ["teamId"]) @auth(rules: [{ allow: private, operations: [read] },{ allow: groups, groups: ["Chef"], operations: [update]}])
  cbrTotalAmount: Int! @default(value: "0")
  cbrCount: Int @default(value: "0") @auth(rules: [{ allow: owner, ownerField: "owner" }]) 
  cbrDrCount: Int @default(value: "0") @auth(rules: [{ allow: owner, ownerField: "owner" }])
  cbrWithRsvCount: Int @default(value: "0") @auth(rules: [{ allow: owner, ownerField: "owner" }]) 
}
`
When I execute like this:
`        const result = await API.graphql({
            query: getTeam,
            variables: {id: "fil_51100"},
            authMode: 'AMAZON_COGNITO_USER_POOLS'
        });
        console.log(result);`
I get an error with 3 unauthorithed fields. Thats cause in the team are two users. One is the person who execute so he can read the fields from hisself but not from the other person. The API.graphql throws and error with the unauthorized fields, but also send the expected data. It looks like this:
[https://ibb.co/yV124z0](url)
How do I not get the unauthorized error or should I get my data from the error (but than what about error handling...)?

**Comment by maziarzamani** [comment]
I have the same problem, but only in Flutter SDK. I do not see this issue in JS.
