### ISSUE TITLE
Best way  to give access team member pull only  env with amplify studio or via IAM ?

### ISSUE THREAD

**Issue by aqarcoSys** [aws-amplify/amplify-cli#9857]
I want to give access to a team members to only pull change on specific env 

**Which Category is your question related to?**
Team work
**Amplify CLI Version**
7.6.15

**What AWS Services are you utilizing?**
- Lambda
- S3
- CloudFront
- dynamodb

**Comment by sachscode** [comment]
Although Amplify doesn't support this out of the box, If the environments are hosted in separate AWS accounts it can be achieved by configuring the correct IAM roles for your team.
1.  Do not allow your team to access the restricted account ( say production )
2. Configure readonly cross account access using - https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html  
3. Test that they are able to perform read-only operations like "amplify pull"
