### ISSUE TITLE
Deleting backend env failed

### ISSUE THREAD

**Issue by parvusville** [aws-amplify/amplify-cli#9880]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.6

### Amplify CLI Version

7.5.4

### What operating system are you using?

Pop!_OS 21.10

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

In the process I manually deleted the existing S3 deployment bucket, and a lambda function IAM role for sending emails, which weren't initially deleted with the rest of the resources. 

### Amplify Categories

hosting

### Amplify Commands

env

### Describe the bug

Hello, I have ended up in a state where I have a backend which shouldn't exists connected to one of my apps, and I cannot delete it. This also means I cannot delete the app.

We've got a monorepo project, where one app "A" has backend connected, and other app B only has frontend. Now I was trying to make another frontend only app "C", but somehow accidentally ended up with the existing dev backend connected to it. I didn't realize this at first, because the appId show under "Edit backend" in console was different. 

I tried deleting this dev backend that appeared in the new app C, noticing that now app A dev backend was also in "Deletion in progress" -stage. Looking at cloudformation logs, I see 
`Embedded stack arn:aws:cloudformation:eu-west-1:xxx:stack/amplify-xxx-dev-115515-functioncontroller-15G4OTLKJEV1/xxxxx-558d-11eb-8426-027144e8a80b was not successfully deleted: The following resource(s) failed to delete: [LambdaExecutionRole]. ` leading into `The following resource(s) failed to delete: [functioncontroller].`. So initially I was left with everything else deleted from dev besides this one  lambda. I dont 100% recall how I got rid of it. I also couldn't get new backend with the exact same name "dev" working, while trying to do that I believe I manually removed the existing S3 deployment bucket for the old environment.

Now I have managed to delete the dev backend from the app A (doesn't show up in the list anymore), but dev backend is still listed for the  app C. Trying to delete the backend "dev" backend shown for app C in the console gives `Deleting backend env: undefined from app: xxx failed`

### Expected behavior

Deleting a backend environment should work. 

### Reproduction steps

1) Connect existing backend into a new app
2) Delete the backend from the new app

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by 0afcode** [comment]
In a case like this, you must use the amplify cli and provide *ALL* of the following: appid, env name, the profile, and the region on the delete command. In below command replace text that is wrapped in <> with your actual values. Then once that is done, you can go run the cli command to delete the app, or use the AWS console.

aws amplify delete-backend-environment --app-id <your_app_id> --environment-name <backend_env_name> --profile <your_local_aws_credentials_profile> --region <region_containing_app>

ex: 
aws amplify delete-backend-environment --app-id fasldfjalsdkfj --environment-name dev --profile mymainprofile --region us-east-1

**Comment by PeteDuncanson** [comment]
@0afcode few questions about this one.

you seem to be starting your command with `aws amplify <whatever>` but mention using the Amplify CLI which I'd expect to just be `amplify <whatever>`

where the heck do I find my profile name?

when running this as `amplify` I get:

`The Amplify CLI can NOT find command:  delete-backend-environment`

**Comment by josefaidt** [comment]
Hey @parvusville :wave: are you still experiencing this issue? Did the above `aws-cli` command work for you to delete this stray backend environment?

**Comment by parvusville** [comment]
@josefaidt Hey, yes the above command worked for deleting the backend environment, and now I was able to delete the app from the AWS console. I only tried this now, as I back then wanted to avoid any kind of potential additional problems :sweat_smile: Note that this all included deleting the old dev backend, that I accidentally linked into this new app.

**Comment by PeteDuncanson** [comment]
Word of warning about this. This will remove the app from Amplify but it won't clean up the resources that you had in AWS genrally for that app. You will still have Lambdas, OpenSearch, DynamoDB tables etc active within your setup for that environment that you will have to manually remove. I've been doing this by just searching for the "-test" environment name I want to get rid of and then manually deleting. If you do this within CludFormation stacks you can delete a lot of them by deleting the root stack (if you try to delete a child stack if will ask if you want to delete the parent to make it easier).

Biggest of these to clear out is the OpenSearch one as you get charged a minimum free ($50 ish) for that monthly one regardless if you aren't on the tiny instance.

Hope that helps :)
