### ISSUE TITLE
GraphQL Transformer v2 migration tool fails to migrate pre-existing many to many relationships created using a join table

### ISSUE THREAD

**Issue by cfbo** [aws-amplify/amplify-cli#9888]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.22

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have upgraded the graphql Transformer to v2 following https://docs.amplify.aws/cli/migration/transformer-migration
I have used the migration tool and then did an amplify push. 

### Amplify Categories

api

### Amplify Commands

codegen, push

### Describe the bug

After successfully building the application (on cloud), when I access the frontend (or even in the Amplify Studio Content view), I get the following sync error:
```
{"data":null,"errors":[{"path":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"Validation error of type FieldUndefined: Field 'syncRuleTemplateRuleLabels' in type 'Query' is undefined @ 'syncRuleTemplateRuleLabels'"}]}
```

The issue occurs on both of the two many-to-many relationship that I have in the schema, which I had created with a join table and that from what I read, I should be able to keep:
![image](https://user-images.githubusercontent.com/7568421/156379349-26ea0514-e020-4eea-9fd6-01b3cb17e3ff.png)

I am wondering if the issue might be related to the use of `(queries: null)` in the join table (which I had borrowed from official docs at the time).

Note: I am using Datastore.

Before migration:
```
type RuleLabel
  @model
  @auth(
    rules: [
      # Authorize content manager to perform all operatations.
      {
        allow: groups
        groups: ["ContentManager"]
        operations: [create, update, delete, read]
      }
      # Authorize any signed-in user to read
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  label: String! #UNIQUE
  ruleTemplates: [RuleTemplateRuleLabel]
    @connection(keyName: "ruleTemplateByRuleLabel", fields: ["id"])
}

# Create a join model and disable queries as are not needed
# (can query through RuleTemplate.ifcVersionList and RuleLabel.ruleTemplates)
type RuleTemplateRuleLabel
  @model(queries: null)
  @auth(
    rules: [
      # Authorize content manager to perform all operatations.
      {
        allow: groups
        groups: ["ContentManager"]
        operations: [create, update, delete, read]
      }
      # Authorize any signed-in user to read
      { allow: private, operations: [read] }
    ]
  )
  @key(name: "ruleTemplateByRuleLabel", fields: ["labelId", "ruleTemplateId"])
  @key(name: "labelByRuleTemplate", fields: ["ruleTemplateId", "labelId"]) {
  id: ID!
  ruleTemplateId: ID!
  labelId: ID!
  ruleTemplate: RuleTemplate! @connection(fields: ["ruleTemplateId"])
  ruleLabel: RuleLabel! @connection(fields: ["labelId"])
}

type RuleTemplate
  @model
  @auth(
    rules: [
      # Authorize content manager to perform all operatations.
      {
        allow: groups
        groups: ["ContentManager"]
        operations: [create, update, delete, read]
      }
      # Authorize any signed-in user to read
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  code: String! #UNIQUE
  name: String!
  description: String!
  notes: String
  ifcVersionList: [RuleTemplateIfcVersion]
    @connection(keyName: "ifcVersionByRuleTemplate", fields: ["id"])
  labelList: [RuleTemplateRuleLabel]
    @connection(keyName: "labelByRuleTemplate", fields: ["id"])
  body: String! # template with tags
  userParameterDefinitions: [UserParameterDefinition]
    @connection(keyName: "byRuleTemplate", fields: ["id"])
  rules: [Rule] @connection(keyName: "byRuleTemplate", fields: ["id"])
}

```

After migration:
```
type RuleLabel
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["ContentManager"] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  label: String!
  ruleTemplates: [RuleTemplateRuleLabel]
    @hasMany(indexName: "ruleTemplateByRuleLabel", fields: ["id"])
}

type RuleTemplateRuleLabel
  @model(queries: null)
  @auth(
    rules: [
      { allow: groups, groups: ["ContentManager"] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  ruleTemplateId: ID!
    @index(name: "labelByRuleTemplate", sortKeyFields: ["labelId"])
  labelId: ID!
    @index(name: "ruleTemplateByRuleLabel", sortKeyFields: ["ruleTemplateId"])
  ruleTemplate: RuleTemplate! @belongsTo(fields: ["ruleTemplateId"])
  ruleLabel: RuleLabel! @belongsTo(fields: ["labelId"])
}

type RuleTemplate
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["ContentManager"] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  code: String!
  name: String!
  description: String!
  notes: String
  ifcVersionList: [RuleTemplateIfcVersion]
    @hasMany(indexName: "ifcVersionByRuleTemplate", fields: ["id"])
  labelList: [RuleTemplateRuleLabel]
    @hasMany(indexName: "labelByRuleTemplate", fields: ["id"])
  body: String!
  userParameterDefinitions: [UserParameterDefinition]
    @hasMany(indexName: "byRuleTemplate", fields: ["id"])
  rules: [Rule] @hasMany(indexName: "byRuleTemplate", fields: ["id"])
}


```

### Expected behavior

I would have expected a smooth migration, given I don't have anything requiring a manual migration and I would have thought the migration tool would take care of everything.
https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate

### Reproduction steps

See bug description.

### Additional information

Application info:
* appId: d3i83n9mlag28r
* eu-central-1
* env: devfab

**Comment by cfbo** [comment]
The issue seems now fixed after removing the `queries: null` option from the join table and then performing an amplify build
![image](https://user-images.githubusercontent.com/7568421/156531563-5dac5a5b-f550-4c8f-aee8-3db346b1b248.png)

I originally added that following the official documentation:
![image](https://user-images.githubusercontent.com/7568421/156532591-2baf1eb8-2636-468a-91fd-951bbad5dec6.png)

and that approach was working in v1.

If confirmed that this is a manual change to make when migrating to v2, you might consider adding it to the migration documentation page and/or have the migration tool printing a warning to the console

**Comment by ykethan** [comment]
closing the issue on documentation update.
