### ISSUE TITLE
Deleting a branch doesn't always delete associated display name

### ISSUE THREAD

**Issue by JanJakes** [aws-amplify/amplify-cli#9896]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1srck04ciclxn

### Region

eu-west-1

### Amplify Console feature

Manual deploys

### Describe the bug

Deleting a branch in Amplify console doesn't seem to always delete the associated display name. This leads to and inconsistent state where a branch with the same name can never be created again.

Deleting the branch fails (as it doesn't exist indeed):

```bash
aws amplify delete-branch --app-id <app-id> --branch-name renovate/graphqlcodegenerator-monorepo

An error occurred (NotFoundException) when calling the DeleteBranch operation: Branch renovate/graphqlcodegenerator-monorepo not found.
```

Creating the branch fails as well:

```bash
aws amplify create-branch --app-id <app-id> --branch-name renovate/graphqlcodegenerator-monorepo

An error occurred (BadRequestException) when calling the CreateBranch operation: Failed to create branch. The display name renovate-graphqlcodegenerator-monorepo already exists for the app <app-id>.
```

This leaves us stuck in a state where we can never create the branch again, neither fully delete it.

I think it's a fairly recent issue (occurring in the recent weeks), haven't encountered it previously.

### Expected behavior

When a branch doesn't exists, the associated display name shouldn't exist either.

### Reproduction steps

I'm not sure how to reproduce it (can't easily reproduce it from the CLI) but we're seeing this when our Renovate bot creates the same-named branches again every now and then. In our CI (GitHub Actions) we simply call the above commands (`aws amplify create-branch` in a CI job run and `aws amplify delete-branch` after the branch has been merged).

The invalid state we're in can be seen on our account (app ID filled in above) for a couple of branches, including `renovate/graphqlcodegenerator-monorepo`.

### Additional information

Not sure if it's related to https://github.com/aws-amplify/amplify-console/issues/2213.

**Comment by ykethan** [comment]
Hey @JanJakes, Thank you for reaching out and apologies for the delay in a response. Wanted to check in to see if you are facing any issues deleting the branches. On performing a quick test in my local CLI, I was able to delete and create a branch using the aws cli.

**Comment by JanJakes** [comment]
@ykethan I'm not using this at the moment so I'm not sure if that issue still occurs.

> On performing a quick test in my local CLI, I was able to delete and create a branch using the aws cli.

Please note that this was an occasional issue that didn't happen with every command. Sometimes the "display name" was simply not deleted while the branch was and that resulted in the inconsistent state with no way out.
