### ISSUE TITLE
Pull existing app to new project

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-cli#9898]
**Amplify CLI Version**
7.6.15

**What AWS Services are you utilizing?**
api, auth, datastore

I have an existing iOS project that is working.
I am trying to create a react project.
I set up the project using 'npx create-react-app mip --typescript'. 
I copied the team-provider-info.json file from my working iOS app to my new React app. 
I then tried 'amplify pull --appId xxxxxx --envName dev' and 'amplify init', where I selected the dev environment. 

Both resulted in the following error.... 
Could not initialize 'dev': Stack with id amplify-mip-dev-xxxxxx does not exist. 
Can you please tell me what I am doing wrong?

**Comment by josefaidt** [comment]
Hey :wave: can you confirm whether you're working in the same AWS account as the existing app? Also it is not required to manually copy files, and instead it is recommended to lean on the Amplify CLI to pulls the necessary files for you upon running `amplify pull --appId xxx --envName dev`

**Comment by LeoReubelt** [comment]
Thanks @josefaidt for getting back to me. I am using the same aws account. And same computer. I tried to do `amplify pull --appId xxx --envName dev` without copying team-provider-info.json first. And it gave me an error saying team-provider-info.json does not exist.

**Comment by josefaidt** [comment]
Hey @LeoReubelt thanks for clarifying! Is there an Amplify project in the parent directory by chance?

**Comment by LeoReubelt** [comment]
@josefaidt no there is not. But I just deleted the amplify directory and pulled again. And now it worked. I was following a tutorial that said to run `npm install --save aws-amplify aws-amplify-react`. I think that is what caused the problem. Either way, it is working now. Thanks for the help.
