### ISSUE TITLE
Open AWS Management Console of S3 or DynamoDB service when run `amplify storage console`

### ISSUE THREAD

**Issue by fossamagna** [aws-amplify/amplify-cli#9900]
### Is this feature request related to a new or existing Amplify category?

storage

### Is this related to another service?

DynamoDB, S3

### Describe the feature you'd like to request

When run `amplify storage console`, shown `to be implemented: storage console`.
I would like to open AWS Management Console of selected S3 or DynamoDB service.

### Describe the solution you'd like

1. Run `amplify storage console`
2. Shown selecting list of `S3` or `DynamoDB`.
3. Open AWS Management Console
   * When selected S3: open S3 bucket in console (ex: https://s3.console.aws.amazon.com/s3/buckets/${bucketName}?region=us-east-1)
   * When selected DynamoDB:  open DynamoDB Tables page in console (ex: https://us-east-1.console.aws.amazon.com/dynamodbv2/home?region=us-east-1#tables)

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hello @fossamagna, apologies for the delay in a response. Thank you for your valuable feedback.
Marking this as a feature request.
