### ISSUE TITLE
Merger to stack v2 not solved issue 

### ISSUE THREAD

**Issue by SecKarma** [aws-amplify/amplify-cli#9905]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

NPM

### If applicable, what version of Node.js are you using?

npm 8.1.1

### Amplify CLI Version

Amplify 7.6.22

### What operating system are you using?

MacOs 11.6.2

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

Merger to stack v2. Upon running amplify push we are unable to change our Opensearch instance even after using the newest documentation.

same error as closed issue on PR 9840 even with the keys.

### Expected behavior

expected to merge to stack v2

### Reproduction steps

Created a new graphql API inside amplify project
Create a new model with the @searchable key
Modify the team-provider-info.json to alter the opensearch instance type
Run amplify push 

### GraphQL schema(s)

<details>

```graphql

#
type TraitSaleHistory @model @searchable
  @auth(rules: [
    {allow: private, provider: iam},
    {allow: public, operations: [read], provider: apiKey},
    {allow: groups, groups: ["User"], operations: [read]},
    {allow: groups, groups: ["Admin"]},
  ]) {
    id: ID!
    soldFor: Float!
}


```

</details>

### Log output

<details>

```
# Put your logs below this line

UPDATE_FAILED         api AWS::CloudFormation::Stack Fri Feb 25 2020 15:50:2020 GMT+0000 (GreenwhichMeanTime) Parameter: [OpenSearchInstanceCount, OpenSearchInstanceType] do not exist in the template 


```

</details>

### Additional information

N/A

**Comment by Tedsterh** [comment]
I'm experiencing the same issue after migrating to V2 as well

**Comment by SecKarma** [comment]
Hey, is their any chance we can get a timescale on this. a vital part of a project we have is needing this feature☺️

(don't want to sound pushy, just need to know what to tell people)

**Comment by SecKarma** [comment]
thank you, no idea at all, like weeks/months. sorry just desperate on this push!

**Comment by SecKarma** [comment]
hey after the recent fix that just went out we are now getting the issue
`parameter "OpenSearchInstanceType` must be one of AllowedValues

even though we are typing the instance name letter for letter

**Comment by SecKarma** [comment]
<img width="546" alt="Screenshot 2022-03-07 at 20 13 45" src="https://user-images.githubusercontent.com/96640232/157111172-92088ee0-5af2-43b3-9f85-47c16fd30510.png">
in team-provider-info.json

please can you help with this as soon as possible

**Comment by marcvberg** [comment]
Hi @SecKarma,

t3.large is not a supported instance type, and you would not be able to select it if you created an OpenSearch cluster through the AWS console either. You can use this page as a reference, if you find an instance type on here that we do not support please let us know. Thanks!

https://aws.amazon.com/opensearch-service/pricing/

**Comment by SecKarma** [comment]
Thank you, sorry for not telling you we managed to solve this! Thank you so much for your assistance

**Comment by youeducate** [comment]
@SecKarma How did you end up solving it?
