### ISSUE TITLE
amplify status always needs update

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-cli#991]
Whenever I would use `amplify status`, it would show that all my functions need to be updated, even when I do not update them. My environment on the cloud is clearly out of sync with my local. I have tried initializing new environments and start over, it doesn't work.

There are 3 things that cause this behavior:
1- using some library in my function/lambda that needs to be imported `yarn add ...`
2- adding a function without an api `amplify add function`
3- modifying permissions from the console for a lambda role.

There is no consistent behavior. Sometimes some functions need update, sometimes all of them need update. Right now I am stuck at everything needing update. My zip files are growing under `/dist` for each function. My `amplify push` takes 10 minutes with a 1Gbps up/down link. Not fair.

Can you please help or let me know if I'm doing something wrong? 
![image](https://user-images.githubusercontent.com/24530625/53947307-60755200-407a-11e9-8a9b-55a41f3b11f2.png)

**Comment by kaustavghosh06** [comment]
@rawadrifai Which version of the CLI are you using? We pushed a fix as a part of V 1.1.7 and this PR - https://github.com/aws-amplify/amplify-cli/pull/963 to improve on the performance when pushing resources.
Also, would you able to do a `git diff` to check what has changed in your environment between the last push and your current push?

**Comment by rawadrifai** [comment]
@kaustavghosh06 I have 0.2.1-multienv.35
Should I not be using multienv?
The diff is too big. The things that could cause this behavior are the 3 items I mentioned above.

**Comment by rawadrifai** [comment]
Overall - the development with amplify is super slow just having to wait a few minutes every time you make a change. I can't simulate locally because I'm using auth. Amplify is super convenient, but needs serious performance enhancements.

**Comment by rawadrifai** [comment]
so I went to 1.1.7 and it's working much better now.. multienv needs rehab.

**Comment by luizdanieldesouza** [comment]
> Overall - the development with amplify is super slow just having to wait a few minutes every time you make a change. I can't simulate locally because I'm using auth. Amplify is super convenient, but needs serious performance enhancements.

Agreed!!!!!
