### ISSUE TITLE
Manual push amplify hosting does not reflect in aws web

### ISSUE THREAD

**Issue by ktmdan** [aws-amplify/amplify-cli#9912]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.3

### Amplify CLI Version

7.6.22

### What operating system are you using?

macs

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Amplify Categories

hosting

### Amplify Commands

publish

### Describe the bug

After publishing a hosting s3 prod, the aws amplify web does not reflect any hosting environments.  It shows the host a web app wizard.  I need to be able to get to domain management and redirects pages.  But it only shows App Settings with General and Amplify studio settings.

I tried s3 dev and s3 prod hosting environments

### Expected behavior

Should show the published hosting environment and allow access to the app settings like domain management and rewrites and redirects.  This worked in older versions.

### Reproduction steps

amplify hosting add
select s3 and prod
amplify publish

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @ktmdan :wave: thanks for raising this! When adding hosting if you select hosting using Amplify Console, this is how we will be able to see our hosted app in the Amplify Console. The option to use s3 and CloudFront will allow you to have more control over the resources, however will not appear in the Amplify Console. https://docs.amplify.aws/cli/hosting/hosting/#amazon-s3-and-amazon-cloudfront

With hosting using the Amplify Console we also have a choice to manually publish. Can you try removing hosting with `amplify remove hosting` and attempt to re-add with `amplify add hosting` selecting hosting with Amplify Console? From there we can select "Manual publish" rather than using the provided CI/CD pipeline https://docs.amplify.aws/cli/hosting/hosting/#type-of-deployments

**Comment by ktmdan** [comment]
Previously it did create a manual publish entry on the aws amplify page.  I don't use the console.  If your removing that feature I understand.  But its a bit odd not to see your entire deployment on aws amplify page.

**Comment by josefaidt** [comment]
Hey @ktmdan apologies for the delay here. To clarify, are you using the "manual publish" option where we selected "Amplify Console" as the provider?

> Manual deployment allows you to publish your web app to the Amplify Console without connecting a Git provider. If you select this option, you will have to run the amplify publish command every time you would like to see your changes reflected in the cloud.

**Comment by josefaidt** [comment]
Hey @ktmdan if you choose to use "Manual Publishing" with Amplify Console/Hosting, it will create the expected entry in your Amplify console. 

```
✔ Select the plugin module to execute · Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
? Choose a type (Use arrow keys)
  Continuous deployment (Git-based deployments) 
❯ Manual deployment 
  Learn more 
```

**Comment by ktmdan** [comment]
Seems to be working after upgrading.  Thank you.
