### ISSUE TITLE
Resolver pipeline auth function override generates duplicate

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-cli#9913]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.20

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

Instead of a pipeline resolver function being overwritten, it is duplicated in the pipeline.

For example, an autogenerated pipeline resolver for getEmployee with authentication has 4 main functions in the AppSync console:

```
QuerygetEmployeepreAuth0Function
QuerygetEmployeeauth0Function
QuerygetEmployeepostAuth0Function
QueryGetEmployeeDataResolverFn
```
These correspond to below generated functions in the /build directory locally:

```
Query.getAnimal.preAuth.1.req.vtl
Query.getAnimal.auth.1.req.vtl
Query.getAnimal.postAuth.1.req.vtl
Query.getAnimal.req.vtl
Query.getAnimal.res.vtl
```

When trying to override any of the auth functions, for example, `Query.getAnimal.auth.1.req.vtl`, the function is successfully overwritten, but another function called `QuerygetEmployeeauth1Function ` is also generated and is added to the pipeline. So after overriding `QuerygetEmployeeauth0Function`, the pipeline will have 5 functions now:

```
QuerygetEmployeepreAuth0Function
QuerygetEmployeeauth0Function
QuerygetEmployeeauth1Function
QuerygetEmployeepostAuth0Function
QueryGetEmployeeDataResolverFn
```

The same behaviour does not happen when overriding any of the data resolver function request or response templates (`QueryGetEmployeeDataResolverFn`). Meaning, no duplicates are created.

Why is an auth1 function created when overriding the auth function ?

### Expected behavior

When overriding an auth0 resolver, no duplicate function called auth1 should be created.

### Reproduction steps

1. Create AppSync API with a model based on the schema provided.
2. Try to override the auth function with your own custom function.
3. You will observe a duplicate function with a different name in the pipeline resolver.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Employee
  @model
  @auth(
    rules: [
      { allow: custom }
      { allow: owner }
      { allow: groups, groups: ["Admin"] }
      { allow: public, provider: iam }
    ]
  ) {
  # Reference Fields
  id: ID! @primaryKey
  owner: ID!
  employee_type: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by rezab777** [comment]
I believe this is a duplicate of [this](https://github.com/aws-amplify/amplify-cli/issues/9650).

**Comment by charlieforward9** [comment]
To clarify, if I edit the files in `amplify/backend/api/<app-name>/build/resolvers` and run `amplify push`, will it permanently update the resolvers in the cloud?
