### ISSUE TITLE
Non-Verifiable URL for Cognito Social Sign-In

### ISSUE THREAD

**Issue by rahul-insight** [aws-amplify/amplify-cli#9914]
**Cognito URL**

**5.1.2**

You can use `amplify -v` to check the amplify cli version on your system

**Cognito**

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

We are using AWS Cognito through Amplify on our Flutter app. Cognito does not allow using permanent custom domain name when provisioned using Amplify. We are using signing with Facebook through Amplify as mentioned [here](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/). Facebook is threatening to block our login app permissions because our website domain does not appear in the domain URL provided by Cognito.

Is there a way to verify our Cognito provided domain URL (it gives 'This site cannot be reached' error) or alternatively use our own custom domain name in Cognito permanently which won't get wiped out on Amplify push?

**Comment by josefaidt** [comment]
Hey @rahul-insight :wave: apologies for the delay here! Are you still experiencing this issue? Alternatively, have you asked this question in our [community Discord server](https://discord.gg/invite/amplify)?
