### ISSUE TITLE
@searchable does not work with custom table names

### ISSUE THREAD

**Issue by rezab777** [aws-amplify/amplify-cli#9916]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

7.6.20

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

When the DynamoDB table name is overwritten, the `@searchable` directive no longer works.

### Expected behavior

Opensearch should work with custom dynamodb table names. 

### Reproduction steps

1. Create AppSync API with a model based on the schema provided.
2. Override one of the table names by providing the override.ts file
```
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';
export function override(resources: AmplifyApiGraphQlResourceStackTemplate) {
    resources.models["TodoOpenSearch"].modelDDBTable.tableName = "staging-todo-opensearch"
}
```
3. Populate the `TodoOpenSearch` table with sample entries .
4. Search for `TodoOpenSearch` data using the generated search query in the AppSync console. No data is returned
5. Populate the `Todo` table with sample entries.
6. Search for `Todo` data using the generated search query in the AppSync console.
7. Data is returned from OpenSearch

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Todo
  @model
  @searchable
  @auth(
    rules: [
      { allow: owner }
      { allow: public, provider: iam }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  todo: String
}

type TodoOpenSearch
  @model
  @searchable
  @auth(
    rules: [
      { allow: owner }
      { allow: public, provider: iam }
    ]
  ) {
  id: ID! @primaryKey
  owner: ID!
  todo: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sundersc** [comment]
Using overrides to change the table name for @searchable also requires the following changes.

1. Streaming lambda: The logic to determine the index name needs to be customized. This is how it computes by default.
```py
# Compute DynamoDB table, type and index for item
doc_table = ddb_table_name.lower()
doc_type = DOC_TYPE
doc_table_parts = doc_table.split('-')
doc_opensearch_index_name = doc_table_parts[0] if len(doc_table_parts) > 0  else doc_table
```
2. Resolver: index name on the resolver needs to be updated to match the index name computed in step 1.
