### ISSUE TITLE
Verify Auth Challenge Response role name is too long

### ISSUE THREAD

**Issue by RadomirPerisic** [aws-amplify/amplify-cli#9926]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I created environment called `production` and added auth with custom signup flow with and Cognito triggers. I added `Verify Auth Challenge Response` trigger and tried to push.

I get error:

CREATE_FAILED      LambdaExecutionRole                                                                                  AWS::IAM::Role             Mon Mar 07 2022 15:00:47 GMT+0100 (Central European Standard Time) 1 validation error detected: Value '****************VerifyAuthChallengeResponse-production' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: ***; Proxy: null)
CREATE_FAILED      amplify-******-production-91310-****************VerifyAuth-19IOBUHMU662B AWS::CloudFormation::Stack Mon Mar 07 2022 15:00:48 GMT+0100 (Central European Standard Time) The following resource(s) failed to create: [LambdaExecutionRole].

Total length of `Value '****************VerifyAuthChallengeResponse-production` is 68 characeters. My app name is 13 characters long

### Expected behavior

It should allow me to push changes and fix name automaticaly or allow me to set the shorter name for lambda.

### Reproduction steps

- Create a new amplify backend with name of 13 characters (that's our name length)
- Create a new environment called `production`.
- Add auth and Lambda triggers for Cognito.
- Push

```
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito Create Auth Challenge, Define Auth Challenge, Pre Sign-up, Verify Auth Challenge Response
? What functionality do you want to use for Create Auth Challenge Create your own module
? What functionality do you want to use for Define Auth Challenge Create your own module
? What functionality do you want to use for Pre Sign-up Create your own module
? What functionality do you want to use for Verify Auth Challenge Response Create your own module
```

**Comment by akshbhu** [comment]
Thanks for reporting it. I have confirmed this is a bug

**Comment by johnpc** [comment]
To avoid these types of limits, we probably shouldn't be providing a role name at all and instead letting CFN generate one for us. I'm not sure what kinds of downstream impacts a change like this will have though particularly on amplify client libraries.
