### ISSUE TITLE
Support instance profile credentials via ec2 metadata service, like aws cli

### ISSUE THREAD

**Issue by ncknuna** [aws-amplify/amplify-cli#993]
**Is your feature request related to a problem? Please describe.**
I'm attempting to run the amplify cli on a Jenkins worker, which gets its credentials from its instance profile, not from a ~/.aws/credentials or ~/.aws/config file. I can run `aws s3 ls` and other aws cli commands just fine, but when I run `amplify init`, it says "AWS access credentials can not be found."

**Describe the solution you'd like**
`amplify` should work automagically just like the aws cli :)

**Describe alternatives you've considered**
Per [these docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) I could fetch the credentials via the AWS STS API, but that's a bit of a pain.

**Comment by UnleashedMind** [comment]
If you've correctly setup your ~/.aws/credentials and ~/.aws/config files for role assumption, the Amplify CLI has the ability to assume the role, just like how that aws cli consumes a role from those two files.  check [here](https://aws-amplify.github.io/docs/cli/init#assuming-an-iam-role) for a details description.

**Comment by UnleashedMind** [comment]
If you configure your EC2 instance to use IAM roles, the Amplify CLI can automatically assume the IAM credentials for your application, eliminating the need to manually provide credentials. This can be done in two ways: 
1. If you are initializing a project, run the `amplify init` in headless mode and set the awscloudformation provider's configuration level to be `general`, see [here](https://aws-amplify.github.io/docs/cli/init#headless-usage-of-the-cli)
2. After you've already initialized a project (probably with other means for credentials), run `amplify configure project`, and when prompted, select to `remove project level configuration`.

**Comment by ncknuna** [comment]
Ah, thanks so much for clarifying! I missed the "general" configuration level setting. Marking this closed :)

**Comment by obijan42** [comment]
All the links specified above to resolve this are broken.  This is a requirement for Cloud9 setups.
