### ISSUE TITLE
Receiving `DeprecationWarning: Invalid 'main' field` for `cloudform` dependency on most Amplify commands with Node 16+

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#9939]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Upon executing an `amplify` command we receive the following error:

```
(node:52156) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/josef/.fnm/node-versions/v16.13.2/installation/pnpm-global/5/node_modules/.pnpm/amplify-provider-awscloudformation@5.9.9/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Fortunately this does not block us from proceeding with the execution.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/5033303/157471761-321bc6e1-a9e8-4bb7-a8a8-1401c67211e8.png">

Pressing the up arrow to modify the API settings duplicates the original output

<img width="771" alt="image" src="https://user-images.githubusercontent.com/5033303/157471798-62caffdc-58ae-4b13-b797-9f65b900e898.png">

**Current Workaround** is to downgrade to Node 14

### Expected behavior

no deprecationwarning error

### Reproduction steps

run any amplify command other than `amplify version`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
https://github.com/bright/cloudform/blob/master/packages/cloudform/package.json#L5

**Comment by ShariqAteeq** [comment]
+1

**Comment by konyilwin** [comment]
same here

**Comment by brgsx** [comment]
+1

**Comment by josefaidt** [comment]
Hey @dtc7240 :wave: with 7.6.24 released I've updated the workaround to downgrade to Node.js 14 `nvm use 14`

**Comment by tiffanychxn** [comment]
+1

**Comment by dtc7240** [comment]
Hey @josefaidt ... that is a MUCH better idea.  I wasn't using nvm before 😳 and now I am.  Thanks so much.

**Comment by Meadosc** [comment]
+1

**Comment by m-ricchiuti** [comment]
+1

**Comment by EvanErickson** [comment]
+1 - Node 16 LTS too. Must be a node 16 thing.

**Comment by julien-tamade** [comment]
+1 apparently node 14 doesn't work on M1 so not sure workaround will work for me

**Comment by josefaidt** [comment]
Hey folks :wave: this issue is now resolved with the release of the packaged Amplify CLI, version 8.0.0. Closing issue 🙂
