### ISSUE TITLE
`amplify pull` fails after project is found, config files found, when generated models missing

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#9941]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.2

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

pull

### Describe the bug

After creating a new project, and source controlling it. I'm having troubles pulling the backend back into a new copy of the repo.

### Expected behavior

`amplify pull` pulls my existing project down successfully

### Reproduction steps

1. I ran `amplify init`, `amplify add api` from another computer. Source controlled the files as according to the `.gitignore` that was generated. 
2. Pulling my repo down, I can see that the files in `amplify` folder have the following structure:
`.config`, `hooks`, `cli.json`, `team-provider-info.json`. 
3. When I run `amplify pull`, i can see it goes through the a few steps like renaming `amplify` to `amplify-backup`. A new `amplify` folder is created with the backend folder within it. Then it is rolled back. In the terminal I can see the following logs
```
Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/mdlaw/lawmicha/AppSyncSample.
🚫 folderNotFound: Amplify generated models not found at /AppSyncSample/amplify/generated/models
-- Recovery suggestion: Run amplify codegen models.
```

It appears the backend exists, but I can't retrieve it, I try to run `amplify codegen models` and it says (as expected)
```

      No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.
        
undefined
(node:80190) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### GraphQL schema(s)

Not sure if relevant, I'm just using the Todo from the first default choice in `amplify add api`, GraphQL, single model selection

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @lawmicha :wave: when you clone the project to the second machine, can you try running `amplify init` rather than `amplify pull` and see if that mitigates the issue?

> It appears the backend exists, but I can't retrieve it

Are you referencing the `amplify/backend` directory here, or the existing backend in AWS?

**Comment by lawmicha** [comment]
Thanks for the quick response @josefaidt, when i run `amplify init`:
```
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✖ There was an error initializing your environment.
Error: File at path: '/Users/mdlaw/lawmicha/AppSyncSample/amplify/backend/backend-config.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getBackendConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:132:17)
    at populateAmplifyMeta (/usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:113:38)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:29:7)
    at onSuccess (/usr/local/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:73:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
```

```
> amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment devtwp
Using default provider  awscloudformation
? Select the authentication method you want to use: (Use arrow keys)
❯ AWS profile 
  AWS access keys (node:82157) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/c
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
Adding backend environment devtwp to AWS Amplify app: dpcj84w819tuf
⠧ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-appsyncsample-devtwp-125236 AWS::CloudFormation::Stack Wed Mar 09 2022 12:52:39 GMT-0500 (Eastern Standard Time) User Initiated             
CREATE_IN_PROGRESS UnauthRole                          AWS::IAM::Role             Wed Mar 09 2022 12:52:43 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS AuthRole                            AWS::IAM::Role             Wed Mar 09 2022 12:52:43 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS DeploymentBucket                    AWS::S3::Bucket            Wed Mar 09 2022 12:52:43 GMT-0500 (Eastern Standard Time)                            
CREATE_IN_PROGRESS UnauthRole                          AWS::IAM::Role             Wed Mar 09 2022 12:52:44 GMT-0500 (Eastern Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                            AWS::IAM::Role             Wed Mar 09 2022 12:52:44 GMT-0500 (Eastern Standard Time) Resource creation Initiated
⠸ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Wed Mar 09 2022 12:52:45 GMT-0500 (Eastern Standard Time) Resource creation Initiated
⠴ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Wed Mar 09 2022 12:53:00 GMT-0500 (Eastern Standard Time) 
CREATE_COMPLETE AuthRole   AWS::IAM::Role Wed Mar 09 2022 12:53:01 GMT-0500 (Eastern Standard Time) 
⠧ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket                    AWS::S3::Bucket            Wed Mar 09 2022 12:53:07 GMT-0500 (Eastern Standard Time) 
CREATE_COMPLETE amplify-appsyncsample-devtwp-125236 AWS::CloudFormation::Stack Wed Mar 09 2022 12:53:09 GMT-0500 (Eastern Standard Time) 
✔ Successfully created initial AWS cloud resources for deployments.
✖ There was an error initializing your environment.
Error: File at path: '/AppSyncSample/amplify/backend/backend-config.json' does not exist
```

What i meant was i'm pretty sure the backend still exists, since `amplify pull` actually pulled in the files to create the `amplify/backend` folder structure and its contents and then later removed them. let me try to get some clearer repro steps here

**Comment by josefaidt** [comment]
Hey @lawmicha thanks for clarifying! Reading this line from the original post it appears the app we are cloning from github may not contain the backend definition

> Pulling my repo down, I can see that the files in amplify folder have the following structure:
.config, hooks, cli.json, team-provider-info.json.

When the project was originally created and pushed to git, was this an app that we pulled but selected "No" to "do you plan on modifying this backend"?

**Comment by lawmicha** [comment]
New Project repro steps
1. Create an Xcode project, so that `amplify init` detects the type of project
2. `amplify init`, ie.
```
Project information
| Name: ExistingBackend
| Environment: dev
| Default editor: Visual Studio Code
| App type: ios

```
3. `amplify add api`
```
? Select from one of the below mentioned services: GraphQL
? Here is the GraphQL API that we will create. Select a setting to edit or continue (Use arrow keys)
  Name: existingbackend 
? Here is the GraphQL API that we will create. Select a setting to edit or continue Authorization modes: API key (default, expiration time: 7 days from now)
? Choose the default authorization type for the API API key
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): 365
? Configure additional auth types? No
? Here is the GraphQL API that we will create. Select a setting to edit or continue Continue
? Choose a schema template: Single object with fields (e.g., “Todo” with ID, name, description)
```
4. `amplify push` and wait for this to finish successfully. `GraphQL transformer version: 2`
5. source control according to the generate `.gitignore`, ie. `git add .` `git push`. Note that the source controlled files under the `amplify` folder are `.config`, `backend`, `hooks`, `cli.json`, `team-provider-info.json`. This is different from my original issue and looks to be working!
6. Go to a new directory and `git clone`, the only different now is the original repo has "#current-cloud-backend` folder, and the `amplifyconfiguration.json`/ `awsconfiguration.json` files

**Comment by lawmicha** [comment]
Hi @josefaidt, I don't recall choosing that option, but if there is such an option- that might be the reason why.

**Comment by josefaidt** [comment]
Ah thanks for that information @lawmicha with the `amplify/backend/` directory checked into git, this will then allow us to clone to another directory or separate machine and run `amplify init`. This will then generate the `#current-cloud-backend` directory as well as the configuration files.

It is important to note when following this flow we are essentially copying the configuration of the resources added and configured in the original Amplify app, and the app we cloned will be treated as a new Amplify application. If we instead want to use the existing resources and create a frontend using those resources we can run `amplify pull` (without cloning the existing app) and choose "No" to "Do you plan on modifying this app?" https://docs.amplify.aws/cli/teams/multi-frontend/

**Comment by lawmicha** [comment]
The more prominent question for me is how do i retrieve the `amplifyconfiguration.json` file now in the cloned repro? I'm taking a look at `https://docs.amplify.aws/cli/start/workflows/#optional-update-projects-using-latest-amplify-cli`

**Comment by lawmicha** [comment]
Yes, I do not want to run `amplify init` to create a copy of the resources from the original app. I simply want to clone the git repo and get the backend configuration files again. Giving `amplify pull` a try

**Comment by josefaidt** [comment]
> Yes, I do not want to run amplify init to create a copy of the resources from the original app. I simply want to clone the git repo and get the backend configuration files again. Giving amplify pull a try

I've misspoken, as a quick note running `init` will actually prompt us to use the same app and env (as long as we have access to the same AWS account).

**Comment by lawmicha** [comment]
thanks @josefaidt, things are working as expected with `amplify pull`. I actually ended up selecting the app from the original issue, and choose `Yes` for `Do you plan on modifying this backend` as I won't be modifying the previous source of truth as explained in the docs:
> Choosing 'Yes' will work, however your backend definition will now be stored in two separate repositories leading to unintended consequences with multiple sources of truth.

**Comment by josefaidt** [comment]
Ah glad to hear that worked for you @lawmicha 🙌

**Comment by barshopen** [comment]
If you are following [this guide](https://amplify.aws/learn/courses/Swift-Course-70a6d/lessons/4) and you are lost because of the `folderNotFound error`, just go ahead and create the missing directories, it should work from there.
This might for others as well so I leave this comment here in case it helped anyone :)
