### ISSUE TITLE
Push Notification CLI prompts for ApiKey for FCM channel

### ISSUE THREAD

**Issue by cshfang** [aws-amplify/amplify-cli#9955]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.3

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

notifications

### Amplify Commands

add

### Describe the bug

When adding push notifications via FCM channel - the CLI prompts for an `ApiKey`. It is unclear what api key it is asking for. (It is asking for the *Server key* from FCM console)

```sh
$ amplify add notifications
? Choose the push notification channel to enable. FCM

An Amazon Pinpoint project will be created for notifications.
? Provide your pinpoint resource name:  tempt0oGF
✔ Successfully created Pinpoint project: tempt0oGF-dev

✔ Successfully set the IAM policy

? ApiKey 
```

### Expected behavior

Expected a little more clarity/guidance on what this is asking for. At the least, the terminology should be updated to `Server Key` to align with the FCM console.

### Reproduction steps

1. Add notifications
```sh
$ amplify add notifications
```
2. Select FCM as the channel to enable
3. See just a prompt for `ApiKey` with no indication what key this is asking for

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by adachishohei** [comment]
Hi all! If nobody's currently working on this issue, I'd like to take it up :)
