### ISSUE TITLE
Receiving DeprecationWarning: Invalid 'main' field for cloudform dependency on most Amplify commands with Node 17

### ISSUE THREAD

**Issue by avasa** [aws-amplify/amplify-cli#9964]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v17.7.1

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac 12.2.1 

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None. Working on a fresh install.

### Amplify Categories

custom

### Amplify Commands

status

### Describe the bug

I am currently working local. Fortunately, this does not stop the command from executing, but I get the following message when I run `amplify status`

`(node:2085) [DEP0128] DeprecationWarning: Invalid 'main' field in '/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author`

I have the following packages installed globally:

`npm -g list                                                                                                                                                                                        
/opt/homebrew/lib
├── @aws-amplify/cli@7.6.23
├── nodemon@2.0.15
├── npm@8.5.4
└── typescript@4.6.2`

### Expected behavior

I expect a clean execution without the Deprecation Warning.

### Reproduction steps

1. brew install node
2. npm install -g @aws-amplify/cli
3. amplify status

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @avasa :wave: thanks for raising this! I've marked this as a duplicate bug of https://github.com/aws-amplify/amplify-cli/issues/9939, and will be closing in favor of tracking the existing item. Please subscribe to #9939 for further updates 🙂
