### ISSUE TITLE
Deprecation warning when running `amplify init` and `amplify add api`

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/amplify-cli#9971]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.14.0

### Amplify CLI Version

7.6.23

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

Not applicable

### Amplify Commands

init, add api

### Describe the bug

When running `amplify init`, and `amplify add api`, I received the following warning:

>? Select the authentication method you want to use: (Use arrow keys)
❯ AWS profile
  AWS access keys (node:36896) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/mcafd/.nvm/versions/node/v16.14.0/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

### Expected behavior

`amplify init` / `amplify add api` should not display a deprecation warning.

### Reproduction steps

1. Run `amplify init` within a new project (I created my project using `npx create-react-app [APP NAME] --template typescript`
2. Observe warning
3. Run `amplify add api`, observe warning

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @david-mcafee :wave: thanks for raising this! Marking as a duplicate bug of https://github.com/aws-amplify/amplify-cli/issues/9939, closing in favor of tracking existing item

**Comment by david-mcafee** [comment]
> Hey @david-mcafee 👋 thanks for raising this! Marking as a duplicate bug of #9939, closing in favor of tracking existing item

Thanks @josefaidt! Sorry I missed the duplicate ticket.

**Comment by josefaidt** [comment]
No worries @david-mcafee !! I do appreciate you filing this as it helps convey the impact 🙂
