### ISSUE TITLE
Amplify pull from CI environment

### ISSUE THREAD

**Issue by umegbewe** [aws-amplify/amplify-cli#9989]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

I'm trying to pull a backend from amplify to my app in a CI environment which means I've to use the terminal
I get stuck in "- Continue in browser to log in…" 

Are there workarounds about this?

**Which Category is your question related to?**

Login

**Amplify CLI Version**

Latest

You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**

**Comment by umegbewe** [comment]
Hi @josefaidt , just trying out the ``AWSCLOUDFORMATIONCONFIG``

Here is how it looks:
```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":\"true",\
\"profileName\":\"default",\
\"accessKeyId\":\"${ACCESS_KEY_ID}\",\
\"secretAccessKey\":\"${SECRET_KEY}\",\
\"region\":\"us-east-1\"\
}"
```

I keep getting an error "Failed to fetch Amplify Studio credentials"

**Comment by josefaidt** [comment]
Hey @umegbewe thanks for clarifying! I'll try to run through this with Studio enabled on an app, however in the mean time can you try modifying this variable to not use a profile?

```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":\"false",\
\"accessKeyId\":\"${ACCESS_KEY_ID}\",\
\"secretAccessKey\":\"${SECRET_KEY}\",\
\"region\":\"us-east-1\"\
}"
```

**Comment by josefaidt** [comment]
Hey @umegbewe :wave: are you still experiencing this issue?

**Comment by umegbewe** [comment]
@josefaidt No I managed to figure it out. Thanks

**Comment by ahmedkhan1991** [comment]
I am having this same issue when trying to pull my environment. Can someone guide me? I am using amplify cli version 6.3.1 and this is what we all are using in our team. This issue has started just recently. Any suggestions?
